[LibOS] Rework futexes implementation
oscarlab/graphene pull request #1164
Opened 2019-11-25 02:39 UTC by boryspoplawski

This patch completely rewrites futex implementation to (hopefully)
remove all races (both on memory access level and between waits and
wakes), make it compatible with actual Linux implementation and make
it more maintainable and readable.

## Affected components

- [ ] README and global configuration
- [ ] Linux PAL
- [ ] SGX PAL
- [ ] FreeBSD PAL
- [ ] Common PAL code
- [ ] Library OS (i.e., SHIM), including GLIBC

## Description of the changes 
This is probably not yet ready to be merged (even after the review) as there is an issue: it seems that both `futex_list_lock` and all the per futex locks are always used (locked and unlocked) together. There are multiple ways to fix it:

1. Remove per futex locks. This will effectively leave just one lock for everything, which is what I tried to avoid with these locks in the first place. On the other hand here (unlike in the Linux kernel) we are dealing only with futexes of one process, so this might be a viable solution.
2. After acquiring a futex lock, immediately release `futex_list_lock`. This will require moving all `maybe_dequeue_futex` calls to the ends of appropriate functions and reacquiring both locks before calling it.
3. Remove `struct shim_futex` altogether. Actually this struct exists only to keep each futex wait list separately. We could remove it and keep all waiters on one list (or perhaps multiple in some hash table). This is, in a sense, similar to option 1. In favor of it: this is what the Linux kernel does (and they do it for all processes in the system!).

I'm leaning towards the 2nd option.

## How to test this PR? 
Usual test suite + you can enable `futex_wait03` in LTP in addition to what's already on. Unfortunately all tests cannot be enabled since some of them require `shm_open` and working `/proc` subsystem.
If this is to be merged, I would probably need to write some tests that LTP does not cover (at least the part graphene has enabled).

2019-11-25 19:48 UTC, yamahata requested changes
only nitpicks.
Basically it looks great refactoring/improvment.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164#-:-LuZ5tBm201Ax1bVHJMX:bhzpapq)* status: 0 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_futex.c, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuYtWvG16SR1JlCnWVH:-LuYtWvG16SR1JlCnWVI:b-qmd1w7) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L21)):*
> ```C
>  * "The futexes are also cursed."
>  * "But they come in a choice of three flavours!"
>  *                                  ~ the Linux kernel source
> ```

funny.
___
*[LibOS/shim/src/sys/shim_futex.c, line 509 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuYxxP83srFoiPTaa69:-LuYxxP83srFoiPTaa6A:b-8xg562) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L509)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>     futex2 = find_futex(uaddr2);
>     if (!futex2) {
>         spinlock_unlock(&futex_list_lock);
>         futex2 = create_new_futex(uaddr2);
>         if (!futex2) {
>             return -ENOMEM;
>         }
>         spinlock_lock(&futex_list_lock);
>         enqueue_futex(futex2);
>     }
> ```
</details>


This is repetition. introduce a helper function?
___
*[LibOS/shim/src/sys/shim_futex.c, line 580 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuYyH2E6DcbXENK3Wlj:-LuYyH2E6DcbXENK3Wlk:bmfmjdd) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L580)):*
> ```
> sizeof
> ```
 
nitpick: alignof
___
*[LibOS/shim/src/sys/shim_futex.c, line 604 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZ4HjtEELghM34KNNC:-LuZ4Hju8alAF0N2ouze:bl3jwt7) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L604)):*
> ```
> timeout < current_time
> ```

This case is allowed. (and can happen on heavy load with short timeout.)
But for now it's okay to avoid corner cases as long as test cases pass.
___
*[LibOS/shim/src/sys/shim_futex.c, line 679 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuYwIw65LoJQy23X9os:-LuYwIw65LoJQy23X9ot:b-q49pxa) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L679)):*
> ```
> _Static_assert
> ```

nitpick: use static_assert()
we'll use static_assert uniformly.
___
*[LibOS/shim/src/sys/shim_futex.c, line 726 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZ1GP75uTUD9m39BS4:-LuZ1GP75uTUD9m39BS5:brwfrwt) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L726)):*
> ```
>  sizeof
> ```
nitpick: alignof


<!-- Sent from Reviewable.io -->

2019-11-25 20:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: 0 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZEFweC1bxE-oKfMmX:-LuZEFweC1bxE-oKfMmY:bsjcsyk) (no related file):*
Blocking until we decide on issue described in the main PR description

---
___
*[LibOS/shim/src/sys/shim_futex.c, line 509 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuYxxP83srFoiPTaa69:-LuZCvFv-91yWkuqKGLI:bpb84l4) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L509)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>     futex2 = find_futex(uaddr2);
>     if (!futex2) {
>         spinlock_unlock(&futex_list_lock);
>         futex2 = create_new_futex(uaddr2);
>         if (!futex2) {
>             return -ENOMEM;
>         }
>         spinlock_lock(&futex_list_lock);
>         enqueue_futex(futex2);
>     }
> ```

This is repetition. introduce a helper function?
</blockquote></details>

This function would have tricky semantic: it needs locks taken at entry, then it would drop those locks, allocate, then acquire again, but only if allocation was successful. I decided that it will be easier to read if it's not inside a different function. I can create a helper, if you are strongly in favor of it.
___
*[LibOS/shim/src/sys/shim_futex.c, line 580 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuYyH2E6DcbXENK3Wlj:-LuZ9I95C5g9vAd1vRw8:b-uqj36y) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L580)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> sizeof
> ```
 
nitpick: alignof
</blockquote></details>

Manual explicitly asks for 4 bytes alignment, but I guess that's only because it also requires futexes to be 4-byte-ints, which would have 4 byte alignment.
Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 604 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZ4HjtEELghM34KNNC:-LuZGTXH6anIGxKBDAQF:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L604)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> timeout < current_time
> ```

This case is allowed. (and can happen on heavy load with short timeout.)
But for now it's okay to avoid corner cases as long as test cases pass.

</blockquote></details>

Fixed.
___
*[LibOS/shim/src/sys/shim_futex.c, line 679 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuYwIw65LoJQy23X9os:-LuZCeXd0gqbyCAi6sEP:bkqj465) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L679)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> _Static_assert
> ```

nitpick: use static_assert()
we'll use static_assert uniformly.
</blockquote></details>

I didn't want to include global `assert.h`, but seems we have our own version of this file.
Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 726 at r1](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZ1GP75uTUD9m39BS4:-LuZCqWY4rh2eL1cwaSg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a76e737a1a981333380f085edca2945b88fea629/LibOS/shim/src/sys/shim_futex.c#L726)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>  sizeof
> ```
nitpick: alignof
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-11-26 01:03 UTC, dimakuv requested changes
Cool PR! Needs at least one LibOS test though, to test each of the futex operations.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164#-:-Lu_Dp7L7WlrBHXO9Ud3:b-z1qjk6)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZEFweC1bxE-oKfMmX:-Lu_CtIs8hguESlOaHaS:bbg2hqf) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Blocking until we decide on issue described in the main PR description
</blockquote></details>

I would prefer Option 3. It removes a lot of complexity from futexes' implementation. Also, realistically you'd have a maximum of maybe ~100 futexes per process, so the overhead of iterating over a list of all futex-waits can't be too huge.

---
___
*[LibOS/shim/include/shim_thread.h, line 266 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZQ0dZ1AL9ZLsmgcAw:-LuZQ0dZ1AL9ZLsmgcAx:blvokjd) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L266)):*
> ```objc
>  * If this thread is already on some queue, then it *will* be woken up soon and there is no need
>  * to add it to another queue.
>  * queue->first should be a vailid pointer or WAKE_QUEUE_TAIL (i.e. cannot be NULL).
> ```

`vailid` -> `valid`
___
*[LibOS/shim/include/shim_thread.h, line 273 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZQOT-EUKpZjkr_Ijw:-LuZQOT-EUKpZjkr_Ijx:bri3esi) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L273)):*
> ```objc
>     struct wake_queue_node* qnode = &thread->wake_queue;
> 
>     /* Atomic cmp&xchg is enough, no need to take thread->lock */
> ```

`cmp&xchg` -> `cmpxchg` (a matter of preference, not blocking on this)
___
*[LibOS/shim/include/shim_thread.h, line 275 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZRtWJ7r5pBgdYgroL:-LuZRtWJ7r5pBgdYgroM:bqfwa29) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L275)):*
> ```objc
>     /* Atomic cmp&xchg is enough, no need to take thread->lock */
>     if (!__atomic_compare_exchange_n(&qnode->next, &nptr, queue->first,
>                                      1, __ATOMIC_RELAXED, __ATOMIC_RELAXED)) {
> ```

Shouldn't we use `weak = false` instead of `1` here (from the man page, "When in doubt, use the strong variation.")? In either case, I'd prefer to change `1` -> `/*weak=*/true` (or `false` is this is more correct).
___
*[LibOS/shim/include/shim_thread.h, line 279 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZS_RX-gkxXjghFc1D:-LuZS_RX-gkxXjghFc1E:b-rpauaf) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L279)):*
> ```objc
>     }
> 
>     queue->first = qnode;
> ```

Can we put a comment somewhere that this func is called with a lock so this update of the queue is properly synced?
___
*[LibOS/shim/src/sys/shim_futex.c, line 48 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZVCv485CSIQXk6XRf:-LuZVCv485CSIQXk6XRg:bu33ndt) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L48)):*
> because they could have been requeued to another futex

Could you give more info on why this can happen? Or maybe a link to a proper source.
___
*[LibOS/shim/src/sys/shim_futex.c, line 119 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZXTPE06WVv2D7tZaI:-LuZXTPE06WVv2D7tZaJ:b-kahf8u) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L119)):*
> ```C
> 
> /*
>  * The caller inherits 1 thread's refcount, which previously accounted for waiter->thread being on
> ```

This sentence is a bit weird. Maybe `Ownership of the thread is passed to the caller; we do not change its refcount because it was previously accounted for thanks to waiter->thread being on futex->waiters list.`
___
*[LibOS/shim/src/sys/shim_futex.c, line 120 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZXM3D1nzMid9lqTW6:-LuZXM3E4PueLETwLXfv:b-l8a1qr) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L120)):*
> ```C
> /*
>  * The caller inherits 1 thread's refcount, which previously accounted for waiter->thread being on
>  * futex->waiters list.
> ```

What about which locks need to be held?
___
*[LibOS/shim/src/sys/shim_futex.c, line 129 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZbojDDHZ3gxrZxzrd:-LuZbojE-j-3ADlMtJif:b-l8a1qr) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L129)):*
> ```C
> 
> /*
>  * Moves waiter from `futex1` to `futex2`.
> ```

What about which locks need to be held?
___
*[LibOS/shim/src/sys/shim_futex.c, line 197 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZdTAtBsqZAgHYFDAX:-LuZdTAtBsqZAgHYFDAY:bxp1can) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L197)):*
> ```C
> 
> /*
>  * Locks two futexes in a specifis order.
> ```

`specifis` -> `specific`. Actually, why not `in ascending order (defined by cmp_futexes)`
___
*[LibOS/shim/src/sys/shim_futex.c, line 204 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZe0Qm4dpIbKzdBFpf:-LuZe0Qm4dpIbKzdBFpg:bplzhn4) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L204)):*
> ```C
>         return;
>     } else if (futex1 && !futex2){
>         spinlock_lock(&futex1->lock);
> ```

Did you forget `return;`? How does it even work?
___
*[LibOS/shim/src/sys/shim_futex.c, line 206 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZe3e5CN9TpBmDY36Q:-LuZe3e5CN9TpBmDY36R:bplzhn4) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L206)):*
> ```C
>         spinlock_lock(&futex1->lock);
>     } else if (!futex1 && futex2) {
>         spinlock_lock(&futex2->lock);
> ```

Did you forget `return;`? How does it even work?
___
*[LibOS/shim/src/sys/shim_futex.c, line 228 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZeRLg4DbQzpWDkqOu:-LuZeRLg4DbQzpWDkqOv:bplzhn4) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L228)):*
> ```C
>         return;
>     } else if (futex1 && !futex2){
>         spinlock_unlock(&futex1->lock);
> ```

Did you forget `return;`? How does it even work?
___
*[LibOS/shim/src/sys/shim_futex.c, line 230 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZeRvMAbMVN1E1cAwX:-LuZeRvMAbMVN1E1cAwY:bplzhn4) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L230)):*
> ```C
>         spinlock_unlock(&futex1->lock);
>     } else if (!futex1 && futex2) {
>         spinlock_unlock(&futex2->lock);
> ```

Did you forget `return;`? How does it even work?
___
*[LibOS/shim/src/sys/shim_futex.c, line 262 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZf9oc0K-Al8Eef2TE:-LuZf9oc0K-Al8Eef2TF:b-r1bfbh) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L262)):*
Comment in `enqueue_futex()` says:
> Both  [...]

2019-11-26 13:29 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZEFweC1bxE-oKfMmX:-LublqAHAMDtcuEmkmqH:b-9nm101) (no related file):*
> Also, realistically you'd have a maximum of maybe ~100 futexes per process

I'm really not that sure about this. Web servers can have a lot of threads and each of them creates a few futexes just because of pthreads (AFAIK).

So, I'd rather go for either 2. option or 3. with a hashmap.

Do I understand correctly, that the only problem with 2. is that the code is more complex then?

---


<!-- Sent from Reviewable.io -->

2019-11-26 16:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: 2 of 4 files reviewed, 31 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/include/shim_thread.h, line 266 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZQ0dZ1AL9ZLsmgcAw:-LucO61-1czOoYyFHpX8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L266)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`vailid` -> `valid`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 273 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZQOT-EUKpZjkr_Ijw:-LucO7QzCXmasO8_W4qe:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L273)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`cmp&xchg` -> `cmpxchg` (a matter of preference, not blocking on this)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 275 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZRtWJ7r5pBgdYgroL:-LucOBam2bq8zjtd10em:b-p2equa) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we use `weak = false` instead of `1` here (from the man page, "When in doubt, use the strong variation.")? In either case, I'd prefer to change `1` -> `/*weak=*/true` (or `false` is this is more correct).
</blockquote></details>

Yes, this was a bug (I copy pasted it and forgot to check).
Done.
___
*[LibOS/shim/include/shim_thread.h, line 279 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZS_RX-gkxXjghFc1D:-LucOcftEmJIbgrm8J3N:bjag75k) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/include/shim_thread.h#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we put a comment somewhere that this func is called with a lock so this update of the queue is properly synced?
</blockquote></details>

But there are no locks, this queue is private to the caller (at least in current usages and actually all I can think of).
___
*[LibOS/shim/src/sys/shim_futex.c, line 48 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZVCv485CSIQXk6XRf:-LucOwka5N3xOYiDk2yr:becl978) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> because they could have been requeued to another futex

Could you give more info on why this can happen? Or maybe a link to a proper source.
</blockquote></details>

`FUTEX_REQUEUE` does that: it (potentially) requeues some waiters on one futex to another.
___
*[LibOS/shim/src/sys/shim_futex.c, line 119 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZXTPE06WVv2D7tZaI:-LucPbHLACrnoyXzAxWF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sentence is a bit weird. Maybe `Ownership of the thread is passed to the caller; we do not change its refcount because it was previously accounted for thanks to waiter->thread being on futex->waiters list.`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 120 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZXM3D1nzMid9lqTW6:-LucPcgeCRxeAYy_s_pB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about which locks need to be held?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 129 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZbojDDHZ3gxrZxzrd:-LucPdg69aKtlyZibLKk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L129)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about which locks need to be held?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 197 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZdTAtBsqZAgHYFDAX:-LucPenJ1rljSiAoW-UZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`specifis` -> `specific`. Actually, why not `in ascending order (defined by cmp_futexes)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 204 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZe0Qm4dpIbKzdBFpf:-LucPi_26l1aLAmo3__-:b9tkc8a) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you forget `return;`? How does it even work?
</blockquote></details>

It turns out that LTP  has *NO* requeue or cmp_requeue tests.
As already discussed, we need custom tests (which I'll add after committing solution to issue in PR description).
___
*[LibOS/shim/src/sys/shim_futex.c, line 206 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZe3e5CN9TpBmDY36Q:-LucPi9S0rzYvmjGiWT3:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you forget `return;`? How does it even work?
</blockquote></details>

ditto
___
*[LibOS/shim/src/sys/shim_futex.c, line 228 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZeRLg4DbQzpWDkqOu:-LucQrEHBxBzlkmyENLb:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L228)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you forget `return;`? How does it even work?
</blockquote></details>

ditto
___
*[LibOS/shim/src/sys/shim_futex.c, line 230 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZeRvMAbMVN1E1cAwX:-LucQtOj8faUvj1NiYSO:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you forget `return;`? How does it even work?
</blockquote></details>

ditto
___
*[LibOS/shim/src/sys/shim_futex.c, line 262 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZf9oc0K-Al8Eef2TE:-LucQx6aEIkbMYJhnuZ6:b-bz4y1l) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L262)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Comment in `enqueue_futex()` says:
> Both `futex_list_lock` and `futex->lock` should be held while calling this function

But here you don't take `futex->lock` (you take it only  [...]

2019-11-27 01:28 UTC, dimakuv approved these changes
Except for the discussion of locking, this PR looks good to me.

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164#-:-LueT9cC3GLpn2eIV_vF:b-hlaeg6)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/src/sys/shim_futex.c, line 262 at r3](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZf9oc0K-Al8Eef2TE:-LueSjKrAkz_yxFgXzQ2:b-hon1rd) ([raw file](https://github.com/oscarlab/graphene/blob/a822d94bbb92b72d7aafe73061930e277ffd7e92/LibOS/shim/src/sys/shim_futex.c#L262)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In general case it should be held, but here we've just created this futex, so there is no way someone got a reference to it before (hence we are the only one to use it).
Should I add a comment describing it?
</blockquote></details>

No, it's fine, I should have figured it out :)


<!-- Sent from Reviewable.io -->

2019-11-27 19:46 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2019-11-28 02:09 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-LuZEFweC1bxE-oKfMmX:-LujlDhg9hmpilpZAn3g:bpxz9c9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Also, realistically you'd have a maximum of maybe ~100 futexes per process

I'm really not that sure about this. Web servers can have a lot of threads and each of them creates a few futexes just because of pthreads (AFAIK).

So, I'd rather go for either 2. option or 3. with a hashmap.

Do I understand correctly, that the only problem with 2. is that the code is more complex then?
</blockquote></details>

I don't have a strong preference. Let's do option 2 then.

---


<!-- Sent from Reviewable.io -->

2019-11-28 02:20 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-Lujl1t9C-LtyfXo39Cx:-Lujl1tBCDP78lQJnsei:b23fud2) (no related file):*
Reminder for myself: add tests for each operation (or at least those not covered by LTP)

---


<!-- Sent from Reviewable.io -->

2019-11-29 21:54 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-Lujl1t9C-LtyfXo39Cx:-Lut8zRi-qE7TtONpaCb:bhxdk0s) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Reminder for myself: add tests for each operation (or at least those not covered by LTP)
</blockquote></details>

I'll put a blocking comment on this to prevent accidental merge of this PR

---


<!-- Sent from Reviewable.io -->

2019-12-03 15:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: 3 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-Lujl1t9C-LtyfXo39Cx:-LvBOk9b7f7VK-myXRu3:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll put a blocking comment on this to prevent accidental merge of this PR
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2019-12-03 23:21 UTC, dimakuv requested changes
Impressive!

> Reviewed 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164#-:-LvD3RDj-NHhKSoTq37y:b-1anbvh)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_futex.c, line 165 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvChdClE_DyZIY55zwP:-LvChdClE_DyZIY55zwQ:brk8y68) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/src/sys/shim_futex.c#L165)):*
> ```C
>  * If `futex` has no waiters and is on `futex_list`, takes it off that list.
>  *
>  * Neither `futex_list_lock` nor `futex->lock)` should be held while calling this,
> ```

Remove `)`
___
*[LibOS/shim/src/sys/shim_futex.c, line 921 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD3CO18pKNhIanS7Qt:-LvD3CO18pKNhIanS7Qu:btnbjbs) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/src/sys/shim_futex.c#L921)):*
> ```C
> 
>     /* We can skip all arguments validation as `clear_child_tid` is checked above. */
>     futex_wake((uint32_t*)clear_child_tid, 1, FUTEX_BITSET_MATCH_ANY);
> ```

BTW, it is interesting that the old code incorrectly woke up all waiting parent threads, even though the man page explicitly states that only one thread should be woken up. Thanks for fixing this.
___
*[LibOS/shim/test/regression/futex.manifest.template, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD2UjX10AjRl8sUmyl:-LvD2UjY3iWk4bOd-0OU:b-996ujb) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/test/regression/futex.manifest.template#L22)):*
> ```
> sgx.trusted_files.libc = file:../../../../Runtime/libc.so.6
> sgx.trusted_files.libpthread = file:../../../../Runtime/libpthread.so.0
> sgx.thread_num = 10
> ```

Can we make it 12 or 16? I understand that 10 is a tight fit (8 child threads + 1 main thread + 1 IPC thread). But soon we'll have always-on Async helper thread (recall PR https://github.com/oscarlab/graphene/pull/1171) and in the future we'll probably have say one more helper thread. So I suggest to give some slack for the number of threads.
___
*[LibOS/shim/test/regression/futex_requeue.manifest.template, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD30uRCAj8kHhtsCs_:-LvD30uS4ttfz2pOt-1E:bx105ui) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/test/regression/futex_requeue.manifest.template#L17)):*
> ```
> sgx.trusted_files.libc = file:../../../../Runtime/libc.so.6
> sgx.trusted_files.libpthread = file:../../../../Runtime/libpthread.so.0
> sgx.thread_num = 11
> ```

Can we make it 16?
___
*[LibOS/shim/test/regression/futex_wake_op.manifest.template, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD34R-2Y-f-Bq7e7LU:-LvD34R-2Y-f-Bq7e7LV:bx105ui) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/test/regression/futex_wake_op.manifest.template#L17)):*
> ```
> sgx.trusted_files.libc = file:../../../../Runtime/libc.so.6
> sgx.trusted_files.libpthread = file:../../../../Runtime/libpthread.so.0
> sgx.thread_num = 11
> ```

Can we make it 16?


<!-- Sent from Reviewable.io -->

2019-12-04 02:22 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvDh8L99IS8qH8SnJBz:-LvDh8L99IS8qH8SnJC-:b8z4ayo) (no related file):*
Does this fix #441? (I think so)
Probably also #161, but I'll need to verify.

---


<!-- Sent from Reviewable.io -->

2019-12-04 14:00 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: 9 of 13 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvDh8L99IS8qH8SnJBz:-LvGBjtoEP1WP30Sw6H5:b-25jvnf) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Does this fix #441? (I think so)
Probably also #161, but I'll need to verify.
</blockquote></details>

#441 - no, that one uses futexes from host and is not related to this PR at all
#161 - no idea, please try it :) 

---
___
*[LibOS/shim/src/sys/shim_futex.c, line 165 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvChdClE_DyZIY55zwP:-LvGBygPAEaiNkkHcWCq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/src/sys/shim_futex.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 921 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD3CO18pKNhIanS7Qt:-LvGCFk7Aq4Q_d5IFYhj:b-2jaswv) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/src/sys/shim_futex.c#L921)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, it is interesting that the old code incorrectly woke up all waiting parent threads, even though the man page explicitly states that only one thread should be woken up. Thanks for fixing this.
</blockquote></details>

I guess it's not a common case to have multiple threads waiting on `clear_child_tid`
___
*[LibOS/shim/test/regression/futex.manifest.template, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD2UjX10AjRl8sUmyl:-LvGCX6_CBODZT2mtf3n:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/test/regression/futex.manifest.template#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we make it 12 or 16? I understand that 10 is a tight fit (8 child threads + 1 main thread + 1 IPC thread). But soon we'll have always-on Async helper thread (recall PR https://github.com/oscarlab/graphene/pull/1171) and in the future we'll probably have say one more helper thread. So I suggest to give some slack for the number of threads.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_requeue.manifest.template, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD30uRCAj8kHhtsCs_:-LvGCXniBtVI89XgJJGx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/test/regression/futex_requeue.manifest.template#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we make it 16?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_wake_op.manifest.template, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvD34R-2Y-f-Bq7e7LU:-LvGCYK18eqE40sLzGBj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8731e2b1df838c56a997625be006891ed9717b84/LibOS/shim/test/regression/futex_wake_op.manifest.template#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we make it 16?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-04 16:09 UTC, boryspoplawski reviewed
Rebased on top of current master. Should be ready for final review and merge.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164#-:-LvGeiMWC7rZ8bZ4vYZl:b-cwkvic)* status: 5 of 13 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2019-12-04 18:51 UTC, dimakuv submitted a review, later dismissed
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/sys/shim_futex.c, line 908 at r6](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvHEjpy6i1pZ4FPtyaI:-LvHEjpy6i1pZ4FPtyaJ:b-cnmm0y) ([raw file](https://github.com/oscarlab/graphene/blob/015a75ee955d25ff33b5d7e017142716de50c634/LibOS/shim/src/sys/shim_futex.c#L908)):*
> ```C
> /*
>  * This function is called by Async Helper thread. It first waits for `clear_child_tid_val_pal`
>  * to be set to 0 (PAL does it when child thread finally exits). Nest, it sets `clear_child_tid`
> ```

Nit: `Nest` -> `Next`


<!-- Sent from Reviewable.io -->

2019-12-04 20:35 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2019-12-04 20:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1164#-LvDh8L99IS8qH8SnJBz:-LvHcKAZ0Rl-eK18S-MP:bymr11i) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

#441 - no, that one uses futexes from host and is not related to this PR at all
#161 - no idea, please try it :) 
</blockquote></details>

I couldn't reproduce #161 on current master, so I closed it.

---


<!-- Sent from Reviewable.io -->

2019-12-13 00:21 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-12-19 01:13 UTC, mkow requested changes
> Reviewed 1 of 4 files at r1, 4 of 10 files at r5, 7 of 8 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_futex.c, line 65 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQcacu0Higpw5yTyP_:-LwQcacvEpLnZglakGU7:bnb3rn9) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L65)):*
> ```C
> 
> static LISTP_TYPE(shim_futex) futex_list = LISTP_INIT;
> static spinlock_t futex_list_lock = INIT_SPINLOCK_UNLOCKED;
> ```

Please prefix global variables with `g_`.
___
*[LibOS/shim/src/sys/shim_futex.c, line 77 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwP865pCz02VrFyV_kM:-LwP865pCz02VrFyV_kN:b-t15hfm) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L77)):*
> ```C
> }
> 
> /* Since we distinguish futexes by their virtual address, we can as well create a total ordering
> ```

I think it would be good to mention somewhere that the current implementation is limited to current process and thus can use virtual addresses for identifying futexes.
___
*[LibOS/shim/src/sys/shim_futex.c, line 155 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQKQiuEkB-vjNjWtiZ:-LwQKQiuEkB-vjNjWti_:b994hol) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L155)):*
> ```C
> 
> static void _maybe_dequeue_futex(struct shim_futex* futex) {
>     if (LISTP_EMPTY(&futex->waiters) && !LIST_EMPTY(futex, list)) {
> ```

Why not just call `check_dequeue_futex` here?
___
*[LibOS/shim/src/sys/shim_futex.c, line 280 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQHz_oBymDeXSAKbRa:-LwQHz_oBymDeXSAKbRb:bfm9p19) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L280)):*
> ```C
> 
>     LISTP_FOR_EACH_ENTRY(futex, &futex_list, list) {
>         if (futex->uaddr == uaddr) {
> ```

You say "This lock guards every access to uaddr and waiters (above)", but here you don't have the lock taken.
___
*[LibOS/shim/src/sys/shim_futex.c, line 290 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwPHHCA7b9lX8VXYfi0:-LwPHHCB13nNuAXbm6-q:b-fkwmvq) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L290)):*
> ```C
> 
> static uint64_t timespec_to_us(const struct timespec* ts) {
>     return ts->tv_sec * 1000000u + ts->tv_nsec / 1000u;
> ```

I think `tv_sec` may be smaller than `uint64_t` (ret val type), so it may overflow on multiplication.
___
*[LibOS/shim/src/sys/shim_futex.c, line 302 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQGekTBq5LVUAOJ30g:-LwQGekU53lJSYJ3-Ufv:b-9un5fn) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L302)):*
> ```C
>     if (!futex) {
>         spinlock_unlock(&futex_list_lock);
>         futex = create_new_futex(uaddr);
> ```

What if two threads end up here with the same `uaddr`?
___
*[LibOS/shim/src/sys/shim_futex.c, line 480 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQPyhOC1oWI5ZE5uLZ:-LwQPyhOC1oWI5ZE5uL_:b7e51mq) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L480)):*
> ```C
>             oparg &= 0x1f;
>         }
>         oparg = 1 << oparg;
> ```

Isn't this a signed overflow for `oparg == 31`, which is UB?
___
*[LibOS/shim/src/sys/shim_futex.c, line 570 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQRB3p1JgFqQntNz0g:-LwQRB3qDoeoMprvmhGC:b-r0f8qh) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L570)):*
> ```C
>     bool needs_dequeue2 = false;
> 
>     if (to_wake < 0 || to_requeue < 0) {
> ```

This check is present here but not in `futex_wake_op` nor `futex_wake`. Why?
___
*[LibOS/shim/src/sys/shim_futex.c, line 578 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQX4j2B4jh0nwHJBN-:-LwQX4j30BiuDi4kw2P3:b-iwb1u8) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L578)):*
> ```C
>     if (!futex2) {
>         spinlock_unlock(&futex_list_lock);
>         futex2 = create_new_futex(uaddr2);
> ```

ditto (seems racy)
___
*[LibOS/shim/src/sys/shim_futex.c, line 642 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQ_kkg7UjIN3DTqELM:-LwQ_kkg7UjIN3DTqELN:byl73su) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L642)):*
> ```C
> 
>     return ret;
> ```

Please remove this empty line
___
*[LibOS/shim/src/sys/shim_futex.c, line 914 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQgk1-3LUZhzJ8lj7w:-LwQgk1-3LUZhzJ8lj7x:ba388us) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L914)):*
> ```C
>  *
>  * Since it is a callback to Async Helper thread, it must follow the
>  * `void (*callback) (IDTYPE caller, void * arg)` signature even though we don't use caller.
> ```

`void * arg` -> `void* arg`
___
*[LibOS/shim/test/regression/futex.c, line 41 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwKZYSABOZ9ozfmSq1R:-LwKZYSABOZ9ozfmSq1S:boxm495) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/futex.c#L41)):*
> ```C
>     setbuf(stderr, NULL);
> 
>     assert(THREADS < sizeof(int) * 8);
> ```

This could be a `static_assert`
___
*[LibOS/shim/test/regression/futex.c, line 72 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwK_-r47ZERz9rpY7s8:-LwK_-r5E9GdQE2zvcHx:b7pqq1p) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/futex.c#L72)):*
> ```C
>             }
>         } while (rv == 0);
>         printf("FUTEX_WAKE_BITSET i = %d rv = %d (expected: %d)\n", i, rv, 1);
> ```

Why not hardcoding this `1` in the format string?
___
*[LibOS/shim/test/regression/futex_requeue.c, line 77 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwKbbFP2ClvuOTa6K8t:-LwKbbFP2ClvuOTa6K8u:bg6x9lg) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/futex_requeue.c#L77)):*
> ```C
>     int ret;
> 
>     for (i = 0; i < THREADS; ++i) {
> ```

`i++` (for consistency with the rest of our codebase)
please fix this in the whole PR
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 26 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwKdoWN92uIZ-IHrHeh:-LwKdoWN92uIZ-IHrHei:by45p87) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/futex_wake_op.c#L26)):*
> ```C
> 
> static int futex_wake_op(int* uaddr1, int to_wake1, int* uaddr2, int to_wake2, int op) {
>     return futex(uaddr1, FUTEX_WAKE_OP | FUTEX_PRIVATE_FLAG, to_wake1, (struct timespec*)(unsigned long)to_wake2, uaddr2, op);
> ```

Is it intended that `uaddr2` and `to_wake2` are swapped with each other in function signature vs syscall invocation? I think it would be better to keep them in the original order.
___
*[LibOS/shim/test/regression/test_libos.py, line 265 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwNjdoJDuS_huIPvFsS:-LwNjdoK1o3oiHPdQktv:b-a2r8m5)  [...]

2019-12-19 01:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/test/regression/test_libos.py, line 265 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwNjdoJDuS_huIPvFsS:-LwQnjPH-RbmidfvInFP:bvnkikr) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/test_libos.py#L265)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The naming of this test is now inconsistent with the others, could you rename it to `futex_wake`? I guess long time ago this was the only futex test we had...
</blockquote></details>

@boryspoplawski Also please replace `stderr` with `_` because now we have a Python linter which complains on all modifications with "unused vars"
___
*[LibOS/shim/test/regression/test_libos.py, line 271 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwNjuDc8zb4JNwHWKAA:-LwQnvYsBGodcOmu1d5F:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/test_libos.py#L271)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For consistency, could you rename this test to `futex_timeout`? (underscore instead of dash)
</blockquote></details>

ditto
___
*[LibOS/shim/test/regression/test_libos.py, line 277 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQo-A872ShHUWG-kmG:-LwQo-A872ShHUWG-kmH:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/test_libos.py#L277)):*
> ```Python
> 
>     def test_042_futex_requeue(self):
>         stdout, stderr = self.run_binary(['futex_requeue'])
> ```

ditto
___
*[LibOS/shim/test/regression/test_libos.py, line 282 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQo-q32A02Lul_NCVM:-LwQo-q32A02Lul_NCVN:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/test_libos.py#L282)):*
> ```Python
> 
>     def test_043_futex_wake_op(self):
>         stdout, stderr = self.run_binary(['futex_wake_op'])
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-12-19 23:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: 5 of 13 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_futex.c, line 65 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQcacu0Higpw5yTyP_:-LwUsjiT2tOfOcTilZfO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please prefix global variables with `g_`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 77 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwP865pCz02VrFyV_kM:-LwUskVJCMCzEtVC7EIt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it would be good to mention somewhere that the current implementation is limited to current process and thus can use virtual addresses for identifying futexes.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 155 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQKQiuEkB-vjNjWtiZ:-LwUtbUpEVeRTFJxCrbs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L155)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just call `check_dequeue_futex` here?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 280 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQHz_oBymDeXSAKbRa:-LwUus8bEcJa9MompUhd:b5vu4lr) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L280)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You say "This lock guards every access to uaddr and waiters (above)", but here you don't have the lock taken.
</blockquote></details>

This was miswording in the struct description, changed it there.
___
*[LibOS/shim/src/sys/shim_futex.c, line 290 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwPHHCA7b9lX8VXYfi0:-LwUvLc38prGhna9EM5c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L290)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think `tv_sec` may be smaller than `uint64_t` (ret val type), so it may overflow on multiplication.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 302 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQGekTBq5LVUAOJ30g:-LwUwXzp3wgAQAcoQkRx:bsdb4dp) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L302)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if two threads end up here with the same `uaddr`?
</blockquote></details>

Good catch, completely missed that.
Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 480 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQPyhOC1oWI5ZE5uLZ:-LwVQzOY9cvnG5zEyYzx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L480)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this a signed overflow for `oparg == 31`, which is UB?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 570 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQRB3p1JgFqQntNz0g:-LwVD3bF1_-SNeV6Uk2r:b-104trq) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L570)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This check is present here but not in `futex_wake_op` nor `futex_wake`. Why?
</blockquote></details>

Because this is what the Linux kernel does: disallows negative values here, but treats them as equal to `1` in `futex_wake`. Don't ask me why.
___
*[LibOS/shim/src/sys/shim_futex.c, line 578 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQX4j2B4jh0nwHJBN-:-LwVCLHKAcXP9xQcGFZL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L578)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (seems racy)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 642 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQ_kkg7UjIN3DTqELM:-LwVDU7391AyB5PVpnpA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L642)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please remove this empty line
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 914 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwQgk1-3LUZhzJ8lj7w:-LwVE32J8Xe0dr9RxZZH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L914)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`void * arg` -> `void* arg`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_requeue.c, line 77 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwKbbFP2ClvuOTa6K8t:-LwVGA0dBMKXQOUMZpAP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/futex_requeue.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`i++` (for consistency with the rest of our codebase)
please fix this in the whole PR
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/futex_wake_op.c, line 26 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwKdoWN92uIZ-IHrHeh:-LwVGHDj2_x-m_RJwj8r:bv11i7r) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/futex_wake_op.c#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is it intended that `uaddr2` and `to_wake2` are swapped with each other in function signature vs syscall invocation? I think it would be better to keep them in the original order.
</blockquote></details>

Yes, this is intended. `futex` syscall has overloaded arguments depending on actual operation being done. In these helper functions I wanted to have a "sane" order of arguments.
___
*[LibOS/shim/test/regression/test_libos.py, line 265 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwNjdoJDuS_huIPvFsS:-LwVHj8UAYM_NkZWXiwM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/test/regression/test_libos.py#L265)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski Also please replace `stderr` with `_` because now we have a Python linter which complains on all modifications with "unused vars"
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 271 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwNjuDc8zb4JNwHWKAA:-LwVHjfnE3xKZ50TnhFr:b-896fix) ([raw file](https://git [...]

2019-12-19 23:33 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (`vfork_and_exec` failed, that's rare)

2019-12-19 23:35 UTC, dimakuv submitted a review, later dismissed
> Reviewed 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2019-12-20 02:15 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sys/shim_futex.c, line 290 at r7](https://reviewable.io/reviews/oscarlab/graphene/1164#-LwPHHCA7b9lX8VXYfi0:-LwW2z9r1NPV1NfZqBXN:b-x6zpup) ([raw file](https://github.com/oscarlab/graphene/blob/76663e6dd91ebd926a972f7010b7493d318e29bf/LibOS/shim/src/sys/shim_futex.c#L290)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The second cast wasn't needed, but whatever.


<!-- Sent from Reviewable.io -->

2019-12-20 04:59 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-12-20 09:44 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1164)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-12-20 09:51 UTC, merged