[LibOS] Build GCC with patched libgomp.so (OpenMP runtime library)
oscarlab/graphene pull request #1732
Opened 2020-08-01 03:25 UTC by dimakuv

## Description of the changes 

Many multi-threaded applications rely on OpenMP for efficient parallelism. Such applications link against the `libgomp.so` lib. Unfortunately, the native `libgomp.so` uses a raw `SYSCALL` instruction to issues `futex()` syscalls instead of `syscall()` Glibc wrapper (for performance reasons).

`SYSCALL` instructions are executed on hot paths of OpenMP, but they are forbidden inside SGX enclaves, so Graphene traps-and-emulates them. This is very expensive, so this commit introduces an optional `make -C LibOS gcc` to build `libgomp.so` where `SYSCALL` is replaced by direct call into Graphene, similar to how we
patch Glibc. See `openmp` LibOS regression manifest for example.

This patched `libgomp.so` significantly improves SGX performance of Machine Learning workloads like PyTorch, TensorFlow, etc.

Note that `libgomp.so` is built as part of GCC, and the build takes 30 min to 2 hours. That's why we make it optional and do not build in Jenkins.

## How to test this PR? 

`LibOS/shim/test/regression/openmp.manifest.template` contains a commented-out line to use the patched library. Manually build the patched library via `make -C LibOS gcc` (wait for it...) and uncomment this line. If you'll run `openmp.manifest.sgx` under GDB now, you'll see no SIGILLs due to SYSCALL instructions. (Without this PR, you'll see several SIGILLs on SYSCALLs.)

2020-08-20 01:22 UTC, mkow requested changes
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1732)* status: all files reviewed, 10 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Examples/pytorch/pytorch.manifest.template, line 77 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF81UzoCMOj9yj1bWJR:-MF81UzoCMOj9yj1bWJS:b27wlge) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/Examples/pytorch/pytorch.manifest.template#L77)):*
> ```
> #
> # We (somewhat arbitrarily) specify 128 threads for this workload.
> sgx.thread_num = 128
> ```

Won't this break this example on older CPUs?
___
*[Examples/pytorch/pytorch.manifest.template, line 162 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF81KvKCPujZ33lw9RP:-MF81KvKCPujZ33lw9RQ:b64ewcd) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/Examples/pytorch/pytorch.manifest.template#L162)):*
> ```
> # Graphene optionally provides patched OpenMP runtime library that runs faster
> # inside SGX enclaves (execute `make -C LibOS gcc` to generate it). Uncomment
> # the below lines to use the patched library. PyTorch's SGX perf overhead
> ```

`below lines` -> `lines below` (AFAIK "below" is not an adjective)
___
*[Examples/pytorch/pytorch.manifest.template, line 165 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8HkGk4_pqbnKr1Zd9:-MF8HkGk4_pqbnKr1ZdA:b-d4340z) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/Examples/pytorch/pytorch.manifest.template#L165)):*
> ```
> # decreases on some workloads from 25% to 8% with this patched library.
> 
> # loader.env.LD_PRELOAD = /lib/libgomp.so.1
> ```

Why do you need LD_PRELOAD here, but not in `openmp` regression test?
___
*[LibOS/Makefile, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8IS_w3OOz1DZG8zl3:-MF8IS_w3OOz1DZG8zl4:bgod342) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/Makefile#L13)):*
> ```Makefile
> GNU_MIRRORS ?= https://ftp.gnu.org/gnu/ \
> 		https://mirrors.kernel.org/gnu/ \
> 		https://mirrors.ocf.berkeley.edu/gnu/
> ```

Please don't align with tabs (either don't align at all and just indent it one level or align with spaces)
___
*[LibOS/Makefile, line 123 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8P7ENDsxKcJDUAGxu:-MF8P7ENDsxKcJDUAGxv:brmgdfl) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/Makefile#L123)):*
> ```Makefile
> # function call into Graphene. GCC is not built by default with Graphene; use `make -C LibOS gcc`
> # to build it. The resulting libgomp.so.1 is symlinked under $RUNTIME_DIR. This patched version
> # makes sense only on x86_64 platforms.
> ```

Please also mention that we'd prefer to build openmp alone, but it seems to be impossible.
___
*[LibOS/Makefile, line 127 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8J4uXDZLtbp9KVAJH:-MF8J4uY03tyI6wn-kAG:b-f4isml) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/Makefile#L127)):*
> ```Makefile
> GCC_VERSION ?= 10.2.0
> GCC_SRC = gcc-$(GCC_VERSION)
> GCC_CHECKSUM = 27e879dccc639cd7b0cc08ed575c1669492579529b53c9ff27b0b96265fa867d
> ```

`GCC_CHECKSUM` -> `GCC_HASH`
___
*[LibOS/Makefile, line 156 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8QTaFB8-e3Xa0bcAe:-MF8QO273ts7vcakZVSa:b-fzf42x) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/Makefile#L156)):*
> ```Makefile
> $(GCC_SRC)/configure: $(GCC_PATCHES) $(GCC_SRC).tar.gz
> 	$(RM) -r $(GCC_SRC)
> 	tar -xzf $(GCC_SRC).tar.gz
> ```

Please use `--touch`
___
*[LibOS/Makefile, line 156 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8Q_Vz4V62wckDr2G7:-MF8Q_Vz4V62wckDr2G8:bfmt277) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/Makefile#L156)):*
> ```Makefile
> $(GCC_SRC)/configure: $(GCC_PATCHES) $(GCC_SRC).tar.gz
> 	$(RM) -r $(GCC_SRC)
> 	tar -xzf $(GCC_SRC).tar.gz
> ```

if anything below this point fails then the target may be treated as built correctly on future Make runs
___
*[LibOS/shim/test/regression/openmp.manifest.template, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8RISX320AudlYl_NN:-MF8RISX320AudlYl_NO:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/shim/test/regression/openmp.manifest.template#L30)):*
> ```
> # Graphene optionally provides patched OpenMP runtime library that runs faster
> # inside SGX enclaves (execute `make -C LibOS gcc` to generate it). Uncomment
> # the below line to use the patched library.
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-08-20 11:15 UTC, mkow requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1732)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Examples/pytorch/pytorch.manifest.template, line 77 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF81UzoCMOj9yj1bWJR:-MFAX9H67ng19hWF74VA:b-u96tjz) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/Examples/pytorch/pytorch.manifest.template#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not sure what you mean by this. This option is just a maximum possible number of parallel threads inside the enclave (the number of TCS pages). The underlying CPU capability doesn't play a role here.
</blockquote></details>

AFAIR SGX1 has a limit of 32 TCSes, so I thought this would break on TCS allocation, but seems it works so I'm unblocking the discussion.
___
*[LibOS/Makefile, line 156 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8QTaFB8-e3Xa0bcAe:-MFAYXwW4yHV8ME6v8_p:b1o5gx3) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/Makefile#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done (via `-m`). (Also for Glibc build.) Not sure why though.
</blockquote></details>

Otherwise the target (`$(GCC_SRC)/configure`) will have some arbitrary modification time (taken from .tar), not the time when this target was being built by us. So, depending on the dates there, it may or may not cause this target to be up-to-date (after a failure of further steps).
___
*[LibOS/Makefile, line 156 at r2](https://reviewable.io/reviews/oscarlab/graphene/1732#-MF8Q_Vz4V62wckDr2G7:-MFAZjQn9RtHtcKAtix6:bc6k33h) ([raw file](https://github.com/oscarlab/graphene/blob/1ebf60706a14d1bab9557a36ec2990082959b1bb/LibOS/Makefile#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not sure how to fix this. Do you want to split into two targets and touch a dummy file as a dependency between them? (Also will need a similar fix for Glibc build.)
</blockquote></details>

No need to split I think, but instead of targeting `$(GCC_SRC)/configure` I'd target a dummy file and touch it at the end.


<!-- Sent from Reviewable.io -->

2020-08-20 19:40 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`kill12` LTP test failed, unrelated)

2020-08-23 23:57 UTC, mkow requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1732)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/Makefile, line 155 at r4](https://reviewable.io/reviews/oscarlab/graphene/1732#-MFSjn0Q29PZGRlfRjPj:-MFSjn0Q29PZGRlfRjPk:bakxwsu) ([raw file](https://github.com/oscarlab/graphene/blob/3f4e9c8bd38bf3c9a70b8beffe268f7ef0b87278/LibOS/Makefile#L155)):*
> ```
> $(GCC_SRC)/.configured
> ```

I think you should make it `.SECONDARY`? But I'm not a Make expert.


<!-- Sent from Reviewable.io -->

2020-08-24 16:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1732)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-08-24 18:44 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1732)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-24 19:32 UTC, merged