Dimakuv/pytorch multi process
oscarlab/graphene pull request #1771
Opened 2020-08-19 23:52 UTC by dimakuv

## Description of the changes 

This PR adds the Python multi-process example and fixes the bug triggered by this example (incorrect checkpointing of "directory" handles/dentries). The two commits are:

- [LibOS] Mark checkpointed dir handle and dentry as not listed. The "directory" shim_handle and its associated dentry are marked as "listed" on `getdents()`, caching the contents of the directory as a list of dentries. However, Graphene doesn't checkpoint these contents (unless they were actually opened). Previously, there was a bug of not cleaning up the "listed" state of dir dentry and associated pointers of dir shim_handle on fork/clone. This led to `getdents()` in the child process showing empty directory contents. This commit fixes this bug.

- [Examples] Add Python3 multi-process (python -> shell ->python) example. This example shows how to write manifests for multi-process applications and highlights the trick of breaking an endless loop of SGX trusted children by using symlinks. This example also stresses the FS checkpointing system of Graphene.

Fixes #1757. Closes #1736.

## How to test this PR? 

The new Python test is added to Jenkins 18.04 pipelines.

2020-08-20 16:00 UTC, mkow requested changes
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1771)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Examples/python-sh-insecure/scripts/callprocess.py, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1771#-MFBa6hbADEiE9HlZfHx:-MFBa6hbADEiE9HlZfHy:b-abwbzt) ([raw file](https://github.com/oscarlab/graphene/blob/b755d9c6841b5e4c27920c3ba084ebbbfc03236a/Examples/python-sh-insecure/scripts/callprocess.py#L5)):*
> ```Python
> import os
> RESULT = os.system('python3 scripts/helloworld.py')
> print('exit code of child process: %s' % RESULT)
> ```

`%s` -> `%d`
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 741 at r1](https://reviewable.io/reviews/oscarlab/graphene/1771#-MFBMooFBcf_SMRVdddk:-MFBMooFBcf_SMRVdddl:b-gfwdvh) ([raw file](https://github.com/oscarlab/graphene/blob/b755d9c6841b5e4c27920c3ba084ebbbfc03236a/LibOS/shim/src/bookkeep/shim_handle.c#L741)):*
> ```C
>                  * directory again in child process; mark handle to indicate no cached dentries */
>                 hdl->dir_info.buf = (void*)-1;
>                 hdl->dir_info.ptr = (void*)-1;
> ```

Why do we use -1 as an invalid pointer here instead of NULL?


<!-- Sent from Reviewable.io -->

2020-08-20 18:02 UTC, bigdata-memory commented
___
*[Examples/python-sh-insecure/Makefile, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/1771#-MFC0wU0Den-rZ86jf8h:-MFC0wU10Rj2IRK-JeDM:b-mh09av) ([raw file](https://github.com/oscarlab/graphene/blob/b755d9c6841b5e4c27920c3ba084ebbbfc03236a/Examples/python-sh-insecure/Makefile#L14)):*
> ```Makefile
> # Python constants are declared in Makefile.python
> # We want to use Python 3.6 (default on Ubuntu 18.04)
> PYTHONVERSION = python3.6
> ```

It could be more flexible to separate the version from Makefile for supporting other minor versions e.g. python3.5


<!-- Sent from Reviewable.io -->

2020-08-20 18:10 UTC, bigdata-memory commented
___
*[Examples/python-sh-insecure/scripts/callprocess.py, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1771#-MFC2cw_DlfNr5QQi9vf:-MFC2cw_DlfNr5QQi9vg:b-d1uj9i) ([raw file](https://github.com/oscarlab/graphene/blob/b755d9c6841b5e4c27920c3ba084ebbbfc03236a/Examples/python-sh-insecure/scripts/callprocess.py#L5)):*
> ```Python
> import os
> RESULT = os.system('python3 scripts/helloworld.py')
> print('exit code of child process: %s' % RESULT)
> ```

It is old style way to format string, the new style is 
```print('exit code of child process: {}'.format(RESULT))```


<!-- Sent from Reviewable.io -->

2020-08-24 16:35 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1771)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-08-25 21:25 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1771)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-25 22:09 UTC, merged