[LibOS,Pal/lib] Partially refactor slabmgr and memmgr in Pal/lib
oscarlab/graphene pull request #1776
Opened 2020-08-26 17:19 UTC by dimakuv

## Description of the changes 

In particular, this PR:
- Removes SLAB_DEBUG macros and corresponding code.
- Removes unused, commented out and outdated `realloc()` code.
- Fixes memory leak in memmgr's enlarge_mem_mgr() by removing  `__set_free_mem_area()` call.
- Fixes bug of double-free of the very first memmgr area in `destroy_mem_mgr()`.
- De-duplicates "get new memory object" code by changing `get_mem_obj_from_mgr()` to call `get_mem_obj_from_mgr_enlarge()`.
- Simplifies and improves performance of `free_mem_obj_to_mgr()` since there is no need to double-check that the object belongs to one of the memmgr's areas because we already check `memory_migrated()`.
- Fixes bug of free of wrong object in slabmgr's `destroy_slab_mgr()`.

This is a partial recreation of #1347. Unfortunately, that PR became too stale and too complicated to review and modify, so I decided to take only some of its changes/fixes and apply them in this new PR.

I plan to create another PR after this one is merged to continue with the work started in #1347.

## How to test this PR? 

Run Jenkins several times to check I didn't introduce any memory management bugs.

2020-08-26 18:48 UTC, mkow requested changes
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1776)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_malloc.c, line 140 at r1](https://reviewable.io/reviews/oscarlab/graphene/1776#-MFg30He87emipOlIS_P:-MFg30Hf9-_6fKeAjR3y:bhrcppl) ([raw file](https://github.com/oscarlab/graphene/blob/84a71a0e4963c7f31e6c076de37f0bab5f94a705/LibOS/shim/src/shim_malloc.c#L140)):*
> ```C
> EXTERN_ALIAS(calloc);
> 
> #if 0 /* Temporarily disabling this code */
> ```

How hard would be to enable this code? There's a bunch of places where having realloc could simplify code.
___
*[LibOS/shim/src/shim_malloc.c, line 195 at r1](https://reviewable.io/reviews/oscarlab/graphene/1776#-MFg3HPh91OQcIjrY8dg:-MFg3HPh91OQcIjrY8dh:b-n423ib) ([raw file](https://github.com/oscarlab/graphene/blob/84a71a0e4963c7f31e6c076de37f0bab5f94a705/LibOS/shim/src/shim_malloc.c#L195)):*
> ```C
> #endif
> {
>     if (!mem)
> ```

Why have you deleted this `if`?


<!-- Sent from Reviewable.io -->

2020-08-26 20:39 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04-apps please (`python-sh-insecure` example failed with timeout, need to look into this but let's try again)

2020-08-26 20:40 UTC, dimakuv commented
Jenkins, retest Jenkins please (`kill01` LTP test failed, known and unrelated)

2020-08-26 21:12 UTC, dimakuv commented
Jenkins, retest this please (run 2; especially interested to see if `python-sh-insecure` fails again)

2020-08-26 21:38 UTC, mkow approved these changes
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1776)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/shim_malloc.c, line 140 at r1](https://reviewable.io/reviews/oscarlab/graphene/1776#-MFg30He87emipOlIS_P:-MFgdtPi23lS_o-ChZJJ:bam5oil) ([raw file](https://github.com/oscarlab/graphene/blob/84a71a0e4963c7f31e6c076de37f0bab5f94a705/LibOS/shim/src/shim_malloc.c#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me restore this code then, but in the commented-out way. The only issue I see with this code is what to do with migrated memory, but probably just not freeing it is enough. Anyway, enabling and using `realloc()` is for a separate PR.
</blockquote></details>

Yup, I think the only problem is handling migrated memory (but I guess it can be simply `if`-ed?)


<!-- Sent from Reviewable.io -->

2020-08-26 21:54 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`blender/../../Scripts/download: Terminated`, looks like Jenkins having a bad day and very slow internet connection or smth)

2020-08-26 22:49 UTC, dimakuv commented
Jenkins, retest this please (run 3; especially interested to see if python-sh-insecure fails again)

2020-08-27 00:26 UTC, dimakuv commented
Jenkins, retest this please (run 4; especially interested to see if python-sh-insecure fails again)

2020-08-27 04:16 UTC, dimakuv commented
Jenkins, retest this please (run 5; especially interested to see if python-sh-insecure fails again)

2020-08-27 15:44 UTC, dimakuv commented
Jenkins, retest this please (run 6; everything seems good, this is the last run before final rebase)

2020-08-28 21:18 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1776)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-28 21:40 UTC, merged