[Examples] Java Blockchain demo
oscarlab/graphene pull request #1779
Opened 2020-08-28 04:42 UTC by bigdata-memory

## Description of the changes 
This patch adds a Java based Example to demonstrate the configuration of Java and its workloads.
The workload of this example is blockchain usage in Java.
it shows following functionalities:
- OpenJDK 11 support in default
- Creating and Adding Ledger entries to a blockchain
- Displaying all Ledger entries managed in the blockchain
- Verifying the integrity of this blockchain
- Tempering one block of the blockchain and verifying it
This examples is designed as flexible as possible to make it easier to reuse.

## How to test this PR
The usage is in README.md file

2020-08-31 17:36 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/.gitignore, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG47li657OEym-H1fKG:-MG4Zm9a2dDYnf-LjR5M:b-z77ljw) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/.gitignore#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Most of these entries are already covered by the upper-level gitignore file (`graphene/Examples/.gitignore`). I think the only entries needed here are:
- `*.war`
- `*.jar`
- `*_demo`
- `test/`
</blockquote></details>

My 2 cents, it could be a bit portable and convenient for user to copy this example as the base of their own project to an independent folder. I'm okay to remove that if you think it doesn't need to consider it here. thanks.


<!-- Sent from Reviewable.io -->

2020-08-31 18:00 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bzt14TgGbE2TBl1_:-MG4eXAp-9ah_O5I7voi:bjilwnw) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we separate this in different lines? Hard to read.
</blockquote></details>

I removed the ```$(RM) $(WL_PKG_NAME)``` for concise, I need to ensure the the whole command chain successful, and failed as whole if any one of those failed so please advice if there is alternative way ? thanks.


<!-- Sent from Reviewable.io -->

2020-08-31 18:57 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG48DWuDo-hvb7LPvDI:-MG4sHVv-faZl5vH32Yk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `Jenkins`? I guess you meant `Java`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 18:57 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG48QaeEKsgEbVOvq-e:-MG4sKvj8q_PR3yY_ZcN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the last three comment lines `In case of Redis...` (or modify so they reflect Java paths)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 18:57 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG493kB3PNUrigCYtiS:-MG4sO2N4t65VNmSmE7c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment on why this path is needed? If it's too hard to explain, I will be fine with no comment as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:01 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG497P48Q5WYtLCIbt7:-MG4sUcMAEACY_TpDjF8:b5weegb) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment on why this path is needed? If it's too hard to explain, I will be fine with no comment as well.
</blockquote></details>

I recall I added the mount of lib64 here for extensibility,  I'm Okay if you think I should not consider it here, thanks.


<!-- Sent from Reviewable.io -->

2020-08-31 19:02 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG49N0ZEM_FodCzhLuj:-MG4tF3F6AvcRUoC6qs3:b5zvz0z) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`copied`? I guess what you want to say is `# this example expects JDK to be installed under /opt`
</blockquote></details>

I just copied it to here so wrote it what I have done, thank you for point it out, I have corrected it here, Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:02 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG49XqP4KQcCrELE6V6:-MG4tW5f9ZIjeX1OJ40o:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment still has `6379`, please fix
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:03 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 97 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG49fmq0Zrt-4SM8Qhd:-MG4tYFb5Wm_vk7zfN0a:bwm65a) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this a default port for this Java workload? I didn't find any specific configuration/command line arguments in other places. Why is it `8080`?
</blockquote></details>

I just leave it for extensibility for reuse this template, so I removed this section here, thanks, done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:03 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG49q6FDUOiigTwqO4a:-MG4tpi94yptyllXhVCq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please modify this comment so that there is no `1024MB` and no `Redis`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:03 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG49zCf9KwIXu08wc6b:-MG4tsL59UrI0kIjzRx8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please modify this comment so that there is no `8` and no `Redis`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 118 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4A0MR2BBhb9pfkphz:-MG4tu4_5HVWF4laTXWQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please expand this comment to smth like `# This Java example creates an output file`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 123 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4AB5DDpVRDY-Mgj1X:-MG4twGkDi1nboi7sc5i:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L123)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `Redis`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4AFQCEt4dh1Y4BZPs:-MG4txhHAxGYrqgRTiFh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `Redis`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4AJP7E9c6lpKpWuiG:-MG4tz1zE3UvJWzU51nm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`libz` is not an NSS library. Could you put it in the below list `TRUSTED JDK DEPENDENCIES`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 183 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4AVnZC9jRFF-PYsvH:-MG4u0XP2Ygva5gh-Ad1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L183)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the point of this comment? Can we just delete it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 194 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4A_jzCyUbKq8BztDF:-MG4u2ac1ILeJzPilX4r:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/java.manifest.template#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove these two last lines of the comment. They talk about Redis.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4AkVe0vmMAmS4_2Md:-MG4u45l-XP5mmQqz-9n:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like `deployed`. I think `installed` is a more standard term?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:04 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4ArwT5ubnaii1BDSQ:-MG4u5y84YGVq2Qzk2c-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does `specified JDK` mean? Maybe `with native JDK`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4B23X4cdWmCiedOeR:-MG4u7Lp6SaRmXryM3I6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Strange phrasing. I suggest `# Default JDK path`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4B8Bh974AMb8Vmb69:-MG4u92M4LA668A8TGNu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Jenkins`- > `Java`? Or even `Java blockchain example`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4BL895S9HTKk1uWKE:-MG4uAiIAGxgDmcmuA29:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `on GSGX`. There is no special configuration for Graphene-SGX for the proxy, Graphene uses whatever proxy settings the system uses.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 88 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4C7a595njH19vY-IT:-MG4uED97anJKpktEmkN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `Redis`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/README.md, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4CMMp4MDmymt7PkYR:-MG4uFZd7o1SSrpuR0LD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/README.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`deployed in folder /opt` -> `installed under /opt`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/README.md, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4CZ5w0AENd6--aG4i:-MG4uGmR2dJnKooa9y_t:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/README.md#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/README.md, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4CcGkD4ZFva_optpp:-MG4uI4I2BT74juRDLNI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/README.md#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you expand `max.` -> `maximum`.
Also, typos: `you can adjust those parameter to fit...` -> `You can adjust these parameters to fit...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/README.md, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4CqIg7ichtK6Y3Mix:-MG4uJFL4Ybf5IvTwG2F:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/README.md#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please expand `max.` -> `maximum`, `num.` -> `number of threads`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:05 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/README.md, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Cwbn0Xgg9MuEAcqh:-MG4uKeL0LoqnotgYkz3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/README.md#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-31 19:10 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MG4uU6hDy7zc5XD1vCQ:b-wt76on) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is your own repo. Is there any other repo from which this workload can be downloaded?
</blockquote></details>

Yes, it is, It is forked from https://github.com/jveverka/java-examples, but it doesn't contain a demo, so I prepared the demo according to the usage and testcases of that library, the gradle script also got updated to accommodate the demo code. that's why I forked it and add the demo code upon it in my own repo.


<!-- Sent from Reviewable.io -->

2020-08-31 19:13 UTC, bigdata-memory commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Czgz8tFZjpfXq3Iw:-MG4vZOq-JrJgNUsHIcU:b-xu4ye6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is great! I'm only a bit concerned about the chosen github repo (your own repo which is a fork of https://github.com/jveverka/java-examples). I wonder if maybe we should have it under `oscarlab`?
</blockquote></details>

Yes, it is, It is forked from https://github.com/jveverka/java-examples, but it doesn't contain a demo, so I prepared the demo according to the usage and testcases of that library, the gradle script also got updated to accommodate the demo code. that's why I forked it and add the demo code upon it in my own repo with a tag for referring to.
Please advice the way I can follow up, thanks.

---


<!-- Sent from Reviewable.io -->

2020-09-01 17:31 UTC, bigdata-memory commented
___
*[Examples/java-blockchain-demo/java.manifest.template, line 81 at r2](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG5Wb0t6EEZ1msnkm8x:-MG9hHq4B7mEiCdnIpzC:b31108b) ([raw file](https://github.com/oscarlab/graphene/blob/90607f0578fec23d0547f4c3b16a3ab92d08eb47/Examples/java-blockchain-demo/java.manifest.template#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand the explanation of `realpath()`. How is this related to these lines where we mount `/opt` to be visible within Graphene? We need ti mount this path anyway...
</blockquote></details>

Yes, the realpath() of JVM returns NULL when I mount it as /opt/jdk, I didn't have chance to dig it deeper, that's why just mount /opt as a workaround. 


<!-- Sent from Reviewable.io -->

2020-09-02 19:07 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Examples/java-blockchain-demo/.gitignore, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGALZdD6zuFFnrCvDQt:-MGFCYqHD1f0JGXSIJoO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0fbc7eff302893cc0fc4a761e6dea06ddcc29d68/Examples/java-blockchain-demo/.gitignore#L7)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> *.war
> *.jar
> *~
> *.manifest
> *.manifest.sgx
> *.sig
> *.token
> pal_loader
> *_demo
> ```

Please group/sort in meaningfull order
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/java.manifest.template, line 81 at r2](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG5Wb0t6EEZ1msnkm8x:-MGFCZUE3SkQzuHcMHcZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/90607f0578fec23d0547f4c3b16a3ab92d08eb47/Examples/java-blockchain-demo/java.manifest.template#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Got it. Could we make a comment shorter please, like this:
```
# JDK should be installed into /opt; note that specifying the full installation path
# (e.g. /opt/jdk) leads to an incorrect path convertion in realpath() -- this may be a bug
# in Graphene and needs further investigation
```
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/Makefile, line 70 at r3](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGB177T-m9MjVNwuEc7:-MGFCfLW8yo9viBPRwc8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0fbc7eff302893cc0fc4a761e6dea06ddcc29d68/Examples/java-blockchain-demo/Makefile#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need this last `cd`, Make automatically goes back to the original path
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGAO90LEmw2Yz-NHiIa:-MGFBTy25QEky66Q-ikl:bcwo9zp) ([raw file](https://github.com/oscarlab/graphene/blob/0fbc7eff302893cc0fc4a761e6dea06ddcc29d68/Examples/java-blockchain-demo/README.md#L12)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

which jdk version are you using? oracle openjdk? or default one?
</blockquote></details>

It is Oracle OpenJDK 11


<!-- Sent from Reviewable.io -->

2020-09-02 19:48 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @yamahata)

___
*[Examples/java-blockchain-demo/Makefile, line 69 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFM3bI1T_uE8pHf4Uh:-MGFM3bI1T_uE8pHf4Ui:b-cyt5t8) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/Makefile#L69)):*
> ```Makefile
> 		cd $(WL_DIR)/block-chain && \
> 		gradle fatjar && \
> 		cp build/libs/block-chain-all-$(WL_PKG_VERSION).jar .. && \
> ```

Now you have a dangling `&& \`. Please remove these.
___
*[Examples/java-blockchain-demo/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGAO90LEmw2Yz-NHiIa:-MGFM8IE5_WGxZPr2A0V:b-dcdqh) ([raw file](https://github.com/oscarlab/graphene/blob/0fbc7eff302893cc0fc4a761e6dea06ddcc29d68/Examples/java-blockchain-demo/README.md#L12)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

It is Oracle OpenJDK 11
</blockquote></details>

I think Isaku wants a change in the text: `An OpenJDK...` -> `An Oracle OpenJDK 11...`


<!-- Sent from Reviewable.io -->

2020-09-02 20:23 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @yamahata)

___
*[Examples/java-blockchain-demo/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGAO90LEmw2Yz-NHiIa:-MGFUFPg4wVp6OKaZXaq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0fbc7eff302893cc0fc4a761e6dea06ddcc29d68/Examples/java-blockchain-demo/README.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think Isaku wants a change in the text: `An OpenJDK...` -> `An Oracle OpenJDK 11...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-02 20:59 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @yamahata)



<!-- Sent from Reviewable.io -->

2020-09-02 21:14 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFedzRB-IB8sMP14gS:-MGFedzRB-IB8sMP14gT:b-v8rd6w) (no related file):*
Is there any reason why oracle openjdk is chosen instead of default openjdk?
Out of curiosity. I don't know the difference.

---
___
*[Examples/java-blockchain-demo/.gitignore, line 4 at r5](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFcBs5AILmBKAwCoKQ:-MGFcBs5AILmBKAwCoKR:b-ezqamo) ([raw file](https://github.com/oscarlab/graphene/blob/91654c0798c773f789e80df595bd186c82b40f10/Examples/java-blockchain-demo/.gitignore#L4)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> *.manifest
> *.manifest.sgx
> *.sig
> *.token
> ```
</details>


This is alreay covered by root .gitignore.
___
*[Examples/java-blockchain-demo/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGAO90LEmw2Yz-NHiIa:-MGFcOof1GGZf3oODTvR:b-x2gjad) ([raw file](https://github.com/oscarlab/graphene/blob/0fbc7eff302893cc0fc4a761e6dea06ddcc29d68/Examples/java-blockchain-demo/README.md#L12)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Because default jdk has higher priority than oracle one, please mention that if default one is used, the path is different.
(It's okay to say only oracle java is tested etc.)


<!-- Sent from Reviewable.io -->

2020-09-02 23:07 UTC, mkow requested changes
> Reviewed 2 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFLf_QA09mnuij5Syz:-MGFLf_QA09mnuij5Sz-:bjvf67h) (no related file):*
I'd rename this example to `openjdk-ledger`.

---
___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MGG0DDn8Fx5HEtxukQe:b-2b95t6) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Yes, it is, It is forked from https://github.com/jveverka/java-examples, but it doesn't contain a demo, so I prepared the demo according to the usage and testcases of that library, the gradle script also got updated to accommodate the demo code. that's why I forked it and add the demo code upon it in my own repo.
</blockquote></details>

Can't we include your demo code here and apply it to the example? Or even better, just include the whole example here?

Also, I don't feel confident quietly downloading and running code from a random repo on GitHub (I mean https://github.com/jveverka/java-examples) which looks like having +/- 0 users. If we want to do such things, we need to really review the code there, because our users won't be doing this and just run this example trusting us.
___
*[Examples/java-blockchain-demo/Makefile, line 90 at r5](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGG2rhuE31XUqFbLf1l:-MGG2rhv5VWPBUYeG83e:b-qpykrs) ([raw file](https://github.com/oscarlab/graphene/blob/91654c0798c773f789e80df595bd186c82b40f10/Examples/java-blockchain-demo/Makefile#L90)):*
> ```Makefile
> # procedure measures all Java dependencies (shared libraries and trusted
> # files), measures Java code/data pages, and adds measurements in the
> # resulting manifest.sgx file (among other, less important SGX options).
> ```

`Java` -> `OpenJDK` (in all places where you mean the runtime)
___
*[Examples/java-blockchain-demo/Makefile, line 117 at r5](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFuIox1mnFkrpG5wMs:-MGFuIox1mnFkrpG5wMt:bovcevx) ([raw file](https://github.com/oscarlab/graphene/blob/91654c0798c773f789e80df595bd186c82b40f10/Examples/java-blockchain-demo/Makefile#L117)):*
> ```Makefile
> 	$(JDK_HOME)/bin/java -jar $(WL_TARGET)
> 
> .PHONY: run-gr
> ```

`run-gr` -> `run-graphene` (remember to also update the readme with this change)
___
*[Examples/java-blockchain-demo/README.md, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFN8d64Z6OpJpJRvQD:-MGFN8d64Z6OpJpJRvQE:bsiv5s5) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L1)):*
> ```Markdown
> # Java Block Chain Demo
> ```

`Java Block Chain Demo` -> `Ledger with OpenJDK`
___
*[Examples/java-blockchain-demo/README.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFNlpG0sg5DPrYrI-M:-MGFNlpG0sg5DPrYrI-N:b-fh3nn) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L3)):*
> ```
> the most popular version of Java (as of this writing, version 11)
> ```

I don't think this is true. Any source?
Also, we don't run "Java", Java is a programming language and we don't even run it's compiler in Graphene. What this example is running is OpenJDK (which is a Java interpreter + runtime) in some particular version.
___
*[Examples/java-blockchain-demo/README.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFO-0j6YwaxVjgZRr6:-MGFO-0j6YwaxVjgZRr7:b-9a91br) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L3)):*
> ```Markdown
> # Java Block Chain Demo
> 
> This directory contains the Makefile and the template manifest for the most
> ```

`the Makefile` -> `a Makefile` (same with "template")
___
*[Examples/java-blockchain-demo/README.md, line 12 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFtffZE_BeHQiavZA0:-MGFtff_D50m0WDkoQFY:b-azhw3u) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L12)):*
> ```Markdown
> 
> # Additional Prerequisites:
>     1) An OpenJDK installed in folder /opt (default: /opt/jdk)
> ```

formatting here is broken (it's formatted as a code block)
___
*[Examples/java-blockchain-demo/README.md, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFunCJBMIof1XcIi71:-MGFunCJBMIof1XcIi72:b-92ieng) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L37)):*
> ```Markdown
> 
> Notice that by default, we run Java blockchain demo configured with 8G enclave size, 2G Java maximum
> heap size and 256 SGX enclave maximum thread number, you can adjust these parameters to fit into
> ```

`number, you` -> `number. You`
___
*[Examples/java-blockchain-demo/README.md, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvFkM9lj6DCU4MJGj:-MGFvFkM9lj6DCU4MJGk:b-8eee86) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L44)):*
> ```Markdown
> make G_JAVA_XMX = <Java maximum heap size> # default: 2G
> 
> # Specify the Graphene SGX enclave capacity in Gigabytes, subject to 2^n
> ```

`subject to 2^n` -> `must be a power of 2`
___
*[Examples/java-blockchain-demo/README.md, line 47 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvKv9BoVG5gg2-1cT:-MGFvKv9BoVG5gg2-1cU:b3gnxgx) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L47)):*
> ```Markdown
> make G_SGX_SIZE = <GSGX enclave capacity> # default: 8G
> 
> # Specify the Graphene SGX maximum number of thread
> ```

`maximum number of thread` -> `maximum number of threads`
___
*[Examples/java-blockchain-demo/README.md, line 48 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvRGVAHp39QYO__Zr:-MGFvRGVAHp39QYO__Zs:b3cs1zi) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L48)):*
> ```Markdown
> 
> # Specify the Graphene SGX maximum number of thread
> make G_SGX_THREAD_NUM = <GSGX maximum number of threads> # default: 256
> ```

here and above: please remove spaces around `=`
___
*[Examples/java-blockchain-demo/README.md, line 54 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvXrLDscW5X5An74v:-MGFvXrLDscW5X5An74w:b-vuwrw9) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L54)):*
> ```Markdown
> 
> ```sh
> # clean Graphene generated files
> ```

`Graphene generated` -> `Graphene-generated`


<!-- Sent from Reviewable.io -->

2020-09-03 17:41 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: 2 of 4 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFedzRB-IB8sMP14gS:-MGJrm6E8fH2GZqFsx3E:b3dpl1k) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Is there any reason why oracle openjdk is chosen instead of default openjdk?
Out of curiosity. I don't know the difference.
</blockquote></details>

I just downloaded it and use it as workload.

---
___
*[Examples/java-blockchain-demo/.gitignore, line 4 at r5](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFcBs5AILmBKAwCoKQ:-MGJs71_AtAZHkTF96vM:bj5tlwo) ([raw file](https://github.com/oscarlab/graphene/blob/91654c0798c773f789e80df595bd186c82b40f10/Examples/java-blockchain-demo/.gitignore#L4)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> *.manifest
> *.manifest.sgx
> *.sig
> *.token
> ```

This is alreay covered by root .gitignore.
</blockquote></details>

Yes, as I explained in previous comments. the user or developer can use it as template for their own projects w/ need to add it manually. thanks.
___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MGJsuvf-KfolJjaEMuH:baxrspi) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can't we include your demo code here and apply it to the example? Or even better, just include the whole example here?

Also, I don't feel confident quietly downloading and running code from a random repo on GitHub (I mean https://github.com/jveverka/java-examples) which looks like having +/- 0 users. If we want to do such things, we need to really review the code there, because our users won't be doing this and just run this example trusting us.
</blockquote></details>

I understood your concerns, It is an external repo. I cannot copy its source directly since I try my best to avoid any potential legal/license issues. Regarding the demo, I have tried to find other alternatives, but looks no much candidates over there. the functionalities of project are handy and good to fit into our needs just for a simple demo and for users or dev. to use it as a template on their own GSGX Java project. my code is written in another form of the project's testcases, but the structure changes are not the point of this GSGX Java demo, it will make the example complicit and hard to reuse, that's why I finally decide to do this way to organize it.
___
*[Examples/java-blockchain-demo/Makefile, line 69 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFM3bI1T_uE8pHf4Uh:-MGJyFspEoRoAJkmFjiW:b-jxzg6b) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/Makefile#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have a dangling `&& \`. Please remove these.
</blockquote></details>

Thank you very much for pointing it out. 
___
*[Examples/java-blockchain-demo/README.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFO-0j6YwaxVjgZRr6:-MGK-DzxE7r0e0IvphBf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`the Makefile` -> `a Makefile` (same with "template")
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 12 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFtffZE_BeHQiavZA0:-MGK0SQK3LckmDcIwpDz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

formatting here is broken (it's formatted as a code block)
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFunCJBMIof1XcIi71:-MGK0bZA93WoD_iULdtw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`number, you` -> `number. You`
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvFkM9lj6DCU4MJGj:-MGK0iv52GptkK11gdyq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`subject to 2^n` -> `must be a power of 2`
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 48 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvRGVAHp39QYO__Zr:-MGK0ps55IBoZeh0ITyZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

here and above: please remove spaces around `=`
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 54 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvXrLDscW5X5An74v:-MGK2g9D3ZCTNSuP6FZR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Graphene generated` -> `Graphene-generated`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-03 23:18 UTC, mkow reviewed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, and @yamahata)

___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MGLEfDt1SDpBqISdvpg:bw0441p) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
> I cannot copy its source directly since I try my best to avoid any potential legal/license issues.

Ok, I see that the author didn't put any license on these files, so we can't copy it :/

Anyways, we need to take a closer look at this code before merging this PR.

Ad your patches: Could you include them in our repo (in this example directory) and apply them after unpacking the source? (or find another way to merge both things). I really don't like this dependency chain graphene-repo -> your-private-repo -> repo-of-some-random-guy-no-one-even-knows, it looks very brittle.


<!-- Sent from Reviewable.io -->

2020-09-03 23:21 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, and @yamahata)

___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MGLG3fsEKpUkIGtdvgJ:b-l7sm5b) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I cannot copy its source directly since I try my best to avoid any potential legal/license issues.

Ok, I see that the author didn't put any license on these files, so we can't copy it :/

Anyways, we need to take a closer look at this code before merging this PR.

Ad your patches: Could you include them in our repo (in this example directory) and apply them after unpacking the source? (or find another way to merge both things). I really don't like this dependency chain graphene-repo -> your-private-repo -> repo-of-some-random-guy-no-one-even-knows, it looks very brittle.
</blockquote></details>

Actually, this guy also has another repo: https://github.com/jveverka/java-11-examples - this one seems to be much better maintained and even has a quite permissive license. Any reason why we could prefer https://github.com/jveverka/java-examples?


<!-- Sent from Reviewable.io -->

2020-09-08 18:25 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFedzRB-IB8sMP14gS:-MGivZnUDPK-mIYOt9OE:bw0tmfi) (no related file):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

I just downloaded it and use it as workload.
</blockquote></details>

Yes, oracle jdk requires manual download/install as you said.
On the other hand, default one(openjdk-11-jre) can be installed as a normal ubuntu package with no hassle.

My question is, why did you bother to install oracle jdk manually? Any special/strong reason?

---


<!-- Sent from Reviewable.io -->

2020-09-08 19:57 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFedzRB-IB8sMP14gS:-MGjD7bS6qjLOXuuSGjx:bve2ui) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Yes, oracle jdk requires manual download/install as you said.
On the other hand, default one(openjdk-11-jre) can be installed as a normal ubuntu package with no hassle.

My question is, why did you bother to install oracle jdk manually? Any special/strong reason?
</blockquote></details>

I think it would be more explicit to user/dev. to reuse this example on their own project since that don't rely on specific Linux distribution they are using. it seperates the concerns to make it more portable and flexible

---
___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MGjDmi17Lv3OESGzOIN:b-yztm96) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, this guy also has another repo: https://github.com/jveverka/java-11-examples - this one seems to be much better maintained and even has a quite permissive license. Any reason why we could prefer https://github.com/jveverka/java-examples?
</blockquote></details>

It looks not specific to JDK11, the user/dev. may consider to adopt this example on other version JDKs even JDK6 to fit into their own project needs.
___
*[Examples/java-blockchain-demo/Makefile, line 69 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFM3bI1T_uE8pHf4Uh:-MGjE8-zDhP3u1Q9UbI-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/Makefile#L69)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Thank you very much for pointing it out. 
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/Makefile, line 90 at r5](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGG2rhuE31XUqFbLf1l:-MGjFMoF7QRVrJacDSf9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/91654c0798c773f789e80df595bd186c82b40f10/Examples/java-blockchain-demo/Makefile#L90)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Java` -> `OpenJDK` (in all places where you mean the runtime)
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/Makefile, line 117 at r5](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFuIox1mnFkrpG5wMs:-MGjFducBKCiq5IAqHKG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/91654c0798c773f789e80df595bd186c82b40f10/Examples/java-blockchain-demo/Makefile#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`run-gr` -> `run-graphene` (remember to also update the readme with this change)
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGAO90LEmw2Yz-NHiIa:-MGjGTzDBFQrO5p0qnEO:bvnaivn) ([raw file](https://github.com/oscarlab/graphene/blob/0fbc7eff302893cc0fc4a761e6dea06ddcc29d68/Examples/java-blockchain-demo/README.md#L12)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Because default jdk has higher priority than oracle one, please mention that if default one is used, the path is different.
(It's okay to say only oracle java is tested etc.)

</blockquote></details>

Sure, added here, thanks.
___
*[Examples/java-blockchain-demo/README.md, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFN8d64Z6OpJpJRvQD:-MGjFqdg9wfIrl-J1-E3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Java Block Chain Demo` -> `Ledger with OpenJDK`
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFNlpG0sg5DPrYrI-M:-MGjGKcl9TJCy_aq6cct:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> the most popular version of Java (as of this writing, version 11)
> ```

I don't think this is true. Any source?
Also, we don't run "Java", Java is a programming language and we don't even run it's compiler in Graphene. What this example is running is OpenJDK (which is a Java interpreter + runtime) in some particular version.
</blockquote></details>

Done.
___
*[Examples/java-blockchain-demo/README.md, line 47 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFvKv9BoVG5gg2-1cT:-MGjGhqBEvVoFyyvchsJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`maximum number of thread` -> `maximum number of threads`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-08 19:57 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: 0 of 4 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFLf_QA09mnuij5Syz:-MGjHotO8zmad0oijoBc:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd rename this example to `openjdk-ledger`.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-09-08 23:04 UTC, mkow requested changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, and @yamahata)

___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MGjwzrA5b2r8u6k8xWU:b-oivv96) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

It looks not specific to JDK11, the user/dev. may consider to adopt this example on other version JDKs even JDK6 to fit into their own project needs.
</blockquote></details>

This is just an example code, it IMO doesn't hurt to use Java 11-specific version if it's much better maintained.
Anyways, what about including your patches here and applying them during build?
___
*[Examples/java-blockchain-demo/README.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFNlpG0sg5DPrYrI-M:-MGjw_Ie2Wde8RtV4RE6:b880hyr) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L3)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now it should be "a" instead of "the".


<!-- Sent from Reviewable.io -->

2020-09-17 22:12 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: 3 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MHT4Aj22XE6FghQRN7u:b-lsjy1z) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is just an example code, it IMO doesn't hurt to use Java 11-specific version if it's much better maintained.
Anyways, what about including your patches here and applying them during build?
</blockquote></details>

IMO, the workload code is exchangeable and it looks better if it is fully separated from Graphene code base since Graphene is aimed to run unmodified applications and working without the knowledge of the code of applications as possible.
___
*[Examples/java-blockchain-demo/README.md, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/1779#-MGFNlpG0sg5DPrYrI-M:-MHT6ngV9U1m7-a5A5H2:b-886gsx) ([raw file](https://github.com/oscarlab/graphene/blob/ffda0dde160959396dfb929e148f550209b45ceb/Examples/java-blockchain-demo/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now it should be "a" instead of "the".
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2020-09-25 09:20 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1779)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Examples/java-blockchain-demo/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/1779#-MG4Bam_DTmz79yK27S1:-MI3YtBY04BClu5D5vLK:b5tcsjz) ([raw file](https://github.com/oscarlab/graphene/blob/4dd20f52997b8194684fcd8979288fb7525a2728/Examples/java-blockchain-demo/Makefile#L64)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

IMO, the workload code is exchangeable and it looks better if it is fully separated from Graphene code base since Graphene is aimed to run unmodified applications and working without the knowledge of the code of applications as possible.
</blockquote></details>

I agree with @mkow , I like the idea of including the required patches in this example and applying them. Otherwise we have way too many GitHub repositories this example depends on.


<!-- Sent from Reviewable.io -->

2020-10-12 08:54 UTC, liangshui-pts commented on Examples/openjdk-ledger/Makefile
> +#
no run-gr option found in makefile

2020-12-21 14:53 UTC, dimakuv commented
This PR seems to be stuck... @bigdata-memory Would you like to continue fixing this PR according to comments? Or should we close this PR for now?

2020-12-21 20:06 UTC, bigdata-memory commented
> This PR seems to be stuck... @bigdata-memory Would you like to continue fixing this PR according to comments? Or should we close this PR for now?

Hi @dimakuv, Yes, please close it, I may continue to improve it and submit another similar PR, Thanks.

2020-12-21 20:06 UTC, closed without merging