[LibOS] Do not recursively send KILL messages via Graphene's IPC
oscarlab/graphene pull request #1781
Opened 2020-08-28 21:37 UTC by dimakuv

## Description of the changes 

Previously, Graphene not only broadcasted the KILL_ALL message via its IPC mechanism to direct children and parent (and they broadcasted to their children and parent in turn), but also sent additional KILL messages to all processes. These additional KILL messages triggered the FINDNS/TELLNS IPC mechanism to find the corresponding PID leaders. However, FINDNS/TELLNS are sent with acknowledgements, forcing the sending thread to wait on futex. This led to segfaults/hangs due to recursive IPC (e.g., in Apache web server after user sends SIGINT to terminate the process).

This PR fixes this bug by *not* sending additional KILL messages to other processes (the process already broadcasted KILL_ALL).

## How to test this PR? 

Manually start our Apache web server example:
```sh
# without this PR
~/graphene/Examples/apache$ make start-graphene-server
./pal_loader httpd.manifest -D FOREGROUND \
        -f conf/httpd-graphene.conf \
        -C "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so" \
        -C "Listen 127.0.0.1:8001" \
        -C "ServerName 127.0.0.1" \
        -C "PidFile logs/httpd-127.0.0.1-8001.pid"
...
^C  (I pressed Ctrl-C)
*** Unexpected memory fault occurred inside PAL (PID = 11937, TID = 11938, RIP = +0x00007f70)! ***
*** Unexpected memory fault occurred inside PAL (PID = 11939, TID = 11940, RIP = +0x00007f70)! ***
*** Unexpected memory fault occurred inside PAL (PID = 11935, TID = 11936, RIP = +0x00007f70)! ***
*** Unexpected memory fault occurred inside PAL (PID = 11933, TID = 11934, RIP = +0x00007f70)! ***

# with this PR
~/graphene/Examples/apache$ make start-graphene-server
./pal_loader httpd.manifest -D FOREGROUND \
        -f conf/httpd-graphene.conf \
        -C "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so" \
        -C "Listen 127.0.0.1:8001" \
        -C "ServerName 127.0.0.1" \
        -C "PidFile logs/httpd-127.0.0.1-8001.pid"
...
^C  (I pressed Ctrl-C)
# no errors
```

2020-08-29 13:28 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1781)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 121 at r1](https://reviewable.io/reviews/oscarlab/graphene/1781#-MFuOrpTAM2bz4LbFQ6y:-MFuOrpUDTSx6AmCHo7X:b-bo897g) ([raw file](https://github.com/oscarlab/graphene/blob/7c540d7a6c9d70fb214a68d321fc5daaacfa27d2/LibOS/shim/src/ipc/shim_ipc_pid.c#L121)):*
> ```C
>         case KILL_ALL:
>             broadcast_ipc(msg, IPC_PORT_DIRCLD | IPC_PORT_DIRPRT, port);
>             ret = do_kill_proc(msgin->sender, msgin->id, msgin->signum, false);
> ```

while we're here, could you annotate name for this argument?
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 379 at r1](https://reviewable.io/reviews/oscarlab/graphene/1781#-MFuOutNEdr87j32H_uN:-MFuOutNEdr87j32H_uO:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7c540d7a6c9d70fb214a68d321fc5daaacfa27d2/LibOS/shim/src/sys/shim_sigaction.c#L379)):*
> ```C
>          * has permission to send, which means all processes in Graphene. */
>         ipc_pid_kill_send(cur->tid, /*target=*/0, KILL_ALL, sig);
>         return do_kill_proc(cur->tid, cur->tgid, sig, false);
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-08-31 11:21 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1781)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_sigaction.c, line 379 at r2](https://reviewable.io/reviews/oscarlab/graphene/1781#-MG3Eh374RmbuwuRdLox:-MG3Eh374RmbuwuRdLoy:b-pas73j) ([raw file](https://github.com/oscarlab/graphene/blob/365f8ba550f92bdb2533d1ed630f72c582dd6855/LibOS/shim/src/sys/shim_sigaction.c#L379)):*
> ```C
>          * has permission to send, which means all processes in Graphene. */
>         ipc_pid_kill_send(cur->tid, /*target=*/0, KILL_ALL, sig);
>         return do_kill_proc(cur->tid, cur->tgid, sig, /*use_ipc=*/false);
> ```

Unrelated to this PR, but could you add a note here, that Linux does not kill (deliver signal to) the process issuing `kill(-1, ...)`?


<!-- Sent from Reviewable.io -->

2020-08-31 11:44 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1781)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-08-31 15:38 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1781)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-08-31 15:55 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`kill01` LTP test failed, known problem)

2020-08-31 16:27 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1781)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-08-31 17:36 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1781)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-31 18:08 UTC, merged