New GSC command to build Docker image with Graphene runtime
oscarlab/graphene pull request #1785
Opened 2020-08-31 20:50 UTC by vahldiek

## Description of the changes 

Previous iterations of GSC always build the Graphene runtime as part of the `gsc build` command. This PR allows to extract the compilation of the Graphene runtime from the `gsc build` command into a separate command called `gsc build-graphene`. Using `gsc build-graphene`, one can prepare a Docker image that includes the required runtime files for a `gsc build` command. 

The purpose of this separation is to make it possible to pre-publish Graphene Docker images for special environments such as a cloud provider's installation characteristics. This simplifies the configuration parameters for the user, since they only have to specify the Graphene Docker image name instead of the Graphene repository and Driver details. 

## How to test this PR? 

Testing is integrated into the Jenkins pipeline Linux-SGX-gsc and included in `Tools/gsc/test/Makefile`. Outside of Jenkins, run the following two commands to first, build required images and second, run tests.

```sh
cd Tools/gsc/test
make gsc-ubuntu18.04-python3-base
make test MAXTESTNUM=2 IMAGE_SUFFIX=-base
```

2020-09-01 17:11 UTC, dimakuv commented
Jenkins, test this please

2020-09-03 00:22 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: 2 of 6 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9YYqv2Ev_9ZHDmmy8:-MGGK1pP4ipxz3OO-i-l:b-pfcon7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For final rebase: the current commit message is too vague. Need to copy-paste the PR description (with minor changes) to explain what happens in this commit.
</blockquote></details>

Tried my best....

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9efGjDJUqdPOusQhp:-MGG5RUsANjSTfMOk_GP:b-11um62) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Documentation failed:
```
Warning, treated as error:
/home/jenkins/workspace/docs-18.04/Documentation/manpages/gsc.rst:206:Duplicate explicit target name: "cmdoption-gsc-sign-image-arg-IMAGE-NAME".
Makefile:22: recipe for target 'html' failed
```
</blockquote></details>

I cannot reproduce this error locally, but think to have found the culprit. 

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9kzZR0t-8g3ZtfqW3:-MGG72rZ610ct-F-iPVz:b-5o2xjb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

GSC pipeline also failed:
```
echo "Building Graphene image graphene-ubuntu18.04..."
Building Graphene image graphene-ubuntu18.04...
cd .. && ./gsc build-graphene -L --rm --no-cache graphene-ubuntu18.04-d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef
Building Graphene image graphene-ubuntu18.04-d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/build?t=graphene-ubuntu18.04-d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef&q=False&nocache=True&rm=True&forcerm=False&pull=False&dockerfile=Dockerfile.build

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "./gsc.py", line 379, in main
    return args.command(args)
  File "./gsc.py", line 271, in gsc_build_graphene
    rm=args.rm, nocache=args.no_cache, buildargs=buildargs_dict)
  File "./gsc.py", line 177, in build_docker_image
    for chunk in stream:
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 354, in _stream_helper
    yield self._result(response, json=decode)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile.build")
Makefile:73: recipe for target 'graphene-ubuntu18.04' failed
make[1]: *** [graphene-ubuntu18.04] Error 1
make[1]: Leaving directory '/home/jenkins/workspace/graphene-sgx-gsc/Tools/gsc/test'
Makefile:20: recipe for target 'all' failed
make: *** [all] Error 1
```
</blockquote></details>

Done. Sorry, I was running of a non-clean build environment. Should work now. (also the cleaning of runtime folders)

---
___
*[Documentation/manpages/gsc.rst, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9_8sx23Jfd1PDKHmR:-MGG7MBa0Y36Ex4a7Voz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you should somehow explain here that this command either builds Graphene as well or can use the prebuilt Graphene image.
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 99 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9ZywjAdJEDxu1U0Sf:-MGG7NX_9PPwZlTsBp3r:b1d911c) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this ignored if we pull the graphene image?
</blockquote></details>

It will likely break, if the prebuild image is non-debug and you're asking for a graphenized Debug image. The Docker build command includes copying a couple of runtime script which only exists if you build Graphene with debug enabled.
___
*[Documentation/manpages/gsc.rst, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9_2t69z_eW8QEqDE3:-MGG7gqkAeuTuf3uPQPr:b-g6urjn) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this ignored if we pull the graphene image?
</blockquote></details>

Yes. And like `-d` may break the `gsc build` due to missing files in the underlying image.
___
*[Documentation/manpages/gsc.rst, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9ZXFQ7lRKlop4_1jH:-MGG7tuP2ZCZTqn9PDoX:b-edfxpq) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is there any point in this option now? Isn't it completely subsumed by `gsc build-graphene`?

I don't want to have many ways of doing the same thing, it's confusing.
</blockquote></details>

Should have been removed.
___
*[Documentation/manpages/gsc.rst, line 168 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9Z7Rd7LQI0wGSxX0v:-MGG8Amt7XMAEl3RTxBK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe `build Graphene-only ...` or `build base Graphene ...`? The user may be confused and not realize that it *only* builds Graphene and that it is only a preparation step for the actual app build.
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9ZM2e4BJceogKgMZh:-MGG8CQK1qY9F-P8MEwu:b5cw8l9) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need `Graphene sources`? Isn't just runtime stuff enough?
</blockquote></details>

Yes runtime would be enough, but this build here is additive, such that the sources are there anyways. We could prune it already as part of this step. The actual copy happens during `gsc build` which picks only the parts it needs.
___
*[Documentation/manpages/gsc.rst, line 173 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9_KYjEYgFeWJfXKIy:-MGG8SvJDCP709sa8boD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/D [...]

2020-09-03 13:42 UTC, mkow commented
Jenkins, retest Jenkins-SGX-gsc please

2020-09-03 14:08 UTC, mkow requested changes
> Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vahldiek)

___
*[Documentation/manpages/gsc.rst, line 278 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9_vmM5mA65ANb7whW:-MGJE4lyDFhrHGYt7dIm:be79wdw) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L278)):*
> ```
> for popular cloud-provider offerings such as cloud provider offerings
> ```

That doesn't sound good ;)
___
*[Tools/gsc/gsc.py, line 194 at r2](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGJEmo9ANiymAFCd1pK:-MGJEmo9ANiymAFCd1pL:bkvqvih) ([raw file](https://github.com/oscarlab/graphene/blob/aeba8fe54d5beba776234ac37cf8cbf9b34f2369/Tools/gsc/gsc.py#L194)):*
> ```Python
>             # from environment
>             if item in os.environ:
>                 buildargs_dict[item] = os.environ[item]
> ```

Please error out in the other case instead of silently ignoring such an invalid option.
___
*[Tools/gsc/test/Makefile, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9cXpQ0kqSG6-dmOgJ:-MGJHRkf9SzbwmuvyQRs:b-npdwr) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Tools/gsc/test/Makefile#L78)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Strictly speaking it is not necessary, because all `sed` commands pull from the config.yaml.template. I found it more convenient, if the non-prebuild state is put back after testing. I have no concerns changing it, if this is preferred.
</blockquote></details>

I also don't like the current hackery.
___
*[Tools/gsc/test/Makefile, line 192 at r2](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGJHfd_DwvtbzFHKwK5:-MGJHfda6PPMjajly6Rb:b-272pol) ([raw file](https://github.com/oscarlab/graphene/blob/aeba8fe54d5beba776234ac37cf8cbf9b34f2369/Tools/gsc/test/Makefile#L192)):*
> ```Makefile
> 
> .PHONY: clean-gsc-base
> # TODO: Add distributions to image names
> ```

What do you mean exactly? Aren't you already doing this in `$(addprefix clean-image-gsc-, $(DISTRIBUTIONS)`?


<!-- Sent from Reviewable.io -->

2020-09-03 14:10 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vahldiek)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9kzZR0t-8g3ZtfqW3:-MGJIJ4R3WCxl8ucg26_:bkckys1) (no related file):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Done. Sorry, I was running of a non-clean build environment. Should work now. (also the cleaning of runtime folders)
</blockquote></details>

Still failing:

```
docker image rm -f gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369
Error: No such image: gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369
docker image rm -f gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369-unsigned
Error: No such image: gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369-unsigned
```

---


<!-- Sent from Reviewable.io -->

2020-09-03 14:39 UTC, vahldiek commented
___
*[Tools/gsc/gsc.py, line 194 at r2](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGJP9bb4gLtQNL9gw0_:-MGJP9bb4gLtQNL9gw0a:b-7nplse) ([raw file](https://github.com/oscarlab/graphene/blob/aeba8fe54d5beba776234ac37cf8cbf9b34f2369/Tools/gsc/gsc.py#L194)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> tract_build_args(args): ⋯ expand 7 lines
>             # user specified a --build-arg flag with key and without value, let's retrieve value
>             # from environment
>             if item in os.environ:
>                 buildargs_dict[item] = os.environ[item]
> ```
</details>



<!-- Sent from Reviewable.io -->

2020-09-03 16:05 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: 3 of 6 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9kzZR0t-8g3ZtfqW3:-MGJd3HE2l0U4P3x6-uR:b-1f1wbw) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still failing:

```
docker image rm -f gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369
Error: No such image: gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369
docker image rm -f gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369-unsigned
Error: No such image: gsc-ubuntu18.04-python3-base-aeba8fe54d5beba776234ac37cf8cbf9b34f2369-unsigned
```
</blockquote></details>

Found a couple more issues with the cleanup. Locally I don't see any error messages.

---
___
*[Documentation/manpages/gsc.rst, line 278 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9_vmM5mA65ANb7whW:-MGJP5-o8-XBOlCEy5sX:b499q7j) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L278)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> for popular cloud-provider offerings such as cloud provider offerings
> ```

That doesn't sound good ;)
</blockquote></details>

Changed
___
*[Tools/gsc/gsc.py, line 194 at r2](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGJEmo9ANiymAFCd1pK:-MGJd0XzBL6mmT6ARFi-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aeba8fe54d5beba776234ac37cf8cbf9b34f2369/Tools/gsc/gsc.py#L194)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please error out in the other case instead of silently ignoring such an invalid option.
</blockquote></details>

Done.
___
*[Tools/gsc/test/Makefile, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9cXpQ0kqSG6-dmOgJ:-MGJdFuQ3Bopnx3BU4jo:b-wnfmk9) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Tools/gsc/test/Makefile#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I also don't like the current hackery.
</blockquote></details>

Done. Removed.
___
*[Tools/gsc/test/Makefile, line 192 at r2](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGJHfd_DwvtbzFHKwK5:-MGJO_ZMAbA7BDd5Hc5n:b-ea01f8) ([raw file](https://github.com/oscarlab/graphene/blob/aeba8fe54d5beba776234ac37cf8cbf9b34f2369/Tools/gsc/test/Makefile#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean exactly? Aren't you already doing this in `$(addprefix clean-image-gsc-, $(DISTRIBUTIONS)`?
</blockquote></details>

Yes, forgot to remove.


<!-- Sent from Reviewable.io -->

2020-09-03 17:41 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vahldiek)

___
*[Documentation/manpages/gsc.rst, line 99 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9ZywjAdJEDxu1U0Sf:-MGJxXaKDZBB2pOWizNI:b-28aafn) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L99)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

It will likely break, if the prebuild image is non-debug and you're asking for a graphenized Debug image. The Docker build command includes copying a couple of runtime script which only exists if you build Graphene with debug enabled.
</blockquote></details>

Can we add a suffix to the description of this option then? Like `...PAL (do not mix with "gsc build-graphene")`
___
*[Documentation/manpages/gsc.rst, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9_2t69z_eW8QEqDE3:-MGJy6fS2cHL2YzMMDpu:b-28aafn) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L103)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Yes. And like `-d` may break the `gsc build` due to missing files in the underlying image.
</blockquote></details>

Can we add a suffix to the description of this option then? Like `...PAL (do not mix with "gsc build-graphene")`
___
*[Documentation/manpages/gsc.rst, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9ZM2e4BJceogKgMZh:-MGK1WK7CmnM8xI3qFU9:bbz3el2) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L171)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Yes runtime would be enough, but this build here is additive, such that the sources are there anyways. We could prune it already as part of this step. The actual copy happens during `gsc build` which picks only the parts it needs.
</blockquote></details>

Ok, I'm fine with this.
___
*[Documentation/manpages/gsc.rst, line 93 at r3](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGJx9uB1Wf9zJN81lHR:-MGJx9uB1Wf9zJN81lHS:b-bea61b) ([raw file](https://github.com/oscarlab/graphene/blob/7fac9055fde8df2708bfe6a7420e5542acfd4a60/Documentation/manpages/gsc.rst#L93)):*
> ```reStructuredText
> 
> Builds an unsigned graphenized Docker image of an application image called
> ``gsc-<IMAGE-NAME>-unsigned`` by compiling Graphene or relying on a prebuild
> ```

`prebuilt` (what's the deal with you and the verb "build"? :)))
___
*[Tools/gsc/gsc.py, line 262 at r3](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK29nT5Vtv2uOXV2-j:-MGK29nU2QUR8356WbHq:bwpxwgt) ([raw file](https://github.com/oscarlab/graphene/blob/7fac9055fde8df2708bfe6a7420e5542acfd4a60/Tools/gsc/gsc.py#L262)):*
> ```Python
>     # Building Graphene should never be done on a base Image of Graphene
>     if 'Image' in config['Graphene']:
>         print('The Configuration Conflict: `gsc build-graphene` does not allow `Graphene.Image` '
> ```

`The Configuration Conflict` sounds like a cool name for a movie :) Can we replace with `Configuration error: ...`
___
*[Tools/gsc/test/Makefile, line 83 at r3](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK2f3r280sw9F-w1lA:-MGK2f3r280sw9F-w1lB:b-w9441q) ([raw file](https://github.com/oscarlab/graphene/blob/7fac9055fde8df2708bfe6a7420e5542acfd4a60/Tools/gsc/test/Makefile#L83)):*
> ```Makefile
> 	sed -e 's/Distro: \".*\"/Distro: \"$*\"/' \
> 		    -e 's/Branch: \"master\"/Image: \"graphene-$*$(IMAGE_SUFFIX)\"/' \
> 			../config.yaml.template > ../config.yaml
> ```

How does it work now? Now you re-write `config.yaml` and leave it like that. Is this fine?


<!-- Sent from Reviewable.io -->

2020-09-03 17:42 UTC, dimakuv commented
Jenkins, test this please

2020-09-03 18:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vahldiek)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK7os59cVpDM-Z9Srs:-MGK7os59cVpDM-Z9Srt:btmemio) (no related file):*
More stuff fails on Jenkins:
```
+ make test MAXTESTNUM=3 TESTCASES=python3 python3-trusted-args DISTRIBUTIONS=ubuntu18.04 IMAGE_SUFFIX=-7fac9055fde8df2708bfe6a7420e5542acfd4a60
echo "Testing ubuntu18.04."
Testing ubuntu18.04.
for t in 1 2 3; do \
	printf "${t}/3: "; \
	make test-${t}-ubuntu18.04 || exit 1; \
	printf "[SUCCESS]\\n"; \
done
1/3: make[1]: Entering directory '/home/jenkins/workspace/graphene-sgx-gsc/Tools/gsc/test'
docker run  --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-python3-7fac9055fde8df2708bfe6a7420e5542acfd4a60 -c 'print("HelloWorld!")' 2>&1 | tee out
+ [ -z  ]
+ GSC_PAL=Linux-SGX
+ executable=python3
+ /graphene/signer/pal-sgx-get-token -output python3.token -sig python3.sig
...
Traceback (most recent call last):
  File "/graphene/signer/pal-sgx-get-token", line 207, in <module>
    sys.exit(main())
  File "/graphene/signer/pal-sgx-get-token", line 199, in main
    token = connect_aesmd(attr)
  File "/graphene/signer/pal-sgx-get-token", line 122, in connect_aesmd
    raise Exception("Failed. (Error Code = %d)" % (ret_msg.ret.error))
Exception: Failed. (Error Code = 30)
grep -q "HelloWorld!" out
Makefile:105: recipe for target 'test-1-ubuntu18.04' failed
make[1]: *** [test-1-ubuntu18.04] Error 1
make[1]: Leaving directory '/home/jenkins/workspace/graphene-sgx-gsc/Tools/gsc/test'
Makefile:95: recipe for target 'test-distro-ubuntu18.04' failed
make: *** [test-distro-ubuntu18.04] Error 1
```

---


<!-- Sent from Reviewable.io -->

2020-09-03 18:05 UTC, vahldiek commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK7os59cVpDM-Z9Srs:-MGK8A3U6aCw3TLzgKoG:bjhh2mo) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

More stuff fails on Jenkins:
```
+ make test MAXTESTNUM=3 TESTCASES=python3 python3-trusted-args DISTRIBUTIONS=ubuntu18.04 IMAGE_SUFFIX=-7fac9055fde8df2708bfe6a7420e5542acfd4a60
echo "Testing ubuntu18.04."
Testing ubuntu18.04.
for t in 1 2 3; do \
	printf "${t}/3: "; \
	make test-${t}-ubuntu18.04 || exit 1; \
	printf "[SUCCESS]\\n"; \
done
1/3: make[1]: Entering directory '/home/jenkins/workspace/graphene-sgx-gsc/Tools/gsc/test'
docker run  --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-python3-7fac9055fde8df2708bfe6a7420e5542acfd4a60 -c 'print("HelloWorld!")' 2>&1 | tee out
+ [ -z  ]
+ GSC_PAL=Linux-SGX
+ executable=python3
+ /graphene/signer/pal-sgx-get-token -output python3.token -sig python3.sig
...
Traceback (most recent call last):
  File "/graphene/signer/pal-sgx-get-token", line 207, in <module>
    sys.exit(main())
  File "/graphene/signer/pal-sgx-get-token", line 199, in main
    token = connect_aesmd(attr)
  File "/graphene/signer/pal-sgx-get-token", line 122, in connect_aesmd
    raise Exception("Failed. (Error Code = %d)" % (ret_msg.ret.error))
Exception: Failed. (Error Code = 30)
grep -q "HelloWorld!" out
Makefile:105: recipe for target 'test-1-ubuntu18.04' failed
make[1]: *** [test-1-ubuntu18.04] Error 1
make[1]: Leaving directory '/home/jenkins/workspace/graphene-sgx-gsc/Tools/gsc/test'
Makefile:95: recipe for target 'test-distro-ubuntu18.04' failed
make: *** [test-distro-ubuntu18.04] Error 1
```
</blockquote></details>

This looks again like AESMD failed, I think

---


<!-- Sent from Reviewable.io -->

2020-09-03 18:14 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: 4 of 6 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Documentation/manpages/gsc.rst, line 99 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9ZywjAdJEDxu1U0Sf:-MGK40HK5ENy8iWBaMWm:b-jzms3l) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add a suffix to the description of this option then? Like `...PAL (do not mix with "gsc build-graphene")`
</blockquote></details>

I've added a comment that it should only be applied when prebuilt image supports it. Same for the `gsc build-graphene` command.
___
*[Documentation/manpages/gsc.rst, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9_2t69z_eW8QEqDE3:-MGK4wZC3ct-622u3mgN:b-i6pjzn) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Documentation/manpages/gsc.rst#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add a suffix to the description of this option then? Like `...PAL (do not mix with "gsc build-graphene")`
</blockquote></details>

like `-d`
___
*[Documentation/manpages/gsc.rst, line 93 at r3](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGJx9uB1Wf9zJN81lHR:-MGK3aqk0kFrNkNdS3fu:bodm4ge) ([raw file](https://github.com/oscarlab/graphene/blob/7fac9055fde8df2708bfe6a7420e5542acfd4a60/Documentation/manpages/gsc.rst#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`prebuilt` (what's the deal with you and the verb "build"? :)))
</blockquote></details>

Sorry, Done. For some reason it doesn't go into my head...
___
*[Tools/gsc/gsc.py, line 262 at r3](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK29nT5Vtv2uOXV2-j:-MGK5B013QvW19IVadXa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7fac9055fde8df2708bfe6a7420e5542acfd4a60/Tools/gsc/gsc.py#L262)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`The Configuration Conflict` sounds like a cool name for a movie :) Can we replace with `Configuration error: ...`
</blockquote></details>

Done.
___
*[Tools/gsc/test/Makefile, line 83 at r3](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK2f3r280sw9F-w1lA:-MGK5D-yCzMj5yHcXjdZ:b2eacf0) ([raw file](https://github.com/oscarlab/graphene/blob/7fac9055fde8df2708bfe6a7420e5542acfd4a60/Tools/gsc/test/Makefile#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How does it work now? Now you re-write `config.yaml` and leave it like that. Is this fine?
</blockquote></details>

Yes, because all sed commands (in this makefile) always pull from config.yaml.template and change the values they need.


<!-- Sent from Reviewable.io -->

2020-09-03 18:14 UTC, vahldiek commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK7os59cVpDM-Z9Srs:-MGKAO4N6clC8PBdMrhZ:b-3p8tgd) (no related file):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

This looks again like AESMD failed, I think
</blockquote></details>

I'll send an Email to david.

---


<!-- Sent from Reviewable.io -->

2020-09-03 18:43 UTC, vahldiek commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK7os59cVpDM-Z9Srs:-MGKGt8B8ec7cRPO6ENX:bs4u67b) (no related file):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

I'll send an Email to david.
</blockquote></details>

Send and responded that he will restart AESMD. (so maybe in a few hours or so you can rerun Jenkins)

---


<!-- Sent from Reviewable.io -->

2020-09-03 22:30 UTC, dimakuv commented
Jenkins, test this please

2020-09-03 22:31 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @vahldiek)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK7os59cVpDM-Z9Srs:-MGL4xYe2TwjO-UzwYvz:b-5nhe7k) (no related file):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Send and responded that he will restart AESMD. (so maybe in a few hours or so you can rerun Jenkins)
</blockquote></details>

I restarted Jenkins, let's see.

---


<!-- Sent from Reviewable.io -->

2020-09-03 22:44 UTC, mkow requested changes
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vahldiek)

___
*[Tools/gsc/test/Makefile, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9cXpQ0kqSG6-dmOgJ:-MGL8-3H7SPr4P4DhzLJ:b-huutoh) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Tools/gsc/test/Makefile#L78)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Done. Removed.
</blockquote></details>

What we meant was to create another config instead of modifying another one with `sed`.


<!-- Sent from Reviewable.io -->

2020-09-03 23:54 UTC, vahldiek commented
___
*[Tools/gsc/test/Makefile, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9cXpQ0kqSG6-dmOgJ:-MGLNCj42ltC0fCxuwWF:bvfndgl) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Tools/gsc/test/Makefile#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What we meant was to create another config instead of modifying another one with `sed`.
</blockquote></details>

Config file has a fixed name (`config.yaml`). Do you want me to implement variable configuration namnig? Just to clarify, this sed command will create a new config from the template with the correct parameters. The only alternative I see is that we allow `gsc build` to only work with an image. Then the sequence would be docker pull graphene/gsc build-graphene, gsc build, gsc sign-image. In that case the configuration file would always include an image name and hence, we would not require a second sed command.


<!-- Sent from Reviewable.io -->

2020-09-04 01:08 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vahldiek)

___
*[Tools/gsc/test/Makefile, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9cXpQ0kqSG6-dmOgJ:-MGLdMbV4_qdBWokVvqr:b-y021k8) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Tools/gsc/test/Makefile#L78)):*
> this sed command will create a new config from the template with the correct parameters

Hmm, but another target here uses exactly the same file, but outputs a different thing there? I think this will break when someone calls Make in parallel mode (-jN).

> The only alternative I see is that we allow gsc build to only work with an image.

I like this solution, we wouldn't have 2 alternative ways GSC could be used, which should be less confusing for users. But parametrizing config name would also be acceptable IMO.


<!-- Sent from Reviewable.io -->

2020-09-05 16:25 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: 3 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vahldiek)

___
*[Tools/gsc/test/Makefile, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9cXpQ0kqSG6-dmOgJ:-MGU2cjL3iluGU4gbXEI:b-wtoaek) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Tools/gsc/test/Makefile#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> this sed command will create a new config from the template with the correct parameters

Hmm, but another target here uses exactly the same file, but outputs a different thing there? I think this will break when someone calls Make in parallel mode (-jN).

> The only alternative I see is that we allow gsc build to only work with an image.

I like this solution, we wouldn't have 2 alternative ways GSC could be used, which should be less confusing for users. But parametrizing config name would also be acceptable IMO.
</blockquote></details>

I've added a new configuration parameter to  all`gsc` commands  called `-c` or `--config_file` (default: `config.yaml`). The makefile now uses a different config file (`config-image.yaml`) and specifies `-c`. I've updated the documentation accordingly.


<!-- Sent from Reviewable.io -->

2020-09-05 16:39 UTC, vahldiek commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK7os59cVpDM-Z9Srs:-MGU7_VHCSYcjhbhEzLt:b-h0yz5y) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I restarted Jenkins, let's see.
</blockquote></details>

Could you let me know, if this test run, ran fine? The changes I made should have no effect on the result, but I'm waiting with the final rebase till everyone got another set of comments in.

---


<!-- Sent from Reviewable.io -->

2020-09-07 16:55 UTC, dimakuv commented
Jenkins, test this please

2020-09-08 23:45 UTC, mkow requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vahldiek)

___
*[Documentation/manpages/gsc.rst, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGk54Ol778j8OCRvSdQ:-MGk54Ol778j8OCRvSdR:b-id1iw3) ([raw file](https://github.com/oscarlab/graphene/blob/0de0f6157b76557d190840618f8a09d6d1e3fb5e/Documentation/manpages/gsc.rst#L191)):*
> ```
> :option:`-d <gsc-build -d>`
> ```
Nice, I didn't know reST can do such nice crossrefs!
___
*[Tools/gsc/test/Makefile, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9cXpQ0kqSG6-dmOgJ:-MGk3k3G4aTlQbSUa2Xs:b-ucfknh) ([raw file](https://github.com/oscarlab/graphene/blob/d68ce5c0f9edcd3b683cda30c006bb0a12cd71ef/Tools/gsc/test/Makefile#L78)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

I've added a new configuration parameter to  all`gsc` commands  called `-c` or `--config_file` (default: `config.yaml`). The makefile now uses a different config file (`config-image.yaml`) and specifies `-c`. I've updated the documentation accordingly.
</blockquote></details>

Thanks!
___
*[Tools/gsc/test/Makefile, line 81 at r5](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGk4FZsEIRDp7hvvs4v:-MGk3xg17PW_WzwxlGGB:b-62b8x2) ([raw file](https://github.com/oscarlab/graphene/blob/0de0f6157b76557d190840618f8a09d6d1e3fb5e/Tools/gsc/test/Makefile#L81)):*
> ```Makefile
> gsc-%-python3-base: %-python3 graphene-%
> 	docker tag $(addsuffix $(IMAGE_SUFFIX), $*-python3) $(addsuffix $(IMAGE_SUFFIX), $*-python3-base)
> 	printf "Distro: \"$*\"\nGraphene:\n   Image: \"graphene-$*$(IMAGE_SUFFIX)\"\n" > ../config-image.yaml
> ```

I think you also need to gitignore + clean this new file. Also, maybe it would be better to emit it here instead of the main GSC folder? Seeing autogenerated files there may confuse the users.


<!-- Sent from Reviewable.io -->

2020-09-09 14:14 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: 5 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Tools/gsc/test/Makefile, line 81 at r5](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGk4FZsEIRDp7hvvs4v:-MGmmxSe2GaGQEp2JbbN:br94cod) ([raw file](https://github.com/oscarlab/graphene/blob/0de0f6157b76557d190840618f8a09d6d1e3fb5e/Tools/gsc/test/Makefile#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think you also need to gitignore + clean this new file. Also, maybe it would be better to emit it here instead of the main GSC folder? Seeing autogenerated files there may confuse the users.
</blockquote></details>

Sounds good. Done. All configs in test are now created within the test folder.


<!-- Sent from Reviewable.io -->

2020-09-09 14:36 UTC, mkow requested changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vahldiek)

___
*[Tools/gsc/test/.gitignore, line 1 at r6](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGnFXXV8EGoyn000QFk:-MGnFXXW4l1nkthbgQEg:b-1m9ux7) ([raw file](https://github.com/oscarlab/graphene/blob/f352cf7156b72699a04b0d2706b8a9c3e989b2e3/Tools/gsc/test/.gitignore#L1)):*
> ```ignore
> *.yaml
> ```

missing newline


<!-- Sent from Reviewable.io -->

2020-09-09 14:45 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: 6 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Tools/gsc/test/.gitignore, line 1 at r6](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGnFXXV8EGoyn000QFk:-MGnJoVo9bRkHmeacOGE:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/f352cf7156b72699a04b0d2706b8a9c3e989b2e3/Tools/gsc/test/.gitignore#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing newline
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-09-09 14:45 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-09 14:47 UTC, mkow commented
Jenkins, retest Jenkins-SGX-gsc please

2020-09-09 22:48 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MG9YYqv2Ev_9ZHDmmy8:-MGp2SoI7ZCaBDNuRlAN:b-896fix) (no related file):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Tried my best....
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGK7os59cVpDM-Z9Srs:-MGp2ZW6CbPuCwx41NGq:bak8uw5) (no related file):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Could you let me know, if this test run, ran fine? The changes I made should have no effect on the result, but I'm waiting with the final rebase till everyone got another set of comments in.
</blockquote></details>

Seems to work :)

---


<!-- Sent from Reviewable.io -->

2020-09-09 22:48 UTC, mkow commented
Jenkins, retest this please

2020-09-09 23:31 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vahldiek)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGpC3Wx9zcYGNCQjfcq:-MGpC3Wx9zcYGNCQjfcr:bl0kypz) (no related file):*
Since there are some typos in this PR, let's also fix the commit message slightly:
- `This commit add an option ` -> `This commit adds an option `
- `such as a cloud provider's installation characteristics` -> `such as cloud provider environments`

---
___
*[Documentation/manpages/gsc.rst, line 133 at r8](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGpBiNv0XoYSRkdynf0:-MGpBiNw2OO3oiOi-KwV:b-avydzs) ([raw file](https://github.com/oscarlab/graphene/blob/5e91d07e01a1cd06cecf0cb0bc0a95b2c3a16bd0/Documentation/manpages/gsc.rst#L133)):*
> ```reStructuredText
> .. option:: -c
> 
>    Specify configuraiton file. Default: :file:`config.yaml`
> ```

Just noticed: typo in `configuration`
___
*[Documentation/manpages/gsc.rst, line 165 at r8](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGpBmHb0CIuHTXCfwVP:-MGpBmHb0CIuHTXCfwVQ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/5e91d07e01a1cd06cecf0cb0bc0a95b2c3a16bd0/Documentation/manpages/gsc.rst#L165)):*
> ```reStructuredText
> .. option:: -c
> 
>    Specify configuraiton file. Default: :file:`config.yaml`
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-09-09 23:41 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGpC3Wx9zcYGNCQjfcq:-MGpEFm74G8WwZ4VtqZE:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since there are some typos in this PR, let's also fix the commit message slightly:
- `This commit add an option ` -> `This commit adds an option `
- `such as a cloud provider's installation characteristics` -> `such as cloud provider environments`
</blockquote></details>

Done.

---
___
*[Documentation/manpages/gsc.rst, line 133 at r8](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGpBiNv0XoYSRkdynf0:-MGpEU4C4jKL-JjbkBr6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5e91d07e01a1cd06cecf0cb0bc0a95b2c3a16bd0/Documentation/manpages/gsc.rst#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed: typo in `configuration`
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 165 at r8](https://reviewable.io/reviews/oscarlab/graphene/1785#-MGpBmHb0CIuHTXCfwVP:-MGpEV4OBBIrHg01ojWH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5e91d07e01a1cd06cecf0cb0bc0a95b2c3a16bd0/Documentation/manpages/gsc.rst#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-09 23:42 UTC, mkow commented
Jenkins, retest this please

2020-09-10 01:16 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1785)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-10 01:37 UTC, merged