[Pal/Linux-SGX] Allocate min required memory for file's filename
oscarlab/graphene pull request #1786
Opened 2020-08-31 21:49 UTC by dimakuv

## Description of the changes 

Previously, Linux-SGX PAL allocated 4KB of memory for URI (filename) of any trusted/allowed file or directory. This led to "out of PAL memory" errors in Graphene if there are 100,000s of trusted files, as is the case for complex workloads in GSC/Docker. This PR removes the static 4KB buffer in file's metadata and instead
allocates the minimum required buffer. This PR also cleans up `register_trusted_file()` code a bit.

## How to test this PR? 

@vahldiek must test this with Python Docker image in GSC.

2020-08-31 23:57 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1786)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/1786#-MG5tXjkAE4SPMaY09cm:-MG5tXjkAE4SPMaY09cn:bubjd2v) ([raw file](https://github.com/oscarlab/graphene/blob/3327d5c92907e98f8ce4398a401b230ee4a6e9e3/Pal/src/host/Linux-SGX/enclave_framework.c#L230)):*
> ```C
>     sgx_stub_t* stubs;
>     size_t uri_len;
>     char uri[];
> ```

could you add an inline comment that this is NULL-terminated? (existence of `uri_len` may make readers think that it doesn't need to be)
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 671 at r1](https://reviewable.io/reviews/oscarlab/graphene/1786#-MG5w4e6-EXhoNUDMbdn:-MG5w4e70PVuFN_yY-lJ:b-k7l0nc) ([raw file](https://github.com/oscarlab/graphene/blob/3327d5c92907e98f8ce4398a401b230ee4a6e9e3/Pal/src/host/Linux-SGX/enclave_framework.c#L671)):*
> ```C
>         new->size = attr.pending_size;
> 
>         for (size_t nbytes = 0; nbytes < sizeof(sgx_checksum_t) ; nbytes++) {
> ```

no space before `;`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 671 at r1](https://reviewable.io/reviews/oscarlab/graphene/1786#-MG5wPJ9B0U-72iwL068:-MG5wPJ9B0U-72iwL069:b-6c1u4a) ([raw file](https://github.com/oscarlab/graphene/blob/3327d5c92907e98f8ce4398a401b230ee4a6e9e3/Pal/src/host/Linux-SGX/enclave_framework.c#L671)):*
> ```C
>         new->size = attr.pending_size;
> 
>         for (size_t nbytes = 0; nbytes < sizeof(sgx_checksum_t) ; nbytes++) {
> ```

`nbytes` -> `i` ("nbytes" sounds like a size in bytes of something)
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 694 at r1](https://reviewable.io/reviews/oscarlab/graphene/1786#-MG5V80aBsI2ING-pkjm:-MG5vrbcAzD4svwt4FyS:brr0adg) ([raw file](https://github.com/oscarlab/graphene/blob/49746f8716167f1e98a5b16cb734ab62ff4ddb04/Pal/src/host/Linux-SGX/enclave_framework.c#L694)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Couldn't look at this "extract hex value from hex string" code, so refactored a bit.
</blockquote></details>

yeah, understandable


<!-- Sent from Reviewable.io -->

2020-09-01 00:02 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1786)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-09-01 01:10 UTC, bigdata-memory commented
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 634 at r3](https://reviewable.io/reviews/oscarlab/graphene/1786#-MG6CbLA2tG4CJW97WM1:-MG6CbLB432-1imNm9XD:b8vp9cl) ([raw file](https://github.com/oscarlab/graphene/blob/032a18f8a6f7c2d865dd77beb6139efb001f6924/Pal/src/host/Linux-SGX/enclave_framework.c#L634)):*
> ```C
>     size_t uri_len = strlen(uri);
>     if (uri_len >= URI_MAX)
>         return -PAL_ERROR_INVAL;
> ```

it would be helpful if print a useful message to users here.


<!-- Sent from Reviewable.io -->

2020-09-01 01:33 UTC, bigdata-memory commented
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 672 at r3](https://reviewable.io/reviews/oscarlab/graphene/1786#-MG6HXkXDob0gLb5gSAm:-MG6HXkY9M1Xv8gu-wrn:bd7dfxh) ([raw file](https://github.com/oscarlab/graphene/blob/032a18f8a6f7c2d865dd77beb6139efb001f6924/Pal/src/host/Linux-SGX/enclave_framework.c#L672)):*
> ```C
>         new->size = attr.pending_size;
> 
>         for (size_t i = 0; i < sizeof(sgx_checksum_t); i++) {
> ```

might be safer to check ```checksum_str != NULL```  and ```len(checksum_str)/2 >= sizeof(sgx_checksum_t)``` first.


<!-- Sent from Reviewable.io -->

2020-09-01 10:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1786)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 672 at r3](https://reviewable.io/reviews/oscarlab/graphene/1786#-MG6HXkXDob0gLb5gSAm:-MG89pTD1ahRh0RdhsKk:bbhfzn2) ([raw file](https://github.com/oscarlab/graphene/blob/032a18f8a6f7c2d865dd77beb6139efb001f6924/Pal/src/host/Linux-SGX/enclave_framework.c#L672)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

might be safer to check ```checksum_str != NULL```  and ```len(checksum_str)/2 >= sizeof(sgx_checksum_t)``` first.
</blockquote></details>

This is an internal helper function, so no need to check for argument validity, at least in the NULL case. For length we could add an assert, because it's more likely that people will violate this without a loud crash, but no strong opinion on this.


<!-- Sent from Reviewable.io -->

2020-09-01 18:28 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1786)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-09-01 22:27 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug please (`truncate01` LTP test failed, known and unrelated)

2020-09-01 22:51 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1786)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-01 23:28 UTC, merged