clang fixes
oscarlab/graphene pull request #1795
Opened 2020-09-04 14:56 UTC by pwmarcz

Remaining:

- [ ] remove use of alloca in `dentry_get_path`
- [ ] segmentation fault when running `getdents` regression tests under gdb (likely because of the above)
- [ ] `IS_ARRAY` macro: clang complains about `static_assert` with `((void *) &(arg)) == ((void *) (arg))`
- [ ] `generated_offsets`: clang does not recognize `%p0` in assembly, generates source with a tab (`.ascii\tGENERATED_INTEGER`)
- [ ] `cfi_offset` (and others) does not work with `%rflags` ([bug](https://bugs.llvm.org/show_bug.cgi?id=33633)), need `#ifdef`
- [ ] clang does not recognize `-Wtrampolines`

2020-09-04 15:15 UTC, mkow submitted a review, later dismissed
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/include/shim_thread.h, line 145 at r1](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOd3OI0hKpJuDgBZBe:-MGOd3OI0hKpJuDgBZBf:b-84tqi8) ([raw file](https://github.com/oscarlab/graphene/blob/aa7578fbb023f0b6ca99aaa70884edbc6c7b90a4/LibOS/shim/include/shim_thread.h#L145)):*
> ```objc
>         return;
> 
>     tcb->debug_buf = debug_buf ? debug_buf : malloc(sizeof(struct debug_buf));
> ```

This malloc needs checking, but that's something for another PR...


<!-- Sent from Reviewable.io -->

2020-09-04 15:44 UTC, mkow commented
Jenkins, test this please

2020-09-04 15:50 UTC, mkow commented
Jenkins, retest Docs-18.04 please (Jenkins seems to have a bad day: `Caused: java.io.IOException: Unexpected termination of the channel`)

2020-09-04 15:55 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOos9b1YzIkRJVdjgr:-MGOos9e2pw6_rcPj2db:bgbrt1x) (no related file):*
@pwmarcz CI failed with:

```
  [ malloc ]
get_time.c:29:5: error: no previous prototype for 'compar' [-Werror=missing-prototypes]
 int compar(const void* arg1, const void* arg2) {
     ^
```

The other un-nested functions will probably fail similarly. Quick fix: make all of them static.

---


<!-- Sent from Reviewable.io -->

2020-09-04 16:18 UTC, yamahata approved these changes
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-09-04 16:45 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOzbEN1wiyqKDjNzlM:-MGOzbEN1wiyqKDjNzlN:b44rvgv) (no related file):*
BTW, if I remember correctly, our checkpointing code also has nested functions (but it is cleverly hidden under a ton of macros). So that code will have to be untagled as well...

---
___
*[LibOS/Makefile, line 139 at r5](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGP-GCi5h9R-g5Ocatn:-MGP-GCi5h9R-g5Ocato:b-hgdja6) ([raw file](https://github.com/oscarlab/graphene/blob/3ea8203ce76572e9026e039447358ddfd9938a84/LibOS/Makefile#L139)):*
> ```Makefile
> $(GCC_BUILD_DIR)/Build.success: $(GCC_BUILD_DIR)/Makefile
> 	@echo "Building gcc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see \"$(GCC_BUILD_DIR)/gcc-build.log\" for more information."
> 	($(MAKE) -C $(GCC_BUILD_DIR) 2>&1 > gcc-build.log) && touch $@
> ```

Please add the same here, when building GCC
___
*[LibOS/Makefile, line 146 at r5](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGP-KnQBIZYVjo3eYGj:-MGP-KnQBIZYVjo3eYGk:b-hgdja6) ([raw file](https://github.com/oscarlab/graphene/blob/3ea8203ce76572e9026e039447358ddfd9938a84/LibOS/Makefile#L146)):*
> ```Makefile
> 	mkdir -p $(GCC_BUILD_DIR)
> 	(cd $(GCC_BUILD_DIR) || exit 1; \
> 	../$(GCC_SRC)/configure --prefix=$(RUNTIME_DIR) \
> ```

Please add the same here, when building GCC
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 709 at r1](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOx5fBA2XMoxRhxQv6:-MGOx5fBA2XMoxRhxQv7:b-t5gz4b) ([raw file](https://github.com/oscarlab/graphene/blob/aa7578fbb023f0b6ca99aaa70884edbc6c7b90a4/LibOS/shim/src/bookkeep/shim_thread.c#L709)):*
> ```C
>     tcb->context.regs = saved_tcb->context.regs;
>     tcb->context.preempt = saved_tcb->context.preempt;
>     debug_setbuf(tcb, NULL);
> ```

BTW, all `debug_setbuf` in this file are memory leaks (on fork/exec), since they allocate on the heap. I currently don't understand which stack Graphene uses at these points (restoring the TCB after fork/exec), so I see that it's impossible to allocate the debug buffer on the stack.

However, I think this whole "where do we allocate the debug buffer for each thread" logic is stupid. Here is what we currently have:
```
struct shim_tcb {
  ...
  struct debug_buf*   debug_buf;
}
```

And `struct debug_buf` is just a 256B array. There is more than enough room in the TCB to simply move the buffer there instead of painfully allocating it on stack/heap. Of course, we'll need to clear the buffer on fork/exec.
___
*[LibOS/shim/test/native/get_time.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOzU2OCbKbUqvYIctt:-MGOzU2OCbKbUqvYIctu:byeokx4) ([raw file](https://github.com/oscarlab/graphene/blob/9fc526c8ad1e441f25492fed31f36ce579bf53cb/LibOS/shim/test/native/get_time.c#L29)):*
> ```C
> }
> 
> int compar(const void* arg1, const void* arg2) {
> ```

`static int`
___
*[LibOS/shim/test/native/test_start_pthread_m.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOzXen-4ZFGNf_9PR8:-MGOzXen-4ZFGNf_9PR9:byeokx4) ([raw file](https://github.com/oscarlab/graphene/blob/9fc526c8ad1e441f25492fed31f36ce579bf53cb/LibOS/shim/test/native/test_start_pthread_m.c#L29)):*
> ```C
> }
> 
> int compar(const void* arg1, const void* arg2) {
> ```

`static int`


<!-- Sent from Reviewable.io -->

2020-09-07 14:24 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: 9 of 12 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOos9b1YzIkRJVdjgr:-MGcwR4v9Mx_yslGTDuk:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@pwmarcz CI failed with:

```
  [ malloc ]
get_time.c:29:5: error: no previous prototype for 'compar' [-Werror=missing-prototypes]
 int compar(const void* arg1, const void* arg2) {
     ^
```

The other un-nested functions will probably fail similarly. Quick fix: make all of them static.
</blockquote></details>

Done.

---
___
*[LibOS/Makefile, line 139 at r5](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGP-GCi5h9R-g5Ocatn:-MGcwcqSDkZzX5tsjJzi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3ea8203ce76572e9026e039447358ddfd9938a84/LibOS/Makefile#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the same here, when building GCC
</blockquote></details>

Done.
___
*[LibOS/Makefile, line 146 at r5](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGP-KnQBIZYVjo3eYGj:-MGcwdf413nP7yVfSBv9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3ea8203ce76572e9026e039447358ddfd9938a84/LibOS/Makefile#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the same here, when building GCC
</blockquote></details>

Done.
___
*[LibOS/shim/test/native/get_time.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOzU2OCbKbUqvYIctt:-MGcwlEV6flhytY-PmVz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9fc526c8ad1e441f25492fed31f36ce579bf53cb/LibOS/shim/test/native/get_time.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`static int`
</blockquote></details>

Done.
___
*[LibOS/shim/test/native/test_start_pthread_m.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOzXen-4ZFGNf_9PR8:-MGcwmg6-cH72Okr-GU2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9fc526c8ad1e441f25492fed31f36ce579bf53cb/LibOS/shim/test/native/test_start_pthread_m.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`static int`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-07 14:32 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-07 14:32 UTC, mkow commented
Jenkins, retest this please

2020-09-07 14:34 UTC, pwmarcz commented
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 709 at r1](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOx5fBA2XMoxRhxQv6:-MGcz-Jn5y2ernMW0t61:b-kwsbyx) ([raw file](https://github.com/oscarlab/graphene/blob/aa7578fbb023f0b6ca99aaa70884edbc6c7b90a4/LibOS/shim/src/bookkeep/shim_thread.c#L709)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, all `debug_setbuf` in this file are memory leaks (on fork/exec), since they allocate on the heap. I currently don't understand which stack Graphene uses at these points (restoring the TCB after fork/exec), so I see that it's impossible to allocate the debug buffer on the stack.

However, I think this whole "where do we allocate the debug buffer for each thread" logic is stupid. Here is what we currently have:
```
struct shim_tcb {
  ...
  struct debug_buf*   debug_buf;
}
```

And `struct debug_buf` is just a 256B array. There is more than enough room in the TCB to simply move the buffer there instead of painfully allocating it on stack/heap. Of course, we'll need to clear the buffer on fork/exec.
</blockquote></details>

OK, but I'd rather do it in a separate PR.


<!-- Sent from Reviewable.io -->

2020-09-07 14:55 UTC, mkow commented
Jenkins, retest Jenkins-Debug please (`apps.LTP.kill01` timed out, known issue)

2020-09-07 17:01 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 709 at r1](https://reviewable.io/reviews/oscarlab/graphene/1795#-MGOx5fBA2XMoxRhxQv6:-MGdVntyDhrGIEgoJNUF:b-misdyg) ([raw file](https://github.com/oscarlab/graphene/blob/aa7578fbb023f0b6ca99aaa70884edbc6c7b90a4/LibOS/shim/src/bookkeep/shim_thread.c#L709)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, but I'd rather do it in a separate PR.
</blockquote></details>

Yes, it should be done in a separate PR. I was thinking aloud :)


<!-- Sent from Reviewable.io -->

2020-09-07 17:21 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-09-07 17:21 UTC, dimakuv commented
Jenkins, test this please

2020-09-07 17:25 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-09-07 17:30 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1795)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-07 18:19 UTC, merged