[Pal/Linux-SGX] Add manifest option `sgx.internal_size`
oscarlab/graphene pull request #1797
Opened 2020-09-04 21:42 UTC by dimakuv

## Description of the changes 

Previously, Graphene preallocated 64MB for PAL internal metadata like trusted/protected files metadata, handles metadata, etc. If this limit was depleted, Graphene loudly failed, and the user had no option but to change constant in source code and rebuild Graphene.

This PR adds the manifest option `sgx.internal_size` to allow increasing this limit in the manifest.

See https://github.com/oscarlab/graphene/issues/1792 and https://github.com/oscarlab/graphene/pull/1768 and https://github.com/oscarlab/graphene/issues/1072 for more context.

Fixes https://github.com/oscarlab/graphene/issues/1792.

This solution is still not the best. Ideally, we want LibOS to be aware of what memory regions PAL takes for itself during runtime (in contrast to how it is done now: PAL gets a limit on the memory it can use). However, the ideal solution is really hard to implement...

## How to test this PR? 

I didn't add any new tests because they take quite some time. I tested on our Protected Files regression tests with this patch:
```
diff --git a/LibOS/shim/test/fs/manifest.template b/LibOS/shim/test/fs/manifest.template
@@ -36,3 +36,6 @@ sgx.allowed_files.tmp_dir = file:tmp/
 sgx.protected_files.output = file:tmp/pf_output
+
+sgx.enclave_size  = 512M
+sgx.internal_size = 64M
diff --git a/LibOS/shim/test/fs/test_fs.py b/LibOS/shim/test/fs/test_fs.py
@@ -16,7 +16,7 @@ class TC_00_FileSystem(RegressionTestCase):
         cls.FILE_SIZES = [0, 1, 2, 15, 16, 17, 255, 256, 257, 1023, 1024, 1025, 65535, 65536, 65537,
-                          1048575, 1048576, 1048577]
+                          1048575, 1048576, 1048577, 64*1024*1024]
         cls.TEST_DIR = 'tmp'
```

Here I created a 64MB protected file. Tests fail if `sgx.internal_size = 0` (or not specified) and pass if `sgx.internal_size = 64M`.

2020-09-04 22:22 UTC, yamahata submitted a review, later dismissed
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-09-08 21:32 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/lib/graphene/config.c, line 540 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGjc41pDzuttwZDqnWJ:-MGjc41q00eFT6PG64l0:b-odwrqn) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/lib/graphene/config.c#L540)):*
> ```C
> }
> 
> uint64_t parse_int(const char* str) {
> ```

```parse_uint(..)``` might be intended.


<!-- Sent from Reviewable.io -->

2020-09-08 23:33 UTC, mkow requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 232 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk1ofv7GdlPSvPp6Z0:-MGk1ofv7GdlPSvPp6Z1:b3kj02f) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Documentation/manifest-syntax.rst#L232)):*
> ```reStructuredText
> ::
> 
>     sgx.internal_size=[SIZE]
> ```

hmm, is this option really SGX-specific?
___
*[Pal/include/lib/api.h, line 238 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk0DbFCr6ZyWAtTts1:-MGk0DbFCr6ZyWAtTts2:bpfbe7p) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/include/lib/api.h#L238)):*
> ```objc
> ssize_t get_config_entries_size (struct config_store * cfg, const char * key);
> int set_config (struct config_store * cfg, const char * key, const char * val);
> uint64_t parse_int(const char* str);
> ```

Could you preserve the documentation from shim_init.c? (especially that this is a public API now)
___
*[Pal/lib/graphene/config.c, line 540 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGjc41pDzuttwZDqnWJ:-MGjzu1A8LYsrJgw7rrG:btxb7jm) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/lib/graphene/config.c#L540)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

```parse_uint(..)``` might be intended.
</blockquote></details>

or rather `parse_size_str()` or something similar, it's not a typical int parsing, but also handles suffixes.
___
*[Pal/lib/graphene/config.c, line 558 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk-oaf7iuZks32zUpU:-MGk-oaf7iuZks32zUpV:b-480eo9) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/lib/graphene/config.c#L558)):*
> ```C
>         if (val < 0)
>             break;
>         if ((uint8_t) val >= radix)
> ```

no space after cast
___
*[Pal/lib/graphene/config.c, line 560 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk-pmt4yctE6JAK3oI:-MGk-pmt4yctE6JAK3oJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/lib/graphene/config.c#L560)):*
> ```C
>         if ((uint8_t) val >= radix)
>             break;
>         num = num * radix + (uint8_t) val;
> ```

ditto
___
*[Pal/src/slab.c, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk0b-h63_4WNjmVV_x:-MGk0b-iC6LMbxt27zRu:bjcdvav) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/src/slab.c#L63)):*
> ```C
>      * manifest option and thus may return -ENOMEM. */
>     int ret = _DkVirtualMemoryAlloc(&addr, ALLOC_ALIGN_UP(size), PAL_ALLOC_INTERNAL,
>               PAL_PROT_READ | PAL_PROT_WRITE);
> ```

This looks like a weird design, why not set `POOL_SIZE` directly with that manifest option?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk1GLk1Yto19WJ5_wE:-MGk1GLk1Yto19WJ5_wF:b-1k85mw) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/src/host/Linux-SGX/db_main.c#L59)):*
> ```
> This relies on the fact that our memory management allocates memory
> from higher addresses to lower addresses (see also enclave_pages.c
> and db_memory.c). */
> ```
Sounds brittle, could you also add a comment there saying that there's a chunk of code relying on this behavior?
___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk2Yjw6GxBBfCG7e0s:-MGk2Yjw6GxBBfCG7e0t:b-y0dxbp) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/src/host/Linux-SGX/enclave_pages.c#L15)):*
> ```C
> static void* g_heap_top;
> 
> static size_t g_pal_internal_used = 0;
> ```

I'd prefer to include "mem" in this name, sounds confusing if you don't have prior knowledge what it is. Same with the other globals you added in this PR.


<!-- Sent from Reviewable.io -->

2020-09-25 10:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: 2 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 232 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk1ofv7GdlPSvPp6Z0:-MI3auTeER-WHfCbSf3g:boghss8) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Documentation/manifest-syntax.rst#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

hmm, is this option really SGX-specific?
</blockquote></details>

Not really, but it is only relevant for SGX (because only SGX really uses a lot of PAL internal memory). I wanted to have a symmetry between `sgx.enclave_size` and `sgx.internal_size`. We could have `sys.internal_size`, but I find it not intuitive.
___
*[Pal/include/lib/api.h, line 238 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk0DbFCr6ZyWAtTts1:-MI3c1OTAfbcOdlmz3Q0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/include/lib/api.h#L238)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you preserve the documentation from shim_init.c? (especially that this is a public API now)
</blockquote></details>

Done.
___
*[Pal/lib/graphene/config.c, line 540 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGjc41pDzuttwZDqnWJ:-MI3cdGf9cX7rnuF0UIy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/lib/graphene/config.c#L540)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

or rather `parse_size_str()` or something similar, it's not a typical int parsing, but also handles suffixes.
</blockquote></details>

Done.
___
*[Pal/lib/graphene/config.c, line 558 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk-oaf7iuZks32zUpU:-MI3ciXU6VgfWO0kjZVX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/lib/graphene/config.c#L558)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space after cast
</blockquote></details>

Done.
___
*[Pal/lib/graphene/config.c, line 560 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk-pmt4yctE6JAK3oI:-MI3cj2w2SuTK9d45Gh9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/lib/graphene/config.c#L560)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/slab.c, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk0b-h63_4WNjmVV_x:-MI3ckeUCW5krBijcbHD:b-mbpoaz) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/src/slab.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This looks like a weird design, why not set `POOL_SIZE` directly with that manifest option?
</blockquote></details>

But `POOL_SIZE` is a constant used for a BSS variable (original memory pool). We cannot modify it at run-time, and we also need this original variable for bootstrapping.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk1GLk1Yto19WJ5_wE:-MI3foiD3qKj6Eq2UyeH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/src/host/Linux-SGX/db_main.c#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> This relies on the fact that our memory management allocates memory
> from higher addresses to lower addresses (see also enclave_pages.c
> and db_memory.c). */
> ```
Sounds brittle, could you also add a comment there saying that there's a chunk of code relying on this behavior?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_pages.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk2Yjw6GxBBfCG7e0s:-MI3f0q_BvAC9U77rg6E:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Pal/src/host/Linux-SGX/enclave_pages.c#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to include "mem" in this name, sounds confusing if you don't have prior knowledge what it is. Same with the other globals you added in this PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-25 13:19 UTC, mkow requested changes
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 232 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk1ofv7GdlPSvPp6Z0:-MI4Mnpp4-7RpBJTetLa:b-omsm0v) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Documentation/manifest-syntax.rst#L232)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not really, but it is only relevant for SGX (because only SGX really uses a lot of PAL internal memory). I wanted to have a symmetry between `sgx.enclave_size` and `sgx.internal_size`. We could have `sys.internal_size`, but I find it not intuitive.
</blockquote></details>

Hmm, but this thing will also be relevant on other PALs in the future. Even on pure Linux PAL if we start using PAL memory more extensively for something. I don't really think this belongs to SGX. And for me this is actually less intuitive, because it sounds like this is some SGX-internal size, not just PAL-reserved memory.


<!-- Sent from Reviewable.io -->

2020-09-30 11:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: 9 of 12 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1797#-MITjG92EokNH7u1NM1M:-MITjG92EokNH7u1NM1N:b-aybc6o) (no related file):*
Note to myself: during rebase, must change from `sgx.internal_size` to `loader.pal_internal_mem_size`.

---
___
*[Documentation/manifest-syntax.rst, line 232 at r1](https://reviewable.io/reviews/oscarlab/graphene/1797#-MGk1ofv7GdlPSvPp6Z0:-MITcNnQ21AzVx37-8pC:b-umrr38) ([raw file](https://github.com/oscarlab/graphene/blob/d2c697a3aa35b71bac1781914f29f3a9a241dce8/Documentation/manifest-syntax.rst#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but this thing will also be relevant on other PALs in the future. Even on pure Linux PAL if we start using PAL memory more extensively for something. I don't really think this belongs to SGX. And for me this is actually less intuitive, because it sounds like this is some SGX-internal size, not just PAL-reserved memory.
</blockquote></details>

Done. Changed to `loader.pal_internal_mem_size`.


<!-- Sent from Reviewable.io -->

2020-09-30 13:46 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-09-30 16:03 UTC, mkow approved these changes
> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1797)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-30 16:47 UTC, mkow commented
Jenkins, retest Jenkins-SGX-gsc please (Jenkins did not pick up the build for some reason)

2020-09-30 18:09 UTC, merged