[Pal/{Linux,Linux-SGX}] Remove ALLOW_BIND_ANY and check_any_addr() logic
oscarlab/graphene pull request #1798
Opened 2020-09-04 22:51 UTC by dimakuv

## Description of the changes 

This PR removes `ALLOW_BIND_ANY` and `check_any_addr()` logic. Removing this logic also fixes the bug in Linux PAL of binding on port 0 (previously it stayed as "0" instead of actual new port).

Fixes https://github.com/oscarlab/graphene/issues/1713.

Closes https://github.com/oscarlab/graphene/pull/1714. (This PR is a recreation of that PR with all fixes applied.)

## How to test this PR? 

New test is added to LibOS regression.

2020-09-05 15:02 UTC, yamahata submitted a review, later dismissed
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1798)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-09-08 23:57 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1798)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1798#-MGk7ilj9zJCDLTQq4d_:-MGk7ilk5pefNKUDANIH:b-xgouhe) (no related file):*
Could you add a `Co-authored-by:` line to the commit message and include @jianyu-m?

---


<!-- Sent from Reviewable.io -->

2020-09-09 02:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1798)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jianyu-m)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1798#-MGk7ilj9zJCDLTQq4d_:-MGkhgybA6kaHnZ7OXeD:b-5gf9p5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a `Co-authored-by:` line to the commit message and include @jianyu-m?
</blockquote></details>

Done. Good point, I should always do that.

---


<!-- Sent from Reviewable.io -->

2020-09-09 11:44 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1798)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-09-09 16:18 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1798)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-09-09 17:37 UTC, yamahata approved these changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1798)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-09 17:38 UTC, merged