[LibOS] Remove stack allocation from dentry_get_path()
oscarlab/graphene pull request #1800
Opened 2020-09-08 12:50 UTC by pwmarcz

Instead, require the user to always provide a big enough buffer.

For clang support, see #1794.

- Create a convenience "into qstr" wrapper
- Eliminate the only instances where the function was called with
  on_stack == false (they were leaking memory)
- Remove a few null checks that are impossible now
- Fix possible overflow in unix_copy_addr() (truncate the address
  instead)

## Description of the changes 

## How to test this PR?

2020-09-08 13:24 UTC, mkow commented
Jenkins, test this please

2020-09-08 14:40 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: 3 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhrtDx-lkhBQJx-5FG:-MGi2H1nCdzPlwsC6Tgb:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

From the commit message:

> see #1794.

Please specify the full link, in case we move/migrate the repo the numbers could change.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGi0wO4B1u1DWcV92Ua:-MGi2XvjDEz-jBeO5Ngk:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Jenkins failed with:
```
sys/shim_socket.c: In function 'unix_copy_addr':
sys/shim_socket.c:300:27: error: passing argument 2 of 'dentry_get_path' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
     dentry_get_path(dent, path);
                           ^
In file included from sys/shim_socket.c:23:0:
../include/shim_fs.h:414:7: note: expected 'char *' but argument is of type 'const char *'
 char* dentry_get_path(struct shim_dentry* dent, char *buffer);
       ^
```
</blockquote></details>

Done.

---
___
*[LibOS/shim/include/shim_fs.h, line 403 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhv9Jn57C8kd2y-qDE:-MGi5ocBCursyt6qjCwA:b2neqbh) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/include/shim_fs.h#L403)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this function will always\* be used for allocations, not for e.g. iterating over the string. Making it return size instead of length (+changing the name accordingly) would make it more error-prone (no need to add 1 to the result).

\* ok, maybe except one callsite :)
</blockquote></details>

Done. There is some awkwardness in `ipc_pid_getmeta_callback`, it looks like we send a string without the null terminator. I kept the current behaviour.
___
*[LibOS/shim/include/shim_fs.h, line 414 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhtxb00McLlFkfKSPe:-MGi5p5q4U-6LqkNmxnh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/include/shim_fs.h#L414)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please move `*` to the types (ditto below)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 420 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhuVm1BBySy6EObgI6:-MGi6wiq2-VYLZ2cpovM:b83bh2r) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/include/shim_fs.h#L420)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`qstrsetstr()` may fail (there's an allocation inside, if it fails it returns NULL)
</blockquote></details>

I made the function return `char*` and fixed the one place that already had a case for `-ENOMEM`. Not sure what to do with others (they don't seem to care about`qstrsetstr()` return value), can we consider that out of scope here?
___
*[LibOS/shim/src/fs/shim_fs.c, line 676 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhvwub5LrRErocIPBX:-MGi5yWo0ulR1x2iWVjz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/src/fs/shim_fs.c#L676)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`char *buffer` -> `char* buffer`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 690 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhwCmy48JIHZu3vd6d:-MGi66-t5lip_Otrpi1R:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/src/fs/shim_fs.c#L690)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're refactoring this code, could you also fix this line?
Should be:
`size_t len = dent->rel_path.len;` (size_t + not aligned)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 307 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGi0C-L2Dd7fRDQ3AiY:-MGi67ZA7nZ-yOdpAsx3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/src/sys/shim_socket.c#L307)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add curly braces to this branch (we either skip them for both if-else cases or use in both).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-08 15:50 UTC, yamahata submitted a review, later dismissed
> Reviewed 3 of 10 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-09-08 16:22 UTC, mkow requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 420 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhuVm1BBySy6EObgI6:-MGiEj9m8Q3VXVPw0v1M:buqw01i) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/include/shim_fs.h#L420)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I made the function return `char*` and fixed the one place that already had a case for `-ENOMEM`. Not sure what to do with others (they don't seem to care about`qstrsetstr()` return value), can we consider that out of scope here?
</blockquote></details>

Ok, let's leave it for later, I'm afraid that you may end up changing too many callsites up in the call chain.
___
*[LibOS/shim/include/shim_fs.h, line 412 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGiCwir6GCfgChg6MU3:-MGiCwir6GCfgChg6MU4:bjogpwr) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L412)):*
> ```objc
> /* Get path (FS path + relpath). The path size can be checked by calling
>  * dentry_get_path_size(dent), and the buffer needs to have space for at least
>  * that many characters.
> ```

`characters` -> `bytes`
___
*[LibOS/shim/include/shim_fs.h, line 416 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGiDLO77hDm8nFoZIwU:-MGiDLO77hDm8nFoZIwV:bueg11r) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L416)):*
> ```
> struct shim_dentry *dent
> ```

You forgot this one ;)


<!-- Sent from Reviewable.io -->

2020-09-08 16:50 UTC, mkow commented
Jenkins, retest this please

2020-09-08 21:43 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs.c, line 693 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGjey0J9BPyHpjg8Bd8:-MGjey0LAKRzqPbBAvxi:b-ulzbyw) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/fs/shim_fs.c#L693)):*
> ```C
> 
>         if (c > buffer && *(c - 1) == '/') {
>             if (*path == '/')
> ```

portable for WinOS ?


<!-- Sent from Reviewable.io -->

2020-09-08 22:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs.c, line 693 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGjey0J9BPyHpjg8Bd8:-MGjv9P0532rUxN_i-yZ:bcod9mz) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/fs/shim_fs.c#L693)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

portable for WinOS ?
</blockquote></details>

We emulate Linux, not Windows ;) This is LibOS code, not PAL, so it's emulating Linux.


<!-- Sent from Reviewable.io -->

2020-09-09 03:03 UTC, dimakuv requested changes
> Reviewed 3 of 10 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGki3gTDpzwnVO7IY9S:-MGki3gTDpzwnVO7IY9T:b6nkz1j) (no related file):*
Debug builds in Jenkins fail with this:
```
  [ fs/shim_fs.o ]
In file included from ../../../Pal/include/lib/list.h:108:0,
                 from fs/shim_fs.c:12:
fs/shim_fs.c: In function 'dentry_get_path':
fs/shim_fs.c:704:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     assert(c - buffer == dentry_get_path_size(dent) - 1);
                       ^
../../../Pal/include/lib/assert.h:30:12: note: in definition of macro 'assert'
         (!(expr)) ? ({                                                   \
            ^
```

---
___
*[LibOS/shim/include/shim_fs.h, line 406 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGkjL3u8Nd8yz7RXpcG:-MGkjL3u8Nd8yz7RXpcH:b-dfl3qq) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L406)):*
> ```objc
>     size_t size = dent->rel_path.len + 1;
>     if (dent->fs)
>         size += dent->fs->path.len + 1;
> ```

This `+1` is for the `/` character? Could you add a comment with this?
___
*[LibOS/shim/include/shim_fs.h, line 412 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGkiy2qDzqhUr9mu6sk:-MGkiy2qDzqhUr9mu6sl:b-942239) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L412)):*
> ```objc
> /* Get path (FS path + relpath). The path size can be checked by calling
>  * dentry_get_path_size(dent), and the buffer needs to have space for at least
>  * that many characters.
> ```

Please rewrap the comment to 100 chars
___
*[LibOS/shim/include/shim_fs.h, line 416 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGiDLO77hDm8nFoZIwU:-MGkk3tv2TlYDh7WohmY:bwaayex) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L416)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> struct shim_dentry *dent
> ```

You forgot this one ;)
</blockquote></details>

Michal means alignment of the asterisk (to the left, not to the right)
___
*[LibOS/shim/src/fs/proc/thread.c, line 122 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknKVo2Q2tVc8oA5Qw:-MGknKVo2Q2tVc8oA5Qx:bq35pjl) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/fs/proc/thread.c#L122)):*
> ```C
> 
>     if (link)
>         dentry_get_path_into_qstr(dent, link);
> ```

Don't we want to add error handling here? Something like:
```
if (!dentry_get_path_into_qstr(dent, link)) {
    ret = -EINVAL;
    goto out;
}
```
___
*[LibOS/shim/src/fs/proc/thread.c, line 365 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknb_H0pYMJ_Z0EM8M:-MGknb_H0pYMJ_Z0EM8N:bqvsd1b) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/fs/proc/thread.c#L365)):*
> ```C
> 
>     if (link)
>         dentry_get_path_into_qstr(dent, link);
> ```

ditto (error handling)
___
*[LibOS/shim/src/sys/shim_exec.c, line 274 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknqT523MiN6PclHLI:-MGknqT523MiN6PclHLJ:bqvsd1b) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/sys/shim_exec.c#L274)):*
> ```C
>     }
> 
>     dentry_get_path_into_qstr(dent, &exec->path);
> ```

ditto (error handling)


<!-- Sent from Reviewable.io -->

2020-09-09 08:14 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: 7 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGki3gTDpzwnVO7IY9S:-MGljYa04BCGexHhHkM4:brwmyrw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Debug builds in Jenkins fail with this:
```
  [ fs/shim_fs.o ]
In file included from ../../../Pal/include/lib/list.h:108:0,
                 from fs/shim_fs.c:12:
fs/shim_fs.c: In function 'dentry_get_path':
fs/shim_fs.c:704:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     assert(c - buffer == dentry_get_path_size(dent) - 1);
                       ^
../../../Pal/include/lib/assert.h:30:12: note: in definition of macro 'assert'
         (!(expr)) ? ({                                                   \
            ^
```
</blockquote></details>

Okay, I  will be sure to check with DEBUG=1 from now on. I added a cast to `ssize_t`.

---
___
*[LibOS/shim/include/shim_fs.h, line 420 at r1](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhuVm1BBySy6EObgI6:-MGltccZ7azEfV77h16y:bayh0h8) ([raw file](https://github.com/oscarlab/graphene/blob/bf36ffa4d8c908142c11e33b420345341cac48e5/LibOS/shim/include/shim_fs.h#L420)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, let's leave it for later, I'm afraid that you may end up changing too many callsites up in the call chain.
</blockquote></details>

@dimakuv suggested error handling, so I added it to the two places where it was easy, see later comments.
___
*[LibOS/shim/include/shim_fs.h, line 406 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGkjL3u8Nd8yz7RXpcG:-MGlpDfN9AByVzaCv0uv:br16hmt) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L406)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `+1` is for the `/` character? Could you add a comment with this?
</blockquote></details>

Ouch, I took a closer look at the function, and this is actually more complicated - we adjust the result so that there is exactly one slash between components.

(And by the way, the original code seems to do it slightly wrong,, because in one case we do `path++` but still adjust by `len`. But the only consequence is to write an extra zero byte to the buffer.)

I refactored `dentry_get_path` for that to be more clear, and made `dentry_get_path_size` mirror that structure, so that hopefully it's obvious that both functions arrive at the same result.
___
*[LibOS/shim/include/shim_fs.h, line 412 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGiCwir6GCfgChg6MU3:-MGlqWsSCrTZ45Em3mpc:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L412)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`characters` -> `bytes`
</blockquote></details>

OK.
___
*[LibOS/shim/include/shim_fs.h, line 412 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGkiy2qDzqhUr9mu6sk:-MGlqYDD35vIUznMYk8W:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L412)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rewrap the comment to 100 chars
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 416 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGiDLO77hDm8nFoZIwU:-MGlqevr3TPvgRUm3sH8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/include/shim_fs.h#L416)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Michal means alignment of the asterisk (to the left, not to the right)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 122 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknKVo2Q2tVc8oA5Qw:-MGltrBRAO_VFsXsLaEq:b-gc6am) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/fs/proc/thread.c#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to add error handling here? Something like:
```
if (!dentry_get_path_into_qstr(dent, link)) {
    ret = -EINVAL;
    goto out;
}
```
</blockquote></details>

Seems obvious enough, so I added it (should be `ENOMEM`, right?).
___
*[LibOS/shim/src/fs/proc/thread.c, line 365 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknb_H0pYMJ_Z0EM8M:-MGltxFYC4x5dRotN5b0:b2nreh6) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/fs/proc/thread.c#L365)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (error handling)
</blockquote></details>

Same as above.
___
*[LibOS/shim/src/sys/shim_exec.c, line 274 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknqT523MiN6PclHLI:-MGltzoY9QCQbkb77sKZ:bctpbie) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/sys/shim_exec.c#L274)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (error handling)
</blockquote></details>

I don't understand error handling in this function (various cleanup paths, returns) so I would rather not touch that in this PR. I'm afraid of breaking something or making the situation worse...


<!-- Sent from Reviewable.io -->

2020-09-09 12:06 UTC, mkow requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs.c, line 737 at r3](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGmiw802jfQZrZOx_Cv:-MGmiw802jfQZrZOx_Cw:b6y6xpe) ([raw file](https://github.com/oscarlab/graphene/blob/cd4cc8f0842d2e6ba981b3c1299b0e43d7019f27/LibOS/shim/src/fs/shim_fs.c#L737)):*
> ```C
>     }
> 
>     assert(c - buffer == (ssize_t) dentry_get_path_size(dent) - 1);
> ```

no space after casts please (they have very high priority, like all prefix operators)
___
*[LibOS/shim/src/fs/proc/thread.c, line 122 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknKVo2Q2tVc8oA5Qw:-MGmjUpH-Ya5Ox-M2sOL:b-ufx1k6) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/fs/proc/thread.c#L122)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Seems obvious enough, so I added it (should be `ENOMEM`, right?).
</blockquote></details>

Yup, ENOMEM is right.
___
*[LibOS/shim/src/sys/shim_exec.c, line 274 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknqT523MiN6PclHLI:-MGmhpAKClDQMnajBrzp:b183xir) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/sys/shim_exec.c#L274)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't understand error handling in this function (various cleanup paths, returns) so I would rather not touch that in this PR. I'm afraid of breaking something or making the situation worse...
</blockquote></details>

@dimakuv see this discussion: https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhuVm1BBySy6EObgI6 ;)


<!-- Sent from Reviewable.io -->

2020-09-09 13:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: 9 of 10 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/shim_fs.c, line 737 at r3](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGmiw802jfQZrZOx_Cv:-MGn-njU-HJafKA2HlQl:bgt13ty) ([raw file](https://github.com/oscarlab/graphene/blob/cd4cc8f0842d2e6ba981b3c1299b0e43d7019f27/LibOS/shim/src/fs/shim_fs.c#L737)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space after casts please (they have very high priority, like all prefix operators)
</blockquote></details>

Done (and I added parentheses to cast the whole expression).


<!-- Sent from Reviewable.io -->

2020-09-09 13:36 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-09 18:51 UTC, mkow commented
Jenkins, retest this please

2020-09-09 21:19 UTC, mkow commented
Jenkins, retest this please

2020-09-09 21:19 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-09 21:46 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 57 at r5](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGonvpl-RXcyx3OQeIX:-MGonvpl-RXcyx3OQeIY:bqfwfro) ([raw file](https://github.com/oscarlab/graphene/blob/016bed7e9e402f3dcb3dc181f46e00cd4d767643/LibOS/shim/src/bookkeep/shim_handle.c#L57)):*
> ```C
>     hdl->flags  = O_RDWR | O_APPEND | 0100000;
> 
>     dentry_get_path_into_qstr(dent, &hdl->path);
> ```

error check?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 88 at r5](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGonxhI6o_iBOCWjtrC:-MGonxhI6o_iBOCWjtrD:bqfwfro) ([raw file](https://github.com/oscarlab/graphene/blob/016bed7e9e402f3dcb3dc181f46e00cd4d767643/LibOS/shim/src/bookkeep/shim_handle.c#L88)):*
> ```C
>         set_handle_fs(exec, fs);
>         if (exec->dentry)
>             dentry_get_path_into_qstr(exec->dentry, &exec->path);
> ```

error check?
___
*[LibOS/shim/src/sys/shim_exec.c, line 274 at r2](https://reviewable.io/reviews/oscarlab/graphene/1800#-MGknqT523MiN6PclHLI:-MGoohMg-awRHnEsCX1a:b-ijg0oh) ([raw file](https://github.com/oscarlab/graphene/blob/d4449299e48ab280ca7c74ff82db52dc119c4799/LibOS/shim/src/sys/shim_exec.c#L274)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv see this discussion: https://reviewable.io/reviews/oscarlab/graphene/1800#-MGhuVm1BBySy6EObgI6 ;)
</blockquote></details>

can you please add comment here?


<!-- Sent from Reviewable.io -->

2020-09-09 21:52 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-09-09 22:22 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1800)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-09 22:26 UTC, merged