Prebuilt image for AKS with documentation on usage for AKS
oscarlab/graphene pull request #1817
Opened 2020-09-15 01:50 UTC by vahldiek

## Description of the changes 

This PR adds a folder `images` to `Tools/gsc` which includes Dockerfile for prebuilt images of popular cloud services (at the start Azure Kubernetes Service). These image files are created via `make` in `Tools/gsc`. Remaking the image files is only required, if GSC changes substantially in its Graphene build process (in particular any changes to `Tools/gsc/templates/Dockerfile.*.compile.template`). Changes in Graphene itself do not require to recreate these image files.

Using this prebuilt image, an additional example in `Documentation/cloud-deployment.rst` describes how to deploy a graphenized Docker image to Azure Kubernetes Service.

In addition, this PR also includes minor changes to GSC which add a configuration parameter to only create the Dockerfile instead of also building the image.

## How to test this PR? 

Run the regular Jenkins pipeline, in particular the one for the docs. Follow the example provided in `Documentation/cloud-deployment.rst` to test he example, if interested.

2020-09-16 21:30 UTC, agowdamsft commented
AKS deployment instructions on MS docs will be published on Dec 18th. We can keep the current provisioning instructions and do an update after Dec 18th. 1. Please change the az extension add --name aks-preview to az extension add --source https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.61-py2.py3-none-any.whl . Customer should download a particular version of CLI to get this preview feature. 2. Lets remove the azure portal as it will not be supported during AKS preview. 3. This step "Install AKS SGX plugin by following" is not required as UseGen2Feature header in the CLI should automatically install the SGX Device Plugin

2020-09-16 21:48 UTC, vahldiek reviewed
Thanks for the feedback! 

I've made the requested changes. After this PR is merged, I will prepare another PR that links to the Microsoft setup description instead of including in our documentation.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817#-:-MHNsXn63pQjXXUnpFva:b-kzq5yn)* status: 0 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2020-09-21 01:06 UTC, mkow requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Documentation/cloud-deployment.rst, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi5uVH7FeyYNFolDZ9:-MHi5uVH7FeyYNFolDZA:b-nna92p) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L82)):*
> ```reStructuredText
> Azure Kubernetes Services (AKS)
> -------------------------------
> ```

For the whole PR: please wrap the text to keep 80 chars per line limit.
___
*[Documentation/cloud-deployment.rst, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi3aPlBgkcWcfEhkLp:-MHi3aPmEYRoYtpiPqqM:b-t3w6id) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L91)):*
> ```reStructuredText
> AKS. Graphenized Docker images execute the application inside an Intel SGX
> enclave using the Graphene Library OS thus enabling confidential containers
> functions on AKS..
> ```

double period
___
*[Documentation/cloud-deployment.rst, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi61Q6D7YnMx0-9w1m:-MHi61Q6D7YnMx0-9w1n:b-fsk2z) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L111)):*
> ```reStructuredText
> 
>     sudo az aks install-cli
>     az extension add --name aks-preview to az extension add --source https://azurecliprod.blob.core.windows.net/cli-extensions/aks_preview-0.4.61-py2.py3-none-any.whl
> ```

Please wrap this command using `\`, now it renders with a long horizontal scrollbar.
___
*[Documentation/cloud-deployment.rst, line 120 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi69Vg7LdbpG67mj3f:-MHi69Vh9XcyQk4WXWO6:bwjqlc) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L120)):*
> ```reStructuredText
> #. Create AKS cluster and choose one of the `DCsv2 VM instances <https://docs.microsoft.com/en-us/azure/virtual-machines/dcv2-series>`__ as `VMinstancetype`::
> 
>        az aks create -l <location> -g <resourcegroupname> -n <aksclustername> --vm-set-type VirtualMachineScaleSets --node-count 1 --kubernetes-version 1.16.10 --network-plugin azure --node-vm-size <VMinstancetype> --aks-custom-headers usegen2vm=true
> ```

ditto (wrapping)
___
*[Documentation/cloud-deployment.rst, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi6RumCmH-KT-Q5BQ4:-MHi6RumCmH-KT-Q5BQ5:bsoyw4d) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L128)):*
> ```reStructuredText
> 
> Follow the `instructions
> <https://graphene.readthedocs.io/en/latest/manpages/gsc.html>`__ to setup
> ```

`setup` -> `set up` ("setup" is only a noun)
___
*[Documentation/cloud-deployment.rst, line 130 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi6hQm9NcCcI2VWJib:-MHi6hQm9NcCcI2VWJic:b37gjy2) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L130)):*
> ```reStructuredText
> <https://graphene.readthedocs.io/en/latest/manpages/gsc.html>`__ to setup
> Graphene Shielded Containers and create your own enclave key. The instructions
> in this section demonstrate how to translate the Python Dockerhub image to a
> ```

`Dockerhub` -> `Docker Hub` (ditto for the whole PR)
___
*[Documentation/cloud-deployment.rst, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi6tpODFDYW16BGHHM:-MHi6tpODFDYW16BGHHN:b-69vt6) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L136)):*
> ```
> relies on insecure arguments
> ```

IMO the readers won't understand this at this point of reading, not enough context (what arguments?). You also didn't explain this anywhere later, so it's not clear what exactly is wrong with this example and how to make it secure (which isn't that trivial with Python).
___
*[Documentation/cloud-deployment.rst, line 152 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi7BjbBlsfDSdvunYI:-MHi7BjbBlsfDSdvunYJ:b507eit) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L152)):*
> ```reStructuredText
> 
>        sgx.allow_file_creation = 1
>        sgx.enclave_size=256M
> ```

Please unify spacing around `=`. I prefer the version with spaces around.
___
*[Documentation/cloud-deployment.rst, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi7NJDB1UtYMeGDv-C:-MHi7NJDB1UtYMeGDv-D:b858a5o) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L163)):*
> ```reStructuredText
>        ./gsc sign-image python enlave-key.pem
> 
> #. Push resulting image to Dockerhub or your prefferred registry::
> ```

`prefferred` -> `preferred`
___
*[Tools/gsc/Makefile, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi8WFiBcwlU0yfcij7:-MHi8WFiBcwlU0yfcij8:b-hqjne6) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L3)):*
> ```Makefile
> # This makefile should be used to generate Dockerfiles for all prebuilt images. Prebuilt images are
> # located in images/*. These files are then pulled by Dockerhub to generate the public Dockerhub
> # images of Graphene. When GSC changes substentially in its initial Graphene build (e.g. when
> ```

`substentially` -> `substantially`
___
*[Tools/gsc/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi8c_40dZeD3MAltZE:-MHi8c_40dZeD3MAltZF:bffn7yp) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L5)):*
> ```Makefile
> # images of Graphene. When GSC changes substentially in its initial Graphene build (e.g. when
> # template/Dockerfile.*.compile.template changes), these automatically generated files need to be
> # updated. Genrally, changes to Graphene do not require to rebuild these Docker files.
> ```

`Genrally` -> `Generally`
___
*[Tools/gsc/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi8gz76dtlhGiXunXn:-MHi8gz76dtlhGiXunXo:bittz1z) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L5)):*
> ```Makefile
> # images of Graphene. When GSC changes substentially in its initial Graphene build (e.g. when
> # template/Dockerfile.*.compile.template changes), these automatically generated files need to be
> # updated. Genrally, changes to Graphene do not require to rebuild these Docker files.
> ```

`to rebuild` -> `rebuilding`
___
*[Tools/gsc/Makefile, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi94Pp6L584xyxC3bU:-MHi94Pp6L584xyxC3bV:byyktfq) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L16)):*
> ```Makefile
> 	 \"https://github.com/oscarlab/graphene.git\"\n    Branch: \"$*\"\nSGXDriver:\n    \
> 	 Repository: \"https://github.com/intel/SGXDataCenterAttestationPrimitives.git\"\n \
> 	    Branch: \"LD_1.22 && cp -r driver/linux/* .\"\n" > $@
> ```

Please format this to have one output line per one source line, now it's really hard to read.
___
*[Tools/gsc/Makefile, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi9EMM9Ew2nF1DqOA9:-MHi9EMM9Ew2nF1DqOAA:b-qyiumb) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53 [...]

2020-09-21 17:09 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: 2 of 6 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Documentation/cloud-deployment.rst, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi5uVH7FeyYNFolDZ9:-MHl52qu1SNPobS0S9sN:b76xi65) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For the whole PR: please wrap the text to keep 80 chars per line limit.
</blockquote></details>

I'm not sure where line wrap is needed here. In particular, I cannot break lines of headings and enumerations, since otherwise my `make html` renders incorrectly. Please let me know, if this is different on the system on Jenkins.
___
*[Documentation/cloud-deployment.rst, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi3aPlBgkcWcfEhkLp:-MHl581D87ylZi7Ak0n-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double period
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi61Q6D7YnMx0-9w1m:-MHl5cVOEHxnzA7_eiWj:b-twk4yt) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please wrap this command using `\`, now it renders with a long horizontal scrollbar.
</blockquote></details>

Removed and replaced with azure description.
___
*[Documentation/cloud-deployment.rst, line 120 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi69Vg7LdbpG67mj3f:-MHl5gGD3_kd0UDgVvmA:byr4ffv) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L120)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (wrapping)
</blockquote></details>

see above
___
*[Documentation/cloud-deployment.rst, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi6RumCmH-KT-Q5BQ4:-MHl5jeh6ctxhRZcN46p:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L128)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`setup` -> `set up` ("setup" is only a noun)
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 130 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi6hQm9NcCcI2VWJib:-MHl5miv39_zR3_1dzJt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Dockerhub` -> `Docker Hub` (ditto for the whole PR)
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi6tpODFDYW16BGHHM:-MHl5xAqEfMHlB4_4oOo:brpmff1) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> relies on insecure arguments
> ```

IMO the readers won't understand this at this point of reading, not enough context (what arguments?). You also didn't explain this anywhere later, so it's not clear what exactly is wrong with this example and how to make it secure (which isn't that trivial with Python).
</blockquote></details>

I disagree about making arguments secure, since GSC takes fixed arguments (e.g. in the entrypoint or cmd) of a the Docker image and makes them trusted. At this point you simply can't change them...

I tried to add more context and provide a hint to where we talk about trusted arguments and GSC.
___
*[Documentation/cloud-deployment.rst, line 152 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi7BjbBlsfDSdvunYI:-MHl6dx1Ea97wWa5gan1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please unify spacing around `=`. I prefer the version with spaces around.
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi7NJDB1UtYMeGDv-C:-MHl6hDr-iAd36ylHsB0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L163)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`prefferred` -> `preferred`
</blockquote></details>

Done.
___
*[Tools/gsc/Makefile, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi8WFiBcwlU0yfcij7:-MHl6pNh-2MrtcvOcEaM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`substentially` -> `substantially`
</blockquote></details>

Done.
___
*[Tools/gsc/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi8c_40dZeD3MAltZE:-MHl6vScBs_dkOm6e5gp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Genrally` -> `Generally`
</blockquote></details>

Done.
___
*[Tools/gsc/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi8gz76dtlhGiXunXn:-MHl6y0a2b0qjhQB3XSY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`to rebuild` -> `rebuilding`
</blockquote></details>

Done.
___
*[Tools/gsc/Makefile, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi94Pp6L584xyxC3bU:-MHl8IY--E4De7GuEbrx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please format this to have one output line per one source line, now it's really hard to read.
</blockquote></details>

Done.
___
*[Tools/gsc/Makefile, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi9EMM9Ew2nF1DqOA9:-MHl8Kw0A16GDpqnaQja:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`rm` -> `$(RM)`
</blockquote></details>

Done.
___
*[Tools/gsc/Makefile, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi9Kk70UBlEdfhf2nc:-MHl8OvUD5WsZ-bWCqdb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Tools/gsc/Makefile#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing .PHONY
</blockquote></details>

Done.
___
*[Tools/gsc/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MH [...]

2020-09-21 18:14 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Documentation/cloud-deployment.rst, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi5uVH7FeyYNFolDZ9:-MHlrin-6E1CdxEajDPO:bpto4fa) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L82)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

I'm not sure where line wrap is needed here. In particular, I cannot break lines of headings and enumerations, since otherwise my `make html` renders incorrectly. Please let me know, if this is different on the system on Jenkins.
</blockquote></details>

Interesting. Anyways, look better now.
___
*[Documentation/cloud-deployment.rst, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHi6tpODFDYW16BGHHM:-MHlpvBgAmKlhjQvEZyv:bwqjeb8) ([raw file](https://github.com/oscarlab/graphene/blob/99adfe7cb53c190e38b3e200d9f0114a4839deec/Documentation/cloud-deployment.rst#L136)):*
> GSC takes fixed arguments [..] of a the Docker image and makes them trusted

Ok, I forgot about this feature :)

Looks good now.
___
*[Documentation/cloud-deployment.rst, line 101 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlpUXFBg47afTWa7-Y:-MHlpUXFBg47afTWa7-Z:b-c5nwy2) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Documentation/cloud-deployment.rst#L101)):*
> ```reStructuredText
> 
> Follow the instructions on the `AKS Confidential Computing Quick Start guide
> <AKS.ms/accaksgetstarted>`__  to provision an AKS cluster with Intel SGX enabled
> ```

This link doesn't work. Please test your changes ;)
___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 36 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrRq35XfVT08JJJwF:-MHlrRq35XfVT08JJJwG:bmx1505) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L36)):*
> ```Dockerfile
> RUN cd /graphene && ISGX_DRIVER_PATH=/graphene/Pal/src/host/Linux-SGX/sgx-driver/linux-sgx-driver \
>     make -s -j4 SGX=1 WERROR=1 \
>      && true 
> ```

trailing blank
___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrQB3Dvo2dbbGAzFI:-MHlrQB4CPbvdoDCS7vY:b49c69t) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L39)):*
> ```Dockerfile
> 
> # Translate runtime symlinks to files
> RUN for f in $(find /graphene/Runtime -type l); do cp --remove-destination $(realpath $f) $f; done
> ```

Now it's missing a newline


<!-- Sent from Reviewable.io -->

2020-09-21 18:39 UTC, vahldiek reviewed
We have three todos left:
* Find someone to test the description
* Find the correct link for the AKS starting guide
* Hopefully Don finds time to review this PR

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817#-:-MHlx7Ri-qtMSltEQoRS:br67lnw)* status: 3 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Documentation/cloud-deployment.rst, line 101 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlpUXFBg47afTWa7-Y:-MHlw_kG6LGw6VIGADGI:b-d1l8j7) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Documentation/cloud-deployment.rst#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This link doesn't work. Please test your changes ;)
</blockquote></details>

I've updated the link so it works, but this may not be the final link. I leave this comment unsolved to track this.
___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 36 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrRq35XfVT08JJJwF:-MHlvOm7ABTHc8t8cokr:b-4c16uo) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

trailing blank
</blockquote></details>

Changed the tempalte
___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrQB3Dvo2dbbGAzFI:-MHlv1OZBfvTWBKJYLaT:bxd234y) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now it's missing a newline
</blockquote></details>

Needs a double new line in the template file. But I guess this is ok?


<!-- Sent from Reviewable.io -->

2020-09-21 19:10 UTC, mkow requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Documentation/cloud-deployment.rst, line 101 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlpUXFBg47afTWa7-Y:-MHm2bfe18CREx48HMiz:b-hpyv86) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Documentation/cloud-deployment.rst#L101)):*
Ok, will leave this blocked. If you want to have something blocked from your side you need to manually switch your disposition to "blocking" (see the bottom right corner of the message widget, you can see dispositions of everyone involved).

> ```
> http://AKS.ms/accaksgetstarted
> ```
Please use HTTPS.
___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrQB3Dvo2dbbGAzFI:-MHm3IZGBZlS_uq3V4LO:b-mugvpo) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L39)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Needs a double new line in the template file. But I guess this is ok?
</blockquote></details>

Huh, this is weird...
Btw. how is this file generated from the template? Can this be done automatically, or you also added some custom changes? If we can do it automatically, why committing it to the repo?


<!-- Sent from Reviewable.io -->

2020-09-21 19:28 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Documentation/cloud-deployment.rst, line 101 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlpUXFBg47afTWa7-Y:-MHm7eFfAbaZbrk2Z2Iv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Documentation/cloud-deployment.rst#L101)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, will leave this blocked. If you want to have something blocked from your side you need to manually switch your disposition to "blocking" (see the bottom right corner of the message widget, you can see dispositions of everyone involved).

> ```
> http://AKS.ms/accaksgetstarted
> ```
Please use HTTPS.
</blockquote></details>

Done.
___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrQB3Dvo2dbbGAzFI:-MHm5setBgyvavPRnxdi:brda81t) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, this is weird...
Btw. how is this file generated from the template? Can this be done automatically, or you also added some custom changes? If we can do it automatically, why committing it to the repo?
</blockquote></details>

Yes it is generated via make in `Tools/gsc`. It is required to generate the public image from it. Dockerhub does not allow to run any scripts, it needs a Dockerfile.


<!-- Sent from Reviewable.io -->

2020-09-21 23:32 UTC, donporter requested changes
> Reviewed 2 of 5 files at r1, 1 of 4 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vahldiek)

___
*[Documentation/cloud-deployment.rst, line 101 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlpUXFBg47afTWa7-Y:-MHmyHr60P44_yAArf8z:b-eye7mu) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Documentation/cloud-deployment.rst#L101)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Since mkow is already blocking, I won't also add a block.  But the link doesn't work for me.
___
*[Documentation/cloud-deployment.rst, line 84 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHmyUGnC4chKl2HWMco:-MHmyUGnC4chKl2HWMcp:b-7nf44k) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L84)):*
> ```reStructuredText
> 
> Azure Kubernetes Service (AKS) offers a popular deployment technique relying on
> Azure's cloud resources. AKS allows to host Kubernetes pods in Azure
> ```

Remove "allows to".  Just say "AKS hosts..." (and make "expose" singular ("exposes") if you change this).
___
*[Documentation/cloud-deployment.rst, line 88 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHmzHO41zFSqYtdGRJ6:-MHmzHO41zFSqYtdGRJ7:b-nhrihz) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L88)):*
> ```reStructuredText
> hardware. In particular, `Graphene Shielded Containers (GSC)
> <https://graphene.readthedocs.io/en/latest/manpages/gsc.html>`__ translate
> existing Docker images to graphenized Docker images which can be deployed in
> ```

Need a comma before "which".
___
*[Documentation/cloud-deployment.rst, line 90 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHmzvFxCATVIs2JuzkI:-MHmzvFxCATVIs2JuzkJ:b-6n7b7j) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L90)):*
> ```reStructuredText
> existing Docker images to graphenized Docker images which can be deployed in
> AKS. Graphenized Docker images execute the application inside an Intel SGX
> enclave using the Graphene Library OS thus enabling confidential containers
> ```

Would read better with a comma before "thus"
___
*[Documentation/cloud-deployment.rst, line 111 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHn-EK15l_ABAUYo9-B:-MHn-EK15l_ABAUYo9-C:b-ti1fe2) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L111)):*
> ```reStructuredText
> Graphene Shielded Containers and create your own enclave key. The instructions
> in this section demonstrate how to translate the Python Docker Hub image to a
> graphenized image which is ready to deploy in a confidential compute AKS
> ```

comma before "which"


<!-- Sent from Reviewable.io -->

2020-09-21 23:39 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: 5 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @donporter and @mkow)

___
*[Documentation/cloud-deployment.rst, line 84 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHmyUGnC4chKl2HWMco:-MHn0V3C-2nDredDOoby:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L84)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Remove "allows to".  Just say "AKS hosts..." (and make "expose" singular ("exposes") if you change this).
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 88 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHmzHO41zFSqYtdGRJ6:-MHn0gMT1AefVWQYlb7r:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L88)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Need a comma before "which".
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 90 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHmzvFxCATVIs2JuzkI:-MHn0kVN4YotpaD6yZPr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L90)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Would read better with a comma before "thus"
</blockquote></details>

Done.
___
*[Documentation/cloud-deployment.rst, line 111 at r4](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHn-EK15l_ABAUYo9-B:-MHn134n6pKwlokb5MOj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0614d76c10089da1e36f99d0ad3649c4030c53c4/Documentation/cloud-deployment.rst#L111)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

comma before "which"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-21 23:41 UTC, donporter approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-09-22 00:05 UTC, mkow reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow and @vahldiek)

___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrQB3Dvo2dbbGAzFI:-MHn6S_20yry-EUYSgsi:b-eg6x4a) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L39)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Yes it is generated via make in `Tools/gsc`. It is required to generate the public image from it. Dockerhub does not allow to run any scripts, it needs a Dockerfile.
</blockquote></details>

Ok, I see, I didn't notice previously that this file is the same as the one generated by the Makefile. Could you add a comment to the top of the Makefile explaining this? (that we have to commit this file to the repo because of how Docker Hub works)


<!-- Sent from Reviewable.io -->

2020-09-22 00:16 UTC, vahldiek commented
___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrQB3Dvo2dbbGAzFI:-MHn9a1y8Pp9sL3WYjha:b-rbqdu0) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, I see, I didn't notice previously that this file is the same as the one generated by the Makefile. Could you add a comment to the top of the Makefile explaining this? (that we have to commit this file to the repo because of how Docker Hub works)
</blockquote></details>

There should be. I changed the Docker Hub spelling.
"# This makefile should be used to generate Dockerfiles for all prebuilt images. Prebuilt images are
# located in images/*. These files are then pulled by Docker Hub to generate the public Docker Hub
# images of Graphene. When GSC changes substantially in its initial Graphene build (e.g. when
# template/Dockerfile.*.compile.template changes), these automatically generated files need to be
# updated. Generally, changes to Graphene do not require rebuilding these Docker files."


<!-- Sent from Reviewable.io -->

2020-09-22 01:08 UTC, mkow reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Tools/gsc/images/graphene_aks.latest.dockerfile, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlrQB3Dvo2dbbGAzFI:-MHnL7Pj7qiO_FtmQ1er:b9zy0nz) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Tools/gsc/images/graphene_aks.latest.dockerfile#L39)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

There should be. I changed the Docker Hub spelling.
"# This makefile should be used to generate Dockerfiles for all prebuilt images. Prebuilt images are
# located in images/*. These files are then pulled by Docker Hub to generate the public Docker Hub
# images of Graphene. When GSC changes substantially in its initial Graphene build (e.g. when
# template/Dockerfile.*.compile.template changes), these automatically generated files need to be
# updated. Generally, changes to Graphene do not require rebuilding these Docker files."
</blockquote></details>

I saw this, but it doesn't say explicitly why can't we generate them during build (i.e. that Docker Hub pulls the repository and doesn't execute any build commands, so we have to commit them). Anyways, not too important, so I won't block on this.


<!-- Sent from Reviewable.io -->

2020-09-22 07:32 UTC, vahldiek commented
___
*[Documentation/cloud-deployment.rst, line 101 at r2](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHlpUXFBg47afTWa7-Y:-MHoiACc-fHPEQHMywGn:bj0a0fc) ([raw file](https://github.com/oscarlab/graphene/blob/24ca9b813abb5244051d1edeb13eb17eabb1c108/Documentation/cloud-deployment.rst#L101)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Since mkow is already blocking, I won't also add a block.  But the link doesn't work for me.
</blockquote></details>

I changed the link back to the one for the AKS guide. This link should go live on Tuesday 10am PST. I'm not sure what it will link to though, but was told that it provides introductions to use AKS with confidential compute.


<!-- Sent from Reviewable.io -->

2020-09-22 07:38 UTC, manojgop reviewed
@vahldiek  I could to test this PR successfully with an existing AKS cluster (which has SGX enabled nodes).  I built the gsc-python image and pushed it to my private docker hub repository. Also modified gsc-aks-python.yaml to use the docker image in my private docker hub repository as mentioned in PR documentation. 

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817#-:-MHoii7uEcN8aj2NQT-v:bjnfvkf)* status: 4 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @donporter and @mkow)



<!-- Sent from Reviewable.io -->

2020-09-22 07:39 UTC, manojgop reviewed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-09-22 10:19 UTC, mkow commented
Jenkins, test this please

2020-09-22 10:24 UTC, mkow requested changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Documentation/cloud-deployment.rst, line 126 at r8](https://reviewable.io/reviews/oscarlab/graphene/1817#-MHpKbYfEXZ6A77nrSgH:-MHpKbYgD_gDfxuAQNmj:baz4jiq) ([raw file](https://github.com/oscarlab/graphene/blob/03cac4b0bcbf842a5cfc1523b34b9f26d6917b11/Documentation/cloud-deployment.rst#L126)):*
> ```reStructuredText
>        docker pull python
> 
> #. Configure GSC to build graphenized images for AKS with the `Graphene Docker Image for AKS from Docker Hub <https://hub.docker.com/repository/docker/graphenelibos/aks>`__ by creating the following configuration file :file:`config.aks.yaml`::
> ```

This link doesn't work without being logged in, is this intended?


<!-- Sent from Reviewable.io -->

2020-09-22 12:19 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-09-22 12:19 UTC, mkow commented
Jenkins, test this please

2020-09-22 13:16 UTC, donporter approved these changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1817)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 13:19 UTC, mkow commented
Jenkins, retest Jenkins-Debug-18.04 please (weird, looks like Jenkins is not too stable: `make[1]: write error: stdout Makefile:13: recipe for target 'distclean' failed`)

2020-09-22 16:45 UTC, merged