[Pal] Rewrite GDB integration, part 1
oscarlab/graphene pull request #1828
Opened 2020-09-17 17:53 UTC by mkow

## Description of the changes 

For now only gdb-script and Python parts. This is mostly a clean-up of both Linux and Linux-SGX integration which additionally removes some annoying user prompts we had in the old scripts.

A step towards resolving #1814 (fixes the annoying prompts).

## How to test this PR? 

Test a few examples with `GDB=1` set in env before using `pal_loader`.

2020-09-18 01:01 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 0 of 27 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Runtime/pal_loader, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHThycq9NNSHqfKlZL0:-MHThycrBEd3hN6o1lef:bhs2wdt) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Runtime/pal_loader#L62)):*
> ```
> sgx_
> ```
 Now gdb python scripts aren't linked to Runtime dir. Can we have same name?
i.e. graphene_gdb.py 
Maybe this is a matter of preference, though.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHTiISiEeUekCv1T-mO:-MHTiISiEeUekCv1T-mP:b-m7pzng) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L50)):*
> ```
> COPY --from=graphene /graphene/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.so /graphene/Runtime
> COPY --from=graphene /graphene/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py /graphene/Runtime
> COPY --from=graphene /graphene/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb /graphene/Runtime
> ```

Now this doesn't make sense because pal_loader doesn't refer it.
they need to be copied into the directory pal_loader refers.


<!-- Sent from Reviewable.io -->

2020-09-18 01:09 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 0 of 27 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Runtime/pal_loader, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHThycq9NNSHqfKlZL0:-MHTjPypD0zVsV6hrBA7:bhkrskt) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Runtime/pal_loader#L62)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> sgx_
> ```
 Now gdb python scripts aren't linked to Runtime dir. Can we have same name?
i.e. graphene_gdb.py 
Maybe this is a matter of preference, though.

</blockquote></details>

Should we actually link them there? I mean, what is the usecase for this? Our `Runtime` directory isn't an equivalent of install directory seen in typical projects.
But maybe I'm missing something and people actually call these scripts manually, without `pal_loader`?
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHTiISiEeUekCv1T-mO:-MHTkB8h2TnvUbmzXwJr:b-9kmzz8) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L50)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> COPY --from=graphene /graphene/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.so /graphene/Runtime
> COPY --from=graphene /graphene/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py /graphene/Runtime
> COPY --from=graphene /graphene/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb /graphene/Runtime
> ```

Now this doesn't make sense because pal_loader doesn't refer it.
they need to be copied into the directory pal_loader refers.
</blockquote></details>

Good point, I overlooked this. I'll fix this after we agree what should be in `Runtime` (i.e. the other discussion on Reviewable).


<!-- Sent from Reviewable.io -->

2020-09-18 16:24 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 0 of 28 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[Runtime/pal_loader, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHThycq9NNSHqfKlZL0:-MHX0-03CJExYiGwHcm3:bh2r6ur) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Runtime/pal_loader#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should we actually link them there? I mean, what is the usecase for this? Our `Runtime` directory isn't an equivalent of install directory seen in typical projects.
But maybe I'm missing something and people actually call these scripts manually, without `pal_loader`?
</blockquote></details>

Agreed that symlink shouldn't be needed in long term. All the related directory should be configured in pal_laoder.
It will help packaging like .deb, .rpm. In that case, the path can be /usr/libexec/graphene or /opt/graphene or something.


<!-- Sent from Reviewable.io -->

2020-09-18 16:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 0 of 28 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[Runtime/pal_loader, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHThycq9NNSHqfKlZL0:-MHX39FD6eEgsBpXwZ4X:bmdx6tw) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Runtime/pal_loader#L62)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Agreed that symlink shouldn't be needed in long term. All the related directory should be configured in pal_laoder.
It will help packaging like .deb, .rpm. In that case, the path can be /usr/libexec/graphene or /opt/graphene or something.

</blockquote></details>

So, should I symlink it for now, or just leave it as-is, without a symlink in Runtime and leave this until we do proper packaging?


<!-- Sent from Reviewable.io -->

2020-09-18 16:39 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 0 of 28 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " found in commit messages' one-liners (waiting on @mkow)

___
*[Runtime/pal_loader, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHThycq9NNSHqfKlZL0:-MHX45i3AkBH5uDGfqyY:b-aj4bto) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Runtime/pal_loader#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, should I symlink it for now, or just leave it as-is, without a symlink in Runtime and leave this until we do proper packaging?
</blockquote></details>

I don't have strong opinion for it.
So please take easiest way for you for this PR.


<!-- Sent from Reviewable.io -->

2020-09-19 00:08 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 0 of 28 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @vahldiek)

___
*[Runtime/pal_loader, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHThycq9NNSHqfKlZL0:-MHYaoMgCf4SDJWucHUQ:b1t5xpj) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Runtime/pal_loader#L62)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

I don't have strong opinion for it.
So please take easiest way for you for this PR.
</blockquote></details>

I think the easiest would be to not symlink them for now and resolve this issue when we'll work on proper packaging.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHTiISiEeUekCv1T-mO:-MHYfZB-74IY4BXBBxRd:b-2gmajg) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good point, I overlooked this. I'll fix this after we agree what should be in `Runtime` (i.e. the other discussion on Reviewable).
</blockquote></details>

Done. @vahldiek could you review and verify this change? Seems it was a bug which existed even before this PR.


<!-- Sent from Reviewable.io -->

2020-09-19 00:15 UTC, yamahata approved these changes
> Reviewed 18 of 27 files at r1, 3 of 10 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-09-19 08:38 UTC, vahldiek commented
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHTiISiEeUekCv1T-mO:-MH_VjqC3XQOheq53arm:bl9r5sr) ([raw file](https://github.com/oscarlab/graphene/blob/1f3e9d2fe3f752be33332d67e95dd55afe00c014/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done. @vahldiek could you review and verify this change? Seems it was a bug which existed even before this PR.
</blockquote></details>

Yes, debugging was a mess and I never found enough time to really pay attention to how it works. (within Docker) The changes now look fine to me.


<!-- Sent from Reviewable.io -->

2020-09-21 15:46 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_gdb_info.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHl6hJ-Bs68fn0EY334:-MHl6hJ-Bs68fn0EY335:b-756waw) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/sgx_gdb_info.c#L10)):*
> ```C
> 
> /* This function is hooked by our gdb integration script and should be left as is. */
> __attribute__((__noinline__)) void execute_gdb_command(const char* command) {
> ```

Calls to this might still get optimized away - add an empty asm statement here.
More info: https://gcc.gnu.org/onlinedocs/gcc-8.4.0/gcc/Common-Function-Attributes.html#index-noinline-function-attribute
___
*[Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlKdRNAFySePrjHnkA:-MHlKdRNAFySePrjHnkB:b-lszknb) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb#L15)):*
> ```GDB
> #     application, but without silencing SIGILLs caused by other reasons. This is impossible to
> #     implement from GDB Python "API", neither using event handlers nor even executing raw commands
> #     with gdb.execute() - it doesn't support multiline commands, and gdb.execute('commands') blocks
> ```

```
gdb.execute('catch signal SIGILL')
gdb.execute('commands\nprint 123\nprint 456\nend')
```
works perfectly fine for me ...
___
*[Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb, line 48 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlD75z-buOCe4b71VB:-MHlD75z-buOCe4b71VC:b-14drgh) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb#L48)):*
> ```GDB
> # which breakpoint we just set and update this each time we change something in this script. Also,
> # this will break if some other script will be loaded first and will add some breakpoints.
> condition 1 *(uint16_t*)$rip == 0xa20f || *(uint16_t*)$rip == 0x310f
> ```

Or you can use `$bpnum` and not worry. (gdb set this variable to the last breakpoint number)
___
*[Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlJ_rv5w2ulSJ0A0Xb:-MHlJ_rv5w2ulSJ0A0Xc:b32vjw) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py#L54)):*
> ```Python
> 
>     def stop(self):
>         command = gdb.parse_and_eval("(const char*)$rdi").string()
> ```

<3


<!-- Sent from Reviewable.io -->

2020-09-21 17:36 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "squash! " and "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[.pylintrc, line 288 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlhwsR6RJkjzu4ZvKq:-MHlhwsSC_dzyyDcC97s:b3ezdjv) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/.pylintrc#L288)):*
> ```
> # Regular expression matching correct constant names. Overrides const-naming-
> # style.
> const-rgx=(^_)|(^[A-Z][A-Z0-9_]*$)
> ```

The ```_``` is a valid identifier in Python that is used for ignore values.
In addition, the single leading underscore indicates the internal use, not necessary to mean the constant only.


<!-- Sent from Reviewable.io -->

2020-09-21 17:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 26 of 28 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[.pylintrc, line 288 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlhwsR6RJkjzu4ZvKq:-MHlkXghBWDNXacxi6vR:b-wp2rsu) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/.pylintrc#L288)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

The ```_``` is a valid identifier in Python that is used for ignore values.
In addition, the single leading underscore indicates the internal use, not necessary to mean the constant only.
</blockquote></details>

I'm not sure what you mean by this comment, i.e. what do you suggest us to do?
The idea here is to don't enforce this particular style requirements on any variable starting with an underscore.
___
*[Pal/src/host/Linux-SGX/sgx_gdb_info.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHl6hJ-Bs68fn0EY334:-MHlU0L-EK8NE5i73c29:b-bq197m) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/sgx_gdb_info.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Calls to this might still get optimized away - add an empty asm statement here.
More info: https://gcc.gnu.org/onlinedocs/gcc-8.4.0/gcc/Common-Function-Attributes.html#index-noinline-function-attribute
</blockquote></details>

I actually read that today but forgot to fix the code.
Actually, their solution seems fishy, non-volatile asm statements can also be removed... But I'll trust the manual and regret later.
___
*[Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlKdRNAFySePrjHnkA:-MHlhmEG43deeI1AuWy8:bc7s8zv) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

```
gdb.execute('catch signal SIGILL')
gdb.execute('commands\nprint 123\nprint 456\nend')
```
works perfectly fine for me ...
</blockquote></details>

I tried this before but I put the whole script into a single command and if failed on parsing. 

Now I tried your code (i.e. splitting `catch` and `commands`; I literally copy pasted the code from your comment) and my GDB (7.11.1) prints:
```
Catchpoint 1 (signal SIGILL)
Catchpoint 2 (signal SIGILL)
warning: bad breakpoint number at or near '
print 123
print 456
end'
```
Seem exploiting this command injection bug fails on my GDB :)
___
*[Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb, line 48 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlD75z-buOCe4b71VB:-MHlUyQP6sq-bSjns0BP:b-1ljrk5) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Or you can use `$bpnum` and not worry. (gdb set this variable to the last breakpoint number)
</blockquote></details>

Nice, thanks for the hint! Previously I was looking at `condition` and `commands` documentation and didn't find any hint about this.
___
*[Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlJ_rv5w2ulSJ0A0Xb:-MHlS1eY4xboSkBrOFZV:b-nmyixc) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx_gdb.py#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

<3
</blockquote></details>

for bystanders: it was like this before, we'll clean this up in a later iteration :)


<!-- Sent from Reviewable.io -->

2020-09-21 22:25 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_gdb_info.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHl6hJ-Bs68fn0EY334:-MHml7Zm0iXcmyeqH-pO:bppe7k2) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/sgx_gdb_info.c#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I actually read that today but forgot to fix the code.
Actually, their solution seems fishy, non-volatile asm statements can also be removed... But I'll trust the manual and regret later.
</blockquote></details>

Yeah, I would add `volatile` here. Manuals doesn't seem to mention the need for it here, but it wouldn't be the first time manual lies.
___
*[Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHlKdRNAFySePrjHnkA:-MHmi_5pAYuDh-SvqMvL:bnacv4u) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I tried this before but I put the whole script into a single command and if failed on parsing. 

Now I tried your code (i.e. splitting `catch` and `commands`; I literally copy pasted the code from your comment) and my GDB (7.11.1) prints:
```
Catchpoint 1 (signal SIGILL)
Catchpoint 2 (signal SIGILL)
warning: bad breakpoint number at or near '
print 123
print 456
end'
```
Seem exploiting this command injection bug fails on my GDB :)
</blockquote></details>

Yeah, seems like I tested this on older gdb version ;)


<!-- Sent from Reviewable.io -->

2020-09-21 22:46 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_gdb_info.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHl6hJ-Bs68fn0EY334:-MHmqDCRDOQGMcua84sW:b-4ddjsp) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/sgx_gdb_info.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I would add `volatile` here. Manuals doesn't seem to mention the need for it here, but it wouldn't be the first time manual lies.
</blockquote></details>

Does this even compile?
Should be `__asm__ volatile`


<!-- Sent from Reviewable.io -->

2020-09-21 22:50 UTC, boryspoplawski approved these changes
> Reviewed 1 of 3 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-09-21 22:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: 25 of 28 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/sgx_gdb_info.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/1828#-MHl6hJ-Bs68fn0EY334:-MHmqy_W9FEuGAuQuPcz:b-gsu0j0) ([raw file](https://github.com/oscarlab/graphene/blob/37018cfb77d1e33e8975a2c784573d6a72d1a54e/Pal/src/host/Linux-SGX/sgx_gdb_info.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Does this even compile?
Should be `__asm__ volatile`
</blockquote></details>

oops. fixed.


<!-- Sent from Reviewable.io -->

2020-09-21 23:01 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r4, 1 of 3 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1828)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-21 23:45 UTC, merged