Clang fixes: get Linux-18.04 to compile and test
oscarlab/graphene pull request #1830
Opened 2020-09-18 08:06 UTC by pwmarcz

Issue: https://github.com/oscarlab/graphene/issues/1794.

After this batch of fixes:
* both Linux and Linux-SGX compile without warnings,
* Linux passes all tests,
* Linux-SGX still fails a few tests: https://leeroy.cs.unc.edu/job/graphene-sgx-18.04/3461/#showFailuresLink

All of this works under Ubuntu 18.04, because you can install Clang 10 there without adding any extra repositories.

I recommend **enabling Clang builds for Linux** on Jenkins now, and leave Linux-SGX until we manage to debug it.

However, I'm a bit hesitant to propose copy-pasting another set of Jenkinsfiles... I tried using a matrix build:
* [Matrix feature introduction](https://www.jenkins.io/blog/2019/11/22/welcome-to-the-matrix/) on Jenkins blog
* [Jenkinsfile](https://github.com/pwmarcz/graphene/blob/de8ed1560fc0baa913dcc43d20c5fb5ef81f939e/Jenkinsfiles/Linux-18.04) parametrized by `COMPILER` being `clang` or `gcc`
* [Build result on Jenkins](https://leeroy.cs.unc.edu/job/graphene-18.04/3517/) for the above

As you can see on Jenkins, both Clang and GCC are on single page, the console output is displayed section by section, and test results are in two variants. Potentially that could be extended to other configuration switches (at least `DEBUG=1`) so that we don't maintain so many separate files. However, I'm not sure if the end result is readable. What do you think?

@mkow @woju

2020-09-18 08:15 UTC, pwmarcz commented
Also regarding Jenkins: if we do decide to keep the current solution, maybe the files could at least be generated from a template? i.e. when changing build configuration, you edit `*.template`, run make to regenerate the set of files, and commit the result. I know committing generated code doesn't make for a prettiest solution, but at least this reduces the risk of various almost-identical files getting out of sync.

2020-09-21 17:16 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1830)* status: 0 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[Pal/src/host/Linux-SGX/db_files.c, line 557 at r1](https://reviewable.io/reviews/oscarlab/graphene/1830#-MHldSgMBUZjcf4MVugo:-MHldSgNBn5TgNwOtu0X:bs7ph0f) ([raw file](https://github.com/oscarlab/graphene/blob/fd6765bf8933f63046111475cd85854683ced10e/Pal/src/host/Linux-SGX/db_files.c#L557)):*
> ```C
> static int pf_file_attrquery(struct protected_file* pf, int fd_from_attrquery, const char* path,
>                              uint64_t real_size, PAL_STREAM_ATTR* attr) {
>     pf = load_protected_file(path, &fd_from_attrquery, real_size, (pf_file_mode_t)PAL_PROT_READ,
> ```

Why not just use the enum PF_FILE_MODE_READ instead. 


<!-- Sent from Reviewable.io -->

2020-09-23 10:04 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1830)* status: 0 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: )

___
*[Pal/src/host/Linux-SGX/db_files.c, line 557 at r1](https://reviewable.io/reviews/oscarlab/graphene/1830#-MHldSgMBUZjcf4MVugo:-MHuPtSZDnjcBT4NKQd4:b-6z4pna) ([raw file](https://github.com/oscarlab/graphene/blob/fd6765bf8933f63046111475cd85854683ced10e/Pal/src/host/Linux-SGX/db_files.c#L557)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Why not just use the enum PF_FILE_MODE_READ instead. 
</blockquote></details>

Seems right. Done.


<!-- Sent from Reviewable.io -->

2020-09-23 12:19 UTC, mkow requested changes
> Reviewed 5 of 10 files at r1, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1830)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1830#-MHusvIjCTxeFXsohcBM:-MHusvIkEIlNtSPJVfGj:bk37ipu) (no related file):*
Regarding Jenkins Matrix builds: Could you create an issue summarizing the problem? I'd prefer to solve this regardless of this PR, because it seems to be quite a complex problem.

---


<!-- Sent from Reviewable.io -->

2020-09-25 14:31 UTC, pwmarcz commented
> Regarding Jenkins Matrix builds: Could you create an issue summarizing the problem? I'd prefer to solve this regardless of this PR, because it seems to be quite a complex problem.

Agreed, and I think this PR can be merged before setting up Jenkins. Created an issue: https://github.com/oscarlab/graphene/issues/1844.

2020-09-25 15:49 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1830)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-09-28 11:11 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 10 files at r1, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1830)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-28 11:28 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1830)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-09-28 12:12 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1830)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-28 13:06 UTC, merged