[LibOS] Unify logic of counting handles in epoll
oscarlab/graphene pull request #1849
Opened 2020-09-28 14:02 UTC by boryspoplawski

## Description of the changes 
This PR unifies logic of counting handles in an epoll instance. Additionally adds a callback function used at every update to a `handle->pal_handle`, to wakup potential threads blocked at `epoll`.

Kudos to @lejunzhu for pinpointing the issue. 

Fixes #1810

## How to test this PR?

2020-09-28 14:04 UTC, boryspoplawski reviewed
This commit message is not very descriptive, might need a rewrite

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849#-:-MIK0h31A3TT-RcndSAf:b3d82o)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 345 at r1](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIK0oLN1XkFJRuShNMg:-MIK0oLN1XkFJRuShNMh:b-vghqbt) ([raw file](https://github.com/oscarlab/graphene/blob/63b9ebad1f04b5ea5ca10ecfd54145fe86b4b31a/LibOS/shim/src/sys/shim_epoll.c#L345)):*
> ```C
>             /* TODO: This loop is wrong. If there are 2 epoll_items with the same pal_handle (e.g.
>              * due to dup-ed fd), only the first will be updated.
>              * GH issue: https://github.com/oscarlab/graphene/issues/1848 */
> ```

TODO: update this issue once this PR gets merged.


<!-- Sent from Reviewable.io -->

2020-09-28 15:35 UTC, mkow requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 815 at r1](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIKJNB6EQf2e4aYbwh5:-MIKJNB77L3Cu5V-lCmt:b-a2hji0) ([raw file](https://github.com/oscarlab/graphene/blob/63b9ebad1f04b5ea5ca10ecfd54145fe86b4b31a/LibOS/shim/src/bookkeep/shim_handle.c#L815)):*
> ```C
>                 count++;
>             }
>             assert (hdl->info.epoll.fds_count == count);
> ```

No space after `assert`, it's just a function/macro. it's not Python ;)

Also, weird that this compiles in non-debug builds without a warning about unused `count` variable. I guess `++` is treated as both reading and writing and there's no further analysis of where this value goes.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIKJfrS6UHRsXCbh44x:-MIKJfrT4eU1Il8JQyRM:b5brcft) ([raw file](https://github.com/oscarlab/graphene/blob/63b9ebad1f04b5ea5ca10ecfd54145fe86b4b31a/LibOS/shim/src/sys/shim_epoll.c#L73)):*
> ```C
>      * epoll items (note that we send waiter_cnt number of signals -- to each waiting thread)
>      * XXX(borys): I don't think this is correct: set_event semantics seem to be producers-consumers
>      * and here we need to wake all waiting threds. */
> ```

`threds` -> `threads`


<!-- Sent from Reviewable.io -->

2020-09-28 18:48 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 815 at r1](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIKJNB6EQf2e4aYbwh5:-MIL1Q5xDVbpnOpNR9jm:b80vpjk) ([raw file](https://github.com/oscarlab/graphene/blob/63b9ebad1f04b5ea5ca10ecfd54145fe86b4b31a/LibOS/shim/src/bookkeep/shim_handle.c#L815)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No space after `assert`, it's just a function/macro. it's not Python ;)

Also, weird that this compiles in non-debug builds without a warning about unused `count` variable. I guess `++` is treated as both reading and writing and there's no further analysis of where this value goes.
</blockquote></details>

Done.
Yes `++` makes this variable used.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIKJfrS6UHRsXCbh44x:-MIL1_i_2AGWUdwtYSuO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/63b9ebad1f04b5ea5ca10ecfd54145fe86b4b31a/LibOS/shim/src/sys/shim_epoll.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`threds` -> `threads`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-28 19:37 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-28 20:21 UTC, yamahata submitted a review, later dismissed
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-29 04:49 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN9WNK7UwxHsPH6c4B:-MIN9WNK7UwxHsPH6c4C:bfiqtvv) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L69)):*
> ```C
> }
> 
> static void update_epoll(struct shim_epoll_handle* epoll) {
> ```

I don't like the name now. Can we rename to smth like `notify_waiters_of_update()`? Then it will be obvious that this function simply sends notifications to waiters on this epoll handle (because some epoll item changed).
___
*[LibOS/shim/src/sys/shim_epoll.c, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN3nIE-OP5Qzz-I6m2:-MIN3nIE-OP5Qzz-I6m3:b-3xg4n0) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L73)):*
> ```C
>      * epoll items (note that we send waiter_cnt number of signals -- to each waiting thread)
>      * XXX(borys): I don't think this is correct: set_event semantics seem to be producers-consumers
>      * and here we need to wake all waiting threads. */
> ```

Borys, I don't understand your comment. Yes, `set_event()` simply sends a dummy byte on a pipe (producer), and another thread unblocks by reading this byte on the same pipe (consumer). That's how thread waking is implemented in LibOS of Graphene. What is the exact scenario where this fails?
___
*[LibOS/shim/src/sys/shim_epoll.c, line 80 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MINA4Q11xiOgaQXdbQw:-MINA4Q11xiOgaQXdbQx:b-pfyrcy) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L80)):*
> ```C
> }
> 
> void _update_epoll_waiters(struct shim_handle* handle) {
> ```

Can we rename to smth like `_update_epolls()` or `_restart_epolls()`? This function is basically "this shim handle was modified such that all outstanding epolls must be restarted". 
___
*[LibOS/shim/src/sys/shim_epoll.c, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN8fEfCuK9kwve6rHl:-MIN8fEg9IaydJUj66lZ:b1kw6h5) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L85)):*
> ```C
>     struct shim_epoll_item* epoll_item;
>     LISTP_FOR_EACH_ENTRY(epoll_item, &handle->epolls, back) {
>         update_epoll(&epoll_item->epoll->info.epoll);
> ```

Do I understand correctly that you updated accesses to `epoll->waiter_cnt` to atomics because of this function that is called whenever a `<some shim handle>->pal_handle` is updated (and thus there is no lock taken on the `epoll` shim handle)? So we had tiny race conditions with respect to `waiter_cnt` accesses.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 352 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MINB3jE94mCGZ8f1EDn:-MINB3jF7b0F6ayJY05N:buc99he) ([raw file](https://github.com/oscarlab/graphene/blob/16aed0987599ac7c6f9f37ecc26d62fbb8c0a51f/LibOS/shim/src/sys/shim_epoll.c#L352)):*
> ```C
>                         epoll_item->connected = false;
>                         /* handle disconnected, must remove it from epoll list */
>                         need_update = true;
> ```

I think we discussed it offline, but why do we remove this "update the epoll list" logic here (and don't replace it with smth like `epoll->fds_count--`)?
___
*[LibOS/shim/src/sys/shim_socket.c, line 1084 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN5u0o1YZdN689moiB:-MIN5u0p04W57TcNPIAv:b9qfx52) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_socket.c#L1084)):*
> ```C
> 
>             hdl->pal_handle = pal_hdl;
>             _update_epoll_waiters(hdl);
> ```

Are these really the only places where we change `<shim_handle>->pal_handle`? Only in the socket code?


<!-- Sent from Reviewable.io -->

2020-09-29 08:55 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN9WNK7UwxHsPH6c4B:-MIO3bFF3tEwIri3_W5-:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like the name now. Can we rename to smth like `notify_waiters_of_update()`? Then it will be obvious that this function simply sends notifications to waiters on this epoll handle (because some epoll item changed).
</blockquote></details>

+1
___
*[LibOS/shim/src/sys/shim_epoll.c, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN3nIE-OP5Qzz-I6m2:-MIO3UMh0e-3IKWzgL96:b6kzrv3) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Borys, I don't understand your comment. Yes, `set_event()` simply sends a dummy byte on a pipe (producer), and another thread unblocks by reading this byte on the same pipe (consumer). That's how thread waking is implemented in LibOS of Graphene. What is the exact scenario where this fails?
</blockquote></details>

One thread can consume all the bytes if it's fast enough :)


<!-- Sent from Reviewable.io -->

2020-09-29 13:11 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: 2 of 5 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN9WNK7UwxHsPH6c4B:-MIOvy_M9IgSEVh0V4Wi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN3nIE-OP5Qzz-I6m2:-MIOwFg8D7bUyu9T97-1:bogx8ik) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One thread can consume all the bytes if it's fast enough :)
</blockquote></details>

Exactly. Updated the comment.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 80 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MINA4Q11xiOgaQXdbQw:-MIOw-LuD816Y2xSquJB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L80)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename to smth like `_update_epolls()` or `_restart_epolls()`? This function is basically "this shim handle was modified such that all outstanding epolls must be restarted". 
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN8fEfCuK9kwve6rHl:-MIOx-wUA58Mc-Byb58d:bs135bq) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L85)):*
Yes.
> So we had tiny race conditions with respect to waiter_cnt accesses.
What do you mean? Previously there were no updates of epolls on `->pal_handle` changes at all ...
___
*[LibOS/shim/src/sys/shim_epoll.c, line 352 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MINB3jE94mCGZ8f1EDn:-MIOxdH90sQ1v48pLv76:b-k6b5xd) ([raw file](https://github.com/oscarlab/graphene/blob/16aed0987599ac7c6f9f37ecc26d62fbb8c0a51f/LibOS/shim/src/sys/shim_epoll.c#L352)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think we discussed it offline, but why do we remove this "update the epoll list" logic here (and don't replace it with smth like `epoll->fds_count--`)?
</blockquote></details>

`fds_count` is just amount of items on `epoll->fds` list (including these without `pal_handle`).
I think the `->connected` field was just a left over from older version, where there was some kind of list/cache of `pal_handle`s. The question is: why would we need the "update the epoll list" logic here? Maybe I'm missing something ...
___
*[LibOS/shim/src/sys/shim_socket.c, line 1084 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN5u0o1YZdN689moiB:-MIOypin2mDsGrfEZLwW:b-uc76u3) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_socket.c#L1084)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are these really the only places where we change `<shim_handle>->pal_handle`? Only in the socket code?
</blockquote></details>

These are the only places I've found (beside initial assignments, right after creation, where the handle is not yet accessible to anything else), maybe someone should double check that?


<!-- Sent from Reviewable.io -->

2020-09-29 13:45 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_epoll.c, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN3nIE-OP5Qzz-I6m2:-MIP2nMd6gyLPcM-FU4I:b-hbzzja) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Exactly. Updated the comment.
</blockquote></details>

OK, got it.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN8fEfCuK9kwve6rHl:-MIP32yr3Uwywet_mQeJ:b-lx748d) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_epoll.c#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes.
> So we had tiny race conditions with respect to waiter_cnt accesses.
What do you mean? Previously there were no updates of epolls on `->pal_handle` changes at all ...
</blockquote></details>

OK. True, there were no updates of epolls on `pal_handle` changes before this PR, I was wrong about "tiny race conditions".
___
*[LibOS/shim/src/sys/shim_epoll.c, line 352 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MINB3jE94mCGZ8f1EDn:-MIP3ixP1l4QFgXofFXj:b-qgbjzo) ([raw file](https://github.com/oscarlab/graphene/blob/16aed0987599ac7c6f9f37ecc26d62fbb8c0a51f/LibOS/shim/src/sys/shim_epoll.c#L352)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`fds_count` is just amount of items on `epoll->fds` list (including these without `pal_handle`).
I think the `->connected` field was just a left over from older version, where there was some kind of list/cache of `pal_handle`s. The question is: why would we need the "update the epoll list" logic here? Maybe I'm missing something ...
</blockquote></details>

OK. It seems that with current logic, if the user doesn't update epoll via `CTL_DEL`, then this epoll item just stays in this epoll and will be re-added here again and the host will return `PAL_WAIT_ERROR` again.

I guess this was the rationale behind that `connected = false` and `need_update = true` logic in the previous version -- LibOS wouldn't re-add this "bad" epoll item in the next epoll_wait.

I think the current logic is fine though.
___
*[LibOS/shim/src/sys/shim_socket.c, line 1084 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MIN5u0o1YZdN689moiB:-MIP5tj53JG-fJjiwoOS:b-vtfzf0) ([raw file](https://github.com/oscarlab/graphene/blob/ec4a68140b941aa1f9da8b658106ee706e4cba57/LibOS/shim/src/sys/shim_socket.c#L1084)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These are the only places I've found (beside initial assignments, right after creation, where the handle is not yet accessible to anything else), maybe someone should double check that?
</blockquote></details>

OK. I double checked by grepping, seems these are the only places.


<!-- Sent from Reviewable.io -->

2020-09-29 13:48 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-09-29 13:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sys/shim_epoll.c, line 352 at r2](https://reviewable.io/reviews/oscarlab/graphene/1849#-MINB3jE94mCGZ8f1EDn:-MIP7B5dEc_X2ba3uNVj:b-mwk5t5) ([raw file](https://github.com/oscarlab/graphene/blob/16aed0987599ac7c6f9f37ecc26d62fbb8c0a51f/LibOS/shim/src/sys/shim_epoll.c#L352)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. It seems that with current logic, if the user doesn't update epoll via `CTL_DEL`, then this epoll item just stays in this epoll and will be re-added here again and the host will return `PAL_WAIT_ERROR` again.

I guess this was the rationale behind that `connected = false` and `need_update = true` logic in the previous version -- LibOS wouldn't re-add this "bad" epoll item in the next epoll_wait.

I think the current logic is fine though.
</blockquote></details>

We want this item to stay on the list and report errors unless user removes it.


<!-- Sent from Reviewable.io -->

2020-09-29 13:55 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-09-29 14:02 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2020-09-29 14:29 UTC, yamahata approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1849)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2020-09-29 15:50 UTC, merged