[LibOS] Make list of supplementary group ids dynamically allocated
oscarlab/graphene pull request #1850
Opened 2020-09-28 18:44 UTC by boryspoplawski

## Description of the changes 
Supplementary groups IDs are not often used inside Graphene, yet there was a global statically allocated buffer for them, which unnecessarily took a lot of space in binaries and was sent in checkpointing code.
This PR fixes that by making this buffer dynamically allocated on demand.

## How to test this PR? 
Added a new test.

2020-09-28 18:51 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_getpid.c, line 100 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIL21AmEetfGv9z4pN6:-MIL21AmEetfGv9z4pN7:bpdj61p) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/src/sys/shim_getpid.c#L100)):*
> ```
> old_groups
> ```

old_groups can be allocated by restore function below, not by malloc.
___
*[LibOS/shim/test/regression/groups.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIL2LUt2yr9-NJ-d1Zx:-MIL2LUt2yr9-NJ-d1Zy:b-sn9zo0) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/test/regression/groups.c#L58)):*
> ```C
>         }
>     }
> ```

Can you please add setgroup, fork, setgroup test for not-free()?


<!-- Sent from Reviewable.io -->

2020-09-28 18:52 UTC, yamahata reviewed
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-09-28 19:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @yamahata)

___
*[LibOS/shim/src/sys/shim_getpid.c, line 100 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIL21AmEetfGv9z4pN6:-MIL4Qt20fDCdcrjnLF7:b-ix63ll) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/src/sys/shim_getpid.c#L100)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> old_groups
> ```

old_groups can be allocated by restore function below, not by malloc.
</blockquote></details>

By the checkpointing restore? Yes it can, but that should be fine, I hope (free should handle this case internally).
___
*[LibOS/shim/test/regression/groups.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIL2LUt2yr9-NJ-d1Zx:-MIL5FtJCbBnX2dDpVsp:bim6loi) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/test/regression/groups.c#L58)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Can you please add setgroup, fork, setgroup test for not-free()?
</blockquote></details>

I can add another setgroup, sure, but what do you mean by "not-free" ?


<!-- Sent from Reviewable.io -->

2020-09-28 19:11 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/sys/shim_getpid.c, line 100 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIL21AmEetfGv9z4pN6:-MIL636Y-UXE-xf-F17B:bdvfnd6) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/src/sys/shim_getpid.c#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

By the checkpointing restore? Yes it can, but that should be fine, I hope (free should handle this case internally).
</blockquote></details>

Yes by the checkpointing restore. You're correct. It's handled by memory_migrated.
___
*[LibOS/shim/test/regression/groups.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIL2LUt2yr9-NJ-d1Zx:-MIL73428g7PLDN0kG-t:blukz04) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/test/regression/groups.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I can add another setgroup, sure, but what do you mean by "not-free" ?
</blockquote></details>

As you're right as above, I withdraw this.


<!-- Sent from Reviewable.io -->

2020-09-28 20:27 UTC, boryspoplawski commented
Jenkins retest Jenkins-Debug-18.04 please (LTP kill01 timed out, known issue)

2020-09-28 20:29 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (LTP kill01 timed out, known issue); missed comma above

2020-09-29 11:37 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIOdSDW3Ke448G3a7tp:-MIOdSDW3Ke448G3a7tq:bangito) (no related file):*
FYI: `libsysdb.so` size before this PR was 831 KB now it's 579 KB. We're 250 KB lighter :)

---
___
*[LibOS/shim/src/sys/shim_getpid.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIOdDtJ5GrdaihjLItO:-MIOdDtJ5GrdaihjLItP:bop8q78) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/src/sys/shim_getpid.c#L73)):*
> ```C
> 
> static struct groups_info_t {
>     size_t size;
> ```

I know it was like this before, but could you rename this field to `count`? It's not size in bytes.
___
*[LibOS/shim/test/regression/groups.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIOKS4ICCSevXm5Gqvt:-MIOKS4ICCSevXm5Gqvu:b9gpsvv) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/test/regression/groups.c#L12)):*
> ```C
> #define ARRAY_LEN(x) (sizeof(x) / sizeof(x[0]))
> 
> static gid_t test_groups[] = { 0, 1337, 1337, 0 };
> ```

It would be nice if the tests also worked natively, this selection causes -EPERM without root.


<!-- Sent from Reviewable.io -->

2020-09-29 13:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/sys/shim_getpid.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIOdDtJ5GrdaihjLItO:-MIOzpdJ9o4ctNKtbEIG:b-6yrv5e) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/src/sys/shim_getpid.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know it was like this before, but could you rename this field to `count`? It's not size in bytes.
</blockquote></details>

Done.
I think it was just following naming in `getgroups` manual, which uses `size` for number of items on list.
___
*[LibOS/shim/test/regression/groups.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIOKS4ICCSevXm5Gqvt:-MIP-UOe04GMPHokrdQa:b4grb4k) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/test/regression/groups.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It would be nice if the tests also worked natively, this selection causes -EPERM without root.
</blockquote></details>

1. Every selection will cause `EPERM` without appropriate capabilities.
2. The linux kernel sorts ids, so this test should actually sort the `getgroups` output list and only then compare, which I was too lazy to implement :)


<!-- Sent from Reviewable.io -->

2020-09-29 13:32 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sys/shim_getpid.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1850#-MIOdDtJ5GrdaihjLItO:-MIP2q4gBRgudY6ik0n6:btz3ltj) ([raw file](https://github.com/oscarlab/graphene/blob/497d42e5feac2748d14dc07e17aa1ee3570a1472/LibOS/shim/src/sys/shim_getpid.c#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
I think it was just following naming in `getgroups` manual, which uses `size` for number of items on list.
</blockquote></details>

let's not propagate bad naming into our codebase


<!-- Sent from Reviewable.io -->

2020-09-29 15:58 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-09-29 15:59 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1850)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-29 16:29 UTC, boryspoplawski commented
Jenkins, retest Jenkins-18.04 please (appache building error, seems unrelated - jenkins failure?)

2020-09-29 17:16 UTC, merged