[LibOS, Pal/Linux-SGX] Signal handling bug fixes
oscarlab/graphene pull request #1852
Opened 2020-09-29 13:03 UTC by dimakuv

## Description of the changes 

This PR has two bug fixes:

1. [LibOS] Wake up parent thread on SIGCHLD from child. Previously, Graphene had a bug of trying to wake up the (remote) child thread on SIGCHLD. This was a nop. It also meant that the parent thread, who was waiting on the child, wasn't interrupted and continued hanging instead of handling SIGCHLD.

2. [Pal/Linux-SGX] Save XSAVE area of normal app context on sync signals. Previously, when a synchronous signal like SIGFPE/SIGILL happened in the application (e.g., due to div-by-zero or SGX-prohibited SYSCALL instruction), Linux-SGX assembly routine incorrectly saved the XSAVE area (containing among other things FP/SSE/AVX registers) of the signal context. This commit fixes this bug by extracting the XSAVE area of the normal app context, i.e., XSAVE of SSA 0.

This was detected on a large statically built application. Kudos to @thiagomacieira for help in debugging and analyzing the issues.

## How to test this PR? 

New LibOS regression test is added to test bug fix 2. The test is x64-only and assumes an SSE2 enabled CPU.

2020-09-29 13:42 UTC, mkow submitted a review, later dismissed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-09-29 13:45 UTC, boryspoplawski requested changes
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP1ylLCHa-YCF2fUui:-MIP1ylM80DKYj1PkAyn:brz0xp0) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L26)):*
> ```C
> 
>     const struct sigaction act = {
>         .sa_sigaction = sigfpe_handler,
> ```

We need to set `.sa_flags` here as well, at least to `SA_SIGINFO` (potentially also: `SA_ONSTACK`).
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP2LYtC_u7z4w83tBi:-MIP2LYtC_u7z4w83tBj:b-ddt7ov) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L31)):*
> ```C
>     ret = sigaction(SIGFPE, &act, NULL);
>     if (ret < 0) {
>         fprintf(stderr, "sigaction failed: %s\n", strerror(errno));
> ```

Not blocking, just for the future: `err` is a nice shorthand for these two calls.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP5ILQ6tEReR78_Mkj:-MIP5ILQ6tEReR78_Mkk:bg4guwn) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L36)):*
> ```C
> 
>     /* populate array with 0,1,2,3... via argc (this test expects no command-line options and thus
>      * argc == 1); this is to prevent the compiler from optimizing out the XMM logic */
> ```

If `argc` stays, please add a check that it's really `1`.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP3qMOBEMfgaVcTltK:-MIP3qMOBEMfgaVcTltL:b-m1gtqm) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L37)):*
> ```C
>     /* populate array with 0,1,2,3... via argc (this test expects no command-line options and thus
>      * argc == 1); this is to prevent the compiler from optimizing out the XMM logic */
>     int16_t a[8];
> ```

This needs to be 16-byte aligned.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP40UcDIlnMF0OzU10:-MIP40UcDIlnMF0OzU11:bd6fx8l) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L41)):*
> ```C
>         a[i] = argc - 1 + i;
>     __m128i xmm_reg = _mm_load_si128((__m128i*)a);
>     __asm__ volatile("" ::: "memory");
> ```

Since we are using inline assembly anyway, why not just use `movdqa` directly? We wouldn't need to worry about compiler optimizing out memory writes and use `argc` trick.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP3mpT2hPGYcV4xFv3:-MIP3mpT2hPGYcV4xFv4:b-o94lvj) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
> ```C
>                      ::: "rax", "rbx", "rdx", "cc", "memory");
> 
>     if (_mm_extract_epi16(xmm_reg, 0) != 0 || _mm_extract_epi16(xmm_reg, 1) != 1 ||
> ```

This looks like a good place to use `for` loop :)
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MIP4rlZ6D0WNZ-ztMw7:b85dsr9) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
> ```C
>                      ::: "rax", "rbx", "rdx", "cc", "memory");
> 
>     if (_mm_extract_epi16(xmm_reg, 0) != 0 || _mm_extract_epi16(xmm_reg, 1) != 1 ||
> ```

I'm not sure how "smart" is gcc around these areas, but can't it optimize away these comparisons? `xmm_reg` is not memory location and there there is no dependency on it in the inline asm.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP5NcF8Ln9tynYffHv:-MIP5NcF8Ln9tynYffHw:b-sbqft9) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L58)):*
> ```C
> 
>     __asm__ volatile("" ::: "memory");
>     printf("Got %d SIGFPE signal(s)\n", sigfpe_ctr);
> ```

Can we add a check for an expected `sigfpe_ctr` value here?


<!-- Sent from Reviewable.io -->

2020-09-29 14:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: 5 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP1ylLCHa-YCF2fUui:-MIPDGiO-RHo_vIhzbW-:b-7cmmoe) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need to set `.sa_flags` here as well, at least to `SA_SIGINFO` (potentially also: `SA_ONSTACK`).
</blockquote></details>

Done. We hit the segfault even without the use of alternate stack, so didn't add `SA_ONSTACK`.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP2LYtC_u7z4w83tBi:-MIPDj2LDPMjPLnv0oRK:b-qefv0h) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not blocking, just for the future: `err` is a nice shorthand for these two calls.
</blockquote></details>

I don't like this because in some cases we don't have any errno to report (like below). And we end up using two different ways of reporting failures in the same program. A matter of taste.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP5ILQ6tEReR78_Mkj:-MIPEW9c6SP-tB2I-9cL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If `argc` stays, please add a check that it's really `1`.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP3qMOBEMfgaVcTltK:-MIPEL6q9BmWVmN72HJ7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This needs to be 16-byte aligned.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP40UcDIlnMF0OzU10:-MIPEeSn7dhTpeu8Dtrw:b-l1uzdz) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Since we are using inline assembly anyway, why not just use `movdqa` directly? We wouldn't need to worry about compiler optimizing out memory writes and use `argc` trick.
</blockquote></details>

Mostly because it would result in a lot of not-so-readable assembly code. I have no particular preference but using intrinsics felt right here. However, I agree that the `argc` trick is ugly, is there a simpler way to init an XMM register to some constant without the fear of optimize-out?
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MIPFMDC8KN75_VORE-h:bg5rqdo) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm not sure how "smart" is gcc around these areas, but can't it optimize away these comparisons? `xmm_reg` is not memory location and there there is no dependency on it in the inline asm.
</blockquote></details>

Not sure what you mean. How could GCC optimize this away? We take the `argc` precaution so that GCC doesn't know the actual XMM reg values.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP3mpT2hPGYcV4xFv3:-MIPGlCL76JNI8zdZ5wc:b-eu1ggl) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This looks like a good place to use `for` loop :)
</blockquote></details>

GCC is not that smart... `error: selector must be an integer constant in the range 0..7`. I don't want to fight against GCC, so I'll leave it as is.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP5NcF8Ln9tynYffHv:-MIPFcCW8dz5hxvKhFil:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can we add a check for an expected `sigfpe_ctr` value here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-29 16:02 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP2LYtC_u7z4w83tBi:-MIPVrtR6RLUJa6QFZ60:b-dzng1f) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this because in some cases we don't have any errno to report (like below). And we end up using two different ways of reporting failures in the same program. A matter of taste.
</blockquote></details>

There's `errx`, which does not append `strerror(errno)`.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP40UcDIlnMF0OzU10:-MIPa1ja5V0gbedxGSBw:b4e8raq) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Mostly because it would result in a lot of not-so-readable assembly code. I have no particular preference but using intrinsics felt right here. However, I agree that the `argc` trick is ugly, is there a simpler way to init an XMM register to some constant without the fear of optimize-out?
</blockquote></details>

Actually, this is just the same discussion about gcc optimizations, resolving this, let's just stick to the one thread below.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP3mpT2hPGYcV4xFv3:-MIPX98mE901TgV7_a7E:b-xjtrfk) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

GCC is not that smart... `error: selector must be an integer constant in the range 0..7`. I don't want to fight against GCC, so I'll leave it as is.
</blockquote></details>

Oh, ok.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MIPXIicCwGnyCTfexNp:bovcduv) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not sure what you mean. How could GCC optimize this away? We take the `argc` precaution so that GCC doesn't know the actual XMM reg values.
</blockquote></details>

1) Now we have a check for `argc`, which I think gcc is smart enough to notice.
2) I meant that gcc might be smart enough to notice that this xmm regiser is not changing, so it could skip using xmm at all, just replace those checks with something like `argc - 1 + 0 != 0` etc ...

Generally speaking, I'm not sure if we can express all we want to do here in C or C mixed with inline asm (setting a xmm regiser, doing div, then checking the reg value).


<!-- Sent from Reviewable.io -->

2020-09-29 16:29 UTC, yamahata approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_exit.c, line 70 at r2](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIPPLgKCUxKGfzwXxV9:-MIPPLgKCUxKGfzwXxVA:bl2exw) ([raw file](https://github.com/oscarlab/graphene/blob/0a7ec1cba7f55235ad13a05a2cb4752f0cdad1db/LibOS/shim/src/sys/shim_exit.c#L70)):*
> ```C
> 
>             if (append_signal(parent, &info) >= 0) {
>                 thread_wakeup(parent);
> ```

nice catch. Why has it hidden for so long?
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MIPcISX550PHN07KEkE:bf5tb5f) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) Now we have a check for `argc`, which I think gcc is smart enough to notice.
2) I meant that gcc might be smart enough to notice that this xmm regiser is not changing, so it could skip using xmm at all, just replace those checks with something like `argc - 1 + 0 != 0` etc ...

Generally speaking, I'm not sure if we can express all we want to do here in C or C mixed with inline asm (setting a xmm regiser, doing div, then checking the reg value).
</blockquote></details>

Although I haven't tested it, how about 

register __m128 xmm0 asm("xmm0")?
__asm__ volatile (" <set xmm0>": "=v"(xmm0));
...
___
*[LibOS/shim/test/regression/test_libos.py, line 494 at r2](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIPTlA23RI65AosfJD1:-MIPTlA23RI65AosfJD2:b-qi9ii) ([raw file](https://github.com/oscarlab/graphene/blob/0a7ec1cba7f55235ad13a05a2cb4752f0cdad1db/LibOS/shim/test/regression/test_libos.py#L494)):*
> ```
> 8
> ```

nitpick: signal.SIGFPE can be used instead of magic number.


<!-- Sent from Reviewable.io -->

2020-09-29 16:34 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/sys/shim_exit.c, line 70 at r2](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIPPLgKCUxKGfzwXxV9:-MIPhAo8EGbGsii8vUTu:b-h3425o) ([raw file](https://github.com/oscarlab/graphene/blob/0a7ec1cba7f55235ad13a05a2cb4752f0cdad1db/LibOS/shim/src/sys/shim_exit.c#L70)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nice catch. Why has it hidden for so long?
</blockquote></details>

I doubt this code is run often - it's the case of destroying a remote thread (thread in another process), whatever that would mean.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MIPhSqz9iGoEdsGP1W3:b-hdiq2b) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Although I haven't tested it, how about 

register __m128 xmm0 asm("xmm0")?
__asm__ volatile (" <set xmm0>": "=v"(xmm0));
...


</blockquote></details>

The problem is that gcc might use `xmm0` in between asm blocks - we cannot stop it from doing so ...


<!-- Sent from Reviewable.io -->

2020-09-30 09:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: 4 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_exit.c, line 70 at r2](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIPPLgKCUxKGfzwXxV9:-MIT9rh98pCq4DSQ4A9x:b-8j6gwd) ([raw file](https://github.com/oscarlab/graphene/blob/0a7ec1cba7f55235ad13a05a2cb4752f0cdad1db/LibOS/shim/src/sys/shim_exit.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I doubt this code is run often - it's the case of destroying a remote thread (thread in another process), whatever that would mean.
</blockquote></details>

Well, this scenario doesn't happen often: the parent must be blocked on a non-waitpid syscall for this particular code to become a bug. Parent processes typically wait via `waitpid()` or similar, but my particular program (where this bug manifests) actually used `poll()` to wait.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP2LYtC_u7z4w83tBi:-MITBL0e9ya6s_Fwogd9:b-uqmyfz) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There's `errx`, which does not append `strerror(errno)`.
</blockquote></details>

Done. I learned something.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP40UcDIlnMF0OzU10:-MITKNLb8Y4mNuUr5mDf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, this is just the same discussion about gcc optimizations, resolving this, let's just stick to the one thread below.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MITKPuvEinRQ7wIA-eJ:b-uspc4x) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The problem is that gcc might use `xmm0` in between asm blocks - we cannot stop it from doing so ...
</blockquote></details>

Done. Ok, you pressed me enough to re-write everything in inline asm. Turned out to be extremely simple :) I wrote three separate asm blocks for readability, not sure if you agree.
___
*[LibOS/shim/test/regression/test_libos.py, line 494 at r2](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIPTlA23RI65AosfJD1:-MITNZ1235LjCjLYkj0n:bat1g4g) ([raw file](https://github.com/oscarlab/graphene/blob/0a7ec1cba7f55235ad13a05a2cb4752f0cdad1db/LibOS/shim/test/regression/test_libos.py#L494)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> 8
> ```

nitpick: signal.SIGFPE can be used instead of magic number.

</blockquote></details>

Done. In other places as well (all in a separate commit).


<!-- Sent from Reviewable.io -->

2020-09-30 15:06 UTC, boryspoplawski requested changes
> Reviewed 1 of 6 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MIUXf8HAr3aDHTA1eD2:bskhfsc) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Ok, you pressed me enough to re-write everything in inline asm. Turned out to be extremely simple :) I wrote three separate asm blocks for readability, not sure if you agree.
</blockquote></details>

Good idea with a out memory buffer!
Unfortunately I do not agree, this should be one asm block. There's nothing blocking gcc from changing xmm0 in between these blocks :)


<!-- Sent from Reviewable.io -->

2020-09-30 15:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIP4rlY4GyiEfSGsngW:-MIUhuCf19ubfrj7RWrc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3d10b9c30c577e23bd8648b207e3a9c9580ec88a/LibOS/shim/test/regression/sighandler_divbyzero.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Good idea with a out memory buffer!
Unfortunately I do not agree, this should be one asm block. There's nothing blocking gcc from changing xmm0 in between these blocks :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-30 16:08 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-09-30 16:46 UTC, mkow requested changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIUqyRH5X-k9ep-qgmW:-MIUqyRI0oHIhSo6qPiA:bc4icfe) ([raw file](https://github.com/oscarlab/graphene/blob/894976c290ad7cb0363c1404c140713ff9091b3a/LibOS/shim/test/regression/sighandler_divbyzero.c#L50)):*
> ```C
> 
>     for (int i = 0; i < 8; i++) {
>         if (out[i] != i) {
> ```

I'd prefer `out[i] != in[i]`


<!-- Sent from Reviewable.io -->

2020-09-30 17:03 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-30 17:03 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-09-30 20:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: 1 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/test/regression/sighandler_divbyzero.c, line 50 at r4](https://reviewable.io/reviews/oscarlab/graphene/1852#-MIUqyRH5X-k9ep-qgmW:-MIVgrLHAxwfDkkK2uvp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/894976c290ad7cb0363c1404c140713ff9091b3a/LibOS/shim/test/regression/sighandler_divbyzero.c#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer `out[i] != in[i]`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-30 21:13 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-09-30 21:15 UTC, yamahata approved these changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1852)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-30 21:56 UTC, merged