[Pal/Linux-SGX] Remove "sgx.allow_file_creation" and always allow it
oscarlab/graphene pull request #1865
Opened 2020-10-02 10:21 UTC by dimakuv

## Description of the changes 

The manifest option "sgx.allow_file_creation" is useless (most real-world apps will set it to "1" anyway). So this PR simply removes this option and always allows to create files.

## How to test this PR? 

All tests must pass (removed this option from some regression tests). Also I manually tested PyTorch, it still works.

2020-10-02 12:07 UTC, mkow requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1865)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1865#-MIdBk7P52Lup6jlQAJ9:-MIdBk7P52Lup6jlQAJA:b-1abqos) (no related file):*
You left 4 occurrences of `sgx.allow_file_creation` in GSC.

---


<!-- Sent from Reviewable.io -->

2020-10-05 07:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1865)* status: 12 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1865#-MIdBk7P52Lup6jlQAJ9:-MIrgBFS46jJuAohayRf:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You left 4 occurrences of `sgx.allow_file_creation` in GSC.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-10-05 10:13 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1865)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-05 19:00 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (SGX workers failed in Jenkins in a previous run)

2020-10-05 19:00 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04 please (SGX workers failed in Jenkins in a previous run)

2020-10-05 19:01 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04-apps please (SGX workers failed in Jenkins in a previous run)

2020-10-05 19:24 UTC, yamahata approved these changes
This is a candidate for release notes because this is user-visible incompatible change.

If this affects many users (it may be surprising to silently ignore it), a warning can be issued when manifest still has sgx.allow_file_creation item. But I don't know about.

> Reviewed 12 of 12 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1865#-:-MIuBDNBEu71SxjNsI8y:b6m0h78)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-06 08:01 UTC, yamahata approved these changes
> Reviewed 1 of 12 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1865)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-06 12:04 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1865)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-06 12:09 UTC, merged