[LibOS,PAL] Add sched_setaffinity/sched_getaffinity syscall support
oscarlab/graphene pull request #1866
Opened 2020-10-02 10:39 UTC by vijaydhanraj

[LibOS,PAL] Add sched_setaffinity/sched_getaffinity syscall support

This patch address 2 things,
1. Adds syscall support for setting/getting CPU affinity of thread
for graphene and graphene+SGX.
2. Fixes CPUID leaf B implementation to retrieve correct CPU topology
for graphene+SGX support.

Co-authored-by: Gary gordon.king@intel.com

Fixes #788
Fixes #1563

Please use the following newly added regression tests to validate the PR.
1. LibOS/shim/test/regression/sched_set_get_cpuaffinity.c
2. LibOS/shim/test/regression/pthread_set_get_affinity.c

2020-10-02 16:14 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 0 of 21 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe1LEqBrojWO7y6TKf:-MIe1LEqBrojWO7y6TKg:b-w4nt59) (no related file):*
Can you please split two logical change into two commits (in single PR).

---
___
*[Pal/src/db_threading.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe3aaHDswkcUT_VZ_E:-MIe3aaHDswkcUT_VZ_F:b-uqolcj) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/db_threading.c#L94)):*
> ```C
>     if (ret < 0) {
>         _DkRaiseFailure(-ret);
>         LEAVE_PAL_CALL_RETURN(ret);
> ```

Please delete this line. (Maybe a matter of taste.)
___
*[Pal/src/pal_internal.h, line 232 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe3lEZ8BgTYjVBYs0z:-MIe3lEZ8BgTYjVBYs1-:b-uixjcu) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/pal_internal.h#L232)):*
> ```objc
> int _DkThreadCreate(PAL_HANDLE* handle, int (*callback)(void*), const void* param);
> noreturn void _DkThreadExit(int* clear_child_tid);
> int _DkThreadDelayExecution (unsigned long * duration);
> ```

Unrelated change. Probably you need to rebase your changes onto master branch.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe4I0X9emqVlKrbAXx:-MIe4I0X9emqVlKrbAXy:b-dqaafz) ([raw file](https://github.com/oscarlab/graphene/blob/3c326a4c0ddcfd9fb207c96c257ee52133016283/Pal/src/host/Linux-SGX/db_threading.c#L61)):*
> ```C
>         if (!tmp->tcs) {
>             new_thread = tmp;
>             new_thread->tid = pal_assign_tid();
> ```

There is a race. see below.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 850 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe2OztDKaja9Y7-jBm:-MIe2OztDKaja9Y7-jBn:bpwpt0g) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/enclave_ocalls.c#L850)):*
> ```C
> 
>     if (!retval) {
>         *tid = READ_ONCE(ms->ms_tid);
> ```

There is a race between this thread and child (newly created) thread.
The child thread can refer thread->thread.tid before parent reaching this sentence.


<!-- Sent from Reviewable.io -->

2020-10-02 19:35 UTC, vijaydhanraj commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe1LEqBrojWO7y6TKf:-MIenmum-YK3z8DRaMIX:b-s4q0p8) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Can you please split two logical change into two commits (in single PR).
</blockquote></details>

sure, will split into 2 commits

---


<!-- Sent from Reviewable.io -->

2020-10-02 19:36 UTC, vijaydhanraj commented
___
*[Pal/src/db_threading.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe3aaHDswkcUT_VZ_E:-MIeo-sP8dQFAgOuBpmG:b-vebc0g) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/db_threading.c#L94)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Please delete this line. (Maybe a matter of taste.)
</blockquote></details>

yes, will take care of this in the next patch.


<!-- Sent from Reviewable.io -->

2020-10-02 19:37 UTC, vijaydhanraj commented
___
*[Pal/src/pal_internal.h, line 232 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe3lEZ8BgTYjVBYs0z:-MIeoJ3tDh6tsgj_uWuQ:b-58t2xy) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/pal_internal.h#L232)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Unrelated change. Probably you need to rebase your changes onto master branch.
</blockquote></details>

good catch, I will undo this.


<!-- Sent from Reviewable.io -->

2020-10-02 19:42 UTC, vijaydhanraj commented
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 850 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe2OztDKaja9Y7-jBm:-MIeoUey8m8BnR78nd-B:b-yetkt1) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/enclave_ocalls.c#L850)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

There is a race between this thread and child (newly created) thread.
The child thread can refer thread->thread.tid before parent reaching this sentence.
</blockquote></details>

yes, agree. Will look into this.


<!-- Sent from Reviewable.io -->

2020-10-05 10:44 UTC, dimakuv requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 67 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe1LEqBrojWO7y6TKf:-MIs3Yee-HzRSVK9qFJ5:b2ngtib) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

sure, will split into 2 commits
</blockquote></details>

+1.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs3iCGBoIGelEz7cmC:-MIs3iCGBoIGelEz7cmD:b-2g5o21) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L146)):*
> ```C
> 
> static int check_affinity_params(bool is_getaffinity,
>                                  int ncpus, 
> ```

There is a trailing whitespace here. Please check for them in your PR and remove them.
___
*[LibOS/shim/src/sys/shim_sched.c, line 159 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs41U4Co21Hg8SX3Tc:-MIs41U4Co21Hg8SX3Td:bkfzt3w) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L159)):*
> ```C
>     
>     /* Return -EINVAL for sched_getaffinity() when cpumask_size is 
>      * smaller than size of aafinity mask used by kernel.
> ```

Please realign this comment to 100-char wrap limit.
___
*[LibOS/shim/src/sys/shim_sched.c, line 160 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs45sL-jz4Ows6_1o8:-MIs45sL-jz4Ows6_1o9:bsii85b) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L160)):*
> ```C
>     /* Return -EINVAL for sched_getaffinity() when cpumask_size is 
>      * smaller than size of aafinity mask used by kernel.
>      * Refer: https://man7.org/linux/man-pages/man2/sched_getaffinity.2.html -EINVAL error notes.
> ```

We usually don't add comments about man pages. It is assumed that whoever reads the sources of Graphene know/read themselves. So I suggest to simply remove this line.
___
*[LibOS/shim/src/sys/shim_sched.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs4TmqD1B1jkVIpzeQ:-MIs4TmqD1B1jkVIpzeR:b-4sl2rh) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L165)):*
> ```C
>         debug("size of cpumask in affinity syscall must be %lu but supplied cpumask is only %lu\n",
>                bitmask_size_in_bytes,
>                cpumask_size);
> ```

We usually don't have a single line for each new argument. So please rewrite as one line: `bitmask_size_in_bytes, cpumask_size);`
___
*[LibOS/shim/src/sys/shim_sched.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7VFcAePqMoNigrei:-MIs7VFcAePqMoNigrej:b7cpz8x) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L178)):*
> ```C
> int shim_do_sched_setaffinity(pid_t pid, size_t cpusetsize, __kernel_cpu_set_t* user_mask_ptr) {
>     int ret;
>     PAL_HANDLE pal_thread = NULL;
> ```

This variable seems useless (see my other comments). Remove from here and just use `thread->pal_handle` where needed.
___
*[LibOS/shim/src/sys/shim_sched.c, line 183 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs82FgEuIN524o_9Ct:-MIs82FgEuIN524o_9Cu:b-xcop8u) ([raw file](https://github.com/oscarlab/graphene/blob/3c326a4c0ddcfd9fb207c96c257ee52133016283/LibOS/shim/src/sys/shim_sched.c#L183)):*
> ```C
>         return bitmask_size_in_bytes;
> 
>     memset(user_mask_ptr, 0, len);
> ```

I would keep this zero-out of the user mask in the new code, just for sanity.
___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MIs6GMSBecnIPywf86s:bochppp) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
> ```C
>     if (!thread)
>         return -ESRCH;
> ```

I would add an assert here that the found thread is not Graphene-internal, like this:
`assert(!is_internal(thread));`
___
*[LibOS/shim/src/sys/shim_sched.c, line 194 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6SO-6Ha6YRYb8yDS:-MIs6SO-6Ha6YRYb8yDT:b-m1tr4r) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L194)):*
> ```C
>     pal_thread = thread->pal_handle;
>     if (!pal_thread)
>         return -ESRCH;
> ```

I don't think it's possible that `thread` doesn't have a `pal_handle` initialized. Please do some investigation to double-check me, but I suggest to replace this IF clause with a simple assert:
`assert(thread->pal_handle);`
___
*[LibOS/shim/src/sys/shim_sched.c, line 196 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6llC7w7ThmJ1ronL:-MIs6llC7w7ThmJ1ronM:b6kbhb6) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L196)):*
> ```C
>         return -ESRCH;
> 
>     put_thread(thread);
> ```

Why here? This looks wrong: what if this `thread` is freed in the meantime, and we end up with a meaningless `DkThreadSetCpuAffinity(<dangling-pointer-to-pal-handle>)`?

I suggest to move this `put_thread(thread)` to the very end of this function, before return. This guarantees that `thread` is not freed until the end of this func.

Also, on each error-handling return, you must add `put_thread(thread)` to prevent memory leaks.
___
*[LibOS/shim/src/sys/shim_sched.c, line 198 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs5zzL6mcPogoV1wff:-MIs5zzL6mcPogoV1wfg:b-mmzojk) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L198)):*
> ```C
>     put_thread(thread);
> 
>     int bitmask_size_in_bytes = check_affinity_params(false, ncpus, cpusetsize, user_mask_ptr);
> ```

We usually add an explanation-comment before false/true arguments. Please rewrite like this:
`check_affinity_params(/*is_getaffinity=*/false, ncpus, cpusetsize, user_mask_ptr)`
___
*[LibOS/shim/src/sys/shim_sched.c, line 211 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7hLx1-uBITTzqLGK:-MIs7hLx1-uBITTzqLGL:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L211)):*
> ```C
> int shim_do_sched_getaffinity(pid_t pid, size_t cpusetsize, __kernel_cpu_set_t* user_mask_ptr) {
>     int ret;
>     PAL_HANDLE pal_thread = NULL;
> ```

ditto
___
*[LibOS/shim/src/sys/shim_sched.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7k0-3OvT9hYxO1i_:-MIs7k0-3OvT9hYxO1ia:b-tl657j) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L225)):*
> ```C
>         return -ESRCH;
> 
>     pal_thread = thread->pal_handle;
> ```

ditto 2x
___
*[LibOS/shim/src/sys/shim_sched.c, line 229 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7mYB90hPrh4iDSeX:-MIs7mYC0WOiDa1TwVqx:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L229)):*
> ```C
>         return -ESRCH;
> 
>     put_thread(thread);
> ```

ditto
___
*[LibOS/shim/src/sys/shim_sched.c, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7nYL1ttZaw4ncyiA:-MIs7nYL1ttZaw4ncyiB:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys [...]

2020-10-05 11:29 UTC, vijaydhanraj commented
Thanks for the review @dimakuv. I just forced pushed the changes based on @yamahata's review comments. I will address your changes in the next fixup.

2020-10-05 19:14 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 4 of 22 files reviewed, 69 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r2](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIu77BXAr9cAz7PGJI5:-MIu77BXAr9cAz7PGJI6:b-umdunt) ([raw file](https://github.com/oscarlab/graphene/blob/19bdcac4acb44e91606b5a392dcd55a464f60bf0/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
> ```C
>         if (!tmp->tcs) {
>             new_thread = tmp;
>             new_thread->tid = tid;
> ```

Can you please add a comment on the race?
Also can  you please add check if new_thread->tid == 0 || new_thread->tid == tid to shield it from untrusted code lying.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 98 at r2](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIu8K9lAarqqco8DP9_:-MIu82Es6ANgiX7X4vby:bc0k56y) ([raw file](https://github.com/oscarlab/graphene/blob/19bdcac4acb44e91606b5a392dcd55a464f60bf0/Pal/src/host/Linux-SGX/db_threading.c#L98)):*
> ```C
>     if (IS_ERR(ret))
>         return unix_to_pal_error(ERRNO(ret));
> ```

Here you still have a race.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1490 at r2](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIuAIuw7QKmEfebXPLt:-MIuAIux-1cQcw0bmIc1:by10sdf) ([raw file](https://github.com/oscarlab/graphene/blob/19bdcac4acb44e91606b5a392dcd55a464f60bf0/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1490)):*
> ```
> ((tid == 0) ? sgx_ocall(OCALL_SCHED_SETAFFINITY, ms
> ```

In libos side, pal_handle for thread is always non-NULL. So we don't have to consider it.
assert (tid != 0) can be put.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1517 at r2](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIuAUmbAA6E6YH-BLrw:-MIuAUmbAA6E6YH-BLrx:blap53) ([raw file](https://github.com/oscarlab/graphene/blob/19bdcac4acb44e91606b5a392dcd55a464f60bf0/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1517)):*
> ```
> (tid == 0) ? sgx_ocall(OCALL_SCHED_GETAFFINITY, ms)
> ```

ditto.


<!-- Sent from Reviewable.io -->

2020-10-07 10:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 4 of 22 files reviewed, 69 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe1LEqBrojWO7y6TKf:-MJ1Evlb8J93ZrCffkfk:bb7f2mf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1.
</blockquote></details>

done

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs3iCGBoIGelEz7cmC:-MIzCEfq8aXlBcJQMVwl:bkoo2p1) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is a trailing whitespace here. Please check for them in your PR and remove them.
</blockquote></details>

Sorry for the timing but the current version in github does fix this.
___
*[LibOS/shim/src/sys/shim_sched.c, line 159 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs41U4Co21Hg8SX3Tc:-MIzCtmn1eycezW9LTHi:br7hrpf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please realign this comment to 100-char wrap limit.
</blockquote></details>

Removed this line itself as suggested in the next comment.
___
*[LibOS/shim/src/sys/shim_sched.c, line 160 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs45sL-jz4Ows6_1o8:-MIzCyHV1C8dG41wI2Tq:bai136l) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We usually don't add comments about man pages. It is assumed that whoever reads the sources of Graphene know/read themselves. So I suggest to simply remove this line.
</blockquote></details>

Removed this line.
___
*[LibOS/shim/src/sys/shim_sched.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs4TmqD1B1jkVIpzeQ:-MIzDIzt99qOtzGGlWfA:b-2alwb4) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We usually don't have a single line for each new argument. So please rewrite as one line: `bitmask_size_in_bytes, cpumask_size);`
</blockquote></details>

Since this exceeded more than 100 chars, split into multiple line as suggested in our coding style page. But I am fine to add this in a single line, please suggest.
___
*[LibOS/shim/src/sys/shim_sched.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7VFcAePqMoNigrei:-MIzE3Kc6kLfDY6whcU-:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This variable seems useless (see my other comments). Remove from here and just use `thread->pal_handle` where needed.
</blockquote></details>

done
___
*[LibOS/shim/src/sys/shim_sched.c, line 183 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs82FgEuIN524o_9Ct:-MJ-DNQWC63OWxO_42EB:b2lj10x) ([raw file](https://github.com/oscarlab/graphene/blob/3c326a4c0ddcfd9fb207c96c257ee52133016283/LibOS/shim/src/sys/shim_sched.c#L183)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would keep this zero-out of the user mask in the new code, just for sanity.
</blockquote></details>

General expectation is that applications will use macros like CPU_ZERO etc to clear out the buffer before making the syscall. So felt zeroing out the mask was redundant.But will add this memset anyways.
___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MIzEw5C18ZTS4fFcBf8:bs0tx4) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would add an assert here that the found thread is not Graphene-internal, like this:
`assert(!is_internal(thread));`
</blockquote></details>

okay, will add the assert after thread NULL check.
___
*[LibOS/shim/src/sys/shim_sched.c, line 194 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6SO-6Ha6YRYb8yDS:-MIzGl3JDGKNgyIzwqSc:b-9zh1gz) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think it's possible that `thread` doesn't have a `pal_handle` initialized. Please do some investigation to double-check me, but I suggest to replace this IF clause with a simple assert:
`assert(thread->pal_handle);`
</blockquote></details>

yes you are correct. We do check for NULL pal_handle when creating the thread. So I will remove the check. I think we can also avoid the assert here. Pls suggest.
___
*[LibOS/shim/src/sys/shim_sched.c, line 196 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6llC7w7ThmJ1ronL:-MIzJATH-NUTrdrdQL1R:b-genkj1) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L196)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why here? This looks wrong: what if this `thread` is freed in the meantime, and we end up with a meaningless `DkThreadSetCpuAffinity(<dangling-pointer-to-pal-handle>)`?

I suggest to move this `put_thread(thread)` to the very end of this function, before return. This guarantees that `thread` is not freed until the end of this func.

Also, on each error-handling return, you must add `put_thread(thread)` to prevent memory leaks.
</blockquote></details>

got it, will do so.
___
*[LibOS/shim/src/sys/shim_sched.c, line 198 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs5zzL6mcPogoV1wff:-MIzLF271qtwEqhk2aG4:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L198)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We usually add an explanation-comment before false/true arguments. Please rewrite like this:
`check_affinity_params(/*is_getaffinity=*/false, ncpus, cpusetsize, user_mask_ptr)`
</blockquote></details>

done
___
*[LibOS/shim/src/sys/shim_sched.c, line 211 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7hLx1-uBITTzqLGK:-MIzLNNF4z5Fk6C9406J:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L211)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done
___
*[LibOS/shim/src/sys/shim_sched.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7k0-3OvT9hYxO1i_:-MIzLQi27R-uUin7AKVs:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L225)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto 2x
</blockquote></details>

done
___
*[LibOS/shim/src/sys/shim_sched.c, line 229 at r1](https://reviewable. [...]

2020-10-07 11:26 UTC, vijaydhanraj commented
Sorry, did a rebase of my branch by force of practice and needed to do a force-push again.

2020-10-07 23:28 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 2 of 24 files reviewed, 69 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MJ4JxIX9erwmtEpBlc_:b-z5leo4) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

okay, will add the assert after thread NULL check.
</blockquote></details>

In theory, application can pass any invalid pid value. So instead of assert, it should be
if (is_internal(thread)) return -ESRCH
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJ4N2wNABmO9AMLu1Bt:b7xgb8k) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
> ```C
>                       "cmp $0, %%rax\n"
>                       "jne loop\n"
>                       : /*no outs*/ : /*no ins*/ : "%rax");
> ```

pthread_getaffinity_no(self) == the one set by main()?
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 52 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4KYNV4E-SXxosH5Zk:-MJ4KYNV4E-SXxosH5Zl:ba23ltx) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L52)):*
> ```
> ········
> ```

nitpick: unintended tab/space.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsLkPE7NGSWF8WSw3V:-MJ4HmA-2Bmltcy1x-Z2:btptwyw) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_threading.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Addressed this by making the ocall logic to ecall and also ensuring that tid is updated in the pal_start_thread() function. This will make sure LibOS cannot access the tid before and also in PAL since no one seems to manipulate this variable, we should be fine.

This change is already present. Added this as part of splitting the patch into 2.
</blockquote></details>

Let's continue the discussion on race here.
So the options are
a. parent thread waits (spin-loop) in _DkThreadCreate for tid to be filled by child.
    (child can wait for parent. But child tends to get scheduler before parent.)
b. both parent and child thread get tid and both fill tid. (and if they checks the old tid value is 0 or same)
c. don't address the race in PAL layer for now. (add a comment on it) LibOS doesn't access it in racy way. 

a is simpler than b. but may cause unnecessary spin-loop
b may cause a bit complexity
c. Personally I don't prefer this because it breaks PAL abstraction.
So I vote for a or b


<!-- Sent from Reviewable.io -->

2020-10-08 01:26 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 2 of 24 files reviewed, 69 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MJ4b_TG7h9lkQ6igP8J:b-hhy291) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

In theory, application can pass any invalid pid value. So instead of assert, it should be
if (is_internal(thread)) return -ESRCH

</blockquote></details>

The PID that applications pass to graphene  is of type int. This can have a range of values between -2,147,483,648 to 2,147,483,647. But our internal threads are greater than or equal to INTERNAL_TID_BASE which is 2147483648. So I think, we should assert here as the PID is not even in the acceptable range. Pls let me know if I misunderstood.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJ4hnJsBG6WjiFhnBQ_:b-oa0raa) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

pthread_getaffinity_no(self) == the one set by main()?
</blockquote></details>

I think you are referring to pthread_setaffinity_np(pthread_self()) right? If so, yes this is the ID of the main(). This has an internal thread ID of 1 in graphene.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 52 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4KYNV4E-SXxosH5Zk:-MJ4hd8b7gQ2hDwr_2c5:b-l0lbj7) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L52)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> ········
> ```

nitpick: unintended tab/space.
</blockquote></details>

yes fixed this tab
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsLkPE7NGSWF8WSw3V:-MJ4iSlk5uRuPeKBBGKI:bz4237w) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_threading.c#L57)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Let's continue the discussion on race here.
So the options are
a. parent thread waits (spin-loop) in _DkThreadCreate for tid to be filled by child.
    (child can wait for parent. But child tends to get scheduler before parent.)
b. both parent and child thread get tid and both fill tid. (and if they checks the old tid value is 0 or same)
c. don't address the race in PAL layer for now. (add a comment on it) LibOS doesn't access it in racy way. 

a is simpler than b. but may cause unnecessary spin-loop
b may cause a bit complexity
c. Personally I don't prefer this because it breaks PAL abstraction.
So I vote for a or b

</blockquote></details>

For option #c, even though there is no race in PAL layer now what about we add a wait like option #a? So it will be like option #a but instead of getting the tid from clone ocall we get it from thread start ecall.


<!-- Sent from Reviewable.io -->

2020-10-09 01:51 UTC, yamahata reviewed
> Reviewed 2 of 21 files at r1, 13 of 21 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 69 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MJA-1Y1DI_jt-JElibq:beda0s1) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The PID that applications pass to graphene  is of type int. This can have a range of values between -2,147,483,648 to 2,147,483,647. But our internal threads are greater than or equal to INTERNAL_TID_BASE which is 2147483648. So I think, we should assert here as the PID is not even in the acceptable range. Pls let me know if I misunderstood.
</blockquote></details>

Isn't it too dependent on the internal implementation which is subject to change?
I prefer to check it by is_internal().
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJA0gwz-IXYz6D4sVE6:b-h7yo4e) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think you are referring to pthread_setaffinity_np(pthread_self()) right? If so, yes this is the ID of the main(). This has an internal thread ID of 1 in graphene.
</blockquote></details>

I meant to add a check if
assert(pthread_getaffinit_np(pthread_self()) == the one set by main thread);

pthread_attr_set/getaffinity_np() only store the parameter into the variable. And pthread_create() issues sched_setattr(). So I'd like to see sched_getattr() exercised by pthread_getaffinity_np().
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsLkPE7NGSWF8WSw3V:-MJA1YfzCeYv1oP2sHLO:b-otm4m2) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_threading.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

For option #c, even though there is no race in PAL layer now what about we add a wait like option #a? So it will be like option #a but instead of getting the tid from clone ocall we get it from thread start ecall.
</blockquote></details>

Do you mean the following?
- parent sets tid
- child waits for tid to be set

It should work.


<!-- Sent from Reviewable.io -->

2020-10-09 18:01 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 69 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MJDQFP48pR2Wm98Qmrp:b6dwacm) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Isn't it too dependent on the internal implementation which is subject to change?
I prefer to check it by is_internal().

</blockquote></details>

pid_t type being int has been there for a long time so I wouldn't see a sudden change. But I will agree with you and make it future proof. I will change assert(!is_internal(thread)); to if (is_internal(thread)) return -ESRCH;
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJDQsWt-FagN8QK_Ed1:b-mtd8cb) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

I meant to add a check if
assert(pthread_getaffinit_np(pthread_self()) == the one set by main thread);

pthread_attr_set/getaffinity_np() only store the parameter into the variable. And pthread_create() issues sched_setattr(). So I'd like to see sched_getattr() exercised by pthread_getaffinity_np().
</blockquote></details>

Sure, will add this check
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsLkPE7NGSWF8WSw3V:-MJDQxP4E2bNsJY9jHpV:bolieqg) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_threading.c#L57)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Do you mean the following?
- parent sets tid
- child waits for tid to be set

It should work.
</blockquote></details>

Yes, that was my earlier implementation (my earlier wording seems confusing :), sorry about that). What I wanted to clarify with reviewers is, option #C (which is the current implementation in the PR) and #A are very similar just that in option #A we wait in the parent for tid to be filled by the child even though there isn't a race currently. This is for future-proofing at the expense of performance.


<!-- Sent from Reviewable.io -->

2020-10-10 17:07 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 69 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsLkPE7NGSWF8WSw3V:-MJISMRA67hka3gSJJaw:bz87dit) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_threading.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, that was my earlier implementation (my earlier wording seems confusing :), sorry about that). What I wanted to clarify with reviewers is, option #C (which is the current implementation in the PR) and #A are very similar just that in option #A we wait in the parent for tid to be filled by the child even though there isn't a race currently. This is for future-proofing at the expense of performance.
</blockquote></details>

I’m discussing about leaking race beyond the layer. 
I think the race should be resolved within pal. not by above layer.
Your previous implementation leaked the race from pal to libps. and libos incidentally solved it.

There are multiple implementations for pal interface. there can be multiple user of Pal. not only our Libos. 


<!-- Sent from Reviewable.io -->

2020-10-11 09:18 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 69 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsLkPE7NGSWF8WSw3V:-MJKbNvZ41zPjkh6NI6L:bm0jnou) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_threading.c#L57)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

I’m discussing about leaking race beyond the layer. 
I think the race should be resolved within pal. not by above layer.
Your previous implementation leaked the race from pal to libps. and libos incidentally solved it.

There are multiple implementations for pal interface. there can be multiple user of Pal. not only our Libos. 
</blockquote></details>

Thanks @yamahata for the clarification.
One things I am trying to wrap my head around is the race within multiple users of PAL. Can you please give an example?

Does the below flow demonstrate the race within PAL?
1. LibOS wants to clone for say Thread A. It calls _DkThreadCreate() assigns a new PAL_HANDLE and sets callback and param in the pal_handle_thread. 
2. Next, LibOS calls clone for say Thread B.  It calls _DkThreadCreate() assigns a new PAL_HANDLE and sets callback and param in the pal_handle_thread. 
3. Normally Thread A would enter enclave first but due to race, Thread B enters enclave first (pal_thread_start), looks for the first pal_handle_thread with NULL tcs and updates tid. But in reality, this pal_handle_thread is part of PAL_HANDLE which was assigned for Thread A.


<!-- Sent from Reviewable.io -->

2020-10-11 14:43 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 71 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN4NTB75qRjgYwPY7Z:-MJN4NTF7Wl-xetOeSCH:b-e3oa15) (no related file):*
I checked sgx_thread.c. I totally forgot about tcs and host tid.
- tcs should br passed to ocall. not host tid.
- the race is a existing bug to be fixed.
- only child thread knows tcs. so parent should wait for tcs to be filled before _DkThreadCreate returnin to resolve the race.

---
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 177 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN5o_H-Uj033WGg2jO:-MJN5o_K7gsHInb58bau:b-6h835f) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/Pal/src/host/Linux-SGX/ocall_types.h#L177)):*
> ```objc
> 
> typedef struct {
>     int ms_tid;
> ```

this should be void* tcs


<!-- Sent from Reviewable.io -->

2020-10-11 20:11 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 71 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN4NTB75qRjgYwPY7Z:-MJOAXPV3DW-E6Iapz4W:b-ve7rk4) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

I checked sgx_thread.c. I totally forgot about tcs and host tid.
- tcs should br passed to ocall. not host tid.
- the race is a existing bug to be fixed.
- only child thread knows tcs. so parent should wait for tcs to be filled before _DkThreadCreate returnin to resolve the race.
</blockquote></details>

Hi @ all reviewers, again it was my bad. I did git rebase after the first round of comments and had to do a force-push. So we don't have incremental changes. Sorry for the confusion caused due to this.

Regarding the code implementation, I had 2 designs
1. ocall approach: Here the parent passed pointer to store the tid through the ocall. I had removed updating the tid in the child (in pal_thread_start). But one issue with this approach is that, child usually starts first and adds the  new cloned thread as part of shim threads. Given this, LibOS could see a invalid tid. (Shim thread->Pal_handle->pal_handle_thread->tid)
2. ecall approach (current design in the github PR): Here the parent just invokes the clone ocall (no tid is passed to ocall). While child does an enclave entry, tid is updated as part of this. Advantage of this approach is that LibOS will not see an invalid tid.

But on my discussion below with @yamahata (sorry not sure how to link the discussion here), it looks like we have a existing race bug to the fixed. The fix can be as simple as adding a spin-lock where parent waits till tid != 0 as mentioned by @dimakuv and @yamahata . 

If everyone is fine, I propose to have ecall approach with a spin-lock in  _DkThreadCreate where parent waits till tid !=0 . Please let me know your thoughts/suggestions.

---
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 177 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN5o_H-Uj033WGg2jO:-MJOGFj4BOAMHmVNBVhb:b-l76z85) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/Pal/src/host/Linux-SGX/ocall_types.h#L177)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

this should be void* tcs
</blockquote></details>

This is the previous design. Current design doesn't pass tid via ocall.


<!-- Sent from Reviewable.io -->

2020-10-12 10:46 UTC, dimakuv requested changes
> Reviewed 13 of 21 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN4NTB75qRjgYwPY7Z:-MJRPjYwBuu6qS8qI9Eg:b-t1oed4) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Hi @ all reviewers, again it was my bad. I did git rebase after the first round of comments and had to do a force-push. So we don't have incremental changes. Sorry for the confusion caused due to this.

Regarding the code implementation, I had 2 designs
1. ocall approach: Here the parent passed pointer to store the tid through the ocall. I had removed updating the tid in the child (in pal_thread_start). But one issue with this approach is that, child usually starts first and adds the  new cloned thread as part of shim threads. Given this, LibOS could see a invalid tid. (Shim thread->Pal_handle->pal_handle_thread->tid)
2. ecall approach (current design in the github PR): Here the parent just invokes the clone ocall (no tid is passed to ocall). While child does an enclave entry, tid is updated as part of this. Advantage of this approach is that LibOS will not see an invalid tid.

But on my discussion below with @yamahata (sorry not sure how to link the discussion here), it looks like we have a existing race bug to the fixed. The fix can be as simple as adding a spin-lock where parent waits till tid != 0 as mentioned by @dimakuv and @yamahata . 

If everyone is fine, I propose to have ecall approach with a spin-lock in  _DkThreadCreate where parent waits till tid !=0 . Please let me know your thoughts/suggestions.
</blockquote></details>

I'm fine with the current ECALL approach. You seem to have added a FIXME comment, so we can postpone fixing this (currently benign) data race to another PR. I'm fine with that.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs4TmqD1B1jkVIpzeQ:-MJRAu6x67sh31n7pjFg:bkwhlz9) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L165)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Since this exceeded more than 100 chars, split into multiple line as suggested in our coding style page. But I am fine to add this in a single line, please suggest.
</blockquote></details>

I meant like this:
```
        debug("size of cpumask in affinity syscall must be %lu but supplied cpumask is only %lu\n",
               bitmask_size_in_bytes, cpumask_size);
```
___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MJRBht69OGDTEvLFEFY:b-fdkcr6) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

pid_t type being int has been there for a long time so I wouldn't see a sudden change. But I will agree with you and make it future proof. I will change assert(!is_internal(thread)); to if (is_internal(thread)) return -ESRCH;
</blockquote></details>

This is not yet done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 194 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6SO-6Ha6YRYb8yDS:-MJRC66eA0h5n7iHc0LX:bsvf1ft) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L194)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes you are correct. We do check for NULL pal_handle when creating the thread. So I will remove the check. I think we can also avoid the assert here. Pls suggest.
</blockquote></details>

OK, let's not add the assert. The code is fine as is.
___
*[LibOS/shim/src/sys/shim_sched.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7k0-3OvT9hYxO1i_:-MJRCJDtEQHChi5mA514:b-9645qf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L225)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

done
</blockquote></details>

Typo: `prevent`
___
*[LibOS/shim/src/sys/shim_sched.c, line 229 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7mYB90hPrh4iDSeX:-MJRCLji3VE7NcZFdQVc:b-awopls) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L229)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

done
</blockquote></details>

Not yet done, we agreed to use `if ...` instead of assert.
___
*[LibOS/shim/src/sys/shim_sched.c, line 160 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRBDjy4NxlNF9hxrTN:-MJRBDjy4NxlNF9hxrTO:b-v2davj) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/src/sys/shim_sched.c#L160)):*
> ```C
>     /* Return -EINVAL for sched_getaffinity() when cpusetsize is
>      * smaller than size of affinity mask used by kernel.
>      */
> ```

Actually, the debug message + code already say the same info as this comment. So I suggest to remove this comment altogether, since it just duplicates the code.
___
*[LibOS/shim/src/sys/shim_sched.c, line 162 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRBMXS7IJ3Xsn6SadY:-MJRBMXS7IJ3Xsn6SadZ:b-qxg9si) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/src/sys/shim_sched.c#L162)):*
> ```C
>      */
>     if (is_getaffinity && (cpumask_size < bitmask_size_in_bytes)) {
>         debug("size of cpumask in affinity syscall must be %lu but supplied cpumask is only %lu\n",
> ```

`in affinity syscall` -> `in getaffinity syscall`
___
*[LibOS/shim/src/sys/shim_sched.c, line 189 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRCDc3-DkduuwTsRVT:-MJRCDc3-DkduuwTsRVU:b-9645qf) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/src/sys/shim_sched.c#L189)):*
> ```C
>         return -ESRCH;
> 
>     /* Increase the thread count to prvent it from being freed */
> ```

Typo: `prevent`
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRCrZBCOVnQaFecg4G:-MJRCrZBCOVnQaFecg4H:b-q8bm5n) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L15)):*
> ```C
> #include <err.h>
> #include <errno.h>
> #include <sys/syscall.h>
> ```

Please sort these includes.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRCw0wEat8mapC15zH:-MJRCw0wEat8mapC15zI:b20gce2) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L17)):*
> ```C
> #include <sys/syscall.h>
> 
> /* Set large busy loops so that we can verify affinity with htop*/
> ```

`...with htop manually */`
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRDNb-CU_nYTNwjTKV:-MJRDNb-CU_nYTNwjTKW:b1mywfi) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
> ```C
>                       "cmp $0, %%rax\n"
>    [...]

2020-10-12 23:51 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 19 of 24 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN4NTB75qRjgYwPY7Z:-MJTPrtf82S8LyYX1YB2:berbzpw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with the current ECALL approach. You seem to have added a FIXME comment, so we can postpone fixing this (currently benign) data race to another PR. I'm fine with that.
</blockquote></details>

@yamahata, regarding "tcs should br passed to ocall. not host tid." now that the code is changed, I think your comment is outdated. If you think it is still valid, can you give more details? 

@dimakuv, thanks but as @yamahata suggested I will add a spin loop and wait till tid != 0 in the parent ( _DkThreadCreate)

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs4TmqD1B1jkVIpzeQ:-MJTvG0a01l75RccGZkr:b-2ojg2x) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I meant like this:
```
        debug("size of cpumask in affinity syscall must be %lu but supplied cpumask is only %lu\n",
               bitmask_size_in_bytes, cpumask_size);
```
</blockquote></details>

ok, done
___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs6GMSBecnIPywf86r:-MJTvJSK5LxpEHYO2dUM:b-vr2rtf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not yet done.
</blockquote></details>

yes true, was waiting to close the discussion on other comments before pushing the changes. Please check in the latest fixup.
___
*[LibOS/shim/src/sys/shim_sched.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7k0-3OvT9hYxO1i_:-MJTw-8R9ng7HJbN03TW:buyydde) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L225)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `prevent`
</blockquote></details>

Fixed it.
___
*[LibOS/shim/src/sys/shim_sched.c, line 229 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIs7mYB90hPrh4iDSeX:-MJTw3ZIAcwZDGLYjiS-:b-vr2rtf) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/LibOS/shim/src/sys/shim_sched.c#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not yet done, we agreed to use `if ...` instead of assert.
</blockquote></details>

yes true, was waiting to close the discussion on other comments before pushing the changes. Please check in the latest fixup.
___
*[LibOS/shim/src/sys/shim_sched.c, line 160 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRBDjy4NxlNF9hxrTN:-MJTw_m5Ejyt2UPHkil5:b-ioi05e) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/src/sys/shim_sched.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, the debug message + code already say the same info as this comment. So I suggest to remove this comment altogether, since it just duplicates the code.
</blockquote></details>

sure, removed the comment.
___
*[LibOS/shim/src/sys/shim_sched.c, line 162 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRBMXS7IJ3Xsn6SadY:-MJTwsxSCW7FS5266z9k:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/src/sys/shim_sched.c#L162)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`in affinity syscall` -> `in getaffinity syscall`
</blockquote></details>

done
___
*[LibOS/shim/src/sys/shim_sched.c, line 189 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRCDc3-DkduuwTsRVT:-MJTwuLcBNFf-YNs0QNG:busaxrw) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/src/sys/shim_sched.c#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `prevent`
</blockquote></details>

Fixed it
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRCrZBCOVnQaFecg4G:-MJU-1IC2FcDMytJC1Ar:b-588ttz) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L15)):*
> Please sort these includes.
done
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRCw0wEat8mapC15zH:-MJU-44OA48TShmTwPQb:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...with htop manually */`
</blockquote></details>

done
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRDNb-CU_nYTNwjTKV:-MJU-BEE02Mo5IKwJV2s:b-7rl0kd) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We clobber RFLAGS, so need to add `%cc` to the clobbered list.
</blockquote></details>

done
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJUBNf1971TBgwbJXhK:b-tko0ko) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sure, will add this check
</blockquote></details>

Instead of an assert, actually added a subtest to ensure we set/get affinity properly for the parent, in this case, main thread.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRDVxbBana2Chq8lTT:-MJU-EEZBqfwX8fJ0Z9k:b-t16vrj) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically should be `return NULL;`
</blockquote></details>

yes, correct. Fixed it.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRDdEeDisQprhhgnP2:-MJU0Am-AaH-GssQfwfl:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `\n` at the end, `err()` adds it automatically. Here and everywhere else.
</blockquote></details>

done
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 52 at r3](https://reviewable.i [...]

2020-10-13 00:34 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 19 of 24 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN4NTB75qRjgYwPY7Z:-MJUM9fpAfAfTLlV9UER:b-6sfw7a) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@yamahata, regarding "tcs should br passed to ocall. not host tid." now that the code is changed, I think your comment is outdated. If you think it is still valid, can you give more details? 

@dimakuv, thanks but as @yamahata suggested I will add a spin loop and wait till tid != 0 in the parent ( _DkThreadCreate)
</blockquote></details>

"tcs" is still valid.
the parameter tid of ocall_sched_s/getaffinity should be tcs. not host tid.

Please refer the execution flow, DkThreadResume(pal_handle) -> _DkThreadResume(pal_handle) -> ocall_resume_thread(tcs) -> sgx_ocall_resume_thread(tcs) -> intterrupt_thread(tcs)
and thread_map @ sgx_thread.c

For race, let's address it as another PR as followup.

---


<!-- Sent from Reviewable.io -->

2020-10-13 00:41 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 19 of 24 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJUNlw9CUd87o7Cs02p:b1635zl) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Instead of an assert, actually added a subtest to ensure we set/get affinity properly for the parent, in this case, main thread.
</blockquote></details>

It's only tests self thread. I'd like to have additional tests for non-self thread additionally.

In main thread set affinity(self) and getaffinity(self)

In this case
in main thread setaffinity(newly created thread), Here getaffinity(self)
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 98 at r2](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIu8K9lAarqqco8DP9_:-MJUODFn6DzvDS84LCk-:b-4ga0eh) ([raw file](https://github.com/oscarlab/graphene/blob/19bdcac4acb44e91606b5a392dcd55a464f60bf0/Pal/src/host/Linux-SGX/db_threading.c#L98)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Discussed with Isaku about this. Since there is no other accesses to  thread->tid in the PAL layer, it looks to be safe from race condition. In the LibOS layer we are anyway protected as the the thread is added only in the callback which happens after tid is updated.
</blockquote></details>

resolved this comment as the discussion continue in other thread.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 850 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIe2OztDKaja9Y7-jBm:-MJUOKJF50Yt_r59QAT8:b-uv9ixe) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/enclave_ocalls.c#L850)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, agree. Will look into this.
</blockquote></details>

Resolving this as the discussion continues in other thread.
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 177 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN5o_H-Uj033WGg2jO:-MJUORSBCGYSjyNAeZjO:b-ho2sqa) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/Pal/src/host/Linux-SGX/ocall_types.h#L177)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is the previous design. Current design doesn't pass tid via ocall.
</blockquote></details>

This should be tcs in despise of your design change.
For details, please refer the discussion above.
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 183 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJUOZ_S8nLhZjlh6cAA:-MJUOZ_S8nLhZjlh6cAB:b-rqxvo7) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/Pal/src/host/Linux-SGX/ocall_types.h#L183)):*
> ```objc
> 
> typedef struct {
>     int ms_tid;
> ```

ditto.


<!-- Sent from Reviewable.io -->

2020-10-13 00:44 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 19 of 24 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJUPQ3h5_i1Aulo6Q7j:bjcbutl) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

It's only tests self thread. I'd like to have additional tests for non-self thread additionally.

In main thread set affinity(self) and getaffinity(self)

In this case
in main thread setaffinity(newly created thread), Here getaffinity(self)
</blockquote></details>

Anyway this is only for test. not eseential. So I made this non-blocking.


<!-- Sent from Reviewable.io -->

2020-10-13 00:45 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 19 of 24 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 261 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJUPZ7l7DkTbvL-_zvT:-MJUPZ7l7DkTbvL-_zvU:bl9y7ia) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/Pal/src/host/Linux-SGX/sgx_enclave.c#L261)):*
> ```
> ms->ms_tid
> ```

This should be tcs.
convert tcs to host tid based on thread_map in sgx_thread.c and use it.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 269 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJUPjum6-UyCsXoE5uW:-MJUPjum6-UyCsXoE5uX:b-8wbelk) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/Pal/src/host/Linux-SGX/sgx_enclave.c#L269)):*
> ```
> ms->ms_tid
> ```

ditto.


<!-- Sent from Reviewable.io -->

2020-10-13 05:31 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 19 of 24 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN4NTB75qRjgYwPY7Z:-MJUnYox2G4pSFLUlpMj:b-8azu6s) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

"tcs" is still valid.
the parameter tid of ocall_sched_s/getaffinity should be tcs. not host tid.

Please refer the execution flow, DkThreadResume(pal_handle) -> _DkThreadResume(pal_handle) -> ocall_resume_thread(tcs) -> sgx_ocall_resume_thread(tcs) -> intterrupt_thread(tcs)
and thread_map @ sgx_thread.c

For race, let's address it as another PR as followup.

</blockquote></details>

ah I see. So you are suggesting to use the tid that is stored as part of the g_enclave_thread_map. But in that case, one option is to modify storage class of `static sgx_arch_tcs_t* g_enclave_tcs;` and `static struct thread_map* g_enclave_thread_map;` variables and remove `static` type as these are defined in `sgx_thread.c` but we call `sched_setaffinity()` and `sched_getaffinity()` syscall which requires tid from `sgx_enclave.c`. This is not the case with `sgx_ocall_resume_thread` which calls interrupt_thread defined in`sgx_thread.c`.

Second option is to write a wrapper for the set/get affinity syscalls in sgx_thread.c and make use of the global variables. These new wrappers will be called from `sgx_enclave.c` instead of the syscall.

Third option is to use the existing approach. Although a little redundant seems more readable to me.

Regarding the race, since we want to address this as part of another PR, shall I remove the spin-loop introduced in `_DkThreadCreate()`?

@yamahata, please let me know your thoughts.

---
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJ4N2wNABmO9AMLu1Bs:-MJUoxz71Gs82ToiKGTb:b-7l63y5) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Anyway this is only for test. not eseential. So I made this non-blocking.
</blockquote></details>

@yamahata, so you are saying since pthread_attr_getaffinity_np() only stores the parameter into the variable but doesn't exercise the getaffinity flow, we need something that exercises this flow for the child thread as we have done for the parent. right?

If so, I have slightly modified the test case and removed pthread_attr_set/getaffinity_np and used pthread_set/get_affinity_np even for the children created by the main thread as shown below. Let me know if this looks ok to you.

```
diff --git a/LibOS/shim/test/regression/pthread_set_get_affinity.c b/LibOS/shim/test/regression/pthread_set_get_affinity.c
index 49a1e914..b8deffdf 100644
--- a/LibOS/shim/test/regression/pthread_set_get_affinity.c
+++ b/LibOS/shim/test/regression/pthread_set_get_affinity.c
@@ -38,10 +38,7 @@ int main(int argc, const char** argv) {
     numprocs = (numprocs >= 2)? numprocs/2 : 1;

     pthread_t threads[numprocs];
-
-    pthread_attr_t attr;
     cpu_set_t cpus, get_cpus;
-    pthread_attr_init(&attr);

     /* Validate parent set/get affinity for child */
     for (long i = 0; i < numprocs; i++) {
@@ -49,23 +46,23 @@ int main(int argc, const char** argv) {
         CPU_ZERO(&get_cpus);
         CPU_SET(i*2, &cpus);

-        ret = pthread_attr_setaffinity_np(&attr, sizeof(cpus), &cpus);
+        ret = pthread_create(&threads[i], NULL, dowork, NULL);
         if (ret != 0) {
-            err(EXIT_FAILURE, "pthread_attr_setaffinity_np failed for child!");
+            err(EXIT_FAILURE, "pthread_create failed!");
         }

-        ret = pthread_attr_getaffinity_np(&attr, sizeof(get_cpus), &get_cpus);
+        ret = pthread_setaffinity_np(threads[i], sizeof(cpus), &cpus);
         if (ret != 0) {
-            err(EXIT_FAILURE, "pthread_attr_getaffinity_np failed for child!");
+            err(EXIT_FAILURE, "pthread_setaffinity_np failed for child!");
         }

-        if (!CPU_EQUAL_S(sizeof(cpus), &cpus, &get_cpus)) {
-            errx(EXIT_FAILURE, "get cpuset is not equal to set cpuset on proc: %ld", i);
+        ret = pthread_getaffinity_np(threads[i], sizeof(get_cpus), &get_cpus);
+        if (ret != 0) {
+            err(EXIT_FAILURE, "pthread_getaffinity_np failed for child!");
         }

-        ret = pthread_create(&threads[i], &attr, dowork, NULL);
-        if (ret != 0) {
-            err(EXIT_FAILURE, "pthread_create failed!");
+        if (!CPU_EQUAL_S(sizeof(cpus), &cpus, &get_cpus)) {
+            errx(EXIT_FAILURE, "get cpuset is not equal to set cpuset on proc: %ld", i);
         }
     }
	
```


<!-- Sent from Reviewable.io -->

2020-10-13 05:58 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 19 of 24 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJN4NTB75qRjgYwPY7Z:-MJVWhHOCBkxI_Y1LeRh:bw9z4og) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ah I see. So you are suggesting to use the tid that is stored as part of the g_enclave_thread_map. But in that case, one option is to modify storage class of `static sgx_arch_tcs_t* g_enclave_tcs;` and `static struct thread_map* g_enclave_thread_map;` variables and remove `static` type as these are defined in `sgx_thread.c` but we call `sched_setaffinity()` and `sched_getaffinity()` syscall which requires tid from `sgx_enclave.c`. This is not the case with `sgx_ocall_resume_thread` which calls interrupt_thread defined in`sgx_thread.c`.

Second option is to write a wrapper for the set/get affinity syscalls in sgx_thread.c and make use of the global variables. These new wrappers will be called from `sgx_enclave.c` instead of the syscall.

Third option is to use the existing approach. Although a little redundant seems more readable to me.

Regarding the race, since we want to address this as part of another PR, shall I remove the spin-loop introduced in `_DkThreadCreate()`?

@yamahata, please let me know your thoughts.

</blockquote></details>

Introduce a function like tcs_to_tid() in sgx_thread.c and use it.
(and delete intrrupt_thread().)  

---


<!-- Sent from Reviewable.io -->

2020-10-13 08:12 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 187 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJVvE3L-7Undr5yBHj8:-MJVvE3MBYm-lT4H24b9:bg3683p) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/LibOS/shim/src/sys/shim_sched.c#L187)):*
> ```C
>     /* When pid !=0, lookup_thread() internally increments the thread count to prevent it from being
>      * freed, so do the same even when pid == 0 after ensuring thread != NULL
>      */
> ```

Good catch! But the comment is unnecessarily long. Modify to a shorter `/* lookup_thread() internal increments thread count; do the same in case of get_cur_thread() */`
___
*[LibOS/shim/src/sys/shim_sched.c, line 191 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJVvYT583uK4kkIuLm1:-MJVvYT583uK4kkIuLm2:bj7jfgl) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/LibOS/shim/src/sys/shim_sched.c#L191)):*
> ```C
>         get_thread(thread);
> 
>     /* Internal graphene threads are not affinitized and shouldn't hit this flow */
> ```

The comment now is weird :) If we shouldn't hit this flow, then we should have an assert instead of an IF. The better comment is:
`/* internal graphene threads are not affinitized; if we hit an internal thread here, this is some bug in user app */`
___
*[LibOS/shim/src/sys/shim_sched.c, line 230 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJVvuPNEBqjAaZ2oKiW:-MJVvuPNEBqjAaZ2oKiX:b-rln9ci) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/LibOS/shim/src/sys/shim_sched.c#L230)):*
> ```C
>     /* When pid !=0, lookup_thread() internally increments the thread count to prevent it from being
>      * freed, so do the same even when pid == 0 after ensuring thread != NULL
>      */
> ```

ditto (shorter comment)
___
*[LibOS/shim/src/sys/shim_sched.c, line 234 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJVvyle4fzEDzh3wMRE:-MJVvyle4fzEDzh3wMRF:b-4n1zoz) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/LibOS/shim/src/sys/shim_sched.c#L234)):*
> ```C
>         get_thread(thread);
> 
>     /* Internal graphene threads are not affinitized and shouldn't hit this flow */
> ```

ditto (better comment)
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRDdEeDisQprhhgnP2:-MJVwK0o3xWycrWF_FZ1:b-8nyi3w) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

done
</blockquote></details>

Not done
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsLkPE7NGSWF8WSw3V:-MJW07J5BQ7kwUhEV-VT:b-4x0dzb) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_threading.c#L57)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

got it, thanks @dimakuv. I have added a spin loop which waits till tid != 0 in the parent ( _DkThreadCreate) to address the race.
</blockquote></details>

See my comments on this synchronization in another discussion.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRNL6WB0DdcW89wxQJ:-MJW-KakBz9vZlVryIrw:bnxjb7z) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/Pal/src/host/Linux-SGX/db_threading.c#L104)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Removed this comment altogether as we now add a spin-loop to address the race.
</blockquote></details>

What's the point of this global `g_thread_create_lock`? Now if we have several threads that each want to spawn corresponding child threads, they are all serialized on this global lock. I believe it's enough to make `new_thread->thread.tcs` (TCS instead of TID because Isaku asks to move to TCS) atomic int and run a while loop. Also, the body of the while loop should have `cpu_pause()` (see example in `host/Linux-SGX/db_pipes.c`).


<!-- Sent from Reviewable.io -->

2020-10-13 15:56 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 14 of 24 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 230 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJVvuPNEBqjAaZ2oKiW:-MJXfDMsCOVSssA4wCd0:b-rnraql) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/LibOS/shim/src/sys/shim_sched.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (shorter comment)
</blockquote></details>

done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 234 at r4](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJVvyle4fzEDzh3wMRE:-MJXfGo2DWBwAM83hxbH:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/2d1b19af658627f30178eb69c4d9341cd0973e90/LibOS/shim/src/sys/shim_sched.c#L234)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (better comment)
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-10-13 16:39 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 14 of 24 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRNL6WB0DdcW89wxQJ:-MJXjW5P7i5YtVZP3uyC:b-1zp4g7) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/Pal/src/host/Linux-SGX/db_threading.c#L104)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I was of the opinion we needed to serialize the parent invocations to clone as well but had quick sync with @dimakuv and it is a bit clear now. I have removed the create lock. I have also added atomic access for TCS and the cpu_pause().
</blockquote></details>

nitpick: now not tid. please drop tid from the comment.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 49 at r5](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJXowdD4yJnCVXImE4e:-MJXowdD4yJnCVXImE4f:by0mdnr) ([raw file](https://github.com/oscarlab/graphene/blob/2ab3b97b16052611e692139d39d33868c39cc011/Pal/src/host/Linux-SGX/db_threading.c#L49)):*
> ```C
>     LISTP_FOR_EACH_ENTRY(tmp, &g_thread_list, list)
>         if (!tmp->tcs) {
>             new_thread = tmp;
> ```

Please assign host tid to thread.tid.
___
*[Pal/src/host/Linux-SGX/enclave_ecalls.c, line 137 at r5](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJXorIS-tXxAfcdWPCh:-MJXorIS-tXxAfcdWPCi:bg2v255) ([raw file](https://github.com/oscarlab/graphene/blob/2ab3b97b16052611e692139d39d33868c39cc011/Pal/src/host/Linux-SGX/enclave_ecalls.c#L137)):*
> ```C
>         }
> 
>         pal_start_thread();
> ```

Please pass host tid.


<!-- Sent from Reviewable.io -->

2020-10-13 16:39 UTC, yamahata reviewed
> Reviewed 2 of 5 files at r4, 10 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)



<!-- Sent from Reviewable.io -->

2020-10-13 17:13 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRNL6WB0DdcW89wxQJ:-MJXwdKq8TvYvvgEHQCG:bl29fn4) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/Pal/src/host/Linux-SGX/db_threading.c#L104)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nitpick: now not tid. please drop tid from the comment.
</blockquote></details>

@yamahata if we add back the tid in `pal_start_thread()`, this comment will be relevant right? 
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 49 at r5](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJXowdD4yJnCVXImE4e:-MJXvUyzEfx1pEbB9ums:bj0hjy9) ([raw file](https://github.com/oscarlab/graphene/blob/2ab3b97b16052611e692139d39d33868c39cc011/Pal/src/host/Linux-SGX/db_threading.c#L49)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Please assign host tid to thread.tid.
</blockquote></details>

@yamahata sure I can bring back the change. But any reason why you suggested to use tcs in the set/get affinity calls if we plan to store tid as part of thread.tid?


<!-- Sent from Reviewable.io -->

2020-10-13 17:46 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 49 at r5](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJXowdD4yJnCVXImE4e:-MJY3-q1EmeVJDCmXID2:b-8z4jnt) ([raw file](https://github.com/oscarlab/graphene/blob/2ab3b97b16052611e692139d39d33868c39cc011/Pal/src/host/Linux-SGX/db_threading.c#L49)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@yamahata sure I can bring back the change. But any reason why you suggested to use tcs in the set/get affinity calls if we plan to store tid as part of thread.tid?
</blockquote></details>

Because you kept tid in ecall. So I thought you’d like to keep host tid.
Personally I’m fine with either way. But please don’t leave your change in half modified.


<!-- Sent from Reviewable.io -->

2020-10-13 17:53 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 49 at r5](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJXowdD4yJnCVXImE4e:-MJY4ghZ2-h9xAdGOXfg:bljvuxw) ([raw file](https://github.com/oscarlab/graphene/blob/2ab3b97b16052611e692139d39d33868c39cc011/Pal/src/host/Linux-SGX/db_threading.c#L49)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Because you kept tid in ecall. So I thought you’d like to keep host tid.
Personally I’m fine with either way. But please don’t leave your change in half modified.
</blockquote></details>

got it. That is my bad, I had missed to clean up those. @yamahata I think the current design of simply using tid from tcs looks fine to me and I will remove the ecall approach.

I will send a fixup shortly.


<!-- Sent from Reviewable.io -->

2020-10-13 18:30 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 18 of 21 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJRNL6WB0DdcW89wxQJ:-MJYDJvY9t2CgnYh51iN:b-u8x1m8) ([raw file](https://github.com/oscarlab/graphene/blob/4481cd3c0a7710212a7fe11e2a14da1c416d73f5/Pal/src/host/Linux-SGX/db_threading.c#L104)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@yamahata if we add back the tid in `pal_start_thread()`, this will be relevant right? 
</blockquote></details>

oops missed this tid comment. Will clean it up in the next iteration


<!-- Sent from Reviewable.io -->

2020-10-14 10:00 UTC, dimakuv requested changes
> Reviewed 6 of 11 files at r5, 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJaYFr881MEYexh4o3C:-MJaYFr98KTQ6pxtsPBP:b-bczuvc) (no related file):*
I definitely like Isaku's suggestion to use `thread->tcs` instead of `thread->tid` in Linux-SGX PAL! The PR looks better with this change.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 185 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJaW9l7-Tqg_JnYxlsT:-MJaW9l803LaksOWKsyn:b7sa1kp) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/LibOS/shim/src/sys/shim_sched.c#L185)):*
> ```C
>         return -ESRCH;
> 
>     /* lookup_thread() internal increments thread count; do the same in case of get_cur_thread() */
> ```

`internally`, my proposed text had a typo :)
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJaWD3UA8FgKjOeov0h:-MJaWD3UA8FgKjOeov0i:b7sa1kp) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/LibOS/shim/src/sys/shim_sched.c#L228)):*
> ```C
>         return -ESRCH;
> 
>     /* lookup_thread() internal increments thread count; do the same in case of get_cur_thread() */
> ```

`internally`, my proposed text had a typo :)
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 100 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJaWru_DjqoSnL56RIw:-MJaWruaCp38bZZr0bwt:b-b6mahf) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/Pal/src/host/Linux-SGX/db_threading.c#L100)):*
> ```C
> 
>     /* There can be subtle race between the parent and child so hold the parent until child updates
>      * its tid, tcs.
> ```

`its tid` is outdated now. Simply `...until child updates its tcs */`


<!-- Sent from Reviewable.io -->

2020-10-14 13:03 UTC, yamahata requested changes
We’re getting for merge. For me, only final code cleanup is remaining.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866#-:-MJbC77K762t3-adNkML:b88yq8a)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 61 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJb9B3NDQubsVky-Tt3:-MJb9B3NDQubsVky-Tt4:boyrn07) ([raw file](https://github.com/oscarlab/graphene/blob/3bcab01a0c0665d190b991b8823bdbbb6ed887ef/Pal/src/host/Linux-SGX/db_threading.c#L61)):*
> ```C
>         if (!tmp->tcs) {
>             new_thread = tmp;
>             new_thread->tid = pal_assign_tid();
> ```

can you please keep thread.tid set to pal_assign_tid for debug?
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 254 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJbBN7HAvSqJ6Cvycsa:-MJbBN7HAvSqJ6Cvycsb:b5mp7sb) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/Pal/src/host/Linux-SGX/sgx_enclave.c#L254)):*
> ```C
> static long sgx_ocall_resume_thread(void* pms) {
>     ODEBUG(OCALL_RESUME_THREAD, pms);
>     return interrupt_thread(pms);
> ```

can you please open code it ande delete interrupt_thread?
simple code clean up.
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 299 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJb8D1FDFvypaGcqPzz:-MJb8D1FDFvypaGcqQ--:bvbo9h6) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/Pal/src/host/Linux-SGX/sgx_thread.c#L299)):*
> ```C
> }
> 
> int interrupt_thread(void* tcs) {
> ```

As ocall_resume_thread is the only caller, can you open code there and delete this function?


<!-- Sent from Reviewable.io -->

2020-10-14 13:03 UTC, yamahata reviewed
> Reviewed 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2020-10-14 16:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 185 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJaW9l7-Tqg_JnYxlsT:-MJbuyvB5Jh8Bn9KiQ3X:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/LibOS/shim/src/sys/shim_sched.c#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`internally`, my proposed text had a typo :)
</blockquote></details>

done
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJaWD3UA8FgKjOeov0h:-MJbuzkE6JPrOuqgNGJp:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`internally`, my proposed text had a typo :)
</blockquote></details>

done
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 61 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJb9B3NDQubsVky-Tt3:-MJbp-Fk3WOLltILXLVR:bsgq2la) ([raw file](https://github.com/oscarlab/graphene/blob/3bcab01a0c0665d190b991b8823bdbbb6ed887ef/Pal/src/host/Linux-SGX/db_threading.c#L61)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

can you please keep thread.tid set to pal_assign_tid for debug?
</blockquote></details>

yes reverted the change
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 100 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJaWru_DjqoSnL56RIw:-MJbpO_h2_ptSb1jw5Mp:bqo6elr) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/Pal/src/host/Linux-SGX/db_threading.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`its tid` is outdated now. Simply `...until child updates its tcs */`
</blockquote></details>

fixed the comment.
___
*[Pal/src/host/Linux-SGX/enclave_ecalls.c, line 137 at r5](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJXorIS-tXxAfcdWPCh:-MJbp3f50SGjGwZ9_fC0:b-uj9qfe) ([raw file](https://github.com/oscarlab/graphene/blob/2ab3b97b16052611e692139d39d33868c39cc011/Pal/src/host/Linux-SGX/enclave_ecalls.c#L137)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Please pass host tid.
</blockquote></details>

We now don't pass the host tid, but get it from tcs.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 254 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJbBN7HAvSqJ6Cvycsa:-MJblwQU3p8AdWG3U-gT:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/Pal/src/host/Linux-SGX/sgx_enclave.c#L254)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

can you please open code it ande delete interrupt_thread?
simple code clean up.
</blockquote></details>

done
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 299 at r6](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJb8D1FDFvypaGcqPzz:-MJblaf81ev7gIHnBRUN:b491ams) ([raw file](https://github.com/oscarlab/graphene/blob/e521d1bdc749fe93876cde2efe4be52e91f3209b/Pal/src/host/Linux-SGX/sgx_thread.c#L299)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

As ocall_resume_thread is the only caller, can you open code there and delete this function?
</blockquote></details>

sure, removed this wrapper and added functionality in `sgx_ocall_resume_thread()`


<!-- Sent from Reviewable.io -->

2020-10-14 16:53 UTC, yamahata submitted a review, later dismissed
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-10-15 08:04 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfHCu389iqkbGhi3lo:-MJfHCu389iqkbGhi3lp:bxvlh50) (no related file):*
I would like to test this PR on my machines. Apart from running the added regression tests manually, what can I use and how to see that PR works? Should I use our OpenVINO example?

---
___
*[Pal/src/host/Linux/db_threading.c, line 287 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfGwmf7-KIfv3prVtc:-MJfGwmgDMaRvj34OT4D:b-ws7pqe) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux/db_threading.c#L287)):*
> ```C
>                              thread->thread.tid,
>                              cpumask_size,
>                              cpu_mask);
> ```

Cosmetic change: please wrap all these arguments to 100 chars (i.e., put as many args as possible on one line until you reach a limit of 100 chars)
___
*[Pal/src/host/Linux/db_threading.c, line 296 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfH4tn0vTU2h-385rQ:-MJfH4tn0vTU2h-385rR:bpc2qks) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux/db_threading.c#L296)):*
> ```C
>                              thread->thread.tid,
>                              cpumask_size,
>                              cpu_mask);
> ```

Same cosmetic change
___
*[Pal/src/host/Linux-SGX/db_main.c, line 440 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsFYVf8V8AFNNfTPi_:-MJfEd5TDBP5t7qC6m9L:b-gkel9n) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_main.c#L440)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Since we are now using tcs to get tid, we no longer need this change. My unit tests work even without this change. So before PR, I will remove this line if everyone is fine with it.
</blockquote></details>

But we still use `thread.tid` for debugging purposes. This line is not strictly needed, but when debugging, the main thread will contain arbitrary value. Let's keep this line but assign to `0` (it's main thread after all, let's give it a known value), like this:
```
    first_thread->thread.tid = 0; /* child threads are assigned TIDs 1,2,...; see pal_start_thread() */
```
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfFqdn7OQ4C-SjDSXj:-MJfFqdn7OQ4C-SjDSXk:b-rz3csc) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
> ```C
>  */
> static PAL_IDX pal_assign_tid(void) {
>     static struct atomic_int tid = ATOMIC_INIT(0);
> ```

Replace with:
```
    static struct atomic_int tid = ATOMIC_INIT(1); /* tid 0 is assigned to the first thread; see pal_linux_main() */
```


<!-- Sent from Reviewable.io -->

2020-10-15 15:17 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 15 of 21 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfHCu389iqkbGhi3lo:-MJglFfq0ETMFUhIGkNr:b-3hybey) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would like to test this PR on my machines. Apart from running the added regression tests manually, what can I use and how to see that PR works? Should I use our OpenVINO example?
</blockquote></details>

Actually, I found the issue while profiling openvino benchmark. I had noticed the number of set/get affinity syscalls were way too less compared to native runs. But there isn't an explicit failure we can check for with openvino. 

So yes for validation, the affinity regression tests introduced as part of the PR would be the ones to check.

---
___
*[Pal/src/host/Linux/db_threading.c, line 287 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfGwmf7-KIfv3prVtc:-MJgkPvo0teQisBw8laG:bilktuu) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux/db_threading.c#L287)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Cosmetic change: please wrap all these arguments to 100 chars (i.e., put as many args as possible on one line until you reach a limit of 100 chars)
</blockquote></details>

yes addressed this in other files too like shim_shim_sched.c, enclave_ocalls.c and sgx_enclave.c. Please flag if you notice any more.
___
*[Pal/src/host/Linux/db_threading.c, line 296 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfH4tn0vTU2h-385rQ:-MJgl3jl3vdz9nX-oSDf:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux/db_threading.c#L296)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Same cosmetic change
</blockquote></details>

done
___
*[Pal/src/host/Linux-SGX/db_main.c, line 440 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsFYVf8V8AFNNfTPi_:-MJgl5A11sTI9V28VJx5:b7trktc) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_main.c#L440)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But we still use `thread.tid` for debugging purposes. This line is not strictly needed, but when debugging, the main thread will contain arbitrary value. Let's keep this line but assign to `0` (it's main thread after all, let's give it a known value), like this:
```
    first_thread->thread.tid = 0; /* child threads are assigned TIDs 1,2,...; see pal_start_thread() */
```
</blockquote></details>

sure, added this statement back with tid initialized to 0.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfFqdn7OQ4C-SjDSXj:-MJglBpI3o4mJApCwln8:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Replace with:
```
    static struct atomic_int tid = ATOMIC_INIT(1); /* tid 0 is assigned to the first thread; see pal_linux_main() */
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-10-15 15:58 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-15 16:12 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfFqdn7OQ4C-SjDSXj:-MJh0QkC7XXF96wpgqbe:b69nngy) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

done
</blockquote></details>

Because add-fetch is used, the first return value is (initial value + 1).
@dimakuv ,is this really your intention?
If the main thread is assigned to tid 1, I think ATOMIC_INIT(1) makes sense.


<!-- Sent from Reviewable.io -->

2020-10-15 20:21 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfFqdn7OQ4C-SjDSXj:-MJhutCB8tr2uCGd1L6M:b-mfa7ew) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Because add-fetch is used, the first return value is (initial value + 1).
@dimakuv ,is this really your intention?
If the main thread is assigned to tid 1, I think ATOMIC_INIT(1) makes sense.
</blockquote></details>

Oops, thanks Isaku, didn't pay attention to this.

@vijaydhanraj Could you change it back (`ATOMIC_INIT(1)` -> `ATOMIC_INIT(0)`), so that we actually have child threads starting with 1, 2, ...?


<!-- Sent from Reviewable.io -->

2020-10-15 21:38 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfFqdn7OQ4C-SjDSXj:-MJiAoyUC6PpeLXvj8hE:b-mfvc4a) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, thanks Isaku, didn't pay attention to this.

@vijaydhanraj Could you change it back (`ATOMIC_INIT(1)` -> `ATOMIC_INIT(0)`), so that we actually have child threads starting with 1, 2, ...?
</blockquote></details>

@yamahata and @dimakuv, based on my earlier debug I observed that tid of the first thread usually is 1. Given this, can we keep ATOMIC_INIT(1) as is and set first_thread->thread.tid=1?


<!-- Sent from Reviewable.io -->

2020-10-15 22:51 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfFqdn7OQ4C-SjDSXj:-MJiSXwc2rs1noqi8iFD:b-pppj4f) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@yamahata and @dimakuv, based on my earlier debug I observed that tid of the first thread usually is 1. Given this, can we keep ATOMIC_INIT(1) as is and set first_thread->thread.tid=1?
</blockquote></details>

I’m fine woth that.


<!-- Sent from Reviewable.io -->

2020-10-16 01:19 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 6 files at r9, 12 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-16 06:50 UTC, dimakuv approved these changes
> Reviewed 10 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 50 at r8](https://reviewable.io/reviews/oscarlab/graphene/1866#-MJfFqdn7OQ4C-SjDSXj:-MJk9xJE1Dr9jZ37-9w7:bd6e8es) ([raw file](https://github.com/oscarlab/graphene/blob/b40da4e14ce7344aeced2af8b5a4541d7a8b75da/Pal/src/host/Linux-SGX/db_threading.c#L50)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

I’m fine woth that.
</blockquote></details>

@vijaydhanraj The way you fixed it (as Isaku suggested) is fine by me.


<!-- Sent from Reviewable.io -->

2020-10-21 00:27 UTC, mkow requested changes
> Reviewed 1 of 21 files at r1, 2 of 5 files at r4, 4 of 11 files at r5, 3 of 6 files at r6, 1 of 5 files at r7, 2 of 6 files at r9, 12 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 32 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK4z1pz3GzmD0IRzcjv:-MK4z1q-DGAyVQTzBQe2:b-msjpth) (no related file):*
The one-liner from the first commit got wrapped, please fix this on the next rebase (i.e. after we resolve all code-related discussions).

> [Pal/Linux-SGX] Fix caching for leaf 0xB and 0x1F to properly
> enumerate CPU topology info.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK514vZD-AXDwGymR3l:-MK514vZD-AXDwGymR3m:b-c99o51) (no related file):*
Please check if there are any new LTP tests which started to work with this PR.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 144 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK5HG4j6v0xHmkypQRb:-MK5HG4kDZH1Kg_XSXwO:b-q4biag) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L144)):*
> ```C
> 
> static int check_affinity_params(bool is_getaffinity, int ncpus, size_t cpumask_size,
>                                  __kernel_cpu_set_t* user_mask_ptr) {
> ```

I think the logic between get- and set- affinity differs enough to split this into two functions or inline in the `shim_do_` functions. The only common part is that aligning up the size, which can be done with a single `ALIGN_UP` call.
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK54FpFApt5e_wwN87i:-MK54FpFApt5e_wwN87j:b-yul9xy) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L146)):*
> ```C
>                                  __kernel_cpu_set_t* user_mask_ptr) {
>     /* Check that user_mask_ptr is valid; if not, should return -EFAULT */
>     if (test_user_memory(user_mask_ptr, cpumask_size, true))
> ```

sched_setaffinity does not write to the user pointer
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK54L_E7W5sF6yHm5OC:-MK54L_E7W5sF6yHm5OD:b-vu5k7a) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L146)):*
> ```C
>                                  __kernel_cpu_set_t* user_mask_ptr) {
>     /* Check that user_mask_ptr is valid; if not, should return -EFAULT */
>     if (test_user_memory(user_mask_ptr, cpumask_size, true))
> ```

`true` -> `/*write=*/true`
___
*[LibOS/shim/src/sys/shim_sched.c, line 151 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK5ClKF1urPKzC2HKbt:-MK5ClKG9G0w5buDzVdS:b3ztlcg) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L151)):*
> ```C
>     /* Linux kernel bitmap is based on long. So according to its
>      * implementation, round up the result to sizeof(long) */
>     size_t bitmask_long_count    = (ncpus + sizeof(long) * 8 - 1) / (sizeof(long) * 8);
> ```

Please use `ALIGN_UP` macro (I know it was here before, but let's fix it while we're here)
___
*[LibOS/shim/src/sys/shim_sched.c, line 154 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7Cjnr6i3l4NKLIART:-MK7CjnuEbQLbq-FHEeK:b-6btijx) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L154)):*
> ```C
>     size_t bitmask_size_in_bytes = bitmask_long_count * sizeof(long);
> 
>     if (is_getaffinity && (cpumask_size < bitmask_size_in_bytes)) {
> ```

no need for parentheses
___
*[LibOS/shim/src/sys/shim_sched.c, line 161 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK5HjEY10k4qMGoh9Dn:-MK5HjEY10k4qMGoh9Do:by8y8x3) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L161)):*
> ```C
> 
>     /* Linux kernel also rejects non-natural size */
>     if (cpumask_size & (sizeof(long) - 1))
> ```

I think sched_setaffinity doesn't have this check?
___
*[LibOS/shim/src/sys/shim_sched.c, line 167 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK52Gyw26yn_Nc153mM:-MK52Gyw26yn_Nc153mN:bt3jbti) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L167)):*
> ```C
> }
> 
> int shim_do_sched_setaffinity(pid_t pid, size_t cpumask_size, __kernel_cpu_set_t* user_mask_ptr) {
> ```

Please make it match the types used by the kernel:
`long shim_do_sched_setaffinity(pid_t pid, unsigned int len, unsigned long* user_mask_ptr)`
___
*[LibOS/shim/src/sys/shim_sched.c, line 170 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK55iDeEo7JGg2pcPAy:-MK55iDeEo7JGg2pcPAz:b-k51i1c) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L170)):*
> ```C
>     int ret;
>     struct shim_thread* thread;
>     int ncpus = PAL_CB(cpu_info.cpu_num);
> ```

should be `size_t`
also, I prefer `cpu_cnt` name
___
*[LibOS/shim/src/sys/shim_sched.c, line 200 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IZg01uB30u_bQ2bn:-MK7IZg01uB30u_bQ2bo:b-a4g74p) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L200)):*
> ```C
>     }
> 
>     ret = DkThreadSetCpuAffinity(thread->pal_handle, bitmask_size_in_bytes, user_mask_ptr);
> ```

`DkThreadSetCpuAffinity` returns `PAL_NUM` which is `unsigned`, so the condition below may not work.
___
*[LibOS/shim/src/sys/shim_sched.c, line 210 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK52gJq6nyHqRmtusYw:-MK52gJq6nyHqRmtusYx:b-3xxj96) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L210)):*
> ```C
> }
> 
> int shim_do_sched_getaffinity(pid_t pid, size_t cpumask_size, __kernel_cpu_set_t* user_mask_ptr) {
> ```

ditto: `long shim_do_sched_getaffinity(pid_t pid, unsigned int len, unsigned long* user_mask_ptr)`
___
*[LibOS/shim/src/sys/shim_sched.c, line 244 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IfM77mVgDR7_MyMe:-MK7IfM77mVgDR7_MyMf:b-rj4epn) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L244)):*
> ```C
> 
>     memset(user_mask_ptr, 0, cpumask_size);
>     ret = DkThreadGetCpuAffinity(thread->pal_handle, bitmask_size_in_bytes, user_mask_ptr);
> ```

ditto (unsigned ret val)
___
*[LibOS/shim/test/regression/Makefile, line 67 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7R6haBZWTnQTshS0l:-MK7R6haBZWTnQTshS0m:byb1os4) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/Makefile#L67)):*
> ```Makefile
> 	readdir \
> 	sched \
> 	sched_set_get_cpuaffinity \
> ```

Any reason why the first one is named `[..]set_get_affinity` and the second `[..]set_get_cpuaffinity`?
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 24 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7U-pXD150L6WLKX-L:-MK7U-pXD150L6WLKX-M:byvrndv) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L24)):*
> ```C
>                       "dec %%rax\n"
>                       "cmp $0, %%rax\n"
>                       "jne loop\n"
> ```

you can simplify this with `loop` instruction
___
*[LibOS/shim/test/regression/pthread_set_get_affin [...]

2020-10-21 00:29 UTC, mkow commented
Jenkins, test this please

2020-10-21 01:06 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 31 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 440 at r1](https://reviewable.io/reviews/oscarlab/graphene/1866#-MIsFYVf8V8AFNNfTPi_:-MK7g2hf53AQ0gBxtVCq:bmnjadu) ([raw file](https://github.com/oscarlab/graphene/blob/c78b8bf761379916796dcec20ff7fc6355ba1e86/Pal/src/host/Linux-SGX/db_main.c#L440)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

/summon @boryspoplawski 
Please take a look at this change, looks relevant to your current work.
</blockquote></details>

I did not touch Pal threads (at least yet ;) )
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 48 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7Llu0CaEYJ_9n_2bT:-MK7g9Uu3eX5YGDXlq2y:biisw57) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/Pal/src/host/Linux-SGX/db_threading.c#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski same here
</blockquote></details>

ditto (this is Pal too)


<!-- Sent from Reviewable.io -->

2020-10-21 09:12 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 32 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK9Q5sQ9ftw0pY4cZ1n:-MK9Q5sR6a7wx_y1UL9N:b-3vbml7) (no related file):*
Your new test (`test_libos.TC_30_Syscall.test_102_pthread_set_get_affinity`) failed on Jenkins by exceeding the time limit. How long does it run? Please keep in mind, that our tests should be as fast as possible, CI already takes a lot of time to run.

---


<!-- Sent from Reviewable.io -->

2020-10-21 12:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 32 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/db_threading.c, line 87 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7Iz5T0dG_wf_7rCCl:-MKA5H_k2iHCAzVH89FJ:bcg4v1r) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/Pal/src/db_threading.c#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

return type is unsigned, but `ret` may be negative here
</blockquote></details>

Oops, good point. I suggest to change `DkThreadSetCpuAffinity()` and `DkThreadSetCpuAffinity()` to return `PAL_BOL` (see for example `DkThreadResume()` above).


<!-- Sent from Reviewable.io -->

2020-10-22 07:00 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 32 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK514vZD-AXDwGymR3l:-MKAyXS50SknpFbUc-sN:bk0gohb) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please check if there are any new LTP tests which started to work with this PR.
</blockquote></details>

thanks to @mkow for helping me check the LTP tests. Based on our findings, sched_setaffinity01 still fails due to dependency on `seteuid`. So keep this test as skipped.  sched_getaffinity01 seems to be already enabled.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK9Q5sQ9ftw0pY4cZ1n:-MKA_A2n4ta5H-js5IQH:bsbx54c) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Your new test (`test_libos.TC_30_Syscall.test_102_pthread_set_get_affinity`) failed on Jenkins by exceeding the time limit. How long does it run? Please keep in mind, that our tests should be as fast as possible, CI already takes a lot of time to run.
</blockquote></details>

on NUC, this test takes ~15-20s. The idea is to make it a little longer so that users can manually verify it. I did test regression runs but didn't observe the timeout error.  What is the default timeout limit on Jenkins? Will adding a timeout parameter like timeout=25 help?

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 144 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK5HG4j6v0xHmkypQRb:-MKBzUhQ0uVWyMVTPQty:b-4i3y9a) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L144)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the logic between get- and set- affinity differs enough to split this into two functions or inline in the `shim_do_` functions. The only common part is that aligning up the size, which can be done with a single `ALIGN_UP` call.
</blockquote></details>


Did a quick check in the linux kernel code and don't see `(cpumask_size & (sizeof(long) - 1))` check either for `sched_setaffinity()`. So agree, we can get rid of `check_affinity_params()`. I have added the sanity checks inside `shim_do` calls.
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK54FpFApt5e_wwN87i:-MKC01T70ai7SGaRXD2U:b-usba78) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

sched_setaffinity does not write to the user pointer
</blockquote></details>

set `write` parameter to false for  test_user_memory when called from `sched_setaffinity()`
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK54L_E7W5sF6yHm5OC:-MKC0xVJ3PY1YXDwxX0N:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`true` -> `/*write=*/true`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 151 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK5ClKF1urPKzC2HKbt:-MKC5xEc4dx1Fho2oP6n:b-6lcsvj) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L151)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use `ALIGN_UP` macro (I know it was here before, but let's fix it while we're here)
</blockquote></details>

since we basically want to convert bits to long, how about adding the following #define to api.h? Extracted these from linux kernel code. With ALIGN_UP we still need to divide by sizeof(long) * 8.
```
#define DIV_ROUND_UP(n,d)              (((n) + (d) - 1) / (d))

#define BITS_IN_BYTE                   (8)
#define BITS_IN_TYPE(type)             (sizeof(type) * BITS_IN_BYTE)
#define BITS_TO_LONGS(nr)              DIV_ROUND_UP(nr, BITS_PER_TYPE(long))
```
___
*[LibOS/shim/src/sys/shim_sched.c, line 154 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7Cjnr6i3l4NKLIART:-MKCIEGb41_ke7jhOvPx:b-k4pzmb) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L154)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need for parentheses
</blockquote></details>

Not applicable after the new code change.
___
*[LibOS/shim/src/sys/shim_sched.c, line 161 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK5HjEY10k4qMGoh9Dn:-MKCIT1d6q12vTj9wPq7:b-ymwieo) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think sched_setaffinity doesn't have this check?
</blockquote></details>

I did confirm with linux kernel and you are right. I have removed this check for `sched_setaffinity` 
___
*[LibOS/shim/src/sys/shim_sched.c, line 167 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK52Gyw26yn_Nc153mM:-MKCKN8f3U6RwPgEaXIP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L167)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please make it match the types used by the kernel:
`long shim_do_sched_setaffinity(pid_t pid, unsigned int len, unsigned long* user_mask_ptr)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 170 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK55iDeEo7JGg2pcPAy:-MKCKOFO492djIDIo89j:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L170)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be `size_t`
also, I prefer `cpu_cnt` name
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 200 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IZg01uB30u_bQ2bn:-MKCTixH1WaDTLgbDr9C:bjtqemc) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`DkThreadSetCpuAffinity` returns `PAL_NUM` which is `unsigned`, so the condition below may not work.
</blockquote></details>

good catch! Modified the return type to int.
___
*[LibOS/shim/src/sys/shim_sched.c, line 210 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK52gJq6nyHqRmtusYw:-MKD6c-68EwlOS3WqfPb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L210)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto: `long shim_do_sched_getaffinity(pid_t pid, unsigned int len, unsigned long* user_mask_ptr)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 244 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IfM77mVgDR7_MyMe:-MKD6dml6EjkgHNUABW2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L244)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

dit [...]

2020-10-22 09:15 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 42 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK9Q5sQ9ftw0pY4cZ1n:-MKETr-K-KIaAzpri3zo:b9k3nlp) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

on NUC, this test takes ~15-20s. The idea is to make it a little longer so that users can manually verify it. I did test regression runs but didn't observe the timeout error.  What is the default timeout limit on Jenkins? Will adding a timeout parameter like timeout=25 help?
</blockquote></details>

The default timeout is 20 seconds AFAIK. But this is in general not very good for CI, I agree with Michal.

What if we add an integer parameter to `do_work()` like this:
```
static void* dowork(void* args) {
    __asm__ volatile (
                      "movq %0, %%rax\n"
                      "loop:\n"
                      ... "m"((uint64_t)args) ...

int main() {
...
  /* if no command-line options, let this test run a lot of time, otherwise only for a short time */
  uint64_t iterations = argc > 1 ? 10000 : 10000000000;
  ret = pthread_create(&threads[i], NULL, dowork, (void*)iterations);
}
```

And then in our `test_libos.py`:
```
    def test_102_pthread_set_get_affinity(self):
        stdout, _ = self.run_binary(['pthread_set_get_affinity', 'dummy-arg'])
```

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 200 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IZg01uB30u_bQ2bn:-MKEYlFz8GHagbvAUI_t:balri5z) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

good catch! Modified the return type to int.
</blockquote></details>

Ok, just noticed this wrong usage of error codes of PAL in these new functions. See my other comments, but the general idea is like this:
1. You should *never* use the return value of `Dk...` functions as error codes. At most you use the return values to figure out "success" vs "fail".
2. You should *never* use `convert_pal_errno()` directly. Instead you must use `PAL_ERRNO()` macro. The logic is a bit quirky, but it's the same idea as with `errno` in libc.

In this particular case, you should convert `DkThread{Set,Get}CpuAffinity()` to return `PAL_BOOL` and use smth like:
```
    PAL_BOL ret = DkThreadSetCpuAffinity(thread->pal_handle, bitmask_size_in_bytes, user_mask_ptr);
    if (!ret) {
        put_thread(thread);
        return -PAL_ERRNO();
    }
```
___
*[LibOS/shim/src/sys/shim_sched.c, line 244 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IfM77mVgDR7_MyMe:-MKEZwJE6rlQ7xCwQZll:b-m3uy9v) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L244)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (`PAL_BOL` and `PAL_ERRNO()`)
___
*[LibOS/shim/src/sys/shim_sched.c, line 204 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKEX-La16p-zZdSJiqm:-MKEX-La16p-zZdSJiqn:bufg36y) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L204)):*
> ```C
>         return -EINVAL;
>     }
>     /* Linux kernel also rejects non-natural size */
> ```

Please add an empty line before this comment (for visual separation)
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 24 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7U-pXD150L6WLKX-L:-MKETyB9-gJgSsjgsIfR:b-udyd1v) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L24)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Is there any reason apart from a reduction in 2 lines of assembly code to use `loop` instruction? SDM states that `loop` internally does dec and compare and not sure if it optimized in any way. Given this, I prefer to use the existing one unless you want me to use loop instruction.
</blockquote></details>

+1 to Vijay, who cares
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7UJnU46ddrcR-TNPG:-MKA4pKu4EVBk3N27RY0:b-273y8a) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L40)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

sure, done.
</blockquote></details>

Nitpick: `pthread_t *threads` -> `pthread_t* threads` (asterisk alignment)
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 82 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKEULMc02KLXvKnrSyF:-MKEULMc02KLXvKnrSyG:bonowdc) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/test/regression/pthread_set_get_affinity.c#L82)):*
> ```C
>         }
>     }
>     /* Validating parent set/get affinity for child done. Free resources*/
> ```

Nitpick: `... Free resources*/` ->`... Free resources */`
___
*[LibOS/shim/test/regression/test_libos.py, line 519 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKEXVO8Agms5OjIUXvJ:-MKEXVO8Agms5OjIUXvK:b-ax7s4s) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/test/regression/test_libos.py#L519)):*
> ```Python
> 
>     def test_102_pthread_set_get_affinity(self):
>         stdout, _ = self.run_binary(['pthread_set_get_affinity'], timeout=25)
> ```

Please see my other comment. I recommend to remove this explicit timeout.
___
*[Pal/include/lib/api.h, line 69 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKEXd-2C3BFBPIXbB5V:-MKEXd-2C3BFBPIXbB5W:b4a9mod) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/Pal/include/lib/api.h#L69)):*
> ```objc
> #define DIV_ROUND_UP(n,d)              (((n) + (d) - 1) / (d))
> 
> #define BITS_IN_BYTE                   (8)
> ```

No need for parenthesis here.
___
*[Pal/include/pal/pal.h, line 516 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKEXjhYA7m3BTwYtQVD:-MKEXjhYA7m3BTwYtQVE:bc8loy3) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/Pal/include/pal/pal.h#L516)):*
> ```objc
> 
> /*!
>  * \brief set the CPU affinity of a thread.
> ```

Start with a capital letter: `set` -> `Set`
___
*[Pal/include/pal/pal.h, line 519 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKEXrh7DnreSTDZDG2x:-MKEXrh7DnreSTDZDG2y:bliwcj1) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/Pal/include/pal/pal.h#L519)):*
> ```objc
>  *
>  * \param cpumask_size length in bytes of the bitmask pointed to by user_mask_ptr
>  * \param cpu_mask user-space pointer to the new CPU mask
> ```

Where is `\param thread`? Please add the first argument.
___
*[Pal/include/pal/pal.h, line 521 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKE_5sY-bYrDpCc_I4E:-MKE_5sZBFnXpH3tqcZx:b-4uexwm) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/Pal/include/pal/pal.h#L521)):*
> ```objc
>  * \param cpu_mask user-space pointer to the new CPU mask
>  *
>  * \return Returns the 0 on success, a errno on failure.
> ```

Must be `PAL_BOL`
___
*[Pal/include/pal [...]

2020-10-22 12:56 UTC, mkow requested changes
> Reviewed 1 of 12 files at r10, 12 of 12 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK9Q5sQ9ftw0pY4cZ1n:-MKEx-nn7FO7AIYWSeVP:bcd7vn9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The default timeout is 20 seconds AFAIK. But this is in general not very good for CI, I agree with Michal.

What if we add an integer parameter to `do_work()` like this:
```
static void* dowork(void* args) {
    __asm__ volatile (
                      "movq %0, %%rax\n"
                      "loop:\n"
                      ... "m"((uint64_t)args) ...

int main() {
...
  /* if no command-line options, let this test run a lot of time, otherwise only for a short time */
  uint64_t iterations = argc > 1 ? 10000 : 10000000000;
  ret = pthread_create(&threads[i], NULL, dowork, (void*)iterations);
}
```

And then in our `test_libos.py`:
```
    def test_102_pthread_set_get_affinity(self):
        stdout, _ = self.run_binary(['pthread_set_get_affinity', 'dummy-arg'])
```
</blockquote></details>

Maybe better: instead of a dummy arg, let's just pass the iteration count there. This way CI and the user could customize the delay (and it's just one call to `atoi` and one less conditional).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKFAtPh3mKzNhO9mHrG:-MKFAtPh3mKzNhO9mHrH:bn3900q) (no related file):*
Now `__kernel_cpu_set_t` in shim_types.h is unused, same as all the macros it used.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 151 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK5ClKF1urPKzC2HKbt:-MKF2Yi7-BoZ0bVaDWXp:brxp9sq) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L151)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

since we basically want to convert bits to long, how about adding the following #define to api.h? Extracted these from linux kernel code. With ALIGN_UP we still need to divide by sizeof(long) * 8.
```
#define DIV_ROUND_UP(n,d)              (((n) + (d) - 1) / (d))

#define BITS_IN_BYTE                   (8)
#define BITS_IN_TYPE(type)             (sizeof(type) * BITS_IN_BYTE)
#define BITS_TO_LONGS(nr)              DIV_ROUND_UP(nr, BITS_PER_TYPE(long))
```
</blockquote></details>

Sounds good.
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF24-SBSU28z87RaPp:-MKF24-TBs_rp2s3i5d6:bncljsh) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L146)):*
> ```C
>     int ret;
>     struct shim_thread* thread;
>     size_t cpu_cnt  = PAL_CB(cpu_info.cpu_num);
> ```

please remove the double space
___
*[LibOS/shim/src/sys/shim_sched.c, line 190 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF3M_D0MgRJP5t04qr:-MKF3M_D0MgRJP5t04qs:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L190)):*
> ```C
>     int ret;
>     struct shim_thread* thread;
>     size_t cpu_cnt  = PAL_CB(cpu_info.cpu_num);
> ```

ditto
___
*[LibOS/shim/src/sys/shim_sched.c, line 192 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF3cuj5qXedMx-Xnmc:-MKF3cuj5qXedMx-Xnmd:b-xq2z3n) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L192)):*
> ```
> if not, should return -EFAULT */
> ```
No need for stating 1-1 what the code does right below (it was here before, but let's fix it while we're rewriting these functions). Ditto for setaffinity.
___
*[LibOS/shim/src/sys/shim_sched.c, line 197 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF3zuA9DRWt8wtkzFs:-MKF3zuA9DRWt8wtkzFt:b-5kg4ov) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L197)):*
> ```C
> 
>     /* Linux kernel bitmap is based on long. So according to its
>      * implementation, round up the result to sizeof(long) */
> ```

please rewrap to 100-chars limit (ditto for all comments in both functions)
___
*[LibOS/shim/src/sys/shim_sched.c, line 200 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF48CmDlZJNM5j38d6:-MKF48CmDlZJNM5j38d7:b-5ky8e4) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L200)):*
> ```
> must be %lu
> ```

This isn't true, should be: "must be at least".
___
*[LibOS/shim/test/regression/Makefile, line 67 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7R6haBZWTnQTshS0l:-MKF4MtW3Jx_tQBIx3Fc:b-78ha5h) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/Makefile#L67)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No reason, it is merging the work of two authors :). I have changed sched_set_get_cpuaffinity to sched_set_get_affinity 
</blockquote></details>

I see :) Thanks for fixing.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 24 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7U-pXD150L6WLKX-L:-MKF4TvE3vxIq9blPFPZ:bzh42c7) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Vijay, who cares
</blockquote></details>

This was only to shorten and simplify the code, I prefer less assembly than more assembly :)

To be honest I don't understand this argument with optimization, the sole purpose of this loop is to be slow ;) Anyways, I won't block on this.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7SDOjEEAqRGkdU13R:-MKF4xBA3YxlzpH2eHTk:b3g5j2v) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

gcc online docs state that "On some machines, GCC represents the condition codes as a specific hardware register; "cc" serves to name this register."
Since gcc thinks this as a hardware register, maybe % works fine. But I have removed the % sign from cc

</blockquote></details>

What about `%rax`? Is this actually a correct syntax?
Our codebase in almost all other places doesn't use `%` here. GCC docs also doesn't use this syntax, see e.g. the rdtsc snippet there: https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Extended-Asm.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 51 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7Ve2J2XljfoPEsumH:-MKF8xuC2K7aVyS_aMGJ:b-4jr6hr) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L51)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I didn't know this but looks like you are right. From https://man7.org/linux/man-pages/man7/pthreads.7.html, it states that "Note that the pthreads functions do not set errno." But in the linux man page for all the pthread functions used in this file, they have examples and all these do e [...]

2020-10-23 05:54 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 17 of 28 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK4z1pz3GzmD0IRzcjv:-MKGNEZf7ZITc64OPteQ:bgeohol) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The one-liner from the first commit got wrapped, please fix this on the next rebase (i.e. after we resolve all code-related discussions).

> [Pal/Linux-SGX] Fix caching for leaf 0xB and 0x1F to properly
> enumerate CPU topology info.
</blockquote></details>

Sure, will fix this before the final PR

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK9Q5sQ9ftw0pY4cZ1n:-MKGbk2-8roOIby0ngoB:bhqa7os) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe better: instead of a dummy arg, let's just pass the iteration count there. This way CI and the user could customize the delay (and it's just one call to `atoi` and one less conditional).
</blockquote></details>

sounds good. Modified such that we pass the iteration and also check in the code so that when running manually by default it uses the longer iteration.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKFAtPh3mKzNhO9mHrG:-MKGNM6SCJS4EgOutHHB:bk5z5x9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now `__kernel_cpu_set_t` in shim_types.h is unused, same as all the macros it used.
</blockquote></details>

yes, I have removed this now. Also updated the new-syscall.rst file as well.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 200 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IZg01uB30u_bQ2bn:-MKGf5wd0a-n-OZAGm7c:bvpznip) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, just noticed this wrong usage of error codes of PAL in these new functions. See my other comments, but the general idea is like this:
1. You should *never* use the return value of `Dk...` functions as error codes. At most you use the return values to figure out "success" vs "fail".
2. You should *never* use `convert_pal_errno()` directly. Instead you must use `PAL_ERRNO()` macro. The logic is a bit quirky, but it's the same idea as with `errno` in libc.

In this particular case, you should convert `DkThread{Set,Get}CpuAffinity()` to return `PAL_BOOL` and use smth like:
```
    PAL_BOL ret = DkThreadSetCpuAffinity(thread->pal_handle, bitmask_size_in_bytes, user_mask_ptr);
    if (!ret) {
        put_thread(thread);
        return -PAL_ERRNO();
    }
```
</blockquote></details>

thanks, @dimakuv for the detailed explanation. I have fixed the code.
___
*[LibOS/shim/src/sys/shim_sched.c, line 244 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7IfM77mVgDR7_MyMe:-MKGta_W5sf5Yg4b4Rig:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/src/sys/shim_sched.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`PAL_BOL` and `PAL_ERRNO()`)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 146 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF24-SBSU28z87RaPp:-MKIpdCX3fu4XALe10Zr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please remove the double space
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 190 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF3M_D0MgRJP5t04qr:-MKIol4TBYUJJebUdAqA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L190)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 192 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF3cuj5qXedMx-Xnmc:-MKIq03c6StdjpzSipJK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> if not, should return -EFAULT */
> ```
No need for stating 1-1 what the code does right below (it was here before, but let's fix it while we're rewriting these functions). Ditto for setaffinity.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 197 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF3zuA9DRWt8wtkzFs:-MKIq35rCMby5YzPMfXm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please rewrap to 100-chars limit (ditto for all comments in both functions)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 200 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF48CmDlZJNM5j38d6:-MKIqeMb144Ow7_MLSkF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L200)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> must be %lu
> ```

This isn't true, should be: "must be at least".
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 204 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKEX-La16p-zZdSJiqm:-MKIo94Y-GWalsA-7uiz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/src/sys/shim_sched.c#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line before this comment (for visual separation)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7SDOjEEAqRGkdU13R:-MKGtrF6-blIUBohfLGw:bkd2lq7) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about `%rax`? Is this actually a correct syntax?
Our codebase in almost all other places doesn't use `%` here. GCC docs also doesn't use this syntax, see e.g. the rdtsc snippet there: https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Extended-Asm.
</blockquote></details>

I have removed the % sign from rax as well. But looks like it doesn't cause any impact. Even in our code, there are few places where we use % sign.

Just for my understanding created a test program and dumped the gcc generated assembly and see no difference if the clobbered register has % or no %. Also, this link https://www.ibiblio.org/gferg/ldp/GCC-Inline-Assembly-HOWTO.html, shows % sign being used in a couple of places. So I think this is not a concern but I will align with how most of the asm code is done in graphene.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK [...]

2020-10-23 08:53 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 192 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJ_wcG0Q0CUrLZU20q:-MKJ_wcG0Q0CUrLZU20r:basofuk) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/LibOS/shim/src/sys/shim_sched.c#L192)):*
> ```C
>     size_t cpu_cnt = PAL_CB(cpu_info.cpu_num);
> 
>     /* Check user_mask_ptr is valid; */
> ```

Nitpick: you have a trailing `;`
___
*[Pal/include/pal/pal.h, line 531 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKE_8673QY06ATXFyKh:-MKJbcRkB3Ob_l_17E8-:beieyvh) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/Pal/include/pal/pal.h#L531)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Why PAL num? I have modified `DkThreadGetCpuAffinity()` to return PAL_BOL as discussed in earlier conversations.
</blockquote></details>

Ok. Yes, that's even better. Your previous description of the return value threw me off.
___
*[Pal/include/pal/pal.h, line 520 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJbmgu8kthDxrPsEKV:-MKJbmgu8kthDxrPsEKW:bwc33a2) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L520)):*
> ```objc
>  * This function assumes that \a cpumask_size is a valid and greater than 0. Also \a cpu_mask, the
>  * user provided buffer is valid and readable. Host tid is part of \a thread which is extracted by
>  * the PAL layer to set the affinity of the given thread.
> ```

I suggest:
```
 * This function assumes that \a cpumask_size is valid and greater than 0. It also assumes that
 * the user-provided buffer \a cpu_mask is valid and readable. The thread to set the CPU affinity
* for is passed in \a thread and cannot be NULL.
```
___
*[Pal/include/pal/pal.h, line 522 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJctNQ2WRy46-PNfd-:-MKJctNQ2WRy46-PNfd0:b-q04y1z) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L522)):*
> ```objc
>  * the PAL layer to set the affinity of the given thread.
>  *
>  * \param thread pal identifier returned when creating the thread resource
> ```

Simply: `* \param thread PAL thread to set CPU affinity for`
___
*[Pal/include/pal/pal.h, line 526 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJd-Tj92FG0AHr4DL9:-MKJd-Tj92FG0AHr4DLA:b-f7842f) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L526)):*
> ```objc
>  * \param cpu_mask user-space pointer to the new CPU mask
>  *
>  * \return Returns 1 on success, 0 on failure. Use PAL_ERRNO() to get the actual linux error code
> ```

Please add a dot at the end.
___
*[Pal/include/pal/pal.h, line 536 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJcO6CAIoKs3q_XwB-:-MKJcO6CAIoKs3q_XwB0:b-w6o4oa) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L536)):*
> ```objc
>  * mask used by the kernel. It also expects \a cpumask_size to aligned by sizeof long. The user
>  * provide \a cpu_mask, must be valid and writable. Host tid is part of \a thread which is extracted
>  * by the PAL layer to get the affinity of the given thread.
> ```

I suggest:
```
 * This function assumes that \a cpumask_size is valid, aligned by sizeof(long), and is less than
 * the size of the affinity mask used by the host OS. It also assumes that the user-provided
 * \a cpu_mask is valid and writable. The thread to get the CPU affinity of is passed in \a thread
 * and cannot be NULL.

```
___
*[Pal/include/pal/pal.h, line 538 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJd66CBG_ImJPlkFV7:-MKJd66CBG_ImJPlkFV8:bpay40j) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L538)):*
> ```objc
>  * by the PAL layer to get the affinity of the given thread.
>  *
>  * \param thread pal identifier returned when creating the thread resource
> ```

Simply: `* \param thread PAL thread to get CPU affinity of`
___
*[Pal/include/pal/pal.h, line 542 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJd9IE-v4Re3I7vci0:-MKJd9IE-v4Re3I7vci1:b-hnhjv) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L542)):*
> ```objc
>  * \param cpu_mask user-space pointer to hold the current CPU mask
>  *
>  * \return Returns 1 on success, 0 on failure. Use PAL_ERRNO() to get the actual linux error code
> ```

Please add a dot at the end
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 324 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7L-9uBWC0dg8FpIQ7:-MKJdOHVAfYpeB7n_Ao_:biprlr3) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/Pal/src/host/Linux-SGX/db_misc.c#L324)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

These leaves provide the following,
```
1. bits to shift APIC ID to get next
2. logical processors at this level
3. level number                      
4. level type                        
5. extended APIC ID              
```
Of these only EDX, extended APIC ID output is independent of values in ECX. But even for this, there is no reference to cross verify. So suggest we take up shielding of CPUID leaves (including the above) as a separate PR.

</blockquote></details>

+1 to Vijay
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1489 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJdeB46fhho3fiKGg5:-MKJdeB46fhho3fiKGg6:b-gigtqq) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1489)):*
> ```C
>     retval = sgx_exitless_ocall(OCALL_SCHED_SETAFFINITY, ms);
>     if (IS_ERR(retval) && !IS_UNIX_ERR(retval))
>         retval = -EACCES;
> ```

This is cool but I would prefer a more restricted list of possible errors on `sched_setaffinity()`. So like this:
```
    if (IS_ERR(retval) && retval != EFAULT && retval != EINVAL && retval != EPERM && retval != ESRCH)
        retval = -EPERM;
```

Note that I throw `EPERM` instead of `EACCES`.This is what we throw in all other "bad" cases during OCALL handling.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1517 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJeDQ312N0Zh01i1Nt:-MKJeDQ312N0Zh01i1Nu:b-epve6h) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1517)):*
> ```C
>     retval = sgx_exitless_ocall(OCALL_SCHED_GETAFFINITY, ms);
>     if (IS_ERR(retval) && !IS_UNIX_ERR(retval))
>         retval = -EACCES;
> ```

ditto (restricted set of possible error codes)


<!-- Sent from Reviewable.io -->

2020-10-23 16:41 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 192 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJ_wcG0Q0CUrLZU20q:-MKL3wuF4-BC2BgGky71:bzb0gh8) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/LibOS/shim/src/sys/shim_sched.c#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nitpick: you have a trailing `;`
</blockquote></details>

ah, Done.
___
*[Pal/include/pal/pal.h, line 520 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJbmgu8kthDxrPsEKV:-MKL909dAiLGGZIhSx-G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L520)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest:
```
 * This function assumes that \a cpumask_size is valid and greater than 0. It also assumes that
 * the user-provided buffer \a cpu_mask is valid and readable. The thread to set the CPU affinity
* for is passed in \a thread and cannot be NULL.
```
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 522 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJctNQ2WRy46-PNfd-:-MKLALy8-aZrOYsQY_nf:b-qr9464) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Simply: `* \param thread PAL thread to set CPU affinity for`
</blockquote></details>

Modified as `\param thread PAL thread for which to set the CPU affinity.`
___
*[Pal/include/pal/pal.h, line 526 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJd-Tj92FG0AHr4DL9:-MKLAkj08BYjDWZP0VLh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L526)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot at the end.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 536 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJcO6CAIoKs3q_XwB-:-MKLAKoa6XPxZV3mr5IB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L536)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest:
```
 * This function assumes that \a cpumask_size is valid, aligned by sizeof(long), and is less than
 * the size of the affinity mask used by the host OS. It also assumes that the user-provided
 * \a cpu_mask is valid and writable. The thread to get the CPU affinity of is passed in \a thread
 * and cannot be NULL.

```
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 538 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJd66CBG_ImJPlkFV7:-MKLEn7ZBOeiK6ih0ide:b-e4ctjd) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L538)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Simply: `* \param thread PAL thread to get CPU affinity of`
</blockquote></details>

Modified as '\param thread PAL thread for which to get the CPU affinity.`
___
*[Pal/include/pal/pal.h, line 542 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJd9IE-v4Re3I7vci0:-MKLExLgB4rxJ7XYN0On:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L542)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot at the end
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1489 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJdeB46fhho3fiKGg5:-MKLFBOV6BbbTW0sV7ab:bm9lhoc) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1489)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is cool but I would prefer a more restricted list of possible errors on `sched_setaffinity()`. So like this:
```
    if (IS_ERR(retval) && retval != EFAULT && retval != EINVAL && retval != EPERM && retval != ESRCH)
        retval = -EPERM;
```

Note that I throw `EPERM` instead of `EACCES`.This is what we throw in all other "bad" cases during OCALL handling.
</blockquote></details>

Even I had the same opinion but did have a quick chat with @mkow and he wanted to have a more generic error checking for all E* errors. I think with generic error, we are a little more future proof. But I am fine with either way. @mkow please confirm.

Regrading `-EACCES` wanted to differentiate this special case of error handling but have changed the return to `-EPERM`.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1517 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJeDQ312N0Zh01i1Nt:-MKLGd0X10G7NWSD20-d:buzkqml) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1517)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (restricted set of possible error codes)
</blockquote></details>

Changed the return to `-EPERM`


<!-- Sent from Reviewable.io -->

2020-10-26 22:35 UTC, mkow requested changes
> Reviewed 1 of 12 files at r11, 8 of 11 files at r12, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKFAtPh3mKzNhO9mHrG:-MK_fPO83xcXFq7TOkin:b-cbjqm) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, I have removed this now. Also updated the new-syscall.rst file as well.
</blockquote></details>

Looks good, thanks for also taking care about the docs :)

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 148 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKagiLJ7HAXPles1xby:-MKagiLJ7HAXPles1xbz:bkysscs) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/src/sys/shim_sched.c#L148)):*
> ```C
>     size_t cpu_cnt = PAL_CB(cpu_info.cpu_num);
> 
>     /* check user_mask_ptr is valid */
> ```

Could you add "if" in the place of this "that" you removed? ("check if user_mask_ptr is valid") Would read better.
___
*[LibOS/shim/src/sys/shim_sched.c, line 192 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_nsWA8yLmqxPHhhNw:-MK_nsWA8yLmqxPHhhNx:b-o5hpja) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/src/sys/shim_sched.c#L192)):*
> ```C
>     size_t cpu_cnt = PAL_CB(cpu_info.cpu_num);
> 
>     /* Check user_mask_ptr is valid */
> ```

ditto (add "if")
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 25 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7SDOjEEAqRGkdU13R:-MKa3roIA-9DHe9a9Z50:b-owwesu) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/LibOS/shim/test/regression/pthread_set_get_affinity.c#L25)):*
> Even in our code, there are few places where we use % sign.

Yeah, I know, but they seem to be a simple overlooks in reviews ;)

And thank you for testing this :)
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 31 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKF6t9U7AIsHjkxBGMl:-MKagZnd9t7TK_odXhJY:bx86iue) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/LibOS/shim/test/regression/pthread_set_get_affinity.c#L31)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, we do at least for the number of CPUs. sysconf(_SC_NPROCESSORS_ONLN) ends up calling glibc's `__get_nprocs()` and this ends up calling /proc/cpuinfo. Here we have a check like below for number of CPUs

`(num_cpus >= 1 && num_cpus <= (1 << 16))`
</blockquote></details>

Thanks for checking this!
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 47 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKa58-z7TWfAv-YXfWh:-MKa58-z7TWfAv-YXfWi:behiw4b) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L47)):*
> ```C
> 
>     /* if no cmdline options are provided, this test runs for a longer duration for manual
>      * verification, otherwise runs only for a short time */
> ```

The comment is now outdated.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 56 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_eaRj1ni0OfXIZyyA:-MK_eaRj1ni0OfXIZyyB:bhvwgl) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L56)):*
> ```C
>         CPU_SET(i*2, &cpus);
> 
>         ret = pthread_create(&threads[i], NULL, dowork, (void*)iterations);
> ```

Could you pass `&iterations` instead? I don't like this assumption that pointers have 64 bits.
___
*[Pal/include/pal/pal.h, line 517 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7FIqu66tlDP98GGst:-MKafPBJED1qGu6g9dFp:b-q64pkt) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/Pal/include/pal/pal.h#L517)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done, please check if any other information needs to be documented.
</blockquote></details>

See above.
___
*[Pal/include/pal/pal.h, line 518 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKFBPwOCHbj6fo-bp5o:-MKaetsO-0Od-hENGqux:bwsofpl) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/Pal/include/pal/pal.h#L518)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I have taken a stab at the text, please let me know if anything else needs to be added.
</blockquote></details>

You're still missing cases like what happens when the API is called with bigger mask than the real CPUs (or too small, in case of getaffinity). What I mean is: imagine you're implementing e.g. Windows or mac OS PAL. You want to implement those 2 calls based on the documentation placed here alone. Right now this won't be possible, because the documentation doesn't describe everything which LibOS relies on (e.g. when implementing getaffinity behavior with wrong mask sizes).
___
*[Pal/include/pal/pal.h, line 520 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJbmgu8kthDxrPsEKV:-MK_lMUJAcJabpamLR0z:b15horg) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L520)):*
> ```
> It also assumes that the user provided buffer \a cpu_mask is valid and readable.
> ```

No need to specify this, this is true for all the APIs here. The only API which is different is the syscall API we emulate.
___
*[Pal/include/pal/pal.h, line 536 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJcO6CAIoKs3q_XwB-:-MK_mHvj-SayhghYGezK:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L536)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[Pal/include/pal/pal.h, line 518 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_kdDe2BR7WLr9pXby:-MK_kdDfANSRmhBQJUdD:bpwuxc7) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/Pal/include/pal/pal.h#L518)):*
> ```objc
>  * \brief Sets the CPU affinity of a thread.
>  *
>  * This function assumes that \a cpumask_size is a valid and greater than 0. It also assumes that
> ```

`is a valid` -> `is valid`
___
*[Pal/include/pal/pal.h, line 519 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKaajnvC4Qq2XGGpeEo:-MKaajnwBMNMFe1aNGVr:b-9lp9y2) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/Pal/include/pal/pal.h#L519)):*
> ```objc
>  *
>  * This function assumes that \a cpumask_size is a valid and greater than 0. It also assumes that
>  * the user provided buffer \a cpu_mask is valid and readable. The \a thread to set the CPU affinity
> ```

`The \a thread` -> `The thread` (in this case this wasn't used as a param, but as an English word)
___
*[Pal/include/pal/pal.h, line 533 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_m_KK30Nf4rgCN81l:-MK_m_KK30Nf4rgCN81m:bpwuxc7) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/Pal/include/pal/pal.h#L533)):*
> ```objc
>  * \brief Gets the CPU affinity of a thread.
>  *
>  * This function assumes that \a cpumask_size is a valid and is aligned by sizeof(long), and is less
> ```

`is a valid` -> `is va [...]

2020-10-27 09:36 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1489 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJdeB46fhho3fiKGg5:-MKdPWaTCRr1Z903w8nB:b6i91yz) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1489)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, I think having a precise whitelist of error codes will be very hard to maintain, because e.g. there isn't a definitive list of possible return values on the syscall layer, new errors get introduced in new kernels, etc.

Maybe the right question is actually whether our untrusted interface should look like this. It's Linux-oriented and almost a direct syscall-passthrough, but maybe it should look more like PAL API? Also, I don't like this split into PAL API and OCALL API, looks like the first wasn't flexible enough so someone added another later instead of coming up with just one interface. \<end of rambling\>
</blockquote></details>

OK, agreed with Michal.


<!-- Sent from Reviewable.io -->

2020-10-27 10:19 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 23 of 28 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 148 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKagiLJ7HAXPles1xby:-MKdA-sL6S7_Kj_Ky90j:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/src/sys/shim_sched.c#L148)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add "if" in the place of this "that" you removed? ("check if user_mask_ptr is valid") Would read better.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 192 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_nsWA8yLmqxPHhhNw:-MKdA83u5HjMQanVK6l9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/src/sys/shim_sched.c#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (add "if")
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 47 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKa58-z7TWfAv-YXfWh:-MKdAaab1b5rWnPdPYw6:b-lhfwy2) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The comment is now outdated.
</blockquote></details>

why? The comment seems valid here. When doing make regression, command-line arguments are provided but if the user does `make SGX=1 or make` and doesn't provide any command-line options, the test runs for a longer duration.
___
*[Pal/include/pal/pal.h, line 518 at r11](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKFBPwOCHbj6fo-bp5o:-MKdOgmHAVydw5u4U7My:b6l5oyz) ([raw file](https://github.com/oscarlab/graphene/blob/f69e4ab42aa994e4e31532345e7f01da1b04b1fb/Pal/include/pal/pal.h#L518)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You're still missing cases like what happens when the API is called with bigger mask than the real CPUs (or too small, in case of getaffinity). What I mean is: imagine you're implementing e.g. Windows or mac OS PAL. You want to implement those 2 calls based on the documentation placed here alone. Right now this won't be possible, because the documentation doesn't describe everything which LibOS relies on (e.g. when implementing getaffinity behavior with wrong mask sizes).
</blockquote></details>

I have addressed the cpu mask size. Hope this is more clear.
___
*[Pal/include/pal/pal.h, line 520 at r12](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKJbmgu8kthDxrPsEKV:-MKdOrm14OEy_PRMZMCY:bs7wumb) ([raw file](https://github.com/oscarlab/graphene/blob/6e5f4a7f9a5d65d452434efcaeb95b396c4267e5/Pal/include/pal/pal.h#L520)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> It also assumes that the user provided buffer \a cpu_mask is valid and readable.
> ```

No need to specify this, this is true for all the APIs here. The only API which is different is the syscall API we emulate.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 518 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_kdDe2BR7WLr9pXby:-MKdOvqQDfwjJ1X0ordT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/Pal/include/pal/pal.h#L518)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`is a valid` -> `is valid`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 519 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKaajnvC4Qq2XGGpeEo:-MKdOz144CPBSyJeVnE4:b-pdzs85) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/Pal/include/pal/pal.h#L519)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`The \a thread` -> `The thread` (in this case this wasn't used as a param, but as an English word)
</blockquote></details>

yes correct, removed `\a`
___
*[Pal/include/pal/pal.h, line 533 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_m_KK30Nf4rgCN81l:-MKdOwjz1qRn4kJpVERo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/Pal/include/pal/pal.h#L533)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`is a valid` -> `is valid`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 536 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKafDLEEOGoZ7BccwWn:-MKdP4g-6BMpmvPuh3T0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/Pal/include/pal/pal.h#L536)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> and cannot be NULL.
> ```

No need to say this, all APIs assume non-NULLness by default (i.e. if not specified otherwise).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1513 at r10](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK7MwwL2bBugR0vB2pa:-MKdPHL5-d71AIV7MhXl:bju8thb) ([raw file](https://github.com/oscarlab/graphene/blob/a12d315c94e36978a4a1c12f713e0d7edd3e9cae/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1513)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We assume here that it's an array of `cpumask_size` bytes anyways (we're using this OCALL to implement `DkThreadSetCpuAffinity()`, which is a PAL API, so it's Linux-agnostic and has strictly defined semantics). You can just cast it (or change the argument type) to `uint8_t*`.
</blockquote></details>

Added a new function to check the validity of `untrusted_cpu_mask`


<!-- Sent from Reviewable.io -->

2020-10-28 02:04 UTC, mkow requested changes
> Reviewed 5 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 47 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKa58-z7TWfAv-YXfWh:-MKgpjta3Z96w6M6UdXT:bhzmdd5) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L47)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

why? The comment seems valid here. When doing make regression, command-line arguments are provided but if the user does `make SGX=1 or make` and doesn't provide any command-line options, the test runs for a longer duration.
</blockquote></details>

right, it's not obvious, but if you read it literally it says:
- if there's no cmdline argument then the test takes long time
- if there's a cmdline argument then the test takes short time

which isn't what actually happens - first point is true, but the second is not.
___
*[Pal/include/lib/api.h, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgr1l73k9DBMikFB8P:-MKgr1l89z1oYwwSya8z:b-vh5utv) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L72)):*
> ```objc
> #define BITS_IN_TYPE(type)             (sizeof(type) * BITS_IN_BYTE)
> #define BITS_TO_LONGS(nr)              DIV_ROUND_UP(nr, BITS_IN_TYPE(long))
> #define BYTES_PER_LONG(nr)             (nr / sizeof(long))
> ```

you need to parenthesize `nr` in the macro, e.g. `BYTES_PER_LONG(1+7)` will return wrong value
___
*[Pal/include/lib/api.h, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKguUUvE0LZD0xV0oMD:-MKguUUw2XS79GPruOgp:b4y2gj9) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L72)):*
> ```objc
> #define BITS_IN_TYPE(type)             (sizeof(type) * BITS_IN_BYTE)
> #define BITS_TO_LONGS(nr)              DIV_ROUND_UP(nr, BITS_IN_TYPE(long))
> #define BYTES_PER_LONG(nr)             (nr / sizeof(long))
> ```

I don't like the name of this macro, I read the implementation first and got confused - it sounds like it should just equal to `sizeof(long)`, which is the number of bytes in a `long`.
I don't have a better idea for the name, but it's used only in one place - maybe it's better to just inline the division and remove this macro?
___
*[Pal/include/lib/api.h, line 73 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgs-fm64ORhmG3fvbK:-MKgs-fn5RxQorRLQsdG:b-5j7w4g) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L73)):*
> ```objc
> #define BITS_TO_LONGS(nr)              DIV_ROUND_UP(nr, BITS_IN_TYPE(long))
> #define BYTES_PER_LONG(nr)             (nr / sizeof(long))
> #define SET_LAST_N_BITS(type, nbits)   (~((1UL << (BITS_IN_TYPE(type) - (nbits))) - 1))
> ```

nitpick: `unsigned long` may not be really too long, it can actually have less than 64 bits. I'd prefer to use `unsigned type` (or some other way to enforce `type` to be unsigned) instead, this way you'll always get the correct result (assuming I'm not missing anything)
___
*[Pal/include/lib/api.h, line 73 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgvHXjAQbeEvx9sKsT:-MKgvHXk2QIKf3Qqakh1:bibz8j2) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L73)):*
> ```
> SET_LAST_N_BITS
> ```
I don't like the "last" naming - I think it's not obvious if "last bist" are the highest or the lowest ones. I'd prefer `SET_HIGHEST_N_BITS` or something similar.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1507 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgu6DDEDLQkxPrE6HE:-MKgu6DDEDLQkxPrE6HF:blzcrvy) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1507)):*
> ```C
> 
>     /* Extract last 64bits to check if any invalid cpu bits are set */
>     int idx = (BYTES_PER_LONG(cpumask_size) - 1);
> ```

the outer parentheses are redundant here
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1512 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgwC2--AyRNZQuBGC0:-MKgwC2--AyRNZQuBGC1:b-fuf7kb) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1512)):*
> ```
>     if (!(cpumask & invalid_cpumask))
>         return true;
>     return false;
> ```

You can just return `!(cpumask & invalid_cpumask)`


<!-- Sent from Reviewable.io -->

2020-10-28 06:00 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 47 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKa58-z7TWfAv-YXfWh:-MKhf5EfDKnAj4DLdW-u:b-i4fo19) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

right, it's not obvious, but if you read it literally it says:
- if there's no cmdline argument then the test takes long time
- if there's a cmdline argument then the test takes short time

which isn't what actually happens - first point is true, but the second is not.
</blockquote></details>

Got it :). I have modified the statement a little bit to reflect this.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 56 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK_eaRj1ni0OfXIZyyA:-MKhf3Ki-TBOZZPGcYKW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you pass `&iterations` instead? I don't like this assumption that pointers have 64 bits.
</blockquote></details>

Done.
___
*[Pal/include/lib/api.h, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgr1l73k9DBMikFB8P:-MKhg3EcEpkaPIfmxV3Y:blc8ww6) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

you need to parenthesize `nr` in the macro, e.g. `BYTES_PER_LONG(1+7)` will return wrong value
</blockquote></details>

yes removed this macro.
___
*[Pal/include/lib/api.h, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKguUUvE0LZD0xV0oMD:-MKhh9Ff1bw6kkZQD67D:b-pfap0h) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like the name of this macro, I read the implementation first and got confused - it sounds like it should just equal to `sizeof(long)`, which is the number of bytes in a `long`.
I don't have a better idea for the name, but it's used only in one place - maybe it's better to just inline the division and remove this macro?
</blockquote></details>

inlined instead of having a macro.
___
*[Pal/include/lib/api.h, line 73 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgvHXjAQbeEvx9sKsT:-MKhhlIG-1iPdmfc1_1_:beeboxl) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> SET_LAST_N_BITS
> ```
I don't like the "last" naming - I think it's not obvious if "last bist" are the highest or the lowest ones. I'd prefer `SET_HIGHEST_N_BITS` or something similar.
</blockquote></details>

Used `SET_HIGHEST_N_BITS` as the name of the macro.
___
*[Pal/include/lib/api.h, line 73 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgs-fm64ORhmG3fvbK:-MKhl72dAbJBrS93NjTD:b-6qyu3t) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: `unsigned long` may not be really too long, it can actually have less than 64 bits. I'd prefer to use `unsigned type` (or some other way to enforce `type` to be unsigned) instead, this way you'll always get the correct result (assuming I'm not missing anything)
</blockquote></details>

@mkow are you suggesting to use unsigned long long? The idea is we just have type in the macro and the user can choose whatever datatype they want to use. If they prefer unsigned long long, the expansion of the macro will result in calculating the sizeof(type) which will be sizeof(unsigned long long).
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1507 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgu6DDEDLQkxPrE6HE:-MKhiVwiCBmFrqEjUvx_:b5lhcno) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1507)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

the outer parentheses are redundant here
</blockquote></details>

got it, but I have removed the macro itself now.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1512 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgwC2--AyRNZQuBGC0:-MKhj1eH0Yr9G6g1BkRA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1512)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>     if (!(cpumask & invalid_cpumask))
>         return true;
>     return false;
> ```

You can just return `!(cpumask & invalid_cpumask)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 09:50 UTC, dimakuv requested changes
> Reviewed 2 of 12 files at r10, 5 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 47 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKa58-z7TWfAv-YXfWh:-MKi_PpFBuMojpnhV4fN:bvr1v5j) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L47)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Got it :). I have modified the statement a little bit to reflect this.
</blockquote></details>

I don't see a change, forgot to save/push?
___
*[Pal/include/lib/api.h, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgr1l73k9DBMikFB8P:-MKi_gxc8vrLRJFD0N1I:b4mxpzp) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L72)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes removed this macro.
</blockquote></details>

Forgot to push changes?
___
*[Pal/include/lib/api.h, line 73 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgvHXjAQbeEvx9sKsT:-MKi_ie-CrbR1kTIxo7h:b4mxpzp) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L73)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Used `SET_HIGHEST_N_BITS` as the name of the macro.
</blockquote></details>

Forgot to push changes?
___
*[Pal/include/pal/pal.h, line 519 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKibEjj43jJFMKGLA8L:-MKibEjj43jJFMKGLA8M:b-s9q9cn) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/pal/pal.h#L519)):*
> ```objc
>  *
>  * This function assumes that \a cpumask_size is valid and greater than 0. \a cpumask_size should be
>  * just large enough to fit the number of processors available in the system and should be aligned
> ```

I don't like this `just` word here. Maybe simply remove it?
___
*[Pal/include/pal/pal.h, line 535 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKibIJc2uFB3XXsFyKO:-MKibIJc2uFB3XXsFyKP:b-s9q9cn) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/pal/pal.h#L535)):*
> ```objc
>  *
>  * This function assumes that \a cpumask_size is valid and greater than 0. \a cpumask_size should be
>  * just large enough to fit the number of processors available in the system and should be aligned
> ```

I don't like this `just` word here. Maybe simply remove it?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1507 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgu6DDEDLQkxPrE6HE:-MKiaNoME6l5DQCLTTtH:bf83zmg) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1507)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

got it, but I have removed the macro itself now.
</blockquote></details>

Forgot to push?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1512 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgwC2--AyRNZQuBGC0:-MKia5bbESo3P-6BjlpV:bf83zmg) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1512)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Forgot to push?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1540 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKianHVElUceqpeLvfQ:-MKianHVElUceqpeLvfR:bgcqfz1) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1540)):*
> ```C
> 
>     if (!is_cpumask_valid(untrusted_cpu_mask, cpumask_size))
>         retval = -EPERM;
> ```

Please move this check *after* `sgx_copy_to_enclave()` below. And replace `untrusted_cpu_mask` with `cpu_mask`.

This is for security. Right now you check CPU-mask validity on the untrusted memory and only after copy from untrusted memory inside the enclave. But you must *first* copy inside the enclave and *then* check CPU-mask validity.


<!-- Sent from Reviewable.io -->

2020-10-28 15:40 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1504 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKjmeRh4Dn-htetetHx:-MKjmeRi82Cbt3bXUaKK:bpeox1e) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1504)):*
> ```C
> 
>     /* create an invalid cpu_mask bits */
>     unsigned long invalid_cpumask = SET_LAST_N_BITS(unsigned long, invalid_bits);
> ```

`SET_LAST_N_BITS` doesn't work with `nbits == BITS_IN_TYPE(type)`, which I think can happen here? (in such case the bitshift is too large and causes an undefined behavior)
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1540 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKianHVElUceqpeLvfQ:-MKjo2VY1Y3JwUJbnjtb:b5moesz) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1540)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this check *after* `sgx_copy_to_enclave()` below. And replace `untrusted_cpu_mask` with `cpu_mask`.

This is for security. Right now you check CPU-mask validity on the untrusted memory and only after copy from untrusted memory inside the enclave. But you must *first* copy inside the enclave and *then* check CPU-mask validity.
</blockquote></details>

Good catch, I missed this.


<!-- Sent from Reviewable.io -->

2020-10-28 16:24 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 143 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKk0DxB7BuxWMqVqqxR:-MKk0DxB7BuxWMqVqqxS:b-dhy3sk) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/LibOS/shim/src/sys/shim_sched.c#L143)):*
> ```C
> }
> 
> long shim_do_sched_setaffinity(pid_t pid, unsigned int cpumask_size, unsigned long* user_mask_ptr) {
> ```

I missed this before, but why is `cpumask_size` ignored in the implementation? What if the used provided e.g. too small buffer? Please look at the kernel implementation and make this function behave 1-1 with it in all edge cases.


<!-- Sent from Reviewable.io -->

2020-10-28 17:44 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1540 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKianHVElUceqpeLvfQ:-MKkI81BCt_-foiMlyz5:b5u0x5w) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1540)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good catch, I missed this.
</blockquote></details>

@dimakuv but why copy from `untrusted_cpu_mask` inside enclave if it is not even valid?


<!-- Sent from Reviewable.io -->

2020-10-28 20:19 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 23 of 28 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_sched.c, line 143 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKk0DxB7BuxWMqVqqxR:-MKkaO5hCc9brTuCkwZ0:bna3avx) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/LibOS/shim/src/sys/shim_sched.c#L143)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I missed this before, but why is `cpumask_size` ignored in the implementation? What if the used provided e.g. too small buffer? Please look at the kernel implementation and make this function behave 1-1 with it in all edge cases.
</blockquote></details>

Yes, correct, this is a bug. Linux's setaffinity implementation has the following check for the `cpumask_size`.
1. If the user passed buffer len that can only hold a lesser number of processors than supported on the host, it ends up using it.
2. if the user passed buffer len is greater than the number of processors supported on the host, then it simply truncates then len to the number of processors supported on the host.

```
if (len < cpumask_size())
	cpumask_clear(new_mask);
else if (len > cpumask_size())
	len = cpumask_size();

where cpumask_size() ==> BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long);
```

I only did #2. I have fixed the code to include #1 as well.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 47 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKa58-z7TWfAv-YXfWh:-MKkowoFCH_4xVblq09x:b-4sdt2q) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see a change, forgot to save/push?
</blockquote></details>

ditto. But I have removed this comment. It is explicit from the code :)
___
*[Pal/include/lib/api.h, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgr1l73k9DBMikFB8P:-MKkdXl_6ByVTy62fQ1y:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to push changes?
</blockquote></details>

ditto
___
*[Pal/include/lib/api.h, line 73 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgs-fm64ORhmG3fvbK:-MKk_3UE3_dG9NBbCtsI:b-tzitej) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L73)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@mkow are you suggesting to use unsigned long long? The idea is we just have type in the macro and the user can choose whatever datatype they want to use. If they prefer unsigned long long, the expansion of the macro will result in calculating the sizeof(type) which will be sizeof(unsigned long long).
</blockquote></details>

@mkow thanks for the clarification on `unsigned long`. I will cast with `uint64_t` instead of `UL`. 
___
*[Pal/include/lib/api.h, line 73 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgvHXjAQbeEvx9sKsT:-MKk_MWu7gPdtF_6lI0p:b-yyc8z4) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/lib/api.h#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to push changes?
</blockquote></details>

no, I wanted to ack @mkow suggestions and respond. But will just reply to comments in the future to avoid this confusion. 
___
*[Pal/include/pal/pal.h, line 519 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKibEjj43jJFMKGLA8L:-MKklQ1K7o70rkspdKuE:b1q62u8) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/pal/pal.h#L519)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this `just` word here. Maybe simply remove it?
</blockquote></details>

I have removed it and also reworded to emphasize the `cpumask_size` len.
___
*[Pal/include/pal/pal.h, line 535 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKibIJc2uFB3XXsFyKO:-MKklbq-7ZBw2ZN58HSc:b-hhvlxy) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/include/pal/pal.h#L535)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this `just` word here. Maybe simply remove it?
</blockquote></details>

I have removed it and also reworded to emphasize the `cpumask_size` len.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1504 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKjmeRh4Dn-htetetHx:-MKkdokc4IbJFOF84vK5:b-cpcba5) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1504)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`SET_LAST_N_BITS` doesn't work with `nbits == BITS_IN_TYPE(type)`, which I think can happen here? (in such case the bitshift is too large and causes an undefined behavior)
</blockquote></details>

@mkow we discussed, linux kernel does the following checks with user buffer len(in our case `cpumask_size`) for getaffinity
1. if buffer len is not aligned by `sizeof(long)` return an error.
2. if buffer len is less than the number of processors supported in the host, return an error.
3. if buffer len is greater than the number of processors supported in the host, truncate len to buffer size that can hold all the processors in the system which sets `cpumask_size = BITS_TO_LONGS(cpu_cnt) * sizeof(long)`.  cpu_cnt is the number of processors in the host.

We do emulate these in our code and due to #3, nbits will be either 0 or less than `BITS_IN_TYPE(type)` so it is safe to assume that `nbits != BITS_IN_TYPE(type)`.

Also, we have documented these conditions `DkThreadGetCpuAffinity ` so that other PAL implementations like windows can follow these changes.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1507 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgu6DDEDLQkxPrE6HE:-MKk_x5Q5E8pdJtpd-vf:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1507)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to push?
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1512 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKgwC2--AyRNZQuBGC0:-MKk_ynN97YKjhXRHCFD:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1512)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to push?
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1540 at r14](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKianHVElUceqpeLvfQ:-MKka-M42tkmaLEtpc30:b2ueq5j) ([raw file](https://github.com/oscarlab/graphene/blob/7b563f0d5618d1402f344bca555f43f04fbcc193/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1540)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv but why copy from `untrusted_cpu_mask` inside enclave if it is not even valid?
</blockquote></details>

Thanks, @dimakuv. Had a quick  [...]

2020-10-29 09:56 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKngF2d9uvxCU2743oZ:bpd51id) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
> ```objc
>  * set len such that it is large enough to fit all processors available in the host. For example
>  * if the host supports 4 CPUs, \a cpumask_size should be 8 bytes or less. The thread tid to set the
>  * CPU affinity for is passed in \a thread.
> ```

I don't like this comment. What is `cpumask_size is less` (less than what?)? What is `len` -- you don't have such a variable here? Also, the last sentence duplicates the parameter description below, so can be removed.

I suggest this:
```
 * This function assumes that \a cpumask_size is valid and non-negative. It is allowed for \a cpumask_size
 * to fit less CPUs than available on the host: then only the fitting CPUs are set in \a cpumask. It is not allowed
 * for \a cpumask_size to fit more CPUs than available on the host. For example, if the host supports 4 CPUs,
 * \a cpumask_size must be 8 bytes or less (but not more than 8 bytes).
```
___
*[Pal/include/pal/pal.h, line 528 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnfv0P1b-tJG1bCm7i:-MKnfv0P1b-tJG1bCm7j:b1llbqv) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L528)):*
> ```objc
>  * \param cpu_mask user-space pointer to the new CPU mask.
>  *
>  * \return Returns 1 on success, 0 on failure. Use PAL_ERRNO() to get the actual linux error code.
> ```

Just realized: please change `actual linux error code` -> `actual error code`. There are no "Linux" codes that PAL functions return, they always return PAL-specific error codes.
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKnipKe2LsmSLZSv80R:bytk5qe) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
> ```objc
>  * should be returned to the user. If \a cpumask_size is larger set len such that it is large enough
>  * to fit all processors available in the host.  For example if the host supports 4 CPUs,
>  * \a cpumask_size should be 8 bytes. Thread tid to get the CPU affinity of is passed in \a thread.
> ```

Similarly, I don't like this comment. What is `cpumask_size is less` (less than what?)? What is `len` -- you don't have such a variable here? Also, the last sentence duplicates the parameter description below, so can be removed.

I suggest this:
```
 * This function assumes that \a cpumask_size is valid, greater than 0 and aligned by sizeof(long).
 * It is not allowed for \a cpumask_size to fit less or more CPUs than available on the host.  
 * For example, if the host supports 4 CPUs, \a cpumask_size must be exactly 8 bytes.
```
___
*[Pal/include/pal/pal.h, line 545 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKng7A4-RikazGFz4pB:-MKng7A4-RikazGFz4pC:b1llbqv) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L545)):*
> ```objc
>  * \param cpu_mask user-space pointer to hold the current CPU mask.
>  *
>  * \return Returns 1 on success, 0 on failure. Use PAL_ERRNO() to get the actual linux error code.
> ```

Just realized: please change `actual linux error code` -> `actual error code`. There are no "Linux" codes that PAL functions return, they always return PAL-specific error codes.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1538 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnlGRd-Rt6I8xTliV-:-MKnlGRd-Rt6I8xTliV0:b-dpqjtt) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1538)):*
> ```C
> 
>     if (retval > 0) {
>         retval = sgx_copy_to_enclave(cpu_mask, cpumask_size, untrusted_cpu_mask, retval);
> ```

Just noticed this bug. `sgx_copy_to_enclave()` returns bool (so, `0` or `1`). You cannot assign it to `retval`, this makes no sense.

You must replace with something like this:
```
    if (retval > 0) {
        if (!sgx_copy_to_enclave(cpu_mask, cpumask_size, untrusted_cpu_mask, retval)) {
            sgx_reset_ustack(old_ustack);
            return -EPERM;
        }
    }
```


<!-- Sent from Reviewable.io -->

2020-10-29 17:29 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKpFAHJ-ez3Flz4xIGc:b-lhgerg) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this comment. What is `cpumask_size is less` (less than what?)? What is `len` -- you don't have such a variable here? Also, the last sentence duplicates the parameter description below, so can be removed.

I suggest this:
```
 * This function assumes that \a cpumask_size is valid and non-negative. It is allowed for \a cpumask_size
 * to fit less CPUs than available on the host: then only the fitting CPUs are set in \a cpumask. It is not allowed
 * for \a cpumask_size to fit more CPUs than available on the host. For example, if the host supports 4 CPUs,
 * \a cpumask_size must be 8 bytes or less (but not more than 8 bytes).
```
</blockquote></details>

By `len` I meant the length of `cpumask_size`.
I think it will be better if we can clarify `It is not allowed for \a cpumask_size to fit more CPUs than available on the host`.

How about this?
```
 * This function assumes that \a cpumask_size is valid and non-negative. Also, if \a cpumask_size is
 * larger than the number of processors in the host, it must be truncated such that it can fit all
 * the processors in the host <b>and<\b> is aligned by sizeof(long). For example, if the host
 * supports 4 CPUs, \a cpumask_size can be 8 bytes or less (but not more than 8 bytes).
 * \note \a cpumask_size that cannot fit all the processors in the host or not aligned by
 * sizeof(long) are considered valid but only the CPUs fitting \a cpumask_size will be set.

```
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKont2f249gRyUjBd02:b-uv6f8s) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Similarly, I don't like this comment. What is `cpumask_size is less` (less than what?)? What is `len` -- you don't have such a variable here? Also, the last sentence duplicates the parameter description below, so can be removed.

I suggest this:
```
 * This function assumes that \a cpumask_size is valid, greater than 0 and aligned by sizeof(long).
 * It is not allowed for \a cpumask_size to fit less or more CPUs than available on the host.  
 * For example, if the host supports 4 CPUs, \a cpumask_size must be exactly 8 bytes.
```
</blockquote></details>

By `len` I meant the length of `cpumask_size`.
`It is not allowed for \a cpumask_size to fit less or more CPUs...`. This statement to me looks to imply that the cpumask_size should be 4 bits which is not the case.

How about this?
```
 * This function assumes that \a cpumask_size is valid and greater than 0. Also, \a cpumask_size
 * must be able to fit all the processors in the host <b>and</b> must be aligned by sizeof(long).
 * For example, if the host supports 4 CPUs, \a cpumask_size should be 8 bytes.
 * \note \a cpumask_size that cannot fit all the processors in the host or is not aligned by
 * sizeof(long) are considered invalid.
```
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1538 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnlGRd-Rt6I8xTliV-:-MKon3Hg4JZcZIYVwINB:bmspkls) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1538)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed this bug. `sgx_copy_to_enclave()` returns bool (so, `0` or `1`). You cannot assign it to `retval`, this makes no sense.

You must replace with something like this:
```
    if (retval > 0) {
        if (!sgx_copy_to_enclave(cpu_mask, cpumask_size, untrusted_cpu_mask, retval)) {
            sgx_reset_ustack(old_ustack);
            return -EPERM;
        }
    }
```
</blockquote></details>

ah, my bad. How about this?
```
-    if (retval > 0) {
-        retval = sgx_copy_to_enclave(cpu_mask, cpumask_size, untrusted_cpu_mask, retval);
-    }
+    if (retval > 0 && !sgx_copy_to_enclave(cpu_mask, cpumask_size, untrusted_cpu_mask, retval))
+        retval = -EPERM;

-    if (!is_cpumask_valid(cpu_mask, cpumask_size))
+    if (retval > 0 && !is_cpumask_valid(cpu_mask, cpumask_size))
         retval = -EPERM;

     sgx_reset_ustack(old_ustack);
```


<!-- Sent from Reviewable.io -->

2020-10-29 17:39 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKpR2pN-Tr2ZcQkrSBj:b-7y31ou) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

By `len` I meant the length of `cpumask_size`.
I think it will be better if we can clarify `It is not allowed for \a cpumask_size to fit more CPUs than available on the host`.

How about this?
```
 * This function assumes that \a cpumask_size is valid and non-negative. Also, if \a cpumask_size is
 * larger than the number of processors in the host, it must be truncated such that it can fit all
 * the processors in the host <b>and<\b> is aligned by sizeof(long). For example, if the host
 * supports 4 CPUs, \a cpumask_size can be 8 bytes or less (but not more than 8 bytes).
 * \note \a cpumask_size that cannot fit all the processors in the host or not aligned by
 * sizeof(long) are considered valid but only the CPUs fitting \a cpumask_size will be set.

```

</blockquote></details>


in the last line changed `are considered -> is considered`
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKpRCyJ7RdDb1FaVI6Z:b-7y31ou) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

By `len` I meant the length of `cpumask_size`.
`It is not allowed for \a cpumask_size to fit less or more CPUs...`. This statement to me looks to imply that the cpumask_size should be 4 bits which is not the case.

How about this?
```
 * This function assumes that \a cpumask_size is valid and greater than 0. Also, \a cpumask_size
 * must be able to fit all the processors in the host <b>and</b> must be aligned by sizeof(long).
 * For example, if the host supports 4 CPUs, \a cpumask_size should be 8 bytes.
 * \note \a cpumask_size that cannot fit all the processors in the host or is not aligned by
 * sizeof(long) are considered invalid.
```

</blockquote></details>


in the last line changed `are considered -> is considered`


<!-- Sent from Reviewable.io -->

2020-10-29 21:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKqHwOL-r9TyET88Bes:b7na3mn) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

in the last line changed `are considered -> is considered`
</blockquote></details>

Yes, the change looks fine to me. Though I would remove `<b>` and `<\b>`, hard to read in the source code. Maybe replace with `... <b>and<\b> is aligned ...` -> `... and must be aligned ...`
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKqIX-i1LtYIRyudj3F:b-sgbze8) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

in the last line changed `are considered -> is considered`
</blockquote></details>

Yes, sounds good to me. But see my comment about `<b>`.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1538 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnlGRd-Rt6I8xTliV-:-MKqIjgF2EEK__D4X6Wh:b927sc) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1538)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ah, my bad. How about this?
```
-    if (retval > 0) {
-        retval = sgx_copy_to_enclave(cpu_mask, cpumask_size, untrusted_cpu_mask, retval);
-    }
+    if (retval > 0 && !sgx_copy_to_enclave(cpu_mask, cpumask_size, untrusted_cpu_mask, retval))
+        retval = -EPERM;

-    if (!is_cpumask_valid(cpu_mask, cpumask_size))
+    if (retval > 0 && !is_cpumask_valid(cpu_mask, cpumask_size))
         retval = -EPERM;

     sgx_reset_ustack(old_ustack);
```
</blockquote></details>

Yes, your change looks good.


<!-- Sent from Reviewable.io -->

2020-10-29 23:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKqespzAA8Lrnsod1n5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, the change looks fine to me. Though I would remove `<b>` and `<\b>`, hard to read in the source code. Maybe replace with `... <b>and<\b> is aligned ...` -> `... and must be aligned ...`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 528 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnfv0P1b-tJG1bCm7i:-MKqf4Ec0NoQpGNExqL1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L528)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just realized: please change `actual linux error code` -> `actual error code`. There are no "Linux" codes that PAL functions return, they always return PAL-specific error codes.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKqeu2zA_1Ffxji2Xrf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, sounds good to me. But see my comment about `<b>`.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 545 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKng7A4-RikazGFz4pB:-MKqf5DL-LR91_FE44jR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L545)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just realized: please change `actual linux error code` -> `actual error code`. There are no "Linux" codes that PAL functions return, they always return PAL-specific error codes.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1538 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnlGRd-Rt6I8xTliV-:-MKqeyu9CFFOQr59_MhS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1538)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, your change looks good.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-30 01:55 UTC, mkow requested changes
> Reviewed 3 of 5 files at r15, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 47 at r13](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKa58-z7TWfAv-YXfWh:-MKr6oGj3Nu158WB3VO5:bm6q3hx) ([raw file](https://github.com/oscarlab/graphene/blob/29fd7fa122271e25f61188c15ecee86506f94c14/LibOS/shim/test/regression/pthread_set_get_affinity.c#L47)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ditto. But I have removed this comment. It is explicit from the code :)
</blockquote></details>

+1 to removing it :)
___
*[Pal/include/lib/api.h, line 72 at r16](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKrC7jM5j_BMWp55mAC:-MKrC7jM5j_BMWp55mAD:b1nkli8) ([raw file](https://github.com/oscarlab/graphene/blob/9c223065ae918b590e317904e35c27bed7033998/Pal/include/lib/api.h#L72)):*
> ```objc
> #define BITS_IN_TYPE(type)              (sizeof(type) * BITS_IN_BYTE)
> #define BITS_TO_LONGS(nr)               DIV_ROUND_UP(nr, BITS_IN_TYPE(long))
> #define SET_HIGHEST_N_BITS(type, nbits) (~(((uint64_t)1 << (BITS_IN_TYPE(type) - (nbits))) - 1))
> ```

Could you add a comment here documenting that this macro doesn't work with `nbits == BITS_IN_TYPE(type)`?
___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKr9xXM2VW9XgqL4205:b3zxqvh) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
> cpumask_size is valid and non-negative

It's unsigned, it can't be negative ;)

> cpumask_size [..] not aligned by sizeof(long) is considered valid but only the CPUs fitting \a cpumask_size will be set.

Hmm, is this actually true? Won't it fail in this case? (it will proxy the mask to the host kernel and fail there, I think, at least in non-SGX version)
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKrB4KD55Qbz_Gnfe9y:b-4dnhp1) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Isn't this `/note` just a 1-1 repetition of the previous sentence?


<!-- Sent from Reviewable.io -->

2020-10-30 06:16 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/lib/api.h, line 72 at r16](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKrC7jM5j_BMWp55mAC:-MKrwcwBB9zJ44CmWpy0:b-1eh3wi) ([raw file](https://github.com/oscarlab/graphene/blob/9c223065ae918b590e317904e35c27bed7033998/Pal/include/lib/api.h#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a comment here documenting that this macro doesn't work with `nbits == BITS_IN_TYPE(type)`?
</blockquote></details>

Sure, done.
___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKrzVCyCFYUG06qIyit:b-c5lo99) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> cpumask_size is valid and non-negative

It's unsigned, it can't be negative ;)

> cpumask_size [..] not aligned by sizeof(long) is considered valid but only the CPUs fitting \a cpumask_size will be set.

Hmm, is this actually true? Won't it fail in this case? (it will proxy the mask to the host kernel and fail there, I think, at least in non-SGX version)
</blockquote></details>

yeah, you are right it can't be negative :) I wrote it thinking that any value 0 or greater is valid but found out that `cpumask_size` cannot be 0 as the host kernel will fail with `EINVAL`. This is neither mentioned in Linux man-pages nor the kernel code has any explicit check when `cpumask_size` (length) is passed as 0.

I have corrected the text to say "greater than 0".

Regarding the `not aligned by sizeof(long)` this is a valid case. I did do a quick test where I set `cpumask_size` to 2 bytes but the host kernel didn't throw any error.
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKs5bXT5qChcGREM3PI:b-kcjt5l) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this `/note` just a 1-1 repetition of the previous sentence?
</blockquote></details>

The note is trying to capture the intended result (in this case invalid parameter) when `cpumask_size` is less than the number of processors or not aligned by `sizeof(long)`. But to make this connection, I did repeat the earlier statement :) 


<!-- Sent from Reviewable.io -->

2020-10-30 09:54 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r16, 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKsv0ws06DchsD0kHqv:b-6m99ir) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The note is trying to capture the intended result (in this case invalid parameter) when `cpumask_size` is less than the number of processors or not aligned by `sizeof(long)`. But to make this connection, I did repeat the earlier statement :) 
</blockquote></details>

I'm fine with statement, it makes it more explicit.


<!-- Sent from Reviewable.io -->

2020-10-31 02:07 UTC, mkow requested changes
> Reviewed 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKwNgZ8-eczA9jbA76b:b-nioi0f) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
> Regarding the `not aligned by sizeof(long)` this is a valid case. I did do a quick test where I set `cpumask_size` to 2 bytes but the host kernel didn't throw any error.

Have you tried this on both Linux and Linux-SGX? If I see correctly, in non-SGX case the pointer and size is just forwarded to the PAL, which will issue the host syscall with it and fail, no? If it actually works, then why? Is something in the way expanding/moving the array?
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKwOd0v-_015roF6hVd:b7rl0qk) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with statement, it makes it more explicit.
</blockquote></details>

But this is just:

```
A must hold.
\note not(A) must not hold.
```

Am I missing something? What's the point of writing the same sentence twice?


<!-- Sent from Reviewable.io -->

2020-10-31 06:08 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MKx8cBU44a1IO40iLsb:b-arynaf) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Regarding the `not aligned by sizeof(long)` this is a valid case. I did do a quick test where I set `cpumask_size` to 2 bytes but the host kernel didn't throw any error.

Have you tried this on both Linux and Linux-SGX? If I see correctly, in non-SGX case the pointer and size is just forwarded to the PAL, which will issue the host syscall with it and fail, no? If it actually works, then why? Is something in the way expanding/moving the array?
</blockquote></details>

correct, the kernel allocates its own internal buffer something like `kmalloc_node(cpumask_size(), flags, node)` where `cpumask_size()` is `BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long)`and copies `len` bytes from the user buffer where `len` is the number of bytes passed by the user.

Yes, I did try both Linux and Linux-SGX and they do work.
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-MKxBysbDTsi7ITNBtRV:brsmu3f) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this is just:

```
A must hold.
\note not(A) must not hold.
```

Am I missing something? What's the point of writing the same sentence twice?
</blockquote></details>

```
A must hold.
\note  not (A) must not hold, `cpusize_mask` parameter is invalid. Implementers should treat this as an error.
```

I was trying to be more explicit as to how other PAL implementers should handle the negative case.


<!-- Sent from Reviewable.io -->

2020-11-01 17:26 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-ML3oqpj-0R2FkOHGUBj:b-c6vqiz) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

correct, the kernel allocates its own internal buffer something like `kmalloc_node(cpumask_size(), flags, node)` where `cpumask_size()` is `BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long)`and copies `len` bytes from the user buffer where `len` is the number of bytes passed by the user.

Yes, I did try both Linux and Linux-SGX and they do work.
</blockquote></details>

So, if non-aligned sizes and pointers work with `sched_setaffinity` which we currently use to implement `DkThreadSetCpuAffinity`, then why we require it in this API? ("must be aligned by sizeof(long)")
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-ML3pKDR3b0_hpFrU_p1:b2i0yag) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

```
A must hold.
\note  not (A) must not hold, `cpusize_mask` parameter is invalid. Implementers should treat this as an error.
```

I was trying to be more explicit as to how other PAL implementers should handle the negative case.
</blockquote></details>

But the first sentence already describes _exactly_ this. I don't see any added information in that note.
Documentation should be concise and precise.


<!-- Sent from Reviewable.io -->

2020-11-01 21:04 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-ML4XvKHCgAYH1QlkRCA:b-tfuj6d) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, if non-aligned sizes and pointers work with `sched_setaffinity` which we currently use to implement `DkThreadSetCpuAffinity`, then why we require it in this API? ("must be aligned by sizeof(long)")
</blockquote></details>

`aligned by sizeof(long)` is only done when `cpumask_size` is larger than the number of processors in the host. Even linux kernel does the same and so wanted to capture this.

Please see the below snippet where when `len` is greater than `cpumask_size()` it is aligned by ` sizeof(long)`.
```
static int get_user_cpu_mask(unsigned long __user *user_mask_ptr, unsigned len,
			     struct cpumask *new_mask)
{
	if (len < cpumask_size())
		cpumask_clear(new_mask);
	else if (len > cpumask_size())
		**len = cpumask_size();**

	return copy_from_user(new_mask, user_mask_ptr, len) ? -EFAULT : 0;
}
```
PS: `cpumask_size() is BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long)`
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-ML4aHuV7R1YbqgT0AJq:b-cx5mi2) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But the first sentence already describes _exactly_ this. I don't see any added information in that note.
Documentation should be concise and precise.
</blockquote></details>

@mkow are you suggesting we remove the note? or do you want me to reword? The idea is just to make things as clear as possible to other PAL implementers. But if things are clear, I am fine removing any additional text.
Adding others to have a common consensus @dimakuv  @yamahata. 


<!-- Sent from Reviewable.io -->

2020-11-02 00:19 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-ML5HgBDEnJjJZPZMi3h:bs4m43o) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
> `aligned by sizeof(long)` is only done when `cpumask_size` is larger than the number of processors in the host. Even linux kernel does the same and so wanted to capture this.

I just tested it and `sched_setaffinity` succeeds with large but unaligned sizes: https://godbolt.org/z/bWob8o.
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-ML5JCMwCjFZL4pOEaZx:b-u70qxd) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
> The idea is just to make things as clear as possible to other PAL implementers

Pasting the same sentence twice doesn't make anything more clear, just more lengthy and time-consuming to read. As I said, maybe I'm missing something and this second sentence actually provides new information, if so, then please say where is it :)


<!-- Sent from Reviewable.io -->

2020-11-02 08:39 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-ML75xt_8qzYSrgp9dRf:bu9hgw0) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> The idea is just to make things as clear as possible to other PAL implementers

Pasting the same sentence twice doesn't make anything more clear, just more lengthy and time-consuming to read. As I said, maybe I'm missing something and this second sentence actually provides new information, if so, then please say where is it :)
</blockquote></details>

Let's just remove this note.


<!-- Sent from Reviewable.io -->

2020-11-02 14:56 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-ML8HG_t491ANBH4V_r6:b-o28aia) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> `aligned by sizeof(long)` is only done when `cpumask_size` is larger than the number of processors in the host. Even linux kernel does the same and so wanted to capture this.

I just tested it and `sched_setaffinity` succeeds with large but unaligned sizes: https://godbolt.org/z/bWob8o.
</blockquote></details>

yes, it is expected since Linux allocates its own internal buffer which is aligned by `sizeof(long)`. The reason it is captured in API description is that, in the case where the buffer is larger than the number of processors in the host and unaligned, Linux overrides the `cpumask_size` which the user had passed by  ` BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long)`. Wanted to capture this for other PAL implementation.

@mkow please suggest how do we want to proceed.
___
*[Pal/include/pal/pal.h, line 539 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKnipKe2LsmSLZSv80Q:-ML8S1_H-0k8sNwt3UeJ:b-kwdr8q) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L539)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's just remove this note.
</blockquote></details>

@dimakuv @mkow sure will remove the note.


<!-- Sent from Reviewable.io -->

2020-11-03 00:24 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MLAMkA29sNvmpj0_UOQ:b-4vs40q) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
One thing from the backlog I just checked: "`cpumask_size` cannot be 0 as the host kernel will fail with EINVAL": it actually returns EPERM then: https://godbolt.org/z/Yjcseb. And it's not about the size, it just always returns EPERM if there are no 0 CPUs selected in the mask (try setting the mask to something longer, but still zeros and you'll see).

> The reason it is captured in API description is that, in the case where the buffer is larger than the number of processors in the host and unaligned, Linux overrides the `cpumask_size` which the user had passed by `BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long)`. Wanted to capture this for other PAL implementation.

Why would it matter for the API specification? This is just an implementation detail which is not detectable from the caller perspective, so other PALs may implement it differently and everything will be fine. Maybe the thing you actually wanted to say here is that all higher bits are ignored? But this has nothing to do with the alignment, anything exceeding the core count is ignored.

> @mkow please suggest how do we want to proceed.

Maybe I'll just propose the whole doc comment:

```C
/*!
 * \brief Sets the CPU affinity of a thread.
 *
 * All bit positions exceeding the count of host CPUs are ignored. Returns an error if no CPUs were
 * selected.
 *
 * \param thread PAL thread for which to set the CPU affinity.
 * \param cpumask_size size in bytes of the bitmask pointed by \a cpu_mask.
 * \param cpu_mask pointer to the new CPU mask.
 *
 * \return Returns 1 on success, 0 on failure. Use PAL_ERRNO() to get the actual error code.
 */
PAL_BOL DkThreadSetCpuAffinity(PAL_HANDLE thread, PAL_NUM cpumask_size, PAL_PTR cpu_mask);
```

This is much shorter, precise and I think it captures all behavior detectable from the caller's perspective.


<!-- Sent from Reviewable.io -->

2020-11-03 01:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MLAf-MP0c4ZKScGZajw:b-ov44zf) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One thing from the backlog I just checked: "`cpumask_size` cannot be 0 as the host kernel will fail with EINVAL": it actually returns EPERM then: https://godbolt.org/z/Yjcseb. And it's not about the size, it just always returns EPERM if there are no 0 CPUs selected in the mask (try setting the mask to something longer, but still zeros and you'll see).

> The reason it is captured in API description is that, in the case where the buffer is larger than the number of processors in the host and unaligned, Linux overrides the `cpumask_size` which the user had passed by `BITS_TO_LONGS(nr_cpumask_bits) * sizeof(long)`. Wanted to capture this for other PAL implementation.

Why would it matter for the API specification? This is just an implementation detail which is not detectable from the caller perspective, so other PALs may implement it differently and everything will be fine. Maybe the thing you actually wanted to say here is that all higher bits are ignored? But this has nothing to do with the alignment, anything exceeding the core count is ignored.

> @mkow please suggest how do we want to proceed.

Maybe I'll just propose the whole doc comment:

```C
/*!
 * \brief Sets the CPU affinity of a thread.
 *
 * All bit positions exceeding the count of host CPUs are ignored. Returns an error if no CPUs were
 * selected.
 *
 * \param thread PAL thread for which to set the CPU affinity.
 * \param cpumask_size size in bytes of the bitmask pointed by \a cpu_mask.
 * \param cpu_mask pointer to the new CPU mask.
 *
 * \return Returns 1 on success, 0 on failure. Use PAL_ERRNO() to get the actual error code.
 */
PAL_BOL DkThreadSetCpuAffinity(PAL_HANDLE thread, PAL_NUM cpumask_size, PAL_PTR cpu_mask);
```

This is much shorter, precise and I think it captures all behavior detectable from the caller's perspective.
</blockquote></details>

Thanks for the write-up. This looks fine to me and will add this.

What about the below check in `DkThreadSetCpuAffinity`? I propose to remove this as well.
 ```
    /* Linux kernel bitmap is based on long. So according to its implementation, round up the result
     * to sizeof(long) */
    size_t bitmask_size_in_bytes = BITS_TO_LONGS(cpu_cnt) * sizeof(long);
    if (cpumask_size > bitmask_size_in_bytes)
        cpumask_size = bitmask_size_in_bytes;
```


<!-- Sent from Reviewable.io -->

2020-11-03 01:31 UTC, vijaydhanraj commented
___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MLAiOtwBJKKDU24ZNMV:b-f2gxqn) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks for the write-up. This looks fine to me and will add this.

What about the below check in `DkThreadSetCpuAffinity`? I propose to remove this as well.
 ```
    /* Linux kernel bitmap is based on long. So according to its implementation, round up the result
     * to sizeof(long) */
    size_t bitmask_size_in_bytes = BITS_TO_LONGS(cpu_cnt) * sizeof(long);
    if (cpumask_size > bitmask_size_in_bytes)
        cpumask_size = bitmask_size_in_bytes;
```

</blockquote></details>

Since this is already taken care by the linux kernel right?


<!-- Sent from Reviewable.io -->

2020-11-03 10:16 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-03 12:28 UTC, mkow requested changes
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MLD3AMu0n_czJ70Lrp8:b-vmhift) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Since this is already taken care by the linux kernel right?
</blockquote></details>

Yes, I think it can be safely removed.
Could you also apply the other small changes from my suggestion? Mostly the removal of "user-space" - this function doesn't have any requirements on this pointer and we don't have a notion of user vs kernel space on the PAL API layer (only on the syscall layer).


<!-- Sent from Reviewable.io -->

2020-11-03 16:34 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 27 of 28 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK4z1pz3GzmD0IRzcjv:-MLDw2hdEZvWPLgqjaCq:b8xooe2) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sure, will fix this before the final PR
</blockquote></details>

@mkow @dimakuv @yamahata if we are ready to merge the PR, shall I squash all fixups and fix the length of topology change commit message?

---
___
*[Pal/include/pal/pal.h, line 522 at r15](https://reviewable.io/reviews/oscarlab/graphene/1866#-MKngF2d9uvxCU2743oY:-MLDviinAkHiXyKPs2cv:b-szhbky) ([raw file](https://github.com/oscarlab/graphene/blob/556a6a5cb28f13acc8a6849d23c9922aa55b048a/Pal/include/pal/pal.h#L522)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, I think it can be safely removed.
Could you also apply the other small changes from my suggestion? Mostly the removal of "user-space" - this function doesn't have any requirements on this pointer and we don't have a notion of user vs kernel space on the PAL API layer (only on the syscall layer).
</blockquote></details>

sure, done.


<!-- Sent from Reviewable.io -->

2020-11-03 16:40 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK4z1pz3GzmD0IRzcjv:-MLDyllH0Qaw9TbHL2U7:b2zdj37) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@mkow @dimakuv @yamahata if we are ready to merge the PR, shall I squash all fixups and fix the length of topology change commit message?
</blockquote></details>

Yes, please do.

---


<!-- Sent from Reviewable.io -->

2020-11-03 17:25 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK4z1pz3GzmD0IRzcjv:-MLE7knnDPrnTA_nnWCl:bpkqspd) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, please do.
</blockquote></details>

Yes, please squash, fix the commit messages, and feel free to rebase to the latest master.

---


<!-- Sent from Reviewable.io -->

2020-11-03 19:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 13 of 28 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MK4z1pz3GzmD0IRzcjv:-MLEXAag0kx4nLhN1RrF:b-1hl0pb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please squash, fix the commit messages, and feel free to rebase to the latest master.
</blockquote></details>

sure, pushed the changes after rebasing to the latest master.

---


<!-- Sent from Reviewable.io -->

2020-11-03 20:30 UTC, mkow approved these changes
> Reviewed 15 of 15 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-04 10:28 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r19, 14 of 15 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 155 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHjA8V1blSmtuTdBnJ:-MLHjA8V1blSmtuTdBnK:bkfkwr8) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/src/sys/shim_sched.c#L155)):*
> ```C
>     } else {
>         thread = get_cur_thread();
>     }
> ```

Just a tiny syntax improvement:
`struct shim_thread* thread = pid ? lookup_thread(pid) : get_cur_thread();`

And please remove `struct shim_thread* thread;` declaration above.
___
*[LibOS/shim/src/sys/shim_sched.c, line 208 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHk0ZH50kxA9_-vzqZ:-MLHk0ZH50kxA9_-vzq_:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/src/sys/shim_sched.c#L208)):*
> ```C
>     } else {
>         thread = get_cur_thread();
>     }
> ```

ditto
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 18 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHkOCLDXkSLsA7--GD:-MLHkOCLDXkSLsA7--GE:bl1tblf) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/test/regression/pthread_set_get_affinity.c#L18)):*
> ```C
> #include <unistd.h>
> 
> /* Set large busy loops so that we can verify affinity with htop manually*/
> ```

Please slightly fix to this: `/* Run a busy loop for some iterations, so that we can verify affinity with htop manually */`
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 86 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHkk7j0bytcQOtWGv7:-MLHkk7j0bytcQOtWGv8:b-j34m9q) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/test/regression/pthread_set_get_affinity.c#L86)):*
> ```C
>         }
>     }
>     /* Validating parent set/get affinity for child done. Free resources */
> ```

Can we add an empty line before this?
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 107 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHko5U0xSd3iQjqpPp:-MLHko5U0xSd3iQjqpPq:b2c0c7d) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/test/regression/pthread_set_get_affinity.c#L107)):*
> ```C
>     }
> 
>     /* Negative test case with empty cpumask*/
> ```

`cpumask*/` -> `cpumask */` (add a space)
___
*[Pal/src/pal_internal.h, line 237 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHlYeI5MUgsJOlTVkN:-MLHlYeI5MUgsJOlTVkO:bks0wnw) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/pal_internal.h#L237)):*
> ```objc
> noreturn void _DkProcessExit(int exitCode);
> int _DkThreadSetCpuAffinity(PAL_HANDLE thread, PAL_NUM cpumask_len, PAL_PTR cpu_mask);
> int _DkThreadGetCpuAffinity(PAL_HANDLE thread, PAL_NUM cpumask_len, PAL_PTR cpu_mask);
> ```

These two functions have `cpumask_len` -> `cpumask_size`
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 113 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHluaqA7YUDtLq0s3_:-MLHluaqA7YUDtLq0s3a:b-g4c5c5) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/host/Linux-SGX/db_threading.c#L113)):*
> ```C
>        its tcs. */
>     while (!__atomic_load_n(&new_thread->thread.tcs, __ATOMIC_ACQUIRE))
>             cpu_pause();
> ```

Indentation is wrong (must be 8 spaces).
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 178 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHmbLs0mj1z8FIZlFY:-MLHmbLs0mj1z8FIZlFZ:b-5bphgs) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/host/Linux-SGX/ocall_types.h#L178)):*
> ```objc
> typedef struct {
>     void* ms_tcs;
>     size_t ms_cpu_mask_size;
> ```

There is a slight mismatch between these names and all other names. Please modify `ms_cpu_mask_size` -> `ms_cpumask_size`
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 184 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHmk9l-IGNefbLaP67:-MLHmk9l-IGNefbLaP68:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/host/Linux-SGX/ocall_types.h#L184)):*
> ```objc
> typedef struct {
>     void* ms_tcs;
>     size_t ms_cpu_mask_size;
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-11-04 12:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_threading.c, line 113 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHluaqA7YUDtLq0s3_:-MLIAjtL2RecZ6_ATBix:b-92igj) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/host/Linux-SGX/db_threading.c#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indentation is wrong (must be 8 spaces).
</blockquote></details>

must be 4 spaces, it's currently 8


<!-- Sent from Reviewable.io -->

2020-11-04 17:59 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_sched.c, line 155 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHjA8V1blSmtuTdBnJ:-MLJOgKY0e-WzhvSDxou:bjejq33) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/src/sys/shim_sched.c#L155)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just a tiny syntax improvement:
`struct shim_thread* thread = pid ? lookup_thread(pid) : get_cur_thread();`

And please remove `struct shim_thread* thread;` declaration above.
</blockquote></details>

This is better, done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 208 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHk0ZH50kxA9_-vzqZ:-MLJOkKK81CimB2-lpGe:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/src/sys/shim_sched.c#L208)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 18 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHkOCLDXkSLsA7--GD:-MLJOt61Bu-kC5S0RGcZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/test/regression/pthread_set_get_affinity.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please slightly fix to this: `/* Run a busy loop for some iterations, so that we can verify affinity with htop manually */`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 86 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHkk7j0bytcQOtWGv7:-MLJOuLfBmbWFSGf_IDV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/test/regression/pthread_set_get_affinity.c#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add an empty line before this?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 107 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHko5U0xSd3iQjqpPp:-MLJOvNfBrZUABmk-DRZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/LibOS/shim/test/regression/pthread_set_get_affinity.c#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`cpumask*/` -> `cpumask */` (add a space)
</blockquote></details>

Done.
___
*[Pal/src/pal_internal.h, line 237 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHlYeI5MUgsJOlTVkN:-MLJP-tjBumtfnx_TctE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/pal_internal.h#L237)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two functions have `cpumask_len` -> `cpumask_size`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_threading.c, line 113 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHluaqA7YUDtLq0s3_:-MLJOYqx8nX1lh2wmf97:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/host/Linux-SGX/db_threading.c#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

must be 4 spaces, it's currently 8
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 178 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHmbLs0mj1z8FIZlFY:-MLJP4T085wvlPXXRsZk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/host/Linux-SGX/ocall_types.h#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is a slight mismatch between these names and all other names. Please modify `ms_cpu_mask_size` -> `ms_cpumask_size`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/ocall_types.h, line 184 at r20](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLHmk9l-IGNefbLaP67:-MLJPMcX0jwh0rBik7T5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8a5de492039335dc3c6bba634fe56ab435866d4/Pal/src/host/Linux-SGX/ocall_types.h#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 18:11 UTC, mkow submitted a review, later dismissed
> Reviewed 7 of 7 files at r21.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-05 04:01 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-05 04:01 UTC, mkow commented
Jenkins, retest this please

2020-11-05 04:07 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 12 files at r11, 3 of 11 files at r12, 1 of 1 files at r19, 11 of 15 files at r20, 7 of 7 files at r21.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 9 unresolved discussions (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-05 07:48 UTC, dimakuv approved these changes
> Reviewed 1 of 15 files at r20, 7 of 7 files at r21.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-05 07:56 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 1 unresolved discussion (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMOcnn3t3abDZM9Xg6:-MLMOcnoCm9tAUn8Ru-L:b-mars5) (no related file):*
All Jenkins pipelines fail on the new LibOS test:
```
pthread_set_get_affinity: pthread_setaffinity_np failed for child!
```

@vijaydhanraj Could you verify your PR on a couple smaller machines? Jenkins machines are typically 2-4 logical cores, maybe this is the difference?

I will check this PR on my local machines now...

---


<!-- Sent from Reviewable.io -->

2020-11-05 10:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMOcnn3t3abDZM9Xg6:-MLMy1j51-IiU4V4hpvp:b-r5njtr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All Jenkins pipelines fail on the new LibOS test:
```
pthread_set_get_affinity: pthread_setaffinity_np failed for child!
```

@vijaydhanraj Could you verify your PR on a couple smaller machines? Jenkins machines are typically 2-4 logical cores, maybe this is the difference?

I will check this PR on my local machines now...
</blockquote></details>

@vijaydhanraj Yes, there is a bug in the code of `pthread_set_get_affinity`:
```
# even on native, there is a non-deterministic bug with 1000 iterations!
$ ./pthread_set_get_affinity 1000
pthread_set_get_affinity: get cpuset is not equal to set cpuset on proc: 3
```

This is because the child thread is so fast that it dies before the parent actually sets its affinity. See my embedded comments below.

---
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMyLrB-qtTV56tqupj:-MLMyLrB-qtTV56tqupk:bp6aaaa) ([raw file](https://github.com/oscarlab/graphene/blob/7ef85f072f224348cb9b3b5fa2af6210b130fc0e/LibOS/shim/test/regression/pthread_set_get_affinity.c#L61)):*
> ```C
>         }
> 
>         ret = pthread_setaffinity_np(threads[i], sizeof(cpus), &cpus);
> ```

At this point, the child thread was already created, started running `dowork()` and possibly **even finished** (if say `iterations == 1000`).

So this `pthread_setaffinity_np()` invocation fails because there is no thread `threads[i]` found.

Three solutions:
1. Make each child thread wait until main thread sets its affinity. Too complicated, let's not do it.
2. Add to each child's `dowork()` the invocation of `pthread_setaffinity_np()` and `pthread_getaffinity_np()`. But this is also complicated and not interesting.
3. Use `pthread_attr_setaffinity_np()` instead. I think you even had this version before, but for some reason changed it. I suggest to use this option.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 67 at r22](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMzoZ7BmTHBBkF6AaD:-MLMzoZ8BiyUE2wJGzQX:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7ef85f072f224348cb9b3b5fa2af6210b130fc0e/LibOS/shim/test/regression/pthread_set_get_affinity.c#L67)):*
> ```C
>         }
> 
>         ret = pthread_getaffinity_np(threads[i], sizeof(get_cpus), &get_cpus);
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-11-05 15:45 UTC, vijaydhanraj commented
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMyLrB-qtTV56tqupj:-MLO2sKU3IM3HjPsxM6f:b-98odf6) ([raw file](https://github.com/oscarlab/graphene/blob/7ef85f072f224348cb9b3b5fa2af6210b130fc0e/LibOS/shim/test/regression/pthread_set_get_affinity.c#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

At this point, the child thread was already created, started running `dowork()` and possibly **even finished** (if say `iterations == 1000`).

So this `pthread_setaffinity_np()` invocation fails because there is no thread `threads[i]` found.

Three solutions:
1. Make each child thread wait until main thread sets its affinity. Too complicated, let's not do it.
2. Add to each child's `dowork()` the invocation of `pthread_setaffinity_np()` and `pthread_getaffinity_np()`. But this is also complicated and not interesting.
3. Use `pthread_attr_setaffinity_np()` instead. I think you even had this version before, but for some reason changed it. I suggest to use this option.
</blockquote></details>

@dimakuv thanks a lot for checking on this. The reason we changed from `pthread_attr_set/getaffinity_np` to `pthread_set/getaffinity_np` was because @yamahata had pointed out that "pthread_attr_set/getaffinity_np() only stores the parameter into the variable. And pthread_create() issues sched_setattr(). So I'd like to see sched_getattr() exercised by pthread_getaffinity_np()." 

I think this is valid. So if the issue is that `dowork` thread completes much faster than set/get affinity, can we increase the timeout value to say 1000000?
Unfortunately, I couldn't see this issue on a 4 physical core NUC (no HT support) as well on a 128 logical core ICX system.


<!-- Sent from Reviewable.io -->

2020-11-05 16:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions (waiting on @vijaydhanraj and @yamahata)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMyLrB-qtTV56tqupj:-MLOHNip6ITiNw7A_9kt:b-dueixc) ([raw file](https://github.com/oscarlab/graphene/blob/7ef85f072f224348cb9b3b5fa2af6210b130fc0e/LibOS/shim/test/regression/pthread_set_get_affinity.c#L61)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv thanks a lot for checking on this. The reason we changed from `pthread_attr_set/getaffinity_np` to `pthread_set/getaffinity_np` was because @yamahata had pointed out that "pthread_attr_set/getaffinity_np() only stores the parameter into the variable. And pthread_create() issues sched_setattr(). So I'd like to see sched_getattr() exercised by pthread_getaffinity_np()." 

I think this is valid. So if the issue is that `dowork` thread completes much faster than set/get affinity, can we increase the timeout value to say 1000000?
Unfortunately, I couldn't see this issue on a 4 physical core NUC (no HT support) as well on a 128 logical core ICX system.
</blockquote></details>

Please add a proper synchronization, otherwise we'll either sleep exceedingly long (which will slow down testing) or have spurious failures.
A sending one byte over a pipe should be enough (or anything equivalent).


<!-- Sent from Reviewable.io -->

2020-11-05 20:25 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 3 unresolved discussions (waiting on @vijaydhanraj and @yamahata)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMyLrB-qtTV56tqupj:-MLP4IWF6Jf100jvWKxy:b-f4d52r) ([raw file](https://github.com/oscarlab/graphene/blob/7ef85f072f224348cb9b3b5fa2af6210b130fc0e/LibOS/shim/test/regression/pthread_set_get_affinity.c#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a proper synchronization, otherwise we'll either sleep exceedingly long (which will slow down testing) or have spurious failures.
A sending one byte over a pipe should be enough (or anything equivalent).
</blockquote></details>

Yes, please use proper synchronization (my option 1). You can check other LibOS regression tests how to do it (I think pipe tests do this a lot).


<!-- Sent from Reviewable.io -->

2020-11-05 21:03 UTC, vijaydhanraj commented
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMyLrB-qtTV56tqupj:-MLPCkOK9Dff8VkGhvbw:bxeok27) ([raw file](https://github.com/oscarlab/graphene/blob/7ef85f072f224348cb9b3b5fa2af6210b130fc0e/LibOS/shim/test/regression/pthread_set_get_affinity.c#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please use proper synchronization (my option 1). You can check other LibOS regression tests how to do it (I think pipe tests do this a lot).
</blockquote></details>

sure @mkow @dimakuv. I have implemented synchronization using pthread_barrier and it does seem to work fine on my NUC with 4 physical cores (no HT support). Can we please restart the Jenkins test to verify it if resolves the issues?


<!-- Sent from Reviewable.io -->

2020-11-05 21:05 UTC, mkow commented
Jenkins, retest this please

2020-11-05 21:08 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: 27 of 28 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLMyLrB-qtTV56tqupj:-MLPEHZj1vD05w5fKh33:b-4rjusx) ([raw file](https://github.com/oscarlab/graphene/blob/7ef85f072f224348cb9b3b5fa2af6210b130fc0e/LibOS/shim/test/regression/pthread_set_get_affinity.c#L61)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

sure @mkow @dimakuv. I have implemented synchronization using pthread_barrier and it does seem to work fine on my NUC with 4 physical cores (no HT support). Can we please restart the Jenkins test to verify it if resolves the issues?
</blockquote></details>

Done, let's see.


<!-- Sent from Reviewable.io -->

2020-11-06 06:06 UTC, dimakuv commented
Jenkins, retest Jenkins please (`clone03` LTP test failed, known and unrelated)

2020-11-06 06:12 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r23.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLRA3xo5OK113B9NYzf:-MLRA3xp2-C7xdiRj47P:b-pttqrj) (no related file):*
We're almost there! Jenkins-SGX pipelines failed now with this:
```
db_threading.c: In function '_DkThreadCreate':
db_threading.c:113:9: error: implicit declaration of function 'cpu_pause' [-Werror=implicit-function-declaration]
         cpu_pause();
         ^
Makefile:107: recipe for target 'db_threading.o' failed
make[2]: Leaving directory '/home/jenkins/workspace/graphene-sgx/Pal/src'
```

I assume this is because Jenkins merged your PR with the current master automatically. And in the current master, `cpu_pause()` was removed (see Borys's PR that we merged in the mean time: https://github.com/oscarlab/graphene/pull/1938/files#diff-2d6129dc96ae0e45742c3426e9984d025fba9dd04a3e81b0ded6f9da34d36a20L8).

@vijaydhanraj I suggest to do a rebase on the latest master and replace `cpu_pause()` usage from your PR with `CPU_RELAX()`.

---


<!-- Sent from Reviewable.io -->

2020-11-06 07:12 UTC, vijaydhanraj commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLRA3xo5OK113B9NYzf:-MLROPkREpSg3FOdclsd:bl6yiec) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We're almost there! Jenkins-SGX pipelines failed now with this:
```
db_threading.c: In function '_DkThreadCreate':
db_threading.c:113:9: error: implicit declaration of function 'cpu_pause' [-Werror=implicit-function-declaration]
         cpu_pause();
         ^
Makefile:107: recipe for target 'db_threading.o' failed
make[2]: Leaving directory '/home/jenkins/workspace/graphene-sgx/Pal/src'
```

I assume this is because Jenkins merged your PR with the current master automatically. And in the current master, `cpu_pause()` was removed (see Borys's PR that we merged in the mean time: https://github.com/oscarlab/graphene/pull/1938/files#diff-2d6129dc96ae0e45742c3426e9984d025fba9dd04a3e81b0ded6f9da34d36a20L8).

@vijaydhanraj I suggest to do a rebase on the latest master and replace `cpu_pause()` usage from your PR with `CPU_RELAX()`.
</blockquote></details>

@dimakuv sure, I have rebased to the latest master and updated the PR.

---


<!-- Sent from Reviewable.io -->

2020-11-06 12:09 UTC, mkow commented
Jenkins, retest this please

2020-11-06 12:19 UTC, mkow requested changes
> Reviewed 1 of 1 files at r23, 8 of 8 files at r24.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 18 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSSjmCCplIyfHSej-W:-MLSSjmCCplIyfHSej-X:bbv1ulh) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L18)):*
> ```C
> #include <unistd.h>
> 
> /* barrier to synchronize between parent and child */
> ```

child -> children
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 30 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSUHrWDfkkFNY-JOIO:-MLSUHrWDfkkFNY-JOIP:be1m40i) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L30)):*
> ```C
>                       "cmp $0, %%rax\n"
>                       "jne loop\n"
>                       : /*no outs*/ : "m"(*iterations)  : "rax", "cc");
> ```

Now that we have proper synchronization, maybe we could move this loop to the parent and simplify the code? No need to pass the argument and to burn CPU in each of the threads.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSSzSU89gZ2VRszqSr:-MLSSzSV9DTz2azG4eLE:b-pii1la) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
> ```C
>     int ret = pthread_barrier_wait(&barrier);
>     if (ret != 0 && ret != PTHREAD_BARRIER_SERIAL_THREAD)
>         printf("Child did not wait on barrier!\n");
> ```

Please fail the whole test in this case (just `exit` here with nonzero code after the print) - right now the test will just print this warning, which will be ignored.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 92 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSU-ee3ZKeakv5Ja0r:-MLSU-ee3ZKeakv5Ja0s:b-6i63ht) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L92)):*
> ```C
> 
>     /* unblock the child threads */
>      ret = pthread_barrier_wait(&barrier);
> ```

huh, this whole block is indented with 5 spaces ;)


<!-- Sent from Reviewable.io -->

2020-11-06 17:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 18 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSSjmCCplIyfHSej-W:-MLTSTIR8mjA_665QBBz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

child -> children
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 30 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSUHrWDfkkFNY-JOIO:-MLTSf7C--J7xQccmdM3:b-r4rght) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now that we have proper synchronization, maybe we could move this loop to the parent and simplify the code? No need to pass the argument and to burn CPU in each of the threads.
</blockquote></details>

@mkow as discussed, the reason for the loop was not for synchronization but to explicitly show the intended behavior like showing thread <-> cpu affinity.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSSzSU89gZ2VRszqSr:-MLTSxWC1uqD0uiGJImq:bhlnuz4) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fail the whole test in this case (just `exit` here with nonzero code after the print) - right now the test will just print this warning, which will be ignored.
</blockquote></details>

yes, my intention was to just have this print as a warning and catch the failure when checking set vs get affinity. This way we could also free up `threads` resource. But have changed to exit on failure from the child thread as there can be a possibility of indefinite hang if set vs get affinity check didn't fail.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 92 at r24](https://reviewable.io/reviews/oscarlab/graphene/1866#-MLSU-ee3ZKeakv5Ja0r:-MLTUMC46okkdjolBVfa:bqh6yxn) ([raw file](https://github.com/oscarlab/graphene/blob/89f909f40791eb21800b6f2d2510bed7af2191fa/LibOS/shim/test/regression/pthread_set_get_affinity.c#L92)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

huh, this whole block is indented with 5 spaces ;)
</blockquote></details>

oops, fixed it.


<!-- Sent from Reviewable.io -->

2020-11-06 17:23 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r25.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-06 17:24 UTC, mkow commented
Jenkins, retest this please

2020-11-06 20:35 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r26.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-06 20:35 UTC, mkow commented
Jenkins, retest this please

2020-11-06 20:37 UTC, dimakuv approved these changes
> Reviewed 8 of 8 files at r24, 2 of 2 files at r26.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-06 21:36 UTC, mkow commented
Jenkins, retest this please

2020-11-06 21:37 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-06 23:27 UTC, yamahata approved these changes
> Reviewed 8 of 8 files at r24, 2 of 2 files at r26.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1866)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-06 23:28 UTC, merged