[Docs] Clarify build requirements
oscarlab/graphene pull request #1867
Opened 2020-10-02 12:32 UTC by donporter

## Description of the changes 

In trying to build the html docs on my system, I ran into several issues following the current docs.  A lot boiled down to (a) that python2 just doesn't work and I had some conflicting packages installed (b) sphinx needs to be 1.8 or higher, and (c) I needed to install sphinx_rtd_theme.

I updated the instructions to be more clear about this, and added sphinx_rtd_theme to requirements.txt.

## How to test this PR? 

Documentation only.

2020-10-02 12:34 UTC, woju requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter)

___
*[Documentation/devel/howto-doc.rst, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdIOns2oZT5lmIwnph:-MIdIOnuAHRXkquzGgrp:b3kre) ([raw file](https://github.com/oscarlab/graphene/blob/f8426ce78e6fe285827c48f53fda6387647e109a/Documentation/devel/howto-doc.rst#L2)):*
> ```reStructuredText
> .. _howto-doc:
> n
> ```

?
___
*[Documentation/devel/howto-doc.rst, line 47 at r1](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdIShy4kEZmQXlrMIP:-MIdIShy4kEZmQXlrMIQ:bc7ei6h) ([raw file](https://github.com/oscarlab/graphene/blob/f8426ce78e6fe285827c48f53fda6387647e109a/Documentation/devel/howto-doc.rst#L47)):*
> ```reStructuredText
> ``make``, specifying the appropriate target. The documentation is built with python3; if you have
> similar packages in python2, it may create problems; we recommend removing any similar packages in
> python2.  Similarly, we recommend version 1.8 or higher of sphinx.
> ```

no, sphinx==1.8, later versions are incompatible
___
*[Documentation/devel/howto-doc.rst, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdIX9GC5rStcC5ywyw:-MIdIX9HEkyeSnLX50Yg:b1qz2fc) ([raw file](https://github.com/oscarlab/graphene/blob/f8426ce78e6fe285827c48f53fda6387647e109a/Documentation/devel/howto-doc.rst#L58)):*
> ```reStructuredText
>    # install prerequisites
>    sudo apt-get install doxygen
>    pip3 install -r requirements.txt
> ```

according to latest trends, this should be `python3 -m pip install ...`


<!-- Sent from Reviewable.io -->

2020-10-02 12:38 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @woju)

___
*[Documentation/devel/howto-doc.rst, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdIOns2oZT5lmIwnph:-MIdJ8w06Jr7zjje1pId:bwlfk6u) ([raw file](https://github.com/oscarlab/graphene/blob/f8426ce78e6fe285827c48f53fda6387647e109a/Documentation/devel/howto-doc.rst#L2)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

My bad
___
*[Documentation/devel/howto-doc.rst, line 47 at r1](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdIShy4kEZmQXlrMIP:-MIdJNba71j3P7RBzYFE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f8426ce78e6fe285827c48f53fda6387647e109a/Documentation/devel/howto-doc.rst#L47)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

no, sphinx==1.8, later versions are incompatible
</blockquote></details>

Done.
___
*[Documentation/devel/howto-doc.rst, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdIX9GC5rStcC5ywyw:-MIdJNG85JlrVit3di7h:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f8426ce78e6fe285827c48f53fda6387647e109a/Documentation/devel/howto-doc.rst#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

according to latest trends, this should be `python3 -m pip install ...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-02 12:48 UTC, woju approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-02 13:03 UTC, mkow requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @donporter)

___
*[Documentation/devel/howto-doc.rst, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdNrw-3_LyP1Gy65sj:-MIdNrw07yK54Fjg4iXP:btzr0ud) ([raw file](https://github.com/oscarlab/graphene/blob/c22242b38da03035ea9c1f129b37a1549e651ba4/Documentation/devel/howto-doc.rst#L47)):*
> ```reStructuredText
> ``make``, specifying the appropriate target. The documentation is built with python3; if you have
> similar packages in python2, it may create problems; we recommend removing any similar packages in
> python2.  Similarly, the documentation requires version 1.8 of sphinx.
> ```

We don't use double-space-after-period in other places, so I'd remove it from here for consistency (personally I'm neutral on this, but most of our docs don't use it). But if you're a huge fan of this then we can discuss having this as a convention and require in other places.


<!-- Sent from Reviewable.io -->

2020-10-02 14:18 UTC, woju commented
___
*[Documentation/devel/howto-doc.rst, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdNrw-3_LyP1Gy65sj:-MIdfB2l5h42XkFR0ks-:bl388d6) ([raw file](https://github.com/oscarlab/graphene/blob/c22242b38da03035ea9c1f129b37a1549e651ba4/Documentation/devel/howto-doc.rst#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We don't use double-space-after-period in other places, so I'd remove it from here for consistency (personally I'm neutral on this, but most of our docs don't use it). But if you're a huge fan of this then we can discuss having this as a convention and require in other places.
</blockquote></details>

No, browsers won't render this anyway.

https://news.ycombinator.com/item?id=22976614
http://1997.webhistory.org/www.lists/www-talk.1993q3/0029.html


<!-- Sent from Reviewable.io -->

2020-10-02 14:46 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[Documentation/devel/howto-doc.rst, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdNrw-3_LyP1Gy65sj:-MIdkUSl5NE-P3cwPXd3:bop86qm) ([raw file](https://github.com/oscarlab/graphene/blob/c22242b38da03035ea9c1f129b37a1549e651ba4/Documentation/devel/howto-doc.rst#L47)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, browsers won't render this anyway.

https://news.ycombinator.com/item?id=22976614
http://1997.webhistory.org/www.lists/www-talk.1993q3/0029.html
</blockquote></details>

I know, this is a purely source-level convention in this case. The question is whether we want to use it for docs sources / comments in the code.


<!-- Sent from Reviewable.io -->

2020-10-05 08:00 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[Documentation/devel/howto-doc.rst, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdNrw-3_LyP1Gy65sj:-MIrl5GKCGvhaaZIkoUC:b-y0mzix) ([raw file](https://github.com/oscarlab/graphene/blob/c22242b38da03035ea9c1f129b37a1549e651ba4/Documentation/devel/howto-doc.rst#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know, this is a purely source-level convention in this case. The question is whether we want to use it for docs sources / comments in the code.
</blockquote></details>

I'd prefer to remove these double spaces. I think people use it for Latex (there is some Latex trick enabled by this), but it's a bit of a distraction while reading.


<!-- Sent from Reviewable.io -->

2020-10-05 14:37 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/devel/howto-doc.rst, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdNrw-3_LyP1Gy65sj:-MItB8zsCD3lCmBFJJTo:b-av1cib) ([raw file](https://github.com/oscarlab/graphene/blob/c22242b38da03035ea9c1f129b37a1549e651ba4/Documentation/devel/howto-doc.rst#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer to remove these double spaces. I think people use it for Latex (there is some Latex trick enabled by this), but it's a bit of a distraction while reading.
</blockquote></details>

Removed. 

Double spacing after periods is going to be a hard habit for me to break, especially when most typesetting tools change the appearance to match an expected style automatically.


<!-- Sent from Reviewable.io -->

2020-10-05 15:12 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-05 15:21 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/howto-doc.rst, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/1867#-MIdNrw-3_LyP1Gy65sj:-MItKI308-QDcfeMbQnR:bktfs8b) ([raw file](https://github.com/oscarlab/graphene/blob/c22242b38da03035ea9c1f129b37a1549e651ba4/Documentation/devel/howto-doc.rst#L47)):*
> there is some Latex trick enabled by this

No, it's the other way around: in DVI/PDF you get 1.5-wide space after each dot every time you forget to escape this, like Dr.\ John Doe always does.


<!-- Sent from Reviewable.io -->

2020-10-05 22:17 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-05 22:28 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-05 22:30 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1867)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-05 23:38 UTC, merged