Fix stack walking in Linux-SGX + add test for GDB
oscarlab/graphene pull request #1868
Opened 2020-10-02 14:37 UTC by pwmarcz

This is based on https://github.com/oscarlab/graphene/pull/1864, so I'm marking it as draft until the other PR is merged.

SGX backtraces should now work, i.e. it's possible to break in an ocall, and see the backtrace up to the code inside enclave. Unfortunately, the backtrace doesn't go any further (to program startup outside the enclave).

There is also a simple regression test for GDB that checks if:
* breakpoints work (which should catch problems with symbol loading),
* backtraces look sane (`_start`, no `??`).

## How to test this PR? 

See https://github.com/oscarlab/graphene/pull/1864 but should work also in Linux-SGX.

2020-10-05 14:05 UTC, pwmarcz commented
Jenkins, retest this please

2020-10-05 19:03 UTC, dimakuv commented
@pwmarcz #1864 was merged and also Jenkins seems to pass, could you rebase this PR to the current master?

2020-10-05 19:30 UTC, pwmarcz commented
@dimakuv Done, thanks for letting me know.

2020-10-05 20:11 UTC, pwmarcz commented
Still randomly fails with:

```
During startup program exited with code 127.
```

Any ideas? I haven't been able to reproduce it locally so far.

2020-10-05 21:04 UTC, mkow requested changes
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/test/regression/debug.c, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuPqxt6lXiqnfCQ4mv:-MIuPqxu7JMpDiye_jH2:bex5dmh) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/LibOS/shim/test/regression/debug.c#L3)):*
> ```C
> #include <stdio.h>
> 
> __attribute((noinline)) static void func() {
> ```

`__attribute__` seems to be more common, at least that's what I always find in GCC docs
___
*[LibOS/shim/test/regression/debug.c, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuQ4E1BS-HXhM0r8iw:-MIuQ4E1BS-HXhM0r8ix:bivmq0u) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/LibOS/shim/test/regression/debug.c#L3)):*
> ```C
> #include <stdio.h>
> 
> __attribute((noinline)) static void func() {
> ```

`func()` -> `func(void)`
___
*[LibOS/shim/test/regression/test_libos.py, line 607 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuV7m4A0hmXCmyO7Lf:-MIuV7m4A0hmXCmyO7Lg:b-mp47de) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/LibOS/shim/test/regression/test_libos.py#L607)):*
> ```Python
>         # Print GDB output, for capture by pytest.
>         sys.stdout.write(stdout)
>         sys.stderr.write(stderr)
> ```

Actually, isn't this missing from all other tests? (or rather the test wrapper itself)

We don't get such a nice output (see https://leeroy.cs.unc.edu/job/graphene-debug-18.04/3640/testReport/junit/test_libos/TC_50_GDB/test_000_gdb_backtrace/) in other tests, when they fail we only get a repr() of parts of stderr and stdout in the backtrace.

CC: @woju
___
*[Scripts/Makefile.configs, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuWJnY9wTKcJ3UzEGx:-MIuWJnY9wTKcJ3UzEGy:b-mli2ae) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/Scripts/Makefile.configs#L58)):*
> ```
> ASFLAGS += -gdwarf-2 -g3
> CFLAGS += -DDEBUG
> ASFLAGS += -DDEBUG
> ```

While we're here, isn't this missing `CXXFLAGS += -DDEBUG`?
___
*[Scripts/regression.py, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuXW8145ZqfZdJ6Zcs:-MIuXW8145ZqfZdJ6Zct:bmy2916) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/Scripts/regression.py#L29)):*
> ```Python
>             libpal = os.environ[self.LIBPAL_PATH_ENV]
>         except KeyError:
>             self.fail('environment variable {} unset'.format(self.LIBPAL_PATH_ENV))
> ```

Could you refactor out this pattern into a function? Seems to repeat in most of methods in this class.
___
*[Scripts/regression.py, line 46 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuXzUp7DPSkKnIDo6b:-MIuXzUp7DPSkKnIDo6c:b-1zdesk) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/Scripts/regression.py#L46)):*
> ```Python
>         if HAS_SGX:
>             prefix += ['-x', os.path.join(host_pal_path, 'gdb_integration/graphene_sgx_gdb.py')]
>             env['LD_PRELOAD'] = os.path.join(host_pal_path, 'gdb_integration/sgx_gdb.so')
> ```

I think we should append to `LD_PRELOAD` in case it already exists (AFAIR `LD_PRELOAD` supports multiple entries, separated by a colon)


<!-- Sent from Reviewable.io -->

2020-10-05 21:37 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIugBPl7idbXuTv2ohC:-MIugBPl7idbXuTv2ohD:b-wj3tqa) (no related file):*
> Any ideas? I haven't been able to reproduce it locally so far.

I did 200 runs on 16.04 and 200 on 18.04 without failures. No idea. I'll try running this pipeline a few times on Jenkins and we'll see if this can be reproduced there.

---


<!-- Sent from Reviewable.io -->

2020-10-05 21:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIugBPl7idbXuTv2ohC:-MIugxYB-KVmTfGdVHJ5:b79g253) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Any ideas? I haven't been able to reproduce it locally so far.

I did 200 runs on 16.04 and 200 on 18.04 without failures. No idea. I'll try running this pipeline a few times on Jenkins and we'll see if this can be reproduced there.
</blockquote></details>

For the record, log from the failure:
```
Standard Output

[graphene_gdb.py] Loading /home/jenkins/workspace/graphene-debug-18.04/Runtime/../Pal/src/host/Linux/gdb_integration/graphene.gdb...
Breakpoint 1 at 0x19120: file pal_start-x86_64.S, line 13.
Breakpoint 2 at 0x19180: file clone-x86_64.S, line 86.
Catchpoint 3 (vfork)
Temporary breakpoint 4 (func) pending.

Standard Error

Function "func" not defined.
debug.gdb:26: Error in sourced command file:
During startup program exited with code 127.
```

---


<!-- Sent from Reviewable.io -->

2020-10-05 21:40 UTC, mkow commented
Jenkins, retest Jenkins-Debug-18.04 please

2020-10-05 22:13 UTC, mkow commented
Jenkins, retest Jenkins-Debug-18.04 please (2/5, previous one succeeded)

2020-10-05 22:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIugBPl7idbXuTv2ohC:-MIuvdDj0RGto-DyoGlR:brxl4md) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For the record, log from the failure:
```
Standard Output

[graphene_gdb.py] Loading /home/jenkins/workspace/graphene-debug-18.04/Runtime/../Pal/src/host/Linux/gdb_integration/graphene.gdb...
Breakpoint 1 at 0x19120: file pal_start-x86_64.S, line 13.
Breakpoint 2 at 0x19180: file clone-x86_64.S, line 86.
Catchpoint 3 (vfork)
Temporary breakpoint 4 (func) pending.

Standard Error

Function "func" not defined.
debug.gdb:26: Error in sourced command file:
During startup program exited with code 127.
```
</blockquote></details>

Ok, it seems to reproduce sometimes: first re-run succeeded, but the next one failed with the same error as the first one.

---


<!-- Sent from Reviewable.io -->

2020-10-06 10:01 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIugBPl7idbXuTv2ohC:-MIxIv1b3-L4_1WsYr_G:b-1h15wk) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, it seems to reproduce sometimes: first re-run succeeded, but the next one failed with the same error as the first one.
</blockquote></details>

Okay, looking at last 7 builds or so, this consistently passes on `slave-constantine` and fails on `slave-waldorf` and `slave-pepe`. Do they have differences in configuration? Different kernel, Docker configuration, packages? 

(I'm less worried about inside of Docker because it should be pretty consistent. There is layer caching though).

---


<!-- Sent from Reviewable.io -->

2020-10-06 10:21 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[LibOS/shim/test/regression/debug.c, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuPqxt6lXiqnfCQ4mv:-MIxMAHY44bH2rOuVY7C:bidrs83) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/LibOS/shim/test/regression/debug.c#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`__attribute__` seems to be more common, at least that's what I always find in GCC docs
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/test/regression/debug.c, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuQ4E1BS-HXhM0r8iw:-MIxMDwn5U_4ePg4ArQx:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/LibOS/shim/test/regression/debug.c#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`func()` -> `func(void)`
</blockquote></details>

Fixed.
___
*[LibOS/shim/test/regression/test_libos.py, line 607 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuV7m4A0hmXCmyO7Lf:-MIxNNG4EHrxb9HSADlY:b2dl8z0) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/LibOS/shim/test/regression/test_libos.py#L607)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, isn't this missing from all other tests? (or rather the test wrapper itself)

We don't get such a nice output (see https://leeroy.cs.unc.edu/job/graphene-debug-18.04/3640/testReport/junit/test_libos/TC_50_GDB/test_000_gdb_backtrace/) in other tests, when they fail we only get a repr() of parts of stderr and stdout in the backtrace.

CC: @woju
</blockquote></details>

Good idea, I think it would be very helpful for debugging. Added to the wrapper, let's see Jenkins output, but it should be fine - the XML will just be bigger.
___
*[Scripts/Makefile.configs, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuWJnY9wTKcJ3UzEGx:-MIxP1bu1BWz97rn3BZi:b163nju) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/Scripts/Makefile.configs#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're here, isn't this missing `CXXFLAGS += -DDEBUG`?
</blockquote></details>

Done. We don't have any C++ code except for some regression tests, right?
___
*[Scripts/regression.py, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuXW8145ZqfZdJ6Zcs:-MIxP9Db4XiUP0kOHgPj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/Scripts/regression.py#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you refactor out this pattern into a function? Seems to repeat in most of methods in this class.
</blockquote></details>

Done.
___
*[Scripts/regression.py, line 46 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuXzUp7DPSkKnIDo6b:-MIxPARc7fJV_WCPmxV_:b-9vusw1) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/Scripts/regression.py#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we should append to `LD_PRELOAD` in case it already exists (AFAIR `LD_PRELOAD` supports multiple entries, separated by a colon)
</blockquote></details>

Done. I added our file at the beginning because presumably we want our `ptrace` to shadow any other version. Also added to `pal_loader` for consistency.


<!-- Sent from Reviewable.io -->

2020-10-06 13:06 UTC, mkow reviewed
> Reviewed 6 of 6 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/test_libos.py, line 607 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuV7m4A0hmXCmyO7Lf:-MIxqY2Q-7IT3J0HH4YQ:by2s728) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/LibOS/shim/test/regression/test_libos.py#L607)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Good idea, I think it would be very helpful for debugging. Added to the wrapper, let's see Jenkins output, but it should be fine - the XML will just be bigger.
</blockquote></details>

Looks good now, thanks!
___
*[Scripts/Makefile.configs, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIuWJnY9wTKcJ3UzEGx:-MIxqdyN36k5xEe3QCQd:b-l7byi4) ([raw file](https://github.com/oscarlab/graphene/blob/abe0cdb28ad9a5903648dd6d61862f82829da23f/Scripts/Makefile.configs#L58)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done. We don't have any C++ code except for some regression tests, right?
</blockquote></details>

Only in tests and one SGX tool, that's probably the reason why it wasn't detected earlier.


<!-- Sent from Reviewable.io -->

2020-10-06 14:29 UTC, pwmarcz commented
Jenkins, retest Jenkins-Debug-18.04 please

2020-10-06 17:06 UTC, pwmarcz commented
Okay, I'm out of ideas...
* The test fails on some Jenkins nodes but not all of them; on both Ubuntu 16.04 and 18.04 Docker images
* As far as I know, this is the first time we tried to run GDB on Jenkins nodes (I had to add it to Dockerfile)
* I got shell access to `slave-waldorf` and was able to run GDB manually, and the scenario worked (not inside Docker, though, because I don't have Docker access)
  * specifically, I ran `GDB=1 GDB_SCRIPT=debug.gdb ./pal_loader debug`
* I added some debug prints and GDB fails to even start the program (i.e. `starti` fails), but provides no additional feedback
* No reproduction on any other system (we tried a few)

Should we commit this test as skipped for now, and wait for the new Jenkins server? Note that the SGX variant of the test wouldn't run on current Jenkins anyway, because we don't have a configuration for SGX under debug mode. (CC @woju)

(I guess there is *some* value in a test which is not on CI but which you can quickly run yourself...)

2020-10-07 08:55 UTC, dimakuv approved these changes
I would mark this test as skipped for now. Lately we have many issues with Jenkins...

> Reviewed 6 of 12 files at r1, 2 of 6 files at r3, 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868#-:-MJ1DSWgB1il22niE_Hr:b-x1ojqz)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "WIP" found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-07 09:55 UTC, pwmarcz commented
@dimakuv OK, skipping for now.

2020-10-07 10:50 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 6 files at r3, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-07 12:08 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIugBPl7idbXuTv2ohC:-MJ1x6KZ7l83exBtV39B:b-sf7tb5) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, looking at last 7 builds or so, this consistently passes on `slave-constantine` and fails on `slave-waldorf` and `slave-pepe`. Do they have differences in configuration? Different kernel, Docker configuration, packages? 

(I'm less worried about inside of Docker because it should be pretty consistent. There is layer caching though).
</blockquote></details>

I'm fine with disabling this test in CI for now, as Dima suggested. Could you create an issue about this, so that it's harder to forget about re-enabling it? Please copy everything we know about the failures there.

---


<!-- Sent from Reviewable.io -->

2020-10-07 12:38 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MIugBPl7idbXuTv2ohC:-MJ23Oew615Dc3SQQyM5:b-hb8fn1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with disabling this test in CI for now, as Dima suggested. Could you create an issue about this, so that it's harder to forget about re-enabling it? Please copy everything we know about the failures there.
</blockquote></details>

Ticketed as https://github.com/oscarlab/graphene/issues/1871.

---


<!-- Sent from Reviewable.io -->

2020-10-07 12:43 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-07 15:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MJ2_VVZ3w9sqLsOBZ9t:-MJ2_VV_4GELjnr0Xn9O:b-tjm3ny) (no related file):*
Sounds like we need to block this PR until Pawel checks the SGX debugging again?

---


<!-- Sent from Reviewable.io -->

2020-10-08 16:39 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: 1 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1868#-MJ2_VVZ3w9sqLsOBZ9t:-MJ80AYy5_lROoClwgWG:b-6ea3zv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds like we need to block this PR until Pawel checks the SGX debugging again?
</blockquote></details>

This is now back for review:

* Last-minute change to the previous PR actually broke debug map loading (libpal.so wasn't present). Fixed now, and the test should keep it in place.
* Reenabled the tests as I assume Jenkins is working again. (Note that we still don't have configuration for SGX=1 DEBUG=1, so I'm running that one manually).
* Fixed SGX backtraces across OCALL, added a test for that.
* Fixed a problem with tail calls removing `func` from the backtrace.

Sorry for the last minute fixup, I was relying too much on manual testing.

(Unfortunately that doesn't exhaust all the scenarios, for instance, a break on `sgx_ocall_write` at the enclave startup will still display a broken stack trace. But at least the "regular" ocall scenarios should work, and are tested.)

---


<!-- Sent from Reviewable.io -->

2020-10-09 08:14 UTC, dimakuv submitted a review, later dismissed
> Reviewed 13 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-09 11:02 UTC, dimakuv commented
@pwmarcz Many Jenkins jobs failed, can you check what happened? I didn't look into Jenkins, but my local `make SGX=1 regression` with your new test failed for me.

However, debugging a complex application with your PR was a nice experience! It's a huge boost for us, thanks!

2020-10-09 12:45 UTC, donporter commented
Jenkins, retest SGX please.  Docker restarted on the nodes.

2020-10-09 14:48 UTC, pwmarcz commented
Apart from the SGX nodes failing, there are two failures of `fork11` ltp test. I cannot reproduce that (it consistently passes for me), and I don't see anything in my code that could have influenced it.

>I didn't look into Jenkins, but my local `make SGX=1 regression` with your new test failed for me.
Could you paste the output? The test (`test_000_gdb_backtrace`) should print the whole GDB output on failure. I just tried the tests both on Ubuntu 16 and Ubuntu 18, and they pass.

One thing I can think of: if you compiled some parts with `DEBUG`, and some without, the test will fail (it's trying to detect whether libpal has been compiled with `DEBUG` but this is a weird corner case).

2020-10-09 14:48 UTC, pwmarcz commented
Jenkins, retest this, please. (Looks like the above didn't work).

2020-10-11 18:22 UTC, mkow requested changes
`fork11` failing from time to time is a known issue, unrelated to this PR.

Anyways, seems that Jenkins failed again, this time with:
```
+ ./Scripts/gitignore-test
================================================================================
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
 M Pal/src/host/Linux-SGX/sgx-driver
Entering 'LibOS/shim/test/ltp/src'
Entering 'LibOS/shim/test/ltp/src/testcases/kernel/mce-test'
Entering 'Pal/src/host/Linux-SGX/sgx-driver'
?? .cache.mk
================================================================================
```
Which is weird, maybe our Jenkins slaves started generating this file after a kernel headers update? CC: @donporter @dcowhig

> Reviewed 13 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868#-:-MJNn1ZcBrZw6N2_m2v1:bxqqzoy)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

___
*[LibOS/shim/test/regression/debug.c, line 7 at r10](https://reviewable.io/reviews/oscarlab/graphene/1868#-MJNnQEX5ee2Npg3j6KF:-MJNnQEX5ee2Npg3j6KG:bfl4q2a) ([raw file](https://github.com/oscarlab/graphene/blob/e30872433e01013890a3dc5fcba105d6013ef9aa/LibOS/shim/test/regression/debug.c#L7)):*
> ```C
>     fflush(stdout);
>     /* Prevent tail call, so that we get a stack trace including func(). */
>     __asm__("");
> ```

Please add `volatile`, I'm not sure if the current form will always work.


<!-- Sent from Reviewable.io -->

2020-10-12 09:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: 13 of 14 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/debug.c, line 7 at r10](https://reviewable.io/reviews/oscarlab/graphene/1868#-MJNnQEX5ee2Npg3j6KF:-MJRCbm462V3Tcf00eSu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e30872433e01013890a3dc5fcba105d6013ef9aa/LibOS/shim/test/regression/debug.c#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add `volatile`, I'm not sure if the current form will always work.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-12 18:28 UTC, yamahata approved these changes
> Reviewed 6 of 12 files at r1, 3 of 6 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 11 of 13 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-12 23:09 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-12 23:59 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-13 00:08 UTC, yamahata approved these changes
> Reviewed 1 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1868)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-13 00:57 UTC, merged