GDB: support extended registers
oscarlab/graphene pull request #1874
Opened 2020-10-09 10:10 UTC by pwmarcz

On top of https://github.com/oscarlab/graphene/pull/1868.

This allows reading/writing XMM0 etc. by passing XSAVE data when GDB requests it. There is also a test for that.

## How to test this PR? 

Check if `print $xmm0` and `set $xmm0 = ...` work.

You can use the provided test program (`tdebug_regs.c`) for that. In `LibOS/shim/test/regression`:

* Run the test script: `SGX=1 GDB=1 GDB_SCRIPT=debug_regs.gdb pal_loader ./debug_regs`
* Or play with the program in GDB: `SGX=1 GDB=1 pal_loader ./debug_regs`

2020-10-09 16:04 UTC, yamahata requested changes
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/shim/test/regression/Makefile, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD4Mvt7LHNoar9tg2g:-MJD4Mvt7LHNoar9tg2h:b-22eyzj) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/LibOS/shim/test/regression/Makefile#L16)):*
> ```Makefile
> 	bootstrap_static \
>     debug \
>     debug_regs \
> ```

As debug_regs is x86_64 specific, this can put in c_executable-x86_64.
The ifdef in debug_regs.c can be removed.
(maybe we'd like to rename it to debug_regs-x86_64.c or something)
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD5BdU8AtVBczKZpCz:-MJD5BdU8AtVBczKZpD-:b2z9wsn) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L237)):*
> ```
>  - 1
> ```

Just to make it sure. Is this("-1") correct? or existing bug?  


<!-- Sent from Reviewable.io -->

2020-10-09 16:11 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @yamahata)

___
*[LibOS/shim/test/regression/Makefile, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD4Mvt7LHNoar9tg2g:-MJD77FI16wI_3jY8XiM:b-bojs52) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/LibOS/shim/test/regression/Makefile#L16)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

As debug_regs is x86_64 specific, this can put in c_executable-x86_64.
The ifdef in debug_regs.c can be removed.
(maybe we'd like to rename it to debug_regs-x86_64.c or something)
</blockquote></details>

I didn't know that. Sounds good, I'll move it there and change the name.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD5BdU8AtVBczKZpCz:-MJD6IJ03-cD_i2K7HuS:bus7h48) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L237)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>  - 1
> ```

Just to make it sure. Is this("-1") correct? or existing bug?  
</blockquote></details>

It's not a bug. From what I've understood, `ssaframesize * cssa` points to the *next* SSA frame to be filled, i.e. the end of current SSA frame. That's why we computed the address of GPR area before as `ssaframesize * cssa - sizeof(sgx_pal_gpr_t)`, because the GPR registers are at the end of current frame.


<!-- Sent from Reviewable.io -->

2020-10-12 09:26 UTC, dimakuv requested changes
> Reviewed 4 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/test/regression/Makefile, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD4Mvt7LHNoar9tg2g:-MJR3kZx7NHDg3Mb1KR7:bn41t5u) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/LibOS/shim/test/regression/Makefile#L16)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I didn't know that. Sounds good, I'll move it there and change the name.
</blockquote></details>

+1 to Isaku's request.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD5BdU8AtVBczKZpCz:-MJR524P8oqvwdJXviwh:b8e41du) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L237)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's not a bug. From what I've understood, `ssaframesize * cssa` points to the *next* SSA frame to be filled, i.e. the end of current SSA frame. That's why we computed the address of GPR area before as `ssaframesize * cssa - sizeof(sgx_pal_gpr_t)`, because the GPR registers are at the end of current frame.
</blockquote></details>

Yes, it is not a bug. `CSSA` contains the "current slot index of an SSA frame", which is incremented by one at each EEXIT/AEX and decremented by one at each EENTER/ERESUME. So for example, if we want to peek inside the very first SSA frame of the enclave (which was interrupted when under GDB), then current `CSSA = 1` and we need to look into `CSSA - 1`.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 289 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJR6PYB1DCFk0ZaQ2qU:-MJR6PYC03X1o9GTWUFO:b-fejj5l) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L289)):*
> ```C
>         return -1;
> 
>     ret = pread(memdev, iov->iov_base, iov->iov_len, (off_t)ssa_addr);
> ```

Could you add a comment here that `SSA.XSAVE` field has an offset of zero inside the SSA frame? Thus we can simply read from `ssa_addr`, without additional offset arithmetic.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 306 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJR6kkp9vQZuozXXVyA:-MJR6kkq5V9gv9fhkFZE:b-50i0y9) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L306)):*
> ```C
>         return -1;
> 
>     ret = pwrite(memdev, iov->iov_base, iov->iov_len, (off_t)ssa_addr);
> ```

Could you add a comment here that `SSA.XSAVE` field has an offset of zero inside the SSA frame? Thus we can simply write to `ssa_addr`, without additional offset arithmetic.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 636 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJR6xKWB3St5W3SLaml:-MJR6xKWB3St5W3SLamm:bxv2jha) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L636)):*
> ```C
> 
>             if ((size_t)addr != NT_X86_XSTATE)
>                 return host_ptrace(PTRACE_GETREGSET, tid, addr, data);
> ```

What does this case even mean? "We want to peek inside the enclave via GETREGSET, but not in the XSAVE area"... What does this do?


<!-- Sent from Reviewable.io -->

2020-10-12 10:29 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/test/regression/Makefile, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD4Mvt7LHNoar9tg2g:-MJRGvUr00nzPWQKWTqr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/LibOS/shim/test/regression/Makefile#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Isaku's request.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJD5BdU8AtVBczKZpCz:-MJRHf78B8gHWyq4wLqa:b-aq8a0i) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L237)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, it is not a bug. `CSSA` contains the "current slot index of an SSA frame", which is incremented by one at each EEXIT/AEX and decremented by one at each EENTER/ERESUME. So for example, if we want to peek inside the very first SSA frame of the enclave (which was interrupted when under GDB), then current `CSSA = 1` and we need to look into `CSSA - 1`.
</blockquote></details>

I added a short comment.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 289 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJR6PYB1DCFk0ZaQ2qU:-MJRHpm-8PQAZdUqTHwN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L289)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment here that `SSA.XSAVE` field has an offset of zero inside the SSA frame? Thus we can simply read from `ssa_addr`, without additional offset arithmetic.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 306 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJR6kkp9vQZuozXXVyA:-MJRHrgy-0zwxTk4HpNO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment here that `SSA.XSAVE` field has an offset of zero inside the SSA frame? Thus we can simply write to `ssa_addr`, without additional offset arithmetic.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 636 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJR6xKWB3St5W3SLaml:-MJRIytO0TpO0NEujJH3:bongcz0) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L636)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does this case even mean? "We want to peek inside the enclave via GETREGSET, but not in the XSAVE area"... What does this do?
</blockquote></details>

The x86 ptrace [supports a few more values](https://code.woboq.org/linux/linux/arch/x86/kernel/ptrace.c.html#x86_64_regsets), but as far as I can tell, GDB doesn't use them.

I wanted to fall back to calling real ptrace on any request we don't support, because that's what the rest of the code does. I think that's slightly better than returning an error, but I don't have a strong opinion either way.


<!-- Sent from Reviewable.io -->

2020-10-12 11:45 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

___
*[Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c, line 636 at r1](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJR6xKWB3St5W3SLaml:-MJRcIjT5i5R2KnYvuY4:b-bg0co9) ([raw file](https://github.com/oscarlab/graphene/blob/63e7c13d8fd3a56c90ac490069d2263d1b37b468/Pal/src/host/Linux-SGX/gdb_integration/sgx_gdb.c#L636)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The x86 ptrace [supports a few more values](https://code.woboq.org/linux/linux/arch/x86/kernel/ptrace.c.html#x86_64_regsets), but as far as I can tell, GDB doesn't use them.

I wanted to fall back to calling real ptrace on any request we don't support, because that's what the rest of the code does. I think that's slightly better than returning an error, but I don't have a strong opinion either way.
</blockquote></details>

OK, agreed. Thanks for explanation!


<!-- Sent from Reviewable.io -->

2020-10-12 18:27 UTC, yamahata approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-13 08:48 UTC, pwmarcz commented
I pushed a rebased version after #1868 has been merged.

2020-10-13 08:53 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-13 11:29 UTC, mkow requested changes
> Reviewed 5 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

___
*[LibOS/shim/test/regression/debug_regs-x86_64.c, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJWcgz9A7p2FDm5suqf:-MJWcgz9A7p2FDm5suqg:ba10sdu) ([raw file](https://github.com/oscarlab/graphene/blob/1540f9f13f479d72a55e4af4deea1dc67264d16f/LibOS/shim/test/regression/debug_regs-x86_64.c#L7)):*
> ```C
>     volatile uint64_t val = 0;
> 
>     __asm__("int3");
> ```

Please add `volatile` to this one, the compiler is free to remove it when compiled with optimizations (this one doesn't have any side effects, at least this is what the compiler will think now).


<!-- Sent from Reviewable.io -->

2020-10-13 13:37 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/test/regression/debug_regs-x86_64.c, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJWcgz9A7p2FDm5suqf:-MJXALKdDwXvfynU5sWu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1540f9f13f479d72a55e4af4deea1dc67264d16f/LibOS/shim/test/regression/debug_regs-x86_64.c#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add `volatile` to this one, the compiler is free to remove it when compiled with optimizations (this one doesn't have any side effects, at least this is what the compiler will think now).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-13 14:10 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/test/regression/debug_regs-x86_64.c, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJWcgz9A7p2FDm5suqf:-MJXHc9D5_WH_zrIwCwr:b-29zh85) ([raw file](https://github.com/oscarlab/graphene/blob/1540f9f13f479d72a55e4af4deea1dc67264d16f/LibOS/shim/test/regression/debug_regs-x86_64.c#L7)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shouldn't we add `volatile` in other two inline asms then? The compiler is free to optimize everything away in this program and leaving only `return 0`, no?
___
*[LibOS/shim/test/regression/debug_regs-x86_64.c, line 4 at r4](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJXHMNO2p-EyUZw9imc:-MJXHMNPCLVysEtnoi2y:bkqfkdv) ([raw file](https://github.com/oscarlab/graphene/blob/6c54527784306e73fea25e0eefffea852d173945/LibOS/shim/test/regression/debug_regs-x86_64.c#L4)):*
> ```C
> 
> int main(void) {
> #ifdef __amd64__
> ```

Just noticed: there is no reason for this ifdef, this file is already built only on x86-64.


<!-- Sent from Reviewable.io -->

2020-10-13 14:41 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/debug_regs-x86_64.c, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJWcgz9A7p2FDm5suqf:-MJXOlDX60LiUjsnTBQ3:b-j55cx1) ([raw file](https://github.com/oscarlab/graphene/blob/1540f9f13f479d72a55e4af4deea1dc67264d16f/LibOS/shim/test/regression/debug_regs-x86_64.c#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't we add `volatile` in other two inline asms then? The compiler is free to optimize everything away in this program and leaving only `return 0`, no?
</blockquote></details>

I would expect `val` being volatile to ensure that, but I'm not really sure, and certaily this won't hurt. Updated.

(By the way, why is `int3` not a side effect?)
___
*[LibOS/shim/test/regression/debug_regs-x86_64.c, line 4 at r4](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJXHMNO2p-EyUZw9imc:-MJXP4tQ6wzwQayUjClX:b6ty03n) ([raw file](https://github.com/oscarlab/graphene/blob/6c54527784306e73fea25e0eefffea852d173945/LibOS/shim/test/regression/debug_regs-x86_64.c#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed: there is no reason for this ifdef, this file is already built only on x86-64.
</blockquote></details>

Right. That's a leftover from previous version. Removed.


<!-- Sent from Reviewable.io -->

2020-10-13 14:47 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: 6 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/debug_regs-x86_64.c, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJWcgz9A7p2FDm5suqf:-MJXP17K8yANd-RGBlJL:bmii882) ([raw file](https://github.com/oscarlab/graphene/blob/1540f9f13f479d72a55e4af4deea1dc67264d16f/LibOS/shim/test/regression/debug_regs-x86_64.c#L7)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I would expect `val` being volatile to ensure that, but I'm not really sure, and certaily this won't hurt. Updated.

(By the way, why is `int3` not a side effect?)
</blockquote></details>

No, other asms have explicit in/out dependency on a volatile variable, so compiler can't skip them.

Ad `int3`: GCC inline asm is very primitive - these are just string templates which gets emitted into the final assembly. It's like .format on a string, there's no interpretation of the contents except the insertion points for arguments.

Anyways, this volatile won't hurt.


<!-- Sent from Reviewable.io -->

2020-10-13 16:11 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-10-13 16:13 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/ltp/src, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene/1874#-MJXhCNV1CBShm0F9GNz:-MJXj7p7DS5wgii4ZuWU:b-33gnqd) ([raw file](https://github.com/oscarlab/graphene/blob/55fc052041e39c0ecd17013c034e92607287fe71/LibOS/shim/test/ltp/src#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, seems like you added this by mistake? Please revert.
</blockquote></details>

Ouch. Yes. Reverted. :)


<!-- Sent from Reviewable.io -->

2020-10-13 16:22 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-10-13 17:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-13 17:07 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`fork11` LTP test failed)

2020-10-13 19:21 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-13 19:44 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-14 05:38 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1874)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-14 05:40 UTC, merged