[LibOS] Add XSAVE area handling and save/restore it on child thread creation
oscarlab/graphene pull request #1875
Opened 2020-10-09 10:59 UTC by dimakuv

## Description of the changes 

Previously, LibOS (shim) layer of Graphene didn't support XSAVE area.

The XSAVE area stores FP, XMM, YMM, ZMM, etc. registers and control states and is handled via FXSAVE/XSAVE and FXRSTOR/XRSTOR x86-64 instructions.

This PR is the first step towards adding full-fledged XSAVE support to LibOS. It adds XSAVE related structs and functions to LibOS code, and propagates XSAVE regs/states from parent to child on thread creation via `clone()`.

This PR is a partial recreation of #1218. My PR borrows the XSAVE structs and functions (but renames them for uniformity) from #1218. But XSAVE on signal-handling is not yet implemented; this is for the future.

Future commits will add XSAVE handling on syscall transitions and arriving signals.

## How to test this PR? 

New test `fp_multithread` is added to LibOS regression suite.

2020-10-09 16:26 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_context-x86_64.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJD6PCO4doW4SeIMkTK:-MJD6PCP3HzCzKF1UONy:b8v83z5) ([raw file](https://github.com/oscarlab/graphene/blob/84ddd104135966cf3bdbff7ad68b9f5cbd8e84de/LibOS/shim/src/shim_context-x86_64.c#L30)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> enum SHIM_CPUID_WORD {
>     SHIM_CPUID_WORD_EAX = 0,
>     SHIM_CPUID_WORD_EBX = 1,
>     SHIM_CPUID_WORD_ECX = 2,
>     SHIM_CPUID_WORD_EDX = 3,
>     SHIM_CPUID_WORD_NUM = 4,
> ```
</details>


Why doesn't PAL_CPU_WORD_* work?
___
*[LibOS/shim/src/sys/shim_clone.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJD8GzH-bCIeL176Q9o:-MJD8GzH-bCIeL176Q9p:b-p0vld8) ([raw file](https://github.com/oscarlab/graphene/blob/84ddd104135966cf3bdbff7ad68b9f5cbd8e84de/LibOS/shim/src/sys/shim_clone.c#L106)):*
> ```C
> 
>     /* TODO: XSAVE area should be part of shim_regs, and restore_context() should XRSTOR */
>     shim_xsave_restore(arg->xregs_state);
> ```

Because currently LibOS is complied with FP code enabled, it doesn't make sense to restore FP register here.
It must be done in restore_context().
or Disable FP code on the execution path.
___
*[LibOS/shim/src/sys/shim_clone.c, line 397 at r1](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJD7OCZBR0YXAe4gSW1:-MJD7OCZBR0YXAe4gSW2:b-yomejz) ([raw file](https://github.com/oscarlab/graphene/blob/84ddd104135966cf3bdbff7ad68b9f5cbd8e84de/LibOS/shim/src/sys/shim_clone.c#L397)):*
> ```C
> 
>     struct shim_vma_info vma_info;
>     if (lookup_vma(ALLOC_ALIGN_DOWN_PTR(user_stack_addr), &vma_info) < 0) {
> ```

nice catch.
___
*[LibOS/shim/src/sys/shim_clone.c, line 431 at r1](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJD8sZJ6u_9wuzPaR6_:-MJD8sZJ6u_9wuzPaR6a:b-scbef9) ([raw file](https://github.com/oscarlab/graphene/blob/84ddd104135966cf3bdbff7ad68b9f5cbd8e84de/LibOS/shim/src/sys/shim_clone.c#L431)):*
> ```C
>      * NOTE: this assumes the user-provided stack is at least ~2KB (for AVX512-enabled CPU) */
>     new_args.xregs_state = ALIGN_DOWN_PTR(user_stack_addr - g_shim_xsave_size, SHIM_XSTATE_ALIGN);
>     shim_xsave_save(new_args.xregs_state);
> ```

similar here.
FP control words are callee save, and the newly interoduced test only tests control word. I think that's the reason why the new test passes.


<!-- Sent from Reviewable.io -->

2020-10-09 16:29 UTC, yamahata reviewed
We know the handling of FP register is heavily broken, and this is only a starting point.
So I'm fine with merging inperfect PR at this point.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875#-:-MJDAlv6CxDNcL--stJn:b-wsi8co)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-10-12 08:59 UTC, dimakuv reviewed
Isaku is right. This PR is just a first step to adding FP/XSAVE support to the LibOS layer. The main purpose of this PR is to introduce the required structs and primitives (`xregs_state`, init/save/restore functions). The poor-man's emulation of XSAVE on `clone()` is just to test that it works, and also to fix one particular use case of Graphene. Next PRs will start adding proper emulation of FP/XSAVE.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875#-:-MJQxhdV91tpaiovVmM6:b-r3wkcv)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

___
*[LibOS/shim/src/shim_context-x86_64.c, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJD6PCO4doW4SeIMkTK:-MJQz4dqEB4vSgf-bHk6:bbwdgvz) ([raw file](https://github.com/oscarlab/graphene/blob/84ddd104135966cf3bdbff7ad68b9f5cbd8e84de/LibOS/shim/src/shim_context-x86_64.c#L30)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> enum SHIM_CPUID_WORD {
>     SHIM_CPUID_WORD_EAX = 0,
>     SHIM_CPUID_WORD_EBX = 1,
>     SHIM_CPUID_WORD_ECX = 2,
>     SHIM_CPUID_WORD_EDX = 3,
>     SHIM_CPUID_WORD_NUM = 4,
> ```

Why doesn't PAL_CPU_WORD_* work?
</blockquote></details>

Done. I first wanted it to be self-contained, but now I see that these `PAL_CPUID_...` constants are a part of the PAL interface, so perfectly legitimate to use.
___
*[LibOS/shim/src/sys/shim_clone.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJD8GzH-bCIeL176Q9o:-MJQzGcI9fGUkvh3xb8q:bix2opg) ([raw file](https://github.com/oscarlab/graphene/blob/84ddd104135966cf3bdbff7ad68b9f5cbd8e84de/LibOS/shim/src/sys/shim_clone.c#L106)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Because currently LibOS is complied with FP code enabled, it doesn't make sense to restore FP register here.
It must be done in restore_context().
or Disable FP code on the execution path.
</blockquote></details>

Indeed it doesn't really make sense. This is a "dummy" to test that XSAVE functionality works in general. This is what my TODO comment refers to. Next PRs will introduce a more correct handling of xstate and fix this. Changed to FIXME to make it more explicit.
___
*[LibOS/shim/src/sys/shim_clone.c, line 431 at r1](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJD8sZJ6u_9wuzPaR6_:-MJQzbqv2pzO29Mv4q7M:b-1pu603) ([raw file](https://github.com/oscarlab/graphene/blob/84ddd104135966cf3bdbff7ad68b9f5cbd8e84de/LibOS/shim/src/sys/shim_clone.c#L431)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

similar here.
FP control words are callee save, and the newly interoduced test only tests control word. I think that's the reason why the new test passes.
</blockquote></details>

Indeed, see my other reply.


<!-- Sent from Reviewable.io -->

2020-10-12 18:31 UTC, yamahata approved these changes
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-13 08:17 UTC, dimakuv commented
FYI: I had to rebase this PR to test Jenkins (previously we had issues with Jenkins which were merged in the meantime).

2020-10-13 09:28 UTC, dimakuv commented
Jenkins, retest Jenkins please (`fork11` LTP test failed, known and unrelated)

2020-10-20 11:48 UTC, mkow requested changes
> Reviewed 5 of 10 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJxQxCb4TM3bE1EpDoX:-MJxQxCb4TM3bE1EpDoY:b-ewg1nl) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L29)):*
> ```
> Linux-style FP layout (_libc_fpstate of glibc)
> ```
So, Linux- or glibc- style? Why not using Linux structs?
___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 48 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJy6DZDBYG5DLiT_Vw1:-MJy6DZDBYG5DLiT_Vw2:byh5aci) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L48)):*
> ```
> SHIM_XFEATURE_MAX,
> ```

Looks unused.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 33 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJy8sGe4HO4WkUhBL-7:-MJy8sGe4HO4WkUhBL-8:b1fb736) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L33)):*
> ```C
> #define ECX_XSAVE   (1UL << 26)
> #define ECX_OSXSAVE (1UL << 27)
> #define XSAVE_CPUID 0x0000000d
> ```

In some other place we used the following format: `CPUID_LEAF_<leaf_name>`
___
*[LibOS/shim/src/shim_context-x86_64.c, line 42 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJy90y38NdRmNSGcH38:-MJy90y45BjAzx9hEtst:b-4jggk) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L42)):*
> ```C
> 
>     unsigned int value[4];
>     if (!DkCpuIdRetrieve(0x1, 0, value))
> ```

Could you change this 0x1 into a `CPUID_LEAF_<leaf_name>` define?
___
*[LibOS/shim/src/shim_context-x86_64.c, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-e-hUETTVJOVxwjf1:-MK-e-hVC-fw1KOFb52K:b-xjm3u9) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L53)):*
> ```C
>     uint32_t xsavesize = value[PAL_CPUID_WORD_ECX];
>     uint64_t xfeatures = value[PAL_CPUID_WORD_EAX] |
>                          (((uint64_t)value[PAL_CPUID_WORD_EDX]) << 32);
> ```

No need for parenthesis around the cast, casting is much higher in priority than the bit shifting (so, I don't think people would find this code confusing without them).
___
*[LibOS/shim/src/shim_context-x86_64.c, line 55 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-i8mr1XFUg-1-4XN1:-MK-i8mr1XFUg-1-4XN2:b-2ge3yy) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L55)):*
> ```C
>                          (((uint64_t)value[PAL_CPUID_WORD_EDX]) << 32);
>     if (!xfeatures)
>         goto out;
> ```

Why do we have this `if` here if we check this variable again, right below?
___
*[LibOS/shim/src/shim_context-x86_64.c, line 75 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-iQoH1bJlPeyfE-h2:-MK-iQoH1bJlPeyfE-h3:bu7vpst) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L75)):*
> ```C
>     if (g_shim_xsave_enabled) {
>         long lmask = -1;
>         long hmask = -1;
> ```

please use `uint64_t`
___
*[LibOS/shim/src/shim_context-x86_64.c, line 84 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-jQe51AjWk2V9fkbn:-MK-jQe51AjWk2V9fkbo:b-bbt0ow) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L84)):*
> ```C
>     /* Emulate format for FP registers that Linux uses:
>      * https://elixir.bootlin.com/linux/v5.4.13/source/arch/x86/kernel/fpu/signal.c#L86
>      * https://elixir.bootlin.com/linux/v5.4.13/source/arch/x86/kernel/fpu/signal.c#L459 */
> ```

Actually, why are we emulating Linux format? Is any syscall using it? Or is this actually an x86 format?
___
*[LibOS/shim/src/shim_context-x86_64.c, line 90 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-kI0x5er5Yj103ow0:-MK-kI0x5er5Yj103ow1:b-v079ro) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L90)):*
> ```C
>     fpx_sw->xfeatures     = g_shim_xsave_features;
>     fpx_sw->xstate_size   = g_shim_xsave_size;
>     memset(fpx_sw->padding, 0, sizeof(fpx_sw->padding));
> ```

Please add `&` to the first arg (just for consistency)
___
*[LibOS/shim/src/shim_context-x86_64.c, line 93 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4dsTh8axy0TUBSpYJ:-MK4dsTi1Kzs0w3MZ9nj:b-8uuip3) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L93)):*
> ```C
>     if (g_shim_xsave_enabled) {
>         *((__typeof__(SHIM_FP_XSTATE_MAGIC2)*)((char*)xregs_state + fpx_sw->xstate_size)) =
>             SHIM_FP_XSTATE_MAGIC2;
> ```

How does this work? Why `shim_xregs_state` is actually a structure, if its fields are shifted depending on some runtime config?
___
*[LibOS/shim/src/shim_context-x86_64.c, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4kDjR4by5C4lbZMFe:-MK4kDjS-R1NTzxctB0i:bbg0lw8) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L101)):*
> ```C
>     if (g_shim_xsave_enabled) {
>         long lmask = -1;
>         long hmask = -1;
> ```

`uint64_t`
___
*[LibOS/shim/src/sys/shim_clone.c, line 393 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4lL1_1UbYk8JtFyBy:-MK4lL1_1UbYk8JtFyBz:b-6ffijx) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/sys/shim_clone.c#L393)):*
> ```C
>     enable_locking();
> 
>     /* when cloning a new thread, user must provide stack space for this new thread */
> ```

/summon @boryspoplawski
There was a discussion about this case under #1902. Basically, there will be a lot of collisions between both PRs in this function. In this case Borys says we handle `user_stack_addr == 0` correctly (which is a valid argument for clone).
___
*[LibOS/shim/test/regression/fp_multithread.c, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4mpGe8Dr-ggoMaueD:-MK4mpGe8Dr-ggoMaueE:b-sxm00z) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/test/regression/fp_multithread.c#L24)):*
> ```C
>         mode = atoi(argv[1]);
>         if (mode > sizeof(rounding_modes)/sizeof(rounding_modes[0]) - 1) {
>             errx(EXIT_FAILURE, "run with single argument <rounding mode: one of 0..%lu>",
> ```

`with single argument` -> `with a single argument`
___
*[LibOS/shim/test/regression/Makefile, line 165 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJstVFkAlR7xyXJkjhx:-MJstVFl3aP8rpBYJq1K:b3ei4fd) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/test/regression/Makefile#L165)):*
> ```Makefile
> LDLIBS-attestation += $(PALDIR)/../lib/crypto/mbedtls/install/lib/libmbedcrypto.a
> 
> CFLAGS-fp_multithread = -pthread -fno-builtin
> ```

Please explain in a comment why `-fno-builtin` is needed (something like "this is needed, see the comment in the test's source" is enough)
___
*[LibOS/shim/test/regression/multi_pthread.manifest.template, line 3 at r4](https://reviewable.i [...]

2020-10-20 12:31 UTC, mkow requested changes
> Reviewed 5 of 10 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-10-20 14:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 1 of 10 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJxQxCb4TM3bE1EpDoX:-MK57Cj274p5-obCjB8f:b-itg2xa) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Linux-style FP layout (_libc_fpstate of glibc)
> ```
So, Linux- or glibc- style? Why not using Linux structs?
</blockquote></details>

Done. Linux and Glibc for x86-64 have the same format (they have to be ABI compatible). But you are right, since we're emulating Linux, we should use the style used in Linux sources, not a mix with Glibc.

Please note that I also changed the names from Glibc-like to Linux-like. The most important change is `xregs_state` -> `xstate`
___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 48 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJy6DZDBYG5DLiT_Vw1:-MK57SSY05NlSHO-yo2Q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> SHIM_XFEATURE_MAX,
> ```

Looks unused.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 33 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJy8sGe4HO4WkUhBL-7:-MK58xW5-IgbwdxBOniJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In some other place we used the following format: `CPUID_LEAF_<leaf_name>`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 42 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MJy90y38NdRmNSGcH38:-MK5903Q5Kv6UX-aQinP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you change this 0x1 into a `CPUID_LEAF_<leaf_name>` define?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-e-hUETTVJOVxwjf1:-MK597vTADvPQR0wBCuI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need for parenthesis around the cast, casting is much higher in priority than the bit shifting (so, I don't think people would find this code confusing without them).
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 55 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-i8mr1XFUg-1-4XN1:-MK5A79t4a9ASiKMm_HX:b-lwevzz) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do we have this `if` here if we check this variable again, right below?
</blockquote></details>

But this is a different check: here we check if we were able to retrieve the values for size and bitmask of available XSAVE features. If not, we fall back to FXSAVE. I added more explanations and an additional sanity check.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 75 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-iQoH1bJlPeyfE-h2:-MK5APet7cXrPbvCTAin:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please use `uint64_t`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 84 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-jQe51AjWk2V9fkbn:-MK5HGe62ETT6f3S4p-n:b6hmoc2) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, why are we emulating Linux format? Is any syscall using it? Or is this actually an x86 format?
</blockquote></details>

This is a good question. Glibc and Musl (and generally any libc) assume the same format. This allows to do checks in user-space that the user didn't corrupt XSTATE (which can be in legacy FXSAVE format or in newer XSAVE format). Though I don't see Glibc performing any checks. Also, Linux actually checks this format and the magic values on context switches, especially on signal-handling returns from user land. See https://elixir.bootlin.com/linux/v5.9/source/arch/x86/kernel/fpu/signal.c#L24. We may want to implement something like this in LibOS one day.

It is *not* an x86 format. This is pure SW convention, to be able to check for state corruptions (HW just gives bytes 464..511 of FXSAVE/XSAVE area for SW to do whatever).
___
*[LibOS/shim/src/shim_context-x86_64.c, line 90 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-kI0x5er5Yj103ow0:-MK5BD2U91xHx44vSbIM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L90)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add `&` to the first arg (just for consistency)
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 93 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4dsTh8axy0TUBSpYJ:-MK5IXsQ2CCO7e8uDnDd:bqryzg0) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L93)):*
This explains it: https://elixir.bootlin.com/linux/v5.9/source/arch/x86/kernel/fpu/signal.c#L42.

Basically, there are two HW ways of saving FP/extended state: legacy FXSAVE and newer XSAVE:
- FXSAVE has a fixed size of 512B. It is enough to have some header fields, then x87 and SSE reg values, and a dozen of bytes for random SW purposes.
- XSAVE has an arbitrary size of >512B. This allows for extensibility: new XMM, YMM, ZMM, bounds-checking registers may require 2-4KB of memory to save all values. This XSAVE feature started with AVX technology, it's rather new.

Now `xregs_state` (which I renamed to `xstate` to be closer to Linux sources) has the `xstate_size` which is 512B for FXSAVE or more for XSAVE (detected via CPUID at runtime). But its "real total size" is `xstate_size + FP_XSTATE_MAGIC2_SIZE` so there are 4 bytes at the very end of `state` object that contain the magic2 value. And Linux puts this magic2 value to make sure the calculations in the app and kernel sources are correct at all times. (This is checked in e.g. `check_for_xstate()` https://elixir.bootlin.com/linux/v5.9/source/arch/x86/kernel/fpu/signal.c#L24)

> if its fields are shifted depending on some runtime config

I didn't understand this comment. There is no shifting of fields. We only add a magic 4B value to the very end of this struct (actually, even past the "xsave-area" struct size).
___
*[LibOS/shim/src/shim_context-x86_64.c, line 101 at r4](h [...]

2020-10-20 15:48 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 1 of 10 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/sys/shim_clone.c, line 393 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4lL1_1UbYk8JtFyBy:-MK5ergl3WTcLWLxZD2_:b-q27me0) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/sys/shim_clone.c#L393)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, my PR wants the user to specify `user_stack_addr != 0`. Because I use the new-thread stack to copy the XSAVE area (SSE/XMM/... regs) from parent thread to child thread. But I could also use `malloc()`/`free()` if there is a chance that a new thread may have no stack...
</blockquote></details>

1. I think it would be a good idea if you rebased this PR on top of 1902 once it gets merged (once I debug a test failing).
2. If `user_stack_addr == 0` then we use parent stack. I know it sounds crazy and in normal cases it won't work, but:
    a) that's what Linux does,
    b) it's dead easy to implement (one if),
    c) it might work in some weird apps switching stack in parent, not using it at all, or some other craziness.


<!-- Sent from Reviewable.io -->

2020-10-20 19:23 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 1 of 10 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/sys/shim_clone.c, line 393 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4lL1_1UbYk8JtFyBy:-MK6SrDJDwqe1KS2eF_i:bwh6hqs) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/sys/shim_clone.c#L393)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1. I think it would be a good idea if you rebased this PR on top of 1902 once it gets merged (once I debug a test failing).
2. If `user_stack_addr == 0` then we use parent stack. I know it sounds crazy and in normal cases it won't work, but:
    a) that's what Linux does,
    b) it's dead easy to implement (one if),
    c) it might work in some weird apps switching stack in parent, not using it at all, or some other craziness.
</blockquote></details>

1902 was merged


<!-- Sent from Reviewable.io -->

2020-10-20 22:52 UTC, mkow requested changes
> Reviewed 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/shim_context-x86_64.c, line 55 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-i8mr1XFUg-1-4XN1:-MK5s7tV8pEdLyyiDQu_:b-1t8z23) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this is a different check: here we check if we were able to retrieve the values for size and bitmask of available XSAVE features. If not, we fall back to FXSAVE. I added more explanations and an additional sanity check.
</blockquote></details>

Ok, but then I think it would be more readable and safer to write `xfeatures & ~SHIM_XFEATURE_MASK_FPSSE`, this actually checks what you wanted to check (without any additional assumptions).
___
*[LibOS/shim/src/shim_context-x86_64.c, line 84 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-jQe51AjWk2V9fkbn:-MK5q3qw1D8Nr-eVjgcU:bl427kw) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a good question. Glibc and Musl (and generally any libc) assume the same format. This allows to do checks in user-space that the user didn't corrupt XSTATE (which can be in legacy FXSAVE format or in newer XSAVE format). Though I don't see Glibc performing any checks. Also, Linux actually checks this format and the magic values on context switches, especially on signal-handling returns from user land. See https://elixir.bootlin.com/linux/v5.9/source/arch/x86/kernel/fpu/signal.c#L24. We may want to implement something like this in LibOS one day.

It is *not* an x86 format. This is pure SW convention, to be able to check for state corruptions (HW just gives bytes 464..511 of FXSAVE/XSAVE area for SW to do whatever).
</blockquote></details>

Thanks for the explanation, it's much clearer to me now.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 93 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4dsTh8axy0TUBSpYJ:-MK5tGSz0Z21OJ6e6Gm0:b-63ezjs) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This explains it: https://elixir.bootlin.com/linux/v5.9/source/arch/x86/kernel/fpu/signal.c#L42.

Basically, there are two HW ways of saving FP/extended state: legacy FXSAVE and newer XSAVE:
- FXSAVE has a fixed size of 512B. It is enough to have some header fields, then x87 and SSE reg values, and a dozen of bytes for random SW purposes.
- XSAVE has an arbitrary size of >512B. This allows for extensibility: new XMM, YMM, ZMM, bounds-checking registers may require 2-4KB of memory to save all values. This XSAVE feature started with AVX technology, it's rather new.

Now `xregs_state` (which I renamed to `xstate` to be closer to Linux sources) has the `xstate_size` which is 512B for FXSAVE or more for XSAVE (detected via CPUID at runtime). But its "real total size" is `xstate_size + FP_XSTATE_MAGIC2_SIZE` so there are 4 bytes at the very end of `state` object that contain the magic2 value. And Linux puts this magic2 value to make sure the calculations in the app and kernel sources are correct at all times. (This is checked in e.g. `check_for_xstate()` https://elixir.bootlin.com/linux/v5.9/source/arch/x86/kernel/fpu/signal.c#L24)

> if its fields are shifted depending on some runtime config

I didn't understand this comment. There is no shifting of fields. We only add a magic 4B value to the very end of this struct (actually, even past the "xsave-area" struct size).
</blockquote></details>

Ah, what confused me is that you use `struct shim_xstate`, but it actually has trailing data afterwards. Could you either comment this stuct or maybe pass it as void* and unpack here to header + data? Current version was very confusing to me.
___
*[LibOS/shim/test/regression/fp_multithread.c, line 12 at r5](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK75utgAjm-p3Lr7b7A:-MK75uth73vJW61KXXvm:bc6izqj) ([raw file](https://github.com/oscarlab/graphene/blob/f1cfee9c0a7884933dca7a54bca1ebb4180c2dea/LibOS/shim/test/regression/fp_multithread.c#L12)):*
> ```C
> static int rounding_modes[] = {FE_TONEAREST, FE_UPWARD, FE_DOWNWARD, FE_TOWARDZERO};
> 
> static char* print_rounding_mode(int mode) {
> ```

`print` -> `get`: it's not actually printing anything
___
*[LibOS/shim/test/regression/fp_multithread.c, line 19 at r5](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK6LgnS1LkgqQThE-gs:-MK6LgnS1LkgqQThE-gt:b-1368dj) ([raw file](https://github.com/oscarlab/graphene/blob/f1cfee9c0a7884933dca7a54bca1ebb4180c2dea/LibOS/shim/test/regression/fp_multithread.c#L19)):*
> ```
> UNKOWN
> ```

Something is not right here :)


<!-- Sent from Reviewable.io -->

2020-10-21 14:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 0 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKAW2ZYBrOdsujQj9V8:-MKAW2ZYBrOdsujQj9V9:b-v44vdf) (no related file):*
NOTE: Squashed and rebased to the current master because #1902 was merged.

---
___
*[LibOS/shim/src/shim_context-x86_64.c, line 55 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK-i8mr1XFUg-1-4XN1:-MKACrEsCcBVUI7L1FvT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but then I think it would be more readable and safer to write `xfeatures & ~SHIM_XFEATURE_MASK_FPSSE`, this actually checks what you wanted to check (without any additional assumptions).
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 93 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4dsTh8axy0TUBSpYJ:-MKAGM5k7f0ys1ypwqy0:b-x6aq1d) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L93)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, what confused me is that you use `struct shim_xstate`, but it actually has trailing data afterwards. Could you either comment this stuct or maybe pass it as void* and unpack here to header + data? Current version was very confusing to me.
</blockquote></details>

Done. Actually found a couple bugs while doing this. Now the code should be much clearer.
___
*[LibOS/shim/src/sys/shim_clone.c, line 393 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4lL1_1UbYk8JtFyBy:-MKAWKgn8S2WTDikwVRz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/sys/shim_clone.c#L393)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1902 was merged
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/fp_multithread.c, line 12 at r5](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK75utgAjm-p3Lr7b7A:-MKA6uWM7hT52gtxa5UL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f1cfee9c0a7884933dca7a54bca1ebb4180c2dea/LibOS/shim/test/regression/fp_multithread.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`print` -> `get`: it's not actually printing anything
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/fp_multithread.c, line 19 at r5](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK6LgnS1LkgqQThE-gs:-MKA6tjKCSi5AyzvqOw3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f1cfee9c0a7884933dca7a54bca1ebb4180c2dea/LibOS/shim/test/regression/fp_multithread.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> UNKOWN
> ```

Something is not right here :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-21 14:37 UTC, dimakuv commented
Jenkins, retest Jenkins please (`truncate01` and `writev07` LTP tests failed, cannot reproduce)

2020-10-21 14:57 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 0 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_clone.c, line 402 at r6](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKAdcMk1DSAr4921dTR:-MKAdcMl5qXPOOJZn74A:bx6t6pi) ([raw file](https://github.com/oscarlab/graphene/blob/b4d21052387297453ef876f2f2910829010ce329/LibOS/shim/src/sys/shim_clone.c#L402)):*
> ```C
>     new_args.xstate_extended    = ALIGN_DOWN_PTR(new_args.stack - xstate_extended_size,
>                                                  SHIM_XSTATE_ALIGN);
>     shim_xstate_save(new_args.xstate_extended);
> ```

This touches memory pointed by `new_args.stack` before validity of that argument is checked (`lookup_vma` in `clone_implementaton_wrapper`).


<!-- Sent from Reviewable.io -->

2020-10-21 14:57 UTC, mkow requested changes
> Reviewed 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/shim_context-x86_64.c, line 93 at r4](https://reviewable.io/reviews/oscarlab/graphene/1875#-MK4dsTh8axy0TUBSpYJ:-MKAc05W9CZRY64gAVRV:bwxjn8z) ([raw file](https://github.com/oscarlab/graphene/blob/196fe0818fb05fcf7a448bd504501c11e2dda967/LibOS/shim/src/shim_context-x86_64.c#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Actually found a couple bugs while doing this. Now the code should be much clearer.
</blockquote></details>

Yeah, it's much better now :)
___
*[LibOS/shim/src/sys/shim_clone.c, line 401 at r6](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKAdodiBfAtHUXG3xHu:-MKAdodiBfAtHUXG3xHv:b-bg8s47) ([raw file](https://github.com/oscarlab/graphene/blob/b4d21052387297453ef876f2f2910829010ce329/LibOS/shim/src/sys/shim_clone.c#L401)):*
> ```C
>     size_t xstate_extended_size = g_shim_xsave_size + SHIM_FP_XSTATE_MAGIC2_SIZE;
>     new_args.xstate_extended    = ALIGN_DOWN_PTR(new_args.stack - xstate_extended_size,
>                                                  SHIM_XSTATE_ALIGN);
> ```

Shouldn't we fix up `new_args.stack` after this alignment?
___
*[LibOS/shim/test/regression/Makefile, line 168 at r6](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKAe8HI3o5CWTWLP6b_:-MKAe8HJ5ME5H4BCR-af:b-mabwp1) ([raw file](https://github.com/oscarlab/graphene/blob/b4d21052387297453ef876f2f2910829010ce329/LibOS/shim/test/regression/Makefile#L168)):*
> ```Makefile
> LDLIBS-attestation += $(PALDIR)/../lib/crypto/mbedtls/install/lib/libmbedcrypto.a
> 
> CFLAGS-fp_multithread = -pthread -fno-builtin  # see comment in the test's source
> ```

Just noticed: why it's `=`, not `+=`?


<!-- Sent from Reviewable.io -->

2020-10-21 15:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/sys/shim_clone.c, line 401 at r6](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKAdodiBfAtHUXG3xHu:-MKAfNmL71NvUMgZMXi-:b9a6jsd) ([raw file](https://github.com/oscarlab/graphene/blob/b4d21052387297453ef876f2f2910829010ce329/LibOS/shim/src/sys/shim_clone.c#L401)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we fix up `new_args.stack` after this alignment?
</blockquote></details>

No, because we kinda abuse this stack to dump XSAVE registers (so that the child thread can restore this state). See the FIXME comment; it's only a hack for now. Should be removed in future PRs...
___
*[LibOS/shim/src/sys/shim_clone.c, line 402 at r6](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKAdcMk1DSAr4921dTR:-MKAf_Tt3BtTOtolvj-c:b-6xgbwa) ([raw file](https://github.com/oscarlab/graphene/blob/b4d21052387297453ef876f2f2910829010ce329/LibOS/shim/src/sys/shim_clone.c#L402)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This touches memory pointed by `new_args.stack` before validity of that argument is checked (`lookup_vma` in `clone_implementaton_wrapper`).
</blockquote></details>

Yes, see the FIXME comment. I didn't want to introduce additional checks of correctness of this memory region, because this is wrong anyway and will be fixed in future PRs.


<!-- Sent from Reviewable.io -->

2020-10-28 11:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 9 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/Makefile, line 168 at r6](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKAe8HI3o5CWTWLP6b_:-MKiu6C-BjNGhmDaVxAa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b4d21052387297453ef876f2f2910829010ce329/LibOS/shim/test/regression/Makefile#L168)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just noticed: why it's `=`, not `+=`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 11:17 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-28 15:35 UTC, boryspoplawski reviewed
> Reviewed 9 of 10 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_context-x86_64.c, line 130 at r7](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKjpTKL-CvUMf5UcBtt:-MKjpTKM4R5f2IpCSgVk:b-vkg63) ([raw file](https://github.com/oscarlab/graphene/blob/afc1f446f8a1699659fb522795ea20e1836d63f5/LibOS/shim/src/shim_context-x86_64.c#L130)):*
> ```C
>         uint64_t lmask = (uint64_t)-1;
>         uint64_t hmask = (uint64_t)-1;
>         __asm__ volatile("xrstor64 (%0)" :: "r"(xstate), "a"(lmask), "d"(hmask) : "memory");
> ```

We need to add all changed regisers (like `xmm0` to clobber list here or use gcc builtins for `xrstor`.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 132 at r7](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKjpeGBC4V9DBLsGJid:-MKjpeGBC4V9DBLsGJie:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/afc1f446f8a1699659fb522795ea20e1836d63f5/LibOS/shim/src/shim_context-x86_64.c#L132)):*
> ```C
>         __asm__ volatile("xrstor64 (%0)" :: "r"(xstate), "a"(lmask), "d"(hmask) : "memory");
>     } else {
>         __asm__ volatile("fxrstor64 (%0)" :: "r"(xstate) : "memory");
> ```

ditto
___
*[LibOS/shim/test/regression/fp_multithread.c, line 22 at r7](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKjq6ldB2dax7eqIerD:-MKjq6ldB2dax7eqIerE:bioep0f) ([raw file](https://github.com/oscarlab/graphene/blob/afc1f446f8a1699659fb522795ea20e1836d63f5/LibOS/shim/test/regression/fp_multithread.c#L22)):*
> ```C
> }
> 
> static void* thread_fp(void* arg) {
> ```

`arg` is not used (which should cause a compiler warrning), either add `(void)arg;` or simply return it from this function.


<!-- Sent from Reviewable.io -->

2020-10-29 08:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: 8 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/shim_context-x86_64.c, line 130 at r7](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKjpTKL-CvUMf5UcBtt:-MKnZEj57gWznyhUcAeU:bw886pq) ([raw file](https://github.com/oscarlab/graphene/blob/afc1f446f8a1699659fb522795ea20e1836d63f5/LibOS/shim/src/shim_context-x86_64.c#L130)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need to add all changed regisers (like `xmm0` to clobber list here or use gcc builtins for `xrstor`.
</blockquote></details>

Done. Good catch. Couldn't find a good way to specify that all "extended state" registers (not only XMM/YMM/ZMM but also exotic ones like BND0..BND3) are clobbered in inline asm, so switched to GCC builtins. This topic seems to be a gray area, couldn't find any assurance that the GCC builtins correctly clobber all possible "extended state" regs...

But anyway, these xsave/xrtor will only be used during app <-> Graphene transitions, so shouldn't be a problem in the future when we move them to appropriate places.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 132 at r7](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKjpeGBC4V9DBLsGJid:-MKn_-YO0fGy-gkkgQzn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/afc1f446f8a1699659fb522795ea20e1836d63f5/LibOS/shim/src/shim_context-x86_64.c#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/fp_multithread.c, line 22 at r7](https://reviewable.io/reviews/oscarlab/graphene/1875#-MKjq6ldB2dax7eqIerD:-MKjshgP4MH4e53iuW-a:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/afc1f446f8a1699659fb522795ea20e1836d63f5/LibOS/shim/test/regression/fp_multithread.c#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`arg` is not used (which should cause a compiler warrning), either add `(void)arg;` or simply return it from this function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 09:13 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`fork11` LTP test failed, known issue)

2020-10-29 10:16 UTC, dimakuv commented
Jenkins, retest Jenkins please (`fork11` LTP test failed, known issue)

2020-10-29 10:16 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (landed on a dying Jenkins worker)

2020-10-29 11:36 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-29 15:18 UTC, boryspoplawski approved these changes
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-29 15:35 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (landed on dying Jenkins worker)

2020-10-29 15:45 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (landed on a dying Jenkins worker, seems to have messed with output)

2020-10-29 15:50 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-29 16:09 UTC, yamahata approved these changes
> Reviewed 4 of 10 files at r6, 3 of 3 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1875)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-29 16:48 UTC, merged