Add first meson.build for installing
oscarlab/graphene pull request #1879
Opened 2020-10-10 09:04 UTC by woju

## Description of the changes 

This adds a possibility to actually install graphene in the system, and make packages for distributions.

This also might be a beginning of switching build system to meson. See #760 for a discussion of alternative build system, which I hope to revive.

## How to test this PR? 

Compile as usual with and without SGX (this is important that both variants are built together). Prepare some `helloworld` executable with manifest, signatures etc.

After that:
```sh
sudo apt install ninja-build

# can be replaced with `sudo apt install meson` on Debian since buster,
# but not on Ubuntu 18.04, where meson is too old
python3 -m pip install meson

# pick some suitable directory; if --prefix <path> is omitted,
# will install to /usr/local
meson setup build --prefix "$HOME"/tmp

ninja -C build # currently no-op, this is where any compilation would happen
ninja -C build install

export PATH="$HOME"/tmp/bin:"$PATH"  # or wherever you chose the prefix

cd "$HOME"/my-example-programs # with manifests and signatures and tokens already prepared
graphene ./helloworld.manifest
graphene-sgx ./helloworld.manifest.sgx
```

2020-10-12 12:54 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJRs1DC8zazs1u5rfAw:b-4gjuut) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
> ```
> #                    Wojtek Porczyk <woju@invisiblethingslab.com>
> 
> if test -n @IN_GIT@  # in meson, this gets zeroed out, so this will only take first branch in repo
> ```

Even with this comment, I don't understand what `IN_GIT` means... Could you give some more context?


<!-- Sent from Reviewable.io -->

2020-10-12 15:11 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJSIsC6-y5VGI9M62ec:b-vwmjph) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Even with this comment, I don't understand what `IN_GIT` means... Could you give some more context?
</blockquote></details>

This is a regular string in shell (`@` is not a special character), so `test -n @IN_GIT@` as it stands verbatim here is true (may I respectfuly remind you that `-n` stands for "nonzero", but really refers to the string length, not the integer value), so the first branch is taken. The first branch is unmodified from before this commit (just indented), so no functional change.

Meson has [configure_file](https://mesonbuild.com/Reference-manual.html#configure_file) function, which is intended for processing `.in` files and substituting things like `sed -e "s:@VARIABLE@:$VALUE:"` was done in other build systems. This is used here to substitute `@IN_GIT@` to empty value, but quoted (see `conf.set_quoted('IN_GIT', '')` line in `Runtime/meson.build`). Then in the resulting file (`graphene` or `graphene-sgx`) this reads `test -n ""`, which is false and the execution takes `else` branch.

The purpose is to have a single file which behaves both as it was before (this PR promises to not make changes and to not make meson mandatory) and also makes it possible to be installed without repository, make and gcc (which is currently invoked on every `pal_loader` invocation). For the second option I needed to hardcode the necessary variables (this is done with the same configure_file call) to absolute paths (`graphene[-sgx]` can be invoked from any directory in the system), so this have to behave differently whether this is run before or after installation.


<!-- Sent from Reviewable.io -->

2020-10-12 15:35 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJSR-7U2o__2Kl_0gg-:b-4b5uz5) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is a regular string in shell (`@` is not a special character), so `test -n @IN_GIT@` as it stands verbatim here is true (may I respectfuly remind you that `-n` stands for "nonzero", but really refers to the string length, not the integer value), so the first branch is taken. The first branch is unmodified from before this commit (just indented), so no functional change.

Meson has [configure_file](https://mesonbuild.com/Reference-manual.html#configure_file) function, which is intended for processing `.in` files and substituting things like `sed -e "s:@VARIABLE@:$VALUE:"` was done in other build systems. This is used here to substitute `@IN_GIT@` to empty value, but quoted (see `conf.set_quoted('IN_GIT', '')` line in `Runtime/meson.build`). Then in the resulting file (`graphene` or `graphene-sgx`) this reads `test -n ""`, which is false and the execution takes `else` branch.

The purpose is to have a single file which behaves both as it was before (this PR promises to not make changes and to not make meson mandatory) and also makes it possible to be installed without repository, make and gcc (which is currently invoked on every `pal_loader` invocation). For the second option I needed to hardcode the necessary variables (this is done with the same configure_file call) to absolute paths (`graphene[-sgx]` can be invoked from any directory in the system), so this have to behave differently whether this is run before or after installation.
</blockquote></details>

Ah, ok. What I missed were two pieces of info:
1. `@IN_GIT@` is just a dummy that is replaced (by empty string) when run via Meson (`pal_loader` becomes the template for Meson, which produces the `graphene` script via sed-like replacements). The name `IN_GIT` is not very telling to me -- smth like `OLD_RUNTIME` would be more intuitive.
2. Meson requires variables to be surrounded with `@` for replacement.


<!-- Sent from Reviewable.io -->

2020-10-12 17:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJS_qou98k2muHzM28q:bn9er8l) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, ok. What I missed were two pieces of info:
1. `@IN_GIT@` is just a dummy that is replaced (by empty string) when run via Meson (`pal_loader` becomes the template for Meson, which produces the `graphene` script via sed-like replacements). The name `IN_GIT` is not very telling to me -- smth like `OLD_RUNTIME` would be more intuitive.
2. Meson requires variables to be surrounded with `@` for replacement.
</blockquote></details>

Would you like this to be included in a comment somewhere?


<!-- Sent from Reviewable.io -->

2020-10-12 17:49 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJSuWBHAnlhZSpgaTqc:ba5wqgq) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Would you like this to be included in a comment somewhere?
</blockquote></details>

What about these:
- Add a link to the `configure_file()` Meson function (this cleared many of my questions immediately) somewhere in the docs/top-level comments
- Rename `IN_GIT` to something more telling like `OLD_RUNTIME`
- Rephrase your comment `in meson, this gets zeroed out, so this will only take first branch in repo` -> `after running through meson, IN_GIT gets zeroed out (i.e., the true branch is taken if run in git repo, false branch is taken in install)` -- smth like this


<!-- Sent from Reviewable.io -->

2020-10-12 18:20 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[Runtime/meson.build, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJT1YAs0Zhn5bmnHlJv:-MJT1YAs0Zhn5bmnHlJw:bvzkf7p) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/meson.build#L2)):*
> ```Meson
> install_data('../Pal/src/host/Linux/libpal.so',
>     install_dir: pkglibexecdir / 'linux')
> ```

nice. This is a starting point for distro package.


<!-- Sent from Reviewable.io -->

2020-10-12 19:14 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: 2 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJTCCpW2QHeOZ0Gz-a5:b-fcvai7) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about these:
- Add a link to the `configure_file()` Meson function (this cleared many of my questions immediately) somewhere in the docs/top-level comments
- Rename `IN_GIT` to something more telling like `OLD_RUNTIME`
- Rephrase your comment `in meson, this gets zeroed out, so this will only take first branch in repo` -> `after running through meson, IN_GIT gets zeroed out (i.e., the true branch is taken if run in git repo, false branch is taken in install)` -- smth like this
</blockquote></details>

Is this comment OK?


<!-- Sent from Reviewable.io -->

2020-10-13 07:17 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJVoIH0Dzj1KA7Dldsz:-MJVoIH0Dzj1KA7Dldt-:b-bketds) (no related file):*
Minor: the last fixup commit refers to a wrong base commit ("Add benchmarks"). Correctly resolve this during squash-and-rebase.

---
___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJVnbgbBYQKiL779AoY:b-480tko) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Is this comment OK?
</blockquote></details>

Yes, perfect for dummies like me :)


<!-- Sent from Reviewable.io -->

2020-10-13 17:49 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJVoIH0Dzj1KA7Dldsz:-MJY3FFJ27JivPA9JKZi:b-xbk93u) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Minor: the last fixup commit refers to a wrong base commit ("Add benchmarks"). Correctly resolve this during squash-and-rebase.
</blockquote></details>

sorry, this was too much shell-fu

---
___
*[Runtime/pal_loader, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJRs1DC8zazs1u5rfAv:-MJY3dovDhWBgnoFPaV6:b-r4dz90) ([raw file](https://github.com/oscarlab/graphene/blob/c5349fe9a10a37d3d4bb359b5787d6fd1ed4e41b/Runtime/pal_loader#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, perfect for dummies like me :)
</blockquote></details>

You'll be not the only on wondering, how this polyglot works.


<!-- Sent from Reviewable.io -->

2020-10-14 14:06 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-14 14:55 UTC, mkow requested changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[.gitignore, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJbYDy884bfOil80s7c:-MJbYDy884bfOil80s7d:b-gtz9uz) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/.gitignore#L1)):*
> ```ignore
> build/
> ```

should be `/build/`, otherwise it's a recursive pattern
___
*[meson.build, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJb_Ar97zRHcN3fzydb:-MJb_Ar97zRHcN3fzydc:b-50qudh) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/meson.build#L8)):*
> ```
> pkglibexecdir
> ```

This is really hard to read without underscores, would be good to ad at least one after `pkg`.
___
*[Runtime/meson.build, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJb_kif3qFosOo7AGPO:-MJb_kif3qFosOo7AGPP:b-xtmopz) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/Runtime/meson.build#L22)):*
> ```Meson
> conf_graphene.set_quoted('HOST_PAL_PATH', hostpalpath_linux)
> conf_graphene.set_quoted('LIBPAL_PATH', hostpalpath_linux / 'libpal.so')
> conf_graphene.set_quoted('PAL_CMD', hostpalpath_linux / 'libpal.so')
> ```

Why is this the same as `LIBPAL_PATH`?
___
*[Runtime/pal_loader, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJbadDZAbvJE5PsjZXf:-MJbadDZAbvJE5PsjZXg:bjgpewy) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/Runtime/pal_loader#L28)):*
> ```
>                 ;;
>             "GDB")
>                 GDB=1
> ```

Why we don't support these options in the installed version?


<!-- Sent from Reviewable.io -->

2020-10-14 15:17 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[.gitignore, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJbYDy884bfOil80s7c:-MJbfUYx4Yc8lbhpPiRJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/.gitignore#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be `/build/`, otherwise it's a recursive pattern
</blockquote></details>

Done.
___
*[meson.build, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJb_Ar97zRHcN3fzydb:-MJbfRlVCUT8KE3-tzvB:b-i0hnkr) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/meson.build#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> pkglibexecdir
> ```

This is really hard to read without underscores, would be good to ad at least one after `pkg`.
</blockquote></details>

This is a convention.
___
*[Runtime/meson.build, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJb_kif3qFosOo7AGPO:-MJbf5ewBJq9nHeZQSOi:b-eio7th) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/Runtime/meson.build#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this the same as `LIBPAL_PATH`?
</blockquote></details>

You tell me. This is how non-sgx graphene works.
___
*[Runtime/pal_loader, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJbadDZAbvJE5PsjZXf:-MJbeS1A8AjzpLTZh5Ao:b-bon6ub) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/Runtime/pal_loader#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why we don't support these options in the installed version?
</blockquote></details>

According to #1053, there are no such options.

`GDB=1 graphene-sgx whatever.manifest.sgx` still works.


<!-- Sent from Reviewable.io -->

2020-10-14 17:03 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Runtime/meson.build, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJb_kif3qFosOo7AGPO:-MJc2yswE-wwNLYW9ZFZ:b-ric2ik) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/Runtime/meson.build#L22)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

You tell me. This is how non-sgx graphene works.
</blockquote></details>

0o
I guess only @chiache and @donporter know the answer :)
___
*[Runtime/pal_loader, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/1879#-MJbadDZAbvJE5PsjZXf:-MJc3AGM9w8NZFEMA8_A:b-jwuorp) ([raw file](https://github.com/oscarlab/graphene/blob/b939fd72cea61e86e211c68cb37a411accbd0eea/Runtime/pal_loader#L28)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

According to #1053, there are no such options.

`GDB=1 graphene-sgx whatever.manifest.sgx` still works.
</blockquote></details>

Ah, I missed the fact that envs still work. Then it's fine.


<!-- Sent from Reviewable.io -->

2020-10-15 00:16 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-15 00:24 UTC, yamahata approved these changes
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1879)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-15 01:16 UTC, merged