Create a helper script for running pytest
oscarlab/graphene pull request #1881
Opened 2020-10-10 16:19 UTC by pwmarcz

Running a subset of regression tests, or a single test, is
currently rather annoying, as you cannot simply run 'pytest':
you need to override PYTHONPATH and specify several environment
variables.

Instead, move the whole boilerplate to a wrapper scripts that
allows running pytest with any command line options. Use it in
Makefiles as well, so that it doesn't go out of sync with CI.

## How to test this PR? 

Try to follow the instructions for `run-pytest` added in `CONTRIBUTING.rst`.

2020-10-11 14:32 UTC, yamahata submitted a review, later dismissed
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-11 17:36 UTC, mkow requested changes
Thanks for the fix, this was annoying me for quite some time.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881#-:-MJNdcrw2gxOL9o8XUtl:bxqfa7x)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNik2y-YOksrDwfkuJ:-MJNik2y-YOksrDwfkuK:brr8xo5) (no related file):*
All Jenkins pipelines failed with:
```
[Pipeline] junit
Recording test results
No test report files were found. Configuration error?
```

---
___
*[CONTRIBUTING.rst, line 179 at r1](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNiJJeDOZE-7uH7RWJ:-MJNiJJfEy7lSp4OJqSk:b76lgqg) ([raw file](https://github.com/oscarlab/graphene/blob/2313f7097881c005d742beb60800b1e65cd98524/CONTRIBUTING.rst#L179)):*
> ```reStructuredText
> 
> One can run tests manually (prepend the command with ``SGX=1`` or ``PAL_HOST=Linux-SGX`` to run the
> SGX variant)::
> ```

Please wrap reST at 80 chars (yeah, that's quite unintuitive. all the complaints should go to @woju :) )
___
*[Scripts/run-pytest, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNfabT66DD0w_OSAiL:-MJNfabT66DD0w_OSAiM:bqeroy2) ([raw file](https://github.com/oscarlab/graphene/blob/2313f7097881c005d742beb60800b1e65cd98524/Scripts/run-pytest#L1)):*
> ```
> #!/bin/bash -e
> ```

please use `/usr/bin/env bash` + `set -e` for better portability to weird distros
___
*[Scripts/run-pytest, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNg09yEV-eAKQcdN4F:-MJNg09yEV-eAKQcdN4G:b-izn87q) ([raw file](https://github.com/oscarlab/graphene/blob/2313f7097881c005d742beb60800b1e65cd98524/Scripts/run-pytest#L1)):*
> ```
> #!/bin/bash -e
> ```

Could you add this file to `.ci/run-shellcheck` and verify that it passes shellcheck?


<!-- Sent from Reviewable.io -->

2020-10-12 09:37 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz and @woju)



<!-- Sent from Reviewable.io -->

2020-10-12 10:42 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: 2 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNik2y-YOksrDwfkuJ:-MJRNBna0mjP5b5TLO2p:bou8y4y) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

All Jenkins pipelines failed with:
```
[Pipeline] junit
Recording test results
No test report files were found. Configuration error?
```
</blockquote></details>

Wrong script path, I must have hallucinated something. Fixed.

---
___
*[CONTRIBUTING.rst, line 179 at r1](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNiJJeDOZE-7uH7RWJ:-MJRO6243-oVCCzymDX2:b-o0zc58) ([raw file](https://github.com/oscarlab/graphene/blob/2313f7097881c005d742beb60800b1e65cd98524/CONTRIBUTING.rst#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please wrap reST at 80 chars (yeah, that's quite unintuitive. all the complaints should go to @woju :) )
</blockquote></details>

No problem, but the 100 columns came from Emacs settings in `.dir-locals.el`. I updated the settings and reformatted the few offending lines in this file.
___
*[Scripts/run-pytest, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNfabT66DD0w_OSAiL:-MJROgzJ9-h6qAbmAvJv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2313f7097881c005d742beb60800b1e65cd98524/Scripts/run-pytest#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please use `/usr/bin/env bash` + `set -e` for better portability to weird distros
</blockquote></details>

Done.
___
*[Scripts/run-pytest, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNg09yEV-eAKQcdN4F:-MJROvJK9AkDkZm6QxX2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2313f7097881c005d742beb60800b1e65cd98524/Scripts/run-pytest#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add this file to `.ci/run-shellcheck` and verify that it passes shellcheck?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-12 11:46 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2020-10-12 13:25 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 5 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-12 18:25 UTC, yamahata approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-12 23:04 UTC, mkow approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNik2y-YOksrDwfkuJ:-MJU1AisCWlsOREIj_h3:b32vhw) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Wrong script path, I must have hallucinated something. Fixed.
</blockquote></details>

:)

---
___
*[CONTRIBUTING.rst, line 179 at r1](https://reviewable.io/reviews/oscarlab/graphene/1881#-MJNiJJeDOZE-7uH7RWJ:-MJU1Qlw6-mKIiyZmDl-:b-oxnmls) ([raw file](https://github.com/oscarlab/graphene/blob/2313f7097881c005d742beb60800b1e65cd98524/CONTRIBUTING.rst#L179)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No problem, but the 100 columns came from Emacs settings in `.dir-locals.el`. I updated the settings and reformatted the few offending lines in this file.
</blockquote></details>

Nice catch! We don't have too many Emacs users, so this went unnoticed for quite some time :)


<!-- Sent from Reviewable.io -->

2020-10-13 06:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-13 09:49 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`setrlimit` LTP test failed)

2020-10-13 10:46 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-13 11:57 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1881)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-13 11:58 UTC, merged