[LibOS] Use correct v5.8 x86 syscall numbers
oscarlab/graphene pull request #1882
Opened 2020-10-10 23:43 UTC by jurobystricky

When compiling against v5.8 (or later) kernel headers, we encounter
compilation errors such as:

  In file included from /usr/include/asm/unistd.h:13,
                   from shim_parser.c:11:
  shim_parser.c:408:10: error: array index in initializer exceeds array bounds
           [__NR_io_uring_setup]    = {.slow = 0, .parser = {NULL}},

The remedy is to extend "syscall_parser_table" by modyfing the
definition of LIBOS_SYSCALL_BOUND so the offending system calls fit in the table.

While at it, also fix the actual values for syscall numbers in "shim_syscalls.h"
(The numbers are not sequential, there is an intentional gap between the numers)

## Description of the changes 

## How to test this PR?

2020-10-11 14:33 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-11 17:10 UTC, mkow requested changes
My bad, seems I introduced this in #1838. Thanks for the fix!

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882#-:-MJNc7sS2pTOblSZNrVo:bssc3x0)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jurobystricky)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNbw76CBg8FsOTsSzr:-MJNbw76CBg8FsOTsSzs:b-212ev2) (no related file):*
Could you please add "Fixes #1878" to the description of this PR on GitHub?

---
___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJNcP0oCrsWQBnhq4Si:b16b2fo) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
> ```objc
> 
> #if defined(__i386__) || defined(__x86_64__)
> #define LIBOS_SYSCALL_BOUND (428) /* __NR_syscalls */
> ```

Parentheses aren't needed now. Also, maybe you could just include `shim_syscalls.h` and use `__NR_syscalls` here?


<!-- Sent from Reviewable.io -->

2020-10-11 21:27 UTC, jurobystricky commented
OK, I will create a new PR with the suggested changes. Thanks for the feedback.

2020-10-11 22:58 UTC, mkow reviewed
Hmm, why a new one? Why not to push fixes here?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882#-:-MJOsb-RCV_JPIxd_sML:b-9m5hbh)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jurobystricky)



<!-- Sent from Reviewable.io -->

2020-10-12 03:05 UTC, jurobystricky commented
> Hmm, why a new one? Why not to push fixes here?
> 
I force-pushed an updated patch...

2020-10-12 09:33 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jurobystricky)

___
*[LibOS/shim/src/Makefile, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJR8wYmEz5pN0QextTY:-MJR8wYn9ILyHnm07aaX:blk5g2d) ([raw file](https://github.com/oscarlab/graphene/blob/6f62fcb9cc6b835b17245f2e2c8b539488049f1d/LibOS/shim/src/Makefile#L29)):*
> ```Makefile
> CFLAGS += -Wno-address-of-packed-member
> 
> ASFLAGS += -Wa,--noexecstack -x assembler-with-cpp -I../include -I../include/arch/$(ARCH)
> ```

Why is this relevant here? What does it do?


<!-- Sent from Reviewable.io -->

2020-10-12 13:55 UTC, jurobystricky commented
> > Reviewed 2 of 2 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)_ status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jurobystricky)
> 
> _[LibOS/shim/src/Makefile, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJR8wYmEz5pN0QextTY:-MJR8wYn9ILyHnm07aaX:blk5g2d) ([raw file](https://github.com/oscarlab/graphene/blob/6f62fcb9cc6b835b17245f2e2c8b539488049f1d/LibOS/shim/src/Makefile#L29)):_
> 
> > ```makefile
> > CFLAGS += -Wno-address-of-packed-member
> > 
> > ASFLAGS += -Wa,--noexecstack -x assembler-with-cpp -I../include -I../include/arch/$(ARCH)
> > ```
> 
> Why is this relevant here? What does it do?


The ASFLAGS need include path adjustment in order to avoid the following error:

<pre>In file included from syscallas-x86_64.S:11:
../include/shim_defs.h:5:10: fatal error: shim_syscalls.h: No such file or directory
 #include "shim_syscalls.h"
</pre>

CFLAGS already contain the above include path _-I../include/arch/$(ARCH)._ 
ASFLAGS also need this now: syscallas-x86_64.S needs to resolve $LIBOS_SYSCALL_BOUND.

2020-10-12 14:24 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jurobystricky)



<!-- Sent from Reviewable.io -->

2020-10-12 18:29 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jurobystricky)



<!-- Sent from Reviewable.io -->

2020-10-12 22:23 UTC, jurobystricky reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNbw76CBg8FsOTsSzr:-MJTt65mABZFUHMwUfzk:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you please add "Fixes #1878" to the description of this PR on GitHub?
</blockquote></details>

Done.

---
___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJTu-bY7USNOt80GFQM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Parentheses aren't needed now. Also, maybe you could just include `shim_syscalls.h` and use `__NR_syscalls` here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-12 22:25 UTC, jurobystricky reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-12 23:16 UTC, mkow requested changes
Thanks.

btw. We prefer fixup commits - see our contribution guidelines: https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882#-:-MJU4WD54D4bcmcFIamN:bi72s2b)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jurobystricky)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNbw76CBg8FsOTsSzr:-MJU4H-eA6ee-BxCffti:bfejutm) (no related file):*
<details><summary><i>Previously, jurobystricky wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant the PR description on GitHub, not commit message. Anyways, I updated it for you.

---
___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJU54iU5T0FcqN404s3:bajpcqd) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, jurobystricky wrote…</i></summary><blockquote>

Done.
</blockquote></details>

these `#ifdefs` aren't needed anymore here and above - `shim_syscalls.h` is already architecture-specific itself (see how you added its path to the Makefile)


<!-- Sent from Reviewable.io -->

2020-10-12 23:23 UTC, jurobystricky reviewed
My bad, old habits...

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882#-:-MJU6RHs3s-mRbjGt73z:b7y2ka4)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNbw76CBg8FsOTsSzr:-MJU6ZC51HUcA1AnZ5ya:b-zcjvte) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I meant the PR description on GitHub, not commit message. Anyways, I updated it for you.
</blockquote></details>

Thanks

---
___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJU6j_16byvoXdEVWCr:bt9gyj5) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

these `#ifdefs` aren't needed anymore here and above - `shim_syscalls.h` is already architecture-specific itself (see how you added its path to the Makefile)
</blockquote></details>

Did not want to remove the original code, did not want to be more invasive than necessary...


<!-- Sent from Reviewable.io -->

2020-10-12 23:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jurobystricky)

___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJUA5KG2Iw-uA61KUvg:bjtxznd) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, jurobystricky wrote…</i></summary><blockquote>

Did not want to remove the original code, did not want to be more invasive than necessary...
</blockquote></details>

That's not too invasive. Even if, invasive changes are good if they improve the code, like in this case ;)


<!-- Sent from Reviewable.io -->

2020-10-12 23:41 UTC, jurobystricky reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJUAeHwBwwCCgIHEvt4:be2j2pt) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's not too invasive. Even if, invasive changes are good if they improve the code, like in this case ;)
</blockquote></details>

Ok, so should I force push the existing/modified PR with #ifdef removed? Or should I just create an additional PR with #ifdef removed?


<!-- Sent from Reviewable.io -->

2020-10-12 23:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jurobystricky)

___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJUCWEj-P-w6t4CgRaT:bbpqgj6) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, jurobystricky wrote…</i></summary><blockquote>

Ok, so should I force push the existing/modified PR with #ifdef removed? Or should I just create an additional PR with #ifdef removed?
</blockquote></details>

No, you should create a fixup commit (using `git commit --fixup`) with the fixes for your initial commit and push (_without_ `--force-with-lease`) to your branch, and then mark this discussion as "done" in Reviewable.
We'll squash all the fixups before merging. During review it's better to keep them separate, so you can see the history of changes to the PR during review.


<!-- Sent from Reviewable.io -->

2020-10-12 23:56 UTC, jurobystricky reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJUE2gh8bdcD6ilsPAp:bppsk9x) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, you should create a fixup commit (using `git commit --fixup`) with the fixes for your initial commit and push (_without_ `--force-with-lease`) to your branch, and then mark this discussion as "done" in Reviewable.
We'll squash all the fixups before merging. During review it's better to keep them separate, so you can see the history of changes to the PR during review.
</blockquote></details>

Thanks. Got it. Will do today (PST).


<!-- Sent from Reviewable.io -->

2020-10-13 00:33 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_defs.h, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/1882#-MJNcP0n0FV172c7jWlp:-MJUMyxl7_FFqa0K3cRS:by2s728) ([raw file](https://github.com/oscarlab/graphene/blob/293eec793dcebf690a4d48104b2816bdd39dca21/LibOS/shim/include/shim_defs.h#L22)):*
<details><summary><i>Previously, jurobystricky wrote…</i></summary><blockquote>

Thanks. Got it. Will do today (PST).
</blockquote></details>

Looks good now, thanks!


<!-- Sent from Reviewable.io -->

2020-10-13 01:16 UTC, mkow commented
Jenkins, test this please

2020-10-13 01:17 UTC, mkow commented
Oops, sorry, I incorrectly rebased it. Let me fix this...

2020-10-13 01:21 UTC, mkow approved these changes
Ok, should be fine now. We'll merge it next, after Jenkins' approval.
I must have used [TAB] too much when doing the previous rebase :)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882#-:-MJUXgWS1W_ww_uctdCU:bds2ta5)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-13 01:22 UTC, mkow commented
Jenkins, test this please

2020-10-13 01:34 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-13 06:42 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1882)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-13 06:45 UTC, merged