[test] allow skipping LTP tests by fnmatch
oscarlab/graphene pull request #1886
Opened 2020-10-13 18:16 UTC by pwmarcz

From now you can write * into section names in ltp.cfg, but such
sections can only contain "skip".

This is in order to make the configuration file more usable: in
many cases, we want to skip a whole class of tests, because a given
feature/syscall is not supported by Graphene.

Two such groups are "collapsed" as a proof of concept. A more thorough cleanup of LTP configuration will follow later.

2020-10-13 18:17 UTC, pwmarcz commented
Based on https://github.com/oscarlab/graphene/pull/1885, updated:

* Missing import etc.
* Modified to match only against wildcard patterns (otherwise it tries to compare every test name to every section name, and my laptop gets pretty noisy).
* Fixed the `for key in proxy` verification (the dictionary includes all the keys from defaults).
* Added a skip for two groups of tests, as a proof-of-concept.
* (ValueError, not Error, because it's not an abnormal test result but a configuration error. And the Error class doesn't display a message).

2020-10-13 18:42 UTC, woju submitted a review, later dismissed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-13 19:13 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 313 at r1](https://reviewable.io/reviews/oscarlab/graphene/1886#-MJYLxPj-b2qFQtVprwJ:-MJYLxPkEXcR1e6yEGUG:b-u8t5gy) ([raw file](https://github.com/oscarlab/graphene/blob/80516fd9eab96b4fad6e0fe0abcdd414d16e6633/LibOS/shim/test/ltp/ltp.cfg#L313)):*
> ```INI
> skip = yes
> 
> [fanotify*]
> ```

Could you add a comment here and above that this syscall is not implemented? (same as you did with the SGX version)


<!-- Sent from Reviewable.io -->

2020-10-14 05:46 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-10-14 05:48 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`fork11` LTP test failed -- it fails frequently these days, need to debug)

2020-10-14 12:16 UTC, yamahata approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-10-14 12:29 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @woju, and @yamahata)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 313 at r1](https://reviewable.io/reviews/oscarlab/graphene/1886#-MJYLxPj-b2qFQtVprwJ:-MJb4OxB43klXSSCXGKs:biw8y1v) ([raw file](https://github.com/oscarlab/graphene/blob/80516fd9eab96b4fad6e0fe0abcdd414d16e6633/LibOS/shim/test/ltp/ltp.cfg#L313)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a comment here and above that this syscall is not implemented? (same as you did with the SGX version)
</blockquote></details>

Right. Done.


<!-- Sent from Reviewable.io -->

2020-10-14 12:43 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-14 13:12 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-10-14 16:35 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-14 20:46 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-14 21:59 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-14 22:01 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1886)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-14 22:02 UTC, merged