Move manifest syntax to TOML
oscarlab/graphene pull request #1892
Opened 2020-10-15 15:25 UTC by dimakuv

## Description of the changes 

**DRAFT**.

Current commits:
- Port tomlc99 library for manifests in TOML syntax. The tomlc99 library is embedded in Graphene as slightly modified toml.c and toml.h source files. The original license is MIT, the author is CK Tan (cktan), used commit ddb9cc4eeb (Sep 22, 2020).

Needs to be rebased on top of https://github.com/oscarlab/graphene/pull/1888.

## How to test this PR? 

All manifests will be rewritten in TOML...

2020-10-15 23:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/lib/string/strspn.c, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/1892#-MJigdVn4sn54fwxubAD:-MJigdVn4sn54fwxubAE:bj9s7av) ([raw file](https://github.com/oscarlab/graphene/blob/ea9f70dd03461e99eef1730cea460abf4f9a2113/Pal/lib/string/strspn.c#L7)):*
> ```C
> 
> #define BITOP(a,b,op) \
>  ((a)[(size_t)(b)/(8*sizeof *(a))] op (size_t)1<<((size_t)(b)%(8*sizeof *(a))))
> ```

This was already merged to master, please rebase.
___
*[Pal/lib/toml/toml.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1892#-MJifx_F0-xnu9-LUiDI:-MJifx_F0-xnu9-LUiDJ:b-6hj1nx) ([raw file](https://github.com/oscarlab/graphene/blob/ea9f70dd03461e99eef1730cea460abf4f9a2113/Pal/lib/toml/toml.c#L1)):*
> ```C
> /* SPDX-License-Identifier: MIT */
> ```

Could we instead download the source and patch it? (same as we do with e.g. cJSON, but there we don't need patches)
Copy pasting sources has the following problems:
- Hard to update the dependency
- Hard to monitor if the dependency got outdated
- Annoying when grepping in our codebase


<!-- Sent from Reviewable.io -->

2020-10-16 06:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @woju, and @yamahata)

___
*[Pal/lib/toml/toml.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1892#-MJifx_F0-xnu9-LUiDI:-MJk64wCD8kvlQIzc5fA:b-93flm9) ([raw file](https://github.com/oscarlab/graphene/blob/ea9f70dd03461e99eef1730cea460abf4f9a2113/Pal/lib/toml/toml.c#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we instead download the source and patch it? (same as we do with e.g. cJSON, but there we don't need patches)
Copy pasting sources has the following problems:
- Hard to update the dependency
- Hard to monitor if the dependency got outdated
- Annoying when grepping in our codebase
</blockquote></details>

Adding @boryspoplawski @yamahata @woju to this discussion.

I can switch to download-and-patch, but here are some objections:
1. The `tomlc99` library is not amazingly well maintained. It has good code, but there are no tags or revisions. I won't be surprised if this repo stops being maintained. (And this is the only good C implementation I found.)
2. I consider this more of a starting point rather than a hard dependency. The code is self-contained and pretty clear. This code supports TOML v1.0 and I don't see how it will change much (especially for our limited Graphene scenarios). If there are some bugs found in the original repo, they won't be significant.
3. The original code has a really cumbersome pattern of setjmp/longjmp and totally messed up error handling/cleanup. From what I understand, this was the idea of the author. (Most of my changes are fixing return values and propagating errors.) It may be hard to convince the author we should get rid of setjmp/longjmp simply because one particular framework doesn't support it.
4. Most of my other changes to the original source code are removing Glibc dependencies. Recall that for manifests, we can use only a limited subset of string/stdlib functions. In particular, I removed `realloc()` from the source code.
5. Formatting is quite different. Too many things to patch. Tabs vs spaces, etc. Just didn't feel right to download-and-patch.

I can go either way. To have an idea how much I changed, see my fork: https://github.com/dimakuv/tomlc99/commits/master. For the formatting and the general feeling for the original library, see https://github.com/cktan/tomlc99.


<!-- Sent from Reviewable.io -->

2020-10-16 09:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 0 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, @woju, and @yamahata)

___
*[Pal/lib/string/strspn.c, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/1892#-MJigdVn4sn54fwxubAD:-MJkfGWE9EVYjumBWzB4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ea9f70dd03461e99eef1730cea460abf4f9a2113/Pal/lib/string/strspn.c#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This was already merged to master, please rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-16 13:49 UTC, mkow reviewed
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 0 of 7 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/lib/toml/toml.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1892#-MJifx_F0-xnu9-LUiDI:-MJleiTm0qhIFBFPxS99:b-2smjf2) ([raw file](https://github.com/oscarlab/graphene/blob/ea9f70dd03461e99eef1730cea460abf4f9a2113/Pal/lib/toml/toml.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Adding @boryspoplawski @yamahata @woju to this discussion.

I can switch to download-and-patch, but here are some objections:
1. The `tomlc99` library is not amazingly well maintained. It has good code, but there are no tags or revisions. I won't be surprised if this repo stops being maintained. (And this is the only good C implementation I found.)
2. I consider this more of a starting point rather than a hard dependency. The code is self-contained and pretty clear. This code supports TOML v1.0 and I don't see how it will change much (especially for our limited Graphene scenarios). If there are some bugs found in the original repo, they won't be significant.
3. The original code has a really cumbersome pattern of setjmp/longjmp and totally messed up error handling/cleanup. From what I understand, this was the idea of the author. (Most of my changes are fixing return values and propagating errors.) It may be hard to convince the author we should get rid of setjmp/longjmp simply because one particular framework doesn't support it.
4. Most of my other changes to the original source code are removing Glibc dependencies. Recall that for manifests, we can use only a limited subset of string/stdlib functions. In particular, I removed `realloc()` from the source code.
5. Formatting is quite different. Too many things to patch. Tabs vs spaces, etc. Just didn't feel right to download-and-patch.

I can go either way. To have an idea how much I changed, see my fork: https://github.com/dimakuv/tomlc99/commits/master. For the formatting and the general feeling for the original library, see https://github.com/cktan/tomlc99.
</blockquote></details>

Ok, sounds like good arguments to keep it here. Could you move the argumentation to a comment in this file? Will be useful if this discussion reappears someday.


<!-- Sent from Reviewable.io -->

2020-10-16 13:50 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @yamahata)

___
*[Pal/lib/toml/toml.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1892#-MJifx_F0-xnu9-LUiDI:-MJlczK74tv_jrsmPVGR:b-3lcyp8) ([raw file](https://github.com/oscarlab/graphene/blob/ea9f70dd03461e99eef1730cea460abf4f9a2113/Pal/lib/toml/toml.c#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, sounds like good arguments to keep it here. Could you move the argumentation to a comment in this file? Will be useful if this discussion reappears someday.
</blockquote></details>

At least some of those patches seem upstreamable, and upstream seems generally receptive. I understand they might not want to merge longjump removal, in that case the optimal thing would be to maintain a friendly fork, possibly renamed (tomlcembedded?) and under our common organisation in github.


<!-- Sent from Reviewable.io -->

2020-10-29 15:42 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 0 of 132 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[Pal/lib/toml/toml.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1892#-MJifx_F0-xnu9-LUiDI:-MKp0CBW1PaaLDcry6sU:bkusk3a) ([raw file](https://github.com/oscarlab/graphene/blob/ea9f70dd03461e99eef1730cea460abf4f9a2113/Pal/lib/toml/toml.c#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

At least some of those patches seem upstreamable, and upstream seems generally receptive. I understand they might not want to merge longjump removal, in that case the optimal thing would be to maintain a friendly fork, possibly renamed (tomlcembedded?) and under our common organisation in github.
</blockquote></details>

Done. CKTan (the maintainer of tomlc99 library) was very responsive and quickly merged our proposed changes to the master branch. So now we simply download the TOML parser: https://github.com/oscarlab/graphene/pull/1930.


<!-- Sent from Reviewable.io -->

2020-11-05 12:43 UTC, dimakuv commented
Jenkins, retest Jenkins please (`setrlimit01` LTP test failed, unrelated)

2020-11-05 20:07 UTC, mkow requested changes
> Reviewed 1 of 7 files at r1, 123 of 123 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNVISM1efvvkwo9jWe:-MLNVISM1efvvkwo9jWf:b5ervn5) (no related file):*
Please also update our docs (there are a lot of places with manifest snippets there)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOK7KQ2CQOJzB8qbB-:-MLOK7KR2bnGeD0JuHAE:bxyytqg) (no related file):*
Please add "Fixes" for #174 and #870.

---
___
*[LibOS/shim/src/shim_init.c, line 288 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNXybT62mgTWP62ltH:-MLNXybT62mgTWP62ltI:b-r89bam) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L288)):*
> ```C
>         if (manifest_sys_stack) {
>             toml_raw_t sys_stack_size_raw = toml_raw_in(manifest_sys_stack, "size");
>             if (sys_stack_size_raw) {
> ```

Could we add a helper to fold such `if` cascades? E.g. where you could pass "sys.stack.size" string and it would return NULL/toml_raw_t. Maybe you could introduce a small Graphene-specific library on top of TOML parser which implements such helpers? This whole PR is insanely repetitive.
___
*[LibOS/shim/src/shim_init.c, line 291 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZfqd9LP5Bj3Y0VfY:-MLNZfqd9LP5Bj3Y0VfZ:b-59u3xp) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L291)):*
> ```C
>                 ret = toml_rtos(sys_stack_size_raw, &sys_stack_size_str);
>                 if (ret < 0) {
>                     debug("Cannot read \'sys.stack.size\' (it must be put in quotes!)\n");
> ```

`quotes` -> `double quotes`
`it` -> `the value` (otherwise the users may think it's about the key, because this is what you mention in this sentence)
___
*[LibOS/shim/src/shim_init.c, line 299 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNYaAh11UXHotNiv8e:-MLNYV2y4SxFxIT0K6TF:b2dk05r) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L299)):*
> ```C
> 
>     if (sys_stack_size_str) {
>         stack_size = ALLOC_ALIGN_UP(parse_size_str(sys_stack_size_str));
> ```

Could we add `toml_sizestr_in` or something similar? Would simplify a lot of our code.
___
*[LibOS/shim/src/shim_init.c, line 402 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZ-ko6YsA17_qhjMJ:-MLNZ-ko6YsA17_qhjMK:bi14scs) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L402)):*
> ```C
>     if (!g_manifest_root) {
>         debug("PAL failed at parsing the manifest: %s\n"
>                "Graphene switched to the TOML format, please update the manifest "
> ```

`Graphene switched to the TOML format` -> `Graphene switched to the TOML format recently`
___
*[LibOS/shim/src/shim_init.c, line 403 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZ32L6PpccSOLlRl5:-MLNZ32L6PpccSOLlRl6:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L403)):*
> ```C
>         debug("PAL failed at parsing the manifest: %s\n"
>                "Graphene switched to the TOML format, please update the manifest "
>                "(in particular, strings must be put in quotes)\n", errbuf);
> ```

ditto
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 235 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZcCd2-UXPsO5bA_j:-MLNZcCd2-UXPsO5bA_k:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/bookkeep/shim_thread.c#L235)):*
> ```C
>                 ret = toml_rtos(fs_start_dir_raw, &fs_start_dir);
>                 if (ret < 0) {
>                     debug("Cannot read \'fs.start_dir\' (it must be put in quotes!)\n");
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs.c, line 103 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOWBAv1WjDQFUlFlkM:-MLOWBAwBdrppSFEXSZ0:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L103)):*
> ```C
>                 ret = toml_rtos(fs_root_type_raw, &fs_root_type);
>                 if (ret < 0) {
>                     debug("Cannot read \'fs.root.type\' (it must be put in quotes!)\n");
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs.c, line 112 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOWH1b2Yqzlyn9qG7i:-MLOWH1b2Yqzlyn9qG7j:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L112)):*
> ```C
>                 ret = toml_rtos(fs_root_uri_raw, &fs_root_uri);
>                 if (ret < 0) {
>                     debug("Cannot read \'fs.root.uri\' (it must be put in quotes!)\n");
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs.c, line 169 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOZ83Q2BYuxSmGL48S:-MLOZ83Q2BYuxSmGL48T:b-nh3vqx) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L169)):*
> ```C
> 
> static int __mount_one_other(toml_table_t* mount) {
> 	assert(mount);
> ```

tab -> space
___
*[LibOS/shim/src/fs/shim_fs.c, line 198 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLO_rPl0f-POBerXVKh:-MLO_rPl0f-POBerXVKi:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L198)):*
> ```C
>     ret = toml_rtos(mount_type_raw, &mount_type);
>     if (ret < 0) {
>         debug("Cannot read \'fs.mount.%s.type\' (it must be put in quotes!)\n", key);
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs.c, line 204 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLO_sFV8o9z4WWwEze_:-MLO_sFV8o9z4WWwEzea:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L204)):*
> ```C
>     ret = toml_rtos(mount_path_raw, &mount_path);
>     if (ret < 0) {
>         debug("Cannot read \'fs.mount.%s.path\' (it must be put in quotes!)\n", key);
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs.c, line 210 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLO_svCCTeW9A-R9ajO:-MLO_svCCTeW9A-R9ajP:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L210)):*
> ```C
>     ret = toml_rtos(mount_uri_raw, &mount_uri);
>     if (ret < 0) {
>         debug("Cannot read \'fs.mount.%s.uri\' (it must be put in quotes!)\n", key);
> ```

ditto
___
*[LibOS/shim/src/sys/shim_brk.c, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLObK3BCAdQiSZ-_FuI:-MLObK3BCAdQiSZ-_FuJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/sys/shim_brk.c#L58)):*
> ```C
>                 ret = toml_rtos(sys_brk_max_size_raw, &sys_brk_max_size_str);
>                 if (ret < 0) {
>                     debug("Cannot read \'sys.brk.max_size\' (it must be put in quotes!)\n");
> ```

ditto
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOb_8f3cwky1kgHCBS:-MLOb_8g3fKkdl7_RMF3:bq20mi0) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/sys/shim_eventfd.c#L26)):*
> ```C
>     bool allow_eventfd = false;
> 
>     /* Reading sys.insecure__allow_eventfd from  [...]

2020-11-10 21:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 102 of 131 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNVISM1efvvkwo9jWe:-MLo-ata6iUgpEYwHcxo:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also update our docs (there are a lot of places with manifest snippets there)
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/shim_init.c, line 288 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNXybT62mgTWP62ltH:-MLm1CTN42iLKHOhGHP9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L288)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we add a helper to fold such `if` cascades? E.g. where you could pass "sys.stack.size" string and it would return NULL/toml_raw_t. Maybe you could introduce a small Graphene-specific library on top of TOML parser which implements such helpers? This whole PR is insanely repetitive.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 291 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZfqd9LP5Bj3Y0VfY:-MLm1D-e6JCTwq02eVqK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L291)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`quotes` -> `double quotes`
`it` -> `the value` (otherwise the users may think it's about the key, because this is what you mention in this sentence)
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 299 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNYaAh11UXHotNiv8e:-MLm7w0j34IjOhwKzeLq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L299)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we add `toml_sizestr_in` or something similar? Would simplify a lot of our code.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 402 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZ-ko6YsA17_qhjMJ:-MLm80vV9aCUNrRsHAoJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L402)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Graphene switched to the TOML format` -> `Graphene switched to the TOML format recently`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 403 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZ32L6PpccSOLlRl5:-MLm8ATU9X3TY-aZjKu7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/shim_init.c#L403)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 235 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLNZcCd2-UXPsO5bA_j:-MLm8o4u004KyoJ5VtGp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/bookkeep/shim_thread.c#L235)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 103 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOWBAv1WjDQFUlFlkM:-MLm9Vv-B62RL9yUL9ew:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L103)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 112 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOWH1b2Yqzlyn9qG7i:-MLm9WX-EyOJAlSz1Wo9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 169 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOZ83Q2BYuxSmGL48S:-MLm9azU-pWBnu4uXCcO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L169)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

tab -> space
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 198 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLO_rPl0f-POBerXVKh:-MLmAEBLAHEo4wcBFeCK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L198)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 204 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLO_sFV8o9z4WWwEze_:-MLmAEeF9hrNMitIobXL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L204)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 210 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLO_svCCTeW9A-R9ajO:-MLmAF3I8yyHL0Q5vk1F:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/fs/shim_fs.c#L210)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_brk.c, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLObK3BCAdQiSZ-_FuI:-MLmB9YW80jDNMRpAOcG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/sys/shim_brk.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_eventfd.c, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOb_8f3cwky1kgHCBS:-MLmBldM9idN0QWZSbOI:bd771d4) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/LibOS/shim/src/sys/shim_eventfd.c#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Reading` -> `Read`
</blockquote></details>

Done. Removed comment.
___
*[Pal/include/lib/api.h, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLON8un6HAxkA-Cixew:-MLmCQ0C359r4npliMTd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/Pal/include/lib/api.h#L249)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please finally delete this :)
</blockquote></details>

Done.
___
*[Pal/lib/Makefile, line 163 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOd0PjEwVWlaB1XV7h:-MLmeUoZCRk4h-WjAU3l:b-b27tpy) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/Pal/lib/Makefile#L163)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If something fails after this line a repeated `make` will treat this target as bu [...]

2020-11-10 21:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 102 of 131 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOK7KQ2CQOJzB8qbB-:-MLo0ecg0RoePhCevm-_:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add "Fixes" for #174 and #870.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-11-11 19:45 UTC, mkow requested changes
> Reviewed 29 of 29 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 31 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsVIJv4nbIeLCPQPwy:-MLsVIJv4nbIeLCPQPwz:b6ume5f) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Documentation/manifest-syntax.rst#L31)):*
> ```reStructuredText
> ::
> 
>     loader.debug_type="[none|inline]"
> ```

while we're here, could you add spaces around `=` in all the snippets in the docs?
___
*[Pal/include/lib/api.h, line 264 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsYd6p80OJdLToptzS:-MLsYd6p80OJdLToptzT:bf575xf) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/include/lib/api.h#L264)):*
> ```objc
>  * \param root      Root table of the TOML manifest.
>  * \param key       Dotted key (e.g. "loader.insecure__use_cmdline_argv").
>  * \param defaulval `retval` is set to this value if not found in the manifest.
> ```

typo: `defaulval`
___
*[Pal/include/lib/api.h, line 289 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsYzNdDA7VykSDAsD3:-MLsYzNdDA7VykSDAsD4:bllnae0) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/include/lib/api.h#L289)):*
> ```objc
>  * \param root      Root table of the TOML manifest.
>  * \param key       Dotted key (e.g. "sys.stack.size").
>  * \param defaulval `retval` is set to this value if not found in the manifest.
> ```

ditto (typo)
___
*[Pal/lib/Makefile, line 163 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOd0PjEwVWlaB1XV7h:-MLs_doK8UJihG15YXz7:b-x2np1n) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/Pal/lib/Makefile#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Not sure I did it right...
</blockquote></details>

I'd prefer to download the source to toml_original.c and then patch it into toml.c.
Also, in the current version, if the second download fails, the target won't be re-tried on the next make (it creates toml.h which is not the target).
___
*[Pal/lib/string/toml_utils.c, line 38 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLscHPK8zc85A3ero1_:-MLscHPK8zc85A3ero1a:bbiagv5) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/lib/string/toml_utils.c#L38)):*
> ```C
>             goto out;
> 
>         *subkey_end = '.';
> ```

this isn't needed
___
*[Pal/src/host/Linux-SGX/db_main.c, line 377 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOpdh_CmPVd8eCynge:-MLsfGH_5lE8ULJqimyp:b-lpp3tx) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/Pal/src/host/Linux-SGX/db_main.c#L377)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I am also not an expert in English, but to me the current version sounds fine.
</blockquote></details>

Let's leave it as is then.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 404 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsfU4C7MCbV9q7osLq:-MLsfU4C7MCbV9q7osLr:byn8sge) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/src/host/Linux-SGX/db_main.c#L404)):*
> ```C
>     g_pal_state.manifest_root = manifest_root;
> 
>     ret = toml_sizestring_in(g_pal_state.manifest_root, "loader.pal_internal_mem_size", /*defaultval=*/0,
> ```

please rewrap
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 953 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLshBjj3NVTZc8VqyqP:-MLshBjj3NVTZc8VqyqQ:bfutn6j) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/src/host/Linux-SGX/enclave_framework.c#L953)):*
> ```C
> 
>     char* file_check_policy_str = NULL;
>     ret = toml_string_in(g_pal_state.manifest_root, "sgx.file_check_policy", &file_check_policy_str);
> ```

please wrap
___
*[Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py, line 43 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsp84L3BQC7_fF6jHX:-MLsp84L3BQC7_fF6jHY:bvyz7l5) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py#L43)):*
> ```Python
> 
> def parse_size(value):
>     if not value.startswith('"') or not value.endswith('"'):
> ```

Those checks accept value containing only a single `"` (ditto for all the changes below)


<!-- Sent from Reviewable.io -->

2020-11-12 10:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: 120 of 131 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 31 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsVIJv4nbIeLCPQPwy:-MLvn_SR6yOqU5hbnYdF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Documentation/manifest-syntax.rst#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

while we're here, could you add spaces around `=` in all the snippets in the docs?
</blockquote></details>

Done.
___
*[Pal/include/lib/api.h, line 264 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsYd6p80OJdLToptzS:-MLvnp1836EpRFdhYUqC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/include/lib/api.h#L264)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

typo: `defaulval`
</blockquote></details>

Done.
___
*[Pal/include/lib/api.h, line 289 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsYzNdDA7VykSDAsD3:-MLvnpaY03bUKyb1nIuU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/include/lib/api.h#L289)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (typo)
</blockquote></details>

Done.
___
*[Pal/lib/Makefile, line 163 at r3](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLOd0PjEwVWlaB1XV7h:-MLvy60M7lMkWvJtxhJ2:b-5wx69t) ([raw file](https://github.com/oscarlab/graphene/blob/a257f7e68722db02c6de57681deacb2ee00de668/Pal/lib/Makefile#L163)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to download the source to toml_original.c and then patch it into toml.c.
Also, in the current version, if the second download fails, the target won't be re-tried on the next make (it creates toml.h which is not the target).
</blockquote></details>

Partially done. I didn't find a way to patch using `patch -p1` such that `toml_original.c` would be renamed to `toml.c`. Seems like such stuff is not supported by `patch`. Also, moving `mv toml_original.c toml.c` looked ugly, so I stayed with the in-place patching of `toml.c/toml.h`.
___
*[Pal/lib/string/toml_utils.c, line 38 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLscHPK8zc85A3ero1_:-MLvnx28Ew6PE-geqkCF:b92qgvl) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/lib/string/toml_utils.c#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this isn't needed
</blockquote></details>

Done. Yes, I reverted the char back simply for sanity. But it's not needed.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 404 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsfU4C7MCbV9q7osLq:-MLvoAVg2ClYVJzj5WDg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/src/host/Linux-SGX/db_main.c#L404)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please rewrap
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 953 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLshBjj3NVTZc8VqyqP:-MLvoHhN3Z7Hx3tr0RGi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/src/host/Linux-SGX/enclave_framework.c#L953)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please wrap
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py, line 43 at r4](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLsp84L3BQC7_fF6jHX:-MLvqM5Y2zdZvn2fVyVu:b-sd4rdh) ([raw file](https://github.com/oscarlab/graphene/blob/2c1fdc467b5fe27fa0021a95ffa8f375d1c36959/Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Those checks accept value containing only a single `"` (ditto for all the changes below)
</blockquote></details>

Done. Behold my Python skills. (Just to reiterate: we should rewrite this whole script anew, it's really bad.)


<!-- Sent from Reviewable.io -->

2020-11-12 10:53 UTC, dimakuv commented
Jenkins, retest Jenkins please (`sigsuspend01` LTP test failed, known issue)

2020-11-12 13:44 UTC, mkow requested changes
> Reviewed 11 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/devel/performance.rst, line 381 at r5](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLwg6j_8zi_gjfd-C0l:-MLwg6ja32QyM05jiB22:b-zenkrj) ([raw file](https://github.com/oscarlab/graphene/blob/d41f0df02fc58dc7514e392c470dd9dce3effb32/Documentation/devel/performance.rst#L381)):*
> ```reStructuredText
> doesn't help, it could be due to insufficient stack size: in this case try to
> increase ``sys.stack.size = "256K"``, ``sys.stack.size = "2M"``,
> ``sys.stack.size = "4M"`` and so on.  Finally, if Graphene complains about
> ```

no double space (for consistency)


<!-- Sent from Reviewable.io -->

2020-11-12 13:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/devel/performance.rst, line 381 at r5](https://reviewable.io/reviews/oscarlab/graphene/1892#-MLwg6j_8zi_gjfd-C0l:-MLwjo7gAEZjhN7UlMyH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d41f0df02fc58dc7514e392c470dd9dce3effb32/Documentation/devel/performance.rst#L381)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no double space (for consistency)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 14:18 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1892)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-12 14:53 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04 please (`poll_closed_fd` LibOS test timed out, looks like one of Jenkins workers is dying)

2020-11-12 16:09 UTC, merged