WIP: LTP cleanup
oscarlab/graphene pull request #1906
Opened 2020-10-20 10:38 UTC by pwmarcz

This is a draft until I try things out on Jenkins.

2020-10-22 23:24 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @woju)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHYK3rD-XY4Rs_hvOj:-MKHYK3rD-XY4Rs_hvOk:b-a1tor9) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L5)):*
> ```INI
> 
> # Common problems:
> # - no FUNC() - feature (typicall syscall) not implemented
> ```

`typicall` -> `typically`
___
*[LibOS/shim/test/ltp/ltp.cfg, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHZB7N7fd6MrVa_2Ca:-MKHZB7N7fd6MrVa_2Cb:b-x1vw2o) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L142)):*
> ```INI
> 
> # 1. nanosleep with tv_nsec = -1 succeeds instead of failing with EINVAL (TODO)
> # 2. nanosleep with tv_nsec = 1e9 succeeds instead of failing with EINVAL (TODO)
> ```

Why "TODO"? A lot of other issues listed here are also "TODO", but aren't marked as such. I'd just skip these annotations.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKH_gyL1j5lxMag3Bp3:-MKH_gyL1j5lxMag3Bp4:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L272)):*
> ```INI
> skip = yes
> 
> # 5. exec on a "fake" file with no execute permission, Graphene tries to execute it anyway (TODO)
> ```

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 400 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKH_shNBy2HIOOavxJN:-MKH_shNBy2HIOOavxJO:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L400)):*
> ```INI
> skip = yes
> 
> # tries to F_DUPFD until limit is reached, hangs in shim_getrlimit (TODO)
> ```

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 598 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHaBKwB5sj-sPrMj1k:-MKHaBKwB5sj-sPrMj1l:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L598)):*
> ```INI
> skip = yes
> 
> # bad read from a shared FD? (TODO)
> ```

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 638 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHaPNn6Z_GfX9WDwyk:-MKHaPNo9jDoB8qFCViI:bymcvaj) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L638)):*
> ```INI
> # tries to mount a filesystem
> [fsync01]
> timeout = 60
> ```

I guess we can remove all timeout fields for tests which fail because of non-implemented features
___
*[LibOS/shim/test/ltp/ltp.cfg, line 645 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHafO30R_5piLDZLDX:-MKHafO30R_5piLDZLDY:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L645)):*
> ```INI
> skip = yes
> 
> # 2. fsync() on a pipe returns EROFS, not EINVAL (TODO)
> ```

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 762 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHau1RDsG1hjn_Qhny:-MKHau1RDsG1hjn_Qhnz:bnrckcq) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L762)):*
> ```INI
> timeout = 40
> 
> # fork()ed process has the same ppid as parent (TODO)
> ```

ditto
will probably get fixed by the current @boryspoplawski's work on threading rewrite
___
*[LibOS/shim/test/ltp/ltp.cfg, line 882 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHbSfm8kBxUlJ0ZANE:-MKHbSfm8kBxUlJ0ZANF:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L882)):*
> ```INI
> skip = yes
> 
> # SIGKILL, times out (TODO)
> ```

ditto
___
*[LibOS/shim/test/ltp/README.rst, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHWswH9b8tbAq5I3Bc:-MKHWswID3Yo6W-KUZHS:b-wrvb1d) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L20)):*
> ```reStructuredText
> - Enable debugging output: edit ``/install/testcases/bin/manifest`` to set
>   ``loader.debug_type = inline``. (Note that this you will need to revert this
>   change for ``make regression`` to work correctly).
> ```

caveat: this won't work for SGX, where you need to re-sign the enclave afterwards. Please mention this issue here.


<!-- Sent from Reviewable.io -->

2020-10-23 00:08 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @pwmarcz, and @woju)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHjMTQ9cIkMJpQJ5Ne:-MKHjMTQ9cIkMJpQJ5Nf:b-ut6iq8) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L594)):*
> ```INI
> skip = yes
> 
> # forks 1000 times
> ```

Why is that a problem? Graphene fails in some specific way (or hangs)?
___
*[LibOS/shim/test/ltp/ltp.cfg, line 762 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHau1RDsG1hjn_Qhny:-MKHkBi62bZqyLikly11:bll3h79) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L762)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
will probably get fixed by the current @boryspoplawski's work on threading rewrite
</blockquote></details>

Should be, we will see (if that's the only issue Graphene has with this test).
___
*[LibOS/shim/test/ltp/README.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHlfdk2nITC59-Tcbt:-MKHlfdl8dA3Wa0dx5_8:b-6d3kjf) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L23)):*
> ```reStructuredText
> - Use GDB: ``.../pal_loader GDB [SGX] <TEST_BINARY>``
> 
> Both above options require Graphene to be compiled with ``DEBUG=1``.
> ```

Afaik that's not true, you can compile without `DEBUG` and Graphene will still print debug info.


<!-- Sent from Reviewable.io -->

2020-10-23 10:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @woju)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHYK3rD-XY4Rs_hvOj:-MKJv1d42Cqauwiy6pmP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`typicall` -> `typically`
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHZB7N7fd6MrVa_2Ca:-MKJvDOrA6KbAyguo1QQ:bmen3p) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L142)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why "TODO"? A lot of other issues listed here are also "TODO", but aren't marked as such. I'd just skip these annotations.
</blockquote></details>

I wanted to highlight the more actionable ones, but on second look, yeah, that's not a clear distinction. Removed.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKH_gyL1j5lxMag3Bp3:-MKJvXdo2dPHYUzEMSFy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L272)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 400 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKH_shNBy2HIOOavxJN:-MKJvYPe1m5nPXM4jM2H:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L400)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHjMTQ9cIkMJpQJ5Ne:-MKJvbCr6EGPmz7rgNZx:bu0jqts) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L594)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is that a problem? Graphene fails in some specific way (or hangs)?
</blockquote></details>

It timed out when I run the full test suite. I thought this is because it's slow, but now that I see it, it runs fine (about 4 seconds on my machine).

I'll unskip it, bump the timeout to 40 seconds, and we can see what happens.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 598 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHaBKwB5sj-sPrMj1k:-MKJxCNx8f6r_VWaG2-g:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L598)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 638 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHaPNn6Z_GfX9WDwyk:-MKJxD8W87WyyWmmhaMw:biw8y1v) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L638)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess we can remove all timeout fields for tests which fail because of non-implemented features
</blockquote></details>

Right. Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 645 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHafO30R_5piLDZLDX:-MKJxOoJEOq8cACSBExl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L645)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 762 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHau1RDsG1hjn_Qhny:-MKJxRWS1XL6ear2qaXt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L762)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Should be, we will see (if that's the only issue Graphene has with this test).
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 882 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHbSfm8kBxUlJ0ZANE:-MKJxS1vAq7CxiB07ozY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L882)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/README.rst, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHWswH9b8tbAq5I3Bc:-MKJuRbBBI3R32fse1Yq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

caveat: this won't work for SGX, where you need to re-sign the enclave afterwards. Please mention this issue here.
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/README.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHlfdk2nITC59-Tcbt:-MKJuT2GDjDnhlBsJ-IF:b-x2x0mi) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Afaik that's not true, you can compile without `DEBUG` and Graphene will still print debug info.
</blockquote></details>

Updated. I also mentioned that LTP should be compiled with ``DEBUG``.


<!-- Sent from Reviewable.io -->

2020-10-23 10:20 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: 5 of 7 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[LibOS/shim/test/ltp/README.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHlfdk2nITC59-Tcbt:-MKJyH1SBqFTDYPUajVJ:b-ejc0np) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L23)):*
> I also mentioned that LTP should be compiled with `DEBUG`

Oh, that's actually not true. So I'm just moving the mention about `DEBUG` to the second bullet point.


<!-- Sent from Reviewable.io -->

2020-10-23 10:39 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKK1Snx6D7ZtO_cV2Y-:-MKK1Sny9HmfvQIrXVQt:b-2wld2z) (no related file):*
To whoever will be merging this: Let's run this ~5 times on Jenkins to verify that the newly enabled tests/timeouts are stable.

---


<!-- Sent from Reviewable.io -->

2020-10-23 12:16 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKK1Snx6D7ZtO_cV2Y-:-MKKNZXk3FaqgRjBHXGF:bm97ksh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

To whoever will be merging this: Let's run this ~5 times on Jenkins to verify that the newly enabled tests/timeouts are stable.
</blockquote></details>

The [graphene-sgx-apps](https://leeroy.cs.unc.edu/job/graphene-sgx-apps/2144/console) build failed with:

```
Building glibc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see "glibc-build/build.log" for more information.
(CC=gcc CXX=g++ AS=gcc make -C glibc-build 2>&1 > build.log) && touch glibc-build/Build.success
sed: -e expression #1, char 96: unknown option to `s'
rtld-Rules:40: *** This makefile is a subroutine of elf/Makefile not to be used directly.  Stop.
make[4]: *** [/home/jenkins/workspace/graphene-sgx-apps@2/LibOS/glibc-build/elf/rtld-libc.a] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [elf/subdir_lib] Error 2
make[2]: *** [all] Error 2
Makefile:63: recipe for target 'glibc-build/Build.success' failed
make[1]: *** [glibc-build/Build.success] Error 2
make[1]: Leaving directory '/home/jenkins/workspace/graphene-sgx-apps@2/LibOS'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```

Probably not my fault, but anyway, looks pretty weird.

---
___
*[LibOS/shim/test/ltp/ltp.cfg, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHjMTQ9cIkMJpQJ5Ne:-MKKNMFY9xq_kgSHAKcK:b-8qrdu9) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/ltp.cfg#L594)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It timed out when I run the full test suite. I thought this is because it's slow, but now that I see it, it runs fine (about 4 seconds on my machine).

I'll unskip it, bump the timeout to 40 seconds, and we can see what happens.
</blockquote></details>

Okay, this time both `fork06` and `fork07` timed out. Since the goal here is to clean up the configuration, not fix the tests, I will skip them both.


<!-- Sent from Reviewable.io -->

2020-10-23 13:49 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @woju)

___
*[LibOS/shim/test/ltp/README.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHlfdk2nITC59-Tcbt:-MKKhUsg1ZOLf_zGxPQf:b2n17fh) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L23)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

> I also mentioned that LTP should be compiled with `DEBUG`

Oh, that's actually not true. So I'm just moving the mention about `DEBUG` to the second bullet point.
</blockquote></details>

Kind of nitpicking, but: I would reword this sentence. You don't need Grephene with `DEBUG` to use gdb, although that greatly eases things ;)


<!-- Sent from Reviewable.io -->

2020-10-23 18:41 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: 6 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKK1Snx6D7ZtO_cV2Y-:-MKLjS8X7ZETw_Q0wAVs:b-pnh9br) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The [graphene-sgx-apps](https://leeroy.cs.unc.edu/job/graphene-sgx-apps/2144/console) build failed with:

```
Building glibc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see "glibc-build/build.log" for more information.
(CC=gcc CXX=g++ AS=gcc make -C glibc-build 2>&1 > build.log) && touch glibc-build/Build.success
sed: -e expression #1, char 96: unknown option to `s'
rtld-Rules:40: *** This makefile is a subroutine of elf/Makefile not to be used directly.  Stop.
make[4]: *** [/home/jenkins/workspace/graphene-sgx-apps@2/LibOS/glibc-build/elf/rtld-libc.a] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [elf/subdir_lib] Error 2
make[2]: *** [all] Error 2
Makefile:63: recipe for target 'glibc-build/Build.success' failed
make[1]: *** [glibc-build/Build.success] Error 2
make[1]: Leaving directory '/home/jenkins/workspace/graphene-sgx-apps@2/LibOS'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```

Probably not my fault, but anyway, looks pretty weird.
</blockquote></details>

Another build failed on a [random timeout of setrlimit01](https://leeroy.cs.unc.edu/job/graphene-18.04/3793/). I'm not sure how that happened. Maybe it would be better to reduce parallelism for these tests in general?

---
___
*[LibOS/shim/test/ltp/README.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHlfdk2nITC59-Tcbt:-MKLkeed8DQbqEwWLNAT:b-6nys2q) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Kind of nitpicking, but: I would reword this sentence. You don't need Grephene with `DEBUG` to use gdb, although that greatly eases things ;)
</blockquote></details>

Ok, how about now? Or feel free to suggest better wording :)


<!-- Sent from Reviewable.io -->

2020-10-26 23:49 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKK1Snx6D7ZtO_cV2Y-:-MKbI0S8DDm75Z4_dJYF:bw67ua2) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Another build failed on a [random timeout of setrlimit01](https://leeroy.cs.unc.edu/job/graphene-18.04/3793/). I'm not sure how that happened. Maybe it would be better to reduce parallelism for these tests in general?
</blockquote></details>

I think I saw this timeout before, looks unrelated to this PR. Anyways, I'll do a few more CI runs now.

---


<!-- Sent from Reviewable.io -->

2020-10-26 23:49 UTC, mkow commented
Jenkins, retest this please (run 1/5)

2020-10-27 01:09 UTC, mkow commented
Jenkins, retest this please (run 2/5, previous run: `apps.LTP.setrlimit01` timed out on Jenkins-18.04 + `sed: -e expression #1, char 96: unknown option to 's'` when building glibc on Jenkins-SGX-apps on slave-leeroy, broken Jenkins?)

2020-10-28 11:23 UTC, dimakuv requested changes
> Reviewed 5 of 7 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKiwYWe-k2eEweze8qr:-MKiwYWe-k2eEweze8qs:b2gmokq) (no related file):*
Awesome work regarding reasons of LTP failures! Thanks!

---
___
*[LibOS/shim/test/ltp/README.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHlfdk2nITC59-Tcbt:-MKiw-YgCA6yLGw-IjkW:b-p9gvfx) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L23)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Ok, how about now? Or feel free to suggest better wording :)
</blockquote></details>

What are these three dots?
___
*[LibOS/shim/test/ltp/README.rst, line 78 at r4](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKiwOi_-J_jATUq2EJY:-MKiwOi_-J_jATUq2EJZ:bj0ku76) ([raw file](https://github.com/oscarlab/graphene/blob/ea9deada2ac3f31bd7b5457fbc98ef556e70951c/LibOS/shim/test/ltp/README.rst#L78)):*
> ```reStructuredText
> In SGX mode, we use additional files: ``ltp-sgx.cfg``, and (temporarily)
> ``ltp-bug-1075.cfg``. These function as an override for ``ltp.cfg``, so that
> configuration is not duplicated.
> ```

There is no mention of `conf_substract.py` helper script. Would you like to add a section about it in README?


<!-- Sent from Reviewable.io -->

2020-10-28 11:36 UTC, mkow commented
Jenkins, retest this please (run 3/5, previous run successful)

2020-10-28 12:57 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKjGOCz1f3_xJokn8qB:-MKjGOD-C4dtzKjRe3HK:b14h2gt) (no related file):*
> I went through about 30% of LTP failures and documented them.
Optimally this should be documented as github issues (either bugs or feature requests, probably each case would be different) and cross-referenced. I understand this would be quite much work, so not blocking on this.

Otherwise LGTM.

---


<!-- Sent from Reviewable.io -->

2020-10-28 13:39 UTC, mkow commented
Jenkins, retest this please (run 4/5, previous run successful)

2020-10-28 13:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKjGOCz1f3_xJokn8qB:-MKjQuWp3K5PSg-SRY75:b-w62bzs) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> I went through about 30% of LTP failures and documented them.
Optimally this should be documented as github issues (either bugs or feature requests, probably each case would be different) and cross-referenced. I understand this would be quite much work, so not blocking on this.

Otherwise LGTM.
</blockquote></details>

I wouldn't add any feature requests based on LTP alone, we rather implement functionalities based on demand in real world apps and for most of the syscalls there are no plans atm to implement them.

---


<!-- Sent from Reviewable.io -->

2020-10-28 14:27 UTC, mkow commented
Jenkins, retest this please (run 5/5, previous run successful)

2020-10-28 15:05 UTC, yamahata approved these changes
> Reviewed 5 of 7 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-10-28 16:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: 6 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKjGOCz1f3_xJokn8qB:-MKjxOxT407Wum8a83fQ:b8x5wwy) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wouldn't add any feature requests based on LTP alone, we rather implement functionalities based on demand in real world apps and for most of the syscalls there are no plans atm to implement them.
</blockquote></details>

Yeah... it's just that there are too many of them, and it would require some more time to investigate before opening an issue. So I'm including this as a starting point for whoever needs to go deeper.

---
___
*[LibOS/shim/test/ltp/README.rst, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKHlfdk2nITC59-Tcbt:-MKjsnKm9-vYyb1Ydntr:bvowyhy) ([raw file](https://github.com/oscarlab/graphene/blob/322824d740eba9c4793de3bf8d5d39f2e418a280/LibOS/shim/test/ltp/README.rst#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What are these three dots?
</blockquote></details>

I meant "`pal_loader`, wherever it's located", but it's actually in the same directory. Changed to `./pal_loader`.
___
*[LibOS/shim/test/ltp/README.rst, line 78 at r4](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKiwOi_-J_jATUq2EJY:-MKjsyh05whEoZvfmUqJ:b-ll6fsx) ([raw file](https://github.com/oscarlab/graphene/blob/ea9deada2ac3f31bd7b5457fbc98ef556e70951c/LibOS/shim/test/ltp/README.rst#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no mention of `conf_substract.py` helper script. Would you like to add a section about it in README?
</blockquote></details>

Well, it was a one-off, included only "just in case". But I guess it wouldn't hurt to explain.

I added a short explanation for all the scripts in `contrib/` (as far as I understand them! For clarification I would ask @woju. :) )


<!-- Sent from Reviewable.io -->

2020-10-28 16:29 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKK1Snx6D7ZtO_cV2Y-:-MKjy31C5X5UPPH4Uz8W:b-9qjuz1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think I saw this timeout before, looks unrelated to this PR. Anyways, I'll do a few more CI runs now.
</blockquote></details>

Ok, 5 runs passed, only 1 failed on some issues which look like Jenkins instability. I'm resolving this thread then.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1906#-MKjGOCz1f3_xJokn8qB:-MKjyFILBo_P6qNf-Ot0:bo25pzn) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah... it's just that there are too many of them, and it would require some more time to investigate before opening an issue. So I'm including this as a starting point for whoever needs to go deeper.
</blockquote></details>

Sounds good to me. Also, before spamming with issues in the future, I'd first fix all the trivial failures (there are a lot of low hanging fruits here, no need to have a separate issue for each one).

---


<!-- Sent from Reviewable.io -->

2020-10-29 09:03 UTC, dimakuv commented
Jenkins, retest this please (GitHub didn't pick up previous Jenkins results)

2020-10-29 09:10 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-29 17:19 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-29 17:27 UTC, mkow commented
Jenkins, retest Jenkins-18.04 please (`apps.LTP.fork11` timed out, known issue)

2020-10-29 17:33 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1906)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-29 17:52 UTC, merged