[Pal/LibOS] Add `physical id` and fix `cpu cores` in `/proc/cpuinfo`
oscarlab/graphene pull request #1910
Opened 2020-10-21 04:09 UTC by vijaydhanraj

## Description of the changes 

Applications tend to use `/proc/cpuinfo` to get the `cpu cores` and `physical id` for computing the number of physical cores in a
socket. Currently `cpu cores` field is incorrectly implemented as it is set to the number of logical processors online and `physical id` isn't implemented. This patch addresses both of these issues.

For example, openVINO these fields in the following way to decide how many threads it should use for its inference engine.
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/inference_engine/os/lin/lin_system_conf.cpp#L24

## How to test this PR? 
We have `proc_common.c` regression test which already covers `/proc/cpuinfo`.

2020-10-21 11:43 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9qEiu6zxgNhr7xUEK:-MK9qEiv4icv3tRYKHRc:bqsbhv3) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L27)):*
> ```objc
> 
> #define PAL_LIBOS_TCB_SIZE 256
> #define PAL_MAX_CPU        1024
> ```

This constant is not architecture-dependent. Let's move it to `Pal/include/pal/pal.h`
___
*[Pal/src/host/Linux/db_main.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9qSiO946hLw7z9DQP:-MK9qSiO946hLw7z9DQQ:bjzadyd) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main.c#L276)):*
> ```C
>  * host without SMT support, /sys/devices/system/cpu/smt/active will return 0 (the actual value)
>  */
> int get_hw_res_count(const char *filename) {
> ```

The implementation of this function is wrong. Consider what happens if run on a single-cpu machine: your `/sys/devices/system/cpu/online` contains `0` (meaning there is one CPU with index 0). This will lead this function to return `0` (firstint). However, Graphene just wanted to know how many CPUs are there, so the correct return must be `1`.

I suggest to change this function as follows:
```
/* Opens a pseudo-file describing HW resources such as online CPUs and counts the number of HW resources
 * present in the file (if count == true) or simply reads the integer stored in the file (if count == false).
 * Returns -errno on failure. For example, calling this function on `/sys/devices/system/cpu/online` (with
 * complex formats like "1,3-5,6") will return 5, and calling this function on `/sys/devices/system/cpu/smt/active`
 * will return 1 (host supports SMT) or 0 (host doesn't support SMT). */
int get_hw_resource(const char *filename, bool count) {
   ... current logic of open and read ...
   if (!count) {
      /* caller wants to read an int stored in the file */
     int ret = strtol(buf, &end, 10);
     ... add error checking and return ret ...
   } else {
      ... current logic of reading the list and counting ...
   }
```
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9svBd6PiEwpqlF_r2:-MK9svBe-ZmIp7cd_VYa:b-z49b5h) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L78)):*
> ```C
> 
> int _DkGetCPUInfo(PAL_CPU_INFO* ci) {
>     char filename[128];
> ```

Please move this `filename` close to the actual place where you use it. (This is a preference in style, but I think it makes sense here: you only use `filename` once in that particular place.)
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9wuhw3zMrH950n7T1:-MK9wuhx4WzGpz40s5jc:bunsy1r) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L83)):*
> ```C
> 
>     const size_t VENDOR_ID_SIZE = 13;
>     char* vendor_id = malloc(VENDOR_ID_SIZE);
> ```

While we're here, can you add error checking `if (!vendor_id) {return -PAL_ERROR_NOMEM}`
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9x3Pd-3YNT8_MuWhh:-MK9x3Pd-3YNT8_MuWhi:b-n716h8) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L93)):*
> ```C
> 
>     const size_t BRAND_SIZE = 49;
>     char* brand = malloc(BRAND_SIZE);
> ```

While we're here, can you add error checking `if (!brand) {return -PAL_ERROR_NOMEM}`
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9tDrCCVF8iq4XJRlW:-MK9tDrCCVF8iq4XJRlX:b-bvji5h) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L107)):*
> ```C
>     if (cpu_num <= 0) {
>         rv = cpu_num;
>         goto out;
> ```

This goes wrong if `cpu_num == 0`. In this case, `rv == 0` and we jump to `out`, which returns `rv == 0` -- but this indicates "success"!

You should keep the old logic of `-PAL_ERROR_STREAMNOTEXIST` in the `get_hw_res_count()` function and don't check for `cpu_num == 0` here.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9taRM-HMRr8BP6mfR:-MK9taRM-HMRr8BP6mfS:b-17h68q) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L112)):*
> ```C
> 
>     /* we cannot use CPUID(0xb) because it counts even disabled-by-BIOS cores (e.g. HT cores);
>      * instead we extract info on number of cores by parsing sysfs pseudo-files */
> ```

Could you move this comment up to the first `get_hw_res_count()`? It doesn't make sense here, in the middle of using sysfs files.

Also, update `extract info on number of cores ...` -> `extract info on total number of logical processors, number of physical cores, SMT support, etc. ...`
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9tyX_2gZ1kHfSJ5HM:-MK9tyXaC_MsSZNlwhGp:b-tw1mfl) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L116)):*
> ```C
>     if (cpu_cores <= 0) {
>         rv = cpu_cores;
>         goto out;
> ```

ditto (`== 0` is wrong)
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 124 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9uHMp2w3qKBmsKEUb:-MK9uHMp2w3qKBmsKEUc:b-7ts4du) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L124)):*
> ```C
>         goto out;
>     }
>     /* This code assumes there are only 2 HTs per core but platforms like KNL can have more */
> ```

Please prepend with`FIXME: `. Also decipher what KNL is (Knights Landing).
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 168 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9ultiBFWUke-IvLlL:-MK9ultiBFWUke-IvLlM:bcfowzs) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L168)):*
> ```C
> 
>     /* Extract physical id for /proc/cpuinfo */
>     int phy_id = 0;
> ```

Remove this declaration from here, it's just a temporary variable that you can declare inside the for loop directly.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9ub8eCZm_lgQwh4gz:-MK9ub8eCZm_lgQwh4h-:b-qg8jm0) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L169)):*
> ```C
>     /* Extract physical id for /proc/cpuinfo */
>     int phy_id = 0;
>     for (int idx =0; idx < cpu_num; idx++) {
> ```

`idx =0` -> `idx = 0`
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9v-oGDXnjk5XF-0Dp:-MK9v-oGDXnjk5XF-0Dq:b-buatlf) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L171)):*
> ```C
>     for (int idx =0; idx < cpu_num; idx++) {
>         snprintf(filename, sizeof(filename),
>                  "/sys/devices/system/cpu/cpu%d/topology/physical_package_id", idx);
> ```

This goes wrong if some CPUs are offline. Say the host has SMT, 4 CPUs (2 physical cores), and [...]

2020-10-22 16:51 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKGC90qA69tyFV-46y7:-MKGC90qA69tyFV-46y8:b4fx6mx) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L27)):*
> ```
> 1024
> ```

How did you come up with this value?
Based on Linux kconfig(arch/x86/Kconfig), it's 1, 2, 8, 32, 64, 512, 8192.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 193 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKGCVqU1nlW7PkZlgbj:-MKGCVqU1nlW7PkZlgbk:b-drinfa) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L193)):*
> ```objc
>     PAL_NUM cpu_num;
>     PAL_NUM cpu_cores;
>     PAL_NUM phy_id[PAL_MAX_CPU];
> ```

This bumps the size of PAL_CPU_INFO. dynamic allocation?


<!-- Sent from Reviewable.io -->

2020-10-26 05:17 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: 0 of 9 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9qEiu6zxgNhr7xUEK:-MKWRCia4pQJVCYrF-0K:b-38d1u6) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This constant is not architecture-dependent. Let's move it to `Pal/include/pal/pal.h`
</blockquote></details>

Removed this #define and used dynamic allocation.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKGC90qA69tyFV-46y7:-MKWRK1O8YAejndzuIu-:b-ttkr9c) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L27)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> 1024
> ```

How did you come up with this value?
Based on Linux kconfig(arch/x86/Kconfig), it's 1, 2, 8, 32, 64, 512, 8192.

</blockquote></details>

Just random, big enough to fit most common platforms. But have removed the static allocation and implemented dynamic allocation.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 193 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKGCVqU1nlW7PkZlgbj:-MKWSr4Y5zC813_pYIxR:b27q08g) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L193)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

This bumps the size of PAL_CPU_INFO. dynamic allocation?
</blockquote></details>

yes, you are right @yamahata and even I am a little hesitant to use static allocation. Have updated the code to use dynamic allocation.
___
*[Pal/src/host/Linux/db_main.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9qSiO946hLw7z9DQP:-MKE6Iui-bfrUG-ytgux:b2etg3h) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The implementation of this function is wrong. Consider what happens if run on a single-cpu machine: your `/sys/devices/system/cpu/online` contains `0` (meaning there is one CPU with index 0). This will lead this function to return `0` (firstint). However, Graphene just wanted to know how many CPUs are there, so the correct return must be `1`.

I suggest to change this function as follows:
```
/* Opens a pseudo-file describing HW resources such as online CPUs and counts the number of HW resources
 * present in the file (if count == true) or simply reads the integer stored in the file (if count == false).
 * Returns -errno on failure. For example, calling this function on `/sys/devices/system/cpu/online` (with
 * complex formats like "1,3-5,6") will return 5, and calling this function on `/sys/devices/system/cpu/smt/active`
 * will return 1 (host supports SMT) or 0 (host doesn't support SMT). */
int get_hw_resource(const char *filename, bool count) {
   ... current logic of open and read ...
   if (!count) {
      /* caller wants to read an int stored in the file */
     int ret = strtol(buf, &end, 10);
     ... add error checking and return ret ...
   } else {
      ... current logic of reading the list and counting ...
   }
```
</blockquote></details>

Good catch @dimakuv. I missed the single-cpu case. Modified the code along similar lines but not exactly as above. Also reworded the comment a little.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9svBd6PiEwpqlF_r2:-MKWbihh2ostnUUNdogr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this `filename` close to the actual place where you use it. (This is a preference in style, but I think it makes sense here: you only use `filename` once in that particular place.)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9wuhw3zMrH950n7T1:-MKY96I205Qakw1-Yn0H:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L83)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

While we're here, can you add error checking `if (!vendor_id) {return -PAL_ERROR_NOMEM}`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9x3Pd-3YNT8_MuWhh:-MKY98pz9CwxQMa69xJB:b95tk4o) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

While we're here, can you add error checking `if (!brand) {return -PAL_ERROR_NOMEM}`
</blockquote></details>

Done. Also added error checks for `flags` and `newflags` allocation failures.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9tDrCCVF8iq4XJRlW:-MKWw19DCs3pV4LVrPPl:b-btntpm) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This goes wrong if `cpu_num == 0`. In this case, `rv == 0` and we jump to `out`, which returns `rv == 0` -- but this indicates "success"!

You should keep the old logic of `-PAL_ERROR_STREAMNOTEXIST` in the `get_hw_res_count()` function and don't check for `cpu_num == 0` here.
</blockquote></details>

updated get_hw_res_count to fix this issue.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9taRM-HMRr8BP6mfR:-MKWyyFB1AWREhte7ZUh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you move this comment up to the first `get_hw_res_count()`? It doesn't make sense here, in the middle of using sysfs files.

Also, update `extract info on number of cores ...` -> `extract info on total number of logical processors, number of physical cores, SMT support, etc. ...`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9tyX_2gZ1kHfSJ5HM:-MKWyKcO0249vyQ-zzLv:b-btntpm) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`== 0` is wrong)
</blockquote></details>

updated get_hw_res_count to fix this issue.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 124 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9uHMp2w3qKBmsKEUb:-MKY9EJk3vb2w0Z1XMzz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L124)):*
<details><summary><i>Previously, dimakuv (Dmitr [...]

2020-10-27 09:28 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9qEiu6zxgNhr7xUEK:-MKdDouaAiE7kwHlnV9z:b-qf5u0a) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L27)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Removed this #define and used dynamic allocation.
</blockquote></details>

Forgot to remove? I still see the define.
___
*[Pal/src/host/Linux/db_main.c, line 275 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdEHJD12wph-KImII4:-MKdEHJD12wph-KImII5:b3xxivx) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L275)):*
> ```C
>  * file (if count == false). For example on a single-cpu machine, calling this function on
>  * `/sys/devices/system/cpu/online` with count == true will return 1 and 0 with count == false.
>  * Returns PAL ERROR on failure.
> ```

`PAL ERROR` -> `PAL error code`
___
*[Pal/src/host/Linux/db_main.c, line 276 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdELth3TH2wroqa1rJ:-MKdELth3TH2wroqa1rK:bnuxe1n) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L276)):*
> ```C
>  * `/sys/devices/system/cpu/online` with count == true will return 1 and 0 with count == false.
>  * Returns PAL ERROR on failure.
>  * N.B: Understands complex formats like "1,3-5,6 when called with count == true.
> ```

Forgot closing `"`
___
*[Pal/src/host/Linux/db_main.c, line 278 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdER2-AppPuWZwsGt_:-MKdER2-AppPuWZwsGta:b4bv5qn) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L278)):*
> ```C
>  * N.B: Understands complex formats like "1,3-5,6 when called with count == true.
> */
> int get_hw_resource(const char *filename, bool count) {
> ```

Just notice wrong asterisk alignment: change to `... char* filename, ...`
___
*[Pal/src/host/Linux/db_main.c, line 307 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdFxbA6J6qGvXu7oAW:-MKdFxbA6J6qGvXu7oAX:b-96ehv6) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L307)):*
> ```C
>             if (*end == '\n' || *end == '\0')
>                 retval = firstint;
>             break;
> ```

Why not just `return retval`? Then we won't need the `else if` part and we won't need the 4-space indentation.
___
*[Pal/src/host/Linux/db_main.c, line 309 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdF-Jg6GDc6dnwKuhV:-MKdF-Jg6GDc6dnwKuhW:ber47dq) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L309)):*
> ```C
>             break;
>         } else if (*end == '\0' || *end == ',' || *end == '\n') {
>             /* single CPU index, count as one more CPU */
> ```

Let's rename `CPU` -> `HW resource`
___
*[Pal/src/host/Linux/db_main.c, line 312 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdF2-n3vmgUEbB9Po0:-MKdF2-n3vmgUEbB9Po1:ber47dq) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L312)):*
> ```C
>             resource_cnt++;
>         } else if (*end == '-') {
>             /* CPU range, count how many CPUs in range */
> ```

Let's rename `CPU` -> `HW resource`
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 125 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8So-r1-125:-MKdHl-yARs5J-7TisxD:bz1qzpk) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L125)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If we intend to run on platforms like KNL which can have 4HTs per core, then I can extract the number of HTs (instead of hard coding to 2) simply by dividing the number of thread_siblings by core_siblings.
</blockquote></details>

How hard is it to do? If it's trivial, then yes, please add this logic. But not blocking on this.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9v-oGDXnjk5XF-0Dp:-MKdIwNXBHEon4E-0gz6:b-uh3q6n) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L171)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Correct, this PR assumes all cores are online and doesn't take into account offlined processor cases.

Regarding the physical package id, the current design just runs a loop from 0 to the total number of online processors and reads the corresponding package id. So if CPU1 is offlined, it will fail when trying to read the `physical_package_id` file as CPU1 is offlined as the file is not present.

I don't think this check will help as well. In the above example that you have mentioned, `cpu_cores` which is `/sys/devices/system/cpu/cpu0/topology/core_siblings_list` will be 3 and if SMT is active, we further divide by 2.`cpu_num` which is `/sys/devices/system/cpu/online` will be 3. cpu_cores will either be less than or equal to cpu_num.

To correctly identify if the processors are offlined, we need to read `/sys/devices/system/cpu/possible` and `/sys/devices/system/cpu/online`. If the counts don't match, some processors are offlined. I have added a print based on this logic.

I would suggest, we treat offlined case as a separate PR as it brings its own complexities. We need to take into account things like to which node CPU belongs and SMT. This can be looked at as phase 2 of CPU topology changes.

In fact, even the current implementation of /proc/cpuinfo also has issues when cores are offlined. If we consider the above example of offlining CPU1, `/proc/cpuinfo` will show `processor` field as 0,1, and 2 instead of 0, 2, and 3 as we iterate from 0  to the total number of online processors.

</blockquote></details>

OK. I'm happy with the current changes in this PR. The offline-cpus case can be postponed to another PR.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 134 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdHPt_Eh0WvttgZ8z-:-MKdHPt_Eh0WvttgZ8z0:ba8m9ks) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main-x86_64.c#L134)):*
> ```C
> 
>     /* FIXME: This code assumes there are only 2 HTs per core but platforms like
>      * KNL(Knights landing) can have more */
> ```

Slight fix: `KNL(Knights landing)` -> `KNL (Knights Landing)`
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 143 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdI7fiCLIsNOk6RdsK:-MKdI7fiCLIsNOk6RdsL:b-lb1e5t) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main-x86_64.c#L143)):*
> ```C
> 
>     /* array of "logical processor -> physical package" mappings */
>     int *phy_id = (int*)malloc(cpu_num * sizeof(int));
> ```

Wrong asterisk alignment: `int* phy_id`
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 147 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdICju7v-i_foXiwG9:-MKdICju7v-i_foXiwGA:b-yfraug) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddace [...]

2020-10-27 22:20 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9qEiu6zxgNhr7xUEK:-MKf0oTk3UPhb7jlY5rX:bnatg91) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/include/arch/x86_64/pal-arch.h#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to remove? I still see the define.
</blockquote></details>

sorry, must have missed saving the file after the change :)
___
*[Pal/src/host/Linux/db_main.c, line 275 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdEHJD12wph-KImII4:-MKf49dfEckClKVlRZ_I:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L275)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`PAL ERROR` -> `PAL error code`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 276 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdELth3TH2wroqa1rJ:-MKf4B-Z1kzgHFLkgRwO:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot closing `"`
</blockquote></details>

Fixed.
___
*[Pal/src/host/Linux/db_main.c, line 278 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdER2-AppPuWZwsGt_:-MKf4TOIBQscyJ-wEDy2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L278)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just notice wrong asterisk alignment: change to `... char* filename, ...`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 307 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdFxbA6J6qGvXu7oAW:-MKf8l-69-gBuUD6sPvS:bp2rc8g) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L307)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just `return retval`? Then we won't need the `else if` part and we won't need the 4-space indentation.
</blockquote></details>

yes, we can do that too. This was just my preference. 
___
*[Pal/src/host/Linux/db_main.c, line 309 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdF-Jg6GDc6dnwKuhV:-MKf4UgB00FWb144UyqI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L309)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's rename `CPU` -> `HW resource`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 312 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdF2-n3vmgUEbB9Po0:-MKfwVb991uaflvb5ZSb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main.c#L312)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's rename `CPU` -> `HW resource`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 125 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8So-r1-125:-MKfCzII93fYXAmGjA_y:b8vfzai) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L125)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How hard is it to do? If it's trivial, then yes, please add this logic. But not blocking on this.
</blockquote></details>

very simple. Modified the code to do this.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 134 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdHPt_Eh0WvttgZ8z-:-MKfDf_A1sAHolk54gxJ:b6gwppl) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main-x86_64.c#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Slight fix: `KNL(Knights landing)` -> `KNL (Knights Landing)`
</blockquote></details>

Not applicable as we not correctly identify the number of siblings per core.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 143 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdI7fiCLIsNOk6RdsK:-MKfDvT1-Y4uV8kRud1M:b-ek8v1i) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main-x86_64.c#L143)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrong asterisk alignment: `int* phy_id`
</blockquote></details>

sorry habits :). I have fixed it.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 147 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdICju7v-i_foXiwG9:-MKfI-9H2F_8NZ7XrqlT:bs7wumx) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main-x86_64.c#L147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this
</blockquote></details>

Done. 
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 149 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdIRSs7i6u-6T1YlN0:-MKfHxsU49_PEmyilWH_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux/db_main-x86_64.c#L149)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Add space: `idx = 0`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 301 at r2](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKdKYYV6GpGAT-2FkqH:-MKfvd2g5m2SiX7Oh1JE:b2gp2b9) ([raw file](https://github.com/oscarlab/graphene/blob/2a0eaa5ddacecd9458343cb6b95fbdb66c522d5e/Pal/src/host/Linux-SGX/db_main.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is wrong! You must dynamically allocate the array `g_pal_sec.phy_id` and then `memcpy(g_pal_sec.phy_id, sec_info.phy_id, sec_info.cpu_cores * sizeof(int))` (something like this).

What happens now is that you assign `g_pal_sec.phy_id` to point to **untrusted memory**. SGX enclaves allow this, but we lost security: the malicious host OS can replace e.g. `g_pal_sec.phy_id[0] = 123` in untrusted memory and in-enclave logic breaks.

For dynamic allocation to work, you should move this logic below `init_enclave_pages()` (otherwise you cannot call `malloc`). I suggest to move this step to after `init_tsc()`.
</blockquote></details>

yeah wasn't sure if we needed two allocations, one outside and one inside enclave but this makes it clear. Have fixed the code accordingly.
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 122 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK9xQtk7N2fyh_DeSzb:-MKfHA62-InnNcknZgve:b-n4uc0c) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux-SGX/db_main-x86_64.c#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

yeah missed this. Fixed it now.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 687 at r2](https://reviewable.io/reviews [...]

2020-10-28 09:40 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

___
*[Pal/src/host/Linux/db_main-x86_64.c, line 125 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8So-r1-125:-MKiZmYd4fipIUe8K2rI:bct65bp) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L125)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

very simple. Modified the code to do this.
</blockquote></details>

Thanks. Please unblock your own comment (see on the right of this text window, change status from "-" to " ") to resolve this.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 139 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYYra6gjjF4dIObhD:-MKiYYra6gjjF4dIObhE:b-4v6m6z) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux/db_main-x86_64.c#L139)):*
> ```C
>         goto out_brand;
>     }
>     ci->cpu_cores = (smt_siblings == 1) ? cpu_cores : (cpu_cores / smt_siblings) ;
> ```

Why not just `ci->cpu_cores = cpu_cores / smt_siblings`? Even the case of `1` will be correctly handled.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 154 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYm_1CWkUmuKpX5jj:-MKiYm_29D1iVhSwpRbP:b-1xre9c) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux/db_main-x86_64.c#L154)):*
> ```C
>         phy_id[idx] = get_hw_resource(filename, /*count=*/false);
>         if (phy_id[idx] < 0) {
>             printf(" cannot read %s\n", filename);
> ```

Nitpick: `printf("Cannot read ...")`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 301 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8Sl-r1-301:-MKiZyL4-qO7Acd4UWho:bd2kp2g) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux-SGX/db_main.c#L301)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

As part of the subsequent patches, I plan to add the number of nodes present. We can cross-verify that each physical package ID should not be greater than the number of nodes.  (Basically create a for loop and validate each physical package id). Other suggestions welcome.
</blockquote></details>

OK. Please unblock your own comment (see on the right of this text window, change status from "-" to " ") to resolve this.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 346 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYvYkBjhNMdsPDiHg:-MKiYvYkBjhNMdsPDiHh:b-j2rglp) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux-SGX/db_main.c#L346)):*
> ```C
>     SET_ENCLAVE_TLS(ready_for_exceptions, 1UL);
> 
>     /* Allocate enclave memory to store "logical processor -> physical package" mappings*/
> ```

Nitpick: `...mappings */` (add space)
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 773 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8Sn-r1-773:-MKi_0WqAKGrD0GO32mz:bnvu0re) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux-SGX/sgx_main.c#L773)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If we intend to run on platforms like KNL which can have 4HTs per core, then I can extract the number of HTs (instead of hard coding to 2) simply by dividing the number of thread_siblings by core_siblings.
</blockquote></details>

Please unblock your own comment (see on the right of this text window, change status from "-" to " ") to resolve this.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 790 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiZUle5_lhWm1Ra-Lw:-MKiZUle5_lhWm1Ra-Lx:btuunxp) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux-SGX/sgx_main.c#L790)):*
> ```C
>     if (smt_siblings < 0)
>         return smt_siblings;
>     pal_sec->cpu_cores = (smt_siblings == 1) ? cpu_cores : (cpu_cores / smt_siblings);
> ```

See my other comment


<!-- Sent from Reviewable.io -->

2020-10-28 21:46 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux/db_main-x86_64.c, line 125 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8So-r1-125:-MKl8F9BE4ydTQvMEF0J:b-qy3qbu) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux/db_main-x86_64.c#L125)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks. Please unblock your own comment (see on the right of this text window, change status from "-" to " ") to resolve this.
</blockquote></details>

yes, done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 139 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYYra6gjjF4dIObhD:-MKl75dt4u6EEKqjlajP:b-qy3qbu) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux/db_main-x86_64.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just `ci->cpu_cores = cpu_cores / smt_siblings`? Even the case of `1` will be correctly handled.
</blockquote></details>

yes, done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 154 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYm_1CWkUmuKpX5jj:-MKl7oib1yKko3ADbyyt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux/db_main-x86_64.c#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nitpick: `printf("Cannot read ...")`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 301 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8Sl-r1-301:-MKl7uaR0xySNNNC_jWp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux-SGX/db_main.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. Please unblock your own comment (see on the right of this text window, change status from "-" to " ") to resolve this.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 346 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYvYkBjhNMdsPDiHg:-MKl85M97AMBSKC0GKDF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux-SGX/db_main.c#L346)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nitpick: `...mappings */` (add space)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 773 at r1](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8Sn-r1-773:-MKl8O8_Ds7HYjvgNXTe:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9efd4bbec7e128795f67c5d21464e6ee491fa831/Pal/src/host/Linux-SGX/sgx_main.c#L773)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please unblock your own comment (see on the right of this text window, change status from "-" to " ") to resolve this.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 790 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiZUle5_lhWm1Ra-Lw:-MKl8An6Dtp6ElrzlNAj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux-SGX/sgx_main.c#L790)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my other comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 23:24 UTC, yamahata approved these changes
> Reviewed 3 of 9 files at r2, 3 of 6 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-10-29 09:59 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/src/host/Linux/db_main-x86_64.c, line 154 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYm_1CWkUmuKpX5jj:-MKnmkkn03M-X01pHeeV:b-xnne7q) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux/db_main-x86_64.c#L154)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You still have a leading space. Please fix.


<!-- Sent from Reviewable.io -->

2020-10-29 17:36 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: 8 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux/db_main-x86_64.c, line 154 at r3](https://reviewable.io/reviews/oscarlab/graphene/1910#-MKiYm_1CWkUmuKpX5jj:-MKpQc6f61rKBChYxCAt:b-2bvwl6) ([raw file](https://github.com/oscarlab/graphene/blob/f08d3daa3ff8fbfd143d8c0e5821c8a26c34abee/Pal/src/host/Linux/db_main-x86_64.c#L154)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You still have a leading space. Please fix.
</blockquote></details>

yes fixed this.


<!-- Sent from Reviewable.io -->

2020-10-30 09:45 UTC, dimakuv approved these changes
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-02 00:07 UTC, mkow requested changes
> Reviewed 3 of 9 files at r2, 3 of 6 files at r3, 2 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5BCMk2oXZmJO3g30H:-ML5BCMk2oXZmJO3g30I:b-3k08lb) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L191)):*
> ```
>     PAL_NUM cpu_num;
>     PAL_NUM cpu_cores;
> ```
How those two relate to each other? Please comment and explain their meaning or use better variable names (when I'm reading the current names I'm confused - at first it looks like the first one is CPU count (i.e. sockets) and the latter is cores count, but this doesn't make sense - can't both sockets have different core counts?).
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML4PNAgErDq7mh64xvK:-ML4PNAgErDq7mh64xvL:bs0saoy) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
> ```objc
>     PAL_NUM cpu_num;
>     PAL_NUM cpu_cores;
>     PAL_PTR phy_id;
> ```

Please change to `int*` and drop the cast from `info.c`, we need to get rid of these PAL types, they don't make any sense.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML59z5MBVE-uW-mO3E4:-ML59z5NEyu98oA9YQS1:b-hqwn3h) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
> ```objc
>     PAL_NUM cpu_num;
>     PAL_NUM cpu_cores;
>     PAL_PTR phy_id;
> ```

Please comment here how many elements has this array
___
*[Pal/src/host/Linux/db_main.c, line 274 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML56dSDAhnvfAPN_sIM:-ML56dSE00rGuEwNsQoO:b-weqkql) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L274)):*
> ```
> and 0 with count == false
> ```

Why 0 in this case? Not an error? `0-7` and similar inputs are not numbers.
___
*[Pal/src/host/Linux/db_main.c, line 277 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5EG2V1n_OcrHlQvPS:-ML5EG2V1n_OcrHlQvPT:bwpu2ql) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L277)):*
> ```C
>  * Returns PAL error code on failure.
>  * N.B: Understands complex formats like "1,3-5,6" when called with count == true.
> */
> ```

broken alignment
___
*[Pal/src/host/Linux/db_main.c, line 278 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML57DFRCfvMr2i46X72:-ML57DFRCfvMr2i46X73:bn2vq4c) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L278)):*
> ```
> get_hw_resource
> ```

Is this format used anywhere outside of `/sys/devices/system/cpu/*`? If not, I'd say "cpu" instead of "hw". Or even better, `parse_sysfs_cpu_info` (this is a global function, `get_hw_resource` could mean a lot of things in the global namespace).
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 121 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML58uRH6kLp03H32HW1:-ML58uRH6kLp03H32HW2:b-6btijx) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main-x86_64.c#L121)):*
> ```C
>     int possible_cpus = get_hw_resource("/sys/devices/system/cpu/possible", /*count=*/true);
>     /* TODO: correctly support offline CPUs */
>     if ((possible_cpus > 0) && (possible_cpus > cpu_num)) {
> ```

no need for parentheses
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 127 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5925l8ce86JG9AY31:-ML5925l8ce86JG9AY32:b-coj8k2) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main-x86_64.c#L127)):*
> ```C
> 
>     int cpu_cores = get_hw_resource("/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
>                                      /*count=*/true);
> ```

please fix alignment of the wrapped line
___
*[Pal/src/host/Linux/pal_linux.h, line 129 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5CJaYE-V1Dj4gozG3:-ML5CJaYE-V1Dj4gozG4:bryla7s) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/pal_linux.h#L129)):*
> ```objc
>                         PAL_HANDLE* manifest);
> 
> int get_hw_resource(const char *filename, bool count);
> ```

`*` should be on the left
___
*[Pal/src/host/Linux-SGX/db_main.c, line 352 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Fa9m3c9afCc4NvOW:-ML5Fa9m3c9afCc4NvOX:b-foabin) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main.c#L352)):*
> ```C
>         ocall_exit(1, /*is_exitgroup=*/true);
>     }
>     memcpy(phy_id, sec_info.phy_id, num_cpus * sizeof(int));
> ```

sec_info.phy_id resides in untrusted memory, you have to copy it using `sgx_copy_to_enclave`. Please also prefix this field in `struct pal_sec` with `uptr_` to make it more visible that it's a pointer to untrusted memory.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 353 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5CoZr0vzh_PRrMglR:-ML5CoZr0vzh_PRrMglS:b-gur9nt) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main.c#L353)):*
> ```C
>     }
>     memcpy(phy_id, sec_info.phy_id, num_cpus * sizeof(int));
>     g_pal_sec.phy_id = (PAL_PTR)phy_id;
> ```

this cast could be removed after you resolve my previous comment
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 123 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5D1On1VozYXgiMK3F:-ML5D1On1VozYXgiMK3G:b-2ja7h6) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main-x86_64.c#L123)):*
> ```C
>     const size_t VENDOR_ID_SIZE = 13;
>     char* vendor_id = malloc(VENDOR_ID_SIZE);
>     if(!vendor_id)
> ```

space after `if`
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 140 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5DBTi1EPAkoq0GED2:-ML5DBTi1EPAkoq0GED3:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main-x86_64.c#L140)):*
> ```C
>     const size_t BRAND_SIZE = 49;
>     char* brand = malloc(BRAND_SIZE);
>     if(!brand) {
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 171 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5D_YM1wEVcHMlfdOM:-ML5D_YM1wEVcHMlfdON:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main-x86_64.c#L171)):*
> ```C
>     int flen = 0, fmax = 80;
>     char* flags = malloc(fmax);
>     if(!flags) {
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 184 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Db5X9OUO5w_UZq4S:-ML5Db5X9OUO5w_UZq4T:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main-x86_64.c#L184)):*
> ```C
>             if (flen + len + 1 > fmax) {
>                 char* new_flags = malloc(fmax * 2);
>                 if(!new_flags) {
> ```

ditto
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 43 at r5](https://reviewable.io/rev [...]

2020-11-02 17:50 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: 0 of 9 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5BCMk2oXZmJO3g30H:-ML8bnk4AebhF9eJUIas:bub7aou) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>     PAL_NUM cpu_num;
>     PAL_NUM cpu_cores;
> ```
How those two relate to each other? Please comment and explain their meaning or use better variable names (when I'm reading the current names I'm confused - at first it looks like the first one is CPU count (i.e. sockets) and the latter is cores count, but this doesn't make sense - can't both sockets have different core counts?).
</blockquote></details>

cpu_num refers to the total number of logical processors available in the host (online processors). This includes all the sockets. This variable name already existed. cpu_cores refers to the total number of physical cores in a physical package (socket). This is the new added by this PR. Kept this name to match `/proc/cpuinfo` output.
note: A physical core can have 2 or more logical processors when HT is turned on.

I have added comments to clarify this. @mkow please let me know if you want me to rename `cpu_num` to `online_procs` and `cpu_cores` to `cores_per_socket`. Do let me know if you have any other suggestions as well.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML4PNAgErDq7mh64xvK:-ML8h41s1jaI9fJBUlOu:b-szhbky) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change to `int*` and drop the cast from `info.c`, we need to get rid of these PAL types, they don't make any sense.
</blockquote></details>

sure, done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML59z5MBVE-uW-mO3E4:-ML8jombB8Kw5Uyb3BzO:b-te234y) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please comment here how many elements has this array
</blockquote></details>

This depends on the number of logical processors available in the host. I have added this comment `/* array of "logical processor -> physical package" mappings */` to clarify.
___
*[Pal/src/host/Linux/db_main.c, line 274 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML56dSDAhnvfAPN_sIM:-ML8kyxoCCgrlWjaMJv9:b6o6l3s) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L274)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> and 0 with count == false
> ```

Why 0 in this case? Not an error? `0-7` and similar inputs are not numbers.
</blockquote></details>

when `count == false` we simply read the contents of the file. So on a single-cpu machine, contents of `/sys/devices/system/cpu/online` will be `zero` and is valid. But if we set `count == true`the expectation is to count the number of cpus which should be greater than `zero`.
___
*[Pal/src/host/Linux/db_main.c, line 277 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5EG2V1n_OcrHlQvPS:-ML8mULL80a-bTk4dnU1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L277)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

broken alignment
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 278 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML57DFRCfvMr2i46X72:-ML8maQt86x5szdnP88j:bo2zdwh) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L278)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> get_hw_resource
> ```

Is this format used anywhere outside of `/sys/devices/system/cpu/*`? If not, I'd say "cpu" instead of "hw". Or even better, `parse_sysfs_cpu_info` (this is a global function, `get_hw_resource` could mean a lot of things in the global namespace).
</blockquote></details>

yes as part of my other changes for sysfs (cpu topology), I intended to use this function to read `/sys/devices/system/node/*` as well.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 121 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML58uRH6kLp03H32HW1:-ML8p_JCBkmHadA7IK8Y:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main-x86_64.c#L121)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need for parentheses
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 127 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5925l8ce86JG9AY31:-ML8qCsH0esMytjfh5Sb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main-x86_64.c#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment of the wrapped line
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/pal_linux.h, line 129 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5CJaYE-V1Dj4gozG3:-ML8qVxY3zyuT3TfpuMO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/pal_linux.h#L129)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`*` should be on the left
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 352 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Fa9m3c9afCc4NvOW:-ML8tz2776_vz2kMAwN9:b-3t44v5) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main.c#L352)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

sec_info.phy_id resides in untrusted memory, you have to copy it using `sgx_copy_to_enclave`. Please also prefix this field in `struct pal_sec` with `uptr_` to make it more visible that it's a pointer to untrusted memory.
</blockquote></details>

Thanks, updated to use `sgx_copy_to_enclave`.
Here we copy from `sec_info.phy_id` to `g_pal_sec.phy_id`. Both these variables are of type `struct pal_sec`, but phy_id in sec_info points to untrusted memory whereas phy_id in g_pal_sec points to trusted memory. So I think renaming to `uptr_phy_id` might lead to some confusion.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 353 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5CoZr0vzh_PRrMglR:-ML8wLIQ2LNpdJeicrJs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main.c#L353)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this cast could be removed after you resolve my previous comment
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 123 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5D1On1VozYXgiMK3F:-ML8wvw_A [...]

2020-11-03 01:18 UTC, mkow requested changes
> Reviewed 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5BCMk2oXZmJO3g30H:-MLAaIMxAxZC4JfFqbTs:b-4t89m4) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L191)):*
But this still doesn't answer one of my questions, quoting: "can't both sockets have different core counts?". If they can, this representation won't work for such cases.

> let me know if you want me to rename `cpu_num` to `online_procs` and `cpu_cores` to `cores_per_socket`

I like this suggestion, but maybe `online_cpu_threads` or `online_logical_cores`? Would be even less ambiguous. But let's do this after we resolve the discussion about multisocket configs.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML59z5MBVE-uW-mO3E4:-MLAap_V1pQLHvl2RKP1:buzyzp9) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This depends on the number of logical processors available in the host. I have added this comment `/* array of "logical processor -> physical package" mappings */` to clarify.
</blockquote></details>

What I mean is saying "[..] and has `cpu_num` elements".
___
*[Pal/src/host/Linux/db_main.c, line 274 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML56dSDAhnvfAPN_sIM:-MLAbFqA6-YSAaoqdhIh:be0ffyt) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L274)):*
> So on a single-cpu machine, contents of /sys/devices/system/cpu/online will be zero

Hmm, no. Maybe you mean a single-logical-core machine? I read single-cpu as "single cpu package", i.e. single socket.
___
*[Pal/src/host/Linux/db_main.c, line 278 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML57DFRCfvMr2i46X72:-MLAbtrnALK5XdKrGRnb:b-pkjtsr) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L278)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes as part of my other changes for sysfs (cpu topology), I intended to use this function to read `/sys/devices/system/node/*` as well.
</blockquote></details>

Sounds good then.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 141 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAcBAe-DZF40H1pYAF:-MLAcBAe-DZF40H1pYAG:b1ao66l) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux/db_main-x86_64.c#L141)):*
> ```C
>     ci->cpu_cores = cpu_cores / smt_siblings;
> 
>     /* array of "logical processors -> physical package" mappings */
> ```

I'd revert adding this "-s" to "processor", if you say "array of" then you describe a single element of the array.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 352 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Fa9m3c9afCc4NvOW:-MLAcYZc0lKJgeBbV-8V:b-nivx46) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/db_main.c#L352)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks, updated to use `sgx_copy_to_enclave`.
Here we copy from `sec_info.phy_id` to `g_pal_sec.phy_id`. Both these variables are of type `struct pal_sec`, but phy_id in sec_info points to untrusted memory whereas phy_id in g_pal_sec points to trusted memory. So I think renaming to `uptr_phy_id` might lead to some confusion.
</blockquote></details>

Ah, I see, good point. Let's leave it as is.
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 159 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdMcl1X4i5QKb5Aod:-MLAdMcl1X4i5QKb5Aoe:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/db_main-x86_64.c#L159)):*
> ```C
>     ci->cpu_cores = g_pal_sec.cpu_cores;
> 
>     /* array of "logical processors -> physical package" mappings */
> ```

ditto
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 43 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Gb3NDYIU6WIj11Gr:-MLAdVO_2Dz0sWyMej2X:b-8egimi) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/pal_security.h#L43)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, they can have when the user offlines a few logical processors in a package, but since this PR doesn't address offlining have kept this an unsigned int. We should look at offlining as phase 2 of CPU topology changes.
</blockquote></details>

Is taking CPUs offline the only case when this can happen? I'm not into servers, so I don't know, but having this assumption embedded in the code when it later turns wrong sounds dangerous. Could you please verify that this is indeed the case and it's not possible to have 2 CPUs with different number of cores in two sockets?
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 46 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5DvCu2UMpoLyDLsPa:-MLAe3tJ21eHiWGTqiiH:bn7a8hs) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/pal_security.h#L46)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Changed type to int*. Please see my earlier comment about count and renaming `phy_id` to `uptr_phy_id`. Doesn't the comment `array of logical processor` clarify?
</blockquote></details>

See my response to the corresponding thread.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 45 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdzLqCk4cEzlTa2Hx:-MLAdzLqCk4cEzlTa2Hy:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/pal_security.h#L45)):*
> ```objc
>     PAL_NUM cpu_cores;
> 
>     /* array of "logical processors -> physical package" mappings */
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 686 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5E1beClFvPloN0dmG:-MLAeJ5J0Qa0KbH7Mpk7:btysawv) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/sgx_main.c#L686)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

please see my earlier comment on this.
</blockquote></details>

ditto ("single-cpu")
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 792 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAeNsbED7KNZWwcKay:-MLAeNsbED7KNZWwcKaz:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/sgx_main.c#L792)):*
> ```C
>     pal_sec->cpu_cores = cpu_cores / smt_siblings;
> 
>     /* array of "logical processors -> physical package" mappings */
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-11-03 05:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @vijaydhanraj, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5BCMk2oXZmJO3g30H:-MLB8D3J4RMdOk7Nb_yy:bajsunm) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this still doesn't answer one of my questions, quoting: "can't both sockets have different core counts?". If they can, this representation won't work for such cases.

> let me know if you want me to rename `cpu_num` to `online_procs` and `cpu_cores` to `cores_per_socket`

I like this suggestion, but maybe `online_cpu_threads` or `online_logical_cores`? Would be even less ambiguous. But let's do this after we resolve the discussion about multisocket configs.
</blockquote></details>

usually, the sockets have a symmetrical number of processors by default unless the user offlines. But my knowledge is limited as well so adding @dimakuv and @yamahata for additional inputs. 

The current implementation of `cpu_cores` is definitely broken which gives the total number of online processors as physical cores per socket :).
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML59z5MBVE-uW-mO3E4:-MLBSXFK8DkHnicFx_IQ:bg0fis) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What I mean is saying "[..] and has `cpu_num` elements".
</blockquote></details>

you mean something like this `/* array of "logical processor -> physical package" mappings having cpu_num elements */` right?
___
*[Pal/src/host/Linux/db_main.c, line 274 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML56dSDAhnvfAPN_sIM:-MLBUMWT7MdrBO1l2C2o:b-i3zh6u) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L274)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> So on a single-cpu machine, contents of /sys/devices/system/cpu/online will be zero

Hmm, no. Maybe you mean a single-logical-core machine? I read single-cpu as "single cpu package", i.e. single socket.
</blockquote></details>

yes, correct I did mean a machine with a single core. Not sure if it is right to add the `logical` term to the core.  I think core usually refers to physical cores.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 43 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Gb3NDYIU6WIj11Gr:-MLBX3u516ykhDXk3vrz:b-mnbfhi) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/pal_security.h#L43)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is taking CPUs offline the only case when this can happen? I'm not into servers, so I don't know, but having this assumption embedded in the code when it later turns wrong sounds dangerous. Could you please verify that this is indeed the case and it's not possible to have 2 CPUs with different number of cores in two sockets?
</blockquote></details>

AFAIK, sockets would be symmetrical with respect to the number of cores. Usually, the number of cores in a socket determines the frequency. For example, a 12 core/socket part will have say 2.5GHz, whereas a 24 core/socket part will lesser frequency due to thermal reasons. Given this example, one cannot easily add asymmetric cores in the socket without special bios changes. But again my knowledge is limited so adding @dimakuv and @yamahata for further inputs.


<!-- Sent from Reviewable.io -->

2020-11-03 10:06 UTC, dimakuv requested changes
> Reviewed 8 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5BCMk2oXZmJO3g30H:-MLCVfSL8aMXXxl9eJZv:bvug8l3) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L191)):*
> can't both sockets have different core counts?

Theoretically each socket may have a different core count, but I am not aware of any machine like this. To me, the assumption that each socket has the same number of logical cores sounds legit.

> I like this suggestion, but maybe `online_cpu_threads` or `online_logical_cores`?

I would suggest `cpu_num` -> `online_logical_cores` and `cpu_cores` -> `physical_cores_per_socket`.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML59z5MBVE-uW-mO3E4:-MLCXJ2M2SDUUjmhntDp:b-7cgce3) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

you mean something like this `/* array of "logical processor -> physical package" mappings having cpu_num elements */` right?
</blockquote></details>

I think Michal wants smth like this:
```
/* array of "logical processor -> socket" mappings; has cpu_num elements */
int* cpu_socket;
```

I am also voting to rename `phy_id` to `cpu_socket` (read it as "returns a socket for this logical processor/CPU").
___
*[Pal/src/host/Linux/db_main.c, line 274 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML56dSDAhnvfAPN_sIM:-MLCYOiv5oOtx6b_AECF:b-sq2xsd) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L274)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, correct I did mean a machine with a single core. Not sure if it is right to add the `logical` term to the core.  I think core usually refers to physical cores.
</blockquote></details>

These terms are overloaded and fuzzy. Let's just stick to one convention in Graphene (and in this PR). I suggest to follow Michal's terminology:
- `logical core` to denote a logical thread/logical CPU/logical core
- `physical core` to denote a physical CPU/physical core
- `socket` to denote a physical package.

I would prefer to remove "CPU" and "physical package" from our variable names and comments and stick to these three.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 43 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Gb3NDYIU6WIj11Gr:-MLCZJ2f3c2k-YxYl6pg:b-6itqgc) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/pal_security.h#L43)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

AFAIK, sockets would be symmetrical with respect to the number of cores. Usually, the number of cores in a socket determines the frequency. For example, a 12 core/socket part will have say 2.5GHz, whereas a 24 core/socket part will lesser frequency due to thermal reasons. Given this example, one cannot easily add asymmetric cores in the socket without special bios changes. But again my knowledge is limited so adding @dimakuv and @yamahata for further inputs.
</blockquote></details>

As mentioned in the previous comment, I have never seen asymmetric sockets.


<!-- Sent from Reviewable.io -->

2020-11-03 12:08 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5BCMk2oXZmJO3g30H:-MLCzC3Q46RC9e1mpzP6:b7rrrs3) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> can't both sockets have different core counts?

Theoretically each socket may have a different core count, but I am not aware of any machine like this. To me, the assumption that each socket has the same number of logical cores sounds legit.

> I like this suggestion, but maybe `online_cpu_threads` or `online_logical_cores`?

I would suggest `cpu_num` -> `online_logical_cores` and `cpu_cores` -> `physical_cores_per_socket`.
</blockquote></details>

Ok, let's leave the implementation as-is then.

Dima's naming suggestions also sound good.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML59z5MBVE-uW-mO3E4:-MLD-4r657yjRq23hDrD:b-1sgxsm) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think Michal wants smth like this:
```
/* array of "logical processor -> socket" mappings; has cpu_num elements */
int* cpu_socket;
```

I am also voting to rename `phy_id` to `cpu_socket` (read it as "returns a socket for this logical processor/CPU").
</blockquote></details>

+1 to Dima's suggestions.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 43 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5Gb3NDYIU6WIj11Gr:-MLD-SaS5abgd06V0ilr:bfkq9tk) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/pal_security.h#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As mentioned in the previous comment, I have never seen asymmetric sockets.
</blockquote></details>

Ok, let's leave it as-is then.


<!-- Sent from Reviewable.io -->

2020-11-03 23:22 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 191 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5BCMk2oXZmJO3g30H:-MLFLn7G1r7YC0yACOTW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, let's leave the implementation as-is then.

Dima's naming suggestions also sound good.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML59z5MBVE-uW-mO3E4:-MLFLjNbE6zjqwS77tVg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to Dima's suggestions.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 274 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML56dSDAhnvfAPN_sIM:-MLFLs4xBOpHSwjazZ9s:br8hwk0) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux/db_main.c#L274)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These terms are overloaded and fuzzy. Let's just stick to one convention in Graphene (and in this PR). I suggest to follow Michal's terminology:
- `logical core` to denote a logical thread/logical CPU/logical core
- `physical core` to denote a physical CPU/physical core
- `socket` to denote a physical package.

I would prefer to remove "CPU" and "physical package" from our variable names and comments and stick to these three.
</blockquote></details>

Sure will use this naming convention. Also, cleaned-up the variables names accordingly.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 141 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAcBAe-DZF40H1pYAF:-MLFMFoL6cKaWNSx77M5:b4ptguu) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux/db_main-x86_64.c#L141)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd revert adding this "-s" to "processor", if you say "array of" then you describe a single element of the array.
</blockquote></details>

yes I have reverted this change.
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 159 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdMcl1X4i5QKb5Aod:-MLFNBOf4BGAFHVosKch:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/db_main-x86_64.c#L159)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 46 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5DvCu2UMpoLyDLsPa:-MLFN1cR9bKQEdq2VqIB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/pal_security.h#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

See my response to the corresponding thread.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 45 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdzLqCk4cEzlTa2Hx:-MLFN-2L58rJd-3lF0Wu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/pal_security.h#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 686 at r5](https://reviewable.io/reviews/oscarlab/graphene/1910#-ML5E1beClFvPloN0dmG:-MLFN3D0-A-bk5TEw5CS:bdnualk) ([raw file](https://github.com/oscarlab/graphene/blob/b221abdf44a210a57c4c9ca01baeccd3c1266410/Pal/src/host/Linux-SGX/sgx_main.c#L686)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto ("single-cpu")
</blockquote></details>

changed to single-core now.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 792 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAeNsbED7KNZWwcKay:-MLFN6541spieY03ivdR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/sgx_main.c#L792)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-03 23:26 UTC, vijaydhanraj commented on Pal/src/host/Linux-SGX/pal_security.h
> +    /* array of "logical processor->physical package" mappings; has online_logical_cores elements*/
will change elements*/ -> elements */ in the next fixup or if things look fine before merge.

2020-11-04 00:57 UTC, mkow requested changes
> Reviewed 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 195 at r7](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLFTYCi02xaJdnol1Pb:-MLFTYCjDHZdyth-fWc1:bn6g6rr) ([raw file](https://github.com/oscarlab/graphene/blob/7202ef905f403e87d319d30c99a59a32c44f5d23/Pal/include/arch/x86_64/pal-arch.h#L195)):*
> ```objc
>     PAL_NUM physical_cores_per_socket;
>     /* array of "logical processor->physical package" mappings; has online_logical_cores elements */
>     int* cpu_socket ;
> ```

trailing space
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 127 at r7](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLFUVOk9Whb0bDmiu4W:-MLFUVOk9Whb0bDmiu4X:b-2y6s2h) ([raw file](https://github.com/oscarlab/graphene/blob/7202ef905f403e87d319d30c99a59a32c44f5d23/Pal/src/host/Linux/db_main-x86_64.c#L127)):*
> ```C
> 
>     int core_siblings = get_hw_resource("/sys/devices/system/cpu/cpu0/topology/core_siblings_list",
>                                            /*count=*/true);
> ```

please fix alignment
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 159 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdMcl1X4i5QKb5Aod:-MLFiRd20kA6GKakbluH:b-9lv303) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/db_main-x86_64.c#L159)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Here this comment about element count doesn't make sense, it was only intended for the structure definition for its users.

Btw. now when all fields are more descriptive, we can remove the comments altogether (here and in the 2 assignments above).
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 45 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdzLqCk4cEzlTa2Hx:-MLFik1i4EWsKEMY3GUI:b-d64auf) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/pal_security.h#L45)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (see my previous comment)
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 792 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAeNsbED7KNZWwcKay:-MLFkFeL4mGRqQcfENny:bfhqml6) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/sgx_main.c#L792)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.


<!-- Sent from Reviewable.io -->

2020-11-04 02:35 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @vijaydhanraj, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 195 at r7](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLFTYCi02xaJdnol1Pb:-MLG1wfrBPo5wF8-icaw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7202ef905f403e87d319d30c99a59a32c44f5d23/Pal/include/arch/x86_64/pal-arch.h#L195)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

trailing space
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 127 at r7](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLFUVOk9Whb0bDmiu4W:-MLG20du9gnNA0oZoaYh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7202ef905f403e87d319d30c99a59a32c44f5d23/Pal/src/host/Linux/db_main-x86_64.c#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 159 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdMcl1X4i5QKb5Aod:-MLG1Gpq09RQ9AIhWgkB:b-szhbky) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/db_main-x86_64.c#L159)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Here this comment about element count doesn't make sense, it was only intended for the structure definition for its users.

Btw. now when all fields are more descriptive, we can remove the comments altogether (here and in the 2 assignments above).
</blockquote></details>

sure, done.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 45 at r7](https://reviewable.io/reviews/oscarlab/graphene/1910#-MK8LHGp7em3_ItuK8Sm-r7-45:-MLG28kF7bpwPGvQvx6L:b-sfb3y2) ([raw file](https://github.com/oscarlab/graphene/blob/7202ef905f403e87d319d30c99a59a32c44f5d23/Pal/src/host/Linux-SGX/pal_security.h#L45)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

will change elements*/ -> elements */ in the next fixup or if things look fine before merge.
</blockquote></details>

Not relevant. Removed the comment itself.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 792 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAeNsbED7KNZWwcKay:-MLG2CCY5bmisujsAuW1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/sgx_main.c#L792)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 03:08 UTC, mkow requested changes
> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 159 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdMcl1X4i5QKb5Aod:-MLGCpvDAy7MG9qIkc-o:b-phyh03) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/db_main-x86_64.c#L159)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

sure, done.
</blockquote></details>

No need for the empty lines now (between the cpu-number-related assignments):

```C
    ci->online_logical_cores = g_pal_sec.online_logical_cores;
    ci->physical_cores_per_socket = g_pal_sec.physical_cores_per_socket;
    ci->cpu_socket = g_pal_sec.cpu_socket;
```
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 45 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdzLqCk4cEzlTa2Hx:-MLGDH5G5NT7IKiIpuvj:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/pal_security.h#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (see my previous comment)
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2020-11-04 06:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 159 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdMcl1X4i5QKb5Aod:-MLGupoZ6A_G4bFZ-8je:b-oscdjg) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/db_main-x86_64.c#L159)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need for the empty lines now (between the cpu-number-related assignments):

```C
    ci->online_logical_cores = g_pal_sec.online_logical_cores;
    ci->physical_cores_per_socket = g_pal_sec.physical_cores_per_socket;
    ci->cpu_socket = g_pal_sec.cpu_socket;
```
</blockquote></details>

sure, clubbed these together.
___
*[Pal/src/host/Linux-SGX/pal_security.h, line 45 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAdzLqCk4cEzlTa2Hx:-MLG-XnGD3DnhgctmKl3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/pal_security.h#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 10:04 UTC, dimakuv requested changes
> Reviewed 4 of 9 files at r7, 3 of 5 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHhY8qD0x8gR4-Bd_O:-MLHhY8qD0x8gR4-Bd_P:b-4l9pas) (no related file):*
I like the new names much better. It makes code much more self-explanatory.

---
___
*[Pal/include/arch/x86_64/pal-arch.h, line 190 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHg0mv5un73GDmCZ7s:-MLHg0mw994cNndyAv4_:bwkg061) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/include/arch/x86_64/pal-arch.h#L190)):*
> ```objc
> /* PAL_CPU_INFO holds /proc/cpuinfo data */
> typedef struct PAL_CPU_INFO_ {
>     /* Number of logical processors available in the host */
> ```

Can we also change all such comments `logical processor(s)` -> `logical core(s)`?
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHgNT_A0fuRA7bDYU5:-MLHgNTa3-KeRKTlhKE8:bm5hvqi) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/include/arch/x86_64/pal-arch.h#L192)):*
> ```objc
>     /* Number of logical processors available in the host */
>     PAL_NUM online_logical_cores;
>     /* Number of physical cores in a physical package (socket) */
> ```

Cam we also change `physical package` -> `socket` everywhere (maybe only keep it in this comment here because you show that these two are synonyms, but replace everywhere else)?
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHfUFTBP02NGtRiRqv:-MLHfUFTBP02NGtRiRqw:b-qqxx24) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/src/host/Linux/db_main-x86_64.c#L119)):*
> ```C
>     ci->online_logical_cores = online_logical_cores;
> 
>     int possible_cores = get_hw_resource("/sys/devices/system/cpu/possible", /*count=*/true);
> ```

Can we rename `possible_cores` -> `possible_logical_cores` for clarity?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 350 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHgCSqBdC8XaNh2Zni:-MLHgCSqBdC8XaNh2Znj:b-9k66c9) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/src/host/Linux-SGX/db_main.c#L350)):*
> ```C
>     int* cpu_socket = (int*)malloc(online_logical_cores * sizeof(int));
>     if (!cpu_socket) {
>         SGX_DBG(DBG_E, "Allocation for logical processor -> physical package mappings failed\n");
> ```

`core`, `socket`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 792 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAeNsbED7KNZWwcKay:-MLHgzaIAa2-p5R6GrwS:b-voqwen) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/sgx_main.c#L792)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (update terminology in comments)
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 773 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHgveq4xY5e7hwVorW:-MLHgverAt7JKTTsB8Rk:b-xgc52s) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/src/host/Linux-SGX/sgx_main.c#L773)):*
> ```C
>     pal_sec->online_logical_cores = online_logical_cores;
> 
>     int possible_cores = get_hw_resource("/sys/devices/system/cpu/possible", /*count=*/true);
> ```

ditto (`possible_logical_cores`)


<!-- Sent from Reviewable.io -->

2020-11-04 12:14 UTC, mkow reviewed
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux/db_main-x86_64.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHfUFTBP02NGtRiRqv:-MLIA9tl5xyZWAuFLOb_:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/src/host/Linux/db_main-x86_64.c#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename `possible_cores` -> `possible_logical_cores` for clarity?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2020-11-04 20:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 190 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHg0mv5un73GDmCZ7s:-MLJpaVLDcZ36aQhDQsu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/include/arch/x86_64/pal-arch.h#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we also change all such comments `logical processor(s)` -> `logical core(s)`?
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 192 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHgNT_A0fuRA7bDYU5:-MLJpwwWDdZw135USFOc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/include/arch/x86_64/pal-arch.h#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Cam we also change `physical package` -> `socket` everywhere (maybe only keep it in this comment here because you show that these two are synonyms, but replace everywhere else)?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHfUFTBP02NGtRiRqv:-MLJq6zh4qG0vddmzIRc:b-szhbky) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/src/host/Linux/db_main-x86_64.c#L119)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

sure, done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 350 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHgCSqBdC8XaNh2Zni:-MLJqTXR8wfxA_Tyj2mD:bs7wumb) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/src/host/Linux-SGX/db_main.c#L350)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`core`, `socket`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 792 at r6](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLAeNsbED7KNZWwcKay:-MLJqvRW9GiQ60UT17fj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d4404016440a80fc72860b6d26c0a5696e4812fb/Pal/src/host/Linux-SGX/sgx_main.c#L792)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (update terminology in comments)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 773 at r9](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLHgveq4xY5e7hwVorW:-MLJqkUt3-iVZR_lQzuR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e1ca9c824fa9abd319d8403925c38d74328cfbff/Pal/src/host/Linux-SGX/sgx_main.c#L773)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`possible_logical_cores`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 23:43 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-04 23:44 UTC, mkow commented
Jenkins, retest this please

2020-11-05 08:15 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLMTH6I1DngsQ2F2twG:-MLMTH6I1DngsQ2F2twH:bft2t20) (no related file):*
Jenkins failed with this:
```
Bootstrap.c: In function 'main':
Bootstrap.c:65:55: error: 'PAL_CPU_INFO {aka struct PAL_CPU_INFO_}' has no member named 'cpu_num'; did you mean 'cpu_vendor'?
     pal_printf("CPU num: %ld\n", pal_control.cpu_info.cpu_num);
                                                       ^~~~~~~
                                                       cpu_vendor
Makefile:116: recipe for target 'Bootstrap' failed
make[2]: Leaving directory '/home/jenkins/workspace/graphene-18.04/Pal/regression'
```

You forgot to modify `cpu_num` in one of the PAL test files. Please grep for `cpu_num` everywhere in Graphene code and rename remaining uses of this variable.

---


<!-- Sent from Reviewable.io -->

2020-11-05 16:31 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1910#-MLMTH6I1DngsQ2F2twG:-MLOEXUI1T-3ddh1THht:b6z5o9i) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenkins failed with this:
```
Bootstrap.c: In function 'main':
Bootstrap.c:65:55: error: 'PAL_CPU_INFO {aka struct PAL_CPU_INFO_}' has no member named 'cpu_num'; did you mean 'cpu_vendor'?
     pal_printf("CPU num: %ld\n", pal_control.cpu_info.cpu_num);
                                                       ^~~~~~~
                                                       cpu_vendor
Makefile:116: recipe for target 'Bootstrap' failed
make[2]: Leaving directory '/home/jenkins/workspace/graphene-18.04/Pal/regression'
```

You forgot to modify `cpu_num` in one of the PAL test files. Please grep for `cpu_num` everywhere in Graphene code and rename remaining uses of this variable.
</blockquote></details>

ah my bad, I tested LibOS/regression but not the PAL/regression. Fixed this now and it works for both cases.
@dimakuv thanks for checking.

---


<!-- Sent from Reviewable.io -->

2020-11-05 16:45 UTC, mkow commented
Jenkins, retest this please

2020-11-05 16:46 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-05 20:22 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-05 22:58 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 9 files at r6, 3 of 9 files at r7, 2 of 2 files at r9, 4 of 4 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-05 23:26 UTC, mkow commented
Jenkins, retest this please

2020-11-05 23:32 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-06 00:47 UTC, yamahata approved these changes
> Reviewed 4 of 4 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1910)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-06 00:57 UTC, merged