[LibOS]Enhance /dev/null stat
oscarlab/graphene pull request #1911
Opened 2020-10-21 08:25 UTC by llly

## Description of the changes 
Glibc function daemon() checks `st_rdev` field in struct stat of `/dev/null`. However current  pseudo dev_null_fs doesn't fill  `st_rdev` field. This PR updates `dev_null_stat` to fill `st_rdev` field with hard code value and leaves `dev_tty_fs_ops` unchanged.
Fixes #1891

2020-10-21 09:21 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/src/fs/dev/null.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1911#-MK9R0mx4JCbjRLDZsaD:-MK9R0my3n2SsofzqIR7:b-ct342s) ([raw file](https://github.com/oscarlab/graphene/blob/0d120121f75178eae96eddf3c2de95e3149b11e8/LibOS/shim/src/fs/dev/null.c#L10)):*
> ```C
>  */
> 
> #include <sys/sysmacros.h>
> ```

Please fix include grouping (see our style guide)
___
*[LibOS/shim/src/fs/dev/null.c, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/1911#-MK9R9sn3sN4oqlSgAfx:-MK9R9sn3sN4oqlSgAfy:b-nh3vqx) ([raw file](https://github.com/oscarlab/graphene/blob/0d120121f75178eae96eddf3c2de95e3149b11e8/LibOS/shim/src/fs/dev/null.c#L43)):*
> ```C
>  */
> #define DEV_NULL_MAJOR	1
> #define DEV_NULL_MINOR	3
> ```

tab -> space
___
*[LibOS/shim/src/fs/dev/null.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/1911#-MK9S8lO-RUgTnC4oqVK:-MK9S8lO-RUgTnC4oqVL:b-58s51q) ([raw file](https://github.com/oscarlab/graphene/blob/0d120121f75178eae96eddf3c2de95e3149b11e8/LibOS/shim/src/fs/dev/null.c#L49)):*
> ```C
> 
>     buf->st_mode = FILE_RW_MODE | S_IFCHR;
>     buf->st_rdev = makedev(DEV_NULL_MAJOR, DEV_NULL_MINOR);
> ```

This does not compile: `null.c:49: undefined reference to `gnu_dev_makedev'`.
Could you remove the include and inline this macro in shim_fs.h? We shouldn't depend on the host includes (we aren't building the host's Linux kernel, but the kernel version we emulate - moreover, we may want to be buildable on Windows someday...).


<!-- Sent from Reviewable.io -->

2020-10-21 11:52 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/src/fs/dev/null.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/1911#-MK9z0wY0_ZX23swZvE5:-MK9z0wY0_ZX23swZvE6:b-tdf8q5) ([raw file](https://github.com/oscarlab/graphene/blob/0d120121f75178eae96eddf3c2de95e3149b11e8/LibOS/shim/src/fs/dev/null.c#L40)):*
> ```C
> 
> /* st_rdev field in struct stat of /dev/null is (1,3).
>  * https://github.com/torvalds/linux/blob/master/drivers/char/mem.c#L978
> ```

This link will quickly go out of sync. Please use this one: `https://elixir.bootlin.com/linux/v5.9/source/drivers/char/mem.c#L950`
___
*[LibOS/shim/src/fs/dev/null.c, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/1911#-MK9zm6WC2NEOKaclrRA:-MK9zm6WC2NEOKaclrRB:bjb3waz) ([raw file](https://github.com/oscarlab/graphene/blob/fffd703b740c3c4c9e8893ab9d188b1f8a4097ef/LibOS/shim/src/fs/dev/null.c#L72)):*
> ```C
> };
> 
> /* /dev/tty is exactly the same as /dev/null in Graphene, so it has the same operations */
> ```

Could you keep this comment but modify it as follows:
`/* /dev/tty differs from /dev/null only in its st_rdev field (and thus in stat/hstat/open) */`


<!-- Sent from Reviewable.io -->

2020-10-22 08:13 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/include/shim_fs.h, line 497 at r2](https://reviewable.io/reviews/oscarlab/graphene/1911#-MKEMbUZCZuEQP3hFxpW:-MKEMbUZCZuEQP3hFxpX:b-pujsem) ([raw file](https://github.com/oscarlab/graphene/blob/9cf72e0508b132fc43634f63c91fa96445c498cc/LibOS/shim/include/shim_fs.h#L497)):*
> ```objc
> };
> 
> static inline __dev_t makedev(unsigned int __major, unsigned int __minor) {
> ```

Why do you use type `__dev_t` and not `dev_t`? Please just use `dev_t`.


<!-- Sent from Reviewable.io -->

2020-10-22 10:41 UTC, mkow requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/include/shim_fs.h, line 498 at r2](https://reviewable.io/reviews/oscarlab/graphene/1911#-MKEt7TU-Sk5DSiGD1CF:-MKEt7TU-Sk5DSiGD1CG:bl4kfds) ([raw file](https://github.com/oscarlab/graphene/blob/9cf72e0508b132fc43634f63c91fa96445c498cc/LibOS/shim/include/shim_fs.h#L498)):*
> ```objc
> 
> static inline __dev_t makedev(unsigned int __major, unsigned int __minor) {
>     __dev_t __dev;
> ```

This is a reserved name in C. See https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers. Same for argument names you used.
___
*[LibOS/shim/include/shim_fs.h, line 502 at r2](https://reviewable.io/reviews/oscarlab/graphene/1911#-MKEt3ur3onrQtXn3ia9:-MKEt3ur3onrQtXn3iaA:bb5vh5o) ([raw file](https://github.com/oscarlab/graphene/blob/9cf72e0508b132fc43634f63c91fa96445c498cc/LibOS/shim/include/shim_fs.h#L502)):*
> ```objc
>     __dev |= (((__dev_t) (__major & 0xfffff000u)) << 32);
>     __dev |= (((__dev_t) (__minor & 0x000000ffu)) <<  0);
>     __dev |= (((__dev_t) (__minor & 0xffffff00u)) << 12);
> ```

no space after casts


<!-- Sent from Reviewable.io -->

2020-10-22 16:40 UTC, yamahata approved these changes
except makedev(), it looks good to me.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911#-:-MKGAflpDfn_Gw17e_Rt:b-vqsfbn)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)



<!-- Sent from Reviewable.io -->

2020-10-23 14:15 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)



<!-- Sent from Reviewable.io -->

2020-10-23 14:15 UTC, dimakuv commented
Jenkins, test this please

2020-10-23 19:10 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)



<!-- Sent from Reviewable.io -->

2020-10-26 23:52 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-27 00:00 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-10-27 00:00 UTC, mkow commented
Jenkins, retest this please

2020-10-27 00:43 UTC, mkow commented
Jenkins, retest Jenkins-18.04 please (apps.LTP.fork11 timed out, known issue)

2020-10-27 00:53 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1911)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-27 01:10 UTC, merged