[LibOS] Fix dangling pointer `dent` on connect(AF_UNIX)
oscarlab/graphene pull request #1913
Opened 2020-10-22 10:19 UTC by dimakuv

## Description of the changes 

When connecting on a named UNIX domain socket, the `connect()` syscall checks if the socket path exists via `path_lookupat(&dent)`. However, `path_lookupat()` may return error and *not* update `dent` allocated on stack. In this case, `dent` contains garbage, and Graphene fails.

This PR fixes this via explicit `dent = NULL`.

## How to test this PR? 

A `unix` LibOS test is updated to test this.

2020-10-22 10:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[LibOS/shim/src/sys/shim_socket.c, line 747 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKEolzZAfP978pHX5n-:-MKEolz_1PutLfDi6Ong:bdabtea) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_socket.c#L747)):*
> ```C
>         struct sockaddr_un* saddr = (struct sockaddr_un*)addr;
>         char* spath               = saddr->sun_path;
>         struct shim_dentry* dent  = NULL;
> ```

FYI: This was the actual bug in Graphene.
___
*[LibOS/shim/src/sys/shim_socket.c, line 753 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKEopwi8AlAqqMZr57w:-MKEopwi8AlAqqMZr57x:bc23i9o) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_socket.c#L753)):*
> ```C
>             // expected case is that the name is free (and we get the dent to
>             // populate the name)
>             if (ret != -ENOENT || !dent)
> ```

Note how we check `!dent` here, even though it may be uninitialized.
___
*[LibOS/shim/src/sys/shim_stat.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKEowkxA1bulEAvNEoq:-MKEowkxA1bulEAvNEor:bdvzr2d) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_stat.c#L226)):*
> ```C
>     }
> 
>     struct shim_dentry* dent = NULL;
> ```

FYI: This I added just for sanity. (I went through all usages of `path_lookupat()` and found only this other case where `dent` was not nullified.)


<!-- Sent from Reviewable.io -->

2020-10-22 13:30 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_socket.c, line 753 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKEopwi8AlAqqMZr57w:-MKFRK1E-I--IW8yQDAl:b-cyvl16) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_socket.c#L753)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Note how we check `!dent` here, even though it may be uninitialized.
</blockquote></details>

Hmm, I don't like the fix in the current form. In general, I'd prefer to never assume values of the output arguments in case the call failed, such properties are hard to preserve in the implementation and it's easy to slip such a bug into it later.
Also, why do we check `dent` here when `ret == -ENOENT`? How can `dent` contain anything else than `NULL` then? (assuming `path_lookupat` doesn't fill it on errors).
___
*[LibOS/shim/test/regression/unix.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKFV-974arMv6IiFoPk:-MKFV-974arMv6IiFoPl:boexl4s) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/test/regression/unix.c#L185)):*
> ```C
> 
> int main(int argc, char** argv) {
>     /* check that we cannot connect to the non-existing UNIX domain socket */
> ```

nitpick: `to the non-existing` -> `to a non-existing`


<!-- Sent from Reviewable.io -->

2020-10-22 16:26 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKG5D_xA0wTE0qtv2tj:-MKG5D_xA0wTE0qtv2tk:b10c5im) (no related file):*
I've roughly grepped for path_lookup(). It seems heavily broken.

ENOENT + returned dent != NULL: this sounds very fragile.
- grep showed many other callers don't check it. Also it looks reference count leak.
- such case happends Only with LOOKUP_CREATE?

Probably 
- LOOKUP_CREATE_NON_EXIST in addition to LOOKUP_CREATE?
then ENOENT + dent != NULL case can be covered?

- when LOOKUP_CREATE: negative cache case should success?

- without LOOKUP_CREATE, LOOKUP_CREATE_NON_EXIST, negative cache means ENOENT and dent untouched.
 

---
___
*[LibOS/shim/src/sys/shim_socket.c, line 759 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKG6Dz2B62euc9NNKkc:-MKG6Dz30EUDsLiZrcO-:brmp259) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_socket.c#L759)):*
> ```C
>         if (dent->state & DENTRY_VALID && !(dent->state & DENTRY_NEGATIVE) &&
>                 dent->fs != &socket_builtin_fs) {
>             ret = -ECONNREFUSED;
> ```

Probably new flag something like LOOKUP_CREATE_NON_EXIST to cover this case.
then check if ret is EEXIST.


<!-- Sent from Reviewable.io -->

2020-10-22 16:28 UTC, yamahata reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-10-22 20:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKG5D_xA0wTE0qtv2tj:-MKGvbkY55Y0AxN7I5RI:b26crxy) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

I've roughly grepped for path_lookup(). It seems heavily broken.

ENOENT + returned dent != NULL: this sounds very fragile.
- grep showed many other callers don't check it. Also it looks reference count leak.
- such case happends Only with LOOKUP_CREATE?

Probably 
- LOOKUP_CREATE_NON_EXIST in addition to LOOKUP_CREATE?
then ENOENT + dent != NULL case can be covered?

- when LOOKUP_CREATE: negative cache case should success?

- without LOOKUP_CREATE, LOOKUP_CREATE_NON_EXIST, negative cache means ENOENT and dent untouched.
 

</blockquote></details>

Yes, agreed. But for now I just want to have a quick fix, and then someone will re-write the whole FS subsystem.

---
___
*[LibOS/shim/src/sys/shim_socket.c, line 753 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKEopwi8AlAqqMZr57w:-MKGuLlz59RvS9i_m0VU:bswrpez) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_socket.c#L753)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I don't like the fix in the current form. In general, I'd prefer to never assume values of the output arguments in case the call failed, such properties are hard to preserve in the implementation and it's easy to slip such a bug into it later.
Also, why do we check `dent` here when `ret == -ENOENT`? How can `dent` contain anything else than `NULL` then? (assuming `path_lookupat` doesn't fill it on errors).
</blockquote></details>

Well, yes, I completely agree. But for now I would like to *not* go on a crusade of fixing `path_lookupat()`. It is a known fact that our FS code is heavily broken (see Isaku's comments), and I would keep away from modifying it right now.

Regarding this bug, `path_lookupat()` abuses `-ENOENT` for two cases:
- actual failure: one of the subdirs was not found, i.e., the file cannot be created at all (`dent == NULL`)
- benign failure: all subdirs are found but the file doesn't exist -- can be created (`dent != NULL`)

The code here checks for the actual failure. That's the crazy semantics we currently have. I don't want to touch the FS code, not now.


<!-- Sent from Reviewable.io -->

2020-10-22 21:06 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKG5D_xA0wTE0qtv2tj:-MKH7NZ8C7YePS1lQk4z:b-wtgi68) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, agreed. But for now I just want to have a quick fix, and then someone will re-write the whole FS subsystem.
</blockquote></details>

ok. Can you please recoerd what is broken. as issue or comment in the code.
As quick work around, I don’t have strong opinion. I’m fine with it.

---


<!-- Sent from Reviewable.io -->

2020-10-26 13:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKG5D_xA0wTE0qtv2tj:-MK_-Hzh0P39OhXZoyKt:b-o8vhue) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

ok. Can you please recoerd what is broken. as issue or comment in the code.
As quick work around, I don’t have strong opinion. I’m fine with it.
</blockquote></details>

Done. Added comments in the code.

---
___
*[LibOS/shim/src/sys/shim_socket.c, line 753 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKEopwi8AlAqqMZr57w:-MK_-O_GBtIfe3aLX8rk:b-jp7hwd) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_socket.c#L753)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, yes, I completely agree. But for now I would like to *not* go on a crusade of fixing `path_lookupat()`. It is a known fact that our FS code is heavily broken (see Isaku's comments), and I would keep away from modifying it right now.

Regarding this bug, `path_lookupat()` abuses `-ENOENT` for two cases:
- actual failure: one of the subdirs was not found, i.e., the file cannot be created at all (`dent == NULL`)
- benign failure: all subdirs are found but the file doesn't exist -- can be created (`dent != NULL`)

The code here checks for the actual failure. That's the crazy semantics we currently have. I don't want to touch the FS code, not now.
</blockquote></details>

Update: added more comments.
___
*[LibOS/shim/src/sys/shim_socket.c, line 759 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKG6Dz2B62euc9NNKkc:-MK_-R0G5D1h9DDb-2Cy:b16wrt0) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/src/sys/shim_socket.c#L759)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Probably new flag something like LOOKUP_CREATE_NON_EXIST to cover this case.
then check if ret is EEXIST.

</blockquote></details>

Done (well, skipped because we agreed that it is for another PR).
___
*[LibOS/shim/test/regression/unix.c, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKFV-974arMv6IiFoPk:-MK_-ku-ApDqD55SdbYd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1ba4f0f2d52712250b99bde03d2a42161ef58343/LibOS/shim/test/regression/unix.c#L185)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: `to the non-existing` -> `to a non-existing`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-26 18:09 UTC, yamahata approved these changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: 1 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)



<!-- Sent from Reviewable.io -->

2020-10-27 00:24 UTC, mkow requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_socket.c, line 481 at r2](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKbQskJCyEgisHXWXK0:-MKbQskJCyEgisHXWXK1:blzbwhf) ([raw file](https://github.com/oscarlab/graphene/blob/75e334f30cbf85f8d32532e87ed288704a632507/LibOS/shim/src/sys/shim_socket.c#L481)):*
> ```
> DEP 7/3/17:
> ```
The comment was substantially changed, I'd drop the old signature.


<!-- Sent from Reviewable.io -->

2020-10-27 09:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 481 at r2](https://reviewable.io/reviews/oscarlab/graphene/1913#-MKbQskJCyEgisHXWXK0:-MKdS22t6k1MVM2dEu5d:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/75e334f30cbf85f8d32532e87ed288704a632507/LibOS/shim/src/sys/shim_socket.c#L481)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> DEP 7/3/17:
> ```
The comment was substantially changed, I'd drop the old signature.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-27 13:34 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-27 14:04 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (Glibc build failed, Jenkins issue?)

2020-10-27 14:13 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (Glibc build failed, Jenkins issue?)

2020-10-27 14:15 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (Glibc build failed, Jenkins issue?)

2020-10-27 14:32 UTC, dimakuv commented
This PR passes Jenkins. `Jenkins-SGX-apps` failed on a particular Jenkins worker; it works on any other worker.

2020-10-27 15:01 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-27 15:09 UTC, yamahata approved these changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-27 15:25 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1913)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-27 16:25 UTC, merged