Loader rework part 3: Disallow starting without an executable
oscarlab/graphene pull request #1915
Opened 2020-10-23 09:28 UTC by mkow

## Description of the changes 

Previously, it was possible to use Graphene without the main executable (e.g. having only preloaded libraries). We aren't aware of anyone using this weird option, but worse, it led to a very bad UX when the user made mistakes - e.g. having a typo in the manifest or executable name could lead to Graphene starting without errors, but doing nothing.

Fixes #1905.

## How to test this PR? 

See #1905 for reproduction steps for an example of a problem fixed by this change.

2020-10-23 14:37 UTC, dimakuv requested changes
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1915)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/Makefile.manifest, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/1915#-MKKslw01IAH8d0h4mR1:-MKKslw12RgTnoqa-wle:bgwbvmj) ([raw file](https://github.com/oscarlab/graphene/blob/e587869e13010e6f8b66e02cd694f24a72fe70de/Pal/src/host/Linux-SGX/Makefile.manifest#L50)):*
> ```
> endif
> include $(addsuffix .manifest.sgx.d,$(call drop_manifest_suffix,$(target)))
> endif
> ```

I don't think you need to delete these lines. The comment above doesn't describe these lines.


<!-- Sent from Reviewable.io -->

2020-10-23 19:18 UTC, yamahata submitted a review, later dismissed
Except Makefile.manifest, it looks good to me.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1915#-:-MKLtT135VVVOBNng4d9:b10v6bc)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/Makefile.manifest, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/1915#-MKKslw01IAH8d0h4mR1:-MKLsR5nAjM71TMOIni0:bmqlltn) ([raw file](https://github.com/oscarlab/graphene/blob/e587869e13010e6f8b66e02cd694f24a72fe70de/Pal/src/host/Linux-SGX/Makefile.manifest#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think you need to delete these lines. The comment above doesn't describe these lines.
</blockquote></details>

That's right. Thank you for pointing it out.


<!-- Sent from Reviewable.io -->

2020-10-27 01:00 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1915)* status: 12 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/Makefile.manifest, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/1915#-MKKslw01IAH8d0h4mR1:-MKbYnv64594ARhPZnYu:b-snyv5p) ([raw file](https://github.com/oscarlab/graphene/blob/e587869e13010e6f8b66e02cd694f24a72fe70de/Pal/src/host/Linux-SGX/Makefile.manifest#L50)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

That's right. Thank you for pointing it out.
</blockquote></details>

I held Ctrl+X for a bit too long :) I also had to fix up the rule above. I missed this because the build started to fail only after `make clean`.


<!-- Sent from Reviewable.io -->

2020-10-27 09:49 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1915)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-27 11:37 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1915)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-27 14:40 UTC, yamahata approved these changes
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1915)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-27 14:41 UTC, merged