[Pal/Linux-SGX] Support in-kernel SGX driver v39
oscarlab/graphene pull request #1916
Opened 2020-10-26 10:06 UTC by dimakuv

## Description of the changes 

SGX driver v39 removes `count` field and returns "number of bytes added" as return value of the SGX_IOC_ENCLAVE_ADD_PAGES ioctl. It also caps the maximum number of bytes to be added as 1MB, or 256 pages. Thus, we must loop on the ADD_PAGES ioctl until all pages are added and first check `ret > 0` and only then check `count` field (to support all versions of the SGX driver).

For additional details, see:
- https://lore.kernel.org/linux-sgx/20200908190042.24895-1-jarkko.sakkinen@linux.intel.com/#r
- https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-sgx.git/tree/arch/x86/kernel/cpu/sgx/ioctl.c?h=v39
- https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/linux-sgx.git/tree/arch/x86/include/uapi/asm/sgx.h?h=v39

## How to test this PR? 

I only tested on older (v33) DCAP SGX driver.

**TODO**: Could someone test this on in-kernel v39?

2020-10-26 18:12 UTC, yamahata approved these changes
Although I haven't tested it myself, the change itself looks good to me.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916#-:-MKa63ZgDs8knjoecXID:bcckr1x)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-10-26 23:41 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1916#-MKb9xgO-mwJX5YXkCDb:-MKb9xgO-mwJX5YXkCDc:b-hudc5d) (no related file):*
> TODO: Could someone test this on in-kernel v39?

me or @woju can do this tomorrow

---
___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 265 at r1](https://reviewable.io/reviews/oscarlab/graphene/1916#-MKbGgjl8VvfrvIMqm-X:-MKbGgjmEK98cHJ4Do7I:buh2xuv) ([raw file](https://github.com/oscarlab/graphene/blob/06c5827739926d33a3ec4b6f592618541ac6200b/Pal/src/host/Linux-SGX/sgx_framework.c#L265)):*
> ```C
> #ifdef SGX_DCAP_16_OR_LATER
>     if (!user_addr && g_zero_pages_size < size) {
>         /* not enough contigious zero pages to back up enclave pages, allocate more */
> ```

We won't need this logic once we drop support for older versions of the driver and introduce the mirrored size cap here ourselves (the huge zero allocation is useless on the new driver). Could you add a TODO?


<!-- Sent from Reviewable.io -->

2020-10-27 09:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_framework.c, line 265 at r1](https://reviewable.io/reviews/oscarlab/graphene/1916#-MKbGgjl8VvfrvIMqm-X:-MKdQtJ24SnaqlJ9Qlxo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/06c5827739926d33a3ec4b6f592618541ac6200b/Pal/src/host/Linux-SGX/sgx_framework.c#L265)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We won't need this logic once we drop support for older versions of the driver and introduce the mirrored size cap here ourselves (the huge zero allocation is useless on the new driver). Could you add a TODO?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 16:03 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1916#-MKb9xgO-mwJX5YXkCDb:-MKeH4NW2u9SHQTK6b_P:b-wbcaam) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> TODO: Could someone test this on in-kernel v39?

me or @woju can do this tomorrow
</blockquote></details>

Ok, seems all our regression tests pass on v40rc2 (the newest driver atm, I think), although, I had to fix one thing in Graphene to allow this: we have to change the mapping in `link-intel-driver.py` to have `'include/uapi/asm/sgx.h': '/dev/sgx/enclave',`. The problem is that it conflicts with an existing entry, which maps the same header path to `/dev/sgx`. I guess this is from the older driver version? Can we just drop support for it?

Also, a non-standard config I had to change to make it work: I had to chmod `/dev/sgx/enclave` to 666. I think we have now a design conflict with the newer driver revisions - they probably want everyone to use a daemon to talk to this device? Anyways, this is an old issue and we even have this documented, but I think we'll need to discuss it at some point.

For the record: the driver path variable I used was: `ISGX_DRIVER_PATH=/usr/src/linux-headers-5.9.0-lock-sgx40rc1/arch/x86/`.

---


<!-- Sent from Reviewable.io -->

2020-10-30 09:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1916#-MKb9xgO-mwJX5YXkCDb:-MKsrQBK8cMVkAlIw1DG:b1mvhei) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, seems all our regression tests pass on v40rc2 (the newest driver atm, I think), although, I had to fix one thing in Graphene to allow this: we have to change the mapping in `link-intel-driver.py` to have `'include/uapi/asm/sgx.h': '/dev/sgx/enclave',`. The problem is that it conflicts with an existing entry, which maps the same header path to `/dev/sgx`. I guess this is from the older driver version? Can we just drop support for it?

Also, a non-standard config I had to change to make it work: I had to chmod `/dev/sgx/enclave` to 666. I think we have now a design conflict with the newer driver revisions - they probably want everyone to use a daemon to talk to this device? Anyways, this is an old issue and we even have this documented, but I think we'll need to discuss it at some point.

For the record: the driver path variable I used was: `ISGX_DRIVER_PATH=/usr/src/linux-headers-5.9.0-lock-sgx40rc1/arch/x86/`.
</blockquote></details>

OK, good point about the driver. `/dev/sgx` was used by older in-kernel SGX drivers (version 1 to 19) and therefore was ported to older DCAP SGX drivers (versions 1.0 to 1.5). But nobody should use these old versions any more, so I created an accompanying PR https://github.com/oscarlab/graphene-sgx-driver/pull/30. Please review that PR and we'll merge them together.

About `chmod 666`. Yes, there was something like this (though I observed it only on some platforms, so I can't say what exactly changes). Let's keep it for another PR.

---


<!-- Sent from Reviewable.io -->

2020-10-31 01:56 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1916#-MKwMH2ABTO9pqe3pzF-:-MKwMH2B4WlK1Zh8p49G:b-g0arkx) (no related file):*
depends on oscarlab/graphene-sgx-driver#30

---


<!-- Sent from Reviewable.io -->

2020-11-02 08:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1916#-MKwMH2ABTO9pqe3pzF-:-ML77WIS5xLG0cHJoON-:b-r1798y) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

depends on oscarlab/graphene-sgx-driver#30
</blockquote></details>

FYI: Updated that PR per your comments and fixed the commit hash here.

---


<!-- Sent from Reviewable.io -->

2020-11-02 09:56 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`setrlimit01` LTP test failed, unrelated)

2020-11-02 17:52 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-11-02 18:10 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1916)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-02 20:05 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (previous landed on worker with AESM dead)

2020-11-02 20:05 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04-apps please (previous landed on worker with AESM dead)

2020-11-03 00:37 UTC, merged