[Pal/Linux-SGX] Allow EPID attestation even with DCAP SGX driver
oscarlab/graphene pull request #1917
Opened 2020-10-26 12:50 UTC by dimakuv

## Description of the changes 

Previously, Graphene assumed that if it was built with the DCAP SGX driver or in-kernel SGX driver, then it should use DCAP/ECDSA based attestation. In fact, the SGX driver has nothing to do with the attestation scheme. This commit allows to use EPID based attestation even when Graphene is built with the DCAP SGX driver.

See #1914 for more context.

## How to test this PR? 

All tests must pass (we have Attestation tests in PAL, LibOS, ra-tls-mbedtls, and ra-tls-secret-prov regressions).

2020-10-26 18:19 UTC, yamahata submitted a review, later dismissed
Although I haven't tested it, it looks good to me only based on code review.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917#-:-MKa7cJR-tjQgSW3FjtS:b20xzel)* status: 0 of 17 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" and "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-01 18:02 UTC, mkow requested changes
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "DONTMERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 393 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3rzE60cLUf7iGwlPB:-ML3rzE73ZcW0NBOrnOt:b-oce4ym) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/db_misc.c#L393)):*
> ```
> (unset them for sanity)
> ```
I'd add "we" in front, imperative in parenthesis sounds weird to me.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.h, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3tIvj44FuuXxDkaVY:-ML3tIvj44FuuXxDkaVZ:b-e6ppym) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/enclave_ocalls.h#L102)):*
> ```objc
>  *
>  * \param[in]  spid       Software provider ID (SPID); if NULL then DCAP/ECDSA is used.
>  * \param[in]  linkable   Quote type (linkable vs unlinkable).
> ```

This is only for EPID? Could you add that this is ignored for DCAP/ECDSA?
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3u4t72YHldmBKbSlW:-ML3u4t72YHldmBKbSlX:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_attest.h#L83)):*
> ```objc
>  * \param[in]  nonce        16B nonce to be included in the quote for freshness.
>  * \param[in]  report_data  64B bytestring to be included in the report and the quote.
>  * \param[in]  linkable     Quote type (linkable vs unlinkable).
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_internal.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3uPRe7IrFg_EY0N_s:-ML3uPRfEFtNFa0PwW-L:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_internal.h#L105)):*
> ```objc
>  *
>  * \param[in]  spid       Software provider ID (SPID); if NULL then DCAP/ECDSA is used.
>  * \param[in]  linkable   Quote type (linkable vs unlinkable).
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 886 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3ufSu4fjI3OEnCl4h:-ML3ufSu4fjI3OEnCl4i:b-wkpo0f) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_main.c#L886)):*
> ```C
>         bool is_epid; /* EPID is used if SPID is specified in manifest, otherwise DCAP/ECDSA */
>         is_epid = get_config(enclave->config, "sgx.ra_client_spid", cfgbuf, sizeof(cfgbuf)) > 0;
>         SGX_DBG(DBG_E, "============ is_epid = %d, spid = %s\n", is_epid, cfgbuf);
> ```

Could you rather print something like "Using {SPID,DCAP/ECDSA} attestation"? Would be much more readable for users.
And maybe without this `====`.
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 188 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3vNZc0czlfJsTQQE2:-ML3vNZc0czlfJsTQQE3:b9hmbo4) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/tools/README.rst#L188)):*
> ```reStructuredText
> 
> - ``sgx.remote_attestation = 1`` -- remote attestation is enabled.
> - ``sgx.ra_client_spid = <empty string>`` -- empty SPID hints that it is DCAP attestation.
> ```

"hints" sounds like this is just an input to some heuristic which decides which method to use, while this alone is determining the mode.


<!-- Sent from Reviewable.io -->

2020-11-02 09:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917)* status: 11 of 17 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 393 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3rzE60cLUf7iGwlPB:-ML7CoJCBE-dA_aNixjs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/db_misc.c#L393)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> (unset them for sanity)
> ```
I'd add "we" in front, imperative in parenthesis sounds weird to me.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.h, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3tIvj44FuuXxDkaVY:-ML7B6rm4hBagQO1F6mr:b30j89i) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/enclave_ocalls.h#L102)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is only for EPID? Could you add that this is ignored for DCAP/ECDSA?
</blockquote></details>

Done. Yes, `linkable` is for EPID only. Interestingly, `nonce` is also only for EPID. (If I remember correctly, there is no real need in nonce, so the SGX PSW/DCAP developers removed the nonce field in the newer DCAP scheme.)
___
*[Pal/src/host/Linux-SGX/sgx_attest.h, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3u4t72YHldmBKbSlW:-ML7C65o7UN6gj5OAHGN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_attest.h#L83)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_internal.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3uPRe7IrFg_EY0N_s:-ML7CLvl-rkoS3Q2Pz9G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_internal.h#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 886 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3ufSu4fjI3OEnCl4h:-ML7DErJEJg4Oipc6kIo:brfet88) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_main.c#L886)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you rather print something like "Using {SPID,DCAP/ECDSA} attestation"? Would be much more readable for users.
And maybe without this `====`.
</blockquote></details>

Done. This was a debug print (to debug Jenkins failures). I forgot to remove it before.
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 188 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3vNZc0czlfJsTQQE2:-ML7CevO0gS-J64ALWWn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/tools/README.rst#L188)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"hints" sounds like this is just an input to some heuristic which decides which method to use, while this alone is determining the mode.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-02 18:06 UTC, mkow requested changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 886 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3ufSu4fjI3OEnCl4h:-ML97cQ60TczRjuv41Kf:b4gp9gn) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_main.c#L886)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. This was a debug print (to debug Jenkins failures). I forgot to remove it before.
</blockquote></details>

I think it would be still useful to print the mode used, just format it nicer


<!-- Sent from Reviewable.io -->

2020-11-03 10:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917)* status: 16 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 886 at r1](https://reviewable.io/reviews/oscarlab/graphene/1917#-ML3ufSu4fjI3OEnCl4h:-MLCk-Gd-hfU0s6hp__Q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/13becfaf3fff357bd041b048428350b05fff4568/Pal/src/host/Linux-SGX/sgx_main.c#L886)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it would be still useful to print the mode used, just format it nicer
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py, line 820 at r3](https://reviewable.io/reviews/oscarlab/graphene/1917#-MLCk0IHAaSsne0FjG0E:-MLCk0IHAaSsne0FjG0F:b-2wfuhg) ([raw file](https://github.com/oscarlab/graphene/blob/a91b392f70ee34c854f1d4086f34410016af1711/Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py#L820)):*
> ```Python
>             print("    DCAP/ECDSA")
>         else:
>             print("    EPID (spid = %s, linkable = %s)" % (spid, linkable))
> ```

FYI: Added information on the embedded-in-manifest attestation scheme (during manifest build) as requested in https://github.com/oscarlab/graphene/issues/1914#issuecomment-720978639.


<!-- Sent from Reviewable.io -->

2020-11-03 12:33 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-03 15:03 UTC, mkow approved these changes
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-03 15:17 UTC, yamahata approved these changes
> Reviewed 5 of 17 files at r1, 5 of 6 files at r2, 1 of 2 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1917)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-03 17:14 UTC, merged