[GSC] Fix test makefile to correctly use configuration file
oscarlab/graphene pull request #1920
Opened 2020-10-27 12:35 UTC by vahldiek

## Description of the changes 

This PR fixes an issue in the test Makefile of GSC. The issue was introduced when the Makefile switched to using dedicated configuration files per distribution. As a result some Makefile targets include the test case in the configuration file name which should not be the case.

## How to test this PR? 

Use a test case that does not have a specific Makefile target like `hello-world` and then run the respective test for this test case.

2020-10-27 12:54 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1920)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Tools/gsc/test/Makefile, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/1920#-MKe6IR14dEp2HvAvT8Z:-MKe6IR14dEp2HvAvT8_:b-epfv6f) ([raw file](https://github.com/oscarlab/graphene/blob/ad492d863f2ba89180252772ee3438024f032c8b/Tools/gsc/test/Makefile#L79)):*
> ```Makefile
> 
> .PRECIOUS: gsc-%-python3-base
> gsc-%-python3-base: %-python3 graphene-%
> ```

Btw, shouldn't this target be moved to before `gsc-%`? I thought that Makefile goes through the file from top to bottom to find a first corresponding target. In this case, won't this `gsc-%-python3-base` target never be executed?


<!-- Sent from Reviewable.io -->

2020-10-27 17:36 UTC, vahldiek commented
___
*[Tools/gsc/test/Makefile, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/1920#-MKe6IR14dEp2HvAvT8Z:-MKeHR9-1Pekk_WlbA_8:b4vvy3h) ([raw file](https://github.com/oscarlab/graphene/blob/ad492d863f2ba89180252772ee3438024f032c8b/Tools/gsc/test/Makefile#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, shouldn't this target be moved to before `gsc-%`? I thought that Makefile goes through the file from top to bottom to find a first corresponding target. In this case, won't this `gsc-%-python3-base` target never be executed?
</blockquote></details>

I can confirm that it is used. The previous target `gsc-%: %` is not used, since `%` evaluates to `ubuntu18.04-python3-base` and this image is never build, hence the dependency breaks. I think this image exists after running make once, hence when run a second time it may create problems. I've pushed a fix for this.

Thanks for noticing.


<!-- Sent from Reviewable.io -->

2020-10-27 17:37 UTC, vahldiek reviewed
I've made several additional changes to the makefile to provide better handling in particular for the base-python3 image. I will reflect this in the PR description in a second. To test this, we can now also run Jenkins GSC pipeline.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1920#-:-MKf7WXS5MtqTJLZgZpS:b-xn8xqm)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-10-28 09:26 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1920)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-28 09:27 UTC, dimakuv commented
Jenkins, test Jenkins-SGX-gsc please

2020-10-28 09:50 UTC, dimakuv commented
For everyone: for some reason GitHub doesn't show the status of `Jenkins-SGX-gsc` pipeline, but I verified manually and this PR passed it. So we're good.

2020-10-31 02:53 UTC, mkow commented
Jenkins, retest Jenkins-SGX-gsc please

2020-10-31 02:57 UTC, mkow submitted a review, later dismissed
This time it worked :)

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1920#-:-MKwZsOq3HFwReasfC_D:bt2nshs)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-01 19:46 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1920)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-01 19:46 UTC, mkow commented
Jenkins, retest this please

2020-11-01 20:39 UTC, mkow commented
Jenkins, retest Jenkins-SGX-apps please (landed on slave-leeroy, which seems to be broken)

2020-11-01 20:41 UTC, mkow commented
Jenkins, retest Jenkins-18.04 please (`apps.LTP.fork11` timed out, known issue)

2020-11-01 20:42 UTC, mkow commented
Jenkins, retest Jenkins-SGX-apps please (aaaand, let's schedule it again, while broken slave-leeroy is busy with the previous retest)

2020-11-01 20:54 UTC, mkow commented
Jenkins, retest Jenkins-SGX-apps please (broken slave-leeroy again...)

2020-11-01 20:56 UTC, mkow commented
Jenkins, retest Jenkins-SGX-apps please (broken slave-leeroy again...)

2020-11-02 08:47 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (broken slave-leeroy again; now it's my turn to try)

2020-11-02 09:58 UTC, dimakuv approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1920#-:-ML7O4J956Vtylnfk6eT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-02 09:59 UTC, merged