moving from a list based storage of futex list, to an avl tree based …
oscarlab/graphene pull request #1921
Opened 2020-10-27 13:23 UTC by aneessahib

…structure in order to improve futex search times when there are a lot of threads in operation.

## Description of the changes 

## How to test this PR?

2020-10-27 13:29 UTC, aneessahib reviewed
improper vma references to be removed.

2020-10-27 14:56 UTC, pwmarcz reviewed
Thanks for the PR!

Some stylistic remarks regarding the whole commit:

* Please make sure that your changes use spaces for indentation instead of tabs, as the rest of the code does. You can see the difference here in Reviewable. It should be a matter of configuring your editor.
* The commit message needs to also follow the project's style, you can look at other commits in the project. In short:
  * The commit title is way too long - as you can see, Github and Reviewable do not display the whole title, and terminal tools will wrap it. The first line should only explain "what" you're doing, then (after empty line) you can add a paragraph of explanation "why". Remember to word-wrap the paragraph at 72 columns if necessary.
  * There needs to be a prefix in the title describing the location of change. In this case, that would be `[LibOS]`.
  * The commit title should be present tense imperative (example: "Replace futex list with AVL tree").

See also coding style guidelines: https://graphene.readthedocs.io/en/latest/devel/coding-style.html

I'm not sure if Graphene has written commit guidelines, but I think we mostly follow the style described here: https://chris.beams.io/posts/git-commit/

Sorry if it sounds like a lot for such a simple change. I assume you will be contributing more in the future, so I hope I can help you familiarize with the project's style.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921#-:-MKeMVNS89jmONVk-5xY:b-42id5x)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[LibOS/shim/src/sys/shim_futex.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeHzYS5BrwPt1pxgYg:-MKeHzYS5BrwPt1pxgYh:bxvk0ky) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L31)):*
> ```C
> #include "shim_types.h"
> #include "spinlock.h"
> #include "avl_tree.h"
> ```

There should be an empty line between  the `#include` and the next declaration.
Can you also make sure the file is included is in alphabetical order, i.e. just after `assert.h`?
___
*[LibOS/shim/src/sys/shim_futex.c, line 53 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIGjs7GaYFsqAe_Zv:-MKeIGjs7GaYFsqAe_Zw:b-zgnh7i) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L53)):*
> ```C
>     LISTP_TYPE(futex_waiter) waiters;
>     LIST_TYPE(shim_futex) list;
>     union {
> ```

This looks like copy-paste from `shim_vma`. We only need the `tree_node`. And probably no comment is necessary.

(Looks like you mentioned that above, but I'm adding a comment to keep track).
___
*[LibOS/shim/src/sys/shim_futex.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIbo81-4hvsdtALGR:-MKeIbo81-4hvsdtALGS:b-r7bbi0) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L66)):*
> ```C
> };
> static struct shim_futex* _lookup_futex(uintptr_t);
> static bool futex_tree_cmp(struct avl_tree_node* node_a, struct avl_tree_node* node_b) {
> ```

Please add an empty line before and after the function definition, so that it's easier to read.
___
*[LibOS/shim/src/sys/shim_futex.c, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeYJXG7HmKa772nv8O:-MKeYJXG7HmKa772nv8P:b-x7msxo) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L70)):*
> ```C
>     struct shim_futex* b = container_of(node_b, struct shim_futex, tree_node);
> 
>     return a->uaddr <= b->uaddr;
> ```

I think you should compare the addresses as numbers, i.e. cast them to `uintptr_t` first. Comparing (unrelated, e.g. not in the same array or struct) pointers directly is unspecified behaviour in C.
___
*[LibOS/shim/src/sys/shim_futex.c, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeJ2HCBWrZHUBc5abo:-MKeJ2HD62E4YDZ-Aiu7:b-cd5sbg) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L72)):*
> ```C
>     return a->uaddr <= b->uaddr;
> }
> static struct avl_tree futex_tree = { .cmp = futex_tree_cmp };
> ```

We have a convention that global variables starts with `g_`, so this should be `g_futex_tree`.
___
*[LibOS/shim/src/sys/shim_futex.c, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIuqw--fxgykZD2VI:-MKeIuqw--fxgykZD2VJ:b-zbna3) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L75)):*
> ```C
> 
> /* Returns whether `addr` is smaller or equal to the one pointed by the node */
> static bool cmp_addr_to_futex(void* addr, struct avl_tree_node* node) {
> ```

This definition should not be between the two variables (futex tree and lock). The variables are related and should be defined next to each other.

But I think that if you use `avl_tree_find`, this function will not be necessary at all.
___
*[LibOS/shim/src/sys/shim_futex.c, line 321 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeJTMH6OtFAlQnHF5O:-MKeJTMIB9CxzBik7RRK:bhp5xqk) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L321)):*
> ```C
> }
> 
> static struct shim_futex* _lookup_futex(uintptr_t addr)
> ```

We don't care about the lower bound, but the exact element. You can use `avl_tree_find` to do that, and also keep it all in the `find_futex` function.


<!-- Sent from Reviewable.io -->

2020-10-28 10:10 UTC, dimakuv reviewed
This looks like a very nice change, thanks @aneessahib ! Please fix the comments left by Pawel.

Also, could you update the description of this PR to give some insight into the speedups you get with this PR?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921#-:-MKifnSTCNuD_S1LF8hk:b38ecy8)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2020-11-03 00:28 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUb2S8Dn1L-vEzTSJ:-MLAUb2T3mAh00YoNuDq:b-fcpetn) (no related file):*
@aneessahib: In the future, please use fixup commits when fixing review comments. See https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUzz41nJdyzgwOFfL:-MLAUzz689_3iQbC1NwC:b-r412t1) (no related file):*
> Also, could you update the description of this PR to give some insight into the speedups you get with this PR?

Moving this to a blocking comment, seems Anees missed this.

---


<!-- Sent from Reviewable.io -->

2020-11-03 06:42 UTC, yamahata requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[LibOS/shim/src/sys/shim_futex.c, line 54 at r2](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLBocvcDHiwe3q23Ehr:-MLBocvcDHiwe3q23Ehs:b-7mos3i) ([raw file](https://github.com/oscarlab/graphene/blob/7311a04c813e1ff5c0cb634b4c285e6bf0b301f3/LibOS/shim/src/sys/shim_futex.c#L54)):*
> ```C
>     LISTP_TYPE(futex_waiter) waiters;
>     LIST_TYPE(shim_futex) list;
>     union {
> ```

nitpick: now union isn’t needed.


<!-- Sent from Reviewable.io -->

2020-11-03 11:41 UTC, pwmarcz reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[LibOS/shim/src/sys/shim_futex.c, line 53 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIGjs7GaYFsqAe_Zv:-MLCt8a7E8QbWdj3lJlL:bbhx2zp) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L53)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This looks like copy-paste from `shim_vma`. We only need the `tree_node`. And probably no comment is necessary.

(Looks like you mentioned that above, but I'm adding a comment to keep track).
</blockquote></details>

Almost there, but as @yamahata said, this should be a regular field (the union was a `shim_vma`-specific hack).


<!-- Sent from Reviewable.io -->

2020-11-03 12:48 UTC, aneessahib commented
> Thanks for the PR!
> 
> Some stylistic remarks regarding the whole commit:
> 
> * Please make sure that your changes use spaces for indentation instead of tabs, as the rest of the code does. You can see the difference here in Reviewable. It should be a matter of configuring your editor.
> * The commit message needs to also follow the project's style, you can look at other commits in the project. In short:
>   
>   * The commit title is way too long - as you can see, Github and Reviewable do not display the whole title, and terminal tools will wrap it. The first line should only explain "what" you're doing, then (after empty line) you can add a paragraph of explanation "why". Remember to word-wrap the paragraph at 72 columns if necessary.
>   * There needs to be a prefix in the title describing the location of change. In this case, that would be `[LibOS]`.
>   * The commit title should be present tense imperative (example: "Replace futex list with AVL tree").
> 
> See also coding style guidelines: https://graphene.readthedocs.io/en/latest/devel/coding-style.html
> 
> I'm not sure if Graphene has written commit guidelines, but I think we mostly follow the style described here: https://chris.beams.io/posts/git-commit/
> 
> Sorry if it sounds like a lot for such a simple change. I assume you will be contributing more in the future, so I hope I can help you familiarize with the project's style.
> 
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921#-:-MKeMVNS89jmONVk-5xY:b-42id5x)_ status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)
> 
> _[LibOS/shim/src/sys/shim_futex.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeHzYS5BrwPt1pxgYg:-MKeHzYS5BrwPt1pxgYh:bxvk0ky) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L31)):_
> 
> > ```c
> > #include "shim_types.h"
> > #include "spinlock.h"
> > #include "avl_tree.h"
> > ```
> 
> There should be an empty line between the `#include` and the next declaration.
> Can you also make sure the file is included is in alphabetical order, i.e. just after `assert.h`?
> 
> _[LibOS/shim/src/sys/shim_futex.c, line 53 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIGjs7GaYFsqAe_Zv:-MKeIGjs7GaYFsqAe_Zw:b-zgnh7i) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L53)):_
> 
> > ```c
> >     LISTP_TYPE(futex_waiter) waiters;
> >     LIST_TYPE(shim_futex) list;
> >     union {
> > ```
> 
> This looks like copy-paste from `shim_vma`. We only need the `tree_node`. And probably no comment is necessary.
> 
> (Looks like you mentioned that above, but I'm adding a comment to keep track).
> 
> _[LibOS/shim/src/sys/shim_futex.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIbo81-4hvsdtALGR:-MKeIbo81-4hvsdtALGS:b-r7bbi0) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L66)):_
> 
> > ```c
> > };
> > static struct shim_futex* _lookup_futex(uintptr_t);
> > static bool futex_tree_cmp(struct avl_tree_node* node_a, struct avl_tree_node* node_b) {
> > ```
> 
> Please add an empty line before and after the function definition, so that it's easier to read.
> 
> _[LibOS/shim/src/sys/shim_futex.c, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeYJXG7HmKa772nv8O:-MKeYJXG7HmKa772nv8P:b-x7msxo) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L70)):_
> 
> > ```c
> >     struct shim_futex* b = container_of(node_b, struct shim_futex, tree_node);
> > 
> >     return a->uaddr <= b->uaddr;
> > ```
> 
> I think you should compare the addresses as numbers, i.e. cast them to `uintptr_t` first. Comparing (unrelated, e.g. not in the same array or struct) pointers directly is unspecified behaviour in C.
> 
> _[LibOS/shim/src/sys/shim_futex.c, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeJ2HCBWrZHUBc5abo:-MKeJ2HD62E4YDZ-Aiu7:b-cd5sbg) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L72)):_
> 
> > ```c
> >     return a->uaddr <= b->uaddr;
> > }
> > static struct avl_tree futex_tree = { .cmp = futex_tree_cmp };
> > ```
> 
> We have a convention that global variables starts with `g_`, so this should be `g_futex_tree`.
> 
> _[LibOS/shim/src/sys/shim_futex.c, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIuqw--fxgykZD2VI:-MKeIuqw--fxgykZD2VJ:b-zbna3) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L75)):_
> 
> > ```c
> > /* Returns whether `addr` is smaller or equal to the one pointed by the node */
> > static bool cmp_addr_to_futex(void* addr, struct avl_tree_node* node) {
> > ```
> 
> This definition should not be between the two variables (futex tree and lock). The variables are related and should be defined next to each other.
> 
> But I think that if you use `avl_tree_find`, this function will not be necessary at all.
> 
> _[LibOS/shim/src/sys/shim_futex.c, line 321 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeJTMH6OtFAlQnHF5O:-MKeJTMIB9CxzBik7RRK:bhp5xqk) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L321)):_
> 
> > ```c
> > }
> > 
> > static struct shim_futex* _lookup_futex(uintptr_t addr)
> > ```
> 
> We don't care about the lower bound, but the exact element. You can use `avl_tree_find` to do that, and also keep it all in the `find_futex` function.

@pwmarcz 
> I think you should compare the addresses as numbers, i.e. cast them to `uintptr_t` first. Comparing (unrelated, e.g. not in the same array or struct) pointers directly is unspecified behaviour in C.
regarding the above one - kept it this way since it's consistent with how the comparison is being done in shim_vma.c.

2020-11-03 12:50 UTC, aneessahib commented
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)_ status: 0 of 1 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @pwmarcz)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUb2S8Dn1L-vEzTSJ:-MLAUb2T3mAh00YoNuDq:b-fcpetn) (no related file):_
> @aneessahib: In the future, please use fixup commits when fixing review comments. See https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUzz41nJdyzgwOFfL:-MLAUzz689_3iQbC1NwC:b-r412t1) (no related file):_
> 
> > Also, could you update the description of this PR to give some insight into the speedups you get with this PR?
> 
> Moving this to a blocking comment, seems Anees missed this.

sure thanks

2020-11-03 12:52 UTC, aneessahib commented
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)_ status: 0 of 1 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @pwmarcz)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUb2S8Dn1L-vEzTSJ:-MLAUb2T3mAh00YoNuDq:b-fcpetn) (no related file):_
> @aneessahib: In the future, please use fixup commits when fixing review comments. See https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUzz41nJdyzgwOFfL:-MLAUzz689_3iQbC1NwC:b-r412t1) (no related file):_
> 
> > Also, could you update the description of this PR to give some insight into the speedups you get with this PR?
> 
> Moving this to a blocking comment, seems Anees missed this.

@mkow  - Had not missed it - was performing new runs to get fresh numbers. will update the description with results soon.

2020-11-03 12:54 UTC, aneessahib commented
LibOS/shim/src/sys/shim_futex.c, line 321 at r1 (raw file):

}

static struct shim_futex* _lookup_futex(uintptr_t addr)
We don't care about the lower bound, but the exact element. You can use avl_tree_find to do that, and also keep it all in the find_futex function.

@pwmarcz  - debugging some issues that i ran into when moved to avl_tree_find. will get back soon.

2020-11-03 13:42 UTC, aneessahib commented
> > > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)_ status: 0 of 1 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @pwmarcz)
> > 
> > 
> > _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUb2S8Dn1L-vEzTSJ:-MLAUb2T3mAh00YoNuDq:b-fcpetn) (no related file):_
> > @aneessahib: In the future, please use fixup commits when fixing review comments. See https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.
> > _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUzz41nJdyzgwOFfL:-MLAUzz689_3iQbC1NwC:b-r412t1) (no related file):_
> > > Also, could you update the description of this PR to give some insight into the speedups you get with this PR?
> > 
> > 
> > Moving this to a blocking comment, seems Anees missed this.
> 
> @mkow - Had not missed it - was performing new runs to get fresh numbers. will update the description with results soon.

@dimakuv  - pls check if the description has everything you are looking for.

2020-11-03 14:50 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/sys/shim_futex.c, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeYJXG7HmKa772nv8O:-MLDTKQT7nUoNms5Sp4X:b-osyaxa) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L70)):*
Moving the discussion to the right thread (by the way, if you don't access this PR using the Reviewable app, you probably should - it's much nicer to keep track of the separate comment threads, see which ones are still open, and so on).

>regarding the above one - kept it this way since it's consistent with how the comparison is being done in shim_vma.c.

If you mean the `vma_tree_cmp` function, yes, it compares `a->end <= b->end` without casting, but that's because these are already  `uintptr_t`.

Here, the situation is different because we have pointers, and comparing them directly is UB (see e.g. [this blog post](https://stefansf.de/post/pointers-are-more-abstract-than-you-might-expect/), specifically "Relational operators" box which cites the C11 standard). That's why I think they should be compared as integers, i.e. `(uintptr_t)a->uaddr <= (uintptr_t)b->uaddr`.
___
*[LibOS/shim/src/sys/shim_futex.c, line 321 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeJTMH6OtFAlQnHF5O:-MLDVMLdDz8Iij63Rf95:b-p0j6uc) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L321)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

> > ```c
> > }
> > 
> > static struct shim_futex* _lookup_futex(uintptr_t addr)
> > ``` 

>  We don't care about the lower bound, but the exact element. You can use `avl_tree_find` to do that, and also keep it all in the `find_futex` function. 

@pwmarcz  

> I think you should compare the addresses as numbers, i.e. cast them to `uintptr_t` first. Comparing (unrelated, e.g. not in the same array or struct) pointers directly is unspecified behaviour in C. 

regarding the above one - kept it this way since it's consistent with how the comparison is being done in shim_vma.c. 
</blockquote></details>

I replied above.

By the way, there is still some weird formatting in `find_futex` and `lookup_futex`: extra space before `=`, indentation using tabs instead of spaces, trailing spaces. Also, in our coding style the opening brace for `if` is on the same line, i.e.`if (!node) {`. So after you refactor this, please make sure these issues are fixed.
___
*[LibOS/shim/src/sys/shim_futex.c, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLDYoLfDS18ZGOND2bj:-MLDYoLfDS18ZGOND2bk:b-4hau13) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L54)):*
> ```C
>     LISTP_TYPE(futex_waiter) waiters;
>     LIST_TYPE(shim_futex) list;
>     struct avl_tree_node tree_node; 
> ```

Formatting (trailing space).
___
*[LibOS/shim/src/sys/shim_futex.c, line 188 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLD__ax3x8UnbXzYe-J:-MLD__ax3x8UnbXzYe-K:b-gw8gbn) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L188)):*
> ```C
>     if (check_dequeue_futex(futex)) {
> 	avl_tree_delete(&g_futex_tree, &futex->tree_node);
> 	/* We still hold this futex reference (in the caller), so this won't call free. */
> ```

Please convert tabs to spaces (these two lines).


<!-- Sent from Reviewable.io -->

2020-11-03 14:50 UTC, pwmarcz reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-03 17:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLAUzz41nJdyzgwOFfL:-MLE7TEX5cEEX38NidhQ:bp96mfk) (no related file):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

@dimakuv  - pls check if the description has everything you are looking for. 
</blockquote></details>

I am happy with this description! (I moved it from the title to the PR body.)

---


<!-- Sent from Reviewable.io -->

2020-11-03 18:31 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[LibOS/shim/src/sys/shim_futex.c, line 314 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLEN5HS8ODr0P7qL-3l:-MLEN5HTDeokVkrHLNXV:b-d0bov9) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L314)):*
> ```C
> 		   get_futex(futex);
> 	           return futex;
> 	   }
> ```

tabs -> spaces (ditto for the whole PR)
___
*[LibOS/shim/src/sys/shim_futex.c, line 316 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLEMzAa8CIa6IF1t-Vo:-MLEMzAa8CIa6IF1t-Vp:b-5ohjyq) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L316)):*
> ```C
> 	   }
>     }  
>     return NULL; 
> ```

Trailing spaces (ditto for the whole PR)


<!-- Sent from Reviewable.io -->

2020-11-03 18:32 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLENE6X2X26j20kLx_0:-MLENE6X2X26j20kLx_1:bvmgfr1) (no related file):*
@aneessahib please read https://graphene.readthedocs.io/en/latest/devel/coding-style.html carefully and reformat all your changes to conform to the style guide

---
___
*[LibOS/shim/src/sys/shim_futex.c, line 309 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLENB3kDk8meh5kvK5B:-MLENB3kDk8meh5kvK5C:b-lezk03) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L309)):*
> ```C
>     futex  = _lookup_futex((uintptr_t)uaddr);
>     if (futex != NULL)
>     {
> ```

`{` should be on the previous line


<!-- Sent from Reviewable.io -->

2020-11-05 13:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[LibOS/shim/src/sys/shim_futex.c, line 321 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeJTMH6OtFAlQnHF5O:-MLNS8nzC2hJGRp2n12f:bks3ew5) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L321)):*
> We don't care about the lower bound, but the exact element. You can use avl_tree_find to do that, and also keep it all in the find_futex function.

In today's conversation with @aneessahib, we decided to keep `avl_tree_lower_bound_fn` for now. This is because `avl_tree_find` needs to be provided another node, not just any value (as the comparison function is used both ways), and we would need to construct a fake `shim_futex` with a few values filled. Using `avl_tree_lower_bound_fn` (and checking if the result is equal) seems simpler and less hacky overall.

Now that I think of it, I guess another way to clean this up would be to change the AVL tree library so that the comparison function returns int. That also seems more in line with C libraries (`qsort`, `strcmp` etc.) But I wouldn't bundle that change with this PR, since it also influences the other use of this library (`shim_vma`).


<!-- Sent from Reviewable.io -->

2020-11-06 12:42 UTC, pwmarcz reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2020-11-06 12:43 UTC, pwmarcz commented
Jenkins, test this please

2020-11-07 01:21 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[LibOS/shim/src/sys/shim_futex.c, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVE2ho7wxIKlxiBU1n:-MLVE2ho7wxIKlxiBU1o:b-5w2z9j) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L53)):*
> ```C
>     uint32_t* uaddr;
>     LISTP_TYPE(futex_waiter) waiters;
>     LIST_TYPE(shim_futex) list;
> ```

Please remove this field, it's not needed anymore.
___
*[LibOS/shim/src/sys/shim_futex.c, line 77 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVE8ZK2H4N_4zdJN09:-MLVE8ZK2H4N_4zdJN0A:bno3s4c) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L77)):*
> ```C
> static struct avl_tree g_futex_tree = { .cmp = futex_tree_cmp };
> 
> static spinlock_t g_futex_list_lock = INIT_SPINLOCK_UNLOCKED;
> ```

Please rename this lock to `g_futex_tree_lock`.
___
*[LibOS/shim/src/sys/shim_futex.c, line 301 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVGPvy2ayufAmU14v3:-MLVGPvy2ayufAmU14v4:b6sfg8g) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L301)):*
> ```C
>  * Increases refcount of futex by 1.
>  */
> ```

Please remove this empty line.
___
*[LibOS/shim/src/sys/shim_futex.c, line 305 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVHKnVCXgTl91xKjK2:-MLVHKnVCXgTl91xKjK3:b-h5k2m1) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L305)):*
> ```C
>     assert(spinlock_is_locked(&g_futex_list_lock));
>     struct shim_futex* futex = NULL;
>     struct avl_tree_node* node = avl_tree_lower_bound_fn(&g_futex_tree, (void*)uaddr, cmp_addr_to_futex);
> ```

You could create a 'fake' futex on stack here:
```c
struct shim_futex cmp_arg = {
    .uaddr = uaddr,
};
```
and then you could use `avl_tree_find`, so there would be no need for double check of `uaddr` (below) and you could remove `cmp_addr_to_futex`.
___
*[LibOS/shim/src/sys/shim_futex.c, line 310 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVH5tbEZiN-o_bwybo:-MLVH5tc1Tn-lwJqWNqk:b-4w7u15) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L310)):*
> ```C
>     }
>     futex = container_of(node, struct shim_futex, tree_node);
>     if (futex != NULL) {
> ```

This check is not needed (if `node` is non-NULL, then `futex` is too).
___
*[LibOS/shim/src/sys/shim_futex.c, line 311 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVH12g4MUd5J8T6uqt:-MLVH12g4MUd5J8T6uqu:b-yxzek5) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L311)):*
> ```C
>     futex = container_of(node, struct shim_futex, tree_node);
>     if (futex != NULL) {
>         if(futex->uaddr == uaddr){
> ```

Please add spaces after `if` and before `{`.


<!-- Sent from Reviewable.io -->

2020-11-09 14:48 UTC, mkow reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2020-11-10 13:51 UTC, aneessahib commented
working on the review comments, plus i have a few more changes coming in based on some corner case issues i ran into. will update this PR tomorrow.

2020-11-11 13:15 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 2 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLENE6X2X26j20kLx_0:-MLSYPRk0GYpDb8DOlf9:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@aneessahib please read https://graphene.readthedocs.io/en/latest/devel/coding-style.html carefully and reformat all your changes to conform to the style guide
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/sys/shim_futex.c, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeYJXG7HmKa772nv8O:-MLSUcJb56EQt-7Ode0-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L70)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Moving the discussion to the right thread (by the way, if you don't access this PR using the Reviewable app, you probably should - it's much nicer to keep track of the separate comment threads, see which ones are still open, and so on).

>regarding the above one - kept it this way since it's consistent with how the comparison is being done in shim_vma.c.

If you mean the `vma_tree_cmp` function, yes, it compares `a->end <= b->end` without casting, but that's because these are already  `uintptr_t`.

Here, the situation is different because we have pointers, and comparing them directly is UB (see e.g. [this blog post](https://stefansf.de/post/pointers-are-more-abstract-than-you-might-expect/), specifically "Relational operators" box which cites the C11 standard). That's why I think they should be compared as integers, i.e. `(uintptr_t)a->uaddr <= (uintptr_t)b->uaddr`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeIuqw--fxgykZD2VI:-MLSYVptELNtb5Iv36zr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L75)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This definition should not be between the two variables (futex tree and lock). The variables are related and should be defined next to each other.

But I think that if you use `avl_tree_find`, this function will not be necessary at all.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 321 at r1](https://reviewable.io/reviews/oscarlab/graphene/1921#-MKeJTMH6OtFAlQnHF5O:-MLSUZWG5kN3aFBgeZUG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/94d563e9ea6a910daf9445371de6733504e25a8a/LibOS/shim/src/sys/shim_futex.c#L321)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

> We don't care about the lower bound, but the exact element. You can use avl_tree_find to do that, and also keep it all in the find_futex function.

In today's conversation with @aneessahib, we decided to keep `avl_tree_lower_bound_fn` for now. This is because `avl_tree_find` needs to be provided another node, not just any value (as the comparison function is used both ways), and we would need to construct a fake `shim_futex` with a few values filled. Using `avl_tree_lower_bound_fn` (and checking if the result is equal) seems simpler and less hacky overall.

Now that I think of it, I guess another way to clean this up would be to change the AVL tree library so that the comparison function returns int. That also seems more in line with C libraries (`qsort`, `strcmp` etc.) But I wouldn't bundle that change with this PR, since it also influences the other use of this library (`shim_vma`).
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLDYoLfDS18ZGOND2bj:-MLSYTrj0EUoVWBbDcV2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L54)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Formatting (trailing space).
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 188 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLD__ax3x8UnbXzYe-J:-MLSYWOxDdX6Q98OxWGp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L188)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Please convert tabs to spaces (these two lines).
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 309 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLENB3kDk8meh5kvK5B:-MLSUXBmBZjEY_p99CWg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L309)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`{` should be on the previous line
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 314 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLEN5HS8ODr0P7qL-3l:-MLSUXw96XSgYnvwqU0t:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L314)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

tabs -> spaces (ditto for the whole PR)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 316 at r3](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLEMzAa8CIa6IF1t-Vo:-MLSYY0R4Z3GgUCCsASs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7acf86a0b08ffc5aae92055f91c46c3ced5aa14/LibOS/shim/src/sys/shim_futex.c#L316)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Trailing spaces (ditto for the whole PR)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 53 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVE2ho7wxIKlxiBU1n:-MLrRIJJA0bDpZEDvhei:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove this field, it's not needed anymore.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 77 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVE8ZK2H4N_4zdJN09:-MLrRLOL9tU657TIOYoj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please rename this lock to `g_futex_tree_lock`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 301 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVGPvy2ayufAmU14v3:-MLrRNX79RDa_N4Dt1DE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L301)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove this empty line.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 305 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVHKnVCXgTl91xKjK2:-MLWYYD3CqR8pOt9AFsz:bsulh80) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87 [...]

2020-11-11 13:29 UTC, aneessahib commented
@boryspoplawski @mkow @pwmarcz - couple changes that would need additional review this time.
1) please review the change in avl_tree.c . This was needed to completely disassociate the node from the tree, else everytime avl_tree_next would return an object, hence failing the check_dequeue. Once this was done- specjbb results improved by 50%.
2) Once the above was done, i hit futex reference going below 0 error. So it looked like put_futex was being called twice in the event check_dequeue passed. So a change was made to have the put_futex run depending on the check_dequeue result inside futex_wait routine. A similar change was done in futex_wake as well but this is just for symmetry, though the futex ref error was incurred in the futex_wait routine. This change needs a closer review. However - i have tested multiple specjbb as well as redis workload runs. Specjbb overall showed an improvement, while redis pretty much performed the same.

2020-11-12 10:33 UTC, pwmarcz reviewed
>please review the change in avl_tree.c . This was needed to completely disassociate the node from the tree, else everytime avl_tree_next would return an object, hence failing the check_dequeue. Once this was done- specjbb results improved by 50%.

See the discussion under `check_dequeue`, I think the check is still not right.

>Once the above was done, i hit futex reference going below 0 error. So it looked like put_futex was being called twice in the event check_dequeue passed. So it looked like put_futex was being called twice in the event check_dequeue passed. So a change was made to have the put_futex run depending on the check_dequeue result inside futex_wait routine. A similar change was done in futex_wake as well but this is just for symmetry, though the futex ref error was incurred in the futex_wait routine. This change needs a closer review. 

That change doesn't look right, see the comments. I don't know why exactly the futex reference is going below 0, but I think it's related to `check_dequeue` still being wrong.

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921#-:-MLvxymb4t23YCQLSQPa:b-rz5db1)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_futex.c, line 305 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVHKnVCXgTl91xKjK2:-MLvqutg6xSnAIsi875a:bolwzkx) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L305)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

@boryspoplawski  the current implementation of avl_tree_find requires a cmp_* routine in any case. what do you suggest the logic here to be?
</blockquote></details>

I suggested `avl_tree_find` because creating a fake futex on stack looked ugly. But I don't have a strong opinion, and if @boryspoplawski  is OK with that, I agree it would make the rest of the code simpler.

It would use the standard compare function (`futex_tree_cmp`), no need for the other one.
___
*[LibOS/shim/src/sys/shim_futex.c, line 311 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVH12g4MUd5J8T6uqt:-MLvstGL4BaDSPn5MFyc:bw3ouxc) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L311)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you missed this one.
___
*[LibOS/shim/src/sys/shim_futex.c, line 176 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvj-l42EK_3n7t1sMG:-MLvj-l42EK_3n7t1sMH:b-d4yqpo) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L176)):*
> ```C
>     assert(spinlock_is_locked(&futex->lock));
> 
>     return LISTP_EMPTY(&futex->waiters) && avl_tree_next(&futex->tree_node);
> ```

This doesn't look right... If this is the only futex in the tree, then `avl_tree_next(&futex->tree_node)` will be null, even though the futex is actually in the tree. See `avl_tree_insert()`: if this is the first node, we just add it and keep `left`, `right` and `parent` null.

From what I can see, there is no way of checking if a node is *in* a tree without also examining `tree->root` (which would require holding a lock to the tree).

I can see some solutions:

1. Refactor this code so that we take `g_futex_tree_lock` and then check if the node is in tree (by doing something like `futex->tree_node->parent || futex->tree_node == g_futex_tree->root`. Probably we could get away with having a weaker check like `check_waiters()` (which will check only `futex->waiters`) for all cases when we call it *before* holding the tree lock, then calling `check_dequeue_futex()` only after we hold the lock.

   This sounds pretty ugly, though, I don't think it's the way to go.

2. Make sure it's possible to tell if an `avl_tree_node` is in tree. We have this feature for lists (a node not on a list has  pointers set to `NULL`, a node on a list has pointers set to self), it makes sense to have similar feature for AVL trees.

   A simple, but wasteful, solution would be to add a `bool in_tree` field to `avl_tree_node` and make sure to set/clear it. Alternatively, we could have a convention that `node->parent` is not `NULL` for a root, but points to self (i.e. `node->parent == node`), but that sounds pretty easy to get wrong somewhere. @boryspoplawski what do you think?

3. Solve this here by adding `bool in_tree` field to the futex structure. That sounds like the simplest solution, but of probably we will run into this problem again.

This PR is getting bigger so I would recommend going with 3 for now, but I'm interested in others' opinion on 2.
___
*[LibOS/shim/src/sys/shim_futex.c, line 273 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvsgkXBrZ1ryPKnY9s:-MLvsgkXBrZ1ryPKnY9t:bnn6wqh) ([raw file](https://github.com/oscarlab/graphene/blob/ea49007aa0c7742f93c80058efedb821a243b2c7/LibOS/shim/src/sys/shim_futex.c#L273)):*
> ```C
>     futex->uaddr = uaddr;
>     INIT_LISTP(&futex->waiters);
>     INIT_LIST_HEAD(futex, list);
> ```

I would call `avl_tree_init_node()` here. We add the futex to tree immediately, so it might not be necessary, but it's good practice to initialize all the fields, and the previous implementation did that.
___
*[LibOS/shim/src/sys/shim_futex.c, line 394 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvxYcn16xU_3VkK9X6:-MLvxYco5IlcNP7vffBK:b50otrg) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L394)):*
> ```C
>     }
>     else {
>         put_futex(futex);
> ```

I don't think that's right. We always increase the refcount for this variable (either by calling `find_futex` or `get_futex`), so we always need to call `put_futex` here.

The `put_futex` call inside the `maybe_dequeue_futex` tracks the reference from `g_futex_list_tree` (and will be called only if we do remove the futex from tree, which is not guaranteed here, hence `maybe` in the name).
___
*[LibOS/shim/src/sys/shim_futex.c, line 474 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvxnH42Y3viAxmya-i:-MLvxnH42Y3viAxmya-j:bnluqzw) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L474)):*
> ```C
>     }
>     else {
>        put_futex(futex);
> ```

Same as above, this `put_futex` was in the right place.
___
*[Pal/lib/avl_tree.c, line 490 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvt_G-DGBzXVzOA-p3:-MLvt_G-DGBzXVzOA-p4:bmi5zab) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/Pal/lib/avl_tree.c#L490)):*
> ```C
>         tree->root = new_root;
>     }
>     avl_tree_init_node(node);
> ```

This change makes sense, but as discussed above, I don't think clearing fields here is enough to make sure that the node has been removed from a tree. Let's see what we come up for `check_dequeue_futex`.


<!-- Sent from Reviewable.io -->

2020-11-13 13:43 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 305 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVHKnVCXgTl91xKjK2:-MM0nd3qE9X2Vd36BJCn:b50a60v) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L305)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I suggested `avl_tree_find` because creating a fake futex on stack looked ugly. But I don't have a strong opinion, and if @boryspoplawski  is OK with that, I agree it would make the rest of the code simpler.

It would use the standard compare function (`futex_tree_cmp`), no need for the other one.
</blockquote></details>

`futex_tree_cmp` is enough in this case, you can just do:
```c
struct shim_futex cmp_arg = {
    .uaddr = uaddr,
};

node = avl_tree_find(&g_futex_tree, &cmp_arg);
```
and then you can remove `cmp_addr_to_futex`
___
*[LibOS/shim/src/sys/shim_futex.c, line 176 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvj-l42EK_3n7t1sMG:-MM0j8EO-7KsP_c-vG2E:b-oy2bw3) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L176)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This doesn't look right... If this is the only futex in the tree, then `avl_tree_next(&futex->tree_node)` will be null, even though the futex is actually in the tree. See `avl_tree_insert()`: if this is the first node, we just add it and keep `left`, `right` and `parent` null.

From what I can see, there is no way of checking if a node is *in* a tree without also examining `tree->root` (which would require holding a lock to the tree).

I can see some solutions:

1. Refactor this code so that we take `g_futex_tree_lock` and then check if the node is in tree (by doing something like `futex->tree_node->parent || futex->tree_node == g_futex_tree->root`. Probably we could get away with having a weaker check like `check_waiters()` (which will check only `futex->waiters`) for all cases when we call it *before* holding the tree lock, then calling `check_dequeue_futex()` only after we hold the lock.

   This sounds pretty ugly, though, I don't think it's the way to go.

2. Make sure it's possible to tell if an `avl_tree_node` is in tree. We have this feature for lists (a node not on a list has  pointers set to `NULL`, a node on a list has pointers set to self), it makes sense to have similar feature for AVL trees.

   A simple, but wasteful, solution would be to add a `bool in_tree` field to `avl_tree_node` and make sure to set/clear it. Alternatively, we could have a convention that `node->parent` is not `NULL` for a root, but points to self (i.e. `node->parent == node`), but that sounds pretty easy to get wrong somewhere. @boryspoplawski what do you think?

3. Solve this here by adding `bool in_tree` field to the futex structure. That sounds like the simplest solution, but of probably we will run into this problem again.

This PR is getting bigger so I would recommend going with 3 for now, but I'm interested in others' opinion on 2.
</blockquote></details>

Paweł is right, this does not work.
I would go for 3 here. While reworking trees to support 2 should be quite easy, I specifically did not add this option when writing this implementation (maybe my reasoning is wrong and I should have) because either:
- you can tell whether a object is on tree just from the code, no need to track this dynamically - this is preferred option and usually possible,
- need to track it dynamically - in some cases, like futexes, object can be taken out of tree asynchronously - in such case I would say we should add a field to futex structure trackng this, just like Paweł suggested.
___
*[LibOS/shim/src/sys/shim_futex.c, line 273 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvsgkXBrZ1ryPKnY9s:-MM0m4yeBVvfFKk0AUrY:b-tyq1oj) ([raw file](https://github.com/oscarlab/graphene/blob/ea49007aa0c7742f93c80058efedb821a243b2c7/LibOS/shim/src/sys/shim_futex.c#L273)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I would call `avl_tree_init_node()` here. We add the futex to tree immediately, so it might not be necessary, but it's good practice to initialize all the fields, and the previous implementation did that.
</blockquote></details>

The trick is that `avl_tree_init_node` is meant to be used internally and if a node is in initialized state, it does NOT follow that it is not on some tree.
___
*[LibOS/shim/src/sys/shim_futex.c, line 394 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvxYcn16xU_3VkK9X6:-MM0oWNeBm88Tg6DgRRe:bxuvf91) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L394)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't think that's right. We always increase the refcount for this variable (either by calling `find_futex` or `get_futex`), so we always need to call `put_futex` here.

The `put_futex` call inside the `maybe_dequeue_futex` tracks the reference from `g_futex_list_tree` (and will be called only if we do remove the futex from tree, which is not guaranteed here, hence `maybe` in the name).
</blockquote></details>

Indeed, I don't see any problems with old version, this changes looks incorrect.
___
*[Pal/lib/avl_tree.c, line 490 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvt_G-DGBzXVzOA-p3:-MM0p3AZEEPgFcW02oTO:b5wmgzd) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/Pal/lib/avl_tree.c#L490)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This change makes sense, but as discussed above, I don't think clearing fields here is enough to make sure that the node has been removed from a tree. Let's see what we come up for `check_dequeue_futex`.
</blockquote></details>

This was not done here intentionally. Caller cannot assume anything about internal pointers anyway event after this call the node could be on some tree. Also it is impossible to check whether a node is not on any tree (we could only add a check if node is not on some specific tree).


<!-- Sent from Reviewable.io -->

2020-11-13 15:28 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 176 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvj-l42EK_3n7t1sMG:-MM167Sv2UzRKT82FudH:b15fhcj) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L176)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Paweł is right, this does not work.
I would go for 3 here. While reworking trees to support 2 should be quite easy, I specifically did not add this option when writing this implementation (maybe my reasoning is wrong and I should have) because either:
- you can tell whether a object is on tree just from the code, no need to track this dynamically - this is preferred option and usually possible,
- need to track it dynamically - in some cases, like futexes, object can be taken out of tree asynchronously - in such case I would say we should add a field to futex structure trackng this, just like Paweł suggested.
</blockquote></details>

Okay, then let's go with 3.

One thing that worries me about this "if a node is not in tree, you cannot rely on the field values" rule is that it might be harder to detect errors, for example trying to delete a node from tree twice, or trying to add a node that was already added. If we can ensure that the node state always means something, and a node outside of tree has an easily distinguishable state, it's easier to catch such bugs with a few asserts in `avl_tree_*` functions.

That's more on the principle of things though, I'm not sure how much it would help in practice. And it doesn't help if you have more than one tree.
___
*[LibOS/shim/src/sys/shim_futex.c, line 273 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvsgkXBrZ1ryPKnY9s:-MM16J8s0oejYY7BrkQX:beoyx6i) ([raw file](https://github.com/oscarlab/graphene/blob/ea49007aa0c7742f93c80058efedb821a243b2c7/LibOS/shim/src/sys/shim_futex.c#L273)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The trick is that `avl_tree_init_node` is meant to be used internally and if a node is in initialized state, it does NOT follow that it is not on some tree.
</blockquote></details>

OK, then I'm resolving this.
___
*[Pal/lib/avl_tree.c, line 490 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvt_G-DGBzXVzOA-p3:-MM18oMT7njVO4fLtk2i:bfbcl4v) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/Pal/lib/avl_tree.c#L490)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This was not done here intentionally. Caller cannot assume anything about internal pointers anyway event after this call the node could be on some tree. Also it is impossible to check whether a node is not on any tree (we could only add a check if node is not on some specific tree).
</blockquote></details>

Okay, if the "all pointers NULL" case is ambiguous anyway (the node could be still on the list) then I agree it's better not to call `avl_tree_init_node` here.


<!-- Sent from Reviewable.io -->

2020-11-13 15:40 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 176 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvj-l42EK_3n7t1sMG:-MM1FnqvEET10WvOVsQY:b-inwwts) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L176)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, then let's go with 3.

One thing that worries me about this "if a node is not in tree, you cannot rely on the field values" rule is that it might be harder to detect errors, for example trying to delete a node from tree twice, or trying to add a node that was already added. If we can ensure that the node state always means something, and a node outside of tree has an easily distinguishable state, it's easier to catch such bugs with a few asserts in `avl_tree_*` functions.

That's more on the principle of things though, I'm not sure how much it would help in practice. And it doesn't help if you have more than one tree.
</blockquote></details>

We could set all internal pointers to some poison value, like `MAP_FAILED` so that it **always** crashes if a free node is used.


<!-- Sent from Reviewable.io -->

2020-11-17 11:02 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 305 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVHKnVCXgTl91xKjK2:-MMKrdXfElUAUj8Ci7Z0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L305)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`futex_tree_cmp` is enough in this case, you can just do:
```c
struct shim_futex cmp_arg = {
    .uaddr = uaddr,
};

node = avl_tree_find(&g_futex_tree, &cmp_arg);
```
and then you can remove `cmp_addr_to_futex`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 176 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvj-l42EK_3n7t1sMG:-MMKriZXAdRzmD2GsJqN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L176)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We could set all internal pointers to some poison value, like `MAP_FAILED` so that it **always** crashes if a free node is used.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 394 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvxYcn16xU_3VkK9X6:-MMKrbUpArlJIaI1bXuD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L394)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Indeed, I don't see any problems with old version, this changes looks incorrect.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 474 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvxnH42Y3viAxmya-i:-MMKra7KBiMQhOdCOyPn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L474)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Same as above, this `put_futex` was in the right place.
</blockquote></details>

Done.
___
*[Pal/lib/avl_tree.c, line 490 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvt_G-DGBzXVzOA-p3:-MMKpQ9_E9vkglI31Zbi:b-m1vm80) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/Pal/lib/avl_tree.c#L490)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, if the "all pointers NULL" case is ambiguous anyway (the node could be still on the list) then I agree it's better not to call `avl_tree_init_node` here.
</blockquote></details>

okay - im removing this change for now. would it help with better memory handling if we were to correct this library for gracefully handling node deletion since avl trees is being used in shim_vma as well. 


<!-- Sent from Reviewable.io -->

2020-11-17 11:37 UTC, pwmarcz reviewed
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_futex.c, line 311 at r4](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLVH12g4MUd5J8T6uqt:-MMKwLLy1dSUtp8vlGMq:b-k2bwfd) ([raw file](https://github.com/oscarlab/graphene/blob/2a9e91c911eb6bcd6946a2be87519c19a8c93a1d/LibOS/shim/src/sys/shim_futex.c#L311)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think you missed this one.
</blockquote></details>

Now that you're using `avl_tree_find`, there is no need to check if `futex->uaddr == uaddr`.
___
*[LibOS/shim/src/sys/shim_futex.c, line 176 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvj-l42EK_3n7t1sMG:-MMKugxV-JEmqC66lScC:b-j8zx1h) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/LibOS/shim/src/sys/shim_futex.c#L176)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No parentheses necessary around `futex->in_tree`.
___
*[LibOS/shim/src/sys/shim_futex.c, line 58 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKw5bXBcH5iYGpQsfT:-MMKw5bXBcH5iYGpQsfU:b-3muqb) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L58)):*
> ```C
>     spinlock_t lock;
>     REFTYPE _ref_count;
>     bool in_tree;
> ```

This needs to be also initialized to false (in `create_new_futex()`).

Also, I would put this field right after `tree_node`, because it's related.
___
*[LibOS/shim/src/sys/shim_futex.c, line 164 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKxI5oA81CTfgcrmBL:-MMKxI5p7Z4qD-kn8XTh:bke7eg9) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L164)):*
> ```C
> 
> /*
>  * Checks whether `futex` has no waiters and is on `g_futex_list`.
> ```

The comment needs to be updated, as there is no `g_futex_list` anymore.

There are many places in this file where `g_futex_list` is still mentioned in comments - can you search & replace them all with `g_futex_tree`?
___
*[LibOS/shim/src/sys/shim_futex.c, line 180 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKukKa2uQPHhvUE5Um:-MMKukKb4comjrnlxNXP:b3k6cps) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L180)):*
> ```C
>     if (check_dequeue_futex(futex)) {
>         avl_tree_delete(&g_futex_tree, &futex->tree_node);
>         futex->in_tree = NULL;	
> ```

This should be `false`, since `in_tree` is bool. 

Also, please remove trailing whitespace.

I remember you're using vim? This might help find these mistakes (specifically, setting`let c_space_errors = 1` in your `.vimrc`): https://vim.fandom.com/wiki/Highlight_unwanted_spaces
___
*[LibOS/shim/src/sys/shim_futex.c, line 299 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKvdRzBd3wY9iowAGD:-MMKvdRzBd3wY9iowAGE:bda9i0v) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L299)):*
> ```C
>     struct shim_futex* futex = NULL;
>     struct shim_futex cmp_arg = {
> 	    .uaddr = uaddr
> ```

Please indent with spaces instead of tabs.

I'm not a vim user, but it looks like these could be the `.vimrc` options that would help you do this automatically: https://vi.stackexchange.com/a/4175
___
*[LibOS/shim/src/sys/shim_futex.c, line 301 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKwty28ciJByfrkuMp:-MMKwty28ciJByfrkuMq:b-cey8o0) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L301)):*
> ```C
> 	    .uaddr = uaddr
>     };
>     struct avl_tree_node* node = avl_tree_find(&g_futex_tree, &cmp_arg.tree_node);//avl_tree_lower_bound_fn(&g_futex_tree, (void*)uaddr, cmp_addr_to_futex);
> ```

There is still some code commented out here, please remove.


<!-- Sent from Reviewable.io -->

2020-11-17 14:03 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 58 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKw5bXBcH5iYGpQsfT:-MMLVDzJCd8l0rBVr725:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L58)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This needs to be also initialized to false (in `create_new_futex()`).

Also, I would put this field right after `tree_node`, because it's related.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 164 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKxI5oA81CTfgcrmBL:-MMLVBeD89JOMTAgKPsP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L164)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The comment needs to be updated, as there is no `g_futex_list` anymore.

There are many places in this file where `g_futex_list` is still mentioned in comments - can you search & replace them all with `g_futex_tree`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 180 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKukKa2uQPHhvUE5Um:-MMLVU-Y2zsYBgXO3iQa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L180)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This should be `false`, since `in_tree` is bool. 

Also, please remove trailing whitespace.

I remember you're using vim? This might help find these mistakes (specifically, setting`let c_space_errors = 1` in your `.vimrc`): https://vim.fandom.com/wiki/Highlight_unwanted_spaces
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 299 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKvdRzBd3wY9iowAGD:-MMLVvZM7161sGMLxQKs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L299)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Please indent with spaces instead of tabs.

I'm not a vim user, but it looks like these could be the `.vimrc` options that would help you do this automatically: https://vi.stackexchange.com/a/4175
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 301 at r6](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMKwty28ciJByfrkuMp:-MMLVeifBAGkMD6JndCx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/473f49b15a14c56f4913c88f0d1794a2e1d8b04e/LibOS/shim/src/sys/shim_futex.c#L301)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

There is still some code commented out here, please remove.
</blockquote></details>

Done.
___
*[Pal/lib/avl_tree.c, line 490 at r5](https://reviewable.io/reviews/oscarlab/graphene/1921#-MLvt_G-DGBzXVzOA-p3:-MMLW-4w6OdOdNMu-x1J:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b3b901c841f84bd25676a58b301b5202e6727cde/Pal/lib/avl_tree.c#L490)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

okay - im removing this change for now. would it help with better memory handling if we were to correct this library for gracefully handling node deletion since avl trees is being used in shim_vma as well. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 15:45 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 20 at r8](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMLpsJrDOu294lbuK6H:-MMLsNQhC2mEmZdSIOGu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/059f781a240338e9518f3ab18978582af71aabad/LibOS/shim/src/sys/shim_futex.c#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please include `<stdbool.h>` (this file didn't use `bool` before)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 15:45 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 49 at r8](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMLr9xTDJ1HwhdSD8fQ:-MMLr9xTDJ1HwhdSD8fR:b-tx2ktf) ([raw file](https://github.com/oscarlab/graphene/blob/059f781a240338e9518f3ab18978582af71aabad/LibOS/shim/src/sys/shim_futex.c#L49)):*
> ```C
> 
> DEFINE_LIST(shim_futex);
> DEFINE_LISTP(shim_futex);
> ```

Please remove these 2 defines, they are not needed anymore.
___
*[LibOS/shim/src/sys/shim_futex.c, line 187 at r8](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMLrLsn7Iblbbtg1dJx:-MMLrLsn7Iblbbtg1dJy:bba29fa) ([raw file](https://github.com/oscarlab/graphene/blob/059f781a240338e9518f3ab18978582af71aabad/LibOS/shim/src/sys/shim_futex.c#L187)):*
> ```C
> 
> /*
>  * If `futex` has no waiters and is on `g_futex_tree`, takes it off that list.
> ```

`off that list` -> `off that tree`


<!-- Sent from Reviewable.io -->

2020-11-17 15:47 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 20 at r8](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMLpsJrDOu294lbuK6H:-MMLsn8r7mMgJxx2lntC:b-cf2c8t) ([raw file](https://github.com/oscarlab/graphene/blob/059f781a240338e9518f3ab18978582af71aabad/LibOS/shim/src/sys/shim_futex.c#L20)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please move it one line above (to keep the headers sorted)


<!-- Sent from Reviewable.io -->

2020-11-17 15:49 UTC, pwmarcz commented
Jenkins, retest this please

2020-11-17 15:51 UTC, pwmarcz reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2020-11-17 15:55 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_futex.c, line 49 at r8](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMLr9xTDJ1HwhdSD8fQ:-MMLuXl91i5OkUNXIy8c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/059f781a240338e9518f3ab18978582af71aabad/LibOS/shim/src/sys/shim_futex.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove these 2 defines, they are not needed anymore.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_futex.c, line 187 at r8](https://reviewable.io/reviews/oscarlab/graphene/1921#-MMLrLsn7Iblbbtg1dJx:-MMLuZSZB9lmewLZrpDm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/059f781a240338e9518f3ab18978582af71aabad/LibOS/shim/src/sys/shim_futex.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`off that list` -> `off that tree`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 16:08 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-17 16:31 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-17 19:03 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-17 19:05 UTC, mkow commented
Jenkins, retest this please

2020-11-17 20:31 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-17 20:31 UTC, mkow commented
Jenkins, retest this please

2020-11-17 20:49 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-17 21:34 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-17 21:55 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1921)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-17 21:55 UTC, merged