[Pal/Linux-SGX] Better error messages if can't talk to AESM
oscarlab/graphene pull request #1925
Opened 2020-10-28 10:41 UTC by dimakuv

## Description of the changes 

Previously, if Graphene-SGX couldn't talk to AESM for whatever reason, it simply printed:
```
load_enclave() failed with error -2
```

This is not helpful. This PR prints a better message like this:
```
Cannot connect to aesm_service (tried sgx_aesm_socket_base and /var/run/aesmd/aesm.socket UNIX sockets).
Please check its status (`service aesmd status` on Ubuntu)!
load_enclave() failed with error -2
```

## How to test this PR? 

You can try manually by temporarily stopping the AESM service:
```
sudo service aesmd stop
LibOS/shim/test/regression$ SGX=1 ~/graphene/Runtime/pal_loader attestation
... fails! ...

sudo service aesmd start
LibOS/shim/test/regression$ SGX=1 ~/graphene/Runtime/pal_loader attestation
... works! ...
```

2020-10-28 10:59 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1925)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_platform.c, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene/1925#-MKioeEh-W5LN_eZ9YEO:-MKioeEh-W5LN_eZ9YEP:b7uyudc) ([raw file](https://github.com/oscarlab/graphene/blob/4b178be6db3be8266765956ce7f1f9ede60b74b7/Pal/src/host/Linux-SGX/sgx_platform.c#L80)):*
I think the exclamation mark should be before the parenthesis:
> ```
> Please check its status! (`service aesmd status` on Ubuntu)
> ```
___
*[Pal/src/host/Linux-SGX/sgx_platform.c, line 122 at r1](https://reviewable.io/reviews/oscarlab/graphene/1925#-MKip90b8XEBFnXKFWq4:-MKip90b8XEBFnXKFWq5:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/4b178be6db3be8266765956ce7f1f9ede60b74b7/Pal/src/host/Linux-SGX/sgx_platform.c#L122)):*
> ```C
>     if (ret < 0) {
>         SGX_DBG(DBG_E, "Cannot communicate with aesm_service (read/write returned error %d).\n"
>                 "Please check its status (`service aesmd status` on Ubuntu)!\n", ERRNO(ret));
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-10-28 11:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1925)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_platform.c, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene/1925#-MKioeEh-W5LN_eZ9YEO:-MKisAVl1zGBQq944blU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4b178be6db3be8266765956ce7f1f9ede60b74b7/Pal/src/host/Linux-SGX/sgx_platform.c#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the exclamation mark should be before the parenthesis:
> ```
> Please check its status! (`service aesmd status` on Ubuntu)
> ```
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_platform.c, line 122 at r1](https://reviewable.io/reviews/oscarlab/graphene/1925#-MKip90b8XEBFnXKFWq4:-MKisB9fEEt5CYlHcvmz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4b178be6db3be8266765956ce7f1f9ede60b74b7/Pal/src/host/Linux-SGX/sgx_platform.c#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-28 11:05 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1925)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-28 11:37 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`fork11` LTP test timed out, unrelated but interesting)

2020-10-28 11:38 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (previously landed on a dying Jenkins worker)

2020-10-28 13:22 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (previously landed on a dying Jenkins worker)

2020-10-28 13:22 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (previously landed on a dying Jenkins worker)

2020-10-28 14:46 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1925)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-10-28 15:45 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1925)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-10-28 18:13 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1925)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-29 08:06 UTC, dimakuv commented
Jenkins, retest this please (previous run was successful, but GitHub didn't "see" Jenkins results for some reason)

2020-10-29 08:53 UTC, merged