[LibOS]: Fix *at() syscalls
oscarlab/graphene pull request #1933
Opened 2020-11-03 02:27 UTC by vijaydhanraj

## Description of the changes 
As per linux man-pages, dirfd can be ignored if an absolute path is provided when invoking *at() calls. But in graphene many of the *at() calls require a valid dirfd even when an absolute path is provided. If not, the call fails. This PR fixes the issue by ignoring dirfd if an absolute file path is provided.

Fixes #1877
    
## How to test this PR? 
no new tests are added as part of this PR. Tested using `make regression` and LTP tests.

2020-11-03 03:08 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLB3af_AjFb--ovA3S_:-MLB3af_AjFb--ovA3Sa:b-mrkrde) (no related file):*
Please don't sprinkle the same logic around.(== "/"). consolidate it in get_dirfd_entry().
Otherwise looks good to me.

---


<!-- Sent from Reviewable.io -->

2020-11-03 06:51 UTC, vijaydhanraj commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLB3af_AjFb--ovA3S_:-MLBrf_VA-kqX-WgmSVU:buyt4rm) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Please don't sprinkle the same logic around.(== "/"). consolidate it in get_dirfd_entry().
Otherwise looks good to me.
</blockquote></details>

sure, also I seem to have missed mknodat, readlinkat and renameat syscalls. Will also fix these.

---


<!-- Sent from Reviewable.io -->

2020-11-03 10:12 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLCa3cQBvc_ICLUM0OH:-MLCa3cQBvc_ICLUM0OI:b-wqa01r) (no related file):*
Nice PR!

---
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1046 at r1](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLC_5IB7s3_QLHFvKJ7:-MLC_5ICCLi9aE36TOak:bpj4212) ([raw file](https://github.com/oscarlab/graphene/blob/8a381fab5c087cf8388a4c9311c888a5562ad3de/LibOS/shim/test/ltp/ltp.cfg#L1046)):*
> ```INI
> 
> [mkdir09]
> skip = yes
> ```

So this LTP test used it?

Are there any other LTP tests that work now?


<!-- Sent from Reviewable.io -->

2020-11-03 18:03 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vijaydhanraj and @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-04 06:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 1046 at r1](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLC_5IB7s3_QLHFvKJ7:-MLGsC6c-I_1uwPVLZte:b-zd92b8) ([raw file](https://github.com/oscarlab/graphene/blob/8a381fab5c087cf8388a4c9311c888a5562ad3de/LibOS/shim/test/ltp/ltp.cfg#L1046)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So this LTP test used it?

Are there any other LTP tests that work now?
</blockquote></details>

yes, another one was rename14. All the other ones failed when I tried to enable them.


<!-- Sent from Reviewable.io -->

2020-11-04 09:48 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

___
*[LibOS/shim/include/shim_fs.h, line 347 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHdT-06LNAocaDkBlT:-MLHdT-06LNAocaDkBlU:baoknsu) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/include/shim_fs.h#L347)):*
> ```objc
> /*
>  * This function returns a dentry (in *dir) from a handle corresponding to dirfd. When absolute
>  * pathname is provided, dirfd is ignored and the function returns. If dirfd == AT_FDCWD returns
> ```

Please add that `dir` will be set to NULL in this case. Change like this: `...dirfd is ignored, *dir is set to NULL, and the function returns.`
___
*[LibOS/shim/src/fs/shim_namei.c, line 824 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHdE-46L7caLsO1gao:-MLHdE-50kI4y2y5i4bk:bobdktq) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/src/fs/shim_namei.c#L824)):*
> ```C
> int get_dirfd_dentry(const char* pathname, int dirfd, struct shim_dentry** dir) {
>     if (pathname && *pathname == '/')
>         return 0;
> ```

We must set `*dir = NULL;` before returning here. Otherwise we may end up with uninitialized-pointer bugs which will be extremely hard to debug later.


<!-- Sent from Reviewable.io -->

2020-11-04 09:48 UTC, dimakuv commented
Jenkins, test this please

2020-11-04 10:06 UTC, dimakuv commented
Jenkins, retest this please (`setrlimit01` and `sigsuspend01` LTP tests failed, this is suspicious and may be due to this PR)

2020-11-04 10:06 UTC, dimakuv commented
Oops, started a retest of all Jenkins pipelines, even though only "Jenkins" pipeline failed. Ok, let it run again.

2020-11-04 11:17 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHyG3N4y9y6eyb0VxW:-MLHyG3N4y9y6eyb0VxX:b-e0fl4c) (no related file):*
@vijaydhanraj Can you run `setrlimit01`, `sigsuspend01` and `mkdir09` LTP tests multiple times on your local machine and make sure that they don't break with this PR? Jenkins fails on them (it may be a fluke, but we need to make sure).

---


<!-- Sent from Reviewable.io -->

2020-11-04 12:23 UTC, mkow requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

___
*[LibOS/shim/src/fs/shim_namei.c, line 824 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLIC2mH3oAd4bhk8ZLM:-MLIC2mH3oAd4bhk8ZLN:b-7c2paw) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/src/fs/shim_namei.c#L824)):*
> ```
>     if (pathname && *pathname == '/')
>         return 0;
> ```

Hmm, I don't really like this new change. Now the code is slightly simpler, but this function has really weird semantics - pathname is passed, but it's only used to check if it's absolute and then not used for anything.
CC: @dimakuv


<!-- Sent from Reviewable.io -->

2020-11-04 13:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj and @yamahata)

___
*[LibOS/shim/src/fs/shim_namei.c, line 824 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLIC2mH3oAd4bhk8ZLM:-MLIPL3z1VHfRPCl1z7K:b-dbcq02) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/src/fs/shim_namei.c#L824)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>     if (pathname && *pathname == '/')
>         return 0;
> ```

Hmm, I don't really like this new change. Now the code is slightly simpler, but this function has really weird semantics - pathname is passed, but it's only used to check if it's absolute and then not used for anything.
CC: @dimakuv
</blockquote></details>

Well, that's true. Maybe we should revert to the first revision of this PR? @yamahata What do you think, maybe some code duplication is justified in this PR?


<!-- Sent from Reviewable.io -->

2020-11-04 16:36 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/shim_namei.c, line 824 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLIC2mH3oAd4bhk8ZLM:-MLJ6BM06-LK4okboFK1:be4koyd) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/src/fs/shim_namei.c#L824)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, that's true. Maybe we should revert to the first revision of this PR? @yamahata What do you think, maybe some code duplication is justified in this PR?
</blockquote></details>

ok, let’s revert this part.


<!-- Sent from Reviewable.io -->

2020-11-04 17:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHyG3N4y9y6eyb0VxW:-MLJCFD_ClGrDgVLZ-T3:b-nmpcda) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj Can you run `setrlimit01`, `sigsuspend01` and `mkdir09` LTP tests multiple times on your local machine and make sure that they don't break with this PR? Jenkins fails on them (it may be a fluke, but we need to make sure).
</blockquote></details>

@dimakuv I did try couple of times and sometimes observe failure with `mkdir09` as shown below,
```
2020-11-04 08:56:42,582 LTP.mkdir09: cannot extract stdio on python < 3.7
2020-11-04 08:56:42,583 LTP.mkdir09: -> ERROR (Timed out after 30.0 s.)
```
But if I do a `make clean` or even simply `make` and run again, it works. 

Regarding `setrlimit01` and `sigsuspend01`, I don't see an error. 
`setrlimit01` has 4 sub-tests of which 13,4 `must-pass` and these do pass but 2 fails and it is marked as skipped. So I think this is expected.
`sigsuspend01` has just one test and this does `pass`

@dimakuv @mkow @yamahata can you please let me know how to run an individual test? Maybe I can run this couple more times and check.

I did try something like `/runltp_xml.py --list-executables ./install/testcases/bin/mkdir09` but throws some error.

---
___
*[LibOS/shim/src/fs/shim_namei.c, line 824 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLIC2mH3oAd4bhk8ZLM:-MLJCBJDCMG4mTEfnolf:b65fk00) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/src/fs/shim_namei.c#L824)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

ok, let’s revert this part.
</blockquote></details>

ok, I will revert the change back.


<!-- Sent from Reviewable.io -->

2020-11-04 18:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHyG3N4y9y6eyb0VxW:-MLJPJki4kI5rBqLQ_kR:b-wltqxi) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv I did try couple of times and sometimes observe failure with `mkdir09` as shown below,
```
2020-11-04 08:56:42,582 LTP.mkdir09: cannot extract stdio on python < 3.7
2020-11-04 08:56:42,583 LTP.mkdir09: -> ERROR (Timed out after 30.0 s.)
```
But if I do a `make clean` or even simply `make` and run again, it works. 

Regarding `setrlimit01` and `sigsuspend01`, I don't see an error. 
`setrlimit01` has 4 sub-tests of which 13,4 `must-pass` and these do pass but 2 fails and it is marked as skipped. So I think this is expected.
`sigsuspend01` has just one test and this does `pass`

@dimakuv @mkow @yamahata can you please let me know how to run an individual test? Maybe I can run this couple more times and check.

I did try something like `/runltp_xml.py --list-executables ./install/testcases/bin/mkdir09` but throws some error.
</blockquote></details>

Go to `LibOS/shim/test/ltp/install/testcases/bin` and then just do `./pal_loader setrlimit01`.

---


<!-- Sent from Reviewable.io -->

2020-11-04 19:28 UTC, vijaydhanraj commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHyG3N4y9y6eyb0VxW:-MLJTcb-6ccBpAX8mTgc:b-dp1ssl) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Go to `LibOS/shim/test/ltp/install/testcases/bin` and then just do `./pal_loader setrlimit01`.
</blockquote></details>

thanks, @mkow, and @dimakuv able to run tests individually. Ran these tests in a loop about 30-40 times and observe the same results as I mentioned above. 
`setrlimit01` sub-test 1,3, 4 pass, and 2 fails
`sigsuspend01` always passes
`mkdir09` is a little flaky. Sometimes passes sometimes hangs leading to a timeout. So I will revert this test to skip.

Can we do a make clean and restart the Jenkins test?

---


<!-- Sent from Reviewable.io -->

2020-11-04 22:51 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_fs.h, line 347 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHdT-06LNAocaDkBlT:-MLKSD2V-T0ODieXn7NY:b96xhn0) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/include/shim_fs.h#L347)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add that `dir` will be set to NULL in this case. Change like this: `...dirfd is ignored, *dir is set to NULL, and the function returns.`
</blockquote></details>

not applicable, we have reverted the changes.
___
*[LibOS/shim/src/fs/shim_namei.c, line 824 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLIC2mH3oAd4bhk8ZLM:-MLKS3zH4Aq8pC25tMAO:bezb3iy) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/src/fs/shim_namei.c#L824)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

ok, I will revert the change back.
</blockquote></details>

Reverted the last fixup and also fixed mknodat, readlinkat and renameat syscalls.
___
*[LibOS/shim/src/fs/shim_namei.c, line 824 at r2](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHdE-46L7caLsO1gao:-MLKSK-T8TzTy4giF6Xr:b96xhn0) ([raw file](https://github.com/oscarlab/graphene/blob/6f737fa0d97aa0fa30b1d7af21bb78095a6aab6e/LibOS/shim/src/fs/shim_namei.c#L824)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We must set `*dir = NULL;` before returning here. Otherwise we may end up with uninitialized-pointer bugs which will be extremely hard to debug later.
</blockquote></details>

not applicable, we have reverted the changes.


<!-- Sent from Reviewable.io -->

2020-11-04 23:33 UTC, mkow commented
Jenkins, retest this please

2020-11-04 23:33 UTC, mkow approved these changes
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1933#-MLHyG3N4y9y6eyb0VxW:-MLKaosc4-Nyrc7OnqcJ:b-896fix) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

thanks, @mkow, and @dimakuv able to run tests individually. Ran these tests in a loop about 30-40 times and observe the same results as I mentioned above. 
`setrlimit01` sub-test 1,3, 4 pass, and 2 fails
`sigsuspend01` always passes
`mkdir09` is a little flaky. Sometimes passes sometimes hangs leading to a timeout. So I will revert this test to skip.

Can we do a make clean and restart the Jenkins test?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-11-05 03:59 UTC, yamahata submitted a review, later dismissed
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-05 08:21 UTC, dimakuv submitted a review, later dismissed
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-05 08:21 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`sigsuspend01` LTP test failed, known issue)

2020-11-05 08:21 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`fork11` LTP test failed, known issue)

2020-11-05 17:26 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-05 17:27 UTC, mkow commented
Jenkins, retest this please

2020-11-05 17:33 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-05 18:04 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1933)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-05 21:10 UTC, merged