Miscelaneous inline asm fixes
oscarlab/graphene pull request #1938
Opened 2020-11-04 04:27 UTC by boryspoplawski

## Description of the changes 

Mostly adds missing "memory" clobber which caused some nasty bugs - gcc
optimized those inline asms and assumed values returned by them never
change.

Don't ask me how long it took me to debug this ...

2020-11-04 11:06 UTC, dimakuv requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHne5k3JDzop_mmNy9:-MLHne5l9ayWD9FSZ-o_:b-t7uzur) (no related file):*
Jenkins SGX (non-debug) pipelines failed with:
```
sgx_main.c: In function 'force_linux_to_grow_stack':
sgx_main.c:902:44: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
     for (uint64_t i = sizeof(dummy) - 1; i >= 0; i -= PRESET_PAGESIZE) {
                                            ^
sgx_main.c:901:10: error: variable 'tmp' set but not used [-Werror=unused-but-set-variable]
     char tmp;
          ^
sgx_main.c:904:13: error: 'dummy[i]' is used uninitialized in this function [-Werror=uninitialized]
         tmp = *(volatile char*)&dummy[i];
             ^
```

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHvp2w15d8T0j4KcHb:-MLHvp2xAZkji12v2Ktz:bkv90fl) (no related file):*
@yamahata Could you review this PR? You wrote some of this inline asm.

---
___
*[LibOS/shim/include/arch/x86_64/shim_internal-arch.h, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHofcU9qHTU7z6197p:-MLHofcU9qHTU7z6197q:bbfwkbk) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/LibOS/shim/include/arch/x86_64/shim_internal-arch.h#L15)):*
> ```objc
>             "movq %0, %%rsp\n"                                  \
>             "xorq %%rbp, %%rbp\n"                               \
>             "jmpq *%%rcx\n"                                     \
> ```

Was there a bug here? The old version seems legit...
___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHrfCF1DyIZOSBJKY6:-MLHrfCG9fBB_S7bYVxG:b2b2lo3) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L142)):*
> ```objc
>                 : "i" (offsetof(PAL_TCB, libos_tcb) +                   \
>                        offsetof(shim_tcb_t, member))                    \
>                 : "memory");                                            \
> ```

Why did you remove the switch statement? I understand that the GCC assembler may be smart enough to deduce the correct mov instruction from type of `ret`, but this looks like a dangerous assumption.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 902 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHuwVw843rwRrY8XHx:-MLHuwVw843rwRrY8XHy:b6fod15) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux-SGX/sgx_main.c#L902)):*
> ```C
>     char dummy[THREAD_STACK_SIZE];
>     char tmp;
>     for (uint64_t i = sizeof(dummy) - 1; i >= 0; i -= PRESET_PAGESIZE) {
> ```

Why did you revert the direction? Is it just to have a better correspondence to the "grow the stack" description? I see no functional difference here.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 903 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHuYUAApHgDDI9Q3XZ:-MLHuYUAApHgDDI9Q3X_:b-nwi2wd) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux-SGX/sgx_main.c#L903)):*
> ```C
>     char tmp;
>     for (uint64_t i = sizeof(dummy) - 1; i >= 0; i -= PRESET_PAGESIZE) {
>         /* touch each page on the stack just to make it is not optimized away */
> ```

`make` -> `make sure`


<!-- Sent from Reviewable.io -->

2020-11-04 11:07 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHvx3C7fPzrEoSCtlS:-MLHvx3C7fPzrEoSCtlT:b-dvkgfa) (no related file):*
> Don't ask me how long it took me to debug this ...

I actually wanted to ask :) Do you know which of these inline asms led to your bug? And in which app and how it manifested?

---


<!-- Sent from Reviewable.io -->

2020-11-04 12:55 UTC, mkow requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHrfCF1DyIZOSBJKY6:-MLIFAYhC4bkPnekD4VD:bvylp9f) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove the switch statement? I understand that the GCC assembler may be smart enough to deduce the correct mov instruction from type of `ret`, but this looks like a dangerous assumption.
</blockquote></details>

I tested it and it seems to work will all the sizes. I think "r" always selects register with a proper size. But I don't see this behavior documented, GCC docs are terrible...
___
*[Pal/regression/Memory.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIH2tME0uGDYu9Q0nj:-MLIH2tME0uGDYu9Q0nk:b7ctzjl) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/regression/Memory.c#L1)):*
> ```C
> /* XXX: What on earth is this supposed to be, an attempt to fit most UBs in one file? */
> ```

+1, always had the same question when looking at this file :)
___
*[Pal/src/host/Linux/db_exception.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIHkyNETtzQcNkAJzh:-MLIHkyNETtzQcNkAJzi:b-pouvfp) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux/db_exception.c#L33)):*
> ```C
> #define DEFINE_RESTORE_RT2(syscall)          \
>     __asm__(                                 \
>         "    nop\n"                          \
> ```

Any idea why it started with a `nop`?
___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLIIipz0BDIBN_x-Vom:b-1jiggo) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> ```C
>         "syscall \n"            /* rdi arg is already prepared, call exit */
>         "2: \n"
>         "hlt \n"
> ```

isn't `hlt` privileged?
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIw34BGQfP2Mbt8Xx:-MLIIw34BGQfP2Mbt8Xy:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux-SGX/sgx_exception.c#L39)):*
> ```C
> #define DEFINE_RESTORE_RT2(syscall)          \
>     __asm__(                                 \
>         "    nop\n"                          \
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 233 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIJK-u219mK1N3Uy7w:-MLIJK-v8M9NWGm2uTGm:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux-SGX/sgx_thread.c#L233)):*
> ```C
>                      "syscall \n"           /* all args are prepared, call exit  */
>                      "2: \n"
>                      "hlt \n"
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-11-04 16:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: 20 of 22 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHne5k3JDzop_mmNy9:-MLIYQjWANEfNOrmta_m:b82i390) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenkins SGX (non-debug) pipelines failed with:
```
sgx_main.c: In function 'force_linux_to_grow_stack':
sgx_main.c:902:44: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
     for (uint64_t i = sizeof(dummy) - 1; i >= 0; i -= PRESET_PAGESIZE) {
                                            ^
sgx_main.c:901:10: error: variable 'tmp' set but not used [-Werror=unused-but-set-variable]
     char tmp;
          ^
sgx_main.c:904:13: error: 'dummy[i]' is used uninitialized in this function [-Werror=uninitialized]
         tmp = *(volatile char*)&dummy[i];
             ^
```
</blockquote></details>

Sorry, it was late. Rewritten completely.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHvx3C7fPzrEoSCtlS:-MLIjK5YEn4sxgXwHSZC:bwaxpu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Don't ask me how long it took me to debug this ...

I actually wanted to ask :) Do you know which of these inline asms led to your bug? And in which app and how it manifested?
</blockquote></details>

It was the lack of "memory" clobber in `shim_tcb-arch.h`. Spotted in LTP's abort01 (probably others too, but I debugged this one):
1) it uses `wait` to, well, wait for the child,
2) `wait` uses `thread_sleep` to sleep if the child did not yet exit,
3) `thread_sleep` is `static inline` function in some `.h` file, so it gets inlined inside `wait`,
4) `thread_sleep` uses `PAL_ERRNO` to obtain errno code in case something fails, `PAL_ERRNO` extracts errno from TCB (and does some translation, not important),
5) this extraction missed the "memory" clobber, so gcc on non-debug builds (i.e. the one with optimizations turned on, `-O2` I think) optimized this errno extraction and moved it to the begining of `wait` (because `thread_sleep` was inlined inside it) - after all this inline asm did only depend on some constant offset, so it could even be moved across compiler barries,
6) so if `thread_sleep` failed, it reported some random errno (obtained at the beginning of the function).

How it manifested?
Sometimes `wait` would fail with `ENOENT` - it happened when `SIGCHLD` was handled while doing `wait`, so it was supposed to report `EINTR`, but due to the bug it reported `ENOENT`.

---
___
*[LibOS/shim/include/arch/x86_64/shim_internal-arch.h, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHofcU9qHTU7z6197p:-MLIS43LET2saipVxYuj:b7cxa28) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/LibOS/shim/include/arch/x86_64/shim_internal-arch.h#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Was there a bug here? The old version seems legit...
</blockquote></details>

gcc could pick `rbp` as `%1` (I did not hit this bug, but it looks possible).
Also arbitrarily setting `rbp` to `rsp` makes no sense, better zero it out to aid debuggers.
___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHrfCF1DyIZOSBJKY6:-MLISOkU8k0ipvXyMwaI:b-sdavdp) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L142)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I tested it and it seems to work will all the sizes. I think "r" always selects register with a proper size. But I don't see this behavior documented, GCC docs are terrible...
</blockquote></details>

Yeah, that was my reasoning: since we always use a register ("r") then we can use `mov` without size suffix.
Should I revert the old version (switch)? Indeed gcc doesn't tell us anything about this case ...
___
*[Pal/src/host/Linux/db_exception.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIHkyNETtzQcNkAJzh:-MLISmSpEtuRjulp9RMk:bcyiw11) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux/db_exception.c#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Any idea why it started with a `nop`?
</blockquote></details>

No and hopefully there are no cursed hacks around it anywhere ...
___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLIStpl8ScwEQqlGMQy:b-sn5h7m) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

isn't `hlt` privileged?
</blockquote></details>

Yeah and it will crash the process and if somehow it does not, we have a safety loop around it. Generally speaking exit syscall should succeed, this is just a safety net.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIw34BGQfP2Mbt8Xx:-MLIZ0pt0zRQkqjExgxX:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux-SGX/sgx_exception.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 902 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHuwVw843rwRrY8XHx:-MLIYARx-sdDx9a_8_XG:b-wo62mz) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux-SGX/sgx_main.c#L902)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you revert the direction? Is it just to have a better correspondence to the "grow the stack" description? I see no functional difference here.
</blockquote></details>

This function made no sense (pre and post changes). Rewritten.
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 233 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIJK-u219mK1N3Uy7w:-MLIZ3OR2k72yjpGE9CV:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux-SGX/sgx_thread.c#L233)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2020-11-04 16:12 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: 20 of 22 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIufCJ9DG5sd3S0Nkf:-MLIufCK2EamRaIqWDRr:bjsai64) (no related file):*
can you please share the combination of compiler version and optimization options to hit the issue?

---
___
*[LibOS/shim/include/arch/x86_64/shim_internal-arch.h, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHofcU9qHTU7z6197p:-MLIvZH-6GEw3K96XJRm:bs1ob6m) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/LibOS/shim/include/arch/x86_64/shim_internal-arch.h#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

gcc could pick `rbp` as `%1` (I did not hit this bug, but it looks possible).
Also arbitrarily setting `rbp` to `rsp` makes no sense, better zero it out to aid debuggers.
</blockquote></details>

it’s correct to clear rbp to indicate the end of stack to gdb. my bad.
___
*[LibOS/shim/include/arch/x86_64/shim_tcb-arch.h, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHrfCF1DyIZOSBJKY6:-MLIweJr4eUbg9evnNT9:bqflain) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/LibOS/shim/include/arch/x86_64/shim_tcb-arch.h#L142)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I tested it and it seems to work will all the sizes. I think "r" always selects register with a proper size. But I don't see this behavior documented, GCC docs are terrible...
</blockquote></details>

I think gas selects actual op code. As long as llvm is happy with it, I’m fine with this.
___
*[Pal/src/db_rtld.c, line 960 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIyiE68bB_rkcaP1bV:-MLIyiE83irCpPtWNdUa:bvxivcu) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/db_rtld.c#L960)):*
> ```C
> 
> /* TODO: Why on earth do we call loaded libraries entry points?!?
>  * I won't bother fixing this asm, it needs to be purged. */
> ```

this was a hack for multiple liboses  to load, I guess.
it is needed to call constructor instead (which isn’t needed at the moment).
___
*[Pal/src/host/Linux/db_exception.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIHkyNETtzQcNkAJzh:-MLJ-ckE1MrdbOgNyp_Y:b-cbmtb7) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux/db_exception.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No and hopefully there are no cursed hacks around it anywhere ...
</blockquote></details>

https://code.woboq.org/userspace/glibc/sysdeps/unix/sysv/linux/x86_64/sigaction.c.html#74
for gdb. the code was copied from glibc.
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 240 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJ-zBnDXPsgnqEVAd2:-MLJ-zBnDXPsgnqEVAd3:b-5is2wg) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/src/host/Linux-SGX/sgx_thread.c#L240)):*
> ```C
>                      : "memory"
>     );
>     __builtin_unreachable();
> ```

nice clean up


<!-- Sent from Reviewable.io -->

2020-11-04 16:29 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: 20 of 22 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLHvp2w15d8T0j4KcHb:-MLJ4mvE6aLMpXWIhbTL:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@yamahata Could you review this PR? You wrote some of this inline asm.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIufCJ9DG5sd3S0Nkf:-MLJ30L45uj6-PSNFhvy:bqk7lxb) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

can you please share the combination of compiler version and optimization options to hit the issue?
</blockquote></details>

Ubuntu 16.04:
```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```
Options: just
`make -j8 WERROR=1 GLIBC_VERSION=2.27`
from Graphene, which I guess is just `-O2`?
Note that this is very subtle issue, so gcc might not always generate code hitting it.

---
___
*[Pal/src/db_rtld.c, line 960 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIyiE68bB_rkcaP1bV:-MLJ4IMzDhQqzeJw4hm8:b-xjgwxy) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/db_rtld.c#L960)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

this was a hack for multiple liboses  to load, I guess.
it is needed to call constructor instead (which isn’t needed at the moment).
</blockquote></details>

Yeah, if that's required we should call global constructors, not entry points ...
___
*[Pal/src/host/Linux/db_exception.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIHkyNETtzQcNkAJzh:-MLJ4SFj2mF7GwGoba_g:b-b1t6xy) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux/db_exception.c#L33)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

https://code.woboq.org/userspace/glibc/sysdeps/unix/sysv/linux/x86_64/sigaction.c.html#74
for gdb. the code was copied from glibc.
</blockquote></details>

Still no idea why we would need a `nop` there ...
Anyway, gdb should have no problem with it.


<!-- Sent from Reviewable.io -->

2020-11-04 17:09 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-04 17:26 UTC, mkow requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/include/arch/x86_64/pal_internal-arch.h, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJEWT567_OcKjQYhnF:-MLJEWT567_OcKjQYhnG:b-q8cqri) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/include/arch/x86_64/pal_internal-arch.h#L6)):*
> ```objc
>  */
> 
> #ifndef _PAL_INTERNAL_ARCH_H
> ```

This is a reserved name in C, please fix it up when doing the final rebase.
___
*[Pal/include/arch/x86_64/pal_internal-arch.h, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJG4WmBBxEzddtTHAm:-MLJG4WnEMKREKlcxzxT:bj5c5es) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/include/arch/x86_64/pal_internal-arch.h#L17)):*
> ```objc
>         "1:\n"                                      \
>         "sub %0, %%rsp\n"                           \
>         "orq $0, (%%rsp)\n"                         \
> ```

This gives me flashbacks from reading https://marcan.st/2017/12/debugging-an-evil-go-runtime-bug/. We have plans for supporting Go, so this may actually cause problems, I think. I'm not sure how to fix this though.
___
*[Pal/include/arch/x86_64/pal_internal-arch.h, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJFg5Z1YbKPTcdkf4U:-MLJFg5_-ma7B-1hqtLS:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/include/arch/x86_64/pal_internal-arch.h#L25)):*
> ```objc
>     )
> 
> #endif // _PAL_INTERNAL_ARCH_H
> ```

ditto
___
*[Pal/src/db_rtld.c, line 960 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIyiE68bB_rkcaP1bV:-MLJGXifEHryZZwXZipV:b-mivr5f) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/db_rtld.c#L960)):*
> this was a hack for multiple liboses to load, I guess.

but this doesn't work, it's noreturn (despite the fact someone called it in a loop...)
___
*[Pal/src/host/Linux/db_exception.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIHkyNETtzQcNkAJzh:-MLJH6YfE7gg_qGlmqZh:b-bcm145) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux/db_exception.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Still no idea why we would need a `nop` there ...
Anyway, gdb should have no problem with it.
</blockquote></details>

Yes, I totally don't get that comment. This isn't a call target, this `nop` is just a dangling byte.
___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLJHEu39SUc01Mokqa0:bq1wfgs) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah and it will crash the process and if somehow it does not, we have a safety loop around it. Generally speaking exit syscall should succeed, this is just a safety net.
</blockquote></details>

But this looks like you tried to implement an infinite loop which sleeps the CPU (like kernels do). If you want to crash the process here then just issue `int3` or something similar, to be explicit.


<!-- Sent from Reviewable.io -->

2020-11-04 21:56 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: 21 of 22 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/include/arch/x86_64/pal_internal-arch.h, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJEWT567_OcKjQYhnF:-MLKF_sr0wn26u5phYc2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/include/arch/x86_64/pal_internal-arch.h#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a reserved name in C, please fix it up when doing the final rebase.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal_internal-arch.h, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJG4WmBBxEzddtTHAm:-MLKENdjDKJ-suLdU8xv:bpp41ea) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/include/arch/x86_64/pal_internal-arch.h#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This gives me flashbacks from reading https://marcan.st/2017/12/debugging-an-evil-go-runtime-bug/. We have plans for supporting Go, so this may actually cause problems, I think. I'm not sure how to fix this though.
</blockquote></details>

This only happens on the main thread in untrusted code, so this has nothing to do with small go stacks.
___
*[Pal/include/arch/x86_64/pal_internal-arch.h, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJFg5Z1YbKPTcdkf4U:-MLKFbL6DaouMvVdCMMK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/include/arch/x86_64/pal_internal-arch.h#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/db_rtld.c, line 960 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIyiE68bB_rkcaP1bV:-MLKEXZsCvOdsiYsB2gJ:bd85ebn) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/db_rtld.c#L960)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> this was a hack for multiple liboses to load, I guess.

but this doesn't work, it's noreturn (despite the fact someone called it in a loop...)
</blockquote></details>

No, if it was only to load our known subset of libraries, which we created, so we could have made their entry point return, it might have worked. That doesn't change the fact that this needs to be removed :)
___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKEtPiB069mkwgjaWC:b-ewtxx2) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this looks like you tried to implement an infinite loop which sleeps the CPU (like kernels do). If you want to crash the process here then just issue `int3` or something similar, to be explicit.
</blockquote></details>

I would very much like such loop, but this is not possible in ring 3, this is the least we can do to show our intentions. `int3` looks like a debug break, doesn't show what we want to achieve here: just stop the cpu, if the exit syscall failed, there's nothing more we can do.


<!-- Sent from Reviewable.io -->

2020-11-04 23:22 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/include/arch/x86_64/pal_internal-arch.h, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLJG4WmBBxEzddtTHAm:-MLKXhqj9_5m95LvqKcO:b-ce6wp8) ([raw file](https://github.com/oscarlab/graphene/blob/8df2a96c9c204c75bb8d677fc4f45ffcd38d0c35/Pal/include/arch/x86_64/pal_internal-arch.h#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This only happens on the main thread in untrusted code, so this has nothing to do with small go stacks.
</blockquote></details>

Oh, right, then it should be fine.
___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKZ73-7GxGpefaqt18:bfflos5) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would very much like such loop, but this is not possible in ring 3, this is the least we can do to show our intentions. `int3` looks like a debug break, doesn't show what we want to achieve here: just stop the cpu, if the exit syscall failed, there's nothing more we can do.
</blockquote></details>

`int3` is nice because it actually stops the debugger, if present, and if not it crashes the process (same as `hlt`, but explicitly, and doesn't pretend that it's an inf busy loop).


<!-- Sent from Reviewable.io -->

2020-11-04 23:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKaniUEUR5tDmN-JR_:bo0rugi) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`int3` is nice because it actually stops the debugger, if present, and if not it crashes the process (same as `hlt`, but explicitly, and doesn't pretend that it's an inf busy loop).
</blockquote></details>

1) `hlt` does not make cpu busy (exactly the opposite),
2) the idea was to look like loop halting the cpu, because we would very much like to do that (but we cannot),
3) if use app handles `SIGTRAP` then `int3` will just run the handler - not what we want.


<!-- Sent from Reviewable.io -->

2020-11-04 23:43 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKcgJ9BidwUgBwA3dS:b-sc8v06) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> hlt does not make cpu busy (exactly the opposite),

In ring0 yes, but I'd still call this busy loop.

> the idea was to look like loop halting the cpu, because we would very much like to do that (but we cannot),

For me this totally looks like an infinitely spinning loop, but it isn't and the code is misleading (it's only such a loop in ring0).

> if use app handles SIGTRAP then int3 will just run the handler - not what we want.

Same for the exception generated by `hlt`? I don't get this argument.

My main problem with this code is that it's _very_ misleading.


<!-- Sent from Reviewable.io -->

2020-11-05 00:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKjTjC2v4B3UVV_P03:biocb3g) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> For me this totally looks like an infinitely spinning loop, but it isn't and the code is misleading (it's only such a loop in ring0).

It should be a inf loop halting the cpu, but we cannot do that, so we just crash. So this code exactly shows the intention, I wouldn't call that misleading.
> Same for the exception generated by hlt? I don't get this argument.

The difference is that handling `int3` will resume the code execution after it and `hlt` before (effectively redoing segfault). That would make a difference if we removed the loop (which I guess is part of your suggestion).
>My main problem with this code is that it's very misleading.

Changing it to `int3` will make it ever more misleading, it will look like someone tried to do some weird debugger trap.


<!-- Sent from Reviewable.io -->

2020-11-05 00:31 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKnW0x18IrpYbo3Hgw:b-3wmr7v) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> It should be a inf loop halting the cpu, but we cannot do that, so we just crash. So this code exactly shows the intention, I wouldn't call that misleading.

Uh, but it's not doing this and never will, at least when implemented using `hlt`. We show the intention to the reader and then actually do something else.

> The difference is that handling `int3` will resume the code execution after it and `hlt` before (effectively redoing segfault). That would make a difference if we removed the loop (which I guess is part of your suggestion).

With the loop as you noticed it doesn't make a difference. The loop makes this code loop like `hlt` actually worked like in ring0.

> Changing it to int3 will make it ever more misleading, it will look like someone tried to do some weird debugger trap.

Which is a good thing? Because it will actually be a debugger trap (both look like a debugger trap and will be a debugger trap).


<!-- Sent from Reviewable.io -->

2020-11-05 00:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKqOnH6rPSyO8ckaIe:bnqll7) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> Uh, but it's not doing this and never will, at least when implemented using hlt. We show the intention to the reader and then actually do something else.

We do exactly what the user sees.
> With the loop as you noticed it doesn't make a difference. The loop makes this code loop like hlt actually worked like in ring0.

The loop is there just as a sanity check, because it doesn't cost us anything to put.
> Which is a good thing? Because it will actually be a debugger trap (both look like a debugger trap and will be a debugger trap).

But we do not want a debugger trap!


<!-- Sent from Reviewable.io -->

2020-11-05 00:53 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKsbqTBqDPZLpf0C9Q:bfax5wr) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> We do exactly what the user sees.

No, the reader sees "wait until next interrupt" instruction, but we actually throw an exception here because the context doesn't allow for this instruction.

> The loop is there just as a sanity check, because it doesn't cost us anything to put.

And it makes `hlt` confusing and `int3` working equally well, but more straightforward.

> But we do not want a debugger trap!

Why not? Even if, then why not just generate an exception explicitly instead of doing some shenanigans?


<!-- Sent from Reviewable.io -->

2020-11-05 01:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKv7L47z_oUzXjO35E:b-gej66l) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> No, the reader sees "wait until next interrupt" instruction, but we actually throw an exception here because the context doesn't allow for this instruction.

Since the use is aware we are in ring3, they can expect an exception.
> And it makes hlt confusing and int3 working equally well, but more straightforward.

I guess that's the whole point here: to me `int3` is confusing here, more than `hlt`. We could go for `ud2` as a middle ground, I guess.
> Why not? Even if, then why not just generate an exception explicitly instead of doing some shenanigans?

Doing a debugger exception not in a context where we expect to be under a debugger sounds like shenanigans to me.


<!-- Sent from Reviewable.io -->

2020-11-05 01:15 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLKxGJ062ECJeSZEMVn:b1xwcuv) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
> Since the use is aware we are in ring3, they can expect an exception.

You can use the same argument to defend any misleading code and just say that the reader knows everything and will notice all the traps.

> We could go for ud2 as a middle ground, I guess.

I'm fine with `ud2`.

> Doing a debugger exception not in a context where we expect to be under a debugger sounds like shenanigans to me.

How does it differ from any other exception? It's not even handled differently, any exception will stop the debugger here if it's present and if it's not it will kill the process. My point is: if you want to throw an exception then throw it explicitly, not write something which on first reading looks like an infinite loop which just quietly spins.


<!-- Sent from Reviewable.io -->

2020-11-05 02:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: 20 of 22 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 262 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIIipz0BDIBN_x-Vol:-MLLB11y1DJJySSgUYw5:b-zbf9q5) ([raw file](https://github.com/oscarlab/graphene/blob/5c1e003c0ec77e94a30a05d12db777b3f2bfe88a/Pal/src/host/Linux/db_threading.c#L262)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Since the use is aware we are in ring3, they can expect an exception.

You can use the same argument to defend any misleading code and just say that the reader knows everything and will notice all the traps.

> We could go for ud2 as a middle ground, I guess.

I'm fine with `ud2`.

> Doing a debugger exception not in a context where we expect to be under a debugger sounds like shenanigans to me.

How does it differ from any other exception? It's not even handled differently, any exception will stop the debugger here if it's present and if it's not it will kill the process. My point is: if you want to throw an exception then throw it explicitly, not write something which on first reading looks like an infinite loop which just quietly spins.
</blockquote></details>

I've changed it to `ud2` and moved loop start to before syscall. Cleaned up the asm a bit too.


<!-- Sent from Reviewable.io -->

2020-11-05 03:47 UTC, yamahata approved these changes
> Reviewed 18 of 21 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux/db_exception.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1938#-MLIHkyNETtzQcNkAJzh:-MLLVWn2DZODVr4ErR0-:bpmv2ym) ([raw file](https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/Pal/src/host/Linux/db_exception.c#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yes, I totally don't get that comment. This isn't a call target, this `nop` is just a dangling byte.
</blockquote></details>

TBH I don't get the original comment. I'm guessing disassembler in gdb?


<!-- Sent from Reviewable.io -->

2020-11-05 03:52 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-05 08:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-05 08:32 UTC, dimakuv commented
Jenkins, retest Jenkins please (`select04` LTP test failed, unrelated)

2020-11-05 13:00 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-05 13:05 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1938)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-05 14:02 UTC, merged