[LibOS] Remove unused IPC port types
oscarlab/graphene pull request #1942
Opened 2020-11-04 14:19 UTC by dimakuv

## Description of the changes 

Previously, `IPC_PORT_SERVER` meant "listening port", and the actual communication ports had several types. Only two of these types were used for differentiation during IPC broadcast (direct-child and direct-parent types). All other types denoted who is the remote party this port connects to, but this info is superfluous. So this commit replaces all these types with a generic `IPC_PORT_CONNECTION`, and renames `IPC_PORT_SERVER` to a more familiar `IPC_PORT_LISTENING`.

## How to test this PR? 

Cosmetic change, all tests must pass.

2020-11-04 16:29 UTC, yamahata approved these changes
very nice to attack cleanup of ipc.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942#-:-MLJ4n-j9zaQYqcfcAV9:bkzyka6)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-11-04 16:35 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_ipc.h, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1942#-MLJ5MGp9hkOC6YBe5ss:-MLJ5MGq-kH0QiKSw_S-:b-4ardp9) ([raw file](https://github.com/oscarlab/graphene/blob/a665b1da8ea8325be69275d06cab1e0dc03645b8/LibOS/shim/include/shim_ipc.h#L33)):*
> ```objc
>     IPC_LISTENING,    /* listening port; processes connect to it to create connection ports */
>     IPC_CONNECTION,   /* processes communicate on ports of this type */
>     IPC_DIRECTCHILD,  /* direct child: used to broadcast CHILDEXIT message only to children */
> ```

While we are at it, what does it mean to broadcase CHILDEXIT to the children? Makes no sense to me ...


<!-- Sent from Reviewable.io -->

2020-11-04 17:41 UTC, mkow reviewed
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-05 08:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1942#-MLJ5MGp9hkOC6YBe5ss:-MLMPIRSCT3H8uWHoKRw:b-ccoigd) ([raw file](https://github.com/oscarlab/graphene/blob/a665b1da8ea8325be69275d06cab1e0dc03645b8/LibOS/shim/include/shim_ipc.h#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

While we are at it, what does it mean to broadcase CHILDEXIT to the children? Makes no sense to me ...
</blockquote></details>

I also don't know :) This is the comment we have at that place:
https://github.com/oscarlab/graphene/blob/b2f03e0d4778e40aa1299a08a7afc92a30c918d9/LibOS/shim/src/ipc/shim_ipc_child.c#L85-L87

But I changed the comment in this PR to a more vague one :)


<!-- Sent from Reviewable.io -->

2020-11-05 08:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1942#-MLJ5MGp9hkOC6YBe5ss:-MLMQNmJ4c9FCbhey7Xo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a665b1da8ea8325be69275d06cab1e0dc03645b8/LibOS/shim/include/shim_ipc.h#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also don't know :) This is the comment we have at that place:
https://github.com/oscarlab/graphene/blob/b2f03e0d4778e40aa1299a08a7afc92a30c918d9/LibOS/shim/src/ipc/shim_ipc_child.c#L85-L87

But I changed the comment in this PR to a more vague one :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 12:29 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-11-05 14:10 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-05 21:15 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-05 22:52 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1942)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-05 23:21 UTC, merged