Fix incorrect thread exit code
oscarlab/graphene pull request #1943
Opened 2020-11-04 16:32 UTC by pwmarcz

## Description of the changes 

This fixes #1937, but more importantly, makes sure that any thread calling `exit()` will cause the correct exit code to be reported.

I do that by making sure that all exiting `shim_thread`s  have the same `exit_code` and `term_signal` (before they had 0). See also the commit message for more details.

## How to test this PR? 

The `exit_group` test is a test for this scenario:

```sh
cd LibOS/shim/test/regression
make exit_group exit_group.manifest

# run the test:
../../../../Scripts/run-pytest -k test_401_exit_group -v

# trigger the binary manually:
./exit_group 3 100; echo $?
./pal_loader exit_group 3 100; echo $?
```

2020-11-04 16:42 UTC, yamahata submitted a review, later dismissed
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-11-04 16:46 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MLJ85Ol5b9pZHCFgQ8s:b-sqlv36) (no related file):*
Today I'll submit a PR reworking threads (just waiting for #1938) which will get rid of these per thread exit codes and unfortunately remove all code introduced in this PR.
Now I know why I hit that LTP `accept02` issue :)

We could merge this as temporary fix, but I'll revert all this changes anyway. What you guys think? cc @dimakuv @mkow @yamahata 

---


<!-- Sent from Reviewable.io -->

2020-11-04 16:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MLJAuaFCB2Wq2wXWDKB:b-yud1rg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Today I'll submit a PR reworking threads (just waiting for #1938) which will get rid of these per thread exit codes and unfortunately remove all code introduced in this PR.
Now I know why I hit that LTP `accept02` issue :)

We could merge this as temporary fix, but I'll revert all this changes anyway. What you guys think? cc @dimakuv @mkow @yamahata 
</blockquote></details>

No problem, the change is somewhat hacky anyway, but you can still use the test :)

---


<!-- Sent from Reviewable.io -->

2020-11-04 16:59 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MLJBSDo0ZoBLbhdoPnT:b-x6q5ls) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No problem, the change is somewhat hacky anyway, but you can still use the test :)
</blockquote></details>

Yeah, we will definitely keep the reworked test, the question is when do we merge it. I expect threads rework merge to be lengthy process, as the PR will be quite big.

---


<!-- Sent from Reviewable.io -->

2020-11-04 17:57 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MLJOw10BOniBsyFVX2T:bzhhbjz) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, we will definitely keep the reworked test, the question is when do we merge it. I expect threads rework merge to be lengthy process, as the PR will be quite big.
</blockquote></details>

@boryspoplawski Your call, I'm fine with both options. But if we decide to merge it, then I'd do it before submitting your changes, because they will conflict.

---


<!-- Sent from Reviewable.io -->

2020-11-04 18:10 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MLJRlT380nbOcg_kXON:bes4o3a) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski Your call, I'm fine with both options. But if we decide to merge it, then I'd do it before submitting your changes, because they will conflict.
</blockquote></details>

Given that it would be me, who needs to resolve the conflicts and that this is not a fatal issue, I would wait and merge just the test after threads PR :)

---


<!-- Sent from Reviewable.io -->

2020-11-05 08:49 UTC, dimakuv requested changes
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MLM_tW07hZisx3kpbov:b6nhuzs) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Given that it would be me, who needs to resolve the conflicts and that this is not a fatal issue, I would wait and merge just the test after threads PR :)
</blockquote></details>

What about we drop the second commit from this PR (bar that skip of the `accept02` LTP test)? And mark it as blocked until we merge Borys's PR (`This PR must be rebased on top of ...`).

---


<!-- Sent from Reviewable.io -->

2020-11-05 14:07 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MLNipV-41LuHGphrq2g:b-yf4532) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about we drop the second commit from this PR (bar that skip of the `accept02` LTP test)? And mark it as blocked until we merge Borys's PR (`This PR must be rebased on top of ...`).
</blockquote></details>

I guess we can live without this test (old version) in the meantime, so I'm ok with this

---


<!-- Sent from Reviewable.io -->

2020-11-19 20:02 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MMX53_g0z6HPIDBqmkz:bgyqlhi) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess we can live without this test (old version) in the meantime, so I'm ok with this
</blockquote></details>

Threads PR was merged, this can be updated (just the test will remain, I guess?)

---


<!-- Sent from Reviewable.io -->

2020-11-20 08:37 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MMZmcZCE9fR_FoJaLsb:b-hae5c8) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Threads PR was merged, this can be updated (just the test will remain, I guess?)
</blockquote></details>

Done. I rebased the code on newest master and left only the test.

---


<!-- Sent from Reviewable.io -->

2020-11-20 09:25 UTC, dimakuv requested changes
> Reviewed 3 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1943#-MLJ85OjAjMbb4as_iF5:-MMZxIJa6Nassumy3e_X:b4zid7h) (no related file):*
> In addition, propagate the exit code from a forked process. That use case is actually broken and will be fixed in next commit.

I believe this para in the commit message should be removed (in the final rebase).

---


<!-- Sent from Reviewable.io -->

2020-11-20 15:09 UTC, mkow requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/test/regression/exit_group.c, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene/1943#-MMaBHFADpaBtL-Yz9aC:-MMaBHFADpaBtL-Yz9aD:biy5cnj) ([raw file](https://github.com/oscarlab/graphene/blob/6eb656b11770d8ca26bf12a79f977f25c7c36f89/LibOS/shim/test/regression/exit_group.c#L53)):*
> ```C
> 
>     pid_t pid = fork();
>     if (fork < 0) {
> ```

Ouch. Are you testing here a function pointer for being negative? :P
Really weird that this didn't produce a warning...


<!-- Sent from Reviewable.io -->

2020-11-20 15:31 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/test/regression/exit_group.c, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene/1943#-MMaBHFADpaBtL-Yz9aC:-MMaGiSD80CpBB1Ne1LV:b-3gk5k0) ([raw file](https://github.com/oscarlab/graphene/blob/6eb656b11770d8ca26bf12a79f977f25c7c36f89/LibOS/shim/test/regression/exit_group.c#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ouch. Are you testing here a function pointer for being negative? :P
Really weird that this didn't produce a warning...
</blockquote></details>

Wow :) Yeah, crazy that this compiled without warnings. Fixed.


<!-- Sent from Reviewable.io -->

2020-11-20 15:33 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-20 15:38 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-20 16:08 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-20 16:27 UTC, yamahata approved these changes
> Reviewed 2 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-23 00:09 UTC, boryspoplawski approved these changes
> Reviewed 2 of 8 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1943)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-23 00:14 UTC, merged