[LibOS] Rework threads
oscarlab/graphene pull request #1949
Opened 2020-11-07 00:44 UTC by boryspoplawski

## Description of the changes 
Summary of changes can be found in commit message.
Let me know which part requires more comments, generally I tried to be descriptive with the code (function names etc.)

Fixes #378, fixes #446 (this one was probably already fixed), fixes #969, fixes  #1068, fixes #1480, fixes #1937
Might fix (needs testing) #1297 

Currently there is some issue with IPC, which leads to hang on `pipe_ocloexec` test from LibOS regression (under SGX only). I'm not yet sure if this issue was introduced in this PR or was just uncovered by it. (see: #1948)

2020-11-07 00:47 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 0 of 46 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLV9o9L6HMTagrl2pIO:-MLV9o9L6HMTagrl2pIP:b1hfyqd) (no related file):*
TODO: add a TODO/issue to change threads list to a tree (probably as a follow up to this PR).

---


<!-- Sent from Reviewable.io -->

2020-11-07 01:09 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 0 of 46 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLVEz1WDXZ1T4_CJghs:-MLVEz1XDTA87y2atxy_:bie7gqz) (no related file):*
TODO: check if any LTP test can be enabled (probably after debugging IPC issue).

---


<!-- Sent from Reviewable.io -->

2020-11-09 12:30 UTC, dimakuv requested changes
> Reviewed 36 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 36 of 46 files reviewed, 30 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_checkpoint.h, line 350 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgT7Na4IOMNs7_Kexl:-MLgT7NbBOrSerUY6R2Q:buh5qx2) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_checkpoint.h#L350)):*
> ```objc
>  * The remaining arguments are passed into the migration function.
>  *
>  * \return             0 on success, negative POSIX error code on failure.
> ```

This indentation is now meaningless. Either no indentation, or align with above params.
___
*[LibOS/shim/include/shim_checkpoint.h, line 354 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgTKCBCvhxK7qffoBk:-MLgTKCBCvhxK7qffoBl:b1pvngk) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_checkpoint.h#L354)):*
> ```objc
> int create_process_and_send_checkpoint(migrate_func_t migrate_func, struct shim_handle* exec,
>                                        struct shim_child_process* child_process,
>                                        struct shim_process* process_description,
> ```

Why do you have two objects describing the child process (`child_process` and `process_description`)? Also, the `child_process` argument is not listen in the comment.

UPDATE: Ok, `child_process` is used in case of clone/fork (`exec` is used in a contrast case of execve), and is added to the list of child processes of the current process. Please update the comment.
___
*[LibOS/shim/include/shim_ipc.h, line 173 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgUWVD-nmE84_W6A5S:-MLgUWVE-e0iZzMymA3K:b-z4ouap) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_ipc.h#L173)):*
> ```objc
> struct shim_ipc_cld_exit {
>     IDTYPE ppid, pid;
>     IDTYPE uid;
> ```

Is `uid` added for sanity/for future? Because currently I don't see any uses of it; it is always the same as the initial one (and seems to be zero?).
___
*[LibOS/shim/include/shim_process.h, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgWPsqBc85msIZtnFm:-MLgWPsrEp1c_PyZ6YGn:briugl7) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L23)):*
> ```objc
>     IDTYPE vmid;
> 
>     int death_notification_signal;
> ```

Why this name? Maybe `child_termination_signal` -- the term used in man pages?
___
*[LibOS/shim/include/shim_process.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgWgWnB6mY4v6dHJWx:-MLgWgWo0ezQFDUY1EdN:bqhtzor) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L27)):*
> ```objc
>     int exit_code;
>     int term_signal;
>     IDTYPE uid;
> ```

Nitpick: move `uid` close to `pid/vmid`.
___
*[LibOS/shim/include/shim_process.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgXDLqDjqDTyN0vg28:-MLgXDLqDjqDTyN0vg29:b3vjgrk) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L46)):*
> ```objc
>     mode_t umask;
> 
>     /* Handle to the executable. Protected by `fs_lock`. */
> ```

This comment looks useless. Maybe at least add `...executable file`?
___
*[LibOS/shim/include/shim_process.h, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgXttD9zWzkWG7YpqR:-MLgXttD9zWzkWG7YpqS:bcx745i) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L74)):*
> ```objc
> /*
>  * These 2 functions mark a child as exited, moving it from `children` list to `zombies` list
>  * and generate a child-death signal (if needed).
> ```

`child-death` -> `child-termination`
___
*[LibOS/shim/include/shim_thread.h, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgZqpeEobOy3Y_E5Ur:-MLgZqpeEobOy3Y_E5Us:b-rj9lgt) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L56)):*
> ```objc
> DEFINE_LISTP(shim_thread);
> struct shim_thread {
>     /* Field for inserting threads on global `thread_list`. */
> ```

Can we rename the global `thread_list` to `g_thread_list` (and its corresponding lock)?
___
*[LibOS/shim/include/shim_thread.h, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgZC4G3YN3pSNBVr-h:-MLgZC4H9QWvsldOxDPf:bmiues3) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L63)):*
> ```objc
> 
>     /* credentials */
>     IDTYPE uid, gid, euid, egid;
> ```

Aren't these supposed to be per-process rather than per-thread?
___
*[LibOS/shim/include/shim_thread.h, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLg_5UkELZlagSNebIl:-MLg_5UkELZlagSNebIm:b-ndgapv) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L82)):*
> ```objc
>      * `process_pending_signals_cnt`. */
>     uint64_t pending_signals;
>     unsigned char signal_handled;
> ```

Can you add comment describing three options: `NOT_HANDLED, HANDLED, RESTART`
___
*[LibOS/shim/include/shim_thread.h, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLg_W593BJsuJSIzl3f:-MLg_W593BJsuJSIzl3g:b-kdxffc) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L107)):*
> ```objc
>     struct shim_thread_queue* next;
>     struct shim_thread* thread;
>     bool in_use;
> ```

Could you put a comment why this is needed?
___
*[LibOS/shim/src/shim_context-x86_64.c, line 146 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgclESCCeJyytCIVC1:-MLgclESCCeJyytCIVC2:b-5hhaay) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/shim_context-x86_64.c#L146)):*
> ```C
>     *(unsigned long*)(regs.rsp - RED_ZONE_SIZE - 8) = regs.rip;
> 
>     context->regs = NULL;
> ```

Is this just for sanity? Looks superfluous. 
___
*[LibOS/shim/src/shim_init.c, line 623 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgdUqZ8_ySG17vr6YK:-MLgdUqZ8_ySG17vr6YL:by9x3bm) ([raw file](https://github.com/oscarlab/graphene/blob/3fa93cc86f3d7f01a81ef387eadd3c29bf4738a2/LibOS/shim/src/shim_init.c#L623)):*
> ```C
>         debug("exit status collides with Graphene-internal magic status; changed to 1\n");
>         exit_code = 1;
>     }
> ```

Don't we want to move this debug message to `shim_do_exitgroup` (or whatever is used now to exit at LibOS level)? Looks useful.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgdzoT23jplINYA5xK:-MLgdzoT23jplINYA5xL:b4lrj8u) ([raw file](https://github.com/oscarlab/graphene/blob/3fa93cc86f3d7f01a81ef387eadd3c29bf4738a2/LibOS/shim/src/bookkeep/shim_handle.c#L42)):*
> ```C
>     /* XXX: Try getting the root FS from current thread? */
>     assert(cur_thread);
>     assert(cur_thread->root);
> ```

This change collides with my https://github.com/oscarlab/graphene/pull/1951. Will need to be rebased (it's the subset of what I changed).
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 133 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgilUX3pj2et_IwHRj:-MLgilUYCjCl3nZzI8lN:b-r0y374) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff5 [...]

2020-11-09 14:42 UTC, dimakuv requested changes
> Reviewed 10 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 45 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLh7cf2E61RTmCLznEv:-MLh7cf2E61RTmCLznEw:bkqpzsm) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/ipc/shim_ipc_child.c#L32)):*
> ```C
>      */
>     if (mark_child_exited_by_vmid(vmid, /*uid=*/0, /*exit_code=*/0, SIGKILL)) {
>         debug("Child process (id: 0x%x) got disconnected\n", vmid);
> ```

Could you replace `vmid` -> `vmid & 0xFFFF`? We do this for readability of the debug output.`

Can you also change `id` to `vmid` in the debug message? Otherwise it is ambiguous: is it host-level pid (vmid) or Graphene-iternal pid (pid)?
___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLh7vca2bQyHLDHMWCN:-MLh7vcbDaunD-lA1YSu:bw6jgzg) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/ipc/shim_ipc_child.c#L84)):*
> ```C
>           msgin->ppid, msgin->pid, msgin->exitcode, msgin->term_signal);
> 
>     /* message cannot come from our own threads (from ourselves as process) */
> ```

`/* Message cannot come from our own process. */`
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 641 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLh8gmK1RCVManr6eSx:-MLh8gmK1RCVManr6eSy:b-fd0e4t) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/ipc/shim_ipc_helper.c#L641)):*
> ```C
> 
>     if (needs_wait) {
>         /* Wait untill the helper thread notices the stop event. */
> ```

Typo: `until`
___
*[LibOS/shim/src/sys/shim_clone.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhH4OH791vG_9YEems:-MLhH4OI8iHeT7Pbqppi:btgb5w2) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_clone.c#L37)):*
> ```C
>     PAL_HANDLE create_event;
>     PAL_HANDLE initialize_event;
>     struct shim_thread* parent;
> ```

`parent` seems to be useless now
___
*[LibOS/shim/src/sys/shim_clone.c, line 213 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhChhMAH0jipqHHL9V:-MLhChhMAH0jipqHHL9W:b-yr1hdl) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_clone.c#L213)):*
> ```C
> 
>     get_dentry(process_description.root);
>     get_dentry(process_description.cwd);
> ```

Shouldn't we check if `root` and `cwd` are not NULL, just like we do with `exec`?
___
*[LibOS/shim/src/sys/shim_clone.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhDO3u3qwysn1O4_11:-MLhDO3u3qwysn1O4_12:bnmbmn8) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_clone.c#L226)):*
> ```C
>     clear_lock(&process_description.children_lock);
> 
>     child_process->pid = process_description.pid;
> ```

Can we add `child_proces->vmid = 0` and add a comment that vmid is set to the host-pid after the process is actually created at the host level?
___
*[LibOS/shim/src/sys/shim_clone.c, line 242 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhEVsD-7IpdBn1rBwd:-MLhEVsD-7IpdBn1rBwe:b-3e5q6l) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_clone.c#L242)):*
> ```C
>     put_handle(process_description.exec);
>     put_dentry(process_description.cwd);
>     put_dentry(process_description.root);
> ```

Shouldn't we have `if ([exec | cwd | root]) put_*(...)`
___
*[LibOS/shim/src/sys/shim_clone.c, line 424 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhHDcyEy5Gau6FtFxW:-MLhHDcz9C27OfwwHnIE:b-aedo2t) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_clone.c#L424)):*
> ```C
>     get_thread(thread);
>     new_args.thread  = thread;
>     new_args.parent  = self;
> ```

Useless
___
*[LibOS/shim/src/sys/shim_exec.c, line 428 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhIhMg9hrd1v38u6Ua:-MLhIhMg9hrd1v38u6Ub:bgdpwz4) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_exec.c#L428)):*
> ```C
>     pause_ipc_helper();
> 
>     lock(&cur_thread->lock);
> ```

Do we need this thread lock/unlock if we know that we are the only thread left?
___
*[LibOS/shim/src/sys/shim_exit.c, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhJ37RCtcYeeT528x0:-MLhJ37RCtcYeeT528x1:b-ao8xm) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_exit.c#L6)):*
> ```C
>  *                    Borys Popławski <borysp@invisiblethingslab.com>
>  * Copyright (C) 2020 Intel Corporation
>  *                    Borys Popławski <borysp@invisiblethingslab.com>
> ```

Why are there two copyrights with your name?
___
*[LibOS/shim/src/sys/shim_exit.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhJxSO3nvs5ZJAOE7i:-MLhJxSO3nvs5ZJAOE7j:b-702p8a) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_exit.c#L73)):*
> ```C
>         lock(&cur_thread->lock);
>         assert(cur_thread->shim_tcb->tp == cur_thread);
>         cur_thread->shim_tcb->tp = NULL;
> ```

Why do we do this?
___
*[LibOS/shim/src/sys/shim_exit.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhKLhYDOZYaAeloPok:-MLhKLhYDOZYaAeloPol:b-hnwvc0) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_exit.c#L92)):*
> ```C
>     }
> 
>     /* Let parent know we exited. */
> ```

Can you prepend `This is the last thread of the process; let parent ...`
___
*[LibOS/shim/src/sys/shim_getpid.c, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhKlHM5ePA2jH1DvAh:-MLhKlHM5ePA2jH1DvAi:bmguedu) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_getpid.c#L18)):*
> ```C
> 
> pid_t shim_do_gettid(void) {
>     return get_cur_thread()->tid;
> ```

Why no lock?
___
*[LibOS/shim/src/sys/shim_getpid.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhKmzeBsexHJJcq2f9:-MLhKmzeBsexHJJcq2fA:bmguedu) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_getpid.c#L28)):*
> ```C
>     struct shim_thread* cur = get_cur_thread();
>     cur->clear_child_tid    = tidptr;
>     return cur->tid;
> ```

Why no lock?
___
*[LibOS/shim/src/sys/shim_getuid.c, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhLfftCMVLSuJsfRea:-MLhLfftCMVLSuJsfReb:b-wv2il2) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_getuid.c#L39)):*
> ```C
>     get_cur_thread()->egid = gid;
>     return 0;
> }
> ```

Lock of thread in all these funcs?
___
*[LibOS/shim/src/sys/shim_wait.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhRnWOBP9X5nPkdt4I:-MLhRnWOBP9X5nPkdt4J:b-blkft) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_wait.c#L60)):*
> ```C
> }
> 
> static void remove_qnode_from_wait_queue(struct shim_thread_queue* qnode) {
> ```

I am confused by the logic of this function. How is this possible that `seen` can be `false`? We are s [...]

2020-11-11 00:07 UTC, boryspoplawski reviewed
> Reviewed 43 of 46 files at r3, 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 33 of 46 files reviewed, 45 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_checkpoint.h, line 350 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgT7Na4IOMNs7_Kexl:-MLnlyDdB-MTuzr3XI5X:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_checkpoint.h#L350)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This indentation is now meaningless. Either no indentation, or align with above params.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_checkpoint.h, line 354 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgTKCBCvhxK7qffoBk:-MLnm-8p9fUjU89j6bte:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_checkpoint.h#L354)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have two objects describing the child process (`child_process` and `process_description`)? Also, the `child_process` argument is not listen in the comment.

UPDATE: Ok, `child_process` is used in case of clone/fork (`exec` is used in a contrast case of execve), and is added to the list of child processes of the current process. Please update the comment.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 173 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgUWVD-nmE84_W6A5S:-MLnn62j4XiB1hTexxfU:b-a7fa42) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_ipc.h#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is `uid` added for sanity/for future? Because currently I don't see any uses of it; it is always the same as the initial one (and seems to be zero?).
</blockquote></details>

This type of message is generated when a process exits to inform the parent. This field is filled (together with rest of the struct) when sending such a message in `ipc_cld_exit_send` and is set to the current `uid` of the last thread.
___
*[LibOS/shim/include/shim_process.h, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgWPsqBc85msIZtnFm:-MLnuFkq4HO5LrlzVc1p:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this name? Maybe `child_termination_signal` -- the term used in man pages?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_process.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgWgWnB6mY4v6dHJWx:-MLnnrNI2_C-c67OWXHo:b-c1kia5) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nitpick: move `uid` close to `pid/vmid`.
</blockquote></details>

This was intentional because this field is set together with `exit_code` and `term_signal` - it comes in a IPC message. Added a comment.
___
*[LibOS/shim/include/shim_process.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgXDLqDjqDTyN0vg28:-MLnumCND5wdEfdzJEIu:b-x7xf30) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment looks useless. Maybe at least add `...executable file`?
</blockquote></details>

Done. This was mainly to state that you need to take `fs_lock` to access this field.
___
*[LibOS/shim/include/shim_process.h, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgXttD9zWzkWG7YpqR:-MLnv3at7FCZ2OTX2BeC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_process.h#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`child-death` -> `child-termination`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgZqpeEobOy3Y_E5Ur:-MLnvn-g0CrXRbjdBfNi:bs7wumx) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename the global `thread_list` to `g_thread_list` (and its corresponding lock)?
</blockquote></details>

Done. 
___
*[LibOS/shim/include/shim_thread.h, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgZC4G3YN3pSNBVr-h:-MLnvpZaAyu456nztzJv:bjaa2qs) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Aren't these supposed to be per-process rather than per-thread?
</blockquote></details>

No, on Linux uids are per thread attribute.
Side note: threading libraries (like NPTL) will make sure all threads have the same credentials, since POSIX requires that, but on kernel level each thread have a separate set of them.
___
*[LibOS/shim/include/shim_thread.h, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLg_5UkELZlagSNebIl:-MLnyTdtAEu-W10Hsa6w:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add comment describing three options: `NOT_HANDLED, HANDLED, RESTART`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLg_W593BJsuJSIzl3f:-MLoa9YZ9ats_r2pL0_N:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you put a comment why this is needed?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 146 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgclESCCeJyytCIVC1:-MLo7hjX-o10_tMZSjY9:brzcr30) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/shim_context-x86_64.c#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this just for sanity? Looks superfluous. 
</blockquote></details>

This `context` is part of `tcb` (at least `clone` calls this functions in such a way). I have no idea what other parts of code use this field (seems like signals sometimes do?), but it's part of the old stack (in `clone` case), so we should not be using it after this function. Additionally the old version cleaned (set to `0`) most of the context.
___
*[LibOS/shim/src/shim_init.c, line 623 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgdUqZ8_ySG17vr6YK:-MLo9lK65xUGZtaZPIMe:b-tcjfyu) ([raw file](https://github.com/oscarlab/graphene/blob/3fa93cc86f3d7f01a81ef387eadd3c29bf4738a2/LibOS/shim/src/shim_init.c#L623)):*
<detai [...]

2020-11-11 08:44 UTC, dimakuv requested changes
> Reviewed 32 of 46 files at r3, 1 of 2 files at r4, 13 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_thread.h, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgZC4G3YN3pSNBVr-h:-MLqDfKz-gyrykE0p3Ze:b-3hy125) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/include/shim_thread.h#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, on Linux uids are per thread attribute.
Side note: threading libraries (like NPTL) will make sure all threads have the same credentials, since POSIX requires that, but on kernel level each thread have a separate set of them.
</blockquote></details>

OK, thanks for clarification.
___
*[LibOS/shim/include/shim_thread.h, line 84 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqE1vl4X-Izt4ERyFz:-MLqE1vl4X-Izt4ERyG-:bkmvjh9) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/include/shim_thread.h#L84)):*
> ```objc
> 
>     /*
>      * This field is used for checking whether we handled a signal during blocking parts in LibOS
> ```

`blocking parts` is ambiguous. Maybe add an example in parenthesis? Like `...blocking parts (e.g. blocking read on a network socket) ...`
___
*[LibOS/shim/include/shim_thread.h, line 118 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqENNe0yuNCdtYdk_j:-MLqENNe0yuNCdtYdk_k:b-m5i3mo) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/include/shim_thread.h#L118)):*
> ```objc
>     struct shim_thread* thread;
>     /* We use this field to mark that this object is still in use (is on some queue). This is needed
>      * to distinquish spurious wake-ups from real ones. */
> ```

`distinquish` -> `distinguish`
___
*[LibOS/shim/src/shim_init.c, line 623 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgdUqZ8_ySG17vr6YK:-MLqFU18DeZBIto78xhu:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/3fa93cc86f3d7f01a81ef387eadd3c29bf4738a2/LibOS/shim/src/shim_init.c#L623)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

User application exit code is truncated to `0-255` (in `shim_do_exitgroup`) so there is no way it collides with `PAL_WAIT_FOR_CHILDREN_EXIT` (which is much higher).
UPDATE: seems I've left this message in `libos_clean_and_exit` (in `LibOS/shim/src/sys/shim_exit.c`).
</blockquote></details>

OK.
___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLh7cf2E61RTmCLznEv:-MLqHlLx4bA7qgikqXB6:b-31o8wt) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/ipc/shim_ipc_child.c#L32)):*
> Is vmid really the host pid? Because then this truncation does not make much sense.

No, it's a bit more complicated than just a host pid:
```
LibOS/shim/src/shim_init.c:    g_process_ipc_info.vmid = (IDTYPE)PAL_CB(process_id);
src/host/Linux-SGX/db_main.c:    g_linux_state.process_id = (start_time & (~0xffff)) | g_pal_sec.pid;
```

I don't know the reason behind throwing the timestamp in the `vmid` value...

> Also wouldn't it be an issue if a malicious host (in case of SGX) would show same host-level pid to two processes, wouldn't ipc code get lost then?

Yes, I think it's a legit issue (the attacker currently also needs to adjust the `start_time` but that's doable). Though recall that all IPC is encrypted in SGX, and two processes with the same `vmid` will conflict on the TLS sequence numbers, so it looks only DoS attacks are possible with this.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 732 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqNKArE3lsDFnYqHKh:-MLqNKArE3lsDFnYqHKi:b-j6sek5) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/ipc/shim_ipc_helper.c#L732)):*
> ```C
>         if (clear_event(&install_new_event) < 0) {
>             goto out_err_unlock;
>         }
> ```

Not really related to your changes, but I think there is a data race in the IPC helper: `install_new_event` is used to unblock the IPC helper thread if it is in blocking poll (on new-port-added or old-port-deleted events).

When we do `clear_event()`, it clears all events, and it may happen after `unlock(ipc_helper_lock)` in the previous iteration of the while loop and before `lock(ipc_helper_lock)` in a new iteration of the while loop. So very rarely, new-port-added and old-port-deleted events may be lost.

The lost event of new-port-added seems fine -- this code re-adds the ports from the global `port_list` anyway, so the IPC helper will learn about the newly added port. However, the lost event of old-port-deleted seems bad -- the `del_ipc_port_fini()` callback may never be called on this deleted port (the IPC helper doesn't notice this event). I wonder if this can manifest in hangs of applications?

I can unblock this comment if this thinking is wrong or if this is out of scope of this PR.
___
*[LibOS/shim/src/sys/shim_getpid.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhKmzeBsexHJJcq2f9:-MLqRqBK2TRtu7z5SA-W:bkt8qgb) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_getpid.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

But we also update `cur->clear_child_tid` in a non-atomic way. Could it lead theoretically to "partial updates" when the same thread calls `set_tid_address()` in the main execution and in the signal handler?
___
*[LibOS/shim/src/sys/shim_wait.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhRnWOBP9X5nPkdt4I:-MLqTCJG-krZXEP0vRfR:b-woqy7b) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_wait.c#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why, one thread can remove another thread from this queue, in particular ipc helper thread does remove (and wake) threads on this queue.
We need `in_use` check since there is no other way of knowing if we are still on this queue and were woken up spuriously. 
</blockquote></details>

Ok, now I got it.


<!-- Sent from Reviewable.io -->

2020-11-11 09:48 UTC, yamahata requested changes
> Reviewed 32 of 46 files at r3, 1 of 2 files at r4, 13 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/shim_init.c, line 501 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5mf32NTjMUjY8aoZ:-MLq5mf32NTjMUjY8ao_:b-758weo) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/shim_init.c#L501)):*
> ```C
>     RUN_INIT(init_process);
>     RUN_INIT(init_thread);
>     RUN_INIT(init_mount);
> ```

init_process() should be after init_mount().
Please see the comment in init_process().
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 19 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq66y4D7Pn6ILFJYOb:-MLq66y4D7Pn6ILFJYOc:b-l7f6s6) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L19)):*
> ```
> struct shim_child_process*
> ```

const struct shim_child_process*. Maybe a matter of preference.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 59 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5_Vq0DQrlY5KXqXu:-MLq5_Vq0DQrlY5KXqXv:bxs0mp6) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L59)):*
> ```C
>     if (root_config && get_config(root_config, "fs.start_dir", dir_cfg, sizeof(dir_cfg)) > 0) {
>         dent = NULL;
>         ret = path_lookupat(NULL, dir_cfg, 0, &dent, NULL);
> ```

This expects that all mount points are initialized.
So init_process() should be called after init_mount().
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 201 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqAw6v3sgy3e4lHkjW:-MLqAw6v3sgy3e4lHkjX:b-kgkaze) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L201)):*
> ```
> struct shim_process
> ```

nitpick: sizeof(*process) and so on.
In graphene, variable name is preferred to type name.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 202 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqBBnxDIbSxQVxEkDB:-MLqBBnxDIbSxQVxEkDC:buax35x) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L202)):*
> ```
> sizeof(struct shim_child_process)
> ```
ditto.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 204 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqBGN7-xZwUtV4y15C:-MLqBGN7-xZwUtV4y15D:buax35x) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L204)):*
> ```
> sizeof(struct shim_child_process)
> ```
ditto.


<!-- Sent from Reviewable.io -->

2020-11-11 10:00 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/sys/shim_wait.c, line 89 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqjMzPDFOjujvNhN3h:-MLqjMzPDFOjujvNhN3i:b-qd1afj) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/sys/shim_wait.c#L89)):*
> ```C
>         }
>         /* We cannot handle any errors here. */
>         (void)thread_sleep(NO_TIMEOUT);
> ```

Why do we need to sleep here?
___
*[LibOS/shim/src/sys/shim_wait.c, line 198 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqj_2S2icF46OB8c05:-MLqj_2S2icF46OB8c06:bs71ci7) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/sys/shim_wait.c#L198)):*
> ```C
>             }
> 
>             DkEventClear(self->scheduler_event);
> ```

This seems race. Probably DkEventClear() should be done within lock or before queuing thread.


<!-- Sent from Reviewable.io -->

2020-11-12 00:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 42 of 46 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_thread.h, line 84 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqE1vl4X-Izt4ERyFz:-MLtg0UO53Xzq7Q61HwN:b97wb6d) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/include/shim_thread.h#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`blocking parts` is ambiguous. Maybe add an example in parenthesis? Like `...blocking parts (e.g. blocking read on a network socket) ...`
</blockquote></details>

Removed the part about blocking, check the comment now.
___
*[LibOS/shim/include/shim_thread.h, line 118 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqENNe0yuNCdtYdk_j:-MLtgDlk4Eh92k-amkt8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/include/shim_thread.h#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`distinquish` -> `distinguish`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 19 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq66y4D7Pn6ILFJYOb:-MLtnbN7CcA1tRWj55Bk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L19)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> struct shim_child_process*
> ```

const struct shim_child_process*. Maybe a matter of preference.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 59 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5_Vq0DQrlY5KXqXu:-MLtgubG0ROUNxrmCpIp:b-8ucv2b) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L59)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

This expects that all mount points are initialized.
So init_process() should be called after init_mount().
</blockquote></details>

I don't think we can change the order of inits, `init_mount` relies on `g_process.root` (hence `fs_lock` too) being initialized. Maybe we should temporarily set `cwd` to be the same as `root` and then change it after `init_mount` if needed?
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 201 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqAw6v3sgy3e4lHkjW:-MLthYbXC0yJCRnWFgk_:b6i1l9a) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L201)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> struct shim_process
> ```

nitpick: sizeof(*process) and so on.
In graphene, variable name is preferred to type name.
</blockquote></details>

That's true, but in this case it should be `sizeof(*new_process)`, but `new_process` is defined and initialized based on `off` which is created in this line ...
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 202 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqBBnxDIbSxQVxEkDB:-MLtiGZr7W02gf0GiNYB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L202)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> sizeof(struct shim_child_process)
> ```
ditto.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 204 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqBGN7-xZwUtV4y15C:-MLtiadYEccpRGMlNxbz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L204)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> sizeof(struct shim_child_process)
> ```
ditto.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 32 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLh7cf2E61RTmCLznEv:-MLtisLmC5GerRvgje7b:byv8p98) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/ipc/shim_ipc_child.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Is vmid really the host pid? Because then this truncation does not make much sense.

No, it's a bit more complicated than just a host pid:
```
LibOS/shim/src/shim_init.c:    g_process_ipc_info.vmid = (IDTYPE)PAL_CB(process_id);
src/host/Linux-SGX/db_main.c:    g_linux_state.process_id = (start_time & (~0xffff)) | g_pal_sec.pid;
```

I don't know the reason behind throwing the timestamp in the `vmid` value...

> Also wouldn't it be an issue if a malicious host (in case of SGX) would show same host-level pid to two processes, wouldn't ipc code get lost then?

Yes, I think it's a legit issue (the attacker currently also needs to adjust the `start_time` but that's doable). Though recall that all IPC is encrypted in SGX, and two processes with the same `vmid` will conflict on the TLS sequence numbers, so it looks only DoS attacks are possible with this.
</blockquote></details>

Okey, if it is only DoS type then it's ok, trusting you on this :)
___
*[LibOS/shim/src/sys/shim_getpid.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhKmzeBsexHJJcq2f9:-MLtjwDiDzf-fysehsAH:b-fjijpg) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_getpid.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But we also update `cur->clear_child_tid` in a non-atomic way. Could it lead theoretically to "partial updates" when the same thread calls `set_tid_address()` in the main execution and in the signal handler?
</blockquote></details>

Oops, you are right, I was talking only about `tid` read here, `clear_child_tid` needs a lock. Done.
___
*[LibOS/shim/src/sys/shim_wait.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLhRnWOBP9X5nPkdt4I:-MLtlSSMAzsUi0SLmrDp:bm233n9) ([raw file](https://github.com/oscarlab/graphene/blob/b0dd06361e1e17afe46df42b7f4ff56dab6a84ff/LibOS/shim/src/sys/shim_wait.c#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, now I got it.
</blockquote></details>

Also `while (!seen) {}` is just a shortcut for `if (!seen) while (1) {}`
___
*[LibOS/shim/src/sys/shim_wait.c, line 89 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqjMzPDFOjujvNhN3h:-MLtleWRDuVJDA2ynUXE:bgm2dj2) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/sys/shim_wait.c#L89)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Why do we need to sleep here?
</blockquote></details>

We could do a busy loop, but I guess sleeping is better? On the other hand if we got removed from the `g_process.wait_queue` then `in_use` should be cleared soon, so buys loop isn't that bad ... I don't know, I don't have any preference on either approach, let me know which one you think is better.
___
*[LibOS/shim/src/sys/shim_wait.c, line 198 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqj_2S2icF46OB8c05:-MLtmDF08-Agkb1nd5R5:bhku33f) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/sys/shim_wait.c#L198)):*
<details><summary><i>Previously, yamahata wr [...]

2020-11-12 01:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 42 of 46 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 732 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqNKArE3lsDFnYqHKh:-MLu4Tql0xWh2Pl-wXcm:b-3vemss) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/ipc/shim_ipc_helper.c#L732)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not really related to your changes, but I think there is a data race in the IPC helper: `install_new_event` is used to unblock the IPC helper thread if it is in blocking poll (on new-port-added or old-port-deleted events).

When we do `clear_event()`, it clears all events, and it may happen after `unlock(ipc_helper_lock)` in the previous iteration of the while loop and before `lock(ipc_helper_lock)` in a new iteration of the while loop. So very rarely, new-port-added and old-port-deleted events may be lost.

The lost event of new-port-added seems fine -- this code re-adds the ports from the global `port_list` anyway, so the IPC helper will learn about the newly added port. However, the lost event of old-port-deleted seems bad -- the `del_ipc_port_fini()` callback may never be called on this deleted port (the IPC helper doesn't notice this event). I wonder if this can manifest in hangs of applications?

I can unblock this comment if this thinking is wrong or if this is out of scope of this PR.
</blockquote></details>

Yeah, this needs more consideration.
I only thought about case of adding/removing ports from that poll list, which is race free currently (all `set_event` and `clear_event` are done under `ipc_herlper_lock`; if such event appears before we do `clear_event` at the loop begning, it must have been done before we got the lock hence we will notice all port list changes).
If a port gets disconnected, shouldn't it trigger poll on its pal handle?


<!-- Sent from Reviewable.io -->

2020-11-12 10:52 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_process.c, line 59 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5_Vq0DQrlY5KXqXu:-MLw2uc_2rdko3cxuZk6:bd47x0p) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think we can change the order of inits, `init_mount` relies on `g_process.root` (hence `fs_lock` too) being initialized. Maybe we should temporarily set `cwd` to be the same as `root` and then change it after `init_mount` if needed?
</blockquote></details>

Good catch from Isaku!

I agree with Borys that we should keep the order of inits as now (`init_process`, then `init_mount`). As Borys suggests, let's:
1. Set `g_process.cwd = g_process.root` temporarily.
2. Move the "init cwd from fs.start_dir" to the very end of `init_mount()`. This makes sense because only at that point Graphene mounted all available directories, and now Graphene can finally set CWD. (In a cleaner approach, if Borys really wants, he can introduce a new `init_cwd()` function that is called right after `init_mount()`).
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 732 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqNKArE3lsDFnYqHKh:-MLw-6K65K0LV0EdGey-:b6nzk9s) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/ipc/shim_ipc_helper.c#L732)):*
> If a port gets disconnected, shouldn't it trigger poll on its pal handle?

But I'm describing exactly this case when a port get disconnected in a time window `(after poll, before clear_event)`. The port is already not in the`port_list` (so it won't be readded to the poll) and its disconnect wasn't triggered on poll because it happened after poll. 

Or did you mean something else?


<!-- Sent from Reviewable.io -->

2020-11-12 14:52 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 732 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqNKArE3lsDFnYqHKh:-MLww8MmD2uZH3HyXyE-:b-2nz8at) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/ipc/shim_ipc_helper.c#L732)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> If a port gets disconnected, shouldn't it trigger poll on its pal handle?

But I'm describing exactly this case when a port get disconnected in a time window `(after poll, before clear_event)`. The port is already not in the`port_list` (so it won't be readded to the poll) and its disconnect wasn't triggered on poll because it happened after poll. 

Or did you mean something else?
</blockquote></details>

Isn't a disconnected port manually removed from the ports list in the loop after poll?


<!-- Sent from Reviewable.io -->

2020-11-12 14:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 732 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLqNKArE3lsDFnYqHKh:-MLwxWaeD01wR9L-dimK:b-96ujwe) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/ipc/shim_ipc_helper.c#L732)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't a disconnected port manually removed from the ports list in the loop after poll?
</blockquote></details>

Ok, I was over-thinking it. If the port got disconnected after the poll, it will **not** be removed from the `port_list` until the next poll (where it will be noticed in its `revents` that it got disconnected). So there is no data race on this. Ignore me.


<!-- Sent from Reviewable.io -->

2020-11-13 02:00 UTC, boryspoplawski reviewed
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 46 of 49 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/shim_init.c, line 501 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5mf32NTjMUjY8aoZ:-MLzK58S4uGQnZESQ3W_:bc46p07) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/shim_init.c#L501)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

init_process() should be after init_mount().
Please see the comment in init_process().
</blockquote></details>

Please check the other comment.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 59 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5_Vq0DQrlY5KXqXu:-MLzKBCN3FE8LJMHAu6D:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good catch from Isaku!

I agree with Borys that we should keep the order of inits as now (`init_process`, then `init_mount`). As Borys suggests, let's:
1. Set `g_process.cwd = g_process.root` temporarily.
2. Move the "init cwd from fs.start_dir" to the very end of `init_mount()`. This makes sense because only at that point Graphene mounted all available directories, and now Graphene can finally set CWD. (In a cleaner approach, if Borys really wants, he can introduce a new `init_cwd()` function that is called right after `init_mount()`).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-13 08:19 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-13 10:42 UTC, dimakuv commented
Jenkins, retest this please (now Jenkins is back again)

2020-11-13 12:38 UTC, boryspoplawski commented
Jenkins, retest this please (making sure, run 2/10)

2020-11-13 15:19 UTC, boryspoplawski commented
Jenkins, retest this please (making sure, run 3/10)

2020-11-15 21:36 UTC, mkow requested changes
> Reviewed 30 of 46 files at r3, 1 of 2 files at r4, 11 of 13 files at r6, 1 of 1 files at r7, 2 of 3 files at r8, 2 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 52 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLVEz1WDXZ1T4_CJghs:-MMCoh7e2yWEbs7L_C2d:bevaszu) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: check if any LTP test can be enabled (probably after debugging IPC issue).
</blockquote></details>

You fixed that pipes bug, I think you can check the LTPs now.

---
___
*[LibOS/shim/include/shim_internal.h, line 507 at r8](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLuQV52BK6Y2ANVFysH:-MLuQV531TnwKsnQdIid:b-ap178q) ([raw file](https://github.com/oscarlab/graphene/blob/f0401e4c32615781ca5120d5d6a69dc8b6220f44/LibOS/shim/include/shim_internal.h#L507)):*
> ```objc
> void delete_from_epoll_handles(struct shim_handle* handle);
> 
> void* allocate_stack(size_t size, size_t protect_size, bool user);
> ```

Could you document the arguments here?
___
*[LibOS/shim/include/shim_process.h, line 23 at r8](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzB89m0jiEf50lYeVh:-MLzB89nDhwML0WeGVTb:b5px5cn) ([raw file](https://github.com/oscarlab/graphene/blob/f0401e4c32615781ca5120d5d6a69dc8b6220f44/LibOS/shim/include/shim_process.h#L23)):*
> ```objc
>     IDTYPE vmid;
> 
>     int child_termination_signal;
> ```

Please explain this field in a comment (I know what it does, but it's not a well-known feature in Linux)
___
*[LibOS/shim/include/shim_process.h, line 68 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzEzof2MUFjrSGkiIX:-MLzEzof2MUFjrSGkiIY:bf0lrml) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_process.h#L68)):*
> ```objc
> /* Allocates a new child process structure, initializing all fields. */
> struct shim_child_process* create_child_process(void);
> /* Frees `child` with all acompanying resources. */
> ```

`acompanying` -> `accompanying`
___
*[LibOS/shim/include/shim_process.h, line 21 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM84zC18soGLCpt3lkH:-MM84zC18soGLCpt3lkI:b-4y5sp7) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/include/shim_process.h#L21)):*
> ```objc
> struct shim_child_process {
>     IDTYPE pid;
>     IDTYPE vmid;
> ```

Could you comment here what's this "vmid"?
___
*[LibOS/shim/include/shim_process.h, line 28 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM85V8m8H-YEkeZoU2d:-MM85V8nELMcKfQZXKE-:b-rm6iol) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/include/shim_process.h#L28)):*
> ```objc
>     int exit_code;
>     int term_signal;
>     IDTYPE uid;
> ```

Uid of what? I looks like it's not just the uid of the child process, because why would it be set only on the termination?
___
*[LibOS/shim/include/shim_thread.h, line 59 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzGuaJ7H-55rHHPYE9:-MLzGuaKDFLRvITuFaS2:b-19zyp5) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_thread.h#L59)):*
> ```objc
>     LIST_TYPE(shim_thread) list;
> 
>     /* thread identifiers */
> ```

`identifiers` -> `identifier`
___
*[LibOS/shim/include/shim_thread.h, line 89 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzHy_4AfKXz4NhnWTj:-MLzHy_4AfKXz4NhnWTk:b-q2g11k) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_thread.h#L89)):*
> ```objc
>      * - `SIGNAL_NOT_HANDLED` - usually initialized to this - no signals were handled,
>      * - `SIGNAL_HANDLED` - at least one signal was handled,
>      * - `SIGNAL_HANDLED_RESTART` - same as above, but the signal had `SA_RESTART` flag.
> ```

Could you use an enum then?
___
*[LibOS/shim/include/shim_thread.h, line 143 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzJSMk9O--p0yXEvDL:-MLzJSMk9O--p0yXEvDM:b-ajcxie) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_thread.h#L143)):*
> ```objc
> void debug_setprefix(shim_tcb_t* tcb);
> 
> /* Set `debug_buf` for `tcb`. If `debug_buf` is `NULL`, then new one is allocated. IF `debug_buf`
> ```

`IF` -> `If`
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 51 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM82G--ETJJXIEfhDiW:-MM82G--ETJJXIEfhDiX:b-bm39sc) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L51)):*
> ```C
>     int ret = path_lookupat(NULL, "/", 0, &dent, NULL);
>     if (ret < 0) {
>         debug("Could not setup dentry for \"/\", something is seriously broken.\n");
> ```

`setup` -> `set up`
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 100 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM85x5o0IfQVyymELZb:-MM85x5o0IfQVyymELZc:b-kq9wgg) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L100)):*
> ```C
> }
> 
> static bool mark_child_exited(child_cmp_t child_cmp, unsigned long arg, IDTYPE uid, int exit_code,
> ```

ditto - uid of what?
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 157 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM87juiC9AzqzuIOBdU:-MM87juiC9AzqzuIOBdV:bcota5y) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L157)):*
> ```C
>         struct shim_thread* thread = wait_queue->thread;
>         __atomic_store_n(&wait_queue->in_use, false, __ATOMIC_RELEASE);
>         COMPILER_BARRIER();
> ```

Isn't that atomic operation above already a compiler barrier?
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 215 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM89GMu5_tJ0OuZW3AH:-MM89GMu5_tJ0OuZW3AI:b-jyhl3t) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L215)):*
> ```C
>     clear_lock(&new_process->children_lock);
> 
>     *(size_t*)((char*)new_process + sizeof(*new_process)) = children_count;
> ```

Could you maintain a pointer to the data and advance it, instead of calculating the offset again and again below?
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 645 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8Dnyq2ElSBfINoFhZ:-MM8Dnyq2ElSBfINoFh_:b-g5n3zu) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_signal.c#L645)):*
> ```C
>     __UNUSED(context);
>     siginfo_t info = {
>         .si_signo = SIGINT,
> ```

umm, why is "suspend" function sending a SIGINT?
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MM8FViB1dbKemaiupo3:b-xb8j1u) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
> ```
> shim_signal_handles
> ```

Not handle**r**s?
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 105 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8GPJW8yF6BALYjMha:-MM8GPJW8yF6BALYjMhb:brychj1) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/b [...]

2020-11-16 17:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 30 of 49 files reviewed, 52 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 507 at r8](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLuQV52BK6Y2ANVFysH:-MMG_8Hw86AG2XHXN_e4:blm7fa5) ([raw file](https://github.com/oscarlab/graphene/blob/f0401e4c32615781ca5120d5d6a69dc8b6220f44/LibOS/shim/include/shim_internal.h#L507)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you document the arguments here?
</blockquote></details>

I did not add these functions, just moved them from `shim_thread.h`, because they are implemented in `shim_init.c`. I could try to check them up and write something here ...
___
*[LibOS/shim/include/shim_process.h, line 23 at r8](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzB89m0jiEf50lYeVh:-MMGbBKs6SOd5MPvm6ba:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f0401e4c32615781ca5120d5d6a69dc8b6220f44/LibOS/shim/include/shim_process.h#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please explain this field in a comment (I know what it does, but it's not a well-known feature in Linux)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_process.h, line 68 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzEzof2MUFjrSGkiIX:-MMGbQv44k9r0tK34wJ0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_process.h#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`acompanying` -> `accompanying`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_process.h, line 21 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM84zC18soGLCpt3lkH:-MMGa55k328LA0aUZ4qx:b1lir98) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/include/shim_process.h#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you comment here what's this "vmid"?
</blockquote></details>

I have no idea what that is. All I know is that uniquely identifies a process and IPC code sometimes uses it.
___
*[LibOS/shim/include/shim_process.h, line 28 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM85V8m8H-YEkeZoU2d:-MMGaMAu2NbGrG4dk9Ai:b-5bwe8t) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/include/shim_process.h#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Uid of what? I looks like it's not just the uid of the child process, because why would it be set only on the termination?
</blockquote></details>

This is uid of the child process and it's set on process termination, so that it can be reported in `waitid`.
___
*[LibOS/shim/include/shim_thread.h, line 59 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzGuaJ7H-55rHHPYE9:-MMGbndX8amMjSxRG_1P:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_thread.h#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`identifiers` -> `identifier`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 89 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzHy_4AfKXz4NhnWTj:-MMGbvq_-54rXo_Gh3-0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_thread.h#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you use an enum then?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 143 at r9](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLzJSMk9O--p0yXEvDL:-MMGctY5Amr8P9Hq89aq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1fb3e4fb8ad0723faecd50a63e401d360dcac375/LibOS/shim/include/shim_thread.h#L143)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`IF` -> `If`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 51 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM82G--ETJJXIEfhDiW:-MMGdBEf2Y2oO60BSUU8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`setup` -> `set up`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 100 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM85x5o0IfQVyymELZb:-MMGyunF6HoxG9hPz7lE:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto - uid of what?
</blockquote></details>

ditto
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 157 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM87juiC9AzqzuIOBdU:-MMGf8uSBS5ogwDhFYdT:b8dxdh6) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't that atomic operation above already a compiler barrier?
</blockquote></details>

Afaik release only prevents code before it from being moved after and gives no such guarantees on the other direction, so I've put the barrier to be sure (we rely on correct ordering here).
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 215 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM89GMu5_tJ0OuZW3AH:-MMGh3xmEvPjFq3Cs2Er:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L215)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you maintain a pointer to the data and advance it, instead of calculating the offset again and again below?
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 645 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8Dnyq2ElSBfINoFhZ:-MMGitTT6EheZdEcS9Z1:bnpi2b2) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_signal.c#L645)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

umm, why is "suspend" function sending a SIGINT?
</blockquote></details>

No idea?
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MMGjMowDBTZoXgECpkQ:b-xcih4w) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> shim_signal_handles
> ```

Not handle**r**s?
</blockquote></details>

Idk, but I guess this struct has more data than just the handler.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 105 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8GPJW8yF6BALYjMha:-MMGjaAT1K36gy8P-VKx:bhh6922) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L105)):*
<details> [...]

2020-11-16 17:05 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 30 of 49 files reviewed, 52 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 647 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCDGCcD54Ess4lq1VK:-MMH0C3AE03u0Q6Urn3p:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/ipc/shim_ipc_helper.c#L647)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> /* Wake up the helper thread. */
> ```

Aren't we inside a function named "pause_ipc_helper"? Why are we waking anything up? Please clarify this comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-16 20:07 UTC, yamahata approved these changes
> Reviewed 1 of 3 files at r8, 2 of 2 files at r9, 18 of 18 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 46 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_process.c, line 59 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5_Vq0DQrlY5KXqXu:-MMHdXJ52p69RaRpQGXm:bpwr1zk) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, that's complicated. Maybe we can defer that issue as follow up PR.
___
*[LibOS/shim/src/sys/shim_clone.c, line 173 at r12](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMHeRLE2-21O-VYz3V3:-MMHeRLE2-21O-VYz3V4:blm60c8) ([raw file](https://github.com/oscarlab/graphene/blob/1fba07880e4e8da5d18a27371cc9f31a95a6a9a5/LibOS/shim/src/sys/shim_clone.c#L173)):*
> ```C
>      * even without any locks. Note this is a shallow copy, so `shim_tcb.context.regs` will be
>      * shared with the parent. */
>     shim_tcb.context.regs = self->shim_tcb->context.regs;
> ```

Do we want to copy regs twice?
Probably it's just micro-optimization, it wouldn't affect clone performance.
So I don't block it here.


<!-- Sent from Reviewable.io -->

2020-11-16 20:11 UTC, mkow requested changes
> Reviewed 18 of 18 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 14 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/shim_internal.h, line 507 at r8](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLuQV52BK6Y2ANVFysH:-MMHG9W64WnV-odhxaEd:b-23md8g) ([raw file](https://github.com/oscarlab/graphene/blob/f0401e4c32615781ca5120d5d6a69dc8b6220f44/LibOS/shim/include/shim_internal.h#L507)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did not add these functions, just moved them from `shim_thread.h`, because they are implemented in `shim_init.c`. I could try to check them up and write something here ...
</blockquote></details>

Ok, fine then.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 100 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM85x5o0IfQVyymELZb:-MMHHn3g833dsFlqCgLU:b-t48oyq) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Could you rename it to `child_uid` then? It's not obvious from the context here which uid is this.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 157 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM87juiC9AzqzuIOBdU:-MMHJscW5yEW2LVGWhGF:b77vw0l) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L157)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Afaik release only prevents code before it from being moved after and gives no such guarantees on the other direction, so I've put the barrier to be sure (we rely on correct ordering here).
</blockquote></details>

I rather thought it has function call semantics and can't be reordered with other calls. But I'm not sure.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 645 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8Dnyq2ElSBfINoFhZ:-MMHPj1z1rlbrJOZ6qQ9:b32vi2) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_signal.c#L645)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No idea?
</blockquote></details>

:/
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MMHPuZKAXHHQrBOEqpz:byggutz) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Idk, but I guess this struct has more data than just the handler.
</blockquote></details>

Isn't it just a list of handlers with a lock+refcount? They aren't any kind of handles.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 105 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8GPJW8yF6BALYjMha:-MMHQ92F-dPrLoJBAUFz:b-kzk4qf) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it is exactly that: a constructor of the `struct shim_thread` for the main thread (+ creates one global lock).
</blockquote></details>

Then it should be `init_first_thread`. The bare `init_thread` is confusing, because "which thread?".
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 204 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8ObB8BnwJF0XZYFUA:-MMHQs2285tYZX0wxcxB:bydvkzr) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L204)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yup.
</blockquote></details>

Doesn't sound like this makes any sense. Could you explain it?
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 277 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMAouvuDYpOA6-e-s5X:-MMHRrj99WaIAiHMGXTp:b8fh15j) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L277)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think `signal_altstack` is allocated by user app, not Graphene.
</blockquote></details>

Could you add a comment here explaining why it's skipped?
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 285 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMAp2k6-fp_WAu8ofOF:-MMHRuMrAIywRTQWPQ6w:b-lyc7mw) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L285)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`wake_queue` is only meaningful when this `thread` is part of some wakeup queue (is just being woken up), which would imply `ref_count > 0`.
</blockquote></details>

ok, but ditto - please put this into a comment
___
*[LibOS/shim/src/fs/shim_fs.c, line 241 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMBA2cS6jocuNYjSDLX:-MMHTGJvERUgfguO7PuB:bxdo5pz) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/fs/shim_fs.c#L241)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And what should I do about it now? It will be fix it when rebasing.
</blockquote></details>

Nothing yet, just a heads up + a note to me to carefully review this conflict afterwards.
___
*[LibOS/shim/src/sys/shim_exec.c, line 435 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCQi_77xCC3MuQYtz6:-MMH_3eX69CuuAaJsjUg:bn6wt5) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_exec.c#L435)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because `g_process` is passed as process description to `create_process_and_send_checkpoint` below.
</blockquote></details>

Could you comment this? Was quite confusing for me.
___
*[LibOS/shim/src/sys/shim_wait.c, line 6 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCifYt8C6NHKvZhpoH:-MMHaKo52-xdgJNaMax4:b-u0u08q) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_wait.c#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`linux/signal.h` iirc. Even if only on 16.04, it's still supported.
</blockquote></details>

I meant, please clarify this in the comment so that we won't need to debug this again and just remove after we get rid of 16.04.


<!-- Sent from Reviewable.io -->

2020-11-17 01:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 42 of 49 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_process.c, line 59 at r6](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLq5_Vq0DQrlY5KXqXu:-MMIU1IeAO_PyeyWc4MB:b-gw1tdz) ([raw file](https://github.com/oscarlab/graphene/blob/e7f25b0a48d68b9c882e33951db77b34defeadbb/LibOS/shim/src/bookkeep/shim_process.c#L59)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Oh, that's complicated. Maybe we can defer that issue as follow up PR.
</blockquote></details>

@yamahata it's already solved in this PR :)
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 100 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM85x5o0IfQVyymELZb:-MMIVaQj3Y5iR4NB5zPk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you rename it to `child_uid` then? It's not obvious from the context here which uid is this.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 157 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM87juiC9AzqzuIOBdU:-MMIVjAb1lqfHtUq9b4c:b-9cdkfe) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_process.c#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I rather thought it has function call semantics and can't be reordered with other calls. But I'm not sure.
</blockquote></details>

Functions can be inlined, even at link time, better be safe than sorry. I'll add a comment for the future.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MMIaSIcDSpYr2K0H763:b37dpl5) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't it just a list of handlers with a lock+refcount? They aren't any kind of handles.
</blockquote></details>

Almost yes: not handlers, but `struct sigaction`, which contains a handler, flags, signal mask and such.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 105 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8GPJW8yF6BALYjMha:-MMIanW54QabsWYOTytL:b45kdv8) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then it should be `init_first_thread`. The bare `init_thread` is confusing, because "which thread?".
</blockquote></details>

I would argue that since it's `init_*` it means the one and only thread we have.
I've split it into two functions, should be cleaner now.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 204 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8ObB8BnwJF0XZYFUA:-MMIcSGI5eAwaz_fJwMN:b-zfckhr) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L204)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Doesn't sound like this makes any sense. Could you explain it?
</blockquote></details>

We need some defaults and it makes sense to copy the current thread values (especially for fields like `uid`). The caller should change these if they wish so. Currently the only usage of this function is in `shim_do_clone`, does **NOT** change these values in case of a fork (after all, the main and only thread in newly forked process will have the same stack pointer values).
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 277 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMAouvuDYpOA6-e-s5X:-MMIdwPU6fyiDYRELPZP:br36ek9) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L277)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a comment here explaining why it's skipped?
</blockquote></details>

We skip like 60% of fields, why only comment this one? And I'm not sure how to describe why we do nothing with e.g. `signal_mask` ...
___
*[LibOS/shim/src/sys/shim_clone.c, line 173 at r12](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMHeRLE2-21O-VYz3V3:-MMIf8k5-sDw4ssWQxg4:b-co792k) ([raw file](https://github.com/oscarlab/graphene/blob/1fba07880e4e8da5d18a27371cc9f31a95a6a9a5/LibOS/shim/src/sys/shim_clone.c#L173)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Do we want to copy regs twice?
Probably it's just micro-optimization, it wouldn't affect clone performance.
So I don't block it here.
</blockquote></details>

I'm not sure what you mean. Where do we copy `regs`? Here we just copy the pointer to it.
___
*[LibOS/shim/src/sys/shim_exec.c, line 435 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCQi_77xCC3MuQYtz6:-MMIfbLB8MCSDQ4ebZN2:b-fv6y5h) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_exec.c#L435)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you comment this? Was quite confusing for me.
</blockquote></details>

There is a comment above: `We are the only thread running (...)`
___
*[LibOS/shim/src/sys/shim_wait.c, line 6 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCifYt8C6NHKvZhpoH:-MMIlD1PEmmSQe6bj9Eu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_wait.c#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I meant, please clarify this in the comment so that we won't need to debug this again and just remove after we get rid of 16.04.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 02:40 UTC, mkow requested changes
> Reviewed 7 of 7 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MMJ0blB8YHjGMQExyzT:b-qhf7rf) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Almost yes: not handlers, but `struct sigaction`, which contains a handler, flags, signal mask and such.
</blockquote></details>

But those are not handles, maybe some aux info/description of a handler. A "handle" is a "proxy" object to something inaccessible in your current environment, e.g. fds on Linux or PAL handles in Graphene (though "inaccessibility" there is enforced only by the opaque pointers).
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 277 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMAouvuDYpOA6-e-s5X:-MMJ2Fqj4LjWZkh877Kb:bmebkl1) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L277)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We skip like 60% of fields, why only comment this one? And I'm not sure how to describe why we do nothing with e.g. `signal_mask` ...
</blockquote></details>

For easier verification - to verify if everything is correctly freed and nothing is leaked you go side-by-side here and with the structure and compare. Missing and not mentioned fields are red-flags for me when verifying such code.
Ofc no need to comment non-pointer/non-struct/trivial fields.
___
*[LibOS/shim/src/sys/shim_exec.c, line 435 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCQi_77xCC3MuQYtz6:-MMJ32F40vBZi8cIwGs0:b-j02hi0) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_exec.c#L435)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is a comment above: `We are the only thread running (...)`
</blockquote></details>

Yeah, but the comment above is about locking. What was confusing to me here was that we reuse current `g_process` temporarily as an argument to the call below (I missed that it's passed there and thought that you're temporarily altering the global state for some reason).


<!-- Sent from Reviewable.io -->

2020-11-17 03:48 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 48 of 49 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MMJ4SSAEJlCfVwOxQmY:b-r8h0e) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But those are not handles, maybe some aux info/description of a handler. A "handle" is a "proxy" object to something inaccessible in your current environment, e.g. fds on Linux or PAL handles in Graphene (though "inaccessibility" there is enforced only by the opaque pointers).
</blockquote></details>

I do not insist on "handles", but these definitely are not just "handlers". Only name that comes to my mind is `shim_sigactions`, which I do not like particularly.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 277 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMAouvuDYpOA6-e-s5X:-MMJDbn7BQZUhBoVt9wM:b3bz7t) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L277)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For easier verification - to verify if everything is correctly freed and nothing is leaked you go side-by-side here and with the structure and compare. Missing and not mentioned fields are red-flags for me when verifying such code.
Ofc no need to comment non-pointer/non-struct/trivial fields.
</blockquote></details>

I do the same thing, but I'm not sure which fields are trivial (probably only uids). Added a comment about those you requested specifically.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 285 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMAp2k6-fp_WAu8ofOF:-MMJGvtDEnA6kQXimAz2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L285)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ok, but ditto - please put this into a comment
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_exec.c, line 435 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCQi_77xCC3MuQYtz6:-MMJIgeU2rFoy7GDa7KY:b-rmc0ty) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_exec.c#L435)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but the comment above is about locking. What was confusing to me here was that we reuse current `g_process` temporarily as an argument to the call below (I missed that it's passed there and thought that you're temporarily altering the global state for some reason).
</blockquote></details>

It also says `we can safely pass them as arguments below`. I'm really not sure what should I write there, let me know about some specific comment you want to have here.


<!-- Sent from Reviewable.io -->

2020-11-17 09:02 UTC, dimakuv reviewed
> Reviewed 13 of 18 files at r11, 1 of 1 files at r12, 6 of 7 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2020-11-17 14:03 UTC, mkow requested changes
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MMLUcuR3IUMzQyVov9D:b-nvma2d) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I do not insist on "handles", but these definitely are not just "handlers". Only name that comes to my mind is `shim_sigactions`, which I do not like particularly.
</blockquote></details>

Maybe "shim_sigaction_infos"? But for me `shim_sigactions` is fine.
___
*[LibOS/shim/src/sys/shim_exec.c, line 435 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCQi_77xCC3MuQYtz6:-MMLV0ZUE55WkZ36pLzK:be5jpeg) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_exec.c#L435)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It also says `we can safely pass them as arguments below`. I'm really not sure what should I write there, let me know about some specific comment you want to have here.
</blockquote></details>

Maybe something like "// temporarily reuse it as an argument to create_process_and_send_checkpoint" or something similar? This pattern is just quite unexpected and would be good to warn the reader what happens here.


<!-- Sent from Reviewable.io -->

2020-11-17 17:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: 44 of 49 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 40 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MM8FViB1dbKemaiupo2:-MMM6nj-9AwXtqoVAOCu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/bookkeep/shim_thread.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe "shim_sigaction_infos"? But for me `shim_sigactions` is fine.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_exec.c, line 435 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMCQi_77xCC3MuQYtz6:-MMM3pBEBO7_1kYCpkyx:b-e4wpps) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/sys/shim_exec.c#L435)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe something like "// temporarily reuse it as an argument to create_process_and_send_checkpoint" or something similar? This pattern is just quite unexpected and would be good to warn the reader what happens here.
</blockquote></details>

Check it now.


<!-- Sent from Reviewable.io -->

2020-11-17 17:33 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-17 21:04 UTC, boryspoplawski reviewed
> Reviewed 3 of 13 files at r6, 1 of 3 files at r8, 2 of 2 files at r9, 11 of 18 files at r11, 1 of 1 files at r12, 4 of 7 files at r13, 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-17 21:37 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-17 21:53 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 12 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLgdzoT23jplINYA5xK:-MMNAXHzBDWx5VrF6spx:b-qyoh9a) ([raw file](https://github.com/oscarlab/graphene/blob/3fa93cc86f3d7f01a81ef387eadd3c29bf4738a2/LibOS/shim/src/bookkeep/shim_handle.c#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Right, merging this will take longer for sure.
</blockquote></details>

Resolving for now but please be careful during rebase.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 227 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBYPG43tVqUZLxH1s:-MMNBYPH7DummVFaa62q:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_process.c#L227)):*
> ```C
>     size_t i = 0;
>     LISTP_FOR_EACH_ENTRY(child, &process->children, list) {
>         memcpy(&children[i], child, sizeof(children[i]));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 240 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNB_6lDDYvmzt2nfhv:-MMNB_6lDDYvmzt2nfhw:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_process.c#L240)):*
> ```C
>     i = 0;
>     LISTP_FOR_EACH_ENTRY(zombie, &process->zombies, list) {
>         memcpy(&zombies[i], zombie, sizeof(zombies[i]));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 301 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBaXz9eWVlF7EVpJS:-MMNBaXz9eWVlF7EVpJT:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_process.c#L301)):*
> ```C
>     }
> 
>     memcpy(&g_process, process, sizeof(g_process));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 438 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNAhmv3Ormo6kbhZkQ:-MMNAhmv3Ormo6kbhZkR:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_thread.c#L438)):*
> ```C
>         lock(&dispositions->lock);
> 
>         memcpy(new_dispositions, dispositions, sizeof(*dispositions));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 479 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBJeHAHZkKAIaiP0y:-MMNBJeHAHZkKAIaiP0z:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_thread.c#L479)):*
> ```C
>         ADD_TO_CP_MAP(obj, off);
>         new_thread = (struct shim_thread*)(base + off);
>         memcpy(new_thread, thread, sizeof(struct shim_thread));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 553 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBMB4DyW9qZgtxcRS:-MMNBMB4DyW9qZgtxcRT:b-s69pu6) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_thread.c#L553)):*
> ```C
> 
>         shim_tcb_t* tcb = shim_get_tcb();
>         memcpy(tcb, thread->shim_tcb, sizeof(*tcb));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase. (This was probably fixed already.)
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 49 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBRly3EAX6DxG3abf:-MMNBRly3EAX6DxG3abg:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/sys/shim_sigaction.c#L49)):*
> ```C
> 
>     if (oldact) {
>         memcpy(oldact, sigaction, sizeof(*oldact));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 53 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBSVzAOkCQ5JAozpw:-MMNBSVzAOkCQ5JAozpx:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/sys/shim_sigaction.c#L53)):*
> ```C
> 
>     if (act) {
>         memcpy(sigaction, act, sizeof(*sigaction));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 175 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBU4mCFcjkrzRkxVz:-MMNBU4mCFcjkrzRkxW-:b-dwuj6f) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/sys/shim_sigaction.c#L175)):*
> ```C
> 
>     lock(&cur->lock);
>     memcpy(&old, get_sig_mask(cur), sizeof(old));
> ```

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.


<!-- Sent from Reviewable.io -->

2020-11-17 22:44 UTC, boryspoplawski reviewed
> Reviewed 15 of 15 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_process.c, line 227 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBYPG43tVqUZLxH1s:-MMNHpTd8Po1EimDtbZf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_process.c#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 240 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNB_6lDDYvmzt2nfhv:-MMNHq5I9hRN59lHrplL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_process.c#L240)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 301 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBaXz9eWVlF7EVpJS:-MMNHqd_7cRAPDnzfhx1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_process.c#L301)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 438 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNAhmv3Ormo6kbhZkQ:-MMNHrSK3IVMWKyBje9V:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_thread.c#L438)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 479 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBJeHAHZkKAIaiP0y:-MMNHs1y6BzhglFydXnS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_thread.c#L479)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 553 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBMB4DyW9qZgtxcRS:-MMNHtoG5XlZ3BjACzPm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/bookkeep/shim_thread.c#L553)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase. (This was probably fixed already.)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 241 at r10](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMBA2cS6jocuNYjSDLX:-MMNHxGdB18J98lKY4g2:bncvegj) ([raw file](https://github.com/oscarlab/graphene/blob/a2a5226c4147fe002809674df42b9b2928765cd6/LibOS/shim/src/fs/shim_fs.c#L241)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nothing yet, just a heads up + a note to me to carefully review this conflict afterwards.
</blockquote></details>

Rebased.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 49 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBRly3EAX6DxG3abf:-MMNI1ks79cJ4NzI7LpG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/sys/shim_sigaction.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 53 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBSVzAOkCQ5JAozpw:-MMNI4THEqLD3N6cTc-_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/sys/shim_sigaction.c#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 175 at r15](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMNBU4mCFcjkrzRkxVz:-MMNI5_M0NQvg1hT6Wah:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f2528d6a9bbe02ab92e559ea9e74ae280fc813f5/LibOS/shim/src/sys/shim_sigaction.c#L175)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change this to direct assignment, as Stefan did in a recent PR? You can do it during rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 23:24 UTC, mkow submitted a review, later dismissed
> Reviewed 15 of 15 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 11 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2020-11-18 07:25 UTC, dimakuv submitted a review, later dismissed
> Reviewed 15 of 15 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-11-18 17:51 UTC, boryspoplawski reviewed
> Reviewed 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMRTUH29C2MgnFwq1mY:-MMRTUH29C2MgnFwq1mZ:bmtwjnq) (no related file):*
@dimakuv Please check the last commit and let me know if this is the correct fix.

---
___
*[LibOS/shim/src/shim_init.c, line 59 at r17](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMRTeGeAe1OOIfi_3MC:-MMRTeGf4uzoVWr2Fmgm:b-v5gqgs) ([raw file](https://github.com/oscarlab/graphene/blob/650817dbbf90d6f2522741917f83485304ba342e/LibOS/shim/src/shim_init.c#L59)):*
> ```C
>     DEBUG_BREAK_ON_FAILURE();
>     /* `__abort` might be called by any thread, even internal. */
>     DkProcessExit(1);
> ```

This was a bug: IPC helper thread could call `process_exit`, but that function should be only called by norma (non-internal) threads.


<!-- Sent from Reviewable.io -->

2020-11-18 21:11 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-11-19 02:03 UTC, boryspoplawski reviewed
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1949#-MLVEz1WDXZ1T4_CJghs:-MMTEN0QBjM0tSys7DAM:bzbuvpo) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You fixed that pipes bug, I think you can check the LTPs now.
</blockquote></details>

Enable a few tests.

---


<!-- Sent from Reviewable.io -->

2020-11-19 02:12 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 125 at r16](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMTFl3_5JJwzEKUczbp:-MMTFl3_5JJwzEKUczbq:b-1gfq9e) ([raw file](https://github.com/oscarlab/graphene/blob/7d2052a2880cf2a373ca7890b5cd52b78d1c4146/LibOS/shim/test/ltp/ltp.cfg#L125)):*
> ```INI
> skip = yes
> 
> # measures difference between successive reading, fails from time to time because it's >5 ms
> ```

enabling this sounds risky, but let's see what Jenkins says...


<!-- Sent from Reviewable.io -->

2020-11-19 02:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMRTUH29C2MgnFwq1mY:-MMTGxDX5ZSaOoNL5XOM:bxrqgwq) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv Please check the last commit and let me know if this is the correct fix.
</blockquote></details>

TODO: reorder commits so that tty fix is before threads commit

---


<!-- Sent from Reviewable.io -->

2020-11-19 02:57 UTC, boryspoplawski commented
Jenkins, test this please (run 2/10)

2020-11-19 03:48 UTC, mkow commented
Jenkins, test this please (run 3/10)

2020-11-19 08:50 UTC, dimakuv commented
Jenkins, test this please (run 4/10; previous run failed only on `Jenkins` with `futex_wait02` timeout)

2020-11-19 10:37 UTC, dimakuv commented
Jenkins, test this please (run 5/10; previous run failed only on `Jenkins-Debug-18.04` with `clock_gettime01` failure)

2020-11-19 10:50 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r17, 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 3 unresolved discussions (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMRTUH29C2MgnFwq1mY:-MMV6z282M6qfcTLS966:b-vuxjvz) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: reorder commits so that tty fix is before threads commit
</blockquote></details>

Yes, the fix looks legit.

---
___
*[Pal/src/db_main.c, line 436 at r18](https://reviewable.io/reviews/oscarlab/graphene/1949#-MMV6oZB9sTU4_aZ-zSz:-MMV6oZB9sTU4_aZ-zT-:bz6ntr6) ([raw file](https://github.com/oscarlab/graphene/blob/e8b38f691407ae500b18163701d4a16981687526/Pal/src/db_main.c#L436)):*
> ```C
>         if (!parent_process) {
>             printf("WARNING: Using insecure argv source. Don't use this configuration in "
>                    "production!\n");
> ```

Thanks, this is much better :)


<!-- Sent from Reviewable.io -->

2020-11-19 11:42 UTC, mkow commented
Jenkins, retest this please (run 6/10; previous run failed on Jenkins-18.04 and Jenkins-Debug with `LTP.fork07: -> FAIL (returncode=1)`)

2020-11-19 13:06 UTC, mkow commented
Jenkins, retest this please (run 7/10; previous run failed on Jenkins-18.04 (`truncate01`, `truncate01_64`, `truncate02` and `truncate02_64` timed out) and Jenkins (`futex_wait02: -> ERROR (Timed out after 30.0 s.)`))

2020-11-19 14:02 UTC, mkow commented
Jenkins, retest this please (run 8/10; previous run failed on Jenkins-Debug-18.04 with `fork07: -> FAIL (returncode=1)` and timeouts on `sendfile08` and `sendfile08_64`)

2020-11-19 15:09 UTC, mkow commented
Jenkins, retest this please (run 9/10; previous run failed on Jenkins with `fork07: -> FAIL (returncode=1)`)

2020-11-19 16:36 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-11-19 17:14 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 7 files at r13, 1 of 5 files at r15, 13 of 15 files at r16, 4 of 4 files at r17, 1 of 2 files at r18, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-11-19 17:42 UTC, boryspoplawski reviewed
> Reviewed 14 of 14 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-19 17:57 UTC, yamahata approved these changes
> Reviewed 14 of 14 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-19 18:25 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r19, 14 of 14 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1949)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-19 18:44 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (`clock_gettime01` failed, cannot trigger locally, will need to investigate further)

2020-11-19 18:54 UTC, boryspoplawski commented
Added an issue to track flacky `clock_gettime01`: #1984

2020-11-19 19:57 UTC, merged