[Pal/{Linux,Linux-SGX}] Refactor "device" PAL handles
oscarlab/graphene pull request #1951
Opened 2020-11-09 09:28 UTC by dimakuv

## Description of the changes 

This PR refactors the source code of `pal_type_device` PAL handle (currently used only for `/dev/tty` STDIN/STDOUT streams). As a side effect, it also slightly refactors the corresponding code in LibOS.

## How to test this PR? 

All tests must pass. Only refactoring, no change in logic.

2020-11-12 02:41 UTC, mkow requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 157 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuAeSNCy2ACTXCFjHa:-MLuAeSO-zQMnWndhG8o:b-44qk6q) ([raw file](https://github.com/oscarlab/graphene/blob/3014a0dd1c46f0ea4f64a5f405382c6802c2f2af/LibOS/shim/src/bookkeep/shim_handle.c#L157)):*
> ```C
>                     return -ENOMEM;
> 
>                 if ((ret = init_tty_handle(hdl, fd)) < 0) {
> ```

Wait, what was that? :O Was this `fd` silently passed as bool, taking advantage of the fact that only fd 0 is not writable? What a "nice" trick...
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 172 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuCQuHAyWR-tS_IRvn:-MLuCQuHAyWR-tS_IRvo:b-8fsrue) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/LibOS/shim/src/bookkeep/shim_handle.c#L172)):*
> ```C
>     }
> 
>     /* initialize stderr as dup of stdout */
> ```

`dup` -> `duplicate`
___
*[Pal/src/host/Linux/db_devices.c, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFGguANc4lcPXkxqT:-MLuFGguANc4lcPXkxqU:bxcb106) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L59)):*
> ```C
> 
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

weird error choice, why this one? the name sounds weird comparing to this case
not just INVAL?
___
*[Pal/src/host/Linux/db_devices.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFbxK6a5Tyfh9LFg9:-MLuFbxK6a5Tyfh9LFgA:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L73)):*
> ```C
> 
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux/db_devices.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFnxi29vHIBEBpNRl:-MLuFnxi29vHIBEBpNRm:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L84)):*
> ```C
> static int dev_close(PAL_HANDLE handle) {
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux/db_devices.c, line 97 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFydD7Kmqk91uT3fJ:-MLuFydD7Kmqk91uT3fK:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L97)):*
> ```C
> static int dev_flush(PAL_HANDLE handle) {
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux/db_devices.c, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuG6Al5HawfYpSYYhm:-MLuG6Al5HawfYpSYYhn:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L111)):*
> ```C
> 
>     if (strcmp(type, URI_TYPE_DEV))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux/db_devices.c, line 127 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuGp3H4IbTgg0HeFta:-MLuGp3I6Qr12Hn2IMty:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L127)):*
> ```C
> static int dev_attrquerybyhdl(PAL_HANDLE handle, PAL_STREAM_ATTR* attr) {
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuHSWL3BsYlfJ6mIAq:-MLuHSWL3BsYlfJ6mIAr:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L60)):*
> ```C
> 
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuHboY1sK3V5AY3Lw-:-MLuHboY1sK3V5AY3Lw0:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L74)):*
> ```C
> 
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 85 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuHixvAqqIWkdj3tUI:-MLuHixvAqqIWkdj3tUJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L85)):*
> ```C
> static int dev_close(PAL_HANDLE handle) {
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuIZaS1yA0BXYn6PkJ:-MLuIZaS1yA0BXYn6PkK:b5g83tm) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L91)):*
> ```
> handle->dev.fd = PAL_IDX_POISON;
> ```

You should do this also on close() failure. Citing man:

> Retrying the close() after a failure return is the wrong thing to do, since this may cause a reused file descriptor from another thread to be closed. This can occur because the Linux kernel always releases the file descriptor early in the close operation, freeing it for reuse; the steps that may return an error, such as flushing data to the filesystem or device, occur only later in the close operation.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 98 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuJgmpCMHF0_bmljNo:-MLuJgmpCMHF0_bmljNp:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L98)):*
> ```C
> static int dev_flush(PAL_HANDLE handle) {
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuJpoI-qzagq98jOE3:-MLuJpoI-qzagq98jOE4:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L128)):*
> ```C
> static int dev_attrquerybyhdl(PAL_HANDLE handle, PAL_STREAM_ATTR* attr) {
>     if (!IS_HANDLE_TYPE(handle, dev))
>         return -PAL_ERROR_NOTCONNECTION;
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-11-12 09:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: 9 of 12 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 157 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuAeSNCy2ACTXCFjHa:-MLvc5Yn5R4pcDH7uggc:b-oacfsz) ([raw file](https://github.com/oscarlab/graphene/blob/3014a0dd1c46f0ea4f64a5f405382c6802c2f2af/LibOS/shim/src/bookkeep/shim_handle.c#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, what was that? :O Was this `fd` silently passed as bool, taking advantage of the fact that only fd 0 is not writable? What a "nice" trick...
</blockquote></details>

Yes, exactly. I hope you also enjoyed the 5 (!!!) levels of abstraction in PAL `.open -> dev_open -> g_term_ops.open -> term_open -> standard_term_open` just to do `hdl->dev.fd = 0 /* stdin */`.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 168 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLvcrmXBhwH0Zt8kwfb:-MLvcrmXBhwH0Zt8kwfc:bwaawr7) ([raw file](https://github.com/oscarlab/graphene/blob/3014a0dd1c46f0ea4f64a5f405382c6802c2f2af/LibOS/shim/src/bookkeep/shim_handle.c#L168)):*
> ```C
>             put_handle(hdl);
>             if (fd != 1)
>                 hdl = NULL;
> ```

And if you love nice tricks, did you pay attention to this beauty? :) The logic is basically "for STDERR (fd=2), reuse the STDOUT handle (leaving hdl from the previous iteration which was fd=1)". But oh boy is this subtle.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 172 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuCQuHAyWR-tS_IRvn:-MLvdTyO3b3s3d3Me-Ar:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/LibOS/shim/src/bookkeep/shim_handle.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`dup` -> `duplicate`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFGguANc4lcPXkxqT:-MLvfRXH3P5Ec-8-NKJO:bpz6o83) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

weird error choice, why this one? the name sounds weird comparing to this case
not just INVAL?
</blockquote></details>

Done. I stole this from `db_pipes.c` but for tty I guess this `ENOTCONN` doesn't make sense.
___
*[Pal/src/host/Linux/db_devices.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFbxK6a5Tyfh9LFg9:-MLvfaYAEVd5IKbD_t_a:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFnxi29vHIBEBpNRl:-MLvfbISEcg56VPxUhJl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 97 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuFydD7Kmqk91uT3fJ:-MLvfcHVDCFmtGEwAQDP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuG6Al5HawfYpSYYhm:-MLvfd-5AgQOwMPEHHlo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 127 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuGp3H4IbTgg0HeFta:-MLvfdYH5q8qDZ7B5EJ3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux/db_devices.c#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuHSWL3BsYlfJ6mIAq:-MLvg0AtD-TW98OjSY79:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuHboY1sK3V5AY3Lw-:-MLvg0at0fiKgryxNaIo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 85 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuHixvAqqIWkdj3tUI:-MLvg5i06MtAMQdTICR7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuIZaS1yA0BXYn6PkJ:-MLvhYd5-qFIzMz7FnYc:bct9z5b) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> handle->dev.fd = PAL_IDX_POISON;
> ```

You should do this also on close() failure. Citing man:

> Retrying the close() after a failure return is the wrong thing to do, since this may cause a reused file descriptor from another thread to be closed. This can occur because the Linux kernel always releases the file descriptor early in the close operation, freeing it for reuse; the steps that may return an error, such as flushing data to the filesystem or device, occur only later in the close operation.
</blockquote></details>

Done. Good catch.

Surprisingly, all other types of PAL handles (files, pipes, sockets, ...) have correct semantics in this regard. I believe this is accidental because they don't even check for host-level `close()` return value :)
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 98 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuJgmpCMHF0_bmljNo:-MLvg7Zl2Fxn_RNxuSUE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/841a51ce6901db588a38a1a74b19613138d5a990/Pal/src/host/Linux-SGX/db_devices.c#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLuJpoI-qzagq98jOE3:-MLvgG09-LHJfG8T96zR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8 [...]

2020-11-12 10:17 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`sigsuspend01` LTP test failed, known issue)

2020-11-12 13:36 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 168 at r1](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLvcrmXBhwH0Zt8kwfb:-MLwdTga1xBDlev9IR6Z:b-r3tvm6) ([raw file](https://github.com/oscarlab/graphene/blob/3014a0dd1c46f0ea4f64a5f405382c6802c2f2af/LibOS/shim/src/bookkeep/shim_handle.c#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

And if you love nice tricks, did you pay attention to this beauty? :) The logic is basically "for STDERR (fd=2), reuse the STDOUT handle (leaving hdl from the previous iteration which was fd=1)". But oh boy is this subtle.
</blockquote></details>

Yeah, I guessed that this is what happens here, but got lost in the logic here and didn't really analyzed it. Too obfuscated :)


<!-- Sent from Reviewable.io -->

2020-11-13 00:57 UTC, boryspoplawski requested changes
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLyxchN7fbmlYR2WeG8:-MLyxchN7fbmlYR2WeG9:b-ji9joz) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/LibOS/shim/src/bookkeep/shim_handle.c#L38)):*
> ```C
> 
>     hdl->type  = TYPE_DEV;
>     hdl->flags = (write ? O_WRONLY : O_RDONLY) | O_APPEND;
> ```

Uhm, what is `O_RDONLY | O_APPEND` supposed to mean?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 145 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLyyxSKA8gEM_OJ9Nre:-MLyyxSKA8gEM_OJ9Nrf:b2czb4k) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/LibOS/shim/src/bookkeep/shim_handle.c#L145)):*
> ```C
>     if (!HANDLE_ALLOCATED(handle_map->map[0])) {
>         struct shim_handle* stdin_hdl = get_new_handle();
>         if (!stdin_hdl)
> ```

We need to unlock `handle_map->lock` here and on every return from this function.
___
*[Pal/src/host/Linux/db_devices.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz1lE490ZzjKeiQ-bX:-MLz1lE490ZzjKeiQ-bY:b4fe319) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L40)):*
> ```C
> 
>     if (access & PAL_ACCESS_WRONLY) {
>         HANDLE_HDR(hdl)->flags |= WFD(0);
> ```

Shouldn't this be `|= WFD(1)` ?
___
*[Pal/src/host/Linux/db_devices.c, line 55 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz1KLO-cCd86cXu6uG:-MLz1KLO-cCd86cXu6uH:b-9xmwua) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L55)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     if (!(HANDLE_HDR(handle)->flags & RFD(0)))
> ```

Shouldn't this be `& RFD(handle->dev.fd)`?
___
*[Pal/src/host/Linux/db_devices.c, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz229h1mmaxiyxcFYs:-MLz229h1mmaxiyxcFYt:bhr58oa) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L57)):*
> ```C
>     if (!(HANDLE_HDR(handle)->flags & RFD(0)))
>         return -PAL_ERROR_DENIED;
> ```

Shouldn't we check for `PAL_IDX_POISON` here as well (`dev_close` could set it)?
___
*[Pal/src/host/Linux/db_devices.c, line 66 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz1d5B5P7anv6yKc0s:-MLz1d5B5P7anv6yKc0t:b-r4zf4u) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L66)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     if (!(HANDLE_HDR(handle)->flags & WFD(0)))
> ```

ditto (`& WFD(handle->dev.fd)`)
___
*[Pal/src/host/Linux/db_devices.c, line 68 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz2GEi3ZoDnjW-TuxW:-MLz2GEi3ZoDnjW-TuxX:b5zm1qi) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L68)):*
> ```C
>     if (!(HANDLE_HDR(handle)->flags & WFD(0)))
>         return -PAL_ERROR_DENIED;
> ```

ditto (`PAL_IDX_POISON`)
___
*[Pal/src/host/Linux/db_devices.c, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz2xpfE1jewIAAilYO:-MLz2xpfE1jewIAAilYP:bqeypst) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L117)):*
> ```C
> 
>     attr->handle_type  = pal_type_dev;
>     attr->readable     = HANDLE_HDR(handle)->flags & RFD(0);
> ```

ditto (`& RFD(handle->dev.fd)`)
___
*[Pal/src/host/Linux/db_devices.c, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz32z1BcshuFKM0mt9:-MLz32z1BcshuFKM0mtA:b-r4zf4u) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L118)):*
> ```C
>     attr->handle_type  = pal_type_dev;
>     attr->readable     = HANDLE_HDR(handle)->flags & RFD(0);
>     attr->writable     = HANDLE_HDR(handle)->flags & WFD(0);
> ```

ditto (`& WFD(handle->dev.fd)`)
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz4aT801ceYPcAFxaR:-MLz4aT801ceYPcAFxaS:b-90uu0f) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L1)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

All comments from `Linux/db_devices.c` apply also in this file as this is mostly copy-paste.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz4uoi54EqSIY4_1fE:-MLz4uojE6GWg5-ePQjS:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L41)):*
> ```C
> 
>     if (access & PAL_ACCESS_WRONLY) {
>         HANDLE_HDR(hdl)->flags |= WFD(0);
> ```

here
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 56 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz4yrjC585KoZqdytP:-MLz4yrjC585KoZqdytQ:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L56)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     if (!(HANDLE_HDR(handle)->flags & RFD(0)))
> ```

here
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz596EEAMEs7QLKywp:-MLz596EEAMEs7QLKywq:b71ttw2) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L58)):*
> ```C
>     if (!(HANDLE_HDR(handle)->flags & RFD(0)))
>         return -PAL_ERROR_DENIED;
> ```

here (`PAL_IDX_POISON` check)
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 67 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz54291StyO0wKZUPR:-MLz54291StyO0wKZUPS:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L67)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     if (!(HANDLE_HDR(handle)->flags & WFD(0)))
> ```

here
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz5DE_0W4HFrlWpE4h:-MLz5DE_0W4HFrlWpE4i:b71ttw2) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L69)):*
> ```C
>     if (!(HANDLE_HDR(handle)->flags & WFD(0)))
>         return -PAL_ERROR_DENIED;
> ```

here (`PAL_IDX_POISON` check)
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz5NHa2Nf6xx14pzgP:-MLz5NHa2Nf6xx14pzgQ:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L118)):*
> ```C
> 
>     attr->handle_type  = pal_type_dev;
>     attr->readable     = HANDLE_HDR(handle)->flags & RFD(0);
> ```

here
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 119 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz5O2E92XWrA4ZO12G:-MLz5O2E92XWrA4ZO12H:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L119)):*
> ```C
>     attr->handle_type  = pal_type_dev;
>     attr->readable     = HANDLE_HDR(handle)->flags & RFD(0);
>     attr->writable     = HANDLE_HDR(handle)->flags & WFD(0);
> ```

here


<!-- Sent from Reviewable.io -->

2020-11-13 08:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: 9 of 12 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLyxchN7fbmlYR2WeG8:-MM-_4RF0QBTrd8ERtVt:be21eeu) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/LibOS/shim/src/bookkeep/shim_handle.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Uhm, what is `O_RDONLY | O_APPEND` supposed to mean?
</blockquote></details>

Done. Yeah, good catch.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 145 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLyyxSKA8gEM_OJ9Nre:-MM-_feiARWLJ4M5Ubvh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/LibOS/shim/src/bookkeep/shim_handle.c#L145)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need to unlock `handle_map->lock` here and on every return from this function.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz1lE490ZzjKeiQ-bX:-MM-_rii0sIlZRuV31KJ:b20okw) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `|= WFD(1)` ?
</blockquote></details>

No. `WFD(0)` means "host-level FD at index 0 is writable". Recall that each PAL handle (`struct pal_handle` == `PAL_HANDLE`) may technically have up to 3 (`MAX_FDS`) host-level actual FDs. So if say a pipe has two FDs, then we set its flags to `RFD(0) | WFD(1)` -- meaning "host-level FD at index 0 is only-read and host-level FD at index 1 is only-write". But for device, we only have one host-level FD, so there is only index 0.

This `MAX_FDS` mapping is an interesting concept but is probably "too smart" -- I think we only have **one** use case for it, in `pipeprv` where one PAL handle hides beneath it two FDs (two ends of the host-level pipe). Maybe we should just remove it (or at least rename macros like `WFD`/`RFD`).
___
*[Pal/src/host/Linux/db_devices.c, line 55 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz1KLO-cCd86cXu6uG:-MM-b16CDg0oCf7sd-iI:bwasf62) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `& RFD(handle->dev.fd)`?
</blockquote></details>

No. I see now where the confusion stems from. `RFD`/`WFD` are really terrible names :)

Here is the snippet from `pal_host.h` that helps in understanding RFD/WFD:
```
#define RFD(n)   (1 << (MAX_FDS * 0 + (n)))
#define WFD(n)   (1 << (MAX_FDS * 1 + (n)))
#define ERROR(n) (1 << (MAX_FDS * 2 + (n)))
```

So the RFD argument is **not**  the host-level FD, but an offset into "array of my FDs".
___
*[Pal/src/host/Linux/db_devices.c, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz229h1mmaxiyxcFYs:-MM-bmzZ7A65QsVSNpAo:bju78iu) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we check for `PAL_IDX_POISON` here as well (`dev_close` could set it)?
</blockquote></details>

Done. Oops, missed to copy-paste this case from the old code.
___
*[Pal/src/host/Linux/db_devices.c, line 66 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz1d5B5P7anv6yKc0s:-MM-btV32LryzSvb1PRo:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`& WFD(handle->dev.fd)`)
</blockquote></details>

ditto
___
*[Pal/src/host/Linux/db_devices.c, line 68 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz2GEi3ZoDnjW-TuxW:-MM-c6I0AI1F5oa8gGkn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L68)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`PAL_IDX_POISON`)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz2xpfE1jewIAAilYO:-MM-c86JBinxbojQLos1:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`& RFD(handle->dev.fd)`)
</blockquote></details>

ditto
___
*[Pal/src/host/Linux/db_devices.c, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz32z1BcshuFKM0mt9:-MM-cA83E4_-L8lB6khg:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`& WFD(handle->dev.fd)`)
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz4aT801ceYPcAFxaR:-MM-cC8PC4BiqPGKQXYg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All comments from `Linux/db_devices.c` apply also in this file as this is mostly copy-paste.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz4uoi54EqSIY4_1fE:-MM-cDRS9bFCNlQob8FJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

here
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 56 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz4yrjC585KoZqdytP:-MM-cENO-_bYvQ1IU1iC:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L56)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

here
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz596EEAMEs7QLKywp:-MM-cQbG0rLypvlGLD2z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

here (`PAL_IDX_POISON` check)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 67 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz54291StyO0wKZUPR:-MM-cR3r7Bi4unEv6HIZ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux-SGX/db_devices.c#L67)):*
<details><summary><i>Previousl [...]

2020-11-13 10:42 UTC, dimakuv commented
Jenkins, retest this please (now Jenkins is back again)

2020-11-13 12:59 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux/db_devices.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/1951#-MLz1lE490ZzjKeiQ-bX:-MM0faQB7JeW_T3segmb:byew7re) ([raw file](https://github.com/oscarlab/graphene/blob/238fc7216d656337c399267247dc4928506801a2/Pal/src/host/Linux/db_devices.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No. `WFD(0)` means "host-level FD at index 0 is writable". Recall that each PAL handle (`struct pal_handle` == `PAL_HANDLE`) may technically have up to 3 (`MAX_FDS`) host-level actual FDs. So if say a pipe has two FDs, then we set its flags to `RFD(0) | WFD(1)` -- meaning "host-level FD at index 0 is only-read and host-level FD at index 1 is only-write". But for device, we only have one host-level FD, so there is only index 0.

This `MAX_FDS` mapping is an interesting concept but is probably "too smart" -- I think we only have **one** use case for it, in `pipeprv` where one PAL handle hides beneath it two FDs (two ends of the host-level pipe). Maybe we should just remove it (or at least rename macros like `WFD`/`RFD`).
</blockquote></details>

Oh, I thought it should be fd, not fd index.


<!-- Sent from Reviewable.io -->

2020-11-13 15:51 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-16 13:04 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-16 14:06 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1951)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-16 14:47 UTC, woju commented
Jenkins, test this please

2020-11-16 15:19 UTC, woju commented
Jenkins, test this please

2020-11-16 18:00 UTC, woju commented
Jenkins, test this please

2020-11-16 18:53 UTC, merged