[LibOS] Gracefully exit with message on duplicate mounts in manifest
oscarlab/graphene pull request #1956
Opened 2020-11-11 12:48 UTC by dimakuv

## Description of the changes 

Sometimes users may try to add `/dev` or root (`/`) mounts to the manifest file, but these paths are already automatically mounted by Graphene on startup. Previously, Graphene failed on assert in such cases, now it prints a meaningful error message.

## How to test this PR? 

Didn't want to introduce a negative test case for this. But try manually by simply adding these lines to `LibOS/shim/test/regression/manifest.template`:
```
fs.mount.dev.type = chroot
fs.mount.dev.path = /dev
fs.mount.dev.uri = file:/dev
```

Without this PR, Graphene mysteriously fails on assert (rebuild and run any LibOS test). With this PR, Graphene says something reasonable:
```
[P15650:T1:spinlock] Mount /dev already exists, verify that there are no duplicate mounts in manifest
[P15650:T1:spinlock] (note that /proc and /dev are automatically mounted in Graphene).
[P15650:T1:spinlock] Mounting file:/dev on /dev (type=chroot) failed (17)
```

2020-11-11 15:42 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-11-11 17:09 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLsGhWV0mfbGyOgPYPc:-MLsGhWW2EeAdg9ld6Gx:bcjea4c) (no related file):*
Hmm, I don't think this change works in all cases. I modified `manifest.template` to have `fs.mount.graphene_lib.path = /` and go the following log:

```
[P24501:spinlock] Mounting root as chroot filesystem: from file:. to /
[P24501:spinlock] Mounting special proc filesystem: /proc
[P24501:spinlock] Mounting special dev filesystem: /dev
[P24501:spinlock] Mounting terminal device /dev/tty under /dev
[P24501:spinlock] Creating pipe: pipe.srv:3460718517
[P24501:spinlock] Adding port (handle 0x7f055d7e1850) for process 24501 (type 0001)
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:../../../../Runtime to /
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:/usr//lib/x86_64-linux-gnu to /usr//lib/x86_64-linux-gnu
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:/bin to /bin
[P24501:T1:spinlock] shim_init() in init_important_handles (-2)
```

Seems that double mount on `/` still works, but some unrelated code fails later.

---


<!-- Sent from Reviewable.io -->

2020-11-11 18:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLsGhWV0mfbGyOgPYPc:-MLsTVG55cwLiny2P6KO:b-swadh1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I don't think this change works in all cases. I modified `manifest.template` to have `fs.mount.graphene_lib.path = /` and go the following log:

```
[P24501:spinlock] Mounting root as chroot filesystem: from file:. to /
[P24501:spinlock] Mounting special proc filesystem: /proc
[P24501:spinlock] Mounting special dev filesystem: /dev
[P24501:spinlock] Mounting terminal device /dev/tty under /dev
[P24501:spinlock] Creating pipe: pipe.srv:3460718517
[P24501:spinlock] Adding port (handle 0x7f055d7e1850) for process 24501 (type 0001)
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:../../../../Runtime to /
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:/usr//lib/x86_64-linux-gnu to /usr//lib/x86_64-linux-gnu
[P24501:T1:spinlock] Mounting as chroot filesystem: from file:/bin to /bin
[P24501:T1:spinlock] shim_init() in init_important_handles (-2)
```

Seems that double mount on `/` still works, but some unrelated code fails later.
</blockquote></details>

Hm, true. This is the special case of the "root" mount (it is initialized differently than the others). I will test more and add handling for this special case.

---


<!-- Sent from Reviewable.io -->

2020-11-12 08:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLsGhWV0mfbGyOgPYPc:-MLvbMbk84qyileDSK9C:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, true. This is the special case of the "root" mount (it is initialized differently than the others). I will test more and add handling for this special case.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-11-12 08:53 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`test_110_basic_bootstrapping_cxx` LibOS test timed out, what is that?)

2020-11-12 13:28 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_fs.c, line 166 at r2](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwcXkM8bTswdwiU3F4:-MLwcXkM8bTswdwiU3F5:b-yonlu8) ([raw file](https://github.com/oscarlab/graphene/blob/0d818309c111a46841e7f7cd004e92e0e0c6e99e/LibOS/shim/src/fs/shim_fs.c#L166)):*
> ```C
>     if (!strcmp(p, "/")) {
>         debug("Root mount / already exists, verify that there are no duplicate mounts in manifest\n"
>               "(note that root / is automatically mounted in Graphene).\n");
> ```

This is a fatal error, but is currently only printed in debug builds. Could you always print it?
___
*[LibOS/shim/src/fs/shim_fs.c, line 166 at r2](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwcdqsCf5Rl7LwDvGF:-MLwcdqsCf5Rl7LwDvGG:b-26n7cu) ([raw file](https://github.com/oscarlab/graphene/blob/0d818309c111a46841e7f7cd004e92e0e0c6e99e/LibOS/shim/src/fs/shim_fs.c#L166)):*
> ```C
>     if (!strcmp(p, "/")) {
>         debug("Root mount / already exists, verify that there are no duplicate mounts in manifest\n"
>               "(note that root / is automatically mounted in Graphene).\n");
> ```

I'd mention here that the root mount can be changed using `fs.root` entries (which are currently undocumented, btw).


<!-- Sent from Reviewable.io -->

2020-11-12 14:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/shim_fs.c, line 166 at r2](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwcXkM8bTswdwiU3F4:-MLwqIz_8zTpYyw891LW:b-z9utf1) ([raw file](https://github.com/oscarlab/graphene/blob/0d818309c111a46841e7f7cd004e92e0e0c6e99e/LibOS/shim/src/fs/shim_fs.c#L166)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a fatal error, but is currently only printed in debug builds. Could you always print it?
</blockquote></details>

But we don't have such a capability in LibOS... (Yeah, we need to rewrite the debug-log interface.)
___
*[LibOS/shim/src/fs/shim_fs.c, line 166 at r2](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwcdqsCf5Rl7LwDvGF:-MLwrrcI0p8unwLTD_kA:b-nl53u7) ([raw file](https://github.com/oscarlab/graphene/blob/0d818309c111a46841e7f7cd004e92e0e0c6e99e/LibOS/shim/src/fs/shim_fs.c#L166)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd mention here that the root mount can be changed using `fs.root` entries (which are currently undocumented, btw).
</blockquote></details>

Done.

Also added documentation for `fs.root` and `fs.start_dir` that was missing (in a separate commit).


<!-- Sent from Reviewable.io -->

2020-11-12 14:55 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 195 at r3](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwwi7I86UwW-jb3JhE:-MLwwi7I86UwW-jb3JhF:brj6zqe) ([raw file](https://github.com/oscarlab/graphene/blob/76f3f70e5d4c1a466cff3b2c2b3087674d096033/Documentation/manifest-syntax.rst#L195)):*
> ```reStructuredText
>     fs.root.[identifier].type = [chroot|...]
>     fs.root.[identifier].path = [PATH]
>     fs.root.[identifier].uri  = [URI]
> ```

This will be in a silent conflict with #1892, which we are going to merge today. Please remember to fix it during rebase.
___
*[Documentation/manifest-syntax.rst, line 219 at r3](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwwq9C5nnR5jmzZk1v:-MLwwq9C5nnR5jmzZk1w:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/76f3f70e5d4c1a466cff3b2c2b3087674d096033/Documentation/manifest-syntax.rst#L219)):*
> ```reStructuredText
> ::
> 
>     fs.start_dir = [URI]
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-11-12 16:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 195 at r3](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwwi7I86UwW-jb3JhE:-MLxIefA8tla4jQtuCCy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76f3f70e5d4c1a466cff3b2c2b3087674d096033/Documentation/manifest-syntax.rst#L195)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This will be in a silent conflict with #1892, which we are going to merge today. Please remember to fix it during rebase.
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 219 at r3](https://reviewable.io/reviews/oscarlab/graphene/1956#-MLwwq9C5nnR5jmzZk1v:-MLxIj432R9FCA4Vq_zr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76f3f70e5d4c1a466cff3b2c2b3087674d096033/Documentation/manifest-syntax.rst#L219)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 16:42 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-12 16:47 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-16 19:05 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-11-16 19:29 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1956)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-16 20:42 UTC, mkow commented
Jenkins, retest Jenkins-SGX-18.04 please (there was some Jenkins maintenance work in the meantime)

2020-11-16 20:42 UTC, mkow commented
Jenkins, retest Jenkins-SGX-18.04-apps please (there was some Jenkins maintenance work in the meantime)

2020-11-16 21:10 UTC, merged