[Pal/{Linux,Linux-SGX}] Allow communication with host devices
oscarlab/graphene pull request #1959
Opened 2020-11-12 12:34 UTC by dimakuv

## Description of the changes 

Previously, Graphene supported only `/dev/tty` (stdin/stdout terminal) device. This PR introduces support for other, arbitrary host devices. The devices must be explicitly allowed in the manifest via a mount point like this:
```
      fs.mount.devkmsg.type = chroot
      fs.mount.devkmsg.path = /dev/kmsg
      fs.mount.devkmsg.uri  = dev:/dev/kmsg
```

Currently only `open/read/write/close/fstat` are supported. Support for IOCTLs and mmaps will be introduced in future PRs.

Needs to be rebased on top of #1951.

## How to test this PR? 

A simple test that opens `/dev/kmsg` and reads from it is added to LibOS regression tests.

2020-11-12 13:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: 0 of 16 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/test/regression/manifest.template, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/1959#-MLwYAKa-fHwYcZ0_KiP:-MLwYAKa-fHwYcZ0_KiQ:b-dy02on) ([raw file](https://github.com/oscarlab/graphene/blob/2ef630d7d718b48fee1ca50f5abad03ae33a4245/LibOS/shim/test/regression/manifest.template#L25)):*
> ```
> fs.mount.devkmsg.type = chroot
> fs.mount.devkmsg.path = /dev/kmsg
> fs.mount.devkmsg.uri = dev:/dev/kmsg
> ```

Jenkins fails on loading this manifest file because we don't propagate `/dev/kmsg` to inside the Docker container. Should we add this (something like `--device=/dev/kmsg:/dev/kmsg` in docker-run args)?

I want a really simple example of an open/read/close on a device file, and `/dev/kmsg` is a good fit. The only other device that we have visible in Jenkins is `/dev/isgx` (or in the future `/dev/sgx/enclave`), but it can't be read from.


<!-- Sent from Reviewable.io -->

2020-11-20 10:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: 0 of 11 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[LibOS/shim/test/regression/manifest.template, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/1959#-MLwYAKa-fHwYcZ0_KiP:-MM_5S2L2FQudTtviidw:b-vhzsni) ([raw file](https://github.com/oscarlab/graphene/blob/2ef630d7d718b48fee1ca50f5abad03ae33a4245/LibOS/shim/test/regression/manifest.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenkins fails on loading this manifest file because we don't propagate `/dev/kmsg` to inside the Docker container. Should we add this (something like `--device=/dev/kmsg:/dev/kmsg` in docker-run args)?

I want a really simple example of an open/read/close on a device file, and `/dev/kmsg` is a good fit. The only other device that we have visible in Jenkins is `/dev/isgx` (or in the future `/dev/sgx/enclave`), but it can't be read from.
</blockquote></details>

Done. Wojtek says it's fine to propagate `/dev/kmsg` so I added it to Docker config.


<!-- Sent from Reviewable.io -->

2020-11-23 12:13 UTC, dimakuv commented
Jenkins, test this please (Wojtek enabled `/dev/kmsg` on Jenkins workers)

2020-11-24 14:32 UTC, dimakuv commented
Jenkins, test this please (still don't understand why `/dev/kmsg` is not available)

2020-11-24 19:26 UTC, woju commented
Jenkins, retest this please (intentionally on all nodes)

2020-11-30 14:34 UTC, boryspoplawski requested changes
> Reviewed 1 of 16 files at r1, 9 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 737 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOXTp23rcGoChGaI01:-MNOXTp23rcGoChGaI02:bcps0mw) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/src/fs/chroot/fs.c#L737)):*
> ```C
> 
>         case SEEK_END:
>             /* TODO: devices may report size == 0 during fstat(), then this emulation breaks */
> ```

Why this comment is here? Doesn't it apply to all cases?
___
*[LibOS/shim/test/regression/device.c, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOY-o3-t94a4nRV7TC:-MNOY-o3-t94a4nRV7TD:b-v4aodx) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/test/regression/device.c#L4)):*
> ```C
> #include <errno.h>
> #include <fcntl.h>
> #include <stdint.h>
> ```

nitpick: is this include needed?
___
*[LibOS/shim/test/regression/device.c, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOZIpj63SeNd5pMuPl:-MNOZIpj63SeNd5pMuPm:bbmgjwy) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/test/regression/device.c#L23)):*
> ```C
>         errx(1, "/dev/kmsg lseek(SEEK_CUR) didn't return -EINVAL (returned: %ld, errno=%d)",
>              offset, errno);
>     }
> ```

Could you also add a check:
```
offset = lseek(devfd, 1, SEEK_CUR);
if (offset != -1 || errno != ESPIPE) {
    err;
```
inside `if 0` for now?
___
*[LibOS/shim/test/regression/device.c, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOYZq1EOdOfN4VN-pk:-MNOYZq2EbWx-IQ3XcCR:bsstkog) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/test/regression/device.c#L27)):*
> ```C
> 
>     offset = lseek(devfd, /*offset=*/0, SEEK_SET);
>     if (offset < 0)
> ```

Isn't `offset > 0` also an error here?
___
*[Pal/src/host/Linux/db_devices.c, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOVkG79XLBNpzWVpze:-MNOVkG79XLBNpzWVpzf:b-wcxsl) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/db_devices.c#L117)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     /* Currently we just assign `0` or `1` without duplicating, so close is a no-op. */
> ```

This is no longer true (in some cases it shouldn't be a noop).
___
*[Pal/src/host/Linux/db_devices.c, line 127 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOW-KYELjbWYuz9Xyj:-MNOW-KYELjbWYuz9Xyk:b-6i25we) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/db_devices.c#L127)):*
> ```C
> 
>     if (handle->dev.fd != PAL_IDX_POISON) {
>         int ret = INLINE_SYSCALL(fsync, 1, handle->dev.fd);
> ```

We should not call this on `0` and `1` as they might be e.g. a pipe, on which `fsync` will fail.
___
*[Pal/src/host/Linux/pal_host.h, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOXFDV1Dj-8zAjs-MI:-MNOXFDW3bVGcZR6pZfO:bq3v69v) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/pal_host.h#L100)):*
> ```objc
>         struct {
>             PAL_IDX fd;
>             PAL_BOL nonblocking;
> ```

Could we change that to just `bool`?
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOX5tCBILKEvnY_jFf:-MNOX5tCBILKEvnY_jFg:bm441b2) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux-SGX/db_devices.c#L118)):*
> ```C
>         return -PAL_ERROR_INVAL;
> 
>     /* Currently we just assign `0` or `1` without duplicating, so close is a no-op. */
> ```

ditto (close)
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 128 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOX7G24hvMNOcFfqae:-MNOX7G34ROCS6Rh58F_:bnn9qr9) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux-SGX/db_devices.c#L128)):*
> ```C
> 
>     if (handle->dev.fd != PAL_IDX_POISON) {
>         int ret = ocall_fsync(handle->dev.fd);
> ```

ditto (fsync)
___
*[Pal/src/host/Linux-SGX/pal_host.h, line 112 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOTHL69G2qy_9L8e-9:-MNOTHL69G2qy_9L8e-A:blbkl0y) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux-SGX/pal_host.h#L112)):*
> ```objc
>         struct {
>             PAL_IDX fd;
>             PAL_BOL nonblocking;
> ```

ditto (bool)


<!-- Sent from Reviewable.io -->

2020-12-01 11:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: 8 of 10 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 737 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOXTp23rcGoChGaI01:-MNSvk5_7dTEXsf8XHl_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/src/fs/chroot/fs.c#L737)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this comment is here? Doesn't it apply to all cases?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/device.c, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOY-o3-t94a4nRV7TC:-MNSvreYBhoIrOCnQIKP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/test/regression/device.c#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

nitpick: is this include needed?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/device.c, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOZIpj63SeNd5pMuPl:-MNSwXWnDITm2TOOU9uR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/test/regression/device.c#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you also add a check:
```
offset = lseek(devfd, 1, SEEK_CUR);
if (offset != -1 || errno != ESPIPE) {
    err;
```
inside `if 0` for now?

</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/device.c, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOYZq1EOdOfN4VN-pk:-MNSwn7M3bZyut5sj5O7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/LibOS/shim/test/regression/device.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't `offset > 0` also an error here?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOVkG79XLBNpzWVpze:-MNSxaSv-2RWm2AArPJk:b-8x0pim) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/db_devices.c#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is no longer true (in some cases it shouldn't be a noop).
</blockquote></details>

What do you mean? This is the latest code in the master branch, and the last commit that modifies these lines is yours: https://github.com/oscarlab/graphene/commit/b7f970d83f79a0d00d25782b287419e468b0f56c
___
*[Pal/src/host/Linux/db_devices.c, line 127 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOW-KYELjbWYuz9Xyj:-MNSxnDDBQL6Fp2CiPUh:b-usn070) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/db_devices.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should not call this on `0` and `1` as they might be e.g. a pipe, on which `fsync` will fail.
</blockquote></details>

Isn't it a problem of the user app code? This `dev_flush()` happens on `DkStreamFlush()` which is called only in `chroot_flush()` which is called in `fsync()` emulation. In other words, we end up here only if the application asked us to.
___
*[Pal/src/host/Linux/pal_host.h, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOXFDV1Dj-8zAjs-MI:-MNSyxIO7ApAk085u56I:b76vmha) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/pal_host.h#L100)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we change that to just `bool`?
</blockquote></details>

I'm not comfortable with this. Could we do it in another PR when we finally remove all these `PAL_` types in a uniform way?
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOX5tCBILKEvnY_jFf:-MNSxke8709vNfmlMVJq:b-8x0pim) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux-SGX/db_devices.c#L118)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (close)
</blockquote></details>

What do you mean? This is the latest code in the master branch, and the last commit that modifies these lines is yours: https://github.com/oscarlab/graphene/commit/b7f970d83f79a0d00d25782b287419e468b0f56c
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 128 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOX7G24hvMNOcFfqae:-MNSz4viDTlZIRLJPMHG:byelxlz) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux-SGX/db_devices.c#L128)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (fsync)
</blockquote></details>

ditto (app's fault)
___
*[Pal/src/host/Linux-SGX/pal_host.h, line 112 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOTHL69G2qy_9L8e-9:-MNSz7bs973fwKYho8Jt:bk90cv1) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux-SGX/pal_host.h#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (bool)
</blockquote></details>

ditto (not comfortable)


<!-- Sent from Reviewable.io -->

2020-12-01 11:33 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_devices.c, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOVkG79XLBNpzWVpze:-MNT260LEbGsY9enrfDP:b-cd9e99) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/db_devices.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? This is the latest code in the master branch, and the last commit that modifies these lines is yours: https://github.com/oscarlab/graphene/commit/b7f970d83f79a0d00d25782b287419e468b0f56c
</blockquote></details>

After this commit `handle->dev.fd` might be something else that `0` or `1` (magic tty) and such fd should be closed here.
___
*[Pal/src/host/Linux/pal_host.h, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOXFDV1Dj-8zAjs-MI:-MNT4-TkDlfmnVnA4f3K:b32w1t) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/pal_host.h#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm not comfortable with this. Could we do it in another PR when we finally remove all these `PAL_` types in a uniform way?
</blockquote></details>

Ok


<!-- Sent from Reviewable.io -->

2020-12-01 12:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: 8 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_devices.c, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOVkG79XLBNpzWVpze:-MNTC5Dj8kH8FkaupNTg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux/db_devices.c#L117)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

After this commit `handle->dev.fd` might be something else that `0` or `1` (magic tty) and such fd should be closed here.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNOX5tCBILKEvnY_jFf:-MNTC79526BbT0pOo9Gx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/11a21a55894d029eb100fbfb2f3b215d6a850f63/Pal/src/host/Linux-SGX/db_devices.c#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? This is the latest code in the master branch, and the last commit that modifies these lines is yours: https://github.com/oscarlab/graphene/commit/b7f970d83f79a0d00d25782b287419e468b0f56c
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-01 12:47 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_devices.c, line 121 at r4](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNTKgLq9VD1cFoA6nkR:-MNTKgLr1FMwOao7Z7Vm:b-bh5kgw) ([raw file](https://github.com/oscarlab/graphene/blob/6467720483fc6f5bd5d4a4dd042897cbe1c0c99c/Pal/src/host/Linux/db_devices.c#L121)):*
> ```C
>     if (handle->dev.fd != PAL_IDX_POISON && handle->dev.fd != 0 && handle->dev.fd != 1) {
>         ret = INLINE_SYSCALL(close, 1, handle->dev.fd);
>         handle->dev.fd = PAL_IDX_POISON;
> ```

We should always set `PAL_IDX_POISON`, even for `0` and `1`.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 122 at r4](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNTKs2K-Bsrde10qOvC:-MNTKs2K-Bsrde10qOvD:bpb4ifo) ([raw file](https://github.com/oscarlab/graphene/blob/6467720483fc6f5bd5d4a4dd042897cbe1c0c99c/Pal/src/host/Linux-SGX/db_devices.c#L122)):*
> ```C
>     if (handle->dev.fd != PAL_IDX_POISON && handle->dev.fd != 0 && handle->dev.fd != 1) {
>         ret = ocall_close(handle->dev.fd);
>         handle->dev.fd = PAL_IDX_POISON;
> ```

ditto (poison)


<!-- Sent from Reviewable.io -->

2020-12-01 12:50 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/device.c, line 42 at r4](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNTLUAk-qTd5bv6wS3c:-MNTLUAk-qTd5bv6wS3d:b-idozld) ([raw file](https://github.com/oscarlab/graphene/blob/6467720483fc6f5bd5d4a4dd042897cbe1c0c99c/LibOS/shim/test/regression/device.c#L42)):*
> ```C
>         err(1, "/dev/kmsg read");
> 
>     printf("First line of /dev/kmsg: %s", buf);
> ```

`buf` is not null terminated here.


<!-- Sent from Reviewable.io -->

2020-12-01 13:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: 7 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/device.c, line 42 at r4](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNTLUAk-qTd5bv6wS3c:-MNTRoeO5cQNQfrcO71P:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6467720483fc6f5bd5d4a4dd042897cbe1c0c99c/LibOS/shim/test/regression/device.c#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`buf` is not null terminated here.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_devices.c, line 121 at r4](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNTKgLq9VD1cFoA6nkR:-MNTSZhe6oHVVJTTWgY8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6467720483fc6f5bd5d4a4dd042897cbe1c0c99c/Pal/src/host/Linux/db_devices.c#L121)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should always set `PAL_IDX_POISON`, even for `0` and `1`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_devices.c, line 122 at r4](https://reviewable.io/reviews/oscarlab/graphene/1959#-MNTKs2K-Bsrde10qOvC:-MNTS_Xa7dxta03FVoh5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6467720483fc6f5bd5d4a4dd042897cbe1c0c99c/Pal/src/host/Linux-SGX/db_devices.c#L122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (poison)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-01 13:22 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-01 15:32 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 16 files at r1, 5 of 13 files at r2, 1 of 2 files at r3, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-01 15:43 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-01 15:43 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1959)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-01 17:20 UTC, merged