[GSC] New info-image command to retrieve SGX information from graphenized Docker image
oscarlab/graphene pull request #1961
Opened 2020-11-12 16:48 UTC by vahldiek

## Description of the changes 

This PR adds a new command to GSC called `info-image`. `info-image` command retrieves the SGX related information from the Docker image. In particular, it prints the sig struct information for each application inside the Docker image. It also adds documentation, a new test case to GSC's test makefile, and a new test to GSC's Jenkins pipeline.

## How to test this PR? 

Run GSC Jenkins pipeline or create a graphenized Docker image (via `gsc build-image` and `gsc sign-image`) and afterwards run `gsc info-image <image-name>`.

2020-11-13 13:17 UTC, vahldiek reviewed
PR was updated to format output in TOML and take as an input the fully qualifying docker image name.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961#-:-MM0kCw9899H3cvAhnqz:b-8iwjti)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2020-11-17 09:34 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vahldiek)

___
*[Documentation/manpages/gsc.rst, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKSa-o20pWMrsbgu6Z:-MMKSa-pC7wo6UWTrzsU:b1l89ji) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Documentation/manpages/gsc.rst#L230)):*
> ```reStructuredText
> --------------------------------------------------------------------------------
> 
> Retrieves Intel SGX relevant infomration about the graphenized Docker image such
> ```

`information` (typo)
___
*[Documentation/manpages/gsc.rst, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKSej7ALMYxh_P2vpD:-MMKSej7ALMYxh_P2vpE:bfa04y2) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Documentation/manpages/gsc.rst#L231)):*
> ```reStructuredText
> 
> Retrieves Intel SGX relevant infomration about the graphenized Docker image such
> as the ``MRENCLAVE`` and ``MRSIGNER`` for each application in the Docker image.
> ```

Looks like broken English. Two fixes, choose whatever you like:
1. `...as the MRENCLAVE and MRSIGNER measurements for...`
2. `...as MRENCLAVE and MRSIGNER for...`
___
*[Tools/gsc/gsc.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKT4HoA7siAgbRaHEH:-MMKT4HoA7siAgbRaHEI:b-lhfxwt) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L19)):*
> ```Python
> import docker
> import yaml
> import toml
> ```

Is there a reason these imports are not sorted? If there is no reason, please sort. If there needs to be some order, please separate into sub-group via line breaks.
___
*[Tools/gsc/gsc.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKYPekAaVVKPm7x4VA:-MMKYPekAaVVKPm7x4VB:bm8k0z2) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L19)):*
> ```Python
> import docker
> import yaml
> import toml
> ```

Aren't you supposed to install `toml` Python package somehow? Mention here: https://graphene.readthedocs.io/en/latest/manpages/gsc.html#software-packages. And probably add to our Jenkinsfiles (if we want to test this feature).
___
*[Tools/gsc/gsc.py, line 336 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKTJdo3zM00_j-BJIS:-MMKTJdo3zM00_j-BJIT:b-zh4y0a) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L336)):*
> ```Python
>               f'image {gsc_image_name(image)}.')
> 
> # Fixed SGX architecture values
> ```

Better comment: `# Offsets for fields in SIGSTRUCT (defined by the SGX HW architecture, never change)`
___
*[Tools/gsc/gsc.py, line 346 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKU-so0nRLkgf8FMmU:-MMKU-so0nRLkgf8FMmV:b-5mqzbo) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L346)):*
> ```Python
> def read_sigstruct(sig):
> 
>     # """Reading Sigstruct."""
> ```

Can you remove this comment line? Looks useless.
___
*[Tools/gsc/gsc.py, line 372 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVG_-9a-88x4kVY9u:-MMKVG_-9a-88x4kVY9v:b-5zke8k) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L372)):*
> ```Python
>         mrsigner = hashlib.sha256()
>         mrsigner.update(attr['modulus'])
> ```

Please remove one empty line
___
*[Tools/gsc/gsc.py, line 378 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKV3uT4gmGWBcvb_JN:-MMKV3uT4gmGWBcvb_JO:b-ns3zj2) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L378)):*
> ```Python
>         sigstruct['mr_signer'] = mrsigner.digest().hex()
>         sigstruct['isv_prod_id'] = attr["isv_prod_id"]
>         sigstruct['isv_svn'] = attr["isv_svn"]
> ```

In the above two lines, please replace `"` with `'` around string values (for consistency)
___
*[Tools/gsc/gsc.py, line 383 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVdG5A_pGaV2ZfMLy:-MMKVdG5A_pGaV2ZfMLz:bbwgde8) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L383)):*
> ```Python
>         return sigstruct
> 
> # Sign Docker image which was previously built via `gsc build`.
> ```

This comment is wrong. We don't sign anything. Maybe `# Retrieve information about a previously built graphenized Docker image`?
___
*[Tools/gsc/gsc.py, line 396 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVqjKElYSG-I5n9jZ:-MMKVqjKElYSG-I5n9j_:b-6ttz6e) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L396)):*
> ```Python
>         sys.exit(1)
> 
>     # Create temporary directory for sig struct files
> ```

`sig struct` -> `sigstruct`
___
*[Tools/gsc/gsc.py, line 399 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVsjx5ZhbUFAA3Hh5:-MMKVsjx5ZhbUFAA3Hh6:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L399)):*
> ```Python
>     with tempfile.TemporaryDirectory() as tmpdirname:
> 
>         # Copy sig struct files into temporary directory
> ```

ditto
___
*[Tools/gsc/test/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKX0sfDPYodj1yCzSh:-MMKX0sfDPYodj1yCzSi:b9sl8xk) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/test/Makefile#L27)):*
> ```Makefile
> 	sed -e 's/Distro: \".*\"/Distro: \"'$*'\"/' \
> 		    -e 's/Branch: \"master\"/Branch: \"'$(GRAPHENE_BRANCH)'\"/' \
> 			../config.yaml.template > config-$*.yaml;
> ```

Strange mix of tabs and spaces. Could you mix them in such a way that there is always one tab in the beginning of line, followed by spaces? And please make indentation so that it's clear that all three lines belong to one command `sed`.

You can also replace `../config.yaml.template` -> `$<` and `config-$*.yaml` -> `$@`.
___
*[Tools/gsc/test/Makefile, line 186 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKXdcR1Zhbwc-8-4jF:-MMKXdcR1Zhbwc-8-4jG:b9xkh1c) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/test/Makefile#L186)):*
> ```Makefile
> 	../gsc info-image $*-python3 > sig.txt
> 	grep -q "mr_enclave" sig.txt
> 	$(RM) sig.txt
> ```

Could you the invocation of `./gsc info-image ...` in the https://graphene.readthedocs.io/en/latest/manpages/gsc.html#example?

Also, this is not really tested, right? This target seems useless. Could you add it to Jenkins tests?


<!-- Sent from Reviewable.io -->

2020-11-17 17:03 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: 0 of 3 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKSa-o20pWMrsbgu6Z:-MMM3t-vBJh2PaN5Ep0q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Documentation/manpages/gsc.rst#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`information` (typo)
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKSej7ALMYxh_P2vpD:-MMM40Dc1_D-WGtSCLSD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Documentation/manpages/gsc.rst#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like broken English. Two fixes, choose whatever you like:
1. `...as the MRENCLAVE and MRSIGNER measurements for...`
2. `...as MRENCLAVE and MRSIGNER for...`
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKT4HoA7siAgbRaHEH:-MMM44et81gN7DUVIGp0:b-ts32dv) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is there a reason these imports are not sorted? If there is no reason, please sort. If there needs to be some order, please separate into sub-group via line breaks.
</blockquote></details>

Most imports have to come before docker, jinja2, toml, yaml otherwise the linter complains. I've tried my best to improve the ordering.
___
*[Tools/gsc/gsc.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKYPekAaVVKPm7x4VA:-MMM55rg6tiXJim7dfGo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Aren't you supposed to install `toml` Python package somehow? Mention here: https://graphene.readthedocs.io/en/latest/manpages/gsc.html#software-packages. And probably add to our Jenkinsfiles (if we want to test this feature).
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 336 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKTJdo3zM00_j-BJIS:-MMM5k5g1laW2t0TFYBu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L336)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Better comment: `# Offsets for fields in SIGSTRUCT (defined by the SGX HW architecture, never change)`
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 346 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKU-so0nRLkgf8FMmU:-MMM5l8t1azYW9wjFzMc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L346)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you remove this comment line? Looks useless.
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 372 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVG_-9a-88x4kVY9u:-MMM5ppe4JINKPiOi-6h:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L372)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove one empty line
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 378 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKV3uT4gmGWBcvb_JN:-MMM5uKv8hEI5zyYiEqf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L378)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In the above two lines, please replace `"` with `'` around string values (for consistency)
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 383 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVdG5A_pGaV2ZfMLy:-MMM5zaR9R4rcXw_Xsjo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L383)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is wrong. We don't sign anything. Maybe `# Retrieve information about a previously built graphenized Docker image`?
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 396 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVqjKElYSG-I5n9jZ:-MMM61-68Bps7n3ZffzG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L396)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sig struct` -> `sigstruct`
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 399 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKVsjx5ZhbUFAA3Hh5:-MMM62Jj1N0C8bZa0F4z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/gsc.py#L399)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Tools/gsc/test/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKX0sfDPYodj1yCzSh:-MMM8HB67u_VJqf9GuY_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/test/Makefile#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Strange mix of tabs and spaces. Could you mix them in such a way that there is always one tab in the beginning of line, followed by spaces? And please make indentation so that it's clear that all three lines belong to one command `sed`.

You can also replace `../config.yaml.template` -> `$<` and `config-$*.yaml` -> `$@`.
</blockquote></details>

Done.
___
*[Tools/gsc/test/Makefile, line 186 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKXdcR1Zhbwc-8-4jF:-MMM6R2H09XN_OOU6XHy:byz9nly) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/test/Makefile#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you the invocation of `./gsc info-image ...` in the https://graphene.readthedocs.io/en/latest/manpages/gsc.html#example?

Also, this is not really tested, right? This target seems useless. Could you add it to Jenkins tests?
</blockquote></details>

Yes, I added this to the jenkins test for GSC. I've also added it to the documentation.


<!-- Sent from Reviewable.io -->

2020-11-24 09:57 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vahldiek)

___
*[Documentation/manpages/gsc.rst, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMteiKv7f1AjNoMpv5W:-MMteiKw4E0F_OP3PidA:b-lmasg8) ([raw file](https://github.com/oscarlab/graphene/blob/9e3fcd33df24ddc7bc4ef9db09bc1b139878fd7a/Documentation/manpages/gsc.rst#L44)):*
> ```reStructuredText
> 
> Please install the ``docker.io``, ``python3``, ``python3-pip`` packages. In
> addition, install the Docker client, Jinja2, TOML, and YAML python package via
> ```

`packages`
___
*[Documentation/manpages/gsc.rst, line 485 at r2](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMteuTP71xXkBWKE-Gh:-MMteuTP71xXkBWKE-Gi:b-9pyqzp) ([raw file](https://github.com/oscarlab/graphene/blob/9e3fcd33df24ddc7bc4ef9db09bc1b139878fd7a/Documentation/manpages/gsc.rst#L485)):*
> ```reStructuredText
>       ./gsc sign-image python enclave-key.pem
> 
> #. Retrieve SGX-related information from graphenized Image using :command:`gsc info-image`:
> ```

Why is `Image` with capital letter? German? :)
___
*[Tools/gsc/test/Makefile, line 186 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKXdcR1Zhbwc-8-4jF:-MMtfpNz36fWXawZGbKE:bpabco4) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/test/Makefile#L186)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Yes, I added this to the jenkins test for GSC. I've also added it to the documentation.
</blockquote></details>

How is this added to Jenkins? I don't see any changes in Jenkins files.


<!-- Sent from Reviewable.io -->

2020-11-24 11:45 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: 2 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMteiKv7f1AjNoMpv5W:-MMu2zUf6GhJD7q1OgrS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9e3fcd33df24ddc7bc4ef9db09bc1b139878fd7a/Documentation/manpages/gsc.rst#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`packages`
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 485 at r2](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMteuTP71xXkBWKE-Gh:-MMu2tkM-Dh0o7gUV4nJ:b-9dylz6) ([raw file](https://github.com/oscarlab/graphene/blob/9e3fcd33df24ddc7bc4ef9db09bc1b139878fd7a/Documentation/manpages/gsc.rst#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is `Image` with capital letter? German? :)
</blockquote></details>

Done. Possibly....
___
*[Tools/gsc/test/Makefile, line 186 at r1](https://reviewable.io/reviews/oscarlab/graphene/1961#-MMKXdcR1Zhbwc-8-4jF:-MMu3-iZ1L1OBxI0Tls-:b5xmryv) ([raw file](https://github.com/oscarlab/graphene/blob/7b47a3dc55d2873d2251202160d72cc9b63abc2e/Tools/gsc/test/Makefile#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How is this added to Jenkins? I don't see any changes in Jenkins files.
</blockquote></details>

Must have slipped through the commit.  Added it now


<!-- Sent from Reviewable.io -->

2020-11-24 14:51 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-24 14:51 UTC, dimakuv commented
Jenkins, test this please

2021-03-17 00:21 UTC, vahldiek reviewed
I finally got around to rebase this PR... Please let me know, if you think it would be better to start a new PR that removes the history of this PR.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961#-:-MVxYYLp9bKu2bvKKIa5:b-ye7h0w)* status: 1 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-03-19 01:10 UTC, mkow commented
Jenkins, retest this please

2021-03-19 01:44 UTC, mkow requested changes
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Tools/gsc/gsc.py, line 15 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW71uQLA-DTfHPCBtqD:-MW71uQLA-DTfHPCBtqE:bfur1f3) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L15)):*
> ```Python
> import sys
> import tempfile
> import struct
> ```

please sort
___
*[Tools/gsc/gsc.py, line 21 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW71x6WEnxu_rzoiPoZ:-MW71x6WEnxu_rzoiPo_:bfur1f3) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L21)):*
> ```Python
> import docker  # pylint: disable=import-error
> import yaml    # pylint: disable=import-error
> import toml
> ```

please sort
___
*[Tools/gsc/gsc.py, line 298 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW72JBM9j4ncTKKmeEs:-MW72JBM9j4ncTKKmeEt:b-bloqjm) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L298)):*
> ```Python
> 
> 
> # Offsets for fields in SIGSTRUCT (defined by the SGX HW architecture, never change)
> ```

`never change` -> `they never change` (otherwise it's unclear if you're saying to the reader to stop him from changing the values or whether they itself are set in stone)
___
*[Tools/gsc/gsc.py, line 307 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW750ArB4yl-uzHmCvJ:-MW750ArB4yl-uzHmCvK:b-m388q5) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L307)):*
> ```Python
> # Simplified version of read_sigstruct from Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
> def read_sigstruct(sig):
> ```

no need for these empty lines, please remove in the whole PR
___
*[Tools/gsc/gsc.py, line 317 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW74U3i4dZUjcBTbDh8:-MW74U3i4dZUjcBTbDh9:bi744mz) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L317)):*
> ```Python
>     }
> 
>     attr = dict()
> ```

`dict()` -> `{}`
___
*[Tools/gsc/gsc.py, line 353 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW763AE53N4CYz_wBHG:-MW763AE53N4CYz_wBHH:bsnynye) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L353)):*
> ```
> gsc build
> ```

Please wrap this in backticks (now it may look like a part of the sentence)
___
*[Tools/gsc/gsc.py, line 362 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW76L7-69HrDJjrEcNK:-MW76L7-69HrDJjrEcNL:b-626pk1) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L362)):*
> ```
> /tmp/host
> ```

This isn't safe when someone runs multiple instances of GSC on the same system.
___
*[Tools/gsc/gsc.py, line 372 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW77IY_0msKdn6AGtfM:-MW77IY_0msKdn6AGtfN:b-cfol2t) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L372)):*
> ```Python
> 
>         if len(siginfo) > 0:
>             print(toml.dumps(siginfo))
> ```

I don't get this, why do you print _TOML_ to the console?
___
*[Tools/gsc/test/Makefile, line 33 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW77fU5BvDkiPp_ZbiG:-MW77fU5BvDkiPp_ZbiH:bb1595x) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/test/Makefile#L33)):*
> ```Makefile
> 	done
> 
> config-%.yaml: ../config.yaml.template
> ```

Why does this depend on `../config.yaml.template` if it's not using it? It's just printing hardcoded data to a file?


<!-- Sent from Reviewable.io -->

2021-03-19 21:10 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: 2 of 4 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Tools/gsc/gsc.py, line 15 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW71uQLA-DTfHPCBtqD:-MWBA9Xs5AlzsXZga_y4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 21 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW71x6WEnxu_rzoiPoZ:-MWBA9pPAsnLlXUkJaJ0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 298 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW72JBM9j4ncTKKmeEs:-MWBAFmS6zgqxP8i0XJL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L298)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`never change` -> `they never change` (otherwise it's unclear if you're saying to the reader to stop him from changing the values or whether they itself are set in stone)
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 307 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW750ArB4yl-uzHmCvJ:-MWBAUii17C2Pqj8sG7y:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L307)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need for these empty lines, please remove in the whole PR
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 317 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW74U3i4dZUjcBTbDh8:-MWBAUR947yFUIblqqOB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L317)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`dict()` -> `{}`
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 353 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW763AE53N4CYz_wBHG:-MWBAixJ2ftUFD-1Ognx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L353)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> gsc build
> ```

Please wrap this in backticks (now it may look like a part of the sentence)
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 362 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW76L7-69HrDJjrEcNK:-MWBB7PJAkF9ZYNtZ2F-:b-c1t2l7) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L362)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> /tmp/host
> ```

This isn't safe when someone runs multiple instances of GSC on the same system.
</blockquote></details>

Why is this not safe for multiple GSC instances? We're using a unique temporary directory. Each of the GSC instances would not copy to the same folder. The location we mount this to inside the docker container is the same '/tmp/host'. 
___
*[Tools/gsc/gsc.py, line 372 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW77IY_0msKdn6AGtfM:-MWBBROt6pHGj9fjhJUo:bwxy1t3) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L372)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't get this, why do you print _TOML_ to the console?
</blockquote></details>

We could also store it in a file, if you prefer. The main reason to print TOML was to provide a machine-readable output instead of something that is more human-readable. The use case here is that someone uses the tool to extract the information and immediately uses it to do something else without human intervention.
___
*[Tools/gsc/test/Makefile, line 33 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW77fU5BvDkiPp_ZbiG:-MWBBzYY1ODt0o_NpeKM:b-ixacax) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/test/Makefile#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why does this depend on `../config.yaml.template` if it's not using it? It's just printing hardcoded data to a file?
</blockquote></details>

It shouldn't. Done. Also fixed the actual configuration creation. 


<!-- Sent from Reviewable.io -->

2021-03-20 01:14 UTC, mkow requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vahldiek)

___
*[Tools/gsc/gsc.py, line 304 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWCACpK-ZMH6HgTVArG:-MWCACpK-ZMH6HgTVArH:b-lj4ix6) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L304)):*
> ```Python
> SGX_ARCH_ENCLAVE_CSS_ISV_PROD_ID = 1024
> SGX_ARCH_ENCLAVE_CSS_ISV_SVN = 1026
> ```

This one was actually useful, it separated the constants list from the function. I mean only these empty lines after `def:` lines you put everywhere. Please just drop the lines after colon-ending lines, all the others were fine.
___
*[Tools/gsc/gsc.py, line 362 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW76L7-69HrDJjrEcNK:-MWCApdZ0lOzvtYrj_At:b-dhjh0x) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L362)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Why is this not safe for multiple GSC instances? We're using a unique temporary directory. Each of the GSC instances would not copy to the same folder. The location we mount this to inside the docker container is the same '/tmp/host'. 
</blockquote></details>

Ah, wait, this `/tmp/host` is inside the container, I misread the code and thought that this is the path on the host.
___
*[Tools/gsc/gsc.py, line 372 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW77IY_0msKdn6AGtfM:-MWCB96XDUh8czzOO8eC:bbj0jdv) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L372)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

We could also store it in a file, if you prefer. The main reason to print TOML was to provide a machine-readable output instead of something that is more human-readable. The use case here is that someone uses the tool to extract the information and immediately uses it to do something else without human intervention.
</blockquote></details>

Hmm, is this consistent with the rest of GSC interface? I mean, is cmdline GSC supposed to be used from scripts and the output to be parsed? Is this the same for other GSC commands than this one?


<!-- Sent from Reviewable.io -->

2021-03-20 04:41 UTC, vahldiek reviewed
Rebased to the latest Graphene master.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961#-:-MWCvu9u-AsoimKWMpzX:b-3t6yqk)* status: 3 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Tools/gsc/gsc.py, line 304 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWCACpK-ZMH6HgTVArG:-MWCu7MMBKmp1V1G_VE8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L304)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This one was actually useful, it separated the constants list from the function. I mean only these empty lines after `def:` lines you put everywhere. Please just drop the lines after colon-ending lines, all the others were fine.
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 362 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW76L7-69HrDJjrEcNK:-MWCu8se2ttfes7J4YT5:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L362)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, wait, this `/tmp/host` is inside the container, I misread the code and thought that this is the path on the host.
</blockquote></details>

OK
___
*[Tools/gsc/gsc.py, line 372 at r4](https://reviewable.io/reviews/oscarlab/graphene/1961#-MW77IY_0msKdn6AGtfM:-MWCuCx-10WVlE98e7H0:b-5q547) ([raw file](https://github.com/oscarlab/graphene/blob/e9cbd97084a0c9c446628119bc41c1d454a1da09/Tools/gsc/gsc.py#L372)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, is this consistent with the rest of GSC interface? I mean, is cmdline GSC supposed to be used from scripts and the output to be parsed? Is this the same for other GSC commands than this one?
</blockquote></details>

This is not the case for the other three commands, since they constantly produce output during the Docker build. But this could be changed and if I remember correctly the Docker output is in Json which we extract (see lines 40 and following). For this PR the request was to have common output format.


<!-- Sent from Reviewable.io -->

2021-03-20 12:19 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-23 16:11 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vahldiek)

___
*[Tools/gsc/gsc.py, line 302 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUpsrR-HfymAXj9-5P:-MWUpsrR-HfymAXj9-5Q:b-wuryk3) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L302)):*
> ```Python
> SGX_ARCH_ENCLAVE_CSS_ENCLAVE_HASH = 960
> SGX_ARCH_ENCLAVE_CSS_ISV_PROD_ID = 1024
> SGX_ARCH_ENCLAVE_CSS_ISV_SVN = 1026
> ```

Can we actually move all these constants inside `read_sigstruct()`?
___
*[Tools/gsc/gsc.py, line 304 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUpp2s8tN-uIUXfqgh:-MWUpp2tCfwA0XybW7u5:b-pk4sb2) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L304)):*
> ```Python
> SGX_ARCH_ENCLAVE_CSS_ISV_SVN = 1026
> 
> # Simplified version of read_sigstruct from Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
> ```

The file was moved to `https://github.com/oscarlab/graphene/blob/master/python/graphenelibos/sgx_get_token.py`. Please change the path.
___
*[Tools/gsc/gsc.py, line 322 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUq3ZPBhaHpGGy5zty:-MWUq3ZPBhaHpGGy5ztz:b-w0vtqi) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L322)):*
> ```Python
>     return attr
> 
> def import_sigstruct_from_file(f_sig):
> ```

Once you'll replace the logic of "find all sig files and call `import_sigstruct_from_file()`" with the "parse entrypoint.sig file", you can merge this function into `gsc_info_image()` itself.
___
*[Tools/gsc/gsc.py, line 338 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUpCyi6DWvzIyVYYSX:-MWUpCyi6DWvzIyVYYSY:b2rbfbg) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L338)):*
> ```Python
> # Retrieve information about a previously built graphenized Docker image
> def gsc_info_image(args):
>     image = args.image
> ```

Can we just use `args.image` everywhere? This "let's alias image with image" looks ugly, and also it's hard to distinguish `image` vs `gsc_image` currently.
___
*[Tools/gsc/gsc.py, line 348 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUoW8bDhUjc0fSwQPJ:-MWUoW8c99x2nvv5mqKx:b-wme9hc) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L348)):*
> ```Python
> 
>     # Create temporary directory for sigstruct files
>     with tempfile.TemporaryDirectory() as tmpdirname:
> ```

But now we have only one `*.sig` file -- namely `entrypoint.sig`. Why all this complicated logic to find and copy these sig files instead of just parsing `entrypoint.sig`?
___
*[Tools/gsc/gsc.py, line 366 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUp4tn9cPDJhpPpsaE:-MWUp4tn9cPDJhpPpsaF:ba5rs9o) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L366)):*
> ```Python
>             print(f'Could not extract Intel SGX-related information from image {image}.')
>             sys.exit(1)
> ```

Please add one more empty line (for readability)


<!-- Sent from Reviewable.io -->

2021-03-29 20:06 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: 3 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Tools/gsc/gsc.py, line 302 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUpsrR-HfymAXj9-5P:-MWzYTbKE65D9N1owocs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L302)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we actually move all these constants inside `read_sigstruct()`?
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 304 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUpp2s8tN-uIUXfqgh:-MWzYaPU7ipB--9Jy1FR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L304)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The file was moved to `https://github.com/oscarlab/graphene/blob/master/python/graphenelibos/sgx_get_token.py`. Please change the path.
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 322 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUq3ZPBhaHpGGy5zty:-MWz_hCjE5_cfl2bVZz1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L322)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Once you'll replace the logic of "find all sig files and call `import_sigstruct_from_file()`" with the "parse entrypoint.sig file", you can merge this function into `gsc_info_image()` itself.
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 338 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUpCyi6DWvzIyVYYSX:-MWz_F5pEXj2PvIIjvn2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L338)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we just use `args.image` everywhere? This "let's alias image with image" looks ugly, and also it's hard to distinguish `image` vs `gsc_image` currently.
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 348 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUoW8bDhUjc0fSwQPJ:-MWz_9T_2JQvv5QNwjCw:b1o8qks) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But now we have only one `*.sig` file -- namely `entrypoint.sig`. Why all this complicated logic to find and copy these sig files instead of just parsing `entrypoint.sig`?
</blockquote></details>

Yes, you're right. I forgot about it. Removed it.
___
*[Tools/gsc/gsc.py, line 366 at r6](https://reviewable.io/reviews/oscarlab/graphene/1961#-MWUp4tn9cPDJhpPpsaE:-MWz_IkcBDnp9qmDKq9r:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c62ff6a440e6bf38e3773a9faa079e7ef4a8739c/Tools/gsc/gsc.py#L366)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add one more empty line (for readability)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-30 07:18 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Tools/gsc/gsc.py, line 331 at r7](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX0z1jjETIUGk_Wl1rT:-MX0z1jk-qa1Gnwd8rlE:b-jzdndw) ([raw file](https://github.com/oscarlab/graphene/blob/d2787ab71a3724bd0f56c8c107ec7f1fdedda8b5/Tools/gsc/gsc.py#L331)):*
> ```Python
>         sys.exit(1)
> 
>     # Create temporary directory for sigstruct files
> ```

`# Create temporary directory on the host for sigstruct file` (single)
___
*[Tools/gsc/gsc.py, line 333 at r7](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX0z5xS3ySq-JGNSPZO:-MX0z5xS3ySq-JGNSPZP:b1a5bxm) ([raw file](https://github.com/oscarlab/graphene/blob/d2787ab71a3724bd0f56c8c107ec7f1fdedda8b5/Tools/gsc/gsc.py#L333)):*
> ```Python
>     # Create temporary directory for sigstruct files
>     with tempfile.TemporaryDirectory() as tmpdirname:
>         # Copy sigstruct files into temporary directory
> ```

`# Copy sigstruct file from Docker container into temporary directory on the host`
___
*[Tools/gsc/gsc.py, line 353 at r7](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX0zQR61dNTilaSMpat:-MX0zQR61dNTilaSMpau:bak9guj) ([raw file](https://github.com/oscarlab/graphene/blob/d2787ab71a3724bd0f56c8c107ec7f1fdedda8b5/Tools/gsc/gsc.py#L353)):*
> ```Python
>         else:
>             print(f'Could not extract Intel SGX-related information from image {args.image}.')
>             sys.exit(1)
> ```

Can we revert this IF logic?
```
    if len(sigstruct) == 0:
        print(f'Could not extract Intel SGX-related information from image {args.image}.')
        sys.exit(1)

    print(toml.dumps(sigstruct))
```


<!-- Sent from Reviewable.io -->

2021-03-30 15:17 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Tools/gsc/gsc.py, line 331 at r7](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX0z1jjETIUGk_Wl1rT:-MX2gXp0El4T1i99ipYY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2787ab71a3724bd0f56c8c107ec7f1fdedda8b5/Tools/gsc/gsc.py#L331)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`# Create temporary directory on the host for sigstruct file` (single)
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 333 at r7](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX0z5xS3ySq-JGNSPZO:-MX2ggPC1O5AEP3TPcXy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2787ab71a3724bd0f56c8c107ec7f1fdedda8b5/Tools/gsc/gsc.py#L333)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`# Copy sigstruct file from Docker container into temporary directory on the host`
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 353 at r7](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX0zQR61dNTilaSMpat:-MX2glRZ08RUBFH3gXNx:bzeyi24) ([raw file](https://github.com/oscarlab/graphene/blob/d2787ab71a3724bd0f56c8c107ec7f1fdedda8b5/Tools/gsc/gsc.py#L353)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we revert this IF logic?
```
    if len(sigstruct) == 0:
        print(f'Could not extract Intel SGX-related information from image {args.image}.')
        sys.exit(1)

    print(toml.dumps(sigstruct))
```
</blockquote></details>

Sure. 


<!-- Sent from Reviewable.io -->

2021-03-30 16:04 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-03-30 16:29 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX2xp_FCzdKeZVQnWeY:-MX2xp_FCzdKeZVQnWeZ:bat00yj) (no related file):*
Just tested this locally, works like charm:
```sh
$ ./gsc info-image gsc-python
mr_enclave = "7f84f5594f59c5f3a72f5c5b88f08a7f7d87ae14355f20d3a3f1a2bc7f803307"
mr_signer = "340c56c0149f6abe58b239e9492dc5ecc0ef1982179ee6d7436811720ec5647b"
isv_prod_id = 0
isv_svn = 0
date = "2021-03-30"
```

---


<!-- Sent from Reviewable.io -->

2021-03-30 16:36 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vahldiek)

___
*[Documentation/manpages/gsc.rst, line 209 at r8](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX2yoLO8aSWMCvBPjxB:-MX2yoLO8aSWMCvBPjxC:bahdp3d) ([raw file](https://github.com/oscarlab/graphene/blob/c1ad9d4f5f898ff8717664533840541a222f63e8/Documentation/manpages/gsc.rst#L209)):*
> ```reStructuredText
>    Name of the resulting Graphene Docker image
> ```

You forgot to add `.. program:: gsc-info-image` before your new text. Otherwise Jenkins complains:
```
/home/jenkins/workspace/docs-18.04/Documentation/manpages/gsc.rst:224:
    Duplicate explicit target name: "cmdoption-gsc-build-graphene-arg-IMAGE-NAME".
Makefile:22: recipe for target 'html' failed
```
___
*[Tools/gsc/gsc.py, line 298 at r8](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX2z9g87kxsjDE5fn8R:-MX2z9g87kxsjDE5fn8S:b-cviou8) ([raw file](https://github.com/oscarlab/graphene/blob/c1ad9d4f5f898ff8717664533840541a222f63e8/Tools/gsc/gsc.py#L298)):*
> ```Python
> 
> # Simplified version of read_sigstruct from python/graphenelibos/sgx_get_token.py
> def read_sigstruct(sig):
> ```


Jenkins complained about this code:
```
************* Module gsc
C:334, 0: Line too long (101/100) (line-too-long)
C:349,11: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
```

For the second error, see this: https://stackoverflow.com/questions/43121340/why-is-the-use-of-lensequence-in-condition-values-considered-incorrect-by-pyli.

Please fix `if len(sigstruct) == 0:` -> `if not sigstruct:`.


<!-- Sent from Reviewable.io -->

2021-03-30 20:30 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: 2 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Documentation/manpages/gsc.rst, line 209 at r8](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX2yoLO8aSWMCvBPjxB:-MX3n_2M-kQUoJhOHaEO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c1ad9d4f5f898ff8717664533840541a222f63e8/Documentation/manpages/gsc.rst#L209)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to add `.. program:: gsc-info-image` before your new text. Otherwise Jenkins complains:
```
/home/jenkins/workspace/docs-18.04/Documentation/manpages/gsc.rst:224:
    Duplicate explicit target name: "cmdoption-gsc-build-graphene-arg-IMAGE-NAME".
Makefile:22: recipe for target 'html' failed
```
</blockquote></details>

Done.
___
*[Tools/gsc/gsc.py, line 298 at r8](https://reviewable.io/reviews/oscarlab/graphene/1961#-MX2z9g87kxsjDE5fn8R:-MX3objF80Ed1haQXD-f:bnyasa9) ([raw file](https://github.com/oscarlab/graphene/blob/c1ad9d4f5f898ff8717664533840541a222f63e8/Tools/gsc/gsc.py#L298)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>


Jenkins complained about this code:
```
************* Module gsc
C:334, 0: Line too long (101/100) (line-too-long)
C:349,11: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
```

For the second error, see this: https://stackoverflow.com/questions/43121340/why-is-the-use-of-lensequence-in-condition-values-considered-incorrect-by-pyli.

Please fix `if len(sigstruct) == 0:` -> `if not sigstruct:`.
</blockquote></details>

Done. Makes sense and looks much nicer.


<!-- Sent from Reviewable.io -->

2021-03-31 06:10 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-03-31 06:11 UTC, dimakuv commented
Jenkins, test this please

2021-03-31 13:34 UTC, dimakuv commented
Jenkins, test this please

2021-03-31 13:46 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1961)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-31 14:01 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`ftruncate01` LTP test failed with `Test killed by SIGPWR`)

2021-03-31 14:02 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (`udp` LibOS test failed)

2021-04-01 06:27 UTC, merged