[LibOS] Preserve type checking when copying equivalent structures
oscarlab/graphene pull request #1962
Opened 2020-11-13 00:55 UTC by stefanberger

Get rid of a few memcpy's to preserve the type checking when copying
structures around.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

## Description of the changes 

## How to test this PR?

2020-11-13 00:56 UTC, stefanberger reviewed
This PR does not cover all cases in LibOS. I first want to see what you say before I was to add more...

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962#-:-MLz5V4X7gbaQp53iR1D:b-57b4kt)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2020-11-13 01:12 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1962#-MLz9CeRC__2BJfZN__f:-MLz9CeRC__2BJfZN__g:bs9m4n8) (no related file):*
> This PR does not cover all cases in LibOS. I first want to see what you say before I was to add more...

This is definitely a good idea, I think I even had this on my todolist :)

---


<!-- Sent from Reviewable.io -->

2020-11-13 01:13 UTC, boryspoplawski approved these changes
Sounds good to me!

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962#-:-MLz9TGc8AlwKnp1E2Ow:b-ba7jdc)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-13 09:43 UTC, dimakuv submitted a review, later dismissed
Good to me as well, approved.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962#-:-MM-zJAwEGF9y287W1jg:b91dklk)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-13 09:44 UTC, dimakuv commented
Jenkins, test this please

2020-11-13 10:42 UTC, dimakuv commented
Jenkins, retest this please (now Jenkins is back again)

2020-11-16 17:28 UTC, stefanberger reviewed
I have another patch with more. Will send another PR then.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962#-:-MMH5JX0BByGGWYIJrGM:bda2qsq)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-16 17:32 UTC, boryspoplawski approved these changes
You could also add it to this PR. We have a temporary Jenkins failure and won't be able to merge anything (including this PR) for a bit. 

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962#-:-MMH5wiD2gbLmka_YKJC:bfg325m)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-16 20:15 UTC, yamahata submitted a review, later dismissed
> Reviewed 3 of 4 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-16 20:26 UTC, mkow requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/src/sys/shim_clone.c, line 287 at r2](https://reviewable.io/reviews/oscarlab/graphene/1962#-MMHj05O3RHZRleGSYFN:-MMHj05P9FuAk49qSAx_:bz5rjzo) ([raw file](https://github.com/oscarlab/graphene/blob/107c8964d761acf24530279d2f8ad7bd70769f99/LibOS/shim/src/sys/shim_clone.c#L287)):*
> ```C
>         /* Associate new cpu context to the new process (its main and only thread) for migration
>          * since we might need to modify some registers. */
>         shim_tcb_t shim_tcb = *self->shim_tcb;
> ```

Now the comment below is misaligned - it was about this very copying you moved here.


<!-- Sent from Reviewable.io -->

2020-11-16 23:49 UTC, boryspoplawski requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)



<!-- Sent from Reviewable.io -->

2020-11-17 00:49 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/sys/shim_clone.c, line 287 at r2](https://reviewable.io/reviews/oscarlab/graphene/1962#-MMHj05O3RHZRleGSYFN:-MMIfQl1DgmVdhvmTAXX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/107c8964d761acf24530279d2f8ad7bd70769f99/LibOS/shim/src/sys/shim_clone.c#L287)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now the comment below is misaligned - it was about this very copying you moved here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 01:17 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-11-17 01:18 UTC, boryspoplawski commented
Jenkins, test this please

2020-11-17 01:20 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-17 07:35 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-17 07:44 UTC, dimakuv approved these changes
> Reviewed 6 of 9 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-11-17 08:16 UTC, dimakuv commented
Jenkins, test this please

2020-11-17 08:37 UTC, dimakuv commented
Jenkins, retest Jenkins  please (`select04` LTP test failed)

2020-11-17 08:46 UTC, dimakuv commented
Jenkins, retest Jenkins please (previous request didn't trigger Jenkins)

2020-11-17 13:07 UTC, boryspoplawski approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-17 13:32 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1962)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-17 13:39 UTC, merged