[Pal,LibOS] Fix loader.debug_type = file
oscarlab/graphene pull request #1965
Opened 2020-11-13 14:27 UTC by pwmarcz

See https://github.com/oscarlab/graphene/issues/1947.

## Description of the changes 

This makes `loader.debug_type = "file"` usable again by introducing a new `DkDebugLog` call.

## How to test this PR? 

Run a program with:

```toml
loader.debug_type = "file"
loader.debug_file = "graphene.log"
```

2020-11-13 17:29 UTC, mkow requested changes
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1IjH1AB-k7plltiRY:-MM1IjH1AB-k7plltiRZ:bdygloh) (no related file):*
The last fixup commit ("fixup! [LibOS,Pal,Examples,GSC,Docs] Move manifest parsing to TOML") targets a wrong one (from another PR).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1JwgA3dFHECd9sWrg:-MM1JwgA3dFHECd9sWrh:b-gbv1dh) (no related file):*
Could you add a test for it, so that we won't break this again? You can probably reuse the `Bootstrap` binary from LibOS regression, as other tests often do.

---
___
*[Pal/src/host/Linux/db_streams.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1ca9bDXG8kjUESJKu:-MM1ca9bDXG8kjUESJKv:bnswi30) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux/db_streams.c#L31)):*
> ```C
> #include <sys/socket.h>
> 
> static int g_debug_fd;
> ```

Could you initialize it to -1? (for the `if` in `_DkDebugLog`)
___
*[Pal/src/host/Linux/db_streams.c, line 381 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1_sfb8atqeWyeHXXx:-MM1_sfd3Wjr8NBsBw1E:bmnb1ps) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux/db_streams.c#L381)):*
> ```C
> }
> 
> int _DkDebugLog(const void *buf, int size) {
> ```

`void *buf` -> `void* buf`
`int size` -> `size_t size`
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1dJ_3EkZFQaA91E35:-MM1dJ_3EkZFQaA91E36:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux-SGX/db_streams.c#L36)):*
> ```C
> #define DUMMYPAYLOADSIZE (sizeof(DUMMYPAYLOAD))
> 
> static int g_debug_fd;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 415 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1dKPjDUimunVgKoPZ:-MM1dKPjDUimunVgKoP_:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux-SGX/db_streams.c#L415)):*
> ```C
> }
> 
> int _DkDebugLog(const void* buf, int size) {
> ```

ditto
___
*[Pal/src/host/Skeleton/db_streams.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1dc1J00qNvUW-zlnz:-MM1dc1J00qNvUW-zlo-:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Skeleton/db_streams.c#L41)):*
> ```C
> }
> 
> int _DkDebugLog(const void *buf, int size) {
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-11-16 09:10 UTC, dimakuv requested changes
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1JwgA3dFHECd9sWrg:-MMFJVij0QCl75p12Qtb:b-arytjs) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add a test for it, so that we won't break this again? You can probably reuse the `Bootstrap` binary from LibOS regression, as other tests often do.
</blockquote></details>

+1, need a test for it.

---
___
*[LibOS/shim/src/utils/printf.c, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFG1l6CU695Tf8tC1r:-MMFG1l773_RvjahATq6:b73tdpv) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/LibOS/shim/src/utils/printf.c#L16)):*
> ```C
> 
> static inline int debug_fputs(const char* buf, int len) {
>     if (DkDebugLog((void*)buf, len) == (PAL_NUM)len)
> ```

Maybe better write in a while loop until everything is written out? This will cover cases of partial writes due to interrupts. You can look at how Graphene calls `DkStreamWrite()` for inspiration.
___
*[Pal/include/pal/pal.h, line 685 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFJHr81goNOHKcywUP:-MMFJHr81goNOHKcywUQ:b-rb4w96) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/include/pal/pal.h#L685)):*
> ```objc
>  *
>  * Works only if the debug stream has been initialized, which can be checked by looking at
>  * `g_pal_control.enable_debug_log`.
> ```

Please add a short description of what the function returns (see `DkStreamWrite()` for inspiration).
___
*[Pal/src/db_streams.c, line 760 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFIDj65s2xS0iPE0Qc:-MMFIDj65s2xS0iPE0Qd:bh5wghl) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/db_streams.c#L760)):*
> ```C
>     int ret = _DkDebugLog(buffer, size);
> 
>     LEAVE_PAL_CALL_RETURN(ret);
> ```

This is wrong semantics. In the stream PAL API, we return `PAL_STREAM_ERROR` on failures, and always set the `PAL_ERRNO` via `_DkRiaseFailure(-ret)`. Please change the return value here exactly as in `DkStreamWrite()`.
___
*[Pal/src/pal_internal.h, line 341 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFHbdh5-6h83XDFHLB:-MMFHbdh5-6h83XDFHLC:b-u6erzh) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/pal_internal.h#L341)):*
> ```objc
> 
> int _DkInitDebugStream(const char* path);
> int _DkDebugLog(const void* buf, int size);
> ```

`int size` -> `size_t size`


<!-- Sent from Reviewable.io -->

2020-11-16 10:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: 11 of 23 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1IjH1AB-k7plltiRY:-MMFXmp63aJiKNWUzUTb:biq08i4) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The last fixup commit ("fixup! [LibOS,Pal,Examples,GSC,Docs] Move manifest parsing to TOML") targets a wrong one (from another PR).
</blockquote></details>

Ouch, right. I squashed these initial commits (but kept the new changes as fixup).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1JwgA3dFHECd9sWrg:-MMFeWFTCCNLG8Wi7cO9:bkz4b3f) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, need a test for it.
</blockquote></details>

Done. I added two tests: `debug_log_inline` and `debug_log_file`.

---
___
*[LibOS/shim/src/utils/printf.c, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFG1l6CU695Tf8tC1r:-MMFVLka-FkGmETgTvbZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/LibOS/shim/src/utils/printf.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe better write in a while loop until everything is written out? This will cover cases of partial writes due to interrupts. You can look at how Graphene calls `DkStreamWrite()` for inspiration.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 685 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFJHr81goNOHKcywUP:-MMFW2lx5Ze8pZGPIrAQ:b14bpnm) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/include/pal/pal.h#L685)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a short description of what the function returns (see `DkStreamWrite()` for inspiration).
</blockquote></details>

Done. This was also not specified for `DkStreamWrite`, so I added it to the doc comment there as well.
___
*[Pal/src/db_streams.c, line 760 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFIDj65s2xS0iPE0Qc:-MMFXCWM3kMQOzCqxSTC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/db_streams.c#L760)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is wrong semantics. In the stream PAL API, we return `PAL_STREAM_ERROR` on failures, and always set the `PAL_ERRNO` via `_DkRiaseFailure(-ret)`. Please change the return value here exactly as in `DkStreamWrite()`.
</blockquote></details>

Done.
___
*[Pal/src/pal_internal.h, line 341 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFHbdh5-6h83XDFHLB:-MMFY6rc2htNjvDpPi-e:b-mrt6yr) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/pal_internal.h#L341)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`int size` -> `size_t size`
</blockquote></details>

Done. I changed the code to use `size_t` and `ssize_t` consistently.
___
*[Pal/src/host/Linux/db_streams.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1ca9bDXG8kjUESJKu:-MMFYIg0CuZe6ucndKFx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux/db_streams.c#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you initialize it to -1? (for the `if` in `_DkDebugLog`)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_streams.c, line 381 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1_sfb8atqeWyeHXXx:-MMFYYYH30vlHp2Wiyvn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux/db_streams.c#L381)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`void *buf` -> `void* buf`
`int size` -> `size_t size`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1dJ_3EkZFQaA91E35:-MMFYd4Q80Z_e0nSLXTx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux-SGX/db_streams.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 415 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1dKPjDUimunVgKoPZ:-MMFYe1W6l2fXZDA7FZ4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Linux-SGX/db_streams.c#L415)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Skeleton/db_streams.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/1965#-MM1dc1J00qNvUW-zlnz:-MMFYf4W3L4_cpXttRCT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/97318ace65b9ab15b529d55f5985f2c31a9e4aae/Pal/src/host/Skeleton/db_streams.c#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-16 10:56 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/test/regression/test_libos.py, line 269 at r2](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFgN7V7yOe8LB1_Fwi:-MMFgN7W2dtJ4HH--i61:b-r2nngl) ([raw file](https://github.com/oscarlab/graphene/blob/b26da9ea26443f139423aa2d918f521e219e9c38/LibOS/shim/test/regression/test_libos.py#L269)):*
> ```Python
>         self.assertIn('Host: Linux', log)
>         self.assertIn('Shim process initialized', log)
>         self.assertIn('Shim process initialized', log)
> ```

Why do you have the same check twice?


<!-- Sent from Reviewable.io -->

2020-11-16 12:09 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: 22 of 23 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/test_libos.py, line 269 at r2](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMFgN7V7yOe8LB1_Fwi:-MMFx8Pb41E31YWfjMBQ:b7n7dfn) ([raw file](https://github.com/oscarlab/graphene/blob/b26da9ea26443f139423aa2d918f521e219e9c38/LibOS/shim/test/regression/test_libos.py#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have the same check twice?
</blockquote></details>

I was too quick :) Fixed now.


<!-- Sent from Reviewable.io -->

2020-11-16 12:28 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-11-16 15:58 UTC, mkow requested changes
> Reviewed 11 of 12 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/test/regression/test_libos.py, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMGkfE_77xu6fPoJml9:-MMGkfEaDsLK7AwREAPw:bqu9m7t) ([raw file](https://github.com/oscarlab/graphene/blob/2755beaeaa7083a20dfd10ea002b0c82c4260a80/LibOS/shim/test/regression/test_libos.py#L249)):*
> ```Python
> 
>     def test_700_debug_log_inline(self):
>         manifest = self.get_manifest('debug_log_inline')
> ```

I think this isn't needed anymore, you can just run `debug_log_inline` directly and it should work (ditto below)
___
*[LibOS/shim/test/regression/test_libos.py, line 266 at r3](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMGl7Nf1e-cVo8g9k_d:-MMGl7Nf1e-cVo8g9k_e:b-5geo6n) ([raw file](https://github.com/oscarlab/graphene/blob/2755beaeaa7083a20dfd10ea002b0c82c4260a80/LibOS/shim/test/regression/test_libos.py#L266)):*
> ```Python
>         self._verify_debug_log(log)
> 
>     def _verify_debug_log(self, log: str):
> ```

Won't these tests fail when testing without `DEBUG=1`? Could you verify in such builds that the log doesn't exist/doesn't contain those lines?
___
*[LibOS/shim/test/regression/test_libos.py, line 267 at r3](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMGl2GU8d12y-pEa7nN:-MMGl2GVANpzHnYz02-l:bnwn4r7) ([raw file](https://github.com/oscarlab/graphene/blob/2755beaeaa7083a20dfd10ea002b0c82c4260a80/LibOS/shim/test/regression/test_libos.py#L267)):*
> ```Python
> 
>     def _verify_debug_log(self, log: str):
>         self.assertIn('Host: Linux', log)
> ```

This will fail on non-Linux backends.


<!-- Sent from Reviewable.io -->

2020-11-16 16:30 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: 22 of 24 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/test_libos.py, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMGkfE_77xu6fPoJml9:-MMGrNDFBk2-_nqeocUF:b-bzgauu) ([raw file](https://github.com/oscarlab/graphene/blob/2755beaeaa7083a20dfd10ea002b0c82c4260a80/LibOS/shim/test/regression/test_libos.py#L249)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this isn't needed anymore, you can just run `debug_log_inline` directly and it should work (ditto below)
</blockquote></details>

Okay, but since I did this by copying other tests, I'd like to fix them too. I added a separate commit for that.
___
*[LibOS/shim/test/regression/test_libos.py, line 266 at r3](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMGl7Nf1e-cVo8g9k_d:-MMGpfyb6RhpjYshpSP-:b-w6e2cb) ([raw file](https://github.com/oscarlab/graphene/blob/2755beaeaa7083a20dfd10ea002b0c82c4260a80/LibOS/shim/test/regression/test_libos.py#L266)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Won't these tests fail when testing without `DEBUG=1`? Could you verify in such builds that the log doesn't exist/doesn't contain those lines?
</blockquote></details>

`DEBUG=1` doesn't control log visibility in LibOS, and these messages do show up.

(it does in SGX PAL... it's kind of a mess, but for now I would rather keep the test this way).
___
*[LibOS/shim/test/regression/test_libos.py, line 267 at r3](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMGl2GU8d12y-pEa7nN:-MMGrBkoB1RF5HBietlU:bs11tqm) ([raw file](https://github.com/oscarlab/graphene/blob/2755beaeaa7083a20dfd10ea002b0c82c4260a80/LibOS/shim/test/regression/test_libos.py#L267)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This will fail on non-Linux backends.
</blockquote></details>

Changed to look for `'Host:'`.


<!-- Sent from Reviewable.io -->

2020-11-16 16:54 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-16 17:39 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-16 20:12 UTC, yamahata approved these changes
> Reviewed 11 of 18 files at r1, 11 of 12 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-16 21:21 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-16 22:34 UTC, yamahata submitted a review, later dismissed
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-17 02:18 UTC, boryspoplawski requested changes
> Reviewed 10 of 18 files at r1, 9 of 12 files at r2, 1 of 2 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 39 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIstXtBKFObCXxGobx:-MMIstXtBKFObCXxGoby:bejbvae) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/include/shim_internal.h#L39)):*
> ```objc
> #include "pal_error.h"
> 
> extern bool g_enable_debug_log;
> ```

Imo `g_debug_log_enabled` would be better
___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMItuHm1XhR8jw6L5Jr:b-ljgg9l) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
> ```C
> 
>     while (bytes < size) {
>         PAL_NUM x = DkDebugLog((void*)(buf + bytes), size - bytes);
> ```

This cast is superfluous.
___
*[Pal/include/pal/pal.h, line 365 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIwowR-WbO_fYdiZQi:-MMIwowSBfzfwqUZbnbq:bsdmnkv) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/include/pal/pal.h#L365)):*
> ```objc
>  * used to specify the remote socket address if the handle is a UDP socket.
>  *
>  * \return Returns number of bytes written if succeeded, and PAL_STREAM_ERROR on failure (in which
> ```

Imo you should skip `Returns` and `,` before `and`.
___
*[Pal/include/pal/pal.h, line 690 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIwzKp5F6LN4zwUTjg:-MMIwzKp5F6LN4zwUTjh:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/include/pal/pal.h#L690)):*
> ```objc
>  * `g_pal_control.enable_debug_log`.
>  *
>  * \return Returns number of bytes written if succeeded, and PAL_STREAM_ERROR on failure (in which
> ```

ditto
___
*[Pal/src/host/Linux/db_streams.c, line 369 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyyjd-sNapDahEqM6:-MMIyyjd-sNapDahEqM7:boumj68) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L369)):*
> ```C
> }
> 
> int _DkInitDebugStream(const char* path) {
> ```

Please add a check that `g_debug_fd` is not yet initialized and fail if it is (or just close the old fd).
___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMIyeQl5zCGzr5Eww2-:b-wkpgcp) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
> ```C
> 
> int _DkInitDebugStream(const char* path) {
>     int ret = INLINE_SYSCALL(open, 3, path, O_WRONLY | O_APPEND | O_CREAT, 0600);
> ```

Please change this to `S_*` constants instead of hardcoded number.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 403 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIzWnRCi4dAljPesOR:-MMIzWnRCi4dAljPesOS:b-5dfur0) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux-SGX/db_streams.c#L403)):*
> ```C
> }
> 
> int _DkInitDebugStream(const char* path) {
> ```

ditto (initialization check)
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 404 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIzZ1J252y_qZiJZjI:-MMIzZ1J252y_qZiJZjJ:b-2bf1k1) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux-SGX/db_streams.c#L404)):*
> ```C
> 
> int _DkInitDebugStream(const char* path) {
>     int ret = ocall_open(path, O_WRONLY | O_APPEND | O_CREAT, 0600);
> ```

ditto (hardcoded number)


<!-- Sent from Reviewable.io -->

2020-11-17 02:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @pwmarcz)

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMJ-22r7yQunvb3hUpy:buqrnp3) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change this to `S_*` constants instead of hardcoded number.
</blockquote></details>

Please don't. Those `S_*` constants are unreadable mess, even Linux community is against them. See https://lwn.net/Articles/696231/.


<!-- Sent from Reviewable.io -->

2020-11-17 02:32 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMJ1H0fA73vv8_u07h8:b-iy3zm5) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't. Those `S_*` constants are unreadable mess, even Linux community is against them. See https://lwn.net/Articles/696231/.
</blockquote></details>

I disagree. While `S_*` constant are a mess (I don't like them neither), they are still better than pure octal numbers. I've already seen missing leading `0` (in Graphene too, I believe). While `PERM_rw_______` would look much nicer, we don't have such macros currently.


<!-- Sent from Reviewable.io -->

2020-11-17 02:59 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @pwmarcz)

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMJ6UR09ajghtgqoe95:bl2bsm5) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
> they are still better than pure octal numbers.

I totally disagree, everyone can read octal permissions on Linux, but no one can read this `S_*` mess. The difference in code readability here is really huge.

> I've already seen missing leading `0` (in Graphene too, I believe).

That's easy to check in the review and this is the only possible bug when using octals. With `S_*` you have a bunch of totally random letters glued together, how is this less error prone?

> While `PERM_rw_______` would look much nicer, we don't have such macros currently.

I agree that these are better. `PERM_*` > octals > `S_*`.


<!-- Sent from Reviewable.io -->

2020-11-17 03:19 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMJ9tw96oEHZ0co7BPv:bnf7r0d) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
> I totally disagree, everyone can read octal permissions on Linux, but no one can read this S_* mess. The difference in code readability here is really huge.

And I totally disagree whit that. Give me `0142` and I have no idea what permission is that. Otoh `S_IXUSR | S_IRGRP | S_IWOTH` is ugly, but self contained, I can easily read what the permissions will be.

> That's easy to check in the review and this is the only possible bug when using octals. With S_* you have a bunch of totally random letters glued together, how is this less error prone?

Easy, yet somehow sometimes slips through. I disagree they are totally random, `S_IWOTH`: `S_I` - this is the problematic part, wth it stands for I do not know, but it's constant, so you can just ignore it, `W` - write, `OTH` - others. If you write `S_JWOTH` it won't even compile, where as if you write `0776`, who know's if that's a bug or intended.

>I agree that these are better. PERM_* > octals > S_*.

`PERM_*` >>> `S_I*` > octals


<!-- Sent from Reviewable.io -->

2020-11-17 07:09 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-11-17 10:47 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 39 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIstXtBKFObCXxGobx:-MMKi_b--LV2kfKVlKYI:b3e7tmb) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/include/shim_internal.h#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Imo `g_debug_log_enabled` would be better
</blockquote></details>

It's called this way because it comes from `pal_control.enable_debug_log` field, and that structure as `disable_aslr` already. Do you think it's worth it to change it only here (so that we have something like `g_debug_log_enabled = pal_control.enable_debug_log`)?
___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMKjMvr88IVDNI7knXt:b2177g5) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This cast is superfluous.
</blockquote></details>

It's not, because we are dropping `const`:
```
utils/printf.c: In function 'debug_fputs':
utils/printf.c:20:32: error: passing argument 1 of 'DkDebugLog' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
         PAL_NUM x = DkDebugLog((buf + bytes), size - bytes);
                                ^
In file included from utils/printf.c:9:0:
../../../Pal/include/pal/pal.h:693:9: note: expected 'PAL_PTR {aka void *}' but argument is of type 'const char *'
 PAL_NUM DkDebugLog(PAL_PTR buffer, PAL_NUM size);
         ^~~~~~~~~~
```
___
*[Pal/include/pal/pal.h, line 365 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIwowR-WbO_fYdiZQi:-MMKkMsZEyHRoKI5c12S:bm3yqt3) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/include/pal/pal.h#L365)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Imo you should skip `Returns` and `,` before `and`.
</blockquote></details>

OK, done.
___
*[Pal/include/pal/pal.h, line 690 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIwzKp5F6LN4zwUTjg:-MMKkQco8x1HdDfuR-df:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/include/pal/pal.h#L690)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_streams.c, line 369 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyyjd-sNapDahEqM6:-MMKluxt1PTaKGcm0I59:bcpnu0h) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L369)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a check that `g_debug_fd` is not yet initialized and fail if it is (or just close the old fd).
</blockquote></details>

I added a close.
___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMKmMGFAnfGqaDnQbPO:b-tp3cn9) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> I totally disagree, everyone can read octal permissions on Linux, but no one can read this S_* mess. The difference in code readability here is really huge.

And I totally disagree whit that. Give me `0142` and I have no idea what permission is that. Otoh `S_IXUSR | S_IRGRP | S_IWOTH` is ugly, but self contained, I can easily read what the permissions will be.

> That's easy to check in the review and this is the only possible bug when using octals. With S_* you have a bunch of totally random letters glued together, how is this less error prone?

Easy, yet somehow sometimes slips through. I disagree they are totally random, `S_IWOTH`: `S_I` - this is the problematic part, wth it stands for I do not know, but it's constant, so you can just ignore it, `W` - write, `OTH` - others. If you write `S_JWOTH` it won't even compile, where as if you write `0776`, who know's if that's a bug or intended.

>I agree that these are better. PERM_* > octals > S_*.

`PERM_*` >>> `S_I*` > octals
</blockquote></details>

So what do we do? I'm happy to change to `S_I*` but please agree on something.

The current code has a pretty even split between octal permissions and `S_*`. Also, the [coding style](https://graphene.readthedocs.io/en/latest/devel/coding-style.html) document currently has an example with `0600` :)

`PERM_*` looks nice but from what I can see the linked patch did not go forward? If we do introduce it, I think it should be in a separate PR that also converts existing code.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 403 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIzWnRCi4dAljPesOR:-MMKlycI0x3goFWKW340:b-16uuh6) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux-SGX/db_streams.c#L403)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (initialization check)
</blockquote></details>

I added a close, same as above.


<!-- Sent from Reviewable.io -->

2020-11-17 14:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMLZTjS9DAKRoaVjFns:boi4vi2) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's not, because we are dropping `const`:
```
utils/printf.c: In function 'debug_fputs':
utils/printf.c:20:32: error: passing argument 1 of 'DkDebugLog' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
         PAL_NUM x = DkDebugLog((buf + bytes), size - bytes);
                                ^
In file included from utils/printf.c:9:0:
../../../Pal/include/pal/pal.h:693:9: note: expected 'PAL_PTR {aka void *}' but argument is of type 'const char *'
 PAL_NUM DkDebugLog(PAL_PTR buffer, PAL_NUM size);
         ^~~~~~~~~~
```
</blockquote></details>

Can you add `const` to the API then? Those `PAL_*` types will go away anyways, they don't make any sense.
___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMLZdEq1pkT9U5TFZxM:b-wdnlzn) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

So what do we do? I'm happy to change to `S_I*` but please agree on something.

The current code has a pretty even split between octal permissions and `S_*`. Also, the [coding style](https://graphene.readthedocs.io/en/latest/devel/coding-style.html) document currently has an example with `0600` :)

`PERM_*` looks nice but from what I can see the linked patch did not go forward? If we do introduce it, I think it should be in a separate PR that also converts existing code.
</blockquote></details>

@dimakuv @yamahata What's your preference here?


<!-- Sent from Reviewable.io -->

2020-11-17 14:22 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 39 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIstXtBKFObCXxGobx:-MMLYtbv2wSy6yRquTX8:bvifuf3) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/include/shim_internal.h#L39)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's called this way because it comes from `pal_control.enable_debug_log` field, and that structure as `disable_aslr` already. Do you think it's worth it to change it only here (so that we have something like `g_debug_log_enabled = pal_control.enable_debug_log`)?
</blockquote></details>

Yeah, that would be fine
___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMLZwhYDqpvsVWXN3FH:ba3dk63) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can you add `const` to the API then? Those `PAL_*` types will go away anyways, they don't make any sense.
</blockquote></details>

Then it's a question why Pal API does not have const ...
But I guess it's an existing problem, so unblocking
___
*[Pal/include/pal/pal.h, line 365 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIwowR-WbO_fYdiZQi:-MML_CYZ3TPn1ZKBlXiU:b-4zwpsz) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/include/pal/pal.h#L365)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, done.
</blockquote></details>

Did you forgot to push your changes? :)


<!-- Sent from Reviewable.io -->

2020-11-17 14:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMLa3s99cwB0WbsjZEi:b-2biob4) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
> Then it's a question why Pal API does not have const ...

I don't know any reason, all those typedefs doesn't make any sense. We should be just using proper C types there.


<!-- Sent from Reviewable.io -->

2020-11-17 14:27 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 8 unresolved discussions (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMLaBx_1rG4xDEmFW8f:bblphbt) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv @yamahata What's your preference here?
</blockquote></details>

I used `S_*` in my code. So slight preference for macros, but I don't care much.


<!-- Sent from Reviewable.io -->

2020-11-17 15:44 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: 16 of 24 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 39 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIstXtBKFObCXxGobx:-MMLnrRSEtW0oaDe5R3f:bm3yqt3) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/include/shim_internal.h#L39)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, that would be fine
</blockquote></details>

OK, done.
___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMLnvlO2n3urhFGxUc6:b-4nzn9p) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
Okay... I assumed these are all `PAL_PTR` instead of proper pointer types for a good reason :)

>Can you add const to the API then? Those PAL_* types will go away anyways, they don't make any sense.

I would rather not. That would mean either using `const PAL_PTR`, `const void*` or `const char*`. None these appear in`pal.h` which uses `PAL_*` types exclusively (there is some usage of `const PAL_PTR` in two internal functions, but even these do not have `const` in headers, just implementation).

If there is no good reason for using `PAL_PTR`, `PAL_NUM` etc., then of course, let's change that in bulk (for example, file-by-file?), but adding one function to `pal.h` that is different from everything else feels like a bad way to do it.
___
*[Pal/include/pal/pal.h, line 365 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIwowR-WbO_fYdiZQi:-MMLn1AMENQtUKSdxVI3:b-qvsz5x) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/include/pal/pal.h#L365)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Did you forgot to push your changes? :)
</blockquote></details>

Yeah... I think I did one rebase too many or something. Anyway, I pushed the new commits now.
___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMLrB-l8_KsbxH4n6Iw:b-7sws6u) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I used `S_*` in my code. So slight preference for macros, but I don't care much.
</blockquote></details>

Then, in the interest of moving this forward, let's go with `S_*` here? I updated the code.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 404 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIzZ1J252y_qZiJZjI:-MMLr_TD6jeH-XngxLJM:b-av1uo0) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux-SGX/db_streams.c#L404)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (hardcoded number)
</blockquote></details>

Changed to `S_*`.


<!-- Sent from Reviewable.io -->

2020-11-17 15:57 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMLtg8Q-WlyZ8Brb279:btblzbm) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay... I assumed these are all `PAL_PTR` instead of proper pointer types for a good reason :)

>Can you add const to the API then? Those PAL_* types will go away anyways, they don't make any sense.

I would rather not. That would mean either using `const PAL_PTR`, `const void*` or `const char*`. None these appear in`pal.h` which uses `PAL_*` types exclusively (there is some usage of `const PAL_PTR` in two internal functions, but even these do not have `const` in headers, just implementation).

If there is no good reason for using `PAL_PTR`, `PAL_NUM` etc., then of course, let's change that in bulk (for example, file-by-file?), but adding one function to `pal.h` that is different from everything else feels like a bad way to do it.
</blockquote></details>

I agree with Paweł, this is not the place for such change.
___
*[Pal/src/host/Linux/db_streams.c, line 371 at r6](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMLu5oHEJqimG4XcLqb:-MMLu5oI8m21PEutkaTz:b-itxax9) ([raw file](https://github.com/oscarlab/graphene/blob/5a361bee8b87ed2cf461b0d97788e4e8098a272b/Pal/src/host/Linux/db_streams.c#L371)):*
> ```C
> int _DkInitDebugStream(const char* path) {
>     if (g_debug_fd >= 0) {
>         INLINE_SYSCALL(close, 1, g_debug_fd);
> ```

Please add error checking (I know, it's `close`, but still)
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 405 at r6](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMLvHhBEXi4wZL5c4GF:-MMLvHhCCYBZp2E9bwRQ:b-dw3cqm) ([raw file](https://github.com/oscarlab/graphene/blob/5a361bee8b87ed2cf461b0d97788e4e8098a272b/Pal/src/host/Linux-SGX/db_streams.c#L405)):*
> ```C
> int _DkInitDebugStream(const char* path) {
>     if (g_debug_fd >= 0) {
>         ocall_close(g_debug_fd);
> ```

Please add error checking


<!-- Sent from Reviewable.io -->

2020-11-17 16:00 UTC, mkow approved these changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/utils/printf.c, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMItuHl5hP0j1kq5qVY:-MMLv0fbEzjUqWbLSkIU:b-i0hchr) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/LibOS/shim/src/utils/printf.c#L20)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay... I assumed these are all `PAL_PTR` instead of proper pointer types for a good reason :)

>Can you add const to the API then? Those PAL_* types will go away anyways, they don't make any sense.

I would rather not. That would mean either using `const PAL_PTR`, `const void*` or `const char*`. None these appear in`pal.h` which uses `PAL_*` types exclusively (there is some usage of `const PAL_PTR` in two internal functions, but even these do not have `const` in headers, just implementation).

If there is no good reason for using `PAL_PTR`, `PAL_NUM` etc., then of course, let's change that in bulk (for example, file-by-file?), but adding one function to `pal.h` that is different from everything else feels like a bad way to do it.
</blockquote></details>

Yeah, but dropping const sounds even worse to me ;) Anyways, I'm unblocking this discussion.
___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMLvUIY92Kb4LEswng-:bk0iihs) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Then, in the interest of moving this forward, let's go with `S_*` here? I updated the code.
</blockquote></details>

Ugly :P
@pwmarcz Would you have time to create a quick PR afterwards and introduce `PERM_*` macros?


<!-- Sent from Reviewable.io -->

2020-11-17 16:39 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: 22 of 24 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMM-exE6HVRaSVitwlg:b-yikse8) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
Some cleanup in headers was necessary to get `#include <linux/stat.h>` to work.

>@pwmarcz Would you have time to create a quick PR afterwards and introduce PERM_* macros?

OK, I'll either create a PR or an issue.
___
*[Pal/src/host/Linux/db_streams.c, line 371 at r6](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMLu5oHEJqimG4XcLqb:-MMM3bn1CHe2MeSBs3B3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a361bee8b87ed2cf461b0d97788e4e8098a272b/Pal/src/host/Linux/db_streams.c#L371)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add error checking (I know, it's `close`, but still)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_streams.c, line 405 at r6](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMLvHhBEXi4wZL5c4GF:-MMM3e668_g6sM6Fo8K-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a361bee8b87ed2cf461b0d97788e4e8098a272b/Pal/src/host/Linux-SGX/db_streams.c#L405)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add error checking
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 16:48 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-17 17:04 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMM9L-45xZAdSJuWUQs:b-1k0d9q) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Some cleanup in headers was necessary to get #include <linux/stat.h> to work.

Aaand it doesn't compile under Ubuntu 16. This is becoming too big of a time waste here, so we agreed with @boryspoplawski to admit defeat and keep this as octal for now.
</blockquote></details>

Yeah, Graphene includes are a big mess right now ...


<!-- Sent from Reviewable.io -->

2020-11-17 17:12 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux/db_streams.c, line 370 at r5](https://reviewable.io/reviews/oscarlab/graphene/1965#-MMIyeQl5zCGzr5Eww1z:-MMMAy0h2eIgi1ODCnoH:b-vfgm4a) ([raw file](https://github.com/oscarlab/graphene/blob/369acc2e1267653eba8e7573e251431a2c961e77/Pal/src/host/Linux/db_streams.c#L370)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, Graphene includes are a big mess right now ...
</blockquote></details>

yay! :partying_face: :)


<!-- Sent from Reviewable.io -->

2020-11-17 21:47 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 4 files at r5, 6 of 8 files at r6, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-17 23:00 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-17 23:05 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-17 23:11 UTC, yamahata submitted a review, later dismissed
> Reviewed 6 of 8 files at r6, 2 of 2 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-17 23:35 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-17 23:36 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-18 01:24 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-18 07:05 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1965)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-18 07:11 UTC, merged