Add support for /sys pseudo-filesystem support
oscarlab/graphene pull request #1975
Opened 2020-11-18 04:47 UTC by vijaydhanraj

## Description of the changes 
This PR adds support for /sys pseudo-filesystem which in turn helps to enable open-source libraries such as "Hardware Locality" to relay underlying hardware topology-related information to applications. This is critical for ML benchmarks which seem to use topology-related info for better scheduling of threads.

Fixes #1783
Closes #1970 

## How to test this PR? 
Please use the newly added regression test "sysfs_common.c" to test the PR. Another option would be to run openVINO benchmark_app which exercises lot flows introduced in this PR.

2020-11-19 10:45 UTC, dimakuv requested changes
> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 66 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/fs/proc/thread.c, line 651 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUsDxD9IvgqGfKkfV1:-MMUsDxD9IvgqGfKkfV2:b6v3qlj) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/proc/thread.c#L651)):*
> ```C
>     buf->st_size = 4096;
>     /* Libs like "hwloc" uses /proc/../task to estimate number of tids. So created a dummy of 3 for
>      * ., .. and one tid*/
> ```

Does this mean that hwloc may decide that there is only one thread in the app? And it will lead to always running single-threaded? If yes, then we need to either fix this (to return a proper number) or at least add a `TODO/FIXME` in the comment.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUuyL30s0Q20v_Yf0e:-MMUuyL30s0Q20v_Yf0f:b40sdpf) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L5)):*
> ```C
> 
> /*
>  * This file contains the implementation of `/sys/devices/system/cpu/cpuX/cache`
> ```

` and its subdirectories.`
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUtCn16PGGDzs3R4Y2:-MMUtCn216cVNaWvF8fJ:b-pupo71) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L18)):*
> ```C
>     char* str = malloc(SYSFS_FILESZ);
>     if (!str)
>         return -ENOMEM;
> ```

You will have a leak of `str` in this function. Just move this malloc close to where you actually start using `str` and don't forget to free it on all return paths.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUtk16Bi_Kb2_-tTmw:-MMUtk16Bi_Kb2_-tTmx:bsj2kdh) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L36)):*
> ```C
>     if (!strcmp(filename, "shared_cpu_map")) {
>         cache_filebuf = pal_control.topo_info.core_topology[cpunum].cache[idx].shared_cpu_map;
> ```

Why do you have these empty lines? Please remove.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUtziR0zI7wsJRWZWi:-MMUtziR0zI7wsJRWZWj:b-cr6to6) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L56)):*
> ```C
> 
>     } else {
>         debug("Unsupported Filepath %s\n", name);
> ```

Better `Unrecognized file %s`
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUu2Hl0DiQfMoii3OQ:-MMUu2Hl0DiQfMoii3OR:bn6jx3k) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L60)):*
> ```C
>     }
> 
>     len =  strlen(cache_filebuf) + 1;
> ```

You have double-space, please remove one
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUuEVM-Xna-9dSkQ6F:-MMUuEVM-Xna-9dSkQ6G:b-v098qs) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L63)):*
> ```C
>     memcpy(str, cache_filebuf, len);
> 
>     struct shim_str_data* data = malloc(sizeof(struct shim_str_data));
> ```

Please use `sizeof(*data)`. Also, you can use `calloc` and skip `memset` below.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUuUd9AjPESp3yFZlU:-MMUuUdA1LOREJ9D52yo:bvkf1r1) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L73)):*
> ```C
>     data->len          = len;
>     hdl->type          = TYPE_STR;
>     hdl->flags         = flags & ~O_RDONLY;
> ```

This looks random, but I understand that you copied it from a similar place. So yes, let's deal with it in another PR.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUv7bQAzpu56rhLKjg:-MMUv7bQAzpu56rhLKjh:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L17)):*
> ```C
>     size_t len;
>     char filename[32];
>     char* str = malloc(SYSFS_FILESZ);
> ```

ditto
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUv9yL5ddm4FZQTXbZ:-MMUv9yL5ddm4FZQTXb_:bqq0qj2) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L27)):*
> ```C
> 
>     int cpunum = extract_num_from_path(name);
>     if (cpunum < 0 )
> ```

Redundant space
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvECYAR9PudbBH281:-MMUvECYAR9PudbBH282:b6i2mct) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L31)):*
> ```C
> 
>     const char* cpu_filebuf;
>     char temp_buf[4];
> ```

You use this in only one place, could you move it inside there?

Also, can we increment to `16`, otherwise we only have 3-digit numbers which could overflow...
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvUaY09c7ty0dexwO:-MMUvUaY09c7ty0dexwP:b3s3lfu) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L33)):*
> ```C
>     char temp_buf[4];
>     if (!strcmp(filename, "online")) {
>         if (strstr(name, "cpu/cpu"))
> ```

This need an explanation comment. Smth like `/* distinguish between /sys/devices/system/cpu/online and /sys/devices/system/cpu/cpuX/online */`
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvO589bT12lYy3zXW:-MMUvO589bT12lYy3zXX:b-7mo7d7) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L37)):*
> ```C
>         else
>             cpu_filebuf = pal_control.topo_info.online_logical_cores;
> ```

Remove empty lines
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvs0V4I5pNe2XZI5u:-MMUvs0V4I5pNe2XZI5v:bw942v0) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L45)):*
> ```C
> 
>     } else if (!strcmp(filename, "physical_package_id")) {
>         /* we have already collected this info as part of /proc/cpuinfo. So reuse it */
> ```

Is it guaranteed that `pal_control.cpu_info` is populated (even if the user didn't open `/proc/cpuinfo`)?
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUwUgT-9KhLL7wHeHN:-MMUwUgU7Th4PMRZYMCM:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L56)):*
> ```C
> 
>     } else {
>         debug("Unsupported Filepath %s\n", name);
> ```

ditto
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUwX7Z4Q8Osy5WkdP_:-MMUwX7Z4Q8Osy5WkdPa:b-e09jxo) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L6 [...]

2020-11-20 01:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 18 of 30 files reviewed, 66 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/proc/thread.c, line 651 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUsDxD9IvgqGfKkfV1:-MMWUbOa6JAfR4jW8Jey:b8ljfsv) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/proc/thread.c#L651)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does this mean that hwloc may decide that there is only one thread in the app? And it will lead to always running single-threaded? If yes, then we need to either fix this (to return a proper number) or at least add a `TODO/FIXME` in the comment.
</blockquote></details>

No, hwloc uses this as an initial estimate for tid and dynamically increases as it finds more when doing a `readdir` of `/proc/..tid`. But I will add the FIXME as the current implementation only helps hwloc. We might need a more generic solution.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUuyL30s0Q20v_Yf0e:-MMWZjkO5ZHfGU9XFeqc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

` and its subdirectories.`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUtCn16PGGDzs3R4Y2:-MMW_mx7A1oQAO6Y_n89:bmdqgfu) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You will have a leak of `str` in this function. Just move this malloc close to where you actually start using `str` and don't forget to free it on all return paths.
</blockquote></details>

yes moved it closer to the usage. This also takes care of freeing it on return paths.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUtk16Bi_Kb2_-tTmw:-MMWbDes4vYMcJbVYehf:brbzva7) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have these empty lines? Please remove.
</blockquote></details>

Thought it will be more readable. But have removed it.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUtziR0zI7wsJRWZWi:-MMWtOV82FdEvleCFcML:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Better `Unrecognized file %s`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUu2Hl0DiQfMoii3OQ:-MMWtat5D7Gabkm6kGCx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have double-space, please remove one
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUuEVM-Xna-9dSkQ6F:-MMX3apI21W7tKNc7jbB:b-szhbky) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `sizeof(*data)`. Also, you can use `calloc` and skip `memset` below.
</blockquote></details>

sure, done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUuUd9AjPESp3yFZlU:-MMX3e-I-G5rOyrIv3A3:b-5inzjz) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cache_info.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks random, but I understand that you copied it from a similar place. So yes, let's deal with it in another PR.
</blockquote></details>

yes, followed existing implementation.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUv7bQAzpu56rhLKjg:-MMX5pKOE47jpSh-PnJ_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUv9yL5ddm4FZQTXbZ:-MMX6JQ0Au1zZrnjVQBw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Redundant space
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvECYAR9PudbBH281:-MMX8Kd26xFkWcajCYfz:b-ho5f52) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You use this in only one place, could you move it inside there?

Also, can we increment to `16`, otherwise we only have 3-digit numbers which could overflow...
</blockquote></details>

yeah, this was on purpose. I didn't think there were platforms with more than 999 sockets. Anyways have changed it to `16`.  Also, have moved the declaration of `temp_buf` closer to usage.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvUaY09c7ty0dexwO:-MMX9niqAdXXzAiKLAfF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This need an explanation comment. Smth like `/* distinguish between /sys/devices/system/cpu/online and /sys/devices/system/cpu/cpuX/online */`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvO589bT12lYy3zXW:-MMX9sVr2FoiOEG9pjs_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove empty lines
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUvs0V4I5pNe2XZI5u:-MMXAr3Z39iy8ebiPFYA:b-jle19o) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/cpu_info.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it guaranteed that `pal_control.cpu_info` is populated (even if t [...]

2020-11-20 09:55 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MM_3x9w-UJ_6LtWebPV:-MM_3x9w-UJ_6LtWebPW:bsf7tuz) (no related file):*
Note to myself: do another round of comprehensive review.

---
___
*[LibOS/shim/src/fs/proc/thread.c, line 651 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUsDxD9IvgqGfKkfV1:-MM_-i-p9FltvCOaqYs9:b-mr2kto) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/proc/thread.c#L651)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No, hwloc uses this as an initial estimate for tid and dynamically increases as it finds more when doing a `readdir` of `/proc/..tid`. But I will add the FIXME as the current implementation only helps hwloc. We might need a more generic solution.
</blockquote></details>

Ok, slight rewording:
```
    /* FIXME: Libs like hwloc use /proc/[..]/task to estimate the number of TIDs (but later dynamically
     * increase it if needed). Currently we set nlink to 3 (for ".", ".." and one TID); need a more
     * generic solution. */
```
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1975#-MM_0pUa41Pqv9mdvtr4:-MM_0pUa41Pqv9mdvtr5:b2be6ek) ([raw file](https://github.com/oscarlab/graphene/blob/e96cc5034e7a2ebda3aaf258c5b0bcd7e3608ca2/LibOS/shim/src/fs/sys/cpu_info.c#L39)):*
> ```C
>     } else if (!strcmp(filename, "physical_package_id")) {
>         /* we have already collected this info as part of /proc/cpuinfo. So reuse it */
>         char temp_buf[16];
> ```

Oops, sorry, we can't move it here. `temp_buf` may be popped off the stack after `cpu_filebuf = temp_buf;` line and we'll end up having stack garbage in `cpu_filebuf`. Let's move it back and put a note that it has to stay on stack for the duration of this function.
___
*[LibOS/shim/src/fs/sys/fs.c, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUykVt-KuV3WPrLqZp:-MM_1UdC3mfHcocdqYJy:bil130c) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/fs.c#L83)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I have initialized ret to 1 already. Please check.
</blockquote></details>

Yeah, I know. Ok, let's keep it like this, the function is short enough. (I prefer to assign a return value explicitly right-before the return, otherwise the reader has to scroll all the way up to check the value.)
___
*[LibOS/shim/src/fs/sys/fs.c, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMV-_vY6ZJHorJ1CeoK:-MM_2HNZAYPotvSLEb0l:b-596huh) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/fs.c#L171)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Didn't want to forget why we put 4 in the generic function. So added the comment.

yes, `cpuX` can have many directories but at least hwloc didn't seem to use this approach to count the number of cpus.  `st_nlink` was a don't care except for `/sys/devices/system/node/nodeX/hugepages` so set dummy value to 4. `hwloc` uses this to `malloc` and `memset` hugepage types. Another option would be to duplicate this function just for `hugepages` dir and leave `st_nlink` to 0 in this function.

Modified comment as below. Does this look better?
```
    /* FIXME: Need more generic solution. But setting this to 4, as libs like "hwloc" uses this
     * information to allocate memory based on number of hugepage types (., .., hugepages-2048kB,
     * hugepages-1048576kB).
     */
```
</blockquote></details>

Ok, slight rewording:
```
    /* FIXME: Libs like hwloc assume that nlink is 4 for paths like /sys/devices/system/node/nodeX/hugepages
     * (".", "..", "hugepages-2048kB", "hugepages-1048576kB"). Thus we currently set nlink to 4; need a more
     * generic solution. */
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/1975#-MM_1NpXBlhcJ1Sr-8rN:-MM_1NpXBlhcJ1Sr-8rO:b-btx71g) ([raw file](https://github.com/oscarlab/graphene/blob/e96cc5034e7a2ebda3aaf258c5b0bcd7e3608ca2/LibOS/shim/src/fs/sys/fs.c#L49)):*
> ```C
>     int ret = 1;
> 
>     /* Duplicate pathname as this will be modifed when extracting path token */
> ```

`modified`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 318 at r2](https://reviewable.io/reviews/oscarlab/graphene/1975#-MM_3_WzAhcFTdsOfhQV:-MM_3_X-DSCzYkZMXhBX:bhvbcxc) ([raw file](https://github.com/oscarlab/graphene/blob/e96cc5034e7a2ebda3aaf258c5b0bcd7e3608ca2/Pal/src/host/Linux-SGX/db_main.c#L318)):*
> ```C
>     int num_cache_index = sec_info.topo_info.num_cache_index;
>     if (num_cache_index < 1 || num_cache_index >= (1 << 4)) {
>         SGX_DBG(DBG_E, "Invalid sec_info.topo_info.num_cache_index: %d\n", num_online_nodes);
> ```

Why do you have `num_online_nodes` here?


<!-- Sent from Reviewable.io -->

2020-11-20 16:32 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/fs/proc/thread.c, line 651 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMUsDxD9IvgqGfKkfV1:-MMaQg_jBNXRZwEVc--d:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/proc/thread.c#L651)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, slight rewording:
```
    /* FIXME: Libs like hwloc use /proc/[..]/task to estimate the number of TIDs (but later dynamically
     * increase it if needed). Currently we set nlink to 3 (for ".", ".." and one TID); need a more
     * generic solution. */
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/1975#-MM_0pUa41Pqv9mdvtr4:-MMaQk-d7rHAtrcgOCov:b-k9f7mn) ([raw file](https://github.com/oscarlab/graphene/blob/e96cc5034e7a2ebda3aaf258c5b0bcd7e3608ca2/LibOS/shim/src/fs/sys/cpu_info.c#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, sorry, we can't move it here. `temp_buf` may be popped off the stack after `cpu_filebuf = temp_buf;` line and we'll end up having stack garbage in `cpu_filebuf`. Let's move it back and put a note that it has to stay on stack for the duration of this function.
</blockquote></details>

yes, I will move it back to the larger scope.
___
*[LibOS/shim/src/fs/sys/fs.c, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMV-_vY6ZJHorJ1CeoK:-MMaRq5M6m-bxI6rspYS:b-78qjwd) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/fs.c#L171)):*
>     /* FIXME: Libs like hwloc assume that nlink is 4 for paths like /sys/devices/system/node/nodeX/hugepages
>      * (".", "..", "hugepages-2048kB", "hugepages-1048576kB"). Thus we currently set nlink to 4; need a more
>      * generic solution. */
Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/1975#-MM_1NpXBlhcJ1Sr-8rN:-MMaRyIjCrfoZEW3nU2V:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e96cc5034e7a2ebda3aaf258c5b0bcd7e3608ca2/LibOS/shim/src/fs/sys/fs.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`modified`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 318 at r2](https://reviewable.io/reviews/oscarlab/graphene/1975#-MM_3_WzAhcFTdsOfhQV:-MMaRzlyE1QIC33vu8Sd:b-oar3gt) ([raw file](https://github.com/oscarlab/graphene/blob/e96cc5034e7a2ebda3aaf258c5b0bcd7e3608ca2/Pal/src/host/Linux-SGX/db_main.c#L318)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have `num_online_nodes` here?
</blockquote></details>

typo, it should have been `num_cache_index`


<!-- Sent from Reviewable.io -->

2020-11-21 14:30 UTC, aneessahib commented
@vijaydhanraj i rebased this with master locally to look for any improvements with java workloads,, but ran into compilation issues in sys/fs.c . pls check.

2020-11-21 17:51 UTC, vijaydhanraj commented
> @vijaydhanraj i rebased this with master locally to look for any improvements with java workloads,, but ran into compilation issues in sys/fs.c . pls check.

Hi @aneessahib, we usually don't rebase until the review is complete (or until the reviewer's request) but just add fixups to address the reviewer's comments. This is done so that the history of changes won't be lost. Given this, there can be issues when rebasing to the latest master. But if you want to quickly try this out, please directly use my branch itself instead of rebasing to laster master. 

The following steps can help.
1. git clone https://github.com/vijaydhanraj/graphene.git
2. git fetch origin vdhanraj/add-sysfs-support_v1
3. git checkout -t origin/vdhanraj/add-sysfs-support_v1
4. Usual make and test your changes.

2020-11-23 08:42 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoG1ep2IuDC8GBIU6C:-MMoG1ep2IuDC8GBIU6D:bo4hq9z) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
> ```C
>         return -ENOENT;
> 
>     /* This needs to stay on stack until duration of the this function. */
> ```

`... on stack for the whole duration of this function. */`


<!-- Sent from Reviewable.io -->

2020-11-23 10:39 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs.h, line 486 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoWixE3XtTdRgLau61:-MMoWixF7VSIl7L6f-ei:b-y85nfy) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/include/shim_fs.h#L486)):*
> ```objc
> #define FILE_R_MODE  0444
> 
> #define SYSFS_FILESZ    256
> ```

Please leave only one space
___
*[LibOS/shim/include/shim_fs.h, line 561 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoWo2B7EoEsyrftstK:-MMoWo2B7EoEsyrftstL:bxtsoy1) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/include/shim_fs.h#L561)):*
> ```objc
> int str_flush(struct shim_handle* hdl);
> 
> /* /sys fs related common APIs*/
> ```

Add space after `APIs`
___
*[LibOS/shim/src/Makefile, line 82 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoWvFV2qZq7GQJtb7i:-MMoWvFV2qZq7GQJtb7j:b9len4e) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/Makefile#L82)):*
> ```Makefile
> 	fs/sys/cpu_info.o \
> 	fs/sys/cache_info.o \
> 	fs/sys/node_info.o \
> ```

These four are not sorted
___
*[LibOS/shim/src/fs/shim_fs.c, line 161 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoX5uy3FhYRaF0N8KN:-MMoX5uy3FhYRaF0N8KO:bvmn5md) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/shim_fs.c#L161)):*
> ```C
>     }
> 
>     debug("mounting as sys filesystem: /sys\n");
> ```

Start with capital letter
___
*[LibOS/shim/src/fs/shim_fs.c, line 164 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoX2gO8WiBnMnUk_MJ:-MMoX2gO8WiBnMnUk_MK:bvmn5md) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/shim_fs.c#L164)):*
> ```C
> 
>     if ((ret = mount_fs("sys", NULL, "/sys", root, NULL, 0)) < 0) {
>         debug("mounting sys filesystem failed (%d)\n", ret);
> ```

Start with capital letter
___
*[LibOS/shim/src/fs/proc/thread.c, line 742 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoXCsW2UfEFVHtg1eY:-MMoXCsW2UfEFVHtg1eZ:b-sh05bn) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/proc/thread.c#L742)):*
> ```C
>                 .type     = LINUX_DT_DIR,
>             },
>         },
> ```

Could you condense this `.ent` entry? Like below, hopefully in one line.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoXuxkAMWiTjLXkHQj:-MMoXuxkAMWiTjLXkHQk:b-bkk4kp) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/cache_info.c#L54)):*
> ```C
>     if (!str)
>         return -ENOMEM;
>     memcpy(str, cache_filebuf, len);
> ```

How can we be sure that `len < SYSFS_FILESZ`? This memcpy looks dangerous, we could have a buffer overwrite... Maybe we should add `assert(len < SYSFS_FILESZ)`?
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoG1ep2IuDC8GBIU6C:-MMoYOq1-wbZUa_EVpGY:b-eoo4v2) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`... on stack for the whole duration of this function. */`
</blockquote></details>

Actually, it is unclear what "This" refers to. Replace `This` -> `temp_buf`.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 56 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoYb6081XdQYxEZssV:-MMoYb6081XdQYxEZssW:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/cpu_info.c#L56)):*
> ```C
>     if (!str)
>         return -ENOMEM;
>     memcpy(str, cpu_filebuf, len);
> ```

ditto
___
*[LibOS/shim/src/fs/sys/fs.c, line 122 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_2hA67jAP9LFoirN:-MMo_2hA67jAP9LFoirO:bs6ipjv) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/fs.c#L122)):*
> ```C
>         dirent_in_buf->ino  = 1;
>         dirent_in_buf->type = LINUX_DT_DIR;
>         dirent_in_buf  = dirent_in_buf->next;
> ```

Remove one space here
___
*[LibOS/shim/src/fs/sys/node_info.c, line 45 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo__PI3XuZmiKaXTC8:-MMo__PI3XuZmiKaXTC9:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/node_info.c#L45)):*
> ```C
>     if (!str)
>         return -ENOMEM;
>     memcpy(str, node_filebuf, len);
> ```

ditto
___
*[Pal/include/arch/x86_64/pal-arch.h, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_w207iqWT9ld8kWA:-MMo_w207iqWT9ld8kWB:b-7bq11i) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L30)):*
> ```objc
> /* Used to represent plain integers (only numeric values) */
> #define PAL_SYSFS_INT_FILESZ      16
> /* Used to represent buffers having numeric values with text. E.g 1024576 KB */
> ```

Please add `"` around the example
___
*[Pal/include/arch/x86_64/pal-arch.h, line 32 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_yWe3hVSM_h2kBdx:-MMo_yWe3hVSM_h2kBdy:b-se4yc7) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L32)):*
> ```objc
> /* Used to represent buffers having numeric values with text. E.g 1024576 KB */
> #define PAL_SYSFS_BUF_FILESZ      64
> /* used to represent cpumaps like 00000000,ffffffff,00000000,ffffffff */
> ```

Please add `"` around the example. And start with capital letter.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 33 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_r4V0DRp0xOJEoCz:-MMo_r4WDdKXU3kBYrI5:b-kkx79w) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L33)):*
> ```objc
> #define PAL_SYSFS_BUF_FILESZ      64
> /* used to represent cpumaps like 00000000,ffffffff,00000000,ffffffff */
> #define PAL_SYSFS_MAP_FILESZ      256
> ```

Please remove redundant spaces in these three macros
___
*[Pal/include/arch/x86_64/pal-arch.h, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoaLjeApruHQoIgY6C:-MMoaLjeApruHQoIgY6D:bdqkmhg) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L249)):*
> ```objc
> 
> /* This struct takes ~1.6KB. On a single socket, 4 logical core system, with 3 cache levels
>  * it would take ~8KB in memory. */
> ```

Actually, could you add one more example: with a dual-socket 160-core system?
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 238 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoap2KB2UQQQBqSp1m:-MMoap2KB2UQQQBqSp1n:b-n0nqko) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux/db_main-x86_64.c#L238)):*
> ```C
>     ret = get_numa_topo_info(topo_info);
>     if (ret < 0)
>         return unix_to_pal_error(ERRNO(ret));
> ```

When `get_numa_topo_info()` fails, we need to free all resources that were allocated inside `get_core_topo_info()`.
___
*[Pal/src/host/Linux-common/topo_info.c, line 74 at r3](https://reviewa [...]

2020-11-23 22:16 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs.h, line 486 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoWixE3XtTdRgLau61:-MMqjs721MQcFgrvI-yb:b-nswhge) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/include/shim_fs.h#L486)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please leave only one space
</blockquote></details>

Removed this, as we can directly use `len` variable in the respective functions to allocate memory. Please refer below.
___
*[LibOS/shim/include/shim_fs.h, line 561 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoWo2B7EoEsyrftstK:-MMqkAj35lDLpurPBAaz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/include/shim_fs.h#L561)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Add space after `APIs`
</blockquote></details>

Done.
___
*[LibOS/shim/src/Makefile, line 82 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoWvFV2qZq7GQJtb7i:-MMqkelO4J0cW0SLjLEU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/Makefile#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These four are not sorted
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 161 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoX5uy3FhYRaF0N8KN:-MMqlnMR3WKJ8DgKfJGp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/shim_fs.c#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Start with capital letter
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 164 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoX2gO8WiBnMnUk_MJ:-MMqlmYw1flMrocSSFTE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/shim_fs.c#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Start with capital letter
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 742 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoXCsW2UfEFVHtg1eY:-MMqmQwu-5w2iEJSkfRC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/proc/thread.c#L742)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you condense this `.ent` entry? Like below, hopefully in one line.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoXuxkAMWiTjLXkHQj:-MMqmSK42nfUxpxpGInA:b-o6ml3r) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/cache_info.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How can we be sure that `len < SYSFS_FILESZ`? This memcpy looks dangerous, we could have a buffer overwrite... Maybe we should add `assert(len < SYSFS_FILESZ)`?
</blockquote></details>

I think it is better to directly use `len`. Since we know the size of the buffer, let us it to allocate the memory.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoG1ep2IuDC8GBIU6C:-MMqh_VjEmN7I4h-P_YB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, it is unclear what "This" refers to. Replace `This` -> `temp_buf`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 56 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoYb6081XdQYxEZssV:-MMqn54f7sPFUF5hdcK7:bq6xy4j) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/cpu_info.c#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

will use `len` to allocate.
___
*[LibOS/shim/src/fs/sys/fs.c, line 122 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_2hA67jAP9LFoirN:-MMqnB7mA1hRrwcme_BP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/fs.c#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove one space here
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/node_info.c, line 45 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo__PI3XuZmiKaXTC8:-MMqnCawD6V9rpOGXsxU:b-g6fgyj) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/LibOS/shim/src/fs/sys/node_info.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

will use `len`.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_w207iqWT9ld8kWA:-MMqoAGD2YUsa-yQjyiz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `"` around the example
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 32 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_yWe3hVSM_h2kBdx:-MMqoBbL71pyN-UVx7od:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `"` around the example. And start with capital letter.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 33 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_r4V0DRp0xOJEoCz:-MMqo8bJ31WfdcWm0Jwd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove redundant spaces in these three macros
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoaLjeApruHQoIgY6C:-MMqoIRv9pu1lW_LUY22:bn83ekr) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, could you add one more example: with a dual-socket 160-core system?
</blockquote></details>

why add another example? Also on large systems, the allocation can vary on number of cache types, and num of sockets. So added a simple use case based on NUC. I think we can let the user evaluate it for their particular case. 

For our reference, a 160 core system with 4 cache levels (L1 Inst, L1 Data, L2 and L3) with 2 sockets will occupy ~366KB.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line  [...]

2020-11-24 09:45 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMtbQeABG_kpOeTece6:-MMtbQeB5wShq65-9hQk:b-g1q657) ([raw file](https://github.com/oscarlab/graphene/blob/e0259d277a645c87d6c19426316722742828e418/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
> ```C
>         return -ENOENT;
> 
>     /* temp_buf needs to stay on stack for the whole duration of the this function. */
> ```

`of the this` -> `of this`
___
*[Pal/include/arch/x86_64/pal-arch.h, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_w207iqWT9ld8kWA:-MMtbbnH5a-MU1uRZebT:b-u0j61g) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L30)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wrong placement of quotes: `"E.g 1024576 KB"` -> `E.g. "1024576 KB"`
___
*[Pal/include/arch/x86_64/pal-arch.h, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoaLjeApruHQoIgY6C:-MMtbldEEMBIU17agulv:bs4ixp3) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L249)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

why add another example? Also on large systems, the allocation can vary on number of cache types, and num of sockets. So added a simple use case based on NUC. I think we can let the user evaluate it for their particular case. 

For our reference, a 160 core system with 4 cache levels (L1 Inst, L1 Data, L2 and L3) with 2 sockets will occupy ~366KB.
</blockquote></details>

OK, fair enough.
___
*[Pal/src/host/Linux/db_main-x86_64.c, line 238 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoap2KB2UQQQBqSp1m:-MMtbxiq7PikAv_Dbg4d:bep03ik) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux/db_main-x86_64.c#L238)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If this function fails, graphene would exit, right? https://github.com/oscarlab/graphene/pull/1975/files#diff-ce9805462ee64fb007825fb70612be1a7b210c30c3d193f98ea903daf9492c84R544. Should this case be handled?
</blockquote></details>

OK, true, we may ignore error handling in this case.
___
*[Pal/src/host/Linux-common/topo_info.c, line 286 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoeXNw1SyPDf-owZ7y:-MMtcRSdEfiJb6GA4dE1:b1ekdtf) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux-common/topo_info.c#L286)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If graphene doesn't emulate Hugepages shouldn't we fail? AFAIU, `nr_hugepages` is a knob that a user with root
privileges can use to dynamically allocate more or free some persistent huge pages by increasing or decreasing its value. So on all systems, the default should be `0` until the user writes some value.

</blockquote></details>

OK, my wording of the comment is wrong then. But I still don't understand what you want to say with your `/sys fs doesn't provide write permission to modify the field.`. What does this comment highlight?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 393 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMofXgf9XjWV1enRsrz:-MMtco4J1uTBfJLJp9sa:b-obdm9w) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux-SGX/db_main.c#L393)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

oops, copy paste. 
</blockquote></details>

You still have `cpu_topology` instead of `core_topology`.
___
*[Pal/src/host/Linux-SGX/db_main-x86_64.c, line 217 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMobhWNA6wYKhHBD9z2:-MMtcyvX6tl-lDTkjlEj:b-hmit94) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux-SGX/db_main-x86_64.c#L217)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

since we don't have a security issue why do we want to do a deep-copy? BTW the logic works fine on both NUC and server systems.
</blockquote></details>

Ok, as long as it works :) I was just afraid that we may have two pointers to the same underlying object, and freeing will invalidate one of these pointers.


<!-- Sent from Reviewable.io -->

2020-11-24 15:40 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 286 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoeXNw1SyPDf-owZ7y:-MMutgL-CBtOXUnvl8YH:b-jgyur3) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux-common/topo_info.c#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, my wording of the comment is wrong then. But I still don't understand what you want to say with your `/sys fs doesn't provide write permission to modify the field.`. What does this comment highlight?
</blockquote></details>

I am trying to say that since we don't support writes, we simply set this to 0, the default value.


<!-- Sent from Reviewable.io -->

2020-11-25 09:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 286 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoeXNw1SyPDf-owZ7y:-MMyhP8DC6mxN4UdqhPh:b87bzyk) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux-common/topo_info.c#L286)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I am trying to say that since we don't support writes, we simply set this to 0, the default value.
</blockquote></details>

Let's change to this then: `/* since our /sys fs doesn't support writes, set persistent hugepages to their default value of zero */`


<!-- Sent from Reviewable.io -->

2020-11-25 17:17 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 26 of 30 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMtbQeABG_kpOeTece6:-MN-MAlJAjX6wUpPN76v:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/e0259d277a645c87d6c19426316722742828e418/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`of the this` -> `of this`
</blockquote></details>

Done
___
*[Pal/include/arch/x86_64/pal-arch.h, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMo_w207iqWT9ld8kWA:-MN-LvqW4Lfcz27lid7J:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/include/arch/x86_64/pal-arch.h#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrong placement of quotes: `"E.g 1024576 KB"` -> `E.g. "1024576 KB"`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 286 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMoeXNw1SyPDf-owZ7y:-MN-KWfS-ZgqBP9hmLpZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux-common/topo_info.c#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's change to this then: `/* since our /sys fs doesn't support writes, set persistent hugepages to their default value of zero */`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 393 at r3](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMofXgf9XjWV1enRsrz:-MN-Lo0O3p7gwOyokUOx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d503d840ef34b697f29cf63c5d3c9b70e31319e0/Pal/src/host/Linux-SGX/db_main.c#L393)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You still have `cpu_topology` instead of `core_topology`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-26 08:59 UTC, dimakuv reviewed
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MN2laqo5p9gZItSjI31:-MN2laqo5p9gZItSjI32:b-xyg1zi) (no related file):*
I am happy with this PR (apart from the two blocking comments with silent conflicts on rebase). Let's wait for @mkow to review it now :)

---


<!-- Sent from Reviewable.io -->

2020-11-26 08:59 UTC, dimakuv commented
Jenkins, test this please

2020-11-26 09:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MN2wTAH4JX7ecl4ZCwF:-MN2wTAIDYlxFRZY1Y1r:b-1ba1jk) (no related file):*
Please fix Jenkins errors:
```
Warning, treated as error:
/home/jenkins/workspace/docs-18.04/Documentation/pal/host-abi.rst:111:c:type reference target not found: PAL_TOPO_INFO
Makefile:22: recipe for target 'html' failed
```

```
fs/sys/fs.c: In function 'sys_info_mode':
fs/sys/fs.c:131:27: error: 'S_IFREG' undeclared (first use in this function)
     *mode = FILE_R_MODE | S_IFREG;
                           ^
fs/sys/fs.c:131:27: note: each undeclared identifier is reported only once for each function it appears in
fs/sys/fs.c: In function 'sys_info_stat':
fs/sys/fs.c:140:34: error: 'S_IFREG' undeclared (first use in this function)
     buf->st_mode = FILE_R_MODE | S_IFREG;
                                  ^
fs/sys/fs.c: In function 'sys_dir_stat':
fs/sys/fs.c:165:28: error: 'S_IFDIR' undeclared (first use in this function)
     buf->st_mode  = 0500 | S_IFDIR;
                            ^
fs/sys/fs.c: At top level:
cc1: error: unrecognized command line option '-Wno-address-of-packed-member' [-Werror]
cc1: all warnings being treated as errors
Makefile:171: recipe for target 'fs/sys/fs.o' failed
```

---


<!-- Sent from Reviewable.io -->

2020-11-26 18:00 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MN2wTAH4JX7ecl4ZCwF:-MN4fQqA-aXp-Pr6zkWs:bf7bwi6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix Jenkins errors:
```
Warning, treated as error:
/home/jenkins/workspace/docs-18.04/Documentation/pal/host-abi.rst:111:c:type reference target not found: PAL_TOPO_INFO
Makefile:22: recipe for target 'html' failed
```

```
fs/sys/fs.c: In function 'sys_info_mode':
fs/sys/fs.c:131:27: error: 'S_IFREG' undeclared (first use in this function)
     *mode = FILE_R_MODE | S_IFREG;
                           ^
fs/sys/fs.c:131:27: note: each undeclared identifier is reported only once for each function it appears in
fs/sys/fs.c: In function 'sys_info_stat':
fs/sys/fs.c:140:34: error: 'S_IFREG' undeclared (first use in this function)
     buf->st_mode = FILE_R_MODE | S_IFREG;
                                  ^
fs/sys/fs.c: In function 'sys_dir_stat':
fs/sys/fs.c:165:28: error: 'S_IFDIR' undeclared (first use in this function)
     buf->st_mode  = 0500 | S_IFDIR;
                            ^
fs/sys/fs.c: At top level:
cc1: error: unrecognized command line option '-Wno-address-of-packed-member' [-Werror]
cc1: all warnings being treated as errors
Makefile:171: recipe for target 'fs/sys/fs.o' failed
```
</blockquote></details>

These are due to silent conflicts on rebase as this commit doesn't include `stat.h` where the above macro are defined.  These warnings/errors should be resolved once I rebase with the latest master (having https://github.com/oscarlab/graphene/pull/1978). 

@dimakuv @mkow @yamahata please let me know if you want me to rebase to the latest master.

---


<!-- Sent from Reviewable.io -->

2020-11-26 18:02 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MN2wTAH4JX7ecl4ZCwF:-MN4i4aJ8j7GULHHVK0H:b735kux) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

These are due to silent conflicts on rebase as this commit doesn't include `stat.h` where the above macro are defined.  These warnings/errors should be resolved once I rebase with the latest master (having https://github.com/oscarlab/graphene/pull/1978). 

@dimakuv @mkow @yamahata please let me know if you want me to rebase to the latest master.
</blockquote></details>

I'm fine with rebase, but please wait for @dimakuv's ack ;)

---


<!-- Sent from Reviewable.io -->

2020-11-27 08:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MN2wTAH4JX7ecl4ZCwF:-MN7qvYg0nzn_AADMeSx:b-djfd85) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with rebase, but please wait for @dimakuv's ack ;)
</blockquote></details>

Yes, please rebase to the latest master.

---


<!-- Sent from Reviewable.io -->

2020-11-27 21:39 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 17 of 30 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MN2wTAH4JX7ecl4ZCwF:-MNAdQ_XAgUAU6Cp1Y_r:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please rebase to the latest master.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/fs/sys/fs.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMV-HA817r4fK5YuTed:-MNAdKhY9SpNKsneMQRU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/fs.c#L161)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Looks like #1978 is merged. Will rebase before the final push.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/1975#-MMV-RRn-fLIawF0Z46c:-MNAdLaVEsrNiiCMo6AC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b95b2e6f38c5c8a63bff07ed668ecd483ceb1483/LibOS/shim/src/fs/sys/fs.c#L169)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

noted.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-27 21:42 UTC, vijaydhanraj commented
> > Reviewed 4 of 4 files at r5.
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)_ status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MN2laqo5p9gZItSjI31:-MN2laqo5p9gZItSjI32:b-xyg1zi) (no related file):_
> I am happy with this PR (apart from the two blocking comments with silent conflicts on rebase). Let's wait for @mkow to review it now :)

Can we please restart the Jenkins test?

2020-11-29 18:19 UTC, mkow commented
Jenkins, retest this please

2020-11-30 09:28 UTC, dimakuv requested changes
> Reviewed 13 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MNNTI4X1Og8_Ox4wO5E:-MNNTI4Y4A4FeLfzZyXg:b-wbi1r7) (no related file):*
Jenskins fails with:
```
  [ host/Skeleton/libpal.so ]
host/Skeleton/.obj/db_main.o: In function `pal_main':
db_main.c:(.text+0xcbb): undefined reference to `_DkGetTopologyInfo'
Makefile:108: recipe for target 'host/Skeleton/libpal.so' failed
make: *** [host/Skeleton/libpal.so] Error 1
```

Seems like you forgot to update the Skeleton PAL with dummy `_Dk` functions.

---


<!-- Sent from Reviewable.io -->

2020-11-30 18:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 30 of 31 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MNNTI4X1Og8_Ox4wO5E:-MNPGy1DCxF_hizE-lDl:b-yuwtw4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenskins fails with:
```
  [ host/Skeleton/libpal.so ]
host/Skeleton/.obj/db_main.o: In function `pal_main':
db_main.c:(.text+0xcbb): undefined reference to `_DkGetTopologyInfo'
Makefile:108: recipe for target 'host/Skeleton/libpal.so' failed
make: *** [host/Skeleton/libpal.so] Error 1
```

Seems like you forgot to update the Skeleton PAL with dummy `_Dk` functions.
</blockquote></details>

Thanks @dimakuv. I have added the dummy implementation in Skeleton PAL as well.

---


<!-- Sent from Reviewable.io -->

2020-12-01 09:15 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-01 09:16 UTC, dimakuv commented
Jenkins, test this please

2020-12-01 10:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MNSm4Yz2JEc3TiDBtSg:-MNSm4Yz2JEc3TiDBtSh:b3zc8e) (no related file):*
Ok, one last thing to fix to make Jenkins happy:
```
Warning, treated as error:
/home/jenkins/workspace/docs-18.04/Documentation/pal/host-abi.rst:111:c:type reference target not found: PAL_TOPO_INFO
Makefile:22: recipe for target 'html' failed
```

I guess you forgot to add the new `PAL_TOPO_INFO` to the documentation file `host-abi.rst`. Please do it.

---


<!-- Sent from Reviewable.io -->

2020-12-01 17:14 UTC, dimakuv commented
Jenkins, test this please

2020-12-31 03:29 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 31 of 32 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 32 at r8](https://reviewable.io/reviews/oscarlab/graphene/1975#-MPqp3FZBV-OSzTBdcA7:-MPqp3FZBV-OSzTBdcA8:biho66z) ([raw file](https://github.com/oscarlab/graphene/blob/818776d92281c4bf633de29ae8a0540631bbb8c8/LibOS/shim/src/fs/sys/fs.c#L32)):*
> ```C
> /* This function will extract "cpu105" from "cpu105/cache/index0/type". If string doesn't have "/"
>  * delimiter, original string is returned. Note: This function modifies pathname! */
> static char* extract_first_token_from_path(char* pathname) {
> ```

A nit: Move most if this code into function index() [possibly Pal/lib/stringindex.c) and call it with index(pathname, '/').


<!-- Sent from Reviewable.io -->

2021-01-04 18:26 UTC, vijaydhanraj commented
___
*[LibOS/shim/src/fs/sys/fs.c, line 32 at r8](https://reviewable.io/reviews/oscarlab/graphene/1975#-MPqp3FZBV-OSzTBdcA7:-MQDZuTS0ZeX3_N_hCwx:bk495s2) ([raw file](https://github.com/oscarlab/graphene/blob/818776d92281c4bf633de29ae8a0540631bbb8c8/LibOS/shim/src/fs/sys/fs.c#L32)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

A nit: Move most if this code into function index() [possibly Pal/lib/stringindex.c) and call it with index(pathname, '/').
</blockquote></details>

@stefanberger are you suggesting to implement the generic index() function, https://man7.org/linux/man-pages/man3/index.3.html (or something like strchr())? If so, it already exists(/Pal/lib/string/strchr.c). On the other hand, this function simply truncates the original string after finding the first occurrence of the delimiter which is '/'. 


<!-- Sent from Reviewable.io -->

2021-01-04 18:40 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 31 of 32 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 32 at r8](https://reviewable.io/reviews/oscarlab/graphene/1975#-MPqp3FZBV-OSzTBdcA7:-MQDgiAA03l3k059jmEO:bq6bdjl) ([raw file](https://github.com/oscarlab/graphene/blob/818776d92281c4bf633de29ae8a0540631bbb8c8/LibOS/shim/src/fs/sys/fs.c#L32)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@stefanberger are you suggesting to implement the generic index() function, https://man7.org/linux/man-pages/man3/index.3.html (or something like strchr())? If so, it already exists(/Pal/lib/string/strchr.c). On the other hand, this function simply truncates the original string after finding the first occurrence of the delimiter which is '/'. 
</blockquote></details>

`strchr()` should also, so you should be able to just call it.


<!-- Sent from Reviewable.io -->

2021-01-04 20:08 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 31 of 32 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

___
*[LibOS/shim/src/fs/sys/fs.c, line 32 at r8](https://reviewable.io/reviews/oscarlab/graphene/1975#-MPqp3FZBV-OSzTBdcA7:-MQDzDHQ22r9uFQHQ03y:b-90rs6z) ([raw file](https://github.com/oscarlab/graphene/blob/818776d92281c4bf633de29ae8a0540631bbb8c8/LibOS/shim/src/fs/sys/fs.c#L32)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

`strchr()` should also, so you should be able to just call it.
</blockquote></details>

sure, we can use `strchr()` to find the position of `/` delimiter and set it to `\0`. The basic idea of this function is to extract something like "cpu105" from "cpu105/cache/index0/type".


<!-- Sent from Reviewable.io -->

2021-01-05 22:42 UTC, vijaydhanraj commented
Rebased to the latest master to resolve merge conflicts.

2021-01-05 23:21 UTC, mkow commented
Jenkins, retest this please

2021-01-07 15:48 UTC, mkow requested changes
> Reviewed 3 of 30 files at r1, 1 of 12 files at r2, 2 of 12 files at r4, 3 of 4 files at r5, 2 of 13 files at r6, 21 of 21 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 82 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPII0L0S7RpRVDZFgo:-MQPII0L0S7RpRVDZFgp:bis3puh) (no related file):*
@vijaydhanraj One general comment, because I see a lot of similar issues in this PR: please carefully analyze the untrusted<->trusted world interactions in SGX PAL added by this change. We can't forward something which is incoherent/invalid to the application, as it trusts the kernel (which is "LibOS" in our case) and probably parses all the data very carelessly.

---
___
*[LibOS/shim/include/shim_fs.h, line 490 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPitXm9aUIAJoPmf3C:-MQPitXn1-HQuAtofKtx:bi8epmo) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/include/shim_fs.h#L490)):*
> ```objc
> struct pseudo_name_ops {
>     int (*match_name)(const char* name);
>     int (*list_name)(const char* name, struct shim_dirent** buf, int count);
> ```

while we're here, `int count` -> `size_t count`
___
*[LibOS/shim/include/shim_fs.h, line 553 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSNIpo5Oh4mk-5dpe4:-MQSNIpo5Oh4mk-5dpe5:blu8sxq) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/include/shim_fs.h#L553)):*
> ```objc
> 
> /* /sys fs related common APIs */
> int extract_num_from_path(const char* path);
> ```

This is a global function in global namespace, the current name is very confusing without context. What kind of paths does it parse? How the number is extracted? I really had no clue until I read the whole implementation.

`extract_first_num_from_string` or something similar would be better.
___
*[LibOS/shim/include/shim_fs.h, line 560 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPj-ii0VWDfdoa5VX7:-MQPj-ii0VWDfdoa5VX8:b-vnlsj5) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/include/shim_fs.h#L560)):*
> ```objc
> int sys_dir_stat(const char* name, struct stat* buf);
> int sys_match_resource_num(const char* pathname);
> int sys_list_resource_num(const char* pathname, struct shim_dirent** buf, int len);
> ```

`int len` -> `size_t size`
___
*[LibOS/shim/src/fs/proc/thread.c, line 728 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPkg-q9lxDgIXcqzC6:-MQPkg-q9lxDgIXcqzC7:bo1arho) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/proc/thread.c#L728)):*
> ```C
>     .ent  = {
>         {.name_ops = &nm_thread, .fs_ops = &fs_thread, .type = LINUX_DT_DIR},
>     }};
> ```

here and below: please move the last `};` to a separate like and unindent that line
___
*[LibOS/shim/src/fs/proc/thread.c, line 738 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPktmF3qqXbQeojcss:-MQPktmGAKQqVjD6X-24:b-k7kz2i) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/proc/thread.c#L738)):*
> ```C
>         {.name = "fd",   .fs_ops = &fs_thread_fd,   .dir  = &dir_fd},
>         {.name = "maps", .fs_ops = &fs_thread_maps, .type = LINUX_DT_REG},
>         {.name = "task", .fs_ops = &fs_thread,      .dir  = &dir_task },
> ```

no space before `}`
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRmc0p7WNt8P1jthJv:-MQRmc0u4MMiTpnYoUQ6:byrqgel) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
> ```
> (strlen(filename) != len)
> ```

What's the point of this check? Isn't `get_base_name` always guaranteeing this?
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRpJlr5RSp1kDxKwHA:-MQRpJls920Z6PtmUNgV:b-cn2zne) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
> ```C
>     }
> 
>     len = strlen(cache_filebuf) + 1;
> ```

this is "size" of the C-string, not "length"
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRqAwbCQAuCGaSI2Lm:-MQRqAwbCQAuCGaSI2Ln:b-cfsbr9) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L119)):*
> ```
>     .ent  = {
>               { .name_ops = &cache_ops,
> ```

This indentation looks weird. I'd propose something like this:

```C
const struct pseudo_dir cpunum_cache_dir = {
    .size = 1,
    .ent  = {
        { .name_ops = &cache_ops,
          .fs_ops   = &cache_info,
          .dir      = &cache_idx_dir,
          .type     = LINUX_DT_DIR
        },
    }
};
```
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 13 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSMpPvEgSIgWXL3Ftb:-MQSMpPvEgSIgWXL3Ftc:byzex97) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L13)):*
> ```C
> static int cpu_info_open(struct shim_handle* hdl, const char* name, int flags) {
>     __UNUSED(hdl);
>     __UNUSED(flags);
> ```

both of these are not unused
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 17 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSMtJ1-_EGdt7L_TdW:-MQSMtJ1-_EGdt7L_TdX:b-1fjees) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L17)):*
> ```C
>     char filename[32];
> 
>     size_t len = sizeof(filename);
> ```

it's size, not length
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSMyYH54nQslqOrZnm:-MQSMyYH54nQslqOrZnn:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L19)):*
> ```C
>     size_t len = sizeof(filename);
>     int ret = get_base_name(name, filename, &len);
>     if (ret < 0 || (strlen(filename) != len))
> ```

ditto
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSOO8CAIqSoTOi3Sp7:-MQSOO8DE5IrcAUud_pU:bb76mu4) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
> ```C
>         return -ENOENT;
> 
>     /* temp_buf needs to stay on stack for the whole duration of this function. */
> ```

Why?
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 31 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSPBcsB06pDx-tHlPN:-MQSOmPF7mEW3AnV_-TG:bvetcfj) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L31)):*
> ```C
>     if (!strcmp(filename, "online")) {
>         /* distinguish /sys/devices/system/cpu/online from /sys/devices/system/cpu/cpuX/online */
>         if (strstr(name, "cpu/cpu"))
> ```

Eh, our filesystem layer really needs to be rewritten. This check will probably break if someone creates a symlink directly to `/sys/devices/system/cpu/cpuX/online`, but fixing this would require changing the filesystem code, so it's something for later.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 52 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSPczq8ntLn87yuDyF:-MQSPczq8ntLn87yuDyG:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_ [...]

2021-01-13 11:22 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 82 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs.h, line 490 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPitXm9aUIAJoPmf3C:-MQeh-tLDW1Nnz_DWoO1:b-udqv2y) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/include/shim_fs.h#L490)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

while we're here, `int count` -> `size_t count`
</blockquote></details>

Done, created a separate commit for this fix.
___
*[LibOS/shim/include/shim_fs.h, line 553 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSNIpo5Oh4mk-5dpe4:-MQeh4Jh5UtJeIVJCD70:btdymka) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/include/shim_fs.h#L553)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a global function in global namespace, the current name is very confusing without context. What kind of paths does it parse? How the number is extracted? I really had no clue until I read the whole implementation.

`extract_first_num_from_string` or something similar would be better.
</blockquote></details>

Done. Also documented the high-level functionality at declaration.
___
*[LibOS/shim/include/shim_fs.h, line 560 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPj-ii0VWDfdoa5VX7:-MQelLNL1XDO8DCYpv1I:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/include/shim_fs.h#L560)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`int len` -> `size_t size`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 728 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPkg-q9lxDgIXcqzC6:-MQemXbx8Nk-BWqQfeza:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/proc/thread.c#L728)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

here and below: please move the last `};` to a separate like and unindent that line
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 738 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPktmF3qqXbQeojcss:-MQemYkQCuNTWKc8XyoS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/proc/thread.c#L738)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space before `}`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRmc0p7WNt8P1jthJv:-MQhMiyS7rwHRmwHM0Vo:beahqyh) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> (strlen(filename) != len)
> ```

What's the point of this check? Isn't `get_base_name` always guaranteeing this?
</blockquote></details>

Just a little cautious. If the user of this API provides overlapping src and destination then the behavior of memcpy in `get_base_name` can be undefined. So verifying the results.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 50 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRpJlr5RSp1kDxKwHA:-MQhQWM9D-lYJYr5ykci:b-896fjx) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this is "size" of the C-string, not "length"
</blockquote></details>

Done
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRqAwbCQAuCGaSI2Lm:-MQhS8IoCpUnIO299Xd0:bw55ujs) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L119)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>     .ent  = {
>               { .name_ops = &cache_ops,
> ```

This indentation looks weird. I'd propose something like this:

```C
const struct pseudo_dir cpunum_cache_dir = {
    .size = 1,
    .ent  = {
        { .name_ops = &cache_ops,
          .fs_ops   = &cache_info,
          .dir      = &cache_idx_dir,
          .type     = LINUX_DT_DIR
        },
    }
};
```
</blockquote></details>

how about this? Can help with LOC count :)
```
const struct pseudo_dir cpunum_cache_dir = {
    .size = 1,
    .ent  = {
        {.name_ops = &cache_ops, .fs_ops = &cache_info, .dir = &cache_idx_dir, .type = LINUX_DT_DIR},
    }
};
```
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 13 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSMpPvEgSIgWXL3Ftb:-MQhVOkB66baGWsUCsWj:bauzkzw) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

both of these are not unused
</blockquote></details>

yes good catch, I have removed it.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 17 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSMtJ1-_EGdt7L_TdW:-MQhrCaK9FgnfvzY5n0Q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

it's size, not length
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSMyYH54nQslqOrZnm:-MQhrDi76gNFAxLaPtfo:b52mkhp) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

pls refer earlier comment.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSOO8CAIqSoTOi3Sp7:-MQhrnw47g3odAYEQJF8:b-4457vy) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

`cpu_filebuf` points to `temp_buf`so cannot make it block scope.
```
    } else if (!strcmp(filename, "physical_package_id")) {
        /* we have already collected this info as part of /proc/cpuinfo. So reuse it */
        snprintf(temp_buf, sizeof(temp_buf), "%d\n", pal_control.cpu_info.cpu_socket[cpunum]);
        cpu_filebuf = temp_buf;
   }
```
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 52 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSPczq8ntLn87yuDyF:-MQhsIb-CRATegDQMdxm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 82 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSPqMcAXPtewkQ_nWE:-MQhsJlV4rCQgLq3WjnQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/c [...]

2021-01-13 14:26 UTC, dimakuv requested changes
> Reviewed 16 of 21 files at r9, 13 of 13 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 93 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs.h, line 555 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw07qv80Ngv2p63Unf:-MQw07qv80Ngv2p63Ung:bgtq0pn) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/include/shim_fs.h#L555)):*
> ```objc
> /* This function extracts first number from the file path. For example, "3" will be extracted
>  * from "cpu/cpu3/topology/core_siblings" path */
> int extract_first_num_from_string (const char* path);
> ```

Please remove the space after function name
___
*[LibOS/shim/src/fs/shim_fs.c, line 160 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw0RwN8S5psVAiYQTW:-MQw0RwN8S5psVAiYQTX:bc9xemd) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/shim_fs.c#L160)):*
> ```C
>     }
> 
>     debug("Mounting as sys filesystem: /sys\n");
> ```

`as sys` -> `special sys`
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw0vkI2cbIjOvsW_5H:-MQw0vkI2cbIjOvsW_5I:bc6uw73) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
> ```C
>         return -ENOENT;
> 
>     int cpunum = extract_first_num_from_string (name);
> ```

Here and everywhere: remove space after function name
___
*[LibOS/shim/src/fs/sys/fs.c, line 57 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw1Tm-80R_i7HBvx9b:-MQw1Tm-80R_i7HBvx9c:b-6oeq5t) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/sys/fs.c#L57)):*
> ```C
>     }
> 
>     num = extract_first_num_from_string (token);
> ```

Remove space
___
*[Pal/src/host/Linux-SGX/db_main.c, line 175 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw4rhn2n7RJwc6RpJl:-MQw4rhn2n7RJwc6RpJm:b-uvcf5s) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L175)):*
> ```C
> extern void* g_enclave_top;
> 
> #define IS_BOOL(data) (data == 1) ? true : ((data == 0) ? true : false)
> ```

Does this make sense? You return true if `data == 0`?

And please remove this macro, you use it in only one place...
___
*[Pal/src/host/Linux-SGX/db_main.c, line 176 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw5-nF589YFmQRdwYW:-MQw5-nF589YFmQRdwYX:b7axyox) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L176)):*
> ```C
> 
> #define IS_BOOL(data) (data == 1) ? true : ((data == 0) ? true : false)
> #define IS_IN_RANGE(value, start, end) (value < start || value > end) ? false : true
> ```

I don't like this macro, why not just embed in lines below? You don't save any LoCs with it.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 183 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw3eYcDxxY0gsE1xbL:-MQw3eYcDxxY0gsE1xbM:b-hh8h1q) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L183)):*
> ```C
>  * Eg. 20abc or 3,4,5 or xyz123 or 512H.
>  * Use case: To extract int from /sys/devices/system/cpu/cpuX/cache/index0/size path. */
> static int extract_int_from_buffer(const char* buf, char* size) {
> ```

This function seems to do exactly the same as already-existing `parse_size_str()`. Please use the already-existing one and remove this.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 212 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7qWF2YvCCWKcF4Ce:-MQw7qWF2YvCCWKcF4Cf:b-9i2qql) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L212)):*
> ```C
>         return -EINVAL;
> 
>     char* end;
> ```

Please define variables close to where they are used (move `end`)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 227 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7NZ64I0g5vNwLWC5:-MQw7NZ64I0g5vNwLWC6:b-ex4ufa) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L227)):*
> ```C
>         }
> 
>         if (*end == '\0' || *end == ',' || *end == '\n') {
> ```

Why do you need this check? Won't it be checked in exactly the same way on the next iteration, because `strtoll()` will lead to `-EINVAL`?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 244 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw6obO7cX_ufwNtOR0:-MQw6obO7cX_ufwNtOR1:bibcvpc) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L244)):*
> ```C
>  * Returns negative unix error if buffer contains alpha or alphanumeric values and number of hw
>  * resources otherwise. */
> static int sanitize_hw_resource_count(const char* buf, bool ordered) {
> ```

Can't you add these checks in `get_hw_resource()` and call that function instead of introducing a new one?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 306 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7zfw0n0rcfae0zU_:-MQw7zfw0n0rcfae0zUa:bk1zbi3) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L306)):*
> ```C
>     int coherency_line_size;
>     int number_of_sets;
>     int physical_line_partition;
> ```

Please define variables close to where they are used (move all here)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 349 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw80fT8gO1-zcYfUx_:-MQw80fT8gO1-zcYfUxa:bk1zbi3) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L349)):*
> ```C
>     int core_id;
>     int core_siblings;
>     int thread_siblings;
> ```

Please define variables close to where they are used (move all here)


<!-- Sent from Reviewable.io -->

2021-01-13 20:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 28 of 33 files reviewed, 93 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs.h, line 555 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw07qv80Ngv2p63Unf:-MQwsQHFCUxlF9ddfE-9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/include/shim_fs.h#L555)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the space after function name
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 160 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw0RwN8S5psVAiYQTW:-MQws_tK20w2Nu56nlN6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/shim_fs.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`as sys` -> `special sys`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 22 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw0vkI2cbIjOvsW_5H:-MQwsv2yEKiwqt8gXhdv:br6spft) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/sys/cache_info.c#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here and everywhere: remove space after function name
</blockquote></details>

Addressed in this file, will check again in other files as well.
___
*[LibOS/shim/src/fs/sys/fs.c, line 57 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw1Tm-80R_i7HBvx9b:-MQwt3uV-S-kaXUj1dbo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/sys/fs.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove space
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 175 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw4rhn2n7RJwc6RpJl:-MQwtCU78Hgf6kF4m4Rk:blkcayl) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L175)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does this make sense? You return true if `data == 0`?

And please remove this macro, you use it in only one place...
</blockquote></details>

This macro checks if the data is of the boolean type which can have only valid inputs of either `0` or `1`. So this function returns true for `0` and `1` and false for all other cases.

Ok, will remove this macro.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 176 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw5-nF589YFmQRdwYW:-MQwvNIl2FKwWepAJxLr:b-wj3xl1) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this macro, why not just embed in lines below? You don't save any LoCs with it.
</blockquote></details>

Agree it doesn't save LOC but it does declutter the code. It becomes ugly when the `value` argument is a lengthy one. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 183 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw3eYcDxxY0gsE1xbL:-MQxGAWgEH3M0f-Nr_Z8:b-1vifbx) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L183)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This function seems to do exactly the same as already-existing `parse_size_str()`. Please use the already-existing one and remove this.
</blockquote></details>

yes I did check `parse_size_str()` function but this fails to identify 2 cases,
1. We can pass any garbage value after a valid size qualifier. Eg. "2K,./:010ijk,3-4,". This should not be permissible for /sys paths.
2. Buffer in /sys path might have `\n` at the end. For example, /sys/devices/system/cpu/cpuX/topology/core_id can contain "31\n". But this function will fail in this case as well.

I felt `parse_size_str()` was more generic and didn't want to modify it. But if you think, these are valid cases, I will replace `parse_size_str()` implementation with `extract_int_from_buffer()`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 212 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7qWF2YvCCWKcF4Ce:-MQxIw6C8P42IKIWtbmR:b-y4gc5g) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L212)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please define variables close to where they are used (move `end`)
</blockquote></details>

I didn't want to keep declaring `end` inside the loop but it is not harmful to do so inside the loop as well. Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 227 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7NZ64I0g5vNwLWC5:-MQxQkcy4jvI7B-n0h2F:b-usors0) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this check? Won't it be checked in exactly the same way on the next iteration, because `strtoll()` will lead to `-EINVAL`?
</blockquote></details>

This is for a corner case when the buffer contains `-`. Something like "00000000-1" is not a valid bitmap but without this check, we might treat this as `-1` and will return `64`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 244 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw6obO7cX_ufwNtOR0:-MQxSaf53wy10uZc_DnC:b-1fu9n0) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can't you add these checks in `get_hw_resource()` and call that function instead of introducing a new one?
</blockquote></details>

I did think about it but `get_hw_resource()` is basically for 2 things,
1. Read integer stored in a file. (syscall to read a file)
2. if `count == true` counts the number of resources present.

It doesn't take care of the ordering, for example, if the input was "1-5, 3-4, 7-1". But this is malformed and `sanitize_hw_resource_count` will handle it. Also, we just need to read a buffer instead of invoking a syscall. So felt it is better to separate these and not overload a single function. My intention is to keep ``get_hw_resource()` for generic purpose and `sanitize_hw_resource_count()` for specifically for checking the validity of the buffer.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 306 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7zfw0n0rcfae0zU_:-MQxVIJ23wZGv1lGKFwc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please define variables close to where they are used (move all here)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 349 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw80fT8gO1-zcYfUx_:-MQxVJIK1i5Ip4dcdCrH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0 [...]

2021-01-15 09:27 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 103 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 175 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw4rhn2n7RJwc6RpJl:-MR4DsZzCB4vLz62AD97:bgtrey7) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L175)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This macro checks if the data is of the boolean type which can have only valid inputs of either `0` or `1`. So this function returns true for `0` and `1` and false for all other cases.

Ok, will remove this macro.
</blockquote></details>

OK, thanks. It was a strange pattern that got me confused. If you would write `(data == 0 || data == 1)` it would be easier to understand. But I see that you changed this already when you embedded this macro in the code. So it's good now.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 176 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw5-nF589YFmQRdwYW:-MR4EGvp8Driwipe5tcY:b51x66c) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L176)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Agree it doesn't save LOC but it does declutter the code. It becomes ugly when the `value` argument is a lengthy one. 
</blockquote></details>

OK, fair enough. But please move to `Pal/include/lib/api.h`, looks useful for other cases.

Also, please wrap `value`, `start`, `end` in parentheses, see examples in `api.h` (basically always `(value)` and so on).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 183 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw3eYcDxxY0gsE1xbL:-MR4LPxPEyYb_Gmg3ZK6:bv264z7) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L183)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes I did check `parse_size_str()` function but this fails to identify 2 cases,
1. We can pass any garbage value after a valid size qualifier. Eg. "2K,./:010ijk,3-4,". This should not be permissible for /sys paths.
2. Buffer in /sys path might have `\n` at the end. For example, /sys/devices/system/cpu/cpuX/topology/core_id can contain "31\n". But this function will fail in this case as well.

I felt `parse_size_str()` was more generic and didn't want to modify it. But if you think, these are valid cases, I will replace `parse_size_str()` implementation with `extract_int_from_buffer()`
</blockquote></details>

OK, this makes sense. Let's keep these funcs separate.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 212 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7qWF2YvCCWKcF4Ce:-MR4Iosr8E6cxTgzLp1X:bx5pt6r) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L212)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I didn't want to keep declaring `end` inside the loop but it is not harmful to do so inside the loop as well. Done.
</blockquote></details>

There is no difference from the assembly point of view. Compilers know better than us humans when to optimize variables out of the loop.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 227 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7NZ64I0g5vNwLWC5:-MR4Kkgw9Omvc69U8hFm:b-wv6h3l) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L227)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is for a corner case when the buffer contains `-`. Something like "00000000-1" is not a valid bitmap but without this check, we might treat this as `-1` and will return `64`.
</blockquote></details>

I would reverse the logic in this IF like this:
```
if (*end != '\0' && *end != ',' && *end != '\n')
    return -EINVAL;

count += ...
```

In general, please try to use as less IFs and indentations as possible in your code. It's really hard to read it.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 244 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw6obO7cX_ufwNtOR0:-MR4Me0GCeUhCXkOs7gn:b-a6o4ua) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L244)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I did think about it but `get_hw_resource()` is basically for 2 things,
1. Read integer stored in a file. (syscall to read a file)
2. if `count == true` counts the number of resources present.

It doesn't take care of the ordering, for example, if the input was "1-5, 3-4, 7-1". But this is malformed and `sanitize_hw_resource_count` will handle it. Also, we just need to read a buffer instead of invoking a syscall. So felt it is better to separate these and not overload a single function. My intention is to keep ``get_hw_resource()` for generic purpose and `sanitize_hw_resource_count()` for specifically for checking the validity of the buffer.
</blockquote></details>

OK, let's keep the funcs separate.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 182 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4G6Hj-A_JdL6NMJIz:-MR4G6HkE3OyuViF9wPH:b-1bhpy0) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L182)):*
> ```C
>  * Eg. 20abc or 3,4,5 or xyz123 or 512H.
>  * Use case: To extract int from /sys/devices/system/cpu/cpuX/cache/index0/size path. */
> static int extract_int_from_buffer(const char* buf, char* size) {
> ```

I would prefer using `int64_t` in this function.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 182 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4GOCK01TRv31_U38i:-MR4GOCK01TRv31_U38j:bhcfu5z) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L182)):*
> ```C
>  * Eg. 20abc or 3,4,5 or xyz123 or 512H.
>  * Use case: To extract int from /sys/devices/system/cpu/cpuX/cache/index0/size path. */
> static int extract_int_from_buffer(const char* buf, char* size) {
> ```

What's the point of `size` output arg? You already check whether it is `K/M/G` in this function, so why does the caller need to check it again? I think you can just remove it and return `-EINVAL` if there is something else as the suffix.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 186 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4GfMW1o9zzz_SkX1q:-MR4GfMW1o9zzz_SkX1r:b7yam6c) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L186)):*
> ```C
>         return -ENOENT;
> 
>     char* end;
> ```

Please make it `= NULL;` for sanity.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 187 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4GeCH81MMDYiwyyUS:-MR4GeCH81MMDYiwyyUT:bjwpvga) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L187)):*
> ```C
> 
>     char* end;
>     const char* ptr = buf;
> ```

Why do you need a new variable `ptr`? You can just use `buf`, and also replace `ptr = end + 1;` with `end += 1;`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 188 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-M [...]

2021-01-15 21:51 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 32 of 34 files reviewed, 103 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 176 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw5-nF589YFmQRdwYW:-MR5ei6b7Il8HUP8Bmxw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, fair enough. But please move to `Pal/include/lib/api.h`, looks useful for other cases.

Also, please wrap `value`, `start`, `end` in parentheses, see examples in `api.h` (basically always `(value)` and so on).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 227 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw7NZ64I0g5vNwLWC5:-MR5iENyBwOAqXuclmXC:b-szhbky) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/Pal/src/host/Linux-SGX/db_main.c#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would reverse the logic in this IF like this:
```
if (*end != '\0' && *end != ',' && *end != '\n')
    return -EINVAL;

count += ...
```

In general, please try to use as less IFs and indentations as possible in your code. It's really hard to read it.
</blockquote></details>

sure, done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 182 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4G6Hj-A_JdL6NMJIz:-MR5jxv88B83e49OQIDJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer using `int64_t` in this function.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 182 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4GOCK01TRv31_U38i:-MR6bJ9y71hF6AFXxs4C:b-7mi1b2) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of `size` output arg? You already check whether it is `K/M/G` in this function, so why does the caller need to check it again? I think you can just remove it and return `-EINVAL` if there is something else as the suffix.
</blockquote></details>

yes, actually we don't need size to be returned to the user. I have removed it.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 186 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4GfMW1o9zzz_SkX1q:-MR6bSh23Jg8G-Mli9U7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please make it `= NULL;` for sanity.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 187 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4GeCH81MMDYiwyyUS:-MR6bVAV5F7yT5NcXtWJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L187)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need a new variable `ptr`? You can just use `buf`, and also replace `ptr = end + 1;` with `end += 1;`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 188 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4Gqki-x3Fhi9L8B7u:-MR6brI-CyPanurclkKP:b-qy3qbu) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L188)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`int64_t` and then you don't need a type cast.
</blockquote></details>

yes, done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 188 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4HTep0LtSLQzMsek2:-MR6btpp6b9v9-wVsY4G:b-wsmvod) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L188)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not have `/*base=*/0` instead of 10, so that `strtol()` decides itself what base the number is in?
</blockquote></details>

I prefer it to be explicit. It tells us what sort of argument is being provided as input. In this case, we cannot have a hex value and this should be considered as an error. Also in `count_bits_set_from_resource_map` I use `strtol` with `16` as the input will be a hex value. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 190 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4HdBuBvwyEBAPn33Q:-MR6cLOT6bVQtiq3fDu1:b-1as8j8) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Reversing args makes it more readable: `if (end == buf)` ("if the end of the number in string is the beginning of this string...")
</blockquote></details>

actually `buf` need not be the beginning and `end` need not be the actual end. All we want to check is if there were no digits at all. strtol() stores the original value of `buf` in `end` in such a case. So `if (buf == end)` does seem to make sense to me.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 192 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4HyVY0_QU0zdYi0fg:-MR6dVRW9K06QvN7nNzc:b-hhuk4r) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for an `else` because you already return in the other branch.

This can be significantly simplified. You can just have a big IF of all good options:
```
if (end[0] == '\0' ||
    (end[0] == '\n' && end[1] == '\0') ||
    ((end[0] == 'K' || end[0] == 'M' || end[0] == 'G') && end[1] == '\0'))  return intval;
```
</blockquote></details>

yes `else` can be removed. But the above condition fails to catch a valid case "20K\n". Also clubbing so many conditions seems a little ugly to me. Modified my earlier approach to remove size but this does have another level of indentation but feel this is cleaner (just my opinion and it might be biased :))
```
    if (end[0] != '\0') {
        if (end[0] != '\n' && (end[0] != 'K' && end[0] != 'M' && end[0] != 'G'))
            return -EINVAL;

        end += 1;
        if (end[0] != '\0' && (end[0] != '\n' && end[1] != '\0'))
            return -EINVAL;
    }
```
___
*[Pal/src/host/Linux-SGX/db_main.c, line 200 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4FdvI6LafNTQRjV2K:-MR6mFqX9-5r9ZCaUXSQ:bm4rwxv) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What if `intval == -22` (== `-EINVAL`)? Then a legit number will be treated as an error condition.

This function is probably used only for non-negative integers, right? Please add this to the top-level comment of this function then. And maybe change the func name to `extract_uint_...` (notice the `u`).
</blockqu [...]

2021-01-18 02:40 UTC, mkow requested changes
> Reviewed 9 of 13 files at r10, 4 of 5 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 112 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPII0L0S7RpRVDZFgo:-MRIHPZf8L0-X1NBmsEh:b6a9r55) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@vijaydhanraj One general comment, because I see a lot of similar issues in this PR: please carefully analyze the untrusted<->trusted world interactions in SGX PAL added by this change. We can't forward something which is incoherent/invalid to the application, as it trusts the kernel (which is "LibOS" in our case) and probably parses all the data very carelessly.
</blockquote></details>

We're still allowing a lot of inconsistent information to be passed to the user app (see some comments in the review, but there's much more). It's quite hard to validate all of them properly, I think we should create an issue about this and discuss the problem there.

@yamahata @dimakuv Any thoughts?

---
___
*[LibOS/shim/include/shim_fs.h, line 553 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ga-T1BNxYW4fl3vw:-MR2ga-T1BNxYW4fl3vx:bh4cj81) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L553)):*
> ```objc
> 
> /* /sys fs related common APIs */
> /* This function extracts first number from the file path. For example, "3" will be extracted
> ```

`the file path` -> `a string` (the description doesn't work well with the new name)
___
*[LibOS/shim/include/shim_fs.h, line 554 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2geux01jbYtgIfidF:-MR2geux01jbYtgIfidG:b-mt8490) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L554)):*
> ```objc
> /* /sys fs related common APIs */
> /* This function extracts first number from the file path. For example, "3" will be extracted
>  * from "cpu/cpu3/topology/core_siblings" path */
> ```

and remove ` path` from here :)
___
*[LibOS/shim/include/shim_fs.h, line 561 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ipqX1LJ9_aarIXg1:-MR2ipqX1LJ9_aarIXg2:b-e3ah7y) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L561)):*
> ```objc
> int sys_dir_mode(const char* name, mode_t* mode);
> int sys_dir_stat(const char* name, struct stat* buf);
> /* This function checks if directory present in the pathname is valid. Returns 1 on success and 0
> ```

Hmm, this doesn't help much. What's "valid"?
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRmc0p7WNt8P1jthJv:-MR2kIw94_zH-vu8HOjS:b-e58h41) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Just a little cautious. If the user of this API provides overlapping src and destination then the behavior of memcpy in `get_base_name` can be undefined. So verifying the results.
</blockquote></details>

But the buffer we're providing here is not overlapping with anything? We allocated it right above.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRqAwbCQAuCGaSI2Lm:-MR2l-q03dr_4anqCZH5:bqk8t0b) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L119)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

how about this? Can help with LOC count :)
```
const struct pseudo_dir cpunum_cache_dir = {
    .size = 1,
    .ent  = {
        {.name_ops = &cache_ops, .fs_ops = &cache_info, .dir = &cache_idx_dir, .type = LINUX_DT_DIR},
    }
};
```

</blockquote></details>

Nah, this is less readable IMO ;) (but the previous struct, `cache_idx_dir`, looks very good after your reformatting)
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSOO8CAIqSoTOi3Sp7:-MR2luD0AOjvTLcDcMF5:b-uv5h69) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`cpu_filebuf` points to `temp_buf`so cannot make it block scope.
```
    } else if (!strcmp(filename, "physical_package_id")) {
        /* we have already collected this info as part of /proc/cpuinfo. So reuse it */
        snprintf(temp_buf, sizeof(temp_buf), "%d\n", pal_control.cpu_info.cpu_socket[cpunum]);
        cpu_filebuf = temp_buf;
   }
```
</blockquote></details>

Oh, that's what you mean in this comment. So, I'd just drop it altogether, I think it's quite obvious that it can't be declared in this block because it has only 2 lines and one of them is extracting the pointer to the outside.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 19 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2lcXS1RWBo4iiyJWQ:-MR2lcXS1RWBo4iiyJWR:b-49wln5) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/src/fs/sys/cpu_info.c#L19)):*
> ```C
>         return -ENOENT;
> 
>     int cpunum = extract_first_num_from_string (name);
> ```

please remove this space
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI7lC9AfSonTAetp6m:-MRI7lCA-c4iZe7LvLIg:blqsgzo) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
> ```
> pal_control.topo_info.core_topology[cpunum].is_logical_core_online
> ```

This field is uninitialized for `cpunum == 0`.
___
*[LibOS/shim/src/fs/sys/fs.c, line 31 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSQgGgEwphUNqo64fL:-MR2mgpA762uCJ_MpCwC:b-ijtb63) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/fs.c#L31)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is a static function.
</blockquote></details>

Oh, sorry, you're right here :)
___
*[LibOS/shim/src/fs/sys/fs.c, line 64 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSRfpZC1EfMocIOA2s:-MR2nnqp4tOa9ye3iZVG:bj4etm7) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/fs.c#L64)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

fixed this by using `strstartswith` and also fixed similar issue in `sys_list_resource_num` by using `strendswith`
</blockquote></details>

Still, what about `nodeasdf`? Maybe I'm missing something, but won't this allow user applications to read from `/sys/something..something/nodeasdf` as if this was a correct path to a node information?
___
*[LibOS/shim/src/fs/sys/fs.c, line 16 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2meIe8s2ebuaIBq0S:-MR2meIe8s2ebuaIBq0T:bmsq1gs) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/src/fs/sys/fs.c#L16)):*
> ```C
> extern const struct pseudo_dir sys_node_dir;
> 
> int extract_first_num_from_string (const char* pathname) {
> ```

no space
___
*[LibOS/shim/src/fs/sys/fs.c, line 30 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975 [...]

2021-01-19 03:45 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 112 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs.h, line 553 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ga-T1BNxYW4fl3vw:-MRITAL30EsF8sgtCjj3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L553)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`the file path` -> `a string` (the description doesn't work well with the new name)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 554 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2geux01jbYtgIfidF:-MRITBZ405EtY2pVaYhT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L554)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

and remove ` path` from here :)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 561 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ipqX1LJ9_aarIXg1:-MRITrLPB_PUfil6t3YG:b-cqprvo) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L561)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, this doesn't help much. What's "valid"?
</blockquote></details>

How about this `This function checks if the resource name (eg. directory) in the path is actually present.
Returns 1 on success and 0 on failure.`?
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRmc0p7WNt8P1jthJv:-MRIY9_OC2W1av3933DZ:b-8s4slt) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But the buffer we're providing here is not overlapping with anything? We allocated it right above.
</blockquote></details>

`get_base_name()` takes 2 `char` pointers right, one is `filename` which we allocated in this function and another one is `name`. `name` is passed from the user. But if you think there cannot be overlap, I will go ahead and remove the check in all the places where we call `get_base_name()`.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRqAwbCQAuCGaSI2Lm:-MRIZUS-6iCxD3GnI6ON:b766o22) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L119)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nah, this is less readable IMO ;) (but the previous struct, `cache_idx_dir`, looks very good after your reformatting)
</blockquote></details>

But wait, both are the same formatting style :) `cache_idx_dir` has multiple entries and `cpunum_cache_dir` just has a single entry. Are you suggesting we do multiple line formatting for single line entries such as these?
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSOO8CAIqSoTOi3Sp7:-MRI_w-e4WLz3G4ZSlU1:bigpsx1) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, that's what you mean in this comment. So, I'd just drop it altogether, I think it's quite obvious that it can't be declared in this block because it has only 2 lines and one of them is extracting the pointer to the outside.
</blockquote></details>

@dimakuv I remember you suggesting this. I am removing this comment but let me know if you want this comment back.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 19 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2lcXS1RWBo4iiyJWQ:-MRIaKoH8gdJbsmAj5UH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/src/fs/sys/cpu_info.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please remove this space
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI7lC9AfSonTAetp6m:-MRJ8854EXh8cuWJjOxi:b-kxojci) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> pal_control.topo_info.core_topology[cpunum].is_logical_core_online
> ```

This field is uninitialized for `cpunum == 0`.
</blockquote></details>

yes, I have added comments in the PAL layer where we read this info. But here I think it is better we return an error as this file will not be present in the system. Something like,
```
 if (cpunum == 0)
     return -ENOENT;
```
This will also make the code explicit regarding the uninitialized `cpunum == 0`
___
*[LibOS/shim/src/fs/sys/fs.c, line 64 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSRfpZC1EfMocIOA2s:-MRJFJa0BJwK7Eguu9GT:bwpy8ms) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/fs.c#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still, what about `nodeasdf`? Maybe I'm missing something, but won't this allow user applications to read from `/sys/something..something/nodeasdf` as if this was a correct path to a node information?
</blockquote></details>

one thing to note is, since we tokenize `token` can only be a single word something like `nodexyz120avads` but you are right, `strstartswith` is not sufficient. How about this?
```
    if (strstartswith(token, "node")) {
        snprintf(dirname, sizeof(dirname), "node%d", num);
        if (strcmp(token, dirname)) {
            ret = 0;
            goto out;
        }
        totalcnt = pal_control.topo_info.num_online_nodes;
    }
```
___
*[LibOS/shim/src/fs/sys/fs.c, line 16 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2meIe8s2ebuaIBq0S:-MRJH_ayCxhvfGbz4gs0:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/src/fs/sys/fs.c#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space
</blockquote></details>

Done
___
*[LibOS/shim/src/fs/sys/fs.c, line 30 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2muBPANLDFjCC9MWF:-MRJHaeR22MMhVk-JERq:b-qki79u) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/src/fs/sys/fs.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Note: Caller's responsibility to free returned buffer.
> ```

I'd drop this, it's obvious from the part that a copy is returned (there's no GC here, so if a copy is returned then the caller has to free it).
</blockquote></details>

ok, removed it.
___
*[LibOS/shim/src/fs/sys/fs.c, line 36 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2nGYO1iVf_DNGdV1n:-MRJZL2OEJj0yiAm6ubD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/src/fs/sys/fs.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you move this cop [...]

2021-01-19 10:10 UTC, dimakuv requested changes
> Reviewed 1 of 21 files at r9, 11 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 105 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPII0L0S7RpRVDZFgo:-MRP6eRw8rMcnv8NRBpe:b-bmufmt) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We're still allowing a lot of inconsistent information to be passed to the user app (see some comments in the review, but there's much more). It's quite hard to validate all of them properly, I think we should create an issue about this and discuss the problem there.

@yamahata @dimakuv Any thoughts?
</blockquote></details>

Yes, let's create an issue on this. This PR is getting too big to add more sanitization...

@vijaydhanraj Could you create an issue that says smth like `We pass a lot of information from host-level /sys/ files. We sanitize some values in some files, but not everything. Need to audit and add missing sanitizations, if any.` And please add a link to this PR.

---
___
*[LibOS/shim/include/shim_fs.h, line 561 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ipqX1LJ9_aarIXg1:-MROeKlT97-UoiVo0TmL:brun2z5) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L561)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

How about this `This function checks if the resource name (eg. directory) in the path is actually present.
Returns 1 on success and 0 on failure.`?
</blockquote></details>

Still hard to decipher. I suggest `check if pathname is a valid path under /sys/; returns 1 on success and 0 on failure`
___
*[LibOS/shim/include/shim_fs.h, line 565 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROe__aCIexRazbKNDv:-MROe__aCIexRazbKNDw:b7xteft) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L565)):*
> ```objc
> int sys_match_resource_num(const char* pathname);
> /* This function lists directory entries present in the pathname. Returns 0 on success and negative
>  * UNIX error on failure. */
> ```

Hard to decipher. I suggest `fill buf with an array of dirents for the given pathname (path under /sys/); return 0 on succes and negative error code otherwise`
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRmc0p7WNt8P1jthJv:-MROkkiA6qeU5OxGxDDl:b-x1a5ec) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`get_base_name()` takes 2 `char` pointers right, one is `filename` which we allocated in this function and another one is `name`. `name` is passed from the user. But if you think there cannot be overlap, I will go ahead and remove the check in all the places where we call `get_base_name()`.
</blockquote></details>

`name` is passed from the user but it cannot point inside the newly-allocated-on-stack `filename` (if it does, then there is a very serious bug of some stack buffer overflow). So yes, this check looks pointless. Since Michal doesn't like this redundant check, let's remove it.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRqAwbCQAuCGaSI2Lm:-MROm5Gv-GME778CJp2B:b-sccfar) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L119)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

But wait, both are the same formatting style :) `cache_idx_dir` has multiple entries and `cpunum_cache_dir` just has a single entry. Are you suggesting we do multiple line formatting for single line entries such as these?
</blockquote></details>

1 to Vijay, I don't see any problem with his current code.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 26 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSOO8CAIqSoTOi3Sp7:-MROf2z13xOHhy0zdAZB:b-6ckun3) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cpu_info.c#L26)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv I remember you suggesting this. I am removing this comment but let me know if you want this comment back.
</blockquote></details>

OK, I am fine with removing the comment.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI7lC9AfSonTAetp6m:-MROhxBx3MOlTKcBVmhP:bo0qcb0) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, I have added comments in the PAL layer where we read this info. But here I think it is better we return an error as this file will not be present in the system. Something like,
```
 if (cpunum == 0)
     return -ENOENT;
```
This will also make the code explicit regarding the uninitialized `cpunum == 0`

</blockquote></details>

Please add a comment here: `/* core 0 is always online, thus file /sys/devices/system/cpu/cpu0/online doesn't exist */`
___
*[LibOS/shim/src/fs/sys/fs.c, line 64 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSRfpZC1EfMocIOA2s:-MROoLb76Yvo47KVnLe9:b-x15znd) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/fs.c#L64)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

one thing to note is, since we tokenize `token` can only be a single word something like `nodexyz120avads` but you are right, `strstartswith` is not sufficient. How about this?
```
    if (strstartswith(token, "node")) {
        snprintf(dirname, sizeof(dirname), "node%d", num);
        if (strcmp(token, dirname)) {
            ret = 0;
            goto out;
        }
        totalcnt = pal_control.topo_info.num_online_nodes;
    }
```

</blockquote></details>

A bit ugly but I don't see any better way (we don't have regex). I'm ok with this.
___
*[LibOS/shim/src/fs/sys/fs.c, line 29 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROmhsW3Z4xGNxp3G9K:-MROmhsXCORfFdi_MisF:beez15z) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L29)):*
> ```C
> }
> 
> /* This function will extract "cpu105" from "cpu105/cache/index0/type". If string doesn't have "/"
> ```

Can you make it more explicit that we always return a new buffer: `/* This function will extract "cpu105" from "cpu105/cache/index0/type" and return it in a newly created buffer. If string...`
___
*[LibOS/shim/src/fs/sys/fs.c, line 113 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROp5SF0fqBZBJgfR4t:-MROp5SF0fqBZBJgfR4u:bryowg5) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L113)):*
> ```C
> 
>     if (!strcmp(filename, "node")) {
>         snprintf(res_name, sizeof(res_name), "node");
> ```

Looks like you don't need `res_name` anymore -- you already have the needed name in `filename`. Please remove the redundant var.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 235 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOsvIe0FIa9yqfCIIt:-MROqTQv3wEoDDSN5gkn:b9aa4k)  [...]

2021-01-19 12:23 UTC, mkow requested changes
> Reviewed 11 of 11 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 61 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/include/shim_fs.h, line 553 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ga-T1BNxYW4fl3vw:-MRPBhNR0elta2mF_tZ4:b6w2pmf) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L553)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think it should be "a", not "the"? (as suggested)
___
*[LibOS/shim/include/shim_fs.h, line 561 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ipqX1LJ9_aarIXg1:-MRPD8Pa10cEzLzm63wZ:br4tuhw) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L561)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still hard to decipher. I suggest `check if pathname is a valid path under /sys/; returns 1 on success and 0 on failure`
</blockquote></details>

+1 to Dmitrii's suggestion.
___
*[LibOS/shim/include/shim_fs.h, line 565 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROe__aCIexRazbKNDv:-MRPDLsjEr9stPk68cqh:bpg11vb) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L565)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hard to decipher. I suggest `fill buf with an array of dirents for the given pathname (path under /sys/); return 0 on succes and negative error code otherwise`
</blockquote></details>

+1 to Dmitrii's suggestion (modulo typo in `success` and `fill` ;) )
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRmc0p7WNt8P1jthJv:-MRPDaSKBSjx81jE8yCD:b-g3u7xs) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`name` is passed from the user but it cannot point inside the newly-allocated-on-stack `filename` (if it does, then there is a very serious bug of some stack buffer overflow). So yes, this check looks pointless. Since Michal doesn't like this redundant check, let's remove it.
</blockquote></details>

Yup, they aren't allowed to overlap.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRqAwbCQAuCGaSI2Lm:-MRPE-5tCMwDwBP8_ACi:b-p2z57j) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L119)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

1 to Vijay, I don't see any problem with his current code.
</blockquote></details>

Yeah, for single entries I prefer a different style ;) But Dmitrii likes the current one, so I'm unblocking.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI7lC9AfSonTAetp6m:-MRPES-I5BJOclqrG5Lk:b-ouwvfg) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment here: `/* core 0 is always online, thus file /sys/devices/system/cpu/cpu0/online doesn't exist */`
</blockquote></details>

+1 to adding a comment, this is quite a weird behavior of Linux
___
*[LibOS/shim/src/fs/sys/fs.c, line 64 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQSRfpZC1EfMocIOA2s:-MRPFHj6DFnfz90qHNhF:b-4lysw) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/fs.c#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A bit ugly but I don't see any better way (we don't have regex). I'm ok with this.
</blockquote></details>

Yeah, ugly but should do the work and I also don't have better ideas :)
___
*[LibOS/shim/src/fs/sys/fs.c, line 29 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROmhsW3Z4xGNxp3G9K:-MRPEfgpDJFuWl2tDO7z:bqjqax6) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you make it more explicit that we always return a new buffer: `/* This function will extract "cpu105" from "cpu105/cache/index0/type" and return it in a newly created buffer. If string...`
</blockquote></details>

but it already says: "a copy of original string is returned"?
___
*[LibOS/shim/src/fs/sys/fs.c, line 32 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPEubZ2sUzYRm_nU7U:-MRPEubZ2sUzYRm_nU7V:bagxch) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L32)):*
> ```C
>  * delimiter, a copy of original string is returned. */
> static char* extract_first_token_from_path(const char* pathname) {
>     if (pathname == NULL)
> ```

Do we need this check?
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPEnbUDmFmpUDzh3o3:-MRPEnbUDmFmpUDzh3o4:b-kfafa9) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L35)):*
> ```C
>         return NULL;
> 
>     int len;
> ```

should be `size_t`
___
*[LibOS/shim/src/fs/sys/fs.c, line 36 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPF1Dp3VeMSgPwavZN:-MRPF1Dp3VeMSgPwavZO:b-hwirug) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L36)):*
> ```C
> 
>     int len;
>     char *delim_ptr = strchr(pathname, '/');
> ```

`char *` -> `char* `
___
*[LibOS/shim/src/fs/sys/fs.c, line 109 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPI-eJ0lE4G4hz_SU7:-MRPI-eJ0lE4G4hz_SU8:b-4k8btq) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L109)):*
> ```C
>     size_t fsize = sizeof(filename);
>     int ret = get_base_name(pathname, filename, &fsize);
>     if (ret < 0 || (strlen(filename) != fsize))
> ```

ditto - no need for the `strlen()` check
___
*[LibOS/shim/src/fs/sys/fs.c, line 113 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROp5SF0fqBZBJgfR4t:-MRPIKji2uSMkWKp-yyL:b4x22f5) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like you don't need `res_name` anymore -- you already have the needed name in `filename`. Please remove the redundant var.
</blockquote></details>

(and these `sprintf`s)
___
*[Pal/include/arch/x86_64/pal-arch.h, line 235 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOsvIe0FIa9yqfCIIt:-MRPJBquBUE695mUWljr:b5ovbdn) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, why do we want it to be a dynamically allocated object? Why not just `PAL_CORE_CACHE_INFO cache[CPUCACHES_MAX];` and `C [...]

2021-01-20 16:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 61 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPII0L0S7RpRVDZFgo:-MRVWllK4OYuXbgSmpqt:b-8of3ht) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, let's create an issue on this. This PR is getting too big to add more sanitization...

@vijaydhanraj Could you create an issue that says smth like `We pass a lot of information from host-level /sys/ files. We sanitize some values in some files, but not everything. Need to audit and add missing sanitizations, if any.` And please add a link to this PR.
</blockquote></details>

Create an issue to track the sanitization efforts, https://github.com/oscarlab/graphene/issues/2105. Please let me know if anything else is needed.

---
___
*[LibOS/shim/include/shim_fs.h, line 553 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ga-T1BNxYW4fl3vw:-MRV7Js2Cf0AGXdSopVX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L553)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it should be "a", not "the"? (as suggested)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 561 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR2ipqX1LJ9_aarIXg1:-MRRPzgiCNqsg2b8D4ad:bs7wumb) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L561)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to Dmitrii's suggestion.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 565 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROe__aCIexRazbKNDv:-MRRQaB-Dv2GZS_5Rq-p:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/LibOS/shim/include/shim_fs.h#L565)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to Dmitrii's suggestion (modulo typo in `success` and `fill` ;) )
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 19 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRmc0p7WNt8P1jthJv:-MRRRYKk7CggVr0BFq8t:b-vrrg7b) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, they aren't allowed to overlap.
</blockquote></details>

I have removed the check.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 119 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQRqAwbCQAuCGaSI2Lm:-MRRUvIoD2DFzdBSAbvq:bxv4o05) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/LibOS/shim/src/fs/sys/cache_info.c#L119)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, for single entries I prefer a different style ;) But Dmitrii likes the current one, so I'm unblocking.
</blockquote></details>

Ok, will retain the existing formatting.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI7lC9AfSonTAetp6m:-MRRV0cj2ButcIW1cXJi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to adding a comment, this is quite a weird behavior of Linux
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 29 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROmhsW3Z4xGNxp3G9K:-MRRWAvA6oTukHL0ASMM:b-x6ddih) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

but it already says: "a copy of original string is returned"?
</blockquote></details>

I think the confusion may be because we say a copy is returned only when we don't have `/` delimiter. In cases where we have `/`, it might be ambiguous. I have added this comment for this revision, as I think it does make it more explicit.
___
*[LibOS/shim/src/fs/sys/fs.c, line 32 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPEubZ2sUzYRm_nU7U:-MRV83bu6Hkobw4ULCw7:bm8unzr) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we need this check?
</blockquote></details>

Actually, `pathname` should at least contain `/' so removing the check.
___
*[LibOS/shim/src/fs/sys/fs.c, line 35 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPEnbUDmFmpUDzh3o3:-MRV82_WBFQjgcS-q_gZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be `size_t`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 36 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPF1Dp3VeMSgPwavZN:-MRV8Enc5PMlPsPMtM_M:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`char *` -> `char* `
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 113 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROp5SF0fqBZBJgfR4t:-MRRXsq_9J41KxpePWyt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(and these `sprintf`s)
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 235 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOsvIe0FIa9yqfCIIt:-MRRYNq18HnompG_Nzja:bnat0jc) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L235)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with both leaving the current allocation scheme and with Dmitrii's proposal. If you want to keep the current version, then please change the comment to: `Array of size num_cache_index, owned by this struct`. Normally we don't add such annotations because there's no built-in support in C for them, but here I got lost when initially reading all the structs in this file (I wasn't sure what's the relation between them), so I think adding a comment will help.
</blockquote></details>

@dimakuv We have NUCs with `3 levels` desktop/server SKUs with `4 levels` so wanted to allocate it dynamically since we already know the number of levels present in a given system from `num_cache_index`. By allocating statically we might need to do more checks just to ensure we don't exceed the actual no. of cache levels. Libraries like `hwloc` blindly go ahead and read cache indices starting from 0 to 9 :).
@mkow I have updated the comment in the struct.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 237 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#- [...]

2021-01-21 08:59 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 64 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPII0L0S7RpRVDZFgo:-MRYwTW23rBCUPeXYCNm:bmj0bfd) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Create an issue to track the sanitization efforts, https://github.com/oscarlab/graphene/issues/2105. Please let me know if anything else is needed.
</blockquote></details>

Thanks, that's good!

---
___
*[LibOS/shim/src/fs/sys/fs.c, line 29 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROmhsW3Z4xGNxp3G9K:-MRYx2TiAOHIyBsRwbts:b-xlpgof) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L29)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think the confusion may be because we say a copy is returned only when we don't have `/` delimiter. In cases where we have `/`, it might be ambiguous. I have added this comment for this revision, as I think it does make it more explicit.
</blockquote></details>

OK. Yes, as Vijay explained, the previous text was confusing.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 235 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOsvIe0FIa9yqfCIIt:-MRYxik-EZZZ6vKc4jDc:bc8zdxn) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L235)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv We have NUCs with `3 levels` desktop/server SKUs with `4 levels` so wanted to allocate it dynamically since we already know the number of levels present in a given system from `num_cache_index`. By allocating statically we might need to do more checks just to ensure we don't exceed the actual no. of cache levels. Libraries like `hwloc` blindly go ahead and read cache indices starting from 0 to 9 :).
@mkow I have updated the comment in the struct.

</blockquote></details>

OK, Vijay, thanks. I didn't expect to got till 9, that's way too much statically allocated memory, so yes, let's keep it dynamic as is now. Btw, you forgot to update the comment per @mkow suggestion?
___
*[Pal/lib/string/atoi.c, line 125 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ8MYI3PBEJxYcMgJv:-MRZ8MYJ8kPGSt57f34t:b-odnhbm) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L125)):*
> ```C
>         val = -val;
>     if (endptr)
>         *endptr = (char*)(outrange ? s : str);
> ```

FYI, I compared to other implementations of strtoul:
- https://github.com/gcc-mirror/gcc/blob/master/libiberty/strtoul.c
- https://opensource.apple.com/source/Libc/Libc-166/stdlib.subproj/strtoul.c.auto.html

Your implementation looks correct.
___
*[Pal/src/host/Linux-common/topo_info.c, line 12 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPBS1aCsLRBQJcAlqv:-MRYy7_jAESX-yx69AL1:b-at2kv9) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/src/host/Linux-common/topo_info.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Almost, you need to separate include groups with an empty line ;)
</blockquote></details>

Marking as blocked as the empty line is not yet added.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 304 at r11](https://reviewable.io/reviews/oscarlab/graphene/1975#-MR4MGqwAI5LjvVU9Rvw:-MRZ41Xc60nceVH65kix:bd2ga0m) ([raw file](https://github.com/oscarlab/graphene/blob/213db4b25d9fb9dac85725867bc5af0366c3cbd7/Pal/src/host/Linux-SGX/db_main.c#L304)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

so there are 4 indexes (L1 Data, L1 code, L2, and L3) and levels are 3. Please see the below snapshot on the server platform.
```
$ cat /sys/devices/system/cpu/cpu0/cache/index0/level
1
$ cat /sys/devices/system/cpu/cpu0/cache/index1/level
1
$ cat /sys/devices/system/cpu/cpu0/cache/index2/level
2
$ cat /sys/devices/system/cpu/cpu0/cache/index3/level
3
```  
</blockquote></details>

OK. Thanks for explanation, I didn't know this.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 218 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI11Iu0RZ2CQvSfx1O:-MRZ-0wa7b2_k0LFsRnq:b2zv032) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/Pal/src/host/Linux-SGX/db_main.c#L218)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

There are 2 issues with this approach,
1. This doesn't handle cases where the buffer could have a greater than 64bits value as part of the map, something like `10000000000000000000, 80000000, 00000001`
2. We can make this work by having a limit check of say 8, but still this will not help other input types like `0-50,100-200,31515-13513513651366`.

I have implemented `strtoul` by extending our `strtol` and following hints from glibc as well as  https://code.woboq.org/gcc/libiberty/strtoul.c.html#1. I think this should help resolve the overflow issue.

@mkow : yes you are right, `80000000` will not fit into `long` on a 32-bit system. Using `strtoul` should help.
</blockquote></details>

OK, this is also a good way to solve the issue. And now we have the `strtoul()` implementation :) Thanks!
___
*[Pal/src/host/Linux-SGX/db_main.c, line 177 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROvcAk5tJRqFJbV_cC:-MRYzPUi1glb9uwCl1oY:b21rokg) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/Pal/src/host/Linux-SGX/db_main.c#L177)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, I did remove this on purpose because we don't have anything to compare against. Since the size can range from a few KBs to MBs or even GBs I wasn't sure of the upper limit to check. So just checking if the format is right like `32` or `32K`.
</blockquote></details>

Hm, well, yes, it's hard to decide on the correct upper bound for these /sys/ sizes. Ok, I don't have any better idea, resolving.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 283 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRP3mdk2j19VpnDoHUJ:-MRZ3bBe0bhg6rRrSR1r:bd82kat) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/Pal/src/host/Linux-SGX/db_main.c#L283)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

got it, thanks. Now I don't do the check.
</blockquote></details>

OK. The new check is a bit redundant, but why not.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 180 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ0sqD--jIemOyRqRB:-MRZ0sqD--jIemOyRqRC:bhuy4ww) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L180)):*
> ```C
>  * malformed Eg. 20abc or 3,4,5 or xyz123 or 512H.
>  * Use case: To extract int from /sys/devices/system/cpu/cpuX/cache/index0/size path. */
> static long extract_int_from_buffer(const char* buf) {
> ```

In these three functions, you use `long/unsigned long` and `int64_t/uint64_t` in a mixed manner. Let's use only one of these variants. I vote for `int64_t/uint64_t` (we typically use these explicit types in the rest of the codebase).

But if you go with `long/unsigned long`, I'm also fine. Just use this format in all three functions.
___
*[Pal/src/host/Linux-SGX/db_ma [...]

2021-01-21 09:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 65 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ9yOD3hLQUIAnfGaA:-MRZ9yOE2i4p9rx-hf4E:bqz2erv) (no related file):*
This PR became a crash course in integer overflows :( Hopefully, we're almost done with this.

---


<!-- Sent from Reviewable.io -->

2021-01-22 01:43 UTC, mkow reviewed
> Reviewed 9 of 10 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbeeeY9vDBFxbHixmD:-MRbeeeY9vDBFxbHixmE:b-wt2zyc) (no related file):*
Note to myself: Do one more round of security review on the final version before merging (especially w.r.t. int overflows).

---
___
*[LibOS/shim/src/fs/sys/fs.c, line 29 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MROmhsW3Z4xGNxp3G9K:-MRbKgEk7yJo85eYK1Ui:b6hmpv2) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/LibOS/shim/src/fs/sys/fs.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. Yes, as Vijay explained, the previous text was confusing.
</blockquote></details>

Oh, I see now. Yes, it was confusing, I just didn't notice the problem.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 235 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOsvIe0FIa9yqfCIIt:-MRbNSE7ENwBJjP8iu98:b-rybug2) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L235)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, Vijay, thanks. I didn't expect to got till 9, that's way too much statically allocated memory, so yes, let's keep it dynamic as is now. Btw, you forgot to update the comment per @mkow suggestion?
</blockquote></details>

Yup, I don't see the comment update.
___
*[Pal/lib/string/atoi.c, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbNjdYBIDkIAGoX4Ez:-MRbNjdYBIDkIAGoX4F-:bm0wn7g) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L72)):*
> ```C
> unsigned long strtoul(const char* str, char** endptr, int base) {
>     const char* s = str;
>     int neg  = 0;
> ```

double space
___
*[Pal/lib/string/atoi.c, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbNqmrBB56Zzj9gEdL:-MRbNqmrBB56Zzj9gEdM:bisjyoo) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L72)):*
> ```C
> unsigned long strtoul(const char* str, char** endptr, int base) {
>     const char* s = str;
>     int neg  = 0;
> ```

please make it `bool` and use `true`/`false`
___
*[Pal/lib/string/atoi.c, line 76 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbONG86J6c_l1Hz1rZ:-MRbONG86J6c_l1Hz1r_:bxz5f3m) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L76)):*
> ```C
>     unsigned long val;
> 
>     // gobble initial whitespace
> ```

Where was this code copied from? We need to check licensing + mention copyright in the file.
___
*[Pal/src/host/Linux-common/topo_info.c, line 124 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRHpVAd3aRJWz3y_XI6:-MRbPHj97746kVDU2kY9:b-aolsdv) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/Pal/src/host/Linux-common/topo_info.c#L124)):*
> can either return a negative unix error code or can return a count which at most can only be 1024

But you have a loop there. You read in _chunks_ of max 1024 bytes until EOF.

Anyways, I see now that this whole logic happens on the untrusted side. I got fooled by this `num_cache_index = num_cache_lvl` assignment (didn't notice that they have different names and thus failed to find the sanitization).
___
*[Pal/src/host/Linux-common/topo_info.c, line 121 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPN4bW5FmVvO57Rrs_:-MRbOoK64-a3SHkGt9zm:b-942w8r) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/Pal/src/host/Linux-common/topo_info.c#L121)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I don't see a wrapping issue here but did find some lines exceeding 100 characters in this and have fixed it.
</blockquote></details>

Yeah, for some reason my line-length setting on Reviewable changed and I noticed it much later. Looks ok.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 225 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI5bKsBsePLEG1TIwS:-MRbbjBx8TUF_nMEMb0J:b-8zf4c) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/Pal/src/host/Linux-SGX/db_main.c#L225)):*
> huge huge buffer with valid 64bit maps

This is technically infeasible currently, but the margin (i.e. how much time would it take to overflow it) is quite narrow, so I'd still guard this addition. This IMO may turn into a vulnerability in the future.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 399 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRPYW036-iJeAUvzD0G:-MRbi9QC499t0uiFy9-H:b-h1efu1) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/Pal/src/host/Linux-SGX/db_main.c#L399)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here as well I don't see it go above 100. But have fixed few that did exceed 100 characters limit. But certain I have kept so that the code doesn't look awkward.

For example, this `/* Now that enclave memory is set up, parse and store host topology info into g_pal_sec struct */`. The last backslash does exceed the 100 character marker. So in such cases, I did wrap but these are in very few places.
</blockquote></details>

Ok with me.
Ad the original comment, as I wrote above, it was a misconfiguration on my side, sorry ;)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 180 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ0sqD--jIemOyRqRB:-MRbRWRa0KnW8xH4MP_V:bv4jwr9) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In these three functions, you use `long/unsigned long` and `int64_t/uint64_t` in a mixed manner. Let's use only one of these variants. I vote for `int64_t/uint64_t` (we typically use these explicit types in the rest of the codebase).

But if you go with `long/unsigned long`, I'm also fine. Just use this format in all three functions.
</blockquote></details>

I don't like `long`, because it's size can vary. If there's no good reason for using it, then we should use types of known size.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 201 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbTANxCSKF9wX98ZhD:-MRbTANxCSKF9wX98ZhE:b-53z88s) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L201)):*
> ```
> Returns 0 on error and actual count on success.
> ```

What if we have no bits set?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 231 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbcHi_-46Y2nb6yW6u:-MRbcHia2gZlE5AxWIaV:b-c5zbje) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L231)):*
> ```
> if buf is empty or contains invalid data on failure
> ```

The "on failure" doesn't fit this whole sentence well (you already said "if buf is empty or contains invalid data" right before it).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 290 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ4yzC0Rv8ZFAJeDPy:-MRbePNK-iWunH3vEbwn:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/042046491 [...]

2021-01-22 07:01 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 30 of 35 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 235 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOsvIe0FIa9yqfCIIt:-MRcPx5p2x4MOD36FzCh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L235)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, I don't see the comment update.
</blockquote></details>

Done.
___
*[Pal/lib/string/atoi.c, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbNqmrBB56Zzj9gEdL:-MRcQBFPBUMcUeYbcFkO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please make it `bool` and use `true`/`false`
</blockquote></details>

Done.
___
*[Pal/lib/string/atoi.c, line 76 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbONG86J6c_l1Hz1rZ:-MRcQMIPDHV55nXCTMSn:bkrsg8q) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Where was this code copied from? We need to check licensing + mention copyright in the file.
</blockquote></details>

I had adapted the code from, https://github.com/gcc-mirror/gcc/blob/master/libiberty/strtoul.c. But I am not sure what parts to copy.
___
*[Pal/src/host/Linux-common/topo_info.c, line 12 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPBS1aCsLRBQJcAlqv:-MRaNndqAlrZK1isHnO-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/src/host/Linux-common/topo_info.c#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Marking as blocked as the empty line is not yet added.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 111 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPDHcM2mxlQIQT7a3S:-MRaOgQp6NYVYCGtrJaf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/src/host/Linux-common/topo_info.c#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You need to drop `== 0`, `strstartswith` returns a `bool`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 124 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRHpVAd3aRJWz3y_XI6:-MRcRVNvA4ays4RTucc7:b-w5ch41) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/Pal/src/host/Linux-common/topo_info.c#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> can either return a negative unix error code or can return a count which at most can only be 1024

But you have a loop there. You read in _chunks_ of max 1024 bytes until EOF.

Anyways, I see now that this whole logic happens on the untrusted side. I got fooled by this `num_cache_index = num_cache_lvl` assignment (didn't notice that they have different names and thus failed to find the sanitization).
</blockquote></details>

Ok, we will leave this logic as is then.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 225 at r12](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRI5bKsBsePLEG1TIwS:-MRcSDtYBhNJt-ywK9HS:b-hhsdtt) ([raw file](https://github.com/oscarlab/graphene/blob/318e78c6847995e636d3cb42fd0dff38d6ff5633/Pal/src/host/Linux-SGX/db_main.c#L225)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> huge huge buffer with valid 64bit maps

This is technically infeasible currently, but the margin (i.e. how much time would it take to overflow it) is quite narrow, so I'd still guard this addition. This IMO may turn into a vulnerability in the future.
</blockquote></details>

Added the below check to gaurd count.
```
if (count > LONG_MAX)
    return -EINVAL;
```
___
*[Pal/src/host/Linux-SGX/db_main.c, line 283 at r13](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRP3mdk2j19VpnDoHUJ:-MRaTzHb5v3pjNzsdHk_:b-d6extm) ([raw file](https://github.com/oscarlab/graphene/blob/b6f7bd40d3f824477427c8362bbfbed95b6e4917/Pal/src/host/Linux-SGX/db_main.c#L283)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. The new check is a bit redundant, but why not.
</blockquote></details>

yes, it may be redundant here but I have moved this check before returning to catch if the `buf == NULL`. The expectation is that this function should return a value greater than 0.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 180 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ0sqD--jIemOyRqRB:-MRapThA2rd50ntzioaa:bbs6xfe) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like `long`, because it's size can vary. If there's no good reason for using it, then we should use types of known size.
</blockquote></details>

I do agree with using explicit types but in these 3 functions, we use `str_to_unsigned` fn to extract the buffer which returns unsigned long. The reason being some inputs to this function can be a cpumask and the length of this can be host arch dependant. Due to this, I prefer to use the `long/unsigned long` just for these 3 functions and I have converted to `int64_t` for the rest. 

One thing to note. I have renamed `count_uint64_bits_set` to `count_uint_bits_set` as input to this is an `unsigned long` variable.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 201 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ-oBkAeL6D4l7qRDq:-MRc4dYE4iY9JVJryXRg:budkkp8) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, why did you change the return type here? I think we should have `long` as the return type and return `-EINVAL` as before on parsing errors, and actual count on success.

If you got confused by our suggestion to use `uint64_t`, then this suggestion was only about the *parsed numbers in buf*, not about the return value of this function.
</blockquote></details>

I have changed this to return a `long` along with few other changes. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 201 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbTANxCSKF9wX98ZhD:-MRcTFXRAYiZG8wFgXpQ:bmyb0s5) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L201)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Returns 0 on error and actual count on success.
> ```

What if we have no bits set?
</blockquote></details>

`0` will be returned if no bit is set. A negative UNIX error code is returned on failure.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 213 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ-BSD45YOH3RMNBJT:-MRcAk6V75VDXF-kcCQu:b-440cb7) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L213)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i> [...]

2021-01-22 14:42 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/lib/string/atoi.c, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbNqmrBB56Zzj9gEdL:-MReVdb101gX7_lqCFl5:b-mddd0i) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L72)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. `int neg` -> `bool neg`.
___
*[Pal/src/host/Linux-common/topo_info.c, line 111 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPDHcM2mxlQIQT7a3S:-MReW3XQE4KQOwSNxNZ1:bfhqmln) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/src/host/Linux-common/topo_info.c#L111)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 290 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ4yzC0Rv8ZFAJeDPy:-MReXktN8aEfQB-2vbe6:b2c0zcb) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L290)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Ok, I have changed all the functions to use `int64_t`except the 3 helper functions which use `str_to_unsigned()`. I have added comments in these functions to say that we are intentionally using `long/unsigned long` due to adapt for variable bitness. Hope this helps.
</blockquote></details>

LGTM, thanks!
___
*[Pal/src/host/Linux-SGX/db_main.c, line 282 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MReXLdi37jCUZJZuNhI:-MReXLdi37jCUZJZuNhJ:bkftgri) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/src/host/Linux-SGX/db_main.c#L282)):*
> ```C
>                 diff = secondint - firstint;
>                 if (diff >= LONG_MAX ||
>                     (resource_cnt + diff + 1) > LONG_MAX)
> ```

Now you can fix the wrapping (both if clauses in one line)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 288 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MReXTk9AdF8gYd7dkyV:-MReXTk9AdF8gYd7dkyW:bkftgri) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/src/host/Linux-SGX/db_main.c#L288)):*
> ```C
>                 diff = firstint - secondint;
>                 if (ordered || diff >= LONG_MAX ||
>                    (resource_cnt + diff + 1) > LONG_MAX)
> ```

Now you can fix the wrapping (both if clauses in one line)


<!-- Sent from Reviewable.io -->

2021-01-22 17:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 32 of 35 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/lib/string/atoi.c, line 72 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbNqmrBB56Zzj9gEdL:-MRf1UIj2QmnZohCbgFY:bay1egd) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done. `int neg` -> `bool neg`.
</blockquote></details>

hmm, might have missed to save, done now.
___
*[Pal/src/host/Linux-common/topo_info.c, line 111 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQPDHcM2mxlQIQT7a3S:-MRf1jn50OHviuJkluMZ:bbqqaoh) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/src/host/Linux-common/topo_info.c#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

done now.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 282 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MReXLdi37jCUZJZuNhI:-MRf1sI8-dPgaw1ps8nO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/src/host/Linux-SGX/db_main.c#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you can fix the wrapping (both if clauses in one line)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 288 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MReXTk9AdF8gYd7dkyV:-MRf1t9QDSd3uqMgnxnT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/src/host/Linux-SGX/db_main.c#L288)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you can fix the wrapping (both if clauses in one line)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-25 08:53 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 91 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsiYn03mdNfc4tqiCQ:-MRsiYn10VpJtxfqI0Wu:b37w8ls) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L91)):*
> ```C
>  * `/sys/devices/system/cpu/cpuX/cache` on success and negative UNIX error code on failure. */
> static int get_num_cache_level(const char* path) {
>     char buf[1024];
> ```

Just noticed a couple issues in this function.

Here, let's zero out the buffer for sanity: `char buf[1024] = {0};`.
___
*[Pal/src/host/Linux-common/topo_info.c, line 104 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsihCaC_ewGU09EhZb:-MRsihCaC_ewGU09EhZc:b-5gl300) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L104)):*
> ```C
>         nread = INLINE_SYSCALL(getdents64, 3, fd, buf, 1024);
>         if (IS_ERR(nread))
>             return -ERRNO(nread);
> ```

This leaks `fd` (there is no corresponding close). Please add a goto label (`out: `) at the bottom of this function and do this here:
```
if (IS_ERR(nread)) {
    num_dirs = -ERRNO(nread);
    goto out;
}
```
___
*[Pal/src/host/Linux-common/topo_info.c, line 113 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsixMo3ZCmPawNideM:-MRsixMo3ZCmPawNideN:b-ry1jcl) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L113)):*
> ```C
>             if (dirent64->d_type == DT_DIR && strstartswith(dirent64->d_name, "index"))
>                 num_dirs++;
>             bpos += dirent64->d_reclen;
> ```

There can be a half-read `dirent64` in the buffer (because `getdents64()` returned only a half-read contents). So this can be equal to `0`, and we have an infinite while loop.

I suggest to add this:
```
if (dirent64->d_reclen == 0) {
    num_dirs = -EINVAL;
    goto out;
}
```
___
*[Pal/src/host/Linux-common/topo_info.c, line 116 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsjIWh6jfwGwYG7lm8:-MRsjIWh6jfwGwYG7lm9:b-qnc8y7) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L116)):*
> ```C
>         }
>     }
> ```

The below code must be under a goto:
```
out:
    INLINE_SYSCALL(close, 1, fd);
    return num_dirs ?: -ENOENT;
```


<!-- Sent from Reviewable.io -->

2021-01-25 14:43 UTC, mkow requested changes
> Reviewed 2 of 5 files at r15, 3 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 259 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOv9tg7RPeKApF2mIH:-MRecAJb6G8ehaJDe_oX:b8ylgtb) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L259)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

pls refer to the earlier comment on ownership.
</blockquote></details>

any updates on this? ;)
___
*[Pal/include/arch/x86_64/pal-arch.h, line 50 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRec6ku6J0IK2W7YJs4:-MRec6ku6J0IK2W7YJs5:b7bpst1) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/include/arch/x86_64/pal-arch.h#L50)):*
> ```objc
> }
> 
> static inline unsigned long count_uint_bits_set(unsigned long x) {
> ```

`uint` -> `ulong`
___
*[Pal/include/lib/api.h, line 145 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRecWJP6PGZ22_dlb69:-MRecWJP6PGZ22_dlb6A:b-5va7zs) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/include/lib/api.h#L145)):*
> ```objc
> long strtol(const char* s, char** endptr, int base);
> long long strtoll(const char* s, char** endptr, int base);
> bool str_to_unsigned(const char* str, int base, unsigned long* out_value, char** out_endptr);
> ```

`str_to_unsigned` -> `str_to_ulong` (sorry I missed this in the chat, we got into the discussion about types and I overlooked this)
There's a type `unsigned` already in C, so it may be confusing (that this function returns `unsigned`, not `unsigned long`)
___
*[Pal/lib/string/atoi.c, line 76 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbONG86J6c_l1Hz1rZ:-MRty4o42JMXmI9m63jG:bie7nyw) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L76)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I had adapted the code from, https://github.com/gcc-mirror/gcc/blob/master/libiberty/strtoul.c. But I am not sure what parts to copy.
</blockquote></details>

Ok, sounds good, but you need to also update LICENSE.addendum.txt and add your copyright to this file (as this isn't a 1-1 copy).
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRtz00F8OEBO-ntQSyU:b-8psw4k) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
> ```C
>     }
> 
>     // plus/minus sign
> ```

Why do we have this? Seems this whole function can be made _much_ simpler if we drop this unused thing.
___
*[Pal/src/host/Linux-common/topo_info.c, line 91 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsiYn03mdNfc4tqiCQ:-MRtxkMOAPa_zj-xzc35:b5ajlla) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed a couple issues in this function.

Here, let's zero out the buffer for sanity: `char buf[1024] = {0};`.
</blockquote></details>

I'd skip it in this particular case, as the buffer is considerably large.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 201 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbTANxCSKF9wX98ZhD:-MRgBVjdChKzuwP4cpOE:b-vk1uh9) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L201)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`0` will be returned if no bit is set. A negative UNIX error code is returned on failure.
</blockquote></details>

Ok, new version makes more sense.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 249 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ2m2kAhtV6ac_5uDI:-MRgCwWoBtrhF_GBrha2:b-fg8whh) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L249)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, correct. I don't think `0-0` is a legal range. The reason being these represent core ids and we cannot have 2 cores having the same number.  
</blockquote></details>

@dimakuv From what I understand, one-element ranges are represented just as `X`, not `X-X` in this format.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 175 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgAt4U6i9JkYwiOmBY:-MRgAt4U6i9JkYwiOmBZ:b1ufds1) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L175)):*
> ```C
> extern void* g_enclave_top;
> 
> /* This function extracts first found integer present in the buffer. For example 31 will be returned
> ```

`first found integer` -> `first positive found integer` (you're returning `long`, but actually not accept negative numbers, so this is quite confusing)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 180 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgAkVk8is8IU6QenC2:-MRgAkVlBlvmyEXBWC_p:b-w3943l) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L180)):*
> ```C
>  * malformed Eg. 20abc or 3,4,5 or xyz123 or 512H.
>  * Use case: To extract int from /sys/devices/system/cpu/cpuX/cache/index0/size path. */
> static long extract_int_from_buffer(const char* buf) {
> ```

`int` -> `long`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 185 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgB84WAZoBlLc4zHVI:-MRgB84WAZoBlLc4zHVJ:bj13z8a) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L185)):*
> ```C
> 
>     /* Intentionally using unsigned long to adapt for variable bitness. */
>     str_to_unsigned(buf, 10, &intval, &end);
> ```

forgot to check retval?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 215 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgBw_1A4GCEVA_KiLr:-MRgBw_1A4GCEVA_KiLs:b-szi4gx) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L215)):*
> ```C
> 
>         char* end = NULL;
>         /* Linux uses different bitmap sizes(4/8 bytes) depending on the host arch. We intentionally
> ```

`sizes(` -> `sizes (`
Actually, I don't think this is just 4 or 8, it's rather the size of `long` on GCC for this particular arch. So maybe just drop the whole parenthesis?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 253 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgCdeFDLaYACmNkxp8:-MRgCdeFDLaYACmNkxp9:b-r0detd) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L253)):*
> ```C
>         unsigned long firstint;
>         /* Intentionally using unsigned long to adapt for variable bitness. */
>         str_to_unsigned(buf, 10, &firstint, &end);
> ```

forgot retval check?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 271 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgD5VWEJM7UN7gXscz:-MRgD5VX-z7fh2QsPDV-:b-hbr9dy) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L2 [...]

2021-01-25 18:25 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 30 of 35 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 259 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOv9tg7RPeKApF2mIH:-MRu_34qAw0wNA3OSHpR:bozpddx) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L259)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

any updates on this? ;)
</blockquote></details>

Added the below comment.
```
    PAL_CORE_TOPO_INFO* core_topology; /* Array of logical core topology info, owned by this struct */
    PAL_NUMA_TOPO_INFO* numa_topology; /* Array of numa topology info, owned by this struct */
```

Here `*/`part of the comment exceeds the 100 characters as I think it makes sense to have it on the side rather than on top, I hope this is fine.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 50 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRec6ku6J0IK2W7YJs4:-MRuWsP9BxURMZuSQBHn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/include/arch/x86_64/pal-arch.h#L50)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`uint` -> `ulong`
</blockquote></details>

Done.
___
*[Pal/include/lib/api.h, line 145 at r15](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRecWJP6PGZ22_dlb69:-MRuXeO57l4b_cd3NisV:b-szhbky) ([raw file](https://github.com/oscarlab/graphene/blob/c8719873cffc296ea6c7a5accc94bde398725e95/Pal/include/lib/api.h#L145)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`str_to_unsigned` -> `str_to_ulong` (sorry I missed this in the chat, we got into the discussion about types and I overlooked this)
There's a type `unsigned` already in C, so it may be confusing (that this function returns `unsigned`, not `unsigned long`)
</blockquote></details>

sure, done.
___
*[Pal/lib/string/atoi.c, line 76 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbONG86J6c_l1Hz1rZ:-MRu_j0V1dI6ERydaCl-:b-gw0d8z) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, sounds good, but you need to also update LICENSE.addendum.txt and add your copyright to this file (as this isn't a 1-1 copy).
</blockquote></details>

`LICENSE.addendum.txt` already has `Pal/lib/string/atoi.c` listed. I have also added the below to the file header.
```
   Copyright (C) 2021 Intel Corporation
                     Vijay Dhanraj <vijay.dhanraj@intel.com>
```
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRueVX21wdMUesodhJ0:bbrroco) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do we have this? Seems this whole function can be made _much_ simpler if we drop this unused thing.
</blockquote></details>

Agree for this implementation we don't use `+/-` sign but since this is a common library function it might be better to use the generic implementation. We do have similar logic even in our implementation of `strtol`.
___
*[Pal/src/host/Linux-common/topo_info.c, line 91 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsiYn03mdNfc4tqiCQ:-MRuQg8K5GrpkYbcqWc_:b-gvkqgm) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd skip it in this particular case, as the buffer is considerably large.
</blockquote></details>

I am fine with either option, but I think we will not have an issue here even if we don't initialize as we only read up to `nread` size from `buf` which should have valid data. @dimakuv what do you think?
___
*[Pal/src/host/Linux-common/topo_info.c, line 104 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsihCaC_ewGU09EhZb:-MRuR-vA3_kYYyIxhwHF:b-u7c3dn) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This leaks `fd` (there is no corresponding close). Please add a goto label (`out: `) at the bottom of this function and do this here:
```
if (IS_ERR(nread)) {
    num_dirs = -ERRNO(nread);
    goto out;
}
```
</blockquote></details>

yes, correct this can cause a leak in case `getdents64` failure. I have added this check.
___
*[Pal/src/host/Linux-common/topo_info.c, line 113 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsixMo3ZCmPawNideM:-MRuRFTs7L6_6_1CZI0l:b-78w3hr) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There can be a half-read `dirent64` in the buffer (because `getdents64()` returned only a half-read contents). So this can be equal to `0`, and we have an infinite while loop.

I suggest to add this:
```
if (dirent64->d_reclen == 0) {
    num_dirs = -EINVAL;
    goto out;
}
```
</blockquote></details>

Sorry, I don't understand how `dirent64->d_reclen` can be `0`. Agree that `getdents64` can return a partially filled buffer but I think those partially filled buffers will be valid else the `getedents64` should have returned `-1` because we cannot make any sense from a partially filled `dirent64` struct. I think the `dirent64` struct will be properly filled for the ones `getdents64` has returned. Also, I don't see such a case mentioned in the man pages. Can you please clarify? 
___
*[Pal/src/host/Linux-common/topo_info.c, line 116 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsjIWh6jfwGwYG7lm8:-MRuUMyEEc8ixD9wNy5d:bh04zis) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The below code must be under a goto:
```
out:
    INLINE_SYSCALL(close, 1, fd);
    return num_dirs ?: -ENOENT;
```
</blockquote></details>

yes, done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 175 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgAt4U6i9JkYwiOmBY:-MRug5fxAyTILQcgqsqD:b-ad7czs) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L175)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`first found integer` -> `first positive found integer` (you're returning `long`, but actually not accept negative numbers, so this is quite confusing)
</blockquote></details>

sure let us just have it as `first positive integer`. `found` seems a little redundant here. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 180 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgAkVk8is8IU6QenC2:-MRuhVto075wYweE76v6:bhozuva) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`int` -> `long`
</blockquote></de [...]

2021-01-25 20:20 UTC, mkow requested changes
> Reviewed 5 of 5 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 259 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOv9tg7RPeKApF2mIH:-MRv1EdW05JXVlFXtsCh:b-h4gc1d) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L259)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Added the below comment.
```
    PAL_CORE_TOPO_INFO* core_topology; /* Array of logical core topology info, owned by this struct */
    PAL_NUMA_TOPO_INFO* numa_topology; /* Array of numa topology info, owned by this struct */
```

Here `*/`part of the comment exceeds the 100 characters as I think it makes sense to have it on the side rather than on top, I hope this is fine.
</blockquote></details>

yeah, I'm fine with this
___
*[Pal/lib/string/atoi.c, line 76 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbONG86J6c_l1Hz1rZ:-MRv70nu1fbn8iO0Ok4a:b-typq6z) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/lib/string/atoi.c#L76)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`LICENSE.addendum.txt` already has `Pal/lib/string/atoi.c` listed. I have also added the below to the file header.
```
   Copyright (C) 2021 Intel Corporation
                     Vijay Dhanraj <vijay.dhanraj@intel.com>
```
</blockquote></details>

Ah, right, I forgot that this isn't a new file.
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRv76s4A8ydiVfPx7Zo:b-w5h34u) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Agree for this implementation we don't use `+/-` sign but since this is a common library function it might be better to use the generic implementation. We do have similar logic even in our implementation of `strtol`.
</blockquote></details>

What do you mean by "generic"? Parsing negative numbers doesn't make sense in "parse to ulong".
___
*[Pal/lib/string/atoi.c, line 20 at r17](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRv2L42AwSCQ6yEAscu:-MRv2L442yuN-sjEiO_u:b-b9f27x) ([raw file](https://github.com/oscarlab/graphene/blob/0252ba8279d0cf1fa906fd71db9bfee15fa35896/Pal/lib/string/atoi.c#L20)):*
> ```C
> 
>    Copyright (C) 2021 Intel Corporation
>                      Vijay Dhanraj <vijay.dhanraj@intel.com>
> ```

Could you reformat + realign this to match 1-1 the style we use in other files?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 175 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgAt4U6i9JkYwiOmBY:-MRv7x5U1quHv1sB3KRH:b-ul8jrf) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L175)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

sure let us just have it as `first positive integer`. `found` seems a little redundant here. 
</blockquote></details>

Good idea
___
*[Pal/src/host/Linux-SGX/db_main.c, line 180 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgAkVk8is8IU6QenC2:-MRv81ABClFPdWjhUFVj:b-7fh3th) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L180)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Are you referring to the function name? If so, `int` here means integer (just any whole number). This is what we have mentioned in the comment as well. I did expand `int` -> `integer` in the comment.
</blockquote></details>

Yup, I mean the function name. I guessed that this is the meaning you used here, but it's confusing in C, where you have a type with exactly the same name. So, reading such a code, I'd expect that this means it parses a buffer into `int` type (especially in C where you don't have name overloading and you often include the types in the function names).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 185 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgB84WAZoBlLc4zHVI:-MRvB3qW-PgE3QQjjj-i:bfg5tz0) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L185)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No, this is done intentionally. The return value is basically to differentiate if we have a valid `ULONG_MAX` or if an overflow has occurred. But here we have this check `firstint > LONG_MAX`to catch any huge values which is not expected. 
</blockquote></details>

Ah. Could you document this semantic in the header which declares `str_to_ulong`? Usually you can't use results from functions which returned an error.


<!-- Sent from Reviewable.io -->

2021-01-25 21:54 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRvOz5c3NuiTtj-Uznz:b-47y10d) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean by "generic"? Parsing negative numbers doesn't make sense in "parse to ulong".
</blockquote></details>

In general, the string can have positive or negative numbers right, and if `strtoul` encounters such strings then it simply casts the result to an unsigned integer. Our implementation of `str_to_ulong` mimics this generic behavior.

https://www.gnu.org/software/libc/manual/html_node/Parsing-of-Integers.html#:~:text=If%20string%20depicts%20a%20negative,ULONG_MAX%20%2B%201)%20%2F%202.

gcc implementation: https://github.com/gcc-mirror/gcc/blob/master/libiberty/strtoul.c

But yes in our sanitization function, we don't expect any negative values and this is enforced through our range checks which will catch negative values and throw an `-EINVAL` error.
___
*[Pal/lib/string/atoi.c, line 20 at r17](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRv2L42AwSCQ6yEAscu:-MRvJhF99ZfwvxIaynuZ:biuzl60) ([raw file](https://github.com/oscarlab/graphene/blob/0252ba8279d0cf1fa906fd71db9bfee15fa35896/Pal/lib/string/atoi.c#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you reformat + realign this to match 1-1 the style we use in other files?
</blockquote></details>

sorry not sure what is 1-1 style. Do you mean something like below? If not, can you please point me to an example?
```
/* SPDX-License-Identifier: LGPL-3.0-or-later */
/* Copyright (C) 2021 Intel Corporation
 *                    Vijay Dhanraj <vijay.dhanraj@intel.com>
 */
```
___
*[Pal/src/host/Linux-SGX/db_main.c, line 180 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgAkVk8is8IU6QenC2:-MRvQf2284M6LUTHcQRK:bsrppby) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, I mean the function name. I guessed that this is the meaning you used here, but it's confusing in C, where you have a type with exactly the same name. So, reading such a code, I'd expect that this means it parses a buffer into `int` type (especially in C where you don't have name overloading and you often include the types in the function names).
</blockquote></details>

ok, I have renamed `int->long`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 185 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRgB84WAZoBlLc4zHVI:-MRvUQOJ-Ha86Cx3ielC:btddzki) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-SGX/db_main.c#L185)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah. Could you document this semantic in the header which declares `str_to_ulong`? Usually you can't use results from functions which returned an error.
</blockquote></details>

Added the below comment.
```
/* Converts a string to an unsigned long value. Sets out_value to ULONG_MAX and returns true if
 * overflow occurred and false otherwise. */
```


<!-- Sent from Reviewable.io -->

2021-01-25 22:34 UTC, dimakuv requested changes
> Reviewed 2 of 5 files at r17, 3 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Examples/openvino/object_detection_sample_ssd.manifest.template, line 113 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvcz3t2Vrj5z6kw2cB:-MRvcz3t2Vrj5z6kw2cC:b-8rdpio) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/Examples/openvino/object_detection_sample_ssd.manifest.template#L113)):*
> ```
> sgx.trusted_files.libopencvcore = "file:$(OPENVINO_DIR)/inference-engine/temp/opencv_4.3.0_ubuntu18/opencv/lib/libopencv_core.so.4.3"
> 
> #OpenVINO TBB dependencies
> ```

Please add a space after `#`
___
*[LibOS/shim/test/regression/sysfs_common.c, line 78 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvdWLt6xy9T5P01Xas:-MRvdWLt6xy9T5P01Xat:b-tm9sx9) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/LibOS/shim/test/regression/sysfs_common.c#L78)):*
> ```C
>     display_file_contents("/sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages");
> 
>     /* Read L1 data, L1 Instruction and L2 cache type*/
> ```

please add a space before `*/`
___
*[LibOS/shim/test/regression/sysfs_common.c, line 81 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvdSnx7p8pZm7k80BC:-MRvdSnx7p8pZm7k80BD:b-yoe134) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/LibOS/shim/test/regression/sysfs_common.c#L81)):*
> ```C
>     for (int lvl = 0; lvl < 3; lvl++) {
>         snprintf(path, sizeof(path),"/sys/devices/system/cpu/cpu%ld/cache/index%d/type",
>                  maxprocs-1, lvl);
> ```

Could add spaces around `-` here
___
*[LibOS/shim/test/regression/sysfs_common.c, line 144 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvddTg554G-m_RQWbB:-MRvddTg554G-m_RQWbC:b-e18n11) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/LibOS/shim/test/regression/sysfs_common.c#L144)):*
> ```C
>     errno = 0;
>     while ((dirent = readdir(dir))) {
>         printf("/sys/devices/system/node/%s \n", dirent->d_name);
> ```

Please remove a space before `\n`
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRveC6K7fIry70wRoSp:bv0infl) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

In general, the string can have positive or negative numbers right, and if `strtoul` encounters such strings then it simply casts the result to an unsigned integer. Our implementation of `str_to_ulong` mimics this generic behavior.

https://www.gnu.org/software/libc/manual/html_node/Parsing-of-Integers.html#:~:text=If%20string%20depicts%20a%20negative,ULONG_MAX%20%2B%201)%20%2F%202.

gcc implementation: https://github.com/gcc-mirror/gcc/blob/master/libiberty/strtoul.c

But yes in our sanitization function, we don't expect any negative values and this is enforced through our range checks which will catch negative values and throw an `-EINVAL` error.
</blockquote></details>

I'm fine either way, I'll let Michal decide.
___
*[Pal/src/host/Linux-common/topo_info.c, line 91 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsiYn03mdNfc4tqiCQ:-MRveVQp9Z-8yNOjlErb:bxjcfp4) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L91)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I am fine with either option, but I think we will not have an issue here even if we don't initialize as we only read up to `nread` size from `buf` which should have valid data. @dimakuv what do you think?
</blockquote></details>

OK, ignore this comment.
___
*[Pal/src/host/Linux-common/topo_info.c, line 113 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRsixMo3ZCmPawNideM:-MRvedqU1aZXxVIZZMF1:b9vihux) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/src/host/Linux-common/topo_info.c#L113)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry, I don't understand how `dirent64->d_reclen` can be `0`. Agree that `getdents64` can return a partially filled buffer but I think those partially filled buffers will be valid else the `getedents64` should have returned `-1` because we cannot make any sense from a partially filled `dirent64` struct. I think the `dirent64` struct will be properly filled for the ones `getdents64` has returned. Also, I don't see such a case mentioned in the man pages. Can you please clarify? 
</blockquote></details>

OK, you are right, my bad. `gedents64` indeed has this guarantees of returning a full dirent struct.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 249 at r14](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRZ2m2kAhtV6ac_5uDI:-MRvfMnGEsO_lYlHIfie:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/042046491356f1e02d07898e843c6dbc558b57a3/Pal/src/host/Linux-SGX/db_main.c#L249)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv From what I understand, one-element ranges are represented just as `X`, not `X-X` in this format.
</blockquote></details>

OK
___
*[Pal/src/host/Linux-SGX/db_main.c, line 178 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvevXh0xCHnQT8t2LA:-MRvevXh0xCHnQT8t2LB:b-8b24hz) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/Pal/src/host/Linux-SGX/db_main.c#L178)):*
> ```C
>  * returned when input "31" is provided. If buffer contains valid size indicators such as "48K",
>  * then just numeric value (48 in this case) is returned. Returns negative unix error code if the
>  * buffer is malformed Eg. 20abc or 3,4,5 or xyz123 or 512H.
> ```

`Eg.` -> `, e.g., `

And can you put examples in double quotes, just for uniformity with other examples you have in this comment. E.g., `20abc` -> `"20abc"`


<!-- Sent from Reviewable.io -->

2021-01-26 01:36 UTC, mkow reviewed
> Reviewed 1 of 5 files at r17, 3 of 3 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRwJGod5KiVwcwyb9KJ:bc9i1mz) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
> In general, the string can have positive or negative numbers

Yeah, it can also contain real and complex numbers, but why would this matter for us? ;)

This behavior of `strtoul` sounds like a weird quirk of this ancient interface, I see no reason to follow it, especially at the cost of having the parsing logic significantly more complex (and remember, that this parser runs on untrusted data, so it needs to be very carefully and thoroughly reviewed).
___
*[Pal/lib/string/atoi.c, line 20 at r17](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRv2L42AwSCQ6yEAscu:-MRwIqdp5SikfG45U4bQ:b6qhuh7) ([raw file](https://github.com/oscarlab/graphene/blob/0252ba8279d0cf1fa906fd71db9bfee15fa35896/Pal/lib/string/atoi.c#L20)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

sorry not sure what is 1-1 style. Do you mean something like below? If not, can you please point me to an example?
```
/* SPDX-License-Identifier: LGPL-3.0-or-later */
/* Copyright (C) 2021 Intel Corporation
 *                    Vijay Dhanraj <vijay.dhanraj@intel.com>
 */
```

</blockquote></details>

Looks good now :)
___
*[Pal/lib/string/atoi.c, line 19 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRwId0h5QhiN4msxzQO:-MRwId0iB_zdv4tLtJKj:b-mj7m1q) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/Pal/lib/string/atoi.c#L19)):*
> ```C
>    02111-1307 USA. */
> 
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

This actually needs to be placed on the first line (some automatic tools look for it there). Alternatively I'd just drop it, because we already have the license from glibc here and I'm not sure if we can just drop it.


<!-- Sent from Reviewable.io -->

2021-01-26 08:01 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 30 of 35 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Examples/openvino/object_detection_sample_ssd.manifest.template, line 113 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvcz3t2Vrj5z6kw2cB:-MRxaExICGHddxkhtGa0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/Examples/openvino/object_detection_sample_ssd.manifest.template#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space after `#`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sysfs_common.c, line 78 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvdWLt6xy9T5P01Xas:-MRxb8tC0_QdwoFAncY7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/LibOS/shim/test/regression/sysfs_common.c#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

please add a space before `*/`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sysfs_common.c, line 81 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvdSnx7p8pZm7k80BC:-MRxbDyv5oytHf_zcsaw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/LibOS/shim/test/regression/sysfs_common.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could add spaces around `-` here
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sysfs_common.c, line 144 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvddTg554G-m_RQWbB:-MRxbKNi14Q9GvmcKrVP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/LibOS/shim/test/regression/sysfs_common.c#L144)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove a space before `\n`
</blockquote></details>

Done.
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRxc4hXBNN9Pqm8R7yg:b-144k4g) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> In general, the string can have positive or negative numbers

Yeah, it can also contain real and complex numbers, but why would this matter for us? ;)

This behavior of `strtoul` sounds like a weird quirk of this ancient interface, I see no reason to follow it, especially at the cost of having the parsing logic significantly more complex (and remember, that this parser runs on untrusted data, so it needs to be very carefully and thoroughly reviewed).
</blockquote></details>

Ok, I have removed the parsing logic for +/- sign. Now if a string contains either of these signs we will return 0 with `str == out_endptr`
___
*[Pal/lib/string/atoi.c, line 19 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRwId0h5QhiN4msxzQO:-MRxcc7M0dADIF5Fpcia:b-c6h0l4) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/Pal/lib/string/atoi.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This actually needs to be placed on the first line (some automatic tools look for it there). Alternatively I'd just drop it, because we already have the license from glibc here and I'm not sure if we can just drop it.
</blockquote></details>

little confused by this comment :) I see your 3 choices but not sure what you are suggesting to do here, 1) drop `/* SPDX-License-Identifier: LGPL-3.0-or-later */` 2) place it on the first line, or 3) leave it as it is.

For now, I have dropped this line (option #1).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 178 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRvevXh0xCHnQT8t2LA:-MRxbvFN92Vm1Ea0XnrI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/Pal/src/host/Linux-SGX/db_main.c#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Eg.` -> `, e.g., `

And can you put examples in double quotes, just for uniformity with other examples you have in this comment. E.g., `20abc` -> `"20abc"`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-26 09:44 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r19.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/lib/api.h, line 146 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy-5YmDuE1NVgr9i6W:-MRy-5YmDuE1NVgr9i6X:b-sz4073) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/include/lib/api.h#L146)):*
> ```objc
> long long strtoll(const char* s, char** endptr, int base);
> /* Converts a string to an unsigned long value. On failure cases, that is if no digits were present,
>  * stores original value of str in *out_endptr and returns 0 or if an overflow occurred, sets
> ```

This comment is more confusing that the previous one... The "failure" and "success" cases in this function are very vague, let's not even use this confusing language.

You must clearly separate that:
- the return boolean indicates "int overflow happened?"
- if `out_value` is not NULL, then it contains the result of conversion (or `ULONG_MAX` if overflow happened)
- if `out_endptr` is not NULL, then it contains the address of the first invalid character in `str` (if there were no digits at all, then it contains the original value of `str`)

So my proposal:
```
/* Converts a string to an unsigned long value. "+" and "-" signs are not allowed in the string.
 * Return value indicates whether int overflow happened. If out_value is not NULL, then it contains
 * the result of conversion (or ULONG_MAX if int overflow happened). If out_endptr is not NULL, then
 * it contains the address of the first invalid char in str (or the original value of str if there
 * were no digits at all).
```
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRy3Muo80vJ8i8UaxH6:buhe6tt) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Ok, I have removed the parsing logic for +/- sign. Now if a string contains either of these signs we will return 0 with `str == out_endptr`
</blockquote></details>

What you meant is "we will return *out_value = 0 and *out_endptr = str". (You said everything correctly, I just want to make it clear that you didn't mean the return boolean.)

General note: please be careful in your language when there are multiple return values in functions. You can't just say "the function will return X". Return in which of the output values? So please be more specific in such messages.
___
*[Pal/lib/string/atoi.c, line 77 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy2lPH5BoULiS4s8UP:-MRy2lPH5BoULiS4s8UQ:b-haahjj) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/lib/string/atoi.c#L77)):*
> ```C
>     bool overflow_detected = false;
>     const char* s = str;
>     int valid_conv;
> ```

Let's rename this variable to `conv_status` and add a comment: `/* 0: no digits found, 1: valid conversion, -1: int overflow */`
___
*[Pal/lib/string/atoi.c, line 96 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy-orr7PIgzidHgnCf:-MRy-orr7PIgzidHgnCg:beeal7n) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/lib/string/atoi.c#L96)):*
> ```C
> 
>     // digits
>     for (val = 0, valid_conv = 0; ; s++) {
> ```

Since we're modifying this function so much, could you change this for loop to while loop, similar to the above `strtol`? Don't forget to add `s++;` at the end of the body!
___
*[Pal/lib/string/atoi.c, line 117 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy-ayCCtjLUX_xjd8B:-MRy-ayCCtjLUX_xjd8C:bcjooy8) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/lib/string/atoi.c#L117)):*
> ```C
>     }
> 
>     if(valid_conv < 0) {
> ```

Please add a space after `if`


<!-- Sent from Reviewable.io -->

2021-01-26 13:58 UTC, mkow requested changes
> Reviewed 5 of 5 files at r19.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 261 at r9](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQOs1gN7aI5dCPtKkl-:-MRyxTYzArOrEjz6Byzq:bpc3fkd) ([raw file](https://github.com/oscarlab/graphene/blob/6e361e5c5dc3ccad065bfbdfaf59c92b97b2fb2a/Pal/include/arch/x86_64/pal-arch.h#L261)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are all the structs above actually arch-dependent?
/summon @stefanberger
</blockquote></details>

@stefanberger ping, would you have a moment to take a look at this? Is this something which would be useful for your PPC64 port, or should be left in x64-specific dir?
___
*[Pal/include/lib/api.h, line 146 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy-5YmDuE1NVgr9i6W:-MRyxzJEBER1Wp4rkq5r:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/include/lib/api.h#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is more confusing that the previous one... The "failure" and "success" cases in this function are very vague, let's not even use this confusing language.

You must clearly separate that:
- the return boolean indicates "int overflow happened?"
- if `out_value` is not NULL, then it contains the result of conversion (or `ULONG_MAX` if overflow happened)
- if `out_endptr` is not NULL, then it contains the address of the first invalid character in `str` (if there were no digits at all, then it contains the original value of `str`)

So my proposal:
```
/* Converts a string to an unsigned long value. "+" and "-" signs are not allowed in the string.
 * Return value indicates whether int overflow happened. If out_value is not NULL, then it contains
 * the result of conversion (or ULONG_MAX if int overflow happened). If out_endptr is not NULL, then
 * it contains the address of the first invalid char in str (or the original value of str if there
 * were no digits at all).
```
</blockquote></details>

+1
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRyyVmh0Ztm-0adOqh1:b74gi8v) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What you meant is "we will return *out_value = 0 and *out_endptr = str". (You said everything correctly, I just want to make it clear that you didn't mean the return boolean.)

General note: please be careful in your language when there are multiple return values in functions. You can't just say "the function will return X". Return in which of the output values? So please be more specific in such messages.
</blockquote></details>

+1 to what Dima says, C is a nasty language without tuples, so we often have to return through args, and such language can be confusing ;)
___
*[Pal/lib/string/atoi.c, line 19 at r18](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRwId0h5QhiN4msxzQO:-MRyy3aD2zxrKyBXT5xK:b97l1u5) ([raw file](https://github.com/oscarlab/graphene/blob/6a59dd3e6768fa57321f623d384dcc615e2d79b3/Pal/lib/string/atoi.c#L19)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

little confused by this comment :) I see your 3 choices but not sure what you are suggesting to do here, 1) drop `/* SPDX-License-Identifier: LGPL-3.0-or-later */` 2) place it on the first line, or 3) leave it as it is.

For now, I have dropped this line (option #1).
</blockquote></details>

Looks fine now.
___
*[Pal/lib/string/atoi.c, line 77 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy2lPH5BoULiS4s8UP:-MRyy8wY-BxrOcXzXt1o:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/lib/string/atoi.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's rename this variable to `conv_status` and add a comment: `/* 0: no digits found, 1: valid conversion, -1: int overflow */`
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-01-26 17:35 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 33 of 35 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/include/lib/api.h, line 146 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy-5YmDuE1NVgr9i6W:-MRzNQlR3VKcgAf0CBND:buzlgzs) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/include/lib/api.h#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

updated the comment.
___
*[Pal/lib/string/atoi.c, line 82 at r16](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRtz00F8OEBO-ntQSyT:-MRzN_OFCE2I_xgx2FNv:bn7mb08) ([raw file](https://github.com/oscarlab/graphene/blob/08a689b430b44662a120a6fdd39c35f942b03ce2/Pal/lib/string/atoi.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 to what Dima says, C is a nasty language without tuples, so we often have to return through args, and such language can be confusing ;)
</blockquote></details>

yes, I meant *out_value being set to 0.
___
*[Pal/lib/string/atoi.c, line 77 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy2lPH5BoULiS4s8UP:-MRzOza_BdP3xGGQ6Vv1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/lib/string/atoi.c#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[Pal/lib/string/atoi.c, line 117 at r19](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRy-ayCCtjLUX_xjd8B:-MRzOxMlCa5k_dSLOycG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8290d6ac915ac8c71d4a060d8ec4a59cb2c8fc26/Pal/lib/string/atoi.c#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space after `if`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-26 17:41 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2021-01-26 17:59 UTC, mkow reviewed
@vijaydhanraj Looks good now. Could you rebase it to the current master? I'll do the last pass of security review afterwards and queue for merging if everything's fine.

> Reviewed 2 of 2 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975#-:-MRzq7VU0kSmmtbbFky1:bd6os53)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2021-01-26 20:21 UTC, vijaydhanraj reviewed
Done, can someone please initiate the Jenkins test please?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975#-:-MS-LYAF6dRCWN5Zx2xD:b-id4ehi)* status: 16 of 35 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2021-01-26 20:25 UTC, mkow commented
Jenkins, retest this please

2021-01-26 23:57 UTC, mkow commented
Jenkins, retest Jenkins-SGX please (timeout on `test_libos.TC_30_Syscall.test_090_sighandler_reset` - random lag? Vijay couldn't reproduce it)

2021-01-27 09:26 UTC, dimakuv requested changes
> Reviewed 19 of 19 files at r21.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1pWn_-1AcZJNormgj:-MS1pWn_-1AcZJNormgk:b5m1a5x) (no related file):*
TODO: during rebase, must put commit "[PAL]: Add support for strtoul library function." as the very first commit, because commit "[PAL/LibOS] Add support for /sys pseudo filesystem" depends on it.

TODO: during rebase, fix commit names (e.g., remove dots at the end)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1rZdK5fo90WL-Cdui:-MS1rZdK5fo90WL-Cduj:bqzrabt) (no related file):*
TODO: during rebase, must squash commit "[LibOS] Add `/proc/[..]/task` path to /proc fs" into commit "[PAL/LibOS] Add support for /sys pseudo filesystem" (because the former commit doesn't make sense without the latter commit, e.g. see a bug with `dir_thread::size == 5`).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS29M9g09N4wyaJJixW:-MS29M9g09N4wyaJJixX:b5c4068) (no related file):*
I did my last round of review, everything looks good to me except for some small typos and beautifications. This is a cool PR, I like its final shape!

---
___
*[LibOS/shim/include/shim_fs.h, line 553 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1ycipDwcYgPgvV8c3:-MS1ycipDwcYgPgvV8c4:b-pxf4ap) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/include/shim_fs.h#L553)):*
> ```objc
> 
> /* /sys fs related common APIs */
> /* This function extracts first number from a string. For example, "3" will be extracted
> ```

Please add that it returns a negative int if no number is found:
```
/* This function extracts first (non-negative) number from a string.
 * Returns a negative error code if no number if found. For example, "3" will be
 * extracted from "cpu/cpu3/topology/core_siblings". */
```

and fix my formatting to 100 chars, of course.
___
*[LibOS/shim/include/shim_fs.h, line 565 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1qu_c1-gdG_K-reBU:-MS1qu_c1-gdG_K-reBV:b-q7g3ws) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/include/shim_fs.h#L565)):*
> ```objc
> /* Fills buf with an array of dirents for the given pathname (path under /sys/); returns 0 on
>  * success and negative error code otherwise */
> int sys_list_resource_num(const char* pathname, struct shim_dirent** buf, size_t len);
> ```

`len` -> `size`
___
*[LibOS/shim/src/fs/shim_fs.c, line 160 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw0RwN8S5psVAiYQTW:-MS1qctECZRLnYbou2Hl:bpvqey0) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/shim_fs.c#L160)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't notice this before, but not completely done. We should remove `as` (for consistency with other messages here).
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 2 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xQl_CwTe1xH5xsOm:-MS1xQl_CwTe1xH5xsOn:b-1vf3h) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2020 Intel Corporation */
> ```

Not too important, but this is `2021` now :) And maybe your name if you want it here.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 9 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1uiJGAIz6hgG5EhuQ:-MS1uiJGAIz6hgG5EhuR:b-5hmhq0) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L9)):*
> ```C
>  */
> 
> #include "shim_fs.h"
> ```

Please also add `#include "api.h"` (you are using helper functions from this header), and don't forget to sort!
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 13 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1uDRe696fT-W4q5bv:-MS1uDRe696fT-W4q5bw:b-bvb5hp) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L13)):*
> ```C
> static int cache_info_open(struct shim_handle* hdl, const char* name, int flags) {
>     __UNUSED(hdl);
>     __UNUSED(flags);
> ```

These two UNUSED lines can be removed -- we use both `hdl` and `flags` in this function.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 26 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1svrxEj_DHhzQ09Hg:-MS1svrxEj_DHhzQ09Hh:b-2k03tx) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L26)):*
> ```C
>         return -ENOENT;
> 
>     int idx = extract_first_num_from_string(strstr(name, "index"));
> ```

Could you add `assert(strstr(name, "index"));` before this line? This way, we make sure that `strstr` doesn't return NULL (which would result in a segfault when passed to `extract_first_num_from_string`). Since we are supposed to have the correct `name` at this point, we can simply do an assert.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 2 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xVT36jsrOnhDHdBO:-MS1xVT36jsrOnhDHdBP:b-1vf3h) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cpu_info.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2020 Intel Corporation */
> ```

Not too important, but this is `2021` now :) And maybe your name if you want it here.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 8 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1usXp2cCjiVG8VMHl:-MS1usXp2cCjiVG8VMHm:b-5hmhq0) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cpu_info.c#L8)):*
> ```C
>  */
> 
> #include "shim_fs.h"
> ```

Please also add `#include "api.h"` (you are using helper functions from this header), and don't forget to sort!
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 9 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1v6FQ2TL5yKTYehVi:-MS1v6FRBLttl1JUnng9:b7v9sle) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cpu_info.c#L9)):*
> ```C
> 
> #include "shim_fs.h"
> extern const struct pseudo_dir cpunum_cache_dir;
> ```

Can you add a comment above this line, like this: `/* Sub-directory /sys/devices/system/cpu/cpuX/cache is implemented in separate file cache_info.c */`
___
*[LibOS/shim/src/fs/sys/fs.c, line 2 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xWbE-N-FXUN-_i85:-MS1xWbE-N-FXUN-_i86:b-1vf3h) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/fs.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2020 Intel Corporation */
> ```

Not too important, but this is `2021` now :) And maybe your name if you want it here.
___
*[LibOS/shim/src/fs/sys/fs.c, line 11 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xLtw-7v4K-UOISLh:-MS1xLtw-7v4K-UOISLi:b-5hmhq0) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/fs.c#L11)):*
> ```C
> #include "perm.h"
> #include "shim_fs.h"
> #include "stat.h"
> ```

Please also add `#include "api.h"` (you are using helper functions from this header), and don't forget to sort!
___
*[LibOS/shim/src/fs/sys/fs.c, line 13 at r21](https://review [...]

2021-01-27 19:03 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 24 of 35 files reviewed, 35 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/include/shim_fs.h, line 553 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1ycipDwcYgPgvV8c3:-MS3Y7ZRETf7uNPhIpnA:b21g0wr) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/include/shim_fs.h#L553)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add that it returns a negative int if no number is found:
```
/* This function extracts first (non-negative) number from a string.
 * Returns a negative error code if no number if found. For example, "3" will be
 * extracted from "cpu/cpu3/topology/core_siblings". */
```

and fix my formatting to 100 chars, of course.
</blockquote></details>

yes done. Just changed `if found -> is found`. I think this is what you meant here.
___
*[LibOS/shim/include/shim_fs.h, line 565 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1qu_c1-gdG_K-reBU:-MS3YTVE-1pNu3UBJXZT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/include/shim_fs.h#L565)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`len` -> `size`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 160 at r10](https://reviewable.io/reviews/oscarlab/graphene/1975#-MQw0RwN8S5psVAiYQTW:-MS3ZZ29AwFGJtooT4mz:bvpbeiz) ([raw file](https://github.com/oscarlab/graphene/blob/aabc97a151b9fe94be0a48b6c2f6336b8f59a70f/LibOS/shim/src/fs/shim_fs.c#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I didn't notice this before, but not completely done. We should remove `as` (for consistency with other messages here).
</blockquote></details>

Ok, removed `as`.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 2 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xQl_CwTe1xH5xsOm:-MS3jpSG29bl-UMEVzLT:b7llll4) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not too important, but this is `2021` now :) And maybe your name if you want it here.
</blockquote></details>

updated the header.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 9 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1uiJGAIz6hgG5EhuQ:-MS3mP7Q9-upuJMoynqD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add `#include "api.h"` (you are using helper functions from this header), and don't forget to sort!
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 13 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1uDRe696fT-W4q5bv:-MS3mMBu1tpdhHa9ZEzb:b-bc0l8h) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two UNUSED lines can be removed -- we use both `hdl` and `flags` in this function.
</blockquote></details>

ah removed these.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 26 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1svrxEj_DHhzQ09Hg:-MS3qLoA25cB4j7Ue5-6:b-lpmcna) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cache_info.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add `assert(strstr(name, "index"));` before this line? This way, we make sure that `strstr` doesn't return NULL (which would result in a segfault when passed to `extract_first_num_from_string`). Since we are supposed to have the correct `name` at this point, we can simply do an assert.
</blockquote></details>

yes makes sense. I have added `assert`.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 2 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xVT36jsrOnhDHdBO:-MS3raiF--_V_HquxmzN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cpu_info.c#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not too important, but this is `2021` now :) And maybe your name if you want it here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 8 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1usXp2cCjiVG8VMHl:-MS3rVm1BcbbbeIxhwwd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cpu_info.c#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add `#include "api.h"` (you are using helper functions from this header), and don't forget to sort!
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 9 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1v6FQ2TL5yKTYehVi:-MS3rWrF-tZcgPg2cf3p:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/cpu_info.c#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment above this line, like this: `/* Sub-directory /sys/devices/system/cpu/cpuX/cache is implemented in separate file cache_info.c */`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 2 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xWbE-N-FXUN-_i85:-MS3sCbu79URmJeiONuH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/fs.c#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not too important, but this is `2021` now :) And maybe your name if you want it here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 11 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xLtw-7v4K-UOISLh:-MS3sBaF3a83-8ltwU0O:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/fs.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add `#include "api.h"` (you are using helper functions from this header), and don't forget to sort!
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 13 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1xddK734rRG-ZIVVP:-MS3ss1gAtIc_-vzzXSB:b-qy3qbu) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/fs.c#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment above this line, like this: `/* Sub-directores /sys/devices/system/{cpu,node} are implemented in separate files cpu_info.c and node_info.c */`
</blockquote></details>

yes, done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 37 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1yIJz9io2TYIq82Sq:-MS3tDN52bBMvAKzNlQT:bi4u88a) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/fs.c#L [...]

2021-01-28 07:37 UTC, dimakuv reviewed
> Reviewed 11 of 11 files at r22.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 129 at r21](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS2-tJBB3d2V44v3DRM:-MS6uU1gC8k1VILnxZ4E:b-c2lz1s) ([raw file](https://github.com/oscarlab/graphene/blob/7ded7323c1deccf19960e432f437afbfd1b44011/LibOS/shim/src/fs/sys/fs.c#L129)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Thanks, but gcc throws a warning `warning: assignment from incompatible pointer type` when we cast it to `char*` as `dirent_in_buf->next` is of type `struct shim_dirent*`.
</blockquote></details>

Ah, ok. I am letting this slip then. Resolving this discussion (but we'll probably need to fix all such places in Graphene at some point).


<!-- Sent from Reviewable.io -->

2021-01-28 13:12 UTC, mkow requested changes
> Reviewed 17 of 19 files at r21, 11 of 11 files at r22.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/fs/proc/thread.c, line 744 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7XJ6A3Uv9aWTNB9By:-MS7XJ6A3Uv9aWTNB9Bz:buc2vvv) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/proc/thread.c#L744)):*
> ```C
>         {.name = "fd",   .fs_ops = &fs_thread_fd,   .dir  = &dir_fd},
>         {.name = "maps", .fs_ops = &fs_thread_maps, .type = LINUX_DT_REG},
>         {.name = "task", .fs_ops = &fs_thread,      .dir  = &dir_task},
> ```

I missed this in the initial review: Why do we leave `.type` uninitialized here and above, instead of setting it to `LINUX_DT_DIR`?
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 11 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7eSIBCpHHhpR6Zpgf:-MS7eSIBCpHHhpR6Zpgg:b-g30xbp) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/sys/cpu_info.c#L11)):*
> ```C
> 
> #include "api.h"
> #include "shim_fs.h"
> ```

please insert an empty line after includes
___
*[LibOS/shim/src/fs/sys/fs.c, line 25 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7suWy5NOYonFlS-c4:-MS7suWy5NOYonFlS-c5:brjdcru) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/sys/fs.c#L25)):*
> ```C
> 
>     while (*str) {
>         if ((*str >= '0') && (*str <= '9') ) {
> ```

no need for parens + no space before `)`
___
*[LibOS/shim/src/fs/sys/fs.c, line 26 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7tGMxBuSRZtYbzq1o:-MS7tGMxBuSRZtYbzq1p:b-8bpat4) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/sys/fs.c#L26)):*
> ```C
>     while (*str) {
>         if ((*str >= '0') && (*str <= '9') ) {
>             return strtol(str, NULL, 10);
> ```

possible int overflow here (you're casting `long` to `int`)
___
*[Pal/include/host/Linux-common/topo_info.h, line 1 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7xROe30yUrhV4No3R:-MS7xROf3QYYZo2WCzYj:b7lu01r) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/include/host/Linux-common/topo_info.h#L1)):*
> ```objc
> #ifndef TOPO_INFO_H_
> ```

Please add license and copyright.
___
*[Pal/src/host/Linux-common/topo_info.c, line 38 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7zKy3BlPBovgt_Rs0:-MS7zKy49Y8b6SK2gSeR:b-y7mo3) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-common/topo_info.c#L38)):*
> ```C
> 
>         char* end;
>         int firstint = (int)strtol(ptr, &end, 10);
> ```

possible int overflow
___
*[Pal/src/host/Linux-common/topo_info.c, line 56 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7zN1SA81HlqYPzgdB:-MS7zN1SA81HlqYPzgdC:b-y7mo3) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-common/topo_info.c#L56)):*
> ```C
>             /* HW resource range, count how many HW resources are in range */
>             ptr = end + 1;
>             int secondint = (int)strtol(ptr, &end, 10);
> ```

possible int overflow
___
*[Pal/src/host/Linux-SGX/db_main.c, line 2 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS80OIK9G5KJQmlXD2G:-MS80OIK9G5KJQmlXD2H:bbaipnx) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2014 Stony Brook University */
> ```

Please update copyright.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS82FfB7PtUQy36X2vd:-MS82FfB7PtUQy36X2ve:b-hmeptv) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L224)):*
> ```
> if (firstint != 0 && firstint <= current_maxint)
> ```

I missed this previously: why 0 has a special meaning here and resets ` current_maxint`? Wasn't this supposed to be: `if (current_maxint != 0 && firstint <= current_maxint)`?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 238 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS838ccBCYzWpfEvwtg:-MS838ccBCYzWpfEvwth:b1w11q) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L238)):*
> ```C
>             unsigned long secondint;
>             str_to_ulong(buf, 10, &secondint, &end);
>             if (secondint > LONG_MAX)
> ```

no check for `end == buf`?


<!-- Sent from Reviewable.io -->

2021-01-28 19:55 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/proc/thread.c, line 744 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7XJ6A3Uv9aWTNB9By:-MS8kQri-Gx9uwWmOlbx:b52knm0) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/proc/thread.c#L744)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I missed this in the initial review: Why do we leave `.type` uninitialized here and above, instead of setting it to `LINUX_DT_DIR`?
</blockquote></details>

If I understand correctly, we use `ent->dir` to identify if it is a directory or not. If `dir == NULL` then we use the `.type` else it is assumed `.type == LINUX_DT_DIR`. My understanding is based on this comment, https://github.com/oscarlab/graphene/blob/master/LibOS/shim/include/shim_fs.h#L514
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 11 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7eSIBCpHHhpR6Zpgf:-MS8nfdg62od9Q7KWb0q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/sys/cpu_info.c#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please insert an empty line after includes
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 25 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7suWy5NOYonFlS-c4:-MS8niLo6aHmemCIhz3a:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/sys/fs.c#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need for parens + no space before `)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 26 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7tGMxBuSRZtYbzq1o:-MS8uLp53bsaI5RpCMcp:bdq0ry) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/sys/fs.c#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

possible int overflow here (you're casting `long` to `int`)
</blockquote></details>

Added a check against `INT_MAX` and return `-1` if the value is greater or less than 0 as we don't expect such insanely huge or negative values.
___
*[Pal/include/host/Linux-common/topo_info.h, line 1 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7xROe30yUrhV4No3R:-MS8ujl9A2_1LvNNdbgW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/include/host/Linux-common/topo_info.h#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add license and copyright.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-common/topo_info.c, line 38 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7zKy3BlPBovgt_Rs0:-MS990HOC76GK1U7z9Sf:b-ts45h3) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-common/topo_info.c#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

possible int overflow
</blockquote></details>

yes, I addressed it.
___
*[Pal/src/host/Linux-common/topo_info.c, line 56 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7zN1SA81HlqYPzgdB:-MS99D4T4Nh4buHQ2BF5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-common/topo_info.c#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

possible int overflow
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 2 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS80OIK9G5KJQmlXD2G:-MS99zlECg_ydElDgahL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please update copyright.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS82FfB7PtUQy36X2vd:-MS9Bop9B4LSBGdxXcTs:bftljmc) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> if (firstint != 0 && firstint <= current_maxint)
> ```

I missed this previously: why 0 has a special meaning here and resets ` current_maxint`? Wasn't this supposed to be: `if (current_maxint != 0 && firstint <= current_maxint)`?
</blockquote></details>

There can be an initial case where `firstint = current_maxint == 0`. For this corner case, I have introduced `firstint != 0`.
The use of `current_maxint` is to ensure that we only have an increasing range. E.g., `0,5,8` when we explicitly set `ordered = true` and so it needs to be reset to current `firstint`
___
*[Pal/src/host/Linux-SGX/db_main.c, line 238 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS838ccBCYzWpfEvwtg:-MS9LL6yB5ZChusPaMr7:b-f9dgxr) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L238)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no check for `end == buf`?
</blockquote></details>

yes, it might be needed for a corner case when `ordered ==false` and if we have a buffer like `4-\0`. Without it, we might end up adding +1 to resource count. I have added it now.


<!-- Sent from Reviewable.io -->

2021-01-28 20:31 UTC, mkow requested changes
> Reviewed 5 of 5 files at r23.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/fs/proc/thread.c, line 744 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7XJ6A3Uv9aWTNB9By:-MS9c4g4BBoQ-ADPP78A:b-fotz0d) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/proc/thread.c#L744)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If I understand correctly, we use `ent->dir` to identify if it is a directory or not. If `dir == NULL` then we use the `.type` else it is assumed `.type == LINUX_DT_DIR`. My understanding is based on this comment, https://github.com/oscarlab/graphene/blob/master/LibOS/shim/include/shim_fs.h#L514
</blockquote></details>

Hmm, but `if dir != NULL, then always LINUX_DT_DIR` sounds like "if `dir` is set, then this field must be `LINUX_DT_DIR`", but now it's `LINUX_DT_UNKNOWN`.
___
*[Pal/src/host/Linux-common/topo_info.c, line 66 at r23](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS9fFp15IY0VSj7vT5e:-MS9fFp15IY0VSj7vT5f:b-1zdpur) ([raw file](https://github.com/oscarlab/graphene/blob/1fb7b38423a9a7b359a10c67065631d7011d87fd/Pal/src/host/Linux-common/topo_info.c#L66)):*
> ```C
>             if (secondint > firstint) {
>                 long diff = secondint - firstint;
>                 if (diff >= INT_MAX || resource_cnt + diff + 1 > INT_MAX)
> ```

`resource_cnt + diff + 1 > INT_MAX` <- this won't work on 32-bit, the addition may overflow (UB). I think the easiest way to prevent this would be to use GCC's overflow builtins.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS82FfB7PtUQy36X2vd:-MS9fhsN96Q6WyRkQ1HN:b-affd5x) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

There can be an initial case where `firstint = current_maxint == 0`. For this corner case, I have introduced `firstint != 0`.
The use of `current_maxint` is to ensure that we only have an increasing range. E.g., `0,5,8` when we explicitly set `ordered = true` and so it needs to be reset to current `firstint`

</blockquote></details>

U sure about this? ;)
What if we have `ordered == true` and input: `0-9, 0-10`?


<!-- Sent from Reviewable.io -->

2021-01-28 23:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 32 of 35 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/fs/proc/thread.c, line 744 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7XJ6A3Uv9aWTNB9By:-MSAD4MdC9oTOBFOEFBu:bnklydo) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/proc/thread.c#L744)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but `if dir != NULL, then always LINUX_DT_DIR` sounds like "if `dir` is set, then this field must be `LINUX_DT_DIR`", but now it's `LINUX_DT_UNKNOWN`.
</blockquote></details>

I think if `dir` is set, then `type` is a don't care. But I have anyway added`.type = LINUX_DT_DIR` as there is nothing wrong in adding it. :)
___
*[Pal/src/host/Linux-common/topo_info.c, line 66 at r23](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS9fFp15IY0VSj7vT5e:-MSADcDY5Rwh5A2bir7T:bl2g6px) ([raw file](https://github.com/oscarlab/graphene/blob/1fb7b38423a9a7b359a10c67065631d7011d87fd/Pal/src/host/Linux-common/topo_info.c#L66)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`resource_cnt + diff + 1 > INT_MAX` <- this won't work on 32-bit, the addition may overflow (UB). I think the easiest way to prevent this would be to use GCC's overflow builtins.
</blockquote></details>

used `__builtin_add_overflow()` to address this issue.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS82FfB7PtUQy36X2vd:-MSADr3H6vzYnCmVZv7-:b-8wbt5p) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

U sure about this? ;)
What if we have `ordered == true` and input: `0-9, 0-10`?
</blockquote></details>

you are right, it will fail for this case. But even `if (current_maxint != 0 && firstint <= current_maxint)` might not help. It will allow input `0,0,1` when `ordered == true`. How about this?
```
        if (ordered) {
            if (init_done && firstint <= current_maxint)
                return -EINVAL;
            current_maxint = firstint;
            init_done = true;
        }
```


<!-- Sent from Reviewable.io -->

2021-01-28 23:47 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r24.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MRbeeeY9vDBFxbHixmD:-MSAOEEZCIEcC5ycwMF5:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Note to myself: Do one more round of security review on the final version before merging (especially w.r.t. int overflows).
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/fs/proc/thread.c, line 744 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS7XJ6A3Uv9aWTNB9By:-MSANaKZA9HZKGDGAiyj:b-ai8vne) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/LibOS/shim/src/fs/proc/thread.c#L744)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I think if `dir` is set, then `type` is a don't care. But I have anyway added`.type = LINUX_DT_DIR` as there is nothing wrong in adding it. :)
</blockquote></details>

I prefer to have a valid value there and don't need to rely on such relations ;)
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r22](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS82FfB7PtUQy36X2vd:-MSAO87I5ojusnLKVv38:b-7h0mdc) ([raw file](https://github.com/oscarlab/graphene/blob/b1136e1f47c7e0bb83ad9b05955c438c69b6ff08/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

you are right, it will fail for this case. But even `if (current_maxint != 0 && firstint <= current_maxint)` might not help. It will allow input `0,0,1` when `ordered == true`. How about this?
```
        if (ordered) {
            if (init_done && firstint <= current_maxint)
                return -EINVAL;
            current_maxint = firstint;
            init_done = true;
        }
```
</blockquote></details>

Looks correct now :)


<!-- Sent from Reviewable.io -->

2021-01-29 02:31 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: 29 of 35 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1rZdK5fo90WL-Cdui:-MSAxy216rbhtxUtaddS:b-hshbm9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: during rebase, must squash commit "[LibOS] Add `/proc/[..]/task` path to /proc fs" into commit "[PAL/LibOS] Add support for /sys pseudo filesystem" (because the former commit doesn't make sense without the latter commit, e.g. see a bug with `dir_thread::size == 5`).
</blockquote></details>

Split changes `../proc/thread.c` from "[PAL/LibOS] Add support for /sys pseudo filesystem" and add it as part of "[LibOS] Add /proc/[..]/task path to /proc fs". Also rearranged this commit to be before /sys fs commit.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MS1pWn_-1AcZJNormgj:-MSAyQE54O-rERMFzhP2:bbg10cd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO: during rebase, must put commit "[PAL]: Add support for strtoul library function." as the very first commit, because commit "[PAL/LibOS] Add support for /sys pseudo filesystem" depends on it.

TODO: during rebase, fix commit names (e.g., remove dots at the end)
</blockquote></details>

Moved  "[PAL]: Add support for strtoul library function" as the first commit and removed periods at the end of the commit info.

Also, rebased to the latest master.

---


<!-- Sent from Reviewable.io -->

2021-01-29 07:31 UTC, dimakuv approved these changes
> Reviewed 3 of 5 files at r23, 2 of 3 files at r24, 6 of 6 files at r25.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-29 08:03 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1975#-MSC9CKOCoEI-26O6iQT:-MSC9CKOCoEI-26O6iQU:be13gz8) (no related file):*
FYI: I rebased again to fix the commit messages (there were some typos).

I also squashed commit `[LibOS] Fix pseudo_name_ops struct function pointer type` into our main commit `[Pal,LibOS] Add support for /sys pseudo filesystem` because otherwise the function types didn't correspond and Graphene build failed. I added a commit body message with this squashed change.

---


<!-- Sent from Reviewable.io -->

2021-01-29 08:03 UTC, dimakuv commented
Jenkins, test this please

2021-01-29 09:52 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r28.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-29 09:54 UTC, dimakuv commented
Jenkins, test this please

2021-01-29 12:13 UTC, mkow approved these changes
> Reviewed 6 of 6 files at r25, 3 of 3 files at r28.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1975)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-29 12:56 UTC, merged