Introduce human-readable file permission helpers
oscarlab/graphene pull request #1978
Opened 2020-11-18 11:08 UTC by pwmarcz

This first creates our own `stat.h` (to avoid the dance with `#define __KERNEL__` + `#include <linux/stat.h>` etc.), and then introduces human-readable macros such as `PERM_rwxrwxr_x` from this patch: https://lwn.net/Articles/696231/

This is a follow-up to the discussion in https://github.com/oscarlab/graphene/pull/1965

The macros do look nice, but stuff like `PERM_r________` is going to be hard to write in an editor without autocomplete.

CC @boryspoplawski @mkow

2020-11-18 11:47 UTC, mkow requested changes
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMQ8CWf59424D_JlIuz:b-n2azs1) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
> ```
>  We keep it here to avoid including <sys/stat.h> or <linux/stat.h>.
> ```

The reason is actually slightly different: This is because we emulate a specific Linux version, not the one which is present on the build host. For example, when building for the *BSD or Windows PAL (in the future) we won't have any of these headers available. So, conceptually, we should have all the headers on our own.
___
*[Pal/include/lib/stat.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ97TO5W4Ns4mKFpkN:-MMQ97TO5W4Ns4mKFpkO:bvpbx4x) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L14)):*
> ```objc
> #define STAT_H
> 
> /* Play nice if someone did include the system headers. */
> ```

We should actually error out here, but our codebase is definitely not ready for this :) Could you add a TODO here to error out?
___
*[Pal/include/lib/stat.h, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ9fK02nIJtNjL3mpq:-MMQ9fK02nIJtNjL3mpr:b-ezbt2n) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L56)):*
> ```objc
> /*
>  * We also define human-readable macros for common file permissions.
>  * Inspired by Linux patch by Inigo Molnar (https://lwn.net/Articles/696231/).
> ```

`Inigo` -> `Ingo`
___
*[Pal/include/lib/stat.h, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ9ID55KQWhljlVB6u:-MMQ9ID55KQWhljlVB6v:b-na8zge) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L59)):*
> ```objc
>  */
> 
> #define PERM_r________	0400
> ```

tab -> spaces (ditto below)


<!-- Sent from Reviewable.io -->

2020-11-18 12:21 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @pwmarcz)

___
*[Pal/include/lib/stat.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ97TO5W4Ns4mKFpkN:-MMQHqlM5FPkC4g--zDy:b2v26sp) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We should actually error out here, but our codebase is definitely not ready for this :) Could you add a TODO here to error out?
</blockquote></details>

Actually it is ready! I added this to be able to use this file in `pf_util.c`, which is a helper program that uses normal libc (e.g. `stat()`) and as such, includes <sys/stat.h>. Everything else should compile.

So, I can replace this with `#error`, but then this file will not be usable in such programs. Is that okay?


<!-- Sent from Reviewable.io -->

2020-11-18 12:23 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @pwmarcz)

___
*[Pal/include/lib/stat.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ97TO5W4Ns4mKFpkN:-MMQIhAK04Ej03QSd_W0:be9m3bg) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L14)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually it is ready! I added this to be able to use this file in `pf_util.c`, which is a helper program that uses normal libc (e.g. `stat()`) and as such, includes <sys/stat.h>. Everything else should compile.

So, I can replace this with `#error`, but then this file will not be usable in such programs. Is that okay?
</blockquote></details>

Alternatively, we can move these helpers to something like `perm.h`.


<!-- Sent from Reviewable.io -->

2020-11-18 12:25 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Pal/include/lib/stat.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ97TO5W4Ns4mKFpkN:-MMQIu453l-o3dTDVRqE:bprgfl8) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L14)):*
That's a nice surprise :)

> So, I can replace this with `#error`, but then this file will not be usable in such programs. Is that okay?

Sounds good IMO.

> Alternatively, we can move these helpers to something like `perm.h`.

+1
___
*[Pal/include/lib/stat.h, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ9fK02nIJtNjL3mpq:-MMQIs1W1e_lXvwOSnCC:bq8tc3w) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Inigo` -> `Ingo`
</blockquote></details>

(ditto for the commit message)


<!-- Sent from Reviewable.io -->

2020-11-18 13:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: 19 of 24 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMQONuE7lgXjnglnSLr:bwvmfys) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  We keep it here to avoid including <sys/stat.h> or <linux/stat.h>.
> ```

The reason is actually slightly different: This is because we emulate a specific Linux version, not the one which is present on the build host. For example, when building for the *BSD or Windows PAL (in the future) we won't have any of these headers available. So, conceptually, we should have all the headers on our own.
</blockquote></details>

Okay, then I think "Linux file type permission macros." is enough for now, we probably don't want to repeat this explanation in every file like that. Changed.
___
*[Pal/include/lib/stat.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ97TO5W4Ns4mKFpkN:-MMQS65o-KDwB312e_ar:b-dcye7h) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's a nice surprise :)

> So, I can replace this with `#error`, but then this file will not be usable in such programs. Is that okay?

Sounds good IMO.

> Alternatively, we can move these helpers to something like `perm.h`.

+1
</blockquote></details>

I did both. Unfortunately I couldn't manage to do it so that the "fixup" commits do not conflict, so I rebased the commits.
___
*[Pal/include/lib/stat.h, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ9fK02nIJtNjL3mpq:-MMQSY0j8tMZa2b9gU9B:b-67ehi0) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(ditto for the commit message)
</blockquote></details>

Fixed in comment and commit message too.
___
*[Pal/include/lib/stat.h, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ9ID55KQWhljlVB6u:-MMQSbT2CUFgj7J3jq81:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

tab -> spaces (ditto below)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-18 13:21 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMQVXUUAAIh802HBibf:b1na6v4) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, then I think "Linux file type permission macros." is enough for now, we probably don't want to repeat this explanation in every file like that. Changed.
</blockquote></details>

I agree, makes sense :)


<!-- Sent from Reviewable.io -->

2020-11-18 13:32 UTC, boryspoplawski requested changes
> Reviewed 20 of 22 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQTskl82-1k5EPbMcP:-MMQTskn1dsw5VDTlEdp:bbjw5ns) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/shim_namei.c#L10)):*
> ```C
> #include <asm/fcntl.h>
> #include <linux/fcntl.h>
> #include <linux/stat.h>
> ```

This file still uses `S_I*` please include `stat.h`
___
*[LibOS/shim/src/fs/chroot/fs.c, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQME2x3gNVqKb6HtMn:-MMQME2y7i7eLTpoE6Qc:b-70s7i2) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/chroot/fs.c#L8)):*
> ```C
>  */
> 
> // FIXME: Sorting these includes causes a bunch of "error: ‘S_IFREG’ undeclared" errors.
> ```

If there are no errors anymore, please sort the includes: system wide first, Graphene internal second.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQU11I7rZfUwCv1HhX:-MMQU11I7rZfUwCv1HhY:bbjw5ns) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/chroot/fs.c#L25)):*
> ```C
> #include <errno.h>
> #include <linux/fcntl.h>
> #include <linux/stat.h>
> ```

This file still uses `S_I*` please include `stat.h`
___
*[LibOS/shim/src/fs/pipe/fs.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQU6GQCfhZpL5kL4kJ:-MMQU6GQCfhZpL5kL4kK:bwfji06) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/pipe/fs.c#L15)):*
> ```C
> #include <errno.h>
> #include <linux/fcntl.h>
> #include <linux/stat.h>
> ```

This file still uses `S_I*` and `PERM_*` please include `stat.h`
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUAuS7TnDY_k9P3-_:-MMQUAuS7TnDY_k9P3-a:bwfji06) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/proc/ipc-thread.c#L8)):*
> ```C
> #include <errno.h>
> #include <linux/fcntl.h>
> #include <linux/stat.h>
> ```

This file still uses `S_I*` and `PERM_*` please include `stat.h`
___
*[LibOS/shim/src/fs/proc/thread.c, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUF5r9LKX3hlAfwyq:-MMQUF5r9LKX3hlAfwyr:b-4ntsx1) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/proc/thread.c#L8)):*
> ```C
> #include <errno.h>
> #include <linux/fcntl.h>
> #include <linux/stat.h>
> ```

Please fix includes and define here too.
UPDATE: This file still uses `S_I*` please include `stat.h`
___
*[LibOS/shim/src/fs/socket/fs.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUKKgBPa4w6OKcL6I:-MMQUKKgBPa4w6OKcL6J:bbjw5ns) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/socket/fs.c#L15)):*
> ```C
> #include <errno.h>
> #include <linux/fcntl.h>
> #include <linux/stat.h>
> ```

This file still uses `S_I*` please include `stat.h`
___
*[LibOS/shim/src/sys/shim_fs.c, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUWX9C_CkPDtAlBnE:-MMQUWXA0kyApGbOx1hV:bbjw5ns) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/sys/shim_fs.c#L14)):*
> ```C
> #include <errno.h>
> #include <linux/fcntl.h>
> #include <linux/stat.h>
> ```

This file still uses `S_I*` please include `stat.h`
___
*[LibOS/shim/src/sys/shim_open.c, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUdVdCFI1LYaYGQM9:-MMQUdVdCFI1LYaYGQMA:bbjw5ns) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/sys/shim_open.c#L23)):*
> ```C
> #include <errno.h>
> #include <dirent.h>
> #include <linux/stat.h>
> ```

This file still uses `S_I*` please include `stat.h`
___
*[LibOS/shim/src/sys/shim_pipe.c, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUv5B4TlNbrkK0GX-:-MMQUv5B4TlNbrkK0GX0:b-sz8hsw) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/LibOS/shim/src/sys/shim_pipe.c#L19)):*
> ```C
> #include "shim_table.h"
> #include "shim_types.h"
> #include "shim_utils.h"
> ```

This file uses `S_I*` please include `stat.h`
___
*[Pal/include/host/Linux-common/pal_flags_conv.h, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQV8U2A4YqSPD8lkvE:-MMQV8U33_fMRVQ36x-C:b-aamc2k) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/Pal/include/host/Linux-common/pal_flags_conv.h#L15)):*
> ```objc
> #define PAL_FLAGS_CONV_H
> 
> #undef __GLIBC__
> ```

Please fix includes and undef.
___
*[Pal/include/lib/perm.h, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQWCRD0IwLLlu2_Rtc:-MMQWCRD0IwLLlu2_Rtd:b-i4zz4y) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/include/lib/perm.h#L24)):*
> ```objc
> #define PERM_rw_rw_rw_  0666
> 
> #define PERM__w_______  0200
> ```

I would remove these 3: they are exotic enough that we will probably never use them.
___
*[Pal/include/lib/perm.h, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQWIi51bSn_tbG2hjO:-MMQWIi67S2WkYrP_9As:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/include/lib/perm.h#L38)):*
> ```objc
> #define PERM_rwxrwxrwx  0777
> 
> #define PERM__wx______  0300
> ```

ditto
___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMQX0eIAfIdNRY_dPqu:b-d3roqb) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
> The reason is actually slightly different: (...)

This is true for LibOS, but in Pal I think we should use host headers.
___
*[Pal/src/host/Linux/db_files.c, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQXrR76Qk_ZFJg6v5E:-MMQXrR76Qk_ZFJg6v5F:b6ui57o) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/Pal/src/host/Linux/db_files.c#L20)):*
> ```C
> #include "pal_linux_defs.h"
> #include "pal_linux_error.h"
> typedef __kernel_pid_t pid_t;
> ```

Could we get rid of this `typedef` and `undef` while we are here?
___
*[Pal/src/host/Linux/db_streams.c, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQXyYG0PbOrwu-qVsW:-MMQXyYG0PbOrwu-qVsX:b-3jjyw5) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/src/host/Linux/db_streams.c#L16)):*
> ```C
> #include "pal_linux.h"
> #include "pal_linux_defs.h"
> #include "pal_security.h"
> ```

Please include `stat.h`
___
*[Pal/src/host/Linux/db_streams.c, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQY-xd1mwubPvodNQi:-MMQY-xd1mwubPvodNQj:b9gnnor) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/src/host/Linux/db_streams.c#L18)):*
> ```C
> #include "pal_security.h"
> 
> typedef __kernel_pid_t pid_t;
> ```

Could we get rid of this `typedef` and sort headers here?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQYO3-36sRbolqKmBe:-MMQYO3-36sRbolqKmBf:b-8vie5l) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/src/host/Linux-SG [...]

2020-11-18 14:14 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQTskl82-1k5EPbMcP:-MMQfM2M3rA3EIt1hetD:bgha8os) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/shim_namei.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file still uses `S_I*` please include `stat.h`
</blockquote></details>

Before, `shim_fs.h` included `<linux/stat.h>` for convenience, and I changed that occurence to `"stat.h"`. I assume the convention was to rely on `shim_fs.h` instead of including `stath.h` everywhere. Do you think we should change that convention as part of this PR?
___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMQg2HM8Lsr76BPubvb:b4xkchd) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The reason is actually slightly different: (...)

This is true for LibOS, but in Pal I think we should use host headers.
</blockquote></details>

Does that mean you want Pal to use `#define __KERNEL__` + `#include <linux/stat.h>` still?


<!-- Sent from Reviewable.io -->

2020-11-18 14:33 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQTskl82-1k5EPbMcP:-MMQjih1-64Zi7VlhQKJ:b-mdwhiw) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/shim_namei.c#L10)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Before, `shim_fs.h` included `<linux/stat.h>` for convenience, and I changed that occurence to `"stat.h"`. I assume the convention was to rely on `shim_fs.h` instead of including `stath.h` everywhere. Do you think we should change that convention as part of this PR?
</blockquote></details>

The convention is that if you use stuff defined in some header, you include it implicitly. I'm not sure what do you mean by "including for convenience". 
___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMQlGFYDJVlgC-DBNTN:b8gjtk6) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Does that mean you want Pal to use `#define __KERNEL__` + `#include <linux/stat.h>` still?
</blockquote></details>

If we don't use anything like `S_I` in Pal API then yes. Otoh it does not really matter. Don't do it for now, but let's discuss it.


<!-- Sent from Reviewable.io -->

2020-11-18 14:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQTskl82-1k5EPbMcP:-MMQn70NEo9KYgZJL-zO:blm04nv) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/shim_namei.c#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The convention is that if you use stuff defined in some header, you include it implicitly. I'm not sure what do you mean by "including for convenience". 
</blockquote></details>

Well then, it does not look like Graphene code follows that convention anywhere :)

Okay, I will include `stat.h` directly in the files that use it.


<!-- Sent from Reviewable.io -->

2020-11-18 14:51 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMQoM110Zx_TGR6RH0M:b6h7rvn) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If we don't use anything like `S_I` in Pal API then yes. Otoh it does not really matter. Don't do it for now, but let's discuss it.
</blockquote></details>

Well, I guess for Pal the main argument is convenience - as we found before, with current state of Pal it's pretty hard to pull in `linux/stat.h` and have it work. But maybe that's a matter of getting rid of the `sys/...` includes.


<!-- Sent from Reviewable.io -->

2020-11-18 15:16 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: 6 of 39 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/fs/shim_namei.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQTskl82-1k5EPbMcP:-MMQtXs84KRKa03mpWZR:b-iuckyc) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/shim_namei.c#L10)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Well then, it does not look like Graphene code follows that convention anywhere :)

Okay, I will include `stat.h` directly in the files that use it.
</blockquote></details>

Done. It looks like `shim_fs.h` include `<linux/stat.h>` in order to pull in `struct stat`; however, many source files took advantage of that to use `S_*` macros. I made sure `stat.h` and `perm.h` are included directly, and made `shim_fs.h` only pull in `<asm/stat.h>`.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQME2x3gNVqKb6HtMn:-MMQtwfN39Pisdx_39F4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/chroot/fs.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If there are no errors anymore, please sort the includes: system wide first, Graphene internal second.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQU11I7rZfUwCv1HhX:-MMQtxJE1v-50KBAd0zh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/chroot/fs.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file still uses `S_I*` please include `stat.h`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/pipe/fs.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQU6GQCfhZpL5kL4kJ:-MMQu09M4oYXvj8zvskD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/pipe/fs.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file still uses `S_I*` and `PERM_*` please include `stat.h`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUAuS7TnDY_k9P3-_:-MMQu2_BBSVNGgX1Jf1x:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/proc/ipc-thread.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file still uses `S_I*` and `PERM_*` please include `stat.h`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUF5r9LKX3hlAfwyq:-MMQu4za8mlkUhxzY9wx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/proc/thread.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please fix includes and define here too.
UPDATE: This file still uses `S_I*` please include `stat.h`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/socket/fs.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUKKgBPa4w6OKcL6I:-MMQu6iz10tzRlzE_dIo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/socket/fs.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file still uses `S_I*` please include `stat.h`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_fs.c, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUWX9C_CkPDtAlBnE:-MMQuDZ97IPJ_coexZBD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/sys/shim_fs.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file still uses `S_I*` please include `stat.h`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUdVdCFI1LYaYGQM9:-MMQuEcR4ESMEqml_n7Q:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/sys/shim_open.c#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file still uses `S_I*` please include `stat.h`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_pipe.c, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQUv5B4TlNbrkK0GX-:-MMQuHwaCKkWUDwcdmBq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/LibOS/shim/src/sys/shim_pipe.c#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file uses `S_I*` please include `stat.h`
</blockquote></details>

Done.
___
*[Pal/include/host/Linux-common/pal_flags_conv.h, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQV8U2A4YqSPD8lkvE:-MMQuK01-_8OuLRyb-N7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/Pal/include/host/Linux-common/pal_flags_conv.h#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please fix includes and undef.
</blockquote></details>

Done.
___
*[Pal/include/lib/perm.h, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQWCRD0IwLLlu2_Rtc:-MMQuT4w-_c2aLwtLSCt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/include/lib/perm.h#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would remove these 3: they are exotic enough that we will probably never use them.
</blockquote></details>

Done.
___
*[Pal/include/lib/perm.h, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQWIi51bSn_tbG2hjO:-MMQv11e2JmJ73K2D-B-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/include/lib/perm.h#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_files.c, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQXrR76Qk_ZFJg6v5E:-MMQuX0GCD0nzbpbkNuI:bbhpes3) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/Pal/src/host/Linux/db_files.c#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we get rid of this `typedef` and `undef` while we are here?
</blockquote></details>

Done, here and in all the other places too.
___
*[Pal/src/host/Linux/db_streams.c, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQXyYG0PbOrwu-qVsW:-MMQu_X88cNLGB2DmlwL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc523dca47882f25c004098767fb0843a08bb0d3/Pal/src/host/Linux/db_streams.c#L16)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please include `stat.h`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_streams.c, line 18 at r2](https://revie [...]

2020-11-18 15:21 UTC, yamahata approved these changes
> Reviewed 5 of 22 files at r1, 1 of 5 files at r2, 33 of 33 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2020-11-18 16:00 UTC, pwmarcz reviewed
Okay, there is one `#include <sys/wait.h>` that causes issues under Ubuntu 16 when included too early. For now, I added a comment.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978#-:-MMR4GbY2zqK0Iq8HQiF:bocamb1)* status: 37 of 39 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-18 16:01 UTC, mkow reviewed
I'm happy to drop 16.04 anytime, but we (ITL) will need to update than one server we still have on it first ;)

> Reviewed 33 of 33 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978#-:-MMR0FCr8QXLERWCDdB5:bnjl8u5)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQTskl82-1k5EPbMcP:-MMR-mErDZlIueaOLtR_:b9padg0) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/shim_namei.c#L10)):*
> Well then, it does not look like Graphene code follows that convention anywhere :)

Most of the codebase is old and doesn't follow any conventions ;)

Anyways, looks good now :)
___
*[LibOS/shim/src/sys/shim_open.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMR0u_Z4VY9RYFj9KGV:-MMR0u_Z4VY9RYFj9KGW:b-509lxk) ([raw file](https://github.com/oscarlab/graphene/blob/5475f6e8f3cff275ad45344c3270dc263081a468/LibOS/shim/src/sys/shim_open.c#L10)):*
> ```C
> 
> #include <errno.h>
> #include <dirent.h>
> ```

off-by-one in sorting ;)
___
*[Pal/include/lib/stat.h, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQ8CWf59424D_JlIuy:-MMR2DwK98O1iLu-vnoA:bp6ntg7) ([raw file](https://github.com/oscarlab/graphene/blob/9a0d1fca93d7bcbea854cf2d9e4906f5f349cc62/Pal/include/lib/stat.h#L8)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Well, I guess for Pal the main argument is convenience - as we found before, with current state of Pal it's pretty hard to pull in `linux/stat.h` and have it work. But maybe that's a matter of getting rid of the `sys/...` includes.
</blockquote></details>

Hmm, right, PALs should use host's headers, because they target particular host, not our "virtual" Linux version. If it's hard to do now I'd just leave it as is and put a comment describing how it should be done.


<!-- Sent from Reviewable.io -->

2020-11-18 17:20 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 22 files at r1, 31 of 33 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMQTskl82-1k5EPbMcP:-MMRJ_9I7a1ALOWmJ-y2:b9yzsdb) ([raw file](https://github.com/oscarlab/graphene/blob/e5988071baeeb48cac19b502a1a1b72a91b43529/LibOS/shim/src/fs/shim_namei.c#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Well then, it does not look like Graphene code follows that convention anywhere :)

Most of the codebase is old and doesn't follow any conventions ;)

Anyways, looks good now :)
</blockquote></details>

Sorry, meant explicitly, not implicitly.
Ok now


<!-- Sent from Reviewable.io -->

2020-11-18 17:21 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug please (LTP truncate02 failed)

2020-11-19 09:35 UTC, dimakuv approved these changes
> Reviewed 5 of 22 files at r1, 1 of 5 files at r2, 31 of 33 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2020-11-19 11:42 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_open.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/1978#-MMR0u_Z4VY9RYFj9KGV:-MMVITTtCmobE48pbe7j:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/5475f6e8f3cff275ad45344c3270dc263081a468/LibOS/shim/src/sys/shim_open.c#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

off-by-one in sorting ;)
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2020-11-19 13:22 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-19 13:28 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-11-19 13:32 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-11-19 14:08 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1978)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-19 14:32 UTC, merged