Improve the TOML source file patching
oscarlab/graphene pull request #1982
Opened 2020-11-19 00:30 UTC by bigdata-memory

## Description of the changes
The user doesn't need to do distclean if TOML source files got
updated and separated the original files from patched ones.

Fixes #1981

2020-11-19 09:01 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bigdata-memory)

___
*[Pal/lib/Makefile, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/1982#-MMUj3ReD7eMJ160jixN:-MMUj3RfCxY6FfGLtEUb:b-kse7k7) ([raw file](https://github.com/oscarlab/graphene/blob/7784de5b47df65052b32db3e2d5d320209243fdc/Pal/lib/Makefile#L185)):*
> ```Makefile
> 	$(RM) ../include/lib/uthash.h
> 	$(RM) ../include/lib/toml.h toml.h toml.c toml.patched \
>               toml.h.$(TOML_H_CHECKSUM) toml.c.$(TOML_C_CHECKSUM)
> ```

What about we just use `toml.c* toml.h*` to delete all these TOML source/header files? In other words, this:
```
$(RM) ../include/lib/toml.h toml.h* toml.c* toml.patched
```


<!-- Sent from Reviewable.io -->

2020-11-19 18:12 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/lib/Makefile, line 185 at r1](https://reviewable.io/reviews/oscarlab/graphene/1982#-MMUj3ReD7eMJ160jixN:-MMWh9h_DIcyrjdKF9ii:b-el4k8f) ([raw file](https://github.com/oscarlab/graphene/blob/7784de5b47df65052b32db3e2d5d320209243fdc/Pal/lib/Makefile#L185)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about we just use `toml.c* toml.h*` to delete all these TOML source/header files? In other words, this:
```
$(RM) ../include/lib/toml.h toml.h* toml.c* toml.patched
```
</blockquote></details>

Sure, it got updated, Thanks.


<!-- Sent from Reviewable.io -->

2020-11-20 09:26 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-11-20 09:26 UTC, dimakuv commented
Jenkins, test this please

2020-11-20 09:35 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1982#-MM_-M7M6nwmuSHjZrmq:-MM_-M7M6nwmuSHjZrmr:b-e4wnqd) (no related file):*
Clean builds in Jenkins fail with this error:
```
https://raw.githubusercontent.com/cktan/tomlc99/5be06807ad5f2230cad99e15380c4f4076c9dd83/toml.h --sha256 e79d6d272576561e1b46ee001b0dd6b554330843e6fc7c658a548c659f282ac5
../../Scripts/download --output toml.c.c21a546ab767a7e40d4f65df179d70357059c15e4439e1980d791625655fbbc6 --url https://raw.githubusercontent.com/cktan/tomlc99/5be06807ad5f2230cad99e15380c4f4076c9dd83/toml.c --sha256 c21a546ab767a7e40d4f65df179d70357059c15e4439e1980d791625655fbbc6
make[3]: *** No rule to make target '/home/jenkins/workspace/graphene/Pal/src/host/Linux/.lib/toml.o', needed by '/home/jenkins/workspace/graphene/Pal/src/host/Linux/.lib/graphene-lib.a'.  Stop.
```
Please fix.

---


<!-- Sent from Reviewable.io -->

2020-11-20 20:34 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1982#-MM_-M7M6nwmuSHjZrmq:-MMbLp3P73McQClrdjlx:b-zd56ou) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Clean builds in Jenkins fail with this error:
```
https://raw.githubusercontent.com/cktan/tomlc99/5be06807ad5f2230cad99e15380c4f4076c9dd83/toml.h --sha256 e79d6d272576561e1b46ee001b0dd6b554330843e6fc7c658a548c659f282ac5
../../Scripts/download --output toml.c.c21a546ab767a7e40d4f65df179d70357059c15e4439e1980d791625655fbbc6 --url https://raw.githubusercontent.com/cktan/tomlc99/5be06807ad5f2230cad99e15380c4f4076c9dd83/toml.c --sha256 c21a546ab767a7e40d4f65df179d70357059c15e4439e1980d791625655fbbc6
make[3]: *** No rule to make target '/home/jenkins/workspace/graphene/Pal/src/host/Linux/.lib/toml.o', needed by '/home/jenkins/workspace/graphene/Pal/src/host/Linux/.lib/graphene-lib.a'.  Stop.
```
Please fix.
</blockquote></details>

fixed, thanks.

---


<!-- Sent from Reviewable.io -->

2020-11-23 08:34 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @dimakuv)

___
*[Pal/lib/Makefile, line 170 at r3](https://reviewable.io/reviews/oscarlab/graphene/1982#-MMoE9kY23Na-eUvdKgv:-MMoDaaJAiI_s1slX7to:b-jc2syh) ([raw file](https://github.com/oscarlab/graphene/blob/04d289df66c30829fa284375b351a11e7b9db818/Pal/lib/Makefile#L170)):*
> ```Makefile
> 
> toml.c toml.h: .toml_sentinel
> 	@:
> ```

Why is this line needed? Can't we just remove this line?
___
*[Pal/lib/Makefile, line 172 at r3](https://reviewable.io/reviews/oscarlab/graphene/1982#-MMoDUbDEspq13TwSN4i:-MMoDUbDEspq13TwSN4j:bt8bxpd) ([raw file](https://github.com/oscarlab/graphene/blob/04d289df66c30829fa284375b351a11e7b9db818/Pal/lib/Makefile#L172)):*
> ```Makefile
> 	@:
> 
> .toml_sentinel: toml.h.$(TOML_H_CHECKSUM) toml.c.$(TOML_C_CHECKSUM)
> ```

Is this a PHONY target? Can you add then `.PHONY: .toml_sentinel`?


<!-- Sent from Reviewable.io -->

2020-11-23 08:34 UTC, dimakuv commented
Jenkins, test this please

2020-11-23 09:48 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1982#-MM_-M7M6nwmuSHjZrmq:-MMoV5-b4rAqA1JnATs9:b-ephyru) (no related file):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

fixed, thanks.
</blockquote></details>

Another error from Jenkins:
```
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
?? Pal/lib/toml.c.c21a546ab767a7e40d4f65df179d70357059c15e4439e1980d791625655fbbc6
?? Pal/lib/toml.h.e79d6d272576561e1b46ee001b0dd6b554330843e6fc7c658a548c659f282ac5
```

You should add these new temporary files (`toml.c.*` and `toml.h.*`) to `Pal/lib/.gitignore`. And by the way, please remove `toml.patched` from there.

---


<!-- Sent from Reviewable.io -->

2020-11-23 19:41 UTC, bigdata-memory commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1982#-MM_-M7M6nwmuSHjZrmq:-MMqbl5X5cGZyxEumLqa:bo3046z) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Another error from Jenkins:
```
              ERROR: Files modified by build, but not gitignored:
--------------------------------------------------------------------------------
?? Pal/lib/toml.c.c21a546ab767a7e40d4f65df179d70357059c15e4439e1980d791625655fbbc6
?? Pal/lib/toml.h.e79d6d272576561e1b46ee001b0dd6b554330843e6fc7c658a548c659f282ac5
```

You should add these new temporary files (`toml.c.*` and `toml.h.*`) to `Pal/lib/.gitignore`. And by the way, please remove `toml.patched` from there.
</blockquote></details>

Sure, Got it updated for your review, thanks.

---


<!-- Sent from Reviewable.io -->

2020-11-23 19:57 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1982)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/lib/Makefile, line 170 at r3](https://reviewable.io/reviews/oscarlab/graphene/1982#-MMoE9kY23Na-eUvdKgv:-MMqfSUYAYjV95Norxyg:b-7r15m) ([raw file](https://github.com/oscarlab/graphene/blob/04d289df66c30829fa284375b351a11e7b9db818/Pal/lib/Makefile#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this line needed? Can't we just remove this line?
</blockquote></details>

I removed it, and using more compact syntax, thanks.
___
*[Pal/lib/Makefile, line 172 at r3](https://reviewable.io/reviews/oscarlab/graphene/1982#-MMoDUbDEspq13TwSN4i:-MMqfkg01n2j7XKeHKyV:b-bzse96) ([raw file](https://github.com/oscarlab/graphene/blob/04d289df66c30829fa284375b351a11e7b9db818/Pal/lib/Makefile#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this a PHONY target? Can you add then `.PHONY: .toml_sentinel`?
</blockquote></details>

added, thanks.


<!-- Sent from Reviewable.io -->

2020-11-24 09:35 UTC, dimakuv commented
Jenkins, test this please

2021-07-22 10:10 UTC, dimakuv commented
We rewrote the Common library (previously under `Pal/lib`) completely -- from Makefiles to Meson. So this PR is not relevant anymore, closing.

2021-07-22 10:10 UTC, closed without merging