[Pal/Linux-SGX] Allow ocall_mmap_untrusted() with fixed address
oscarlab/graphene pull request #1991
Opened 2020-11-24 14:14 UTC by dimakuv

## Description of the changes 

This PR allows `ocall_mmap_untrusted()` to be used with a fixed address (aka `MAP_FIXED`). This can be used to allocate untrusted memory at specific untrusted addresses.

This functionality is currently not used by Linux-SGX PAL but will be required in the IOCTL emulation in future PRs. (Some devices require allocating shared untrusted memory with `MAP_FIXED`.)

## How to test this PR? 

All tests must pass.

2020-11-24 15:40 UTC, mkow requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMuhmrL2wGWIW9VkNls:-MMuhmrL2wGWIW9VkNlt:b-insqql) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L91)):*
> ```C
>     ODEBUG(OCALL_MMAP_UNTRUSTED, ms);
> 
>     /* NOTE: enclave never asks for fixed address 0x0, so ms_mem == NULL means "no fixed addr" */
> ```

Could we instead have a bool in `ms_ocall_mmap_untrusted_t`? Will be equally simple, but won't require a magic sentinel value and allow mapping at zero if we ever needed it.


<!-- Sent from Reviewable.io -->

2020-11-24 20:18 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 187 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMvs5Fh4dqXmiR1YtmM:-MMvs5Fh4dqXmiR1YtmN:b-n8lqz9) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/enclave_ocalls.c#L187)):*
> ```C
> 
>     if (!retval) {
>         if (!sgx_copy_ptr_to_enclave(mem, returned_mem, size)) {
> ```

This call can be now omitted - we've already checked that `[returned_mem; returned_mem + size)` is outside enclave at entry.
Also you could remove `sgx_copy_ptr_to_enclave` completely - this is the only usage and it does not look correct.


<!-- Sent from Reviewable.io -->

2020-11-25 09:09 UTC, yamahata approved these changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMycKBR8pTwVPWcDNg8:-MMycKBR8pTwVPWcDNg9:b-9f211j) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L92)):*
> ```C
> 
>     /* NOTE: enclave never asks for fixed address 0x0, so ms_mem == NULL means "no fixed addr" */
>     int flags = ms->ms_mem ? MAP_FIXED : 0;
> ```

Can we add easy overlap check?
For example overlapping with [__executable_start, _end].

This is just random thoughts. So non-blocking.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMyWXe95KMKq1Powb-7:-MMyWXe95KMKq1Powb-8:b-p64oz0) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L93)):*
> ```
> MAP_FILE
> ```

nitpick: MAP_FILE is ignored and defined for compatibility.
On this occasion, let's remove it.


<!-- Sent from Reviewable.io -->

2020-11-25 10:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: 0 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 187 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMvs5Fh4dqXmiR1YtmM:-MMyyqEd35FgxalNBMBg:b-3wjuom) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/enclave_ocalls.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This call can be now omitted - we've already checked that `[returned_mem; returned_mem + size)` is outside enclave at entry.
Also you could remove `sgx_copy_ptr_to_enclave` completely - this is the only usage and it does not look correct.
</blockquote></details>

This check and function are still needed because in some cases, address is not fixed, and so we need to check the untrusted part's chosen address. I rewrote all this code for better readability now.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMuhmrL2wGWIW9VkNls:-MMyyhR57gjUup3brLfo:b-pdf3t2) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we instead have a bool in `ms_ocall_mmap_untrusted_t`? Will be equally simple, but won't require a magic sentinel value and allow mapping at zero if we ever needed it.
</blockquote></details>

Done. This comment made me re-write `ocall_mmap_untrusted`/`ocall_munmap_untrusted` to finally resemble normal mmap/munmap.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMycKBR8pTwVPWcDNg8:-MMynNG02PjF_nGR1GLJ:bvd180n) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L92)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Can we add easy overlap check?
For example overlapping with [__executable_start, _end].

This is just random thoughts. So non-blocking.
</blockquote></details>

But if the requested region overlaps with smth else (e.g., with the executable region), the `mmap()` syscall will just fail and the corresponding error code will be returned. So the overlapping case is already covered.


<!-- Sent from Reviewable.io -->

2020-11-25 11:12 UTC, boryspoplawski requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 187 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMvs5Fh4dqXmiR1YtmM:-MMz3V9RA-yIyF7cO99s:b1xr1ch) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/enclave_ocalls.c#L187)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This check and function are still needed because in some cases, address is not fixed, and so we need to check the untrusted part's chosen address. I rewrote all this code for better readability now.
</blockquote></details>

Previous version assumed that address is fixed, but the new does not.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 163 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz5PGC4Fkn5L6JL0aO:-MMz5PGDCafo-dBcI1DI:b-yvfzid) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/enclave_ocalls.c#L163)):*
> ```C
>     void* requested_addr = *addrptr;
> 
>     if (flags & MAP_FIXED) {
> ```

Maybe we should also support `MAP_FIXED_NOREPLACE`? Thie problem is that it is not be defined on kernels <4.17 ...
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 183 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz2oEd4XC2-X_2W53-:-MMz2oEe14FAVhPO6334:blt7m01) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/enclave_ocalls.c#L183)):*
> ```C
>     if (IS_ERR(retval) && !IS_UNIX_ERR(retval)) {
>         sgx_reset_ustack(old_ustack);
>         return -EPERM;
> ```

Could you change this to `return IS_UNIX_ERR(retval) ? retval : -EPERM` (and remove this check from `if`)? It would be easier to follow control flow in this function.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMycKBR8pTwVPWcDNg8:-MMz4h904OzXas-evVrC:b-p0ptfp) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But if the requested region overlaps with smth else (e.g., with the executable region), the `mmap()` syscall will just fail and the corresponding error code will be returned. So the overlapping case is already covered.
</blockquote></details>

Not if we use `MAP_FIXED`. But otoh we cannot really check anything, this is the limitation of `MAP_FIXED` ...
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 103 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz51cV4XBOfmA7sxeQ:-MMz51cV4XBOfmA7sxeR:bmqjfzd) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/sgx_enclave.c#L103)):*
> ```C
>     ms_ocall_munmap_untrusted_t* ms = (ms_ocall_munmap_untrusted_t*)pms;
>     ODEBUG(OCALL_MUNMAP_UNTRUSTED, ms);
>     const void* aligned_bottom = ALLOC_ALIGN_DOWN_PTR(ms->ms_addr);
> ```

Why do we do this align? It should be an error (api violation) to pass unaligned pointer here.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 104 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz506ZESjStdYtJbkp:-MMz506ZESjStdYtJbkq:b44pij2) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/sgx_enclave.c#L104)):*
> ```C
>     ODEBUG(OCALL_MUNMAP_UNTRUSTED, ms);
>     const void* aligned_bottom = ALLOC_ALIGN_DOWN_PTR(ms->ms_addr);
>     const void* aligned_top    = ALLOC_ALIGN_UP_PTR(ms->ms_addr + ms->ms_size);
> ```

This align is not needed.


<!-- Sent from Reviewable.io -->

2020-11-25 12:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: 7 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 163 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz5PGC4Fkn5L6JL0aO:-MMzEvIX9kCoQ3QU7orT:b-q6kgj3) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/enclave_ocalls.c#L163)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe we should also support `MAP_FIXED_NOREPLACE`? Thie problem is that it is not be defined on kernels <4.17 ...
</blockquote></details>

Yes, I first had it but then removed. This `ocall_mmap_untrusted()` is used purely by the Linux-SGX PAL (i.e., flags are always explicitly set by the caller of this ocall), so we just keep an eye that no caller ever uses `MAP_FIXED_NOREPLACE`. (And I don't see a reason for any caller to use this flag.)
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 183 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz2oEd4XC2-X_2W53-:-MMzFnir31U_KPMKzOTK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/enclave_ocalls.c#L183)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you change this to `return IS_UNIX_ERR(retval) ? retval : -EPERM` (and remove this check from `if`)? It would be easier to follow control flow in this function.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMycKBR8pTwVPWcDNg8:-MMzHRPy07HkehIDnHrQ:b-6ssfqf) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L92)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not if we use `MAP_FIXED`. But otoh we cannot really check anything, this is the limitation of `MAP_FIXED` ...
</blockquote></details>

Good point about `MAP_FIXED`. Unfortunately I don't see a simple way to check overlapping with the untrusted-pal executable. Let's leave it as-is.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 103 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz51cV4XBOfmA7sxeQ:-MMzIo0s80ewXgit4UTx:b-r1t8z9) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/sgx_enclave.c#L103)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we do this align? It should be an error (api violation) to pass unaligned pointer here.
</blockquote></details>

Done. I simply refactored the old logic, but you're right. So fixed now.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 104 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz506ZESjStdYtJbkp:-MMzItrh3QEjJnsoqIy0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/sgx_enclave.c#L104)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This align is not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-25 12:29 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`wait401` LTP test failed)

2020-11-25 13:01 UTC, boryspoplawski requested changes
Did you investigate why `wait401` failed?

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991#-:-MMzTZK8BzUkkn3l5_fV:b4b0r6q)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 163 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz5PGC4Fkn5L6JL0aO:-MMzTiiz04MtHchRfEdS:bntfurg) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/enclave_ocalls.c#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I first had it but then removed. This `ocall_mmap_untrusted()` is used purely by the Linux-SGX PAL (i.e., flags are always explicitly set by the caller of this ocall), so we just keep an eye that no caller ever uses `MAP_FIXED_NOREPLACE`. (And I don't see a reason for any caller to use this flag.)
</blockquote></details>

The reason is that `MAP_FIXED` should never be used as there is no way using it safely (but before 4.17 there was no other way). Could you actually give some usecase for this (currently we do not use it at all)?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 195 at r3](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMzU4DD0LqjxrNcU_X8:-MMzU4DD0LqjxrNcU_X9:b-9ad8gu) ([raw file](https://github.com/oscarlab/graphene/blob/1fdc41726af8ae1801a72ca6541d32563e349993/Pal/src/host/Linux-SGX/enclave_ocalls.c#L195)):*
> ```C
>     } else {
>         /* update addrptr with the mmap'ed address, but only if mmap succeeded */
>         if (!retval && !sgx_copy_ptr_to_enclave(addrptr, returned_addr, size)) {
> ```

Now this `!retval` and comment are not needed.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMycKBR8pTwVPWcDNg8:-MMzUNOA5bjPFtd0Ma8c:b-pajlfq) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Good point about `MAP_FIXED`. Unfortunately I don't see a simple way to check overlapping with the untrusted-pal executable. Let's leave it as-is.
</blockquote></details>

There is no way of doing that, that's why using `MAP_FIXED` is dangerous.


<!-- Sent from Reviewable.io -->

2020-11-26 09:37 UTC, dimakuv reviewed
I couldn't reproduce the failure of `wait401` locally.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991#-:-MN2qI1I55L2O4hIeYO7:be4zc7x)* status: 8 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 163 at r2](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMz5PGC4Fkn5L6JL0aO:-MN2rtjq1O5dj8Y8L6Bx:b-volw8b) ([raw file](https://github.com/oscarlab/graphene/blob/0b629b49cc6537296a2c34c3abe83cb6ca0f3756/Pal/src/host/Linux-SGX/enclave_ocalls.c#L163)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The reason is that `MAP_FIXED` should never be used as there is no way using it safely (but before 4.17 there was no other way). Could you actually give some usecase for this (currently we do not use it at all)?
</blockquote></details>

`MAP_FIXED` is currently not used but its support is needed for devices (`/dev/..`). E.g.:
- https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_framework.c#L158-L164
- https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_framework.c#L318-L319

Similarly, GPU devices use `MAP_FIXED`. This whole PR is a prerequisite for arbitrary-device support in Graphene.

I first thought to substitute `MAP_FIXED` with `MAP_FIXED_NOREPLACE` at this OCALL level, but then Linux 4.17 is too new... Even my Ubuntu 18.04 has 4.15. So we can't rely on this at all.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 195 at r3](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMzU4DD0LqjxrNcU_X8:-MN2uRp_7HxW_yDv23oo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1fdc41726af8ae1801a72ca6541d32563e349993/Pal/src/host/Linux-SGX/enclave_ocalls.c#L195)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now this `!retval` and comment are not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-26 09:53 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/1991#-MMycKBR8pTwVPWcDNg8:-MN2xtepC_SG1NDYhNDm:b-73nrnv) ([raw file](https://github.com/oscarlab/graphene/blob/efbd5ed1fa7f35a0105fe3a55344f1c940ac0da0/Pal/src/host/Linux-SGX/sgx_enclave.c#L92)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is no way of doing that, that's why using `MAP_FIXED` is dangerous.
</blockquote></details>

Otoh, if some app uses `MAP_FIXED` on some address, then it should have allocated it before, now only changing fd/offset/flags. Otherwise it's the app fault, nothing we can do about it.


<!-- Sent from Reviewable.io -->

2020-12-01 15:47 UTC, yamahata submitted a review, later dismissed
> Reviewed 7 of 9 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-04 01:36 UTC, mkow requested changes
> Reviewed 7 of 9 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9xIOm-w7OKLIRWKxh:-MQ9xIOm-w7OKLIRWKxi:b-t8txsl) (no related file):*
The commit message needs an update now (but you can do this when doing the final rebase).

---
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 195 at r4](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9zs6h2dIbmfOExqy2:-MQ9zs6h2dIbmfOExqy3:b-drrn4d) ([raw file](https://github.com/oscarlab/graphene/blob/f248126b44c904b08200f6c2d8ad587748d48f83/Pal/src/host/Linux-SGX/enclave_ocalls.c#L195)):*
> ```
> sgx_copy_ptr_to_enclave
> ```

Wow, this name is really misleading (but it was like this before). It's not copying anything into the enclave...
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 202 at r4](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9yaZi-imLjZvadgmR:-MQ9yaZi-imLjZvadgmS:byy3ejy) ([raw file](https://github.com/oscarlab/graphene/blob/f248126b44c904b08200f6c2d8ad587748d48f83/Pal/src/host/Linux-SGX/enclave_ocalls.c#L202)):*
> ```C
> 
>     sgx_reset_ustack(old_ustack);
>     return retval;
> ```

This is always zero now (because you handle errors without a goto, just inline returning)


<!-- Sent from Reviewable.io -->

2021-01-04 09:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: 8 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9xIOm-w7OKLIRWKxh:-MQBo3ZpCuN2ink5E9tX:b-livlmi) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The commit message needs an update now (but you can do this when doing the final rebase).
</blockquote></details>

What do you mean? The commit message seems legit. The commit adds handling of `MAP_FIXED` but it is not used currently by anyone.

As part of this commit/PR, I modified the OCALL arguments to resemble normal `mmap/munmap`. Should I add a sentence on this in the commit message?

---
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 195 at r4](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9zs6h2dIbmfOExqy2:-MQBn6yu0NXellDDHcyC:b-gwwau1) ([raw file](https://github.com/oscarlab/graphene/blob/f248126b44c904b08200f6c2d8ad587748d48f83/Pal/src/host/Linux-SGX/enclave_ocalls.c#L195)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> sgx_copy_ptr_to_enclave
> ```

Wow, this name is really misleading (but it was like this before). It's not copying anything into the enclave...
</blockquote></details>

Yep. For another PR.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 202 at r4](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9yaZi-imLjZvadgmR:-MQBns_7EcsEVo6KedEN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f248126b44c904b08200f6c2d8ad587748d48f83/Pal/src/host/Linux-SGX/enclave_ocalls.c#L202)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is always zero now (because you handle errors without a goto, just inline returning)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-04 12:37 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9xIOm-w7OKLIRWKxh:-MQCOOEJCdg46gpTIaE7:bdtoju8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean? The commit message seems legit. The commit adds handling of `MAP_FIXED` but it is not used currently by anyone.

As part of this commit/PR, I modified the OCALL arguments to resemble normal `mmap/munmap`. Should I add a sentence on this in the commit message?
</blockquote></details>

Yup, I mean adding this argument change to the message body.

---


<!-- Sent from Reviewable.io -->

2021-01-04 14:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: 1 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1991#-MQ9xIOm-w7OKLIRWKxh:-MQCgfVC1jplC-4cF3xL:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, I mean adding this argument change to the message body.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-01-04 14:11 UTC, mkow approved these changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-04 15:52 UTC, boryspoplawski approved these changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1991)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-04 16:06 UTC, merged