[LibOS] Fix deadlock in shim_do_accept()
oscarlab/graphene pull request #1996
Opened 2020-11-25 02:14 UTC by llly

`shim_do_accept()` locks `hdl->lock` first then wait for client to connect.  accept() blocks the caller until a connection is present.
It's a deadlock When one thread call fork() while another thread blocked in socket accept().

`BEGIN_MIGRATION_DEF(fork)` also locks `hdl->lock`.
Java API ProcessBuilder.start() fork explicitly then execve, triggers the deadlock.

fixes #1842

2020-11-25 09:44 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/src/sys/shim_socket.c, line 848 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMym4-14FSt7VnyKQaC:-MMym4-14FSt7VnyKQaD:b5omhzj) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L848)):*
> ```C
>     PAL_HANDLE handle = hdl->pal_handle;
>     if (sock->sock_state != SOCK_LISTENED) {
>         debug("shim_accpet: invalid socket\n");
> ```

Could you fix this typo while we're here: `shim_accept`
___
*[LibOS/shim/src/sys/shim_socket.c, line 849 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMymQKD0V8HTI7YDtqL:-MMymQKD0V8HTI7YDtqM:b77fgro) ([raw file](https://github.com/oscarlab/graphene/blob/07f62303c8ef878e08cfb7f64952e45080835098/LibOS/shim/src/sys/shim_socket.c#L849)):*
> ```C
>         debug("shim_accpet: invalid socket\n");
>         ret = -EINVAL;
>         goto out;
> ```

Why did you remove this? I would leave this as-is.
___
*[LibOS/shim/src/sys/shim_socket.c, line 862 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMyl9fq9AnKbrlhbxQv:-MMyl9fq9AnKbrlhbxQw:bf98xnq) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L862)):*
> ```C
>        goto out;
>     }
> ```

Could you add a couple sanity checks to verify that the `hdl` object is still good? I suggest to add this:
```
if (sock->sock_state != SOCK_LISTENED || hdl->pal_handle != handle) {
    debug("shim_accept: socket changed while waiting for a client connection\n");
    ret = -ECONNABORTED;
    goto out;
}
```


<!-- Sent from Reviewable.io -->

2020-11-25 10:13 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/src/sys/shim_socket.c, line 851 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMyq3nt7TQLPgHit4Oa:-MMyskVkE0Wq0vWeBJYv:bz706pk) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L851)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Here hdl is unlocked. after locking again, you need to check the state is sane.
And have you checked if while waiting, the state is changed by others, DkStreamWaitForClient will return?
</blockquote></details>

supplement: I think DkStreamWaitForClient or related functions are not designed as thread safe. That's the reason why we have lock around those calls. (At least those aren't tested well in threaded way.)
Now you changed its semantics. So related PAL code needs to be audited.


<!-- Sent from Reviewable.io -->

2020-11-26 06:27 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/sys/shim_socket.c, line 848 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMym4-14FSt7VnyKQaC:-MN2BsSR5ndkhQdE9Qd_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L848)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you fix this typo while we're here: `shim_accept`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 849 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMymQKD0V8HTI7YDtqL:-MN2Brd7DHrsjFjcmY8f:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/07f62303c8ef878e08cfb7f64952e45080835098/LibOS/shim/src/sys/shim_socket.c#L849)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this? I would leave this as-is.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_socket.c, line 851 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMyq3nt7TQLPgHit4Oa:-MN2D2gH-jOsqgijymCQ:b-xtji11) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L851)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

supplement: I think DkStreamWaitForClient or related functions are not designed as thread safe. That's the reason why we have lock around those calls. (At least those aren't tested well in threaded way.)
Now you changed its semantics. So related PAL code needs to be audited.
</blockquote></details>

Should I add `get_handle(hdl);`in before unlock() and `put_handle(hdl);` after `DkStreamWaitForClient()` ?
___
*[LibOS/shim/src/sys/shim_socket.c, line 862 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMyl9fq9AnKbrlhbxQv:-MN2BucP9uElZCJpFq_9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L862)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a couple sanity checks to verify that the `hdl` object is still good? I suggest to add this:
```
if (sock->sock_state != SOCK_LISTENED || hdl->pal_handle != handle) {
    debug("shim_accept: socket changed while waiting for a client connection\n");
    ret = -ECONNABORTED;
    goto out;
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-26 08:33 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/sys/shim_socket.c, line 851 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMyq3nt7TQLPgHit4Oa:-MN2eCKaEx7mzjVL-At3:b-3jgtua) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L851)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Should I add `get_handle(hdl);`in before unlock() and `put_handle(hdl);` after `DkStreamWaitForClient()` ?
</blockquote></details>

@llly No, you don't need to get and then put the handle -- this is already done by the caller of this function. So the `hdl` object (at the LibOS level) cannot suddenly disappear during `DkStreamWaitForClient()`.

@yamahata I looked at `DkStreamWaitForClient()` and its dependencies (in particular, `tcp_accept()` functions where it ends up in for sockets). All these functions seem to be thread-safe (probably by accident, not by design :)). So looks legit.

The only issue I see is that the `hdl->pal_handle` object could be freed during this `DkStreamWaitForClient()`, and we will end up working on a dangling pointer. But from my manual inspection of the code, `hdl->pal_handle` cannot be freed at this point (of doing `accept()`).

So everything seems fine.
___
*[LibOS/shim/src/sys/shim_socket.c, line 854 at r2](https://reviewable.io/reviews/oscarlab/graphene/1996#-MN2f0Wn8NCHjKiwHgFH:-MN2f0Wo-AOWIbc-MEk8:bane5cx) ([raw file](https://github.com/oscarlab/graphene/blob/6744e11a8ab255f7bb8210ff6a5e90d11f4d40c9/LibOS/shim/src/sys/shim_socket.c#L854)):*
> ```C
>     unlock(&hdl->lock);
> 
>     accepted = DkStreamWaitForClient(handle);
> ```

Could you add a comment:
```
/* NOTE: DkStreamWaitForClient() is blocking so we need to unlock before it and lock again afterwards;
  * we rely on DkStreamWaitForClient() being thread-safe and that `handle` is not freed during the wait. */
```

Please also re-wrap this comment to 100 chars.


<!-- Sent from Reviewable.io -->

2020-11-26 08:54 UTC, dimakuv commented
Jenkins, test this please

2020-11-26 09:05 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2020-11-26 09:05 UTC, dimakuv commented
Jenkins, test this please

2020-11-26 19:10 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[LibOS/shim/src/sys/shim_socket.c, line 851 at r1](https://reviewable.io/reviews/oscarlab/graphene/1996#-MMyq3nt7TQLPgHit4Oa:-MN4xUAb5BNOwAKh-xDI:bspt9cp) ([raw file](https://github.com/oscarlab/graphene/blob/d0b5bae58c73399a1ac591dfd645ded123018928/LibOS/shim/src/sys/shim_socket.c#L851)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@llly No, you don't need to get and then put the handle -- this is already done by the caller of this function. So the `hdl` object (at the LibOS level) cannot suddenly disappear during `DkStreamWaitForClient()`.

@yamahata I looked at `DkStreamWaitForClient()` and its dependencies (in particular, `tcp_accept()` functions where it ends up in for sockets). All these functions seem to be thread-safe (probably by accident, not by design :)). So looks legit.

The only issue I see is that the `hdl->pal_handle` object could be freed during this `DkStreamWaitForClient()`, and we will end up working on a dangling pointer. But from my manual inspection of the code, `hdl->pal_handle` cannot be freed at this point (of doing `accept()`).

So everything seems fine.
</blockquote></details>

Great. Thank you for checking codes!


<!-- Sent from Reviewable.io -->

2020-12-28 12:50 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

___
*[LibOS/shim/src/sys/shim_socket.c, line 867 at r3](https://reviewable.io/reviews/oscarlab/graphene/1996#-MPdOKob7c0pXjwwdq6-:-MPdODv63U5Hrt53qg3V:bhlq4jj) ([raw file](https://github.com/oscarlab/graphene/blob/3612107548bddc4b2f89593a285c841ac37ab8ac/LibOS/shim/src/sys/shim_socket.c#L867)):*
> ```C
>     }
> 
>     if (sock->sock_state != SOCK_LISTENED || hdl->pal_handle != handle) {
> ```

I don't like this - either `hdl->pal_handle != handle` should be impossible or it is possible and the assumption from the comment above is broken.


<!-- Sent from Reviewable.io -->

2021-01-05 01:12 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_socket.c, line 867 at r3](https://reviewable.io/reviews/oscarlab/graphene/1996#-MPdOKob7c0pXjwwdq6-:-MQF4vI81v38y-kFrKwC:b-b0eoer) ([raw file](https://github.com/oscarlab/graphene/blob/3612107548bddc4b2f89593a285c841ac37ab8ac/LibOS/shim/src/sys/shim_socket.c#L867)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this - either `hdl->pal_handle != handle` should be impossible or it is possible and the assumption from the comment above is broken.
</blockquote></details>

defense in depth


<!-- Sent from Reviewable.io -->

2021-01-05 02:17 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

___
*[LibOS/shim/src/sys/shim_socket.c, line 867 at r3](https://reviewable.io/reviews/oscarlab/graphene/1996#-MPdOKob7c0pXjwwdq6-:-MQFK3oQ7zaJaUqg26v3:boirbv9) ([raw file](https://github.com/oscarlab/graphene/blob/3612107548bddc4b2f89593a285c841ac37ab8ac/LibOS/shim/src/sys/shim_socket.c#L867)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

defense in depth
</blockquote></details>

If this `hdl->pal_handle != handle` ever is true then we are already in deep and just checking this gives 0 benefits.
If this is really impossible make it an assert.


<!-- Sent from Reviewable.io -->

2021-01-05 07:35 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_socket.c, line 867 at r3](https://reviewable.io/reviews/oscarlab/graphene/1996#-MPdOKob7c0pXjwwdq6-:-MQGSut7BXD-cj00g9r8:b-eesxy3) ([raw file](https://github.com/oscarlab/graphene/blob/3612107548bddc4b2f89593a285c841ac37ab8ac/LibOS/shim/src/sys/shim_socket.c#L867)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If this `hdl->pal_handle != handle` ever is true then we are already in deep and just checking this gives 0 benefits.
If this is really impossible make it an assert.
</blockquote></details>

Yes, sounds like changing `hdl->pal_handle != handle` to an assert `assert(hdl->pal_handle == handle);` is a good idea here.


<!-- Sent from Reviewable.io -->

2021-01-05 08:24 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_socket.c, line 867 at r3](https://reviewable.io/reviews/oscarlab/graphene/1996#-MPdOKob7c0pXjwwdq6-:-MQGdC3x0EJ960rGN6JO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8652747823df39b9c7cea85a81384b5021c369e8/LibOS/shim/src/sys/shim_socket.c#L867)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, sounds like changing `hdl->pal_handle != handle` to an assert `assert(hdl->pal_handle == handle);` is a good idea here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-05 08:28 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-01-05 08:29 UTC, dimakuv commented
Jenkins, test this please

2021-01-05 12:22 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-05 12:25 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1996#-MQHV3QTBokNJZwFupM2:-MQHV3QTBokNJZwFupM3:b-rh03ef) (no related file):*
Before merge: commits messages need to be rewritten and merge commit needs to be removed.
@llly for the future: we use fixups to apply review comments (easy to squash later on) and rebase instead of merge to update branch to master.

---


<!-- Sent from Reviewable.io -->

2021-01-05 17:26 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion (waiting on @llly)



<!-- Sent from Reviewable.io -->

2021-01-05 17:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/1996#-MQHV3QTBokNJZwFupM2:-MQIdJcBBYQ6GY-odHdV:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Before merge: commits messages need to be rewritten and merge commit needs to be removed.
@llly for the future: we use fixups to apply review comments (easy to squash later on) and rebase instead of merge to update branch to master.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-01-05 17:45 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: all files reviewed, 1 unresolved discussion (waiting on @llly)



<!-- Sent from Reviewable.io -->

2021-01-05 17:45 UTC, mkow commented
Jenkins, retest this please

2021-01-05 18:03 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug please (`sendfile08` LTP test failed)

2021-01-05 18:47 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/1996)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-05 19:08 UTC, merged