[Pal] Add SGX profiling support
oscarlab/graphene pull request #2001
Opened 2020-11-27 15:30 UTC by pwmarcz

This adds a "do it yourself" profiler that instruments AEX handler. I'm not sure how accurate it is, but the overhead seems to be pretty low (I haven't measured it though).

## Background

Background: I looked into `perf` first, and while it's pretty good for profiling non-SGX code, for SGX it only shows time spent in `async_exit_pointer` on interrupts. Unfortunately it seems pretty hard to extend, as perf events are generated in the kernel (and even if we did that, there's still the matter of resolving addresses to symbols).

First, I wrote some code on `async_exit_pointer` that reads the IP from enclave memory. This can already be dynamically instrumented by perf (using `perf probe`), but the resulting report is a list of events with `ip=0xabcd` and doesn't seem very usable. So I decided to go all the way and implement both event collection and symbol resolution in Graphene.

## Description of the changes 

* `SGX_PROFILE` compilation flag, and `sgx.profile` manifest option
* Code in `async_exit_pointer` to measure IP and collect it in a hash table
* `profile-report` Python tool for generating a report

## How to test this PR? 

Try to follow the instructions in `performance.rst`, and run some non-trivial workload.

## Possible improvements

* Make `perf` do more work somehow? Maybe we could generate synthetic `perf` events from userspace, not sure if it's ever done
* The Python program is pretty bad at symbol resolution: unlike perf and gdb, it doesn't understand that there can be external debug info. What can I use to do it better?
* Recover call graph (or at least a single caller)? I guess we could follow saved `RBP` and get something useful most of the time...

2020-11-30 11:55 UTC, dimakuv requested changes
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNrG4u1Rh1NGLOTp4J:-MNNrG4u1Rh1NGLOTp4K:bs9i9k2) (no related file):*
Do we want to add `SGX_PROFILE=1` to Jenkins on debug builds? Here: https://github.com/oscarlab/graphene/blob/master/.ci/lib/config-debug.jenkinsfile. Just to test that it compiles correctly.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNyhZuCiFuDk7L_g9e:-MNNyhZuCiFuDk7L_g9f:bcybehr) (no related file):*
> The Python program is pretty bad at symbol resolution: unlike perf and gdb, it doesn't understand that there can be external debug info. What can I use to do it better?

How does it work in GDB? I think there are some default paths that are looked for, with `[binaryname].debug` file? Cannot you do the same in your `profile-report` script, maybe even with additional arguments (i.e., the user must find the appropriate `.debug` files and explicitly specify them as arguments)?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNzcmvEPwHj_JAhHFX:-MNNzcmvEPwHj_JAhHFY:b-o3793f) (no related file):*
> Recover call graph (or at least a single caller)? I guess we could follow saved RBP and get something useful most of the time...

This would be super-useful, even with a single caller. I'm afraid we'll end up with `spinlock_lock` or something less than helpful in the profiles, and without a call graph that's not helpful.

From what I see in our Makefiles and `enclave_entry.S`, yes, we can use RBP. And even if not, we should be able to change our Makefiles and fix the asm files to track it.

---
___
*[Documentation/manifest-syntax.rst, line 448 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNo7lu7MGnXcayfRTF:-MNNo7lu7MGnXcayfRTG:b60hre0) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/manifest-syntax.rst#L448)):*
> ```reStructuredText
> This syntax specifies whether to enable SGX enclave-specific statistics:
> 
> #. ``TCS.FLAGS.DBGOPTIN`` flag. This flag is set in all enclave threads and
> ```

How is it possible that you don't need to set this flag on `sgx.profile`? Or you do, but forgot to mention this in your added text?

Also, now we have two ways of checking stats. Maybe we should merge them into one? Like `sgx.profile = "sgx_stats"`?
___
*[Documentation/manifest-syntax.rst, line 473 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNkUVl32W3ZMw2Uyec:-MNNkUVl32W3ZMw2Uyed:b383kgy) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/manifest-syntax.rst#L473)):*
> ```reStructuredText
> with ``DEBUG=1`` and ``SGX_PROFILE=1`` for this option to work.
> 
> If this option is set to ``root``, the root process will collect IP samples and
> ```

Can we specify `root (main) process` as a synonym? (I typically use "main process" and haven't heard the term "root process".)
___
*[Documentation/manifest-syntax.rst, line 474 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNk9K02C4M-XdmzKVp:-MNNk9K02C4M-XdmzKVq:b-oxq368) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/manifest-syntax.rst#L474)):*
> ```reStructuredText
> 
> If this option is set to ``root``, the root process will collect IP samples and
> save them as ``profile-sgx.data``. If it's to ``all``, all processes will
> ```

`If it's to` -> `If it is set to`
___
*[Documentation/devel/performance.rst, line 531 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNkmNf5ku5OtNdHaeS:-MNNkmNf5ku5OtNdHaeT:b-6w324r) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/devel/performance.rst#L531)):*
> ```reStructuredText
>    (``Pal/src/host/Linux-SGX/tools/profile-report/profile-report``) with the
>    data file as parameter. It should display a table of functions (or raw
>    addresses, if symbol information is not available)
> ```

Add a dot at the end.
___
*[Documentation/devel/performance.rst, line 535 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNkxVw2o1QJllq1-TX:-MNNkxVw2o1QJllq1-TY:bdl70w4) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/devel/performance.rst#L535)):*
> ```reStructuredText
> *Note*: The accuracy of this tool is unclear. The SGX profiling works by
> measuring the value of instruction pointer on each asynchronous enclave exit
> (AEX), which happen on Linux scheduler interrupts as well as other such as page
> ```

`as well as other such` -> `as well as other events`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNnaceDnfQlt99aOGK:-MNNnaceDnfQlt99aOGL:b-8h7j7h) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/enclave_framework.c#L43)):*
> ```C
>  * When SGX_PROFILE is enabled, we run some code on asynchronous enclave exit (AEX) that uses the
>  * stack. Make sure to update URSP so that the AEX handler does not overwrite the part of the stack
>  * that we just allocated.
> ```

Please add smth like: `(recall that URSP is an outside stack pointer saved by EENTER and restored on AEX by the SGX hardware itself)`
___
*[Pal/src/host/Linux-SGX/Makefile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNnmtR7d4r6MatCru_:-MNNnmtR7d4r6MatCrua:b97bcjv) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/Makefile#L73)):*
> ```Makefile
> urts-objs = \
> 	clone-x86_64.o \
> 	sgx_profile.o \
> ```

This is not sorted.
___
*[Pal/src/host/Linux-SGX/sgx_entry.S, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNpH-M5yFMULeLLnwj:-MNNpH-M5yFMULeLLnwk:bv58gli) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/sgx_entry.S#L81)):*
> ```
> 	.cfi_adjust_cfa_offset 8
> 
> 	# Align stack (eequired by System V AMD64 ABI)
> ```

`required`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 304 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNpxZuBI9s2l9VYPUI:-MNNpxZuBI9s2l9VYPUJ:bytpqpv) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/sgx_main.c#L304)):*
> ```C
>     g_sgx_enable_stats = !!enable_stats_int64;
> 
>     char* profile_str;
> ```

Could you set it to `= NULL` for sanity?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 307 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNqT9FEmH-8MCoMgei:-MNNqT9FEmH-8MCoMgej:bje96tq) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/sgx_main.c#L307)):*
> ```C
>     ret = toml_string_in(enclave->manifest_root, "sgx.profile", &profile_str);
>     if (ret < 0) {
>         SGX_DBG(DBG_E, "Cannot parse \'sgx.profile\' (the value must be 'none', 'root' or 'all')\n");
> ```

Can you use double-quotes for values? This may be confusing to a casual user (they will try to literally set `sgx.profile = 'none'` and won't be happy with the result).
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 318 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNt9Yd-uD6_jXY_8MP:-MNNt9Yd-uD6_jXY_8MQ:bsg8vje) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/sgx_main.c#L318)):*
> ```C
>             ret = sgx_profile_init(/*all=*/false);
>             if (ret < 0)
>                 goto out;
> ``` [...]

2020-11-30 19:30 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: 6 of 16 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNrG4u1Rh1NGLOTp4J:-MNOhUhx8pb-TxKexbPt:b13g43j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to add `SGX_PROFILE=1` to Jenkins on debug builds? Here: https://github.com/oscarlab/graphene/blob/master/.ci/lib/config-debug.jenkinsfile. Just to test that it compiles correctly.
</blockquote></details>

Sounds good to me. Strictly speaking it could be tested as a separate configuration, but it's probably not worth the resources.

(Actually, do we have debug builds for SGX yet? @woju ?)

Alternatively, maybe we could have this under `DEBUG` and remove `SGX_PROFILE`? I was afraid of adding the code in `async_exit_pointer` without a feature flag, but the overhead should be negligible when profiling is disabled, and maybe in `DEBUG` it's okay to have it. What do you think? 

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNyhZuCiFuDk7L_g9e:-MNOkcuQD9UNluZxFJ9d:bnbz1my) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> The Python program is pretty bad at symbol resolution: unlike perf and gdb, it doesn't understand that there can be external debug info. What can I use to do it better?

How does it work in GDB? I think there are some default paths that are looked for, with `[binaryname].debug` file? Cannot you do the same in your `profile-report` script, maybe even with additional arguments (i.e., the user must find the appropriate `.debug` files and explicitly specify them as arguments)?
</blockquote></details>

Okay, I implemented [what GDB specifies](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html) and it seems to work okay. For example, I installed `python3.6-dbg` and now the symbols in Python binary resolve correctly.

I think that's enough for now - I would rather not add a separate option until somebody needs it; I think being able to install a `*-dbg` package or provide `binary.debug` / `.debug/binary.debug` file should be enough.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNzcmvEPwHj_JAhHFX:-MNOzZmQ64vk3lvexjfC:b-gzcu04) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Recover call graph (or at least a single caller)? I guess we could follow saved RBP and get something useful most of the time...

This would be super-useful, even with a single caller. I'm afraid we'll end up with `spinlock_lock` or something less than helpful in the profiles, and without a call graph that's not helpful.

From what I see in our Makefiles and `enclave_entry.S`, yes, we can use RBP. And even if not, we should be able to change our Makefiles and fix the asm files to track it.
</blockquote></details>

Okay. I can try it in next PR.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNParlz9FcL5WRPwNUn:-MNParlz9FcL5WRPwNUo:b-dllkoa) (no related file):*
I realized keeping a global variable for last timestamp is incorrect with multiple threads, so I moved it to thread-local storage (`sgx_tls`).

---
___
*[Documentation/manifest-syntax.rst, line 448 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNo7lu7MGnXcayfRTF:-MNP103M2lC8b-6FdMyh:b5yhmzg) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/manifest-syntax.rst#L448)):*
>How is it possible that you don't need to set this flag on sgx.profile? Or you do, but forgot to mention this in your added text?

Apparently `TCS.FLAGS.DBGOPTIN` controls these additional features but not whether to allow access to memory. This is controlled by DEBUG flag in SECS structure, which is enabled by default, and can be disabled by `sgx.debug = 0` in manifest.

>Also, now we have two ways of checking stats. Maybe we should merge them into one? Like sgx.profile = "sgx_stats"?

These are separate subsystems, and you can configure them independently (enable one of them, or enable both, and also configure `sgx.profile` as `root/all`), so I think they should stay as separate manifest options.
___
*[Documentation/manifest-syntax.rst, line 473 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNkUVl32W3ZMw2Uyec:-MNP1vOZ1Yj3LUKN3LxW:b-4ynoge) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/manifest-syntax.rst#L473)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we specify `root (main) process` as a synonym? (I typically use "main process" and haven't heard the term "root process".)
</blockquote></details>

Sure, I invented this on the spot. Changed to `main`.
___
*[Documentation/manifest-syntax.rst, line 474 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNk9K02C4M-XdmzKVp:-MNP2Tm66C5jG6WECNhj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/manifest-syntax.rst#L474)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`If it's to` -> `If it is set to`
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 531 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNkmNf5ku5OtNdHaeS:-MNP2_k31axU2K9GPJpD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/devel/performance.rst#L531)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Add a dot at the end.
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 535 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNkxVw2o1QJllq1-TX:-MNP2g0r5OmGDvUSMheP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/devel/performance.rst#L535)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`as well as other such` -> `as well as other events`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNnaceDnfQlt99aOGK:-MNP2wTa6KSo4INwRK9f:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/enclave_framework.c#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add smth like: `(recall that URSP is an outside stack pointer saved by EENTER and restored on AEX by the SGX hardware itself)`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/Makefile, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNnmtR7d4r6MatCru_:-MNP30PICR8uf5pOQ20g:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/Makefile#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not sorted.
</blockquote></details>

Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_entry.S, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNpH-M5yFMULeLLnwj:-MNP38Y01DRRM84BCpZQ:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/sgx_entry.S#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`required`
</ [...]

2020-11-30 20:41 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: 6 of 16 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNrG4u1Rh1NGLOTp4J:-MNPsQ-80aysOxhFWI2w:b-nbt2qu) (no related file):*
> Actually, do we have debug builds for SGX yet?
No, we don't. Right now we lack capacity, but I'm working on disabling LTP on SGX, so we could gain some time here, which we could expend on SGX debug builds. Right now this is stuck as part of #2003, which isn't ready yet.

---


<!-- Sent from Reviewable.io -->

2020-12-01 10:07 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNrG4u1Rh1NGLOTp4J:-MNSbV_VBj_-119A7wKo:btjzg51) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> Actually, do we have debug builds for SGX yet?
No, we don't. Right now we lack capacity, but I'm working on disabling LTP on SGX, so we could gain some time here, which we could expend on SGX debug builds. Right now this is stuck as part of #2003, which isn't ready yet.
</blockquote></details>

I see no problem in tucking the `SGX_PROFILE` functionality under `DEBUG`. The introduced AEX code is quite small and fast. And having a separate IFDEF logic for it is bad for development and testing (of other features, since developers will forget to test with `SGX_PROFILE=1` and discrepancies will creep in).

We'll need @mkow and @yamahata to chime in.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNyhZuCiFuDk7L_g9e:-MNSc8WkAnafOgDZcKIN:b-vifnll) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, I implemented [what GDB specifies](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html) and it seems to work okay. For example, I installed `python3.6-dbg` and now the symbols in Python binary resolve correctly.

I think that's enough for now - I would rather not add a separate option until somebody needs it; I think being able to install a `*-dbg` package or provide `binary.debug` / `.debug/binary.debug` file should be enough.
</blockquote></details>

Ok, this is awesome!

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNParlz9FcL5WRPwNUn:-MNSlGdm3GANpGHrwX8j:b2eca5z) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I realized keeping a global variable for last timestamp is incorrect with multiple threads, so I moved it to thread-local storage (`sgx_tls`).
</blockquote></details>

OK. You marked this comment as "blocking", please unblock yourself.

---
___
*[Documentation/manifest-syntax.rst, line 448 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNo7lu7MGnXcayfRTF:-MNScJQt7HPRi05uQH81:bkdwrpw) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Documentation/manifest-syntax.rst#L448)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>How is it possible that you don't need to set this flag on sgx.profile? Or you do, but forgot to mention this in your added text?

Apparently `TCS.FLAGS.DBGOPTIN` controls these additional features but not whether to allow access to memory. This is controlled by DEBUG flag in SECS structure, which is enabled by default, and can be disabled by `sgx.debug = 0` in manifest.

>Also, now we have two ways of checking stats. Maybe we should merge them into one? Like sgx.profile = "sgx_stats"?

These are separate subsystems, and you can configure them independently (enable one of them, or enable both, and also configure `sgx.profile` as `root/all`), so I think they should stay as separate manifest options.
</blockquote></details>

OK, agreed in both points.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNvulC7vudyu8DEDdf:-MNSiJV7ANdb26EZGGbD:b-r13gpl) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/sgx_profile.c#L225)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Maybe I'll start by showing what happened when I tried that.

This is the report for a short program that spends a few seconds in a loop (20e9 iterations):
```
   TIME  OBJ                   SYMBOL              

 93.91%  bootstrap             spin                
  4.57%  libpal.so             memcpy              
  0.62%  libpal.so             mbedtls_internal_sha256_process
  0.49%  libpal.so             cmac_xor_block      
  0.12%  libpal.so             mbedtls_aesni_crypt_ecb
  0.08%  libpal.so             memset              
  0.07%  libpal.so             _DkMutexLockTimeout 
```

This is the report for the same program when we increase by 1:
```
   TIME  OBJ                   SYMBOL              

 46.29%  libpal.so             memcpy              
 43.52%  bootstrap             spin                
  4.50%  libpal.so             memset              
  1.43%  libpal.so             mbedtls_internal_sha256_process
  0.84%  libpal.so             cmac_xor_block      
  0.69%  libpal.so             _DkExceptionHandler 
  0.24%  libpal.so             maybe_enlarge_slab_mgr
  0.22%  libpal.so             mbedtls_aesni_crypt_ecb
  0.17%  libpal.so             create_slab_mgr     
  0.09%  libpal.so             pal_linux_main      
  0.09%  libpal.so             elf_machine_rela_relative
  0.09%  libpal.so             strnlen             
  0.09%  libpal.so             _DkMutexLockTimeout 
  0.06%  libpal.so             handle_ecall        
  0.06%  libpal.so             (2a0ea)             
  0.06%  libpal.so             elf_dynamic_do_rela 
  0.06%  libpal.so             slab_alloc          
```

I think the difference is that there are a lot of AEXs caused by page faults, which inflates the count for `memcpy` and other functions, even though much less real time is spent in them than in `spin`. (I checked the exact IP value and it points right at the `rep movsb` instruction in memcpy, with 2138 occurences).

That's why I think measuring time is more accurate than just measuring number of AEXs (which is what increasing by `1` would do). Is that more clear? If so, do you have any suggestion how I could reword the explanation in the comment?
</blockquote></details>

Ok, now I understand this. What I was missing in my mental model is that we count only on AEX events, and these events do *not* have a fixed sampling period (unlike `perf record`). So we'll give more weight to the samples (and their corresponding IPs) after longer execution periods, and less weight to the samples after shorter execution periods. But we need to cap the duration of one execution period, otherwise a blocking/sleeping thread may seriously skew the results.

In other words, if AEX events would happen only due to timer interrupts (every 4ms), then we would have a fixed sampling period and could use `1` (or any fixed value like the clock `dt`, which would be approx. equal to 4ms). But since AEX events can happen also due to other events, we need to lower the weight of these "interjecting" events.

Well, I'm not sure how to describe it succinctly in a comment. Maybe `Samples are collected on AEX events, thus this profiling method doesn't have a fixed sampling period (unlike perf-record). But on modern Linux, we know that timer interrupts happen every 4ms (unless explicitly modified by admin), so we may assume that at least one AEX event happens every 4ms. However, AEX events happen on other interrupts/exceptions as well (such as page faults), thus we must lower the weight of these interjecting AEXs. We use "elapsed clock cycles" as a simple and sufficient way to control the weights of samples happening with different frequencies.`
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 63 at r2](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNSd5Yp03PpN749ETIK:-MNSd5Yp03PpN749ETIL:b-jnj20v) ([raw file](https://github.com/oscarlab/graphene/blob/78eae2e6a168fec876845522bffc7e4bd643f3ef/Pal/src/host/Linux-SGX/sgx_p [...]

2020-12-01 15:26 UTC, yamahata requested changes
> Reviewed 6 of 14 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: 15 of 16 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNrG4u1Rh1NGLOTp4J:-MNT8MKn4zmKDq6Q52Dg:bnjv9v6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see no problem in tucking the `SGX_PROFILE` functionality under `DEBUG`. The introduced AEX code is quite small and fast. And having a separate IFDEF logic for it is bad for development and testing (of other features, since developers will forget to test with `SGX_PROFILE=1` and discrepancies will creep in).

We'll need @mkow and @yamahata to chime in.
</blockquote></details>

+1 for DEBUG because people won’t test many ifdef combinations.

---
___
*[Pal/src/host/Linux-SGX/sgx_graphene.c, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNT9xxY3exGXdZqU5wK:-MNT9ufxEoc9b8QSOSQf:b-44p6km) ([raw file](https://github.com/oscarlab/graphene/blob/78eae2e6a168fec876845522bffc7e4bd643f3ef/Pal/src/host/Linux-SGX/sgx_graphene.c#L32)):*
> ```C
> }
> 
> static int vprintf(int fd, const char* fmt, va_list ap) {
> ```

nit: can the function be renamed?
because vprintf is wildly accepted name and we’re deviating from it.
___
*[Pal/src/host/Linux-SGX/tools/profile-report/profile-report, line 108 at r2](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNTtcKi2MKQqYi6Lwta:-MNTtcKi2MKQqYi6Lwtb:b-mi6lmg) ([raw file](https://github.com/oscarlab/graphene/blob/78eae2e6a168fec876845522bffc7e4bd643f3ef/Pal/src/host/Linux-SGX/tools/profile-report/profile-report#L108)):*
> ```
>         for addr, file_name in self.files:
>             self.symbols.extend(load_symbols(file_name, addr))
> ```

nitpick:
files.symbolts = [load_symbols(file_name, addr) if _, file_name in self.files]


<!-- Sent from Reviewable.io -->

2020-12-01 15:31 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: 15 of 16 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNvulC7vudyu8DEDdf:-MNTrn2G8qWvqhBJO2hQ:bwh1yj6) ([raw file](https://github.com/oscarlab/graphene/blob/96fc1f7c629b06fe49af7120c69c4ba97cf13cc4/Pal/src/host/Linux-SGX/sgx_profile.c#L225)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, now I understand this. What I was missing in my mental model is that we count only on AEX events, and these events do *not* have a fixed sampling period (unlike `perf record`). So we'll give more weight to the samples (and their corresponding IPs) after longer execution periods, and less weight to the samples after shorter execution periods. But we need to cap the duration of one execution period, otherwise a blocking/sleeping thread may seriously skew the results.

In other words, if AEX events would happen only due to timer interrupts (every 4ms), then we would have a fixed sampling period and could use `1` (or any fixed value like the clock `dt`, which would be approx. equal to 4ms). But since AEX events can happen also due to other events, we need to lower the weight of these "interjecting" events.

Well, I'm not sure how to describe it succinctly in a comment. Maybe `Samples are collected on AEX events, thus this profiling method doesn't have a fixed sampling period (unlike perf-record). But on modern Linux, we know that timer interrupts happen every 4ms (unless explicitly modified by admin), so we may assume that at least one AEX event happens every 4ms. However, AEX events happen on other interrupts/exceptions as well (such as page faults), thus we must lower the weight of these interjecting AEXs. We use "elapsed clock cycles" as a simple and sufficient way to control the weights of samples happening with different frequencies.`
</blockquote></details>

Thanks. I reworded the comment based on your suggestion.

I also changed the clock to `CLOCK_THREAD_CPUTIME_ID`. It should give better results in case the thread sleeps for some time, due to high load or blocking system calls (while these do not generate AEX, the next AEX will be delayed, so we would count too much time anyway). On my toy example from above, the result is pretty similar but `_DkMutexLockTimeout` went down from 0.07% to about 0.03%.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 63 at r2](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNSd5Yp03PpN749ETIK:-MNTnYaOASNtf0T_CvRD:bdwcyr5) ([raw file](https://github.com/oscarlab/graphene/blob/78eae2e6a168fec876845522bffc7e4bd643f3ef/Pal/src/host/Linux-SGX/sgx_profile.c#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This returns `0` (success). Do you want to change to smth like `-EINVAL`? But I'm not blocking on this.
</blockquote></details>

Good catch. I'm changing it to `-EINVAL` as we always expect to read the full size.


<!-- Sent from Reviewable.io -->

2020-12-01 16:03 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 216 at r3](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNU1oNB0gEBY-rwXCvi:-MNU1oNC-MLFgKUdfg-2:b-mkww0u) ([raw file](https://github.com/oscarlab/graphene/blob/2aea517515de5c5874be94c9b5842138e3263c9f/Pal/src/host/Linux-SGX/sgx_profile.c#L216)):*
> ```C
>     // Check current CPU time
>     struct timespec ts;
>     int res = INLINE_SYSCALL(clock_gettime, 2, CLOCK_THREAD_CPUTIME_ID, &ts);
> ```

Good idea to use this clock!


<!-- Sent from Reviewable.io -->

2020-12-02 10:38 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: 5 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNNrG4u1Rh1NGLOTp4J:-MNXxAgg0UxDUoIY-LK5:b-58xudh) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

+1 for DEBUG because people won’t test many ifdef combinations.
</blockquote></details>

Done. I removed `SGX_PROFILE` and used `DEBUG` instead.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNXzzKs3TgYB5kNYCpT:-MNXzzKs3TgYB5kNYCpU:baggw3x) (no related file):*
First success already! I used this to figure out a performance degradation in Tensorflow. The report said that a suspicious amount of time is spent in `memset`, which turned out to be zeroing memory for `_DkVirtualMemoryAlloc`, because the code allocated a lot of memory using `mmap`.

I think this confirms that some callers information would be super helpful (I added some code to get to `*(RBP + 8)` to find out about `_DkVirtualMemoryAlloc`). I talked with @mkow and he pointed out that using RBP will be inaccurate (the code might not use frame pointers, or have different conventions, etc.) But I still want to try that out, maybe adding some sanity checks for the value of RBP relative to RSP.

---
___
*[Pal/src/host/Linux-SGX/sgx_graphene.c, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNT9xxY3exGXdZqU5wK:-MNXxZnhEIgHTFAjWpL8:bcyxdl6) ([raw file](https://github.com/oscarlab/graphene/blob/78eae2e6a168fec876845522bffc7e4bd643f3ef/Pal/src/host/Linux-SGX/sgx_graphene.c#L32)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nit: can the function be renamed?
because vprintf is wildly accepted name and we’re deviating from it.
</blockquote></details>

I renamed it to `vfdprintf`, to match the `pal_fdprintf` below.
___
*[Pal/src/host/Linux-SGX/tools/profile-report/profile-report, line 108 at r2](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNTtcKi2MKQqYi6Lwta:-MNXxfaD3n3dQPjC9M-P:b-2764nu) ([raw file](https://github.com/oscarlab/graphene/blob/78eae2e6a168fec876845522bffc7e4bd643f3ef/Pal/src/host/Linux-SGX/tools/profile-report/profile-report#L108)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>         for addr, file_name in self.files:
>             self.symbols.extend(load_symbols(file_name, addr))
> ```

nitpick:
files.symbolts = [load_symbols(file_name, addr) if _, file_name in self.files]
</blockquote></details>

That would create a list of lists, not a flat list (I'm using `extend` here, not `append`). I could use something like
```
self.symbols = itertools.chain(*(load_symbols(file_name, addr) for addr, file_name in self.files))
```
but I think this is too much complexity for a single line, and the current way is more readable.


<!-- Sent from Reviewable.io -->

2020-12-02 23:38 UTC, yamahata approved these changes
> Reviewed 10 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/tools/profile-report/profile-report, line 108 at r2](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNTtcKi2MKQqYi6Lwta:-MN_oFvv6_mB0BjlcCPo:b-cx07dc) ([raw file](https://github.com/oscarlab/graphene/blob/78eae2e6a168fec876845522bffc7e4bd643f3ef/Pal/src/host/Linux-SGX/tools/profile-report/profile-report#L108)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That would create a list of lists, not a flat list (I'm using `extend` here, not `append`). I could use something like
```
self.symbols = itertools.chain(*(load_symbols(file_name, addr) for addr, file_name in self.files))
```
but I think this is too much complexity for a single line, and the current way is more readable.

</blockquote></details>

Oops. I scratch that.


<!-- Sent from Reviewable.io -->

2020-12-03 08:52 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`sendfile08` LTP test failed/timed out, never seen this before, must be unrelated to this PR)

2020-12-03 09:02 UTC, dimakuv requested changes
> Reviewed 9 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 485 at r4](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNboiTR2MPPnfXYDrwV:-MNboiTR2MPPnfXYDrwW:bnvs28c) ([raw file](https://github.com/oscarlab/graphene/blob/4f95892b315f01517e57d83dc313731a7889901c/Documentation/manifest-syntax.rst#L485)):*
> ```reStructuredText
> *Note:* this option is insecure and cannot be used with production enclaves
> (``sgx.debug = 0``). If the production enclave is started with this option set,
> Graphene will fail initialization of the enclave.
> ```

Is this true? I don't see any enforcement of this rule in your code.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 247 at r4](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNboZVvCQspmMzRDCHL:-MNboZVvCQspmMzRDCHM:b86gedd) ([raw file](https://github.com/oscarlab/graphene/blob/4f95892b315f01517e57d83dc313731a7889901c/Pal/src/host/Linux-SGX/sgx_profile.c#L247)):*
> ```C
>             counter->count += dt;
>         } else {
>             counter = malloc(sizeof(*counter));
> ```

Can we add error checking with "out of memory" debug message?


<!-- Sent from Reviewable.io -->

2020-12-03 09:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNbpeAzAtRUl3NDzOeq:-MNbpeAzAtRUl3NDzOer:b-bzdeur) (no related file):*
FYI: Jenkins-SGX-gsc pipeline fails because this PR was unfortunate to be submitted during the Jenkins transitioning period. The gsc failure must go away after the rebase of this PR.

---


<!-- Sent from Reviewable.io -->

2020-12-03 13:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 485 at r4](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNboiTR2MPPnfXYDrwV:-MNcmpIu1QpJgRj_d5yp:b3i5ev9) ([raw file](https://github.com/oscarlab/graphene/blob/4f95892b315f01517e57d83dc313731a7889901c/Documentation/manifest-syntax.rst#L485)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this true? I don't see any enforcement of this rule in your code.
</blockquote></details>

Not true anymore: an error in `debug_read` is not fatal.

I added a check to the initialization code.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 247 at r4](https://reviewable.io/reviews/oscarlab/graphene/2001#-MNboZVvCQspmMzRDCHL:-MNcqEZgBKxVFLQDX3PB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4f95892b315f01517e57d83dc313731a7889901c/Pal/src/host/Linux-SGX/sgx_profile.c#L247)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add error checking with "out of memory" debug message?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 15:11 UTC, dimakuv approved these changes
> Reviewed 1 of 11 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-15 07:58 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MO_Oy28CdFA2LDrYJly:-MO_Oy28CdFA2LDrYJlz:b-mpvql) (no related file):*
How does this compare with #2026 now?

---


<!-- Sent from Reviewable.io -->

2020-12-15 08:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MO_Oy28CdFA2LDrYJly:-MO_PT0-5PxgAu-oZ2Hr:b-s5igkv) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How does this compare with #2026 now?
</blockquote></details>

This PR does not use `perf` so #2026 does not help.

(I have a next version of this profiler, which does use `perf` and has stack information. But I was hoping to get this PR merged first, so that the next PR can be on top of it).

---


<!-- Sent from Reviewable.io -->

2020-12-15 11:47 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2001)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2001#-MO_Oy28CdFA2LDrYJly:-MOaD_63-93sy95DCVgh:bl34lks) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This PR does not use `perf` so #2026 does not help.

(I have a next version of this profiler, which does use `perf` and has stack information. But I was hoping to get this PR merged first, so that the next PR can be on top of it).
</blockquote></details>

Ok, good.

---


<!-- Sent from Reviewable.io -->

2020-12-15 12:45 UTC, pwmarcz commented
Okay... I wanted to wait for this one to be merged, and then make a new PR. But I see that it has non-trivial conflicts with master (manifest parsing code got moved) so I won't bother and make a new PR independently.

Consider this PR superseded by the new one: #2027

2020-12-22 14:31 UTC, closed without merging