Loader rework part 4: manifest loading and handling
oscarlab/graphene pull request #2008
Opened 2020-12-03 01:26 UTC by mkow

## Description of the changes

Another step in fixing the loader (previously in this series: #1895, #1901, #1915). This is a major refactor of the way manifests are loaded and handled, which will be followed by a complete rework of the loader code (which will include e.g. centralized config).

Changes:

* (a bit unrelated) Fixing return type in INTERNAL_SYSCALL macros
* Huge part of manifest handling was refactored and untangled.
* Starting without a manifest is now disallowed. This was actually accidentally broken for some time and no one complained. It also makes little sense in practice and in Graphene's overall design, e.g. it conflicts with protected argv.
* Now we only allow starting by giving the executable, not manifest (the magic resolution logic was removed).
* Now manifests are sent over pipes between parent and children, instead of children finding and loading them on their own. This is a preparation for the upcoming centralized manifests change.
* Previously manifests were parsed 2 times on Linux and 3 times on Linux-SGX (by untrusted PAL, trusted PAL and LibOS). This is now fixed.
* The common `pal_main()` now requires that the backend-specific PAL loader loads the manifest before calling it. SGX code already has to do it (for proper initialization), so let's unify this interface for all PALs.
* Fix for a PAL crash when manifest size was divisible by page size (sic!). NULL termination was missing, but most of the time the padding to page size saved Graphene from crashing.

## How to test this PR? 

CI.

2020-12-03 06:02 UTC, yamahata reviewed
> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/db_main.c, line 291 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbBIGnCs2UXe5dTUAO:-MNbBIGnCs2UXe5dTUAP:bn0zv1k) ([raw file](https://github.com/oscarlab/graphene/blob/0c9ed03164720f10f78dcb8babac06864a2f7c05/Pal/src/db_main.c#L291)):*
> ```C
>     }
> 
>     if (manifest_handle) {
> ```

Very nice cleanup.


<!-- Sent from Reviewable.io -->

2020-12-03 09:40 UTC, dimakuv reviewed
> Reviewed 37 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Documentation/devel/debugging.rst, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbqzor4wfyKhfSdMAA:-MNbqzor4wfyKhfSdMAB:bhqtqpi) ([raw file](https://github.com/oscarlab/graphene/blob/0c9ed03164720f10f78dcb8babac06864a2f7c05/Documentation/devel/debugging.rst#L22)):*
> ```reStructuredText
> To run Graphene with GDB, use the following command to run your application::
> 
>     GDB=1 [Graphene Directory]/Runtime/pal_loader [executable|manifest] [arguments]
> ```

What about the same in our README? We have "Option 2" there in the README...
___
*[Documentation/pal/host-abi.rst, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbrTxZA92I9chWkP7q:-MNbrTxZA92I9chWkP7r:byxmmsd) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Documentation/pal/host-abi.rst#L31)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> The PAL loader supports multiple ways of locating the manifest and executable.
> ```

Should we just remove this first sentence? `multiple` is definitely an incorrect word here.
___
*[Pal/src/pal_internal.h, line 187 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbsiPq51TuqKwqpjYW:-MNbsiPq51TuqKwqpjYX:b-a0lx80) ([raw file](https://github.com/oscarlab/graphene/blob/0c9ed03164720f10f78dcb8babac06864a2f7c05/Pal/src/pal_internal.h#L187)):*
> ```objc
>  * \param instance_id       current instance id
>  * \param manifest_handle   manifest handle if opened
>  * \param exec_handle       executable handle if opened
> ```

You shouldn't have removed `exec_handle`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 675 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx4Kk1MTSw-W-ma5a:-MNbx4Kk1MTSw-W-ma5b:beontuu) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L675)):*
> ```C
>     if (ret < 0 || (sgx_remote_attestation_int != 0 && sgx_remote_attestation_int != 1)) {
>         SGX_DBG(DBG_E, "Cannot parse \'sgx.remote_attestation\' (the value must be 0 or 1)\n");
>         return -EINVAL;
> ```

Replace with `goto`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx6wz5mN-CzAm8o9D:-MNbx6wz5mN-CzAm8o9E:beontuu) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L684)):*
> ```C
>         SGX_DBG(DBG_E, "Cannot parse \'sgx.ra_client_spid\' "
>                        "(the value must be put in double quotes!)\n");
>         return -EINVAL;
> ```

Replace with `goto`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 692 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx7fZ3q_YI8AWBBYf:-MNbx7f_71vaTgU0roPs:beontuu) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L692)):*
> ```C
>     if (ret < 0) {
>         SGX_DBG(DBG_E, "Cannot parse \'sgx.ra_client_linkable\'\n");
>         return -EINVAL;
> ```

Replace with `goto`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 701 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx8NjEEt-i2KIv1nA:-MNbx8NjEEt-i2KIv1nB:beontuu) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L701)):*
> ```C
>                 "\'ra_client_linkable\' in the manifest but no \'remote_attestation\' parameter. "
>                 "Please add \'sgx.remote_attestation = 1\' to the manifest.\n");
>         return -EINVAL;
> ```

Replace with `goto`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 706 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx9CM5c9GZ8zrl-5l:-MNbx9CM5c9GZ8zrl-5m:bgf1obl) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L706)):*
> ```C
>     /* EPID is used if SPID is a non-empty string in manifest, otherwise DCAP/ECDSA */
>     enclave_info->use_epid_attestation = sgx_ra_client_spid_str && strlen(sgx_ra_client_spid_str);
>     free(sgx_ra_client_spid_str);
> ```

I suggest to move this free to `out`
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbxWdqCPJx6S_Idvsx:-MNbxWdqCPJx6S_Idvsy:b-wgxiow) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_process.c#L31)):*
> ```C
>     int          stream_fd;
>     PAL_SEC_STR  pipe_prefix;
>     size_t       manifest_size; // manifest will follow this struct on the pipe.
> ```

Shouldn't it be `manifest_len` because you don't send the NUL byte?


<!-- Sent from Reviewable.io -->

2020-12-03 14:03 UTC, mkow reviewed
> Reviewed 37 of 37 files at r1, 1 of 1 files at r2, 32 of 32 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/devel/debugging.rst, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbqzor4wfyKhfSdMAA:-MNcZoeLELlgnBhuDLQn:b-9hoq2b) ([raw file](https://github.com/oscarlab/graphene/blob/0c9ed03164720f10f78dcb8babac06864a2f7c05/Documentation/devel/debugging.rst#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about the same in our README? We have "Option 2" there in the README...
</blockquote></details>

Thanks, I missed this when grepping for such descriptions! I also found now another bunch of occurrences and fixed them.
___
*[Documentation/pal/host-abi.rst, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbrTxZA92I9chWkP7q:-MNcnTJ27Ldymtz2iYle:b-mh93qr) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Documentation/pal/host-abi.rst#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should we just remove this first sentence? `multiple` is definitely an incorrect word here.
</blockquote></details>

Right, done. Finally we can remove it.
___
*[Pal/src/pal_internal.h, line 187 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbsiPq51TuqKwqpjYW:-MNcnrnc8VGQ-Cx9m23t:b-2prhzr) ([raw file](https://github.com/oscarlab/graphene/blob/0c9ed03164720f10f78dcb8babac06864a2f7c05/Pal/src/pal_internal.h#L187)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You shouldn't have removed `exec_handle`
</blockquote></details>

Oops, this slipped from the future changes (not included in this PR).
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 675 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx4Kk1MTSw-W-ma5a:-MNcoLSl5X_i9QegfB4W:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L675)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Replace with `goto`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx6wz5mN-CzAm8o9D:-MNcoM9g0s5jnSdhNcVy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L684)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Replace with `goto`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 692 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx7fZ3q_YI8AWBBYf:-MNcoM_oB1NHaCILcVTK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L692)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Replace with `goto`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 701 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx8NjEEt-i2KIv1nA:-MNcoN0i7G8nmjT_veu8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L701)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Replace with `goto`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 706 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbx9CM5c9GZ8zrl-5l:-MNcoXL-7u-SgWRxA4WY:b-7jzv7t) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_main.c#L706)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to move this free to `out`
</blockquote></details>

right
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbxWdqCPJx6S_Idvsx:-MNco_iE9dmDewyTnblU:br73qpx) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_process.c#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't it be `manifest_len` because you don't send the NUL byte?
</blockquote></details>

Nope, this is the byte-size of the object which is sent over a pipe, which is not a C-string (len is only for C-strings). I can rename it to `manifest_data_size` if you think it's better this way.


<!-- Sent from Reviewable.io -->

2020-12-03 15:20 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r2, 31 of 32 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNbxWdqCPJx6S_Idvsx:-MNdAyHn2SM544H93Ws8:b-jjmh43) ([raw file](https://github.com/oscarlab/graphene/blob/ac0f4b02378b5d38ffdbb6744f212ca3cf73c859/Pal/src/host/Linux-SGX/sgx_process.c#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nope, this is the byte-size of the object which is sent over a pipe, which is not a C-string (len is only for C-strings). I can rename it to `manifest_data_size` if you think it's better this way.
</blockquote></details>

OK, I'm fine with this explanation.


<!-- Sent from Reviewable.io -->

2020-12-03 19:16 UTC, boryspoplawski reviewed
> Reviewed 31 of 37 files at r1, 1 of 1 files at r2, 31 of 32 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " and "DO NOT MERGE" found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 257 at r4](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdVpgi-lzHhy9uXnY1:-MNdVpgi-lzHhy9uXnY2:b-vtiu5p) ([raw file](https://github.com/oscarlab/graphene/blob/b323b058b0139b92e2b71b52c19842e667fae67a/Pal/src/host/Linux/db_main.c#L257)):*
> ```C
> 
>         ret = read_text_file_to_cstr(manifest_path, &manifest);
>         if (ret == -ENOENT)
> ```

Nitpick: either add curly brackets here or remove them from the if below.
___
*[Pal/src/host/Linux/db_process.c, line 218 at r4](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdXRk134SJZoeLxOOI:-MNdXRk134SJZoeLxOOJ:b-p8y6al) ([raw file](https://github.com/oscarlab/graphene/blob/b323b058b0139b92e2b71b52c19842e667fae67a/Pal/src/host/Linux/db_process.c#L218)):*
> ```C
>     memcpy(data, parent_data, parent_data_size);
>     proc_args->parent_data_size = parent_data_size;
>     data += parent_data_size;
> ```

Please don't do arithmetic on `void*`.
___
*[Pal/src/host/Linux-common/file_utils.c, line 18 at r4](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdgUTF9OQBTeQ1hr-l:-MNdgUTF9OQBTeQ1hr-m:bjxkp14) ([raw file](https://github.com/oscarlab/graphene/blob/b323b058b0139b92e2b71b52c19842e667fae67a/Pal/src/host/Linux-common/file_utils.c#L18)):*
> ```C
>     long ret;
>     char* buf = NULL;
>     long fd = INLINE_SYSCALL(open, 3, path, O_RDONLY, 0);
> ```

Why not `INLINE_SYSCALL(open, 2, path, O_RDONLY)` ?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 245 at r5](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdm8uq0ymmzmQjwCUj:-MNdm8uq0ymmzmQjwCUk:b-jmmgkr) ([raw file](https://github.com/oscarlab/graphene/blob/d0b924470baac0e1fe94b8c20d4d689a1f6906e0/Pal/src/host/Linux-SGX/sgx_main.c#L245)):*
> ```C
>             TLS
>         } data_src;
>         int fd; // valid iff data_src == ELF_FD
> ```

union?
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 115 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe0XdR9gQukEsjTLeG:-MNe0XdSB_7TgzM0ubhP:b-d98wwm) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L115)):*
> ```C
>     ret = INLINE_SYSCALL(write, 3, fds[1], &proc_args, sizeof(struct proc_args));
>     if (IS_ERR(ret) || (size_t)ret != sizeof(struct proc_args)) {
>         ret = IS_ERR(ret) ? -ERRNO(ret) : -EINTR;
> ```

Uhm, why do we need this `-ERRNO(ret)` ? It's just the same as `ret` (except for intermediate case to `long`) ...
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 121 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe0iZfCf1aF1J9cB3b:-MNe0iZfCf1aF1J9cB3c:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L121)):*
> ```C
>     ret = INLINE_SYSCALL(write, 3, fds[1], manifest, proc_args.manifest_size);
>     if (IS_ERR(ret) || (size_t)ret != proc_args.manifest_size) {
>         ret = IS_ERR(ret) ? -ERRNO(ret) : -EINTR;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 127 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe0jIS6Zl2B529rvMT:-MNe0jIT5-up7VYf6K7R:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L127)):*
> ```C
>     ret = INLINE_SYSCALL(read, 3, fds[1], &rete, sizeof(rete));
>     if (IS_ERR(ret) || (size_t)ret != sizeof(rete)) {
>         ret = IS_ERR(ret) ? -ERRNO(ret) : -EINTR;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 161 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe11mN9FKs2W6tlZfr:-MNe11mN9FKs2W6tlZfs:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L161)):*
> ```C
>     bytes_read = INLINE_SYSCALL(read, 3, parent_pipe_fd, &proc_args, sizeof(struct proc_args));
>     if (IS_ERR(bytes_read) || bytes_read != sizeof(struct proc_args)) {
>         ret = IS_ERR(bytes_read) ? -ERRNO(bytes_read) : -EINTR;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 173 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe13KD6qL8RT49WNaX:-MNe13KD6qL8RT49WNaY:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L173)):*
> ```C
>     bytes_read = INLINE_SYSCALL(read, 3, parent_pipe_fd, manifest, proc_args.manifest_size);
>     if (IS_ERR(bytes_read)) {
>         ret = IS_ERR(bytes_read) ? -ERRNO(bytes_read) : -EINTR;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 181 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe141M8EbcD3wfcFrb:-MNe141M8EbcD3wfcFrc:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L181)):*
> ```C
>     bytes_written = INLINE_SYSCALL(write, 3, parent_pipe_fd, &child_status, sizeof(int));
>     if (IS_ERR(bytes_written)) {
>         ret = IS_ERR(bytes_written) ? -ERRNO(bytes_written) : -EINTR;
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-12-03 22:59 UTC, mkow reviewed
> Reviewed 1 of 2 files at r5, 2 of 66 files at r7, 1 of 1 files at r8, 63 of 63 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_main.c, line 257 at r4](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdVpgi-lzHhy9uXnY1:-MNekkRy35Ta48SEaqCf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b323b058b0139b92e2b71b52c19842e667fae67a/Pal/src/host/Linux/db_main.c#L257)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: either add curly brackets here or remove them from the if below.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_process.c, line 218 at r4](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdXRk134SJZoeLxOOI:-MNeklUU3632y7i3Khn3:b-jjmij0) ([raw file](https://github.com/oscarlab/graphene/blob/b323b058b0139b92e2b71b52c19842e667fae67a/Pal/src/host/Linux/db_process.c#L218)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please don't do arithmetic on `void*`.
</blockquote></details>

I was already like that before, but I can fix it.
___
*[Pal/src/host/Linux-common/file_utils.c, line 18 at r4](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdgUTF9OQBTeQ1hr-l:-MNelIaB4rzboPvMGOF_:bavj0fr) ([raw file](https://github.com/oscarlab/graphene/blob/b323b058b0139b92e2b71b52c19842e667fae67a/Pal/src/host/Linux-common/file_utils.c#L18)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `INLINE_SYSCALL(open, 2, path, O_RDONLY)` ?
</blockquote></details>

The syscall is not variadic (only C wrapper is), and I think omitting arguments is quite an ugly hack in this case.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 245 at r5](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdm8uq0ymmzmQjwCUj:-MNelaag1nVzr0fN5qu8:bsgtetp) ([raw file](https://github.com/oscarlab/graphene/blob/d0b924470baac0e1fe94b8c20d4d689a1f6906e0/Pal/src/host/Linux-SGX/sgx_main.c#L245)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

union?
</blockquote></details>

I thought about it, but the code would look much uglier (a lot of nesting, because this would be an union with a struct inside). IMO current version is simple enough to not need an union.
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 115 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe0XdR9gQukEsjTLeG:-MNelyw96DBcM9IxnvBi:b14n60d) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Uhm, why do we need this `-ERRNO(ret)` ? It's just the same as `ret` (except for intermediate case to `long`) ...
</blockquote></details>

I thought this way it will be more explicit (that we are extracting errno value from a `long`, especially in that case with `bytes_read`). But I can simplify it.
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 121 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe0iZfCf1aF1J9cB3b:-MNemRVU3eq5fgfCA1Xk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L121)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 127 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe0jIS6Zl2B529rvMT:-MNemSQhA_Bsu3StU05G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 161 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe11mN9FKs2W6tlZfr:-MNemXRoCB-LHdueGm02:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 173 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe13KD6qL8RT49WNaX:-MNemXqC9WMi2HrTC5Eu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L173)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 181 at r6](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNe141M8EbcD3wfcFrb:-MNemYHN5_pabLaaVmzC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/100834cd2b958bf68169ff67f03d5fd938c801c6/Pal/src/host/Linux-SGX/sgx_process.c#L181)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-04 09:42 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r8, 62 of 63 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/db_main.c, line 258 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh03rA5oQiQmEK2m_r:-MNh03rA5oQiQmEK2m_s:b-xnv4vv) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L258)):*
> ```C
> noreturn void pal_main(PAL_NUM instance_id,        /* current instance id */
>                        PAL_HANDLE exec_handle,     /* executable handle if opened */
>                        PAL_PTR exec_loaded_addr,   /* executable addr if loaded */
> ```

Feels like this `exec_loaded_addr` is not really needed in this function (we may extract the same info from `exec_handle`). But not blocking.
___
*[Pal/src/db_main.c, line 267 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNgzoFLD_0c4Rw7OFX1:-MNgzoFLD_0c4Rw7OFX2:b-uousdh) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L267)):*
> ```C
> 
>     char uri_buf[URI_MAX];
>     char* exec_uri = NULL;
> ```

`uri_buf` is used only once in this function, to populate `exec_uri`. I suggest to simplify: remove `uri_buf` and just do `exec_uri = malloc(URI_MAX)` (who cares about these 4KB taken from the heap). Then you won't need `malloc_copy()`.
___
*[Pal/src/db_main.c, line 270 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNgyewHA7t11z-19Zvq:-MNgyewI2bdZpyvyufa8:b-tiaea5) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L270)):*
> ```C
>     ssize_t ret;
> 
>     assert(g_pal_state.manifest_root);
> ```

You moved `init_slab_mgr()` to the host-specific PAL. But don't you want to assert here that `g_pal_state.alloc_align` was also initialized?
___
*[Pal/src/db_main.c, line 284 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh-PsE5QUvkenGPyae:-MNh-PsE5QUvkenGPyaf:b-d1eabd) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L284)):*
> ```C
>         INIT_FAIL(PAL_ERROR_INVAL, "loader.exec is not supported anymore. Please update your "
>                                    "manifest according to the current documentation.");
> ```

Oops, my fault in a previous PR: I forgot to `free(dummy_exec_str)` after it was used. Please add this free here.
___
*[Pal/src/db_main.c, line 286 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh-eeA--5l9Bj1v6RP:-MNh-eeA--5l9Bj1v6RQ:byavqjv) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L286)):*
> ```C
> 
>     /* must be an ELF */
>     if (exec_handle) {
> ```

Why do you have this `if`? You already asserted that it is not NULL.
___
*[Pal/src/db_main.c, line 313 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh0QBH5FHoRiG3t75D:-MNh0QBH5FHoRiG3t75E:b-xlx0aw) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L313)):*
> ```C
>      * for manifests). 'loader.argv0_override' won't be needed after implementing this feature and
>      * resolving https://github.com/oscarlab/graphene/issues/1053 (RFC: graphene invocation).
>      */
> ```

BTW, looks like we can implement this now that we have proper TOML, right?
___
*[Pal/src/db_main.c, line 379 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh0kJ39DuxJTBLCXie:-MNh0kJ39DuxJTBLCXif:bxfrieh) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L379)):*
> ```C
> 
>     if (use_host_env) {
>         printf("WARNING: Forwarding host environment variables to the app is enabled. Don't use "
> ```

A bit unrelated, but can we `/* Warn only in the first process. */` here as well (just like in argv)?
___
*[Pal/src/db_main.c, line 415 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh0-2I4na7crquRMYJ:-MNh0-2I4na7crquRMYK:byavqjv) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L415)):*
> ```C
>     load_libraries();
> 
>     if (exec_handle) {
> ```

Why do you have this `if`? You already asserted that it is not NULL.
___
*[Pal/src/db_main.c, line 440 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh19D788eaJqx677W3:-MNh19D788eaJqx677W4:b-4pqeej) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L440)):*
> ```C
>                                     &g_pal_control.user_address.end);
> 
>     g_pal_control.alloc_align = g_pal_state.alloc_align;
> ```

BTW, did you figure out why we need two similar objects, `g_pal_control` and `g_pal_state`?
___
*[Pal/src/pal_internal.h, line 184 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh1Hy96L4Uytq0aiWh:-MNh1Hy96L4Uytq0aiWi:b-tzhorh) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/pal_internal.h#L184)):*
> ```objc
>  * \param instance_id       current instance id
>  * \param exec_handle       executable handle if opened
>  * \param exec_loaded_addr  executable addr if loaded
> ```

As mentioned above, this is not really needed. But not blocking.
___
*[Pal/src/host/Linux/db_process.c, line 298 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh2WQYBddGM5pbKt_M:-MNh2WQYBddGM5pbKt_N:bjqrq07) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux/db_process.c#L298)):*
> ```C
> 
>     /* try to do a very large reading, so it doesn't have to be read for the
>        second time */
> ```

Can we remove this comment? It is incorrect.
___
*[Pal/src/host/Linux/db_process.c, line 299 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh2ZW652JzN8-HvEqn:-MNh2ZW652JzN8-HvEqo:bpb9lgy) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux/db_process.c#L299)):*
> ```C
>     /* try to do a very large reading, so it doesn't have to be read for the
>        second time */
>     struct proc_args* proc_args = __alloca(sizeof(struct proc_args));
> ```

Can we remove `__alloca` and just have a normal stack var. Who wrote this...
___
*[Pal/src/host/Linux/db_process.c, line 315 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh338108ddIil8ObxS:-MNh33823vCWUJl43vmK:b-sigvix) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux/db_process.c#L315)):*
> ```C
>     new_proc_args = __alloca(sizeof(*proc_args) + data_size);
>     memcpy(new_proc_args, proc_args, sizeof(*proc_args));
>     proc_args = new_proc_args;
> ```

This makes my eyes bleed. We can't allocate `new_proc_args` on the stack, because the manifest can be huge in size (theoretically). We need to allocate a `data` blob on the heap (or via an explicit `INLINE_SYSCALL(mmap)`), and *not* do the rewiring of `proc_args`. Please refactor all this logic, I'm surprised that it even worked for so long.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 557 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh4vXFAZYT_RJEItvX:-MNh4vXGDZHqcLsT4ITM:b-tmjwgn) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux-SGX/sgx_main.c#L557)):*
> ```C
> }
> 
> static int parse_loader_config(char* loader_config, struct pal_enclave* enclave_info) {
> ```

Why did you decide to change the name? We are still parsing the manifest.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 670 at r9](https://reviewable.io/reviews [...]

2020-12-04 10:43 UTC, boryspoplawski requested changes
> Reviewed 2 of 66 files at r7, 1 of 1 files at r8, 63 of 63 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[Pal/src/db_main.c, line 267 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNgzoFLD_0c4Rw7OFX1:-MNhHKhOAyRzZaNCdEPu:b82xr61) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L267)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`uri_buf` is used only once in this function, to populate `exec_uri`. I suggest to simplify: remove `uri_buf` and just do `exec_uri = malloc(URI_MAX)` (who cares about these 4KB taken from the heap). Then you won't need `malloc_copy()`.
</blockquote></details>

+1 as this function does not return.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 245 at r5](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdm8uq0ymmzmQjwCUj:-MNhKVwkDw3bFywLFT2V:b-7r4zy3) ([raw file](https://github.com/oscarlab/graphene/blob/d0b924470baac0e1fe94b8c20d4d689a1f6906e0/Pal/src/host/Linux-SGX/sgx_main.c#L245)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I thought about it, but the code would look much uglier (a lot of nesting, because this would be an union with a struct inside). IMO current version is simple enough to not need an union.
</blockquote></details>

Both struct and union can be anonymous - accessing fields would stay the same. Now you have to specify conditions in comments on when each field has a meaning, which I don't like.


<!-- Sent from Reviewable.io -->

2020-12-04 12:51 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/db_process.c, line 207 at r10](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNhmzxG1MAafqFOy-0K:-MNhmzxG1MAafqFOy-0L:b-4g7n10) ([raw file](https://github.com/oscarlab/graphene/blob/e6af96a4ea8049849982d92fe7af7bf930ecb621/Pal/src/host/Linux/db_process.c#L207)):*
> ```C
> 
>     size_t data_size = parent_data_size + exec_data_size + manifest_data_size;
>     proc_args = malloc(sizeof(struct proc_args) + data_size);
> ```

Please add error checking.
___
*[Pal/src/host/Linux/db_process.c, line 313 at r10](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNhnWGXA9aHrSrQPVVY:-MNhnWGXA9aHrSrQPVVZ:b-4g7n10) ([raw file](https://github.com/oscarlab/graphene/blob/e6af96a4ea8049849982d92fe7af7bf930ecb621/Pal/src/host/Linux/db_process.c#L313)):*
> ```C
>     size_t data_size = proc_args.parent_data_size + proc_args.exec_data_size
>                        + proc_args.manifest_data_size;
>     char* data = malloc(data_size);
> ```

Please add error checking.


<!-- Sent from Reviewable.io -->

2020-12-04 12:58 UTC, mkow reviewed
> Reviewed 2 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/src/db_main.c, line 258 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh03rA5oQiQmEK2m_r:-MNhJbNV24xsD4-rMp-K:b-qs94ye) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L258)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Feels like this `exec_loaded_addr` is not really needed in this function (we may extract the same info from `exec_handle`). But not blocking.
</blockquote></details>

Yup, but this is something for the next PR (the whole exec handling will change).
___
*[Pal/src/db_main.c, line 267 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNgzoFLD_0c4Rw7OFX1:-MNhJmGV1FBQtb8I_xrC:bvzdhys) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L267)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 as this function does not return.
</blockquote></details>

ditto - I'll remove all this code in the upcoming PR
___
*[Pal/src/db_main.c, line 270 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNgyewHA7t11z-19Zvq:-MNhQWC53Urh0PqXjWhM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L270)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You moved `init_slab_mgr()` to the host-specific PAL. But don't you want to assert here that `g_pal_state.alloc_align` was also initialized?
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 284 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh-PsE5QUvkenGPyae:-MNhQc_t8fWvcniENe-o:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L284)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, my fault in a previous PR: I forgot to `free(dummy_exec_str)` after it was used. Please add this free here.
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 286 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh-eeA--5l9Bj1v6RP:-MNhQiKj5NNhxh6CZU6A:bss7047) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have this `if`? You already asserted that it is not NULL.
</blockquote></details>

Leftover from the original code which didn't have it. Fixed.
___
*[Pal/src/db_main.c, line 313 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh0QBH5FHoRiG3t75D:-MNhSWEbE6x-GWZGWIFe:b-rj57wo) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L313)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, looks like we can implement this now that we have proper TOML, right?
</blockquote></details>

Yup. But that's something for another PR which would conflict with the loader rework, so I left this for later.
___
*[Pal/src/db_main.c, line 379 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh0kJ39DuxJTBLCXie:-MNhTB6f0I5YPpJ_Uimp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L379)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A bit unrelated, but can we `/* Warn only in the first process. */` here as well (just like in argv)?
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 415 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh0-2I4na7crquRMYJ:-MNhTC6a4Hvor6l0MHix:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L415)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have this `if`? You already asserted that it is not NULL.
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 440 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh19D788eaJqx677W3:-MNhTDzx8KnXr0IaG9XD:bhnkvhy) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/db_main.c#L440)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, did you figure out why we need two similar objects, `g_pal_control` and `g_pal_state`?
</blockquote></details>

No idea yet, we even have more that just those two, all with meaningless names (like "pal_sec", with zero relation to security). No one knows what's the difference between them...
___
*[Pal/src/pal_internal.h, line 184 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh1Hy96L4Uytq0aiWh:-MNhTYqj0wfXHTnNY_4n:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/pal_internal.h#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As mentioned above, this is not really needed. But not blocking.
</blockquote></details>

ditto
___
*[Pal/src/host/Linux/db_process.c, line 298 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh2WQYBddGM5pbKt_M:-MNhTfQC51jLA95SGqPj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux/db_process.c#L298)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove this comment? It is incorrect.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_process.c, line 299 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh2ZW652JzN8-HvEqn:-MNhTjQM3q-_kmN_U5hF:b-x1xt3d) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux/db_process.c#L299)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove `__alloca` and just have a normal stack var. Who wrote this...
</blockquote></details>

Lol, didn't notice this previously :) Fixed and refactored this whole mess around here.
___
*[Pal/src/host/Linux/db_process.c, line 315 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh338108ddIil8ObxS:-MNhYA4eAwFowy3pRrUl:b8ch48u) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux/db_process.c#L315)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This makes my eyes bleed. We can't allocate `new_proc_args` on the stack, because the manifest can be huge in size (theoretically). We need to allocate a `data` blob on the heap (or via an explicit `INLINE_SYSCALL(mmap)`), and *not* do the rewiring of `proc_args`. Please refactor all this logic, I'm surprised that it even worked for so long.
</blockquote></details>

Done, refactored all the hacks here.
___
*[Pal/src/host/Linux/db_process.c, line 207 at r10](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNhmzxG1MAafqFOy-0K:-MNhnygo3eyaDhDJV1LP:b-99ro7q) ([raw file](https://github.com/oscarlab/graphene/blob/e6af96a4ea8049849982d92fe7af7bf930ecb621/Pal/src/host/Linux/db_process.c#L207)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Pleas [...]

2020-12-04 13:07 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 245 at r5](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdm8uq0ymmzmQjwCUj:-MNhqrAO7AKX4r2-UW2a:b5jt7o) ([raw file](https://github.com/oscarlab/graphene/blob/d0b924470baac0e1fe94b8c20d4d689a1f6906e0/Pal/src/host/Linux-SGX/sgx_main.c#L245)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If I make them anonymous then I'll still need to add a comment to say which fields correspond to which data type.
</blockquote></details>

But it will be cleaner. (and you won't need `// ^`)


<!-- Sent from Reviewable.io -->

2020-12-04 13:56 UTC, mkow reviewed
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 245 at r5](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNdm8uq0ymmzmQjwCUj:-MNi0HAi5QQ77TrJid5f:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d0b924470baac0e1fe94b8c20d4d689a1f6906e0/Pal/src/host/Linux-SGX/sgx_main.c#L245)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it will be cleaner. (and you won't need `// ^`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-04 13:59 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2020-12-04 22:07 UTC, dimakuv approved these changes
> Reviewed 1 of 63 files at r9, 1 of 3 files at r10, 1 of 1 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 780 at r9](https://reviewable.io/reviews/oscarlab/graphene/2008#-MNh5BWi5j5Qoh7oB158:-MNjmubIC89iSy669BPu:bh1bh2s) ([raw file](https://github.com/oscarlab/graphene/blob/2952f90f4499d1baef778f022b34bf1e54d29a9f/Pal/src/host/Linux-SGX/sgx_main.c#L780)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a bit foreshadowing the future stripping of all information from it. Should I rename it or leave it as is?
</blockquote></details>

OK, leave as is.


<!-- Sent from Reviewable.io -->

2020-12-04 22:56 UTC, mkow commented
Jenkins, retest this please (seems there was a restart of Jenkins in the meantime?)

2020-12-04 23:54 UTC, mkow commented
Jenkins, retest this please (let's try now after more Jenkins recovery)

2020-12-05 00:48 UTC, mkow reviewed
> Reviewed 1 of 1 files at r15, 63 of 63 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2020-12-05 21:27 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r15, 63 of 63 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2020-12-06 00:20 UTC, boryspoplawski approved these changes
> Reviewed 1 of 66 files at r7, 1 of 1 files at r15, 63 of 63 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2008)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-06 00:25 UTC, merged