[Pal/Linux-SGX] Fix type cast issue during async signal handling
oscarlab/graphene pull request #2020
Opened 2020-12-09 19:16 UTC by dimakuv

## Description of the changes 

Untrusted Linux-SGX PAL handles host-level asynchronous signals by emulating the interrupt (-EINTR) of the pending OCALL. Unfortunately, there was a type cast issue such that int32_t -EINTR (`-4`) was casted to a positive uint64_t and then OCALL consumed this positive number instead of erroring out on -EINTR. This PR adds explicit type casting to fix this bug.

## How to test this PR? 

All tests must pass. This bug was found on a large workload that spawned several child processes. Sometimes it so happened that one child process finished and sent SIGCHLD signal to the main (parent) process, and the main process simultaneously was sending a checkpoint to another spawned child. This resulted in `ocall_read()` being interrupted and then returning a ridiculous big number instead of `-EINTR`, and the whole application crashed.

2020-12-09 19:29 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/2020#-MO7yTxa2HlK2WS1syAo:-MO7yTxbCJHX6P2BCIMj:bee50tm) ([raw file](https://github.com/oscarlab/graphene/blob/4ae33fead790076669f0069888a11e9b43cbfdab/Pal/src/host/Linux-SGX/sgx_exception.c#L178)):*
> ```C
>     /* signal arrived while in untrusted PAL code (during syscall handling), emulate as if syscall
>      * was interrupted by calling sgx_entry_return(syscall_return_value=-EINTR, event); NOTE: must
>      * always explicitly type cast arguments to the `greg_t` type! */
> ```

please explain why (because `pal_ucontext_set_function_parameters` is variadic and reads this argument as `greg_t`, not `int`)


<!-- Sent from Reviewable.io -->

2020-12-09 19:36 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2020-12-09 21:44 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/2020#-MO7yTxa2HlK2WS1syAo:-MO8QtIa5pwWEpBnRhBy:b-xzfvki) ([raw file](https://github.com/oscarlab/graphene/blob/4ae33fead790076669f0069888a11e9b43cbfdab/Pal/src/host/Linux-SGX/sgx_exception.c#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please explain why (because `pal_ucontext_set_function_parameters` is variadic and reads this argument as `greg_t`, not `int`)
</blockquote></details>

+1. This is the only use.
Maybe we can have explicit 4 parameters with size.


<!-- Sent from Reviewable.io -->

2020-12-09 22:11 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/2020#-MO7yTxa2HlK2WS1syAo:-MO8YVU3ElZf-T1qsxX8:b4n7jt4) ([raw file](https://github.com/oscarlab/graphene/blob/4ae33fead790076669f0069888a11e9b43cbfdab/Pal/src/host/Linux-SGX/sgx_exception.c#L178)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

+1. This is the only use.
Maybe we can have explicit 4 parameters with size.
</blockquote></details>

+1 to what @yamahata said: please change it to non-variadic function (and change name accordingly).


<!-- Sent from Reviewable.io -->

2020-12-10 09:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/2020#-MO7yTxa2HlK2WS1syAo:-MOB1Fju64NagMAk4xzu:bobz2o5) ([raw file](https://github.com/oscarlab/graphene/blob/4ae33fead790076669f0069888a11e9b43cbfdab/Pal/src/host/Linux-SGX/sgx_exception.c#L178)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 to what @yamahata said: please change it to non-variadic function (and change name accordingly).
</blockquote></details>

Done. I opted for a fixed-size array instead of for explicit arguments. And I don't know how to change the function name. Please suggest.


<!-- Sent from Reviewable.io -->

2020-12-10 09:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOB1_c3ClWNFWpOx32e:-MOB1_c3ClWNFWpOx32f:bx8ra9s) (no related file):*
@stefanberger Does this change make sense to you? Is it fine for your purposes?

---


<!-- Sent from Reviewable.io -->

2020-12-10 13:04 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/Linux/ucontext.h, line 161 at r3](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOBjj5uBDYOVnFWSGqV:-MOBjj5uBDYOVnFWSGqW:b-prx4qv) ([raw file](https://github.com/oscarlab/graphene/blob/5cfcc323c3809d30595460664e1dc3cec9b2ab07/Pal/include/arch/x86_64/Linux/ucontext.h#L161)):*
> ```objc
> 
> static inline void pal_ucontext_set_function_parameters(ucontext_t* uc, void* func, size_t count,
>                                                         greg_t func_args[4]) {
> ```

Please change to `greg_t*`. It's the same thing, but since we have a `count` parameter it will look less confusing.


<!-- Sent from Reviewable.io -->

2020-12-10 15:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 0 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/Linux/ucontext.h, line 161 at r3](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOBjj5uBDYOVnFWSGqV:-MOC6kSk3dyVTta8_gGz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5cfcc323c3809d30595460664e1dc3cec9b2ab07/Pal/include/arch/x86_64/Linux/ucontext.h#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change to `greg_t*`. It's the same thing, but since we have a `count` parameter it will look less confusing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-10 16:35 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-12-12 15:52 UTC, stefanberger commented
> @stefanberger Does this change make sense to you? Is it fine for your purposes?

[ I cannot reply via reviewable due to some 3rd party permission problem that oscarlabs has to resolve ]

@dimakuv Are you referring to ppc64 work? I don't see a problem with this.

2020-12-14 19:45 UTC, mkow requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 181 at r4](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOXlpLZ16MbM46MgRdO:-MOXlpLZ16MbM46MgRdP:b-jgobnn) ([raw file](https://github.com/oscarlab/graphene/blob/df51e9722204d31d7e4291fb201e7df78f72cbf2/Pal/src/host/Linux-SGX/sgx_exception.c#L181)):*
> ```
> /*count=*/
> ```

It's not `count` anymore.


<!-- Sent from Reviewable.io -->

2020-12-14 20:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOB1_c3ClWNFWpOx32e:-MOXpa7yCqY27rMcQK1l:bn3mdlt) (no related file):*
> [ I cannot reply via reviewable due to some 3rd party permission problem that oscarlabs has to resolve ]

Should be fixed now, sorry.

@dimakuv FYI (if you missed it): Stefan's response from GitHub: "@dimakuv Are you referring to ppc64 work? I don't see a problem with this.".

---


<!-- Sent from Reviewable.io -->

2020-12-15 07:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 181 at r4](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOXlpLZ16MbM46MgRdO:-MO_Kgzz1nbsqlycGg17:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/df51e9722204d31d7e4291fb201e7df78f72cbf2/Pal/src/host/Linux-SGX/sgx_exception.c#L181)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> /*count=*/
> ```

It's not `count` anymore.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-15 08:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2020#-MO_ZFKI6eZOCRsizMa7:-MO_ZFKI6eZOCRsizMa8:bk1g00t) (no related file):*
Blocking myself. Need to debug this error of `pipe_ocloexec`:
```
Standard Output
pipe_ocloexec: child received an unexpected signal: 11

Standard Error
WARNING: Using insecure argv source. Don't use this configuration in production!
Accessing file:../../../../Runtime/ld-linux-x86-64.so.2 is denied (Operation interrupted). This file is not trusted or allowed. Trusted files should be regular files (seekable).
```

Looks like the child process got interrupted by some signal during startup, when the child is still reading startup files.

---


<!-- Sent from Reviewable.io -->

2020-12-15 13:14 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2020-12-15 15:02 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2020-12-15 15:27 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2020-12-15 15:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 2 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2020#-MO_ZFKI6eZOCRsizMa7:-MOb2NnV72W4Telq9-pb:b-9u1yfi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking myself. Need to debug this error of `pipe_ocloexec`:
```
Standard Output
pipe_ocloexec: child received an unexpected signal: 11

Standard Error
WARNING: Using insecure argv source. Don't use this configuration in production!
Accessing file:../../../../Runtime/ld-linux-x86-64.so.2 is denied (Operation interrupted). This file is not trusted or allowed. Trusted files should be regular files (seekable).
```

Looks like the child process got interrupted by some signal during startup, when the child is still reading startup files.
</blockquote></details>

Done. Please see the second commit (and file `enclave_ocalls.c`).

---


<!-- Sent from Reviewable.io -->

2020-12-15 15:53 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1454 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOb5hKN7nYe54Ct4J1x:-MOb5hKN7nYe54Ct4J1y:bkary6j) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1454)):*
> ```C
> 
>     do {
>         retval = sgx_exitless_ocall(OCALL_EVENTFD, ms);
> ```

Why don't we allow `EINTR` here?


<!-- Sent from Reviewable.io -->

2020-12-15 16:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1454 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOb5hKN7nYe54Ct4J1x:-MOb7vfQ3gp_CKoKKCp3:bwzkr8c) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1454)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why don't we allow `EINTR` here?
</blockquote></details>

This OCALL issues `INLINE_SYSCALL(eventfd2, 2, ms->ms_initval, ms->ms_flags);`. I don't see any mention of EINTR as a possible return value in `man 2 eventfd2`.

Why would we want to allow `-EINTR` here? It's just a "create an FD of type eventfd" syscall.


<!-- Sent from Reviewable.io -->

2020-12-15 16:45 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1454 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOb5hKN7nYe54Ct4J1x:-MObHb079pZHiuY3TXAN:b1rhzw1) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1454)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This OCALL issues `INLINE_SYSCALL(eventfd2, 2, ms->ms_initval, ms->ms_flags);`. I don't see any mention of EINTR as a possible return value in `man 2 eventfd2`.

Why would we want to allow `-EINTR` here? It's just a "create an FD of type eventfd" syscall.
</blockquote></details>

Yeah, my bad.


<!-- Sent from Reviewable.io -->

2020-12-15 17:13 UTC, mkow requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 326 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObNSHABUzcBnZlsbb8:-MObNSHABUzcBnZlsbb9:bbt17v8) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L326)):*
> ```C
> 
>     /* this open() ocall is used only for files and devices (never to open pipes), so it must never
>      * return -EINTR (which may happen when untrusted PAL receives an async signal from host OS) */
> ```

can we assert this somewhere, or adding it is not easy? looks like an assumption which can be easily broken in the future and go unnoticed in review


<!-- Sent from Reviewable.io -->

2020-12-15 17:37 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 326 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObNSHABUzcBnZlsbb8:-MObR6G79fq8fju7Tvgw:bqv2hlr) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L326)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

can we assert this somewhere, or adding it is not easy? looks like an assumption which can be easily broken in the future and go unnoticed in review
</blockquote></details>

I can't figure out a way how to assert this. There is nothing in the arguments here we can assert on...

Yeah, it's a tricky one. Not sure what we could do here.


<!-- Sent from Reviewable.io -->

2020-12-15 18:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 326 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObNSHABUzcBnZlsbb8:-MObYVfF9VcHatLFWkO_:bu13bpb) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L326)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can't figure out a way how to assert this. There is nothing in the arguments here we can assert on...

Yeah, it's a tricky one. Not sure what we could do here.
</blockquote></details>

I will change the name to `ocall_open_uninterruptible()`. Or even `ocall_open_with_retry()`.


<!-- Sent from Reviewable.io -->

2020-12-15 18:03 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 349 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObVedNAI-H_6-5TTKW:-MObVedNAI-H_6-5TTKX:b3wxnwj) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L349)):*
> ```C
> 
>     do {
>         retval = sgx_exitless_ocall(OCALL_CLOSE, ms);
> ```

close case is subtle. Please don't retry on close case.
For reference, https://lwn.net/Articles/576478/


<!-- Sent from Reviewable.io -->

2020-12-15 18:03 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOB1_c3ClWNFWpOx32e:-MOMcnZa62wjyDqTRUP7:b2464he) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@stefanberger Does this change make sense to you? Is it fine for your purposes?
</blockquote></details>

@dimakuv Are you referring to ppc64 work? I don't see a problem with this (unless you point one out to me).

---


<!-- Sent from Reviewable.io -->

2020-12-16 08:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 2 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOB1_c3ClWNFWpOx32e:-MOed3sb7hhG5c-wKPfe:bvu3k7v) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

@dimakuv Are you referring to ppc64 work? I don't see a problem with this (unless you point one out to me).
</blockquote></details>

Thanks, @stefanberger! Yes, I meant your ppc64 work. Thanks for acking that this PR is ok.

---
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 326 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObNSHABUzcBnZlsbb8:-MOeicuq-nwWQeOeTnQH:b-5rz4d9) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L326)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I will change the name to `ocall_open_uninterruptible()`. Or even `ocall_open_with_retry()`.
</blockquote></details>

Changed to `ocall_open_with_retry()` because we already have a similar name in LibOS (`object_wait_with_retry()`).
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 349 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObVedNAI-H_6-5TTKW:-MOedxgpCAzc4pKnGqyl:b-5ipav6) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L349)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

close case is subtle. Please don't retry on close case.
For reference, https://lwn.net/Articles/576478/

</blockquote></details>

Done. Thanks for info!


<!-- Sent from Reviewable.io -->

2020-12-16 10:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 2 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOf0SY10papp_IE2mq7:-MOf0SY21W6XHEKL5g6Q:be311i3) (no related file):*
Blocking myself: during final rebase, fix typo: `uninterruptable` -> `uninterruptible` in the commit message.

---


<!-- Sent from Reviewable.io -->

2020-12-16 13:23 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 349 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObVedNAI-H_6-5TTKW:-MOfhsDk2GG1-fLhs8xb:b-ap6wjc) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L349)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Thanks for info!
</blockquote></details>

Otoh there is also `EINTR` which gets artificially injected (is *not* returned by actual syscall on host) on which we should retry ...


<!-- Sent from Reviewable.io -->

2020-12-16 13:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 349 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObVedNAI-H_6-5TTKW:-MOfnMObDA2uAxSHcIyG:blhttm3) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L349)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Otoh there is also `EINTR` which gets artificially injected (is *not* returned by actual syscall on host) on which we should retry ...
</blockquote></details>

@boryspoplawski True. But this is a rare case and the current code has an FD leak, whereas retrying (as in my previous version of code) could break Graphene process (?). I still think that we shouldn't retry per Isaku's suggestion.


<!-- Sent from Reviewable.io -->

2020-12-16 14:30 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 349 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObVedNAI-H_6-5TTKW:-MOfvpJnCMTF81h3d6XW:bhpifba) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L349)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski True. But this is a rare case and the current code has an FD leak, whereas retrying (as in my previous version of code) could break Graphene process (?). I still think that we shouldn't retry per Isaku's suggestion.
</blockquote></details>

I guess, you are right, let's leave it as it is.
Some notes:
- I think we should not just inject `EINTR`, but should be able to distinguish interrupted enclave<->untrusted transition from host syscall returning `EINTR`, but that would probably require heavy redesign.
- I also think that `close` returning `EINTR` is much more rare (idk when it could happen, nfs failure or something) than us getting this artificial `EINTR` from Graphene code ...


<!-- Sent from Reviewable.io -->

2020-12-16 14:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 349 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObVedNAI-H_6-5TTKW:-MOfzNgO1n1m2OCRT8Aj:b-coijo1) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L349)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess, you are right, let's leave it as it is.
Some notes:
- I think we should not just inject `EINTR`, but should be able to distinguish interrupted enclave<->untrusted transition from host syscall returning `EINTR`, but that would probably require heavy redesign.
- I also think that `close` returning `EINTR` is much more rare (idk when it could happen, nfs failure or something) than us getting this artificial `EINTR` from Graphene code ...
</blockquote></details>

@boryspoplawski I agree with both your notes. The original idea (or hmmm... wish?) was to "continue/fix the untrusted logic of each OCALL", as documented here: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_exception.c#L178-L179

For example, for the `sgx_ocall_close()`, we would compare interrupted-at-RIP with "RIP-before-host-close-syscall" and "RIP-after-host-close-syscall" and based on the case, either perform the `close()` syscall again or inject `RAX = 0` to kinda "roll RIP forward to good state".

This is quite heavy to implement though...


<!-- Sent from Reviewable.io -->

2020-12-16 17:47 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 349 at r6](https://reviewable.io/reviews/oscarlab/graphene/2020#-MObVedNAI-H_6-5TTKW:-MOgdAT586dMmdbNAndp:b-y4uoh3) ([raw file](https://github.com/oscarlab/graphene/blob/8bc976a1645a63d392fb7f581ffe106f9a0b6e9d/Pal/src/host/Linux-SGX/enclave_ocalls.c#L349)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I agree with both your notes. The original idea (or hmmm... wish?) was to "continue/fix the untrusted logic of each OCALL", as documented here: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_exception.c#L178-L179

For example, for the `sgx_ocall_close()`, we would compare interrupted-at-RIP with "RIP-before-host-close-syscall" and "RIP-after-host-close-syscall" and based on the case, either perform the `close()` syscall again or inject `RAX = 0` to kinda "roll RIP forward to good state".

This is quite heavy to implement though...
</blockquote></details>

I agree that we should able to distingush host system call error code and artificial injection and that it would require redesign. (or even we should stop eintr injection)
For now I unblock this.


<!-- Sent from Reviewable.io -->

2020-12-16 18:38 UTC, mkow requested changes
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 592 at r7](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOgo35U2KdN4XUvLM2g:-MOgo35U2KdN4XUvLM2h:b-sxoqdx) ([raw file](https://github.com/oscarlab/graphene/blob/a4cbf2d30082d0b2f80e75968283f07cfdefca61/Pal/src/host/Linux-SGX/db_files.c#L592)):*
> ```C
>     /* open the file with O_NONBLOCK to avoid blocking the current thread if it is actually a FIFO
>      * pipe; O_NONBLOCK will be reset below if it is a regular file */
>     int fd = ocall_open_with_retry(uri, O_NONBLOCK, /*mode=*/0);
> ```

Umm, this callsites looks now like a bug (see the comment above). The semantic of `ocall_open_with_retry` is really weird now - could you update the comment above and describe the peculiarity?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 325 at r7](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOgoSqn7VHPi1IwHvR9:-MOgoSqn7VHPi1IwHvRA:b-pex77v) ([raw file](https://github.com/oscarlab/graphene/blob/a4cbf2d30082d0b2f80e75968283f07cfdefca61/Pal/src/host/Linux-SGX/enclave_ocalls.c#L325)):*
> ```C
>     WRITE_ONCE(ms->ms_pathname, untrusted_pathname);
> 
>     /* this ocall is used only for files and devices (never to open pipes), so it must never return
> ```

This stands contrary to the callsite I marked above.


<!-- Sent from Reviewable.io -->

2020-12-17 09:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 592 at r7](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOgo35U2KdN4XUvLM2g:-MOjyjbs1idPl1pbZjsv:bkae3op) ([raw file](https://github.com/oscarlab/graphene/blob/a4cbf2d30082d0b2f80e75968283f07cfdefca61/Pal/src/host/Linux-SGX/db_files.c#L592)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Umm, this callsites looks now like a bug (see the comment above). The semantic of `ocall_open_with_retry` is really weird now - could you update the comment above and describe the peculiarity?
</blockquote></details>

Done. Reverted all these callsites. I don't see a particular issue here (EINTR and non-blocking are two orthogonal things), but I can see how the naming became confusing. I reverted to having a "normal" ocall name and explaining the situation in a top-level comment.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 325 at r7](https://reviewable.io/reviews/oscarlab/graphene/2020#-MOgoSqn7VHPi1IwHvR9:-MOjySK16SuVj4o55veJ:b-gwtr2g) ([raw file](https://github.com/oscarlab/graphene/blob/a4cbf2d30082d0b2f80e75968283f07cfdefca61/Pal/src/host/Linux-SGX/enclave_ocalls.c#L325)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This stands contrary to the callsite I marked above.
</blockquote></details>

Done. I reverted the rename `ocall_open_with_retry()` back to `ocall_open()` and removed this comment. Now I have a top-level comment at the beginning of this file explaining the retry logic in these ocalls. This should cover everything and explain the current situation with async signals and EINTR.


<!-- Sent from Reviewable.io -->

2020-12-17 15:25 UTC, boryspoplawski approved these changes
> Reviewed 2 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-12-23 22:19 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-28 10:10 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`writev07` LTP test failed, unrelated since it was not under SGX)

2020-12-28 11:53 UTC, mkow approved these changes
> Reviewed 1 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-28 12:15 UTC, boryspoplawski approved these changes
> Reviewed 1 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2020)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-28 12:20 UTC, merged