SGX profiling based on perf
oscarlab/graphene pull request #2027
Opened 2020-12-15 12:45 UTC by pwmarcz

New version of https://github.com/oscarlab/graphene/pull/2001.

Includes `eh_frame_hdr` fix (#2026, can be merged faster).

## Description of the changes:

This generates a file with samples readable by `perf`. After recording, you can view a report with `perf record`. The samples can include stack: a snapshot of up to 8192 bytes is recorded, and `perf record` will try to walk it based on DWARF info.

Basically, this replaces the kernel part of `perf` for SGX.

![image](https://user-images.githubusercontent.com/468495/102214471-9b0b5000-3ed8-11eb-999e-f1ba73ab40c2.png)

## Alternate approaches I have considered

- **Hand-rolled statistics/report** (as in #2001): I got stuck trying to add stack traces. You can follow frame pointers (`RBP`) quite easily, but that works more or less only in Graphene code, as even glibc is compiled without frame pointers nowadays.

- **Parsing the stack ourselves**: I tried to use `libunwind` (not very flexible) and `libdwfl` (better, but complex), and it worked, but then started crashing on more complicated (and multithreaded) programs, I'm not sure why...

   Anyway, I decided I'm not comfortable introducing a complicated library to outer PAL, and invoking it during AEX. Besides, with `perf` I can lean on existing tool.

- **VTune**: Haven't looked into that, according to @dimakuv it might be a matter of [adding module maps](https://scc.ustc.edu.cn/zlsc/tc4600/intel/2017.0.098/vtune_amplifier_xe/help/GUID-B55461C0-94A2-48DA-A2DA-4B7A6A2976B7.html). Sounds promising, but regardless of that, I think it's good to have perf support because of availability (free software, present in Ubuntu, works in terminal, etc.)

- **Kernel patch for SGX perf**: Might be worth doing someday? I can imagine Linux kernel reporting the samples from enclave. Still, memory maps would have to be reported somehow.

## Limitations

- I can't see symbols from `python3.6` in perf. Oddly, the same happens without Graphene. I might debug this later.
- I'm not 100% sure the mmap reporting is correct, because the ELF linking code is pretty bad. I'd be interested in redoing it soon (CC @mkow).
- Soon LibOS syscalls will use a separate stack (@boryspoplawski is working on that). That means with this approach we will not see the transition between application and LibOS. But I think that can be worked around, by doing basically the same thing `perf` does when showing split stack traces between userland and kernel (record call chain for kernel stack, and dump for user stack).
- JITted languages won't work too well. It might be worth looking into the workarounds for normal perf (there is some support for Java).

## How to test this PR?

1. Compile with `DEBUG=1`
2. `sgx.profile.enable = "main"`, `sgx.profile.with_stack = 1`
3. Run application
4. `perf report -i sgx-perf.data`
5. To view the raw dump: `perf script -Di sgx-perf.data`

2020-12-16 10:08 UTC, dimakuv requested changes
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOenIAg1s59yFtXbcWB:-MOenIAg1s59yFtXbcWC:b-yy8wk2) (no related file):*
Can you add to PR description that it "Closes #2001"?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOenRQt7hC1FmuGVixj:-MOenRQu6hOVvc4-SUZl:brjs9ak) (no related file):*
> I'm not 100% sure the mmap reporting is correct, because the ELF linking code is pretty bad. I'd be interested in redoing it soon (CC @mkow).

Definitely we should do it soon-ish. The bulk of the code was taken from Glibc and hacked around (blindly) to make Graphene work. It stayed in this condition for the last 4-5 years, noone dares to touch it. From what I've seen, Musl ELF code is cleaner, and we may want to borrow some code from there.

---
___
*[Documentation/manifest-syntax.rst, line 501 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOetDIpAH8uA1YGTfWz:-MOetDIpAH8uA1YGTfX-:b-p107z0) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Documentation/manifest-syntax.rst#L501)):*
> ```reStructuredText
> 
> This syntax specifies approximate frequency at which profiling samples are
> taken. Lower values will mean less accurate results, but also lower overhead.
> ```

What are the units of this frequency? What does `50` mean, why 50?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 118 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeqUgj6KMwFH6dhhaV:-MOeqUgj6KMwFH6dhhaW:b-h3cu8t) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L118)):*
> ```C
>             sgx_profile_report_mmap(filename, base + mapstart, mapend - mapstart, mapoff);
>             if (IS_ERR(ret))
>                 return -ERRNO(ret);
> ```

These two lines must be removed
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOerILQB6BNJ9pqFIc9:-MOerILS6RWJUcAPBQo_:bbztp2n) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L594)):*
> ```C
>     if (enclave->profile_enable) {
>         /* Report libpal map before enclave start, so that all profiling samples can be attributed
>          * to it. */
> ```

What does it mean `can be attributed to it`? I understand that we need to report_mmap `libpal.so` because it is not DkDebugAddMap'ed later, but the comment says something more... Isn't it enough to just write `/* Explicitly report libmap map before enclave start because it will not be added via DkDebugAddMap() */`?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 775 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOesX-nEDulSevWOS7f:-MOesX-o5OFrdIzTVvHG:b-tppiyw) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L775)):*
> ```C
> #ifdef DEBUG
>     enclave_info->profile_enable = false;
>     strcpy(enclave_info->profile_filename, "sgx-perf.data");
> ```

I would move this strcpy to under `"main"`. Here I would leave only `enclave_info->profile_filename = NULL;`
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 796 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOesgVD78x13eD34vwR:-MOesgVD78x13eD34vwS:bu1pqyz) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L796)):*
> ```C
>                  "sgx-perf-%d.data", (int)INLINE_SYSCALL(getpid, 0));
>     } else {
>         SGX_DBG(DBG_E, "Invalid \'sgx.profile\' (the value must be \"none', \"main\" or \"all\")\n");
> ```

Typo: `\"none\"` (closing double-quote)
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 814 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOet4_a8E50iONcOOka:-MOet4_a8E50iONcOOkb:b-med0kl) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L814)):*
> ```C
>     ret = toml_int_in(manifest_root, "sgx.profile.frequency", /*defaultval=*/50,
>                       &profile_frequency);
>     if (ret < 0 || (profile_frequency <= 0)) {
> ```

No need for additional parens
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOetmHc4B_jxm7v0WYQ:-MOetmHd-3JeSf4VVqCY:b5if3zy) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L40)):*
> ```C
> #define PROLOGUE_SIZE (sizeof(struct perf_file_header) + sizeof(struct perf_file_attr))
> 
> #define BUF_SIZE (32 * 1024 * 1024)
> ```

32MBs? Why this value?

Ok, now I see that you allocate a 32MB buffer and periodically flush its contents to the file (when the buffer is full). Maybe just add a comment that this buffer is periodically flushed to file and re-filled.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeudPD85RqdE4cmPqi:-MOeudPD85RqdE4cmPqj:bx2wjiq) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L42)):*
> ```C
> #define BUF_SIZE (32 * 1024 * 1024)
> 
> /* Registers to sample - see arch/x86/include/uapi/asm/perf_regs.h */
> ```

The whole file seems to be very x86-64-specific. Could we add `#ifndef __x86_64__  #error "unsupported architecture #endif"` for sanity?
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeuzeNC7BuQl5RsTjy:-MOeuzeNC7BuQl5RsTjz:brn8x2y) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L92)):*
> ```C
>     size_t file_pos;
>     // Assume last buf_pos bytes have not been written yet
>     size_t buf_pos;
> ```

So it's not a "current position in the buffer", right? If it's truly "bytes left in the buffer", maybe rename to `buf_rest` or `buf_left`?

Looking below, it does look like a "position in the buffer", but with a magic `0` value (meaning the buffer is completely flushed)... And why then `last buf_pos bytes` in the comment?
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOevT-hEjJp-asLolU2:-MOevT-hEjJp-asLolU3:biseqfc) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L112)):*
> ```C
> 
> static int pd_flush(struct perf_data* pd) {
>     if (pd->buf_pos == 0)
> ```

Why this magic zero value? It seems that `buf_pos` means "position in the buffer", but then `0` should mean "start of the buffer" in which case everything should be flushed...
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 166 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOewWiM-IQtPh0wka28:-MOewWiM-IQtPh0wka29:b-bktkhj) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L166)):*
> ```C
>     return pd;
> 
> out:
> ```

Could you rename this label to `fail`?
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeyb_04ipXLBHIXhLQ:-MOeyb_04ipXLBHIXhLR:bpxziv6) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_profile.c#L25)):*
> ```C
> 
> // glibc realpath; declared here because the headers will conflict with PAL
> char* realpath(const char* path, char* resolved_path);
> ` [...]

2020-12-16 11:32 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: 18 of 22 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOenIAg1s59yFtXbcWB:-MOf2djG8vD71ZgIFs2a:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add to PR description that it "Closes #2001"?
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOenRQt7hC1FmuGVixj:-MOf2hzc3fQd5zMjvR0G:b-gcokjf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I'm not 100% sure the mmap reporting is correct, because the ELF linking code is pretty bad. I'd be interested in redoing it soon (CC @mkow).

Definitely we should do it soon-ish. The bulk of the code was taken from Glibc and hacked around (blindly) to make Graphene work. It stayed in this condition for the last 4-5 years, noone dares to touch it. From what I've seen, Musl ELF code is cleaner, and we may want to borrow some code from there.
</blockquote></details>

I'll take a look at musl code then. I'm hoping to simplify the whole system, including debug maps and `r_debug`.

---
___
*[Documentation/manifest-syntax.rst, line 501 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOetDIpAH8uA1YGTfWz:-MOf2yQSELBK7lZHsgAm:b5m6r81) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Documentation/manifest-syntax.rst#L501)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What are the units of this frequency? What does `50` mean, why 50?
</blockquote></details>

Samples per second. (I thought that would be less error-prone than specifying period in milli/micro/nanoseconds; also, this is what `perf record` does). Do you think it's enough to say `frequency (in samples per second)` here, or would you rather have `frequency_hz` as name?

As for 50 samples per second, I didn't do any rigorous testing, but it seems to still produce a reasonable file size (8KB stack samples means roughly 25 MB per minute per thread when collecting stack), and the time overhead seemed small when I tested the ~200 thread Tensorflow workload.

I modified the description.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 118 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeqUgj6KMwFH6dhhaV:-MOf4DppA7mdx8ZpMDY0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two lines must be removed
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOerILQB6BNJ9pqFIc9:-MOf58zF3D8yrm8k_FnY:bun8akd) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L594)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does it mean `can be attributed to it`? I understand that we need to report_mmap `libpal.so` because it is not DkDebugAddMap'ed later, but the comment says something more... Isn't it enough to just write `/* Explicitly report libmap map before enclave start because it will not be added via DkDebugAddMap() */`?
</blockquote></details>

It's not reported via `DkDebugAddMap`, but the obvious other place is `setup_pal_map()` which reports libpal to GDB. However, when I added this code to `setup_pal_map()`, it produced a report with a lot of unresolved addresses. This is because some samples are recorded after enclave start, but before I reported the map.

Now that I think of it, the same applies to GDB:  right now it's impossible to add a breakpoint during early enclave start, before `setup_pal_map()`. This is problematic right now because we keep the `g_debug_map` structure inside enclave. I'm planning to move it out.

I added a longer explanation and a TODO here.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 775 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOesX-nEDulSevWOS7f:-MOf70tnEEr9QDIwBUrG:b-2cfgzm) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L775)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would move this strcpy to under `"main"`. Here I would leave only `enclave_info->profile_filename = NULL;`
</blockquote></details>

Done (it's an array, so I set it to empty string).
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 796 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOesgVD78x13eD34vwR:-MOf74sC-arGlVpw1ixz:b-lx4fi1) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L796)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `\"none\"` (closing double-quote)
</blockquote></details>

Fixed.F
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 814 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOet4_a8E50iONcOOka:-MOf78jV3SMW2xM_jQJU:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L814)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for additional parens
</blockquote></details>

Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOetmHc4B_jxm7v0WYQ:-MOf7aMpC8f23PSyX68g:b-f8sf1p) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

32MBs? Why this value?

Ok, now I see that you allocate a 32MB buffer and periodically flush its contents to the file (when the buffer is full). Maybe just add a comment that this buffer is periodically flushed to file and re-filled.
</blockquote></details>

Added a comment.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeudPD85RqdE4cmPqi:-MOf7eC4BwPtnlpE7CNX:bnqdkig) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The whole file seems to be very x86-64-specific. Could we add `#ifndef __x86_64__  #error "unsupported architecture #endif"` for sanity?
</blockquote></details>

SGX is x86-64 specific, right? But I guess this file could be used outside the SGX subsystem someday. I added a check.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeuzeNC7BuQl5RsTjy:-MOf909r9l99DwRhzsVI:b9j5gok) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So it's not a "current position in the buffer", right? If it's truly "bytes left in the buffer", maybe rename to `buf_rest` or `buf_left`?

Looking below, it does look like a "position in the buffer", but with a magic `0` value (meaning the buffer is completely flushed)... And why then `last buf_pos bytes` in the comment?
</blo [...]

2020-12-16 11:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: 18 of 22 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOfJx_i3egzU6sF5k7u:-MOfJx_jEA6j-koaEsEQ:b3piv91) (no related file):*
Another fun thing to try with `perf report`: press `a` to annotate the function disassembly with time spent on exact instructions :)

---


<!-- Sent from Reviewable.io -->

2020-12-16 12:04 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Documentation/manifest-syntax.rst, line 501 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOetDIpAH8uA1YGTfWz:-MOfOe6XAjp9sibtD8SQ:b-o570xd) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Documentation/manifest-syntax.rst#L501)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Samples per second. (I thought that would be less error-prone than specifying period in milli/micro/nanoseconds; also, this is what `perf record` does). Do you think it's enough to say `frequency (in samples per second)` here, or would you rather have `frequency_hz` as name?

As for 50 samples per second, I didn't do any rigorous testing, but it seems to still produce a reasonable file size (8KB stack samples means roughly 25 MB per minute per thread when collecting stack), and the time overhead seemed small when I tested the ~200 thread Tensorflow workload.

I modified the description.
</blockquote></details>

OK. No need to change the name. It looks good now.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOerILQB6BNJ9pqFIc9:-MOfPTs24a5mcnARWCcu:b-m3fpus) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_main.c#L594)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's not reported via `DkDebugAddMap`, but the obvious other place is `setup_pal_map()` which reports libpal to GDB. However, when I added this code to `setup_pal_map()`, it produced a report with a lot of unresolved addresses. This is because some samples are recorded after enclave start, but before I reported the map.

Now that I think of it, the same applies to GDB:  right now it's impossible to add a breakpoint during early enclave start, before `setup_pal_map()`. This is problematic right now because we keep the `g_debug_map` structure inside enclave. I'm planning to move it out.

I added a longer explanation and a TODO here.
</blockquote></details>

OK. Thanks for explanations! I agree that we should move out `g_debug_map` and init everything before jumping into the enclave.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOeudPD85RqdE4cmPqi:-MOfPo6h6VJcP_dwzNjm:buk71pc) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_perf_data.c#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

SGX is x86-64 specific, right? But I guess this file could be used outside the SGX subsystem someday. I added a check.
</blockquote></details>

Thanks. Yes, SGX in Graphene is x86-64-specific. But technically SGX supports 32-bit systems. Also, this file may be used in other places, so it's better to give a hint to others here.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 200 at r1](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOf-YM980AKRj72PGhY:-MOfQgIZDsI7PWvXum_r:b-41dxd3) ([raw file](https://github.com/oscarlab/graphene/blob/880082ee975c08c4163dd1f398a455a55f772e2f/Pal/src/host/Linux-SGX/sgx_profile.c#L200)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's 8KB, not megabytes. Here are our stack sizes (`Linux-SGX/pal_linux_defs.h`):

```
#define THREAD_STACK_SIZE (PRESET_PAGESIZE * 512) /* 2MB untrusted stack */
#define ALT_STACK_SIZE    (PRESET_PAGESIZE * 16)  /* 64KB untrusted signal stack */
#define RPC_STACK_SIZE    (PRESET_PAGESIZE * 2)
```

I think that during AEX we land on the "2MB untrusted stack". Do you think this is good enough, or would it be better not to rely on it and to malloc the 8KB?
</blockquote></details>

Ok. Sorry, I got it wrong. 8KB on the stack is no problem (and yes, the untrusted stack is 2MB, so more than enough). No need to use the heap.


<!-- Sent from Reviewable.io -->

2020-12-17 09:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: 21 of 22 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOk7C4dDoRh4q39051L:-MOk7C4e147Ba3XMtXBh:b-dnqssi) (no related file):*
I added a sanity check that disallows `sgx.profile.enable` (other than none) without DEBUG option.

---


<!-- Sent from Reviewable.io -->

2020-12-17 10:00 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-17 22:44 UTC, boryspoplawski requested changes
> Reviewed 18 of 22 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1384 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlVyfBC18K3qAiu4hO:-MOlVyfBC18K3qAiu4hP:bnz0x9f) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1384)):*
> ```C
> }
> 
> int ocall_report_mmap(const char* filename, uint64_t addr, uint64_t len, uint64_t offset) {
> ```

This function will be called (and do EEXIT) even on non-debug builds, am I right? If so, please wrap it inside `ifdef DEBUG`
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1386 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlUPLv1ObPjclvHkjM:-MOlUPLv1ObPjclvHkjN:b-oczr8a) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1386)):*
> ```C
> int ocall_report_mmap(const char* filename, uint64_t addr, uint64_t len, uint64_t offset) {
>     int retval = 0;
>     int filename_len = filename ? strlen(filename) + 1 : 0;
> ```

Please change type to `size_t`.
___
*[Pal/src/host/Linux-SGX/sgx_entry.S, line 83 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlYbU73gubCaAe4psP:-MOlYbU73gubCaAe4psQ:b-7ku5s8) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_entry.S#L83)):*
> ```
> 	# Align stack (required by System V AMD64 ABI)
> 	movq %rsp, %rbp
> 	andq $~0xF, %rsp
> ```

Here we possibly change `rsp` which is default cfa register, I believe. This seem to work by accident: there are 3 pushes above (`0x18`) and `rsp == 8 mod 0x10` at entry so here `resp == 0x20 == 0 mod 0x10` and this and effectively is a nop.
Afaik the solution would be to add `.cfi_def_cfa_register %rbp` after `movq` and `.cfi_def_cfa_register %rsp` after `restore stack` below.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 97 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbJ7O8VIZYTHhSaeF:-MOlbJ7P-9z8trsKHveC:b-416fjc) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L97)):*
> ```C
> 
>     if (IS_ERR(ret = INLINE_SYSCALL(lseek, 3, fd, 0, SEEK_SET)))
>         return -ERRNO(ret);
> ```

Isn't it just equal to `ret` ?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 102 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbK-H-q-QKaOkv87G:-MOlbK-H-q-QKaOkv87H:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L102)):*
> ```C
>     ret = INLINE_SYSCALL(read, 3, fd, filebuf, FILEBUF_SIZE);
>     if (IS_ERR(ret))
>         return -ERRNO(ret);
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 108 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbgBlEc0oTF2r-QxE:-MOlbgBn97P1sdn9LwJX:b-ggx7d5) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L108)):*
> ```C
> 
>     const ElfW(Ehdr)* header = (void*)filebuf;
>     const ElfW(Phdr)* phdr   = (void*)filebuf + header->e_phoff;
> ```

How are we sure this (and the whole loop below) still fits in `FILEBUF_SIZE` size?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 798 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOleXVuBWEF9Q6lL30I:-MOleXVuBWEF9Q6lL30J:bv4216m) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L798)):*
> ```C
>     } else if (!strcmp(profile_str, "main")) {
>         if (enclave_info->is_first_process) {
>             strcpy(enclave_info->profile_filename, "sgx-perf.data");
> ```

Please either use `snprintf` or add a `static_assert` on string size.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 825 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOletrjBjeGQtLvS8fa:-MOletrjBjeGQtLvS8fb:balb5xa) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L825)):*
> ```C
>     ret = toml_int_in(manifest_root, "sgx.profile.frequency", /*defaultval=*/50,
>                       &profile_frequency);
>     if (ret < 0 || profile_frequency <= 0) {
> ```

I've seen a comment somewhere about max frequency (250?) - if there indeed is a max, please add a check here.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 135 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlhmeRC5UaQsnwMHq0:-MOlhmeRC5UaQsnwMHq1:b19ud6w) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L135)):*
> ```C
>     }
> 
>     assert(pd->buf_count + size < sizeof(pd->buf));
> ```

Shouldn't this be `<=`?
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 146 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlkWY03VtZl1-i7YLP:-MOlkWY195PmXABI2hpw:bb4vunn) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L146)):*
> ```C
>     int fd = INLINE_SYSCALL(open, 3, file_name, O_WRONLY | O_TRUNC | O_CREAT, PERM_rw_r__r__);
>     if (fd < 0) {
>         SGX_DBG(DBG_E, "pd_open: cannot open %s for writing: %d\n", file_name, -fd);
> ```

Why the negation of `fd`? I think rest of the code base prints negative values on error (and tbh I prefer such way).
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlnr9f5amUY7bQ1knv:-MOlnr9f5amUY7bQ1knw:b-11fyl4) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L282)):*
> ```C
>         goto out;
> 
>     int close_ret;
> ```

Wait, how does it even compile? `close_ret` is undefined on `goto` paths ...
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 286 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOmnDqz4YwhGKlrvUc-:-MOlo3I41PE0ntuGy3ca:b-nqnne1) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L286)):*
> ```C
>     close_ret = INLINE_SYSCALL(close, 1, pd->fd);
>     if (close_ret < 0)
>         SGX_DBG(DBG_E, "pd_close: close failed: %d\n", -close_ret);
> ```

ditto (negation)
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOmoBhS1uBFgZ9C71yN:-MOmoBhS1uBFgZ9C71yO:b6ujrb5) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_profile.c#L29)):*
> ```C
> #define NSEC_IN_SEC 1000000000
> 
> static spinlock_t g_perf_data_lock = INIT_SPINLOCK_UNLOCKED;
> ```

Why spinlocks? In untrusted part (where we don't have to exit enclave) normal locks (with sleeping) are much better.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOmlBUo2zl0N-kFZUbo:-MOmlBUp6uUtxhEmeelY:b4738tc) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_profile.c#L36)):*
> ```C
> static int g_mem_fd = -1;
> 
> /* Read memory from inside enclave (using /proc/self/mem). */
> ```

How does it work? How can we read enclave memory from outside?
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 50 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOmki6I2FkpIRUqU8Mc:-MOmki6K4fdfrC72QBVC:b-arzrdr) ([raw fil [...]

2020-12-18 11:56 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: 16 of 22 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1384 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlVyfBC18K3qAiu4hO:-MOpCB-C62zeDsiwtT0L:b-48aylx) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1384)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This function will be called (and do EEXIT) even on non-debug builds, am I right? If so, please wrap it inside `ifdef DEBUG`
</blockquote></details>

It will not. The caller is `_DkDebugAddMap`, which is called only when compiled with `DEBUG`. The same applies to `ocall_update_debugger` above.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 1386 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlUPLv1ObPjclvHkjM:-MOpCVhc0Ifo6MRnpgOr:b-gjhc7o) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1386)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change type to `size_t`.
</blockquote></details>

Fixed (also in `ocall_open` etc.)
___
*[Pal/src/host/Linux-SGX/sgx_entry.S, line 83 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlYbU73gubCaAe4psP:-MOpEaaR-y2zXPYuLgGl:bv64r46) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_entry.S#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Here we possibly change `rsp` which is default cfa register, I believe. This seem to work by accident: there are 3 pushes above (`0x18`) and `rsp == 8 mod 0x10` at entry so here `resp == 0x20 == 0 mod 0x10` and this and effectively is a nop.
Afaik the solution would be to add `.cfi_def_cfa_register %rbp` after `movq` and `.cfi_def_cfa_register %rsp` after `restore stack` below.
</blockquote></details>

Makes sense. Done.

Actually this does not help either because there is no more stack after `async_exit_pointer`; by design we don't know where we came from. GDB tries to go further and says the next function is `0x0000000000000000 in ??`. I added a `.cfi_undefined %rip` to signify this is the first frame (as glibc start.S does).
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 97 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbJ7O8VIZYTHhSaeF:-MOpM_HT0fEj6aHlSoFI:botfyhn) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L97)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't it just equal to `ret` ?
</blockquote></details>

Yes it is, I agree this is too convoluted. Removed all the `return -ERRNO(...)` from this file.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 102 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbK-H-q-QKaOkv87G:-MOpdlW29UbtGsgqgS_4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L102)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 108 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbgBlEc0oTF2r-QxE:-MOpNFhBAc81loNq8gvd:b2rch9y) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L108)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How are we sure this (and the whole loop below) still fits in `FILEBUF_SIZE` size?
</blockquote></details>

Yeah, I think the ELF format allows the offset to be anywhere. But the same applies to `scan_enclave_binary` just above.

I've started looking into rewriting the ELF code, but I don't think it's worth it to try and fix this locally right now.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 798 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOleXVuBWEF9Q6lL30I:-MOpOCmkA6r1Juz5lsQ-:b-1t2kvm) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L798)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please either use `snprintf` or add a `static_assert` on string size.
</blockquote></details>

Changed to `snprintf`.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 825 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOletrjBjeGQtLvS8fa:-MOpOwbD3_Mkq70D6q2D:bsr2tld) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L825)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've seen a comment somewhere about max frequency (250?) - if there indeed is a max, please add a check here.
</blockquote></details>

Done. I also moved out the constants here (frequency and filenames) to `sgx_internal.h`.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 135 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlhmeRC5UaQsnwMHq0:-MOpPhJ332vh0ZL2qG8z:bidrs83) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L135)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `<=`?
</blockquote></details>

Right. Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 146 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlkWY03VtZl1-i7YLP:-MOpPxPH3vNDNtTtTXKT:bojs4s8) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L146)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why the negation of `fd`? I think rest of the code base prints negative values on error (and tbh I prefer such way).
</blockquote></details>

But from a quick grep for `SGX_DBG()`, it's pretty much 50-50 :)

I agree printing the code directly is better. Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlnr9f5amUY7bQ1knv:-MOpQMfq2FDCdoCHtCS4:b-qg4bsu) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L282)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, how does it even compile? `close_ret` is undefined on `goto` paths ...
</blockquote></details>

AFAIK it's valid for a goto to jump past a declaration (except variable-length arrays). I got there because this is a compilation error:

```
out:
    int close_ret = INLINE_SYSCALL(...);
```

It fails with `error: a label can only be part of a statement and a declaration is not a statement`.

Anyway, I moved the declaration `close_ret` to the beginning of the function - even if it's allowed, it's confusing.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 286 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOmnDqz4YwhGKlrvUc-:-MOpQJfO9cf0GVk5AO0c:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L286)):*
<details><summary><i>Previously, borysp [...]

2020-12-18 13:30 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOmlBUo2zl0N-kFZUbo:-MOq13-b3gjibua-tvLq:b-6x2im4) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_profile.c#L36)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Same as the GDB integration: this is handled by the SGX driver and uses  the `EDBGRD`  instruction internally (but `EDBGRD` works on addresses in EPC, not the program address space, so it's not easy/not possible? to use directly).
</blockquote></details>

`EDBGRD` is a kernel-mode instruction (more specifically, a leaf of kernel-mode-only `ENCLS`). Can't be used in user-space.


<!-- Sent from Reviewable.io -->

2020-12-18 15:22 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 108 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbgBlEc0oTF2r-QxE:-MOqOuol7GgJE1_mhjl0:b-6c81t9) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L108)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, I think the ELF format allows the offset to be anywhere. But the same applies to `scan_enclave_binary` just above.

I've started looking into rewriting the ELF code, but I don't think it's worth it to try and fix this locally right now.
</blockquote></details>

Ok, but please leave a comment here.
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 825 at r4](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOqPAg72gDINWWkAY_6:-MOqPAg72gDINWWkAY_7:bipvwur) ([raw file](https://github.com/oscarlab/graphene/blob/b6bbcf98a9efc1e051044e8070dd5e6777578271/Pal/src/host/Linux-SGX/sgx_main.c#L825)):*
> ```C
>     int64_t profile_frequency;
>     ret = toml_int_in(manifest_root, "sgx.profile.frequency",
>                       /*defaultval=*/SGX_PROFILE_DEFAULT_FREQUENCY,
> ```

Nitpick: I think comment with arg name is superfluous in this case (it's only useful when arg is a numeric constant which meaning we cannot infer).
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlnr9f5amUY7bQ1knv:-MOqPzQ45_JLXLtt0re0:b-qgbmjf) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_perf_data.c#L282)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

AFAIK it's valid for a goto to jump past a declaration (except variable-length arrays). I got there because this is a compilation error:

```
out:
    int close_ret = INLINE_SYSCALL(...);
```

It fails with `error: a label can only be part of a statement and a declaration is not a statement`.

Anyway, I moved the declaration `close_ret` to the beginning of the function - even if it's allowed, it's confusing.
</blockquote></details>

The other solution is to add a empty statement: `out: ;` (but I'm fine with this solution)
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOmoBhS1uBFgZ9C71yN:-MOqQGzp2pN5ZV3Rh7_k:bkcoax6) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_profile.c#L29)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

As far as I can tell, we use spinlocks everywhere in outer PAL (`sgx_*`), and we don't have any other lock available. Except for one place in `rpc_thread_loop` where we manually implement a futex-based lock.

Should I do the same here? Create a `sgx_lock.h` perhaps?
</blockquote></details>

Maybe, but not in this PR. (resolving)
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 139 at r4](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOqQxIy2jPoBS4aEaHy:-MOqQxIz0GYnjbniAI76:b-3g3ver) ([raw file](https://github.com/oscarlab/graphene/blob/b6bbcf98a9efc1e051044e8070dd5e6777578271/Pal/src/host/Linux-SGX/sgx_profile.c#L139)):*
> ```C
>         ssize_t close_ret = pd_close(g_perf_data);
>         if (IS_ERR(close_ret))
>             SGX_DBG(DBG_E, "sgx_profile_init: pd_close failed: %d\n", (int)close_ret);
> ```

Uhm, not like it's a big deal, but why not `%ld` and do not cast?
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 156 at r4](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOqR1wpDs4cYtsblbz1:-MOqR1wpDs4cYtsblbz2:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b6bbcf98a9efc1e051044e8070dd5e6777578271/Pal/src/host/Linux-SGX/sgx_profile.c#L156)):*
> ```C
>     size = pd_close(g_perf_data);
>     if (IS_ERR(size))
>         SGX_DBG(DBG_E, "sgx_profile_finish: pd_close failed: %d\n", (int)size);
> ```

ditto


<!-- Sent from Reviewable.io -->

2020-12-18 16:47 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: 20 of 22 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 108 at r3](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOlbgBlEc0oTF2r-QxE:-MOqhsDWDIPJeI6ER_qN:bdb4c0j) ([raw file](https://github.com/oscarlab/graphene/blob/5eff81d262e01a971ce148c18552c84e8c2ef4c1/Pal/src/host/Linux-SGX/sgx_main.c#L108)):*
Done.

Haha, I found [where this is from](https://code.woboq.org/userspace/glibc/elf/dl-load.c.html#34):

>... Add to this a bit of margin for program notes and reading 512B and 832B for 32-bit and 64-bit files respecitvely is enough.  If thiss heuristic should really fail for some file the code in`_dl_map_object_from_fd' knows how to recover. 
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 825 at r4](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOqPAg72gDINWWkAY_6:-MOqiA5B9dZFt3kd4YH2:bxwmib) ([raw file](https://github.com/oscarlab/graphene/blob/b6bbcf98a9efc1e051044e8070dd5e6777578271/Pal/src/host/Linux-SGX/sgx_main.c#L825)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: I think comment with arg name is superfluous in this case (it's only useful when arg is a numeric constant which meaning we cannot infer).
</blockquote></details>

Makes sense. Updated.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 139 at r4](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOqQxIy2jPoBS4aEaHy:-MOqiG7e3qQLO9UW0nhN:b-m7wxwt) ([raw file](https://github.com/oscarlab/graphene/blob/b6bbcf98a9efc1e051044e8070dd5e6777578271/Pal/src/host/Linux-SGX/sgx_profile.c#L139)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Uhm, not like it's a big deal, but why not `%ld` and do not cast?
</blockquote></details>

Yes, that's better. Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 156 at r4](https://reviewable.io/reviews/oscarlab/graphene/2027#-MOqR1wpDs4cYtsblbz1:-MOqimaP8T61MHTFYAmf:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/b6bbcf98a9efc1e051044e8070dd5e6777578271/Pal/src/host/Linux-SGX/sgx_profile.c#L156)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2020-12-21 17:17 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-21 19:09 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-12-22 13:30 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-12-22 14:12 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2027)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-22 14:31 UTC, merged