[LibOS] Save/restore FP/SSE/AVX/... control words on syscalls
oscarlab/graphene pull request #2036
Opened 2020-12-21 12:59 UTC by dimakuv

## Description of the changes 

Previously, Graphene saved and restored only the GP registers of the CPU context on entering and leaving syscall emulation in `syscalldb()`. In reality, the CPU context must also contain FP control word (fpcw) and the SSE/AVX/... control word (mxcsr). This commit preserves these control words across app-to-Graphene context switches.

During syscall emulation, Graphene may clobber the FP/SSE/AVX/... state (except the control words). We rely on the fact that apps do *not* assume that this state is preserved across syscalls (except the control words). Thus, it is enough to save/restore only the control words on each syscall. This commit also removes previous hack of performing expensive xsave/xrstor instructions on `clone()`.

Note the performance regression: we add 4 instructions on each syscall (`fnstcw`, `stmxcsr`, `fldcw`, `ldmxcsr`). According to Agner Fog's instruction tables, each of these instructions has latency of about 5 cycles. So there is a total penalty of ~20 cycles, which sounds very reasonable.

**Why not save the whole extended state (xstate)?**

Answer: This is very expensive. We would perform `fxsave/xsave` and then `fxrstor/xrstor` on each syscall. The latency of each of these instructions is 100-300 cycles, so that would add up to 500-1200 cycles. Moreover, sane applications must not assume that FP/SSE/AVX registers are preserved across system calls -- even though the syscall ABI never explicitly mandates this, it is written in the System V ABI, and there are some discussions in the LKML: http://lkml.iu.edu/hypermail/linux/kernel/1107.3/00124.html.

Therefore, it seems reasonable to allow Graphene internal code (LibOS and PALs) to use FP/vector instructions as they please and only preserve the control words for applications on top.

For more info, see https://github.com/oscarlab/graphene/pull/301.

For some info on how Linux kernel works with FP, see https://www.halolinux.us/kernel-reference/process-switch.html.

For System-V ABI, see https://uclibc.org/docs/psABI-x86_64.pdf (especially Figure 3.4. Register Usage).

Closes #301.

## How to test this PR? 

All tests must pass. We have `fp_multithread` that tests exactly this already, so this test must pass.

2020-12-21 14:01 UTC, dimakuv commented
Jenkins, retest Jenkins please (`sendfile08` LTP test timed out)

2020-12-22 16:13 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2036)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2020-12-22 17:36 UTC, mkow requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2036)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/syscallas-x86_64.S, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2036#-MPATuIy4L8WAbqolgdZ:-MPATuIzBzuu1wonb0EV:b2amlax) ([raw file](https://github.com/oscarlab/graphene/blob/252b43f41e35e050e76edc960faabfd371d9e968/LibOS/shim/src/syscallas-x86_64.S#L11)):*
> ```
>  * thread on the thread's stack, then calls the corresponding LibOS syscall-emulation function, and
>  * then restores the context and passes control back to the application. The context consists of
>  * GPRs and FP control word (fpcw) and the SSE/AVX/... control word (mxcsr).
> ```

`GPRs and FP` -> `GPRs, FP`


<!-- Sent from Reviewable.io -->

2020-12-22 19:16 UTC, yamahata approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2036)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_tcb.h, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2036#-MPAsCgY7_ftOMzHeHHC:-MPAsCgY7_ftOMzHeHHD:b2z230e) ([raw file](https://github.com/oscarlab/graphene/blob/252b43f41e35e050e76edc960faabfd371d9e968/LibOS/shim/include/shim_tcb.h#L15)):*
> ```
>     uint16_t          fpcw;    /* FPU Control Word (for x87) */
>     uint32_t          mxcsr;   /* MXCSR control/status register (for SSE/AVX/...) */
>     uint64_t          fs_base;
> ```
nitpick: reorder for alignment. (64 -> 32 -> 16)
___
*[LibOS/shim/src/shim_context-x86_64.c, line 155 at r1](https://reviewable.io/reviews/oscarlab/graphene/2036#-MPArhjH90HI2cAc4g_l:-MPArhjH90HI2cAc4g_m:b-8m610s) ([raw file](https://github.com/oscarlab/graphene/blob/252b43f41e35e050e76edc960faabfd371d9e968/LibOS/shim/src/shim_context-x86_64.c#L155)):*
> ```
>     __asm__ volatile("fldcw (%0)\r\n"
>                      "ldmxcsr (%1)\r\n"
>                      :: "g"(&context->fpcw), "g"(&context->mxcsr) : "memory");
> ```

Can this be merged into the following inline asm?
Just to be safe to prevent gcc from doing insane. (Maybe I'm paranoid. so making this as non-blocking.)


<!-- Sent from Reviewable.io -->

2020-12-22 22:06 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2036)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/include/shim_tcb.h, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2036#-MPAsCgY7_ftOMzHeHHC:-MPBSdHm4Ctoz2k3Q3V_:b-2061vp) ([raw file](https://github.com/oscarlab/graphene/blob/252b43f41e35e050e76edc960faabfd371d9e968/LibOS/shim/include/shim_tcb.h#L15)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>     uint16_t          fpcw;    /* FPU Control Word (for x87) */
>     uint32_t          mxcsr;   /* MXCSR control/status register (for SSE/AVX/...) */
>     uint64_t          fs_base;
> ```
nitpick: reorder for alignment. (64 -> 32 -> 16)
</blockquote></details>

Hmm, I don't think it changes anything? Both orderings result in the same amount of pad bytes and the current ordering (looking at the variables meanings) looks more intuitive (fpu -> sse).
___
*[LibOS/shim/src/shim_context-x86_64.c, line 155 at r1](https://reviewable.io/reviews/oscarlab/graphene/2036#-MPArhjH90HI2cAc4g_l:-MPBTKACCiCsqPUjqcpJ:b-kxuahk) ([raw file](https://github.com/oscarlab/graphene/blob/252b43f41e35e050e76edc960faabfd371d9e968/LibOS/shim/src/shim_context-x86_64.c#L155)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>     __asm__ volatile("fldcw (%0)\r\n"
>                      "ldmxcsr (%1)\r\n"
>                      :: "g"(&context->fpcw), "g"(&context->mxcsr) : "memory");
> ```

Can this be merged into the following inline asm?
Just to be safe to prevent gcc from doing insane. (Maybe I'm paranoid. so making this as non-blocking.)
</blockquote></details>

@dimakuv: FYI: I fixed this when rebasing.
___
*[LibOS/shim/src/syscallas-x86_64.S, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2036#-MPATuIy4L8WAbqolgdZ:-MPBSW8XA8fNW59BGWHl:b-wo15nc) ([raw file](https://github.com/oscarlab/graphene/blob/252b43f41e35e050e76edc960faabfd371d9e968/LibOS/shim/src/syscallas-x86_64.S#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`GPRs and FP` -> `GPRs, FP`
</blockquote></details>

@dimakuv: I fixed this when rebasing.


<!-- Sent from Reviewable.io -->

2020-12-22 22:08 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2036)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-23 01:29 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2036)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-12-23 01:33 UTC, merged