[LibOS,Pal] Use GCC's stack protector in LibOS and PAL functions
oscarlab/graphene pull request #2038
Opened 2020-12-22 13:23 UTC by dimakuv

## Description of the changes 

GCC (and other compilers, e.g. Clang) provide a **stack protector** feature to detect stack corruptions. This is achieved by storing a 64-bit canary value on the stack frame on function entry and verifying this value on function exit.

Previously, Graphene disabled stack protector completely. This PR enables it in LibOS and PAL code (only if `-mstack-protector` feature is supported by compiler).

The stack protector uses a random per-thread canary stored in the TLS/TCB of each thread. Each PAL implementation must follow the rule that TLS/TCB is accessed via the GS register and that the offset of canary in TLS/TCB is 0x8. Since LibOS re-uses TLS/TCB of the PAL, there is no need for additional enabling at the LibOS layer.

Since `-mstack-protector` feature is architecture-specific, it is currently enabled only for x86-64.

Co-authored-by: Isaku Yamahata <isaku.yamahata@gmail.com>

Recreation (and simplification) of #774. Closes #774.

Useful links:
- https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html (see `no_stack_protector`)
- https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html (see `-fstack-protector`)
- https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html#x86-Options (see `-mstack-protector-guard`)
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=29838
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94722
- https://embeddedartistry.com/blog/2020/05/18/implementing-stack-smashing-protection-for-microcontrollers-and-embedded-artistrys-libc/

## How to test this PR? 

All tests must pass. You can manually verify that LibOS and PAL binaries now have stack checks:
```
cd graphene/Runtime
objdump -D libsysdb.so | grep __stack_chk_fail
objdump -D pal-Linux | grep __stack_chk_fail
objdump -D libpal-Linux-SGX.so | grep __stack_chk_fail

# as a bonus, verify that the untrusted part of Linux-SGX PAL doesn't have stack protector
objdump -D pal-Linux-SGX | grep __stack_chk_fail
```

2020-12-22 15:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 0 of 19 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2038#-MP9xUTL3thq25uozx9t:-MP9xUTL3thq25uozx9u:b-3823in) (no related file):*
BTW, I observed about 1-2% throughput overhead on the worst-case Redis benchmark with enabled Stack Protector in Graphene.

At the same time, I observed *no* noticeable increase in binary sizes (recall that Stack Protector adds a couple instructions in each function prologue and epilogue).

---


<!-- Sent from Reviewable.io -->

2020-12-22 19:08 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 0 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2038#-MP9xUTL3thq25uozx9t:-MPAq_zGERphlZDrGo87:b62mkeb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, I observed about 1-2% throughput overhead on the worst-case Redis benchmark with enabled Stack Protector in Graphene.

At the same time, I observed *no* noticeable increase in binary sizes (recall that Stack Protector adds a couple instructions in each function prologue and epilogue).
</blockquote></details>

Great! now the patch is much simpler.

---
___
*[Pal/src/host/Linux/db_main.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPAiv6e-T1lRF8j1yYa:-MPAiv6f-c7-eAZyVnR7:b-9caj4z) ([raw file](https://github.com/oscarlab/graphene/blob/d6561d404234f8a8d629182c3150f885915676a3/Pal/src/host/Linux/db_main.c#L165)):*
> ```C
>     dummy_tcb_for_stack_protector.common.self = &dummy_tcb_for_stack_protector.common;
>     dummy_tcb_for_stack_protector.common.stack_protector_canary = STACK_PROTECTOR_CANARY_DEFAULT;
>     ret = pal_set_tcb(&dummy_tcb_for_stack_protector.common);
> ```

Pranoid: Add -fno-stack-protector to pal_set_tcb().
I think usually gcc inlines the function and it doesn't matter. But no guarantee for gcc to do that.
___
*[Pal/src/host/Linux/db_threading.c, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPAjJrtCM1rrFEzwlkS:-MPAjJrtCM1rrFEzwlkT:buuw2j5) ([raw file](https://github.com/oscarlab/graphene/blob/d6561d404234f8a8d629182c3150f885915676a3/Pal/src/host/Linux/db_threading.c#L91)):*
> ```C
>     /* each newly-created thread (including the first thread) has its own random stack canary */
>     tcb->common.stack_protector_canary = STACK_PROTECTOR_CANARY_DEFAULT;
>     _DkRandomBitsRead(&tcb->common.stack_protector_canary,
> ```

_DkRandomBitsRead() is compiled with stack protector and here %gs has parent's value.
So
- initialize the value by thread parent or
- or no-stack-protector version of _DkRandomBitsRead().

On the other hand, Pal/Linux-SGX case, %gsbase is known value on enclave entry.
___
*[Pal/src/host/Linux/db_threading.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPAjt578G8VFV1Jz2vw:-MPAjt578G8VFV1Jz2vx:b-lfod3j) ([raw file](https://github.com/oscarlab/graphene/blob/d6561d404234f8a8d629182c3150f885915676a3/Pal/src/host/Linux/db_threading.c#L94)):*
> ```C
>                       sizeof(tcb->common.stack_protector_canary));
> 
>     ret = pal_set_tcb(&tcb->common);
> ```

Pranoid: no-stack-protector to pal_set_tcb()


<!-- Sent from Reviewable.io -->

2020-12-23 10:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 0 of 20 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPE4LnH5jugWuOSmTaL:-MPE4LnH5jugWuOSmTaM:b-x7n8ps) (no related file):*
A question to reviewers: in this PR, I'm using the `-fstack-protector-strong` variant of the Stack Protector. This variant enables rather strong checks, see comparison e.g. here: https://www.keil.com/support/man/docs/armclang_ref/armclang_ref_cjh1548250046139.htm. This is used at least by Google ChromiumOS, and they claim it's the best performance-security option.

So, should we also use this `strong` version? We could also go for `-fstack-protector` but this looks quite useless and for `-fstack-protector-all` which seems to be an overkill.

---
___
*[Pal/lib/Makefile, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPE5daP5GHNffO9bdGn:-MPE5daP5GHNffO9bdGo:b-ln2n9q) ([raw file](https://github.com/oscarlab/graphene/blob/d6561d404234f8a8d629182c3150f885915676a3/Pal/lib/Makefile#L8)):*
> ```Makefile
> #        different libraries/executables including those that do not provide __stack_chk_fail(),
> #        e.g. PAL regression tests (in particular, avl_tree_test.c)
> CFLAGS += -fno-stack-protector
> ```

BTW, after we move to Meson and away from Makefiles, I definitely want to:
- revisit the way we detect compiler options (right now we basically append these options, and sometimes we use the trick of multiple compiler options overriding each other, depending on their order in the command line)
- move our "common library" from `/Pal/lib` to outside of PAL, maybe to its own directory `/Common`.
___
*[Pal/src/host/Linux/db_main.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPAiv6e-T1lRF8j1yYa:-MPE6aP69rMTyaQc0QGt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d6561d404234f8a8d629182c3150f885915676a3/Pal/src/host/Linux/db_main.c#L165)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Pranoid: Add -fno-stack-protector to pal_set_tcb().
I think usually gcc inlines the function and it doesn't matter. But no guarantee for gcc to do that.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_threading.c, line 91 at r1](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPAjJrtCM1rrFEzwlkS:-MPE8ljr0XbayjebAE0U:b-eh5156) ([raw file](https://github.com/oscarlab/graphene/blob/d6561d404234f8a8d629182c3150f885915676a3/Pal/src/host/Linux/db_threading.c#L91)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

_DkRandomBitsRead() is compiled with stack protector and here %gs has parent's value.
So
- initialize the value by thread parent or
- or no-stack-protector version of _DkRandomBitsRead().

On the other hand, Pal/Linux-SGX case, %gsbase is known value on enclave entry.

</blockquote></details>

Done. Similarly to the case of the main thread, I now install a dummy TCB.

As you correctly mentioned, we already have a `gsbase` value set in the Linux-SGX case, so nothing to be done there.
___
*[Pal/src/host/Linux/db_threading.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPAjt578G8VFV1Jz2vw:-MPE6en03SDZkYfwa8Ta:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d6561d404234f8a8d629182c3150f885915676a3/Pal/src/host/Linux/db_threading.c#L94)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Pranoid: no-stack-protector to pal_set_tcb()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-31 21:10 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 0 of 20 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPucgQH5Dj02ED7DphI:-MPucgQH5Dj02ED7DphJ:b-mi56g5) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L100)):*
> ```C
> 
>     /* each newly-created thread (including the first thread) has its own random stack canary */
>     tcb->common.stack_protector_canary = STACK_PROTECTOR_CANARY_DEFAULT;
> ```

You should be able to remove the above line. It's overwritten immediately after.


<!-- Sent from Reviewable.io -->

2020-12-31 21:18 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 0 of 20 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPud1pO6J_K9HJ5jiF8:-MPud1pO6J_K9HJ5jiF9:blpdh2i) (no related file):*
Great stuff! I am looking forward to (trying to) enable this on ppc64 as well. It should be possible to enable this on the PAL layer independently of the LibOS layer since we are setting the canary really early... We only have one TLS pointer on ppc64 (I think x86_64 has 2 wit %fs and %gs), so trying to think what must not happen to cause failures. glibc seems to set its own stack protector and I suppose it will never unroll the stack and run into the canary set by either PAL or LibOS and error because of that then... I guess it's going to be a matter of trying.

---


<!-- Sent from Reviewable.io -->

2020-12-31 21:27 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 0 of 20 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPugH925G54l5-Usors:-MPugH925G54l5-Usort:bc7fx9l) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L94)):*
> ```C
>     static PAL_TCB_LINUX dummy_tcb_for_stack_protector = { 0 };
>     dummy_tcb_for_stack_protector.common.self = &dummy_tcb_for_stack_protector.common;
>     dummy_tcb_for_stack_protector.common.stack_protector_canary = STACK_PROTECTOR_CANARY_DEFAULT;
> ```

I think we will need an architecture-specific function to initialize the PAL_TCB_LINUX.


<!-- Sent from Reviewable.io -->

2020-12-31 21:51 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 0 of 20 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[Pal/src/host/Linux/db_threading.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPugH925G54l5-Usors:-MPujnsk-Tqu_6b9Zo0C:bx1e43c) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L94)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I think we will need an architecture-specific function to initialize the PAL_TCB_LINUX.
</blockquote></details>

For PPC64 we will need to change pal_tcb_linux so we can have the canary  at the right location:

```
typedef struct pal_tcb_linux {
    PAL_TCB common;
    struct {
        /* private to Linux PAL */
        int        pending_events[MAX_SIGNAL_LOG];
        int        pending_events_num;
        PAL_HANDLE handle;
        void*      alt_stack;
        int        (*callback)(void*);
        void*      param;
    };
    PAL_TCB_ARCH_TRAILER trailer;   <---- for PPC64
} PAL_TCB_LINUX;


typedef struct pal_tcb_arch_trailer {
    uintptr_t stack_protector_canary; // must be previous to last in TCB
    void *dtv; // must be last in TCB
} PAL_TCB_ARCH_TRAILER;
```

On ppc64 the stack_protector_canary must be the 2nd to last field in the thread control block with the last field being a pointer.

see also: http://openpowerfoundation.org/wp-content/uploads/resources/leabi/content/dbdoclet.50655241_50444.html


<!-- Sent from Reviewable.io -->

2020-12-31 21:57 UTC, stefanberger reviewed
> Reviewed 17 of 19 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 19 of 20 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)



<!-- Sent from Reviewable.io -->

2020-12-31 21:57 UTC, stefanberger reviewed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)



<!-- Sent from Reviewable.io -->

2021-01-01 04:26 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-01-01 04:26 UTC, yamahata submitted a review, later dismissed
> Reviewed 17 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-01-04 08:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPud1pO6J_K9HJ5jiF8:-MQBSr5W3j5QMWmnOtVa:b-yy4j1g) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Great stuff! I am looking forward to (trying to) enable this on ppc64 as well. It should be possible to enable this on the PAL layer independently of the LibOS layer since we are setting the canary really early... We only have one TLS pointer on ppc64 (I think x86_64 has 2 wit %fs and %gs), so trying to think what must not happen to cause failures. glibc seems to set its own stack protector and I suppose it will never unroll the stack and run into the canary set by either PAL or LibOS and error because of that then... I guess it's going to be a matter of trying.
</blockquote></details>

I guess this is thinking aloud, right? :) Or is there any action I need to do on this PR?

In Graphene, we download and build Glibc *without* stack protector: https://github.com/oscarlab/graphene/blob/master/LibOS/Makefile#L48. Not sure if this is what you meant in your comment.

---
___
*[Pal/src/host/Linux/db_threading.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPugH925G54l5-Usors:-MQBRfE329vMnW0sbwi5:bmtz3fd) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L94)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

For PPC64 we will need to change pal_tcb_linux so we can have the canary  at the right location:

```
typedef struct pal_tcb_linux {
    PAL_TCB common;
    struct {
        /* private to Linux PAL */
        int        pending_events[MAX_SIGNAL_LOG];
        int        pending_events_num;
        PAL_HANDLE handle;
        void*      alt_stack;
        int        (*callback)(void*);
        void*      param;
    };
    PAL_TCB_ARCH_TRAILER trailer;   <---- for PPC64
} PAL_TCB_LINUX;


typedef struct pal_tcb_arch_trailer {
    uintptr_t stack_protector_canary; // must be previous to last in TCB
    void *dtv; // must be last in TCB
} PAL_TCB_ARCH_TRAILER;
```

On ppc64 the stack_protector_canary must be the 2nd to last field in the thread control block with the last field being a pointer.

see also: http://openpowerfoundation.org/wp-content/uploads/resources/leabi/content/dbdoclet.50655241_50444.html
</blockquote></details>

I can create an arch-specific new function `pal_set_tcb_stack_canary()`, would that work?

But I don't want to move `PAL_TCB::stack_protector_canary` from its offset `0x8` in the `PAL_TCB` struct. Would it be fine with you? You'll then have an unused x86-specific field in the common TCB...
___
*[Pal/src/host/Linux/db_threading.c, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPucgQH5Dj02ED7DphI:-MQBRd9c7Y6mScXP0xBl:bhy9ot6) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L100)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

You should be able to remove the above line. It's overwritten immediately after.
</blockquote></details>

Will do.


<!-- Sent from Reviewable.io -->

2021-01-05 18:40 UTC, mkow requested changes
> Reviewed 17 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 27 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPE4LnH5jugWuOSmTaL:-MQIciXrBRV4aqNJewqj:bnkc7df) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A question to reviewers: in this PR, I'm using the `-fstack-protector-strong` variant of the Stack Protector. This variant enables rather strong checks, see comparison e.g. here: https://www.keil.com/support/man/docs/armclang_ref/armclang_ref_cjh1548250046139.htm. This is used at least by Google ChromiumOS, and they claim it's the best performance-security option.

So, should we also use this `strong` version? We could also go for `-fstack-protector` but this looks quite useless and for `-fstack-protector-all` which seems to be an overkill.
</blockquote></details>

`-fstack-protector-strong` sounds like a good choice.
btw. the docs you linked are for clang, GCC is free to have different semantic for this option.

---
___
*[LibOS/shim/src/Makefile, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIeCpa8kVQ6KcynLID:-MQIeCpa8kVQ6KcynLIE:b-dzbjm7) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/Makefile#L21)):*
> ```Makefile
> CFLAGS += -Wextra
> 
> # use TLS-based stack protector of GCC (we rely on the fact LibOS re-uses the same TCB as its
> ```

`on the fact LibOS` -> `on the fact that LibOS`
`re-uses` -> `reuses`
___
*[LibOS/shim/src/shim_init.c, line 63 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIhAxY7rRMrXExDQ3Y:-MQIhAxc3vYZEYi1XFKu:b2nclf8) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/shim_init.c#L63)):*
> ```C
> 
> /* we use GCC's stack protector; when it detects corrupted stack, it calls __stack_chk_fail() */
> noreturn void __stack_chk_fail(void); /* to supress GCC's warning "no previous prototype" */
> ```

`supress` -> `suppress`
___
*[LibOS/shim/src/shim_init.c, line 64 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIhI4q-KVY1-S9dqlD:-MQIhI4q-KVY1-S9dqlE:b-k662tk) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/shim_init.c#L64)):*
> ```C
> /* we use GCC's stack protector; when it detects corrupted stack, it calls __stack_chk_fail() */
> noreturn void __stack_chk_fail(void); /* to supress GCC's warning "no previous prototype" */
> void __stack_chk_fail(void) {
> ```

no `noreturn` here?
___
*[LibOS/shim/src/shim_init.c, line 65 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIhtylDXO9Zmy3JZlt:-MQIhtym82q0STD5n7Ic:b-ei826z) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/shim_init.c#L65)):*
> ```C
> noreturn void __stack_chk_fail(void); /* to supress GCC's warning "no previous prototype" */
> void __stack_chk_fail(void) {
>     debug("Stack protector: Graphene LibOS internal stack is corrupted at %p\n",
> ```

`is corrupted at %p` -> `corruption detected` (I don't think printing the stack pointer is anyhow helpful, it's random and impossible to analyze after the crash)
___
*[Pal/include/arch/x86_64/pal-arch.h, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIibK2AgsCWICKtYvv:-MQIibK2AgsCWICKtYvw:br20dxe) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/include/arch/x86_64/pal-arch.h#L32)):*
> ```objc
> typedef struct pal_tcb {
>     struct pal_tcb* self;
>     /* random per-thread canary used by GCC's stack protector; must be in %gs reg and at offset 0x8
> ```

`must be in %gs reg and at offset 0x8` -> `must be at gs:[0x8]`
___
*[Pal/include/arch/x86_64/pal-arch.h, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIiNwD6nvJDPfVr5uj:-MQIiNwD6nvJDPfVr5uk:bpdfp8w) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/include/arch/x86_64/pal-arch.h#L34)):*
> ```objc
>     /* random per-thread canary used by GCC's stack protector; must be in %gs reg and at offset 0x8
>      * because we specify `-mstack-protector-guard-reg=%gs -mstack-protector-guard-offset=8` */
>     uint64_t stack_protector_canary;
> ```

This struct should either be packed or we should have a `static_assert` for this field having offset == 8.
___
*[Pal/include/arch/x86_64/Linux/pal_host-arch.h, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIjQ_c5DTyVAYcsr1Y:-MQIjQ_c5DTyVAYcsr1Z:b-kq0yj8) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/include/arch/x86_64/Linux/pal_host-arch.h#L22)):*
> ```objc
> /* Graphene uses GCC's stack protector that looks for a canary at %gs:0x8, but this function changes
>  * the GS register value, so we disable stack protector here (even though it is mostly inlined) */
> __attribute__ ((__optimize__("-fno-stack-protector"))) static inline int pal_set_tcb(PAL_TCB* tcb) {
> ```

no space after `__attribute__`
___
*[Pal/src/host/Linux/db_exception.c, line 45 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIkk0W07dvh8W93aKr:-MQIkk0W07dvh8W93aKs:b2nclf8) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_exception.c#L45)):*
> ```C
> 
> /* we use GCC's stack protector; when it detects corrupted stack, it calls __stack_chk_fail() */
> noreturn void __stack_chk_fail(void); /* to supress GCC's warning "no previous prototype" */
> ```

`supress` -> `suppress`
___
*[Pal/src/host/Linux/db_exception.c, line 46 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQInoFSEVjBYoYtjKMa:-MQInoFSEVjBYoYtjKMb:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_exception.c#L46)):*
> ```C
> /* we use GCC's stack protector; when it detects corrupted stack, it calls __stack_chk_fail() */
> noreturn void __stack_chk_fail(void); /* to supress GCC's warning "no previous prototype" */
> void __stack_chk_fail(void) {
> ```

ditto
___
*[Pal/src/host/Linux/db_exception.c, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIklj2Albmjzd7L5Fr:-MQIklj2Albmjzd7L5Fs:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_exception.c#L47)):*
> ```C
> noreturn void __stack_chk_fail(void); /* to supress GCC's warning "no previous prototype" */
> void __stack_chk_fail(void) {
>     printf("Stack protector: Graphene PAL internal stack is corrupted at %p\n",
> ```

ditto
___
*[Pal/src/host/Linux/db_main.c, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIkyqb2E6fISumrMQH:-MQIkyqcAnDlkeoE0FJ2:b-kq0yj8) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_main.c#L155)):*
> ```C
> /* Graphene uses GCC's stack protector that looks for a canary at %gs:0x8, but this function starts
>  * with no TCB in the GS register, so we disable stack protector here */
> __attribute__ ((__optimize__("-fno-stack-protector")))
> ```

no space after `__attribute__`
___
*[Pal/src/host/Linux/db_threading.c, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIlmcSEPRZo0zRQgWW:-MQIlmcSEPRZo0zRQgWX:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L85)):*
> ```C
>  * is used as the alternate stack for signal handling. Since Graphene uses GCC's stack protector,
>  * and this [...]

2021-01-05 20:26 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 27 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPud1pO6J_K9HJ5jiF8:-MQJDgaVAAS4yHU18fhW:bs98vlg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess this is thinking aloud, right? :) Or is there any action I need to do on this PR?

In Graphene, we download and build Glibc *without* stack protector: https://github.com/oscarlab/graphene/blob/master/LibOS/Makefile#L48. Not sure if this is what you meant in your comment.
</blockquote></details>

No, just thinking out loud...

---


<!-- Sent from Reviewable.io -->

2021-01-05 20:28 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 27 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_threading.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPugH925G54l5-Usors:-MQJDoFPAxY0TWU0SnEL:b-17hsof) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can create an arch-specific new function `pal_set_tcb_stack_canary()`, would that work?

But I don't want to move `PAL_TCB::stack_protector_canary` from its offset `0x8` in the `PAL_TCB` struct. Would it be fine with you? You'll then have an unused x86-specific field in the common TCB...
</blockquote></details>

`pal_set_tcb_stack_canary` should then take `pal_tcb_linux` as first parameter so x86 can then use `PAL_TCB` and ppc64 `PAL_TCB_ARCH` to actually set it. Maybe the function should be called `pal_tcb_linux_set_stack_canary` ?


<!-- Sent from Reviewable.io -->

2021-01-06 11:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 8 of 22 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/Makefile, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIeCpa8kVQ6KcynLID:-MQLzlnd-M7B3n1cr3zc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/Makefile#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`on the fact LibOS` -> `on the fact that LibOS`
`re-uses` -> `reuses`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 63 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIhAxY7rRMrXExDQ3Y:-MQM-56bBWofPFaMjbY5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/shim_init.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`supress` -> `suppress`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 64 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIhI4q-KVY1-S9dqlD:-MQM-9dA3K2eKK9Zu8dE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/shim_init.c#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no `noreturn` here?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 65 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIhtylDXO9Zmy3JZlt:-MQM-JyJCkSAyzuRoWZp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/LibOS/shim/src/shim_init.c#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`is corrupted at %p` -> `corruption detected` (I don't think printing the stack pointer is anyhow helpful, it's random and impossible to analyze after the crash)
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIibK2AgsCWICKtYvv:-MQM-USy7jc-8fOwpcfx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/include/arch/x86_64/pal-arch.h#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`must be in %gs reg and at offset 0x8` -> `must be at gs:[0x8]`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIiNwD6nvJDPfVr5uj:-MQM08VE0Y5RaV263ACF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/include/arch/x86_64/pal-arch.h#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This struct should either be packed or we should have a `static_assert` for this field having offset == 8.
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/Linux/pal_host-arch.h, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIjQ_c5DTyVAYcsr1Y:-MQM1YBk1rxWPVMd3eZ-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/include/arch/x86_64/Linux/pal_host-arch.h#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space after `__attribute__`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_exception.c, line 45 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIkk0W07dvh8W93aKr:-MQM1ts12gKcAyDWwDNn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_exception.c#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`supress` -> `suppress`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_exception.c, line 46 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQInoFSEVjBYoYtjKMa:-MQM1uQxD42DciUXjGHC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_exception.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_exception.c, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIklj2Albmjzd7L5Fr:-MQM1unt1AtlZ6krcYbn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_exception.c#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIkyqb2E6fISumrMQH:-MQM1y779Bxnfk-jrwRk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_main.c#L155)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space after `__attribute__`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_threading.c, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQIlmcSEPRZo0zRQgWW:-MQM21Bf3Y2QlFPGvqw2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_threading.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MPugH925G54l5-Usors:-MQMGmcv6DG3fDno3THx:buy78j4) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L94)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

`pal_set_tcb_stack_canary` should then take `pal_tcb_linux` as first parameter so x86 can then use `PAL_TCB` and ppc64 `PAL_TCB_ARCH` to actually set it. Maybe the function should be called `pal_tcb_linux_set_stack_canary` ?
</blockquote></details>

Done. But I still chose the name `pal_set_tcb_stack_canary()`.
___
*[Pal/src/host/Linux/db_threading.c, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQImmWz6o7gCIw3eTZX:-MQM2t808xvs--brm6OY:bgey0fc) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If we'd start with this and setting TCB then we could skip the dummy TCB (and correct the cookie later, ensuring that `_DkRandomBitsRead` reads to a temporary variable, not the real cookie).
</blockquote></details>

I don't see how we can skip dummy TCB (unless we mark `_DkRandomBitsRead()` and all its called functions as `-fno-stack-protector`).

Note that when we're in this function, Linux just created a new thread, and there is nothing stored at `gs:[0x8]` (it may be even inaccessible). This function is fine because it is marked as `-fno-stack-protector`, but we need to call `_DkRandomBitsRead()` which is not marked (and we don't want to mark it because this is really hard to maintain if we ever change that func). So at runtime, there will be an access to `gs:[0x8]` in the `_DkRandomBitsRead()` prologue, and this may lead to SEGFAULT.

So it looks like we need this dummy TCB. I don't see how to circumvent this.
___
*[Pal/src/host/Linux/db_threading.c, line 100 at r2](h [...]

2021-01-06 22:27 UTC, mkow requested changes
> Reviewed 16 of 16 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQOnjIv2xmSQHxS9vls:-MQOnjIv2xmSQHxS9vlt:b-5x5uqv) ([raw file](https://github.com/oscarlab/graphene/blob/833c4e83222e0e2fdd4b2e6f5ba11fee3fc255f2/Pal/include/arch/x86_64/pal-arch.h#L29)):*
> ```objc
> #define PAL_LIBOS_TCB_SIZE 256
> 
> #define STACK_PROTECTOR_CANARY_DEFAULT  0xbadbadbadbad00UL
> ```

No point in having `00` in this hardcoded cookie, no one needs to leak it :)
___
*[Pal/src/host/Linux/db_threading.c, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQImmWz6o7gCIw3eTZX:-MQOm5hx6hcvmdlaRac3:bhgpwb5) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see how we can skip dummy TCB (unless we mark `_DkRandomBitsRead()` and all its called functions as `-fno-stack-protector`).

Note that when we're in this function, Linux just created a new thread, and there is nothing stored at `gs:[0x8]` (it may be even inaccessible). This function is fine because it is marked as `-fno-stack-protector`, but we need to call `_DkRandomBitsRead()` which is not marked (and we don't want to mark it because this is really hard to maintain if we ever change that func). So at runtime, there will be an access to `gs:[0x8]` in the `_DkRandomBitsRead()` prologue, and this may lead to SEGFAULT.

So it looks like we need this dummy TCB. I don't see how to circumvent this.
</blockquote></details>

What I meant is doing `stack_protector_canary = STACK_PROTECTOR_CANARY_DEFAULT` and `pal_set_tcb(&tcb->common);` at the very beginning of this function and then set up the final canary later (so, `_DkRandomBitsRead` would be called with a dummy canary and after its return we'd assign the random value to the canary).
___
*[Pal/src/host/Linux/pal_linux.h, line 170 at r3](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQOn06V-aw-w2R1W2Gq:-MQOn06V-aw-w2R1W2Gr:b63vfcr) ([raw file](https://github.com/oscarlab/graphene/blob/833c4e83222e0e2fdd4b2e6f5ba11fee3fc255f2/Pal/src/host/Linux/pal_linux.h#L170)):*
> ```objc
> 
> static inline void pal_set_tcb_stack_canary(PAL_TCB_LINUX* tcbptr, uint64_t canary) {
>     canary &= ~0xffUL; /* prevent C-string-based stack leaks from exposing the cookie */
> ```

You should actually cast it to `uint8_t*`, otherwise this snippet won't work on big endian.
___
*[Pal/src/host/Linux-SGX/sgx_tls.h, line 87 at r3](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQOndzh71QIxQqVTVqs:-MQOndzh71QIxQqVTVqt:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/833c4e83222e0e2fdd4b2e6f5ba11fee3fc255f2/Pal/src/host/Linux-SGX/sgx_tls.h#L87)):*
> ```objc
> 
> static inline void pal_set_tcb_stack_canary(uint64_t canary) {
>     canary &= ~0xffUL; /* prevent C-string-based stack leaks from exposing the cookie */
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-01-07 11:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: 18 of 22 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQOnjIv2xmSQHxS9vls:-MQRGvOLBIRNbKKKKRcI:b-whwz66) ([raw file](https://github.com/oscarlab/graphene/blob/833c4e83222e0e2fdd4b2e6f5ba11fee3fc255f2/Pal/include/arch/x86_64/pal-arch.h#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No point in having `00` in this hardcoded cookie, no one needs to leak it :)
</blockquote></details>

Done. Reverted.
___
*[Pal/src/host/Linux/db_threading.c, line 100 at r2](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQImmWz6o7gCIw3eTZX:-MQRIajK0OJjOzj5joFA:b-2m4r8s) ([raw file](https://github.com/oscarlab/graphene/blob/256ef53592f2d4967119c2d3e66a102299d0fac5/Pal/src/host/Linux/db_threading.c#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What I meant is doing `stack_protector_canary = STACK_PROTECTOR_CANARY_DEFAULT` and `pal_set_tcb(&tcb->common);` at the very beginning of this function and then set up the final canary later (so, `_DkRandomBitsRead` would be called with a dummy canary and after its return we'd assign the random value to the canary).
</blockquote></details>

Done. Understood now.
___
*[Pal/src/host/Linux/pal_linux.h, line 170 at r3](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQOn06V-aw-w2R1W2Gq:-MQRJ02WBcp_BeWw-Kfr:b46rjs9) ([raw file](https://github.com/oscarlab/graphene/blob/833c4e83222e0e2fdd4b2e6f5ba11fee3fc255f2/Pal/src/host/Linux/pal_linux.h#L170)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You should actually cast it to `uint8_t*`, otherwise this snippet won't work on big endian.
</blockquote></details>

Done. I have a feeling we have quite a few other places in Graphene where big-endian is broken...
___
*[Pal/src/host/Linux-SGX/sgx_tls.h, line 87 at r3](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQOndzh71QIxQqVTVqs:-MQRJSC1CBqXp8OKHiwy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/833c4e83222e0e2fdd4b2e6f5ba11fee3fc255f2/Pal/src/host/Linux-SGX/sgx_tls.h#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-07 12:15 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux/pal_linux.h, line 170 at r3](https://reviewable.io/reviews/oscarlab/graphene/2038#-MQOn06V-aw-w2R1W2Gq:-MQRlJ1aE4Gy06DNoeNb:b-bnwvnv) ([raw file](https://github.com/oscarlab/graphene/blob/833c4e83222e0e2fdd4b2e6f5ba11fee3fc255f2/Pal/src/host/Linux/pal_linux.h#L170)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I have a feeling we have quite a few other places in Graphene where big-endian is broken...
</blockquote></details>

Definitely, but let's try to keep this at minimum :)


<!-- Sent from Reviewable.io -->

2021-01-07 14:40 UTC, mkow approved these changes
> Reviewed 12 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2038)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-07 17:06 UTC, merged