Loader rework part 5: central manifest and constant MRENCLAVE
oscarlab/graphene pull request #2050
Opened 2020-12-30 01:47 UTC by mkow

## Description of the changes 

// Sorry for such a big change in a single commit (and PR), but I really don't have a good idea how to split it into smaller steps.

This is the next part of the great loader rework (previously in this series: #1895, #1901, #1915, #2008), with a lot of breaking changes:

- Complete removal of the "trusted children" thing - now children processes can be spawned arbitrarily and from arbitrary mountpoint types, without any additional configuration needed.
- There's a new, required option in the manifest: `libos.entrypoint` - it specifies the URI to the entry binary in the first process. There's no need anymore to name the manifest and the first binary identically.
- On SGX, the main binary is not measured in MRENCLAVE anymore - only PAL, LibOS and the manifest are measured. This is enough to bind MRENCLAVE to the specific entrypoint user executable if wanted - it just has to be mounted as a trusted file.
- All Graphene SGX enclaves have now exactly the same MRENCLAVE. This is a hash of a "Graphene stub", which can "fork" into one of two states in runtime: initial process or child. The initial process creates a new "Graphene namespace" with a clean state, it can also be attested remotely (contrary to child processes). The initial process can spawn children processes by spawning a Graphene stub and directing it to start in the child mode. It then attests it locally, and if successful, establishes an encrypted pipe, "connects" to its own namespace and treats as trusted (including sending protected files key).
- Now, there's only one, central manifest describing the initial state of a Graphene instance which can be spawned from it (previously, each process required a separate manifest which could have different configuration - which wasn't actually supported and didn't make sense design-wise). One downside of central manifests is that all processes require the same enclave configuration (e.g. size), but that was already the case so far because of broken checkpointing code. Also, this is only a temporary problem, which will cease to exist after the introduction of EDMM.
- `sgx.static_address` was renamed to `sgx.nonpie_binary` and now has to be inserted manually by users (`sgx_sign` tools doesn't know about the binaries run inside, which can be even provided or generated in runtime by the user's workload).
- Caveat: the memory gap for non-PIE executables was removed because it requires adding a new option to the manifest to be cleanly implemented. This is left for some future loader rework PR.

Next plans:

- pal_loader's argument should (IMO) now point to the manifest, not the "project name". It was added as a temporary measure to keep the old invocation syntax for now (this PR introduces a lot of changes already).
- PAL loader code should have no notion of the entrypoint binary - this should be handled solely by the LibOS.
- We need to add a manifest option to reserve user-chosen memory address ranges for non-PIE executables. Upon trying of loading a non-PIE executable without such a reservation, we'd print an error with a snippet which has to be added to the manifest (when printing it we'll already know the exact range used).
- We need to double check (and block in software) that accidental remote attestation of children is not possible (only the initial process should be remotely attested).
- Add separate tests for all weird loading patterns (e.g. starting from a protected file).

Questions/doubts/bugs:

- I didn't do a proper "garbage collecting" stage yet, so you may find some now-unused code while reviewing, please point such cases out. I'll do some cleanups after the next PR (see above).
- GCC still doesn't work, one of the children is crashing. I left debugging this for later, as everything else works.
- After my changes a weird bug in Make started to appear indeterministically: sometimes, after I change a few files, building LibOS regression paralelly overwrites Scripts/Makefile.manifest (using manifest.template from LibOS regression dir). I have no idea how this is possible and I couldn't find which rule/include causes its regeneration, nor how to reproduce it reliably.
- I gave up fixing GSC, too PITA to test changes :/ I think we should move it to a separate repository in our GitHub org, so that both (Graphene and GSC can be updated independently). CC: @vahldiek
- Kudos to @dimakuv for debugging a bug in RTLD code which I triggered :)

Resolves #972. May also help with #1989, but this needs to be verified.

## How to test this PR? 

Current tests should cover most of the cases. I plan to add more tests with weird cases, but rather after finishing the changes from the "Next plans" above.

2020-12-31 03:42 UTC, llly commented
`All Graphene SGX enclaves have now exactly the same MRENCLAVE`  The description is not accurate. There is only one enclave. This enclave can load initial process or child in different instances.

2020-12-31 10:05 UTC, mkow commented
> `All Graphene SGX enclaves have now exactly the same MRENCLAVE` The description is not accurate. There is only one enclave. This enclave can load initial process or child in different instances.

I use "enclave" as "instance of an SGX enclave" there - and we use multiple such instances in one Graphene "namespace", one for each process emulated inside Graphene.

2021-01-02 19:32 UTC, mkow reviewed
> Reviewed 224 of 224 files at r1, 8 of 8 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Examples/gcc/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2050#-MPtQroz8brIIAcV-CZq:-MPtQroz8brIIAcV-CZr:b-8n6ufv) ([raw file](https://github.com/oscarlab/graphene/blob/13c699f7e6445e1b2493790ab5c990512144bde8/Examples/gcc/Makefile#L67)):*
> ```Makefile
> .SECONDARY: gcc.sig
> %.sig: %.manifest.sgx
> 	@true
> ```

Is this how it should be done? I just transformed the older version with weird `echo`, but this whole construction seems suspicious. I'd just remove it and use `;`, but after this (still) unfixed bug (see the PR description) I'm not sure if I understand Make enough :)
___
*[LibOS/shim/src/sys/shim_exec.c, line 378 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2LKvwC3UjcSFD0OGr:-MQ2LKvwC3UjcSFD0OGs:b-y9jzmm) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/LibOS/shim/src/sys/shim_exec.c#L378)):*
> ```C
>     disable_preempt(NULL);
> 
>     bool use_same_process = true;
> ```

Now we're always using the same process (because it always has matching enclave parameters).
___
*[LibOS/shim/test/regression/test_libos.py, line 402 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2fCBs3FDxZ1k5dZDg:-MQ2fCBt88p3mH1kS1vZ:b3rdj4j) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/LibOS/shim/test/regression/test_libos.py#L402)):*
> ```Python
>         self.assertIn('mmap test 7 passed', stdout)
> 
>         # TODO: why is "test 5" missing from here??
> ```

Anyone knows?
The implementation of them looks really hacky and brittle, so maybe that's the reason? We should either remove or fix them, if that's really the reason.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 326 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2icQY6Ajw6g8MxmAq:-MQ2icQZ-WT38NCrluLF:b-pzab6e) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Pal/src/host/Linux-SGX/db_main.c#L326)):*
> ```C
>     }
> 
>     // TODO: Should this really be so early? Isn't this insecure?
> ```

Anyone knows why is it here, where we still didn't finish the initialization?
___
*[Pal/src/host/Linux-SGX/db_process.c, line 102 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ38Xg--7N7u2CHax4U:-MQ38Xg--7N7u2CHax4V:bshw7qf) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Pal/src/host/Linux-SGX/db_process.c#L102)):*
> ```C
> }
> 
> static bool is_child_mr_enclave_ok(PAL_HANDLE child, sgx_measurement_t* mr_enclave,
> ```

Not sure if this `int` -> `bool` change makes sense, now when reading the diff again I like it less than when I wrote it.
Pro: `bool` is simpler and the meaning of the retval is obvious.
Con: we aren't nicely printing errors from `generate_sign_data` anymore, but looking at its code it can't really fail due to any runtime conditions

What do you think, should I revert this?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 698 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3_BsHDembJyuUaVqO:-MQ3_BsHDembJyuUaVqP:b-b111qi) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/Pal/src/host/Linux-SGX/enclave_framework.c#L698)):*
> ```C
>         }
> 
>         SGX_DBG(DBG_S, "trusted: %s\n", new->uri);
> ```

Removed those, were too noisy (and doesn't seem really useful)
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 240 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3ClUL0OS-6mFgT4US:-MQ3ClUL0OS-6mFgT4UT:b-konl8p) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/Pal/src/host/Linux-SGX/sgx_main.c#L240)):*
> ```C
>          * loaded at 0x400000, and heap cannot start at zero (modern OSes do not allow this) */
>         enclave->baseaddr = DEFAULT_ENCLAVE_BASE;
>         enclave_heap_min  = MMAP_MIN_ADDR;
> ```

This was a bug - it should be `MMAP_MIN_ADDR - DEFAULT_ENCLAVE_BASE`, because in the old code `enclave_heap_min` was relative to the enclave base. It worked only because we currently use `DEFAULT_ENCLAVE_BASE == 0`.
I changed all the variables here and below to contain real addresses (except for the ones ending with `_offset`).
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1078 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3PoHZE6eZJPxBZuj8:-MQ3PoH_9LBL44YmhC_y:btb5byn) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Pal/src/host/Linux-SGX/sgx_main.c#L1078)):*
> ```C
>     unmap_tcs();
>     INLINE_SYSCALL(munmap, 2, alt_stack, ALT_STACK_SIZE);
>     INLINE_SYSCALL(exit, 1, 0);
> ```

Yup, this was a bug.
___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3RFub7JA-OAonIKk6:-MQ3RFub7JA-OAonIKk7:b-bgt0c0) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Pal/src/host/Linux-SGX/sgx_process.c#L115)):*
> ```C
>     memcpy(proc_args.pipe_prefix, pal_sec->pipe_prefix, sizeof(PAL_SEC_STR));
> 
>     ret = INLINE_SYSCALL(write, 3, fds[1], &proc_args, sizeof(struct proc_args));
> ```

We should use looped read/write functions here (and everywhere else), but that's something for another PR.
___
*[python/graphenelibos/sgx_sign.py, line 857 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3TK2W-aoHhAZROk3w:-MQ3TK2W-aoHhAZROk3x:bbqjhzd) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/python/graphenelibos/sgx_sign.py#L857)):*
> ```Python
>         # loaded at 0x400000, and heap cannot start at zero (modern OSes do not allow this)
>         enclave_base_addr = offs.DEFAULT_ENCLAVE_BASE
>         enclave_heap_min = offs.MMAP_MIN_ADDR
> ```

FYI: same bug as on the C side.
___
*[Scripts/Makefile.rules, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3U8WX3ghRS1HrVLSJ:-MQ3U8WX3ghRS1HrVLSK:b1rt0yb) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Scripts/Makefile.rules#L155)):*
> ```
> -e 's:\$$(ENTRYPOINT):$(2):g'
> ```

Not sure if that's a good place to insert this, probably not. I got lost in our Makefiles maze, if you have better ideas then please suggest how to do this better.
___
*[Tools/gsc/finalize_manifest.py, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3V--FCXc-4fSmHsDS:-MQ3V--FCXc-4fSmHsDT:b-sa5fgp) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/finalize_manifest.py#L5)):*
> ```Python
> # Copyright (C) 2020 Intel Corp.
> #                    Anjo Vahldiek-Oberwagner <anjo.lucas.vahldiek-oberwagner@intel.com>
> ```

FYI: Seems that Reviewable failed to notice that this file was renamed, you'd better use `git diff` to review it.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQ3VjQ1EN2nbIUV1wlg:b-iz0rsk) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
> ```
> COPY gsc-signer-key.pem /gsc-signer-key.pem
> 
> RUN python3 -B sign_manifests.py #TODO: missing arg here?
> ```

As noted in the PR description, I'm still working on the GSC part, it doesn't work yet :/


<!-- Sent from Reviewable.io -->

2021-01-04 16:41 UTC, woju requested changes
> Reviewed 24 of 224 files at r1, 1 of 8 files at r2, 1 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQDC8tlDTKgEVCiNAiL:-MQDC8tp53EZL8FCVw1N:b-tev2px) (no related file):*
> This is enough to bind MRENCLAVE to the specific entrypoint user executable if wanted - it just has to be mounted as a trusted file.

Is it actually mandatory? ISTM that without enforcing that people actually sign their binaries, this is a huge footgun.

At the minimum I'd like to see a minimal HOWTO in documentation. Otherwise, and if we allow to not have the executable signed, unofficial howtos and instructions will spread which will skip this consideration. Cf. adding `Runtime/` wholesale and copying the libs over there...

---
___
*[.ci/lib/stage-test-direct.jenkinsfile, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD810h76ifVqrqPmOR:-MQD810h76ifVqrqPmOS:b-dkup18) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-direct.jenkinsfile#L40)):*
> ```
>         '''
>     }
>     /* TODO: segfaults for some reason, probably a bug in RTLD code.
> ```

I'd like an issue and #.
___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8EUo6YMnLTDfvOwT:-MQD8EUpE9IB7YDu2XWl:bb7od0r) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-sgx.jenkinsfile#L30)):*
> ```
>         '''
>     }
>     /* TODO: segfaults for some reason, probably a bug in RTLD code.
> ```

same
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQD8Itz1YlS53dnNVUb:bzgf6kn) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
> ```reStructuredText
> ::
> 
>    libos.entrypoint = "URI"
> ```

Can we name this just "entrypoint"? Regular users probably don't need to know what LibOS is.
___
*[Examples/gcc/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2050#-MPtQroz8brIIAcV-CZq:-MQDCjVo9SEO---a1FGf:b-pv82ig) ([raw file](https://github.com/oscarlab/graphene/blob/13c699f7e6445e1b2493790ab5c990512144bde8/Examples/gcc/Makefile#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this how it should be done? I just transformed the older version with weird `echo`, but this whole construction seems suspicious. I'd just remove it and use `;`, but after this (still) unfixed bug (see the PR description) I'm not sure if I understand Make enough :)
</blockquote></details>

This is the proper way: https://www.gnu.org/software/make/manual/html_node/Multiple-Targets.html#Rules-with-Grouped-Targets

I have never used it though.
___
*[Scripts/Makefile.rules, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3U8WX3ghRS1HrVLSJ:-MQDAn8QBrvYD3KSatSY:banuz2) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Scripts/Makefile.rules#L155)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> -e 's:\$$(ENTRYPOINT):$(2):g'
> ```

Not sure if that's a good place to insert this, probably not. I got lost in our Makefiles maze, if you have better ideas then please suggest how to do this better.
</blockquote></details>

Whatever, this will soon go out of the window as part of meson rewrite.


<!-- Sent from Reviewable.io -->

2021-01-04 17:24 UTC, mkow reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQDC8tlDTKgEVCiNAiL:-MQDJ1h05Usz4jLF7Coc:b-9one7r) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> This is enough to bind MRENCLAVE to the specific entrypoint user executable if wanted - it just has to be mounted as a trusted file.

Is it actually mandatory? ISTM that without enforcing that people actually sign their binaries, this is a huge footgun.

At the minimum I'd like to see a minimal HOWTO in documentation. Otherwise, and if we allow to not have the executable signed, unofficial howtos and instructions will spread which will skip this consideration. Cf. adding `Runtime/` wholesale and copying the libs over there...
</blockquote></details>

The problem is actually a bit different than you described - using allowed files in almost all cases is insecure, the main executable isn't any special. E.g. in anything which uses Python you can easily get code exec if .pyc files are _allowed_ instead of _protected_. Same for any other dynamic dependencies, like e.g. .so libraries.

So, this is quite unrelated to this PR, but yes, it is a UX problem. In general, we should discourage any use of allowed files except for testing purposes, but that will be hard, looking at the current state of the project (e.g. we'd need to allow trusted mounts of whole directories to make it more usable).

---
___
*[.ci/lib/stage-test-direct.jenkinsfile, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD810h76ifVqrqPmOR:-MQDKFPg6ICb0VqwrPu9:bbtzixv) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-direct.jenkinsfile#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'd like an issue and #.
</blockquote></details>

For now I hoped that some reviewer will find the bug while reviewing, if that won't happen I'll create an issue.
___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8EUo6YMnLTDfvOwT:-MQDKU1vCXyfPN1jVey5:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-sgx.jenkinsfile#L30)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

same
</blockquote></details>

ditto
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQDKXIy5c258JFExjp6:b-ymtrrz) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can we name this just "entrypoint"? Regular users probably don't need to know what LibOS is.
</blockquote></details>

The trick is that we actually have 2 entrypoints, but one is obfuscated under "preload" setting (and it's actually not preloaded, but launched as a normal executable). So, it works like this: execution starts in PAL, then PAL loads and calls `loader.preload` (I plan to rename this later to `pal.entrypoint`) which usually points to our LibOS (but technically it may not), and then our LibOS initializes itself and loads the user binary from `libos.entrypoint`.

In my opinion we could just link PAL and LibOS statically instead of dynamically and just have one binary and make this exotic configuration (i.e. using different LibOSes) a compile-time option. But that's something for later, definitely out of scope for this PR.
___
*[Examples/gcc/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2050#-MPtQroz8brIIAcV-CZq:-MQDM0G-3vwFVqBabs6j:b-upgvls) ([raw file](https://github.com/oscarlab/graphene/blob/13c699f7e6445e1b2493790ab5c990512144bde8/Examples/gcc/Makefile#L67)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is the proper way: https://www.gnu.org/software/make/manual/html_node/Multiple-Targets.html#Rules-with-Grouped-Targets

I have never used it though.
</blockquote></details>

There's a comment removed by this PR (see Examples/r/Makefile diff) in which I say that I tried using this feature, but seems that it's bugged in Make :) But let's try again, maybe this time I'll have more luck...

Just by using `&:` I get:
```
Makefile:55: *** mixed implicit and normal rules.  Stop.
```

But now we have only one manifest, so I tried replacing pattern matching with a static rule and it seems to work, check now. But I think we won't be able to use it with patterns, or at least I don't know how (I remember this error from the time when I was fixing R example, and that I failed at trying to fix it).


<!-- Sent from Reviewable.io -->

2021-01-04 18:25 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQDC8tlDTKgEVCiNAiL:-MQDYYhp2MtL9YEx7Apv:b8wanz7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem is actually a bit different than you described - using allowed files in almost all cases is insecure, the main executable isn't any special. E.g. in anything which uses Python you can easily get code exec if .pyc files are _allowed_ instead of _protected_. Same for any other dynamic dependencies, like e.g. .so libraries.

So, this is quite unrelated to this PR, but yes, it is a UX problem. In general, we should discourage any use of allowed files except for testing purposes, but that will be hard, looking at the current state of the project (e.g. we'd need to allow trusted mounts of whole directories to make it more usable).
</blockquote></details>

I understand, but this is actually regression. Before this PR, the binary that was launched was included in MRENCLAVE.

---
___
*[.ci/lib/stage-test-direct.jenkinsfile, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD810h76ifVqrqPmOR:-MQD_Za761Xau8ejfu2P:b-7jwzas) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-direct.jenkinsfile#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For now I hoped that some reviewer will find the bug while reviewing, if that won't happen I'll create an issue.
</blockquote></details>

OK, I'll wait.
___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8EUo6YMnLTDfvOwT:-MQD_e-jBJHVZ2Ag6Sjo:bb7s9mg) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-sgx.jenkinsfile#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

yeah
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQD_hT47Rfpu6sARUPM:bo44opv) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The trick is that we actually have 2 entrypoints, but one is obfuscated under "preload" setting (and it's actually not preloaded, but launched as a normal executable). So, it works like this: execution starts in PAL, then PAL loads and calls `loader.preload` (I plan to rename this later to `pal.entrypoint`) which usually points to our LibOS (but technically it may not), and then our LibOS initializes itself and loads the user binary from `libos.entrypoint`.

In my opinion we could just link PAL and LibOS statically instead of dynamically and just have one binary and make this exotic configuration (i.e. using different LibOSes) a compile-time option. But that's something for later, definitely out of scope for this PR.
</blockquote></details>

So as a comment, this is too much developer-centric. I (as a user) care only about the executables and their I/O (mostly limited to files and sockets, because I accidentally forgot about time etc.), so the distinction between PAL and LibOS is for me, shall we say, academic. I think this particular option should be named just `entrypoint` not because of architectural things, but because this matches user expectations.

I agree about compile-time option, and yes, it is out of scope.


<!-- Sent from Reviewable.io -->

2021-01-04 18:42 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQDC8tlDTKgEVCiNAiL:-MQDg1Kr2jBGt1Pg0v-M:b-ny94l3) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I understand, but this is actually regression. Before this PR, the binary that was launched was included in MRENCLAVE.
</blockquote></details>

And it won't just silently continue to work now without updating the manifest, but will complain that the main binary is not allowed nor trusted, and require the user to explicitly add it to the manifest.

---
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQDgTrMD1DQX6ZpjALH:bybowlx) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

So as a comment, this is too much developer-centric. I (as a user) care only about the executables and their I/O (mostly limited to files and sockets, because I accidentally forgot about time etc.), so the distinction between PAL and LibOS is for me, shall we say, academic. I think this particular option should be named just `entrypoint` not because of architectural things, but because this matches user expectations.

I agree about compile-time option, and yes, it is out of scope.
</blockquote></details>

But right now we can't name it just "entrypoint", because we literally have 2 entrypoints specified in the manifest, and we can't get rid of them without changing the linking. I agree that this is very user-unfriendly, but it can't be fixed without changing the design.


<!-- Sent from Reviewable.io -->

2021-01-04 19:09 UTC, dimakuv requested changes
> Reviewed 205 of 224 files at r1, 8 of 8 files at r2, 10 of 10 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 70 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[README.rst, line 70 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQC9Pv1E-wmRGx3_6xB:-MQC9Pv1E-wmRGx3_6xC:b-6763vg) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/README.rst#L70)):*
> ```reStructuredText
> 
>    [PATH TO Runtime]/pal_loader [PROJECT_PATH] [ARGUMENTS]...
>    (Manifest file: "[PROJECT_PATH].manifest")
> ```

Isn't it better to call it `APPLICATION` instead of `PROJECT_PATH`? The documentation around it talks about "applications" (= collection of associated binaries).
___
*[Documentation/manifest-syntax.rst, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAs9J3PgE49ouJRrU:-MQCAs9J3PgE49ouJRrV:b-z8fh51) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L282)):*
> ```reStructuredText
> 
> This setting tells Graphene whether to use a specially crafted memory layout,
> which is required to support non-relocatable binaries (non-PIE).
> ```

Don't we want to add a note here that currently, for multi-process applications, we need to specify `sgx.nonpie_binary = 1` due to the checkpoint/restore logic relying on the exact same memory layout?
___
*[Documentation/devel/debugging.rst, line 22 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAglpD6Ao_F72jvrD:-MQCAglpD6Ao_F72jvrE:bo3xsh9) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/devel/debugging.rst#L22)):*
> ```reStructuredText
> To run Graphene with GDB, use the following command to run your application::
> 
>     GDB=1 [Graphene Directory]/Runtime/pal_loader [project_path] [arguments]
> ```

ditto (`application`?)
___
*[Documentation/devel/performance.rst, line 475 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCB7f61bxbj5OukSJT:-MQCB7f61bxbj5OukSJU:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/devel/performance.rst#L475)):*
> ```reStructuredText
> To record (saves ``perf.data``)::
> 
>     perf record ./pal_loader project_path
> ```

ditto
___
*[Documentation/manpages/gsc.rst, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBJ6oAnWiBJbuCXtw:-MQCBJ6oAnWiBJbuCXtx:bq3iq5a) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manpages/gsc.rst#L249)):*
> ```reStructuredText
> The Docker image defines the entrypoint application which could fork additional
> applications. A common pattern in Docker images executes an entrypoint script
> which calls a set of applications. Similarly to Docker, Graphene has a
> ```

Can we rename `applications` in this file to `executables` where appropriate?
___
*[Documentation/manpages/gsc.rst, line 511 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBY_o9ulZ8plFTgG2:-MQCBY_o9ulZ8plFTgG3:b-hyoy0j) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/Documentation/manpages/gsc.rst#L511)):*
> ```reStructuredText
>    :command:`gsc build` command) at build time. This workaround does not allow
>    these files to change between build and run, or over multiple runs. This only
>    provides integrity for files and not confidentiality.
> ```

Why was this removed?
___
*[Documentation/manpages/pal_loader.rst, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBePdDTDLrR6dmY9g:-MQCBePdDTDLrR6dmY9h:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manpages/pal_loader.rst#L14)):*
> ```reStructuredText
> ========
> 
> :command:`pal_loader` [SGX] [GDB] {<*PROJECT_PATH*>} [<*ARGS*> ...]
> ```

ditto
___
*[Documentation/pal/host-abi.rst, line 31 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBj4o1xPUAlPXER-v:-MQCBj4o1xPUAlPXER-w:b-yj9giz) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/pal/host-abi.rst#L31)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> To run a program in Graphene the PAL loader needs a manifest, which will describe the whole environment inside Graphene namespace. It also describes which binary to start first (via ``libos.entrypoint``).
> ```

`binary` -> `executable` (for consistency, but no hard preference)
___
*[Documentation/tutorials/pytorch/index.rst, line 229 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBuQi4WIjkmkUUidQ:-MQCBuQjCmQWhJwmjpPO:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/tutorials/pytorch/index.rst#L229)):*
> ```reStructuredText
> 
> Now, launch Graphene via ``pal_loader``. You can simply append the arguments
> after the project name.  Our example takes
> ```

ditto
___
*[Examples/bash/manifest.template, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCDU_2-T8RhPF93J4q:-MQCDU_2-T8RhPF93J4r:b-n30n5p) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/bash/manifest.template#L58)):*
> ```
> sgx.thread_num = 4
> 
> # SGX trusted libraries
> ```

Can we change to `SGX trusted files`?
___
*[Examples/busybox/busybox.manifest.template, line 71 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCEDY543M1wimMaSUy:-MQCEDY543M1wimMaSUz:bf8uo0d) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/busybox.manifest.template#L71)):*
> ```
> fs.mount.etc.uri = "file:/etc"
> 
> ############################# SGX: TRUSTED LIBS ###############################
> ```

`TRUSTED FILES`
___
*[Examples/busybox/busybox.manifest.template, line 73 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCEGrO8vuQSeojaoqO:-MQCEGrO8vuQSeojaoqP:b-wa13m0) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/busybox.manifest.template#L73)):*
> ```
> ############################# SGX: TRUSTED LIBS ###############################
> 
> # Specify all libraries used by Busybox and its dependencies (including all
> ```

`libraries` -> `files`
___
*[Examples/busybox/busybox.manifest.template, line 86 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCIWsN2hulP8KjCW8b:-MQCIWsN2hulP8KjCW8c:b-8jkjw7) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/busybox.manifest.template#L86)):*
> ```
> # and compares it with the one specified in 'sgx.trusted_checksum.xxx'. If both
> # hashes match, this library is trusted and allowed to be loaded and used. Note
> # that this happens on the client machine.
> ```

Please fix this comment as you did in Memcached.
___
*[Examples/busybox/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCIQvWAlbpDsBNLpgm:-MQCIQvWAlbpDsBNLpgn:b-8jkjw7) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/Makefile#L79)):*
> ```Makefile
> # procedure measures all Busybox dependencies (shared libraries and trusted
> # files), measures Busybox code/data pages, and adds measurements into the
> # resulting manifest.sgx file (among other, less important SGX options).
> ```

Please fix this comment as you did in Memcached.
___
*[Examples/capnproto/Makefile, line 36 at r3](https://reviewable.io/reviews/oscarlab/g [...]

2021-01-04 19:15 UTC, dimakuv reviewed
> Reviewed 1 of 224 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 70 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2021-01-04 21:03 UTC, yamahata requested changes
> Reviewed 26 of 224 files at r1, 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 72 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[LibOS/shim/src/sys/shim_exec.c, line 452 at r5](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQDxDLJCl4ZVZ_nX_Qy:-MQDxDLK1CaZQlzygZUC:b5jccm7) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/LibOS/shim/src/sys/shim_exec.c#L452)):*
> ```C
>     g_process.exec = exec;
> 
>     ret = create_process_and_send_checkpoint(&migrate_execve, exec, /*child_process=*/NULL,
> ```

Now there is only caller for clone with always exec=NULL.
create_process_and_send_checkpoint can be simplified.
But it can be done as follow up PR. This PR is already huge.
Also same to BEGIN_RS_FUNC(thread) in bookkeep/shim_thread.c
___
*[Pal/src/host/Linux/db_main.c, line 234 at r5](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQE2pxUD0n0_zp1_D8p:-MQE2pxUD0n0_zp1_D8q:b-foglov) ([raw file](https://github.com/oscarlab/graphene/blob/b91baafdf1ad629896a73c59ddfc2b1b51650450/Pal/src/host/Linux/db_main.c#L234)):*
> ```C
>     if (first_process) {
>         const char* project_path = argv[3];
>         exec_uri = NULL;
> ```

nitpick: redundant to the above line.


<!-- Sent from Reviewable.io -->

2021-01-05 03:02 UTC, mkow reviewed
> Reviewed 62 of 62 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 66 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, @woju, and @yamahata)

___
*[README.rst, line 70 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQC9Pv1E-wmRGx3_6xB:-MQDzgEn7Va9yFRfgoMc:b6j1d7d) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/README.rst#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't it better to call it `APPLICATION` instead of `PROJECT_PATH`? The documentation around it talks about "applications" (= collection of associated binaries).
</blockquote></details>

I like the name you're proposing, much better :) If no one else objects then I'll change it to "application" (just want to ensure I won't have to change it back later if others won't like it :) ).

Anyways, it's probably just a temporary thing - see the PR description. I think it would be better to specify the manifest as the argument.
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQEaGpu9AfNCVheuSIN:buchcqz) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But right now we can't name it just "entrypoint", because we literally have 2 entrypoints specified in the manifest, and we can't get rid of them without changing the linking. I agree that this is very user-unfriendly, but it can't be fixed without changing the design.
</blockquote></details>

FYI: We discussed the linking today on the call (with @dimakuv, @boryspoplawski, @donporter and @yamahata) and the conclusion was that static linking of PAL<->LibOS seems like a good idea.
___
*[Documentation/manifest-syntax.rst, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAs9J3PgE49ouJRrU:-MQE2CWL8Oj8lWPHV1hV:b-pd8bmz) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we want to add a note here that currently, for multi-process applications, we need to specify `sgx.nonpie_binary = 1` due to the checkpoint/restore logic relying on the exact same memory layout?
</blockquote></details>

Hmm, good question. Is it actually true? What's allocated first, checkpoint or the executable?
___
*[Documentation/manpages/gsc.rst, line 249 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBJ6oAnWiBJbuCXtw:-MQEJSA2-g5NmdEEOvDJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manpages/gsc.rst#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename `applications` in this file to `executables` where appropriate?
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 511 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBY_o9ulZ8plFTgG2:-MQEK8al8tkpuV2OvUt3:buu2qiq) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/Documentation/manpages/gsc.rst#L511)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why was this removed?
</blockquote></details>

Good question, I can't remember the original reason, maybe I deleted this accidentally. Anyways, restored.
___
*[Documentation/pal/host-abi.rst, line 31 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBj4o1xPUAlPXER-v:-MQEKlitAHCcThLntJR1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/pal/host-abi.rst#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`binary` -> `executable` (for consistency, but no hard preference)
</blockquote></details>

Done.
___
*[Examples/bash/manifest.template, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCDU_2-T8RhPF93J4q:-MQEL6hx5qUDlkeF5aOd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/bash/manifest.template#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we change to `SGX trusted files`?
</blockquote></details>

Done.
___
*[Examples/busybox/busybox.manifest.template, line 71 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCEDY543M1wimMaSUy:-MQELTq_BpZ0c2Vm4cVL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/busybox.manifest.template#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`TRUSTED FILES`
</blockquote></details>

Done.
___
*[Examples/busybox/busybox.manifest.template, line 73 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCEGrO8vuQSeojaoqO:-MQEPm-uCyohPTdXsHYS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/busybox.manifest.template#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`libraries` -> `files`
</blockquote></details>

Done.
___
*[Examples/busybox/busybox.manifest.template, line 86 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCIWsN2hulP8KjCW8b:-MQEQ8OD9-R3ERML1_ix:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/busybox.manifest.template#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix this comment as you did in Memcached.
</blockquote></details>

Done.
___
*[Examples/busybox/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCIQvWAlbpDsBNLpgm:-MQEQkw9B8I3aJSwvE7Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/busybox/Makefile#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix this comment as you did in Memcached.
</blockquote></details>

Done.
___
*[Examples/capnproto/Makefile, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCFzG97FI1U1zFlO5P:-MQEXOtj2wPkHPyuVayy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/capnproto/Makefile#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sometimes you add all three files (`.sgx`, `.token`, `.sig`) and sometimes only one. I suggest to add all three files everywhere, this makes it explicit what this makefile generates (here and everywhere).
</blockquote></details>

Done.
___
*[Examples/common_tools/get_deps.sh, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCFVB6CEON3q2ZBVbk:-MQEXWHl74APWvwAZC5z:bq869l5) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/common_tools/get_deps.sh#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically this is not needed as TOML supports arbitrary keys if surrounded by quotes: `sgx.trusted_files."cr@zy-n00b" = file:...`
</blockquote></details>

Good idea, let's try this.
___
*[Examples/gcc/Makefile, line 67 at r1](htt [...]

2021-01-05 06:34 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 65 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, @woju, and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_main.c, line 326 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2icQY6Ajw6g8MxmAq:-MQGENS8-4W8vjXm1CNX:bdj3ywb) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Pal/src/host/Linux-SGX/db_main.c#L326)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just to be sure, CC @boryspoplawski @yamahata
</blockquote></details>

1a1e199c7 doesn't tell anything.
By grepping enclave_flags, it loos safe to move down the line right before pal_main().


<!-- Sent from Reviewable.io -->

2021-01-05 08:14 UTC, dimakuv requested changes
> Reviewed 58 of 62 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 20 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, @woju, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAs9J3PgE49ouJRrU:-MQGUZWN1NnCOn4Vxc7Q:bmebaia) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L282)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, good question. Is it actually true? What's allocated first, checkpoint or the executable?
</blockquote></details>

Actually, I noticed that the base address where to map the executable is passed in the arguments to the child process, so technically `sgx.nonpie_binary = 1` is not needed. We'll need to investigate why `nonpie_binary` is currently required for multi-process apps with your PR (because now we do `execve` in the same enclave, so "exact same layout" is not an argument anymore). But this is for a follow-up PR.

Anyway, resolving this particular comment.
___
*[Examples/gcc/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2050#-MPtQroz8brIIAcV-CZq:-MQGX4v173lq_jb2GP7u:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/13c699f7e6445e1b2493790ab5c990512144bde8/Examples/gcc/Makefile#L67)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but my original question here was why can't we use `;` after the command here (I think this was the syntax to specify empty rules). Anyways, we have a better solution now :)
</blockquote></details>

OK.
___
*[Examples/python-scipy-insecure/python.manifest.template, line 112 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCKNr1BjVF7WkFu8ll:-MQGXS145oOXpaS6dri-:bkj2thc) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Examples/python-scipy-insecure/python.manifest.template#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good question! On 20.04 these files doesn't exist and the example won't build :)
</blockquote></details>

OK. I don't understand how this was changed in 20.04, but sure, if it works.
___
*[Examples/redis/redis-server.manifest.template, line 89 at r7](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQGY1sm23NaTCgpuYuJ:-MQGY1sn591IVf71eVCm:bf8uo0d) ([raw file](https://github.com/oscarlab/graphene/blob/b83da62705a04878bd5509a8dcd5dae8a3e93125/Examples/redis/redis-server.manifest.template#L89)):*
> ```
> sgx.thread_num = 8
> 
> ############################# SGX: TRUSTED LIBS ###############################
> ```

`TRUSTED FILES`
___
*[Examples/redis/redis-server.manifest.template, line 136 at r7](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQGY8KCDbPVGhwqFkBj:-MQGY8KCDbPVGhwqFkBk:b22quet) ([raw file](https://github.com/oscarlab/graphene/blob/b83da62705a04878bd5509a8dcd5dae8a3e93125/Examples/redis/redis-server.manifest.template#L136)):*
> ```
> sgx.trusted_files.liblz4 = "file:/usr/$(ARCH_LIBDIR)/liblz4.so.1"
> 
> ############################ SGX: TRUSTED FILES ###############################
> ```

Remove this
___
*[LibOS/shim/src/shim_checkpoint.c, line 685 at r7](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQGZ2Ji1Gsl78zCs8rB:-MQGZ2Ji1Gsl78zCs8rC:bai457n) ([raw file](https://github.com/oscarlab/graphene/blob/b83da62705a04878bd5509a8dcd5dae8a3e93125/LibOS/shim/src/shim_checkpoint.c#L685)):*
> ```C
>     add_child_process(child_process);
> 
>     /* fork/clone case: new process is an actual child process for this current process, so
> ```

No need for `fork/clone case:` prefix -- we only have this case left. Just remove it.
___
*[LibOS/shim/test/regression/.gitignore, line 23 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCPkweCVb1-OrKPkw6:-MQGZYFNDFA9cOBtnGEE:bisbsw9) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/LibOS/shim/test/regression/.gitignore#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I just wanted to reduce layers of abstractions and indirections where possible, after spending too much time fighting with our Makefiles :) I can revert this if you don't like it, but let's maybe wait for other's opinions.

CC: @boryspoplawski @yamahata
</blockquote></details>

No, I'm fine. I like this change, but would prefer it in another, unrelated PR (but now it's too late).
___
*[LibOS/shim/test/regression/argv_from_file.manifest, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCPwmf-lQ9OUkz8Twi:-MQGZjo546cBJTT0S0mN:by2ysd5) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/LibOS/shim/test/regression/argv_from_file.manifest#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It doesn't have the insecure argv switch, so it tries to load `loader.argv_src_file` (otherwise it doesn't know what to put into argv[0]). But now we could just put the entrypoint path there, I think this is a good idea. But I'd rather add this to my todolist and do right after this PR, if you don't have a strong opinion on this ;)
</blockquote></details>

OK. We'll fix it in a future PR.


<!-- Sent from Reviewable.io -->

2021-01-05 15:31 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 19 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQDC8tlDTKgEVCiNAiL:-MQI7QJq4k0GJ46W4sBq:bmoepmd) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And it won't just silently continue to work now without updating the manifest, but will complain that the main binary is not allowed nor trusted, and require the user to explicitly add it to the manifest.
</blockquote></details>

OK, if it's not possible to run the executable without it's hash in signature, then it's not a regression.

---
___
*[README.rst, line 70 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQC9Pv1E-wmRGx3_6xB:-MQIA2e50g24iky9nxhv:b-pp2tt6) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/README.rst#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like the name you're proposing, much better :) If no one else objects then I'll change it to "application" (just want to ensure I won't have to change it back later if others won't like it :) ).

Anyways, it's probably just a temporary thing - see the PR description. I think it would be better to specify the manifest as the argument.
</blockquote></details>

Application seems OK.
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQI7kHS2GDS6JKL2oUF:be87ekh) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: We discussed the linking today on the call (with @dimakuv, @boryspoplawski, @donporter and @yamahata) and the conclusion was that static linking of PAL<->LibOS seems like a good idea.
</blockquote></details>

Why can't we name this "entrypoint"? Is the other one already named "entrypoint"?
___
*[Examples/gcc/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2050#-MPtQroz8brIIAcV-CZq:-MQI9kc-4HML8xyyGem5:b-85i63v) ([raw file](https://github.com/oscarlab/graphene/blob/13c699f7e6445e1b2493790ab5c990512144bde8/Examples/gcc/Makefile#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

LGTM.
___
*[LibOS/shim/test/regression/test_libos.py, line 402 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2fCBs3FDxZ1k5dZDg:-MQI8N4S7b3u0AQSwz8v:b-bqk5km) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/LibOS/shim/test/regression/test_libos.py#L402)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No idea. That whole file is hacky...
</blockquote></details>

They're in `test_051_mmap_sgx`, I moved them to another function because they were under some SGX-related `if`, so they needed to be elsewhere. I also moved the comment to the skip message. Skipping works by raising exception, so individual lines cannot be meaningfully skipped, only whole function.

See 01f3553a25a099da02c5b7a0645bdbac2a67c86d.


<!-- Sent from Reviewable.io -->

2021-01-05 17:07 UTC, mkow reviewed
> Reviewed 1 of 1 files at r5, 13 of 13 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQDC8tlDTKgEVCiNAiL:-MQIOgT_BWIVv4Tp-qw7:b-jfai4z) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, if it's not possible to run the executable without it's hash in signature, then it's not a regression.
</blockquote></details>

It is possible, but not by an accident - you need to explicitly add the executable as an allowed file.

---
___
*[README.rst, line 70 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQC9Pv1E-wmRGx3_6xB:-MQIU1nJ80JcF6a9-cr3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/README.rst#L70)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Application seems OK.
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQIOtA_7prAaojUluXk:b5nxdvl) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why can't we name this "entrypoint"? Is the other one already named "entrypoint"?
</blockquote></details>

It's not, but it's currently named incorrectly ("preload", while it's actually the real entrypoint and doesn't have preload semantics).
___
*[Documentation/manifest-syntax.rst, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAs9J3PgE49ouJRrU:-MQIPFu-3eZ2Vb11Mi2S:bxkwb7v) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I noticed that the base address where to map the executable is passed in the arguments to the child process, so technically `sgx.nonpie_binary = 1` is not needed. We'll need to investigate why `nonpie_binary` is currently required for multi-process apps with your PR (because now we do `execve` in the same enclave, so "exact same layout" is not an argument anymore). But this is for a follow-up PR.

Anyway, resolving this particular comment.
</blockquote></details>

I think it's needed only to ensure that the hardcoded range (e.g. 0x400000+) is covered by ELRANGE (see the `if` choosing the base and size).
___
*[Documentation/devel/debugging.rst, line 22 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAglpD6Ao_F72jvrD:-MQIUA_cCW3xGIDDkAlH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/devel/debugging.rst#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`application`?)
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 475 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCB7f61bxbj5OukSJT:-MQIUC5_2E4HCOcQD2F0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/devel/performance.rst#L475)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Documentation/manpages/pal_loader.rst, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBePdDTDLrR6dmY9g:-MQIUDUnB-tHhBoHGieq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manpages/pal_loader.rst#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Documentation/tutorials/pytorch/index.rst, line 229 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCBuQi4WIjkmkUUidQ:-MQIV_6b2wy5FMyLbzlt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/tutorials/pytorch/index.rst#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/redis/redis-server.manifest.template, line 89 at r7](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQGY1sm23NaTCgpuYuJ:-MQIQ8wf0xwp9xSg-8Hh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b83da62705a04878bd5509a8dcd5dae8a3e93125/Examples/redis/redis-server.manifest.template#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`TRUSTED FILES`
</blockquote></details>

Done.
___
*[Examples/redis/redis-server.manifest.template, line 136 at r7](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQGY8KCDbPVGhwqFkBj:-MQIQAx2DCfbj2zR4NGQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b83da62705a04878bd5509a8dcd5dae8a3e93125/Examples/redis/redis-server.manifest.template#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove this
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 685 at r7](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQGZ2Ji1Gsl78zCs8rB:-MQIQT75BnQb0svi53Us:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b83da62705a04878bd5509a8dcd5dae8a3e93125/LibOS/shim/src/shim_checkpoint.c#L685)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `fork/clone case:` prefix -- we only have this case left. Just remove it.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 402 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2fCBs3FDxZ1k5dZDg:-MQIR4AJ7tuFaQd-YOBn:b79nlzl) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/LibOS/shim/test/regression/test_libos.py#L402)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

They're in `test_051_mmap_sgx`, I moved them to another function because they were under some SGX-related `if`, so they needed to be elsewhere. I also moved the comment to the skip message. Skipping works by raising exception, so individual lines cannot be meaningfully skipped, only whole function.

See 01f3553a25a099da02c5b7a0645bdbac2a67c86d.
</blockquote></details>

Right, I didn't notice that they are in a separate test now. I added a comment to not confuse future readers.
___
*[Pal/src/host/Linux/db_main.c, line 138 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCiqEi4cWc0cSV4g8J:-MQIUWjU-W2Jnx6qfEyl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Pal/src/host/Linux/db_main.c#L138)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 326 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2icQY6Ajw6g8MxmAq:-MQIRbiVEPiY7qAIKrv0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Pal/src/host/Linux-SGX/db_main.c#L326)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

1a1e199c7 doesn't tell anything.
By grepping enclave_flags, it loos safe to move down the line right before pal_main().
</blockquote></details>

Do [...]

2021-01-05 17:54 UTC, dimakuv requested changes
> Reviewed 13 of 13 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)

___
*[Tools/gsc/sign_manifest.py, line 32 at r9](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQIfpPQ1NUpFSJy7aoG:-MQIfpPREHGrVGqMzoYS:bu8fzxc) ([raw file](https://github.com/oscarlab/graphene/blob/7ee0cbdf5ed862bb952019f821a183cd6a642407/Tools/gsc/sign_manifest.py#L32)):*
> ```Python
> 
> def main(args=None):
>     print('Signing project:', args[1])
> ```

`Signing application:`


<!-- Sent from Reviewable.io -->

2021-01-05 17:58 UTC, mkow reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, and @yamahata)

___
*[Tools/gsc/sign_manifest.py, line 32 at r9](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQIfpPQ1NUpFSJy7aoG:-MQIgs5m9prM79wYx4qT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ee0cbdf5ed862bb952019f821a183cd6a642407/Tools/gsc/sign_manifest.py#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Signing application:`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-05 18:07 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 414 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCMTQN4_U4xXiqCFK4:-MQIijgw0ll3He_erk92:bxgvo9j) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/LibOS/shim/include/shim_ipc.h#L414)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think I "notified" Borys about removing those, but let's wait for his opinion here :)
</blockquote></details>

OK, I'll resolve this comment from my side.


<!-- Sent from Reviewable.io -->

2021-01-05 20:18 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQJBDgq6rJFZ8RJqJbV:bdayyba) (no related file):*
Now single manifest file is used for all parent and children. we have single setting for sgx.nonpie_binary.
What if some children are pie and some are not?

---


<!-- Sent from Reviewable.io -->

2021-01-05 21:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQJLSv7E76v_WAzLE1v:bsq4k61) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Now single manifest file is used for all parent and children. we have single setting for sgx.nonpie_binary.
What if some children are pie and some are not?

</blockquote></details>

It should still work, this setting only limits the ELRANGE to a less-preferred one (the one with the zero-address problem).

---


<!-- Sent from Reviewable.io -->

2021-01-05 21:06 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-01-06 07:26 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQL_PV57gbMfva0cTS3:bhgpx65) (no related file):*
> this setting only limits the ELRANGE to a less-preferred one (the one with the zero-address problem).

Just to make sure: why do you say "zero-address problem"? There is no real problem, the Intel SGX driver doesn't require `mmap_min_addr == 0` for a long time already.

---


<!-- Sent from Reviewable.io -->

2021-01-06 22:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQOkBso8Guol4OrrCXT:bm76l3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> this setting only limits the ELRANGE to a less-preferred one (the one with the zero-address problem).

Just to make sure: why do you say "zero-address problem"? There is no real problem, the Intel SGX driver doesn't require `mmap_min_addr == 0` for a long time already.
</blockquote></details>

Why do we use that [size; size*2) range then? Why not just always map on the low addresses?

---


<!-- Sent from Reviewable.io -->

2021-01-07 09:45 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQRDgA-2tXeLU71EKu6:baguqho) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why do we use that [size; size*2) range then? Why not just always map on the low addresses?
</blockquote></details>

As always in Graphene, "historical reasons". This was needed before, when the Intel SGX driver didn't allow this. And then nobody cared to remove the `[size; size*2)` logic.

On the other hand, I think our Jenkins still uses the version of the SGX driver that needs `mmap_min_addr == 0`. So we probably can't remove it just yet, until we update the in-Jenkins version.

---


<!-- Sent from Reviewable.io -->

2021-01-07 12:12 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQRkRTh41EFjmJ6IX_q:b-tnui09) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As always in Graphene, "historical reasons". This was needed before, when the Intel SGX driver didn't allow this. And then nobody cared to remove the `[size; size*2)` logic.

On the other hand, I think our Jenkins still uses the version of the SGX driver that needs `mmap_min_addr == 0`. So we probably can't remove it just yet, until we update the in-Jenkins version.
</blockquote></details>

/summon @woju: Which driver version exactly do we use on Jenkins?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQRkgnyBc-pRqPBheX_:-MQRkgnz9A_n5wP1HrWq:bbdnti2) (no related file):*
Just to not forget about this: There's still that makefiles bug we need to debug (see the PR description).

---


<!-- Sent from Reviewable.io -->

2021-01-07 17:32 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQSt1ga3v-3EqWkYuNV:b-fqjctr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

/summon @woju: Which driver version exactly do we use on Jenkins?
</blockquote></details>

commit 0373e2e8b96d9a261657b7657cb514f003f67094 (I don't know how this maps to version numbers)

---
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQStUC41T3o82uaF7G4:bh0te09) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's not, but it's currently named incorrectly ("preload", while it's actually the real entrypoint and doesn't have preload semantics).
</blockquote></details>

Yeah, so if you touch this, why don't fix this once, to the eventual name, and not change this twice?
___
*[LibOS/shim/test/regression/test_libos.py, line 402 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2fCBs3FDxZ1k5dZDg:-MQStkj-BAaTUSkl1UA5:b-85i63v) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/LibOS/shim/test/regression/test_libos.py#L402)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Right, I didn't notice that they are in a separate test now. I added a comment to not confuse future readers.
</blockquote></details>

LGTM.


<!-- Sent from Reviewable.io -->

2021-01-08 03:20 UTC, mkow reviewed
> Reviewed 12 of 12 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @donporter, @mkow, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQRkgnyBc-pRqPBheX_:-MQUwWd00ZLQCD8muFVq:b8zpl63) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just to not forget about this: There's still that makefiles bug we need to debug (see the PR description).
</blockquote></details>

I decided to rename `Makefile.manifest` to `manifest.mk`, which workarounds the issue. I wanted to do this change before anyways, because I was annoyed with the conflicting file extension which prevented nice syntax highlighting in code editors. I didn't rename other makefiles to not extend this PR too much, we can do this later.

---
___
*[.ci/lib/stage-test-direct.jenkinsfile, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD810h76ifVqrqPmOR:-MQUpCYN9m4kYFZgarFK:bu1pubn) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-direct.jenkinsfile#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, I'll wait.
</blockquote></details>

@dimakuv debugged the issue and I just pushed the fix, which passed on Jenkins :) So, huge kudos to him, this wasn't easy to analyze!
___
*[.ci/lib/stage-test-sgx.jenkinsfile, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8EUo6YMnLTDfvOwT:-MQUpNyv2xLTIo9rPzFy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-sgx.jenkinsfile#L30)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

yeah
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQUpTWpD4DknN1kE9Ns:b2na9op) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yeah, so if you touch this, why don't fix this once, to the eventual name, and not change this twice?
</blockquote></details>

The problem is that we don't know when we'll do that change and even if it's actually possible technically without tons of other changes. This is just a general idea of what we want to accomplish in the long run. The "preload" renaming and fixing is going to happen very soon, so we need to have a name for this option without conflicts, because it may stay with us for a long time.

Also, consider that:
a) Currently, manifest syntax is far from stable and will be in such state for quite some time. E.g. we need to actually start using TOML syntax, instead of encoding everything as strings.
b) Users already know (and have to) the distinction between PAL and LibOS, this is a very core term in our project (e.g. users can switch PALs between the ones we provide).


<!-- Sent from Reviewable.io -->

2021-01-08 07:25 UTC, dimakuv submitted a review, later dismissed
> Reviewed 12 of 12 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQJBDgoAh8s6vLnkk9i:-MQVpEVJDBdR6omr8UN_:b-iinymm) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

commit 0373e2e8b96d9a261657b7657cb514f003f67094 (I don't know how this maps to version numbers)
</blockquote></details>

The commit 0373e2 is the latest commit (Nov 2020) in https://github.com/intel/linux-sgx-driver/commits/master. As I understand, this is what we actually run on the hosts. We also use commit 276c5c (see https://github.com/oscarlab/graphene/blob/master/.ci/lib/stage-build-sgx.jenkinsfile#L8) which is also quite new. It's not very good that we have a mismatch between what Graphene "assumes" to be the version and what version actually runs on the host, but there are no differences between the two (only cosmetic ones). So it's all fine.

Both these versions are new and do *not* require the hack of `mmap_min_addr == 0`. We can remove all that stuff on creating enclaves at either `[0; size)` or `[size; size*2)` and keep only the first way (if we agree we don't need the other way for some other reasons).

But this should not be a part of this PR.

---
___
*[.ci/lib/stage-test-direct.jenkinsfile, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD810h76ifVqrqPmOR:-MQVqEfM0YUe1dIAu4j2:b-vubdnm) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-direct.jenkinsfile#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv debugged the issue and I just pushed the fix, which passed on Jenkins :) So, huge kudos to him, this wasn't easy to analyze!
</blockquote></details>

The biggest problem was to find a combination of GDB commands to get to the 7th child process :) Once I was able to put breakpoints in that child, the rest was easy.
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQVqmlt3rLQKd5EePiI:b-avarlk) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem is that we don't know when we'll do that change and even if it's actually possible technically without tons of other changes. This is just a general idea of what we want to accomplish in the long run. The "preload" renaming and fixing is going to happen very soon, so we need to have a name for this option without conflicts, because it may stay with us for a long time.

Also, consider that:
a) Currently, manifest syntax is far from stable and will be in such state for quite some time. E.g. we need to actually start using TOML syntax, instead of encoding everything as strings.
b) Users already know (and have to) the distinction between PAL and LibOS, this is a very core term in our project (e.g. users can switch PALs between the ones we provide).
</blockquote></details>

Agreed with Michal. `loader.preload` should be renamed to `pal.entrypoint`, but in a later PR. It's not just a matter of renaming one field, it's a matter of rewriting this Beautiful Code: https://github.com/oscarlab/graphene/blob/d88e35e1c1dadd54a974a0641f42605797cad52a/Pal/src/db_main.c#L30-L63. Note how this code tries to parse the string of format `lib1,lib2,lib3` via iterating through the `char*` string (because `string.h` is for the weak!). This should be changed to a TOML array instead of this ad-hoc string manipulation.

In other words, it's not hard but not trivial either.


<!-- Sent from Reviewable.io -->

2021-01-08 21:19 UTC, boryspoplawski requested changes
> Reviewed 129 of 224 files at r1, 3 of 8 files at r2, 5 of 10 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 51 of 62 files at r6, 4 of 4 files at r7, 13 of 13 files at r8, 1 of 1 files at r9, 12 of 12 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 20 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, @woju, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQXJ6I-1u51JyK2cR4Q:b-tk6jes) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
> FYI: We discussed the linking today on the call (with @dimakuv, @boryspoplawski, @donporter and @yamahata) and the conclusion was that static linking of PAL<->LibOS seems like a good idea.
FWIW I'm not sure we reached such a conclusion, but there is a lot of benefits from such approach undoubtedly. 
___
*[Documentation/manifest-syntax.rst, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAs9J3PgE49ouJRrU:-MQXJdJoDsMPepp3Ci2u:b-keje0j) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L282)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it's needed only to ensure that the hardcoded range (e.g. 0x400000+) is covered by ELRANGE (see the `if` choosing the base and size).
</blockquote></details>

Could you add a comment what issues arise from setting this? Because now it looks like user should always set this "just in case".
___
*[Documentation/devel/performance.rst, line 319 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXRP3p0zWuZb7VgGM-:-MQXRP3p0zWuZb7VgGM0:bpil6de) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Documentation/devel/performance.rst#L319)):*
> ```reStructuredText
> in Graphene:
> 
> #. ``Fork()``, ``vfork()``, ``clone()`` as well as the ``execve()`` system calls
> ```

I think `execve` doesn't fall in this category now.
___
*[Documentation/devel/performance.rst, line 394 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXRZdVCSAHOs8LUVnc:-MQXRZdVCSAHOs8LUVnd:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Documentation/devel/performance.rst#L394)):*
> ```reStructuredText
>    on each file access via SGX SDK Merkle-tree format.
> 
> #. ``Fork/vfork/clone/execve`` all require to generate an encrypted checkpoint
> ```

ditto
___
*[Examples/bash/Makefile, line 30 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYa5Tj5JGYf0Z9uXqd:-MQYa5Tj5JGYf0Z9uXqe:bfkusg7) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/bash/Makefile#L30)):*
> ```Makefile
> # Generate manifest rules for Bash dependencies.
> # We'll duplicate some Glibc libraries (which Graphene provides in a customized version), but
> # there's no harm in this.
> ```

I don't like this. What if host glibc provides a symbol which Graphene's glibc does not? I suppose host glibc will be loaded and such symbol used (as it is trusted and in LIBRARY_PATH)
___
*[Examples/bash/manifest.template, line 32 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYLcAQ7svV3XPuMxqh:-MQYLcAQ7svV3XPuMxqi:bl7hih0) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/bash/manifest.template#L32)):*
> ```
> fs.mount.usr_lib.type = "chroot"
> fs.mount.usr_lib.path = "/usr/lib"
> fs.mount.usr_lib.uri = "file:/usr/lib"
> ```

Is it a good idea to hardcode this (and the one above) path here?
___
*[Examples/blender/blender.manifest.template, line 86 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYXa3N-xbbXFail5z6:-MQYXa3OESSzwFKqps5s:b-s06uc7) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/blender/blender.manifest.template#L86)):*
> ```
> # Ubuntu version specific files
> # [Ubuntu18.04] sgx.trusted_files.libbsd = "file:$(ARCH_LIBDIR)/libbsd.so.0"
> # [Ubuntu20.04] sgx.trusted_files.libbsd = "file:/usr/$(ARCH_LIBDIR)/libbsd.so.0"
> ```

This makes no sense (and works by accident), `ARCH_LIBDIR` is an absolute path.
___
*[Examples/blender/Makefile, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYZKVH5Mwsypb9s8ez:-MQYZKVH5Mwsypb9s8f-:b-w46yue) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/blender/Makefile#L48)):*
> ```Makefile
> 	mkdir -p $@
> 
> blender.manifest: blender.manifest.template $(BLENDER_DIR)/blender | $(RUN_DIR)
> ```

Is there any particular reason fro moving all these files out of `BLENDER_DIR`?
___
*[LibOS/shim/include/shim_ipc.h, line 414 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCMTQN4_U4xXiqCFK4:-MQXN7qa2XhsiEsgJjYO:b-t2x4ta) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/LibOS/shim/include/shim_ipc.h#L414)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I'll resolve this comment from my side.
</blockquote></details>

Yes, since there is no more moving current graphene process to a new host process, they are not needed anymore.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXOpzo5CPMOvzV3Kr-:-MQXOpzo5CPMOvzV3Kr0:bgk4dzr) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/bookkeep/shim_handle.c#L61)):*
> ```C
>     if (g_process.exec) {
>         // TODO: This is only a temporary workaround, which should be deleted after removing exec
>         // handling from PAL. PAL_CB(executable) is valid only until first execve - in such case
> ```

Wait, what does `PAL_CB(executable)` point to after first execve?
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 8 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXTXyt4I8YsxE4PpTB:-MQXTXyt4I8YsxE4PpTC:b-x4usrv) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/ipc/shim_ipc_helper.c#L8)):*
> ```C
>  * of IPC ports.
>  */
> ```

There are a couple of places in this file that have some dead code (due to execve-in-new-process being removed). Please add a TODO here to remove them (let's not do that in this PR, it's already big and close to being merged).
___
*[LibOS/shim/src/sys/shim_clone.c, line 221 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXUvST0G11gazeeJAK:-MQXUvST0G11gazeeJAL:b-o6ktye) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/sys/shim_clone.c#L221)):*
> ```C
> 
>     long ret = create_process_and_send_checkpoint(&migrate_fork,
>                                                   child_process,
> ```

NP: Please move this to previous line.
___
*[LibOS/shim/src/sys/shim_exec.c, line 378 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ2LKvwC3UjcSFD0OGr:-MQXW3m32Sjefu7CFvd6:b-mxe9vo) ([raw file](https://github.com/oscarlab/graphene/blob/1df560ee2ec91bee6efd101529f5140d2057c439/LibOS/shim/src/sys/shim_exec.c#L378)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

:champagne:
</blockquote></details>

noice!
___
*[LibOS/shim/test/ltp/Makefile.Test, line 87 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYmxvq5CzUCIO9ZFzi:-MQYmxvq5CzUCIO9ZFzj:b-aqplrd) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/test/ltp/Makefile.Test#L87)):*
> ```
> 	sed -e 's:\$$(ENTRYPOINT):$*:g' $(manifest_rules) $< > $@
> 
>  [...]

2021-01-09 01:47 UTC, mkow reviewed
> Reviewed 8 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, @woju, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQZcH4SA8B4_SKi4U2E:bym67yp) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
> FWIW I'm not sure we reached such a conclusion, but there is a lot of benefits from such approach undoubtedly.

Hmm, seems we interpreted this differently ;) Anyways, I think this is something we'll eventually do someday.
___
*[Documentation/manifest-syntax.rst, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQCAs9J3PgE49ouJRrU:-MQZcj_j6iFqpIEFvJxn:b-ss72vk) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L282)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you add a comment what issues arise from setting this? Because now it looks like user should always set this "just in case".
</blockquote></details>

See the other discussion thread, about the driver. The conclusion is that this option can be removed altogether and we can always use `[0, size)` ELRANGE. This option made sense with the old OOT driver, but we don't support it anymore.
But also, @dimakuv asked to not remove it in this PR and to do this in a follow-up one ;)
___
*[Documentation/devel/performance.rst, line 319 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXRP3p0zWuZb7VgGM-:-MQZdeLm7bCrnHXGzwhI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Documentation/devel/performance.rst#L319)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think `execve` doesn't fall in this category now.
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 394 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXRZdVCSAHOs8LUVnc:-MQZdoU-Bxvq3YSotviS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Documentation/devel/performance.rst#L394)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Examples/bash/Makefile, line 30 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYa5Tj5JGYf0Z9uXqd:-MQZe88W4wKfss4ItOeX:bapvla0) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/bash/Makefile#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this. What if host glibc provides a symbol which Graphene's glibc does not? I suppose host glibc will be loaded and such symbol used (as it is trusted and in LIBRARY_PATH)
</blockquote></details>

I don't think so, I think the first library matching by name is loaded? I would be surprised if there was a logic loading other libraries with the same name from different directories if a symbol is missing.
___
*[Examples/bash/manifest.template, line 32 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYLcAQ7svV3XPuMxqh:-MQZnh8m5OD_LPlgLmTM:befi62i) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/bash/manifest.template#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is it a good idea to hardcode this (and the one above) path here?
</blockquote></details>

I'm not sure what you mean, we do it this was in all examples (mounting some host paths directly).
___
*[Examples/blender/blender.manifest.template, line 86 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYXa3N-xbbXFail5z6:-MQZetbyD8qMe6nCl4TH:b424ti) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/blender/blender.manifest.template#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This makes no sense (and works by accident), `ARCH_LIBDIR` is an absolute path.
</blockquote></details>

I'm not sure how all those paths work and which one is which on Linux. What do you propose here? Adding additional `ARCH_USRLIBDIR`?
___
*[Examples/blender/Makefile, line 48 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYZKVH5Mwsypb9s8ez:-MQZfAmSDu7Bu2kSgDw7:bubx26b) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/blender/Makefile#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is there any particular reason fro moving all these files out of `BLENDER_DIR`?
</blockquote></details>

Just to simplify everything, now we don't need to store the manifest in that subdirectory. Also, AFAIR that's how it was before I introduced that 1-1 manifest-exec matching in a previous loader rework PR and was forced to move it there.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXOpzo5CPMOvzV3Kr-:-MQZfYeqC2jSjaFI_CF9:bp2t1vi) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/bookkeep/shim_handle.c#L61)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, what does `PAL_CB(executable)` point to after first execve?
</blockquote></details>

The first executable called (the one PAL knew about when starting, but it can be later swapped by LibOS). It's quite a mess right now, but I plan to just delete this field in the next PR instead of fixing it.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 8 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXTXyt4I8YsxE4PpTB:-MQZgJ5B3PylmjDdZ8m7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/ipc/shim_ipc_helper.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There are a couple of places in this file that have some dead code (due to execve-in-new-process being removed). Please add a TODO here to remove them (let's not do that in this PR, it's already big and close to being merged).
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_clone.c, line 221 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXUvST0G11gazeeJAK:-MQZgT9Q3OhV237hoDw9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/sys/shim_clone.c#L221)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: Please move this to previous line.
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/Makefile.Test, line 87 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYmxvq5CzUCIO9ZFzi:-MQZgX0d4OxYSmHn299f:bxnbpb7) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/test/ltp/Makefile.Test#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`%` in target only)
</blockquote></details>

Why is this a problem? I use this rule e.g. in LTP or LibOS regression, where some tests have `%.manifest.template` (which takes precedence) but some don't, and use the main template.
___
*[Pal/regression/Bootstr [...]

2021-01-09 01:55 UTC, mkow commented
Jenkins, retest Jenkins please (sendfile tests from LTP failed, known issue)

2021-01-09 03:04 UTC, boryspoplawski requested changes
> Reviewed 7 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, @woju, and @yamahata)

___
*[Examples/bash/Makefile, line 30 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYa5Tj5JGYf0Z9uXqd:-MQZzxJu8OJJCncbkc7G:bf6izsm) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/bash/Makefile#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think so, I think the first library matching by name is loaded? I would be surprised if there was a logic loading other libraries with the same name from different directories if a symbol is missing.
</blockquote></details>

Indeed there seem to be no such logic.
___
*[Examples/bash/manifest.template, line 32 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYLcAQ7svV3XPuMxqh:-MQ_-FKP8gYE99Hp1GG3:b-2ovtqd) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/bash/manifest.template#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure what you mean, we do it this was in all examples (mounting some host paths directly).
</blockquote></details>

I thought most examples generate all such entries dynamically based on used system.
Anyway, unblocking, as this is an existing issue (or it's not even an issue at all).
___
*[Examples/blender/blender.manifest.template, line 86 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYXa3N-xbbXFail5z6:-MQ_025sCBE9pExv5BBs:b-yj857l) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/blender/blender.manifest.template#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure how all those paths work and which one is which on Linux. What do you propose here? Adding additional `ARCH_USRLIBDIR`?
</blockquote></details>

I've seen ldd + awk already being used somewhere in this PR, maybe it's time to also use a loop? :)
To be clear: what I'm saying is that we could extract all needed shared libraries, add them to trusted files and mount all of their directories.
Otoh, I'm not sure if we want to extend this PR ...
On the other (third?) hand if don't do this now, it will stay like this for a long time, as nobody will bother to fix it until something brakes.
Unblocking, this is not really important.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXOpzo5CPMOvzV3Kr-:-MQ_0xXR8OtnCjilZ9v7:bbyto6f) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/bookkeep/shim_handle.c#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The first executable called (the one PAL knew about when starting, but it can be later swapped by LibOS). It's quite a mess right now, but I plan to just delete this field in the next PR instead of fixing it.
</blockquote></details>

Just to be sure: this is not a dangling pointer after we do a `fork()`?
___
*[LibOS/shim/test/ltp/Makefile.Test, line 87 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYmxvq5CzUCIO9ZFzi:-MQ_4XMrB4-PU7qG24ur:b-m3k42o) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/test/ltp/Makefile.Test#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this a problem? I use this rule e.g. in LTP or LibOS regression, where some tests have `%.manifest.template` (which takes precedence) but some don't, and use the main template.
</blockquote></details>

Not really a problem per se, but now we have to remember that we cannot have a file named `*.manifest` anywhere, as there is similar rule in general makefile - and I'm not comfortable with this situation.
Since this is not a huge problem, I'm unblocking.
___
*[python/graphenelibos/sgx_sign.py, line 23 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXtb-s5Ngn1AJY57Lh:-MQ_1tsU1a5Rx1KPp3vj:b-pn9tkn) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/python/graphenelibos/sgx_sign.py#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The problem is that I did a lot of them _after_ changing a significant part of the measurement process, which was itself very PITA to change. So, refactoring them out, debugging the measurement, rebasing the main changes and debugging measurements again would take quite some time (believe me, you don't want to debug "invalid measurement" errors when "invalid measurement" is the only feedback you get).
</blockquote></details>

I was talking more about all these `"` -> `'` changes, which contribute to a lot of not important noise
___
*[Scripts/manifest.mk, line 10 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXxQ7fCNykykTWVuML:-MQ_2QFU96LQL1lu752P:bx2y4i2) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Scripts/manifest.mk#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I know, that's why the previous revision of this PR included an explicit rule for `Scripts/Makefile.manifest` to override this one. And it fixed the issue, but indeterministically ¯\\_(ツ)_/¯

So, I gave up and removed that overriding and just renamed the problematic file, so that the problem disappeared (there's a discussion about this somewhere in this review).
</blockquote></details>

FWIW I cound't find any revision with that explicit rule.
(unblocked)


<!-- Sent from Reviewable.io -->

2021-01-11 00:15 UTC, mkow reviewed
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @donporter, @mkow, @woju, and @yamahata)

___
*[Examples/bash/manifest.template, line 32 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYLcAQ7svV3XPuMxqh:-MQbuCpHBskqes5a0raE:b-kkysa2) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/bash/manifest.template#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I thought most examples generate all such entries dynamically based on used system.
Anyway, unblocking, as this is an existing issue (or it's not even an issue at all).
</blockquote></details>

Nah, they just allow configuring it manually by passing parameters to `make`, and only some of the paths.
___
*[Examples/blender/blender.manifest.template, line 86 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYXa3N-xbbXFail5z6:-MQiklEH2R18XYyNIlYn:b-a8vvza) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Examples/blender/blender.manifest.template#L86)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've seen ldd + awk already being used somewhere in this PR, maybe it's time to also use a loop? :)
To be clear: what I'm saying is that we could extract all needed shared libraries, add them to trusted files and mount all of their directories.
Otoh, I'm not sure if we want to extend this PR ...
On the other (third?) hand if don't do this now, it will stay like this for a long time, as nobody will bother to fix it until something brakes.
Unblocking, this is not really important.
</blockquote></details>

Your third hand convinced me, done :)
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 61 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXOpzo5CPMOvzV3Kr-:-MQbumOa1sqqyzF40O9D:b-dnx3cs) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/src/bookkeep/shim_handle.c#L61)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Just to be sure: this is not a dangling pointer after we do a `fork()`?
</blockquote></details>

Nah, it's always set in `pal_main` and afterwards it never changes.
___
*[LibOS/shim/test/ltp/Makefile.Test, line 87 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYmxvq5CzUCIO9ZFzi:-MQc-vZU1Dp4LAKS1rMI:b-b32hx6) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/test/ltp/Makefile.Test#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not really a problem per se, but now we have to remember that we cannot have a file named `*.manifest` anywhere, as there is similar rule in general makefile - and I'm not comfortable with this situation.
Since this is not a huge problem, I'm unblocking.
</blockquote></details>

Yup, but this makefile should be included only for tests, so I don't think it's a big problem.
___
*[python/graphenelibos/sgx_sign.py, line 23 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXtb-s5Ngn1AJY57Lh:-MQc06_W9ywVeT-i3Lsj:b-v9f7pb) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/python/graphenelibos/sgx_sign.py#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I was talking more about all these `"` -> `'` changes, which contribute to a lot of not important noise
</blockquote></details>

Ah, yup. But I thought they are small enough to not be worth a separate PR.
___
*[Scripts/manifest.mk, line 10 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQXxQ7fCNykykTWVuML:-MQbtfO25eDyq46tLYkh:b-mtr619) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/Scripts/manifest.mk#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

FWIW I cound't find any revision with that explicit rule.
(unblocked)
</blockquote></details>

Check this very file in r1.


<!-- Sent from Reviewable.io -->

2021-01-11 00:30 UTC, boryspoplawski reviewed
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, @woju, and @yamahata)

___
*[LibOS/shim/test/ltp/Makefile.Test, line 87 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYmxvq5CzUCIO9ZFzi:-MQipLp59OcojkRHP6N7:bk0jqsi) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/test/ltp/Makefile.Test#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, but this makefile should be included only for tests, so I don't think it's a big problem.
</blockquote></details>

We have the vary same rule in `Scripts/manifest.mk` which can be (is?) included in a lot of others.


<!-- Sent from Reviewable.io -->

2021-01-11 00:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, @woju, and @yamahata)

___
*[LibOS/shim/test/ltp/Makefile.Test, line 87 at r12](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQYmxvq5CzUCIO9ZFzi:-MQismpZ6HYOXUK9UbOF:b-92y868) ([raw file](https://github.com/oscarlab/graphene/blob/9c0bc450bab851446996b1aa4a612a0298826cd6/LibOS/shim/test/ltp/Makefile.Test#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We have the vary same rule in `Scripts/manifest.mk` which can be (is?) included in a lot of others.
</blockquote></details>

I just checked, only tests use it.
FYI: The rule here is duplicated because no one ever deduplicated the manifests here, in LTP. AFAIR originally all the manifests were duplicated everywhere and we managed to clean up only some of them.


<!-- Sent from Reviewable.io -->

2021-01-11 07:45 UTC, dimakuv approved these changes
> Reviewed 8 of 8 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, @woju, and @yamahata)

___
*[Pal/src/host/Linux-SGX/sgx_process.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3RFub7JA-OAonIKk6:-MQkOWCa36oGlg3xuFt9:blz8auc) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Pal/src/host/Linux-SGX/sgx_process.c#L115)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess this was a question to @dimakuv? I'm in for looping these reads and writes.
</blockquote></details>

Yes, we definitely need to add looping for reads/writes on UNIX domain sockets.

@boryspoplawski seems to be right that POSIX doesn't mandate atomicity for AF_UNIX. On the other hand, it looks like Linux has these atomicity guarantees. I looked at `man 7 unix` and https://stackoverflow.com/questions/4669710/atomic-write-on-an-unix-socket.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQkOuBt1u9_fFA4Rioi:bl4g5xg) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure what to do, I'm giving up with fixing GSC. We can either wait for @vahldiek's help or hardcode the last working commit in GSC default config (right now it's "master").

@dimakuv @boryspoplawski What do you think?
</blockquote></details>

I'm fine with hard-coding the mast working commit.

GSC can be fixed in a later PR.


<!-- Sent from Reviewable.io -->

2021-01-11 14:44 UTC, mkow reviewed
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @donporter, @vahldiek, @woju, and @yamahata)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQltHOz40xGHA97puW-:bz9zjy7) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with hard-coding the mast working commit.

GSC can be fixed in a later PR.
</blockquote></details>

Done, although I wasn't able to test my change to GSC. And... I'm a bit afraid that it won't help, because now the manifest generation scripts will be updated, only the Graphene running inside Docker will be old...
@dimakuv Do you have a server where GSC works? None of mine are compatible with GSC.


<!-- Sent from Reviewable.io -->

2021-01-11 15:14 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, @vahldiek, and @yamahata)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD810h76ifVqrqPmOR:-MQlvMMQ0qBz8mRwrl93:b-ucfknh) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/.ci/lib/stage-test-direct.jenkinsfile#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The biggest problem was to find a combination of GDB commands to get to the 7th child process :) Once I was able to put breakpoints in that child, the rest was easy.
</blockquote></details>

Thanks!
___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQlvYDuCjjYhyERd6cb:bj8pw7) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
I'm talking about a perspective of a random admin/user, who while following a hypothetical "Graphene-SGX quick start" would like to know, where to put her own binary to be executed "in graphene". If that's named `entrypoint`, that would be more helpful than `{whatever}.entrypoint`, for any value of whatever. The latter provokes reaction of "WTF is {whatever} and why would I need this", when that knowledge is unnecessary.

I understand that you know what "libos" is (certainly better than me), but that's https://en.wikipedia.org/wiki/Curse_of_knowledge. Not everyone knows what libos is, and doesn't need to know.

Especially calling this `pal.entrypoint` and `libos.entrypoint` is misguided, because this implies those two options are somehow comparable, bu they're really not: `pal.entrypoint` (`loader.preload`) is implementation detail, while `[libos.]entrypoint` is The Most Important Field in the Whole Manifest.

IOW, I'm advocating for specifying that `entrypoint` is "where you put your (user's) executable", disregarding any implementation detail. For example if you had some hypothetical libos replacement that should also use this key to get the elf to load, not `replacement.entrypoint`, because that would be one thing less to remember to change.

> But right now we can't name it just "entrypoint", because we literally have 2 entrypoints specified in the manifest

I'm not familiar with manifest parsing. Is this because of some technical reason, like "everything from `libos.*` subtree is passed to libos and it is impossible to touch anything not in this tree"?


<!-- Sent from Reviewable.io -->

2021-01-11 15:15 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @donporter, @mkow, @vahldiek, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQm-xDE4XQrDpx_NWUD:b-smp7cp) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'm talking about a perspective of a random admin/user, who while following a hypothetical "Graphene-SGX quick start" would like to know, where to put her own binary to be executed "in graphene". If that's named `entrypoint`, that would be more helpful than `{whatever}.entrypoint`, for any value of whatever. The latter provokes reaction of "WTF is {whatever} and why would I need this", when that knowledge is unnecessary.

I understand that you know what "libos" is (certainly better than me), but that's https://en.wikipedia.org/wiki/Curse_of_knowledge. Not everyone knows what libos is, and doesn't need to know.

Especially calling this `pal.entrypoint` and `libos.entrypoint` is misguided, because this implies those two options are somehow comparable, bu they're really not: `pal.entrypoint` (`loader.preload`) is implementation detail, while `[libos.]entrypoint` is The Most Important Field in the Whole Manifest.

IOW, I'm advocating for specifying that `entrypoint` is "where you put your (user's) executable", disregarding any implementation detail. For example if you had some hypothetical libos replacement that should also use this key to get the elf to load, not `replacement.entrypoint`, because that would be one thing less to remember to change.

> But right now we can't name it just "entrypoint", because we literally have 2 entrypoints specified in the manifest

I'm not familiar with manifest parsing. Is this because of some technical reason, like "everything from `libos.*` subtree is passed to libos and it is impossible to touch anything not in this tree"?
</blockquote></details>

Ah, and I agree that rewriting `pal.entrypoint` and The Beautiful Code is out of scope, but that's not what I meant.


<!-- Sent from Reviewable.io -->

2021-01-12 00:33 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @donporter, @vahldiek, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQm0mJH5ZcQXq401xkg:b4yxik0) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
But users are actually required to know what LibOS and PAL are and will always need to - because you have different PALs (backends) from which you need to choose and configure one. Some configuration options are backend-specific and will always be prefixed with something like "pal_linux_sgx.something" (right now it's just "sgx", but that may change if we at some point add e.g. Windows-SGX PAL). This split also tells you what to change if you change PAL (you shouldn't need to touch any libos.\*).

> this implies those two options are somehow comparable, bu they're really not

They are, currently we support running without LibOS (you can replace LibOS with any executable which dynamically links to PAL API). Not used in practice at the moment, but the current state is that we support this. If we want to change it we need to do that complicated step of merging PAL and LibOS build-time.

> IOW, I'm advocating for specifying that entrypoint is "where you put your (user's) executable"

As above, user executable may be using PAL directly.

> I'm not familiar with manifest parsing. Is this because of some technical reason, like "everything from libos.* subtree is passed to libos and it is impossible to touch anything not in this tree"?

Nope, the reason is to have nicely structurized configuration with a split between PAL and LibOS params, because they are totally separate components.

Anyways, my high-level take is that we shouldn't focus on micro-optimization of Graphene-newbies experience at the cost of technical cleanliness. We have a lot of changes ahead of us and optimizing UX for newcomers at this moment doesn't make sense, because everything will change a lot. We can do this after we reach some stability with the overall design.


<!-- Sent from Reviewable.io -->

2021-01-12 13:15 UTC, woju submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @vahldiek)

___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQqh9PpAIPFK7tQznXg:b-ychuoc) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But users are actually required to know what LibOS and PAL are and will always need to - because you have different PALs (backends) from which you need to choose and configure one. Some configuration options are backend-specific and will always be prefixed with something like "pal_linux_sgx.something" (right now it's just "sgx", but that may change if we at some point add e.g. Windows-SGX PAL). This split also tells you what to change if you change PAL (you shouldn't need to touch any libos.\*).

> this implies those two options are somehow comparable, bu they're really not

They are, currently we support running without LibOS (you can replace LibOS with any executable which dynamically links to PAL API). Not used in practice at the moment, but the current state is that we support this. If we want to change it we need to do that complicated step of merging PAL and LibOS build-time.

> IOW, I'm advocating for specifying that entrypoint is "where you put your (user's) executable"

As above, user executable may be using PAL directly.

> I'm not familiar with manifest parsing. Is this because of some technical reason, like "everything from libos.* subtree is passed to libos and it is impossible to touch anything not in this tree"?

Nope, the reason is to have nicely structurized configuration with a split between PAL and LibOS params, because they are totally separate components.

Anyways, my high-level take is that we shouldn't focus on micro-optimization of Graphene-newbies experience at the cost of technical cleanliness. We have a lot of changes ahead of us and optimizing UX for newcomers at this moment doesn't make sense, because everything will change a lot. We can do this after we reach some stability with the overall design.
</blockquote></details>

I object to "nicely structurized configuration with a split between PAL and LibOS params". This is too much developer-centric.

For now I'll resolve, and will continue this in #2076.


<!-- Sent from Reviewable.io -->

2021-01-12 14:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Documentation/manifest-syntax.rst, line 58 at r3](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQD8Ity2X4DJlcFGB3S:-MQqwERb4IL9xxeT62r0:bh2mdc) ([raw file](https://github.com/oscarlab/graphene/blob/32bf0ec25c10c4101f86d6d5266bb34fdd224c40/Documentation/manifest-syntax.rst#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I object to "nicely structurized configuration with a split between PAL and LibOS params". This is too much developer-centric.

For now I'll resolve, and will continue this in #2076.
</blockquote></details>

Yup, let's move the discussion there.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQqwJHS3Ng2FDYrvy9I:b-7xg5k2) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done, although I wasn't able to test my change to GSC. And... I'm a bit afraid that it won't help, because now the manifest generation scripts will be updated, only the Graphene running inside Docker will be old...
@dimakuv Do you have a server where GSC works? None of mine are compatible with GSC.
</blockquote></details>

Ok, we decided to not block on this and fix it later.


<!-- Sent from Reviewable.io -->

2021-01-12 14:32 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @vahldiek)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQr-V4ZCZlXKNEyfKtS:b-cx74jy) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, we decided to not block on this and fix it later.
</blockquote></details>

Shouldn't we drop all gsc changes from this PR then?
I did not look at them at all (since they do not work)


<!-- Sent from Reviewable.io -->

2021-01-12 14:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @vahldiek)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQr0EKe308RoAHOqoDy:b-tm304u) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we drop all gsc changes from this PR then?
I did not look at them at all (since they do not work)
</blockquote></details>

I'm fine with both leaving and dropping them, whatever :)
@dimakuv what do you think?


<!-- Sent from Reviewable.io -->

2021-01-12 14:52 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @vahldiek)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQr4D5u7VqmrZQBXvCQ:bg9vvbk) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm fine with both leaving and dropping them, whatever :)
@dimakuv what do you think?
</blockquote></details>

I'm fine with leaving the GSC changes here, makes my life easier later (when I submit a PR fixing GSC). 


<!-- Sent from Reviewable.io -->

2021-01-12 14:59 UTC, boryspoplawski reviewed
unblocking GH

2021-01-12 20:15 UTC, mkow reviewed
> Reviewed 20 of 20 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @vahldiek)



<!-- Sent from Reviewable.io -->

2021-01-12 20:21 UTC, mkow commented
Jenkins, retest Jenkins-Debug please (sendfile from LTP failed, known issue)

2021-01-12 21:00 UTC, boryspoplawski approved these changes
> Reviewed 20 of 20 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQ3VjQ1EN2nbIUV1wlf:-MQsNIER6fPv_0laJq6A:b-hs5laz) ([raw file](https://github.com/oscarlab/graphene/blob/70accb7dcdd3943980e81e7af4b2c94fe02855f7/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with leaving the GSC changes here, makes my life easier later (when I submit a PR fixing GSC). 
</blockquote></details>

My point was that they might be wrong :)
Anyway, if you both are ok with having them in this state then let's leave them


<!-- Sent from Reviewable.io -->

2021-01-13 09:49 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r15, 15 of 20 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2050)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2050#-MQv-E1t-ZI_LvuXjl6n:-MQv-E1u7eBcE2rRBUNi:b-qr4d2a) (no related file):*
FYI: I tested this PR on three machines, all of them work:
1. Ubuntu 16.04, Linux 4.15, GCC 5.4.0
2. Ubuntu 18.04, Linux 4.15, GCC 8.4.0
3. Ubuntu 19.10, Linux 5.4, GCC 9.2.1

---


<!-- Sent from Reviewable.io -->

2021-01-13 09:58 UTC, merged