[LibOS] Do not call test_user_memory on LibOS allocated memory
oscarlab/graphene pull request #2061
Opened 2021-01-05 21:25 UTC by boryspoplawski

## Description of the changes 
This commit additionally fixes bugs in shim_do_sendmmsg and
shim_do_recvmmsg - `vlen` argument is the number of items in the array,
not size (in bytes) of it, as previous code assumed.

This change is important in a follow up PR, which causes LibOS to use internally allocated stack.

2021-01-06 09:07 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQLtcf641GykJka7guK:-MQLtcf7CMDMggp45L6j:b-gnwaga) (no related file):*
The commit name is not exact (it made me think that you did some global changes). I would prefer to change it to `[LiBOS] Do not call test_user_memory in internal sendmsg/recvmsg funcs`.

(This can be done during final rebase, otherwise I found no issues with this PR so I implicitly approve it.)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQLwPP142jSS_493TFi:-MQLwPP142jSS_493TFj:b-mwbdm2) (no related file):*
Nice fixes! Is this the only place where LibOS did `test_user_memory()/test_user_string()` on LibOS-internal objects? If yes, I'm surprised :)

---


<!-- Sent from Reviewable.io -->

2021-01-06 15:23 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQLwPP142jSS_493TFi:-MQNHkZf8CSHG8VjWCQJ:byrg8qq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nice fixes! Is this the only place where LibOS did `test_user_memory()/test_user_string()` on LibOS-internal objects? If yes, I'm surprised :)
</blockquote></details>

There is also `wait4`, but I have it stashed in another PR. Could move it here for a price of conflicts at rebase (but it should be easy).
Actually, let me try that now.

---


<!-- Sent from Reviewable.io -->

2021-01-06 15:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQLwPP142jSS_493TFi:-MQNLCEUDNbBPF82hrme:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is also `wait4`, but I have it stashed in another PR. Could move it here for a price of conflicts at rebase (but it should be easy).
Actually, let me try that now.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQLtcf641GykJka7guK:-MQNLDxW77jxrK0ndVeq:b-73xit0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The commit name is not exact (it made me think that you did some global changes). I would prefer to change it to `[LiBOS] Do not call test_user_memory in internal sendmsg/recvmsg funcs`.

(This can be done during final rebase, otherwise I found no issues with this PR so I implicitly approve it.)
</blockquote></details>

Now it also covers `waitid` (not only `sendmsg/recvmsg`)

---


<!-- Sent from Reviewable.io -->

2021-01-06 17:07 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQNU3DM7pwaaSbPRRZE:-MQNU3DNEq0O85SXmaJL:b-kagzo0) (no related file):*
I think the `vlen` bug is this one: #1931. So, it may also fix `sendmmsg01` from LTP.

---


<!-- Sent from Reviewable.io -->

2021-01-06 17:18 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQLtcf641GykJka7guK:-MQNVHxJAup7otjBNYAV:b-msiqoj) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now it also covers `waitid` (not only `sendmsg/recvmsg`)
</blockquote></details>

OK. No need to change the commit name then.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQNU3DM7pwaaSbPRRZE:-MQNghh2-dl2R4MFSmCj:b-93klhr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the `vlen` bug is this one: #1931. So, it may also fix `sendmmsg01` from LTP.
</blockquote></details>

+1. Please check and add the LTP tests, and also "Fixes #1931".

---


<!-- Sent from Reviewable.io -->

2021-01-07 05:09 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-07 18:31 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2061#-MQNU3DM7pwaaSbPRRZE:-MQT6T5ID0U0MPFOZuRa:bshjand) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. Please check and add the LTP tests, and also "Fixes #1931".
</blockquote></details>

`sendmmsg01` still fails.

---


<!-- Sent from Reviewable.io -->

2021-01-07 18:58 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-01-07 19:01 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2061)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-07 19:05 UTC, merged