[PAL] Some cleanups around pal_linux_tcb and pal_tcb structures
oscarlab/graphene pull request #2065
Opened 2021-01-07 20:33 UTC by stefanberger

This PR creates an inline function for initializing the pal_linux_tcb structure and an architecture-specific inline function for setting the stack canary. For the latter it turned out to be sufficient to use PAL_TCB, rather than PAL_LINUX_TCB, to also set the stack canary on the ppc64 port [On ppc64 the stack canary must be at the 2nd last 64 bit entry in the PAL_TCB structure, so at offset -0x10].

2021-01-08 07:54 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[Pal/src/host/Linux/db_main.c, line 214 at r1](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQVyi6BCmjXmnMxUWUF:-MQVyi6C6DrsKloNb5td:b-qfzjrk) ([raw file](https://github.com/oscarlab/graphene/blob/2f2b97606bbb869cad3c9ae5fbaf452de0668907/Pal/src/host/Linux/db_main.c#L214)):*
> ```C
>     // Initialize TCB at the top of the alternative stack.
>     PAL_TCB_LINUX* tcb = alt_stack + ALT_STACK_SIZE - sizeof(PAL_TCB_LINUX);
>     pal_tcb_linux_init(tcb, first_thread, alt_stack, NULL, NULL);
> ```

Could you add comments: `.., /*callback=*/NULL, /*param=*/NULL);`
___
*[Pal/src/host/Linux/db_threading.c, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQVytAA9K5ta22ELyjb:-MQVytAA9K5ta22ELyjc:b-29zqa1) ([raw file](https://github.com/oscarlab/graphene/blob/2f2b97606bbb869cad3c9ae5fbaf452de0668907/Pal/src/host/Linux/db_threading.c#L163)):*
> ```C
>     // Initialize TCB at the top of the alternative stack.
>     PAL_TCB_LINUX* tcb = child_stack + ALT_STACK_SIZE - sizeof(PAL_TCB_LINUX);
>     pal_tcb_linux_init(tcb, hdl, child_stack, callback, (void *)param);
> ```

Remove redundant space: `(void *)` -> `(void*)`


<!-- Sent from Reviewable.io -->

2021-01-08 12:03 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_main.c, line 214 at r1](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQVyi6BCmjXmnMxUWUF:-MQWs5KTAnUQmesGboip:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f2b97606bbb869cad3c9ae5fbaf452de0668907/Pal/src/host/Linux/db_main.c#L214)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add comments: `.., /*callback=*/NULL, /*param=*/NULL);`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_threading.c, line 163 at r1](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQVytAA9K5ta22ELyjb:-MQWsLVJ24ZrZi6UUZ1k:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f2b97606bbb869cad3c9ae5fbaf452de0668907/Pal/src/host/Linux/db_threading.c#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove redundant space: `(void *)` -> `(void*)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-08 12:06 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-08 12:06 UTC, dimakuv commented
Jenkins, test this please

2021-01-09 02:20 UTC, mkow requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQZwM8aA_bBIiGuzjC3:b-m421id) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
> ```objc
> 
> static inline void pal_tcb_arch_set_stack_canary(PAL_TCB* tcb, uint64_t canary) {
>     tcb->stack_protector_canary = canary;
> ```

Out of curiosity: How can this be different on ppc64? How do you set up the canary there?
___
*[Pal/src/host/Linux/pal_linux.h, line 160 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwAKJ7G1XRxsCuPy_:-MQZwAKJ7G1XRxsCuPya:b-2y6s2h) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/src/host/Linux/pal_linux.h#L160)):*
> ```objc
> 
> static inline void pal_tcb_linux_init(PAL_TCB_LINUX* tcb, PAL_HANDLE handle, void* alt_stack,
>                         int (*callback)(void*), void* param)
> ```

please fix alignment
___
*[Pal/src/host/Linux/pal_linux.h, line 161 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZw75KB0S8_Yih4n_T:-MQZw75L1GrVoQtKjvcW:b9sw6ii) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/src/host/Linux/pal_linux.h#L161)):*
> ```objc
> static inline void pal_tcb_linux_init(PAL_TCB_LINUX* tcb, PAL_HANDLE handle, void* alt_stack,
>                         int (*callback)(void*), void* param)
> {
> ```

this should be on the previous line


<!-- Sent from Reviewable.io -->

2021-01-09 02:35 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQZzumm0qx8iUIHe41h:b89uyur) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Out of curiosity: How can this be different on ppc64? How do you set up the canary there?
</blockquote></details>

Have a look at this patch: https://github.com/stefanberger/graphene4ppc64/commit/72540a6b66da3af72b4ec5e09b99d865076d3d34


<!-- Sent from Reviewable.io -->

2021-01-09 02:37 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[Pal/src/host/Linux/pal_linux.h, line 161 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZw75KB0S8_Yih4n_T:-MQ_-P504pHE-4NkNhlc:b-adacaw) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/src/host/Linux/pal_linux.h#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this should be on the previous line
</blockquote></details>

A line with ~131 characters?


<!-- Sent from Reviewable.io -->

2021-01-09 02:38 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux/pal_linux.h, line 160 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwAKJ7G1XRxsCuPy_:-MQ_-Xir4LJ_OPfQIJSP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/src/host/Linux/pal_linux.h#L160)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-09 02:39 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/pal_linux.h, line 161 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZw75KB0S8_Yih4n_T:-MQ_-m7OCDdxdon8BbWL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/src/host/Linux/pal_linux.h#L161)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

A line with ~131 characters?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-09 02:47 UTC, stefanberger commented
>
> 
> Have a look at this patch: [stefanberger/graphene4ppc64@72540a6](https://github.com/stefanberger/graphene4ppc64/commit/72540a6b66da3af72b4ec5e09b99d865076d3d34)

In short, it has to be at a different location in the TCB... it's a longer story to explain it. Register r13 holds a pointer to the TCB but this pointer is 0x7000 beyond the END of PAL_TCB, so r13 - 0x7000 - sizeof(PAL_TCB) gets you to the PAL_TCB pointer. The canary has to be at r13 - 0x7000 - 0x10, so there's a structure whose last element is a void * and before that is the 64bit canary -- that's where the 0x10 comes from!

2021-01-09 11:42 UTC, yamahata requested changes
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQavHBFDi8S8D1GEwGR:-MQavHBGEtH4miqfdgqo:b-kmnnx9) ([raw file](https://github.com/oscarlab/graphene/blob/811f9c340c1977ec0b9b7422f982391c23354bdf/Pal/include/arch/x86_64/pal-arch.h#L41)):*
> ```objc
> } PAL_TCB;
> 
> static inline void pal_tcb_arch_set_stack_canary(PAL_TCB* tcb, uint64_t canary) {
> ```

paranoia: please add -fno-stack-protector.


<!-- Sent from Reviewable.io -->

2021-01-09 14:25 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: 4 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQavHBFDi8S8D1GEwGR:-MQbXPBCCVe2idBTArHQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/811f9c340c1977ec0b9b7422f982391c23354bdf/Pal/include/arch/x86_64/pal-arch.h#L41)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

paranoia: please add -fno-stack-protector.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-09 19:45 UTC, yamahata reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-09 19:46 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-11 01:19 UTC, boryspoplawski requested changes
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQj-5wf3zg3-3qbZvv8:b-qkj5te) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Have a look at this patch: https://github.com/stefanberger/graphene4ppc64/commit/72540a6b66da3af72b4ec5e09b99d865076d3d34
</blockquote></details>

Does this mean you overwrite glibc's stack canary (on ppc64)?


<!-- Sent from Reviewable.io -->

2021-01-11 02:01 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQj7xSW4v0Ouf2-aIGC:b1y34bm) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Does this mean you overwrite glibc's stack canary (on ppc64)?
</blockquote></details>

No, I don't. glibc just happens to define the layout of the TCB and I embedded this at the end of PAL_TCB. I think I would only need the last two elements of glibc's structure that include the canary and that `void *`.

PAL sets its canary and then glibc will set its own afterwards when initializing. I don't think PAL will ever unroll its stack (via `ret`urns) and run into code that was expecting the PAL canary, which would be a problem. All tests run stable.


<!-- Sent from Reviewable.io -->

2021-01-11 02:02 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQjAQ-yCXaOjwgG8-Cp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

No, I don't. glibc just happens to define the layout of the TCB and I embedded this at the end of PAL_TCB. I think I would only need the last two elements of glibc's structure that include the canary and that `void *`.

PAL sets its canary and then glibc will set its own afterwards when initializing. I don't think PAL will ever unroll its stack (via `ret`urns) and run into code that was expecting the PAL canary, which would be a problem. All tests run stable.

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-11 04:16 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQjdnR_A1N9DXskxg3U:bm9poe1) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But this canary and glibc's are two completely different and unrelated things, neither should overwrite the other. I still fail to understand why this code needs to be arch specific.


<!-- Sent from Reviewable.io -->

2021-01-11 07:51 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQkQ0J-3UEaycp-Gwg2:bwewc45) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But this canary and glibc's are two completely different and unrelated things, neither should overwrite the other. I still fail to understand why this code needs to be arch specific.
</blockquote></details>

@boryspoplawski I think @stefanberger will introduce another field in the TCB struct (`stack_protector_canary_ppc64` or smth) because PPC64 mandates a very specific offset of the canary (I don't understand the details why and how). So that field will be PPC-specific and thus arch-specific.


<!-- Sent from Reviewable.io -->

2021-01-11 07:51 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-01-11 11:35 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlAewJ1XPmyW6sbazN:b-xtk4hk) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I think @stefanberger will introduce another field in the TCB struct (`stack_protector_canary_ppc64` or smth) because PPC64 mandates a very specific offset of the canary (I don't understand the details why and how). So that field will be PPC-specific and thus arch-specific.
</blockquote></details>

@dimakuv , right. The register to use for the TCB is r13 and the canary is at `-0x7010(r13)` (-28688=-0x7010), which ends up being the 2nd to last element in the TCB due to an offset of 0x7000 (see below).

Documentation is here. Hard to digest after breakfast. http://openpowerfoundation.org/wp-content/uploads/resources/leabi/content/dbdoclet.50655241_50444.html

It's called stack_guard in glibc's tcbhead_t. If this structure is extended it needs to be extended at the *beginning* so the canary stays at its designated offset, which is -0x10 from the end of this structure. Due to register relative addressing being used to access the TCB, r13 holds an address that is 0x7000 beyond the end of the TCB structure. So that's where -0x7010 comes from.

This is how code looks like that puts the canary onto the stack:
```
 121478:	f0 8f 4d e9 	ld      r10,-28688(r13)
  12147c:	48 01 5f f9 	std     r10,328(r31)
  121480:	00 00 40 39 	li      r10,0
```

This is how code looks like that verifies it afterwards:

```
  1216fc:	48 01 3f e9 	ld      r9,328(r31)
  121700:	f0 8f 4d e9 	ld      r10,-28688(r13)
  121704:	79 52 29 7d 	xor.    r9,r9,r10
  121708:	00 00 40 39 	li      r10,0
```


<!-- Sent from Reviewable.io -->

2021-01-11 11:58 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlH4Py08k5tdMePqNA:bfcmujc) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

@dimakuv , right. The register to use for the TCB is r13 and the canary is at `-0x7010(r13)` (-28688=-0x7010), which ends up being the 2nd to last element in the TCB due to an offset of 0x7000 (see below).

Documentation is here. Hard to digest after breakfast. http://openpowerfoundation.org/wp-content/uploads/resources/leabi/content/dbdoclet.50655241_50444.html

It's called stack_guard in glibc's tcbhead_t. If this structure is extended it needs to be extended at the *beginning* so the canary stays at its designated offset, which is -0x10 from the end of this structure. Due to register relative addressing being used to access the TCB, r13 holds an address that is 0x7000 beyond the end of the TCB structure. So that's where -0x7010 comes from.

This is how code looks like that puts the canary onto the stack:
```
 121478:	f0 8f 4d e9 	ld      r10,-28688(r13)
  12147c:	48 01 5f f9 	std     r10,328(r31)
  121480:	00 00 40 39 	li      r10,0
```

This is how code looks like that verifies it afterwards:

```
  1216fc:	48 01 3f e9 	ld      r9,328(r31)
  121700:	f0 8f 4d e9 	ld      r10,-28688(r13)
  121704:	79 52 29 7d 	xor.    r9,r9,r10
  121708:	00 00 40 39 	li      r10,0
```

</blockquote></details>

So what I understand (I think): you extend Glibc's TCB with Graphene's TCB (I guess because there's no free-to-use register on pcc64, like currently `gs` on x86).
What I do not understand: why do you reuse Glibc's canary field for Graphene's canary? There's an option `-mstack-protector-guard-offset=0x..` for this (changing canary offset), which seems to be supported on gcc on ppc.


<!-- Sent from Reviewable.io -->

2021-01-11 12:03 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlJEmt1as1RM9Mba9b:b-xgnmgg) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

So what I understand (I think): you extend Glibc's TCB with Graphene's TCB (I guess because there's no free-to-use register on pcc64, like currently `gs` on x86).
What I do not understand: why do you reuse Glibc's canary field for Graphene's canary? There's an option `-mstack-protector-guard-offset=0x..` for this (changing canary offset), which seems to be supported on gcc on ppc.
</blockquote></details>

I only have one register `r13` for the TCB, I think on x86_64 you use `gs` and if I remember correctly also `fs`, one for PAL, the other one for LibOS/glibc. I have to keep everything `constant`, not switching offsets and so on, so that code executed with glibc's canary can enter PAL code and find the canary at the expected offset within the TCB and not access some other field in the TCB (which may work,but wouldn't be correct).


<!-- Sent from Reviewable.io -->

2021-01-11 12:08 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlKxyXD2zsKhvabsNk:b8oaj2i) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I only have one register `r13` for the TCB, I think on x86_64 you use `gs` and if I remember correctly also `fs`, one for PAL, the other one for LibOS/glibc. I have to keep everything `constant`, not switching offsets and so on, so that code executed with glibc's canary can enter PAL code and find the canary at the expected offset within the TCB and not access some other field in the TCB (which may work,but wouldn't be correct).
</blockquote></details>

But canary offset needs to match prologue with epilogue of a function, so it's perfectly fine to have different offsets in different functions (different compilation units in this case) and call one another (glibc and Pal).


<!-- Sent from Reviewable.io -->

2021-01-11 12:15 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlMJ0UCRbSS0rObHrB:b2pcrpy) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But canary offset needs to match prologue with epilogue of a function, so it's perfectly fine to have different offsets in different functions (different compilation units in this case) and call one another (glibc and Pal).
</blockquote></details>

What would the ppc64 access if NOT accessing the canary at its standard location at `-0x7010(r13)` and now r13 holds the glic TCB and enters PAL code that assumes it at a totally different offset but in the same register?


<!-- Sent from Reviewable.io -->

2021-01-11 12:33 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlQBL58h5NJcVMlxPB:b-ec66g7) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

What would the ppc64 access if NOT accessing the canary at its standard location at `-0x7010(r13)` and now r13 holds the glic TCB and enters PAL code that assumes it at a totally different offset but in the same register?
</blockquote></details>


```
typedef struct pal_tcb {
    struct pal_tcb* self;
    /* uint64_t for alignment */
    uint64_t NEW_CANARY;        <------------------------------------------- here
    uint8_t libos_tcb[PAL_LIBOS_TCB_SIZE];
    /* data private to PAL implementation follows this struct. */
    /* we have to keep this last */
    tcbhead_t glibc_tcb;
} PAL_TCB;
```
and the offset would be `-(0x7000 + sizeof(tcbhead_t) + PAL_LIBOS_TCB_SIZE + sizeof(NEW_CANARY))`


<!-- Sent from Reviewable.io -->

2021-01-11 12:47 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlTj7l5NRXXLr1gN15:b-hk0auw) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>


```
typedef struct pal_tcb {
    struct pal_tcb* self;
    /* uint64_t for alignment */
    uint64_t NEW_CANARY;        <------------------------------------------- here
    uint8_t libos_tcb[PAL_LIBOS_TCB_SIZE];
    /* data private to PAL implementation follows this struct. */
    /* we have to keep this last */
    tcbhead_t glibc_tcb;
} PAL_TCB;
```
and the offset would be `-(0x7000 + sizeof(tcbhead_t) + PAL_LIBOS_TCB_SIZE + sizeof(NEW_CANARY))`
</blockquote></details>

And what would I do with existing compiled applications that expect the canary at `-0x7010(r13)`? Would glibc now have to also modify its tcbhead_t to reflect two canary locations?


<!-- Sent from Reviewable.io -->

2021-01-11 12:49 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlUQCtDgKe5l3WXXyG:b-v560bt) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

And what would I do with existing compiled applications that expect the canary at `-0x7010(r13)`? Would glibc now have to also modify its tcbhead_t to reflect two canary locations?
</blockquote></details>

No, why? You don't need to do anything with them, they would still use the old canary. As I said before these are 2 separate and unrelated canaries (one used by glibc+app, the other by LibOS+Pal)


<!-- Sent from Reviewable.io -->

2021-01-11 12:50 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlUL5G1brrbv3WLnBm:bl2gtoj) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, why? You don't need to do anything with them, they would still use the old canary. As I said before these are 2 separate and unrelated canaries (one used by glibc+app, the other by LibOS+Pal)
</blockquote></details>

What I can do in the above structure is simplify it like this:

```
typedef struct pal_tcb {
    struct pal_tcb* self;
    /* uint64_t for alignment */
    uint8_t libos_tcb[PAL_LIBOS_TCB_SIZE];
    /* data private to PAL implementation follows this struct. */
    /* we have to keep this last */
    uint64_t NEW_CANARY;        <------------------------------------------- here
    void *DTV;
} PAL_TCB;
```

This would keep it at -0x7010. I kept it with the glibc_tcb in PAL_TCB because of all these other odd elements in that structure that I don't know under what circumstances and whether at all they are accessed by gcc-created code.


<!-- Sent from Reviewable.io -->

2021-01-11 12:54 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlUwk41FqIeHXPRMyJ:b1yg2w1) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

What I can do in the above structure is simplify it like this:

```
typedef struct pal_tcb {
    struct pal_tcb* self;
    /* uint64_t for alignment */
    uint8_t libos_tcb[PAL_LIBOS_TCB_SIZE];
    /* data private to PAL implementation follows this struct. */
    /* we have to keep this last */
    uint64_t NEW_CANARY;        <------------------------------------------- here
    void *DTV;
} PAL_TCB;
```

This would keep it at -0x7010. I kept it with the glibc_tcb in PAL_TCB because of all these other odd elements in that structure that I don't know under what circumstances and whether at all they are accessed by gcc-created code.
</blockquote></details>

@boryspoplawski But glibc will need to extend its own TCB structure to have the NEW_CANARY field then as well so that it has that also at that 2nd offset, and fill it. So far its structure is smaller and doesn't need it. If we work-around it in an architecture-specific way, I think we're better off for now. Also, PAL_TCB is already defined in arch-specific header files.


<!-- Sent from Reviewable.io -->

2021-01-11 12:58 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlWQLH01ov9nVbkmBb:bl7hirj) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

@boryspoplawski But glibc will need to extend its own TCB structure to have the NEW_CANARY field then as well so that it has that also at that 2nd offset, and fill it. So far its structure is smaller and doesn't need it. If we work-around it in an architecture-specific way, I think we're better off for now. Also, PAL_TCB is already defined in arch-specific header files.
</blockquote></details>

No, you change the offset only for Pal and LibOS, not for glibc, for glibc just leave the default.


<!-- Sent from Reviewable.io -->

2021-01-11 13:18 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQl_ryF-Lm8sZPYWVMq:b-i114ik) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, you change the offset only for Pal and LibOS, not for glibc, for glibc just leave the default.
</blockquote></details>

And when glibc has set r13 with its TCB structure and entered PAL code which now let's say accesses the canary at -0x7200(r13), what do we find at that offset then?


<!-- Sent from Reviewable.io -->

2021-01-11 13:23 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlatKBDrH99lR8bzhD:b-jpswr2) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

And when glibc has set r13 with its TCB structure and entered PAL code which now let's say accesses the canary at -0x7200(r13), what do we find at that offset then?
</blockquote></details>

How do you access LibOS (and Pal as well) TCB then? I thought you have it prepended to glibc TCB.


<!-- Sent from Reviewable.io -->

2021-01-11 13:34 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQldFFx7SApTHt7vS0u:b9j5pf8) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How do you access LibOS (and Pal as well) TCB then? I thought you have it prepended to glibc TCB.
</blockquote></details>

Here: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20210106/LibOS/glibc-patches/glibc-2.31-ppc64.patch#L132

When glibc initializes its TCB it takes the contents of current r13 and stores that into the newly added  `void *LibOS_TCB`. [Ah, and that's why I cannot take take glibc's structure out of TCB_PAL.]


<!-- Sent from Reviewable.io -->

2021-01-11 13:58 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlhv8259OWaT6F0uzC:b-84cp6t) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Here: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20210106/LibOS/glibc-patches/glibc-2.31-ppc64.patch#L132

When glibc initializes its TCB it takes the contents of current r13 and stores that into the newly added  `void *LibOS_TCB`. [Ah, and that's why I cannot take take glibc's structure out of TCB_PAL.]
</blockquote></details>

Ok, now I see, you have just a pointer to LIBOS_TCB added in Glibc's TCB, not the whole struct. This indeed seems not to be solvable just with compilation flags. I guess making this arch-specific is the best way, considering current approach. I'm unblocking this, @dimakuv @mkow if you have something against, now is the time.

Out of curiosity: is there any reason for not stashing whole Graphene's TCB (instead of just a pointer) in Glibc's?


<!-- Sent from Reviewable.io -->

2021-01-11 14:04 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQljgmA7smcm-voQth7:b6t76r9) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, now I see, you have just a pointer to LIBOS_TCB added in Glibc's TCB, not the whole struct. This indeed seems not to be solvable just with compilation flags. I guess making this arch-specific is the best way, considering current approach. I'm unblocking this, @dimakuv @mkow if you have something against, now is the time.

Out of curiosity: is there any reason for not stashing whole Graphene's TCB (instead of just a pointer) in Glibc's?
</blockquote></details>

If it came to 'upstreamability' to get this accepted by glibc folks, I think I'd rather not do that and keep the changes to a minimum. Besides if we were to start stashing the whole thing into glibc we would have to keep the two in sync and keep on stashing... forever.

besides that this LibOS_TCB pointer now lets me detect what structure we are dealing with:
- if it's pointing to NULL, the structure is the PAL_TCB itself (PAL_TCB will always have LIBOS_TCB pointing to NULL)
- if it's pointing to != NULL, that pointer points to the PAL_TCB and the structure that holds this != NULL is the glibc's tcbhead_t.


<!-- Sent from Reviewable.io -->

2021-01-11 14:26 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2065#-MQZwM8aA_bBIiGuzjC2:-MQlpojh78LrH4qWCLYc:b10fuze) ([raw file](https://github.com/oscarlab/graphene/blob/ea35ec5e8125b43b62c282ce26ccc2132c906220/Pal/include/arch/x86_64/pal-arch.h#L42)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

If it came to 'upstreamability' to get this accepted by glibc folks, I think I'd rather not do that and keep the changes to a minimum. Besides if we were to start stashing the whole thing into glibc we would have to keep the two in sync and keep on stashing... forever.

besides that this LibOS_TCB pointer now lets me detect what structure we are dealing with:
- if it's pointing to NULL, the structure is the PAL_TCB itself (PAL_TCB will always have LIBOS_TCB pointing to NULL)
- if it's pointing to != NULL, that pointer points to the PAL_TCB and the structure that holds this != NULL is the glibc's tcbhead_t.
</blockquote></details>

I was silently following this thread. I have no problems with this PR.


<!-- Sent from Reviewable.io -->

2021-01-12 00:40 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-12 08:03 UTC, dimakuv commented
Jenkins, test this please

2021-01-12 08:04 UTC, dimakuv approved these changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-12 09:25 UTC, yamahata approved these changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-12 12:28 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2065)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-12 12:57 UTC, merged