[LIBOS] Fix internal memory fault due to the permission modification of socket
oscarlab/graphene pull request #2070
Opened 2021-01-08 21:07 UTC by bigdata-memory

## Description of the changes 
This patch fixes the unprotected NULL pointer access on dentry
when calling function shim_do_fchmod trying to modify the permissions
of an unnamed domain socket. The fchmod function will return EINVAL
error code according to BSD style in case of no existed dentry
associated with a domain socket FD.

Fixes #2066

2021-01-11 07:57 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-11 07:57 UTC, dimakuv commented
Jenkins, test this please

2021-01-11 09:29 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-11 10:38 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (`test_libos.TC_30_Syscall.test_090_sighandler_reset` timed out, something new; let's do 10 runs to make sure this is not introduced in this PR which I doubt)

2021-01-11 11:07 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (`test_libos.TC_30_Syscall.test_090_sighandler_reset` check; run 2/10)

2021-01-11 11:31 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (`test_libos.TC_30_Syscall.test_090_sighandler_reset` check; run 3/10)

2021-03-10 17:41 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @bigdata-memory)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2070#-MVSBX0i-9nX79YKdmYX:-MVSBX0k24PpEuSf9UHd:b-6kycve) (no related file):*
Could you please rewrite the commit message to something like (the current version does not describe what is the underlying issue):
```
[LibOS] Disallow changing permissions of unnamed UNIX domain sockets

Unnamed UNIX domain sockets are not bound to any filesystem, hence
Graphene does not store any dentry for them and filesystem permission
modifications are not allowed.
```

---
___
*[LibOS/shim/src/sys/shim_fs.c, line 209 at r1](https://reviewable.io/reviews/oscarlab/graphene/2070#-MVSD52G1wV3iQ9IUTK8:-MVSD52G1wV3iQ9IUTK9:b4rt5pl) ([raw file](https://github.com/oscarlab/graphene/blob/4106ed72b6b6c5f0c4809e2bcfdabce7854c640f/LibOS/shim/src/sys/shim_fs.c#L209)):*
> ```C
> 
>     if (!dent) {
>         ret = -EINVAL;
> ```

`EBADF` is the error Linux returns.


<!-- Sent from Reviewable.io -->

2021-03-10 17:53 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @bigdata-memory)

___
*[LibOS/shim/src/sys/shim_fs.c, line 209 at r1](https://reviewable.io/reviews/oscarlab/graphene/2070#-MVSD52G1wV3iQ9IUTK8:-MVSFtz9CoYur25idgTj:bgyi8hc) ([raw file](https://github.com/oscarlab/graphene/blob/4106ed72b6b6c5f0c4809e2bcfdabce7854c640f/LibOS/shim/src/sys/shim_fs.c#L209)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`EBADF` is the error Linux returns.
</blockquote></details>

Sorry, apparently Linux allows for modifying unnamed socket permissions, hence this is only a Graphene bug.


<!-- Sent from Reviewable.io -->

2021-03-10 20:28 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2070#-MVSBX0i-9nX79YKdmYX:-MVSoqh22itH_0L9imUr:b32v57) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you please rewrite the commit message to something like (the current version does not describe what is the underlying issue):
```
[LibOS] Disallow changing permissions of unnamed UNIX domain sockets

Unnamed UNIX domain sockets are not bound to any filesystem, hence
Graphene does not store any dentry for them and filesystem permission
modifications are not allowed.
```
</blockquote></details>

+1

---


<!-- Sent from Reviewable.io -->

2021-03-11 08:08 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2070#-MVSBX0i-9nX79YKdmYX:-MVVJxhF-PGcUxHVfOZk:bjnwb9x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Actually, since we don't have any other pending issues, let me just rebase and change this commit message.

---


<!-- Sent from Reviewable.io -->

2021-03-11 08:14 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2070#-MVSBX0i-9nX79YKdmYX:-MVVLRLJ7uSD95UTuyLx:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, since we don't have any other pending issues, let me just rebase and change this commit message.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-03-11 08:14 UTC, dimakuv commented
Jenkins, test this please

2021-03-11 15:18 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-03-11 17:38 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2070)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-11 20:02 UTC, merged