[LibOS] Compile glibc on x86_64 with stack protector
oscarlab/graphene pull request #2073
Opened 2021-01-11 12:23 UTC by stefanberger

This patch compiles glibc in x86_64 with the stack protector.

2021-01-11 12:24 UTC, stefanberger commented
I will have to rebase this once the other stuff is merged, but I think this is a missing part.

2021-01-12 00:44 UTC, mkow requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2073#-MQo2GwuAW2H8ioeiv1_:-MQo2GwuAW2H8ioeiv1a:b-5k2psw) ([raw file](https://github.com/oscarlab/graphene/blob/8ec473f133d28d4d12dfca214cdd20727ec389b6/LibOS/Makefile#L70)):*
> ```Make
> ifeq ($(ARCH),x86_64)
> STACK_PROTECTOR=--enable-stack-protector=strong
> endif
> ```

Why not doing this on all archs?


<!-- Sent from Reviewable.io -->

2021-01-12 00:50 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2073#-MQo2GwuAW2H8ioeiv1_:-MQo38JnArKKQFBNpXeC:bupxvrx) ([raw file](https://github.com/oscarlab/graphene/blob/8ec473f133d28d4d12dfca214cdd20727ec389b6/LibOS/Makefile#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```Make
> ifeq ($(ARCH),x86_64)
> STACK_PROTECTOR=--enable-stack-protector=strong
> endif
> ```

Why not doing this on all archs?
</blockquote></details>

Because all the other locations where the stack canary is enabled look like this.

https://github.com/oscarlab/graphene/blob/master/Pal/src/Makefile#L34
https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/Makefile#L26


<!-- Sent from Reviewable.io -->

2021-01-12 01:30 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2073#-MQo2GwuAW2H8ioeiv1_:-MQoCM8u5-ijZngopNR2:bksova) ([raw file](https://github.com/oscarlab/graphene/blob/8ec473f133d28d4d12dfca214cdd20727ec389b6/LibOS/Makefile#L70)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Because all the other locations where the stack canary is enabled look like this.

https://github.com/oscarlab/graphene/blob/master/Pal/src/Makefile#L34
https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/Makefile#L26
</blockquote></details>

Yeah, but that's a different case, see the explanation comment in the code: https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/LibOS/shim/src/Makefile#L24

I.e., in our own code we need to specify the exact access method to the cookie, and not all compilers+arch combinations support this.
I think there's nothing stopping us from using strong stack protector in glibc.


<!-- Sent from Reviewable.io -->

2021-01-12 08:41 UTC, dimakuv approved these changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2073#-MQo2GwuAW2H8ioeiv1_:-MQpk7Wv4F44pWwrpf1U:b-s0yh9b) ([raw file](https://github.com/oscarlab/graphene/blob/8ec473f133d28d4d12dfca214cdd20727ec389b6/LibOS/Makefile#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but that's a different case, see the explanation comment in the code: https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/LibOS/shim/src/Makefile#L24

I.e., in our own code we need to specify the exact access method to the cookie, and not all compilers+arch combinations support this.
I think there's nothing stopping us from using strong stack protector in glibc.
</blockquote></details>

I agree with Michal. Actually, we don't even need to specify the stack protector options for Glibc. I think we should build Glibc as-is (whatever stack protector option it uses by default).

So only the hunk above (removing `-fno-stack-protector`) will be left in this PR.

(And before merge, we'll need to check that it actually works, on e.g. newer Ubuntus where this is the default.)


<!-- Sent from Reviewable.io -->

2021-01-12 08:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-12 11:59 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/Makefile, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2073#-MQo2GwuAW2H8ioeiv1_:-MQqSfjN4niJCJ9Yt4_f:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8ec473f133d28d4d12dfca214cdd20727ec389b6/LibOS/Makefile#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Michal. Actually, we don't even need to specify the stack protector options for Glibc. I think we should build Glibc as-is (whatever stack protector option it uses by default).

So only the hunk above (removing `-fno-stack-protector`) will be left in this PR.

(And before merge, we'll need to check that it actually works, on e.g. newer Ubuntus where this is the default.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-12 12:52 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-01-12 13:16 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2073#-MQqjIVD2buHZLy_OJp6:-MQqjIVE4SB0GQOXNaTU:b-r7756t) (no related file):*
@stefanberger Please rebase this to the latest master since we merged 2065.

---


<!-- Sent from Reviewable.io -->

2021-01-12 13:24 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2073#-MQqjIVD2buHZLy_OJp6:-MQql9jt3SAwqElyfLlI:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@stefanberger Please rebase this to the latest master since we merged 2065.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-01-12 13:46 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-12 13:46 UTC, dimakuv commented
Jenkins, test this please

2021-01-12 14:11 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug please (`select04` LTP test failed, strange)

2021-01-12 14:19 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-01-12 14:35 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2073)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-12 14:37 UTC, merged