sync with upstreamed SGX in-kernel driver from mainline 5.11
oscarlab/graphene pull request #2084
Opened 2021-01-14 07:42 UTC by johnvenn

## Description of the changes
1. Intel SGX driver has been upstreamed to mainline from kernel version 5.11. To sync with upstreamed SGX in-kernel driver, as SGX device in the kernel is exposed to "/dev/sgx_enclave" instead of "/dev/sgx/enclave", we need to add instructions to user "udev rules" in Pal/src/host/Linux-SGX/link-intel-driver.py
Fixes #2007
2. Also we need to update documentation on sgx_intro.html for the upstreamed in-kernel SGX driver in linux mainline.
3. For OOT drivers in DCAP from version 1.10, the header file is also changed, we need to sync with it. see:
https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/155

## To test this PR:
1. the 1st time rebooting to 5.11 linux kernel, check:
    ls /dev | grep sgx ==> no /dev/sgx/enclave but /dev/sgx_enclave
2. at Pal/src/host/Linux-SGX, run:
    ISGX_DRIVER_PATH="" ./link-intel-driver.py < ./gsgx.h.in > ./gsgx.h
    An error message will be prompted for how to run the udev rules.

2021-01-14 08:12 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @johnvenn)

___
*[Documentation/sgx-intro.rst, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQztkDaDRvavhD9LEdz:-MQztkDaDRvavhD9LEe-:b14x6le) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Documentation/sgx-intro.rst#L93)):*
> ```reStructuredText
>   more "normal" PKI infrastructure).
> 
> - SGX driver is upstreamed to linux mainline from 5.11+ (see LKML patches). 
> ```

There is a trailing space at the end of this line, please remove
___
*[Documentation/sgx-intro.rst, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQztnZ-2SqHqkZ0KgX0:-MQztnZ-2SqHqkZ0KgX1:b14x6le) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Documentation/sgx-intro.rst#L94)):*
> ```reStructuredText
> 
> - SGX driver is upstreamed to linux mainline from 5.11+ (see LKML patches). 
>   The current SGX driver upstreamed only supports DCAP. SGX device is exposed 
> ```

There is a trailing space at the end of this line, please remove
___
*[Documentation/sgx-intro.rst, line 95 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzu-M310p6rjCyHDmJ:-MQzu-M310p6rjCyHDmK:boo62fu) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Documentation/sgx-intro.rst#L95)):*
> ```reStructuredText
> - SGX driver is upstreamed to linux mainline from 5.11+ (see LKML patches). 
>   The current SGX driver upstreamed only supports DCAP. SGX device is exposed 
>   as /dev/sgx_enclave at current stage, to make it compatible with older versions
> ```

I would prefer `;` instead of `,`: `...at current stage; to make it...`
___
*[Documentation/sgx-intro.rst, line 96 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzu5tE-W9KocXNzwTe:-MQzu5tE-W9KocXNzwTf:b-avk2gy) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Documentation/sgx-intro.rst#L96)):*
> ```reStructuredText
>   The current SGX driver upstreamed only supports DCAP. SGX device is exposed 
>   as /dev/sgx_enclave at current stage, to make it compatible with older versions
>   of SGX driver, user need to apply udev rules the first time rebooting the kernel.
> ```

`user need to` -> `user must`
___
*[Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzww0b8d-DJb4vFUk1:-MQzww0b8d-DJb4vFUk2:bfnf3kr) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/91-sgx-enclave.rules#L3)):*
> ```
> SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> ```

Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzuPWk7s-QJNDzFR1u:-MQzuPWk7s-QJNDzFR1v:b14x6le) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L8)):*
> ```Python
> 
> DRIVER_VERSIONS = {
>         'sgx_user.h':                 '/dev/isgx',         # For Non-DCAP, older versions of legacy OOT SGX driver 
> ```

There is a trailing space at the end of this line, please remove
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzuXy24hCjC5fJhbOQ:-MQzuXy24hCjC5fJhbOR:b-g9x16y) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L9)):*
> ```Python
> DRIVER_VERSIONS = {
>         'sgx_user.h':                 '/dev/isgx',
>         'include/uapi/asm/sgx_oot.h': '/dev/sgx/enclave',
> ```

Please let's also keep this version (`sgx_oot.h`), to support DCAP drivers below 1.10
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzugUO4uZyz3rhCWF8:-MQzugUO4uZyz3rhCWF9:b-be8d4g) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L9)):*
> ```Python
> DRIVER_VERSIONS = {
>         'sgx_user.h':                 '/dev/isgx',         # For Non-DCAP, older versions of legacy OOT SGX driver 
>         'include/sgx_user.h':         '/dev/sgx/enclave',  # For Dcap driver from version 1.10+
> ```

`For Dcap driver from version 1.10+` -> `For DCAP driver version 1.10+`
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvHJo1KVDwewmeu-M:-MQzvHJp7RkVXlwHlz-T:b1dt8vq) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L10)):*
> ```Python
>         'sgx_user.h':                 '/dev/isgx',
>         'include/uapi/asm/sgx_oot.h': '/dev/sgx/enclave',
>         'sgx_in_kernel.h':            '/dev/sgx/enclave',
> ```

Please let's also keep this version, to support the case where the user doesn't specify any SGX-driver directory (`ISGX_DRIVER_PATH=""`). And here the driver name must be changed to the new `/dev/sgx_enclave`.
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvkX3CkGdxw_1KM85:-MQzvkX3CkGdxw_1KM86:b-weooko) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L18)):*
> ```Python
>       - sgx_user.h for non-DCAP, older version of the driver
>         (https://github.com/intel/linux-sgx-driver)
>       - include/uapi/asm/sgx_oot.h for DCAP 1.6+ version of the driver
> ```

Please keep this, to support older versions of DCAP
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvnmP-sCiez-kvCib:-MQzvnmP-sCiez-kvCic:b-hakbj1) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L20)):*
> ```Python
>       - include/uapi/asm/sgx_oot.h for DCAP 1.6+ version of the driver
>         (https://github.com/intel/SGXDataCenterAttestationPrimitives)
>       - default sgx_in_kernel.h for in-kernel 32+ version of the driver
> ```

Please keep this, to support the case where the user doesn't specify any SGX-driver directory (`ISGX_DRIVER_PATH=""`).
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzwANXAlwZUvtsUOyo:-MQzwANYA8q862wZi3Yq:bxeshcr) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L59)):*
> ```Python
>     if not isgx_driver_path: #using in-kernel SGX driver from kernel version 5.11
>         # user did not specify any driver path, use default in-kernel driver's C header
>         # isgx_driver_path = os.path.dirname(os.path.abspath(__file__))
> ```

Why did you comment this line out?
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzwR6z2xEO4n3-NOuD:-MQzwR6z2xEO4n3-NOuE:brxl6j1) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L67)):*
> ```Python
>                     raise FileNotFoundError
>             except FileNotFoundError:
>                 print('SGX in- [...]

2021-01-15 07:16 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @johnvenn)



<!-- Sent from Reviewable.io -->

2021-01-15 07:30 UTC, johnvenn commented
Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):

SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?

Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?

[My answer]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.

2021-01-15 07:31 UTC, johnvenn commented
Pal/src/host/Linux-SGX/link-intel-driver.py, line 20 at r1 (raw file):

      - include/uapi/asm/sgx_oot.h for DCAP 1.6+ version of the driver
        (https://github.com/intel/SGXDataCenterAttestationPrimitives)
      - default sgx_in_kernel.h for in-kernel 32+ version of the driver
Please keep this, to support the case where the user doesn't specify any SGX-driver directory (ISGX_DRIVER_PATH="").

[Xiangping]: will update it in r3.

2021-01-15 07:34 UTC, johnvenn commented
# isgx_driver_path = os.path.dirname(os.path.abspath(__file__))
Why did you comment this line out?

[Xiangping]: sorry for the mistake, there are some problem if user uses in-kernel SGX driver header to compile graphene-SGX for this statement. I will update it to get sgx.h in kernel header

2021-01-15 07:52 UTC, debin-yang commented
> Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> 
> SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> 
> Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> 
> [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.

2021-01-15 08:11 UTC, debin-yang commented
> Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> 
> SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> 
> Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> 
> [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.



> Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> 
> SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> 
> Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> 
> [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.

Just an opinion. I think it should not be the driver or its installer's role to do this (to provide compatibility support for other variants/versions of driver, except its own legacy versions of the same driver.). It should be abstracted higher level above driver.

Drivers (or SGX Linux kernel upstream patch) usually does not know of other variants of SGX Linux driver. This seems particularly true for the SGX Linux Upstream patches so far, along the way it kept changing its device node and/or interfaces, and it does not knows about its owns' previous versions, neither other SGX Linux drivers (SGX Linux OOT Driver, or SGX Linux DCAP drivers).

One reference design of solution for this issue, is the SGX Linux PSW's design which had been adapted to be compatible with all variants/legacy versions of SGX Linux kernel support, namely SGX Linux OOT Drivers, SGX DCAP Linux drivers (which had been tracking the SGX Linux Kernel Upstream patches' interfaces) /SGX Linux Kernel Upstream patches.  So if following this reference, the solution (compatibility with various driver, and the upcoming SGX Linux kernel upstream patch) might go into somewhere into Graphene's installation process instead of the individual driver's installation.

2021-01-15 08:26 UTC, debin-yang commented
> > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> 
> > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> 
> Just an opinion. I think it should not be the driver or its installer's role to do this (to provide compatibility support for other variants/versions of driver, except its own legacy versions of the same driver.). It should be abstracted higher level above driver.
> 
> Drivers (or SGX Linux kernel upstream patch) usually does not know of other variants of SGX Linux driver. This seems particularly true for the SGX Linux Upstream patches so far, along the way it kept changing its device node and/or interfaces, and it does not knows about its owns' previous versions, neither other SGX Linux drivers (SGX Linux OOT Driver, or SGX Linux DCAP drivers).
> 
> One reference design of solution for this issue, is the SGX Linux PSW's design which had been adapted to be compatible with all variants/legacy versions of SGX Linux kernel support, namely SGX Linux OOT Drivers, SGX DCAP Linux drivers (which had been tracking the SGX Linux Kernel Upstream patches' interfaces) /SGX Linux Kernel Upstream patches. So if following this reference, the solution (compatibility with various driver, and the upcoming SGX Linux kernel upstream patch) might go into somewhere into Graphene's installation process instead of the individual driver's installati

> > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> 
> > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> 
> Just an opinion. I think it should not be the driver or its installer's role to do this (to provide compatibility support for other variants/versions of driver, except its own legacy versions of the same driver.). It should be abstracted higher level above driver.
> 
> Drivers (or SGX Linux kernel upstream patch) usually does not know of other variants of SGX Linux driver. This seems particularly true for the SGX Linux Upstream patches so far, along the way it kept changing its device node and/or interfaces, and it does not knows about its owns' previous versions, neither other SGX Linux drivers (SGX Linux OOT Driver, or SGX Linux DCAP drivers).
> 
> One reference design of solution for this issue, is the SGX Linux PSW's design which had been adapted to be compatible with all variants/legacy versions of SGX Linux kernel support, namely SGX Linux OOT Drivers, SGX DCAP Linux drivers (which had been tracking the SGX Linux Kernel Upstream patches' interfaces) /SGX Linux Kernel Upstream patches. So if following this reference, the solution (compatibility with various driver, and the upcoming SGX Linux kernel upstream patch) might go into somewhere into Graphene's installation process instead of the individual driver's installation.

To be more specific, currently the SGX Linux PSW's installer did this compatibility work. The individual drivers' installation does not know about their owns' previous implementation, or other variants of driver's implementation (including their earlier versions).

2021-01-15 13:23 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @johnvenn)

___
*[Documentation/sgx-intro.rst, line 95 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5Akk4CwwV1fOnttpi:-MR5Akk4CwwV1fOnttpj:b-t9zl61) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L95)):*
> ```reStructuredText
> - SGX driver is upstreamed to linux mainline from 5.11+ (see LKML patches).
>   The current SGX driver upstreamed only supports DCAP. SGX device is exposed
>   as /dev/sgx_enclave at current stage; to make it compatible with older versions
> ```

NAK the idea of making the upstream driver compatible with older versions.
@debin-yang is right that this compat thingy should be done in our code.
Also oot and dcap drivers should adhere to whatever upstream driver does, in fact DCAP driver is maintained exactly this way, and OOT driver is binary-incompatible anyway, so we need to have compat adjustments anyway.
___
*[Documentation/sgx-intro.rst, line 98 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5BOcaAoQclLFTQ6zP:-MR5BOcaAoQclLFTQ6zQ:bp2mjoa) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L98)):*
> ```reStructuredText
>   of SGX driver, user must apply udev rules the first time rebooting the kernel.
>   For information in detail, please refer to:
>   https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/driver/linux/README.kernel.md#udev-rules
> ```

Reference to DCAP repo is wrong. Please write the install instructions here, and please refer to the `.rules` copy in our repo.
___
*[Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzww0b8d-DJb4vFUk1:-MR54WPeETZlcji7zSXU:b-a275ce) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/91-sgx-enclave.rules#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
</blockquote></details>

AFAICT oot driver by default have the device at `666` (https://github.com/intel/linux-sgx-driver/blob/0373e2e8b96d9a261657b7657cb514f003f67094/sgx_main.c#L168) and dcap has this file: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/70f54dba09934381fad79bfe857f172e47819fc7/driver/linux/10-sgx.rules and instruction in README to install it. But the kernel driver has no such thing, because under kernel maintainers `chmod 777` wouldn't fly and udev rules are maintained separately (https://github.com/systemd/systemd/tree/061e9fc5f1abc9d4a338a072803e293bd93c3c3e/rules.d). So this file was lifted from DCAP and, for lack of better idea, added here.

May I reiterate that this is distro business, not ours. The proper way would be to submit a PR against systemd/systemd after 5.11.0 release and wait for distros to carry the patch, but if we'd like to make user's life easier, we can have this in contrib/ and some reference in documentation (not in build system).
___
*[Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR4wk453hXZ56Emrbhr:-MR4wk453hXZ56Emrbhs:b-75lhu5) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Pal/src/host/Linux-SGX/91-sgx-enclave.rules#L2)):*
> ```
> SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> ```

I strongly object to:
- `SYMLINK+=`: We have no business in adding different files/symlinks to host's `/dev`. Instead we should make independently configurable both the path to the header and path to the device itself. Optimally the path to chardev should be `#define`d in the header itself, but this is outside of our control.
- `MODE=`: This is not our decision if SGX should be available to all users or just some of them. I expect distributions to create a group (probably named `sgx`) and have the file `0660` and belonging to said group. Then local admin would add users to this group if they are to be permitted to use SGX on the host. But the group setup would have to happen in configuration/postinstall part of the distro package.
- The sort number of `91-`: Around 80 there are distro overrides, which is already too late, and especially 90+ is reserved for admin and local overrides. Packages usually have the files between 60 and 70, so I'd suggest 65.

As it stands, this is NAK. If you'd like to supply this file, please move it to `contrib/udev-rules.d/65-graphene-sgx.rules` (create the directories) and change mode to 0660. Yes, this will require more work to install and configure, but I don't want `chmod 777` and equivalents in the repo.
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzwmNF-Nup7f_Hvnqe:-MR4tW9N-_m8LboNFjrR:b-t4bnfe) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
</blockquote></details>

Either way, this instruction has no place in this file. It will not age well, because the config will eventually be supplied by distribution (either as standalone file, or likely just added to an existing file).
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5AOstBuj5Yh-6mQ4D:-MR5AOt14P0LAZF5PJz4:bfpb5sw) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Pal/src/host/Linux-SGX/link-intel-driver.py#L69)):*
> ```Python
>                 if not os.path.exists(in_kernel_dev_node):
>                     raise FileNotFoundError
>             except FileNotFoundError:
> ```

Why this convoluted logic? Wouldn't `if os.path.exists(...) and not os.path.exists(...):` suffice?


<!-- Sent from Reviewable.io -->

2021-01-19 02:33 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvHJo1KVDwewmeu-M:-MRNU5Cj0GtWRLqyiHa2:b-3e5ws6) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please let's also keep this version, to support the case where the user doesn't specify any SGX-driver directory (`ISGX_DRIVER_PATH=""`). And here the driver name must be changed to the new `/dev/sgx_enclave`.
</blockquote></details>

udpated.


<!-- Sent from Reviewable.io -->

2021-01-19 02:36 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5AOstBuj5Yh-6mQ4D:-MRNUP9Z4C2xjOp1X5SF:b-cwyi88) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Pal/src/host/Linux-SGX/link-intel-driver.py#L69)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why this convoluted logic? Wouldn't `if os.path.exists(...) and not os.path.exists(...):` suffice?
</blockquote></details>

Both are ok. Just for indent purpose and make the line shorter.


<!-- Sent from Reviewable.io -->

2021-01-19 07:49 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @johnvenn, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRObFdWBmWbPwwEmSLK:-MRObFdWBmWbPwwEmSLL:bfya12b) (no related file):*
@johnvenn Please use Reviewable for reviews and comments, it's much more convenient than normal GitHub functionality. (There is a button "Reviewable" in each PR description.)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRObZiR1EArdqZNHSo3:-MRObZiR1EArdqZNHSo4:b-q2sjkk) (no related file):*
Please address @woju's comments.

---
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvHJo1KVDwewmeu-M:-MROaYOx0R8NHek2wHS4:b-w7mgmj) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L10)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

udpated.
</blockquote></details>

The `sgx_in_kernel.h` option is still missing...
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvnmP-sCiez-kvCib:-MROat-qAqSXSGzKpATE:b-oi6o89) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please keep this, to support the case where the user doesn't specify any SGX-driver directory (`ISGX_DRIVER_PATH=""`).
</blockquote></details>

Why did you change `sgx_in_kernel.h` to `sgx.h`? We only have `sgx_in_kernel.h` in the Graphene repo: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_in_kernel.h


<!-- Sent from Reviewable.io -->

2021-01-20 06:44 UTC, johnvenn commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRObFdWBmWbPwwEmSLK:-MRTXAWEA0P14HoK55PC:bbhjqau) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@johnvenn Please use Reviewable for reviews and comments, it's much more convenient than normal GitHub functionality. (There is a button "Reviewable" in each PR description.)
</blockquote></details>

yes, I have trouble in  accessing this website several days ago, now I solved the issue. 

---


<!-- Sent from Reviewable.io -->

2021-01-20 06:44 UTC, johnvenn commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRObZiR1EArdqZNHSo3:-MRTXKAF24uVN6-iy2Ue:b-5mb2i7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please address @woju's comments.
</blockquote></details>

I will solve it today. 

---


<!-- Sent from Reviewable.io -->

2021-01-20 06:55 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzugUO4uZyz3rhCWF8:-MRNU2On2l0pqlFZKBlu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`For Dcap driver from version 1.10+` -> `For DCAP driver version 1.10+`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 06:55 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzuPWk7s-QJNDzFR1u:-MRTZveQ-Ae6IKRnUKnv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is a trailing space at the end of this line, please remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 06:55 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvkX3CkGdxw_1KM85:-MRNUIydBV05JRYAv3-M:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please keep this, to support older versions of DCAP
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 06:56 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvnmP-sCiez-kvCib:-MRT_1ddAJwmcwjQlsVB:b-kq7p6r) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you change `sgx_in_kernel.h` to `sgx.h`? We only have `sgx_in_kernel.h` in the Graphene repo: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_in_kernel.h
</blockquote></details>

yes, I am aware of this default header file, done to keep it


<!-- Sent from Reviewable.io -->

2021-01-20 06:56 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvnmP-sCiez-kvCib:-MRT_Bsq6CdTtuqpUsiZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L20)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

yes, I am aware of this default header file, done to keep it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 06:57 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5AOstBuj5Yh-6mQ4D:-MRNV-fsC5uL8e1lQlzf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Pal/src/host/Linux-SGX/link-intel-driver.py#L69)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

Both are ok. Just for indent purpose and make the line shorter.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 06:59 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzw1KR422-oe_C3ezA:-MRNVEW8EyzrzRai4bPA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove spaces
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 07:16 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR4wk453hXZ56Emrbhr:-MRTdf1n3rJ85d9-48BV:bvgp13u) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Pal/src/host/Linux-SGX/91-sgx-enclave.rules#L2)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I strongly object to:
- `SYMLINK+=`: We have no business in adding different files/symlinks to host's `/dev`. Instead we should make independently configurable both the path to the header and path to the device itself. Optimally the path to chardev should be `#define`d in the header itself, but this is outside of our control.
- `MODE=`: This is not our decision if SGX should be available to all users or just some of them. I expect distributions to create a group (probably named `sgx`) and have the file `0660` and belonging to said group. Then local admin would add users to this group if they are to be permitted to use SGX on the host. But the group setup would have to happen in configuration/postinstall part of the distro package.
- The sort number of `91-`: Around 80 there are distro overrides, which is already too late, and especially 90+ is reserved for admin and local overrides. Packages usually have the files between 60 and 70, so I'd suggest 65.

As it stands, this is NAK. If you'd like to supply this file, please move it to `contrib/udev-rules.d/65-graphene-sgx.rules` (create the directories) and change mode to 0660. Yes, this will require more work to install and configure, but I don't want `chmod 777` and equivalents in the repo.
</blockquote></details>

ok, working... in progress


<!-- Sent from Reviewable.io -->

2021-01-20 07:21 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzvHJo1KVDwewmeu-M:-MRTenVoAusc2RurAM8w:b-t948zx) ([raw file](https://github.com/oscarlab/graphene/blob/303528131c67f58aeee677397ade9593f222ae88/Pal/src/host/Linux-SGX/link-intel-driver.py#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `sgx_in_kernel.h` option is still missing...
</blockquote></details>

added.


<!-- Sent from Reviewable.io -->

2021-01-20 10:02 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @johnvenn, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUD4QcB5pCFMtX58aO:-MRUD4QcB5pCFMtX58aP:b-5rua0r) (no related file):*
Please don't merge the master branch in your branch. We use the rebase git flow (and **only when absolutely necessary to rebase**). Please check https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.

---
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzw1KR422-oe_C3ezA:-MRUDqBX2HG44vPe69aZ:bfhqml6) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L74)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 11 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUDznVEeYEeSDEwV8z:-MRUDznVEeYEeSDEwV9-:b-6qd2ft) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L11)):*
> ```Python
>         'include/uapi/asm/sgx_oot.h': '/dev/sgx/enclave',  # For Dcap driver 1.6+, but below 1.10
>         'include/sgx_user.h':         '/dev/sgx/enclave',  # For Dcap driver 1.10+
>         'include/uapi/asm/sgx.h':     '/dev/sgx/enclave',  # For upstreamed in-kernel SGX driver, kernel version 5.11+
> ```

Why did you revert back to `/dev/sgx/enclave`? I thought you wanted to add an option for `/dev/sgx_enclave`...
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 20 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUEC_X2CJ40KwvOE5r:-MRUEC_X2CJ40KwvOE5s:bz1aoff) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L20)):*
> ```Python
>       - sgx_user.h for non-DCAP, older version of the driver
>         (https://github.com/intel/linux-sgx-driver)
>       - include/uapi/asm/sgx_oot.h for DCAP 1.6+ version of the driver
> ```

Please append `but below 1.10`
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 24 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUEPoY3V0f3595ZGeO:-MRUEPoY3V0f3595ZGeP:bn1wvu5) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L24)):*
> ```Python
>       - include/sgx_user.h for DCAP 1.10+ version of the driver
>         (https://github.com/intel/SGXDataCenterAttestationPrimitives)
>       - sgx.h for upstreamed SGX in-kernel driver from mainline kernel version 5.11
> ```

Please replace `sgx.h` -> `include/uapi/asm/sgx.h`
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 62 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUEZh70xSIa9pbjnbI:-MRUEZh70xSIa9pbjnbJ:bqq61en) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L62)):*
> ```Python
>         sys.exit(1)
> 
>     if not isgx_driver_path: #using in-kernel SGX driver from kernel version 5.11
> ```

Please remove this added comment, we already explain that we use the in-kernel SGX driver in the comment below


<!-- Sent from Reviewable.io -->

2021-01-20 10:44 UTC, johnvenn commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUD4QcB5pCFMtX58aO:-MRUNtv36kk3ysEoB7qU:b-6kpgtr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't merge the master branch in your branch. We use the rebase git flow (and **only when absolutely necessary to rebase**). Please check https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.
</blockquote></details>

thanks a lot for the advice. Actually I was confusing because since we are now using this reviewable.io, I should not force push the fixes before all comments are resolved. 

---


<!-- Sent from Reviewable.io -->

2021-01-20 11:04 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 20 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUEC_X2CJ40KwvOE5r:-MRUSnJQAR7s2KRmWQha:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please append `but below 1.10`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 11:04 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 24 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUEPoY3V0f3595ZGeO:-MRUSvrE0Xmzhtq3WxdA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `sgx.h` -> `include/uapi/asm/sgx.h`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 11:05 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 62 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUEZh70xSIa9pbjnbI:-MRUT2IoDO5gJcO8zKMR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this added comment, we already explain that we use the in-kernel SGX driver in the comment below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 11:05 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzw1KR422-oe_C3ezA:-MRURP0P9isXomNwXKJX:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-01-20 11:07 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 95 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5Akk4CwwV1fOnttpi:-MRTd5ihAn0c3AzZBHgY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L95)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

NAK the idea of making the upstream driver compatible with older versions.
@debin-yang is right that this compat thingy should be done in our code.
Also oot and dcap drivers should adhere to whatever upstream driver does, in fact DCAP driver is maintained exactly this way, and OOT driver is binary-incompatible anyway, so we need to have compat adjustments anyway.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 15:56 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR4wk453hXZ56Emrbhr:-MRVVdye682PiyQhdFeU:b9rxnfn) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Pal/src/host/Linux-SGX/91-sgx-enclave.rules#L2)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

ok, working... in progress
</blockquote></details>

under testing


<!-- Sent from Reviewable.io -->

2021-01-20 15:57 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 11 at r3](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUDznVEeYEeSDEwV8z:-MRUOrgf-jYaYCmShBk2:b-cxnnxw) ([raw file](https://github.com/oscarlab/graphene/blob/d0111217ca11c97e0ee23cb32f4b6895f798431b/Pal/src/host/Linux-SGX/link-intel-driver.py#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you revert back to `/dev/sgx/enclave`? I thought you wanted to add an option for `/dev/sgx_enclave`...
</blockquote></details>

Per woju's comment, I will keep /dev/sgx_enclave, under testing


<!-- Sent from Reviewable.io -->

2021-01-20 16:29 UTC, johnvenn commented
> > > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> > 
> > 
> > > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> > 
> > 
> > Just an opinion. I think it should not be the driver or its installer's role to do this (to provide compatibility support for other variants/versions of driver, except its own legacy versions of the same driver.). It should be abstracted higher level above driver.
> > Drivers (or SGX Linux kernel upstream patch) usually does not know of other variants of SGX Linux driver. This seems particularly true for the SGX Linux Upstream patches so far, along the way it kept changing its device node and/or interfaces, and it does not knows about its owns' previous versions, neither other SGX Linux drivers (SGX Linux OOT Driver, or SGX Linux DCAP drivers).
> > One reference design of solution for this issue, is the SGX Linux PSW's design which had been adapted to be compatible with all variants/legacy versions of SGX Linux kernel support, namely SGX Linux OOT Drivers, SGX DCAP Linux drivers (which had been tracking the SGX Linux Kernel Upstream patches' interfaces) /SGX Linux Kernel Upstream patches. So if following this reference, the solution (compatibility with various driver, and the upcoming SGX Linux kernel upstream patch) might go into somewhere into Graphene's installation process instead of the individual driver's installati
> 
> > > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> > 
> > 
> > > Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1 (raw file):
> > > SUBSYSTEM=="misc",KERNEL=="enclave",MODE="0666"
> > > SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0666",SYMLINK+="sgx/enclave"
> > > SUBSYSTEM=="sgx",KERNEL=="sgx/enclave",MODE="0666"
> > > Why is this file needed? Isn't it the responsibility of the Intel SGX driver to do all these udev rules during installation?
> > > Actually, isn't it the SGX driver installation procedure that does this? Like, why would the user have to do this on a properly set up Linux system?
> > > [Xiangping]: I agree with you, it is the driver installation procedure that should do this, but this step is not yet fixed in kernel. As an amendment on this transition, we need to provide instruction to users. This extra step can be omitted when in-kernel driver includes this step.
> > 
> > 
> > Just an opinion. I think it should not be the driver or its installer's role to do this (to provide compatibility support for other variants/versions of driver, except its own legacy versions of the same driver.). It should be abstracted higher level above driver.
> > Drivers (or SGX Linux kernel upstream patch) usually does not know of other variants of SGX Linux driver. This seems particularly true for the SGX Linux Upstream patches so far, along the way it kept changing its device node and/or interfaces, and it does not knows about its owns' previous versions, neither other SGX Linux drivers (SGX Linux OOT Driver, or SGX Linux DCAP drivers).
> > One reference design of solution for this issue, is the SGX Linux PSW's design which had been adapted to be compatible with all variants/legacy versions of SGX Linux kernel support, namely SGX Linux OOT Drivers, SGX DCAP Linux drivers (which had been tracking the SGX Linux Kernel Upstream patches' interfaces) /SGX Linux Kernel Upstream patches. So if following this reference, the solution (compatibility with various driver, and the upcoming SGX Linux kernel upstream patch) might go into somewhere into Graphene's installation process instead of the individual driver's installation.
> 
> To be more specific, currently the SGX Linux PSW's installer did this compatibility work. The individual drivers' installation does not know about their owns' previous implementation, or other variants of driver's implementation (including their earlier versions). And when release a new version of SGX PSW, we want the PSW to work fine on an existing SGX Linux platform which could have been installed with earlier variants of driver (could be SGX Linux OOT, SGX Linux DCAP, or SGX Linux kernel upstream patch candidates). This similar use case should apply to Graphene SGX too. (Courtesy to @hyjiang's advice on this.)

thanks Debin for the input.

Per my understanding there are 2 ways applying this:
1. by linux distros, add sgx-rules in systemd repo as mentioned in Readme.kernel.md in dcap driver(by Haitao), so that the existing user space application don't need to do any change. But this process is complex. And you are right, it shouldn't be the distro's responsibility to make it. 
2. by graphene code, graphene uses the MACRO "ISGX_FILE" for SGX device, the PR here is to support ISGX_FILE --> "/dev/sgx_enclave" as the upstreamed in-kernel SGX node, and add notes for the advice on granting access "RW" to SGX node.

2021-01-20 16:30 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR4wk453hXZ56Emrbhr:-MRVcUt_9NuimiqtvLfh:b-6df1dx) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Pal/src/host/Linux-SGX/91-sgx-enclave.rules#L2)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

under testing
</blockquote></details>

I will also update the document sgx-intro.rst per your comment.


<!-- Sent from Reviewable.io -->

2021-01-22 05:23 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzwmNF-Nup7f_Hvnqe:-MRcY3kSAk4sS7zoTisD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L71)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Either way, this instruction has no place in this file. It will not age well, because the config will eventually be supplied by distribution (either as standalone file, or likely just added to an existing file).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 05:24 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 98 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5BOcaAoQclLFTQ6zP:-MRcY8958x5655vF6pcp:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Reference to DCAP repo is wrong. Please write the install instructions here, and please refer to the `.rules` copy in our repo.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-01-22 05:24 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/91-sgx-enclave.rules, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzww0b8d-DJb4vFUk1:-MRcYAzHDYPYyH02rBRS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/91-sgx-enclave.rules#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

AFAICT oot driver by default have the device at `666` (https://github.com/intel/linux-sgx-driver/blob/0373e2e8b96d9a261657b7657cb514f003f67094/sgx_main.c#L168) and dcap has this file: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/70f54dba09934381fad79bfe857f172e47819fc7/driver/linux/10-sgx.rules and instruction in README to install it. But the kernel driver has no such thing, because under kernel maintainers `chmod 777` wouldn't fly and udev rules are maintained separately (https://github.com/systemd/systemd/tree/061e9fc5f1abc9d4a338a072803e293bd93c3c3e/rules.d). So this file was lifted from DCAP and, for lack of better idea, added here.

May I reiterate that this is distro business, not ours. The proper way would be to submit a PR against systemd/systemd after 5.11.0 release and wait for distros to carry the patch, but if we'd like to make user's life easier, we can have this in contrib/ and some reference in documentation (not in build system).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 05:59 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 98 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5BOcaAoQclLFTQ6zP:-MRcevzd4ZPR9RO-luEd:bpoog2j) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

done
</blockquote></details>

Per your advice, I tried to add contrib/udev-rules.d/65-graphene-sgx.rules but failed. So I just dump the content of the file into document sgx-intro.rst.


<!-- Sent from Reviewable.io -->

2021-01-25 02:49 UTC, johnvenn commented
@dimakuv @woju hi, the update is done, could you help review r4?

2021-01-25 09:24 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @debin-yang, @johnvenn, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRUD4QcB5pCFMtX58aO:-MRslgkICoU8zH7_Mf_2:b-65he94) (no related file):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

thanks a lot for the advice. Actually I was confusing because since we are now using this reviewable.io, I should not force push the fixes before all comments are resolved. 
</blockquote></details>

You're welcome :) No problem, this happens.

---
___
*[Documentation/sgx-intro.rst, line 98 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5BOcaAoQclLFTQ6zP:-MRslvtOAvoPek7D7pW3:b-qpn002) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

Per your advice, I tried to add contrib/udev-rules.d/65-graphene-sgx.rules but failed. So I just dump the content of the file into document sgx-intro.rst.
</blockquote></details>

OK, this looks fine to me.
___
*[Documentation/sgx-intro.rst, line 96 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRslzcq602KWtj0KltT:-MRslzcq602KWtj0KltU:bdvjamr) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L96)):*
> ```reStructuredText
>   The current SGX driver upstreamed only supports DCAP. SGX device is exposed
>   as /dev/sgx_enclave in linux kernel from 5.11+ instead of /dev/sgx/enclave as 
>   the out-of-tree(OOT) SGX driver does; if user wants the in-kernel tree driver 
> ```

You have a trailing space in this line and the previous line. Please remove.
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MRsmPwH44-0wBpLZZ7J:bavz2ap) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
> ```reStructuredText
>   # cat > /etc/udev/rules.d/65-graphene-sgx.rules << EOF
>   SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0660",SYMLINK+="sgx/enclave"
>   # udevadm trigger
> ```

Firstly, you forgot to add `EOF` at the end. Secondly, You should use the correct RestructedText format.

Please change to this:
```
  compatible with the OOT SGX driver, you must apply udev rules as root user
  for remapping::

      # cat > /etc/udev/rules.d/65-graphene-sgx.rules <<EOF
      SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0660",SYMLINK+="sgx/enclave"
      EOF
      # udevadm trigger
```
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzugUO4uZyz3rhCWF8:-MRsoIAj7bo2UOcBmgG_:b-62bi3l) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L9)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. What I meant by the comment is that I want you to capitalize `Dcap` -> `DCAP`. Please fix this.
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 36 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRspyPHCLDgCiftQr-Y:-MRspyPHCLDgCiftQr-Z:b-omdsly) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L36)):*
> ```Python
>                 print('Could not find dev {!r}'.format(dev_path), file=sys.stderr)
>                 sys.exit(1)
>             else:
> ```

I don't like this change. Sometimes we want to build Graphene on a non-SGX machine (just for testing) or before the SGX driver is enabled on Linux. Your change fails Graphene build if it doesn't find a working SGX driver.

Could you just remove this change? Why do you need it?
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 67 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqV4K6X-mcRbW83xG:-MRsqV4K6X-mcRbW83xH:bgkhu87) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L67)):*
> ```Python
>             'For upstreamed in-kernel driver, kernel version 5.11+'
>             'You need to specify ISGX_DRIVER_PATH, '
>             'default is /usr/src/linux-headers-$(uname -r)/arch/x86',
> ```

I don't think your newly added comment is needed. I'm pretty sure that our 32+ version of the header file works also with the mainlined version of the driver in 5.11+. Thus, there is no need for this additional details. Everything just works.

Why did you want to add this comment? Did something break on your 5.11 kernel when you just specified `ISGX_DRIVER_PATH=""`?
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 70 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqpAO4BTPWq4tPeVM:-MRsqpAO4BTPWq4tPeVN:br60ply) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L70)):*
> ```Python
>             file=sys.stderr)
>         sys.exit(1)
>     
> ```

Please remove the spaces, it must be just an empty line


<!-- Sent from Reviewable.io -->

2021-01-26 17:16 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @debin-yang, @dimakuv, and @johnvenn)

___
*[Documentation/sgx-intro.rst, line 95 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5Akk4CwwV1fOnttpi:-MRzfyfX8VGazLfxOPYo:b5h5pxy) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L95)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, this is still wrong. IIUC we don't need "remapping" (symlinking), since you specified the correct path in `link-intel-driver.py`. I'd cut the sentence to just: "Since kernel 5.11, SGX device is exposed as /dev/sgx_enclave."
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MRzb9WdCxG90KI3T1uU:b-wo4ama) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Firstly, you forgot to add `EOF` at the end. Secondly, You should use the correct RestructedText format.

Please change to this:
```
  compatible with the OOT SGX driver, you must apply udev rules as root user
  for remapping::

      # cat > /etc/udev/rules.d/65-graphene-sgx.rules <<EOF
      SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0660",SYMLINK+="sgx/enclave"
      EOF
      # udevadm trigger
```
</blockquote></details>

Is `SYMLINK+=` still necessary? IIUC you have correct path (`/dev/sgx_enclave`) in `link-intel-driver.py`. ISTM only `MODE=` is relevant here, and could also use explicit group:

```rst
::
   # groupadd -r sgx
   # gpasswd -a USERNAME sgx
   # cat > /etc/udev/rules.d/65-graphene-sgx.rules <<EOF
   SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0660",GROUP="sgx"
   # udevadm trigger
```

Also, what about `/dev/sgx_provision`? Is is also relevant/necessary/appropriate to add here?
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 67 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqV4K6X-mcRbW83xG:-MRzeBS47cjQeOlUKf4F:b-o048ok) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think your newly added comment is needed. I'm pretty sure that our 32+ version of the header file works also with the mainlined version of the driver in 5.11+. Thus, there is no need for this additional details. Everything just works.

Why did you want to add this comment? Did something break on your 5.11 kernel when you just specified `ISGX_DRIVER_PATH=""`?
</blockquote></details>

@dimakuv If (when) the upstream header would be released (or available as package?) I'd consider removing our copy of `sgx.h` and make it so that empty ISGX_DRIVER_PATH means autodetection as described here.

I think it's too early to do this in this PR, but maybe I'm wrong? Maybe the people who actually use inkernel driver would like such a change, which would eliminate confusion around our vendored header.


<!-- Sent from Reviewable.io -->

2021-01-27 02:31 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 36 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRspyPHCLDgCiftQr-Y:-MS0fUCK-GBfcOWQQ6U6:b-1yn9y) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this change. Sometimes we want to build Graphene on a non-SGX machine (just for testing) or before the SGX driver is enabled on Linux. Your change fails Graphene build if it doesn't find a working SGX driver.

Could you just remove this change? Why do you need it?
</blockquote></details>

ok, thanks for the comment, will correct it.


<!-- Sent from Reviewable.io -->

2021-01-27 07:16 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 70 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqpAO4BTPWq4tPeVM:-MS1gi_E3g5W6YFDHxI1:b-gxra0o) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the spaces, it must be just an empty line
</blockquote></details>

will update. done.


<!-- Sent from Reviewable.io -->

2021-01-27 07:16 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2084#-MQzugUO4uZyz3rhCWF8:-MS1gmhb7T3d58NkSqAo:b-458sk) ([raw file](https://github.com/oscarlab/graphene/blob/0e8055885d1c42b37f437583dea6f3a1007189a8/Pal/src/host/Linux-SGX/link-intel-driver.py#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done. What I meant by the comment is that I want you to capitalize `Dcap` -> `DCAP`. Please fix this.
</blockquote></details>

done, will update


<!-- Sent from Reviewable.io -->

2021-01-27 07:17 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 70 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqpAO4BTPWq4tPeVM:-MS1h-Z27kjn8gfSK8pa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L70)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

will update. done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-27 07:20 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 96 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRslzcq602KWtj0KltT:-MS1hdBqC4Nlf4OkjBuL:baj6b6t) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have a trailing space in this line and the previous line. Please remove.
</blockquote></details>

Done.will be updated


<!-- Sent from Reviewable.io -->

2021-01-27 07:20 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 95 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5Akk4CwwV1fOnttpi:-MS1hgVZ7wlwZScJaiQC:b-r57ky5) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L95)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this is still wrong. IIUC we don't need "remapping" (symlinking), since you specified the correct path in `link-intel-driver.py`. I'd cut the sentence to just: "Since kernel 5.11, SGX device is exposed as /dev/sgx_enclave."
</blockquote></details>

so @woju, you mean here we don't need to provide suggestions for users to do the remapping to be compatible with OOT driver?


<!-- Sent from Reviewable.io -->

2021-01-27 07:21 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 95 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5Akk4CwwV1fOnttpi:-MS1hqNgBNq0d7yluX1l:buj3e48) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L95)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

so @woju, you mean here we don't need to provide suggestions for users to do the remapping to be compatible with OOT driver?
</blockquote></details>

@woju, do you mean we don't need to provide 65-graphene-sgx.rules to user?


<!-- Sent from Reviewable.io -->

2021-01-27 07:29 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 36 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRspyPHCLDgCiftQr-Y:-MS1jsdA9Y3YZpYBUqvs:b-7rl0jd) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L36)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

ok, thanks for the comment, will correct it.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2021-01-27 07:39 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 67 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqV4K6X-mcRbW83xG:-MS1lVIAC-HJjCfyk0zI:b-nb01fa) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L67)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@dimakuv If (when) the upstream header would be released (or available as package?) I'd consider removing our copy of `sgx.h` and make it so that empty ISGX_DRIVER_PATH means autodetection as described here.

I think it's too early to do this in this PR, but maybe I'm wrong? Maybe the people who actually use inkernel driver would like such a change, which would eliminate confusion around our vendored header.
</blockquote></details>

in my opinion, suppose in future people will use the upstreamed SGX driver for graphene and they will need to use the sgx.h from kernel headers in linux-header-$(uname-r), so here we should point out explicitly to avoid confusion. Of course, if user doesn't specify any PATH, he/she can use the default header located at the current dir of this script.


<!-- Sent from Reviewable.io -->

2021-01-27 07:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @debin-yang, @dimakuv, and @johnvenn)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS1nc1HEEWoX2MVbuAF:-MS1nc1IB9jPqKJedsTM:b-6hxvuh) (no related file):*
@johnvenn I don't see any new changes on this PR. Did you forget to push your changes to the GitHub repo?

---


<!-- Sent from Reviewable.io -->

2021-01-27 08:25 UTC, johnvenn commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS1nc1HEEWoX2MVbuAF:-MS1w_OY9xOwoCyhOmKE:b-wd6rao) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@johnvenn I don't see any new changes on this PR. Did you forget to push your changes to the GitHub repo?
</blockquote></details>

not yet, I still have one comment to solve. will push after a while 

---


<!-- Sent from Reviewable.io -->

2021-01-27 08:32 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS1y20sC1_HDSKFpWgT:b91ii74) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Is `SYMLINK+=` still necessary? IIUC you have correct path (`/dev/sgx_enclave`) in `link-intel-driver.py`. ISTM only `MODE=` is relevant here, and could also use explicit group:

```rst
::
   # groupadd -r sgx
   # gpasswd -a USERNAME sgx
   # cat > /etc/udev/rules.d/65-graphene-sgx.rules <<EOF
   SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0660",GROUP="sgx"
   # udevadm trigger
```

Also, what about `/dev/sgx_provision`? Is is also relevant/necessary/appropriate to add here?
</blockquote></details>

I will add /dev/sgx_provision here. 


<!-- Sent from Reviewable.io -->

2021-01-27 08:36 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS1yrSK77ARiSBgLJRP:bz9vs46) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

I will add /dev/sgx_provision here. 
</blockquote></details>

and this is a recommendation if user wants to be compatible with the OOT driver. If they still want to access the SGX device using legacy SGX node. 


<!-- Sent from Reviewable.io -->

2021-01-27 08:40 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 95 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5Akk4CwwV1fOnttpi:-MS1zXzMDmZQVHBe0Xwr:bi7r5cf) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L95)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

@woju, do you mean we don't need to provide 65-graphene-sgx.rules to user?
</blockquote></details>

But in case user wants the their application be compatible with the legacy OOT driver, the remapping is just recommended for this compatibility.


<!-- Sent from Reviewable.io -->

2021-01-27 09:15 UTC, johnvenn commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS1nc1HEEWoX2MVbuAF:-MS26ztNEmjWyUajg6It:b-fm8amu) (no related file):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

not yet, I still have one comment to solve. will push after a while 
</blockquote></details>

done with r5.

---


<!-- Sent from Reviewable.io -->

2021-01-27 09:50 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @debin-yang and @johnvenn)

___
*[Documentation/sgx-intro.rst, line 96 at r5](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS2COVu8lQ1fSOa8c0d:-MS2COVvDduNks1LpwtZ:bgwts21) ([raw file](https://github.com/oscarlab/graphene/blob/257347a543dfd38cae345f68c54adc9a19981968/Documentation/sgx-intro.rst#L96)):*
> ```reStructuredText
>   The current SGX driver upstreamed only supports DCAP. SGX device is exposed
>   as /dev/sgx_enclave and /dev/sgx_provision in linux kernel from 5.11+.
>   The following udev rules are recommended for users to access the SGX node:
> ```

Please use the Restructured Text formatting. Right now, your instructions will look like gibberish on the web page.

Please change to this (note the double colon at the end of the line and the indentation!):
```
The following udev rules are recommended for users to access the SGX node::

      # groupadd -r sgx
      # gpasswd -a USERNAME sgx
      # groupadd -r sgx_prv
      # gpasswd -a USERNAME sgx_prv
      # cat > /etc/udev/rules.d/65-graphene-sgx.rules << EOF
      SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0660",GROUP="sgx"
      SUBSYSTEM=="misc",KERNEL=="sgx_provision",MODE="0660",GROUP="sgx_prv"
      EOF
      # udevadm trigger
```
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 67 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqV4K6X-mcRbW83xG:-MS2DXtk2f6fzj10Smt9:bwjsfc4) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L67)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

in my opinion, suppose in future people will use the upstreamed SGX driver for graphene and they will need to use the sgx.h from kernel headers in linux-header-$(uname-r), so here we should point out explicitly to avoid confusion. Of course, if user doesn't specify any PATH, he/she can use the default header located at the current dir of this script.
</blockquote></details>

OK, let's keep this comment.
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 12 at r5](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS2CzWY12wobnac822t:-MS2CzWY12wobnac822u:bloiac8) ([raw file](https://github.com/oscarlab/graphene/blob/257347a543dfd38cae345f68c54adc9a19981968/Pal/src/host/Linux-SGX/link-intel-driver.py#L12)):*
> ```Python
>         'include/sgx_user.h':         '/dev/sgx/enclave',  # For DCAP driver 1.10+
>         'include/uapi/asm/sgx.h':     '/dev/sgx_enclave',  # For upstreamed in-kernel SGX driver, kernel version 5.11+
>         'sgx_in_kernel.h':            '/dev/sgx/enclave',  # By default, using sgx_in_kernel.h in current dir of this script 
> ```

Still a space at the end of this line
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 63 at r5](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS2DZHTE6oJBG2XkbKR:-MS2DZHTE6oJBG2XkbKS:b-7hh6wm) ([raw file](https://github.com/oscarlab/graphene/blob/257347a543dfd38cae345f68c54adc9a19981968/Pal/src/host/Linux-SGX/link-intel-driver.py#L63)):*
> ```Python
>             'For upstreamed in-kernel driver, kernel version 5.11+'
>             'You need to specify ISGX_DRIVER_PATH, '
>             'default is /usr/src/linux-headers-$(uname -r)/arch/x86',
> ```

Let's make this comment more readable. Please change to this:
```
        print(
            'ISGX_DRIVER_PATH environment variable is undefined. You can define\n'
            'ISGX_DRIVER_PATH="" to use the in-kernel driver\'s C header from version\n'
            '32 (bundled with Graphene but NOT upstreamed) . For upstreamed\n'
            'in-kernel driver (if you are using Linux kernel 5.11+), define\n'
            'ISGX_DRIVER_PATH="/usr/src/linux-headers-$(uname -r)/arch/x86".',
            file=sys.stderr)
```


<!-- Sent from Reviewable.io -->

2021-01-27 15:16 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @johnvenn)

___
*[Documentation/sgx-intro.rst, line 95 at r2](https://reviewable.io/reviews/oscarlab/graphene/2084#-MR5Akk4CwwV1fOnttpi:-MS3OvDCDXjmSL0tL8BH:b-rc4hcv) ([raw file](https://github.com/oscarlab/graphene/blob/76823ed4f875255bc5ab5bbfbb9d3518b14aacb5/Documentation/sgx-intro.rst#L95)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

But in case user wants the their application be compatible with the legacy OOT driver, the remapping is just recommended for this compatibility.
</blockquote></details>

For the forseeable future we probably do need to provide this file, at least for `MODE=`. I hope someday this file would be provided by udev upstream.
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS3LvUHEAAgjiyG8E9-:b-et235p) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

and this is a recommendation if user wants to be compatible with the OOT driver. If they still want to access the SGX device using legacy SGX node. 
</blockquote></details>

About `/dev/sgx_provision`: that was a honest question, because I'm not familiar with intricacies of SGX drivers and their userspace APIs. Is it really necessary? I can't find any reference to this file in graphene, and by cursory reading of https://elixir.bootlin.com/linux/v5.11-rc5/source/arch/x86/kernel/cpu/sgx/driver.c#L136 this device doesn't do anything, but I might have missed something.

So my question still stands: is this chardev necessary or relevant?
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 67 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsqV4K6X-mcRbW83xG:-MS3O_eW4SP6Esz9xlVE:b-yentla) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Pal/src/host/Linux-SGX/link-intel-driver.py#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, let's keep this comment.
</blockquote></details>

Yeah, either here or in `Documentation/` is OK.


<!-- Sent from Reviewable.io -->

2021-01-28 06:05 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS6a1Y-3lEPJLArMHvB:b-oi7e4q) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

About `/dev/sgx_provision`: that was a honest question, because I'm not familiar with intricacies of SGX drivers and their userspace APIs. Is it really necessary? I can't find any reference to this file in graphene, and by cursory reading of https://elixir.bootlin.com/linux/v5.11-rc5/source/arch/x86/kernel/cpu/sgx/driver.c#L136 this device doesn't do anything, but I might have missed something.

So my question still stands: is this chardev necessary or relevant?
</blockquote></details>

for graphene, currently I don't see any usage of sgx_provision, but this is the SGX node provided by upstream, in case in future, someone would use it, we should state it here. 


<!-- Sent from Reviewable.io -->

2021-01-28 07:05 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS6kc2I3jLHD2RSu97u:b-pcebjl) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

for graphene, currently I don't see any usage of sgx_provision, but this is the SGX node provided by upstream, in case in future, someone would use it, we should state it here. 
</blockquote></details>

/dev/sgx_provision is a file handler for SET_ATTRIBUTE IOC. For provisioning enclaves that require to access the provision key, it need to open this file handler to notify the driver, the owner of the provisioning enclave need to be granted as the right permission and the right group (sgx_prv) for this operation.  


<!-- Sent from Reviewable.io -->

2021-01-28 07:06 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS6o5l52gLZ-X681bKA:bgrzng7) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

/dev/sgx_provision is a file handler for SET_ATTRIBUTE IOC. For provisioning enclaves that require to access the provision key, it need to open this file handler to notify the driver, the owner of the provisioning enclave need to be granted as the right permission and the right group (sgx_prv) for this operation.  
</blockquote></details>

here's the detail:https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/driver/linux#process-permissions-and-flow


<!-- Sent from Reviewable.io -->

2021-01-28 07:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @johnvenn and @woju)

___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS6xeB623sjcWe23gc1:b3e3nkq) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

here's the detail:https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/driver/linux#process-permissions-and-flow
</blockquote></details>

Thinking about it, there is **no** usage for `sgx_provision` in Graphene. Graphene is not in the business of provisioning SGX information. Graphene doesn't do anything with the Provisioning Enclave, it doesn't even use it. So we can actually remove this part about `sgx_provision` from this document.


<!-- Sent from Reviewable.io -->

2021-01-28 08:04 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS70FV88TpZQU3X5sS4:b-8qbpft) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thinking about it, there is **no** usage for `sgx_provision` in Graphene. Graphene is not in the business of provisioning SGX information. Graphene doesn't do anything with the Provisioning Enclave, it doesn't even use it. So we can actually remove this part about `sgx_provision` from this document.
</blockquote></details>

sure, since currently nowhere in graphese uses the node, I will remove it. 


<!-- Sent from Reviewable.io -->

2021-01-28 08:47 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 12 at r5](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS2CzWY12wobnac822t:-MS7A9ngCrD7g6tI01Xk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/257347a543dfd38cae345f68c54adc9a19981968/Pal/src/host/Linux-SGX/link-intel-driver.py#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still a space at the end of this line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-28 08:47 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 63 at r5](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS2DZHTE6oJBG2XkbKR:-MS7ACix7aUIPpt7mUBL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/257347a543dfd38cae345f68c54adc9a19981968/Pal/src/host/Linux-SGX/link-intel-driver.py#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's make this comment more readable. Please change to this:
```
        print(
            'ISGX_DRIVER_PATH environment variable is undefined. You can define\n'
            'ISGX_DRIVER_PATH="" to use the in-kernel driver\'s C header from version\n'
            '32 (bundled with Graphene but NOT upstreamed) . For upstreamed\n'
            'in-kernel driver (if you are using Linux kernel 5.11+), define\n'
            'ISGX_DRIVER_PATH="/usr/src/linux-headers-$(uname -r)/arch/x86".',
            file=sys.stderr)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-28 08:47 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 96 at r5](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS2COVu8lQ1fSOa8c0d:-MS7AHxn1vTmKBaxCyYd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/257347a543dfd38cae345f68c54adc9a19981968/Documentation/sgx-intro.rst#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use the Restructured Text formatting. Right now, your instructions will look like gibberish on the web page.

Please change to this (note the double colon at the end of the line and the indentation!):
```
The following udev rules are recommended for users to access the SGX node::

      # groupadd -r sgx
      # gpasswd -a USERNAME sgx
      # groupadd -r sgx_prv
      # gpasswd -a USERNAME sgx_prv
      # cat > /etc/udev/rules.d/65-graphene-sgx.rules << EOF
      SUBSYSTEM=="misc",KERNEL=="sgx_enclave",MODE="0660",GROUP="sgx"
      SUBSYSTEM=="misc",KERNEL=="sgx_provision",MODE="0660",GROUP="sgx_prv"
      EOF
      # udevadm trigger
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-28 08:47 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS7AJkg8Bt5lYVXAdsD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

sure, since currently nowhere in graphese uses the node, I will remove it. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-28 09:37 UTC, hyjiang commented
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)_ status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @johnvenn and @woju)
> 
> _[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS6xeB623sjcWe23gc1:b3e3nkq) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):_
> 
> Previously, johnvenn (xiangping-INTEL) wrote…
> Thinking about it, there is **no** usage for `sgx_provision` in Graphene. Graphene is not in the business of provisioning SGX information. Graphene doesn't do anything with the Provisioning Enclave, it doesn't even use it. So we can actually remove this part about `sgx_provision` from this document.

In SGX attestation, Intel(R) signed PCE (Provisioning Certificate Enclave) will be used, which requires provisioning bit access. So if Graphene wants to do SGX attestation, it means it would use PCE anyway. 
For example, there are 2 modes for ECDSA attestation:
 - In-Proc mode, user's process will link DCAP library
 - Out-Of-Process mode, user's process will call Intel(R) AESM to do attestation 

In previous SGX releases, both 'In-Proc' and 'Out-Of-Proc' modes can be used by any user by default. But in upcoming SGX release, we aligned the 'provision' configuration with upstream SGX driver. Then 'In-Proc' mode needs user to configure the permission by himself. 
So when Graphene uses `In-Proc` mode without Root privilege, then user needs to configure the permission.

2021-01-28 09:57 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS7KoFf-2xlvno7b8tN:bo6u93b) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, hyjiang (HY) wrote…</i></summary><blockquote>

In SGX attestation, Intel(R) signed PCE (Provisioning Certificate Enclave) will be used, which requires provisioning bit access. So if Graphene wants to do SGX attestation, it means it would use PCE anyway.  For example, there are 2 modes for ECDSA attestation:
 - In-Proc mode, user's process will link DCAP library
 - Out-Of-Process mode, user's process will call Intel(R) AESM to do attestation 

In previous SGX releases, both 'In-Proc' and 'Out-Of-Proc' modes can be used by any user by default. But in upcoming SGX release, we aligned the 'provision' configuration with upstream SGX driver. Then 'In-Proc' mode needs user to configure the permission by himself.  So when Graphene uses `In-Proc` mode without Root privilege, then user needs to configure the permission.  
</blockquote></details>

per discussion with hongyan, I still think /dev/sgx_provision is needed, and there should be enhancements in load_enclave file as to open the device, you can refer to code in intel-sgx repo: https://github.com/intel/linux-sgx/blob/master/psw/enclave_common/sgx_enclave_common.cpp, ioctl request code SGX_IOC_ENCLAVE_SET_ATTRIBUTE_IN_KERNEL in function enclave_create()


<!-- Sent from Reviewable.io -->

2021-01-28 10:15 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @johnvenn and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MS7UDQbCPKBMrvGhzgG:-MS7UDQbCPKBMrvGhzgH:bchd1ki) (no related file):*
Thanks for this PR, I'm happy with it now.

@woju Could you do another round of review?

---
___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS7TZ2v6Lw8Bz305HsT:ba59kr2) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

per discussion with hongyan, I still think /dev/sgx_provision is needed, and there should be enhancements in load_enclave file as to open the device, you can refer to code in intel-sgx repo: https://github.com/intel/linux-sgx/blob/master/psw/enclave_common/sgx_enclave_common.cpp, ioctl request code SGX_IOC_ENCLAVE_SET_ATTRIBUTE_IN_KERNEL in function enclave_create()
</blockquote></details>

Thank you @hyjiang , this is very good to know! Agreed, we will need `/dev/sgx_provision` then.


<!-- Sent from Reviewable.io -->

2021-01-28 14:05 UTC, woju submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 1 unresolved discussion (waiting on @johnvenn)

___
*[Documentation/sgx-intro.rst, line 101 at r4](https://reviewable.io/reviews/oscarlab/graphene/2084#-MRsmPwG7gdl69OTzbb0:-MS8IvLg0mFMPBOEj_3Q:bg6zxn4) ([raw file](https://github.com/oscarlab/graphene/blob/a7d4da93e28e0779c996833b46f397b2bf1c7647/Documentation/sgx-intro.rst#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thank you @hyjiang , this is very good to know! Agreed, we will need `/dev/sgx_provision` then.
</blockquote></details>

OK. Thanks for explanation.


<!-- Sent from Reviewable.io -->

2021-01-29 01:37 UTC, johnvenn commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2021-02-01 02:13 UTC, mkow requested changes
> Reviewed 1 of 3 files at r4, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 3 unresolved discussions (waiting on @johnvenn)

___
*[Documentation/sgx-intro.rst, line 95 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQJypK2MW1IVulZBx1:-MSQJypK2MW1IVulZBx2:be161pe) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L95)):*
> ```reStructuredText
> - SGX driver is upstreamed to linux mainline from 5.11+ (see LKML patches).
>   The current SGX driver upstreamed only supports DCAP. SGX device is exposed
>   as /dev/sgx_enclave and /dev/sgx_provision in linux kernel from 5.11+.
> ```

I don't like the wording of this whole point, it's hard to read and repetitive. Something like this should be better:

```
- SGX support was upstreamed to the Linux mainline starting from 5.11.
  It currently supports only DCAP attestation. The driver is accessible through
  /dev/sgx_enclave and /dev/sgx_provision.
```

(plus leaving that "The following [...]" sentence as is, it's good in the current form)
___
*[Documentation/sgx-intro.rst, line 98 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQId1uCU8UidZo4Ijd:-MSQId1v9CuDdVu241te:b-1r2s1p) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L98)):*
> ```reStructuredText
>   The following udev rules are recommended for users to access the SGX node::
> 
>     # groupadd -r sgx
> ```

This whole block gets highlighted treating `#` as a comment marker, so the resulting HTML looks misleading (as these lines were comments). Please fix.
Also, I'm not sure which syntax highlighting scheme is selected by default, but it's probably Python, not sh, so you should use `.. code-block:: sh`.
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 77 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQHkeEDOaUHY7c7Q-S:-MSQHkeF7wGwcbQWE5T_:b-ikz1dq) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Pal/src/host/Linux-SGX/link-intel-driver.py#L77)):*
> ```Python
>         DRIVER_SGX_H=header_path,
>         ISGX_FILE=dev_path,
>         DEFINE_DCAP=('#define SGX_DCAP 1' if dev_path != '/dev/isgx'  else '')
> ```

please fix the double space


<!-- Sent from Reviewable.io -->

2021-02-01 03:53 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 98 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQId1uCU8UidZo4Ijd:-MSQi9f45J8_SK6Vt0a_:bljbemv) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This whole block gets highlighted treating `#` as a comment marker, so the resulting HTML looks misleading (as these lines were comments). Please fix.
Also, I'm not sure which syntax highlighting scheme is selected by default, but it's probably Python, not sh, so you should use `.. code-block:: sh`.
</blockquote></details>

I used "make html man" command to verify my original change, it's ok as I opened the file using firefox. Not sure what browser you are using to open this file.


<!-- Sent from Reviewable.io -->

2021-02-01 04:18 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 98 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQId1uCU8UidZo4Ijd:-MSQnyJo1l7vQQdGn7iT:bbj2p0v) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

I used "make html man" command to verify my original change, it's ok as I opened the file using firefox. Not sure what browser you are using to open this file.
</blockquote></details>

in my opinion, this is not code-block, it just lists the commands recommended for user to apply. 


<!-- Sent from Reviewable.io -->

2021-02-01 05:38 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 95 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQJypK2MW1IVulZBx1:-MSR5FLY6GVxYbm_inPe:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like the wording of this whole point, it's hard to read and repetitive. Something like this should be better:

```
- SGX support was upstreamed to the Linux mainline starting from 5.11.
  It currently supports only DCAP attestation. The driver is accessible through
  /dev/sgx_enclave and /dev/sgx_provision.
```

(plus leaving that "The following [...]" sentence as is, it's good in the current form)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-01 05:38 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 77 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQHkeEDOaUHY7c7Q-S:-MSR5I8f-FFEO1VOji5v:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Pal/src/host/Linux-SGX/link-intel-driver.py#L77)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix the double space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-01 07:26 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[Documentation/sgx-intro.rst, line 98 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQId1uCU8UidZo4Ijd:-MSRTmMWCFfpffY-siWe:bx80t57) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

in my opinion, this is not code-block, it just lists the commands recommended for user to apply. 
</blockquote></details>

Michal is right, this is a `sh`-formatted code block. Please add `.. highlight:: sh` line at the beginning of this whole file.

You can find an example of this in `Documentation/quickstart.rst`.


<!-- Sent from Reviewable.io -->

2021-02-01 08:08 UTC, johnvenn commented
___
*[Documentation/sgx-intro.rst, line 98 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQId1uCU8UidZo4Ijd:-MSRc_s39Q6IHxcnhkV3:b-xcpb9h) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Michal is right, this is a `sh`-formatted code block. Please add `.. highlight:: sh` line at the beginning of this whole file.

You can find an example of this in `Documentation/quickstart.rst`.
</blockquote></details>

thanks a lot, Dmitrii, I have updated. could you please review?


<!-- Sent from Reviewable.io -->

2021-02-01 08:13 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Documentation/sgx-intro.rst, line 98 at r8](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSQId1uCU8UidZo4Ijd:-MSRdtUx1R3sRimNvAAE:b34d6mo) ([raw file](https://github.com/oscarlab/graphene/blob/86cd52f1d5dbc0a51d2e5c2c57da6d2a4d12387b/Documentation/sgx-intro.rst#L98)):*
<details><summary><i>Previously, johnvenn (xiangping-INTEL) wrote…</i></summary><blockquote>

thanks a lot, Dmitrii, I have updated. could you please review?
</blockquote></details>

LGTM. Looks good to me!


<!-- Sent from Reviewable.io -->

2021-02-01 08:14 UTC, dimakuv commented
Jenkins, test this please

2021-02-01 08:38 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @johnvenn and @mkow)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 12 at r10](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSRjBrX6-bBpENki85-:-MSRjBrX6-bBpENki850:b6b071h) ([raw file](https://github.com/oscarlab/graphene/blob/1fa48faca431279a45b94fc4ff2835798818cea8/Pal/src/host/Linux-SGX/link-intel-driver.py#L12)):*
> ```Python
>         'include/sgx_user.h':         '/dev/sgx/enclave',  # For DCAP driver 1.10+
>         'include/uapi/asm/sgx.h':     '/dev/sgx_enclave',  # For upstreamed in-kernel SGX driver, kernel version 5.11+
>         'sgx_in_kernel.h':            '/dev/sgx/enclave',  # By default, using sgx_in_kernel.h in current dir of this script
> ```

Didn't notice before, but these lines now exceed the limit of 100 chars per line. Could you fix this by moving the comments above the lines? Like this:
```
         # For Non-DCAP, older versions of legacy OOT SGX driver
        'sgx_user.h':                 '/dev/isgx',
         # For DCAP driver 1.6+, but below 1.10
        'include/uapi/asm/sgx_oot.h': '/dev/sgx/enclave',
         # For DCAP driver 1.10+
        'include/sgx_user.h':         '/dev/sgx/enclave',
         # For upstreamed in-kernel SGX driver, kernel version 5.11+
        'include/uapi/asm/sgx.h':     '/dev/sgx_enclave',
         # By default, using sgx_in_kernel.h in current dir of this script
        'sgx_in_kernel.h':            '/dev/sgx/enclave',

```


<!-- Sent from Reviewable.io -->

2021-02-01 13:03 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @johnvenn)



<!-- Sent from Reviewable.io -->

2021-02-01 14:36 UTC, johnvenn commented
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 12 at r10](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSRjBrX6-bBpENki85-:-MST0PbK3LyGUaA97HWa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1fa48faca431279a45b94fc4ff2835798818cea8/Pal/src/host/Linux-SGX/link-intel-driver.py#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Didn't notice before, but these lines now exceed the limit of 100 chars per line. Could you fix this by moving the comments above the lines? Like this:
```
         # For Non-DCAP, older versions of legacy OOT SGX driver
        'sgx_user.h':                 '/dev/isgx',
         # For DCAP driver 1.6+, but below 1.10
        'include/uapi/asm/sgx_oot.h': '/dev/sgx/enclave',
         # For DCAP driver 1.10+
        'include/sgx_user.h':         '/dev/sgx/enclave',
         # For upstreamed in-kernel SGX driver, kernel version 5.11+
        'include/uapi/asm/sgx.h':     '/dev/sgx_enclave',
         # By default, using sgx_in_kernel.h in current dir of this script
        'sgx_in_kernel.h':            '/dev/sgx/enclave',

```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-01 15:09 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-02-01 19:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-01 19:08 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2084#-MSTzVfS6oXs8ENZ7JCq:-MSTzVfS6oXs8ENZ7JCr:b18lb3n) (no related file):*
@johnvenn Thanks for the PR! It was approved, and we will rebase and merge it now. Please do **not** do anything with this PR and your branch from now on.

---


<!-- Sent from Reviewable.io -->

2021-02-01 19:20 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-02-01 19:20 UTC, dimakuv commented
Jenkins, test this please

2021-02-01 19:24 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2084)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-01 19:55 UTC, merged