[LibOS] Use GS register for syscalls
oscarlab/graphene pull request #2086
Opened 2021-01-14 14:11 UTC by pwmarcz

CC @boryspoplawski: as discussed, I think your version could just do `jmp *%gs:<offset>` instead of `call *%gs:<offset>`?

## Description of the changes 

Instead of depending on dynamic linking for LibOS entry point
(syscalldb), pass a function pointer in the shim_tcb structure,
so that the patched code can call it using 'callq %gs:\<offset>'.

In addition, remove the other two instances where we import a
symbol directly from LibOS: register_library (can be also done
through GS register) and glibc_version (not important because we
build Graphene and glibc together).

This simplifies things because the dynamic linking necessary to
make the syscalldb function available had to be performed by LibOS
itself (in many cases, effectively doing a second pass of dynamic
linking after ld.so). After this change, there will be no need for
LibOS to perform dynamic linking, and the ELF loading code can be
simplified.

## Next steps

After this, I can get rid of dynamic linking from LibOS. The code that remains should be more similar to Linux kernel than glibc: handle `execve` by loading the executable, load the interpreter (`ld.so`), pass control to the interpreter.

The subsequent libraries (loaded by `ld.so`) will still be reported to Graphene, but only for debugging purposes (reporting them to GDB); see also #2044.

(As a quick experiment, I checked that I can just disable the code doing the relocations, and everything still works. I can also stub out `register_library`, and the programs still run, although GDB stops seeing the libraries).

## Considered alternatives

* I first proposed to pass the syscall address using an environment variable, but using GS register is more convenient.
* This is, in spirit, pretty similar to vDSO: in some architectures (sadly, not x86-64) the program even receives `AT_SYSINFO` which is the syscall entry address. I don't think it's a good idea to use this mechanism on x86-64, though: it's more complicated to set up (both on Graphene and glibc sides), and could trigger something unexpected.
* The offset is hardcoded in the patches. I guess we could `#include` a file from LibOS instead, but I don't think it's worth it: I like that the patches are self-contained now, and that building patched glibc doesn't depend on using rest of Graphene sources.

2021-01-14 20:59 UTC, yamahata reviewed
+1 for deleting glibc version check. For upstream, better way needs to be invented. e.g. introduce new section like .note.libos to have such info.

Regarding to call vs jmp, I'll leave it to Borys. It has impacts on switch stack between libos and app.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086#-:-MR1dlflANeg8ngkuCxb:bcugc1g)* status: 0 of 11 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1bDqB5LQs8tUg8Tj_:-MR1bDqB5LQs8tUg8Tja:br6wagg) ([raw file](https://github.com/oscarlab/graphene/blob/2f88a6cc8fa95d4838676083664a8424660a1b0f/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> --- /dev/null
> +++ b/syscallas.S
> @@ -0,0 +1,11 @@
> +#include <syscalldb.h>
> +
> +.weak syscalldb
> +.type syscalldb,@function
> +
> +syscalldb:
> +	.cfi_startproc
> +	syscall
> +	retq
> +	.cfi_endproc
> +	.size syscalldb,.-syscalldb
> ```
</details>


This code is to make patched glibc work without graphene. i.e. normal environment.
Although I don't believe that someone is testing it, that's the intention.
For that, stub like this needs to be kept and on early startup of ld.so, determine the environment is graphene or not, and then initialize %gs:syscalldb_offset properly if needed.

I mark this unblocking because I'm not sure it's worthwhile to keep such compatibility at the moment.
Although compatibility is definitively necessary when upstreaming, penalizing normal case unconditionally doesn't work for upstream.
 


<!-- Sent from Reviewable.io -->

2021-01-14 21:04 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 0 of 11 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/glibc-patches/glibc-2.23.patch, line 498 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1hNgZ7nXNJHi4I-vm:-MR1hNgZ7nXNJHi4I-vn:b-xverbx) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.23.patch#L498)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 
> +  /* for graphene, get around R_X86_64_NONE */
> +  else if (__builtin_expect (r_type != R_X86_64_NONE, 1))
>      _dl_reloc_bad_type (map, r_type, 1);
>  }
> ```
</details>


Can we remove this hunk?
This is a hack for relocation twice.  prevent ld.so from erroring out.


<!-- Sent from Reviewable.io -->

2021-01-15 08:19 UTC, dimakuv commented
Jenkins, retest this please (Jenkins had internal problems)

2021-01-15 08:42 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @yamahata)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR481D5BU-gCPDzbUMt:-MR481D5BU-gCPDzbUMu:bm4bdpy) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L15)):*
> ```Diff
> +    "callq *%%gs:" SHIM_SYSCALLDB_OFFSET_STR "\n\t"  \
> +    "addq $128, %%rsp\n\t"                           \
> +    ".cfi_adjust_cfa_offset -128\n\t"
> ```

Did you check that it builds correctly now? You can simply do `make -C LibOS gcc -j` (achtung, takes a looot of time) and then examine the objdump of `Runtime/libgomp.so`. This is *not* automatically tested in our Jenkins, so we need to verify manually.
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR49X6U05yAl-runO6I:-MR49X6U05yAl-runO6J:b-lzr42v) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.23.patch#L44)):*
> ```Diff
>  
> +  /* register the library to SHIM */
> +  register_library(l->l_name, l->l_addr);
> ```

I thought we don't need this `register_library()` anymore. Will it be removed after your other PR on debugging lands?
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 498 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1hNgZ7nXNJHi4I-vm:-MR495WC9e3-j6XeFKWh:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.23.patch#L498)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> 
> +  /* for graphene, get around R_X86_64_NONE */
> +  else if (__builtin_expect (r_type != R_X86_64_NONE, 1))
>      _dl_reloc_bad_type (map, r_type, 1);
>  }
> ```

Can we remove this hunk?
This is a hack for relocation twice.  prevent ld.so from erroring out.
</blockquote></details>

+1
___
*[LibOS/glibc-patches/glibc-2.27.patch, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR49sB0C-8Qh6kuURrQ:-MR49sB0C-8Qh6kuURrR:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.27.patch#L44)):*
> ```Diff
>  
> +  /* register the library to SHIM */
> +  register_library(l->l_name, l->l_addr);
> ```

ditto
___
*[LibOS/glibc-patches/glibc-2.27.patch, line 351 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR49uNa2yK2BccDKbGa:-MR49uNa2yK2BccDKbGb:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.27.patch#L351)):*
> ```Diff
> -  else
> +  /* for graphene, get around R_X86_64_NONE */
> +  else if (__builtin_expect (r_type != R_X86_64_NONE, 1))
> ```

ditto
___
*[LibOS/glibc-patches/glibc-2.31.patch, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4A6xGCXEJblfwImOM:-MR4A6xGCXEJblfwImON:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.31.patch#L45)):*
> ```Diff
>  
> +  /* register the library to SHIM */
> +  register_library(l->l_name, l->l_addr);
> ```

ditto
___
*[LibOS/glibc-patches/glibc-2.31.patch, line 342 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4A8gN1kbawwn1scGe:-MR4A8gN1kbawwn1scGf:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.31.patch#L342)):*
> ```Diff
> -  else
> +  /* for Graphene, get around R_X86_64_NONE */
> +  else if (__builtin_expect (r_type != R_X86_64_NONE, 1))
> ```

ditto
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1bDqB5LQs8tUg8Tj_:-MR4Az912zc9hr1jhDlJ:b-ps88dh) ([raw file](https://github.com/oscarlab/graphene/blob/2f88a6cc8fa95d4838676083664a8424660a1b0f/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> --- /dev/null
> +++ b/syscallas.S
> @@ -0,0 +1,11 @@
> +#include <syscalldb.h>
> +
> +.weak syscalldb
> +.type syscalldb,@function
> +
> +syscalldb:
> +	.cfi_startproc
> +	syscall
> +	retq
> +	.cfi_endproc
> +	.size syscalldb,.-syscalldb
> ```

This code is to make patched glibc work without graphene. i.e. normal environment.
Although I don't believe that someone is testing it, that's the intention.
For that, stub like this needs to be kept and on early startup of ld.so, determine the environment is graphene or not, and then initialize %gs:syscalldb_offset properly if needed.

I mark this unblocking because I'm not sure it's worthwhile to keep such compatibility at the moment.
Although compatibility is definitively necessary when upstreaming, penalizing normal case unconditionally doesn't work for upstream.
 
</blockquote></details>

+1 to Isaku. I would leave this "fallback to normal environment" code as-is if possible.
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4CFn4C1CoYyEuwXnO:-MR4CFn4C1CoYyEuwXnP:b-dkbb9f) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
> ```Diff
> +    subq $128, %rsp;                    \
> +    .cfi_adjust_cfa_offset 128;         \
> +    callq *%gs:SHIM_SYSCALLDB_OFFSET;   \
> ```

@stefanberger How bad is this change for you? Do you even use Glibc in your project?
___
*[LibOS/shim/include/shim_internal.h, line 506 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4ByEDCiJcN_lUsgCP:-MR4ByEE-qzMnMfW3Q8t:b4yto44) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/shim/include/shim_internal.h#L506)):*
> ```objc
> void syscalldb(void);
> 
> int register_library(const char* name, unsigned long load_address);
> ```

Wouldn't it make sense to move these into `shim_tcb.h`? It will slightly simplify the code, but maybe logically it's a bad idea...
___
*[LibOS/shim/include/shim_tcb.h, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4BMsO3-fcv4k2XMY8:-MR4BMsO3-fcv4k2XMY9:b-4vvvno) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/shim/include/shim_tcb.h#L13)):*
> ```objc
> 
> /* Offsets for patched code calling into Graphene (see patches for glibc and gcc). If you change
>  * this, update the patches too.*/
> ```

Please add a space before `*/` :)


<!-- Sent from Reviewable.io -->

2021-01-15 08:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4D1PwA-WYv55D2BWK:-MR4D1PwA-WYv55D2BWL:bx49kh9) (no related file):*
This PR is awesome!

> After this, I can get rid of dynamic linking from LibOS.

This future PR will be even more awesome!

---


<!-- Sent from Reviewable.io -->

2021-01-15 12:17 UTC, pwmarcz reviewed
>Regarding to call vs jmp, I'll leave it to Borys. It has impacts on switch stack between libos and app.

Of course. I mean that after the refactoring, the syscall will be a jmp instead of call, but the rest should work the same.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086#-:-MR4ux3f8zctvve8MYlf:b-8862c4)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @pwmarcz, and @yamahata)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR481D5BU-gCPDzbUMt:-MR4v4Do9WKG4yYkeya3:b240rkn) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you check that it builds correctly now? You can simply do `make -C LibOS gcc -j` (achtung, takes a looot of time) and then examine the objdump of `Runtime/libgomp.so`. This is *not* automatically tested in our Jenkins, so we need to verify manually.
</blockquote></details>

I did exactly that (compile, then check objdump). And yeah, I'm doing this on a strong enough server. :)
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR49X6U05yAl-runO6I:-MR4vLazEWY_HtY07T3o:b-e040kx) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.23.patch#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I thought we don't need this `register_library()` anymore. Will it be removed after your other PR on debugging lands?
</blockquote></details>

Unfortunately, we still need it to report the library to GDB. Glibc/ld.so does keep its own list of libraries, and we could hook into that, but last time I looked it was too much trouble.

What we can do is remove everything else that `register_library()` does - basically it tries to perform (most of) the loading again, and redo dynamic linking :)
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 498 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1hNgZ7nXNJHi4I-vm:-MR4vryc1c3xa4MPOmdh:b-3mj86j) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.23.patch#L498)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

As far as I can tell, in this PR we still do relocation twice - I don't want to change too much in one commit, so I'm not touching the RTLD code yet. But I think I'll be able to do that as next step, thanks for pointing it out.
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1bDqB5LQs8tUg8Tj_:-MR4wFBL35TY2pchLvi-:bvrresf) ([raw file](https://github.com/oscarlab/graphene/blob/2f88a6cc8fa95d4838676083664a8424660a1b0f/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Isaku. I would leave this "fallback to normal environment" code as-is if possible.
</blockquote></details>

Good point. What would be a good way of detecting if we're running under Graphene? Without relying on the dynamic linker, or syscalls.
___
*[LibOS/shim/include/shim_internal.h, line 506 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4ByEDCiJcN_lUsgCP:-MR4xngf33JzOy7sz4Mm:b-xqzzyo) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/shim/include/shim_internal.h#L506)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it make sense to move these into `shim_tcb.h`? It will slightly simplify the code, but maybe logically it's a bad idea...
</blockquote></details>

Maybe. It's messy because `shim_internal.h` includes `shim_tcb.h`, so I have to work around that and declare them locally in `shim_tcb.h`. Your solution is a bit confusing, but does improve the situation (no need for workaround).


<!-- Sent from Reviewable.io -->

2021-01-15 14:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @yamahata)

___
*[LibOS/glibc-patches/glibc-2.23.patch, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR49X6U05yAl-runO6I:-MR5U50JBxPOOrHqxWV9:b-hbzzja) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/glibc-2.23.patch#L44)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Unfortunately, we still need it to report the library to GDB. Glibc/ld.so does keep its own list of libraries, and we could hook into that, but last time I looked it was too much trouble.

What we can do is remove everything else that `register_library()` does - basically it tries to perform (most of) the loading again, and redo dynamic linking :)
</blockquote></details>

OK, got it.
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1bDqB5LQs8tUg8Tj_:-MR5VCN7EcZE1lhoBLcA:bjqe4b9) ([raw file](https://github.com/oscarlab/graphene/blob/2f88a6cc8fa95d4838676083664a8424660a1b0f/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Good point. What would be a good way of detecting if we're running under Graphene? Without relying on the dynamic linker, or syscalls.
</blockquote></details>

There are tunables in Glibc (https://www.gnu.org/software/libc/manual/html_node/Tunables.html) but I don't know if they can be accessed prior to any Glibc's syscall attempt. I don't know of a good way of detecting...
___
*[LibOS/shim/include/shim_internal.h, line 506 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4ByEDCiJcN_lUsgCP:-MR5UZKc4OWRIRhNj6Zh:b-8m4l7q) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/shim/include/shim_internal.h#L506)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Maybe. It's messy because `shim_internal.h` includes `shim_tcb.h`, so I have to work around that and declare them locally in `shim_tcb.h`. Your solution is a bit confusing, but does improve the situation (no need for workaround).
</blockquote></details>

Actually, yes, let's leave as is. It's a mess either way :)


<!-- Sent from Reviewable.io -->

2021-01-15 15:54 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @pwmarcz, and @yamahata)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1bDqB5LQs8tUg8Tj_:-MR5YzDMAt3IZN_wfRMX:b5gc1iz) ([raw file](https://github.com/oscarlab/graphene/blob/2f88a6cc8fa95d4838676083664a8424660a1b0f/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There are tunables in Glibc (https://www.gnu.org/software/libc/manual/html_node/Tunables.html) but I don't know if they can be accessed prior to any Glibc's syscall attempt. I don't know of a good way of detecting...
</blockquote></details>

I'll give it some more thought. If we want to have a fallback to normal environment (and some startup step seems necessary for that), then perhaps using GS is not the best option.


<!-- Sent from Reviewable.io -->

2021-01-15 16:09 UTC, boryspoplawski reviewed
TBH, I would rather first merge #2090 as applying this patch later will be just matter of chaning `jmp func` to `jmp %gs:...`. Other than that seems compatible with my changes.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086#-:-MR5iNBGDIBD5nfEvNm7:bbbefeq)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @pwmarcz, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-01-15 16:56 UTC, pwmarcz reviewed
No problem, this is not ready yet.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086#-:-MR5yWgv48ttld-IzA1K:b-l61uoz)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @pwmarcz, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-01-15 17:13 UTC, pwmarcz commented
This approach doesn't work too well when we want the code to still be runnable in "normal environment". It becomes necessary to do some initialization and detect whether we're running under Graphene or not.

Because of that, using the GS register doesn't sound like it will buy us much. Instead, I would propose something pretty close to the current approach:

* In `ld.so`, define and export syscalldb as a pointer (not a function):
```c
// default_syscalldb is the default implementation that does SYSCALL; RET
void (*syscalldb)(void) = &default_syscalldb;
```

* Use ELF aux vector: define an AT_GRAPHENE_ENTRY key (with some suitably high number) and pass `&syscalldb` under that key when executing an ELF object. 
  * Initially I didn't want this, but I looked at glibc code, and it doesn't seem to mind unknown aux keys.

* Early during `ld.so` startup, search the ELF aux vector passed to the binary, and set `syscalldb` to the value of `AT_GRAPHENE_ENTRY`. 
  * Normally `ld.so` does that parsing a bit too late, but it seems pretty simple to implement by hand: see how [musl reads the aux vector](https://github.com/ifduyue/musl/blob/master/ldso/dlstart.c#L26).

* The rest of the code imports the `syscalldb` variable and does an indirect call:
```asm
.weak syscalldb
...
callq *syscalldb(%rip)
```

This way we still rely on dynamic linking, but crucially, **we import the `syscalldb` pointer from `ld.so`, not from Graphene**. So the dynamic linking performed by `ld.so` itself is enough - no extra postprocessing by Graphene necessary, and I can still delete all the code I want to delete.

I like this approach also because patching the applications is simpler - there is no constant offset to adjust, just do `.weak syscalldb` and go. The downside is that it doesn't work as well for statically linked binaries (you have to recreate what `ld.so` does yourself). But we don't do anything to support static binaries right now, either.

2021-01-15 17:24 UTC, pwmarcz reviewed
Oh, but then again... if it's true that LibOS can change address after a fork (and so far we've been assuming that), then you cannot store a pointer into LibOS. So I guess using the GS register is still necessary.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086#-:-MR63Nh0Azby2LQQQfKI:bi6t9rq)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @pwmarcz, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-01-18 11:21 UTC, dimakuv approved these changes
> The downside is that it doesn't work as well for statically linked binaries (you have to recreate what ld.so does yourself). But we don't do anything to support static binaries right now, either.

This sounds pretty bad. We do have use cases where we run static binaries. And in general, we want to have full support for static linking in the near future.

> if it's true that LibOS can change address after a fork (and so far we've been assuming that), then you cannot store a pointer into LibOS.

I would definitely want to allow LibOS text section to be randomizable after fork.

I like the current approach of using the GS register directly. All these changes are anyway confined to the x86-64 arch-specific files, so this should be portable. I suggest we stick to this.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086#-:-MRKCSVNAGeuYVCL-HVc:bwxnbf3)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz and @yamahata)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR1bDqB5LQs8tUg8Tj_:-MRKDTBCD3MEioV0K6KJ:bjvg48y) ([raw file](https://github.com/oscarlab/graphene/blob/2f88a6cc8fa95d4838676083664a8424660a1b0f/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'll give it some more thought. If we want to have a fallback to normal environment (and some startup step seems necessary for that), then perhaps using GS is not the best option.
</blockquote></details>

I think we are very far away from upstreaming such Glibc changes, so let's not take this into account. If there is no easy way, then let's just keep it as is.


<!-- Sent from Reviewable.io -->

2021-01-18 11:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz and @yamahata)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4CFn4C1CoYyEuwXnO:-MRKDm9jDGxMQRCock9p:b-ohywz0) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@stefanberger How bad is this change for you? Do you even use Glibc in your project?
</blockquote></details>

I just realized that these are anyway x86-specific changes. So if Stefan uses Glibc in his project, he anyway has his own patches.


<!-- Sent from Reviewable.io -->

2021-01-18 15:15 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2086#-MRL327d-oAGuVXPmuMx:-MRL327e64jpqxRU0e3g:bny8cx0) (no related file):*
> TBH, I would rather first merge #2090 as applying this patch later will be just matter of chaning `jmp func` to `jmp %gs:...`. Other than that seems compatible with my changes.

Moving to a blocking comment.

---


<!-- Sent from Reviewable.io -->

2021-01-18 20:05 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz and @yamahata)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4CFn4C1CoYyEuwXnO:-MRM5NxC5f-n4TsApgpq:b-w5p23w) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/glibc-patches/syscalldb-api.patch#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I just realized that these are anyway x86-specific changes. So if Stefan uses Glibc in his project, he anyway has his own patches.
</blockquote></details>

I am ready for this change -- I have already prepared for it! I am more scared of 2090 than this one. :-)


<!-- Sent from Reviewable.io -->

2021-01-20 19:56 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-01-20 19:56 UTC, yamahata submitted a review, later dismissed
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-02-08 10:06 UTC, pwmarcz reviewed
After looking into it deeper, and talking with @mkow, we decided it's not worth it to retain non-Graphene compatibility in libc. It would be pretty complicated:

* first, you have to notify glibc that we're running under Graphene (and that would be very early in `ld.so` startup), 
* then, if no Graphene, glibc has to set up the area under GS register,
* then we would need to make that happen for all new threads - we could hook into libpthread but what if the app is not using it?
* alternatively, glibc could set up its own internal syscall address, but that can change after fork...

If glibc upstream would ever support alternate syscall mechanism, I would recommend something else, like using vDSO. But for now, using the GS register is simplest.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086#-:-MT01cIA0TPqvcc6M5QX:b349b2n)* status: 2 of 15 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2086#-MRL327d-oAGuVXPmuMx:-MT03T41--3P9edx0iSS:bszaur7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> TBH, I would rather first merge #2090 as applying this patch later will be just matter of chaning `jmp func` to `jmp %gs:...`. Other than that seems compatible with my changes.

Moving to a blocking comment.
</blockquote></details>

Patch updated after #2090. A notable change is updating/simplifying the vDSO machinery.

---
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MT044KRCG9CRmehAl-5:b-4tmic6) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
> ```Diff
> +++ b/syscalldb_macro.S
> @@ -0,0 +1,7 @@
> +SHIM_SYSCALLDB_OFFSET = 32
> ```

It's pretty hacky to redefine the constant here, but C preprocessor and assembler macros apparently don't mix too well, so I didn't have a better idea.
___
*[LibOS/shim/include/shim_tcb.h, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2086#-MR4BMsO3-fcv4k2XMY8:-MT04WdU6hYWnAjTDSK9:brnnzii) ([raw file](https://github.com/oscarlab/graphene/blob/3740e22b834d240ebbeaba4e71775fc45d124908/LibOS/shim/include/shim_tcb.h#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space before `*/` :)
</blockquote></details>

I moved the definitions to `shim_defs.h` and fixed the comment there.


<!-- Sent from Reviewable.io -->

2021-02-08 16:24 UTC, mkow requested changes
> Reviewed 2 of 11 files at r1, 12 of 13 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_tcb.h, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1OkP2-USaVXMeyxuj:-MT1OkP2-USaVXMeyxuk:b-qkp1j6) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/include/shim_tcb.h#L26)):*
> ```objc
> 
>     /* Function pointers for patched code calling into Graphene. */
>     void*               syscalldb;
> ```

Unrelated to the PR, but why is this called "syscalldb"? What's that "db"? Anyone knows?
___
*[LibOS/shim/include/shim_tcb.h, line 61 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1R9pC5s2okcC6LuyK:-MT1R9pD8JOzVYC2jEa_:b-5uurgh) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/include/shim_tcb.h#L61)):*
> ```objc
> static inline void __shim_tcb_init(shim_tcb_t* shim_tcb) {
>     /* These are declared in shim_internal.h, but we cannot include it because of a circular
>      * dependency (this file is included by shim_internal.h already. */
> ```

Could you split them into a separate header? This would solve the cyclic dependency problem.
Ideally with a name suggesting that these are shared with the patched glibc.
___
*[LibOS/shim/src/vdso/arch/x86_64/vdso_syscall.h, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1SCzH5nOHacF5IrDk:-MT1SCzH5nOHacF5IrDl:be38bi1) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/src/vdso/arch/x86_64/vdso_syscall.h#L17)):*
> ```objc
>         ".Lret%=:\n"
>         : "=a" (ret)
>         : "0" (nr), "D"(arg1), "S"(arg2), [syscalldb] "i" (SHIM_SYSCALLDB_OFFSET)
> ```

no space after `"i"` (it was here before, but let's fix it now)


<!-- Sent from Reviewable.io -->

2021-02-08 16:53 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 11 of 18 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_tcb.h, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1OkP2-USaVXMeyxuj:-MT1UesL8MBTJ_UdioUP:b-qr0ax2) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/include/shim_tcb.h#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Unrelated to the PR, but why is this called "syscalldb"? What's that "db"? Anyone knows?
</blockquote></details>

No idea but LibOS is compiled to `libsysdb.so` :)
___
*[LibOS/shim/include/shim_tcb.h, line 61 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1R9pC5s2okcC6LuyK:-MT1XzxK0yMEaO5Viehl:b-m33qv4) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/include/shim_tcb.h#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you split them into a separate header? This would solve the cyclic dependency problem.
Ideally with a name suggesting that these are shared with the patched glibc.
</blockquote></details>

Done, but I called the file `shim_entry.h` - I'd rather not imply the functions are glibc-specific.
___
*[LibOS/shim/src/vdso/arch/x86_64/vdso_syscall.h, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1SCzH5nOHacF5IrDk:-MT1YIiX6prLV7UBP2Ru:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/src/vdso/arch/x86_64/vdso_syscall.h#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space after `"i"` (it was here before, but let's fix it now)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 16:59 UTC, mkow approved these changes
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-02-08 18:25 UTC, boryspoplawski requested changes
> Reviewed 2 of 11 files at r1, 8 of 13 files at r2, 1 of 1 files at r3, 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 10 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1lQbCCzaj3Zp8r4kg:-MT1lQbCCzaj3Zp8r4kh:bs6agxl) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L10)):*
> ```Diff
>  
> +#define SHIM_SYSCALLDB_OFFSET_STR "32"
> +#define SYSCALLDB "jmpq *%%gs:" SHIM_SYSCALLDB_OFFSET_STR "\n\t"
> ```

This is wrong: you need to set `rcx` to the return address.
Why not keep the old macro and just change the `jmp`?
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1r76NEq7Tgl5SO-hX:-MT1r76NEq7Tgl5SO-hY:bwei2jt) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/glibc-patches/glibc-2.23.patch#L35)):*
> ```Diff
>  #include <dl-sysdep-open.h>
>  
> +#include "syscalldb.c"
> ```

`.c` -> `.h`.
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MT1oj0H71lDymXDcj0S:bknb2m6) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's pretty hacky to redefine the constant here, but C preprocessor and assembler macros apparently don't mix too well, so I didn't have a better idea.
</blockquote></details>

Why not create a `shim_syscalldb_offsets.h` with:
```
#define SHIM_SYSCALLDB_OFFSET 32
...
```
and just `#include "shim_syscalldb_offset.h"` here? Seems to be working ok ...
You could also symlink that file to have the very same in LibOS.
___
*[LibOS/shim/include/shim_tcb.h, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1OkP2-USaVXMeyxuj:-MT1rdXK6owt02m29dT2:bgkfhcx) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/include/shim_tcb.h#L26)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No idea but LibOS is compiled to `libsysdb.so` :)
</blockquote></details>

Wild guess: `syscalls database`


<!-- Sent from Reviewable.io -->

2021-02-09 10:10 UTC, dimakuv requested changes
> Reviewed 8 of 13 files at r2, 1 of 1 files at r3, 6 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @woju)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 10 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1lQbCCzaj3Zp8r4kg:-MT5Ards7ItVr3moDOOi:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L10)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is wrong: you need to set `rcx` to the return address.
Why not keep the old macro and just change the `jmp`?
</blockquote></details>

+1
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1r76NEq7Tgl5SO-hX:-MT5C8EV5vsC3nFWy1Uf:b5fo0sh) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/glibc-patches/glibc-2.23.patch#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`.c` -> `.h`.
</blockquote></details>

How could this not be caught by our Jenkins CI? We have this Jenkinsfile: https://github.com/oscarlab/graphene/blob/master/.ci/linux-direct-ubuntu16.04-gcc-glibc223.jenkinsfile. But it seems we don't use this file anywhere in our actual Jenkins? @woju @mkow Are we not testing this?

Well, maybe it's time to finally retire `glibc-2.23`, noone is using it and apparently we don't even test its build in Jenkins (as we did previously).
___
*[LibOS/shim/include/shim_tcb.h, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1OkP2-USaVXMeyxuj:-MT5EGM42j3EeS8Fm779:b-qygqs) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/include/shim_tcb.h#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wild guess: `syscalls database`
</blockquote></details>

I have another guess: `db = DrawBridge`. Recall that Graphene was started as a Drawbridge counterpart in Linux. I've seen some Drawbridge mentions in the original code from 5 years ago.
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT5G2bQ14WJsO7pcig5:-MT5G2bQ14WJsO7pcig6:b8tx3ow) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
> ```C
>  */
> 
> static void* vdso_addr __attribute_migratable = NULL;
> ```

Why do we have `attribute_migratable` here? Isn't `vdso_addr` always re-initialized when a new Graphene instance starts, even if it's a child process?


<!-- Sent from Reviewable.io -->

2021-02-09 11:58 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 10 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1lQbCCzaj3Zp8r4kg:-MT5NKd35x9hkrHi_u85:b-5rq4v) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Right, I didn't rebase that properly.

Fixed and tested (I recompiled gcc, and ran `openmp` regression test with the patched `libgomp.so`).
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1r76NEq7Tgl5SO-hX:-MT5PUY212hAhTzc6ZyJ:bz2fvfn) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/glibc-patches/glibc-2.23.patch#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How could this not be caught by our Jenkins CI? We have this Jenkinsfile: https://github.com/oscarlab/graphene/blob/master/.ci/linux-direct-ubuntu16.04-gcc-glibc223.jenkinsfile. But it seems we don't use this file anywhere in our actual Jenkins? @woju @mkow Are we not testing this?

Well, maybe it's time to finally retire `glibc-2.23`, noone is using it and apparently we don't even test its build in Jenkins (as we did previously).
</blockquote></details>

Interesting. It looks like glibc 2.23 is the default for Ubuntu 16, but Jenkins tests Ubuntu 16 with glibc 2.27.

Also, there are several patches necessaary only in that version of glibc:

```
cvs-common-symbols.patch
dangling-else.patch
ieee754-boolean-context.patch
nis-bogus-conditional.patch
rpc-format-overflow.patch
```

I guess running glibc 2.27 under Ubuntu 16 might cause some compatibility issues (if you're running applications compiled against glibc 2.23). However, seeing how
* our glibc 2.23 support is not tested at all by CI,
* we plan to drop Ubuntu 16 soon, 
* Ubuntu 16 [reaches end of standard support this April](https://wiki.ubuntu.com/Releases),

I would really rather submit a separate PR that drops these patches instead of fixing this. Any objections?
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MT5SrBo7NUVGS5HYszD:b-46t6pf) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
>Seems to be working ok ...

What have you tried? This:

```asm
#include "shim_syscalldb_offset.h"

.macro SYSCALLDB
leaq .Lafter_syscalldb\@(%rip), %rcx
jmpq *%gs:SHIM_SYSCALLDB_OFFSET
.Lafter_syscalldb\@:
.endm
```

fails for me with:

```
/usr/bin/ld: /home/user/graphene/LibOS/glibc-build/elf/librtld.os: relocation R_X86_64_32S against undefined symbol `SHIM_SYSCALLDB_OFFSET' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
```

>You could also symlink that file to have the very same in LibOS.

Should I, though? I wanted to avoid sharing code between LibOS and glibc, so that the patches can be self-contained. I think that doing otherwise complicates the build scripts and dependencies (you need to either make a symlink, or `#include` a file outside glibc tree, as we did before, also you need a rule to rebuild glibc whenever the file changes), and sets a bad precedent (what if someone comes later and makes that file more complicated).

But I understand also the pain of duplicating these constants, so I won't push back on this.

(By the way, I also learned that `.include` assembly 
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT5G2bQ14WJsO7pcig5:-MT5XATY7ZxIOD_bwwVm:b37jva9) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we have `attribute_migratable` here? Isn't `vdso_addr` always re-initialized when a new Graphene instance starts, even if it's a child process?
</blockquote></details>

I don't think so. The `vdso_addr` is supposed to be the same after fork, and we migrate the vdso page instead of setting it up again.

Reading the code, the path seems to be: `vdso_map_init` <- `execute_elf_object` <- `shim_init` (but only if we don't call `restore_child_context_after_clone`).


<!-- Sent from Reviewable.io -->

2021-02-09 12:01 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 17 of 18 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MT5eIKYCHVsUNPBR90l:b-wmjmr5) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Seems to be working ok ...

What have you tried? This:

```asm
#include "shim_syscalldb_offset.h"

.macro SYSCALLDB
leaq .Lafter_syscalldb\@(%rip), %rcx
jmpq *%gs:SHIM_SYSCALLDB_OFFSET
.Lafter_syscalldb\@:
.endm
```

fails for me with:

```
/usr/bin/ld: /home/user/graphene/LibOS/glibc-build/elf/librtld.os: relocation R_X86_64_32S against undefined symbol `SHIM_SYSCALLDB_OFFSET' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
```

>You could also symlink that file to have the very same in LibOS.

Should I, though? I wanted to avoid sharing code between LibOS and glibc, so that the patches can be self-contained. I think that doing otherwise complicates the build scripts and dependencies (you need to either make a symlink, or `#include` a file outside glibc tree, as we did before, also you need a rule to rebuild glibc whenever the file changes), and sets a bad precedent (what if someone comes later and makes that file more complicated).

But I understand also the pain of duplicating these constants, so I won't push back on this.

(By the way, I also learned that `.include` assembly 
</blockquote></details>

By the way, I also learned that `.include` assembly directive in `syscalldb.h` breaks ccache (it doesn't get picked up as dependency). I don't think that's enough reason to change it, though, the macro is quite convenient.


<!-- Sent from Reviewable.io -->

2021-02-09 12:22 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)

___
*[LibOS/glibc-patches/glibc-2.23.patch, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1r76NEq7Tgl5SO-hX:-MT5iqXp9EryurtfnAJc:b-jcx0r3) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/glibc-patches/glibc-2.23.patch#L35)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Interesting. It looks like glibc 2.23 is the default for Ubuntu 16, but Jenkins tests Ubuntu 16 with glibc 2.27.

Also, there are several patches necessaary only in that version of glibc:

```
cvs-common-symbols.patch
dangling-else.patch
ieee754-boolean-context.patch
nis-bogus-conditional.patch
rpc-format-overflow.patch
```

I guess running glibc 2.27 under Ubuntu 16 might cause some compatibility issues (if you're running applications compiled against glibc 2.23). However, seeing how
* our glibc 2.23 support is not tested at all by CI,
* we plan to drop Ubuntu 16 soon, 
* Ubuntu 16 [reaches end of standard support this April](https://wiki.ubuntu.com/Releases),

I would really rather submit a separate PR that drops these patches instead of fixing this. Any objections?
</blockquote></details>

I agree that we should remove Glibc 2.23, in a separate PR.

But could you still fix `.c -> .h`? This is a simple fix, and definitely a bug here.
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT5G2bQ14WJsO7pcig5:-MT5jVjY6KGya-wrM-x0:bv27shy) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't think so. The `vdso_addr` is supposed to be the same after fork, and we migrate the vdso page instead of setting it up again.

Reading the code, the path seems to be: `vdso_map_init` <- `execute_elf_object` <- `shim_init` (but only if we don't call `restore_child_context_after_clone`).
</blockquote></details>

OK. You are right about the different code paths.


<!-- Sent from Reviewable.io -->

2021-02-09 12:40 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 17 of 18 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[LibOS/glibc-patches/glibc-2.23.patch, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1r76NEq7Tgl5SO-hX:-MT5mHvrETISYURO0txx:b-yacws9) ([raw file](https://github.com/oscarlab/graphene/blob/59e9e2b76dd0f410ccacb5a934251b83fe2ec2eb/LibOS/glibc-patches/glibc-2.23.patch#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree that we should remove Glibc 2.23, in a separate PR.

But could you still fix `.c -> .h`? This is a simple fix, and definitely a bug here.
</blockquote></details>

I was hoping to merge the removal first and drop this file entirely :) But you're right, there's no need to bundle these changes, and the fix is cheap.

I fixed the patch and did a quick sanity check on Ubuntu 16 (compile + `./pal_loader bootstrap` regression test).

And I submitted glibc 2.23 removal in https://github.com/oscarlab/graphene/pull/2150.


<!-- Sent from Reviewable.io -->

2021-02-09 12:59 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-02-09 13:22 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

___
*[LibOS/shim/include/shim_tcb.h, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT1OkP2-USaVXMeyxuj:-MT5ww0uEcy4bsR-6v6h:b-43ws78) ([raw file](https://github.com/oscarlab/graphene/blob/341b9fcd25eaffe3cf7bfd50e2e01c1c48b5d857/LibOS/shim/include/shim_tcb.h#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have another guess: `db = DrawBridge`. Recall that Graphene was started as a Drawbridge counterpart in Linux. I've seen some Drawbridge mentions in the original code from 5 years ago.
</blockquote></details>

Not sure about DrawBridge, it's the name for the API used in PAL, not here...
Anyways, we should rename this confusing thing, but not in this PR.


<!-- Sent from Reviewable.io -->

2021-02-09 17:24 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MT6ms0b3YqzyhD2Yb_G:bs2u712) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
I've tried a simple `.S` including `.h` and it worked, but indeed it fails in the glibc build, no idea why (header not included?).
> Should I, though? I wanted to avoid sharing code between LibOS and glibc, so that the patches can be self-contained. I think that doing otherwise complicates the build scripts and dependencies (you need to either make a symlink, or #include a file outside glibc tree, as we did before, also you need a rule to rebuild glibc whenever the file changes),

Well, if you dont add the dependency it's not worse than having the value hardcoded. I don't mind adding a symlink.
> and sets a bad precedent (what if someone comes later and makes that file more complicated).

Imo it's fine if this header contains only `define`s and does not include anything.


<!-- Sent from Reviewable.io -->

2021-02-10 13:50 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 12 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MTAel-q8_pl_c2cAHOO:bpamj21) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
>I've tried a simple .S including .h and it worked, but indeed it fails in the glibc build, no idea why (header not included?).

I had a header with `#define` and that did not work. But later I changed it to constant definition (`SHIM_SYSCALLDB_OFFSET = 32`) and that _still_ didn't work for C files in glibc, probably due to the use of `asm(".include ...")`.

Anyway, I got it to work and I'm quite happy with the current solution: the macro is defined twice (in C and in assembler mode), but I think it's well worth it as it makes the whole patch less complicated. (And I don't have to work around ccache not understanding `asm(".include")` in my developer setup :) )

I also created a separate file (`shim_entry_offsets.h`) shared between glibc and Graphene.


<!-- Sent from Reviewable.io -->

2021-02-10 14:04 UTC, mkow approved these changes
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-02-10 15:14 UTC, mkow reviewed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 12 at r7](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBVRmi0mg1OlL468qQ:-MTBVRmi0mg1OlL468qR:b2i15tt) ([raw file](https://github.com/oscarlab/graphene/blob/8c62c3ca5733fcab2672468bac2fc0b723b0166d/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L12)):*
> ```Diff
> +
> +#define XSTR(s) STR(s)
> +#define STR(s) #s
> ```

Hmm, wasn't this working? Why have you undid this change?
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 33 at r7](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBVJPf5cFZfSB2HyHP:-MTBVJPf5cFZfSB2HyHQ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/8c62c3ca5733fcab2672468bac2fc0b723b0166d/LibOS/glibc-patches/syscalldb-api.patch#L33)):*
> ```Diff
> +
> +#define XSTR(s) STR(s)
> +#define STR(s) #s
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-02-10 16:02 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 12 at r7](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBVRmi0mg1OlL468qQ:-MTBewRNE0H6teX0Ms9S:b46bev0) ([raw file](https://github.com/oscarlab/graphene/blob/8c62c3ca5733fcab2672468bac2fc0b723b0166d/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, wasn't this working? Why have you undid this change?
</blockquote></details>

Conflict with glibc :) (`setjmp.h` in glibc 2.27)

```
../include/setjmp.h:40:0: error: "STR" redefined [-Werror]
 # define STR(x) STR_HELPER(x)
```

Do you think it's better to keep doing it this way? With some other name like `_STR` or `SHIM_STR`.


<!-- Sent from Reviewable.io -->

2021-02-10 16:06 UTC, boryspoplawski requested changes
> Reviewed 3 of 8 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MTBfmJhC1jA8ohN9dsg:b-7acnnd) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>I've tried a simple .S including .h and it worked, but indeed it fails in the glibc build, no idea why (header not included?).

I had a header with `#define` and that did not work. But later I changed it to constant definition (`SHIM_SYSCALLDB_OFFSET = 32`) and that _still_ didn't work for C files in glibc, probably due to the use of `asm(".include ...")`.

Anyway, I got it to work and I'm quite happy with the current solution: the macro is defined twice (in C and in assembler mode), but I think it's well worth it as it makes the whole patch less complicated. (And I don't have to work around ccache not understanding `asm(".include")` in my developer setup :) )

I also created a separate file (`shim_entry_offsets.h`) shared between glibc and Graphene.
</blockquote></details>

The only problem I have with the current version is that we need to duplicate that macro in every patch. Now we have two, but if we add more, each of them will have to have its own version.
Is there no way of keeping the macro include and the offsets include?
___
*[LibOS/shim/include/shim_entry_offsets.h, line 11 at r8](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBgGOG7iowKKe9sCjw:-MTBgGOG7iowKKe9sCjx:b66q7h) ([raw file](https://github.com/oscarlab/graphene/blob/03d2216b849e2071c43fb6feaf1ee5fa973a6197/LibOS/shim/include/shim_entry_offsets.h#L11)):*
> ```objc
> #ifdef __ASSEMBLER__
> 
> SHIM_SYSCALLDB_OFFSET                    = 32
> ```

Afaik `#define` works for `.S`, why do we need  this?


<!-- Sent from Reviewable.io -->

2021-02-10 16:33 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MTBiONS2tilr2T2G3i3:b-xidx8z) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The only problem I have with the current version is that we need to duplicate that macro in every patch. Now we have two, but if we add more, each of them will have to have its own version.
Is there no way of keeping the macro include and the offsets include?
</blockquote></details>

I see the problem... Looking through glibc's code for a precedent (I know, maybe not a very good thing to base on) I see some instances of `#includes` for assembler files, and even some `.macro`s being defined for `.S` files, but no macros intended for use with both `.S` and inline assembly. 

So, I don't have an idea how to keep both includes, other than that `asm(".include ...")` doesn't work too well.

How about moving the macro definitions to Graphene? We already accepted that we have a shared file for offsets. So maybe that file could be called `shim_entry_api.h` and actually define the `SYSCALLDB` macro? And the actual patches would just use it.
___
*[LibOS/shim/include/shim_entry_offsets.h, line 11 at r8](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBgGOG7iowKKe9sCjw:-MTBieh66gYdkVZ8lU7U:bjir6yv) ([raw file](https://github.com/oscarlab/graphene/blob/03d2216b849e2071c43fb6feaf1ee5fa973a6197/LibOS/shim/include/shim_entry_offsets.h#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Afaik `#define` works for `.S`, why do we need  this?
</blockquote></details>

You're right. I thought I checked that and it didn't. I'll change it to `#define`.


<!-- Sent from Reviewable.io -->

2021-02-11 10:29 UTC, dimakuv approved these changes
> Reviewed 1 of 7 files at r4, 3 of 8 files at r7, 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-02-11 18:49 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MTHPliZ10aKUo5sJ2rc:b9wxcvd) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
Is there anything wrong with `asm(".include...` except for code dependency tracking issues?
> So maybe that file could be called shim_entry_api.h and actually define the SYSCALLDB macro? 

Hmm, that might be the best thing we can go for, given current requirements...
Summon @dimakuv @mkow @yamahata 


<!-- Sent from Reviewable.io -->

2021-02-12 10:18 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MTKjMF3C1H5y1wMVGY4:bfwdsae) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is there anything wrong with `asm(".include...` except for code dependency tracking issues?
> So maybe that file could be called shim_entry_api.h and actually define the SYSCALLDB macro? 

Hmm, that might be the best thing we can go for, given current requirements...
Summon @dimakuv @mkow @yamahata 
</blockquote></details>

I'm fine with defining the macro in the Graphene header and using it here. I also like the name `shim_entry_api.h`. So I'm fine with this proposal. This way we also won't need to redefine the SYSCALLDB macro is every other lib we add (like `libgomp.so`).


<!-- Sent from Reviewable.io -->

2021-02-12 12:06 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 10 of 18 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/gcc-patches/libgomp-replace-futex-instruction.patch, line 12 at r7](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBVRmi0mg1OlL468qQ:-MTL2Xsw2zaRJENBuvnd:b-xrsf4q) ([raw file](https://github.com/oscarlab/graphene/blob/8c62c3ca5733fcab2672468bac2fc0b723b0166d/LibOS/gcc-patches/libgomp-replace-futex-instruction.patch#L12)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Conflict with glibc :) (`setjmp.h` in glibc 2.27)

```
../include/setjmp.h:40:0: error: "STR" redefined [-Werror]
 # define STR(x) STR_HELPER(x)
```

Do you think it's better to keep doing it this way? With some other name like `_STR` or `SHIM_STR`.
</blockquote></details>

I renamed the macros to `SHIM_STR` / `SHIM_XSTR` (and moved the code to a single include file in `shim/include`).
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MT044KQ7H-Cqd8z1rM-:-MTL2mdB5BoY-fr0ZnAb:b4sckl6) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/syscalldb-api.patch#L42)):*
>Is there anything wrong with asm(".include... except for code dependency tracking issues?

Yes. The dependency tracking issue with ccache is just my own quality-of-life (it speeds up rebulding glibc somewhat), but the main issue is that apparently C preprocessor doesn't work inside a file included with `.include` (which kind of makes sense, as gcc runs `cpp` earlier than assembler and `.include` is handled by assembler).

Anyway, I introduced `shim_entry_api.h`. It's more or less what was in `syscalldb-api.patch` before, but now the code is kept in LibOS directory directly, and the patches (glibc 2.27, glibc 2.31, gcc) symlink and include it.
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 33 at r7](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBVJPf5cFZfSB2HyHP:-MTL2jp95DAWLipslIkF:bca6yj5) ([raw file](https://github.com/oscarlab/graphene/blob/8c62c3ca5733fcab2672468bac2fc0b723b0166d/LibOS/glibc-patches/syscalldb-api.patch#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same - the macros are back, namespaced, in a common file.
___
*[LibOS/shim/include/shim_entry_offsets.h, line 11 at r8](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTBgGOG7iowKKe9sCjw:-MTL4PZi4Q625dkwS1YP:bjeb1oc) ([raw file](https://github.com/oscarlab/graphene/blob/03d2216b849e2071c43fb6feaf1ee5fa973a6197/LibOS/shim/include/shim_entry_offsets.h#L11)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

You're right. I thought I checked that and it didn't. I'll change it to `#define`.
</blockquote></details>

Done, the new version uses `#define` for both C and assembler.


<!-- Sent from Reviewable.io -->

2021-02-12 14:23 UTC, dimakuv approved these changes
> Reviewed 9 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-02-12 14:25 UTC, boryspoplawski approved these changes
> Reviewed 9 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-02-12 14:56 UTC, boryspoplawski commented
Jenkins, retest this please (internal jenkins failure)

2021-02-12 22:53 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MTNRAiA5LC4DTSED01E:b-oec47a) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
> ```objc
> #define SHIM_REGISTER_LIBRARY_OFFSET  40
> 
> #ifdef __ASSEMBLER__
> ```

Ideally the architecture-specific part here (the #ifdef __ASSEMBLER ... #endif block) would go into a `LibOS/shim/include/arch/x86_64/shim_entry_api-arch.h`


<!-- Sent from Reviewable.io -->

2021-02-12 23:32 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MTN_aYb3dbUIy2o8YqM:b-et85bw) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Ideally the architecture-specific part here (the #ifdef __ASSEMBLER ... #endif block) would go into a `LibOS/shim/include/arch/x86_64/shim_entry_api-arch.h`
</blockquote></details>

Good point, please move it.


<!-- Sent from Reviewable.io -->

2021-02-15 11:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 13 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MT_VTSS2R7fsieWnovy:b1ivxoq) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Good point, please move it.
</blockquote></details>

Okay, but I would argue the whole file is architecture-specific, including the offsets: on a different architecture, the TCB structure might have different field sizes, different padding, or architecture-specific fields.

Also, I would rather keep it simple; splitting the API into two files means you have to use them both in the patches.

I moved the whole file to `include/arch/x86_64`, without the `-arch` suffix: if I understand correctly, the suffix is added when there is also an architecture-independent file, and omitted otherwise (as in `shim_syscalls.h`, `shim_dl-machine.h`, and also `vdso_syscall.h`).


<!-- Sent from Reviewable.io -->

2021-02-15 13:02 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 13 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MT_kz6a2oBrrrlnjCxx:b-mcpgkz) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, but I would argue the whole file is architecture-specific, including the offsets: on a different architecture, the TCB structure might have different field sizes, different padding, or architecture-specific fields.

Also, I would rather keep it simple; splitting the API into two files means you have to use them both in the patches.

I moved the whole file to `include/arch/x86_64`, without the `-arch` suffix: if I understand correctly, the suffix is added when there is also an architecture-independent file, and omitted otherwise (as in `shim_syscalls.h`, `shim_dl-machine.h`, and also `vdso_syscall.h`).
</blockquote></details>

The problem with the current solution is that now we have a symbolic link for glibc pointing to an architecture-specific include file, which prevents me from doing something similar for ppc64. We may not be able to use $(ARCH) in gibc, so maybe having the following in `shim_entry_api.h` would solve the issue:

```
/* needs to be usable from glibc where $(ARCH) is not available */
#ifdef (__x86_64__)
#include "arch/x86_64/shim_entry_api-arch.h"
#endif
``` 

One could then extend this with `#ifdef (__powerpc64__)`


<!-- Sent from Reviewable.io -->

2021-02-15 13:40 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 13 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MT_ngNw9chxJw_PCs6d:b-f0jj3b) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

The problem with the current solution is that now we have a symbolic link for glibc pointing to an architecture-specific include file, which prevents me from doing something similar for ppc64. We may not be able to use $(ARCH) in gibc, so maybe having the following in `shim_entry_api.h` would solve the issue:

```
/* needs to be usable from glibc where $(ARCH) is not available */
#ifdef (__x86_64__)
#include "arch/x86_64/shim_entry_api-arch.h"
#endif
``` 

One could then extend this with `#ifdef (__powerpc64__)`

</blockquote></details>

I thought the glibc patches were going to be x86-64-specific. Are you planning to support many architectures in a single `.patch` file?

If so, then I would rather not do it using symlinks. I think symlinking a whole tree of files (including the `arch/` directories) is too complicated and brittle. It might be better to go back to adding include flags:
```sh
CFLAGS += -I../shim/include -I../shim/include/arch/$(ARCH)
```

This is what we do currently for glibc (except for `$(ARCH)`, I think that would still work). Would that work for you?


<!-- Sent from Reviewable.io -->

2021-02-15 13:56 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 13 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MT_yBzs1JAvmLYC7-pQ:bgxrbk2) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I thought the glibc patches were going to be x86-64-specific. Are you planning to support many architectures in a single `.patch` file?

If so, then I would rather not do it using symlinks. I think symlinking a whole tree of files (including the `arch/` directories) is too complicated and brittle. It might be better to go back to adding include flags:
```sh
CFLAGS += -I../shim/include -I../shim/include/arch/$(ARCH)
```

This is what we do currently for glibc (except for `$(ARCH)`, I think that would still work). Would that work for you?
</blockquote></details>

No, but the naming of your symbolic link was architecture un-specific but pointing to an architecture specific file.

Your above solution would work for me. Thanks!


<!-- Sent from Reviewable.io -->

2021-02-15 14:18 UTC, mkow requested changes
> Reviewed 4 of 9 files at r9, 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/glibc-patches/glibc-2.27.patch, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTa-QCE7tV9k4lYhtuI:-MTa-QCE7tV9k4lYhtuJ:bkdr8rf) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/glibc-2.27.patch#L23)):*
> ```Diff
>  
> -headers		= elf.h bits/elfclass.h link.h bits/link.h
> +headers		= elf.h bits/elfclass.h link.h bits/link.h syscalldb.h
> ```

Shouldn't we add `shim_entry_api.h` to deps here, in place of `syscalldb.h`, instead of removing this hunk?
___
*[LibOS/shim/include/arch/x86_64/shim_entry_api.h, line 46 at r10](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTa1y3XEUXY3ApvgW7L:-MTa1y3Y7pumnciUXHp_:b-tr2gcz) ([raw file](https://github.com/oscarlab/graphene/blob/f0dbdacd49fce38a4b3d14634ae096159745771a/LibOS/shim/include/arch/x86_64/shim_entry_api.h#L46)):*
> ```objc
> 
> static inline int shim_register_library(const char* name, unsigned long load_address)
> {
> ```

the brace should be on previous line


<!-- Sent from Reviewable.io -->

2021-02-15 14:23 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @stefanberger)

___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MTa3RaT1hUPc4nVkzGK:bjpfzki) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
> No, but the naming of your symbolic link was architecture un-specific but pointing to an architecture specific file.

Was it used somewhere in a non-architecture-specific way? If not, then all you need to do is provide a different symlink (since patches are arch-specific anyway).


<!-- Sent from Reviewable.io -->

2021-02-15 16:21 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: 14 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @stefanberger)

___
*[LibOS/glibc-patches/glibc-2.27.patch, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTa-QCE7tV9k4lYhtuI:-MTaCX_s9zoWdQMNjsxb:b-3xjslm) ([raw file](https://github.com/oscarlab/graphene/blob/a9b9f75ada52554871377b61a576fff972add5b3/LibOS/glibc-patches/glibc-2.27.patch#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we add `shim_entry_api.h` to deps here, in place of `syscalldb.h`, instead of removing this hunk?
</blockquote></details>

I think this is actually for _installable_ headers, i.e. what `make install` is supposed to install.

Also, I just removed the file from this source tree anyway.
___
*[LibOS/shim/include/shim_entry_api.h, line 21 at r9](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTNRAiA5LC4DTSED01D:-MTaAkGK72m1TcvQhWf4:b-6dx7of) ([raw file](https://github.com/oscarlab/graphene/blob/442571c1fd3670487db5547ad7f5e91de83c728d/LibOS/shim/include/shim_entry_api.h#L21)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> No, but the naming of your symbolic link was architecture un-specific but pointing to an architecture specific file.

Was it used somewhere in a non-architecture-specific way? If not, then all you need to do is provide a different symlink (since patches are arch-specific anyway).
</blockquote></details>

I applied the above suggestion for glibc (the easiest was to pass `CPPFLAGS="-I..."` to `configure` from outside). I think it's reasonably future-proof: if we ever split the "entry API" into a few files, there is no need to update the patches.

GCC in another story. I couldn't figure it out, because it has this multi-stage build process, and flags passed to top-level `configure` do not seem to propagate to `libgomp` (which has a nested `./configure`). There's also no obvious place in gcc makefiles to patch.

Seeing how GCC is probably going to be an exception, I'm keeping a symlink there - it's in a directory called `linux/x86` anyway.
___
*[LibOS/shim/include/arch/x86_64/shim_entry_api.h, line 46 at r10](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTa1y3XEUXY3ApvgW7L:-MTaAiOCBMzDPXWHMU8p:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/f0dbdacd49fce38a4b3d14634ae096159745771a/LibOS/shim/include/arch/x86_64/shim_entry_api.h#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

the brace should be on previous line
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-02-15 16:33 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @stefanberger)



<!-- Sent from Reviewable.io -->

2021-02-15 17:40 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/Makefile, line 57 at r11](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTakznf11oRed6uMV_U:-MTakzng-m4MSaYP31QP:bv2qcja) ([raw file](https://github.com/oscarlab/graphene/blob/2449f5af4e70cbe104f13e991f2d4c55947cd343/LibOS/Makefile#L57)):*
> ```Makefile
> GLIBC_CPPFLAGS = -I$(abspath $(SHIM_DIR))/include -I$(abspath $(SHIM_DIR))/include/arch/$(ARCH)
> export GLIBC_CPPFLAGS
> GLIBC_DEPS = shim/include/arch/x86_64/shim_entry_api.h
> ```

Shouldn't we use `$(ARCH)` here as well?


<!-- Sent from Reviewable.io -->

2021-02-15 19:03 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/Makefile, line 57 at r11](https://reviewable.io/reviews/oscarlab/graphene/2086#-MTakznf11oRed6uMV_U:-MTb2-H8361iOjrwwDsZ:b5jba04) ([raw file](https://github.com/oscarlab/graphene/blob/2449f5af4e70cbe104f13e991f2d4c55947cd343/LibOS/Makefile#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we use `$(ARCH)` here as well?
</blockquote></details>

Makes sense. Updated, and I changed the line for gcc as well.


<!-- Sent from Reviewable.io -->

2021-02-15 19:16 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-15 19:25 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-15 19:38 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug please (known issue #2156)

2021-02-15 21:00 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 5 files at r10, 3 of 4 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-15 21:28 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-15 21:30 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-15 21:50 UTC, mkow commented
Jenkins, retest Jenkins-18.04 please (Examples/apache build failed, looks like broken dependencies in the Makefile there)

2021-02-15 22:01 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2086)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-15 22:08 UTC, mkow commented
Jenkins, retest Jenkins-SGX-apps please (Examples/redis failed on invalid enclave measurement, probably a race in the Makefile)

2021-02-15 22:08 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-apps please (`enclave EINIT failed - Invalid measurement`, known issue)

2021-02-15 22:59 UTC, merged