UBSAN fixes
oscarlab/graphene pull request #2089
Opened 2021-01-14 18:46 UTC by stefanberger

This PR contains 2 UBSAN fixes.

2021-01-14 19:04 UTC, stefanberger commented
FYI: I have tree here where UBSAN is enabled via `make UBSA=1`: https://github.com/stefanberger/graphene/commits/stefanberger/ubsan_keep

Some regression tests are not working at all and finding the locations to fix is quite a challenge, especially in some case where the UBSAN error occurs after a fork + execve.

2021-01-14 20:12 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-14 20:25 UTC, stefanberger reviewed
I have another patch that I will append to this shortly.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089#-:-MR1Z_Y-3UlM84aONHPj:b-7589vr)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-15 00:30 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MR2LWz-0939SG7n8r8H:bjkrqkg) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
> ```
> rs_func rs = (&__rs_func)[cpent->cp_type - CP_FUNC_BASE];
> ```

What warning did you get here?
___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Pn70BVZjc5mesny6:-MR2Pn70BVZjc5mesny7:bp8lhhp) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/shim_checkpoint.c#L465)):*
> ```
> /* ubsan */
> ```

This comment will be quite hard to understand without the context of this PR.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2NvmD3n3NmeUBDgP_:-MR2NvmD3n3NmeUBDgPa:b-c4rhfw) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_hash.c#L13)):*
> ```C
> static HASHTYPE __hash(const char* p, size_t len) {
>     HASHTYPE hash = 0;
>     unsigned char buf[sizeof(hash)];
> ```

How can this help with alignment? It has the same guarantees as `const char` array in the argument.
You should do the memcpy into a `HASHTYPE` variable and remove the casts.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 16 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PtbT6MKqkTdNsjSX:-MR2PtbT6MKqkTdNsjSY:b-ei786h) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_hash.c#L16)):*
> ```C
> 
>     for (; len >= sizeof(hash); p += sizeof(hash), len -= sizeof(hash)) {
>         memcpy(buf, p, sizeof(hash)); /* ubsan */
> ```

ditto (comment)
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 95 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2J7jZ1nqsvKYvxyF3:-MR2J7j_Al_BYNHBnBtg:b32vgs) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_pseudo.c#L95)):*
> ```C
>             /* directory entry has a hardcoded name */
>             size_t name_size   = strlen(ent->name) + 1;
>             size_t dirent_size = ROUND_UP(sizeof(struct shim_dirent) + name_size, 8);
> ```

8?
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2ODpQCsAkN4eIfAnI:-MR2ODpQCsAkN4eIfAnJ:bhmjw3p) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/proc/thread.c#L677)):*
> ```C
>         ;
> 
>     int buflen = ROUND_UP(l + 1, 8); /* rounding for pointer-alignment */
> ```

`int` -> `size_t`
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2ObPa47AJj310Q6ao:-MR2ObPa47AJj310Q6ap:b32vgs) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/proc/thread.c#L677)):*
> ```C
>         ;
> 
>     int buflen = ROUND_UP(l + 1, 8); /* rounding for pointer-alignment */
> ```

8?
___
*[LibOS/shim/src/sys/shim_open.c, line 332 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PXDV9qFVR6PR3OZQ:-MR2PXDV9qFVR6PR3OZR:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L332)):*
> ```C
> 
> #define DIRENT_SIZE(len) \
>     ROUND_UP(sizeof(struct linux_dirent) + sizeof(struct linux_dirent_tail) + (len) + 1, 8)
> ```

ditto
___
*[LibOS/shim/src/sys/shim_open.c, line 340 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Q3A0DCTTJilcaCZ4:-MR2Q3A0DCTTJilcaCZ5:be0j7rx) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L340)):*
> ```C
>             goto done;                                                                   \
>                                                                                          \
>         struct linux_dirent_tail* bt = (void*)b + DIRENT_SIZE(len) - 2;                  \
> ```

Why -2?
___
*[LibOS/shim/src/sys/shim_open.c, line 351 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2R5xe2L-9ovIZjKAe:-MR2R5xe2L-9ovIZjKAf:b-fsk1pa) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/sys/shim_open.c#L351)):*
> ```C
>         bt->d_type = (type);                                                             \
>                                                                                          \
>         b = (void*)bt + sizeof(struct linux_dirent_tail);                                \
> ```

What happened to `linux_dirent_tail`?
___
*[LibOS/shim/src/sys/shim_open.c, line 433 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PjFP1evdxzNE5U2P:-MR2PjFP1evdxzNE5U2Q:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L433)):*
> ```C
>     }
> 
> #define DIRENT_SIZE(len) ROUND_UP(sizeof(struct linux_dirent64) + (len) + 1, 8)
> ```

ditto
___
*[Pal/include/lib/api.h, line 69 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2IZMeBp9KhviAwG-4:-MR2IZMeBp9KhviAwG-5:b-w5g3sv) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/Pal/include/lib/api.h#L69)):*
> ```objc
> 
> #define DIV_ROUND_UP(n,d)               (((n) + (d) - 1) / (d))
> #define ROUND_UP(n,d)                   (DIV_ROUND_UP(n, d) * (d))
> ```

We already have `ALIGN_UP*` macros for exactly this, please use them.


<!-- Sent from Reviewable.io -->

2021-01-15 01:36 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MR2WL7i3sLPvDHQNgmK:b-3uk2c4) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> rs_func rs = (&__rs_func)[cpent->cp_type - CP_FUNC_BASE];
> ```

What warning did you get here?
</blockquote></details>

The problem is we don't get a warning, just segfaults that loop forever. You have to hook gdb to it or detect it with debug() line by line and in this case I had to use debug() after the fork()/execve(). So, I don't know, but this resolves the issue.
___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Pn70BVZjc5mesny6:-MR2WSG9D8RCpoiI76oB:byxjp6b) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> /* ubsan */
> ```

This comment will be quite hard to understand without the context of this PR.
</blockquote></details>

Ok, let me clarify this tomorrow.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2NvmD3n3NmeUBDgP_:-MR2WX4Q1kCEEmOHLLfu:bzefgj3) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_hash.c#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How can this help with alignment? It has the same guarantees as `const char` array in the argument.
You should do the memcpy into a `HASHTYPE` variable and remove the casts.
</blockquote></details>

Yes, wrong type. Fixed.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 16 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PtbT6MKqkTdNsjSX:-MR2bgUn24WHYO8A6zMG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_hash.c#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (comment)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 95 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2J7jZ1nqsvKYvxyF3:-MR2WjI6EZQF3ihwGlzh:bvnswte) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_pseudo.c#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

8?
</blockquote></details>

`dirent_in_buf->next` needs to be properly aligned!
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2ODpQCsAkN4eIfAnI:-MR2WuDm9eMohqvLdYh5:b32w1t) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/proc/thread.c#L677)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`int` -> `size_t`
</blockquote></details>

Ok
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2ObPa47AJj310Q6ao:-MR2WwyxCKDKT19U4EeJ:bjruup0) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/proc/thread.c#L677)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

8?
</blockquote></details>

Same requirements for alignment. buf->next below is otherwise not properly aligned on the NEXT entry.
___
*[LibOS/shim/src/sys/shim_open.c, line 332 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PXDV9qFVR6PR3OZQ:-MR2eMIP3G_ZORQFjv0w:bm8ugwe) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L332)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

`b->d_ino` is a uint64_t that needs to be 8-byte aligned.
___
*[LibOS/shim/src/sys/shim_open.c, line 340 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Q3A0DCTTJilcaCZ4:-MR2YiEw1KRxNq93e_wb:b54w460) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L340)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why -2?
</blockquote></details>

sizeof(*bt)
___
*[LibOS/shim/src/sys/shim_open.c, line 351 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2R5xe2L-9ovIZjKAe:-MR2XURb-KDEXkdZrTDE:b-z6on32) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/sys/shim_open.c#L351)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What happened to `linux_dirent_tail`?
</blockquote></details>

Didn't touch anything related to this... 
___
*[LibOS/shim/src/sys/shim_open.c, line 433 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PjFP1evdxzNE5U2P:-MR2eUnD80ZcViLkuQgb:b34mw0z) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L433)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same explanation. `b->d_ino` below.
___
*[Pal/include/lib/api.h, line 69 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2IZMeBp9KhviAwG-4:-MR2Zv9D4zKzZfY7Dcxc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/Pal/include/lib/api.h#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We already have `ALIGN_UP*` macros for exactly this, please use them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 01:37 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 0 of 5 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Pn70BVZjc5mesny6:-MR2gAfN7AQ4YihJ9G8M:b-wtcrb1) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Ok, let me clarify this tomorrow.
</blockquote></details>

Clarified today :-)


<!-- Sent from Reviewable.io -->

2021-01-15 08:12 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Pn70BVZjc5mesny6:-MR40D3X9Fb0Qj7bB53f:b64t6mv) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Clarified today :-)
</blockquote></details>

Wait wait wait, this is some hack...

Did you find this on x86-64 or ppc64? If it is ppc64, what are the alignment requirements for function pointers?

Here is how `__rs_func` symbol is declared in `LibOS/src/shim-x86_64.lds`:
```c
  .text :
  {
    /* the rest of text segments */
    __code_address = .;
    *(.text .stub .text.*);
    . = ALIGN(8);           /* <-- explicit 8-byte alignment */
    __cp_name = .;
    *(SORT(.cp_name.*));
    __cp_func = .;
    *(SORT(.cp_func.*));
    __rs_func = .;
    *(SORT(.rs_func.*));   /* <-- all restore-graphene-object functions are sorted in this array */
    __code_address_end = .;
  }
```

So `__rs_func[idx]` is an 8-byte aligned function pointer (to a restore-specific-graphene-object function). From what I know (https://stackoverflow.com/questions/27183604/alignment-requirement-of-function-pointers), there is no alignment requirement on x86-64 for function pointers. So why is this whole snippet cases troubles on UBSAN?

UPDATE: I make an assumption that `__cp_name`, `cp_name_*`, `__cp_func`, `cp_func_*` entries are all 8-byte pointers (which they are). So the alignment of 8 bytes is preserved until the linker sees `__rs_func` and `rs_func_*`.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 16 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PtbT6MKqkTdNsjSX:-MR42lmlATBBUSjPPLYq:br4drub) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_hash.c#L16)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK, this fix makes sense.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 95 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2J7jZ1nqsvKYvxyF3:-MR434yk7j608eHfKU2P:bg4cd5n) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_pseudo.c#L95)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

`dirent_in_buf->next` needs to be properly aligned!
</blockquote></details>

I think Michal wants `8` -> `sizeof(dirent_in_buf->next)` and a comment `/* all directory entries must be aligned on the dirent::next pointer size */`
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2ODpQCsAkN4eIfAnI:-MR43cLtCuW56n1zj69B:bu3xmuu) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/proc/thread.c#L677)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Ok
</blockquote></details>

Please `8` -> `sizeof(buf->next)`. Hm, `buf` is declared later; then simply `sizeof(struct shim_dirent*)`
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2ObPa47AJj310Q6ao:-MR43uRxETxcv4ScMh3X:b-urzzu5) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/proc/thread.c#L677)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Same requirements for alignment. buf->next below is otherwise not properly aligned on the NEXT entry.
</blockquote></details>

See my comments above
___
*[LibOS/shim/src/sys/shim_open.c, line 332 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PXDV9qFVR6PR3OZQ:-MR43xONAtY22taGIusi:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L332)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

`b->d_ino` is a uint64_t that needs to be 8-byte aligned.
</blockquote></details>

ditto
___
*[LibOS/shim/src/sys/shim_open.c, line 351 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2R5xe2L-9ovIZjKAe:-MR44oSb48u9j9gi2quS:bfwdzr5) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/sys/shim_open.c#L351)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Didn't touch anything related to this... 
</blockquote></details>

@mkow Stefan did some unrelated cleanup of the code here (instead of calculating offsets from `bt` which points somewhere in the middle of `b`, just calculate everything from `b`). It's easier to just read the new code. Looks legit.
___
*[LibOS/shim/src/sys/shim_open.c, line 433 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PjFP1evdxzNE5U2P:-MR45EBo9oZ6-crqPjkr:bq0xcuz) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L433)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Same explanation. `b->d_ino` below.
</blockquote></details>

ditto (need a comment and `sizeof`)


<!-- Sent from Reviewable.io -->

2021-01-15 12:18 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Pn70BVZjc5mesny6:-MR4ukV0-IPaK-4KjFp2:brc88o6) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait wait wait, this is some hack...

Did you find this on x86-64 or ppc64? If it is ppc64, what are the alignment requirements for function pointers?

Here is how `__rs_func` symbol is declared in `LibOS/src/shim-x86_64.lds`:
```c
  .text :
  {
    /* the rest of text segments */
    __code_address = .;
    *(.text .stub .text.*);
    . = ALIGN(8);           /* <-- explicit 8-byte alignment */
    __cp_name = .;
    *(SORT(.cp_name.*));
    __cp_func = .;
    *(SORT(.cp_func.*));
    __rs_func = .;
    *(SORT(.rs_func.*));   /* <-- all restore-graphene-object functions are sorted in this array */
    __code_address_end = .;
  }
```

So `__rs_func[idx]` is an 8-byte aligned function pointer (to a restore-specific-graphene-object function). From what I know (https://stackoverflow.com/questions/27183604/alignment-requirement-of-function-pointers), there is no alignment requirement on x86-64 for function pointers. So why is this whole snippet cases troubles on UBSAN?

UPDATE: I make an assumption that `__cp_name`, `cp_name_*`, `__cp_func`, `cp_func_*` entries are all 8-byte pointers (which they are). So the alignment of 8 bytes is preserved until the linker sees `__rs_func` and `rs_func_*`.
</blockquote></details>

I found it on x86_64. I unfortunately do not know why this is causing an issue. I had added additional ALIGN(8) statements into the snippet above but that didn't help.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2NvmD3n3NmeUBDgP_:-MR4vbOsBa-Oc1YoM_0F:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_hash.c#L13)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Yes, wrong type. Fixed.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 95 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2J7jZ1nqsvKYvxyF3:-MR4wbLMCopgU5jnpEHM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_pseudo.c#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think Michal wants `8` -> `sizeof(dirent_in_buf->next)` and a comment `/* all directory entries must be aligned on the dirent::next pointer size */`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2ObPa47AJj310Q6ao:-MR4xGo44j_uDsP1vTgp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/proc/thread.c#L677)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my comments above
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 332 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PXDV9qFVR6PR3OZQ:-MR4yGHz4MprH6Xin9JF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L332)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 340 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Q3A0DCTTJilcaCZ4:-MR4yGjc8kOF5GGDGvlL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L340)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

sizeof(*bt)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 351 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2R5xe2L-9ovIZjKAe:-MR4yJlN4Z87frTGwHvN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/sys/shim_open.c#L351)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow Stefan did some unrelated cleanup of the code here (instead of calculating offsets from `bt` which points somewhere in the middle of `b`, just calculate everything from `b`). It's easier to just read the new code. Looks legit.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 433 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2PjFP1evdxzNE5U2P:-MR4yMfB0StX8PcDRGmK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/sys/shim_open.c#L433)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (need a comment and `sizeof`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 12:20 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 2 of 5 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MR4zDmW52L2e-U3RaHo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

The problem is we don't get a warning, just segfaults that loop forever. You have to hook gdb to it or detect it with debug() line by line and in this case I had to use debug() after the fork()/execve(). So, I don't know, but this resolves the issue.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 14:48 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Pn70BVZjc5mesny6:-MR5ViZU1sGNuexpcx3-:bo2k3h) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I found it on x86_64. I unfortunately do not know why this is causing an issue. I had added additional ALIGN(8) statements into the snippet above but that didn't help.
</blockquote></details>

OK, I'm accepting because it's a small change. But I don't understand what could cause this...
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 95 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2J7jZ1nqsvKYvxyF3:-MR5VrJ1B4hgR-85WReD:b-9agpkf) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_pseudo.c#L95)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Typo: `pinter` -> `pointer`


<!-- Sent from Reviewable.io -->

2021-01-18 07:20 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-18 15:29 UTC, mkow requested changes
> Reviewed 3 of 6 files at r4, 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRL3PMF28bF-XqMD701:bcufzcg) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This seems like a potentially serious issue, could you please debug/analyze why does it fail? I'm not ok with just shifting code around without understanding what caused the segfaults, the change could just temporarily mask it.
___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2Pn70BVZjc5mesny6:-MRL3jCmAxgi4sr-yN-e:bu50hc1) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, I'm accepting because it's a small change. But I don't understand what could cause this...
</blockquote></details>

But I'm not ;) (see the comment above)
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 95 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2J7jZ1nqsvKYvxyF3:-MRL4ecfBmkOvf95ebaf:b-a8ow6f) ([raw file](https://github.com/oscarlab/graphene/blob/2f4af9295bb35904c66bb5b646225a69a8331b02/LibOS/shim/src/fs/shim_fs_pseudo.c#L95)):*
> and a comment

The comment is ok, but my point was mostly about hardcoding magic constants in the code.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5Dva8p2diaN11S2z:-MRL5Dvb0w0F-nG6wqkM:bbcodtf) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
> ```
> sizeof(dirent_in_buf->next)
> ```

Should be: `alignof(*dirent_in_buf->next)` (+ include `stdalign.h`)
___
*[LibOS/shim/src/fs/proc/thread.c, line 678 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5_Ip5lLT_DqmjUYc:-MRL5_Ip5lLT_DqmjUYd:b-am2f) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/proc/thread.c#L678)):*
> ```C
> 
>     /* buf->next below must be pointer-aligned */
>     size_t buflen = ALIGN_UP(l + 1, sizeof(struct shim_dirent*));
> ```

ditto (`alignof`, not `sizeof`)
___
*[LibOS/shim/src/sys/shim_open.c, line 334 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5iOVD8NkuXY7ULew:-MRL5iOW4iFu3dh-3K4n:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/sys/shim_open.c#L334)):*
> ```C
> #define DIRENT_SIZE(len) \
>     ALIGN_UP(sizeof(struct linux_dirent) + sizeof(struct linux_dirent_tail) + (len) + 1, \
>              sizeof(b->d_ino))
> ```

ditto
___
*[LibOS/shim/src/sys/shim_open.c, line 437 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5zwn4MFgW-Sbo_zE:-MRL5zwn4MFgW-Sbo_zF:b-vb0wlq) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/sys/shim_open.c#L437)):*
> ```C
> /* Size calculation for dirent considering alignment restrictions for b->d_ino */
> #define DIRENT_SIZE(len) ALIGN_UP(sizeof(struct linux_dirent64) + (len) + 1, \
>                                   sizeof(b->d_ino))
> ```

ditto (`alignof`)


<!-- Sent from Reviewable.io -->

2021-01-18 17:31 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 2 of 5 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5Dva8p2diaN11S2z:-MRLYE-x44uUN6BPes3k:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> sizeof(dirent_in_buf->next)
> ```

Should be: `alignof(*dirent_in_buf->next)` (+ include `stdalign.h`)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 678 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5_Ip5lLT_DqmjUYc:-MRLYFI52DjWB8l-L7Op:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/proc/thread.c#L678)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`alignof`, not `sizeof`)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 334 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5iOVD8NkuXY7ULew:-MRLYFnv-vgQaHzcEgTI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/sys/shim_open.c#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 437 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5zwn4MFgW-Sbo_zE:-MRLYGUn-4FsKMWBnZq8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/sys/shim_open.c#L437)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`alignof`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-18 17:43 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 2 of 5 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRL_7V59xjFZoBJGtAX:bou4syd) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This seems like a potentially serious issue, could you please debug/analyze why does it fail? I'm not ok with just shifting code around without understanding what caused the segfaults, the change could just temporarily mask it.
</blockquote></details>

In instrumented the code like this now.
```
        debug("--> __rs_func=%p\n", __rs_func);
        debug("--> &__rs_func=%p\n", &__rs_func);
        debug("--> &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE]=%p\n", &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE]);
        const void *addr = &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE];
        //rs_func rs;
        rs_func rs = (&__rs_func)[cpent->cp_type - CP_FUNC_BASE];
        memcpy(&rs, addr, sizeof(rs));
```
I put in the previous offending line again.
Here's the output:

```
[P3838794:udp] restored memory from checkpoint
[P3838794:udp] receiving 2 PAL handles
[P3838794:udp] restoring checkpoint at 0x15554b178000 rebased from 0x15554b178000
[P3838794:udp] --> __rs_func=0x155551341527
[P3838794:udp] --> &__rs_func=0x155551413470
[P3838794:udp] --> &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE]=0x155551413500
```

Here's the definition of rs_func. So it's a function pointer. My guess is it doesn't like the odd address, but I cannot say.

LibOS/shim/include/shim_checkpoint.h:typedef int (*rs_func)(RS_FUNC_ARGS);

Hooking gdb to it, I don't see anything. 


<!-- Sent from Reviewable.io -->

2021-01-18 23:55 UTC, mkow requested changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRMsaz10QGcMMUeOwpt:b-t61hpg) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

In instrumented the code like this now.
```
        debug("--> __rs_func=%p\n", __rs_func);
        debug("--> &__rs_func=%p\n", &__rs_func);
        debug("--> &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE]=%p\n", &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE]);
        const void *addr = &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE];
        //rs_func rs;
        rs_func rs = (&__rs_func)[cpent->cp_type - CP_FUNC_BASE];
        memcpy(&rs, addr, sizeof(rs));
```
I put in the previous offending line again.
Here's the output:

```
[P3838794:udp] restored memory from checkpoint
[P3838794:udp] receiving 2 PAL handles
[P3838794:udp] restoring checkpoint at 0x15554b178000 rebased from 0x15554b178000
[P3838794:udp] --> __rs_func=0x155551341527
[P3838794:udp] --> &__rs_func=0x155551413470
[P3838794:udp] --> &(&__rs_func)[cpent->cp_type - CP_FUNC_BASE]=0x155551413500
```

Here's the definition of rs_func. So it's a function pointer. My guess is it doesn't like the odd address, but I cannot say.

LibOS/shim/include/shim_checkpoint.h:typedef int (*rs_func)(RS_FUNC_ARGS);

Hooking gdb to it, I don't see anything. 

</blockquote></details>

Tbh everything looks perfectly fine with the log you pasted. There's nothing wrong (maybe except performance-wise) with functions starting on odd addresses on x86.

Where's that crash occurring exactly? Could you paste its details?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5Dva8p2diaN11S2z:-MRMtRdDApQ_phj7_pQ_:b-l0ikw7) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Include is still missing.
___
*[LibOS/shim/src/fs/proc/thread.c, line 678 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5_Ip5lLT_DqmjUYc:-MRMtbdH4Jn51Ja2y5MG:b-q9pz) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/proc/thread.c#L678)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

missing include
___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r7](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRMupFL-f_aHrlKxmRB:-MRMupFL-f_aHrlKxmRC:b-aueaij) ([raw file](https://github.com/oscarlab/graphene/blob/e42b49d0c31b30878c4bee05ac828ce1cd256762/LibOS/shim/src/fs/proc/thread.c#L677)):*
> ```C
>         ;
> 
>     /* buf->next below must be pointer-aligned */
> ```

`must be pointer-aligned` -> `must be properly aligned` (`struct shim_dirent` may have different alignment than a pointer)
___
*[LibOS/shim/src/sys/shim_open.c, line 334 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5iOVD8NkuXY7ULew:-MRMtdzo-Bj6hu7MCgnZ:b-3kdjtk) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/sys/shim_open.c#L334)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> <<<<<<< HEAD
>              sizeof(b->d_ino))
> =======
>              alignof(b->d_ino))
> >>>>>>> 0fea7a38... fixup! [LibOS] Fix a getdents related pointer alignment issue (UBSAN)
> ```
</details>


incorrect rebase? ;)

+ missing include
___
*[LibOS/shim/src/sys/shim_open.c, line 437 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5zwn4MFgW-Sbo_zE:-MRMu7Ct3zhh8nmQ8sWa:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/sys/shim_open.c#L437)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[LibOS/shim/src/sys/shim_open.c, line 337 at r7](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRMuY0S6V6h8VRXz6Qb:-MRMuY0S6V6h8VRXz6Qc:bi7i7tr) ([raw file](https://github.com/oscarlab/graphene/blob/e42b49d0c31b30878c4bee05ac828ce1cd256762/LibOS/shim/src/sys/shim_open.c#L337)):*
> ```C
>              sizeof(b->d_ino))
> =======
>              alignof(b->d_ino))
> ```

Actually, why are we aligning to `d_ino` field here? What's special about this field?


<!-- Sent from Reviewable.io -->

2021-01-18 23:57 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRMvW-50njRRTkDquGg:bjy8gl1) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Tbh everything looks perfectly fine with the log you pasted. There's nothing wrong (maybe except performance-wise) with functions starting on odd addresses on x86.

Where's that crash occurring exactly? Could you paste its details?
</blockquote></details>

I doesn't get past this line above: `  rs_func rs = (&__rs_func)[cpent->cp_type - CP_FUNC_BASE];`


<!-- Sent from Reviewable.io -->

2021-01-18 23:57 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRMvafu7q_awv8ouirb:b-ungjqm) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I doesn't get past this line above: `  rs_func rs = (&__rs_func)[cpent->cp_type - CP_FUNC_BASE];`
</blockquote></details>

(this was the original code)


<!-- Sent from Reviewable.io -->

2021-01-18 23:58 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5Dva8p2diaN11S2z:-MRMvni2CRdSoHyBnLXs:bbil4t9) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Include is still missing.
</blockquote></details>

I didn't explicitly include it because 'it compiles' already.


<!-- Sent from Reviewable.io -->

2021-01-19 00:12 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRMy2IvBRBi3iAJk1cN:b6ft2dl) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

(this was the original code)
</blockquote></details>

By "get past" you mean stepping in GDB? Could you paste the assembly line (in Intel syntax plz) which crashed + register values?
Also, is there a simple way we could reproduce this crash?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r6](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRL5Dva8p2diaN11S2z:-MRMyZQn01PiVPS__3WA:b-1jhdo2) ([raw file](https://github.com/oscarlab/graphene/blob/e6e4b5b90834c149e162a489122be990c0f5c110/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I didn't explicitly include it because 'it compiles' already.
</blockquote></details>

We've had this discussion at least 3 times already under other PRs ;)
You need to directly include everything you use, otherwise this file will stop to compile after completely unrelated changes in other parts of the project (right now it works only because someone somewhere in the project already included stdalign.h).


<!-- Sent from Reviewable.io -->

2021-01-19 00:21 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 2 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/sys/shim_open.c, line 337 at r7](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRMuY0S6V6h8VRXz6Qb:-MRN0Bi79fEM7ZxRgVgu:b-l1808b) ([raw file](https://github.com/oscarlab/graphene/blob/e42b49d0c31b30878c4bee05ac828ce1cd256762/LibOS/shim/src/sys/shim_open.c#L337)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, why are we aligning to `d_ino` field here? What's special about this field?
</blockquote></details>

64 bit number.


<!-- Sent from Reviewable.io -->

2021-01-19 00:23 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 2 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/fs/proc/thread.c, line 677 at r7](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRMupFL-f_aHrlKxmRB:-MRN0e7h5onnC-V7oomX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e42b49d0c31b30878c4bee05ac828ce1cd256762/LibOS/shim/src/fs/proc/thread.c#L677)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`must be pointer-aligned` -> `must be properly aligned` (`struct shim_dirent` may have different alignment than a pointer)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 00:28 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 2 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRN15N85PClJad6iTl4:b4pnf6t) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

By "get past" you mean stepping in GDB? Could you paste the assembly line (in Intel syntax plz) which crashed + register values?
Also, is there a simple way we could reproduce this crash?
</blockquote></details>

This branch here has the Makefile changes for UBSAN: https://github.com/stefanberger/graphene/tree/stefanberger/ubsan_keep

You will have to put back the offending line into the code, though, like I did above.

Run:

```
make clean
make UBSAN=1 DEBUG=1 -j64
cd LibOS/shim/test/regression
make UBSAN=1 DEBUG=1 -j64
gdb --args ~/tmp/graphene.upstream/Runtime/pal-Linux ~/tmp/graphene.upstream/Runtime/ init ./udp
```


<!-- Sent from Reviewable.io -->

2021-01-19 00:42 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 2 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRN4P6E7FbUjRCLEd3U:b-jnhdrc) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This branch here has the Makefile changes for UBSAN: https://github.com/stefanberger/graphene/tree/stefanberger/ubsan_keep

You will have to put back the offending line into the code, though, like I did above.

Run:

```
make clean
make UBSAN=1 DEBUG=1 -j64
cd LibOS/shim/test/regression
make UBSAN=1 DEBUG=1 -j64
gdb --args ~/tmp/graphene.upstream/Runtime/pal-Linux ~/tmp/graphene.upstream/Runtime/ init ./udp
```
</blockquote></details>

The last debugging output then looks like this here:
```
[P3939406:udp] restored memory from checkpoint
[P3939406:udp] receiving 2 PAL handles
[P3939406:udp] restoring checkpoint at 0x14a023864000 rebased from 0x14a023864000
```
Nothing happens after this once the offending line is in there. Take it out and works fine.

I tried removing the SEGV handler on the Pal level but that causes issues elsewhere. I had hoped for termination of the program with a UBSAN message.


<!-- Sent from Reviewable.io -->

2021-01-19 00:58 UTC, mkow reviewed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRN6_hP4joY4T-BYOHf:bl2b68r) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

The last debugging output then looks like this here:
```
[P3939406:udp] restored memory from checkpoint
[P3939406:udp] receiving 2 PAL handles
[P3939406:udp] restoring checkpoint at 0x14a023864000 rebased from 0x14a023864000
```
Nothing happens after this once the offending line is in there. Take it out and works fine.

I tried removing the SEGV handler on the Pal level but that causes issues elsewhere. I had hoped for termination of the program with a UBSAN message.
</blockquote></details>

Thanks, I have a repro, will debug it tomorrow.

FYI: I had to change the linking path in `-L` on Ubuntu 20.04 to something inside GCC directory to make it build, otherwise it couldn't find `libubsan`.
FYI2: You can do just `./pal_loader GDB udp`, no need for this complex invocation (also, you're missing our GDB scripts this way, which add proper symbols to GDB).
___
*[LibOS/shim/src/sys/shim_open.c, line 337 at r7](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRMuY0S6V6h8VRXz6Qb:-MRN1TVZ8aqvuyazG4_Z:b-uzwahf) ([raw file](https://github.com/oscarlab/graphene/blob/e42b49d0c31b30878c4bee05ac828ce1cd256762/LibOS/shim/src/sys/shim_open.c#L337)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

64 bit number.
</blockquote></details>

But why this one, and only this single field? This seems like an arbitrarily chosen variable which has 8 bytes, which is effectively the same as hardcoding "8" here.

So, what we're actually trying to align here and what had an incorrect alignment before? We should use `alignof` of the thing we're trying to properly align, not just some random thing which is equal to "8". I guess this code may start crashing if we add a field with 16-byte alignment to dirent struct...


<!-- Sent from Reviewable.io -->

2021-01-19 01:16 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_open.c, line 337 at r7](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRMuY0S6V6h8VRXz6Qb:-MRNCcT79TkGo4NGM7EA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e42b49d0c31b30878c4bee05ac828ce1cd256762/LibOS/shim/src/sys/shim_open.c#L337)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But why this one, and only this single field? This seems like an arbitrarily chosen variable which has 8 bytes, which is effectively the same as hardcoding "8" here.

So, what we're actually trying to align here and what had an incorrect alignment before? We should use `alignof` of the thing we're trying to properly align, not just some random thing which is equal to "8". I guess this code may start crashing if we add a field with 16-byte alignment to dirent struct...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 07:54 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-19 14:38 UTC, mkow requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r3](https://reviewable.io/reviews/oscarlab/graphene/2089#-MR2LWz-0939SG7n8r8G:-MRQ207p82YoklTAIJEo:bgebxza) ([raw file](https://github.com/oscarlab/graphene/blob/6ff2f12906d9718beafb5543249d1ea2c2060cb7/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Thanks, I have a repro, will debug it tomorrow.

FYI: I had to change the linking path in `-L` on Ubuntu 20.04 to something inside GCC directory to make it build, otherwise it couldn't find `libubsan`.
FYI2: You can do just `./pal_loader GDB udp`, no need for this complex invocation (also, you're missing our GDB scripts this way, which add proper symbols to GDB).
</blockquote></details>

Ok, from what I see this is _not_ an alignment issue, UBSAN correctly thinks that `__rs_func` is just a single object (because that's how it's declared) and we're accessing out-of-bounds memory. Normally it doesn't blow up because of the hacks in checkpointing code, which use a linker script to turn `__rs_func` into an array (but C still thinks it's a single object).

So, the fix is to declare `__rs_func` as an array of unknown size (`extern const rs_func __rs_func[];`) and then do `rs_func rs = __rs_func[cpent->cp_type - CP_FUNC_BASE];` here. After these fixes the `udp` test works under UBSAN for me.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r9](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRPf1fsEM4KM9PpDgcG:-MRPf1fsEM4KM9PpDgcH:b-4cphsl) ([raw file](https://github.com/oscarlab/graphene/blob/918f75aa37122f3420bba2a707f000663896197d/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
> ```C
>             /* directory entry has a hardcoded name */
>             size_t name_size   = strlen(ent->name) + 1;
>             /* all directory entries must be aligned on the dirent::next pointer size */
> ```

`dirent::next pointer size` -> `*dirent::next alignment`


<!-- Sent from Reviewable.io -->

2021-01-19 14:50 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 4 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r9](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRPf1fsEM4KM9PpDgcG:-MRQ73dsE6bhErk7vmti:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/918f75aa37122f3420bba2a707f000663896197d/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`dirent::next pointer size` -> `*dirent::next alignment`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 15:04 UTC, mkow requested changes
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r10](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ9dAD4Y8LiLnBb950:-MRQ9dAECG5nyXSHCpm-:b-h9j3y4) ([raw file](https://github.com/oscarlab/graphene/blob/1b878afb032a6f1694865faf6ebc209340f4a65c/LibOS/shim/src/shim_checkpoint.c#L465)):*
> ```C
>         }
> 
>         /* avoid pointer alignment issues on 'rs' with additional pointer */
> ```

the comment is now obsolete
___
*[LibOS/shim/src/shim_checkpoint.c, line 466 at r10](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ9IDxE0ONn2C5adOJ:-MRQ9IDxE0ONn2C5adOK:b-6btijx) ([raw file](https://github.com/oscarlab/graphene/blob/1b878afb032a6f1694865faf6ebc209340f4a65c/LibOS/shim/src/shim_checkpoint.c#L466)):*
> ```C
> 
>         /* avoid pointer alignment issues on 'rs' with additional pointer */
>         rs_func rs = (__rs_func)[cpent->cp_type - CP_FUNC_BASE];
> ```

no need for parentheses
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 97 at r9](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRPf1fsEM4KM9PpDgcG:-MRQ9rvF1TYKU3L1u4xv:b-fl3ntg) ([raw file](https://github.com/oscarlab/graphene/blob/918f75aa37122f3420bba2a707f000663896197d/LibOS/shim/src/fs/shim_fs_pseudo.c#L97)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about the rest of the sentence? (see my suggestion above)
We're not aligning to the pointer size, but to the object alignment (which may be different than a pointer size).


<!-- Sent from Reviewable.io -->

2021-01-19 15:21 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/shim_checkpoint.c, line 465 at r10](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ9dAD4Y8LiLnBb950:-MRQE7aD-sx2goAEY7wG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1b878afb032a6f1694865faf6ebc209340f4a65c/LibOS/shim/src/shim_checkpoint.c#L465)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

the comment is now obsolete
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 466 at r10](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ9IDxE0ONn2C5adOJ:-MRQE7rT2JyFgzUy-WLy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1b878afb032a6f1694865faf6ebc209340f4a65c/LibOS/shim/src/shim_checkpoint.c#L466)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need for parentheses
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 15:25 UTC, mkow requested changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-19 15:28 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-19 15:29 UTC, mkow commented
Jenkins, retest this please

2021-01-19 16:49 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r8, 1 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/include/shim_checkpoint.h, line 104 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQY-ve5Ek0pGhtXwga:-MRQY-ve5Ek0pGhtXwgb:bi7lyn9) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/include/shim_checkpoint.h#L104)):*
> ```objc
> extern const char* __cp_name;
> extern const cp_func __cp_func;
> extern const rs_func __rs_func[];
> ```

Lol :)

Technically should do the same with the two other arrays `__cp_name` and `__cp_func`.


<!-- Sent from Reviewable.io -->

2021-01-19 16:52 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_checkpoint.h, line 104 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQY-ve5Ek0pGhtXwga:-MRQYjXw7Se-qwVaR6mg:b-for0wt) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/include/shim_checkpoint.h#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Lol :)

Technically should do the same with the two other arrays `__cp_name` and `__cp_func`.
</blockquote></details>

Yeah.
But - I tried this and everything explodes if you try to touch `__cp_func`. So, I'd leave it for some other PR.


<!-- Sent from Reviewable.io -->

2021-01-19 16:59 UTC, boryspoplawski approved these changes
> Reviewed 1 of 6 files at r4, 1 of 3 files at r8, 1 of 1 files at r9, 1 of 3 files at r10, 1 of 1 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_open.c, line 334 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ_5Ff6uvyTXWTSt-Q:-MRQ_5Ff6uvyTXWTSt-R:bype9wn) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/src/sys/shim_open.c#L334)):*
> ```C
> /* Size calculation for dirent considering alignment restrictions for b->d_ino */
> #define DIRENT_SIZE(len) \
>     ALIGN_UP(sizeof(struct linux_dirent) + sizeof(struct linux_dirent_tail) + (len) + 1, \
> ```

I think this `1` is not needed. `linux_dirent_tail::pad` is exactly to store the string ending nullbyte.
Not blocking as this is a present issue.


<!-- Sent from Reviewable.io -->

2021-01-19 17:04 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/include/shim_checkpoint.h, line 104 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQY-ve5Ek0pGhtXwga:-MRQaXpACjQ9DNBK_Yvg:b1quyh7) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/include/shim_checkpoint.h#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah.
But - I tried this and everything explodes if you try to touch `__cp_func`. So, I'd leave it for some other PR.
</blockquote></details>

Could we put at least a FIXME or TODO about this? We can add it as part of the rebase.


<!-- Sent from Reviewable.io -->

2021-01-19 17:13 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_checkpoint.h, line 104 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQY-ve5Ek0pGhtXwga:-MRQcOJS3no8_ZMCbMre:bj9o9d8) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/include/shim_checkpoint.h#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we put at least a FIXME or TODO about this? We can add it as part of the rebase.
</blockquote></details>

Ok, let me do the final rebase and add this.
___
*[LibOS/shim/src/sys/shim_open.c, line 334 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ_5Ff6uvyTXWTSt-Q:-MRQcUhm5MWBElByQSWu:b-4aso9b) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/src/sys/shim_open.c#L334)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think this `1` is not needed. `linux_dirent_tail::pad` is exactly to store the string ending nullbyte.
Not blocking as this is a present issue.
</blockquote></details>

Let's leave this for later, as this was already present before and we already had a lot of iterations on this PR.


<!-- Sent from Reviewable.io -->

2021-01-19 17:17 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_open.c, line 334 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ_5Ff6uvyTXWTSt-Q:-MRQdYtb8QC0zKk-PKAv:b-o9kfmp) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/src/sys/shim_open.c#L334)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Let's leave this for later, as this was already present before and we already had a lot of iterations on this PR.
</blockquote></details>

Sure, but maybe add a TODO in the code?


<!-- Sent from Reviewable.io -->

2021-01-19 17:44 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_checkpoint.h, line 104 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQY-ve5Ek0pGhtXwga:-MRQjYLc947fNGD7DD32:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/include/shim_checkpoint.h#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, let me do the final rebase and add this.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQjb0mERI5wmJPvg0Z:-MRQjb0mERI5wmJPvg0_:bq00qxw) ([raw file](https://github.com/oscarlab/graphene/blob/0ffe04b1d0595cf1c942601f01a4e6f5903de81c/LibOS/shim/src/fs/shim_fs_hash.c#L17)):*
> ```C
>     for (; len >= sizeof(hash); p += sizeof(hash), len -= sizeof(hash)) {
>         memcpy(&tmp, p, sizeof(tmp)); /* avoid pointer alignment issues */
>         hash += *((HASHTYPE*)&tmp);
> ```

FYI: During rebase I noticed that this cast was not needed (`tmp` is already `HASHTYPE`)
___
*[LibOS/shim/src/sys/shim_open.c, line 334 at r12](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQ_5Ff6uvyTXWTSt-Q:-MRQhQOv2eZgORz9TTLr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e22974029130ea9ec1aa37874b67b9d77f07a38/LibOS/shim/src/sys/shim_open.c#L334)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, but maybe add a TODO in the code?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 17:45 UTC, mkow commented
Jenkins, retest this please

2021-01-19 17:46 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQjqPz-z1QiQrbhGSE:-MRQjqPz-z1QiQrbhGSF:b-fg7ima) (no related file):*
@stefanberger: I squashed two TODOs requested by @dimakuv and @boryspoplawski into your commits, please check if you're fine with these changes (if not I can split them into separate a commit or drop). Just wanted to speed things up a bit and added them myself + did the rebase.

---


<!-- Sent from Reviewable.io -->

2021-01-19 17:53 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @stefanberger)



<!-- Sent from Reviewable.io -->

2021-01-19 17:59 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQjqPz-z1QiQrbhGSE:-MRQn9Tk1ou6xqghfZST:b-dl0osg) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@stefanberger: I squashed two TODOs requested by @dimakuv and @boryspoplawski into your commits, please check if you're fine with these changes (if not I can split them into separate a commit or drop). Just wanted to speed things up a bit and added them myself + did the rebase.
</blockquote></details>

@mkow no problem, fine by me.

---


<!-- Sent from Reviewable.io -->

2021-01-19 18:00 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2089)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2089#-MRQjqPz-z1QiQrbhGSE:-MRQnSRgDNyQEsEK5y6d:bbv1th0) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

@mkow no problem, fine by me.
</blockquote></details>

awesome, thanks :)

---


<!-- Sent from Reviewable.io -->

2021-01-19 19:11 UTC, merged