[LibOS] Rework signal handling
oscarlab/graphene pull request #2090
Opened 2021-01-15 00:52 UTC by boryspoplawski

## Description of the changes 
This PR completely reworks signal handling and (as a side effect) syscall emulation in LibOS.
More info in commit message and appropriate places in code.

Please point me to places in the code that need more comments/explanation.

Closes #1218

(This is next version of #2071)

2021-01-15 01:41 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 0 of 55 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux/pal_host.h, line 157 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2gtnR1XLIaCh2Bmse:-MR2gtnR1XLIaCh2Bmsf:b-n91hmj) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/Pal/src/host/Linux/pal_host.h#L157)):*
> ```objc
> #define HANDLE_TYPE(handle) ((handle)->hdr.type)
> 
> // TODO: remove these
> ```

As a follow up PR, not to generate many conflicts here.


<!-- Sent from Reviewable.io -->

2021-01-15 07:08 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 0 of 55 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/shim_defs.h, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3qQaIEmTyOLtU4yzB:-MR3qQaIEmTyOLtU4yzC:b-3wdxj8) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/include/shim_defs.h#L6)):*
> ```objc
> #include "shim_syscalls.h"
> 
> /* Names taken from the Linux kernel. */
> ```

value is also taken from kernel?
___
*[LibOS/shim/include/shim_thread.h, line 224 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3d2O9EGPYmb_jGyKZ:-MR3d2O9EGPYmb_jGyK_:bdk7ku9) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/include/shim_thread.h#L224)):*
> ```objc
> static inline void thread_wakeup(struct shim_thread* thread) {
>     DkEventSet(thread->scheduler_event);
>     DkThreadResume(thread->pal_handle);
> ```

Why is this needed?
___
*[LibOS/shim/src/shim_context-x86_64.c, line 234 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3e6N7EI_dUZ-QTzQc:-MR3e6N7EI_dUZ-QTzQd:b-39zvz7) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/shim_context-x86_64.c#L234)):*
> ```
> '\0'
> ```

0
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 76 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3pQtGBSOcTX0ZmVOq:-MR3pQtGBSOcTX0ZmVOr:bupxao8) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L76)):*
> ```C
> } SIGHANDLER_T;
> 
> static SIGHANDLER_T default_sighandler[NUM_SIGS] = {
> ```

nitpick: const
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 610 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3hInVCTHhmBnBB71l:-MR3hInVCTHhmBnBB71m:b-tthmjv) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L610)):*
> ```
> context_is_libos(context)
> ```

This needs to be more exact. For example rip is in return_from_syscall, context_is_libos() is true, but it will just return to app. So the signal is queued, but won't be delivered until next app syscall.

The boundary needs to be determined and the code would be trickey.
and vDSO would complicates it.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 795 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3odbgANC5KctbSPpk:-MR3odbh6oYfZTr58F0i:buiq0t6) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L795)):*
> ```C
>             long sysnr = shim_get_tcb()->context.syscall_nr;
>             if (sysnr >= 0) {
>                 switch (pal_context_get_retval(context)) {
> ```

It's very nice to naturally handle syscall restart.
___
*[LibOS/shim/src/sys/shim_clone.c, line 325 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3dK_-8SCfMkmzsO7Z:-MR3dK_-8SCfMkmzsO7_:b-yomejz) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/sys/shim_clone.c#L325)):*
> ```C
>         thread->clear_child_tid = child_tidptr;
> 
>     unsigned long tls_base = flags & CLONE_SETTLS ? tls : get_tls_base();
> ```

nice catch.
___
*[LibOS/shim/src/vdso/vdso.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2dN3s3YY6nt5BjMzR:-MR2dN3s3YY6nt5BjMzS:bj6zifs) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/LibOS/shim/src/vdso/vdso.c#L15)):*
> ```C
> 
> /* XXX(borysp): What's the point of manual relocations/emulation of GOT here? Why cannot this be
>  * just normal, generic relocation? Wouldn't loading vdso as first library be enough? */
> ```

The reason is to support fork emulated by graphene.
graphene fork does host fork and can load libos into new address.
which means vDSO bundled with LibOS can have new address. So
- transfer also vDSO from parent into child. so app sees vdso at the same address.
- but the entry point for libos, syscalldb, can be different address, so fixup the entry point.

With recent manifest redesign, the situation has changed a bit.
___
*[Pal/src/host/Linux/db_exception.c, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3kMsH3cti_2UB9Oxm:-MR3kMsH3cti_2UB9Oxn:bse2shk) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/Pal/src/host/Linux/db_exception.c#L44)):*
> ```
>  SIGINT,
> ```

What if SIGINT arrived?
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2X8Ur-6fmcJRjEIDz:-MR3lpub6S4FC4TrgOzO:b4874im) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/Pal/src/host/Linux-SGX/db_exception.c#L283)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Summon @dimakuv @yamahata
</blockquote></details>

This function is used only when async signal arrived during ocall. so this isn't called for sync signal. 

My feeling is, this function should be deleted eventually.
the current logic should be sorted out somehow.


<!-- Sent from Reviewable.io -->

2021-01-15 07:08 UTC, yamahata reviewed
> Reviewed 51 of 55 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2021-01-15 12:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR4rTMA0ymuX0uFb0be:-MR4rTMB5owlSSJqWTdY:b-dhc8b6) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
> ```C
>  */
> static void* vdso_addr __attribute_migratable                       = NULL;
> static ElfW(Addr)* __vdso_shim_clock_gettime __attribute_migratable = NULL;
> ```

Why does `syscalldb` need to be in the vdso object (and not just LibOS)?

Also, why do we need the vdso object at all? I get that `gettimeofday` etc. will be fast anyway (no context switch to kernel needed), so no need to include them in vdso, but then is there anything preventing us from removing all of this? I think at least glibc should handle vdso not being vailable.

See also #2086 - I can rebase it once this PR is merged, but the point is that I would like `syscalldb` not to be exposed for dynamic linking, just passed through a pointer in TCB.
___
*[LibOS/shim/src/vdso/vdso.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2dN3s3YY6nt5BjMzR:-MR4t1HF4IQrfKx8q8se:b-8svur0) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/LibOS/shim/src/vdso/vdso.c#L15)):*
>graphene fork does host fork and can load libos into new address.

Does that actually happen? I asked @mkow and he didn't think so.

Or is it that we still want to keep this possibility open?
___
*[LibOS/shim/test/regression/test_libos.py, line 614 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR4tuFt-TZe_vITBLgD:-MR4tuFt-TZe_vITBLgE:bw9s571) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/test/regression/test_libos.py#L614)):*
> ```Python
> 
>     # TODO: DISABLED TEMPORARILY
>     #def test_000_gdb_backtrace(self):
> ```

Any problems with this? I would expect we need to store the old IP value on the new stack somewhere, and also use the `__morestack` trick (same as we do on enclave exit).


<!-- Sent from Reviewable.io -->

2021-01-15 16:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 53 of 55 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/include/shim_defs.h, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3qQaIEmTyOLtU4yzB:-MR5npXCAMUTAgDfBeDy:b-nrc9kh) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/include/shim_defs.h#L6)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

value is also taken from kernel?
</blockquote></details>

Base value (512) is, but they rest might not be, i.e. I've just assigned them iteratively.
Update: seems to be exactly as in kernel, should I update the comment?
___
*[LibOS/shim/include/shim_thread.h, line 224 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3d2O9EGPYmb_jGyKZ:-MR5oCb955WgW4pgdlNI:b-1dnlh7) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/include/shim_thread.h#L224)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

Hmm, now I think of it, it might have been a mistake. I thought that `thread_wakeup` should also interrupt thread, even if it is not sleeping on `scheduler_event`, but these are probably 2 different things and should be done separately (i.e. sometimes we do not need/want to interrupt it). Let me think about it (I'll probably drop this change).
___
*[LibOS/shim/src/shim_context-x86_64.c, line 234 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3e6N7EI_dUZ-QTzQc:-MR5rHtZ4PkiTr5kb6FO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/shim_context-x86_64.c#L234)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> '\0'
> ```

0
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 76 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3pQtGBSOcTX0ZmVOq:-MR5rW6c1h--wFGOwjoW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L76)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nitpick: const
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 610 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3hInVCTHhmBnBB71l:-MR5rbFL35X_KXXEG_nm:b-xm6yqb) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L610)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> context_is_libos(context)
> ```

This needs to be more exact. For example rip is in return_from_syscall, context_is_libos() is true, but it will just return to app. So the signal is queued, but won't be delivered until next app syscall.

The boundary needs to be determined and the code would be trickey.
and vDSO would complicates it.
</blockquote></details>

This is true, but that should be fine in general case, I suppose? On normal Linux (async) signals are delivered only on transition from kernel to user space, so they can too be delayed for arbitrary time interval. The only difference is that on Linux in normal case scheduler will preempt a process and cause a signal delivery from time to time, but I think that can be delayed arbitrarily in some cases, couldn't it?
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR4rTMA0ymuX0uFb0be:-MR5tGZ69rKbTedTQDtL:bqr05ma) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Why does `syscalldb` need to be in the vdso object (and not just LibOS)?

Also, why do we need the vdso object at all? I get that `gettimeofday` etc. will be fast anyway (no context switch to kernel needed), so no need to include them in vdso, but then is there anything preventing us from removing all of this? I think at least glibc should handle vdso not being vailable.

See also #2086 - I can rebase it once this PR is merged, but the point is that I would like `syscalldb` not to be exposed for dynamic linking, just passed through a pointer in TCB.
</blockquote></details>

See the comment in `vdso.c`.
I only made this code work with other changes, which requires to go through `syscalldb` when entering LibOS (the old code called `shim_do_*` directly, which is now prohibited.
Why do we need vdso at all? No idea, but I suppose glibc requires it, or some weird apps somehow called it directly, because the world is evil.
Actually what's the problem? We can add a similar stub (just like `syscalldb`, calling `gs`) here too. Possibly just include the header from glibc patches, I don't see any reason for it not to work.
___
*[LibOS/shim/src/vdso/vdso.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2dN3s3YY6nt5BjMzR:-MR5t_rZ72IZaKPVvrve:bvusaqz) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/LibOS/shim/src/vdso/vdso.c#L15)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>graphene fork does host fork and can load libos into new address.

Does that actually happen? I asked @mkow and he didn't think so.

Or is it that we still want to keep this possibility open?
</blockquote></details>

I'm not sure what's the situation now, but before loader rework, Pal loaded LibOS, which meant it could land at any address.
___
*[LibOS/shim/src/vdso/vdso.c, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR5tn1M3PCeR7nmy5Uv:-MR5tn1NEzVXwjiV46RO:bw440ay) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/vdso/vdso.c#L14)):*
> ```C
> #include "vdso_syscall.h"
> 
> /* XXX(borysp): What's the point of manual relocations/emulation of GOT here? Why cannot this be
> ```

TODO: remove this comment (answer below)
___
*[LibOS/shim/test/regression/test_libos.py, line 614 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR4tuFt-TZe_vITBLgD:-MR5v46k7Q-YQoAT-HS3:b-68l3i) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/test/regression/test_libos.py#L614)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Any problems with this? I would expect we need to store the old IP value on the new stack somewhere, and also use the `__morestack` trick (same as we do on enclave exit).
</blockquote></details>

Yes, gdb is stupid and does not understand stack switching unless it happens in function `__morestack`. I've just yet not invested enough time into investigating how to make it work, will do after this PR is "generally" accepted.
___
*[Pal/src/host/Linux/db_exception.c, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3kMsH3cti_2UB9Oxm:-MR5vNKbBI7UVcRR9opo:b-4b2n2z) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/Pal/src/host/Linux/db_exception.c#L44)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>  SIGINT,
> ```

What if SIGINT arrived?
</blockquote></details>

It's completely ignored, as we discussed it on one of the weekly calls a while ago. The reasoning is: we do **not** want to inject host signals at all, but there is one situation that seems useful: gracefully exit an application (e.g. web server etc.). For [...]

2021-01-15 17:52 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 53 of 55 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR4rTMA0ymuX0uFb0be:-MR62XBL0AUazOCLnDzh:b-m61czi) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
Oh, so gettimeofday etc. are still available through vdso, it's just that we need to keep this one address (`__vdso_syscalldb`) up to date. I misunderstood and somehow thought you are removing these functions. Never mind.

>Actually what's the problem? We can add a similar stub (just like syscalldb, calling gs) here too. Possibly just include the header from glibc patches, I don't see any reason for it not to work.

You mean so that the stub will be imported by glibc/application code? I thought about this but AFAICT, functions from vdso are not linked for you. You have to parse the vdso page and find them yourself (or [call dlopen and dlsym](https://github.com/torvalds/linux/blob/v5.9/tools/testing/selftests/x86/test_vdso.c#L90) - I dug into glibc code and it looks like it also does that). And anyway, I'd need this pretty early in `ld.so` startup, before it issues any system call.
___
*[LibOS/shim/src/vdso/vdso.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2dN3s3YY6nt5BjMzR:-MR66eoI0g0_iPHIhkdj:b-xe03b6) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/LibOS/shim/src/vdso/vdso.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm not sure what's the situation now, but before loader rework, Pal loaded LibOS, which meant it could land at any address.
</blockquote></details>

Right, so if it changed, it was relatively recently. I think it'd be nice to be able to assume that someday (isn't the whole "checkpointing" machinery, with rebasing values, because of LibOS possibly changing location?) but that's probably for later.


<!-- Sent from Reviewable.io -->

2021-01-15 18:46 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 53 of 55 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR4rTMA0ymuX0uFb0be:-MR6LtPf-JC2opcxEV7f:b7s1uah) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh, so gettimeofday etc. are still available through vdso, it's just that we need to keep this one address (`__vdso_syscalldb`) up to date. I misunderstood and somehow thought you are removing these functions. Never mind.

>Actually what's the problem? We can add a similar stub (just like syscalldb, calling gs) here too. Possibly just include the header from glibc patches, I don't see any reason for it not to work.

You mean so that the stub will be imported by glibc/application code? I thought about this but AFAICT, functions from vdso are not linked for you. You have to parse the vdso page and find them yourself (or [call dlopen and dlsym](https://github.com/torvalds/linux/blob/v5.9/tools/testing/selftests/x86/test_vdso.c#L90) - I dug into glibc code and it looks like it also does that). And anyway, I'd need this pretty early in `ld.so` startup, before it issues any system call.
</blockquote></details>

I mean if we use `jmp *%gs:syscalldb` then there is no need for linking (or any other way of chaning syscalldb address) so that works for you, right?
Yeah, vdso is not meant to be used by apps directly, but you know, app sometimes do weird things and we want to be as similar to normal Linux as possible
___
*[LibOS/shim/src/vdso/vdso.c, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2dN3s3YY6nt5BjMzR:-MR6MNzfAFTyuFHNIbF1:bkvrwou) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/LibOS/shim/src/vdso/vdso.c#L15)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Right, so if it changed, it was relatively recently. I think it'd be nice to be able to assume that someday (isn't the whole "checkpointing" machinery, with rebasing values, because of LibOS possibly changing location?) but that's probably for later.
</blockquote></details>

Checkpointing needs rebasing in case that the checkpoint blob is allocated at different address, as it has self-referencing pointers inside.


<!-- Sent from Reviewable.io -->

2021-01-15 19:04 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 53 of 55 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR4rTMA0ymuX0uFb0be:-MR6PoYd9btCBirNt823:bdkx469) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
>I mean if we use jmp *%gs:syscalldb then there is no need for linking (or any other way of chaning syscalldb address) so that works for you, right?

That's right, it works for me.


<!-- Sent from Reviewable.io -->

2021-01-15 20:35 UTC, stefanberger reviewed
> Reviewed 50 of 55 files at r1, 3 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_clone.c, line 325 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3dK_-8SCfMkmzsO7Z:-MR6kHiQ-YNq0UzI4gH4:bpv3rhb) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/sys/shim_clone.c#L325)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nice catch.
</blockquote></details>

Can you use `... ? tls_to_tls_base(tls) : get_tls_base()` ?


<!-- Sent from Reviewable.io -->

2021-01-15 20:51 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_clone.c, line 32 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6o5rw3seLHX0yLv21:-MR6o5rw3seLHX0yLv22:b5fn8d6) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/src/sys/shim_clone.c#L32)):*
> ```C
>     void* stack;
>     unsigned long tls_base;
>     PAL_CONTEXT* regs;
> ```

I wished this alone could be split off.
___
*[LibOS/shim/src/sys/shim_exit.c, line 158 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6kheA5d7CfVCwmI1G:-MR6kheA5d7CfVCwmI1H:b-w8d28e) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/sys/shim_exit.c#L158)):*
> ```C
> }
> 
> noreturn long shim_do_exit_group(int error_code) {
> ```

It would be minot, but can we split this off?
___
*[LibOS/shim/src/sys/shim_exit.c, line 168 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6koKbAFxfxGw3_aj9:-MR6koKbAFxfxGw3_ajA:bs4q9op) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/sys/shim_exit.c#L168)):*
> ```C
> }
> 
> noreturn long shim_do_exit(int error_code) {
> ```

Ditto.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6kyS_5HauIMguHXyG:-MR6kyS_5HauIMguHXyH:b-3ermv7) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/src/sys/shim_sigaction.c#L30)):*
> ```C
> #include "shim_utils.h"
> 
> long shim_do_rt_sigaction(int signum, const struct __kernel_sigaction* act,
> ```

Also split off the renaming of this call?
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 68 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6l54Q8aeTuusy4hpv:-MR6l54Q8aeTuusy4hpw:bv2i47c) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/src/sys/shim_sigaction.c#L68)):*
> ```C
> }
> 
> long shim_do_rt_sigreturn(void) {
> ```

Minor, but also here.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 86 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6l8NI7_GfNw2C6A_J:-MR6l8NI7_GfNw2C6A_K:bs5x6n2) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/src/sys/shim_sigaction.c#L86)):*
> ```C
> }
> 
> long shim_do_rt_sigprocmask(int how, const __sigset_t* set, __sigset_t* oldset) {
> ```

... and here...
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 181 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6lGTi1O_tdDtiDyDh:-MR6lGTi1O_tdDtiDyDi:b9e6w46) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/src/sys/shim_sigaction.c#L181)):*
> ```C
> }
> 
> long shim_do_rt_sigsuspend(const __sigset_t* mask_ptr, size_t setsize) {
> ```

Also this one.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 224 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6lLkOBXCsAeRqcv1T:-MR6lLkOBXCsAeRqcv1U:b3sgkp4) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/src/sys/shim_sigaction.c#L224)):*
> ```C
> }
> 
> long shim_do_rt_sigpending(__sigset_t* set, size_t sigsetsize) {
> ```

.. and this one


<!-- Sent from Reviewable.io -->

2021-01-15 20:54 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_table.h, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6osnGCm2E3U_nZzxO:-MR6osnGCm2E3U_nZzxP:bqb0e5u) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/include/shim_table.h#L40)):*
> ```objc
>                           struct __kernel_sigaction* oldact, size_t sigsetsize);
> long shim_do_rt_sigprocmask(int how, const __sigset_t* set, __sigset_t* oldset);
> long shim_do_rt_sigreturn(void);
> ```

Split off the renamings?


<!-- Sent from Reviewable.io -->

2021-01-16 17:15 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 47 of 55 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/include/shim_table.h, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR6osnGCm2E3U_nZzxO:-MRB5FvSDKzdeDMI7wox:b-7rxzy2) ([raw file](https://github.com/oscarlab/graphene/blob/da5406b56ae375f982b0db7217dc010b0fa65125/LibOS/shim/include/shim_table.h#L40)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Split off the renamings?
</blockquote></details>

Why? What's the point? You do not change these in you port, do you?
___
*[LibOS/shim/src/sys/shim_clone.c, line 325 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3dK_-8SCfMkmzsO7Z:-MRB6avr-aaAenlISII1:b-jnm90a) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/sys/shim_clone.c#L325)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Can you use `... ? tls_to_tls_base(tls) : get_tls_base()` ?
</blockquote></details>

I would rather rename `get_tls_base` to `get_tls` and `set_tls` accordingly. This value is arch specific and can be only understood by arch specific code and it might have nothing to do with a `base`.


<!-- Sent from Reviewable.io -->

2021-01-17 05:30 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 47 of 55 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/sys/shim_clone.c, line 325 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3dK_-8SCfMkmzsO7Z:-MRDoYrz-npmkru66pSh:b5uty71) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/sys/shim_clone.c#L325)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would rather rename `get_tls_base` to `get_tls` and `set_tls` accordingly. This value is arch specific and can be only understood by arch specific code and it might have nothing to do with a `base`.
</blockquote></details>

Also good.


<!-- Sent from Reviewable.io -->

2021-01-18 14:35 UTC, dimakuv requested changes
> Reviewed 39 of 55 files at r1, 1 of 4 files at r2, 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 53 of 55 files reviewed, 63 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2Wx4y7LYM_bVjnOWt:-MRKGZJj1JlblFcIrN7W:b-dbvux9) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

There is (at least) one known issue: I don't know how to handle a case, where we are executing a blocking syscall (e.g. read) and a signal comes after we enter LibOS, but before we do actual blocking host syscall. In such case we will just block and handle the signal only when returning to the user app (which can take arbitrarily long, since read can block indefinitely.
I see only one solution: just say that signals can arrive anytime and ignore the problem :) There is one caveat tho: we would need to change the way time_to_die is handled - probably introduce something like old preemption counter and check it every time we reach 0 (i.e. when we give up last lock). Generally speaking - doable.
</blockquote></details>

This looks like the case of an *async signal from another process in the same Graphene instance*? Or is it *all signals*? I'm trying to understand the scope of this issue.

And IIUC, if another signal comes during the blocking host syscall, Linux will interrupt it anyway and Graphene will unfreeze and handle the first "pending" signal, right? In this case, the sysadmin tool (or the user) can simply repeat the signal after couple seconds, and Graphene will continue working.

Is there a particular scenario when this will lead to Graphene hanging completely? Like a parent waiting for a child's SIGCHLD, and being unfortunate to get SIGCHLD right-before issuing a host-level `waitpid()`?

---
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 2 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKIg283dRbiTmQ5LD5:-MRKIg283dRbiTmQ5LD6:bgq89pn) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/glibc-patches/glibc-2.23.patch#L2)):*
> ```Diff
> diff --git a/Makeconfig b/Makeconfig
> index 87a22e88bed375d073663063dd4a93444d72ba25..b69ff41077a5f279bde52aac11f03604fa61ae65 100644
> ```

Could you regenerate these patches with `--full-index`? I forgot why we did this but I specifically changed it in this PR: https://github.com/oscarlab/graphene/pull/1641. You can ask Michal about the history of that (I guess we simply wanted to make it more explicit)?
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 82 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKJu2E1cnBruwUChEP:-MRKJu2E1cnBruwUChEQ:b-mewrio) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/glibc-patches/syscalldb-api.patch#L82)):*
> ```Diff
> +.macro SYSCALLDB
> +leaq .Lafter_syscalldb\@(%rip), %rcx
> +jmpq *syscalldb@GOTPCREL(%rip)
> ```

Are you using `jmp` instead of `call` to not mess with the user-level stack?
___
*[LibOS/shim/include/shim_defs.h, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3qQaIEmTyOLtU4yzB:-MRKKD51E0Iyzbs7eBHX:bwzz6uh) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/include/shim_defs.h#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Base value (512) is, but they rest might not be, i.e. I've just assigned them iteratively.
Update: seems to be exactly as in kernel, should I update the comment?
</blockquote></details>

Yes, please add `...and values are taken from...`
___
*[LibOS/shim/include/shim_defs.h, line 7 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKKaZXE4pnpgHWrTBn:-MRKKaZXE4pnpgHWrTBo:b-xi4532) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_defs.h#L7)):*
> ```objc
> 
> /* Names taken from the Linux kernel. */
> #define ERESTARTSYS     512 /* Usual case - restart if SA_RESTART is set. */
> ```

Maybe we should add an assert that these are greater than `LIBOS_SYSCALL_BOUND` (or `__NR_syscalls` which is the same)
___
*[LibOS/shim/include/shim_internal.h, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKL5n66csv_fjNI9W0:-MRKL5n66csv_fjNI9W1:br8o37c) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_internal.h#L76)):*
> ```objc
> void syscalldb(void);
> noreturn void shim_do_syscall(PAL_CONTEXT* context);
> noreturn void return_from_syscall(PAL_CONTEXT* regs);
> ```

Why is the argument called `regs` and not `context` like others? Is it intentional?
___
*[LibOS/shim/include/shim_lock.h, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKLYFR9EUqqnzc4KMl:-MRKLYFR9EUqqnzc4KMm:bvb1lw5) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/include/shim_lock.h#L63)):*
> ```objc
> 
>     shim_tcb_t* tcb = shim_get_tcb();
>     disable_preempt(tcb);
> ```

For my understanding: we don't need to block signals when we do `lock()` because signals are anyway are marked as "pending" if they arrive during LibOS/PAL execution? And we append such signals in a data race-free manner to lists of pending signals, and only examine them after the LibOS-syscall is done?

In other words, there is nothing that can "get in the way" of the current lock on the current thread, right? So there is no need for disabling preemption.
___
*[LibOS/shim/include/shim_signal.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKMOJ-0LbUYrvEykTP:-MRKMOJ-0LbUYrvEykTQ:byo362j) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_signal.h#L108)):*
> ```objc
> struct shim_signal {
>     siginfo_t siginfo;
> };
> ```

This is an unnecessary level of indirection now. We could remove `shim_signal` and just use `siginfo` now. But maybe this will be useful in the future when we add some fields... Not blocking on this.
___
*[LibOS/shim/include/shim_signal.h, line 114 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKMjgz8iVlHK9K7bpP:-MRKMjgz8iVlHK9K7bpQ:b-xu1x02) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_signal.h#L114)):*
> ```objc
> 
> uint64_t get_stack_for_sighandler(uint64_t sp, bool use_altstack);
> bool is_on_altstack(uint64_t sp, stack_t* alt_stack);
> ```

Can you add some brief comments on what the arguments are and what the return values are? For example, I don't understand why we have `sp` argument in `get_stack_for_sighandler()`? And why we have `alt_stack` in `is_on_altstack()` -- does it also return the alt stack, in addition to telling true/false?

The function names are confusing, maybe just change them... Or fix function signatures.
___
*[LibOS/shim/include/shim_tcb.h, line 27 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKO0TLEQ1zb8ZbURyd:-MRKO0TLEQ1zb8ZbURye:bmk7lr9) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_tcb.h#L27)):*
> ```objc
>     void*               libos_stack_bottom;
>     struct shim_context context;
>     void*               syscall_scratch_pc;
> ```

Could you add a brief comment what this is?
___
*[LibOS/shim/include/shim_thread.h, line 224 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3d2O9EGPYmb_jGyKZ:-MRKQmVd9-W8pwkcJqOr:b-pqlqua) ([raw file](https://github.com/oscarlab/graphene/blob/663fed807 [...]

2021-01-18 23:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 38 of 55 files reviewed, 61 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2Wx4y7LYM_bVjnOWt:-MRLaAk-63LvE1W3QEqM:b-neqqec) (no related file):*
> This looks like the case of an async signal from another process in the same Graphene instance? Or is it all signals? I'm trying to understand the scope of this issue.

What's the difference? We only handle syscalls from inside Graphene (instance), with the small exception of SIGINT (only on demand tho).
Anyway, it's all (async) signals.
> And IIUC, if another signal comes during the blocking host syscall, Linux will interrupt it anyway and Graphene will unfreeze and handle the first "pending" signal, right?

Yes, if it reached the host-syscall, it works. The problem is in the window between entering LibOS and issuing host syscall.
> In this case, the sysadmin tool (or the user) can simply repeat the signal after couple seconds, and Graphene will continue working.

I do not understand this. I'm not concerned about host injected signals, they are not essential anyway.
> Is there a particular scenario when this will lead to Graphene hanging completely? Like a parent waiting for a child's SIGCHLD, and being unfortunate to get SIGCHLD right-before issuing a host-level waitpid()?

No, I can't think of any valid scenario, but it doesn't mean there is none. And Graphene does not use host-level `waitpid`, waiting for children is emulated purely in LibOS. This also means that `waitpid` is immune to this issue - it calls Graphene thread sleeping function, which checks pending signals, so we are good here.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMaaHF5XZa-cYGyC3Y:-MRMaaHF5XZa-cYGyC3Z:bnrg73g) (no related file):*
Forgot it before: `PAL_CONTEXT` should be renamed to something else. This now is general Graphene context (CPU context actually) and is arch-specific, not Pal specific.
Any ideas for the name? I won't change it in this PR, for less conflicts.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMr83j6e-zOT69GEiq:-MRMr83k0l21onLb1iV6:b-24hne4) (no related file):*
TODO: fix gcc-patches

---
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 2 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKIg283dRbiTmQ5LD5:-MRLeXjx1j1XgWpOl_us:be5k8xh) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/glibc-patches/glibc-2.23.patch#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you regenerate these patches with `--full-index`? I forgot why we did this but I specifically changed it in this PR: https://github.com/oscarlab/graphene/pull/1641. You can ask Michal about the history of that (I guess we simply wanted to make it more explicit)?
</blockquote></details>

There are some comments in the orginal PR (linked to the one you've posted).
Done.
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 82 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKJu2E1cnBruwUChEP:-MRLfu0EAMtOJgO4hNUv:b-eakyrx) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/glibc-patches/syscalldb-api.patch#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are you using `jmp` instead of `call` to not mess with the user-level stack?
</blockquote></details>

Yes. This PR has this nice feature, that user app can even have no stack at all.
___
*[LibOS/shim/include/shim_defs.h, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3qQaIEmTyOLtU4yzB:-MRLieVe-KDs7Jg1ZNMx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/include/shim_defs.h#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please add `...and values are taken from...`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_defs.h, line 7 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKKaZXE4pnpgHWrTBn:-MRLg9700O1E4POWAWCD:bdygjwd) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_defs.h#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we should add an assert that these are greater than `LIBOS_SYSCALL_BOUND` (or `__NR_syscalls` which is the same)
</blockquote></details>

Why would we add such an assert? These are error values, used internally in Graphene, generally not visible to the app (tho they might appear in the debug logs) and they have nothing to do with syscall numbers.
___
*[LibOS/shim/include/shim_internal.h, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKL5n66csv_fjNI9W0:-MRLgWn01VYMVitH-u3O:bjtuw8w) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_internal.h#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is the argument called `regs` and not `context` like others? Is it intentional?
</blockquote></details>

No, not intentional. Otoh I've used context above in below, to name 2 different structs... Need some good naming convention here. BTW `PAL_CONTEXT` should be rename, because it's more like Graphene context now - it's arch specific, not Pal specific.
I should also add comments to all of these functions.
___
*[LibOS/shim/include/shim_lock.h, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKLYFR9EUqqnzc4KMl:-MRLh2pSCvU25fIJYhSU:b9l165u) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/include/shim_lock.h#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For my understanding: we don't need to block signals when we do `lock()` because signals are anyway are marked as "pending" if they arrive during LibOS/PAL execution? And we append such signals in a data race-free manner to lists of pending signals, and only examine them after the LibOS-syscall is done?

In other words, there is nothing that can "get in the way" of the current lock on the current thread, right? So there is no need for disabling preemption.
</blockquote></details>

Exactly. But keep in mind LibOS-syscall will not sleep in such case (`thread_sleep` handles the case of having pending signals), but the host-level syscall still can block (as discussed in top-level comment). Also we sometimes examine them inside LibOS (e.g. to check if there are any pending).
___
*[LibOS/shim/include/shim_signal.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKMOJ-0LbUYrvEykTP:-MRLhvP58-nyRXCDZ3gp:b-q515ph) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_signal.h#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is an unnecessary level of indirection now. We could remove `shim_signal` and just use `siginfo` now. But maybe this will be useful in the future when we add some fields... Not blocking on this.
</blockquote></details>

Yes there is, but is there any harm in it? I've just liked the idea of hiding the details from as much code as possible (only exposing `struct shim_signal`).
___
*[LibOS/shim/include/shim_signal.h, line 114 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKMjgz8iVlHK9K7bpP:-MRLmK6F9PKdp-KaOs85:bushg6n) ([raw file](h [...]

2021-01-19 01:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 38 of 55 files reviewed, 62 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRNC8411OKgDXhlaiAQ:-MRNC842D_uCamiUVkoF:bso5vle) (no related file):*
TODO: at rebase, squash the first commit (`[LibOS] Move `DkThreadResume` into `thread_wakeup``) into the second one (`[LibOS] Rework signal handling and syscall emulation`). The first one was reverted as one of the fixup to the second one (unfortunately some code was changed around, so couldn't make reversing changes as a fixup to the first one).

---
___
*[LibOS/shim/include/shim_thread.h, line 224 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3d2O9EGPYmb_jGyKZ:-MRNBxomBsDYf4MZRJxS:b-cf9dfa) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/include/shim_thread.h#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Doesn't seem to be needed...
</blockquote></details>

Done - removed it (restored to the original). Also see the top level comment.


<!-- Sent from Reviewable.io -->

2021-01-19 11:13 UTC, dimakuv requested changes
> Reviewed 11 of 16 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 52 of 55 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2Wx4y7LYM_bVjnOWt:-MRP9t5_29wb6lGb-NF4:b-cqkx9w) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> This looks like the case of an async signal from another process in the same Graphene instance? Or is it all signals? I'm trying to understand the scope of this issue.

What's the difference? We only handle syscalls from inside Graphene (instance), with the small exception of SIGINT (only on demand tho).
Anyway, it's all (async) signals.
> And IIUC, if another signal comes during the blocking host syscall, Linux will interrupt it anyway and Graphene will unfreeze and handle the first "pending" signal, right?

Yes, if it reached the host-syscall, it works. The problem is in the window between entering LibOS and issuing host syscall.
> In this case, the sysadmin tool (or the user) can simply repeat the signal after couple seconds, and Graphene will continue working.

I do not understand this. I'm not concerned about host injected signals, they are not essential anyway.
> Is there a particular scenario when this will lead to Graphene hanging completely? Like a parent waiting for a child's SIGCHLD, and being unfortunate to get SIGCHLD right-before issuing a host-level waitpid()?

No, I can't think of any valid scenario, but it doesn't mean there is none. And Graphene does not use host-level `waitpid`, waiting for children is emulated purely in LibOS. This also means that `waitpid` is immune to this issue - it calls Graphene thread sleeping function, which checks pending signals, so we are good here.
</blockquote></details>

OK, understood all points (also during offline discussion).

Looks like it's fine (at least for now) to ignore this case. I would assume real-world applications have timeouts/timers/alarms to detect blocking-for-too-long syscalls.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMaaHF5XZa-cYGyC3Y:-MRPAqZU0Mzk6waNLTgB:b-wow2gr) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Forgot it before: `PAL_CONTEXT` should be renamed to something else. This now is general Graphene context (CPU context actually) and is arch-specific, not Pal specific.
Any ideas for the name? I won't change it in this PR, for less conflicts.
</blockquote></details>

`COMMON_CPU_CONTEXT`? Or simply `CPU_CONTEXT`.

---
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 2 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPBfuUDW0vK71jkgua:-MRPBfuUDW0vK71jkgub:b-sk823o) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/glibc-patches/glibc-2.23.patch#L2)):*
> ```Diff
> diff --git a/Makeconfig b/Makeconfig
> index 87a22e88bed375d073663063dd4a93444d72ba25..3e2cf93fad804b81e67a476398a9c86c93ffa3cd 100644
> ```

Why did this hash change? Strange, but not blocking.
___
*[LibOS/glibc-patches/glibc-2.27.patch, line 2 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPBm353rNBEHIP4Vr8:-MRPBm353rNBEHIP4Vr9:b-rstmyu) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/glibc-patches/glibc-2.27.patch#L2)):*
> ```Diff
> diff --git a/Makeconfig b/Makeconfig
> index 86a71e580213f6e5de6e619d9f3370f4365b4ae2..515f8be0d13a14fe0588c357cfc5608503aca341 100644
> ```

ditto (not blocking)
___
*[LibOS/glibc-patches/glibc-2.31.patch, line 2 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPCHhh-exe9gtDO3Vf:-MRPCHhh-exe9gtDO3Vg:b-rstmyu) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/glibc-patches/glibc-2.31.patch#L2)):*
> ```Diff
> diff --git a/Makeconfig b/Makeconfig
> index f252842979a1d777e0f0c2bdafa7a65aee0805cd..0a044a7b60ae305af56c47982e3bdf1e25769527 100644
> ```

ditto (not blocking)
___
*[LibOS/glibc-patches/syscalldb-api.patch, line 82 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKJu2E1cnBruwUChEP:-MRPCPr-9ntAqRwngea2:b7l01ha) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/glibc-patches/syscalldb-api.patch#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes. This PR has this nice feature, that user app can even have no stack at all.
</blockquote></details>

Ok. Awesome.
___
*[LibOS/shim/include/shim_defs.h, line 7 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKKaZXE4pnpgHWrTBn:-MRPCYdA3CtZ1Z1gVrgN:b-velq91) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_defs.h#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why would we add such an assert? These are error values, used internally in Graphene, generally not visible to the app (tho they might appear in the debug logs) and they have nothing to do with syscall numbers.
</blockquote></details>

Ok. I confused these UNIX error codes with syscall numbers.
___
*[LibOS/shim/include/shim_internal.h, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKL5n66csv_fjNI9W0:-MRPCqUeCJITh9C4_CcW:b1475zx) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_internal.h#L76)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, not intentional. Otoh I've used context above in below, to name 2 different structs... Need some good naming convention here. BTW `PAL_CONTEXT` should be rename, because it's more like Graphene context now - it's arch specific, not Pal specific.
I should also add comments to all of these functions.
</blockquote></details>

I see a stranded `/**/`, I guess still working on this.
___
*[LibOS/shim/include/shim_signal.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKMOJ-0LbUYrvEykTP:-MRPD7sD4wyOFPiz-qYq:b-qezkjt) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_signal.h#L108)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes there is, but is there any harm in it? I've just liked the idea of hiding the details from as much code as possible (only exposing `struct shim_signal`).
</blockquote></details>

Ok, fair enough.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 28 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKSUPJ3Pf9hJ3o4qgw:-MRPEIvnDtHrXtnML04G:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/shim_context-x86_64.c#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why would it be? It did not set `XSTATE_MAGIC` and such, so it was always treated as non-extended context (with `fxsrstor`).
</blockquote></details>

OK
___
*[LibOS/shim/src/shim_context-x86_64.c, line 151 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKTz-11iPlTdSwK19S:-MRPEaOy7OfciQFyqWj5:bc7gld0) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/src/shim_context-x86_64.c#L151)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'm completely confused. Why would I want to do it?
</blockquote>< [...]

2021-01-19 17:58 UTC, dimakuv requested changes
> Reviewed 3 of 55 files at r1, 2 of 4 files at r2, 1 of 8 files at r4, 1 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 54 of 55 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @stefanberger, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKL5n66csv_fjNI9W0:-MRPl7Ln1dDPAHRBld-K:bvskl8w) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_internal.h#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see a stranded `/**/`, I guess still working on this.
</blockquote></details>

I suggest simply: `shim_context context` and `PAL_CONTEXT* regs` (or `PAL_CONTEXT* cpu_state`)
___
*[LibOS/shim/include/shim_thread.h, line 90 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQG6Pm6Hl6Fx-Gs6LR:-MRQG6Pm6Hl6Fx-Gs6LS:bq7rvls) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/include/shim_thread.h#L90)):*
> ```objc
>     struct shim_signal_queue signal_queue;
>     /* For the field below, see the explanation in "LibOS/shim/src/bookkeep/shim_signal.c" near
>      * `process_pending_signals_cnt`. */
> ```

This variable now has a prefix `g_`
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 130 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQCEUoEItMh0eoqD1F:-MRQCEUoEItMh0eoqD1G:b-p03nju) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L130)):*
> ```C
> 
> static bool is_rt_sq_empty(struct shim_rt_signal_queue* queue) {
>     return queue->get_idx == queue->put_idx;
> ```

For my own understanding: we don't need atomics here because all callers already take the appropriate (current thread's) lock?
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 149 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQ8xATDqCLWctHnwPn:-MRQ8xAU4NxxVQg-HnKR:b6m25no) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L149)):*
> ```C
> }
> 
> void get_pending_signals(__sigset_t* set) {
> ```

This function returns **all** pending signals, disregarding the current thread's signal mask. The next function applies the current thread's signal mask. Could we change their names so this is reflected? E.g.:
- `get_pending_signals` -> `get_all_pending_signals`
- `have_pending_signals` -> `have_unblocked_pending_signals`

In other words, I'd like to add a dimension of `all | blocked | unblocked` signals to the naming scheme.

Well, `have_unblocked_pending_signals` sounds unwieldy. Maybe we should assume "unblocked" by default in the naming scheme, but add `all | blocked` in all other names.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 280 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQfcIXCRWR_BcZPLUj:-MRQfcIY2RFTLb4zIISR:bki4w6c) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L280)):*
> ```C
> }
> 
> static void force_signal(siginfo_t* info) {
> ```

Why do we have a special `thread::forced_signal` field? Why couldn't we add this signal via `queue_append_signal()`?

Is it because we don't have any priorities of signals? So we need to check `forced_signal` first, and then go to the queue of pending signals.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 322 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQjGhg4pM3G0xjTbyw:-MRQjGhg4pM3G0xjTbyx:b-6a1uxi) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L322)):*
> ```C
>     assert(context);
> 
>     if (is_internal_tid(get_cur_tid()) || context_is_libos(context)) {
> ```

Not that important, but isn't the first clause excessive? How can an internal thread be running something other than the LibOS code?
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 332 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQjnzX2hcSsJQqtjq_:-MRQjnzX2hcSsJQqtjqa:b-942w06) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L332)):*
> ```C
>         };
>         force_signal(&info);
>         handle_signal(context, NULL);
> ```

Can you add `/*old_mask_ptr=*/NULL`? Here and everywhere.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 351 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQk2eW5vV3a6Bxf6Rb:-MRQk2eW5vV3a6Bxf6Rc:b-dvboh2) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L351)):*
> ```C
>     }
> 
>     if (is_internal_tid(get_cur_tid()) || context_is_libos(context)) {
> ```

ditto (first clause excessive)
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 558 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQmNNB9ppt5vLi-h5M:-MRQmNNB9ppt5vLi-h5N:b-dvboh2) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L558)):*
> ```C
> 
>     struct shim_vma_info vma_info = {.file = NULL};
>     if (is_internal(get_cur_thread()) || context_is_libos(context)
> ```

ditto (first clause excessive)
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 582 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQn7JP3jLoImCPB1Q8:-MRQn7JP3jLoImCPB1Q9:b-1djbrd) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L582)):*
> ```C
> }
> 
> static void quit_upcall(PAL_NUM arg, PAL_CONTEXT* context) {
> ```

TODO for myself: continue from here
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 231 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQBA3t8F_WeFwDgucf:-MRQBA3t8F_WeFwDgucg:b-wq7k4p) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/sys/shim_sigaction.c#L231)):*
> ```C
>         return -EFAULT;
> 
>     get_pending_signals(set);
> ```

Is this correct? `get_pending_signals()` returns all pending signals, whether blocked or unblocked. This is fine.

But manpages also say: `If a signal is both blocked and has a disposition of "ignored", it is not added to the mask of pending signals`. I see that `get_pending_signals()` returns blocked signals, but what about the second part of this clause ("disposition of ignored")?
___
*[LibOS/shim/src/vdso/arch/x86_64/vdso_syscall.h, line 8 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhAlj5ISS_ac8TcvZ:-MRPhAlj5ISS_ac8Tcv_:bsq81sg) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/vdso/arch/x86_64/vdso_syscall.h#L8)):*
> ```objc
> #define _VDSO_SYSCALL_H
> 
> static inline long arch_syscall(long (*syscalldb)(void), long nr, long arg1, long arg2) {
> ```

Can we change this name to something like `vdso_arch_syscall()`? This function is not generic, it only allows two arguments.
___
*[LibOS/shim/test/regression/test_libos.py, line 613 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhcVc246ncge6N5wB:-MRPhcVc246ncge6N5wC:b-7gyi5o) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/test/regression/test_libos.py#L613)):*
> ```Python
>         return match.group(1).strip()
> 
>     # TODO: DISABLED TEMPORARILY
> ```

Putting a blocking comment on this.


<!-- Sent from Reviewable.io -->

2021-01-19 20:02 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 54 of 55 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 610 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3hInVCTHhmBnBB71l:-MRR3Wx542jZbUR7A-ps:bmvx8p) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L610)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is true, but that should be fine in general case, I suppose? On normal Linux (async) signals are delivered only on transition from kernel to user space, so they can too be delayed for arbitrary time interval. The only difference is that on Linux in normal case scheduler will preempt a process and cause a signal delivery from time to time, but I think that can be delayed arbitrarily in some cases, couldn't it?
</blockquote></details>

Agreed with Borys. It's not perfect (the signal may be delivered much later), but at least for now it should be enough.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 668 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRR5g3230iiCe35RTfJ:-MRR5g3230iiCe35RTfK:b-y8q5ge) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L668)):*
> ```C
> }
> 
> /* XXX: This function assumes that stack is growning down.  */
> ```

typo: `growing`
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 678 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRR5hyE09Dj1_mKK4QR:-MRR5hyE09Dj1_mKK4QS:b-y8q5ge) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L678)):*
> ```C
> }
> 
> /* XXX: This function assumes that stack is growning down.  */
> ```

typo: `growing`
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 707 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRREO243ZbukMpvonsh:-MRREO243ZbukMpvonsi:bsdgxg7) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L707)):*
> ```C
>     }
> 
>     struct shim_signal signal = { 0 };
> ```

TODO for myself: continue from here.


<!-- Sent from Reviewable.io -->

2021-01-19 20:28 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 54 of 55 files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2Wx4y7LYM_bVjnOWt:-MRQLvir5hKHtfg2fV30:bm54sdm) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, understood all points (also during offline discussion).

Looks like it's fine (at least for now) to ignore this case. I would assume real-world applications have timeouts/timers/alarms to detect blocking-for-too-long syscalls.
</blockquote></details>

They rather use epoll, with a timeout

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMaaHF5XZa-cYGyC3Y:-MRQM4go6Ug6jhb8vXHO:buf3dbe) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`COMMON_CPU_CONTEXT`? Or simply `CPU_CONTEXT`.
</blockquote></details>

`CPU_CONTEXT` or maybe `struct cpu_context` sounds good.

---
___
*[LibOS/glibc-patches/glibc-2.23.patch, line 2 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPBfuUDW0vK71jkgua:-MRQN-qa82ttL0Mm-8zk:b-saczdo) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/glibc-patches/glibc-2.23.patch#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did this hash change? Strange, but not blocking.
</blockquote></details>

TBH, no idea. I've just double checked - I'm getting the new hash.
I generated this patches by applying the old one, changing needed things and generating them.
___
*[LibOS/glibc-patches/glibc-2.27.patch, line 2 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPBm353rNBEHIP4Vr8:-MRQN6dS8UevqFZ-bT6H:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/glibc-patches/glibc-2.27.patch#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (not blocking)
</blockquote></details>

ditto
___
*[LibOS/glibc-patches/glibc-2.31.patch, line 2 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPCHhh-exe9gtDO3Vf:-MRQNaeu-0njLmuwPj3s:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/glibc-patches/glibc-2.31.patch#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (not blocking)
</blockquote></details>

ditto
___
*[LibOS/shim/include/shim_internal.h, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKL5n66csv_fjNI9W0:-MRQNkUH7AoJeFIhWDxG:b4hgz3m) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/include/shim_internal.h#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see a stranded `/**/`, I guess still working on this.
</blockquote></details>

Ah, yes, I've added this just so that if I forget, there is still some change that somebody see and remind me, I guess it worked :)
Done.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 151 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKTz-11iPlTdSwK19S:-MRQOHRMDt29h9oZUerd:b5wqh2e) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/LibOS/shim/src/shim_context-x86_64.c#L151)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is what compilers add to function prologues and epilogues (to use these 128B as a scratch space for random data inside the function). But you don't need it here. This was me thinking out loud and forgetting to remove the comment afterwards.
</blockquote></details>

Ah, 128 sounded like some red zone, I guess just number coincidence.
___
*[LibOS/shim/src/syscallas-x86_64.S, line 34 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPIOZ95-YC6xPYu0eT:-MRQP7hA6Mu0y0o7bn2K:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/syscallas-x86_64.S#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `registers`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 120 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKo394AkPEQQ6rF4vT:-MRQPM6W4EECMHI9X7Hr:b-23ci0u) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/sys/shim_sigaction.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. Sure. We can postpone it to other PRs.
</blockquote></details>

I'll leave a blocking comment to remind me to add a TODO or GH issue before merging it.
___
*[Pal/src/host/Linux/db_exception.c, line 104 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKrlLe7hO4gA-WnFQc:-MRQ_glB6Lo02GVzgpZS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/Pal/src/host/Linux/db_exception.c#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's interesting. I guess you should add a comment in the LibOS `upcall` definition, and then brief comments in places in PAL where you actually set it.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_exception.c, line 122 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKtQFp-9YcvbVq53qc:-MRQ_yFq1ONvhlicQPOq:b-slpeu2) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/Pal/src/host/Linux/db_exception.c#L122)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to add a comment that `arg` (or `second argument`) is an exception address for sync signals.

Please do it everywhere, I will resolve all other comments for now.
</blockquote></details>

I've added the comment to the function definition. Should I also add some at the call sites? 
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 178 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKugbO8G4pcfKJreQM:-MRQPr9M9GFxudi4iWf4:bjl76ld) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/Pal/src/host/Linux-SGX/sgx_exception.c#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. Sorry, didn't notice that you changed that function completely. The PR is way too big, can't keep it in my head :)
</blockquote></details>

Yea, sorry about that, but I don't see a way to split it without doubling like half of the work.


<!-- Sent from Reviewable.io -->

2021-01-19 21:26 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 53 of 55 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @stefanberger, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 139 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRVMYI3hFZX9_4SBFE:-MRRVMYI3hFZX9_4SBFF:btl81pn) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L139)):*
> ```objc
>  *
>  * \param context original CPU context
>  * \param new_mask (OUT) new signal mask
> ```

The typical way is `\param[out] new_mask new signal mask`
___
*[LibOS/shim/include/shim_internal.h, line 141 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRVTWU5Op6GLituohQ:-MRRVTWVB1s0v4GymD-R:bpapic7) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L141)):*
> ```objc
>  * \param new_mask (OUT) new signal mask
>  *
>  * Restores cpu context in a architecure specific way. On entry to this funciton \p context holds
> ```

typo: `function`
___
*[LibOS/shim/include/shim_internal.h, line 143 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRVkdGEbe2MN4tDoti:-MRRVkdGEbe2MN4tDotj:bfs4y0i) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L143)):*
> ```objc
>  * Restores cpu context in a architecure specific way. On entry to this funciton \p context holds
>  * initial CPU context and this function extracts signal frame (generated by `prepare_sigframe`)
>  * and restores it into \p context. The new signal mask (to be set) is written into \p new_mask.
> ```

What is this `new signal mask`? Isn't it just the `previously saved old_mask from the signal frame generated by prepare_sigframe`? If yes, then could you reword along these lines? It would be easier to understand.
___
*[LibOS/shim/include/shim_internal.h, line 153 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRWANWBkQkkmVXwSDu:-MRRWANWBkQkkmVXwSDv:bf215sa) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L153)):*
> ```objc
>  * If the current instruction pointer in \p context points to a syscall instruction, arrange
>  * \p context so that it is emulated.
>  * Returns `true` if it was a syscall instruction (hence it was emulated).
> ```

`was emulated`? Technically `will be emulated` (looking at the code of `handle_signal`)

Ok, you have it explained in the next sentence. But why do you use past tense here then?
___
*[LibOS/shim/include/shim_internal.h, line 168 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRWZmy7GYYiwldG48T:-MRRWZmy7GYYiwldG48U:b-fh61js) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L168)):*
> ```objc
>  * If \p old_mask_ptr is not `NULL`, it is stored into the signal frame, otherwise the current
>  * signal mask is used.
>  * Returns `true` if a not-ignored signal was handled (hence \p context wasa changed), `false`
> ```

typo: `was`
___
*[Pal/src/host/Linux/db_exception.c, line 122 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKtQFp-9YcvbVq53qc:-MRRXG3y-CeSaUlqrt7N:b-4bfpar) ([raw file](https://github.com/oscarlab/graphene/blob/963e9ce0bb990da750c976c0137136563da2eca5/Pal/src/host/Linux/db_exception.c#L122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've added the comment to the function definition. Should I also add some at the call sites? 
</blockquote></details>

That should be enough, resolving.


<!-- Sent from Reviewable.io -->

2021-01-20 00:37 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 53 of 55 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @stefanberger, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 139 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRVMYI3hFZX9_4SBFE:-MRRoM_a2G5FjgWuh5_c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The typical way is `\param[out] new_mask new signal mask`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 141 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRVTWU5Op6GLituohQ:-MRRoSV3AwtQ7nDKuhef:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `function`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 143 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRVkdGEbe2MN4tDoti:-MRRow9s9ixPU31Gmr9x:bmg28hl) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L143)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `new signal mask`? Isn't it just the `previously saved old_mask from the signal frame generated by prepare_sigframe`? If yes, then could you reword along these lines? It would be easier to understand.
</blockquote></details>

How about this?
___
*[LibOS/shim/include/shim_internal.h, line 153 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRWANWBkQkkmVXwSDu:-MRRpU8kBn35BHw5E9pc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`was emulated`? Technically `will be emulated` (looking at the code of `handle_signal`)

Ok, you have it explained in the next sentence. But why do you use past tense here then?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 168 at r7](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRRWZmy7GYYiwldG48T:-MRRpgHy4sYGNIvuRiO4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/23e86fdf6b1a03111edfd1888ec31d6c98ea81ff/LibOS/shim/include/shim_internal.h#L168)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `was`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 90 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQG6Pm6Hl6Fx-Gs6LR:-MRRMVhZEMIxocDqoUUP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/include/shim_thread.h#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This variable now has a prefix `g_`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 130 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQCEUoEItMh0eoqD1F:-MRRMeFF4_FzbPzZZcmE:b-p4pp8r) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For my own understanding: we don't need atomics here because all callers already take the appropriate (current thread's) lock?
</blockquote></details>

Yes, except there is also a global queue (with a appropriate lock).
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 149 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQ8xATDqCLWctHnwPn:-MRS-0G9A-N8ie1kYv9q:b-5z2jkj) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L149)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This function returns **all** pending signals, disregarding the current thread's signal mask. The next function applies the current thread's signal mask. Could we change their names so this is reflected? E.g.:
- `get_pending_signals` -> `get_all_pending_signals`
- `have_pending_signals` -> `have_unblocked_pending_signals`

In other words, I'd like to add a dimension of `all | blocked | unblocked` signals to the naming scheme.

Well, `have_unblocked_pending_signals` sounds unwieldy. Maybe we should assume "unblocked" by default in the naming scheme, but add `all | blocked` in all other names.
</blockquote></details>

Done.
I went with `get_all_pending_signals` and `have_pending_signals`.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 280 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQfcIXCRWR_BcZPLUj:-MRRMwwA9oL3rlXSXtov:bx5nykk) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we have a special `thread::forced_signal` field? Why couldn't we add this signal via `queue_append_signal()`?

Is it because we don't have any priorities of signals? So we need to check `forced_signal` first, and then go to the queue of pending signals.
</blockquote></details>

Two reasons: 1) priorities (as you pointed), 2) there could be a user generated `SIGSEGV` (via `kill`) while a sync `SIGSEGV` happens and in such case we need to forcibly deliver the latter.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 322 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQjGhg4pM3G0xjTbyw:-MRRNEdb7rQUD5KieiNk:b-7i52q5) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L322)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not that important, but isn't the first clause excessive? How can an internal thread be running something other than the LibOS code?
</blockquote></details>

No idea, old code always checked this, so I've left it. I guess there could be some weird async helper that doesn't run LibOS? Probably not ...
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 332 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQjnzX2hcSsJQqtjq_:-MRRO97O5bgqlyJx31I8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L332)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add `/*old_mask_ptr=*/NULL`? Here and everywhere.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 668 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRR5g3230iiCe35RTfJ:-MRROSQR9oWhSrsg8Msh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L668)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `growing`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 678 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRR5hyE09Dj1_mKK4QR:-MRROStx7JBMgMwCrLhQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bo [...]

2021-01-20 09:53 UTC, dimakuv requested changes
> Reviewed 1 of 16 files at r5, 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU6d0hCUfWvILPZqbe:-MRU6d0hCUfWvILPZqbf:b-qmzoi5) (no related file):*
One interesting observation is that we **only switch to libos stack on syscalls**. But we do **not** switch to the libos stack on signals. I.e., the alt stack created by PAL and provided by the host OS is used for LibOS upcalls (but when LibOS jumps into the app's signal handler, we switch to the app-provided stack, so that's fine).

I wonder if this is benign? It's a bit weird that we don't switch from PAL stack to LibOS stack on signal handling. But maybe it's just a matter of renaming `libos_stack` to `graphene_stack` or `internal_stack`?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU9j5p0vHnE_tMP4Z8:-MRU9j5p0vHnE_tMP4Z9:b-1kzosd) (no related file):*
Please add `sys.enable_sigterm_injection` to the manifest-options docs file.

---
___
*[LibOS/shim/include/shim_internal.h, line 88 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU8CFOBaie9mSNszqt:-MRU8CFP1m6HpV2fhAzb:b-1pmu81) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_internal.h#L88)):*
> ```objc
>  * Emulates the syscall given the entry \p context.
>  */
> noreturn void shim_do_syscall(PAL_CONTEXT* context);
> ```

Maybe add a warning `Never call this function in the LibOS code, the only entry to it is from syscalldb()!`.

On the other hand, we must never call `shim_do_*` functions anyway. So feel free to ignore this comment.
___
*[LibOS/shim/include/shim_internal.h, line 172 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU8eLB2pDu9BHWg3Vp:-MRU8eLB2pDu9BHWg3Vq:b-vee968) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_internal.h#L172)):*
> ```objc
>  * otherwise.
>  */
> bool handle_signal(PAL_CONTEXT* context, __sigset_t* old_mask_ptr);
> ```

As mentioned in my other comments, there is a subtle flow around calling this function: it must be called after the syscall-return value is set but before the syscall number is invalidated. I would add a comment about this here.
___
*[LibOS/shim/include/shim_thread.h, line 93 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU92nb8qOmIwYHN8g-:-MRU92nb8qOmIwYHN8g0:b3api1z) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_thread.h#L93)):*
> ```objc
>     uint64_t pending_signals;
> 
>     struct shim_signal forced_signal;
> ```

Please add a comment about the need for this field.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 165 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU9CRpEzTc_y5sAth5:-MRU9CRpEzTc_y5sAth6:b-5zke8k) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/shim_context-x86_64.c#L165)):*
> ```C
>     "ret\n"
> );
> ```

Please remove one empty line
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 280 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQfcIXCRWR_BcZPLUj:-MRTsWRk8hUTJB-IUm7S:b-9p1zxl) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L280)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Two reasons: 1) priorities (as you pointed), 2) there could be a user generated `SIGSEGV` (via `kill`) while a sync `SIGSEGV` happens and in such case we need to forcibly deliver the latter.
</blockquote></details>

Could you add this description as a comment to `forced_signal` field in `shim_thread.h`?
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 322 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQjGhg4pM3G0xjTbyw:-MRTsf8b9AFO0xVF2pyg:b7c2plo) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L322)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No idea, old code always checked this, so I've left it. I guess there could be some weird async helper that doesn't run LibOS? Probably not ...
</blockquote></details>

OK. Resolving this, doesn't matter much.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 262 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTuqR06S8eRSVo-SNz:-MRTuqR06S8eRSVo-SO-:brwl71) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L262)):*
> ```C
> 
>     if (queue->get_idx < queue->put_idx) {
>         *signal = queue->queue[queue->get_idx % ARRAY_SIZE(queue->queue)];
> ```

For standard signals, you mark the queue slot as empty. Don't you want to do the same here? I think simply `queue->queue[queue->get_idx % ARRAY_SIZE(queue->queue)] = NULL;` is enough.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 694 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTte0Q5TkiSuMpL1ON:-MRTte0Q5TkiSuMpL1OO:ba7lqxg) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L694)):*
> ```C
> }
> 
> bool handle_signal(PAL_CONTEXT* context, __sigset_t* old_mask_ptr) {
> ```

Why does this function handle only one signal? Why not all pending signals? E.g., in a situation where my own thread got a SIGILL (say due to "syscall" instruction in SGX) and simultaneously another process sent my SIGCHLD, the current code will only run a SIGILL handler but won't run the SIGCHLD handler until after the start/restart of the next syscall.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 716 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTuQW-3cXbC20BrteI:-MRTuQW-3cXbC20BrteJ:b-mca210) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L716)):*
> ```C
>                 bool got = false;
>                 bool was_process = false;
>                 /* First try to handle thread targeted signals, then these proces wide targeted. */
> ```

`these proces` -> `this process` (two typos)
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 769 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTwsaT7v32w4gDntmc:-MRTwsaT7v32w4gDntmd:bogvwhs) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L769)):*
> ```C
> 
>     int sig = signal.siginfo.si_signo;
>     if (sig) {
> ```

Can we revert it to:
```
if (!sig)
    return false;

... continue with the signal (but now no need for indentation)...
```
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 770 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTxY_V1ipxU4cYW0qE:-MRTxY_V1ipxU4cYW0qF:b-vclq17) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L770)):*
> ```C
>     int sig = signal.siginfo.si_signo;
>     if (sig) {
>         lock(&current->signal_dispositions->lock);
> ```

I got confused with this lock on `signal_dispositions`. Why do we need this lock, why can't the logic be protected via `current->lock`? Is this because a single `signal_dispositions` object may be shared between different threads?

In other words, would it be possible to change the implementation such that we only need the `current->lock`? Signals are anyway  [...]

2021-01-20 10:10 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRUGSki-2bjkbparuzk:-MRUGSki-2bjkbparuzl:bnsrtvf) (no related file):*
Could you fix new-headers' macros like this: `_SGX_LOG_H -> SGX_LOG_H_`. Michal says the current macro names are reserved.

---


<!-- Sent from Reviewable.io -->

2021-01-20 19:49 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 36 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @stefanberger)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 610 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3hInVCTHhmBnBB71l:-MRWCac_Er6XNeb56Km8:bu8tts6) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L610)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Agreed with Borys. It's not perfect (the signal may be delivered much later), but at least for now it should be enough.
</blockquote></details>

Ok. Closing the gap will require careful change/review and this PR is already very big. hard to review.
Let's make it progress.
Can you please add some comment on it.
___
*[Pal/src/host/Linux/db_exception.c, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3kMsH3cti_2UB9Oxm:-MRWAHk2DYU1Z5dhmemf:batkff8) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/Pal/src/host/Linux/db_exception.c#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's completely ignored, as we discussed it on one of the weekly calls a while ago. The reasoning is: we do **not** want to inject host signals at all, but there is one situation that seems useful: gracefully exit an application (e.g. web server etc.). For this case, applications usually use `SIGTERM`, so we allow for a one-time host-injection of this signal (but only if allowed explicitly in manifest).
</blockquote></details>

Okay. Can you please add such description into commit message?
I didn't expect such change based on commit message. (or split off the behaviour change to another PR)
NOTE: I'm not opposing such behavior change itself.


<!-- Sent from Reviewable.io -->

2021-01-20 20:54 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 49 of 56 files reviewed, 36 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU9j5p0vHnE_tMP4Z8:-MRVdH1x0diGND2NHQlE:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `sys.enable_sigterm_injection` to the manifest-options docs file.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU6d0hCUfWvILPZqbe:-MRVdHX98dFJS9KdnZba:b2220sh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One interesting observation is that we **only switch to libos stack on syscalls**. But we do **not** switch to the libos stack on signals. I.e., the alt stack created by PAL and provided by the host OS is used for LibOS upcalls (but when LibOS jumps into the app's signal handler, we switch to the app-provided stack, so that's fine).

I wonder if this is benign? It's a bit weird that we don't switch from PAL stack to LibOS stack on signal handling. But maybe it's just a matter of renaming `libos_stack` to `graphene_stack` or `internal_stack`?
</blockquote></details>

That was a conscious choice. Why would we switch to LibOS stack on Pal-signal handling? The alternative stack is allocated by Pal so it's fine to use.
Why is that weird? Would you also like to switch to Pal stack on each Pal API call?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRUGSki-2bjkbparuzk:-MRVhdRq1bL0tdLWAXjo:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you fix new-headers' macros like this: `_SGX_LOG_H -> SGX_LOG_H_`. Michal says the current macro names are reserved.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRWTbSK-tZWfuC1QFUq:-MRWTbSLBuMWGHkldiHa:bv60qsv) (no related file):*
TODO: Add information about ignoring host signals to the commit message (at rebase).

---
___
*[LibOS/shim/include/shim_internal.h, line 88 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU8CFOBaie9mSNszqt:-MRVhr0Y14uJi7pOZbk9:b-r9pad) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_internal.h#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add a warning `Never call this function in the LibOS code, the only entry to it is from syscalldb()!`.

On the other hand, we must never call `shim_do_*` functions anyway. So feel free to ignore this comment.
</blockquote></details>

The only issue with calling `shim_do_*` directly is that they expect arguments to come from user.
Actually I'm considering renaming this function to `shim_emulate_syscall`.
What you think?
cc @mkow 
___
*[LibOS/shim/include/shim_internal.h, line 172 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU8eLB2pDu9BHWg3Vp:-MRWTksc0CJjiOCqaiQU:bhks9i3) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_internal.h#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As mentioned in my other comments, there is a subtle flow around calling this function: it must be called after the syscall-return value is set but before the syscall number is invalidated. I would add a comment about this here.
</blockquote></details>

Responded there.
___
*[LibOS/shim/include/shim_thread.h, line 93 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU92nb8qOmIwYHN8g-:-MRVk5Gg-pFPsqh6TvU2:bnlp9sw) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_thread.h#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment about the need for this field.
</blockquote></details>

Done.
I don't like this comment, so if you have a better idea/wording please let me know :)
___
*[LibOS/shim/src/shim_context-x86_64.c, line 165 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU9CRpEzTc_y5sAth5:-MRVjRdb9CkP4uILtPCK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/shim_context-x86_64.c#L165)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove one empty line
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 610 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3hInVCTHhmBnBB71l:-MRWVR8Y1MsMILM-TgyX:btnraya) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L610)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Ok. Closing the gap will require careful change/review and this PR is already very big. hard to review.
Let's make it progress.
Can you please add some comment on it.


</blockquote></details>

It is not solvable with the current approach: if we are in the middle of `handle_signal`, we might be past the point of being able to deliver a signal at this syscall return.
Sure I can write a comment about this, where would be an appropriate place?
The only solution I can think of is to add an async job that will trigger a interrupt after some time.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 280 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRQfcIXCRWR_BcZPLUj:-MRVjzAh4DvH9fz-QIDb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/src/bookkeep/shim_signal.c#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add this description as a comment to `forced_signal` field in `shim_thread.h`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 262 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTuqR06S8eRSVo-SNz:-MRVjajo-1zOIoVytScp:buljc3s) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L262)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For standard signals, you mark the queue slot as empty. Don't you want to do the same here? I think simply `queue->queue[queue->get_idx % ARRAY_SIZE(queue->queue)] = NULL;` is enough.
</blockquote></details>

What for? `get_idx` and `put_idx` define which slots are empty and which are not.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 694 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTte0Q5TkiSuMpL1ON:-MRVzF1L8Q5OMTd9iRoF:bo3h18s) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L694)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why does this function handle only one signal? Why not all pending signals? E.g., in a situation where my own thread got a SIGILL (say due to "syscall" instruction in SGX) and simultaneously another process sent my SIGCHLD, the current code will only run a SIGILL handler but won't run the SIGCHLD handler until after the start/restart of the next syscall.
</blockquote></details>

On x86 returning from a signal is done via a syscall (sigreturn), so it will be handled. They only difference is if the signal handl [...]

2021-01-21 09:39 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU6d0hCUfWvILPZqbe:-MRZAmVh5V7z5rgsBB4N:b-nx1bu5) (no related file):*
It's just a weird concept that we allocate a PAL stack (see e.g. https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux/db_threading.c#L129). But we don't really use the "THREAD_STACK_SIZE" part of it (for the normal context). (The same is true for Linux-SGX PAL.)

So we have:
- a PAL stack for each thread, allocated by PAL, but only the TCB and the altstack parts are used at runtime.
- a LibOS stack for each thread, allocated by LibOS, but *not* used for TCB and *not* used for altstack (only for normal stack).

It's a bizarre state of affairs. Well, I don't know if we need to change anything about this.

> Would you also like to switch to Pal stack on each Pal API call?

No. No need for this.

---
___
*[Documentation/manifest-syntax.rst, line 217 at r9](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRZC023BMrQbWfoIJz1:-MRZC023BMrQbWfoIJz2:b1wyira) ([raw file](https://github.com/oscarlab/graphene/blob/a6d93b3f98a31d373d81a6f232837457467fdfbd/Documentation/manifest-syntax.rst#L217)):*
> ```reStructuredText
> Be careful! In SGX environment, the untrusted host could inject that signal in
> an arbitrary moment. Examine what your application `SIGTERM` handler does and
> whether it poses any security-treat.
> ```

`security threat`. But I like your version!
___
*[LibOS/shim/include/shim_internal.h, line 88 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU8CFOBaie9mSNszqt:-MRZIk_U5rPhT4SVYqxx:b-ko08rq) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_internal.h#L88)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The only issue with calling `shim_do_*` directly is that they expect arguments to come from user.
Actually I'm considering renaming this function to `shim_emulate_syscall`.
What you think?
cc @mkow 
</blockquote></details>

I'm fine with both renaming and leaving as-is. You choice.
___
*[LibOS/shim/include/shim_thread.h, line 93 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU92nb8qOmIwYHN8g-:-MRZCAsVAwk1puc8aGeX:b-15nt8f) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_thread.h#L93)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
I don't like this comment, so if you have a better idea/wording please let me know :)
</blockquote></details>

LGTM. I'm fine with this comment.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 610 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3hInVCTHhmBnBB71l:-MRZCQJ49kZfAI8qJkKb:byppjr9) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L610)):*
> an async job that will trigger a interrupt

Actually, not a bad idea. Not for this PR of course, but generally could add this to the Async Helper Thread.

> Sure I can write a comment about this, where would be an appropriate place?

How about `shim_internal.h: handle_signal`, in the body of your function-description comment? Just a note that `signals are delivered only during transition from LibOS to app, so a situation is possible when a signal is queued but is not delivered until a system call is done (could pose an issue for indefinitely-long-blocking host syscalls)`.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 262 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTuqR06S8eRSVo-SNz:-MRZCG-OBpOyJECNMMXh:bs4ixp3) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L262)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What for? `get_idx` and `put_idx` define which slots are empty and which are not.
</blockquote></details>

OK, fair enough.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 694 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTte0Q5TkiSuMpL1ON:-MRZDe356j3opOslR1cF:bdpiabz) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L694)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On x86 returning from a signal is done via a syscall (sigreturn), so it will be handled. They only difference is if the signal handler does not issue any syscalls and the architecture (if we support it in the future) doesn't use a syscall to return from signal handler.
I guess I could rework it to generate sigframes for all available signals at once. Should I?
</blockquote></details>

LGTM. Sorry, forgot that we'll end up in `rt_sigreturn()` anyway after we handled the signal, and so the next pending signal (if any) will be created on the way out of that syscall.

Is `sigreturn()` arch-specific? I thought it is Linux-specific, in which case the used flow will always be true. Anyway, even if it is not, we don't want to deal with it right now :)
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 770 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTxY_V1ipxU4cYW0qE:-MRZEN0T79URWmHU7J4Q:b-hbzzja) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L770)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's always shared between threads (`CLONE_THREAD` requires `CLONE_SIGHAND` explicitly).
So the answer is: no, it's not possible.
</blockquote></details>

OK, got it.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 793 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTymbhDBQrRGeNJ6DC:-MRZFXhSDRc1ewqEoZmD:b-rp7jrc) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L793)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This not true: we also call `handle_signal()` in upcalls and most importantly in `interrupted_upcall` (which indicates there is some async notification we should handle). None of these call `pal_context_set_retval` or `SHIM_TCB_SET(context.syscall_nr, -1)`.
</blockquote></details>

Ok, true. In this case we don't even get inside this flow (because the upcalls only call `handle_signal()` if the signal arrived during app-code execution, and so `sysnr == -1`). Ignore my request.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 842 at r9](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRZGNicA3kI5-hrX5Sz:-MRZGNicA3kI5-hrX5T-:b-rqt78o) ([raw file](https://github.com/oscarlab/graphene/blob/a6d93b3f98a31d373d81a6f232837457467fdfbd/LibOS/shim/src/bookkeep/shim_signal.c#L842)):*
> ```C
>         /* We have seen an ignored signal, retry. */
>         return handle_signal(context, old_mask_ptr);
>     }
> ```

Did you add this because we could have several signals in the signal queue, and the first one this function looked at is ignored? So without this new retry logic, LibOS would simply return back to the app even though there was another not-ignored signal pending? And with this new retry logic, LibOS is guaranteed to deliver one not-ignored pending signal (if any)?
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 196 at r8](https://review [...]

2021-01-22 00:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2Wx4y7LYM_bVjnOWt:-MRbW6Zu67aCs1d9u6x7:b5rpezx) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

They rather use epoll, with a timeout
</blockquote></details>

Added a comment in `shim_internal.h`

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU6d0hCUfWvILPZqbe:-MR_xN0TA9PKuE2rMj-8:bj552w4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's just a weird concept that we allocate a PAL stack (see e.g. https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux/db_threading.c#L129). But we don't really use the "THREAD_STACK_SIZE" part of it (for the normal context). (The same is true for Linux-SGX PAL.)

So we have:
- a PAL stack for each thread, allocated by PAL, but only the TCB and the altstack parts are used at runtime.
- a LibOS stack for each thread, allocated by LibOS, but *not* used for TCB and *not* used for altstack (only for normal stack).

It's a bizarre state of affairs. Well, I don't know if we need to change anything about this.

> Would you also like to switch to Pal stack on each Pal API call?

No. No need for this.
</blockquote></details>

Let's keep the discussion about 2 stacks to one place (near comment about it).

---
___
*[Documentation/manifest-syntax.rst, line 217 at r9](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRZC023BMrQbWfoIJz1:-MR_lpDQA2VD0rTM-gpt:blclh4c) ([raw file](https://github.com/oscarlab/graphene/blob/a6d93b3f98a31d373d81a6f232837457467fdfbd/Documentation/manifest-syntax.rst#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`security threat`. But I like your version!
</blockquote></details>

Don't you know you need to find a cookie before you get rip control? ;)
Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 610 at r2](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR3hInVCTHhmBnBB71l:-MRbPmCRAidFS3JDytPc:behjo3k) ([raw file](https://github.com/oscarlab/graphene/blob/663fed80768c5d7b8e929b21d0ad7bd806bf5bf4/LibOS/shim/src/bookkeep/shim_signal.c#L610)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> an async job that will trigger a interrupt

Actually, not a bad idea. Not for this PR of course, but generally could add this to the Async Helper Thread.

> Sure I can write a comment about this, where would be an appropriate place?

How about `shim_internal.h: handle_signal`, in the body of your function-description comment? Just a note that `signals are delivered only during transition from LibOS to app, so a situation is possible when a signal is queued but is not delivered until a system call is done (could pose an issue for indefinitely-long-blocking host syscalls)`.
</blockquote></details>

Added a comment in `shim_thread.h`
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 694 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRTte0Q5TkiSuMpL1ON:-MR_mij0C1ZBq9HpQfZb:b-snu2a3) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_signal.c#L694)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

LGTM. Sorry, forgot that we'll end up in `rt_sigreturn()` anyway after we handled the signal, and so the next pending signal (if any) will be created on the way out of that syscall.

Is `sigreturn()` arch-specific? I thought it is Linux-specific, in which case the used flow will always be true. Anyway, even if it is not, we don't want to deal with it right now :)
</blockquote></details>

The user application (usually libc) sets the `sa_restorer` field in `struct sigaction`, so it might very well not use any syscalls. I guess restoring some data is possible without a syscall (e.g. all general purpose registers), but some (e.g. signal mask) is not. We should be fine then. Added a comment.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 842 at r9](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRZGNicA3kI5-hrX5Sz:-MR_wwGS30yK1B0f11r6:b-1vijnd) ([raw file](https://github.com/oscarlab/graphene/blob/a6d93b3f98a31d373d81a6f232837457467fdfbd/LibOS/shim/src/bookkeep/shim_signal.c#L842)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you add this because we could have several signals in the signal queue, and the first one this function looked at is ignored? So without this new retry logic, LibOS would simply return back to the app even though there was another not-ignored signal pending? And with this new retry logic, LibOS is guaranteed to deliver one not-ignored pending signal (if any)?
</blockquote></details>

Exactly.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 196 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU4bpQDPrGU29MFyb8:-MR_xITJ7FrSNEFqg-wE:b-cgbnrv) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_thread.c#L196)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I mentioned this in a top-level comment on LibOS/PAL stacks. I guess this is what you meant?

Yes, we have a PAL allocated stack for *every thread*. And yes, its normal-context region is basically unused.
</blockquote></details>

Yes, that's what this comment is about.
So we can freely use it as the only Graphene stack (well, except alternative stack for host-level signal handling) ?
If yes, should I stash such change to this PR or leave for a follow-up?
___
*[Pal/src/host/Linux/db_exception.c, line 104 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRUBWqRBHBQYnW1Fier:-MRa782N1izyuutP6yjf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/Pal/src/host/Linux/db_exception.c#L104)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about:
```
 * This function must be reentrant and thread-safe - this includes `upcall` too! (Technically,
 * only for cases if signal arrived while in Graphene code; if signal arrived while in user app,
 * this function doesn't need to be reentrant and thread-safe.)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 01:14 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (Jenkins could not connect to github)

2021-01-22 14:29 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 174 at r10](https://reviewable.io/reviews/oscarlab/graphene/2090#-MReTwFS05xhGvmi39oI:-MReTwFS05xhGvmi39oJ:bl0gkjf) ([raw file](https://github.com/oscarlab/graphene/blob/37335d56732c8521f9e908194c674155a047b853/LibOS/shim/include/shim_internal.h#L174)):*
> ```objc
>  * XXX: Signals are delivered only during transition from LibOS to the user app, so a situation is
>  * possible when a signal is queued, but is not delivered for an arbitrary amount of time. There are
>  * two distinc situations when this can happen:
> ```

`distinct`.

Other than this typo, the comment is good.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 697 at r10](https://reviewable.io/reviews/oscarlab/graphene/2090#-MReUSwfD1sYCZ_TmhW2:-MReUSwfD1sYCZ_TmhW3:bwhka7v) ([raw file](https://github.com/oscarlab/graphene/blob/37335d56732c8521f9e908194c674155a047b853/LibOS/shim/src/bookkeep/shim_signal.c#L697)):*
> ```C
>  * XXX(borysp): This function handles one pending, non-blocked, non-ignored signal at a time, while,
>  * I believe, normal Linux creates sigframes for all pending, non-blocked, non-ignored signals at
>  * once.
> ```

Since you added this comment, can you please also add a sentence that `Each signal handler (at least on Linux x86) issues rt_sigreturn() syscall to return back to the normal context; since this syscall is intercepted by LibOS, this function will be called again. This way, all pending, non-blocked, non-ignored signals will be handled one by one.`
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 196 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU4bpQDPrGU29MFyb8:-MReUFSB0tDF3yfnV2wE:b-xlggza) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_thread.c#L196)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, that's what this comment is about.
So we can freely use it as the only Graphene stack (well, except alternative stack for host-level signal handling) ?
If yes, should I stash such change to this PR or leave for a follow-up?
</blockquote></details>

Let's leave it for a follow-up. We need to merge this PR at some point :)


<!-- Sent from Reviewable.io -->

2021-01-22 15:02 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 174 at r10](https://reviewable.io/reviews/oscarlab/graphene/2090#-MReTwFS05xhGvmi39oI:-MReYDynBpR941ZayZ22:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/37335d56732c8521f9e908194c674155a047b853/LibOS/shim/include/shim_internal.h#L174)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`distinct`.

Other than this typo, the comment is good.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 697 at r10](https://reviewable.io/reviews/oscarlab/graphene/2090#-MReUSwfD1sYCZ_TmhW2:-MReayCD57SaSD6btaWz:brglhon) ([raw file](https://github.com/oscarlab/graphene/blob/37335d56732c8521f9e908194c674155a047b853/LibOS/shim/src/bookkeep/shim_signal.c#L697)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since you added this comment, can you please also add a sentence that `Each signal handler (at least on Linux x86) issues rt_sigreturn() syscall to return back to the normal context; since this syscall is intercepted by LibOS, this function will be called again. This way, all pending, non-blocked, non-ignored signals will be handled one by one.`
</blockquote></details>

Done (with some changes).
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 196 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU4bpQDPrGU29MFyb8:-MReb3vt2IDjA1wE4a-v:b58kr64) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_thread.c#L196)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's leave it for a follow-up. We need to merge this PR at some point :)
</blockquote></details>

TODO: write down all leftovers from this PR in an issue.


<!-- Sent from Reviewable.io -->

2021-01-24 19:50 UTC, boryspoplawski commented
Jenkins, retest Jenkins please (mbedtls download failed)

2021-01-24 19:51 UTC, boryspoplawski commented
Jenkins, retest Jenkins-18.04 please (internet connection issues)

2021-01-24 19:52 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (internet connection issues)

2021-01-25 01:59 UTC, boryspoplawski commented
Jenkins, retest Jenkins please (`sendfile08` from LTP failed, known issue)

2021-01-25 08:20 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 697 at r10](https://reviewable.io/reviews/oscarlab/graphene/2090#-MReUSwfD1sYCZ_TmhW2:-MRsbYNw4mrusqbpUD4V:b-mydrrz) ([raw file](https://github.com/oscarlab/graphene/blob/37335d56732c8521f9e908194c674155a047b853/LibOS/shim/src/bookkeep/shim_signal.c#L697)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done (with some changes).
</blockquote></details>

LGTM. Thanks for `swapcontext`, good catch.


<!-- Sent from Reviewable.io -->

2021-01-26 17:20 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/test/regression/test_libos.py, line 613 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhcVc246ncge6N5wB:-MRzgtAi03GmGaL_xpC1:b-spacxk) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/test/regression/test_libos.py#L613)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Got it, waiting for a fix...
</blockquote></details>

I think the important part is to preserve the stack when deep inside LibOS, i.e. inside `shim_do_syscall`, not necessarily at the moment of syscall entry or exit. This seems to work:

```diff
--- a/LibOS/shim/src/syscallas-x86_64.S
+++ b/LibOS/shim/src/syscallas-x86_64.S
@@ -116,14 +116,38 @@ syscalldb:
     mov %rsp, (%rcx)
 
     and $~0xF, %rsp  # Required by System V AMD64 ABI.
-    sub $8, %rsp
     xor %ebp, %ebp
 
-    jmp shim_do_syscall # this does not return
+    # CFA setup so that shim_do_syscall has the right traceback.  Pretend that this (syscalldb) is
+    # being called from function called __morestack (hardcoded name necessary to keep GDB happy when
+    # jumping stacks), with RBP/RSP set to values stored in PAL_CONTEXT, and return address to
+    # application in RCX.
+
+    mov %rdi, %r12
+    .cfi_def_cfa %r12, 0
+    .cfi_offset %rcx, 0x80
+    .cfi_offset %rsp, 0x78
+    .cfi_offset %rbp, 0x50
+
+    leaq Lfor_cfa_debug_info(%rip), %r13
+    .cfi_register %rip, %r13
+
+    call shim_do_syscall
 
     .cfi_endproc
     .size syscalldb, .-syscalldb
 
+.global __morestack
+.type __morestack, @function
+__morestack:
+    .cfi_startproc
+    .cfi_register %rip, %rcx
+    .cfi_same_value %rsp
+    .cfi_same_value %rbp
+    nop
+Lfor_cfa_debug_info:
+    .cfi_endproc
+
 .global return_from_syscall
 .type return_from_syscall, @function
```

It's a bit tricky because apparently `__morestack` should already have the new (application) stack. But I don't have a super good understanding of CFI so maybe that's too complicated.


<!-- Sent from Reviewable.io -->

2021-01-26 17:48 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/test/regression/test_libos.py, line 613 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhcVc246ncge6N5wB:-MRznEObAFRzt7uXA-VN:bdsa78y) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/test/regression/test_libos.py#L613)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think the important part is to preserve the stack when deep inside LibOS, i.e. inside `shim_do_syscall`, not necessarily at the moment of syscall entry or exit. This seems to work:

```diff
--- a/LibOS/shim/src/syscallas-x86_64.S
+++ b/LibOS/shim/src/syscallas-x86_64.S
@@ -116,14 +116,38 @@ syscalldb:
     mov %rsp, (%rcx)
 
     and $~0xF, %rsp  # Required by System V AMD64 ABI.
-    sub $8, %rsp
     xor %ebp, %ebp
 
-    jmp shim_do_syscall # this does not return
+    # CFA setup so that shim_do_syscall has the right traceback.  Pretend that this (syscalldb) is
+    # being called from function called __morestack (hardcoded name necessary to keep GDB happy when
+    # jumping stacks), with RBP/RSP set to values stored in PAL_CONTEXT, and return address to
+    # application in RCX.
+
+    mov %rdi, %r12
+    .cfi_def_cfa %r12, 0
+    .cfi_offset %rcx, 0x80
+    .cfi_offset %rsp, 0x78
+    .cfi_offset %rbp, 0x50
+
+    leaq Lfor_cfa_debug_info(%rip), %r13
+    .cfi_register %rip, %r13
+
+    call shim_do_syscall
 
     .cfi_endproc
     .size syscalldb, .-syscalldb
 
+.global __morestack
+.type __morestack, @function
+__morestack:
+    .cfi_startproc
+    .cfi_register %rip, %rcx
+    .cfi_same_value %rsp
+    .cfi_same_value %rbp
+    nop
+Lfor_cfa_debug_info:
+    .cfi_endproc
+
 .global return_from_syscall
 .type return_from_syscall, @function
```

It's a bit tricky because apparently `__morestack` should already have the new (application) stack. But I don't have a super good understanding of CFI so maybe that's too complicated.
</blockquote></details>

Thanks!
I've been trying to fix this, but all I did was always failing. I was even considering a dynamic in-memory patching of gdb (please don't ask for details) as a last resort fix ...
The trick here that I've missed is using `.cfi_same_value` inside `__morestack` - this way we can pretend that `__morestack` is called from user app stack.
I'll prepare a commit in a moment.


<!-- Sent from Reviewable.io -->

2021-01-26 20:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/test/regression/test_libos.py, line 613 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhcVc246ncge6N5wB:-MS-JOHb36q0vLmgsalp:b-wnzh9c) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/test/regression/test_libos.py#L613)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Thanks!
I've been trying to fix this, but all I did was always failing. I was even considering a dynamic in-memory patching of gdb (please don't ask for details) as a last resort fix ...
The trick here that I've missed is using `.cfi_same_value` inside `__morestack` - this way we can pretend that `__morestack` is called from user app stack.
I'll prepare a commit in a moment.
</blockquote></details>

Now that I think of it, I guess it also needs to have `.cfi_offset` for all the registers in saved context? Probably not important for unwinding, but might be useful for debugging.


<!-- Sent from Reviewable.io -->

2021-01-26 22:15 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 54 of 55 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/test/regression/test_libos.py, line 613 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhcVc246ncge6N5wB:-MS-kko16nfWAamDvKzI:b-ccyvqc) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/test/regression/test_libos.py#L613)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Now that I think of it, I guess it also needs to have `.cfi_offset` for all the registers in saved context? Probably not important for unwinding, but might be useful for debugging.
</blockquote></details>

All? Probably not, maybe only these caller-saved...
Otoh what's the point, why would that be useful in debugging?

@dimakuv Done.


<!-- Sent from Reviewable.io -->

2021-01-26 22:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 54 of 55 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRNC8411OKgDXhlaiAQ:-MS-pFOnD8vBaQgFch8T:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase, squash the first commit (`[LibOS] Move `DkThreadResume` into `thread_wakeup``) into the second one (`[LibOS] Rework signal handling and syscall emulation`). The first one was reverted as one of the fixup to the second one (unfortunately some code was changed around, so couldn't make reversing changes as a fixup to the first one).
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRWTbSK-tZWfuC1QFUq:-MS-pGbx8RpIIgULNxgN:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: Add information about ignoring host signals to the commit message (at rebase).
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-01-26 23:03 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 42 of 55 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/test/regression/test_libos.py, line 613 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhcVc246ncge6N5wB:-MS-tIF5Bh0XubeBlHRU:b-gxf5gc) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/test/regression/test_libos.py#L613)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All? Probably not, maybe only these caller-saved...
Otoh what's the point, why would that be useful in debugging?

@dimakuv Done.
</blockquote></details>

Since this is syscall, the application code will only expect RCX and R11 to be clobbered, right?

I was thinking so that if you print the stack trace in GDB, you see the right function arguments. And you can examine the upper frames, I guess, although that's less important since you can exit the syscall.

Also if the application does something weird with CFI and the other registers are needed for the stack trace? Sounds unlikely though.


<!-- Sent from Reviewable.io -->

2021-01-26 23:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 42 of 55 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/syscallas-x86_64.S, line 189 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS017RZ8_z1X4t8g5Wy:-MS017R_6g7XkRcoWkgN:bcyazxn) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/syscallas-x86_64.S#L189)):*
> ```
>     .cfi_same_value %rax
>     .cfi_same_value %rcx
>     .cfi_same_value %rsp
> ```

Do we need to be so explicit?
cc @pwmarcz
___
*[LibOS/shim/test/regression/test_libos.py, line 613 at r6](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRPhcVc246ncge6N5wB:-MS-xMBTEkoAol_6HXCh:b6ndg4e) ([raw file](https://github.com/oscarlab/graphene/blob/26e9f4343e70f94f038b827c21ec3864c92f45e5/LibOS/shim/test/regression/test_libos.py#L613)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Since this is syscall, the application code will only expect RCX and R11 to be clobbered, right?

I was thinking so that if you print the stack trace in GDB, you see the right function arguments. And you can examine the upper frames, I guess, although that's less important since you can exit the syscall.

Also if the application does something weird with CFI and the other registers are needed for the stack trace? Sounds unlikely though.
</blockquote></details>

True and it's trivial to fix, so I'll just add it.
Done.


<!-- Sent from Reviewable.io -->

2021-01-27 00:03 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-apps please (redis-server enclave initialization failed - unrelated)

2021-01-27 00:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 42 of 55 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/syscallas-x86_64.S, line 189 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS017RZ8_z1X4t8g5Wy:-MS076Tx2hhAjWKYuub9:brtsbrx) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/syscallas-x86_64.S#L189)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need to be so explicit?
cc @pwmarcz
</blockquote></details>

GDB doesn't seem to mind - I compiled a toy program and apparently you don't need `.cfi_same_value` for registers to still be able to see them (or walk the stack using the register as return address).

So probably specifying just RIP and RSP is enough? Since only these two do change by default when you're unwinding.


<!-- Sent from Reviewable.io -->

2021-01-27 09:36 UTC, dimakuv approved these changes
> Reviewed 14 of 14 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 13 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMr83j6e-zOT69GEiq:-MS2BmGqBdAy1riYrrM_:bmdfvcs) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: fix gcc-patches
</blockquote></details>

Looks like this is the last blocker (apart from creating an issue enumerating all TODO leftovers)?

---
___
*[LibOS/shim/src/syscallas-x86_64.S, line 219 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS2BCTk1kjot6Ifbu5o:-MS2BCTk1kjot6Ifbu5p:bypdvzm) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/syscallas-x86_64.S#L219)):*
> ```
>     # and just restores the user context, so it will not be visible in any backtrace.
>     # Note that fixing it is not trivial - we need a trick with `__morestack`, but we don't have
>     # neither a stack, nor a scratch register.
> ```

Yep, no-one cares about debugging metadata on these two instructions.


<!-- Sent from Reviewable.io -->

2021-01-27 12:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 13 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/syscallas-x86_64.S, line 189 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS017RZ8_z1X4t8g5Wy:-MS2azZ413Ym1Wp0tkDT:b-3ljt18) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/syscallas-x86_64.S#L189)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

GDB doesn't seem to mind - I compiled a toy program and apparently you don't need `.cfi_same_value` for registers to still be able to see them (or walk the stack using the register as return address).

So probably specifying just RIP and RSP is enough? Since only these two do change by default when you're unwinding.
</blockquote></details>

By the way, the CFI table for these looks fun:

![image.png](https://files.reviewableusercontent.io/images/reviewable/468495/eOpAz9sJ667E_1GGt2NiWXq8/image.png)

(this is `objdump -wF`; `u` seems to mean undefined) 

I did some more reading of elfutils source, and at least callee-saved registers (RBP etc.) have an explicit default of `.cfi_same_value`. The rest, it's unclear to me - I would expect them to be "undefined" (i.e. unrecoverable) by default but I can't find confirmation for that. Anyway, it's probably simplest to leave this as-is.


<!-- Sent from Reviewable.io -->

2021-01-27 14:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 12 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMr83j6e-zOT69GEiq:-MS3GoiQBzCNtJvuW4R8:bcbivos) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like this is the last blocker (apart from creating an issue enumerating all TODO leftovers)?
</blockquote></details>

Yeah, but I was not rushing fixing all TODOs, since I also wait for @mkow review :)

---
___
*[LibOS/shim/src/syscallas-x86_64.S, line 189 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS017RZ8_z1X4t8g5Wy:-MS3HFs860xjPvOZakip:b-5kt260) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/syscallas-x86_64.S#L189)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

By the way, the CFI table for these looks fun:

![image.png](https://files.reviewableusercontent.io/images/reviewable/468495/eOpAz9sJ667E_1GGt2NiWXq8/image.png)

(this is `objdump -wF`; `u` seems to mean undefined) 

I did some more reading of elfutils source, and at least callee-saved registers (RBP etc.) have an explicit default of `.cfi_same_value`. The rest, it's unclear to me - I would expect them to be "undefined" (i.e. unrecoverable) by default but I can't find confirmation for that. Anyway, it's probably simplest to leave this as-is.
</blockquote></details>

We could collapse the table for `shim_do_syscall` to probably ~3 rows, but big table just for one function won't hurt and this allows for single stepping and having a proper backtrace everywhere :)
___
*[LibOS/shim/src/syscallas-x86_64.S, line 219 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS2BCTk1kjot6Ifbu5o:-MS3HhzA-rXVjYy5PkDN:bjjn59n) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/syscallas-x86_64.S#L219)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yep, no-one cares about debugging metadata on these two instructions.
</blockquote></details>

Well, if a segfault or something happens at some of these instructions (note there are far more than 2) I would be nice to have a backtrace. Otoh if such fault happens, one backtrace probably won't help much...


<!-- Sent from Reviewable.io -->

2021-02-02 01:07 UTC, mkow requested changes
> Reviewed 15 of 55 files at r1, 2 of 8 files at r4, 7 of 16 files at r5, 2 of 9 files at r8, 1 of 7 files at r9, 8 of 14 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 52 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPJYcx8pyhfxP2ZQvr:-MSPJYcyBwU585ECaJjv:b6osg7u) (no related file):*
Nitpick: `Pal` -> `PAL` in the commit message.

---
___
*[Documentation/manifest-syntax.rst, line 226 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSV4M1k3U7R_gERzptE:-MSV4M1k3U7R_gERzptF:baeg2de) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/Documentation/manifest-syntax.rst#L226)):*
> ```reStructuredText
> ::
> 
>     sys.enable_sigterm_injection = [1|0]
> ```

Could you set it to 1 in one of the LibOS regression tests, e.g. `openmp`? It already sets another option just so that we have a test exercising it.
___
*[Documentation/manifest-syntax.rst, line 229 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPJtgb1oDEpGWcq588:-MSPJtgb1oDEpGWcq589:bb4qji1) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/Documentation/manifest-syntax.rst#L229)):*
> ```reStructuredText
>     (Default: 0)
> 
> This specifies whether to allow for a one time injection of `SIGTERM` signal
> ```

`one time` -> `one-time`
___
*[Documentation/manifest-syntax.rst, line 232 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPK3781vOUP1cwP2QW:-MSPK3781vOUP1cwP2QX:b2n59my) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/Documentation/manifest-syntax.rst#L232)):*
> ```reStructuredText
> into Graphene. Could be useful to handle graceful shutdown.
> Be careful! In SGX environment, the untrusted host could inject that signal in
> an arbitrary moment. Examine what your application `SIGTERM` handler does and
> ```

`application` -> `application's`
___
*[LibOS/shim/include/shim_defs.h, line 12 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQF19V8LqC1OdE_k05:-MSQF19V8LqC1OdE_k06:b-ikz1dq) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_defs.h#L12)):*
> ```objc
> 
> /* Internal LibOS stack size: 3 pages + one guard page. */
> #define SHIM_THREAD_LIBOS_STACK_SIZE (3 * PAGE_SIZE  + PAGE_SIZE)
> ```

please fix the double space
___
*[LibOS/shim/include/shim_internal.h, line 88 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU8CFOBaie9mSNszqt:-MSQFKEm9SVJF26yTYWf:bo33qgw) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_internal.h#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with both renaming and leaving as-is. You choice.
</blockquote></details>

I like `shim_emulate_syscall`. Please remember to also update the comment above when renaming.
___
*[LibOS/shim/include/shim_internal.h, line 84 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQNJcm2prgS3E0aMFU:-MSQNJcn7B6JfGvVlGso:b-60porb) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L84)):*
> ```objc
>  * \brief LibOS syscall emulation entrypoint.
>  *
>  * Actual implementation and ABI are architecture specific, but generally should dump the CPU
> ```

`architecture specific` -> `architecture-specific`
___
*[LibOS/shim/include/shim_internal.h, line 102 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQPsdg7gUqXejap-Cp:-MSQPsdg7gUqXejap-Cq:bc087nv) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L102)):*
> ```
> it does not need to be reentrant/atomic
> ```

This part seems confusing to me, this function doesn't have any control flow allowing for a nested call (no external calls) and if a signal arrives during it it still can't cause its execution (I mean, it's confusing why you state such a thing here).
Also, you mean `signal-atomic`?
___
*[LibOS/shim/include/shim_internal.h, line 122 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS9vP6WQ1lzuB6uOC:-MSQS9vP6WQ1lzuB6uOD:bor84z3) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L122)):*
> ```objc
>  * \param handler pointer to the user app signal handler
>  * \param restorer pointer to the restorer function
>  * \param use_altstack `true` if alternative stack can be used
> ```

The name is `use_*` and the doc says `can be used`. So, which meaning one is right? If the latter, the name should be something like `may_use_*` or `can_use_*`.
___
*[LibOS/shim/include/shim_internal.h, line 132 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS-2X78F9hP6UZj8_:-MSQS-2X78F9hP6UZj8a:b-nuyxdl) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L132)):*
> ```objc
>  */
> void prepare_sigframe(PAL_CONTEXT* context, siginfo_t* siginfo, uint64_t handler,
>                       uint64_t restorer, bool use_altstack, __sigset_t* old_mask);
> ```

I think the user app pointers should be `uintptr_t`?
___
*[LibOS/shim/include/shim_internal.h, line 148 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTCLC02Q7clW3k-9pG:-MSTCLC02Q7clW3k-9pH:b789gis) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L148)):*
> ```objc
>  * \param[out] new_mask new signal mask
>  *
>  * Restores cpu context in a architecure specific way. On entry to this function \p context holds
> ```

`cpu` -> `CPU`
`a architecure specific` -> `an architecture-specific` (`an`, `t` and `-`)
___
*[LibOS/shim/include/shim_signal.h, line 122 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTK367A6oKbST-UBkY:-MSTK3689dXHpE1rcUMY:bnwtonh) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_signal.h#L122)):*
> ```objc
>  * thread's settings.
>  */
> uint64_t get_stack_for_sighandler(uint64_t sp, bool use_altstack);
> ```

not `uintptr_t`? ditto for the whole PR
___
*[LibOS/shim/include/shim_thread.h, line 95 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTNlUO8q8J9meNXgTg:-MSTNlUP3jd4Q998Vbsk:b7ek571) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_thread.h#L95)):*
> ```objc
>     /*
>      * Space to store a forced, synchronous signal. Needed to handle e.g. `SIGSEGV` caused by
>      * referencing an invalid address, which we need to handle before any user generated `SIGSEGV`
> ```

`user generated` -> `user-generated`
___
*[LibOS/shim/src/generated-offsets.c, line 8 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTQZLMBg8Wyj_i5-2-:-MSTQZLMBg8Wyj_i5-20:bekjnoa) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/generated-offsets.c#L8)):*
> ```C
> 
> __attribute__((__used__)) static void dummy(void) {
>     OFFSET_T(SHIM_TCB_OFFSET, PAL_TCB, libos_tcb);
> ```

This one has `_OFFSET` suffix, but yours have `_OFF`. Please unify.
___
*[LibOS/shim/src/shim_arch_prctl-x86_64.c, line 25 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTRIDH9JgRrjhOwco5:-MSTRIDH9JgRrjhOwco6:b-7nv1lp) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/shim_arch_prctl-x86_64.c#L25)):*
> ```C
> 
>         default:
>             debug("Not supported flag (0x%x) pas [...]

2021-02-02 01:41 UTC, mkow reviewed
> Reviewed 2 of 55 files at r1, 2 of 8 files at r4, 1 of 7 files at r9, 2 of 14 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 55 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 142 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSVK9aW-URzjPBQND1q:-MSVK9aX32GBI5zYVBTX:bpp4lnp) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_thread.c#L142)):*
> ```C
>     void* tmp_vma = NULL;
>     if (bkeep_munmap(addr, SHIM_THREAD_LIBOS_STACK_SIZE, /*is_internal=*/true, &tmp_vma) < 0) {
>         debug("[alloc_thread_libos_stack]"
> ```

ditto (`log_*` after rebase)
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1338 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSVLaoHERlYJBSTOdNf:-MSVLaoHERlYJBSTOdNg:b-5bjn3l) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/elf/shim_rtld.c#L1338)):*
> ```C
>  */
> static void* vdso_addr __attribute_migratable                       = NULL;
> static ElfW(Addr)* __vdso_syscalldb __attribute_migratable        = NULL;
> ```

please fix `=` alignment (or better, just unalign both)
___
*[LibOS/shim/src/sys/shim_clone.c, line 134 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSVMp4O5A3haZWL2Bmt:-MSVMp4P-E8SA0A2_yHi:bvvnwwm) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/sys/shim_clone.c#L134)):*
> ```C
> static long do_clone_new_vm(unsigned long flags, struct shim_thread* thread, unsigned long tls,
>                             unsigned long user_stack_addr, int* set_parent_tid) {
>     assert(!(flags & CLONE_VM));
> ```

`flags` arg is used only in this assert, looks useless now.


<!-- Sent from Reviewable.io -->

2021-02-02 07:34 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 55 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 226 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSV4M1k3U7R_gERzptE:-MSWdBQS3zAE5CZ595g3:b-th4alc) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/Documentation/manifest-syntax.rst#L226)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you set it to 1 in one of the LibOS regression tests, e.g. `openmp`? It already sets another option just so that we have a test exercising it.
</blockquote></details>

Now that we remembered this: we should also set this to 1 in several examples. At least in Redis, Memcached, Nginx, Apache, Lighttpd, Nodejs, Nodejs-server, r, python-simple, ra-tls-mbedtls (in server).


<!-- Sent from Reviewable.io -->

2021-02-02 08:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 39 of 66 files reviewed, 54 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPJYcx8pyhfxP2ZQvr:-MSVvKj9Dgp3KCXSkhqt:b-mat3bg) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nitpick: `Pal` -> `PAL` in the commit message.
</blockquote></details>

TODO: at rebase.
Btw, I've just checked the history and apparently I've always written `Pal` in commit messages, seems this is the first time anybody noticed it :)

---
___
*[Documentation/manifest-syntax.rst, line 226 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSV4M1k3U7R_gERzptE:-MSVwcrY7eI0yykucPhz:becd412) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/Documentation/manifest-syntax.rst#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that we remembered this: we should also set this to 1 in several examples. At least in Redis, Memcached, Nginx, Apache, Lighttpd, Nodejs, Nodejs-server, r, python-simple, ra-tls-mbedtls (in server).
</blockquote></details>

Done. (except nodejs)
___
*[Documentation/manifest-syntax.rst, line 229 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPJtgb1oDEpGWcq588:-MSVwtt76sb7GptXTSRn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/Documentation/manifest-syntax.rst#L229)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`one time` -> `one-time`
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 232 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPK3781vOUP1cwP2QW:-MSVx0T958_i3hPc7QCv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/Documentation/manifest-syntax.rst#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`application` -> `application's`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_defs.h, line 12 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQF19V8LqC1OdE_k05:-MSVx9AWEkpxtXBo11sc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_defs.h#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix the double space
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 88 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU8CFOBaie9mSNszqt:-MSWtGy-1Bt49oEtqzv2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/include/shim_internal.h#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like `shim_emulate_syscall`. Please remember to also update the comment above when renaming.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 84 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQNJcm2prgS3E0aMFU:-MSVxHH37l-OqglM-kLR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`architecture specific` -> `architecture-specific`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 102 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQPsdg7gUqXejap-Cp:-MSVyH-ZCDwgh2nqq7ul:b4h79j9) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L102)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> it does not need to be reentrant/atomic
> ```

This part seems confusing to me, this function doesn't have any control flow allowing for a nested call (no external calls) and if a signal arrives during it it still can't cause its execution (I mean, it's confusing why you state such a thing here).
Also, you mean `signal-atomic`?
</blockquote></details>

But it uses global data, so it cannot be used e.g. for returning from host-level exception.
___
*[LibOS/shim/include/shim_internal.h, line 122 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS9vP6WQ1lzuB6uOC:-MSVzbq09iLJFUm9bAZw:bqw5nsq) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The name is `use_*` and the doc says `can be used`. So, which meaning one is right? If the latter, the name should be something like `may_use_*` or `can_use_*`.
</blockquote></details>

Yeah, but: I don't like the name `can_use_altstack` (sounds weird to me) and `may_use_*` is kind of misleading. This parameter indicated that the alternative signal stack should be used, but there might be some other reason preventing that from happening (e.g. it's already used).
___
*[LibOS/shim/include/shim_internal.h, line 132 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS-2X78F9hP6UZj8_:-MSVxhqa6E5h0bGBh6Hc:b7vmlc5) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the user app pointers should be `uintptr_t`?
</blockquote></details>

They should be `greg_t` or something similar, but we do not have such define yet (architecture register typedef).
I can stash it to this PR, but I believe it should come together with `PAL_CONTEXT` rename.
___
*[LibOS/shim/include/shim_internal.h, line 148 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTCLC02Q7clW3k-9pG:-MSVxYy-3jZLFB9M9cp7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L148)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`cpu` -> `CPU`
`a architecure specific` -> `an architecture-specific` (`an`, `t` and `-`)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_signal.h, line 122 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTK367A6oKbST-UBkY:-MSW-ewr7HWFxLjrhP4I:b-55m590) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_signal.h#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not `uintptr_t`? ditto for the whole PR
</blockquote></details>

See the comment near `prepare_sigframe`.
___
*[LibOS/shim/include/shim_thread.h, line 95 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTNlUO8q8J9meNXgTg:-MSW3OGh2-7ilynbeFwh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_thread.h#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`user generated` -> `user-generated`
</blockquote></details>

Done.
___
*[LibOS/shim/src/generated-offsets.c, line 8 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTQZLMBg8Wyj_i5-2-:-MSW4F8JCCJnoDBfHym8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/generated-offsets.c#L8)): [...]

2021-02-02 09:41 UTC, dimakuv requested changes
> Reviewed 27 of 27 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 55 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @stefanberger, and @yamahata)

___
*[LibOS/shim/src/syscallas-x86_64.S, line 163 at r13](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSX5xvkAhfQ5CAgsCBO:-MSX5xvkAhfQ5CAgsCBP:b-taed4x) ([raw file](https://github.com/oscarlab/graphene/blob/a26d1caa167a8f786a1bc785f351434b3ee0408c/LibOS/shim/src/syscallas-x86_64.S#L163)):*
> ```
>     # instruction in there) into r14 (a callee-saved register) and mark it as holding old rip. This
>     # way GDB thinks `syscalldb` was called by `__morestack`. Inside `__morestack` we mark all
>     # register as having the same value as in the previous frame (basically a no-op frame). Now GDB
> ```

`register` -> `registers`


<!-- Sent from Reviewable.io -->

2021-02-02 13:10 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: 65 of 67 files reviewed, 55 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMr83j6e-zOT69GEiq:-MSXqxVoAMGepRuT2S5h:bu60z9h) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, but I was not rushing fixing all TODOs, since I also wait for @mkow review :)
</blockquote></details>

@dimakuv Could you double check the patch?

---
___
*[LibOS/shim/src/syscallas-x86_64.S, line 163 at r13](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSX5xvkAhfQ5CAgsCBO:-MSXrFA6D1PILXWsz3qf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a26d1caa167a8f786a1bc785f351434b3ee0408c/LibOS/shim/src/syscallas-x86_64.S#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`register` -> `registers`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 13:38 UTC, stefanberger reviewed
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 49 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @stefanberger, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-02-02 17:01 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 47 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRMr83j6e-zOT69GEiq:-MSYg5Bi15R-T182TrzX:bbu2g0n) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv Could you double check the patch?
</blockquote></details>

LGTM, after 3 hours of building GCC and `libgomp.so`, it worked.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPJYcx8pyhfxP2ZQvr:-MSXu8jv0jWW1jUrH4Qu:b-mnegv9) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase.
Btw, I've just checked the history and apparently I've always written `Pal` in commit messages, seems this is the first time anybody noticed it :)
</blockquote></details>

Yeah, we have inconsistency here. For the prefix, we almost always use `[Pal]`, but inside commit messages we use `PAL`. But I agree with Michal, at least inside the message we should write `PAL`.

---


<!-- Sent from Reviewable.io -->

2021-02-02 23:35 UTC, mkow requested changes
> Reviewed 5 of 55 files at r1, 1 of 6 files at r7, 1 of 9 files at r8, 2 of 7 files at r9, 4 of 14 files at r12, 26 of 27 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 27 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPJYcx8pyhfxP2ZQvr:-MSZ254cBJXGs61sJUbl:ba5iept) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, we have inconsistency here. For the prefix, we almost always use `[Pal]`, but inside commit messages we use `PAL`. But I agree with Michal, at least inside the message we should write `PAL`.
</blockquote></details>

yeah, I meant only in the message body, not `[Pal]` (we use "Pal" because that's the name of the corresponding top-level directory, but it's quite a questionable choice, I'm following it only for consistency)

---
___
*[LibOS/shim/include/shim_internal.h, line 102 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQPsdg7gUqXejap-Cp:-MSZDXIZ5Zrt3aMfqVDd:bpbmk6f) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L102)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But it uses global data, so it cannot be used e.g. for returning from host-level exception.
</blockquote></details>

Yeah, but it's "return_from_syscall", not "return_from_exception". Anyways, unblocking.
___
*[LibOS/shim/include/shim_internal.h, line 122 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS9vP6WQ1lzuB6uOC:-MSZEBuQ90kaQS1E3bO6:b-3ngmzp) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, but: I don't like the name `can_use_altstack` (sounds weird to me) and `may_use_*` is kind of misleading. This parameter indicated that the alternative signal stack should be used, but there might be some other reason preventing that from happening (e.g. it's already used).
</blockquote></details>

So, maybe `should_use_altstack`? Quite long, but not misleading. Could you also make the comment more precise? Only after your response here I got how this works.
___
*[LibOS/shim/include/shim_internal.h, line 132 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS-2X78F9hP6UZj8_:-MSZEVA70KGXxNxjHD_e:b-kqu7zw) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L132)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

They should be `greg_t` or something similar, but we do not have such define yet (architecture register typedef).
I can stash it to this PR, but I believe it should come together with `PAL_CONTEXT` rename.
</blockquote></details>

Not sure about this, `greg_t` is just for register storage, here we know the values are pointers, not arbitrary registers. I don't like `uint64_t` because it's 64-bit even on 32-bit, `uintptr_t` will always have the right size.
___
*[LibOS/shim/include/shim_thread.h, line 87 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZahShDgoWf7j_09qf:-MSZahShDgoWf7j_09qg:b-loag28) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/include/shim_thread.h#L87)):*
> ```objc
>     /* signal handling */
>     __sigset_t signal_mask;
>     /* Always take `thread->signal_dispositions->lock` before `thread->lock`. */
> ```

This hierarchy is quite unintuitive, should it really be like this? There are many places which take `thread->lock` without holding `thread->signal_dispositions->lock`.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 157 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTUKKs0yG4jS7gKeBc:-MSZGIsg6dQUuAHlsrB3:b-pf7in8) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/shim_context-x86_64.c#L157)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`edx:eax` is a feature mask for `xrstor`.
</blockquote></details>

Oops, I looked at `fxrstor` instead, my bad. Resolving.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 227 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTYJWQCBlyT-U0bBhK:-MSZGmHS2pXnkOqo0Ekq:bbz411s) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/shim_context-x86_64.c#L227)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It does, but without writing down this `static_assert` (and then realizing it's always true) it was not immediately clear (at least to me), that the second `ALIGN_DOWN` doesn't break the first one. Treat it as a comment (extension of the comment above it).
</blockquote></details>

This assert was _really_ confusing to me, a check which does nothing in a convoluted way is very suspicious when I read code ;)
I'd prefer to clarify this in the comment than to have such an assert (it's not even obvious why it's here).
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 687 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSV68Aw5OXM8qxdNjR8:-MSZ_9lsBEOp6kL2bmW7:b-xtw5p4) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L687)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The edge cases are tricky here - if `alt_sp == sp` then either the alternative stack is full or we have another stack allocated above it (at lower address) which is empty and just about to be used...
I've chosen the second case, since overflowing the alt stack is undefined behavior and chances for reaching exactly the top of the alt stack without overflowing are minimal.
Update: I've just checked and the Linux kernel does the same, however it's unclear for what reasons (there is no comment): https://elixir.bootlin.com/linux/latest/source/include/linux/sched/signal.h#L549
</blockquote></details>

Ok, makes sense, but IMO it's worth a comment (why we've chosen this specific boundary)
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 857 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSVEuoKAEoBil465Zjf:-MSZbYw608c1B78Q3fHn:b-8x2bdc) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L857)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, I think if we say "I"/"me"/"my" then we should probably add a nickname of the author of this comment? Something like: "borysp: In my opinion [...]". Or just not use "I"/"me"/"my" ;)
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 40 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZdAWX5z0ppAYO5OOQ:-MSZdAWX5z0ppAYO5OOR:b-mhcbnk) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L40)):*
> ```C
>         return -EFAULT;
> 
>     if (oldact && test_user_memory(oldact, sizeof(*oldact), true))
> ```

while we're here: please add name to the bool arg (ditto above)
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 44 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZdOBZ4_z1XQsq4wcR:-MSZdOBZ4_z1XQsq4wcS:b-61chr6) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L44)):*
> ```C
> 
>  [...]

2021-02-03 22:59 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 26 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 122 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS9vP6WQ1lzuB6uOC:-MScIR7c4gp6AVPT2J8V:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, maybe `should_use_altstack`? Quite long, but not misleading. Could you also make the comment more precise? Only after your response here I got how this works.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 132 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSQS-2X78F9hP6UZj8_:-MSca54245mvE2vjmKIP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_internal.h#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not sure about this, `greg_t` is just for register storage, here we know the values are pointers, not arbitrary registers. I don't like `uint64_t` because it's 64-bit even on 32-bit, `uintptr_t` will always have the right size.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_signal.h, line 122 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTK367A6oKbST-UBkY:-MSccIXR7r4DNhQlf2ez:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/include/shim_signal.h#L122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

See the comment near `prepare_sigframe`.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 87 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZahShDgoWf7j_09qf:-MSccS6W0fUYH_s9izx8:b-ibuq5i) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/include/shim_thread.h#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This hierarchy is quite unintuitive, should it really be like this? There are many places which take `thread->lock` without holding `thread->signal_dispositions->lock`.
</blockquote></details>

And basically nothing takes `thread->signal_dispositions->lock`. This hierarchy is fine, updated the comment to be more descriptive.
___
*[LibOS/shim/src/shim_context-x86_64.c, line 227 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTYJWQCBlyT-U0bBhK:-MSdv4GYEVfVo2W4lL7m:b-47yzv) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/shim_context-x86_64.c#L227)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This assert was _really_ confusing to me, a check which does nothing in a convoluted way is very suspicious when I read code ;)
I'd prefer to clarify this in the comment than to have such an assert (it's not even obvious why it's here).
</blockquote></details>

Check now.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 687 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSV68Aw5OXM8qxdNjR8:-MSdwGhbEFav61cjOedA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L687)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, makes sense, but IMO it's worth a comment (why we've chosen this specific boundary)
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 857 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSVEuoKAEoBil465Zjf:-MSdwZ6L7cRSOiGMUQza:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L857)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, I think if we say "I"/"me"/"my" then we should probably add a nickname of the author of this comment? Something like: "borysp: In my opinion [...]". Or just not use "I"/"me"/"my" ;)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 40 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZdAWX5z0ppAYO5OOQ:-MSdx4tdCvxEMf68bn6C:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

while we're here: please add name to the bool arg (ditto above)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 44 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZdOBZ4_z1XQsq4wcR:-MSdxCZWElsiKDHWgj7x:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space before ellipsis
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 139 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZe8Ef5WBw0OF4343i:-MSdxJKa1v_HfYMcgrNB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

here and above: the argument is called `write`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 160 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZf8xUDOpfM7Uv3udd:-MSdzsyq-p_3S59arNnu:b-7j5w5p) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L160)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How could `cur_ss->ss_flags & SS_DISABLE` be true while current `sp` is on the altstack? (the `if` above) Seems impossible to me, but I probably just don't get how this thing works.
</blockquote></details>

Good catch, it was a bug I introduced (this check was supposed to be in the previous `if`).
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 228 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZg4Jh0ZjsR24JgANP:-MSe-C792X6a5AEcPZ6c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no testing for writing? (+named arg)
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 284 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZgdR55QIGAhVzso1A:-MSe-IM_BDlpUVIwEYih:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/LibOS/shim/src/sys/shim_sigaction.c#L284)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`singal` -> `signal`
</blockquote></details>

Done.
___
*[Pal/include/arch/x86_64/pal-arch.h, line 250 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSZuOJs42Nfw3X0jZrn:-MSe0Cj-5EZvCV4sqdOM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/Pal/include/arch/x86_64/pal-arch.h#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`fpu/sse` -> `FPU/SSE`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 572 at r14](https://reviewable.io/ [...]

2021-02-04 00:17 UTC, mkow requested changes
> Reviewed 16 of 16 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 135 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSUiHXF3pXFGwLEOA7j:-MSeIj75CK6rPCfqLXrB:b-71bzs7) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L135)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Elaborate.
</blockquote></details>

I meant that the variable name is `queue`, but it's just a pointer to a signal object, not to a queue?
___
*[LibOS/shim/src/sys/shim_clone.c, line 134 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSVMp4O5A3haZWL2Bmt:-MSeJz1vAxb3H_MKZdI-:bfbahxo) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/sys/shim_clone.c#L134)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is not true (line 195).
</blockquote></details>

Sorry, I must have stopped expanding the file diff an a wrong brace :)
___
*[Pal/src/host/Linux/db_exception.c, line 161 at r15](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSeNGwX2OHMmvCyv8sb:-MSeNGwX2OHMmvCyv8sc:bpbo02b) ([raw file](https://github.com/oscarlab/graphene/blob/04816a88e4e2f1093cb8e7131931d88251ff6983/Pal/src/host/Linux/db_exception.c#L161)):*
> ```C
> }
> 
> /* TODO: remove this function. It's not an expcetion handling, it's just returning an error from
> ```

`expcetion` -> `exception`
but yeah, we should finally delete this mess
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2X8Ur-6fmcJRjEIDz:-MSeNkNf-FEervNaSQxt:b-2jdfwc) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/Pal/src/host/Linux-SGX/db_exception.c#L283)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can also go in a follow-up PR. Not blocking.
</blockquote></details>

Please open an issue for this if you aren't planning to fix this now, sounds like an important thing.
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 317 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS_3XgiDczUZSWTduzN:-MSeNxW08HX6q9qm_3uZ:b-l2wr0d) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/Pal/src/host/Linux-SGX/db_exception.c#L317)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

?
</blockquote></details>

What's this TODO? It's just a single, commented out line of code. Looks like you forgot to fix/remove this before submitting the PR?
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 272 at r15](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSeNaAPAB1eL7c5m4sc:-MSeNaAPAB1eL7c5m4sd:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/04816a88e4e2f1093cb8e7131931d88251ff6983/Pal/src/host/Linux-SGX/db_exception.c#L272)):*
> ```C
> }
> 
> /* TODO: remove this function. It's not an expcetion handling, it's just returning an error from
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 177 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS_3pSg3zx4U1TaVTUd:-MSeOBWG7AUQy8Id23Ld:brxygvj) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/Pal/src/host/Linux-SGX/sgx_exception.c#L177)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, why would it be? I did not change sgx-host-signal flows.
</blockquote></details>

Ah, I see. But this influences only locks in the untrusted PAL, right? I mean, can this be a security issue, or only stability?


<!-- Sent from Reviewable.io -->

2021-02-04 00:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 135 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSUiHXF3pXFGwLEOA7j:-MSeQMKxEnGFs9iIzpXr:b-axa1p8) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I meant that the variable name is `queue`, but it's just a pointer to a signal object, not to a queue?
</blockquote></details>

It's a queue, but it has maximum size of `1` :)
___
*[Pal/src/host/Linux/db_exception.c, line 161 at r15](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSeNGwX2OHMmvCyv8sb:-MSeUHM3DPrXlM_SkndU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/04816a88e4e2f1093cb8e7131931d88251ff6983/Pal/src/host/Linux/db_exception.c#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`expcetion` -> `exception`
but yeah, we should finally delete this mess
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2X8Ur-6fmcJRjEIDz:-MSeUQH2CNKPeNA_Rd8x:b-dg3dfk) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/Pal/src/host/Linux-SGX/db_exception.c#L283)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please open an issue for this if you aren't planning to fix this now, sounds like an important thing.
</blockquote></details>

Yeah, I'll open a issue with all leftovers/TODOs from this PR. Just waiting for this PR to be ready.
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 317 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS_3XgiDczUZSWTduzN:-MSeUeQC6YAKb_3ia5HS:b-kzto9e) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/Pal/src/host/Linux-SGX/db_exception.c#L317)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's this TODO? It's just a single, commented out line of code. Looks like you forgot to fix/remove this before submitting the PR?
</blockquote></details>

This is basically the same thing as the comment above: this function needs to be fixed/removed. If it's to stay, then it needs something like that here.
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 272 at r15](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSeNaAPAB1eL7c5m4sc:-MSeUMgtDZzlABHb-tbW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/04816a88e4e2f1093cb8e7131931d88251ff6983/Pal/src/host/Linux-SGX/db_exception.c#L272)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 177 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS_3pSg3zx4U1TaVTUd:-MSeVewaCZMGdqXv_T-J:bzbq7ur) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/Pal/src/host/Linux-SGX/sgx_exception.c#L177)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I see. But this influences only locks in the untrusted PAL, right? I mean, can this be a security issue, or only stability?
</blockquote></details>

All it does is fakes `-EINTR` as return value from the current ocall.


<!-- Sent from Reviewable.io -->

2021-02-04 02:46 UTC, mkow requested changes
> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 135 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSUiHXF3pXFGwLEOA7j:-MSepv1x3PYqSqCX29hQ:bg29qda) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L135)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's a queue, but it has maximum size of `1` :)
</blockquote></details>

Can we _not_ name it "a queue" then? It's just an object which is optional. The "queue" name is IMO misleading, an obvious connotation to a "queue" is that it holds a bunch of ordered elements, which are waiting in that order to be dealt with. Also, this name doesn't work well with standard signals, which are _not queued_, but in this implementation we insert them into this "queue".
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 317 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS_3XgiDczUZSWTduzN:-MSevQSY9S3VzFb15jpi:b-a3s9c4) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/Pal/src/host/Linux-SGX/db_exception.c#L317)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is basically the same thing as the comment above: this function needs to be fixed/removed. If it's to stay, then it needs something like that here.
</blockquote></details>

Then please add _any_ text to it. Right now it looks like some garbage you forgot to delete before submitting the PR. No one except you known what you mean by this line ;)


<!-- Sent from Reviewable.io -->

2021-02-04 07:17 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)



<!-- Sent from Reviewable.io -->

2021-02-04 15:53 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 135 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSUiHXF3pXFGwLEOA7j:-MShYsf1-upYCbakzYIs:b-iwmvro) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we _not_ name it "a queue" then? It's just an object which is optional. The "queue" name is IMO misleading, an obvious connotation to a "queue" is that it holds a bunch of ordered elements, which are waiting in that order to be dealt with. Also, this name doesn't work well with standard signals, which are _not queued_, but in this implementation we insert them into this "queue".
</blockquote></details>

But this is not just a object pointer, this a pointer to a "slot" (slot in a queue, to be fair), it always exists, we just check whether it's used.
And I would argue this is a queue and the fact that we limit it's size to 1 is an implementation detail which reader of the signature doesn't need to care about.
But to speed things up, I renamed it to something else.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 196 at r8](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRU4bpQDPrGU29MFyb8:-MShifA12JC51W_jg1C2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a99d2f9641d8325bfcc3c58151a1433754fd65e5/LibOS/shim/src/bookkeep/shim_thread.c#L196)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: write down all leftovers from this PR in an issue.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sigaction.c, line 120 at r4](https://reviewable.io/reviews/oscarlab/graphene/2090#-MRKo394AkPEQQ6rF4vT:-MShihHkBV1k5xVqxAf0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d2dea5f4ec7362b8139333e171c1554735a20098/LibOS/shim/src/sys/shim_sigaction.c#L120)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I'll leave a blocking comment to remind me to add a TODO or GH issue before merging it.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2090#-MR2X8Ur-6fmcJRjEIDz:-MShina38QC99MIiUUPg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c6b3f82e1346eea1e2eb407d7eaad0eaf991206d/Pal/src/host/Linux-SGX/db_exception.c#L283)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, I'll open a issue with all leftovers/TODOs from this PR. Just waiting for this PR to be ready.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 317 at r14](https://reviewable.io/reviews/oscarlab/graphene/2090#-MS_3XgiDczUZSWTduzN:-MShfkMP1_fc06WnF-R6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4dd0c0578de6b681bfb14d8cd4a6e847b330b5ce/Pal/src/host/Linux-SGX/db_exception.c#L317)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then please add _any_ text to it. Right now it looks like some garbage you forgot to delete before submitting the PR. No one except you known what you mean by this line ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 02:17 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 135 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSUiHXF3pXFGwLEOA7j:-MSjxEuQ7wKd9s5fF6T5:bq5kc49) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_signal.c#L135)):*
> And I would argue this is a queue and the fact that we limit it's size to 1 is an implementation detail which reader of the signature doesn't need to care about.

But using the name "queue" for just one slot is IMO misleading and so the signature with such an argument.

Anyways, the new name is much better :)


<!-- Sent from Reviewable.io -->

2021-02-05 07:35 UTC, dimakuv approved these changes
> Reviewed 12 of 16 files at r15, 1 of 2 files at r16, 5 of 5 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-02-05 13:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSPJYcx8pyhfxP2ZQvr:-MSmIRWS6tRfqHAfBiCV:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

yeah, I meant only in the message body, not `[Pal]` (we use "Pal" because that's the name of the corresponding top-level directory, but it's quite a questionable choice, I'm following it only for consistency)
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/shim_arch_prctl-x86_64.c, line 25 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTRIDH9JgRrjhOwco5:-MSmHefq1qNNgHXaWNUo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/shim_arch_prctl-x86_64.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_syscalls.c, line 13 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSTcGwhCp4S_dcfvX8R:-MSmI-mdC-0erVzSL2eK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/shim_syscalls.c#L13)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 142 at r12](https://reviewable.io/reviews/oscarlab/graphene/2090#-MSVK9aW-URzjPBQND1q:-MSmIEPJ6yssf-hJR6GQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98c4ce15465675af728ce5037911ae3262df10af/LibOS/shim/src/bookkeep/shim_thread.c#L142)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 13:28 UTC, mkow approved these changes
> Reviewed 17 of 17 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-05 13:54 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 2/5)

2021-02-05 14:18 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-apps please (`enclave EINIT failed`, known issue unrelated to the PR)

2021-02-05 14:21 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-05 14:44 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 3/5)

2021-02-05 16:05 UTC, yamahata approved these changes
> Reviewed 2 of 8 files at r4, 5 of 16 files at r5, 1 of 9 files at r8, 2 of 7 files at r9, 2 of 14 files at r12, 14 of 27 files at r13, 2 of 2 files at r14, 9 of 16 files at r15, 1 of 2 files at r16, 2 of 5 files at r17, 17 of 17 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-05 16:31 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 4/5)

2021-02-05 16:53 UTC, boryspoplawski commented
3/5 had one fail: Jenkins-18.04 - LibOS/regression `./exit_group 2 102` failed with `wrong wait() status: 9` (this is know issue, IPC), but also had `Internal memory fault` in `check_last_thread` - in `LISTP_DEL_INIT` `self->prev` was `NULL`. From reading the code it should not be possible (this it only place in whole Graphene that removes a thread from global list and it's covered with a lock), so this probably is some unrelated overwrite. Unfortunately I could not reproduce it locally.

2021-02-05 17:08 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 5/5)

2021-02-05 20:51 UTC, stefanberger reviewed
looks like this 'storm' is arriving now ;-)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090#-:-MSnxZ594_2ZPWq3R9sE:bd86w8i)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-05 22:56 UTC, merged

2021-02-05 22:57 UTC, boryspoplawski reviewed
Just merged :)
Feel free to pm me or send me an email (address in commits) if I can be of any help with rebasing

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2090#-:-MSoPPWkD9HVNnAyMb4x:b5wf7z2)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-09 01:22 UTC, stefanberger commented
> Feel free to pm me or send me an email (address in commits) if I can be of any help with rebasing

@boryspoplawski Thanks for the offer. The PPC64 port is back on track after the pitstop. It has become really beautiful with the PAL_CONTEXT used also now on the shim layer! The rebasing was a challenge in some parts but I am amazed in how things fit together. Great work, guys!