[Docs,LibOS] Move helloworld example from native/ to regression/
oscarlab/graphene pull request #2092
Opened 2021-01-15 10:40 UTC by dimakuv

## Description of the changes 

Applications under `native/` cannot be built after commit "Introduce one, central manifest, zero-config children and constant MRENCLAVE". Instead of fixing `native/`, this commit simply moves `helloworld` and all its mentions under `regression/`.

## How to test this PR? 

New test `helloworld` is added to the LibOS regression tests.

2021-01-15 12:58 UTC, yamahata submitted a review, later dismissed
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2092)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-15 17:25 UTC, boryspoplawski requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2092)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/native/helloworld.c, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2092#-MR63yYk421bHC9g7u20:-MR63yYk421bHC9g7u21:b-3dacfw) ([raw file](https://github.com/oscarlab/graphene/blob/5dace18916d9127162013d6de924701746a1c6ae/LibOS/shim/test/native/helloworld.c#L6)):*
> ```C
> 
> int main(int argc, char** argv) {
>     printf("Hello world (%s)!\n", argv[0]);
> ```

Why did you remove `argv[0]`?


<!-- Sent from Reviewable.io -->

2021-01-15 20:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2092)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/native/helloworld.c, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2092#-MR63yYk421bHC9g7u20:-MR6p5gi5hXp4shMWu4L:b-kt0eof) ([raw file](https://github.com/oscarlab/graphene/blob/5dace18916d9127162013d6de924701746a1c6ae/LibOS/shim/test/native/helloworld.c#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you remove `argv[0]`?
</blockquote></details>

I don't see any point in printing `Hello world helloworld`. The textbook example simply prints `Hello world`, so I decided we just do this.

This Helloworld example is anyway mainly for Quick Start in the documentation.


<!-- Sent from Reviewable.io -->

2021-01-16 16:26 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2092)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-16 21:01 UTC, yamahata approved these changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2092)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-17 15:37 UTC, mkow approved these changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2092)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-17 18:40 UTC, merged