[LibOS] Cast mask to unsigned long (UBSAN)
oscarlab/graphene pull request #2097
Opened 2021-01-15 23:28 UTC by stefanberger

We need to cast the mask used in select() to an unsigned int, otherwise UBSAN complains about it being a negative number.

2021-01-15 23:44 UTC, stefanberger commented
As far as regression tests for PAL and LibOS layers are concerned, almost all regression tests now pass on these layers. One exception is test_110_basic_bootstrapping_cpp that will probably have to be excluded from running.

```
$ ~/tmp/graphene.upstream/Runtime/pal-Linux ~/tmp/graphene.upstream/Runtime/ init ./bootstrap_cpp
WARNING: Using insecure argv source. Don't use this configuration in production!
==3670747==Sanitizer CHECK failed: ../../../../libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cpp:289 ((14)) == ((write_errno)) (14, 107)
```

Once all these tests are merged, I'll post the small Makefile changes so that this could possibly be used by Jenkins... though more issues are lurking with ltp where gdb catches `clock_gettime`, though this isn't the real problem.

2021-01-17 18:38 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[LibOS/shim/src/sys/shim_poll.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRGcTc28GF1yQectjx_:-MRGcTc28GF1yQectjxa:b-str9ip) ([raw file](https://github.com/oscarlab/graphene/blob/549a2e226f591d9cc9aa32f9dc1cfbd85fca1e00/LibOS/shim/src/sys/shim_poll.c#L41)):*
> ```C
> #define __FD_ELT(d)        ((d) / __NFDBITS)
> /* ubsan requires the mask to be an unsigned long */
> #define __FD_MASK(d)       ((unsigned long)(__fd_mask)1 << ((d) % __NFDBITS))
> ```

What's the point of the `(__fd_mask)` cast now? Also, why is `__fd_mask` signed? Can't we just change it to `unsigned long`?
I don't like such silencing UBSAN without investigating and fixing the underlying issue ;)


<!-- Sent from Reviewable.io -->

2021-01-18 01:05 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_poll.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRGcTc28GF1yQectjx_:-MRI-TAH7KohIcT2Esep:b-s3b79a) ([raw file](https://github.com/oscarlab/graphene/blob/549a2e226f591d9cc9aa32f9dc1cfbd85fca1e00/LibOS/shim/src/sys/shim_poll.c#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of the `(__fd_mask)` cast now? Also, why is `__fd_mask` signed? Can't we just change it to `unsigned long`?
I don't like such silencing UBSAN without investigating and fixing the underlying issue ;)
</blockquote></details>

This is where the problem comes from: `/usr/include/powerpc64le-linux-gnu/sys/select.h:typedef long int __fd_mask;`


<!-- Sent from Reviewable.io -->

2021-01-18 01:05 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_poll.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRGcTc28GF1yQectjx_:-MRI0b6R8sOYhxy0TFKz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/549a2e226f591d9cc9aa32f9dc1cfbd85fca1e00/LibOS/shim/src/sys/shim_poll.c#L41)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This is where the problem comes from: `/usr/include/powerpc64le-linux-gnu/sys/select.h:typedef long int __fd_mask;`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-18 03:02 UTC, mkow reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

___
*[LibOS/shim/src/sys/shim_poll.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRGcTc28GF1yQectjx_:-MRIPxK-79RhG9M-10ee:bual0gt) ([raw file](https://github.com/oscarlab/graphene/blob/549a2e226f591d9cc9aa32f9dc1cfbd85fca1e00/LibOS/shim/src/sys/shim_poll.c#L41)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But this is our own implementation, which we don't expose to the user app (I mean, this type definition). Why can't we use sane types and not have such problems at all?


<!-- Sent from Reviewable.io -->

2021-01-18 04:16 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_poll.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRGcTc28GF1yQectjx_:-MRIhE6Z4nV-M9NuOMrl:bu56l2k) ([raw file](https://github.com/oscarlab/graphene/blob/549a2e226f591d9cc9aa32f9dc1cfbd85fca1e00/LibOS/shim/src/sys/shim_poll.c#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this is our own implementation, which we don't expose to the user app (I mean, this type definition). Why can't we use sane types and not have such problems at all?
</blockquote></details>

We would have to define our own type(s) rather than using the one(s) from Linux...


<!-- Sent from Reviewable.io -->

2021-01-18 07:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/src/sys/shim_poll.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRGcTc28GF1yQectjx_:-MRJS3Pg2G8PdbbITE3X:b-n2v55d) ([raw file](https://github.com/oscarlab/graphene/blob/549a2e226f591d9cc9aa32f9dc1cfbd85fca1e00/LibOS/shim/src/sys/shim_poll.c#L41)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

We would have to define our own type(s) rather than using the one(s) from Linux...
</blockquote></details>

+1 to Michal. I don't know why Linux uses a signed type of `__fd_mask`, but I see that Android Bionic, OpenBSD, etc. use normal unsigned int:
- https://android.googlesource.com/platform/bionic/+/master/libc/include/sys/select.h#44
- http://www.cs.cmu.edu/afs/cs.cmu.edu/academic/class/15745-f03/public/Linux/nci/include/ncicfe/gnu/types.h
- https://github.com/openbsd/src/blob/master/sys/sys/select.h#L70

So let's just change the type of `__fd_mask`.
___
*[LibOS/shim/src/sys/shim_poll.c, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRJSRfGAcrojzGG8jy4:-MRJSRfGAcrojzGG8jy5:bhjkmgu) ([raw file](https://github.com/oscarlab/graphene/blob/0d6d51404027700df2e5baffbae0715ccaec76cc/LibOS/shim/src/sys/shim_poll.c#L21)):*
> ```C
> #include "shim_utils.h"
> 
> typedef long int __fd_mask;
> ```

Let's just add `unsigned` here.


<!-- Sent from Reviewable.io -->

2021-01-18 11:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

___
*[LibOS/shim/src/sys/shim_poll.c, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRGcTc28GF1yQectjx_:-MRKKl1b78_dp2kOu9dU:b-cogh2w) ([raw file](https://github.com/oscarlab/graphene/blob/549a2e226f591d9cc9aa32f9dc1cfbd85fca1e00/LibOS/shim/src/sys/shim_poll.c#L41)):*
> We would have to define our own type(s) rather than using the one(s) from Linux...

What the problem with this? It's our own, custom implementation of Linux API, we have to conform to the API, but why would it matter how exactly we coded it internally?


<!-- Sent from Reviewable.io -->

2021-01-18 11:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_poll.c, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRJSRfGAcrojzGG8jy4:-MRKL5Ww7eJ8CTxDYCGG:bqvy8cn) ([raw file](https://github.com/oscarlab/graphene/blob/0d6d51404027700df2e5baffbae0715ccaec76cc/LibOS/shim/src/sys/shim_poll.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's just add `unsigned` here.
</blockquote></details>

and drop superfluous `int`


<!-- Sent from Reviewable.io -->

2021-01-19 16:15 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_poll.c, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRJSRfGAcrojzGG8jy4:-MRQQJ_p4Z17mBDvFnvy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d6d51404027700df2e5baffbae0715ccaec76cc/LibOS/shim/src/sys/shim_poll.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

and drop superfluous `int`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 16:31 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

___
*[LibOS/shim/src/sys/shim_poll.c, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRQU-KC7DtrnB7-D580:-MRQU-KC7DtrnB7-D581:b-4ht2w5) ([raw file](https://github.com/oscarlab/graphene/blob/08cdb5c59be6fdae7cf721efd327f1fb42588631/LibOS/shim/src/sys/shim_poll.c#L40)):*
> ```C
> 
> #define __FD_ELT(d)        ((d) / __NFDBITS)
> /* ubsan requires the mask to be an unsigned long */
> ```

this comment is now obsolete


<!-- Sent from Reviewable.io -->

2021-01-19 16:31 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

___
*[LibOS/shim/src/sys/shim_poll.c, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRQU-KC7DtrnB7-D580:-MRQU4jJAHH8lSDyuJFI:b-m8fr8t) ([raw file](https://github.com/oscarlab/graphene/blob/08cdb5c59be6fdae7cf721efd327f1fb42588631/LibOS/shim/src/sys/shim_poll.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this comment is now obsolete
</blockquote></details>

(just remove it)


<!-- Sent from Reviewable.io -->

2021-01-19 16:42 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_poll.c, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRQU-KC7DtrnB7-D580:-MRQWdVh0nnl0vvCvP80:b-b79yz2) ([raw file](https://github.com/oscarlab/graphene/blob/08cdb5c59be6fdae7cf721efd327f1fb42588631/LibOS/shim/src/sys/shim_poll.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

(just remove it)
</blockquote></details>

argh, yes.


<!-- Sent from Reviewable.io -->

2021-01-19 16:43 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_poll.c, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRQU-KC7DtrnB7-D580:-MRQWxaZCTeEAacv7aSR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/08cdb5c59be6fdae7cf721efd327f1fb42588631/LibOS/shim/src/sys/shim_poll.c#L40)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

argh, yes.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 16:47 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_poll.c, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2097#-MRQU-KC7DtrnB7-D580:-MRQXe1o8GPNZahPx0xB:b32vhw) ([raw file](https://github.com/oscarlab/graphene/blob/08cdb5c59be6fdae7cf721efd327f1fb42588631/LibOS/shim/src/sys/shim_poll.c#L40)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2021-01-19 17:05 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-19 19:18 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-01-19 19:18 UTC, mkow commented
Jenkins, retest this please

2021-01-19 19:32 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-01-19 19:45 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2097)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-19 19:52 UTC, merged