[Pal,LibOS] Fix GDB integration in case of removing maps
oscarlab/graphene pull request #2099
Opened 2021-01-18 10:48 UTC by pwmarcz

Follow-up to #2044.

- The GDB command for removing a symbol file takes text address
  (or any address inside the mapped memory area), not load offset
  (which might be before the area). Because of that, removing a 
  map in GDB did not actually work, and displayed a warning.
- The remove_r_debug() function in LibOS did not actually remove
  the map from list in LibOS. As a result, LibOS attempted to
  report the removal to PAL more than once, causing a harmless but
  annoying warning message.

## How to test this PR? 

Compile with `DEBUG=1` and run a test case with exec, e.g. `./pal_loader exec_same 1 2 3` (in LibOS/shim/test/regression).
There should be no console warnings (on master, it says `debug_map_remove(...) failed: -22` multiple times).

When running the same example under GDB, there should also be no failure messages (on master, it says `warning: failed to remove symbol file`)

2021-01-18 11:13 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[LibOS/shim/src/shim_debug.c, line 85 at r1](https://reviewable.io/reviews/oscarlab/graphene/2099#-MRKBSq_6vUPBzENKWk4:-MRKBSq_6vUPBzENKWk5:b5bvsqj) ([raw file](https://github.com/oscarlab/graphene/blob/3fa92763e49ab2eed8ea31d5c867e38b01e6db53/LibOS/shim/src/shim_debug.c#L85)):*
> ```C
>         m->l_next->l_prev = m->l_prev;
>     } else {
>         link_map_list = m->l_prev;
> ```

Is this correct? You have a singly linked list, but here you're saying "if there is no next element after the to-remove one, then update the head of the list"...


<!-- Sent from Reviewable.io -->

2021-01-18 11:20 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_debug.c, line 85 at r1](https://reviewable.io/reviews/oscarlab/graphene/2099#-MRKBSq_6vUPBzENKWk4:-MRKCyXt6dg2xZe1ohN4:bk32e7c) ([raw file](https://github.com/oscarlab/graphene/blob/3fa92763e49ab2eed8ea31d5c867e38b01e6db53/LibOS/shim/src/shim_debug.c#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this correct? You have a singly linked list, but here you're saying "if there is no next element after the to-remove one, then update the head of the list"...
</blockquote></details>

Oh. Of course not. Fixed.

(Not sure what I was thinking, probably I thought I'm adjusting "first" and "last" pointers).


<!-- Sent from Reviewable.io -->

2021-01-18 11:23 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/shim_debug.c, line 85 at r1](https://reviewable.io/reviews/oscarlab/graphene/2099#-MRKBSq_6vUPBzENKWk4:-MRKE4yj2kKe8Je6ia2k:b32vhw) ([raw file](https://github.com/oscarlab/graphene/blob/3fa92763e49ab2eed8ea31d5c867e38b01e6db53/LibOS/shim/src/shim_debug.c#L85)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh. Of course not. Fixed.

(Not sure what I was thinking, probably I thought I'm adjusting "first" and "last" pointers).
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2021-01-18 13:28 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-19 20:35 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-19 20:43 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-01-19 20:48 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-01-19 21:08 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2099)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-19 23:22 UTC, merged