pal_loader: Print clearer error on invalid invocations
oscarlab/graphene pull request #2100
Opened 2021-01-18 17:28 UTC by mkow

## Description of the changes 

Previously (i.e.: before #2050), if the user used the old way of calling `pal_loader` they just got "Reading manifest failed" and that was all. Let's try to fix this.

I thought about moving this to PAL code, but the error handling on SGX currently doesn't allow for nice output formatting, and also this is just an UX improvement for the users of `pal_loader`, so I think it's fine to "pre-check" it on this layer.

## How to test this PR? 

Run `pal_loader` with invalid arguments (both in SGX and non-SGX mode).

2021-01-18 17:59 UTC, mkow commented
Jenkins, retest Jenkins-SGX-apps please (seems that SGX is broken on bobothebear node? CC: @woju)

2021-01-18 18:07 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-01-18 19:06 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[Runtime/pal_loader, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2100#-MRLsRVC-UKP3mB3ulaq:-MRLsRVC-UKP3mB3ular:binndtl) ([raw file](https://github.com/oscarlab/graphene/blob/d91b170ff8ae356390ff724d4a4f43266b28ee1f/Runtime/pal_loader#L126)):*
> ```
>     echo    "after appending corresponding extensions."
>     exit 1
> fi
> ```

All this should echo to stderr (`echo >&2`) and `exit 2`. Also the lines should be broken at 80 column as per standard terminal.


<!-- Sent from Reviewable.io -->

2021-01-18 19:07 UTC, woju reviewed
Do you have a link to a failed run log?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100#-:-MRLt3KrCmXplYQSiAQt:b-51gb5d)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-01-18 19:49 UTC, mkow reviewed
> Do you have a link to a failed run log?

I have, but you probably don't want it :) (I got it as a screenshot on email)

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100#-:-MRLtI-m4vhacDA6dLFL:b45wyg0)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Runtime/pal_loader, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2100#-MRLsRVC-UKP3mB3ulaq:-MRM0EKY9q1d2tPrg7nz:b311axj) ([raw file](https://github.com/oscarlab/graphene/blob/d91b170ff8ae356390ff724d4a4f43266b28ee1f/Runtime/pal_loader#L126)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

All this should echo to stderr (`echo >&2`) and `exit 2`. Also the lines should be broken at 80 column as per standard terminal.
</blockquote></details>

I used the same exit code as above in usage printing, fixed both.

I'm not sure about wrapping, why would we hardcode what's the width of user's terminal instead of relying on the terminal to do the wrapping? Also, it will look terrible if the user's terminal is narrower than 80.


<!-- Sent from Reviewable.io -->

2021-01-18 20:10 UTC, woju requested changes
From bobothebear?

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100#-:-MRM6dTu3trqUEy7mikp:b-cpi3wb)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Runtime/pal_loader, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2100#-MRLsRVC-UKP3mB3ulaq:-MRM5aIe9lnZMRxfPpa3:b-kfatr0) ([raw file](https://github.com/oscarlab/graphene/blob/d91b170ff8ae356390ff724d4a4f43266b28ee1f/Runtime/pal_loader#L126)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I used the same exit code as above in usage printing, fixed both.

I'm not sure about wrapping, why would we hardcode what's the width of user's terminal instead of relying on the terminal to do the wrapping? Also, it will look terrible if the user's terminal is narrower than 80.
</blockquote></details>

Because that's log, and logs get pasted in places like ```-blocks and those don't wrap lines on purpose. It's not a hard wrap, i.e. if you have something that can't be wrapped, like URL or filepath, obviously don't wrap at all. But what you've got here is prose, so no problem to wrap.

WRT terminals narrower than 80, well, the line has to be drawn somewhere.

Thx for exit 2.


<!-- Sent from Reviewable.io -->

2021-01-18 23:42 UTC, mkow reviewed
Ah, I though you're asking for a sample failure from the user's perspective ;)
That's the log: https://leeroy.cs.unc.edu/job/graphene-sgx-apps/2770/console

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100#-:-MRMnqSX4KP5XrRawXkR:b-7myqfv)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Runtime/pal_loader, line 126 at r1](https://reviewable.io/reviews/oscarlab/graphene/2100#-MRLsRVC-UKP3mB3ulaq:-MRMoC9O-YljvDfgLsMb:bhswb1n) ([raw file](https://github.com/oscarlab/graphene/blob/d91b170ff8ae356390ff724d4a4f43266b28ee1f/Runtime/pal_loader#L126)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because that's log, and logs get pasted in places like ```-blocks and those don't wrap lines on purpose. It's not a hard wrap, i.e. if you have something that can't be wrapped, like URL or filepath, obviously don't wrap at all. But what you've got here is prose, so no problem to wrap.

WRT terminals narrower than 80, well, the line has to be drawn somewhere.

Thx for exit 2.
</blockquote></details>

I wouldn't treat this as a log, this is an error message for user which incorrectly used Graphene manually - I don't think it's possible (or at least likely) to see this this in some logs, rather when playing with Graphene manually.
But OTOH, the argument with users pasting this in triple backticks is quite strong - it's likely we'll see this someday pasted in issues. So, I made the change, but I'm still in opposition to manual wrapping wherever possible (because I like to use weird widths of windows and such wrapping works badly with them, and after this change it started to look ugly on my terminal ;) ).


<!-- Sent from Reviewable.io -->

2021-01-19 07:38 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-01-19 15:09 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-19 15:26 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-01-19 15:38 UTC, mkow commented
Jenkins, retest Jenkins-SGX-apps please (uncledeadly node seems to have some issues, CC: @woju)

2021-01-19 15:42 UTC, woju approved these changes
```
+ make -j8 start-graphene-server
./pal_loader redis-server --save '' --protected-mode no
Initializing enclave failed: 1
load_enclave() failed with error -1
```

I see no other problems. System logs have nothing problematic.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2100#-:-MRQBdKU3RAaDYNk8_Uu:b-6qiwox)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-19 16:39 UTC, merged