[Pal,LibOS] Enable UBSAN via 'make UBSAN=1'
oscarlab/graphene pull request #2101
Opened 2021-01-19 21:31 UTC by stefanberger

## Description of the changes 

This PR enables a build with UBSAN enable by using 'make USBAN=1' as shown below. Some test cases that do not work under UBSAN are deactivated when USBAN is used. The regression tests on the PAL and LibOS level are passing now. LTP, however, has several failing tests.

## How to test this PR? 

```
make clean
make USBAN=1 DEBUG=1 -j32
pushd Pal/regression
make USBAN=1 DEBUG=1 regression -j32
popd
pushd LibOS/shim/test/regression
make USBAN=1 DEBUG=1 regression -j32
popd
```

2021-01-19 21:34 UTC, stefanberger reviewed
One concern is how to detect that the build was done with UBSAN. Maybe we should consider writing a file Runtime/.compilerflags and write 'ubsan' into it and have this file checked for when compiling and/or running test to skip skip tests. Other possibility may be to run `ldd Runtime/pal-Linux` to detect whether the it links to ubsan library.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101#-:-MRRYwK1BvxVtpFyuMKn:b-1ufsqn)* status: 0 of 16 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2021-01-20 07:39 UTC, dimakuv requested changes
Yes, I would also vote for having a special file like `Runtime/.compilerflags` to now how exactly Graphene was built.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101#-:-MRTiT7TAlBMQiBdmVie:bgtpcf1)* status: 0 of 16 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTi_d298q9GMDEyNOs:-MRTi_d298q9GMDEyNOt:b-9w1eyq) (no related file):*
Could @woju take a look at this?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTidMw145-fDT-CnER:-MRTidMw145-fDT-CnES:bc27oc) (no related file):*
This is a cool PR, but I'd like to de-prioritize it for now... At least until we finish the "big signal rewrite" PRs.

---
___
*[Scripts/Makefile.configs, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRThnm15jd3mFDdOm2l:-MRThnm15jd3mFDdOm2m:btt9i7n) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/Scripts/Makefile.configs#L75)):*
> ```
> CFLAGS += -fsanitize=undefined -fno-omit-frame-pointer -fno-sanitize-recover
> CXXFLAGS += -fsanitize=undefined -fno-omit-frame-pointer -fno-sanitize-recover
> UBSAN_LDFLAGS = -L/usr/$(ARCH_LIBDIR) -lubsan
> ```

Is it supposed to be installed on the system? Is it in a default GCC/Ubuntu (or whatever OS distro you use) installation?

If it must be installed explicitly, it should be mentioned in our Documentation and in our `.ci/` directory for Jenkins.


<!-- Sent from Reviewable.io -->

2021-01-20 07:39 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 0 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[LibOS/shim/test/regression/argv_from_file.manifest.template, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTixkt-92gNkJHnr05:-MRTixkuD514CEYlrR_5:b-tt7duy) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/argv_from_file.manifest.template#L15)):*
> ```
> fs.mount.host_usr_lib.type = "chroot"
> fs.mount.host_usr_lib.path = "/usr/$(ARCH_LIBDIR)"
> fs.mount.host_usr_lib.uri = "file:/usr/$(ARCH_LIBDIR)"
> ```

Not amazingly happy with this... Maybe we should create a symlink `Runtime/libubsan.so` during Graphene build?


<!-- Sent from Reviewable.io -->

2021-01-20 12:12 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 0 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @stefanberger, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTi_d298q9GMDEyNOs:-MRUhNeNCCVdJ3FNBqEY:bwf0qk4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could @woju take a look at this?
</blockquote></details>

Sure...

---
___
*[Scripts/Makefile.configs, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRThnm15jd3mFDdOm2l:-MRUfBrw4E-wrCYr4FaO:bscuts7) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/Scripts/Makefile.configs#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is it supposed to be installed on the system? Is it in a default GCC/Ubuntu (or whatever OS distro you use) installation?

If it must be installed explicitly, it should be mentioned in our Documentation and in our `.ci/` directory for Jenkins.
</blockquote></details>

Yes. Fedora 32 has it and it installs here:
```
lrwxrwxrwx. 1 root root 24 Jan 13 18:12 /usr/lib64/libubsan.so -> /usr/lib64/libubsan.so.1
```

On Ubuntu 18.04 I had to create the .so symlink myself for it to link (packaging error?)
```
lrwxrwxrwx 1 root root 13 Jan 19 15:41 /usr/lib/powerpc64le-linux-gnu/libubsan.so -> libubsan.so.0
```

The location corresponds to `/usr/$(ARCH_LIBDIR)` on these two. With this we should be able to copy `libubsan.so.*.*.*` into the Runtime dir, or at least link to it.

I will add the documentation then.
___
*[LibOS/shim/test/regression/argv_from_file.manifest.template, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTixkt-92gNkJHnr05:-MRUgJIY2VcmPXlyu6vf:bh68v81) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/argv_from_file.manifest.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not amazingly happy with this... Maybe we should create a symlink `Runtime/libubsan.so` during Graphene build?
</blockquote></details>

Yes, that's a possibility.


<!-- Sent from Reviewable.io -->

2021-01-20 19:05 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 0 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTi_d298q9GMDEyNOs:-MRWAjgn1y8QXIW4SoJK:b-n1u40) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Sure...
</blockquote></details>

... any help would be appreciated, especially with SGX, which I don't try at all.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTidMw145-fDT-CnER:-MRWArG96bYWLJfPUcoI:b2nhb2c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a cool PR, but I'd like to de-prioritize it for now... At least until we finish the "big signal rewrite" PRs.
</blockquote></details>

Ack

---


<!-- Sent from Reviewable.io -->

2021-01-27 12:15 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 0 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[Scripts/Makefile.configs, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRThnm15jd3mFDdOm2l:-MS2l4zH32HklrZzldBn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/Scripts/Makefile.configs#L75)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Yes. Fedora 32 has it and it installs here:
```
lrwxrwxrwx. 1 root root 24 Jan 13 18:12 /usr/lib64/libubsan.so -> /usr/lib64/libubsan.so.1
```

On Ubuntu 18.04 I had to create the .so symlink myself for it to link (packaging error?)
```
lrwxrwxrwx 1 root root 13 Jan 19 15:41 /usr/lib/powerpc64le-linux-gnu/libubsan.so -> libubsan.so.0
```

The location corresponds to `/usr/$(ARCH_LIBDIR)` on these two. With this we should be able to copy `libubsan.so.*.*.*` into the Runtime dir, or at least link to it.

I will add the documentation then.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/argv_from_file.manifest.template, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTixkt-92gNkJHnr05:-MS2kye2B_g2-lm_4yAv:bvet1vw) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/argv_from_file.manifest.template#L15)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Yes, that's a possibility.
</blockquote></details>

Copying that now in a new script and removed all these manifest changes. Since there were so many changes I just squashed the stuff together.


<!-- Sent from Reviewable.io -->

2021-01-27 12:15 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 0 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[LibOS/shim/test/regression/argv_from_file.manifest.template, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTixkt-92gNkJHnr05:-MS2lKWeAR1iSBvXLR9S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/argv_from_file.manifest.template#L15)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Copying that now in a new script and removed all these manifest changes. Since there were so many changes I just squashed the stuff together.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-27 12:17 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 0 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[Scripts/compiler-option, line 96 at r2](https://reviewable.io/reviews/oscarlab/graphene/2101#-MS2lYlQAkvYkc-J1KGy:-MS2lYlQAkvYkc-J1KGz:b-8y7x9w) ([raw file](https://github.com/oscarlab/graphene/blob/01aacde224f5c6022267ffb97d449ecc229367bd/Scripts/compiler-option#L96)):*
> ```
> 		case "$enable" in
> 		ubsan) enable_ubsan "${runtimedir}" "${libdir}";;
> 		*) echo "Unsupported feature $enable." >&2; exit 1;;
> ```

will change this to option and also below.


<!-- Sent from Reviewable.io -->

2021-01-28 10:08 UTC, dimakuv requested changes
> Reviewed 3 of 16 files at r1, 7 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 9 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @stefanberger, and @woju)

___
*[Scripts/compiler-option, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2101#-MS7SUgJ3Bk9BW9qJaWi:-MS7SUgK-pzf5ggnjNVv:bdhfgy7) ([raw file](https://github.com/oscarlab/graphene/blob/01aacde224f5c6022267ffb97d449ecc229367bd/Scripts/compiler-option#L1)):*
> ```
> #!/usr/bin/env bash
> ```

This script is called `compiler-option` but in some other places you have `compiler-options` (with an `s` at the end). I like the latter version, could you rename this script and all its invocations?


<!-- Sent from Reviewable.io -->

2021-01-28 12:48 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 8 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Scripts/compiler-option, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2101#-MS7SUgJ3Bk9BW9qJaWi:-MS80rvoCfEp86Hb7Rjr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/01aacde224f5c6022267ffb97d449ecc229367bd/Scripts/compiler-option#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This script is called `compiler-option` but in some other places you have `compiler-options` (with an `s` at the end). I like the latter version, could you rename this script and all its invocations?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-30 00:14 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 5 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTidMw145-fDT-CnER:-MSFchPPCF0RDRb3LA5K:b-7enp0x) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Ack
</blockquote></details>

I now fixed issues related to sysfs implementation and made that the 1st patch. I squashed all the fixups into the 2nd patch and modified the script a bit to take a command (enable-ubsan, is-ubsan-enabled) as the first parameter before all options. It now passed PAL and LibOS regression tests and LTP tests.

---


<!-- Sent from Reviewable.io -->

2021-03-22 15:39 UTC, woju requested changes
> Reviewed 1 of 16 files at r1, 3 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 7 of 12 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRTi_d298q9GMDEyNOs:-MRzjMjj1durz6K5DUTW:bvkj4uu) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

... any help would be appreciated, especially with SGX, which I don't try at all.
</blockquote></details>

Well, I'm no fan, but if this will be rewritten to meson, I don't object.

---
___
*[LibOS/shim/test/regression/test_libos.py, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRiKNXVDWlYWSlp3Ss9:-MRiKNXX9ScxWBp_sStk:b107t2d) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/test_libos.py#L105)):*
> ```Python
>     def test_110_basic_bootstrapping_cpp(self):
>         if not os.path.exists('bootstrap_cpp'):
>             return
> ```

`self.skipTest()` https://docs.python.org/3/library/unittest.html#unittest.TestCase.skipTest

Just returning reports the test as passed, which is wrong.
___
*[LibOS/shim/test/regression/test_libos.py, line 628 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRiKiuwDlhjVcOfF1a9:-MRiKiuwDlhjVcOfF1aA:b-b08rqx) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/test_libos.py#L628)):*
> ```Python
>         # enclave, instead of including eclave entry.
>         if not os.path.exists('debug'):
>             return
> ```

`self.skipTest()`
___
*[LibOS/shim/test/regression/test_libos.py, line 657 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRiKl651LErIwMuhyUR:-MRiKl66DpzUEniU2y0E:b-b08rqx) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/test_libos.py#L657)):*
> ```Python
>         # GDB=1 GDB_SCRIPT=debug_regs-x86_64.gdb ./pal_loader debug_regs-x86_64
>         if not os.path.exists('debug_regs-x86_64'):
>             return
> ```

`self.skipTest()`
___
*[Scripts/Makefile.configs, line 76 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWP_1UN35r07kJ4FCph:-MWP_1UO1NtJCpXhR3cy:b-lfr9z0) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/Makefile.configs#L76)):*
> ```
> IS_UBSAN_ENABLED = $(shell $(MAKEFILE_CONFIGS_DIR)/compiler-options is-ubsan-enabled --runtimedir $(RUNTIME))
> ifneq ($(IS_UBSAN_ENABLED),1)
> ifeq ($(UBSAN),1)
> ```

If I'm reading this correctly, it's possible to enable this, but not disable. Moreover this can be done exactly once. So if you do this:
```sh
make UBSAN=1
make SGX=1
```
Then Linux-SGX also gets built with IS_UBSAN_ENABLED=1.

This will certainly cause confusion.
___
*[Scripts/Makefile.configs, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPZt-L6qUOgbmarfeD:-MWPZt-N0j4EvRzSO16d:b-sqn2y0) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/Makefile.configs#L79)):*
> ```
> $(info Enabling UBSAN)
> $(shell $(MAKEFILE_CONFIGS_DIR)/compiler-options enable-ubsan --runtimedir $(RUNTIME) --libdir "/usr/$(ARCH_LIBDIR)")
> #$(info $(RES))
> ```

Is this comment needed?
___
*[Scripts/compiler-options, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPYb9H-7pMkFVNm8vp:-MWPYb9H-7pMkFVNm8vq:b-r2825b) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/compiler-options#L36)):*
> ```
> 		src="$(ldd ${libubsan} | grep ${dep} | gawk '{print $3}')"
> 		cp "${src}" "${runtimedir}/$(basename "${src}")"
> 	done
> ```

I don't understand why all this is copied to `Runtime`. Shouldn't this be included in app's manifest instead?


<!-- Sent from Reviewable.io -->

2021-03-22 15:42 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 7 of 12 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @stefanberger)

___
*[Scripts/compiler-options, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPaCiIEgdMXLiAohYA:-MWPaCiJ4b2wbHrfbYWI:b-1spym6) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/compiler-options#L10)):*
> ```
> 
> 	local out src
> 	local libubsan="${libdir}/libubsan.so"
> ```

Is this the correct filename? https://packages.debian.org/buster/amd64/libubsan1/filelist says `libubsan.so.1` and I don't have reference for an RPM package handy.


<!-- Sent from Reviewable.io -->

2021-03-23 02:52 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 7 of 12 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[LibOS/shim/test/regression/test_libos.py, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRiKNXVDWlYWSlp3Ss9:-MWRxTvY0XT02fz1YBbJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/test_libos.py#L105)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`self.skipTest()` https://docs.python.org/3/library/unittest.html#unittest.TestCase.skipTest

Just returning reports the test as passed, which is wrong.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 628 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRiKiuwDlhjVcOfF1a9:-MWRxUze269I5SqO1IBX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/test_libos.py#L628)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`self.skipTest()`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 657 at r1](https://reviewable.io/reviews/oscarlab/graphene/2101#-MRiKl651LErIwMuhyUR:-MWRxVII4epTzz-wPloG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61939ce222de87dc889a55545b6578369276c3f1/LibOS/shim/test/regression/test_libos.py#L657)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`self.skipTest()`
</blockquote></details>

Done.
___
*[Scripts/Makefile.configs, line 76 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWP_1UN35r07kJ4FCph:-MWRyLIQAO45kNq7mdQ1:b-uc46sp) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/Makefile.configs#L76)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If I'm reading this correctly, it's possible to enable this, but not disable. Moreover this can be done exactly once. So if you do this:
```sh
make UBSAN=1
make SGX=1
```
Then Linux-SGX also gets built with IS_UBSAN_ENABLED=1.

This will certainly cause confusion.
</blockquote></details>

To get rid of UBSAN you would have to do a `make clean`. Wouldn't you expect to build SGX with UBSAN enabled in this case? It is done this way so that we don't always have to pass UBSAN=1 on the command line if we make changes to the code and want to build again with UBSAN enabled. I at least found it better that UBSAN=1 persists until the next `make clean`.
___
*[Scripts/Makefile.configs, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPZt-L6qUOgbmarfeD:-MWRyfmz67wu_JsoP_OC:b-z8v68c) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/Makefile.configs#L79)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Is this comment needed?
</blockquote></details>

Was for debugging purposes.
___
*[Scripts/compiler-options, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPaCiIEgdMXLiAohYA:-MWRxdEW0RyAMrfG4lls:b9kodk) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/compiler-options#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Is this the correct filename? https://packages.debian.org/buster/amd64/libubsan1/filelist says `libubsan.so.1` and I don't have reference for an RPM package handy.
</blockquote></details>

This would have to change anyway since the build now prints out this here:

```
make[3]: Leaving directory '/home/stefanb/tmp/graphene/Pal/src/host/Linux'
  [ host/Linux/libpal.so ]
  [ host/Linux/libpal.a ]
Error: host/Linux/libpal.so should not be dynamically linked
```

I had tried to make it link statically a while ago wit libubsan.a but couldn't get it to do so...

```
 rpm -q --list libubsan-static
/usr/lib/gcc
/usr/lib/gcc/x86_64-redhat-linux
/usr/lib/gcc/x86_64-redhat-linux/10
/usr/lib/gcc/x86_64-redhat-linux/10/libubsan.a
/usr/share/doc/libubsan-static
/usr/share/doc/libubsan-static/ChangeLog.bz2
/usr/share/licenses/libubsan-static
/usr/share/licenses/libubsan-static/LICENSE.TXT
```
___
*[Scripts/compiler-options, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPYb9H-7pMkFVNm8vp:-MWRxpMU7mfAaKj5o75d:b-bjqxdw) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/compiler-options#L36)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't understand why all this is copied to `Runtime`. Shouldn't this be included in app's manifest instead?
</blockquote></details>

These were dependencies of libubsan itself that needed to be made available. Probably they should also be explicitly enumerated in every manifest but if we get static linking with libubsan.a to work this would not be needed anymore.


<!-- Sent from Reviewable.io -->

2021-03-24 17:46 UTC, woju requested changes
> Reviewed 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 6 of 12 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @stefanberger, and @woju)

___
*[Scripts/Makefile.configs, line 76 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWP_1UN35r07kJ4FCph:-MW_In4u2tB9EtLkG6vm:b-e24fzy) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/Makefile.configs#L76)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

To get rid of UBSAN you would have to do a `make clean`. Wouldn't you expect to build SGX with UBSAN enabled in this case? It is done this way so that we don't always have to pass UBSAN=1 on the command line if we make changes to the code and want to build again with UBSAN enabled. I at least found it better that UBSAN=1 persists until the next `make clean`.
</blockquote></details>

For this case, yes, I would expect the second (SGX) build to be without UBSAN. For example, if you build linux kernel, you're expected to pass `ARCH=` every time, and if you don't it's get reset to autodetected.

(TBH I don't have a good answer here. Most build systems have `./configure` (or equivalent) distinct from `make`, for us it's a mixed bag and unholy mess.)
___
*[Scripts/Makefile.configs, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPZt-L6qUOgbmarfeD:-MW_K4nd1jQsBdoAl4Vp:b-q7h6ba) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/Makefile.configs#L79)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Was for debugging purposes.
</blockquote></details>

OK, so please either remove, or uncomment and have it under some sort of VERBOSE/DEBUG/whatever you think would be ok.


<!-- Sent from Reviewable.io -->

2021-03-24 17:52 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2101)* status: 6 of 12 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @stefanberger, and @woju)

___
*[Scripts/compiler-options, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2101#-MWPaCiIEgdMXLiAohYA:-MW_MIae-xqsOXNrvj7d:bnr0fgd) ([raw file](https://github.com/oscarlab/graphene/blob/38ed52ed1ba23cef085dac52177858a55ba510eb/Scripts/compiler-options#L10)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

This would have to change anyway since the build now prints out this here:

```
make[3]: Leaving directory '/home/stefanb/tmp/graphene/Pal/src/host/Linux'
  [ host/Linux/libpal.so ]
  [ host/Linux/libpal.a ]
Error: host/Linux/libpal.so should not be dynamically linked
```

I had tried to make it link statically a while ago wit libubsan.a but couldn't get it to do so...

```
 rpm -q --list libubsan-static
/usr/lib/gcc
/usr/lib/gcc/x86_64-redhat-linux
/usr/lib/gcc/x86_64-redhat-linux/10
/usr/lib/gcc/x86_64-redhat-linux/10/libubsan.a
/usr/share/doc/libubsan-static
/usr/share/doc/libubsan-static/ChangeLog.bz2
/usr/share/licenses/libubsan-static
/usr/share/licenses/libubsan-static/LICENSE.TXT
```
</blockquote></details>

Until I find time to get this to link statically, if that will work at all,  this PR is frozen.


<!-- Sent from Reviewable.io -->

2021-08-28 10:07 UTC, closed without merging