[LibOS] Align char msg[] in shim_ipc_msg to 8-bytes (UBSAN)
oscarlab/graphene pull request #2103
Opened 2021-01-19 23:23 UTC by stefanberger

## Description of the changes 

The msg field of 'struct shim_ipc_msg' will for example be cast to
'struct shim_ipc_sysv_tellkey*' (in ipc_sysv_tellkey_callback()) and
needs to be properly aligned. There are also casts to other ipc
related structures that also require alignment.

2021-01-20 00:06 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[LibOS/shim/include/shim_ipc.h, line 104 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS4sU86I2IheWIRCgr:-MRS4sU86I2IheWIRCgs:b-1afmi7) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L104)):*
> ```objc
>     IDTYPE src, dst;
>     unsigned long seq;
>     /* msg must for example be aligned to struct shim_ipc_sysv_tellkey */
> ```

`msg must for example be aligned to struct shim_ipc_sysv_tellkey` -> `msg is used to store and read various structures, we need to ensure its proper alignment`
___
*[LibOS/shim/include/shim_ipc.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS55i9EjlZcsvQnfYG:-MRS55i9EjlZcsvQnfYH:bcalozi) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L105)):*
> ```objc
>     unsigned long seq;
>     /* msg must for example be aligned to struct shim_ipc_sysv_tellkey */
>     char msg[] __attribute__((aligned(alignof(8))));
> ```

Please change `8` to `16`, I'll feel safer then (but this thing will need to be rewritten anyways, the IPC code is terribly hacky).
___
*[LibOS/shim/include/shim_ipc.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS5bg0CZ0V6ea39phA:-MRS5bg0CZ0V6ea39phB:b4jx30z) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L105)):*
> ```
> __attribute__((aligned(alignof(8))))
> ```

This doesn't work as you think - `alignof(8)` first calculates alignment of `8`, which is an `int`, so it equals 4, and then you get `__attribute__((aligned(4)))` attribute.


<!-- Sent from Reviewable.io -->

2021-01-20 00:50 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @stefanberger)

___
*[LibOS/shim/include/shim_ipc.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS55i9EjlZcsvQnfYG:-MRSFQ8Z086KrMmbi0-d:b-69s19s) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change `8` to `16`, I'll feel safer then (but this thing will need to be rewritten anyways, the IPC code is terribly hacky).
</blockquote></details>

I re-tested this and this align statement doesn't seem to work. I removed the 'packed' attribute.
___
*[LibOS/shim/include/shim_ipc.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS5bg0CZ0V6ea39phA:-MRSFvOj5b4NWnY0gPAH:b643qro) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L105)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> __attribute__((aligned(alignof(8))))
> ```

This doesn't work as you think - `alignof(8)` first calculates alignment of `8`, which is an `int`, so it equals 4, and then you get `__attribute__((aligned(4)))` attribute.
</blockquote></details>

Yes, I had tried with alignment of that structure but ended up replacing align(struct ...) with align(8).
With this and the other UBSAN PR fixes applied, LTP now passes as well.


<!-- Sent from Reviewable.io -->

2021-01-20 00:51 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 104 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS4sU86I2IheWIRCgr:-MRSGgO3BMDHdoRYXnxm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`msg must for example be aligned to struct shim_ipc_sysv_tellkey` -> `msg is used to store and read various structures, we need to ensure its proper alignment`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS5bg0CZ0V6ea39phA:-MRSGbUn0OuSCNQZdbjq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L105)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Yes, I had tried with alignment of that structure but ended up replacing align(struct ...) with align(8).
With this and the other UBSAN PR fixes applied, LTP now passes as well.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS55i9EjlZcsvQnfYG:-MRSGegb0ywkHfFnpg5o:bg0tm9k) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L105)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I re-tested this and this align statement doesn't seem to work. I removed the 'packed' attribute.
</blockquote></details>

My bad.


<!-- Sent from Reviewable.io -->

2021-01-20 00:52 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 105 at r1](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRS55i9EjlZcsvQnfYG:-MRSGh_B2wlyiwfC8bUo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/919ba7d168cf1cbe5978edd03ad295c5dddd24fa/LibOS/shim/include/shim_ipc.h#L105)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

My bad.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-20 02:05 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-01-20 08:12 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-01-20 08:12 UTC, dimakuv commented
Jenkins, test this please

2021-01-20 19:59 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-20 22:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: all files reviewed, 1 unresolved discussion (waiting on @stefanberger)

___
*[LibOS/shim/include/shim_ipc.h, line 104 at r2](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRWzD_f0F9dMkJDlMG1:-MRWzD_f0F9dMkJDlMG2:b-731xvk) ([raw file](https://github.com/oscarlab/graphene/blob/324e9b3d16b0e555525b6a1a5c5a4a3b44ade03a/LibOS/shim/include/shim_ipc.h#L104)):*
> ```objc
>     IDTYPE src, dst;
>     unsigned long seq;
>     /* msg is used to store and read various structures, we need to ensure its proper alignment */
> ```

Could you add a comment stating this is a temporary workaround?
We should rewrite the IPC at last ....


<!-- Sent from Reviewable.io -->

2021-01-20 22:53 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 104 at r2](https://reviewable.io/reviews/oscarlab/graphene/2103#-MRWzD_f0F9dMkJDlMG1:-MRX-46UDZyJyujWL5cv:b-48xzsv) ([raw file](https://github.com/oscarlab/graphene/blob/324e9b3d16b0e555525b6a1a5c5a4a3b44ade03a/LibOS/shim/include/shim_ipc.h#L104)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you add a comment stating this is a temporary workaround?
We should rewrite the IPC at last ....
</blockquote></details>

will do with the rebase


<!-- Sent from Reviewable.io -->

2021-01-20 23:01 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-01-20 23:01 UTC, mkow commented
Jenkins, retest this please

2021-01-20 23:02 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-01-21 01:27 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2103)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-21 01:41 UTC, merged