[Pal/Linux-SGX] Fix GDB integration for some binaries
oscarlab/graphene pull request #2111
Opened 2021-01-21 16:28 UTC by pwmarcz

The _DkDebugMapAdd function looked for executable program segments
and reported them using ocall_report_mmap(). Unfortunately, the
code incorrectly assumed the ELF header is located at load address
and not start of the map, which is not true for some binaries
(e.g. Ubuntu build of Python), and segfaulted on these binaries.

Because the information about the segments is only important for
SGX profiling, this change simplifies things by removing
the ocall_report_mmap() path and parsing the ELF file in the SGX
subsystem itself.

## Why this way?

Having this code directly in `_DkDebugAddMap` was already kind of a hack. We could avoid re-parsing the ELF file by hooking all the places that do the actual mapping, but that's not a very good solution: there is PAL rtld, LibOS rtld, and also the application ld.so. We already collect information about mapping a new executable from all these places, so it's far easier to process the executable segments in one place (`sgx_profile.c`).

## How to test this PR? 

Compile with DEBUG=1, run the `python-simple` example. It should crash on master (segfault inside `_DkDebugAddMap) and work on this branch.

(I didn't check if it crashes under Ubuntu 18, but verified it under Ubuntu 20).

2021-01-21 19:31 UTC, yamahata submitted a review, later dismissed
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-22 02:43 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 299 at r1](https://reviewable.io/reviews/oscarlab/graphene/2111#-MRbyIpl9SIyPuIs3vfG:-MRbyIpl9SIyPuIs3vfH:boice7o) ([raw file](https://github.com/oscarlab/graphene/blob/15b331a67c8e588d576d53849e68df8dce854df1/Pal/src/host/Linux-SGX/sgx_profile.c#L299)):*
> ```C
>     }
> 
>     void* elf_addr = (void*)INLINE_SYSCALL(mmap, 6, NULL, elf_length, PROT_READ, MAP_SHARED, fd, 0);
> ```

Out of curiosity: Why `MAP_SHARED` here?


<!-- Sent from Reviewable.io -->

2021-01-22 10:02 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 299 at r1](https://reviewable.io/reviews/oscarlab/graphene/2111#-MRbyIpl9SIyPuIs3vfG:-MRdWKbO2UYS8AT0dgxn:bn9uz4w) ([raw file](https://github.com/oscarlab/graphene/blob/15b331a67c8e588d576d53849e68df8dce854df1/Pal/src/host/Linux-SGX/sgx_profile.c#L299)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Out of curiosity: Why `MAP_SHARED` here?
</blockquote></details>

I think I copied it from previous version of debug map code :)

I don't think it changes much if we just want to read the file, and the map is read only? But `MAP_PRIVATE` sounds like a better default. Updated.


<!-- Sent from Reviewable.io -->

2021-01-22 14:18 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2111#-MReSEbH8kquSFRNrQ_t:-MReSEbH8kquSFRNrQ_u:b-aocxog) (no related file):*
As discussed on priv, blocking on the following issue: The paths inside Graphene may be different than on the host, and sometimes even inaccessible (e.g. in case of protected files). We need to handle this reverse translation somehow.

---
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 299 at r1](https://reviewable.io/reviews/oscarlab/graphene/2111#-MRbyIpl9SIyPuIs3vfG:-MReOfZCEIW4ZptGBgcc:b-1xboei) ([raw file](https://github.com/oscarlab/graphene/blob/15b331a67c8e588d576d53849e68df8dce854df1/Pal/src/host/Linux-SGX/sgx_profile.c#L299)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think I copied it from previous version of debug map code :)

I don't think it changes much if we just want to read the file, and the map is read only? But `MAP_PRIVATE` sounds like a better default. Updated.
</blockquote></details>

Yeah, I think it doesn't matter and should work basically the same, but I was just curious whether there's maybe some reason for it which I don't know ;)


<!-- Sent from Reviewable.io -->

2021-01-22 14:49 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2111#-MReSEbH8kquSFRNrQ_t:-MReZTFz5-fTYzs6Gj6Q:b-y9uplw) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

As discussed on priv, blocking on the following issue: The paths inside Graphene may be different than on the host, and sometimes even inaccessible (e.g. in case of protected files). We need to handle this reverse translation somehow.
</blockquote></details>

Isn't this issue unrelated to this PR?

I mean, the issue was already there (on master). Shouldn't we continue with this merging PR and fixing the issue in a separate PR? 

---


<!-- Sent from Reviewable.io -->

2021-01-22 14:56 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2111#-MReSEbH8kquSFRNrQ_t:-MRe_nfh8j8KxFeOTWYb:b-rii93c) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't this issue unrelated to this PR?

I mean, the issue was already there (on master). Shouldn't we continue with this merging PR and fixing the issue in a separate PR? 
</blockquote></details>

I thought it was introduced here (by moving the code from inside to the untrusted world), but I had a chat with Paweł and it actually works - the paths received there are already after mount-reverse-translation, so it should be fine.

a.d. PF it was already broken, so Paweł will just add a comment and we'll fix it later.

---


<!-- Sent from Reviewable.io -->

2021-01-22 15:21 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: 7 of 9 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2111#-MReSEbH8kquSFRNrQ_t:-MRefDja0Fqb-cTc-nPc:b-kd7bw0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I thought it was introduced here (by moving the code from inside to the untrusted world), but I had a chat with Paweł and it actually works - the paths received there are already after mount-reverse-translation, so it should be fine.

a.d. PF it was already broken, so Paweł will just add a comment and we'll fix it later.
</blockquote></details>

Right. As explained in comment, I don't think it's worth it to add another workaround for PF. 

However, I added a sanity check (ELF magic number) to the code that parses the ELF, to prevent it from crashing someday when somebody feeds it an encrypted file.

---


<!-- Sent from Reviewable.io -->

2021-01-22 15:35 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-22 17:10 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-01-22 17:46 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-01-22 22:01 UTC, mkow commented
Jenkins, retest Jenkins-18.04 please (network issues on slave-leeroy?)

2021-01-22 23:59 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2111)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-23 00:49 UTC, merged