[GSC] Refactor GSC and make it work again
oscarlab/graphene pull request #2112
Opened 2021-01-21 16:44 UTC by dimakuv

## Description of the changes 

Commit "Introduce one, central manifest, zero-config children and constant MRENCLAVE" broke GSC. This commit fixes GSC (mainly adjusts it the single-manifest change in that commit). Also, significant internal refactoring is done (no user-visible changes).

## How to test this PR? 

If someone re-enables the GSC pipeline in Jenkins, then it should pass. Alternatively, just do the tests manually.

2021-01-21 16:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: 0 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2112#-MR_pSW_23zu9Re9A7Sb:-MR_pSWaCKebwHH4VqZ1:b-hyj6ru) (no related file):*
Summoning @vahldiek for a quick review, just to have an ack from him.

---


<!-- Sent from Reviewable.io -->

2021-01-21 17:13 UTC, vahldiek reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: 0 of 20 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2112#-MR_pSW_23zu9Re9A7Sb:-MR_sY5e0FakJX54h-Kb:b-1jtwzu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Summoning @vahldiek for a quick review, just to have an ack from him.
</blockquote></details>

look good to me

---


<!-- Sent from Reviewable.io -->

2021-01-22 15:01 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (internet connectivity)

2021-01-22 15:20 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (internet connectivity)

2021-01-25 09:32 UTC, dimakuv commented
Jenkins, retest Jenkins please (internet connectivity)

2021-01-25 13:45 UTC, dimakuv commented
Jenkins, test Jenkins-SGX-gsc please

2021-01-25 19:01 UTC, woju commented
Jenkins, test Jenkins-SGX-gsc please

2021-01-25 19:08 UTC, woju commented
Jenkins, test Jenkins-SGX-gsc please

2021-01-31 19:24 UTC, mkow requested changes
> Reviewed 18 of 20 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 60 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS98D8S5J80sdbZr9CS:-MS98D8S5J80sdbZr9CT:br79vst) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L60)):*
> ```reStructuredText
> - `Intel SGX driver <https://github.com/intel/linux-sgx-driver>`__
> - `Intel SGX SDK <https://01.org/intel-software-guard-extensions/downloads>`__
> - `Graphene SGX Driver (kernel module) <https://github.com/oscarlab/graphene-sgx-driver>`__
> ```

we should drop this and ask to use a kernel with fsgsbase
___
*[Documentation/manpages/gsc.rst, line 70 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS98eHZDFz3p6WNyKNX:-MS98eHZDFz3p6WNyKNY:bchyvss) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L70)):*
> ```
>    You could also run commands as root.
> ```

I'd drop this sentence, the whole warning sounds really weird with it.
___
*[Documentation/manpages/gsc.rst, line 114 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS99J5w9A3S6sybZEo5:-MS99J5w9A3S6sybZEo6:bf461s5) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L114)):*
> ```reStructuredText
>    any arguments specified during :command:`docker run` are ignored.
> 
> .. option:: -nc
> ```

shouldn't this be `--`, not `-`?
___
*[Documentation/manpages/gsc.rst, line 149 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS99cdyCUPfrq0AaAtD:-MS99cdyCUPfrq0AaAtE:b8mqsp1) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L149)):*
> ```reStructuredText
> Docker image called ``gsc-<IMAGE-NAME>``. :command:`gsc sign-image` always
> removes intermediate Docker images, if successful or not, to ensure the removal
> of the signing key in intermediate Docker images.
> ```

`in intermediate Docker images` -> `in them` (repetition)
___
*[Documentation/manpages/gsc.rst, line 238 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9ApzQE7oG5H1ZEw-t:-MS9ApzQE7oG5H1ZEw-u:bbwbk6k) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L238)):*
> ```
> Similarly to Docker, Graphene has a corresponding option (``libos.entrypoint``) [...]
> ```

Not sure if this whole sentence is actually needed, seems the users doesn't need to know about manifests?
___
*[Documentation/manpages/gsc.rst, line 269 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9BklhBZwKYolDadt8:-MS9BklhBZwKYolDadt9:bs71oh1) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L269)):*
> ```reStructuredText
>    SGX token and starts the :program:`pal-Linux-SGX` loader. Note that the
>    generated image (``gsc-<image-name>-unsigned``) cannot successfully load an
>    Intel SGX enclave, since essential files and the signing of the enclave are
> ```

`signing of the enclave` -> `signature of the enclave`
___
*[Documentation/manpages/gsc.rst, line 281 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9CCWPEwVWwpc91WjK:-MS9CCWPEwVWwpc91WjL:b-gfhohg) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L281)):*
> ```
> Note that prebuilt Graphene images will be provided for popular cloud-provider
> offerings or can be created via :command:`gsc build-graphene`.
> ```

`Note that` -> `In the future we plan to provide [...]`
___
*[Documentation/manpages/gsc.rst, line 434 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9Egs7CRmnDsX89d-T:-MS9Egs7CRmnDsX89d-U:b7mdbho) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L434)):*
> ```reStructuredText
>    .. code-block:: sh
> 
>       docker run --device=/dev/gsgx --device=/dev/sgx/enclave \
> ```

` SGXDriver.Repository` default value is pointing to the old OOT (and basically most of this guide is pointing to it).
___
*[Tools/gsc/finalize_manifest.py, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSJJ3PTDq5kad2Wwx6z:-MSJJ3PTDq5kad2Wwx7-:b-707tol) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/finalize_manifest.py#L42)):*
> ```Python
>             if exclude_re.match(filename) or not os.path.isfile(filename):
>                 continue
>             if not is_ascii(filename):
> ```

that's not enough, there are still names which will break the generation, e.g. `asdf"qwer`. Not sure about newlines, we'd need to verify with tomlc99.
___
*[Tools/gsc/gsc.py, line 254 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOtHN62wWgKRUUCb6F:-MSOtHN62wWgKRUUCb6G:bnk2j3w) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/gsc.py#L254)):*
> ```Python
> 
>     try:
>         # forcerm parameter forces removal of intermediate Docker images even after unsuccessful
> ```

please wrap `forcerm` with backticks, looked like a typo for me at first ;)
___
*[Tools/gsc/templates/entrypoint.manifest.template, line 20 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOoPejDagTTcj4FPZM:-MSOoPek3rGwS4pa8tkV:b-e3w6cd) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/templates/entrypoint.manifest.template#L20)):*
> ```
> # !! INSECURE !! Allow passing command-line arguments from the host without validation.
> # Most Docker images rely on runtime arguments and hence, a more general technique is required.
> # The issue is documented for future release of GSC in issue #1520.
> ```

Please link to the issue, the numbers may change if we migrate the Graphene repo or GSC.


<!-- Sent from Reviewable.io -->

2021-01-31 19:30 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOuMBL7QN_8cwj2dW4:-MSOuMBL7QN_8cwj2dW5:b-10r070) (no related file):*
Waaait, what's that thing in the Jenkins log, of that successful run?

```
make[1]: Entering directory '/home/jenkins/workspace/graphene-sgx-gsc/Tools/gsc/test'
echo "Building base image ubuntu18.04-python3.dockerfile..."
Building base image ubuntu18.04-python3.dockerfile...
docker build --rm --no-cache -t ubuntu18.04-python3-a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f -f ubuntu18.04-python3.dockerfile ../../../Examples
free(): invalid pointer
SIGABRT: abort
PC=0x7fde76fa4fb7 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42005fcc0, 0xc42005fce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42005fc90 sp=0xc42005fc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0xa16270)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42005fcc0 sp=0xc42005fc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0xa16270)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42005fcf8 sp=0xc42005fcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200143d0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42005fda0 sp=0xc42005fcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42005fe88, 0x410022, 0xc420014330)
	<autogenerated>:4 +0x46 fp=0xc42005fde0 sp=0xc42005fda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42005fe68 sp=0xc42005fde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffe2c183f1c, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42005fed8 sp=0xc42005fe68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42005ff58 sp=0xc42005fed8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42005ff88 sp=0xc42005ff58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42005ffe0 sp=0xc42005ff88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42005ffe8 sp=0xc42005ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffe2c182b30
rcx    0x7fde76fa4fb7
rdx    0x0
rdi    0x2
rsi    0x7ffe2c1828c0
rbp    0x7ffe2c182c30
rsp    0x7ffe2c1828c0
r8     0x0
r9     0x7ffe2c1828c0
r10    0x8
r11    0x246
r12    0x7ffe2c182b30
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fde76fa4fb7
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Sending build context to Docker daemon   1.54MB
```

See https://leeroy.cs.unc.edu/job/graphene-sgx-gsc/1021/consoleFull.
How could it succeed?

---


<!-- Sent from Reviewable.io -->

2021-02-01 12:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOuMBL7QN_8cwj2dW4:-MSSdq50-3dVoHbPZq22:bevkfmy) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Waaait, what's that thing in the Jenkins log, of that successful run?

```
make[1]: Entering directory '/home/jenkins/workspace/graphene-sgx-gsc/Tools/gsc/test'
echo "Building base image ubuntu18.04-python3.dockerfile..."
Building base image ubuntu18.04-python3.dockerfile...
docker build --rm --no-cache -t ubuntu18.04-python3-a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f -f ubuntu18.04-python3.dockerfile ../../../Examples
free(): invalid pointer
SIGABRT: abort
PC=0x7fde76fa4fb7 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42005fcc0, 0xc42005fce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42005fc90 sp=0xc42005fc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0xa16270)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42005fcc0 sp=0xc42005fc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0xa16270)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42005fcf8 sp=0xc42005fcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200143d0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42005fda0 sp=0xc42005fcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42005fe88, 0x410022, 0xc420014330)
	<autogenerated>:4 +0x46 fp=0xc42005fde0 sp=0xc42005fda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42005fe68 sp=0xc42005fde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffe2c183f1c, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42005fed8 sp=0xc42005fe68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42005ff58 sp=0xc42005fed8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42005ff88 sp=0xc42005ff58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42005ffe0 sp=0xc42005ff88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42005ffe8 sp=0xc42005ffe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffe2c182b30
rcx    0x7fde76fa4fb7
rdx    0x0
rdi    0x2
rsi    0x7ffe2c1828c0
rbp    0x7ffe2c182c30
rsp    0x7ffe2c1828c0
r8     0x0
r9     0x7ffe2c1828c0
r10    0x8
r11    0x246
r12    0x7ffe2c182b30
r13    0x1000
r14    0x0
r15    0x30
rip    0x7fde76fa4fb7
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Sending build context to Docker daemon   1.54MB
```

See https://leeroy.cs.unc.edu/job/graphene-sgx-gsc/1021/consoleFull.
How could it succeed?
</blockquote></details>

After reading through internet, this is a commonly seen benign bug in Docker. It was fixed in the mainline Docker but seems like not backported in Ubuntu 18.04. See these:
- https://github.com/docker/docker-credential-helpers/issues/103
- https://github.com/docker/docker-credential-helpers/pull/29 -- this is the fix
- https://github.com/docker/docker-credential-helpers/issues/103#issuecomment-479508473 -- the favorite way of fixing this.

So looks like we can ignore this benign error on Docker side. Or fix it via `dpkg -r --force-depends golang-docker-credential-helpers` on that Jenkins worker. @woju what would be your advise?

---


<!-- Sent from Reviewable.io -->

2021-02-01 13:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/manpages/gsc.rst, line 114 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS99J5w9A3S6sybZEo5:-MSSf5hz3R-0r3Q-Ro3x:b44fq18) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

shouldn't this be `--`, not `-`?
</blockquote></details>

No, the option is either `-nc` or `--no-cache`. So this is correct.
___
*[Documentation/manpages/gsc.rst, line 434 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9Egs7CRmnDsX89d-T:-MSSfHsi1vdXnx7bttQQ:b-9d6uyg) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L434)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

` SGXDriver.Repository` default value is pointing to the old OOT (and basically most of this guide is pointing to it).
</blockquote></details>

Not sure what you're suggesting here. We have `SGXDriver.Repository` pointing to the old OOT driver because this is what is used in our Jenkins. Anyway, this is something that the user must change for himself.

Or do you mean to simply replace `/dev/sgx/enclave` here with `/dev/isgx`, for consistency in all GSC docs/files?
___
*[Tools/gsc/finalize_manifest.py, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSJJ3PTDq5kad2Wwx6z:-MSSfeyIEq8cU0vHXmKj:b3dur6a) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/finalize_manifest.py#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

that's not enough, there are still names which will break the generation, e.g. `asdf"qwer`. Not sure about newlines, we'd need to verify with tomlc99.
</blockquote></details>

Yeah, I'm not sure what to do here? Should I remove this check completely and hope that the filenames are TOML-formatted? Should I white-list only latin alphanumerics plus a couple special signs?


<!-- Sent from Reviewable.io -->

2021-02-01 13:38 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Documentation/manpages/gsc.rst, line 114 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS99J5w9A3S6sybZEo5:-MSSn0He3ELHlIRCys9T:b-rs2375) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L114)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, the option is either `-nc` or `--no-cache`. So this is correct.
</blockquote></details>

I meant that usually you have `--` for long options and `-` for single-letter ones, so you can concat them (i.e. `-nc` is the same as `-n -c`). Seems confusing, as all other options used here seem to stick to this convention, except this one.
___
*[Documentation/manpages/gsc.rst, line 434 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9Egs7CRmnDsX89d-T:-MSSnNidC8eS1nfHfjYW:b-4flevz) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L434)):*
> We have `SGXDriver.Repository` pointing to the old OOT driver because this is what is used in our Jenkins.

That's a bad argument for user-facing defaults ;) Users should not need to know about our Jenkins.

> Or do you mean to simply replace /dev/sgx/enclave here with /dev/isgx, for consistency in all GSC docs/files?

Whichever way, but make it consistent.
___
*[Tools/gsc/finalize_manifest.py, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSJJ3PTDq5kad2Wwx6z:-MSSnqUc2c6mhL2a6uLK:b24ijeq) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/finalize_manifest.py#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I'm not sure what to do here? Should I remove this check completely and hope that the filenames are TOML-formatted? Should I white-list only latin alphanumerics plus a couple special signs?
</blockquote></details>

Maybe just escape `"` and `\`? Isn't this enough? (but please check with TOML specs/tomlc99 code, because I'm not sure about newlines and similar stuff)


<!-- Sent from Reviewable.io -->

2021-02-02 09:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: 16 of 20 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/manpages/gsc.rst, line 60 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS98D8S5J80sdbZr9CS:-MSWl40X3R8zYiI9D1nt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

we should drop this and ask to use a kernel with fsgsbase
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 70 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS98eHZDFz3p6WNyKNX:-MSWl6gO4E5QLY8pWJIx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>    You could also run commands as root.
> ```

I'd drop this sentence, the whole warning sounds really weird with it.
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 114 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS99J5w9A3S6sybZEo5:-MSWlPB6EBpbFSQ51QAz:b-sa9pe1) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I meant that usually you have `--` for long options and `-` for single-letter ones, so you can concat them (i.e. `-nc` is the same as `-n -c`). Seems confusing, as all other options used here seem to stick to this convention, except this one.
</blockquote></details>

Done. Got it now, changed to `--`.
___
*[Documentation/manpages/gsc.rst, line 149 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS99cdyCUPfrq0AaAtD:-MSWl_5e5Xym0faR71lr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L149)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`in intermediate Docker images` -> `in them` (repetition)
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 238 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9ApzQE7oG5H1ZEw-t:-MSWmBDu5gU8LqxFm9WN:b-puiu4v) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L238)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Similarly to Docker, Graphene has a corresponding option (``libos.entrypoint``) [...]
> ```

Not sure if this whole sentence is actually needed, seems the users doesn't need to know about manifests?
</blockquote></details>

Done. I believe you added this :)

But yes, this whole section looks unnecessary. Users only use the original Docker image and (optionally) the extra-manifest (with things like `sgx.enclave_size`). They don't specify `libos.entrypoint` at all. So I removed the whole section.
___
*[Documentation/manpages/gsc.rst, line 269 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9BklhBZwKYolDadt8:-MSWmaEv6CdhvUS_94VI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L269)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`signing of the enclave` -> `signature of the enclave`
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 281 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9CCWPEwVWwpc91WjK:-MSWmolX61PW2qZArGU9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L281)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Note that prebuilt Graphene images will be provided for popular cloud-provider
> offerings or can be created via :command:`gsc build-graphene`.
> ```

`Note that` -> `In the future we plan to provide [...]`
</blockquote></details>

Done.
___
*[Documentation/manpages/gsc.rst, line 434 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9Egs7CRmnDsX89d-T:-MSWmuK232qiQx2JwJnS:brz82hj) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L434)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> We have `SGXDriver.Repository` pointing to the old OOT driver because this is what is used in our Jenkins.

That's a bad argument for user-facing defaults ;) Users should not need to know about our Jenkins.

> Or do you mean to simply replace /dev/sgx/enclave here with /dev/isgx, for consistency in all GSC docs/files?

Whichever way, but make it consistent.
</blockquote></details>

Done. We're currently stuck with supporting multiple versions of the SGX driver. This is a sad reality our users should be aware of for at least a year or two.

I fixed to use old `isgx` in this example.
___
*[Tools/gsc/finalize_manifest.py, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSJJ3PTDq5kad2Wwx6z:-MSWq6818ulHHpfoizQK:b-klp4l1) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/finalize_manifest.py#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe just escape `"` and `\`? Isn't this enough? (but please check with TOML specs/tomlc99 code, because I'm not sure about newlines and similar stuff)
</blockquote></details>

Done. I ended up using single-line basic strings in TOML. I only restrict newlines and carriage returns, and we must escape backslashes and quotes, but other stuff is supported (must be in UTF-8). See https://toml.io/en/v1.0.0#string
___
*[Tools/gsc/gsc.py, line 254 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOtHN62wWgKRUUCb6F:-MSWqU9ZCdod0vveBeKo:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/gsc.py#L254)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please wrap `forcerm` with backticks, looked like a typo for me at first ;)
</blockquote></details>

Done.
___
*[Tools/gsc/templates/entrypoint.manifest.template, line 20 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOoPejDagTTcj4FPZM:-MSWqq8L92ZHIUFa88uO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Tools/gsc/templates/entrypoint.manifest.template#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please link to the issue, the numbers may change if we migrate the Graphene repo or GSC.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 10:13 UTC, dimakuv commented
Jenkins, retest Jenkins please (`sendfile08` LTP test failed, known issue)

2021-02-03 00:12 UTC, mkow requested changes
> Reviewed 3 of 6 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Documentation/manpages/gsc.rst, line 238 at r3](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS9ApzQE7oG5H1ZEw-t:-MS_AaCsC9zrFrAfZyqg:b-fr74hu) ([raw file](https://github.com/oscarlab/graphene/blob/a532c8a366b1d66b256c5d3c8e3ea56de7cbe27f/Documentation/manpages/gsc.rst#L238)):*
> Done. I believe you added this :)

Yes, I know :) But now I re-read the whole GSC documentation and noticed that the users don't really need to know our manifest syntax to use it, and moreover, this entry is automatically generated. So, it's not very useful to mention it here.
___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MS_C2Yy4_O7-9D3YDvm:b-v255h2) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
> ```Python
> def is_utf8(string):
>     try:
>         string.encode('utf-8')
> ```

not `.decode()`? and `bytes`, not `string`


<!-- Sent from Reviewable.io -->

2021-02-03 10:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MSbVQe_EcyROFsyAB63:b-nuc5vg) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not `.decode()`? and `bytes`, not `string`
</blockquote></details>

No, my version looks correct. We pass the `str` object to this function -- which is the Unicode string in Python3. Then we `encode()` it to get the `bytes` object (these are the objects that are used to store to file).

Please see https://medium.com/better-programming/strings-unicode-and-bytes-in-python-3-everything-you-always-wanted-to-know-27dc02ff2686. Python3 `strings` vs `bytes` are a mess, but much better than Python2 :)


<!-- Sent from Reviewable.io -->

2021-02-03 12:26 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MSboqKh3IDl96jHQdsr:bz7kn2i) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, my version looks correct. We pass the `str` object to this function -- which is the Unicode string in Python3. Then we `encode()` it to get the `bytes` object (these are the objects that are used to store to file).

Please see https://medium.com/better-programming/strings-unicode-and-bytes-in-python-3-everything-you-always-wanted-to-know-27dc02ff2686. Python3 `strings` vs `bytes` are a mess, but much better than Python2 :)
</blockquote></details>

I understand bytes vs str in Python3, seems I got confused by the function name - `is_utf8` - UTF-8 is an encoding, so only a byte array can be "utf-8". What does this mean for a string?
Also, looking only at the implementation, how can something be non-encodable in UTF-8? I thought it can encode all unicode codepoints?


<!-- Sent from Reviewable.io -->

2021-02-03 13:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MSbv52L1z_ruomFoWn3:b-rvq7b8) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I understand bytes vs str in Python3, seems I got confused by the function name - `is_utf8` - UTF-8 is an encoding, so only a byte array can be "utf-8". What does this mean for a string?
Also, looking only at the implementation, how can something be non-encodable in UTF-8? I thought it can encode all unicode codepoints?
</blockquote></details>

Yes, I think I didn't conceptualize it to myself previously. So the issue is like this:

1. Python3 uses utf-8, utf-16 or utf-32 to represent `string` objects internally (it chooses the fitting encoding at runtime, see https://www.python.org/dev/peps/pep-0393/).

2. TOML only accepts utf-8.

3. Some filenames in some Docker images surprisingly have non-utf-8 names (I got the error "cant parse this string" on some Python image, I think with `numpy`).

Thus, it is possible that a `filename` from `os.walk()` returns a utf-32 string which can't be represented in utf-8. So `string.encode('utf-8')` fails, and we skip outputting this filename to TOML.

Should I rename the function or add a comment?


<!-- Sent from Reviewable.io -->

2021-02-03 13:48 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MSc27AFB9bGGWqZiUMs:bfy8tea) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I think I didn't conceptualize it to myself previously. So the issue is like this:

1. Python3 uses utf-8, utf-16 or utf-32 to represent `string` objects internally (it chooses the fitting encoding at runtime, see https://www.python.org/dev/peps/pep-0393/).

2. TOML only accepts utf-8.

3. Some filenames in some Docker images surprisingly have non-utf-8 names (I got the error "cant parse this string" on some Python image, I think with `numpy`).

Thus, it is possible that a `filename` from `os.walk()` returns a utf-32 string which can't be represented in utf-8. So `string.encode('utf-8')` fails, and we skip outputting this filename to TOML.

Should I rename the function or add a comment?
</blockquote></details>

1. ? Why would this matter for anything? It's just the internal representation. Python strings AFAIK are conceptually just arrays of unicode codepoints.
2. Yes.
3. Filenames on Linux are not in UTF-8. They are arbitrary byte sequences without null bytes and slashes. I guess the bug is that GSC treats them as UTF-8 sequences?


<!-- Sent from Reviewable.io -->

2021-02-03 13:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MSc7ME17rNyDZm_mkgG:b-noai46) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I think I didn't conceptualize it to myself previously. So the issue is like this:

1. Python3 uses utf-8, utf-16 or utf-32 to represent `string` objects internally (it chooses the fitting encoding at runtime, see https://www.python.org/dev/peps/pep-0393/).

2. TOML only accepts utf-8.

3. Some filenames in some Docker images surprisingly have non-utf-8 names (I got the error "cant parse this string" on some Python image, I think with `numpy`).

Thus, it is possible that a `filename` from `os.walk()` returns a utf-32 string which can't be represented in utf-8. So `string.encode('utf-8')` fails, and we skip outputting this filename to TOML.

Should I rename the function or add a comment?
</blockquote></details>

Sorry, I'm educating myself as I'm writing these comments. I was wrong in the previous comments.

https://www.b-list.org/weblog/2017/sep/05/how-python-does-unicode/ -- reading this document helped me clear the confusion between UTF-8 vs UTF-16 vs UTF-32 vs latin-1 vs UCS-2 and UCS-4.


<!-- Sent from Reviewable.io -->

2021-02-03 13:52 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MSc8uBY2rwqHAB1FcS3:b-o4ehp0) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I'm educating myself as I'm writing these comments. I was wrong in the previous comments.

https://www.b-list.org/weblog/2017/sep/05/how-python-does-unicode/ -- reading this document helped me clear the confusion between UTF-8 vs UTF-16 vs UTF-32 vs latin-1 vs UCS-2 and UCS-4.
</blockquote></details>

Let me debug what happens below. My head is spinning.

Ok, so my code basically does this, right:
```python
    for root, _, files in os.walk(root_dir, followlinks=False):
        for file in files:
            filename = os.path.join(root, file)
            filename.encode('utf-8') # this can fail!
```

We have the `string` Python object. We encode it into UTF-8. All strings must be representable in UTF-8, unless the string is not really a string but a sequence of non-UTF-8-formatted bytes...


<!-- Sent from Reviewable.io -->

2021-02-03 13:59 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MScB4mF5xN8R385XQGC:b-p96c09) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let me debug what happens below. My head is spinning.

Ok, so my code basically does this, right:
```python
    for root, _, files in os.walk(root_dir, followlinks=False):
        for file in files:
            filename = os.path.join(root, file)
            filename.encode('utf-8') # this can fail!
```

We have the `string` Python object. We encode it into UTF-8. All strings must be representable in UTF-8, unless the string is not really a string but a sequence of non-UTF-8-formatted bytes...
</blockquote></details>

Wait, `os.walk` returns `bytes`, not `str`? I don't get what's happening in that listing :P


<!-- Sent from Reviewable.io -->

2021-02-03 14:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MScDeua6coRYgQYDRuX:b-vzrnr6) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wait, `os.walk` returns `bytes`, not `str`? I don't get what's happening in that listing :P
</blockquote></details>

No, filenames have a type `str`. Just check this:
```python
for root, _, files in os.walk(".", followlinks=False):
    for file in files:
        print(f"{file} {type(file)}")
```

It prints things like:
```
.ubuntu18.04-bash.dockerfile.swp <class 'str'>
ubuntu18.04-pytorch.dockerfile <class 'str'>
.ubuntu18.04-numpy.dockerfile.swp <class 'str'>
```

(Same if I do `type(os.path.join(root, file))`)


<!-- Sent from Reviewable.io -->

2021-02-03 14:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MScG0ZUBUExEnqc9OlR:b-oc0qrl) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, filenames have a type `str`. Just check this:
```python
for root, _, files in os.walk(".", followlinks=False):
    for file in files:
        print(f"{file} {type(file)}")
```

It prints things like:
```
.ubuntu18.04-bash.dockerfile.swp <class 'str'>
ubuntu18.04-pytorch.dockerfile <class 'str'>
.ubuntu18.04-numpy.dockerfile.swp <class 'str'>
```

(Same if I do `type(os.path.join(root, file))`)
</blockquote></details>

Do `os.walk(b'.', ...)` and it will return bytes.


<!-- Sent from Reviewable.io -->

2021-02-03 15:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: 19 of 20 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 17 at r5](https://reviewable.io/reviews/oscarlab/graphene/2112#-MS_C2Yy4_O7-9D3YDvl:-MScY3ZjCxTAjGcDeaDY:bh38inh) ([raw file](https://github.com/oscarlab/graphene/blob/dceefd684e0a2233affedbf9df672b4320f54ea1/Tools/gsc/finalize_manifest.py#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do `os.walk(b'.', ...)` and it will return bytes.
</blockquote></details>

Done. I decided to have explicit `UTF-8` encoding everywhere to make it very clear that we (well, TOML) want this encoding and nothing else.
___
*[Tools/gsc/finalize_manifest.py, line 49 at r6](https://reviewable.io/reviews/oscarlab/graphene/2112#-MScYjuzCMjoud5eB7Ap:-MScYjuzCMjoud5eB7Aq:b-7ft9hp) ([raw file](https://github.com/oscarlab/graphene/blob/3a9613daf93b5fff53b8965219193965e19ef9c8/Tools/gsc/finalize_manifest.py#L49)):*
> ```Python
>                 # we append filenames as TOML strings which must be in UTF-8, ignore filenames
>                 # that cannot be represented in UTF-8 encoding
>                 print(f'\t[from inside Docker container] File {filename} is not in UTF-8!')
> ```

Currently I'm just printing the "bad" filename. I will change to loud fail after I analyze which files are non-utf-8.


<!-- Sent from Reviewable.io -->

2021-02-03 16:30 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: 19 of 21 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Tools/gsc/finalize_manifest.py, line 49 at r6](https://reviewable.io/reviews/oscarlab/graphene/2112#-MScYjuzCMjoud5eB7Ap:-MScihdiCId4p10EWQ_v:b-42pu5h) ([raw file](https://github.com/oscarlab/graphene/blob/3a9613daf93b5fff53b8965219193965e19ef9c8/Tools/gsc/finalize_manifest.py#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Currently I'm just printing the "bad" filename. I will change to loud fail after I analyze which files are non-utf-8.
</blockquote></details>

Done. Changed to a fail now.


<!-- Sent from Reviewable.io -->

2021-02-03 17:56 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-apps please (`./pal_loader redis-server --save '' --protected-mode no enclave EINIT failed - Invalid measurement`, some Makefile issue that Michal mentioned?)

2021-02-04 00:32 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-02-04 08:12 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: 20 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOuMBL7QN_8cwj2dW4:-MSg5-R-B-z_dKXlOHZk:brvd3zh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

After reading through internet, this is a commonly seen benign bug in Docker. It was fixed in the mainline Docker but seems like not backported in Ubuntu 18.04. See these:
- https://github.com/docker/docker-credential-helpers/issues/103
- https://github.com/docker/docker-credential-helpers/pull/29 -- this is the fix
- https://github.com/docker/docker-credential-helpers/issues/103#issuecomment-479508473 -- the favorite way of fixing this.

So looks like we can ignore this benign error on Docker side. Or fix it via `dpkg -r --force-depends golang-docker-credential-helpers` on that Jenkins worker. @woju what would be your advise?
</blockquote></details>

Should we do anything about it? @woju Ping again.

---


<!-- Sent from Reviewable.io -->

2021-02-04 08:39 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug please (Apache web server seems to have taken more than 1 second to initialize due to a LOT of debug messages, and the client couldn't connect and panicked)

2021-02-04 11:17 UTC, mkow reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-02-04 14:58 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOuMBL7QN_8cwj2dW4:-MShXle33Ie5onhmLToq:bxwwuek) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should we do anything about it? @woju Ping again.
</blockquote></details>

If it's not critical and builds won't fail, I don't think we should do anything about this. Also I wonder why we didn't see this previously. Sorry for the delay.

---


<!-- Sent from Reviewable.io -->

2021-02-04 21:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2112#-MSOuMBL7QN_8cwj2dW4:-MSivDPzCT_hohB087cZ:b2xir44) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If it's not critical and builds won't fail, I don't think we should do anything about this. Also I wonder why we didn't see this previously. Sorry for the delay.
</blockquote></details>

Ok, thanks for the input. I suggest to unblock this then.

We probably simply haven't noticed this before. This thing happens in the very beginning of the Jenkins job, and is buried in the several-MBs log.

---


<!-- Sent from Reviewable.io -->

2021-02-04 22:56 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2112)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-04 22:59 UTC, merged