[LibOS] Disable UBSAN sanitizer in test_user_memory to not trip on NULL pointer
oscarlab/graphene pull request #2123
Opened 2021-01-26 18:28 UTC by stefanberger

This patch further prepares to enable USBAN in Graphene. It disables the UBSAN sanitizer in `test_user_memory()` so that we do not trip on writing to the NULL pointer in when some of the syscalls call this function with a NULL pointer. This now allows to pass LPC tests calling the syscalls `getrandom`, `sethostname`, `setdomainname` and the ones that are calling into `chkmsg_hdr`.

2021-01-26 19:02 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-26 19:17 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 492 at r1](https://reviewable.io/reviews/oscarlab/graphene/2123#-MS-78G41iZ7YsCAgYpi:-MS-78G41iZ7YsCAgYpj:b-opo7ge) ([raw file](https://github.com/oscarlab/graphene/blob/f974a7f855d2cebb5ad3101d76ab7d534a8cbdfb/LibOS/shim/src/bookkeep/shim_signal.c#L492)):*
> ```C
>  * whether the memory is readable.
>  */
> bool test_user_string(const char* addr) {
> ```

Actually, can you add this attribute here as well? These two functions go hand-in-hand.


<!-- Sent from Reviewable.io -->

2021-01-26 19:38 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 492 at r1](https://reviewable.io/reviews/oscarlab/graphene/2123#-MS-78G41iZ7YsCAgYpi:-MS-Bz7I9x1IQLYV3Dbe:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f974a7f855d2cebb5ad3101d76ab7d534a8cbdfb/LibOS/shim/src/bookkeep/shim_signal.c#L492)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, can you add this attribute here as well? These two functions go hand-in-hand.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-26 19:53 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-26 19:53 UTC, dimakuv commented
Jenkins, test this please

2021-01-28 13:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2123#-MS87cq7Bgjwov_9Jmwu:-MS87cq7Bgjwov_9Jmwv:b-mlyn8b) (no related file):*
@stefanberger Jenkins failed with:
```
bookkeep/shim_signal.c:438:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 bool test_user_memory(void* addr, size_t size, bool write) {
 ^
bookkeep/shim_signal.c:498:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 bool test_user_string(const char* addr) {
 ^
```

---


<!-- Sent from Reviewable.io -->

2021-01-28 13:40 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2123#-MS87cq7Bgjwov_9Jmwu:-MS8CKAI3K-N8J3cyLe0:b-gx729t) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@stefanberger Jenkins failed with:
```
bookkeep/shim_signal.c:438:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 bool test_user_memory(void* addr, size_t size, bool write) {
 ^
bookkeep/shim_signal.c:498:1: error: 'no_sanitize' attribute directive ignored [-Werror=attributes]
 bool test_user_string(const char* addr) {
 ^
```
</blockquote></details>

That's the gcc version ... what version are you running there? We may need a #define for this __attribute__ to be enabled starting with a certain gcc version but then also can only compile with UBSAN enabled if we have the right versions, otherwise we'll trip on the NULL pointer. I have the same issue on ppc64:
```
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I am using gcc 10.2 on Fedora 33 on x86_64 now.

---


<!-- Sent from Reviewable.io -->

2021-01-28 13:50 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2123#-MS87cq7Bgjwov_9Jmwu:-MS8EtkfALn56yFgOCBp:b4i6pxo) (no related file):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

That's the gcc version ... what version are you running there? We may need a #define for this __attribute__ to be enabled starting with a certain gcc version but then also can only compile with UBSAN enabled if we have the right versions, otherwise we'll trip on the NULL pointer. I have the same issue on ppc64:
```
gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I am using gcc 10.2 on Fedora 33 on x86_64 now.
</blockquote></details>

It failed both on Ubuntu 16.04 and 18.04. 18.04 has GCC 7.5.0.
I guess the easiest way would be to ifdef on `USBAN` (and pass this to the preprocessor from Make when building with UBSAN). But this assumes that this attribute is always supported when `-fsanitize` is (i.e. this attribute wasn't added later).

---


<!-- Sent from Reviewable.io -->

2021-01-28 15:35 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2123#-MS87cq7Bgjwov_9Jmwu:-MS8cKHh3brABMce6hzi:b-91nc6j) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It failed both on Ubuntu 16.04 and 18.04. 18.04 has GCC 7.5.0.
I guess the easiest way would be to ifdef on `USBAN` (and pass this to the preprocessor from Make when building with UBSAN). But this assumes that this attribute is always supported when `-fsanitize` is (i.e. this attribute wasn't added later).
</blockquote></details>

`USBAN` hehe, same typo I make all the time.
Do we want to test the compiler somehow or just let the build run into the issue and the user then has to determine not to use UBSAN?

---


<!-- Sent from Reviewable.io -->

2021-01-28 15:52 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2123#-MS87cq7Bgjwov_9Jmwu:-MS8fmdC5d0Iqz9Bs7xj:bwyr2po) (no related file):*
lol :smile:

>  Do we want to test the compiler somehow or just let the build run into the issue and the user then has to determine not to use UBSAN?

I think we should be able to do this check in the makefiles with our `cc-option` function and refuse to build with `UBSAN=1` on an incompatible compiler.

---


<!-- Sent from Reviewable.io -->

2021-01-28 18:38 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-29 00:27 UTC, mkow commented
Jenkins, retest this please

2021-01-29 07:20 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-01-29 13:02 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-01-29 13:03 UTC, dimakuv commented
Jenkins, test this please

2021-01-29 13:04 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-01-29 17:14 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2123)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-29 21:24 UTC, merged