[LibOS] Add tmpfs implementation that allows program to protect intermediate file
oscarlab/graphene pull request #2124
Opened 2021-01-27 05:57 UTC by llly

## Description of the changes
When temporary files contain sensitive data, it's hard to add them to manifest as sgx.protected_files because the file name is usually contain generated random string.

In-memory tmpfs can solve this problem and avoid encryption/decryption overhead. Everything in tmpfs is temporary in the sense that no files will be created on your hard drive. All files and directories are stored in memory/EPC and will lost after Graphene exit.
- Usage:
tmpfs mount point can be assigned in manifest as
```
    fs.mount.[identifier].type = "tmpfs"
    fs.mount.[identifier].path = "[PATH]"
    fs.mount.[identifier].uri  = "[URI]"
```
`[PATH]` is the mount point. `[URI]` is ignored no matter what string it is.

Fixes #1787.

TODO: mmap().

## How to test this PR? 
TODO: Will add regression test.

2021-01-27 07:25 UTC, llly commented
@dimakuv Currently I'm blocked by mmap().
https://github.com/oscarlab/graphene/blob/ae8beba1a72c8c8cf68f5631a8cef9caa7a546dd/LibOS/shim/src/sys/shim_mmap.c#L177-L180
requires input and out address must be same. I don't know how to map memory to memory. alternatively, mmap() is not needed for tmpfs. 
Could you please give me some suggestion?

2021-01-27 10:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 0 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 255 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2Hf513ezekjWzK3WV:-MS2Hf513ezekjWzK3WW:bxpgm4c) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L255)):*
> ```C
>             }
>         } else {
>             /* This line is diffrent from strfs*/
> ```

Why did you copy-paste `str_write()` implementation and change these couple lines here?

Is there a bug in `str_write()` that you wanted to fix only for your tmpfs?

We should modify `str_write` and call it from this function.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 292 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2I6-T09gsokQAtCuj:-MS2I6-T09gsokQAtCuk:b-2q9jdi) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L292)):*
> ```C
> }
> 
> /* TODO is mmap really needed? */
> ```

Yes, mmap on temporary files is definitely needed. This is a common thing to use.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MS2IAFF7ywh7kTOgBu7:byn1h9r) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
> ```C
>     }
> 
>     // TODO mmap EPC addr  `data->str_data.str + offset` to EPC addr `*addr`
> ```

I understand your problem. On the one hand, you're just doing `malloc()` to keep temporary file contents. On the other hand, Graphene's `mmap()` implementation forces you to use the predefined `addr`.

I suggest the following:
1. Add `str_map()` function to `fs/str/fs.c`. This function will have the same arguments as here. This function will use `addr`.
2. Call `str_map()` from here.

Now inside `str_map()` we should simply do:
- `memcpy(addr, hdl->info.str->data->str + offset, size)` (if there is `hdl->info.str->data->str` at all)
- `free(hdl->info.str->data->str)`
- rewire `hdl->info.str->data->str = addr` (this is the address that the user mmapped for us, so we should rewire the internal buffer to this)
- probably change `hdl->info.str->ptr` to change the offset for subsequent `str_read` and `str_write` (but I don't remember semantics here, you need to check POSIX and manpages)
- add a new struct member to `shim_str_data` like `is_alloced_by_user`; this struct member will be false if there was no mmap and true if there was an mmap (if it is true, then you shouldn't do `free` in the `str/fs.c` code)

So basically you'll have two ways of allocating the internal str buffer:
1. via implicit malloc (the only way that is available now)
2. via explicit mmap (the new way to support shim_do_mmap)

And you rewire `hdl->info.str->data->str` based on which way is currently used.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 319 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2Hxrr6SZsITWsiQDR:-MS2Hxrr6SZsITWsiQDS:b-7o8uua) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L319)):*
> ```C
>     return ENOSYS;
> }
> static off_t tmpfs_seek(struct shim_handle* hdl, off_t offset, int whence) {
> ```

Why did you copy-paste `str_seek()` implementation and change couple lines here?

Is there a bug in `str_seek()` that you wanted to fix only for your tmpfs?

We should modify `str_seek` and call it from this function.


<!-- Sent from Reviewable.io -->

2021-01-28 01:48 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 0 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @llly)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 255 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2Hf513ezekjWzK3WV:-MS5aHFh3UH3ACMcFsVv:b-qauje4) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you copy-paste `str_write()` implementation and change these couple lines here?

Is there a bug in `str_write()` that you wanted to fix only for your tmpfs?

We should modify `str_write` and call it from this function.
</blockquote></details>

Will do.  str_write() doesn't handle current position of the pointer correctly.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MS5ekQS8bXjB5puwKsr:b-nqktf5) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I understand your problem. On the one hand, you're just doing `malloc()` to keep temporary file contents. On the other hand, Graphene's `mmap()` implementation forces you to use the predefined `addr`.

I suggest the following:
1. Add `str_map()` function to `fs/str/fs.c`. This function will have the same arguments as here. This function will use `addr`.
2. Call `str_map()` from here.

Now inside `str_map()` we should simply do:
- `memcpy(addr, hdl->info.str->data->str + offset, size)` (if there is `hdl->info.str->data->str` at all)
- `free(hdl->info.str->data->str)`
- rewire `hdl->info.str->data->str = addr` (this is the address that the user mmapped for us, so we should rewire the internal buffer to this)
- probably change `hdl->info.str->ptr` to change the offset for subsequent `str_read` and `str_write` (but I don't remember semantics here, you need to check POSIX and manpages)
- add a new struct member to `shim_str_data` like `is_alloced_by_user`; this struct member will be false if there was no mmap and true if there was an mmap (if it is true, then you shouldn't do `free` in the `str/fs.c` code)

So basically you'll have two ways of allocating the internal str buffer:
1. via implicit malloc (the only way that is available now)
2. via explicit mmap (the new way to support shim_do_mmap)

And you rewire `hdl->info.str->data->str` based on which way is currently used.
</blockquote></details>

Thanks. Will add `str_mmap()`
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 319 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2Hxrr6SZsITWsiQDR:-MS5b9R7ACu-7rDGvKhO:bu7ufar) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L319)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you copy-paste `str_seek()` implementation and change couple lines here?

Is there a bug in `str_seek()` that you wanted to fix only for your tmpfs?

We should modify `str_seek` and call it from this function.
</blockquote></details>

 Will do.  str_seek() doesn't handle current position of the pointer correctly.


<!-- Sent from Reviewable.io -->

2021-01-28 04:37 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 0 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS6GYEw8XLP-wJEOAp9:-MS6GYEyC5OVO995Qy7H:b566jcx) (no related file):*
just to check my understanding. files under this tmpfs won’t be shared with child or sibling graphene process. so it can’t be used to pass/share file, correct?

---
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 167 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS6E9NSB1b8m_pyKec4:-MS6E9NU5G2ACO8ebmbW:b-g3x82x) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L167)):*
> ```C
>             break;
>         default:
>             assert(true);
> ```

nit: abort()


<!-- Sent from Reviewable.io -->

2021-02-02 04:59 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 0 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS6GYEw8XLP-wJEOAp9:-MSW5iDgDp0RnWwvINx4:b-vxjkbz) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

just to check my understanding. files under this tmpfs won’t be shared with child or sibling graphene process. so it can’t be used to pass/share file, correct?
</blockquote></details>

Correct. I think it's impossible to share between processes.

---
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 167 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS6E9NSB1b8m_pyKec4:-MSW5fMI0Q85CCp7PjyN:bfr8kzo) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L167)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nit: abort()
</blockquote></details>

wil fix.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSW3bvlDMQDLGe-nJR9:b-h8rzsl) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
>memcpy(addr, hdl->info.str->data->str + offset, size) (if there is hdl->info.str->data->str at all)
>free(hdl->info.str->data->str)

There is a problem here. If `offset` is non-zero. the str from start to offset is lost. If  hdl->info.str->data->len is bigger than offset +size(both aligned with page), the str from  offset +size to len is lost, too.


<!-- Sent from Reviewable.io -->

2021-02-02 06:01 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 0 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSWHo9aCCCmx9EgY0nO:b-4k6qr1) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
> via explicit mmap (the new way to support shim_do_mmap)
I think str will lost after user call shim_do_munmap().

And two mmap call to map one str to different addr cannot be handled. 


<!-- Sent from Reviewable.io -->

2021-02-02 07:54 UTC, dimakuv reviewed
> Reviewed 2 of 4 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 3 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSWhbDeAExJlprhA6sW:bvq9svn) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
Hm, so we have two issues here:

> There is a problem here. If offset is non-zero. the str from start to offset is lost. If hdl->info.str->data->len is bigger than offset +size(both aligned with page), the str from offset +size to len is lost, too.

I think this is easy to solve. We simply take into account these "unused parts" and keep the "largest used" memory region. And we return a pointer inside this memory region to the user (based on the user-provided offset).

> And two mmap call to map one str to different addr cannot be handled.

I don't think this is actually realistic. I can't image an app that will do `mmap(0x10000, ..., my-tmp-file-fd)` and then at another address `mmap(0x20000, ..., my-tmp-file-fd)`.

So I think you can just check whether `addr` passed to `tmpfs_mmap()` is not the same as an already-used-one and return some error (I suggest `EPERM`). I'm 99% sure no sane application will map the same file at different addresses twice.


<!-- Sent from Reviewable.io -->

2021-02-02 08:20 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 3 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSWmSo_EqnWrLau6P0j:b-ccg7ie) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
> We simply take into account these "unused parts" and keep the "largest used" memory region.

The memory region is calculated from length before calling tmpfs_mmap().  Can't know "largest used".


<!-- Sent from Reviewable.io -->

2021-02-02 09:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 3 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSX6whI3wJD_uaK2tB4:bsk24l4) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

> We simply take into account these "unused parts" and keep the "largest used" memory region.

The memory region is calculated from length before calling tmpfs_mmap().  Can't know "largest used".
</blockquote></details>

Sorry, I'm not following. Why can't we have additional fields in `struct shim_tmpfs_data` to carry the base, the size, etc. of the memory region? Maybe an example would help me understand.


<!-- Sent from Reviewable.io -->

2021-02-02 12:49 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 3 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/str/fs.c, line 195 at r2](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSWrotJ74xL2rgDQ_Q8:-MSWrotJ74xL2rgDQ_Q9:b6iypux) ([raw file](https://github.com/oscarlab/graphene/blob/ae8beba1a72c8c8cf68f5631a8cef9caa7a546dd/LibOS/shim/src/fs/str/fs.c#L195)):*
> ```
>                
> ```
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 255 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2Hf513ezekjWzK3WV:-MSWp7NK-K2M6ru1P4a3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L255)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Will do.  str_write() doesn't handle current position of the pointer correctly.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSXjGrM6quXqyKw1h0l:b-mgq6nw) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I'm not following. Why can't we have additional fields in `struct shim_tmpfs_data` to carry the base, the size, etc. of the memory region? Maybe an example would help me understand.
</blockquote></details>

Do you mean that we cut `str` into three pieces: 1, str_begin to (str_begin+offset),  2, (str_begin+offset) to (str_begin+offset+length), 3,(str_begin+offset+length) to str_end. When mmap(), only cut number 2  to `addr`?


<!-- Sent from Reviewable.io -->

2021-02-02 12:57 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 3 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSXn6ve2TsrdjoWx7XT:bozt120) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Do you mean that we cut `str` into three pieces: 1, str_begin to (str_begin+offset),  2, (str_begin+offset) to (str_begin+offset+length), 3,(str_begin+offset+length) to str_end. When mmap(), only cut number 2  to `addr`?
</blockquote></details>

Or in shim_do_mmap(), use bkeep_mmap_any_aslr() to find enough  memory region for whole data->str instead of  only`length`?
bkeep_mmap_any_aslr() is called earlier than any tmpfs operations. So it doesn't know it's tmpfs.


<!-- Sent from Reviewable.io -->

2021-02-03 07:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 3 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSapK01CzSrGawOaozc:-MSapK01CzSrGawOaozd:b9sj5g0) (no related file):*
We had an offline chat with @llly and agreed to **not** implement the `mmap()` callback in this PR.

1. There are luckily currently no applications that require mmap on tmpfs files.
2. The `str_mmap()` implementation turned out extremely cumbersome and with many assumptions on what the applications can and cannot do.
3. Graphene's `shim_do_mmap()` and `shim_do_unmap()` implementations do not really give any room for special-casing tmpfs memory management. In particular, `shim_do_unmap()` doesn't have any callback into the FS, which means that tmpfs has no idea whether its file-backed memory regions got invalidated.

There are at least two cases that we don't know how to solve currently:
1. Two `mmaps` on the same tmpfs file. The file representation is simply an enclave memory region, but two `shim_do_mmap()` will require to allocate two different memory regions in the enclave. Since there is no way to share pages (map two virtual addresses to a single physical one), there is no way to alias these two memory regions to one "backing" tmpfs file. So if the user modifies in one memory region, and then reads from another memory region, the result will be inconsistent.
2. The sequence `open -> mmap -> munmap -> read`. This is perfectly legal in normal Linux, but after the `munmap`, our tmpfs has no access to the file's memory region (`shim_do_munmap()` simply frees this memory region unconditionally). So the subsequent `read` will segfault. There seems to be no way to fix this without making global changes to how `munmap()` is emulated in Graphene.

Based on the above, we decided to **not** implement mmap functionality in this PR. @llly will add a TODO comment about this.

---
___
*[LibOS/shim/src/fs/str/fs.c, line 195 at r2](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSWrotJ74xL2rgDQ_Q8:-MSap-Bn5O6xnc-xgwhm:b-wcxmyw) ([raw file](https://github.com/oscarlab/graphene/blob/ae8beba1a72c8c8cf68f5631a8cef9caa7a546dd/LibOS/shim/src/fs/str/fs.c#L195)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

> ```
>                
> ```

</blockquote></details>

Accidental comment? Please mark it as Resolved or delete it.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS2IAFF7ywh7kTOgBu6:-MSap4hQDZnE_1tVfBNX:b4ipzrw) ([raw file](https://github.com/oscarlab/graphene/blob/f236f4ad6ee7c9abc0d2a272a32adf2c636ffd93/LibOS/shim/src/fs/tmpfs/fs.c#L314)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Or in shim_do_mmap(), use bkeep_mmap_any_aslr() to find enough  memory region for whole data->str instead of  only`length`?
bkeep_mmap_any_aslr() is called earlier than any tmpfs operations. So it doesn't know it's tmpfs.
</blockquote></details>

Yes, `mmap()` implementation turned out extremely complicated/impossible under current LibOS memory-management implementation. See my top comment. I'm resolving this, we should proceed with this PR *without mmap*.


<!-- Sent from Reviewable.io -->

2021-02-05 06:16 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 2 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MS6GYEw8XLP-wJEOAp9:-MSkp9ld2_sOuEma58Yq:b-896fix) (no related file):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Correct. I think it's impossible to share between processes.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSapK01CzSrGawOaozc:-MSkotr--3D6WlRoj3Tl:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We had an offline chat with @llly and agreed to **not** implement the `mmap()` callback in this PR.

1. There are luckily currently no applications that require mmap on tmpfs files.
2. The `str_mmap()` implementation turned out extremely cumbersome and with many assumptions on what the applications can and cannot do.
3. Graphene's `shim_do_mmap()` and `shim_do_unmap()` implementations do not really give any room for special-casing tmpfs memory management. In particular, `shim_do_unmap()` doesn't have any callback into the FS, which means that tmpfs has no idea whether its file-backed memory regions got invalidated.

There are at least two cases that we don't know how to solve currently:
1. Two `mmaps` on the same tmpfs file. The file representation is simply an enclave memory region, but two `shim_do_mmap()` will require to allocate two different memory regions in the enclave. Since there is no way to share pages (map two virtual addresses to a single physical one), there is no way to alias these two memory regions to one "backing" tmpfs file. So if the user modifies in one memory region, and then reads from another memory region, the result will be inconsistent.
2. The sequence `open -> mmap -> munmap -> read`. This is perfectly legal in normal Linux, but after the `munmap`, our tmpfs has no access to the file's memory region (`shim_do_munmap()` simply frees this memory region unconditionally). So the subsequent `read` will segfault. There seems to be no way to fix this without making global changes to how `munmap()` is emulated in Graphene.

Based on the above, we decided to **not** implement mmap functionality in this PR. @llly will add a TODO comment about this.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-02-05 16:57 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 0 of 14 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @llly)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 51 at r5](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSn5YvX21_j48KsSjiF:-MSn5YvY0dL1EIgp9E2y:bfye5h7) ([raw file](https://github.com/oscarlab/graphene/blob/bec8f96e066790621aafebd39c4a37c347701fac/LibOS/shim/src/fs/tmpfs/fs.c#L51)):*
> ```C
>         return NULL;
> 
>     memset(data, 0, sizeof(struct shim_tmpfs_data));
> ```

nitpick: This isn't needed because calloc does it.
___
*[LibOS/shim/test/fs/test_tfs.py, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSn7-FX-x1qWSJY3uAr:-MSn7-FX-x1qWSJY3uAs:b-lnnzra) ([raw file](https://github.com/oscarlab/graphene/blob/bec8f96e066790621aafebd39c4a37c347701fac/LibOS/shim/test/fs/test_tfs.py#L1)):*
> ```Python
> #!/usr/bin/env python3
> ```

nitpick: test_tfs.py -> test_tempfs.py.
Or name conflict? Even in such case, test_tempfs0, etc is more descriptive.


<!-- Sent from Reviewable.io -->

2021-02-08 02:51 UTC, jinghe-INTC commented
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)_ status: 0 of 14 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @llly)
> 
> _[LibOS/shim/src/fs/tmpfs/fs.c, line 51 at r5](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSn5YvX21_j48KsSjiF:-MSn5YvY0dL1EIgp9E2y:bfye5h7) ([raw file](https://github.com/oscarlab/graphene/blob/bec8f96e066790621aafebd39c4a37c347701fac/LibOS/shim/src/fs/tmpfs/fs.c#L51)):_
> 
> > ```c
> >         return NULL;
> > 
> >     memset(data, 0, sizeof(struct shim_tmpfs_data));
> > ```
> 
> nitpick: This isn't needed because calloc does it.
> 
> _[LibOS/shim/test/fs/test_tfs.py, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSn7-FX-x1qWSJY3uAr:-MSn7-FX-x1qWSJY3uAs:b-lnnzra) ([raw file](https://github.com/oscarlab/graphene/blob/bec8f96e066790621aafebd39c4a37c347701fac/LibOS/shim/test/fs/test_tfs.py#L1)):_
> 
> > ```python
> > #!/usr/bin/env python3
> > ```
> 
> nitpick: test_tfs.py -> test_tempfs.py.
> Or name conflict? Even in such case, test_tempfs0, etc is more descriptive.

I am updating the test name from tfs to tmpfs.

2021-02-08 05:33 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 0 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 51 at r5](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSn5YvX21_j48KsSjiF:-MT-7IVm-iwR2D5KV7I6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bec8f96e066790621aafebd39c4a37c347701fac/LibOS/shim/src/fs/tmpfs/fs.c#L51)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nitpick: This isn't needed because calloc does it.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tfs.py, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene/2124#-MSn7-FX-x1qWSJY3uAr:-MT-7BTw0ZlAVTt4QWng:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bec8f96e066790621aafebd39c4a37c347701fac/LibOS/shim/test/fs/test_tfs.py#L1)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

I am updating the test name from tfs to tmpfs. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 15:29 UTC, dimakuv requested changes
> Reviewed 1 of 3 files at r3, 4 of 5 files at r4, 1 of 8 files at r5, 2 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 15 files reviewed, 64 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/Makefile, line 90 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT07zOM64BMlBUy1JGl:-MT07zOM64BMlBUy1JGm:b-z61q29) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/Makefile#L90)):*
> ```Makefile
> 	fs/socket/fs.o \
> 	fs/str/fs.o \
> 	fs/tmpfs/fs.o \
> ```

Please sort this list
___
*[LibOS/shim/src/fs/str/fs.c, line 137 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0oQ1B44TWrT5f98_o:-MT0oQ1CCt8p3-nQmkZI:b-kanppc) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L137)):*
> ```C
>             }
>         } else {
>             newlen = strhdl->ptr + count - data->str;
> ```

What is the point of this change? If you're here, then `data->str == 0`. And if there is no "underlying str memory region", then `strhdl->ptr == 0`.

If for some reason `strhdl->ptr` is not NULL at this point, this must indicate an internal bug in Graphene. So maybe also add `assert(strhdl->ptr);`.
___
*[LibOS/shim/src/fs/str/fs.c, line 144 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0p-ZK94V0PFUgFoCC:-MT0p-ZK94V0PFUgFoCD:b-7ci6ec) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L144)):*
> ```C
>             return -ENOMEM;
> 
>         memset(newbuf, 0, newlen);
> ```

Instead of memset, you can just replace `malloc()` with `calloc()` above. Please do this.
___
*[LibOS/shim/src/fs/str/fs.c, line 177 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0rYxkEDlzeD6yTtuD:-MT0rYxkEDlzeD6yTtuE:b4qdon0) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L177)):*
> ```C
>             if (offset < 0)
>                 return -EINVAL;
>             strhdl->ptr = data->str + offset;
> ```

Ideally, here and below, we would want to check for integer overflows. But it's not directly related to this PR, and we have similar issues in e.g. `chroot_seek()`, so I'm not blocking on this.
___
*[LibOS/shim/src/fs/str/fs.c, line 188 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0sBfG6nuXDLod8p2Y:-MT0sBfG6nuXDLod8p2Z:b-1ol8bm) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L188)):*
> ```C
>         case SEEK_END:
>             if (data->len + offset < 0)
>                return -EINVAL;
> ```

Indentation looks wrong. You have 3-space indent here.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 45 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0swcaB81N4y5xb4MR:-MT0swcaB81N4y5xb4MS:b-vaxjze) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L45)):*
> ```C
> 
> /* simply just create data, sometimes it is individually called when the
>    handle is not linked to a dentry */
> ```

What's the point of this comment? There is only one caller for this function. I suggest to remove this comment.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 47 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0tN0O55m7IRST67cO:-MT0tN0O55m7IRST67cP:b-f1fni8) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L47)):*
> ```C
>    handle is not linked to a dentry */
> static struct shim_tmpfs_data* __create_data(void) {
>     struct shim_tmpfs_data* data = calloc(1, sizeof(struct shim_tmpfs_data));
> ```

`sizeof(struct shim_tmpfs_data)` -> `sizeof(*data)`
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 65 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0ttQ_COzKvBRMxEA0:-MT0ttQ_COzKvBRMxEA1:b-r5eddr) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L65)):*
> ```C
> }
> 
> /* create a data in the dentry. dent->lock needs to be held */
> ```

This comment is useless, please remove it.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 77 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT12xiyAxK3evG1xYqr:-MT12xiyAxK3evG1xYqs:blycb4u) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L77)):*
> ```C
> 
>     data->type = FILE_UNKNOWN;
>     data->mode = 0;
> ```

I think you should use `NO_MODE` constant here.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 81 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0ubkRBROAWl4AIhJf:-MT0ubkSEFv_hdN9UXom:b-43ql2i) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L81)):*
> ```C
>     uint64_t time = DkSystemTimeQuery();
>     if (time == (uint64_t)-1)
>         time = 0;
> ```

I would prefer a more correct check and simply failing:
```
    uint64_t time = DkSystemTimeQuery();
    if ((int64_t)time < 0) {
        __destroy_data(data);
        return -EPERM;
    }
```
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 91 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0wZbs2kI8fJe-mVXa:-MT0wZbs2kI8fJe-mVXb:b5w16o3) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L91)):*
> ```C
> }
> 
> static inline int try_create_data(struct shim_dentry* dent, struct shim_tmpfs_data** dataptr) {
> ```

Can we rename this function to `get_or_create_tmpfs_data()`? The current name is misleading.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 102 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0wfdMD6fxMraD5rtQ:-MT0wfdMD6fxMraD5rtR:b5l8mgz) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L102)):*
> ```C
>             return ret;
>         }
>     }
> ```

This is racy and generally hard to read. I understand that you copy-pasted it from other part of Graphene, but our FS code is notoriously bad.

In particular, two threads may race on the very first line of code here. You read `dent->data` without the dent lock. So both threads can read NULL and then we'll have two `create_data()` which is wrong. I suggest this version:
```
lock(&dent->lock);
if (!dent->data) {
    int ret = create_data(dent);
    if (ret < 0) {
        unlock(&dent->lock);
        return ret;
    }
}
assert(dent->data);
*dataptr = (struct shim_tmpfs_data*)dent->data;
unlock(&dent->lock);
return 0;
```
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 124 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0yDeB8BjTAUtkdUaa:-MT0yDeB8BjTAUtkdUab:b-926o2o) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L124)):*
> ```C
>     struct shim_tmpfs_data* data;
>     if ((ret = try_create_data(dent, &data)) < 0)
>         return ret;
> ```

Let's split this in two lines for readability:
```
    ret = try_create_data(dent, &data);
    if (ret < 0)
        return ret;
```
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 130 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0zoQ61hkqLoS3fwBF:-MT0zoQ61hkqLoS3fwBG:b7p064) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L130)):*
> ```C
>         /* root of tmpfs */
>         data->type = FILE_DIR;
>         data->mode = 0777;
> ```

Please add `#include "perm.h"` at the top and use our macros: `PERM_rwxrwxrwx` in this case.
___
*[LibOS/shim/ [...]

2021-02-09 02:45 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 15 files reviewed, 64 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/test/fs/Makefile, line 23 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT1FY-M3lMEzsabK7nF:-MT3VM6t0eXbDH8CU2OL:b-qe0qbr) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/Makefile#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort all these lines
</blockquote></details>

Will change to 
``` 
        delete \
        delete_tmpfs \  
        open_close \
        open_flags \
        read_write \
        seek_tell \
        seek_tell_tmpfs \
        stat \
        stat_tmpfs \
        truncate \
        truncate_tmpfs
```
___
*[LibOS/shim/test/fs/manifest.template, line 28 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT095uA4le3Ff-mcEke:-MT3V9JlA7MlWAiB9KE1:b-f8ljg0) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/manifest.template#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? Why do you need the `uri` key for tmpfs?
</blockquote></details>

It is required by the current tmpfs design.
___
*[LibOS/shim/test/fs/manifest.template, line 40 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT09AoU9NwwzULCTtRE:-MT3V1IR67h5Mpu0SI5Z:bk6z0nk) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/manifest.template#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? Why is it needed?
</blockquote></details>

Will remove it.
___
*[LibOS/shim/test/fs/README.md, line 20 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT09F964r8bVo7HHfzc:-MT3_ZhK30v9g2IlNUYk:bxo2fy5) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/README.md#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this sentence. What does it mean `as tmpfs`?
</blockquote></details>

will be changed to `to test files and folders at a path on tmpfs`


<!-- Sent from Reviewable.io -->

2021-02-09 06:07 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 6 of 15 files reviewed, 63 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/src/Makefile, line 90 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT07zOM64BMlBUy1JGl:-MT3LAhAE1GpLJ-X_rFb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/Makefile#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort this list
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 137 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0oQ1B44TWrT5f98_o:-MT3BFchBiYGCtFNdXax:b-kr8mcl) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L137)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the point of this change? If you're here, then `data->str == 0`. And if there is no "underlying str memory region", then `strhdl->ptr == 0`.

If for some reason `strhdl->ptr` is not NULL at this point, this must indicate an internal bug in Graphene. So maybe also add `assert(strhdl->ptr);`.
</blockquote></details>

It's needed.
user can open() new file ,then seek(SEEK_SET, offset),  then write().  At this time, `data->str == NULL` and `strhdl->ptr == offset`.
This line can be simplified to  `newlen = strhdl->ptr + count;`, but hard to understand.
___
*[LibOS/shim/src/fs/str/fs.c, line 144 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0p-ZK94V0PFUgFoCC:-MT3LaiT6xVzbjSv7S0e:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L144)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of memset, you can just replace `malloc()` with `calloc()` above. Please do this.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 188 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0sBfG6nuXDLod8p2Y:-MT3Ldxh74WLPeI0GE88:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L188)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indentation looks wrong. You have 3-space indent here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 45 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0swcaB81N4y5xb4MR:-MT3LvFQDYfVCYSEWol-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of this comment? There is only one caller for this function. I suggest to remove this comment.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 47 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0tN0O55m7IRST67cO:-MT3baMYAaglSdix5Upz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sizeof(struct shim_tmpfs_data)` -> `sizeof(*data)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 65 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0ttQ_COzKvBRMxEA0:-MT3M6HM232L1xOiZkQV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is useless, please remove it.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 77 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT12xiyAxK3evG1xYqr:-MT3bgOb3GgvD4IFFklw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you should use `NO_MODE` constant here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 81 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0ubkRBROAWl4AIhJf:-MT3cDGm6MEGa2F9hTGa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer a more correct check and simply failing:
```
    uint64_t time = DkSystemTimeQuery();
    if ((int64_t)time < 0) {
        __destroy_data(data);
        return -EPERM;
    }
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 91 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0wZbs2kI8fJe-mVXa:-MT3MiQu2EU2oV-GZ-Ai:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename this function to `get_or_create_tmpfs_data()`? The current name is misleading.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 102 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0wfdMD6fxMraD5rtQ:-MT3NhiGDw7fh9MRMVg2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is racy and generally hard to read. I understand that you copy-pasted it from other part of Graphene, but our FS code is notoriously bad.

In particular, two threads may race on the very first line of code here. You read `dent->data` without the dent lock. So both threads can read NULL and then we'll have two `create_data()` which is wrong. I suggest this version:
```
lock(&dent->lock);
if (!dent->data) {
    int ret = create_data(dent);
    if (ret < 0) {
        unlock(&dent->lock);
        return ret;
    }
}
assert(dent->data);
*dataptr = (struct shim_tmpfs_data*)dent->data;
unlock(&dent->lock);
return 0;
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 124 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0yDeB8BjTAUtkdUaa:-MT3O-L8ClUMhz98LSGK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's split this in two lines for readability:
```
    ret = try_create_data(dent, &data);
    if (ret < 0)
        return ret;
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 130 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0zoQ61hkqLoS3fwBF:-MT3OBVj09iboPbLuDUt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L130)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `#include "perm.h"` at the top and use our macros: `PERM_rwxrwxrwx` in this case.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 137 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0zIYfASC_QtIDtPXN:-MT3P7txCRytDh4eqh-o:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e [...]

2021-02-09 07:26 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 2 of 15 files reviewed, 63 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 418 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT1BnfL3d0T240SItAD:-MT4fNd1AVxKDBTv1EwQ:b-5ik6lr) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L418)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're not using `hdl->dentry`, why do you need an assert here.
</blockquote></details>

Done.  It's copied from other str operations. Now removed.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 421 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT1CHXE5__yJl4Qvgjb:-MT4f8ne3qZropQbDyev:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L421)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All the code below should go into a new function `str_truncate()` inside `str/fs.c`. And you should call this new function here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 454 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT1ChKK736MVvCQSGMk:-MT4fA5F2V5yifWw8fgq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L454)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All this code is exactly the same as in `str_write()`. You should extract it into a new function like `expand_str_buf()` and call it from `str_write()` and `str_truncate()`.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/Makefile, line 23 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT1FY-M3lMEzsabK7nF:-MT4fBDx1bQzdr2rcbSz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/Makefile#L23)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Will change to 
``` 
        delete \
        delete_tmpfs \  
        open_close \
        open_flags \
        read_write \
        seek_tell \
        seek_tell_tmpfs \
        stat \
        stat_tmpfs \
        truncate \
        truncate_tmpfs
```
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/manifest.template, line 40 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT09AoU9NwwzULCTtRE:-MT4fFDvEnbTrRNH5YR_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/manifest.template#L40)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Will remove it.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/README.md, line 20 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT09F964r8bVo7HHfzc:-MT4fHuT4WRCvozyBoJ6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/README.md#L20)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

will be changed to `to test files and folders at a path on tmpfs`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 12:58 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 15 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/fs/str/fs.c, line 137 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT0oQ1B44TWrT5f98_o:-MT5ka5J7IHYGGVTOA4Q:blabyq3) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/str/fs.c#L137)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

It's needed.
user can open() new file ,then seek(SEEK_SET, offset),  then write().  At this time, `data->str == NULL` and `strhdl->ptr == offset`.
This line can be simplified to  `newlen = strhdl->ptr + count;`, but hard to understand.
</blockquote></details>

Ok, true.
___
*[LibOS/shim/src/fs/str/fs.c, line 116 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5kQiM7_Mm95eLbvSR:-MT5kQiM7_Mm95eLbvSS:b-ntk6g) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L116)):*
> ```C
> }
> 
> static ssize_t str_expand_buf(struct shim_str_handle* strhdl, size_t len) {
> ```

Please change the variable name from `len` to `size`
___
*[LibOS/shim/src/fs/str/fs.c, line 116 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5lfrZ518SEvEjNflf:-MT5lfrZ518SEvEjNflg:bq1zihi) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L116)):*
> ```C
> }
> 
> static ssize_t str_expand_buf(struct shim_str_handle* strhdl, size_t len) {
> ```

You don't always expand the buffer in this function. So let's rename it to `str_maybe_expand_buf()`.
___
*[LibOS/shim/src/fs/str/fs.c, line 120 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5kXSM0ns6ZDgG-p4Q:-MT5kXSM0ns6ZDgG-p4R:b1hnc7) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L120)):*
> ```C
> 
>     if (!data->str || len > data->buf_size) {
>         size_t newlen = 0;
> ```

Please change the variable name from `newlen` to `new_size`
___
*[LibOS/shim/src/fs/str/fs.c, line 132 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5lK1v6Z2xfg5C2Krd:-MT5lK1w9S_34LMIM8hq:be9efm0) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L132)):*
> ```C
>         }
> 
>         char* newbuf = calloc(1, newlen);
> ```

Please rename `newbuf` to `new_data_str`
___
*[LibOS/shim/src/fs/str/fs.c, line 223 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5mFMACZ6nacuubuCE:-MT5mFMACZ6nacuubuCF:blnc0fu) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L223)):*
> ```C
> 
>     if (!(hdl->acc_mode & MAY_WRITE))
>         return -EINVAL;
> ```

Why EINVAL? It should be EACCES (see `man 2 truncate`).
___
*[LibOS/shim/src/fs/str/fs.c, line 237 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5mcVY5WrLQBwOuebf:-MT5mcVZ44Jez8XcWSth:b-rpe1za) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L237)):*
> ```C
>         return ret;
> 
>     data->len = len;
> ```

Shouldn't you also add `data->dirty = true;`?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 223 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT16YfU05q3rxL-DB-9:-MT5oNAOBYiOYxaJEZ6C:bpnb4kv) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L223)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

open(O_CREAT) new file then read() should return 0.   Current str_read() returns -EACCES.  I also update str_read() to return 0. Done.
</blockquote></details>

OK. Thanks, this is a good catch and a good fix.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 359 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT1AMZX0SOGSIUCfPib:-MT5qikf0wzdunQosuBI:bv56fo0) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L359)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

`data->type == FILE_DIR`is true only when there is already a dir with same name.  `data` is created by previous `mkdir()`, Should not `destry_data`.
</blockquote></details>

OK, makes sense.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 383 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT1B8xNAkm5l5wUIH6l:-MT5qrbo1swB4sPO8LGs:bv56fo0) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/src/fs/tmpfs/fs.c#L383)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

`data->type != FILE_UNKNOWN`is true only when there is already a dir or file with same name.  `data` is created by previous `mkdir()`or `creat()`, Should not `destry_data`.
</blockquote></details>

OK, makes sense.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 226 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5npQk8CkS7_3Svm3V:-MT5npQk8CkS7_3Svm3W:b-i4p22) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L226)):*
> ```C
> 
>     ssize_t ret = str_read(hdl, buf, count);
>     /* don't udpate access time for performance on Linux-SGX host. */
> ```

Typo: `update`. Actually, a slightly better wording:
```
/* technically, we should update access time here, but we skip this because it
  * could hurt performance on Linux-SGX host */
```
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 244 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5ocCf4YkX6Zh1uRNl:-MT5ocCf4YkX6Zh1uRNm:b-kk6nio) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L244)):*
> ```C
>     lock(&hdl->lock);
>     ssize_t ret = str_write(hdl, buf, count);
>     unlock(&hdl->lock);
> ```

You added locking here. This sounds correct (according to `man 2 write: BUGS`). But you should also add locking to `tmpfs_read()` and to `tmpfs_truncate()`. I am not sure about the other functions in this file...

Also, I think you should `unlock()` right-before return, to cover `ctime` and `mtime` modifications.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 255 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5puAv8FVCj0b3K4JN:-MT5puAv8FVCj0b3K4JO:bg9wsoa) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L255)):*
> ```C
> }
> 
> /* TODO: tmpfs_mmap() function is not implemented because shim_do_mmap() and shim_do_unmap()
> ```

Typo: `shim_do_munmap()`
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 360 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5qH55DOlGbWbibq63:-MT5qH55DOlGbWbibq64:bm5j1h6) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L360)):*
> ```C
>     int ret = 0;
>     if (!hdl)
>         return 0;
> ```

Btw, why does it return `0`? Why not error code?
___
*[LibOS/shim/test/fs/manifest.template, line 28 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT095uA4le3Ff-mcEke:-MT5rNPt5eu3PeMNATqC:bo9s3z6) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/manifest.template#L28)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

It is required by the current tmpfs design.
</blockquote></details>

I don't understand. @llly Could you help in explaining why `uri` is needed?


<!-- Sent from [...]

2021-02-10 02:49 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 6 of 18 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/str/fs.c, line 116 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5kQiM7_Mm95eLbvSR:-MT8bspk5OTi-5e1ySKX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change the variable name from `len` to `size`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 116 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5lfrZ518SEvEjNflf:-MT8bu_H6-f-ao96d5K9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't always expand the buffer in this function. So let's rename it to `str_maybe_expand_buf()`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 120 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5kXSM0ns6ZDgG-p4Q:-MT8bvMf-SsaoJ7xlw7H:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change the variable name from `newlen` to `new_size`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 132 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5lK1v6Z2xfg5C2Krd:-MT8bx9y6P273-J7TAm_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L132)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename `newbuf` to `new_data_str`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 223 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5mFMACZ6nacuubuCE:-MT8by2oBT2SHIksnP9b:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L223)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why EINVAL? It should be EACCES (see `man 2 truncate`).
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 237 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5mcVY5WrLQBwOuebf:-MT8c8pr0ytN-gYU079T:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/str/fs.c#L237)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't you also add `data->dirty = true;`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 226 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5npQk8CkS7_3Svm3V:-MT8cVrGAToPciQvWuS2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `update`. Actually, a slightly better wording:
```
/* technically, we should update access time here, but we skip this because it
  * could hurt performance on Linux-SGX host */
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 244 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5ocCf4YkX6Zh1uRNl:-MT8dM6P5WSo-DP-Krpg:b7onq98) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You added locking here. This sounds correct (according to `man 2 write: BUGS`). But you should also add locking to `tmpfs_read()` and to `tmpfs_truncate()`. I am not sure about the other functions in this file...

Also, I think you should `unlock()` right-before return, to cover `ctime` and `mtime` modifications.
</blockquote></details>

Done.  Move unlock() to return point and also add lock to tmpfs_read(). tmpfs_truncate() already has lock.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 255 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5puAv8FVCj0b3K4JN:-MT8dwk8EDfKVenf6HrU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `shim_do_munmap()`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 360 at r9](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT5qH55DOlGbWbibq63:-MT8f5O6Ct69FX9tutI7:bmx3hu5) ([raw file](https://github.com/oscarlab/graphene/blob/40878561e08a86b6cd395d421d4d1a78a478d125/LibOS/shim/src/fs/tmpfs/fs.c#L360)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, why does it return `0`? Why not error code?
</blockquote></details>

`hdl` is created before calling `tmpfs_creat`. Change to `assert` here.
___
*[LibOS/shim/test/fs/manifest.template, line 28 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT095uA4le3Ff-mcEke:-MT4fCGC9wYJgSuOLlNy:bl5856e) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/manifest.template#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand. @llly Could you help in explaining why `uri` is needed?
</blockquote></details>

https://github.com/oscarlab/graphene/blob/a06b93d8dc007428bd40a1a59bf8e1938607605c/LibOS/shim/src/fs/shim_fs.c#L188-L191

 `type`, `path` and `uri` must match in current `__mount_one_other()` checking. I don't want to change this logic since it should not care what `type` it is.
So user has to add `uri` in manifest though tmpfs doesn't use it.


<!-- Sent from Reviewable.io -->

2021-02-10 08:53 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 18 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/test/fs/.gitignore, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA2dqSCkIs82zxH3TC:-MTA2dqSCkIs82zxH3TD:bl2528h) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/.gitignore#L20)):*
> ```ignore
> /stat
> /truncate
> /copy_subdir_tmpfs
> ```

Please add an empty line before this, to visually separate this new "tmpfs" group of ignored files
___
*[LibOS/shim/test/fs/common.c, line 172 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA6SjY-tYWhwbDvwFG:-MTA6SjY-tYWhwbDvwFH:bfb8x2n) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/common.c#L172)):*
> ```C
> }
> 
> void copy_file_tmpfs(const char* input_path, const char* output_path) {
> ```

Sorry that I haven't looked at the tests before.

The test code in this PR is 99% copy-paste from other `LibOS/shim/test/fs/` files. We should remove all this duplication . E.g., `copy_file_tmpfs()` function is exactly the same as `common_copy.c: copy_file()` with `copy_whole.c: copy_data()`.

I think you should do this:
1. Remove all these changes in `common.c` and all new files `*_tmpfs.c`.
2. Keep `tmpfs-test` changes in the Makefile.
3. Keep changes in the `manifest.template`.
4. Use inherited member functions in `test_tmpfs.py` as much as possible, don't duplicate the code (I think you only need to change `setUpClass` and `tearDownClass` like you have now). Also, you will need to add `@expectedFailureIf(HAS_SGX)` to all mmap tests (since mmap is currently not implemented in tmpfs).
___
*[LibOS/shim/test/fs/manifest.template, line 28 at r7](https://reviewable.io/reviews/oscarlab/graphene/2124#-MT095uA4le3Ff-mcEke:-MTA25kA2dL008dlWyH1:b-c8fq8i) ([raw file](https://github.com/oscarlab/graphene/blob/7681b73c07485876e674430a2da6519df47b0abb/LibOS/shim/test/fs/manifest.template#L28)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

https://github.com/oscarlab/graphene/blob/a06b93d8dc007428bd40a1a59bf8e1938607605c/LibOS/shim/src/fs/shim_fs.c#L188-L191

 `type`, `path` and `uri` must match in current `__mount_one_other()` checking. I don't want to change this logic since it should not care what `type` it is.
So user has to add `uri` in manifest though tmpfs doesn't use it.
</blockquote></details>

Now I got it. Thanks.
___
*[LibOS/shim/test/fs/manifest.template, line 28 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA2B8c4cvsGxJeV2cv:-MTA2B8c4cvsGxJeV2cw:b-ra5qcq) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/manifest.template#L28)):*
> ```
> fs.mount.tmpfs.type = "tmpfs"
> fs.mount.tmpfs.path = "/mnt-tmpfs"
> fs.mount.tmpfs.uri = "file:tmpfs"
> ```

Since `uri` is not really used by tmpfs, can we change the filename to an explicit dummy filename? Like this:
```
fs.mount.tmpfs.uri = "file:dummy-unused-by-tmpfs-uri"
```


<!-- Sent from Reviewable.io -->

2021-02-18 06:08 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 18 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/test/fs/.gitignore, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA2dqSCkIs82zxH3TC:-MTnaw6v9B4iVuD-IKny:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/.gitignore#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line before this, to visually separate this new "tmpfs" group of ignored files
</blockquote></details>

OK
___
*[LibOS/shim/test/fs/manifest.template, line 28 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA2B8c4cvsGxJeV2cv:-MTnZogn97YOXb349y7G:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/manifest.template#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since `uri` is not really used by tmpfs, can we change the filename to an explicit dummy filename? Like this:
```
fs.mount.tmpfs.uri = "file:dummy-unused-by-tmpfs-uri"
```
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-02-22 07:46 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 18 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/test/fs/common.c, line 172 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA6SjY-tYWhwbDvwFG:-MU7fSdW94tD7eW5DrBp:bqg4imi) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/common.c#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry that I haven't looked at the tests before.

The test code in this PR is 99% copy-paste from other `LibOS/shim/test/fs/` files. We should remove all this duplication . E.g., `copy_file_tmpfs()` function is exactly the same as `common_copy.c: copy_file()` with `copy_whole.c: copy_data()`.

I think you should do this:
1. Remove all these changes in `common.c` and all new files `*_tmpfs.c`.
2. Keep `tmpfs-test` changes in the Makefile.
3. Keep changes in the `manifest.template`.
4. Use inherited member functions in `test_tmpfs.py` as much as possible, don't duplicate the code (I think you only need to change `setUpClass` and `tearDownClass` like you have now). Also, you will need to add `@expectedFailureIf(HAS_SGX)` to all mmap tests (since mmap is currently not implemented in tmpfs).
</blockquote></details>

I am trying to do what you suggested, but a major difference of tmpfs usage other than regular fs is that the temporary folder will be lost after running each Python command or binary. It seems not possible to do the testing like deleting or the verification of copying result, in the way of the existing Pytest script.  


<!-- Sent from Reviewable.io -->

2021-02-22 08:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 18 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @jinghe-INTC, and @yamahata)

___
*[LibOS/shim/test/fs/common.c, line 172 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA6SjY-tYWhwbDvwFG:-MU7lqUO6FJSq77umbah:b3ub304) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/common.c#L172)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

I am trying to do what you suggested, but a major difference of tmpfs usage other than regular fs is that the temporary folder will be lost after running each Python command or binary. It seems not possible to do the testing like deleting or the verification of copying result, in the way of the existing Pytest script.  
</blockquote></details>

Yes, it is impossible to verify the copy/deletion of tmpfs files in the Pytest script. Then just don't do this verification (you don't do it now in your tests, right?).

Let's start with removing the current copy-paste code, and then we'll think of how to add verification "does the copied file contain the right data?". Right now it's hard to read this PR because of all the copy-paste.


<!-- Sent from Reviewable.io -->

2021-02-23 02:34 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 6 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/test/fs/common.c, line 172 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA6SjY-tYWhwbDvwFG:-MUBdPF4442EB34kDYYj:b-7wgxxg) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/common.c#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, it is impossible to verify the copy/deletion of tmpfs files in the Pytest script. Then just don't do this verification (you don't do it now in your tests, right?).

Let's start with removing the current copy-paste code, and then we'll think of how to add verification "does the copied file contain the right data?". Right now it's hard to read this PR because of all the copy-paste.
</blockquote></details>

Yes. For open_close, read_write, and all copy related test cases, the verification of the result files have been skipped for now. 

And I am thinking about copying data back to regular file system, and then do the comparation with the original copy.

For test cases like seek_tell, delete, stat, and truncate, it is necessary to prepare the data files on the tmpfs folder within the same process, which was impossible to be done by Python either.   

It looks we still have to write some C code, but avoiding copy-paste existing code.


<!-- Sent from Reviewable.io -->

2021-02-23 08:02 UTC, dimakuv requested changes
> Reviewed 5 of 12 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrBiaEcFz1OpaWfGf:-MUCrBiaEcFz1OpaWfGg:b7ieki3) (no related file):*
for testing in our automated Jenkins, please add a line `make tmpfs-test` in this file after this line: https://github.com/oscarlab/graphene/blob/master/.ci/lib/stage-test.jenkinsfile#L50

---
___
*[LibOS/shim/test/fs/common.c, line 172 at r11](https://reviewable.io/reviews/oscarlab/graphene/2124#-MTA6SjY-tYWhwbDvwFG:-MUCu6ZZ9JBSv-Gyw5Nv:b-xvqe7y) ([raw file](https://github.com/oscarlab/graphene/blob/26e8a5f69a2e1670b6b4796587198c75f4d88124/LibOS/shim/test/fs/common.c#L172)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Yes. For open_close, read_write, and all copy related test cases, the verification of the result files have been skipped for now. 

And I am thinking about copying data back to regular file system, and then do the comparation with the original copy.

For test cases like seek_tell, delete, stat, and truncate, it is necessary to prepare the data files on the tmpfs folder within the same process, which was impossible to be done by Python either.   

It looks we still have to write some C code, but avoiding copy-paste existing code.


</blockquote></details>

Thanks for the update in this PR! This is what I wanted. I left some comments in the new version, please update the PR accordingly.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 34 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrQLH-DuLTqlh_twu:-MUCrQLH-DuLTqlh_twv:b-u3k2bn) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L34)):*
> ```Python
>         for i in cls.INDEXES:
>             with open(cls.INPUT_FILES[i], 'wb') as file:
>                 file.write(os.urandom(cls.FILE_SIZES[i]))
> ```

So what you're doing here is:
1. You create real regular files under `tmp/`
2. You make the output dir (`OUTPUT_DIR`) as your tmpfs `/mnt-tmpfs/`

So it looks like your intention is to create some real input files and then copy/stat/rm them in the ephemeral tmpfs directory. Is my understanding correct?
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 38 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrsH5CzPb3Lf9SHcy:-MUCrsH5CzPb3Lf9SHcz:b96cwr2) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L38)):*
> ```Python
>     def setUp(self):
>         # clean output for each test
>         shutil.rmtree(self.OUTPUT_DIR, ignore_errors=True)
> ```

There is no reason for this command, the `/mnt-tmpfs` directory is only visible inside Graphene and never on the host. Please remove.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 44 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs8_A6110C81Vg4z9:-MUCs8_B04L-WyDeTTfC:b-f803yl) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L44)):*
> ```Python
>         input_path = self.INPUT_FILES[-1] # existing file
>         output_path = os.path.join(self.OUTPUT_DIR, 'test_100') # new file to be created
>         stdout, stderr = self.run_binary(['open_close', 'R', input_path])
> ```

What is the point of this test? This will **not** use the tmpfs because you're only looking at the `input_path` file which is under real directory `tmp/`.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 64 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsXV3Ed9jNUmC83qb:-MUCsXV3Ed9jNUmC83qc:ba1mj89) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L64)):*
> ```Python
>         self.assertIn('close(' + file_path + ') RW OK', stdout)
> 
>     # will decide to drop or enchance it for tmpfs
> ```

Please prepend `TODO: ` here
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 69 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsZRW57tJlQATD1hV:-MUCsZRW57tJlQATD1hW:ba1mj89) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L69)):*
> ```Python
>         TC_00_FileSystem.test_115_seek_tell(self)
> 
>     # will decide to drop or enchance it for tmpfs
> ```

Please prepend `TODO: ` here
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 74 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs_0L2RxezFbtTyVM:-MUCs_0L2RxezFbtTyVN:ba1mj89) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L74)):*
> ```Python
>         TC_00_FileSystem.test_120_file_delete(self)
> 
>     # will decide to drop or enchance it for tmpfs
> ```

Please prepend `TODO: ` here
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 79 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs_hB-4zEUL_XGamp:-MUCs_hB-4zEUL_XGamq:ba1mj89) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L79)):*
> ```Python
>         TC_00_FileSystem.test_130_file_stat(self)
> 
>     # will decide to drop or enchance it for tmpfs
> ```

Please prepend `TODO: ` here
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 85 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsuZz9uf4-6vkP_ci:-MUCsuZz9uf4-6vkP_cj:b-7itg1q) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L85)):*
> ```Python
> 
>     # overrides TC_00_FileSystem to skip verification by python
>     def verify_copy(self, stdout, stderr, input_dir, executable):
> ```

It looks like the only difference from `test_fs.py: verify_copy()` is in these lines: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/test/fs/test_fs.py#L276-L278


So why not re-define the `verify_copy_content()` function instead? You will define it in this file like this:
```
    # overrides TC_00_FileSystem to skip verification of file contents by python
    def verify_copy_content(self, input_path, output_path):
        pass
```

And then you won't need to copy-paste the `verify_copy()` function in this file.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 115 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCt__t5fowmaQWpx6b:-MUCt__t5fowmaQWpx6c:bv997yg) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L115)):*
> ```Python
>             self.assertIn('close(' + size + ') output OK', stdout)
> 
>     def test_200_copy_dir_whole(self):
> ```

There is no need to define this function, it will be called automatically in the parent class. Please remove.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 118 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCte0FC2j3r4SCl8oI:-MUCte0FC2j3r4SCl8oJ:bv997yg) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L118)):*
> ```Python
>         TC_00_FileSystem.test_200_copy_dir_whole(self)
> 
>     def test_201_copy_dir_seq(self):
> ```

There is no need to define this function, it will be called automatically in the parent class. Please remove.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 121 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCte_H-seLdyYf8I2_:-MUCte_H-seLdyYf8I2a:bv997yg) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L121)):*
> ```Python
>         TC_00_FileSystem.test_201_copy_dir_seq(se [...]

2021-02-24 00:55 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrBiaEcFz1OpaWfGf:-MUGTu3C-YZxkv5DOqpC:b32w0x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

for testing in our automated Jenkins, please add a line `make tmpfs-test` in this file after this line: https://github.com/oscarlab/graphene/blob/master/.ci/lib/stage-test.jenkinsfile#L50
</blockquote></details>

OK

---
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 34 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrQLH-DuLTqlh_twu:-MUGU6_X3Qp6604878XB:b-qnjn0x) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So what you're doing here is:
1. You create real regular files under `tmp/`
2. You make the output dir (`OUTPUT_DIR`) as your tmpfs `/mnt-tmpfs/`

So it looks like your intention is to create some real input files and then copy/stat/rm them in the ephemeral tmpfs directory. Is my understanding correct?
</blockquote></details>

Yes. I plan to take the files from tmp/input/ as source for delete/truncate/stat test in the future implementation.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 38 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrsH5CzPb3Lf9SHcy:-MUGUE1m9EBSWF-I65fT:b-513y0) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no reason for this command, the `/mnt-tmpfs` directory is only visible inside Graphene and never on the host. Please remove.
</blockquote></details>

OK. But I still need to override the setup function with ‘pass’, otherwise it will try to create ‘/mnt-tmpfs’ and get failure.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 44 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs8_A6110C81Vg4z9:-MUGUNHxCn3aFqaiGmOa:b-jk7gj5) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the point of this test? This will **not** use the tmpfs because you're only looking at the `input_path` file which is under real directory `tmp/`.
</blockquote></details>

OK. I remove the lines with ‘input_path’.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 64 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsXV3Ed9jNUmC83qb:-MUGUXKE-qRzpjDBTtPL:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend `TODO: ` here
</blockquote></details>

OK
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 69 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsZRW57tJlQATD1hV:-MUGUYUFEDnWjJfPB8I_:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend `TODO: ` here
</blockquote></details>

OK
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 74 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs_0L2RxezFbtTyVM:-MUGUZER860lADcB7NtH:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend `TODO: ` here
</blockquote></details>

OK
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 79 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs_hB-4zEUL_XGamp:-MUGU_240utQ2-ojH4BJ:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend `TODO: ` here
</blockquote></details>

OK
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 85 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsuZz9uf4-6vkP_ci:-MUGUa6RCk7MQr4GB09f:b-uhmktj) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It looks like the only difference from `test_fs.py: verify_copy()` is in these lines: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/test/fs/test_fs.py#L276-L278


So why not re-define the `verify_copy_content()` function instead? You will define it in this file like this:
```
    # overrides TC_00_FileSystem to skip verification of file contents by python
    def verify_copy_content(self, input_path, output_path):
        pass
```

And then you won't need to copy-paste the `verify_copy()` function in this file.
</blockquote></details>

OK. I remove the overrided verify_copy() and use the above verify_copy_content().
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 115 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCt__t5fowmaQWpx6b:-MUGUj2nAuaV7q-GshK6:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L115)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need to define this function, it will be called automatically in the parent class. Please remove.
</blockquote></details>

OK.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 118 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCte0FC2j3r4SCl8oI:-MUGWzkGB1p4uZQ0wTK0:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L118)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need to define this function, it will be called automatically in the parent class. Please remove.
</blockquote></details>

OK.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 121 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCte_H-seLdyYf8I2_:-MUGUk8mDMsDBxlXZGt1:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need to define this function, it will be called automatically in the parent class. Please remove.
</blockquote></details>

OK.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 124 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCtf5j-013sjc8q5sw:-MUGUl1t-uzSQT3OiGz0:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L124)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need to define this function, it will be called automatically in the parent class. Please remove.
</blockquote></details>

OK.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 127 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCthGpD3jnC-LOdQLt:-MUGWRIz3nkUxzUNEIms:b2nhktp) ([raw file] [...]

2021-02-24 01:17 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 11 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrBiaEcFz1OpaWfGf:-MUGb5mUDVLwxtcSNjS4:b-896fix) (no related file):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 34 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrQLH-DuLTqlh_twu:-MUGahot0NfEwZcnzigC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L34)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Yes. I plan to take the files from tmp/input/ as source for delete/truncate/stat test in the future implementation.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 38 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrsH5CzPb3Lf9SHcy:-MUGagFqD1gZCv3hAl5x:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L38)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK. But I still need to override the setup function with ‘pass’, otherwise it will try to create ‘/mnt-tmpfs’ and get failure.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 44 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs8_A6110C81Vg4z9:-MUGafi30VmI-j62IoOk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L44)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK. I remove the lines with ‘input_path’.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 64 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsXV3Ed9jNUmC83qb:-MUGaf7W1AYmm-FTKo-f:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L64)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 69 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsZRW57tJlQATD1hV:-MUGaedE6KQTq2kEN_r7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L69)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 74 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs_0L2RxezFbtTyVM:-MUGaeA38n7l1Xwx0-ZN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L74)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 79 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCs_hB-4zEUL_XGamp:-MUGadflAnrNvlAJmkJq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L79)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 85 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCsuZz9uf4-6vkP_ci:-MUGad9iAIy8uq31cnal:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L85)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK. I remove the overrided verify_copy() and use the above verify_copy_content().
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 115 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCt__t5fowmaQWpx6b:-MUGac3a7yxRYRMBXX_x:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L115)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 118 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCte0FC2j3r4SCl8oI:-MUGabZ22C-lPqIAJJLB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L118)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 121 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCte_H-seLdyYf8I2_:-MUGab3S1n1QeWK0Z58E:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L121)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 124 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCtf5j-013sjc8q5sw:-MUGaaIW9VPvEXXanHAH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L124)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 127 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCthGpD3jnC-LOdQLt:-MUGa_k-BrIHSWfukvcb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L127)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 131 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCtkbu4502ugaaz0Xw:-MUGa_8kCCTxC7a7A-6B:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L131)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

OK.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 135 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCtl7f8xTqsjaRZSbY:-MUGaZIb6cT7mUy8lN0O:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L135)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Ok.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 140 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCtvygAbJkVlixcLzQ:-MUGaVOx--9olq7_LmiO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L140)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

The test of '/mounted' seems  inapplicable for tmpfs. I will skip it with overriding and skipping command.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-24 09:30 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/test/fs/test_tmpfs.py, line 38 at r12](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUCrsH5CzPb3Lf9SHcy:-MUIM4XM9JcNAg2bsPBS:b2jcqbx) ([raw file](https://github.com/oscarlab/graphene/blob/41449cd779724190281fcba0957e093e0f3b9fde/LibOS/shim/test/fs/test_tmpfs.py#L38)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK, thanks, makes sense.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 82 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMZe_6XpLZohifEFQ:-MUIMZea-sfkt_eYIt_e:bamo2ti) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L82)):*
> ```Python
>         pass
> 
>     # mmap is not yet implemented in tmpfs
> ```

Now you have the comment twice :) Please remove this Python comment, so that only `skip("...")` comment stays.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 87 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMfG48ku_bI3MrU2z:-MUIMfG48ku_bI3MrU3-:bamo2ti) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L87)):*
> ```Python
>         TC_00_FileSystem.test_204_copy_dir_mmap_whole(self)
> 
>     # mmap is not yet implemented in tmpfs
> ```

Now you have the comment twice :) Please remove this Python comment, so that only `skip("...")` comment stays.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 92 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMgC04Ee95Upk2yKb:-MUIMgC04Ee95Upk2yKc:bamo2ti) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L92)):*
> ```Python
>         TC_00_FileSystem.test_205_copy_dir_mmap_seq(self)
> 
>     # mmap is not yet implemented in tmpfs
> ```

Now you have the comment twice :) Please remove this Python comment, so that only `skip("...")` comment stays.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 97 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMl1f9bRVu3lYpFbH:-MUIMl1f9bRVu3lYpFbI:b1g8fuy) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L97)):*
> ```Python
>         TC_00_FileSystem.test_206_copy_dir_mmap_rev(self)
> 
>     # overrides TC_00_FileSystem to skip it
> ```

No reason for this comment as you already have a comment inside `unittest.skip()`. So delete this line.


<!-- Sent from Reviewable.io -->

2021-02-25 00:51 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 11 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/test/fs/test_tmpfs.py, line 82 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMZe_6XpLZohifEFQ:-MULde9z5oPmRWaqDhGh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have the comment twice :) Please remove this Python comment, so that only `skip("...")` comment stays.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 87 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMfG48ku_bI3MrU2z:-MULdg2FAYVV7Hm1GSSR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have the comment twice :) Please remove this Python comment, so that only `skip("...")` comment stays.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 92 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMgC04Ee95Upk2yKb:-MULdi0GEnWbehwrpmx-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have the comment twice :) Please remove this Python comment, so that only `skip("...")` comment stays.
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 97 at r14](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUIMl1f9bRVu3lYpFbH:-MULdlkv4sh9wdRtGeYT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a74615f6e70fe79a8a2a2f8dbb3639cb32132f8/LibOS/shim/test/fs/test_tmpfs.py#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No reason for this comment as you already have a comment inside `unittest.skip()`. So delete this line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 07:55 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r15, 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 193 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUNAnUN4PuTrFky4ArK:-MUNAnUOBf-KH_TAC73Z:b-lt471s) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L193)):*
> ```C
>     /* Don't destroy data when DENTRY_NEGATIVE. Renamed dent is using this data. */
>     if (!(dent->state & DENTRY_NEGATIVE))
>         __destroy_data(tmpfs_data);
> ```

This new change won't be needed if you implement the renaming as I suggested below (unless I'm missing something).
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUN98yu9HkANPb1yL1A:bk660uk) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
> ```C
>         old->data = NULL;
>         old->mode = NO_MODE;
>     }
> ```

This new change is really convoluted. I see the bug you had, but why did you fix it this way?

I think what we actually need to do is to increment the refcount on the `old->data` (this tells Graphene "hey, this data is used by two files now").

So ideally we should have smth like this:
```
    __destroy_data(tmpfs_data); /* clean new dentry's data if any */

    assert(REF_GET(old->ref_count) > 0); /* old file must be existing, otherwise some bug */
    REF_INC(old->data->str_data.ref_count); /* both new and old file use this string from now on */
    new->data = old->data;
    new->mode = old->mode;
    new->type = old->type;
    old->state |= DENTRY_NEGATIVE; /* mark old file as non-existing now, after renaming */
```


<!-- Sent from Reviewable.io -->

2021-02-25 08:36 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 193 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUNAnUN4PuTrFky4ArK:-MUNK3H88VfMo4GwmGP0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L193)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This new change won't be needed if you implement the renaming as I suggested below (unless I'm missing something).
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUNK9AJ04AdX7OmKx5g:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This new change is really convoluted. I see the bug you had, but why did you fix it this way?

I think what we actually need to do is to increment the refcount on the `old->data` (this tells Graphene "hey, this data is used by two files now").

So ideally we should have smth like this:
```
    __destroy_data(tmpfs_data); /* clean new dentry's data if any */

    assert(REF_GET(old->ref_count) > 0); /* old file must be existing, otherwise some bug */
    REF_INC(old->data->str_data.ref_count); /* both new and old file use this string from now on */
    new->data = old->data;
    new->mode = old->mode;
    new->type = old->type;
    old->state |= DENTRY_NEGATIVE; /* mark old file as non-existing now, after renaming */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-25 09:05 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUNQiJO4ljVIVxfKYhD:b-s3lg52) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just to make sure: did you re-run the test case where this broke previously? Does this new code fix the issue?


<!-- Sent from Reviewable.io -->

2021-02-26 01:30 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUQu5Dr-S3H4iNTE66S:bndr68y) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just to make sure: did you re-run the test case where this broke previously? Does this new code fix the issue?
</blockquote></details>

Yes. I tested this change.  But I just recognized that  `REF_INC(old->data->str_data.ref_count);` is not needed. It blocks `str_data` free since there is not a  corresponding `REF_DEC`. 
Keeping `old->data` instead  of NULL it is enough.  I tested this and it works. Will commit.


<!-- Sent from Reviewable.io -->

2021-02-26 07:32 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r18.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUSEf-yATO2t5_jgTXG:b-risfh5) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Yes. I tested this change.  But I just recognized that  `REF_INC(old->data->str_data.ref_count);` is not needed. It blocks `str_data` free since there is not a  corresponding `REF_DEC`. 
Keeping `old->data` instead  of NULL it is enough.  I tested this and it works. Will commit.


</blockquote></details>

Sorry, I don't understand how this works.

We have two objects: `old` and `new` dentries. Each of them has a reference to separate objects `old->data` and `new->data`. In your new code, both `old->data` and `new->data` point to the same underlying object (of type `struct shim_tmpfs_data`). At the same time, you don't increment the refcount of this object (`old->data->str_data.ref_count`). So you have two dentries pointing to the same one `shim_tmpfs_data` object, but the refcount of this object is `1`. Isn't it a bug?

I thought that the code I suggested was correct... What am I missing in these rename flows?


<!-- Sent from Reviewable.io -->

2021-02-26 08:13 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUSH_iE14bms-S9YWLj:brjjsdg) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I don't understand how this works.

We have two objects: `old` and `new` dentries. Each of them has a reference to separate objects `old->data` and `new->data`. In your new code, both `old->data` and `new->data` point to the same underlying object (of type `struct shim_tmpfs_data`). At the same time, you don't increment the refcount of this object (`old->data->str_data.ref_count`). So you have two dentries pointing to the same one `shim_tmpfs_data` object, but the refcount of this object is `1`. Isn't it a bug?

I thought that the code I suggested was correct... What am I missing in these rename flows?
</blockquote></details>

I explain my thought here.

In one sentence,  new dentry is not opened when rename(), should not increase `str_data.ref_count`.

`str_data.ref_count` is increased when open() in str/fs.c line 26 and creat() in line 146.
`str_data.ref_count` is dncreased when close()  and unlink(), both calls dput() in str/fs.c line 37.
So `open(O_CREAT)`  increases `str_data.ref_count` twice.

Here is a scenario:
1. open( "file", O_RDWR|O_CREAT|0x80900, 0600) = 0x6
    * old->data is malloced.
    * old->data.ref_count = 2
2. write(6, 0x3e7fa17b40b0, 0xa35) ...
3. rename("file", "newfile") = 0x0
    * (old|new)->data.ref_count = 2
    * old->state |= DENTRY_NEGATIVE;
4. open("newfile", O_RDONLY|0x80900, 0600) = 0x7
    * REF_INC(new->data->ref_count)
     * new->data.ref_count = 3
5. close(6)
    * REF_DEC(old->data->ref_count)
    * old->data.ref_count = 2
5. unlink("newfile")
    * REF_DEC(new->data->ref_count)
    * new->data.ref_count = 1
4. close(7)
    * REF_DEC(new->data->ref_count)
    * new->data.ref_count = 0
    * new->data is freed.

If increase `data.ref_count` in rename(), ref_count is not 0 and data is not freed at the end.


<!-- Sent from Reviewable.io -->

2021-02-26 08:38 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUST1051Izq2boIr60-:b-8qywb0) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

I explain my thought here.

In one sentence,  new dentry is not opened when rename(), should not increase `str_data.ref_count`.

`str_data.ref_count` is increased when open() in str/fs.c line 26 and creat() in line 146.
`str_data.ref_count` is dncreased when close()  and unlink(), both calls dput() in str/fs.c line 37.
So `open(O_CREAT)`  increases `str_data.ref_count` twice.

Here is a scenario:
1. open( "file", O_RDWR|O_CREAT|0x80900, 0600) = 0x6
    * old->data is malloced.
    * old->data.ref_count = 2
2. write(6, 0x3e7fa17b40b0, 0xa35) ...
3. rename("file", "newfile") = 0x0
    * (old|new)->data.ref_count = 2
    * old->state |= DENTRY_NEGATIVE;
4. open("newfile", O_RDONLY|0x80900, 0600) = 0x7
    * REF_INC(new->data->ref_count)
     * new->data.ref_count = 3
5. close(6)
    * REF_DEC(old->data->ref_count)
    * old->data.ref_count = 2
5. unlink("newfile")
    * REF_DEC(new->data->ref_count)
    * new->data.ref_count = 1
4. close(7)
    * REF_DEC(new->data->ref_count)
    * new->data.ref_count = 0
    * new->data is freed.

If increase `data.ref_count` in rename(), ref_count is not 0 and data is not freed at the end.
</blockquote></details>

Alternative thinking, rename() can be considered as two actions.
1. unlink old dentry 
2. create new dentry  <- this is why you want to increase ref_count

decreasing ref_count and increasing ref_count add up to keeping ref_count.


<!-- Sent from Reviewable.io -->

2021-03-01 08:15 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUgqG7C7r_s-VV67b6i:-MUgqG7C7r_s-VV67b6j:b-pwsjz6) (no related file):*
The PR looks good to me now. @yamahata and maybe @pwmarcz -- could you review this? It would be good to merge this *before* the Big FS Rewrite.

Also, this is the first step in supporting temporary (in-memory-only) files. We'll need to think how to support `mmap()` operation on temporary files (if at all possible, see discussions here). And how to correctly fork and synchronize these files (but this is a problem of the whole FS subsystem of Graphene).

---
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 562 at r16](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUN98yu9HkANPb1yL19:-MUgoUBj55Q_5xC9pYur:b586k7l) ([raw file](https://github.com/oscarlab/graphene/blob/41d37191e5045ddae2dcde6523a8bf865678f6c8/LibOS/shim/src/fs/tmpfs/fs.c#L562)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Alternative thinking, rename() can be considered as two actions.
1. unlink old dentry 
2. create new dentry  <- this is why you want to increase ref_count

decreasing ref_count and increasing ref_count add up to keeping ref_count.

</blockquote></details>

OK. Thanks for the detailed explanation! You are right.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 7 at r18](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUgpP3H7zUeSw1HKEb_:-MUgpP3H7zUeSw1HKEba:b-oms5mt) ([raw file](https://github.com/oscarlab/graphene/blob/bada4e064e95290bd65828f078d7eaf8381247f1/LibOS/shim/src/fs/tmpfs/fs.c#L7)):*
> ```C
> 
> /*
>  * This file contains code for implementation of 'tmpfs' filesystem.
> ```

The current `tmpfs` implementation doesn't keep the temporary files in the child process. Please add a comment like this: `The tmpfs files are *not* cloned during fork/clone and cannot be synchronized between processes`.


<!-- Sent from Reviewable.io -->

2021-03-01 08:16 UTC, dimakuv commented
Jenkins, test this please

2021-03-01 09:18 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/test/fs/test_tmpfs.py, line 6 at r18](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUh45Wd-aLv1y1KO0Ms:-MUh45Wd-aLv1y1KO0Mt:b-64in8y) ([raw file](https://github.com/oscarlab/graphene/blob/bada4e064e95290bd65828f078d7eaf8381247f1/LibOS/shim/test/fs/test_tmpfs.py#L6)):*
> ```Python
> import os
> import shutil
> import unittest
> ```

Our syntax checker complained like this:
```
************* Module test_tmpfs
W:  3, 0: Unused import filecmp (unused-import)
W:  5, 0: Unused import shutil (unused-import)
W:  8, 0: Unused HAS_SGX imported from regression (unused-import)
W:  8, 0: Unused expectedFailureIf imported from regression (unused-import)
```

Please remove unused imports.


<!-- Sent from Reviewable.io -->

2021-03-02 01:07 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/test/fs/test_tmpfs.py, line 6 at r18](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUh45Wd-aLv1y1KO0Ms:-MUkTF003SJrDr0T5iz4:b-2cilaa) ([raw file](https://github.com/oscarlab/graphene/blob/bada4e064e95290bd65828f078d7eaf8381247f1/LibOS/shim/test/fs/test_tmpfs.py#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Our syntax checker complained like this:
```
************* Module test_tmpfs
W:  3, 0: Unused import filecmp (unused-import)
W:  5, 0: Unused import shutil (unused-import)
W:  8, 0: Unused HAS_SGX imported from regression (unused-import)
W:  8, 0: Unused expectedFailureIf imported from regression (unused-import)
```

Please remove unused imports.
</blockquote></details>

Remove lines
```
import filecmp
import shutil

from regression import (
    HAS_SGX,
    expectedFailureIf,
)
```


<!-- Sent from Reviewable.io -->

2021-03-02 01:07 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/test/fs/test_tmpfs.py, line 6 at r18](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUh45Wd-aLv1y1KO0Ms:-MUkTOot-N01Xbrhxhxv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bada4e064e95290bd65828f078d7eaf8381247f1/LibOS/shim/test/fs/test_tmpfs.py#L6)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Remove lines
```
import filecmp
import shutil

from regression import (
    HAS_SGX,
    expectedFailureIf,
)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-02 05:49 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 9 of 11 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 7 at r18](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUgpP3H7zUeSw1HKEb_:-MUlTln15IqEaGP0pegZ:b-8a6u7s) ([raw file](https://github.com/oscarlab/graphene/blob/bada4e064e95290bd65828f078d7eaf8381247f1/LibOS/shim/src/fs/tmpfs/fs.c#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The current `tmpfs` implementation doesn't keep the temporary files in the child process. Please add a comment like this: `The tmpfs files are *not* cloned during fork/clone and cannot be synchronized between processes`.
</blockquote></details>

Done. I'll highlight clone and mmap limitation in documentation in later PR.


<!-- Sent from Reviewable.io -->

2021-03-02 09:49 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r19, 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-02 09:50 UTC, dimakuv commented
Jenkins, test this please

2021-03-02 10:32 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUmUMjW0lBtNHISVeer:-MUmUMjW0lBtNHISVees:b-2ykymy) (no related file):*
@llly Could you check why Jenkins complains and fix it:
```
fs/tmpfs/fs.c: In function 'tmpfs_open':
../include/shim_internal.h:324:22: error: this statement may fall through [-Werror=implicit-fallthrough=]
 #define REF_INC(ref) __ref_inc(&(ref))
                      ^~~~~~~~~~~~~~~~~
fs/tmpfs/fs.c:147:13: note: in expansion of macro 'REF_INC'
             REF_INC(data->str_data.ref_count);
             ^~~~~~~
fs/tmpfs/fs.c:149:9: note: here
         case FILE_REGULAR:
         ^~~~
  [ ipc/shim_ipc_child.o ]
  [ ipc/shim_ipc_helper.o ]
  [ ipc/shim_ipc_pid.o ]
  [ ipc/shim_ipc_ranges.o ]
fs/tmpfs/fs.c: At top level:
cc1: error: unrecognized command line option '-Wno-address-of-packed-member' [-Werror]
```

---


<!-- Sent from Reviewable.io -->

2021-03-02 13:18 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUmUMjW0lBtNHISVeer:-MUn4GjA-7PYo7yX8tZa:b6w391e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@llly Could you check why Jenkins complains and fix it:
```
fs/tmpfs/fs.c: In function 'tmpfs_open':
../include/shim_internal.h:324:22: error: this statement may fall through [-Werror=implicit-fallthrough=]
 #define REF_INC(ref) __ref_inc(&(ref))
                      ^~~~~~~~~~~~~~~~~
fs/tmpfs/fs.c:147:13: note: in expansion of macro 'REF_INC'
             REF_INC(data->str_data.ref_count);
             ^~~~~~~
fs/tmpfs/fs.c:149:9: note: here
         case FILE_REGULAR:
         ^~~~
  [ ipc/shim_ipc_child.o ]
  [ ipc/shim_ipc_helper.o ]
  [ ipc/shim_ipc_pid.o ]
  [ ipc/shim_ipc_ranges.o ]
fs/tmpfs/fs.c: At top level:
cc1: error: unrecognized command line option '-Wno-address-of-packed-member' [-Werror]
```
</blockquote></details>

Done. The error is caused by intended fallthrough. Update the logic to avoid warning/error.

---


<!-- Sent from Reviewable.io -->

2021-03-02 13:26 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 136 at r21](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUn6RvVBxxNthc7kn9q:-MUn6RvVBxxNthc7kn9r:bvlwlal) ([raw file](https://github.com/oscarlab/graphene/blob/9d0af34944f6dfa5e474c5b5df05590b2d4aac96/LibOS/shim/src/fs/tmpfs/fs.c#L136)):*
> ```C
>         tmpfs_update_ino(dent);
>     }
>     if (data->type == FILE_UNKNOWN) {
> ```

Could you add empty lines around this `if (data->type == FILE_UNKNOWN) { }` block? Hard to read without empty lines.


<!-- Sent from Reviewable.io -->

2021-03-02 13:42 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 136 at r21](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUn6RvVBxxNthc7kn9q:-MUnA9eWANA0ex7nxto5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9d0af34944f6dfa5e474c5b5df05590b2d4aac96/LibOS/shim/src/fs/tmpfs/fs.c#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add empty lines around this `if (data->type == FILE_UNKNOWN) { }` block? Hard to read without empty lines.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-02 14:50 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-02 14:50 UTC, dimakuv commented
Jenkins, test this please

2021-03-02 16:07 UTC, pwmarcz reviewed
> Reviewed 1 of 4 files at r8, 1 of 3 files at r9, 3 of 12 files at r12, 1 of 2 files at r13, 3 of 4 files at r18, 1 of 1 files at r19, 1 of 1 files at r22.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUgqG7C7r_s-VV67b6i:-MUnbIio6Bo6wA_BOaX0:b-rgaus7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR looks good to me now. @yamahata and maybe @pwmarcz -- could you review this? It would be good to merge this *before* the Big FS Rewrite.

Also, this is the first step in supporting temporary (in-memory-only) files. We'll need to think how to support `mmap()` operation on temporary files (if at all possible, see discussions here). And how to correctly fork and synchronize these files (but this is a problem of the whole FS subsystem of Graphene).
</blockquote></details>

I took a look and left a few comments. I also did a simple sanity check by running the `python-simple` example, and things seem to work:
```python
import os

print(os.listdir('/mnt-tmpfs'))
with open('/mnt-tmpfs/foo.txt', 'w') as f:
    f.write('hello')
os.mkdir('/mnt-tmpfs/dir')

print(os.listdir('/mnt-tmpfs'))
print(os.stat('/mnt-tmpfs/foo.txt'))
print(os.stat('/mnt-tmpfs/dir'))

with open('/mnt-tmpfs/foo.txt', 'r') as f:
    print(f.read())
```

---
___
*[.ci/lib/stage-test.jenkinsfile, line 51 at r22](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUnX4Hy09xSnir8jFRK:-MUnX4Hy09xSnir8jFRL:bpdhv40) ([raw file](https://github.com/oscarlab/graphene/blob/aa1c34587f4051762514ebcf79b0ef2aca6bc1d7/.ci/lib/stage-test.jenkinsfile#L51)):*
> ```
>             fi
>             make test
>             make tmpfs-test
> ```

Could this be a part of `make test`? Otherwise it's harder to discover for a developer running the tests manually.
___
*[LibOS/shim/src/fs/str/fs.c, line 89 at r22](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUnX_8q7xEFjrV9b9Qf:-MUnX_8q7xEFjrV9b9Qg:b-kr4xbf) ([raw file](https://github.com/oscarlab/graphene/blob/aa1c34587f4051762514ebcf79b0ef2aca6bc1d7/LibOS/shim/src/fs/str/fs.c#L89)):*
> ```C
>     if (!data->str) {
>         log_error("str_data has no str\n");
>         ret = 0;
> ```

If `data->str == NULL` is a valid case now, shouldn't we remove the `log_error`?
___
*[LibOS/shim/test/fs/Makefile, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUnZZ_5BNHWBwawSKoX:-MUnZZ_5BNHWBwawSKoY:b-40l2wv) ([raw file](https://github.com/oscarlab/graphene/blob/aa1c34587f4051762514ebcf79b0ef2aca6bc1d7/LibOS/shim/test/fs/Makefile#L61)):*
> ```Makefile
> 	$(MAKE) fs-test.xml
> 
> .PHONY: tmpfs-test
> ```

As mentioned above: can this be triggered by `make test`? For example, by refactoring it like so:

```make
.PHONY: tmpfs-test
tmpfs-test:  ...

.PHONY: pf-test
pf-test: ...

.PHONY: test
test: tmpfs-test pf-test
```

I see there is some mess in there (`pf-test` actually triggers `fs-test` inside Python?), but so far, `make test` ran all the tests, and I think we should keep that property.


<!-- Sent from Reviewable.io -->

2021-03-02 16:16 UTC, dimakuv commented
Jenkins, retest Jenkins-18.04 please (`send01` LTP test failed, unrelated though I don't remember such test failing)

2021-03-03 05:25 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 11 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/fs/str/fs.c, line 89 at r22](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUnX_8q7xEFjrV9b9Qf:-MUqWqXu0Mu54o6bbV6v:b-vdx0qw) ([raw file](https://github.com/oscarlab/graphene/blob/aa1c34587f4051762514ebcf79b0ef2aca6bc1d7/LibOS/shim/src/fs/str/fs.c#L89)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If `data->str == NULL` is a valid case now, shouldn't we remove the `log_error`?
</blockquote></details>

Done. Changed to log_warning. It's not common to read empty file. 


<!-- Sent from Reviewable.io -->

2021-03-03 05:46 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 11 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, @pwmarcz, and @yamahata)

___
*[LibOS/shim/test/fs/Makefile, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUnZZ_5BNHWBwawSKoX:-MUqbMJDDFUeGWt2il35:b-podj1a) ([raw file](https://github.com/oscarlab/graphene/blob/aa1c34587f4051762514ebcf79b0ef2aca6bc1d7/LibOS/shim/test/fs/Makefile#L61)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

As mentioned above: can this be triggered by `make test`? For example, by refactoring it like so:

```make
.PHONY: tmpfs-test
tmpfs-test:  ...

.PHONY: pf-test
pf-test: ...

.PHONY: test
test: tmpfs-test pf-test
```

I see there is some mess in there (`pf-test` actually triggers `fs-test` inside Python?), but so far, `make test` ran all the tests, and I think we should keep that property.
</blockquote></details>

Done. Update the script, README, and the Jenkins file.


<!-- Sent from Reviewable.io -->

2021-03-03 05:46 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 11 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @pwmarcz, and @yamahata)

___
*[.ci/lib/stage-test.jenkinsfile, line 51 at r22](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUnX4Hy09xSnir8jFRK:-MUqbxPqBlwlwCcnhY3X:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/aa1c34587f4051762514ebcf79b0ef2aca6bc1d7/.ci/lib/stage-test.jenkinsfile#L51)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Could this be a part of `make test`? Otherwise it's harder to discover for a developer running the tests manually.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-03 09:23 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r23, 3 of 3 files at r24.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly, @pwmarcz, and @yamahata)

___
*[LibOS/shim/test/fs/Makefile, line 61 at r22](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUnZZ_5BNHWBwawSKoX:-MUrO_uB4gAmXZGorRK4:bs29mr5) ([raw file](https://github.com/oscarlab/graphene/blob/aa1c34587f4051762514ebcf79b0ef2aca6bc1d7/LibOS/shim/test/fs/Makefile#L61)):*
<details><summary><i>Previously, jinghe-INTC wrote…</i></summary><blockquote>

Done. Update the script, README, and the Jenkins file.
</blockquote></details>

Thanks for fixing this mess!
___
*[LibOS/shim/test/fs/README.md, line 19 at r24](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUrOOfiCPSvbzDqeDPg:-MUrOOfjDmu2e2bNSwql:b4wjy7i) ([raw file](https://github.com/oscarlab/graphene/blob/f6486d283194badd564f5e882dd86244608fbe2f/LibOS/shim/test/fs/README.md#L19)):*
> ```Markdown
> 
> Run `make fs-test` to only test regular files.
> Run `make pf-test` to test regular files and protected files.
> ```

This comment is wrong now. It should be:
```
Run `make pf-test` to only test protected files.
```
___
*[LibOS/shim/test/fs/README.md, line 21 at r24](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUrOWVT-aByGI2v4dJG:-MUrOWVT-aByGI2v4dJH:b9ij9tw) ([raw file](https://github.com/oscarlab/graphene/blob/f6486d283194badd564f5e882dd86244608fbe2f/LibOS/shim/test/fs/README.md#L21)):*
> ```Markdown
> Run `make pf-test` to test regular files and protected files.
> Run `make tmpfs-test` to test files and folders at a path on tmpfs.
> Run `make test` to test all above.
> ```

`to test all above.` -> `to test all of the above.`


<!-- Sent from Reviewable.io -->

2021-03-03 09:32 UTC, dimakuv commented
Jenkins, test this please

2021-03-03 11:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @llly, and @yamahata)

___
*[LibOS/shim/test/fs/README.md, line 19 at r24](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUrOOfiCPSvbzDqeDPg:-MUriDtf31bnr-Wu7kNl:bndfbrz) ([raw file](https://github.com/oscarlab/graphene/blob/f6486d283194badd564f5e882dd86244608fbe2f/LibOS/shim/test/fs/README.md#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This comment is wrong now. It should be:
```
Run `make pf-test` to only test protected files.
```
</blockquote></details>

Unfortunately the comment is still true, because `test_pf.py` imports `test_fs.py` to inherit from a class, and so Pytest runs tests from both files.  And the same applies to `test_tmpfs.py` (so if you run both `test_pf` and `test_tmpfs`, then the tests from `test_fs` run twice).

I don't think it's worth fixing right now; I'm happy with `make test` still doing more or less the right thing.


<!-- Sent from Reviewable.io -->

2021-03-03 13:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[LibOS/shim/test/fs/README.md, line 19 at r24](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUrOOfiCPSvbzDqeDPg:-MUsAZww8JLbGEGo-f0l:b-8k0xhg) ([raw file](https://github.com/oscarlab/graphene/blob/f6486d283194badd564f5e882dd86244608fbe2f/LibOS/shim/test/fs/README.md#L19)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Unfortunately the comment is still true, because `test_pf.py` imports `test_fs.py` to inherit from a class, and so Pytest runs tests from both files.  And the same applies to `test_tmpfs.py` (so if you run both `test_pf` and `test_tmpfs`, then the tests from `test_fs` run twice).

I don't think it's worth fixing right now; I'm happy with `make test` still doing more or less the right thing.
</blockquote></details>

Got it. Please ignore this comment then.


<!-- Sent from Reviewable.io -->

2021-03-04 01:06 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/test/fs/README.md, line 21 at r24](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUrOWVT-aByGI2v4dJG:-MUul5dIAjTcfomO0czJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f6486d283194badd564f5e882dd86244608fbe2f/LibOS/shim/test/fs/README.md#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to test all above.` -> `to test all of the above.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-04 11:08 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r25.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-04 11:08 UTC, dimakuv commented
Jenkins, test this please

2021-03-04 12:37 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`select04` LTP test failed, known issue)

2021-03-04 12:41 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUxFL1qDb_pFj5BRr_a:-MUxFL1qDb_pFj5BRr_b:bozh1ys) (no related file):*
Now that we added the new `tmpfs` tests, 5 minutes is not enough for Jenkins. Could you please increase the timeout from 5 minutes to 15 minutes? Change here: https://github.com/oscarlab/graphene/blob/master/.ci/lib/stage-test.jenkinsfile#L42.

---


<!-- Sent from Reviewable.io -->

2021-03-05 01:04 UTC, jinghe-INTC reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MUxFL1qDb_pFj5BRr_a:-MUzuU26DqRA7B6kVzL3:brgq1k0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now that we added the new `tmpfs` tests, 5 minutes is not enough for Jenkins. Could you please increase the timeout from 5 minutes to 15 minutes? Change here: https://github.com/oscarlab/graphene/blob/master/.ci/lib/stage-test.jenkinsfile#L42.
</blockquote></details>

Sure. Done.

---


<!-- Sent from Reviewable.io -->

2021-03-05 07:51 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r26.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-05 07:51 UTC, dimakuv commented
Jenkins, test this please

2021-03-09 01:23 UTC, llly commented
It  seems that all comments have been addressed. What can I do now?

2021-03-09 12:16 UTC, dimakuv approved these changes
You don't have to do anything. One more person needs to finish reviewing this PR. @pwmarcz Could you review this and request changes/approve it? (When you have time.)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124#-:-MVLuZRW5n0IjxtM7sFj:bpzi61x)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-09 14:14 UTC, pwmarcz reviewed
Sure, I already reviewed it, so I can confirm now that I have approval rights.

> Reviewed 1 of 1 files at r23, 1 of 3 files at r24, 1 of 1 files at r25, 1 of 1 files at r26.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124#-:-MVMKLUx60oE60IqDvoS:buxyf5o)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-18 10:00 UTC, pwmarcz submitted a review, later dismissed
Approving.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124#-:-MW3lkLl-o5QU1sf8jeF:bnjmlxl)* status: all files reviewed, 2 unresolved discussions (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-18 12:49 UTC, mkow reviewed
> Reviewed 1 of 4 files at r8, 10 of 12 files at r12, 2 of 4 files at r18, 1 of 1 files at r19, 1 of 1 files at r22, 1 of 1 files at r23, 1 of 3 files at r24, 1 of 1 files at r25, 1 of 1 files at r26.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 11 unresolved discussions (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4N9HF-6Vlrh8gIf02:-MW4N9HF-6Vlrh8gIf03:bhykwuu) (no related file):*
Please also update documentation (manifest-syntax.rst)

---
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 179 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4J471EWdblHGHgknt:-MW4J471EWdblHGHgknu:b-bs1c2f) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L179)):*
> ```C
> 
>     hdl->acc_mode = ACC_MODE(flags & O_ACCMODE);
>     ret           = 0;
> ```

please remove the alignment
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 232 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4JIjY1lNB0AnjQNi0:-MW4JIjY1lNB0AnjQNi1:b-sohr5w) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L232)):*
> ```C
>     ssize_t ret = str_read(hdl, buf, count);
>     /* technically, we should update access time here, but we skip this because it
>      * could hurt performance on Linux-SGX host */
> ```

please rewrap to 100 chars per line
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 441 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4KKFw7j_Do2V-cIng:-MW4KKFw7j_Do2V-cInh:b-dpiokv) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L441)):*
> ```C
>     int ret                = 0;
>     size_t dirent_buf_size = 0;
>     char* dirent_buf       = NULL;
> ```

please unalign all of these
ditto for the whole PR, except assignments which are structurized (see https://graphene.readthedocs.io/en/latest/devel/coding-style.html#code-formatting)
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 492 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4KpcPBnVUxe8xrDBy:-MW4KpcQEaYvdBpSfKDF:bqcbp7e) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L492)):*
> ```C
> 
> out:
>     /* Need to free output buffer if error is returned */
> ```

no need for this comment, it's obvious (literally every function in Graphene has a similar pattern :) )
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 508 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4L8Py96veh7_-Z2wQ:-MW4L8Py96veh7_-Z2wR:b-kfafa9) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L508)):*
> ```C
>     } else if (tmpfs_data->type == FILE_DIR && dent->nchildren != 0) {
>         struct shim_dentry* tmp = NULL;
>         int nchildren           = 0;
> ```

should be `size_t`
___
*[LibOS/shim/test/fs/Makefile, line 72 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4LfC23xBpsGtW91fu:-MW4LfC23xBpsGtW91fv:b-jygh8v) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/test/fs/Makefile#L72)):*
> ```Makefile
> 
> .PHONY: test
> test: tmpfs-test pf-test
> ```

What about `fs-test`? Seems you accidentally disabled all of them?
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 8 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4Lxug1FUlktNhrTzd:-MW4Lxug1FUlktNhrTze:b-a9m0yh) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/test/fs/test_tmpfs.py#L8)):*
> ```Python
> from test_fs import TC_00_FileSystem
> 
> # Do tmpfs tests.
> ```

please remove, this comment doesn't say anything useful
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 51 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4MTpYEG0CD-B04_oL:-MW4MTpZ020T6aU6gI_6:b-kh5iom) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/test/fs/test_tmpfs.py#L51)):*
> ```Python
>         self.assertIn('close(' + file_path + ') RW OK', stdout)
> 
>     # TODO: will decide to drop or enchance it for tmpfs
> ```

What do you mean by "will decide"? Sounds like something you wanted to discuss in the review, not leave in the code?


<!-- Sent from Reviewable.io -->

2021-03-19 02:44 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 8 of 11 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4N9HF-6Vlrh8gIf02:-MW7GZxYBtbck-ZGP3R-:b37nk5w) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please also update documentation (manifest-syntax.rst)
</blockquote></details>

documentation is in #2223

---
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 179 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4J471EWdblHGHgknt:-MW7H8G8-XOGugnMS8Om:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please remove the alignment
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 232 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4JIjY1lNB0AnjQNi0:-MW7HHyp0xQeb4dnO3l5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L232)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please rewrap to 100 chars per line
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 441 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4KKFw7j_Do2V-cIng:-MW7HhyA-JsrkxtScHoZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L441)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please unalign all of these
ditto for the whole PR, except assignments which are structurized (see https://graphene.readthedocs.io/en/latest/devel/coding-style.html#code-formatting)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 492 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4KpcPBnVUxe8xrDBy:-MW7HlHV28NExp94sodh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L492)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no need for this comment, it's obvious (literally every function in Graphene has a similar pattern :) )
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 508 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4L8Py96veh7_-Z2wQ:-MW7IQXT6ea8ML38ZLlr:b-jvc0su) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L508)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be `size_t`
</blockquote></details>

`dent->nchildren` is `int`. should keep `int`.
___
*[LibOS/shim/test/fs/Makefile, line 72 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4LfC23xBpsGtW91fu:-MW7IiQc4xFAb0VabBUS:btf3ldz) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/test/fs/Makefile#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about `fs-test`? Seems you accidentally disabled all of them?
</blockquote></details>

`fs-test` is already included in `pf-test`. See pwmarcz 's comment in README.md
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 8 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4Lxug1FUlktNhrTzd:-MW7JwqI5mGR7ypSwVKa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/test/fs/test_tmpfs.py#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please remove, this comment doesn't say anything useful
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/test_tmpfs.py, line 51 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4MTpYEG0CD-B04_oL:-MW7KaxJCjxP15-iZhV_:bylbfj6) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/test/fs/test_tmpfs.py#L51)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean by "will decide"? Sounds like something you wanted to discuss in the review, not leave in the code?
</blockquote></details>

decision Done. comment removed.


<!-- Sent from Reviewable.io -->

2021-03-19 03:01 UTC, mkow requested changes
Please don't use merge commits in the future (we'll need to delete them anyway) and instead use `git rebase` if you need to update the base of the PR (but this is generally discouraged during review). See https://graphene.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle.

> Reviewed 5 of 5 files at r27.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124#-:-MW7Oe8G2Fm00-dG88vm:bytxhx8)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4N9HF-6Vlrh8gIf02:-MW7OolnE84b8kSyRadE:bbg10pa) (no related file):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

documentation is in #2223
</blockquote></details>

Could you move the documentation part to this PR? It's quite small, so this will be easy, and logically it makes much more sense IMO (this PR will then contain the core implementation and documentation for it, and #2223 will contain an example).

---
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 508 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4L8Py96veh7_-Z2wQ:-MW7PR4k6ueiaXRnjjND:b-er01r9) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L508)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

`dent->nchildren` is `int`. should keep `int`.
</blockquote></details>

This is a bug in `dent->nchildren` then, so please use `size_t` here. The dentries will be fixed in Paweł's FS rewrite soon and `size_t` will work correctly with both `int` and `size_t` in this case.
___
*[LibOS/shim/test/fs/Makefile, line 72 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4LfC23xBpsGtW91fu:-MW7PuXN8-0j2nQr7n1C:b-9ohbja) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/test/fs/Makefile#L72)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

`fs-test` is already included in `pf-test`. See pwmarcz 's comment in README.md
</blockquote></details>

Ah, I see. We should clean this up later, it's confusing...


<!-- Sent from Reviewable.io -->

2021-03-19 03:43 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 10 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4N9HF-6Vlrh8gIf02:-MW7Yp07E8XSy4IGoV7D:bs7wumx) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you move the documentation part to this PR? It's quite small, so this will be easy, and logically it makes much more sense IMO (this PR will then contain the core implementation and documentation for it, and #2223 will contain an example).
</blockquote></details>

Done. 

---
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 508 at r26](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4L8Py96veh7_-Z2wQ:-MW7Z0pCAi0Rf7DvCvnm:b-f34m7j) ([raw file](https://github.com/oscarlab/graphene/blob/5b8d535be94548b25094b7a595e9abc8902e8165/LibOS/shim/src/fs/tmpfs/fs.c#L508)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is a bug in `dent->nchildren` then, so please use `size_t` here. The dentries will be fixed in Paweł's FS rewrite soon and `size_t` will work correctly with both `int` and `size_t` in this case.
</blockquote></details>

Done. Also change `offset`in `mmap` 


<!-- Sent from Reviewable.io -->

2021-03-19 19:09 UTC, mkow requested changes
> Reviewed 6 of 6 files at r28.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MW4N9HF-6Vlrh8gIf02:-MWAomri0jvvfQKhbBv0:bb6llez) (no related file):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Done. 
</blockquote></details>

I meant only the docs, but whatever, the change in the example is also small so we can merge them together.

---
___
*[Documentation/manifest-syntax.rst, line 277 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWAq_9a-4hnVpjJ9df_:-MWAq_9a-4hnVpjJ9dfa:bf4x7nq) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Documentation/manifest-syntax.rst#L277)):*
> ```
> to a Graphene instance
> ```

I think in this case it should be "the".
___
*[Documentation/manifest-syntax.rst, line 292 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWArrku4qZw3qmrd0dP:-MWArrkvDg0PKn-S5GVr:bjin891) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Documentation/manifest-syntax.rst#L292)):*
> ```
> currently do *not* support mmap and fork/clone
> ```

I'd slightly reword this, because it may be read as "clone doesn't work if you use tmpfs mounts". Maybe just explicitly say that the contents of tmpfs are currently local to each process inside Graphene?
___
*[Examples/lighttpd/lighttpd.manifest.template, line 52 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWAsL2xAbbX8IaloCgp:-MWAsL2xAbbX8IaloCgq:bp4qi9u) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Examples/lighttpd/lighttpd.manifest.template#L52)):*
> ```
> fs.mount.var_tmp.type = "tmpfs"
> fs.mount.var_tmp.path = "/var/tmp"
> fs.mount.var_tmp.uri = "file:dummy-unused-by-tmpfs-uri"
> ```

If this is ignored, why can't we drop this line altogether?


<!-- Sent from Reviewable.io -->

2021-03-22 01:25 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly, @mkow, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 292 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWArrku4qZw3qmrd0dP:-MWMUe9v2nuHkEFUwfju:b-zhybls) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Documentation/manifest-syntax.rst#L292)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> currently do *not* support mmap and fork/clone
> ```

I'd slightly reword this, because it may be read as "clone doesn't work if you use tmpfs mounts". Maybe just explicitly say that the contents of tmpfs are currently local to each process inside Graphene?
</blockquote></details>

How about `currently do *not* support mmap and are *not* available in a different Graphene instance even child process of fork/clone.` ?
___
*[Examples/lighttpd/lighttpd.manifest.template, line 52 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWAsL2xAbbX8IaloCgp:-MWMTchG1rO4QYvhj3G4:bwom5bs) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Examples/lighttpd/lighttpd.manifest.template#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If this is ignored, why can't we drop this line altogether?
</blockquote></details>

manifest parser requires three items  type/path/uri for one mount point.  It should not care what mount point it is.


<!-- Sent from Reviewable.io -->

2021-03-22 12:11 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 292 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWArrku4qZw3qmrd0dP:-MWOfasPBF3p2U3IubQy:b-krduvq) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Documentation/manifest-syntax.rst#L292)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

How about `currently do *not* support mmap and are *not* available in a different Graphene instance even child process of fork/clone.` ?
</blockquote></details>

What about this?

`currently do *not* support mmap and each process has its own, non-shared tmpfs (i.e. processes don't see each other's files).`
___
*[Examples/lighttpd/lighttpd.manifest.template, line 52 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWAsL2xAbbX8IaloCgp:-MWOodO671_5-DZUzHab:blkgb3i) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Examples/lighttpd/lighttpd.manifest.template#L52)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

manifest parser requires three items  type/path/uri for one mount point.  It should not care what mount point it is.
</blockquote></details>

Ah. Could you make it optional then and remove this line? It should be just a small change in `__mount_one_other()`, plus ensuring that chroot mount code errors out nicely on `uri==NULL`.


<!-- Sent from Reviewable.io -->

2021-03-23 01:35 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 15 of 16 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 277 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWAq_9a-4hnVpjJ9df_:-MWRd4OCEkqcNj_nNYVV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Documentation/manifest-syntax.rst#L277)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> to a Graphene instance
> ```

I think in this case it should be "the".
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 292 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWArrku4qZw3qmrd0dP:-MWRd5KXAsQLYhyITWxw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Documentation/manifest-syntax.rst#L292)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about this?

`currently do *not* support mmap and each process has its own, non-shared tmpfs (i.e. processes don't see each other's files).`
</blockquote></details>

Done.
___
*[Examples/lighttpd/lighttpd.manifest.template, line 52 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWAsL2xAbbX8IaloCgp:-MWRd84D69iAADx3F6ZR:bkkdjdv) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Examples/lighttpd/lighttpd.manifest.template#L52)):*
small but bad change.  I have to move
>log_error("Cannot find 'fs.mount.%s.uri'\n", key);

to chroot. Currently`key` is only used locally. Either passing `key` to chroot or not printing `key` in error message is not good solution.


<!-- Sent from Reviewable.io -->

2021-03-23 01:58 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r29.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @yamahata)

___
*[Examples/lighttpd/lighttpd.manifest.template, line 52 at r28](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWAsL2xAbbX8IaloCgp:-MWRnGKrAq7Vy0FFRtnd:b-o1h40k) ([raw file](https://github.com/oscarlab/graphene/blob/1cb5ff24b7597e3997b5bc4912a53c30b50c7e96/Examples/lighttpd/lighttpd.manifest.template#L52)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

small but bad change.  I have to move
>log_error("Cannot find 'fs.mount.%s.uri'\n", key);

to chroot. Currently`key` is only used locally. Either passing `key` to chroot or not printing `key` in error message is not good solution.
</blockquote></details>

Ah, I see. Resolving then.


<!-- Sent from Reviewable.io -->

2021-03-23 01:58 UTC, mkow commented
Jenkins, retest this please

2021-03-23 14:39 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUV4TyDoTxQgN0i3K-:-MWUV4TyDoTxQgN0i3K0:b2vkz32) (no related file):*
atime update is missing.

---
___
*[LibOS/shim/src/fs/str/fs.c, line 96 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUWZJ89zANUm0-VmNA:-MWUWZJ89zANUm0-VmNB:b-6ibz6a) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/str/fs.c#L96)):*
> ```
>     off_t offset  = strhdl->ptr - data->str;
>     size_t remain = data->len - offset;
> ```

offset can be larger than file size. more check is needed.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 232 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUUWbp7l8VcbposkGh:-MWUUWbp7l8VcbposkGi:b-t086lm) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L232)):*
> ```C
>     ssize_t ret = str_read(hdl, buf, count);
>     /* technically, we should update access time here, but we skip this because it could hurt
>      * performance on Linux-SGX host */
> ```

atime?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 256 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUUSc62FMmn9YO4Xo0:-MWUUSc62FMmn9YO4Xo1:b-t086lm) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L256)):*
> ```C
> 
>     tmpfs_data->ctime = time / 1000000;
>     tmpfs_data->mtime = tmpfs_data->ctime;
> ```

atime?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 558 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUU8vB4Vl-hukn60qo:-MWUU8vB4Vl-hukn60qp:b-t086lm) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L558)):*
> ```C
> 
>     tmpfs_data        = new->data;
>     tmpfs_data->ctime = time / 1000000;
> ```

atime?
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 577 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUU2FV-_Sd0IrRZxga:-MWUU2FV-_Sd0IrRZxgb:b-t086lm) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L577)):*
> ```C
>     dent->mode        = mode;
>     tmpfs_data->mode  = mode;
>     tmpfs_data->ctime = time / 1000000;
> ```

atime?


<!-- Sent from Reviewable.io -->

2021-03-23 14:40 UTC, yamahata reviewed
> Reviewed 2 of 12 files at r12, 1 of 1 files at r23, 1 of 3 files at r24, 1 of 1 files at r25, 1 of 1 files at r26, 4 of 5 files at r27, 5 of 6 files at r28, 1 of 1 files at r29.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @llly)



<!-- Sent from Reviewable.io -->

2021-03-24 02:05 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: 15 of 16 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUV4TyDoTxQgN0i3K-:-MWWtq6DBRNMMGMUoEIq:b4s4vaa) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

atime update is missing.
</blockquote></details>

atime updating is aligned with Ubuntu18.04 behavior except read. 

---
___
*[LibOS/shim/src/fs/str/fs.c, line 96 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUWZJ89zANUm0-VmNA:-MWWuQ4LE3RRq3P4pV8D:b-hakueb) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/str/fs.c#L96)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>     off_t offset  = strhdl->ptr - data->str;
>     size_t remain = data->len - offset;
> ```

offset can be larger than file size. more check is needed.
</blockquote></details>

Done. Nice catch.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 232 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUUWbp7l8VcbposkGh:-MWWuTlh5KvahcLVZDcF:b2wzg6s) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L232)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

atime?
</blockquote></details>

Ocall to only update atime take too much time for read. So I decide not to update it in read.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 256 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUUSc62FMmn9YO4Xo0:-MWWuZk90JCCzOdCyo_8:b-dgwin3) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L256)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

atime?
</blockquote></details>

atime is not updated after write. It is aligned with Ubuntu18.04 behavior. 
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 558 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUU8vB4Vl-hukn60qo:-MWWwwv125bQi_PRM2p-:ba5rg0o) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L558)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

atime?
</blockquote></details>

atime is not updated after rename. It is aligned with Ubuntu18.04 behavior. 
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 577 at r29](https://reviewable.io/reviews/oscarlab/graphene/2124#-MWUU2FV-_Sd0IrRZxga:-MWWx494Bmvr12pynFAq:b-ckwvy5) ([raw file](https://github.com/oscarlab/graphene/blob/0c94d3e3b043a09b3562b248462f357f5eb456af/LibOS/shim/src/fs/tmpfs/fs.c#L577)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

atime?
</blockquote></details>

atime is not updated after chmod. It is aligned with Ubuntu18.04 behavior. 


<!-- Sent from Reviewable.io -->

2021-03-24 10:04 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r30.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-31 14:55 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-04-01 07:31 UTC, dimakuv approved these changes
> Reviewed 3 of 5 files at r27, 3 of 6 files at r28, 1 of 1 files at r29, 7 of 7 files at r31.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-04-01 07:33 UTC, dimakuv commented
Jenkins, test this please

2021-04-01 08:03 UTC, dimakuv commented
Jenkins, test this please

2021-04-01 11:44 UTC, pwmarcz approved these changes
> Reviewed 3 of 5 files at r27, 3 of 6 files at r28, 1 of 1 files at r29, 1 of 1 files at r30, 5 of 7 files at r31, 1 of 1 files at r32.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-01 12:02 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r32.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2124)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-01 12:12 UTC, merged