[LibOS] Allow but ignore MSG_WAITALL flag in recv
oscarlab/graphene pull request #2128
Opened 2021-01-29 02:40 UTC by llly

## Description of the changes 
 This PR adds dummy emulation (simply ignoring) the flag MSG_WAITALL in recv/recvmsg, etc. , similar to #1766.
with MSG_WAITALL, the call may still return less data than requested.

## How to test this PR?
tcp_msg_peek LibOS regression test

2021-01-29 08:11 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSCBBEX0b9ES7R14F4S:-MSCBBEX0b9ES7R14F4T:b-pnu2no) (no related file):*
I'm fine with this PR, but can you give some context why you need this dummy emulation? I guess some app just sets this flag without (hopefully) really relying on its behavior?

Also, what's even the point of this flag if `the call may still return less data than requested if a signal is caught, an error or disconnect occurs, or the next data to be received is of a different type than that returned`. Sounds like a pure performance optimization...

---
___
*[LibOS/shim/test/regression/tcp_msg_peek.c, line 176 at r1](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSCASZt1TJN26oVDW9a:-MSCASZt1TJN26oVDW9b:b-dt5n1i) ([raw file](https://github.com/oscarlab/graphene/blob/2b95424bd139bb090b1ee817fc234fcb94ba78ee/LibOS/shim/test/regression/tcp_msg_peek.c#L176)):*
> ```C
>     }
> 
>     /* we specify dummy MSG_DONTWAIT and MSG_WAITALL just to test this flag */
> ```

`to test this flag` -> `to test these flags`


<!-- Sent from Reviewable.io -->

2021-01-29 08:12 UTC, dimakuv commented
Jenkins, test this please

2021-02-01 05:23 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSCBBEX0b9ES7R14F4S:-MSR-RKQ2bBxzjxeuxqB:b-oi3am9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with this PR, but can you give some context why you need this dummy emulation? I guess some app just sets this flag without (hopefully) really relying on its behavior?

Also, what's even the point of this flag if `the call may still return less data than requested if a signal is caught, an error or disconnect occurs, or the next data to be received is of a different type than that returned`. Sounds like a pure performance optimization...
</blockquote></details>

[XGBoost](https://github.com/dmlc/xgboost) for JVM uses this flag and gets error when I tries it using Graphene.  It can work with this fix.

---
___
*[LibOS/shim/test/regression/tcp_msg_peek.c, line 176 at r1](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSCASZt1TJN26oVDW9a:-MSR1VBT116sA3oyyY6V:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2b95424bd139bb090b1ee817fc234fcb94ba78ee/LibOS/shim/test/regression/tcp_msg_peek.c#L176)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to test this flag` -> `to test these flags`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-01 07:30 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSCBBEX0b9ES7R14F4S:-MSRUxTo9rowInj1NGNI:bxcixb5) (no related file):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

[XGBoost](https://github.com/dmlc/xgboost) for JVM uses this flag and gets error when I tries it using Graphene.  It can work with this fix.
</blockquote></details>

OK, thanks for explanation!

---


<!-- Sent from Reviewable.io -->

2021-02-01 07:31 UTC, dimakuv commented
Jenkins, test this please

2021-02-01 15:16 UTC, mkow requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1251 at r2](https://reviewable.io/reviews/oscarlab/graphene/2128#-MST8qeW1nooEWz7PC7M:-MST8qeX7vaihrhNL_eo:b-xbkeje) ([raw file](https://github.com/oscarlab/graphene/blob/14610c0b34ab92a0ce774c3c480d4b8903ab9431/LibOS/shim/src/sys/shim_socket.c#L1251)):*
> ```C
> 
>     if (flags & MSG_WAITALL) {
>         debug("Warning: MSG_WAITALL is ignored, may lead to a read that returns less data.\n");
> ```

Please use our new interface (`log_{error,warning,debug,trace}`) in new code (we'll fix other debug() calls soon).
I think it should be `log_debug`, not `log_warning`, because it's very low-importance (as skipping this flag is semantically correct).


<!-- Sent from Reviewable.io -->

2021-02-01 19:34 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @llly)



<!-- Sent from Reviewable.io -->

2021-02-02 00:58 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1251 at r2](https://reviewable.io/reviews/oscarlab/graphene/2128#-MST8qeW1nooEWz7PC7M:-MSVEfNn-lpgLR67vbfg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/14610c0b34ab92a0ce774c3c480d4b8903ab9431/LibOS/shim/src/sys/shim_socket.c#L1251)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use our new interface (`log_{error,warning,debug,trace}`) in new code (we'll fix other debug() calls soon).
I think it should be `log_debug`, not `log_warning`, because it's very low-importance (as skipping this flag is semantically correct).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 01:16 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1251 at r3](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSVIKDcAXI3zoYaRqsv:-MSVIKDcAXI3zoYaRqsw:byuc1w6) ([raw file](https://github.com/oscarlab/graphene/blob/5066298c330e9cbb2120898b30600fb96709a50d/LibOS/shim/src/sys/shim_socket.c#L1251)):*
> ```C
> 
>     if (flags & MSG_WAITALL) {
>         log_debug("MSG_WAITALL is ignored, may lead to a read that returns less data.\n");
> ```

One more thing I missed previously (sorry): could you mention _where_ this flag was ignored? This message will pop up without the context when using log_level == debug.
Something like: "MSG_WAITALL was ignored in recvmsg, [...]".


<!-- Sent from Reviewable.io -->

2021-02-02 01:27 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1251 at r3](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSVIKDcAXI3zoYaRqsv:-MSVLHwi65pxnElobA1E:b-hbvwcm) ([raw file](https://github.com/oscarlab/graphene/blob/5066298c330e9cbb2120898b30600fb96709a50d/LibOS/shim/src/sys/shim_socket.c#L1251)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

One more thing I missed previously (sorry): could you mention _where_ this flag was ignored? This message will pop up without the context when using log_level == debug.
Something like: "MSG_WAITALL was ignored in recvmsg, [...]".
</blockquote></details>

How about "recvmsg()/recvmmsg()/recvfrom(): MSG_WAITALL is ignored, may lead to a read that returns less data." like previous message?


<!-- Sent from Reviewable.io -->

2021-02-02 07:24 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly and @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1252 at r4](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSWbw405EeMyLwFUMGu:-MSWbw405EeMyLwFUMGv:b-3jzpy) ([raw file](https://github.com/oscarlab/graphene/blob/094088a0577352d1b9fe8d12a33e9a5a4717fa43/LibOS/shim/src/sys/shim_socket.c#L1252)):*
> ```C
>     if (flags & MSG_WAITALL) {
>         log_debug("recvmsg()/recvmmsg()/recvfrom(): MSG_WAITALL is ignored, may lead to a read"
> 		  " that returns less data.\n");
> ```

Please use spaces instead of tabs and align the line similar to other such lines (see example above).


<!-- Sent from Reviewable.io -->

2021-02-02 08:00 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1252 at r4](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSWbw405EeMyLwFUMGu:-MSWkXd6EjDvgmJNfrvN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/094088a0577352d1b9fe8d12a33e9a5a4717fa43/LibOS/shim/src/sys/shim_socket.c#L1252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use spaces instead of tabs and align the line similar to other such lines (see example above).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-02 09:22 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-02-02 18:35 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/sys/shim_socket.c, line 1251 at r3](https://reviewable.io/reviews/oscarlab/graphene/2128#-MSVIKDcAXI3zoYaRqsv:-MSZ0cez4F4rWcUQpMop:b-n7gfil) ([raw file](https://github.com/oscarlab/graphene/blob/5066298c330e9cbb2120898b30600fb96709a50d/LibOS/shim/src/sys/shim_socket.c#L1251)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

How about "recvmsg()/recvmmsg()/recvfrom(): MSG_WAITALL is ignored, may lead to a read that returns less data." like previous message?
</blockquote></details>

Sounds good, I missed that it's also used by other syscalls. Thanks for noticing this!


<!-- Sent from Reviewable.io -->

2021-02-03 00:19 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-03 00:19 UTC, mkow commented
Jenkins, retest this please

2021-02-03 00:31 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-02-03 08:08 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2128)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-03 08:10 UTC, merged