[Pal/Linux-SGX] Allow CPUID leaves 0x40000000 - 0x4FFFFFFF
oscarlab/graphene pull request #2134
Opened 2021-02-02 12:39 UTC by dimakuv

## Description of the changes 

These CPUID leaves used by virtualization software (Hyper-V, KVM, etc.) and is zeroed out on bare metal. Some runtimes like JVM query these CPUID leaves to detect underlying virtualization software. This commit makes these leaves return zeroes ("no virtualization").

Some references:
1. Intel SDM
2. https://github.com/qemu/qemu/blob/master/docs/hyperv.txt
3. https://www.kernel.org/doc/html/latest/virt/kvm/cpuid.html

## How to test this PR? 

LibOS test `cpuid` was augmented to test this (the test is run only on SGX).

2021-02-03 00:14 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2134)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/cpuid.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2134#-MS_EHN14fFeUu1dOL80:-MS_EHN14fFeUu1dOL81:bwh8zz8) ([raw file](https://github.com/oscarlab/graphene/blob/3095bc952267dfb59f192b52285d2a277e5ff72e/LibOS/shim/test/regression/cpuid.c#L84)):*
> ```C
>     if (r.eax || r.ebx || r.ecx || r.edx)
>         abort();
>     memset(&r, 0, sizeof(r));
> ```

That's not needed.


<!-- Sent from Reviewable.io -->

2021-02-03 08:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2134)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/cpuid.c, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene/2134#-MS_EHN14fFeUu1dOL80:-MSb0SpM8OjSbu2Lbsa4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3095bc952267dfb59f192b52285d2a277e5ff72e/LibOS/shim/test/regression/cpuid.c#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-03 12:12 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2134)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-04 17:35 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2134)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-05 02:25 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2134)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-02-05 02:49 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2134)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-05 03:07 UTC, merged