[LibOS] Make poll and epoll_wait pass errors from DkStreamsWaitEvents
oscarlab/graphene pull request #2135
Opened 2021-02-02 17:31 UTC by boryspoplawski

## Description of the changes 
Previously `poll` and `epoll_wait` ignored all errors returned from `DkStreamsWaitEvents`, including `EINTR`.

2021-02-02 18:40 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2135)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-03 08:29 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2135)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2135#-MSayiUU7jnizCO3vZOS:-MSayiUU7jnizCO3vZOT:bwtaka9) (no related file):*
Some LTP tests failed (non-sgx graphene):
```
test-direct / apps.LTP.personality02
test-direct / apps.LTP.pselect03
test-direct / apps.LTP.pselect03_64
test-direct / apps.LTP.select01
```

It looks like they fail with `-EINVAL`, which most probably stems from this:
https://github.com/oscarlab/graphene/blob/master/Pal/src/db_object.c#L81-L91

Maybe sometimes LibOS tries to call `DkStreamsWaitEvents()` with say `count == 0` and this is supposed to be a legal operation, but our strict checks in PAL return `-PAL_ERROR_INVAL`?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2135#-MSb-Mn1-UNtZ7DhJISD:-MSb-Mn1-UNtZ7DhJISE:bf5zjas) (no related file):*
I checked where else `DkStreamsWaitEvents()` is used in LibOS code:
- `shim_internal.h: clear_event()` -- error handling is already there
- Async helper thread -- no error handling, but we don't really need it there (we can't do much about things like ENOMEM in helper threads)
- IPC helper thread -- no error handling, but same reasoning as above

So it looks like this PR covers all uses.

---


<!-- Sent from Reviewable.io -->

2021-02-03 14:13 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2135)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2135#-MSayiUU7jnizCO3vZOS:-MScCTL56flZXjSCd4he:bt2vr1b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Some LTP tests failed (non-sgx graphene):
```
test-direct / apps.LTP.personality02
test-direct / apps.LTP.pselect03
test-direct / apps.LTP.pselect03_64
test-direct / apps.LTP.select01
```

It looks like they fail with `-EINVAL`, which most probably stems from this:
https://github.com/oscarlab/graphene/blob/master/Pal/src/db_object.c#L81-L91

Maybe sometimes LibOS tries to call `DkStreamsWaitEvents()` with say `count == 0` and this is supposed to be a legal operation, but our strict checks in PAL return `-PAL_ERROR_INVAL`?
</blockquote></details>

Fixed.

---


<!-- Sent from Reviewable.io -->

2021-02-03 14:56 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2135)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_poll.c, line 151 at r2](https://reviewable.io/reviews/oscarlab/graphene/2135#-MScNr_e5jadlY0hobGf:-MScNr_e5jadlY0hobGg:bwmri9p) ([raw file](https://github.com/oscarlab/graphene/blob/caf7db6039807a68657680b7c1e62bce41146998/LibOS/shim/src/sys/shim_poll.c#L151)):*
> ```C
>     PAL_BOL polled = false;
>     long error = 0;
>     if (pal_cnt) {
> ```

Meh, we had this error all this time (`DkStreamsWaitEvents(pal_cnt == 0)` returning EINVAL), and never realized this...


<!-- Sent from Reviewable.io -->

2021-02-03 15:55 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2135)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-02-03 16:37 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2135)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-03 16:39 UTC, merged