[CI] Increase sleep times between server start and client start
oscarlab/graphene pull request #2138
Opened 2021-02-04 08:46 UTC by dimakuv

## Description of the changes 

Sometimes one second of sleep between the server start and the client start is not enough for the server to completely initialize itself. In particular, in debug builds, the server process may output a lot of debug messages, which slows down its initialization significantly.

## How to test this PR? 

This problem was observed on e.g. https://github.com/oscarlab/graphene/pull/2112 in the Jenkins-Debug CI job.

2021-02-04 18:10 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-02-05 01:57 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MSjteuX7pSfsKT7yNu3:b-fdk1bp) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
> ```
>             make -j8 all
>             make start-graphene-server &
>             sleep 3
> ```

Any idea how could we implement this wait without sleeping for some arbitrary time? This is quite annoying in our examples, we lose CI time on sleeping and we still can't be sure if a failure was caused by this or by a bug.

CC: @woju


<!-- Sent from Reviewable.io -->

2021-02-05 07:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MSl6l5IAWj5i4J8-aJx:b-wplquo) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Any idea how could we implement this wait without sleeping for some arbitrary time? This is quite annoying in our examples, we lose CI time on sleeping and we still can't be sure if a failure was caused by this or by a bug.

CC: @woju
</blockquote></details>

No idea. Hopefully woju has some ideas.


<!-- Sent from Reviewable.io -->

2021-02-05 11:58 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MSm2Wbp4fMocxG18jkO:b6d0tnq) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No idea. Hopefully woju has some ideas.
</blockquote></details>

Isn't this impossible without cooperation of the server binary? It's quite binary specific when it's ready...
Otoh, if in all cases these are TCP servers, we could just poll an appropriate port here.


<!-- Sent from Reviewable.io -->

2021-02-08 15:32 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @woju)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MT1GKxWCr2pWJkRA_Iq:bplhxdj) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't this impossible without cooperation of the server binary? It's quite binary specific when it's ready...
Otoh, if in all cases these are TCP servers, we could just poll an appropriate port here.
</blockquote></details>

yeah, I thought about something like waiting for the TCP port to get opened


<!-- Sent from Reviewable.io -->

2021-02-09 10:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MT5JmRP8UUKXoGSv3EN:b-biz8z2) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

yeah, I thought about something like waiting for the TCP port to get opened
</blockquote></details>

Let's ping @woju again as he is our CI expert.


<!-- Sent from Reviewable.io -->

2021-02-09 13:22 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MT5szHbCHReGDqvHwIf:b-q65e0n) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's ping @woju again as he is our CI expert.
</blockquote></details>

In principle that's a hard problem, and I'd refer you to "Type=" option from `systemd.service(5)` manual, which lists 6 methods, which systemd uses to know exactly when the service is considered active: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options. This doesn't include inetd aka. "socket activation" in which there is a intermediary daemon, which starts very quickly and just listens on the socket for incoming connections and hands descriptors to the real server.

Polling TCP port is a good idea (with timeout, obviously, in case the server didn't start).

Also you may try to intercept the sd_notify protocol (https://www.freedesktop.org/software/systemd/man/sd_notify.html#Description) if the server supports that (it might be implemented in module like http://httpd.apache.org/docs/trunk/mod/mod_systemd.html): the server is supposed to open the unix socket given by `$NOTIFY_SOCKET` and send `READY=1`. If you could intercept that (give your own socket and wait for this write), that would be the most robust solution.


<!-- Sent from Reviewable.io -->

2021-02-10 10:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MTAHHaB1344aYSP89pk:bre7u60) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

In principle that's a hard problem, and I'd refer you to "Type=" option from `systemd.service(5)` manual, which lists 6 methods, which systemd uses to know exactly when the service is considered active: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Options. This doesn't include inetd aka. "socket activation" in which there is a intermediary daemon, which starts very quickly and just listens on the socket for incoming connections and hands descriptors to the real server.

Polling TCP port is a good idea (with timeout, obviously, in case the server didn't start).

Also you may try to intercept the sd_notify protocol (https://www.freedesktop.org/software/systemd/man/sd_notify.html#Description) if the server supports that (it might be implemented in module like http://httpd.apache.org/docs/trunk/mod/mod_systemd.html): the server is supposed to open the unix socket given by `$NOTIFY_SOCKET` and send `READY=1`. If you could intercept that (give your own socket and wait for this write), that would be the most robust solution.
</blockquote></details>

All this sounds really complicated. Does anyone want me to proceed with this PR, or should I just close it? This doesn't bother us too much, Jenkins fails maybe once in 100 runs.


<!-- Sent from Reviewable.io -->

2021-02-10 17:12 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MTBuYT-75884NJGdVx_:bqvyqwa) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

All this sounds really complicated. Does anyone want me to proceed with this PR, or should I just close it? This doesn't bother us too much, Jenkins fails maybe once in 100 runs.
</blockquote></details>

It very much is complicated, and this is part of the reason why systemd was/is criticized. This was a holy war, and some people prefer to stay out of it, because the community is still licking the wounds. Just saying.


<!-- Sent from Reviewable.io -->

2021-02-10 21:30 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski, @dimakuv, and @woju)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MTCqKH3A8g6FxL4aqah:b-lb16m1) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It very much is complicated, and this is part of the reason why systemd was/is criticized. This was a holy war, and some people prefer to stay out of it, because the community is still licking the wounds. Just saying.
</blockquote></details>

But for our needs, polling the TCP port doesn't sound that complicated? I guess it can be done with a few lines of Bash using `nc`?


<!-- Sent from Reviewable.io -->

2021-02-11 03:59 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2138)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[.ci/lib/stage-test-direct.jenkinsfile, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2138#-MSjteuX7pSfsKT7yNu2:-MTEEM7HC_LW7jmUHI0E:bi0ul6a) ([raw file](https://github.com/oscarlab/graphene/blob/69c02d44a43da9422d0e1c7869202e60db83c5ea/.ci/lib/stage-test-direct.jenkinsfile#L52)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But for our needs, polling the TCP port doesn't sound that complicated? I guess it can be done with a few lines of Bash using `nc`?
</blockquote></details>

Yeah, please do not over complicate it, we need a simple TCP polling (basically just just loop doing a handshake, nc/socakt would be more than enough).


<!-- Sent from Reviewable.io -->

2021-02-25 09:16 UTC, dimakuv commented
This is very low-priority, and we haven't seen these failures in Jenkins for quite some time. Closing this PR.

2021-02-25 09:16 UTC, closed without merging