[LibOS] Fix `/sys/devices/system/[cpu|node]/` path resolution
oscarlab/graphene pull request #2153
Opened 2021-02-09 20:23 UTC by vijaydhanraj

## Description of the changes 
The current implementation of /sys fs will fail for paths such as
`/sys/devices/system/[cpu|node]/online` which doesn't have a
numeric value. This patch fixes this issue. This patch also adds
2 additional test cases as part of the /sys fs regression test.

Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>

## How to test this PR? 
Please run sysfs_common.c as part of LibOS regression tests.

2021-02-10 08:19 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-CWS0N9YeVSEEy6H:-MTA-CWS0N9YeVSEEy6I:b-rrbvnv) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L27)):*
> ```C
>     const char* cpu_filebuf;
>     if (!strcmp(filename, "online") && !strstr(name, "cpu/cpu")) {
>         cpu_filebuf = pal_control.topo_info.online_logical_cores;
> ```

Please add a comment above this line: `/* this is a file /sys/devices/system/cpu/online */`
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-KV5BRqVwuVmU58i:-MTA-KV5BRqVwuVmU58j:brr5utv) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
> ```C
>         cpu_filebuf = pal_control.topo_info.online_logical_cores;
>     } else if (!strcmp(filename, "possible")) {
>         cpu_filebuf = pal_control.topo_info.possible_logical_cores;
> ```

Please add a comment above this line: `/* this is a file /sys/devices/system/cpu/possible */`
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-gEU3LqjajRQ9qQR:-MTA-gEU3LqjajRQ9qQS:bwfknt9) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L31)):*
> ```C
>         cpu_filebuf = pal_control.topo_info.possible_logical_cores;
>     } else {
>         int cpunum = extract_first_num_from_string(name);
> ```

Please add a comment above this line: `/* the below are files under /sys/devices/system/cpu/cpuX/ */`
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-xa08jpzW6N1eyNU:-MTA-xa08jpzW6N1eyNV:bvn6k2g) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L35)):*
> ```C
>              return -ENOENT;
> 
>         if (!strcmp(filename, "online") && strstr(name, "cpu/cpu")) {
> ```

The `strstr()` part of this IF is not needed, please remove
___
*[LibOS/shim/src/fs/sys/node_info.c, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA08FFAOWMkIS0OElV:-MTA08FFAOWMkIS0OElW:b-eh0tgl) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/node_info.c#L23)):*
> ```C
>     const char* node_filebuf;
>     if (!strcmp(filename, "online")) {
>         node_filebuf = pal_control.topo_info.online_nodes;
> ```

Please add a comment above this line: `/* this is a file /sys/devices/system/node/online */`
___
*[LibOS/shim/src/fs/sys/node_info.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA0RWR-kame77otkco:-MTA0RWR-kame77otkcp:bnct3uj) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/node_info.c#L25)):*
> ```C
>         node_filebuf = pal_control.topo_info.online_nodes;
>     } else {
>         int nodenum = extract_first_num_from_string(name);
> ```

Please add a comment above this line: `/* the below are files under /sys/devices/system/node/nodeX/ */`


<!-- Sent from Reviewable.io -->

2021-02-10 17:19 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-CWS0N9YeVSEEy6H:-MTBkTkU1BzGuW0hVUWi:b1ski8i) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment above this line: `/* this is a file /sys/devices/system/cpu/online */`
</blockquote></details>

I think it should be `the`, not `a`? But otherwise +1.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-KV5BRqVwuVmU58i:-MTBlTwH66UVq32jkDXh:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment above this line: `/* this is a file /sys/devices/system/cpu/possible */`
</blockquote></details>

ditto
___
*[LibOS/shim/src/fs/sys/node_info.c, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA08FFAOWMkIS0OElV:-MTBw1_I1Ou10T3Dehim:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/node_info.c#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment above this line: `/* this is a file /sys/devices/system/node/online */`
</blockquote></details>

ditto
___
*[LibOS/shim/test/regression/sysfs_common.c, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBgKMN5RufzlAlp5Ja:-MTBgKMN5RufzlAlp5Jb:ba66y8g) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/test/regression/sysfs_common.c#L134)):*
> ```C
>     if (errno)
>         err(EXIT_FAILURE, "readdir failed for /sys/devices/system/cpu");
>     printf("Total CPU count=%d\n", count);
> ```

Not related to this PR, but I just noticed when running this test:

```
/sys/devices/system/cpu/cpu0, type=4
/sys/devices/system/cpu/cpu1, type=4
[...]
/sys/devices/system/cpu/cpu126, type=4
/sys/devices/system/cpu/cpu127, type=4
Total CPU count=127
```

The count is off-by-one ;) Could you fix this in another PR? And also validate other counts here if they are correct.


<!-- Sent from Reviewable.io -->

2021-02-10 17:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/test/regression/sysfs_common.c, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBgKMN5RufzlAlp5Ja:-MTBxGdMB0U3A6905Kh6:b-euraur) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/test/regression/sysfs_common.c#L134)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not related to this PR, but I just noticed when running this test:

```
/sys/devices/system/cpu/cpu0, type=4
/sys/devices/system/cpu/cpu1, type=4
[...]
/sys/devices/system/cpu/cpu126, type=4
/sys/devices/system/cpu/cpu127, type=4
Total CPU count=127
```

The count is off-by-one ;) Could you fix this in another PR? And also validate other counts here if they are correct.
</blockquote></details>

Or maybe just a separate commit, in case the fix turns out to be trivial.


<!-- Sent from Reviewable.io -->

2021-02-10 17:25 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBxwxt5v6c7-bKJYqi:-MTBxwxt5v6c7-bKJYqj:b-5tc0fl) (no related file):*
I tried running `lscpu` on this PR and there are still some failures left: (probably unrelated to this PR, but seem to be separate bugs in sysfs topology)

```
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index0", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index1", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index2", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index3", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index4", 0) = 0x0
[P80473:T1:lscpu] Incorrect index 5 in file index5 (max supported is 4)
```

```
[P80473:T1:lscpu] Incorrect index 160923600 in file node160923600 (max supported is 1)
```

Could you take a look at these?

There are also some SIGSEGVs, but probably unrelated to sysfs.

---


<!-- Sent from Reviewable.io -->

2021-02-10 22:53 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBxwxt5v6c7-bKJYqi:-MTD6SZw1aiu2tH7gP1V:b-wxnn45) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I tried running `lscpu` on this PR and there are still some failures left: (probably unrelated to this PR, but seem to be separate bugs in sysfs topology)

```
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index0", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index1", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index2", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index3", 0) = 0x0
[P80473:T1:lscpu] ---- shim_faccessat(4, "cpu0/cache/index4", 0) = 0x0
[P80473:T1:lscpu] Incorrect index 5 in file index5 (max supported is 4)
```

```
[P80473:T1:lscpu] Incorrect index 160923600 in file node160923600 (max supported is 1)
```

Could you take a look at these?

There are also some SIGSEGVs, but probably unrelated to sysfs.
</blockquote></details>

This seems to be unrelated. @mkow can you please let me know how to repro this? If a fix is needed, will create a separate PR.

---
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-CWS0N9YeVSEEy6H:-MTC-1lY8rBgvD_OtzPP:b-a2got6) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it should be `the`, not `a`? But otherwise +1.
</blockquote></details>

get the idea but reworded to `This file refers to /sys/devices/system/cpu/online `
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-KV5BRqVwuVmU58i:-MTC-E5_EDndHQ9gAC44:b-dnl63b) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Reworded to `This file refers to /sys/devices/system/cpu/possible `
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-gEU3LqjajRQ9qQR:-MTC-mHxD8Jex8HfEE9Y:btfst17) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L31)):*
> the below are files under /sys/devices/system/cpu/cpuX/
Done.
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA-xa08jpzW6N1eyNU:-MTC-npUDUq9bp5mKFrF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/cpu_info.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `strstr()` part of this IF is not needed, please remove
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/node_info.c, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA08FFAOWMkIS0OElV:-MTC4Kk18laxtsJOK5qF:bkkmsih) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/node_info.c#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Reworded to `This file refers to /sys/devices/system/node/online`
___
*[LibOS/shim/src/fs/sys/node_info.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTA0RWR-kame77otkco:-MTCGi632D47MOioa8bN:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/src/fs/sys/node_info.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment above this line: `/* the below are files under /sys/devices/system/node/nodeX/ */`
</blockquote></details>

Done
___
*[LibOS/shim/test/regression/sysfs_common.c, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBgKMN5RufzlAlp5Ja:-MTD5Elj6IwDmT3jwJu1:by9robo) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/test/regression/sysfs_common.c#L134)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Or maybe just a separate commit, in case the fix turns out to be trivial.
</blockquote></details>

Oh my bad. I had used `_SC_ULONG_MAX` instead of `ULONG_MAX` to check the error case of `strtoul()`. `_SC_ULONG_MAX` is defined as `117` which prevented the below code to increment the count when checking against `cpu117` :).
```
 if (nr != _SC_ULONG_MAX && endp != dirent64->d_name + 4 && *endp == '\0')
     count++;
```

Created a separate commit to fix this issue.


<!-- Sent from Reviewable.io -->

2021-02-11 02:07 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBxwxt5v6c7-bKJYqi:-MTDoeZxCd7JncmfaGZB:b-x09aec) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This seems to be unrelated. @mkow can you please let me know how to repro this? If a fix is needed, will create a separate PR.
</blockquote></details>

Not sure if it is an issue here. The application/library may try to open this file and see if it is accessible. At least on server platforms, I have seen the max to up to index3 and on regular NUC max I have seen is index2.

Based on the error log, we can confirm this ` (max supported is 4)`.

---


<!-- Sent from Reviewable.io -->

2021-02-11 07:16 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-02-11 07:17 UTC, dimakuv commented
Jenkins, test this please

2021-02-15 02:01 UTC, mkow requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBxwxt5v6c7-bKJYqi:-MTYJy0n3zGHTX1laflC:b-mmh1sb) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Not sure if it is an issue here. The application/library may try to open this file and see if it is accessible. At least on server platforms, I have seen the max to up to index3 and on regular NUC max I have seen is index2.

Based on the error log, we can confirm this ` (max supported is 4)`.
</blockquote></details>

Right, seems it's just `lscpu` probing the max index this way. But now I checked this better and I don't have `ls /sys/devices/system/cpu/cpu0/cache/index4` file on my host, yet inside Graphene this file exists (see the log above). Isn't this a bug?

btw. I updated #2004 with info what's still failing after this PR.

---
___
*[LibOS/shim/test/regression/sysfs_common.c, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBgKMN5RufzlAlp5Ja:-MTYPkW2Ciftpvwb0Kf8:b62p0nr) ([raw file](https://github.com/oscarlab/graphene/blob/1017887599c47563beaffdcd27dc76aa480d270c/LibOS/shim/test/regression/sysfs_common.c#L134)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Oh my bad. I had used `_SC_ULONG_MAX` instead of `ULONG_MAX` to check the error case of `strtoul()`. `_SC_ULONG_MAX` is defined as `117` which prevented the below code to increment the count when checking against `cpu117` :).
```
 if (nr != _SC_ULONG_MAX && endp != dirent64->d_name + 4 && *endp == '\0')
     count++;
```

Created a separate commit to fix this issue.
</blockquote></details>

huh, lol :) seems I missed this in the review...


<!-- Sent from Reviewable.io -->

2021-02-15 03:44 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBxwxt5v6c7-bKJYqi:-MTYmEUYAHErLS4KCREd:b-66xfh1) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Right, seems it's just `lscpu` probing the max index this way. But now I checked this better and I don't have `ls /sys/devices/system/cpu/cpu0/cache/index4` file on my host, yet inside Graphene this file exists (see the log above). Isn't this a bug?

btw. I updated #2004 with info what's still failing after this PR.
</blockquote></details>

yes, you are right. We have to limit the index from 0-3. I have fixed this.

---


<!-- Sent from Reviewable.io -->

2021-02-15 08:00 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTZgph7-Yxi79MzenZP:-MTZgph7-Yxi79MzenZQ:bt3f57c) ([raw file](https://github.com/oscarlab/graphene/blob/f7dca3b92eca43cb4ce2b9a959da01e07009a4d5/LibOS/shim/src/fs/sys/fs.c#L91)):*
> ```C
>     }
> 
>     /* sysfs resources like cpu, cache start from 0 till totalcnt-1 */
> ```

Slightly better wording:
```
/* sysfs resources like NUMA nodes, CPU cores, CPU caches have indexes from 0 to totalcnt - 1 */
```


<!-- Sent from Reviewable.io -->

2021-02-15 13:45 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTBxwxt5v6c7-bKJYqi:-MT_w0Hv7hf0lXihtLvW:bxjswtv) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, you are right. We have to limit the index from 0-3. I have fixed this.
</blockquote></details>

Hah, seems it was just an off-by-one error :)

---


<!-- Sent from Reviewable.io -->

2021-02-15 17:50 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/sys/fs.c, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene/2153#-MTZgph7-Yxi79MzenZP:-MTaoAaAAoN6QVlzj7Az:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f7dca3b92eca43cb4ce2b9a959da01e07009a4d5/LibOS/shim/src/fs/sys/fs.c#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Slightly better wording:
```
/* sysfs resources like NUMA nodes, CPU cores, CPU caches have indexes from 0 to totalcnt - 1 */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 18:52 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-02-15 21:14 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-15 21:14 UTC, dimakuv commented
Jenkins, test this please

2021-02-15 23:26 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-15 23:47 UTC, mkow commented
Jenkins, retest this please

2021-02-16 06:56 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2153)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-16 06:57 UTC, merged