fix the deadlock of _DkSystemTimeQuery()
oscarlab/graphene pull request #2155
Opened 2021-02-11 01:45 UTC by ying2liu

_DkSystemTimeQuery() can be interrupted by async signal when it holds spin lock,
signal handler can recursively issue _DkSystemTimeQuery() with tsc_lock held,
thus it can result in deadlock(self recursive lock).
Solve such deadlock by introducing sequential number for data integrity for
fast path and use spinlock_trylock() instead spinlock_lock() for slow path to
update start_usec, start_tsc.

Change-Id: Ia922676890cfaaa1ca9a32b74130f74bf540f719
Signed-off-by: Isaku Yamahata <saku.yamahata@intel.com>
Signed-off-by: Ying Liu <ying2.liu@intel.com>

## Description of the changes 

_DkSystemTimeQuery() can be interrupted by async signal when it holds spin lock,
signal handler can recursively issue _DkSystemTimeQuery() with tsc_lock held,
thus it can result in deadlock(self recursive lock).
Solve such deadlock by introducing sequential number for data integrity for
fast path and use spinlock_trylock() instead spinlock_lock() for slow path to
update start_usec, start_tsc.

## How to test this PR? 
This commit also includes a unit test case.

2021-02-11 04:28 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2155)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ying2liu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2155#-MTEKPu93pQd9Iejj4wq:-MTEKPuC7HCOeZ0A53Ps:bfiy9vp) (no related file):*
> _DkSystemTimeQuery() can be interrupted by async signal when it holds spin lock,
> signal handler can recursively issue _DkSystemTimeQuery() with tsc_lock held,
> thus it can result in deadlock(self recursive lock).

Could you specify where exactly a signal handler can recursively issue `_DkSystemTimeQuery()`? Currently signal handlers should be reentrant...

---


<!-- Sent from Reviewable.io -->

2021-02-12 02:05 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2155)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ying2liu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2155#-MTIz6eP--t9pY7cWczM:-MTIz6eP--t9pY7cWczN:b-79lzk2) (no related file):*
Please check #2156 it might solve the issues you are having.

---


<!-- Sent from Reviewable.io -->

2021-02-12 17:11 UTC, ying2liu commented
Yes, signal handler is reentrant, but it is an async signal and might be called in a thread just within _DkSystemTimeQuery and holding the lock.
This would cause recursive locking and dead lock if the handler calls gettimeofdata/_DkSystemTimeQuery. This commit tries to solve this problem because
lots of signal hander calls gettimeofday for bookkeeping.

From: Borys Popławski <notifications@github.com>
Sent: Wednesday, February 10, 2021 8:29 PM
To: oscarlab/graphene <graphene@noreply.github.com>
Cc: Liu, Ying2 <ying2.liu@intel.com>; Mention <mention@noreply.github.com>
Subject: Re: [oscarlab/graphene] fix the deadlock of _DkSystemTimeQuery() (#2155)


@boryspoplawski requested changes on this pull request.

Reviewable<https://reviewable.io/reviews/oscarlab/graphene/2155> status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ying2liu<https://github.com/ying2liu>)

a discussion<https://reviewable.io/reviews/oscarlab/graphene/2155#-MTEKPu93pQd9Iejj4wq:-MTEKPuC7HCOeZ0A53Ps:bfiy9vp> (no related file):

_DkSystemTimeQuery() can be interrupted by async signal when it holds spin lock,
signal handler can recursively issue _DkSystemTimeQuery() with tsc_lock held,
thus it can result in deadlock(self recursive lock).

Could you specify where exactly a signal handler can recursively issue _DkSystemTimeQuery()? Currently signal handlers should be reentrant...

________________________________

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/oscarlab/graphene/pull/2155#pullrequestreview-588241685>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIUG3QUZ62RHPPZWU7DABA3S6NMHFANCNFSM4XOAKZSQ>.

2021-02-12 17:22 UTC, boryspoplawski reviewed
For the future: pleas respond directly in reviewable or at least github, responding via emials completely breaks formatting.
> Yes, signal handler is reentrant, but it is an async signal and might be called in a thread just within _DkSystemTimeQuery and holding the lock. This would cause recursive locking and dead lock if the handler calls gettimeofdata/_DkSystemTimeQuery. This commit tries to solve this problem because lots of signal hander calls gettimeofday for bookkeeping.
 
This is not true. User-level signal handlers are only called when returning from a syscall / interrupt (host-level signal) - they cannot hold a Graphene-level lock. Host-level signal handlers should be reentrant, hence they do not use locks at all (this means that they do not call functions holding any locks, such as `DkSystemTimeQuery`).

Keep in mind that recently a bug was discovered (#2156) which could cause host-level singal to be nested, if the first one appeared while the code was in host-level vdso. That's why I asked you to verify it it fixes issues you are having, as this might have been the underlying issue to your deadlocks.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2155#-:-MTME_nK28Rio_TI6THZ:b7o3fuv)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @ying2liu)



<!-- Sent from Reviewable.io -->

2021-02-12 19:09 UTC, ying2liu commented
I will run some tests using #2156.

Thanks

Ying

From: Borys Popławski <notifications@github.com>
Sent: Friday, February 12, 2021 9:23 AM
To: oscarlab/graphene <graphene@noreply.github.com>
Cc: Liu, Ying2 <ying2.liu@intel.com>; Mention <mention@noreply.github.com>
Subject: Re: [oscarlab/graphene] fix the deadlock of _DkSystemTimeQuery() (#2155)


@boryspoplawski commented on this pull request.

For the future: pleas respond directly in reviewable or at least github, responding via emials completely breaks formatting.

Yes, signal handler is reentrant, but it is an async signal and might be called in a thread just within _DkSystemTimeQuery and holding the lock. This would cause recursive locking and dead lock if the handler calls gettimeofdata/_DkSystemTimeQuery. This commit tries to solve this problem because lots of signal hander calls gettimeofday for bookkeeping.

This is not true. User-level signal handlers are only called when returning from a syscall / interrupt (host-level signal) - they cannot hold a Graphene-level lock. Host-level signal handlers should be reentrant, hence they do not use locks at all (this means that they do not call functions holding any locks, such as DkSystemTimeQuery).

Keep in mind that recently a bug was discovered (#2156<https://github.com/oscarlab/graphene/pull/2156>) which could cause host-level singal to be nested, if the first one appeared while the code was in host-level vdso. That's why I asked you to verify it it fixes issues you are having, as this might have been the underlying issue to your deadlocks.

Reviewable<https://reviewable.io/reviews/oscarlab/graphene/2155#-:-MTME_nK28Rio_TI6THZ:b7o3fuv> status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski<https://github.com/boryspoplawski> and @ying2liu<https://github.com/ying2liu>)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/oscarlab/graphene/pull/2155#pullrequestreview-589669159>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIUG3QTTEIU2N4VJ4YBYLK3S6VPYHANCNFSM4XOAKZSQ>.

2021-02-16 23:35 UTC, ying2liu commented
I ran 80000 tests and didn’t see the deadlock. It seems that #2156 has fixed the deadlock of _DkSystemTimeQuery().

Thanks

Ying

From: Liu, Ying2
Sent: Friday, February 12, 2021 11:08 AM
To: oscarlab/graphene <reply@reply.github.com>; oscarlab/graphene <graphene@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [oscarlab/graphene] fix the deadlock of _DkSystemTimeQuery() (#2155)

I will run some tests using #2156.

Thanks

Ying

From: Borys Popławski <notifications@github.com<mailto:notifications@github.com>>
Sent: Friday, February 12, 2021 9:23 AM
To: oscarlab/graphene <graphene@noreply.github.com<mailto:graphene@noreply.github.com>>
Cc: Liu, Ying2 <ying2.liu@intel.com<mailto:ying2.liu@intel.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [oscarlab/graphene] fix the deadlock of _DkSystemTimeQuery() (#2155)


@boryspoplawski commented on this pull request.

For the future: pleas respond directly in reviewable or at least github, responding via emials completely breaks formatting.

Yes, signal handler is reentrant, but it is an async signal and might be called in a thread just within _DkSystemTimeQuery and holding the lock. This would cause recursive locking and dead lock if the handler calls gettimeofdata/_DkSystemTimeQuery. This commit tries to solve this problem because lots of signal hander calls gettimeofday for bookkeeping.

This is not true. User-level signal handlers are only called when returning from a syscall / interrupt (host-level signal) - they cannot hold a Graphene-level lock. Host-level signal handlers should be reentrant, hence they do not use locks at all (this means that they do not call functions holding any locks, such as DkSystemTimeQuery).

Keep in mind that recently a bug was discovered (#2156<https://github.com/oscarlab/graphene/pull/2156>) which could cause host-level singal to be nested, if the first one appeared while the code was in host-level vdso. That's why I asked you to verify it it fixes issues you are having, as this might have been the underlying issue to your deadlocks.

Reviewable<https://reviewable.io/reviews/oscarlab/graphene/2155#-:-MTME_nK28Rio_TI6THZ:b7o3fuv> status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski<https://github.com/boryspoplawski> and @ying2liu<https://github.com/ying2liu>)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/oscarlab/graphene/pull/2155#pullrequestreview-589669159>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIUG3QTTEIU2N4VJ4YBYLK3S6VPYHANCNFSM4XOAKZSQ>.

2021-02-17 19:56 UTC, closed without merging