[Pal/Linux] Change `ADDR_IN_PAL` to `ADDR_IN_PAL_OR_VDSO`
oscarlab/graphene pull request #2156
Opened 2021-02-12 02:05 UTC by boryspoplawski

## Description of the changes 
When an async exception triggers, LibOS needs to know whether it
happened while inside PAL code. Since Linux-PAL sometimes call VDSO
functions, they need to be accounted for as well.

2021-02-12 08:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFMy2Es5gkGA-IBIr:-MTKFMy2Es5gkGA-IBIs:b5knxqz) (no related file):*
Linux-SGX could do the same, right? It doesn't do it now (afaik), but it can surely do it in the future.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTKFWAt-J-ljoI5gh6C:b-mu36hg) (no related file):*
Why not:
1. Replace the naive `ADDR_IN_PAL()` macro with a proper function `is_in_pal()`
2. This function is initialized with results of parsing `/proc/self/maps` to find all maps with permission `x`
3. For each PAL, a common PAL initialization routine should parse `/proc/self/maps` right-before jumping into LibOS (so we don't have any LibOS-related VMAs yet) and mark all `x`-permission VMAs as "in PAL".

---


<!-- Sent from Reviewable.io -->

2021-02-12 13:49 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFMy2Es5gkGA-IBIr:-MTLUF5c4SD7NRcERssf:b2szx65) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Linux-SGX could do the same, right? It doesn't do it now (afaik), but it can surely do it in the future.
</blockquote></details>

Linux-SGX needs to do a ocall anyway and we are only interested in trusted part (which doesn't and never will use VDSO, at least direclty).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTLUef8A7xEuIygO_AD:b-2wbvan) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not:
1. Replace the naive `ADDR_IN_PAL()` macro with a proper function `is_in_pal()`
2. This function is initialized with results of parsing `/proc/self/maps` to find all maps with permission `x`
3. For each PAL, a common PAL initialization routine should parse `/proc/self/maps` right-before jumping into LibOS (so we don't have any LibOS-related VMAs yet) and mark all `x`-permission VMAs as "in PAL".
</blockquote></details>

1) Possible.
2,3) This would make no sense for some PALs (like Linux-SGX, we care about the trusted part only).
We could do that only for specific PALs (here: Linux). Should I?
cc @mkow 

---


<!-- Sent from Reviewable.io -->

2021-02-12 14:54 UTC, boryspoplawski commented
Jenkins, retest this please (jenkins internal failure)

2021-02-13 16:11 UTC, boryspoplawski commented
Jenkins, retest this please (testing new nodes)

2021-02-13 16:16 UTC, boryspoplawski commented
Jenkins, retest this please (testing new nodes)

2021-02-14 01:22 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTT5fum9YV0nDaZOJlz:bnou47q) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) Possible.
2,3) This would make no sense for some PALs (like Linux-SGX, we care about the trusted part only).
We could do that only for specific PALs (here: Linux). Should I?
cc @mkow 
</blockquote></details>

I don't like 2 and 3, they look complicated and brittle (e.g. what about libraries which are loaded lazily? you'll silently miss them and reintroduce this hard-to-reproduce and hard-to-pinpoint bug).

What about the idea we discussed on priv, about having the LibOS address range and just checking if something is outside it? Would be trivial and correct. The only problem with it, as Borys mentioned, is that we might not want to have a separate address range for LibOS in the future, but I think this requires a major redesign and we can think about this problem when doing this redesign.

---


<!-- Sent from Reviewable.io -->

2021-02-14 19:55 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTX67TQAG0Iwie84Lop:bk0pgth) (no related file):*
> but I think this requires a major redesign and we can think about this problem when doing this redesign.
As far as I remember, LibOS part (vma bookkeeping) should be ready for such change, so doesn't sound like a major redesign.

---


<!-- Sent from Reviewable.io -->

2021-02-15 00:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTY70KbA9sM0Rpn_G8n:b-2it4vd) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> but I think this requires a major redesign and we can think about this problem when doing this redesign.
As far as I remember, LibOS part (vma bookkeeping) should be ready for such change, so doesn't sound like a major redesign.
</blockquote></details>

But how do you imagine solving the problem we have here without the address space separation? For me your current approach looks like something which will blow up eventually and again lead to hours of debugging...

---


<!-- Sent from Reviewable.io -->

2021-02-15 01:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTYIz258EejzHV4vyGM:b3tjj96) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But how do you imagine solving the problem we have here without the address space separation? For me your current approach looks like something which will blow up eventually and again lead to hours of debugging...
</blockquote></details>

As long as we build PAL statically nothing should blow up. We could also add a comment in makefile, where we set `-static` for PAL, about this function.

---


<!-- Sent from Reviewable.io -->

2021-02-15 02:10 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTYQVu-2y2RtC9uBjIs:b-sdbnhk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

As long as we build PAL statically nothing should blow up. We could also add a comment in makefile, where we set `-static` for PAL, about this function.
</blockquote></details>

Ok, please add such a comment then.

---
___
*[Pal/src/host/Linux/db_rtld.c, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTYREvL9aVqMjcGk1Lm:-MTYREvL9aVqMjcGk1Ln:b15mujl) ([raw file](https://github.com/oscarlab/graphene/blob/55f517f05fe1a11e8ab326ec020dc4030fef47b7/Pal/src/host/Linux/db_rtld.c#L76)):*
> ```C
>         switch (ph->p_type) {
>             case PT_LOAD:
>                 /* Assumes that VDSO has only one PT_LOAD segment. */
> ```

we should actually assert this... but I'm not blocking, this issues was already here before


<!-- Sent from Reviewable.io -->

2021-02-15 08:04 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFMy2Es5gkGA-IBIr:-MTZhKuz8BvjIxF5DqKk:b-dkjlih) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Linux-SGX needs to do a ocall anyway and we are only interested in trusted part (which doesn't and never will use VDSO, at least direclty).
</blockquote></details>

Ok, this is true.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTZhSii-Ecdca9DxjBi:bci3vfe) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, please add such a comment then.
</blockquote></details>

LGTM, my bad. I didn't realize this issue doesn't exist in Linux-SGX PAL.

---


<!-- Sent from Reviewable.io -->

2021-02-16 18:20 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTg0A0a9k2f2cDtR-DN:b-b8r3bw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

LGTM, my bad. I didn't realize this issue doesn't exist in Linux-SGX PAL.
</blockquote></details>

I couldn't find a place to put it. I wanted to add an assert on `readelf -a libpal.so | fgrep -q NEEDED` being empty, but that would be PAL-Linux specific check, but `libpal.so` is a generic makefile target...

---
___
*[Pal/src/host/Linux/db_rtld.c, line 76 at r1](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTYREvL9aVqMjcGk1Lm:-MTg3_Vd3EdPZ3l9St9s:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/55f517f05fe1a11e8ab326ec020dc4030fef47b7/Pal/src/host/Linux/db_rtld.c#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

we should actually assert this... but I'm not blocking, this issues was already here before
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 21:35 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-apps please (apache build failed with `util_expr_eval.c:(.text+0x112b): undefined reference to `ap_expr_yylex_init'`, broken disc?)

2021-02-16 22:15 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTgtdkoB816HdAYb9kR:bowmvua) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I couldn't find a place to put it. I wanted to add an assert on `readelf -a libpal.so | fgrep -q NEEDED` being empty, but that would be PAL-Linux specific check, but `libpal.so` is a generic makefile target...
</blockquote></details>

If this is a shared file between all PALs and one of them has some requirements, then I'm fine with asserting them for that common file. Why not?

---
___
*[Pal/src/host/Linux/db_rtld.c, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTgtwnw1EBKKSxl3gS4:-MTgtwnx0wEg4oPMZ1eZ:b8orhwi) ([raw file](https://github.com/oscarlab/graphene/blob/9d6b9feef79a63904ac6cc27569e24af1feebabf/Pal/src/host/Linux/db_rtld.c#L89)):*
> ```C
> 
>     if (pt_loads_count != 1) {
>         /* This code assumes that VDSO has exactly one PT_LOAD segment. */
> ```

Shouldn't we print an error and fail here? Silently continuing will:
a) make the bug you fixed here reappear
b) we may never learn that some systems has such a problematic vdso


<!-- Sent from Reviewable.io -->

2021-02-16 22:19 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTgv16r1OcVf2FSO3Wj:bhij0b9) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If this is a shared file between all PALs and one of them has some requirements, then I'm fine with asserting them for that common file. Why not?
</blockquote></details>

This file is not shared by all PALs, it just has the very same build recipe.

---
___
*[Pal/src/host/Linux/db_rtld.c, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTgtwnw1EBKKSxl3gS4:-MTgv9DL9uubRf8miJU_:bvrub8y) ([raw file](https://github.com/oscarlab/graphene/blob/9d6b9feef79a63904ac6cc27569e24af1feebabf/Pal/src/host/Linux/db_rtld.c#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we print an error and fail here? Silently continuing will:
a) make the bug you fixed here reappear
b) we may never learn that some systems has such a problematic vdso
</blockquote></details>

1) this function does not return errors and callers do not handle them.
2) no it will not. If this code doesn't set vdso address, Graphene will not use it (we skip setting on errors).


<!-- Sent from Reviewable.io -->

2021-02-16 22:26 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTgwPsy7fAg-1k8Z0Oq:b-m9ylcm) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This file is not shared by all PALs, it just has the very same build recipe.
</blockquote></details>

Ah, then maybe just an `if` on `$(SGX)`?

---
___
*[Pal/src/host/Linux/db_rtld.c, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTgtwnw1EBKKSxl3gS4:-MTgwZGB1wRiP-vMRYoo:b-8wcn4j) ([raw file](https://github.com/oscarlab/graphene/blob/9d6b9feef79a63904ac6cc27569e24af1feebabf/Pal/src/host/Linux/db_rtld.c#L89)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) this function does not return errors and callers do not handle them.
2) no it will not. If this code doesn't set vdso address, Graphene will not use it (we skip setting on errors).
</blockquote></details>

Ah, so we aren't using vsdo at all in this case? Then it's fine, but maybe just log a warning then?


<!-- Sent from Reviewable.io -->

2021-02-17 16:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTKFWAt-J-ljoI5gh6B:-MTkcu-Y6dHNEVwIYFYM:b-2j2qhz) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, then maybe just an `if` on `$(SGX)`?
</blockquote></details>

Rather on `Pal-Linux` as it's that-Pal-specific.
Done.

---
___
*[Pal/src/host/Linux/db_rtld.c, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene/2156#-MTgtwnw1EBKKSxl3gS4:-MTkbXqDDfyE65u93WG9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9d6b9feef79a63904ac6cc27569e24af1feebabf/Pal/src/host/Linux/db_rtld.c#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, so we aren't using vsdo at all in this case? Then it's fine, but maybe just log a warning then?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 16:40 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-17 17:01 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-17 19:23 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-17 19:52 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2156)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-17 19:56 UTC, merged