[Docs] Add documentation on Attestation
oscarlab/graphene pull request #2159
Opened 2021-02-16 10:53 UTC by dimakuv

## Description of the changes 

The new document describes three levels of remote-attestation flows available in Graphene:
1. low-level `/dev/attestation`,
2. mid-level RA-TLS,
3. high-level Secret Provisioning.

The document copy-pastes some info from https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/tools/README.rst -- we may want to remove this README file from there finally (so we have only one place -- ReadTheDocs -- to modify in the future).

## How to test this PR? 

Just documentation.

2021-02-17 01:22 UTC, mkow requested changes
Nice doc, we really needed it :)

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159#-:-MThZaFZCPqAOdnrHBCE:b-d3vy3a)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/attestation.rst, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh2I_x3sEMWKRUcFX3:-MTh2I_x3sEMWKRUcFX4:bzi6bko) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L3)):*
> ```reStructuredText
> Attestation
> ===========
> ```

Please add links to the glossary everywhere, like:
```
:term:`TEE`
```
___
*[Documentation/attestation.rst, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh2vrs7wFrJsxh3mfH:-MTh2vrs7wFrJsxh3mfI:b-gdxu81) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L7)):*
> ```
> in a correct up-to-date TEE
> ```

Comma after "correct", I think.
___
*[Documentation/attestation.rst, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh3J1m2P5pOcp40cfd:-MTh3J1m2P5pOcp40cfe:bptp4rv) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L14)):*
> ```
> attestation flows are designed to be TEE-agnostic, we discuss only *Intel SGX*
> remote attestation flows.
> ```

I'd add a parenthesis saying that this is because that's the only one currently implemented.
___
*[Documentation/attestation.rst, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh5ZaF2MxLiEEkWFpC:-MTh5ZaF2MxLiEEkWFpD:b-boiih0) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L58)):*
> ```reStructuredText
>   ``/dev/attestation/user_report_data``. Otherwise the obtained attestation
>   quote will contain incorrect or stale user report data.
> ```

I'd mention somewhere here that these files are process-local, so there's no need to add locking between processes setting the user data and reading quote.
___
*[Documentation/attestation.rst, line 65 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThOgEUDwOVptJ4oMGB:-MThOgEUDwOVptJ4oMGC:bsih8s9) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L65)):*
> ```
> Typically, the application will write some unique identifier of the TEE
> into ``/dev/attestation/user_report_data``
> ```

Hmm, this sounds weird, why would anyone use it for an identifier instead of the pubkey? How could this be useful for anything?
___
*[Documentation/attestation.rst, line 88 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThQoPv14Zwjn7gX0oZ:-MThQoPv14Zwjn7gX0o_:b16k1el) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L88)):*
> ```reStructuredText
>     int fd2 = open("/dev/attestation/quote", O_RDONLY);
>     read(fd2, &quote, sizeof(quote));
>     close(fd2);
> ```

You already omitted error-checking from this snippet, so I think we can also drop closing FDs.
___
*[Documentation/attestation.rst, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThSYx2A0Z8blPlvqG3:-MThSYx2A0Z8blPlvqG4:b-woadj5) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L112)):*
> ```reStructuredText
> verification of the attestation quote. Instead, the remote user is encouraged to
> use the :program:`quote_dump`, :program:`ias_request` and
> :program:`verify_ias_report` tools shipped together with Graphene (for
> ```

Hmm, shouldn't that `:program:` generate a clickable link to their documentation? Doesn't work for me.
/summon @woju
___
*[Documentation/attestation.rst, line 146 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThTG2eCaEKtvEQ-v4y:-MThTG2eCaEKtvEQ-v4z:bxai4dp) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L146)):*
> ```
> It must be loaded
> ```

This "it" sounds like referring to the certificate, not the library.
___
*[Documentation/attestation.rst, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThT_cb8rKFwSVm4vXR:-MThT_cb8rKFwSVm4vXS:b-ssurih) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L156)):*
> ```
> linkable/unlinkable attestation policy
> ```

Isn't this rather "mode" than "policy"?
___
*[Documentation/attestation.rst, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThTnXF2h5C7px8NcgF:-MThTnXF2h5C7px8NcgG:b-63qnrg) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L161)):*
> ```
> "<empty string>"
> ```

I don't get this. If it's supposed to be empty, then why isn't it just `""`?
___
*[Documentation/attestation.rst, line 180 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThV1Bu9gGoOB6AFvCT:-MThV1Bu9gGoOB6AFvCU:b-pthfcw) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L180)):*
> ```
> typically linked into client applications
> ```

This categorization into client/server is IMO misleading, it can be both ways and client/server doesn't really say which side is a TEE and which is doing the verification.

ditto for this whole file
___
*[Documentation/attestation.rst, line 329 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThZK7T-B57_p87W0wD:-MThZK7T-B57_p87W0wE:bijxieg) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L329)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> This library is typically linked into a (normal non-enclavized)
> ```

`normal non-enclavized` -> `normal, non-enclavized`


<!-- Sent from Reviewable.io -->

2021-02-17 09:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: 1 of 5 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/attestation.rst, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh2I_x3sEMWKRUcFX3:-MTjJU8D5KEWQ6xIsE59:b-kvsxe4) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add links to the glossary everywhere, like:
```
:term:`TEE`
```
</blockquote></details>

Done. Added a lot of stuff in the glossary.
___
*[Documentation/attestation.rst, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh2vrs7wFrJsxh3mfH:-MTjJZhM2dZ57Xvo480u:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> in a correct up-to-date TEE
> ```

Comma after "correct", I think.
</blockquote></details>

Done.
___
*[Documentation/attestation.rst, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh3J1m2P5pOcp40cfd:-MTjJnBj9ZvGDJdUUFqG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> attestation flows are designed to be TEE-agnostic, we discuss only *Intel SGX*
> remote attestation flows.
> ```

I'd add a parenthesis saying that this is because that's the only one currently implemented.
</blockquote></details>

Done.
___
*[Documentation/attestation.rst, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTh5ZaF2MxLiEEkWFpC:-MTjK2tB2OCE_uDGEail:b-7794lb) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd mention somewhere here that these files are process-local, so there's no need to add locking between processes setting the user data and reading quote.
</blockquote></details>

Done. A bit lower in the text.
___
*[Documentation/attestation.rst, line 65 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThOgEUDwOVptJ4oMGB:-MTjK92yB5kN6OX8X-Ry:b-cdapyj) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Typically, the application will write some unique identifier of the TEE
> into ``/dev/attestation/user_report_data``
> ```

Hmm, this sounds weird, why would anyone use it for an identifier instead of the pubkey? How could this be useful for anything?
</blockquote></details>

I mention below that typically it is populated with a (hash of) public key. But technically it could be an arbitrary string. Maybe there are some other cryptographic schemes that could rely on something not based on public-private-key crypto.

But I noticed that I used `unique private key` below. I fixed it to `unique public key`.
___
*[Documentation/attestation.rst, line 88 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThQoPv14Zwjn7gX0oZ:-MTjKk0L0TjhkgszhRik:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You already omitted error-checking from this snippet, so I think we can also drop closing FDs.
</blockquote></details>

Done.
___
*[Documentation/attestation.rst, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThSYx2A0Z8blPlvqG3:-MTjL0DC9vt6C9lOJHbg:b-a0s9pz) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L112)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, shouldn't that `:program:` generate a clickable link to their documentation? Doesn't work for me.
/summon @woju
</blockquote></details>

It doesn't look like it generates anything. We also have "bold non-clickable text" in other places where we use `:program:`.
___
*[Documentation/attestation.rst, line 146 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThTG2eCaEKtvEQ-v4y:-MTjLK8MDO7XyRaGGWQu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> It must be loaded
> ```

This "it" sounds like referring to the certificate, not the library.
</blockquote></details>

Done.
___
*[Documentation/attestation.rst, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThT_cb8rKFwSVm4vXR:-MTjLeNzE9mU-pFrFHAl:b-qq48jd) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> linkable/unlinkable attestation policy
> ```

Isn't this rather "mode" than "policy"?
</blockquote></details>

Done. True.
___
*[Documentation/attestation.rst, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThTnXF2h5C7px8NcgF:-MTjLraFDVhIYe1IXBXm:bs1jhtx) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> "<empty string>"
> ```

I don't get this. If it's supposed to be empty, then why isn't it just `""`?
</blockquote></details>

Done. It was me trying to confuse everyone.
___
*[Documentation/attestation.rst, line 180 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThV1Bu9gGoOB6AFvCT:-MTjNJ3p5-9OJld5Y05w:bsf74u4) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> typically linked into client applications
> ```

This categorization into client/server is IMO misleading, it can be both ways and client/server doesn't really say which side is a TEE and which is doing the verification.

ditto for this whole file
</blockquote></details>

Done. I agree that it is a confusing terminology for RA-TLS, so I removed it from there. But I still kept `client - service` dichotomy in the Secret Provisioning description -- because there we actually have a service that waits for client connections. Hopefully it is clearer now.
___
*[Documentation/attestation.rst, line 329 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThZK7T-B57_p87W0wD:-MTjOpfB-BPlpVCfOC_4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L329)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`normal non-enclavized` -> `normal, non-enclavized`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 14:34 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[Documentation/attestation.rst, line 65 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThOgEUDwOVptJ4oMGB:-MTkKWINBkqUvQWZAd7U:b-50r1r) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L65)):*
Still, "unique identifier" sounds like just an ID, which doesn't (IMO) make any sense in any real scenario. My problem with this description is that you don't say "arbitrary string", but "unique identifier".

> Maybe there are some other cryptographic schemes that could rely on something not based on public-private-key crypto.

But still, this wouldn't be an "ID".

Basically, if it's not a public key, then the only scenario I could imagine would be a "secret-less" enclave - just doing some computations and attesting that the result was actually calculated from some input. But then user data still wouldn't be an "ID", but a hash  of the (input, output) tuple.
___
*[Documentation/attestation.rst, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThTnXF2h5C7px8NcgF:-MTkOEqEErXGm0aYx7dW:b32vhw) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. It was me trying to confuse everyone.
</blockquote></details>

:)
___
*[Documentation/attestation.rst, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkJJpL4wyZ96WXPrWc:-MTkJJpL4wyZ96WXPrWd:bgsysw9) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/attestation.rst#L7)):*
> ```
> application runs in a correct
> ```

I didn't notice this previously, but attestation has nothing to do with correctness.
___
*[Documentation/attestation.rst, line 12 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkJSur91PufJlTrcGH:-MTkJSusCE-cAgVfkCoh:bm0wn7g) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/attestation.rst#L12)):*
> ```reStructuredText
> 
> There are two types of attestation: :term:`Local Attestation` and
> :term:`Remote Attestation`.  Local attestation is used when two TEEs run on the
> ```

double space
___
*[Documentation/sgx-intro.rst, line 191 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkFVVQ0ngPjdC0PlEU:-MTkFVVQ0ngPjdC0PlEV:b72tlo) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L191)):*
> ```reStructuredText
>       A |~| set of "system" enclaves concerned with starting and attesting other
>       enclaves. Intel provides reference implementations of these enclaves,
>       though other companies may write their own implementations.
> ```

Could you start the description with expanding the abbreviation "AE"?
___
*[Documentation/sgx-intro.rst, line 207 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkFmGa5wjTTwrB3YYq:-MTkFmGa5wjTTwrB3YYr:b-7shhy9) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L207)):*
> ```
> Attestation is a mechanism to prove the correctness
> ```

It's not proving the correctness, the enclave can still have bugs. It's just proving that it runs on a real hardware and the initial state was as expected.
___
*[Documentation/sgx-intro.rst, line 226 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkGUaKEhfzI_CHDnm2:-MTkGUaL6qiWOgp5c7MO:b-cdz9dz) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L226)):*
> ```reStructuredText
> 
>          :term:`Local Attestation`
>             Description of Local Attestation
> ```

While we're here, I'd drop this "Description of Local Attestation" text here and below, it's not really useful.
___
*[Documentation/sgx-intro.rst, line 430 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkI14IBmhicvHMXhpo:-MTkI14IBmhicvHMXhpp:b-kbjuwx) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L430)):*
> ```
> The SGX quote is the proof of correctness
> ```

ditto
___
*[Documentation/sgx-intro.rst, line 436 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkIDEv1WlQFU1zk_D9:-MTkIDEv1WlQFU1zk_DA:b-yrl2k1) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L436)):*
> ```
> publicly known key of the Quoting Enclave
> ```

Is this really the QE key? Not some other key, known only by IAS? At least in EPID.
___
*[Documentation/sgx-intro.rst, line 443 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkIaY-9SM1M1XeECb6:-MTkIaY-9SM1M1XeECb7:b-5x7zj9) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L443)):*
> ```
> enclave measurements
> ```

Plural?
___
*[Documentation/sgx-intro.rst, line 471 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkItR-4Q7L0c1T5R2s:-MTkItR-4Q7L0c1T5R2t:b-ecjris) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L471)):*
> ```
> no one have access to the data
> ```

nitpick: the code running inside has :)
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 192 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTk9Xlj7NyjyJRH0oy7:-MTk9Xlk7mDpTxL4NGa3:b-1lcjsl) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Pal/src/host/Linux-SGX/tools/README.rst#L192)):*
> ```reStructuredText
> service provisions the secrets to the client. The established TLS channel may be
> either closed after provisioning these initial secrets or may be further used by
> both parties for continued secure communication.
> ```

I got lost here, which side, client of service is running in a TEE?


<!-- Sent from Reviewable.io -->

2021-02-17 15:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: 2 of 5 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/attestation.rst, line 65 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThOgEUDwOVptJ4oMGB:-MTkc22g6_Ox0a6absj5:baf2ti0) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L65)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still, "unique identifier" sounds like just an ID, which doesn't (IMO) make any sense in any real scenario. My problem with this description is that you don't say "arbitrary string", but "unique identifier".

> Maybe there are some other cryptographic schemes that could rely on something not based on public-private-key crypto.

But still, this wouldn't be an "ID".

Basically, if it's not a public key, then the only scenario I could imagine would be a "secret-less" enclave - just doing some computations and attesting that the result was actually calculated from some input. But then user data still wouldn't be an "ID", but a hash  of the (input, output) tuple.
</blockquote></details>

Done. Got it. Since I already talk about `arbitrary string` above, here I just replaced with the classic example of the "hash of the public key".
___
*[Documentation/attestation.rst, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkJJpL4wyZ96WXPrWc:-MTkapvc8Z25mgnLXCus:bmr1pyh) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/attestation.rst#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> application runs in a correct
> ```

I didn't notice this previously, but attestation has nothing to do with correctness.
</blockquote></details>

Done. True, this was a wrong word. Hopefully the new definition is correct and concise.
___
*[Documentation/attestation.rst, line 12 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkJSur91PufJlTrcGH:-MTkbVGRD_DHRXVGPudp:begwn35) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/attestation.rst#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Done. Did a grep and hopefully fixed all such occurrences. I don't know how these creep in.
___
*[Documentation/sgx-intro.rst, line 191 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkFVVQ0ngPjdC0PlEU:-MTkcLKlCjoqSTY-soRw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L191)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you start the description with expanding the abbreviation "AE"?
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 207 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkFmGa5wjTTwrB3YYq:-MTkcm3eEg0mCdpxFiaE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Attestation is a mechanism to prove the correctness
> ```

It's not proving the correctness, the enclave can still have bugs. It's just proving that it runs on a real hardware and the initial state was as expected.
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 226 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkGUaKEhfzI_CHDnm2:-MTkcrCm4CqzOrfW1gv9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L226)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're here, I'd drop this "Description of Local Attestation" text here and below, it's not really useful.
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 430 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkI14IBmhicvHMXhpo:-MTkczP6EAoCmRPHnKc3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L430)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> The SGX quote is the proof of correctness
> ```

ditto
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 436 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkIDEv1WlQFU1zk_D9:-MTkdm8ZAMLG90dto0_A:b-m8plli) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L436)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> publicly known key of the Quoting Enclave
> ```

Is this really the QE key? Not some other key, known only by IAS? At least in EPID.
</blockquote></details>

Done. Yes, it's not really a "publicly known key". It depends on whether we talk about EPID or DCAP. In the former case, Intel controls the measurements of QE, and the SGX Quote contains measurements of the QE, so then IAS can verify first the QE authenticity and then the SGX Quote authenticity. In the latter case, the QE is backed by a certificate chain that typically ends in the Intel PCS root certificate (but may be rooted in e.g. Microsoft cert that is trusted by public).

So given these complexities, I replaced with a vague `tied to the identity of QE`.
___
*[Documentation/sgx-intro.rst, line 443 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkIaY-9SM1M1XeECb6:-MTkevOXDD72_ws2c6Ma:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L443)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> enclave measurements
> ```

Plural?
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 471 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkItR-4Q7L0c1T5R2s:-MTkfATUDD5Zh7WHS-_Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L471)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> no one have access to the data
> ```

nitpick: the code running inside has :)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/README.rst, line 192 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTk9Xlj7NyjyJRH0oy7:-MTkfTKd74n6M5QVB-WZ:bw1dnam) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Pal/src/host/Linux-SGX/tools/README.rst#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I got lost here, which side, client of service is running in a TEE?
</blockquote></details>

Done. I added `enclavized` to the `client`. The service runs on a trusted machine and gives secrets to clients (which are enclaves).

Client = inside enclave
Service = no enclave, trusted


<!-- Sent from Reviewable.io -->

2021-02-17 16:09 UTC, dimakuv commented
Jenkins, retest Jenkins please (`sendfile08` in LTP failed, known issue)

2021-02-17 16:51 UTC, mkow reviewed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Documentation/sgx-intro.rst, line 191 at r2](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTkFVVQ0ngPjdC0PlEU:-MTkryCE5cro6MhQD2WD:bwe9kha) ([raw file](https://github.com/oscarlab/graphene/blob/7a511bf7f60034a7ef7dc445457687ff3061ba9c/Documentation/sgx-intro.rst#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, I actually missed that this is a double-entry (I missed the line above "AE"). But the current version is still better IMO.


<!-- Sent from Reviewable.io -->

2021-02-17 17:04 UTC, vijaydhanraj commented
Thanks, @dimakuv. Can we please add a high-level flow diagram on how remote attestation works. This will be super helpful for beginners like me :). Not blocking this comment, just a request.





<!-- Sent from Reviewable.io -->

2021-02-17 17:07 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/attestation.rst, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThSYx2A0Z8blPlvqG3:-MTkv6yp14k9u5-4doI0:b-yxhriz) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It doesn't look like it generates anything. We also have "bold non-clickable text" in other places where we use `:program:`.
</blockquote></details>

https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-program (Nowhere this claims to generate a link).
There is also https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-command, which is basicaly `:program:` with path, arguments, etc., also doesn't generate link. If you need link to something, do a link: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role.

Alternatively there is https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-manpage, but this would requiree https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-manpages_url and this doesn't work out of the box (i.e. you can't just set this to `https://graphene.rtfd.io/en/latest/manpages/{path}`, it needs HTTP redirects to be set up server-side, which is possible in RTD admin interface, but IIUC needs to be done manually for each manpage).


<!-- Sent from Reviewable.io -->

2021-02-17 19:56 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Documentation/attestation.rst, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/2159#-MThSYx2A0Z8blPlvqG3:-MTlYZL2-XCEoPRlLiH7:b-ckzdlg) ([raw file](https://github.com/oscarlab/graphene/blob/faff3fbfea8289f0c2dc16b37fe7ce8cfa230311/Documentation/attestation.rst#L112)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-program (Nowhere this claims to generate a link).
There is also https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-command, which is basicaly `:program:` with path, arguments, etc., also doesn't generate link. If you need link to something, do a link: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#ref-role.

Alternatively there is https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-manpage, but this would requiree https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-manpages_url and this doesn't work out of the box (i.e. you can't just set this to `https://graphene.rtfd.io/en/latest/manpages/{path}`, it needs HTTP redirects to be set up server-side, which is possible in RTD admin interface, but IIUC needs to be done manually for each manpage).
</blockquote></details>

Ok, I see now, I thought it's supposed to refer to one of the binaries/apps documented in here. I'm fine with leaving it as is then, although maybe we should use those "ref-roles" to link to the corresponding page? Could be useful for users.


<!-- Sent from Reviewable.io -->

2021-02-18 10:47 UTC, dimakuv reviewed
@vijaydhanraj Added three diagrams.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159#-:-MTojstA20aWpjB12nnO:b-ycjncu)* status: 3 of 8 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-02-18 12:38 UTC, mkow requested changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/attestation.rst, line 207 at r4](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTp73Od5MHqFg6Cxi4w:-MTp73Of6lznhf9v23XF:b-ir7aoe) ([raw file](https://github.com/oscarlab/graphene/blob/09f12c96d8dc47bda825b6e9d27b62059e5c5539/Documentation/attestation.rst#L207)):*
> ```reStructuredText
> .. image:: ./img/ratls.svg
>    :target: ./img/ratls.svg
>    :alt: Figure: The X.509 certificate generated by RA-TLS
> ```

There's a weird dot floating in the air at the bottom-left corner of this image, could you remove it?
___
*[Documentation/sgx-intro.rst, line 411 at r4](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTp8SDZ91NxeWqaCnHt:-MTp8SDZ91NxeWqaCnHu:b347v2u) ([raw file](https://github.com/oscarlab/graphene/blob/09f12c96d8dc47bda825b6e9d27b62059e5c5539/Documentation/sgx-intro.rst#L411)):*
> ```
> Older internet service
> ```

Not sure we should say it this way, sounds like it's deprecated (while EPID isn't deprecated for client machines).


<!-- Sent from Reviewable.io -->

2021-02-18 14:25 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: 6 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/attestation.rst, line 207 at r4](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTp73Od5MHqFg6Cxi4w:-MTpWZRqDeWs_8vfPff8:biwfn9r) ([raw file](https://github.com/oscarlab/graphene/blob/09f12c96d8dc47bda825b6e9d27b62059e5c5539/Documentation/attestation.rst#L207)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There's a weird dot floating in the air at the bottom-left corner of this image, could you remove it?
</blockquote></details>

Done. Oops, that's my PowerPoint skills :)
___
*[Documentation/sgx-intro.rst, line 411 at r4](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTp8SDZ91NxeWqaCnHt:-MTpWtN8B2UsmZ3E1Wsy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09f12c96d8dc47bda825b6e9d27b62059e5c5539/Documentation/sgx-intro.rst#L411)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Older internet service
> ```

Not sure we should say it this way, sounds like it's deprecated (while EPID isn't deprecated for client machines).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 14:43 UTC, mkow requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/sgx-intro.rst, line 411 at r4](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTp8SDZ91NxeWqaCnHt:-MTp_zpqCyRQ5ek7eEmC:b-xru1iv) ([raw file](https://github.com/oscarlab/graphene/blob/09f12c96d8dc47bda825b6e9d27b62059e5c5539/Documentation/sgx-intro.rst#L411)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now the keys overlap with `hash()` text :P

btw. from my experience, draw.io is much better than PowerPoint for such stuff ;)


<!-- Sent from Reviewable.io -->

2021-02-18 20:29 UTC, vijaydhanraj reviewed
Very nice, makes the EPID, DCAP flow much clearer to me. Thanks, @dimakuv.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159#-:-MTqVKpaEUnMG1Gvhrit:bbvt1im)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-02-19 09:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: 7 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/sgx-intro.rst, line 411 at r4](https://reviewable.io/reviews/oscarlab/graphene/2159#-MTp8SDZ91NxeWqaCnHt:-MTtXAvO5HfbSfdzs9h2:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/09f12c96d8dc47bda825b6e9d27b62059e5c5539/Documentation/sgx-intro.rst#L411)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now the keys overlap with `hash()` text :P

btw. from my experience, draw.io is much better than PowerPoint for such stuff ;)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-02-19 18:16 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-22 00:10 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2159)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-22 00:45 UTC, merged