[GSC] Allow in-kernel Intel SGX driver; improve GSC testing
oscarlab/graphene pull request #2165
Opened 2021-02-17 11:42 UTC by dimakuv

## Description of the changes 

Previously, GSC required to use an out-of-tree SGX driver (either the legacy one or the DCAP one) but could not support the in-kernel SGX driver (merged into Linux 5.11). This PR allows to specify the in-kernel SGX driver in the configuration file `config.yaml` for GSC.

This PR also fixes a couple tiny bugs in the testing Makefile.

## How to test this PR? 

GSC in Jenkins must succeed. Manual testing on Linux 5.11 with the in-kernel SGX driver is in progress.

2021-02-18 01:35 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Tools/gsc/templates/entrypoint.manifest.template, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2165#-MTmlQ_HBmWQd0HDuZ92:-MTmlQ_I-uvzUqOOeB-I:bbkyemg) ([raw file](https://github.com/oscarlab/graphene/blob/f7fc74b3f7133908bbde34bbcb479a25a00e8845/Tools/gsc/templates/entrypoint.manifest.template#L29)):*
> ```
> # TODO: provide a switch `--insecure_envs` similar to `--insecure_args` above.
> # The issue is documented at https://github.com/oscarlab/graphene/issues/1520.
> loader.insecure__use_host_env = 1
> ```

Hmm, do I understand correctly, that merging this PR will make GSC temporarily insecure? If that's the case, then I'd rather wait for this fix and squash it here.


<!-- Sent from Reviewable.io -->

2021-02-18 07:34 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: 0 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Tools/gsc/templates/entrypoint.manifest.template, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2165#-MTmlQ_HBmWQd0HDuZ92:-MTo2p9M9vE8HFFdTBPu:bxerrn6) ([raw file](https://github.com/oscarlab/graphene/blob/f7fc74b3f7133908bbde34bbcb479a25a00e8845/Tools/gsc/templates/entrypoint.manifest.template#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, do I understand correctly, that merging this PR will make GSC temporarily insecure? If that's the case, then I'd rather wait for this fix and squash it here.
</blockquote></details>

OK, let me revert the second commit then. Your understanding is correct, it makes GSC temporarily insecure (due to forwarded env vars).


<!-- Sent from Reviewable.io -->

2021-02-18 07:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Tools/gsc/templates/entrypoint.manifest.template, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2165#-MTmlQ_HBmWQd0HDuZ92:-MTo3E1LEGr9rMhetd99:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f7fc74b3f7133908bbde34bbcb479a25a00e8845/Tools/gsc/templates/entrypoint.manifest.template#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, let me revert the second commit then. Your understanding is correct, it makes GSC temporarily insecure (due to forwarded env vars).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 13:51 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-02-19 11:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: 3 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Tools/gsc/finalize_manifest.py, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene/2165#-MTtzj6I4TUKZeGvdT-e:-MTtzj6I4TUKZeGvdT-f:bcrq6sk) ([raw file](https://github.com/oscarlab/graphene/blob/36ccd3ea4c957c8ad8cb92cf0ba3697a3ab90e8b/Tools/gsc/finalize_manifest.py#L35)):*
> ```Python
>                             f'|^{cwd}/('
>                                 r'.*\.manifest'
>                                 r'|finalize_manifest\.py)$')
> ```

FYI: This is simply not needed anymore, now that we always use the absolute paths for GSC-related files.
___
*[Tools/gsc/finalize_manifest.py, line 88 at r3](https://reviewable.io/reviews/oscarlab/graphene/2165#-MTtzVGx8sN8qaiV4ELF:-MTtzVGx8sN8qaiV4ELG:bql28d8) ([raw file](https://github.com/oscarlab/graphene/blob/c97c300b383edf2ac1802d371d9c5989986c6d45/Tools/gsc/finalize_manifest.py#L88)):*
> ```Python
>     env.globals.update({'library_paths': generate_library_paths(), 'env_path': os.getenv('PATH')})
> 
>     manifest = '/entrypoint.manifest'
> ```

FYI: I missed to change this to absolute path (from the incorrect relative path). This should have gone into already-merged PR https://github.com/oscarlab/graphene/pull/2151, but I failed to notice that. So I added it in this PR.


<!-- Sent from Reviewable.io -->

2021-02-19 18:45 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-23 11:26 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-23 11:37 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2165)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-23 12:01 UTC, mkow commented
Jenkins, retest Jenkins please (openssl failed with `unable to write 'random state'`, disk full maybe?)

2021-02-23 16:02 UTC, mkow commented
Jenkins, retest Jenkins please (`apps.LTP.kill11` failed, known issue)

2021-02-23 16:18 UTC, merged