[Pal/Linux-SGX] Fix stack unwinding on enclave exit
oscarlab/graphene pull request #2168
Opened 2021-02-17 16:47 UTC by pwmarcz

## Description of the changes 

A previous change in LibOS started storing fake syscall return address in R8. This broke stack unwinding when the stack spans both LibOS syscall and SGX OCALL, because we had no CFI directives for recovering register values except for RBP, RSP and RIP,	and the value of R8 was lost.

This change adds proper CFI to enclave exit code, which is unfortunately pretty tricky due to switching stacks. As a result
GDB should have access to all saved registers. 

There is a detailed explanation in the comment.

Fixes #2160.

## How to test this PR? 

This fixes the debug regression test under SGX (we didn't notice it break because the configuration is not on Jenkins yet). 

You can run it using `SGX=1 .../graphene/Scripts/run-pytest -k TC_50_GDB` in `LibOS/shim/test/regression`. Make sure to compile with `DEBUG=1`.

2021-02-17 20:38 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 858 at r1](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTlh-IH8Ck6aOKUERaJ:-MTlh-IH8Ck6aOKUERaK:b-wy7urs) ([raw file](https://github.com/oscarlab/graphene/blob/4763cc3128cf202356848316486a3f04557c3230/Pal/src/host/Linux-SGX/enclave_entry.S#L858)):*
> ```
> 	# Inserting a fake `__morestack` function is unfortunately the only way to keep GDB happy when
> 	# switching stacks. Here, an additional complication is that the registers are saved on an
> 	# signal stack, which might be different than application stack. As a result we have to insert
> ```

`an signal stack` -> `a signal stack`


<!-- Sent from Reviewable.io -->

2021-02-17 21:19 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTlob_t3_SWvlHuf2Rp:-MTlob_u0ASuC_YwJtlR:b-inq8zv) (no related file):*
LibOS does not use `r8`, I do not understand the commit message...
Why do we need two "fake frames"? I'm quite lost in all of this tbh.
Also: not clearing callee-saved registers (ofc in debug builds only) seems to be enough - in LibOS we intentionally use r14, which is callee saved, to keep fake return address.
Check out https://github.com/boryspoplawski/graphene/commits/borys/backtrace_test - I was able to get a clear backtrace spanning untrusted PAL <-> trusted PAL <-> LibOS <-> user program
Does it miss some edge case?

---


<!-- Sent from Reviewable.io -->

2021-02-18 02:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTlob_t3_SWvlHuf2Rp:-MTmnstb0Nsj6py-AK_R:b8a623m) (no related file):*
>LibOS does not use r8, I do not understand the commit message...

My mistake. LibOS uses R14, and that's what we need to preserve.

>Why do we need two "fake frames"? I'm quite lost in all of this tbh.

Because there is signal stack involved: `sgx_ocall` switches to signal stack, saves the registers there, and only then exits enclave. If we want CFI to take the saved registers into account, we need a stack frame that is on the signal stack. Unfortunately that means we jump stacks not once, but twice, so we need two `__morestack` frames.

To be honest I have no idea why `sgx_ocall` switches to the signal stack. If we could get rid of that, it would simplify things. But your idea sounds even better.

>Also: not clearing callee-saved registers (ofc in debug builds only) seems to be enough - in LibOS we intentionally use r14, which is callee saved, to keep fake return address.

That's good news! And much simpler than trying to reach the saved registers.

I agree that callee-saved registers should be enough, we are being called like a normal function.

>Does it miss some edge case?

Looking at that code, it looks like we can account for all callee-saved registers except for RBX. It can be saved next to RBP, like so:

```diff
 sgx_ocall:
     pushq %rbp
+    pushq %rbx
     movq %rsp, %rbp
```

Does that sound good? Technically we don't need RBX for the stack trace, but it makes the CFI "correct", and I guess it could be useful when examining upper frames in GDB. But I'm not sure if we should bother.

---


<!-- Sent from Reviewable.io -->

2021-02-18 12:28 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTlob_t3_SWvlHuf2Rp:-MTp4sXO6-JeG580iJD2:bdhtorm) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>LibOS does not use r8, I do not understand the commit message...

My mistake. LibOS uses R14, and that's what we need to preserve.

>Why do we need two "fake frames"? I'm quite lost in all of this tbh.

Because there is signal stack involved: `sgx_ocall` switches to signal stack, saves the registers there, and only then exits enclave. If we want CFI to take the saved registers into account, we need a stack frame that is on the signal stack. Unfortunately that means we jump stacks not once, but twice, so we need two `__morestack` frames.

To be honest I have no idea why `sgx_ocall` switches to the signal stack. If we could get rid of that, it would simplify things. But your idea sounds even better.

>Also: not clearing callee-saved registers (ofc in debug builds only) seems to be enough - in LibOS we intentionally use r14, which is callee saved, to keep fake return address.

That's good news! And much simpler than trying to reach the saved registers.

I agree that callee-saved registers should be enough, we are being called like a normal function.

>Does it miss some edge case?

Looking at that code, it looks like we can account for all callee-saved registers except for RBX. It can be saved next to RBP, like so:

```diff
 sgx_ocall:
     pushq %rbp
+    pushq %rbx
     movq %rsp, %rbp
```

Does that sound good? Technically we don't need RBX for the stack trace, but it makes the CFI "correct", and I guess it could be useful when examining upper frames in GDB. But I'm not sure if we should bother.
</blockquote></details>

Updated. The new version is much simpler - apart from not clearing callee-saved registers, I mostly moved `__morestack` out of the way to make the code less confusing, and did my best to comment it. I also added RBX, as described above.

---
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 858 at r1](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTlh-IH8Ck6aOKUERaJ:-MTp5Fvy4KXTnw0cfuAp:b-3ex806) ([raw file](https://github.com/oscarlab/graphene/blob/4763cc3128cf202356848316486a3f04557c3230/Pal/src/host/Linux-SGX/enclave_entry.S#L858)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`an signal stack` -> `a signal stack`
</blockquote></details>

Fixed - the new version doesn't use or mention the signal stack at all.


<!-- Sent from Reviewable.io -->

2021-02-18 14:51 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTlob_t3_SWvlHuf2Rp:-MTpb8Pp4WRNM5YrldTB:b-agezz7) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Updated. The new version is much simpler - apart from not clearing callee-saved registers, I mostly moved `__morestack` out of the way to make the code less confusing, and did my best to comment it. I also added RBX, as described above.
</blockquote></details>

Thanks for this PR! I would like to keep `rbx` visible in the stack trace, so I am for pushing it to the stack as you implemented.

Thankfully I looked at this PR after the first version was thrown away :)

---
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 638 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTpbcXQ21OopX1X40Ap:-MTpbcXQ21OopX1X40Aq:b-g9henj) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L638)):*
> ```
> 
> #ifdef DEBUG
> 	# Keep callee-saved registers in order to recover stack later (see __morestack() below).
> ```

Do we want to add a warning somewhere in the documentation that `DEBUG=1` Graphene leaks registers on OCALLs? @mkow @boryspoplawski @yamahata . I can imagine people building Graphene in DEBUG mode and using this in production...


<!-- Sent from Reviewable.io -->

2021-02-18 14:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 638 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTpbcXQ21OopX1X40Ap:-MTpbv2J3Cc-UwfQtny2:b-q5rsqo) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L638)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we want to add a warning somewhere in the documentation that `DEBUG=1` Graphene leaks registers on OCALLs? @mkow @boryspoplawski @yamahata . I can imagine people building Graphene in DEBUG mode and using this in production...
</blockquote></details>

Not in the docs, but maybe a big fat warning when Graphene-SGX starts.


<!-- Sent from Reviewable.io -->

2021-02-18 15:08 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 638 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTpbcXQ21OopX1X40Ap:-MTpekuG6DYOy5G4npL3:b-dfylhq) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L638)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not in the docs, but maybe a big fat warning when Graphene-SGX starts.
</blockquote></details>

Actually, what do you think about saving R12, R13, R14, R15 on stack in the same way  as RBX, and clearing them here? This way, we would directly expose only RBP (same as before), and the other registers would be accessible only if it is a debug enclave and we can access enclave memory.

A warning under `#ifdef DEBUG` might still be a good idea.


<!-- Sent from Reviewable.io -->

2021-02-18 15:18 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @pwmarcz, and @yamahata)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 638 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTpbcXQ21OopX1X40Ap:-MTpgPuF5otPfExm6m7N:b-e3vge6) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L638)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Actually, what do you think about saving R12, R13, R14, R15 on stack in the same way  as RBX, and clearing them here? This way, we would directly expose only RBP (same as before), and the other registers would be accessible only if it is a debug enclave and we can access enclave memory.

A warning under `#ifdef DEBUG` might still be a good idea.
</blockquote></details>

1) I see no difference in exposing all of them vs just rbp, so imo this could can stay as it is
2) I remember talking about it with @mkow some time ago and afair we've reached the conclusion not to bother about it atm, but add such a warning after Graphene reaches ready-for-productio state.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 885 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTphh8kEjbZV8_1TmdH:-MTphh8kEjbZV8_1TmdI:bn4qcz1) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L885)):*
> ```
> 	.cfi_offset %rbx, -24
> 
> 	# RDI, RSI: not changed (function parameters to sgx_ocall)
> ```

These two are caller-saved and as such cannot be used meaningfully in cfi (we can drop this comment)


<!-- Sent from Reviewable.io -->

2021-02-18 15:46 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTlob_t3_SWvlHuf2Rp:-MTpnyyU7Rbj6mMf8lEX:b-mg7tlc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for this PR! I would like to keep `rbx` visible in the stack trace, so I am for pushing it to the stack as you implemented.

Thankfully I looked at this PR after the first version was thrown away :)
</blockquote></details>

Yeah, I'm happy about this too :) I learned more about CFI, though.

---
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 638 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTpbcXQ21OopX1X40Ap:-MTpnJMEBAQacrY4SMtz:b-g4zdah) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L638)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) I see no difference in exposing all of them vs just rbp, so imo this could can stay as it is
2) I remember talking about it with @mkow some time ago and afair we've reached the conclusion not to bother about it atm, but add such a warning after Graphene reaches ready-for-productio state.
</blockquote></details>

Okay, I'll keep the registers as they are right now.
___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 885 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTphh8kEjbZV8_1TmdH:-MTpnfQi3E5-7ed6_uKQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L885)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

These two are caller-saved and as such cannot be used meaningfully in cfi (we can drop this comment)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 15:48 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)



<!-- Sent from Reviewable.io -->

2021-02-19 08:09 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 638 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTpbcXQ21OopX1X40Ap:-MTtKThM0rOGHuq6eH7S:bm4tas5) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L638)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, I'll keep the registers as they are right now.
</blockquote></details>

OK, fair.


<!-- Sent from Reviewable.io -->

2021-02-19 18:01 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/enclave_entry.S, line 638 at r2](https://reviewable.io/reviews/oscarlab/graphene/2168#-MTpbcXQ21OopX1X40Ap:-MTvRWmn0T8FTDDh_HVa:b-c7sad6) ([raw file](https://github.com/oscarlab/graphene/blob/f451cf56ef99a8ae4cb2e5c74a1ce7dc252d6b8c/Pal/src/host/Linux-SGX/enclave_entry.S#L638)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, fair.
</blockquote></details>

Yup, I think a warning about debug builds is a good idea, now that we have a proper logging subsystem :)


<!-- Sent from Reviewable.io -->

2021-02-19 19:42 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-19 20:04 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-19 20:50 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-gsc (please jenkins disc full)

2021-02-19 20:50 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-gsc please (jenkins disc full)

2021-02-19 21:29 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2168)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-19 21:30 UTC, merged