[Pal/Linux-SGX] Add OCALL profiling modes
oscarlab/graphene pull request #2169
Opened 2021-02-18 16:45 UTC by pwmarcz

Based on #2168, I'll rebase once that is merged.

@dimakuv You might be interested in this :)

## Description of the changes 

This change extends the SGX profiler to handle OCALLs, not only
asynchronous enclave exit. Depending on settings, we either
record enclave state during OCALL, or the outer OCALL handler
being executed.

Example output (mode = "ocall_outer"):

```
# Overhead  Command  Shared Object  Symbol                        
# ........  .......  .............  ..............................
#
    28.91%  pal-sgx  pal-sgx        [.] sgx_ocall_open
    27.61%  pal-sgx  pal-sgx        [.] sgx_ocall_close
    22.41%  pal-sgx  pal-sgx        [.] sgx_ocall_fstat
    17.03%  pal-sgx  pal-sgx        [.] sgx_ocall_getdents
     1.13%  pal-sgx  pal-sgx        [.] sgx_ocall_mmap_untrusted
     0.90%  pal-sgx  pal-sgx        [.] sgx_ocall_cpuid
     0.70%  pal-sgx  pal-sgx        [.] sgx_ocall_munmap_untrusted
     0.53%  pal-sgx  pal-sgx        [.] sgx_ocall_write
     0.25%  pal-sgx  pal-sgx        [.] sgx_ocall_debug_map_add
     0.13%  pal-sgx  pal-sgx        [.] sgx_ocall_pread
     0.05%  pal-sgx  pal-sgx        [.] sgx_ocall_futex
     0.05%  pal-sgx  pal-sgx        [.] sgx_ocall_gettime
     0.05%  pal-sgx  pal-sgx        [.] sgx_ocall_poll
     0.05%  pal-sgx  pal-sgx        [.] sgx_ocall_sleep
     0.05%  pal-sgx  pal-sgx        [.] sgx_ocall_socketpair
     0.03%  pal-sgx  pal-sgx        [.] sgx_ocall_clone_thread
     0.03%  pal-sgx  pal-sgx        [.] sgx_ocall_exit
     0.03%  pal-sgx  pal-sgx        [.] sgx_ocall_listen
     0.03%  pal-sgx  pal-sgx        [.] sgx_ocall_read
     0.03%  pal-sgx  pal-sgx        [.] sgx_ocall_send
     0.03%  pal-sgx  pal-sgx        [.] sgx_ocall_shutdown
```

Example output (mode = "ocall_inner"):

```
#
    99.05%  pal-sgx  libpal.so      [.] sgx_exitless_ocall
            |
            ---sgx_exitless_ocall
               |          
               |--28.92%--ocall_open
               |          |          
               |          |--22.01%--file_attrquery
               |          |          
               |          |--5.40%--dir_open
               |          |          
               |           --1.48%--file_open
               |          
               |--27.61%--ocall_close
               |          |          
               |          |--20.93%--file_attrquery
               |          |          
               |          |--5.40%--dir_close
               |          |          
               |          |--0.73%--file_close
               |          |          
               |           --0.53%--file_open
               |          
               |--22.41%--ocall_fstat
               |          |          
               |          |--20.93%--file_attrquery
               |          |          
               |           --1.48%--file_open
               |          
               |--17.04%--ocall_getdents
               |          dir_read
               |          
               |--1.13%--ocall_mmap_untrusted
               |          |          
               |           --0.90%--load_trusted_file
               |          
               |--0.70%--ocall_munmap_untrusted
               |          file_close
               |          
                --0.53%--ocall_write
                          _DkDebugLog
```

Note that these percentages are all ocall counts, not time spent.

## How to test this PR? 

Follow the instructions in documentation.

2021-02-19 08:57 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 562 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtO7lvAbIDBRrDp-GM:-MTtO7lvAbIDBRrDp-GN:b-3lk497) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/manifest-syntax.rst#L562)):*
> ```reStructuredText
> ::
> 
>     sgx.profile.mode = ["aex"|"ocall_inner"|"ocall_outer"]
> ```

Please add that `aex` is the default.
___
*[Documentation/devel/performance.rst, line 555 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtPH0r760OxwdBFHML:-MTtPH0r760OxwdBFHMM:b-afh1sx) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/devel/performance.rst#L555)):*
> ```reStructuredText
> * Use ``sgx.profile.mode = "ocall_outer"``. This will give you a report on what
>   outer PAL code is handling the OCALLs (``sgx_ocall_open``, ``sgx_ocall_write``
>   etc.)
> ```

This mode looks a bit useless, since it's more or less the same info we can get via `strace` (outer OCALL implementations are very straight-forward and typically issue one host syscall). But still nice to have :)
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 288 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtUMrc7ng_N_VyXpBd:-MTtUMrd2m3sZ8worpka:buku4ei) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Pal/src/host/Linux-SGX/sgx_profile.c#L288)):*
> ```C
>     ret = debug_read_all(&gpr, enclave_gpr, sizeof(gpr));
>     if (IS_ERR(ret)) {
>         urts_log_error("sgx_profile_sample_eexit: error reading GPR: %d\n", ret);
> ```

Old function name?
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 303 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtVJB_3XXdHE6Sk9_Q:-MTtVJB_3XXdHE6Sk9_R:b-cvkk6o) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Pal/src/host/Linux-SGX/sgx_profile.c#L303)):*
> ```C
>         return;
> 
>     assert(!g_pal_enclave.profile_with_stack);
> ```

Maybe also assert that `ocall_func` is not NULL?
___
*[Pal/src/host/Linux-SGX/sgx_profile_glibc.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtSVF5C7ughd4r0yVD:-MTtSVF5C7ughd4r0yVE:b-x5sw9s) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Pal/src/host/Linux-SGX/sgx_profile_glibc.c#L37)):*
> ```C
> 
> void sgx_profile_report_urts_elfs(void) {
>     dl_iterate_phdr(&callback, NULL);
> ```

Was this feature needed for our untrusted PAL? I thought we only use Glibc and Protobuf libraries as dependencies. Did you want to collect the information on these outside-PAL libs? But you also disallow the stack with `ocall_outer`, so I'm confused what's the point of even looking at the outside libs.

Update: after reading the whole PR, it looks like you're mainly doing it to collect the ELF info on the untrusted PAL executable itself?


<!-- Sent from Reviewable.io -->

2021-02-19 10:34 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

___
*[Documentation/devel/performance.rst, line 555 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtPH0r760OxwdBFHML:-MTtlzcXCIWn8oSs19xA:bdp4p5) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/devel/performance.rst#L555)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This mode looks a bit useless, since it's more or less the same info we can get via `strace` (outer OCALL implementations are very straight-forward and typically issue one host syscall). But still nice to have :)
</blockquote></details>

Let's see:

Pros:
* It might not be exactly the same as `strace`, and differences could be helpful in hunting down problems (don't we have any non-trivial parts in the URTS except for ocalls?)
* Relatively cheap to implement
* Lower overhead than `ocall_inner` (we don't read enclave memory or record 8KB of stack sample every time), and possibly lower overhead than strace (since it happens in process, not though ptrace). I haven't experimented with it though.

Cons:
* Some added implementation complexity (adding `dl_iterate_phdr`)
* Added complexity for the user (you need to understand and decide between the two ocall modes)
* The same information, i.e. which ocall, is in `ocall_inner`. However, it's hidden at the 2nd level of stack, so you need to gather stack traces as well.

So, on balance, I'm slightly leaning towards keeping this mode. But if any of the above convinces you, I can remove it.

Also, maybe different names would help? `ocall` and `ocall_urts`?
___
*[Documentation/devel/performance.rst, line 557 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtojAG9qsTd-s4ItT2:-MTtojAG9qsTd-s4ItT3:b-1zsk4q) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/devel/performance.rst#L557)):*
> ```reStructuredText
>   etc.)
> 
> **Warning**: The report for OCALL modes should be interpreted in term of *number
> ```

One thing I'm worried about is lack of rate limiting, which means we will record every OCALL, increasing the overhead.

I don't want to do what the AEX code does (not take a sample if we took one recently). I'm afraid this will bias the results: for example, if two OCALLs are always performed one after another, we will never record the second one. For the same reason, I don't think it's a good idea to record every Nth sample. So far my only idea is something like `if rand() < threshold`. 

But then again, I'm not even sure if rate limiting is necessary, the overhead should be that high since we already execute some code (and a syscall) on every OCALL. So for now I'd rather keep it simple and see if it's useful without rate limiting.
___
*[Pal/src/host/Linux-SGX/sgx_profile_glibc.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtSVF5C7ughd4r0yVD:-MTtnQnkEnRa3MYSAg-H:b-8jqirf) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Pal/src/host/Linux-SGX/sgx_profile_glibc.c#L37)):*
>Update: after reading the whole PR, it looks like you're mainly doing it to collect the ELF info on the untrusted PAL executable itself?

Yes, that's what it's for. Information about glibc/protobuf/any other libraries is not necessary for now, although might be useful if we want to record something more.

If there is a simpler way to check the load address of main executable, I'll gladly change it. I figured out that since we're loaded by glibc (ld.so), it might be easiest to ask glibc itself. But as we can see, it's pretty inconvenient because of the header issue.


<!-- Sent from Reviewable.io -->

2021-02-19 14:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz)

___
*[Documentation/devel/performance.rst, line 555 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtPH0r760OxwdBFHML:-MTubq293K24qje2NzMJ:b6d0f72) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/devel/performance.rst#L555)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Let's see:

Pros:
* It might not be exactly the same as `strace`, and differences could be helpful in hunting down problems (don't we have any non-trivial parts in the URTS except for ocalls?)
* Relatively cheap to implement
* Lower overhead than `ocall_inner` (we don't read enclave memory or record 8KB of stack sample every time), and possibly lower overhead than strace (since it happens in process, not though ptrace). I haven't experimented with it though.

Cons:
* Some added implementation complexity (adding `dl_iterate_phdr`)
* Added complexity for the user (you need to understand and decide between the two ocall modes)
* The same information, i.e. which ocall, is in `ocall_inner`. However, it's hidden at the 2nd level of stack, so you need to gather stack traces as well.

So, on balance, I'm slightly leaning towards keeping this mode. But if any of the above convinces you, I can remove it.

Also, maybe different names would help? `ocall` and `ocall_urts`?
</blockquote></details>

I'm fine with current names and I am for keeping this mode.
___
*[Documentation/devel/performance.rst, line 557 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtojAG9qsTd-s4ItT2:-MTuc1QlDUwXi6k9Olsx:b8vkgkh) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/devel/performance.rst#L557)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

One thing I'm worried about is lack of rate limiting, which means we will record every OCALL, increasing the overhead.

I don't want to do what the AEX code does (not take a sample if we took one recently). I'm afraid this will bias the results: for example, if two OCALLs are always performed one after another, we will never record the second one. For the same reason, I don't think it's a good idea to record every Nth sample. So far my only idea is something like `if rand() < threshold`. 

But then again, I'm not even sure if rate limiting is necessary, the overhead should be that high since we already execute some code (and a syscall) on every OCALL. So for now I'd rather keep it simple and see if it's useful without rate limiting.
</blockquote></details>

+1 for not adding rate limiting. It's like `strace -c` right now, which is totally fine.
___
*[Pal/src/host/Linux-SGX/sgx_profile_glibc.c, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtSVF5C7ughd4r0yVD:-MTucMJb1o26turTgKuE:b-iwcxpc) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Pal/src/host/Linux-SGX/sgx_profile_glibc.c#L37)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Update: after reading the whole PR, it looks like you're mainly doing it to collect the ELF info on the untrusted PAL executable itself?

Yes, that's what it's for. Information about glibc/protobuf/any other libraries is not necessary for now, although might be useful if we want to record something more.

If there is a simpler way to check the load address of main executable, I'll gladly change it. I figured out that since we're loaded by glibc (ld.so), it might be easiest to ask glibc itself. But as we can see, it's pretty inconvenient because of the header issue.
</blockquote></details>

I'm fine with this solution. If anything, we can change this later.


<!-- Sent from Reviewable.io -->

2021-02-19 15:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: 7 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 562 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtO7lvAbIDBRrDp-GM:-MTuq0rqDOct7niHKdKv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/manifest-syntax.rst#L562)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add that `aex` is the default.
</blockquote></details>

Done.
___
*[Documentation/devel/performance.rst, line 555 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtPH0r760OxwdBFHML:-MTuq1yc7681yt-zBzQR:b5iwv2w) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Documentation/devel/performance.rst#L555)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with current names and I am for keeping this mode.
</blockquote></details>

Okay, then no changes here.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 288 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtUMrc7ng_N_VyXpBd:-MTur2mmBlkT3aKNgnWr:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Pal/src/host/Linux-SGX/sgx_profile.c#L288)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Old function name?
</blockquote></details>

Fixed.
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 303 at r1](https://reviewable.io/reviews/oscarlab/graphene/2169#-MTtVJB_3XXdHE6Sk9_Q:-MTuqLJD6wDg4TDS06QU:b-ijlim) ([raw file](https://github.com/oscarlab/graphene/blob/a57ba07ea0939114380eb15cb2edab5cf2e98871/Pal/src/host/Linux-SGX/sgx_profile.c#L303)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe also assert that `ocall_func` is not NULL?
</blockquote></details>

There's no harm here if it's NULL (we'll just log a 0 to the perf data file), but indeed that should never happen, as we're about to jump to `ocall_func`. I added an assertion.


<!-- Sent from Reviewable.io -->

2021-02-20 22:11 UTC, mkow requested changes
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU0Q0pP0LDZQ9h_eJb7:b-b9rwgl) (no related file):*
FYI: I played with this profiler briefly, and seems to be really useful for pinpointing reasons of high numbers of OCALLs. Example from Blender:
```
-   97.89%  pal-sgx  libpal.so      [.] sgx_exitless_ocall
   - sgx_exitless_ocall
      - 21.00% ocall_open
         + 14.25% file_attrquery
         + 5.02% file_open
         + 1.72% dir_open
```

This clearly shows an issue with our attrquery always requiring to open a file. It's already known to us (the reason is AFAIR PAL API design, which says it should be stateless), but I think it's a nice demo for this new feature :)
Also, this particular problem is probably something which would be good to fix when rewriting the FS subsystem.

---
___
*[Pal/src/host/Linux-SGX/sgx_profile_glibc.c, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0TmNt4GcjE8CWYA0W:-MU0TmNt4GcjE8CWYA0X:bfcgbjq) ([raw file](https://github.com/oscarlab/graphene/blob/7abefcb6dbc95ebb7b310aa9a19368ef5f93ca0b/Pal/src/host/Linux-SGX/sgx_profile_glibc.c#L19)):*
> ```C
> #include <stdlib.h>
> #include <string.h>
> #include <link.h>
> ```

nitpick: please sort :)
___
*[Pal/src/host/Linux-SGX/sgx_profile_glibc.c, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Tv7dEFPnjPRbA26Q:-MU0Tv7dEFPnjPRbA26R:b-wb2zo7) ([raw file](https://github.com/oscarlab/graphene/blob/7abefcb6dbc95ebb7b310aa9a19368ef5f93ca0b/Pal/src/host/Linux-SGX/sgx_profile_glibc.c#L30)):*
> ```C
> static int callback(struct dl_phdr_info *info,
>                     __attribute__((unused)) size_t size,
>                     __attribute__((unused)) void *data) {
> ```

please move asterisks to the left (x2)


<!-- Sent from Reviewable.io -->

2021-02-20 22:51 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU0cGAX1KcH9XsiSBra:b9n8dn6) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: I played with this profiler briefly, and seems to be really useful for pinpointing reasons of high numbers of OCALLs. Example from Blender:
```
-   97.89%  pal-sgx  libpal.so      [.] sgx_exitless_ocall
   - sgx_exitless_ocall
      - 21.00% ocall_open
         + 14.25% file_attrquery
         + 5.02% file_open
         + 1.72% dir_open
```

This clearly shows an issue with our attrquery always requiring to open a file. It's already known to us (the reason is AFAIR PAL API design, which says it should be stateless), but I think it's a nice demo for this new feature :)
Also, this particular problem is probably something which would be good to fix when rewriting the FS subsystem.
</blockquote></details>

Isn't it because we wanted PAL to support a minimal number of different syscalls, and so we don't do `stat` because we can do `open` + `fstat`? 

I don't necessarily agree, especially if it matters for performance, but that sounds like a reason.

---


<!-- Sent from Reviewable.io -->

2021-02-20 23:36 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU0mS6XCxZNZkWYWK3a:bsewkqx) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Isn't it because we wanted PAL to support a minimal number of different syscalls, and so we don't do `stat` because we can do `open` + `fstat`? 

I don't necessarily agree, especially if it matters for performance, but that sounds like a reason.
</blockquote></details>

Hmm, actually, I just checked and we have `file_attrquerybyhdl`, but AFAIR some PAL APIs still had to use the handle-less versions for some reason (and that was the known issue I mentioned, but I don't remember the details). And we already have `ocall_fstat` :)

---


<!-- Sent from Reviewable.io -->

2021-02-20 23:37 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU0nNfxDzVmXwPZQ6PM:bswv83c) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, actually, I just checked and we have `file_attrquerybyhdl`, but AFAIR some PAL APIs still had to use the handle-less versions for some reason (and that was the known issue I mentioned, but I don't remember the details). And we already have `ocall_fstat` :)
</blockquote></details>

Ah, sorry, misread your part about stat/fstat, yes, I think that was the reason to do open+fstat. I think we should just somehow get rid of the handle-less `attrquery`.

---


<!-- Sent from Reviewable.io -->

2021-02-22 05:28 UTC, yamahata approved these changes
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-02-22 08:49 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU7v7LdBzK0PwVj7Ew7:b-tmyxc0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, sorry, misread your part about stat/fstat, yes, I think that was the reason to do open+fstat. I think we should just somehow get rid of the handle-less `attrquery`.
</blockquote></details>

https://github.com/oscarlab/graphene/issues/570 -- Indeed, `ocall_stat` was never implemented because we can emulate the same via `ocall_open + ocall_fstat`. The reason is to minimize the number of OCALLs (to decrease attack surface).

---


<!-- Sent from Reviewable.io -->

2021-02-22 09:56 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: 8 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU878fcE-wdfnG4r3DI:b-nqlpyb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

https://github.com/oscarlab/graphene/issues/570 -- Indeed, `ocall_stat` was never implemented because we can emulate the same via `ocall_open + ocall_fstat`. The reason is to minimize the number of OCALLs (to decrease attack surface).
</blockquote></details>

There's still room for improvement here. For example our `shim_do_getdents` ends up calling `DkStreamAttributesQuery` for every file. There is an OCALL for `getdents`, which PAL uses for listing the directory, but it uses only file names.

---
___
*[Pal/src/host/Linux-SGX/sgx_profile_glibc.c, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0TmNt4GcjE8CWYA0W:-MU88yhk4W1I3QQSxWSM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7abefcb6dbc95ebb7b310aa9a19368ef5f93ca0b/Pal/src/host/Linux-SGX/sgx_profile_glibc.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: please sort :)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_profile_glibc.c, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Tv7dEFPnjPRbA26Q:-MU890TZ2WiiuC8a3lid:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7abefcb6dbc95ebb7b310aa9a19368ef5f93ca0b/Pal/src/host/Linux-SGX/sgx_profile_glibc.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please move asterisks to the left (x2)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-22 10:09 UTC, dimakuv approved these changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU8C20F-Y9sb7LRSnQW:b-jxcynd) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

There's still room for improvement here. For example our `shim_do_getdents` ends up calling `DkStreamAttributesQuery` for every file. There is an OCALL for `getdents`, which PAL uses for listing the directory, but it uses only file names.
</blockquote></details>

Yes, in terms of performance there is a lot of room for improvement... I'm not against adding `ocall_stat` if this lies on a critical path for FS-intensive workloads, but I think we currently just need to remove `DkStreamAttributesQuery()` from the critical paths (which should be possible).

---


<!-- Sent from Reviewable.io -->

2021-02-22 10:15 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2169#-MU0Q0pP0LDZQ9h_eJb6:-MU8D_aQB34_meoNDFU2:b-r7dggi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, in terms of performance there is a lot of room for improvement... I'm not against adding `ocall_stat` if this lies on a critical path for FS-intensive workloads, but I think we currently just need to remove `DkStreamAttributesQuery()` from the critical paths (which should be possible).
</blockquote></details>

That's what I meant - we already use `getdents`, so if we just stop throwing away the results, a lot of this `open + fstat` can go away.

---


<!-- Sent from Reviewable.io -->

2021-02-22 12:27 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-22 12:47 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-22 14:47 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-02-22 14:49 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-02-22 17:20 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2169)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-22 17:24 UTC, merged