[LibOS] Migrate logging to the new API
oscarlab/graphene pull request #2177
Opened 2021-02-20 00:32 UTC by mkow

## Description of the changes 

PAL was already converted, only LibOS was left, so that's it.

After this PR the only thing left is code in Pal/lib, but this one is tricky - the code there is also used without the rest of Graphene, and also shared between PAL and LibOS. So, that's left for another PR.

Also, fixed a bug in the `_log` macro which got triggered after converting some of the callsites.

## How to test this PR? 

Try different log_levels.

2021-02-20 22:47 UTC, pwmarcz reviewed
> Reviewed 62 of 62 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0_vpq7Ux40brfFDuD:-MU0_vpr7LcrWEH7jA87:bhw3q0j) (no related file):*
I haven't tried to run it, but is the `debug` output acceptable now, or should we demote some more noisy messages to `trace`? For instance IPC?

---
___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU0TxGh5e-7V0cBfehU:bcdda3p) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
> ```objc
> void debug_vprintf(const char* fmt, va_list ap) __attribute__((format(printf, 1, 0)));
> 
> void _log(int level, const char* fmt, ...) __attribute__((format(printf, 2, 3)));
> ```

Why not inline? An inline function will preserve the side effects, but still might be optimized if we end up not needing to log something: for instance, `log_debug("%p", foo->bar)` can potentially omit dereferencing `foo` if the function is inline.
___
*[LibOS/shim/src/shim_malloc.c, line 97 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0ZsWd47XSBFlrf1-W:-MU0ZsWd47XSBFlrf1-X:bh34ixm) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/src/shim_malloc.c#L97)):*
> ```C
>          * condition and must terminate the current process.
>          */
>         log_error("******** Out-of-memory in library OS ********\n");
> ```

Do we still want the `******`?


<!-- Sent from Reviewable.io -->

2021-02-20 23:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 61 of 62 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0_vpq7Ux40brfFDuD:-MU0nwRMB86rUoSbo0ng:b-6hpuii) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I haven't tried to run it, but is the `debug` output acceptable now, or should we demote some more noisy messages to `trace`? For instance IPC?
</blockquote></details>

Hard to say, it was still a bit noisy (not terribly), but that's mostly because it's totally random which events are logged and which aren't. Each subsystem is different in this terms. I think the log consisted mostly of thread creation/exit events and "async event installed [...]" entries.

What we should do is probably look at the whole codebase and remove all low-quality/noise/debugging-leftovers messages and add some important ones.

---
___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU0om4OCcDyqhCPK4e7:b-an8zt0) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Why not inline? An inline function will preserve the side effects, but still might be optimized if we end up not needing to log something: for instance, `log_debug("%p", foo->bar)` can potentially omit dereferencing `foo` if the function is inline.
</blockquote></details>

Normal functions can also be optimized, `inline` is just a hint to compiler's heuristic. I'm not convinced it should ever be used - in the end, the compiler should know better where and what to inline.
___
*[LibOS/shim/src/shim_malloc.c, line 97 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0ZsWd47XSBFlrf1-W:-MU0pCRU8mywokDCLcps:b3unloe) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/src/shim_malloc.c#L97)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Do we still want the `******`?
</blockquote></details>

Nah, fixed.


<!-- Sent from Reviewable.io -->

2021-02-21 08:22 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 61 of 62 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU2clCG3CqwwE8N32V9:bw3z1dr) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Normal functions can also be optimized, `inline` is just a hint to compiler's heuristic. I'm not convinced it should ever be used - in the end, the compiler should know better where and what to inline.
</blockquote></details>

Functions in the same object file yes, but I think GCC will not optimize functions across compilation units unless enable link-time optimization (`-flto`). Should we enable it for Graphene?

(Or maybe what I know is outdated, and LTO is on by default, but I didn't find anything to confirm that).


<!-- Sent from Reviewable.io -->

2021-02-21 17:09 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 61 of 62 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU4Y96XEGUDUqxgyckJ:b-wu73ad) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Functions in the same object file yes, but I think GCC will not optimize functions across compilation units unless enable link-time optimization (`-flto`). Should we enable it for Graphene?

(Or maybe what I know is outdated, and LTO is on by default, but I didn't find anything to confirm that).
</blockquote></details>

Yup, but this has (AFAIK) nothing to do with `inline` specifier.

And yes, we should enable LTO, but I think it may be non-trivial, considering our custom linking scripts. I'm not sure if anyone has tried it already with Graphene.


<!-- Sent from Reviewable.io -->

2021-02-21 17:27 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 61 of 62 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU4Zeuw1PzVLDv2TZKc:b-sfbsn1) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
> Yup, but this has (AFAIK) nothing to do with inline specifier.

Not directly, but: if we don't have LTO, and if we want this function to be inlined, it needs to be defined here in the header file. And `inline` is the only way to do that, because otherwise the linker will complain about multiple definitions across `.o` files. (`inline` is used not to ensure the function is inlined, but to ensure we're generating a weak symbol).

So, since we don't compile with LTO right now, I understand the choice is:
* define `_log` as inline in the header file, and it will get inlined by compiler when appropriate,
* define `_log` in a separate `.c` file, and it will never get inlined (except possibly in other functions in that file).

Do I have it right?

(Now that I think of it, we also tend to abuse `static inline`, which causes compiler to emit separate copies if the functions are not inlined...)


<!-- Sent from Reviewable.io -->

2021-02-21 17:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 61 of 62 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU4dPi7CaeFo1SUjaOm:bjk39t1) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
>(Now that I think of it, we also tend to abuse static inline, which causes compiler to emit separate copies if the functions are not inlined...)

That's unrelated, but... ouch:

```
$ nm Runtime/libsysdb.so | grep ref_inc
000000000001723f t __ref_inc
000000000002023c t __ref_inc
000000000002df2e t __ref_inc
00000000000418fb t __ref_inc
0000000000043533 t __ref_inc
000000000004716f t __ref_inc
000000000005dea1 t __ref_inc
```

`__ref_inc` is `static inline`. And changing it to `inline` causes linker errors about undefined symbols. Either I don't understand something or our build script is broken and `static inline` was a workaround for that :)


<!-- Sent from Reviewable.io -->

2021-02-21 18:04 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 61 of 62 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU4h6g20FXSNWdNgukG:bqyv6wo) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>(Now that I think of it, we also tend to abuse static inline, which causes compiler to emit separate copies if the functions are not inlined...)

That's unrelated, but... ouch:

```
$ nm Runtime/libsysdb.so | grep ref_inc
000000000001723f t __ref_inc
000000000002023c t __ref_inc
000000000002df2e t __ref_inc
00000000000418fb t __ref_inc
0000000000043533 t __ref_inc
000000000004716f t __ref_inc
000000000005dea1 t __ref_inc
```

`__ref_inc` is `static inline`. And changing it to `inline` causes linker errors about undefined symbols. Either I don't understand something or our build script is broken and `static inline` was a workaround for that :)
</blockquote></details>

Okay, my conclusion is: I think `_log` should be possible to be inlined by compiler, and I would recommend it to be defined `inline` in the header... once our linking is fixed. If you agree, maybe add a TODO comment? I'm resolving the discussion anyway.

(Usiing `static inline` right now would work pretty badly since we would generate separate `_log` function for each file). 

I ticketed the linking issue as https://github.com/oscarlab/graphene/issues/2179.


<!-- Sent from Reviewable.io -->

2021-02-21 18:12 UTC, pwmarcz reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-22 01:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 59 of 62 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU0TxGh5e-7V0cBfehT:-MU6HdF45gXAQRSiA2f6:bh715yw) ([raw file](https://github.com/oscarlab/graphene/blob/2d4725908203b675507f041855927e9936ff1dbd/LibOS/shim/include/shim_internal.h#L49)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, my conclusion is: I think `_log` should be possible to be inlined by compiler, and I would recommend it to be defined `inline` in the header... once our linking is fixed. If you agree, maybe add a TODO comment? I'm resolving the discussion anyway.

(Usiing `static inline` right now would work pretty badly since we would generate separate `_log` function for each file). 

I ticketed the linking issue as https://github.com/oscarlab/graphene/issues/2179.
</blockquote></details>

(for others: at this point we had some discussions on priv, so I'll skip replying to older points)

Hmm, I'd rather say that the ideal way of resolving this would be to leave this code as-is and enable LTO, as it doesn't require us to manually mark all cross-object-inlinable functions. The question here is how hard would it be to enable LTO and whether it will be possible in near future.

Anyways, a TODO added.


<!-- Sent from Reviewable.io -->

2021-02-22 05:24 UTC, yamahata submitted a review, later dismissed
> Reviewed 58 of 62 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-02-22 08:44 UTC, dimakuv requested changes
> Reviewed 58 of 62 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/sys/cache_info.c, line 47 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7qwZ34F1yQ-WeybLs:-MU7qwZ34F1yQ-WeybLt:bnk71o7) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/fs/sys/cache_info.c#L47)):*
> ```C
>         cache_filebuf = pal_control.topo_info.core_topology[cpunum].cache[idx].physical_line_partition;
>     } else {
>         log_debug("Unrecognized file %s\n", name);
> ```

For all these sysfs files, I'd prefer `log_warning` (I can imagine a situation when some app goes bonkers because a sysfs file is not found, and the end user shouldn't scroll through MBs of `debug` logs to find this). But no hard preference.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 602 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7qlo6C72ZHTUHjC-s:-MU7qlo6C72ZHTUHjC-t:b-okhvmt) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/ipc/shim_ipc_helper.c#L602)):*
> ```C
>                     ret = send_response_ipc_message(port, msg->src, ret, msg->seq);
>                     if (ret < 0) {
>                         log_debug("Sending IPC_MSG_RESP msg on port %p (handle %p) to %u failed\n",
> ```

I'd prefer `log_error`. This is a Graphene-internal error which should never happen in normal circumstances.
___
*[LibOS/shim/src/sys/shim_clone.c, line 253 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7rv_KApaXFmTfHEpk:-MU7rv_KApaXFmTfHEpl:b-p90i5x) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_clone.c#L253)):*
> ```C
> 
>     if (flags & ~supported_flags) {
>         log_warning("clone called with unsupported flags argument.\n");
> ```

Shouldn't it be `log_error`?

Here and below, my assumption is:
- `warning` is used for situations "weird syscall arguments are given, it is application's fault OR Graphene will continue but with caveats"
- `error` is used for situations "unsupported arguments are given, Graphene will fail unexpectedly for application"
___
*[LibOS/shim/src/sys/shim_clone.c, line 273 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7rxgzDQrJC-8jNVK6:-MU7rxgzDQrJC-8jNVK7:b-ea14kv) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_clone.c#L273)):*
> ```C
>     if (flags & CLONE_VM) {
>         if (!((flags & CLONE_THREAD) || (flags & CLONE_VFORK))) {
>             log_warning("CLONE_VM without either CLONE_THREAD or CLONE_VFORK is unsupported\n");
> ```

Shouldn't it be `log_error`?
___
*[LibOS/shim/src/sys/shim_futex.c, line 799 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7sDBu-ZEFA6n34swO:-MU7sDBu-ZEFA6n34swP:b-81wohb) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_futex.c#L799)):*
> ```C
>         case FUTEX_CMP_REQUEUE_PI:
>         case FUTEX_WAIT_REQUEUE_PI:
>             log_warning("PI futexes are not yet supported!\n");
> ```

`log_error`?
___
*[LibOS/shim/src/sys/shim_mmap.c, line 255 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7sNoEC79BVGNOs94x:-MU7sNoEC79BVGNOs94y:bw9gsbk) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_mmap.c#L255)):*
> ```C
>             }
>         } else {
>             log_warning("Memory that was about to be mprotected was unmapped, your program is "
> ```

`log_error`? Even though it is application's fault, sounds like something to complain about very loudly.
___
*[LibOS/shim/src/sys/shim_sleep.c, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7sbjl6kuY_YiCc3zo:-MU7sbjl6kuY_YiCc3zp:b-81wohb) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_sleep.c#L54)):*
> ```C
> 
>     if (flags) {
>         log_warning("Graphene's clock_nanosleep does not support non-zero flags (0x%x)\n", flags);
> ```

`log_error`?
___
*[LibOS/shim/src/sys/shim_socket.c, line 484 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7slsj9hZRBwo05khZ:-MU7slsj9hZRBwo05kh_:b-81wohb) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_socket.c#L484)):*
> ```C
>     if (!pal_hdl) {
>         ret = (PAL_NATIVE_ERRNO() == PAL_ERROR_STREAMEXIST) ? -EADDRINUSE : -PAL_ERRNO();
>         log_warning("bind: invalid handle returned\n");
> ```

`log_error`?
___
*[LibOS/shim/src/sys/shim_socket.c, line 1509 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7sykF9hdQHn5TuOyF:-MU7sykF9hdQHn5TuOyG:b-81wohb) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_socket.c#L1509)):*
> ```C
>     /* TODO(donporter): timeout properly. For now, explicitly return an error. */
>     if (timeout) {
>         log_warning("recvmmsg(): timeout parameter unsupported.\n");
> ```

`log_error`?


<!-- Sent from Reviewable.io -->

2021-02-22 09:44 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/sys/shim_clone.c, line 253 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7rv_KApaXFmTfHEpk:-MU84v2B2sf9Nghx-cFH:b-rwebsa) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_clone.c#L253)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't it be `log_error`?

Here and below, my assumption is:
- `warning` is used for situations "weird syscall arguments are given, it is application's fault OR Graphene will continue but with caveats"
- `error` is used for situations "unsupported arguments are given, Graphene will fail unexpectedly for application"
</blockquote></details>

In the [documentation about log levels](https://graphene.readthedocs.io/en/latest/manifest-syntax.html#log-level), I think both of these situations fall into `warning`, and `error` is reserved for fatal errors / problems with Graphene itself.

My thinking behind that was that an application could (possibly frequently) request something unsupported, but continue anyway (for instance, fall back to an older mechanism). Because `error` is on by default, so the user will get a lot of noise on stderr.

(As an example, we don't produce `error` on unsupported syscalls, and probably shouldn't?)

So if you want to treat some of these as `error`, I would advise to at least test them on our examples. And it might be good to update the documentation.


<!-- Sent from Reviewable.io -->

2021-02-22 09:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/sys/shim_clone.c, line 253 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7rv_KApaXFmTfHEpk:-MU887W84-8fG8pkQL2I:b2nwzrj) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_clone.c#L253)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

In the [documentation about log levels](https://graphene.readthedocs.io/en/latest/manifest-syntax.html#log-level), I think both of these situations fall into `warning`, and `error` is reserved for fatal errors / problems with Graphene itself.

My thinking behind that was that an application could (possibly frequently) request something unsupported, but continue anyway (for instance, fall back to an older mechanism). Because `error` is on by default, so the user will get a lot of noise on stderr.

(As an example, we don't produce `error` on unsupported syscalls, and probably shouldn't?)

So if you want to treat some of these as `error`, I would advise to at least test them on our examples. And it might be good to update the documentation.
</blockquote></details>

Thanks, Pawel, that's true. I'll resolve my comments on this.


<!-- Sent from Reviewable.io -->

2021-02-22 12:24 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: 60 of 62 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/fs/sys/cache_info.c, line 47 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7qwZ34F1yQ-WeybLs:-MU8crCK9R_M96qGPqF4:bv12iub) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/fs/sys/cache_info.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For all these sysfs files, I'd prefer `log_warning` (I can imagine a situation when some app goes bonkers because a sysfs file is not found, and the end user shouldn't scroll through MBs of `debug` logs to find this). But no hard preference.
</blockquote></details>

I thought about it, but it's actually a completely valid case which just returns `ENOENT`. And some apps do try to open such files, e.g. `lscpu` - for indexed entries (like `cache/index<number>`) it just loops until ENOENT. So, it'd rather keep it at debug level.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 602 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7qlo6C72ZHTUHjC-s:-MU8dosS5iGiB96_iI77:bwlwmf2) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/ipc/shim_ipc_helper.c#L602)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd prefer `log_error`. This is a Graphene-internal error which should never happen in normal circumstances.
</blockquote></details>

Right, I overlooked this one.
___
*[LibOS/shim/src/sys/shim_mmap.c, line 255 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7sNoEC79BVGNOs94x:-MU8f-Pf7RLurhTNcWUk:b18ho2g) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_mmap.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`log_error`? Even though it is application's fault, sounds like something to complain about very loudly.
</blockquote></details>

I thought about this one, but it's not really a fatal error, the application can continue afterwards (with its buggy behavior). OTOH, it's rare and definitely something which the user should see.
@pwmarcz What do you think?
___
*[LibOS/shim/src/sys/shim_socket.c, line 484 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7slsj9hZRBwo05khZ:-MU8g5T_22-3bbAtxCjG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_socket.c#L484)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`log_error`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-22 12:44 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/sys/cache_info.c, line 47 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7qwZ34F1yQ-WeybLs:-MU8lBNz1o8TnIZYUjIK:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/fs/sys/cache_info.c#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I thought about it, but it's actually a completely valid case which just returns `ENOENT`. And some apps do try to open such files, e.g. `lscpu` - for indexed entries (like `cache/index<number>`) it just loops until ENOENT. So, it'd rather keep it at debug level.
</blockquote></details>

OK.
___
*[LibOS/shim/src/sys/shim_mmap.c, line 255 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7sNoEC79BVGNOs94x:-MU8lKdwDEZ7WMLnK8sr:blz3wp9) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_mmap.c#L255)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I thought about this one, but it's not really a fatal error, the application can continue afterwards (with its buggy behavior). OTOH, it's rare and definitely something which the user should see.
@pwmarcz What do you think?
</blockquote></details>

OK, resolving from my side.


<!-- Sent from Reviewable.io -->

2021-02-22 19:54 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-02-22 19:54 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-22 20:03 UTC, pwmarcz reviewed
> Reviewed 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2177)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/sys/shim_mmap.c, line 255 at r3](https://reviewable.io/reviews/oscarlab/graphene/2177#-MU7sNoEC79BVGNOs94x:-MUAIV0SEasuN-GnbkLF:bap5hn) ([raw file](https://github.com/oscarlab/graphene/blob/9f98e7300343b817ca94c738539a304fe9f74d94/LibOS/shim/src/sys/shim_mmap.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, resolving from my side.
</blockquote></details>

I think that by our definition it's `warning` - as I understand, it's recoverable, it doesn't indicate a problem in Graphene, and it's not a security issue.


<!-- Sent from Reviewable.io -->

2021-02-22 20:17 UTC, merged