[PAL] Rework PAL API value and error returning interface
oscarlab/graphene pull request #2182
Opened 2021-02-23 01:04 UTC by boryspoplawski

## Description of the changes 
The old version used special function `DkRaiseFailure` (which in turn
calledLibOS callback, which saved the error code) to return errors,
values were returned directly from functions. This was annoying to deal
with, as some functions did not return any value, yet they still used
`DkRaiseFailure` to indicate errors. Moreover it abused exception
handling interface, to callback into LibOS.
The new version uniformly returns values via out-arguments (pointer
passed by the caller, where the return value is stored). Errors are
returned from functions directly, with `0` indicating successful call.

This commit additionally fixes multiple bugs around error code checking.

2021-02-23 05:57 UTC, yamahata requested changes
> Reviewed 68 of 101 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: 68 of 101 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/shim_checkpoint.c, line 359 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUCPFab2UBNgNqu3XVS:-MUCPFacC80qDBF9xM9i:bc2iggs) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_checkpoint.c#L359)):*
> ```C
>             if (ret < 0) {
>                 log_error("failed allocating %p-%p\n", addr, addr + size);
>                 return -pal_to_unix_errno(-ret);
> ```

nitpick: pal_to_unix_errno(ret)
___
*[LibOS/shim/src/shim_init.c, line 87 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUCPYkL4KnA6t2y8JDp:-MUCPYkL4KnA6t2y8JDq:bwockjt) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L87)):*
> ```C
> 
> long pal_to_unix_errno(long err) {
>     if (err >= 0) {
> ```

clever convention.


<!-- Sent from Reviewable.io -->

2021-02-23 10:39 UTC, dimakuv requested changes
> Reviewed 101 of 101 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDCrTFEvr6xJpDhQiC:-MUDCrTFEvr6xJpDhQiD:b-c167ht) (no related file):*
Typo in commit message: `calledLibOS callback`

---
___
*[LibOS/shim/include/shim_internal.h, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDDk6B31dSVBHKryf0:-MUDDk6B31dSVBHKryf1:b-ig34l7) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/include/shim_internal.h#L217)):*
> ```objc
>     memset(bytes, '\0', n);
>     while (n > 0) {
>         size_t this_read = n;
> ```

Why such a strange name? Why not `this_write`? Or just `size`.
___
*[LibOS/shim/include/shim_internal.h, line 220 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDEKgh-UFzTWojA4yr:-MUDEKgh-UFzTWojA4ys:b3jg9l3) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/include/shim_internal.h#L220)):*
> ```objc
>         int ret = DkStreamWrite(e->event, 0, &this_read, bytes, NULL);
>         if (ret < 0) {
>             if (ret == -PAL_ERROR_INVAL || ret == -PAL_ERROR_TRYAGAIN) {
> ```

`PAL_ERROR_INVAL`? You probably meant `PAL_ERROR_INTERRUPTED`.
___
*[LibOS/shim/include/shim_internal.h, line 277 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDF4rS7A6T0l4_K7lX:-MUDF4rT218Ww7QO26dQ:b-9gvwim) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/include/shim_internal.h#L277)):*
> ```objc
>             if (ret == -EINTR) {
>                 continue;
>             } else if (ret == -EAGAIN || ret == -EWOULDBLOCK) {
> ```

Here and above you're using UNIX error codes, but in all other places you're using PAL error codes. Let's change here to PAL codes.
___
*[LibOS/shim/src/shim_async.c, line 289 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDFoQw7h6-7JoXO2-W:-MUDFoQw7h6-7JoXO2-X:b-r7zra6) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_async.c#L289)):*
> ```C
>         /* wait on async IO events + install_new_event + next expiring alarm/timer */
>         ret = DkStreamsWaitEvents(pals_cnt + 1, pals, pal_events, ret_events, sleep_time);
>         if (ret && ret != -PAL_ERROR_INTERRUPTED && ret != -PAL_ERROR_TRYAGAIN) {
> ```

Can we replace `ret` with `ret < 0`, for uniformity with other checks?
___
*[LibOS/shim/src/shim_checkpoint.c, line 359 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUCPFab2UBNgNqu3XVS:-MUDGZgb8-CmlPXHCq9u:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_checkpoint.c#L359)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nitpick: pal_to_unix_errno(ret)
</blockquote></details>

+1
___
*[LibOS/shim/src/shim_checkpoint.c, line 684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDGs8u2RyHely-QXVA:-MUDGs8u2RyHely-QXVB:bmybqwq) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_checkpoint.c#L684)):*
> ```C
>             BUG();
>         bkeep_remove_tmp_vma(tmp_vma);
>         return -pal_to_unix_errno(-ret);
> ```

No negations.
___
*[LibOS/shim/src/shim_checkpoint.c, line 720 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDIPid0JwCnEqWavrl:-MUDIPid0JwCnEqWavrm:b-aoafrw) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_checkpoint.c#L720)):*
> ```C
>     return 0;
> 
> out:;
> ```

Can we rename this label to `out_fail`, to make it explicit?
___
*[LibOS/shim/src/shim_init.c, line 87 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUCPYkL4KnA6t2y8JDp:-MUDHSqc0yqptv12YX4J:bxjftrr) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L87)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

clever convention.
</blockquote></details>

Clever, but why you do want to allow two ways of using this (both-positives and both-negatives)?
___
*[LibOS/shim/src/shim_init.c, line 150 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDHuzv4qYMj1mzKNSM:-MUDHuzw4QMEgMoyLV5G:bqvmsfa) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L150)):*
> ```C
>     }
> 
>     log_debug("Allocated stack at %p (size = %ld)\n", stack, size);
> ```

Now this log message is not shown on `user == false`. Could you maybe move it before both allocations and change `Allocated`- > `Allocating`?
___
*[LibOS/shim/src/shim_init.c, line 427 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDIcpFA2Afqm_FReIS:-MUDIcpFA2Afqm_FReIT:b-iw7ly9) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L427)):*
> ```C
>         int ret = DkStreamRead(PAL_CB(parent_process), 0, &hdr_size, &hdr, NULL, 0);
>         if (ret < 0) {
>             DkProcessExit(pal_to_unix_errno(-ret));
> ```

Now you have single-negation :) I'm afraid the trick with `pal_to_unix_errno()` makes the code less readable.
___
*[LibOS/shim/src/shim_init.c, line 460 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDItQO4mH15N5_dcKF:-MUDItQO4mH15N5_dcKG:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L460)):*
> ```C
>         int ret = DkStreamWrite(PAL_CB(parent_process), 0, &child_vmid_size, &child_vmid, NULL);
>         if (ret < 0) {
>             DkProcessExit(pal_to_unix_errno(-ret));
> ```

ditto
___
*[LibOS/shim/src/shim_malloc.c, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJ9kc8pd4fRU9bf9g:-MUDJ9kc8pd4fRU9bf9h:b1vobcf) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/shim_malloc.c#L52)):*
> ```C
>         if (!ret_addr) {
>             if (PAL_NATIVE_ERRNO() == PAL_ERROR_INTERRUPTED) {
>                 continue;
> ```

We're assuming this is not possible?
___
*[LibOS/shim/src/shim_object.c, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJMKZ-6bWPZ9aBfhj:-MUDJMKZ-6bWPZ9aBfhk:bhrowix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_object.c#L11)):*
> ```C
> 
>     if (ret < 0) {
>         log_error("waiting on %p resulted in error %s", handle, pal_strerror(-ret));
> ```

By the way, I think that your clever trick should be used in `pal_strerror()`
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1030 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDK8297g0AijYa7CIt:-MUDK8297g0AijYa7CIu:b-u0igk3) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/elf/shim_rtld.c#L1030)):*
> ```C
>     ret = DkRandomBitsRead((PAL_PTR)random, 16);
>     if (ret < 0) {
>         ret = pal_to_unix_errno(ret);
> ```

I would remove this conversion. It is confusing to have in the log a UNIX error code for a Dk PAL function.
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1032 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDKIuC6Y1vTp4OKd2_:-MUDKIuC6Y1vTp4OKd2a:b-t12cv0) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/elf/shim_rtld.c#L1032)):*
> ```C
>         ret = pal_to_unix_errno(ret);
>         log_error("execute_elf_object: DkRandomBitsRead fa [...]

2021-02-23 16:44 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 30 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDCrTFEvr6xJpDhQiC:-MUEXDCw3-4gLedL8zzM:be6mdj4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo in commit message: `calledLibOS callback`
</blockquote></details>

TODO: at rebase

---
___
*[LibOS/shim/include/shim_internal.h, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDDk6B31dSVBHKryf0:-MUEXGR60zX6NYHn2pY6:b-l50yvh) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/include/shim_internal.h#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why such a strange name? Why not `this_write`? Or just `size`.
</blockquote></details>

Uh, copy-pasteed probably...
Done.
___
*[LibOS/shim/include/shim_internal.h, line 220 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDEKgh-UFzTWojA4yr:-MUEXdJ2E6mSi8TuTzP4:b-t69qs3) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/include/shim_internal.h#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`PAL_ERROR_INVAL`? You probably meant `PAL_ERROR_INTERRUPTED`.
</blockquote></details>

Ooooops
___
*[LibOS/shim/include/shim_internal.h, line 277 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDF4rS7A6T0l4_K7lX:-MUEXrki1N4It22ZY0rf:bqfl8ce) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/include/shim_internal.h#L277)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here and above you're using UNIX error codes, but in all other places you're using PAL error codes. Let's change here to PAL codes.
</blockquote></details>

I've just left what was here already.
Changed.
___
*[LibOS/shim/src/shim_async.c, line 289 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDFoQw7h6-7JoXO2-W:-MUEYeiu846nyUcV0C3x:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_async.c#L289)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we replace `ret` with `ret < 0`, for uniformity with other checks?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 359 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUCPFab2UBNgNqu3XVS:-MUEYo1nB5qQtrMw4RE9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_checkpoint.c#L359)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDGs8u2RyHely-QXVA:-MUEYoenC-WQ1jTQX2b1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_checkpoint.c#L684)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No negations.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 720 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDIPid0JwCnEqWavrl:-MUEYyuy2aUHWYksLOgk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_checkpoint.c#L720)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename this label to `out_fail`, to make it explicit?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 87 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUCPYkL4KnA6t2y8JDp:-MUEZ-ItEoEOG0ttO45h:bq93ken) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Clever, but why you do want to allow two ways of using this (both-positives and both-negatives)?
</blockquote></details>

Because I've changed this function first and then rewrote all of this incrementally (there might also have been some bugs around negations in the old code).
Now I'm done, I could restore this to just use negative values, but this sounds useful and I think I used it in some places (`pal_to_unix_errno(-ret)` to get the positive value).
I can remove it and stick to negative input + negative output convention only, if you want.
___
*[LibOS/shim/src/shim_init.c, line 150 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDHuzv4qYMj1mzKNSM:-MUE_ZqbBt5Wr1HpjFKU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L150)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now this log message is not shown on `user == false`. Could you maybe move it before both allocations and change `Allocated`- > `Allocating`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 427 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDIcpFA2Afqm_FReIS:-MUE_bK5Dso41-lA6pJe:bnjn2dt) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L427)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have single-negation :) I'm afraid the trick with `pal_to_unix_errno()` makes the code less readable.
</blockquote></details>

This is intended. We want to return the positive value. TBH after reading `-pal_to_unix_errno(-ret)` I would have no idea if this is positive or negative. Probably just like in the current version :)
___
*[LibOS/shim/src/shim_init.c, line 460 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDItQO4mH15N5_dcKF:-MUEa4bp7MvwOV6jYESk:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L460)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[LibOS/shim/src/shim_malloc.c, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJ9kc8pd4fRU9bf9g:-MUEaFMY1TuHwPZaHyWB:bsa8r9t) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/shim_malloc.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We're assuming this is not possible?
</blockquote></details>

No, why?
___
*[LibOS/shim/src/shim_object.c, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJMKZ-6bWPZ9aBfhj:-MUEahN5EMKvI1njYZ1g:b-hjc5gx) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_object.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, I think that your clever trick should be used in `pal_strerror()`
</blockquote></details>

I guess it could be, should I stash it into this PR?
___
*[LibOS/shim/src/elf/shim_rtld.c, line 1030 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDK8297g0AijYa7CIt:-MUEbjkN2v6tEnlsuusM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/elf/shim_rtld.c#L1030)):*
<details><summary>< [...]

2021-02-23 17:27 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/src/shim_init.c, line 87 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUCPYkL4KnA6t2y8JDp:-MUEs2RR7E9FgwimmSUH:b8d2w23) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L87)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because I've changed this function first and then rewrote all of this incrementally (there might also have been some bugs around negations in the old code).
Now I'm done, I could restore this to just use negative values, but this sounds useful and I think I used it in some places (`pal_to_unix_errno(-ret)` to get the positive value).
I can remove it and stick to negative input + negative output convention only, if you want.
</blockquote></details>

LGTM, I'm fine with this trick.
___
*[LibOS/shim/src/shim_init.c, line 427 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDIcpFA2Afqm_FReIS:-MUEsPNB3zkdJFUF6ImM:b-g88919) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_init.c#L427)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is intended. We want to return the positive value. TBH after reading `-pal_to_unix_errno(-ret)` I would have no idea if this is positive or negative. Probably just like in the current version :)
</blockquote></details>

OK, I see, we need special handling for `DkProcessExit()`, true
___
*[LibOS/shim/src/shim_malloc.c, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJ9kc8pd4fRU9bf9g:-MUEsyyV7X8j9r3NhYPT:bc2qnpb) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/shim_malloc.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, why?
</blockquote></details>

Don't we still have the problem of the PAL function that may return `-PAL_ERROR_INTERRUPTED` during the e.g. `ocall_mmap()`?
___
*[LibOS/shim/src/shim_object.c, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJMKZ-6bWPZ9aBfhj:-MUEtNv-ERW78AAETxO_:b-yecvnh) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_object.c#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess it could be, should I stash it into this PR?
</blockquote></details>

Yes, I think it will be a small change, so let's just add here.
___
*[LibOS/shim/src/sys/shim_mmap.c, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDNNrd94dbeC6G8BJ3:-MUEtpi94oAHYZerZaZT:bhmye1k) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/sys/shim_mmap.c#L171)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess it's used for filesystem operations in which case `EACCES` is the error for, well, refusing the access.
</blockquote></details>

Interesting. I'm still not sure all this rain dancing with `PAL error code <-> UNIX error code` is worth it... Or maybe we should give subsystem context to the parser, like this: `pal_to_unix_errno(ret, LIBOS_MEMORY_SUBSYSTEM)` and based on this do the conversion `PAL_ERROR_DENIED -> EPERM`.
___
*[Pal/include/pal/pal.h, line 454 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDPfQ47Er3WCMU_Ue6:-MUEuXcoDueh30g6D7wY:b77a02p) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/Pal/include/pal/pal.h#L454)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't want to dig into this function and all checks in it right now (and for some reason I don't want to blindly assume the other text is correct :smile:  )
</blockquote></details>

The other text is correct, simply because it's very vague :)
___
*[Pal/regression/AttestationReport.c, line 96 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDQRAq8AcJk3XL4Eyk:-MUEuiCE6yQk82jKOO2o:b-vzexfx) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/Pal/regression/AttestationReport.c#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please, dont make me look at anything in `Pal/regression/` again...
</blockquote></details>

Ha-ha, I'm really sorry about this :)
___
*[Pal/src/host/Linux-SGX/db_exception.c, line 292 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDSt0VCbCIl0gCKOI9:-MUEvDox80QAmyDeD6OZ:b-kbrjpk) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/Pal/src/host/Linux-SGX/db_exception.c#L292)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we inject `EINTR` as return value from ocall anyway?
Review and possible some changes to the SGX signals are on my TODO list (I did that partially already but got interrupted).
</blockquote></details>

OK, this is one of the last things to fix.


<!-- Sent from Reviewable.io -->

2021-02-23 18:47 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/src/shim_malloc.c, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJ9kc8pd4fRU9bf9g:-MUF6MQE6Kw4NmuovHlS:b1s46b2) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/shim_malloc.c#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we still have the problem of the PAL function that may return `-PAL_ERROR_INTERRUPTED` during the e.g. `ocall_mmap()`?
</blockquote></details>

Ah, reviewable showed me the last revision, not the diff, so I thought your comment refers to a different line, my bad.
On the topic:
1) Even if we have such a problem, it should be handled at the PAL level, not here.
2) there is no such thing as ocall_mmap, all pages are added to the enclave at startup (currently).
___
*[LibOS/shim/src/shim_object.c, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJMKZ-6bWPZ9aBfhj:-MUFBi2z2uQSd7HN8keq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/shim_object.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I think it will be a small change, so let's just add here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_mmap.c, line 171 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDNNrd94dbeC6G8BJ3:-MUFC66f9ci19hI_zLAq:bdu4mlc) ([raw file](https://github.com/oscarlab/graphene/blob/0efab6a2a1946d2b9a8c4cde6bfbfcc4d420feed/LibOS/shim/src/sys/shim_mmap.c#L171)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting. I'm still not sure all this rain dancing with `PAL error code <-> UNIX error code` is worth it... Or maybe we should give subsystem context to the parser, like this: `pal_to_unix_errno(ret, LIBOS_MEMORY_SUBSYSTEM)` and based on this do the conversion `PAL_ERROR_DENIED -> EPERM`.
</blockquote></details>

I wanted to remove it completely (and use UNIX codes everywhere), but got convinced by one argument: PAL could be used without our LibOS and the more OS agnostic it is, the better.


<!-- Sent from Reviewable.io -->

2021-02-23 19:05 UTC, dimakuv submitted a review, later dismissed
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/src/shim_malloc.c, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDJ9kc8pd4fRU9bf9g:-MUFG80u1a8QE2O2ByEH:bmctigb) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/shim_malloc.c#L52)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, reviewable showed me the last revision, not the diff, so I thought your comment refers to a different line, my bad.
On the topic:
1) Even if we have such a problem, it should be handled at the PAL level, not here.
2) there is no such thing as ocall_mmap, all pages are added to the enclave at startup (currently).

</blockquote></details>

OK, true.


<!-- Sent from Reviewable.io -->

2021-02-24 01:23 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/src/sys/shim_pipe.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDNhMr9eLxXnl3M4qY:-MUGSyoC7JzrIH5OO7rd:b-qv6r41) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/sys/shim_pipe.c#L46)):*
>  Actually: quick google showed the correct form is `acception`.

Uh, how so? "Acception" seems to be some uncommon/archaic form, some dictionaries even miss it altogether. "Acceptation" is the one used everywhere.


<!-- Sent from Reviewable.io -->

2021-02-24 10:31 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_pipe.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDNhMr9eLxXnl3M4qY:-MUIYyx11pt_kjVTfU5K:bz3qk6k) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/sys/shim_pipe.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

>  Actually: quick google showed the correct form is `acception`.

Uh, how so? "Acception" seems to be some uncommon/archaic form, some dictionaries even miss it altogether. "Acceptation" is the one used everywhere.
</blockquote></details>

Seems I got lost in wiktionary syntax.
https://en.wiktionary.org/wiki/acceptance seems to be the correct word here ;)


<!-- Sent from Reviewable.io -->

2021-02-25 02:37 UTC, mkow requested changes
> Reviewed 46 of 101 files at r1, 8 of 12 files at r2, 3 of 9 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 178 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKxcnR7GfMGW6YtlAv:-MUKxcnR7GfMGW6YtlAw:b-dsvetj) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/include/shim_internal.h#L178)):*
> ```objc
> bool handle_signal(PAL_CONTEXT* context, __sigset_t* old_mask_ptr);
> 
> long pal_to_unix_errno(long err);
> ```

Please document that it preserves the sign.
___
*[LibOS/shim/include/shim_internal.h, line 255 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKJcvI-y4UzNlDwmQ0:-MUKJcvI-y4UzNlDwmQ1:b4uenha) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/include/shim_internal.h#L255)):*
> ```objc
>             return -ENODATA;
>         }
>     }
> ```

Hmm, so, now this `while` loop can only stop spinning after an error? The old implementation stopped after a successful read.
___
*[LibOS/shim/src/shim_checkpoint.c, line 639 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKvXX--Fp-GCxPdwhW:-MUKvXX--Fp-GCxPdwhX:bn8krv4) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/shim_checkpoint.c#L639)):*
> ```C
>     if (ret < 0) {
>         if (pal_process)
>             DkObjectClose(pal_process);
> ```

This code relies on `DkProcessCreate` not overwriting `pal_process` on error. Is this a convention we want to explicitly have in the whole PAL API? For me this is not an obvious assumption, because there are cases where modifying argument even on error makes sense (e.g. time elapsed on sleep, which got interrupted).
___
*[LibOS/shim/src/shim_checkpoint.c, line 726 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKwzxRBWnAGLVIN3iy:-MUKwzxRBWnAGLVIN3iz:bjw0az) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/shim_checkpoint.c#L726)):*
> ```C
>     if (DkVirtualMemoryFree(mapaddr, mapsize) < 0) {
>         BUG();
>     }
> ```

Please unify bracing either way (the `if` above doesn't have braces, and this one has)
___
*[LibOS/shim/src/shim_object.c, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUL-Sq4ASkYa6LORlJM:-MUL-Sq4ASkYa6LORlJN:b-ump2st) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/shim_object.c#L11)):*
> ```C
> 
>     if (ret < 0) {
>         log_error("waiting on %p resulted in error %s", handle, pal_strerror(ret));
> ```

You undid my change :) I removed the pointer on purpose: a) I don't think it's really useful to have pointer values in the log, b) errors are visible in production builds, not sure if leaking pointer values is a good idea.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 631 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULIVoM8zkgJgL-4Iuc:-MULIVoM8zkgJgL-4Iud:b74tawh) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/fs/chroot/fs.c#L631)):*
> ```C
>         if (file->type != FILE_TTY && __builtin_add_overflow(file->marker, count, &file->marker))
>             BUG();
>         ret = count;
> ```

Other places do `if (__builtin_add_overflow(count, 0, &ret))`, same as the old version of this code, to prevent overflows.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 264 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULLdluAyzshzUyQ4JO:-MULLdluAyzshzUyQ4JP:bphymhu) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc.c#L264)):*
> ```C
>         int ret = DkStreamWrite(port->pal_handle, 0, &size, (void*)msg + bytes, NULL);
> 
>         if (ret < 0 || size == 0) {
> ```

Hmm, so, the value written back to `size` argument is actually bytes written, not bytes left to be written? A bit confusing to me, maybe it would be better to switch it the other way or return in an additional argument?
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 581 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULNCFL6VUXV7je_zyg:-MULNCFL6VUXV7je_zyh:bug0dbk) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_helper.c#L581)):*
> ```C
>                     ret = pal_to_unix_errno(ret);
>                     log_debug("Port %p (handle %p): error while receiving IPC message: %d\n", port,
>                           port->pal_handle, ret);
> ```

alignment is now broken
ditto above
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 762 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULNcOk9XXZF7wqC7qL:-MULNcOk9XXZF7wqC7qM:b970ajp) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_helper.c#L762)):*
> ```C
>             goto out_err;
>         }
>         PAL_BOL polled = ret == 0;
> ```

`PAL_BOL` -> `bool`
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 764 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULNowh1Viu_fodNH8i:-MULNowh1Viu_fodNH8j:b-ofeuer) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_helper.c#L764)):*
> ```C
>         PAL_BOL polled = ret == 0;
> 
>         for (size_t i = 0; polled && i < ports_cnt + 1; i++) {
> ```

It was like this before, but why `polled` is checked every loop iteration, while not being modified inside the loop?
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 1477 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULOvVJ6rrhXnVl9O-w:-MULOvVK1OEkzr1EnC4c:b5fiq8j) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_ranges.c#L1477)):*
> ```C
>             PAL_HANDLE pal_handle = NULL;
>             int ret = DkStreamOpen(uri, 0, 0, 0, 0, &pal_handle);
>             (void)ret; // I have no idea how to handle errors here, this function needs a rework.
> ```

maybe at least `BUG()` here?
___
*[LibOS/shim/src/sys/shim_alarm.c, line 82 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULP5mGDsWjHhYXqiP6:-MULP5mGDsWjHhYXqiP7:bkw326h) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/sys/shim_alarm.c#L82)):*
> ```C
> 
>     uint64_t setup_time = 0;
>     int64_t ret = DkSystemTimeQuery(&setup_time);
> ```

`int64_t` -> `int`
___
*[LibOS/shim/src/sys/shim_epoll.c, line 341 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULPxW13dOz-AeOKQ7N:-MULPxW13dOz-AeOKQ7O:b970ajp) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/sys/shim_epoll.c#L341)):*
> ```C
>         long error = DkStreamsWaitEvents(pal_cnt + 1, pal_handles, pal_events, ret_events,
>                                          timeout_ms * 1000);
>         PAL_BOL polled = error == 0;
> ```

`PAL_BOL` -> `bool`
___
*[LibOS/shim/src/sys/shim_pipe.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDNhMr9eLxXnl3M4qY:-MUKI7FC9j7SVUHUtnkn:b-fnhikh) ([raw file](https://github.com/oscarlab/graphene/blob/11bae54f87d237a2854fc6ebdf1b1471c38314ce/LibOS/shim/src/sys/shim_pipe.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Seems I got lost in wiktionary syntax.
https://en.wiktionary.org/wiki/acceptance seems to be the correct word here [...]

2021-02-25 12:10 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 178 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKxcnR7GfMGW6YtlAv:-MUNrKLzANusObeERzIZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/include/shim_internal.h#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please document that it preserves the sign.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_internal.h, line 255 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKJcvI-y4UzNlDwmQ0:-MUNsaaOBPLiiXtRktGm:bmqd0wf) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/include/shim_internal.h#L255)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, so, now this `while` loop can only stop spinning after an error? The old implementation stopped after a successful read.
</blockquote></details>

Oops, there was supposed to be a break at the end. After adding it it seemed ugly, so I rewrote this a bit.
Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 639 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKvXX--Fp-GCxPdwhW:-MUNt8Sb9ndJ9RficuLb:bybc6bn) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/shim_checkpoint.c#L639)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This code relies on `DkProcessCreate` not overwriting `pal_process` on error. Is this a convention we want to explicitly have in the whole PAL API? For me this is not an obvious assumption, because there are cases where modifying argument even on error makes sense (e.g. time elapsed on sleep, which got interrupted).
</blockquote></details>

No, this code relies on `DkProcessCreate` not overwriting `pal_process` with garbage. I don't want to have a convention of not-overwriting out-arguments on errors, BUT I would like to have what we have right now: out-arguments must be meaningful and valid (or unchanged).
___
*[LibOS/shim/src/shim_checkpoint.c, line 726 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUKwzxRBWnAGLVIN3iy:-MUNwTzjDEl_SqTp7Hv6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/shim_checkpoint.c#L726)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please unify bracing either way (the `if` above doesn't have braces, and this one has)
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_object.c, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUL-Sq4ASkYa6LORlJM:-MUNwoXQ6U9szxCfXInW:b-7i2els) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/shim_object.c#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You undid my change :) I removed the pointer on purpose: a) I don't think it's really useful to have pointer values in the log, b) errors are visible in production builds, not sure if leaking pointer values is a good idea.
</blockquote></details>

Rebase fail (that's why I was grumbling about that rebase).
Done.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 631 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULIVoM8zkgJgL-4Iuc:-MUNyXEF4Uq_TR1ksqZN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/fs/chroot/fs.c#L631)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Other places do `if (__builtin_add_overflow(count, 0, &ret))`, same as the old version of this code, to prevent overflows.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 264 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULLdluAyzshzUyQ4JO:-MUO0GHlDBd1qdGr-jTv:b-63ir2e) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc.c#L264)):*
> Hmm, so, the value written back to size argument is actually bytes written, not bytes left to be written? 
 
Yes.
> or return in an additional argument?

That was the original idea, but I decided not to bloat the API with more arguments.
> A bit confusing to me, maybe it would be better to switch it the other way

I don't think that will be useful in most call sites. Also returning bytes left to be written would be confusing as hell to me.

I'm with the current version, but I won't oppose if you insist on adding additional out-argument.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 581 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULNCFL6VUXV7je_zyg:-MUO1l6k-UOVDuS-E9WR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_helper.c#L581)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

alignment is now broken
ditto above
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 762 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULNcOk9XXZF7wqC7qL:-MUO1piH9PejbBMEDGzY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_helper.c#L762)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`PAL_BOL` -> `bool`
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_helper.c, line 764 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULNowh1Viu_fodNH8i:-MUO1tE-Akz6TE4Te8k0:b-kipuri) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_helper.c#L764)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was like this before, but why `polled` is checked every loop iteration, while not being modified inside the loop?
</blockquote></details>

I guess to have one indentation level less? No other ideas.
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 1477 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULOvVJ6rrhXnVl9O-w:-MUO26KpCyQ-EQ_OWIAw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc_ranges.c#L1477)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

maybe at least `BUG()` here?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_alarm.c, line 82 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULP5mGDsWjHhYXqiP6:-MUO33fz-7736CjD9RPZ:b-a73shv) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/sys/shim_alarm.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`int64_t` -> `int`
</blockquote></details>

But `install_async_event` uses this variable below (and it returns `int64_t`). I could split this into 2 variables, if you insist.
Actually, done just that.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 341 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULPxW13dOz-AeOKQ7N:-MUO3XgU4ESrBKuLjQ_j:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/sys/shim_epoll.c#L341)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blo [...]

2021-02-25 14:27 UTC, mkow requested changes
> Reviewed 43 of 101 files at r1, 2 of 12 files at r2, 6 of 9 files at r3, 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 260 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOAKuIDaN_r8fDarJo:-MUOAKuIDaN_r8fDarJp:babfbi6) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/LibOS/shim/include/shim_internal.h#L260)):*
> ```objc
>     } while (ret == -EINTR || ret == -EAGAIN);
> 
>     return ret < 0 ? ret : 0;
> ```

can `DkStreamRead` return anything > 0? If not, why we have this whole translation?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 264 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULLdluAyzshzUyQ4JO:-MUOC6gf2kTdEexeT37u:ba5pi8w) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/LibOS/shim/src/ipc/shim_ipc.c#L264)):*
> Also returning bytes left to be written would be confusing as hell to me.

The idea would be to pass the same variable on a retry loop there, without the need for any calculation is such a loop, just set it to "bytes left" and loop until done.

> I'm with the current version, but I won't oppose if you insist on adding additional out-argument.

Ok, let's leave it as is.
___
*[Pal/include/pal/pal.h, line 406 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULpb0W6KMQf-PJhUrB:-MUOBAOhETcP2x5fr91t:bilo4h1) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/include/pal/pal.h#L406)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still have `see #DkVirtualMemoryAlloc` on the resulting page :/
___
*[Pal/regression/File.c, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUNz1a95EK-78vmt-LJ:-MUNz1aA3-BlqFbWl50H:b-5whjs4) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/File.c#L29)):*
> ```C
>     PAL_HANDLE file1 = NULL;
>     ret = DkStreamOpen("file:File", PAL_ACCESS_RDWR, 0, 0, 0, &file1);
>     if (ret >= 0 && file1) {
> ```

In some places you write `ret >= 0` and in others you write `ret == 0`, could you unify?
___
*[Pal/regression/Select.c, line 39 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO2tu2DncqIbnQVK-T:-MUO2tu2DncqIbnQVK-U:b-98wmh6) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Select.c#L39)):*
> ```C
>         return 1;
>     }
>     wakeup     = handles[2];
> ```

please unalign, now it doesn't make sense
___
*[Pal/regression/SendHandle.c, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO5aCH-z37EHOGv_oI:-MUO5aCH-z37EHOGv_oJ:bfutn6j) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/SendHandle.c#L116)):*
> ```C
>             }
> 
>             ret = DkStreamOpen("file:to_send.tmp", PAL_ACCESS_RDWR, 0600, PAL_CREATE_TRY, 0, &handles[2]);
> ```

please wrap
___
*[Pal/regression/Tcp.c, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO7F_C2L4MZiaA6Lf1:-MUO7F_C2L4MZiaA6Lf2:b-vdgqsb) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L17)):*
> ```C
> 
>     if (argc == 1) {
>         unsigned long time = 0;
> ```

old bug, but should be `int64_t`
___
*[Pal/regression/Tcp.c, line 130 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8HTq6RWqpJlFq5RB:-MUO8HTr49lrIpBRPcN_:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L130)):*
> ```C
>         }
> 
>         unsigned long end = 0;
> ```

ditto
___
*[Pal/regression/Tcp.c, line 137 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8N-o8wachk2MAtlF:-MUO8N-o8wachk2MAtlG:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L137)):*
> ```C
>         pal_printf("end time = %lu\n", end);
> 
>         unsigned long start = atol(argv[1]);
> ```

ditto
___
*[Pal/regression/Udp.c, line 15 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8Xmx-iak8QT3jTFg:-MUO8Xmx-iak8QT3jTFh:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Udp.c#L15)):*
> ```C
> 
>     if (argc == 1) {
>         unsigned long start = 0;
> ```

ditto
___
*[Pal/regression/Udp.c, line 56 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8Z28BiFMQPQXBJBr:-MUO8Z28BiFMQPQXBJBs:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Udp.c#L56)):*
> ```C
>         }
> 
>         unsigned long end = 0;
> ```

ditto
___
*[Pal/regression/Udp.c, line 97 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO9O8E1yzR1hdTzBYp:-MUO9O8E1yzR1hdTzBYq:bx72q8n) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Udp.c#L97)):*
> ```C
> 
>         for (i = 0; i < NTRIES; i++) {
>             char buf[12] = "Hello World";
> ```

why not `[]`?
___
*[Pal/src/db_misc.c, line 28 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOHrHX6h6Xj-DULPWG:-MUOHrHYBlW-gaIVDIad:bk7s692) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/Pal/src/db_misc.c#L28)):*
> ```C
> 
> int DkSegmentRegisterSet(PAL_FLG reg, PAL_PTR addr) {
>     return _DkSegmentRegisterSet(reg, addr);
> ```

I guess this internal/external split of most of the PAL API is not really needed now? (but that's for another PR)
___
*[Pal/src/db_streams.c, line 243 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOJ_Qh55dN0baYFAmP:-MUOJ_Qh55dN0baYFAmQ:bwpu2ql) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/Pal/src/db_streams.c#L243)):*
> ```C
> 
> int DkStreamRead(PAL_HANDLE handle, PAL_NUM offset, PAL_NUM* count, PAL_PTR buffer, PAL_PTR source,
>              PAL_NUM size) {
> ```

broken alignment
___
*[Pal/src/db_streams.c, line 440 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOKutw1idkEvBgQXBM:-MUOKltI0r-NbnyreBGY:b-xwyhuz) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/Pal/src/db_streams.c#L440)):*
> ```C
>     }
> 
>     if (map_addr && _DkCheckMemoryMappable(map_addr, size)) {
> ```

Do I see correctly, that `_DkCheckMemoryMappable` returns `true`if memory is _not_ mappable? Great convention...
But let's leave fixing it for another PR.


<!-- Sent from Reviewable.io -->

2021-02-25 16:42 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @woju, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 260 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOAKuIDaN_r8fDarJo:-MUOvmRL1jHqYJLbo3J4:b-qilifn) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/LibOS/shim/include/shim_internal.h#L260)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

can `DkStreamRead` return anything > 0? If not, why we have this whole translation?
</blockquote></details>

Brain lag.
Done.
___
*[Pal/include/pal/pal.h, line 406 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MULpb0W6KMQf-PJhUrB:-MUOw3USDmYY4gBuU4Kl:b-djyf5) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/include/pal/pal.h#L406)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I still have `see #DkVirtualMemoryAlloc` on the resulting page :/
</blockquote></details>

Hmm, https://www.doxygen.nl/manual/autolink.html says `#` can be used. It's used everywhere else, so I didn't want to change convention...
Seems to be unrelated bug, @woju is on it.
Update: added a fix, thx to @woju for it.
___
*[Pal/regression/File.c, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUNz1a95EK-78vmt-LJ:-MUP-vM88mmI99aZsnS_:b-saue3o) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/File.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In some places you write `ret >= 0` and in others you write `ret == 0`, could you unify?
</blockquote></details>

Do I have to? It's Pal/regression, this needs to be purged anyway...
___
*[Pal/regression/Select.c, line 39 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO2tu2DncqIbnQVK-T:-MUP1kYLDqhFqjoJ5Qbn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Select.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please unalign, now it doesn't make sense
</blockquote></details>

Done.
___
*[Pal/regression/SendHandle.c, line 116 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO5aCH-z37EHOGv_oI:-MUP1g5UB9GPJGYfQXrm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/SendHandle.c#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please wrap
</blockquote></details>

Done.
___
*[Pal/regression/Tcp.c, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO7F_C2L4MZiaA6Lf1:-MUP1mIW600kT-FFeJJM:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

old bug, but should be `int64_t`
</blockquote></details>

ditto
___
*[Pal/regression/Tcp.c, line 130 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8HTq6RWqpJlFq5RB:-MUP1nA48p_ITwulumwx:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L130)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/regression/Tcp.c, line 137 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8N-o8wachk2MAtlF:-MUP1o727dfg4NPdumii:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L137)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/regression/Udp.c, line 15 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8Xmx-iak8QT3jTFg:-MUP1p4yBBKdjYLyfW5W:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Udp.c#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/regression/Udp.c, line 56 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO8Z28BiFMQPQXBJBr:-MUP1pnZ1GSwTqWFXuTJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Udp.c#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/regression/Udp.c, line 97 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO9O8E1yzR1hdTzBYp:-MUP1r7-2O4tyEucVwI6:bisjrzz) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Udp.c#L97)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why not `[]`?
</blockquote></details>

No idea, the old version sent 12 bytes, I do not want to investigate, these tests make little sense anyway.
___
*[Pal/src/db_misc.c, line 28 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOHrHX6h6Xj-DULPWG:-MUP22p66z-K0wCt70VD:b-4en705) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/Pal/src/db_misc.c#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess this internal/external split of most of the PAL API is not really needed now? (but that's for another PR)
</blockquote></details>

Yeah, it makes little sens if it's just a passthrough like here.
___
*[Pal/src/db_streams.c, line 243 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOJ_Qh55dN0baYFAmP:-MUP2nZT3Sh7gziE0VVU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/Pal/src/db_streams.c#L243)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

broken alignment
</blockquote></details>

Done.
___
*[Pal/src/db_streams.c, line 440 at r5](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUOKutw1idkEvBgQXBM:-MUP35D22HWzY3v1CtEz:b-x0paxf) ([raw file](https://github.com/oscarlab/graphene/blob/bdabcbb02ebde23dc665b10a44cd75e07aa8ab2f/Pal/src/db_streams.c#L440)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do I see correctly, that `_DkCheckMemoryMappable` returns `true`if memory is _not_ mappable? Great convention...
But let's leave fixing it for another PR.
</blockquote></details>

Yes :)


<!-- Sent from Reviewable.io -->

2021-02-25 17:02 UTC, mkow requested changes
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/regression/File.c, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUNz1a95EK-78vmt-LJ:-MUP7mYyBPL2Li3x6AsU:bjj06o7) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/File.c#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do I have to? It's Pal/regression, this needs to be purged anyway...
</blockquote></details>

Ok, right.
___
*[Pal/regression/Tcp.c, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO7F_C2L4MZiaA6Lf1:-MUP7tFLDHXX8dzfzc5x:b-4d6jrx) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

but this fix is trivial, please do it, just for sanity ;)


<!-- Sent from Reviewable.io -->

2021-02-25 17:27 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Pal/regression/Tcp.c, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO7F_C2L4MZiaA6Lf1:-MUPDelr-Zl84EKX7wM2:bml7rv7) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

but this fix is trivial, please do it, just for sanity ;)
</blockquote></details>

Why would it be `int64_t`? What's the bug here?


<!-- Sent from Reviewable.io -->

2021-02-25 17:42 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[Pal/regression/Tcp.c, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUO7F_C2L4MZiaA6Lf1:-MUPFbQb1-radBI4naYZ:bfv2ag0) ([raw file](https://github.com/oscarlab/graphene/blob/17d05977e7d0a5626d04c36efe628d91f232e542/Pal/regression/Tcp.c#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why would it be `int64_t`? What's the bug here?
</blockquote></details>

Oh, seems I misread `DkSystemTimeQuery` signature (or confused it with something else). Let's wait with fixing this until we get rid of `PAL_NUM`.


<!-- Sent from Reviewable.io -->

2021-02-25 17:47 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: 108 of 109 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2182#-MUDCrTFEvr6xJpDhQiC:-MUPIJc87PbkoXfKKnPW:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at rebase
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-02-25 17:51 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-02-25 17:58 UTC, boryspoplawski commented
Jenkins, retest  Jenkins-SGX-18.04-apps please (internal jenkins issues)

2021-02-25 18:01 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-apps please (internal jenkins issues)

2021-02-25 18:02 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-18.04-apps please (internal jenkins issues)

2021-02-25 18:25 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2182)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-25 18:32 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-apps please (internal jenkins issues)

2021-02-25 18:56 UTC, merged