Add TensorFlow Serving Cluster Tutorial
oscarlab/graphene pull request #2194
Opened 2021-02-26 07:53 UTC by RodgerZhu

## Description of the changes 
Add TensorFlow Serving Cluster Tutorial

## How to test this PR? 
N/A.

2021-03-01 09:15 UTC, dimakuv requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 55 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgtlhe2sh_DETQAnNB:-MUgtlhe2sh_DETQAnNC:b-kuub87) (no related file):*
Could you change the image files from `.jpg` to `.svg`? SVG files are just nicer for web sites. Also, SVG files are more light-weight and can be re-used by others if they want to draw.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUguG85CId4HViAwYCF:-MUguG85CId4HViAwYCG:bcz0a2l) (no related file):*
Please add a link to your new file in `Documentation/index.rst` (similarly to PyTorch tutorial).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgwhat-nVfZ--SrmyE:-MUgwhat-nVfZ--SrmyF:buyuw46) (no related file):*
In your `Graphene_TF_Serving_Flow.jpg` diagram:
- `Mode Uploader` -> `Model Uploader`
- `Keys & Certificates Providers` -> what is "providers" here? Did you mean `Keys & Certificates of Providers`?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUh330X61URzdEnIwg3:-MUh330X61URzdEnIwg4:b-fq9wif) (no related file):*
For other reviewers: this tutorial currently refers to `<graphene repository>/Examples/tensorFlow-serving-cluster/tensorflow-serving`. We agreed to move the accompanying scripts/files **not** under `Examples/` but to some other Graphene-related repository (e.g. `oscarlab/graphene-contrib`). We're currently working on this...

---
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUguO8v5WL5UYPC0HJJ:-MUguO8v5WL5UYPC0HJK:b1h1eva) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L6)):*
> ```reStructuredText
> 
> 
> This tutorial presents a framework for developing a PPML (Privacy-Preserving 
> ```

There is a trailing whitespace on this line. Please remove it here (and also check in other places, you have a few places like this).
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgufRk2Q9djpG_lVyU:-MUgufRk2Q9djpG_lVyV:b-pbwgvi) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L15)):*
> ```reStructuredText
> Simply running a TensorFlow Serving system inside Graphene is not enough for a
> safe & secure end-user experience. Thus, there is a need to build a complete
> secure inferencing flow. Instead, this tutorial will present TensorFlow Serving
> ```

Please remove `Instead, `. It is not needed here.
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgumOOAWPaPBdz_xe9:-MUgumOOAWPaPBdz_xeA:b-iu3p39) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L16)):*
> ```reStructuredText
> safe & secure end-user experience. Thus, there is a need to build a complete
> secure inferencing flow. Instead, this tutorial will present TensorFlow Serving
> with Intel SGX and Graphene and will involve full-flow protection (from client
> ```

`will involve full-flow protection` -> `will provide end-to-end protection`
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgv2RM2GQElKfcbQBU:-MUgv2RM2GQElKfcbQBV:b-5kizrb) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L26)):*
> ```reStructuredText
> efficiently manage those clusters. Kubernetes clusters can span hosts across
> on-premise, public, private, or hybrid clouds. For this reason, Kubernetes is
> an
> ```

Please re-wrap these lines.
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvJ7Y6-mb7Ix5RE1k:-MUgvJ7Z7PJ0TTMPWmRX:bkb8uwv) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L48)):*
> ```reStructuredText
>    :target: ./NGINX-Ingress-Controller.jpg
>    :scale: 50 %
>    :alt: Figure: Nginx ingress controller
> ```

`Nginx ingress` -> `Nginx Ingress` (capitalize)
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvNnIEpxwjl0c1QcR:-MUgvNnIEpxwjl0c1QcS:b-c5g7n5) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L52)):*
> ```reStructuredText
> In this tutorial, we focus on:
> 
> - AI Service - TensorFlow Serving , a flexible, high-performance serving system
> ```

`TensorFlow Serving , a` -> `TensorFlow Serving, a` (remove unnecessary space)
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 65 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvbIvCR_hb7EYh14V:-MUgvbIvCR_hb7EYh14W:bryc2nq) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L65)):*
> ```reStructuredText
>   scaling, and management of containerized TensorFlow Serving so that the cloud
>   providers can setup the environment easily. Using Nginx to automatically load
>   balance.
> ```

`Using Nginx to automatically load balance.` -> `We use Nginx for automatic load balancing.`
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvpOZ146vKeC36WM3:-MUgvpOZ146vKeC36WM4:b-6wu2xr) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L73)):*
> ```reStructuredText
> isolate TensorFlow Serving's execution to protect data confidentiality and
> integrity, and to provide a cryptographic proof that the program is correctly
> initialized and running on legitimate hardware with the latest patches.We also
> ```

`with the latest patches.We also` -> `with the latest patches. We also` (please add a space after the dot)
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvwcS0gAjZfDEw6UA:-MUgvwcS0gAjZfDEw6UB:bz82dfb) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L83)):*
> ```reStructuredText
> 
> In this tutorial, we use three machines: `Machine A` is the trusted machine,
> it can be non-SGX platform or SGX platform; `Machine B` is SGX-enabled,
> ```

`it can be non-SGX platform or SGX platform` -> `it can be a non-SGX platform or an SGX platform` (please add `a/an`)
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgwFSl0sxfavhcY9Cy:-MUgwFSl0sxfavhcY9Cz:bjis9op) ([raw file](https://github.co [...]

2021-03-02 08:32 UTC, RodgerZhu commented
> > Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)_ status: all files reviewed, 55 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgtlhe2sh_DETQAnNB:-MUgtlhe2sh_DETQAnNC:b-kuub87) (no related file):_
> Could you change the image files from `.jpg` to `.svg`? SVG files are just nicer for web sites. Also, SVG files are more light-weight and can be re-used by others if they want to draw.
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUguG85CId4HViAwYCF:-MUguG85CId4HViAwYCG:bcz0a2l) (no related file):_
> Please add a link to your new file in `Documentation/index.rst` (similarly to PyTorch tutorial).
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgwhat-nVfZ--SrmyE:-MUgwhat-nVfZ--SrmyF:buyuw46) (no related file):_
> In your `Graphene_TF_Serving_Flow.jpg` diagram:
> 
> * `Mode Uploader` -> `Model Uploader`
> * `Keys & Certificates Providers` -> what is "providers" here? Did you mean `Keys & Certificates of Providers`?
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUh330X61URzdEnIwg3:-MUh330X61URzdEnIwg4:b-fq9wif) (no related file):_
> For other reviewers: this tutorial currently refers to `<graphene repository>/Examples/tensorFlow-serving-cluster/tensorflow-serving`. We agreed to move the accompanying scripts/files **not** under `Examples/` but to some other Graphene-related repository (e.g. `oscarlab/graphene-contrib`). We're currently working on this...
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUguO8v5WL5UYPC0HJJ:-MUguO8v5WL5UYPC0HJK:b1h1eva) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L6)):_
> 
> > ```
> > This tutorial presents a framework for developing a PPML (Privacy-Preserving 
> > ```
> 
> There is a trailing whitespace on this line. Please remove it here (and also check in other places, you have a few places like this).
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgufRk2Q9djpG_lVyU:-MUgufRk2Q9djpG_lVyV:b-pbwgvi) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L15)):_
> 
> > ```
> > Simply running a TensorFlow Serving system inside Graphene is not enough for a
> > safe & secure end-user experience. Thus, there is a need to build a complete
> > secure inferencing flow. Instead, this tutorial will present TensorFlow Serving
> > ```
> 
> Please remove `Instead, `. It is not needed here.
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgumOOAWPaPBdz_xe9:-MUgumOOAWPaPBdz_xeA:b-iu3p39) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L16)):_
> 
> > ```
> > safe & secure end-user experience. Thus, there is a need to build a complete
> > secure inferencing flow. Instead, this tutorial will present TensorFlow Serving
> > with Intel SGX and Graphene and will involve full-flow protection (from client
> > ```
> 
> `will involve full-flow protection` -> `will provide end-to-end protection`
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgv2RM2GQElKfcbQBU:-MUgv2RM2GQElKfcbQBV:b-5kizrb) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L26)):_
> 
> > ```
> > efficiently manage those clusters. Kubernetes clusters can span hosts across
> > on-premise, public, private, or hybrid clouds. For this reason, Kubernetes is
> > an
> > ```
> 
> Please re-wrap these lines.
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvJ7Y6-mb7Ix5RE1k:-MUgvJ7Z7PJ0TTMPWmRX:bkb8uwv) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L48)):_
> 
> > ```
> >    :target: ./NGINX-Ingress-Controller.jpg
> >    :scale: 50 %
> >    :alt: Figure: Nginx ingress controller
> > ```
> 
> `Nginx ingress` -> `Nginx Ingress` (capitalize)
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvNnIEpxwjl0c1QcR:-MUgvNnIEpxwjl0c1QcS:b-c5g7n5) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L52)):_
> 
> > ```
> > In this tutorial, we focus on:
> > 
> > - AI Service - TensorFlow Serving , a flexible, high-performance serving system
> > ```
> 
> `TensorFlow Serving , a` -> `TensorFlow Serving, a` (remove unnecessary space)
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 65 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvbIvCR_hb7EYh14V:-MUgvbIvCR_hb7EYh14W:bryc2nq) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L65)):_
> 
> > ```
> >   scaling, and management of containerized TensorFlow Serving so that the cloud
> >   providers can setup the environment easily. Using Nginx to automatically load
> >   balance.
> > ```
> 
> `Using Nginx to automatically load balance.` -> `We use Nginx for automatic load balancing.`
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 73 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvpOZ146vKeC36WM3:-MUgvpOZ146vKeC36WM4:b-6wu2xr) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L73)):_
> 
> > ```
> > isolate TensorFlow Serving's execution to protect data confidentiality and
> > integrity, and to provide a cryptographic proof that the program is correctly
> > initialized and running on legitimate hardware with the latest patches.We also
> > ```
> 
> `with the latest patches.We also` -> `with the latest patches. We also` (please add a space after the dot)
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgvwcS0gAjZfDEw6UA:-MUgvwcS0gAjZfDEw6UB:bz82dfb) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L83)):_
> 
> > ```
> > In this tutorial, we use three machines: `Machine A` is the trusted machine,
> > it can be non-SGX platform or SGX platform; `Machine B` is SGX-enabled,
> > ```
> 
> `it can be non-SGX platform or SGX platform` -> `it can be a non-SGX platform or an SGX platform` (please add `a/an`)
> 
> _[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgwFSl0sxfavhcY9Cy:-MUgwFSl0sxfavhcY9Cz:bjis9op) ([raw f [...]

2021-03-02 08:37 UTC, RodgerZhu commented
Reopen this PR.

2021-03-02 10:27 UTC, dimakuv requested changes
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUguG85CId4HViAwYCF:-MUmPFXw3bCbSnyF8T-j:b-1lurvi) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a link to your new file in `Documentation/index.rst` (similarly to PyTorch tutorial).
</blockquote></details>

This is not yet done. Forgot to add the file to the git commit?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUh330X61URzdEnIwg3:-MUmPPkl6W6oGkCRS961:bly67dt) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For other reviewers: this tutorial currently refers to `<graphene repository>/Examples/tensorFlow-serving-cluster/tensorflow-serving`. We agreed to move the accompanying scripts/files **not** under `Examples/` but to some other Graphene-related repository (e.g. `oscarlab/graphene-contrib`). We're currently working on this...
</blockquote></details>

Update: the repo is created, https://github.com/oscarlab/graphene-contrib. @rodgerzhu will push the corresponding scripts as a PR to this new repo.

---
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 83 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmQF9e2InMCXxU3OSM:-MUmQF9e2InMCXxU3OSN:b80lc9l) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L83)):*
> ```reStructuredText
> 
> In this tutorial, we use three machines: `Machine A` is the trusted machine,
> it can be a non-SGX platform or SGX platform; `Machine B` is SGX-enabled,
> ```

`or SGX platform` -> `or an SGX platform`
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 164 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmQrEv7oVZkiKqMbx8:-MUmQrEv7oVZkiKqMbx9:b-w0ov3m) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L164)):*
> ```reStructuredText
>   host to get the tool `pf_crypt`, which will be used to encrypt the model file.
> 
> - TensorFlow Serving cluster scripts package. You can download the scrips package
> ```

`scrips` -> `scripts`
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 165 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmQhzy2NPsopkiVHRj:-MUmQhzy2NPsopkiVHRk:b52rtva) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L165)):*
> ```reStructuredText
> 
> - TensorFlow Serving cluster scripts package. You can download the scrips package
>   `tensorflow-serving-cluster` `here <https://github.com/oscarlab/graphene-contrib.git>`.
> ```

This formatting is wrong. Please use the reST formatting for hyperlinks as in other places in this file. 
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 178 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmR1J1DguGnvsuSNfe:-MUmR1J1DguGnvsuSNff:bpyhrf9) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L178)):*
> ```reStructuredText
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> Under the untrusted machine B, go to the directory::
> ```

`Under the untrusted machine B, go to the directory` -> `Under the untrusted machine B, clone the GitHub repository with our provided scripts and go to the directory`
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmRFv83yVclLPQrxcs:-MUmRFv83yVclLPQrxct:b-t1n4ai) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L205)):*
> ```reStructuredText
>    models/resnet50-v15-fp32/1/saved_model.pb
> 
> Next step, we will pull the Docker image of TensorFlow Serving.
> ```

`Next step,` -> `Next,`
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 228 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmRQcj4jMNdQPVyLpC:-MUmRQcj4jMNdQPVyLpD:bstz2i0) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L228)):*
> ```reStructuredText
> 
> We choose gRPC TLS and create the one-way TLS Keys and certificates by setting
> TensorFlow Serving domain name to keep the communication link between client
> ```

`keep the` -> `establish a`
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 254 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmRbAyAyK3Uo8F9p1W:-MUmRbAyAyK3Uo8F9p1X:b-1ss80f) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L254)):*
> ```reStructuredText
> requests from the client.
> 
> To run the client, under the untrusted machine C, go to the directory::
> ```

`...under the untrusted machine C, go to the directory` -> `...under the untrusted machine C, clone the GitHub repository with our provided scripts and go to the directory`
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 273 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmRkFX0tRGzB3-hVce:-MUmRkFX0tRGzB3-hVcf:b-kom2r9) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L273)):*
> ```reStructuredText
> *Note*: Please make sure that the connection between machines A and B is good.
> ``machineB_ip_addr`` is the IP address of machine B; ``service_domain_name``
> is a domain name of TensorFlow Serving set under machine B.
> ```

`set under` -> `installed on`
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 424 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmSNOY7xRAszB2HYm1:-MUmSNOY7xRAszB2HYm2:b-npqj5l) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L424)):*
> ```reStructuredText
> Initialize and enable taint for master node. Kubernetes allows users to taint
> the node so that no pods can be scheduled to it, unless a pod explicitly tolerates
> the taint.::
> ```

`.::` -> `::` (remove the dot)
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 559 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmScQ24mBzWH5jtROJ:-MUmScQ24mBzWH5jtROK:bvqenlk) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L559)):*
> ```reStructuredText
> Move this encrypted model file to replace the plaintext file under::
> 
>    <graphene-contrib repository>/tensorflow-serving-cluste/tensorFlow-serving/models/resnet50-v15-fp32/1/saved_model.pb
> ```

You still have `tensorflow-serving-cluste/` typo in some places. Please fix everywhere (you need to add `r`).
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 617 at r3](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUmSzKr6gltOR2-Y9Go:-MUmSzKr6gltOR2-Y9Gp:b-bgpv36) ([raw file](https://github.com/oscarlab/graphene/blob/5bf26fabe2c9d6d1aa76df1ba8ab39ddddbaf390/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L617)): [...]

2021-03-03 09:40 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUrR4kuDGEWwOw4mN6v:-MUrR4kuDGEWwOw4mN6w:b8ohi9t) ([raw file](https://github.com/oscarlab/graphene/blob/d9a1cdba1e8e609dd8ec589125bbd64e8a9efcbd/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L35)):*
> ```reStructuredText
> in Kubernetes `pods <https://kubernetes.io/docs/concepts/workloads/pods/pod/>`__
> are not accessible from the external network, but only from other pods within
> the Kubernetes cluster. 
> ```

Please remove trailing space.
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 82 at r4](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUrRBH-2Bvdr4upZPBP:-MUrRBH-2Bvdr4upZPBQ:bq9m6aj) ([raw file](https://github.com/oscarlab/graphene/blob/d9a1cdba1e8e609dd8ec589125bbd64e8a9efcbd/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L82)):*
> ```reStructuredText
>    :alt: Figure: TensorFlow Serving Flow
> 
> In this tutorial, we use three machines: `Machine A` is the trusted machine,
> ```

Sorry, I just noticed that you use a single backquote (`). This a Markdown syntax. In reST, you should use double-backquote (``). Please fix everywhere.

For more info, check this: https://stackoverflow.com/a/57302493/6325371.
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 591 at r4](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUrSEGF5dvwrAQahx8z:-MUrSEGF5dvwrAQahx9-:bjqp32k) ([raw file](https://github.com/oscarlab/graphene/blob/d9a1cdba1e8e609dd8ec589125bbd64e8a9efcbd/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L591)):*
> ```reStructuredText
> handshake, but it was designed for local (single-machine) test.
> We need to regenerate the ``server2-sha256.crt to support remote (two different
> machines) test. For `server2.key` and `test-ca-sha256.crt`, we keep the same.
> ```

`we keep the same` -> `we keep them as-is`
___
*[Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst, line 577 at r2](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUh28ooBMcKB-aL5eGJ:-MUrS5_0E1iDEhHrm-q-:b-xbv52p) ([raw file](https://github.com/oscarlab/graphene/blob/2f8fc3b429d11e6809668339e2ed49b2b3b4a9e2/Documentation/tutorials/tensorflow-serving-cluster/tf_serving_cluster_index.rst#L577)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sentence still doesn't make sense to me. I'm not sure what you want to say here.

In particular, this: `Also, in order for the in-Graphene secret provisioning library to verify secret
provisioning library that can verify the provisioning server` doesn't make sense to me
</blockquote></details>

OK, thanks, the new text is much better.


<!-- Sent from Reviewable.io -->

2021-03-04 12:45 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 329 at r5](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUxG76xES1om5V3l6hm:-MUxG76xES1om5V3l6hn:bp6p8a5) ([raw file](https://github.com/oscarlab/graphene/blob/762743e49e3cb64747e77c810d394ab5af41e4df/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L329)):*
> ```reStructuredText
> ``sgx.trusted_files.<name>`` specifies a file that will be verified and trusted
> by the SGX enclave. Note that the key string ``<name>`` may be an arbitrary legal
> string (but without `-` and other special symbols) and does not have to be the
> ```

You missed this place. Please add double backticks around `-`.
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 383 at r5](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUxGGOk7koRldcV6CUj:-MUxGGOk7koRldcV6CUk:b4mqc1y) ([raw file](https://github.com/oscarlab/graphene/blob/762743e49e3cb64747e77c810d394ab5af41e4df/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L383)):*
> ```reStructuredText
>       ......
> 
> *``Note``*: Please modify ``proxy_server`` in the script first according to your
> ```

Why do you need backticks around Note? Just `*Note*` is enough.


<!-- Sent from Reviewable.io -->

2021-03-05 08:54 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-03-05 08:54 UTC, dimakuv commented
Jenkins, test this please

2021-03-05 09:15 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MV0elZR1NJLr9r4z77F:-MV0elZR1NJLr9r4z77G:bt3d9zf) (no related file):*
Could you look at this problem with the `tensorflow-serving-cluster/index.rst` file, at line 202:
```
Warning, treated as error:
/home/jenkins/workspace/docs-18.04/Documentation/tutorials/tensorflow-serving-cluster/index.rst:202:Could not lex literal_block as "c". Highlighting skipped.
Makefile:22: recipe for target 'html' failed
```

---


<!-- Sent from Reviewable.io -->

2021-03-08 10:55 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-03-08 10:55 UTC, dimakuv commented
Jenkins, test this please

2021-03-17 05:08 UTC, RodgerZhu commented
@mkow Could you help to review the scripts for this tutorial?
 https://github.com/oscarlab/graphene-contrib/pull/1
Thanks!

2021-03-22 15:14 UTC, mkow requested changes
> Reviewed 2 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgtlhe2sh_DETQAnNB:-MWPRpTtB68mpK5N53Hf:bv20ge7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you change the image files from `.jpg` to `.svg`? SVG files are just nicer for web sites. Also, SVG files are more light-weight and can be re-used by others if they want to draw.
</blockquote></details>

Not done, that's not what Dmitrii meant - now you just pasted SVGs with inlined PNG blobs inside. What Dmitrii asked for was submitting proper, vectorized SVGs.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MWPRH9r0RSYTh_7BUyP:-MWPRH9sBWoqL9XR4xLf:b-mrq5j1) (no related file):*
Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can push-force if you choose the former.

---
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 10 at r7](https://reviewable.io/reviews/oscarlab/graphene/2194#-MWPSAiZ0lVRQwxqq8_6:-MWPSAi_8ulCk4cjdGCN:b-ih247q) ([raw file](https://github.com/oscarlab/graphene/blob/99fd5e861959ac9dabd1e5d115efb04d7bf5d486/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L10)):*
> ```reStructuredText
> Machine Learning) solution - `TensorFlow Serving <https://www.tensorflow.org/tfx/guide/serving>`__
> cluster with Intel SGX and Graphene.
> ```

If this is going to be included in our main documentation, then please included the following warning:

```reST
.. warning::

   This tutorial is an external contribution and wasn't reviewed as thoroughly as the rest of the
   code. Please be careful, especially in terms of security!
```


<!-- Sent from Reviewable.io -->

2021-03-30 18:44 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgtlhe2sh_DETQAnNB:-MX3Ri5k80V83YVJHsHK:b-j5fzr5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done, that's not what Dmitrii meant - now you just pasted SVGs with inlined PNG blobs inside. What Dmitrii asked for was submitting proper, vectorized SVGs.
</blockquote></details>

It's still the same, you just changed the PNG blob into a JPEG blob embedded inside SVG.

---


<!-- Sent from Reviewable.io -->

2021-04-06 02:23 UTC, RodgerZhu commented
@mkow Hi Mkow, I use Visio to draw the figures and save them as SVG format.
If this can't meet the requirement, could you give me some sgguestions?

2021-04-06 13:30 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgtlhe2sh_DETQAnNB:-MXbMWhp7JnIoTmme9UI:brlfb74) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's still the same, you just changed the PNG blob into a JPEG blob embedded inside SVG.
</blockquote></details>

@mkow Are you sure? (Or maybe this was already fixed.) Because I see that there are SVG elements (texts, boxes, etc) in the image files.

There are a couple embedded PNG images in the NGINX image-file, but this is expected (Kubernetes logo).

---


<!-- Sent from Reviewable.io -->

2021-04-12 02:38 UTC, RodgerZhu commented
Dear @mkow , could you please help to take a review ?

2021-04-12 07:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @RodgerZhu)



<!-- Sent from Reviewable.io -->

2021-05-07 09:46 UTC, m1ghtym0 commented
Hey folks,
cool demo!
@daniel-weisse created a Marblerun version of this: https://github.com/edgelesssys/graphene-tensorflow-demo
Would love to hear your feedback @monavij @dimakuv @mkow :-)
There was some issue with protected files and the trained model, @daniel-weisse is opening an Issue about that in a bit.
Thanks!

2021-05-08 01:48 UTC, mkow requested changes
> Reviewed 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @RodgerZhu)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2194#-MUgtlhe2sh_DETQAnNB:-M_8Woca4LeS6GU_QTuX:b-honyf3) (no related file):*
> @mkow Are you sure? (Or maybe this was already fixed.) Because I see that there are SVG elements (texts, boxes, etc) in the image files.

There was a push after my comment.

Now the SVG looks fine (i.e. it's actually vectorized)

---
___
*[Documentation/tutorials/tensorflow-serving-cluster/img/Graphene_TF_Serving_Flow.svg, line 74 at r8](https://reviewable.io/reviews/oscarlab/graphene/2194#-M_8ZWacB4QOL2I4VTAJ:-M_8ZWacB4QOL2I4VTAK:b-lhhkd3) ([raw file](https://github.com/oscarlab/graphene/blob/343014bb36e45c36d854013ae7c9d45607d4af7b/Documentation/tutorials/tensorflow-serving-cluster/img/Graphene_TF_Serving_Flow.svg#L74)):*
> ```
> Intel@
> ```

I guess this was supposed to be the copyright sign? ditto for this whole file
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 17 at r8](https://reviewable.io/reviews/oscarlab/graphene/2194#-M_8dnIbC6n3gKuFZvco:-M_8dnIbC6n3gKuFZvcp:b-kwqc23) ([raw file](https://github.com/oscarlab/graphene/blob/343014bb36e45c36d854013ae7c9d45607d4af7b/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L17)):*
> ```reStructuredText
> 
> Introduction
> ------------
> ```

Seems that huge part of this section is just copypasted https://www.redhat.com/en/topics/containers/what-is-kubernetes (with some minor modifications).
You can't just copy-paste someone else's work and commit as yours...


<!-- Sent from Reviewable.io -->

2021-05-10 09:49 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @RodgerZhu)

___
*[Documentation/tutorials/tensorflow-serving-cluster/img/Graphene_TF_Serving_Flow.svg, line 74 at r8](https://reviewable.io/reviews/oscarlab/graphene/2194#-M_8ZWacB4QOL2I4VTAJ:-M_KfCnA3I77BVdCLhGY:b-ee7a1w) ([raw file](https://github.com/oscarlab/graphene/blob/343014bb36e45c36d854013ae7c9d45607d4af7b/Documentation/tutorials/tensorflow-serving-cluster/img/Graphene_TF_Serving_Flow.svg#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Intel@
> ```

I guess this was supposed to be the copyright sign? ditto for this whole file
</blockquote></details>

Good catch from Michal. @rodgerzhu Please remove the `@` sign. You don't use the copyright sign anywhere in this tutorial, so let's remove it from here as well.
___
*[Documentation/tutorials/tensorflow-serving-cluster/img/Graphene_TF_Serving_Flow.svg, line 78 at r9](https://reviewable.io/reviews/oscarlab/graphene/2194#-M_KfP56A8GrBRV2S-hj:-M_KfP56A8GrBRV2S-hk:btgjbd4) ([raw file](https://github.com/oscarlab/graphene/blob/5ec9fdd089c0f5a3d43f58737a47fdcdef3320d8/Documentation/tutorials/tensorflow-serving-cluster/img/Graphene_TF_Serving_Flow.svg#L78)):*
> ```SVG
> 							 L7.9 236.51 A7.90003 7.90003 -180 0 0 0 244.41 L0 287.86 A7.90003 7.90003 -180 0 0 7.9 295.76 Z"
> 						class="st1"/>
> 				<text x="25.83" y="251.13" class="st2">Intel@ <tspan x="14.64" dy="1.2em" class="st3">Provisioning </tspan><tspan
> ```

Please also remove the `@` sign from here.
___
*[Documentation/tutorials/tensorflow-serving-cluster/index.rst, line 25 at r9](https://reviewable.io/reviews/oscarlab/graphene/2194#-M_KeaNg6zXC2I-6Y72y:-M_KeaNh4JB39ScrP-R7:b-5uwm2) ([raw file](https://github.com/oscarlab/graphene/blob/5ec9fdd089c0f5a3d43f58737a47fdcdef3320d8/Documentation/tutorials/tensorflow-serving-cluster/index.rst#L25)):*
> ```reStructuredText
> and integrate various security ingredients such as the load balancer (Nginx
> Ingress) and elastic scheduler (Kubernetes). Please refer to `What is Kubernetes <https://www.redhat.com/en/topics/containers/what-is-kubernetes>`__
> for more details.
> ```

These last three lines are incorrectly wrapped. Please re-wrap them according to our symbol limit of 80 chars. Like this:
```
Ingress) and elastic scheduler (Kubernetes). Please refer to `What is Kubernetes
<https://www.redhat.com/en/topics/containers/what-is-kubernetes>`__ for more
details.
```


<!-- Sent from Reviewable.io -->

2021-05-11 06:32 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2194)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @RodgerZhu)



<!-- Sent from Reviewable.io -->

2021-07-01 23:15 UTC, mkow commented
This was migrated to the contrib repo (see https://github.com/oscarlab/graphene-contrib/pull/4), closing.

2021-07-01 23:15 UTC, closed without merging