[GSC] Ignore allowed|trusted|protected files specified in user manifest
oscarlab/graphene pull request #2204
Opened 2021-03-03 11:23 UTC by dimakuv

## Description of the changes 

GSC concatenates the user-provided manifest with the auto-generated manifest. Previously, the auto-generated manifest would include even those files which were already defined in the user-provided manifest. This led to runtime errors (Graphene complains about redefined manifest entries) and didn't allow to white-list files like `/etc/resolv.conf`.

This PR instructs GSC to skip already-defined files (using a heuristic that such manifest entries start with the strings "sgx.allowed_files", "sgx.trusted_files", "sgx.protected_files").

Must be rebased after https://github.com/oscarlab/graphene/pull/2203 is merged. First commit of this PR is from there.

## How to test this PR? 

GSC. I added some lines to the Python3 example. You can check the final manifest manually by inspecting the resulting `gsc-ubuntu18.04-python3`  container.

2021-03-22 13:52 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2204)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2204#-MWPBkPi5bYLeJ58xYOC:-MWPBkPj9Y7ghsD-uqqy:b-c58fzj) (no related file):*
#2203 was merged, could you rebase?
Btw. maybe it would be a good idea to first change the trusted files into an array? This should simplify this PR, or maybe even make it redundant?

---


<!-- Sent from Reviewable.io -->

2021-03-24 12:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2204)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2204#-MWPBkPi5bYLeJ58xYOC:-MWZGlmQEOjNYOXqW11D:b-r6n0dr) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

#2203 was merged, could you rebase?
Btw. maybe it would be a good idea to first change the trusted files into an array? This should simplify this PR, or maybe even make it redundant?
</blockquote></details>

Done, rebased.

I would prefer to merge this PR first, without the "trusted files as TOML array" change. I'm pretty sure that change would end up in ~5 additional PRs and a couple weeks of effort :)

---


<!-- Sent from Reviewable.io -->

2021-03-24 13:18 UTC, mkow requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2204)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2204#-MWPBkPi5bYLeJ58xYOC:-MWZNYW46zETjs1TR_y5:b2nhll9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, rebased.

I would prefer to merge this PR first, without the "trusted files as TOML array" change. I'm pretty sure that change would end up in ~5 additional PRs and a couple weeks of effort :)
</blockquote></details>

Ok.

---
___
*[Tools/gsc/finalize_manifest.py, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene/2204#-MWZN15v0CjjVCQzpK4S:-MWZN15w4H5OIqSk7jPx:bd881xo) ([raw file](https://github.com/oscarlab/graphene/blob/5734707a4c1a78c74e2a72f265d3fe2ad5a416e0/Tools/gsc/finalize_manifest.py#L29)):*
> ```Python
>         line = line.strip()
>         if line.startswith((f'sgx.trusted_files', f'sgx.allowed_files', f'sgx.protected_files')):
>             if line.count("=") != 1:
> ```

`"="` -> `'='`
___
*[Tools/gsc/finalize_manifest.py, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2204#-MWZNC2G2HZw3Os6zRuP:-MWZNC2G2HZw3Os6zRuQ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/5734707a4c1a78c74e2a72f265d3fe2ad5a416e0/Tools/gsc/finalize_manifest.py#L32)):*
> ```Python
>                 # TODO: process manifest lines like `sgx.allowed_files.a = "file:=weird=file="`
>                 continue
>             filename = line.split("=")[1].strip()
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-03-24 14:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2204)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Tools/gsc/finalize_manifest.py, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene/2204#-MWZN15v0CjjVCQzpK4S:-MWZPIGd0QxwzH-hbM27:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5734707a4c1a78c74e2a72f265d3fe2ad5a416e0/Tools/gsc/finalize_manifest.py#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`"="` -> `'='`
</blockquote></details>

Done.
___
*[Tools/gsc/finalize_manifest.py, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2204#-MWZNC2G2HZw3Os6zRuP:-MWZPIZCEgTWEG8A800C:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5734707a4c1a78c74e2a72f265d3fe2ad5a416e0/Tools/gsc/finalize_manifest.py#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-24 15:04 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2204)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-24 15:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2204)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-24 16:04 UTC, merged