[Pal/{lib,Linux-SGX}] Add seqlocks and use them in SGX's _DkSystemTimeQuery()
oscarlab/graphene pull request #2222
Opened 2021-03-09 11:54 UTC by dimakuv

## Description of the changes 

For gettime emulation, Linux-SGX PAL uses RDTSC instruction if its execution is allowed inside the SGX enclave and if the CPU supports Invariant TSC. Previously, this code path used a global spinlock to synchronize read/write accesses to shared-time-variables (threads very frequently read these shared variables and very rarely update them).

Using a spinlock led to significant performance overhead due to contention between readers (on some systems, around 140 simultaneous reader threads). This commit introduces seqlocks to allow fast lock-free readers, and replaces spinlock with a seqlock in `_DkSystemTimeQuery()`.

## How to test this PR? 

New test to sanity-check `gettimeofday()` emulation on Linux-SGX was added to LibOS regression suite.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2222)

2021-03-09 12:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: 0 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[Pal/include/lib/seqlock.h, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVLu2D8-BkZMHgt50vJ:-MVLu2D8-BkZMHgt50vK:behkeyk) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L59)):*
> ```objc
>         CPU_RELAX();
>     }
>     RMB();
> ```

FYI: Interestingly, https://elixir.bootlin.com/linux/v3.19.8/source/include/linux/seqlock.h (Linux 3.19) didn't have this `RMB` but https://elixir.bootlin.com/linux/v5.11.4/source/include/linux/seqlock.h has it. So I added too.


<!-- Sent from Reviewable.io -->

2021-03-09 14:16 UTC, boryspoplawski requested changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

___
*[LibOS/shim/test/regression/gettimeofday.c, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVM-sgD8FTtKVcUocH6:-MVM-sgD8FTtKVcUocH7:b3vkhm6) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/LibOS/shim/test/regression/gettimeofday.c#L14)):*
> ```C
> 
> struct timeval base_tv;
> struct timeval tv[THREAD_NUM];
> ```

Why this is global array? You only use one entry at a time and only as a local variable.
___
*[LibOS/shim/test/regression/gettimeofday.c, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVM-HP82j7T1Hj5YSB8:-MVM-HP96o0yHkQrHGiK:b-bmej7i) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/LibOS/shim/test/regression/gettimeofday.c#L25)):*
> ```C
>             err(1, "thread gettimeofday");
> 
>         if (tv[idx].tv_sec < base_tv.tv_sec || tv[idx].tv_sec - base_tv.tv_sec > 20)
> ```

Please introduce a define for this constant value.
___
*[LibOS/shim/test/regression/gettimeofday.c, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVM-fhuABm5fqcywMV6:-MVM-fhuABm5fqcywMV7:bov84zg) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/LibOS/shim/test/regression/gettimeofday.c#L57)):*
> ```C
>                                                           : base_tv.tv_usec - end_tv.tv_usec;
>     printf("Finish time: %lu sec, %lu usec (passed: %lu sec, %lu usec)\n", end_tv.tv_sec,
>            end_tv.tv_usec, end_tv.tv_sec - base_tv.tv_sec, usec_diff);
> ```

We should subtract 1 from 3rd param if `end_tv.tv_usec < base_tv.tv_usec`.
___
*[Pal/include/lib/seqlock.h, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVLq0tk2QGWQToV-kpT:-MVM07G38eR10VsONo10:b-8ef97z) ([raw file](https://github.com/oscarlab/graphene/blob/ec42fcf811716c0f35beb3abca3c85b9ae249a7c/Pal/include/lib/seqlock.h#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski I haven't added the debugging stuff that you had in spinlocks. Do we need those?
</blockquote></details>

Nah, we can add them later if needed.
___
*[Pal/include/lib/seqlock.h, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVLq7jGCU1qE2cE5K3S:-MVM9NeM2RguDqGFFLO3:bo7q3bm) ([raw file](https://github.com/oscarlab/graphene/blob/ec42fcf811716c0f35beb3abca3c85b9ae249a7c/Pal/include/lib/seqlock.h#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski @yamahata I used `RMB` and `WMB` (read and write memory barriers) macros instead of relying on GCC atomics' memory ordering. I wasn't sure whether I can and should use `__ATOMIC_*` keywords instead of the explicit RMB/WMB. Please advise.
</blockquote></details>

`__ATOMIC_RELAXED` gives no synchronization, so we need these barrier.
I think we could use `ACQUIRE/RELEASE` in other places, to have the same (or actually stronger) guarantees as now, but this (`seqretry`) case is special and we cannot use any of those. In such case I prefer to have barriers everywhere.
___
*[Pal/include/lib/seqlock.h, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVLu2D8-BkZMHgt50vJ:-MVM275L3eslmuU5_svV:b-xs73uw) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Interestingly, https://elixir.bootlin.com/linux/v3.19.8/source/include/linux/seqlock.h (Linux 3.19) didn't have this `RMB` but https://elixir.bootlin.com/linux/v5.11.4/source/include/linux/seqlock.h has it. So I added too.
</blockquote></details>

Both versions you've linked have the barrier (and it's essential for this to work correctly).
___
*[Pal/include/lib/seqlock.h, line 74 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMHce16V26gE6pWWWX:-MVMHce16V26gE6pWWWY:bg064w7) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L74)):*
> ```objc
>  * \brief Start a writer-side critical section (acquires spinlock).
>  */
> static inline void write_seqlock(seqlock_t* sl) {
> ```

Could you rename this to `write_seqbegin` to match `read` version?
___
*[Pal/include/lib/seqlock.h, line 76 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMEviZ6X0lh5lgcu89:-MVMEviZ6X0lh5lgcu8A:b-8d2cp5) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L76)):*
> ```objc
> static inline void write_seqlock(seqlock_t* sl) {
>     spinlock_lock(&sl->lock);
>     __atomic_add_fetch(&sl->sequence, 1, __ATOMIC_RELAXED);
> ```

Fun fact: kernel uses a plain `++` here (https://elixir.bootlin.com/linux/v5.11.4/source/include/linux/seqlock.h#L473) which I believe is incorrect. Nothing stops the compiler from doing something like:
```
x = load(seq);
*seq = 5;
x += 1;
*seq = x;
WMB();
```
and in such case it's clear that a reader can see an invalid value. As far as this case is unrealistic, there could be some others like: stores and reads get shredded into byte-by-byte read/write.
Otoh kernel uses `READ_ONCE` in readers, which might be enough (I think it prevents shredding)...
___
*[Pal/include/lib/seqlock.h, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMHhN44kLk1N2cvelD:-MVMHhN5AIYCq5DIkzlw:blhx4oh) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L83)):*
> ```objc
>  * \brief End a writer-side critical section (releases spinlock).
>  */
> static inline void write_sequnlock(seqlock_t* sl) {
> ```

ditto (name)
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 54 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMJV5J5l9Vfwq3glgj:-MVMJV5J5l9Vfwq3glgk:b-p2j61c) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L54)):*
> ```C
>             return -PAL_ERROR_DENIED;
> 
>         *out_usec = usec;
> ```

Do we need the additional parameter? Why not just pass `out_usec` to `ocall_gettime`?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMJQ5_3HZhEZdvZ8vB:-MVMJQ5_3HZhEZdvZ8vC:bw4slw6) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L58)):*
> ```C
>     }
> 
>     uint32_t seq;
> ```

Please move this inside `do {} while`.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 65 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMKJiL8bRMGDP9YmRk:-MVMKJiL8bRMGDP9YmRl:b-sb0oik) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L65)):*
> ```C
>              * careful with integer overflow during calculations) */
>             uint64_t tsc_diff = get_tsc() - g_start_tsc;
>             if (tsc_diff < INT64_MAX / 1000000) {
> ```

Shouldn't this be `UINT64_MAX`?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 66 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMK1lC7jZN7KVf6Zz_:-MVMK1lC7jZN7KVf6Zza:b-5xq8qk) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L66)):*
> ```C
>             uint64_t tsc_diff = get_tsc() - g_start_tsc;
>             if (tsc_diff < INT64_MAX / 1000000) {
>  [...]

2021-03-09 19:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/gettimeofday.c, line 14 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVM-sgD8FTtKVcUocH6:-MVN83yp1G9f6d2EKkh6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/LibOS/shim/test/regression/gettimeofday.c#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is global array? You only use one entry at a time and only as a local variable.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/gettimeofday.c, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVM-HP82j7T1Hj5YSB8:-MVN8NV46R43PgGTQgIE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/LibOS/shim/test/regression/gettimeofday.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please introduce a define for this constant value.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/gettimeofday.c, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVM-fhuABm5fqcywMV6:-MVNFWyNE7IkV9pFn2_M:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/LibOS/shim/test/regression/gettimeofday.c#L57)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should subtract 1 from 3rd param if `end_tv.tv_usec < base_tv.tv_usec`.
</blockquote></details>

Done.
___
*[Pal/include/lib/seqlock.h, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVLq7jGCU1qE2cE5K3S:-MVNS5etBlX3Kmk89cmx:bnjom5k) ([raw file](https://github.com/oscarlab/graphene/blob/ec42fcf811716c0f35beb3abca3c85b9ae249a7c/Pal/include/lib/seqlock.h#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`__ATOMIC_RELAXED` gives no synchronization, so we need these barrier.
I think we could use `ACQUIRE/RELEASE` in other places, to have the same (or actually stronger) guarantees as now, but this (`seqretry`) case is special and we cannot use any of those. In such case I prefer to have barriers everywhere.
</blockquote></details>

Ok, then I hope I added all the barriers correctly?
___
*[Pal/include/lib/seqlock.h, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVLu2D8-BkZMHgt50vJ:-MVNRzBwEVdKe5hs56rt:b7dv4i) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Both versions you've linked have the barrier (and it's essential for this to work correctly).
</blockquote></details>

True, my eyes deceived me on 3.19.
___
*[Pal/include/lib/seqlock.h, line 74 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMHce16V26gE6pWWWX:-MVNSMbI8r1CK3R0ptMj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L74)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you rename this to `write_seqbegin` to match `read` version?
</blockquote></details>

Done.
___
*[Pal/include/lib/seqlock.h, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMHhN44kLk1N2cvelD:-MVNScaX2UjtlzMsSMtd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/include/lib/seqlock.h#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (name)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 54 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMJV5J5l9Vfwq3glgj:-MVNGhM30AflxacDjS3R:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we need the additional parameter? Why not just pass `out_usec` to `ocall_gettime`?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMJQ5_3HZhEZdvZ8vB:-MVNJvxp50jJS-HI-i7o:b-fyg9q7) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move this inside `do {} while`.
</blockquote></details>

This doesn't work?
```
db_misc.c: In function ‘_DkSystemTimeQuery’:
db_misc.c:54:18: error: unused variable ‘seq’ [-Werror=unused-variable]
db_misc.c:70:41: error: ‘seq’ undeclared (first use in this function); did you mean ‘usec’?
```

Keeping as-is for now, maybe I'm being stupid but I don't think `seq` will still exist in `while (<condition>)`.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 65 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMKJiL8bRMGDP9YmRk:-MVNLNdI5nLDFVy-nP2I:bwlq46u) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L65)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't this be `UINT64_MAX`?
</blockquote></details>

Done. I guess at some point we had `int64_t` types here...
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 66 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMK1lC7jZN7KVf6Zz_:-MVNQsCv46TOxDcjf4Ls:b-actlme) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we need `add_overflow` check here?
</blockquote></details>

Done. I really don't know what to do if time overflows and wraps around... For now, I'm doing a post-check (since we have `uint`) and return an OVERFLOW error.


<!-- Sent from Reviewable.io -->

2021-03-09 20:57 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @yamahata, and @ying2liu)

___
*[Pal/include/lib/seqlock.h, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVLq7jGCU1qE2cE5K3S:-MVNh7Me3v59SeEMPbXI:b-de04pm) ([raw file](https://github.com/oscarlab/graphene/blob/ec42fcf811716c0f35beb3abca3c85b9ae249a7c/Pal/include/lib/seqlock.h#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, then I hope I added all the barriers correctly?
</blockquote></details>

Hopefully :)
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVMJQ5_3HZhEZdvZ8vB:-MVNk57A9BBNdOEnDUwB:bx73zw0) ([raw file](https://github.com/oscarlab/graphene/blob/7a77aa7a431bf589733a2323e3b29dd862b8842c/Pal/src/host/Linux-SGX/db_misc.c#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't work?
```
db_misc.c: In function ‘_DkSystemTimeQuery’:
db_misc.c:54:18: error: unused variable ‘seq’ [-Werror=unused-variable]
db_misc.c:70:41: error: ‘seq’ undeclared (first use in this function); did you mean ‘usec’?
```

Keeping as-is for now, maybe I'm being stupid but I don't think `seq` will still exist in `while (<condition>)`.
</blockquote></details>

Sorry, apparently it does not work.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 66 at r3](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVNhkMeBE_HeAbBOFGf:-MVNhkMeBE_HeAbBOFGg:b-q5xbnx) ([raw file](https://github.com/oscarlab/graphene/blob/95499a4edd4fb180555bfd989a9eb119ca67cd48/Pal/src/host/Linux-SGX/db_misc.c#L66)):*
> ```C
>                      * TSC/usec pair (time drift is contained), use the RDTSC-calculated time */
>                     usec = g_start_usec + diff_usec;
>                     if (usec < g_start_usec)
> ```

This case is tricky, but since we are inside seqlock, the value can be random garbage, unless we get out and confirm we passed the critical section successfully. Here we need to save the value, get out of the loop and only then check if it is correct (does not overflow).
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 73 at r3](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVNlkQVBl1BwGp3f-yI:-MVNlkQVBl1BwGp3f-yJ:be7co5y) ([raw file](https://github.com/oscarlab/graphene/blob/95499a4edd4fb180555bfd989a9eb119ca67cd48/Pal/src/host/Linux-SGX/db_misc.c#L73)):*
> ```C
>     } while (read_seqretry(&g_tsc_lock, seq));
> 
>     if (usec) {
> ```

If one loop fails (due to parallel writer), and the second due to int overflow, we will still exit successfully here.


<!-- Sent from Reviewable.io -->

2021-03-10 08:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @yamahata, and @ying2liu)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 66 at r3](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVNhkMeBE_HeAbBOFGf:-MVQ97FxBlLGRqefhtB4:b-1m9zjr) ([raw file](https://github.com/oscarlab/graphene/blob/95499a4edd4fb180555bfd989a9eb119ca67cd48/Pal/src/host/Linux-SGX/db_misc.c#L66)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This case is tricky, but since we are inside seqlock, the value can be random garbage, unless we get out and confirm we passed the critical section successfully. Here we need to save the value, get out of the loop and only then check if it is correct (does not overflow).
</blockquote></details>

Done. Good catch. I decided to move all these calculations outside of the critical section -- we only need to read a consistent set of global vars in the critical section, and the rest can be done outside of it.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 73 at r3](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVNlkQVBl1BwGp3f-yI:-MVQ9NHVCZucN9AbhOF4:br2il1u) ([raw file](https://github.com/oscarlab/graphene/blob/95499a4edd4fb180555bfd989a9eb119ca67cd48/Pal/src/host/Linux-SGX/db_misc.c#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If one loop fails (due to parallel writer), and the second due to int overflow, we will still exit successfully here.
</blockquote></details>

I don't understand your scenario. Are you meaning two parallel threads?


<!-- Sent from Reviewable.io -->

2021-03-10 16:04 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: 5 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @yamahata, and @ying2liu)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 58 at r4](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVRqTXyD_KMoXmPGd0l:-MVRqTXyD_KMoXmPGd0m:b-xqi8gg) ([raw file](https://github.com/oscarlab/graphene/blob/44e965224f888ee1d8fc98f3559c60168d8df60d/Pal/src/host/Linux-SGX/db_misc.c#L58)):*
> ```
>         start_tsc  = READ_ONCE(g_start_tsc);
>         start_usec = READ_ONCE(g_start_usec);
> ```

Because The integrity is guaranteed by seqlock, READ_ONCE is overkill.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 68 at r4](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVRqeDT94TAcOi0oUTh:-MVRqeDT94TAcOi0oUTi:blbcsfq) ([raw file](https://github.com/oscarlab/graphene/blob/44e965224f888ee1d8fc98f3559c60168d8df60d/Pal/src/host/Linux-SGX/db_misc.c#L68)):*
> ```
>         if (diff_tsc < UINT64_MAX / 1000000) {
>             uint64_t diff_usec = diff_tsc * 1000000 / g_tsc_hz;
>             if (diff_usec < TSC_REFINE_INIT_TIMEOUT_USECS) {
> ```

These two if clause can be done in single if clause without UINT64_MAX.
But it's a matter of preference. Non-blocking


<!-- Sent from Reviewable.io -->

2021-03-10 16:04 UTC, yamahata reviewed
> Reviewed 3 of 6 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: 5 of 6 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @yamahata, and @ying2liu)



<!-- Sent from Reviewable.io -->

2021-03-10 16:20 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @yamahata, and @ying2liu)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 73 at r3](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVNlkQVBl1BwGp3f-yI:-MVRu4QYCQgOrun93SCu:b-fh64py) ([raw file](https://github.com/oscarlab/graphene/blob/95499a4edd4fb180555bfd989a9eb119ca67cd48/Pal/src/host/Linux-SGX/db_misc.c#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand your scenario. Are you meaning two parallel threads?
</blockquote></details>

No, I meant first loop iteration vs second iteration. 2nd could fail this `if (diff_tsc < UINT64_MAX / 1000000)`.
Anyway, with the new version the issue is not present anymore.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 58 at r4](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVRqTXyD_KMoXmPGd0l:-MVRtE-NDXnuqxDfAW04:b-ocirl) ([raw file](https://github.com/oscarlab/graphene/blob/44e965224f888ee1d8fc98f3559c60168d8df60d/Pal/src/host/Linux-SGX/db_misc.c#L58)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>         start_tsc  = READ_ONCE(g_start_tsc);
>         start_usec = READ_ONCE(g_start_usec);
> ```

Because The integrity is guaranteed by seqlock, READ_ONCE is overkill.

</blockquote></details>

+1 we do not need them. Any reason why you added them now?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 68 at r4](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVRqeDT94TAcOi0oUTh:-MVRupre2Gc-HK85AoCM:b-rngmim) ([raw file](https://github.com/oscarlab/graphene/blob/44e965224f888ee1d8fc98f3559c60168d8df60d/Pal/src/host/Linux-SGX/db_misc.c#L68)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
>         if (diff_tsc < UINT64_MAX / 1000000) {
>             uint64_t diff_usec = diff_tsc * 1000000 / g_tsc_hz;
>             if (diff_usec < TSC_REFINE_INIT_TIMEOUT_USECS) {
> ```

These two if clause can be done in single if clause without UINT64_MAX.
But it's a matter of preference. Non-blocking
</blockquote></details>

Hmm, how exactly would we do that? How to make sure we do not overflow?
We could use `__builtin_mul_overflow`, but that's different approach entirely.


<!-- Sent from Reviewable.io -->

2021-03-10 16:25 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @yamahata, and @ying2liu)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 68 at r4](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVRqeDT94TAcOi0oUTh:-MVRx3Tg6mMnU9EMIAAR:b-ef6ol) ([raw file](https://github.com/oscarlab/graphene/blob/44e965224f888ee1d8fc98f3559c60168d8df60d/Pal/src/host/Linux-SGX/db_misc.c#L68)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, how exactly would we do that? How to make sure we do not overflow?
We could use `__builtin_mul_overflow`, but that's different approach entirely.
</blockquote></details>

builtin is ugly. Let's keep this as is. I scratch my comment here.


<!-- Sent from Reviewable.io -->

2021-03-10 16:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 58 at r4](https://reviewable.io/reviews/oscarlab/graphene/2222#-MVRqTXyD_KMoXmPGd0l:-MVRxqQg7y2upFOgbjqa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/44e965224f888ee1d8fc98f3559c60168d8df60d/Pal/src/host/Linux-SGX/db_misc.c#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I wanted to make it explicit, but yes, no reason other than "in your face readability". Will change to normal assignment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-10 20:53 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-10 21:16 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-03-10 21:24 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2222)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-11 07:19 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug please (Jenkins log was removed due to other jobs in the meantime, don't know the reason for failing)

2021-03-11 08:00 UTC, merged