[Examples][Docs] Update lighttpd example and doc to utilize tmpfs feature
oscarlab/graphene pull request #2223
Opened 2021-03-10 07:54 UTC by llly

## Description of the changes 
tmpfs mount point was added In #2124, followed by this one to utilize it.

Descriptions and usage are added to `FS mount points` section of `manifest-syntax` page.

`deflate.cache-dir` conf is introduced to `lighttpd` in 1.4.56.
[lighttpd wiki](https://redmine.lighttpd.net/projects/1/wiki/docs_moddeflate)
>Output compression reduces the network load and can improve the overall throughput of the webserver. All major http-clients support compression by announcing it in the Accept-Encoding header. 
>deflate.cache-dir (since 1.4.56) is the location under which to store cache of compressed files. Cleaning the cache is left to the user.

Cache can contain sensitive data. So tmpfs can be used for it.
`curl --compressed' explicitly requests a compressed response using one of the algorithms curl supports. It triggers lighttpd cache while `wget` doesn't.

2021-03-10 08:53 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2223)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[Documentation/manifest-syntax.rst, line 266 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVQGu3Z9RQPWtMwBHEt:-MVQGu3Z9RQPWtMwBHEu:bmtms7j) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Documentation/manifest-syntax.rst#L266)):*
> ```reStructuredText
> ::
> 
>     fs.mount.[identifier].type = "[chroot|tmpfs|...]"
> ```

Can you remove `|...`? We currently have only two options: chroot and tmpfs.
___
*[Documentation/manifest-syntax.rst, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVQGmt89BM3unI0IM1u:-MVQGmt9235Scr2R5ZJV:bepngac) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Documentation/manifest-syntax.rst#L280)):*
> ```reStructuredText
> 
> **Note**: The tmpfs files are *not* cloned during fork/clone and cannot be
> synchronized between processes.
> ```

Let's replace this text with this:
```
Graphene currently supports two types of mount points:

* ``chroot``: Host-backed files. All host files and sub-directories found under ``[URI]`` are forwarded
  to a Graphene instance and placed under ``[PATH]``. For example, with a host-level path specified as
  ``fs.mount.lib.uri = "file:graphene/Runtime/"`` and forwarded to Graphene via ``fs.mount.lib.path = "/lib"``,
  a host-level file ``graphene/Runtime/libc.so.6`` is visible to graphenized application as ``/lib/libc.so.6``.
  This concept is similar to FreeBSD's chroot and to Docker's named volumes. Files under ``chroot`` mount
  points support mmap and fork/clone.

* ``tmpfs``: Temporary in-memory-only files. These files are *not* backed by host-level files. The tmpfs files
  are created under ``[PATH]`` (this path is empty on Graphene instance startup) and are destroyed when a
  Graphene instance terminates. The ``[URI]`` parameter is always ignored. ``tmpfs`` is especially useful
  in trusted environments (like Intel SGX) for securely storing temporary files. This concept is similar to Linux's
  tmpfs. Files under ``tmpfs`` mount points currently do *not* support mmap and fork/clone.
```

Please also re-wrap this text to 80 chars.
___
*[Examples/lighttpd/lighttpd.manifest.template, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVQGJLc-iL-1tJF-YCM:-MVQGJLc-iL-1tJF-YCN:burdvni) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Examples/lighttpd/lighttpd.manifest.template#L52)):*
> ```
> fs.mount.var_tmp.type = "tmpfs"
> fs.mount.var_tmp.path = "/var/tmp"
> fs.mount.var_tmp.uri = "file:/var/tmp"
> ```

Please use `file:dummy-unused-by-tmpfs-uri` for uri


<!-- Sent from Reviewable.io -->

2021-03-11 06:50 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2223)* status: 3 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 266 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVQGu3Z9RQPWtMwBHEt:-MVV2Bpv5tXG7wGXyfNP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Documentation/manifest-syntax.rst#L266)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you remove `|...`? We currently have only two options: chroot and tmpfs.
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVQGmt89BM3unI0IM1u:-MVV2CmG3lLtVbqUwyBs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Documentation/manifest-syntax.rst#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's replace this text with this:
```
Graphene currently supports two types of mount points:

* ``chroot``: Host-backed files. All host files and sub-directories found under ``[URI]`` are forwarded
  to a Graphene instance and placed under ``[PATH]``. For example, with a host-level path specified as
  ``fs.mount.lib.uri = "file:graphene/Runtime/"`` and forwarded to Graphene via ``fs.mount.lib.path = "/lib"``,
  a host-level file ``graphene/Runtime/libc.so.6`` is visible to graphenized application as ``/lib/libc.so.6``.
  This concept is similar to FreeBSD's chroot and to Docker's named volumes. Files under ``chroot`` mount
  points support mmap and fork/clone.

* ``tmpfs``: Temporary in-memory-only files. These files are *not* backed by host-level files. The tmpfs files
  are created under ``[PATH]`` (this path is empty on Graphene instance startup) and are destroyed when a
  Graphene instance terminates. The ``[URI]`` parameter is always ignored. ``tmpfs`` is especially useful
  in trusted environments (like Intel SGX) for securely storing temporary files. This concept is similar to Linux's
  tmpfs. Files under ``tmpfs`` mount points currently do *not* support mmap and fork/clone.
```

Please also re-wrap this text to 80 chars.
</blockquote></details>

Done.
___
*[Examples/lighttpd/lighttpd.manifest.template, line 52 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVQGJLc-iL-1tJF-YCM:-MVV2DkUDGC8AeM1sKpH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Examples/lighttpd/lighttpd.manifest.template#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use `file:dummy-unused-by-tmpfs-uri` for uri
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-11 07:22 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2223)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @llly)

___
*[Documentation/manifest-syntax.rst, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVV9MhnAL4SzWy1qLf_:-MVV98Y6Bedr4Cq2mpEz:b-z68ox5) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Documentation/manifest-syntax.rst#L272)):*
> ```reStructuredText
> This syntax specifies how file systems are mounted inside the library OS. For
> dynamically linked binaries, usually at least one `chroot` mount point is
> required in the manifest (the mount point of the Glibc library).
> ```

Please keep this paragraph (`This syntax specifies...`). This one is useful.


<!-- Sent from Reviewable.io -->

2021-03-11 07:37 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2223)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVV9MhnAL4SzWy1qLf_:-MVVCgvU5ftJj9ycN_pg:b-qndnsr) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Documentation/manifest-syntax.rst#L272)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please keep this paragraph (`This syntax specifies...`). This one is useful.
</blockquote></details>

Done. Also reverted wrong change to `Start (current working) directory`


<!-- Sent from Reviewable.io -->

2021-03-11 08:04 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2223)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Documentation/manifest-syntax.rst, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/2223#-MVV9MhnAL4SzWy1qLf_:-MVVJ0DUEC6B30Y72Pcs:b-o4uvrv) ([raw file](https://github.com/oscarlab/graphene/blob/9f7a51b0e1db36436af49e8b641982eb7dc02e81/Documentation/manifest-syntax.rst#L272)):*
<details><summary><i>Previously, llly (Li Xun) wrote…</i></summary><blockquote>

Done. Also reverted wrong change to `Start (current working) directory`
</blockquote></details>

Oops, I didn't notice that wrong change before. Thanks for fixing it!


<!-- Sent from Reviewable.io -->

2021-03-11 08:04 UTC, dimakuv commented
Jenkins, test this please

2021-03-19 04:58 UTC, llly commented
Merged to #2124

2021-03-19 04:58 UTC, closed without merging