Stefanberger/readlink proc self exe
oscarlab/graphene pull request #2228
Opened 2021-03-11 13:50 UTC by stefanberger

This PR addresses issue #2185. The missing dentry is added to the shim_handle to make `/proc/self/exe` accessible. A test case is added for the bash.

## How to test this PR? 

Run the bash regression tests:
```
cd Examples/bash
make regression
```

Or run this 'manually':

```
~/graphene/Examples/bash$ ./pal_loader bash -c "readlink /proc/self/exe" 
WARNING: Using insecure argv source. Don't use this configuration in production!
/bin/readlink
```

2021-03-11 14:08 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWafnaBwTVqsuvoloT:-MVWafnaBwTVqsuvoloU:blht24o) (no related file):*
Thanks Stefan! Though I don't like the commit message, and I would prefer to merge the two commits in one (the second one is a trivial bash-manifest fix) and write something like:
```
[LibOS] Update exec handle's dentry on execve()

A simple test `readlink /proc/self/exe` is added to the Bash example.
```

But this can be done during final rebase.

---
___
*[LibOS/shim/src/sys/shim_exec.c, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWaYgUBzS7PNAcA9Eg:-MVWaYgUBzS7PNAcA9Eh:bfxx7la) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L217)):*
> ```C
>     exec->flags    = O_RDONLY;
>     exec->acc_mode = MAY_READ;
>     exec->dentry   = dent;
> ```

Looks legit but I summon @boryspoplawski here.


<!-- Sent from Reviewable.io -->

2021-03-11 16:11 UTC, yamahata approved these changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @stefanberger)



<!-- Sent from Reviewable.io -->

2021-03-11 18:11 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWafnaBwTVqsuvoloT:-MVXU-vMDkGaImI2YFxX:b32v57) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks Stefan! Though I don't like the commit message, and I would prefer to merge the two commits in one (the second one is a trivial bash-manifest fix) and write something like:
```
[LibOS] Update exec handle's dentry on execve()

A simple test `readlink /proc/self/exe` is added to the Bash example.
```

But this can be done during final rebase.
</blockquote></details>

+1

---
___
*[Examples/bash/manifest.template, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXTlddCS6Ikw9qBfmQ:-MVXTlddCS6Ikw9qBfmR:beumcp2) ([raw file](https://github.com/oscarlab/graphene/blob/2cfdd510dcd95fde4e6442eafaf9549dbc8f97b4/Examples/bash/manifest.template#L35)):*
> ```
> 
> fs.mount.lib2.type = "chroot"
> fs.mount.lib2.path = "$(ARCH_LIBDIR)"
> ```

What was in this entry on other distros, e.g. Ubuntu? Don't we need it there?
___
*[LibOS/shim/src/sys/shim_exec.c, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWaYgUBzS7PNAcA9Eg:-MVXSwD31_fZ_GbuJpji:b-e0ej9b) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks legit but I summon @boryspoplawski here.
</blockquote></details>

We definitely need `get_dentry(dent)` here.


<!-- Sent from Reviewable.io -->

2021-03-11 18:13 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @stefanberger)

___
*[LibOS/shim/src/sys/shim_exec.c, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWaYgUBzS7PNAcA9Eg:-MVXUR4296gHS0GDQsry:ba9c9zj) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L217)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We definitely need `get_dentry(dent)` here.
</blockquote></details>

No wait, we have some random `get_dentry` above... Let me dig into this


<!-- Sent from Reviewable.io -->

2021-03-11 18:16 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @dimakuv)

___
*[Examples/bash/manifest.template, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXTlddCS6Ikw9qBfmQ:-MVXV7ze4eADg5zKjyeK:b4hyue3) ([raw file](https://github.com/oscarlab/graphene/blob/2cfdd510dcd95fde4e6442eafaf9549dbc8f97b4/Examples/bash/manifest.template#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What was in this entry on other distros, e.g. Ubuntu? Don't we need it there?
</blockquote></details>

With this change I get this here now:

```
# Host-level libraries (e.g., /lib/x86_64-linux-gnu) required by Bash
fs.mount.lib64.type = "chroot"
fs.mount.lib64.path = "/lib/powerpc64le-linux-gnu"
fs.mount.lib64.uri = "file:/lib/powerpc64le-linux-gnu"
```

and the bash regression tests work.
___
*[LibOS/shim/src/sys/shim_exec.c, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWaYgUBzS7PNAcA9Eg:-MVXUumS6smyOOKbU12m:bd1mvjm) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L217)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No wait, we have some random `get_dentry` above... Let me dig into this
</blockquote></details>

That's the one that gets a reference for us already.


<!-- Sent from Reviewable.io -->

2021-03-11 18:26 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Examples/bash/manifest.template, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXTlddCS6Ikw9qBfmQ:-MVXX86-2J36FQMPfCvU:b-kmzu0g) ([raw file](https://github.com/oscarlab/graphene/blob/2cfdd510dcd95fde4e6442eafaf9549dbc8f97b4/Examples/bash/manifest.template#L35)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

With this change I get this here now:

```
# Host-level libraries (e.g., /lib/x86_64-linux-gnu) required by Bash
fs.mount.lib64.type = "chroot"
fs.mount.lib64.path = "/lib/powerpc64le-linux-gnu"
fs.mount.lib64.uri = "file:/lib/powerpc64le-linux-gnu"
```

and the bash regression tests work.
</blockquote></details>

Seems like `/lib64` was not needed at all - it only holds ld.so, but we build and provide that with Graphene
___
*[LibOS/shim/src/sys/shim_exec.c, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWaYgUBzS7PNAcA9Eg:-MVXWFb27nH7ScHEcRXl:b-9a7jpg) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L217)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

That's the one that gets a reference for us already.
</blockquote></details>

Oh boy, this code this ugly.
Yes it gets a reference but in wrong place (if an error occurs in between, we never free that up). Please just move it here.


<!-- Sent from Reviewable.io -->

2021-03-11 18:40 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

___
*[Examples/bash/manifest.template, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXTlddCS6Ikw9qBfmQ:-MVXY6Le9dnFy4h0115I:bgryvbs) ([raw file](https://github.com/oscarlab/graphene/blob/2cfdd510dcd95fde4e6442eafaf9549dbc8f97b4/Examples/bash/manifest.template#L35)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Seems like `/lib64` was not needed at all - it only holds ld.so, but we build and provide that with Graphene
</blockquote></details>

Maybe something doesn't work if one uses the bash in interactive mode. But the test cases are now passing on Ubuntu and Fedora at least.
___
*[LibOS/shim/src/sys/shim_exec.c, line 217 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWaYgUBzS7PNAcA9Eg:-MVX_npa5XUMhWCEAzn5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L217)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Oh boy, this code this ugly.
Yes it gets a reference but in wrong place (if an error occurs in between, we never free that up). Please just move it here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-11 19:22 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @stefanberger, and @yamahata)

___
*[Examples/bash/manifest.template, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXTlddCS6Ikw9qBfmQ:-MVXiVU3Cv2oqEdyLV4e:b-tg62dq) ([raw file](https://github.com/oscarlab/graphene/blob/2cfdd510dcd95fde4e6442eafaf9549dbc8f97b4/Examples/bash/manifest.template#L35)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Maybe something doesn't work if one uses the bash in interactive mode. But the test cases are now passing on Ubuntu and Fedora at least.
</blockquote></details>

It should be all good.
___
*[LibOS/shim/src/sys/shim_exec.c, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXicPi2fIAyB2ol_Kr:-MVXicPi2fIAyB2ol_Ks:bk7m1sh) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L192)):*
> ```C
>         ret = -EACCES;
>     err:
>         put_dentry(dent);
> ```

Don't remove this `put_dentry` it's needed here. `path_lookupat` returns this `dent` giving the ownership to the caller and this `put_dentry` is to give up that ownership.
Please revert all changes but moving the `get_dentry` from above.


<!-- Sent from Reviewable.io -->

2021-03-11 20:12 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/src/sys/shim_exec.c, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXicPi2fIAyB2ol_Kr:-MVXuUW_AClNK5a0zNQ7:bsxyqqv) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L192)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't remove this `put_dentry` it's needed here. `path_lookupat` returns this `dent` giving the ownership to the caller and this `put_dentry` is to give up that ownership.
Please revert all changes but moving the `get_dentry` from above.
</blockquote></details>

Ha, I thought this put_dentry() was the counter-part to the get_dentry() above it (that I just moved). It sounds like you are saying there were too many references taken before.


<!-- Sent from Reviewable.io -->

2021-03-11 20:12 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/src/sys/shim_exec.c, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVXicPi2fIAyB2ol_Kr:-MVXukeY77KXNc7YBF1c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e9acdeceb3bd7b7a6cf199cb12d9e10379d0dd51/LibOS/shim/src/sys/shim_exec.c#L192)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Ha, I thought this put_dentry() was the counter-part to the get_dentry() above it (that I just moved). It sounds like you are saying there were too many references taken before.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-11 21:11 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

___
*[LibOS/shim/src/sys/shim_exec.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY66iKEUcNHbAj1GmP:-MVY66iLCedYDs81P34l:b-r8fvy3) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L223)):*
> ```C
> 
>     if (qstrempty(&exec->uri)) {
>         put_handle(exec);
> ```

Uh, we are also missing `put_dentry(dent)` on all error paths here and below. Could you add them? Actually first verify I'm not wrong, I'm slowly getting lost in this...
cc @dimakuv @mkow 
___
*[LibOS/shim/src/sys/shim_exec.c, line 230 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY6XIE4_F6gZzop38F:-MVY6XIE4_F6gZzop38G:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L230)):*
> ```C
> 
>     if ((ret = check_elf_object(exec)) < 0 && ret != -EINVAL) {
>         put_handle(exec);
> ```

here
___
*[LibOS/shim/src/sys/shim_exec.c, line 290 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY6mTZ5IAg32q5Y0yC:-MVY6mTZ5IAg32q5Y0yD:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L290)):*
> ```C
>         if (!started) {
>             debug("file not recognized as ELF or shebang");
>             put_handle(exec);
> ```

here
___
*[LibOS/shim/src/sys/shim_exec.c, line 304 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY6nhM9WWhWTuTpwWR:-MVY6nhM9WWhWTuTpwWS:bb7hf91) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L304)):*
> ```C
>         file = first->arg;
>         LISTP_SPLICE(&new_shargs, &shargs, list, sharg);
>         put_handle(exec);
> ```

here
___
*[LibOS/shim/src/sys/shim_exec.c, line 307 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY72u75ikURdiZNHe8:-MVY72u75ikURdiZNHe9:bcqhsj2) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L307)):*
> ```C
>         goto reopen;
>     }
> ```

And we actually need a `put_dentry(dent)` here.


<!-- Sent from Reviewable.io -->

2021-03-11 22:47 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

___
*[LibOS/shim/src/sys/shim_exec.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY66iKEUcNHbAj1GmP:-MVYSqhe8j1AsdT7aQul:batxguz) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L223)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Uh, we are also missing `put_dentry(dent)` on all error paths here and below. Could you add them? Actually first verify I'm not wrong, I'm slowly getting lost in this...
cc @dimakuv @mkow 
</blockquote></details>

No we do NOT need to do this. Once we attach the entry to the shim_handle it will be dereferenced once the shim_handle references are 0: https://github.com/oscarlab/graphene/blob/7f186ba30aa211f4af6313ef3b8cc198de31ec4c/LibOS/shim/src/bookkeep/shim_handle.c#L468


<!-- Sent from Reviewable.io -->

2021-03-11 22:49 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

___
*[LibOS/shim/src/sys/shim_exec.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY66iKEUcNHbAj1GmP:-MVYTZ4LA_HVtjnxt_LS:b304u01) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L223)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

No we do NOT need to do this. Once we attach the entry to the shim_handle it will be dereferenced once the shim_handle references are 0: https://github.com/oscarlab/graphene/blob/7f186ba30aa211f4af6313ef3b8cc198de31ec4c/LibOS/shim/src/bookkeep/shim_handle.c#L468
</blockquote></details>

What I meant to say was : Once we attach the dentry to the shim_handle...


<!-- Sent from Reviewable.io -->

2021-03-11 23:07 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

___
*[LibOS/shim/src/sys/shim_exec.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY66iKEUcNHbAj1GmP:-MVYXhSzCDvqbSTQH6xs:b-jk6p8v) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L223)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

What I meant to say was : Once we attach the dentry to the shim_handle...
</blockquote></details>

But we have a `get_dentry` just before attaching, to account for that reference. We need to give up the reference we are using in this function, the one we got from `path_lookupat`.


<!-- Sent from Reviewable.io -->

2021-03-11 23:32 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

___
*[LibOS/shim/src/sys/shim_exec.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY66iKEUcNHbAj1GmP:-MVYaQvA23S9wb_Deq-w:bt2b7nz) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L223)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But we have a `get_dentry` just before attaching, to account for that reference. We need to give up the reference we are using in this function, the one we got from `path_lookupat`.
</blockquote></details>

Then maybe we shouldn't take an additional reference but leave it up to put_handle(exec) to drop the dentry. We call put_handle(exec)  on every failure exit and before the process_exit() at the very end.


<!-- Sent from Reviewable.io -->

2021-03-11 23:38 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @stefanberger)

___
*[LibOS/shim/src/sys/shim_exec.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY66iKEUcNHbAj1GmP:-MVYcmIM6dpj_5T8kxE4:bhgbmpf) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L223)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Then maybe we shouldn't take an additional reference but leave it up to put_handle(exec) to drop the dentry. We call put_handle(exec)  on every failure exit and before the process_exit() at the very end.
</blockquote></details>

But then if any of the functions we call here which takes `exec` as the argument changes the `dent` entry (and effectively drops this reference) and if this was the last reference (which probably is since we've just created it) we get an UAF.


<!-- Sent from Reviewable.io -->

2021-03-12 00:00 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: 2 of 3 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/sys/shim_exec.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY66iKEUcNHbAj1GmP:-MVYfydd7pVZ-0IdOGEt:b-wcdsql) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L223)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But then if any of the functions we call here which takes `exec` as the argument changes the `dent` entry (and effectively drops this reference) and if this was the last reference (which probably is since we've just created it) we get an UAF.
</blockquote></details>

Ok. Agreed.
___
*[LibOS/shim/src/sys/shim_exec.c, line 230 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY6XIE4_F6gZzop38F:-MVYidP_5xtYIq0tQR7S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L230)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

here
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_exec.c, line 290 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY6mTZ5IAg32q5Y0yC:-MVYifdbECDcAXYuMH04:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L290)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

here
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_exec.c, line 304 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY6nhM9WWhWTuTpwWR:-MVYihUN0M3VNx4du1eH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L304)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

here
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_exec.c, line 307 at r3](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVY72u75ikURdiZNHe8:-MVYigVS3q3JUOqEhHwA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1e444c953f2c54153e9c2d1ab568708b65f9d8a5/LibOS/shim/src/sys/shim_exec.c#L307)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

And we actually need a `put_dentry(dent)` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-12 00:03 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-03-12 00:04 UTC, boryspoplawski commented
Jenkins, test this please

2021-03-12 00:19 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVYmzRs1BPIt6LN4KoY:-MVYmzRt0UfyZW-XK6y_:b2potf3) (no related file):*
@stefanberger Could you rebase this to the newest master? CI fails due to some incompatibilities (most likely)...
You could also fix the commit message with that rebase

---


<!-- Sent from Reviewable.io -->

2021-03-12 00:57 UTC, llly commented
Also fixes #1927

2021-03-12 01:17 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVWafnaBwTVqsuvoloT:-MVZ-__i2WX-V7Sg9XeC:bb6un1j) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVYmzRs1BPIt6LN4KoY:-MVZ-azmDPM2fl-hJgrx:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@stefanberger Could you rebase this to the newest master? CI fails due to some incompatibilities (most likely)...
You could also fix the commit message with that rebase
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-03-12 01:19 UTC, boryspoplawski commented
Jenkins, test this please

2021-03-12 01:20 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-03-12 01:34 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @stefanberger)

___
*[Examples/bash/manifest.template, line 61 at r5](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVZ3DWQ2d8CqadZlAga:-MVZ3DWRCYpby_UZYDAB:b-v7mkv8) ([raw file](https://github.com/oscarlab/graphene/blob/3a890a510cfd9ffb1c9d3ceb46070db6bde4331a/Examples/bash/manifest.template#L61)):*
> ```
> sgx.trusted_files.rm = "file:$(EXECDIR)/rm"
> sgx.trusted_files.cp = "file:$(EXECDIR)/cp"
> sgx.trusted_files.date = "file:$(EXECDIR)/date"
> ```

@stefanberger you need to add readlink executable to trusted_files


<!-- Sent from Reviewable.io -->

2021-03-12 04:47 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @stefanberger)



<!-- Sent from Reviewable.io -->

2021-03-12 08:18 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @stefanberger)

___
*[Examples/bash/manifest.template, line 61 at r5](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVZ3DWQ2d8CqadZlAga:-MV_VIo46w7B7TEwv75m:b-4olakj) ([raw file](https://github.com/oscarlab/graphene/blob/3a890a510cfd9ffb1c9d3ceb46070db6bde4331a/Examples/bash/manifest.template#L61)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@stefanberger you need to add readlink executable to trusted_files
</blockquote></details>

+1. In particular, please add like this:
```
sgx.trusted_files.readlink = "file:$(EXECDIR)/readlink"
```


<!-- Sent from Reviewable.io -->

2021-03-12 12:58 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[Examples/bash/manifest.template, line 61 at r5](https://reviewable.io/reviews/oscarlab/graphene/2228#-MVZ3DWQ2d8CqadZlAga:-MVaW05TAA1uDDHwd8mW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3a890a510cfd9ffb1c9d3ceb46070db6bde4331a/Examples/bash/manifest.template#L61)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. In particular, please add like this:
```
sgx.trusted_files.readlink = "file:$(EXECDIR)/readlink"
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-12 12:58 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-03-12 12:59 UTC, dimakuv commented
Jenkins, test this please

2021-03-12 14:09 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-03-12 14:15 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-12 14:20 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-03-12 14:21 UTC, dimakuv commented
Jenkins, test this please

2021-03-12 15:06 UTC, mkow approved these changes
> Reviewed 1 of 3 files at r1, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2228)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-12 15:12 UTC, merged