[LibOS/shim] rtld: Refactor the ELF mapping function
oscarlab/graphene pull request #2231
Opened 2021-03-12 15:33 UTC by pwmarcz

## Description of the changes 

This is a refactoring of the biggest function in `shim_rtld`. See the commit message for details. Hopefully, it should be easier to understand now.

(I decided *not* to rewrite the function completely or base it on code from other projects. The [musl version](https://git.musl-libc.org/cgit/musl/tree/ldso/dynlink.c#n622) is dense and not very well-documented, and the [Linux version](https://code.woboq.org/linux/linux/fs/binfmt_elf.c.html) handles the load commands in a way I do not fully understand).

## How to test this PR? 

The existing Jenkins tests should be enough.

## Next steps

I'm now more or less satisfied with LibOS ELF handling: the `search_elf_by_handle` thing is kind of awkward but seems lower priority. When I have more time for ELFs, I will move on to PAL code.

2021-03-12 16:32 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbFRajCmoNuMybH6gr:-MVbFRajCmoNuMybH6gs:b-237d3z) (no related file):*
Can you please also remove unused typedef and defines?
non-blocking as it can be done as followup.

#ifndef DT_THISPROCNUM
typedef ElfW(Word) Elf_Symndx;
#define ELF32_CLASS ELFCLASS32
#define ELF64_CLASS ELFCLASS64

---
___
*[LibOS/shim/src/shim_rtld.c, line 138 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbGQDi9In3CWvgbIqc:-MVbGQDi9In3CWvgbIqd:bkri98w) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L138)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> #if __BYTE_ORDER == __BIG_ENDIAN
> #define byteorder ELFDATA2MSB
> #elif __BYTE_ORDER == __LITTLE_ENDIAN
> #define byteorder ELFDATA2LSB
> #else
> #error "Unknown __BYTE_ORDER " __BYTE_ORDER
> #define byteorder ELFDATANONE
> #endif
> ```
</details>


Please move down right above of the usage.
>  static const unsigned char expected[EI_NIDENT] = {


<!-- Sent from Reviewable.io -->

2021-03-12 18:16 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbFRajCmoNuMybH6gr:-MVbdUOm9-YHT6TxbvQR:b-z70dha) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Can you please also remove unused typedef and defines?
non-blocking as it can be done as followup.

#ifndef DT_THISPROCNUM
typedef ElfW(Word) Elf_Symndx;
#define ELF32_CLASS ELFCLASS32
#define ELF64_CLASS ELFCLASS64

</blockquote></details>

Done. `ELF32_CLASS` / `ELF64_CLASS` were actually used, indirectly, for `ELFW(CLASS)`. I replaced it with more straightforward code.

---
___
*[LibOS/shim/src/shim_rtld.c, line 138 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbGQDi9In3CWvgbIqc:-MVbciLcBxO9cpZZNM98:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L138)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> #if __BYTE_ORDER == __BIG_ENDIAN
> #define byteorder ELFDATA2MSB
> #elif __BYTE_ORDER == __LITTLE_ENDIAN
> #define byteorder ELFDATA2LSB
> #else
> #error "Unknown __BYTE_ORDER " __BYTE_ORDER
> #define byteorder ELFDATANONE
> #endif
> ```

Please move down right above of the usage.
>  static const unsigned char expected[EI_NIDENT] = {
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-13 01:20 UTC, mkow requested changes
Nice cleanup!

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231#-:-MVd9Fra9LL_9wcXcHTA:b7oy6or)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd5TsqCP-DM9kplkTM:-MVd5TsrEmCisjlEFNO_:b-uo887v) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L82)):*
> ```C
>     struct shim_handle* l_file;
> 
> #define MAX_LOADCMDS 4
> ```

This seems pretty low, could you change it to 8? OTOH, why not just allocated this array dynamically and remove this artificial limitation?
___
*[LibOS/shim/src/shim_rtld.c, line 144 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbM3wq1diR6nl6UIUs:-MVbM3wrBE9xu8a4Eqq8:bryla7s) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L144)):*
> ```C
> #endif
> 
> static int read_loadcmd(const ElfW(Phdr*) ph, struct loadcmd *c) {
> ```

`*` should be on the left
___
*[LibOS/shim/src/shim_rtld.c, line 195 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbPcKn0pCdmO9i70ZH:-MVbPcKn0pCdmO9i70ZI:bswr6e0) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L195)):*
> ```C
> 
> /*
>  * Execute a single load command: bookeep the memory, map the file content, and make sure the area
> ```

`bookeep` -> `bookkeep` (ditto for the commit msg)
___
*[LibOS/shim/src/shim_rtld.c, line 229 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd4cig6tj6MWYhcWww:-MVd4cih2SuDFpoX3osW:bodjgd5) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L229)):*
> ```C
>             if ((ret = DkVirtualMemoryProtect(last_page_start, g_pal_alloc_align,
>                                               pal_prot | PAL_PROT_WRITE) < 0)) {
>                 log_debug("execute_loadcmd: cannot change memory protections\n");
> ```

Could you use `__func__` everywhere to print function name? Will be less likely to diverge when refactoring.
___
*[LibOS/shim/src/shim_rtld.c, line 342 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd6Evr77XSDIw0zEHQ:-MVd6Evr77XSDIw0zEHR:bytplze) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L342)):*
> ```C
>     /* Determine the load address. */
> 
>     size_t total_size = l->l_loadcmds[l->l_nloadcmds - 1].alloc_end - l->l_loadcmds[0].start;
> ```

Is it actually guaranteed that the segments have to be sorted? I think ld.so assumes that the loading base is equal to the address of the first `PT_LOAD` segment, but the kernel doesn't, so you can use this trick to create ELFs which are parsed differently by both. And we should follow kernel here, if I understand correctly.
___
*[LibOS/shim/src/shim_rtld.c, line 363 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd7D7y7Ef9QachUv4J:-MVd7D7y7Ef9QachUv4K:bt6qzvf) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L363)):*
> ```C
>     /* Execute load commands. */
> 
>     for (struct loadcmd* c = &l->l_loadcmds[0]; c < &l->l_loadcmds[l->l_nloadcmds]; ++c) {
> ```

`++c` -> `c++` (for consistency + in C you don't have the iterator problem like in C++)
___
*[LibOS/shim/src/shim_rtld.c, line 405 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd5uLi-nGvEU7gzo11:-MVd5uLi-nGvEU7gzo12:b-ltq1s8) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L405)):*
> ```C
>     return l;
> 
> call_lose:
> ```

Could you rename this label while we're here? What does "call lose" even mean? :)


<!-- Sent from Reviewable.io -->

2021-03-13 09:15 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd5TsqCP-DM9kplkTM:-MVejTGy1u2_k4ZD4C8g:b-w8umfo) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This seems pretty low, could you change it to 8? OTOH, why not just allocated this array dynamically and remove this artificial limitation?
</blockquote></details>

This is a limit from glibc so I assume ELFs with more than 4 PT_LOAD headers are pretty rare. But OK, it doesn't hurt to allocate dynamically. Done.
___
*[LibOS/shim/src/shim_rtld.c, line 144 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbM3wq1diR6nl6UIUs:-MVemUxf4mUD3HQd-25R:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L144)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`*` should be on the left
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 195 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVbPcKn0pCdmO9i70ZH:-MVen0eu5_tj_bSOrJkk:bdmng77) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L195)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`bookeep` -> `bookkeep` (ditto for the commit msg)
</blockquote></details>

Done (in commit message too).
___
*[LibOS/shim/src/shim_rtld.c, line 229 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd4cig6tj6MWYhcWww:-MVenYIA9R25GdYzIcp_:bm3yqt3) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L229)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you use `__func__` everywhere to print function name? Will be less likely to diverge when refactoring.
</blockquote></details>

OK, done.
___
*[LibOS/shim/src/shim_rtld.c, line 342 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd6Evr77XSDIw0zEHQ:-MVenjDBAioLiaNqmNaV:bpnmlsd) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L342)):*
>Is it actually guaranteed that the segments have to be sorted? 

Yes. From [the spec](https://refspecs.linuxfoundation.org/elf/elf.pdf): "Loadable segment entries in the program header table appear in ascending order, sorted on the `p_vaddr` member."

>I think ld.so assumes that the loading base is equal to the address of the first PT_LOAD segment, but the kernel doesn't, so you can use this trick to create ELFs which are parsed differently by both. And we should follow kernel here, if I understand correctly.

Is this about a malformed ELF with non-sorted segment list?

I'm not sure what you mean by loading base. If it's the load address (added to all `vaddr` values) then it's called `l_addr` in here, and it's 0 in case of non-PIC binaries.

In case of PIC binaries, It does depend on the first segment address, but only in the sense that we don't need to reserve a full chunk of memory starting from 0 (i.e. if the first segment starts at vaddr `0x1000`, then we will reserve memory starting from `l_addr + 0x1000`, not starting from `l_addr`).
___
*[LibOS/shim/src/shim_rtld.c, line 363 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd7D7y7Ef9QachUv4J:-MVepfY1E8VtEyG-IF1A:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L363)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`++c` -> `c++` (for consistency + in C you don't have the iterator problem like in C++)
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 405 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd5uLi-nGvEU7gzo11:-MVepzyu-_0Inah0fk30:b-2cx0dj) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L405)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you rename this label while we're here? What does "call lose" even mean? :)
</blockquote></details>

I renamed it to `err`.


<!-- Sent from Reviewable.io -->

2021-03-13 13:25 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd5TsqCP-DM9kplkTM:-MVfaMdSAMo3ovlU7wbB:bvv61nf) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L82)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is a limit from glibc so I assume ELFs with more than 4 PT_LOAD headers are pretty rare. But OK, it doesn't hurt to allocate dynamically. Done.
</blockquote></details>

Huh.
I should have expected that from glibc :)
___
*[LibOS/shim/src/shim_rtld.c, line 342 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd6Evr77XSDIw0zEHQ:-MVfiunuAM2hTEARnRCj:b-67pkvr) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L342)):*
> Is this about a malformed ELF with non-sorted segment list?

Malformed or intentionally protected from reverse engineering/debugging, but the later case isn't too common on Linux, so I guess we don't have to care too much about it if the standard says that it's not allowed.

> I'm not sure what you mean by loading base. If it's the load address (added to all `vaddr` values) then it's called `l_addr` in here, and it's 0 in case of non-PIC binaries.

Yup, I meant `l_addr`.

Anyways, I think we don't need to care about this, so I'm resolving.
___
*[LibOS/shim/src/shim_rtld.c, line 167 at r3](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVfajRk7rQXUWcp94eg:-MVfajRl8NAF6mJLaQo5:b-305di) ([raw file](https://github.com/oscarlab/graphene/blob/03e7de1e88758b8f112ad9b6598e6beeb212cc20/LibOS/shim/src/shim_rtld.c#L167)):*
> ```C
>     int ret;
> 
>     int n = 0;
> ```

Could make this and `phnum` `size_t`?


<!-- Sent from Reviewable.io -->

2021-03-13 13:56 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd5TsqCP-DM9kplkTM:-MVfoaa43xm0vfmNGAvP:b-aduaek) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh.
I should have expected that from glibc :)
</blockquote></details>

Uhhh, okay, it's not so simple because the `loadcmds` are migrated too, and what I just wrote blows up on fork.

I could fix that (allocate memory for this array during checkpointing, and copy it), but I'd rather make this simpler (I'm already not happy that this PR is `+290 -260`, but at least the code looks better :) ). So I limited the use of `loadcmds` to this one function.
___
*[LibOS/shim/src/shim_rtld.c, line 167 at r3](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVfajRk7rQXUWcp94eg:-MVfrTUe2X8X5U0RNlJ5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/03e7de1e88758b8f112ad9b6598e6beeb212cc20/LibOS/shim/src/shim_rtld.c#L167)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could make this and `phnum` `size_t`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-13 15:35 UTC, mkow approved these changes, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd5TsqCP-DM9kplkTM:-MVgDW_x9FNQoFJq5iNG:bab7c6r) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L82)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Uhhh, okay, it's not so simple because the `loadcmds` are migrated too, and what I just wrote blows up on fork.

I could fix that (allocate memory for this array during checkpointing, and copy it), but I'd rather make this simpler (I'm already not happy that this PR is `+290 -260`, but at least the code looks better :) ). So I limited the use of `loadcmds` to this one function.
</blockquote></details>

I like the new version :)


<!-- Sent from Reviewable.io -->

2021-03-17 01:58 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 342 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd6Evr77XSDIw0zEHQ:-MVxfuBa0gzOjeGKYDaj:b-ds5hnc) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L342)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Is this about a malformed ELF with non-sorted segment list?

Malformed or intentionally protected from reverse engineering/debugging, but the later case isn't too common on Linux, so I guess we don't have to care too much about it if the standard says that it's not allowed.

> I'm not sure what you mean by loading base. If it's the load address (added to all `vaddr` values) then it's called `l_addr` in here, and it's 0 in case of non-PIC binaries.

Yup, I meant `l_addr`.

Anyways, I think we don't need to care about this, so I'm resolving.
</blockquote></details>

As far as the spec says the segments have to be sorted, we still should either validate that (in `read_all_loadcmds`?) or not assume at all.
___
*[LibOS/shim/src/shim_rtld.c, line 105 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxouqr61cesDY13SS5:-MVxouqs3TE3RhqHy7kt:bsu86db) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L105)):*
> ```C
> 
>     /* File offset */
>     off_t map_off;
> ```

Could you change this to a signed version: either `ElfW(Off)` or `size_t`?
I'll submit a PR changing our `bkeep_*` interfaces in the meantime, they are bad/wrong (and will try to merge it asap, so that you can rebase on it). Let's wait with this change till then.
___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MVxHUpR7w-E9FkFubRZ:b-64qebw) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
> ```C
>     assert(ph->p_type == PT_LOAD);
> 
>     if (!IS_ALLOC_ALIGNED(ph->p_align)) {
> ```

It should also be a power of 2 (because that's elf requirement and the code below assumes that).
Also there are special cases for `0` and `1`.
___
*[LibOS/shim/src/shim_rtld.c, line 138 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxKQ093UO7YMAfu-VI:-MVxIF-jD4L9uGqJKRbR:bon6j6l) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L138)):*
> ```C
>     }
> 
>     if (!IS_ALIGNED_POW2(ph->p_vaddr - ph->p_offset, ph->p_align)) {
> ```

We should also check that `p_offset` and `p_vaddr` are both page aligned. Which for now probably means `ALLOC_ALIGNED` (we need to fix this mess...)
___
*[LibOS/shim/src/shim_rtld.c, line 148 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxLMN-EOat9UkgOCM2:-MVxLMN-EOat9UkgOCM3:bkjdc9r) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L148)):*
> ```C
>     }
> 
>     c->start = ALLOC_ALIGN_DOWN(ph->p_vaddr);
> ```

Assuming this is the same as page aligning, it's not needed.
Assuming it's not the same, this code does not work as we could get overlapping segments.
Hence: please remove aligning here (but see the comment above about checking).
___
*[LibOS/shim/src/shim_rtld.c, line 152 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxMr3x8DAPcz_fFhVW:-MVxMr3x8DAPcz_fFhVX:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L152)):*
> ```C
>     c->map_end = ALLOC_ALIGN_UP(ph->p_vaddr + ph->p_filesz);
>     c->alloc_end  = ALLOC_ALIGN_UP(ph->p_vaddr + ph->p_memsz);
>     c->map_off = ALLOC_ALIGN_DOWN(ph->p_offset);
> ```

ditto
___
*[LibOS/shim/src/shim_rtld.c, line 164 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxZEIN9rE-R_C-H14K:-MVxZEIN9rE-R_C-H14L:bce7dph) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L164)):*
> ```C
> }
> 
> static ssize_t read_all_loadcmds(const ElfW(Phdr*) phdr, size_t phnum,
> ```

Could you please use out-arguments for returning values (here size)?
___
*[LibOS/shim/src/shim_rtld.c, line 165 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxZCIB53mK5U_iCwS6:-MVxZCIB53mK5U_iCwS7:bdx86s1) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L165)):*
> ```C
> 
> static ssize_t read_all_loadcmds(const ElfW(Phdr*) phdr, size_t phnum,
>                              struct loadcmd** loadcmds) {
> ```

Broken alignment.
___
*[LibOS/shim/src/shim_rtld.c, line 177 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxOLM33sCJmNa2OaWn:-MVxOLM33sCJmNa2OaWo:b-t5byxg) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L177)):*
> ```C
>         return 0;
> 
>     if ((*loadcmds = malloc(n * sizeof(struct loadcmd))) == NULL) {
> ```

Please change to `sizeof(**loadcmds)`
___
*[LibOS/shim/src/shim_rtld.c, line 217 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxTDfd7omTrcsWsU3n:-MVxTDfd7omTrcsWsU3o:b720pa5) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L217)):*
> ```C
>  * Execute a single load command: bookkeep the memory, map the file content, and make sure the area
>  * not mapped to a file (ph_filesz .. ph_memsz) is zero-filled.
>  */
> ```

Please add a comment saying this function does not perform cleanups (e.g. does not unmap 1st segment if allocation of 2nd fails).
___
*[LibOS/shim/src/shim_rtld.c, line 227 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxQ0Jl1PNAKMTXFF2p:-MVxQ0Jl1PNAKMTXFF2q:b66h36q) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L227)):*
> ```C
>         size_t map_size = c->map_end - c->start;
>         int map_flags =  MAP_FILE | MAP_FIXED | MAP_PRIVATE;
> ```

`MAP_FILE` is a no-op and ignored, you can skip it.
___
*[LibOS/shim/src/shim_rtld.c, line 246 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxQqiu64DuJEC0fFnO:-MVxQqiu64DuJEC0fFnP:b-k5jfu5) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L246)):*
> ```C
>         void* zero_start = (void*)(load_addr + c->data_end);
>         size_t zero_size = c->map_end - c->data_end;
>         void* last_page_start = (void*)(ALLOC_ALIGN_DOWN(load_addr + c->data_end));
> ```

NP: please change to `ALLOC_ALIGN_DOWN_PTR(zero_start)`
___
*[LibOS/shim/src/shim_rtld.c, line 247 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxRm7Y10XVcbMRLfc0:-MVxRm7Y10XVcbMRLfc1:b-7ad9i) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L247)):*
> ```C
>         size_t zero_size = c->map_end - c->data_end;
>         void* last_page_start = (void*)(ALLOC_ALIGN_DOWN(load_addr + c->data_end));
>         PAL_FLG pal_prot = LINUX_PROT_TO_PAL(c->prot, /*map_flags=*/0);
> ```

`map_flags` are not `0` but, the same as the ones passed to `bkeep_mmap_fixed` above.
___
*[LibOS/shim/src/shim_rtld.c, line 257 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxSL0f08lVos4vdy8t:-MVxSL0f08lVos4vdy8u:bry1izz) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shi [...]

2021-03-17 03:07 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 105 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxouqr61cesDY13SS5:-MVy8bEO5pJAHCnxu_uo:b9reg22) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you change this to a signed version: either `ElfW(Off)` or `size_t`?
I'll submit a PR changing our `bkeep_*` interfaces in the meantime, they are bad/wrong (and will try to merge it asap, so that you can rebase on it). Let's wait with this change till then.
</blockquote></details>

PR #2244


<!-- Sent from Reviewable.io -->

2021-03-17 16:36 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 342 at r1](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVd6Evr77XSDIw0zEHQ:-MW-kcWa-69lfGQvDWyi:bx82bgs) ([raw file](https://github.com/oscarlab/graphene/blob/d211ae8c8e67c07d3f659e06daf3ce7f7b6565b6/LibOS/shim/src/shim_rtld.c#L342)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

As far as the spec says the segments have to be sorted, we still should either validate that (in `read_all_loadcmds`?) or not assume at all.
</blockquote></details>

OK, I added a check in `read_all_loadcmds`.
___
*[LibOS/shim/src/shim_rtld.c, line 105 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxouqr61cesDY13SS5:-MW-TkjH6WSUeSETn7rs:b-iiuxdc) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L105)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

PR #2244
</blockquote></details>

Changed to `size_t`.
___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW-Xr-W-547PiBnXaTj:b-3a08bu) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It should also be a power of 2 (because that's elf requirement and the code below assumes that).
Also there are special cases for `0` and `1`.
</blockquote></details>

Good point. But if I read the spec correctly, we don't need `p_align` at all, we just need to make sure `p_vaddr` and `p_offset` are congruent modulo page size.

That seems in line with what Linux and musl ELF code do (they don't look at `p_align` at all when processing `PT_LOAD`).

I removed the `p_align` checks and instead check if `p_vaddr - p_offset` is page-aligned (which is what we actually need).
___
*[LibOS/shim/src/shim_rtld.c, line 138 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxKQ093UO7YMAfu-VI:-MW-YmxdEnEtQM9m4JRt:b-vkzig1) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L138)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should also check that `p_offset` and `p_vaddr` are both page aligned. Which for now probably means `ALLOC_ALIGNED` (we need to fix this mess...)
</blockquote></details>

They don't need to be. As an example, here's the last segment of `/bin/cat` from my system:

```
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
...
  LOAD           0x0000000000009a30 0x000000000000aa30 0x000000000000aa30
                 0x0000000000000690 0x0000000000000808  RW     0x1000
```

The offset and virtual address are not aligned modulo 0x1000, but their difference is.

That's the reason for the `ALLOC_ALIGN_DOWN` in the following code: we round both offset and virtual address down, mapping a segment so that it starts at page boundary. This is what glibc does (that's where this code was copied from), as well as Linux (see [elf_map](https://code.woboq.org/linux/linux/fs/binfmt_elf.c.html#347)).
___
*[LibOS/shim/src/shim_rtld.c, line 148 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxLMN-EOat9UkgOCM2:-MW-biBTCeoATimaRVpD:bsw7ldc) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L148)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Assuming this is the same as page aligning, it's not needed.
Assuming it's not the same, this code does not work as we could get overlapping segments.
Hence: please remove aligning here (but see the comment above about checking).
</blockquote></details>

See above, my understanding is this is still necessary.
___
*[LibOS/shim/src/shim_rtld.c, line 164 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxZEIN9rE-R_C-H14K:-MW-dhL3DyqUIiREO9Z0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L164)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you please use out-arguments for returning values (here size)?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 165 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxZCIB53mK5U_iCwS6:-MW-dnwZ80fawMyfG_OA:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L165)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Broken alignment.
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/shim_rtld.c, line 177 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxOLM33sCJmNa2OaWn:-MW-dtdG3i7he7e0rSvV:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L177)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change to `sizeof(**loadcmds)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 217 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxTDfd7omTrcsWsU3n:-MW-f05fA8nW8G0mV1U4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L217)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment saying this function does not perform cleanups (e.g. does not unmap 1st segment if allocation of 2nd fails).
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 227 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxQ0Jl1PNAKMTXFF2p:-MW-f3_Q8G9bq7ce6oBF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L227)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`MAP_FILE` is a no-op and ignored, you can skip it.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 246 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxQqiu64DuJEC0fFnO:-MW-fEQ99J17_PrrV8Vh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L246)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: please change to `ALLOC_ALIGN_DOWN_PTR(zero_start)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 247 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxRm7Y10XVcbMRLfc0:-MW-g1UU1uGR6vQ3J7Bk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L247)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`map_flags` are not `0` but, the same as the ones passed to `bkeep_mmap_fixed` above.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 257 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxSL0f08lVos4vdy8t:-MW-g6Hi1F_zUDEenrKJ:b-896fix) ([raw file](https://github.com/oscarlab/graph [...]

2021-03-17 16:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW049OZ7Elcz-_i9o_G:bveta2q) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Good point. But if I read the spec correctly, we don't need `p_align` at all, we just need to make sure `p_vaddr` and `p_offset` are congruent modulo page size.

That seems in line with what Linux and musl ELF code do (they don't look at `p_align` at all when processing `PT_LOAD`).

I removed the `p_align` checks and instead check if `p_vaddr - p_offset` is page-aligned (which is what we actually need).
</blockquote></details>

By the way, `ALLOC_ALIGN_*` / `g_pal_alloc_align` is not actually the same as "page aligned", but some approximation by Graphene? I don't know the details but I assume that's what we should use.


<!-- Sent from Reviewable.io -->

2021-03-17 19:29 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW04CeF33jePCpIcVTs:b-gae01d) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Good point. But if I read the spec correctly, we don't need `p_align` at all, we just need to make sure `p_vaddr` and `p_offset` are congruent modulo page size.

That seems in line with what Linux and musl ELF code do (they don't look at `p_align` at all when processing `PT_LOAD`).

I removed the `p_align` checks and instead check if `p_vaddr - p_offset` is page-aligned (which is what we actually need).
</blockquote></details>

We do need to look at `p_align`, it might be greater than page alignment.
The Linux kernel does look at it, I did not search through code, but manual check (just changed alignment of first segment it elf to `0x8000`) indicates that it respects the request.
___
*[LibOS/shim/src/shim_rtld.c, line 138 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxKQ093UO7YMAfu-VI:-MW054-cBI4V0a0LLF_w:b-kkruve) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L138)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

They don't need to be. As an example, here's the last segment of `/bin/cat` from my system:

```
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
...
  LOAD           0x0000000000009a30 0x000000000000aa30 0x000000000000aa30
                 0x0000000000000690 0x0000000000000808  RW     0x1000
```

The offset and virtual address are not aligned modulo 0x1000, but their difference is.

That's the reason for the `ALLOC_ALIGN_DOWN` in the following code: we round both offset and virtual address down, mapping a segment so that it starts at page boundary. This is what glibc does (that's where this code was copied from), as well as Linux (see [elf_map](https://code.woboq.org/linux/linux/fs/binfmt_elf.c.html#347)).
</blockquote></details>

That's true, I dont know where I got that from...
___
*[LibOS/shim/src/shim_rtld.c, line 272 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxSyCM3J2JijHmNfSo:-MW067UR5EqPaUty6YXR:b-x0uwsv) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L272)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done (here we map with `MAP_ANONYMOUS`, which doesn't matter for `LINUX_PROT_TO_PAL`, but I refactored it so that it's clear it's a PAL version of the same flags).
</blockquote></details>

Yeah, it does not matter now, but we should not bother about it here.
___
*[LibOS/shim/src/shim_rtld.c, line 297 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxY7q67OjBaIQShpMw:-MW0EUig6_LtYlSBsHFI:bjsgggw) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L297)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We don't return the code, but I think we should at least report it instead of throwing away. I added it to the `log_debug` in the error handling code.
</blockquote></details>

That solves the issue as well.
___
*[LibOS/shim/src/shim_rtld.c, line 369 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxguep4jt_ur0L4hXw:-MW0VdyU00Acggtsl_9f:b-2lbct8) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L369)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Not sure. Looking at the other implementations, I think they don't worry about that, and just do what we do here. In practice, a shared object gets loaded at some high address...

Thinking aloud, I can see the following options:
1. Not wory about it either, and let `l_addr` wrap around... but yeah, something might break.
2. Add an `assert(map_start >= loadcmds[0].start)`, so that we at least catch this in debug mode.
3. Reserve the whole chunk of memory (starting from 0, not `loadcmds[0].start`, possibly wasting some memory at the beginning).
4. Add a `min_addr` parameter to `bkeep_mmap_any_aslr` so that we can request an address no lower than `loadcmds[0].start`.

What do you think?
</blockquote></details>

I would go for 3. I dont expect many elfs to not have segments mapped at `0` and have the first mapped at meaningfully large offset.

Btw, there is a way to do 4, there's a function mmap in range (but lets not do that here).
___
*[LibOS/shim/src/shim_rtld.c, line 46 at r5](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW0RtFv59pC9atEUy7Z:-MW0RtFv59pC9atEUy7_:bid4uin) ([raw file](https://github.com/oscarlab/graphene/blob/96204b02fda495b74094ed3feb94e8957edc627e/LibOS/shim/src/shim_rtld.c#L46)):*
> ```C
>  * Originally based on glibc link_map structure.
>  */
> struct link_map {
> ```

Actually what's the need for this struct? Sounds like something glibc would hold not kernel...
Do we need all these fields or just like 10% of them and only for main executable?
___
*[LibOS/shim/src/shim_rtld.c, line 168 at r5](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW05d8n8HOHPY0sSRww:-MW05d8n8HOHPY0sSRwx:bso84lq) ([raw file](https://github.com/oscarlab/graphene/blob/96204b02fda495b74094ed3feb94e8957edc627e/LibOS/shim/src/shim_rtld.c#L168)):*
> ```C
>             n++;
> 
>     if (n == 0)
> ```

Don't we need to set `n_loadcmds` to `0` here as well? (Also setting `loadcmds` to `NULL` wouldn't hurt, just to be explicit)


<!-- Sent from Reviewable.io -->

2021-03-17 19:35 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW0eeX45uYvFMC6gPbf:bxywn8u) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
> By the way, ALLOC_ALIGN_* / g_pal_alloc_align is not actually the same as "page aligned", but some approximation by Graphene? I don't know the details but I assume that's what we should use.

It could be greater than page size. The idea is that Pal might require higher alignment on some allocations (e.g. Windows), but this is all a mess and does not work well (i.e. I don't think Graphene will work with anything else than page size).


<!-- Sent from Reviewable.io -->

2021-03-17 21:37 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW119x2CuX7kR6mrML3:b-9cnax5) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
> The Linux kernel does look at it, I did not search through code, but manual check (just changed alignment of first segment it elf to 0x8000) indicates that it respects the request.

Okay, it looks like I was looking at an older Linux version (whatever it is on code.woboq.org)? And it looks like [since Linux 5.10, `p_align` is used for selecting a start address for `ET_DYN` binaries](https://github.com/torvalds/linux/commit/ce81bb256a224259ab686742a6284930cbe4f1fa).

Is that what you mean, or is there something else I should do?
___
*[LibOS/shim/src/shim_rtld.c, line 369 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxguep4jt_ur0L4hXw:-MW152wK3j5HG44b4uWM:b-drfg3l) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L369)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would go for 3. I dont expect many elfs to not have segments mapped at `0` and have the first mapped at meaningfully large offset.

Btw, there is a way to do 4, there's a function mmap in range (but lets not do that here).
</blockquote></details>

OK, I'll do that.
___
*[LibOS/shim/src/shim_rtld.c, line 46 at r5](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW0RtFv59pC9atEUy7Z:-MW1-Nfw-U5AL0TXuI4m:b7mr3vm) ([raw file](https://github.com/oscarlab/graphene/blob/96204b02fda495b74094ed3feb94e8957edc627e/LibOS/shim/src/shim_rtld.c#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually what's the need for this struct? Sounds like something glibc would hold not kernel...
Do we need all these fields or just like 10% of them and only for main executable?
</blockquote></details>

I'd say we are in the process of removing this. These are the fields that are still used, *after* I removed the rest of them :)

So yeah, taking this further, probably we can get rid of this whole global list of objects, and possibly the struct as well. But it needs a few steps more: the ELF setup is split across several functions that operate on `link_map`s.
___
*[LibOS/shim/src/shim_rtld.c, line 168 at r5](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW05d8n8HOHPY0sSRww:-MW14ufZ5f27U33mTobG:by1eqof) ([raw file](https://github.com/oscarlab/graphene/blob/96204b02fda495b74094ed3feb94e8957edc627e/LibOS/shim/src/shim_rtld.c#L168)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we need to set `n_loadcmds` to `0` here as well? (Also setting `loadcmds` to `NULL` wouldn't hurt, just to be explicit)
</blockquote></details>

ACK, will fix.


<!-- Sent from Reviewable.io -->

2021-03-18 09:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 369 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxguep4jt_ur0L4hXw:-MW3ead171P46gCrjrdF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L369)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I'll do that.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 168 at r5](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW05d8n8HOHPY0sSRww:-MW3chSbAdW4UAgaeIH2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96204b02fda495b74094ed3feb94e8957edc627e/LibOS/shim/src/shim_rtld.c#L168)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

ACK, will fix.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-18 12:19 UTC, mkow requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 104 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4CBE3AlS0xNqv3lOE:-MW4CBE473ZJQkhu6x57:b-2x71hj) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L104)):*
> ```C
> 
>     /* File offset */
>     size_t map_off;
> ```

Please use `uint64_t` for file offsets (`size_t` may be too small on 32-bit)
ditto for the whole PR
___
*[LibOS/shim/src/shim_rtld.c, line 358 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4ESR407UmzMakqRHD:-MW4ESR407UmzMakqRHE:b9lt0qu) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L358)):*
> ```C
>     const ElfW(Phdr)* ph;
>     for (ph = phdr; ph < &phdr[ehdr->e_phnum]; ph++) {
>         switch (ph->p_type) {
> ```

This can be just an `if` now.
___
*[LibOS/shim/src/shim_rtld.c, line 447 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4FMXBDMJn80_UC7oz:-MW4FMXC1cA8TMfnbdlk:b67kdjp) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L447)):*
> ```C
> 
>     if (ehdr->e_entry != 0 && !l->l_entry) {
>         errstring = "interpreter name not found in any of the segments";
> ```

Static binaries don't have an interpreter at all.


<!-- Sent from Reviewable.io -->

2021-03-18 12:58 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 104 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4CBE3AlS0xNqv3lOE:-MW4LXT2CyJkqwIwZgU5:b-e4vfmp) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use `uint64_t` for file offsets (`size_t` may be too small on 32-bit)
ditto for the whole PR
</blockquote></details>

Are you sure I should? On 32-bit, the field we take this from is `Elf32_Off` which is unsigned 32-bit, so I think 32-bit ELFs are not allowed to specify a bigger offset.

And unfortunately our filesystem (`fs_ops->seek`) uses `off_t` for now... It shouldn't matter here but probably we should change it.
___
*[LibOS/shim/src/shim_rtld.c, line 358 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4ESR407UmzMakqRHD:-MW4N2uh2jl8FBTC6AK4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L358)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This can be just an `if` now.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 447 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4FMXBDMJn80_UC7oz:-MW4N4n2EDaeJ__8uDL-:b-er0dmc) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L447)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Static binaries don't have an interpreter at all.
</blockquote></details>

Oops, this is the wrong message (this one is supposed to be for entry point). Fixed.

Anyway, we do check if ELF specified an interpreter (`interp_libname_vaddr != 0`), and complain only if it's specified but not mapped.


<!-- Sent from Reviewable.io -->

2021-03-18 13:10 UTC, mkow requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 104 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4CBE3AlS0xNqv3lOE:-MW4RmC31XbINHKKPnuX:b6em10w) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L104)):*
> Are you sure I should? On 32-bit, the field we take this from is `Elf32_Off` which is unsigned 32-bit, so I think 32-bit ELFs are not allowed to specify a bigger offset.

Even if, I prefer to push such limitations down to the very layer they appear and don't propagate them throughout our code.

Ad FS code: yup, this is something we need to fix. Borys recently fixed this for _mmap callbacks, but others are still to be done.
___
*[LibOS/shim/src/shim_rtld.c, line 447 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4FMXBDMJn80_UC7oz:-MW4SATYByn5E-dKmJWZ:bi98jik) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L447)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oops, this is the wrong message (this one is supposed to be for entry point). Fixed.

Anyway, we do check if ELF specified an interpreter (`interp_libname_vaddr != 0`), and complain only if it's specified but not mapped.
</blockquote></details>

Ah. Sounds good then.


<!-- Sent from Reviewable.io -->

2021-03-18 13:23 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 104 at r6](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW4CBE3AlS0xNqv3lOE:-MW4TeW9E6qNZPvgzArR:b-q20d1y) ([raw file](https://github.com/oscarlab/graphene/blob/dd56eac29671587a30653d67c8bd574d3ae36aa5/LibOS/shim/src/shim_rtld.c#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Are you sure I should? On 32-bit, the field we take this from is `Elf32_Off` which is unsigned 32-bit, so I think 32-bit ELFs are not allowed to specify a bigger offset.

Even if, I prefer to push such limitations down to the very layer they appear and don't propagate them throughout our code.

Ad FS code: yup, this is something we need to fix. Borys recently fixed this for _mmap callbacks, but others are still to be done.
</blockquote></details>

OK. I changed the offset to `uint64_t` and added a TODO to `read_file_fragment` function explaining the current limitation.


<!-- Sent from Reviewable.io -->

2021-03-18 13:42 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-18 16:22 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW54EkK0KDCKxG8a_pU:b-bd8ko4) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

> The Linux kernel does look at it, I did not search through code, but manual check (just changed alignment of first segment it elf to 0x8000) indicates that it respects the request.

Okay, it looks like I was looking at an older Linux version (whatever it is on code.woboq.org)? And it looks like [since Linux 5.10, `p_align` is used for selecting a start address for `ET_DYN` binaries](https://github.com/torvalds/linux/commit/ce81bb256a224259ab686742a6284930cbe4f1fa).

Is that what you mean, or is there something else I should do?
</blockquote></details>

This is what linux does: https://elixir.bootlin.com/linux/latest/source/fs/binfmt_elf.c#L1114 and I would follow that (it just takes the maximum alignment of all load segments).
___
*[LibOS/shim/src/shim_rtld.c, line 373 at r8](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW56kx16jRntxQvJKn1:-MW56kx16jRntxQvJKn2:bxkn5tf) ([raw file](https://github.com/oscarlab/graphene/blob/1e38311702ed763e98f82a47e245e48f8bb4278d/LibOS/shim/src/shim_rtld.c#L373)):*
> ```C
>          * address.
>          *
>          * Note that we reserve memory starting from virtual address 0, not from load_start. This is
> ```

This is misleading - it's rather an offset, not an address (I know, that's how it's called in elf, but still).


<!-- Sent from Reviewable.io -->

2021-03-18 17:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW5ATmI8lBbnYm7Mrpv:b-o2qk9w) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is what linux does: https://elixir.bootlin.com/linux/latest/source/fs/binfmt_elf.c#L1114 and I would follow that (it just takes the maximum alignment of all load segments).
</blockquote></details>

That's the same code as I linked to, and it's new behaviour introduced in Linux 5.10 (I had to switch kernels to verify it works).

According to the patch message, it's about supporting huge pages? So I'm not convinced it's too important for us, but I guess it doesn't hurt to emulate Linux.

Done (and same as Linux, I'm not doing it for interpreter).
___
*[LibOS/shim/src/shim_rtld.c, line 373 at r8](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW56kx16jRntxQvJKn1:-MW5LHt6CRTsQ4JZjhy6:b-svqod4) ([raw file](https://github.com/oscarlab/graphene/blob/1e38311702ed763e98f82a47e245e48f8bb4278d/LibOS/shim/src/shim_rtld.c#L373)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is misleading - it's rather an offset, not an address (I know, that's how it's called in elf, but still).
</blockquote></details>

Changed "virtual address" to "offset".


<!-- Sent from Reviewable.io -->

2021-03-18 17:44 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW5QP8A2846VX-nwIdO:b-5lj3ww) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's the same code as I linked to, and it's new behaviour introduced in Linux 5.10 (I had to switch kernels to verify it works).

According to the patch message, it's about supporting huge pages? So I'm not convinced it's too important for us, but I guess it doesn't hurt to emulate Linux.

Done (and same as Linux, I'm not doing it for interpreter).
</blockquote></details>

I guess there are no other use cases for higher-than-pagesize alignment than, well, larger page sizes...
This is getting messy, we now just overallocate memory. As this indeed seems not really important, I'm fine with either reverting this change or leaving it as it is, your choice :)
cc @mkow 


<!-- Sent from Reviewable.io -->

2021-03-18 17:59 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW5TLEU-F0USf6fnEcV:b-ike07d) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I guess there are no other use cases for higher-than-pagesize alignment than, well, larger page sizes...
This is getting messy, we now just overallocate memory. As this indeed seems not really important, I'm fine with either reverting this change or leaving it as it is, your choice :)
cc @mkow 
</blockquote></details>

Then I'll revert it: it's not needed according to ELF spec, it's implemented by Linux but only recently, and I want to keep this code simpler. We can add it if it ever turns out to be important.


<!-- Sent from Reviewable.io -->

2021-03-18 18:11 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW5Vz7F-oiievm-kVhp:b-l4p0ur) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Then I'll revert it: it's not needed according to ELF spec, it's implemented by Linux but only recently, and I want to keep this code simpler. We can add it if it ever turns out to be important.
</blockquote></details>

"Otherwise, p_align should be a positive, integral power of two, and p_vaddr should equal p_offset, modulo p_align." (from elf spec)
So I would say it is needed be spec, but in practice noone cares, as everything is just page aligned (except for the new case of huge pages, as you pointed out). Nevertheless we should validate the entries (I think this code was here, in once of the intermediate versions).
___
*[LibOS/shim/src/shim_rtld.c, line 373 at r10](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW5VdB21YxCxiI9QDOY:-MW5VdB21YxCxiI9QDOZ:bdxw3i3) ([raw file](https://github.com/oscarlab/graphene/blob/308d038ae57da2ed10731a6fae00874b3c34997c/LibOS/shim/src/shim_rtld.c#L373)):*
> ```C
>          * address.
>          *
>          * Note that we reserve memory starting from virtual address 0, not from load_start. This is
> ```

But this change should stay :)


<!-- Sent from Reviewable.io -->

2021-03-18 18:54 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW5_VLF59redmK77Nox:b-1xs8o2) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
Okay, I wouldn't be surprised if that was intended by ELF spec, but I have no idea where the spec says `p_align` works like that. I understand what you quoted as `p_vaddr - p_offset % p_align == 0`, which is a statement about these three fields, not about how the segment should be loaded in memory or what the load address should be. I don't know how else I could interpret it.

(The spec does mention _maximum page size_ elsewhere, but I think that's maximum page size for the architecture, not `p_align`).

>Nevertheless we should validate the entries (I think this code was here, in once of the intermediate versions).

Okay... There already was a check that the values are page-aligned (so that we can mmap the segment). I added a sanity check that verifies `p_align` and the offsets modulo `p_align` (if it's not 0 or 1).
___
*[LibOS/shim/src/shim_rtld.c, line 373 at r10](https://reviewable.io/reviews/oscarlab/graphene/2231#-MW5VdB21YxCxiI9QDOY:-MW5fUHx3tuI3k18ury8:bvybzrr) ([raw file](https://github.com/oscarlab/graphene/blob/308d038ae57da2ed10731a6fae00874b3c34997c/LibOS/shim/src/shim_rtld.c#L373)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But this change should stay :)
</blockquote></details>

Oops, right. Changed back to "offset".


<!-- Sent from Reviewable.io -->

2021-03-18 19:16 UTC, boryspoplawski approved these changes, later dismissed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yamahata)

___
*[LibOS/shim/src/shim_rtld.c, line 133 at r4](https://reviewable.io/reviews/oscarlab/graphene/2231#-MVxHUpQ7Gxh1gsgt_5A:-MW5kjA_AqUKTucGmJmt:b-q8rrx6) ([raw file](https://github.com/oscarlab/graphene/blob/837e231ce4b0d7670e3b2228e3f06b7ce240b1ab/LibOS/shim/src/shim_rtld.c#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, I wouldn't be surprised if that was intended by ELF spec, but I have no idea where the spec says `p_align` works like that. I understand what you quoted as `p_vaddr - p_offset % p_align == 0`, which is a statement about these three fields, not about how the segment should be loaded in memory or what the load address should be. I don't know how else I could interpret it.

(The spec does mention _maximum page size_ elsewhere, but I think that's maximum page size for the architecture, not `p_align`).

>Nevertheless we should validate the entries (I think this code was here, in once of the intermediate versions).

Okay... There already was a check that the values are page-aligned (so that we can mmap the segment). I added a sanity check that verifies `p_align` and the offsets modulo `p_align` (if it's not 0 or 1).
</blockquote></details>

I've just grepped `p_align` in https://refspecs.linuxfoundation.org/elf/elf.pdf 

The current version looks good.


<!-- Sent from Reviewable.io -->

2021-03-18 19:44 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2021-03-23 14:06 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/shim_rtld.c, line 192 at r11](https://reviewable.io/reviews/oscarlab/graphene/2231#-MWUMfOx7L-yv95qHOzm:-MWUMfOx7L-yv95qHOzn:b-wewn79) ([raw file](https://github.com/oscarlab/graphene/blob/2dae987cc097aa6762060a411ae885855f47f709/LibOS/shim/src/shim_rtld.c#L192)):*
> ```C
>     struct loadcmd* c = *loadcmds;
>     const ElfW(Phdr)* ph_prev = NULL;
>     for (ph = phdr; ph < &phdr[phnum]; ph++)
> ```

nitpick: braces for "for" per graphene style.


<!-- Sent from Reviewable.io -->

2021-03-23 14:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/shim_rtld.c, line 192 at r11](https://reviewable.io/reviews/oscarlab/graphene/2231#-MWUMfOx7L-yv95qHOzm:-MWUTZ3H6G5FfAkh_rRN:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/2dae987cc097aa6762060a411ae885855f47f709/LibOS/shim/src/shim_rtld.c#L192)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

nitpick: braces for "for" per graphene style.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-03-23 14:41 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-23 14:43 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-23 14:53 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2231)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-23 15:24 UTC, merged