[Pal] Clean up unix_to_pal_error()
oscarlab/graphene pull request #2234
Opened 2021-03-12 21:14 UTC by mkow

## Description of the changes 

A split-off from #2232. I decided to get rid of `ERRNO()` and `IS_ERR()` macros altogether, after making `unix_to_pal_error()` more intuitive (i.e. preserving the sign, not flipping it) the code looks much simpler without these macros.

This change is based on assumption that Linux always returns errors as "-error_code" on all archs (not e.g. with a bitmask or something similar), which I think is true.

## How to test this PR? 

CI.

2021-03-12 21:15 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: 0 of 46 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux-SGX/db_mutex.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcHmCU0JAxIv90FP9t:-MVcHmCU0JAxIv90FP9u:b-db4ay5) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/db_mutex.c#L73)):*
> ```C
> 
>         if (ret < 0) {
>             if (ret == -EWOULDBLOCK) {
> ```

FYI: this was a bug


<!-- Sent from Reviewable.io -->

2021-03-12 22:34 UTC, boryspoplawski requested changes
> Reviewed 46 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcY8TEDmWGj8qF5FQE:-MVcY8TFBajvzEXfvfN2:b-qltw3x) (no related file):*
Please remove `IS_ERR` and `ERRNO` from `Pal/src/host/Linux/pal_linux.h`.

---
___
*[Pal/src/host/Linux/db_misc.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcQZBc02MfkYlsFUhs:-MVcQZBc02MfkYlsFUht:b-q99sku) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_misc.c#L31)):*
> ```C
> 
>     if (ret < 0)
>         return ret;
> ```

Don't we miss a `unix_to_pal_error` here?
___
*[Pal/src/host/Linux/db_process.c, line 289 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcRNws4bgEARjcnnQJ:-MVcRNws4bgEARjcnnQK:b-6mnr6) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_process.c#L289)):*
> ```C
>     long bytes = INLINE_SYSCALL(read, 3, parent_pipe_fd, &proc_args, sizeof(proc_args));
>     if (bytes < 0 || bytes != sizeof(proc_args)) {
>         int err = bytes < 0 ? unix_to_pal_error(bytes) : PAL_ERROR_INTERRUPTED;
> ```

Signs are mixed here.
___
*[Pal/src/host/Linux/db_process.c, line 379 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcRfDbCANBsAjZUM5y:-MVcRfDbCANBsAjZUM5z:btjo3vg) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_process.c#L379)):*
> ```C
>         }
> 
>     assert(bytes >= 0);
> ```

Just remove it please...
___
*[Pal/src/host/Linux/db_sockets.c, line 332 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcS-IT1r454bbQdsYj:-MVcS-IT1r454bbQdsYk:b-enac4h) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_sockets.c#L332)):*
> ```C
> 
>     /* call getsockname to get socket address */
>     if ((ret = INLINE_SYSCALL(getsockname, 3, fd, bind_addr, &bind_addrlen)) < 0)
> ```

We lack `unix_to_pal_error` here.
(unrelated to PR)
___
*[Pal/src/host/Linux/db_sockets.c, line 441 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcSDWS8HC04gmvw8zU:-MVcSDWT-8UVI44LSIzJ:bym0nh2) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_sockets.c#L441)):*
> ```C
>     ret = INLINE_SYSCALL(connect, 3, fd, dest_addr, dest_addrlen);
> 
>     if (ret < 0 && ret == -EINPROGRESS) {
> ```

You can remove `ret < 0` from condition.
___
*[Pal/src/host/Linux/db_threading.c, line 131 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcTFVT00_s6A6MVHxs:-MVcTFVT00_s6A6MVHxt:bbd0em6) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_threading.c#L131)):*
> ```C
>     void* stack = get_thread_stack();
>     if (!stack) {
>         ret = -ENOMEM;
> ```

Please change to pal error code.
___
*[Pal/src/host/Linux/db_threading.c, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcTKsICzGassthvR5n:-MVcTKsICzGassthvR5o:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_threading.c#L156)):*
> ```C
>     hdl = malloc(HANDLE_SIZE(thread));
>     if (!hdl) {
>         ret = -ENOMEM;
> ```

ditto
___
*[Pal/src/host/Linux/pal_linux_error.h, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcXnVG9W6oGm6FrERL:-MVcXnVG9W6oGm6FrERM:b25scn) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/pal_linux_error.h#L11)):*
> ```objc
> #include "pal_error.h"
> 
> static int unix_to_pal_error_positive(int unix_errno) {
> ```

Why this has no `inline` but the below has?
___
*[Pal/src/host/Linux-SGX/db_mutex.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcHmCU0JAxIv90FP9t:-MVcUWtj4vtNh1mLMpNa:b-uifjy0) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/db_mutex.c#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: this was a bug
</blockquote></details>

What was the bug?
___
*[Pal/src/host/Linux-SGX/pal_linux_error.h, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcXXMfDlijNA4kuX6l:-MVcXXMg5w52H7IptOWT:b25scn) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/pal_linux_error.h#L11)):*
> ```objc
> #include "pal_error.h"
> 
> static int unix_to_pal_error_positive(int unix_errno) {
> ```

Why this has no `inline` but the below has?
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 448 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYNrhBOp6QXAf6YJN:-MVcYNrhBOp6QXAf6YJO:b-6zes1r) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L448)):*
> ```C
>         ret = INLINE_SYSCALL(connect, 3, fd, ms->ms_addr, ms->ms_addrlen);
> 
>         if (ret < 0 && ret == -EINPROGRESS) {
> ```

You can remove `ret < 0`.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 456 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYRVX2lnUvmDZafvC:-MVcYRVX2lnUvmDZafvD:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L456)):*
> ```C
>                 };
>                 ret = INLINE_SYSCALL(ppoll, 4, &pfd, 1, NULL, NULL);
>             } while (ret < 0 && ret == -EWOULDBLOCK);
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 599 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYV3J1bEsRVAz4tYl:-MVcYV3J1bEsRVAz4tYm:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L599)):*
> ```C
> 
>     ret = INLINE_SYSCALL(nanosleep, 2, &req, &rem);
>     if (ret < 0 && ret == -EINTR)
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 633 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYWIs0v381HnhxIYp:-MVcYWIs0v381HnhxIYq:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L633)):*
> ```C
>     ret = INLINE_SYSCALL(unlink, 1, ms->ms_pathname);
> 
>     if (ret < 0 && ret == -EISDIR)
> ```

ditto
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 502 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcZ9xI-urFcSNof8RT:-MVcZ9xI-urFcSNof8RU:bmhpna4) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_main.c#L502)):*
> ```C
>         enclave_mem = INLINE_SYSCALL(open, 3, "/proc/self/mem", O_RDWR | O_LARGEFILE, 0);
>         if (enclave_mem < 0) {
>             urts_log_error("Setting TCS.FLAGS.DBGOPTIN failed: %d\n", -enclave_mem);
> ```

Shouldn't we set `ret` to some error here?
___
*[Pal/src/host/Linux-SGX/sgx_profile.c, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcZ_d-DXlTFCNNfuCF:-MVcZ_d-DXlTFCNNfuCG:bi3sfv1) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_profile.c#L50)):*
> ```C
>                              (off_t)addr + total);
> 
>         if (ret < 0 && ret == -EINTR)
> ```

You can remove `ret < 0`


<!-- Sent from Reviewable.io -->

2021-03-13 00:07 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: 39 of 47 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcY8TEDmWGj8qF5FQE:-MVclc-G2nd22QSUPo9S:b-ovmx62) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove `IS_ERR` and `ERRNO` from `Pal/src/host/Linux/pal_linux.h`.
</blockquote></details>

Heh, I did this (I grepped the whole code before submitting this PR), but had this file opened in an unsaved editor tab. Fixed now by pressing ctrl+s first :)

---
___
*[Pal/src/host/Linux/db_misc.c, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcQZBc02MfkYlsFUhs:-MVcm03_5KsK3Ru12u4-:b-purkrr) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_misc.c#L31)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Don't we miss a `unix_to_pal_error` here?
</blockquote></details>

Yeah, I think so. Fixed.
___
*[Pal/src/host/Linux/db_process.c, line 289 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcRNws4bgEARjcnnQJ:-MVcnRZ_95mJxi1pne2g:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_process.c#L289)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Signs are mixed here.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_process.c, line 379 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcRfDbCANBsAjZUM5y:-MVcnYYi6cpu8RbtlDNt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_process.c#L379)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Just remove it please...
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_sockets.c, line 332 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcS-IT1r454bbQdsYj:-MVco2zS5SmNzFSAjuuK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_sockets.c#L332)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We lack `unix_to_pal_error` here.
(unrelated to PR)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_sockets.c, line 441 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcSDWS8HC04gmvw8zU:-MVcoN0f7NL7dCBBMeQH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_sockets.c#L441)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can remove `ret < 0` from condition.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_threading.c, line 131 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcTFVT00_s6A6MVHxs:-MVcoeEU3RjmmCGwaUgw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_threading.c#L131)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change to pal error code.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_threading.c, line 156 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcTKsICzGassthvR5n:-MVcoecF15joVlKLLQo9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/db_threading.c#L156)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/pal_linux_error.h, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcXnVG9W6oGm6FrERL:-MVcolvn7iQJFNofmLI8:b-9j1o4w) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/pal_linux_error.h#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this has no `inline` but the below has?
</blockquote></details>

Should I remove it from both? I'm fine with both removing and with leaving as is.

This one doesn't have `inline`, because why would it?
___
*[Pal/src/host/Linux-SGX/db_mutex.c, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcHmCU0JAxIv90FP9t:-MVcphYX4EUFR2zNoaCo:b-jvh818) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/db_mutex.c#L73)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What was the bug?
</blockquote></details>

Oops, I pinned this comment under wrong EWOULDBLOCK check -.-
Check out the one in `Pal/src/host/Linux-SGX/sgx_enclave.c`.
___
*[Pal/src/host/Linux-SGX/pal_linux_error.h, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcXXMfDlijNA4kuX6l:-MVcryEQ85reBYPGON2o:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/pal_linux_error.h#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this has no `inline` but the below has?
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 448 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYNrhBOp6QXAf6YJN:-MVcqGw55CtNIV9TFK1S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L448)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You can remove `ret < 0`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 456 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcq02Z1ZLbzmt-4rsP:-MVcq02Z1ZLbzmt-4rsQ:bpoht1h) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L456)):*
> ```C
>                 };
>                 ret = INLINE_SYSCALL(ppoll, 4, &pfd, 1, NULL, NULL);
>             } while (ret < 0 && ret == -EWOULDBLOCK);
> ```

FYI: This was a bug (this time I hope I pinned this comment at the correct line :) )
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 456 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYRVX2lnUvmDZafvC:-MVcqHEo3edJxNNa3kKe:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L456)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 599 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYV3J1bEsRVAz4tYl:-MVcqMgJAedxb0p-RT17:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L599)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 633 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcYWIs0v381HnhxIYp:-MVcqN-c9_C7UQtVkTdx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L633)):*
<details><summary><i>Previously, boryspoplawski (Bo [...]

2021-03-13 01:00 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux/pal_linux_error.h, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcXnVG9W6oGm6FrERL:-MVd4BBfD2nnpOihrVRX:b-80tuzo) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/pal_linux_error.h#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should I remove it from both? I'm fine with both removing and with leaving as is.

This one doesn't have `inline`, because why would it?
</blockquote></details>

The only reason is to be consistent with the rest of the code (which I believe follows convention of `static inline` in headers), putting aside reasons for that.
I don't mind any, do what you want, but do the same thing for both functions in this file :)
___
*[Pal/src/host/Linux-SGX/pal_linux_error.h, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcXXMfDlijNA4kuX6l:-MVd5HFKCi-qEtIENEDe:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/pal_linux_error.h#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 456 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcq02Z1ZLbzmt-4rsP:-MVd4ygq3pNM0TtUeKMc:b-2ls1jd) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux-SGX/sgx_enclave.c#L456)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: This was a bug (this time I hope I pinned this comment at the correct line :) )
</blockquote></details>

Yeah, here it was a bug indeed :)


<!-- Sent from Reviewable.io -->

2021-03-13 01:28 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: 45 of 47 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/pal_linux_error.h, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene/2234#-MVcXnVG9W6oGm6FrERL:-MVdBVh-AecANEyTZCs-:b-wmaney) ([raw file](https://github.com/oscarlab/graphene/blob/b13776895385d4df2723e978df3f309dc7ba3e66/Pal/src/host/Linux/pal_linux_error.h#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The only reason is to be consistent with the rest of the code (which I believe follows convention of `static inline` in headers), putting aside reasons for that.
I don't mind any, do what you want, but do the same thing for both functions in this file :)
</blockquote></details>

Removing it then.


<!-- Sent from Reviewable.io -->

2021-03-13 02:38 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-13 04:55 UTC, yamahata approved these changes
> Reviewed 37 of 46 files at r1, 8 of 8 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-13 14:07 UTC, boryspoplawski approved these changes
> Reviewed 1 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-15 18:06 UTC, yamahata approved these changes
> Reviewed 1 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2234)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-15 18:11 UTC, merged