[Pal] Use WRITE_ONCE instead of READ_ONCE for sgx.preheat_enclave
oscarlab/graphene pull request #2236
Opened 2021-03-13 22:08 UTC by mkow

## Description of the changes 

This is a follow-up to #2191.

Turns out that in benchmarks WRITE_ONCE is strictly faster (by a few percents) than READ_ONCE (both in total runtime and in after-preheat performance). I verified assembly for both versions which were used in benchmarking and they seemed correct (i.e. looked exactly as expected).

I can't explain why writing gives better performance, but let's do what benchmarks say.

Kudos to @jinengandhi-intel for testing on 100 iterations of quite a big workload.

## How to test this PR? 

Use preheat feature and compare performance.

2021-03-24 09:14 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2236)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-24 10:35 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2236)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-24 10:40 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2236)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2236#-MWYoSqW6XG6tbshQt3k:-MWYoSqW6XG6tbshQt3l:bdrnewg) (no related file):*
Didn't we decide to postpone merging this, until more tests are done?

---


<!-- Sent from Reviewable.io -->

2021-06-28 16:30 UTC, mkow commented
Closing this for now, at least until we have conclusive data and some explanation for them. AFAIR in the tests we did the difference wasn't reproducible between machines.

2021-06-28 16:30 UTC, closed without merging