[LibOS] Change `mmap` signature so that the file offset is unsigned
oscarlab/graphene pull request #2244
Opened 2021-03-17 03:06 UTC by boryspoplawski

## Description of the changes 
On Linux `mmap` syscall takes the file offset as `unsigned long`, only the POSIX wrapper has it as `off_t` (which is signed).

Interesting fact: on powerpc the syscall signature has `off_t`, but then instantly recasts it into `unsigned long` (https://elixir.bootlin.com/linux/v5.11.6/source/arch/powerpc/kernel/syscalls.c#L71).

2021-03-17 12:46 UTC, mkow requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2244)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_handle.h, line 420 at r1](https://reviewable.io/reviews/oscarlab/graphene/2244#-MW-Cat4EQ1qHO9MYvF6:-MW-Cat56S5RAkdELuJW:b-8jq60s) ([raw file](https://github.com/oscarlab/graphene/blob/d83540630fd6582bdba8e9df9b17d46b106a1e90/LibOS/shim/include/shim_handle.h#L420)):*
> ```objc
> int init_important_handles(void);
> 
> int get_file_size(struct shim_handle* file, size_t* size);
> ```

Shouldn't we stay with `off_t` internally? And just drop to wrong types on the syscall layer? With `size_t` large files will break on 32-bit.


<!-- Sent from Reviewable.io -->

2021-03-17 14:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2244)* status: 2 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_handle.h, line 420 at r1](https://reviewable.io/reviews/oscarlab/graphene/2244#-MW-Cat4EQ1qHO9MYvF6:-MW-bsBh0kyvZpd9UHSR:bmfpui7) ([raw file](https://github.com/oscarlab/graphene/blob/d83540630fd6582bdba8e9df9b17d46b106a1e90/LibOS/shim/include/shim_handle.h#L420)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we stay with `off_t` internally? And just drop to wrong types on the syscall layer? With `size_t` large files will break on 32-bit.
</blockquote></details>

Good point, but I've changed to `uint64_t` (`off_t` is signed and on i386 it's 32bit, I think).


<!-- Sent from Reviewable.io -->

2021-03-17 15:12 UTC, mkow approved these changes
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2244)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_handle.h, line 420 at r1](https://reviewable.io/reviews/oscarlab/graphene/2244#-MW-Cat4EQ1qHO9MYvF6:-MW-iTmK5kMe0WW48R8h:bpzrp2p) ([raw file](https://github.com/oscarlab/graphene/blob/d83540630fd6582bdba8e9df9b17d46b106a1e90/LibOS/shim/include/shim_handle.h#L420)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Good point, but I've changed to `uint64_t` (`off_t` is signed and on i386 it's 32bit, I think).
</blockquote></details>

`uint64_t` sounds good. We even have it in our coding guidelines :)


<!-- Sent from Reviewable.io -->

2021-03-17 15:29 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX please (`udp` from LibOS regresison failed, cannot reproduce locally, probably spurious EINTR)

2021-03-18 06:52 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 8 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2244)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-18 11:56 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2244)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-18 14:28 UTC, yamahata approved these changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2244)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-18 15:33 UTC, merged