CI: fix problems with too new BIOS+microcode
oscarlab/graphene pull request #2258
Opened 2021-03-19 23:41 UTC by woju

## Description of the changes 

In `Examples/ra-tls-mbedtls` IAS API reports quote status, and on CI machines this was always `GROUP_OUT_OF_DATE`, because, well, BIOS and/or microcode is out of date on those. But recently we've got some new machines, one among them is surprisingly updated and for this machine another error, `CONFIGURATION_AND_SW_HARDENING_NEEDED` is returned instead, which confuses our tooling. This PR makes the attestation code to ignore also this problem.

An `ias.py` python module and `graphene-ias-query` tool, which aided debugging this problem, are included. This was necessary to write, as the existing tools in `Pal/**/Linux-SGX/tools` use IAS API v3, and I needed v4 API.

## How to test this PR? 

For this PR only, the problematic CI pipeline was pinned to the machine in question, which for now only serves for this PR. The 18.04-sgx-apps pipeline should pass. Before merging (maybe as part of final rebase) the commit with pinning should be dropped. After merging this PR the Jenkins node will be made available for all SGX pipelines, and possibly all other SGX nodes will be brought up-to-date.

`ias.py` tool lacks tests, because it's complicated to provoke every possible IAS response. It would require multiple carefully setup boxen, each with it's own bespoke set of problems. Please review thoroughly.

2021-03-22 13:36 UTC, mkow requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWOxmjb301Ci7dQZHEE:-MWOxmjb301Ci7dQZHEF:b-kfu8t0) (no related file):*
> Maybe, just maybe, someday we'll run the CI on actually secure machines.

I'd drop this sentence, it sounds like:
a) Current CI machines are insecure (which isn't true, they're just too old for SGX, but otherwise are fine).
b) It's a problem we should fix (in fact it doesn't matter for our tests).

---
___
*[Documentation/conf.py, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWOzlw8230yIbcsN_jd:-MWOzlw8230yIbcsN_je:b-8gatal) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/conf.py#L154)):*
> ```Python
>     ('manpages/ias_request', 'ias_request', 'Submit Intel Attestation Service request', [author], 1),
>     ('manpages/verify_ias_report', 'verify_ias_report', 'Verify Intel Attestation Service report', [author], 1),
>     ('manpages/graphene-ias-query', 'graphene-ias-query', 'Query Intel Attestation Service API', [author], 1),
> ```

How does this relate to `ias_request`? Sounds like both did the same thing.
Also, other tools have a different naming convention, please unify them one way or another.
___
*[Documentation/manpages/graphene-ias-query.rst, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWP0IdQ9pNoj1QXsu5n:-MWP0IdQ9pNoj1QXsu5o:bqlxvkv) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/manpages/graphene-ias-query.rst#L19)):*
> ```reStructuredText
> signature checking is performed.
> 
> The quote is to be provided as hex-encoded *FILE* (``-`` means standard input).
> ```

Why such a weird format, instead of just a quote saved raw in a file?
___
*[python/graphenelibos/ias.py, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWP3fHVANg5XNnEcT-X:-MWP3fHVANg5XNnEcT-Y:btirql) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/python/graphenelibos/ias.py#L6)):*
> ```Python
> Tools for querying IAS v4 API.
> 
> .. seealso::
> ```

Is this actually parsed by anything as reST?


<!-- Sent from Reviewable.io -->

2021-03-22 13:57 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWOxmjb301Ci7dQZHEE:-MWPAIPH0o96jNKmYWbZ:b-xwofar) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Maybe, just maybe, someday we'll run the CI on actually secure machines.

I'd drop this sentence, it sounds like:
a) Current CI machines are insecure (which isn't true, they're just too old for SGX, but otherwise are fine).
b) It's a problem we should fix (in fact it doesn't matter for our tests).
</blockquote></details>

Wilco.

---
___
*[Documentation/conf.py, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWOzlw8230yIbcsN_jd:-MWPAL81-xF6Z9G6-uFS:b-nbdsba) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/conf.py#L154)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How does this relate to `ias_request`? Sounds like both did the same thing.
Also, other tools have a different naming convention, please unify them one way or another.
</blockquote></details>

`ias_request` uses v3 API and this thing does v4. As of now v3 API is undocumented (the official doc, see `ias.py` for a link, describes only v4 API). I rewrote this, because it's easier for me to just write this in Python rather than fix C.

Every tool I add has `graphene-` prefix and uses kebab-case rather than snake_case, because that's preferred in cli (on most Western keyboard layouts you have to press shift for underscore). I can do this to all other tools.
___
*[Documentation/manpages/graphene-ias-query.rst, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWP0IdQ9pNoj1QXsu5n:-MWPBgLG89OkrKW6JXK-:bteeuh7) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/manpages/graphene-ias-query.rst#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why such a weird format, instead of just a quote saved raw in a file?
</blockquote></details>

Because I can't be bothered to think about newlines and it's easy decode hex in Python. Also I have a tool to export the quote as hex, as that was easy to write in C. I recall there was time that graphene did some logging to stdout, so I didn't want to risk problems. Note this was/is quick and dirty hack and misses other critical functionality like checking signature.

If you'd like, I can add `--format={raw,hex,base64,whatever}` if you'd like, just list whatever you need. Also I can add the quote extractor somewhere, probably in `/contrib`.
___
*[python/graphenelibos/ias.py, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWP3fHVANg5XNnEcT-X:-MWP9eXZ9qaCiSZ33tB0:b-yg3luy) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/python/graphenelibos/ias.py#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this actually parsed by anything as reST?
</blockquote></details>

Not now, but in the future, if we'd like to have documentation of Python API on RTD, this would be directly it. https://www.sphinx-doc.org/en/master/usage/quickstart.html#autodoc https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-automodule


<!-- Sent from Reviewable.io -->

2021-03-22 15:30 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/conf.py, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWOzlw8230yIbcsN_jd:-MWPWUgW2MiYQAUIcqap:bbbazjw) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/conf.py#L154)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`ias_request` uses v3 API and this thing does v4. As of now v3 API is undocumented (the official doc, see `ias.py` for a link, describes only v4 API). I rewrote this, because it's easier for me to just write this in Python rather than fix C.

Every tool I add has `graphene-` prefix and uses kebab-case rather than snake_case, because that's preferred in cli (on most Western keyboard layouts you have to press shift for underscore). I can do this to all other tools.
</blockquote></details>

Ok, could you convert other tools names then? Preferably as a separate PR.

Ad v3 vs v4: My issue is that now the documentation is highly confusing - you basically see 2 entries in manpages with synonymous names, almost identical descriptions etc.
___
*[Documentation/manpages/graphene-ias-query.rst, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWP0IdQ9pNoj1QXsu5n:-MWPXNEO-3S9mdGmo5qO:b9g2vtq) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/manpages/graphene-ias-query.rst#L19)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because I can't be bothered to think about newlines and it's easy decode hex in Python. Also I have a tool to export the quote as hex, as that was easy to write in C. I recall there was time that graphene did some logging to stdout, so I didn't want to risk problems. Note this was/is quick and dirty hack and misses other critical functionality like checking signature.

If you'd like, I can add `--format={raw,hex,base64,whatever}` if you'd like, just list whatever you need. Also I can add the quote extractor somewhere, probably in `/contrib`.
</blockquote></details>

Please add the `--format` then, and default to `raw`.

Ad quote extractor: What exactly it does? And how does it relate to other tools we already have? I just don't want to make this whole tools collection a mess.


<!-- Sent from Reviewable.io -->

2021-03-22 16:39 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/manpages/graphene-ias-query.rst, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWP0IdQ9pNoj1QXsu5n:-MWPn43-960C14MPTiPg:b1wonwl) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/manpages/graphene-ias-query.rst#L19)):*
> I'm only interested in the quote, so If I could, I'd write SDK-based .so to skip graphene entirely and instead I'd include that in https://github.com/woju/prometheus-sgx-exporter. I don't think I have time for that, but it would be a nice to be able to monitor this in our CI farm.

Sounds good.


<!-- Sent from Reviewable.io -->

2021-03-22 21:14 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWOxmjb301Ci7dQZHEE:-MWQmMu4-ZiWZBi6G5sU:b-896fix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Wilco.
</blockquote></details>

Done.

---
___
*[Documentation/conf.py, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWOzlw8230yIbcsN_jd:-MWPdrvB0f3vlCGlIvl7:b4fz6b3) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/conf.py#L154)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, could you convert other tools names then? Preferably as a separate PR.

Ad v3 vs v4: My issue is that now the documentation is highly confusing - you basically see 2 entries in manpages with synonymous names, almost identical descriptions etc.
</blockquote></details>

https://github.com/oscarlab/graphene/issues/895#issuecomment-804390603

I propose to retire the previous tool (#2262), because 1) it uses obsolete API; 2) it doesn't need to be written in C (Python is enough).

For clarity I added "v3" and "v4" to manpages.
___
*[Documentation/manpages/graphene-ias-query.rst, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWP0IdQ9pNoj1QXsu5n:-MWQltM26uTbftOcZ1L5:by3kg7x) ([raw file](https://github.com/oscarlab/graphene/blob/16025d05a507323274f596668ba7996f0f68ca40/Documentation/manpages/graphene-ias-query.rst#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I'm only interested in the quote, so If I could, I'd write SDK-based .so to skip graphene entirely and instead I'd include that in https://github.com/woju/prometheus-sgx-exporter. I don't think I have time for that, but it would be a nice to be able to monitor this in our CI farm.

Sounds good.
</blockquote></details>

Done (`--format`).


<!-- Sent from Reviewable.io -->

2021-03-22 23:30 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[python/graphenelibos/ias.py, line 111 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWRGIFnAHZHTkFTkl5z:-MWRGIFnAHZHTkFTkl6-:b38i4h6) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/python/graphenelibos/ias.py#L111)):*
> ```
> the quote from the FILE
> ```

Not `a quote from FILE`?


<!-- Sent from Reviewable.io -->

2021-03-23 18:33 UTC, dimakuv requested changes
> Reviewed 8 of 11 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV-tjsC8Sv3j4VJJ7i:-MWV-tjsC8Sv3j4VJJ7j:boq8fb) (no related file):*
The new tool is written in Python and can be exposed as a Python API.

The older tools are written in C and are stand-alone programs (though some of their functionality is exposed as a C API).

How do we want to proceed with this? Is this new tool just a quick hack? Or is the plan to move all programs around Graphene to Python? (For the latter, we still need to keep some core functionality in C because Graphene internals use them.)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV2bPrATVRKh4hjrdS:-MWV2bPs5KX95sHuqHPD:b-jgaoxm) (no related file):*
There are some more files to fix (only in the comments section):
- https://github.com/oscarlab/graphene/blob/73b774f5ebee56185b03f98bee81e0dd62fab9db/Pal/src/host/Linux-SGX/tools/common/attestation.h#L39
- https://github.com/oscarlab/graphene/blob/73b774f5ebee56185b03f98bee81e0dd62fab9db/Pal/src/host/Linux-SGX/tools/common/attestation.h#L71

Please add the new status messages into these comments.

---
___
*[Documentation/conf.py, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV0wVX4ClsGvgLB32W:-MWV0wVX4ClsGvgLB32X:b39ag8e) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/conf.py#L152)):*
> ```Python
>     ('manpages/is_sgx_available', 'is_sgx_available', 'Check SGX compatibility', [author], 1),
>     ('manpages/quote_dump', 'quote_dump', 'Display SGX quote', [author], 1),
>     ('manpages/ias_request', 'ias_request', 'Submit Intel Attestation Service v3 request', [author], 1),
> ```

The old `ias_request` and the new `graphene-ias-query` do roughly the same stuff -- send the SGX quote and receive the SGX attestation report. Why do we have very different names for them and different descriptions?
___
*[Documentation/conf.py, line 153 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV1E55-ts2Z4tDYyyO:-MWV1E55-ts2Z4tDYyyP:b-k80fyy) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/conf.py#L153)):*
> ```Python
>     ('manpages/quote_dump', 'quote_dump', 'Display SGX quote', [author], 1),
>     ('manpages/ias_request', 'ias_request', 'Submit Intel Attestation Service v3 request', [author], 1),
>     ('manpages/verify_ias_report', 'verify_ias_report', 'Verify Intel Attestation Service report', [author], 1),
> ```

We don't have a v4 counter-part for this old program. Is this because you just wanted to commit your quick-and-dirty `graphene-ias-query` tool?

Given all the above questions, maybe we move this `graphene-is-query` tool to a separate PR? I really don't like that we have such a hacky tool in this PR.
___
*[Documentation/manpages/graphene-ias-query.rst, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWUz03eBkTAz2P6tKZY:-MWUz03eBkTAz2P6tKZZ:b-ozuh9y) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/manpages/graphene-ias-query.rst#L4)):*
> ```reStructuredText
> 
> ============================================================================
> :program:`graphene-ias-query` -- Submit Intel Attestation Service v4 request
> ```

Shouldn't the text be `Query Intel Attestation Service API v4`?
___
*[Documentation/manpages/graphene-ias-query.rst, line 54 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV0SZm3jgcilZ6RLzT:-MWV0SZm3jgcilZ6RLzU:b-ufmpv1) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/manpages/graphene-ias-query.rst#L54)):*
> ```reStructuredText
> .. code-block:: python
> 
>    from graphenelibos import ias
> ```

Don't you want to be more specific, like `ias4` or `ias_v4`?
___
*[python/graphenelibos/ias.py, line 76 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWVLTYbAD3HzY9ue_A4:-MWVLTYbAD3HzY9ue_A5:b39etlm) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/python/graphenelibos/ias.py#L76)):*
> ```Python
>             data=data)
> 
> class IAS:
> ```

I would really prefer to have a version in the name, like `IAS_v4`
___
*[python/graphenelibos/ias.py, line 111 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWVL_Fi6dyQ1MmH7qoc:-MWVL_Fi6dyQ1MmH7qod:b-m8xriw) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/python/graphenelibos/ias.py#L111)):*
> ```Python
> def main(key, fmt, nonce, quote):
>     '''
>     Query Intel Attestation Service sending the quote from the FILE.
> ```

Why not just `Send an SGX quote from the FILE to the Intel Attestation Service and get the SGX attestation report back`? But not blocking.


<!-- Sent from Reviewable.io -->

2021-03-24 18:11 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV-tjsC8Sv3j4VJJ7i:-MWYwMCH2tTES8K9aqzu:b-wqy10l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The new tool is written in Python and can be exposed as a Python API.

The older tools are written in C and are stand-alone programs (though some of their functionality is exposed as a C API).

How do we want to proceed with this? Is this new tool just a quick hack? Or is the plan to move all programs around Graphene to Python? (For the latter, we still need to keep some core functionality in C because Graphene internals use them.)
</blockquote></details>

Well, I don't know, probably it depends on the tool in question. Generally I think it would be better to have the tools written in Python for maintainability reasons, if there is no need to have C API. IAS is a simple web API, so unless I miss some need to have C API, I think it doesn't have to be written in C. This particular tool certainly started as a quick hack for debugging one machine only. @mkow asked for it to be included in the PR, so here it is.

---
___
*[Documentation/conf.py, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV0wVX4ClsGvgLB32W:-MW_QVbF9bV0o9b9XQza:b65qvzw) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/conf.py#L152)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The old `ias_request` and the new `graphene-ias-query` do roughly the same stuff -- send the SGX quote and receive the SGX attestation report. Why do we have very different names for them and different descriptions?
</blockquote></details>

Moved to #2268.
___
*[Documentation/conf.py, line 153 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV1E55-ts2Z4tDYyyO:-MWZ0wWQ0Xg8oRBYa69N:b-4cpxek) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/conf.py#L153)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't have a v4 counter-part for this old program. Is this because you just wanted to commit your quick-and-dirty `graphene-ias-query` tool?

Given all the above questions, maybe we move this `graphene-is-query` tool to a separate PR? I really don't like that we have such a hacky tool in this PR.
</blockquote></details>

@mkow asked for the tool to be included here, but I'm sure it can go to another PR: #2268.

In principle, yes, I just wanted to commit and didn't dwell too much on it.
___
*[Documentation/manpages/graphene-ias-query.rst, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWUz03eBkTAz2P6tKZY:-MW_NBwG6u6mNlLT4HKz:bu0u1hv) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/manpages/graphene-ias-query.rst#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't the text be `Query Intel Attestation Service API v4`?
</blockquote></details>

Fixed in #2268.
___
*[Documentation/manpages/graphene-ias-query.rst, line 54 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV0SZm3jgcilZ6RLzT:-MWZ1Db357k0XJZqmDpl:b38snu0) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/Documentation/manpages/graphene-ias-query.rst#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to be more specific, like `ias4` or `ias_v4`?
</blockquote></details>

`ias.APIv4` is a good advice, but when/if `APIv5` comes I'd like to have it in a single module and have a switch (`-4/-5`? `--api={v4,v4-dev,v5,v5-dev}`?) in the same CLI tool.
___
*[python/graphenelibos/ias.py, line 76 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWVLTYbAD3HzY9ue_A4:-MWZ1RTuBeeencqjWSts:b427xzf) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/python/graphenelibos/ias.py#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would really prefer to have a version in the name, like `IAS_v4`
</blockquote></details>

Done in #2268.
___
*[python/graphenelibos/ias.py, line 111 at r2](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWVL_Fi6dyQ1MmH7qoc:-MW_Qizq6C5dYCmu29xp:b427xzf) ([raw file](https://github.com/oscarlab/graphene/blob/f1f158d6704709f02a827b29551d103022c4adf7/python/graphenelibos/ias.py#L111)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just `Send an SGX quote from the FILE to the Intel Attestation Service and get the SGX attestation report back`? But not blocking.
</blockquote></details>

Done in #2268.


<!-- Sent from Reviewable.io -->

2021-03-24 18:15 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: 4 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV2bPrATVRKh4hjrdS:-MW_Rc2v42ScKUtliFhg:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There are some more files to fix (only in the comments section):
- https://github.com/oscarlab/graphene/blob/73b774f5ebee56185b03f98bee81e0dd62fab9db/Pal/src/host/Linux-SGX/tools/common/attestation.h#L39
- https://github.com/oscarlab/graphene/blob/73b774f5ebee56185b03f98bee81e0dd62fab9db/Pal/src/host/Linux-SGX/tools/common/attestation.h#L71

Please add the new status messages into these comments.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-03-24 21:38 UTC, mkow submitted a review, later dismissed
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DO NOT MERGE" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV-tjsC8Sv3j4VJJ7i:-MW_qwquAjM7LFBrBMtT:bun5uo7) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Well, I don't know, probably it depends on the tool in question. Generally I think it would be better to have the tools written in Python for maintainability reasons, if there is no need to have C API. IAS is a simple web API, so unless I miss some need to have C API, I think it doesn't have to be written in C. This particular tool certainly started as a quick hack for debugging one machine only. @mkow asked for it to be included in the PR, so here it is.
</blockquote></details>

I think there's no reason to keep them in C, but I may be missing something.

---


<!-- Sent from Reviewable.io -->

2021-03-25 07:39 UTC, dimakuv approved these changes
> Reviewed 4 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, all discussions resolved, "DO NOT MERGE" and "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2258#-MWV-tjsC8Sv3j4VJJ7i:-MWcIrIWE8euA1_6gNjG:bliudne) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think there's no reason to keep them in C, but I may be missing something.
</blockquote></details>

Yes, some of these tools don't need to be written in C (`ias_request` and `quote_dump` for sure). I have no objections in re-writing them in Python. Anyway, resolving.

---


<!-- Sent from Reviewable.io -->

2021-03-25 13:27 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-25 13:32 UTC, mkow approved these changes
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-25 13:41 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2258)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-25 15:02 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (`udp` LibOS test failed, unrelated)

2021-03-25 15:38 UTC, merged