Change file type of /proc/self/exe from DIRECTORY to SYMLINK.
oscarlab/graphene pull request #2259
Opened 2021-03-21 16:05 UTC by aneessahib

Signed-off-by: aneessahib <anees.a.sahib@intel.com>

The problem with returning file type as DIRECTORY for proc/self/exe is that when certain apps (eg Dotnet) attempts to locate other binaries relative to its executable path, the path resolves to "/proc/self/<binary>". In this fix, the type is returned as SYMLINK, and hence the path to binary that the application seeks resolves to "/<binary". Support to resolve the links (readlink) to the exact paths are already present, hence no further code is needed to support the LINK status of exe. Furthermore, the pseudo entry for the same is also defined as LINUX_DT_LNK. The fix added also applies to other links within proc/self such as "cwd" and "root" for consistency.

2021-03-21 16:20 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWKZbUBBWZyor76S7o6:-MWKZbUBBWZyor76S7o7:b982vj5) (no related file):*
Please add `[LibOS]` component tag to the commit message (you can force-push afterwards).

---
___
*[LibOS/shim/src/fs/proc/thread.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWK_CP_A2qTxjrjRHNC:-MWK_CP_A2qTxjrjRHND:bbufv93) ([raw file](https://github.com/oscarlab/graphene/blob/71751c7457218f57b7795f50d84c2b315e951d51/LibOS/shim/src/fs/proc/thread.c#L178)):*
> ```C
> 
>     __UNUSED(name);
>     __UNUSED(dent);
> ```

Why not just delete it then? :)
___
*[LibOS/shim/src/fs/proc/thread.c, line 179 at r1](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWK_6IV4q2c1aEDsn8z:-MWK_6IW6jxkdhppQYD6:b-d4ui68) ([raw file](https://github.com/oscarlab/graphene/blob/71751c7457218f57b7795f50d84c2b315e951d51/LibOS/shim/src/fs/proc/thread.c#L179)):*
> ```C
>     __UNUSED(name);
>     __UNUSED(dent);
>     memset(buf, 0, sizeof(struct stat));
> ```

`sizeof(struct stat)` -> `sizeof(*buf)`
___
*[LibOS/shim/src/fs/proc/thread.c, line 188 at r1](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWK_G0E-REW_L_WlVRR:-MWK_G0E-REW_L_WlVRS:be2jgdl) ([raw file](https://github.com/oscarlab/graphene/blob/71751c7457218f57b7795f50d84c2b315e951d51/LibOS/shim/src/fs/proc/thread.c#L188)):*
> ```C
> 
>     return 0;
>     
> ```

trailing blanks (you can just remove this whole line)


<!-- Sent from Reviewable.io -->

2021-03-21 16:20 UTC, mkow reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2021-03-21 17:20 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWKZbUBBWZyor76S7o6:-MWKn8AzBbAJ1VnbaVrN:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add `[LibOS]` component tag to the commit message (you can force-push afterwards).
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/fs/proc/thread.c, line 178 at r1](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWK_CP_A2qTxjrjRHNC:-MWKnCSr940GZ6XHZQG_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/71751c7457218f57b7795f50d84c2b315e951d51/LibOS/shim/src/fs/proc/thread.c#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not just delete it then? :)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 179 at r1](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWK_6IV4q2c1aEDsn8z:-MWKnCpH2Mxm7WITfBz0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/71751c7457218f57b7795f50d84c2b315e951d51/LibOS/shim/src/fs/proc/thread.c#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`sizeof(struct stat)` -> `sizeof(*buf)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/thread.c, line 188 at r1](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWK_G0E-REW_L_WlVRR:-MWKnDYxCuMGpueqCiry:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/71751c7457218f57b7795f50d84c2b315e951d51/LibOS/shim/src/fs/proc/thread.c#L188)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

trailing blanks (you can just remove this whole line)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-21 22:15 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWKZbUBBWZyor76S7o6:-MWLqaXN22MV94d8j8jt:b-iebgr4) (no related file):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, one more thing I missed: no period at the end of the one liner.

---
___
*[LibOS/shim/src/fs/proc/thread.c, line 188 at r1](https://reviewable.io/reviews/oscarlab/graphene/2259#-MWK_G0E-REW_L_WlVRR:-MWLqjzmDLYT2X8VVyqz:b8g5mg4) ([raw file](https://github.com/oscarlab/graphene/blob/71751c7457218f57b7795f50d84c2b315e951d51/LibOS/shim/src/fs/proc/thread.c#L188)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now you have a trailing space after `;`.


<!-- Sent from Reviewable.io -->

2021-03-22 12:13 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-22 15:43 UTC, mkow commented
Jenkins, test this please

2021-03-22 21:58 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (kill11 from LTP failed, known issue)

2021-03-24 09:10 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-03-24 17:11 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-24 17:33 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-24 17:34 UTC, mkow commented
Jenkins, retest this please

2021-03-24 17:36 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-24 17:58 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2259)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-24 18:16 UTC, merged