Draft: Sync engine
oscarlab/graphene pull request #2267
Opened 2021-03-24 10:46 UTC by pwmarcz

## Description of the changes 

## How to test this PR?

2021-03-25 12:24 UTC, dimakuv reviewed
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[Examples/python-simple/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcujXK89hEqluC_gOW:-MWcujXK89hEqluC_gOX:bq8yhk7) ([raw file](https://github.com/oscarlab/graphene/blob/9d16647026b035a7c026b75da266ba23d285d22d/Examples/python-simple/Makefile#L67)):*
> ```Makefile
> 	@grep -q "Success 1/3" TEST_STDOUT
> 	@grep -q "Success 2/3" TEST_STDOUT
> 	@grep -q "Success 3/3" TEST_STDOUT
> ```

This commit should be split in a separate PR.
___
*[LibOS/shim/include/shim_sync.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcz0y0EYDT91i4fodN:-MWcz0y0EYDT91i4fodO:b-5h05en) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L14)):*
> ```objc
>  * - SYNC_STATE_SHARED: many processes can have a copy of the handle
>  * - SYNC_STATE_EXCLUSIVE: only one process can have a copy of the handle, but the data stored
>  *   handle can be updated
> ```

`data stored handle can be updated` -- I can't parse this
___
*[LibOS/shim/include/shim_sync.h, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWczC5o-jfu9CYC7A1q:-MWczC5o-jfu9CYC7A1r:bhwg57u) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L16)):*
> ```objc
>  *   handle can be updated
>  *
>  * When the handle is not locked, it can be downgraded to SYNC_STATE_INVALID by the remote
> ```

I don't understand the point of this. Is this the invalidation mechanism to detect that now there are several processes wanting the same handle?
___
*[LibOS/shim/include/shim_sync.h, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWczjwgERqni_i5NXUV:-MWczjwgERqni_i5NXUW:burmsac) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L34)):*
> ```objc
>  *     // it. After locking, you can read latest data.
>  *     sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE);
>  *     if (obj.sync.data_size == sizeof(obj.field))
> ```

What is this IF? Looks like a way to distinguish among several fields of the handle? This looks brittle.
___
*[LibOS/shim/include/shim_sync.h, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd--Fx4lNFQg0t6ZfK:-MWd--Fx4lNFQg0t6ZfL:b-ol27ye) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L35)):*
> ```objc
>  *     sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE);
>  *     if (obj.sync.data_size == sizeof(obj.field))
>  *         memcpy(&obj.field, obj.sync.buf, sizeof(obj.field);
> ```

Forgot a closing `)` :)
___
*[LibOS/shim/include/shim_sync.h, line 121 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdDUUACK9sUKaNgqsN:-MWdDUUACK9sUKaNgqsO:bf7o1qc) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L121)):*
> ```objc
>     int up_state;
>     /* Requested by server; always lower than cur_state, or NONE */
>     int down_state;
> ```

Can you explain the upgrade/downgrade mechanisms in more detail?
___
*[LibOS/shim/include/shim_sync.h, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd09iYCRAf3ZIHC_mq:-MWd09iYCRAf3ZIHC_mr:b-xw6824) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L134)):*
> ```objc
> 
> /* Initialize and register a sync handle. If `id` is 0, allocate a fresh handle ID.
>  * The handle must have `id` set to 0, for easier lifecycle tracking. */
> ```

I don't understand this sentence. So we always do `id = 0`?
___
*[LibOS/shim/src/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcw4t43C3sgWactDCn:-MWcw4t520ktT4XvuGAs:bzcp783) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/Makefile#L5)):*
> ```Makefile
> include ../../../Scripts/Makefile.configs
> 
> CFLAGS += -fPIC -Winline -Wp,-U_FORTIFY_SOURCE -Wwrite-strings \
> ```

Why exactly do you need this? Could we look at this a bit more? Does it mean that Graphene didn't have any code patterns that would trigger the fortification, and so it was never used anyway?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 475 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcwi2n7yLZ8cFvgGfO:-MWcwi2n7yLZ8cFvgGfP:b26qb0y) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/bookkeep/shim_handle.c#L475)):*
> ```C
>         if ((hdl->type == TYPE_FILE || hdl->type == TYPE_DIR)
>                 && sync_is_open(&hdl->info.file.sync)) {
>             log_debug("collect handle %p\n", hdl);
> ```

What do you mean by "collect"?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcyEKA6G6O4SNaat99:-MWcyEKA6G6O4SNaat9A:bgmmokf) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/fs/chroot/fs.c#L46)):*
> ```C
> 
>     sync_lock(&file->sync, state);
>     if (file->sync.data_size == sizeof(*data)) {
> ```

I don't understand this IF statement. Shouldn't it be assert? Why would `data_size` be something different?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd6Gr95XMo8RVUHUfO:-MWd6Gr95XMo8RVUHUfP:bt0vhcv) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/fs/chroot/fs.c#L667)):*
> ```C
>     }
> 
>     lock(&hdl->lock);
> ```

Why do you have these locks left? These locks look unnecessary now (if we assume that `hdl->pal_handle` doesn't change which should be always true for regular files/dirs).
___
*[LibOS/shim/src/fs/chroot/fs.c, line 668 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd6aOq3RMeXectgnPN:-MWd6aOq3RMeXectgnPO:by1ho2n) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/fs/chroot/fs.c#L668)):*
> ```C
> 
>     lock(&hdl->lock);
>     file_sync_lock(file, SYNC_STATE_EXCLUSIVE);
> ```

Why EXCLUSIVE locks on reads? Shouldn't you have SHARED here?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd6r1f3TXRbFLcuNTc:-MWd6r1f3TXRbFLcuNTd:biqw5up) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/sync/shim_sync_client.c#L34)):*
> ```C
> 
> static inline void lock_client(void) {
>     if (lock_created(&g_client_lock))
> ```

Why IF? Shouldn't it be an assert?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 39 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd6t6pE8Nujj1WmVRG:-MWd6t6pE8Nujj1WmVRH:biqw5up) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/sync/shim_sync_client.c#L39)):*
> ```C
> 
> static inline void unlock_client(void) {
>     if (lock_created(&g_client_lock))
> ```

Why IF? Shouldn't it be an assert?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdDfx4998pOHwDzIh9:-MWdDfx4998pOHwDzIhA:b1sgzan) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/sync/shim_sync_client.c#L61)):*
> ```C
>         FATAL("sending DOWNGRADE");
>     handle->cur_state = handle->down_state;
>     handle->down_state = SYNC_STATE_NONE;
> ```

I understand that you send the DOWNGRA [...]

2021-03-25 15:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 7 of 12 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdwzou3lY35D_Dn8ap:-MWdwzou3lY35D_Dn8aq:b-g0udw6) (no related file):*
@dimakuv Thanks for reading! Do you have any *general* remarks about this engine? I'd love to make this code simpler.

---
___
*[Examples/python-simple/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcujXK89hEqluC_gOW:-MWd_pQTCP1xQYFP9nPK:b-h0jqq8) ([raw file](https://github.com/oscarlab/graphene/blob/9d16647026b035a7c026b75da266ba23d285d22d/Examples/python-simple/Makefile#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This commit should be split in a separate PR.
</blockquote></details>

OK, i'll remove it from here.

(As you can imagine, this failed on me and I found out it throws away all useful output...)
___
*[LibOS/shim/include/shim_sync.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcz0y0EYDT91i4fodN:-MWdaa0j8mkUNvdmx0iI:b2nw7c3) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`data stored handle can be updated` -- I can't parse this
</blockquote></details>

Fixed, should be `data stored with the handle`
___
*[LibOS/shim/include/shim_sync.h, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWczC5o-jfu9CYC7A1q:-MWdagMT7ATceRrgIHC8:b-qp4dtg) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand the point of this. Is this the invalidation mechanism to detect that now there are several processes wanting the same handle?
</blockquote></details>

The invalidation is necessary if another process wants to *modify* the handle (i.e. locks it in EXCLUSIVE mode). Does that make sense? (I reworded the explanation).
___
*[LibOS/shim/include/shim_sync.h, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWczjwgERqni_i5NXUV:-MWdbzVs3vDC-_X8o4FO:b-dubfm2) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this IF? Looks like a way to distinguish among several fields of the handle? This looks brittle.
</blockquote></details>

This is a corner case: for a brand new handle, there is no data associated yet, so `data_size == 0`.

I rewrote the example, is it more clear? I agree it looks somewhat brittle. The idea is that these two operations (lock and read data / write data and unlock) are encapsulated in a set of object-specific functions. See the `file_handle` code for an example of that.
___
*[LibOS/shim/include/shim_sync.h, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd--Fx4lNFQg0t6ZfK:-MWdd62sDsLn-ytvWeox:b-4aqni2) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot a closing `)` :)
</blockquote></details>

I rewrote this.
___
*[LibOS/shim/include/shim_sync.h, line 121 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdDUUACK9sUKaNgqsN:-MWddo2sBcBD_c-ZOjMS:bnrpt5p) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you explain the upgrade/downgrade mechanisms in more detail?
</blockquote></details>

I added a comment to this file explaining the protocol.
___
*[LibOS/shim/include/shim_sync.h, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd09iYCRAf3ZIHC_mq:-MWdimEz-y43khvRJrvd:b-j3xkc) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this sentence. So we always do `id = 0`?
</blockquote></details>

I reworded it to: "Before calling sync_open() on given handle, handle->id must be set to 0, for easier lifecycle tracking".

I did it this way because the object lifecycle in Graphene is very unclear, and we need a way to tell is a given sync handle (`shim_handle.info.file.sync`) is initialized or not.

Maybe I should just make `sync_open` allocate a new object, and `sync_close` free it? This way you would always declare a pointer field: `struct obj { ... struct sync_handle* handle; };`
___
*[LibOS/shim/src/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcw4t43C3sgWactDCn:-MWdjfUh4v53w1P3lzXg:bihm5jb) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/Makefile#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why exactly do you need this? Could we look at this a bit more? Does it mean that Graphene didn't have any code patterns that would trigger the fortification, and so it was never used anyway?
</blockquote></details>

It's explained in the commit that introduces this change: I was getting linker errors on Jenkins complaining about `__memcpy_chk` function. I think it's because I used inluded `uthash.h`, which includes `<stdlib.h>`. However, weirdly, I could not trigger that locally.

`-U_FORTIFY_SOURCE` is used to compile PAL. I dug deeper in Git history and I could not find any explanation. I believe it's due to the use of uthash.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 475 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcwi2n7yLZ8cFvgGfO:-MWdkPqV3Eb3e_ti2Onj:b-2m16qa) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/bookkeep/shim_handle.c#L475)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by "collect"?
</blockquote></details>

That's a debug print, I'm removing it.

(The code kept crashing on me and I was trying to figure out why it doesn't clean up properly. Apparently `hdl->fs->close` is not guaranteed to be called, and that's why it's a no-op.)
___
*[LibOS/shim/src/fs/chroot/fs.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcyEKA6G6O4SNaat99:-MWdlCDCClmP6kVGOEva:b-vg8kev) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/fs/chroot/fs.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this IF statement. Shouldn't it be assert? Why would `data_size` be something different?
</blockquote></details>

As explained above, the size can be 0 if there's no data yet. I changed it to `!= 0` check and assert.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd6Gr95XMo8RVUHUfO:-MWdm4vJ6xwugDCtw1W6:bykbcez) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/fs/chroot/fs.c#L667)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have these locks left? These  [...]

2021-03-26 09:38 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 7 of 12 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdwzou3lY35D_Dn8ap:-MWhsTUO42qMImRCGRIp:b-2gpzbk) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

@dimakuv Thanks for reading! Do you have any *general* remarks about this engine? I'd love to make this code simpler.
</blockquote></details>

Apart from the confusing naming of `DOWNGRADE` and `UPGRADE`, and the two pending states `up_state` and `down_state`, the rest of the code makes sense to me.

As discussed below, it would be nice to merge `up_state` and `down_state` into one `pending_state`. Other than that, I don't see what to simplify here.

---
___
*[LibOS/shim/include/shim_sync.h, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWczC5o-jfu9CYC7A1q:-MWht79sAQBzZvrr2ASo:b-8nhk4s) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/include/shim_sync.h#L16)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The invalidation is necessary if another process wants to *modify* the handle (i.e. locks it in EXCLUSIVE mode). Does that make sense? (I reworded the explanation).
</blockquote></details>

Ok, thanks, now it makes sense.
___
*[LibOS/shim/include/shim_sync.h, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhd3p13yWFo8YKblj7:-MWhd3p13yWFo8YKblj8:b-jxbgvg) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L83)):*
> ```objc
>  *
>  * - DOWNGRADE(id, state, data_size, data): The client confirms downgrade of its own handle, and
>  *   sends the latest data associated with it. This is usually a response to REQUEST_DOWNGRADE.
> ```

Why "usually"? Because the client may also ask for a downgrade when it closes the handle (so on its volition, without the REQUEST_DOWNGRADE from the server)?

Then renaming `DOWNGRADE` to `CONFIRM_DOWNGRADE` will not be correct. But maybe we should use names like `INFORM_DOWNGRADED` and `INFORM_UPGRADED`?
___
*[LibOS/shim/include/shim_sync.h, line 88 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhf1Gn9nTq09kCC0Lw:-MWhf1Gn9nTq09kCC0Lx:bvznvin) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L88)):*
> ```objc
>  *
>  * - UPGRADE(id, state, data_size, data): The server confirms upgrade of a handle to the
>  *   server. This is a response to REQUEST_UPGRADE.
> ```

`to the client`. And `also sends the latest data associated with the handle`, right?
___
*[LibOS/shim/include/shim_sync.h, line 180 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhmtIUC2CbIFwaRLEA:-MWhmtIUC2CbIFwaRLEB:bkjghgc) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L180)):*
> ```objc
>     int up_state;
>     /* Requested by server; always lower than cur_state, or NONE */
>     int down_state;
> ```

Actually, is there a need to have two "pending" states (`up_state` and `down_state`)? Why not just use one state `pending_state`?

On the other hand, I guess you need two states in the following case:
1. Client wants to acquire the lock so it sends a request to up its state to EXCLUSIVE (from say SHARED)
2. Server actually granted EXCLUSIVE lock to someone else, so server sends REQUEST_DOWNGRADE to client
3. Client receives the server's request (via the IPC helper thread) and in the callback, downgrades its current state from SHARED to INVALID (and sends the ack to the server, but that's not important here)
4. Client continues to wait on its EXCLUSIVE request; even if interrupted, the client notices that current state is not yet EXCLUSIVE and the up state is already set to EXCLUSIVE, so the client doesn't need to send the request message again and just continues waiting.

If we wouldn't have two states (`up_state` and `down_state`), it looks like the client would send the request message again to the server.

But on the other hand, so what? The server can simply ignore repeated requests (from the same client for the same handle). And in terms of performance/number of messages, this should be a rare case, because interruptions of `DkSynchronizationObjectWait` shouldn't happen often.

So are there any particular blocks to merging `up_state` and `down_state` into one `pending_state`? This would simplify the logic and will be more intuitive.
___
*[LibOS/shim/src/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcw4t43C3sgWactDCn:-MWhtAgx1Tdg_xCOaoxD:bjg0lcm) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/Makefile#L5)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's explained in the commit that introduces this change: I was getting linker errors on Jenkins complaining about `__memcpy_chk` function. I think it's because I used inluded `uthash.h`, which includes `<stdlib.h>`. However, weirdly, I could not trigger that locally.

`-U_FORTIFY_SOURCE` is used to compile PAL. I dug deeper in Git history and I could not find any explanation. I believe it's due to the use of uthash.
</blockquote></details>

I guess someone will need to check what happens here in a separate effort and submit a separate analysis/PR.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 668 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWd6aOq3RMeXectgnPN:-MWhpvvqCxq5wItQQu-m:bv56fo0) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/fs/chroot/fs.c#L668)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We need an `EXCLUSIVE` lock because we're modifying the data (here, `file->marker`), and also because we don't want anything else to modify it in the meantime.

I guess in some scenarios we could speculatively take a `SHARED` lock, and upgrade it to `EXCLUSIVE` one once we determine that we are changing the data. But here we do need exclusive access from the beginning.

So it seems that `SHARED` locks are not too useful yet, as these functions always try to update the data. I hope the case will be different for dentries...
</blockquote></details>

OK, makes sense.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdDfx4998pOHwDzIh9:-MWhkKYr4Xfwnk_R6k8B:bh1fuy3) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/sync/shim_sync_client.c#L61)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

As a client, it's always safe to downgrade immediately, and then notify the server: if the server thinks that we have *higher* state, nothing bad will happen.

The invariant is that always `client cur_state <= server cur_state`. That's why downgrade changes the state for client first (`DOWNGRADE` message goes from client to server), and upgrade changes the state for server first (`UPGRADE` message goes from server to client).
</blockquote></details>

Ok, thanks. After reading your new explanations on message types and mentally replacing `DOWNGRADE` with `INFORM_DOWNGRADED`, the code is much more understandable.

The current names `DOWNGRADE` and `UPGRADE` are confusing. I like my proposed `INFORM_DOWNGRADED` and `INFORM_UPGRADED` terms (but `CONFIRM_` is also fine).
___
*[LibOS/shim/src/sync/shim_sync_client. [...]

2021-03-26 16:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 7 of 12 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdwzou3lY35D_Dn8ap:-MWjGRyTAagK2R5x3af6:bmbems6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Apart from the confusing naming of `DOWNGRADE` and `UPGRADE`, and the two pending states `up_state` and `down_state`, the rest of the code makes sense to me.

As discussed below, it would be nice to merge `up_state` and `down_state` into one `pending_state`. Other than that, I don't see what to simplify here.
</blockquote></details>

That's good to hear. I'm still worried about stability, @mkow tells me the IPC code is not very reliable right now. But this will be disabled by default and hidden behind a feature flag.

---
___
*[Examples/python-simple/Makefile, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcujXK89hEqluC_gOW:-MWjIZNn41XPioqE0aPk:b3kqr) ([raw file](https://github.com/oscarlab/graphene/blob/9d16647026b035a7c026b75da266ba23d285d22d/Examples/python-simple/Makefile#L67)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, i'll remove it from here.

(As you can imagine, this failed on me and I found out it throws away all useful output...)
</blockquote></details>

(
___
*[LibOS/shim/include/shim_sync.h, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhd3p13yWFo8YKblj7:-MWizJyjCL2FuIuRnl0f:bcr5sqo) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L83)):*
>Why "usually"? Because the client may also ask for a downgrade when it closes the handle (so on its volition, without the REQUEST_DOWNGRADE from the server)?

Yes. And I think that's a hint that open/close (register/unregister?) deserve their own set of messages. The final downgrade/unregister is special, because it needs confirmation from a server. (That might also solve your problem with `CONFIRM_DOWNGRADE`)
___
*[LibOS/shim/include/shim_sync.h, line 88 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhf1Gn9nTq09kCC0Lw:-MWj-bMD2SUgWIM_scMS:bidrs83) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L88)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to the client`. And `also sends the latest data associated with the handle`, right?
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/include/shim_sync.h, line 180 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhmtIUC2CbIFwaRLEA:-MWj-e1G-2QraHoeAqAN:br2tfzl) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, is there a need to have two "pending" states (`up_state` and `down_state`)? Why not just use one state `pending_state`?

On the other hand, I guess you need two states in the following case:
1. Client wants to acquire the lock so it sends a request to up its state to EXCLUSIVE (from say SHARED)
2. Server actually granted EXCLUSIVE lock to someone else, so server sends REQUEST_DOWNGRADE to client
3. Client receives the server's request (via the IPC helper thread) and in the callback, downgrades its current state from SHARED to INVALID (and sends the ack to the server, but that's not important here)
4. Client continues to wait on its EXCLUSIVE request; even if interrupted, the client notices that current state is not yet EXCLUSIVE and the up state is already set to EXCLUSIVE, so the client doesn't need to send the request message again and just continues waiting.

If we wouldn't have two states (`up_state` and `down_state`), it looks like the client would send the request message again to the server.

But on the other hand, so what? The server can simply ignore repeated requests (from the same client for the same handle). And in terms of performance/number of messages, this should be a rare case, because interruptions of `DkSynchronizationObjectWait` shouldn't happen often.

So are there any particular blocks to merging `up_state` and `down_state` into one `pending_state`? This would simplify the logic and will be more intuitive.
</blockquote></details>

Are you talking about the two pending states in here (client code), or server code as well?

Both sides keep two variables: "state requested by remote side" and "state requested by me".

The first is important to track, because otherwise a request would get dropped. I want to keep the invariant that "if one side requested upgrade/downgrade, the other side will grant that request at some moment".

The second is being tracked to prevent repeated requests:

* For the server, I think that preventing repeated requests is important. Let's say there are some clients holding a SHARED handle, and using it for some longer operation (so they will not respond to REQUEST_DOWNGRADE immediately). Then, every new client requesting EXCLUSIVE access will cause the server to resend REQUEST_DOWNGRADE to all these clients.

  (One perspective is that the client gets woken up only on `UPGRADE`, but the server gets woken up on all messages for a given handle).

* For the client, I agree it's not very important yet. There is currently only one thread waiting. However, I'm again thinking about adding conditional waits later: if we have an operation like "request upgrade when `flags & FILE_UNLOCKED != 0`", there would be multiple threads making these requests, and it might be useful to prevent unnecessary requests if one of them is waiting for some rarely-occuring condition. (Then again, maybe that means the notifications should also be conditional, so that they don't wake up all the threads?)

So... for now I think it's better to keep both `up_state` and `down_state`, if only for symmetry between client and server.

Maybe better names for these variables would help? But I couldn't think of good ones: if there's something like `pending_state` and `requested_state`, then it's not clear which side requested what...
___
*[LibOS/shim/src/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcw4t43C3sgWactDCn:-MWjGqAg4UkzIYkBmaHr:bdtihx6) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/Makefile#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess someone will need to check what happens here in a separate effort and submit a separate analysis/PR.
</blockquote></details>

OK, I'll make an issue and/or PR out of it.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 232 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWdGoklBzKiqXDXQ4wZ:-MWjGMQH8zhSMc3pj-uj:b-4mxuh6) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/sync/shim_sync_client.c#L232)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> This is the REQUEST_DOWNGRADE callback.

My bad. But again, the name `DOWNGRADE` is easy to confuse with `REQUEST_DOWNGRADE` (especially in function names like here). Please change to `INFORM_DOWNGRADED` or whatever you prefer.

Everything makes sense now.
</blockquote></details>

OK, it's clear the messages should be renamed.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhpLQ48M9EQv_ppfqt:-MWjF7bACG09vu15OqvI:b4cloba) ([r [...]

2021-03-29 07:43 UTC, dimakuv reviewed
> Reviewed 4 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_sync.h, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhd3p13yWFo8YKblj7:-MWwvxJx1yFUWdHPw9ly:b-8hwbvo) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L83)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Why "usually"? Because the client may also ask for a downgrade when it closes the handle (so on its volition, without the REQUEST_DOWNGRADE from the server)?

Yes. And I think that's a hint that open/close (register/unregister?) deserve their own set of messages. The final downgrade/unregister is special, because it needs confirmation from a server. (That might also solve your problem with `CONFIRM_DOWNGRADE`)
</blockquote></details>

Do we need additional messages? I would be fine with these 4 messages, just better names.
___
*[LibOS/shim/include/shim_sync.h, line 180 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhmtIUC2CbIFwaRLEA:-MWwvHG42ewARtGFQISI:b-ftltok) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L180)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Are you talking about the two pending states in here (client code), or server code as well?

Both sides keep two variables: "state requested by remote side" and "state requested by me".

The first is important to track, because otherwise a request would get dropped. I want to keep the invariant that "if one side requested upgrade/downgrade, the other side will grant that request at some moment".

The second is being tracked to prevent repeated requests:

* For the server, I think that preventing repeated requests is important. Let's say there are some clients holding a SHARED handle, and using it for some longer operation (so they will not respond to REQUEST_DOWNGRADE immediately). Then, every new client requesting EXCLUSIVE access will cause the server to resend REQUEST_DOWNGRADE to all these clients.

  (One perspective is that the client gets woken up only on `UPGRADE`, but the server gets woken up on all messages for a given handle).

* For the client, I agree it's not very important yet. There is currently only one thread waiting. However, I'm again thinking about adding conditional waits later: if we have an operation like "request upgrade when `flags & FILE_UNLOCKED != 0`", there would be multiple threads making these requests, and it might be useful to prevent unnecessary requests if one of them is waiting for some rarely-occuring condition. (Then again, maybe that means the notifications should also be conditional, so that they don't wake up all the threads?)

So... for now I think it's better to keep both `up_state` and `down_state`, if only for symmetry between client and server.

Maybe better names for these variables would help? But I couldn't think of good ones: if there's something like `pending_state` and `requested_state`, then it's not clear which side requested what...

</blockquote></details>

Thanks, your explanation makes sense. (I meant the client code.)

I agree that it's better to keep two states, but maybe rename them to verbose-but-obvious `client_requests_state` and `server_requests_state`?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhpLQ48M9EQv_ppfqt:-MWwvmje0WwrNBT8_3wb:bunzoze) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/src/sync/shim_sync_client.c#L200)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I did think about the interruptions (the outer loop should handle these), but it would be good to also handle errors instead of going into a busy loop. I used `object_wait_with_retry`.
</blockquote></details>

Why do you have both `object_wait_with_retry()` and `DkSynchronizationObjectWait()` now?


<!-- Sent from Reviewable.io -->

2021-03-31 18:43 UTC, pwmarcz reviewed
Update:

* Renamed `UPGRADE` to `CONFIRM_UPGRADE`, etc.
* Renamed `{up,down}_state` variables to less confusing `{client,server}_req_state`.
* Added "close" interaction and cleanup code (including a sanity check on process disconnect).
* Added additional "closed" state, to distinguish handles that have never been requested from the server (which can happen for handles inherited after fork).
* Renamed `sync_{open_close}` to `sync_{init,destroy}` because of the above (`sync_init` initializes the handle in closed state).
* Refactored IPC glue code to reduce boilerplate.

With the addition of cleanup code, I think this is ready to exit "draft" status.

@boryspoplawski Regarding our earlier discussion about IPC leader connecting to itself: this branch adds some code to do that. Do you think it can stay like that for now, or should we special-case such messages (e.g. replace pipe with a queue)? As you can probably see from the code structure, it would be good for such special-casing to be transparent, so that I can do something like `send_ipc_message(msg, /*port=*/NULL)` and not worry about the details.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267#-:-MX8XyIVE6DtaS_LYrXD:b-z443k2)* status: 0 of 13 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_sync.h, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhd3p13yWFo8YKblj7:-MX8X4OxEe7ghX_XYCxc:b2dm7t8) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L83)):*
>Do we need additional messages? I would be fine with these 4 messages, just better names.

Apparently I do... I think there are some weird corner cases around unregistering a handle, and I decided it's cleaner to add another pair of messages: `REQUEST_CLOSE` and `CONFIRM_CLOSE`.

Now, the design is more regular: `CONFIRM_x` always is a response to `REQUEST_x`, so "confirm" is not misleading.
___
*[LibOS/shim/include/shim_sync.h, line 180 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhmtIUC2CbIFwaRLEA:-MX8_Uwz7QyUmCtbGnrf:b-ab7ptb) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, your explanation makes sense. (I meant the client code.)

I agree that it's better to keep two states, but maybe rename them to verbose-but-obvious `client_requests_state` and `server_requests_state`?
</blockquote></details>

Changed to `client_req_state` and `server_req_state`.
___
*[LibOS/shim/src/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWcw4t43C3sgWactDCn:-MX8_Zb020LUVDuVr-H0:b-sqodp9) ([raw file](https://github.com/oscarlab/graphene/blob/a62f4cc4097ec9238214e97ef7ce4669af7a6bdf/LibOS/shim/src/Makefile#L5)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I'll make an issue and/or PR out of it.
</blockquote></details>

The problem is now fixed by #2277, and #2282 will reenable `_FORTIFY_SOURCE` (not necessary here, but nice to have).
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhpLQ48M9EQv_ppfqt:-MX8XvbMB_QfgNYbdls3:b-hbyrol) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/src/sync/shim_sync_client.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have both `object_wait_with_retry()` and `DkSynchronizationObjectWait()` now?
</blockquote></details>

My mistake. Fixed.


<!-- Sent from Reviewable.io -->

2021-04-01 09:48 UTC, dimakuv requested changes
> Reviewed 13 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBcGlUCZH2X1My0Uok:-MXBcGlUCZH2X1My0Uol:bno7pra) (no related file):*
> The current objects (shim_handle, shim_dentry) are used pretty much everywhere, without clearly defined rules, and the code is... resistant to change.

BTW, this is the mildest phrase used for the state of Graphene file system code :)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBpGDl5vvrbo1TzcXt:-MXBpGDl5vvrbo1TzcXu:b-de0ig8) (no related file):*
Jenkins (non-SGX) complains about `kill_all` LibOS test:
```
[P21054:i1:kill_all] IPC leader died
[P21052:i1:kill_all] IPC leader died
[P21057:i1:kill_all] IPC leader died
```

@boryspoplawski Any ideas what this means?

---
___
*[LibOS/shim/include/shim_sync.h, line 83 at r2](https://reviewable.io/reviews/oscarlab/graphene/2267#-MWhd3p13yWFo8YKblj7:-MXBdquvBbdSzoab4AnM:b-g64abx) ([raw file](https://github.com/oscarlab/graphene/blob/4255db4cacddefcb1de302f78c8ac1b467298fb8/LibOS/shim/include/shim_sync.h#L83)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Do we need additional messages? I would be fine with these 4 messages, just better names.

Apparently I do... I think there are some weird corner cases around unregistering a handle, and I decided it's cleaner to add another pair of messages: `REQUEST_CLOSE` and `CONFIRM_CLOSE`.

Now, the design is more regular: `CONFIRM_x` always is a response to `REQUEST_x`, so "confirm" is not misleading.
</blockquote></details>

Done. Yes, the names are self-explanatory now, thanks!
___
*[LibOS/shim/include/shim_sync.h, line 84 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBe2ZLCqG5tx3G7_xs:-MXBe2ZLCqG5tx3G7_xt:b-pql1d3) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L84)):*
> ```objc
>  *
>  *    The client requests access to a resource with given ID (in either SHARED or EXCLUSIVE)
>  *    mode. The server downgrades the handles for other clients (if that's necessary for fulfilling
> ```

The closing bracket is in a wrong place: should be `...EXCLUSIVE mode)`
___
*[LibOS/shim/include/shim_sync.h, line 92 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBeEiV-VIQvwUMpBhD:-MXBeEiV-VIQvwUMpBhE:btfhpz0) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L92)):*
> ```objc
>  *    - client: CONFIRM_DOWNGRADE(id, state, data)
>  *
>  *    The server requests client to dongrade its handle. The client replies with CONFIRM_DOWNGRADE
> ```

Typo: `downgrade`
___
*[LibOS/shim/include/shim_sync.h, line 100 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBe_w58l0uP8EveBRx:-MXBe_w58l0uP8EveBRy:b-no5eke) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L100)):*
> ```objc
>  *
>  *    The client informs that it has stopped using a handle, and (if the state was EXCLUSIVE) sends
>  *    latest data. The server cancels any pending requests from the client, and replies with
> ```

`cancels any pending requests from the client` -- this is vague. By "pending", do you mean **all currently-handled REQUEST_UPGRADE** messages from this client?

It makes sense, but I just want more precise wording here.

Also, what happens if we have:
- Two subsequent `REQUEST_CLOSE` messages from the same client? Does the service simply no-op the second request?
- A `REQUEST_UPGRADE` after a `REQUEST_CLOSE`? Does the server consider this request as a "brand new lock on this handle" (in other words, just like the very first `REQUEST_UPGRADE` from that client)?
___
*[LibOS/shim/include/shim_sync.h, line 104 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBhL9zDGTO3-uiUB9F:-MXBhL9zDGTO3-uiUB9G:b6ytng9) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L104)):*
> ```objc
>  *
>  *    This is done by client for every handle it destroys, and should be done for all handles before
>  *    process exit.
> ```

Actually, what happens to the whole system if one process "forgets" to reply to say `REQUEST_DOWNGRADE`? Or if one process doesn't cleanly terminate and never sends `REQUEST_CLOSE`? How does the server handle this situation?
___
*[LibOS/shim/include/shim_sync.h, line 107 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBhhoJB2qszjMtyXwR:-MXBhhoJB2qszjMtyXwS:b3hy0qg) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L107)):*
> ```objc
>  *
>  * Note that the request and confirmation aren't necessarily paired one-to-one: in principle,
>  * multiple REQUESTs can be answered with one CONFIRM.
> ```

Can you give an example? Do you mean cases like `REQUEST_UPGRADE` on the same handle by the same client sent twice?
___
*[LibOS/shim/include/shim_sync.h, line 253 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBoR4H5xKhC1_sXGsN:-MXBoR4H5xKhC1_sXGsO:b-e1h4ni) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L253)):*
> ```objc
> void sync_server_handle_message(struct shim_ipc_port* port, int code, uint64_t id, int state,
>                                 size_t data_size, void* data);
> void sync_server_handle_disconnect(struct shim_ipc_port* port);
> ```

Why this strange name? Shouldn't it be `sync_server_client_disconnect()`? I.e., it is the client that disconnected, not the handle.
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 287 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBlvDF67bVWc6M6Gpd:-MXBlvDG4sXwDkvlqD2l:b-vjzvr4) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/src/sync/shim_sync_server.c#L287)):*
> ```C
>     struct server_handle* handle;
>     if (!(handle = find_handle(id, /*create=*/false)))
>         FATAL("REQUEST_CLOSE for unknown handle\n");
> ```

I wonder if we really want this tight coupling between the server and clients. I understand that say a double `REQUEST_CLOSE` from the same client is a protocol error, but do we really want to panic and destroy the whole Graphene cluster of processes?
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBnvb43T4JHlgQRgDh:-MXBnb355QLIz7216fjF:b-16f2zl) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/src/sync/shim_sync_server.c#L350)):*
> ```C
>         return;
> 
>     lock(&g_server_lock);
> ```

This global lock seems a bit extreme. It could become a perf bottleneck. But for now, such coarse-grained locking is fine, not blocking. Maybe add a TODO comment somewhere to use more fine grained locking?


<!-- Sent from Reviewable.io -->

2021-04-01 13:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 8 of 13 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBpGDl5vvrbo1TzcXt:-MXCV_IQC1RoPSt1xuqk:b78i9bx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenkins (non-SGX) complains about `kill_all` LibOS test:
```
[P21054:i1:kill_all] IPC leader died
[P21052:i1:kill_all] IPC leader died
[P21057:i1:kill_all] IPC leader died
```

@boryspoplawski Any ideas what this means?
</blockquote></details>

Looks like I broke the "broadcast" feature when adding the self-connection of IPC leader. Fixed.

(Again, if a loopback pipe is not good, I'm happy with an alternative mechanism for queuing messages to self).

---
___
*[LibOS/shim/include/shim_sync.h, line 84 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBe2ZLCqG5tx3G7_xs:-MXCFKlh3Hz3xdhdR9jJ:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The closing bracket is in a wrong place: should be `...EXCLUSIVE mode)`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_sync.h, line 92 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBeEiV-VIQvwUMpBhD:-MXCFOOSB2DxE3sRnm88:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `downgrade`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_sync.h, line 100 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBe_w58l0uP8EveBRx:-MXCFVkgDdAlbdsZaqGE:b5zlmug) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L100)):*
>cancels any pending requests from the client -- this is vague. By "pending", do you mean all currently-handled REQUEST_UPGRADE messages from this client?

I meant that the server drops whatever is remembered in `client_req_state`. But, more to the point, it means that after `CONFIRM_CLOSE` the server guarantees to send no further messages about a handle. I reworded the explanation.

>Two subsequent REQUEST_CLOSE messages from the same client? Does the service simply no-op the second request?

This will cause the server to panic, because REQUEST_CLOSE is also a promise not to send further requests. In practice it means all work on a handle has to be finished before `sync_close()`. (I think right now it's the case because we destroy the handle really late in the lifecycle, but I don't trust the filesystem code too much...)

>A REQUEST_UPGRADE after a REQUEST_CLOSE? Does the server consider this request as a "brand new lock on this handle" (in other words, just like the very first REQUEST_UPGRADE from that client)?

Yes, but I'm not sure if that won't cause problems.. Right now it's not important (a `REQUEST_UPGRADE` is always for a fresh ID, or for ID inherited after fork, but we never "reopen" a handle), but when I it comes to implementing dentries, I think I'll need some concept of client-local IDs that cannot be reused.
___
*[LibOS/shim/include/shim_sync.h, line 104 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBhL9zDGTO3-uiUB9F:-MXCJ_0O-xCfgpK6dZY9:b-m1h3yx) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L104)):*
>Actually, what happens to the whole system if one process "forgets" to reply to say REQUEST_DOWNGRADE?

The system will lock up, with other processes waiting for that downgrade.

>Or if one process doesn't cleanly terminate and never sends REQUEST_CLOSE?

When that process exits, the IPC disconnect handler (`sync_server_disconnect`) will run, notice that there are still open handles, and panic.

An alternative would be to forget about all handles of such a process, so that other processes can continue. But that can mean data loss: if some of these handles were EXCLUSIVE, they will be possibly reverted to earlier versions. So I thought shutting down everything is the safer thing.
___
*[LibOS/shim/include/shim_sync.h, line 107 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBhhoJB2qszjMtyXwR:-MXCKgSt6QzRNxeu5XWA:bprsrhk) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L107)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you give an example? Do you mean cases like `REQUEST_UPGRADE` on the same handle by the same client sent twice?
</blockquote></details>

I reworded it to include examples: there could be two subsequent requests for different states, and the server can answer with a "better" one.
___
*[LibOS/shim/include/shim_sync.h, line 253 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBoR4H5xKhC1_sXGsN:-MXCP23CBTpGkTN8j35B:bvzwjaq) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/include/shim_sync.h#L253)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this strange name? Shouldn't it be `sync_server_client_disconnect()`? I.e., it is the client that disconnected, not the handle.
</blockquote></details>

Unfortunate choice of names: I meant "handle" as a verb. I renamed these functions to `*_callback`, same as their IPC counterparts.
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 287 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBlvDF67bVWc6M6Gpd:-MXCWOA3D60QXG5rY0d0:beo9hyl) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/src/sync/shim_sync_server.c#L287)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I wonder if we really want this tight coupling between the server and clients. I understand that say a double `REQUEST_CLOSE` from the same client is a protocol error, but do we really want to panic and destroy the whole Graphene cluster of processes?
</blockquote></details>

Right now, I think that's the best we can do to handle bugs: a protocol error likely means an implementation error, and I want to fail fast on these. Certainly I don't want to try (possibly unsound) ways of recovering from such errors. But also the issue is there's really no way to reply with an error code...

Actually, now that I think of it, it would be great if the IPC system supported responding to a message. The `REQUEST_x / RESPONSE_x` could just become a pair of request/response, and it would simplify the implementation (at the cost of some more server-side bookkeeping).

I see that right now we have a "message with ack", but it's pretty limited:
* The response is just a single int, and I would need a struct with data, same as request (or error code),
* ~~Only replying immediately is supported, and I want to store something like a request number, and reply at some later time.~~ Actually there seems to be `send_response_ipc_message`, so I think I can do that.

@boryspoplawski What do you think about extending the IPC system in this way? 

(In any case, I'd rather do that after merging this PR).
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBnvb43T4JHlgQRgDh:-MXCTSH3CXb0UuKT_v6B:b-a5iqgd) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf [...]

2021-04-01 13:43 UTC, dimakuv submitted a review, later dismissed
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sync/shim_sync_server.c, line 287 at r4](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBlvDF67bVWc6M6Gpd:-MXCf1r36_YZWA2uVU4R:bq62qtr) ([raw file](https://github.com/oscarlab/graphene/blob/d3387b794febb05b2e0f791a96a6bbcf0f5aa993/LibOS/shim/src/sync/shim_sync_server.c#L287)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Right now, I think that's the best we can do to handle bugs: a protocol error likely means an implementation error, and I want to fail fast on these. Certainly I don't want to try (possibly unsound) ways of recovering from such errors. But also the issue is there's really no way to reply with an error code...

Actually, now that I think of it, it would be great if the IPC system supported responding to a message. The `REQUEST_x / RESPONSE_x` could just become a pair of request/response, and it would simplify the implementation (at the cost of some more server-side bookkeeping).

I see that right now we have a "message with ack", but it's pretty limited:
* The response is just a single int, and I would need a struct with data, same as request (or error code),
* ~~Only replying immediately is supported, and I want to store something like a request number, and reply at some later time.~~ Actually there seems to be `send_response_ipc_message`, so I think I can do that.

@boryspoplawski What do you think about extending the IPC system in this way? 

(In any case, I'd rather do that after merging this PR).
</blockquote></details>

OK, resolving. Let's fail fast.


<!-- Sent from Reviewable.io -->

2021-04-02 16:23 UTC, boryspoplawski requested changes
The IPC changes are still WIP, but the end goal is to have something like `send_ipc_message(msg, vmid)` or `send_ipc_message(msg, pid)` - in your case you could just provide vmid or pid of current process. Unfortunately, it's not yet ready (PR should land next week).

> Reviewed 8 of 14 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267#-:-MXH7Cye1LwnXcNnTofC:b-r87yrh)* status: all files reviewed, 37 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXBcGlUCZH2X1My0Uok:-MXH71Kw5AGsVa5uyEpK:b-ydnxck) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> The current objects (shim_handle, shim_dentry) are used pretty much everywhere, without clearly defined rules, and the code is... resistant to change.

BTW, this is the mildest phrase used for the state of Graphene file system code :)
</blockquote></details>

I wouldn't be so gentle ;)

---
___
*[LibOS/shim/include/shim_ipc.h, line 123 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHuXdfECbXMIhBVPJ7:-MXHuXdfECbXMIhBVPJ8:b-nf41gr) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_ipc.h#L123)):*
> ```objc
>     struct shim_lock msgs_lock;
> 
>     unsigned int num_sync_handles;
> ```

Please add a comment that accesses to this field should be synchronized by a global lock in sync server.
___
*[LibOS/shim/include/shim_sync.h, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHF7WG1PZyYv0ZPsFP:-MXHF7WG1PZyYv0ZPsFQ:bqopafu) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L20)):*
> ```objc
>  * handle in EXCLUSIVE mode (which means that data held by other processes are about to become
>  * invalid). Therefore, as long as the handle is uncontested, there is no communication overhead for
>  * using it.
> ```

Doesn't it always require round-trip with IPC leader?
___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-MXHGHFz8hPCNxI42gsq:byta3rp) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
> ```objc
>  * using it.
>  *
>  * Example usage (note that the "Lock" and "Unlock" parts should probably be extracted to helper
> ```

I do not like the interface, but I assume it's done this way to enable syncing only some fields of the struct.
How about changing it to something like:
```
struct obj {
    struct {
        int field_one;
        long filed_two;
    } synced_fields;
    int field_tree;
};
struct obj obj = { 0 };

sync_init(&obj.sync, 0, sizeof(obj.synced_fields));

sync_lock(...);
if (obj.sync_buf) {
    /* This needs `synced_fields` to be packed or manual field by field copying.
     * Needs rethinking. */
    memcpy(&obj.synced_fields, obj.sync.buf, sizeof(obj.synced_fields));
}

(...)
```

Just some ideas, I've not yet read the implementation, just this example.
___
*[LibOS/shim/include/shim_sync.h, line 138 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHPGsz-jnRz-vOnOSC:-MXHPGsz-jnRz-vOnOSD:b-y8nonw) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L138)):*
> ```objc
>  * TODO (new features for additional use cases):
>  * - mechanism for independently acquiring the same handle, without knowing the ID (e.g. for a given
>  *   file path); will probably need REQUEST_OPEN/CONFIRM_OPEN messages
> ```

Any other example? Opening same path twice should give you independent handles, which do not need to be synchronized.
___
*[LibOS/shim/include/shim_sync.h, line 143 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHPhf05Dha4tpbbAW2:-MXHPhf05Dha4tpbbAW3:b-uo12sw) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L143)):*
> ```objc
>  */
> 
> #ifndef _SHIM_SYNC_H_
> ```

Reserved name, just remove the leading `_`.
___
*[LibOS/shim/include/shim_sync.h, line 162 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHR43V15q2QnjKY827:-MXHR43V15q2QnjKY828:b-x7fhw5) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L162)):*
> ```objc
> enum {
>     /* No state, used for {client_server}_req_state */
>     SYNC_STATE_NONE = 0,
> ```

`0` is default, no need to explicitly specify it.
___
*[LibOS/shim/include/shim_sync.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHV4KuERrLFKgqGbIQ:-MXHV4KuERrLFKgqGbIR:be8dpc7) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L192)):*
> ```objc
> 
>     /* Size of currently stored data. Should be always less than buf_size. */
>     size_t data_size;
> ```

Why do we need this field? Isn't it always equal to `buf_size`?
___
*[LibOS/shim/include/shim_sync.h, line 195 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI1ZLKChFK_WJtYYCU:-MXI1ZLKChFK_WJtYYCV:b-8242i) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L195)):*
> ```objc
> 
>     /* Internal properties lock. Protects all the following fields. */
>     struct shim_lock prop_lock;
> ```

Please document lock ordering (this vs use_lock).
___
*[LibOS/shim/include/shim_sync.h, line 256 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHVwd02LyDWnIhB-ZC:-MXHVwd02LyDWnIhB-ZD:btyoy99) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L256)):*
> ```objc
> /*** Message handlers (called from IPC, see ipc/shim_ipc_sync.c) ***/
> 
> struct shim_ipc_port;
> ```

Why not include `shim_ipc.h`?
___
*[LibOS/shim/src/shim_init.c, line 34 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHxHEv8HVr00IiW_Gj:-MXHxHEv8HVr00IiW_Gk:bdixqn8) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/shim_init.c#L34)):*
> ```C
> 
> #include "shim_sync.h"
> ```

Please sort this into other includes.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 474 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIMEoy9qxShNrBLsrI:-MXIMEoy9qxShNrBLsrJ:b-yq4aol) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/bookkeep/shim_handle.c#L474)):*
> ```C
> 
>         if ((hdl->type == TYPE_FILE || hdl->type == TYPE_DIR)
>                 && sync_is_initialized(&hdl->info.file.sync)) {
> ```

Do we have `hdl->info.file` for `TYPE_DIR`?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 456 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIN96j9nqdXdWhyqE9:-MXIN96j9nqdXdWhyqEA:bjtqwze) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/fs/chroot/fs.c#L456)):*
> ```C
>     hdl->info.file.data    = data;
> 
>     if (!sync_is_initialized(&hdl->info.file.sync))
> ```

Can this be false? In what case?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 721 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIO1Fr-9fgOHKt8--3:-MXIO1Fr-9fgOHKt8--4:b-cxoiau) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/fs/chroot/fs.c#L721)):*
> ```C
>         if (file->marker > file->size) {
>             file->size = file->marker;
>             chroot_update_size(hdl, file, FILE_HANDLE_DATA(hdl));
> ```

This seem to update some fileds other than `file->size` and `file->marker`. Is that safe without old locks taken?
___
*[LibOS/shim/s [...]

2021-04-02 19:36 UTC, pwmarcz reviewed
@boryspoplawski That sounds good, I can wait for that PR, let's resolve the rest of the issues in this PR in the meantime.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267#-:-MXIb8Hp-driyyxhIbyT:b-4jsq2x)* status: 5 of 12 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/shim_ipc.h, line 123 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHuXdfECbXMIhBVPJ7:-MXIbKB7EPr9xIYn_A9P:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_ipc.h#L123)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add a comment that accesses to this field should be synchronized by a global lock in sync server.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_sync.h, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHF7WG1PZyYv0ZPsFP:-MXIbLnlCpFumSgrzPjg:b94ooge) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Doesn't it always require round-trip with IPC leader?
</blockquote></details>

I mean repeated uses of the handle are free, the only IPC overhead is at first use and shutdown. I added that to the comment.
___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-MXIbpzh5iZ47B45T-bv:b-xgasib) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
>I do not like the interface, but I assume it's done this way to enable syncing only some fields of the struct.

Something like that. I definitely wouldn't want to send data such as pointers. The idea was to allow more complicated serialization mechanisms someday (e.g. sending strings, or recreating objects), but for now I'm happy with something simple.

>This needs `synced_fields` to be packed or manual field by field copying. Needs rethinking.

Why? Do we worry about copying the data stored in padding? The checkpointing system doesn't seem to mind that.

And requiring the user of the sync handle to use a packed struct in their own data structure sounds pretty inconvenient.

Anyway, can you explain what you don't like about the current interface? Maybe we can come up with something better.
___
*[LibOS/shim/include/shim_sync.h, line 138 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHPGsz-jnRz-vOnOSC:-MXIe1wc2cT8MubMuL1f:brtbg66) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L138)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Any other example? Opening same path twice should give you independent handles, which do not need to be synchronized.
</blockquote></details>

I don't mean a file handle, this would be for synchronizing dentry data. That's my next use case: to try and implement `flock` using sync handles.
___
*[LibOS/shim/include/shim_sync.h, line 143 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHPhf05Dha4tpbbAW2:-MXIfF2S4Pm5GqcavNDh:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L143)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Reserved name, just remove the leading `_`.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_sync.h, line 162 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHR43V15q2QnjKY827:-MXIfIMQA2QUDJMuwMFZ:b-e06j4t) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L162)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`0` is default, no need to explicitly specify it.
</blockquote></details>

OK, removed.
___
*[LibOS/shim/include/shim_sync.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHV4KuERrLFKgqGbIQ:-MXIfKlr8r6Hq3tEmktP:b-rbinjs) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L192)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this field? Isn't it always equal to `buf_size`?
</blockquote></details>

The API allows storing _less_ data than `buf_size`, that doesn't seem useful right now though...

More importantly, a newly created handle has `data_size` of 0, and we need to distinguish this case somehow (so that we don't overwrite fields with 0s). Maybe `bool is_new` would be better?
___
*[LibOS/shim/include/shim_sync.h, line 195 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI1ZLKChFK_WJtYYCU:-MXIgwLI0J2y4ZLt0eRy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L195)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please document lock ordering (this vs use_lock).
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_sync.h, line 256 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHVwd02LyDWnIhB-ZC:-MXIhKZ-4-T2kZyVygKD:bqht8zs) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L256)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not include `shim_ipc.h`?
</blockquote></details>

Circular dependency: `shim_ipc.h` includes `shim_handle.h` which includes this file.
___
*[LibOS/shim/src/shim_init.c, line 34 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHxHEv8HVr00IiW_Gj:-MXIhhyNEbAx_ZUSSgEn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/shim_init.c#L34)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please sort this into other includes.
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 474 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIMEoy9qxShNrBLsrI:-MXIhjDk8eUQd-otFaeW:b-q9sip9) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/bookkeep/shim_handle.c#L474)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Do we have `hdl->info.file` for `TYPE_DIR`?
</blockquote></details>

Ouch, yeah, this is actually worse than I thought :(

Mostly, `TYPE_xxx` means we can access `hdl->info.xxx` (that holds e.g. for sockets). However, `hdl->info.file`, despite its name, is actually "owned" by chroot filesystem. And `TYPE_FILE / TYPE_DIR` can appear for any filesystem.

So, seeing how this is actually about `chroot` filesystem, and we have the necessary hooks there (`fs->hput` and `fs->checkin`), I moved out the code there.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 456 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIN96j9nqdXdWhyqE9:-MXIqMy5ClY8vBRJ9Eto:b405h70) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/fs/chroot/fs.c#L456)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can this be false? In what case?
</blockquote></details>

If this is a handle received fr [...]

2021-04-02 21:20 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-MXJ9gPO7sj_Qkf6afnY:b-x84psk) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
> Why? Do we worry about copying the data stored in padding? The checkpointing system doesn't seem to mind that.

No we do not worry about the padding, but now I don't remember why I wrote this comment. Seems we are fine without packing.
> And requiring the user of the sync handle to use a packed struct in their own data structure sounds pretty inconvenient.

Yup, agree, that's why I wrote this needs a thought. But it seems we do not need it at all.
> Anyway, can you explain what you don't like about the current interface? Maybe we can come up with something better.

I do not like we would have to keep additional struct for each that want's to use this mechanism, which would actually be just a part of the original one. And we need to handle each field separately.
___
*[LibOS/shim/include/shim_sync.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHV4KuERrLFKgqGbIQ:-MXJD8bN4Yk_GDYf2X0Y:b-w56ii6) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L192)):*
Isn't holding one size filed - describing how much data this handle is syncing, the value passed to init - enough? `is_new` could be equivalent to `buf == NULL`.

> The API allows storing less data than buf_size, that doesn't seem useful right now though...

Yeah, plus we need to worry about the sizes mismatch, which adds some complexity...
___
*[LibOS/shim/src/fs/chroot/fs.c, line 456 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIN96j9nqdXdWhyqE9:-MXJKVi_7vd1C_tk4xQl:b-l11tc9) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/fs/chroot/fs.c#L456)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If this is a handle received from checkpointing filesystem (i.e. inherited after fork).
</blockquote></details>

Isn't a handle from checkpointing system refering to well, already opened file, and as such won't even land in `__chroot_open`?
Also you now to `sync_init` in `checkin`.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 182 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI2FHC8sLcjyW1i4tp:-MXJNGei3j5NSSgM-rZf:b-b1dsht) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L182)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm not sure, but isn't `prop_lock` necessary for memory ordering? It looks weird to access the properties protected by `prop_lock` without taking it, _after_ they've been possibly used by other threads.
</blockquote></details>

I don't think so. Calling this function should be only possible if we are holding the last reference to this handle.
I think all issues steam from the fact that this function both destroys the object and takes it from global list and there is no telling if other threads are using it concurrently.
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHvgrWB5_YkZDzl_AC:-MXJRzrD1NJNh7hAwCtr:b-t1ahki) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_server.c#L350)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If the lock is not created, then we're sure nobody called `init_sync_server`, but it does not follow that no IPC connection got disconnected - you need to know how the rest of Graphene calls us for that.

So, I would be uncomfortable just removing this check, but how about changing it to an assertion?
</blockquote></details>

Hmm, `init_sync_server` should probably be called by inside ipc_helper initialization routines (as the ipc helper is actually the sync server). Then it would be clear that no disconnects can happen without initialization.


<!-- Sent from Reviewable.io -->

2021-04-07 09:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 7 of 12 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-MXaU_yl4cxa6Kdm8G4X:b-mkznc6) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
I tried to apply the solution with `struct sync_data` (or `synced_data`) and it looks very invasive: if the field is going to be synchronized, you need to move it to the inner struct and convert all accesses to it. I also don't like how inflexible the mechanism is: all you can do is synchronize the set of fields byte-by-byte.

>And we need to handle each field separately.

I don't think this is such a bad thing when it comes to serialization/deserialization. It's better to make a decision on case-by-case basis, because only some fields (integers, enums) are going to be transferred directly, and others (pointers, strings, arrays etc.) we will likely want to convert.

Anyway, I modified the mechanism slightly: instead of accessing the data directly (which, I think, was not correct wrt locks...), the `sync_lock` and `sync_unlock` operations now take pointer to data. In principle, you could use it in the way you mentioned:

```
sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE, sizeof(obj.sync_data), &obj.sync_data);
```

But, as I said, I prefer to keep the data structure externally, because it makes the mechanism less invasive, and potentially easier to extend (the data serialized might not be exactly the same as the data in object).

(This might be a good moment to also invite @dimakuv and @mkow to the discussion - any more ideas?)
___
*[LibOS/shim/include/shim_sync.h, line 192 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHV4KuERrLFKgqGbIQ:-MXal-_x4U8AKEUWdSsq:bujyd77) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L192)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't holding one size filed - describing how much data this handle is syncing, the value passed to init - enough? `is_new` could be equivalent to `buf == NULL`.

> The API allows storing less data than buf_size, that doesn't seem useful right now though...

Yeah, plus we need to worry about the sizes mismatch, which adds some complexity...
</blockquote></details>

OK, I changed it so that there's only `data_size`, and NULL means no data yet.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 456 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIN96j9nqdXdWhyqE9:-MXaosp22hfOOQmm_qGz:bef9lss) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/fs/chroot/fs.c#L456)):*
>Isn't a handle from checkpointing system refering to well, already opened file, and as such won't even land in __chroot_open?

Despite its name, `__chroot_open` is also called by `chroot_recreate`, which gets called on files inherited after a fork. I think it's done this way (not in `checkin`) so that such files are initialized lazily.

> Also you now to sync_init in checkin.

Which is why `sync_is_initialized()` will be true for such a file. I added a comment here to explain that.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 103 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI3nr30KqlY6SYtLjW:-MXfXtcFAQn72M-GOE4u:b-h2eozn) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L103)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Agreed, I need to rewrite this and `sync_destroy`.
</blockquote></details>

I rewrote the logic around destroying handles and exiting the process. I decided that adding an artificial state (`SYNC_STATE_CLOSED`) is too hacky, and handle lifecycle (new -> open -> closing -> closed) deserves a separate variable.

The problem with shutdown specifically is that when we clean up just before exit, other threads may be running - so we need to ensure they will not attempt to send any more messages.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 179 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI63V_69mHWtLdGncT:-MXfYuzW8IUNQFYikmWm:bga8crt) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L179)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

ACK, I'm going to rewrite that.
</blockquote></details>

See above thread about the rewrite
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 182 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI2FHC8sLcjyW1i4tp:-MXaq7_e6OTTf_0znBd9:bk3yw00) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L182)):*
>I don't think so. Calling this function should be only possible if we are holding the last reference to this handle.

That is my understanding as well, but is that enough? We know that if another thread modified the handle, it called `unlock(&prop_lock)` already. But does that guarantee (according to the C11 memory model) that if we don't take the lock here, we will not be operating on stale data?
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHvgrWB5_YkZDzl_AC:-MXatsdM1rBBLMikh292:b1xzjs8) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_server.c#L350)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, `init_sync_server` should probably be called by inside ipc_helper initialization routines (as the ipc helper is actually the sync server). Then it would be clear that no disconnects can happen without initialization.
</blockquote></details>

Reading the code, that's not necessarily true. I added the callback to `del_ipc_port_fini`, and it seems that function actually gets called outside the IPC helper (in `send_ipc_message`). 

I could move the callback code somewhere into `shim_ipc_helper()`, but then it's not clear to me it will be called every time a connection is closed (since there are apparently other code paths where we destroy a port).


<!-- Sent from Reviewable.io -->

2021-04-07 12:08 UTC, boryspoplawski requested changes
> Reviewed 4 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 11 of 12 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-MXgDwuz9Knj8MFTFyah:b-nec2kw) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I tried to apply the solution with `struct sync_data` (or `synced_data`) and it looks very invasive: if the field is going to be synchronized, you need to move it to the inner struct and convert all accesses to it. I also don't like how inflexible the mechanism is: all you can do is synchronize the set of fields byte-by-byte.

>And we need to handle each field separately.

I don't think this is such a bad thing when it comes to serialization/deserialization. It's better to make a decision on case-by-case basis, because only some fields (integers, enums) are going to be transferred directly, and others (pointers, strings, arrays etc.) we will likely want to convert.

Anyway, I modified the mechanism slightly: instead of accessing the data directly (which, I think, was not correct wrt locks...), the `sync_lock` and `sync_unlock` operations now take pointer to data. In principle, you could use it in the way you mentioned:

```
sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE, sizeof(obj.sync_data), &obj.sync_data);
```

But, as I said, I prefer to keep the data structure externally, because it makes the mechanism less invasive, and potentially easier to extend (the data serialized might not be exactly the same as the data in object).

(This might be a good moment to also invite @dimakuv and @mkow to the discussion - any more ideas?)
</blockquote></details>

Ok, makes sense.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 456 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIN96j9nqdXdWhyqE9:-MXgDcqL2eW_b7rcVNFL:b-56g3q0) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/fs/chroot/fs.c#L456)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Isn't a handle from checkpointing system refering to well, already opened file, and as such won't even land in __chroot_open?

Despite its name, `__chroot_open` is also called by `chroot_recreate`, which gets called on files inherited after a fork. I think it's done this way (not in `checkin`) so that such files are initialized lazily.

> Also you now to sync_init in checkin.

Which is why `sync_is_initialized()` will be true for such a file. I added a comment here to explain that.
</blockquote></details>

I don't even want to know what `chroot_recreate` is...
Resolving.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 103 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI3nr30KqlY6SYtLjW:-MXfyEOV3KmwYR9XVGVe:b-yhce1u) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L103)):*
> The problem with shutdown specifically is that when we clean up just before exit, other threads may be running - so we need to ensure they will not attempt to send any more messages.

The only threads running are current thread (last user thread, exiting whole process), IPC helper and async helper (usually it's not there). Other user threads are already killed.
Why can't you take a lock -> take object off the list -> unlock -> handle cleanup/free object?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 182 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI2FHC8sLcjyW1i4tp:-MXg6DXK4hnUW6Uk11aX:b-oqhnz0) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L182)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>I don't think so. Calling this function should be only possible if we are holding the last reference to this handle.

That is my understanding as well, but is that enough? We know that if another thread modified the handle, it called `unlock(&prop_lock)` already. But does that guarantee (according to the C11 memory model) that if we don't take the lock here, we will not be operating on stale data?
</blockquote></details>

In general case? No that's not enough.
But we have two cases:
A) no refcounting -> you need some synchronization that will provide the ordering, otherwise you cannot know this is the last reference
B) ref counting -> put operation should provide the synchronization (in Graphene refcouting uses seq_cst ordering)
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 222 at r7](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXgCXfi6eNTnt8z9fWJ:-MXgCXfjAMf2wRyx3ZMu:b-ym08b5) ([raw file](https://github.com/oscarlab/graphene/blob/6b6cce9c67c702d6c1e04b093e6a9c5ab5703374/LibOS/shim/src/sync/shim_sync_client.c#L222)):*
> ```C
> 
>     lock_client();
>     HASH_DELETE(hh, g_client_handles, handle);
> ```

This is still invalid.
If a `find_handle` runs concurrently just before `lock_client` above we get UAF.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 323 at r7](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXgDA11DOdmCVdQj_UM:-MXgDA12BqA8ylBEELSI:b-imk2pj) ([raw file](https://github.com/oscarlab/graphene/blob/6b6cce9c67c702d6c1e04b093e6a9c5ab5703374/LibOS/shim/src/sync/shim_sync_client.c#L323)):*
> ```C
> 
> static struct sync_handle* find_handle(uint64_t id) {
>     lock(&g_client_lock);
> ```

Why not `lock_client()`?
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHvgrWB5_YkZDzl_AC:-MXfxVXG2ODZXxdwJ-gx:bgs0776) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_server.c#L350)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Reading the code, that's not necessarily true. I added the callback to `del_ipc_port_fini`, and it seems that function actually gets called outside the IPC helper (in `send_ipc_message`). 

I could move the callback code somewhere into `shim_ipc_helper()`, but then it's not clear to me it will be called every time a connection is closed (since there are apparently other code paths where we destroy a port).
</blockquote></details>

Well, I'm concurrently rewriting that part of IPC, so everything will change soon...


<!-- Sent from Reviewable.io -->

2021-04-07 14:04 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 10 of 12 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 103 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI3nr30KqlY6SYtLjW:-MXgKrZU-buysj4fhWQs:b-ncybkq) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L103)):*
Oh, that's better! Somehow I thought this is just whichever thread receives `exit_group`. It's nice to be positively surprised by Graphene for a change.

I simplified the code: because I know no other user threads are running, there is no need to add more flags or states.

I also added cleanup: we need to wait for `CONFIRM_CLOSE` messages, but it should guarantee that after `shutdown_sync_client`, we won't get any more IPC sync messages. Should be better than having to wait 0.5 second. :)

>Why can't you take a lock -> take object off the list -> unlock -> handle cleanup/free object?

Because even if this process will not do anything with a handle, the server might still send us messages about it.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 182 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI2FHC8sLcjyW1i4tp:-MXgRMrz2mYrGGSU-HWP:bzd093c) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L182)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

In general case? No that's not enough.
But we have two cases:
A) no refcounting -> you need some synchronization that will provide the ordering, otherwise you cannot know this is the last reference
B) ref counting -> put operation should provide the synchronization (in Graphene refcouting uses seq_cst ordering)
</blockquote></details>

I just noticed that we're still using the handle concurrently, though: the user code in this process might hold the last reference, but there are still messages from the server (we might receive `REQUEST_DOWNGRADE` just after close). That's the reason for the `REQUEST_CLOSE .. CONFIRM_CLOSE` flow. 
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 222 at r7](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXgCXfi6eNTnt8z9fWJ:-MXgUIi89TrmBmMLs9Rm:b4zoyui) ([raw file](https://github.com/oscarlab/graphene/blob/6b6cce9c67c702d6c1e04b093e6a9c5ab5703374/LibOS/shim/src/sync/shim_sync_client.c#L222)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is still invalid.
If a `find_handle` runs concurrently just before `lock_client` above we get UAF.
</blockquote></details>

That's the point of `CONFIRM_CLOSE`: at this point, we have received `CONFIRM_CLOSE`, and so we are guaranteed not to receive any more messages for this handle ID.

I added a comment to clarify that.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 323 at r7](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXgDA11DOdmCVdQj_UM:-MXgV8K0-QneH1HY6Aj4:bidrs83) ([raw file](https://github.com/oscarlab/graphene/blob/6b6cce9c67c702d6c1e04b093e6a9c5ab5703374/LibOS/shim/src/sync/shim_sync_client.c#L323)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `lock_client()`?
</blockquote></details>

Right. Fixed.
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHvgrWB5_YkZDzl_AC:-MXgKnvBDpzg8nQclpyJ:b-jrr9ad) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_server.c#L350)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, I'm concurrently rewriting that part of IPC, so everything will change soon...
</blockquote></details>

OK, I'll take a look again then.


<!-- Sent from Reviewable.io -->

2021-04-12 09:00 UTC, dimakuv approved these changes
> Reviewed 2 of 8 files at r6, 2 of 5 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-MY4BKEdALFrw-Mij523:bmsxdj1) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, makes sense.
</blockquote></details>

I like the current @pwmarcz's interface with a separate struct. As mentioned, this gives flexibility and can be extended on a case by case basis (e.g., instead of sending a string, send a compressed string -- something like this).

It's a bit weird to see the pattern `if (sync_lock(...)) { can use data}; sync_unlock();`. This makes me think of `sync_lock()` semantics as `trylock()` (i.e., it makes me think that the lock was *not* taken if it returned false). I would prefer `void sync_lock(..., bool* data_updated)`, but this is also quite ugly. Anyway, not blocking on this, the current interface is fine.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 721 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXIO1Fr-9fgOHKt8--3:-MY4DGnCCOjZ78JmkGNW:b-plrxyp) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/fs/chroot/fs.c#L721)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm mostly sure it's safe... we update `struct shim_file_data` which as I understand is potentially shared between many handles, and we use atomic operations anyway.

But with this code, I'm not 100% certain, and I don't want to be too clever. It's not my goal to refactor this code, but add a new feature as a proof of concept. So I'll add the locks back just to be safe.

(CC @dimakuv who initially requested removing the old locks.)
</blockquote></details>

Yeah, the FS code is a total mess. I am also not sure if just the `file_sync_lock()` is enough. Let's keep the old locks too.


<!-- Sent from Reviewable.io -->

2021-05-21 19:51 UTC, boryspoplawski requested changes
> Reviewed 1 of 7 files at r2, 1 of 14 files at r4, 1 of 2 files at r8, 13 of 13 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/ipc/shim_ipc_sync.c, line 53 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEYErGABl64O5MvT3e:-MaEYErGABl64O5MvT3f:b-961zvd) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/ipc/shim_ipc_sync.c#L53)):*
> ```C
>     sync_log("sync client", code, id, state);
>     IDTYPE dest;
>     if (g_pal_control->parent_process) {
> ```

The intended check is `!g_process_ipc_ids.leader_vmid`. Also, please collapse this with ternary operator.
`IDTYPE dest = g_process_ipc_ids.leader_vmid ?: g_self_vmid`
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 95 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEZAeACzP1v5KYjJFe:-MaEZAeACzP1v5KYjJFf:baw882p) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/ipc/shim_ipc_worker.c#L95)):*
> ```C
>     ipc_child_disconnect_callback(conn->vmid);
> 
>     if (!g_pal_control->parent_process) {
> ```

Please change to `if (!g_process_ipc_ids.leader_vmid) {`
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 103 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI3nr30KqlY6SYtLjW:-MXgeGTP7IP675CpyQak:b-2o71m2) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L103)):*
> Because even if this process will not do anything with a handle, the server might still send us messages about it.

But we are exiting the whole process, so we can ignore all subsequent requests from server, dont we? We are about to downgrade to the lowest level possible anyway.

Update: after rebase this code seems to be gone.
Update2: it's not gone, added the comment in the new place.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 9 at r6](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFTNTQ7XFNny6moK_3:-MaFTNTQ7XFNny6moK_4:b9l6ax8) ([raw file](https://github.com/oscarlab/graphene/blob/095592aaa0b979edb1507c70b996c9de82fa5b12/LibOS/shim/src/sync/shim_sync_client.c#L9)):*
> ```C
>  * Client part of the sync engine.
>  */
> ```

Locking in this file seems to be still wrong and due to the way it's written is hard to reason about: you keep a global list of objects we no clear notion of ownership or lifetimes.
E.g. what happens if ipc worker thread handles a request from server to do something with a handle lease and at the same time normal app thread closes the fd corresponding to that handle? 
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 83 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEyH5f0jSx4EYNeEJs:-MaEyH5f0jSx4EYNeEJt:b-9zbzce) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L83)):*
> ```C
> 
>     size_t data_size;
>     if (handle->data && handle->cur_state == SYNC_STATE_EXCLUSIVE) {
> ```

Could you unify the semantics to `handle->data_size` being the source of truth? I.e. if there is no data then it's equal to `0` (and then `handle->data` is either `NULL` or a pointer with `0` size, both being ok to pass to `free` or any of `ipc_sync_*` functions).
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 134 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEzsA7A1cIdov5MVee:-MaEzsA7A1cIdov5MVef:bizls25) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L134)):*
> ```C
>         goto err;
>     }
>     if ((ret = DkEventCreate(&handle->event, /*init_signaled=*/false, /*aut_clear=*/false)) < 0) {
> ```

`aut_clear`
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 319 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFETZ481sMxkQzyM5a:-MaFETZ481sMxkQzyM5b:b-u4fe5n) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L319)):*
> ```C
>         lock_client();
>         HASH_DELETE(hh, g_client_handles, handle);
>         __sync_destroy(handle);
> ```

Why do you even call this? Why not simply remove from list/hashtable?
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHvgrWB5_YkZDzl_AC:-MaExEOs1y5UeadlxexS:bb7mm0n) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_server.c#L350)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I'll take a look again then.
</blockquote></details>

ping
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 53 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEqxTQ1cYUBFvZOwy8:-MaEqxTR22Hv4fIpmWU_:bupdfy0) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_server.c#L53)):*
> ```C
> 
>     /* Client ID */
>     IDTYPE vmid;
> ```

Isn't this just `client->vmid`? Why do we need it?
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 137 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEqMz84wZlnoN1Gi9R:-MaEqMz84wZlnoN1Gi9S:bfmvdmy) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_server.c#L137)):*
> ```C
> 
>     if (!(lease = malloc(sizeof(*lease)))) {
>         free(client);
> ```

What if `client` was already created before?
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 387 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEtQ2o6HoXx9iKqEfV:-MaEtQ2o6HoXx9iKqEfW:b8mcao) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_server.c#L387)):*
> ```C
>         FATAL("sending CONFIRM_CLOSE\n");
> 
>     bool handle_deleted = delete_lease(handle, lease);
> ```

This is the only place where this function is used; I would remove deleting `handle` inside it and just inline it here or create another function. It would be cleaner and not confusing: now if this function returns `true` we **cannot** touch `handle`, because it's freed already. It's like we pass the ownership of the pointer, but only conditionally.


<!-- Sent from Reviewable.io -->

2021-05-24 10:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 12 of 17 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc_sync.c, line 53 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEYErGABl64O5MvT3e:-MaSf1tP5ysGZMvzgP90:byuxmcb) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/ipc/shim_ipc_sync.c#L53)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The intended check is `!g_process_ipc_ids.leader_vmid`. Also, please collapse this with ternary operator.
`IDTYPE dest = g_process_ipc_ids.leader_vmid ?: g_self_vmid`
</blockquote></details>

Done.

AFAICT, the shortened ternary operator is a GNU extension, do we have a policy for/against these? I know I had to remove instances of nested functions, because they are not supported by Clang, but the shortened ternary seems to be supported.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 95 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEZAeACzP1v5KYjJFe:-MaSfdWFEhRhPWRU3WD4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/ipc/shim_ipc_worker.c#L95)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change to `if (!g_process_ipc_ids.leader_vmid) {`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 103 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI3nr30KqlY6SYtLjW:-MaSmGtd10cVfK9VrYp7:bopr7sa) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L103)):*
>>>Why can't you take a lock -> take object off the list -> unlock -> handle cleanup/free object?

>>Because even if this process will not do anything with a handle, the server might still send us messages about it.

>But we are exiting the whole process, so we can ignore all subsequent requests from server, dont we? We are about to downgrade to the lowest level possible anyway.

So, the current version of the shutdown code sends `REQUEST_CLOSE` for all handles, and then waits for all `CONFIRM_CLOSE`.

I _think_ that we could get away with only sending downgrades for the handles that are not downgraded yet, and ignoring server messages for an unknown handle. But that would mean that there's no longer a guarantee:

1. for the server, that if it sends a sync message, it will not be dropped by client and will not fail due to client having already disconnected,
2. for the server, that during client shutdown, the client will have no leases,
3. for the client, that if it receives a sync message, it will be for a known handle,
4. for the client, that after client shutdown, it will not receive any more sync messages.

I would rather have these guarantees: while in this scenario it might be harmless to violate them, their violation can also indicate data loss / deadlock bugs, so I want to detect that early.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 9 at r6](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFTNTQ7XFNny6moK_3:-MaSfx1J4bwiuui_KkWn:b-vbf3x9) ([raw file](https://github.com/oscarlab/graphene/blob/095592aaa0b979edb1507c70b996c9de82fa5b12/LibOS/shim/src/sync/shim_sync_client.c#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Locking in this file seems to be still wrong and due to the way it's written is hard to reason about: you keep a global list of objects we no clear notion of ownership or lifetimes.
E.g. what happens if ipc worker thread handles a request from server to do something with a handle lease and at the same time normal app thread closes the fd corresponding to that handle? 
</blockquote></details>

I'm not seeing what's wrong.

- If a thread closes a fd, it calls `sync_destroy`. That means at that point nobody is using the sync handle (`sync_lock`), although the worker thread still can handle some requests.
- `sync_destroy` unregisters the handle from the server, i.e. sends `REQUEST_CLOSE` and waits for `CONFIRM_CLOSE`. After handling `CONFIRM_CLOSE`, we are guaranteed not to receive any more messages regarding the handle, so we know it will not be used by the worker thread either.
- At this point, we can safely free memory, etc.

This is all explained in the implementation overview (`shim_sync.h` line 90).

It's true that the worker thread complicates things, but from the user's perspective, the only requirement is calling `sync_destroy` after you're done locking the handle (you cannot use `sync_lock`/`sync_unlock` anymore). And that's the same requirement as, say, `pthread_mutex_destroy`.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 83 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEyH5f0jSx4EYNeEJs:-MaSkPeO7s_NGDtkG4Qm:brk1x3l) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you unify the semantics to `handle->data_size` being the source of truth? I.e. if there is no data then it's equal to `0` (and then `handle->data` is either `NULL` or a pointer with `0` size, both being ok to pass to `free` or any of `ipc_sync_*` functions).
</blockquote></details>

If `data_size` is 0 in the beginning, that means the API would include data size along with data, like this:

```diff
-sync_init(&obj.sync, id, sizeof(struct obj_sync_data));
+sync_init(&obj.sync, id);

 struct obj_sync_data data;
-if (sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE, &data)) {
+if (sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE, &data, sizeof(data))) {
     obj.field_one = data.field_one;
     obj.field_two = data.field_two;
 }

 data.field_one = obj.field_one;
 data.field_two = obj.field_two;
-sync_unlock(&file->sync, &data);
+sync_unlock(&file->sync, &data, sizeof(data));
```

(Unless we store two variables, predefined data size and current data size, but I was already requested to remove that).

Is that OK?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 134 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEzsA7A1cIdov5MVee:-MaSnb9j60SAxqoUkVCQ:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L134)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`aut_clear`
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 319 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFETZ481sMxkQzyM5a:-MaSnka6-y43w66Vl7RA:b3zrxx9) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L319)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do you even call this? Why not simply remove from list/hashtable?
</blockquote></details>

`__sync_destroy` frees memory, should I not call it just because we are exiting?

I remember @dimakuv saying about a similar case that "Ideally, Graphene could `free()`  all such variables during final cleanup, but this is already covered by Linux, and Graphene has many higher-priority things to fix." I understood it as: we should treat freeing memory on exit as a correct thing to do, even though it's not high priority.
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 350 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHvgrWB5_YkZDzl_AC:-MaSrL2w5nIFjblzYczW:b-wev [...]

2021-05-24 15:43 UTC, boryspoplawski commented
Jenkins, retest Jenkins-18.04 please (EINTR on read, should be already fixed on master)

2021-05-24 17:34 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/ipc/shim_ipc_sync.c, line 53 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEYErGABl64O5MvT3e:-MaTzoPZ5zi_jlHMMDHv:b-reofqu) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/ipc/shim_ipc_sync.c#L53)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.

AFAICT, the shortened ternary operator is a GNU extension, do we have a policy for/against these? I know I had to remove instances of nested functions, because they are not supported by Clang, but the shortened ternary seems to be supported.
</blockquote></details>

There is no official policy, I'm personally in favor of things that are sane and supported both by clang and gcc (even if they are non-standard extensions). I deem shortened ternary operator to be one of such things. Nested functions are not one of them :)
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 103 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI3nr30KqlY6SYtLjW:-MaUKqmKBXCF0IRb6WmA:b1q19y1) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L103)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>>>Why can't you take a lock -> take object off the list -> unlock -> handle cleanup/free object?

>>Because even if this process will not do anything with a handle, the server might still send us messages about it.

>But we are exiting the whole process, so we can ignore all subsequent requests from server, dont we? We are about to downgrade to the lowest level possible anyway.

So, the current version of the shutdown code sends `REQUEST_CLOSE` for all handles, and then waits for all `CONFIRM_CLOSE`.

I _think_ that we could get away with only sending downgrades for the handles that are not downgraded yet, and ignoring server messages for an unknown handle. But that would mean that there's no longer a guarantee:

1. for the server, that if it sends a sync message, it will not be dropped by client and will not fail due to client having already disconnected,
2. for the server, that during client shutdown, the client will have no leases,
3. for the client, that if it receives a sync message, it will be for a known handle,
4. for the client, that after client shutdown, it will not receive any more sync messages.

I would rather have these guarantees: while in this scenario it might be harmless to violate them, their violation can also indicate data loss / deadlock bugs, so I want to detect that early.
</blockquote></details>

I do not want to drop any guarantees.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 9 at r6](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFTNTQ7XFNny6moK_3:-MaUMKdN4bF7IFl5lO-e:b-403y9o) ([raw file](https://github.com/oscarlab/graphene/blob/095592aaa0b979edb1507c70b996c9de82fa5b12/LibOS/shim/src/sync/shim_sync_client.c#L9)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm not seeing what's wrong.

- If a thread closes a fd, it calls `sync_destroy`. That means at that point nobody is using the sync handle (`sync_lock`), although the worker thread still can handle some requests.
- `sync_destroy` unregisters the handle from the server, i.e. sends `REQUEST_CLOSE` and waits for `CONFIRM_CLOSE`. After handling `CONFIRM_CLOSE`, we are guaranteed not to receive any more messages regarding the handle, so we know it will not be used by the worker thread either.
- At this point, we can safely free memory, etc.

This is all explained in the implementation overview (`shim_sync.h` line 90).

It's true that the worker thread complicates things, but from the user's perspective, the only requirement is calling `sync_destroy` after you're done locking the handle (you cannot use `sync_lock`/`sync_unlock` anymore). And that's the same requirement as, say, `pthread_mutex_destroy`.
</blockquote></details>

The problem is you tie the validity of a pointer/memory to the state of **another process**. This sounds like a very bad design choice and it's also virtually impossible to reason about correctness of a single object usage without having this whole >1k loc PR in mind.

E.g. you look at function `do_request_downgrade` and it looks up an object on a global list, gets the reference to it and starts using it. The fact that it won't be freed concurrently by `sync_destroy` stems from assumption that we have only one IPC worker thread handling requests from the server in order (but see the probable deadlock below) and the server not issuing any more requests after `CONFIRM_CLOSE` (well, just like you described) and that `do_request_downgrade` is called only from IPC worker.

As far as you might be right that in practice there is no UAF, thanks to all the mentioned assumptions, it seems to be very hard to maintain and I also think there are some deadlocks.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 83 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEyH5f0jSx4EYNeEJs:-MaULuMq-3H_Bq5AD2me:b-tyhtj5) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L83)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If `data_size` is 0 in the beginning, that means the API would include data size along with data, like this:

```diff
-sync_init(&obj.sync, id, sizeof(struct obj_sync_data));
+sync_init(&obj.sync, id);

 struct obj_sync_data data;
-if (sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE, &data)) {
+if (sync_lock(&obj.sync, SYNC_STATE_EXCLUSIVE, &data, sizeof(data))) {
     obj.field_one = data.field_one;
     obj.field_two = data.field_two;
 }

 data.field_one = obj.field_one;
 data.field_two = obj.field_two;
-sync_unlock(&file->sync, &data);
+sync_unlock(&file->sync, &data, sizeof(data));
```

(Unless we store two variables, predefined data size and current data size, but I was already requested to remove that).

Is that OK?
</blockquote></details>

Isn't `data_size` just the size of memory pointer by `data`?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 319 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFETZ481sMxkQzyM5a:-MaUJSmSBgrY5aBB1MMb:b-loc3l4) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L319)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`__sync_destroy` frees memory, should I not call it just because we are exiting?

I remember @dimakuv saying about a similar case that "Ideally, Graphene could `free()`  all such variables during final cleanup, but this is already covered by Linux, and Graphene has many higher-priority things to fix." I understood it as: we should treat freeing memory on exit as a correct thing to do, even though it's not high priority.
</blockquote></details>

But you do not free the handle completely, you just free some part of it - `__sync_destroy` is just "cleanup/free part of the handled used by this subsystem", not destroy an object completely. If you did an equivalent of `close(fd)` that would be ok (tbh we should do it at some point, i.e. just close all fds, so all internal cleanup, syncing or whatever mechanisms trigger, but it's unrelated to this PR).
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 211 at r10](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaUIYlR51_IxewTltk4 [...]

2021-05-25 15:51 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 9 at r6](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFTNTQ7XFNny6moK_3:-MaYzGDW2rAKV3olct8p:b-63ntzs) ([raw file](https://github.com/oscarlab/graphene/blob/095592aaa0b979edb1507c70b996c9de82fa5b12/LibOS/shim/src/sync/shim_sync_client.c#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The problem is you tie the validity of a pointer/memory to the state of **another process**. This sounds like a very bad design choice and it's also virtually impossible to reason about correctness of a single object usage without having this whole >1k loc PR in mind.

E.g. you look at function `do_request_downgrade` and it looks up an object on a global list, gets the reference to it and starts using it. The fact that it won't be freed concurrently by `sync_destroy` stems from assumption that we have only one IPC worker thread handling requests from the server in order (but see the probable deadlock below) and the server not issuing any more requests after `CONFIRM_CLOSE` (well, just like you described) and that `do_request_downgrade` is called only from IPC worker.

As far as you might be right that in practice there is no UAF, thanks to all the mentioned assumptions, it seems to be very hard to maintain and I also think there are some deadlocks.
</blockquote></details>

I see. So if the server violates the protocol, it can cause use after free. I agree it's a bad idea.

What do you think about adding a reference counter to `sync_handle`, similar to `shim_futex.c`? This way, we would destroy the handle after it's removed from the hash table, _and_ all functions that took it from the hash table are done with it.

As for assumption that requests are handled in order: yeah, with the above change it'ss not as necessary, but without it I would have to (at least) accept requests coming for unknown handles.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 83 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEyH5f0jSx4EYNeEJs:-MaYzu-67SpKK36x6q9h:bmleqeu) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't `data_size` just the size of memory pointer by `data`?
</blockquote></details>

A newly created object has no data associated yet (`sync_handle.data` is NULL). The idea was that `data_size` is supplied during initialization.

But yeah, that's pretty confusing to have `data_size` and `data` out of sync. I changed it so that `data_size` gets passed to `sync_lock` and `sync_unlock`.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 319 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFETZ481sMxkQzyM5a:-MaYy_hR7NP5t2IS82lU:bdfqmb5) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L319)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But you do not free the handle completely, you just free some part of it - `__sync_destroy` is just "cleanup/free part of the handled used by this subsystem", not destroy an object completely. If you did an equivalent of `close(fd)` that would be ok (tbh we should do it at some point, i.e. just close all fds, so all internal cleanup, syncing or whatever mechanisms trigger, but it's unrelated to this PR).
</blockquote></details>

I get your point. So `shutdown_sync_client` is only for objects that we would already consider leaked.

I changed the code so that it only waits for `CONFIRM_CLOSE`, and doesn't remove or destroy them. (I think it's better to not remove them from the hashtable - it shouldn't matter but it seems more consistent).
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 211 at r10](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaUIYlR51_IxewTltk4:-MaZ2sllEe1E_MkArE0m:bd0lodf) ([raw file](https://github.com/oscarlab/graphene/blob/c47ef2c45c7e54bafaaf5bad8d10c2b8f5d404b0/LibOS/shim/src/sync/shim_sync_client.c#L211)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What if we receive downgrade request while waiting for close confirmation (e.g. even before sending close request)? We hold `handle->prop_lock`, so IPC worker thread will hang trying to lock it and will never handle close confirmation -> deadlock.
</blockquote></details>

Do you mean in this loop? This is `sync_wait`, which does relinquish the lock.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 240 at r10](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaUFoBO1dDxHsRdcnIZ:-MaZ4DfvDvw7EDuggK_B:bb8l42v) ([raw file](https://github.com/oscarlab/graphene/blob/c47ef2c45c7e54bafaaf5bad8d10c2b8f5d404b0/LibOS/shim/src/sync/shim_sync_client.c#L240)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Unneeded space at the end. Also please add explicit `!= SYNC_STATE_NONE`. Btw what actually happens if `handle->cur_state == SYNC_STATE_NONE`? Deadlock?
</blockquote></details>

Oops, looks like editing accident. `&& handle_cur_state` is a leftover - we just need to check if `handle->cur_state < state`, but that happens outside this block. Removed.
___
*[LibOS/shim/src/sync/shim_sync_server.c, line 133 at r10](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaU0DBp4yguy5VWfCYt:-MaYz-Zs0h2AoY7mqqxu:bi5ypcf) ([raw file](https://github.com/oscarlab/graphene/blob/c47ef2c45c7e54bafaaf5bad8d10c2b8f5d404b0/LibOS/shim/src/sync/shim_sync_server.c#L133)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I personally find:
```
struct server_client* client = find_client(vmid, /*create=*/true);
if (!client) {
```
easier to read, especially since both of these lines are close to each other.
Probably just personal preference, not blocking.
</blockquote></details>

OK, changed.


<!-- Sent from Reviewable.io -->

2021-05-25 20:08 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 9 at r6](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFTNTQ7XFNny6moK_3:-MaZMWHn6NU6YrIxZ9gP:b-56wlpx) ([raw file](https://github.com/oscarlab/graphene/blob/095592aaa0b979edb1507c70b996c9de82fa5b12/LibOS/shim/src/sync/shim_sync_client.c#L9)):*
> What do you think about adding a reference counter 

That's usually the way. We have lots of structures using ref counting, not only futexes.

> As for assumption that requests are handled in order: yeah, with the above change it'ss not as necessary, but without it I would have to (at least) accept requests coming for unknown handles.

That assumption is fine, as long as violating it causes a deadlock (which is pretty harmless and basically a DOS) not a process crash (which probably is not that bad since it can be only caused by other trusted part, but still).
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 83 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEyH5f0jSx4EYNeEJs:-MaZN99E-s61dYBUcVwH:b-pu0c9h) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L83)):*
> The idea was that data_size is supplied during initialization.

That was a good idea, I liked that part.

> But yeah, that's pretty confusing to have data_size and data out of sync.

Yeah.

> I changed it so that data_size gets passed to sync_lock and sync_unlock.

This looks kind of weird, but well, it works and we are getting too many iterations of review anyway :)

I guess my main confusion was why we cannot allocate `data = malloc(data_size)` at initialization. It seems that you want to handle `data` of different sizes on the same `handle`, is that correct? If yes, any specific usage for it (current or future)?
Update: hmm, you seem to FAIL on data sizes mismatch in `sync_lock`...
I have a feeling we've already talked about this, but cannot find it.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 319 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFETZ481sMxkQzyM5a:-Ma_6gcS5E2eyl9u_JQD:b-ovgl3t) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L319)):*
> is only for objects that we would already consider leaked.

What do you mean?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 211 at r10](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaUIYlR51_IxewTltk4:-Ma_7co2BNPXF1-WDQRj:bm9c0br) ([raw file](https://github.com/oscarlab/graphene/blob/c47ef2c45c7e54bafaaf5bad8d10c2b8f5d404b0/LibOS/shim/src/sync/shim_sync_client.c#L211)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Do you mean in this loop? This is `sync_wait`, which does relinquish the lock.
</blockquote></details>

Ah, right, forgot about that.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 70 at r11](https://reviewable.io/reviews/oscarlab/graphene/2267#-Ma_7n7-B63ZdqIj-p_-:-Ma_7n70En0yM7YxXlZc:ba8i0tv) ([raw file](https://github.com/oscarlab/graphene/blob/83785c635d87c932cf1514401b868d5bef0cd2a1/LibOS/shim/src/sync/shim_sync_client.c#L70)):*
> ```C
> }
> 
> static void sync_notify(struct sync_handle* handle) {
> ```

Please add an assert that it holds `handle->prop_lock`


<!-- Sent from Reviewable.io -->

2021-05-26 12:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 15 of 17 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 9 at r6](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFTNTQ7XFNny6moK_3:-Mac_Eb_12d95_gn2uGg:bnttctm) ([raw file](https://github.com/oscarlab/graphene/blob/095592aaa0b979edb1507c70b996c9de82fa5b12/LibOS/shim/src/sync/shim_sync_client.c#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> What do you think about adding a reference counter 

That's usually the way. We have lots of structures using ref counting, not only futexes.

> As for assumption that requests are handled in order: yeah, with the above change it'ss not as necessary, but without it I would have to (at least) accept requests coming for unknown handles.

That assumption is fine, as long as violating it causes a deadlock (which is pretty harmless and basically a DOS) not a process crash (which probably is not that bad since it can be only caused by other trusted part, but still).
</blockquote></details>

I added reference counting.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 83 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEyH5f0jSx4EYNeEJs:-MacU4WSCqqta4FRYW1i:b-4rzrvi) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L83)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The idea was that data_size is supplied during initialization.

That was a good idea, I liked that part.

> But yeah, that's pretty confusing to have data_size and data out of sync.

Yeah.

> I changed it so that data_size gets passed to sync_lock and sync_unlock.

This looks kind of weird, but well, it works and we are getting too many iterations of review anyway :)

I guess my main confusion was why we cannot allocate `data = malloc(data_size)` at initialization. It seems that you want to handle `data` of different sizes on the same `handle`, is that correct? If yes, any specific usage for it (current or future)?
Update: hmm, you seem to FAIL on data sizes mismatch in `sync_lock`...
I have a feeling we've already talked about this, but cannot find it.
</blockquote></details>

Right now the assumption on client's part is that the data size won't change. To be more precise, we assume that `sync_lock` reads exactly as many bytes as last `sync_unlock` wrote.

(I think we might need variable sized data sometime in the future, for storing things like paths, but not soon).

However, if I malloc the buffer at the beginning, I would need an additional variable to say whether the data in buffer is already valid. That's because when I `sync_lock` a new handle for the first time, I don't have any data to read (since the API assumes you write the data on `sync_unlock`).

The first design was like that: there was `buf_size` (the size of the pre-allocated buffer), and `data_size` (the current size of data in the buffer). But it gradually got simplified into the current form.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 319 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFETZ481sMxkQzyM5a:-MacW6T8Epe1JlVl4cRF:b5yyhou) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L319)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> is only for objects that we would already consider leaked.

What do you mean?
</blockquote></details>

I mean objects that we could free on Graphene shutdown, but we do not - not a leak strictly speaking, since the OS cleans up after us, but not following good practices?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 70 at r11](https://reviewable.io/reviews/oscarlab/graphene/2267#-Ma_7n7-B63ZdqIj-p_-:-Mac_8BX2yw1rIGab1-h:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/83785c635d87c932cf1514401b868d5bef0cd2a1/LibOS/shim/src/sync/shim_sync_client.c#L70)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add an assert that it holds `handle->prop_lock`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-26 14:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 12 of 17 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 9 at r6](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFTNTQ7XFNny6moK_3:-Mad52-5DiW-yb4zR_oG:bfysvfi) ([raw file](https://github.com/oscarlab/graphene/blob/095592aaa0b979edb1507c70b996c9de82fa5b12/LibOS/shim/src/sync/shim_sync_client.c#L9)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I added reference counting.
</blockquote></details>

After 1-on-1 discussion: this is still wrong, because the sync handle is a part of other object (e.g. file handle) with its own timeline, and that object might get destroyed before we get to our cleanup in `put_handle`. It would be much better to operate on pointers, and have `shim_sync.c` manage the object fully (i.e. allocate and deallocate it).

So I refactored it this way, and also added checkpoint/restore functions for them so that they can be plugged into checkpoint/restore for everything else.


<!-- Sent from Reviewable.io -->

2021-05-27 09:50 UTC, pwmarcz reviewed
Rebased after LibOS port to Meson.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267#-:-MahDmrb-Fn5Ahf4NJOx:b-85pdba)* status: 12 of 17 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-06-01 02:03 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r12, 7 of 8 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 17 of 18 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 716 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4E92g4Rd5OWyqrtcx:-Mb4E92g4Rd5OWyqrtcy:bmmt6rk) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/bookkeep/shim_handle.c#L716)):*
> ```C
>             case TYPE_FILE:
>                 if (hdl->info.file.sync)
>                     DO_CP(sync_handle, hdl->info.file.sync, &new_hdl->info.file.sync);
> ```

We have a `DO_CP_MEMBER` macro for this (tho it's equivalent).
Not blocking - checkpointing is ugly anyway :)
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 83 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaEyH5f0jSx4EYNeEJs:-Mb4IpXI3knY-zYR0C3g:bkl8euf) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L83)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Right now the assumption on client's part is that the data size won't change. To be more precise, we assume that `sync_lock` reads exactly as many bytes as last `sync_unlock` wrote.

(I think we might need variable sized data sometime in the future, for storing things like paths, but not soon).

However, if I malloc the buffer at the beginning, I would need an additional variable to say whether the data in buffer is already valid. That's because when I `sync_lock` a new handle for the first time, I don't have any data to read (since the API assumes you write the data on `sync_unlock`).

The first design was like that: there was `buf_size` (the size of the pre-allocated buffer), and `data_size` (the current size of data in the buffer). But it gradually got simplified into the current form.
</blockquote></details>

Ok, I see
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 319 at r9](https://reviewable.io/reviews/oscarlab/graphene/2267#-MaFETZ481sMxkQzyM5a:-Mb4CiT7EIvL6UPxeoxT:bze53j0) ([raw file](https://github.com/oscarlab/graphene/blob/1703325de5fa82829d469f999715fe3b39a7fe49/LibOS/shim/src/sync/shim_sync_client.c#L319)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I mean objects that we could free on Graphene shutdown, but we do not - not a leak strictly speaking, since the OS cleans up after us, but not following good practices?
</blockquote></details>

Not calling `free` in exit is fine, not calling a destructor of an object might be an error.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 235 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4FdYI84ifusEOhXdD:-Mb4FdYI84ifusEOhXdE:b-w7r2zt) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/sync/shim_sync_client.c#L235)):*
> ```C
> void sync_destroy(struct sync_handle* handle) {
>     assert(handle->id != 0);
>     get_sync_handle(handle);
> ```

Wait, what's happening here? Why do you get a refcount here?
Update: ok, this refcounting in this file is wrong. You need to call `get_sync_handle` when you obtain a new reference to an existing handle e.g. copy it from global list and call `put_sync_handle` when you "destroy"(fortget about/release) that reference. There is no point in calling `get_...` at function entry if that handle is passed to it as an argument...
Well, wrong is too harsh, the current version probably works, but has some unnecessary gets/puts.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 459 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4HLMU94G-WGUrOlB1:-Mb4HLMU94G-WGUrOlB2:b-bfyg4m) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/sync/shim_sync_client.c#L459)):*
> ```C
>     size_t off = GET_FROM_CP_MAP(obj);
>     if (!off) {
>         off = ADD_CP_OFFSET(size);
> ```

I think you also need to call `ADD_TO_CP_MAP(obj, off)`
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 482 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4I2lD-yQwNIYXCnhC:-Mb4I2lD-yQwNIYXCnhD:b-5e5res) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/sync/shim_sync_client.c#L482)):*
> ```C
>     __UNUSED(rebase);
> 
>     return sync_init(handle, handle->id);
> ```

I think you are only supposed to return explicitly from these checkpointing functions in case of errors. But well, currently `END_RS_FUNC` is just `return 0`, I would just prefer that tho have some uniformity between all `RS_FUNC`s.


<!-- Sent from Reviewable.io -->

2021-06-01 10:27 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 16 of 18 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 716 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4E92g4Rd5OWyqrtcx:-Mb65G9Q2hcQdsIJ1xct:bb2o1wu) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/bookkeep/shim_handle.c#L716)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We have a `DO_CP_MEMBER` macro for this (tho it's equivalent).
Not blocking - checkpointing is ugly anyway :)
</blockquote></details>

Then I'll keep that this way, for consistency with code for `TYPE_EPOLL` below.

(Also, the `member` parameter would be `info.file.sync`, which works but makes this macro even more confusing than usual.)
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 235 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4FdYI84ifusEOhXdD:-Mb62r8y9Jzs9OqjK41t:b5ua61l) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/sync/shim_sync_client.c#L235)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait, what's happening here? Why do you get a refcount here?
Update: ok, this refcounting in this file is wrong. You need to call `get_sync_handle` when you obtain a new reference to an existing handle e.g. copy it from global list and call `put_sync_handle` when you "destroy"(fortget about/release) that reference. There is no point in calling `get_...` at function entry if that handle is passed to it as an argument...
Well, wrong is too harsh, the current version probably works, but has some unnecessary gets/puts.
</blockquote></details>

OK. My thinking was that taking a reference in every function guards against the user concurrently calling `sync_lock` and `sync_destroy`, but that would be a bug anyway.

Now the ref counting is only in `sync_init` / `sync_destroy`, and when retrieve the handle from hashmap in IPC handlers.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 459 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4HLMU94G-WGUrOlB1:-Mb64q8T5qkvz0j2ZHVh:biw8y1v) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/sync/shim_sync_client.c#L459)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think you also need to call `ADD_TO_CP_MAP(obj, off)`
</blockquote></details>

Right. Done.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 482 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4I2lD-yQwNIYXCnhC:-Mb64uXVEZiuzbeP66NJ:b-jetx8j) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/sync/shim_sync_client.c#L482)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think you are only supposed to return explicitly from these checkpointing functions in case of errors. But well, currently `END_RS_FUNC` is just `return 0`, I would just prefer that tho have some uniformity between all `RS_FUNC`s.
</blockquote></details>

Changed to an error check.


<!-- Sent from Reviewable.io -->

2021-06-01 11:36 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 17 of 18 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 235 at r13](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb4FdYI84ifusEOhXdD:-Mb6GRbE9OPlsPIuLLvV:b-z08r92) ([raw file](https://github.com/oscarlab/graphene/blob/20d68b6baff2eda93a7bf7e5a22c9dab4b0a1c62/LibOS/shim/src/sync/shim_sync_client.c#L235)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK. My thinking was that taking a reference in every function guards against the user concurrently calling `sync_lock` and `sync_destroy`, but that would be a bug anyway.

Now the ref counting is only in `sync_init` / `sync_destroy`, and when retrieve the handle from hashmap in IPC handlers.
</blockquote></details>

But callers of `sync_lock` already need to have the reference for `handle`, so there is no worry that it will disappear or something.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 187 at r14](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb6ITTwBZILu6U9zAxT:-Mb6ITTwBZILu6U9zAxU:bi3qbo3) ([raw file](https://github.com/oscarlab/graphene/blob/c97858f1fed6271ecf263c1ba89897f9fc098a3d/LibOS/shim/src/sync/shim_sync_client.c#L187)):*
> ```C
>     }
> 
>     HASH_ADD(hh, g_client_handles, id, sizeof(id), handle);
> ```

We need to inc ref count here, since you create another reference to this handle and add it to a global list. Also this looks kind of weird that you set a reference count above in a function that already takes a pointer to the object. I think you need to set it to `0` and split adding to the global list from this function into a speparate one.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 255 at r14](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb6GqviB9FgXXZMV2qh:-Mb6GqviB9FgXXZMV2qi:b-mdczl9) ([raw file](https://github.com/oscarlab/graphene/blob/c97858f1fed6271ecf263c1ba89897f9fc098a3d/LibOS/shim/src/sync/shim_sync_client.c#L255)):*
> ```C
>     unlock_client();
> 
>     /* Drop the reference taken in `sync_init()`. */
> ```

That's not true, we are dropping reference accounting for `handle` being on `g_client_handles` here (the delete just above).
Update: ok, it seems to be true, but is still wrong. I think you have two options:
- make this function own the reference it gets as argument (i.e. make callers give it up) and add another `put_*` here
- make this only wait for close + take `handle` off from `g_client_handles` list (the code would stay as it is, but name change would be needed) and make the owners of the parent handle give up the reference to `handle`, i.e.
```c
put_sync_handle(fd_handle->sync_handle);
fd_handle->sync_handle = NULL;
```


<!-- Sent from Reviewable.io -->

2021-06-01 14:25 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-08 10:55 UTC, mkow requested changes
> Reviewed 1 of 13 files at r9, 2 of 8 files at r13, 1 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 7 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_ipc.h, line 427 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mbco_o-2WoSnZPdA1qZ:-Mbco_o-2WoSnZPdA1q_:brzd7dv) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_ipc.h#L427)):*
> ```objc
> int ipc_sysv_semret_callback(struct shim_ipc_msg* msg, IDTYPE src);
> 
> /* SYNC_REQUEST_*, SYNC_CONFIRM_*/
> ```

missing space before `*/`
___
*[LibOS/shim/include/shim_ipc.h, line 433 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbcpR0l1zHBQ1AbQgzB:-MbcpR0l1zHBQ1AbQgzC:b-rsw2ch) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_ipc.h#L433)):*
> ```objc
>     size_t data_size;
>     unsigned char data[];
> };
> ```

This may need changes after https://github.com/oscarlab/graphene/pull/2424 got merged, I think.
___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-Mbcv6Xp41JrZ348Ut6-:b-44b83f) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like the current @pwmarcz's interface with a separate struct. As mentioned, this gives flexibility and can be extended on a case by case basis (e.g., instead of sending a string, send a compressed string -- something like this).

It's a bit weird to see the pattern `if (sync_lock(...)) { can use data}; sync_unlock();`. This makes me think of `sync_lock()` semantics as `trylock()` (i.e., it makes me think that the lock was *not* taken if it returned false). I would prefer `void sync_lock(..., bool* data_updated)`, but this is also quite ugly. Anyway, not blocking on this, the current interface is fine.
</blockquote></details>

I also find the meaning of the retval a bit confusing (for exactly the same reasons as Dima). Unfortunately an out argument would add a lot of boilerplate to such locking, so I'm also fine with something like:
```C
bool updated = sync_lock(...);
if (updated) {
```
OTOH, in the code I see that statement blocks inside such IFs make this less confusing, as they literally update the state from the received struct.

Ad API proposed by Borys: I like it more than current, but it probably won't suffice for more complex types, as Paweł mentioned.
___
*[LibOS/shim/include/shim_sync.h, line 14 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mbd9BKS3P8L340GYp5n:-Mbd9BKS3P8L340GYp5o:b18b4hj) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L14)):*
> ```
>  * - SYNC_STATE_EXCLUSIVE: only one process can have a copy of the handle, but the data stored
>  *   with the handle can be updated
> ```

I have problems understanding this description, if only one process can have such a handle, then what "an update" means for it? Where do you get it from?
___
*[LibOS/shim/include/shim_sync.h, line 156 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdCeeZ-HEinn6QY17j:-MbdCeeZ-HEinn6QY17k:bp7ebam) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L156)):*
> ```
> {client_server}
> ```

Not `,` instead of `_`?
___
*[LibOS/shim/include/shim_sync.h, line 179 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdDQb50RN6DAvL3nJ-:-MbdDQb50RN6DAvL3nJ0:bc6g1y0) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L179)):*
> ```
> messages from server should be disregarded
> ```

But except `CONFIRM_CLOSE`?
___
*[LibOS/shim/include/shim_sync.h, line 208 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdEdax9TEyTY-Hkow8:-MbdEdax9TEyTY-Hkow9:buocae4) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L208)):*
> ```objc
>     /* Notification event for state changes. */
>     PAL_HANDLE event;
>     unsigned int n_waiters;
> ```

Why not `size_t`? I'd feel safer this way :)
___
*[LibOS/shim/include/shim_sync.h, line 267 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdETQIA5McqOsXcxKq:-MbdETQIA5McqOsXcxKr:b-60gkdo) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L267)):*
> ```objc
> void sync_client_message_callback(int code, uint64_t id, int state, size_t data_size, void* data);
> void sync_server_message_callback(IDTYPE src, int code, uint64_t id, int state,
>                                 size_t data_size, void* data);
> ```

please align


<!-- Sent from Reviewable.io -->

2021-06-08 11:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 9 of 18 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 427 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mbco_o-2WoSnZPdA1qZ:-MbfLFiL5v679YhKmPPy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_ipc.h#L427)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing space before `*/`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 433 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbcpR0l1zHBQ1AbQgzB:-MbfLG690Lleo2pJotn5:b-7rr4mg) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_ipc.h#L433)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This may need changes after https://github.com/oscarlab/graphene/pull/2424 got merged, I think.
</blockquote></details>

Rebased after IPC changes.
___
*[LibOS/shim/include/shim_sync.h, line 22 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXHGHFz8hPCNxI42gsp:-MbfM49xD3bpHETPFlmC:bnyj1zn) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/include/shim_sync.h#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I also find the meaning of the retval a bit confusing (for exactly the same reasons as Dima). Unfortunately an out argument would add a lot of boilerplate to such locking, so I'm also fine with something like:
```C
bool updated = sync_lock(...);
if (updated) {
```
OTOH, in the code I see that statement blocks inside such IFs make this less confusing, as they literally update the state from the received struct.

Ad API proposed by Borys: I like it more than current, but it probably won't suffice for more complex types, as Paweł mentioned.
</blockquote></details>

Changed according to your suggestion.
___
*[LibOS/shim/include/shim_sync.h, line 14 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mbd9BKS3P8L340GYp5n:-MbfLpfI0tZ1-0-MNh_r:b1u46a4) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  * - SYNC_STATE_EXCLUSIVE: only one process can have a copy of the handle, but the data stored
>  *   with the handle can be updated
> ```

I have problems understanding this description, if only one process can have such a handle, then what "an update" means for it? Where do you get it from?
</blockquote></details>

Changed to `... and that process is allowed to update the data stored with the handle`.
___
*[LibOS/shim/include/shim_sync.h, line 156 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdCeeZ-HEinn6QY17j:-MbfM9kz9ed_YauFPRFx:bgwt35a) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L156)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> {client_server}
> ```

Not `,` instead of `_`?
</blockquote></details>

Yes. Fixed.
___
*[LibOS/shim/include/shim_sync.h, line 179 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdDQb50RN6DAvL3nJ-:-MbfMH5i71NJoXND9azu:be28xxj) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> messages from server should be disregarded
> ```

But except `CONFIRM_CLOSE`?
</blockquote></details>

Yes. Updated.
___
*[LibOS/shim/include/shim_sync.h, line 208 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdEdax9TEyTY-Hkow8:-MbfMLcwCn4iw-aoQ1Y_:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L208)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not `size_t`? I'd feel safer this way :)
</blockquote></details>

OK.
___
*[LibOS/shim/include/shim_sync.h, line 267 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdETQIA5McqOsXcxKq:-MbfMW-M8ME9Ev9jzbQM:b-k5hmkr) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L267)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please align
</blockquote></details>

Changed after rebase.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 187 at r14](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb6ITTwBZILu6U9zAxT:-Mb6w79B-r216AnBtfz6:b-i0fpog) ([raw file](https://github.com/oscarlab/graphene/blob/c97858f1fed6271ecf263c1ba89897f9fc098a3d/LibOS/shim/src/sync/shim_sync_client.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We need to inc ref count here, since you create another reference to this handle and add it to a global list. Also this looks kind of weird that you set a reference count above in a function that already takes a pointer to the object. I think you need to set it to `0` and split adding to the global list from this function into a speparate one.
</blockquote></details>

As discussed, `sync_init` initializes ref count to 1, and adds another reference here.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 255 at r14](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mb6GqviB9FgXXZMV2qh:-Mb6wNcM6jUjgCTKLHD3:b-9g6f2h) ([raw file](https://github.com/oscarlab/graphene/blob/c97858f1fed6271ecf263c1ba89897f9fc098a3d/LibOS/shim/src/sync/shim_sync_client.c#L255)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That's not true, we are dropping reference accounting for `handle` being on `g_client_handles` here (the delete just above).
Update: ok, it seems to be true, but is still wrong. I think you have two options:
- make this function own the reference it gets as argument (i.e. make callers give it up) and add another `put_*` here
- make this only wait for close + take `handle` off from `g_client_handles` list (the code would stay as it is, but name change would be needed) and make the owners of the parent handle give up the reference to `handle`, i.e.
```c
put_sync_handle(fd_handle->sync_handle);
fd_handle->sync_handle = NULL;
```
</blockquote></details>

Updated: there is an initial reference taken in `sync_init` (ref count initialized to 1), and another one for `g_client_handles`.


<!-- Sent from Reviewable.io -->

2021-06-08 13:21 UTC, boryspoplawski requested changes
> Reviewed 8 of 9 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/ipc/shim_ipc_sync.c, line 40 at r17](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbflLkB6l8gTMLqcmq-:-MbflLkB6l8gTMLqcmq0:b-m7cslk) ([raw file](https://github.com/oscarlab/graphene/blob/d29c5614c8c778e3d6c4858d73050f62c0b5e270/LibOS/shim/src/ipc/shim_ipc_sync.c#L40)):*
> ```C
>     init_ipc_msg(msg, code, total_msg_size);
> 
>     struct shim_ipc_sync* msgin = (void*)&msg->data;
> ```

`msgin` could be unaligned. Please check other places after recent IPC changes for correct usage.
BTW this will change again soon ;)


<!-- Sent from Reviewable.io -->

2021-06-08 14:27 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 16 of 18 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_sync.h, line 267 at r15](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbdETQIA5McqOsXcxKq:-Mbg0KuN9pEVkfv8_c0Q:b-r8wsrc) ([raw file](https://github.com/oscarlab/graphene/blob/6bdf35c180d2dd76270f90f788bae6f9c1f037f1/LibOS/shim/include/shim_sync.h#L267)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Changed after rebase.
</blockquote></details>

Actually, no, it's wasn't this one. Fixed now.


<!-- Sent from Reviewable.io -->

2021-06-08 18:18 UTC, mkow requested changes
> Reviewed 2 of 7 files at r2, 2 of 14 files at r4, 1 of 13 files at r9, 1 of 5 files at r10, 1 of 4 files at r11, 1 of 2 files at r14, 1 of 3 files at r15, 5 of 9 files at r16, 1 of 1 files at r17, 2 of 2 files at r18, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/include/shim_sync.h, line 258 at r19](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mbga86_0nkDBLWQnTYc:-Mbga86_0nkDBLWQnTYd:bkinlis) ([raw file](https://github.com/oscarlab/graphene/blob/a69e9768a69beca947ce765c2d74a9db4c2b36d4/LibOS/shim/include/shim_sync.h#L258)):*
> ```objc
>  * - if state is SYNC_STATE_EXCLUSIVE, no other process is holding a lock in any state
>  */
> bool sync_lock(struct sync_handle* handle, int state, void* data, size_t data_size);
> ```

This could be a good candidate to add `__attribute__((warn_unused_result))` (and `[[nodiscard]]` after we start using C23 someday). We don't use this in other places, but it may be the high time to start :)
___
*[LibOS/shim/src/shim_init.c, line 480 at r19](https://reviewable.io/reviews/oscarlab/graphene/2267#-Mbg6xQg9VNvg5Ejtiax:-Mbg6xQg9VNvg5Ejtiay:b3spfx7) ([raw file](https://github.com/oscarlab/graphene/blob/a69e9768a69beca947ce765c2d74a9db4c2b36d4/LibOS/shim/src/shim_init.c#L480)):*
> ```
> the in the
> ```

:)
___
*[LibOS/shim/src/fs/chroot/fs.c, line 417 at r19](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbgYRsY7LYfyEPz-PTj:-MbgYRsZEw7gGWEyjYSR:b66oacz) ([raw file](https://github.com/oscarlab/graphene/blob/a69e9768a69beca947ce765c2d74a9db4c2b36d4/LibOS/shim/src/fs/chroot/fs.c#L417)):*
> ```C
>     /* files obtained from checkpoint system will have sync handle initialized already */
>     if (!hdl->info.file.sync)
>         ret = sync_create(&hdl->info.file.sync, /*id=*/0);
> ```

What if `ret` was non-zero before this, and then this call succeeds?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-MbghmA23B_eq_xIwY0x:b-33dfwm) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This semantic is very dangerous, do we really want to keep it like this? It's completely invisible in the caller, e.g. it may do something like:

```C
lock();
a = some_locked_var;
sync_wait();
/* use `a` assuming it's still up to date */
unlock();
```

Maybe at least add "_and_relock" to the name?
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 133 at r19](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbgkvKg4DqfadKMbJik:-MbgkvKg4DqfadKMbJil:b-owyzh2) ([raw file](https://github.com/oscarlab/graphene/blob/a69e9768a69beca947ce765c2d74a9db4c2b36d4/LibOS/shim/src/sync/shim_sync_client.c#L133)):*
> ```C
>     int ret = toml_int_in(g_manifest_root, "libos.sync.enable", /*defaultval=*/0, &sync_enable);
>     if (ret < 0 || (sync_enable != 0 && sync_enable != 1)) {
>         log_error("Cannot parse 'libos.sync.enable' (the value must be 0 or 1)\n");
> ```

Please use true / false (and `toml_bool_in()`).


<!-- Sent from Reviewable.io -->

2021-06-08 21:21 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 14 of 18 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-MbhUBW528wudsAQ3hZv:bfdy1x6) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Isn't this a pretty standard pattern? With a condition variable and an associated mutex.

* [pthread_cond_wait](https://linux.die.net/man/3/pthread_cond_wait) / pthread_cond_signal
* [Condition variables](https://en.wikipedia.org/wiki/Monitor_(synchronization)#Condition_variables_2) - with `wait` and `signal / notify` operations.

Or am I misunderstanding something and my usage is subtly different somehow.
</blockquote></details>

Well, it is different here because we don't inherit the critical section from the thread doing the signalling (which is why we have to `sync_wait` in a loop and not just once). But still - the "wait" operation releasing the lock seems standard.


<!-- Sent from Reviewable.io -->

2021-06-09 00:01 UTC, mkow requested changes
> Reviewed 4 of 4 files at r20.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-Mbi3EHQAPZE_aXYApQb:bei97no) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, it's not standard. `pthread_cond_wait` has an explicit argument for a mutex to release while waiting. I didn't like this approach either, but we are at r20 and soon there will be no more space for revisions on my screen :)
Otoh, @mkow is right, it might be easily misused...
</blockquote></details>

Please at least add a suffix to the function name, I really dislike this pattern ;) It's super hard to review multithread code with such semantics.
___
*[LibOS/shim/src/sync/shim_sync_client.c, line 133 at r19](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbgkvKg4DqfadKMbJik:-Mbi3V1h14md_IqVj0vI:bc0zfiq) ([raw file](https://github.com/oscarlab/graphene/blob/a69e9768a69beca947ce765c2d74a9db4c2b36d4/LibOS/shim/src/sync/shim_sync_client.c#L133)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done. I think this change predates our usage of true/false in manifest :)
</blockquote></details>

Yes, it definitely does :)


<!-- Sent from Reviewable.io -->

2021-06-09 07:36 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: 17 of 18 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-Mbjdgs67rTbvJ6cM_ED:b3jdenx) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please at least add a suffix to the function name, I really dislike this pattern ;) It's super hard to review multithread code with such semantics.
</blockquote></details>

Sure, I want to finish this as well. I changed to `sync_wait_without_lock()`, I hope that's good enough for now.

Do you see a better solution? I'll be happy to change this code in the next PRs, it's just that I don't have a good idea how.

Also, by "it's not standard", do you mean that condition variables are not standard (in OS code? in general?), or that their API should be different (i.e. have explicit argument for a mutex)?


<!-- Sent from Reviewable.io -->

2021-06-09 10:31 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r21.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-MbkJjmZ7O8xfTc5jiR0:byqlx0k) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sure, I want to finish this as well. I changed to `sync_wait_without_lock()`, I hope that's good enough for now.

Do you see a better solution? I'll be happy to change this code in the next PRs, it's just that I don't have a good idea how.

Also, by "it's not standard", do you mean that condition variables are not standard (in OS code? in general?), or that their API should be different (i.e. have explicit argument for a mutex)?
</blockquote></details>

I don't have any good idea how to change it other than making this more explicit in its name. Looks acceptable now :)


<!-- Sent from Reviewable.io -->

2021-06-09 14:25 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 4 of 5 files at r21.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-Mbl6Vg2C2vJKy-UdKA_:bjtpyfk) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't have any good idea how to change it other than making this more explicit in its name. Looks acceptable now :)
</blockquote></details>

I meant that such function explicitly take a lock/mutex argument to temporarily relinquish and the caller has to set that, so there is no way they are not aware of such mechanism or forget about it.
In this code: previously callers could be not aware, now they might just forget about it.
I simple idea of a different version: change this function to `sync_wait_for_state` or `sync_wait_for_phase`, which would sleep until a desired state/phase is seen. The assumption would be that it should be called **without** any locks and if it needed a lock it would take that itself.


<!-- Sent from Reviewable.io -->

2021-06-09 21:29 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r22.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-MbmfK1t1d-BIf0XzRtc:b-gtvrm9) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I meant that such function explicitly take a lock/mutex argument to temporarily relinquish and the caller has to set that, so there is no way they are not aware of such mechanism or forget about it.
In this code: previously callers could be not aware, now they might just forget about it.
I simple idea of a different version: change this function to `sync_wait_for_state` or `sync_wait_for_phase`, which would sleep until a desired state/phase is seen. The assumption would be that it should be called **without** any locks and if it needed a lock it would take that itself.
</blockquote></details>

I like Borys idea, but I'm fine with merging the current version. Would be good to change it later.


<!-- Sent from Reviewable.io -->

2021-06-09 22:50 UTC, boryspoplawski approved these changes
> Reviewed 1 of 5 files at r21, 2 of 2 files at r22.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-MblAGXL49DXvIZFlg4D:b-g46qf8) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like Borys idea, but I'm fine with merging the current version. Would be good to change it later.
</blockquote></details>

Otoh it's not that simple: if we spot appropriate state/phase we would like to keep the lock, not release it...


<!-- Sent from Reviewable.io -->

2021-06-10 05:48 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/sync/shim_sync_client.c, line 56 at r5](https://reviewable.io/reviews/oscarlab/graphene/2267#-MXI7JKl1n-JIPFdJqlZ:-MboMguYBHjsX6MqcW7e:b-y7qsal) ([raw file](https://github.com/oscarlab/graphene/blob/84d2992c934b2adbbe22888c6df5c8de8bb01003/LibOS/shim/src/sync/shim_sync_client.c#L56)):*
>I like Borys idea, but I'm fine with merging the current version. Would be good to change it later.

Yes, I said "in the next PRs", this has gone for too long for last minute changes like this :)

I think with the current mechanism (mutex + event) the best I can do is manually inline `sync_wait` at both call sites. That should make it clear that the lock is released. However, it might be better to use a wait queue like we do with futexes.


<!-- Sent from Reviewable.io -->

2021-06-10 07:16 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_sync.h, line 266 at r22](https://reviewable.io/reviews/oscarlab/graphene/2267#-MbokOzj67D18wbk9IsA:-MbokOzk7gYDPk8iK5zZ:bqtiv9l) ([raw file](https://github.com/oscarlab/graphene/blob/2bdee97ab8715d40cc6e20d3a30e5d1c5c5f9426/LibOS/shim/include/shim_sync.h#L266)):*
> ```objc
> /*** Message handlers (called from IPC, see ipc/shim_ipc_sync.c) ***/
> 
> struct shim_ipc_port;
> ```

This seems to be not needed. Not blocking, but let's fix in some follow-up PR.


<!-- Sent from Reviewable.io -->

2021-06-10 07:17 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2267)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-10 07:20 UTC, merged