[LibOS] Change reported exit reason on IPC disconnection
oscarlab/graphene pull request #2270
Opened 2021-03-25 09:41 UTC by boryspoplawski

## Description of the changes 
If IPC pipe is disconnected (without proper cleanup), Graphene reported that as child dying due to a SIGKILL. Now we use SIGPWR in such scenario, to be able to distinquish this case from a genuine SIGKILL.
Hopefully, SIGPWR is not used too often.

2021-03-25 10:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2270#-MWcqGf38VS-AuLKhJPF:-MWcqGf38VS-AuLKhJPG:b-1hg25b) (no related file):*
This PR is fine, but did you test it locally? Does it actually help in detecting such errors?

---


<!-- Sent from Reviewable.io -->

2021-03-25 10:07 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2270#-MWcqGf38VS-AuLKhJPF:-MWcqMu52OI3tQyB44Mm:b-df0ny5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This PR is fine, but did you test it locally? Does it actually help in detecting such errors?
</blockquote></details>

We can run this PR 10 times, I bet we'll see some IPC-disconnect error during these 10 runs, and we'll be able to judge whether SIGPWR helps.

---


<!-- Sent from Reviewable.io -->

2021-03-25 10:09 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2270#-MWcqGf38VS-AuLKhJPF:-MWcqjy9DMNs9EnCljbp:b-31bsxc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can run this PR 10 times, I bet we'll see some IPC-disconnect error during these 10 runs, and we'll be able to judge whether SIGPWR helps.
</blockquote></details>

I'm usually unable to trigger these IPC issues locally, so let's hope Jenkins will hit something.

---


<!-- Sent from Reviewable.io -->

2021-03-25 10:11 UTC, boryspoplawski commented
Jenkins, retest this please (2/10)

2021-03-25 10:31 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX please (`udp` from LibOS failed, known issue)

2021-03-25 11:48 UTC, boryspoplawski commented
Jenkins, retest this please (3/10)

2021-03-25 13:36 UTC, boryspoplawski commented
Jenkins, retest this please (5/10)

2021-03-25 13:37 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2270#-MWdaY55EuPyLrP48Ufr:-MWdaY562ueN5XQYnbH0:buhbqhu) ([raw file](https://github.com/oscarlab/graphene/blob/4a5aa2b9d2b82d28e600c68d916dfc2403e417eb/LibOS/shim/src/ipc/shim_ipc_child.c#L29)):*
> ```C
>      * (and so the host OS closed all its sockets). This may happen before arrival of the expected
>      * IPC_MSG_CHILDEXIT message from child process. In such case report that the child process was
>      * killed by SIGPWR (we've picked this signal hoping that nothing really uses it).
> ```

Could you be more precise here? I.e. include the reason why we use such a weird signal.


<!-- Sent from Reviewable.io -->

2021-03-25 16:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc_child.c, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene/2270#-MWdaY55EuPyLrP48Ufr:-MWeAYxXCUPiz8rt_Jxa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4a5aa2b9d2b82d28e600c68d916dfc2403e417eb/LibOS/shim/src/ipc/shim_ipc_child.c#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you be more precise here? I.e. include the reason why we use such a weird signal.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 16:21 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-03-25 16:34 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-03-25 18:01 UTC, boryspoplawski commented
Jenkins, retest this please (7/10)

2021-03-25 18:42 UTC, boryspoplawski commented
Jenkins, retest this please (8/10)

2021-03-25 23:44 UTC, mkow commented
Jenkins, retest this please (8/10) (previous run conflicted with 20.04 introduction to CI)

2021-03-26 00:17 UTC, mkow commented
Jenkins, retest this please (9/10)

2021-03-26 00:56 UTC, mkow commented
Jenkins, retest this please (10/10)

2021-03-26 01:33 UTC, mkow commented
@boryspoplawski FYI: on the last run Jenkins-Debug failed with a timeout on `apps.LTP.kill11` and Jenkins-SGX on `test_libos.TC_80_Socket.test_200_socket_udp` with just "recvfrom() failed". Let's merge this PR and wait for the bug in question to reproduce somewhere else.

2021-03-26 01:36 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-03-26 02:26 UTC, mkow commented
Jenkins, retest Jenkins-SGX please (`test_libos.TC_80_Socket.test_200_socket_udp` failed with "recvfrom() failed" again)

2021-03-26 05:23 UTC, boryspoplawski commented
Jenkins, retest this please

2021-03-26 06:28 UTC, boryspoplawski commented
Jenkins, retest this please

2021-03-26 06:47 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2270)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-26 07:25 UTC, merged