[CI] Add Ubuntu 20.04 LTS (focal) pipelines
oscarlab/graphene pull request #2272
Opened 2021-03-25 15:28 UTC by woju

## Description of the changes 

This adds pipelines for testing Ubuntu 20.04.

## How to test this PR? 

20.04 pipelines should pass (I shall add them shortly).

2021-03-25 15:59 UTC, mkow requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWe4hKA3wJ3p1CGh72P:-MWe4hKA3wJ3p1CGh72Q:b-sxm04w) (no related file):*
Please drop 16.04 pipelines.

---
___
*[.ci/ubuntu20.04.docker, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWe4d0z6JNB8UniK1Bz:-MWe4d0z6JNB8UniK1C-:bsk7wix) ([raw file](https://github.com/oscarlab/graphene/blob/4f60f98d22febfdebd28435a4dbd75ef0deb2d60/.ci/ubuntu20.04.docker#L1)):*
> ```
> # Start with 18.04
> ```

please update (or just remove this comment)


<!-- Sent from Reviewable.io -->

2021-03-25 19:11 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWe4hKA3wJ3p1CGh72P:-MWen1Yd3_e9YIu1pGWQ:b-8sfuw6) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please drop 16.04 pipelines.
</blockquote></details>

#2273

---
___
*[.ci/ubuntu20.04.docker, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWe4d0z6JNB8UniK1Bz:-MWen8Z--NHp-sNdfwgg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4f60f98d22febfdebd28435a4dbd75ef0deb2d60/.ci/ubuntu20.04.docker#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please update (or just remove this comment)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 19:42 UTC, woju commented
Jenkins test this please

2021-03-25 23:10 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: 5 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWfPlrJ9_An6Qsrr6Vc:-MWfPlrN26ad03Lch4nm:bwltuz) (no related file):*
```
+ make -C Examples/memcached distclean
make: Entering directory '/tmp/graphene-sgx-20.04.clean-check.test/Examples/memcached'
Makefile:27: *** This example requires Ubuntu 16.04 or 18.04.  Stop.
make: Leaving directory '/tmp/graphene-sgx-20.04.clean-check.test/Examples/memcached'
```

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWf_PVIADFNJ31gVNfW:bdl8fc6) (no related file):*
```
  [ host/Skeleton/libpal.so ]
ld: host/Skeleton/.obj/db_exception.o: in function `warn':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_exception.c:41: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `load_libraries':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:66: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `insert_envs_from_manifest':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:154: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `set_debug_type':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:208: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `load_cstring_array':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:266: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_misc.o:/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_misc.c:53: more undefined references to `__stack_chk_fail' follow
make: *** [Makefile:116: host/Skeleton/libpal.so] Error 1
make: Leaving directory '/home/jenkins/workspace/graphene-debug-20.04/Pal/src'
```

---


<!-- Sent from Reviewable.io -->

2021-03-25 23:52 UTC, mkow reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWe4hKA3wJ3p1CGh72P:-MWflyM_42Yao25jQq0K:bwcpo7e) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

#2273
</blockquote></details>

Will leave this blocking until we merge #2273 (we don't have enough capacity to run all three configs at the same time)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWfPlrJ9_An6Qsrr6Vc:-MWfmKNO5ckodKWIcfnU:b-ggbtbw) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```
+ make -C Examples/memcached distclean
make: Entering directory '/tmp/graphene-sgx-20.04.clean-check.test/Examples/memcached'
Makefile:27: *** This example requires Ubuntu 16.04 or 18.04.  Stop.
make: Leaving directory '/tmp/graphene-sgx-20.04.clean-check.test/Examples/memcached'
```
</blockquote></details>

My guess is that you can drop this check and try without it, after trusted directories support it should work out of the box I think.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWfmqSuEnfNqgn5Zqey:bvxmk49) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```
  [ host/Skeleton/libpal.so ]
ld: host/Skeleton/.obj/db_exception.o: in function `warn':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_exception.c:41: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `load_libraries':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:66: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `insert_envs_from_manifest':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:154: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `set_debug_type':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:208: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_main.o: in function `load_cstring_array':
/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_main.c:266: undefined reference to `__stack_chk_fail'
ld: host/Skeleton/.obj/db_misc.o:/home/jenkins/workspace/graphene-debug-20.04/Pal/src/db_misc.c:53: more undefined references to `__stack_chk_fail' follow
make: *** [Makefile:116: host/Skeleton/libpal.so] Error 1
make: Leaving directory '/home/jenkins/workspace/graphene-debug-20.04/Pal/src'
```
</blockquote></details>

We should either copy our `__stack_chk_fail()` implementation to Skeleton PAL or disable stack protector in its makefiles.

@boryspoplawski, @dimakuv: any preferences or other ideas?

---


<!-- Sent from Reviewable.io -->

2021-03-26 07:01 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWfPlrJ9_An6Qsrr6Vc:-MWhIsVG1qSuGyCLxKbn:b-l5nz1f) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

My guess is that you can drop this check and try without it, after trusted directories support it should work out of the box I think.
</blockquote></details>

We have two such cases:
- Blender whitelists Ubuntu 16, 18, and 20: https://github.com/oscarlab/graphene/blob/fd8b41e053158bf881806f808c43d1486e9e18c2/Examples/blender/Makefile#L17-L22
- Memcached whitelists only Ubuntu 16 and 18: https://github.com/oscarlab/graphene/blob/17ab04db59e6c789d5979addac6976765425efbf/Examples/memcached/Makefile#L24-L28

I agree with Michal that we should simply delete these checks. After Michal's https://github.com/oscarlab/graphene/pull/2269 the OS distro wouldn't be that important for Graphene.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWhJufS589EaeCIHoR9:b-vu1a2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We should either copy our `__stack_chk_fail()` implementation to Skeleton PAL or disable stack protector in its makefiles.

@boryspoplawski, @dimakuv: any preferences or other ideas?
</blockquote></details>

Let's add this function to Skeleton PAL, similar to this but with empty body: https://github.com/oscarlab/graphene/blob/593e5d3f93ea75729f4adb0a4f685d62f51259de/LibOS/shim/src/shim_init.c#L46-L51.

I suggest to add this function here: https://github.com/oscarlab/graphene/blob/fd8b41e053158bf881806f808c43d1486e9e18c2/Pal/src/host/Skeleton/db_misc.c

---


<!-- Sent from Reviewable.io -->

2021-03-26 07:38 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWhSW9t4p7L9VCNGVj0:btgb6y8) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's add this function to Skeleton PAL, similar to this but with empty body: https://github.com/oscarlab/graphene/blob/593e5d3f93ea75729f4adb0a4f685d62f51259de/LibOS/shim/src/shim_init.c#L46-L51.

I suggest to add this function here: https://github.com/oscarlab/graphene/blob/fd8b41e053158bf881806f808c43d1486e9e18c2/Pal/src/host/Skeleton/db_misc.c
</blockquote></details>

Actually, why this function is not in shared Pal? Or even in lib (i.e. shared with LibOS as well)?

---


<!-- Sent from Reviewable.io -->

2021-03-26 07:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWhWfj_0YNl0OJ3d877:bcaiuwv) (no related file):*
> Actually, why this function is not in shared Pal? Or even in lib (i.e. shared with LibOS as well)?

But in `lib`, you don't have any way of printing messages. (And you probably don't have any way of aborting.)

This function is also different in PAL and in LibOS, this is intentional. PAL uses its own way of panicking, LibOS uses its own way.

And I'm not sure it makes sense to share this function across PALs. In Skeleton for example, this function is a noop (what's the point of having a Skeleton function that prints some error message? Skeleton doesn't have a notion of printing.).

---


<!-- Sent from Reviewable.io -->

2021-03-26 08:05 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWhY5wCEXgUZqfd9bWX:b-a3cpsx) (no related file):*
> But in lib, you don't have any way of printing messages. (And you probably don't have any way of aborting.)

We used to have `warn` Pal API function which was available everywhere. Actually seems we still do. `__abort` is too available everywhere.
> This function is also different in PAL and in LibOS, this is intentional. PAL uses its own way of panicking, LibOS uses its own way.

Sure, but that's not a problem. We have prototypes of all needed functions and their implementation could be different, depending what this is compiled into.

Actually, I'll try to cook a quick PR, let's see if that's doable.

---


<!-- Sent from Reviewable.io -->

2021-03-26 08:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWhbfjlDOIaP0OTSFL2:bjz0i8q) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> But in lib, you don't have any way of printing messages. (And you probably don't have any way of aborting.)

We used to have `warn` Pal API function which was available everywhere. Actually seems we still do. `__abort` is too available everywhere.
> This function is also different in PAL and in LibOS, this is intentional. PAL uses its own way of panicking, LibOS uses its own way.

Sure, but that's not a problem. We have prototypes of all needed functions and their implementation could be different, depending what this is compiled into.

Actually, I'll try to cook a quick PR, let's see if that's doable.
</blockquote></details>

I thought we had different interfaces for printing and panicking. But sure, if everything can be done with `want() + abort()`, then we can consolidate this.

---


<!-- Sent from Reviewable.io -->

2021-03-26 08:32 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWheN5l1L3YTFzJNOwf:b-8sfuw5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I thought we had different interfaces for printing and panicking. But sure, if everything can be done with `want() + abort()`, then we can consolidate this.
</blockquote></details>

#2274

---


<!-- Sent from Reviewable.io -->

2021-03-26 11:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWiAq9GAJ3kP9b4INtm:b740p0i) (no related file):*
> Let's add this function to Skeleton PAL, similar to this but with empty body:

Noo, this is a very bad idea (to leave it empty). When bootstrapping a new PAL from it you would end up with stack cookie checks silently nopped out, despite providing that option to the compiler.

Anyways, seems that Borys already solved this issue.

---


<!-- Sent from Reviewable.io -->

2021-03-26 11:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWiHYPc9m5OdzLgjuyx:bnnme3) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Let's add this function to Skeleton PAL, similar to this but with empty body:

Noo, this is a very bad idea (to leave it empty). When bootstrapping a new PAL from it you would end up with stack cookie checks silently nopped out, despite providing that option to the compiler.

Anyways, seems that Borys already solved this issue.
</blockquote></details>

Borys fixed this in #2274 and it was already merged. So this issue should be fixed after this PR is rebased on current master.

---


<!-- Sent from Reviewable.io -->

2021-03-29 14:43 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: 6 of 9 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWe4hKA3wJ3p1CGh72P:-MWyR997Bu8wA4lJJpnd:b2nha9w) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will leave this blocking until we merge #2273 (we don't have enough capacity to run all three configs at the same time)
</blockquote></details>

ACK

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWfPlrJ9_An6Qsrr6Vc:-MWyR2q-AZ3tvVuJfOjt:b-iji3m9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We have two such cases:
- Blender whitelists Ubuntu 16, 18, and 20: https://github.com/oscarlab/graphene/blob/fd8b41e053158bf881806f808c43d1486e9e18c2/Examples/blender/Makefile#L17-L22
- Memcached whitelists only Ubuntu 16 and 18: https://github.com/oscarlab/graphene/blob/17ab04db59e6c789d5979addac6976765425efbf/Examples/memcached/Makefile#L24-L28

I agree with Michal that we should simply delete these checks. After Michal's https://github.com/oscarlab/graphene/pull/2269 the OS distro wouldn't be that important for Graphene.
</blockquote></details>

Checks removed, let's see what happens.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MWyR69w8WaCXrXKNQVB:b-r8gail) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Borys fixed this in #2274 and it was already merged. So this issue should be fixed after this PR is rebased on current master.
</blockquote></details>

Rebased, let's see.

---


<!-- Sent from Reviewable.io -->

2021-03-29 15:03 UTC, mkow reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2021-03-29 15:21 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-03-29 15:22 UTC, boryspoplawski reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-03-29 15:23 UTC, boryspoplawski reviewed
> Reviewed 4 of 6 files at r1, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-03-30 06:33 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2021-04-20 21:45 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: 5 of 13 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWfPlrJ9_An6Qsrr6Vc:-MYlEaohA1dVGB8CiMnG:b-34794p) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Checks removed, let's see what happens.
</blockquote></details>

Looks like tests passed.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MWf_PVF2YSfXFdB1E6i:-MYlEeVy1l_yz5e50l-0:bt2vr1b) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Rebased, let's see.
</blockquote></details>

Fixed.

---


<!-- Sent from Reviewable.io -->

2021-04-20 22:05 UTC, boryspoplawski commented
Jenkins, retest Jenkins-20.04 please (unrelated IPC failure)

2021-04-20 22:12 UTC, boryspoplawski requested changes
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[Documentation/devel/packaging.rst, line 26 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK-tSBj4TmHiyjoWu:-MYlK-tSBj4TmHiyjoWv:b-ikxvbu) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L26)):*
> ```reStructuredText
> Glibc is a special case, because we need to provide the version supported by the
> distribution **or a later version**, which is inverse from the usual dependency
> relation that we need to support the version from distro or earlier. Therefore
> ```

Truncated?
___
*[Documentation/devel/packaging.rst, line 28 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK6YfDxi4vgYoXuvn:-MYlJzWyDkYDSfyFpvRu:b-pbfp37) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L28)):*
> ```reStructuredText
> relation that we need to support the version from distro or earlier. Therefore
> 
> varia
> ```

What is `varia`?


<!-- Sent from Reviewable.io -->

2021-04-20 22:28 UTC, mkow requested changes
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK87c-EqQI7AX8CgN:-MYlK87dB8vl7pkJA8af:bergykt) (no related file):*
"[Documentation] Distro support policy"

Should be: "[Docs] Add distro support policy"

---
___
*[Documentation/devel/packaging.rst, line 5 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKnV-0uQgeTKFNzHQ:-MYlKnV-0uQgeTKFNzHR:brt2f5a) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L5)):*
> ```reStructuredText
> 
> Graphene project aims to support two most recent releases of the long-lived
> distributions (eg. Debian, Ubuntu LTS, [the CentOS replacement that will
> ```

`eg.` -> `e.g.`
___
*[Documentation/devel/packaging.rst, line 6 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKLA16zKxZSXyO_O2:-MYlKLA16zKxZSXyO_O3:b-fc7g16) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L6)):*
> ```reStructuredText
> Graphene project aims to support two most recent releases of the long-lived
> distributions (eg. Debian, Ubuntu LTS, [the CentOS replacement that will
> hopefuly emerge soon], ...).
> ```

`hopefuly` -> `hopefully`
___
*[Documentation/devel/packaging.rst, line 8 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKuQ38FzaSpJ5IT0V:-MYlKuQ38FzaSpJ5IT0W:bfw8dna) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L8)):*
> ```reStructuredText
> hopefuly emerge soon], ...).
> 
> Currently supported distributions:
> ```

`Currently supported` -> `Currently officially supported`
___
*[Documentation/devel/packaging.rst, line 41 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlM25z9xUdQGSK8v0J:-MYlM25z9xUdQGSK8v0K:b-9d0duv) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L41)):*
> ```reStructuredText
> 
> Distro support policy was inspired by `Libvirt's policy
> <https://libvirt.org/platforms.html>`__.
> ```

Was it actually inspired by anything and is it worth mentioning? Our whole policy is just "we support 2 latest Ubuntu LTSes".


<!-- Sent from Reviewable.io -->

2021-04-21 17:54 UTC, woju commented
Jenkins, test Jenkins-Debug-20.04 please

2021-04-21 17:55 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: 9 of 13 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @donporter, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK87c-EqQI7AX8CgN:-MYpPf4x51b4nbkWoNt_:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"[Documentation] Distro support policy"

Should be: "[Docs] Add distro support policy"
</blockquote></details>

Done.

---
___
*[Documentation/devel/packaging.rst, line 5 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKnV-0uQgeTKFNzHQ:-MYpPt5C-vji0AOs_DvK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`eg.` -> `e.g.`
</blockquote></details>

Done.
___
*[Documentation/devel/packaging.rst, line 6 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKLA16zKxZSXyO_O2:-MYpPtNM1Bii0L0Cp_CE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`hopefuly` -> `hopefully`
</blockquote></details>

Done.
___
*[Documentation/devel/packaging.rst, line 8 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKuQ38FzaSpJ5IT0V:-MYpQ0NJ6m5bosA3rLp8:bp4wzmy) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Currently supported` -> `Currently officially supported`
</blockquote></details>

Looks like too many adjectives to me...
___
*[Documentation/devel/packaging.rst, line 26 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK-tSBj4TmHiyjoWu:-MYpOeuDATATJ-9TlP2-:b-7xtei2) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Truncated?
</blockquote></details>

Yeah.
___
*[Documentation/devel/packaging.rst, line 28 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK6YfDxi4vgYoXuvn:-MYpJYiQ8PntbObnQvQy:b8iit6x) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L28)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What is `varia`?
</blockquote></details>

Latin for "miscellany", used in Polish and English alike. https://www.merriam-webster.com/dictionary/varia
___
*[Documentation/devel/packaging.rst, line 41 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlM25z9xUdQGSK8v0J:-MYpJcYt3UEUT2d9jhbX:bocme4p) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Was it actually inspired by anything and is it worth mentioning? Our whole policy is just "we support 2 latest Ubuntu LTSes".
</blockquote></details>

Nope, I did read through various projects' docs in search for a good template. This one stood out to me as a sensible template, so I copied the approach here. I agree there is a limited number of viable approaches, so this isn't very innovative, but I dunno.

Maybe we can ask the scientists, they should know if acknowledgment is due? @donporter ^


<!-- Sent from Reviewable.io -->

2021-04-21 18:03 UTC, mkow reviewed
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @donporter)

___
*[Documentation/devel/packaging.rst, line 8 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKuQ38FzaSpJ5IT0V:-MYp_TAV5ysq29Mc7aQv:bgqsejd) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Looks like too many adjectives to me...
</blockquote></details>

I agree that it doesn't sound nice, but the old version seemed like other distros are not supported, which is not true - I think Graphene works on Fedora and CentOS, as people sometimes submit patches once we break them. They are just not officially declared as supported.


<!-- Sent from Reviewable.io -->

2021-04-21 18:13 UTC, boryspoplawski approved these changes
@woju for the future, please add a reason why you restart a pipeline

> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272#-:-MYpc8jD-Rr0MPQJhrG8:bvreh0y)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @donporter)



<!-- Sent from Reviewable.io -->

2021-04-21 18:25 UTC, woju reviewed
OK

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272#-:-MYpfOz4Dw81actDqT5d:b32w0x)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @donporter)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK87c-EqQI7AX8CgN:-MYperpVBsLn7hMIuJkK:b-pu5t8y) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like reviewable got confused by this rename, stats and diffs for devel/packaging.rst are funny.

---
___
*[Documentation/devel/packaging.rst, line 8 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKuQ38FzaSpJ5IT0V:-MYpf6zt6uyAU6lLqfm6:b-vfoe5n) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I agree that it doesn't sound nice, but the old version seemed like other distros are not supported, which is not true - I think Graphene works on Fedora and CentOS, as people sometimes submit patches once we break them. They are just not officially declared as supported.
</blockquote></details>

That's pretty much the meaning of just "supported". Even "not supported" doesn't mean "doesn't work", it's just you're on your own.


<!-- Sent from Reviewable.io -->

2021-04-21 19:09 UTC, donporter reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Documentation/devel/packaging.rst, line 41 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlM25z9xUdQGSK8v0J:-MYppNTA9FVuV_vuXzW4:b9cfzwy) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L41)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Nope, I did read through various projects' docs in search for a good template. This one stood out to me as a sensible template, so I copied the approach here. I agree there is a limited number of viable approaches, so this isn't very innovative, but I dunno.

Maybe we can ask the scientists, they should know if acknowledgment is due? @donporter ^
</blockquote></details>

idk.  Can't hurt, but also doesn't seem like the result of particular creativity.


<!-- Sent from Reviewable.io -->

2021-04-21 22:17 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @donporter and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlK87c-EqQI7AX8CgN:-MYqUoJa2vxJNIG-BXV5:b9odhl0) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Looks like reviewable got confused by this rename, stats and diffs for devel/packaging.rst are funny.
</blockquote></details>

Nah, they look right for me. You sure you have proper diff ranges selected?

---
___
*[Documentation/devel/packaging.rst, line 8 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlKuQ38FzaSpJ5IT0V:-MYqUujpEbsdN_iRjYpM:bp7mhes) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

That's pretty much the meaning of just "supported". Even "not supported" doesn't mean "doesn't work", it's just you're on your own.
</blockquote></details>

I read this a bit different, usually when you see e.g. a list of "supported architectures" or "supported OSes" by some app then anything outside that won't work. Here we have some distros with non-official support by volunteers.
___
*[Documentation/devel/packaging.rst, line 41 at r5](https://reviewable.io/reviews/oscarlab/graphene/2272#-MYlM25z9xUdQGSK8v0J:-MYqVWlX4g-Q4SMuI_He:b-m9yc4c) ([raw file](https://github.com/oscarlab/graphene/blob/14e64ff212f06540980a99c7eafcb0b34f604ede/Documentation/devel/packaging.rst#L41)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

idk.  Can't hurt, but also doesn't seem like the result of particular creativity.
</blockquote></details>

I'd drop this just to make the document shorter, but I'm not blocking.


<!-- Sent from Reviewable.io -->

2021-04-21 22:49 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (weird host VDSO crash???)

2021-04-22 00:09 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (previous run was ok)

2021-04-22 00:29 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (Jenkins interned connection problems, unrelated)

2021-04-22 01:01 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (previous run was ok)

2021-04-22 01:39 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (previous run was ok)

2021-04-22 07:36 UTC, dimakuv approved these changes
> Reviewed 4 of 8 files at r5, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: all files reviewed, 1 unresolved discussion (waiting on @donporter and @woju)



<!-- Sent from Reviewable.io -->

2021-04-22 07:37 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2272)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-22 10:19 UTC, merged