Work around problems with uthash and `_FORTIFY_SOURCE`
oscarlab/graphene pull request #2277
Opened 2021-03-29 11:23 UTC by pwmarcz

These changes enable me to use uthash in LibOS. I found out that disabling `_FORTIFY_SOURCE` is necessary. However, since it took me some time to identify the problem (I got confusing linker errors for `__memcpy_chk` etc.), I decided to comment this better, and also make uthash more nostdlib-friendly in case something else comes up.

(First discussed in #2267).

## How to test this PR? 

If things still compile with no warnings, we should be OK.

2021-03-29 12:01 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 0 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWxp-xy8Sa5tjD2Czkw:b-mbrzsi) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
> ```Makefile
> # Forcefully disable _FORTIFY_SOURCE: causes conflicts when including glibc headers (e.g. defines
> # memcpy to use __memcpy_chk)
> CFLAGS += -Wp,-U_FORTIFY_SOURCE
> ```

Please don't disable this, it's a security measure. I think correct solution for the uthash problems is just adding the missing functions (`__memcpy_chk`, etc.) to Pal/lib/. These are normally implemented by glibc, but since we're on our own, we need to implement them in our code.
The most important thing is that `_FORTIFY_SOURCE` set to at least 1 enables compile-time checks for string/memory operations correctness.


<!-- Sent from Reviewable.io -->

2021-03-29 12:21 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 5 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWxvB4lBPkbX_b2hGW5:b3irqrg) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't disable this, it's a security measure. I think correct solution for the uthash problems is just adding the missing functions (`__memcpy_chk`, etc.) to Pal/lib/. These are normally implemented by glibc, but since we're on our own, we need to implement them in our code.
The most important thing is that `_FORTIFY_SOURCE` set to at least 1 enables compile-time checks for string/memory operations correctness.
</blockquote></details>

Hm, we should probably split this PR into two PRs then :)

I think the `uthash.patch` commit raises no questions, so that part can be quickly merged. But this part with FORTIFY_SOURCE may take some time to agree on. In general, I agree with Michal that we can simply add all these "hardened" C functions, but this may take time and effort, so I'd prefer to split it in a separate PR.


<!-- Sent from Reviewable.io -->

2021-03-29 12:43 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWxxcBuD_DdtkImIDHD:b-hbaa1d) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
>Please don't disable this, it's a security measure.

Does that actually disable anything? As far as I know, `_FORTIFY_SOURCE` is a feature of glibc.

> I think correct solution for the uthash problems is just adding the missing functions (__memcpy_chk, etc.) to Pal/lib/. These are normally implemented by glibc, but since we're on our own, we need to implement them in our code.

Okay, as @dimakuv suggested, I can do that in separate PR. 

But it's not enough to define `__memcpy_chk`, you need to also define `memcpy` to use it (and same for other functions). Glibc provides an inline definition, see `string_fortified.h`:

```
__fortify_function void *
__NTH (memcpy (void *__restrict __dest, const void *__restrict __src,
	       size_t __len))
{
  return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
}
```

(Which expands to `inline void *memcpy` with a bunch of attributes like `always_inline` and `artificial`).

So, it seems that as a result, glibc headers like `string.h` will still be unincludable by us (as the definition would be duplicated). Is that OK?


<!-- Sent from Reviewable.io -->

2021-03-29 12:51 UTC, mkow submitted a review, later dismissed
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy0bkX2O4osaE1cMNZ:-MWy0bkX2O4osaE1cMN_:b82c0e3) (no related file):*
The commit message is now out of date.

---
___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWy0JCn7u0tlQ3JDiap:bmgqpn7) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Please don't disable this, it's a security measure.

Does that actually disable anything? As far as I know, `_FORTIFY_SOURCE` is a feature of glibc.

> I think correct solution for the uthash problems is just adding the missing functions (__memcpy_chk, etc.) to Pal/lib/. These are normally implemented by glibc, but since we're on our own, we need to implement them in our code.

Okay, as @dimakuv suggested, I can do that in separate PR. 

But it's not enough to define `__memcpy_chk`, you need to also define `memcpy` to use it (and same for other functions). Glibc provides an inline definition, see `string_fortified.h`:

```
__fortify_function void *
__NTH (memcpy (void *__restrict __dest, const void *__restrict __src,
	       size_t __len))
{
  return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
}
```

(Which expands to `inline void *memcpy` with a bunch of attributes like `always_inline` and `artificial`).

So, it seems that as a result, glibc headers like `string.h` will still be unincludable by us (as the definition would be duplicated). Is that OK?
</blockquote></details>

I think that's fine, ideally we should not include any non-graphene headers at all, as we don't use system-provided libc.


<!-- Sent from Reviewable.io -->

2021-03-29 13:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy0bkX2O4osaE1cMNZ:-MWy5jZWEaXYGai9J8kc:b-jgajh0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The commit message is now out of date.
</blockquote></details>

Why? PAL disables`_FORTIFY_SOURCE` since beginning of Git history, I think this is the reason.

---


<!-- Sent from Reviewable.io -->

2021-03-29 13:13 UTC, dimakuv requested changes
> Reviewed 3 of 8 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWy6EC05o0svBjL_LLs:bt55xa9) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think that's fine, ideally we should not include any non-graphene headers at all, as we don't use system-provided libc.
</blockquote></details>

I'm resolving it here for now, but it looks like Pawel's original decision to undefine `FORTIFY_SOURCE` was correct. So feel free to create a new PR with the same changes as you first introduced here.
___
*[Pal/lib/Makefile, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy62WJ4lS3of3Z0Hif:-MWy62WJ4lS3of3Z0Hig:brvtcsc) ([raw file](https://github.com/oscarlab/graphene/blob/ead4268490d84114ed088916e07f3b679dba7935/Pal/lib/Makefile#L205)):*
> ```Makefile
> 	$(RM) -r crypto/$(MBEDTLS_SRC) crypto/$(MBEDCRYPTO_SRC) crypto/mbedtls
> 	$(RM) ../include/lib/uthash.h
> 	$(RM) ../include/lib/toml.h toml.h toml.c toml.patched uthash.o uthash.patched
> ```

`uthash.o`? But uthash is header-only...


<!-- Sent from Reviewable.io -->

2021-03-29 13:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWy7Pkl8lSJuRIEiebI:bu04jio) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm resolving it here for now, but it looks like Pawel's original decision to undefine `FORTIFY_SOURCE` was correct. So feel free to create a new PR with the same changes as you first introduced here.
</blockquote></details>

Well, I agree it's better to have the additional security measures, so hopefully they won't be hard to add.
___
*[Pal/lib/Makefile, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy62WJ4lS3of3Z0Hif:-MWy7K4n4K4QyE7Eljyz:bxqbo1e) ([raw file](https://github.com/oscarlab/graphene/blob/ead4268490d84114ed088916e07f3b679dba7935/Pal/lib/Makefile#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`uthash.o`? But uthash is header-only...
</blockquote></details>

Typo, should be `uthash.h`. Fixed.


<!-- Sent from Reviewable.io -->

2021-03-29 13:18 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/lib/Makefile, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy62WJ4lS3of3Z0Hif:-MWy7cVTBweXU5RJmAiA:b4du2pu) ([raw file](https://github.com/oscarlab/graphene/blob/ead4268490d84114ed088916e07f3b679dba7935/Pal/lib/Makefile#L205)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Typo, should be `uthash.h`. Fixed.
</blockquote></details>

Now you have too many `../include/lib/uthash.h` (here and in the above line) :)


<!-- Sent from Reviewable.io -->

2021-03-29 13:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/lib/Makefile, line 205 at r3](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy62WJ4lS3of3Z0Hif:-MWy98km4xGQz4_eOEuO:b-yw5fnz) ([raw file](https://github.com/oscarlab/graphene/blob/ead4268490d84114ed088916e07f3b679dba7935/Pal/lib/Makefile#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have too many `../include/lib/uthash.h` (here and in the above line) :)
</blockquote></details>

Oh, right, I didn't notice the previous line was for uthash. That looks better.


<!-- Sent from Reviewable.io -->

2021-03-29 13:45 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-03-29 13:47 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWyEGPs-d6boq9q63qx:-MWyEGPs-d6boq9q63qy:bq4w1sw) (no related file):*
Jenkins fails with errors like this:
```
make[3]: Entering directory '/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX'
In file included from pal_linux.h:24:0,
                 from db_devices.c:18:
../../../include/lib/uthash.h:129:2: error: #error You need to define uthash_fatal(msg)
 #error You need to define uthash_fatal(msg)
  ^
  [ db_events.o ]
Makefile:118: recipe for target 'db_devices.o' failed
```

---


<!-- Sent from Reviewable.io -->

2021-03-29 13:58 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWyEGPs-d6boq9q63qx:-MWyFXNa2dRC08LrwCkY:b-9xdlmo) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Jenkins fails with errors like this:
```
make[3]: Entering directory '/home/jenkins/workspace/graphene-sgx/Pal/src/host/Linux-SGX'
In file included from pal_linux.h:24:0,
                 from db_devices.c:18:
../../../include/lib/uthash.h:129:2: error: #error You need to define uthash_fatal(msg)
 #error You need to define uthash_fatal(msg)
  ^
  [ db_events.o ]
Makefile:118: recipe for target 'db_devices.o' failed
```
</blockquote></details>

Looks like we were a bit sloppy with re/defining `uthash_fatal`. I moved the definition above include - I think it still makes sense to require an explicit definition, because the default (`exit()`) rarely makes sense for us.

---


<!-- Sent from Reviewable.io -->

2021-03-29 14:21 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-03-29 14:33 UTC, mkow requested changes
> Reviewed 2 of 2 files at r3, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy0bkX2O4osaE1cMNZ:-MWyNJ_s41RC6B-M6rEu:b-me9uad) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Why? PAL disables`_FORTIFY_SOURCE` since beginning of Git history, I think this is the reason.
</blockquote></details>

Ah, you're right.
We need to fix this...

---
___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWyNTN8AfiT5gLk3yIA:b-ad0coa) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Well, I agree it's better to have the additional security measures, so hopefully they won't be hard to add.
</blockquote></details>

@dimakuv Why? Undefining it disables even compile-time checks for memcpy-like calls correctness.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 28 at r6](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWyOUA_8WzTmOWYvf1C:-MWyOUA_8WzTmOWYvf1D:behnlt8) ([raw file](https://github.com/oscarlab/graphene/blob/c81ce744100fac6615228d9f7b76a6e7e15a2d1b/Pal/src/host/Linux-SGX/pal_linux.h#L28)):*
> ```objc
> # define uthash_fatal(msg)              \
>     do {                                \
>         __UNUSED(msg);                  \
> ```

Could you log this error message? Or maybe there are some problems with doing this?
___
*[Pal/src/host/Linux-SGX/protected-files/lru_cache.c, line 21 at r6](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWyOJfl3X9KSDobs5Ve:-MWyOJfl3X9KSDobs5Vf:b-lcmuro) ([raw file](https://github.com/oscarlab/graphene/blob/c81ce744100fac6615228d9f7b76a6e7e15a2d1b/Pal/src/host/Linux-SGX/protected-files/lru_cache.c#L21)):*
> ```C
> #include <stdlib.h>
> 
> #define uthash_fatal(msg) exit(-1)
> ```

We have stdlib available in this case, so we could print the message. Just returning -1 will be hard to debug in the future.


<!-- Sent from Reviewable.io -->

2021-03-29 14:34 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 28 at r6](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWyOUA_8WzTmOWYvf1C:-MWyOpeFCUefiZ-1iHwI:b-9xltvq) ([raw file](https://github.com/oscarlab/graphene/blob/c81ce744100fac6615228d9f7b76a6e7e15a2d1b/Pal/src/host/Linux-SGX/pal_linux.h#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you log this error message? Or maybe there are some problems with doing this?
</blockquote></details>

Actually, now I noticed that old code did the same, but AFAIR it was written before he had your new logging API :) So, would be good to fix it while we're here.


<!-- Sent from Reviewable.io -->

2021-03-29 15:38 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 3 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy0bkX2O4osaE1cMNZ:-MWy_iq915U_LqcXtxK0:ber6k5b) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, you're right.
We need to fix this...
</blockquote></details>

Good news is, I almost finished that and will submit in next PR :)

---
___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWyaVvkDz1ujMlTDQAy:bk7wqyl) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv Why? Undefining it disables even compile-time checks for memcpy-like calls correctness.
</blockquote></details>

Yeah, I did not know about the compile-time checks. And it they actually did find something: no buffer overruns, but things like "%d output can be truncated" for `snprintf`.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 28 at r6](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWyOUA_8WzTmOWYvf1C:-MWya9mbDNWiXWqUnLBU:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/c81ce744100fac6615228d9f7b76a6e7e15a2d1b/Pal/src/host/Linux-SGX/pal_linux.h#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, now I noticed that old code did the same, but AFAIR it was written before he had your new logging API :) So, would be good to fix it while we're here.
</blockquote></details>

Fixed.
___
*[Pal/src/host/Linux-SGX/protected-files/lru_cache.c, line 21 at r6](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWyOJfl3X9KSDobs5Ve:-MWyaUzp0yJZXF4QvQix:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c81ce744100fac6615228d9f7b76a6e7e15a2d1b/Pal/src/host/Linux-SGX/protected-files/lru_cache.c#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We have stdlib available in this case, so we could print the message. Just returning -1 will be hard to debug in the future.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-29 17:06 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWxp-xy8Sa5tjD2Czkv:-MWywbOk4BAPfWrsdgLv:bxppt2o) ([raw file](https://github.com/oscarlab/graphene/blob/f4a9ca540473165e0b4ba1856d10d05e2304112b/LibOS/shim/src/Makefile#L33)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, I did not know about the compile-time checks. And it they actually did find something: no buffer overruns, but things like "%d output can be truncated" for `snprintf`.
</blockquote></details>

I also didn't know about compile-time checks. Cool.


<!-- Sent from Reviewable.io -->

2021-03-29 17:41 UTC, mkow requested changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWy0bkX2O4osaE1cMNZ:-MWz3FM_4yddVSf6_ok9:bn1wz0t) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Good news is, I almost finished that and will submit in next PR :)
</blockquote></details>

:thumbsup:

---
___
*[Pal/src/pal_internal.h, line 318 at r7](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWz3h-UC3WpKo-QlBhU:-MWz3h-UC3WpKo-QlBhV:b45opy9) ([raw file](https://github.com/oscarlab/graphene/blob/ace41cf8463a0e109560066dc1480cd5488a62b3/Pal/src/pal_internal.h#L318)):*
> ```objc
> #define log_trace(fmt...)    _log(PAL_LOG_TRACE, fmt)
> 
> #define uthash_fatal(msg)                \
> ```

`\` is misaligned by one space
___
*[Pal/src/pal_internal.h, line 320 at r7](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWz3Un992dLjDjVVHur:-MWz3Un992dLjDjVVHus:bo9q5l1) ([raw file](https://github.com/oscarlab/graphene/blob/ace41cf8463a0e109560066dc1480cd5488a62b3/Pal/src/pal_internal.h#L320)):*
> ```objc
> #define uthash_fatal(msg)                \
>     do {                                  \
>         log_error("uthash error: " msg);  \
> ```

Using `%s` would be safer, `msg` can contain percent signs and weird things could happen :)


<!-- Sent from Reviewable.io -->

2021-03-29 17:47 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/pal_internal.h, line 318 at r7](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWz3h-UC3WpKo-QlBhU:-MWz51Fp3Bij3SakUGnK:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/ace41cf8463a0e109560066dc1480cd5488a62b3/Pal/src/pal_internal.h#L318)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`\` is misaligned by one space
</blockquote></details>

Fixed.
___
*[Pal/src/pal_internal.h, line 320 at r7](https://reviewable.io/reviews/oscarlab/graphene/2277#-MWz3Un992dLjDjVVHur:-MWz525x59ctk-ElYQxD:bidrs83) ([raw file](https://github.com/oscarlab/graphene/blob/ace41cf8463a0e109560066dc1480cd5488a62b3/Pal/src/pal_internal.h#L320)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Using `%s` would be safer, `msg` can contain percent signs and weird things could happen :)
</blockquote></details>

Right. Fixed.


<!-- Sent from Reviewable.io -->

2021-03-29 17:56 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-30 06:58 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug please (`select04` LTP test failed)

2021-03-30 07:02 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX please (`udp` LibOS test failed)

2021-03-30 09:22 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-03-30 10:20 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2277)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-30 11:18 UTC, merged