Enable _FORTIFY_SOURCE
oscarlab/graphene pull request #2282
Opened 2021-03-29 15:54 UTC by pwmarcz

Following the discussion #2277, I'm adding support for `_FORTIFY_SOURCE`. Apart from runtime checks, this actually added some compile-time warnings related to `snprintf` buffer size.

By the way, does anyone know why we also disable `_FORTIFY_SOURCE` within glibc itself?

2021-03-29 18:04 UTC, mkow submitted a review, later dismissed
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MWz42bV4tI0hDbPYnt4:-MWz42bV4tI0hDbPYnt5:b-g9ali9) (no related file):*
> By the way, does anyone know why we also disable `_FORTIFY_SOURCE` within glibc itself?

No idea, I guess it was just contained in the initial Graphene version. @chiache or @donporter may know, but I guess it's not needed anymore as our patches are much simpler than they were a few years ago.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MWz64ja4YIHdmFjlz2j:-MWz64ja4YIHdmFjlz2k:b-himavf) (no related file):*
> This is on top of #2277 and will be rebased later.

Moving this to a blocking comment.

---


<!-- Sent from Reviewable.io -->

2021-03-30 06:55 UTC, dimakuv requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX0u_Aa3bzyFveGtbA5:-MX0u_Aa3bzyFveGtbA6:b-51d0kj) (no related file):*
Awesome PR!

---
___
*[Pal/src/host/Linux-SGX/sgx_internal.h, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX0uDP79BRtMZ68ACFc:-MX0uDP84irI2QWyf7kx:bl3hf4i) ([raw file](https://github.com/oscarlab/graphene/blob/cd3a4380184b8de6b85ad3535b5138c0b945c0aa/Pal/src/host/Linux-SGX/sgx_internal.h#L24)):*
> ```objc
> #undef snprintf
> int printf(const char* fmt, ...) __attribute__((format(printf, 1, 2)));
> int snprintf(char* str, size_t size, const char* fmt, ...) __attribute__((format(printf, 3, 4)));
> ```

Actually, what are these function declarations? Why are they needed here? Can we just remove them?


<!-- Sent from Reviewable.io -->

2021-03-30 12:34 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: 12 of 22 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MWz42bV4tI0hDbPYnt4:-MX1JxBUD0HZLYwHb-Ea:bpc2iow) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> By the way, does anyone know why we also disable `_FORTIFY_SOURCE` within glibc itself?

No idea, I guess it was just contained in the initial Graphene version. @chiache or @donporter may know, but I guess it's not needed anymore as our patches are much simpler than they were a few years ago.
</blockquote></details>

I removed the flag, hopefully nothing will break and we can build glibc with standard options.

---
___
*[Pal/src/host/Linux-SGX/sgx_internal.h, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX0uDP79BRtMZ68ACFc:-MX1KhToCoEH0cLlKERA:b-n2n8ll) ([raw file](https://github.com/oscarlab/graphene/blob/cd3a4380184b8de6b85ad3535b5138c0b945c0aa/Pal/src/host/Linux-SGX/sgx_internal.h#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, what are these function declarations? Why are they needed here? Can we just remove them?
</blockquote></details>

I think we used to have some custom version of these functions for outer PAL. But yes, it seems I can remove these now. Done.


<!-- Sent from Reviewable.io -->

2021-03-30 12:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: 12 of 22 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MWz64ja4YIHdmFjlz2j:-MX27CYh9iM_nEVFIK7o:bncvegj) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is on top of #2277 and will be rebased later.

Moving this to a blocking comment.
</blockquote></details>

Rebased.

---


<!-- Sent from Reviewable.io -->

2021-03-30 16:01 UTC, dimakuv approved these changes
> Reviewed 10 of 11 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-03-30 16:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX2v7xd3tKCeTyJioyP:-MX2v7xd3tKCeTyJioyQ:b5pjd25) (no related file):*
Now that's interesting!

```
[P10631:fork_and_exec] restored memory from checkpoint
[P10631:fork_and_exec] restoring checkpoint at 0x73840952c000 rebased from 0x7c7ca082d000
memcpy() check failed
[P10626:T1:fork_and_exec] process creation failed
[P10626:T1:fork_and_exec] ---- return from shim_clone(...) = -61
```

---


<!-- Sent from Reviewable.io -->

2021-03-30 16:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX2v7xd3tKCeTyJioyP:-MX2wfBhDnmhVlsOdVwK:b-6mlzte) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Now that's interesting!

```
[P10631:fork_and_exec] restored memory from checkpoint
[P10631:fork_and_exec] restoring checkpoint at 0x73840952c000 rebased from 0x7c7ca082d000
memcpy() check failed
[P10626:T1:fork_and_exec] process creation failed
[P10626:T1:fork_and_exec] ---- return from shim_clone(...) = -61
```
</blockquote></details>

This is what fails:
```c
// shim_checkpoint.c

BEGIN_RS_FUNC(migratable) {
    __UNUSED(offset);
    __UNUSED(rebase);

    const char* data = (char*)base + GET_CP_FUNC_ENTRY();
    memcpy(&__migratable, data, &__migratable_end - &__migratable);
}
END_RS_FUNC(migratable)
```

TODO: debug this, and add `DEBUGOPT=1` support to Makefiles (`_FORTIFY_SOURCE` works only in optimized builds)

---


<!-- Sent from Reviewable.io -->

2021-03-30 16:40 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX2v7xd3tKCeTyJioyP:-MX3-NrC9hjkWO1jR891:bgbpfl2) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is what fails:
```c
// shim_checkpoint.c

BEGIN_RS_FUNC(migratable) {
    __UNUSED(offset);
    __UNUSED(rebase);

    const char* data = (char*)base + GET_CP_FUNC_ENTRY();
    memcpy(&__migratable, data, &__migratable_end - &__migratable);
}
END_RS_FUNC(migratable)
```

TODO: debug this, and add `DEBUGOPT=1` support to Makefiles (`_FORTIFY_SOURCE` works only in optimized builds)
</blockquote></details>

Isn't this simply because of this brainfart: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/include/shim_checkpoint.h#L22-L23

These should be `char*` or `void*` pointers, not chars.

---


<!-- Sent from Reviewable.io -->

2021-03-30 16:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX2v7xd3tKCeTyJioyP:-MX30XrR7hrVHCvuo5nC:b-3e7uig) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't this simply because of this brainfart: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/include/shim_checkpoint.h#L22-L23

These should be `char*` or `void*` pointers, not chars.
</blockquote></details>

I haven't checked yet, but I'm not sure... This looks like a symbol from linker script, and we take its address with `&`. So changing it to `char*` or `void*` would cause compiler to assume there is`sizeof(char*)` or `sizeof(void*)` max size. Maybe some cast would help?

---


<!-- Sent from Reviewable.io -->

2021-03-30 18:02 UTC, yamahata approved these changes
> Reviewed 12 of 21 files at r1, 9 of 11 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-03-30 19:58 UTC, mkow approved these changes
> Reviewed 9 of 11 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MWz42bV4tI0hDbPYnt4:-MX3hs9A1VV0flHyZ_Ip:bif50kc) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I removed the flag, hopefully nothing will break and we can build glibc with standard options.
</blockquote></details>

Good to hear that we can remove it :)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX2v7xd3tKCeTyJioyP:-MX3ggU_12_DUWUxsvln:bas3l7a) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I haven't checked yet, but I'm not sure... This looks like a symbol from linker script, and we take its address with `&`. So changing it to `char*` or `void*` would cause compiler to assume there is`sizeof(char*)` or `sizeof(void*)` max size. Maybe some cast would help?
</blockquote></details>

I think this is that magic section generated by the checkpointing hacks. `__migratable` is actually just the first byte of it and `__migratable_end` is the byte after its end. So, this blows up because on the C side there's no information about the real size of `__migratable`. I don't think we can fix this without unhacking checkpointing code.
So, possible workarounds are: (I think)
* Cast `&__migratable` to `void*`.
* Define `__migratable` as `char[]`, but I'm not sure if this is legal outside of structures.

---


<!-- Sent from Reviewable.io -->

2021-03-31 09:54 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: 22 of 24 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX2v7xd3tKCeTyJioyP:-MX6fGDR3Zm16zBRQzkh:bn60xz) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this is that magic section generated by the checkpointing hacks. `__migratable` is actually just the first byte of it and `__migratable_end` is the byte after its end. So, this blows up because on the C side there's no information about the real size of `__migratable`. I don't think we can fix this without unhacking checkpointing code.
So, possible workarounds are: (I think)
* Cast `&__migratable` to `void*`.
* Define `__migratable` as `char[]`, but I'm not sure if this is legal outside of structures.
</blockquote></details>

Casting to `void*` doesn't work, maybe it would work with some more indirection to fool the compiler.

Declaring `__migratable` as `char[]` works, probably because it's just a declaration (extern). The compiler emits a normal `memcpy` call.

And it does feel correct: we want to treat the `.migratable` section as an array of unknown size.

---


<!-- Sent from Reviewable.io -->

2021-03-31 13:33 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 11 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2282#-MX2v7xd3tKCeTyJioyP:-MX7PxCQC3zngIO6eV5f:b-myh531) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Casting to `void*` doesn't work, maybe it would work with some more indirection to fool the compiler.

Declaring `__migratable` as `char[]` works, probably because it's just a declaration (extern). The compiler emits a normal `memcpy` call.

And it does feel correct: we want to treat the `.migratable` section as an array of unknown size.
</blockquote></details>

Great! Yup, `char[]` sounds more correct, but I have some flashbacks of already implementing this because of UBSAN warnings. And because it's not in the code I thought it's because it didn't work in the end for some reason :)

---


<!-- Sent from Reviewable.io -->

2021-03-31 14:05 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-31 15:03 UTC, yamahata approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-03-31 17:40 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-01 08:36 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-01 13:20 UTC, dimakuv approved these changes
> Reviewed 1 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-04-01 14:46 UTC, mkow approved these changes
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-01 14:58 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2282)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-01 15:00 UTC, merged