[Make] Add DEBUGOPT=1 option for optimized debug builds
oscarlab/graphene pull request #2283
Opened 2021-03-31 10:24 UTC by pwmarcz

This should be useful for more reliable profiling, and is necessary for debugging _FORTIFY_SOURCE runtime failures, because they are enabled only in optimized builds.

2021-03-31 15:10 UTC, yamahata approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-03-31 15:11 UTC, mkow approved these changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-03-31 15:16 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[Documentation/building.rst, line 209 at r1](https://reviewable.io/reviews/oscarlab/graphene/2283#-MX7q0Vd-UKJI1pYvbtG:-MX7q0Vd-UKJI1pYvbtH:b-m2916s) ([raw file](https://github.com/oscarlab/graphene/blob/5bba133d6d694977233f7bf8d49fa9caccdc174c/Documentation/building.rst#L209)):*
> ```reStructuredText
> 
> - To create a debug build that does not disable optimizations, run
>   :command:`make DEBUGOPT=1`.
> ```

On a second thought, could you add some warnings here and in debugging.rst? I'm afraid that people will use it because it just sounds better than plain DEBUG and will report to us bogus backtracks and analyses, because GDB often doesn't warn when you get garbage data when printing variables in optimized builds. Example with DEBUGOPT=1:

```
Thread 1 "pal-Linux" hit Breakpoint 1, main (argc=7463, argv=0xc2, envp=0xf0b5ff) at bootstrap.c:5
5	int main(int argc, const char** argv, const char** envp) {
(gdb) p argv
$1 = (const char **) 0xc2
```

This is ofc expected, but I don't think that most people are aware of it.


<!-- Sent from Reviewable.io -->

2021-03-31 17:02 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: 3 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[Documentation/building.rst, line 209 at r1](https://reviewable.io/reviews/oscarlab/graphene/2283#-MX7q0Vd-UKJI1pYvbtG:-MX8Dm971zfehF6SivG7:b-u3gnvf) ([raw file](https://github.com/oscarlab/graphene/blob/5bba133d6d694977233f7bf8d49fa9caccdc174c/Documentation/building.rst#L209)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

On a second thought, could you add some warnings here and in debugging.rst? I'm afraid that people will use it because it just sounds better than plain DEBUG and will report to us bogus backtracks and analyses, because GDB often doesn't warn when you get garbage data when printing variables in optimized builds. Example with DEBUGOPT=1:

```
Thread 1 "pal-Linux" hit Breakpoint 1, main (argc=7463, argv=0xc2, envp=0xf0b5ff) at bootstrap.c:5
5	int main(int argc, const char** argv, const char** envp) {
(gdb) p argv
$1 = (const char **) 0xc2
```

This is ofc expected, but I don't think that most people are aware of it.
</blockquote></details>

I added a disclaimer, does it look good? (If not, feel free to suggest better wording.)


<!-- Sent from Reviewable.io -->

2021-03-31 18:07 UTC, boryspoplawski requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Documentation/building.rst, line 209 at r1](https://reviewable.io/reviews/oscarlab/graphene/2283#-MX7q0Vd-UKJI1pYvbtG:-MX8RPc01RxVj-_m-wGc:bkx4ebl) ([raw file](https://github.com/oscarlab/graphene/blob/5bba133d6d694977233f7bf8d49fa9caccdc174c/Documentation/building.rst#L209)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I added a disclaimer, does it look good? (If not, feel free to suggest better wording.)
</blockquote></details>

FWIW: @mkow the example you give is misleading, the same thing happens on a full debug build (because you stopped before function prologue).
___
*[Documentation/manifest-syntax.rst, line 546 at r2](https://reviewable.io/reviews/oscarlab/graphene/2283#-MX8SWAh0iSfWaI_sz1x:-MX8SWAh0iSfWaI_sz1y:b-m1b4k1) ([raw file](https://github.com/oscarlab/graphene/blob/8631996bbc0433ddca58deb2294afb6c2d5a4108/Documentation/manifest-syntax.rst#L546)):*
> ```reStructuredText
> This syntax specifies whether to enable SGX profiling. Graphene must be compiled
> with ``DEBUG=1`` for this option to work. Enabling optimizations
> (``DEBUGOPT=1``) is advised.
> ```

This comment sounds like you could do `DEBUG=1 DEBUGOPT=1`. I would merge this sentence with the one before: `with DEBUG=1 or DEBUGOPT=1 for this option to work (the latter is advised).` or something like that.


<!-- Sent from Reviewable.io -->

2021-03-31 18:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[Documentation/manifest-syntax.rst, line 546 at r2](https://reviewable.io/reviews/oscarlab/graphene/2283#-MX8SWAh0iSfWaI_sz1x:-MX8TLF9-8BPQao63JdK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8631996bbc0433ddca58deb2294afb6c2d5a4108/Documentation/manifest-syntax.rst#L546)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This comment sounds like you could do `DEBUG=1 DEBUGOPT=1`. I would merge this sentence with the one before: `with DEBUG=1 or DEBUGOPT=1 for this option to work (the latter is advised).` or something like that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-31 18:28 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-03-31 18:30 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX please (`udp` failed, known issue)

2021-03-31 18:43 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Documentation/building.rst, line 209 at r1](https://reviewable.io/reviews/oscarlab/graphene/2283#-MX7q0Vd-UKJI1pYvbtG:-MX8_Z741WFGPQcvY5m1:b-ti0fmu) ([raw file](https://github.com/oscarlab/graphene/blob/5bba133d6d694977233f7bf8d49fa9caccdc174c/Documentation/building.rst#L209)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

FWIW: @mkow the example you give is misleading, the same thing happens on a full debug build (because you stopped before function prologue).
</blockquote></details>

@boryspoplawski: ah, right, I forgot how stupid is GDB :(
@pwmarcz: I like the wording you used, so I'm resolving this discussion.


<!-- Sent from Reviewable.io -->

2021-04-01 08:44 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-01 15:36 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-04-01 15:46 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-01 16:05 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2283)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-01 16:12 UTC, merged