[LibOS] Refactor `udp` LibOS regression test
oscarlab/graphene pull request #2287
Opened 2021-03-31 17:19 UTC by dimakuv

## Description of the changes 

The `udp` LibOS test didn't have proper error checking and retrying on EINTR/EAGAIN. This led to periodic failures in Jenkins because LibOS layer doesn't yet have ERESTARTSYS handling on `recv()` family of syscalls, and sometimes Graphene sends host-level SIGCONT signals to its processes which leads to injecting an EINTR (and not restarting the syscall automatically because there is no ERESTARTSYS).

Technically there is no real issue with current-master `udp`'s recv code because there shouldn't be any EINTRs in this program (there are no signal handlers installed in the app). But Graphene's signal handling and ERESTARTSYS is not yet fully operational, thus this problem.

## How to test this PR? 

`udp` shouldn't fail now.

2021-03-31 18:23 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/udp.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8Ukjn6tcUe8sCyUJa:-MX8Ukjn6tcUe8sCyUJb:bx5vj8n) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L49)):*
> ```C
>         char byte = 0;
>         ssize_t written = 0;
>         while (written == 0) {
> ```

Hmm, won't `written` be `-1` on `EINTR`? Also `0` is probably an error too (otoh it probably cannot happen in practice).
___
*[LibOS/shim/test/regression/udp.c, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8VZaS2UM2ZJ_WxcvT:-MX8VZaS2UM2ZJ_WxcvU:bvwng6v) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L59)):*
> ```C
> 
>     for (int i = 0; i < NPACK; i++) {
>         ssize_t read = 0;
> ```

This should be `size_t`.
___
*[LibOS/shim/test/regression/udp.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8VkMWE5QmEeyoNE-b:-MX8VkMWE5QmEeyoNE-c:b8m3owe) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L60)):*
> ```C
>     for (int i = 0; i < NPACK; i++) {
>         ssize_t read = 0;
>         while (true) {
> ```

`while (read < BUFLEN)` and remove `if () break` below (or at least first part of it)?
___
*[LibOS/shim/test/regression/udp.c, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8WVRpEeZJNlkJwqqF:-MX8WVRq2_FvINJPQ9J3:bq1a7jo) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L69)):*
> ```C
>             }
>             read += n;
>             if (read == BUFLEN || !n)
> ```

Isn't `n==0` (socket closed prematurely) considered error in this test?
___
*[LibOS/shim/test/regression/udp.c, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8W8dP953Y6T0C7rdC:-MX8Vzkq8jAelH9IsuM8:b9xyllc) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L78)):*
> ```C
> 
>     ret = close(s);
>     if (ret < 0)
> ```

Nitpick: this can be oneliner.
___
*[LibOS/shim/test/regression/udp.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8WC9D93Cj3ouzdUVY:-MX8WC9D93Cj3ouzdUVZ:butvnxm) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L94)):*
> ```C
>         char byte = 0;
>         ssize_t received = 0;
>         while (received == 0) {
> ```

ditto (`received == -1` on EINTR)
___
*[LibOS/shim/test/regression/udp.c, line 147 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8UDb-5oy0Ck1bFkeC:-MX8UDb0EhU8C7ZKjAs1:b-9js6o9) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L147)):*
> ```C
>         } else {
>             puts("Invalid option!");
>             return EXIT_FAILURE;
> ```

Nitpick: `errx` (not blocking)


<!-- Sent from Reviewable.io -->

2021-04-01 08:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: 1 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/regression/tcp_msg_peek.c, line 62 at r2](https://reviewable.io/reviews/oscarlab/graphene/2287#-MXBTCr9DJ5ZuBBGPkLc:-MXBTCrA1CjNj4-PuvtO:b-gqd9by) ([raw file](https://github.com/oscarlab/graphene/blob/38e16f164f881999afeb19315dd9aab98c5097f6/LibOS/shim/test/regression/tcp_msg_peek.c#L62)):*
> ```C
> 
>         ssize_t written = 0;
>         while (written <= 0) {
> ```

FYI: Same issue as Borys pointed out was in this test, so I fixed it as well
___
*[LibOS/shim/test/regression/udp.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8Ukjn6tcUe8sCyUJa:-MXBOb_F7IHeWIlZkNtw:b-xb70tm) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, won't `written` be `-1` on `EINTR`? Also `0` is probably an error too (otoh it probably cannot happen in practice).
</blockquote></details>

Done. Oops. As for `0`, this must never happen.
___
*[LibOS/shim/test/regression/udp.c, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8VZaS2UM2ZJ_WxcvT:-MXBP-wnDt--8k_SngEO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L59)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This should be `size_t`.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/udp.c, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8VkMWE5QmEeyoNE-b:-MXBPmA_DjzCIIw_cOSF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L60)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`while (read < BUFLEN)` and remove `if () break` below (or at least first part of it)?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/udp.c, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8WVRpEeZJNlkJwqqF:-MXBPmoH7Qa3KAd_4Wor:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't `n==0` (socket closed prematurely) considered error in this test?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/udp.c, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8W8dP953Y6T0C7rdC:-MXBPqZzBc7kzZfDOJnB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L78)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: this can be oneliner.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/udp.c, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8WC9D93Cj3ouzdUVY:-MXBQ4WC7wRUMdW_N8V-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L94)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (`received == -1` on EINTR)
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/udp.c, line 147 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8UDb-5oy0Ck1bFkeC:-MXBQMuI73qSVPkf5Ogl:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L147)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Nitpick: `errx` (not blocking)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-04-01 16:31 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/udp.c, line 91 at r2](https://reviewable.io/reviews/oscarlab/graphene/2287#-MXDGIY7ESPQ9W-IJqPS:-MXDGIY845NP18CCdMsy:b-y57o4y) ([raw file](https://github.com/oscarlab/graphene/blob/38e16f164f881999afeb19315dd9aab98c5097f6/LibOS/shim/test/regression/udp.c#L91)):*
> ```C
>         char byte = 0;
>         ssize_t received = 0;
>         while (received <= 0) {
> ```

This will loop infinitely when `received == 0` (closed pipe)


<!-- Sent from Reviewable.io -->

2021-04-06 13:57 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-06 14:19 UTC, mkow requested changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/udp.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8Ukjn6tcUe8sCyUJa:-MXbXLyhAuVgjD0gGW4j:b-msgnmv) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Oops. As for `0`, this must never happen.
</blockquote></details>

Could you also error on 0? I know it's not technically possible according to write() specification, but sounds like a bug which may someday happen in Graphene. And currently you silently continue execution on 0.
___
*[LibOS/shim/test/regression/udp.c, line 120 at r3](https://reviewable.io/reviews/oscarlab/graphene/2287#-MXbY2NY5wpTFoYXl0Kc:-MXbY2NY5wpTFoYXl0Kd:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/c85b64dea49b95bd44b72d765fd78f394708e991/LibOS/shim/test/regression/udp.c#L120)):*
> ```C
>         while (written < BUFLEN) {
>             ssize_t n = sendto(s, buf + written, BUFLEN - written, /*flags=*/0,
>                                (struct sockaddr*)&si_other, slen);
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-04-06 15:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/test/regression/udp.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2287#-MX8Ukjn6tcUe8sCyUJa:-MXbi6da8VWeGBYRM_i_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/427cfe592d72706f77566c46d4a217071117c6dd/LibOS/shim/test/regression/udp.c#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you also error on 0? I know it's not technically possible according to write() specification, but sounds like a bug which may someday happen in Graphene. And currently you silently continue execution on 0.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/udp.c, line 120 at r3](https://reviewable.io/reviews/oscarlab/graphene/2287#-MXbY2NY5wpTFoYXl0Kc:-MXbmdZa2rc4Za4ZQDZb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c85b64dea49b95bd44b72d765fd78f394708e991/LibOS/shim/test/regression/udp.c#L120)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-06 15:28 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-04-06 15:29 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-04-06 15:37 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-06 17:44 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-06 17:47 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04 please (LTP test `kill_all` failed with `SIGPWR`)

2021-04-06 18:10 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2287)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-06 18:35 UTC, merged