[LibOS,PAL] Deprecate internal printf in favor of `log_*`
oscarlab/graphene pull request #2292
Opened 2021-04-04 16:47 UTC by mkow

## Description of the changes 

After this PR the only changes left to the logging will be getting rid of `pal_printf` and `printf` from PAL regression and PAL lib (which is nontrivial, due to linking hacks). Or at least that's what I think is left.

## How to test this PR? 

Run code on different logging levels.

2021-04-04 19:13 UTC, mkow commented
Jenkins, retest Jenkins-SGX please (`test_pal.TC_23_SendHandle.test_000_send_handle` failed, but I cannot reproduce, and seems unrelated)

2021-04-05 17:22 UTC, boryspoplawski requested changes
> Reviewed 41 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXuUDND_VadWNqen2Z:-MXXuUDND_VadWNqen2_:b-a8eccu) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/include/shim_internal.h#L46)):*
> ```objc
> void _log(int level, const char* fmt, ...) __attribute__((format(printf, 2, 3)));
> /* This function emits logs regardless of log_level setting and doesn't prefix the output. It's
>  * intended for outputs explicitly requested by the user. */
> ```

I do not understand the 2nd sentence: who is the user? Graphene user, Graphene dev, app running in Graphene dev?
Please clarify/reword.
___
*[LibOS/shim/src/utils/log.c, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXygPr-ASnVKR_yDot:-MXXygPr-ASnVKR_yDou:b8as4ae) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/src/utils/log.c#L54)):*
> ```C
>     const char* exec = PAL_CB(executable);
>     for (const char* it = exec; *it; it++)
>         if (*it == ':' || *it == '/')
> ```

Why `:`?
___
*[LibOS/shim/src/utils/log.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXzUvTDsYJFAZZF6C_:-MXXzUvTDsYJFAZZF6Ca:b-2svfeu) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/src/utils/log.c#L82)):*
> ```C
> }
> 
> void _log(int level, const char* fmt, ...) {
> ```

Why isn't `level` unsigned?
___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXY-dpU-cYiJBcAEicH:b-u8j450) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
> ```C
>         /* Warn only in the first process. */
>         if (!parent_process) {
>             log_error("Using insecure argv source. Don't use this configuration in production!\n");
> ```

This sounds like a warning, not error, and the old version printed warning (current will print `error: `).
___
*[Pal/src/db_main.c, line 375 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-gzQCQCxKnzIkI94:-MXY-gzQCQCxKnzIkI95:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L375)):*
> ```C
>         /* Warn only in the first process. */
>         if (!parent_process) {
>             log_error("Forwarding host environment variables to the app is enabled. Don't use this "
> ```

ditto
___
*[Pal/src/pal_internal.h, line 310 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY1U5n2MTFn-IbPOIb:-MXY1U5n2MTFn-IbPOIc:b-azc2j5) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/pal_internal.h#L310)):*
> ```objc
> void _log(int level, const char* fmt, ...) __attribute__((format(printf, 2, 3)));
> /* This function emits logs regardless of log_level setting and doesn't prefix the output. It's
>  * intended for outputs explicitly requested by the user. */
> ```

ditto (elaborate)
___
*[Pal/src/printf.c, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY0FxlAyOx3QtSjvY5:-MXY0FxlAyOx3QtSjvY6:bv521p3) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/printf.c#L79)):*
> ```C
> EXTERN_ALIAS(printf);
> 
> void _log(int level, const char* fmt, ...) {
> ```

Why this function is not shared by LibOS and Pals? (applies to half of this file)
___
*[Pal/src/host/Linux-SGX/sgx_log.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY1NJP9IFtBgg_4Zpp:-MXY1NJP9IFtBgg_4Zpq:b-azc2j5) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.h#L27)):*
> ```objc
> void _urts_log(int level, const char* fmt, ...) __attribute__((format(printf, 2, 3)));
> /* This function emits logs regardless of log_level setting and doesn't prefix the output. It's
>  * intended for outputs explicitly requested by the user. */
> ```

ditto (elaborate)
___
*[Pal/src/host/Linux-SGX/sgx_log.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2-wA1R52tS6BTlTk:-MXY2-wB4aHya4SpLyNN:b7db97o) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.c#L58)):*
> ```C
> 
>     buf->buf[buf->end++] = ch;
>     if (buf->end == LOG_BUF_SIZE) {
> ```

Why no flushing on newline like in other places?
___
*[Pal/src/host/Linux-SGX/sgx_log.c, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2BKy5mBFd0nDuZIv:-MXY2BKy5mBFd0nDuZIw:bvdj5kz) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.c#L90)):*
> ```C
>         va_start(ap, fmt);
>         assert(0 <= level && (size_t)level < ARRAY_SIZE(log_level_to_prefix));
>         urts_log_always("%s", log_level_to_prefix[level]);
> ```

Shouldn't you check if internal buffer is empty before prepending prefix?
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1076 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2SOZBhuVtqRQHCJA:-MXY2SOZBhuVtqRQHCJB:b-85khxz) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_main.c#L1076)):*
> ```C
>         /* This shows the time for Graphene + the Intel SGX driver to initialize the untrusted
>          * PAL, config and create the SGX enclave, add enclave pages, measure and init it.
>          * The user explicitly asked to print this, so we disregard the log level.
> ```

Imo this is obvious and does not need a comment (not blocking).
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2cK4CHqyV33T1Wik:-MXY2cK4CHqyV33T1Wil:b-rqxvol) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_thread.c#L48)):*
> ```C
>     int tid = INLINE_SYSCALL(gettid, 0);
>     assert(tid > 0);
>     /* The user explicitly asked to print this, so we disregard the log level. */
> ```

ditto 
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2dDr95lEhEaSQUDX:-MXY2dDr95lEhEaSQUDY:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_thread.c#L67)):*
> ```C
>         int pid = INLINE_SYSCALL(getpid, 0);
>         assert(pid > 0);
>         /* The user explicitly asked to print this, so we disregard the log level. */
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-04-05 22:12 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: 35 of 41 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXuUDND_VadWNqen2Z:-MXY4zdGAVJz1QPQGB1K:b-t0j2ih) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/include/shim_internal.h#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I do not understand the 2nd sentence: who is the user? Graphene user, Graphene dev, app running in Graphene dev?
Please clarify/reword.
</blockquote></details>

Done. Not sure thought whether I should keep "the", any clue?
___
*[LibOS/shim/src/utils/log.c, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXygPr-ASnVKR_yDot:-MXY7e3LAfvVfkYwzbTi:b-rn83wk) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/src/utils/log.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `:`?
</blockquote></details>

It's not part of this PR (I only moved the code), but the reason was AFAIR to strip the URI type prefix.
___
*[LibOS/shim/src/utils/log.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXzUvTDsYJFAZZF6C_:-MXZ12pl6Xr833J1czRM:bnvw4it) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/src/utils/log.c#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why isn't `level` unsigned?
</blockquote></details>

Dunno, it was like this before. I'd say "whatever", it's actually an enum anyways, but in C there's no way to enforce this (like with `enum class` in C++).
___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXZ1NkbE7afrrMr3fj_:bad895n) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This sounds like a warning, not error, and the old version printed warning (current will print `error: `).
</blockquote></details>

It printed error, but with "warning" prefix. The problem is that in production builds warnings are not printed, and we want this to be always printed.
___
*[Pal/src/pal_internal.h, line 310 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY1U5n2MTFn-IbPOIb:-MXZ3vJO7q300pbv_Pe3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/pal_internal.h#L310)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (elaborate)
</blockquote></details>

Done.
___
*[Pal/src/printf.c, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY0FxlAyOx3QtSjvY5:-MXZ1q1U0Xg5eWEJ35LG:b-nifq7k) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/printf.c#L79)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this function is not shared by LibOS and Pals? (applies to half of this file)
</blockquote></details>

Because currently there's no way to do this nicely, I think. They all slightly differ, plus pal/lib is shared only with LibOS, so we'd still need a copy in urts. Anyways, it was like this before.
___
*[Pal/src/host/Linux-SGX/sgx_log.h, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY1NJP9IFtBgg_4Zpp:-MXZ2BU1B1GadHKMSiu8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.h#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (elaborate)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_log.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2-wA1R52tS6BTlTk:-MXZ2xJt7oXPinex9SM8:b-5tua6y) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why no flushing on newline like in other places?
</blockquote></details>

Because it's used differently than in other places. Here we don't have a thread-local `log_buf`, but per-invocation, which is manually flushed at the end.
The other implementations flush here because the buffer is global and is not flushed after each log().
___
*[Pal/src/host/Linux-SGX/sgx_log.c, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2BKy5mBFd0nDuZIv:-MXZ3WM6EkOGN2acIRR_:bbm5y12) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.c#L90)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't you check if internal buffer is empty before prepending prefix?
</blockquote></details>

It's always empty, notice that here the buffer is local to each invocation (contrary to other logging places).
___
*[Pal/src/host/Linux-SGX/sgx_main.c, line 1076 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2SOZBhuVtqRQHCJA:-MXZ4wywDVeD9vIJpTlU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_main.c#L1076)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Imo this is obvious and does not need a comment (not blocking).
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2cK4CHqyV33T1Wik:-MXZ1k4lE9yK1ngvzMhD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_thread.c#L48)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto 
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_thread.c, line 67 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2dDr95lEhEaSQUDX:-MXZ3rU40nPH_mCzr01I:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_thread.c#L67)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-05 23:26 UTC, boryspoplawski requested changes
> Reviewed 1 of 41 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXuUDND_VadWNqen2Z:-MXZH7Ta4qQ1cSymsLJ4:b-w2iob4) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/include/shim_internal.h#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Done. Not sure thought whether I should keep "the", any clue?
</blockquote></details>

I think you should keep "the", but not sure too.
It's still not clear what this sentence is about (i.e. I only understand it because I've read other changes in this PR). How can user request to log something inside Graphene?
___
*[LibOS/shim/src/utils/log.c, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXygPr-ASnVKR_yDot:-MXZGkxD6x3FDQkGgnvK:b-1yi4kd) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/src/utils/log.c#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's not part of this PR (I only moved the code), but the reason was AFAIR to strip the URI type prefix.
</blockquote></details>

Ah, you renamed the file + made changes, so the reviewable did not pick up rename and just showed delete+new file.
___
*[LibOS/shim/src/utils/log.c, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXzUvTDsYJFAZZF6C_:-MXZH4Po13NIs4gAj7Up:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/src/utils/log.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Dunno, it was like this before. I'd say "whatever", it's actually an enum anyways, but in C there's no way to enforce this (like with `enum class` in C++).
</blockquote></details>

ditto
___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXZITEd52heOqeag5ve:b67qw7b) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It printed error, but with "warning" prefix. The problem is that in production builds warnings are not printed, and we want this to be always printed.
</blockquote></details>

Aren't errors not printed with none (default) log level? Doesn't this PR introduce function `log_always` for such usecases?
___
*[Pal/src/printf.c, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY0FxlAyOx3QtSjvY5:-MXZJAfOCAvfIxFbcOuY:b-wi9otc) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/printf.c#L79)):*
> They all slightly differ

I don't think they should...
> plus pal/lib is shared only with LibOS, so we'd still need a copy in urts.

Hmm, cant we just link pal/lib in urts as well?
> Anyways, it was like this before.

But you state that logging subsystem is finished except some todos and this is **not** one of them, whereas I would say it needs more unification, like commoning some of these functions.
___
*[Pal/src/host/Linux-SGX/sgx_log.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2-wA1R52tS6BTlTk:-MXZKp4B224uLPo9x47H:bygj9ci) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Because it's used differently than in other places. Here we don't have a thread-local `log_buf`, but per-invocation, which is manually flushed at the end.
The other implementations flush here because the buffer is global and is not flushed after each log().
</blockquote></details>

Where do these differences steam from? Why each layer uses slightly different logging (ofc except for the actual writing function)?


<!-- Sent from Reviewable.io -->

2021-04-06 01:46 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXuUDND_VadWNqen2Z:-MXZo6VQ4tCQCsdJba90:bk0kdpx) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/include/shim_internal.h#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think you should keep "the", but not sure too.
It's still not clear what this sentence is about (i.e. I only understand it because I've read other changes in this PR). How can user request to log something inside Graphene?
</blockquote></details>

Another try.
___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXZoMVhAV8s1U0MzY2b:b-vsz51r) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
> Aren't errors not printed with none (default) log level?

Too many negations for me, could you reword this question? ;)

> Doesn't this PR introduce function `log_always` for such usecases?

Not exactly. `log_always` is circumventing the whole log level thing and should only be used for things the user requested explicitly. For security warnings I'd expect them to not appear when log_level is set to "none" - there should be no logs in this mode, except those cases which were manually overridden by the user.
___
*[Pal/src/printf.c, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY0FxlAyOx3QtSjvY5:-MXZq7p9Alw7D9RIXuu2:bvfc6hc) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/printf.c#L79)):*
> Hmm, cant we just link pal/lib in urts as well?

I don't think so, I expect that something for sure will blow up.

> But you state that logging subsystem is finished except some todos and this is not one of them, whereas I would say it needs more unification, like commoning some of these functions.

Updated the PR description then.
___
*[Pal/src/host/Linux-SGX/sgx_log.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2-wA1R52tS6BTlTk:-MXZqOKj-sF0gLCuZkxW:b-4aoag7) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.c#L58)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Where do these differences steam from? Why each layer uses slightly different logging (ofc except for the actual writing function)?
</blockquote></details>

I don't know, it was like this before and I didn't really touch this part (the buffers itself). I guess this will be fixed after deduplication of the code.


<!-- Sent from Reviewable.io -->

2021-04-06 13:01 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXuUDND_VadWNqen2Z:-MXbBrgsE_-WBUzCaHn8:bfcyokk) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/include/shim_internal.h#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Another try.
</blockquote></details>

Just remove this sentence (as discussed off-reviewable).
___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXbDho-CrpMBq0C2RxY:b-riq3fs) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
> Too many negations for me, could you reword this question? ;)

If `log_level = none` (default), then `log_error` doesnt't print anything, does it?
You said that `The problem is that in production builds warnings are not printed, and we want this to be always printed.`and I just pointed that `log_error` is not printed always as well. Also afaik production builds have nothing to do with logging currently (i.e. you can still have full logging there).

> Not exactly. log_always is circumventing the whole log level thing and should only be used for things the user requested explicitly. For security warnings I'd expect them to not appear when log_level is set to "none" - there should be no logs in this mode, except those cases which were manually overridden by the user.

Ok, you previously wrote that `we want this to be always printed`, but actually you want to print a warning message on error level.
I would say security warning should be printed always - to nudge user to fix the issue. This message even explicitly says `Don't use this configuration in production!` so we should not hide it.
___
*[Pal/src/printf.c, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY0FxlAyOx3QtSjvY5:-MXbGIzz4jVuEhmUsS5B:b-46jbu0) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/printf.c#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Hmm, cant we just link pal/lib in urts as well?

I don't think so, I expect that something for sure will blow up.

> But you state that logging subsystem is finished except some todos and this is not one of them, whereas I would say it needs more unification, like commoning some of these functions.

Updated the PR description then.
</blockquote></details>

Ok, so we leave that for the future.
___
*[Pal/src/host/Linux-SGX/sgx_log.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY2-wA1R52tS6BTlTk:-MXbGS4F4_7Qh774d-kn:b-nqvskg) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/host/Linux-SGX/sgx_log.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't know, it was like this before and I didn't really touch this part (the buffers itself). I guess this will be fixed after deduplication of the code.
</blockquote></details>

If we ever do that...


<!-- Sent from Reviewable.io -->

2021-04-06 13:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: 38 of 41 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_internal.h, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXXuUDND_VadWNqen2Z:-MXbHAiw2amBrv9FdTLQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/LibOS/shim/include/shim_internal.h#L46)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Just remove this sentence (as discussed off-reviewable).
</blockquote></details>

Done.
___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXbHVkA5gCAvxZjnEwQ:bzcym36) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
> `log_level = none` (default)

The default is "error", and this is also what's intended for release builds.

> Also afaik production builds have nothing to do with logging currently (i.e. you can still have full logging there).

Depends, I think our example makefiles use debug/error depending on the build mode. And yes, you can have full logging in release builds, but that may be insecure if printed to stderr.

> but actually you want to print a warning message on error level.

Yes, but I also don't want to add a special API just for this place. Using `log_error` is just more conservative trade-off choice.

>  I would say security warning should be printed always - to nudge user to fix the issue. This message even explicitly says Don't use this configuration in production! so we should not hide it.

I think we should respect the "none" level - it doesn't even print other runtime errors, which can be much more important that this one. And I don't really expect anyone to use the "none" debug level too often (and as I said above, it's _not_ the default, you need to manually change it to remove the logs).


<!-- Sent from Reviewable.io -->

2021-04-06 13:36 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXbLzRo-YeiXZQm9zpR:b9o1oel) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
> The default is "error", and this is also what's intended for release builds.

LibOS does initializes it to none, but seems we always overwrite it with info from Pal, which has default "error". That's why I got confused.
>  And yes, you can have full logging in release builds, but that may be insecure if printed to stderr.

Sure, I just pointed out it's unrelated.
> Yes, but I also don't want to add a special API just for this place. Using log_error is just more conservative trade-off choice.

Agree that introducing special function just for this is too much, but now we print an 'error: ' message and run happily. I would expect errors to change the way the program works (either exit due to fatal error or disable some functionality use a workaround/different path or approach to circumvent the error) - here there is completely no change. But the main issue is discussed below.
> I think we should respect the "none" level - it doesn't even print other runtime errors, which can be much more important that this one. And I don't really expect anyone to use the "none" debug level too often (and as I said above, it's not the default, you need to manually change it to remove the logs).

Yeah, but this is not a runtime error, this is a deliberate configuration choice (user had to set `insecure_argv_something` in manifest explicitly). So imo we should either print it always or push down to lower logging levels (or even remove, the `insecure` prefix might be enough).


<!-- Sent from Reviewable.io -->

2021-04-06 14:42 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXbcGOB8JRsydd9uU7I:b-hkk10g) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> The default is "error", and this is also what's intended for release builds.

LibOS does initializes it to none, but seems we always overwrite it with info from Pal, which has default "error". That's why I got confused.
>  And yes, you can have full logging in release builds, but that may be insecure if printed to stderr.

Sure, I just pointed out it's unrelated.
> Yes, but I also don't want to add a special API just for this place. Using log_error is just more conservative trade-off choice.

Agree that introducing special function just for this is too much, but now we print an 'error: ' message and run happily. I would expect errors to change the way the program works (either exit due to fatal error or disable some functionality use a workaround/different path or approach to circumvent the error) - here there is completely no change. But the main issue is discussed below.
> I think we should respect the "none" level - it doesn't even print other runtime errors, which can be much more important that this one. And I don't really expect anyone to use the "none" debug level too often (and as I said above, it's not the default, you need to manually change it to remove the logs).

Yeah, but this is not a runtime error, this is a deliberate configuration choice (user had to set `insecure_argv_something` in manifest explicitly). So imo we should either print it always or push down to lower logging levels (or even remove, the `insecure` prefix might be enough).
</blockquote></details>

@dimakuv, @pwmarcz: What do you think? I dislike both mine and Borys' solution :)


<!-- Sent from Reviewable.io -->

2021-04-06 18:50 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/src/db_main.c, line 375 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-gzQCQCxKnzIkI94:-MXcWPUf9KrIkosu04aJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L375)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2021-04-06 19:12 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXcaB3lDZy5rhZs2WpH:b-21vcgr) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I prefer the current `log_error` over `log_warning` or `log_always`. Maybe we should add something like:
```
log_error("Using insecure argv source. Graphene will continue application execution, "
          "but this configuration must not be used in production!\n");
```
</blockquote></details>

The message proposed by @dimakuv looks better than the current one and will work nicely with `error: ` prefix, so big +1 from my side.


<!-- Sent from Reviewable.io -->

2021-04-06 20:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: 40 of 41 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Pal/src/db_main.c, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-dpU-cYiJBcAEicG:-MXcg9xyEJdCmdY8fNBu:b-sxysvn) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L337)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The message proposed by @dimakuv looks better than the current one and will work nicely with `error: ` prefix, so big +1 from my side.
</blockquote></details>

@dimakuv: Good wording! I like it, done.
___
*[Pal/src/db_main.c, line 375 at r1](https://reviewable.io/reviews/oscarlab/graphene/2292#-MXY-gzQCQCxKnzIkI94:-MXcmEmv3dahfGRbnpla:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d38e1be8ea5d1cf1bf7ad065ed3b4aa8b23a8e22/Pal/src/db_main.c#L375)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-06 20:12 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-04-06 20:15 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-06 20:18 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-06 20:20 UTC, dimakuv approved these changes
> Reviewed 1 of 41 files at r1, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2292)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-06 20:37 UTC, mkow commented
Jenkins, retest Jenkins-Debug-18.04 please (`apps.LTP.kill11` timed out, known issue)

2021-04-06 21:12 UTC, merged