Test what's installed
oscarlab/graphene pull request #2298
Opened 2021-04-07 13:59 UTC by woju

## Description of the changes 

This is a preparation to meson rewrite (#760). Meson builds out of tree and it's necessary to run things installed, so to maintain test coverage, we need to have a working install before touching makefiles.

This is based on #2288.

## How to test this PR? 

All tests should pass.

2021-04-09 18:44 UTC, woju commented
Jenkins, test Jenkins-SGX-18.04, please (udp)

2021-04-09 18:45 UTC, woju commented
Jenkins, test Jenkins-18.04 please (udp)

2021-04-09 18:45 UTC, woju commented
Jenkins, test Jenkins-SGX-18.04 please (udp)

2021-04-14 12:58 UTC, woju commented
Jenkins, test Jenkins-SGX please

2021-04-14 14:44 UTC, woju commented
Jenkins, test Jenkins-SGX-18.04 please

2021-04-15 09:28 UTC, dimakuv requested changes
> Reviewed 83 of 83 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJqkh40mgcGHgz3jVm:-MYJqkh40mgcGHgz3jVn:b-q55he) (no related file):*
I have a feeling GSC will break completely due to this change. Could you do a quick test of GSC with your PR? You can follow this quick start: https://graphene.readthedocs.io/en/latest/manpages/gsc.html#example

---
___
*[Makefile, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJjzJl7KZvpMlszIpq:-MYJjzJl7KZvpMlszIpr:b2s4fhm) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L19)):*
> ```Makefile
> 	$(MAKE) -C Tools $@
> 	@echo
> 	@echo NOTE: We arere in the middle of transision to meson build system.
> ```

Multiple typos. Corrected: `NOTE: We are in the middle of a transition to the meson build system.`
___
*[README.rst, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJkEoVDSqrri1tu_5h:-MYJkEoVDSqrri1tu_5i:b-v224kx) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/README.rst#L18)):*
> ```reStructuredText
> .. highlight:: sh
> 
> **NOTE:** we are in the middle of transitioning buildsystem to meson, and the
> ```

`our build system`?
___
*[.ci/lib/stage-test.jenkinsfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJlbTW9P7SG5mgDInV:-MYJlbTW9P7SG5mgDInW:bydil7c) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/stage-test.jenkinsfile#L59)):*
> ```
>                 fi
>                 make test
> #               python3 -m pytest -v --junit-xml fs.xml test_fs.py test_tmpfs.py test_pf.py
> ```

Why can't we use it? Because we don't know which tests to perform?
- `test_fs.py` and `test_tmpfs.py` should be done for non-SGX
- all three should be done for SGX
___
*[Documentation/building.rst, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJm6Rt26yfTd-3xR6i:-MYJm6Rt26yfTd-3xR6j:b-bsxjl8) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L64)):*
> ```reStructuredText
> 
>     # For Ubuntu 18.04
>     sudo apt-get install -y meson python3-protobuf
> ```

What about `jq`? What about `ninja`?
___
*[Documentation/building.rst, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJmOjp52-LSCKHLDIb:-MYJmOjp52-LSCKHLDIc:b-ps2yib) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L135)):*
> ```reStructuredText
> 
> Alternatively, if you want to use the DCAP versions of the SDK and driver,
> download and install it from:
> ```

`it` -> `them`
___
*[Documentation/building.rst, line 137 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJmSJS7BwvQ634gTLP:-MYJmSJS7BwvQ634gTLQ:b-5w26x5) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L137)):*
> ```reStructuredText
> download and install it from:
> 
> - https://github.com/intel/SGXDataCenterAttestationPrimitives
> ```

Can you also add yet another alternative: if you already have Linux 5.11+, then the SGX driver is already enabled and there is no need to install a separate one.
___
*[Documentation/building.rst, line 167 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJmlhH-eQv7zQv5za3:-MYJmlhH-eQv7zQv5za4:bc847wj) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L167)):*
> ```reStructuredText
> commands::
> 
>    # if you build graphene-direct
> ```

`graphene-direct` is our internal name. People typically say `Graphene without SGX` or simply `Graphene`
___
*[Documentation/building.rst, line 170 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJmqMB3JsXMlSxLH28:-MYJmqMB3JsXMlSxLH29:blnwd1g) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L170)):*
> ```reStructuredText
>    make
> 
>    # if you build graphene-sgx
> ```

I suggest to capitalize and slightly modify: `Graphene with SGX`
___
*[Documentation/building.rst, line 183 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJn73c5wZfmC7M5ZPf:-MYJn73c5wZfmC7M5ZPg:b-mkobuv) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L183)):*
> ```reStructuredText
> and EINITTOKENs (``.token`` files).
> 
> Then install graphene::
> ```

`Then install graphene (note that 'direct' means non-SGX version)::`

Actually, why do we have such an interface? Wouldn't it make sense to always build `direct` version? This can only confuse the users...
___
*[Documentation/building.rst, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJnSHm1gVg8JvHlzkH:-MYJnSHm1gVg8JvHlzkI:b-d5kh4l) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L190)):*
> ```reStructuredText
> 
> Set ``-Ddirect=`` and ``-Dsgx=`` options to ``enabled`` or ``disabled``
> according to whether you build corresponding PAL (the snippet assumes you built
> ```

`build` -> `built the `
___
*[Documentation/manifest-syntax.rst, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJnj-3BGV9-bAuIgAI:-MYJnj-3BGV9-bAuIgAJ:b4dlh0c) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/manifest-syntax.rst#L90)):*
> ```reStructuredText
> 
> If the string is not specified in the manifest, the application will get
> ``argv[0]`` from :program:`graphene-direct` or :program:`graphens-sgx`
> ```

Do we need to specify `graphene-direct`? Can we shorten it to just `graphene`? This is what the users got used to.
___
*[Documentation/manifest-syntax.rst, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJns3Y61oaolBwbU5b:-MYJns3Y61oaolBwbU5c:b-x3y6ek) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/manifest-syntax.rst#L90)):*
> ```reStructuredText
> 
> If the string is not specified in the manifest, the application will get
> ``argv[0]`` from :program:`graphene-direct` or :program:`graphens-sgx`
> ```

Typo: `graphens` -> `graphene`
___
*[Examples/apache/Makefile, line 96 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJoVLE66iN52jsJIgw:-MYJoVLE66iN52jsJIgx:b-dbz9dx) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Examples/apache/Makefile#L96)):*
> ```Makefile
> 		$(TEST_DATA) \
> 		$(INSTALL_DIR)/conf/server.crt
> 	graphene-sgx-sign \
> ```

This is really cool! I like how it looks now.
___
*[Examples/gcc/Makefile, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJoltAEzBEMflrLda4:-MYJoltAEzBEMflrLda5:b-48x3sg) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Examples/gcc/Makefile#L62)):*
> ```Makefile
> # the file hosted by the authors doesn't compile...
> test_files/gzip_broken.c:
> 	$(GRAPHENEDIR)/Scripts/download --output $@ --sha256 $(GZIP_HASH) $(foreach mirror,$(GZIP_MIRRORS),--url $(mirror))
> ```

By the way, what about this helper script? Isn't it also installed and can be used like `download` or something?
___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MYJpYMx8t8qOPQx1pwW:bi4ibwx) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
> ```Me [...]

2021-04-15 12:21 UTC, mkow requested changes
> Reviewed 83 of 83 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 37 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGW8KpBtk0zulBu0JQ:-MYGW8KqEb1foPGtPzM-:bp83k1r) (no related file):*
Some fix-ups for the commit messages:

- "Loader executable (PAL_CMD) is named "loader"" <- one-liners should be in imperative mood and specify what this particular commit does. With this one I'm not really sure if what you wrote is the change or the bug you're fixing in this commit.
- "[ci]" -> "[CI]"
- "[CI] Test what is installed, not from repo" vs ["[LibOS,Pal] tests: Run tests from installed graphene" and "[Examples] Run tests from installed graphene"] - what's the difference actually? Could you clarify this a bit in the commit messages? The first one sounds like something which should cover everything included in the others.
- "pt1" -> "pt. 1"

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZdqd-0QDERal6hDu:-MYGZdqd-0QDERal6hDv:byvjahm) (no related file):*
TODO for myself: test the changes in my setup.

---
___
*[Makefile, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZjjU6hBNWBxYNrUj:-MYGZjjU6hBNWBxYNrUk:btx7vfz) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L19)):*
> ```
> arere
> ```

> ```
> transision
> ```

:)
___
*[Makefile, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYG_kuD80EWO4l7cXp_:-MYG_kuD80EWO4l7cXpa:b-wxp356) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L19)):*
> ```Makefile
> 	$(MAKE) -C Tools $@
> 	@echo
> 	@echo NOTE: We arere in the middle of transision to meson build system.
> ```

`meson` -> `Meson`
___
*[Makefile, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGcw0z2ixUmAM3G8bR:-MYGcw0z2ixUmAM3G8bS:bcjoipr) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L19)):*
> ```Makefile
> 	$(MAKE) -C Tools $@
> 	@echo
> 	@echo NOTE: We arere in the middle of transision to meson build system.
> ```

`build system` -> `buildsystem` (for consistency with other places in this PR)
___
*[Makefile, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYG_t0j6ZyuNawcx0Qp:-MYG_t0j6ZyuNawcx0Qq:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L20)):*
> ```Makefile
> 	@echo
> 	@echo NOTE: We arere in the middle of transision to meson build system.
> 	@echo You have sucessfully built Graphene, now please install Graphene using meson.
> ```

ditto
___
*[Makefile, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYG_v019sfQKfeydySf:-MYG_v019sfQKfeydySg:bh2bnz1) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L20)):*
> ```Makefile
> 	@echo
> 	@echo NOTE: We arere in the middle of transision to meson build system.
> 	@echo You have sucessfully built Graphene, now please install Graphene using meson.
> ```

`sucessfully` -> `successfully`
___
*[README.rst, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGcrep-S3yEvy4MkRJ:-MYGcrep-S3yEvy4MkRK:b-m6ydue) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/README.rst#L18)):*
> ```reStructuredText
> .. highlight:: sh
> 
> **NOTE:** we are in the middle of transitioning buildsystem to meson, and the
> ```

`buildsystem` -> `our buildsystem`
___
*[README.rst, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGdIw-6rZ2IdCOgmN2:-MYGdIw-6rZ2IdCOgmN3:b-wxp356) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/README.rst#L18)):*
> ```reStructuredText
> .. highlight:: sh
> 
> **NOTE:** we are in the middle of transitioning buildsystem to meson, and the
> ```

`meson` -> `Meson`
___
*[README.rst, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGdNAAEA2xXtxvFsc0:-MYGdNAAEA2xXtxvFsc1:bdbjyuw) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/README.rst#L18)):*
> ```reStructuredText
> .. highlight:: sh
> 
> **NOTE:** we are in the middle of transitioning buildsystem to meson, and the
> ```

`we` -> `We`
___
*[.ci/lib/config.jenkinsfile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGeinfEOZk8WbMuO7z:-MYGeinfEOZk8WbMuO8-:b-4cl83o) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/config.jenkinsfile#L7)):*
> ```
> import os, sysconfig
> print(sysconfig.get_path('platlib', vars={'platbase': os.environ['PREFIX']}))
> "''').trim()
> ```

Shouldn't this command be run inside the docker image? Jenkins host may have different paths that the image.
___
*[.ci/lib/stage-test.jenkinsfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYKDECw6PqVQjixZ4cd:-MYKDECx63l51rJxgsd3:b7orp7g) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/stage-test.jenkinsfile#L59)):*
> ```
>                 fi
>                 make test
> #               python3 -m pytest -v --junit-xml fs.xml test_fs.py test_tmpfs.py test_pf.py
> ```

Why is this commented out?
___
*[Documentation/building.rst, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJm6Rt26yfTd-3xR6i:-MYKEkEm-D9luJLfA6Ob:bj0s1a2) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about `jq`? What about `ninja`?
</blockquote></details>

Shouldn't these (and `meson`) be moved to "Common dependencies"?
___
*[Documentation/building.rst, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYKEsry6QFoVukW-WJB:-MYKEsrz-uC7G_6p5yLB:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L68)):*
> ```reStructuredText
>     # For Ubuntu 16.04
>     sudo apt-get install -y ninja
>     sudo /usr/bin/pip3 install meson protobuf
> ```

ditto
___
*[Documentation/building.rst, line 162 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYKFOKKA79WfubEbpWE:-MYKFOKKA79WfubEbpWF:btcvs03) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L162)):*
> ```
> first make then meson
> ```

Please wrap "make" and "meson" in double backticks (or maybe in `:command:`?).
___
*[Documentation/building.rst, line 167 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJmlhH-eQv7zQv5za3:-MYKFWRdDK37E7tfbWB7:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L167)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`graphene-direct` is our internal name. People typically say `Graphene without SGX` or simply `Graphene`
</blockquote></details>

+1
___
*[Documentation/tutorials/pytorch/index.rst, line 300 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYKGsYJ03ubU8RBtrzY:-MYKGsYK87xhoIJDP9yH:btzy4uk) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/tutorials/pytorch/index.rst#L300)):*
> ```reStructuredText
> After running this command and building all the required files, we can
>  use :command:`graphene-sgx` to launch the PyTorch workload inside an SGX
>  enclave::
> ```

this paragraph is misformatted
___
*[Examples [...]

2021-04-15 17:54 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 76 of 83 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGW8KpBtk0zulBu0JQ:-MYLdtO94i-VOG8TGhJh:b-hrr5hs) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Some fix-ups for the commit messages:

- "Loader executable (PAL_CMD) is named "loader"" <- one-liners should be in imperative mood and specify what this particular commit does. With this one I'm not really sure if what you wrote is the change or the bug you're fixing in this commit.
- "[ci]" -> "[CI]"
- "[CI] Test what is installed, not from repo" vs ["[LibOS,Pal] tests: Run tests from installed graphene" and "[Examples] Run tests from installed graphene"] - what's the difference actually? Could you clarify this a bit in the commit messages? The first one sounds like something which should cover everything included in the others.
- "pt1" -> "pt. 1"
</blockquote></details>

Done. I squashed those two commits, since there's no good way to split them (Scripts/regression.py should be in both). This resulted in awkward `[CI,LibOS,Pal]` tag. Oh well.

---
___
*[Makefile, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJjzJl7KZvpMlszIpq:-MYLVas4ArZnf7SUXp5U:b-gphu12) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Multiple typos. Corrected: `NOTE: We are in the middle of a transition to the meson build system.`
</blockquote></details>

Thanks, guys. Sorry for this.
___
*[Makefile, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYG_t0j6ZyuNawcx0Qp:-MYLVoTl71caCGpfvhGY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Makefile, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYG_v019sfQKfeydySf:-MYLVorxAIX5Phx0Gzf3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Makefile#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`sucessfully` -> `successfully`
</blockquote></details>

Done.
___
*[README.rst, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGdNAAEA2xXtxvFsc0:-MYLVzE70cdrdo-fD8FY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/README.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`we` -> `We`
</blockquote></details>

Done.
___
*[README.rst, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGdIw-6rZ2IdCOgmN2:-MYLVzZi44SibpgBrxNW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/README.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`meson` -> `Meson`
</blockquote></details>

Done.
___
*[README.rst, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGcrep-S3yEvy4MkRJ:-MYLW-_X-uj9D_Z545eA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/README.rst#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`buildsystem` -> `our buildsystem`
</blockquote></details>

Done.
___
*[.ci/lib/config.jenkinsfile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGeinfEOZk8WbMuO7z:-MYLW5427FEkfu8kewUp:bfnxiur) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/config.jenkinsfile#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't this command be run inside the docker image? Jenkins host may have different paths that the image.
</blockquote></details>

Yes, and also different python version. That's why this was split from config-docker.jenkinsfile and right now only config-docker.jenkinsfile runs outside of docker. See linux-*.jenkinsfile changes.
___
*[.ci/lib/stage-test.jenkinsfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJlbTW9P7SG5mgDInV:-MYLWUiB7I9hUtUIyVF4:b8nnhf8) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/stage-test.jenkinsfile#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why can't we use it? Because we don't know which tests to perform?
- `test_fs.py` and `test_tmpfs.py` should be done for non-SGX
- all three should be done for SGX
</blockquote></details>

There is some compilation dependency inside makefiles, which I haven't been able to fix quickly, so I reverted. The tests themselves are properly skipped (I believe).
___
*[.ci/lib/stage-test.jenkinsfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYKDECw6PqVQjixZ4cd:-MYLWqKR0e7JM8Doq3tk:b7lgczm) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/stage-test.jenkinsfile#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this commented out?
</blockquote></details>

See other thread.
___
*[Documentation/building.rst, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJm6Rt26yfTd-3xR6i:-MYLX3iE89ljaHTRNiMb:b-qvq4tz) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L64)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't these (and `meson`) be moved to "Common dependencies"?
</blockquote></details>

- `jq` is only for jenkins, not actually needed in practice
- `ninja` is a hard dependency of `meson` package iff it is installed from apt
- Unfortunately in 16.04 apt has too old version, so you need to install from pip, then install ninja from usual place.

Yes, it's common. Moved.
___
*[Documentation/building.rst, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYKEsry6QFoVukW-WJB:-MYLXfyc3Vo-GxcRmOPp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Documentation/building.rst, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJmOjp52-LSCKHLDIb:-MYLYMjeC2JugjFD-4De:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`it` -> `them`
</blockquote></details>

Done.
___
*[Documentation/building.rst, line 137 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJmSJS7BwvQ634gTLP:-MYLZ6Rt1VQHnBqYd4b_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/building.rst#L137)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you also add yet another alternative: if you already have Linux 5.11+, then the SGX driver is already enabled and there is no need to install a separate one.
</blockquote></details>

Done.
___
*[Documentation/building.rst, line 162 at r1](https://reviewable [...]

2021-04-15 20:12 UTC, woju commented
Jenkins, retest Jenkins-18.04 please
Jenkins, retest Jenkins-Debug please

2021-04-15 20:13 UTC, woju commented
Jenkins, retest Jenkins-Debug please

2021-04-16 06:37 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[.ci/lib/stage-test.jenkinsfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJlbTW9P7SG5mgDInV:-MYOKsfTA3NCuChKBKkl:bydno1v) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/stage-test.jenkinsfile#L59)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

There is some compilation dependency inside makefiles, which I haven't been able to fix quickly, so I reverted. The tests themselves are properly skipped (I believe).
</blockquote></details>

OK, so you want to fix it in a later PR. Unblocking.
___
*[Documentation/building.rst, line 136 at r2](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYOMnYP8fplviO-Vumv:-MYOMnYP8fplviO-Vumw:biq7tt6) ([raw file](https://github.com/oscarlab/graphene/blob/8c44a0300f7f53ba9d5fc6f8173da1ca4c889788/Documentation/building.rst#L136)):*
> ```reStructuredText
> 
> If you have kernel 5.11 or later, the SGX driver is part of the upstream kernel
> and you don't need to do anything. If you have older kernel, you need to install
> ```

Well, `don't need to do anything` is incorrect. You don't need to install the SGX driver, but you still need to install the SDK/PSW...

Either split this section into two (`3. Install Intel SGX driver` and `4. Install Intel SGX SDK/PSW`) or slightly re-word the current sentence.
___
*[Documentation/building.rst, line 178 at r2](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYOMJ-kEAISXMdNeBbA:-MYOMJ-kEAISXMdNeBbB:b-i21626) ([raw file](https://github.com/oscarlab/graphene/blob/8c44a0300f7f53ba9d5fc6f8173da1ca4c889788/Documentation/building.rst#L178)):*
> ```
>  (note that "direct" means non-SGX version)
> ```

Could add this comment here? Because this is the first time this term is used in this document. And you can remove from below (or keep it, as you wish).
___
*[Documentation/manifest-syntax.rst, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJnj-3BGV9-bAuIgAI:-MYOMarw5Xl4FMdaXoFP:bepzqve) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Documentation/manifest-syntax.rst#L90)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Users are used to `./pal_loader`, so IDK. In the future people will think of graphene as "that thing used to run programs in SGX", not unlike qemu, which is "the thing used to run KVM" (which is even less true than graphene case). So when they'd try `graphene` and it won't run things in SGX, that would be a confusion.
</blockquote></details>

OK, very good point. I agree that we should keep it like you did.
___
*[Examples/gcc/Makefile, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJoltAEzBEMflrLda4:-MYON9Ou1-fc_ZRV-w2Q:b-xxotck) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/Examples/gcc/Makefile#L62)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, it's not installed and yes, we don't want it to ever see the sunshine. It will go away as part of meson rewrite.
</blockquote></details>

OK, good to know.
___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MYONGMe7KvwMsuoAx2V:bim1mwv) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I dunno, but it was in the Makefile, so I copied it here.
</blockquote></details>

I mean, this library is an interesting case. We'll probably have a couple more such libraries in the future (e.g., Go runtime).

This is the **patched GNU OpenMP** library. The idea is that the original version of this library uses "raw syscalls", which is very bad for Graphene-SGX performance. So we have an **optional make rule** to build a patched version of this library, which makes Graphene-SGX run much faster. This gives significant performance boost for **some applications**, but most apps don't need this. So this is only an optional thingy.

I can imagine the same for some other popular libraries. E.g., the Go runtime libraries will be probably patched in the same way, and they must be somehow distributed as optional features of Graphene-SGX. Also, maybe JVM and R runtime will be patched in a similar way.

What do you think, @woju , how should we go about this?
___
*[LibOS/shim/test/regression/.gitignore, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpqhO9Fic8-StZyso:-MYOOOSx7oscY1CWLUOp:burkqac) ([raw file](https://github.com/oscarlab/graphene/blob/b3f9e6d5e5278a540453404685ed82428f95df07/LibOS/shim/test/regression/.gitignore#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We need them for `{{ graphene.libos }}` and `{{ graphene.runtime() }}`, because those change from install to install (the absolute paths change depending on what's the jenkins job called). After the installation I doubt we can have tested non-template manifests in the repo.
</blockquote></details>

Yes, I understand the need for this. Michal is fine with this, so resolving.


<!-- Sent from Reviewable.io -->

2021-04-19 14:59 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJqkh40mgcGHgz3jVm:-MYecedH-SMcaiLHwpMW:b-k7g4dd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I have a feeling GSC will break completely due to this change. Could you do a quick test of GSC with your PR? You can follow this quick start: https://graphene.readthedocs.io/en/latest/manpages/gsc.html#example
</blockquote></details>

Right now it possibly still works, because I haven't technically broke the previous way of running graphene, so testing this now won't find anything. But you're right that the next PR in queue will certainly break things.

---
___
*[Documentation/building.rst, line 136 at r2](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYOMnYP8fplviO-Vumv:-MYeafzO7xpMarF_Ssrw:b-lq73v7) ([raw file](https://github.com/oscarlab/graphene/blob/8c44a0300f7f53ba9d5fc6f8173da1ca4c889788/Documentation/building.rst#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, `don't need to do anything` is incorrect. You don't need to install the SGX driver, but you still need to install the SDK/PSW...

Either split this section into two (`3. Install Intel SGX driver` and `4. Install Intel SGX SDK/PSW`) or slightly re-word the current sentence.
</blockquote></details>

Do you really? I thought we just `open("/dev/sgx/enclave")` ourselves and we don't have any external dependencies. Or did I miss something, maybe some auxiliary Linux-SGX/tools do need SDK?
___
*[Documentation/building.rst, line 178 at r2](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYOMJ-kEAISXMdNeBbA:-MYecAwA9Xjp-Ow98eOW:b-o00km5) ([raw file](https://github.com/oscarlab/graphene/blob/8c44a0300f7f53ba9d5fc6f8173da1ca4c889788/Documentation/building.rst#L178)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> ```
>  (note that "direct" means non-SGX version)
> ```

Could add this comment here? Because this is the first time this term is used in this document. And you can remove from below (or keep it, as you wish).
</blockquote></details>

Oh, good catch. I rewrote the second sequence so it won't be 100% duplicate.
___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MYeHlv775bivb8_37fq:b8898vr) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I mean, this library is an interesting case. We'll probably have a couple more such libraries in the future (e.g., Go runtime).

This is the **patched GNU OpenMP** library. The idea is that the original version of this library uses "raw syscalls", which is very bad for Graphene-SGX performance. So we have an **optional make rule** to build a patched version of this library, which makes Graphene-SGX run much faster. This gives significant performance boost for **some applications**, but most apps don't need this. So this is only an optional thingy.

I can imagine the same for some other popular libraries. E.g., the Go runtime libraries will be probably patched in the same way, and they must be somehow distributed as optional features of Graphene-SGX. Also, maybe JVM and R runtime will be patched in a similar way.

What do you think, @woju , how should we go about this?
</blockquote></details>

I don't know anything about this problem and how it affects the libraries/runtimes you listed, but I can answer from packaging/maintainaince position.

So about optionality of support for any particular library, it's optional for enclave developer, which means that we either provide it (almost) always or not at all. Sure we will provide a compile-time switch, but for a release/distro package it will always be enabled, because IIUC disabling it will make things slower. It will be used for non-technical reasons like licence compatibility etc.

So some day we'll need to investigate all the libraries in existence and check if they're affected by this "raw syscalls" problem and decide whether we'd like to patch, based on amount of work needed and expected gains. Depending on what we'd like to optimise for, we can keep them in main `graphene` repo (this would be optimisation for developers) or we can keep them in separate repos (this would be optimisation for distro/packagers). For now let's keep them here in the repo.

(Is that alternative "syscall replacement" interface stable? Do we need to keep recompiled libraries in sync with graphene? What changes more often: the patches or the interface?)

Note that this all is really gathering a new OS (because it has a different syscall interface), so in time LibOS won't be much "Lib" anymore.


<!-- Sent from Reviewable.io -->

2021-04-22 17:59 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 82 of 83 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/building.rst, line 135 at r3](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYuiHG4BhKE2_pWk3CX:-MYuiHGCBVXWKV9Zf2V4:b7l0tgc) ([raw file](https://github.com/oscarlab/graphene/blob/0735f100a522f70501b0190d7dece19b179b70e6/Documentation/building.rst#L135)):*
> ```reStructuredText
> """""""""""""""""""""""""""""""""""""""""""
> 
> If you have kernel 5.11 or later, the SGX driver is part of the upstream kernel
> ```

Recently Thibaud raised an important point on slack: if you have a CPU without FLC, you're limited to OOT driver. Do we need to mention this here? (or somewhere near the kernel driver choice)

@dimakuv @mkow


<!-- Sent from Reviewable.io -->

2021-04-22 18:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 82 of 83 files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/building.rst, line 135 at r3](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYuiHG4BhKE2_pWk3CX:-MYukOqw5GuDUqu9Jphp:bsvwtd1) ([raw file](https://github.com/oscarlab/graphene/blob/0735f100a522f70501b0190d7dece19b179b70e6/Documentation/building.rst#L135)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Recently Thibaud raised an important point on slack: if you have a CPU without FLC, you're limited to OOT driver. Do we need to mention this here? (or somewhere near the kernel driver choice)

@dimakuv @mkow
</blockquote></details>

Good point, I think we should mention it here.


<!-- Sent from Reviewable.io -->

2021-04-23 01:47 UTC, mkow requested changes
> Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[.ci/lib/config.jenkinsfile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGeinfEOZk8WbMuO7z:-MYwLx104Rum-nJ98C5g:b-7vo826) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/config.jenkinsfile#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, and also different python version. That's why this was split from config-docker.jenkinsfile and right now only config-docker.jenkinsfile runs outside of docker. See linux-*.jenkinsfile changes.
</blockquote></details>

Ah, I see.
___
*[.ci/lib/stage-test.jenkinsfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJlbTW9P7SG5mgDInV:-MYwM8US4L6v9gQivXvG:b-r6d04q) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/stage-test.jenkinsfile#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, so you want to fix it in a later PR. Unblocking.
</blockquote></details>

Please add a TODO comment with this explanation then.
___
*[Documentation/building.rst, line 45 at r3](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYwMN1E90CvzxPoWxCA:-MYwMN1F96ybdiaYcZqI:b8o8w70) ([raw file](https://github.com/oscarlab/graphene/blob/0735f100a522f70501b0190d7dece19b179b70e6/Documentation/building.rst#L45)):*
> ```reStructuredText
>     sudo apt-get install -y meson
> 
> Or in Ubuntu 16.04::
> ```

16.04 support was dropped in the meantime
___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MYwOJtX8UQFbz9JBgTE:b7j0hgp) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
> (Is that alternative "syscall replacement" interface stable? Do we need to keep recompiled libraries in sync with graphene? What changes more often: the patches or the interface?)

Hard to say, the syscall patching API should in theory be quite stable, but we recently made some changes to it, so it happens from time to time. Overall I'd say that the patched libraries change more often, but that's not a significant difference.


<!-- Sent from Reviewable.io -->

2021-04-26 08:40 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/building.rst, line 136 at r2](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYOMnYP8fplviO-Vumv:-MZCIjfP9wwoc37m7LvE:b-u7jy06) ([raw file](https://github.com/oscarlab/graphene/blob/8c44a0300f7f53ba9d5fc6f8173da1ca4c889788/Documentation/building.rst#L136)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Do you really? I thought we just `open("/dev/sgx/enclave")` ourselves and we don't have any external dependencies. Or did I miss something, maybe some auxiliary Linux-SGX/tools do need SDK?
</blockquote></details>

Yes, auxiliary Graphene tools need SDK/PSW. In particular, Graphene needs the AESM service which provides access to the Intel Launch Enclave and Intel Quoting Enclave -- these are all packages in the SDK/PSW. This is needed in Graphene's python signer tools and also in the Graphene RA-TLS/Secret Provisioning tools.
___
*[Documentation/building.rst, line 135 at r3](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYuiHG4BhKE2_pWk3CX:-MZCIfUP5pBa0VoW0B0S:b-otgfld) ([raw file](https://github.com/oscarlab/graphene/blob/0735f100a522f70501b0190d7dece19b179b70e6/Documentation/building.rst#L135)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good point, I think we should mention it here.
</blockquote></details>

Yes, would be nice to mention it.
___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MZCJdbN8aXq_g6GY0uq:b-kbmr8x) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
> (Is that alternative "syscall replacement" interface stable? Do we need to keep recompiled libraries in sync with graphene? What changes more often: the patches or the interface?)

The Graphene "syscall replacement" interface is not expected to change (too often). I hope we won't change it at all from now on. But yes, we need to keep recompiled libraries in sync with Graphene.

You are right about "gathering a new OS". There may be hundreds of such libraries that require recompilation to run under Graphene (with good performance), so this will become a real burden... Anyway, I'm resolving this from my side -- let's just keep it in the main Graphene repo and not try to package it / move to other places.

By the way, there was an idea to dynamically patch such "raw syscall" libraries in Graphene -- this would require a binary rewriting mechanism embedded in Graphene. Would be cool to revive this idea and actually implement it at some point.


<!-- Sent from Reviewable.io -->

2021-04-26 12:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MZDEEvC7qfFbgX9dh66:bgscqlb) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
> By the way, there was an idea to dynamically patch such "raw syscall" libraries in Graphene -- this would require a binary rewriting mechanism embedded in Graphene. Would be cool to revive this idea and actually implement it at some point.

I don't think this is technically possible without DBI, which would turn Graphene into a completely different project (I mean, huge amount of code would need to be changed to integrate with e.g. DynamoRIO).


<!-- Sent from Reviewable.io -->

2021-04-26 13:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MZDHGUDDrhyIl8MQ7fz:b-peztc4) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> By the way, there was an idea to dynamically patch such "raw syscall" libraries in Graphene -- this would require a binary rewriting mechanism embedded in Graphene. Would be cool to revive this idea and actually implement it at some point.

I don't think this is technically possible without DBI, which would turn Graphene into a completely different project (I mean, huge amount of code would need to be changed to integrate with e.g. DynamoRIO).
</blockquote></details>

Yes, Graphene will need an embedded DBI. But from what I remember, there are quite small DBI engines created specifically for such purposes (definitely not DynamoRIO which is huge). Anyway, this is completely off-topic.


<!-- Sent from Reviewable.io -->

2021-04-26 13:53 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MZDRHToBRx6HT1Qe4YQ:bl4qyo4) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, Graphene will need an embedded DBI. But from what I remember, there are quite small DBI engines created specifically for such purposes (definitely not DynamoRIO which is huge). Anyway, this is completely off-topic.
</blockquote></details>

Are they better than just some artifacts from research papers? :) Overall I'm quite skeptical, DynamoRIO is that huge for a reason.

Anyways, as you said, it's off-topic, just wanted to mark that it's not necessarily something which we'll ever manage to implement.


<!-- Sent from Reviewable.io -->

2021-04-26 16:02 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 71 of 88 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

___
*[.ci/lib/stage-test.jenkinsfile, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJlbTW9P7SG5mgDInV:-MZDFG4q9gmo-ooMPGiH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/.ci/lib/stage-test.jenkinsfile#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a TODO comment with this explanation then.
</blockquote></details>

Done.
___
*[Documentation/building.rst, line 136 at r2](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYOMnYP8fplviO-Vumv:-MZDoZ_OCwvR0VO4UjzB:b-shxbll) ([raw file](https://github.com/oscarlab/graphene/blob/8c44a0300f7f53ba9d5fc6f8173da1ca4c889788/Documentation/building.rst#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, auxiliary Graphene tools need SDK/PSW. In particular, Graphene needs the AESM service which provides access to the Intel Launch Enclave and Intel Quoting Enclave -- these are all packages in the SDK/PSW. This is needed in Graphene's python signer tools and also in the Graphene RA-TLS/Secret Provisioning tools.
</blockquote></details>

I rewrote this section to have 5.11 driver mentioned first as recommendation, and to describe FLC.
___
*[Documentation/building.rst, line 45 at r3](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYwMN1E90CvzxPoWxCA:-MZDG9T77nfLokblB7p3:bgcsnan) ([raw file](https://github.com/oscarlab/graphene/blob/0735f100a522f70501b0190d7dece19b179b70e6/Documentation/building.rst#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

16.04 support was dropped in the meantime
</blockquote></details>

Done, and also:
- fixed the part about testing above, together with "3.x/4.x/5.x";
- added python3-click needed for python cli tools.
___
*[Documentation/building.rst, line 135 at r3](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYuiHG4BhKE2_pWk3CX:-MZDoqzrAqzMedVfLuHA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0735f100a522f70501b0190d7dece19b179b70e6/Documentation/building.rst#L135)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, would be nice to mention it.
</blockquote></details>

Done.
___
*[LibOS/meson.build, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYJpYMw6nU2OAP3HEIK:-MZDp5cg9_6F1zu1dyS6:blfl072) ([raw file](https://github.com/oscarlab/graphene/blob/3bad210df4417d07c30e67f111459ec8e881188b/LibOS/meson.build#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Are they better than just some artifacts from research papers? :) Overall I'm quite skeptical, DynamoRIO is that huge for a reason.

Anyways, as you said, it's off-topic, just wanted to mark that it's not necessarily something which we'll ever manage to implement.
</blockquote></details>

ACK this discussion, sure it's offtopic, if any of you care, plz file a feature request.


<!-- Sent from Reviewable.io -->

2021-04-26 16:04 UTC, woju commented
Rebased on top of current master, notably after upgrade of ubuntu versions, which got quite a few conflicts.





<!-- Sent from Reviewable.io -->

2021-04-26 23:41 UTC, mkow requested changes
> Reviewed 18 of 18 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[Documentation/building.rst, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFVQ-I2zZmCmFICSaV:-MZFVQ-K9QxrnqChgWBR:bfur1f3) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/building.rst#L40)):*
> ```reStructuredText
>     sudo apt-get install -y \
>         build-essential \
>         autoconf \
> ```

please sort
___
*[Documentation/building.rst, line 140 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFVyj78AuzDXHKUpso:-MZFVyj78AuzDXHKUpsp:b9hrx64) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/building.rst#L140)):*
> ```reStructuredText
> 
> - https://github.com/01org/linux-sgx
> - https://github.com/01org/linux-sgx-driver
> ```

Intel renamed recently "01org" to "intel" on GitHub, could you update it?
___
*[Documentation/building.rst, line 169 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFWHtFARBv1aPiTnZE:-MZFWHtFARBv1aPiTnZF:b-8flmsd) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/building.rst#L169)):*
> ```reStructuredText
> .. note::
> 
>    We're in the middle of the migration from make to meson. In the meantime you
> ```

`make` -> `Make`
`meson` -> `Meson`
___
*[Documentation/sgx-intro.rst, line 306 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFXxT09Kz7kOfKdi0v:-MZFXxT09Kz7kOfKdi0w:bxache1) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/sgx-intro.rst#L306)):*
> ```reStructuredText
> 
>       Support for FLC can be detected using ``CPUID`` instruction, as
>       ``CPUID.07H:ECX.SGX_LC[bit 30]`` (SDM vol. 2A calls this "SGX Launch
> ```

I'd add ` == 1` after `]`, just to be 100% clear
___
*[Documentation/sgx-intro.rst, line 312 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFWy1MC2cxdSff1WsN:-MZFWy1MC2cxdSff1WsO:buys3gl) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/sgx-intro.rst#L312)):*
> ```reStructuredText
> 
>          https://software.intel.com/en-us/blogs/2018/12/09/an-update-on-3rd-party-attestation
>             Announcement
> ```

Unrelated to the PR, but I just noticed that this "Announcement" is hanging here weirdly. Is it supposed to be explanation to the link above? Or was is supposed to be the displayed text of that link? Any idea?


<!-- Sent from Reviewable.io -->

2021-04-27 12:47 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 86 of 91 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/building.rst, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFVQ-I2zZmCmFICSaV:-MZIGwZc5wu82NEWXCrk:b-pelbv9) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/building.rst#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please sort
</blockquote></details>

`build-essential` is a special virtual package, and everything else is "in addition" to it. I sorted it first on purpose, because it is convenient for copy-pasting into package dependencies (`build-essential` is implied, you actually don't put it in packages).
___
*[Documentation/building.rst, line 140 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFVyj78AuzDXHKUpso:-MZIHAJi9CPrSXtleiZM:b-80tlqk) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/building.rst#L140)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Intel renamed recently "01org" to "intel" on GitHub, could you update it?
</blockquote></details>

Sure.
___
*[Documentation/building.rst, line 169 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFWHtFARBv1aPiTnZE:-MZIJEUw4PTvC58apkS0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/building.rst#L169)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`make` -> `Make`
`meson` -> `Meson`
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 306 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFXxT09Kz7kOfKdi0v:-MZIJQuA2iobR_MhF9En:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/sgx-intro.rst#L306)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add ` == 1` after `]`, just to be 100% clear
</blockquote></details>

Done.
___
*[Documentation/sgx-intro.rst, line 312 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFWy1MC2cxdSff1WsN:-MZIJTvX0PrbvKKPLDeu:bzckwjn) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/sgx-intro.rst#L312)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Unrelated to the PR, but I just noticed that this "Announcement" is hanging here weirdly. Is it supposed to be explanation to the link above? Or was is supposed to be the displayed text of that link? Any idea?
</blockquote></details>

`.. seealso::` contains definition list (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-seealso), and definition list is just term and indented description like here (https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#definition-lists). This was meant so you put the title of document you're supposed to "see also", and the description contains some narrative why you might want to read it with an URL if applicable.

So theoretically we should swap this and put the title ("An update on 3rd Party Attestation") in the dedented part and some description in the indented part ("Intel's announcement available at https://software.intel.com/en-us/blogs/2018/12/09/an-update-on-3rd-party-attestation" or so). But for technical documentation I find the url more descriptive (you clearly see where it came from and sets expectations on what you might find there), certainly more descriptive than the title of this those half-technical, half-marketing releases.


<!-- Sent from Reviewable.io -->

2021-04-27 12:57 UTC, mkow requested changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)

___
*[Documentation/building.rst, line 44 at r5](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZIO9rD6kPb3C7nrBRi:-MZIO9rD6kPb3C7nrBRj:b-su34x4) ([raw file](https://github.com/oscarlab/graphene/blob/1ae78de681fe9402940a8d0dfc010f4619c77c55/Documentation/building.rst#L44)):*
> ```reStructuredText
>         gawk \
>         meson \
>         python3-click
> ```

Aren't we missing jinja2 from here? (or below)
___
*[Documentation/sgx-intro.rst, line 312 at r4](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZFWy1MC2cxdSff1WsN:-MZIObGXE2HXZYxVIdsm:b-d1cg6y) ([raw file](https://github.com/oscarlab/graphene/blob/96bee1363ae161e534b3ee3ed5bf58610e4e12cb/Documentation/sgx-intro.rst#L312)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`.. seealso::` contains definition list (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-seealso), and definition list is just term and indented description like here (https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#definition-lists). This was meant so you put the title of document you're supposed to "see also", and the description contains some narrative why you might want to read it with an URL if applicable.

So theoretically we should swap this and put the title ("An update on 3rd Party Attestation") in the dedented part and some description in the indented part ("Intel's announcement available at https://software.intel.com/en-us/blogs/2018/12/09/an-update-on-3rd-party-attestation" or so). But for technical documentation I find the url more descriptive (you clearly see where it came from and sets expectations on what you might find there), certainly more descriptive than the title of this those half-technical, half-marketing releases.
</blockquote></details>

Hmm, ok. I find this formatting confusing, looks like a dangling word which was accidentally left here ;) Anyways, unblocking.


<!-- Sent from Reviewable.io -->

2021-04-27 14:49 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 90 of 91 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZdqd-0QDERal6hDu:-MZInYN57jf5JckCNIjI:b-a01wr5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO for myself: test the changes in my setup.
</blockquote></details>

Did you, by chance?

---
___
*[Documentation/building.rst, line 44 at r5](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZIO9rD6kPb3C7nrBRi:-MZInBj_99AFSuP9Ou9K:b-f06h8g) ([raw file](https://github.com/oscarlab/graphene/blob/1ae78de681fe9402940a8d0dfc010f4619c77c55/Documentation/building.rst#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Aren't we missing jinja2 from here? (or below)
</blockquote></details>

Yes, good catch.


<!-- Sent from Reviewable.io -->

2021-04-28 10:56 UTC, dimakuv approved these changes
> Reviewed 11 of 18 files at r4, 4 of 5 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-04-30 23:41 UTC, mkow requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZdqd-0QDERal6hDu:-MZVPlb8BHlrgnxB49Ac:bf7hjep) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Did you, by chance?
</blockquote></details>

Yup, some notes:
- `-Ddirect` and `-Dsgx` sound like something which may not age well if we ever support cross-compilation. We'll need to rename them to `linux-direct` and `linux-sgx` then. OTOH, right now they sound quite long. Also, I think we've already had this discussion, but I don't remember the conclusion.
- I get a deprecation warning on `meson build -Ddirect=enabled -Dsgx=enabled`: `DEPRECATION: Project targeting '>=0.45' but tried to use feature deprecated since '0.48.0': python3 module` and `WARNING: Deprecated features used:  * 0.48.0: {'python3 module'}`.
- Then, in the same command's output I get `Build targets in project: 0` and ofc ninja doesn't build anything because of this.

What am I doing wrong? I tried running on a clean repo from this branch, but I got into the same problem. Note that running Make succeeded and I followed all (I think) the steps from the docs.

---


<!-- Sent from Reviewable.io -->

2021-05-01 00:52 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 2 unresolved discussions (waiting on @woju)

___
*[Documentation/building.rst, line 225 at r6](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZ_OweGDandpk7NhBgm:-MZ_OweGDandpk7NhBgn:b-xxunqx) ([raw file](https://github.com/oscarlab/graphene/blob/ddf8f81e42e6579cab1c5061d47d0a13c8cec5d4/Documentation/building.rst#L225)):*
> ```
>  :command:`meson --prefix=<prefix>`
> ```

This doesn't work ("ERROR: Must specify at least one directory name."), I guess you meant adding `--prefix=<prefix>` to the `meson build` invocation mentioned above? Same with other such places in this section.


<!-- Sent from Reviewable.io -->

2021-05-01 09:06 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 85 of 92 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZdqd-0QDERal6hDu:-MZb125W0bjgWRKm5NK4:bvciwv0) (no related file):*
> -Ddirect and -Dsgx sound like something which may not age well if we ever support cross-compilation. We'll need to rename them to linux-direct and linux-sgx then. OTOH, right now they sound quite long. Also, I think we've already had this discussion, but I don't remember the conclusion.

Cross-compilation is done differently in meson: https://mesonbuild.com/Cross-compilation.html, so if the PAL will be the same (only `arch/` directory will be different), then it's OK.

The discussion was in #1858, on the occasion of renaming jenkins files.

> I get a deprecation warning on meson build -Ddirect=enabled -Dsgx=enabled: DEPRECATION: Project targeting '>=0.45' but tried to use feature deprecated since '0.48.0': python3 module and WARNING: Deprecated features used:  * 0.48.0: {'python3 module'}.

This is a bug in meson<=0.54.2 i believe: https://github.com/mesonbuild/meson/issues/7080, and Ubuntu 20.04 has 0.53. If you read it closely, it's apparent that the warnings are wrong.

> Then, in the same command's output I get Build targets in project: 0 and ofc ninja doesn't build anything because of this.

"Build targets" are `executable()`, `shared_library()` etc., but currently we only `install_data()`, which is not a build target, IOW meson doesn't run `cc` at all. So as of this commit `ninja -C build` is a no-op, only `ninja -C build install` actually does something. This all is intended, because of the gradual rewrite process we agreed upon, and this will change when we'll actually build something using meson (i.e. next PR in the series).

So I would leave all this as-is.

---
___
*[Documentation/building.rst, line 225 at r6](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZ_OweGDandpk7NhBgm:-MZb6QQb6whZScUMzG3O:byl66d1) ([raw file](https://github.com/oscarlab/graphene/blob/ddf8f81e42e6579cab1c5061d47d0a13c8cec5d4/Documentation/building.rst#L225)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  :command:`meson --prefix=<prefix>`
> ```

This doesn't work ("ERROR: Must specify at least one directory name."), I guess you meant adding `--prefix=<prefix>` to the `meson build` invocation mentioned above? Same with other such places in this section.
</blockquote></details>

Yes, fixed here and in `meson build --werror`.

`GLIBC_MIRRORS=` are orthogonal.

Debugs are tricky, and I wanted to address them at later stage, because unlike our makefiles, meson defaults to `debug` build unless you specify `--buildtype` like `meson build --buildtype=plain` or `meson build --build=release` (see https://mesonbuild.com/Builtin-options.html#core-options, second table).


<!-- Sent from Reviewable.io -->

2021-05-01 10:52 UTC, woju commented
Jenkins, test Jenkins-Debug-20.04 please

2021-05-01 12:56 UTC, mkow requested changes
> Reviewed 7 of 17 files at r7, 11 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZdqd-0QDERal6hDu:-MZbuXup-e3-ryKrrvrn:b-yi6og1) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> -Ddirect and -Dsgx sound like something which may not age well if we ever support cross-compilation. We'll need to rename them to linux-direct and linux-sgx then. OTOH, right now they sound quite long. Also, I think we've already had this discussion, but I don't remember the conclusion.

Cross-compilation is done differently in meson: https://mesonbuild.com/Cross-compilation.html, so if the PAL will be the same (only `arch/` directory will be different), then it's OK.

The discussion was in #1858, on the occasion of renaming jenkins files.

> I get a deprecation warning on meson build -Ddirect=enabled -Dsgx=enabled: DEPRECATION: Project targeting '>=0.45' but tried to use feature deprecated since '0.48.0': python3 module and WARNING: Deprecated features used:  * 0.48.0: {'python3 module'}.

This is a bug in meson<=0.54.2 i believe: https://github.com/mesonbuild/meson/issues/7080, and Ubuntu 20.04 has 0.53. If you read it closely, it's apparent that the warnings are wrong.

> Then, in the same command's output I get Build targets in project: 0 and ofc ninja doesn't build anything because of this.

"Build targets" are `executable()`, `shared_library()` etc., but currently we only `install_data()`, which is not a build target, IOW meson doesn't run `cc` at all. So as of this commit `ninja -C build` is a no-op, only `ninja -C build install` actually does something. This all is intended, because of the gradual rewrite process we agreed upon, and this will change when we'll actually build something using meson (i.e. next PR in the series).

So I would leave all this as-is.
</blockquote></details>

Looks better, but now I got a different warning:

```
python/graphenelibos/meson.build:20: WARNING: Got an empty configuration_data() object and found no
substitutions in the input file 'generated_offsets.py'. If you want to copy a file to the build dir,
use the 'copy:' keyword argument added in 0.47.0
```

And then on `ninja -C build install` (with custom `--prefix`) I get a huge wall of the following warnings repeated:
```
Warning: trying to copy a symlink that points to a file. This will copy the file,
but this will be changed in a future version of Meson to copy the symlink as is. Please update your
build definitions so that it will not break when the change happens.
```

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZbxqo-DoooZut7xVlj:-MZ_ODBVEltdij4DrXTa:b-h4k3iz) (no related file):*
How do I run regression tests now? `make regression` in `LibOS/shim/test/regression` fails with:
```
Traceback (most recent call last):
  File "/home/mkow/graphene-install/bin/graphene-manifest", line 4, in <module>
    from graphenelibos.manifest import main
ModuleNotFoundError: No module named 'graphenelibos'
```

Note, that we still specify this invocation as the way to test Graphene in Contributing to Graphene\Running Regression Tests by Hand.
Also, yup, I set `$PYTHONPATH`, but maybe incorrectly?

```
> echo $PYTHONPATH
/home/mkow/graphene-install/lib/python3.8/site-packages
> ls /home/mkow/graphene-install/lib/python3.8/site-packages
graphenelibos/
```

---


<!-- Sent from Reviewable.io -->

2021-05-01 17:14 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZdqd-0QDERal6hDu:-MZcp8zjA09mGK5uMou7:b-9ztn8u) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Looks better, but now I got a different warning:

```
python/graphenelibos/meson.build:20: WARNING: Got an empty configuration_data() object and found no
substitutions in the input file 'generated_offsets.py'. If you want to copy a file to the build dir,
use the 'copy:' keyword argument added in 0.47.0
```

And then on `ninja -C build install` (with custom `--prefix`) I get a huge wall of the following warnings repeated:
```
Warning: trying to copy a symlink that points to a file. This will copy the file,
but this will be changed in a future version of Meson to copy the symlink as is. Please update your
build definitions so that it will not break when the change happens.
```


</blockquote></details>

IDK. Setting to just `'0.45'` will cause errors instead of warnings if the version doesn't match exactly. So at this point I'm inclined to say that if you wan't to get rid of those bogus warnings, upgrade your meson (from newer distro or from pip). I'm dropping the patch with `meson_version:` change.

About symlinks:
```
% ls -ld /home/woju/graphene/LibOS/glibc-build/resolv/libresolv.so.2
lrwxrwxrwx 1 woju woju 12 May  1 18:57 /home/woju/graphene/LibOS/glibc-build/resolv/libresolv.so.2 -> libresolv.so
```
Looks like something to be fixed, because should install both the `.so.2` as symlink and `.so` as regular file. But here it doesn't hurt if we install files twice instead of file+symlink.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZbxqo-DoooZut7xVlj:-MZcpe3mDFWFPJjVmTKa:b-quone7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How do I run regression tests now? `make regression` in `LibOS/shim/test/regression` fails with:
```
Traceback (most recent call last):
  File "/home/mkow/graphene-install/bin/graphene-manifest", line 4, in <module>
    from graphenelibos.manifest import main
ModuleNotFoundError: No module named 'graphenelibos'
```

Note, that we still specify this invocation as the way to test Graphene in Contributing to Graphene\Running Regression Tests by Hand.
Also, yup, I set `$PYTHONPATH`, but maybe incorrectly?

```
> echo $PYTHONPATH
/home/mkow/graphene-install/lib/python3.8/site-packages
> ls /home/mkow/graphene-install/lib/python3.8/site-packages
graphenelibos/
```
</blockquote></details>

Could not reproduce:

```
% make -j`nproc` && make -j`nproc` SGX=1 ISGX_DRIVER_PATH=/opt/intel/linux-sgx-driver
[...]
% meson build -Dsgx=enabled -Ddirect=enabled --prefix=$HOME/usr
The Meson build system
Version: 0.53.2
Source dir: /home/woju/graphene
Build dir: /home/woju/graphene/build
Build type: native build
Project name: graphene
Project version: 1.0
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program /bin/sh found: YES (/bin/sh)
Configuring graphene-direct using configuration
Configuring graphene-sgx using configuration
Configuring __init__.py using configuration
Configuring _offsets.py using configuration
python/graphenelibos/meson.build:20: WARNING: Got an empty configuration_data() object and found no substitutions in the input file 'generated_offsets.py'. If you want to copy a file to the build dir, use the 'copy:' keyword argument added in 0.47.0
Build targets in project: 0

Found ninja-1.10.0 at /usr/bin/ninja
% ninja -C build                                               
ninja: Entering directory `build'
ninja: no work to do.
% ninja -C build install                                       
ninja: Entering directory `build'
[0/1] Installing files.
[...]
% export PYTHONPATH=/home/woju/usr/lib/python3.8/site-packages              
% export PATH=$PATH:/home/woju/usr/bin
% graphene-manifest
Usage: graphene-manifest [OPTIONS] INFILE [OUTFILE]
Try "graphene-manifest --help" for help.

Error: Missing argument "INFILE".
```
Which is OK (no `ImportError`).

Also `make regression` in `LibOS/shim/test/regression` went OK, and log says it built all manifests.

---


<!-- Sent from Reviewable.io -->

2021-05-04 01:07 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZouSJH9QV2-PjvWv35:-MZouSJI7HB1ZxtQ9k9o:br30z5k) (no related file):*
There are still some dangling references to `pal_loader` around the codebase, please fix.

---


<!-- Sent from Reviewable.io -->

2021-05-04 10:02 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: 86 of 116 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MYGZdqd-0QDERal6hDu:-MZqhIYWE8g6j8-K8jIW:bgfpsz0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> IDK. Setting to just '0.45' will cause errors instead of warnings if the version doesn't match exactly. So at this point I'm inclined to say that if you wan't to get rid of those bogus warnings, upgrade your meson (from newer distro or from pip). I'm dropping the patch with meson_version: change.

FYI: I already use a pretty new Ubuntu (20.04).

Anyways, resolving for now, but would be good to think if we can somehow silence the warnings on older Meson to not confuse people.

Ad. symlinks: please keep this in mind and fix it at some point of the buildsystem rework.
</blockquote></details>

Yes, this will be done when removing makefiles in `LibOS/`.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZouSJH9QV2-PjvWv35:-MZqoCnE139DZ_C5KFuF:b11g39h) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There are still some dangling references to `pal_loader` around the codebase, please fix.
</blockquote></details>

Removed references from `README`s and `.gitignore`s. There are still references in `Pal/**/Makefile`s and the `pal_loader.rst` manpage, which applies to both graphene-sgx and graphene-direct. Those will be fixed later.

---


<!-- Sent from Reviewable.io -->

2021-05-04 12:32 UTC, dimakuv approved these changes
> Reviewed 1 of 83 files at r1, 5 of 17 files at r7, 10 of 11 files at r8, 30 of 30 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-05-04 13:33 UTC, woju commented
Jenkins, test this please

2021-05-04 16:41 UTC, mkow requested changes
> Reviewed 30 of 30 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[meson.build, line 9 at r8](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZsDCJ3D1VoMl1BrHDG:-MZsDCJ3D1VoMl1BrHDH:b-ph8a92) ([raw file](https://github.com/oscarlab/graphene/blob/477abfd04692b0615eff76ed0ca595313b96a4ea/meson.build#L9)):*
> ```Meson
>     # meson>=0.54, because meson<0.54.2 has a bug which displays bogus warnings
>     # about deprecated versions: https://github.com/mesonbuild/meson/issues/7080
> #   meson_version: '>=0.45',
> ```

Accidental revert?


<!-- Sent from Reviewable.io -->

2021-05-04 16:48 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[meson.build, line 9 at r8](https://reviewable.io/reviews/oscarlab/graphene/2298#-MZsDCJ3D1VoMl1BrHDG:-MZsGj_W8ZNf1zjz9yrw:b-vmtrof) ([raw file](https://github.com/oscarlab/graphene/blob/477abfd04692b0615eff76ed0ca595313b96a4ea/meson.build#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Accidental revert?
</blockquote></details>

Talked on priv, it's intended (both versions resulted in bogus warnings, so it doesn't matter)


<!-- Sent from Reviewable.io -->

2021-05-04 17:32 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-04 18:15 UTC, mkow approved these changes
> Reviewed 1 of 30 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-05-04 18:23 UTC, dimakuv approved these changes
> Reviewed 1 of 30 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2298)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-04 18:46 UTC, merged