[LTP] Enable LTP tests that PASS but marked as skipped in ltp.cfg
oscarlab/graphene pull request #2301
Opened 2021-04-08 05:49 UTC by jinengandhi-intel

## Description of the changes 
With multiple features and bug-fixes that have been pushed to Graphene, multiple of the LTP tests have been passing with Graphene non-SGX. This PR is enabling such tests and removing the skip label from ltp.cfg.

2021-04-08 12:29 UTC, pwmarcz requested changes
Thanks!

As mentioned in the below comments, it would be good to have some more explanation why the skipped tests are failing, at least if it's easy for you to determine. Usually, reading the test code and running it with `log_level = "trace"` should be enough.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301#-:-MXlRalaBIvNeiJRsR3y:b-dheo7z)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 1325 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlQfqa5SaHTxjNLjDE:-MXlQfqb1cpzjrYoPTPw:b8zk1oa) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1325)):*
> ```INI
> skip = yes
> 
> # uses unsupported msync flag
> ```

Can you write which flag it is?
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1329 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlR7atCjnO4qe9KQF6:-MXlR7atCjnO4qe9KQF7:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1329)):*
> ```INI
> skip = yes
> 
> # 2 sub-tests fail with unsupported msync flag
> ```

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlR8gkA7MCrc4sy3Yz:-MXlR8gkA7MCrc4sy3Z-:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1337)):*
> ```INI
>     5
> 
> # uses unsupported msync flag
> ```

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlSCcR1b6mY2XLv_qJ:-MXlSCcSEG1h0TbMwTbE:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1684)):*
> ```INI
> skip = yes
> 
> # one sub-test fails with unsupported msync flag
> ```

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2380 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlRIDp2jypjMncwmr7:-MXlRIDp2jypjMncwmr8:bp7zoug) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L2380)):*
> ```INI
> skip = yes
> 
> [statfs02]
> ```

Can you add a comment why these test cases are failing?
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2392 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlRS927fC73LO8Vabq:-MXlRS927fC73LO8Vabr:bnlob6i) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L2392)):*
> ```INI
> skip = yes
> 
> [statvfs02]
> ```

Can you add a comment why this test case is failing?


<!-- Sent from Reviewable.io -->

2021-04-08 12:30 UTC, pwmarcz reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel)



<!-- Sent from Reviewable.io -->

2021-04-08 12:47 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 1161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlW9a98f0Is2DhtNBg:-MXlW9aAD4LIMnw3sYot:b-x29tt8) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/test/ltp/ltp.cfg#L1161)):*
> ```INI
> skip = yes
> 
> # uses siglongjmp() from exception handler back into normal execution; not supported by Graphene
> ```

@boryspoplawski: Does this actually work right now?
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1168 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlWB4CA1L7jVc2Pz-w:-MXlWB4CA1L7jVc2Pz-x:bfuw53q) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/test/ltp/ltp.cfg#L1168)):*
> ```INI
> skip = yes
> 
> # uses siglongjmp() from exception handler back into normal execution; not supported by Graphene
> ```

CC: @boryspoplawski
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1225 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlWH7CBotycOu-p6lZ:-MXlWH7CBotycOu-p6l_:bfuw53q) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/test/ltp/ltp.cfg#L1225)):*
> ```INI
>     2
> 
> # uses siglongjmp() from exception handler back into normal execution; not supported by Graphene
> ```

CC: @boryspoplawski


<!-- Sent from Reviewable.io -->

2021-04-08 14:52 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jinengandhi-intel and @mkow)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 1161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlW9a98f0Is2DhtNBg:-MXlxYvn2XNr9Arl-qVt:b-y97j7c) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/test/ltp/ltp.cfg#L1161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski: Does this actually work right now?
</blockquote></details>

`siglongjmp` should work, but I have no idea about this specific test.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1168 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlWB4CA1L7jVc2Pz-w:-MXlxf394JsJ-ONKIOjb:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/test/ltp/ltp.cfg#L1168)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

CC: @boryspoplawski
</blockquote></details>

ditto
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1225 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlWH7CBotycOu-p6lZ:-MXlxqOv17-QLgNGiOSJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/test/ltp/ltp.cfg#L1225)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

CC: @boryspoplawski
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2021-04-09 04:56 UTC, jinengandhi-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 1325 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlQfqa5SaHTxjNLjDE:-MXoyN-eAYKxXjlOlA3F:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1325)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can you write which flag it is?
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1329 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlR7atCjnO4qe9KQF6:-MXoyNgj7JGqpuNVNtU7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1329)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlR8gkA7MCrc4sy3Yz:-MXoyO3NB_0ozXh5ybXE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1337)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1684 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlSCcR1b6mY2XLv_qJ:-MXoyOZ61pmzLmltOQap:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L1684)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2380 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlRIDp2jypjMncwmr7:-MXoyPmH6qcLNbUsP__g:bv16oul) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L2380)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can you add a comment why these test cases are failing?
</blockquote></details>

statfs had 3 LTP tests out of which 1 is passing and hence I had to remove the [statfs*] block and mark skipped for individual tests. Here I have analyzed the failure reason for statfs02 and statfs02_64. statfs03 might need some more analysis. But there are many other skipped tests in ltp.cfg which don't have a comment so I don't think that should block the PR.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 2392 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlRS927fC73LO8Vabq:-MXozGvE3mLf56uVHr2F:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L2392)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can you add a comment why this test case is failing?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-09 07:49 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 2380 at r1](https://reviewable.io/reviews/oscarlab/graphene/2301#-MXlRIDp2jypjMncwmr7:-MXp_PQW7HCRptmNkRfx:b-tv6ifg) ([raw file](https://github.com/oscarlab/graphene/blob/f43b9cba5f809a58db9ee2c4eb7c10a3d1a6f4d6/LibOS/shim/test/ltp/ltp.cfg#L2380)):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

statfs had 3 LTP tests out of which 1 is passing and hence I had to remove the [statfs*] block and mark skipped for individual tests. Here I have analyzed the failure reason for statfs02 and statfs02_64. statfs03 might need some more analysis. But there are many other skipped tests in ltp.cfg which don't have a comment so I don't think that should block the PR.
</blockquote></details>

Sure - no need to go deep with analysis if something is more complicated. Thanks!


<!-- Sent from Reviewable.io -->

2021-04-09 11:55 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-09 14:31 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-09 14:31 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-12 09:30 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-12 09:38 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-04-12 09:43 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-04-12 09:47 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2301)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-12 10:19 UTC, merged