Clean up shim_handle types
oscarlab/graphene pull request #2302
Opened 2021-04-08 11:05 UTC by pwmarcz

It looks like there was an assumption that `shim_handle.info` is controlled by `shim_handle.type`, and at some point it broke down because of `TYPE_DIR`. See also #810 (which adds a workaround by extracting `info.dir` outside of union) and #836 (which proposes to clean up that workaround).

This change restores that assumption and ensures it's explicit in the code. Now directories are `TYPE_FILE` (or `TYPE_STR` in case of pseudo fs) with `is_dir == true`.

As a next step, I would like to rename `TYPE_FILE` to `TYPE_CHROOT` and `shim_file_handle` to `shim_chroot_handle` - these are specific to the "chroot" (host) filesystem, and it's not obvious because of the generic name, which causes some incorrect usages.

2021-04-08 12:29 UTC, mkow requested changes
> Reviewed 20 of 20 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_handle.h, line 308 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlNiKh03bHOxy2k1PX:-MXlNiKi4raJP297zfWf:b-4l8vi4) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/include/shim_handle.h#L308)):*
> ```objc
> struct shim_handle {
>     enum shim_handle_type type;
>     bool is_dir;
> ```

Please include `<stdbool.h>`
___
*[LibOS/shim/include/shim_handle.h, line 326 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlNrjEAtnoiESaDKXK:-MXlNrjEAtnoiESaDKXL:b-a57idz) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/include/shim_handle.h#L326)):*
> ```objc
>     PAL_HANDLE pal_handle;
> 
>     /* Type-specific fields: when accessing, ensure that type field is appropriate first (at least
> ```

please wrap "type" in backticks, this sentence is very confusing in the current form
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 177 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlOknM8FU5-6LVJk20:-MXlOknM8FU5-6LVJk21:be0b9dc) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/src/fs/shim_fs_pseudo.c#L177)):*
> ```C
>     if (*name == '\0') {
>         hdl->is_dir = true;
>         hdl->type = TYPE_STR;
> ```

Shouldn't we initialize `info` field at this point? It looks like this code leaves the structure in an inconsistent state (but it was already like this before this PR).
ditto for other similar places, I guess I'm just missing something?
___
*[LibOS/shim/src/sys/shim_open.c, line 251 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlQRBh0GpsZGMC_JfK:-MXlQRBiCpUgWqTD50ka:bdc4q8q) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/src/sys/shim_open.c#L251)):*
> ```C
>     if (hdl->type == TYPE_DIR)
>         goto out;
> ```

accidentally deleted?
___
*[LibOS/shim/src/sys/shim_open.c, line 511 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlQ_oz44OBHRQTu08v:-MXlQ_p08DUO4QNnq7p7:b-n108aq) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/src/sys/shim_open.c#L511)):*
> ```C
>         goto out;
> 
>     if (!hdl->is_dir)
> ```

gotcha! you flipped the condition here :)
update: ok, seems you just noticed :)
___
*[LibOS/shim/src/sys/shim_semget.c, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlRb3fDDzpDOTdzxag:-MXlRb3fDDzpDOTdzxah:bmqh9ed) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/src/sys/shim_semget.c#L71)):*
> ```C
> 
>     hdl->type   = TYPE_SEM;
>     tmp         = &hdl->info.sem;
> ```

I'd unalign this one assignment, as it's not assigning to structure fields as it's done in the lines below


<!-- Sent from Reviewable.io -->

2021-04-08 13:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: 14 of 20 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_handle.h, line 308 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlNiKh03bHOxy2k1PX:-MXlUlEnCg-0PjKfz1H3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/include/shim_handle.h#L308)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please include `<stdbool.h>`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_handle.h, line 326 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlNrjEAtnoiESaDKXK:-MXlUmCmDnCGMECWEez3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/include/shim_handle.h#L326)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please wrap "type" in backticks, this sentence is very confusing in the current form
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 177 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlOknM8FU5-6LVJk20:-MXlVCF15HylVEPzVW4d:b6v077u) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/src/fs/shim_fs_pseudo.c#L177)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we initialize `info` field at this point? It looks like this code leaves the structure in an inconsistent state (but it was already like this before this PR).
ditto for other similar places, I guess I'm just missing something?
</blockquote></details>

Okay, I looked deeper...

* Turns out that yeah, you have to initialize `TYPE_STR` with actual data (I was hoping to keep it zeroed out, but yes, that should have been explicit). So in this file, I'd rather not use `TYPE_STR`, but explicitly create a handle with no data (other filesystems might what to override that later). So I created `TYPE_PSEUDO` for the `pseudo_*` functions.

* There is one more suspicious place, which is `str_open`. It's never used directly (the whole "str filesystem" doesn't seem to be), only by tmpfs. I refactored it so that it makes more sense: `str_open` now performs full initialization (curiously, it increased the ref count but did not set info, even though later functions asserted that the info is set).
___
*[LibOS/shim/src/sys/shim_open.c, line 251 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlQRBh0GpsZGMC_JfK:-MXl_pkgBc4c1GZgAefg:bgwt35a) ([raw file](https://github.com/oscarlab/graphene/blob/666a451fcf2a738003e1e27efcc840e07068d426/LibOS/shim/src/sys/shim_open.c#L251)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

accidentally deleted?
</blockquote></details>

Yes. Fixed.
___
*[LibOS/shim/src/sys/shim_semget.c, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlRb3fDDzpDOTdzxag:-MXl_zJa0eTqQWFfNfOf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/src/sys/shim_semget.c#L71)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd unalign this one assignment, as it's not assigning to structure fields as it's done in the lines below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-08 13:36 UTC, mkow submitted a review, later dismissed
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 177 at r1](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXlOknM8FU5-6LVJk20:-MXlfmuTDVeCs-BRzxNP:b-al1xlf) ([raw file](https://github.com/oscarlab/graphene/blob/b034685a9d76d4cf1e50db664bcae01bb5b55aff/LibOS/shim/src/fs/shim_fs_pseudo.c#L177)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, I looked deeper...

* Turns out that yeah, you have to initialize `TYPE_STR` with actual data (I was hoping to keep it zeroed out, but yes, that should have been explicit). So in this file, I'd rather not use `TYPE_STR`, but explicitly create a handle with no data (other filesystems might what to override that later). So I created `TYPE_PSEUDO` for the `pseudo_*` functions.

* There is one more suspicious place, which is `str_open`. It's never used directly (the whole "str filesystem" doesn't seem to be), only by tmpfs. I refactored it so that it makes more sense: `str_open` now performs full initialization (curiously, it increased the ref count but did not set info, even though later functions asserted that the info is set).
</blockquote></details>

Looks better now, thanks!


<!-- Sent from Reviewable.io -->

2021-04-08 16:06 UTC, yamahata approved these changes
> Reviewed 14 of 20 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-08 17:08 UTC, boryspoplawski requested changes
> Reviewed 14 of 20 files at r1, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 424 at r3](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXmP8blCBJQWskjsL_-:-MXmP8blCBJQWskjsL_0:b-gi9tdd) ([raw file](https://github.com/oscarlab/graphene/blob/5a479050e8ceb0d5ac720c6f414442b0d310b6b0/LibOS/shim/src/bookkeep/shim_handle.c#L424)):*
> ```C
> 
>         if (hdl->is_dir) {
>             struct shim_dir_handle* dir = &hdl->dir_info;
> ```

Please add an assert on the `type`. Actually which ones are valid? PR description mentions `TYPE_FILE` and `TYPE_STR`, code also seems to use `TYPE_PSEUDO`, but it's not clear if other types are invalid.
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXmQeTiBG-LSrceWc33:-MXmQeTiBG-LSrceWc34:b9a4g26) ([raw file](https://github.com/oscarlab/graphene/blob/5a479050e8ceb0d5ac720c6f414442b0d310b6b0/LibOS/shim/src/fs/tmpfs/fs.c#L27)):*
> ```C
>  * Implementation:
>  *
>  * The tmpfs file handles are TYPE_STR, and we delegate to str_* functions. This works because
> ```

Delegate what? Seems like some part of this sentence is  missing...


<!-- Sent from Reviewable.io -->

2021-04-08 18:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: 17 of 22 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @yamahata)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 424 at r3](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXmP8blCBJQWskjsL_-:-MXmUxol72vuJqRr6NZu:bh09mci) ([raw file](https://github.com/oscarlab/graphene/blob/5a479050e8ceb0d5ac720c6f414442b0d310b6b0/LibOS/shim/src/bookkeep/shim_handle.c#L424)):*
>Please add an assert on the `type`.

The point is that it doesn't matter - we should do nothing here that would require a specific type.

But yes, now that I look at it, this is wrong because of the `else` branch. And it makes sense to execute `else` branch unconditionally - we always call `open` on handles, so we should also always call `close`.

I think the previous code was wrong, and we neglected to e.g. call `chroot_close` on directory handles. Which might explain why that function was empty...

I'm changing this. It required some changes in `proc`, `dev` and `sys` pseudo-filesystems, because they now also receive these `TYPE_PSEUDO` directory handles. But I think it's good direction overall, to make it explicit.

>Actually which ones are valid? PR description mentions `TYPE_FILE` and `TYPE_STR`, code also seems to use `TYPE_PSEUDO`, but it's not clear if other types are invalid.

As far as I know, yes, right now only these three handle types can be directory handles. I updated the PR description to account for `TYPE_PSEUDO`, sorry - I added that after @mkow's review.

Other handles cannot be directories, because they are produced by filesystems that do not support directories. But it should be up to the filesystem which initializes the handle (or initializes the dentry from which the handle is initialized).
___
*[LibOS/shim/src/fs/tmpfs/fs.c, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXmQeTiBG-LSrceWc33:-MXmZf6mBc7lio9faWC1:b-yewo2h) ([raw file](https://github.com/oscarlab/graphene/blob/5a479050e8ceb0d5ac720c6f414442b0d310b6b0/LibOS/shim/src/fs/tmpfs/fs.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Delegate what? Seems like some part of this sentence is  missing...
</blockquote></details>

I meant just "delegate", as in "defer to". Changed to "delegate work" to make it clearer.


<!-- Sent from Reviewable.io -->

2021-04-08 18:38 UTC, mkow reviewed
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-04-08 18:41 UTC, boryspoplawski approved these changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 424 at r3](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXmP8blCBJQWskjsL_-:-MXmmC7J07tjRVkAnVWp:b-sdmgst) ([raw file](https://github.com/oscarlab/graphene/blob/5a479050e8ceb0d5ac720c6f414442b0d310b6b0/LibOS/shim/src/bookkeep/shim_handle.c#L424)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>Please add an assert on the `type`.

The point is that it doesn't matter - we should do nothing here that would require a specific type.

But yes, now that I look at it, this is wrong because of the `else` branch. And it makes sense to execute `else` branch unconditionally - we always call `open` on handles, so we should also always call `close`.

I think the previous code was wrong, and we neglected to e.g. call `chroot_close` on directory handles. Which might explain why that function was empty...

I'm changing this. It required some changes in `proc`, `dev` and `sys` pseudo-filesystems, because they now also receive these `TYPE_PSEUDO` directory handles. But I think it's good direction overall, to make it explicit.

>Actually which ones are valid? PR description mentions `TYPE_FILE` and `TYPE_STR`, code also seems to use `TYPE_PSEUDO`, but it's not clear if other types are invalid.

As far as I know, yes, right now only these three handle types can be directory handles. I updated the PR description to account for `TYPE_PSEUDO`, sorry - I added that after @mkow's review.

Other handles cannot be directories, because they are produced by filesystems that do not support directories. But it should be up to the filesystem which initializes the handle (or initializes the dentry from which the handle is initialized).
</blockquote></details>

This looks now weird as you handle `TYPE_PSEUDO` inside some other types' specific files (e.g. dev).
But I probably just don't understand what `TYPE_PSEUDO` is, so I'm fine with these changes :)


<!-- Sent from Reviewable.io -->

2021-04-08 18:59 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 424 at r3](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXmP8blCBJQWskjsL_-:-MXmn8gwDhXOpisanqFg:bqsbsv9) ([raw file](https://github.com/oscarlab/graphene/blob/5a479050e8ceb0d5ac720c6f414442b0d310b6b0/LibOS/shim/src/bookkeep/shim_handle.c#L424)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This looks now weird as you handle `TYPE_PSEUDO` inside some other types' specific files (e.g. dev).
But I probably just don't understand what `TYPE_PSEUDO` is, so I'm fine with these changes :)
</blockquote></details>

I agree that's ugly, same applies to `TYPE_STR`. It's because these filesystems (proc, tmp, dev, sys) reuse code from "str" and "pseudo".

So, it's kind of by (existing) design, only the design is not so good. I hope I'll be able to make it better, this change just makes the ugliness visible :)


<!-- Sent from Reviewable.io -->

2021-04-12 09:09 UTC, pwmarcz reviewed
Test failure (https://leeroy.cs.unc.edu/job/graphene-sgx-18.04/5067/) looks related to recent change in logging subsystem, see #2304 for fix.

In the meantime, I'm rebasing this on newest master.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302#-:-MY4KaZM-mBXznFUjR5p:b-r178ff)* status: 21 of 22 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-04-12 10:17 UTC, dimakuv requested changes
> Reviewed 12 of 20 files at r1, 5 of 6 files at r3, 4 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4ZtXh1m_GH1yfpGML:-MY4ZtXh1m_GH1yfpGMM:b-mpoyd1) (no related file):*
I don't understand this commit sentence: `Directories in pseudo filesystems are treated as TYPE_STR with empty data.` But in code, it looks like directories are created as `TYPE_PSEUDO` and never change into `TYPE_STR`. E.g.:

```
    if (hdl->type == TYPE_PSEUDO) {
        /* e.g. a directory */
        return 0;
    }
```

---
___
*[LibOS/shim/include/shim_handle.h, line 39 at r5](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4_Vun4FFwXMswlU-J:-MY4UV4m3qyFl3LciY36:bb9vpwz) ([raw file](https://github.com/oscarlab/graphene/blob/adc3a4ec6e26e08bbaf46682b8e9619813f22784/LibOS/shim/include/shim_handle.h#L39)):*
> ```objc
>     TYPE_EPOLL,
>     TYPE_EVENTFD,
>     TYPE_PSEUDO,
> ```

Since we're here, can we group these types logically (all "file" types in one group, all pipe/socket in another group, and the rest -- epoll, sem, eventfd, msg -- in yet another group). Plus add brief comments for each type.
___
*[LibOS/shim/include/shim_handle.h, line 329 at r5](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4VuWh0sFFHRvQAYTu:-MY4VuWh0sFFHRvQAYTv:bi93nr2) ([raw file](https://github.com/oscarlab/graphene/blob/adc3a4ec6e26e08bbaf46682b8e9619813f22784/LibOS/shim/include/shim_handle.h#L329)):*
> ```objc
> 
>     /* Type-specific fields: when accessing, ensure that `type` field is appropriate first (at least
>      * by using assert())*/
> ```

Please add a space before closing `*/`
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 424 at r3](https://reviewable.io/reviews/oscarlab/graphene/2302#-MXmP8blCBJQWskjsL_-:-MY4Wyjy2qqS8QbsmSKq:b-u2fxiy) ([raw file](https://github.com/oscarlab/graphene/blob/5a479050e8ceb0d5ac720c6f414442b0d310b6b0/LibOS/shim/src/bookkeep/shim_handle.c#L424)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I agree that's ugly, same applies to `TYPE_STR`. It's because these filesystems (proc, tmp, dev, sys) reuse code from "str" and "pseudo".

So, it's kind of by (existing) design, only the design is not so good. I hope I'll be able to make it better, this change just makes the ugliness visible :)
</blockquote></details>

It makes the ugliness very much visible :)
___
*[LibOS/shim/src/fs/str/fs.c, line 7 at r5](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4XxAE0ciNADQvpMq0:-MY4XxAF3vuJbyKE5CeD:bbenxdx) ([raw file](https://github.com/oscarlab/graphene/blob/adc3a4ec6e26e08bbaf46682b8e9619813f22784/LibOS/shim/src/fs/str/fs.c#L7)):*
> ```C
>  * This file contains code for implementation of 'str' filesystem.
>  *
>  * TODO: This filesystem doesn't seem to be used directly, only by other filesystems. Refactor?
> ```

This is correct, the `str` filesystem is a bunch of "helper" functions (historical reasons...). It would be good to refactor it, yes. It is used by all pseudo-FSes: `tmpfs`, `/proc`, `/dev`.


<!-- Sent from Reviewable.io -->

2021-04-12 11:48 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: 20 of 22 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4ZtXh1m_GH1yfpGML:-MY4fs2D9_GfmsX8Hk0Z:bpcu280) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this commit sentence: `Directories in pseudo filesystems are treated as TYPE_STR with empty data.` But in code, it looks like directories are created as `TYPE_PSEUDO` and never change into `TYPE_STR`. E.g.:

```
    if (hdl->type == TYPE_PSEUDO) {
        /* e.g. a directory */
        return 0;
    }
```

</blockquote></details>

You're right, the commit message is outdated: I didn't realize `TYPE_PSEUDO` was necessary from the start.

It also looks like the two commits are not completely independent anymore, as the first one leaves directories in a messy state. I squashed them together and updated the commit message.

---
___
*[LibOS/shim/include/shim_handle.h, line 39 at r5](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4_Vun4FFwXMswlU-J:-MY4iJFCExUIbbQTkZlg:begw0lt) ([raw file](https://github.com/oscarlab/graphene/blob/adc3a4ec6e26e08bbaf46682b8e9619813f22784/LibOS/shim/include/shim_handle.h#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we're here, can we group these types logically (all "file" types in one group, all pipe/socket in another group, and the rest -- epoll, sem, eventfd, msg -- in yet another group). Plus add brief comments for each type.
</blockquote></details>

How about now?
___
*[LibOS/shim/include/shim_handle.h, line 329 at r5](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4VuWh0sFFHRvQAYTu:-MY4i_QLCCpRCVGqaRHK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/adc3a4ec6e26e08bbaf46682b8e9619813f22784/LibOS/shim/include/shim_handle.h#L329)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space before closing `*/`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/str/fs.c, line 7 at r5](https://reviewable.io/reviews/oscarlab/graphene/2302#-MY4XxAE0ciNADQvpMq0:-MY4iqAJ660-MPPf6gCb:byoj1yi) ([raw file](https://github.com/oscarlab/graphene/blob/adc3a4ec6e26e08bbaf46682b8e9619813f22784/LibOS/shim/src/fs/str/fs.c#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is correct, the `str` filesystem is a bunch of "helper" functions (historical reasons...). It would be good to refactor it, yes. It is used by all pseudo-FSes: `tmpfs`, `/proc`, `/dev`.
</blockquote></details>

Yes, it's also abused by tmpfs, and that seems like a slightly different use case.

Okay. I added an explanation, and on second thought I'm removing this TODO: I don't know exactly how to redesign it yet, so I don't want to keep a TODO that is too vague or contains outdated details.


<!-- Sent from Reviewable.io -->

2021-04-12 12:18 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-04-12 17:41 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-12 18:46 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-12 18:57 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2302)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-12 21:35 UTC, merged