[GSC] Add dockerfile and manifest file for ra-tls-secret-prov sample's gsc image
oscarlab/graphene pull request #2305
Opened 2021-04-12 19:15 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>
## Description of the changes 
This PR adds dockerifle and manifest file for ra-tls-secret-prov sample inside gsc/test folder. In addition to these two files, there is a docker-entrypoint.sh file provided in the gsc/test folder itself. Also, there is a small extra PHONY included inside /Examples/ra-tls-secret-prov/Makefile.

The objective of this PR is to provide a sample implementation of how a remote client running as part of docker container can provide it's sgx-based attestation report to a verifier/server entity.

## How to test this PR?
Step 0.  make sure RA-TLS DCAP libraries are built in Graphene via:
            $ cd graphene/Pal/src/host/Linux-SGX/tools/ra-tls && make dcap

Step 1. $ cd graphene
            $ docker build -t my_ra-tls-secret-prov:0.1 -f ~/graphene/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile .
            // Here "my_ra-tls-secret-prov:0.1" is the name of base ra-tls-secret-prov image.
            // ubuntu18.04-ra-tls-secret-prov.dockerfile is the dockerfile added as part of this PR.

Step 2. $  cd graphene/Tools/gsc
            $ ./gsc build  --insecure-args my_ra-tls-secret-prov:0.1 test/ubuntu18.04-ra-tls-secret-prov.manifest
            //  ubuntu18.04-ra-tls-secret-prov.manifest is the manifest added as part of this PR.

Step 3. ./gsc sign-image my_ra-tls-secret-prov:0.1  ~/graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem
             // Now we will have signed gsc image gsc-my_ra-tls-secret-prov:0.1

Step 4. Start the server
            $ cd graphene/Examples/ra-tls-secret-prov
            $  make dcap
            $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./libs
            $ RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 ./secret_prov_server_dcap &
            // Press ctrl +c , the server will be running in background

Step 5. docker run --net=host --device=/dev/sgx/enclave    -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc- my_ra-tls-secret-prov:0.1
// Output will look something like:
send secret1, send secret 2
received secret1, received secret 2

Note 1: By default the above steps are for DCAP attestation. For EPID attestation please uncomment "sgx.ra_client_spid" and "sgx.ra_client_linkable" inside ubuntu18.04-ra-tls-secret-prov.manifest. Also, please start EPID based server at the localhost.

Note 2: There are 3 clients implemented as part of Examples/ra-tls-secret-prov sample. The above steps will show output for secret_prov_client only. This binary is defined inside Tools/gsc/test/ra-tls-secret-prov-docker-entrypoint.sh. User can change the binary name inside this entrypoint.sh file, and also can uncomment client specific flags inside ubuntu18.04-ra-tls-secret-prov.manifest.

Note 3: In order to build client binaries in non-graphene / non-graphene-sgx mode, I have added a phony target "clients" inside graphene/Examples/ra-tls-secret-prov/Makefile. 

Note 4: This sample assumes the server is running on localhost:4433, so --net=host command will allow docker to connect to the localhost server. In real scenario, the server will be a remote entity.

2021-04-13 07:46 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9BKxhCPUnuUxzWCSv:-MY9BKxhCPUnuUxzWCSw:bdi56e) (no related file):*
I like your description of steps in the PR message. Can you copy-paste it (with some minimal changes for style) in your `.manifest` file as a top comment? People will wonder how to run this, and nobody wants to check GitHub for this...

---
___
*[Tools/gsc/test/ra-tls-secret-prov-docker-entrypoint.sh, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY98nhsDkcA73MaO1zo:-MY98nhtBtaMQ7qx0rZj:bw04cah) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ra-tls-secret-prov-docker-entrypoint.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./libs
> ```

Why do you need this complication of an additional bash script? You can declare the `LD_LIBRARY_PATH` environment variable in two places instead:
- Either in the `ubuntu18.04-ra-tls-secret-prov.dockerfile` using `ENV LD_LIBRARY_PATH ="${LD_LIBRARY_PATH}:./libs"`
- Or in the `ubuntu18.04-ra-tls-secret-prov.manifest` using `loader.env.LD_LIBRARY_PATH=/lib:/lib/x86_64-linux-gnu/:/usr//lib/x86_64-linux-gnu/:./libs`

...And then you don't need this `.sh` file and you can simply do `ENTRYPOINT ["/graphene/Examples/ra-tls-secret-prov/secret_prov_client"]`.

...But also I think you'll need to define in your Dockerfile something like this: `ENV PATH="${PATH}:/graphene/Examples/ra-tls-secret-prov"`, so that the Docker container actually knows where to search for `secret_prov_client` executable.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9ANQd4yAJKAWCl-u9:-MY9ANQd4yAJKAWCl-uA:byhd26l) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L9)):*
> ```Dockerfile
>     gnupg2
> 
> # Installing dcap and epid specific libraries 
> ```

Please remove all trailing whitespaces in your files.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AVJ77fCiqwAh1Wzt:-MY9AVJ77fCiqwAh1Wzu:btzfhz7) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L14)):*
> ```
> sgx.remote_attestation = 1
> 
> # Uncomment below lines for EPID-Based attestation
> ```

Please use small letter: `EPID-based`
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AguF5GPM_M4JJMI7:-MY9AguF5GPM_M4JJMI8:b2wviu1) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L30)):*
> ```
> fs.mount.etc.type = "chroot"
> fs.mount.etc.path = "/etc"
> fs.mount.etc.uri = "file:/etc"
> ```

None of these FS mount points should be needed. GSC adds them automatically. Please remove all three and check that everything still works.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AnUM351PFVZ0BwUs:-MY9AnUM351PFVZ0BwUt:bx99wyi) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L46)):*
> ```
> sgx.allowed_files.passwd = "file:/etc/passwd"
> sgx.allowed_files.gaiconf = "file:/etc/gai.conf"
> sgx.allowed_files.resolv = "file:/etc/resolv.conf"
> ```

None of these `sgx.trusted_files` and `sgx.allowed_files` are needed -- GSC adds them automatically. Please remove all **except `/etc/hostname`, `/etc/hosts` and `/etc/resolv.conf`**. See the rationale here: https://github.com/oscarlab/graphene/blob/master/Tools/gsc/test/ubuntu18.04-python3.manifest#L11
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9B5ijEKI7rkhr9BtK:-MY9B5ijEKI7rkhr9BtL:b-is6xcv) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L49)):*
> ```
> 
> # Uncomment for secret_prov_pf_client
> # sgx.protected_files.input = "file:files/input.txt"
> ```

This is correct, this entry will be needed (GSC can't know that this is a protected file)


<!-- Sent from Reviewable.io -->

2021-04-13 17:20 UTC, veenasai2 commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9BKxhCPUnuUxzWCSv:-MYBEZiC5FF28zOwgtTN:b77i4af) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like your description of steps in the PR message. Can you copy-paste it (with some minimal changes for style) in your `.manifest` file as a top comment? People will wonder how to run this, and nobody wants to check GitHub for this...
</blockquote></details>

sure, thanks.

---


<!-- Sent from Reviewable.io -->

2021-04-13 17:28 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9ANQd4yAJKAWCl-u9:-MYBGXN0BimuSxETx7ru:b-gourf7) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove all trailing whitespaces in your files.
</blockquote></details>

ok, I will check again. Thanks.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AVJ77fCiqwAh1Wzt:-MYBF6LR5_rrUPf0cWvT:bad9j1v) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use small letter: `EPID-based`
</blockquote></details>

sure, thanks.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AguF5GPM_M4JJMI7:-MYBFCeVABm1W0_dOzuy:b-4jikk3) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

None of these FS mount points should be needed. GSC adds them automatically. Please remove all three and check that everything still works.
</blockquote></details>

ok, I will check. Thanks.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AnUM351PFVZ0BwUs:-MYBFTTx40WlyN9VorK5:b-h7etc3) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

None of these `sgx.trusted_files` and `sgx.allowed_files` are needed -- GSC adds them automatically. Please remove all **except `/etc/hostname`, `/etc/hosts` and `/etc/resolv.conf`**. See the rationale here: https://github.com/oscarlab/graphene/blob/master/Tools/gsc/test/ubuntu18.04-python3.manifest#L11
</blockquote></details>

ok, I will remove. Thanks.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9B5ijEKI7rkhr9BtK:-MYBFkJJCGcTvipBICuj:b-ucfkn4) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is correct, this entry will be needed (GSC can't know that this is a protected file)
</blockquote></details>

Thanks.


<!-- Sent from Reviewable.io -->

2021-04-13 17:30 UTC, veenasai2 commented
___
*[Tools/gsc/test/ra-tls-secret-prov-docker-entrypoint.sh, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY98nhsDkcA73MaO1zo:-MYBH6WC790YCeon9AsT:b-sjws94) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ra-tls-secret-prov-docker-entrypoint.sh#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this complication of an additional bash script? You can declare the `LD_LIBRARY_PATH` environment variable in two places instead:
- Either in the `ubuntu18.04-ra-tls-secret-prov.dockerfile` using `ENV LD_LIBRARY_PATH ="${LD_LIBRARY_PATH}:./libs"`
- Or in the `ubuntu18.04-ra-tls-secret-prov.manifest` using `loader.env.LD_LIBRARY_PATH=/lib:/lib/x86_64-linux-gnu/:/usr//lib/x86_64-linux-gnu/:./libs`

...And then you don't need this `.sh` file and you can simply do `ENTRYPOINT ["/graphene/Examples/ra-tls-secret-prov/secret_prov_client"]`.

...But also I think you'll need to define in your Dockerfile something like this: `ENV PATH="${PATH}:/graphene/Examples/ra-tls-secret-prov"`, so that the Docker container actually knows where to search for `secret_prov_client` executable.
</blockquote></details>

I will get back on this soon, thanks.


<!-- Sent from Reviewable.io -->

2021-04-15 06:40 UTC, veenasai2 commented
___
*[Tools/gsc/test/ra-tls-secret-prov-docker-entrypoint.sh, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY98nhsDkcA73MaO1zo:-MYF4WLk7gcZkb7hYIxT:b-e4a8a2) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ra-tls-secret-prov-docker-entrypoint.sh#L3)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

I will get back on this soon, thanks.
</blockquote></details>

Earlier with ENTRYPOINT ["/graphene/Examples/ra-tls-secret-prov/secret_prov_client"], I was facing this error: 
[P9:T1:secret_prov_client] ERROR: Failed to load /secret_prov_client. This may be caused by the binary being non-PIE, in which case Graphene requires a specially-crafted memory layout. You can enable it by adding 'sgx.nonpie_binary = 1' to the manifest.

[P9:T1:secret_prov_client] Error during shim_init() in init_loader (-2).

This time when I use ENV PATH="${PATH}:/graphene/Examples/ra-tls-secret-prov", the error no longer was there. Anyways , I made changes as you suggested.


<!-- Sent from Reviewable.io -->

2021-04-15 06:43 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: 0 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9ANQd4yAJKAWCl-u9:-MYJGAWpCwWKi2Th4f-J:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L9)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

ok, I will check again. Thanks.
</blockquote></details>

Done.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AVJ77fCiqwAh1Wzt:-MYJGCouBwD5AnHrRmCx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L14)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

sure, thanks.
</blockquote></details>

Done.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AguF5GPM_M4JJMI7:-MYJGECt5bzCgj05k0bB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L30)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

ok, I will check. Thanks.
</blockquote></details>

Done.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2305#-MY9AnUM351PFVZ0BwUs:-MYJGEvR5OzpUvN8Jz-3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/903232125d2ec4a6e4d0f99c91279722dd4ad015/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L46)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

ok, I will remove. Thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-15 13:10 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKdg6D79-JbUQawy7R:-MYKdg6D79-JbUQawy7S:bpfzp6m) (no related file):*
TODO(myself): check this PR locally. Make sure everything works as expected.

---
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcL8s7chI4789gJJb:-MYKcL8s7chI4789gJJc:b-15ri7s) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L47)):*
> ```Dockerfile
> 
> # If user doesn't want to copy above files, then she can build the ra-tls-secret-prov sample locally
> # and copy the entire folder with executatbles
> ```

Typo: `executables`
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcQkG10Z9nnx42E3Y:-MYKcQkG10Z9nnx42E3Z:b-s8z8k3) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L47)):*
> ```Dockerfile
> 
> # If user doesn't want to copy above files, then she can build the ra-tls-secret-prov sample locally
> # and copy the entire folder with executatbles
> ```

`folder` -> `directory`
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcbQh4CMJs0tY_r2V:-MYKcbQh4CMJs0tY_r2W:b-poojaz) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L1)):*
> ```
> # Steps to create ra-tls-secret-prov gsc image:
> ```

`GSC image` (capital letters)
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKckw37gY3OY8ivyjp:-MYKckw37gY3OY8ivyjq:b-97uzao) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L8)):*
> ```
> # STEP 2: Create base ra-tls-secret-prov-image
> #         $ cd graphene
> #         $ docker build -t <my-base-ra-tls-secret-prov-image> -f ~/graphene/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile .
> ```

You are already under `graphene/` dir, no need for `~/graphene/`
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKdGJ20Fl6el1jkNpo:-MYKdGJ20Fl6el1jkNpp:b-sik844) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L8)):*
> ```
> # STEP 2: Create base ra-tls-secret-prov-image
> #         $ cd graphene
> #         $ docker build -t <my-base-ra-tls-secret-prov-image> -f ~/graphene/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile .
> ```

Can you change `<my-base-ra-tls-secret-prov-image>` to something shorter, e.g. `<base-secret-prov-img>`?
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcq8A6hZZAkf4CpyM:-MYKcq8A6hZZAkf4CpyN:bov68iy) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L13)):*
> ```
> #         $ cd graphene/Tools/gsc
> #         $ ./gsc build --insecure-args <my-base-ra-tls-secret-prov-image> test/ubuntu18.04-ra-tls-secret-prov.manifest
> #         $ ./gsc sign-image <my-base-ra-tls-secret-prov-image> ~/graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem
> ```

You are already under `graphene/` dir, no need for `~/graphene/` (instead, you need something like `../../Pal/src/ and so on`)
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKd6MiAwpscRLqp0Zc:-MYKd6MiAwpscRLqp0Zd:b-aiuq2n) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L21)):*
> ```
> #         $ RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 ./secret_prov_server_dcap &
> #
> # STEP 5: docker run --net=host --device=/dev/sgx/enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-<my-base-ra-tls-secret-prov-image>
> ```

Could you modify similar to other steps: first line contains a description, next lines start with `$ ` and contain the actual command.


<!-- Sent from Reviewable.io -->

2021-04-19 09:32 UTC, veenasai2 commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKdGJ20Fl6el1jkNpo:-MYLlzuOAym-hL4slA6v:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you change `<my-base-ra-tls-secret-prov-image>` to something shorter, e.g. `<base-secret-prov-img>`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-19 09:33 UTC, veenasai2 commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKd6MiAwpscRLqp0Zc:-MYLlxrC7qxfX0FCE-kb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you modify similar to other steps: first line contains a description, next lines start with `$ ` and contain the actual command.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-19 09:33 UTC, veenasai2 commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcq8A6hZZAkf4CpyM:-MYLlzR62i2woTq5wZ6S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You are already under `graphene/` dir, no need for `~/graphene/` (instead, you need something like `../../Pal/src/ and so on`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-19 09:33 UTC, veenasai2 commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKckw37gY3OY8ivyjp:-MYLm-OU3-TqK18wc8cE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You are already under `graphene/` dir, no need for `~/graphene/`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-19 09:33 UTC, veenasai2 commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcbQh4CMJs0tY_r2V:-MYLm01bEBo8g7WvTp95:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`GSC image` (capital letters)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-19 09:33 UTC, veenasai2 commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcL8s7chI4789gJJb:-MYLeChE-VQCAcZbdWJa:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `executables`
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-04-19 09:34 UTC, veenasai2 commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKcQkG10Z9nnx42E3Y:-MYLm19HD1ywUZ55OGxy:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/890a515443c967110af779e47b90c58fcc75b6ef/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`folder` -> `directory`
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-04-19 09:34 UTC, veenasai2 commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKdg6D79-JbUQawy7R:-MYdTlGHAWaeyZKbUBCr:b-wpb374) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): check this PR locally. Make sure everything works as expected.
</blockquote></details>

ok, thanks.

---


<!-- Sent from Reviewable.io -->

2021-04-19 18:03 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKdg6D79-JbUQawy7R:-MYOJPUaCAeUMf0LCNaW:bju67sc) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): check this PR locally. Make sure everything works as expected.
</blockquote></details>

To code looks good to me, but still blocking myself from approving (must check locally that this PR works).

---


<!-- Sent from Reviewable.io -->

2021-04-20 07:47 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKdg6D79-JbUQawy7R:-MYiAEyF6oAsmUBTCLEC:bguak7g) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To code looks good to me, but still blocking myself from approving (must check locally that this PR works).
</blockquote></details>

Ok, trying this on my local machine. Got some errors during STEP 2:

```
gcc src/secret_prov_server.c -O2 -Wall -std=c11 -Wmissing-prototypes -O2 -Wall -std=c11 -I../../Pal/src/host/Linux-SGX/tools/ra-tls -Wl,-rpath-link,./libs/ -L./libs/ -lmbedcrypto -lmbedtls -lmbedx509 -lsecret_prov_verify_epid -pthread -o secret_prov_server_epid
/usr/bin/ld: warning: libcurl-gnutls.so.4, needed by ./libs//libsgx_util.so, not found (try using -rpath or -rpath-link)
Makefile:92: recipe for target 'secret_prov_server_epid' failed
make: *** [secret_prov_server_epid] Error 1
```

Looks like a missing dependency.

UPDATE: I added `libcurl3-gnutls` to the list of Ubuntu packages in the Dockerfile, and it works now! Please add it (see also my comment below).

---
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYiEpQU2UkRXh7I1pFd:-MYiEpQU2UkRXh7I1pFe:bh5mzfy) ([raw file](https://github.com/oscarlab/graphene/blob/771337d6f5e3efc4cdd470dd072e6c265f11ac8a/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L6)):*
> ```Dockerfile
>     && env DEBIAN_FRONTEND=noninteractive apt-get install -y wget \
>     build-essential \
>     python3 \
> ```

Please add `libcurl3-gnutls`. This is needed when building the EPID-based secret provisioning service.


<!-- Sent from Reviewable.io -->

2021-04-20 08:41 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-04-20 08:41 UTC, dimakuv commented
Jenkins, test this please

2021-04-20 08:53 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYKdg6D79-JbUQawy7R:-MYiPNhy8_JP2iRDFY9G:bl08rit) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, trying this on my local machine. Got some errors during STEP 2:

```
gcc src/secret_prov_server.c -O2 -Wall -std=c11 -Wmissing-prototypes -O2 -Wall -std=c11 -I../../Pal/src/host/Linux-SGX/tools/ra-tls -Wl,-rpath-link,./libs/ -L./libs/ -lmbedcrypto -lmbedtls -lmbedx509 -lsecret_prov_verify_epid -pthread -o secret_prov_server_epid
/usr/bin/ld: warning: libcurl-gnutls.so.4, needed by ./libs//libsgx_util.so, not found (try using -rpath or -rpath-link)
Makefile:92: recipe for target 'secret_prov_server_epid' failed
make: *** [secret_prov_server_epid] Error 1
```

Looks like a missing dependency.

UPDATE: I added `libcurl3-gnutls` to the list of Ubuntu packages in the Dockerfile, and it works now! Please add it (see also my comment below).
</blockquote></details>

I added this dependency, but I did not face this error in my system. Thanks. 

---
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYiEpQU2UkRXh7I1pFd:-MYiTrxT8mxRWB_TJRKY:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/771337d6f5e3efc4cdd470dd072e6c265f11ac8a/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `libcurl3-gnutls`. This is needed when building the EPID-based secret provisioning service.
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-04-23 14:56 UTC, mkow requested changes
> Reviewed 1 of 4 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYz1vmn2h9xYrHf6S0P:-MYz1vmn2h9xYrHf6S0Q:b-dzyy4g) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L1)):*
> ```Dockerfile
> From ubuntu:18.04
> ```

`From` -> `FROM`
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 10 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYz3Y7FCFE2uaScVNHm:-MYz3Y7G9gosnLRv_cq8:b-5ce9nx) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L10)):*
> ```Dockerfile
>     gnupg2
> 
> # Installing dcap and epid specific libraries
> ```

`dcap` -> `DCAP-`
`epid specific` -> `EPID-specific`
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 13 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYz4DSj-meqHLETVOCm:-MYz4DSj-meqHLETVOCn:b5q4ata) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L13)):*
> ```Dockerfile
> 
> RUN echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' | \
>     tee /etc/apt/sources.list.d/intel-sgx.list > /dev/null \
> ```

Why use `tee` if you redirect to `/dev/null` afterwards? Why not just use `>`?
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzCCAN1es8ZTuSVw9A:-MYzCCAN1es8ZTuSVw9B:by223r7) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L37)):*
> ```Dockerfile
> 
> COPY Pal/src/host/Linux-SGX/tools/pf_crypt/pf_crypt /graphene/Pal/src/host/Linux-SGX/tools/pf_crypt/
> COPY Pal/src/host/Linux-SGX/tools/common/libsgx_util.so /graphene/Pal/src/host/Linux-SGX/tools/common/
> ```

Shouldn't these be copied by GSC itself? CC: @vahldiek
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 12 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzD5mw1lx5bRKpXXXA:-MYzD5mw1lx5bRKpXXXB:b9uslqr) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L12)):*
> ```
> --insecure-args
> ```

Is this example actually requiring custom args? If not, then please drop this switch, and if you need to keep it then please add a warning here that this is insecure and only for testing.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 19 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzD0YOAPTueqUnJgkI:-MYzD0YOAPTueqUnJgkJ:b4zkdhm) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L19)):*
> ```
> RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1
> ```

Please remove this, it's insecure (as the name says).
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest, line 23 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzCe_k7yeua_V0Oq9f:-MYzCe_k7yeua_V0Oq9g:bdp9ayy) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.manifest#L23)):*
> ```
> # STEP 5: Run the gsc-<base-secret-prov-img>-signed image created at STEP 3
> #         $ docker run --net=host --device=/dev/sgx/enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
> #           gsc-<base-secret-prov-img>
> ```

Please wrap this whole section to 100 chars


<!-- Sent from Reviewable.io -->

2021-04-23 17:00 UTC, vahldiek commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzCCAN1es8ZTuSVw9A:-MYzdf567033Mx2j1ArT:b6vowj8) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't these be copied by GSC itself? CC: @vahldiek
</blockquote></details>

Could be. Currently the focus is on the runtime and debug folders. We never started to implement the feature of remote attestation or protected files with GSC which would require these files.


<!-- Sent from Reviewable.io -->

2021-04-26 17:25 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzCCAN1es8ZTuSVw9A:-MZECOIe1Qx9onNzuq8o:b-n1wbld) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L37)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Could be. Currently the focus is on the runtime and debug folders. We never started to implement the feature of remote attestation or protected files with GSC which would require these files.
</blockquote></details>

Yeah, we probably could add a flag to GSC `-add-dcap-attestation`/`-add-epid-attestation` or something like this. However, this is currently fluid (there will be quite some changes to SGX attestation soon-ish).


<!-- Sent from Reviewable.io -->

2021-04-26 18:49 UTC, vahldiek commented
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzCCAN1es8ZTuSVw9A:-MZEVI5e2LxcFbvSi4VK:bp9mmlz) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, we probably could add a flag to GSC `-add-dcap-attestation`/`-add-epid-attestation` or something like this. However, this is currently fluid (there will be quite some changes to SGX attestation soon-ish).
</blockquote></details>

Not only that, you may want to use Graphene-independent attestation library provided by a third party like the pre-main from Marblerun. We could discuss if pf_crypt and sgx_util should always be available for GSC images, since they constitute a central role within the Graphene universe. (but I believe the ra-tls libraries should be separate and rather via ```-add-ld-preload```)


<!-- Sent from Reviewable.io -->

2021-04-26 23:14 UTC, mkow requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 13 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYz4DSj-meqHLETVOCm:-MZFS8XD0mGSA979srGs:b-d97xxf) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L13)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

tee will copy the download url to /etc/apt/sources.list.d/intel-sgx.list and at the same time it will display the url to stdout. If we redirect to /dev/null, then tee will copy the url to the file, but it won't display the url. These steps I copied from https://software.intel.com/content/www/cn/zh/develop/articles/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html . Thanks. 
</blockquote></details>

So, you effectively want to just write it to the file, not to display it? So, why not just use `>` instead of `tee`?


<!-- Sent from Reviewable.io -->

2021-04-27 03:49 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 13 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYz4DSj-meqHLETVOCm:-MZGREC_4cyreqsZfUUU:b-9ifcl9) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, you effectively want to just write it to the file, not to display it? So, why not just use `>` instead of `tee`?
</blockquote></details>

Sure, thanks. Done.
___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzCCAN1es8ZTuSVw9A:-MZGRJAR5RNYwb5tEa3h:b-qqdd45) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L37)):*
<details><summary><i>Previously, vahldiek (Anjo Vahldiek-Oberwagner) wrote…</i></summary><blockquote>

Not only that, you may want to use Graphene-independent attestation library provided by a third party like the pre-main from Marblerun. We could discuss if pf_crypt and sgx_util should always be available for GSC images, since they constitute a central role within the Graphene universe. (but I believe the ra-tls libraries should be separate and rather via ```-add-ld-preload```)
</blockquote></details>

Do I need to make some changes for this requirement as part of current PR?


<!-- Sent from Reviewable.io -->

2021-04-27 06:00 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2305#-MYzCCAN1es8ZTuSVw9A:-MZGuHAA1GI5hUakoDRr:b-gaw4ps) ([raw file](https://github.com/oscarlab/graphene/blob/8068c36b0fb9b9c3f0a9590c3910926f8bf4550b/Tools/gsc/test/ubuntu18.04-ra-tls-secret-prov.dockerfile#L37)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Do I need to make some changes for this requirement as part of current PR?
</blockquote></details>

No, you don't need to change your PR. We don't have these requirements for GSC crystallized, this discussion is just for future.


<!-- Sent from Reviewable.io -->

2021-04-27 14:08 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 4 files at r2, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-27 15:53 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MZJ1D4A9JSRFY2swwgk:-MZJ1D4A9JSRFY2swwgl:b-jshtpg) (no related file):*
FYI: I double-checked that after all fixups, the PR still works correctly. Everything is fine, can be merged.

---


<!-- Sent from Reviewable.io -->

2021-04-27 15:53 UTC, dimakuv commented
Jenkins, test this please

2021-04-27 16:20 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2305#-MZJ1D4A9JSRFY2swwgk:-MZJ7HeW-TRdnEDSNOek:b-10zg8a) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I double-checked that after all fixups, the PR still works correctly. Everything is fine, can be merged.
</blockquote></details>

Thank you. 

---


<!-- Sent from Reviewable.io -->

2021-04-27 17:56 UTC, dimakuv commented
Jenkins, test this please

2021-04-27 18:03 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-04-27 18:15 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2305)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-27 18:30 UTC, merged