[Pal,LibOS] Make the logging system always flush data
oscarlab/graphene pull request #2309
Opened 2021-04-13 11:26 UTC by pwmarcz

New version of #2304. Should fix test failures like this one for `send_handle` PAL test: https://leeroy.cs.unc.edu/job/graphene-sgx-18.04/5067/

This makes sure the behaviour of logging functions is consistent, but that they still output whole lines with a single syscall whenever possible.

The syscall trace (shim_parser.c), which depended on the buffering mechanism in LibOS, is converted to use its own buffer. As a result, we no longer need to keep a per-thread log buffer, just log prefix for a given thread.

2021-04-13 15:07 UTC, yamahata approved these changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-04-13 16:36 UTC, dimakuv requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/lib/stdlib/printfmt.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYB-GkYAFFFesxbKU6n:-MYB-GkYAFFFesxbKU6o:b-73m6vw) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/lib/stdlib/printfmt.c#L226)):*
> ```C
>                 break;
> 
>             // '%' at the end of string - just print the %
> ```

Nice catch!
___
*[Pal/lib/stdlib/printfmt.c, line 334 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYB0rZ-D74IEzFp_LQ2:-MYB0rZ-D74IEzFp_LQ3:bzeysjy) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/lib/stdlib/printfmt.c#L334)):*
> ```C
>             return ret;
>     }
>     assert(buf->pos < ARRAY_SIZE(buf->data));
> ```

Am I missing something? Nothing here or in `buf_flush()` resets `buf->pos`, so how can the code survive this assert?

Looks like we are just lucky that no messages from Graphene span more than 256 chars?


<!-- Sent from Reviewable.io -->

2021-04-13 16:59 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/lib/stdlib/printfmt.c, line 334 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYB0rZ-D74IEzFp_LQ2:-MYB9rb_0qs8c12kXtxm:b-1j9rij) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/lib/stdlib/printfmt.c#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Am I missing something? Nothing here or in `buf_flush()` resets `buf->pos`, so how can the code survive this assert?

Looks like we are just lucky that no messages from Graphene span more than 256 chars?
</blockquote></details>

Yes, I forgot to reset position in `buf->flush`.

I'll change the buffer size to something like 40 to check if it works.


<!-- Sent from Reviewable.io -->

2021-04-13 18:03 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: 19 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/lib/stdlib/printfmt.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYB-GkYAFFFesxbKU6n:-MYBOkdMBlysRYSoYFik:bodzn7i) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/lib/stdlib/printfmt.c#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nice catch!
</blockquote></details>

Yeah, all these `fmt--` and `fmt[-1]` looked pretty fishy...
___
*[Pal/lib/stdlib/printfmt.c, line 334 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYB0rZ-D74IEzFp_LQ2:-MYBOa4w1GFktA_W3aAS:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/lib/stdlib/printfmt.c#L334)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, I forgot to reset position in `buf->flush`.

I'll change the buffer size to something like 40 to check if it works.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-04-13 22:28 UTC, mkow requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: 19 of 21 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/shim_parser.c, line 1553 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYC2TM33xE9hTDaUFro:-MYC2TM33xE9hTDaUFrp:b-on8tb7) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/LibOS/shim/src/shim_parser.c#L1553)):*
> ```
> log_trace("%*s\n", (int)size, str);
> ```

I don't think this `*` works as you expect it to? See https://godbolt.org/z/c85vcMTPq.
___
*[LibOS/shim/src/utils/log.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYCHm2T99r9orV7V7QN:-MYCHm2T99r9orV7V7QO:b7mtuvk) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/LibOS/shim/src/utils/log.c#L46)):*
> ```C
>             /* internal LibOS thread: show Process ID, Internal-thread ID, and exec name */
>             snprintf(tcb->log_prefix, ARRAY_SIZE(tcb->log_prefix), "[P%u:i%u:%s] ", vmid,
>                       tcb->tp->tid - INTERNAL_TID_BASE, exec);
> ```

This line got misaligned
___
*[Pal/include/lib/api.h, line 250 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYCJS_O4aTLJ-9zy7Rj:-MYCJS_O4aTLJ-9zy7Rk:bjv65e5) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/include/lib/api.h#L250)):*
> ```objc
> /*
>  * Buffered printing. The print_buf structure holds PRINT_BUF_SIZE characters, and outputs them
>  * (using `write_all` callback) when `buf_flush()` is called, or when the buffer overflows.
> ```

IMO worth noting that a newline is added at `buf_flush()` and that `puts()` has different semantics than the standard `puts()` (no implicit newline)


<!-- Sent from Reviewable.io -->

2021-04-14 07:27 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-04-14 10:17 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: 18 of 21 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/shim_parser.c, line 1553 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYC2TM33xE9hTDaUFro:-MYEoHnxEeQXQu0b-zez:b8uegx7) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/LibOS/shim/src/shim_parser.c#L1553)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> log_trace("%*s\n", (int)size, str);
> ```

I don't think this `*` works as you expect it to? See https://godbolt.org/z/c85vcMTPq.
</blockquote></details>

I changed it to `.*`, that seems to do what I want.
___
*[LibOS/shim/src/utils/log.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYCHm2T99r9orV7V7QN:-MYEoeWG6YEdCDX119Ew:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/LibOS/shim/src/utils/log.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This line got misaligned
</blockquote></details>

Fixed.
___
*[Pal/include/lib/api.h, line 250 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYCJS_O4aTLJ-9zy7Rj:-MYEolKI6ZwZK-MNzIKV:b-j2sxxw) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/include/lib/api.h#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO worth noting that a newline is added at `buf_flush()` and that `puts()` has different semantics than the standard `puts()` (no implicit newline)
</blockquote></details>

I don't understand this comment. I don't add newlines anywhere in this API, and most of its users (the `_log` functions) don't either.

The only place where a newline is added is `shim_parser.c`, which does split long messages across multiple prefixed lines. I added an explanation there.


<!-- Sent from Reviewable.io -->

2021-04-14 11:03 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Pal/include/lib/api.h, line 250 at r1](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYCJS_O4aTLJ-9zy7Rj:-MYEvkNxE-hMpu90CMnV:b7hsau) ([raw file](https://github.com/oscarlab/graphene/blob/1914976302cd835d7e6921bc370808bcc60a516d/Pal/include/lib/api.h#L250)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't understand this comment. I don't add newlines anywhere in this API, and most of its users (the `_log` functions) don't either.

The only place where a newline is added is `shim_parser.c`, which does split long messages across multiple prefixed lines. I added an explanation there.
</blockquote></details>

Ah, right, it's a per-callback property.


<!-- Sent from Reviewable.io -->

2021-04-14 12:09 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-14 12:37 UTC, boryspoplawski requested changes
> Reviewed 13 of 21 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/utils/log.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYFMyj0BSlNogbArxOq:-MYFMyj15_BlUz2x3Utr:b-jmzdxl) ([raw file](https://github.com/oscarlab/graphene/blob/732505a761f4a6da942594fe847cd158e15503c7/LibOS/shim/src/utils/log.c#L63)):*
> ```C
> }
> 
> void _log(int level, const char* fmt, ...) {
> ```

Does this mean code like:
```
log_error("abc");
log_error("123\n");
```
print
```
[prefix] log_level: abc[prefix] log_level: 123
```
?
We have such patterns e.g. https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/bookkeep/shim_signal.c#L905


<!-- Sent from Reviewable.io -->

2021-04-14 12:49 UTC, boryspoplawski reviewed
> Reviewed 4 of 21 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-04-14 12:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: 21 of 27 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/utils/log.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYFMyj0BSlNogbArxOq:-MYFQYVg9faZ3Q1MoHLR:b-gs060y) ([raw file](https://github.com/oscarlab/graphene/blob/732505a761f4a6da942594fe847cd158e15503c7/LibOS/shim/src/utils/log.c#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Does this mean code like:
```
log_error("abc");
log_error("123\n");
```
print
```
[prefix] log_level: abc[prefix] log_level: 123
```
?
We have such patterns e.g. https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/bookkeep/shim_signal.c#L905
</blockquote></details>

Good catch, I thought `shim_parser` was the only place. I fixed that, and I grepped through LibOS for other log messages not ending with newline - I didn't find any other instances of "string building" pattern, but quite a few missing newlines that I also fixed.

By the way, what do you think about converting `log_*` to add implicit newline (+ @mkow @dimakuv)? I don't want to do it in this PR (since it requires changing every invocation), but looks like it makes sense.


<!-- Sent from Reviewable.io -->

2021-04-14 13:00 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/utils/log.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYFMyj0BSlNogbArxOq:-MYFSdfg1xQFTbgw3xFL:b-7ugp9a) ([raw file](https://github.com/oscarlab/graphene/blob/732505a761f4a6da942594fe847cd158e15503c7/LibOS/shim/src/utils/log.c#L63)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Good catch, I thought `shim_parser` was the only place. I fixed that, and I grepped through LibOS for other log messages not ending with newline - I didn't find any other instances of "string building" pattern, but quite a few missing newlines that I also fixed.

By the way, what do you think about converting `log_*` to add implicit newline (+ @mkow @dimakuv)? I don't want to do it in this PR (since it requires changing every invocation), but looks like it makes sense.
</blockquote></details>

I don't like this: this PR disallows for log messages without a newline, but it's not enforced anywhere in any way.
Do we want to disallow messages without newlines?


<!-- Sent from Reviewable.io -->

2021-04-14 13:03 UTC, mkow approved these changes
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/utils/log.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYFMyj0BSlNogbArxOq:-MYFT8sZ5swV05SZccVm:bqt2jaz) ([raw file](https://github.com/oscarlab/graphene/blob/732505a761f4a6da942594fe847cd158e15503c7/LibOS/shim/src/utils/log.c#L63)):*
> By the way, what do you think about converting `log_*` to add implicit newline (+ @mkow @dimakuv)? I don't want to do it in this PR (since it requires changing every invocation), but looks like it makes sense.

+1, I even wanted to do this myself but was blocked on shim_parser which relied on this string building. But now it sounds like a reasonable change.


<!-- Sent from Reviewable.io -->

2021-04-14 13:17 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/utils/log.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYFMyj0BSlNogbArxOq:-MYFWavx21As4DZPQnMt:b-awmb24) ([raw file](https://github.com/oscarlab/graphene/blob/732505a761f4a6da942594fe847cd158e15503c7/LibOS/shim/src/utils/log.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> By the way, what do you think about converting `log_*` to add implicit newline (+ @mkow @dimakuv)? I don't want to do it in this PR (since it requires changing every invocation), but looks like it makes sense.

+1, I even wanted to do this myself but was blocked on shim_parser which relied on this string building. But now it sounds like a reasonable change.
</blockquote></details>

Ok, so let's have this temporarily and explicitly add newlines in next PR


<!-- Sent from Reviewable.io -->

2021-04-14 16:53 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/utils/log.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYFMyj0BSlNogbArxOq:-MYGIFO-8vLXVeixSpq8:b-mwq92y) ([raw file](https://github.com/oscarlab/graphene/blob/732505a761f4a6da942594fe847cd158e15503c7/LibOS/shim/src/utils/log.c#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, so let's have this temporarily and explicitly add newlines in next PR
</blockquote></details>

I'm fine with this.


<!-- Sent from Reviewable.io -->

2021-04-14 17:46 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-14 18:05 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYGYaG34QwM1ek_pVTU:-MYGYaG48ccqeUV60FC6:b-4opy72) (no related file):*
@pwmarcz Interesting, seems it's still broken...

See https://leeroy.cs.unc.edu/job/graphene-sgx-18.04/5114/testReport/junit/test_pal/TC_23_SendHandle/test_000_send_handle/:

```
Send Handle OK
debug: sock_getopt (fd = 7, sockopt addr = 0x7ffc4e3f0400) is not implemented and always returns 0
warning: DkVirtualMemoryProtect is unimplemented in Linux-SGX PAL
Receive Handle OK
debug: sock_getopt (fd = 9, sockopt addr = 0x7ffd073908e0) is not implemented and always returns 0
Receive Pipe Handle: Hello World
debug: sock_getopt (fd = 7, sockopt addr = 0x7ffc4e3f0400) is not implemented and always returns 0
Send Handle OK
debug: Receive Handle OK
sock_getopt (fd = 7, sockopt addr = 0x7ffc4e3f0400) is not implemented and always returns 0
Receive Socket Handle: Hello World
Send Handle OK
Receive Handle OK
Receive File Handle: Hello World
```

Some of the output lines are prefixed and some aren't.

---


<!-- Sent from Reviewable.io -->

2021-04-14 18:36 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[LibOS/shim/src/utils/log.c, line 41 at r5](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYGeKI_5Uw6cZdLSmjJ:-MYGeKIaCHEsG-chFIay:bm1j2xq) ([raw file](https://github.com/oscarlab/graphene/blob/170c02b0789c12059b28fca51169668a114ae025/LibOS/shim/src/utils/log.c#L41)):*
> ```
> ARRAY_SIZE(tcb->log_prefix)
> ```

doesn't sizeof work?


<!-- Sent from Reviewable.io -->

2021-04-14 19:00 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYGYaG34QwM1ek_pVTU:-MYGkLLdC9SX-WX2ya2A:bvyp04s) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@pwmarcz Interesting, seems it's still broken...

See https://leeroy.cs.unc.edu/job/graphene-sgx-18.04/5114/testReport/junit/test_pal/TC_23_SendHandle/test_000_send_handle/:

```
Send Handle OK
debug: sock_getopt (fd = 7, sockopt addr = 0x7ffc4e3f0400) is not implemented and always returns 0
warning: DkVirtualMemoryProtect is unimplemented in Linux-SGX PAL
Receive Handle OK
debug: sock_getopt (fd = 9, sockopt addr = 0x7ffd073908e0) is not implemented and always returns 0
Receive Pipe Handle: Hello World
debug: sock_getopt (fd = 7, sockopt addr = 0x7ffc4e3f0400) is not implemented and always returns 0
Send Handle OK
debug: Receive Handle OK
sock_getopt (fd = 7, sockopt addr = 0x7ffc4e3f0400) is not implemented and always returns 0
Receive Socket Handle: Hello World
Send Handle OK
Receive Handle OK
Receive File Handle: Hello World
```

Some of the output lines are prefixed and some aren't.
</blockquote></details>

```
        urts_log_always("%s", log_level_to_prefix[level]);
        print_to_fd(g_urts_log_fd, fmt, ap);
```

---


<!-- Sent from Reviewable.io -->

2021-04-14 20:05 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: 26 of 27 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYGYaG34QwM1ek_pVTU:-MYGxutl0wvdHrLT43b0:b-y5uwm8) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

```
        urts_log_always("%s", log_level_to_prefix[level]);
        print_to_fd(g_urts_log_fd, fmt, ap);
```
</blockquote></details>

Right, I forgot about that one. Updated.

---
___
*[LibOS/shim/src/utils/log.c, line 41 at r5](https://reviewable.io/reviews/oscarlab/graphene/2309#-MYGeKI_5Uw6cZdLSmjJ:-MYGy93l4j2jij_2h77S:b-b6a84r) ([raw file](https://github.com/oscarlab/graphene/blob/170c02b0789c12059b28fca51169668a114ae025/LibOS/shim/src/utils/log.c#L41)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

> ```
> ARRAY_SIZE(tcb->log_prefix)
> ```

doesn't sizeof work?
</blockquote></details>

It would work, but only because `log_prefix` is an array, not pointer. Since it's declared elsewhere, I thought `ARRAY_SIZE` would be safer in case somebody changed it.


<!-- Sent from Reviewable.io -->

2021-04-14 22:52 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-04-14 23:00 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-14 23:15 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 6 of 6 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2309)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-14 23:23 UTC, merged