[LibOS] Reword IPC transport layer
oscarlab/graphene pull request #2313
Opened 2021-04-15 00:02 UTC by boryspoplawski

## Description of the changes 
This took so long I dont remember anymore. Please refer to the commit messages and the code :)
As always please point me which places need more comments, this time it definitely lacks some.

2021-04-15 00:28 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 0 of 29 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHr-P5DFwW-Qs5Haxs:-MYHr-P5DFwW-Qs5Haxt:b-sprwyx) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L72)):*
> ```C
> 
> static noreturn void ipc_leader_died_callback(void) {
>     // TODO maybe just ignore it? this triggers often if parent does wait+exit
> ```

If the ipc leader does:
```
wait(...);
exit(0);
```
then the child might see the parent (ipc leader) exiting in the window between the child sends child-death-notification and actually exits/kills ipc worker thread.

How bad of an idea would be to ignore IPC leader dying? I think it should work - if we need a leader, then an error will be spotted when trying to communicate with it.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 83 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHrWJt-J9hs52pvp3q:-MYHrWJt-J9hs52pvp3r:b-les1v5) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L83)):*
> ```C
>     ipc_child_disconnect_callback(conn->vmid);
> 
>     // TODO: ipc_disconnect_msg_with_ack_callback(conn->vmid);
> ```

We might have some msg_with_ack that are waiting for a response, which might never come since the remote disconnected.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 228 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHt7csAm56sYwzqI_i:-MYHt7csAm56sYwzqI_j:b-jnl4r0) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L228)):*
> ```C
> 
> static noreturn void ipc_worker_main(void) {
>     // TODO: maybe global array - but would require copying on conn delete
> ```

If we had a global array of connection (instead of a list) we wouldn't have to gather them all here in every loop iteration, but then deletion would be slower (but deletion should be rare).
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 294 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHuiDh6sRInf3jn41J:-MYHuiDh6sRInf3jn41K:bz51ey2) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L294)):*
> ```C
>         }
> 
>         int ret = DkStreamsWaitEvents(items_cnt, handles, events, ret_events, NO_TIMEOUT);
> ```

There is some weird behavior of this function (that I've not yet debugged) that causes a closed handle to report it's available for reading, although it's already closed - and the next read returns `0` as expected, causing spurious error messages in the log (about remote closing early).
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 333 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHuEE1DC4S4-qRoqh-:-MYHuEE1DC4S4-qRoqh0:b-k9yrq2) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L333)):*
> ```C
>             ret = read_exact(new_handle, &new_id, sizeof(new_id));
>             if (ret < 0) {
>                 // TODO: maybe just die here?
> ```

I don't think this case can happen legitimately.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 348 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHuSm1EwD_b39rrlYa:-MYHuSm1EwD_b39rrlYb:b-7mx259) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L348)):*
> ```C
>             conn = connections[i];
>             if (ret_events[i] & PAL_WAIT_READ) {
>                 // TODO: what to do on errors? die or just delete connection?
> ```

Currently they are ignored here, I'm not sure which path to take. I guess removing connection is the proper one?
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 371 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHvBjfE0OlLjykqrcg:-MYHvBjfE0OlLjykqrch:b68o7h9) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L371)):*
> ```C
>     log_setprefix(shim_get_tcb());
> 
>     // TODO; curently we have PAL provided stack = 64 pages
> ```

Default PAL provided stack is 64 pages. Is that enough for this worker thread? I think yes.


<!-- Sent from Reviewable.io -->

2021-04-15 01:28 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 0 of 29 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYI6cgn6lRtchQEHAK2:-MYI6cgn6lRtchQEHAK3:b-byg4hv) (no related file):*
TBH I don't like this approach of 2 separate sets of connections (incoming+outgoing) anymore. The alternative was to have only one set, but that really complicates the case of 2 processes connecting to each other at the same time (remember we want to have at most one connection between each pair) and probably has some other issues.
I'm not sure what to do now, stay with this weirdness (e.g. the connect back requests) or try rewriting this to the other version?

---


<!-- Sent from Reviewable.io -->

2021-04-15 05:18 UTC, yamahata requested changes
> Reviewed 27 of 29 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYI6cgn6lRtchQEHAK2:-MYIp9H0DNao8vgVH5zm:bq11jfm) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TBH I don't like this approach of 2 separate sets of connections (incoming+outgoing) anymore. The alternative was to have only one set, but that really complicates the case of 2 processes connecting to each other at the same time (remember we want to have at most one connection between each pair) and probably has some other issues.
I'm not sure what to do now, stay with this weirdness (e.g. the connect back requests) or try rewriting this to the other version?
</blockquote></details>

(I'm only thinking loudly and curious about what the complication of one set approach is.)

If simultaneous connection occurs with one set approach, two processes will have two connections (contrary to the naive assumption).
But does it harm?
Other than one extra connection on rare event(in wrost case, same to 2 separates sets of connections), I think of only avl node disambiguation, broadcast, closing connections on child death.
the process will use dedicated one of two connections to send message. callback on receiving message will be triggered properly.

---
___
*[LibOS/shim/src/shim_checkpoint.c, line 576 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYIsl94Cr8hsqIxVNRn:-MYIsl94Cr8hsqIxVNRo:bq3n9j2) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/shim_checkpoint.c#L576)):*
> ```
> 42
> ```

please introduce symbolic macro.
___
*[LibOS/shim/src/shim_init.c, line 469 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYIswQ84KeoBXKGfRTd:-MYIswQ99Uc_ksbpCB9u:b-m9k3ec) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/shim_init.c#L469)):*
> ```
> 42
> ```

symbolic value please.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 112 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYIvF_QBVWeRIW5GfcJ:-MYIvF_QBVWeRIW5GfcK:bp5640z) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L112)):*
> ```C
>             BUG();
>         }
>         ret = DkStreamOpen(uri, 0, 0, 0, 0, &conn->handle);
> ```

This is connect system call on named pipe. So it's blocking operation.
the use of spinlock is suspicous.
Or unlock, DkStreamOpen, lock and recheck is needed.


<!-- Sent from Reviewable.io -->

2021-04-15 08:44 UTC, dimakuv requested changes
> Reviewed 27 of 29 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 70 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYI6cgn6lRtchQEHAK2:-MYJgXEI30dy0Mq833r4:bjv1wbn) (no related file):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

(I'm only thinking loudly and curious about what the complication of one set approach is.)

If simultaneous connection occurs with one set approach, two processes will have two connections (contrary to the naive assumption).
But does it harm?
Other than one extra connection on rare event(in wrost case, same to 2 separates sets of connections), I think of only avl node disambiguation, broadcast, closing connections on child death.
the process will use dedicated one of two connections to send message. callback on receiving message will be triggered properly.
</blockquote></details>

I don't know, I like this two-set approach. I only recommend to rename your two `shim_ipc_connection` structs to `shim_ipc_incoming_conn` and `shim_ipc_outgoing_conn` and add a small comment that the former is handled solely by the IPC worker thread (and no locks/refcounts are needed) and the latter -- by the normal app threads.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJgqbi948K46NNoxEp:-MYJgqbi948K46NNoxEq:b-wrwe83) (no related file):*
Impressive PR!

---
___
*[LibOS/shim/include/shim_handle.h, line 356 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJBHMZBlq-QLX36PfU:-MYJBHMZBlq-QLX36PfV:bae35k8) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_handle.h#L356)):*
> ```objc
>     int flags; /* Linux' O_* flags */
>     int acc_mode;
>     IDTYPE owner;
> ```

Seems like this was never used? The actual tracking of ownership seems to be encapsulated in the `ipc_ranges` metadata.
___
*[LibOS/shim/include/shim_ipc.h, line 32 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJBb704BQTrc5sZ3q0:-MYJBb704BQTrc5sZ3q1:bv6w5g8) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L32)):*
> ```objc
>     IPC_MSG_RESP = 0,
>     IPC_MSG_CONNBACK,
>     IPC_MSG_DUMMY,
> ```

Could we have brief comments on these types? I'd prefer to have them on all types, but you can only add comments at least on the two new ones.
___
*[LibOS/shim/include/shim_ipc.h, line 63 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJBsNN8eV_H0Md9z0g:-MYJBsNN8eV_H0Md9z0h:b-jwojst) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_ipc.h#L63)):*
> ```objc
> struct shim_ipc_cp_data {
>     IDTYPE parent_vmid;
>     IDTYPE ns_vmid;
> ```

No more `ns`, thank god! I hated this name.
___
*[LibOS/shim/include/shim_ipc.h, line 64 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJI4Ay4lUXaXOthjj-:-MYJI4Ay4lUXaXOthjj0:b-10qy6b) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L64)):*
> ```objc
> struct shim_ipc_ids {
>     IDTYPE parent_id;
>     IDTYPE leader_id;
> ```

Sometimes you use `id`, and sometimes `vmid`. I would prefer to have `vmid` everywhere, otherwise it's confusing.
___
*[LibOS/shim/include/shim_ipc.h, line 89 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJCFHB6iHEXbDGCqKW:-MYJCFHB6iHEXbDGCqKX:b-re9qel) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L89)):*
> ```objc
> 
> /* common functions for pid & sysv namespaces */
> int add_ipc_subrange(IDTYPE idx, IDTYPE owner);
> ```

When we have `owner` in these functions, does this actual mean "VMID of the owner process"?

If yes, maybe rename to a more concrete `owner_vmid`?
___
*[LibOS/shim/include/shim_ipc.h, line 125 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJCzgb-pJg6FNSDPgj:-MYJCzgb-pJg6FNSDPgk:bpuzwbv) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L125)):*
> ```objc
> int ipc_cld_exit_send(unsigned int exitcode, unsigned int term_signal);
> int ipc_cld_exit_callback(struct shim_ipc_msg* msg, IDTYPE src);
> void ipc_child_disconnect_callback(IDTYPE vmid);
> ```

We have mismatches in these namings. I would prefer to change:
- `cld` -> `child`
- `vmid` -> `src`

Alternatively, you could make longer names everywhere: `src` -> `src_vmid`, `dst` -> `dst_vmid`, but this seems like an overkill.
___
*[LibOS/shim/include/shim_ipc.h, line 158 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJDkTi2I9GH84j2kiY:-MYJDkTi2I9GH84j2kiZ:b-upjigv) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_ipc.h#L158)):*
> ```objc
> } __attribute__((packed));
> 
> int ipc_offer_send(struct shim_ipc_port* port, IDTYPE dest, IDTYPE base, IDTYPE size,
> ```

Stupid question: why did we previously need `port` if we could already find the port via `dest`? Is it because there could be several open ports on one `dest`, so there was a need to have an explicit concrete `port`?
___
*[LibOS/shim/include/shim_ipc.h, line 328 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJEI6lEjCAJlgLY6af:-MYJEI6lEjCAJlgLY6ag:b-h3fuwt) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L328)):*
> ```objc
>                              void (*callback)(struct shim_ipc_msg_with_ack*, void*), void* data);
> 
> void wake_req_msg_thread(struct shim_ipc_msg_with_ack* req_msg, void* data);
> ```

Can you add a short comment on why `data` and `seq` are needed in these two functions?
___
*[LibOS/shim/include/shim_ipc.h, line 331 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJERCu2P9a7VoGARTk:-MYJERCu2P9a7VoGARTl:b-xrovzq) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L331)):*
> ```objc
> 
> int connect_to_process(IDTYPE dest);
> int request_leader_connect_back(void);
> ```

Need some comment what this function is.
___
*[LibOS/shim/include/shim_ipc.h, line 332 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJETnj8jGM6LYeLp2e:-MYJETnj8jGM6LYeLp2f:bxsv65r) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L332)):*
> ```objc
> int connect_to_process(IDTYPE dest);
> int request_leader_connect_back(void);
> int ipc_dummy_callback(struct shim_ipc_msg* msg, IDTYPE src);
> ```

Need some comment what this dummy callback is.
___
*[LibOS/shim/include/shim_ipc.h, line 333 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJEYUI1QiEYGSgTpOG:-MYJEYUI1QiEYGSgTpOH:bgg1jdp) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L333)):*
> ```objc
> int request_leader_connect_back(void);
> int ipc_dummy_callback(struct shim_ipc_msg* msg, IDTYPE src);
> int broadcast_ipc(struct shim_ipc_msg* msg, IDTYPE exclude_id);
> ```

`exclude_id` -> `exclude_vmid`
___
*[LibOS/shim/include/shim_ipc.h, line 336 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJEeY03IqAFn6ex1LS:-MYJEeY03IqAFn6ex1LT:bey6yty) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L336)):*
> ```objc
> int send_ipc_message(struct shim_ipc_msg* msg, I [...]

2021-04-15 10:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 71 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYK0ynPEQI2GFg6MZ5g:b71yupw) (no related file):*
- Ordering guarantees: In my code, I assume that if I send several messages to the same recipient (from the same thread), then the recipient processes them in the same order (in its IPC helper thread). Is that still valid?
- Can I now connect/send message to myself? I didn't see any custom handling of such connections, but also no assertion against it. (From what I understand, just opening a pipe to myself would _mostly_ work, but can technically cause a deadlock on IPC worker sending too many messages to itself. So that would mean I can already continue work on my branch, since that stuff is experimental anyway).
- It would be nice to have a short introduction to IPC, maybe in a comment on top of `shim_ipc.h`. Things like:
  - general architecture (pipes, worker thread)
  - maybe the above ordering guarantees
  - role of IPC leader?
  - example usage (sending a message / message with ack)?

---
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHr-P5DFwW-Qs5Haxs:-MYK4Mu0BmVY_oA7iG32:b7k3at8) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L72)):*
>I think @pwmarcz has the same assumption on his FS-sync work: panic only when failed to explicitly communicate with the leader.

That's right, but I should mention that FS-sync flushes data on process exit (which requires IPC between the exiting process and the leader). But it sounds like that could happen before we send the child death notification?


<!-- Sent from Reviewable.io -->

2021-04-15 15:33 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 71 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYI6cgn6lRtchQEHAK2:-MYL7dFA9DUJAhu8xrBW:btzsyiq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't know, I like this two-set approach. I only recommend to rename your two `shim_ipc_connection` structs to `shim_ipc_incoming_conn` and `shim_ipc_outgoing_conn` and add a small comment that the former is handled solely by the IPC worker thread (and no locks/refcounts are needed) and the latter -- by the normal app threads.
</blockquote></details>

Supplement: I'm _not_ against two-set approach. 

---


<!-- Sent from Reviewable.io -->

2021-04-15 22:10 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 65 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYI6cgn6lRtchQEHAK2:-MYKdyg12CoTA6jh2Vkf:b-mttwz3) (no related file):*
> If simultaneous connection occurs with one set approach, two processes will have two connections (contrary to the naive assumption).

@yamahata The problem is we sometimes want to detect a disconnect and trigger a callback - in such case we could see a disconnect of one conenction, while the other still has some unread messages. This proved to be problematic e.g. in child death detection (in the old code).
We can solve that issue by having a set of pending connections and e.g. not accepting a new connection if we have one pending for the same recipient, but only in one of the processes (e.g. the one with lower id).
(I guess that's what you proposed)

> rename your two shim_ipc_connection structs to shim_ipc_incoming_conn and shim_ipc_outgoing_conn

You think such naming will be better? They are a bit longer and both are actually internal interfaces (each specific to one file only).
> add a small comment 

Sure, will do

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYKm2l-1nVp8dIfAG4Q:bhwdg4j) (no related file):*
>  I assume that if I send several messages to the same recipient (from the same thread), then the recipient processes them in the same order (in its IPC helper thread). Is that still valid?

This is **now** valid, but was not before. In the old code there could be multiple connections between a pair of processes and if you sent 2 messages each on a different connection, the order could be reversed. Now we have only one connection per pair and the order is always preserved.
> Can I now connect/send message to myself? I didn't see any custom handling of such connections, but also no assertion against it. (From what I understand, just opening a pipe to myself would mostly work, but can technically cause a deadlock on IPC worker sending too many messages to itself. So that would mean I can already continue work on my branch, since that stuff is experimental anyway).

In theory yes, but I did not consider that when rewriting the message_with_ack thingies, so there might be some deadlocks there.
Why can't you do, like the rest of the code:
```
if (Im_ipc_leader) {
    return some_ipc_callback();
}

return send_ipc_msg_to_leader(msg_causing_some_ipc_callback);
```

> It would be nice to have a short introduction to IPC, maybe in a comment on top of shim_ipc.h.

Yeah, this PR definitely lacks a general description, will try to add something.
> general architecture (pipes, worker thread)

Worker thread - yes, that should be documented; pipes - imo that's implementation details that rest of the code does not neet to be aware of.
> maybe the above ordering guarantees

+1
> role of IPC leader

Yes, this needs to be summarized, but in this PR I did not change anything related to that...
> example usage (sending a message / message with ack)

I think this still needs to be changed/reworked/cleanedup. I did not touch that part in this PR (except for where I had to).

---
___
*[LibOS/shim/include/shim_handle.h, line 356 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJBHMZBlq-QLX36PfU:-MYKoizb6362RxpRJy30:b6cjjys) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_handle.h#L356)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Seems like this was never used? The actual tracking of ownership seems to be encapsulated in the `ipc_ranges` metadata.
</blockquote></details>

Yes, this was never used
___
*[LibOS/shim/include/shim_ipc.h, line 32 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJBb704BQTrc5sZ3q0:-MYKoprFAZxheym44HUD:bw6d9sa) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we have brief comments on these types? I'd prefer to have them on all types, but you can only add comments at least on the two new ones.
</blockquote></details>

I did not investigate the semantics of all types here, so I would rather not describe all of them atm. Besides, I think we should rewrite the IPC data layer (messages format etc) too.
Commented on the new ones.
___
*[LibOS/shim/include/shim_ipc.h, line 64 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJI4Ay4lUXaXOthjj-:-MYKqgveDXRDvQZCuv20:b-icp9d) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sometimes you use `id`, and sometimes `vmid`. I would prefer to have `vmid` everywhere, otherwise it's confusing.
</blockquote></details>

I had a plan to rename `vmid`, but not in this PR and I'm not yet sure about the new nam.
I can temporarily make this `parent_vmid`, to be consistent.
Proposed new names:
- `process_id`
- `graphene_id`
- `gprocess_id`
- `gpid`

This would also include introducing new type (e.g. `process_id_t`). What do you think?
Update: maybe it should be done in this PR, as there are a lot of inconsistencies.
___
*[LibOS/shim/include/shim_ipc.h, line 158 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJDkTi2I9GH84j2kiY:-MYKsEvk5pJ6msMRY3EZ:b5gm2m5) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_ipc.h#L158)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Stupid question: why did we previously need `port` if we could already find the port via `dest`? Is it because there could be several open ports on one `dest`, so there was a need to have an explicit concrete `port`?
</blockquote></details>

You are asking wrong person ;)
I suspect your explanation is correct - we could have multiple ports per one `dest`. Besides old code did not offer a way to send a message to `dest` only to a `port` (so it created a new `port` if it did not have a reference to one).
___
*[LibOS/shim/include/shim_ipc.h, line 374 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJF6mO5n7EL5sG6iGy:-MYL12143tXm0BCgW3Mi:b-7ly2rl) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_ipc.h#L374)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you also supply a quick PR to fix the name of the `async helper thread`? Otherwise we'll have inconsistency in names, which will be very confusing to people.
</blockquote></details>

I would like to rewrite the async helper, so that it's cleaner, so wait for the thread termination and possibly move some code to some abstraction layer to share with ipc worker thread (if there is anything to be shared).
But that probably not a high priority task, so I'm not sure when it will happen. Do you want me to do just the rename for now?
___
*[LibOS/shim/src/shim_checkpoint.c, line 504 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJFQjmEjTb6S0XZXmu:-MYL1pie31AfYwlHmUlf:b-ojps5p) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/shim_checkpoint.c#L504)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are we sure there cannot be a legit vmid of `0 [...]

2021-04-16 08:04 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYI6cgn6lRtchQEHAK2:-MYO_NM6D67Wh2GrISRL:b-ejoler) (no related file):*
> You think such naming will be better? They are a bit longer and both are actually internal interfaces (each specific to one file only).

Ok, fair enough. It was confusing to see two identical names in this PR, used for two different things. But I agree that this is internal details, so unblocking.

---
___
*[LibOS/shim/include/shim_ipc.h, line 64 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJI4Ay4lUXaXOthjj-:-MYObgIsCHYV7L_5tY5o:b-j3z3ah) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I had a plan to rename `vmid`, but not in this PR and I'm not yet sure about the new nam.
I can temporarily make this `parent_vmid`, to be consistent.
Proposed new names:
- `process_id`
- `graphene_id`
- `gprocess_id`
- `gpid`

This would also include introducing new type (e.g. `process_id_t`). What do you think?
Update: maybe it should be done in this PR, as there are a lot of inconsistencies.
</blockquote></details>

I like your new names. And a new type. But then let's do it in a follow-up PR (this will be a trivial change that will be quickly merged). For now, we can live with these inconsistencies.
___
*[LibOS/shim/include/shim_ipc.h, line 336 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJEeY03IqAFn6ex1LS:-MYOc-DP7Na_HciyzSj1:b-xz529b) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L336)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `seq`? Since we have only one connection per pair of processes, and we use TCP/IP (and also TLS in case of SGX enclaves), why do we care about sequence numbers (the way I understand what `seq` is)?
</blockquote></details>

This was written before I looked at the code that uses it. Since this is out of scope of this PR, I'm unblocking this.
___
*[LibOS/shim/include/shim_ipc.h, line 374 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJF6mO5n7EL5sG6iGy:-MYOc83Y4aGLvrdiGZ9d:b-ibtie1) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_ipc.h#L374)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would like to rewrite the async helper, so that it's cleaner, so wait for the thread termination and possibly move some code to some abstraction layer to share with ipc worker thread (if there is anything to be shared).
But that probably not a high priority task, so I'm not sure when it will happen. Do you want me to do just the rename for now?
</blockquote></details>

Yes, you can just do a rename now. Actually, in a separate PR (no need to bundle in this PR). This will be a trivial change (just renames), so that PR will be approved quickly.
___
*[LibOS/shim/src/shim_checkpoint.c, line 571 at r4](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYOcLaJCFjjtMr8hgC5:-MYOcLaJCFjjtMr8hgC6:bqsjz5e) ([raw file](https://github.com/oscarlab/graphene/blob/2c49d8b269c0333ba9e6e5b7f389796ce6d66697/LibOS/shim/src/shim_checkpoint.c#L571)):*
> ```C
> 
>     /* Child creation was successful, now we add it to the children list. Child process should have
>      * already conencted to us, but is waiting for an acknowledgement, so it will not send any IPC
> ```

`connected`
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJJQGgEkNGS_5vuxwH:-MYOd4tZEkDIti_vPE81:bcfuzn3) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/src/ipc/shim_ipc.c#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Imo they just state the obvious. As far as it would be nice to have some top-level comment/description, it should actually be meaningful...
Added a one sentence, let me know what kind of information would you like to have here.
</blockquote></details>

OK, this comment is very good.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJK9MPEgveYsWaglmh:-MYOdI2IDRQY1hcHDc7H:b-3nngyg) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Forgot to add a reveiwable comment here.
That was something to consider. If we expect very low number of connections (which I think we do) maybe a simple list will be better? Linear search, but if the N=4 that might be faster than tree/hashmap. But otoh do we care?
</blockquote></details>

I mean, I'm pretty sure we don't care. Anything would do here. So I don't see a point in this TODO -- this is extremely low-priority. I suggest to just remove this.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJKwcL6jh5oV1LFexD:-MYOdZLjCcnB9k3WkfPp:b-s7j5e0) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L79)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If the connection is still in AVL tree, then `ref_count >= 1` (because the reference in the tree is counted).
There is no `is_in_tree` function (and it's intentionally, so that nobody does some weird flows where they check if something is in tree explicitly - it should always follow from the code flow).
</blockquote></details>

OK, thanks, I forgot (or didn't know) this about your AVL tree implementation.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 96 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJLXKx8qW8Q7Fv4z6r:-MYOdjPs4ehHtP1ttpRy:b-o7va3v) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L96)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is that a question or a statement? :)
I don't think it would be cleaner. In the current version we have the common case (of `conn` being non-NULL`) not repeated. Otoh I dont mind either version, so let me know which one you prefer (the one you proposed, I guess?).
</blockquote></details>

OK, just a matter of taste. No need to change anything.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 112 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYIvF_QBVWeRIW5GfcJ:-MYOdySUBLZeJNQ60giK:b-krkhsj) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L112)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, it's a blocking operation (at least I think so). The idea is that connection to another process is a very rare operation and 2 happening at the same time is even more unlikely.
>  the use of spinlock is suspicous

These are not necessary spinlocks. Anyway we cannot unlock here - this is to make sure we only have one connection per pair of processes.

I think we need two types of general purpose locks: for small and big/blocking critical sections. For the small case we could use spinloc [...]

2021-04-16 11:21 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYPFTLxC19gpVLXjMwg:bey1m70) (no related file):*
>This is now valid, but was not before. In the old code there could be multiple connections between a pair of processes and if you sent 2 messages each on a different connection, the order could be reversed. Now we have only one connection per pair and the order is always preserved.

Ouch. I'm glad that code is gone, then.

>In theory yes, but I did not consider that when rewriting the message_with_ack thingies, so there might be some deadlocks there.

I'll try it out then. I'm not using message_with_ack.

> Why can't you do, like the rest of the code: (...)

Because it behaves differently - unlike sending message, `some_ipc_callback()` returns after processing the message, not before. And if `some_ipc_callback()` is supposed to, in turn, send another message back, I get 2 layers of nested calls. To give a specific example from my code: [here](https://github.com/oscarlab/graphene/blob/9e3e53e447cc2d62578f0e66e55b3b1d6c28073b/LibOS/shim/src/sync/shim_sync_server.c#L160) the flow can possibly be like so (assuming client and server are both on the IPC leader):
```
(client) send_request_upgrade()
  (server) do_request_uprade()
    (server) send_confirm_upgrade()
      (client) do_confirm_upgrade()
```

The client code calling `send_request_upgrade()` has to assume that the response will sometimes be handled later, and sometimes _before_ `send_request_downgrade()` returns, with implications for locking, state updates etc., and with no way to determine that before call (because sometimes `send_confirm_upgrade()` will be triggered later).

Furthermore, the _server_ code calling `send_confirm_downgrade` will sometimes be blocked on the client handling the code. And I don't think _more_ nesting is possible, the client shouldn't ever try to call server back in such a scenario, but it's still an annoying limitation to think about, if it ever becomes necessary.

If we make sure that "send a message from/to leader" simply works in _all_ cases, the above problems do not appear and we have a relatively simple client-server protocol with "request / confirm" messages. So, I think the potential performance gain in one "happy case" is not worth complicating it.

---

And actually, now that I think of it, this might be solved by expanding "message with ack" to "message with arbitrary response". The server might then immediately respond, either with "request granted, here's the data" or with "I will call you later". But still it would be more of a performance improvement at the cost of complicating the code, so I don't want to be forced to implement it this way from the start.

---


<!-- Sent from Reviewable.io -->

2021-04-16 11:52 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYPUbZN4aQMw390CfEH:b-o8sfnv) (no related file):*
To be honest, I do not understand that example and why it cannot be done in the calling thread. Are you saying that the thread needs to wait for `do_confirm_upgrade`? That doesn't sound like a problem, if these are all called in the same thread. Or that the there is no internal locking inside server states (e.g. because it assumes that it's run in one thread)? That might be an issue indeed...
> the server code calling send_confirm_downgrade will sometimes be blocked on the client handling the code.

If you call that function directly from the thread it should block as well. Is that a problem, wouldn't it block anyway while waiting for response?

> this might be solved by expanding "message with ack" to "message with arbitrary response".

Afaik "messages with ack" are exactly this. You need to send a response manually with the correct ack number and the response could be any message (i.e. it can have a body).
> want to be forced to implement it this way from the start.

Sure don't, just saying for the future.

---


<!-- Sent from Reviewable.io -->

2021-04-16 12:03 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYPXmmGAUZkYU_qX2Hh:bm9otpy) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

To be honest, I do not understand that example and why it cannot be done in the calling thread. Are you saying that the thread needs to wait for `do_confirm_upgrade`? That doesn't sound like a problem, if these are all called in the same thread. Or that the there is no internal locking inside server states (e.g. because it assumes that it's run in one thread)? That might be an issue indeed...
> the server code calling send_confirm_downgrade will sometimes be blocked on the client handling the code.

If you call that function directly from the thread it should block as well. Is that a problem, wouldn't it block anyway while waiting for response?

> this might be solved by expanding "message with ack" to "message with arbitrary response".

Afaik "messages with ack" are exactly this. You need to send a response manually with the correct ack number and the response could be any message (i.e. it can have a body).
> want to be forced to implement it this way from the start.

Sure don't, just saying for the future.
</blockquote></details>

The main problem with making `senc_ipc_message` handle sending to the same process is that:
a) connection needs to be established - one thread cannot both connect and accept - so if the first message comes from IPC worker thread we get a deadlock,
b) sending the message might briefly block, e.g. when the underlying kernel buffer is full. If we block in the IPC worker thread then it won't ever empty that buffer - deadlock.
The two above are a problem, because IPC worker thread sometimes needs to send a response to a message - that's why I mentioned "messages with ack" before, but in theory any callback could send any message (not necessarily "msg_with_ack"). And judging from your example that's what you want - send messages as response to other messages. I don't think this can be handled in one thread (ipc worker).

---


<!-- Sent from Reviewable.io -->

2021-04-16 12:53 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYPXBqI6NtiPGO_xe23:bho2mww) (no related file):*
>Are you saying that the thread needs to wait for `do_confirm_upgrade`? That doesn't sound like a problem, if these are all called in the same thread.

The client thread does need to wait for `do_confirm_upgrade`. I guess the situation I described does work, as long as I release my lock _before_ messaging the server (so I'll probably have to copy the data I'm sending). And the responses will still be handled in correct order, thanks to the server having a lock.

So, that covers situations like `client -> server -> client`. The other direction (`server -> client -> server`) is more tricky, because there is also a server lock, and the response for client _does_ potentially trigger further messages. I could release the server lock before sending the outgoing messages, but then I can't guarantee the order of outgoing messages from multiple server callbacks...

Overall, it sounds like a lot of special cases, and again, all of this should not be a problem if there is a working, reliable, asynchronous "send message" primitive, whether it internally uses an inter-process pipe, in-process queue, or whatever else. I could just take a lock, send my messages, release lock, and have a much easier time reasoning about what happens in my critical section.

>If you call that function directly from the thread it should block as well. Is that a problem, wouldn't it block anyway while waiting for response?

`send_ipc_message` will write message to the pipe, but not wait for it to be handled, or for response. And that's what I want, the server does not ever to wait for a response: for server code, that would be generally a bad idea, since it needs to handle other messages in the meantime, possibly related to the same resource.

>Afaik "messages with ack" are exactly this. You need to send a response manually with the correct ack number and the response could be any message (i.e. it can have a body).

Yes, I think that's how it works right now. But it would be nice to have a "send message and wait for a response" as an available operation. Like an RPC call.

>And judging from your example that's what you want - send messages as response to other messages. I don't think this can be handled in one thread (ipc worker).

This is already a problem, right? Since the IPC worker sends acks, and there could be a deadlock between two processes sending acks to each other. Maybe that means outgoing messages should be queued, so that sending doesn't ever block on a full buffer?

---


<!-- Sent from Reviewable.io -->

2021-04-16 13:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYPn1nmE41umKWUVAht:bbnsh7r) (no related file):*
Since you have locking in server, I still do not understand. The client always needs to wait for a response from server, right?
Generally speaking: why something (whatever that is, that the callbacks for client messages do) can be done inside IPC worker, but not inside the calling thread itself? If you have proper locking schemes (I believe you said you do) it should be no difference, is there?
From what I understood this is the hard case:
```
A               S               B
|  up_req ->    |
                |
                |  down_req ->  |
                                |
                                |
                | <- down_conf  |
                |
                |
                |
|  <- up_conf   |
```
If thread A would be the same as S (server) then it could do the first part `up_req` + `down_req` directly and then sleep awaiting for the 2nd part to come asynchronously (handled by IPC worker this time).

> Yes, I think that's how it works right now. But it would be nice to have a "send message and wait for a response" as an available operation. Like an RPC call.

But that's what `send_msg_with_asck` do!

> This is already a problem, right? Since the IPC worker sends acks, and there could be a deadlock between two processes sending acks to each other. Maybe that means outgoing messages should be queued, so that sending doesn't ever block on a full buffer?

No, because IPC worker thread never awaits for ack messages, it just handles them. If it needs to send a message it does send a normal one (without confirmation).

---


<!-- Sent from Reviewable.io -->

2021-04-16 14:41 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYPw1kD1XZJac_Cpv3y:bqiw0pt) (no related file):*
>If thread A would be the same as S (server) then it could do the first part up_req + down_req directly and then sleep awaiting for the 2nd part to come asynchronously (handled by IPC worker this time).

That sounds fine. Generally, I'm not worried about cases where a thread needs to sleep and wait. I'm worried about the ones where the other side messages me synchronously. For example (sorry, I'm sure it can be made simpler, but I hope it makes the problem clear):

```
A               S              B            C
.               | <-------------- up_req    |
.               | down_req ->  |            .
|  <- down_req  |              |            .
|  down_conf -> |              |            .
.               | <- down_conf |            . 
.               | up_conf --------------->  |    
```

Assume A and S are the same process. Now, what I _would like_ to have, is:

1. S receives `up_req`from C, and then sends `down_req` to A and B
2. At a later time, S receives `down_conf` from A
3. At a later time, S receives `down_conf` from B, and then sends `up_conf` to C

All of the above 3 steps are separate invocations of a server handler, from the IPC worker main loop. The server functions as a nice state machine: lock, handle the incoming message, send resulting outgoing messages, unlock.

However, if "sending" `down_req` to A is actually a function call, and A "responds" immediately to S by issuing another function call, then I have the server handler running, nested, inside the same server handler. Which breaks my design: I cannot just take a lock in the server handler, and assume that my server handler invocations happen one after another.

And probably I can special-case that, but it looks like my code has to handle both "what if I'm calling the other side locally" and "what if I am being called by the other side locally"? This really should be the responsibility of the transport layer, not the code built on top of it.

>But that's what send_msg_with_asck do!

Yes, `send_msg_with_ack` is like an RPC call _that returns a single int_. I would need it to return arbitrary data. I believe this would be useful for the sync engine, although I'm not sure if it would fully solve the above problem of local messages. So maybe it's not so important right now.

>No, because IPC worker thread never awaits for ack messages, it just handles them. If it needs to send a message it does send a normal one (without confirmation).

I'm referring to this part:

```
        if (msg->code < ARRAY_SIZE(ipc_callbacks) && ipc_callbacks[msg->code]) {
            int ret = ipc_callbacks[msg->code](msg, conn->vmid);
            if ((ret < 0 || ret == RESPONSE_CALLBACK) && msg->seq) {
                ret = send_ipc_response(conn->vmid, ret, msg->seq);
```

AFAICT, this runs inside the IPC worker main loop. And `send_ipc_response` writes to a pipe. And the other end of that pipe is handled by another IPC worker. So if two IPC workers send responses to each other simultaneously, it's possible (although unlikely) that both these writes (to their respective pipes) could be blocked on full kernel buffers, causing a deadlock. Is that reasoning correct, or am I making a wrong assumption somewhere?

---


<!-- Sent from Reviewable.io -->

2021-04-16 15:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 64 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJI4Ay4lUXaXOthjj-:-MYQ0NRQ1Q32opQFvXAT:b-ic3kio) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like your new names. And a new type. But then let's do it in a follow-up PR (this will be a trivial change that will be quickly merged). For now, we can live with these inconsistencies.
</blockquote></details>

Well, I could make it consistent here, that should be hard...
`vmid` everywhere for now?
___
*[LibOS/shim/include/shim_ipc.h, line 374 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJF6mO5n7EL5sG6iGy:-MYQ0pYw4BDShoa_tWxx:bhd0sfl) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/LibOS/shim/include/shim_ipc.h#L374)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, you can just do a rename now. Actually, in a separate PR (no need to bundle in this PR). This will be a trivial change (just renames), so that PR will be approved quickly.
</blockquote></details>

I'll stash a commit to this PR, because otherwise I never do it :)
Update, I'll just prepare another PR to be merged after this one - to make it easier to review.
Update: #2318 
___
*[LibOS/shim/src/shim_checkpoint.c, line 571 at r4](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYOcLaJCFjjtMr8hgC5:-MYQ3R5O2z8WCqg4X7EA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c49d8b269c0333ba9e6e5b7f389796ce6d66697/LibOS/shim/src/shim_checkpoint.c#L571)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`connected`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_checkpoint.c, line 577 at r4](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYQCcmR9cJUP8xjlach:-MYQCcmR9cJUP8xjlaci:bq986ku) ([raw file](https://github.com/oscarlab/graphene/blob/2c49d8b269c0333ba9e6e5b7f389796ce6d66697/LibOS/shim/src/shim_checkpoint.c#L577)):*
> ```C
> 
>     char dummy_c = 0;
>     ret = write_exact(pal_process, &dummy_c, sizeof(dummy_c));
> ```

Ughh, this is still not enough. Imagine scenario: everything goes ok, but the malicious host-OS kills the child thread just before we do `add_child_process` above and spoofs this write (i.e. reports it succeeded without sending anything). Since the process was killed before `add_child_porcess` the disconnect callback did not see this child, we added it only later. Now we end up in a situation when the child is dead, but we are not aware of it and have it sill marked as alive.
Is such scenario problematic one, or is it just a simple DoS, which we could ignore? I don't know anymore...
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJK9MPEgveYsWaglmh:-MYQ40N63M78MCZ9FMxG:bmo15j9) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I mean, I'm pretty sure we don't care. Anything would do here. So I don't see a point in this TODO -- this is extremely low-priority. I suggest to just remove this.
</blockquote></details>

Most of the TODOs in this PR should be resolved before merging, e.g. this one. So since we don't really care, I see 2 options:
1) leave it as it is,
2) change tree to list - should be easy and fast to do, the question is would be the code cleaner? I don't know.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJKwcL6jh5oV1LFexD:-MYQ5HJrCXNqxGMFxwTg:b-d9387u) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, thanks, I forgot (or didn't know) this about your AVL tree implementation.
</blockquote></details>

When I was writing this PR I wanted to use such function (`is_in_tree`) and then remembered that I did not add it intentionally. I think the code that used it would be much harder to read and maintain (e,g, getting track of object ownership), so I'm even more convinced that not adding such a function was a good decision.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 96 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJLXKx8qW8Q7Fv4z6r:-MYQ7pcg4_PBbOP9CiCk:b-mri226) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, just a matter of taste. No need to change anything.
</blockquote></details>

I've tried rewriting it, but ended up with `unlock` in 3 different places, so I gave up and left the current version.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 112 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYIvF_QBVWeRIW5GfcJ:-MYQ9IaW6YdmJyMBHeyH:b-nq24id) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L112)):*
>  the use of spinlock is suspicous.

Actually I've just checked and `lock()` is never a spinlock, even on Linux-SGX PAL. Actually that would be weird, LibOS is common for all PALs.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 159 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJNDKe8db-ogNzwYvH:-MYQAYZm90X9Q7tivh4j:b-ilidr5) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L159)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you forgot to push your changes with comments. I don't see anything there.
</blockquote></details>

Yeah, sorry, I got distracted with debugging that damn `DkStreamsWaitEvents`...
I want to cleanup `shim_ipc.h` and add comments to all public functions there. Unfortunately not finished yet.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 220 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJP_kx2V-IdIAYHPt2:-MYQAx0_EwnZ4Lm0Jm2j:bhd12th) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L220)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We **cannot** use this message (`msg`) after giving up the lock - it might get taken of the tree and be destroyed.
</blockquote></details>

Keep in mind that currently we use generic `thread_sleep` which might finish due to other wakeups (e.g. signal arriving). I've added TODO somewhere to change that.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 294 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHuiDh6sRInf3jn41J:-MYQBoee47Oe0gOwtWXX:by8vzhb) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L294)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Interesting, I don't remember seeing this (but this was ages ago when I worked on this part).
</blockquote></details>

Update: this function is broken, e.g. it also report `available for read` only once - if we call it 2 times in a row, without d [...]

2021-04-16 15:48 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 27 of 29 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYQKWl1AQ2ysd47GDdy:bukn7vw) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>If thread A would be the same as S (server) then it could do the first part up_req + down_req directly and then sleep awaiting for the 2nd part to come asynchronously (handled by IPC worker this time).

That sounds fine. Generally, I'm not worried about cases where a thread needs to sleep and wait. I'm worried about the ones where the other side messages me synchronously. For example (sorry, I'm sure it can be made simpler, but I hope it makes the problem clear):

```
A               S              B            C
.               | <-------------- up_req    |
.               | down_req ->  |            .
|  <- down_req  |              |            .
|  down_conf -> |              |            .
.               | <- down_conf |            . 
.               | up_conf --------------->  |    
```

Assume A and S are the same process. Now, what I _would like_ to have, is:

1. S receives `up_req`from C, and then sends `down_req` to A and B
2. At a later time, S receives `down_conf` from A
3. At a later time, S receives `down_conf` from B, and then sends `up_conf` to C

All of the above 3 steps are separate invocations of a server handler, from the IPC worker main loop. The server functions as a nice state machine: lock, handle the incoming message, send resulting outgoing messages, unlock.

However, if "sending" `down_req` to A is actually a function call, and A "responds" immediately to S by issuing another function call, then I have the server handler running, nested, inside the same server handler. Which breaks my design: I cannot just take a lock in the server handler, and assume that my server handler invocations happen one after another.

And probably I can special-case that, but it looks like my code has to handle both "what if I'm calling the other side locally" and "what if I am being called by the other side locally"? This really should be the responsibility of the transport layer, not the code built on top of it.

>But that's what send_msg_with_asck do!

Yes, `send_msg_with_ack` is like an RPC call _that returns a single int_. I would need it to return arbitrary data. I believe this would be useful for the sync engine, although I'm not sure if it would fully solve the above problem of local messages. So maybe it's not so important right now.

>No, because IPC worker thread never awaits for ack messages, it just handles them. If it needs to send a message it does send a normal one (without confirmation).

I'm referring to this part:

```
        if (msg->code < ARRAY_SIZE(ipc_callbacks) && ipc_callbacks[msg->code]) {
            int ret = ipc_callbacks[msg->code](msg, conn->vmid);
            if ((ret < 0 || ret == RESPONSE_CALLBACK) && msg->seq) {
                ret = send_ipc_response(conn->vmid, ret, msg->seq);
```

AFAICT, this runs inside the IPC worker main loop. And `send_ipc_response` writes to a pipe. And the other end of that pipe is handled by another IPC worker. So if two IPC workers send responses to each other simultaneously, it's possible (although unlikely) that both these writes (to their respective pipes) could be blocked on full kernel buffers, causing a deadlock. Is that reasoning correct, or am I making a wrong assumption somewhere?
</blockquote></details>

We had a quick call about this. Short summary from my side:

1. I still need to have a way to send messages to self, e.g. because of the above example
2. I was wrong about `send_msg_with_ack`, it actually does send arbitrary data an response. I will take a look and might be able to use that.
3. Looks like sending messages from IPC worker in general is incorrect, and sending IPC responses / "acks" has to be handled differently, but it's not clear how best to do it:
   * One solution is two helper threads threads (one for receiving messages, another for sending outgoing messages), but this raises performance concerns
   * Another solution is sending in non-blocking mode (queue outgoing data, send as much as you're able, include the outgoing pipes in `select()` to wait until they're unblocked)
   * ...
4. Hopefully, if we solve the problem with sending messages from IPC worker, it will also be a good solution for sending messages to self.
5. For now, I'll continue working with the current IPC code - it should be "good enough" for experimental feature although in practice it can deadlock.

Please correct if anything is not right  :) And I'm resolving this.

---


<!-- Sent from Reviewable.io -->

2021-04-16 15:56 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 27 of 29 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYQN8_i6JOc0KtUOy3N:b2wdmpc) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We had a quick call about this. Short summary from my side:

1. I still need to have a way to send messages to self, e.g. because of the above example
2. I was wrong about `send_msg_with_ack`, it actually does send arbitrary data an response. I will take a look and might be able to use that.
3. Looks like sending messages from IPC worker in general is incorrect, and sending IPC responses / "acks" has to be handled differently, but it's not clear how best to do it:
   * One solution is two helper threads threads (one for receiving messages, another for sending outgoing messages), but this raises performance concerns
   * Another solution is sending in non-blocking mode (queue outgoing data, send as much as you're able, include the outgoing pipes in `select()` to wait until they're unblocked)
   * ...
4. Hopefully, if we solve the problem with sending messages from IPC worker, it will also be a good solution for sending messages to self.
5. For now, I'll continue working with the current IPC code - it should be "good enough" for experimental feature although in practice it can deadlock.

Please correct if anything is not right  :) And I'm resolving this.
</blockquote></details>

To be clear the case when it can deadlock is:
- we have two processes A and B,
- IPC worker in A sends data to process B,
- IPC worker in B sends data to process A,
- they both block on send due to underlying host buffer (e.g. pipe) being full.
The problem is that since they are both blocked on send, they wont process any IPC messages, hence won't read from any buffer and will never allow the other side to unblock.

This issue definitely needs to be addressed, the question is how and when (in this PR?)
I'll try to create some draft proposals and present them on nearest contributors meeting.

---


<!-- Sent from Reviewable.io -->

2021-04-16 19:41 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 64 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJI4Ay4lUXaXOthjj-:-MYRBdx11ZEnaDIkN51h:b59126i) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L64)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, I could make it consistent here, that should be hard...
`vmid` everywhere for now?
</blockquote></details>

`vmid` everywhere then.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 361 at r4](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYOhCdz795GXYQc6TOU:-MYRBn6w9jYrcxxA_BqO:b6kiryw) ([raw file](https://github.com/oscarlab/graphene/blob/2c49d8b269c0333ba9e6e5b7f389796ce6d66697/LibOS/shim/src/ipc/shim_ipc_worker.c#L361)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Or singluar? Which version is correct? (ignore the current version with typo for now)
</blockquote></details>

I think `there are messages`.


<!-- Sent from Reviewable.io -->

2021-04-20 03:07 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 20 of 29 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 64 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJI4Ay4lUXaXOthjj-:-MYh69Ps82x0_kmfGaGC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`vmid` everywhere then.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 328 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJEI6lEjCAJlgLY6af:-MYh6FUG3BHRNppBN1Yg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L328)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a short comment on why `data` and `seq` are needed in these two functions?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 331 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJERCu2P9a7VoGARTk:-MYh6GGbDnkpahfush_g:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L331)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need some comment what this function is.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 332 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJETnj8jGM6LYeLp2e:-MYh6GrR4UcHf-C2WG11:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/include/shim_ipc.h#L332)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Need some comment what this dummy callback is.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 159 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJNDKe8db-ogNzwYvH:-MYh6OgL4DE2cwN0l1N0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L159)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yeah, sorry, I got distracted with debugging that damn `DkStreamsWaitEvents`...
I want to cleanup `shim_ipc.h` and add comments to all public functions there. Unfortunately not finished yet.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 361 at r4](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYOhCdz795GXYQc6TOU:-MYh6fwM6FtmESs1SfHk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c49d8b269c0333ba9e6e5b7f389796ce6d66697/LibOS/shim/src/ipc/shim_ipc_worker.c#L361)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think `there are messages`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-20 08:21 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYK0ynPEQI2GFg6MZ5f:-MYiGmuUEwFVM46xSrhT:b644ehk) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

To be clear the case when it can deadlock is:
- we have two processes A and B,
- IPC worker in A sends data to process B,
- IPC worker in B sends data to process A,
- they both block on send due to underlying host buffer (e.g. pipe) being full.
The problem is that since they are both blocked on send, they wont process any IPC messages, hence won't read from any buffer and will never allow the other side to unblock.

This issue definitely needs to be addressed, the question is how and when (in this PR?)
I'll try to create some draft proposals and present them on nearest contributors meeting.
</blockquote></details>

I think this should be a separate PR.

Using two worker threads seems like the simple solution, but this will become even trickier to debug... Also, now our SGX examples may break because we add one more enclave thread. I don't like this option.

Looks like some form of non-blocking writes with reads-in-between should be the solution.

---
___
*[LibOS/shim/include/shim_ipc.h, line 94 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiG6Ro-QfZP9chKArn:-MYiG6Ro-QfZP9chKAro:b-tf276g) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L94)):*
> ```objc
>  * broadcast ipc messages.
>  */
> int request_leader_connect_back(void);
> ```

Sorry I'm still confused about this function. Why is it different from `connect_to_process(leader_vmid)`? The comment doesn't help in explaining this (if this is about broadcast, doesn't leader always broadcast to all connected processes, no matter how they got connected initially?).
___
*[LibOS/shim/include/shim_ipc.h, line 146 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiIk3t7RJWxW-HnLMH:-MYiIk3uDKBpLjHZ6iY9:bha7uul) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L146)):*
> ```objc
>  * \param[out] seq upon return contains sequence number of this message
>  *
>  * This functions sends a ipc message to the \p dest process and awaits for a response.
> ```

`function`
___
*[LibOS/shim/include/shim_ipc.h, line 169 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiIt1G-s_SwvhEZzwl:-MYiIt1G-s_SwvhEZzwm:b43ecsh) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L169)):*
> ```objc
> 
> /*!
>  * \brief Handle a response to previousle sent message
> ```

`previously`
___
*[LibOS/shim/include/shim_ipc.h, line 186 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiJKEF0JWI5u1S6BMt:-MYiJKEG5b8E8tstx_So:b-rlg8ds) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L186)):*
> ```objc
>  *
>  * \param req_msg original message which got the response
>  * \param data unused (just to confrom #ipc_msg_response_handle callbacks interface)
> ```

`conform to`
___
*[LibOS/shim/src/shim_checkpoint.c, line 577 at r4](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYQCcmR9cJUP8xjlach:-MYiL9RQD-51qj31TTFP:b-ca44z2) ([raw file](https://github.com/oscarlab/graphene/blob/2c49d8b269c0333ba9e6e5b7f389796ce6d66697/LibOS/shim/src/shim_checkpoint.c#L577)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ughh, this is still not enough. Imagine scenario: everything goes ok, but the malicious host-OS kills the child thread just before we do `add_child_process` above and spoofs this write (i.e. reports it succeeded without sending anything). Since the process was killed before `add_child_porcess` the disconnect callback did not see this child, we added it only later. Now we end up in a situation when the child is dead, but we are not aware of it and have it sill marked as alive.
Is such scenario problematic one, or is it just a simple DoS, which we could ignore? I don't know anymore...
</blockquote></details>

It's a DoS situation. As soon as you write "malicious OS does X", then the only thing that Graphene shouldn't do is to reveal any secret info. Graphene can hang, try sending messages to the non-existing child (which will result in either a hang or a TLS error), terminate itself.

So this looks fine. The malicious OS can pretend that the terminated child is still alive at any moment, right (by simply not forwarding the `SIGCHLD` message to the parent)? So it doesn't really matter at which moment the malicious OS "hides" this fact.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJK9MPEgveYsWaglmh:-MYiMLio7UZHq-ttT-Wl:b-a8uxa3) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Most of the TODOs in this PR should be resolved before merging, e.g. this one. So since we don't really care, I see 2 options:
1) leave it as it is,
2) change tree to list - should be easy and fast to do, the question is would be the code cleaner? I don't know.
</blockquote></details>

Well, then I vote for changing to a list.


<!-- Sent from Reviewable.io -->

2021-04-20 20:04 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 94 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiG6Ro-QfZP9chKArn:-MYjivL19mbKist1TVuS:by6mkf1) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry I'm still confused about this function. Why is it different from `connect_to_process(leader_vmid)`? The comment doesn't help in explaining this (if this is about broadcast, doesn't leader always broadcast to all connected processes, no matter how they got connected initially?).
</blockquote></details>

We probably need some general description of IPC inner workings somewhere...
For now updated these comments.
___
*[LibOS/shim/include/shim_ipc.h, line 146 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiIk3t7RJWxW-HnLMH:-MYjjNJP6VZ5pG9ngrNq:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`function`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 169 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiIt1G-s_SwvhEZzwl:-MYjjVF70FJs1zXn-PkI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`previously`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 186 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiJKEF0JWI5u1S6BMt:-MYjj_dh0FV32Izy8fCj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`conform to`
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYJK9MPEgveYsWaglmh:-MYkRrLJ-HsaDgiQJsUB:b-jmo5kn) ([raw file](https://github.com/oscarlab/graphene/blob/c364fdc303dcde75b22755172b324d6c7f54f8ab/LibOS/shim/src/ipc/shim_ipc.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, then I vote for changing to a list.
</blockquote></details>

Sorry for messing, but since the tree is a bit better than list here, I've just left it.


<!-- Sent from Reviewable.io -->

2021-04-21 10:10 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 94 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiG6Ro-QfZP9chKArn:-MYnrUyA2p7cFXRxbx91:brulr2q) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L94)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We probably need some general description of IPC inner workings somewhere...
For now updated these comments.
</blockquote></details>

OK. Now I understood, thanks.
___
*[LibOS/shim/include/shim_ipc.h, line 146 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiIk3t7RJWxW-HnLMH:-MYnrY8OA5kmei4CwwNl:b8kep9h) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L146)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now you have `Ssend` :)

Also, `await for` -> `wait for`
___
*[LibOS/shim/include/shim_ipc.h, line 186 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiJKEF0JWI5u1S6BMt:-MYnrfea95eBmLP9p4kV:b-8e96mk) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L186)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still `confrom` -> `conform`
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 294 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHuiDh6sRInf3jn41J:-MYntsOA5PkPucjcafdn:bj6yodo) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L294)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Update: this function is broken, e.g. it also report `available for read` only once - if we call it 2 times in a row, without doing anything with polled handles, it will report `PAL_WAIT_READ` only on the first call.
I need to rewrite it before merging this PR :(
</blockquote></details>

But your new commit fixes a slightly more specific case: if we call poll 2 times in a row on an **errored** handle, then it will report read only on the first call. Right? Was that the actual problem?
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 238 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYnrmHqCIMRqYsFu6p6:-MYnrmHqCIMRqYsFu6p7:b-flf8wl) ([raw file](https://github.com/oscarlab/graphene/blob/d9c780843ce3fafb054a3ae31e2c073f55739385/LibOS/shim/src/ipc/shim_ipc_worker.c#L238)):*
> ```C
> 
> static noreturn void ipc_worker_main(void) {
>     /* TODO: If we had a global array of connection (instead of a list) we wouldn't have to gather
> ```

`connections` (multiple)
___
*[Pal/src/db_object.c, line 67 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYnruO5BYtUG7GmFi4Y:-MYnruO5BYtUG7GmFi4Z:b-y5tg7z) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/Pal/src/db_object.c#L67)):*
> ```C
>                         PAL_FLG* ret_events, PAL_NUM timeout_us) {
>     if (!count || !handle_array || !events || !ret_events) {
>         return -PAL_ERROR_INVAL;
> ```

Why did you remove it? Seems to make sense to check these values...
___
*[Pal/src/host/Linux/db_object.c, line 75 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYnsyqMDlxPfTm4Z7N8:-MYnsyqMDlxPfTm4Z7N9:bb8q3d1) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/Pal/src/host/Linux/db_object.c#L75)):*
> ```C
>                  * skip it but update its ret_events */
>                 if (events[i] & (PAL_WAIT_READ | PAL_WAIT_WRITE)) {
>                     ret_events[i] |= PAL_WAIT_ERROR;
> ```

Ok, so the error was here. If we would cache `READ`/`WRITE` events in the `hdl`, we could update the `ret_events[i]` with this. But in the current code, we only put `ERROR` event in `ret_events[i]`, so availability of read/write is suppressed.

Is my understanding correct? If yes, then it was quite a bad bug :(

Now we might poll twice on the "errored" handle, but that doesn't seem to pose any problems.
___
*[Pal/src/host/Linux/db_object.c, line 103 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYntcXi4RWpo9i6QqRV:-MYntcXi4RWpo9i6QqRW:b8ecs1n) ([raw file](https://github.com/oscarlab/graphene/blob/d9c780843ce3fafb054a3ae31e2c073f55739385/Pal/src/host/Linux/db_object.c#L103)):*
> ```C
> 
>     if (ret < 0) {
>         ret = unix_to_pal_error(ret);
> ```

This is just a simplification, right? There was no bug here?


<!-- Sent from Reviewable.io -->

2021-04-21 13:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 146 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiIk3t7RJWxW-HnLMH:-MYoVvgS-IReE9me6iys:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L146)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have `Ssend` :)

Also, `await for` -> `wait for`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 186 at r6](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYiJKEF0JWI5u1S6BMt:-MYoW1Sx3E83qImbLzHU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4707f835692de688ea29c8df561c4b760c15211/LibOS/shim/include/shim_ipc.h#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still `confrom` -> `conform`
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 294 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHuiDh6sRInf3jn41J:-MYoWJLT7zRfpqa9bD8Y:b-vq6sap) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L294)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But your new commit fixes a slightly more specific case: if we call poll 2 times in a row on an **errored** handle, then it will report read only on the first call. Right? Was that the actual problem?
</blockquote></details>

Closing the remote end is considered an error (at least by Graphene).
The new commit fixes all kinds of errors we could encounter by not polling what the user requested.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 238 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYnrmHqCIMRqYsFu6p6:-MYoW9F87GNTJ4i0pFuH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d9c780843ce3fafb054a3ae31e2c073f55739385/LibOS/shim/src/ipc/shim_ipc_worker.c#L238)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`connections` (multiple)
</blockquote></details>

Done.
___
*[Pal/src/db_object.c, line 67 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYnruO5BYtUG7GmFi4Y:-MYoWpwk1T9n_2GoKchr:bhxtggt) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/Pal/src/db_object.c#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove it? Seems to make sense to check these values...
</blockquote></details>

Because we actually allow for `count == 0` case.
___
*[Pal/src/host/Linux/db_object.c, line 75 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYnsyqMDlxPfTm4Z7N8:-MYoX6P-72Fia_jf6cXH:b5lrdgp) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/Pal/src/host/Linux/db_object.c#L75)):*
> Is my understanding correct? If yes, then it was quite a bad bug :(

Yes, but note that `ERROR` might be set by other functions as well (whereas there would be no way for them to set availability of read/write).
> Now we might poll twice on the "errored" handle, but that doesn't seem to pose any problems.

Yup, it will just return immediately with an error in revents (which is what the call should expect). Also I've left the caching of errors, so that mallicious host cannot report 1 poll erroring and another succeeding (not sure if that's needed, but doesn't hurt).
___
*[Pal/src/host/Linux/db_object.c, line 103 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYntcXi4RWpo9i6QqRV:-MYoXlpcAGIQxJBcu2EO:b2nhswy) ([raw file](https://github.com/oscarlab/graphene/blob/d9c780843ce3fafb054a3ae31e2c073f55739385/Pal/src/host/Linux/db_object.c#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is just a simplification, right? There was no bug here?
</blockquote></details>

Yes


<!-- Sent from Reviewable.io -->

2021-04-21 14:55 UTC, yamahata approved these changes
> Reviewed 6 of 9 files at r6, 4 of 6 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @yamahata)

___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 371 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHvBjfE0OlLjykqrcg:-MYou40i9wccj8IR9Zys:b-sd1bjl) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L371)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, removing this, but cc @mkow @pwmarcz @yamahata 
</blockquote></details>

IIRC, the comment was stale, I think.


<!-- Sent from Reviewable.io -->

2021-04-21 15:17 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @yamahata)

___
*[Pal/src/host/Linux/db_object.c, line 75 at r7](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYnsyqMDlxPfTm4Z7N8:-MYp-OXIAQGMx3FlRDOl:byg1mft) ([raw file](https://github.com/oscarlab/graphene/blob/5a66947da4f2717353b9337b1c23e61a9352dc5d/Pal/src/host/Linux/db_object.c#L75)):*
> Yes, but note that ERROR might be set by other functions as well (whereas there would be no way for them to set availability of read/write).

True, good point, I didn't take it into account. Yes, it was quite a bad bug :( Resolving.


<!-- Sent from Reviewable.io -->

2021-04-21 18:14 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (kill11, known issue)

2021-04-22 11:02 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 2 unresolved discussions (waiting on @boryspoplawski and @yamahata)



<!-- Sent from Reviewable.io -->

2021-04-22 21:39 UTC, mkow requested changes
> Reviewed 18 of 29 files at r1, 6 of 9 files at r6, 4 of 6 files at r7, 2 of 2 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 16 unresolved discussions (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYI6cgn6lRtchQEHAK2:-MYqo5ta6jfoyl_CkbSB:bp5sb9g) (no related file):*
> You think such naming will be better? They are a bit longer and both are actually internal interfaces (each specific to one file only).

I'd prefer to rename ad Dima suggests, it will make reading this code easier after a few years when we forget this whole discussion and the IPC design ;) But I'm not blocking, not too important.

---
___
*[LibOS/shim/include/shim_ipc.h, line 74 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuSaFF9qcvufS2pQaC:-MYuSaFG4UXErIvy_XfP:bh6ws02) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L74)):*
> ```objc
> 
> /*!
>  * \brief Initialize the ipc worker thread
> ```

`ipc` -> `IPC` (ditto for other places)
___
*[LibOS/shim/include/shim_ipc.h, line 150 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuUJ247Q6qluYoY-0X:-MYuUJ247Q6qluYoY-0Y:be747yi) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L150)):*
> ```objc
>  * the same sequence number.
>  */
> int send_ipc_message_with_ack(struct shim_ipc_msg_with_ack* msg, IDTYPE dest, unsigned long* seq);
> ```

Why `unsigned long`? I'd say we need 64-bits for this.
___
*[LibOS/shim/include/shim_ipc.h, line 152 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuUQcJCFNqMcO_jvqV:-MYuUQcJCFNqMcO_jvqW:bu56mrg) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L152)):*
> ```objc
> int send_ipc_message_with_ack(struct shim_ipc_msg_with_ack* msg, IDTYPE dest, unsigned long* seq);
> /*!
>  * \brief Broadcast a ipc message
> ```

`a` -> `an`
___
*[LibOS/shim/include/shim_ipc.h, line 196 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuVd0R5k-BOE5Q--d6:-MYuVd0R5k-BOE5Q--d7:b-zdq5c1) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L196)):*
> ```objc
> 
> /*!
>  * \brief Find owner of a given id
> ```

What are these IDs? I think this wasn't explained anywhere.
___
*[LibOS/shim/include/shim_ipc.h, line 320 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuW4WL8KgCRGH4x5ZT:-MYuW4WL8KgCRGH4x5ZU:btds7ib) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L320)):*
> ```objc
> 
> int ipc_pid_retmeta_send(IDTYPE dest, IDTYPE pid, enum pid_meta_code code, const void* data,
>                          int datasize, unsigned long seq);
> ```

it was like this before, but could you change this `int` to `size_t`?
___
*[LibOS/shim/include/shim_ipc.h, line 325 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuWEDc77OkuDWaryUl:-MYuWEDc77OkuDWaryUm:bmxtkyr) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L325)):*
> ```objc
> /* sysv namespace */
> struct sysv_key {
>     unsigned long key;
> ```

why `unsigned long`?
___
*[LibOS/shim/src/shim_checkpoint.c, line 583 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuX0us7zZX_OCRSNw9:-MYuX0us7zZX_OCRSNwA:beeloor) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/shim_checkpoint.c#L583)):*
> ```C
>          * Let's pretend the process creation was successful - we have no way to handle such failure
>          * here and it should be indistinguishable form host OS killing the child process right
>          * after we returns from this function.
> ```

`we returns` -> `we return`
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 192 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYv5kd2Djgp72TNSLir:-MYv5kd2Djgp72TNSLis:bx5fhhq) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_pid.c#L192)):*
> ```C
> }
> 
> int ipc_pid_retstatus_send(IDTYPE dest, int nstatus, struct pid_status* status, unsigned long seq) {
> ```

`nstatus` -> `status_cnt`
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 250 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYv9lwSD2TJ8lwnNwzO:-MYv9lwSD2TJ8lwnNwzP:bceivhj) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_pid.c#L250)):*
> ```C
>     data.status = malloc_copy(msgin->status, sizeof(*data.status) * msgin->nstatus);
>     if (!data.status) {
>         data.retval = 0;
> ```

How does this work? Why not just return an error?
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 371 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvAxsa9xivGHVchIlv:-MYvAxsa9xivGHVchIlw:b-d57ga6) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_pid.c#L371)):*
> ```C
> 
> int ipc_pid_retmeta_send(IDTYPE dest, IDTYPE pid, enum pid_meta_code code, const void* data,
>                          int datasize, unsigned long seq) {
> ```

ditto (`size_t`)
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 371 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHvBjfE0OlLjykqrcg:-MYvVGDj3khWdgQEoxAk:b-tt7a9e) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L371)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

IIRC, the comment was stale, I think.
</blockquote></details>

Yeah, it should be fine now. The old code abused alloca too much AFAIR.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 87 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvL_lO-Sw8vchYVmVx:-MYvL_lO-Sw8vchYVmVy:bwxe3wz) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_worker.c#L87)):*
> ```C
>     ipc_child_disconnect_callback(conn->vmid);
> 
>     // TODO: ipc_msg_with_ack_disconnect_callback(conn->vmid);
> ```

Could you write why this code is a TODO?
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 133 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvMvOJ8ncMZ815JdD6:-MYvMvOJ8ncMZ815JdD7:b42u6vz) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_worker.c#L133)):*
> ```C
>     }
> 
>     req_msg->retval = (int)(long)data;
> ```

`long` -> `uintptr_t`
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 142 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvNMXMCE0pNLTCjAKT:-MYvNMXMCE0pNLTCjAKU:b8vlvvf) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_worker.c#L142)):*
> ```C
>     assert(src == msg->src);
> 
>     ipc_msg_response_handle(src, msg->seq, set_request_retval, (void*)(long)resp->retval);
> ```

`long` -> `uintptr_t` (or maybe just cast directly?)
___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MYuDYFVEKdbS5tnRg8s:b-sizyah) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
> ```C
>                 continue;
>             }
> ```

Could we have a test for this bug and similar cases? Overall it seems that our polling is poorly tested, at least comparing to how complex it is.


<!-- Sent from Reviewable.io -->

2021-04-23 00:23 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 29 of 32 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_ipc.h, line 74 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuSaFF9qcvufS2pQaC:-MYvzSj56fSmb4fJV6T1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L74)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`ipc` -> `IPC` (ditto for other places)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 150 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuUJ247Q6qluYoY-0X:-MYvysjJ5w5lJJms0Q7Z:b-8c8ie8) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L150)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why `unsigned long`? I'd say we need 64-bits for this.
</blockquote></details>

Idk, I did not touch that part. (yet™)
___
*[LibOS/shim/include/shim_ipc.h, line 152 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuUQcJCFNqMcO_jvqV:-MYvzX9Z2z6uYbBEfj_8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`a` -> `an`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 196 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuVd0R5k-BOE5Q--d6:-MYvz_hP3rvXIn-TefSe:b-3kofup) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What are these IDs? I think this wasn't explained anywhere.
</blockquote></details>

Probably it wasn't, but that's existing issue out of scope of this PR - I did not rework that part here (fwiw I think these are pids + sysv keys/ids/whatevers - stuff managed by our beautiful IPC ranges).

(this is just a new version of `connect_owner` function).
___
*[LibOS/shim/include/shim_ipc.h, line 320 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuW4WL8KgCRGH4x5ZT:-MYw-ll85dfXHEQ6GHAv:bu2798v) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L320)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

it was like this before, but could you change this `int` to `size_t`?
</blockquote></details>

There are multiple issues like that in the ipc messages part, do you want me to stash fixes in this PR? It's completely unrelated. Also I hope to rewrite them soon anyway.
___
*[LibOS/shim/include/shim_ipc.h, line 325 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuWEDc77OkuDWaryUl:-MYw-4oY4aMffuCCuWeu:bt5u8k9) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L325)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why `unsigned long`?
</blockquote></details>

Why are you asking me? I've just moved this from above.
___
*[LibOS/shim/src/shim_checkpoint.c, line 583 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuX0us7zZX_OCRSNw9:-MYw0IMH-KypFcwpGSfi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/shim_checkpoint.c#L583)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`we returns` -> `we return`
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 192 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYv5kd2Djgp72TNSLir:-MYw0c4_45xdbYtD3c4D:b-y1ypy0) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_pid.c#L192)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`nstatus` -> `status_cnt`
</blockquote></details>

ditto (same case as `int`->`size_t`)
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 250 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYv9lwSD2TJ8lwnNwzO:-MYw1J3y2EdCiE-ZKWMi:b-hoodme) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_pid.c#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How does this work? Why not just return an error?
</blockquote></details>

Because this code assumes that `retval` is actually size/length of `status` and I did not change that part in this PR.
There's no error checking anywhere, so I've at least removed the memory corruption in case of failed allocation.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 371 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvAxsa9xivGHVchIlv:-MYw1yhE2zw1o38B3bbJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_pid.c#L371)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`size_t`)
</blockquote></details>

ditto
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 371 at r1](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYHvBjfE0OlLjykqrcg:-MYw4o8s2Gmbdxy361lg:btd8wym) ([raw file](https://github.com/oscarlab/graphene/blob/400502aee674530a9ba87c73e556707d49e1baf1/LibOS/shim/src/ipc/shim_ipc_worker.c#L371)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, it should be fine now. The old code abused alloca too much AFAIR.
</blockquote></details>

The new one still can - indirectly calling functions outside of this file (and I remember increasing stack size of normal threads recently, due to huge arrays being used). Let's hope it's all fixed or not reachable from this thread...
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 87 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvL_lO-Sw8vchYVmVx:-MYw2Fkk-SxlZz6Dbvv8:bmnfq0k) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_worker.c#L87)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you write why this code is a TODO?
</blockquote></details>

Ah, yes, forgot about that.
Done.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 133 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvMvOJ8ncMZ815JdD6:-MYw4GUy5Gy79L0wkKCv:b-69hcwi) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_worker.c#L133)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`long` -> `uintptr_t`
</blockquote></details>

Done. (`intptr_t`)
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 142 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYvNMXMCE0pNLTCjAKT:-MYw4MnzASHLv0pjhVZf:bxp1ify) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_worker.c#L142)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`long` -> `uintptr_t` (or maybe just cast directly?)
</blockquote></details>

Done. (I don't think you can cast pointer <-> non-pointer of a different size)
___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.i [...]

2021-04-23 00:39 UTC, mkow requested changes
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_ipc.h, line 196 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuVd0R5k-BOE5Q--d6:-MYw6mFFC9-DRxlrtnp0:btyuuxv) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L196)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Probably it wasn't, but that's existing issue out of scope of this PR - I did not rework that part here (fwiw I think these are pids + sysv keys/ids/whatevers - stuff managed by our beautiful IPC ranges).

(this is just a new version of `connect_owner` function).
</blockquote></details>

Ok, but please keep in mind for the upcoming rewrites that this part is not explained anywhere ;)
___
*[LibOS/shim/include/shim_ipc.h, line 325 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuWEDc77OkuDWaryUl:-MYw6vlr4mp0ErC-kGJb:b-r5hruq) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L325)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why are you asking me? I've just moved this from above.
</blockquote></details>

Ah, I missed that this was just shuffling code around.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 250 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYv9lwSD2TJ8lwnNwzO:-MYw77E59nvhDW9aAbvs:b-k9kzzb) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/src/ipc/shim_ipc_pid.c#L250)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because this code assumes that `retval` is actually size/length of `status` and I did not change that part in this PR.
There's no error checking anywhere, so I've at least removed the memory corruption in case of failed allocation.
</blockquote></details>

Ugh. Let's leave this for future PRs then.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 174 at r10](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYw86Ov0R2H0AIXymzx:-MYw86Ov0R2H0AIXymzy:b-2p3m52) ([raw file](https://github.com/oscarlab/graphene/blob/3ca5c7cea571fb1f5fedb7fd6f6dc617e2e59630/LibOS/shim/src/ipc/shim_ipc_worker.c#L174)):*
> ```C
>     union {
>         struct shim_ipc_msg msg_header;
>         char buf[IPC_MSG_MINIMAL_SIZE + READAHEAD_SIZE];
> ```

I just noticed, the size is `IPC_MSG_MINIMAL_SIZE + IPC_MSG_MINIMAL_SIZE + 0x20` - was this double inclusion of `IPC_MSG_MINIMAL_SIZE` intended?
___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MYw9Kuo0IdNAGt-EmAu:b-cyvq39) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think it should be addressed as a separate PR - probably while cleaning stuff in `Pal/regression` - I think they should test stuff like that.
</blockquote></details>

Yeah, not saying that it should be done here. Maybe at least create an issue about lack of proper tests for polling?


<!-- Sent from Reviewable.io -->

2021-04-23 01:23 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 31 of 32 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 196 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuVd0R5k-BOE5Q--d6:-MYw9y7B9ECML6FnNnki:b-t98al) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, but please keep in mind for the upcoming rewrites that this part is not explained anywhere ;)
</blockquote></details>

I hope to get rid of this completely, so there will be no need to explain it :)))
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 174 at r10](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYw86Ov0R2H0AIXymzx:-MYwAtjRErQtO_8tvoG8:b-v892xi) ([raw file](https://github.com/oscarlab/graphene/blob/3ca5c7cea571fb1f5fedb7fd6f6dc617e2e59630/LibOS/shim/src/ipc/shim_ipc_worker.c#L174)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I just noticed, the size is `IPC_MSG_MINIMAL_SIZE + IPC_MSG_MINIMAL_SIZE + 0x20` - was this double inclusion of `IPC_MSG_MINIMAL_SIZE` intended?
</blockquote></details>

Yes, in hope that if we start reading the next message we at least get it's header to have the size ready already.
Added a comment.
___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MYwBdebBmHVSaSy6R5F:bfc3emj) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, not saying that it should be done here. Maybe at least create an issue about lack of proper tests for polling?
</blockquote></details>

Do we have any issue about rewriting `Pal/regression`? It could fit in there. Otherwise I don't see why poll should be special, every function deserves testing!
(btw, we have some poll tests disable in LTP - maybe time to fix them)


<!-- Sent from Reviewable.io -->

2021-04-23 01:52 UTC, mkow requested changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_ipc.h, line 196 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuVd0R5k-BOE5Q--d6:-MYwPoW-CMQL3iiyXG9o:bw4yx53) ([raw file](https://github.com/oscarlab/graphene/blob/5a4b8a974918c8661167841e50803aff76d7ac21/LibOS/shim/include/shim_ipc.h#L196)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I hope to get rid of this completely, so there will be no need to explain it :)))
</blockquote></details>

That's also a good option :)
___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MYwQ0K12NYca2GVUhSM:b-bs6qn3) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
Nah, I don't think we have such an issue.

> Otherwise I don't see why poll should be special, every function deserves testing!

Because it's _really_ complicated and has a lot of corner cases, and yet doesn't have too many tests.


<!-- Sent from Reviewable.io -->

2021-04-23 01:56 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYwR80d8vIxeTBVnQFV:-MYwR80eEfZfWLI_saa2:bejbi2m) (no related file):*
Blocking this PR for now - there are some timeouts in LTP that I need to debug (not sure if due to this PR or just uncovered).

---
___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MYwRJ-ODEiTySSCV4BE:bk41mmq) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nah, I don't think we have such an issue.

> Otherwise I don't see why poll should be special, every function deserves testing!

Because it's _really_ complicated and has a lot of corner cases, and yet doesn't have too many tests.
</blockquote></details>

Then please do create one, I'm not sure what you want to put in there


<!-- Sent from Reviewable.io -->

2021-04-23 01:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MYwRSJK8lqZzMJM4jUE:bw78ecs) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then please do create one, I'm not sure what you want to put in there
</blockquote></details>

It should be faster than proxying this by me :)


<!-- Sent from Reviewable.io -->

2021-04-23 10:59 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-04-23 12:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MYydxYzAfmRBhQUB97C:bftljld) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It should be faster than proxying this by me :)
</blockquote></details>

But you know much better how to test polling, you could describe what and how to test exactly in the issue.


<!-- Sent from Reviewable.io -->

2021-05-04 23:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 14 of 33 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 278 at r12](https://reviewable.io/reviews/oscarlab/graphene/2313#-MZtjV9h74F7yf0nLpB-:-MZtjV9h74F7yf0nLpB0:b-3nk315) ([raw file](https://github.com/oscarlab/graphene/blob/e01f7a8a992ddaf984c734773129355c05fa15b0/LibOS/shim/test/ltp/runltp_xml.py#L278)):*
> ```Python
>         self.time = time.time() - start_time
> 
>         if timedout:
> ```

 I don't particularly like this `timedout` variable and the way the code looks now, but I couldn't think of a better way.
Context: we need to run that `os.killpg` no matter what (timeout, exception, etc) and we need to run it before collecting output streams.


<!-- Sent from Reviewable.io -->

2021-05-05 00:15 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 14 of 33 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/src/host/Linux/db_object.c, line 80 at r9](https://reviewable.io/reviews/oscarlab/graphene/2313#-MYuDYFU2biZ8TUbAJgr:-MZtsJ9w5PTG3xaZuXPS:bbmt727) ([raw file](https://github.com/oscarlab/graphene/blob/b9dbf7d7ff38534c85bb4510ea8e78b3a792346e/Pal/src/host/Linux/db_object.c#L80)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But you know much better how to test polling, you could describe what and how to test exactly in the issue.
</blockquote></details>

#2346 


<!-- Sent from Reviewable.io -->

2021-05-05 06:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed 19 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 278 at r12](https://reviewable.io/reviews/oscarlab/graphene/2313#-MZtjV9h74F7yf0nLpB-:-MZvFoNm9QvZowNsZ3Ve:b-9jg4s7) ([raw file](https://github.com/oscarlab/graphene/blob/e01f7a8a992ddaf984c734773129355c05fa15b0/LibOS/shim/test/ltp/runltp_xml.py#L278)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

 I don't particularly like this `timedout` variable and the way the code looks now, but I couldn't think of a better way.
Context: we need to run that `os.killpg` no matter what (timeout, exception, etc) and we need to run it before collecting output streams.
</blockquote></details>

The code looks good to me.


<!-- Sent from Reviewable.io -->

2021-05-05 11:41 UTC, mkow submitted a review, later dismissed
> Reviewed 19 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-05 12:14 UTC, woju reviewed
> Reviewed 1 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 278 at r12](https://reviewable.io/reviews/oscarlab/graphene/2313#-MZtjV9h74F7yf0nLpB-:-MZwOLa44qQZ2O8LVlff:b-nuf5rm) ([raw file](https://github.com/oscarlab/graphene/blob/e01f7a8a992ddaf984c734773129355c05fa15b0/LibOS/shim/test/ltp/runltp_xml.py#L278)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The code looks good to me.
</blockquote></details>

No, it's OK. I don't think there's a better way.


<!-- Sent from Reviewable.io -->

2021-05-06 04:36 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 32 of 33 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 278 at r12](https://reviewable.io/reviews/oscarlab/graphene/2313#-MZtjV9h74F7yf0nLpB-:-MZzwHKz5nXoxSwaFf2x:b-1dbex) ([raw file](https://github.com/oscarlab/graphene/blob/e01f7a8a992ddaf984c734773129355c05fa15b0/LibOS/shim/test/ltp/runltp_xml.py#L278)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, it's OK. I don't think there's a better way.
</blockquote></details>

Changed got bigger than expected. Pros:
- there shouldn't be any runaway processes no more (previously if the process was already dead, `os.getpgid` failed, which prevented calling `killpg`),
- stdout+stderr are extracted even if the process timed out,
- fixed a hang, where child process was still holding a communication pipe and python tried to extract stdout and hanged.


<!-- Sent from Reviewable.io -->

2021-05-06 06:34 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 32 of 33 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_-NPp-7jJ3sL4dNk2Y:-M_-NPp-7jJ3sL4dNk2Z:b-7ocrgl) (no related file):*
@boryspoplawski Jenkins-Debug-20.04 failed with pretty bad messages: `error: *** Unexpected memory fault occurred inside VDSO (PID = 24244, TID = 24244, RIP = +0x00000b6f)! ***`.

The failing LTP tests were `alarm07` and `select04`.

---


<!-- Sent from Reviewable.io -->

2021-05-06 08:12 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (idk what's going on, I need worksapce but broken jenkins overwrote it)

2021-05-06 09:48 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-06 10:16 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 278 at r12](https://reviewable.io/reviews/oscarlab/graphene/2313#-MZtjV9h74F7yf0nLpB-:-M_01Uu414oKF_FDY2pW:btrz3xx) ([raw file](https://github.com/oscarlab/graphene/blob/e01f7a8a992ddaf984c734773129355c05fa15b0/LibOS/shim/test/ltp/runltp_xml.py#L278)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Changed got bigger than expected. Pros:
- there shouldn't be any runaway processes no more (previously if the process was already dead, `os.getpgid` failed, which prevented calling `killpg`),
- stdout+stderr are extracted even if the process timed out,
- fixed a hang, where child process was still holding a communication pipe and python tried to extract stdout and hanged.
</blockquote></details>

The logic looks OK, I also extracted it to a simple program and tested for myself.

I think it can be made more readable if you run two tasks in parallel, "kill after N seconds" and "communicate":

```python
async def kill_after(self, proc, timeout):
    '''Kill the process if it doesn't exit after `timeout` time. Return True if the wait timed out.'''
    try:
        await asyncio.wait_for(asyncio.ensure_future(proc.wait()), timeout=timeout)
        return False

    except asyncio.exceptions.TimeoutError:
        if proc.pid != os.getpgid(proc.pid):
            # ... (log warning)
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except subprocess.ProcessLookupError:
            pass

        # not strictly necessary because of communicate() below
        await proc.wait()
        return True

async def _run_cmd(...):
    ... # start process

    timed_out, (stdout, stderr) = await asyncio.gather(
         self.kill_after(proc, timeout), proc.communicate())

    ... # process stdout, stderr

    if timed_out:
        raise Error(...)
```

But I'm not sure about it - feel free to ignore if it doesn't read better for you.
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 293 at r13](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_089t5ARbTnPMKadzB:-M_089t61XmPMeUsDnGb:br99twi) ([raw file](https://github.com/oscarlab/graphene/blob/8603631441a88b09750c3f0febe687bdc919f5b1/LibOS/shim/test/ltp/runltp_xml.py#L293)):*
> ```Python
>             for stream in tasks[1].result())
> 
>         if not done:
> ```

I think this `raise Error` should be after the log lines (just before setting `returncode`).

Also, in earlier code you redefine `pending` but not `done`, which is somewhat confusing. How about:

```py
done, pending = ...

if pending:
    timed_out = True
    done, pending = await asyncio.wait(pending)
    assert not pending
else:
    timed_out = False

...

if timed_out:
    raise Error()
```


<!-- Sent from Reviewable.io -->

2021-05-06 10:41 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/test/ltp/runltp_xml.py, line 278 at r12](https://reviewable.io/reviews/oscarlab/graphene/2313#-MZtjV9h74F7yf0nLpB-:-M_0EiSG91egx4Utel8C:bkrouoe) ([raw file](https://github.com/oscarlab/graphene/blob/e01f7a8a992ddaf984c734773129355c05fa15b0/LibOS/shim/test/ltp/runltp_xml.py#L278)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The logic looks OK, I also extracted it to a simple program and tested for myself.

I think it can be made more readable if you run two tasks in parallel, "kill after N seconds" and "communicate":

```python
async def kill_after(self, proc, timeout):
    '''Kill the process if it doesn't exit after `timeout` time. Return True if the wait timed out.'''
    try:
        await asyncio.wait_for(asyncio.ensure_future(proc.wait()), timeout=timeout)
        return False

    except asyncio.exceptions.TimeoutError:
        if proc.pid != os.getpgid(proc.pid):
            # ... (log warning)
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except subprocess.ProcessLookupError:
            pass

        # not strictly necessary because of communicate() below
        await proc.wait()
        return True

async def _run_cmd(...):
    ... # start process

    timed_out, (stdout, stderr) = await asyncio.gather(
         self.kill_after(proc, timeout), proc.communicate())

    ... # process stdout, stderr

    if timed_out:
        raise Error(...)
```

But I'm not sure about it - feel free to ignore if it doesn't read better for you.
</blockquote></details>

I'm not sure which version is better, so I took lazy approach of not doing anything.
___
*[LibOS/shim/test/ltp/runltp_xml.py, line 293 at r13](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_089t5ARbTnPMKadzB:-M_0Dis08ioAnCLVNpp7:bw3fwq7) ([raw file](https://github.com/oscarlab/graphene/blob/8603631441a88b09750c3f0febe687bdc919f5b1/LibOS/shim/test/ltp/runltp_xml.py#L293)):*
> I think this raise Error should be after the log lines (just before setting returncode).

The old version did not print that log and IIUC it's supposed to be a succesful log. On errors we get stdout/err anyway.

> Also, in earlier code you redefine pending but not done, which is somewhat confusing. How about:

`if pending:` is wrong, `pending` can be non-empty both on successful run.
I've changed the part with `if done` tho.


<!-- Sent from Reviewable.io -->

2021-05-06 12:40 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-05-07 12:06 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`select04` LTP test timed out, just a slow Jenkins worker?)

2021-05-07 12:25 UTC, dimakuv requested changes
> Reviewed 4 of 5 files at r14, 12 of 12 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[Pal/src/host/Linux/db_memory.c, line 128 at r15](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_5lwKf5vtmhJEb3lor:-M_5lwKf5vtmhJEb3los:b-j6aoty) ([raw file](https://github.com/oscarlab/graphene/blob/30fbb8d42a28ac02804f0cb68aa3fe103dfdecca/Pal/src/host/Linux/db_memory.c#L128)):*
> ```C
> }
> 
> static void parse_line(const char* line, uintptr_t* start_ptr, uintptr_t* end_ptr) {
> ```

Maybe add a comment that this function expects a line in the format (starting with):
`08048000-08056000 ...`
___
*[Pal/src/host/Linux/pal_linux.h, line 109 at r15](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_5kqB6C-Ybn9g_c3G0:-M_5kqB6C-Ybn9g_c3G1:b7z12w7) ([raw file](https://github.com/oscarlab/graphene/blob/30fbb8d42a28ac02804f0cb68aa3fe103dfdecca/Pal/src/host/Linux/pal_linux.h#L109)):*
> ```objc
> extern uintptr_t g_vdso_end;
> bool is_in_vdso(uintptr_t addr);
> /* Parse "/proc/self/maps" and return addres ranges for "vdso" and "vvar". */
> ```

`address`


<!-- Sent from Reviewable.io -->

2021-05-07 13:01 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: 43 of 45 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Pal/src/host/Linux/db_memory.c, line 128 at r15](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_5lwKf5vtmhJEb3lor:-M_5uGxNC7BgJ6i-4HTR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/30fbb8d42a28ac02804f0cb68aa3fe103dfdecca/Pal/src/host/Linux/db_memory.c#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe add a comment that this function expects a line in the format (starting with):
`08048000-08056000 ...`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/pal_linux.h, line 109 at r15](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_5kqB6C-Ybn9g_c3G0:-M_5uVi01bDy-WHqnFYF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/30fbb8d42a28ac02804f0cb68aa3fe103dfdecca/Pal/src/host/Linux/pal_linux.h#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`address`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-07 13:07 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-05-07 13:18 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (`kill11` failed, known issue)

2021-05-07 22:06 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/src/db_memory.c, line 63 at r16](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_6DTGo6siG2Gb3WOGZ:-M_7qzqp2IXHLwCDPdft:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc3b1538ae24bb760766295d5c735a39015c4d2a/Pal/src/db_memory.c#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer `_cnt` suffix for array element counts, but I'm not blocking.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_memory.c, line 129 at r16](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_6Jwnu7ZE6QLYnxFvF:-M_6dS-X8OQ37rAtRn7s:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc3b1538ae24bb760766295d5c735a39015c4d2a/Pal/src/host/Linux/db_memory.c#L129)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> hexadecimal_number-hexadecimalnumber
> ```

Once with and once without an underscore? :)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_memory.c, line 132 at r16](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_6Nms481hvesqN2w6r:-M_7p8DL8gX7k48BbJuf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc3b1538ae24bb760766295d5c735a39015c4d2a/Pal/src/host/Linux/db_memory.c#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like this, it relies on user addresses being in the lower half of address space.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_memory.c, line 162 at r16](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_6PTbdD8nThvl_8M4E:-M_7pGJD1Ej6GB2mcYEb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc3b1538ae24bb760766295d5c735a39015c4d2a/Pal/src/host/Linux/db_memory.c#L162)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

At first I got confused by this `buf + size` iteration despite the comment saying that there are no partial reads possible. Could you say that we still need to loop because `buf` is small?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_memory.c, line 187 at r16](https://reviewable.io/reviews/oscarlab/graphene/2313#-M_6N5nM8BWgI3afennh:-M_7qNrK27wFs8govwvt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bc3b1538ae24bb760766295d5c735a39015c4d2a/Pal/src/host/Linux/db_memory.c#L187)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please convert into`else-if`, otherwise it's harder to reason about the correctness of this - `parse_line()` assumes that the out arguments were zeroed by the caller, otherwise you will use undefined data on failure. With `if-else` it would be clearly visible that both codepaths are correct.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-07 22:34 UTC, boryspoplawski commented
Jenkins, retest Jenkins-20.04 please (`kill11` known issue)

2021-05-07 22:44 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-05-08 00:36 UTC, mkow approved these changes
> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-05-08 00:39 UTC, yamahata approved these changes
> Reviewed 14 of 19 files at r12, 5 of 5 files at r14, 7 of 12 files at r15, 1 of 2 files at r16, 4 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: all files reviewed, 1 unresolved discussion (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-05-08 09:52 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2313)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-08 17:33 UTC, merged