[LibOS] Get proper distlib path for python apps on Fedora and Ubuntu
oscarlab/graphene pull request #2319
Opened 2021-04-16 18:15 UTC by stefanberger

The distlib path for python apps differs by distro like this:
- Ubuntu: /usr/lib/python3/dist-packages
- Fedora: /usr/lib64/python3.9/site-packages

This patch now builds these paths and only returns them if
the directory exists. The order in which we try things is important
because on Ubuntu /usr/lib/python3.6/site-packages may exist
but on Fedora /usr/lib/python3/dist-packages does not exist.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

2021-04-16 18:16 UTC, stefanberger commented
@woju This should fix the regression.

2021-04-18 23:56 UTC, mkow commented
Jenkins, test this please

2021-04-19 00:01 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2319)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger and @woju)

___
*[python/graphenelibos/manifest.py, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYbPoX58aqYmg2QLoDa:-MYbPoX58aqYmg2QLoDb:bumyfcu) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L48)):*
> ```Python
>     - Ubuntu: /usr/lib/python3/dist-packages
>     - Fedora: /usr/lib64/python3.9/site-packages
>     """
> ```

nitpick: `'''`
___
*[python/graphenelibos/manifest.py, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYbQNKHDzU8WQ4bZAsH:-MYbQNKHDzU8WQ4bZAsI:b-3h3f08) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L56)):*
> ```Python
>     for base in bases:
>         for directory in ['dist-packages', 'site-packages']:
>             p = os.path.join(base, directory)
> ```

I think using pathlib is preferred, but let's ask @woju for an opinion on this.
___
*[python/graphenelibos/manifest.py, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYbPf_YCGJm4X_-BHzI:-MYbPf_YCGJm4X_-BHzJ:b5kjycb) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L59)):*
> ```Python
>             if os.path.isdir(p):
>                 return p
>     return ""
> ```

nitpick: `''`


<!-- Sent from Reviewable.io -->

2021-04-19 12:32 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2319)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @stefanberger and @woju)

___
*[python/graphenelibos/manifest.py, line 53 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYdxnZ01JqwjvrqcLzY:-MYdxnZ01JqwjvrqcLzZ:bmkpjgw) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L53)):*
> ```Python
>                                         vars={'py_version_short': sys.version_info[0]})),
>         sysconfig.get_path('stdlib')
>     ]
> ```

I am wondering whether we should test for availability of a certain directory under that path and I am actually not quite sure whether one path is enough on Fedora.

Jinja2 package unfortunately is not a good way to determine the right path:

Ubuntu: `/usr/lib/python3/dist-packages/jinja2/`
Fedora: `/usr/lib/python3.8/site-patckages/jinja2/`


numpy (and scipy) would work:
Ubuntu: `/usr/lib/python3/dist-packages/num-py`
Fedora: `/usr/lib64/python3.8/site-packages/numpy`

I had been using `/usr/lib64/python3.8/site-packages` successfully before to get the  python-scipy tests to work, though there's a real chance that on Fedora we would require both paths, this one and `/usr/lib/python3.8/site-packages`.


<!-- Sent from Reviewable.io -->

2021-04-19 20:15 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2319)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @stefanberger, and @woju)

___
*[python/graphenelibos/manifest.py, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYbPoX58aqYmg2QLoDa:-MYflVNa8Kl5EJSomlbT:b28c2iw) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L48)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: `'''`
</blockquote></details>

Docstrings should be tripe double quotes: https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring


<!-- Sent from Reviewable.io -->

2021-04-19 20:24 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2319)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow, @stefanberger, and @woju)

___
*[python/graphenelibos/manifest.py, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYbPoX58aqYmg2QLoDa:-MYfn_1k5hjUHGWP7aa3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L48)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Docstrings should be tripe double quotes: https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring
</blockquote></details>

Done.
___
*[python/graphenelibos/manifest.py, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYbPf_YCGJm4X_-BHzI:-MYfna2F-ZCPWWDK9raB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: `''`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-26 16:45 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2319)* status: 0 of 1 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @stefanberger)

___
*[python/graphenelibos/manifest.py, line 53 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYdxnZ01JqwjvrqcLzY:-MZE24XgEd8m0fdrgfTg:byyktuj) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L53)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

I am wondering whether we should test for availability of a certain directory under that path and I am actually not quite sure whether one path is enough on Fedora.

Jinja2 package unfortunately is not a good way to determine the right path:

Ubuntu: `/usr/lib/python3/dist-packages/jinja2/`
Fedora: `/usr/lib/python3.8/site-patckages/jinja2/`


numpy (and scipy) would work:
Ubuntu: `/usr/lib/python3/dist-packages/num-py`
Fedora: `/usr/lib64/python3.8/site-packages/numpy`

I had been using `/usr/lib64/python3.8/site-packages` successfully before to get the  python-scipy tests to work, though there's a real chance that on Fedora we would require both paths, this one and `/usr/lib/python3.8/site-packages`.
</blockquote></details>

This is app-dependent, so if you got this right once in a particular manifest, this shouldn't change. More specifically, it is a property of a particular python module: if you have compiled python module, then it goes to platlib, if not compiled, it goes to purelib (in theory).
___
*[python/graphenelibos/manifest.py, line 56 at r1](https://reviewable.io/reviews/oscarlab/graphene/2319#-MYbQNKHDzU8WQ4bZAsH:-MZE2ZVEBzhJwaPsHtgS:b-sg9fsx) ([raw file](https://github.com/oscarlab/graphene/blob/3b370ef0ca326f6753da1175ad73755127ef79f0/python/graphenelibos/manifest.py#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think using pathlib is preferred, but let's ask @woju for an opinion on this.
</blockquote></details>

I object to the whole approach, but yes, I prefer pathlib.
___
*[python/graphenelibos/manifest.py, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2319#-MZDzfptA5lFQXClQXoH:-MZDzfptA5lFQXClQXoI:b-ush4kc) ([raw file](https://github.com/oscarlab/graphene/blob/2f04123e8e3b01ea21de58005504a11f9feb7683/python/graphenelibos/manifest.py#L47)):*
> ```Python
>     ''' Get distlib directory depending on distro. Examples are:
>     - Ubuntu: /usr/lib/python3/dist-packages
>     - Fedora: /usr/lib64/python3.9/site-packages
> ```

The second one is "platlib" and actually a standard thing. `dist-packages` is debian-specific (https://wiki.debian.org/Python#Deviations_from_upstream, https://salsa.debian.org/cpython-team/python3/-/blob/master/debian/patches/distutils-install-layout.diff) and also a source of displeasure among Python upstream developers (because it has far implications for the "pip" tool which is also patched, see link, and revolves around different ideas about packaging between distro package managers and language-specific package managers).

Would it be enough to modify manifest by adding platlib directory to trusted files?

If not, we could modify the jinja interface by running debian-patched code in `distutils.sysconfig` (which is documented as legacy) instead of standard `sysconfig`, which AFAIU debian does not patch.


<!-- Sent from Reviewable.io -->

2021-05-07 20:02 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2319)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2319#-M_7Q-_a5dq5NG7OPatU:-M_7Q-_b8WhHgxJfeGOZ:b6c6cng) (no related file):*
@woju @stefanberger After we merged https://github.com/oscarlab/graphene/pull/2353, is this PR still relevant? If not, we should close it.

---


<!-- Sent from Reviewable.io -->

2021-05-08 14:01 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2319)* status: 0 of 1 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @stefanberger)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2319#-M_7Q-_a5dq5NG7OPatU:-M_BGVw00FXGEUf6fE9U:b-e8gk0a) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju @stefanberger After we merged https://github.com/oscarlab/graphene/pull/2353, is this PR still relevant? If not, we should close it.
</blockquote></details>

No, #2353 was about installation paths and this one is about paths in manifest. We need it in one form or another. Please keep it open for now, although I might supersede it with some other approach, based on experience gained on #2353. I'm not sure yet.

---


<!-- Sent from Reviewable.io -->

2024-01-15 12:27 UTC, closed without merging