`libos.entrypoint` parsing fixes
oscarlab/graphene pull request #2322
Opened 2021-04-19 16:03 UTC by mkow

## Description of the changes 

This fixes a bunch of issues around `libos.entrypoint` handling:
- Due to our old and incorrect implementation of `snprintf`, long exec names resulted in an unterminated C-strings in some places.
- Even after fixing the above, our logging didn't handle this case nicely - `] ` suffix was missing.
- Seems that one `error: ERROR: ` survived the last logging cleanup.
- `libos.entrypoint` was silently assumed to start with `file:`. So, it if wasn't a proper URI (e.g. due to a user error) it got trimmed: e.g. `my_binary` was stripped to `nary`.

## How to test this PR? 

Set `libos.entrypoint` to some funny things and check whether anything still blows up :)

2021-04-19 17:41 UTC, dimakuv submitted a review, later dismissed
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-20 03:26 UTC, boryspoplawski requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/utils/log.c, line 55 at r1](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhINkTBimZ9cTTgjOM:-MYhINkTBimZ9cTTgjON:b-jiaior) ([raw file](https://github.com/oscarlab/graphene/blob/befd95d76d3083ec31fd3f545c2cb94db38e6fd7/LibOS/shim/src/utils/log.c#L55)):*
> ```C
>         snprintf(tcb->log_prefix, ARRAY_SIZE(tcb->log_prefix), "[%s] ", exec);
>     }
>     if (strlen(tcb->log_prefix) == ARRAY_SIZE(tcb->log_prefix) - 1) {
> ```

This will also snip in a legitimate case (of snprintf-ed string being exactly `ARRAY_SIZE(tcb->log_prefix) - 1` bytes long.
Why don't you check snprintf return value to check whether truncation happened? (it should work after your fixes)
___
*[Pal/src/db_main.c, line 422 at r1](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhIstpCAwzwTrYhX62:-MYhIstpCAwzwTrYhX63:b-bpox) ([raw file](https://github.com/oscarlab/graphene/blob/befd95d76d3083ec31fd3f545c2cb94db38e6fd7/Pal/src/db_main.c#L422)):*
> ```C
>     if (entrypoint) {
>         if (!strstartswith(entrypoint, URI_PREFIX_FILE))
>             INIT_FAIL(-PAL_ERROR_INVAL, "'pal.entrypoint' is missing 'file:' prefix\n");
> ```

Positive value should be passed here.


<!-- Sent from Reviewable.io -->

2021-04-20 03:28 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhJEx16r5-Yw0Shu6n:-MYhJEx16r5-Yw0Shu6o:b-gaco93) (no related file):*
NP: I would drop the `*` from `*snprintf` in commit message. It looks weird and `__snprintf_chk` doesn't match this regex anyway.

---


<!-- Sent from Reviewable.io -->

2021-04-20 14:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: 5 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhJEx16r5-Yw0Shu6n:-MYjYk9f3kdU_iKtPklw:bk5odft) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: I would drop the `*` from `*snprintf` in commit message. It looks weird and `__snprintf_chk` doesn't match this regex anyway.
</blockquote></details>

Will do at rebase.

---
___
*[LibOS/shim/src/utils/log.c, line 55 at r1](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhINkTBimZ9cTTgjOM:-MYjYoj11goMb6UJNAmV:b605yek) ([raw file](https://github.com/oscarlab/graphene/blob/befd95d76d3083ec31fd3f545c2cb94db38e6fd7/LibOS/shim/src/utils/log.c#L55)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This will also snip in a legitimate case (of snprintf-ed string being exactly `ARRAY_SIZE(tcb->log_prefix) - 1` bytes long.
Why don't you check snprintf return value to check whether truncation happened? (it should work after your fixes)
</blockquote></details>

Right. When I was implementing this, `snprintf()` didn't return correct values and only later I noticed that it's incorrect and I can make use of it if it worked :)
___
*[Pal/src/db_main.c, line 422 at r1](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhIstpCAwzwTrYhX62:-MYjgJDw4Jf-_W8E8o8S:b-834n6i) ([raw file](https://github.com/oscarlab/graphene/blob/befd95d76d3083ec31fd3f545c2cb94db38e6fd7/Pal/src/db_main.c#L422)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Positive value should be passed here.
</blockquote></details>

Oops.


<!-- Sent from Reviewable.io -->

2021-04-20 15:06 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-04-20 15:53 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-04-20 16:36 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhJEx16r5-Yw0Shu6n:-MYk7ud46ph96pzB6pD0:b-8nyi3w) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Will do at rebase.
</blockquote></details>

Not done

---


<!-- Sent from Reviewable.io -->

2021-04-20 17:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2322#-MYhJEx16r5-Yw0Shu6n:-MYkJE2YDnkbVOkQ3xm7:bi4mxl4) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Oops, forgot about this. Fixed now.

---


<!-- Sent from Reviewable.io -->

2021-04-20 17:40 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-04-20 19:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2322)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-20 20:02 UTC, merged