[LibOS] Simplify low-level dentry functions
oscarlab/graphene pull request #2324
Opened 2021-04-21 11:05 UTC by pwmarcz

Related to issue #2321 (dentry cleanup)

See the commit message for full list.

This takes care of some low hanging fruit in the dentry cache system - the things that, hopefully, do not cascade to a bigger change.

Next steps are going to be a bit bigger:
- Rewrite `mount_fs`. The current mount semantics are pretty weird: `DENTRY_ANCESTOR` synthetic entries, confusion between parent and child filesystem dentry, deleting old dentries under a mountpoint, mountpoints are invisible in listings (`readdir("/")` doesn't contain `"proc"` even though listing `/proc` works), etc.
  - Fun fact: the regression tests contain a `dev` binary which somehow gets mounted under `/dev`, alongside (???) the dev filesystem
- Rewrite `path_lookupat` / `open_namei` functions, as outlined in #2321 (saner semantics around files that do not exist, and following links); unfortunately this means rewriting all of the call sites, so I want to do it in a separate PR
- Get serious about reference counting and debug whatever is happening there; probably I'll write some nice function to dump the full dentry tree

2021-04-21 12:29 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MYoHUzRBFUHXfXESVE5:bmca08g) (no related file):*
> Fun fact: the regression tests contain a dev binary which somehow gets mounted under /dev, alongside (???) the dev filesystem

Well, that's a hack/feature that is allowed by our current FS mount point semantics. It is legitimate to mount not only directories, but also separate files. It is also legit to mount a subdirectory of another mounter directory (its ancestor). Finally, it is legit to mount subdirectories even under pseudo-FSes like proc and dev. But this abusing of `/dev` can be removed if it is too hacky.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoIKl14TFfFEJLkXFU:-MYoIKl14TFfFEJLkXFV:b-exbyah) (no related file):*
Can you also rename `dcache_lock` -> `g_dcache_lock` and `dentry_root` -> `g_dentry_root` (to make them visibly global).

---
___
*[LibOS/shim/include/shim_fs.h, line 416 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoOtOQ84ky1lVApoMn:-MYoOtORE-I354MiP-ZE:balm5e3) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L416)):*
> ```objc
>  * `dcache_lock`.
>  *
>  * `parent` is the parent node, or NULL if this is supposed to be a root dentry.
> ```

By the way, why can't we enforce `parent != NULL` and pass `dentry_root` in root-dentry cases? 
___
*[LibOS/shim/include/shim_fs.h, line 418 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoIdyg13Xrl9r2Qwbv:-MYoIdyg13Xrl9r2Qwbw:bhteqf7) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L418)):*
> ```objc
>  * `parent` is the parent node, or NULL if this is supposed to be a root dentry.
>  *
>  * `fs` is the mountpoint the dentry is under, or NULL. This should typically be `parent->fs`, but
> ```

Could you please add a comment what happens if `fs == NULL`? Is the mountpoint taken from `parent->fs`?
___
*[LibOS/shim/include/shim_fs.h, line 419 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJB6ZCXpj1sStKy3M:-MYoJB6_CP31fzgkJUTq:bwbghlq) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L419)):*
> ```objc
>  *
>  * `fs` is the mountpoint the dentry is under, or NULL. This should typically be `parent->fs`, but
>  * is passed explicitly for initializing the dentry of a mountpoint.
> ```

I'm confused. Do you mean:
- "`fs` is used to initialize to mountpoint field of the dentry" or
- "the dentry field of `fs` is initialized as a side-effect"
?
___
*[LibOS/shim/include/shim_fs.h, line 422 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJ8ND63U2Owd1vVmT:-MYoJ8ND63U2Owd1vVmU:bk82yyk) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L422)):*
> ```objc
>  *
>  * Returns the new dentry, or NULL in case of allocation failure. The function will initialize
>  * `fs` (if provided), `name`, `rel_path`, and parent/children links. The reference count of the
> ```

What is the `rel_path`?
___
*[LibOS/shim/include/shim_fs.h, line 423 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJb0l87dUQAgYM2wj:-MYoJb0l87dUQAgYM2wk:b-rvz4rc) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L423)):*
> ```objc
>  * Returns the new dentry, or NULL in case of allocation failure. The function will initialize
>  * `fs` (if provided), `name`, `rel_path`, and parent/children links. The reference count of the
>  * returned dentry will be incremented.
> ```

The old comment mentions 2 or 1, depending on whether there is a parent or not. This looks like an important detail to mention.
___
*[LibOS/shim/include/shim_fs.h, line 436 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoKvxc-nJ5iRM-0Uhp:-MYoKvxc-nJ5iRM-0Uhq:b-kaz55r) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L436)):*
> ```objc
> 
> /*
>  * Search for a child of a dentry with a given name. The caller should hold `dcache_lock`.
> ```

Accidentally copied a wrong comment here? You didn't change this function (and it recursively deletes the whole dentry tree).
___
*[LibOS/shim/src/fs/shim_dcache.c, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoNVBt2YPxB2EaQOZm:-MYoNVBt2YPxB2EaQOZn:b-7n3nbu) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L142)):*
> ```C
> }
> 
> static void maybe_delete_dentry(struct shim_dentry* dent) {
> ```

The name is misleading... Maybe `unlink_nonexisting_dentry_from_parent()`?

Well, my proposed name is also long, but at least very specific.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoN3ecBF9guPabY6GI:-MYoN3ed3qkdMwsd-Qne:bywld3l) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
> ```C
>     if (count == 2) {
>         /* If the ref count is exactly 2, we are holding the last reference to dentry (except for parent
>          * or filesystem, in case of root). Try to delete it. Make sure we check the conditions while
> ```

`except for parent or filesystem, in case of root` -- I don't get this sentence. Looks like you're trying to say that we can have count = 2 in two cases:
- Last reference to non-root dentry: legitimate case, can delete and free
- Two independent references to root dentry: don't do anything, just put one reference

If I understood you correctly, please re-write the comment to be more precise about these two cases.
___
*[LibOS/shim/src/sys/shim_socket.c, line 428 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoKfTmEslQbKenTThZ:-MYoKfTnArDvcEwvyuVK:b-esd87v) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/sys/shim_socket.c#L428)):*
> ```C
> 
> static int hash_to_hex_string(struct shim_dentry* dent, char* buf, size_t size) {
>     char buffer[dentry_get_path_size(dent)];
> ```

I would suggest to put an assert on the maximum path size here. We're using the LibOS stack, it could overflow if the path is very long... I believe there is already a macro constant like this (`PATH_SIZE`?).


<!-- Sent from Reviewable.io -->

2021-04-21 14:29 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: 4 of 10 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MYoPvAl-dTJVKvskUEw:b2ci49h) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Fun fact: the regression tests contain a dev binary which somehow gets mounted under /dev, alongside (???) the dev filesystem

Well, that's a hack/feature that is allowed by our current FS mount point semantics. It is legitimate to mount not only directories, but also separate files. It is also legit to mount a subdirectory of another mounter directory (its ancestor). Finally, it is legit to mount subdirectories even under pseudo-FSes like proc and dev. But this abusing of `/dev` can be removed if it is too hacky.
</blockquote></details>

Okay, so the `/dev` directory shadows the `dev` executable, but somehow we load the `dev` executable earlier, while it's still accessible...

I ran into it while trying to refactor the mount system, because in other cases it complains about duplicate mounts, so I assumed mounting under an existing file/directory should be disallowed. But apparently it's not always disallowed.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoIKl14TFfFEJLkXFU:-MYojC32-CSzzP_sJlmD:b-9h485d) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you also rename `dcache_lock` -> `g_dcache_lock` and `dentry_root` -> `g_dentry_root` (to make them visibly global).
</blockquote></details>

Done. But I don't want this PR to get too big, so let's not bundle more unrelated changes here. I'd rather follow up with next PRs quickly, this is already a part of a much bigger branch.

---
___
*[LibOS/shim/include/shim_fs.h, line 416 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoOtOQ84ky1lVApoMn:-MYoT6ElEsO48jcX6c2n:b4pinco) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L416)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, why can't we enforce `parent != NULL` and pass `dentry_root` in root-dentry cases? 
</blockquote></details>

I'm not convinced that is better... If the root dentry has itself as parent, you trade all `if(dent->parent)` checks for `if (dent->parent != dent)`, but you still need to make the checks in all cases that use the parent (detaching entry from parent, computing the path, etc.)

(Also, if we're creating the root dentry, it doesn't exist yet, so wouldn't we need to bootstrap it with NULL anyway, and only then add the cyclic reference?)
___
*[LibOS/shim/include/shim_fs.h, line 418 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoIdyg13Xrl9r2Qwbv:-MYoUryf6_Nb_NGgmxyH:bpogyqp) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L418)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you please add a comment what happens if `fs == NULL`? Is the mountpoint taken from `parent->fs`?
</blockquote></details>

It defaults to null, I think taking it from`parent` would be too clever (too many ways of achieving the same thing). I added a comment.

Maybe I'll be able get rid of that `fs` parameter when rewriting mounts. Or split that off to another mount-making function.
___
*[LibOS/shim/include/shim_fs.h, line 419 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJB6ZCXpj1sStKy3M:-MYoVs-VBzPtD8BzBFdR:b-i1f1oc) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L419)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm confused. Do you mean:
- "`fs` is used to initialize to mountpoint field of the dentry" or
- "the dentry field of `fs` is initialized as a side-effect"
?
</blockquote></details>

I reworded it to "to support initializing the root dentry of a newly mounted filesystem." I hope that's more clear.
___
*[LibOS/shim/include/shim_fs.h, line 422 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJ8ND63U2Owd1vVmT:-MYoVy1Y8SSkyj7I7-PW:b-anddbf) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L422)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the `rel_path`?
</blockquote></details>

`rel_path` is path relative to dentry's mountpoint, as documented in `struct shim_dentry`. It's also a horrible mess - the mount code does this:

```c
    // We need to fix up the relative path to this mount, but only for
    // directories.
    qstrsetstr(&dent->rel_path, "", 0);
```

Because I do not want to modify the mount code yet, I'll document what happens here, and leave the behavior of `get_new_dentry` as-is.
___
*[LibOS/shim/include/shim_fs.h, line 423 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJb0l87dUQAgYM2wj:-MYo_2ew2VBSmckwS2vb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L423)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The old comment mentions 2 or 1, depending on whether there is a parent or not. This looks like an important detail to mention.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 436 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoKvxc-nJ5iRM-0Uhp:-MYo_bLD1emN-_drcVDC:blqu2zo) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L436)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Accidentally copied a wrong comment here? You didn't change this function (and it recursively deletes the whole dentry tree).
</blockquote></details>

Yeah, I don't want to touch that yet. Fixed.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 142 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoNVBt2YPxB2EaQOZm:-MYo_qr5EP_PWel1XN0V:b7brstq) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The name is misleading... Maybe `unlink_nonexisting_dentry_from_parent()`?

Well, my proposed name is also long, but at least very specific.
</blockquote></details>

I don't want to say "unlink", because it suggests unlinking an actual file from directory.

I changed it to `detach_dentry_if_possible` and added a better explanation of what happens.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoN3ecBF9guPabY6GI:-MYod4GW3ShFcB0Zc6xj:b-6jvb1r) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`except for parent or filesystem, in case of root` -- I don't get this sentence. Looks like you're trying to say that we can have count = 2 in two cases:
- Last reference to non-root dentry: legitimate case, can delete and free
- Two independent references to root dentry: don't do anything, just put one reference

If I understood you correctly, please re-write the comment to be more precise about these t [...]

2021-04-21 15:11 UTC, yamahata submitted a review, later dismissed
> Reviewed 4 of 9 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 187 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoxrEyAy7qm10fGoRK:-MYoxrEyAy7qm10fGoRL:buz6mo6) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/src/fs/shim_dcache.c#L187)):*
> ```C
>          * holding `g_dcache_lock`, as someone might have acquired a reference in meantime.
>          */
>         if (locked(&g_dcache_lock)) {
> ```

This doesn't seem right. What if other thread is holding this lock?
If we know this thread has this lock, it should be passed as argument.

anyway this PR is preparation for future PR, the original code is a sort of broken, whole rewrite is planned, I make this comment non-blocking.


<!-- Sent from Reviewable.io -->

2021-04-21 15:13 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MYoxicr10znluBInzHT:bzhr6c3) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, so the `/dev` directory shadows the `dev` executable, but somehow we load the `dev` executable earlier, while it's still accessible...

I ran into it while trying to refactor the mount system, because in other cases it complains about duplicate mounts, so I assumed mounting under an existing file/directory should be disallowed. But apparently it's not always disallowed.
</blockquote></details>

Oops. I'm sorry, I misunderstood you. I thought you meant `/dev/kmsg` device that we mount in our LibOS regression tests.

Now I understand that you meant the `dev` executable (one of our tests). Because `dev` is located in the current dir, it automatically goes under root dir and becomes `/dev`. Yes, this is surprising and is a fun fact. I don't know how/why this happens.

---
___
*[LibOS/shim/include/shim_fs.h, line 416 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoOtOQ84ky1lVApoMn:-MYoy9RG5VDecAAR0n2S:bmctigb) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L416)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'm not convinced that is better... If the root dentry has itself as parent, you trade all `if(dent->parent)` checks for `if (dent->parent != dent)`, but you still need to make the checks in all cases that use the parent (detaching entry from parent, computing the path, etc.)

(Also, if we're creating the root dentry, it doesn't exist yet, so wouldn't we need to bootstrap it with NULL anyway, and only then add the cyclic reference?)
</blockquote></details>

OK, true.
___
*[LibOS/shim/include/shim_fs.h, line 419 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJB6ZCXpj1sStKy3M:-MYoyIWI-h1MSHY7pksn:b-j2lh2c) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L419)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I reworded it to "to support initializing the root dentry of a newly mounted filesystem." I hope that's more clear.
</blockquote></details>

OK, thanks. These semantics are just insane...
___
*[LibOS/shim/include/shim_fs.h, line 422 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJ8ND63U2Owd1vVmT:-MYoyOQe2pSeKQx7QsIC:btm9clh) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L422)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`rel_path` is path relative to dentry's mountpoint, as documented in `struct shim_dentry`. It's also a horrible mess - the mount code does this:

```c
    // We need to fix up the relative path to this mount, but only for
    // directories.
    qstrsetstr(&dent->rel_path, "", 0);
```

Because I do not want to modify the mount code yet, I'll document what happens here, and leave the behavior of `get_new_dentry` as-is.
</blockquote></details>

OK. I wrote this comment because `rel_path` is not in the argument list of this function, so I thought you made a typo. Now I understand that you meant initializing `rel_path` of the dentry.
___
*[LibOS/shim/include/shim_fs.h, line 425 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoyh8T63EPK-LQ9kfV:-MYoyh8T63EPK-LQ9kfW:b8tg65m) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/include/shim_fs.h#L425)):*
> ```objc
>  * `fs` (if provided), `name`, `rel_path`, and parent/children links.
>  *
>  * The reference count of the returned dentry will 2 if `parent` was provided, 1 otherwise.
> ```

`will be`
___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoN3ecBF9guPabY6GI:-MYoz7-b4KdNZOjPfCzG:bxa31k) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Is the explanation right now OK? I'm not talking about the dentry root, but about whether the dentry has a parent (which is what this function should care about).

I don't want to enumerate these 2 cases here, because (at least right now) there is also the `__del_dentry_tree` function that detaches parent manually. There might be other such cases in the future, and as long as the reference counts are maintained correctly, `put_dentry` should do the right thing.
</blockquote></details>

OK, thanks, the comments are very good now.


<!-- Sent from Reviewable.io -->

2021-04-21 16:27 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: 9 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MYpEJcY8yDntsANP3Pt:b46bk3b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops. I'm sorry, I misunderstood you. I thought you meant `/dev/kmsg` device that we mount in our LibOS regression tests.

Now I understand that you meant the `dev` executable (one of our tests). Because `dev` is located in the current dir, it automatically goes under root dir and becomes `/dev`. Yes, this is surprising and is a fun fact. I don't know how/why this happens.
</blockquote></details>

I'll look into it when rewriting mounts, and probably rename the example for sanity.

And at some point I would like the default directory (where the executable is mounted, etc.) to not be `/`, but something like `/home/user`.

---
___
*[LibOS/shim/include/shim_fs.h, line 419 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJB6ZCXpj1sStKy3M:-MYpCkIr9f9zeFffmyXr:b-l4xeyu) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L419)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, thanks. These semantics are just insane...
</blockquote></details>

It's going to get better :)
___
*[LibOS/shim/include/shim_fs.h, line 425 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoyh8T63EPK-LQ9kfV:-MYpEynD67eca7SWwe4L:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/include/shim_fs.h#L425)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`will be`
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 187 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoxrEyAy7qm10fGoRK:-MYpCw9PDef4KopycA_y:btev8yx) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/src/fs/shim_dcache.c#L187)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

This doesn't seem right. What if other thread is holding this lock?
If we know this thread has this lock, it should be passed as argument.

anyway this PR is preparation for future PR, the original code is a sort of broken, whole rewrite is planned, I make this comment non-blocking.
</blockquote></details>

`locked()` checks if our thread is holding the lock (`get_cur_tid() == lock->owner`), it's my understanding that it is accurate (otherwise the asserts that use it are not accurate either, and could sometimes pass when they shouldn't).

The point is that I'd like `put_dentry` to be usable in all circumstances, and be guaranteed to detach the dentry sooner or later. If this check is no good, there could be `put_dentry_with_lock()` and `put_dentry_without_lock()` and you're supposed to call the right one, but it sounds pretty inconvenient.

Or maybe there is some better way of garbage-collecting the dentries...


<!-- Sent from Reviewable.io -->

2021-04-21 16:58 UTC, boryspoplawski requested changes
> Reviewed 4 of 9 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MYpGhLABWXsN7kQpgiW:brevglv) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I'll look into it when rewriting mounts, and probably rename the example for sanity.

And at some point I would like the default directory (where the executable is mounted, etc.) to not be `/`, but something like `/home/user`.
</blockquote></details>

Imo there should be no default main-exec mounting. If you want to run something mount it explicitly. We should also get rid of this mounting host `.` as `/` completely.

---
___
*[LibOS/shim/include/shim_fs.h, line 389 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpEubj7lLp8-lh2YJ4:-MYpEubk2knOScHHhR15:bllow90) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/include/shim_fs.h#L389)):*
> ```objc
>  * Decrement the reference count on `dent`, and delete it from the tree if possible (i.e. there are
>  * no references to it except parent, and it does not represent a real file (it's either invalid or
>  * negative).
> ```

Is Graphene really ready for this without other reworks?
E.g. what happens if you mount host file `a` on `/a` and then open+close it (so that `put_dentry` triggers on last reference)?
___
*[LibOS/shim/include/shim_fs.h, line 412 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpFWH13CqBhYwCUNxR:-MYpFWH13CqBhYwCUNxS:b-u42v0a) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/include/shim_fs.h#L412)):*
> ```objc
> }
> 
> /*
> ```

Could you rewrite this to use sphinx syntax?
Actually ditto for all comments you've rewritten in `.h`.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 187 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoxrEyAy7qm10fGoRK:-MYpJTO51pmten0aZNFI:b-5yrbdt) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/src/fs/shim_dcache.c#L187)):*
Hard veto from my side.

`locked()` is only meant to be used inside `assert` in debug builds and nowhere else (e.g. spinlocks define such function only on debug builds).
> otherwise the asserts that use it are not accurate either, and could sometimes pass when they shouldn't

Yes, they sometimes can pass when they shouldn't. These asserts have some purpose tho:
1) there are no false-negatives, so if some trigger it means we have a bug (and given enough runs they should),
2) they document which locks a function needs.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 126 at r3](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpIMRJ2qMUXoUa-gtK:-MYpIMRJ2qMUXoUa-gtL:b-t7jsjc) ([raw file](https://github.com/oscarlab/graphene/blob/0d8335b7ef5cf644ea6991b8ded3c7d2c2f58747/LibOS/shim/src/fs/shim_dcache.c#L126)):*
> ```C
> }
> 
> static int __put_dentry(struct shim_dentry* dent) {
> ```

Names starting with double underscore are reserved in C.
___
*[LibOS/shim/src/sys/shim_socket.c, line 427 at r3](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpMDi9-okt1FRBaxcb:-MYpMDiA1jGcfQOj4swt:b-4ttp46) ([raw file](https://github.com/oscarlab/graphene/blob/0d8335b7ef5cf644ea6991b8ded3c7d2c2f58747/LibOS/shim/src/sys/shim_socket.c#L427)):*
> ```C
> }
> 
> static int hash_to_hex_string(struct shim_dentry* dent, char* buf, size_t size) {
> ```

Now this function name is wrong, isn't it?


<!-- Sent from Reviewable.io -->

2021-04-21 17:17 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 187 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoxrEyAy7qm10fGoRK:-MYpPYmo7tU-cJss_t9E:b-ntcb5t) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/src/fs/shim_dcache.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hard veto from my side.

`locked()` is only meant to be used inside `assert` in debug builds and nowhere else (e.g. spinlocks define such function only on debug builds).
> otherwise the asserts that use it are not accurate either, and could sometimes pass when they shouldn't

Yes, they sometimes can pass when they shouldn't. These asserts have some purpose tho:
1) there are no false-negatives, so if some trigger it means we have a bug (and given enough runs they should),
2) they document which locks a function needs.
</blockquote></details>

Ok, then it makes sense as long as lock owner is checked.


<!-- Sent from Reviewable.io -->

2021-04-21 22:58 UTC, mkow requested changes
> Reviewed 9 of 9 files at r1, 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MYoiXeA8egr-kohkBeV:b-62wnk5) (no related file):*
> Well, that's a hack/feature that is allowed by our current FS mount point semantics.

I'd say it's a feature, I think on Linux you can also mount single files.

> But this abusing of /dev can be removed if it is too hacky.

In this case it's not abusing it, it's just a bug that this is possible.

Anyways, I see that you just misunderstood Paweł :)

> Imo there should be no default main-exec mounting. If you want to run something mount it explicitly. We should also get rid of this mounting host `.` as `/` completely.

+1, although the main-exec is not "mounted", it's just the current directory which is (I think).

---
___
*[LibOS/shim/src/fs/shim_dcache.c, line 127 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqbKZP1jbQ5k4fjy7p:-MYqbKZP1jbQ5k4fjy7q:b-ib6du7) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L127)):*
> ```C
> 
> static int __put_dentry(struct shim_dentry* dent) {
>     int count = REF_DEC(dent->ref_count);
> ```

Huh, I just noticed that our ref counters are `int64_t`, but `REF_DEC` trims the counts to `int`. @pwmarcz Could you fix this in another PR? Looks simple.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqby4HDR9iP3fx7_J8:-MYqby4HDR9iP3fx7_J9:b-n66qs2) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
> ```C
>     if (count == 2) {
>         /* If the ref count is exactly 2, we are holding the last reference to dentry (except for parent
>          * or filesystem, in case of root). Try to delete it. Make sure we check the conditions while
> ```

Please rewrap
___
*[LibOS/shim/src/fs/shim_dcache.c, line 187 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoxrEyAy7qm10fGoRK:-MYqcVNOCBwVj3a2pOQb:b-rmlfvk) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/src/fs/shim_dcache.c#L187)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Ok, then it makes sense as long as lock owner is checked.
</blockquote></details>

I agree with Borys, `locked()` is racy and usable only in asserts.


<!-- Sent from Reviewable.io -->

2021-04-22 00:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 127 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqbKZP1jbQ5k4fjy7p:-MYqx3jqAXulsUZ_m3UP:b49phva) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, I just noticed that our ref counters are `int64_t`, but `REF_DEC` trims the counts to `int`. @pwmarcz Could you fix this in another PR? Looks simple.
</blockquote></details>

I've already done that in IPC PR (well, probably should have split that...)


<!-- Sent from Reviewable.io -->

2021-04-22 00:56 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 127 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqbKZP1jbQ5k4fjy7p:-MYr3lht05tSVAbldvYD:b-lkgykz) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've already done that in IPC PR (well, probably should have split that...)
</blockquote></details>

Great! But I'll leave this blocking, as rebasing may introduce (probably silent?) bugs here. Not sure if GCC would warn about such an assignment.


<!-- Sent from Reviewable.io -->

2021-04-22 01:00 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 127 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqbKZP1jbQ5k4fjy7p:-MYr4rIAAkrgjMWmwYXE:bt8p1ky) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Great! But I'll leave this blocking, as rebasing may introduce (probably silent?) bugs here. Not sure if GCC would warn about such an assignment.
</blockquote></details>

Ah, no, I've just change the function signature/return value, but I've not touched every call site (which means probably every `put_something`).


<!-- Sent from Reviewable.io -->

2021-04-22 07:44 UTC, dimakuv approved these changes
> Reviewed 1 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-04-22 13:39 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: 6 of 10 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_fs.h, line 389 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpEubj7lLp8-lh2YJ4:-MYtgjRY3fbeL9sPJrY8:b7k0d90) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/include/shim_fs.h#L389)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is Graphene really ready for this without other reworks?
E.g. what happens if you mount host file `a` on `/a` and then open+close it (so that `put_dentry` triggers on last reference)?
</blockquote></details>

We are only deleting invalid and negative dentries, so in your example, nothing will happen. "Real" dentries are managed by their filesystem, so we would have to ask filesystem to release the data first. This is only a solution for "ephemeral" dentries such as result of a failed lookup.

 (I refactored this, but the point still stands).
___
*[LibOS/shim/include/shim_fs.h, line 412 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpFWH13CqBhYwCUNxR:-MYthB_94-KyU1_HP4YM:b-o1qu32) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/include/shim_fs.h#L412)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you rewrite this to use sphinx syntax?
Actually ditto for all comments you've rewritten in `.h`.
</blockquote></details>

Sure, done. I'll keep that in mind when rewriting more functions.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 127 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqbKZP1jbQ5k4fjy7p:-MYthFGJB9d7nyo8cObg:bi2jhpk) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, no, I've just change the function signature/return value, but I've not touched every call site (which means probably every `put_something`).
</blockquote></details>

I changed `get_dentry` and `put_dentry` to use `int64_t`.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqby4HDR9iP3fx7_J8:-MYtRN749sV8wmS7pL4R:bic92yp) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please rewrap
</blockquote></details>

I rewrote this code, but what is wrong here? This comment is wrapped to 100 columns.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 187 at r2](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoxrEyAy7qm10fGoRK:-MYthZtC0lDIg4hi1QTV:bm7fo7b) ([raw file](https://github.com/oscarlab/graphene/blob/67c6867ee4927df737292bb35abd46ba5e82e0fe/LibOS/shim/src/fs/shim_dcache.c#L187)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I agree with Borys, `locked()` is racy and usable only in asserts.
</blockquote></details>

OK, got it. I am reverting this.

I don't want to make the user of `put_dentry` think whether they're holding a lock or not, though. A solution with two `put_dentry` functions (or a parametrized one) seems pretty inconvenient to me. So maybe it's not a good idea for reference counting to be too clever.

I think that a better approach (at least for now) is to delete ephemeral dentries during traversal. It doesn't guarantee we will drop them immediately, but performing many failed lookups will not slow down future operations. And it's a more internal mechanism now - the rest of filesystem code doesn't need to do anything.

(This will probably change later, if we decide that a linear directory lookup is too slow, or that we want to keep some negative dentries around, or purge non-negative dentries).
___
*[LibOS/shim/src/fs/shim_dcache.c, line 126 at r3](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpIMRJ2qMUXoUa-gtK:-MYtPkqCD-GCl9Gh_FSI:b-fz45lv) ([raw file](https://github.com/oscarlab/graphene/blob/0d8335b7ef5cf644ea6991b8ded3c7d2c2f58747/LibOS/shim/src/fs/shim_dcache.c#L126)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Names starting with double underscore are reserved in C.
</blockquote></details>

This code is now gone, but this issue will come up often as Graphene makes heavy use of `__name` for internal/helper functions - any ideas for an alternative convention?
___
*[LibOS/shim/src/sys/shim_socket.c, line 427 at r3](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpMDi9-okt1FRBaxcb:-MYtkJX20cKblwXffzDv:b-bvindf) ([raw file](https://github.com/oscarlab/graphene/blob/0d8335b7ef5cf644ea6991b8ded3c7d2c2f58747/LibOS/shim/src/sys/shim_socket.c#L427)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now this function name is wrong, isn't it?
</blockquote></details>

Renamed to `hash_dentry_path`.


<!-- Sent from Reviewable.io -->

2021-04-22 14:13 UTC, mkow requested changes
> Reviewed 1 of 6 files at r2, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqby4HDR9iP3fx7_J8:-MYttpIT265xxqNYY4Mt:bj0h6ot) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I rewrote this code, but what is wrong here? This comment is wrapped to 100 columns.
</blockquote></details>

Hmm, I don't think it was. I have Reviewable set to show 100 chars per line and these two got wrapped.

These lines in r1 are:
```C
        /* If the ref count is exactly 2, we are holding the last reference to dentry (except for parent
         * or filesystem, in case of root). Try to delete it. Make sure we check the conditions while
```

The first one has 104 characters and the second 101. Maybe your editor has the count incorrectly set? Or maybe I was looking at a different revision than you?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 126 at r3](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpIMRJ2qMUXoUa-gtK:-MYtspMD0wp6xA6Yqb2s:bqulh24) ([raw file](https://github.com/oscarlab/graphene/blob/0d8335b7ef5cf644ea6991b8ded3c7d2c2f58747/LibOS/shim/src/fs/shim_dcache.c#L126)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This code is now gone, but this issue will come up often as Graphene makes heavy use of `__name` for internal/helper functions - any ideas for an alternative convention?
</blockquote></details>

Maybe a single underscore? It's not reserved if the second char is lowercase.
___
*[LibOS/shim/src/sys/shim_socket.c, line 436 at r4](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYtuvyV0DUkO0sEEy41:-MYtuvyV0DUkO0sEEy42:b-rcd3t4) ([raw file](https://github.com/oscarlab/graphene/blob/6bff9e6921538f2dfe060a6cff778e773bcfa624/LibOS/shim/src/sys/shim_socket.c#L436)):*
> ```C
> 
>     /* TODO: this could be a stack allocation, but LibOS full paths do not respect any limit (only
>      * mount-relative paths do). */
> ```

Is this really something we want to change? I'm fine with internal support for unlimited paths and only filtering them where original Linux interface does.


<!-- Sent from Reviewable.io -->

2021-04-22 17:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: 9 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqby4HDR9iP3fx7_J8:-MYuWPHN2kwhyVKGs_SB:bkp9c0h) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I don't think it was. I have Reviewable set to show 100 chars per line and these two got wrapped.

These lines in r1 are:
```C
        /* If the ref count is exactly 2, we are holding the last reference to dentry (except for parent
         * or filesystem, in case of root). Try to delete it. Make sure we check the conditions while
```

The first one has 104 characters and the second 101. Maybe your editor has the count incorrectly set? Or maybe I was looking at a different revision than you?
</blockquote></details>

I see, we're talking about different revisions. Reviewable showed me your comment over the code for r2 (which is properly wrapped), but there is a small "r1" in the corner. Next time something like that happens, I'll know where to look :)

(I did post r2 before your comment, though, judging by the timestamps.)
___
*[LibOS/shim/src/fs/shim_dcache.c, line 126 at r3](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpIMRJ2qMUXoUa-gtK:-MYuVzCkEtudD7mPeds7:b-k93gqi) ([raw file](https://github.com/oscarlab/graphene/blob/0d8335b7ef5cf644ea6991b8ded3c7d2c2f58747/LibOS/shim/src/fs/shim_dcache.c#L126)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe a single underscore? It's not reserved if the second char is lowercase.
</blockquote></details>

Oh, that's good to know.
___
*[LibOS/shim/src/sys/shim_socket.c, line 436 at r4](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYtuvyV0DUkO0sEEy41:-MYuY7P48PUoK8mWEoyP:b-rajwva) ([raw file](https://github.com/oscarlab/graphene/blob/6bff9e6921538f2dfe060a6cff778e773bcfa624/LibOS/shim/src/sys/shim_socket.c#L436)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this really something we want to change? I'm fine with internal support for unlimited paths and only filtering them where original Linux interface does.
</blockquote></details>

I don't know. There are a few places where we allocate a buffer on stack, but they can be fixed to also use malloc (or even trim, in case of debugging output). @boryspoplawski @dimakuv What do you think?

And by the way, the same question applies to mount-relative path. Currently it has a limit of `STR_SIZE = 4096`. If it's better to construct it on-demand than store in the dentries, should it still have a limit?

(And for now, I'll remove this TODO. If this is not an obvious thing, then there's no point keeping it in a comment.)


<!-- Sent from Reviewable.io -->

2021-04-22 17:28 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 164 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYqby4HDR9iP3fx7_J8:-MYuawwA3oURra3NFNG7:ba80wni) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/src/fs/shim_dcache.c#L164)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I see, we're talking about different revisions. Reviewable showed me your comment over the code for r2 (which is properly wrapped), but there is a small "r1" in the corner. Next time something like that happens, I'll know where to look :)

(I did post r2 before your comment, though, judging by the timestamps.)
</blockquote></details>

Ah, seems we had a race condition, I didn't see that you pushed an update while I was reviewing :)
___
*[LibOS/shim/src/sys/shim_socket.c, line 436 at r4](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYtuvyV0DUkO0sEEy41:-MYubA6FEVbSPR831YVo:b-w1najs) ([raw file](https://github.com/oscarlab/graphene/blob/6bff9e6921538f2dfe060a6cff778e773bcfa624/LibOS/shim/src/sys/shim_socket.c#L436)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't know. There are a few places where we allocate a buffer on stack, but they can be fixed to also use malloc (or even trim, in case of debugging output). @boryspoplawski @dimakuv What do you think?

And by the way, the same question applies to mount-relative path. Currently it has a limit of `STR_SIZE = 4096`. If it's better to construct it on-demand than store in the dentries, should it still have a limit?

(And for now, I'll remove this TODO. If this is not an obvious thing, then there's no point keeping it in a comment.)
</blockquote></details>

I'd say we should keep such things on heap. 4KB is quite a lot, and it's easy to spin out of control and get stack overflow, especially in non-main threads, which has smaller and non-growable stacks.


<!-- Sent from Reviewable.io -->

2021-04-22 19:41 UTC, boryspoplawski requested changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 423 at r1](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoJb0l87dUQAgYM2wj:-MYulVp-2h0AWFHKtSdp:boui2t) ([raw file](https://github.com/oscarlab/graphene/blob/feae2d7794a9c75ea5e6814d5745416fec78756e/LibOS/shim/include/shim_fs.h#L423)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

TBH that doesn't sound important, every reference is counted, so it's obvious that if `parent` got one, then the ref count was increased as well. The only thing that may be worth mentioning (but might be obvious too, idk) is that we pass the ownership of the returned pointer to the caller (i.e. it's a new pointer which caller will be now owner of).
(not blocking - the current version has all information needed as well)
___
*[LibOS/shim/include/shim_fs.h, line 438 at r5](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYukMsj-dTYrLGK80D4:-MYukMsj-dTYrLGK80D5:b-5u2qw9) ([raw file](https://github.com/oscarlab/graphene/blob/0e7ad02c6ed35f1e3cd36b56a49a979dc415f92d/LibOS/shim/include/shim_fs.h#L438)):*
> ```objc
> /*!
>  * \brief Allocate and initialize a new dentry for path name, under parent. The caller should hold
>  * `g_dcache_lock`.
> ```

I think info about locks fits better in general description, not `brief`.
___
*[LibOS/shim/include/shim_fs.h, line 447 at r5](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYuksSz6cB0YDF91B9V:-MYuksT-7yp38GVbMrCN:b-13z9md) ([raw file](https://github.com/oscarlab/graphene/blob/0e7ad02c6ed35f1e3cd36b56a49a979dc415f92d/LibOS/shim/include/shim_fs.h#L447)):*
> ```objc
>  * \returns the new dentry, or NULL in case of allocation failure
>  *
>  * The function will initialize `fs` (if provided), `name`, `rel_path`, and parent/children links.
> ```

This is confusing (at least to me): you mean `fs` (as in pointer passed to this function) or `dent->fs`? (I guess the latter)
___
*[LibOS/shim/src/fs/shim_dcache.c, line 126 at r3](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYpIMRJ2qMUXoUa-gtK:-MYur5xpAEHNahr02Zyr:bvg46fs) ([raw file](https://github.com/oscarlab/graphene/blob/0d8335b7ef5cf644ea6991b8ded3c7d2c2f58747/LibOS/shim/src/fs/shim_dcache.c#L126)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh, that's good to know.
</blockquote></details>

Yeah, in the new code we tend to use one underscore.
I personally add a leading underscore only if we have 2 functions, doing basically the same thing and one of them assumes that a lock is taken (with `_`) and the other that it's not taken (the one without `_`).
___
*[LibOS/shim/src/fs/shim_dcache.c, line 175 at r5](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYuusYjDCvbwMDZZdHX:-MYuusYjDCvbwMDZZdHY:b-y4j50z) ([raw file](https://github.com/oscarlab/graphene/blob/0e7ad02c6ed35f1e3cd36b56a49a979dc415f92d/LibOS/shim/src/fs/shim_dcache.c#L175)):*
> ```C
>     if (parent) {
>         /* Increment both dentries' ref counts, because they will be linked (through `dent->parent`
>          * and `parent->children`) */
> ```

NP: if you would move each `get_dentry` after corresponding copy, then this comment would be obvious and unnecessary.
___
*[LibOS/shim/src/sys/shim_socket.c, line 436 at r4](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYtuvyV0DUkO0sEEy41:-MYuiPPl19OdUrHx4SYw:b-56gvkq) ([raw file](https://github.com/oscarlab/graphene/blob/6bff9e6921538f2dfe060a6cff778e773bcfa624/LibOS/shim/src/sys/shim_socket.c#L436)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd say we should keep such things on heap. 4KB is quite a lot, and it's easy to spin out of control and get stack overflow, especially in non-main threads, which has smaller and non-growable stacks.
</blockquote></details>

Even if we had any limits, allocating 4kb on stack is not a good thing to do (as @mkow mentioned above). Also in most cases these paths are small (or at least well below 4k), so no point in storing such huge buffers.


<!-- Sent from Reviewable.io -->

2021-04-23 07:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_fs.h, line 438 at r5](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYukMsj-dTYrLGK80D4:-MYx_lNxBf4wCoqOBO7w:b-58vy0b) ([raw file](https://github.com/oscarlab/graphene/blob/0e7ad02c6ed35f1e3cd36b56a49a979dc415f92d/LibOS/shim/include/shim_fs.h#L438)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I think info about locks fits better in general description, not `brief`.
</blockquote></details>

OK, moved to description.
___
*[LibOS/shim/include/shim_fs.h, line 447 at r5](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYuksSz6cB0YDF91B9V:-MYx_yLp6Wd1n4Sg5aII:b-dif9sb) ([raw file](https://github.com/oscarlab/graphene/blob/0e7ad02c6ed35f1e3cd36b56a49a979dc415f92d/LibOS/shim/include/shim_fs.h#L447)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is confusing (at least to me): you mean `fs` (as in pointer passed to this function) or `dent->fs`? (I guess the latter)
</blockquote></details>

Reworded to make it clear it's about fields.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 175 at r5](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYuusYjDCvbwMDZZdHX:-MYxaV2H1daeNMtl1kHe:bk95eja) ([raw file](https://github.com/oscarlab/graphene/blob/0e7ad02c6ed35f1e3cd36b56a49a979dc415f92d/LibOS/shim/src/fs/shim_dcache.c#L175)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: if you would move each `get_dentry` after corresponding copy, then this comment would be obvious and unnecessary.
</blockquote></details>

Right, I moved the `get_dentry`s around so that it's clear.


<!-- Sent from Reviewable.io -->

2021-04-23 11:10 UTC, dimakuv approved these changes
> Reviewed 1 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_fs.h, line 415 at r6](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYyPxMf3PXu_ZJ_r1Nx:-MYyPxMf3PXu_ZJ_r1Ny:b-flpoi3) ([raw file](https://github.com/oscarlab/graphene/blob/2c875af06ffe36f8ca8a98b032cb1334257f5797/LibOS/shim/include/shim_fs.h#L415)):*
> ```objc
>  * \endcode
>  */
> void dentry_gc(struct shim_dentry* dent);
> ```

This is cool! Nice idea.
___
*[LibOS/shim/src/sys/shim_socket.c, line 436 at r4](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYtuvyV0DUkO0sEEy41:-MYyPn5C1ncP__d3KhVY:b-5hegyc) ([raw file](https://github.com/oscarlab/graphene/blob/6bff9e6921538f2dfe060a6cff778e773bcfa624/LibOS/shim/src/sys/shim_socket.c#L436)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Even if we had any limits, allocating 4kb on stack is not a good thing to do (as @mkow mentioned above). Also in most cases these paths are small (or at least well below 4k), so no point in storing such huge buffers.
</blockquote></details>

I'm absolutely fine with mallocs everywhere and having unlimited paths.


<!-- Sent from Reviewable.io -->

2021-04-23 13:15 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-04-23 16:17 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYzUz0J-PWfJ52I4bkw:-MYzUz0K92t4pbUFwMaI:byvlmnj) (no related file):*
By the way, I'm experimenting with visualising the dentry tree. I'll submit some code with the next PR. Here is an example state after running `./pal_loader busybox ls /lib`:

```
[P64909:T1:busybox] [chroot V..S 10] * /
[P64909:T1:busybox] [  proc V..S  1] *   proc/
[P64909:T1:busybox] [   dev V..S  3] *   dev/
[P64909:T1:busybox] [chroot V.IS  3] *     tty
[P64909:T1:busybox] [   sys V..S  1] *   sys/
[P64909:T1:busybox] [chroot VLIS 26] *   lib/
[P64909:T1:busybox] [chroot V.IS  1] *     x86_64-linux-gnu/
[P64909:T1:busybox] [chroot V.I.  3]       ld-linux-x86-64.so.2
[P64909:T1:busybox] [chroot V.I.  2]       libm.so.6
[P64909:T1:busybox] [chroot V.I.  2]       libresolv.so.2
[P64909:T1:busybox] [chroot V.I.  2]       libc.so.6
[P64909:T1:busybox] [chroot V.I.  1]       pal-Linux-SGX
[P64909:T1:busybox] [chroot V.I.  1]       libnss_dns.so.2
[P64909:T1:busybox] [chroot V.I.  1]       Makefile
[P64909:T1:busybox] [chroot V.I.  1]       meson.build
[P64909:T1:busybox] [chroot V.I.  1]       libthread_db.so.1
[P64909:T1:busybox] [chroot V.I.  1]       libdl.so.2
[P64909:T1:busybox] [chroot V.I.  1]       libutil.so.1
[P64909:T1:busybox] [chroot V.I.  1]       pal-Linux
[P64909:T1:busybox] [chroot V.I.  1]       libpal-Linux.so
[P64909:T1:busybox] [chroot V.I.  1]       librt.so.1
[P64909:T1:busybox] [chroot V.I.  1]       libpal-Linux-SGX.so
[P64909:T1:busybox] [chroot V.I.  1]       crtn.o
[P64909:T1:busybox] [chroot V.I.  1]       crt1.o
[P64909:T1:busybox] [chroot V.I.  1]       libsysdb.a
[P64909:T1:busybox] [chroot V.I.  1]       libsysdb.so
[P64909:T1:busybox] [chroot V.I.  1]       libc.so
[P64909:T1:busybox] [chroot V.I.  1]       crti.o
[P64909:T1:busybox] [chroot V.I.  1]       libpthread.so.0
[P64909:T1:busybox] [chroot V...  1]       .gitignore
[P64909:T1:busybox] [chroot V.I.  1]       pal_loader
[P64909:T1:busybox] [chroot V.IS  2] *   etc/
[P64909:T1:busybox] [chroot V...  1]  -    ld.so.preload
[P64909:T1:busybox] [chroot V...  2]     busybox
```

(`*` is mountpoint, `-` is negative, remaining flags are `V`alid, `L`isted, `I`no updated, `S`ynthetic)

---


<!-- Sent from Reviewable.io -->

2021-04-23 20:41 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYzUz0J-PWfJ52I4bkw:-MZ-ScfBAo5tRPbkMHp_:b-ed0vma) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

By the way, I'm experimenting with visualising the dentry tree. I'll submit some code with the next PR. Here is an example state after running `./pal_loader busybox ls /lib`:

```
[P64909:T1:busybox] [chroot V..S 10] * /
[P64909:T1:busybox] [  proc V..S  1] *   proc/
[P64909:T1:busybox] [   dev V..S  3] *   dev/
[P64909:T1:busybox] [chroot V.IS  3] *     tty
[P64909:T1:busybox] [   sys V..S  1] *   sys/
[P64909:T1:busybox] [chroot VLIS 26] *   lib/
[P64909:T1:busybox] [chroot V.IS  1] *     x86_64-linux-gnu/
[P64909:T1:busybox] [chroot V.I.  3]       ld-linux-x86-64.so.2
[P64909:T1:busybox] [chroot V.I.  2]       libm.so.6
[P64909:T1:busybox] [chroot V.I.  2]       libresolv.so.2
[P64909:T1:busybox] [chroot V.I.  2]       libc.so.6
[P64909:T1:busybox] [chroot V.I.  1]       pal-Linux-SGX
[P64909:T1:busybox] [chroot V.I.  1]       libnss_dns.so.2
[P64909:T1:busybox] [chroot V.I.  1]       Makefile
[P64909:T1:busybox] [chroot V.I.  1]       meson.build
[P64909:T1:busybox] [chroot V.I.  1]       libthread_db.so.1
[P64909:T1:busybox] [chroot V.I.  1]       libdl.so.2
[P64909:T1:busybox] [chroot V.I.  1]       libutil.so.1
[P64909:T1:busybox] [chroot V.I.  1]       pal-Linux
[P64909:T1:busybox] [chroot V.I.  1]       libpal-Linux.so
[P64909:T1:busybox] [chroot V.I.  1]       librt.so.1
[P64909:T1:busybox] [chroot V.I.  1]       libpal-Linux-SGX.so
[P64909:T1:busybox] [chroot V.I.  1]       crtn.o
[P64909:T1:busybox] [chroot V.I.  1]       crt1.o
[P64909:T1:busybox] [chroot V.I.  1]       libsysdb.a
[P64909:T1:busybox] [chroot V.I.  1]       libsysdb.so
[P64909:T1:busybox] [chroot V.I.  1]       libc.so
[P64909:T1:busybox] [chroot V.I.  1]       crti.o
[P64909:T1:busybox] [chroot V.I.  1]       libpthread.so.0
[P64909:T1:busybox] [chroot V...  1]       .gitignore
[P64909:T1:busybox] [chroot V.I.  1]       pal_loader
[P64909:T1:busybox] [chroot V.IS  2] *   etc/
[P64909:T1:busybox] [chroot V...  1]  -    ld.so.preload
[P64909:T1:busybox] [chroot V...  2]     busybox
```

(`*` is mountpoint, `-` is negative, remaining flags are `V`alid, `L`isted, `I`no updated, `S`ynthetic)
</blockquote></details>

Wow, that looks awesome! (and ofc very useful!)

---


<!-- Sent from Reviewable.io -->

2021-04-23 21:33 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-26 12:36 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-26 12:44 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-26 12:45 UTC, merged

2021-04-30 16:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MZYaER-9f0UXR5aRvkl:bktk0ai) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Well, that's a hack/feature that is allowed by our current FS mount point semantics.

I'd say it's a feature, I think on Linux you can also mount single files.

> But this abusing of /dev can be removed if it is too hacky.

In this case it's not abusing it, it's just a bug that this is possible.

Anyways, I see that you just misunderstood Paweł :)

> Imo there should be no default main-exec mounting. If you want to run something mount it explicitly. We should also get rid of this mounting host `.` as `/` completely.

+1, although the main-exec is not "mounted", it's just the current directory which is (I think).
</blockquote></details>

Several branches later, I finally hit that again... It looks like this worked because a dentry for executable was created sort of "on the side", not in the actual dentry tree.

The gory details: https://github.com/oscarlab/graphene/pull/2342/commits/441ef9cfd8e881ad507d608031b2aa851db40788

(part of upcoming PR #2342)

---


<!-- Sent from Reviewable.io -->

2021-04-30 22:57 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2324)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2324#-MYoHUzRBFUHXfXESVE4:-MZZzyXz9VffmZXadHW_:bg2mzue) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Several branches later, I finally hit that again... It looks like this worked because a dentry for executable was created sort of "on the side", not in the actual dentry tree.

The gory details: https://github.com/oscarlab/graphene/pull/2342/commits/441ef9cfd8e881ad507d608031b2aa851db40788

(part of upcoming PR #2342)
</blockquote></details>

yay, finally fixed! this mess was really annoying :)

---


<!-- Sent from Reviewable.io -->