[Pal/Linux-SGX] Add `sgx_seal_key_mr{enclave,signer}` manifest options
oscarlab/graphene pull request #2328
Opened 2021-04-23 07:40 UTC by dimakuv

## Description of the changes 

Previously, only `sgx.protected_files_key = "[16-byte hex value]"` was allowed in the manifest (i.e., hard-coding the master key for protected-files encryption). This could only be used for debugging purposes and never in production.

This commit adds two more options to this manifest config: `"sgx_seal_key_mrenclave"` and `"sgx_seal_key_mrsigner"`. They specify that the key is generated via SGX instruction `EGETKEY(SEAL_KEY)`, bound to the MRENCLAVE/MRSIGNER enclave measurement (so that only instances of the same enclave/only enclaves with the same signer may decrypt protected files). This allows to seal data files.

A corresponding LibOS test is added and documentation is updated to reflect this. Also, internal doc on Protected Files was updated (unrelated, so in a separate commit).

## How to test this PR? 

A corresponding LibOS test is added.

2021-04-23 07:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2328)* status: 0 of 11 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[LibOS/shim/test/regression/.gitignore, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2328#-MYxfQC41oOM619cCkyb:-MYxfQC41oOM619cCkyc:bt69z10) ([raw file](https://github.com/oscarlab/graphene/blob/73276fdb4c3fb6747cb6c34d8b2839b296065d0f/LibOS/shim/test/regression/.gitignore#L114)):*
> ```ignore
> /tcp_ipv6_v6only
> /tcp_msg_peek
> /testfile
> ```

FYI: This is a text file, not an executable. So I moved it to a separate sub-list.
___
*[LibOS/shim/test/regression/manifest.template, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2328#-MYxfWeU13WwhhrvIxcH:-MYxfWeU13WwhhrvIxcI:b-ubf5ws) ([raw file](https://github.com/oscarlab/graphene/blob/da67f982fe6a6b3119619acd9e098d49d83b78ea/LibOS/shim/test/regression/manifest.template#L42)):*
> ```
> # for protected_file test
> sgx.protected_files_key = "sgx_seal_key_mrenclave"
> sgx.protected_files.pffile = "file:protected_file.dat"
> ```

FYI: Note that this file cannot go under `tmp/` because that directory is in `allowed_files`.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/2328#-MYxfkaoE6xdXVX88_bS:-MYxfkaoE6xdXVX88_bT:b53pc54) ([raw file](https://github.com/oscarlab/graphene/blob/da67f982fe6a6b3119619acd9e098d49d83b78ea/Pal/src/host/Linux-SGX/enclave_framework.c#L226)):*
> ```C
>      * enclave). The rest of the keyrequest fields are currently zeros -- CET attributes, enclave
>      * ATTRIBUTES, enclave MISCSELECT bits are *not* included in key derivation. KEYID is also zero,
>      * to generate the same sealing key in different instances of the same enclave/same signer. */
> ```

FYI: This may require some discussions, but these configurations seem the most adequate.

For details, I recommend Sections 37.18, 38.4.3.1 from the Intel SDM. And also https://www.felixcloutier.com/x86/egetkey.
___
*[Pal/src/host/Linux-SGX/protected-files/README.rst, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2328#-MYxgKqY5N28AMaUu0Sq:-MYxgKqY5N28AMaUu0Sr:b-8k5029) ([raw file](https://github.com/oscarlab/graphene/blob/73276fdb4c3fb6747cb6c34d8b2839b296065d0f/Pal/src/host/Linux-SGX/protected-files/README.rst#L1)):*
> ```reStructuredText
> ===============
> ```

FYI: I just noticed that we have this file :) It describes the internals and some TODOs/details regarding the Protected Files. So the file itself seems useful, but also not quite ready for its own readthedocs page...

So I decided to simply remove redundant info and update it slightly. I would be fine with deleting it completely. (We will need a proper page in our docs describing Protected Files and its design anyway...)


<!-- Sent from Reviewable.io -->

2021-04-25 06:14 UTC, llly reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2328)* status: 0 of 13 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/2328#-MYxfkaoE6xdXVX88_bS:-MZ6cDOe-d2ychNFOZmS:bmiluk8) ([raw file](https://github.com/oscarlab/graphene/blob/da67f982fe6a6b3119619acd9e098d49d83b78ea/Pal/src/host/Linux-SGX/enclave_framework.c#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This may require some discussions, but these configurations seem the most adequate.

For details, I recommend Sections 37.18, 38.4.3.1 from the Intel SDM. And also https://www.felixcloutier.com/x86/egetkey.
</blockquote></details>

LGTM. This key used in Graphene protected files are key derivation key instead of seal key. Nonces/KEYIDs  are added by KDF to avoid replay attack.


<!-- Sent from Reviewable.io -->

2021-05-10 22:37 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2328)* status: 0 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 484 at r2](https://reviewable.io/reviews/oscarlab/graphene/2328#-M_NPhVeBn6X8MWKNv-D:-M_NPhVeBn6X8MWKNv-E:b-9fo778) ([raw file](https://github.com/oscarlab/graphene/blob/15a337ee8885ecbd1a36071a021576f373330eaf/Documentation/manifest-syntax.rst#L484)):*
> ```reStructuredText
>   MRSIGNER enclave measurement (so that only enclaves with the same signer may
>   decrypt protected files). Note that enclave's CPU/ISV/CONFIG SVNs are also
>   used for protected files key derivation.
> ```

Now that I look at this and the original PF design, it seems to me that we may need a change: I think the key config should be a per-mount property, otherwise this sealing is quite useless - if you seal any data, then you can't use runtime encryption (the traditional PFs).
___
*[Documentation/manifest-syntax.rst, line 489 at r2](https://reviewable.io/reviews/oscarlab/graphene/2328#-M_NOIPED5CPpnqmuprt:-M_NOIPED5CPpnqmupru:b-1ei72j) ([raw file](https://github.com/oscarlab/graphene/blob/15a337ee8885ecbd1a36071a021576f373330eaf/Documentation/manifest-syntax.rst#L489)):*
> ```
> ``sgx.protected_files_key = "sgx_seal_key_mrenclave"``
> ``sgx.protected_files_key = "sgx_seal_key_mrsigner"``
> ``sgx.protected_files_key = "[16-byte hex value]"``
> ```

Too hacky, plz don't :)
___
*[Pal/src/host/Linux/db_rtld.c, line 143 at r2](https://reviewable.io/reviews/oscarlab/graphene/2328#-M_NQDRa1y-5EqdqTEr9:-M_NQDRbE1HYAM06npzL:b-378c3m) ([raw file](https://github.com/oscarlab/graphene/blob/15a337ee8885ecbd1a36071a021576f373330eaf/Pal/src/host/Linux/db_rtld.c#L143)):*
> ```C
>             INLINE_SYSCALL(getpid, 0), INLINE_SYSCALL(gettid, 0), (void*)vdso_start);
>     log_error("+++++ setup_vdso_map (PID = %ld, TID = %ld): vdso_clock_gettime = %p +++++\n",
>             INLINE_SYSCALL(getpid, 0), INLINE_SYSCALL(gettid, 0), g_linux_state.vdso_clock_gettime);
> ```

debugging leftovers?


<!-- Sent from Reviewable.io -->

2021-05-11 06:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2328)* status: 0 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 484 at r2](https://reviewable.io/reviews/oscarlab/graphene/2328#-M_NPhVeBn6X8MWKNv-D:-M_PBSHmBAzHgxjr9oyn:b-io12od) ([raw file](https://github.com/oscarlab/graphene/blob/15a337ee8885ecbd1a36071a021576f373330eaf/Documentation/manifest-syntax.rst#L484)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now that I look at this and the original PF design, it seems to me that we may need a change: I think the key config should be a per-mount property, otherwise this sealing is quite useless - if you seal any data, then you can't use runtime encryption (the traditional PFs).
</blockquote></details>

I agree that ideally we should be able to encrypt files in different ways: some files using SGX sealing, some files using the provisioned key.

But I don't like the "per-mount" idea. We only have FS mounts at the level of LibOS; this detail is completely oblivious to the PAL layer (where Protected Files sits). We don't want to break this encapsulation...

Maybe we should introduce `sgx.sealed_files`? Actually, two flavours:
- `sgx.sealed_mrenclave_files`
- `sgx.sealed_mrsigner_files`

But this goes significantly out of scope of this PR. Well, now that I'm thinking of it... This will actually be a better implementation, this will be sufficiently simple to implement, and this will be per-file (which is typically what is needed for sealing).

@mkow What do you think about the proposal? I agree that I should probably close this PR and submit a new one, with a more flexible sealing scheme.
___
*[Documentation/manifest-syntax.rst, line 489 at r2](https://reviewable.io/reviews/oscarlab/graphene/2328#-M_NOIPED5CPpnqmuprt:-M_PCtJL6k2HgB1ovh6G:b-uy52pt) ([raw file](https://github.com/oscarlab/graphene/blob/15a337ee8885ecbd1a36071a021576f373330eaf/Documentation/manifest-syntax.rst#L489)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> ``sgx.protected_files_key = "sgx_seal_key_mrenclave"``
> ``sgx.protected_files_key = "sgx_seal_key_mrsigner"``
> ``sgx.protected_files_key = "[16-byte hex value]"``
> ```

Too hacky, plz don't :)
</blockquote></details>

Yeah, agreed. I will remove this hack, based on the decision in the above comment.
___
*[Pal/src/host/Linux/db_rtld.c, line 143 at r2](https://reviewable.io/reviews/oscarlab/graphene/2328#-M_NQDRa1y-5EqdqTEr9:-M_PCxZ20kIKYdhE0NYL:b-k7qrz6) ([raw file](https://github.com/oscarlab/graphene/blob/15a337ee8885ecbd1a36071a021576f373330eaf/Pal/src/host/Linux/db_rtld.c#L143)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

debugging leftovers?
</blockquote></details>

The second commit is a `DONTMERGE` commit where I tested a bug in vDSO. This commit will be removed from the final PR.


<!-- Sent from Reviewable.io -->

2021-05-11 10:00 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2328)* status: 0 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/manifest-syntax.rst, line 484 at r2](https://reviewable.io/reviews/oscarlab/graphene/2328#-M_NPhVeBn6X8MWKNv-D:-M_Pr0ZA8_5TmFvEUaf_:b-76wgb7) ([raw file](https://github.com/oscarlab/graphene/blob/15a337ee8885ecbd1a36071a021576f373330eaf/Documentation/manifest-syntax.rst#L484)):*
> @mkow What do you think about the proposal? I agree that I should probably close this PR and submit a new one, with a more flexible sealing scheme.

+1 from my side


<!-- Sent from Reviewable.io -->

2021-06-07 09:37 UTC, sammyne commented
This pending PR should ease the sealing based on MRENCLAVE or MRSIGNER.
Why is the merging suspended? @dimakuv

2021-06-07 20:19 UTC, dimakuv commented
@sammyne We decided to go with another, more flexible approach. See my previous comment:

> Maybe we should introduce sgx.sealed_files? Actually, two flavours:
> - sgx.sealed_mrenclave_files
> - sgx.sealed_mrsigner_files
>
> But this goes significantly out of scope of this PR. Well, now that I'm thinking of it... This will actually be a better implementation, this will be sufficiently simple to implement, and this will be per-file (which is typically what is needed for sealing).

So this PR will be closed when I will submit a new PR with such changes. However, I haven't had the time to actually implement such a PR...

2021-06-29 11:13 UTC, dimakuv reviewed
This PR will be closed now. I split this PR into two and created new ones:
- https://github.com/oscarlab/graphene/pull/2484
- https://github.com/oscarlab/graphene/pull/2482

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2328#-:-MdMT4hh14nk3Veu9Upt:bcsk47n)* status: 0 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " and "DONTMERGE" found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-06-29 11:13 UTC, closed without merging