[LibOS]: Partial implementation of `getcpu` syscall
oscarlab/graphene pull request #2331
Opened 2021-04-25 22:34 UTC by vijaydhanraj

## Description of the changes 

This patch adds a partial implementation of `getcpu` syscall that returns a random set bit from the first non-empty cpu affinity mask. `pthread_set_get_affinity` regression test is extended to validate this implementation. This patch also enables the `getcpu01` ltp test for non-SGX case.

## How to test this PR? 
Please run `pthread_set_get_affinity` regression test to validate this PR.

2021-04-26 08:20 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZC9_W7-sUeole-tk8h:-MZC9_W7-sUeole-tk8i:b70wfr4) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L226)):*
> ```C
> 
> #define CPUMASK_SETSIZE 1024
> #define CPUBITS         (8 * sizeof (unsigned long))
> ```

No space after `sizeof`
___
*[LibOS/shim/src/sys/shim_sched.c, line 227 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZC9RAi8FAIL-LhPiEB:-MZC9RAi8FAIL-LhPiEC:b-lgmknc) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L227)):*
> ```C
> #define CPUMASK_SETSIZE 1024
> #define CPUBITS         (8 * sizeof (unsigned long))
> #define NUM_MASKS       (CPUMASK_SETSIZE / CPUBITS)
> ```

Don't we have these constants in one of our header files? If not, can we add them in the header file instead of declaring them here. Seems useful for other purposes.

Actually, why do you need these constants? Aren't you supposed to use `bitmask_size_in_bytes`? See comments below.
___
*[LibOS/shim/src/sys/shim_sched.c, line 229 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZC9OHt2qHxmtNZ99In:-MZC9OHt2qHxmtNZ99Io:b-uvmfog) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L229)):*
> ```C
> #define NUM_MASKS       (CPUMASK_SETSIZE / CPUBITS)
> 
> /* dummy implementation: always return cpu0  */
> ```

Can you remove this comment? It's not correct now.
___
*[LibOS/shim/src/sys/shim_sched.c, line 244 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCCOHz8RbBk4HKYDEU:-MZCCOHz8RbBk4HKYDEV:b5bn85d) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L244)):*
> ```C
>         get_thread(thread);
> 
>         if (is_internal(thread)) {
> ```

Can you add the comment here:
```
    /* Internal graphene threads are not affinitized; if we hit an internal thread here, this is
       some bug in user app. */
```
___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-MZCD3JAC8z-rsY_-vZ0:b-xph8tk) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
> ```C
>         }
> 
>         unsigned long mask[NUM_MASKS] = {0};
> ```

Why are you using `NUM_MASKS` instead of `bitmask_size_in_bytes / sizeof(unsigned long)`? Otherwise you may have a situation where `bitmask_size_in_bytes` shows something like 32 bytes, but your `mask` is only 16 bytes. So you will have a buffer overflow.
___
*[LibOS/shim/src/sys/shim_sched.c, line 255 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCF39RAzyqNj9YKxV_:-MZCF39RAzyqNj9YKxVa:b-tx6ylv) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L255)):*
> ```C
>             return pal_to_unix_errno(ret);
>         }
> ```

Technically, you can add `put_thread(thread)` here because you're not using `thread` below. This will simplify some of your error returns.
___
*[LibOS/shim/src/sys/shim_sched.c, line 257 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDc8h5bXZ6hsMFVy9:-MZCDZWh2c2gHvxxB4Bl:b7erro9) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L257)):*
> ```C
> 
>         /* Find first non-empty cpumask and get the no. of bits set */
>         unsigned int num_bits[NUM_MASKS] = {0};
> ```

Why do you need an array? You're simply iterating through `mask[i]` and finding a non-empty mask. Then you memorize the number of bits in this non-empty mask, that's it. No need for an array, simply `unsigned int num_bits = 0`.
___
*[LibOS/shim/src/sys/shim_sched.c, line 263 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDsqH8bMZaUJAN3ht:-MZCDsqH8bMZaUJAN3hu:bsy0mrx) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L263)):*
> ```C
>             if (num_bits[idx])
>                 break;
>         }
> ```

No reason for a `for` loop, `while` is more readable here.
___
*[LibOS/shim/src/sys/shim_sched.c, line 264 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDxotBBw1jAep2QMt:-MZCDxotBBw1jAep2QMu:b-yjdhxt) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L264)):*
> ```C
>                 break;
>         }
> ```

After the loop, you should check that you actually have `idx` and `num_bits` set to adequate values (maybe your whole mask is zeros? there is no check for this in your code).
___
*[LibOS/shim/src/sys/shim_sched.c, line 265 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCE7zW-U15B9es6yNK:-MZCE7zW-U15B9es6yNL:bpvfs2o) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L265)):*
> ```C
>         }
> 
>         /* Generate a random no. and use it to find a random set bit in the cpumask */
> ```

Please don't use `no.`. I am not sure if this is an Americanism, but my brain always stumbles on this. Simply `number`.
___
*[LibOS/shim/src/sys/shim_sched.c, line 269 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDUscEqZ8bcdci2Wp:-MZCDUscEqZ8bcdci2Wq:b2yau1d) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L269)):*
> ```C
>         ret = DkRandomBitsRead(&rand_num, sizeof(rand_num));
>         if (ret < 0) {
>             return pal_to_unix_errno(ret);
> ```

You forgot to `put_thread()` here.
___
*[LibOS/shim/src/sys/shim_sched.c, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEK2W6n0kQCWgdclU:-MZCEK2W6n0kQCWgdclV:bslbzqh) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L272)):*
> ```C
>         }
> 
>         int nth_setbit = (num_bits[idx] == 1) ? 0 : (rand_num % (num_bits[idx] - 1) + 1);
> ```

Why this complex logic? Why not simply `rand_num % num_bits`? (Of course, you need a check beforehand that `num_bits > 0`, otherwise return `-EINVAL`.)
___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZCEhaj3_HdJ5hJP2t4:brfgzfj) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
> ```C
>         for (int j =0; j < nth_setbit; j++) {
>             cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask));
>         }
> ```

What is happening in this loop? Why? This whole loop doesn't make sense to me, why not simply remove it and use the arithmetic below?
___
*[LibOS/shim/test/ltp/ltp.cfg, line 705 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZC5KNpCoCfLsv5XfeI:-MZC5KNq9UfVvIgZLzx1:bs43t6a) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/test/ltp/ltp.cfg#L705)):*
> ```INI
> # getcpu() always returns cpu0
> [getcpu01]
> skip = no
> ```

You should simply remove these three lines, then the test is run by default.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCFcMzCnPHq-Vv2UfF:-MZCFcMzCnPHq-Vv [...]

2021-04-27 00:42 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 0 of 3 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 226 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZC9_W7-sUeole-tk8h:-MZEWNsjDlCHCSwiu2AR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L226)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No space after `sizeof`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 229 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZC9OHt2qHxmtNZ99In:-MZEWYQhB1U9VUcu8PxL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you remove this comment? It's not correct now.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 244 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCCOHz8RbBk4HKYDEU:-MZEWlCw9DXU54SxUuQf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add the comment here:
```
    /* Internal graphene threads are not affinitized; if we hit an internal thread here, this is
       some bug in user app. */
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-MZElDr6CXoVM-uvaPAh:b-9ocobk) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why are you using `NUM_MASKS` instead of `bitmask_size_in_bytes / sizeof(unsigned long)`? Otherwise you may have a situation where `bitmask_size_in_bytes` shows something like 32 bytes, but your `mask` is only 16 bytes. So you will have a buffer overflow.
</blockquote></details>

This is to address cpu offlining case. Consider the example below where I have only 5 cpus as below and if I run 5 threads concurrently `getcpu` is expected to actual cpu number where threads are running. 
```
 vdhanraj@sdp  cat /sys/devices/system/cpu/online
0,31,63,96,127

 vdhanraj@sdp   ./sched_getcpu                    
Thread TID = 74986, is running on CPU = (sched_getcpu)63
Thread TID = 74983, is running on CPU = (sched_getcpu)96
Thread TID = 74984, is running on CPU = (sched_getcpu)127
Thread TID = 74985, is running on CPU = (sched_getcpu)31
Thread TID = 74987, is running on CPU = (sched_getcpu)96

```

In this case, if we end up using `bitmask_size_in_bytes  /  sizeof(unsigned long)`, that is mask[1] we cannot store higher-numbered cpus.
___
*[LibOS/shim/src/sys/shim_sched.c, line 255 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCF39RAzyqNj9YKxV_:-MZEqdf14a0DDJsq9tZG:b-tegtn4) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L255)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Technically, you can add `put_thread(thread)` here because you're not using `thread` below. This will simplify some of your error returns.
</blockquote></details>

you are right but to me having it in the end seems a little easier to read. But this is just my choice if needed I can move it here.
___
*[LibOS/shim/src/sys/shim_sched.c, line 257 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDc8h5bXZ6hsMFVy9:-MZErC50-7QQh2uergqq:b-r6j2iq) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L257)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need an array? You're simply iterating through `mask[i]` and finding a non-empty mask. Then you memorize the number of bits in this non-empty mask, that's it. No need for an array, simply `unsigned int num_bits = 0`.
</blockquote></details>

This is a residual code I will remove it. In my previous implementation I wanted to randomize the mask location as well, meaning we could pick any cpu present in any`mask[0] - mask[n]` so was storing the corresponding num_bits. But now I only select the first available cpumask and randomly select any cpu present.
___
*[LibOS/shim/src/sys/shim_sched.c, line 263 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDsqH8bMZaUJAN3ht:-MZEt7rQ-SGCgEZ1wTG_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L263)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No reason for a `for` loop, `while` is more readable here.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 264 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDxotBBw1jAep2QMt:-MZExeGg6OGzAOPL3A0V:b-ap8h7d) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L264)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

After the loop, you should check that you actually have `idx` and `num_bits` set to adequate values (maybe your whole mask is zeros? there is no check for this in your code).
</blockquote></details>

how about just adding `assert(num_bits)`? This should take care of the error case of `idx == NUM_MASKS` as well.
___
*[LibOS/shim/src/sys/shim_sched.c, line 265 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCE7zW-U15B9es6yNK:-MZExHu6ED_nqJ1IaVT1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L265)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't use `no.`. I am not sure if this is an Americanism, but my brain always stumbles on this. Simply `number`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 269 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDUscEqZ8bcdci2Wp:-MZF5Q4fAbBme_S_NOen:bn94qb6) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot to `put_thread()` here.
</blockquote></details>

yes missed it, I have added it now.
___
*[LibOS/shim/src/sys/shim_sched.c, line 272 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEK2W6n0kQCWgdclU:-MZFZnPs2gkyWrzgEVXq:bo06ix9) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L272)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this complex logic? Why not simply `rand_num % num_bits`? (Of course, you need a check beforehand that `num_bits > 0`, otherwise return `-EINVAL`.)
</blockquote></details>

please refer to the below for the explanation.
___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZF_5E92MDrYuOXCnNY:b-xm1tzh) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf [...]

2021-04-27 06:31 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-MZGxmf59f_4-f-jZWUb:bgwkp7) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is to address cpu offlining case. Consider the example below where I have only 5 cpus as below and if I run 5 threads concurrently `getcpu` is expected to actual cpu number where threads are running. 
```
 vdhanraj@sdp  cat /sys/devices/system/cpu/online
0,31,63,96,127

 vdhanraj@sdp   ./sched_getcpu                    
Thread TID = 74986, is running on CPU = (sched_getcpu)63
Thread TID = 74983, is running on CPU = (sched_getcpu)96
Thread TID = 74984, is running on CPU = (sched_getcpu)127
Thread TID = 74985, is running on CPU = (sched_getcpu)31
Thread TID = 74987, is running on CPU = (sched_getcpu)96

```

In this case, if we end up using `bitmask_size_in_bytes  /  sizeof(unsigned long)`, that is mask[1] we cannot store higher-numbered cpus.

</blockquote></details>

Ok, understood.

But then why do you need `bitmask_size_in_bytes` at all? Shouldn't you just pass `NUM_MASKS` below (in `DkThreadGetCpuAffinity()`)? Or am I misunderstanding the interfaces here?
___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZGzIyP1f8LUC9q_j2e:b-l3fyug) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

short answer:
If we remove the logic and use the just use arithmetic, we will always end up picking up the first set bit position from the cpumask. I wanted to randomly select a set cpu position from the mask.

long answer:
Basic idea is to find the `first` non-empty cpumask and then randomly select a CPU that is set. So based on the below figure we select mask[1] and then select any random cpu bit that is set. The way I randomly select a bit is as follows,
```
    +--------------------+
    |       64 bits      |  mask[0]=0x0
    |                    |
    +--------------------+
    |                    |
    |                    |  mask[1]= 0xFFFFFFFFFFFFFFFF
    +--------------------+
    |                    |
    |                    |
    |                    |
    +--------------------+
    |                    |
    |                    |  mask[n]
    +--------------------+

```

To find the random bit that is set in the selected cpumask I use `(num_bits == 1) ? 0 : (rand_num % (num_bits - 1) + 1)` where only if the number of bits set 1, I directly get its offset location (that is skip the loop) by ` __builtin_ctzl(cpumask) + (CPUBITS * idx);`. In all other cases, I don't want to pick the first set bit but shuffle. So I map it between `1-(num_bits-1)` and then randomly pick any of the set bit.

mapping numbers using `%` and `offset` is very common in random number generation so applied it. https://www.cs.fsu.edu/~vastola/cop3014/notes/rand.html (please refer to the last case).

BTW, `rand_num % num_bits` will work but will include 0 (which will select the first set bit without shuffling to find the random numbers). If it is complex will revert to `rand_num % num_bits`.

Once the random bit is selected I use the below logic to find the index. For example, if the cpumask has 5 bits and nth_setbit comes out as 4, the below logic will find the position of the last set bit in cpumask.
```
        for (int j =0; j < nth_setbit; j++) {
            cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask));
        }
```


</blockquote></details>

I still don't understand why so complex.

So you have these inputs:
- `cpumask` -- bitmask that contains some bits set
- `num_bits` -- number of bits set in `cpumask`
-  `rand_num` -- random number

Why can't do something like this:
```c
nth_setbit = (rand_num % num_bits) + 1;  /* we want to find the position of Nth bit set in cpumask */
bit_position = 0;
while (nth_setbit && cpumask) {
    if (cpumask & 1UL)
        nth_setbit--;  /* yet one more bit is set in cpumask, we are getting closer to Nth bit set */
    if (!nth_setbit)
        break;  /* we found the Nth bit set */
    cpumask = cpumask >> 1UL;  /* continue searching for set bits in cpumask (using lowest bit) */
    bit_position++;  /* shift bit position in cpumask */
}

*cpu = bit_position + CPUBITS * idx;
```
___
*[LibOS/shim/src/sys/shim_sched.c, line 257 at r2](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZGy6Y-5fkCUvlfVjIJ:-MZGy6Y-5fkCUvlfVjIK:bkhn7sk) ([raw file](https://github.com/oscarlab/graphene/blob/e331c8695812fa0268ee76f1df88aa9651b7525a/LibOS/shim/src/sys/shim_sched.c#L257)):*
> ```C
>         }
> 
>         /* Find first non-empty cpumask and get the no. of bits set */
> ```

`no.` -> `number`


<!-- Sent from Reviewable.io -->

2021-04-27 08:13 UTC, yamahata requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZHMEkY0dn0ZEUJIgu8:b-re0mzp) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still don't understand why so complex.

So you have these inputs:
- `cpumask` -- bitmask that contains some bits set
- `num_bits` -- number of bits set in `cpumask`
-  `rand_num` -- random number

Why can't do something like this:
```c
nth_setbit = (rand_num % num_bits) + 1;  /* we want to find the position of Nth bit set in cpumask */
bit_position = 0;
while (nth_setbit && cpumask) {
    if (cpumask & 1UL)
        nth_setbit--;  /* yet one more bit is set in cpumask, we are getting closer to Nth bit set */
    if (!nth_setbit)
        break;  /* we found the Nth bit set */
    cpumask = cpumask >> 1UL;  /* continue searching for set bits in cpumask (using lowest bit) */
    bit_position++;  /* shift bit position in cpumask */
}

*cpu = bit_position + CPUBITS * idx;
```
</blockquote></details>

what does randomization buy us? and why only in unsigned long?
How about using thread id?
___
*[LibOS/shim/src/sys/shim_sched.c, line 241 at r2](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZHMlvs0BXRW9LjNTbP:-MZHMlvs0BXRW9LjNTbQ:bxsrtn) ([raw file](https://github.com/oscarlab/graphene/blob/e331c8695812fa0268ee76f1df88aa9651b7525a/LibOS/shim/src/sys/shim_sched.c#L241)):*
> ```C
>         size_t bitmask_size_in_bytes = BITS_TO_LONGS(cpu_cnt) * sizeof(long);
>         struct shim_thread* thread = get_cur_thread();
>         get_thread(thread);
> ```

why do you need get_thread?


<!-- Sent from Reviewable.io -->

2021-04-27 20:14 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-MZJ_ZuH7W5lGyz0mgRs:b-nus3su) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, understood.

But then why do you need `bitmask_size_in_bytes` at all? Shouldn't you just pass `NUM_MASKS` below (in `DkThreadGetCpuAffinity()`)? Or am I misunderstanding the interfaces here?
</blockquote></details>

The second parameter of `DkThreadGetCpuAffinity()` represents the number of bytes to copy from the cpumask. `NUM_MAKS` represent the max number of cpumasks supported. Currently, in our code, it is `16`. This will work well if we have at max 128 cpus (16 * 8). If we have 256 cpus, we might end up losing higher-order set bits. `bitmask_size_in_bytes ` will take care of this case.
___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZJoBTG-VS1P5A_I9ME:b-fmzhnx) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

what does randomization buy us? and why only in unsigned long?
How about using thread id?

</blockquote></details>

@dimakuv  yes we can do it but why do we want to do this manually when we can use the `__builtin*` function? Isn't this more optimized? Please let me know what you feel is complex.

I felt this was more readable wherein each time you find the trailing zero count and shift to clear the set bit until you hit the desired set bit. But open to adopting your implementation if you feel this is more complex.
```
 for (int j = 0; j < nth_setbit; j++)
     cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask));
```

@yamahata `getcpu` syscall returns the cpu on which the calling thread is running. So if we have 2 threads that can run on any cpu, without randomization our implementation will end up getting the same cpu. 

Regarding `thread id` comment are you suggesting to use this instead of rand_num?
___
*[LibOS/shim/src/sys/shim_sched.c, line 241 at r2](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZHMlvs0BXRW9LjNTbP:-MZJv3og3F4S_GhigSjO:b-ihpsbx) ([raw file](https://github.com/oscarlab/graphene/blob/e331c8695812fa0268ee76f1df88aa9651b7525a/LibOS/shim/src/sys/shim_sched.c#L241)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

why do you need get_thread?
</blockquote></details>

Please correct me but my understanding is to increment the thread reference count inside the enclave before the `ocall`.
___
*[LibOS/shim/src/sys/shim_sched.c, line 257 at r2](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZGy6Y-5fkCUvlfVjIJ:-MZJgaO_DtQwQijOCFnT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e331c8695812fa0268ee76f1df88aa9651b7525a/LibOS/shim/src/sys/shim_sched.c#L257)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`no.` -> `number`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-28 01:55 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZL7sXB6BWTLbDEISLY:bp74ukw) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@dimakuv  yes we can do it but why do we want to do this manually when we can use the `__builtin*` function? Isn't this more optimized? Please let me know what you feel is complex.

I felt this was more readable wherein each time you find the trailing zero count and shift to clear the set bit until you hit the desired set bit. But open to adopting your implementation if you feel this is more complex.
```
 for (int j = 0; j < nth_setbit; j++)
     cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask));
```

@yamahata `getcpu` syscall returns the cpu on which the calling thread is running. So if we have 2 threads that can run on any cpu, without randomization our implementation will end up getting the same cpu. 

Regarding `thread id` comment are you suggesting to use this instead of rand_num?
</blockquote></details>

Then what will happen if two or more threads have the same cpu? Are you observing concrete (bad) app behavior with it?
If app doesn't respond to it in a bad way, there is no point for randomization (or any kind of twist).

Yes. Then it will be deterministic.
___
*[LibOS/shim/src/sys/shim_sched.c, line 241 at r2](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZHMlvs0BXRW9LjNTbP:-MZLASMV2QvGjLylQivN:buwbzba) ([raw file](https://github.com/oscarlab/graphene/blob/e331c8695812fa0268ee76f1df88aa9651b7525a/LibOS/shim/src/sys/shim_sched.c#L241)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Please correct me but my understanding is to increment the thread reference count inside the enclave before the `ocall`.
</blockquote></details>

It's current thread. So until thread_exit(), the reference count is guaranteed to be > = 1.


<!-- Sent from Reviewable.io -->

2021-04-28 03:54 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZLYgrk--Z6bDkY-YQ2:b-bqvnwr) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Then what will happen if two or more threads have the same cpu? Are you observing concrete (bad) app behavior with it?
If app doesn't respond to it in a bad way, there is no point for randomization (or any kind of twist).

Yes. Then it will be deterministic.
</blockquote></details>

I am not sure what the application expects. @mkow can you please provide some info on the nature of the test and the expectation. In my opinion, applications use `getcpu` to make per-cpu optimizations. If we provide the same cpu number for all the threads, it might defeat this purpose. 

Why do we want it to be deterministic? Let's say if the thread can is affinitized to 10 cpus, then it could run on any of those, and `getcpu` should return the corresponding cpu. If we want to be deterministic we could simply return the first set bit from the cpumask. Isn't it?

But agree that if the applications don't need this randomization we can always select the first available cpumask and return the 1st set bit in the cpumask. This will make implementation simpler.
___
*[LibOS/shim/src/sys/shim_sched.c, line 241 at r2](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZHMlvs0BXRW9LjNTbP:-MZLasoF3E1OR12CzrRm:btko3ez) ([raw file](https://github.com/oscarlab/graphene/blob/e331c8695812fa0268ee76f1df88aa9651b7525a/LibOS/shim/src/sys/shim_sched.c#L241)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

It's current thread. So until thread_exit(), the reference count is guaranteed to be > = 1.
</blockquote></details>

Ok, then I will go ahead and remove the `get_thread()` and `put_thread()` calls.


<!-- Sent from Reviewable.io -->

2021-04-28 06:44 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @vijaydhanraj, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-MZM7U5s52uXS46JcaoC:baittns) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The second parameter of `DkThreadGetCpuAffinity()` represents the number of bytes to copy from the cpumask. `NUM_MAKS` represent the max number of cpumasks supported. Currently, in our code, it is `16`. This will work well if we have at max 128 cpus (16 * 8). If we have 256 cpus, we might end up losing higher-order set bits. `bitmask_size_in_bytes ` will take care of this case.
</blockquote></details>

You math looks wrong. We have `NUM_MASKS = 16` and `unsigned long mask[NUM_MASKS]`. This means that `mask` contains `(16 * 64) = 1024` bits or 128 bytes. So it can hold up to 1024 CPUs.

Also, I still don't understand why buffer overflow can't happen in `DkThreadGetCpuAffinity()`. You give it a buffer of 1024 bits, but you say that the length is `bitmask_size_in_bytes` which could be e.g. `BITS_TO_LONGS(cpu_cnt) * sizeof(long) = BITS_TO_LONGS(2048) * 8 = 32 * 8 = 256` bytes (if `cpu_cnt = 2048`).

So it seems possible that you supply a 128-byte `mask` and also `bitmask_size_in_bytes = 256`. And you have a buffer overflow.
___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZM98oV1TVw9ocT-puc:bayb3kj) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
> Then what will happen if two or more threads have the same cpu?

@yamahata , two scenarios:
- If the application set affinity for these threads, then typically apps affinize different threads to different CPUs (or subsets of CPUs). Since this PR takes into account the affinity mask (see `DkThreadGetCpuAffinity` call), there will never be a case that two threads will have the same CPU.
- If the application doesn't set affinity for these threads, then yes, two threads can have the same CPU. So what, this is a legit possibility according to https://man7.org/linux/man-pages/man2/getcpu.2.html (`The caller must allow for the possibility that the information returned in cpu and node is no longer current by the time the call returns.`)

I like this randomization approach.

> Regarding thread id comment are you suggesting to use this instead of rand_num?

We definitely shouldn't do this. Then `set/get_cpuaffinity` and the consequent `getcpu` won't work as expected.
___
*[LibOS/shim/src/sys/shim_sched.c, line 280 at r3](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZMApeuBTYFD6Bixhva:-MZMApeuBTYFD6Bixhvb:bv4prwv) ([raw file](https://github.com/oscarlab/graphene/blob/fc92af15de221e4a37193d01a931d3e9b78b1f2f/LibOS/shim/src/sys/shim_sched.c#L280)):*
> ```C
>         for (int j = 0; j < nth_setbit; j++) {
>             cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask));
>         }
> ```

Ok, now I understand your logic, Vijay. Thanks for explanations. Let's do two things to make it more readable.

1. `int nth_setbit = rand_num % num_bits`. If `nth_setbit` calculates to 0 here, then there will be no additional shuffling (we skip the for loop), and the logic simply selects the first set bit in the cpumask. Which is perfectly fine.

2. For `cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask))` line, please explain its logic. Add a comment inside the for loop with smth like this: `/* at each iteration, find the lowest set bit in cpumask and unset it; this will bring us to the nth_setbit after nth_setbit iterations */`

What confused me is that there were no comments explaining this behavior. I think just by adding one suggested comment, the logic becomes clear.
___
*[LibOS/shim/src/sys/shim_sched.c, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZMD-oT2F-auRGjcroy:-MZMD-oT2F-auRGjcroz:bt18g5r) ([raw file](https://github.com/oscarlab/graphene/blob/fc92af15de221e4a37193d01a931d3e9b78b1f2f/LibOS/shim/src/sys/shim_sched.c#L282)):*
> ```C
>         }
> 
>         *cpu = __builtin_ctzl(cpumask) + (CPUBITS * idx);
> ```

No need for `(` and `)`.


<!-- Sent from Reviewable.io -->

2021-04-28 17:46 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-MZOAbonC_ExW8JslQs7:bgc6bga) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You math looks wrong. We have `NUM_MASKS = 16` and `unsigned long mask[NUM_MASKS]`. This means that `mask` contains `(16 * 64) = 1024` bits or 128 bytes. So it can hold up to 1024 CPUs.

Also, I still don't understand why buffer overflow can't happen in `DkThreadGetCpuAffinity()`. You give it a buffer of 1024 bits, but you say that the length is `bitmask_size_in_bytes` which could be e.g. `BITS_TO_LONGS(cpu_cnt) * sizeof(long) = BITS_TO_LONGS(2048) * 8 = 32 * 8 = 256` bytes (if `cpu_cnt = 2048`).

So it seems possible that you supply a 128-byte `mask` and also `bitmask_size_in_bytes = 256`. And you have a buffer overflow.
</blockquote></details>

Yes, the mask can hold 1024 but what I meant was the number of bytes to copy. If we set it as `NUM_MASK` we would end up copying only 128 bits as it is always fixed. But when we use `bitmask_size_in_bytes ` it will get adjusted according to the number of cpus. This should work fine when the number of cpus is less than or equal to 1024.

Now on a system that has actually 2048 cpus but when we pass a mask of 128 bytes (meaning can take only 1024 cpus), yes the buffer will overflow. How about we add the below error checking?

```
         size_t cpu_cnt = PAL_CB(cpu_info.online_logical_cores);
+        if (cpu_cnt > CPUMASK_SETSIZE) {
+            log_warning("Due to glibc limitation max supported CPUs is 1024. "
+                        "System CPU count is %ld\n", cpu_cnt);
+            return -EINVAL;
+        }
+
```

PS: The reason I set `#define CPUMASK_SETSIZE 1024` is to basically emulate `cpu_set_t` struct which has a size of 128 bytes or in other words can take up to  1024 cpus.
___
*[LibOS/shim/src/sys/shim_sched.c, line 280 at r3](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZMApeuBTYFD6Bixhva:-MZOQTFW1TMYBBkB8_I7:b-h43rks) ([raw file](https://github.com/oscarlab/graphene/blob/fc92af15de221e4a37193d01a931d3e9b78b1f2f/LibOS/shim/src/sys/shim_sched.c#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, now I understand your logic, Vijay. Thanks for explanations. Let's do two things to make it more readable.

1. `int nth_setbit = rand_num % num_bits`. If `nth_setbit` calculates to 0 here, then there will be no additional shuffling (we skip the for loop), and the logic simply selects the first set bit in the cpumask. Which is perfectly fine.

2. For `cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask))` line, please explain its logic. Add a comment inside the for loop with smth like this: `/* at each iteration, find the lowest set bit in cpumask and unset it; this will bring us to the nth_setbit after nth_setbit iterations */`

What confused me is that there were no comments explaining this behavior. I think just by adding one suggested comment, the logic becomes clear.
</blockquote></details>

Sounds good, done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 282 at r3](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZMD-oT2F-auRGjcroy:-MZOQYCW7-lC9pFSN3Qg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fc92af15de221e4a37193d01a931d3e9b78b1f2f/LibOS/shim/src/sys/shim_sched.c#L282)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `(` and `)`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-29 05:37 UTC, yamahata approved these changes, later dismissed
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZR2PxA7Xa9hUXsV1_V:bc5cn3k) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Then what will happen if two or more threads have the same cpu?

@yamahata , two scenarios:
- If the application set affinity for these threads, then typically apps affinize different threads to different CPUs (or subsets of CPUs). Since this PR takes into account the affinity mask (see `DkThreadGetCpuAffinity` call), there will never be a case that two threads will have the same CPU.
- If the application doesn't set affinity for these threads, then yes, two threads can have the same CPU. So what, this is a legit possibility according to https://man7.org/linux/man-pages/man2/getcpu.2.html (`The caller must allow for the possibility that the information returned in cpu and node is no longer current by the time the call returns.`)

I like this randomization approach.

> Regarding thread id comment are you suggesting to use this instead of rand_num?

We definitely shouldn't do this. Then `set/get_cpuaffinity` and the consequent `getcpu` won't work as expected.
</blockquote></details>

My question is about the second scenario. there is arbitrarity of which bit of cpu affinity mask to pick.
For example, the first set bit of cpu affinity mask can be returned without randomization. What's wrong?
What's the difference between first bit set and random picking?

Off course it depends on how applications use the result of getcpu.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZR7CmH7EF0HyAkjGpZ:-MZR7CmH7EF0HyAkjGp_:bwm54sd) ([raw file](https://github.com/oscarlab/graphene/blob/434dd6ae677a2b30484902e292de031594872e35/LibOS/shim/test/regression/pthread_set_get_affinity.c#L37)):*
> ```C
>         errx(EXIT_FAILURE, "sched_getcpu failed!");
>     else
>         printf("Thread %ld, is running on CPU %d\n", syscall(SYS_gettid), ret);
> ```

Can we add check the result is in cpuaffinity? or ltp does?


<!-- Sent from Reviewable.io -->

2021-04-29 06:37 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-MZRK_mz9HsXAP3SNqPo:b-ii1kz2) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, the mask can hold 1024 but what I meant was the number of bytes to copy. If we set it as `NUM_MASK` we would end up copying only 128 bits as it is always fixed. But when we use `bitmask_size_in_bytes ` it will get adjusted according to the number of cpus. This should work fine when the number of cpus is less than or equal to 1024.

Now on a system that has actually 2048 cpus but when we pass a mask of 128 bytes (meaning can take only 1024 cpus), yes the buffer will overflow. How about we add the below error checking?

```
         size_t cpu_cnt = PAL_CB(cpu_info.online_logical_cores);
+        if (cpu_cnt > CPUMASK_SETSIZE) {
+            log_warning("Due to glibc limitation max supported CPUs is 1024. "
+                        "System CPU count is %ld\n", cpu_cnt);
+            return -EINVAL;
+        }
+
```

PS: The reason I set `#define CPUMASK_SETSIZE 1024` is to basically emulate `cpu_set_t` struct which has a size of 128 bytes or in other words can take up to  1024 cpus.
</blockquote></details>

OK, with the new check, it makes sense now.
___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-MZRKm5H6hANH0E-FfsX:b-lgczle) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

My question is about the second scenario. there is arbitrarity of which bit of cpu affinity mask to pick.
For example, the first set bit of cpu affinity mask can be returned without randomization. What's wrong?
What's the difference between first bit set and random picking?

Off course it depends on how applications use the result of getcpu.

</blockquote></details>

@yamahata Understood you now. I don't have a good argument for randomization, your "always-first-set-bit" approach also works and technically correct. My only argument for randomization is that is approximates reality better :) Maybe we need a third opinion (of a reviewer from ITL).
___
*[LibOS/shim/src/sys/shim_sched.c, line 280 at r3](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZMApeuBTYFD6Bixhva:-MZRJrDX-MOcouYQmuG5:bct07vd) ([raw file](https://github.com/oscarlab/graphene/blob/fc92af15de221e4a37193d01a931d3e9b78b1f2f/LibOS/shim/src/sys/shim_sched.c#L280)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sounds good, done.
</blockquote></details>

Thanks, looks good to me!
___
*[LibOS/shim/src/sys/shim_sched.c, line 241 at r4](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZRJy-2Bj29xqmA-kYP:-MZRJy-30mGtxHLyo7Lh:b1ei29z) ([raw file](https://github.com/oscarlab/graphene/blob/434dd6ae677a2b30484902e292de031594872e35/LibOS/shim/src/sys/shim_sched.c#L241)):*
> ```C
>         if (cpu_cnt > CPUMASK_SETSIZE) {
>             log_warning("Due to glibc limitation max supported CPUs is 1024. "
>                         "System CPU count is %ld\n", cpu_cnt);
> ```

I would rephrase slightly: `"Maximum supported CPU count in Glibc is %d, but current CPU count is %lu\n", CPUMASK_SETSIZE, cpu_cnt)`


<!-- Sent from Reviewable.io -->

2021-04-29 21:06 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 2 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 241 at r4](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZRJy-2Bj29xqmA-kYP:-MZUOy0IDsjwN2QG-Tsk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/434dd6ae677a2b30484902e292de031594872e35/LibOS/shim/src/sys/shim_sched.c#L241)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would rephrase slightly: `"Maximum supported CPU count in Glibc is %d, but current CPU count is %lu\n", CPUMASK_SETSIZE, cpu_cnt)`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZR7CmH7EF0HyAkjGpZ:-MZUGuvC9PpsviXTSek2:b5ppp7x) ([raw file](https://github.com/oscarlab/graphene/blob/434dd6ae677a2b30484902e292de031594872e35/LibOS/shim/test/regression/pthread_set_get_affinity.c#L37)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Can we add check the result is in cpuaffinity? or ltp does?
</blockquote></details>

ltp test does this. They set the affinity and then compare it with the result of `getcpu` syscall. https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/getcpu/getcpu01.c#L139


<!-- Sent from Reviewable.io -->

2021-04-30 06:10 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/lib/api.h, line 110 at r5](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZWO5pi3mbiR-gyCW3H:-MZWO5pi3mbiR-gyCW3I:b-ryvexg) ([raw file](https://github.com/oscarlab/graphene/blob/66475d76e931ea45b4e89915b0691daaf19ac9a8/Pal/include/lib/api.h#L110)):*
> ```objc
> #define CPUMASK_SETSIZE 1024
> #define CPUBITS         (8 * sizeof(unsigned long))
> #define NUM_MASKS       (CPUMASK_SETSIZE / CPUBITS)
> ```

Looks like you can remove `CPUBITS` macro and use:
```
#define NUM_MASKS       (CPUMASK_SETSIZE / BITS_IN_TYPE(unsigned long))
```

Also, since you moved `NUM_MASKS` in this shared header, can you give it a more descriptive name? I think `MAX_CPUMASKS`.


<!-- Sent from Reviewable.io -->

2021-04-30 15:47 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/lib/api.h, line 110 at r5](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZWO5pi3mbiR-gyCW3H:-MZYRUsS9R7_TPun2Fd0:bu85ywm) ([raw file](https://github.com/oscarlab/graphene/blob/66475d76e931ea45b4e89915b0691daaf19ac9a8/Pal/include/lib/api.h#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like you can remove `CPUBITS` macro and use:
```
#define NUM_MASKS       (CPUMASK_SETSIZE / BITS_IN_TYPE(unsigned long))
```

Also, since you moved `NUM_MASKS` in this shared header, can you give it a more descriptive name? I think `MAX_CPUMASKS`.
</blockquote></details>

yes but felt that this `#define` was better to read. For example when we remove `CPUBITS` the following conversion might be a little difficult to understand first. Let me know what you think.

```
-        *cpu = __builtin_ctzl(cpumask) + CPUBITS * idx;
+        *cpu = __builtin_ctzl(cpumask) + BITS_IN_TYPE(unsigned long) * idx;
```

But agree we can change `NUM_MASKS` to `MAX_CPUMASKS`. This is more appropriate when defining in the common header file.


<!-- Sent from Reviewable.io -->

2021-04-30 20:17 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[Pal/include/lib/api.h, line 110 at r5](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZWO5pi3mbiR-gyCW3H:-MZZQFey8RoX2kMDKJS0:bjnh7kc) ([raw file](https://github.com/oscarlab/graphene/blob/66475d76e931ea45b4e89915b0691daaf19ac9a8/Pal/include/lib/api.h#L110)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes but felt that this `#define` was better to read. For example when we remove `CPUBITS` the following conversion might be a little difficult to understand first. Let me know what you think.

```
-        *cpu = __builtin_ctzl(cpumask) + CPUBITS * idx;
+        *cpu = __builtin_ctzl(cpumask) + BITS_IN_TYPE(unsigned long) * idx;
```

But agree we can change `NUM_MASKS` to `MAX_CPUMASKS`. This is more appropriate when defining in the common header file.
</blockquote></details>

Ah, you still use `CPUBITS`... What about only renaming then:
- `CPUBITS` -> `CPUMASK_BITS`
- `NUM_MASKS` -> `MAX_CPUMASKS`


<!-- Sent from Reviewable.io -->

2021-04-30 21:57 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 2 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/include/lib/api.h, line 110 at r5](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZWO5pi3mbiR-gyCW3H:-MZZiCVD-xaFg0JIax-a:bc0j6ql) ([raw file](https://github.com/oscarlab/graphene/blob/66475d76e931ea45b4e89915b0691daaf19ac9a8/Pal/include/lib/api.h#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, you still use `CPUBITS`... What about only renaming then:
- `CPUBITS` -> `CPUMASK_BITS`
- `NUM_MASKS` -> `MAX_CPUMASKS`
</blockquote></details>

yes sounds good, done.


<!-- Sent from Reviewable.io -->

2021-05-03 06:38 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-07 02:03 UTC, mkow requested changes
> Reviewed 2 of 3 files at r2, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-M_3V9HB50TU_oB5XhrM:b-okvro5) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
> What is happening in this loop? Why? This whole loop doesn't make sense to me, why not simply remove it and use the arithmetic below?

Wait to see my even more magical proposal in a thread above! :D

Overall, I slightly prefer the randomized version (but assuming that we'll properly randomize from all the bits, as I suggested in another thread). I don't think in practice any app would break if we returned hardcoded-but-valid numbers, but some too-picky tests (like LTP) probably can.
But as I said, it's not a strong preference.
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3MwHv9klcYoFjNB9z:-M_3MwHv9klcYoFjNBA-:brk8caq) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
> ```C
>     __UNUSED(unused);
> 
>     /* Mock implementation that returns a random set bit from the first non-empty cpu affinity mask */
> ```

`set bit` -> `bit set` (if I understood the intended meaning correctly)
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-M_3QPHn3tH8JWj3CDjI:b-cqw6m9) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
> ```
> the first non-empty cpu affinity mask
> ```

I don't understand this comment. I thought each thread has just one affinity mask?
___
*[LibOS/shim/src/sys/shim_sched.c, line 234 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3OLtEC5VBi1GSCv1p:-M_3OLtEC5VBi1GSCv1q:bugd71k) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L234)):*
> ```
> PAL_CB
> ```

This will need to be updated after rebase (`PAL_CB` was removed recently)
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-M_3O1A8CBjRtUUSSmBB:bieheg6) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
> ```
> Glibc
> ```

Uh, what does Glibc have to do with Linux syscalls?
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-M_3P4h4AjKo2pmqBjwJ:bngjyc3) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
> ```
> in user app
> ```

Not in Graphene? This case should be unreachable from the app.
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-M_3PAKHEyqu8kyLuy9K:bmsznne) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
> ```C
>          * some bug in user app. */
>         if (is_internal(thread)) {
>             return -ESRCH;
> ```

This should be a hard failure, as (IMO) this looks like a serious bug in Graphene.
___
*[LibOS/shim/src/sys/shim_sched.c, line 250 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3RCCW2AOplDpORLwf:-M_3RCCW2AOplDpORLwg:b-3w5qc5) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L250)):*
> ```C
>         }
> 
>         unsigned long mask[MAX_CPUMASKS] = {0};
> ```

I think you're missing a check if `bitmask_size_in_bytes` actually fit into this array.
___
*[LibOS/shim/src/sys/shim_sched.c, line 256 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3Qe8uBQQr280L7ngK:-M_3Qe8uBQQr280L7ngL:b-jelgtv) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L256)):*
> ```
> cpumask
> ```

What's "cpumask"? I guess you meant "CPU mask" (looking at some previous comment), but then it doesn't make sense for me - each thread has only one affinity mask.
___
*[LibOS/shim/src/sys/shim_sched.c, line 261 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3SjG3-rJlairdW_tL:-M_3SjG3-rJlairdW_tM:b-pg74js) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L261)):*
> ```C
>         while (idx < MAX_CPUMASKS) {
>             num_bits = count_ulong_bits_set(mask[idx]);
>             if (num_bits)
> ```

If you removed this `if` and moved `idx` into the loop we'd have a proper random from the whole affinity mask. Why doing doing so? The code may even get simpler this way.
___
*[LibOS/shim/src/sys/shim_sched.c, line 267 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3S8G3CNp9lGi2yKdo:-M_3S8G3CNp9lGi2yKdp:bdqo1qu) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L267)):*
> ```C
>         assert(num_bits);
> 
>         /* Generate a random number and use it to find a random set bit in the cpumask */
> ```

`set bit` -> `bit set`
___
*[LibOS/shim/src/sys/shim_sched.c, line 274 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3SJBh01NUTWBjDQhP:-M_3SJBh01NUTWBjDQhQ:bqky5hd) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L274)):*
> ```C
>         }
> 
>         int nth_setbit = rand_num % num_bits;
> ```

All bit indexes were `unsigned long` so far in this function, why `int` now?
___
*[LibOS/shim/src/sys/shim_sched.c, line 277 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3T6yr4qv_N5KqKiZJ:-M_3T6yr4qv_N5KqKiZK:bdqo1qu) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L277)):*
> ```C
>         unsigned long cpumask = mask[idx];
>         for (int j = 0; j < nth_setbit; j++) {
>             /* At each iteration, find the lowest set bit in cpumask and unset it; this will bring
> ```

`set bit` -> `bit set`
___
*[LibOS/shim/src/sys/shim_sched.c, line 279 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3TWw038H350JRxjQA:-M_3TWw038H350JRxjQB:b-jg8ifi) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L279)):*
> ```C
> cpumask = cpumask & ~(1UL << __builtin_ctzl(cpumask));
> ```

`cpumask -= cpumask & -cpumask;` does the same and is faster and doesn't depend on arch+compiler-specific builtins, although it's more magical :) (but with a proper comment it should be fine)
___
*[LibOS/shim/src/sys/shim_sched.c, line 289 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3VPPY29BSBabM5AUu:-M_3VPPY29BSBabM5AUv:b399hxl) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L289)):*
> ```C
>             return -EFAULT;
>         }
>         *node = 0;
> ```

Hmm, so, right now we can return a CPU which doesn't actually belong to the returned node?
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 37 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3HbmIDqEAbIy1OgZ6:-M_3HbmJDdGe8ZeHTDlc:bwxm7is) ([raw  [...]

2021-05-08 00:42 UTC, yamahata approved these changes, later dismissed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 18 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2021-05-12 20:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 1 of 4 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3MwHv9klcYoFjNB9z:-M_Vi1KM6b_-n7dHl7-Z:ba3jysg) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`set bit` -> `bit set` (if I understood the intended meaning correctly)
</blockquote></details>

I have changed but what is the difference you see?
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-M_ViFJD2q5bUorIS9AD:bhl6c59) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> the first non-empty cpu affinity mask
> ```

I don't understand this comment. I thought each thread has just one affinity mask?
</blockquote></details>

No, each thread can run on any cpu by default and so will have all the bits set in the affinity mask. Based on the user input, the affinity can be reduced to a subset that could range between 1 and `max cpus`. 

Now, cpu affinity is stored as an array of `unsigned long mask[n]` with first 64 cpus represented in mask[0] and next 64 as part of mask[1] and so on. Say for example we have 128 cpus and the thread affinity is set to cpus 64, 65 mask[0] will be empty and mask[1] = 3 and the comment says that we pick a random bit set from mask[1] which will result in this function returning either 64 or 65.


  
___
*[LibOS/shim/src/sys/shim_sched.c, line 234 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3OLtEC5VBi1GSCv1p:-M_Vt9eS6Kivm1YujH9e:bcl170p) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L234)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> PAL_CB
> ```

This will need to be updated after rebase (`PAL_CB` was removed recently)
</blockquote></details>

yes fixed this as part of the rebase.
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-M_VyatPBt2rqUd9Jp3c:bsebwa3) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Glibc
> ```

Uh, what does Glibc have to do with Linux syscalls?
</blockquote></details>

Affinity mask struct `cpu_set_t` that we use with calls like `sched_setaffinity` and `sched_getaffinity`is part of glibc and this has a limitation of storing max 1024 cpus. So called this out as part of the error log as `getcpu` syscall in graphene case is using `sched_getaffinity`

Below text is extracted from https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html
```
However, the cpu_set_t data type used by glibc has a fixed size of 128 bytes, meaning that the maximum CPU number that can be represented is 1023.  If the kernel CPU affinity mask is larger than 1024, then calls of the form: sched_getaffinity(pid, sizeof(cpu_set_t), &mask); fail with the error EINVAL
```
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-M_W-Xej4F0OB8AoMpcr:b28fmy0) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> in user app
> ```

Not in Graphene? This case should be unreachable from the app.
</blockquote></details>

Are you suggesting we remove `user app` and replace it with `graphene` as the application cannot affinitize graphene internal threads? I think the comment was suggested to replicate the comments in `shim_do_sched_getaffinity` /`shim_do_sched_setaffinity`
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-M_W1Sjd6rwgd1eE0nOe:b-s56qnr) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be a hard failure, as (IMO) this looks like a serious bug in Graphene.
</blockquote></details>

how about returning `DkProcessExit(1)` instead of `-ESRCH`? If we do this, then I will also change the logic to handle this error in the same way in for `shim_do_sched_getaffinity` and `shim_do_sched_setaffinity`
___
*[LibOS/shim/src/sys/shim_sched.c, line 250 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3RCCW2AOplDpORLwf:-M_W2xk0DYhVnLp8JKoO:bh5sfr) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think you're missing a check if `bitmask_size_in_bytes` actually fit into this array.
</blockquote></details>

`bitmask_size_in_bytes` is limited based on the `cpu_cnt` .
```
size_t bitmask_size_in_bytes = BITS_TO_LONGS(cpu_cnt) * sizeof(long);
```

And we do have a check for `cpu_cnt` when it exceeds more than 1024. So we should be good here and able to fit `bitmask_size_in_bytes ` to `mask[MAX_CPUMASKS]`
___
*[LibOS/shim/src/sys/shim_sched.c, line 256 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3Qe8uBQQr280L7ngK:-M_W3XbJ1COii-DZkjb8:b-2bm4wy) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L256)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> cpumask
> ```

What's "cpumask"? I guess you meant "CPU mask" (looking at some previous comment), but then it doesn't make sense for me - each thread has only one affinity mask.
</blockquote></details>

pls refer to the earlier comment on one affinity mask.
___
*[LibOS/shim/src/sys/shim_sched.c, line 261 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3SjG3-rJlairdW_tL:-M_W5jax1Ra09oUNyIRV:bmyrfri) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L261)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If you removed this `if` and moved `idx` into the loop we'd have a proper random from the whole affinity mask. Why doing doing so? The code may even get simpler this way.
</blockquote></details>

Can you please clarify your logic of randomly picking a random bit set bit from `mask[idx]`?

As I mentioned in my earlier comment `mask[0]` will hold cpu mask from `0-63` and `mask[1]` will hold cpu mask `64-127` and so on. In this logic, we find the first non-empty mask and then randomly pick a bit set from it.
___
*[LibOS/shim/src/sys/shim_sched.c, line 267 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3S8G3CNp9lGi2yKdo:-M_W7CO860u9aGvIu5Qi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L267)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`set bit` -> `bit set`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_s [...]

2021-05-13 00:36 UTC, mkow requested changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_XoJtt0rJ5I6VGinhF:-M_XoJtt0rJ5I6VGinhG:b3htg6e) (no related file):*
`[LibOS]:` -> `[LibOS]` (in the commit message)
+ missing verb in the one-liner

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3MwHv9klcYoFjNB9z:-M_XoXAm-aSi08JhvfHM:bta1or) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
> what is the difference you see?

You mean in Reviewable? (i.e. you pushed the change and don't see it here? if so, then it looks fine)

Or you mean in English? "random set bit" just sounds very odd to me, but I'm not sure if there's any rule for this. Now that I read the old and the new version I dislike them both, they are hard to parse in English :) Anyways, this isn't too important.
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-M_Y0Nk86WUbE9xtI-wC:b2n7hfi) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No, each thread can run on any cpu by default and so will have all the bits set in the affinity mask. Based on the user input, the affinity can be reduced to a subset that could range between 1 and `max cpus`. 

Now, cpu affinity is stored as an array of `unsigned long mask[n]` with first 64 cpus represented in mask[0] and next 64 as part of mask[1] and so on. Say for example we have 128 cpus and the thread affinity is set to cpus 64, 65 mask[0] will be empty and mask[1] = 3 and the comment says that we pick a random bit set from mask[1] which will result in this function returning either 64 or 65.


  
</blockquote></details>

Huh, I think you use "mask" as "a single word from the affinity mask"? This is just an implementation detail, a mask is an array of bits, and the whole `unsigned long mask[n]` altogether is "a mask".
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-M_Y0p854E6WQkk4SzFc:b-8zlap) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Affinity mask struct `cpu_set_t` that we use with calls like `sched_setaffinity` and `sched_getaffinity`is part of glibc and this has a limitation of storing max 1024 cpus. So called this out as part of the error log as `getcpu` syscall in graphene case is using `sched_getaffinity`

Below text is extracted from https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html
```
However, the cpu_set_t data type used by glibc has a fixed size of 128 bytes, meaning that the maximum CPU number that can be represented is 1023.  If the kernel CPU affinity mask is larger than 1024, then calls of the form: sched_getaffinity(pid, sizeof(cpu_set_t), &mask); fail with the error EINVAL
```

</blockquote></details>

What if the user uses musl? Or Go runtime? This warning doesn't make sense for them. We implement Linux, there may be no glibc involved here at all.
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-M_Y1Flb-gKMQ1tHljfH:b1h1yem) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
> Are you suggesting we remove `user app` and replace it with `graphene` as the application cannot affinitize graphene internal threads?

Yes, if it's actually this way. But I think it shouldn't be possible from the app.
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-M_Y1cRgER-RObe1wZUA:boqegll) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
> returning `DkProcessExit(1)`

I assume you mean _calling_?

Isn't the case with the other calls different? Here you use `get_cur_thread()` and there you have a `pid` argument.
___
*[LibOS/shim/src/sys/shim_sched.c, line 250 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3RCCW2AOplDpORLwf:-M_Y4cAwE6UzL017H2Wm:bz9840u) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L250)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`bitmask_size_in_bytes` is limited based on the `cpu_cnt` .
```
size_t bitmask_size_in_bytes = BITS_TO_LONGS(cpu_cnt) * sizeof(long);
```

And we do have a check for `cpu_cnt` when it exceeds more than 1024. So we should be good here and able to fit `bitmask_size_in_bytes ` to `mask[MAX_CPUMASKS]`
</blockquote></details>

This is bad. To verify correctness of this code the reader has to perform a lot of calculations, all the sizes you use seem obfuscated - on one side the buffer size is `sizeof(unsigned long mask[MAX_CPUMASKS])` == `sizeof(unsigned long) * MAX_CPUMASKS` == `sizeof(unsigned long) * (CPUMASK_SETSIZE / CPUMASK_BITS)` == `sizeof(unsigned long) * (1024 / BITS_IN_TYPE(unsigned long))` == 128.
On the other side we have `bitmask_size_in_bytes` which is `BITS_TO_LONGS(cpu_cnt) * sizeof(long)`, which is `DIV_ROUND_UP(cpu_cnt, 8) * 8`, which is `((cpu_cnt + 7) / 8) * 8`.

To not have a possible buffer overflow here we need to have `128 >= ((cpu_cnt + 7) / 8) * 8`. We only know that `cpu_cnt <= CPUMASK_SETSIZE` from the `if` above, which is `cpu_cnt <= 1024`, so we can't actually prove this... But I probably made a mistake somewhere in the calculations.


Anyways, you should get the idea now. I had to do tons of calculations just to prove that one simple call is correct... That's not how readable and maintainable code should be written.
___
*[LibOS/shim/src/sys/shim_sched.c, line 261 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3SjG3-rJlairdW_tL:-M_Y2L9424j1HiI3gODR:bsmggqk) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L261)):*
> As I mentioned in my earlier comment mask[0] will hold cpu mask from 0-63 and mask[1] will hold cpu mask 64-127 and so on.

Yup, I understand the format of the data.

> Can you please clarify your logic of randomly picking a random bit set bit from mask[idx]?

You just count all the ones in the mask, then pick a number in this range and then just find the n-th "1" bit using a slightly modified version of the loop below.
___
*[LibOS/shim/src/sys/shim_sched.c, line 279 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3TWw038H350JRxjQA:-M_Y30sa6g41SSRfZeKh:bi5larx) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L279)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is a cool trick :) where you get a number with only its least significant bit set and then subtract it from the original to get the next set LSB. Once the nth_setbit is found either shift or use the `builtin` function to identify the cpu

IIUC the logic depends on finding the 2's complement which is a little difficult to picture mentally while reading the code. Also, we do use `builtins` at many other places so this  [...]

2021-05-13 07:37 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-M_Zd8Px0yraSTc3odY3:beu5yz) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, I think you use "mask" as "a single word from the affinity mask"? This is just an implementation detail, a mask is an array of bits, and the whole `unsigned long mask[n]` altogether is "a mask".
</blockquote></details>

yes, correct that is the intention of the comment.
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3MwHv9klcYoFjNB9z:-M_ZdJi36mTNs1g9SYHJ:b-bk6ooj) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> what is the difference you see?

You mean in Reviewable? (i.e. you pushed the change and don't see it here? if so, then it looks fine)

Or you mean in English? "random set bit" just sounds very odd to me, but I'm not sure if there's any rule for this. Now that I read the old and the new version I dislike them both, they are hard to parse in English :) Anyways, this isn't too important.
</blockquote></details>

I meant in English :)
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-M_ZbY35-he1quFb1aHt:b-ls585r) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if the user uses musl? Or Go runtime? This warning doesn't make sense for them. We implement Linux, there may be no glibc involved here at all.
</blockquote></details>

yes, good point but I am not sure how to handle this in a generic way. One thing is, I can remove the glibc word from the comment :) and another thing is we could increase the mask to the account for max cpus supported by Linux (8K?) so that there will not be an overflow.
Any other thoughts to handle this case?

Looked at musl libc and even they seem to be limiting to 1024 cpus.
https://git.musl-libc.org/cgit/musl/tree/include/sched.h#n87
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-M_ZbAdb0OY3J8P93nKw:bnwzfsz) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Are you suggesting we remove `user app` and replace it with `graphene` as the application cannot affinitize graphene internal threads?

Yes, if it's actually this way. But I think it shouldn't be possible from the app.
</blockquote></details>

OK, got it. Will update the text.
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-M_ZZjrsCurxP5jgm8IX:b-cpt4om) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
> I assume you mean calling?

Yes.
Regarding `shim_do_sched_getaffinity`/`shim_do_sched_setaffinity` calls we handle for both cases, `get_cur_thread()` as well as `pid` case but in either case we handle this error by returning `-ESRCH` 
___
*[LibOS/shim/src/sys/shim_sched.c, line 250 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3RCCW2AOplDpORLwf:-M_ZQIk23pa0vkjwgK9N:bbzi1q2) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is bad. To verify correctness of this code the reader has to perform a lot of calculations, all the sizes you use seem obfuscated - on one side the buffer size is `sizeof(unsigned long mask[MAX_CPUMASKS])` == `sizeof(unsigned long) * MAX_CPUMASKS` == `sizeof(unsigned long) * (CPUMASK_SETSIZE / CPUMASK_BITS)` == `sizeof(unsigned long) * (1024 / BITS_IN_TYPE(unsigned long))` == 128.
On the other side we have `bitmask_size_in_bytes` which is `BITS_TO_LONGS(cpu_cnt) * sizeof(long)`, which is `DIV_ROUND_UP(cpu_cnt, 8) * 8`, which is `((cpu_cnt + 7) / 8) * 8`.

To not have a possible buffer overflow here we need to have `128 >= ((cpu_cnt + 7) / 8) * 8`. We only know that `cpu_cnt <= CPUMASK_SETSIZE` from the `if` above, which is `cpu_cnt <= 1024`, so we can't actually prove this... But I probably made a mistake somewhere in the calculations.


Anyways, you should get the idea now. I had to do tons of calculations just to prove that one simple call is correct... That's not how readable and maintainable code should be written.
</blockquote></details>

The reason I didn't add an explicit check is because I declare this variable `unsigned long mask[MAX_CPUMASKS]` and this isn't passed from user or other function. But I do get your point if someone else tries to modify this piece of code, it might be a little difficult to read.  

Does the below change look fine to you?
```
diff --git a/LibOS/shim/src/sys/shim_sched.c b/LibOS/shim/src/sys/shim_sched.c
index f4d53a84..d7e2079c 100644
--- a/LibOS/shim/src/sys/shim_sched.c
+++ b/LibOS/shim/src/sys/shim_sched.c
@@ -252,6 +252,7 @@ long shim_do_getcpu(unsigned* cpu, unsigned* node, struct getcpu_cache* unused)
         }
 
         unsigned long mask[MAX_CPUMASKS] = {0};
+        assert(sizeof(mask) > bitmask_size_in_bytes);
         int ret = DkThreadGetCpuAffinity(thread->pal_handle, bitmask_size_in_bytes, &mask);
         if (ret < 0) {
             return pal_to_unix_errno(ret);
```
___
*[LibOS/shim/src/sys/shim_sched.c, line 261 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3SjG3-rJlairdW_tL:-M_ZNsZQ2_BOFQC-ASW7:b-wykbz9) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L261)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> As I mentioned in my earlier comment mask[0] will hold cpu mask from 0-63 and mask[1] will hold cpu mask 64-127 and so on.

Yup, I understand the format of the data.

> Can you please clarify your logic of randomly picking a random bit set bit from mask[idx]?

You just count all the ones in the mask, then pick a number in this range and then just find the n-th "1" bit using a slightly modified version of the loop below.
</blockquote></details>

sorry little confused, I am doing the same thing right :). Are you suggesting a different optimization? If so I am missing the point. Please clarify.
___
*[LibOS/shim/src/sys/shim_sched.c, line 289 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3VPPY29BSBabM5AUu:-M_ZJ6o49jjXfzmrTUQF:b-3nbb8m) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L289)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this a problem? How hard would it be to emulate this properly? I don't like such possibilities from the security perspective, the application may not expect this.
</blockquote></details>

Yes, agree this would be a little misleading and we should add this support. But prefer to do thi [...]

2021-05-14 09:16 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-M_e8w6Y4MGdUxT9f1XG:b3goi3d) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, good point but I am not sure how to handle this in a generic way. One thing is, I can remove the glibc word from the comment :) and another thing is we could increase the mask to the account for max cpus supported by Linux (8K?) so that there will not be an overflow.
Any other thoughts to handle this case?

Looked at musl libc and even they seem to be limiting to 1024 cpus.
https://git.musl-libc.org/cgit/musl/tree/include/sched.h#n87
</blockquote></details>

Why not just replace `Glibc` -> `Graphene`?


<!-- Sent from Reviewable.io -->

2021-05-17 14:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-M_uhuS1CZR0sADB0JBj:b-t5omie) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just replace `Glibc` -> `Graphene`?
</blockquote></details>

yes, this will be generic we can do this. @mkow do you think this is reasonable?


<!-- Sent from Reviewable.io -->

2021-06-01 00:38 UTC, vijaydhanraj commented
Rebased to latest master. Also renamed the commit message.

2021-06-01 06:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 3 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)



<!-- Sent from Reviewable.io -->

2021-06-15 19:50 UTC, mkow requested changes
> Reviewed 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_XoJtt0rJ5I6VGinhF:-McG8hCd0s9U-AfbW52Z:bfhqml6) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`[LibOS]:` -> `[LibOS]` (in the commit message)
+ missing verb in the one-liner
</blockquote></details>

Not done.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-McGA1eI0alG6mfu3c6a:b-k62al9) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, correct that is the intention of the comment.
</blockquote></details>

So, it's wrong ;) The "mask" is the whole thing, it's just split into a bunch of integers for technical reasons.
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McGAOkTE5JOz-oyCZ4K:bsrumvb) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, this will be generic we can do this. @mkow do you think this is reasonable?
</blockquote></details>

We can go with saying it's a Graphene limit.
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-McGB0c1EiRutEakWPcv:b-du4cg8) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

OK, got it. Will update the text.
</blockquote></details>

`graphene` -> `Graphene`
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-McGCy4I-xPfhfO7EnBx:bvjrj5x) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> I assume you mean calling?

Yes.
Regarding `shim_do_sched_getaffinity`/`shim_do_sched_setaffinity` calls we handle for both cases, `get_cur_thread()` as well as `pid` case but in either case we handle this error by returning `-ESRCH` 
</blockquote></details>

Ok, then it seems that `shim_do_sched_{get,set}affinity` are doing this wrong.
___
*[LibOS/shim/src/sys/shim_sched.c, line 250 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3RCCW2AOplDpORLwf:-McGCTmP9y2pfG1U7ox8:b-67jmlc) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L250)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The reason I didn't add an explicit check is because I declare this variable `unsigned long mask[MAX_CPUMASKS]` and this isn't passed from user or other function. But I do get your point if someone else tries to modify this piece of code, it might be a little difficult to read.  

Does the below change look fine to you?
```
diff --git a/LibOS/shim/src/sys/shim_sched.c b/LibOS/shim/src/sys/shim_sched.c
index f4d53a84..d7e2079c 100644
--- a/LibOS/shim/src/sys/shim_sched.c
+++ b/LibOS/shim/src/sys/shim_sched.c
@@ -252,6 +252,7 @@ long shim_do_getcpu(unsigned* cpu, unsigned* node, struct getcpu_cache* unused)
         }
 
         unsigned long mask[MAX_CPUMASKS] = {0};
+        assert(sizeof(mask) > bitmask_size_in_bytes);
         int ret = DkThreadGetCpuAffinity(thread->pal_handle, bitmask_size_in_bytes, &mask);
         if (ret < 0) {
             return pal_to_unix_errno(ret);
```
</blockquote></details>

I'd prefer if you untangled the whole code instead ;)
___
*[LibOS/shim/src/sys/shim_sched.c, line 261 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3SjG3-rJlairdW_tL:-McGBo691OQU8RQ3bSIV:bceqebx) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L261)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

sorry little confused, I am doing the same thing right :). Are you suggesting a different optimization? If so I am missing the point. Please clarify.
</blockquote></details>

No, you're counting ones only in the first non-zero ulong of the mask and choose only from it, skipping the rest of the mask.
___
*[LibOS/shim/src/sys/shim_sched.c, line 289 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3VPPY29BSBabM5AUu:-McGCA5EEXcBbafXV8zU:b-hqy66s) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L289)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, agree this would be a little misleading and we should add this support. But prefer to do this in a separate PR if it is fine.
 
Regarding implementation, it shouldn't be difficult as we already read `/sys/devices/system/node/node0/cpumap` path and store the cpumap associated with a node during`PAL` initialization. From this, we can extract cpu that is part of a numa and pass it to LibOS. 

</blockquote></details>

So, this sounds like a single `for` loop here? If so, then I'd add it to this PR to not upstream code which returns incorrect data to the app.


<!-- Sent from Reviewable.io -->

2021-06-15 23:52 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r7, 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCD3J97BcU2pUVZIPX:-McGzw1n7GOkiZqM44RK:b-6dy59) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, with the new check, it makes sense now.
</blockquote></details>

There is no `cpu_set_t` as far as kernel is concerned.
___
*[LibOS/shim/src/sys/shim_sched.c, line 264 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDxotBBw1jAep2QMt:-McH0Ni53klfCh-iAL86:bpfuam7) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L264)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

how about just adding `assert(num_bits)`? This should take care of the error case of `idx == NUM_MASKS` as well.
</blockquote></details>

`asserts` are not error checks. Can a malicious host return empty affinity mask?
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-McGKywt6o1zW5UEux-s:b-z2235i) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, it's wrong ;) The "mask" is the whole thing, it's just split into a bunch of integers for technical reasons.
</blockquote></details>

Agreed, there is only one (per thread) cpu affinity mask, so saying "first non-empty" is misleading.
Also `a random bit set` will probably be understood as `a set of random bits`, which is not you wanted to say here, is it?
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McGL9TY-7mqlVoLObah:b9oak9o) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We can go with saying it's a Graphene limit.
</blockquote></details>

This is wrong, why do you check for some arbitrary limit? We are playing the role of the Linux kernel here and the kernel does not enforce any limits.
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-McGLeADD9IyIpy2DXqT:b-mvigvc) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`graphene` -> `Graphene`
</blockquote></details>

This check is useless and makes no sense. We do not call syscall emulation routines from internal threads.
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-McGyyVnEbqshxO16KyI:b-r26c6) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, then it seems that `shim_do_sched_{get,set}affinity` are doing this wrong.
</blockquote></details>

Please check the comment above.
___
*[LibOS/shim/src/sys/shim_sched.c, line 250 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3RCCW2AOplDpORLwf:-McH-kmuD35FFpw6b0s3:be7jf7) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer if you untangled the whole code instead ;)
</blockquote></details>

Why not `malloc` just enough space?
___
*[LibOS/shim/src/sys/shim_sched.c, line 256 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3Qe8uBQQr280L7ngK:-McH-HCm9TQrQ9xETW-C:bitr5k) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L256)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

pls refer to the earlier comment on one affinity mask.
</blockquote></details>

+1, threads have only one affinity mask
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r8](https://reviewable.io/reviews/oscarlab/graphene/2331#-McGMRfI-Wt1Hz8q7BY1:-McGMRfJBPm65BJiDI9J:bm145ef) ([raw file](https://github.com/oscarlab/graphene/blob/1720acdf5bede3d863ddb06a4ca666e4833a30e9/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
> ```C
> 
>     int ret = sched_getcpu();
>     if (ret < 0)
> ```

Please use `{ }`, since there is an `else` clause.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 35 at r8](https://reviewable.io/reviews/oscarlab/graphene/2331#-McGN61o2jqX0eGDXq1A:-McGN61p2DjcvjGKObOK:b-qzuhub) ([raw file](https://github.com/oscarlab/graphene/blob/1720acdf5bede3d863ddb06a4ca666e4833a30e9/LibOS/shim/test/regression/pthread_set_get_affinity.c#L35)):*
> ```C
>     int ret = sched_getcpu();
>     if (ret < 0)
>         errx(EXIT_FAILURE, "sched_getcpu failed!");
> ```

Please use `err()`, `sched_getcpu` sets `errno`.


<!-- Sent from Reviewable.io -->

2021-06-16 00:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-McH5WOh08YfgVkQuhc9:bev55lk) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
> Also `a random bit set` will probably be understood as `a set of random bits`, which is not you wanted to say here, is it?

Hah, I didn't think of reading it this way (it was me who suggested this wording because I got confused by the older one). Let's maybe use a longer form to make it clearer, e.g. "returns a random bit which is set"?
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McH6goLBo8JpF3hQhFi:b-8hq2qw) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is wrong, why do you check for some arbitrary limit? We are playing the role of the Linux kernel here and the kernel does not enforce any limits.
</blockquote></details>

I was fine with capping this because it prevents int overflows (e.g. on the allocation below), but now that I think of this, we already do this when initializing `g_pal_control->cpu_info.online_logical_cores` if I remember correctly.
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-McH7D27ELREqE9NNV5C:bu6f3qg) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This check is useless and makes no sense. We do not call syscall emulation routines from internal threads.
</blockquote></details>

So, I guess this should either be an assert or a hard failure, as suggested. Or just removed, if it's impossible to create such a bug.


<!-- Sent from Reviewable.io -->

2021-06-16 07:10 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-McIcqIa0smTYSd3Fr-X:b3ph2mu) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, I guess this should either be an assert or a hard failure, as suggested. Or just removed, if it's impossible to create such a bug.
</blockquote></details>

I think such checks are remnants of the old code in Graphene where these sycall functions (`sim_do_...`) could be called from anywhere in the LibOS. Since we recently moved away from this, these checks can be removed (as Borys mentions, this cannot happen at all).
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-McIdTjSCI-q78aPA8G7:b-99c3nj) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please check the comment above.
</blockquote></details>

Let's remove such checks from `shim_do_sched_getaffinity`/`shim_do_sched_setaffinity` too.


<!-- Sent from Reviewable.io -->

2021-06-16 10:42 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McJOvBC6zr-AdvdlhDe:b-qgrm2w) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I was fine with capping this because it prevents int overflows (e.g. on the allocation below), but now that I think of this, we already do this when initializing `g_pal_control->cpu_info.online_logical_cores` if I remember correctly.
</blockquote></details>

Then check for int overflows, not some random limit...
___
*[LibOS/shim/src/sys/shim_sched.c, line 245 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3P4h4AjKo2pmqBjwI:-McJP5c6CuU5Mks8dPL7:bqilkuu) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L245)):*
> could be called from anywhere in the LibOS. Since we recently moved away from this (...)

Was that really ever the case? I don't think it could work, like ever, maybe except some super simple syscalls.


<!-- Sent from Reviewable.io -->

2021-06-16 11:07 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McJUZdWDfqvJQqf-CAp:bgnrcpb) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then check for int overflows, not some random limit...
</blockquote></details>

But this value is global and would need to be checked in tons of places, and then places which depend on these (i.e. any place which somehow depends on the CPU count, even indirectly by iterating over some other CPU-related struct). And in practice this number can be just capped at ~10/100k and we'll be fine.


<!-- Sent from Reviewable.io -->

2021-06-16 11:18 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McJXSfDCnfkMp16PvMu:biwpbis) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But this value is global and would need to be checked in tons of places, and then places which depend on these (i.e. any place which somehow depends on the CPU count, even indirectly by iterating over some other CPU-related struct). And in practice this number can be just capped at ~10/100k and we'll be fine.
</blockquote></details>

Sure, it it's capped reasonably low we dont have to. It's just you suggested that we need something to prevent int overflows and I said I prefer explicit checks than a **random** cap.


<!-- Sent from Reviewable.io -->

2021-06-16 11:24 UTC, mkow reviewed
> Reviewed 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McJYaKL1HHY22Q42bJ-:b-u5zgdj) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure, it it's capped reasonably low we dont have to. It's just you suggested that we need something to prevent int overflows and I said I prefer explicit checks than a **random** cap.
</blockquote></details>

What I meant is that because `online_logical_cores` is already capped in the initialization routine we don't need the `if` here neither overflow checks below (e.g. in `bitmask_size_in_bytes = BITS_TO_LONGS(cpu_cnt) * sizeof(long)`). I.e. we can assume that this global is reasonably small.


<!-- Sent from Reviewable.io -->

2021-06-18 02:16 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 1 of 4 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_XoJtt0rJ5I6VGinhF:-McJwidx2vy64eLUHPWL:b64wql7) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Just to clarify, you mean I still have `:` and this needs to be removed right? Because I do have `add` in the commit one-liner which is a verb `Add partial support for getcpu syscall`

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 264 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCDxotBBw1jAep2QMt:-McR_mK1EuMnDEHfEhwk:b-5kkrkr) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L264)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`asserts` are not error checks. Can a malicious host return empty affinity mask?
</blockquote></details>

Ideally if the mask is empty or contains processors that are not physically present in the system, then `sched_getaffinity` will return `-EINVAL`. But if the host is malicious then it can be empty.

I have added an explicit check.
___
*[LibOS/shim/src/sys/shim_sched.c, line 276 at r1](https://reviewable.io/reviews/oscarlab/graphene/2331#-MZCEhai-Hon2r0hR73J:-McRctUj8O72NKlg6_Fu:b8ws98g) ([raw file](https://github.com/oscarlab/graphene/blob/e6824bc1445542ca8cf28b47d0ee45d1c9d93912/LibOS/shim/src/sys/shim_sched.c#L276)):*
> Overall, I slightly prefer the randomized version (but assuming that we'll properly randomize from all the bits, as I suggested in another thread). I don't think in practice any app would break if we returned hardcoded-but-valid numbers, but some too-picky tests (like LTP) probably can.
> But as I said, it's not a strong preference.
I prefer the current approach of randomization as randomizing from all the bits doesn't seem to provide any additional value.
___
*[LibOS/shim/src/sys/shim_sched.c, line 228 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3QPHn3tH8JWj3CDjH:-McK-fSf6_c26beQlqpS:b-rtrabn) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L228)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Also `a random bit set` will probably be understood as `a set of random bits`, which is not you wanted to say here, is it?

Hah, I didn't think of reading it this way (it was me who suggested this wording because I got confused by the older one). Let's maybe use a longer form to make it clearer, e.g. "returns a random bit which is set"?
</blockquote></details>

yeah, I now see that `first` is misleading. Reworded as suggested.
___
*[LibOS/shim/src/sys/shim_sched.c, line 236 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3O1A8CBjRtUUSSmBA:-McRL8snBrpxg98qfFB0:b-9iejgr) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L236)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What I meant is that because `online_logical_cores` is already capped in the initialization routine we don't need the `if` here neither overflow checks below (e.g. in `bitmask_size_in_bytes = BITS_TO_LONGS(cpu_cnt) * sizeof(long)`). I.e. we can assume that this global is reasonably small.
</blockquote></details>

Removed the limits check but we do need `bitmask_size_in_bytes` as  `DkThreadGetCpuAffinity` will require it. (`size` parameter) 
___
*[LibOS/shim/src/sys/shim_sched.c, line 247 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3PAKHEyqu8kyLuy9J:-McROfTaBqPAi8RMSZbM:b6s6jvw) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L247)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's remove such checks from `shim_do_sched_getaffinity`/`shim_do_sched_setaffinity` too.
</blockquote></details>

yes have removed this check and have created another commit which removes this from `shim_do_sched_getaffinity/shim_do_sched_setaffinity` as well.
___
*[LibOS/shim/src/sys/shim_sched.c, line 250 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3RCCW2AOplDpORLwf:-McRPwDeAWO8dtBGM_l9:b2icjrr) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L250)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `malloc` just enough space?
</blockquote></details>

yes, used `malloc` approach and cleaned it a bit.
___
*[LibOS/shim/src/sys/shim_sched.c, line 256 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3Qe8uBQQr280L7ngK:-McRQKmiAapd-yDt2maK:b7y591l) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L256)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1, threads have only one affinity mask
</blockquote></details>

Yes they do. By `cpumask` I meant to refer the first non-empty `unsigned long` that is part of the cpu affinity `mask`.  I have now reworded the comment.
___
*[LibOS/shim/src/sys/shim_sched.c, line 261 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3SjG3-rJlairdW_tL:-McRUeAP8MdAnWdL_t34:b-msgpbi) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L261)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No, you're counting ones only in the first non-zero ulong of the mask and choose only from it, skipping the rest of the mask.
</blockquote></details>

ah ok, I get it. So by default a thread can run on all `cpus` unless it is affinitized to one or subset of `cpus` which means either of the suggested approach will only be an approximation as we simply find a random bit set in the cpu affinity `mask` instead of getting infomation from scheduler. Given this, I didn't see much value in counting all the bits set in the `mask` and then parsing each of the `unsigned longs` to find the random set bit so implemented this logic.
___
*[LibOS/shim/src/sys/shim_sched.c, line 289 at r6](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_3VPPY29BSBabM5AUu:-McRdNiaC-A4iq9760qt:b-vna9u6) ([raw file](https://github.com/oscarlab/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L289)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, this sounds like a single `for` loop here? If so, then I'd add it to this PR to not upstream code which returns incorrect data to the app.
</blockquote></details>

No not that simple :). LibOS doesn't know anything about the `cpumap` yet. We need to build infrastrucute to propagate this from `PAL` to `LibOS` until that we can print a warning message if user might be misled and will create another github issue so track the change.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r8](https://reviewable.io/reviews/oscarlab/graphene/2331#-McGMRfI-Wt1Hz8q7BY1:-McRgg5Q1dgVMbwOKU-s:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1720acdf5bede3d863ddb06a4ca666e4833a30e9/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please use `{ }`, since there is an  [...]

2021-06-18 13:57 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/src/sys/shim_sched.c, line 223 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUNE9x6lx1GpNuo0AB:-McUNE9x6lx1GpNuo0AC:bcgfuf8) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L223)):*
> ```C
>         size_t cpu_cnt = g_pal_control->cpu_info.online_logical_cores;
> 
>         /* Allocate memory to hold the thread's cpu affinity mask*/
> ```

`.` and ` ` (space) missing at the end.
___
*[LibOS/shim/src/sys/shim_sched.c, line 226 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUNJCi0orxSGnTIkd4:-McUNJCi0orxSGnTIkd5:b-tbewz4) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L226)):*
> ```C
>         size_t max_cpu_bitmask = BITS_TO_LONGS(cpu_cnt);
>         size_t bitmask_size_in_bytes = max_cpu_bitmask * sizeof(unsigned long);
>         unsigned long* mask = (unsigned long*)malloc(bitmask_size_in_bytes);
> ```

Cast not needed.
___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUOCRx7X6ebVxOi0Fg:-McUOCRx7X6ebVxOi0Fh:b-9ayzv4) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L249)):*
> ```C
> 
>         /* There should be atleast one bit set as part of the cpu affinity mask */
>         if (num_bits == 0)
> ```

`mask` is not freed here. Generally speaking, to avoid doing `free` everywhere we usually have a cleanup code at the end of the function and use goto in case of errors.
___
*[LibOS/shim/src/sys/shim_sched.c, line 281 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUPDeHAipygUj9UW1X:-McUPDeHAipygUj9UW1Y:bgyoygq) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L281)):*
> ```C
>     }
> 
>     return 0;
> ```

`mask` is not freed here.


<!-- Sent from Reviewable.io -->

2021-06-18 15:33 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 3 of 4 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/sys/shim_sched.c, line 223 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUNE9x6lx1GpNuo0AB:-McUemciEdvmRoGUPIrC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L223)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`.` and ` ` (space) missing at the end.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 226 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUNJCi0orxSGnTIkd4:-McUeu_TC_PWJW4qkzw1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L226)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Cast not needed.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUOCRx7X6ebVxOi0Fg:-McUezq62DFsvy1voNlh:b522hsw) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`mask` is not freed here. Generally speaking, to avoid doing `free` everywhere we usually have a cleanup code at the end of the function and use goto in case of errors.
</blockquote></details>

yes, thought of doing it the suggested way but`mask` is declared within scope of `if (cpu)...` and we need to free it at the end of this scope. Since `mask` isn't common and to avoid the additional check for error at the end of `if(cpu)..` scope didn't prefer the common code cleanup approach.

I have added the missing `free`  
___
*[LibOS/shim/src/sys/shim_sched.c, line 281 at r9](https://reviewable.io/reviews/oscarlab/graphene/2331#-McUPDeHAipygUj9UW1X:-McUhpHC14S690NaqTsb:b-mgon2o) ([raw file](https://github.com/oscarlab/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L281)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`mask` is not freed here.
</blockquote></details>

`mask` is out of scope here. But have added missing free at end of `if (cpu)...` scope.


<!-- Sent from Reviewable.io -->

2021-06-22 20:37 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 3 of 4 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_XoJtt0rJ5I6VGinhF:-McpR5Ak6Cy4gRyHHkWL:bz0cvdb) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Just to clarify, you mean I still have `:` and this needs to be removed right? Because I do have `add` in the commit one-liner which is a verb `Add partial support for getcpu syscall`
</blockquote></details>

@boryspoplawski @mkow any other suggestions/comments?  I have rebased to the latest master.

---


<!-- Sent from Reviewable.io -->

2021-07-01 20:17 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2331)* status: 2 of 6 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2331#-M_XoJtt0rJ5I6VGinhF:-MdYhbxB1ahXgPqyhIUI:bhhl69r) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

@boryspoplawski @mkow any other suggestions/comments?  I have rebased to the latest master.
</blockquote></details>

Added a new commit that adds NUMA node support to the syscall. Also, rebased to the latest master.

---


<!-- Sent from Reviewable.io -->

2021-09-10 18:55 UTC, vijaydhanraj commented
Rebased to the latest master. @mkow @boryspoplawski @dimakuv Can we please complete this review here before moving to the new repo?

2021-09-13 08:22 UTC, dimakuv requested changes
> Reviewed 2 of 4 files at r11, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2331#-M_XoJtt0rJ5I6VGinhF:-MjTEthS4vPCMX2K2R_j:b2a5cjg) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Added a new commit that adds NUMA node support to the syscall. Also, rebased to the latest master.
</blockquote></details>

Now you have two commits (first one and third one) which overwrite each other's logic of `getcpu()`. This doesn't make sense, let's just merge these two commits into one.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTEYJC0VQv1pkG2KxL:-MjTEYJDBs6FzO9RtZI1:b-80c8mb) (no related file):*
Typo in second commit message: `affintiy` -> `affinity`.

Actually, I would change the commit message to this: `[LibOS] Do not check internal threads in set/get affinity syscalls`

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 289 at r6](https://reviewable.io/reviews/gramineproject/graphene/2331#-M_3VPPY29BSBabM5AUu:-MjT79D5BFitccADUhvI:b-gnxv5t) ([raw file](https://github.com/gramineproject/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L289)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

No not that simple :). LibOS doesn't know anything about the `cpumap` yet. We need to build infrastrucute to propagate this from `PAL` to `LibOS` until that we can print a warning message if user might be misled and will create another github issue so track the change.
</blockquote></details>

To be honest, I don't understand the issue, but if it exists: please add the `log_warning` here.
___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r9](https://reviewable.io/reviews/gramineproject/graphene/2331#-McUOCRx7X6ebVxOi0Fg:-MjT5ir08YS3tdKfQk_Z:bu0evyc) ([raw file](https://github.com/gramineproject/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L249)):*
Actually, I dislike the current code. Please use `free(mask)` at the very end of this function and use `goto out` in error-handling code. This will be more readable.

> Since mask isn't common and to avoid the additional check for error at the end of if(cpu).. scope didn't prefer the common code cleanup approach.

But `mask` is very common in this function -- all return statements except the first ones use it.
___
*[LibOS/shim/src/sys/shim_sched.c, line 281 at r9](https://reviewable.io/reviews/gramineproject/graphene/2331#-McUPDeHAipygUj9UW1X:-MjT6YqIEiZMiIzri024:b-gyj6gs) ([raw file](https://github.com/gramineproject/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L281)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

`mask` is out of scope here. But have added missing free at end of `if (cpu)...` scope.
</blockquote></details>

Why out of scope? Nothing prevents you to move the `free(mask)` from above to right-before `return 0`. I would prefer to have the same code style as in other places in our code, smth like this:
```
if (something bad) {
    ret = -EINVAL;
    goto out;
}

...

    ret = 0;
out:
    free(mask);
    return ret;
```

Finding `free(mask)` in the middle of the function is tedious for code readers (just like Borys had this problem), and doesn't bring any benefits (other than the theoretical "correct scope").
___
*[LibOS/shim/src/sys/shim_sched.c, line 243 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT4vv7Df6xzfDMaCuZ:-MjT4vv81vNgREMhVBRQ:bgdtyvt) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/LibOS/shim/src/sys/shim_sched.c#L243)):*
> ```C
>     }
> 
>     /* There should be atleast one bit set as part of the cpu affinity mask. */
> ```

`atleast` -> `at least`

Can you also append something like this: `...mask (otherwise host is malicious). */`
___
*[LibOS/shim/src/sys/shim_sched.c, line 272 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT68Zd1_uYDMHtX60m:-MjT68Zd1_uYDMHtX60n:by1svvp) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/LibOS/shim/src/sys/shim_sched.c#L272)):*
> ```C
>         if (!is_user_memory_writable(cpu, sizeof(*cpu))) {
>             return -EFAULT;
>         }
> ```

We should have these `is_user_memory_writable()` checks in the very beginning of this function. Please move there
___
*[LibOS/shim/src/sys/shim_sched.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT6CDpEAGv1UAfMmGP:-MjT6CDpEAGv1UAfMmGQ:by1svvp) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/LibOS/shim/src/sys/shim_sched.c#L279)):*
> ```C
>         if (!is_user_memory_writable(node, sizeof(*node))) {
>             return -EFAULT;
>         }
> ```

We should have these `is_user_memory_writable()` checks in the very beginning of this function. Please move there
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r8](https://reviewable.io/reviews/gramineproject/graphene/2331#-McGMRfI-Wt1Hz8q7BY1:-MjT7MdI1WjgsMncpVi3:bom2t4q) ([raw file](https://github.com/gramineproject/graphene/blob/1720acdf5bede3d863ddb06a4ca666e4833a30e9/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wait, why? We don't need the `else` clause, we can just do `printf("Thread ...")` because otherwise we will exit the program.

So just:
```
if (ret < 0)
    err(EXIT_FAILURE, "sched_getcpu failed!");

printf("Thread ....");
```
___
*[Pal/src/host/Linux-common/topo_info.c, line 212 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT855A1z8fiyZ1EbDA:-MjT855A1z8fiyZ1EbDB:b-lk27d3) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L212)):*
> ```C
>         /* Initialize all cores to be part of node 0. We later update this when reading numa
>          * topology. */
>         core_topology[idx].node = 0;
> ```

Please append to the comment `; see get_numa_topo_info()`

Also, change `numa` -> `NUMA`
___
*[Pal/src/host/Linux-common/topo_info.c, line 254 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTAJA62UkrLAbzJhk_:-MjTAJA62UkrLAbzJhka:b-2nf0s) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L254)):*
> ```C
>         return possible_logical_cores;
> 
>     /* Each submap of the node cpumap is atmost 32 bits */
> ```

`at most`

Actually, can you add some example of the `cpumap` string here?
___
*[Pal/src/host/Linux-common/topo_info.c, line 256 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT98g6BeorvK2mspAA:-MjT98g6BeorvK2mspAB:b-pa7up0) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L256)):*
> ```C
>     /* Each submap of the node cpumap is atmost 32 bits */
>     int bitmap_sz = BITS_IN_TYPE(int);
>     int num_bitmaps = (possible_logical_cores > bitmap_sz) ? possible_logical_cores / bitmap_sz : 1;
> ```

This looks wrong? If `possible_logical_cores == 33`, then `num_bitmaps = 1`. But I would expect `num_bitmaps = 2`.

I think you want:
```
 int num_bitmaps = possible_logical_cores / bitmap_sz + (possible_logical_cores % bitmap_sz != 0);
```
___
*[Pal/src/host/L [...]

2021-09-14 15:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: 3 of 8 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2331#-M_XoJtt0rJ5I6VGinhF:-MjXtYWtB3MxcEtKK0I2:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now you have two commits (first one and third one) which overwrite each other's logic of `getcpu()`. This doesn't make sense, let's just merge these two commits into one.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTEYJC0VQv1pkG2KxL:-MjZb2PF4aLQQRoIZ-33:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo in second commit message: `affintiy` -> `affinity`.

Actually, I would change the commit message to this: `[LibOS] Do not check internal threads in set/get affinity syscalls`
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/sys/shim_sched.c, line 289 at r6](https://reviewable.io/reviews/gramineproject/graphene/2331#-M_3VPPY29BSBabM5AUu:-MjZbL1i2PJL7zZy8Qhb:b4a3brz) ([raw file](https://github.com/gramineproject/graphene/blob/1b5e5f8f8ff23c49bc0122e932ce40564dfe33a5/LibOS/shim/src/sys/shim_sched.c#L289)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To be honest, I don't understand the issue, but if it exists: please add the `log_warning` here.
</blockquote></details>

There is a little confusion here. This comment was before the NUMA changes were introduced and Michal was suggesting an approach to get the NUMA node info. There is no `log_warning` required here.
___
*[LibOS/shim/src/sys/shim_sched.c, line 249 at r9](https://reviewable.io/reviews/gramineproject/graphene/2331#-McUOCRx7X6ebVxOi0Fg:-MjZcgya3Ra9CWG7wehV:bk6ryx2) ([raw file](https://github.com/gramineproject/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L249)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I dislike the current code. Please use `free(mask)` at the very end of this function and use `goto out` in error-handling code. This will be more readable.

> Since mask isn't common and to avoid the additional check for error at the end of if(cpu).. scope didn't prefer the common code cleanup approach.

But `mask` is very common in this function -- all return statements except the first ones use it.
</blockquote></details>

Please see to the earlier comment on this.
___
*[LibOS/shim/src/sys/shim_sched.c, line 281 at r9](https://reviewable.io/reviews/gramineproject/graphene/2331#-McUPDeHAipygUj9UW1X:-MjZbmkA11BdurNaSzhJ:bptqbw6) ([raw file](https://github.com/gramineproject/graphene/blob/79528f6c970d02da83017d5f84e67f128aab7ab6/LibOS/shim/src/sys/shim_sched.c#L281)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why out of scope? Nothing prevents you to move the `free(mask)` from above to right-before `return 0`. I would prefer to have the same code style as in other places in our code, smth like this:
```
if (something bad) {
    ret = -EINVAL;
    goto out;
}

...

    ret = 0;
out:
    free(mask);
    return ret;
```

Finding `free(mask)` in the middle of the function is tedious for code readers (just like Borys had this problem), and doesn't bring any benefits (other than the theoretical "correct scope").
</blockquote></details>

Again, this comment was before the NUMA node patch was introduced which had `mask` inside an `if (cpu) ...` causing scope issues. But now that code is changed, I have `free(mask)` common to exit all cases.
___
*[LibOS/shim/src/sys/shim_sched.c, line 243 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT4vv7Df6xzfDMaCuZ:-MjZgVFy7ERtbVd3CfqB:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/LibOS/shim/src/sys/shim_sched.c#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`atleast` -> `at least`

Can you also append something like this: `...mask (otherwise host is malicious). */`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 272 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT68Zd1_uYDMHtX60m:-MjZga9F8R0F-YVWHBzV:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/LibOS/shim/src/sys/shim_sched.c#L272)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should have these `is_user_memory_writable()` checks in the very beginning of this function. Please move there
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sched.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT6CDpEAGv1UAfMmGP:-MjZgb8R2ZH75IwP6UAn:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/LibOS/shim/src/sys/shim_sched.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We should have these `is_user_memory_writable()` checks in the very beginning of this function. Please move there
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 34 at r8](https://reviewable.io/reviews/gramineproject/graphene/2331#-McGMRfI-Wt1Hz8q7BY1:-MjZgp-B4ISOqIzRFlEP:bhi0r0f) ([raw file](https://github.com/gramineproject/graphene/blob/1720acdf5bede3d863ddb06a4ca666e4833a30e9/LibOS/shim/test/regression/pthread_set_get_affinity.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, why? We don't need the `else` clause, we can just do `printf("Thread ...")` because otherwise we will exit the program.

So just:
```
if (ret < 0)
    err(EXIT_FAILURE, "sched_getcpu failed!");

printf("Thread ....");
```
</blockquote></details>

yes right. We don't need to have the `else` case.
___
*[Pal/src/host/Linux-common/topo_info.c, line 212 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT855A1z8fiyZ1EbDA:-MjZhZQR9nF06gZkgMK-:bb6un1j) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L212)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please append to the comment `; see get_numa_topo_info()`

Also, change `numa` -> `NUMA`
</blockquote></details>

Done
___
*[Pal/src/host/Linux-common/topo_info.c, line 254 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTAJA62UkrLAbzJhk_:-MjZi-DpAzfcpKTEVRiu:b7nup3x) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L254)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`at most`

Actually, can you add some example of the `cpumap` string here?
</blockquote></details>

Removed this code and the comment.
___
*[Pal/src/host/Linux-common/topo_info.c, line 256 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjT98g6BeorvK2mspAA:-MjZi1vy7vLp8w_L6jgd:bptnp1s) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks wrong? If `possible_logical_cores == 33`, then `num_bitmaps = 1`. But I would expect `num_bitmaps = 2`.

I thin [...]

2021-09-15 07:07 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 259 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTBONh1vRD9vgMzUEs:-MjcCgmL2TFqXuQXJYGf:b-uhik7z) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L259)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

We need to skip `,` to get the next bitmap from the `cpumap`. 

`,` is legit. Here how the output looks,
```
cat /sys/devices/system/node/node0/cpumap                                                                    
00000000,ffffffff,00000000,ffffffff
```
</blockquote></details>

What I meant is that `,` cannot happen *at the very beginning* of this string. You can't have formats like `,00000000,ffffffff, ...`.

But anyway, this is nitpicking, I resolve this comment.
___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-MjcErmfEX2V4IEeb_0Z:b-d6sgch) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I don't think `cpu` can go out of bounds. `cpu` is value is based on 
1) `num_bitmaps` which is nothing but `possible_logical_cores` which is the same as `online_logical_cores` which is the size of the array as we don't support core offlining yet. (Say for example this is 4 for a system having 128 cores)
2) `bitmap_sz` is nothing but `BITS_IN_TYPE(int)` which is 32
3) `pos` is based on `bitmap` which cannot be more than 31.

Given this cpu can at most have `3*32+31` which is `127`.
</blockquote></details>

But I was talking about the array access `core_topology[cpu]` going out of bounds, no the variable `cpu` itself going out of bounds.

For example, we have `possible_logical_cores = 1` (single-core system) and we got `cpumap = "00000003"` (maliciously reports two cores in the system). Then, on the second iteration of this for loop:

`int cpu = (num_bitmaps - 1) * BITS_IN_TYPE(int) + pos = (1 - 1) * 4 + 1 = 1`

Which means `core_topology[1].node = ...` -- but the array doesn't have this second item! And we have a buffer overflow.
___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTE8qy3igAHGkSeLRh:-MjcG-T47C0WjcNzbmGv:b4vix5e) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is tricky since `node == 0` is valid, this check will cause make the parsing fail even in the correct cases. Maybe instead of initializing this value to `0` we can have it as `UNIT32_MAX` and check against this. 

But I think the better way will be to do sanitization checks inside the enclave for `TOCTOU`. I have added NUMA sanitization case as part sysfs refactoring PR which should catch such cases.

</blockquote></details>

Can you at least add a TODO comment here, so that if some poor soul uses this commit (before your sysfs sanitization PR), she will at least know that there is a potential problem in this code?

Smth like: `/* TODO: check that one CPU does not belong to two NUMA domains */`
___
*[Pal/src/host/Linux-common/topo_info.c, line 269 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcCvjW967VBnSyuSzM:-MjcCvjW967VBnSyuSzN:b-5fnyw4) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L269)):*
> ```C
>             return -EINVAL;
> 
>         /* cpumap is represented by comma seperated unsigned 32-bit integers ranging upto the total
> ```

`seperated` -> `separated`

`ranging upto` -> `summing up to` (? I'm not sure I understood your comment correctly)

`total processors` -> `total number of cores` (note `cores`, for consistency with your other comments)
___
*[Pal/src/host/Linux-common/topo_info.c, line 280 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcDup84PNgrUNSa_nI:-MjcDup9-_YUF3y9IsRf:b13282q) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L280)):*
> ```C
> 
>         /* Number of 32-bit unsigned `bitmap` to represent `cpumap` exceeds the number of cores
>          * present in the system. */
> ```

Please expand a bit:
```
Number of 32-bit unsigned `bitmap` integers read from the `cpumap` string exceeds ...
```
___
*[Pal/src/host/Linux-SGX/db_main.c, line 348 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcGTHf-MI4dN658Khy:-MjcGTHf-MI4dN658Khz:bdrt89i) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-SGX/db_main.c#L348)):*
> ```C
>     int64_t cpumap;
>     for (int64_t idx = 0; idx < num_nodes; idx++) {
>         cpumap =+ count_bits_set_from_resource_map(numa_topology[idx].cpumap);
> ```

What is going on here? `=+` is equivalent to `=`, so how does this help?

Did you want to do `+=`? In this case, you should also do `int64_t cpumap = 0` (init with zero). And also, please rename `cpumap` to smth like `num_bits_in_cpumap`.


<!-- Sent from Reviewable.io -->

2021-09-15 15:52 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: 5 of 8 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-Mjdw6Yp5sNZ7F6_ceVD:b-fuoqlh) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But I was talking about the array access `core_topology[cpu]` going out of bounds, no the variable `cpu` itself going out of bounds.

For example, we have `possible_logical_cores = 1` (single-core system) and we got `cpumap = "00000003"` (maliciously reports two cores in the system). Then, on the second iteration of this for loop:

`int cpu = (num_bitmaps - 1) * BITS_IN_TYPE(int) + pos = (1 - 1) * 4 + 1 = 1`

Which means `core_topology[1].node = ...` -- but the array doesn't have this second item! And we have a buffer overflow.
</blockquote></details>

I see what you are saying. Yes, this is true and we should keep track of this across nodes. I have added a check which keeps track of the number of cores read from `cpumap` part of a node and fails if it exceeds the total count.
___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTE8qy3igAHGkSeLRh:-MjdxX545GcxS6nstsls:b-zao9gt) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you at least add a TODO comment here, so that if some poor soul uses this commit (before your sysfs sanitization PR), she will at least know that there is a potential problem in this code?

Smth like: `/* TODO: check that one CPU does not belong to two NUMA domains */`
</blockquote></details>

This is basically sanitization, right? Adding such a comment here might not help as the malicious host can change before we use this variable. I have added such a comment in `sanitize_numa_topology_info()`
___
*[Pal/src/host/Linux-common/topo_info.c, line 269 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcCvjW967VBnSyuSzM:-MjdzhoL7O6BtIsCZDXd:b-z18vny) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L269)):*
>ranging upto -> summing up to (? I'm not sure I understood your comment correctly)
In this context, `cpumap` represents cores that are part of particular a single NUMA node, which in most cases (except single NUMA node) will not be all the cores present in the system. So, I have `ranging` instead of `summing`
___
*[Pal/src/host/Linux-common/topo_info.c, line 280 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcDup84PNgrUNSa_nI:-Mje1AHH58mftCATgpu0:bw7a5u4) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please expand a bit:
```
Number of 32-bit unsigned `bitmap` integers read from the `cpumap` string exceeds ...
```
</blockquote></details>

This part of your suggestion `...read from the cpumap` might mislead the readers. We don't get `num_bits` from cpumap but from `possible_logical_cores`. `num_bits` basically tells us how many (comma separated unsigned 32-bit integers) bitmaps can be part of `cpumap`. Given this, I feel the comment makes sense here.

If it is still unclear, we can try rewording.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 348 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcGTHf-MI4dN658Khy:-Mje42Eq81sDO4ubDswS:bhxhnwx) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-SGX/db_main.c#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is going on here? `=+` is equivalent to `=`, so how does this help?

Did you want to do `+=`? In this case, you should also do `int64_t cpumap = 0` (init with zero). And also, please rename `cpumap` to smth like `num_bits_in_cpumap`.
</blockquote></details>

Oops, my bad I meant `+=`. Done.


<!-- Sent from Reviewable.io -->

2021-09-15 15:53 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: 5 of 8 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 269 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcCvjW967VBnSyuSzM:-Mje9Kc42y8z6O2bUDgb:b-oqv50) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L269)):*
>ranging upto -> summing up to (? I'm not sure I understood your comment correctly)

In this context, cpumap represents cores that are part of particular a single NUMA node, which in most cases (except single NUMA node) will not be all the cores present in the system. So, I have ranging instead of summing


<!-- Sent from Reviewable.io -->

2021-09-16 07:28 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-MjhV1z9CV4Jz3aC1qDX:bdmculz) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I see what you are saying. Yes, this is true and we should keep track of this across nodes. I have added a check which keeps track of the number of cores read from `cpumap` part of a node and fails if it exceeds the total count.
</blockquote></details>

Your added change is good, but does it fix my example? I don't see that it does.
___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTE8qy3igAHGkSeLRh:-MjhVJXC0mT4HLWLwrh_:bf5cchd) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This is basically sanitization, right? Adding such a comment here might not help as the malicious host can change before we use this variable. I have added such a comment in `sanitize_numa_topology_info()`
</blockquote></details>

Where did you add it? I don't see any new comment in this PR.
___
*[Pal/src/host/Linux-common/topo_info.c, line 269 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcCvjW967VBnSyuSzM:-MjhT0XSDI2YBGjvyy9p:bsk1llf) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L269)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

>ranging upto -> summing up to (? I'm not sure I understood your comment correctly)

In this context, cpumap represents cores that are part of particular a single NUMA node, which in most cases (except single NUMA node) will not be all the cores present in the system. So, I have ranging instead of summing
</blockquote></details>

I still don't like the sentence you have in the comment. But I like the wording you used now. So maybe `cpumap is represented by comma separated unsigned 32-bit integers, representing cores that are part of a particular NUMA node.`?
___
*[Pal/src/host/Linux-common/topo_info.c, line 280 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcDup84PNgrUNSa_nI:-MjhU-8y18c38ihQduJk:b-z7i022) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L280)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

This part of your suggestion `...read from the cpumap` might mislead the readers. We don't get `num_bits` from cpumap but from `possible_logical_cores`. `num_bits` basically tells us how many (comma separated unsigned 32-bit integers) bitmaps can be part of `cpumap`. Given this, I feel the comment makes sense here.

If it is still unclear, we can try rewording.
</blockquote></details>

But I didn't talk about `num_bitmaps`. Your comment talks about `bitmap` -- and `bitmap` is read from the `cpumap`. So your comment says smth like "The number of 32-bit chunks present in the possibly-malicious cpumap string exceeds the number of cores actually present in the system". Your comment is correct, but I wanted to be more explicit that this `bitmap` sub-string comes from the larger and user-supplied and possibly-malicious `cpumap`.
___
*[Pal/src/host/Linux-common/topo_info.c, line 259 at r14](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjhUfmq6pdkv5U_FJJh:-MjhUfmq6pdkv5U_FJJi:b-8c92cg) ([raw file](https://github.com/gramineproject/graphene/blob/2a8de9348dd3460aa10977bb2e86ac319c20116e/Pal/src/host/Linux-common/topo_info.c#L259)):*
> ```C
> 
>     int num_bitmaps = BITS_TO_INTS(possible_logical_cores);
>     static int total_online_cores = 0;
> ```

Why `static`? Is this because you will call this function several times? In this case, this is correct, but you need to move this variable to the very top of this function and add a big comment explaining why static.


<!-- Sent from Reviewable.io -->

2021-09-16 21:01 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-Mjj59P20TTaFJYPTb6-:bxkybu5) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Your added change is good, but does it fix my example? I don't see that it does.
</blockquote></details>

In your example, you have `cpumap` having more bits set than the array size of `core_topology[X]` which can trigger a buffer overflow, right? 

So, the new logic keeps a track of the number of bits set in the `cpumap` across nodes. If this count is greater than the total number of online cores, then we fail right away and we won't even hit the line where the array is accessed. (Note: Number of elements in `core_topology[]` is equal to `online_logical_cores`. With no cores offlined, `online_logical_cores == `possible_logical_cores`)

Applying this logic, if we have `cpumap = 00000003` and `online_logical_cores = 1`, in the first iteration, the below condition will fail but in the 2nd iteration `total_online_cores` will become greater than `online_logical_cores` and the condition will succeed, and exit. The array will not even be accessed.

```
                if (total_online_cores > online_logical_cores)
                    return -EINVAL;
```
___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTE8qy3igAHGkSeLRh:-MjjBvAl1xkfRDH661Ze:bn92sbz) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Where did you add it? I don't see any new comment in this PR.
</blockquote></details>

Please see here, https://github.com/gramineproject/graphene/pull/2331/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R353
___
*[Pal/src/host/Linux-common/topo_info.c, line 269 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcCvjW967VBnSyuSzM:-MjkHlzw7B4xjlD0f2ms:b-nozrp) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still don't like the sentence you have in the comment. But I like the wording you used now. So maybe `cpumap is represented by comma separated unsigned 32-bit integers, representing cores that are part of a particular NUMA node.`?
</blockquote></details>

Modified it a bit but have included this text.
___
*[Pal/src/host/Linux-common/topo_info.c, line 280 at r13](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjcDup84PNgrUNSa_nI:-MjkH0s2B9G2mSKboiOt:b-dyvv8p) ([raw file](https://github.com/gramineproject/graphene/blob/d96e4f46f44784b4eb0dd6b5e7fdb41434bc6d24/Pal/src/host/Linux-common/topo_info.c#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But I didn't talk about `num_bitmaps`. Your comment talks about `bitmap` -- and `bitmap` is read from the `cpumap`. So your comment says smth like "The number of 32-bit chunks present in the possibly-malicious cpumap string exceeds the number of cores actually present in the system". Your comment is correct, but I wanted to be more explicit that this `bitmap` sub-string comes from the larger and user-supplied and possibly-malicious `cpumap`.
</blockquote></details>

OK, modified the comment a bit. Hope this clarifies the point here.
___
*[Pal/src/host/Linux-common/topo_info.c, line 259 at r14](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjhUfmq6pdkv5U_FJJh:-MjkMKDi3VJVbsbQhKey:b-9ea8wo) ([raw file](https://github.com/gramineproject/graphene/blob/2a8de9348dd3460aa10977bb2e86ac319c20116e/Pal/src/host/Linux-common/topo_info.c#L259)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `static`? Is this because you will call this function several times? In this case, this is correct, but you need to move this variable to the very top of this function and add a big comment explaining why static.
</blockquote></details>

yes, that is the case. It will be called for each NUMA node, and we want to accumulate cores that are part of each NUMA node.

I have added a comment and moved the declaration to the top.


<!-- Sent from Reviewable.io -->

2021-09-17 09:00 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-Mjmy9eV2oLi91mBEWap:b-q9mzu1) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

In your example, you have `cpumap` having more bits set than the array size of `core_topology[X]` which can trigger a buffer overflow, right? 

So, the new logic keeps a track of the number of bits set in the `cpumap` across nodes. If this count is greater than the total number of online cores, then we fail right away and we won't even hit the line where the array is accessed. (Note: Number of elements in `core_topology[]` is equal to `online_logical_cores`. With no cores offlined, `online_logical_cores == `possible_logical_cores`)

Applying this logic, if we have `cpumap = 00000003` and `online_logical_cores = 1`, in the first iteration, the below condition will fail but in the 2nd iteration `total_online_cores` will become greater than `online_logical_cores` and the condition will succeed, and exit. The array will not even be accessed.

```
                if (total_online_cores > online_logical_cores)
                    return -EINVAL;
```
</blockquote></details>

Hm, `cpumap = "00000003"` was an unfortunate example.

Let's say we have a single-core system and `cpumap = "00000002"` (only one core reported, but this is the *second* core). Then you get into this code snippet only on the second iteration of the for loop, when `pos = 1`. After `total_online_cores++`, you have `total_online_cores = online_logical_cores = 1`, so the code doesn't return EINVAL and proceeds to:
```
int cpu = (num_bitmaps - 1) * BITS_IN_TYPE(int) + pos;
// this leads to cpu = (1 - 1) * 32 + 1 = 1

core_topology[cpu].node = node;
// this accesses core_topology[1] which is a buffer overflow!
```

Or am I missing something again?


<!-- Sent from Reviewable.io -->

2021-09-19 03:23 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-Mjvl8jT5Z-CiVttRTDs:b-dzrelb) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, `cpumap = "00000003"` was an unfortunate example.

Let's say we have a single-core system and `cpumap = "00000002"` (only one core reported, but this is the *second* core). Then you get into this code snippet only on the second iteration of the for loop, when `pos = 1`. After `total_online_cores++`, you have `total_online_cores = online_logical_cores = 1`, so the code doesn't return EINVAL and proceeds to:
```
int cpu = (num_bitmaps - 1) * BITS_IN_TYPE(int) + pos;
// this leads to cpu = (1 - 1) * 32 + 1 = 1

core_topology[cpu].node = node;
// this accesses core_topology[1] which is a buffer overflow!
```

Or am I missing something again?
</blockquote></details>

Can we have holes in cpu numbering? IIUC, this isn't a valid case as linux assigns cpu numbers from `0` to `NR_CPUS-1`. So, if we have just 1 cpu, then only 1st bit should be set (position 0). 

This scenario is valid when we have core offling support, but currently, we don't support this feature.


<!-- Sent from Reviewable.io -->

2021-09-19 11:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-MjxjGbx6uPKFLlZGwhb:bh5qtsk) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
> This scenario is valid when we have core offling support, but currently, we don't support this feature.

Isn't this situation triggerable from the host right now? I.e. the untrusted host can trigger this OOB access? Regardless of what we declare as supported, we can't trust the host.

Also, even if we have the check somewhere, this is very brittle - imagine what happens if we add offlining support at some point. We'll update the sanitization code to support it, but how can we know that there's this magic place here, which will trigger memory corruptions when some CPUs are offline?


<!-- Sent from Reviewable.io -->

2021-09-19 14:17 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: 7 of 8 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-MjyLXKb1QsACBwCuAo6:bdfd86n) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
> Regardless of what we declare as supported, we can't trust the host.
OK, added the following check which will prevent OOB access
```
+                /* cpu extracted from cpumap cannot be greater than or equal to total number of
+                 * cores. cpu value ranges from 0 to number of cores in system - 1. */
                 int cpu = (num_bitmaps - 1) * BITS_IN_TYPE(int) + pos;
+                if (cpu >= online_logical_cores)
+                    return -EINVAL;
```

> how can we know that there's this magic place here, which will trigger memory corruptions when some CPUs are offline
When we introduce offlining support we need to revisit the code and allocate `core_topology[]`having `possible_logical_cores` instead of `online_logical_cores` elements. Then check we stay within the bounds when accessing the array.


<!-- Sent from Reviewable.io -->

2021-09-19 14:20 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: 7 of 8 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-MjyQE9c800i5EcmV-Oe:b-bv7a2t) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
> Regardless of what we declare as supported, we can't trust the host.

OK, added the following check which will prevent OOB access

```
+                /* cpu extracted from cpumap cannot be greater than or equal to total number of
+                 * cores. cpu value ranges from 0 to number of cores in system - 1. */
                 int cpu = (num_bitmaps - 1) * BITS_IN_TYPE(int) + pos;
+                if (cpu >= online_logical_cores)
+                    return -EINVAL;
```

> how can we know that there's this magic place here, which will trigger memory corruptions when some CPUs are offline

When we introduce offlining support we need to revisit the code and allocate core_topology[]having possible_logical_cores instead of online_logical_cores elements. Then check we stay within the bounds when accessing the array.


<!-- Sent from Reviewable.io -->

2021-09-21 07:54 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 35 at r16](https://reviewable.io/reviews/gramineproject/graphene/2331#-Mk6LNTu4OZYBu_4Z9_N:-Mk6LNTu4OZYBu_4Z9_O:b-evzizs) ([raw file](https://github.com/gramineproject/graphene/blob/b0f7da096f0d1e53b9a4fb3f7751b053a641b211/LibOS/shim/test/regression/pthread_set_get_affinity.c#L35)):*
> ```C
> 
>     unsigned int cpu, node;
>     int ret =  syscall(SYS_getcpu, &cpu, &node);
> ```

Double space before `syscall`
___
*[Pal/src/host/Linux-common/topo_info.c, line 279 at r12](https://reviewable.io/reviews/gramineproject/graphene/2331#-MjTDzrm75aoKzEsvSIm:-Mk6KWuF87VYAmbU9UwE:b-htzkw5) ([raw file](https://github.com/gramineproject/graphene/blob/3f56c8e23d610dbb50049f7f09f397f87823e8b6/Pal/src/host/Linux-common/topo_info.c#L279)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

> Regardless of what we declare as supported, we can't trust the host.

OK, added the following check which will prevent OOB access

```
+                /* cpu extracted from cpumap cannot be greater than or equal to total number of
+                 * cores. cpu value ranges from 0 to number of cores in system - 1. */
                 int cpu = (num_bitmaps - 1) * BITS_IN_TYPE(int) + pos;
+                if (cpu >= online_logical_cores)
+                    return -EINVAL;
```

> how can we know that there's this magic place here, which will trigger memory corruptions when some CPUs are offline

When we introduce offlining support we need to revisit the code and allocate core_topology[]having possible_logical_cores instead of online_logical_cores elements. Then check we stay within the bounds when accessing the array.
</blockquote></details>

OK, the new check (and the corresponding comment) looks good to me. Thanks!
___
*[Pal/src/host/Linux-SGX/db_main.c, line 353 at r16](https://reviewable.io/reviews/gramineproject/graphene/2331#-Mk6LFW91BQdOuaUzFSc:-Mk6LFWA1sh2odDhpoZF:b-ffgp5o) ([raw file](https://github.com/gramineproject/graphene/blob/b0f7da096f0d1e53b9a4fb3f7751b053a641b211/Pal/src/host/Linux-SGX/db_main.c#L353)):*
> ```C
>             return -EINVAL;
>     }
>     /* TODO: Ensure each NUMA has unique set of cores and there is no overlap */
> ```

`...NUMA has...` -> `...NUMA node has...`

Also, please add an empty line before this TODO comment.


<!-- Sent from Reviewable.io -->

2021-09-21 17:02 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: 6 of 8 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @vijaydhanraj)

___
*[LibOS/shim/test/regression/pthread_set_get_affinity.c, line 35 at r16](https://reviewable.io/reviews/gramineproject/graphene/2331#-Mk6LNTu4OZYBu_4Z9_N:-Mk8FcqtD1txpUvmx5sL:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/b0f7da096f0d1e53b9a4fb3f7751b053a641b211/LibOS/shim/test/regression/pthread_set_get_affinity.c#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Double space before `syscall`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 353 at r16](https://reviewable.io/reviews/gramineproject/graphene/2331#-Mk6LFW91BQdOuaUzFSc:-Mk8Ii124UiLIHxje6fD:bs7wumb) ([raw file](https://github.com/gramineproject/graphene/blob/b0f7da096f0d1e53b9a4fb3f7751b053a641b211/Pal/src/host/Linux-SGX/db_main.c#L353)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...NUMA has...` -> `...NUMA node has...`

Also, please add an empty line before this TODO comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-21 18:19 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2331)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2331#-Mk8_7Te6VYmorVd-p6g:-Mk8_7Te6VYmorVd-p6h:b-6okr7q) (no related file):*
Blocking this PR on https://github.com/gramineproject/graphene/pull/2661 (this PR should be merged *after* that PR)

---


<!-- Sent from Reviewable.io -->

2022-09-06 18:36 UTC, closed without merging