Rewrite path lookup functions
oscarlab/graphene pull request #2333
Opened 2021-04-26 12:19 UTC by pwmarcz

This is the next step in FS rewrite, after #2324 (the first commit should disappear after merging #2324).

See also the issue for dentry cleanup (#2321).

Initially, I wanted to reverse the "follow symlinks" semantics (`LOOKUP_FOLLOW` -> `LOOKUP_NO_FOLLOW`). I decided against that after seeing Linux and BSD have a flag like that, but found that FreeBSD has a convention to *also* use `NOFOLLOW` (defined as zero) to make the code clearer.

Apart from that (and general cleanup), the most important change is `LOOKUP_CREATE` and not returning `-ENOENT` when the file can be created.

Next step: rewrite `mount_fs` and make mount semantics more sane (as mentioned in #2324).

2021-04-26 14:15 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: 0 of 17 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 261 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZDWNKH7MPCVry6rT_-:-MZDWNKH7MPCVry6rT_0:b34u3t5) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/fs/shim_dcache.c#L261)):*
> ```C
> #define DUMP_FLAG(flag, s, empty) buf_puts(&buf, (dent->state & flag) ? s : empty)
> 
> static void dump_dentry(struct shim_dentry* dent, unsigned int level) {
> ```

For now, I'm manually adding `dump_dentry(NULL);` in `libos_clean_and_exit()`. Any idea how best I can enable it without having to make local modifications to the code? I would stick it at `log_trace()`, but it's probably not useful if you're not working on the filesystem specifically.


<!-- Sent from Reviewable.io -->

2021-04-27 12:41 UTC, dimakuv requested changes
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHd2KcCckxkdQH3Uao:-MZHd2Kd8zhmedQuuweJ:bu9se5) (no related file):*
> Instead, the code now treats such cases as a success and create a

Typo in commit message: `create` -> `creates`.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHdTJI9xzzUoP1RJyL:-MZHdTJI9xzzUoP1RJyM:b-zxr5h) (no related file):*
>   This also adds a LOOKUP_NO_FOLLOW value to make the the call sites

One more typo in commit message: `the the` -> `the`

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZILG_UCwtx7w7zUnHQ:-MZILG_UCwtx7w7zUnHR:b-51d0kj) (no related file):*
Awesome PR!

---
___
*[LibOS/shim/include/shim_fs.h, line 220 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHe29OAvhy_xrZQmNK:-MZHe29OAvhy_xrZQmNL:b-ebc9gp) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L220)):*
> ```objc
> };
> 
> /* TODO: This actually does not get migrated after a fork, we just copy `g_process.root` */
> ```

Is `g_process.root` equal to `g_dentry_root`? In this case, you're right, we should simply use the migration mechanism instead of copying.
___
*[LibOS/shim/include/shim_fs.h, line 225 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHeDatAVVeQIBzxqKD:-MZHeDatAVVeQIBzxqKE:b4ejiz2) ([raw file](https://github.com/oscarlab/graphene/blob/658de0e002ac782e2effc9334db359a4e09c879a/LibOS/shim/include/shim_fs.h#L225)):*
> ```objc
> #define LOOKUP_DIRECTORY 002
> #define LOOKUP_CONTINUE  004  // No longer needed
> #define LOOKUP_PARENT    010  // Not sure we need this
> ```

I just love these old comments! :)
___
*[LibOS/shim/include/shim_fs.h, line 308 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHeuL1CSwAmrsiSopp:-MZHeuL24Uk3lW4BYQ2S:b-tg93bt) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L308)):*
> ```objc
>  * -ENOENT).
>  */
> int check_permissions(struct shim_dentry* dent, mode_t mask);
> ```

Shouldn't you start this function name with `_` because it assumes a lock?
___
*[LibOS/shim/include/shim_fs.h, line 316 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHemLW6grBwucNuZgm:-MZHemLW6grBwucNuZgn:b97mf7b) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L316)):*
> ```objc
>  * LOOKUP_NO_FOLLOW as a pseudo-flag for readability.
>  *
>  * This is modeled after Linux and and BSD codebases, which define a positive FOLLOW flag, and a
> ```

typo: `and and` -> `and`
___
*[LibOS/shim/include/shim_fs.h, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHg-AiD2COycKnqUd6:-MZHg-AiD2COycKnqUd7:b9k1syy) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L337)):*
> ```objc
>  *
>  * On success, returns 0, and puts the found dentry in `*new`. The reference count of the dentry
>  * will be increased by one.
> ```

`increased by one` == `set to one`? The wording is confusing -- we just created the dentry and we set the refcount, there is nothing to increase.
___
*[LibOS/shim/include/shim_fs.h, line 340 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHgHs02-HBFtSp2DOz:-MZHgHs02-HBFtSp2DP-:b4lmu7h) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L340)):*
> ```objc
>  *
>  * On failure, returns a negative error code, and sets `*new` to NULL. (Note that in case of
>  * LOOKUP_CREATE, not all file-not-found errors are considered a failure).
> ```

What does this mean? Could you give an example? By `file-not-found errors`, do you mean `-ENOENT` or do you mean `file isn't there but can be created`?
___
*[LibOS/shim/include/shim_fs.h, line 385 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHhh5b5orpdzyO6T-8:-MZHhh5c4-aSgZkUlINZ:bk732z1) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L385)):*
> ```objc
>  * \param[out] hdl handle to initialize, can be NULL
>  * \param start the start dentry for relative paths, or NULL (in which case it will default to
>  * process' cwd)
> ```

You missed `\param path`
___
*[LibOS/shim/include/shim_fs.h, line 388 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHiDyf4nk1nWUwEHEm:-MZHhjd_0JGWHyM8kWSc:bw1g971) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L388)):*
> ```objc
>  * \param flags Unix open flags (see below)
>  * \param mode Unix file mode, used when creating a new file/directory
>  * \param[out] new pointer to retrieved dentry, can be NULL
> ```

Why `new`? Should be `dent`
___
*[LibOS/shim/include/shim_fs.h, line 396 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHiNVfEfAeX7CAc29D:-MZHiNVfEfAeX7CAc29E:bw1g971) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L396)):*
> ```objc
>  * will be just retrieved or created.
>  *
>  * If `new` is provided, on success it will be set to the files's dentry (and its reference count
> ```

Why `new`? Should be `dent`
___
*[LibOS/shim/include/shim_fs.h, line 396 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHiOMmEAvZWVJSYO4o:-MZHiOMmEAvZWVJSYO4p:bgknppj) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L396)):*
> ```objc
>  * will be just retrieved or created.
>  *
>  * If `new` is provided, on success it will be set to the files's dentry (and its reference count
> ```

Typo: `files's dentry` -> `file's dentry`
___
*[LibOS/shim/include/shim_fs.h, line 407 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHicylDakcKWq6iQQf:-MZHicylDakcKWq6iQQg:b-a3ene) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L407)):*
> ```objc
>  * - O_TRUNC: truncate the file after opening
>  *
>  * The flags (including any not listed above), as well as file mode, are passed to the underlying
> ```

Why "including any not listed above"? Is this how Linux does it? Shouldn't we check and restrict the possible flags, just like we do in other places (e.g. `mmap` and `futex`)?
___
*[LibOS/shim/include/shim_fs.h, line 414 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHjF5E7RXk5okTiD_Z:-MZHjF5E7RXk5okTiD__:b-lgzwyf) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L414)):*
> ```objc
> 
> /*
>  * \brief Open an already retrieved dentry
> ```

`...and associate hdl with it`
___
*[LibOS/shim/include/shim_fs.h, line 416 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHjKH_73SXG2AWECAb:-MZHjKH_73SXG2AWECAc:b-3wh0of) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L416)):*
> ```objc
>  * \brief Open an already retrieved dentry
>  *
>  * \param[out] hdl handle to initialize
> ```

Maybe not `initialize` but `associate with the opened dent`?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 261 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZDWNKH7MPCVry6rT_-:-MZHvu533cm_bog2sC-Q:b-ml3kzt) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/fs/shim_dcache.c#L261)):*
<details><su [...]

2021-04-27 14:55 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: 13 of 17 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHd2KcCckxkdQH3Uao:-MZIhjcy9LER4MgxNH8K:bt2vr1b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Instead, the code now treats such cases as a success and create a

Typo in commit message: `create` -> `creates`.
</blockquote></details>

Fixed.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHdTJI9xzzUoP1RJyL:-MZIhmDJ9FiZ5_IPdfbc:bt2vr1b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

>   This also adds a LOOKUP_NO_FOLLOW value to make the the call sites

One more typo in commit message: `the the` -> `the`
</blockquote></details>

Fixed.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZILG_UCwtx7w7zUnHQ:-MZIhnF_-LsbjoG0o5bL:b-ucfknh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Awesome PR!
</blockquote></details>

Thanks!

---
___
*[LibOS/shim/include/shim_fs.h, line 220 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHe29OAvhy_xrZQmNK:-MZISaT1Enbo5eJQ8ks1:bczms3k) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is `g_process.root` equal to `g_dentry_root`? In this case, you're right, we should simply use the migration mechanism instead of copying.
</blockquote></details>

I meant we migrate `g_process.root`, but leave `g_dentry_root` alone and it points to an empty directory. I reworded the comment.

Additional context:

- After initialization, we use `g_process.root` pretty much everywhere, which is why this went undetected
- The two are not necessarily the same, because we support chroot (although I'm not sure how good that support is).
___
*[LibOS/shim/include/shim_fs.h, line 308 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHeuL1CSwAmrsiSopp:-MZITjquDW6QIUGeVuP5:b-1a3p4x) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L308)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't you start this function name with `_` because it assumes a lock?
</blockquote></details>

Do we have this convention? I thought `_func` is a version of `func` that assumes a lock, but if there's only one of them, there's no need to mark them this way.

And from the looks of it (there are other functions such as `lookup_dcache`, `get_new_dentry` etc. that also assume the lock) I think it's not worth it to enforce a naming convention for all functions requiring the lock. (Also, while it's not checked statically, in DEBUG mode mistakes are easy to notice at runtime because of the asserts).
___
*[LibOS/shim/include/shim_fs.h, line 316 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHemLW6grBwucNuZgm:-MZIV8of5KWzqBPiq3eU:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L316)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

typo: `and and` -> `and`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHg-AiD2COycKnqUd6:-MZIVA5R7q6SYgxqe4Rd:b-e5yvah) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L337)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`increased by one` == `set to one`? The wording is confusing -- we just created the dentry and we set the refcount, there is nothing to increase.
</blockquote></details>

This function does not necessarily create a new dentry. And even if it does, it adds it to the cache first, so there is one extra reference above the ones in cache.

I guess `new` is a pretty bad name. Changed to`found`.
___
*[LibOS/shim/include/shim_fs.h, line 340 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHgHs02-HBFtSp2DOz:-MZIXbmrBbJ3ZKUXhroU:b-i8344n) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L340)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does this mean? Could you give an example? By `file-not-found errors`, do you mean `-ENOENT` or do you mean `file isn't there but can be created`?
</blockquote></details>

Yeah, it's not clear here. I meant that there are circumstances when the file does not exist but this function succeeds (if `LOOKUP_CREATE` is set).

I reworded the description: the description of `LOOKUP_CREATE` elaborates on this case, and here I just say that it is the only case in which we return a negative dentry. Is that better?
___
*[LibOS/shim/include/shim_fs.h, line 385 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHhh5b5orpdzyO6T-8:-MZIYq5k03pxXwDtLoYA:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L385)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You missed `\param path`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 388 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHiDyf4nk1nWUwEHEm:-MZIYqo92E8bAidXuGcd:b-csuwfw) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L388)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `new`? Should be `dent`
</blockquote></details>

I renamed it to `found`, for consistency with `path_lookupat`.
___
*[LibOS/shim/include/shim_fs.h, line 396 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHiNVfEfAeX7CAc29D:-MZIZ5x74KOtxIa5G69m:b-csuwfw) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L396)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `new`? Should be `dent`
</blockquote></details>

I renamed it to `found`, for consistency with `path_lookupat`.
___
*[LibOS/shim/include/shim_fs.h, line 396 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHiOMmEAvZWVJSYO4o:-MZIhvZmA_7dPpxnPq27:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L396)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `files's dentry` -> `file's dentry`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 407 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHicylDakcKWq6iQQf:-MZIZXqe2KPfNo0YDt5o:b-u4cukv) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L407)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why "including any not listed above"? Is this how Linux does it? Shouldn't we check and restrict the possible flags, just like we do in other places (e.g. `mmap` and `futex`)?
</blockquote></details>

Is this the right place, though? This function is a proxy, and needs to ha [...]

2021-04-27 16:59 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHd2KcCckxkdQH3Uao:-MZJCsiP97bljMzh0Am4:bc25yqy) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

I don't see any changes in the commit messages?

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHdTJI9xzzUoP1RJyL:-MZJD-Oy8krAk6ZPELgQ:b-7ropln) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

ditto

---
___
*[LibOS/shim/include/shim_fs.h, line 220 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHe29OAvhy_xrZQmNK:-MZJD6yq6FhNGf96XxdD:b1sdurx) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L220)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I meant we migrate `g_process.root`, but leave `g_dentry_root` alone and it points to an empty directory. I reworded the comment.

Additional context:

- After initialization, we use `g_process.root` pretty much everywhere, which is why this went undetected
- The two are not necessarily the same, because we support chroot (although I'm not sure how good that support is).
</blockquote></details>

OK, thanks, now the comment is good and I understand the issue.
___
*[LibOS/shim/include/shim_fs.h, line 308 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHeuL1CSwAmrsiSopp:-MZJDLeA70TrwJFfyn0T:b-1xfk04) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L308)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Do we have this convention? I thought `_func` is a version of `func` that assumes a lock, but if there's only one of them, there's no need to mark them this way.

And from the looks of it (there are other functions such as `lookup_dcache`, `get_new_dentry` etc. that also assume the lock) I think it's not worth it to enforce a naming convention for all functions requiring the lock. (Also, while it's not checked statically, in DEBUG mode mistakes are easy to notice at runtime because of the asserts).
</blockquote></details>

OK, agreed. I had a feeling that "global function + assumes lock" means "start with underscore". But apparently not the case.
___
*[LibOS/shim/include/shim_fs.h, line 337 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHg-AiD2COycKnqUd6:-MZJDh7ODeCox9-jkCEO:b48iuai) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L337)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This function does not necessarily create a new dentry. And even if it does, it adds it to the cache first, so there is one extra reference above the ones in cache.

I guess `new` is a pretty bad name. Changed to`found`.
</blockquote></details>

OK. Thanks, this is better.
___
*[LibOS/shim/include/shim_fs.h, line 340 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHgHs02-HBFtSp2DOz:-MZJDtHg4amJc6VL2DO_:b1lnnh2) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L340)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, it's not clear here. I meant that there are circumstances when the file does not exist but this function succeeds (if `LOOKUP_CREATE` is set).

I reworded the description: the description of `LOOKUP_CREATE` elaborates on this case, and here I just say that it is the only case in which we return a negative dentry. Is that better?
</blockquote></details>

OK, perfect.
___
*[LibOS/shim/include/shim_fs.h, line 407 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHicylDakcKWq6iQQf:-MZJE8UJ--E126V4eOte:b-a96i19) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/include/shim_fs.h#L407)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Is this the right place, though? This function is a proxy, and needs to handle only some of the flags. It's not the syscall entrypoint such as `shim_do_openat` - maybe we should restrict the flags there?

The analogous function in Linux (`lookup_open`) assumes that the flags are already validated, and passes them to underlying filesystem.
</blockquote></details>

OK, fair enough. I guess not for this PR, so not blocking.
___
*[LibOS/shim/src/fs/shim_namei.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHyGsP97TBS6M7lsQ6:-MZJEagaB3e_WdL1TobJ:b7aovdi) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/fs/shim_namei.c#L66)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I understand it as a suggestion to remove `d_ops->mode()`, and instead initialize the mode together with the rest of dentry (in `d_ops->lookup()`). A filesystem that doesn't disallow anything could set the mode to something like 0777, and this entire branch could be removed.

I think it's a good idea, and the same might be done with `d_ops->stat()`. That way, the initial `lookup()` fills all the necessary information about a file. But I don't want to do it until I understand this part of the filesystem better.
</blockquote></details>

OK, let's keep it.
___
*[LibOS/shim/src/fs/shim_namei.c, line 510 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZIKxSm7NvhWIrJpcQg:-MZJFPnWCloLg3PlNBVE:b-n54xjx) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/fs/shim_namei.c#L510)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We are at the place where it's reflected in our code: this comment explains why the check is done here, and not outside of the if.

Here is the use case described in the comment, as replicated in Python:
```py
# creating a new file
>>> os.open('xyz', os.O_CREAT | os.O_WRONLY, stat.S_IRUSR)
3
# opening it again
>>> os.open('xyz', os.O_CREAT | os.O_WRONLY, stat.S_IRUSR)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: 'xyz'
```
</blockquote></details>

My confusion is more about the part of the comment `opening a newly-created, read-only file for writing` -- you don't check permissions at all when creating a file, but in the comment you have a very specific case. So the comment is too restrictive, whereas the code is simply "don't check permissions on newly-created file". So why do you mention this specific example in the comment (or maybe it's the only case?)?
___
*[LibOS/shim/src/sys/shim_fs.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZIi5JU8w-V48oYc7Jh:-MZJG0df13ZpAx-lq4S1:b-tnejhv) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/sys/shim_fs.c#L1)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's annoying to have both `sys/shim_fs.h` and `fs/shim_fs.h`, especially since they are different layers of the same thing. What do you think about renaming this file (later) to `sys/shim_files.h`?
</blockquote></details>

Which file? This file is `sh [...]

2021-04-27 17:02 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_fs.c, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZIi5JU8w-V48oYc7Jh:-MZJGnmi6Nc5hwOGIFrr:b-dlwmba) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/sys/shim_fs.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Which file? This file is `shim_fs.c`. I guess you meant these two:
- `shim/src/fs/shim_fs.c`
- `shim/src/sys/shim_fs.c`

I'm fine with renaming one of them. Your suggestion of `sys/shim_files.c` is fine.
</blockquote></details>

Yes, sorry, I meant `.c` (not `.h`) in all instances.


<!-- Sent from Reviewable.io -->

2021-04-28 07:43 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: 16 of 17 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHd2KcCckxkdQH3Uao:-MZMHOuHDr85iv6X6MN7:b-73ldwg) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see any changes in the commit messages?
</blockquote></details>

Oh, I didn't save the changed message before rebasing, sorry.

Should be good now.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZHdTJI9xzzUoP1RJyL:-MZMQUf33gaY4L56IAE3:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/fs/shim_namei.c, line 510 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZIKxSm7NvhWIrJpcQg:-MZMHt_A8mBQHnDBWRi0:b-5n860g) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/fs/shim_namei.c#L510)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

My confusion is more about the part of the comment `opening a newly-created, read-only file for writing` -- you don't check permissions at all when creating a file, but in the comment you have a very specific case. So the comment is too restrictive, whereas the code is simply "don't check permissions on newly-created file". So why do you mention this specific example in the comment (or maybe it's the only case?)?
</blockquote></details>

That's not my comment, but I agree: this case is more general, you can even set `mode` to 0.

I removed the example, and reworded the comment to describe the case directly (the mode can be incompatible with `acc_mode`).


<!-- Sent from Reviewable.io -->

2021-04-28 07:53 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/fs/shim_namei.c, line 510 at r1](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZIKxSm7NvhWIrJpcQg:-MZMSl-S-nf4elbL7nu3:blluxvb) ([raw file](https://github.com/oscarlab/graphene/blob/3aaef34c2472f5e8e5aa491ec2283a38841f123c/LibOS/shim/src/fs/shim_namei.c#L510)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's not my comment, but I agree: this case is more general, you can even set `mode` to 0.

I removed the example, and reworded the comment to describe the case directly (the mode can be incompatible with `acc_mode`).
</blockquote></details>

OK. I didn't notice that you copied this comment from the previous code (I didn't dare to look at the old code). Now I understand the context for this :) Thanks for rewording the comment!


<!-- Sent from Reviewable.io -->

2021-05-03 06:40 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-05 00:21 UTC, mkow requested changes
> Reviewed 13 of 17 files at r1, 2 of 4 files at r2, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 389 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZp1fRN0i9ZOYmL5-7K:-MZp1fRN0i9ZOYmL5-7L:b-v0eczh) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/include/shim_fs.h#L389)):*
> ```
> but not permissions for the whole path.
> ```

So, the caller is expected to do this? Is it actually implemented in the caller or do we just skip these checks? If the latter, there should be a TODO here, I think.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 259 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtWqKH92x97sF0VTY6:-MZtWqKI8tDhYf2eNFem:b-5v6ese) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_dcache.c#L259)):*
> ```C
> }
> 
> #define DUMP_FLAG(flag, s, empty) buf_puts(&buf, (dent->state & flag) ? s : empty)
> ```

I know this macro is used only in the function below, but please still write it safely :) I.e. parenthesize the parameters.
___
*[LibOS/shim/src/fs/shim_fs.c, line 509 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtY8jd8Fe2lI__pM3C:-MZtY8jd8Fe2lI__pM3D:bvx0hmp) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_fs.c#L509)):*
> ```
> bool make_ancestor
> ```

I think we could remove this argument and always assume it's `true`. But I guess you'll refactor this when fixing mountpoints.
___
*[LibOS/shim/src/fs/shim_namei.c, line 222 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtkZwV3hZPH99Y4nlL:-MZtkZwV3hZPH99Y4nlM:b-a8hu8t) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_namei.c#L222)):*
> ```C
>     assert(start);
>     dent = start;
>     get_dentry(dent);
> ```

Any reason why couldn't we simplify this logic and just `get` the final, to-be-returned dentry right before returning?
___
*[LibOS/shim/src/fs/shim_namei.c, line 368 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtnJ2UB14O9aQVDOUl:-MZtnJ2UB14O9aQVDOUm:b-guc46w) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_namei.c#L368)):*
> ```
> is_opened
> ```

I think grammatically correct form is either `is_open` or `is_opened`.
___
*[LibOS/shim/src/fs/shim_namei.c, line 627 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtrlyp8O0OzB2AFbHQ:-MZtrlyq-7mzVWIWCnwJ:btl4fb7) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_namei.c#L627)):*
> ```C
>         if ((ret = lookup_dentry(dent, d->name, strlen(d->name), &child)) < 0) {
>             /* ENOENT from underlying lookup should be handled as DENTRY_NEGATIVE */
>             assert(ret != ENOENT);
> ```

Not `-ENOENT`?


<!-- Sent from Reviewable.io -->

2021-05-05 08:22 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: 14 of 17 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 389 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZp1fRN0i9ZOYmL5-7K:-MZvP9aaD39QYkbnlYqb:b-rqlc74) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/include/shim_fs.h#L389)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> but not permissions for the whole path.
> ```

So, the caller is expected to do this? Is it actually implemented in the caller or do we just skip these checks? If the latter, there should be a TODO here, I think.
</blockquote></details>

That's right, the check should be here. Or actually, it probably belongs to `path_lookupat`. I added a TODO to both of these functions.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 259 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtWqKH92x97sF0VTY6:-MZvQcgeBcO7QcF6akD3:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_dcache.c#L259)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know this macro is used only in the function below, but please still write it safely :) I.e. parenthesize the parameters.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 509 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtY8jd8Fe2lI__pM3C:-MZvQdZqESKJnL8926W3:b-uyj8q1) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_fs.c#L509)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> bool make_ancestor
> ```

I think we could remove this argument and always assume it's `true`. But I guess you'll refactor this when fixing mountpoints.
</blockquote></details>

Yes, I will be rewriting this function completely, when I change how mounts work. I don't want to touch the current implementation too much until then. And I agree, it should always create a synthetic node.
___
*[LibOS/shim/src/fs/shim_namei.c, line 222 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtkZwV3hZPH99Y4nlL:-MZvTY1_4bBIV01XEPOu:b9vvrv6) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_namei.c#L222)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Any reason why couldn't we simplify this logic and just `get` the final, to-be-returned dentry right before returning?
</blockquote></details>

That's because this function calls other functions that give it a dentry with increased reference count (`lookup_dentry`, and itself, recursively, when following a symlink). So it needs to adjust some reference counts in the middle anyway.

Also, _not_ keeping a reference for the intermediate dentries is only correct assuming nothing can delete them in the meantime. This assumption is true now (because we keep `g_dcache_lock` for the whole time), but might not be later (if we e.g. release the lock during low-level filesystem lookup), and since keeping the ref counts is not a big deal here, I'd rather make the code not depend on it.

Overall, I'd say it's better to keep the "correct" reference counting discipline, unless a function is really simple (ideally doesn't call anything else).
___
*[LibOS/shim/src/fs/shim_namei.c, line 368 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtnJ2UB14O9aQVDOUl:-MZvYu0Y-peMFl2ii5QK:b-cgkycx) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_namei.c#L368)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> is_opened
> ```

I think grammatically correct form is either `is_open` or `is_opened`.
</blockquote></details>

I thought about it a bit more, and I can just check `hdl->dentry`. The handle really should be unassociated before that (looking at the call sites confirms it, and I added an assert just in case).

(I did not like the `is_open` name because it somehow didn't suggest to me that it was opened in this function. So I started thinking about names like `initialized`. But it's better to avoid this variable completely).
___
*[LibOS/shim/src/fs/shim_namei.c, line 627 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtrlyp8O0OzB2AFbHQ:-MZv_P-Y8PmQT7IIc1h_:b-sr7xhk) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_namei.c#L627)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not `-ENOENT`?
</blockquote></details>

That's right, this assert did nothing. Fixed.


<!-- Sent from Reviewable.io -->

2021-05-05 15:49 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_namei.c, line 222 at r5](https://reviewable.io/reviews/oscarlab/graphene/2333#-MZtkZwV3hZPH99Y4nlL:-MZx0goZ1KeaNu7Jg_gB:b-j40ifj) ([raw file](https://github.com/oscarlab/graphene/blob/a4bf8a49acba539d47ada2ecd583cdf43166925c/LibOS/shim/src/fs/shim_namei.c#L222)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's because this function calls other functions that give it a dentry with increased reference count (`lookup_dentry`, and itself, recursively, when following a symlink). So it needs to adjust some reference counts in the middle anyway.

Also, _not_ keeping a reference for the intermediate dentries is only correct assuming nothing can delete them in the meantime. This assumption is true now (because we keep `g_dcache_lock` for the whole time), but might not be later (if we e.g. release the lock during low-level filesystem lookup), and since keeping the ref counts is not a big deal here, I'd rather make the code not depend on it.

Overall, I'd say it's better to keep the "correct" reference counting discipline, unless a function is really simple (ideally doesn't call anything else).
</blockquote></details>

Ok, makes sense, I was just curious why you wrote it this way :)


<!-- Sent from Reviewable.io -->

2021-05-05 15:59 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-05-05 17:53 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-05 17:53 UTC, dimakuv approved these changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-05 18:12 UTC, merged

2021-05-06 10:53 UTC, boryspoplawski reviewed
> Reviewed 8 of 17 files at r1, 2 of 4 files at r2, 3 of 3 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, 12 unresolved discussions (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_-vIrPAtkuJQZzbPSy:-M_-vIrQ7WX1kieKx_WS:bcdvb5p) (no related file):*
Sorry I'm late to the party but I have a couple of comments.

---
___
*[LibOS/shim/include/shim_fs.h, line 383 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_-wlSX-OsXMCO1U26z:-M_-wlSX-OsXMCO1U27-:b-unojl3) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/include/shim_fs.h#L383)):*
> ```objc
>  * \brief Open a file under a given path, similar to Unix open
>  *
>  * \param[out] hdl handle to associate with dentry, can be NULL
> ```

I'm not sure if this is really `out` param. It's just modified/passed to another object IIUC, so I would omit it or use `in/out` (but I dont think it fits that case)
___
*[LibOS/shim/include/shim_fs.h, line 418 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_-yqbD0tle9Sm-h3Z_:-M_-yqbD0tle9Sm-h3Za:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/include/shim_fs.h#L418)):*
> ```objc
>  * \brief Open an already retrieved dentry, and associate a handle with it
>  *
>  * \param[out] hdl handle to associate with dentry
> ```

ditto
___
*[LibOS/shim/src/fs/shim_namei.c, line 93 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_-zsrt06R2vbHBwlLy:-M_-zsrt06R2vbHBwlLz:b-5mei1m) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L93)):*
> ```C
>  * The caller should hold `g_dcache_lock`.
>  *
>  * On success, returns 0 and sets `*new` to the found dentry (whose reference count is increased). A
> ```

`*new` -> `*found`
___
*[LibOS/shim/src/fs/shim_namei.c, line 94 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_-zxIs-nyykolAxSkr:-M_-zxIs-nyykolAxSks:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L94)):*
> ```C
>  *
>  * On success, returns 0 and sets `*new` to the found dentry (whose reference count is increased). A
>  * negative filesystem lookup (ENOENT) is also considered a success, and `*new` is set to a negative
> ```

ditto
___
*[LibOS/shim/src/fs/shim_namei.c, line 98 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_-zyIL9mZVZoy54BLK:-M_-zyIL9mZVZoy54BLL:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L98)):*
> ```C
>  *
>  * On failure (including lookup failing with any other error than ENOENT) returns the negative error
>  * code, and sets `*new` to NULL.
> ```

ditto
___
*[LibOS/shim/src/fs/shim_namei.c, line 212 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_0-nqm50sXdpgil2wv:-M_0-nqm50sXdpgil2ww:b-iznrk9) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L212)):*
> ```C
>         /* Relative part with no start dentry provided, use process current working directory */
>         lock(&g_process.fs_lock);
>         start = g_process.cwd;
> ```

This seems incorrect: we do not get this dentry and then unlock `g_process.fs_lock`. What if another thread changes `cwd` and this dentry is destroyed?

Maybe change this to set `dent` directly and just add an `else` clause at the end to handle `start != NULL` case (and just do `dent = start` there)?
___
*[LibOS/shim/src/fs/shim_namei.c, line 228 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_06gcI5yjg0tjLxAfV:-M_06gcI5yjg0tjLxAfW:b63vseh) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L228)):*
> ```C
>         name++;
> 
>     while (*name != '\0') {
> ```

If `path == "/"` and `!(flags & LOOKUP_DIRECTORY)` this will still succeed and return root dentry.
___
*[LibOS/shim/src/fs/shim_namei.c, line 334 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_08LJc26nTP3hpa8Gi:-M_08LJd0qVGKqbDJ82t:b-snlvd2) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L334)):*
> ```C
>                    struct shim_dentry** found) {
>     lock(&g_dcache_lock);
>     int ret = do_path_lookupat(start, path, flags, found, /*link_depth=*/0);
> ```

NP: `_path_lookupat`?
___
*[LibOS/shim/src/fs/shim_namei.c, line 467 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_0Hd59-PisyAFiOwa5:-M_0Hd5A7Zu9Rnvn-Nu7:b-tnrpw2) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L467)):*
> ```C
> 
>     if (dent->state & DENTRY_ISLINK) {
>         /* Can happen if user specified O_NOFOLLOW, or O_TRUNC | O_EXCL. Posix requires us to fail
> ```

I guess we do not support `O_PATH`?
___
*[LibOS/shim/src/fs/shim_namei.c, line 490 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_0IE8G6GxFlIUyTs2n:-M_0IE8G6GxFlIUyTs2o:b1be03r) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L490)):*
> ```C
>             goto err;
> 
>         /* Create directory or file, depending on O_DIRECTORY. Return -EINVAL if the operation is
> ```

man for `open(2)` states that `When both O_CREAT and O_DIRECTORY are specified in flags and the file specified by pathname does not exist, open() will create a regular file (i.e., O_DIRECTORY is ignored).` Is that not the case on newer kernel? Because if it is, we might need to emulate it...
___
*[LibOS/shim/src/fs/shim_namei.c, line 632 at r7](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_09j6m977CsgUwULgI:-M_09j6n78XgnaWZX9nq:b-4ei442) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_namei.c#L632)):*
> ```C
> 
>             /* Ignore inaccessible files */
>             if (ret == -EACCES)
> ```

How can we have access to only part of directory?


<!-- Sent from Reviewable.io -->

2021-05-06 17:03 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2333)* status: all files reviewed, 12 unresolved discussions (waiting on @boryspoplawski and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2333#-M_-vIrPAtkuJQZzbPSy:-M_1aQsm8rOV2wR0mbPa:b-d17khr) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sorry I'm late to the party but I have a couple of comments.
</blockquote></details>

Thanks. I created a PR in #2354, and I will respond to your comments there.

---


<!-- Sent from Reviewable.io -->