[Pal/Linux-SGX] Remove `g_enclave_key` and use SHA256 for file chunk hashes
oscarlab/graphene pull request #2337
Opened 2021-04-27 16:34 UTC by dimakuv

## Description of the changes 

Previously, Graphene generated `g_enclave_key` based on Intel SGX's `EGETKEY(SEAL_KEY)`. This key was generated insecurely (it was always the same for any enclave on the platform), and it was used to generate hashes of trusted-file chunks. This was done via 128-bit AES-CMAC. However, there is no need for a key-based hash to verify the integrity of trusted-file chunks; SHA-256 (truncated to 128 bits) is sufficient.

Therefore, this PR removes `g_enclave_key` and replaces its uses with keyless SHA-256.

Fixes #2326.

## How to test this PR? 

All tests must pass. One can use GDB to manually flip some bits in untrusted-memory files and see how Graphene complains.

2021-05-03 13:02 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm95YaEV2WI9GioQl3:-MZm95Yb0FUnIxloYCQW:b-qlutg5) (no related file):*
FYI: If I'm not mistaken, this is fixing a huge security vuln and should be prioritized. See https://github.com/oscarlab/graphene/issues/2326#issuecomment-831238330.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm9B7T43v_NLK50_jm:-MZm9B7UBNnFZe5wgxM9:b-ksc8d6) (no related file):*
I think the original reason for using AES-CMAC for hashing was performance - it can use AES-NI which (AFAIK) is supported on all SGX CPUs. SHA-* acceleration is much more recent, do you know if it's also supported on all SGX CPUs?
Alternative fix would be to rename this key to `trusted_files_cmac_key` (because its current name is very confusing) and just fill with crypto-randomness during initialization, so that we can keep using AES-CMAC (if it turns out that it's actually faster).

---


<!-- Sent from Reviewable.io -->

2021-05-03 13:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm9B7T43v_NLK50_jm:-MZmU-FG6bh0EzNnTNVc:bv7xmu8) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think the original reason for using AES-CMAC for hashing was performance - it can use AES-NI which (AFAIK) is supported on all SGX CPUs. SHA-* acceleration is much more recent, do you know if it's also supported on all SGX CPUs?
Alternative fix would be to rename this key to `trusted_files_cmac_key` (because its current name is very confusing) and just fill with crypto-randomness during initialization, so that we can keep using AES-CMAC (if it turns out that it's actually faster).
</blockquote></details>

I don't think *all* SGX CPUs have support for AES-NI. I'm pretty sure small SGX-enabled NUCs don't have AES-NI.

Also, I am opposed to the idea of continuing to use the AES-CMAC key. It's just redundant, and is an obvious attack target (e.g., side channel attack). Even if SHA256 is a bit slower on some CPUs, I don't see a reason to favor AES over SHA. Also, two observations:
- I haven't noticed any significant slowdowns on this PR -- even thousands of files in GSC workloads ran fine
- This loading of trusted files is hardly on a trusted path -- these files are mainly used shared libraries and configuration files, which are not read/mmapped frequently enough to make a perf difference.

---


<!-- Sent from Reviewable.io -->

2021-05-03 16:45 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm9B7T43v_NLK50_jm:-MZmb8nw-C1mYKIrfni-:b-kzmlyy) (no related file):*
> It's just redundant

I wouldn't say "redundant", just a different hashing algorithm, which tries to utilize AES-NI.

> is an obvious attack target (e.g., side channel attack)

Ok, this is a really good argument, I'm resolving then.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm95YaEV2WI9GioQl3:-MZmu5CO0VvVjIcwQZlA:b-mc0df0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

FYI: If I'm not mistaken, this is fixing a huge security vuln and should be prioritized. See https://github.com/oscarlab/graphene/issues/2326#issuecomment-831238330.
</blockquote></details>

Actually, we may want to update the commit message here.

---
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 433 at r1](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZn57MF5iD2FEyEe4Ms:-MZn57MF5iD2FEyEe4Mt:bcbfl9a) ([raw file](https://github.com/oscarlab/graphene/blob/ecd925dd524e1f01d743eca1c5652e7787888f7f/Pal/src/host/Linux-SGX/enclave_framework.c#L433)):*
> ```C
> 
>         /* To prevent TOCTOU attacks when calculating the file hashes, copy file contents into the
>          * enclave before hashing. Use a small stack-allocated buffer to store these contents. */
> ```

Why not simplify this into just copying by `TRUSTED_STUB_SIZE`? We could allocate such buffer on the heap and free right after. Should be faster and the code will be considerably simpler.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 598 at r1](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZn6CAY2IPL989YsJKO:-MZn6CAY2IPL989YsJKP:buxgt8n) ([raw file](https://github.com/oscarlab/graphene/blob/ecd925dd524e1f01d743eca1c5652e7787888f7f/Pal/src/host/Linux-SGX/enclave_framework.c#L598)):*
> ```C
>         }
> 
>         ret = lib_SHA256Final(&sha_stub, (uint8_t*)hash.bytes);
> ```

Instead of casting here, could we fix the type in the struct itself?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 612 at r1](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZn6Wp3C7ttdKt_zSef:-MZn6Wp3C7ttdKt_zSeg:b-w4e12r) ([raw file](https://github.com/oscarlab/graphene/blob/ecd925dd524e1f01d743eca1c5652e7787888f7f/Pal/src/host/Linux-SGX/enclave_framework.c#L612)):*
> ```C
> 
> failed:
>     memset(buffer, 0, size);
> ```

good idea :thumbsup: 


<!-- Sent from Reviewable.io -->

2021-05-04 09:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: 1 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm95YaEV2WI9GioQl3:-MZqCo4K4zjdBNnyhq7y:b-brkhbc) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, we may want to update the commit message here.
</blockquote></details>

Do you want to add a phrase on vulnerabilities? I can change the commit message during rebase, what about this text:
```
[Pal/Linux-SGX] Remove `g_enclave_key` and use SHA256 for file chunk hashes

Previously, Graphene generated `g_enclave_key` based on Intel SGX's
`EGETKEY(SEAL_KEY)`. This key was generated insecurely (it was always
the same for any enclave on the platform), and it was used to generate
hashes of trusted-file chunks. This was done via 128-bit AES-CMAC.
However, there is no need for a key-based hash to verify the integrity
of trusted-file chunks; SHA-256 (truncated to 128 bits) is sufficient.
Moreover, using AES-CMAC as a hashing function was a serious security
vulnerability: the attacker could re-generate the same key in her own
malicious enclave, and then make controlled changes to trusted files
without changing the hashes of trusted-file chunks. This would break
security of Graphene completely. Therefore, this commit removes
`g_enclave_key` and replaces its uses with keyless SHA-256.
```

---
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 433 at r1](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZn57MF5iD2FEyEe4Ms:-MZqhgPc9VMTSLmaEDDK:becby12) ([raw file](https://github.com/oscarlab/graphene/blob/ecd925dd524e1f01d743eca1c5652e7787888f7f/Pal/src/host/Linux-SGX/enclave_framework.c#L433)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not simplify this into just copying by `TRUSTED_STUB_SIZE`? We could allocate such buffer on the heap and free right after. Should be faster and the code will be considerably simpler.
</blockquote></details>

Done. I didn't want to refactor the code, but look what you made me do.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 598 at r1](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZn6CAY2IPL989YsJKO:-MZqhpRF5RKmt7FDAn0K:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ecd925dd524e1f01d743eca1c5652e7787888f7f/Pal/src/host/Linux-SGX/enclave_framework.c#L598)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Instead of casting here, could we fix the type in the struct itself?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 87 at r2](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZqhr_8APqo4LG0XaiA:-MZqhr_8APqo4LG0XaiB:bg5z4x8) ([raw file](https://github.com/oscarlab/graphene/blob/bbc2632ad92c1f2fefafc49dd1d19c1af2671ce0/Pal/src/host/Linux-SGX/pal_linux.h#L87)):*
> ```objc
> #define DATA_END   ((void*)(&__text_end))
> 
> /* TODO: rename to sgx_file_hash_t and sgx_chunk_hash_t; always use "hash" and "chunk" in naming */
> ```

FYI: I didn't want to make this PR even bigger, so I postponed this refactoring to a future PR (I'll do it in spare time after this one is merged). There is still a lot of room for refactoring this "trusted files" logic.


<!-- Sent from Reviewable.io -->

2021-05-04 09:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: 1 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZqi8Nt6YhFC18dtqn4:-MZqi8Nt6YhFC18dtqn5:b-6ocl0e) (no related file):*
TODO(myself): Add to commit message that "As a side effect, `load_trusted_file()` and `copy_and_verify_trusted_file()` were refactored."

---


<!-- Sent from Reviewable.io -->

2021-05-04 12:07 UTC, mkow requested changes
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm95YaEV2WI9GioQl3:-MZr2jnC5eEki8ohnRF6:btu2l3z) (no related file):*
> Do you want to add a phrase on vulnerabilities?

Yes. Someone reading the commit log should clearly see that this was fixing an important security vulnerability.

So, I'd change the one-liner to make it clear, e.g. to something like "[Pal/Linux-SGX] Fix vulnerability which allowed tampering with trusted files".

---
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 433 at r1](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZn57MF5iD2FEyEe4Ms:-MZr47dM-tCnQg7JCkoh:b-vl0edh) ([raw file](https://github.com/oscarlab/graphene/blob/ecd925dd524e1f01d743eca1c5652e7787888f7f/Pal/src/host/Linux-SGX/enclave_framework.c#L433)):*
> +143 −234

no regrets here :)
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 511 at r3](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZrE31N23hnW-jpnt0X:-MZrE31N23hnW-jpnt0Y:b-lnuy9j) ([raw file](https://github.com/oscarlab/graphene/blob/1d5eabf92fcb57b6e97123e649b8b4badd0e64b7/Pal/src/host/Linux-SGX/enclave_framework.c#L511)):*
> ```C
>         if (chunk_offset >= offset && chunk_end <= end) {
>             /* if current chunk-to-copy completely resides in the requested region-to-copy,
>              * directly copy into buf (without a sratch buffer) and hash in-place */
> ```

`sratch` -> `scratch`
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 518 at r3](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZrEs12EiumoSetcqZZ:-MZrEs12EiumoSetcqZ_:b-li29p4) ([raw file](https://github.com/oscarlab/graphene/blob/1d5eabf92fcb57b6e97123e649b8b4badd0e64b7/Pal/src/host/Linux-SGX/enclave_framework.c#L518)):*
> ```C
>                 goto failed;
> 
>             buf += chunk_size;
> ```

That's risky, I'd prefer if you didn't modify the arguments. Why it's risky? You left this :point_down: at the end of the function :)
```C
memset(buf, 0, end - offset);
```
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 521 at r3](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZrFLTWDGPS_8v0vjRI:-MZrFLTWDGPS_8v0vjRJ:b-y7xhhr) ([raw file](https://github.com/oscarlab/graphene/blob/1d5eabf92fcb57b6e97123e649b8b4badd0e64b7/Pal/src/host/Linux-SGX/enclave_framework.c#L521)):*
> ```C
>         } else {
>             /* if current chunk-to-copy only partially overlaps with the requested region-to-copy,
>              * read the file contents in a scratch buffer, verify hash and then copy only the part
> ```

`in a scratch buffer` -> `into a scratch buffer`


<!-- Sent from Reviewable.io -->

2021-05-04 12:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: 3 of 4 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm95YaEV2WI9GioQl3:-MZrJWEJ2qDeSEQr6K1w:b-ss9asp) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Do you want to add a phrase on vulnerabilities?

Yes. Someone reading the commit log should clearly see that this was fixing an important security vulnerability.

So, I'd change the one-liner to make it clear, e.g. to something like "[Pal/Linux-SGX] Fix vulnerability which allowed tampering with trusted files".
</blockquote></details>

Will do during rebase.

---
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 511 at r3](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZrE31N23hnW-jpnt0X:-MZrIW-8CQvIVyDqQRf-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1d5eabf92fcb57b6e97123e649b8b4badd0e64b7/Pal/src/host/Linux-SGX/enclave_framework.c#L511)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`sratch` -> `scratch`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 518 at r3](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZrEs12EiumoSetcqZZ:-MZrIx3h0VXQlLD-R0PR:bsq6571) ([raw file](https://github.com/oscarlab/graphene/blob/1d5eabf92fcb57b6e97123e649b8b4badd0e64b7/Pal/src/host/Linux-SGX/enclave_framework.c#L518)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's risky, I'd prefer if you didn't modify the arguments. Why it's risky? You left this :point_down: at the end of the function :)
```C
memset(buf, 0, end - offset);
```
</blockquote></details>

Done. I actually had a correct version and then decided to save on one variable, and got a bug :)
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 521 at r3](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZrFLTWDGPS_8v0vjRI:-MZrIZ9k5xbStlZw5zjw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1d5eabf92fcb57b6e97123e649b8b4badd0e64b7/Pal/src/host/Linux-SGX/enclave_framework.c#L521)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`in a scratch buffer` -> `into a scratch buffer`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-04 12:31 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-05-04 12:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: 2 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2337#-MZm95YaEV2WI9GioQl3:-MZrMwRK-10no3bJ0pGn:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Will do during rebase.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-05-04 12:43 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2337)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-04 13:09 UTC, merged