[LibOS,Pal] Remove needless functions from exposed PAL API
oscarlab/graphene pull request #2339
Opened 2021-04-28 14:45 UTC by dimakuv

## Description of the changes 

This PR contains two commits:

### Remove needless functions from exposed PAL API

Exposed PAL API (globally visible functions) is listed in the file `pal-symbols`. It mostly contains `Dk*()` functions but over time it grew to contain several non-standard functions. In particular:
- `pal_printf()`: exposed but not used in LibOS,
- `pal_control_addr()`: used in LibOS to access PAL shared fields
- `pal_strerror()`: erroneously used in one place in LibOS
- `warn()`: used in fortified `_chk` versions of standard C functions and thus implicitly called in LibOS.

This commit removes `pal_printf()`, `pal_strerror()` and `warn()` from the list of exposed PAL APIs. The LibOS code implements its own version of `warn()` now, and removes a call to `pal_strerror()`. PAL regression tests too implement their own `pal_printf()` and `warn()` functions.

Also, a few places in PAL code are fixed to not call the exposed API functions but instead use their locally-visible variants. This change has the additional benefit that PAL binaries do not need PLT relocations anymore.

### Replace `pal_control_addr()` with `DkGetPalControl()`

Previously, exposed PAL API (globally visible functions) contained `pal_control_addr()` function that returned a pointer to the `PAL_CONTROL` global structure containing PAL-initialized shared fields. There were also hacky `PAL_CB` and `pal_control` macros that obfuscated the call to `pal_control_addr()`.

This commit renames `pal_control_addr()` to `DkGetPalControl()` for uniformity with other PAL APIs. It also removes hacky macros.

## How to test this PR? 

All tests must pass.

2021-04-28 14:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: 0 of 71 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/regression/Makefile, line 108 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZNwwJW97s6PalUv0SV:-MZNwwJX3aZ4TRjrZkeT:b-e7ciqm) ([raw file](https://github.com/oscarlab/graphene/blob/483a292e676f2a0bbdeeab65fd8c08582c396316/Pal/regression/Makefile#L108)):*
> ```Makefile
> 	@true
> 
> LDLIBS-preloads = ../crt_init/user_shared_start.o $(graphene_lib) $(pal_lib) abort.o
> ```

FYI: This was a tiny bug of wrong linking order. `abort.o` may use functions from `graphene_lib` and `pal_lib`, but when it was placed at the end, it didn't get the functions. Moving `abort.o` before these libs fixed the problem.
___
*[Pal/regression/normalize_path.c, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZNxD5N-XssWsOYL7Nr:-MZNxD5N-XssWsOYL7Ns:b-5epq6r) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/Pal/regression/normalize_path.c#L45)):*
> ```C
> static const char* func_name;
> 
> char buf[4096] = {0};
> ```

FYI: Removed `URI_MAX` dependency because it was in `pal_defs.h` which is supposed to be a PAL-internal header. The particular constant I chose `4096` doesn't matter much, could be anything.
___
*[Pal/regression/pal_regression.h, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZNxRsbAODMisNe2D_y:-MZNxRsbAODMisNe2D_z:b-axktbb) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/Pal/regression/pal_regression.h#L12)):*
> ```objc
> #include "pal.h"
> 
> #define pal_control (*DkGetPalControl())
> ```

FYI: In this file, I have hacky implementations of symbols used in PAL regression tests. I didn't want to rewrite the PAL regression tests because it's too tedious.
___
*[Pal/src/pal-symbols, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZNxcnB-l3UniwyyynK:-MZNxcnB-l3UniwyyynL:b-k7222q) ([raw file](https://github.com/oscarlab/graphene/blob/483a292e676f2a0bbdeeab65fd8c08582c396316/Pal/src/pal-symbols#L54)):*
> ```
> pal_control_addr
> pal_strerror
> warn
> ```

FYI: This whole PR started with me noticing that these functions are supposed to be used internally in PAL and never by LibOS/regression tests. So I went ahead and removed them. Now the list of exposed symbols in PAL binaries is beautiful and doesn't contain these weird hacks.
___
*[Pal/src/pal_internal.h, line 312 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZNxus932FvzITyz6ns:-MZNxus932FvzITyz6nt:bpuomm7) ([raw file](https://github.com/oscarlab/graphene/blob/483a292e676f2a0bbdeeab65fd8c08582c396316/Pal/src/pal_internal.h#L312)):*
> ```objc
>     do {                                       \
>         log_error("uthash error: %s\n", msg);  \
>         DkProcessExit(PAL_ERROR_NOMEM);        \
> ```

FYI: Here and below, these are all instances of using exposed symbols instead of internal ones. I fixed all such places.


<!-- Sent from Reviewable.io -->

2021-04-28 15:07 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (`kill11` LTP test failed, unrelated)

2021-04-28 18:02 UTC, pwmarcz requested changes
> Reviewed 8 of 71 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: 8 of 71 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOXrgzBJ_AzCW0PWnP:-MZOXrh-EftxNCdJEcgD:b-4odb9u) (no related file):*
I don't understand, why are you calling `DkGetPalControl()` every time? A more straightforward fix for me would be to make a `g_pal_control` pointer in LibOS, and initialize it from `DkGetPalControl()` once.

Also, that would make it clear that `DkGetPalControl()` returns the same value every time, and the results don't go stale or anything - the current usage suggests the semantics might be more complicated, and you are actually required to call it.

Removing `PAL_CB` is definitely a win, that was really confusing for me.

---
___
*[Documentation/pal/host-abi.rst, line 96 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOcP5f4nQoU9vnEhOr:-MZOcP5f4nQoU9vnEhOs:b1yu4ci) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/Documentation/pal/host-abi.rst#L96)):*
> ```reStructuredText
> ^^^^^^^^^^^^^^^^^^^^^^
> 
> The control block in Graphene is a structure that provides static information
> ```

Does "static information" mean it never changes? Maybe it would be better to be more explicit about that, to answer any concerns about accessing it concurrently.
___
*[Documentation/pal/host-abi.rst, line 98 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZObMPS57Z3caLKwxwH:-MZObMPS57Z3caLKwxwI:be1b4bf) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/Documentation/pal/host-abi.rst#L98)):*
> ```reStructuredText
> The control block in Graphene is a structure that provides static information
> about the current process and its host. It is also a dynamic symbol that will be
> linked by the library OS and resolved at runtime. Sometimes, for the flexibility
> ```

That's not true anymore, right?
___
*[LibOS/shim/src/shim_init.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOYScp9JWeLWrMWEna:-MZOYScp9JWeLWrMWEnb:bhfr7bl) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/LibOS/shim/src/shim_init.c#L40)):*
> ```C
> toml_table_t* g_manifest_root = NULL;
> 
> /* TODO: Currently copied from log_always(). Remove this and always use log_*. */
> ```

What do you mean by `always use log_*`? I don't think we should use `log_*` instead of `warn` in printf, assertions, etc.

Probably LibOS's implementation of `warn` can call `log_always()` (or a `va_list` version of `_log(PAL_LOG_ALL)`), if that's what you mean.
___
*[LibOS/shim/src/shim_init.c, line 47 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOWUJA045Y1H_McrYi:-MZOWUJA045Y1H_McrYj:b-ucoco3) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/LibOS/shim/src/shim_init.c#L47)):*
> ```C
> }
> 
> void warn(const char* format, ...) {
> ```

I started to write that this should live next to `__abort` (because both are functions required by our "standard library"), but I just noticed `__abort` is also in this file...

So, not blocking, but maybe there is a better place for these.
___
*[Pal/src/pal_internal.h, line 312 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZNxus932FvzITyz6ns:-MZO_DBs0hSX7owvIN94:b-phh8wj) ([raw file](https://github.com/oscarlab/graphene/blob/483a292e676f2a0bbdeeab65fd8c08582c396316/Pal/src/pal_internal.h#L312)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Here and below, these are all instances of using exposed symbols instead of internal ones. I fixed all such places.
</blockquote></details>

Maybe offtopic, but the difference between these is really not clear and arbitrary. Some of these add validation, some just add assertions, some convert the parameters...

Can we have a rule that "only `DkFoo` calls `_DkFoo`", or is it too strict?


<!-- Sent from Reviewable.io -->

2021-04-29 07:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: 5 of 73 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOXrgzBJ_AzCW0PWnP:-MZRXagEA_QDf-YasybA:bjlemhj) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't understand, why are you calling `DkGetPalControl()` every time? A more straightforward fix for me would be to make a `g_pal_control` pointer in LibOS, and initialize it from `DkGetPalControl()` once.

Also, that would make it clear that `DkGetPalControl()` returns the same value every time, and the results don't go stale or anything - the current usage suggests the semantics might be more complicated, and you are actually required to call it.

Removing `PAL_CB` is definitely a win, that was really confusing for me.
</blockquote></details>

Done. I agree with your arguments. There was no good reason to call `DkGetPalControl()`, I initially just wanted to make it very clear that there is no "magic" (as opposed to the previous version with macros).

---
___
*[Documentation/pal/host-abi.rst, line 96 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOcP5f4nQoU9vnEhOr:-MZRR1xu7rGbeKm7bWHo:b9adoud) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/Documentation/pal/host-abi.rst#L96)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Does "static information" mean it never changes? Maybe it would be better to be more explicit about that, to answer any concerns about accessing it concurrently.
</blockquote></details>

Done. Added "immutable".
___
*[Documentation/pal/host-abi.rst, line 98 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZObMPS57Z3caLKwxwH:-MZRR4Z2AAtJO8wUvOFv:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/Documentation/pal/host-abi.rst#L98)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

That's not true anymore, right?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_init.c, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOYScp9JWeLWrMWEna:-MZRZc964ejjFdLpHgKs:baswtpf) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/LibOS/shim/src/shim_init.c#L40)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What do you mean by `always use log_*`? I don't think we should use `log_*` instead of `warn` in printf, assertions, etc.

Probably LibOS's implementation of `warn` can call `log_always()` (or a `va_list` version of `_log(PAL_LOG_ALL)`), if that's what you mean.
</blockquote></details>

Done. Yes, I meant your second sentence. Currently we don't have such `va_list` versions, so I decided it is out of scope of this PR (we had similar comments in other places as well, so they all should be fixed in one separate PR).
___
*[LibOS/shim/src/shim_init.c, line 47 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOWUJA045Y1H_McrYi:-MZRSrc9D__YFvKo1JtM:bjyt3bz) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/LibOS/shim/src/shim_init.c#L47)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I started to write that this should live next to `__abort` (because both are functions required by our "standard library"), but I just noticed `__abort` is also in this file...

So, not blocking, but maybe there is a better place for these.
</blockquote></details>

Yes, these functions should be moved to a better place, but not in this PR.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZRch_u7yj3EHIo1oTu:-MZRch_u7yj3EHIo1oTv:b-3hvi5t) ([raw file](https://github.com/oscarlab/graphene/blob/901b8f5092805cd999257421bb475b8866b01bbc/LibOS/shim/src/fs/chroot/fs.c#L27)):*
> ```C
> 
> #define FILE_BUFMAP_SIZE (DkGetPalControl()->alloc_align * 4)
> #define FILE_BUF_SIZE    (DkGetPalControl()->alloc_align)
> ```

FYI: These macros turned out to be unused.
___
*[Pal/src/pal_internal.h, line 312 at r1](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZNxus932FvzITyz6ns:-MZRXprP9ZZ4xNLYhYcA:b-s30qy6) ([raw file](https://github.com/oscarlab/graphene/blob/483a292e676f2a0bbdeeab65fd8c08582c396316/Pal/src/pal_internal.h#L312)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Maybe offtopic, but the difference between these is really not clear and arbitrary. Some of these add validation, some just add assertions, some convert the parameters...

Can we have a rule that "only `DkFoo` calls `_DkFoo`", or is it too strict?
</blockquote></details>

Definitely offtopic :)

Yes, the difference is quite arbitrary. The original idea as far as I can tell was to have these `DkFoo` entrypoints to the PAL API: they would check (not assert!) that all inputs are reasonable, call the internal function, check that the outputs are reasonable (otherwise return an error from a predefined set, possibly converting internal error semantics). And the internal versions `_DkFoo` were supposed to be more "free" in their interfaces and allowed to assert stuff.

But this spiraled out of control at some point :(


<!-- Sent from Reviewable.io -->

2021-04-29 09:23 UTC, pwmarcz approved these changes
> Reviewed 46 of 71 files at r1, 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZOXrgzBJ_AzCW0PWnP:-MZRvkGG-B-DBa1x60_j:b-514sup) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I agree with your arguments. There was no good reason to call `DkGetPalControl()`, I initially just wanted to make it very clear that there is no "magic" (as opposed to the previous version with macros).
</blockquote></details>

Looks much better!

---
___
*[LibOS/shim/include/shim_internal.h, line 35 at r2](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZRszqXCE4u6q3V7qzo:-MZRszqY7oHUlef6iPc7:b-xmhgxv) ([raw file](https://github.com/oscarlab/graphene/blob/f513c8e5e2c433098b4ed43f04525095a2883603/LibOS/shim/include/shim_internal.h#L35)):*
> ```objc
> extern int g_log_level;
> 
> extern PAL_CONTROL* g_pal_control;
> ```

Nitpick: `const`?
___
*[LibOS/shim/include/shim_internal.h, line 336 at r2](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZRsl7nCSSrMl_BpWgb:-MZRsl7o7bG5Gab6AABC:b-bqj1nx) ([raw file](https://github.com/oscarlab/graphene/blob/f513c8e5e2c433098b4ed43f04525095a2883603/LibOS/shim/include/shim_internal.h#L336)):*
> ```objc
> #endif
> 
> #define ALLOC_ALIGNMENT         g_pal_control->alloc_align
> ```

Good improvement, I remember coming across `g_pal_alloc_align` and not being sure where it came from.


<!-- Sent from Reviewable.io -->

2021-04-29 11:50 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: 71 of 74 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_internal.h, line 35 at r2](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZRszqXCE4u6q3V7qzo:-MZSSqo32KiOdVrAYpse:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/f513c8e5e2c433098b4ed43f04525095a2883603/LibOS/shim/include/shim_internal.h#L35)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Nitpick: `const`?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-04-29 12:17 UTC, pwmarcz approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-29 14:30 UTC, yamahata submitted a review, later dismissed
> Reviewed 50 of 71 files at r1, 21 of 23 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-29 19:02 UTC, boryspoplawski requested changes
> Reviewed 50 of 71 files at r1, 21 of 23 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_internal.h, line 336 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTuAbIAU7DbIG-Pv8z:-MZTuAbIAU7DbIG-Pv9-:bs8x3mn) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/include/shim_internal.h#L336)):*
> ```objc
> #endif
> 
> #define ALLOC_ALIGNMENT         g_pal_control->alloc_align
> ```

Please wrap with `()` (in practice it's not needed since `->` has highest precedence, but still please do).
___
*[LibOS/shim/include/shim_internal.h, line 337 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTuLdlAdpBuq8IFhkv:-MZTuLdmC8UM66pEDqz0:buv1y05) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/include/shim_internal.h#L337)):*
> ```objc
> 
> #define ALLOC_ALIGNMENT         g_pal_control->alloc_align
> #define IS_ALLOC_ALIGNED(x)     IS_ALIGNED_POW2(x, g_pal_control->alloc_align)
> ```

1) Please wrap `x` in `()` (again in practice not needed, but sill :) )
2) Maybe use `ALLOC_ALIGNMENT` here?
ditto for all below
___
*[LibOS/shim/src/shim_checkpoint.c, line 534 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTv5xx-S9awmyhWfkd:-MZTv5xx-S9awmyhWfke:by51vea) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/src/shim_checkpoint.c#L534)):*
> ```C
> 
>         cpstore.bound >>= 1;
>         if (cpstore.bound < g_pal_control->alloc_align)
> ```

Hmm, what's the rule here: when do we use `ALLOC_ALIGNMENT` and when `g_pal_control->alloc_align`? 
___
*[LibOS/shim/src/shim_object.c, line 11 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTwY3L0ehz19OjVXlC:-MZTwY3L0ehz19OjVXlD:b4konh3) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/src/shim_object.c#L11)):*
> ```C
> 
>     if (ret < 0) {
>         log_error("waiting on an object with retry failed (%ld)\n", pal_to_unix_errno(ret));
> ```

Please just do `ret = pal_to_unix_errno(ret)`, instead of calling it twice.
___
*[Pal/include/pal/pal.h, line 179 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTxsnc7G_P8k7IXOvv:-MZTxsnc7G_P8k7IXOvw:bu9shzp) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/Pal/include/pal/pal.h#L179)):*
> ```objc
> } PAL_CONTROL;
> 
> PAL_CONTROL* DkGetPalControl(void);
> ```

Hmm, could this return `const PAL_CONTROL*` ?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1188 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZU-Xq1C3EuQwA4-dU1:-MZU-Xq26Ogkw0Ch1nZJ:b-6azbs6) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/Pal/src/host/Linux-SGX/enclave_framework.c#L1188)):*
> ```C
> 
> out:
>     ocall_shutdown(stream->process.stream, SHUT_RDWR);
> ```

Why not `_DkStreamDelete`?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1278 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZU-_dkEYM6vet4WiyW:-MZU-_dkEYM6vet4WiyX:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/Pal/src/host/Linux-SGX/enclave_framework.c#L1278)):*
> ```C
> 
> out:
>     ocall_shutdown(stream->process.stream, SHUT_RDWR);
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-04-30 00:52 UTC, mkow requested changes
> Reviewed 50 of 71 files at r1, 21 of 23 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/shim_internal.h, line 337 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTuLdlAdpBuq8IFhkv:-MZVFIevDO1NK4xbhf9d:bgeqno) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/include/shim_internal.h#L337)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

1) Please wrap `x` in `()` (again in practice not needed, but sill :) )
2) Maybe use `ALLOC_ALIGNMENT` here?
ditto for all below
</blockquote></details>

ad. 1: we don't do this in other places, so I'd keep it as-is for consistency (and technically it's not a problem, as you already said)
ad. 2: +1
___
*[LibOS/shim/src/shim_init.c, line 37 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTlFxb7Ztqu_3LI1F6:-MZTlFxcAzUHFkLDDgFP:b-94f737) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/src/shim_init.c#L37)):*
> ```C
> 
> const toml_table_t* g_manifest_root = NULL;
> const PAL_CONTROL* g_pal_control    = NULL;
> ```

I'd unalign this.


<!-- Sent from Reviewable.io -->

2021-04-30 07:11 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: 63 of 75 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/include/shim_internal.h, line 336 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTuAbIAU7DbIG-Pv8z:-MZWUfPm2_YH9JRKI8Rh:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/include/shim_internal.h#L336)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please wrap with `()` (in practice it's not needed since `->` has highest precedence, but still please do).
</blockquote></details>

Done
___
*[LibOS/shim/include/shim_internal.h, line 337 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTuLdlAdpBuq8IFhkv:-MZWUoMO-LBgqTCGdTvE:bl9ebnz) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/include/shim_internal.h#L337)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok, then ignore 1)
</blockquote></details>

Done for (2)
___
*[LibOS/shim/src/Makefile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZWazpG7xGdq12pB7MA:-MZWazpG7xGdq12pB7MB:blwa427) ([raw file](https://github.com/oscarlab/graphene/blob/d310903711def441e53b74f6a45a98c7799f69c5/LibOS/shim/src/Makefile#L37)):*
> ```Makefile
> # TODO: This is due to use of packed structs in IPC code, which triggers "taking address of a packed
> # member" warning in Clang and newer GCC. That code needs to be rewritten.
> CFLAGS += $(cc-option,-Wno-address-of-packed-member)
> ```

FYI: After a routine update of my Ubuntu 18.04, I got gcc 8.4.0 which started to complain about this "unknown option". So added this tiny fix.
___
*[LibOS/shim/src/shim_checkpoint.c, line 534 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTv5xx-S9awmyhWfkd:-MZWUxHo27_uxutvylzB:bc7hmdm) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/src/shim_checkpoint.c#L534)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, what's the rule here: when do we use `ALLOC_ALIGNMENT` and when `g_pal_control->alloc_align`? 
</blockquote></details>

Done. I use `ALLOC_ALIGNMENT` everywhere now.
___
*[LibOS/shim/src/shim_init.c, line 37 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTlFxb7Ztqu_3LI1F6:-MZWV7Bn28-YbalxQmpg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/src/shim_init.c#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd unalign this.
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_object.c, line 11 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTwY3L0ehz19OjVXlC:-MZWa-gX1vWVHxASnR9A:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/LibOS/shim/src/shim_object.c#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please just do `ret = pal_to_unix_errno(ret)`, instead of calling it twice.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 179 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZTxsnc7G_P8k7IXOvv:-MZWZuggCip4Mwc_ORM1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/Pal/include/pal/pal.h#L179)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, could this return `const PAL_CONTROL*` ?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1188 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZU-Xq1C3EuQwA4-dU1:-MZW_m4SEGyI7W8d7aFJ:bhn09x7) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/Pal/src/host/Linux-SGX/enclave_framework.c#L1188)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `_DkStreamDelete`?
</blockquote></details>

Done. My blunder.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 1278 at r3](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZU-_dkEYM6vet4WiyW:-MZW_p6s3UMXbsWPQwwT:bhn09x7) ([raw file](https://github.com/oscarlab/graphene/blob/30c1591c64145a8656ca595583118001fa0ed132/Pal/src/host/Linux-SGX/enclave_framework.c#L1278)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. My blunder.


<!-- Sent from Reviewable.io -->

2021-04-30 07:33 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: 63 of 75 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/Makefile, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2339#-MZWazpG7xGdq12pB7MA:-MZWgaaH3z-itsa1UYlz:b6xpprb) ([raw file](https://github.com/oscarlab/graphene/blob/d310903711def441e53b74f6a45a98c7799f69c5/LibOS/shim/src/Makefile#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: After a routine update of my Ubuntu 18.04, I got gcc 8.4.0 which started to complain about this "unknown option". So added this tiny fix.
</blockquote></details>

I take it back. The problem was not in this. Reverted because it started failing on 20.04 due to this change.


<!-- Sent from Reviewable.io -->

2021-04-30 08:08 UTC, pwmarcz approved these changes
> Reviewed 11 of 12 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-04-30 08:27 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-20.04-apps please (looks like Jenkins worker died)

2021-04-30 12:38 UTC, mkow approved these changes
> Reviewed 11 of 12 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-04-30 13:37 UTC, boryspoplawski approved these changes
> Reviewed 11 of 12 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-04-30 22:32 UTC, mkow approved these changes
> Reviewed 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-05-03 06:40 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (`mprotect02` LTP test failed, cannot reproduce locally)

2021-05-03 07:13 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (just making sure)

2021-05-03 11:35 UTC, pwmarcz approved these changes
> Reviewed 9 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2339)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-03 11:41 UTC, merged