[GSC] Exclude deprecated files from trusted files list
oscarlab/graphene pull request #2341
Opened 2021-04-30 04:40 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 

While running gsc images as part of Azure Kubernetes Services (AKS) Cluster (kubernetes version 1.19.9), the following errors are showing up:

Could not find size of file: file:/.dockerenv
Failed to load the checksums of trusted files: -9

OR (if previous error is resolved then the next error)

Could not find size of file: file:/.dockerinit
Failed to load the checksums of trusted files: -9

OR

Could not find size of file: file:/etc/mtab
Failed to load the checksums of trusted files: -9

.dockerenv and .dockerinit are considered to be deprecated (https://superuser.com/questions/1021834/what-are-dockerenv-and-dockerinit). 
 
For /etc/mtab file also, there are open issues of broken symlinks (https://github.com/kubernetes/kubernetes/issues/96961).

These 3 files are not used for the gsc-images we tested so far. Hence, we can exclude them from the trusted files list that will be appended inside entrypoint.manifest file. 

As part of the fix, these 3 files are excluded inside finalize_manifest.py.

## How to test this PR?

1. Create a gsc-python image or any other gsc image and deploy it inside AKS cluster (Exact steps described here: https://graphene.readthedocs.io/en/latest/cloud-deployment.html#deploying-a-helloworld-python-application-in-a-confidential-compute-aks-cluster).

2.  First try without the fix: the error will show up.

3.  After putting the fix, the issue resolves.

Note: This issue is observed only with Azure Kubernetes Cluster, with regular docker run the image runs successfully.

2021-04-30 06:15 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2341)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2341#-MZWPNqh3bExegR-chnh:-MZWPNqh3bExegR-chni:bbsebi1) (no related file):*
Looks legit, thanks! `.dockerenv` and `.dockerinit` files are definitely not needed inside the SGX enclave (we never enclavize the Docker itself). `/etc/mtab` is used to point to/enumerate existing host-OS volumes, which is not something we support in Graphene anyway.

---
___
*[Tools/gsc/finalize_manifest.py, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2341#-MZWP5E7EOSkSMzReMhf:-MZWP5E85S_WlHKxJFEK:b-g6yp04) ([raw file](https://github.com/oscarlab/graphene/blob/db025923d60fff6bc0cc90447bf75409db6401e6/Tools/gsc/finalize_manifest.py#L40)):*
> ```Python
>     excluded_paths_regex = (r'^/('
>                                 r'boot/.*'
>                                 r'|.dockerenv'
> ```

`.` by itself means "any character" in regex. You want an actual dot as part of the name, so you need to use escaping: `\.`. In the end, you need this string: `r'|\.dockerenv'`.
___
*[Tools/gsc/finalize_manifest.py, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2341#-MZWPM-3C84uApNan39X:-MZWPM-3C84uApNan39Y:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/db025923d60fff6bc0cc90447bf75409db6401e6/Tools/gsc/finalize_manifest.py#L41)):*
> ```Python
>                                 r'boot/.*'
>                                 r'|.dockerenv'
>                                 r'|.dockerinit'
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-04-30 07:02 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2341)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2341#-MZWPNqh3bExegR-chnh:-MZW_PtZ6Gw7fYwg0Q8m:b-ucfkn4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks legit, thanks! `.dockerenv` and `.dockerinit` files are definitely not needed inside the SGX enclave (we never enclavize the Docker itself). `/etc/mtab` is used to point to/enumerate existing host-OS volumes, which is not something we support in Graphene anyway.
</blockquote></details>

Thanks.

---
___
*[Tools/gsc/finalize_manifest.py, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene/2341#-MZWP5E7EOSkSMzReMhf:-MZW_UPsBHG_p0yD-nxQ:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/db025923d60fff6bc0cc90447bf75409db6401e6/Tools/gsc/finalize_manifest.py#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`.` by itself means "any character" in regex. You want an actual dot as part of the name, so you need to use escaping: `\.`. In the end, you need this string: `r'|\.dockerenv'`.
</blockquote></details>

done, thanks.
___
*[Tools/gsc/finalize_manifest.py, line 41 at r1](https://reviewable.io/reviews/oscarlab/graphene/2341#-MZWPM-3C84uApNan39X:-MZW_Vcs2giLDQnR98tY:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/db025923d60fff6bc0cc90447bf75409db6401e6/Tools/gsc/finalize_manifest.py#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-04-30 07:15 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2341)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-04-30 07:16 UTC, dimakuv commented
Jenkins, test this please

2021-05-03 11:00 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2341)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-05-05 18:17 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2341)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-05-05 18:17 UTC, mkow commented
Jenkins, retest this please

2021-05-05 20:03 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2341)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-05 20:04 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please

2021-05-05 23:07 UTC, merged