[LibOS] Don't store dentry paths
oscarlab/graphene pull request #2342
Opened 2021-04-30 11:58 UTC by pwmarcz

This is the next step in FS rewrite, after #2333 (I'll rebase after it's merged).

See also the issue for dentry cleanup (#2321).

This change removes `shim_dentry.rel_path` and `shim_handle.path` fields. Instead, the path is computed whenever necessary. This also means that the length limit for relative path is lifted.

To obtain a path for a dentry, use `dentry_abs_path` or `dentry_rel_path`. The constructed path is allocated on heap and must be
freed afterwards.

Because computing the path can fail when out of memory, the functions for hashing dentries do not compute the path explicitly, but follow the dentry chain to the root.

(There were many places in the code was responsible for maintaining the stored path, or enforcing the length. It looked pretty brittle. So I think this is a positive change).

**Next step**: rewrite `mount_fs` and make mount semantics more sane (as mentioned in #2324). More specifically, I want mounting to not _replace_ a dentry, but attach a new tree under it. This way, both the original mountpoint and the mounted directory can exist in the dentry tree.
* if a dentry is marked as a mountpoint, you're supposed to go to `dentry->mounted->root`,
* `dentry->parent` can be null not only for the global root, but also for the filesystem root, in which case you can go to `dentry->fs->mountpoint`.

2021-05-06 08:19 UTC, dimakuv requested changes
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-XjZnAj7C8inWSt6Y:-M_-XjZnAj7C8inWSt6Z:bpc1rlr) (no related file):*
> Because computing the path can fail when out of memory, the functions
> for hashing dentries do not compute the path explicitly, but follow the
> dentry chain to the root.

This explanation in the commit message is not understandable. I will check what the code actually does and will propose to reword it.

---
___
*[LibOS/shim/include/shim_fs.h, line 496 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ZJcC7Sp8BiKonRrX:-M_-ZJcC7Sp8BiKonRrY:b5uheb) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L496)):*
> ```objc
>  * \returns pointer to the path, or NULL if out of memory
>  *
>  * This function computes a path for dentry, allocating a new buffer for it.  The returned string
> ```

You have double space after `.`, please remove one space.
___
*[LibOS/shim/include/shim_fs.h, line 499 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ZTxE7kk11NRACGRN:-M_-ZTxE7kk11NRACGRO:b-ivbwj4) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L499)):*
> ```objc
>  * should be freed using `free`.
>  *
>  * An absolute path is a combination of all names up to the root (not including the root), separated
> ```

I don't understand the remark `not including the root`. Don't you include the root simply by the fact that the path starts with `/`?
___
*[LibOS/shim/include/shim_fs.h, line 513 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-_h9u6EXxgyvCGLaY:-M_-_h9u6EXxgyvCGLaZ:bz1t56w) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L513)):*
> ```objc
> char* dentry_rel_path(struct shim_dentry* dent, size_t* sizep);
> 
> char* dentry_abs_path_into_qstr(struct shim_dentry* dent, struct shim_qstr* str);
> ```

BTW, I hate this `qstr` trick. At some point, I would prefer to replace it with normal `char*` strings.
___
*[LibOS/shim/include/shim_fs.h, line 580 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-aIYoBdC6mUdDL9A-:-M_-aIYoBdC6mUdDL9A0:b-ar9owi) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L580)):*
> ```objc
>  */
> 
> int init_hash(void);
> ```

What is this function? I don't see it anywhere.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 793 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-bn1C6WT6sTUafGim:-M_-bn1C6WT6sTUafGin:be077h8) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/bookkeep/shim_handle.c#L793)):*
> ```C
>         hdl->fs->fs_ops->checkin(hdl);
> 
> #if DEBUG_RESUME == 1
> ```

Is this macro really useful? If you haven't used it, maybe just delete this macro and corresponding logic?
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1341 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-c2PM6wtdbuTRaxk_:-M_-c2PM6wtdbuTRaxka:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/bookkeep/shim_vma.c#L1341)):*
> ```C
>     }
> 
> #if DEBUG_RESUME == 1
> ```

ditto
___
*[LibOS/shim/src/fs/shim_dcache.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ctE73p6XGrGgj1EG:-M_-ctE73p6XGrGgj1EH:ba3y5ex) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L128)):*
> ```C
>     int64_t count = REF_DEC(dent->ref_count);
> #ifdef DEBUG_REF
>     const char* path = dentry_abs_path(dent);
> ```

Forgot to `free(path)` afterwards?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 266 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-emJDAfCuNnw5r4Qd:-M_-emJDAfCuNnw5r4Qe:b-fmf09i) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L266)):*
> ```C
> }
> 
> static char* dentry_path_into_buf(struct shim_dentry* dent, bool relative, char* buf, size_t size) {
> ```

It's worth mentioning that this function returns a pointer inside `buf` where the constructed path starts (not necessarily the beginning of `buf`), because it constructs the path from the end
___
*[LibOS/shim/src/fs/shim_dcache.c, line 274 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-e0dV0ZQoKik7eN5Q:-M_-e0dV0ZQoKik7eN5R:b-s9zprr) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L274)):*
> ```C
>     /* Add names, starting from the last one, until we encounter root */
>     while (dent && dent->parent) {
>         /* If the path is relative, also finish when encountering a mountpoint */
> ```

So in the context of our FS subsystem, "relative" means "ending at the first encountered mountpoint", right? It has nothing to do with the conventional meaning of "ending at the CWD"?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 478 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-fmNo6DCy_F5-UMXx:-M_-fmNo6DCy_F5-UMXy:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L478)):*
> ```C
>     }
> 
> #if DEBUG_RESUME == 1
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs.c, line 444 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-h1N536npG-Y2jQ1N:-M_-h1N536npG-Y2jQ1O:b-3g9emf) ([raw file](https://github.com/oscarlab/graphene/blob/51dcf9681bbb2e009698b22e47f870cff8b37a21/LibOS/shim/src/fs/shim_fs.c#L444)):*
> ```C
>      * rehash the path; this should be handled by get_new_dentry, or already be
>      * hashed if mount_root exists.  I'm going to leave this line here for now
>      * as documentation in case there is a problem later.
> ```

Oh these comments from the past "I don't know what's this but let's keep it", I will miss you :)
___
*[LibOS/shim/src/fs/shim_fs.c, line 562 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-hlDN-B1RdOSXSzon:-M_-hlDN-B1RdOSXSzoo:b-q51yan) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_fs.c#L562)):*
> ```C
>     dent->state |= DENTRY_MOUNTPOINT;
>     if ((ret = _path_lookupat(g_dentry_root, mount_point, lookup_flags, &dent2)) < 0) {
>         dent->state &= ~DENTRY_MOUNTPOINT;
> ```

Why does it even matter? Aren't we supposed to destroy this dentry on failure to look it up? On the other hand, you will rewrite this function in a next PR, so may ignore this comment.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-jJ4dApdT-NrJhWvD:-M_-jJ4dApdT-NrJhWvE:bb96k8h) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/chroot/fs.c#L26)):*
> ```C
> #include "stat.h"
> 
> #define READDIR_BUF_SIZE 4096
> ```

Don't you want to move it to some header file? You use it already twice.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 550 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-k63C2fRl_ZS_Kgqm:-M_-k63C2fRl_ZS_Kgqn:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/sys/shim_epoll.c#L550)):*
> ```C
>         CP_REBASE(epoll_item->list);
> 
> #if DEBUG_RESUME == 1
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-05-06 09:18 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: 18 of 22 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 496 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ZJcC7Sp8BiKonRrX:-M_-ne_IAm-Cekx5bfdK:b-bcbxh5) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L496)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have double space after `.`, please remove one space.
</blockquote></details>

Fixed. And I changed the setting in my Emacs that does this :)
___
*[LibOS/shim/include/shim_fs.h, line 499 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ZTxE7kk11NRACGRN:-M_-oXCnD4gQ6gkCSnYT:b-5ulim8) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L499)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand the remark `not including the root`. Don't you include the root simply by the fact that the path starts with `/`?
</blockquote></details>

I wanted to give a definition that closely describes what the code does. Consider a path like `/foo/bar`. The dentries on the path are `name_0 = ""` (the root), `name_1 = "foo"`, and `name_2 = "bar"`.

By my definition, the absolute path is a combination of `"foo"` and `"bar"`, separated by `/`, and beginning with `/`: `"/" + name_1 + "/" + name_2`.

I _could_ also define the absolute path as "a combination of all names up to the root; separated by `/`", and note that because the last name is empty, the path always begins with `/`. The above path would be then defined as `name_0 + "/" + name_1 + "/" + name_2`.

However, I don't like it because:
- the fact that an absolute path starts with root becomes an incidental property instead of essential part of the definition,
- the root itself (`/`) becomes an exception, because by above definition the absolute path would be empty.

Does that make sense? Should I reword the comment to make this clearer? Maybe "An absolute path is a combination of all names up to the root (not including the root, which by convention has an empty name), separated by `/` and beginning with `/`".
___
*[LibOS/shim/include/shim_fs.h, line 513 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-_h9u6EXxgyvCGLaY:-M_-rKaY4zd9ISDG6ns-:b-flzza6) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L513)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, I hate this `qstr` trick. At some point, I would prefer to replace it with normal `char*` strings.
</blockquote></details>

Agreed, I'm trying not to use it in new code, and we can replace the remaining places that use it.

I think it was taken from Linux filesystem code, which uses it (among other things) to store a hash together with a string? But we never did that consistently.
___
*[LibOS/shim/include/shim_fs.h, line 580 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-aIYoBdC6mUdDL9A-:-M_-rchJElQk6qstgdiy:b-gnsg6i) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L580)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this function? I don't see it anywhere.
</blockquote></details>

Right. Removed.

(It's a leftover from when I briefly wanted to use CRC64 for the hashes, and the function initialized a lookup table. I decided not to bother, I think a proper solution wouldn't use path hashes anyway.)
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 793 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-bn1C6WT6sTUafGim:-M_-ruPG0mjZkbMNSMrS:bxntwsg) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/bookkeep/shim_handle.c#L793)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this macro really useful? If you haven't used it, maybe just delete this macro and corresponding logic?
</blockquote></details>

I haven't used it but I never did anything with the checkpoint/restore system. I expect it might be useful for debugging the checkpoints, so I'm not comfortable deleting that code while making an unrelated (to some degree) change.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ctE73p6XGrGgj1EG:-M_-t346A2JXbwRCRmOd:b-aydsdc) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to `free(path)` afterwards?
</blockquote></details>

Fixed.

By the way, unlike `DEBUG_RESUME`, I did use these messages at one point.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 266 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-emJDAfCuNnw5r4Qd:-M_-txJX6_BtU1X__YMx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L266)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's worth mentioning that this function returns a pointer inside `buf` where the constructed path starts (not necessarily the beginning of `buf`), because it constructs the path from the end
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 274 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-e0dV0ZQoKik7eN5Q:-M_-u-in8Uov-VJ-0skR:btz9ggg) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L274)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So in the context of our FS subsystem, "relative" means "ending at the first encountered mountpoint", right? It has nothing to do with the conventional meaning of "ending at the CWD"?
</blockquote></details>

Yes.

I guess calling it "mount-relative" would be less confusing, but it looks pretty bad in the code, and the name (`rel_path` etc.) is pretty well established in the code already.
___
*[LibOS/shim/src/fs/shim_fs.c, line 562 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-hlDN-B1RdOSXSzon:-M_-vMn9DnDfK_UPmFWk:b289r6c) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_fs.c#L562)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why does it even matter? Aren't we supposed to destroy this dentry on failure to look it up? On the other hand, you will rewrite this function in a next PR, so may ignore this comment.
</blockquote></details>

Yes, I decided this function is beyond repair, it will work differently anyway. This PR prepares the ground, and fortunately, the next PR is finally the moment I can rewrite it.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-jJ4dApdT-NrJhWvD:-M_-vixY05g_-uRKFKLt:b-w02z4x) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/chroot/fs.c#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't you want to move it to some header file? You use it already twice.
</blockquote></details>

Okay, moved to `shim_fs.h`. I left it [...]

2021-05-06 09:39 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-XjZnAj7C8inWSt6Y:-M_00tgS0z4i69v89yT3:b6va25w) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Because computing the path can fail when out of memory, the functions
> for hashing dentries do not compute the path explicitly, but follow the
> dentry chain to the root.

This explanation in the commit message is not understandable. I will check what the code actually does and will propose to reword it.
</blockquote></details>

OK, the commit message actually makes sense. The hash functions iterate through `dentry->name` and update the hash based on this, instead of concatenating names into one string and then taking a hash over it. Unblocking.

---
___
*[LibOS/shim/include/shim_fs.h, line 499 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ZTxE7kk11NRACGRN:-M_01Pdn--fqu6xkW_wu:bsn3yj1) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L499)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I wanted to give a definition that closely describes what the code does. Consider a path like `/foo/bar`. The dentries on the path are `name_0 = ""` (the root), `name_1 = "foo"`, and `name_2 = "bar"`.

By my definition, the absolute path is a combination of `"foo"` and `"bar"`, separated by `/`, and beginning with `/`: `"/" + name_1 + "/" + name_2`.

I _could_ also define the absolute path as "a combination of all names up to the root; separated by `/`", and note that because the last name is empty, the path always begins with `/`. The above path would be then defined as `name_0 + "/" + name_1 + "/" + name_2`.

However, I don't like it because:
- the fact that an absolute path starts with root becomes an incidental property instead of essential part of the definition,
- the root itself (`/`) becomes an exception, because by above definition the absolute path would be empty.

Does that make sense? Should I reword the comment to make this clearer? Maybe "An absolute path is a combination of all names up to the root (not including the root, which by convention has an empty name), separated by `/` and beginning with `/`".
</blockquote></details>

I like your proposed rewording, please add that part about "by convention"
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 793 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-bn1C6WT6sTUafGim:-M_01d0606NdIhwvvIWq:bs4ixp3) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/bookkeep/shim_handle.c#L793)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I haven't used it but I never did anything with the checkpoint/restore system. I expect it might be useful for debugging the checkpoints, so I'm not comfortable deleting that code while making an unrelated (to some degree) change.
</blockquote></details>

OK, fair enough.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ctE73p6XGrGgj1EG:-M_01hHX74pNAVhkrQ3M:byz0mxe) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L128)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Fixed.

By the way, unlike `DEBUG_RESUME`, I did use these messages at one point.
</blockquote></details>

Yes, `DEBUG_REF` is sometimes useful :)
___
*[LibOS/shim/src/fs/shim_dcache.c, line 274 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-e0dV0ZQoKik7eN5Q:-M_01oc_B2ps1hKHfr9O:b-mcw7o4) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L274)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes.

I guess calling it "mount-relative" would be less confusing, but it looks pretty bad in the code, and the name (`rel_path` etc.) is pretty well established in the code already.
</blockquote></details>

OK. I like the naming scheme, just wanted to make sure.


<!-- Sent from Reviewable.io -->

2021-05-06 10:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: 21 of 22 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_fs.h, line 499 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ZTxE7kk11NRACGRN:-M_0CTgREWcJW56fNRd9:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/include/shim_fs.h#L499)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like your proposed rewording, please add that part about "by convention"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-06 10:30 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-06 23:54 UTC, mkow requested changes
> Reviewed 18 of 22 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_2pkoQEOf8Y60A9fZi:-M_2pkoQEOf8Y60A9fZj:b-ya7edk) (no related file):*
@boryspoplawski wanted to take a look at this PR because he tried to do the same some time ago. So, I'm doing just a quick review and will rely on his judgements ;)

---
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 376 at r3](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_31gVZ5bxhUS6zvMKN:-M_31gVZ5bxhUS6zvMKO:b-vn22fj) ([raw file](https://github.com/oscarlab/graphene/blob/c5ff4e1118c1dc9670f86193e43dd31a846af35f/LibOS/shim/src/fs/shim_fs_pseudo.c#L376)):*
> ```C
> int pseudo_follow_link(struct shim_dentry* dent, struct shim_qstr* link,
>                        const struct pseudo_ent* root_ent) {
>     char* rel_path = dentry_rel_path(dent, /*sizep=*/NULL);
> ```

Missing check for retval?
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 306 at r3](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_32QaI8Ap7PxJRnSC1:-M_32QaI8Ap7PxJRnSC2:bdcbvqh) ([raw file](https://github.com/oscarlab/graphene/blob/c5ff4e1118c1dc9670f86193e43dd31a846af35f/LibOS/shim/src/ipc/shim_ipc_pid.c#L306)):*
> ```C
> 
>             struct shim_dentry* dent = NULL;
>             switch(msgin->code) {
> ```

missing space after `switch`


<!-- Sent from Reviewable.io -->

2021-05-07 08:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_2pkoQEOf8Y60A9fZi:-M_51vvo1UPvGJ0zeIY6:brujzsz) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski wanted to take a look at this PR because he tried to do the same some time ago. So, I'm doing just a quick review and will rely on his judgements ;)
</blockquote></details>

OK, thanks!

---
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 376 at r3](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_31gVZ5bxhUS6zvMKN:-M_51ndWDQm908IiP6-J:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/c5ff4e1118c1dc9670f86193e43dd31a846af35f/LibOS/shim/src/fs/shim_fs_pseudo.c#L376)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Missing check for retval?
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 306 at r3](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_32QaI8Ap7PxJRnSC1:-M_51pEyAQ9Rda7sLqTx:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/c5ff4e1118c1dc9670f86193e43dd31a846af35f/LibOS/shim/src/ipc/shim_ipc_pid.c#L306)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing space after `switch`
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-05-07 15:53 UTC, mkow reviewed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-05-08 00:52 UTC, yamahata approved these changes
> Reviewed 18 of 22 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-05-10 00:35 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_2pkoQEOf8Y60A9fZi:-M_IgM9Q-Le6QCqrqtYI:breqv7w) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, thanks!
</blockquote></details>

(small correction, for the record: I misread one of Borys' messages, he didn't work on this previously, but just wanted to take a look before merging)

---


<!-- Sent from Reviewable.io -->

2021-05-10 13:04 UTC, boryspoplawski requested changes
> Reviewed 17 of 22 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 16 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 217 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_KsjFi82R2ZBqvYuV-:-M_KsjFi82R2ZBqvYuV0:b3zzj6m) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L217)):*
> ```objc
>     struct shim_d_ops* d_ops;
> 
>     /* TODO: this is unused right now (see `mount_point`) */
> ```

Why not remove it for now then?
___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L1ExE7IYDal77Dmbq:-M_L1ExE7IYDal77Dmbr:bl4ayzp) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
> ```objc
>  * \param[out] sizep if not NULL, will be set to path size, including null terminator
>  *
>  * \returns pointer to the path, or NULL if out of memory
> ```

Isn't the keyword `\return`?
___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L2mhu0EfEgTsFHIhA:-M_L2mhu0EfEgTsFHIhB:bedddjy) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
> ```objc
>  * \param[out] sizep if not NULL, will be set to path size, including null terminator
>  *
>  * \returns pointer to the path, or NULL if out of memory
> ```

Could you return the calues with out-params and errors directly from the function? We recently switched to that convention, at least in PAL API, but IMO we should go with it everywhere.
___
*[LibOS/shim/include/shim_fs.h, line 505 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L3Tj9C099MRS8uQKU:-M_L3Tj9C099MRS8uQKV:bprlh7t) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L505)):*
> ```objc
>  * mountpoint), separated by `/`. A relative path never begins with `/`.
>  *
>  * Instead of using this function directly, you should use `dentry_abs_path` or `dentry_rel_path`,
> ```

Why this function is even exported then? It's not used anywhere outside of `dentry_*_path` and as you suggested shouldn't be.
___
*[LibOS/shim/include/shim_fs.h, line 513 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LDsRdDyu6ahO2tKmq:-M_LDsRdDyu6ahO2tKmr:b-3fg6kj) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L513)):*
> ```objc
> char* dentry_rel_path(struct shim_dentry* dent, size_t* sizep);
> 
> char* dentry_abs_path_into_qstr(struct shim_dentry* dent, struct shim_qstr* str);
> ```

Could you just return `int` errors here? No call places uses the return value for anything except checking for errors.
___
*[LibOS/shim/src/shim_rtld.c, line 873 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L5atQ7h1HnnFr8jQg:-M_L5atQ7h1HnnFr8jQh:bp92bzv) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/shim_rtld.c#L873)):*
> ```C
>                       "case Graphene requires a specially-crafted memory layout. You can enable it "
>                       "by adding 'sgx.nonpie_binary = 1' to the manifest.\n",
>                       path ? path : "(unknown)");
> ```

Hmm, wouldn't be a host path better to print in this place?
Not sure, just an idea.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 89 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L6CoHAE2gK95T24So:-M_L6CoHAE2gK95T24Sp:bh64i34) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/bookkeep/shim_handle.c#L89)):*
> ```C
>             return ret;
>         }
>         if (exec->dentry->fs != fs) {
> ```

Couldn't we check that `exec->dentry` points to a real file (not a mountpoint, not a directory etc)? Like check the type or something.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ctE73p6XGrGgj1EG:-M_L7S3ZC3tgCqgxfHBn:b38yf7x) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, `DEBUG_REF` is sometimes useful :)
</blockquote></details>

Can confirm, used `DEBUG_REF` a few times, but never `DEBUG_RESUME` :)
___
*[LibOS/shim/src/fs/shim_dcache.c, line 172 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L7pys8Ir0KY_tdAai:-M_L7pys8Ir0KY_tdAaj:b-ua5ty9) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_dcache.c#L172)):*
> ```C
> 
>     if (!qstrsetstr(&dent->name, name, name_len))
>         return NULL;
> ```

Shouldn't we cleanup here? I.e. `put_mount(fs)` and `free_dentry(dent)`.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 254 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L9wy_Dh7v7rMhOHtE:-M_L9-v10XCs_idd-Hvp:b92crd2) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_dcache.c#L254)):*
> ```C
>             break;
> 
>         if (!first)
> ```

Not blocking, but I think we could remove `first`, always add `1` here and change `if (!relative)` to `if (relative && size > 1) { size--; }` after the loop. Not sure if that would be cleaner though.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 255 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L9_UA0smrguCbh40r:-M_L9_UA0smrguCbh40s:bnp5zkz) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_dcache.c#L255)):*
> ```C
> 
>         if (!first)
>             size++;
> ```

Could you add a quick comment this accounts for `/` separating two path segments?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 262 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L9Iqb6rJYQdNMwo99:-M_L9Iqb6rJYQdNMwo9A:b-2vujki) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_dcache.c#L262)):*
> ```C
> 
>     if (!relative)
>         size++;
> ```

Could you add a quick comment this accounts for leading `/`?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 271 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LAva86vw4IcvDA_gk:-M_LAva86vw4IcvDA_gl:bhw3nph) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_dcache.c#L271)):*
> ```C
> static char* dentry_path_into_buf(struct shim_dentry* dent, bool relative, char* buf, size_t size) {
>     bool first = true;
>     size_t pos = size - 1;
> ```

Sounds like a good thing to assert (`size > 0`) or even explicitly check.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 276 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LBLsxAQH5CcpbX3DF:-M_LBLsxAQH5CcpbX3DG:besnspr) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_dcache.c#L276)):*
> ```C
> 
>     /* Add names, starting from the last one, until we encounter root */
>     while (dent && dent->parent) {
> ```

Why is `dent == NULL` allowed to be passed to this function?
___
*[LibOS/shim/src/fs/shim_fs.c, line 560 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LFRRz8ykE0qdGxqn0:-M_LFRRz8ykE0qdGxqn1:b-bifx0n) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_fs.c#L560)):*
> ```C
> 
>     /*Now go ahead and do a lookup so the dentry is valid */
>     dent->state |=  [...]

2021-05-11 10:41 UTC, mkow requested changes
> Reviewed 1 of 22 files at r1, 7 of 8 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L1ExE7IYDal77Dmbq:-M_PxEoU9F53Sz6Tbniz:bi5kdir) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Doxygen allows both, so I was using `\returns` so that this reads better. But I see that we consistently use return. Updated.
</blockquote></details>

Didn't know it's allowed, I like `returns` much more! But let's change and unify this in another PR.
___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L2mhu0EfEgTsFHIhA:-M_PxntH3ql1rpXCdDuR:b-9h21dd) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> We recently switched to that convention, at least in PAL API

I don't think we should go to this extreme... For internal functions, most of the time a NULL/non-NULL distinction is sufficient.
</blockquote></details>

Yeah, I think if the only possible failure is ENOMEM then returning NULL should be fine.
___
*[LibOS/shim/src/shim_rtld.c, line 873 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L5atQ7h1HnnFr8jQg:-M_PzUi1E4PeSDQuVS0m:butksv4) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/shim_rtld.c#L873)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I agree. Changed to URI.
</blockquote></details>

Hmm, not sure if this is a good idea. What if we start a binary from tmpfs? (after its fixed to be shared between processes) And conceptually, Graphene is starting files from its internal "mount namespace", not from the host.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LGyqQ1QMgWcPCtlWv:-M_Q-Vqf0uVCL0RHdnAs:b-4mfjni) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_fs_hash.c#L40)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Because now that path can be arbitrarily large, the previous version (take a path and compute a hash based on it) can fail on allocation. Instead of adding error handling everywhere, I decided to write a version that doesn't allocate memory.

As for "something sane": this is mostly for inventing inode values, so hashing is just not correct here (because two paths might resolve to the same hash). I wonder how important this is - if we don't care, I could use a better function (CRC64?), if we do, then probably we need to allocate the numbers in a different way.
</blockquote></details>

I think we care about this, inode collisions may be a security issue, so I'd allocate them properly.


<!-- Sent from Reviewable.io -->

2021-05-11 12:09 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L2mhu0EfEgTsFHIhA:-M_QJVsj7OZ-9hGZ9j5Z:bywt7i5) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Generally I agree, for simple functions returning object poitner makes more sense, but this already has out-peremeter (`sizep`) and I dislike this convention (returning values both directly and via out-param from one function).
Resolving as others seem fine, maybe just personal opinion.
</blockquote></details>

Ah, I didn't notice that part of the result is in out-parameter. Then I'd return everything through args, but I won't block.
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LGyqQ1QMgWcPCtlWv:-M_QK1wJ2ZkO0hSIROMb:bu4t6yd) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_fs_hash.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But previous version had no allocations and seemed to handle arbitrary size? Not that I want it restored, but I'm confused.
</blockquote></details>

The problem is not about sizes and memory allocation, but about inode number allocation which can collide in the current implementation. The change with memory allocation removal from here is perfectly fine.


<!-- Sent from Reviewable.io -->

2021-05-11 12:17 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LGyqQ1QMgWcPCtlWv:-M_QLhrmDU1t69V0ShAj:bc8i10e) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_fs_hash.c#L40)):*
> (...) but about inode number allocation which can collide in the current implementation.

Yes, that's why I wanted to introduce a "sane" version.

> The change with memory allocation removal from here is perfectly fine.

The thing is I don't see any memory allocations in the original version...


<!-- Sent from Reviewable.io -->

2021-05-11 12:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LGyqQ1QMgWcPCtlWv:-M_QN3rB1tNVhS89XQUa:b4082vq) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_fs_hash.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> (...) but about inode number allocation which can collide in the current implementation.

Yes, that's why I wanted to introduce a "sane" version.

> The change with memory allocation removal from here is perfectly fine.

The thing is I don't see any memory allocations in the original version...
</blockquote></details>

Ah, right, now I'm also confused a bit :) Maybe it had to be allocated in the callsites due to the old API of this function, dunno. Let's wait for Paweł then.


<!-- Sent from Reviewable.io -->

2021-05-11 14:47 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L2mhu0EfEgTsFHIhA:-M_Qt7de3Qo3lqL4SZwj:bj5qjml) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, I see your point - this function already has an out-parameter.

What I don't like about the current code is that the `sizep` parameter is most of the time not necessary. There are only a few usages (5 out of 19 total):

```c
fs/chroot/fs.c:    char* rel_path = dentry_rel_path(dent, &rel_path_size);
fs/shim_dcache.c:    char* path = dentry_abs_path(dent, &size);
ipc/shim_ipc_pid.c:            if (!(data = dentry_abs_path(dent, &bufsize))) {
sys/shim_getcwd.c:    char* path = dentry_abs_path(cwd, &size);
sys/shim_socket.c:    char* path = dentry_abs_path(dent, &size);
```

And the rest of the code needs to pass an ugly `/*sizep=*/NULL`.

A few options:

1. Remove the `sizep` parameter, use `strlen()` if you need the size. A bit inefficient, but simplest.
2. Leave this code as-is.
3. Remove the `sizep` parameter, but keep a general-purpose function such as `int dentry_path(dentry, bool relative, char** path, size_t* sizep)` for the few places that do need the size.

What do you think?
</blockquote></details>

If it was up to me, I would do 4. `int dentry_rel_path(dentry, char** path, size_t* size)`. But 1 and 2 should be fine too, 3 seems excessive.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 89 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L6CoHAE2gK95T24So:-M_QrhGACigBkJaEL7ro:b2nhysk) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/bookkeep/shim_handle.c#L89)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Bad news: `dentry->type` seems unused :)

(It's even worse than `dentry->mode`, which is _cached_ mode and can be missing).

Longer term, I want to reorganize it so that:
* "special" dentry types (invalid, negative, synthetic etc.) are an enum, not a set of flags, so that there are no worrying questions about possible combinations,
* `mode` is Linux `st_mode` (file type and mode), is filled by `lookup()` fs operation; overall we make it so that `stat()` just reads the information from the dentry and does not require additional queries,
* `DENTRY_ISDIRECTORY` and `DENTRY_ISLINK` are replaced by `S_ISDIR(dentry->mode)` and `S_ISLNK(dentry->mode)`, etc.
</blockquote></details>

ack
___
*[LibOS/shim/src/fs/shim_fs_hash.c, line 40 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_LGyqQ1QMgWcPCtlWv:-M_QsEiH1QnGBycIgYqZ:bls79hh) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/src/fs/shim_fs_hash.c#L40)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>But previous version had no allocations and seemed to handle arbitrary size? Not that I want it restored, but I'm confused.

Sorry, I wasn't precise. There were no allocations _in this algorithm_, but the hash was (usually) computed based on `dentry->rel_path`, and XORed with a filesystem-specific value. Probably because that was convenient: the `rel_path` field was already there.

Now  that `rel_path` field is gone, in order to compute the hash for a given dentry, you would need to call `dentry_rel_path()` first, and handle a case where it gives you NULL. That's what I meant when I said that hashing the dentry can fail on allocation.

I thought it would be simpler to create `hash_abs_path()`, which does not require allocation, and works on absolute paths (so no need to manually XOR with a filesystem-specific value).
</blockquote></details>

FWIW prev version XORed hashes of each path segment.
Let's leave it as it is, it needs major rework anyway.


<!-- Sent from Reviewable.io -->

2021-05-11 17:44 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-05-11 18:14 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L2mhu0EfEgTsFHIhA:-M_RcR3Y3x6Ntz2ESpaV:b-jzirkn) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If it was up to me, I would do 4. `int dentry_rel_path(dentry, char** path, size_t* size)`. But 1 and 2 should be fine too, 3 seems excessive.
</blockquote></details>

I'm also flipping my vote, Borys is right :) It is confusing to have one return value in the return of function, and the other return value in the arg list. I would also go for 4.


<!-- Sent from Reviewable.io -->

2021-05-11 19:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L2mhu0EfEgTsFHIhA:-M_RoOVqAEBIi6XL1ldY:bmww6kn) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I'll change it to 4. Blocking until I'm done.
</blockquote></details>

Done, please review the changes.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_-ctE73p6XGrGgj1EG:-M_RotQh0Px92Mp_Zx_b:b-rp9nw1) ([raw file](https://github.com/oscarlab/graphene/blob/6beb06e20846e504a39ebed2bc057da0622531d2/LibOS/shim/src/fs/shim_dcache.c#L128)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's remove it in some other new PR, this will be simple.
</blockquote></details>

Okay, I'm convinced nobody will miss that code. I removed the `DEBUG_RS` invocations that used the now-removed path.


<!-- Sent from Reviewable.io -->

2021-05-12 00:18 UTC, mkow requested changes
> Reviewed 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 502 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_SsCjr67aT7ucNhop0:-M_SsCjs5aoezS3pT8id:bnvqlwx) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/include/shim_fs.h#L502)):*
> ```objc
>  * convention has an empty name), separated by `/`, and beginning with `/`.
>  */
> int dentry_abs_path(struct shim_dentry* dent, char** path, size_t* size);
> ```

What is the return value? I think it's missing from the documentation, it only says about setting `*path` on failure.
___
*[LibOS/shim/include/shim_fs.h, line 519 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_SsMAO8HsOdPJBcOJI:-M_SsMAO8HsOdPJBcOJJ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/include/shim_fs.h#L519)):*
> ```objc
>  * mountpoint), separated by `/`. A relative path never begins with `/`.
>  */
> int dentry_rel_path(struct shim_dentry* dent, char** path, size_t* size);
> ```

ditto
___
*[LibOS/shim/src/fs/shim_dcache.c, line 323 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_Ss_ah-N5MCKCq8hVS:-M_Ss_ah-N5MCKCq8hVT:bz6q99r) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L323)):*
> ```C
> }
> 
> static int dentry_path(struct shim_dentry* dent, bool relative, char** pathp, size_t* sizep) {
> ```

Here you use `pathp` and `sizep`, but in `dentry_abs_path` you use `path` and `size`. Please unify.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 340 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_RtHjLCiDUQEkBMlBG:-M_St7f30Fuji4NKM10s:bddxked) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L340)):*
>  Btw, I think not touching `pathp` instead of explicitly setting it to NULL would also be fine (on failures).

No strong opinions on this, but I prefer NULLying it, so the callsites can just always `free()` the result. But if you decide to change it, then please remember to update error handling in all the callsites (some of them don't check the retval and some always call `free`).
___
*[LibOS/shim/src/sys/shim_getcwd.c, line 40 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_Rv3f27_eYecr_vVia:-M_SvIIkERWyrenO9IwM:bopdzw4) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/sys/shim_getcwd.c#L40)):*
> Maybe just wrap all below in `if (ret >= 0)`?

I prefer to not nest successful cases, and that's the convention we use in most of (whole?) our codebase.

But `put_dentry` is indeed missing, so this part should definitely be fixed.


<!-- Sent from Reviewable.io -->

2021-05-12 01:31 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 340 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_RtHjLCiDUQEkBMlBG:-M_TB8O15xzYVJeYxWyA:b8hioi9) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L340)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

>  Btw, I think not touching `pathp` instead of explicitly setting it to NULL would also be fine (on failures).

No strong opinions on this, but I prefer NULLying it, so the callsites can just always `free()` the result. But if you decide to change it, then please remember to update error handling in all the callsites (some of them don't check the retval and some always call `free`).
</blockquote></details>

IMO the better convention is to not touch and let the callers worry. Each caller could then just initialize the variable to NULL and call free unconditionally. Probably personal preference, but we use that convention in rest of the code.
___
*[LibOS/shim/src/sys/shim_getcwd.c, line 40 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_Rv3f27_eYecr_vVia:-M_TBVId9icwq7BLqLhR:b1i9b0l) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/sys/shim_getcwd.c#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Maybe just wrap all below in `if (ret >= 0)`?

I prefer to not nest successful cases, and that's the convention we use in most of (whole?) our codebase.

But `put_dentry` is indeed missing, so this part should definitely be fixed.
</blockquote></details>

I would prefer not to as well, but then duplicating cleanup code is even worse. Maybe good old `goto` is needed?


<!-- Sent from Reviewable.io -->

2021-05-12 07:17 UTC, dimakuv approved these changes
> Reviewed 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 494 at r4](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_L2mhu0EfEgTsFHIhA:-M_UPlRw17sDE0GQ5k-d:b9j9n3q) ([raw file](https://github.com/oscarlab/graphene/blob/04a6a98ffbdb7c6f966d1fcfee6ef5f8e5ed48d6/LibOS/shim/include/shim_fs.h#L494)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done, please review the changes.
</blockquote></details>

Looks good to me!
___
*[LibOS/shim/include/shim_fs.h, line 502 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_SsCjr67aT7ucNhop0:-M_UPo7EDwb7ciYSDjFj:b5ekx9k) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/include/shim_fs.h#L502)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What is the return value? I think it's missing from the documentation, it only says about setting `*path` on failure.
</blockquote></details>

+1 though it's obvious that `0 on success, negative error code otherwise`. But we typically write it, so please add.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 323 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_Ss_ah-N5MCKCq8hVS:-M_UQBGs3zrL244sWXyj:bx51hce) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L323)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Here you use `pathp` and `sizep`, but in `dentry_abs_path` you use `path` and `size`. Please unify.
</blockquote></details>

+1. I prefer without these `p` suffixes.


<!-- Sent from Reviewable.io -->

2021-05-12 07:48 UTC, yamahata approved these changes
> Reviewed 1 of 8 files at r5, 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-05-12 09:13 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: 18 of 22 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[LibOS/shim/include/shim_fs.h, line 502 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_SsCjr67aT7ucNhop0:-M_UkIgQ7bmTD4c-8xXc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/include/shim_fs.h#L502)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 though it's obvious that `0 on success, negative error code otherwise`. But we typically write it, so please add.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 519 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_SsMAO8HsOdPJBcOJI:-M_UkNscCoN7iH5AC5LV:b-nq4bpe) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/include/shim_fs.h#L519)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Described the return value here as well.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 323 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_Ss_ah-N5MCKCq8hVS:-M_Uk_QYBrr5DGM6-JND:b-mnwjbb) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L323)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1. I prefer without these `p` suffixes.
</blockquote></details>

I did it this way because this function already uses `path` as `size` for actual values. I renamed them to `_path` and `_size` - if we already have a convention for such cases, I can change.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 340 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_RtHjLCiDUQEkBMlBG:-M_Um4I51Om_aS4mlCcT:bb6b87a) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L340)):*
OK, I changed the code not to touch the path on failure, and updated the call sites that needed to null-initialize the path.

>These two return paths are so similar, please join them.

This not relevant anymore, but for future reference: how did you want to join? If we're setting two different values, I'm not seeing a good option.

I'm considering something like:
```c
*pathp = (ret == 0 ? path : NULL);
if (sizep)
    *sizep = (ret == 0 ? size : 0);
```

Or:
```c
if (ret == 0) {
    *pathp = path;
    if (sizep)
       *sizep = size;
} else {
    *pathp = NULL;
    if (sizep)
       *sizep = 0;
}
```
Both of these look worse to me than having a separate error path.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 158 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_RtoUnCGT3J8VJL62J:-M_UoxsR0wIBtef2AL1u:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/chroot/fs.c#L158)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please realign.
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/sys/shim_getcwd.c, line 40 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_Rv3f27_eYecr_vVia:-M_UpL4q8DCQYY5qR9BS:bxsrwqm) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/sys/shim_getcwd.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would prefer not to as well, but then duplicating cleanup code is even worse. Maybe good old `goto` is needed?
</blockquote></details>

Changed to use goto.


<!-- Sent from Reviewable.io -->

2021-05-12 10:14 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-05-12 11:04 UTC, boryspoplawski requested changes
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 340 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_RtHjLCiDUQEkBMlBG:-M_VBrcM8FKC6ltQFsTh:bic31oh) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L340)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I changed the code not to touch the path on failure, and updated the call sites that needed to null-initialize the path.

>These two return paths are so similar, please join them.

This not relevant anymore, but for future reference: how did you want to join? If we're setting two different values, I'm not seeing a good option.

I'm considering something like:
```c
*pathp = (ret == 0 ? path : NULL);
if (sizep)
    *sizep = (ret == 0 ? size : 0);
```

Or:
```c
if (ret == 0) {
    *pathp = path;
    if (sizep)
       *sizep = size;
} else {
    *pathp = NULL;
    if (sizep)
       *sizep = 0;
}
```
Both of these look worse to me than having a separate error path.
</blockquote></details>

Generally speaking in other places we do not set return values on errors, because usually it makes no sense (if we had something to return there wouldn't be an error). In such case you could set return values before the goto label and just do cleanup + return value after it.
___
*[LibOS/shim/src/sys/shim_getcwd.c, line 37 at r9](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_VEOpM81h46js5VNi3:-M_VEOpM81h46js5VNi4:b-3rd4n) ([raw file](https://github.com/oscarlab/graphene/blob/a10322fded63f4d7d90704d2b84ad62ba59fc851/LibOS/shim/src/sys/shim_getcwd.c#L37)):*
> ```C
>     unlock(&g_process.fs_lock);
> 
>     char* path;
> ```

Please initialize `path`. We do not touch it on errors now so there is no real problem here, but now that the API does not clean it, it would be better not to worry if it's initialized in later parts of the code.


<!-- Sent from Reviewable.io -->

2021-05-12 11:33 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-12 11:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_dcache.c, line 340 at r8](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_RtHjLCiDUQEkBMlBG:-M_VLDeY9m-8Jpt0HJQs:bqfxfv8) ([raw file](https://github.com/oscarlab/graphene/blob/923e7247bf14087f35548abcddccfac67a9dbd4c/LibOS/shim/src/fs/shim_dcache.c#L340)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Generally speaking in other places we do not set return values on errors, because usually it makes no sense (if we had something to return there wouldn't be an error). In such case you could set return values before the goto label and just do cleanup + return value after it.
</blockquote></details>

Okay. I agree with that reasoning, and it works that way now, but I understood "these paths are similar, join them" as refactoring the code, not completely changing what the error path does :)
___
*[LibOS/shim/src/sys/shim_getcwd.c, line 37 at r9](https://reviewable.io/reviews/oscarlab/graphene/2342#-M_VEOpM81h46js5VNi3:-M_VL-5P2lokRbg0xu3G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a10322fded63f4d7d90704d2b84ad62ba59fc851/LibOS/shim/src/sys/shim_getcwd.c#L37)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please initialize `path`. We do not touch it on errors now so there is no real problem here, but now that the API does not clean it, it would be better not to worry if it's initialized in later parts of the code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-12 11:44 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-12 12:42 UTC, dimakuv approved these changes
> Reviewed 3 of 4 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-12 13:16 UTC, mkow approved these changes
> Reviewed 9 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-05-12 13:21 UTC, dimakuv approved these changes
> Reviewed 1 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-12 13:22 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (`kill11` LTP test failed)

2021-05-12 13:23 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-20.04-apps please (`Cannot contact <jenkins worker>`, looks like Jenkins glitches)

2021-05-12 13:25 UTC, boryspoplawski approved these changes
> Reviewed 9 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2342)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-12 14:04 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04-apps please (Jenkins worker glitches)

2021-05-12 15:13 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04-apps please (Jenkins worker glitches)

2021-05-12 15:34 UTC, merged