Meson: compile LibOS
oscarlab/graphene pull request #2351
Opened 2021-05-05 13:08 UTC by woju

## Description of the changes 

This moves compiling `libsysdb.so` from `Makefile`s to `meson.build` files.

## How to test this PR? 

Build should succeed, and tests should pass. Specifically LibOS tests should be unaffected.

2021-05-06 09:16 UTC, dimakuv requested changes
> Reviewed 30 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" and "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[.ci/lib/config-release.jenkinsfile, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-swaS54IcSiN8oqch:-M_-swaT-LJibdcWjeiU:b-munu0y) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/.ci/lib/config-release.jenkinsfile#L2)):*
> ```
> // env.DEBUG is not set
> env.BUILDTYPE = 'plain'
> ```

Why not release? According to https://mesonbuild.com/Builtin-options.html, `plain` is `debug=false, optimization=0`. We want to have `optimization=3`.
___
*[LibOS/shim/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-vppY0MK72cpJ2Yt4:-M_-vppY0MK72cpJ2Yt5:b-5tm0gz) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/Makefile#L7)):*
> ```Makefile
> .PHONY: all
> all:
> 	$(MAKE) -C src $@
> ```

Why do we keep this file at all? Only for the `graphene-lib` hacky build?
___
*[LibOS/shim/meson.build, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-wMDa83yF-MZKXMkJ:-M_-wMDa83yF-MZKXMkK:b-124q4y) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/meson.build#L33)):*
> ```Meson
> # is required in the LibOS code);
> # not all compilers support mstack-protector-guard, so use stack protector only if supported
> cflags_libos += '-fno-stack-protector'
> ```

You can actually move it under `else` below. This was a hacky way to set a default value to "no stack protecter" and then overwrite it with "use stack protector" if it is supported by GCC (relying on the fact that GCC negates the previous option when it finds a contradictory option).
___
*[LibOS/shim/meson.build, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-wxIM-4yLprYnOdja:-M_-wxIN32BMS6Tiv6Fc:bmpn6yg) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/meson.build#L48)):*
> ```Meson
> #	     $(graphene_lib) $(pal_lib) shim.map arch/$(ARCH)/shim.lds
> #	$(call cmd,ld_so_o)
> # cmd_ld_so_o = ... $(filter-out pal-symbols %.map %.map.template %.lds,$^) -soname $(notdir $@)
> ```

What is this commented out logic?
___
*[LibOS/shim/src/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-xCRD4YgA0MGx_lOT:-M_-xCRD4YgA0MGx_lOU:b5unblr) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/src/Makefile#L5)):*
> ```Makefile
> 
> .PHONY: all
> all: graphene_lib_recurse
> ```

Do we keep this Makefile only because of this graphene-lib ugliness? I have a patch that will remove it from here, I'll submit it soon.
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-v7LF28UIBFNuAq3v:-M_-v7LF28UIBFNuAq3w:b-my6cj5) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/src/vdso/arch/x86_64/meson.build#L24)):*
> ```Meson
> 
> # vdso.so is required to have no relocations. This rule checks it.
> # Use default linker script to retain relocations if exist.
> ```

Do we really all this logic simply to check that the produced vDSO ELF file doesn't have relocations? I vote for removing all this logic and the corresponding `.sh` script, it's just too cumbersome. Maybe just a comment somewhere that "vDSO is not supposed to have relocations" somewhere here is sufficient.
___
*[Scripts/check-no-reloc.sh, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-vmGy4_Y6HqBn9Y2h:-M_-vmGy4_Y6HqBn9Y2i:b8jtekg) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/Scripts/check-no-reloc.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

ditto (delete this file?)
___
*[Scripts/Makefile.rules, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-uXFw9lwZZJqiasDk:-M_-uXFw9lwZZJqiasDl:bhupemj) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/Scripts/Makefile.rules#L139)):*
> ```
> 
> # pal map
> SCRIPTSDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
> ```

Why do you define SCRIPTSDIR here, even though you use it above?


<!-- Sent from Reviewable.io -->

2021-05-06 10:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 27 of 30 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[.ci/lib/config-release.jenkinsfile, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-swaS54IcSiN8oqch:-M_03Dej-8YpWfp9A4an:b2es4ey) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/.ci/lib/config-release.jenkinsfile#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not release? According to https://mesonbuild.com/Builtin-options.html, `plain` is `debug=false, optimization=0`. We want to have `optimization=3`.
</blockquote></details>

No reason, I didn't thought much about this, I can change to `'release'`. Let's see what happens.
___
*[LibOS/shim/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-vppY0MK72cpJ2Yt4:-M_03PPR0ZeE2Qg79yiF:beh8pqr) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/Makefile#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we keep this file at all? Only for the `graphene-lib` hacky build?
</blockquote></details>

Yes, exactly. And that's why I told you I'll be happy if you did something to this lib.
___
*[LibOS/shim/meson.build, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-wMDa83yF-MZKXMkJ:-M_03e3mCxjiXWh1HR1j:b-8jg4ze) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/meson.build#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You can actually move it under `else` below. This was a hacky way to set a default value to "no stack protecter" and then overwrite it with "use stack protector" if it is supported by GCC (relying on the fact that GCC negates the previous option when it finds a contradictory option).
</blockquote></details>

OK. Thanks, I didn't know.
___
*[LibOS/shim/meson.build, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-wxIM-4yLprYnOdja:-M_043oc1PvUK-RSW3HR:b-on9cf5) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/meson.build#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this commented out logic?
</blockquote></details>

This was leftover from rewriting, and I missed it when I was juggling the logic between directories, because there isn't 1:1 relationship between makefiles and mesonfiles.

Removed.
___
*[LibOS/shim/src/Makefile, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-xCRD4YgA0MGx_lOT:-M_04Sg5CWTM7SXKJSDe:b-wjixja) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/src/Makefile#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we keep this Makefile only because of this graphene-lib ugliness? I have a patch that will remove it from here, I'll submit it soon.
</blockquote></details>

I'd be grateful.
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-v7LF28UIBFNuAq3v:-M_04aoJ0sNJGyE9Rs8h:b-wtaw37) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/src/vdso/arch/x86_64/meson.build#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we really all this logic simply to check that the produced vDSO ELF file doesn't have relocations? I vote for removing all this logic and the corresponding `.sh` script, it's just too cumbersome. Maybe just a comment somewhere that "vDSO is not supposed to have relocations" somewhere here is sufficient.
</blockquote></details>

I don't think the comment is sufficient. This file currently has relocations (see failed tests), so this logic is probably needed. @mkow told me that some time ago he also screwed something and this test triggered as it should, so I think we need it in some form.

I could change the check to point to vdso.so proper (and remove libos_vdso_for_reloc_check), because vdso.so also has relocations (you can't see this in jenkins log, you have to reproduce yourself, but it's 100%). Or some other way, IDK, I'm no expert on linkers.
___
*[Scripts/check-no-reloc.sh, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-vmGy4_Y6HqBn9Y2h:-M_06NXI9-EdtFAvTYCt:b2ni7t9) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/Scripts/check-no-reloc.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (delete this file?)
</blockquote></details>

mhm
___
*[Scripts/Makefile.rules, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-uXFw9lwZZJqiasDk:-M_05mwB-78Pa8EMeKK0:b-fymvgj) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/Scripts/Makefile.rules#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you define SCRIPTSDIR here, even though you use it above?
</blockquote></details>

This was supposed to go back at the top, but was misrebased I think. Corrected.


<!-- Sent from Reviewable.io -->

2021-05-06 13:29 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-v7LF28UIBFNuAq3v:-M_0r_PC6fIQ-LcXyl6Q:b8sa2kd) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/src/vdso/arch/x86_64/meson.build#L24)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't think the comment is sufficient. This file currently has relocations (see failed tests), so this logic is probably needed. @mkow told me that some time ago he also screwed something and this test triggered as it should, so I think we need it in some form.

I could change the check to point to vdso.so proper (and remove libos_vdso_for_reloc_check), because vdso.so also has relocations (you can't see this in jenkins log, you have to reproduce yourself, but it's 100%). Or some other way, IDK, I'm no expert on linkers.
</blockquote></details>

OK. Looks very ugly though...


<!-- Sent from Reviewable.io -->

2021-05-07 02:46 UTC, yamahata approved these changes
> Reviewed 26 of 30 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-05-08 00:43 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_8QFZ50Y3LrNSUUnAk:-M_8QFZ50Y3LrNSUUnAl:b-t1nsps) (no related file):*
@woju Is this ready for review? If not, please convert to a draft (seems it's not passing CI).

---


<!-- Sent from Reviewable.io -->

2021-05-10 12:12 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 25 of 30 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_8QFZ50Y3LrNSUUnAk:-M_LBGOX3KQ_JU9jvgOA:b-nbbiah) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@woju Is this ready for review? If not, please convert to a draft (seems it's not passing CI).
</blockquote></details>

Tests fixed, now it's ready for review.

---


<!-- Sent from Reviewable.io -->

2021-05-17 07:39 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 2 unresolved discussions (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_tFn27-JMJA9sfAcQX:-M_tFn27-JMJA9sfAcQY:bmun8q9) (no related file):*
@woju Out of curiosity, how do you decide whether a helper script is written in Shell or Python?

---


<!-- Sent from Reviewable.io -->

2021-05-17 12:21 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_tFn27-JMJA9sfAcQX:-M_uCtIk6NT-v7Vd2xdU:b-w3ix6f) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju Out of curiosity, how do you decide whether a helper script is written in Shell or Python?
</blockquote></details>

Experience and feel? I think I know shell and python well enough to predict how clean and easy the thing would be to write and maintain in which language. Shell is terse (so very readable), but Python has less problems with string manipulation. So most of those are in Python, but check-no-reloc is a good candidate for shell, because in Python this would be `import subprocess`. Also there is a related PR with clang-format, also in shell because that is a single pipeline of `find -exec`.

In context of meson, sometimes there is also a consideration of portability to a certain OS replacement which offers no sh and has different path conventions. But if you're running meson, you already have python, so it's OK to write helpers in python, which has a nice `pathlib` module and `subprocess` works as well. (This is directly comparable to autotools, where `./configure` run on top of `sh`, so you can assume `sh` is always available).

Read more about meson portability:
- https://mesonbuild.com/Use-of-Python.html
- https://mesonbuild.com/FAQ.html#why-is-meson-implemented-in-python-rather-than-programming-language-x
- https://mesonbuild.com/Reference-manual.html#custom_target ("Note: Assuming that command: is executed by a POSIX sh shell is not portable, notably to Windows. Instead, consider using a native: true executable(), or a python script.")

---


<!-- Sent from Reviewable.io -->

2021-05-17 12:33 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_tFn27-JMJA9sfAcQX:-M_uJ9Xf6ceB5p4-LXrD:b-ucfknh) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Experience and feel? I think I know shell and python well enough to predict how clean and easy the thing would be to write and maintain in which language. Shell is terse (so very readable), but Python has less problems with string manipulation. So most of those are in Python, but check-no-reloc is a good candidate for shell, because in Python this would be `import subprocess`. Also there is a related PR with clang-format, also in shell because that is a single pipeline of `find -exec`.

In context of meson, sometimes there is also a consideration of portability to a certain OS replacement which offers no sh and has different path conventions. But if you're running meson, you already have python, so it's OK to write helpers in python, which has a nice `pathlib` module and `subprocess` works as well. (This is directly comparable to autotools, where `./configure` run on top of `sh`, so you can assume `sh` is always available).

Read more about meson portability:
- https://mesonbuild.com/Use-of-Python.html
- https://mesonbuild.com/FAQ.html#why-is-meson-implemented-in-python-rather-than-programming-language-x
- https://mesonbuild.com/Reference-manual.html#custom_target ("Note: Assuming that command: is executed by a POSIX sh shell is not portable, notably to Windows. Instead, consider using a native: true executable(), or a python script.")
</blockquote></details>

Thanks!

---


<!-- Sent from Reviewable.io -->

2021-05-17 22:31 UTC, boryspoplawski requested changes
> Reviewed 22 of 30 files at r1, 3 of 4 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 25 unresolved discussions (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uVpvZ4xwuAmqHJOjy:-M_uVpv_EGBiFazCFeAm:b667wra) (no related file):*
I would drop that `[*]` from commit message, IMO if you dont add a prefix, it can be assumed implicitly that it's about the repo as general/whole.
(not blocking, just personal opinion)

---
___
*[meson.build, line 19 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_ulkcDEspHcYasDJTP:-M_ulkcDEspHcYasDJTQ:beimwm8) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/meson.build#L19)):*
> ```Meson
> 
>     default_options: [
>         'c_std=c11',
> ```

Please add `-Wall` and `-Wmissing-prototypes`.
___
*[meson.build, line 19 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_umMLz2642nMEOoqN_:-M_umMM-AjlDmZcjGjUO:b3129ff) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/meson.build#L19)):*
> ```Meson
> 
>     default_options: [
>         'c_std=c11',
> ```

I would also add:
- `-Wextra` (previously we added that in LibOS and Pal/host, but not in general Pal),
- `-Werror` (previously it was hidden begind `WERROR=1` cmdline arg, I would make it default)
___
*[LibOS/shim/meson.build, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uXhqSDKBug1Z3x4EQ:-M_uXhqSDKBug1Z3x4ER:b6m5ayz) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L3)):*
> ```Meson
> cflags_libos = [
>     '-fPIC',
>     '-fmerge-all-constants',
> ```

Why do we need this? If we have two const arrays with same content, this would probably be a bug in graphene.
___
*[LibOS/shim/meson.build, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_udWDi33hdCp9ZM_oo:-M_udWDi33hdCp9ZM_op:b-ep1drn) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L4)):*
> ```Meson
>     '-fPIC',
>     '-fmerge-all-constants',
>     '-fno-builtin',
> ```

Ideally we would want to remove this option, but that would require checking all standard functions conform to their interfaces and requirements (which historically was not true).
Could you add a TODO/github issue about this?
___
*[LibOS/shim/meson.build, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_unU43ECjx_bIVn-Ax:-M_unU44CGIqOOiww_Gx:b-3v0rj) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L6)):*
> ```Meson
>     '-fno-builtin',
> 
>     '-Werror=implicit-function-declaration',
> ```

If we add global `Werror`, remove this.
___
*[LibOS/shim/meson.build, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_unIajDgXROPcCCD3U:-M_unIajDgXROPcCCD3V:b-y0ixgq) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L7)):*
> ```Meson
> 
>     '-Werror=implicit-function-declaration',
>     '-Wextra',
> ```

Imo should be global default (see the comment there).
___
*[LibOS/shim/meson.build, line 9 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uoyCJ8LLZyPt0hcZC:-M_uoyCJ8LLZyPt0hcZD:bwxdu5m) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L9)):*
> ```Meson
>     '-Wextra',
>     '-Winline',
>     '-Wno-inline',
> ```

really...
Please remove this line (just leave `'-Winline`).
___
*[LibOS/shim/meson.build, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vVF9t4BOPJJo6tidI:-M_vVF9u3JZavLyIhejb:b-wh1nv4) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L17)):*
> ```Meson
> 
> cflags_libos += cc.get_supported_arguments(
>     '-Wtrampolines',
> ```

I would move that to global flags.
___
*[LibOS/shim/include/meson.build, line 2 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vgroC7qQkJGigYtiO:-M_vgroE1vZBmnVlxQGu:b-noe76e) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/include/meson.build#L2)):*
> ```Meson
> # don't put this in include_directories for now, we need this for assembly-only custom_target
> includes_libos = [
> ```

Why is this list maintained here in `include` directory, not in `src`?
I guess it all boils down to generated_offsets being handled in `include` directory. Why is it done this way?
___
*[LibOS/shim/include/meson.build, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vxB1BEZsWoLr3asIv:-M_vxB1BEZsWoLr3asIw:b-y7hq15) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/include/meson.build#L15)):*
> ```Meson
> includes_libos_i = []
> foreach i : includes_libos
>     includes_libos_i += '-I@0@'.format(join_paths(meson.current_source_dir(), i))
> ```

Hmm, is there no way to iterate the output of `include_directories`? (I couldn't find anything about that in meson reference manual)
___
*[LibOS/shim/src/meson.build, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vztuW7IxQBXvF1Mn_:-M_vztuW7IxQBXvF1Mna:bkl9dx6) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/meson.build#L27)):*
> ```Meson
> endif
> 
> subdir('arch')
> ```

I don't like this. See the comment in `bookkeep/meson.build` + now we need to rely on this specific order of "define libos_sources list" -> "include subdirectories" -> "define target".
___
*[LibOS/shim/src/meson.build, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_w0IIR-6O457q7cpuw:-M_w0IIR-6O457q7cpux:b-9lkurz) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/meson.build#L42)):*
> ```Meson
>     c_args: cflags_libos,
>     link_args: [
>         '-Wl,-shared',
> ```

This is weird: `-Wl` is a compiler specific prefix to indicate that the flags is to be passed to the linker. I would expect meson to deal with this, but looking at couple of examples and reference seems that this is the way. Upstream bug or am I missing something?
___
*[LibOS/shim/src/bookkeep/meson.build, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vydPzEzFa_7jvRJXf:-M_vydPzEzFa_7jvRJXg:byef5wj) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/bookkeep/meson.build#L1)):*
> ```Meson
> libos_sources += files(
> ```

Why this split of `meson.build`? This files are (and must be) handled in the very same way as files directly in `src` and this directory layout is semantically equivalent to naming these files `shim_bookkeep_handle.c` etc, so I see no reason for this split.
I.e. why cannot we just add these files directly in `src/meson.build`?
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 8 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_w7ctk2w84ULpKUwlp:-M_w7ctk2w84ULpKUwlq:b-cnzqo0) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/vdso/arch/x86_64/meson.build#L8)):*
> ```Meson
>     c_args: cflags_libos,
>     link_args: [
>         '-nostdlib',
> ```

Missing `-Wl`?
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_w9HZ-3B8l_IiJ7_En:-M_w9HZ-3B8l_IiJ7_Eo:b-h63yu) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/vdso/arch/x86_64/meson.build#L10)):*
> ```Meson
>         '-nostdlib',
>         '-Wl,-T@0@'.format(join_paths(meson.current_source_dir(), 'vdso.lds')),
>         '-Wl [...]

2021-05-18 12:38 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 24 of 30 files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uVpvZ4xwuAmqHJOjy:-M_zPDSh-Bg4Ev9cp61_:b56762o) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would drop that `[*]` from commit message, IMO if you dont add a prefix, it can be assumed implicitly that it's about the repo as general/whole.
(not blocking, just personal opinion)
</blockquote></details>

@mkow? I'm not versed well enough on our commit style.

---
___
*[meson.build, line 19 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_ulkcDEspHcYasDJTP:-M_zFIfNBugnN26sX8Ur:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/meson.build#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add `-Wall` and `-Wmissing-prototypes`.
</blockquote></details>

Done.
___
*[meson.build, line 19 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_umMLz2642nMEOoqN_:-M_zG6Un4-pQgpImryEL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/meson.build#L19)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would also add:
- `-Wextra` (previously we added that in LibOS and Pal/host, but not in general Pal),
- `-Werror` (previously it was hidden begind `WERROR=1` cmdline arg, I would make it default)
</blockquote></details>

Done.
___
*[LibOS/shim/meson.build, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uXhqSDKBug1Z3x4EQ:-M_zG8HS6IXdYhGCqiHb:bovdj5e) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do we need this? If we have two const arrays with same content, this would probably be a bug in graphene.
</blockquote></details>

IDK, this was in Makefile, so I moved it here.
___
*[LibOS/shim/meson.build, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_udWDi33hdCp9ZM_oo:-M_zGm4ZDNG7gHdclJfr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ideally we would want to remove this option, but that would require checking all standard functions conform to their interfaces and requirements (which historically was not true).
Could you add a TODO/github issue about this?
</blockquote></details>

Done.
___
*[LibOS/shim/meson.build, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_unU43ECjx_bIVn-Ax:-M_zGn2JD-FSIFO4Zj-7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L6)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If we add global `Werror`, remove this.
</blockquote></details>

Done.
___
*[LibOS/shim/meson.build, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_unIajDgXROPcCCD3U:-M_zGnSN8xfFCmZTSbI4:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Imo should be global default (see the comment there).
</blockquote></details>

Done.
___
*[LibOS/shim/meson.build, line 9 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uoyCJ8LLZyPt0hcZC:-M_zGo-ECoBRuUkFvNj0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L9)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

really...
Please remove this line (just leave `'-Winline`).
</blockquote></details>

Done.
___
*[LibOS/shim/meson.build, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vVF9t4BOPJJo6tidI:-M_zHmIz1hEdeCrkF7iM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would move that to global flags.
</blockquote></details>

Done.
___
*[LibOS/shim/include/meson.build, line 2 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vgroC7qQkJGigYtiO:-M_zPPP280vKAhyR57PC:bwmbw9f) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/include/meson.build#L2)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why is this list maintained here in `include` directory, not in `src`?
I guess it all boils down to generated_offsets being handled in `include` directory. Why is it done this way?
</blockquote></details>

The same reason as in other 
___
*[LibOS/shim/include/meson.build, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vxB1BEZsWoLr3asIv:-M_zI6Vp5Kj0_8eBUzMR:b-xqqkt) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/include/meson.build#L15)):*
https://mesonbuild.com/Reference-manual.html#include_directories:
> Returns an opaque object

The problem with this one is meson treats this object slightly differently depending on context. Usually (like in `executable()`, `shared_library()` etc.) `include_directories('.')` means two directories: `meson.current_source_dir()` and `meson.current_build_dir()` (builddir tree is a mirror of source dir). But in some edge cases it means only source dir part (the only place I found so far is compiler checks, like `cc.has_argument()`).
___
*[LibOS/shim/src/meson.build, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vztuW7IxQBXvF1Mn_:-M_zIYJ4Bh4KoRkTCvV3:b-uyqaxk) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/meson.build#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this. See the comment in `bookkeep/meson.build` + now we need to rely on this specific order of "define libos_sources list" -> "include subdirectories" -> "define target".
</blockquote></details>

Yes, that's the way. Meson is "almost" Turing complete, but key things are deliberately kept not-Turing-complete. One key difference from make is that there is no postponed expansion (i.e. everything is `:=`-assigned) and all variables are immutable. Another is that you can't visit a particular `meson.build` twice.

This order makes things simpler in terms of "where is a definition of some variable". In Make you can't generally reason about contents of variables.
___
*[LibOS/shim/src/meson.build, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_w0IIR-6O457q7cpuw:-M_zBAL2Bht5YnG-wtEj:b-pjo4q5) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/meson.build#L42)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is weird: `-Wl` is a compiler specific prefix to indicate that the flags is to be passed to the linker. I would expect meson to deal with this, but looking at couple of examples and reference seems  [...]

2021-05-19 00:12 UTC, boryspoplawski requested changes
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-Ma0h9QeDMZ4bjTbqP-x:b55n2) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
> ```Meson
>     default_options: [
>         'c_std=c11',
>         'warning_level=2',
> ```

Where can I find any documentation about what this `2` means? `https://mesonbuild.com/Builtin-options.html` doesnt say anything...
I just found that it probably means `-Wall` + `-Wextra`, but that was some random GH issue...
___
*[meson.build, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0inYM4ZeZRhB-t4No:-Ma0inYM4ZeZRhB-t4Np:b-sk2iee) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L44)):*
> ```Meson
> 
> add_project_arguments(
>     '-Wmissing-prototypes',
> ```

What are the rules: what should go into `default_options` of `project` and what here?
___
*[meson.build, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0iz4F5FxaXYsERBwA:-Ma0iz4GA-_3LGR3ClUs:b-vn9vxk) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L63)):*
> ```Meson
> 
> # not all compilers support mstack-protector-guard, so use stack protector only if supported
> cflags_stack_protector = [
> ```

Why did you move it here? IMO it should be specified on each part separately (LibOS, PAL trusted, PAL untrusted).
___
*[LibOS/shim/meson.build, line 33 at r2](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0kSAp3sVgsoEYThEW:-Ma0kSAp3sVgsoEYThEX:bq0if2i) ([raw file](https://github.com/oscarlab/graphene/blob/94921984316762440e9ebb1fab62783f00edc635/LibOS/shim/meson.build#L33)):*
> ```Meson
> # is required in the LibOS code);
> # not all compilers support mstack-protector-guard, so use stack protector only if supported
> cflags_libos_stack_protector = [
> ```

Why moved to globals?
___
*[LibOS/shim/meson.build, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uXhqSDKBug1Z3x4EQ:-Ma0jEgDBWPWfqIc123q:bmt1wvm) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L3)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK, this was in Makefile, so I moved it here.
</blockquote></details>

Then please remove, tho it might be a good exercise to diff the binaries with and without this option. 
___
*[LibOS/shim/meson.build, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_udWDi33hdCp9ZM_oo:-Ma0jSYyB3ljxZvoquHN:b-k36dac) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not about APIs themselves, but whether their implementations are matching the APIs. Please update the comment accordingly. Maybe `TODO: check whether all standard functions implemented in Graphene match their APIs and remove this`?
___
*[LibOS/shim/meson.build, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vVF9t4BOPJJo6tidI:-Ma0kGwb99Z1Em2EWR1g:bwjc8e3) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L17)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

...and since it's in globals, remove it from here.
___
*[LibOS/shim/include/meson.build, line 15 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vxB1BEZsWoLr3asIv:-Ma0koBoCRduUzeOm5GH:b-qdzu81) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/include/meson.build#L15)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

https://mesonbuild.com/Reference-manual.html#include_directories:
> Returns an opaque object

The problem with this one is meson treats this object slightly differently depending on context. Usually (like in `executable()`, `shared_library()` etc.) `include_directories('.')` means two directories: `meson.current_source_dir()` and `meson.current_build_dir()` (builddir tree is a mirror of source dir). But in some edge cases it means only source dir part (the only place I found so far is compiler checks, like `cc.has_argument()`).
</blockquote></details>

Thanks for explanation, makes sense.
___
*[LibOS/shim/src/meson.build, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vztuW7IxQBXvF1Mn_:-Ma0l-AF29G2sh_jo_kN:buuq76v) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/meson.build#L27)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, that's the way. Meson is "almost" Turing complete, but key things are deliberately kept not-Turing-complete. One key difference from make is that there is no postponed expansion (i.e. everything is `:=`-assigned) and all variables are immutable. Another is that you can't visit a particular `meson.build` twice.

This order makes things simpler in terms of "where is a definition of some variable". In Make you can't generally reason about contents of variables.
</blockquote></details>

Still, if somebody touches this file in a month, they will have no idea the ordering here is the key. Move the target above `subdir` and things are broken. Just sounds like a bad practice to include/execute subdirectory in the middle which are not independent, it's really hard to track what's happening where, since each `subdir` modifies `libos_sources`.
___
*[LibOS/shim/src/meson.build, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_w0IIR-6O457q7cpuw:-Ma0tFc4EewxVQ5etxKp:b-c4cl84) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/meson.build#L42)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`link_args` is whatever you pass to gcc frontend (not linker) for the link stage (as opposed to `c_args` which is passed always), so `-Wl` is appropriate.

The problem is that some of those arguments may depend on something else which is generated (for example: in PAL the version script is generated). So there are two different sets of arguments, `c_args` and `link_args`, and if `c_args` didn't change, as an optimisation meson won't recompile all `.o` files when `link_args` did change. Without this distinction you'd have to recompile all objects.
</blockquote></details>

Ok, got it, we meson uses `gcc` as frontend to `ld`.
___
*[LibOS/shim/src/bookkeep/meson.build, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vydPzEzFa_7jvRJXf:-Ma0t_aD2Xs7SijZbGnm:bqw6fne) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/bookkeep/meson.build#L1)):*
But you do not handle these files here, you merely append them to a list. So if I want to know "where the hell is the meson.build that touches this file", I still need to look in upper directory (`LibOS/shim/src`), which kind of renders this whole argument invalid.
Agree that renaming directories would be easier, but ease of maintaining the buildsystem is more important.

> This is a convention that all files are handled by meson.build as close as where they are, optimally in the same directory. 

If you had rules to build [...]

2021-05-19 00:17 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[LibOS/shim/meson.build, line 8 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0ypVYEE2dobyPyl4V:-Ma0ypVYEE2dobyPyl4W:bct5wtr) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/LibOS/shim/meson.build#L8)):*
> ```Meson
>     '-fno-builtin',
> 
>     '-Winline',
> ```

This one needs to be removed too, unfortunately some of the `static inline` defined in headers are not inlined.


<!-- Sent from Reviewable.io -->

2021-05-19 17:42 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 14 of 32 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @yamahata)

___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-Ma4hlFTDOdGsnpnbHRe:b-k5pthm) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Where can I find any documentation about what this `2` means? `https://mesonbuild.com/Builtin-options.html` doesnt say anything...
I just found that it probably means `-Wall` + `-Wextra`, but that was some random GH issue...
</blockquote></details>

There is no doc for this AFAIK, because this depends on the compiler (for example `icc` has no `-Wpedantic`.
___
*[meson.build, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0inYM4ZeZRhB-t4No:-Ma2sk_7ExKMo-ZyRi5G:b-tfj0o6) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L44)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What are the rules: what should go into `default_options` of `project` and what here?
</blockquote></details>

I'm not exactly sure, I don't have a feel for this one, mainly because of my limited knowledge about C compilers.

- `add_project_arguments()` cannot be undone by user (without editing `meson.build` files), so it feels appropriate for things like `-D`.
- `c_args` in `default_options` will be overridden if user runs `meson build -Dc_args=...`, so IDK, maybe warnings should be there?
- There is also a third interface, you can run `CFLAGS=... meson build` and the flags from `CFLAGS` envvar will be appended to `c_args`.
- Some of the options are abstracted under generic meson options, like `c_std`, `werror` or `warning_level`. Some of those
___
*[meson.build, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0iz4F5FxaXYsERBwA:-Ma2umBj3vIc1FxMCr-x:b-kysyyq) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why did you move it here? IMO it should be specified on each part separately (LibOS, PAL trusted, PAL untrusted).
</blockquote></details>

Note that this is only variable assignment based on feature detection against cc. A specific target may or may not add this to it's args. This logic (along with feature detection) was duplicated several times in different makefiles, so I moved it here.
___
*[LibOS/shim/meson.build, line 33 at r2](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0kSAp3sVgsoEYThEW:-Ma2rSxb3Iqe68ctSkgU:b-4ejrf4) ([raw file](https://github.com/oscarlab/graphene/blob/94921984316762440e9ebb1fab62783f00edc635/LibOS/shim/meson.build#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why moved to globals?
</blockquote></details>

Because the same logic was copy-pasted several times in Pal/* makefiles. This commit was cherry-picked from Pal/Linux PR.
___
*[LibOS/shim/meson.build, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uXhqSDKBug1Z3x4EQ:-Ma4gWp_0BVWMsmcS6qR:b-eqsevp) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L3)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then please remove, tho it might be a good exercise to diff the binaries with and without this option. 
</blockquote></details>

Removed. Also `-fPIC`, because it is added by meson.
___
*[LibOS/shim/meson.build, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_udWDi33hdCp9ZM_oo:-Ma4ggMh6seuYA_UFJqI:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L4)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not about APIs themselves, but whether their implementations are matching the APIs. Please update the comment accordingly. Maybe `TODO: check whether all standard functions implemented in Graphene match their APIs and remove this`?
</blockquote></details>

Done.
___
*[LibOS/shim/meson.build, line 17 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vVF9t4BOPJJo6tidI:-Ma4gkOUC6kBrFcHXmee:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/meson.build#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

...and since it's in globals, remove it from here.
</blockquote></details>

Done.
___
*[LibOS/shim/meson.build, line 8 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0ypVYEE2dobyPyl4V:-Ma4ghjv2aRTWOE2-qje:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/LibOS/shim/meson.build#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This one needs to be removed too, unfortunately some of the `static inline` defined in headers are not inlined.
</blockquote></details>

Done.
___
*[LibOS/shim/src/meson.build, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vztuW7IxQBXvF1Mn_:-Ma4gp27D_ZAXnbXnU9w:b-k8xdnk) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/meson.build#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Still, if somebody touches this file in a month, they will have no idea the ordering here is the key. Move the target above `subdir` and things are broken. Just sounds like a bad practice to include/execute subdirectory in the middle which are not independent, it's really hard to track what's happening where, since each `subdir` modifies `libos_sources`.
</blockquote></details>

OK, the tree was flattened.
___
*[LibOS/shim/src/bookkeep/meson.build, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_vydPzEzFa_7jvRJXf:-Ma4guUo64hDFAZBxAHX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/bookkeep/meson.build#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But you do not handle these files here, you merely append them to a list. So if I want to know "where the hell is the meson.build that touches this file", I still need to look in upper directory (`LibOS/shim/src`), which kind of renders this whole argument invalid.
Agree that renaming directories would be easier, but ease of maintaining the buildsystem is more important.

> This is a convention that all files are handled by meson.build as close as where they are, optimally in the same directory. 

If you had rules to build these files here that would be true, but in this case it's invalid (see the explanation above).
</blockquote></details>

Done.
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_w9oZf5sd7B2SD0-a7:-Ma4gyKyCYxfAD5n2Znd:b54jibb) ([raw file](https://github.com/oscarlab/graphene/blob/09ad416f6d8f68346f532c0717172117a4105b22/LibOS/shim/src/vdso/arch/x86_64/meson.build#L14)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not sure about `build-id` and `hash-style`, I don't see a reason for them to be needed.
</blockquote></details>

I [...]

2021-05-19 18:20 UTC, boryspoplawski requested changes
> Reviewed 17 of 18 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow and @woju)

___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-Ma4ibw79_Jh4XFj4B5i:b-losu45) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

There is no doc for this AFAIK, because this depends on the compiler (for example `icc` has no `-Wpedantic`.
</blockquote></details>

I don't like this: currently we have no idea what flags we have enabled and way to notice when/if they change.
Couldn't we use `Wall` etc, directly (and probably silence meson warnings about that)?
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 36 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4pWU7-c411unTwrR2:-Ma4pWU84rcyBntsT8LE:bu3800z) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/LibOS/shim/src/vdso/arch/x86_64/meson.build#L36)):*
> ```Meson
> )
> 
> # vdso.so is required to have no relocations. This rule checks it.
> ```

NP: it also copies the file to the destination, not only checks.
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-Ma4qNVz7J1ZFDSczCJP:bd5tg5i) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
> ```Meson
>     'meson-clang-format.sh',
> ]
>     set_variable('@0@_prog'.format(script.split('.')[0].underscorify()),
> ```

I don't like this, the names are not greppable anymore (i.e. if I grep `check_no_reloc_prog` I'll find nothing).


<!-- Sent from Reviewable.io -->

2021-05-20 11:18 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-Ma8UXkDCwUYJWOAXJ0k:b-vd1ceg) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this: currently we have no idea what flags we have enabled and way to notice when/if they change.
Couldn't we use `Wall` etc, directly (and probably silence meson warnings about that)?
</blockquote></details>

I don't know a way to silence this, and this is probably on purpose as `-Wall` may not be portable to certain other compilers.
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 36 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4pWU7-c411unTwrR2:-Ma8U2z004QRKlIGG8f4:b56lb60) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/LibOS/shim/src/vdso/arch/x86_64/meson.build#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: it also copies the file to the destination, not only checks.
</blockquote></details>

Yes, so how this should be? Update comment and/or prog name?
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-Ma8UCpU1TR1FZpCicOY:bgcoc60) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like this, the names are not greppable anymore (i.e. if I grep `check_no_reloc_prog` I'll find nothing).
</blockquote></details>

Yeah, this `_prog` is a convention. Would you like me to write this into coding style guide?


<!-- Sent from Reviewable.io -->

2021-05-20 13:09 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @pwmarcz, @woju, and @yamahata)

___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-Ma8nXku8BUl4K-COS93:b-jch5ld) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't know a way to silence this, and this is probably on purpose as `-Wall` may not be portable to certain other compilers.
</blockquote></details>

I can personally live with this warning, especially since it's supported by both gcc and clang.
@dimakuv @mkow @pwmarcz @yamahata What would you say?
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 36 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4pWU7-c411unTwrR2:-Ma8nvXq5A8_3OWyFahE:bykxprh) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/LibOS/shim/src/vdso/arch/x86_64/meson.build#L36)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, so how this should be? Update comment and/or prog name?
</blockquote></details>

Just the comment.
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-Ma8oK7q7jehNzLkkwc4:boqzf0g) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yeah, this `_prog` is a convention. Would you like me to write this into coding style guide?
</blockquote></details>

But there is also a change `-` -> `_`. I (as a developer) just want to be able to find what a given thing does when I need to. Maybe there is some magic messon command `meson magic check_no_reloc_prog` which would tell me where the variable is defined? That would both solve my issue and allow the current version to stay.


<!-- Sent from Reviewable.io -->

2021-05-20 14:21 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 36 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4pWU7-c411unTwrR2:-Ma95WBFBdBl5uHUSZaD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/LibOS/shim/src/vdso/arch/x86_64/meson.build#L36)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Just the comment.
</blockquote></details>

Done.
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-Ma97WAR9ljg2yB8x5tw:bw6d1ce) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But there is also a change `-` -> `_`. I (as a developer) just want to be able to find what a given thing does when I need to. Maybe there is some magic messon command `meson magic check_no_reloc_prog` which would tell me where the variable is defined? That would both solve my issue and allow the current version to stay.
</blockquote></details>

```
% meson introspect -i build --targets | jq -r 'map(select(.name == "vdso.so"))[0].target_sources[0].compiler[0]'
/home/woju/src/graphene/Scripts/check-no-reloc.sh
```

`meson introspect --targets` lists all toplevel targets (everything that has target name; all `executable()`s, `shared_library()`ies, and `custom_target()`s will be there, but individual `.o`bjects will not), together with compiler commands already expanded. Is this sufficient for your use case?


<!-- Sent from Reviewable.io -->

2021-05-20 14:37 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)

___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-Ma9AfhQ1cQ0VmgkTAuY:bwhz7bv) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```
% meson introspect -i build --targets | jq -r 'map(select(.name == "vdso.so"))[0].target_sources[0].compiler[0]'
/home/woju/src/graphene/Scripts/check-no-reloc.sh
```

`meson introspect --targets` lists all toplevel targets (everything that has target name; all `executable()`s, `shared_library()`ies, and `custom_target()`s will be there, but individual `.o`bjects will not), together with compiler commands already expanded. Is this sufficient for your use case?
</blockquote></details>

How on earth am I supposed to get that from `check_no_reloc_prog`?

Update: ok, you need to search for the target that the command is used inside, not the command itself. Well, compared to `git grep check-no-reloc.sh` that sounds rather cumbersome...

summon @dimakuv @mkow 

We live with worse things, so if rest is ok with this, we could move on.


<!-- Sent from Reviewable.io -->

2021-05-20 17:30 UTC, woju reviewed
Rebased on top of `common/`.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351#-:-Ma9p1pFE_HP8yw1DYRz:ba0cclw)* status: 27 of 32 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-05-20 19:48 UTC, boryspoplawski reviewed
> Reviewed 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, @pwmarcz, and @yamahata)



<!-- Sent from Reviewable.io -->

2021-05-21 07:04 UTC, dimakuv requested changes
> Reviewed 7 of 18 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 3 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow, @pwmarcz, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uVpvZ4xwuAmqHJOjy:-MaCbkWx-mPyeCzAEKyh:bbdqrxb) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@mkow? I'm not versed well enough on our commit style.
</blockquote></details>

I would either:
- drop `[*]` as Borys suggests, or
- replace with `[Scripts]` or `[Build]`

---
___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-MaCcE_W96Xv5atdjgZy:bifi5w3) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I can personally live with this warning, especially since it's supported by both gcc and clang.
@dimakuv @mkow @pwmarcz @yamahata What would you say?
</blockquote></details>

I agree with Borys, I would very much prefer explicit `-Wall -Wextra`
___
*[meson.build, line 47 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCctnP46Xnsdu5UV88:-MaCctnP46Xnsdu5UV89:b-zg2dzh) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L47)):*
> ```Meson
> 
>     cc.get_supported_arguments(
>         '-Wtrampoline',
> ```

What about `-Wnull-dereference`? It should be for all components, not only LibOS (as you have now). I see that you disabled it and added a comment, is this still relevant? If yes, you can just move it here (the comment and the disabled option).
___
*[meson.build, line 62 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCiUgV6PAiJo61wp_g:-MaCdpl7Ch3lnbgYDgUz:b-eew4is) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L62)):*
> ```Meson
> #
> 
> # not all compilers support mstack-protector-guard, so use stack protector only if supported
> ```

Could you add a quick comment about this Graphene-custom stack protector? Smth like `Graphene-custom stack protector uses the canary stored in the TCB (same for both in LibOS and PAL) at offset 0x8`.
___
*[meson.build, line 63 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCdPyg8V0C4i-NrW_8:-MaCdPyg8V0C4i-NrW_9:b-4qdy6a) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L63)):*
> ```Meson
> 
> # not all compilers support mstack-protector-guard, so use stack protector only if supported
> cflags_stack_protector = [
> ```

By the way, I just realized that we have two stack protector flavors:
- Our custom one (using `%gs + 8`), used for LibOS and trusted PALs, and
- GCC standard one, used for untrusted SGX PAL

And then of course we also have a third option: no stack protector at all.

So we should probably have a better name here? Like `cflags_graphene_stack_protector` or `cflags_custom_stack_protector`?
___
*[LibOS/shim/meson.build, line 7 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaChqn92h7GG0IHvZ-d:-MaChqn92h7GG0IHvZ-e:b-s8hd8j) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/LibOS/shim/meson.build#L7)):*
> ```Meson
> 
>     '-Wstrict-prototypes',
>     '-Wwrite-strings',
> ```

Actually, these two should be moved to a common meson script. These should be also enabled in PALs. But I see they aren't currently, so I'm not blocking.
___
*[LibOS/shim/meson.build, line 15 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCi1MV7ehzo9ih_8DE:-MaCi1MV7ehzo9ih_8DF:bsai3g9) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/LibOS/shim/meson.build#L15)):*
> ```Meson
>     # TODO: this option was broken in Makefile, and some problems slipped through;
>     # need to debug before reenabling
> #   '-Wnull-dereference',
> ```

As mentioned in my other comment, I'd move it to globals.
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 14 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCg2vZ9SEWTBtOQayM:-MaCg2vZ9SEWTBtOQayN:bnxrqe8) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/LibOS/shim/src/vdso/arch/x86_64/meson.build#L14)):*
> ```Meson
>         '-fno-builtin',
> 
>         '-Wnull-dereference',
> ```

Why is this not surrounded with `cc.get_supported_arguments`?
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-MaCfUAUB44ouP-9AMEa:bmkacty) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How on earth am I supposed to get that from `check_no_reloc_prog`?

Update: ok, you need to search for the target that the command is used inside, not the command itself. Well, compared to `git grep check-no-reloc.sh` that sounds rather cumbersome...

summon @dimakuv @mkow 

We live with worse things, so if rest is ok with this, we could move on.
</blockquote></details>

I can live with this. You just need to memorize once that Graphene build "underscorifies" targets into commands. Also, there will be like 5-6 of these helper commands/scripts, I don't think we'll need grep for this.


<!-- Sent from Reviewable.io -->

2021-05-21 12:17 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uVpvZ4xwuAmqHJOjy:-MaDoz9e1MYEuFFTUlbo:bbyybos) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would either:
- drop `[*]` as Borys suggests, or
- replace with `[Scripts]` or `[Build]`
</blockquote></details>

OK, dropped and rebased.

---
___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-MaDo8brAsFaMiqlEKM7:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with Borys, I would very much prefer explicit `-Wall -Wextra`
</blockquote></details>

OK.
___
*[meson.build, line 47 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCctnP46Xnsdu5UV88:-MaDh-ms50Jvy9WhglAd:b-vv7qb0) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about `-Wnull-dereference`? It should be for all components, not only LibOS (as you have now). I see that you disabled it and added a comment, is this still relevant? If yes, you can just move it here (the comment and the disabled option).
</blockquote></details>

Yes, this is still relevant. This triggers with `-O3`, at least on GCC 9.3 (Ubuntu 20.04):
```
In file included from ../LibOS/shim/src/bookkeep/shim_vma.c:17:
../LibOS/shim/src/bookkeep/shim_vma.c: In function ‘rs_vma’:
../LibOS/shim/include/shim_checkpoint.h:192:12: error: potential null pointer dereference [-Werror=null-dereference]
  192 |         tmp->cp_val;                                 \
      |         ~~~^~~~~~~~
../LibOS/shim/src/bookkeep/shim_vma.c:1279:32: note: in expansion of macro ‘GET_CP_ENTRY’
 1279 |     void* need_mapped = (void*)GET_CP_ENTRY(ADDR);
      |                                ^~~~~~~~~~~~
../LibOS/shim/include/shim_checkpoint.h:190:19: error: null pointer dereference [-Werror=null-dereference]
  190 |         while (tmp->cp_type != CP_##type)            \
      |                ~~~^~~~~~~~~
../LibOS/shim/src/bookkeep/shim_vma.c:1279:32: note: in expansion of macro ‘GET_CP_ENTRY’
 1279 |     void* need_mapped = (void*)GET_CP_ENTRY(ADDR);
      |                                ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```

So I moved it here without comment, and left the edited comment in LibOS near `-Wno-null-dereference`.
___
*[meson.build, line 62 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCiUgV6PAiJo61wp_g:-MaDmtI19aP0vPj0xnTZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a quick comment about this Graphene-custom stack protector? Smth like `Graphene-custom stack protector uses the canary stored in the TCB (same for both in LibOS and PAL) at offset 0x8`.
</blockquote></details>

Done.
___
*[meson.build, line 63 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCdPyg8V0C4i-NrW_8:-MaDllTt-eFM0MkTFbW_:b-t2dujz) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, I just realized that we have two stack protector flavors:
- Our custom one (using `%gs + 8`), used for LibOS and trusted PALs, and
- GCC standard one, used for untrusted SGX PAL

And then of course we also have a third option: no stack protector at all.

So we should probably have a better name here? Like `cflags_graphene_stack_protector` or `cflags_custom_stack_protector`?
</blockquote></details>

I have no idea, I don't know what a stack protector is. Sure I can rename to whatever the consensus says. @mkow @boryspoplawski 
___
*[LibOS/shim/meson.build, line 7 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaChqn92h7GG0IHvZ-d:-MaDm5_yE3FynTomXvH0:b-khh40f) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/LibOS/shim/meson.build#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, these two should be moved to a common meson script. These should be also enabled in PALs. But I see they aren't currently, so I'm not blocking.
</blockquote></details>

OK, moved to global, and if I'd see them as errors when rewriting PALs, I'll put `-Wno-*` in the respective PAL.
___
*[LibOS/shim/meson.build, line 15 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCi1MV7ehzo9ih_8DE:-MaDoR_V5gbejLy6nvBP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/LibOS/shim/meson.build#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As mentioned in my other comment, I'd move it to globals.
</blockquote></details>

Done.
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 14 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCg2vZ9SEWTBtOQayM:-MaDgOMwDQ6xpVBnngLO:b628yo) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/LibOS/shim/src/vdso/arch/x86_64/meson.build#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this not surrounded with `cc.get_supported_arguments`?
</blockquote></details>

This was a mistake. Thanks for catching. Now it is removed, because we enable this globally (see other discussion).
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-MaDoYNUEovlx0dMqUOm:bwf52kx) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I can live with this. You just need to memorize once that Graphene build "underscorifies" targets into commands. Also, there will be like 5-6 of these helper commands/scripts, I don't think we'll need grep for this.
</blockquote></details>

OK, so leaving as is.


<!-- Sent from Reviewable.io -->

2021-05-21 12:24 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @mkow, @pwmarcz, and @yamahata)

___
*[meson.build, line 47 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCctnP46Xnsdu5UV88:-MaDs0DD-_aaAszrSd2s:brujztc) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L47)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, this is still relevant. This triggers with `-O3`, at least on GCC 9.3 (Ubuntu 20.04):
```
In file included from ../LibOS/shim/src/bookkeep/shim_vma.c:17:
../LibOS/shim/src/bookkeep/shim_vma.c: In function ‘rs_vma’:
../LibOS/shim/include/shim_checkpoint.h:192:12: error: potential null pointer dereference [-Werror=null-dereference]
  192 |         tmp->cp_val;                                 \
      |         ~~~^~~~~~~~
../LibOS/shim/src/bookkeep/shim_vma.c:1279:32: note: in expansion of macro ‘GET_CP_ENTRY’
 1279 |     void* need_mapped = (void*)GET_CP_ENTRY(ADDR);
      |                                ^~~~~~~~~~~~
../LibOS/shim/include/shim_checkpoint.h:190:19: error: null pointer dereference [-Werror=null-dereference]
  190 |         while (tmp->cp_type != CP_##type)            \
      |                ~~~^~~~~~~~~
../LibOS/shim/src/bookkeep/shim_vma.c:1279:32: note: in expansion of macro ‘GET_CP_ENTRY’
 1279 |     void* need_mapped = (void*)GET_CP_ENTRY(ADDR);
      |                                ^~~~~~~~~~~~
cc1: all warnings being treated as errors
```

So I moved it here without comment, and left the edited comment in LibOS near `-Wno-null-dereference`.
</blockquote></details>

OK, thanks.


<!-- Sent from Reviewable.io -->

2021-05-21 14:35 UTC, boryspoplawski reviewed
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[meson.build, line 63 at r9](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaCdPyg8V0C4i-NrW_8:-MaEKD5q3WIL7CEkQX0x:bu98ui0) ([raw file](https://github.com/oscarlab/graphene/blob/831a477c6e5345aaca32a78e9a30bbc6bdc77156/meson.build#L63)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I have no idea, I don't know what a stack protector is. Sure I can rename to whatever the consensus says. @mkow @boryspoplawski 
</blockquote></details>

+1 to `cflags_custom_stack_protector`


<!-- Sent from Reviewable.io -->

2021-05-21 16:19 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-05-21 20:21 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-05-23 14:55 UTC, mkow requested changes
> Reviewed 9 of 30 files at r1, 2 of 4 files at r2, 12 of 18 files at r5, 1 of 1 files at r7, 5 of 5 files at r9, 1 of 3 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 13 unresolved discussions (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_uVpvZ4xwuAmqHJOjy:-MaL_j1I8Us8zdiYU91k:bk2f8xc) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, dropped and rebased.
</blockquote></details>

+1 for dropping it.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaL_dRXA69HwKvUEnWh:-MaL_dRYBgmsNpOORtNy:b-9e5k5n) (no related file):*
fixes for commit messages:
`initialisation` -> `initialization`
`python script` -> `a Python script`
`meson` -> `Meson`

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLhOT9ELBbW3Qva6Kv:-MaLhOT9ELBbW3Qva6Kw:b-xqhks1) (no related file):*
```Make
@echo '(For now, please ignore "Build targets in project: 0" and "ninja: no work to do.")'
```

Please update (remove?) this warning from the main Makefile, those messages don't show anymore.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOd4hQCd4_HHwE9TQS:-MaOd4hQCd4_HHwE9TQT:binjqfk) (no related file):*
@stefanberger: Heads-up, we're going to merge this soon and you may be interested in those changes (especially whether we IFed the arch-specific dirs correctly).

---
___
*[LibOS/shim/include/meson.build, line 15 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLnFgbCY94hDr-52IW:-MaLnFgbCY94hDr-52IX:b-hh7o46) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L15)):*
> ```Meson
> 
> includes_libos_i = []
> foreach i : includes_libos
> ```

nitpick: I'd rename this `i` to `include` or something similar. Conventionally variables like `i` and `j` are used as _indexes_, not the items from an array itself.
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaLngCR6bxcb0p4Oqv1:b71iq9k) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
> ```Meson
> includes_libos = include_directories(includes_libos)
> 
> libos_generated_offsets_s = custom_target('generated-offsets.s',
> ```

I think this would be more readable if the first arg was on the next line (i.e. all args should be on the same indentation level if you do one-per-line).
It kinda looks like the following construction:
```C
if (a && b) { asdf();
    do_something();
    do_other_thing();
}
```
(i.e. the first statement is hidden and easy to overlook)
___
*[LibOS/shim/src/meson.build, line 1 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaO_1f83m-pFl-o74Gy:-MaO_1f83m-pFl-o74Gz:b-31u2zf) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L1)):*
> ```
> precompiled
> ```

To be technically strict, this is not a precompilation, it's just normal compilation.
___
*[LibOS/shim/src/meson.build, line 11 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaO_sCvBcSMbVm0bQFI:-MaO_sCvBcSMbVm0bQFJ:b6p7xiw) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L11)):*
> ```Meson
>         dirs: join_paths(meson.current_source_dir(), '../../../Runtime'))
> else
>     error('need to link libsysdb against either PAL')
> ```

rather libpal? (which is actually a deprecated name, should be something like "common lib", especially after @dimakuv fixed part of this problem)
___
*[LibOS/shim/src/meson.build, line 106 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOabCe4MkaGpkH4oVC:-MaOabCe4MkaGpkH4oVD:bz217pb) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L106)):*
> ```Meson
>     'syscallas.S',
> ]
> foreach i : libos_sources_arch
> ```

ditto (`i`)
___
*[LibOS/shim/src/meson.build, line 115 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaObrX6AOSgOOkQVcDT:-MaObrX6AOSgOOkQVcDU:b-y622i5) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L115)):*
> ```Meson
> subdir('vdso')
> 
> vdso_data_o = custom_target('vdso-data.o',
> ```

ditto (next line please)
___
*[LibOS/shim/src/meson.build, line 129 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOhzjv9C7S_GIlH6cX:-MaOhzjv9C7S_GIlH6cY:bb5gdu1) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L129)):*
> ```Meson
> )
> 
> shared_library('sysdb',
> ```

ditto (next line please)
and ditto for the whole PR, I see a lot of such places
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2351#-M_-v7LF28UIBFNuAq3v:-MaOdh4vACE_Eb9uq-vE:b1xdqbk) ([raw file](https://github.com/oscarlab/graphene/blob/012b0e6a72e02de6006d058910a409538df26176/LibOS/shim/src/vdso/arch/x86_64/meson.build#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK. Looks very ugly though...
</blockquote></details>

This script saved my ass when I was modifying something recently and made a silly mistake, so I'd prefer to keep it :)
___
*[LibOS/shim/src/vdso/arch/x86_64/meson.build, line 1 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOdRBwBL3qTZWID4Oj:-MaOdRBwBL3qTZWID4Ok:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/vdso/arch/x86_64/meson.build#L1)):*
> ```Meson
> vdso_so_dbg = shared_library('vdso',
> ```

ditto
___
*[Scripts/gen-offsets.py, line 13 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOelA4C2zmc5u_mUBl:-MaOelA4C2zmc5u_mUBm:bd7vvou) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/Scripts/gen-offsets.py#L13)):*
> ```Python
>     .ascii "GENERATED_INTEGER SHIM_TCB_OFF $8 "
> 
> (see the DEFINE macro common/include/generated-offsets-build.h)
> ```

I'd add "in" or "from" after "macro".
___
*[Scripts/gen-pal-map.py, line 29 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOgJWk8J51lxWESaGj:-MaOgJWk8J51lxWESaGk:bz217pb) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/Scripts/gen-pal-map.py#L29)):*
> ```Python
> def main(args=None):
>     args = argparser.parse_args(args)
>     pal_symbols = ' '.join(f'{i};' for i in args.pal_symbols.read().strip().split())
> ```

ditto (`i`)
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-MaOgp20AU9xAMznx9Zt:bb1w82f) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, so leaving as is.
</blockquote></details>

I don't like it for exactly the same reason as Borys, auto-generated names are _huge_ pain because they are unsearchable. I can live with this as there are only 4 of them here, but I definitely don't like it.


<!-- Sent from Reviewable.io -->

2021-05-24 10:14 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 13 unresolved discussions (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaL_dRXA69HwKvUEnWh:-MaShrcIA0rMPoQREpH6:b-ra09tm) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

fixes for commit messages:
`initialisation` -> `initialization`
`python script` -> `a Python script`
`meson` -> `Meson`
</blockquote></details>

"Initialisation" is correct: https://www.lexico.com/definition/initialisation. Capitalisation fixed.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLhOT9ELBbW3Qva6Kv:-MaSiAaR6uNrIoqkCyan:b94oufv) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

```Make
@echo '(For now, please ignore "Build targets in project: 0" and "ninja: no work to do.")'
```

Please update (remove?) this warning from the main Makefile, those messages don't show anymore.
</blockquote></details>

I had a commit for this in Pal/Linux PR, but if you'd like it here, no problem, I've cherry-picked it here.

---
___
*[LibOS/shim/include/meson.build, line 15 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLnFgbCY94hDr-52IW:-MaSill-4Zdi063WqULx:b-stq4q6) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: I'd rename this `i` to `include` or something similar. Conventionally variables like `i` and `j` are used as _indexes_, not the items from an array itself.
</blockquote></details>

Nope, in Python it's OK to iterate over contents of a collection with ijk.
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaSiwyq2HRT8KEDgGNO:bw75dpf) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this would be more readable if the first arg was on the next line (i.e. all args should be on the same indentation level if you do one-per-line).
It kinda looks like the following construction:
```C
if (a && b) { asdf();
    do_something();
    do_other_thing();
}
```
(i.e. the first statement is hidden and easy to overlook)
</blockquote></details>

The first argument to meson targets is special, it is a name of the target, a string, which has varying levels of connection to any filenames involved. In `custom_target` there is almost no connection (you can only use it in `@`-substitutions in other arguments). For example, if you generate `.c` and `.h` file together, it's perfectly fine to name the target `foo.[ch]` for example. Also, all other arguments are keyword-only, so here it surely would be OK to write as you suggest. But in binary targets (`executable`, `shared_library` etc.) it's the name of the executable, or the stem of the library name (`foo` → `libfoo.so.1.2.3`), and immediately after it, all positional arguments are inputs for that binary. So it has to be distinguished, because the other variant is unclear:

```meson
executable(
    'asdf',  # ← this is BAD, because it's not separated from other args
    'zxcv.o',
    'qwerty.c`,
    'qwerty.h',
)
```

So for consistency, I prefer to write all target names on the same line as the the opening paren. As a data point, we do the same with `argparse` in python, arguments are on the same line as `.add_argument(`, and also `metavar=` is inline, all for clarity.
___
*[LibOS/shim/src/meson.build, line 1 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaO_1f83m-pFl-o74Gy:-MaSm6loBDd_aNP2pa0k:b-hji1c1) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> precompiled
> ```

To be technically strict, this is not a precompilation, it's just normal compilation.
</blockquote></details>

From meson's POV it's precompiled, and it will go away when mesonifying PALs.
___
*[LibOS/shim/src/meson.build, line 11 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaO_sCvBcSMbVm0bQFI:-MaSrTno3WzeidWhJzZf:b-xc4v26) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

rather libpal? (which is actually a deprecated name, should be something like "common lib", especially after @dimakuv fixed part of this problem)
</blockquote></details>

"common" is `precompiled_libgraphene_libos` above, this is the actual PAL. Yes, it's named `libpal`.
___
*[Scripts/gen-offsets.py, line 13 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOelA4C2zmc5u_mUBl:-MaSoaRM-lAuI_RRYks2:bqtzbgv) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/Scripts/gen-offsets.py#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add "in" or "from" after "macro".
</blockquote></details>

Done. Previous version was directly copied from makefile.
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-MaSoqLnANwIRDM5TYS6:b-kxmi) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like it for exactly the same reason as Borys, auto-generated names are _huge_ pain because they are unsearchable. I can live with this as there are only 4 of them here, but I definitely don't like it.
</blockquote></details>

The other way would be to:
```meson
check_no_reloc_prog = find_program('check-no-reloc.sh'
gen_ofsets_prog = find_program('gen-offsets.py')
get_python_platlib_prog = find_program('get-python-platlib.py')
meson_clang_format_prog = find_program('meson-clang-format.sh')
```
but then we'll have to be careful about spelling mistakes (did you catch the one in the second line?)


<!-- Sent from Reviewable.io -->

2021-05-24 12:46 UTC, mkow requested changes
> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @pwmarcz, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaL_dRXA69HwKvUEnWh:-MaTIxywEvk5v3toQKJA:bijkabn) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"Initialisation" is correct: https://www.lexico.com/definition/initialisation. Capitalisation fixed.
</blockquote></details>

It's not, we use American English, please fix.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLhOT9ELBbW3Qva6Kv:-MaTJjfP4aY4fTLCWEqV:bu7r1oj) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I had a commit for this in Pal/Linux PR, but if you'd like it here, no problem, I've cherry-picked it here.
</blockquote></details>

This was fixed here (and this PR will be merged first), so the warning should also be fixed here.

---
___
*[LibOS/shim/include/meson.build, line 15 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLnFgbCY94hDr-52IW:-MaTL_U22hlwxjVi8dCB:b-99nq7t) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L15)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Nope, in Python it's OK to iterate over contents of a collection with ijk.
</blockquote></details>

I don't think so, at least not in the examples I found in pep. The one single-letter instance I found used "x", which is good, and all the others used the element name (e.g. `for key in dict.iterkeys():`).
IMO using `i` here is very confusing. In most languages you can iterate over collections in two distinct ways, and using `i` for the name suggests the other way than you used here.
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaTMISe2lLcDd5mKk5v:b913c09) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The first argument to meson targets is special, it is a name of the target, a string, which has varying levels of connection to any filenames involved. In `custom_target` there is almost no connection (you can only use it in `@`-substitutions in other arguments). For example, if you generate `.c` and `.h` file together, it's perfectly fine to name the target `foo.[ch]` for example. Also, all other arguments are keyword-only, so here it surely would be OK to write as you suggest. But in binary targets (`executable`, `shared_library` etc.) it's the name of the executable, or the stem of the library name (`foo` → `libfoo.so.1.2.3`), and immediately after it, all positional arguments are inputs for that binary. So it has to be distinguished, because the other variant is unclear:

```meson
executable(
    'asdf',  # ← this is BAD, because it's not separated from other args
    'zxcv.o',
    'qwerty.c`,
    'qwerty.h',
)
```

So for consistency, I prefer to write all target names on the same line as the the opening paren. As a data point, we do the same with `argparse` in python, arguments are on the same line as `.add_argument(`, and also `metavar=` is inline, all for clarity.
</blockquote></details>

But my point isn't about this arg being distinguishable, but that it's just hidden from the normal reading flow, same as in the `if` example I pasted, which is IMO much more important.
But I see that official Meson examples unfortunately also do this.

@dimakuv @boryspoplawski @pwmarcz: What do you think?
___
*[LibOS/shim/src/meson.build, line 1 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaO_1f83m-pFl-o74Gy:-MaTNvfFBqWl1mVtS86N:b-fkc68r) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

From meson's POV it's precompiled, and it will go away when mesonifying PALs.
</blockquote></details>

What do you mean by "Meson POV"? Does it use different terminology? Precompilation is just a different thing, this file is already compiled, but not linked.
___
*[Scripts/meson.build, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma4qNVy3TySFNGL30hY:-MaTOJx0ADZuMtsO4e7f:bidsfvw) ([raw file](https://github.com/oscarlab/graphene/blob/f887ae62e5413dfcde80b4fa6cf1ac6bd25a921c/Scripts/meson.build#L7)):*
> did you catch the one in the second line?

I did, I'm quite picky about typos ;) I also found a missing `)` on the first line :)

Typos like the one here are harmless, because either the build will blow up or you made the same typo in all the places, so someone probably will notice it.

Anyways, I'm not blocking here, but I dislike this version.


<!-- Sent from Reviewable.io -->

2021-05-24 15:15 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 32 of 33 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaTrLEYBmFHhtc52QQt:b-q5gfjb) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But my point isn't about this arg being distinguishable, but that it's just hidden from the normal reading flow, same as in the `if` example I pasted, which is IMO much more important.
But I see that official Meson examples unfortunately also do this.

@dimakuv @boryspoplawski @pwmarcz: What do you think?
</blockquote></details>

I had no problem with reading this when reviewing this PR, so I'm completely fine with this staying.
The C example you provided is different, `asdf();` is a separate statement and function arguments != scope block (w.r.t. indentation and styling).
___
*[LibOS/shim/src/meson.build, line 5 at r12](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaTtIcy1LyjgCe8IVfS:-MaTtIcy1LyjgCe8IVfT:br8q0p7) ([raw file](https://github.com/oscarlab/graphene/blob/f63f06c88202b806076e53580a31f37ee31a4fc4/LibOS/shim/src/meson.build#L5)):*
> ```Meson
> 
> # TODO: Is this library even needed for linking LibOS? Maybe it can be removed from the
> # dependencies.
> ```

It is needed. Maybe there is some combination of flags to `ld` and linker script commands that would allow to not add it, but I'm not aware of any. In anyway, it would definitely not be a common practice to not specify it.


<!-- Sent from Reviewable.io -->

2021-05-24 18:27 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 29 of 34 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @woju, and @yamahata)

___
*[meson.build, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2351#-Ma0h9QeDMZ4bjTbqP-w:-MaUULpT0snZ8uFJvJs6:b-lj9seq) ([raw file](https://github.com/oscarlab/graphene/blob/26d2bfbe1b715ac729d3bf271469987dfb4eee97/meson.build#L24)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

I agree too. I get that Meson might abstract over some differences between compilers here, but I think fine-grained control over warnings is more important, even if we need to special-case these compilers.
___
*[LibOS/shim/include/meson.build, line 15 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLnFgbCY94hDr-52IW:-MaUXVuA8qtRyOhJ9F_W:b-v9snyx) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L15)):*
>Nope, in Python it's OK to iterate over contents of a collection with ijk.

It does happen sometimes, I can see examples, although rare, in Django (mostly in tests) and in CPython (mostly in documentation). But even going through these projects it's like 1-2% of all instances of `for i in`.

I haven't found any style guide recommending it - closest is Google style guide that permits one-letter names for "counters or iterators (e.g. i, j, k, v, et al.)", but it sounds to me like they recommend `i, j, k` for counters, and `k, v` for keys/values.

I don't care too much but I consider it an anti-pattern.
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaUVBPsEWsYSq_jQ4P_:b-49qb7w) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I had no problem with reading this when reviewing this PR, so I'm completely fine with this staying.
The C example you provided is different, `asdf();` is a separate statement and function arguments != scope block (w.r.t. indentation and styling).
</blockquote></details>

It's certainly an unusual convention for Python or C; I've seen Lispers do that (vary the indentation rules depending on what the function/form is, so that `(if cond expr1 expr2)` is formatted differently to `(when cond expr1 expr2)`).

I would definitely prefer to follow this style if it was a strongly prescribed Meson convention (e.g. if there was something like PEP-8 for Meson, or an official auto-formatting tool), if it's only examples, maybe it's not so important.

In the end, I don't care too much either way, but it should be the same everywhere. Looking below, `libos_asm_offsets_h` doesn't follow this convention.


<!-- Sent from Reviewable.io -->

2021-05-24 18:49 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 29 of 34 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @woju, and @yamahata)

___
*[LibOS/shim/include/meson.build, line 15 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLnFgbCY94hDr-52IW:-MaTzjenCw8pVhwOSBFW:b-vcbabx) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't think so, at least not in the examples I found in pep. The one single-letter instance I found used "x", which is good, and all the others used the element name (e.g. `for key in dict.iterkeys():`).
IMO using `i` here is very confusing. In most languages you can iterate over collections in two distinct ways, and using `i` for the name suggests the other way than you used here.
</blockquote></details>

PEP 8 doesn't specify this, and if you're talking about https://wiki.python.org/moin/ForLoop, this document is misguided, because there is `for list in list_of_lists`, which is wrong, as `list` is builtin.

But this generally might be a good principle, so I added a change to coding style.
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaU0uBO6uitSz-4BS50:b-qddwc3) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I had no problem with reading this when reviewing this PR, so I'm completely fine with this staying.
The C example you provided is different, `asdf();` is a separate statement and function arguments != scope block (w.r.t. indentation and styling).
</blockquote></details>

Oh, and also, if you forget about this arg, there are strange results:
```meson
sources = ['file1.c', 'file2.c']
executable(
    sources
)
```
Guess what will happen: this will build `file1.c` ELF from `file2.c` alone.
___
*[LibOS/shim/src/meson.build, line 1 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaO_1f83m-pFl-o74Gy:-MaU1rTC8uyWwrCs8Uh_:b-xrx7b1) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What do you mean by "Meson POV"? Does it use different terminology? Precompilation is just a different thing, this file is already compiled, but not linked.
</blockquote></details>

Removed "precompiled".
___
*[LibOS/shim/src/meson.build, line 106 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOabCe4MkaGpkH4oVC:-MaUNC4s8g4pDsLges8L:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L106)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`i`)
</blockquote></details>

Done.
___
*[LibOS/shim/src/meson.build, line 5 at r12](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaTtIcy1LyjgCe8IVfS:-MaU1UjB5C0v3ruytzv7:b-7yvciw) ([raw file](https://github.com/oscarlab/graphene/blob/f63f06c88202b806076e53580a31f37ee31a4fc4/LibOS/shim/src/meson.build#L5)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It is needed. Maybe there is some combination of flags to `ld` and linker script commands that would allow to not add it, but I'm not aware of any. In anyway, it would definitely not be a common practice to not specify it.
</blockquote></details>

OK, removing.
___
*[Scripts/gen-pal-map.py, line 29 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaOgJWk8J51lxWESaGj:-MaUJddO5VU8J_fgY7ZU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/Scripts/gen-pal-map.py#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`i`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-24 18:54 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 29 of 34 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, @woju, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaL_dRXA69HwKvUEnWh:-MaUiIMR2-JkgZqSwt_X:b-qak1eh) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's not, we use American English, please fix.
</blockquote></details>

If you're attached to this dialect, can you do it yourself while rebasing?

---
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaUhUbiA3dTkWT3IUd1:bxkcc8) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
I added this to coding-style.rst and fixed remaining places.

> if there was something like PEP-8 for Meson

There is https://mesonbuild.com/Style-guide.html, also there are examples thorough the docs. But some of them are IMHO wrong, like `:` separating kwarg and value has spaces on both sides and there are also spaces inside `[ a, b, c ]`. Example with `files()` on the very page is wrong, because `[]` is not needed. So I'd prefer to have our own meson style.


<!-- Sent from Reviewable.io -->

2021-05-24 19:05 UTC, boryspoplawski requested changes
> Reviewed 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/devel/coding-style.rst, line 169 at r13](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaUkgEhCK46PDARv7Kp:-MaUkgEhCK46PDARv7Kq:b-lx4asf) ([raw file](https://github.com/oscarlab/graphene/blob/0a4526adfe71bccc24f7d5a66208c99397665484/Documentation/devel/coding-style.rst#L169)):*
> ```reStructuredText
>    other arguments should be on next lines, aligned to 4-space indent.
> 
>    Arguments to other functions should either be all on the same line, or there
> ```

What, why? Why we differentiate between these 3 functions and all others?
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaUjh06AnMfXKoNiYE6:b-ewmsl0) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
> It's certainly an unusual convention for Python or C

I wouldn't say so:
```
long x = some_function_with_long_name(argument_1_with_a_long_name,
                                      arg_2_with_a_long_name,
                                      arg3);
```
seems like a common pattern. The only difference is indention.


<!-- Sent from Reviewable.io -->

2021-05-24 19:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaUqPOx6H05J5nnoEiu:b-3d0jux) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
>The only difference is indention.

Yes, I meant indentation.


<!-- Sent from Reviewable.io -->

2021-05-24 23:29 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[Documentation/devel/coding-style.rst, line 169 at r13](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaUkgEhCK46PDARv7Kp:-MaVdbugDF-mVGCF1Xfq:b-3nnd2s) ([raw file](https://github.com/oscarlab/graphene/blob/0a4526adfe71bccc24f7d5a66208c99397665484/Documentation/devel/coding-style.rst#L169)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What, why? Why we differentiate between these 3 functions and all others?
</blockquote></details>

Because in principle @mkow's criticisms was valid in that the first argument is off. And it is off by design in those target functions, but not in others like `join_paths()`.
(There are eight of those target functions, incl. `jar()` and `build_target()`, the latter has keyword argument which muxes it to one of the other seven).
___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaVe0AnAbBtom0y1IRV:b-8qsgj5) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>The only difference is indention.

Yes, I meant indentation.
</blockquote></details>

This pattern is misguided, especially for repetitive blocks (and we expect there will be many of those in meson!) where the about only thing that changes is variable name. Then there indented block jumps all over the editor. Everything should be indented to a multiple of base indent (4 spaces in our case). So in that case if the first argument is on the first line, it's kinda disconnected and @mkow has a point. But in this case it should be disconnected in the first place.


<!-- Sent from Reviewable.io -->

2021-05-24 23:50 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 10 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)



<!-- Sent from Reviewable.io -->

2021-05-25 09:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 3 files at r12, 4 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 10 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[LibOS/shim/include/meson.build, line 20 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaLngCR6bxcb0p4Oqv0:-MaXmsBo8brpTgZQYEPj:bjfgmmz) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/include/meson.build#L20)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This pattern is misguided, especially for repetitive blocks (and we expect there will be many of those in meson!) where the about only thing that changes is variable name. Then there indented block jumps all over the editor. Everything should be indented to a multiple of base indent (4 spaces in our case). So in that case if the first argument is on the first line, it's kinda disconnected and @mkow has a point. But in this case it should be disconnected in the first place.
</blockquote></details>

I have no problems with either of these conventions. The current one looks fine to me, as long as it is used everywhere in our files.
___
*[LibOS/shim/src/meson.build, line 11 at r11](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaO_sCvBcSMbVm0bQFI:-MaXnFVeC3cLyNLjANWW:bifccas) ([raw file](https://github.com/oscarlab/graphene/blob/f20cc79e207125730d6bcb6e09e93fa6bbaf487d/LibOS/shim/src/meson.build#L11)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

"common" is `precompiled_libgraphene_libos` above, this is the actual PAL. Yes, it's named `libpal`.
</blockquote></details>

@woju is right, `libpal` is the name of the PAL library/executable. The name for the "common lib" is `graphene-lib`.

@mkow Please note that we link LibOS library against `libpal` library simply to shut up gcc/ld because otherwise it would complain about `not found symbol DkCreateProcess, DkThreadCreate` etc.

All this will go away when I will finish the transition to "link LibOS + PAL in one binary". And yes, I'll try to rename all these libraries to something more meaningful (`graphene-lib` -> `libcommon`).


<!-- Sent from Reviewable.io -->

2021-05-25 13:32 UTC, mkow requested changes
> Reviewed 5 of 5 files at r13.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaL_dRXA69HwKvUEnWh:-MaYbiUA98JCR5k4Lz2C:bj83v0r) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If you're attached to this dialect, can you do it yourself while rebasing?
</blockquote></details>

The whole project uses it, this is for consistency. I can fix this during rebase.

---
___
*[Documentation/devel/coding-style.rst, line 122 at r13](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaYcezx3ylUq6fOdgiL:-MaYcezx3ylUq6fOdgiM:b-3ippnb) ([raw file](https://github.com/oscarlab/graphene/blob/0a4526adfe71bccc24f7d5a66208c99397665484/Documentation/devel/coding-style.rst#L122)):*
> ```
> indexes to arrays
> ```

I think it should be either "array indexes" or "indexes for arrays" (but I'm not 100% sure about the latter).
___
*[Documentation/devel/coding-style.rst, line 178 at r13](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaYh0_GBZeIrOTNeyTb:-MaYh0_H2l3CdNZKfrin:b-3iu30l) ([raw file](https://github.com/oscarlab/graphene/blob/0a4526adfe71bccc24f7d5a66208c99397665484/Documentation/devel/coding-style.rst#L178)):*
> ```
> file:`meson.build`
> ```

This thing misrenders: (see file:_meson.build_ there)


<!-- Sent from Reviewable.io -->

2021-05-25 15:27 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 4 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Documentation/devel/coding-style.rst, line 122 at r13](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaYcezx3ylUq6fOdgiL:-MaZ7PMQ0j6CwAAy8nps:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0a4526adfe71bccc24f7d5a66208c99397665484/Documentation/devel/coding-style.rst#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> indexes to arrays
> ```

I think it should be either "array indexes" or "indexes for arrays" (but I'm not 100% sure about the latter).
</blockquote></details>

Done.
___
*[Documentation/devel/coding-style.rst, line 178 at r13](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaYh0_GBZeIrOTNeyTb:-MaZ7KSq5jt1WOYu9rtb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0a4526adfe71bccc24f7d5a66208c99397665484/Documentation/devel/coding-style.rst#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> file:`meson.build`
> ```

This thing misrenders: (see file:_meson.build_ there)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 15:33 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-05-25 15:57 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-05-25 17:34 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaZZryZBJHhVuvEliAM:-MaZZryZBJHhVuvEliAN:b-4u4gjw) (no related file):*
@woju All pipelines failed with `undefined reference to `log_always'` and `... to 'abort'`. This looks weird, probably an artifact of Jenkins automatically merging your branch into master (because it didn't detect conflicts so decided to merge).

I merged this PR in the meantime which adds `log_always` and `abort` to the Common library (it expects these functions as callbacks defined in LibOS/PAL/other). Probably you'll need to rebase this PR to the latest master to fix this.

---


<!-- Sent from Reviewable.io -->

2021-05-25 19:01 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: 32 of 34 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaZZryZBJHhVuvEliAM:-MaZrmWt7SAfRSuxON3x:bt2vr1b) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju All pipelines failed with `undefined reference to `log_always'` and `... to 'abort'`. This looks weird, probably an artifact of Jenkins automatically merging your branch into master (because it didn't detect conflicts so decided to merge).

I merged this PR in the meantime which adds `log_always` and `abort` to the Common library (it expects these functions as callbacks defined in LibOS/PAL/other). Probably you'll need to rebase this PR to the latest master to fix this.
</blockquote></details>

Fixed.

---


<!-- Sent from Reviewable.io -->

2021-05-25 19:58 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2021-05-25 20:07 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 2 files at r14, 1 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-05-26 10:38 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2351#-MaL_dRXA69HwKvUEnWh:-MacF1il21se2iEzrDhm:b-q2x346) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The whole project uses it, this is for consistency. I can fix this during rebase.
</blockquote></details>

Done. I also made the message a bit more precise - as this wasn't a bug in the code as the old one suggested, but just overzealous compiler warnings.

---


<!-- Sent from Reviewable.io -->

2021-05-26 10:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2351)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-26 11:27 UTC, merged