[Pal] Return remaining time in DkEventWait
oscarlab/graphene pull request #2368
Opened 2021-05-11 20:41 UTC by boryspoplawski

## Description of the changes 
These changes are needed to correctly emulate `nanosleep` syscall.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2368)

2021-05-11 23:59 UTC, mkow requested changes
> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SU_mfEvbLb4i5p7kF:-M_SU_mfEvbLb4i5p7kG:b-s5bf68) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/host/Linux-common/linux_utils.h#L20)):*
> ```objc
> int read_text_file_to_cstr(const char* path, char** out);
> 
> void time_get_now_plus_ns(struct timespec* ts, uint64_t val);
> ```

This `val` in the signature is quite confusing. I didn't read the implementation yet, but I have no idea what value it is (looking only at the signature).
___
*[Pal/include/pal/pal.h, line 653 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SX_xkBmaZtqZQ2LQr:-M_SX_xkBmaZtqZQ2LQs:bu56mrg) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L653)):*
> ```objc
> 
> /*!
>  * \brief Wait for a event handle.
> ```

`a` -> `an`
___
*[Pal/include/pal/pal.h, line 655 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SXxcZ9yjGixh3RyXL:-M_SXxcZ9yjGixh3RyXM:b-rj8n3q) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L655)):*
> ```objc
>  * \brief Wait for a event handle.
>  *
>  * \param handle handle to wait on, must be of event type
> ```

`of event type` -> `of "event" type` (although I'm not sure which marking to use here)
___
*[Pal/include/pal/pal.h, line 656 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SXdS13K8idv37G-Z8:-M_SXdS13K8idv37G-Z9:bbx5xfd) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L656)):*
> ```objc
>  *
>  * \param handle handle to wait on, must be of event type
>  * \param timeout_us timeout for the wait TODO
> ```

TODO? I guess you forgot to finish this :)
___
*[Pal/include/pal/pal.h, line 659 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SYRtQ4E2ZP81cIQxl:-M_SYRtQ4E2ZP81cIQxm:b-2y6s2h) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L659)):*
> ```objc
>  *
>  * \return 0 if the event was triggered, negative error code otherwise (#PAL_ERROR_TRYAGAIN in case
>  *           of timeout triggering)
> ```

please fix alignment
___
*[Pal/include/pal/pal.h, line 662 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SZTDd2UWsKbtUjTiS:-M_SZTDd2UWsKbtUjTiT:b-9euvej) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L662)):*
> ```
> Specifying #NO_TIMEOUT blocks indefnitely.
> ```

I'm confused. Where I'm supposed to put this value? It's a number, but the argument is a pointer. And all the callsites use `/*timeout=*/NULL`...

btw. if you decide to just fix up the current description, then please fix the typo: "indefnitely".
___
*[Pal/include/pal/pal.h, line 665 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SYyNcDGQWupkV29m3:-M_SYyNcDGQWupkV29m4:b7jhwm7) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L665)):*
> ```objc
>  * in any case this function can return earlier, e.g. if a signal has arrived, but this will be
>  * indicated by the returned error code.
>  * This function has acuire semantics and synchronizes with #DkEventSet.
> ```

`acuire` -> `acquire`
___
*[Pal/include/pal/pal.h, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SZ47g49E_m-tVXS_H:-M_SZ47g49E_m-tVXS_I:bigsony) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L667)):*
> ```
> uint64_t* timeout
> ```

Please add time unit suffix.
___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sl5hiE6JIkFxNekS0:-M_Sl5hiE6JIkFxNekS1:b-6melk9) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux/db_events.c#L38)):*
> ```C
>     int ret = INLINE_SYSCALL(futex, 6, &handle->event.signaled, FUTEX_WAKE_BITSET,
>                              handle->event.auto_clear ? 1 : INT_MAX, NULL, NULL,
>                              FUTEX_BITSET_MATCH_ANY);
> ```

Why changing to `FUTEX_WAKE_BITSET`?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SoEJL9jKLhgv3c93i:-M_SoEJL9jKLhgv3c93j:b-eq0xlb) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/enclave_ocalls.c#L113)):*
> ```C
>             WRITE_ONCE(ms->ms_futex, &req->lock.lock);
>             WRITE_ONCE(ms->ms_op, FUTEX_WAIT_PRIVATE);
>             WRITE_ONCE(ms->ms_timeout_us, (uint64_t)-1l); /* never time out */
> ```

why the literal suffix?
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 931 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SouwrBNRVVrmLf9ZF:-M_SouwrBNRVVrmLf9ZG:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/enclave_ocalls.c#L931)):*
> ```C
>     WRITE_ONCE(ms->ms_op, op);
>     WRITE_ONCE(ms->ms_val, val);
>     WRITE_ONCE(ms->ms_timeout_us, timeout_us ? *timeout_us : (uint64_t)-1l);
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 942 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sq8NS0cTXmlBlLjYM:-M_SpP2K00xxtwFQHmNs:b-vzoreg) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/enclave_ocalls.c#L942)):*
> ```C
>     }
> 
>     if (timeout_us) {
> ```

Should we execute this branch on all errors? E.g. on `-EINVAL` `ms->ms_timeout_us` is not updated at all. Not sure if this is a problem, but if it's fine, then I'd add an explicit comment about it.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 296 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SqWyFEa3IK03wzHr1:-M_SqWyFEa3IK03wzHr2:b13l8ob) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/sgx_enclave.c#L296)):*
> ```C
> 
>     struct timespec timeout = { 0 };
>     bool have_timeout = ms->ms_timeout_us != (uint64_t)-1l;
> ```

ditto (suffix)
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 313 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sqn1I4K8icr-lEi6L:-M_Sqn1I4K8icr-lEi6M:b7kuqfg) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/sgx_enclave.c#L313)):*
> ```C
>         /* Other operations are not supported atm. */
>         return -EINVAL;
>     }
> ```

Could you add a comment with an explanation what is happening here? I.e. why we need this translation.


<!-- Sent from Reviewable.io -->

2021-05-12 02:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: 20 of 27 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SU_mfEvbLb4i5p7kF:-M_TCnyJ1KE58Cn3yxHW:beyo48g) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/host/Linux-common/linux_utils.h#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This `val` in the signature is quite confusing. I didn't read the implementation yet, but I have no idea what value it is (looking only at the signature).
</blockquote></details>

Now that you've read it, what would you suggest? Only thing that comes to my mind is `offset`, but that looks weird too...
___
*[Pal/include/pal/pal.h, line 653 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SX_xkBmaZtqZQ2LQr:-M_TE1XG5bNDlQVtAG9F:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L653)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`a` -> `an`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 655 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SXxcZ9yjGixh3RyXL:-M_TE4aK7bCZ9BF9TDQC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L655)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`of event type` -> `of "event" type` (although I'm not sure which marking to use here)
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 656 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SXdS13K8idv37G-Z8:-M_TE5GdCXk0JNUvTdfW:b-hdp2bn) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L656)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

TODO? I guess you forgot to finish this :)
</blockquote></details>

Yea, this whole docs was still TODO, which I forgot about.
___
*[Pal/include/pal/pal.h, line 659 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SYRtQ4E2ZP81cIQxl:-M_TEUmZ2l32TlptolQS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L659)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please fix alignment
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 662 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SZTDd2UWsKbtUjTiS:-M_TEYGZA50-Z_5GHSPh:b-ir0yov) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L662)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Specifying #NO_TIMEOUT blocks indefnitely.
> ```

I'm confused. Where I'm supposed to put this value? It's a number, but the argument is a pointer. And all the callsites use `/*timeout=*/NULL`...

btw. if you decide to just fix up the current description, then please fix the typo: "indefnitely".
</blockquote></details>

Old version, updated.
___
*[Pal/include/pal/pal.h, line 665 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SYyNcDGQWupkV29m3:-M_TEh0oE-T_Fm0tRv68:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L665)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`acuire` -> `acquire`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SZ47g49E_m-tVXS_H:-M_TElSn0yc5BMsyvB8b:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L667)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> uint64_t* timeout
> ```

Please add time unit suffix.
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_TEoBz4XwVmm6E33f7:-M_TEoBz4XwVmm6E33f8:b-dqneag) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L667)):*
> ```objc
>  * This function has acuire semantics and synchronizes with #DkEventSet.
>  */
> int DkEventWait(PAL_HANDLE handle, uint64_t* timeout);
> ```

I wonder, maybe we should move to nanoseconds?
___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sl5hiE6JIkFxNekS0:-M_THtb1EprHTQYcg4nb:b-f5jgp) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why changing to `FUTEX_WAKE_BITSET`?
</blockquote></details>

Because it has different timeout semantics than `FUTEX_WAKE`. `man 2 futex` (basically, `FUTEX_WAKE` has relative timeout, `FUTEX_WAKE_BITSET` has absolute timeout).
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SoEJL9jKLhgv3c93i:-M_TI4TD7rp7bI1Oj1g_:b43wqal) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/enclave_ocalls.c#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why the literal suffix?
</blockquote></details>

First I wanted 64bit immediate an had `-1l`, but then added an explicit cast and it stayed. It was never really needed.
Removed.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 931 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SouwrBNRVVrmLf9ZF:-M_TJ0Dc8jBjAsYKkgEs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/enclave_ocalls.c#L931)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 942 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sq8NS0cTXmlBlLjYM:-M_TJEjV-LeIQX5C2l3y:b-5is46e) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/enclave_ocalls.c#L942)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should we execute this branch on all errors? E.g. on `-EINVAL` `ms->ms_timeout_us` is not updated at all. Not sure if this is a problem, but if it's fine, then I'd add an explicit comment about it.
</blockquote></details>

On all failures before actually ocall, the value is not updated because it does not need to (remaining time is equal to original).
The only place it's not updated after ocall is if `reamaining_time` is malicious, in which case we don't have any sane value to update it with.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 296 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SqWyFEa3IK03wzHr1:-M_TJYxH-wh5mTC6bBxk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/sgx_enclave.c#L296)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (suffix)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 313 at r1](https://reviewable.io/reviews/os [...]

2021-05-12 07:08 UTC, dimakuv requested changes
> Reviewed 20 of 27 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SU_mfEvbLb4i5p7kF:-M_UFaJJDkQULXqyaZmO:bf7r8d3) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/host/Linux-common/linux_utils.h#L20)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Now that you've read it, what would you suggest? Only thing that comes to my mind is `offset`, but that looks weird too...
</blockquote></details>

I suggest to rename `val` -> `add_ns` and add a quick comment to this function: `/* returns <current time + add_ns> in ts */`. Maybe also `ts` -> `ts_out`?
___
*[Pal/include/host/Linux-common/linux_utils.h, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_UGImlAHM2h6DqBmKL:-M_UGImm7LiMKkFKsNLn:bpchpgh) ([raw file](https://github.com/oscarlab/graphene/blob/d5f495140be041ccd164c043cd2254c8c73bbeab/Pal/include/host/Linux-common/linux_utils.h#L21)):*
> ```objc
> 
> void time_get_now_plus_ns(struct timespec* ts, uint64_t val);
> int64_t time_ns_diff_from_now(struct timespec* ts);
> ```

Same here, quick comment: `/* returns (maybe negative) difference in nanoseconds between current time and time in ts */`
___
*[Pal/include/pal/pal.h, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_TEoBz4XwVmm6E33f7:-M_UHR8H4ucVWqb_svIz:b-e3t74z) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L667)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I wonder, maybe we should move to nanoseconds?
</blockquote></details>

This sounds like a fix for a separate PR. I think we have a bunch of places that use microseconds.
___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sl5hiE6JIkFxNekS0:-M_UIjWs4ZJlkryxyXzE:b-gdsn9n) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux/db_events.c#L38)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because it has different timeout semantics than `FUTEX_WAKE`. `man 2 futex` (basically, `FUTEX_WAKE` has relative timeout, `FUTEX_WAKE_BITSET` has absolute timeout).
</blockquote></details>

From what I understand, there is no difference between `FUTEX_WAKE` and `FUTEX_WAKE_BITSET + FUTEX_BITSET_MATCH_ANY` (from the man page: `The FUTEX_WAKE operation  is  equivalent  to FUTEX_WAKE_BITSET with val3 specified as FUTEX_BITSET_MATCH_ANY`).

But you're changing it here for consistency with the below `FUTEX_WAIT_BITSET`, which indeed has this difference in relative vs absolute timeout. Is this correct?
___
*[Pal/src/host/Linux/db_events.c, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_UO-zABz-wNvJDIWi4:-M_UO-zABz-wNvJDIWi5:bkecems) ([raw file](https://github.com/oscarlab/graphene/blob/d5f495140be041ccd164c043cd2254c8c73bbeab/Pal/src/host/Linux/db_events.c#L69)):*
> ```C
> 
>         ret = INLINE_SYSCALL(futex, 6, &handle->event.signaled, FUTEX_WAIT_BITSET, 0,
>                              timeout_us ? &timeout : NULL, NULL, FUTEX_BITSET_MATCH_ANY);
> ```

Do I understand correctly that this is the crux of the bug fix of `kill11`? We replaced relative timeout with an absolute one. So previously even if futex syscall was interrupted, it was restarted with the same relative timeout (because futex syscall doesn't update the timeout variable itself). But now even if futex syscall is interrupted, it is restarted with the same *absolute* timeout, which will trigger earlier than if it would be relative.

I'm asking this because I don't see any other behavior changes in this PR. In particular, I don't see that the LibOS uses this new feature of "DkEventWait returns an adjusted timeout value". I guess this is postponed for a follow-up PR?
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 313 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sqn1I4K8icr-lEi6L:-M_UMjfy12jWSJ0c4dRh:b769kzk) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/sgx_enclave.c#L313)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I guess ideally we would simply force `FUTEX_WAKE_BITSET`/`FUTEX_WAIT_BITSET` (+ private flag) inside the enclave logic (in `enclave_ocalls.c`), and then we won't need this translation (and we'll force `val3 = FUTEX_BITSET_MATCH_ANY` always). But it doesn't matter much. Not blocking.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 303 at r2](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_ULhKV5L3LKopOfObD:-M_ULhKV5L3LKopOfObE:b-b1invx) ([raw file](https://github.com/oscarlab/graphene/blob/d5f495140be041ccd164c043cd2254c8c73bbeab/Pal/src/host/Linux-SGX/sgx_enclave.c#L303)):*
> ```C
>     /* `FUTEX_WAIT` treats timeout parameter as a relative value. We want to have an absolute one
>      * (since we need to get start time anyway, to calculate remaining time later on), hence we use
>      * `FUTEX_WAIT_BITSET` with `FUTEX_BITSET_MATCH_ANY`. */
> ```

We could add a similar comment to Linux version of`_DkEventWait()`. I understand that there is no "replacement" logic like you do here, but just for the future (so that someone doesn't come and revert it back to `FUTEX_WAIT`, thinking it's a smart optimization). But not blocking.


<!-- Sent from Reviewable.io -->

2021-05-12 07:38 UTC, dimakuv commented
Jenkins, retest this please (just curious to see if any failures are left)

2021-05-12 08:03 UTC, yamahata reviewed
> Reviewed 20 of 27 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-05-12 10:03 UTC, mkow requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SU_mfEvbLb4i5p7kF:-M_UuuC_5EbmOYtZ1IKr:b-nlm4ey) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/host/Linux-common/linux_utils.h#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to rename `val` -> `add_ns` and add a quick comment to this function: `/* returns <current time + add_ns> in ts */`. Maybe also `ts` -> `ts_out`?
</blockquote></details>

Maybe `addend_ns`?
___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sl5hiE6JIkFxNekS0:-M_UzbeO1u2fKzgWPdbZ:b2gvoux) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux/db_events.c#L38)):*
Wow, what a weird API.
And yup, seems Dima is right:

> Note: for FUTEX_WAIT, timeout is interpreted as a relative value.  This differs from other futex operations, where timeout is interpreted as an absolute value.  To obtain the equivalent of FUTEX_WAIT with an absolute timeout, employ FUTEX_WAIT_BITSET with val3 specified as FUTEX_BITSET_MATCH_ANY.

@boryspoplawski Please explain this in a comment (the reason why we don't use the simpler `FUTEX_WAKE`).


<!-- Sent from Reviewable.io -->

2021-05-12 13:56 UTC, boryspoplawski reviewed
@dimakuv This PR does not fix any failures by itself (but ofc it could introduce some:) )

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368#-:-M_VlNKV9bscvpw0XGqL:b-z6bw2)* status: 24 of 27 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

___
*[Pal/include/host/Linux-common/linux_utils.h, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_SU_mfEvbLb4i5p7kF:-M_VmMYiAtT1vgFX8a3I:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/host/Linux-common/linux_utils.h#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe `addend_ns`?
</blockquote></details>

Done.
___
*[Pal/include/host/Linux-common/linux_utils.h, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_UGImlAHM2h6DqBmKL:-M_VmMKf6LqYeIcdiPvt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d5f495140be041ccd164c043cd2254c8c73bbeab/Pal/include/host/Linux-common/linux_utils.h#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Same here, quick comment: `/* returns (maybe negative) difference in nanoseconds between current time and time in ts */`
</blockquote></details>

Done.
___
*[Pal/include/pal/pal.h, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_TEoBz4XwVmm6E33f7:-M_VmPr9308328td_pU3:b-tefjfw) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L667)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sounds like a fix for a separate PR. I think we have a bunch of places that use microseconds.
</blockquote></details>

Yes, not in this PR, and I'm not saying we should, but I just thought it's a good place to think about it.
Do you think we should? I would say yes: Linux uses nanoseconds and if some PALs do not support such high resolution they can always just scale the timeout down.
FWIW: 64bit unsigned can hold ~600 years worth of nanoseconds :)
___
*[Pal/src/host/Linux/db_events.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sl5hiE6JIkFxNekS0:-M_VnaPW97Yi-TaVyIc7:b-mnt9fq) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux/db_events.c#L38)):*
> From what I understand, there is no difference between FUTEX_WAKE and FUTEX_WAKE_BITSET + FUTEX_BITSET_MATCH_ANY (from the man page: The FUTEX_WAKE operation  is  equivalent  to FUTEX_WAKE_BITSET with val3 specified as FUTEX_BITSET_MATCH_ANY).

Yes and even Linux kernel just translates `FUTES_WAKE` into that.

> But you're changing it here for consistency with the below FUTEX_WAIT_BITSET, which indeed has this difference in relative vs absolute timeout. Is this correct?

That's correct, in theory we could leave the old version here, but I wanted to be consistent.

> @boryspoplawski Please explain this in a comment (the reason why we don't use the simpler FUTEX_WAKE).

Done.
___
*[Pal/src/host/Linux/db_events.c, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_UO-zABz-wNvJDIWi4:-M_VoBLP9uZBhaVy3TYw:b-6sbq7j) ([raw file](https://github.com/oscarlab/graphene/blob/d5f495140be041ccd164c043cd2254c8c73bbeab/Pal/src/host/Linux/db_events.c#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do I understand correctly that this is the crux of the bug fix of `kill11`? We replaced relative timeout with an absolute one. So previously even if futex syscall was interrupted, it was restarted with the same relative timeout (because futex syscall doesn't update the timeout variable itself). But now even if futex syscall is interrupted, it is restarted with the same *absolute* timeout, which will trigger earlier than if it would be relative.

I'm asking this because I don't see any other behavior changes in this PR. In particular, I don't see that the LibOS uses this new feature of "DkEventWait returns an adjusted timeout value". I guess this is postponed for a follow-up PR?
</blockquote></details>

No, this is just preparation, this PR by itself does not fix anything `kill11` related, it  just adds functionality + small bugfix for that timeout you mentioned.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 313 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sqn1I4K8icr-lEi6L:-M_VqX_t8DaMNP3nYy0L:b12zrmg) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/sgx_enclave.c#L313)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I guess ideally we would simply force `FUTEX_WAKE_BITSET`/`FUTEX_WAIT_BITSET` (+ private flag) inside the enclave logic (in `enclave_ocalls.c`), and then we won't need this translation (and we'll force `val3 = FUTEX_BITSET_MATCH_ANY` always). But it doesn't matter much. Not blocking.
</blockquote></details>

Then we would also need to expand interface to pass `val3` (forcing it to a constant value makes no sense).
Also in such case we would get different semantics of `ocall_futex` from original `futex` (relative vs absolute timeout), which I don't particularly like.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 303 at r2](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_ULhKV5L3LKopOfObD:-M_Vq1wxAViKcaS_80zl:b-olqnmi) ([raw file](https://github.com/oscarlab/graphene/blob/d5f495140be041ccd164c043cd2254c8c73bbeab/Pal/src/host/Linux-SGX/sgx_enclave.c#L303)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We could add a similar comment to Linux version of`_DkEventWait()`. I understand that there is no "replacement" logic like you do here, but just for the future (so that someone doesn't come and revert it back to `FUTEX_WAIT`, thinking it's a smart optimization). But not blocking.
</blockquote></details>

Done.
Btw, `FUTEX_WAIT` is literally the same, so it's not faster in any way.


<!-- Sent from Reviewable.io -->

2021-05-12 14:16 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (`large_mmap` from Libos/regression failed with `mmap 2: Permission denied`, looks weird, but cannot reproduce locally - in 10k runs)

2021-05-12 14:36 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-18.04 please (Jenkins randomly died while building glibc, probably todays Jenkins hiccups)

2021-05-12 14:58 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/include/pal/pal.h, line 667 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_TEoBz4XwVmm6E33f7:-M_W4BAzEV_hmKJ9D25g:bs9z4rl) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/include/pal/pal.h#L667)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Yes, not in this PR, and I'm not saying we should, but I just thought it's a good place to think about it.
Do you think we should? I would say yes: Linux uses nanoseconds and if some PALs do not support such high resolution they can always just scale the timeout down.
FWIW: 64bit unsigned can hold ~600 years worth of nanoseconds :)
</blockquote></details>

Yes, I like this idea. Currently Graphene uses both ns and us, and this is really annoying.
___
*[Pal/src/host/Linux/db_events.c, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_UO-zABz-wNvJDIWi4:-M_W4PKw2Cl2p1BG0r6B:bz385wu) ([raw file](https://github.com/oscarlab/graphene/blob/d5f495140be041ccd164c043cd2254c8c73bbeab/Pal/src/host/Linux/db_events.c#L69)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No, this is just preparation, this PR by itself does not fix anything `kill11` related, it  just adds functionality + small bugfix for that timeout you mentioned.
</blockquote></details>

OK, understood.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 313 at r1](https://reviewable.io/reviews/oscarlab/graphene/2368#-M_Sqn1I4K8icr-lEi6L:-M_W4Z5WEpZHo8LCx96q:bs4ixp3) ([raw file](https://github.com/oscarlab/graphene/blob/0d5d065251c5f781f8b97da802005ffd140c6005/Pal/src/host/Linux-SGX/sgx_enclave.c#L313)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Then we would also need to expand interface to pass `val3` (forcing it to a constant value makes no sense).
Also in such case we would get different semantics of `ocall_futex` from original `futex` (relative vs absolute timeout), which I don't particularly like.
</blockquote></details>

OK, fair enough.


<!-- Sent from Reviewable.io -->

2021-05-12 15:27 UTC, mkow approved these changes
> Reviewed 1 of 7 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-05-12 23:13 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-05-12 23:21 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (`kill11` failed, please, one more PR and this will be gone...)

2021-05-12 23:27 UTC, yamahata approved these changes
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2368)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-12 23:42 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (`kill11` failed ...)

2021-05-13 00:25 UTC, merged