[LibOS] Remove `shim_dentry.ino`
oscarlab/graphene pull request #2374
Opened 2021-05-14 14:34 UTC by pwmarcz

This change is in preparation for bigger refactoring: simplifying directory handles, `getdents` and `getdents64`.

This commit removes the `shim_dentry.ino` field, and replaces it with a function computing the dentry hash (which is what we usually did anyway).

This is to simplify the code (the inode number was computed in several places: `readdir`, `stat`, `hstat`), and to ensure that the inode number is always available for a dentry.

2021-05-14 18:52 UTC, dimakuv approved these changes
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2374)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-05-14 20:19 UTC, mkow requested changes
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2374)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 247 at r1](https://reviewable.io/reviews/oscarlab/graphene/2374#-M_gVT36AQ48HBXq7RRm:-M_gVT3738O1zllPZVDC:bhk0i2r) ([raw file](https://github.com/oscarlab/graphene/blob/97c63e815f46a2892a3cf7305563d115b912d504/LibOS/shim/src/fs/shim_dcache.c#L247)):*
> ```C
> }
> 
> ino_t dentry_ino(struct shim_dentry* dent) {
> ```

Can we just say "inode"? Why saving these two letters?


<!-- Sent from Reviewable.io -->

2021-05-17 10:11 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2374)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 247 at r1](https://reviewable.io/reviews/oscarlab/graphene/2374#-M_gVT36AQ48HBXq7RRm:-M_tmug04T5bfnUwQFuE:b-g7yimx) ([raw file](https://github.com/oscarlab/graphene/blob/97c63e815f46a2892a3cf7305563d115b912d504/LibOS/shim/src/fs/shim_dcache.c#L247)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we just say "inode"? Why saving these two letters?
</blockquote></details>

`dentry_inode` would be suggest this is about an inode _object_. `ino` is the usual name for inode number (as in `stat.st_ino`, `ino_t`). Do you think I should rename this function to `dentry_inode_number` or `dentry_inode_num`?


<!-- Sent from Reviewable.io -->

2021-05-17 14:32 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2374)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/fs/shim_dcache.c, line 247 at r1](https://reviewable.io/reviews/oscarlab/graphene/2374#-M_gVT36AQ48HBXq7RRm:-M_uit5G2Nqtc3G9YYs5:b-4wyjb7) ([raw file](https://github.com/oscarlab/graphene/blob/97c63e815f46a2892a3cf7305563d115b912d504/LibOS/shim/src/fs/shim_dcache.c#L247)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`dentry_inode` would be suggest this is about an inode _object_. `ino` is the usual name for inode number (as in `stat.st_ino`, `ino_t`). Do you think I should rename this function to `dentry_inode_number` or `dentry_inode_num`?
</blockquote></details>

Oh, I thought it's just a shorter version of `inode`, as old C/Linux/POSIX authors like to overabbreviate everything :)

If this is actually a standard name then I'm unblocking, although I don't like it, `dentry_inode_num` would be less confusing IMO :)


<!-- Sent from Reviewable.io -->

2021-05-17 15:56 UTC, dimakuv approved these changes
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2374)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-05-17 22:19 UTC, mkow approved these changes
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2374)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-18 05:50 UTC, merged