[LibOS] Rework `pause` and `nanosleep` syscalls
oscarlab/graphene pull request #2375
Opened 2021-05-14 14:35 UTC by boryspoplawski

## Description of the changes 
Refer to commit messages for description. Each commit is independent so reviewing them separately is recommended.

Fixes #2260 

## How to test this PR? 
`kill11` should not fail anymore. It's unclear if other timeouts are fixed as well, since nobody debugged them yet.

2021-05-14 14:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: 0 of 39 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_fIdrqEVqiMNHSsb4d:-M_fIdrr9FPjwzKyd973:bocvs6) (no related file):*
TODO: check if any LTP tests could be enabled.

---
___
*[Pal/regression/Wait.c, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_fIx3YBLu-ntJMobn0:-M_fIx3YBLu-ntJMobn1:b-8m46kh) ([raw file](https://github.com/oscarlab/graphene/blob/adf6269218dfa80aed276d57121a98e7b13b0f4e/Pal/regression/Wait.c#L63)):*
> ```C
>     if (ret < 0) {
>         pal_printf("DkStreamsWaitEvents did not return any events\n");
>         return -1;
> ```

This always triggered, i.e. `DkStreamsWaitEvents` never actually returned anything. This makes sense, since events created via `DkEventCreate` are not waitable. It's unclear what this tests is supposed to check.
Also I have no idea why it returned -1 (which probably was rounded to 255) and still passed.
___
*[Pal/regression/Yield.c, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_fJMEyDKbGe5HlXlZa:-M_fJMEyDKbGe5HlXlZb:b-tihyqn) ([raw file](https://github.com/oscarlab/graphene/blob/adf6269218dfa80aed276d57121a98e7b13b0f4e/Pal/regression/Yield.c#L4)):*
> ```C
> #include "pal_regression.h"
> 
> /* XXX: What is this even supposed to test?? */
> ```

This was completely useless and even if any of `DkThreadDelayExecution` or `DkThreadResume` was broken, it would still finish and pass.


<!-- Sent from Reviewable.io -->

2021-05-14 15:48 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 2/10)

2021-05-14 16:18 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 3/10)

2021-05-14 17:29 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 4/10)

2021-05-14 18:34 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure, 5/10)

2021-05-14 20:39 UTC, boryspoplawski commented
Jenkins, retest Jenkins-18.04 please (`clone03` from LTP failed with EINTR on pipe read, no idea how, run 65k times without repro)

2021-05-14 20:59 UTC, boryspoplawski commented
> Jenkins, retest Jenkins-18.04 please (`clone03` from LTP failed with EINTR on pipe read, no idea how, run 65k times without repro)

The only explanation I have (but unconfirmed) is that our SGX code injected EINTR, which was not handled (test does not expect it because it cannot happen legitimately and we still lack ERESTARTSYS on most of the syscalls).

2021-05-14 21:05 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (`poll_closed_fd.c` from LibOS regression timed-out, no idea what happened, cannot reproduce)

2021-05-14 21:54 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-14 22:12 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-14 22:55 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-14 23:39 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-14 23:58 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-15 00:40 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-15 01:26 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-15 02:05 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-15 03:20 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-16 00:21 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-16 05:42 UTC, boryspoplawski commented
Jenkins, retest this please (need to trigger it)

2021-05-16 13:33 UTC, boryspoplawski commented
Jenkins, retest this please (need to trigger it)

2021-05-16 14:50 UTC, boryspoplawski commented
Jenkins, retest this please (need to trigger it)

2021-05-16 23:17 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-16 23:47 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-17 00:21 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-17 00:35 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-17 00:57 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-17 01:31 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-20.04 please (need to trigger it)

2021-05-17 07:18 UTC, dimakuv requested changes
> Reviewed 39 of 39 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DONTMERGE" found in commit messages' one-liners (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t7Y5370UmduXrlypW:-M_t7Y549rKZv3EQFO9r:b1lwt33) (no related file):*
> It's no longer needed and will never be (it slept for a given duration
> in a not-signal-aware manner.

Typo in this commit message: please add a closing bracket (on rebase).

---
___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 194 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t81tOD9ZvEJPXtLAS:-M_t81tOD9ZvEJPXtLAT:b-93stsv) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/bookkeep/shim_thread.c#L194)):*
> ```C
>     unlock(&cur_thread->lock);
> 
>     int ret = DkEventCreate(&cur_thread->scheduler_event, /*init_signaled=*/false,
> ```

This was a bug before?
___
*[LibOS/shim/src/sys/shim_sleep.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t8QQt4npPCeuvfCiN:-M_t8QQt4npPCeuvfCiO:b56gji3) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_sleep.c#L40)):*
> ```C
>      * thread or no other thread handles it first.
>      * Ideally, we could have something like the Linux kernel: restart block, which holds a pointer
>      * to a function to be called instead of restarting the syscall.
> ```

Do you want to put a `TODO` here? On the other hand, this is probably a highly unlikely scenario (that an app will have 2+ threads, install a sig handler catchable by both threads, etc). Not blocking.
___
*[LibOS/shim/src/sys/shim_sleep.c, line 93 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t9XdkAApIQj7-n9Qe:-M_t9XdkAApIQj7-n9Qf:b-58w4o1) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_sleep.c#L93)):*
> ```C
>             ret = pal_to_unix_errno(ret);
>             log_error("clock_nanosleep: DkSystemTimeQuery failed with: %d\n", ret);
>             die_or_inf_loop();
> ```

Is this really what we want to do? Why not have an assert here? If you were thinking about a malicious scenario in Linux-SGX PAL, then we should have such a check inside that PAL, not here.
___
*[LibOS/shim/src/sys/shim_wait.c, line 82 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t9wvL76VUwSbzTGu-:-M_t9wvL76VUwSbzTGu0:b-vvsgv5) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_wait.c#L82)):*
> ```C
> 
>     while (!seen) {
>         thread_prepare_wait();
> ```

Why don't we increment the refcount for the current thread? Or it was already done in a caller, so we don't need to bother here?
___
*[LibOS/shim/src/sys/shim_wait.c, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_tA5TJDePcBBhq_u71:-M_tA5TJDePcBBhq_u72:b-3kjh3h) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_wait.c#L89)):*
> ```C
>             break;
>         }
>         int ret = thread_wait(/*timeout_us=*/NULL, /*ignore_pending_signals=*/true);
> ```

ditto (decrement refcount)
___
*[LibOS/shim/src/sys/shim_wait.c, line 182 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_tA7GgDK1OK2h6Rali:-M_tA7GgDK1OK2h6Ralj:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_wait.c#L182)):*
> ```C
>         unlock(&g_process.children_lock);
> 
>         thread_prepare_wait();
> ```

ditto
___
*[LibOS/shim/src/sys/shim_wait.c, line 191 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_tAAQi-ceTLLxlDjaP:-M_tAAQi-ceTLLxlDjaQ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_wait.c#L191)):*
> ```C
>             break;
>         }
>         ret = thread_wait(/*timeout_us=*/NULL, /*ignore_pending_signals=*/false);
> ```

ditto
___
*[LibOS/shim/test/regression/debug_regs-x86_64.gdb, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_tAEJ-E8H1NZF-vG0b:-M_tAEJ-E8H1NZF-vG0c:bpde8iy) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/test/regression/debug_regs-x86_64.gdb#L16)):*
> ```GDB
> # Check RDX register write
> set $rdx = 0x2000200020002000
> continue
> ```

Cool finding!
___
*[Pal/regression/.gitignore, line 45 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_tApkf-H4Ae4fDU7b_:-M_tApkf-H4Ae4fDU7ba:bt52opf) ([raw file](https://github.com/oscarlab/graphene/blob/adf6269218dfa80aed276d57121a98e7b13b0f4e/Pal/regression/.gitignore#L45)):*
> ```ignore
> /Select
> /SendHandle
> /Sleep
> ```

You're my hero!


<!-- Sent from Reviewable.io -->

2021-05-17 13:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DONTMERGE" found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_thread.c, line 194 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t81tOD9ZvEJPXtLAS:-M_uRhT78XgxJg5-BaoL:b-p9hswm) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/bookkeep/shim_thread.c#L194)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This was a bug before?
</blockquote></details>

Kind of, but doesn't really matter that much, most (or maybe even all) callsites use this event just for sleeping, verification whether we need to sleep is done using other means (e.g. `pause` syscall will wait for a signal to be present).
___
*[LibOS/shim/src/sys/shim_sleep.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t8QQt4npPCeuvfCiN:-M_uSF1v442fdrc5IvBx:b4v65h7) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_sleep.c#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you want to put a `TODO` here? On the other hand, this is probably a highly unlikely scenario (that an app will have 2+ threads, install a sig handler catchable by both threads, etc). Not blocking.
</blockquote></details>

I can add an explicit `TODO` here if you want, but I do not have any plans to fix it (as it's not so easy and very low priority atm).
___
*[LibOS/shim/src/sys/shim_sleep.c, line 93 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t9XdkAApIQj7-n9Qe:-M_uSh1gD8vrdsG6Kzx2:bny1ry6) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_sleep.c#L93)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this really what we want to do? Why not have an assert here? If you were thinking about a malicious scenario in Linux-SGX PAL, then we should have such a check inside that PAL, not here.
</blockquote></details>

Possibly, but then `DkSystemTimeQuery` should return `void`. For now it does return an error (at least in theory) so we need to handle it somehow. From what I understood, this can indeed only fail in case of malicious host.
I guess the solution would be to rework `DkSystemTimeQuery` so that it does not return any errors, but I don't want to deal with that in this PR...
___
*[LibOS/shim/src/sys/shim_wait.c, line 82 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t9wvL76VUwSbzTGu-:-M_uU7udDr1yjyCw8egk:b8ij8zw) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_wait.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why don't we increment the refcount for the current thread? Or it was already done in a caller, so we don't need to bother here?
</blockquote></details>

I''m greatly confused, why would we even do that?
___
*[LibOS/shim/src/sys/shim_wait.c, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_tA5TJDePcBBhq_u71:-M_uUS-9APChnpTMiIHI:bhnpq6z) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_wait.c#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (decrement refcount)
</blockquote></details>

But why?


<!-- Sent from Reviewable.io -->

2021-05-17 14:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "DONTMERGE" found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_sleep.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t8QQt4npPCeuvfCiN:-M_uoKs22GvWK8Fthog8:by7436q) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_sleep.c#L40)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I can add an explicit `TODO` here if you want, but I do not have any plans to fix it (as it's not so easy and very low priority atm).
</blockquote></details>

It's Ok, I don't care.
___
*[LibOS/shim/src/sys/shim_wait.c, line 82 at r2](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t9wvL76VUwSbzTGu-:-M_uogox4lm2Jn9-Y7iF:b-5v6qbd) ([raw file](https://github.com/oscarlab/graphene/blob/43492a28c2965c87851c6894172dd1ea9dfd1e9c/LibOS/shim/src/sys/shim_wait.c#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I''m greatly confused, why would we even do that?
</blockquote></details>

Ignore me, sometimes I forget how refcounting and object ownership works :) I just saw that you do `get_thread()` in other places in this PR, but there you do it because you actually add a new owner (like `msg->thread`).


<!-- Sent from Reviewable.io -->

2021-05-17 16:57 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: 6 of 40 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_t7Y5370UmduXrlypW:-M_vFc1J03oKBgq0vhVa:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> It's no longer needed and will never be (it slept for a given duration
> in a not-signal-aware manner.

Typo in this commit message: please add a closing bracket (on rebase).
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-05-17 17:15 UTC, dimakuv requested changes
> Reviewed 1 of 34 files at r3, 33 of 33 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 395 at r4](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_vJdSN8eGoZdeh8RjE:-M_vJdSO33Dy1ZpDPhX_:b4v9vf6) ([raw file](https://github.com/oscarlab/graphene/blob/4e9b60305284067964d526344a0f291a8d2a2455/Pal/src/host/Linux-SGX/enclave_ocalls.c#L395)):*
> ```C
> 
>     /* We should never restart host-level `close` syscall on errors (including `EINTR`), but
>      * `OCALL_CLOSE` does not forward any errors (always returns `0`), so this can only be
> ```

`OCALL_CLOSE` -> `sgx_ocall_close()`. This can be done during final rebase.


<!-- Sent from Reviewable.io -->

2021-05-17 17:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: 39 of 40 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 395 at r4](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_vJdSN8eGoZdeh8RjE:-M_vO3F7B7krIwt1fIGC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/4e9b60305284067964d526344a0f291a8d2a2455/Pal/src/host/Linux-SGX/enclave_ocalls.c#L395)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`OCALL_CLOSE` -> `sgx_ocall_close()`. This can be done during final rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-17 18:32 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-17 19:11 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-17 19:26 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_vmbFx2G6ujk9RsHZo:-M_vmbFx2G6ujk9RsHZp:brfi2wl) (no related file):*
> sgx_ocall_open

You have the same typo in the commit message... Should be `sgx_ocall_close`

---
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 395 at r4](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_vJdSN8eGoZdeh8RjE:-M_vmf8H9j4Gn3CYNnd-:brmekd2) ([raw file](https://github.com/oscarlab/graphene/blob/4e9b60305284067964d526344a0f291a8d2a2455/Pal/src/host/Linux-SGX/enclave_ocalls.c#L395)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. You have `sgx_ocall_open`, but should be `sgx_ocall_close`.


<!-- Sent from Reviewable.io -->

2021-05-17 19:55 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: 39 of 40 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_vmbFx2G6ujk9RsHZo:-M_vtInh4AnimQpoy1hu:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> sgx_ocall_open

You have the same typo in the commit message... Should be `sgx_ocall_close`
</blockquote></details>

Done.

---
___
*[Pal/src/host/Linux-SGX/enclave_ocalls.c, line 395 at r4](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_vJdSN8eGoZdeh8RjE:-M_vtGE_AC-GEo7eMnfL:b-vp59nu) ([raw file](https://github.com/oscarlab/graphene/blob/4e9b60305284067964d526344a0f291a8d2a2455/Pal/src/host/Linux-SGX/enclave_ocalls.c#L395)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done. You have `sgx_ocall_open`, but should be `sgx_ocall_close`.
</blockquote></details>

Oops, copy paste fail.
Done.


<!-- Sent from Reviewable.io -->

2021-05-17 20:13 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-05-17 20:20 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-17 21:02 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-17 22:32 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-18 00:50 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-18 01:31 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-18 01:56 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-05-18 01:56 UTC, mkow requested changes
> Reviewed 13 of 39 files at r1, 1 of 34 files at r3, 32 of 33 files at r4, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_sleep.c, line 76 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_x5KPb1Hc-ly5q690-:-M_x5KPb1Hc-ly5q6900:bg5tw6v) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/LibOS/shim/src/sys/shim_sleep.c#L76)):*
> ```C
> long shim_do_clock_nanosleep(clockid_t clock_id, int flags, struct __kernel_timespec* req,
>                              struct __kernel_timespec* rem) {
>     /* In Graphene all cloks are the same. */
> ```

`cloks` -> `clocks`
___
*[LibOS/shim/src/sys/shim_sleep.c, line 95 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_x7Do2BFl9hcCIqKHb:-M_x7Do2BFl9hcCIqKHc:b8bwhgt) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/LibOS/shim/src/sys/shim_sleep.c#L95)):*
> ```C
>             die_or_inf_loop();
>         }
>         if (timeout_us < current_time) {
> ```

`<` -> `<=`
___
*[Pal/src/host/Linux/db_events.c, line 85 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_xA5o5BftT3LMC2M7q:-M_xA5o5BftT3LMC2M7r:b-lvtt0h) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/Pal/src/host/Linux/db_events.c#L85)):*
> ```C
>             diff = 0;
>         }
>         assert(ret != -PAL_ERROR_TRYAGAIN || diff == 0);
> ```

Huh, good catch. Time for somehow strongly typing the error codes maybe?


<!-- Sent from Reviewable.io -->

2021-05-18 22:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: 39 of 41 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_fIdrqEVqiMNHSsb4d:-Ma0aUdI8yU5MDksTmhk:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: check if any LTP tests could be enabled.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/sys/shim_sleep.c, line 76 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_x5KPb1Hc-ly5q690-:-Ma-W7Cg3u511DQLETNE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/LibOS/shim/src/sys/shim_sleep.c#L76)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`cloks` -> `clocks`
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_sleep.c, line 95 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_x7Do2BFl9hcCIqKHb:-Ma-WVd9EQmqxDo61r2G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/LibOS/shim/src/sys/shim_sleep.c#L95)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`<` -> `<=`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_events.c, line 85 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_xA5o5BftT3LMC2M7q:-Ma-WXS15n5k9cGvCL1U:bp00jax) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/Pal/src/host/Linux/db_events.c#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, good catch. Time for somehow strongly typing the error codes maybe?
</blockquote></details>

The only thing I can think of is having `struct PAL_ERROR {dummy}` and then `DEFINE PAL_ERROR_TRYAGAIN ((struct PAL_ERROR*)42)` and make functions return `struct PAL_ERROR*` instead of `int`. This could be douable, since we moved to out arguments and return **only** errors directly, but oh boy it's ugly.


<!-- Sent from Reviewable.io -->

2021-05-18 22:49 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux/db_events.c, line 85 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_xA5o5BftT3LMC2M7q:-Ma0dcev-TRL5oHS2AVS:b-gnuugf) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/Pal/src/host/Linux/db_events.c#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The only thing I can think of is having `struct PAL_ERROR {dummy}` and then `DEFINE PAL_ERROR_TRYAGAIN ((struct PAL_ERROR*)42)` and make functions return `struct PAL_ERROR*` instead of `int`. This could be douable, since we moved to out arguments and return **only** errors directly, but oh boy it's ugly.
</blockquote></details>

Yeah... stupid C :/


<!-- Sent from Reviewable.io -->

2021-05-18 23:21 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux/db_events.c, line 85 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_xA5o5BftT3LMC2M7q:-Ma0lrM91GN7UBNWXDBj:b-ye2frv) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/Pal/src/host/Linux/db_events.c#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah... stupid C :/
</blockquote></details>

I played with this a bit and it actually seems doable to some extent with `-Wall`, `-Wextra` and `-Werror`, which we already use. See https://godbolt.org/z/zMvb3Mqar.


<!-- Sent from Reviewable.io -->

2021-05-18 23:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux/db_events.c, line 85 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_xA5o5BftT3LMC2M7q:-Ma0sh8ZE9xtThCoeDv4:b-u3m0jw) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/Pal/src/host/Linux/db_events.c#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I played with this a bit and it actually seems doable to some extent with `-Wall`, `-Wextra` and `-Werror`, which we already use. See https://godbolt.org/z/zMvb3Mqar.
</blockquote></details>

`enum-conversion` is available only in gcc >= 10.


<!-- Sent from Reviewable.io -->

2021-05-19 00:08 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[Pal/src/host/Linux/db_events.c, line 85 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_xA5o5BftT3LMC2M7q:-Ma0wO512Ai6GdDHGicO:bk145l5) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/Pal/src/host/Linux/db_events.c#L85)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`enum-conversion` is available only in gcc >= 10.
</blockquote></details>

So, we just need to ensure that at least one pipeline in CI is using it. Which probably is not yet true, but doesn't sound like an insurmountable obstacle.


<!-- Sent from Reviewable.io -->

2021-05-19 00:20 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-Ma0zGN_AtPUZGfltzfV:-Ma0zGNa1nf9ku8SpPvM:b3n44gn) (no related file):*
@dimakuv @mkow I've run this PR ~15 times on jenkins and observed no failures/timeouts, so from now on treat every timeout as something new that needs to be debugged.

---
___
*[Pal/src/host/Linux/db_events.c, line 85 at r7](https://reviewable.io/reviews/oscarlab/graphene/2375#-M_xA5o5BftT3LMC2M7q:-Ma0zTy85lI0hLzLwxMO:b-a2vfkl) ([raw file](https://github.com/oscarlab/graphene/blob/b59ce565dd6685d1c89aa770a1a02addd7c6fe18/Pal/src/host/Linux/db_events.c#L85)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, we just need to ensure that at least one pipeline in CI is using it. Which probably is not yet true, but doesn't sound like an insurmountable obstacle.
</blockquote></details>

Yup, should be doable, someday. (ubuntu20.04 uses gcc9.3)


<!-- Sent from Reviewable.io -->

2021-05-19 00:20 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure; waiting for approvals)

2021-05-19 01:04 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure; waiting for approvals)

2021-05-19 06:08 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04 please (`test_300_socket_tcp_msg_peek` LibOS test failed, with `AssertionError: '[server] done' not found`)

2021-05-19 06:12 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2375)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2375#-Ma0zGN_AtPUZGfltzfV:-Ma2EXAvEzPaa3_u3cvV:b9e2c5) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@dimakuv @mkow I've run this PR ~15 times on jenkins and observed no failures/timeouts, so from now on treat every timeout as something new that needs to be debugged.
</blockquote></details>

I've seen not a timeout but a failure on `tcp_msg_peek` LibOS regression test. Not sure if this is relevant to this PR... I'm fine with merging the PR and then checking whether this test is reproducible.

---


<!-- Sent from Reviewable.io -->

2021-05-19 10:35 UTC, merged