[meson] Compile Pal/Linux
oscarlab/graphene pull request #2376
Opened 2021-05-14 14:56 UTC by woju

## Description of the changes 

This moves compiling direct PAL's `libpal.so` from Makefiles into meson.

Makefile.am is intentionally left alone, because it is needed to compile `.lib/` (`Pal/lib`), which is not in scope for this PR.

This PR depends on #2351.
See also: #2289.

## How to test this PR? 

Build should succeed, tests should pass.

2021-05-17 07:46 UTC, dimakuv reviewed
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[meson.build, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2376#-M_tGOgx6ks61GgV6ecv:-M_tGOgx6ks61GgV6ecw:bruartn) ([raw file](https://github.com/oscarlab/graphene/blob/5e67f50d04ecf3a0107f8e711150543505344fce/meson.build#L60)):*
> ```Meson
> if not cc.has_multi_arguments(cflags_stack_protector)
>     cflags_stack_protector = '-fno-stack-protector'
> endif
> ```

Btw, is there a way to add "build" flags and choices inside the final executable of Graphene? It would be cool to have something like `graphene-direct --version` which would give the version, month/year, and a set of flags with which it was built. I don't know how this is typically implemented.


<!-- Sent from Reviewable.io -->

2021-05-17 12:00 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[meson.build, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2376#-M_tGOgx6ks61GgV6ecv:-M_u8bndDLbzURzEEOMj:buwy5b8) ([raw file](https://github.com/oscarlab/graphene/blob/5e67f50d04ecf3a0107f8e711150543505344fce/meson.build#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, is there a way to add "build" flags and choices inside the final executable of Graphene? It would be cool to have something like `graphene-direct --version` which would give the version, month/year, and a set of flags with which it was built. I don't know how this is typically implemented.
</blockquote></details>

It's typically done by having some header generated with all the config (like linux' `CONFIG_WHATEVER` or autotools-style `HAVE_` or `WITH_`), and somewhere inbeetween an `#define CONFIG_CFLAGS "..."` (it's generated by the config system, and the config system knows the flags). Then you can `prinf("%s\n", CONFIG_CFLAGS)` to your heart's content. `--version` probably shouldn't contain all the flags (just `graphene-direct X.Y.Z`, because it might be parsed), but `--fullversion` is definitely possible.

I could do this now, because I process `pal_loader` to `graphene-direct` with meson already, but not as part of this PR. Instead, could you please comment on #1053 (RFC: graphene invocation)?


<!-- Sent from Reviewable.io -->

2021-05-17 12:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[meson.build, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2376#-M_tGOgx6ks61GgV6ecv:-M_uDEpI7hdUoHa3e9qU:bk9qef3) ([raw file](https://github.com/oscarlab/graphene/blob/5e67f50d04ecf3a0107f8e711150543505344fce/meson.build#L60)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's typically done by having some header generated with all the config (like linux' `CONFIG_WHATEVER` or autotools-style `HAVE_` or `WITH_`), and somewhere inbeetween an `#define CONFIG_CFLAGS "..."` (it's generated by the config system, and the config system knows the flags). Then you can `prinf("%s\n", CONFIG_CFLAGS)` to your heart's content. `--version` probably shouldn't contain all the flags (just `graphene-direct X.Y.Z`, because it might be parsed), but `--fullversion` is definitely possible.

I could do this now, because I process `pal_loader` to `graphene-direct` with meson already, but not as part of this PR. Instead, could you please comment on #1053 (RFC: graphene invocation)?
</blockquote></details>

Done. Thanks for explanations.


<!-- Sent from Reviewable.io -->

2021-05-27 12:55 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: 5 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[Pal/src/host/Linux/meson.build, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahoiav5x4Fk0BK6JHk:-MahsMuj95RBAMr-CXk1:b31mjad) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I noticed that you don't produce a `static_library` anymore (`libpal.a`). This static library was produced by our Makefiles, and I will actually need it in my work ("LibOS + PAL + common in one single binary"). Could you add this? You also don't produce the static library `libsysdb.a` in the PR on LibOS meson build (already merged), so maybe do this in a separate PR for all Graphene parts.
</blockquote></details>

Apart from `shared_library()` meson has `static_library()`, `both_libraries()` and `library()`, the last one is either shared or static and depends on configure-time switch to choose. Would `both_libraries()` be OK for you?


<!-- Sent from Reviewable.io -->

2021-05-27 13:09 UTC, dimakuv requested changes
> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahuCva1KvA5H2qvQMy:-MahuCvb1kB4hEyfK_mY:b-ebnqqw) (no related file):*
Why didn't you remove `Pal/src/host/Linux/Makefile.am`?

---
___
*[Pal/include/meson.build, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahsLbE0Q-VLkBgPo8R:-MahsLbF6M7u1R-8KItR:brgxgbx) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L5)):*
> ```Meson
>         '.',
>         'pal',
>         'arch',
> ```

This one doesn't make sense. There are no files under `Pal/include/arch`, only under `Pal/include/arch/<cpu_family>`. Please remove.
___
*[Pal/include/meson.build, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahspf-CW4nlN1T1tol:-Mahspf-CW4nlN1T1tom:baqihg4) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L7)):*
> ```Meson
>         'arch',
>         join_paths('arch', host_machine.cpu_family()),
>         '../src',
> ```

Why this? Shouldn't we add this in the `Pal/src/meson.build` file's `include_dirs`?

On the other hand, all these header files are currently in random places, and I had a plan to fix them (half of them will be removed anyway as part of my "LibOS + PAL + common in one binary" -- I will remove almost all ELF handling).
___
*[Pal/include/meson.build, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahtK0lCph371oSot1y:-MahtK0lCph371oSot1z:bpa003c) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L9)):*
> ```Meson
>         '../src',
>     ),
>     includes_common,
> ```

Adding `includes_common` to `includes_pal_common` feels strange to me. Shouldn't we better do it in the final `libpal_direct = shared_library('pal' ...)` target? This feels much more natural: to build `libpal.so` we need PAL includes, common includes, and `.` includes.
___
*[Pal/src/host/Linux/meson.build, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahuWdH2h_JogxofyMC:-MahuWdH2h_JogxofyMD:b-h4tihl) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L27)):*
> ```Meson
> foreach i : pal_direct_sources_arch
>     pal_direct_sources += join_paths('arch', host_machine.cpu_family(), i)
> endforeach
> ```

Why do you collect `pal_direct_sources_arch` here and not in `arch/<cpu_family>/meson.build`? See my other comment as well.
___
*[Pal/src/host/Linux/meson.build, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahoiav5x4Fk0BK6JHk:-Mahugja5a3yLjN21EDX:b7n5y1a) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Apart from `shared_library()` meson has `static_library()`, `both_libraries()` and `library()`, the last one is either shared or static and depends on configure-time switch to choose. Would `both_libraries()` be OK for you?
</blockquote></details>

Yes, `both_libraries` will be awesome. The more I learn about Meson, the more I love it!
___
*[Pal/src/host/Linux/meson.build, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahv-3Q3rS9zOnFjvKA:-Mahv-3Q3rS9zOnFjvKB:bbdmpql) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L41)):*
> ```Meson
> 
> libpal_direct = shared_library('pal',
>     pal_sources_common,
> ```

You seem to have the notation `pal_blabla_sources` but for the Common library, you have `pal_sources_blabla`. Could you unify and replace here with `pal_common_sources`?
___
*[Pal/src/host/Linux/meson.build, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahvT7lC7klB1tazHEq:-MahvT7lC7klB1tazHEr:bnp6x6u) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L49)):*
> ```Meson
>         include_directories(
>             '../../../include/arch/@0@/Linux'.format(host_machine.cpu_family()),
>             '../../../include/host/Linux-common',
> ```

This looks very ugly. Do we want to introduce a new meson variable that holds the OS? We would specify `os=Linux` during meson configure, and then we'll replace with `os` here. But I'm not sure if this is too cumbersome. I'm not blocking.
___
*[Pal/src/host/Linux/meson.build, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahw7oG5IYV64IHK2ao:-Mahw7oHBUvvOQ1-Myt0:b-2emkva) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L58)):*
> ```Meson
> 
>         '-DHOST_TYPE=Linux',
>         '-DLINUX',
> ```

This one is not used anywhere, can safely remove.
___
*[Pal/src/host/Linux/arch/x86_64/meson.build, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahuPyf6lswmIbs4Fbs:-MahuPyf6lswmIbs4Fbt:b-112k6n) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/arch/x86_64/meson.build#L1)):*
> ```Meson
> pal_direct_lds = join_paths(meson.current_source_dir(), 'pal.lds')
> ```

Why don't you collect `pal_direct_sources_arch` here? Looks like a more appropriate place.


<!-- Sent from Reviewable.io -->

2021-05-27 14:01 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahuCva1KvA5H2qvQMy:-Mai-Cxy9j-iK4puNEdF:b-eiq5pu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why didn't you remove `Pal/src/host/Linux/Makefile.am`?
</blockquote></details>

Because it is needed for `.lib/` aka `graphene-lib`. IDK why, I didn't feel like disentangling this one here.

---
___
*[Pal/include/meson.build, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahsLbE0Q-VLkBgPo8R:-Mai-sl90zDMaJ4UF0AQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This one doesn't make sense. There are no files under `Pal/include/arch`, only under `Pal/include/arch/<cpu_family>`. Please remove.
</blockquote></details>

Done.
___
*[Pal/include/meson.build, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahspf-CW4nlN1T1tol:-Mai-uxS3d0Zo8hKCG9n:b-w7r47m) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L7)):*
> Why this? Shouldn't we add this in the Pal/src/meson.build file's include_dirs?

There is no include_dirs in this file, but there are common `.c` files *and* common `.h` files with the catch that they don't match the `.c` files (at least by name). I would very much prefer to just move the `.h` files here (to `Pal/include`). If you'd like, I can `git mv Pal/src/*.h Pal/include/` in this PR.
___
*[Pal/include/meson.build, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahtK0lCph371oSot1y:-Mai119R2kJD2WHpjxyh:b-6v8ttr) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Adding `includes_common` to `includes_pal_common` feels strange to me. Shouldn't we better do it in the final `libpal_direct = shared_library('pal' ...)` target? This feels much more natural: to build `libpal.so` we need PAL includes, common includes, and `.` includes.
</blockquote></details>

`includes_common` will go away when I'll rewrite `common/` to meson. Then I'll use `declare_dependency(include_directories:)` exactly for this.

"Dependencies" in meson is a concept of modular targets. A target may be understood as list of sources, cflags, include dirs and libraries to link. So a "dependency" is a subset of any of those list. Usually it's library + its `include_directories` (but this might get way more complicated than that).

So if it's true that `includes_common` is used iff there is linking against common lib, then I'd be very happy to remove it from here. I can even move it now, to `Pal/src/host/Linux/meson.build`, like that:

```meson
libgraphene_pal_direct = declare_dependency(
    dependencies: cc.find_library('graphene-lib',
        dirs: join_paths(meson.current_source_dir(), '.lib')),
    include_dirs: includes_common,
)
```
and possibly similar change in LibOS.

Which variant do you prefer?
___
*[Pal/src/host/Linux/meson.build, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahuWdH2h_JogxofyMC:-Mai4QCpEaxCED__m97k:b-e2ehdf) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you collect `pal_direct_sources_arch` here and not in `arch/<cpu_family>/meson.build`? See my other comment as well.
</blockquote></details>

I wanted to do that, but we had a similar discussion in `LibOS`, and @boryspoplawski and @mkow wanted arch-specific files to be done this way, IIUC they wanted list of all files to be in a single `meson.build` file. So I changed here for consistency with `LibOS/`.
___
*[Pal/src/host/Linux/meson.build, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahoiav5x4Fk0BK6JHk:-Mai4aaF8F6mGy3jucJ5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, `both_libraries` will be awesome. The more I learn about Meson, the more I love it!
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/meson.build, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahv-3Q3rS9zOnFjvKA:-Mai6a5R2kFB3kCacmq2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You seem to have the notation `pal_blabla_sources` but for the Common library, you have `pal_sources_blabla`. Could you unify and replace here with `pal_common_sources`?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/meson.build, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahvT7lC7klB1tazHEq:-Mai6dF0Cf-xNwr115ei:bl85bzz) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks very ugly. Do we want to introduce a new meson variable that holds the OS? We would specify `os=Linux` during meson configure, and then we'll replace with `os` here. But I'm not sure if this is too cumbersome. I'm not blocking.
</blockquote></details>

I think this is another symptom of the mess in `.h` files being everywhere, and I'd postpone this to when we'll fix the headers and includes. Then I expect this will magically fix itself. :)
___
*[Pal/src/host/Linux/meson.build, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahw7oG5IYV64IHK2ao:-Mai4j9g0stSdwoH9wMA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This one is not used anywhere, can safely remove.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/arch/x86_64/meson.build, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahuPyf6lswmIbs4Fbs:-Mai7EMyCLgkiPu-PrgF:byz4vxa) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/arch/x86_64/meson.build#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why don't you collect `pal_direct_sources_arch` here? Looks like a more appropriate place.
</blockquote></details>

see other


<!-- Sent from Reviewable.io -->

2021-05-27 20:45 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahuCva1KvA5H2qvQMy:-MajZAfW-_fNgquf3J6L:b32w0x) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because it is needed for `.lib/` aka `graphene-lib`. IDK why, I didn't feel like disentangling this one here.
</blockquote></details>

OK

---
___
*[Pal/include/meson.build, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahspf-CW4nlN1T1tol:-MajZLVf3QkUMGAJniue:b-wumqhm) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L7)):*
>  If you'd like, I can git mv Pal/src/*.h Pal/include/ in this PR.

Yes, I think it will make sense to do in this PR.
___
*[Pal/include/meson.build, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-MahtK0lCph371oSot1y:-MajZYFw1puJGgWKFQqA:b5utt3v) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`includes_common` will go away when I'll rewrite `common/` to meson. Then I'll use `declare_dependency(include_directories:)` exactly for this.

"Dependencies" in meson is a concept of modular targets. A target may be understood as list of sources, cflags, include dirs and libraries to link. So a "dependency" is a subset of any of those list. Usually it's library + its `include_directories` (but this might get way more complicated than that).

So if it's true that `includes_common` is used iff there is linking against common lib, then I'd be very happy to remove it from here. I can even move it now, to `Pal/src/host/Linux/meson.build`, like that:

```meson
libgraphene_pal_direct = declare_dependency(
    dependencies: cc.find_library('graphene-lib',
        dirs: join_paths(meson.current_source_dir(), '.lib')),
    include_dirs: includes_common,
)
```
and possibly similar change in LibOS.

Which variant do you prefer?
</blockquote></details>

It's ok, then just leave it for now and do the dependency in the PR where you will rewrite common lib to meson.


<!-- Sent from Reviewable.io -->

2021-05-28 10:32 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: 18 of 24 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[Pal/include/meson.build, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahspf-CW4nlN1T1tol:-MamV56RB5F0hFsQPihZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

>  If you'd like, I can git mv Pal/src/*.h Pal/include/ in this PR.

Yes, I think it will make sense to do in this PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-28 11:03 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: 17 of 25 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux/meson.build, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahoiav5x4Fk0BK6JHk:-MamaM8m5sAffIbOCwSi:bxg81nf) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/src/host/Linux/meson.build#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, `both_libraries` needs meson>=0.46, and we target 0.45 for bionic. So I have a workaround.


<!-- Sent from Reviewable.io -->

2021-05-31 07:24 UTC, dimakuv submitted a review, later dismissed
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Pal/include/meson.build, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mahspf-CW4nlN1T1tol:-Mb0IVPy9zojntEg_DN8:b-fmamnk) ([raw file](https://github.com/oscarlab/graphene/blob/e09eac7f000833babd8de4865fa299db4813ec90/Pal/include/meson.build#L7)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, one more step closer to header-file sanity in Graphene :)


<!-- Sent from Reviewable.io -->

2021-05-31 22:16 UTC, boryspoplawski requested changes
> Reviewed 5 of 15 files at r1, 10 of 14 files at r2, 1 of 3 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 8 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[meson.build, line 51 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb2GOWx8SWWWaJJmHn-:-Mb2GOWyBmxLbF3TLIru:b-y6yxo6) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/meson.build#L51)):*
> ```Meson
> 
>     cc.get_supported_arguments(
>         '-Wtrampoline',
> ```

Could you stash a fix for this typo in this PR? It should be `-Wtrampolines`.
___
*[Pal/src/host/Linux/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3O9X05fUl6iYvDWuC:-Mb3O9X05fUl6iYvDWuD:b-qs6ssk) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L1)):*
> ```Meson
> pal_direct_sources = files(
> ```

Why this is called `pal_direct_sources`, not `pal_sources`? Is it because these variables are visible in all meson files, even higher level, so we would have conflicts on all Pals?
___
*[Pal/src/host/Linux/meson.build, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3NkFq5jFbmN4sqKi9:-Mb3NkFq5jFbmN4sqKiA:b-28ace5) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L29)):*
> ```Meson
> endforeach
> 
> subdir('arch')
> ```

see `arch/x86_64/meson.build`
___
*[Pal/src/host/Linux/meson.build, line 61 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3Tq_09Yt6psyHW4cn:-Mb3Tq_09Yt6psyHW4co:b-4hbdzr) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L61)):*
> ```Meson
>             '-DHOST_TYPE=Linux',
> 
>             '-DPIC',
> ```

Please remove this
___
*[Pal/src/host/Linux/meson.build, line 62 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3TspY-vPPp8ovxlKt:-Mb3TspY-vPPp8ovxlKu:b-u6exap) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L62)):*
> ```Meson
> 
>             '-DPIC',
>             '-DSHARED',
> ```

Please remove this. Note that you might need to flatten ifdef in "Pal/regression/crt_init/arch/x86_64/user_start.S"
___
*[Pal/src/host/Linux/meson.build, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3U-c-5bx05U6DNJa2:-Mb3U-c-5bx05U6DNJa3:b4wrtd1) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L63)):*
> ```Meson
>             '-DPIC',
>             '-DSHARED',
>             '-Wa,--noexecstack',
> ```

Could you add something like this in Libos meson.build? Our loading code ignores GNU_STACK completely, but just for the sake of sanity please add it.
___
*[Pal/src/host/Linux/arch/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3Nf2V7ZipSW7cN6yN:-Mb3Nf2W58zBNAHzQ2RV:byrq2m7) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/arch/meson.build#L1)):*
> ```Meson
> subdir(host_machine.cpu_family())
> ```

see below
___
*[Pal/src/host/Linux/arch/x86_64/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3NWZ_40KcMDogpgMg:-Mb3NWZaBGwFji3QPQjs:b-8fmih) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/arch/x86_64/meson.build#L1)):*
> ```Meson
> pal_direct_lds = join_paths(meson.current_source_dir(), 'pal.lds')
> ```

Why this is here not in `Pal/src/host/Linux/meson.build`?


<!-- Sent from Reviewable.io -->

2021-06-01 01:33 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: 23 of 26 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb4Bn3-4Ev_bDd53B7t:-Mb4Bn3-4Ev_bDd53B7u:b-1vkr6q) (no related file):*
I don't think that creating a separate commit for "[Pal/Linux] Get rid of -DSHARED and -DPIC" is necessary, it can be stashed with general PAL meson compilation commit.

---


<!-- Sent from Reviewable.io -->

2021-06-01 08:31 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 9 unresolved discussions (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-06-01 15:47 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: 23 of 26 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb4Bn3-4Ev_bDd53B7t:-Mb6x4Bq6lWDHI_j9ouJ:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think that creating a separate commit for "[Pal/Linux] Get rid of -DSHARED and -DPIC" is necessary, it can be stashed with general PAL meson compilation commit.
</blockquote></details>

Done.

---
___
*[meson.build, line 51 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb2GOWx8SWWWaJJmHn-:-Mb3fn2BCI9Pz1ieAYmk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/meson.build#L51)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you stash a fix for this typo in this PR? It should be `-Wtrampolines`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3O9X05fUl6iYvDWuC:-Mb3frtcD0-nNhqxmv2E:bb6gxwk) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is called `pal_direct_sources`, not `pal_sources`? Is it because these variables are visible in all meson files, even higher level, so we would have conflicts on all Pals?
</blockquote></details>

Yes, they're visible. All `meson.build` files are recursively flattened to a single namespace, in a DFS manner specified by `subdir()`s. So apart from very simple things like `i` or `conf`, I prefer to avoid name collisions if I don't intend to refer to the same variable. In this case, there may be `pal_skeleton_sources`. In SGX case there are two lists, for trusted and untrusted PAL, and there is no `arch/` directory, so no need to append to any of those lists.
___
*[Pal/src/host/Linux/meson.build, line 61 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3Tq_09Yt6psyHW4cn:-Mb3eGHf2v8T2qPuMDmJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L61)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove this
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/meson.build, line 62 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3TspY-vPPp8ovxlKt:-Mb6wq2Z-TjHsSWxQ2bn:bwlz3im) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L62)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please remove this. Note that you might need to flatten ifdef in "Pal/regression/crt_init/arch/x86_64/user_start.S"
</blockquote></details>

I'll leave this out, flags here don't affect the compilation of `user_start.S`.
___
*[Pal/src/host/Linux/meson.build, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3U-c-5bx05U6DNJa2:-Mb3ehT78lEz30aPfSY3:b-swowch) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L63)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you add something like this in Libos meson.build? Our loading code ignores GNU_STACK completely, but just for the sake of sanity please add it.
</blockquote></details>

Done in project-wide `meson.build`.
___
*[Pal/src/host/Linux/arch/x86_64/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3NWZ_40KcMDogpgMg:-Mb3f573193RJLgvIdmX:b-vlzckd) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/arch/x86_64/meson.build#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is here not in `Pal/src/host/Linux/meson.build`?
</blockquote></details>

Because the file lives here. Without this, it's not greppable, where this file is used.


<!-- Sent from Reviewable.io -->

2021-06-01 16:11 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 9 unresolved discussions (waiting on @boryspoplawski and @woju)



<!-- Sent from Reviewable.io -->

2021-06-01 16:26 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 3 unresolved discussions (waiting on @woju)

___
*[Pal/src/host/Linux/arch/x86_64/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3NWZ_40KcMDogpgMg:-Mb7NyxwB6iF3JuqAzUM:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/arch/x86_64/meson.build#L1)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Because the file lives here. Without this, it's not greppable, where this file is used.
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2021-06-01 17:02 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: 23 of 26 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/meson.build, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3NkFq5jFbmN4sqKi9:-Mb7WiuD67bl87wsDg4Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/meson.build#L29)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

see `arch/x86_64/meson.build`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/arch/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3Nf2V7ZipSW7cN6yN:-Mb7Wjsv17m4NwXvu4yp:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/arch/meson.build#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

see below
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/arch/x86_64/meson.build, line 1 at r4](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb3NWZ_40KcMDogpgMg:-Mb7Wkc841_zpwspkhdr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fefd31bf96509afc5dcdc284b3d435cbd90f55cb/Pal/src/host/Linux/arch/x86_64/meson.build#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-01 18:34 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-01 18:40 UTC, dimakuv commented
Jenkins, retest Jenkins-SGX-18.04-apps please (looks like "general timeout exceeded", happened during Apache test)

2021-06-01 19:24 UTC, boryspoplawski commented
Jenkins, retest Jenkins-SGX-18.04-apps please ("general timeout exceeded", faulty node, turned it off)

2021-06-02 10:33 UTC, mkow requested changes
> Reviewed 4 of 15 files at r1, 9 of 14 files at r2, 1 of 3 files at r3, 7 of 8 files at r4, 2 of 3 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb9TYI97p6QOgi2I2dz:-Mb9TYI97p6QOgi2I2e-:b-4cz0qo) (no related file):*
`meson` -> `Meson` (in the commit messages)

---
___
*[Pal/src/host/Linux/meson.build, line 25 at r7](https://reviewable.io/reviews/oscarlab/graphene/2376#-MbBFsHi6HHzZ9PyjThO:-MbBFsHi6HHzZ9PyjThP:b-dkyll1) ([raw file](https://github.com/oscarlab/graphene/blob/2ebcb280d7036d3b5e28400f5520673274c2e94b/Pal/src/host/Linux/meson.build#L25)):*
> ```Meson
>     'pal_start.S',
> ]
> foreach i : pal_direct_sources_arch
> ```

`i` -> `src`


<!-- Sent from Reviewable.io -->

2021-06-02 16:32 UTC, mkow reviewed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-06-02 16:39 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: 24 of 28 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2376#-Mb9TYI97p6QOgi2I2dz:-MbC_t2CBhmaE9k3aYpd:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`meson` -> `Meson` (in the commit messages)
</blockquote></details>

Done.

---
___
*[Pal/src/host/Linux/meson.build, line 25 at r7](https://reviewable.io/reviews/oscarlab/graphene/2376#-MbBFsHi6HHzZ9PyjThO:-MbC_JRw2VoQZRCyrrDA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2ebcb280d7036d3b5e28400f5520673274c2e94b/Pal/src/host/Linux/meson.build#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`i` -> `src`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-02 19:22 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-06-02 19:26 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-06-02 20:18 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r7, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2376)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-02 20:19 UTC, merged