WIP: Ensure dentry type and permissions are always stored
oscarlab/graphene pull request #2379
Opened 2021-05-17 10:49 UTC by pwmarcz

(Based on unmerged PRs)

This change is in preparation for bigger refactoring: simplifying directory handles, `getdents` and `getdents64`. It also unblocks changing the mount semantics.

In principle, this refactoring could be taken further:
* remove `mode()` callback
* remove `DENTRY_DIRECTORY`, `DENTRY_ISLINK` flags, as they're redundant now
* remove various `type` fields throughout the code

However, when I tried to do any of these, the change snowballed. The important part is that the `type` field is available as part of dentry, because it unblocks many other simplifications in the code.

2021-05-19 11:54 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 375 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3RJCpDdztHRrpzN5X:-Ma3RJCqBiwME5L5225W:b-28wcu0) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/shim_dcache.c#L375)):*
> ```C
> static void dump_dentry_mode(struct print_buf* buf, mode_t type, mode_t perm) {
>     buf_printf(buf, "%06o ", type | perm);
>     
> ```

Please remove whitespace
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 109 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3SwuG0Nq0_WFT_2CY:-Ma3SwuHDXReo9IcTKST:belpfn4) ([raw file](https://github.com/oscarlab/graphene/blob/3a44389825e5b5c250e4a9dd5afd955c38622749/LibOS/shim/src/fs/proc/ipc-thread.c#L109)):*
> ```C
> }
> 
> static int proc_ipc_thread_link_open(struct shim_handle* hdl, const char* name, int flags) {
> ```

Why was this open callback removed? It was never used?
___
*[LibOS/shim/src/fs/proc/thread.c, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3T3lh-ZNklWg44_iW:-Ma3T3lh-ZNklWg44_iX:b-f57whn) ([raw file](https://github.com/oscarlab/graphene/blob/3a44389825e5b5c250e4a9dd5afd955c38622749/LibOS/shim/src/fs/proc/thread.c#L139)):*
> ```C
> }
> 
> static int proc_thread_link_open(struct shim_handle* hdl, const char* name, int flags) {
> ```

ditto (why removed?)


<!-- Sent from Reviewable.io -->

2021-05-19 14:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 375 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3RJCpDdztHRrpzN5X:-Ma3_8GY2WxUXcmvrBV1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/shim_dcache.c#L375)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove whitespace
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 109 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3SwuG0Nq0_WFT_2CY:-Ma3nqHD5ivDNF--wSci:blvext0) ([raw file](https://github.com/oscarlab/graphene/blob/3a44389825e5b5c250e4a9dd5afd955c38622749/LibOS/shim/src/fs/proc/ipc-thread.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why was this open callback removed? It was never used?
</blockquote></details>

This is a callback for symlinks (`/proc/xxx/{cwd,exe,root}`). You are not able to `open()` them directly. This `open` implementation attempted to open the target file, but as long as they're properly marked as symlinks (with `S_IFLNK`), the filesystem will use the `follow_link` operation.

(And actually `ipc-thread.c` seems pretty broken right now... I created issue #2385 for this).
___
*[LibOS/shim/src/fs/proc/thread.c, line 139 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3T3lh-ZNklWg44_iW:-Ma3sG_r2YdekozRXIan:b-l37r56) ([raw file](https://github.com/oscarlab/graphene/blob/3a44389825e5b5c250e4a9dd5afd955c38622749/LibOS/shim/src/fs/proc/thread.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (why removed?)
</blockquote></details>

Same as above - this is for symlinks (`/proc/xxx/{cwd,exe,root}`), you cannot open them.

You can check using Busybox that they're indeed treated as symlinks:

```
$ graphene-direct busybox sh -c 'ls -l /proc/1/'
total 0
-r--------    0 root     root             0 Jan  1  1970 cmdline
lr--------    0 root     root             0 Jan  1  1970 cwd -> /
lr--------    0 root     root             0 Jan  1  1970 exe -> /busybox
dr-x------    3 root     root          4096 Jan  1  1970 fd
-r--------    0 root     root             0 Jan  1  1970 maps
lr--------    0 root     root             0 Jan  1  1970 root -> /
dr-x------    3 root     root          4096 Jan  1  1970 task
```


<!-- Sent from Reviewable.io -->

2021-05-19 16:28 UTC, mkow requested changes
> Reviewed 11 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 180 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3VlBM0f_0gzv9iRpB:-Ma3VlBN-QLdC4ShZSDz:b-klmxjq) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/include/shim_fs.h#L180)):*
> ```
> the caller will update dentry
> ```

You mean rather "the caller has to update"? I.e. this is a requirement for the callers, right?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3pnpMDUOUGpZKdVou:-Ma3pnpMDUOUGpZKdVov:b-vjofhk) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/chroot/fs.c#L237)):*
> ```C
>             break;
>         default:
>             log_warning("unknown PAL handle type");
> ```

not an error?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 340 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3qxNI8e3-HtAPw3Uy:-Ma3qxNI8e3-HtAPw3Uz:bwyohft) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/chroot/fs.c#L340)):*
> ```C
>         stat->st_ctime = (time_t)data->ctime;
>         stat->st_nlink = data->nlink;
>    }
> ```

this is misindented


<!-- Sent from Reviewable.io -->

2021-05-20 06:37 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-05-20 10:31 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 180 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3VlBM0f_0gzv9iRpB:-Ma8FzUn0fE2XYNMZ5iV:b1jpxn8) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/include/shim_fs.h#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> the caller will update dentry
> ```

You mean rather "the caller has to update"? I.e. this is a requirement for the callers, right?
</blockquote></details>

I assumed this describes the interface from the perspective of whoever will be implementing `chmod`, not calling it. See for instance [Linux](https://www.kernel.org/doc/html/latest/filesystems/vfs.html#id3) with phrases like "called when...", "should return...", "the caller will attempt to mount..."

I changed it to "has to update" for consistency, but I'll return here when I have an actual contract for these functions, and write detailed comments. Right now I would be afraid of lying in them :)
___
*[LibOS/shim/src/fs/chroot/fs.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3pnpMDUOUGpZKdVou:-Ma8JEd--ZDZ7gbA9Ges:b-4kmp62) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/chroot/fs.c#L237)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not an error?
</blockquote></details>

The original code simply omitted `default`, but yeah, let's at least return an error. Changed to `return -EINVAL`.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 340 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3qxNI8e3-HtAPw3Uy:-Ma8JAeACkdFNQzcg56e:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/chroot/fs.c#L340)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this is misindented
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-05-20 11:20 UTC, mkow requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3pnpMDUOUGpZKdVou:-Ma8VGKr7klwhu2P-8Z1:b-3jwwn3) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/chroot/fs.c#L237)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The original code simply omitted `default`, but yeah, let's at least return an error. Changed to `return -EINVAL`.
</blockquote></details>

What I meant is even stronger: Shouldn't Graphene emit error message and exit here? Sounds like an implementation bug if the handle is weird?


<!-- Sent from Reviewable.io -->

2021-05-20 11:33 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 237 at r1](https://reviewable.io/reviews/oscarlab/graphene/2379#-Ma3pnpMDUOUGpZKdVou:-Ma8Xy7q4voyZMlUR9em:b-suuo2g) ([raw file](https://github.com/oscarlab/graphene/blob/01139821fc518582f653bffe88801bd73fb2cfac/LibOS/shim/src/fs/chroot/fs.c#L237)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What I meant is even stronger: Shouldn't Graphene emit error message and exit here? Sounds like an implementation bug if the handle is weird?
</blockquote></details>

I'm not 100% sure that doesn't ever happen, but OK, let's fail fast. The tests are not complaining so far.


<!-- Sent from Reviewable.io -->

2021-05-20 11:35 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-20 13:59 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-20 14:19 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-05-20 15:51 UTC, dimakuv approved these changes
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2379)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-20 16:07 UTC, merged