WIP: Simplify readdir
oscarlab/graphene pull request #2383
Opened 2021-05-18 11:45 UTC by pwmarcz

## Description of the changes 

## How to test this PR?

2021-05-21 08:32 UTC, dimakuv requested changes
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaD2L9W04cS5pOuP_Yo:-MaD2L9W04cS5pOuP_Yp:b-ahn8bn) (no related file):*
> (@dimakuv you asked about this recently - this commit does not implement lseek, but it makes it relatively simple to do so)

Thanks! Looks like adding directory handling to lseek will be trivial after this PR -- we can simply set `dir_handle.pos` to the requested value.

---
___
*[LibOS/shim/include/shim_fs.h, line 455 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCt444B_OqmVRF55T7:-MaCt444B_OqmVRF55T8:b-2od7hi) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/include/shim_fs.h#L455)):*
> ```objc
>  * \param hdl a directory handle
>  *
>  * This function initializes the `hdl->dir_info` for a structure, so that the directory can be
> ```

`initializes ... for a structure`? This doesn't sound like correct English.
___
*[LibOS/shim/include/shim_fs.h, line 457 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCtGAkA360WY3DtSWB:-MaCtGAkA360WY3DtSWC:byhh02e) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/include/shim_fs.h#L457)):*
> ```objc
>  * This function initializes the `hdl->dir_info` for a structure, so that the directory can be
>  * listed using `getdents/getdents64` syscalls. It should only be called once, i.e. only if
>  * `hdl->dir_info->dents` is NULL.
> ```

Why `only called once`? What if there is a file created in this directory by Graphene at runtime? If this is not supported, we should add a TODO/explanation.

Or maybe it doesn't `list` the directory (as the name suggests), but only inits some metadata? Then I suggest a rename of this function.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 685 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCu8l2Aca7lNpww49p:-MaCu8l30_FfCH97VOV_:bawq4p) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/bookkeep/shim_handle.c#L685)):*
> ```C
>                 /* we don't checkpoint children dentries of a directory dentry, so need to list
>                  * directory again in child process; mark handle to indicate no cached dentries */
>                 hdl->dir_info.dents = NULL;
> ```

How did this survive our tests?! (Hm, or maybe it's just a memory leak.)

You must update `new_hdl`, not `hdl`. Right now you're "destroying" the information in the parent's directory handle. But what you want to do is to mark `new_hdl` as an "uninitialized" directory.

It looks like there was this same bug in the old code as well...
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 227 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv-1C7ow7Yo4qpvLq:-MaCv-1C7ow7Yo4qpvLr:b4mpjxs) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L227)):*
> ```C
> 
> /*!
>  * \brief Create and populate buffer with dirents.
> ```

The description is wrong now, there is no buffer.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv7uA8whFWlke6f53:-MaCv7uBBtWUAJgKEaeY:b-ngle8o) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L231)):*
> ```C
>  * Generic function for pseudo-filesystems. Example usage for the `/proc` FS is
>  * `pseudo_readdir("/proc/3", callback, arg, proc_root_ent)` -- this calls `callback` on "root",
>  * "cwd", "exe", "fd", etc.
> ```

I got lost here. So what does this callback do? How do we get the list of dir entries using this function?

UPDATE: Ok, after reading the implementation, the callback is typically (always?) used to create a temporary list of child entries, and `arg` is the pointer to this list. Please add a comment in the header file about this typical usage.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 234 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv2ZR8TryFAts0_Li:-MaCv2ZR8TryFAts0_Lj:b-dzxlgj) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L234)):*
> ```C
>  *
>  * \param[in]  dent       Dentry with path to the requested directory.
>  * \param[out] dirent     Pointer to newly created buffer with dirents.
> ```

There is no `dirent`, now you have a callback.
___
*[LibOS/shim/src/fs/shim_namei.c, line 579 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCxVr10DVz1XTtFIw8:-MaCxVr10DVz1XTtFIw9:b-2ytkoo) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L579)):*
> ```C
>     LISTP_FOR_EACH_ENTRY(ent, &ents, list) {
>         struct shim_dentry* child;
>         int ret = lookup_dentry(dent, ent->name, ent->name_len, &child);
> ```

Why do we need to double-check what `readdir` returned? What is the case when `readdir` lies to us and this additional loop over children detects?
___
*[LibOS/shim/src/fs/shim_namei.c, line 579 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCxhxjBB6-beDlF2Qv:-MaCxhxjBB6-beDlF2Qw:b-l6204q) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L579)):*
> ```C
>     LISTP_FOR_EACH_ENTRY(ent, &ents, list) {
>         struct shim_dentry* child;
>         int ret = lookup_dentry(dent, ent->name, ent->name_len, &child);
> ```

You have a redefinition of `int ret` here. Not important though.
___
*[LibOS/shim/src/fs/shim_namei.c, line 601 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCy1EQ92onpk_1ofcM:-MaCy1EQ92onpk_1ofcN:befx9r7) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L601)):*
> ```C
>     assert(locked(&hdl->lock));
>     assert(hdl->dentry);
>     assert(!dirhdl->dents);
> ```

Why do we have this assert? I still don't understand why we do this only once. I would expect `if (dirhdl->dents) return 0` instead.
___
*[LibOS/shim/src/fs/shim_namei.c, line 608 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCyBp2326RaMeSLi2R:-MaCyBp2326RaMeSLi2S:btyueao) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L608)):*
> ```C
>     int ret;
> 
>     lock(&g_dcache_lock);
> ```

This looks brittle. The caller first grabs the lock over `hdl`, and only then we grab the global lock `g_dcache_lock`. Shouldn't it be the other way around? Or at least shouldn't both these operations happen in the caller?
___
*[LibOS/shim/src/fs/shim_namei.c, line 613 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCyZLKBCOtvMgkQzvp:-MaCyZLKBCOtvMgkQzvq:b2yjgnb) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L613)):*
> ```C
>         goto out;
> 
>     size_t capacity = hdl->dentry->nchildren + 1;
> ```

Maybe add a quick comment that `+1` is `.`?
___
*[LibOS/shim/src/fs/shim_namei.c, line 627 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCypkMAk74zeTHBm5B:-MaCypkMAk74zeTHBm5C:b-ee52hn) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L627)):*
> ```C
>     if (hdl->dentry->parent) {
>         get_dentry(hdl->dentry->parent);
>         assert(count < capacity);
> ```

This assert is trivial, I suggest to remove it. Or do you do this just for readability?
___
*[Li [...]

2021-05-24 01:00 UTC, mkow requested changes
Awesome cleanup!

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383#-:-MaQmPeJ51D3cATiToME:b-ptfwld)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaD2L9W04cS5pOuP_Yo:-MaQQUVI6JPXrj_Isf0g:bv7jy95) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> (@dimakuv you asked about this recently - this commit does not implement lseek, but it makes it relatively simple to do so)

Thanks! Looks like adding directory handling to lseek will be trivial after this PR -- we can simply set `dir_handle.pos` to the requested value.
</blockquote></details>

To whoever will be adding this later: Please remember to add a test for it :)

---
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 685 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCu8l2Aca7lNpww49p:-MaQWaHs7idEsbwOu-wp:bcosfwz) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/bookkeep/shim_handle.c#L685)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How did this survive our tests?! (Hm, or maybe it's just a memory leak.)

You must update `new_hdl`, not `hdl`. Right now you're "destroying" the information in the parent's directory handle. But what you want to do is to mark `new_hdl` as an "uninitialized" directory.

It looks like there was this same bug in the old code as well...
</blockquote></details>

@pwmarcz: When fixing this, could you add a test which would be able to detect this bug? Seems this was completely untested?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv7uA8whFWlke6f53:-MaQX_KxBAiwbWejHQVe:b-4fk5cr) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L231)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I got lost here. So what does this callback do? How do we get the list of dir entries using this function?

UPDATE: Ok, after reading the implementation, the callback is typically (always?) used to create a temporary list of child entries, and `arg` is the pointer to this list. Please add a comment in the header file about this typical usage.
</blockquote></details>

Tbh current description was pretty clear to me (it's a generic function which calls the given function for all subfiles in a dir), but if you want we can describe an example usage.
___
*[LibOS/shim/src/fs/shim_namei.c, line 528 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQcdbX0TkydGmSsjZP:-MaQcdbX0TkydGmSsjZQ:besfvwp) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L528)):*
> ```
> its names
> ```

Rather its subfiles names?
___
*[LibOS/shim/src/fs/shim_namei.c, line 560 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQehdz15raC0T9O0T1:-MaQehdz15raC0T9O0T2:b4bz2gg) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L560)):*
> ```
> list_directory
> ```

I think it's not really listing it, from the API point of view? It just verifies if all the dentries are in place, without returning the entries. So, I'd reflect this in the name somehow (assuming my understanding is correct).
___
*[LibOS/shim/src/fs/shim_namei.c, line 582 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQdzsx-p5rcVc7YQx6:-MaQdzsx-p5rcVc7YQx7:bslnyp9) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L582)):*
> ```C
>         if (ret == 0) {
>             put_dentry(child);
>         } else if (ret != -EACCES) {
> ```

Should this actually be an error? Sometimes we have a dir with unreadable files. I assume that the idea here is that they still should be possible to be "looked up"? (yup, I'm not sure when exactly `lookup_dentry()` may fail with `-EACCES`, so I'm confused about what is actually checked here)
___
*[LibOS/shim/src/fs/shim_namei.c, line 611 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQfE3VARR8IcEPxnXA:-MaQfE3VARR8IcEPxnXB:b533e1f) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L611)):*
> ```C
> 
>     if ((ret = list_directory(hdl->dentry)) < 0)
>         goto out;
> ```

When exactly can this happen? (that we lack some dentries)
___
*[LibOS/shim/src/fs/shim_namei.c, line 614 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQfjQfDZB1w1qUQKfJ:-MaQfjQfDZB1w1qUQKfK:b-nucl6g) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L614)):*
> ```C
> 
>     size_t capacity = hdl->dentry->nchildren + 1;
>     if (hdl->dentry->parent)
> ```

Actually, how is this possible? On Linux even `/` has a parent (itself) and the corresponding `..` entry.
___
*[LibOS/shim/src/fs/shim_namei.c, line 617 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQgtYzECocBzwT78cE:-MaQgtYzECocBzwT78cF:b-mfir8h) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L617)):*
> ```C
>         capacity++;
> 
>     dents = malloc(sizeof(struct shim_dentry) * capacity);
> ```

Only partially related to the PR, but: All the data we work here on may be (I think) externally controlled, e.g. in chroot mounts. So, the attacker may theoretically pretend to have tons of subdirs and overflow this multiplication. Probably impossible on 64-bit, but on 32-bit it's harder to be sure. In general, I think all our dentry-related code isn't careful enough...

Anyways, this sounds theoretical, but I think this is actually triggerable on 64-bit - due to the quality of Graphene legacy code, `shim_dentry::nchildren` is `int`, and on 64-bit systems it should be possible to overflow it :)
___
*[LibOS/shim/src/fs/chroot/fs.c, line 273 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQjGdo-THKfK3I8Upr:-MaQjGdo-THKfK3I8Ups:bubz82q) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/chroot/fs.c#L273)):*
> ```C
>         /* DEP 3/18/17: If we have a directory, we need to find out how many
>          * children it has by hand. */
>         /* XXX: Keep coherent with rmdir/mkdir/creat, etc */
> ```

I don't get both of these comments, are they still valid?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 828 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQlaBJBrFf4h7owkKM:-MaQlaBJBrFf4h7owkKN:b-cxcb7n) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/chroot/fs.c#L828)):*
> ```C
>             /* By the PAL convention, if a name ends with '/', it is a directory. However, we ignore
>              * that distinction here and pass the name without '/' to the callback. */
>             if (buf[end - 1] == '/')
> ```

This whole loop assumes that empty names are impossible. Nothing bad happens if they aren't, but I'd feel safer if this was handled better.
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQm20w7EIBLWwaj0tB:-MaQm20w7EIBLWwaj0tC:bkjss5h) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/proc/ipc-thread.c#L283)):*
> ```C
>         IDTYPE pid = status->status[i].pid;
>         char name[10];
>         snprintf(name, sizeo [...]

2021-05-24 17:24 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: 4 of 16 files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaD2L9W04cS5pOuP_Yo:-MaTbnVt9pXTYb2LGHQ8:b63oun6) (no related file):*
> Thanks! Looks like adding directory handling to lseek will be trivial after this PR -- we can simply set dir_handle.pos to the requested value.

Almost... this still caches the directory contents, and the user doing `lseek` expects to see the new files, so you probably need to also refresh (`clear_directory_handle`).

---
___
*[LibOS/shim/include/shim_fs.h, line 455 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCt444B_OqmVRF55T7:-MaTcHukEJQwqnIVee6k:b-qj92pf) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/include/shim_fs.h#L455)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`initializes ... for a structure`? This doesn't sound like correct English.
</blockquote></details>

Reworded.
___
*[LibOS/shim/include/shim_fs.h, line 457 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCtGAkA360WY3DtSWB:-MaThnkl58tc62VKTKbe:begjqfz) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/include/shim_fs.h#L457)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `only called once`? What if there is a file created in this directory by Graphene at runtime? If this is not supported, we should add a TODO/explanation.

Or maybe it doesn't `list` the directory (as the name suggests), but only inits some metadata? Then I suggest a rename of this function.
</blockquote></details>

I changed to `populate_directory_handle` / `clear_directory_handle`, both are no-op if the handle is already in desired state.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 685 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCu8l2Aca7lNpww49p:-MaTrawT-do2vGx41iqX:b8821gy) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/bookkeep/shim_handle.c#L685)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@pwmarcz: When fixing this, could you add a test which would be able to detect this bug? Seems this was completely untested?
</blockquote></details>

Done. I modified the `getdents` test so that it checks what happens with a handle across fork.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 227 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv-1C7ow7Yo4qpvLq:-MaUMuGX9ux3myLurrlL:b-bw8e14) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L227)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The description is wrong now, there is no buffer.
</blockquote></details>

Updated.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv7uA8whFWlke6f53:-MaTUC4l8-lIAyD72cL7:bdxwmpr) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L231)):*
>the callback is typically (always?) used to create a temporary list of child entries, and arg is the pointer to this list.

Currently, I also use it in one place to just _count_ the entries. And a previous implementation called `lookup_dentry()` on each name, but that's problematic if we're already inside `readdir`.

My point: this is a generic "for each" mechanism, and I believe a `void*` argument is a common pattern in C for these, to use for any kind of necessary context. We already do the same for `walk_thread_list`.

I fleshed out the description for `readdir`. I couldn't think of an example short enough to be worth including, so I explained that `arg` can be used to pass additional data, for example a list.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 234 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv2ZR8TryFAts0_Li:-MaTXKwe9hQsgVs5r1sf:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L234)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no `dirent`, now you have a callback.
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_namei.c, line 528 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQcdbX0TkydGmSsjZP:-MaTXVufAKnFXQGJtO7P:b-qj92pf) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L528)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> its names
> ```

Rather its subfiles names?
</blockquote></details>

Reworded.
___
*[LibOS/shim/src/fs/shim_namei.c, line 560 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQehdz15raC0T9O0T1:-MaTX_NCBZwSUqQAoEo5:b-fxdlxc) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L560)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> list_directory
> ```

I think it's not really listing it, from the API point of view? It just verifies if all the dentries are in place, without returning the entries. So, I'd reflect this in the name somehow (assuming my understanding is correct).
</blockquote></details>

Renamed to `populate_directory`.
___
*[LibOS/shim/src/fs/shim_namei.c, line 579 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCxVr10DVz1XTtFIw8:-MaTXk1eBIvhzsR9HWV9:badr7cv) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L579)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need to double-check what `readdir` returned? What is the case when `readdir` lies to us and this additional loop over children detects?
</blockquote></details>

`readdir` gives us only a list of names, here we call the underlying lookup to create a dentry if necessary. This is to make underlying filesystem implementation easier: it doesn't need to construct the same information twice.

(It's also less efficient but given the state of FS code I really want to simplify it as much as I can first).
___
*[LibOS/shim/src/fs/shim_namei.c, line 579 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCxhxjBB6-beDlF2Qv:-MaTYaMn3fBqHYYMww2h:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L579)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have a redefinition of `int ret` here. Not important though.
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_namei.c, line 582 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQdzsx-p5rcVc7YQx6:-MaTZR1H5I_6ExQee0Kn:b-u0wz7e) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L582)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should this actually be an error? Sometimes we have a dir with unreadable files. I assume that the idea here is that they still should be possible to be "looked up"? (yup, I'm not sure when exactly `lookup_dentry()` may fail with `-EACCES`, so I'm confused about what is actually checked her [...]

2021-05-25 08:05 UTC, dimakuv requested changes
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 193 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXS4yl8iwP9C4gdDUK:-MaXS4yl8iwP9C4gdDUL:b6z5t6y) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/include/shim_fs.h#L193)):*
> ```objc
>      *
>      * \param dentry the dentry, must be valid, non-negative and describing a directory
>      * \param callback the callback to invoke on each
> ```

`on each file name`
___
*[LibOS/shim/include/shim_fs.h, line 197 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXSDkY6wqiHIy0w87M:-MaXSDkY6wqiHIy0w87N:b68vgil) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/include/shim_fs.h#L197)):*
> ```objc
>      *
>      * Calls `callback(name, arg)` for all file names in the directory. `name` is not guaranteed to
>      * be valid after callback returns, so the callback should copy it necessary.
> ```

`... it if necessary` (forgot `if`)
___
*[LibOS/shim/include/shim_fs.h, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXSksY6VHihKe7aqD5:-MaXSksY6VHihKe7aqD6:bha7uul) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/include/shim_fs.h#L482)):*
> ```objc
>  * \param hdl a directory handle
>  *
>  * This functions discards an array of dentries previously prepared by `populate_directory_handle`.
> ```

`function`
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv7uA8whFWlke6f53:-MaXTSqX73LQAWDyk6v1:bj89ixo) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L231)):*
> My point: this is a generic "for each" mechanism, and I believe a void* argument is a common pattern in C for these

Yes, I understand this. I didn't have a problem with understanding "for each" logic; I had a problem with "why so complex and generic at all". I'm fine with the current comments, so resolving this.
___
*[LibOS/shim/src/fs/shim_namei.c, line 579 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCxVr10DVz1XTtFIw8:-MaXU7asBR0u03xVX9_P:bxcixb5) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L579)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`readdir` gives us only a list of names, here we call the underlying lookup to create a dentry if necessary. This is to make underlying filesystem implementation easier: it doesn't need to construct the same information twice.

(It's also less efficient but given the state of FS code I really want to simplify it as much as I can first).
</blockquote></details>

OK, thanks for explanation!
___
*[LibOS/shim/src/fs/shim_namei.c, line 617 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQgtYzECocBzwT78cE:-MaXUsgA8cETOOCceRlB:ba2tgar) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L617)):*
> Or maybe put a limit on the number of children?

This solution sounds reasonable. I would do this.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 273 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQjGdo-THKfK3I8Upr:-MaXVaxN1uIQeKSIM82o:b-s8zvbq) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/chroot/fs.c#L273)):*
> Maybe we don't need to do that? Do you know if applications might do something with it?

IIRC, we haven't had any issues with any applications that would complain/be confused about `nlink`. So I'd say let's just ignore accurate reporting of nlink.
___
*[LibOS/shim/test/regression/getdents.c, line 36 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXXgp51RY8c7IUWWkf:-MaXXgp51RY8c7IUWWkg:bh6ezhq) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L36)):*
> ```C
>     int count = syscall(SYS_getdents, fd, buf, buf_size);
>     if (count < 0) {
>         fprintf(stderr, "%s: %s\n", name, strerror(errno));
> ```

Why not `perror()`?
___
*[LibOS/shim/test/regression/getdents.c, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXXWHA9Yc-DMx4qQez:-MaXXWHA9Yc-DMx4qQf-:biopsee) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L41)):*
> ```C
>     for (size_t offs = 0; offs < count;) {
>         struct linux_dirent* d32 = (struct linux_dirent*)(buf + offs);
>         char d_type              = *(buf + offs + d32->d_reclen - 1);
> ```

This indentation looks ugly, please unindent.
___
*[LibOS/shim/test/regression/getdents.c, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXYO0H7R5GWKqMtZqN:-MaXYO0H7R5GWKqMtZqO:bsmjl33) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L155)):*
> ```C
>      *
>      * Note that we currently do not synchronize handle state between parent and child in Graphene,
>      * so both calls after fork will return the same entries.
> ```

Is this comment valid? I thought that this PR fixes this: the directory handle retains `pos`, so even after fork, the child proceeds with where the parent stopped.

Also, doesn't it directly contradict the comment line above?


<!-- Sent from Reviewable.io -->

2021-05-25 12:43 UTC, mkow requested changes
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 685 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCu8l2Aca7lNpww49p:-MaYOjxx5bHVOWx3myJD:b-ucfknh) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/bookkeep/shim_handle.c#L685)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done. I modified the `getdents` test so that it checks what happens with a handle across fork.
</blockquote></details>

Thanks!
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 681 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYPx-UByNju-gJYqvo:-MaYPx-UByNju-gJYqvp:b-m3qsqu) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/src/bookkeep/shim_handle.c#L681)):*
> ```
> so that `getdents/getdents64` will resume from the same place.
> ```

What's the semantics of this if the contents changed in the meantime? (I mean, on Linux)
___
*[LibOS/shim/src/fs/shim_namei.c, line 617 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQgtYzECocBzwT78cE:-MaYRPab3V4JUqGgvWcv:baivw7m) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L617)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Or maybe put a limit on the number of children?

This solution sounds reasonable. I would do this.
</blockquote></details>

Yup, seems the easiest to cap it at e.g. 1 million or something similar. But this `nchildren` type should be fixed regardless of this capping.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 273 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQjGdo-THKfK3I8Upr:-MaYS7UX2IRMRJTexQyZ:b-izw0h2) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/chroot/fs.c#L273)):*
> I can rewrite these comments

That would be helpful :)

Ad `nlink` I think we can ignore it, but please reflect this problem in the comment.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 828 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYSXhK6NeaD4eU1kJG:-MaYSXhK6NeaD4eU1kJH:b8qszy7) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/src/fs/chroot/fs.c#L828)):*
> ```C
>             if (end == start) {
>                 log_warning("chroot_readdir: empty name returned from PAL\n");
>                 ret = -EINVAL;
> ```

I'd `die_or_inf_loop()` here, as this should be only possible when the PAL is bugged or the host is attacking the enclave.
___
*[LibOS/shim/src/sys/shim_open.c, line 361 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQpu-l5lRCY1Q6TIS8:-MaYTGGV58m_555GCnQg:b-yje6zg) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/sys/shim_open.c#L361)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, this is what the comment in previous version suggested: `linux_dirent_tail` starts with a zero padding byte.

```
           struct linux_dirent {
               unsigned long  d_ino;     /* Inode number */
               unsigned long  d_off;     /* Offset to next linux_dirent */
               unsigned short d_reclen;  /* Length of this linux_dirent */
               char           d_name[];  /* Filename (null-terminated) */
                                 /* length is actually (d_reclen - 2 -
                                    offsetof(struct linux_dirent, d_name)) */
               /*
               char           pad;       // Zero padding byte
               char           d_type;    // File type (only since Linux
                                         // 2.6.4); offset is (d_reclen - 1)
               */
           }
```

On the other hand, maybe just adding `+1` for clarity would be better?
</blockquote></details>

I'm fine with the current, commented version. Thanks!
___
*[LibOS/shim/src/sys/shim_open.c, line 383 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQs7eVD0-tfVzS__6B:-MaYTkDyBx-4EeZ66BGu:b6smacz) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/sys/shim_open.c#L383)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

So actually `getdents64` should return `ssize_t`, I had a [broken man page](https://github.com/mkerrisk/man-pages/commit/13e88b70707183489228cd26deb939a27a00d661).

I added a check for the return value, does that look good?
</blockquote></details>

Yup, looks good, although it silently assumes that `ssize_t` is not smaller than `long` (because of the type of `ret`). You can add a static assert for this if you want.
___
*[LibOS/shim/test/regression/getdents.c, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYWNuA5UOGcr2pCMKE:-MaYWNuA5UOGcr2pCMKF:b-pgmrmu) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L152)):*
> ```
>      * with a buffer size small enough so that all three calls return something.
> ```

I don't get this part, didn't you mean "big enough"? Even if, I don't understand it... Won't the calls always return something > 0 for the first invocation, if the buffer is big enough?


<!-- Sent from Reviewable.io -->

2021-05-25 14:33 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: 12 of 17 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 193 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXS4yl8iwP9C4gdDUK:-MaYhDAi7ygg9-MKGsFG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/include/shim_fs.h#L193)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`on each file name`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 197 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXSDkY6wqiHIy0w87M:-MaYhEfU4dl5IcSjMeKf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/include/shim_fs.h#L197)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`... it if necessary` (forgot `if`)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 482 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXSksY6VHihKe7aqD5:-MaYhKWy28yypuhOo_b_:byac1gx) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/include/shim_fs.h#L482)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`function`
</blockquote></details>

I must have been tired... Fixed.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 681 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYPx-UByNju-gJYqvo:-MaYhOm56ZMonayOZkZR:b-tvi5c) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/src/bookkeep/shim_handle.c#L681)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> so that `getdents/getdents64` will resume from the same place.
> ```

What's the semantics of this if the contents changed in the meantime? (I mean, on Linux)
</blockquote></details>

On Linux? I'm not sure of the exact implementation, but experimentally, subsequent `getdents` calls continue from the same file, but iterate over an updated directory if we update it in the meantime.

Here, because we only store a position and the child recreates the listing, unfortunately we might jump over or repeat an entry...
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv7uA8whFWlke6f53:-MaYjfs94JD5739zXdFa:b-rym5uj) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L231)):*
>I didn't have a problem with understanding "for each" logic; I had a problem with "why so complex and generic at all".

I misunderstood then, sorry. I hope my other comments explain the choice.

(Now that I think of it, I could also make `readdir` return a list of names, and provide a set of functions to construct this list... but that seems pretty close to the callback solution, and would require more error handling from the filesystems).
___
*[LibOS/shim/src/fs/shim_namei.c, line 617 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQgtYzECocBzwT78cE:-MaYmZUH7YcU8OIs3tIv:b-7fe0wv) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_namei.c#L617)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, seems the easiest to cap it at e.g. 1 million or something similar. But this `nchildren` type should be fixed regardless of this capping.
</blockquote></details>

I converted `nchildren` to `size_t`, and added a limit of 1 million.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 273 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQjGdo-THKfK3I8Upr:-MaYqyVD1NGm1K0gRsqw:b-tl1qv) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/chroot/fs.c#L273)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> I can rewrite these comments

That would be helpful :)

Ad `nlink` I think we can ignore it, but please reflect this problem in the comment.
</blockquote></details>

I think some code uses `nlink` to determine number of files in a directory. `sys/fs.c` mentions hwloc, [see here](https://github.com/open-mpi/hwloc/blob/03bddd0037c62116d6171e4bf1fb72c48a57d825/hwloc/topology-linux.c)).

So we might have to revisit this, but let's try to hardcode `nlink` in here for now.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 828 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYSXhK6NeaD4eU1kJG:-MaYrX6r0ynLVS5TATqX:bz00a57) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/src/fs/chroot/fs.c#L828)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd `die_or_inf_loop()` here, as this should be only possible when the PAL is bugged or the host is attacking the enclave.
</blockquote></details>

OK. I'm changing the message to error, then - it would be bad for Graphene to abort without any explanation.
___
*[LibOS/shim/src/sys/shim_open.c, line 383 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaQs7eVD0-tfVzS__6B:-MaYsOns-CVh8zdU9HHw:b2vctbl) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/sys/shim_open.c#L383)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, looks good, although it silently assumes that `ssize_t` is not smaller than `long` (because of the type of `ret`). You can add a static assert for this if you want.
</blockquote></details>

I added a static assert.
___
*[LibOS/shim/test/regression/getdents.c, line 36 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXXgp51RY8c7IUWWkf:-MaYsY6NAGYYfji0zv48:b-4cdqva) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not `perror()`?
</blockquote></details>

`perror()` doesn't do format strings, and I wanted to parametrize by `name` here... but you're right, I can just do `perror(name)`. Fixed.
___
*[LibOS/shim/test/regression/getdents.c, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXXWHA9Yc-DMx4qQez:-MaYswGGCbAeOHiz0_ih:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This indentation looks ugly, please unindent.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/getdents.c, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYWNuA5UOGcr2pCMKE:-MaYsz3i0Ty-cCfXtS7x:b-uhe13e) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>      * with a buffer size small enough so that all three calls return something.
> ```

I don't get this part, didn't you mean "big enough"? Even if, I don't understand it... Won't the calls always return something > 0 for the first invocation, if the buffer is big enough?
</blockquote></details>

If the buffer is too big, then the first call (the one before fork) will retrieve all the entries, and the calls after the fork will return 0.
___
*[ [...]

2021-05-25 15:06 UTC, mkow requested changes
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 681 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYPx-UByNju-gJYqvo:-MaZ-knXAoNxxycM1DMh:b-jpd4iz) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/src/bookkeep/shim_handle.c#L681)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

On Linux? I'm not sure of the exact implementation, but experimentally, subsequent `getdents` calls continue from the same file, but iterate over an updated directory if we update it in the meantime.

Here, because we only store a position and the child recreates the listing, unfortunately we might jump over or repeat an entry...
</blockquote></details>

@boryspoplawski Do you know maybe if Linux has any guarantees in this situation? I remember we discussed this long time ago, but I'm not sure which of these were actually documented/guaranteed anywhere.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 172 at r3](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaZ0YoC0KArVJMUMYH_:-MaZ0YoC0KArVJMUMYHa:bp7t3dz) ([raw file](https://github.com/oscarlab/graphene/blob/2e208831ac1b43b20916218e95ebc127c1187a73/LibOS/shim/src/fs/shim_dcache.c#L172)):*
> ```C
> 
>     if (!qstrsetstr(&dent->name, name, name_len)) {
>         free_dentry(dent);
> ```

Is this call correct? It does `qstrfree(&dent->name)`, on a qstr which failed to be allocated, and I don't think `qstrsetstr()` has any guarantees about the `qstr` contents after a failure.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 178 at r3](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaZ17s029IDoZFGIKod:-MaZ17s029IDoZFGIKoe:b-f0ce08) ([raw file](https://github.com/oscarlab/graphene/blob/2e208831ac1b43b20916218e95ebc127c1187a73/LibOS/shim/src/fs/shim_dcache.c#L178)):*
> ```C
>     if (parent->nchildren >= DENTRY_MAX_CHILDREN) {
>         log_warning("get_new_dentry: nchildren limit reached\n");
>         free_dentry(dent);
> ```

ditto - `dent` is only partially initialized here, is this really correct to call a destructor on it?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 231 at r1](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaCv7uA8whFWlke6f53:-MaZ1LKI4jA9wVLy6-Fa:blinevb) ([raw file](https://github.com/oscarlab/graphene/blob/fb314957e7b7f06b5b065a35d93a7d3f363b48f8/LibOS/shim/src/fs/shim_fs_pseudo.c#L231)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>I didn't have a problem with understanding "for each" logic; I had a problem with "why so complex and generic at all".

I misunderstood then, sorry. I hope my other comments explain the choice.

(Now that I think of it, I could also make `readdir` return a list of names, and provide a set of functions to construct this list... but that seems pretty close to the callback solution, and would require more error handling from the filesystems).
</blockquote></details>

I like the current solution, I don't think there's any simpler/better one we could have.
___
*[LibOS/shim/test/regression/getdents.c, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYWNuA5UOGcr2pCMKE:-MaZ2UfI3JPQje_eimP5:b-5tx05j) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L152)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If the buffer is too big, then the first call (the one before fork) will retrieve all the entries, and the calls after the fork will return 0.
</blockquote></details>

Aaaah. Could you add a parenthesis explaining that briefly?
___
*[LibOS/shim/test/regression/getdents.c, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXYO0H7R5GWKqMtZqN:-MaZ2iR-15njOZfY9S9X:b-7fjk2v) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L155)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We retain `pos` after fork, but don't synchronize it between parent and child after that. Under Linux, the two calls after `fork` get subsequent entries because the position is shared between the processes, Graphene has two independent handles.

Running this example under Linux displays:

```
getdents64 before fork: dir3 [0x4]
getdents64 before fork: file1 [0x8]
parent getdents64: file2 [0x8]
parent getdents64: .. [0x4]
child getdents64: . [0x4]
```

Under Graphene:

```
getdents64 before fork: . [0x4]
getdents64 before fork: .. [0x4]
child getdents64: file2 [0x8]
child getdents64: file1 [0x8]
parent getdents64: file1 [0x8]
parent getdents64: file2 [0x8]
```

I'm not sure how to make this comment clearer, but I can reword if you have an idea how.
</blockquote></details>

@boryspoplawski please also take a look at this ^


<!-- Sent from Reviewable.io -->

2021-05-25 16:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: 16 of 17 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 172 at r3](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaZ0YoC0KArVJMUMYH_:-MaZEsJK05Ij8IWUbkqm:b-k4xjwo) ([raw file](https://github.com/oscarlab/graphene/blob/2e208831ac1b43b20916218e95ebc127c1187a73/LibOS/shim/src/fs/shim_dcache.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is this call correct? It does `qstrfree(&dent->name)`, on a qstr which failed to be allocated, and I don't think `qstrsetstr()` has any guarantees about the `qstr` contents after a failure.
</blockquote></details>

Looking at `qstrsetstr()` and `qstrfree()`, I think it's correct: `qstrsetstr` can fail to allocate the `oflow` field, but then `qstrfree` will not free any memory. It would be a pretty serious bug if `qstrsetstr` left the string in an inconsistent state from which you cannot even clean up...
___
*[LibOS/shim/src/fs/shim_dcache.c, line 178 at r3](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaZ17s029IDoZFGIKod:-MaZG2XY2DzOpUWNSbBq:b-5ngmmi) ([raw file](https://github.com/oscarlab/graphene/blob/2e208831ac1b43b20916218e95ebc127c1187a73/LibOS/shim/src/fs/shim_dcache.c#L178)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto - `dent` is only partially initialized here, is this really correct to call a destructor on it?
</blockquote></details>

Yes. I think the idea was that `alloc_dentry` performs the initialization, i.e. ensures the object is in a consistent state, after which you can call `free_dentry` on it. This function (`get_new_dentry`) performs additional setup, i.e. installs the newly created dentry in the dentry cache.
___
*[LibOS/shim/test/regression/getdents.c, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYWNuA5UOGcr2pCMKE:-MaZEO2L8Lghahjyq8Fm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Aaaah. Could you add a parenthesis explaining that briefly?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 17:40 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/getdents.c, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXYO0H7R5GWKqMtZqN:-MaZbFOV3JEJdDki8LNH:brujztc) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L155)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski please also take a look at this ^
</blockquote></details>

OK, thanks.


<!-- Sent from Reviewable.io -->

2021-05-26 17:50 UTC, boryspoplawski reviewed
> Reviewed 2 of 12 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 681 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaYPx-UByNju-gJYqvo:-Madm5g29v4GPRKvX3lZ:bz9f2sl) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/src/bookkeep/shim_handle.c#L681)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski Do you know maybe if Linux has any guarantees in this situation? I remember we discussed this long time ago, but I'm not sure which of these were actually documented/guaranteed anywhere.
</blockquote></details>

This depends on the actual filesystem used, afaik there are no general guarantees. E.g. ext4 can return already deleted entries, because caching and what not.
___
*[LibOS/shim/test/regression/getdents.c, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaXYO0H7R5GWKqMtZqN:-MadmzhU0-qBxnnbfHr6:b-smwszs) ([raw file](https://github.com/oscarlab/graphene/blob/e99c572695243a61dd60b265e0b0001906717587/LibOS/shim/test/regression/getdents.c#L155)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, thanks.
</blockquote></details>

Yup, handle is shared on Linux, hence the position too. I guess that will be the case in Graphene, once we have the sync code.


<!-- Sent from Reviewable.io -->

2021-05-27 01:32 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_dcache.c, line 172 at r3](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaZ0YoC0KArVJMUMYH_:-MafQCo-0OytMRsaOM0f:bfnn94z) ([raw file](https://github.com/oscarlab/graphene/blob/2e208831ac1b43b20916218e95ebc127c1187a73/LibOS/shim/src/fs/shim_dcache.c#L172)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Looking at `qstrsetstr()` and `qstrfree()`, I think it's correct: `qstrsetstr` can fail to allocate the `oflow` field, but then `qstrfree` will not free any memory. It would be a pretty serious bug if `qstrsetstr` left the string in an inconsistent state from which you cannot even clean up...
</blockquote></details>

Hmm, I think it depends. `qstrsetstr()` actually leaves it uninitialized (or rather just unchanged) in case of an error, not in any particular state, but this function seems to also be a "constructor"? And `alloc_dentry()` doesn't "construct" this structure anyhow, just zeroes the whole memory, so it kinda works by an accident?
Unblocking for now, this code looks really fishy, but it's more like these "qstrings" being broken.


<!-- Sent from Reviewable.io -->

2021-05-27 09:55 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_dcache.c, line 172 at r3](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaZ0YoC0KArVJMUMYH_:-MahEmwLCXkBE_2O7q9q:b-veki6c) ([raw file](https://github.com/oscarlab/graphene/blob/2e208831ac1b43b20916218e95ebc127c1187a73/LibOS/shim/src/fs/shim_dcache.c#L172)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I think it depends. `qstrsetstr()` actually leaves it uninitialized (or rather just unchanged) in case of an error, not in any particular state, but this function seems to also be a "constructor"? And `alloc_dentry()` doesn't "construct" this structure anyhow, just zeroes the whole memory, so it kinda works by an accident?
Unblocking for now, this code looks really fishy, but it's more like these "qstrings" being broken.
</blockquote></details>

We're getting close to removing them :)


<!-- Sent from Reviewable.io -->

2021-05-27 12:01 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 172 at r3](https://reviewable.io/reviews/oscarlab/graphene/2383#-MaZ0YoC0KArVJMUMYH_:-MahgcCgBtbHM0_-hn16:bb77rlh) ([raw file](https://github.com/oscarlab/graphene/blob/2e208831ac1b43b20916218e95ebc127c1187a73/LibOS/shim/src/fs/shim_dcache.c#L172)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We're getting close to removing them :)
</blockquote></details>

Yay!


<!-- Sent from Reviewable.io -->

2021-05-27 12:04 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-27 12:31 UTC, mkow approved these changes
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2383)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-27 13:43 UTC, merged