[Pal/Linux-SGX] Do not use Exitless for clone OCALL
oscarlab/graphene pull request #2384
Opened 2021-05-19 08:11 UTC by dimakuv

## Description of the changes 

Exitless feature distinguishes between normal enclave threads and untrusted RPC threads (the latter submit syscall requests on behalf of the former). Enclave threads catch all sync and async signals from the host, including SIGILL. RPC threads block all sync and async signals other than SIGUSR2.

This PR fixes a bug that clone OCALL was considered suitable for Exitless, which meant that the new enclave thread was created on behalf of the RPC tread, and thus inherited its signal mask. Thus, the new enclave thread couldn't handle e.g. SIGILL exceptions (which can happen on legit CPUID and RDTSC instructions), and Graphene terminated the whole process.

## How to test this PR? 

All tests must pass. This bug was found on our Redis example with Exitless enabled.

2021-05-19 11:40 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2384)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-05-19 13:06 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2384)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2384#-Ma3ibsDCrV0MmF4Su1A:-Ma3ibsE5mgN99AAQYn-:b6fj6s7) (no related file):*
Actually, why do we block all signals in rpc threads? Doesn't sound like something we should do...
This change is fine anyway, since creating a new enclave is expensive anyway, so exitless doesn't make much sense

---


<!-- Sent from Reviewable.io -->

2021-05-19 14:16 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2384)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2384#-Ma3ibsDCrV0MmF4Su1A:-Ma3yhsc1ldsoWOnMLSB:bmkcfqy) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually, why do we block all signals in rpc threads? Doesn't sound like something we should do...
This change is fine anyway, since creating a new enclave is expensive anyway, so exitless doesn't make much sense
</blockquote></details>

Why should we keep signals unblocked in RPC threads? What's the point of getting a SIGINT signal in the RPC thread? Or SIGILL in the RPC thread? In the first case, SIGINT should be re-directed to some enclave thread. In the second case, SIGILL should just terminate the whole process, since it's a bug in untrusted RPC code.

By the way, you created a blocking comment. Do you want me to change anything in this PR?

---


<!-- Sent from Reviewable.io -->

2021-05-19 16:51 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2384)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2384#-Ma3ibsDCrV0MmF4Su1A:-Ma47tjg6T5gnIW_vhPH:b-jsr2ul) (no related file):*
> Why should we keep signals unblocked in RPC threads?

Why should we block them? If a thread gets a signal it's probably for a reason.
 
> What's the point of getting a SIGINT signal in the RPC thread? In the first case, SIGINT should be re-directed to some enclave thread. 

We do not handle SIGINT, so there is no need to block it. Only async signal that's handled and is SIGTERM, which we should block indeed, others are either targeted at the thread directly or not handled at all.

> In the second case, SIGILL should just terminate the whole process, since it's a bug in untrusted RPC code.

Yes, and in what way blocking it helps?

> By the way, you created a blocking comment. Do you want me to change anything in this PR?

Yes, I wanted to understand the situation and possibly fix if there is anything to fix (and I believe there is), but since this is an existing issue, we can postpone fixes for later. IIUC you want to fasttrack this? In such case ignore my comments :)

---


<!-- Sent from Reviewable.io -->

2021-05-19 19:24 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2384)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-05-19 20:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2384)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2384#-Ma3ibsDCrV0MmF4Su1A:-Ma5BuWj39IIfeOSR1pp:b-vwjsv7) (no related file):*
I don't know, I don't see a compelling reason to unblock all signals in RPC threads but still block SIGTERM (and explicitly unblock SIGUSR2 which is blocked in enclave threads). In other words, we'll still need to do some blocking/unblocking for RPC threads, so why bother?

> Yes, and in what way blocking it helps?

It doesn't but it makes it explicit in the code that there is no signal handler SIGILL for RPC threads. If we wouldn't block, then the host would jump into the Graphene signal handler, and only then terminate the process. For me, "RPC threads catch SIGILL but fail on it" sounds weird -- I don't think it's good readability.

---


<!-- Sent from Reviewable.io -->

2021-05-19 20:11 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2384)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-20 06:15 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (`fsync02` LTP test timed out, can't be related)

2021-05-20 06:38 UTC, merged