[Docs,Pal/Linux-SGX] Switch to in-kernel SGX driver as default
oscarlab/graphene pull request #2387
Opened 2021-05-19 15:14 UTC by dimakuv

## Description of the changes 

Now `ISGX_DRIVER_PATH=""` correctly implies the in-kernel SGX driver `/dev/sgx_enclave` as used in Linux versions 5.11+. Documentation and GSC are updated correspondingly (to assume Linux 5.11+ by default).

## How to test this PR? 

Try building and installing on a Linux 5.11 machine. The rest works as usual.

2021-05-19 15:53 UTC, woju requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: 1 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-Ma4I3-m4OsUHMcSF0uW:-Ma4I3-m4OsUHMcSF0uX:b92jrey) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L19)):*
> ```Python
>         # By default, using sgx_in_kernel.h in current dir of this script --
>         # this corresponds to the upstreamed in-kernel SGX driver (Linux 5.11+)
>         'sgx_in_kernel.h':            '/dev/sgx_enclave',
> ```

It's awesome, but I see an opportunity for improvement here. We should drop support for the custom patchset, then we wouldn't have problem of the same header path mapping to two different device paths, so there will be no need for vendoring `sgx_in_kernel.h`.


<!-- Sent from Reviewable.io -->

2021-05-19 17:37 UTC, jtakeshi-nd commented
Builds on Ubuntu 18.04 LTS, kernel 5.11.0-051100-generic. GCC and curl pass tests.

2021-05-19 20:05 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: 1 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-Ma4I3-m4OsUHMcSF0uW:-Ma5Db783y7D2WpAjP9_:b-16s42a) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L19)):*
> We should drop support for the custom patchset

What do you mean by "custom patchset"? Do you mean custom-built Linux kernels? I don't think we can drop support for it, it's used quite heavily (IIRC, MS Azure Confidential Compute VMs still use patched Linux 5.4 with the `/dev/sgx/enclave` version of the Intel SGX driver).


<!-- Sent from Reviewable.io -->

2021-05-20 14:35 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: 1 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-Ma4I3-m4OsUHMcSF0uW:-Ma8TslSB5012IrXK2vC:b-p9ghjg) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L19)):*
> What do you mean by "custom patchset"?

IIUC there are some patches applied to kernel 5.4 that differ from the patchset that was actually merged (at least the difference is in the device path). That's why I called them "custom".

I don't like this vendored header precisely for the reason stated in the comment (it might diverge), though it's not that bad as kernel headers are backwards compatible. Also, this script will soon be removed, and replaced with meson options (`-Dsgx_driver={upstream,dcap1.10,dcap1.6,oot}`, `-Dsgx_driver_include_path` and `-Dsgx_driver_device`), so it will be possible to override the path in `/dev`.

So IDK, what would be better? Merge this as is, and the interface will change in several weeks anyway, or wait until meson (possibly several weeks, I'm not sure how long based on the current review pace), and in the meantime fix this up using udev and symlinks?

@mkow? ^


<!-- Sent from Reviewable.io -->

2021-05-20 17:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: 1 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-Ma4I3-m4OsUHMcSF0uW:-Ma9l9nC7FcpAQD4d2jf:bhhn7q8) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L19)):*
> Merge this as is, and the interface will change in several weeks anyway, or wait until meson

I don't have a strong opinion here, I could also wait for Meson. But I created this PR because several independent users wrote about this weirdness, so I am inclined to merge it now and wait for your fix in Meson (which I definitely prefer).


<!-- Sent from Reviewable.io -->

2021-05-20 18:14 UTC, woju approved these changes
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: 3 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-Ma4I3-m4OsUHMcSF0uW:-Ma9xs0zAwuHFAp7VBIe:bhgnkna) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Merge this as is, and the interface will change in several weeks anyway, or wait until meson

I don't have a strong opinion here, I could also wait for Meson. But I created this PR because several independent users wrote about this weirdness, so I am inclined to merge it now and wait for your fix in Meson (which I definitely prefer).
</blockquote></details>

OK, so let's merge, but expect those users to brace for more weirdness soon.


<!-- Sent from Reviewable.io -->

2021-05-22 16:25 UTC, mkow requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-Ma4I3-m4OsUHMcSF0uW:-MaJr0_G-oRNOB5_qFcP:bd13m49) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L19)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, so let's merge, but expect those users to brace for more weirdness soon.
</blockquote></details>

I really don't like this `sgx_in_kernel.h` copied into our sources, but if it's a real problem for our users, then I'm fine with this temporary hack. I hope we could get rid of it with Woju's changes.
___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-MaJs2Tw-qK2CH6xz8Ce:-MaJs2TxAuH2nWAptbC3:b-lr90rk) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L78)):*
> ```
> define a complete path
> ```

nitpick: we're defining the variable, not the path ;) So, I think it should be "specify", not "define".


<!-- Sent from Reviewable.io -->

2021-05-24 18:20 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

___
*[Pal/src/host/Linux-SGX/link-intel-driver.py, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2387#-MaJs2Tw-qK2CH6xz8Ce:-MaUaORo8XytuT6VGnGP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/765409f8c67c8779ab016d3a85259327955bd05e/Pal/src/host/Linux-SGX/link-intel-driver.py#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> define a complete path
> ```

nitpick: we're defining the variable, not the path ;) So, I think it should be "specify", not "define".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-24 18:23 UTC, woju approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-05-24 21:33 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2387)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-24 21:34 UTC, merged