[Pal/Linux-SGX] Use AES-CMAC for key derivation in Protected Files
oscarlab/graphene pull request #2390
Opened 2021-05-21 10:44 UTC by dimakuv

## Description of the changes 

Protected FS previously used AES-GCM (with empty output argument, using the MAC as the derived key) as a KDF. This is cryptographically wrong. This PR replaces AES-GCM with a proper AES-CMAC as a KDF.

Fixes #2386.

## How to test this PR? 

All tests must pass, especially FS tests (`make pf-test`).

2021-05-21 10:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: 0 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaDWtcaDgqZx5VGLlIq:-MaDWtcb8D7njk9eqFj8:b-p9xbcl) ([raw file](https://github.com/oscarlab/graphene/blob/75962a812d686e839fabe5d9525e52128a8f1c86/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L128)):*
> ```C
> 
>     status = g_cb_aes_gcm_encrypt(&pf->user_kdk_key, &g_empty_iv, &buf, sizeof(buf), NULL, 0, NULL,
>                                   output);
> ```

FYI: This was the bug.


<!-- Sent from Reviewable.io -->

2021-05-21 16:38 UTC, mkow requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEgygpEbmJPu0InIU0:-MaEgygpEbmJPu0InIU1:bovx0is) (no related file):*
> This is cryptographically wrong.

I don't see how is this wrong, but I also don't see how is it correct and overall it looks a bit fishy, probably just an implementation bug. So, the change is definitely good, but please either say in the commit message why the old code was wrong or instead just say that it lacked any proof and we're changing it to a NIST-recommended construction.

---
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEfwB4C8JqQIeuBV8B:-MaEfwB4C8JqQIeuBV8C:b-nv8et1) ([raw file](https://github.com/oscarlab/graphene/blob/d128f893c79e39795061a8032f0c82191969251a/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L106)):*
> ```C
> // https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-108.pdf
> 
> // derive a metadata key from user key (if restore is false, the derived key is randomized)
> ```

While we're here, can we remove this nonsensical `restore==false` mode and just use `ipf_generate_random_key` instead? Will simplify this function considerably.
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEkfw-5B1B60rBnXJv:-MaEkfw0AOH1QiIJ-rhA:b16twav) ([raw file](https://github.com/oscarlab/graphene/blob/d128f893c79e39795061a8032f0c82191969251a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L62)):*
> ```C
>     buf.index = 1;
>     strncpy(buf.label, METADATA_KEY_NAME, MAX_LABEL_SIZE);
>     memcpy(&buf.nonce, key_id, sizeof(buf.nonce));
> ```

While we're here, could we use `COPY_ARRAY` to ensure that the types match? The current version looks quite dangerous. I know it's just a test, but this code may be reused later and we may regret this :)


<!-- Sent from Reviewable.io -->

2021-05-25 07:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: 4 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEgygpEbmJPu0InIU0:-MaXLargC-Vm_KREVTnf:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is cryptographically wrong.

I don't see how is this wrong, but I also don't see how is it correct and overall it looks a bit fishy, probably just an implementation bug. So, the change is definitely good, but please either say in the commit message why the old code was wrong or instead just say that it lacked any proof and we're changing it to a NIST-recommended construction.
</blockquote></details>

Done.

---
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEfwB4C8JqQIeuBV8B:-MaXHip090GJDgyx7CJ_:bnooqpn) ([raw file](https://github.com/oscarlab/graphene/blob/d128f893c79e39795061a8032f0c82191969251a/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L106)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're here, can we remove this nonsensical `restore==false` mode and just use `ipf_generate_random_key` instead? Will simplify this function considerably.
</blockquote></details>

No, we can't do it. `restore` is essential for the Protected Files functioning.

I updated the comment to explain better what `restore` does. I would rename it to something like `derive_from_key_id` or `use_key_id_as_nonce` but this would be a departure from Intel SGX SDK's names. I dislike Intel SGX SDK names, but at least it is easy to cross-check our implementation against that implementation. So I'd prefer not to rename stuff here.
___
*[Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEkfw-5B1B60rBnXJv:-MaXKcdZ0laJ0XGZxGwz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d128f893c79e39795061a8032f0c82191969251a/Pal/src/host/Linux-SGX/tools/pf_tamper/pf_tamper.c#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

While we're here, could we use `COPY_ARRAY` to ensure that the types match? The current version looks quite dangerous. I know it's just a test, but this code may be reused later and we may regret this :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 12:49 UTC, mkow requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEfwB4C8JqQIeuBV8B:-MaYYpVF9094UG3DkMXd:b-e4rx0u) ([raw file](https://github.com/oscarlab/graphene/blob/d128f893c79e39795061a8032f0c82191969251a/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, we can't do it. `restore` is essential for the Protected Files functioning.

I updated the comment to explain better what `restore` does. I would rename it to something like `derive_from_key_id` or `use_key_id_as_nonce` but this would be a departure from Intel SGX SDK's names. I dislike Intel SGX SDK names, but at least it is easy to cross-check our implementation against that implementation. So I'd prefer not to rename stuff here.
</blockquote></details>

But why would you ever call this function with `restore == false`? It just generates a random key in a very weird manner, instead of just calling `ipf_generate_random_key`.
IMO this just obfuscates the whole logic. I want to see in such callsites that it's just generating a completely new, random key, not a weird call for which I need to remember or the operation modes to notice that it's just a `get_random()` call.


<!-- Sent from Reviewable.io -->

2021-05-25 14:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEfwB4C8JqQIeuBV8B:-MaYswfg54iQB1PM7j0J:b-7znpqe) ([raw file](https://github.com/oscarlab/graphene/blob/d128f893c79e39795061a8032f0c82191969251a/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I looked deeper into this logic, and it goes like this:

There is a single METADATA BLOCK in each Protected File. We have a single master key (stored in `pf->user_kdk_key`) and several Protected Files. So we need to derive a "root key" for each Protected File from this master key.

For derivation, we use the algorithm from NIST 800-108. This is what this weird logic does, with label, nonce, length and doing AES-CMAC over this mix.

Now there are two cases we want to cover:
1. Creating the new Protected File or updating it. In this case, we need a new randomized "root key" for the protected file, derived from `user_kdk_key`. We also **need to store the nonce** used in KDF as the `file_metadata.plain_part.metadata_key_id`, so that we can derive the exact same key later (when we re-open the file). This is the case of `restore == false`.
2. Opening the existing Protected File. We need to derive the exact same key as used before, given the same `user_kdk_key`. This is achieved by taking not a random nonce, but a nonce stored in `file_metadata.plain_part.metadata_key_id`. This is the case of `restore == true`.

So I think the part that you missed here is: we create a random key using a `KDF(user_kdk_key, nonce)` and we store `nonce` in the plaintext part of the METADATA BLOCK of the Protected File (for future re-open and decryption).

We can't use `ipf_generate_random_key()` because we need the "root key", which can be derived from some known nonce.
</blockquote></details>

Ah, I missed that part with storing the nonce and thought that it's discarded. Makes much more sense now. Could you explain this briefly in the comment about `restore == false`?


<!-- Sent from Reviewable.io -->

2021-05-25 15:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/2390#-MaEfwB4C8JqQIeuBV8B:-MaZ8xIR-6Ey7zwoIsph:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d128f893c79e39795061a8032f0c82191969251a/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L106)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I missed that part with storing the nonce and thought that it's discarded. Makes much more sense now. Could you explain this briefly in the comment about `restore == false`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 15:38 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-25 17:25 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (`clone06` LTP test failed with `read from pipe failed: errno=EINTR(4): Interrupted system call`, probably will be fixed by https://github.com/oscarlab/graphene/pull/2392)

2021-05-26 12:42 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2390)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-26 13:04 UTC, merged