[LibOS] Rewrite `test_user_memory` and `test_user_string`
oscarlab/graphene pull request #2394
Opened 2021-05-25 02:23 UTC by boryspoplawski

## Description of the changes 
For the details check commit message and comments in code.

## How to test this PR? 
Old tests should be enough.

2021-05-25 02:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: 0 of 33 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 416 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaWLOrc0e1XS-mBk9WG:-MaWLOrdE_LIP5PQ9oKV:bed0ukg) ([raw file](https://github.com/oscarlab/graphene/blob/9c95f7b67a96cff4164ac3ea7227495d0349d403/LibOS/shim/src/bookkeep/shim_signal.c#L416)):*
> ```C
>  *
>  * The second option is faster in fault-free case but cannot be used under
>  * SGX PAL. We use the best option for each PAL for now. */
> ```

For small sizes (I wound say < 256 bytes) the first option might be indeed faster, but for bigger the VMAs traverse should be faster, as long as there is no lock contention (which basically means these checks are not don't concurrently by many threads).

In any way, if one cares so much about performance of emulated syscalls, they should disable these checks with `libos.check_invalid_pointers` and not pass weird pointers to syscalls.
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 167 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaWKkmW62vHCKm648l5:-MaWKkmW62vHCKm648l6:b3ag1xe) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/bookkeep/shim_vma.c#L167)):*
> ```C
> 
>     struct shim_vma* prev = NULL;
>     bool is_continuous = vma->begin <= begin;
> ```

This is actually a bugfix.


<!-- Sent from Reviewable.io -->

2021-05-25 09:05 UTC, dimakuv requested changes
> Reviewed 33 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 427 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXiM3Y84lgXDqoikAT:-MaXiM3Y84lgXDqoikAU:b7dve1b) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/bookkeep/shim_signal.c#L427)):*
> ```C
>     assert(next_page_addr != addr);
> 
>     size_t len = addr < next_page_addr ? (size_t)(next_page_addr - addr) : -(uintptr_t)addr;
> ```

What is this `-addr` in the else branch here? Is this a hack to force `access_ok()` to return false on wrap around? If yes, then why not simply add `if (next_page_addr <= addr)` check? This would be much more readable.
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 1104 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXgddoASkzXuODHqWb:-MaXgddoASkzXuODHqWc:b-axsfn2) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/bookkeep/shim_vma.c#L1104)):*
> ```C
>     spinlock_unlock(&vma_tree_lock);
> 
>     return is_continuous && ctx.is_ok;
> ```

Awesome code!
___
*[LibOS/shim/src/sys/shim_epoll.c, line 151 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXjKPc8beMCwm8rIW_:-MaXjKPc8beMCwm8rIWa:b60ovxy) ([raw file](https://github.com/oscarlab/graphene/blob/9c95f7b67a96cff4164ac3ea7227495d0349d403/LibOS/shim/src/sys/shim_epoll.c#L151)):*
> ```C
>         if (test_user_memory(event, sizeof(*event), false)) {
>             /* surprisingly, man(epoll_ctl) does not specify EFAULT if event is invalid so
>              * we re-use EINVAL; also note that EPOLL_CTL_DEL ignores event completely */
> ```

Why did you remove this comment? I know that we kinda "expand" on actually-defined-by-linux error codes in Graphene; was that you reasoning? ("We already return these extra error codes in other places, so why not do it here as well")
___
*[LibOS/shim/src/sys/shim_mmap.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXkRJx26GC5OxmLN6R:-MaXkRJy4pyv0w82N46N:b5cobgm) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/sys/shim_mmap.c#L314)):*
> ```C
>         return -EFAULT;
> 
>     if (!is_in_adjacent_user_vmas(addr, len, /*prot=*/0)) {
> ```

Does this even make sense? We already check `is_user_memory_readable(addr, len)` above which subsumes this check, no?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 483 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXlIcv4rVDk9OJf-DX:-MaXlIcv4rVDk9OJf-DY:b-m1zqfa) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/Pal/src/host/Linux-SGX/db_files.c#L483)):*
> ```C
>             if (read_size > MAX_READ_SIZE) {
>                 read_size = MAX_READ_SIZE;
>             }
> ```

Why not simply `MAX(total_size - bytes_read, MAX_READ_SIZE)`?


<!-- Sent from Reviewable.io -->

2021-05-25 12:54 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 427 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXiM3Y84lgXDqoikAT:-MaYSE39EakkIeI-u_-a:bcv7krh) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/bookkeep/shim_signal.c#L427)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `-addr` in the else branch here? Is this a hack to force `access_ok()` to return false on wrap around? If yes, then why not simply add `if (next_page_addr <= addr)` check? This would be much more readable.
</blockquote></details>

Because `next_page_addr` could wrap around and that's not an error, as long as the string ends before that (i.e. string itself does not wrap around). `-addr == 0-addr == MAX_ADDR+1-addr` mod `2**number_of_bits_in_addr` - it's just length left till wrap around.
___
*[LibOS/shim/src/sys/shim_epoll.c, line 151 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXjKPc8beMCwm8rIW_:-MaYTBTg4wupQ0JyA8A4:bn58bt2) ([raw file](https://github.com/oscarlab/graphene/blob/9c95f7b67a96cff4164ac3ea7227495d0349d403/LibOS/shim/src/sys/shim_epoll.c#L151)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this comment? I know that we kinda "expand" on actually-defined-by-linux error codes in Graphene; was that you reasoning? ("We already return these extra error codes in other places, so why not do it here as well")
</blockquote></details>

The comment was misleading: the man page does not mention `EFAULT`, but that's the error code that Linux actually returns and we are emulating Linux, not whatever Linux manpages describe.
___
*[LibOS/shim/src/sys/shim_mmap.c, line 314 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXkRJx26GC5OxmLN6R:-MaYTuXi3vmpwsVfHvRd:bgm9zci) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/sys/shim_mmap.c#L314)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does this even make sense? We already check `is_user_memory_readable(addr, len)` above which subsumes this check, no?
</blockquote></details>

True, I think the first `is_user_memory_readable` is not needed.
Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 483 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXlIcv4rVDk9OJf-DX:-MaYVg87C6cq0n-lKK4M:bpt5il0) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/Pal/src/host/Linux-SGX/db_files.c#L483)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not simply `MAX(total_size - bytes_read, MAX_READ_SIZE)`?
</blockquote></details>

I've just realized that the issue I had was both `butes_read` and `total_size` being signed for no good reason.
Rewrote.


<!-- Sent from Reviewable.io -->

2021-05-25 13:38 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 427 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXiM3Y84lgXDqoikAT:-MaYirJ56SP1g8__2BI0:bjk41j7) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/bookkeep/shim_signal.c#L427)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because `next_page_addr` could wrap around and that's not an error, as long as the string ends before that (i.e. string itself does not wrap around). `-addr == 0-addr == MAX_ADDR+1-addr` mod `2**number_of_bits_in_addr` - it's just length left till wrap around.
</blockquote></details>

OK, got it now. Maybe add a quick comment reminding that "even if `next_page_addr` wraps around, it may be still valid if string ends before that"? This wasn't obvious.


<!-- Sent from Reviewable.io -->

2021-05-25 14:28 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: 31 of 33 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 427 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaXiM3Y84lgXDqoikAT:-MaYvFSm46SUiOI73bHX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/bookkeep/shim_signal.c#L427)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, got it now. Maybe add a quick comment reminding that "even if `next_page_addr` wraps around, it may be still valid if string ends before that"? This wasn't obvious.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-25 15:19 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-05-26 15:42 UTC, mkow requested changes
finally! :partying_face: 

> Reviewed 30 of 33 files at r1, 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394#-:-Mad2CM47h0A9bd7vMdT:b-y9z9ef)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 431 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad9UmR98P4i7G71_Va:-Mad9UmR98P4i7G71_Vb:b28xm86) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/LibOS/shim/src/bookkeep/shim_signal.c#L431)):*
> ```C
>     size_t len = addr < next_page_addr ? (size_t)(next_page_addr - addr) : -(uintptr_t)addr;
>     while (1) {
>         if (!access_ok(addr, len)) {
> ```

I think this won't work in wrap around case (i.e. when `len == -addr`).
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 438 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad9ofT0uYR5WZ3f4PL:-Mad9ofT0uYR5WZ3f4PM:b-vbmtar) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/LibOS/shim/src/bookkeep/shim_signal.c#L438)):*
> ```C
>         }
> 
>         if (strnlen(addr, len) != len) {
> ```

This one probably also won't work.
___
*[LibOS/shim/src/bookkeep/shim_vma.c, line 167 at r1](https://reviewable.io/reviews/oscarlab/graphene/2394#-MaWKkmW62vHCKm648l5:-MadAzN82d19bFkWhbqp:b-7lj86y) ([raw file](https://github.com/oscarlab/graphene/blob/6ef02e34adea2f038fe16c17419db19c81cf1523/LibOS/shim/src/bookkeep/shim_vma.c#L167)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is actually a bugfix.
</blockquote></details>

oops.
___
*[LibOS/shim/src/sys/shim_getuid.c, line 103 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad4V1nBBmZaF6DPXBg:-Mad4V1nBBmZaF6DPXBh:b9pow59) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/LibOS/shim/src/sys/shim_getuid.c#L103)):*
> ```C
>         return -EINVAL;
> 
>     if (gidsetsize && !is_user_memory_writable(grouplist, gidsetsize * sizeof(gid_t)))
> ```

so, these checking funcs doesn't work with size=0?
___
*[Pal/src/host/Linux-SGX/db_files.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad7B7V4urbc-rpQme-:-Mad7B7WEmAANFJfTiXH:bp5gmub) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/Pal/src/host/Linux-SGX/db_files.c#L473)):*
> ```C
>         /* case of allowed file: simply read from underlying file descriptor into enclave memory */
>         uint64_t aligned_offset = ALLOC_ALIGN_DOWN(offset);
>         size_t total_size = ALLOC_ALIGN_UP(offset + size) - aligned_offset;
> ```

can't this overflow on 32-bit?


<!-- Sent from Reviewable.io -->

2021-05-26 23:34 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 431 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad9UmR98P4i7G71_Va:-MaduDND3xOQQ6tkrs1f:b-bw8e14) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/LibOS/shim/src/bookkeep/shim_signal.c#L431)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this won't work in wrap around case (i.e. when `len == -addr`).
</blockquote></details>

Updated.
___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 438 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad9ofT0uYR5WZ3f4PL:-MaduGFp0gLs6uGd2QHe:b80t3kf) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/LibOS/shim/src/bookkeep/shim_signal.c#L438)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This one probably also won't work.
</blockquote></details>

This should not matter anymore.
___
*[LibOS/shim/src/sys/shim_getuid.c, line 103 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad4V1nBBmZaF6DPXBg:-MaeurTeAv6la0MigIe2:bmlu3gd) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/LibOS/shim/src/sys/shim_getuid.c#L103)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

so, these checking funcs doesn't work with size=0?
</blockquote></details>

They do. I guess this was just a shortcut, since `gidsetsize == 0` is special.
Anyway, removed.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad7B7V4urbc-rpQme-:-MaexEMKD-iZwl1SAUqK:bpz52lq) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/Pal/src/host/Linux-SGX/db_files.c#L473)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

can't this overflow on 32-bit?
</blockquote></details>

It can.


<!-- Sent from Reviewable.io -->

2021-05-27 01:21 UTC, mkow requested changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 428 at r4](https://reviewable.io/reviews/oscarlab/graphene/2394#-MafNVp93qz2YueCPu6T:-MafNVp93qz2YueCPu6U:b3eht25) ([raw file](https://github.com/oscarlab/graphene/blob/4fd47abd6e87a4c3b3f024a75b54278b0f540fc2/LibOS/shim/src/bookkeep/shim_signal.c#L428)):*
> ```
> Subtracting these two pointers would be illegal in C though, hence the casts.
> ```

I think they still don't make them legal, imagine e.g. having pointers which are actually some bitfields (e.g. tagged pointers). But I guess we can neglect this for now.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad7B7V4urbc-rpQme-:-MafOmD531WA2M9HzL9k:b-eb9k1x) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/Pal/src/host/Linux-SGX/db_files.c#L473)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It can.
</blockquote></details>

Hmm, not this code started to look weird... So, I noticed that at this point we already have `mem` allocated and it has size `size`, so we don't need to check for `size > SIZE_MAX`. But then, aren't we reading _more_ than `size` to the buffer? (`total_size`)
Am I missing something?


<!-- Sent from Reviewable.io -->

2021-05-27 01:26 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 428 at r4](https://reviewable.io/reviews/oscarlab/graphene/2394#-MafNVp93qz2YueCPu6T:-MafPgnH4N-Pc9wc_WwO:b-785sr) ([raw file](https://github.com/oscarlab/graphene/blob/4fd47abd6e87a4c3b3f024a75b54278b0f540fc2/LibOS/shim/src/bookkeep/shim_signal.c#L428)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Subtracting these two pointers would be illegal in C though, hence the casts.
> ```

I think they still don't make them legal, imagine e.g. having pointers which are actually some bitfields (e.g. tagged pointers). But I guess we can neglect this for now.
</blockquote></details>

That would make the arithmetic on pointers casted to `uintptr_t` illegal in any case (e.g. even if both pointed inside one small object in memory). Is that the case? I hope not...
___
*[Pal/src/host/Linux-SGX/db_files.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad7B7V4urbc-rpQme-:-MafQC7R5mno7E7Ras3J:btoni7t) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/Pal/src/host/Linux-SGX/db_files.c#L473)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, not this code started to look weird... So, I noticed that at this point we already have `mem` allocated and it has size `size`, so we don't need to check for `size > SIZE_MAX`. But then, aren't we reading _more_ than `size` to the buffer? (`total_size`)
Am I missing something?
</blockquote></details>

Typo (actually copy-paste fail), that was supposed to be `total_size`.


<!-- Sent from Reviewable.io -->

2021-05-27 01:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: 34 of 35 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad7B7V4urbc-rpQme-:-MafTeWbE1gBw-lJ4GxH:b-a0q2iv) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/Pal/src/host/Linux-SGX/db_files.c#L473)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Typo (actually copy-paste fail), that was supposed to be `total_size`.
</blockquote></details>

Something's seriously wrong with this function. TODO: check it (and fix that bof...)


<!-- Sent from Reviewable.io -->

2021-05-27 07:47 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-05-28 01:18 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: 34 of 37 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/db_rtld.c, line 207 at r6](https://reviewable.io/reviews/oscarlab/graphene/2394#-MakXaIdEHXNQ-qL8YtZ:-MakXaIe8PTUPqGAlsmM:b-qxyzkl) ([raw file](https://github.com/oscarlab/graphene/blob/5785d9e58cc6d3a1560bdff83a6f27c960c266fe/Pal/src/db_rtld.c#L207)):*
> ```C
>                 c->mapend   = ALLOC_ALIGN_UP(ph->p_vaddr + ph->p_filesz);
>                 c->dataend  = ph->p_vaddr + ph->p_filesz;
>                 c->allocend = ALLOC_ALIGN_UP(ph->p_vaddr + ph->p_memsz);
> ```

@pwmarcz Could you look at this? I kinda did this based on intuition did not really investigate this code, but judging from name and usage this should be ok.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2394#-Mad7B7V4urbc-rpQme-:-MakYEC_5U_44Z2NwwLS:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a58ad44c64290c72ce73a69ecb7f2e1114f60fa1/Pal/src/host/Linux-SGX/db_files.c#L473)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Something's seriously wrong with this function. TODO: check it (and fix that bof...)
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_files.c, line 464 at r6](https://reviewable.io/reviews/oscarlab/graphene/2394#-MakY7Za3DkblmC4RBkr:-MakY7Zb5bldUFg9jNP5:b-cpz60h) ([raw file](https://github.com/oscarlab/graphene/blob/5785d9e58cc6d3a1560bdff83a6f27c960c266fe/Pal/src/host/Linux-SGX/db_files.c#L464)):*
> ```C
>         }
> 
>         /* FIXME: doesn't this overflow `mem`? It has only `size` bytes which could be less than
> ```

Could any of you guys pick this up? I have too much to do atm...


<!-- Sent from Reviewable.io -->

2021-05-31 07:11 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 464 at r6](https://reviewable.io/reviews/oscarlab/graphene/2394#-MakY7Za3DkblmC4RBkr:-Mb0E2g63Zg5eo3WXJ_z:b-ctd8g8) ([raw file](https://github.com/oscarlab/graphene/blob/5785d9e58cc6d3a1560bdff83a6f27c960c266fe/Pal/src/host/Linux-SGX/db_files.c#L464)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could any of you guys pick this up? I have too much to do atm...
</blockquote></details>

I looked into this, and I don't think we have any issue with the current code.

- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L480 -- here is the `copy_and_verify_trusted_file()` implementation
- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L499 -- here is the only place where `file_size` is used (== `handle->file.total`)

Note that we have `end = MIN(offset + size, handle->file.total)`, so it is the smallest from the "requested end of data" (`offset + size`) and "actual file end" (`handle->file.total`). This `end` **limits** how much data can be copied into enclave memory `mem`. You can see that `copy_and_verify_trusted_file()` always consults this `end` argument:

- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L509
- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L531

So there is no buffer overflow of `mem`. Looks good to me, and your FIXME comment can be removed.


<!-- Sent from Reviewable.io -->

2021-05-31 10:54 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/db_rtld.c, line 207 at r6](https://reviewable.io/reviews/oscarlab/graphene/2394#-MakXaIdEHXNQ-qL8YtZ:-Mb11U9g3wgN8tfUlTEe:b-qrxfmh) ([raw file](https://github.com/oscarlab/graphene/blob/5785d9e58cc6d3a1560bdff83a6f27c960c266fe/Pal/src/db_rtld.c#L207)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@pwmarcz Could you look at this? I kinda did this based on intuition did not really investigate this code, but judging from name and usage this should be ok.
</blockquote></details>

This is the PAL code I did not touch yet, but I did the same align-up in my rewrite of LibOS code (`shim_rtld.c`). Looks OK.


<!-- Sent from Reviewable.io -->

2021-05-31 15:51 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_files.c, line 464 at r6](https://reviewable.io/reviews/oscarlab/graphene/2394#-MakY7Za3DkblmC4RBkr:-Mb26dX9EgCO7tlv1yhJ:bz1j2an) ([raw file](https://github.com/oscarlab/graphene/blob/5785d9e58cc6d3a1560bdff83a6f27c960c266fe/Pal/src/host/Linux-SGX/db_files.c#L464)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I looked into this, and I don't think we have any issue with the current code.

- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L480 -- here is the `copy_and_verify_trusted_file()` implementation
- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L499 -- here is the only place where `file_size` is used (== `handle->file.total`)

Note that we have `end = MIN(offset + size, handle->file.total)`, so it is the smallest from the "requested end of data" (`offset + size`) and "actual file end" (`handle->file.total`). This `end` **limits** how much data can be copied into enclave memory `mem`. You can see that `copy_and_verify_trusted_file()` always consults this `end` argument:

- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L509
- https://github.com/oscarlab/graphene/blob/5717e748d0abbca504befd7cdb67d045d50c4634/Pal/src/host/Linux-SGX/enclave_framework.c#L531

So there is no buffer overflow of `mem`. Looks good to me, and your FIXME comment can be removed.
</blockquote></details>

Thanks!
That function seems overly complicated to me tho...


<!-- Sent from Reviewable.io -->

2021-05-31 16:06 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 428 at r4](https://reviewable.io/reviews/oscarlab/graphene/2394#-MafNVp93qz2YueCPu6T:-MafS9vN5bN70pzzggPB:bcd5p9u) ([raw file](https://github.com/oscarlab/graphene/blob/4fd47abd6e87a4c3b3f024a75b54278b0f540fc2/LibOS/shim/src/bookkeep/shim_signal.c#L428)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That would make the arithmetic on pointers casted to `uintptr_t` illegal in any case (e.g. even if both pointed inside one small object in memory). Is that the case? I hope not...
</blockquote></details>

I think it is? I mean, you can do this, but you can't cast it back to a pointer, I think.


<!-- Sent from Reviewable.io -->

2021-05-31 17:07 UTC, dimakuv approved these changes
> Reviewed 17 of 17 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-31 17:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2394)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/bookkeep/shim_signal.c, line 428 at r4](https://reviewable.io/reviews/oscarlab/graphene/2394#-MafNVp93qz2YueCPu6T:-Mb2QBP64a-LQksGu3IT:b-h1ddc1) ([raw file](https://github.com/oscarlab/graphene/blob/4fd47abd6e87a4c3b3f024a75b54278b0f540fc2/LibOS/shim/src/bookkeep/shim_signal.c#L428)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it is? I mean, you can do this, but you can't cast it back to a pointer, I think.
</blockquote></details>

It turns out that you are right. We use arithmetic on `uintptr_t` in some places, we should get rid of these then.


<!-- Sent from Reviewable.io -->

2021-05-31 17:17 UTC, merged