Dimakuv/rm malloc copy realloc
oscarlab/graphene pull request #2401
Opened 2021-05-27 12:26 UTC by dimakuv

## Description of the changes 

Two commits in this PR:

- [LibOS,Pal] Remove `malloc_copy` and commented-out `realloc`
- [Pal/Linux] Fix typo in macros `DATA_START` and `DATA_END`

These are a couple random changes/bug fixes I did while working on a bigger project of "LibOS + PAL + common in one binary". `realloc()` was never used in LibOS and couldn't actually be used, due to the issue of unmovable checkpoint memory. `malloc_copy()` is a weird function not used frequently, so I just re-wrote its usages.

## How to test this PR? 

All tests must pass.

2021-05-27 13:22 UTC, pwmarcz requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2401)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/db_main.c, line 125 at r1](https://reviewable.io/reviews/oscarlab/graphene/2401#-MahwyxG3T2nCURVrVaI:-MahwyxH3wxkiWBcDWqC:b-hrk8oc) ([raw file](https://github.com/oscarlab/graphene/blob/2867bf4a6822321eb2c64523cacb4de5f03de0c6/Pal/src/db_main.c#L125)):*
> ```C
>                 return -PAL_ERROR_NOMEM;
>             }
>             memcpy((char*)new_envp[idx], *orig_env, strlen(*orig_env) + 1);
> ```

This cast is confusing, it took me a while to (1) understand we're stripping away `const`, (2) understand why we're allowed to. I would prefer to create an intermediate variable:

```
char* new_env = malloc(strlen(*orig_env));
if (!new_env) { ... }
memcpy(new_env, *orig_env, strlen(*orig_env) + 1);
new_envp[idx] = new_env;
```
___
*[Pal/src/db_rtld.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2401#-MahyEtcDs4DHekKNLMU:-MahyEtcDs4DHekKNLMV:bgtejoz) ([raw file](https://github.com/oscarlab/graphene/blob/2867bf4a6822321eb2c64523cacb4de5f03de0c6/Pal/src/db_rtld.c#L66)):*
> ```C
> 
>     if (new->l_name)
>         memcpy((char*)new->l_name, realname, strlen(realname) + 1);
> ```

Looks like `l_name` shouldn't be a const, and should be freed in `free_elf_object`?

(I know this file needs a much bigger cleanup, but this seems like an easy fix.)


<!-- Sent from Reviewable.io -->

2021-05-27 13:40 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2401)* status: 7 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/src/db_main.c, line 125 at r1](https://reviewable.io/reviews/oscarlab/graphene/2401#-MahwyxG3T2nCURVrVaI:-Mai-cWiEM8MyXzLbvs9:b8jo2pb) ([raw file](https://github.com/oscarlab/graphene/blob/2867bf4a6822321eb2c64523cacb4de5f03de0c6/Pal/src/db_main.c#L125)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This cast is confusing, it took me a while to (1) understand we're stripping away `const`, (2) understand why we're allowed to. I would prefer to create an intermediate variable:

```
char* new_env = malloc(strlen(*orig_env));
if (!new_env) { ... }
memcpy(new_env, *orig_env, strlen(*orig_env) + 1);
new_envp[idx] = new_env;
```
</blockquote></details>

Done. Actually I remembed about`strdup()` :)
___
*[Pal/src/db_rtld.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2401#-MahyEtcDs4DHekKNLMU:-Mai22GO2OzsHB-m2Qer:b-q2e9xv) ([raw file](https://github.com/oscarlab/graphene/blob/2867bf4a6822321eb2c64523cacb4de5f03de0c6/Pal/src/db_rtld.c#L66)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Looks like `l_name` shouldn't be a const, and should be freed in `free_elf_object`?

(I know this file needs a much bigger cleanup, but this seems like an easy fix.)
</blockquote></details>

Done, partially. I didn't want to free it in `free_elf_object()` because in some other places it's not allocated but just points to some other var. This whole RTLD/ELF thing will go away so in PAL, so I suggest not to bother about this.


<!-- Sent from Reviewable.io -->

2021-05-27 14:06 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2401)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[Pal/src/db_main.c, line 125 at r1](https://reviewable.io/reviews/oscarlab/graphene/2401#-MahwyxG3T2nCURVrVaI:-Mai8KLQA3ihsZw9mSBr:b-wuvux5) ([raw file](https://github.com/oscarlab/graphene/blob/2867bf4a6822321eb2c64523cacb4de5f03de0c6/Pal/src/db_main.c#L125)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Actually I remembed about`strdup()` :)
</blockquote></details>

Oh, right!
___
*[Pal/src/db_rtld.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2401#-MahyEtcDs4DHekKNLMU:-Mai8TCECLYxYfCxCsWU:b-h264ww) ([raw file](https://github.com/oscarlab/graphene/blob/2867bf4a6822321eb2c64523cacb4de5f03de0c6/Pal/src/db_rtld.c#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done, partially. I didn't want to free it in `free_elf_object()` because in some other places it's not allocated but just points to some other var. This whole RTLD/ELF thing will go away so in PAL, so I suggest not to bother about this.
</blockquote></details>

Ouch. Okay, let's not touch this :)


<!-- Sent from Reviewable.io -->

2021-05-27 22:44 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2401)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_malloc.c, line 109 at r2](https://reviewable.io/reviews/oscarlab/graphene/2401#-Majzu7d7SnPfG0O-FGJ:-Majzu7d7SnPfG0O-FGK:b-yrt2v0) ([raw file](https://github.com/oscarlab/graphene/blob/8b0b7759c6ff3af09b7fc375eab7e290b889b9b7/LibOS/shim/src/shim_malloc.c#L109)):*
> ```C
> 
> #if 0
> void* realloc(void* ptr, size_t new_size) {
> ```

Would be useful to have it someday, but that's after we fix checkpointing. Anyways, I'm fine with removing it for now.
___
*[Pal/src/db_rtld.c, line 364 at r2](https://reviewable.io/reviews/oscarlab/graphene/2401#-MajzgTN5jA-iwXsiajJ:-MajzgTO9Q0A4Yg5Spqn:b-r5q2mn) ([raw file](https://github.com/oscarlab/graphene/blob/9ace1ffb0b06fa9eef6567539cf485ce7ab5a9ac/Pal/src/db_rtld.c#L364)):*
> ```C
>             l->l_ld = malloc(sizeof(ElfW(Dyn)) * l->l_ldnum);
>             if (l->l_ld)
>                 memcpy(l->l_ld, old_l_ld, sizeof(ElfW(Dyn)) * l->l_ldnum);
> ```

tbh I liked this `malloc_copy`, it simplified places like this... Especially that it removed duplication - now you need to pass the arguments twice and done make any mistakes (i.e. same size twice).


<!-- Sent from Reviewable.io -->

2021-05-31 11:45 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2401)* status: 9 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_rtld.c, line 364 at r2](https://reviewable.io/reviews/oscarlab/graphene/2401#-MajzgTN5jA-iwXsiajJ:-Mb182He5Gp4LboNCA1b:bkkehwp) ([raw file](https://github.com/oscarlab/graphene/blob/9ace1ffb0b06fa9eef6567539cf485ce7ab5a9ac/Pal/src/db_rtld.c#L364)):*
> it simplified places like this...

Neh, I would argue that the only places where `malloc_copy()` is used are the super-old IPC and RTLD code. Note that RTLD code will be purged soon-ish (hopefully). And IPC code too (by Borys). Surely there's a reason why we never used `malloc_copy()` in our new code :)
___
*[Pal/src/host/Linux/db_memory.c, line 22 at r3](https://reviewable.io/reviews/oscarlab/graphene/2401#-Mb1DxHq3zBHejoeIukg:-Mb1DxHq3zBHejoeIukh:be7i87w) ([raw file](https://github.com/oscarlab/graphene/blob/8b0b7759c6ff3af09b7fc375eab7e290b889b9b7/Pal/src/host/Linux/db_memory.c#L22)):*
> ```C
> 
> bool _DkCheckMemoryMappable(const void* addr, size_t size) {
>     return (addr < DATA_END && addr + size > TEXT_START);
> ```

FYI: This was funny. The two bugs (`addr < DATA_END` here and `DATA_END ((void*)(&__text_end))` below) negated each other, so Graphene worked correctly (by accident). In reality, `addr < DATA_END` couldn't ever work because we have a 64MB static memory pool that is counted in this `[DATA_START, DATA_END)` region and serves as normal "mappable" memory. So it is currently impossible to use `addr < DATA_END`.


<!-- Sent from Reviewable.io -->

2021-06-01 14:30 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2401)* status: 9 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/db_rtld.c, line 364 at r2](https://reviewable.io/reviews/oscarlab/graphene/2401#-MajzgTN5jA-iwXsiajJ:-Mb6yBcy3HNkvaHNYWxj:b-4xs628) ([raw file](https://github.com/oscarlab/graphene/blob/9ace1ffb0b06fa9eef6567539cf485ce7ab5a9ac/Pal/src/db_rtld.c#L364)):*
Then let's wait to get this code refactored, making it more complicated won't help in this ;)

> Surely there's a reason why we never used `malloc_copy()` in our new code :)

Isn't the reason for this that we just forgot we have it? Not that we don't like it? ;)


<!-- Sent from Reviewable.io -->

2021-06-01 15:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2401)* status: 9 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/db_rtld.c, line 364 at r2](https://reviewable.io/reviews/oscarlab/graphene/2401#-MajzgTN5jA-iwXsiajJ:-Mb76OH134gDNH75l3HX:b-2n9br4) ([raw file](https://github.com/oscarlab/graphene/blob/9ace1ffb0b06fa9eef6567539cf485ce7ab5a9ac/Pal/src/db_rtld.c#L364)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then let's wait to get this code refactored, making it more complicated won't help in this ;)

> Surely there's a reason why we never used `malloc_copy()` in our new code :)

Isn't the reason for this that we just forgot we have it? Not that we don't like it? ;)
</blockquote></details>

Hm, Ok. Let's put this PR on hold.


<!-- Sent from Reviewable.io -->

2021-07-02 08:56 UTC, dimakuv commented
Michal suggested that `malloc_copy()` may be useful. Anyway, this PR is very low priority, so I'm closing it for now.

2021-07-02 08:56 UTC, closed without merging