WIP: [LibOS] Split `shim_mount` and `shim_fs`
oscarlab/graphene pull request #2402
Opened 2021-05-27 13:08 UTC by pwmarcz

(I think this finally unblocks the "mount semantics" refactoring! I'm checking that right now, but it's going to be a separate PR.)

This change replaces most usages of `shim_mount` with `shim_fs`. Graphene uses the `shim_mount` structure to represent a mounted filesystem, but in most cases we're only interested in the function table.

The main reason for this change is special treatment of sockets and FIFOs: before, we replaced the `fs` field (actually `shim_mount`) for their dentries, so that they are served by a different filesystem. However, that loses information about which part of the tree the dentry actually is in.

The new solution is to store both `shim_mount` and `shim_fs` for a dentry. This follows Linux, which stores both `super_block` and `inode_iperations` for an inode, and replaces the latter in case of sockets and FIFOs. This will allow me to refactor the way mounted filesystems are represented.

As a bonus, this change removes some hacks like unwarranted usage of `*_builtin_fs` and storing filesystem type separately for checkpointing purposes.

2021-05-31 08:18 UTC, dimakuv requested changes
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 593 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0PgAeBoQgAqRJ8X38:-Mb0PgAeBoQgAqRJ8X39:b-iwm87e) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/include/shim_fs.h#L593)):*
> ```objc
>  *
>  * If the `mount` parameter is provided, the resulting dentry's `mount` field will be initialized to
>  * it, and the `fs` field will initialized to `mount->fs` (but you can override `fs` later for
> ```

`will be initialized`
___
*[LibOS/shim/include/shim_fs.h, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0PiBX-UTeRClxwiT8:-Mb0PiBX-UTeRClxwiT9:b-jkx3s3) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/include/shim_fs.h#L594)):*
> ```objc
>  * If the `mount` parameter is provided, the resulting dentry's `mount` field will be initialized to
>  * it, and the `fs` field will initialized to `mount->fs` (but you can override `fs` later for
>  * special files). Otherwise, both `mount` and `fs` parameters will be left as NULL.
> ```

What's the point of having `dentry.mount` and `dentry.fs` as NULL? Is it used in Graphene? Can we add an assert that `mount != NULL`?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0R24UB_4qdIWPSu1M:-Mb0R24UB_4qdIWPSu1N:bwn55wt) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L102)):*
> ```C
>         put_mount(mount);
>     } else {
>         exec->fs = &chroot_builtin_fs;
> ```

Actually, what is the point of this hack? If we end up here, then the executable is not really mounted, so it is like a "pseudo" file. How is this useful?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 655 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0RcV51zmFCDl5ryLR:-Mb0RcV51zmFCDl5ryLS:bh0ibil) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L655)):*
> ```C
> 
>         lock(&hdl->lock);
>         struct shim_fs* fs = hdl->fs;
> ```

Can we remove this `fs` alias and use `hdl->fs` in the below two lines of code?
___
*[LibOS/shim/src/fs/shim_fs.c, line 615 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0T3bN79pDzZBzJvb_:-Mb0T3bN79pDzZBzJvba:b-mjcm73) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/fs/shim_fs.c#L615)):*
> ```C
>  * Note that checkpointing the `shim_fs` structure copies it, instead of using a pointer to
>  * corresponding global object on the remote side. This does not waste too much memory (because each
>  * global object is only copied once), but it means that `shim_fs` objects cannot be compared by
> ```

Btw, did you check that `each global object is only copied once` is actually true? I know we have this `GET_FROM_CP_MAP(obj)` that avoids duplication of already-checkpointed objects (based on pointer value), but I never checked if this macro actually works as expected.
___
*[LibOS/shim/src/fs/pipe/fs.c, line 264 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0ULyQ1w3ElZESOIhP:-Mb0ULyQ1w3ElZESOIhQ:bdb29q1) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/fs/pipe/fs.c#L264)):*
> ```C
> 
> struct shim_fs fifo_builtin_fs = {
>     .name   = "fifo",
> ```

Why do we have hard-coded `fifo` instead of macro like `URI_TYPE_FIFO`?

Or maybe the question should be the other way around: why do we have `URI_TYPE_PIPE` instead of hard-coded `pipe`?


<!-- Sent from Reviewable.io -->

2021-05-31 11:47 UTC, pwmarcz reviewed
Rebased to fix typo in a commit message: `inode_iperations` -> `inode_operations`.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402#-:-Mb1E9Bz5OMZ3bnr5gib:b-ey8kaw)* status: 20 of 25 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_fs.h, line 593 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0PgAeBoQgAqRJ8X38:-Mb14agkEmeBXADSmx_k:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/include/shim_fs.h#L593)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`will be initialized`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 594 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0PiBX-UTeRClxwiT8:-Mb15Jbl8gshMpze7jSi:b-kgxrqz) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/include/shim_fs.h#L594)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point of having `dentry.mount` and `dentry.fs` as NULL? Is it used in Graphene? Can we add an assert that `mount != NULL`?
</blockquote></details>

There's the `g_dentry_root`, which is initialized as "mount-less" dentry. But it does not use `get_new_dentry()`.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0R24UB_4qdIWPSu1M:-Mb17oWD03A2JCEoxL5O:bfvodoj) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, what is the point of this hack? If we end up here, then the executable is not really mounted, so it is like a "pseudo" file. How is this useful?
</blockquote></details>

I removed it and I got an answer immediately by running the tests:

See the `host_root_fs` test. It mounts `/` as root, but specifies the executable as relative URI same as other tests (`file:host_root_fs`). So we're not able to determine where `host_root_fs` is in the mounted filesystem, and execute this line, initializing a dentry-less handle.

Apparently this code for finding a mount works mostly for the common case of mounting `file:.` as root, and specifying executable in relative URI.

I think a proper fix would be to deal with absolute URIs, both for executable and for mounted filesystems. The manifest may still specify to mount `file:.`, but internally we translate it to absolute path the manifest itself (probably supplied by PAL). Does that make sense?

(I'd like to leave a TODO / explanation here after we agree on something).
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 655 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0RcV51zmFCDl5ryLR:-Mb19dTB-XY5d8F154wr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L655)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove this `fs` alias and use `hdl->fs` in the below two lines of code?
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 615 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0T3bN79pDzZBzJvb_:-Mb1ByA87yV2zpsQepYm:b-gyo1x7) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/fs/shim_fs.c#L615)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, did you check that `each global object is only copied once` is actually true? I know we have this `GET_FROM_CP_MAP(obj)` that avoids duplication of already-checkpointed objects (based on pointer value), but I never checked if this macro actually works as expected.
</blockquote></details>

Yes, I added debug prints to both branches in this function and they confirm that:

```
[P26031:T1:getdents] fs chroot
[P26031:T1:getdents] fs existing chroot
[P26031:T1:getdents] fs proc
[P26031:T1:getdents] fs existing proc
[P26031:T1:getdents] fs dev
[P26031:T1:getdents] fs existing dev
[P26031:T1:getdents] fs existing chroot
[P26031:T1:getdents] fs existing chroot
[P26031:T1:getdents] fs sys
[P26031:T1:getdents] fs existing sys
[P26031:T1:getdents] fs existing chroot
[P26031:T1:getdents] fs existing chroot
[P26031:T1:getdents] fs existing chroot
[P26031:T1:getdents] fs existing chroot
```
___
*[LibOS/shim/src/fs/pipe/fs.c, line 264 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0ULyQ1w3ElZESOIhP:-Mb1DXCICZKzKadzkunO:b-7rk464) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/fs/pipe/fs.c#L264)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we have hard-coded `fifo` instead of macro like `URI_TYPE_FIFO`?

Or maybe the question should be the other way around: why do we have `URI_TYPE_PIPE` instead of hard-coded `pipe`?
</blockquote></details>

Yeah, looks inconsistent. I'd rather hardcode the name, it seems like a misuse of `URI_TYPE_*`.

(Also I found one for eventfd and changed it).


<!-- Sent from Reviewable.io -->

2021-05-31 12:24 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0R24UB_4qdIWPSu1M:-Mb1N4dr90VFJ9Ps2kzy:b-dkcje4) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L102)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I removed it and I got an answer immediately by running the tests:

See the `host_root_fs` test. It mounts `/` as root, but specifies the executable as relative URI same as other tests (`file:host_root_fs`). So we're not able to determine where `host_root_fs` is in the mounted filesystem, and execute this line, initializing a dentry-less handle.

Apparently this code for finding a mount works mostly for the common case of mounting `file:.` as root, and specifying executable in relative URI.

I think a proper fix would be to deal with absolute URIs, both for executable and for mounted filesystems. The manifest may still specify to mount `file:.`, but internally we translate it to absolute path the manifest itself (probably supplied by PAL). Does that make sense?

(I'd like to leave a TODO / explanation here after we agree on something).
</blockquote></details>

I didn't understand your proposal for a fix. Could you maybe describe on the example of `host_root_fs`? Here is the current `host_root_fs.manifest.template` for ease of discussion (I retained only the relevant lines):
```
libos.entrypoint = "file:host_root_fs"

fs.root.type = "chroot"
fs.root.path = "/"
fs.root.uri = "file:/"

sgx.trusted_files.host_root_fs = "file:host_root_fs"
```


<!-- Sent from Reviewable.io -->

2021-05-31 13:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0R24UB_4qdIWPSu1M:-Mb1XH772wB4LmoDrdXm:bedx17h) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I didn't understand your proposal for a fix. Could you maybe describe on the example of `host_root_fs`? Here is the current `host_root_fs.manifest.template` for ease of discussion (I retained only the relevant lines):
```
libos.entrypoint = "file:host_root_fs"

fs.root.type = "chroot"
fs.root.path = "/"
fs.root.uri = "file:/"

sgx.trusted_files.host_root_fs = "file:host_root_fs"
```
</blockquote></details>

OK. Following that example, let's say we run this from `/home/user/graphene/LibOS/shim/test/regression`, and all relative paths should be resolved relative to this directory.

PAL would determine that path during bootstrapping, and pass it to LibOS as something like `g_pal_control->host_cwd_uri = "file:/home/user/graphene/LibOS/shim/test/regression"`.

Then:
```c
const char* exec_uri = g_pal_control->executable;
// exec_uri = "file:host_root_fs"

exec_uri = to_abspath(g_pal_control->host_cwd_uri, exec_uri);
// exec_uri = "file:/home/user/graphene/LibOS/shim/test/regression"

struct shim_mount* mount;
const char* exec_rel_path;
find_mount(exec_uri, &mount, &exec_rel_path);
// mount = <chroot mount for />
// mount->uri = "file:/"
// exec_rel_path = "home/user/graphene/LibOS/shim/test/regression"

struct shim_dentry* dent;
path_lookupat(mount->mount_point, exec_rel_path, ..., &dent);
```

The same code would work in the "regular" case, i.e. when `fs.root.uri = "file:.", because we would also convert `mount->uri` to be an absolute. It would also work for other combinations of mount URI / mount path / executable URI that are probably broken right now.


<!-- Sent from Reviewable.io -->

2021-05-31 13:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0R24UB_4qdIWPSu1M:-Mb1aVPx8whAYwY00DBL:b87r0kx) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L102)):*
>The same code would work in the "regular" case, i.e. when `fs.root.uri = "file:."`, because we would also convert `mount->uri` to be an absolute path. 

Sorry about the typo, can't fix on Reviewable.


<!-- Sent from Reviewable.io -->

2021-05-31 17:23 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0R24UB_4qdIWPSu1M:-Mb2RpN4EvDKq5ENGutU:b-ezokot) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L102)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>The same code would work in the "regular" case, i.e. when `fs.root.uri = "file:."`, because we would also convert `mount->uri` to be an absolute path. 

Sorry about the typo, can't fix on Reviewable.
</blockquote></details>

Understood. Yes, this proposal looks good to me.


<!-- Sent from Reviewable.io -->

2021-06-01 10:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: 24 of 25 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 102 at r1](https://reviewable.io/reviews/oscarlab/graphene/2402#-Mb0R24UB_4qdIWPSu1M:-Mb62E8Q5btdnyCCPH26:b-4lwxd9) ([raw file](https://github.com/oscarlab/graphene/blob/a40082fc58823ccdd1401e33663f425a52f36445/LibOS/shim/src/bookkeep/shim_handle.c#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Understood. Yes, this proposal looks good to me.
</blockquote></details>

I added a comment to this code to explain the situation.


<!-- Sent from Reviewable.io -->

2021-06-01 12:21 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-02 15:20 UTC, mkow requested changes
> Reviewed 20 of 25 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2402#-MbC-0ii5vIld_Ltognh:-MbC-0ii5vIld_Ltogni:b-48nv97) ([raw file](https://github.com/oscarlab/graphene/blob/8fad86c04f65027800d4dc9bf27f85a70747637d/LibOS/shim/src/fs/shim_dcache.c#L473)):*
> ```C
>         new_dent->state &= ~DENTRY_LISTED;
> 
>         if (new_dent->type != S_IFIFO) {
> ```

How does this `type` field correspond to the underlying FS implementation on our side? Seems like the information in these fields overlap and may be hard to always keep them in sync?


<!-- Sent from Reviewable.io -->

2021-06-04 08:43 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 473 at r3](https://reviewable.io/reviews/oscarlab/graphene/2402#-MbC-0ii5vIld_Ltognh:-MbL6xPF6_rSmkk6aic2:bgwd71s) ([raw file](https://github.com/oscarlab/graphene/blob/8fad86c04f65027800d4dc9bf27f85a70747637d/LibOS/shim/src/fs/shim_dcache.c#L473)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How does this `type` field correspond to the underlying FS implementation on our side? Seems like the information in these fields overlap and may be hard to always keep them in sync?
</blockquote></details>

Currently, yes, unfortunately individual filesystems (mostly `chroot`) also keep some type information, and do this messy synchronization.

My goal (in a few PRs...) is to remove these extra sources of information, and always write to `type`. This already happened for file permissions.


<!-- Sent from Reviewable.io -->

2021-06-04 10:50 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-04 14:01 UTC, dimakuv approved these changes
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-04 14:04 UTC, mkow approved these changes
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2402)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-04 14:05 UTC, merged