WIP: Change mount semantics
oscarlab/graphene pull request #2403
Opened 2021-05-27 13:34 UTC by pwmarcz

## Description of the changes 

## How to test this PR?

2021-06-08 10:00 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbepTOb3R8dPddTLhcv:-MbepTOb3R8dPddTLhcw:b-e9comn) (no related file):*
> [P67026:T1:busybox] [chroot V..  1] 000000 ?---  -        ld.so.preload

Unrelated, but what does this mean?

---
___
*[LibOS/shim/include/shim_fs.h, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbepfW1CWZZ8d1LrmzD:-MbepfW1CWZZ8d1LrmzE:b8tzxu6) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L134)):*
> ```objc
> 
>     /* Parent of this dentry, within the same filesystem. Use `dentry_up` to get the dentry above
>      * (going across filesystems, if necessary). */
> ```

The comment is confusing. Do you mean that `Don't use this field directly, instead use dentry_up...`? Or do you mean that `if parent == NULL, then use dentry_up to go across filesystems (if possible)`?

UPDATE: It looks like both are used in the code. `dentry->parent` is used for relative paths, `dentry_up(dentry)` is used for absolute paths. Maybe add something like this in your comment?
___
*[LibOS/shim/include/shim_fs.h, line 143 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbetpOB2NfWguarFvFX:-MbetpOC8GqO16MKwXlX:b-f1fhax) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L143)):*
> ```objc
>     /* Filesystem mounted under this dentry. If set, this dentry is a mountpoint: filesystem
>      * operations should use `mounted->fs->root` instead of this dentry. */
>     struct shim_mount* mounted;
> ```

I find this name unreadable. First, I think it must be a boolean (due to the `-ed` ending). Then, I always confuse `dent->mount` and `dent->mounted`. Basically, `mount` means "my mount point I'm under" and `mounted` means "I am dentry where new mount point is attached".

Could we rename `mounted` to something like `attached_mount`?
___
*[LibOS/shim/include/shim_fs.h, line 304 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbeqtGQ2w7x4mys3byR:-MbeqtGR1ihRZDG9PncS:b-7dilqa) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L304)):*
> ```objc
>  *
>  * If `make_synthetic` is true, the function will also ensure that the mountpoint exists: new
>  * dentries marked with DENTRY_SYNTHETIC will be created, if necessary. This is is a departure from
> ```

`is is a` -> `is a`
___
*[LibOS/shim/include/shim_fs.h, line 310 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MberHL26aPXmnagpUu9:-MberHL26aPXmnagpUuA:bi82qds) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L310)):*
> ```objc
>  * `make_synthetic` is true).
>  */
> int mount_fs(const char* type, const char* uri, const char* mount_path, bool make_synthetic);
> ```

What is the case when the user wants `make_synthetic = false`? Why do we need such functionality (apart from the global root, but there this flag is not even checked)?
___
*[LibOS/shim/include/shim_fs.h, line 609 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mberq-6DDb0xOIX5QYi:-Mberq-6DDb0xOIX5QYj:b-xfkq9) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L609)):*
> ```objc
>  *
>  * \param parent the parent node, or NULL if this is supposed to be the mount root
>  * \param mount the mount the dentry is under
> ```

Please re-order `parent` and `mount`
___
*[LibOS/shim/src/fs/shim_fs.c, line 132 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mbeuc9F2AzgJrrLn5E6:-Mbeuc9F2AzgJrrLn5E7:b-ejy2dq) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/src/fs/shim_fs.c#L132)):*
> ```C
> 
>     log_debug("Mounting terminal device /dev/tty under /dev\n");
>     if ((ret = mount_fs("chroot", URI_PREFIX_DEV "tty", "/dev/tty", /*make_synthetic=*/true)) < 0) {
> ```

BTW, we'll need to fix this weirdness: `/dev/tty` is of chroot file type, but mounted (separately!) under `/dev`.
___
*[LibOS/shim/src/fs/shim_namei.c, line 140 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mbf-MsG200fgx9hSNPh:-Mbf-MsG200fgx9hSNPi:bl0irhn) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/src/fs/shim_namei.c#L140)):*
> ```C
>     if (!up)
>         up = g_dentry_root;
>     ret = do_path_lookupat(up, qstrgetstr(&link_target), flags, found, link_depth);
> ```

Unrelated question but how does this work? Why is the link target searched under the parent dir?
___
*[LibOS/shim/src/fs/shim_namei.c, line 364 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mbf345m2V3kliyuEXif:-Mbf345m2V3kliyuEXig:bm5u75) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/src/fs/shim_namei.c#L364)):*
> ```C
>         .link_depth = link_depth,
>     };
>     dent = NULL;
> ```

What's the point in this assignment?


<!-- Sent from Reviewable.io -->

2021-06-08 13:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: 5 of 9 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbepTOb3R8dPddTLhcv:-MbfZ0dy3a6JqTipk3VP:b-wp61og) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> [P67026:T1:busybox] [chroot V..  1] 000000 ?---  -        ld.so.preload

Unrelated, but what does this mean?
</blockquote></details>

This is a negative dentry: the code tried to open `/etc/ld.so.preload` recently, and Graphene confirmed that it does not exist.

---
___
*[LibOS/shim/include/shim_fs.h, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbepfW1CWZZ8d1LrmzD:-MbfZnHvEtjWNFJa8RGh:b-a3u8vt) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The comment is confusing. Do you mean that `Don't use this field directly, instead use dentry_up...`? Or do you mean that `if parent == NULL, then use dentry_up to go across filesystems (if possible)`?

UPDATE: It looks like both are used in the code. `dentry->parent` is used for relative paths, `dentry_up(dentry)` is used for absolute paths. Maybe add something like this in your comment?
</blockquote></details>

How about: "Parent of this dentry, but only within the same mount. If you need the dentry one level up, regardless of mounts (i.e. `..`), you should use `dentry_up()` instead."
___
*[LibOS/shim/include/shim_fs.h, line 143 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbetpOB2NfWguarFvFX:-MbfahZc1ugaLnR6UTOn:b-2bcrqf) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L143)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I find this name unreadable. First, I think it must be a boolean (due to the `-ed` ending). Then, I always confuse `dent->mount` and `dent->mounted`. Basically, `mount` means "my mount point I'm under" and `mounted` means "I am dentry where new mount point is attached".

Could we rename `mounted` to something like `attached_mount`?
</blockquote></details>

Sounds good. Changed to `attached_mount`.
___
*[LibOS/shim/include/shim_fs.h, line 304 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbeqtGQ2w7x4mys3byR:-MbfavLK3u9DxAGGVi-8:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L304)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`is is a` -> `is a`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 310 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MberHL26aPXmnagpUu9:-MbfaxIq9JFIEohvewM7:b-2v9f6m) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L310)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the case when the user wants `make_synthetic = false`? Why do we need such functionality (apart from the global root, but there this flag is not even checked)?
</blockquote></details>

I kept it around because `make_synthetic = false` gives the "standard" mount behaviour that we might want if we implement mount in Graphene.

But now that you point it out, yeah, I'd rather simplify now. Removed.
___
*[LibOS/shim/include/shim_fs.h, line 609 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mberq-6DDb0xOIX5QYi:-MbfbzYjALGngCWgskSO:by7biuu) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L609)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-order `parent` and `mount`
</blockquote></details>

Oh, right. Fixed.
___
*[LibOS/shim/src/fs/shim_namei.c, line 140 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mbf-MsG200fgx9hSNPh:-Mbfc9KHBNLT_WDNdVii:b-yi6bzm) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/src/fs/shim_namei.c#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Unrelated question but how does this work? Why is the link target searched under the parent dir?
</blockquote></details>

If the target is relative, it's relative to the directory the link is in. For instance, here we want `/foo/bar/link` to work, so we need to search the target under `/foo/bar`:

```
/
  foo/
    bar/
      link -> ../target.txt
    target.txt
```
___
*[LibOS/shim/src/fs/shim_namei.c, line 364 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mbf345m2V3kliyuEXif:-MbfdWFNEG03sxKx11Ca:beil37y) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/src/fs/shim_namei.c#L364)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What's the point in this assignment?
</blockquote></details>

The error path... but yeah, it's not used there. Removed.


<!-- Sent from Reviewable.io -->

2021-06-08 13:38 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbepfW1CWZZ8d1LrmzD:-MbfogZZ1fKbJM-4ozuK:bo1b3jj) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L134)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

How about: "Parent of this dentry, but only within the same mount. If you need the dentry one level up, regardless of mounts (i.e. `..`), you should use `dentry_up()` instead."
</blockquote></details>

Yes, this new text is better.
___
*[LibOS/shim/src/fs/shim_namei.c, line 140 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mbf-MsG200fgx9hSNPh:-MbfpW128M3P_wEEjttt:b-nzb79) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/src/fs/shim_namei.c#L140)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If the target is relative, it's relative to the directory the link is in. For instance, here we want `/foo/bar/link` to work, so we need to search the target under `/foo/bar`:

```
/
  foo/
    bar/
      link -> ../target.txt
    target.txt
```

</blockquote></details>

OK, now I see that this is only for relative link targets. And absolute link targets submitted to `do_path_lookupat()` force that function to ignore the `up` argument.


<!-- Sent from Reviewable.io -->

2021-06-08 13:53 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_fs.h, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2403#-MbepfW1CWZZ8d1LrmzD:-MbftXut8aHFutS1xl8w:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/37d75123bbfb0a36fd10cac6f1b4a02c5a1c0ed3/LibOS/shim/include/shim_fs.h#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, this new text is better.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-08 13:56 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-13 23:14 UTC, mkow requested changes
> Reviewed 5 of 9 files at r1, 3 of 4 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc1aqzJ0xJ3QoPzyaez:-Mc1aqzK-u-CxG8Qhkzb:b-ckbrxy) (no related file):*
Not sure if this is a known issue, but I l played a bit with a shell in busybox on this PR and one FS still seems to be broken:
```
/ # ls /sys
ls: sys/devices: Permission denied
```

---
___
*[LibOS/shim/include/shim_fs.h, line 293 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0P-yP3AetZx7AaE6m:-Mc0P-yQ-pPhxHDwy5OS:b-g0mtw9) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L293)):*
> ```
> converts the dentry pointed to by `mount_path` to a mountpoint
> ```

So, this means that the mounts are not stackable, like in Linux?
___
*[LibOS/shim/include/shim_fs.h, line 306 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0O-Na5e9xEBmeSptk:-Mc0O-Nb5t60jh_29B84:b-xnujiz) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L306)):*
> ```objc
>  * Graphene manifest semantics.
>  *
>  * TODO: On failure, this function does not clean the synthetic nodes it just created.
> ```

How hard is it to fix this? It's just a leftover you forgot to fix before submitting the PR, or something which needs more changes than just a few deallocations?
___
*[LibOS/shim/src/fs/shim_fs.c, line 408 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc1dNk_6hwGzkN7moPA:-Mc1dNka0rTWGqvvj3k_:b-9g8kpl) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/src/fs/shim_fs.c#L408)):*
> ```C
>     mount->mount_point = mount_point;
>     get_dentry(mount_point);
>     mount_point->attached_mount = mount;
> ```

How do you actually free this circular reference? (`mount` <-> `mount_point`) Which of these pointers is non-owning/weak-ref?
___
*[LibOS/shim/src/fs/shim_namei.c, line 261 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc6YlCS7w5CMxabC7lK:-Mc6YFRt7dozVRKd_hmX:bxis8ga) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/src/fs/shim_namei.c#L261)):*
> ```C
>         } else if (!is_final || !(lookup->flags & LOOKUP_CREATE)) {
>             return -ENOENT;
>         }
> ```

What if we don't get caught in any of the if-else branches? It has to be negative, without `LOOKUP_MAKE_SYNTHETIC`, with `is_final` and with `LOOKUP_CREATE`. So, shouldn't we create it?

// This question may not make any sense, I admit I got lost in all the logic and IFs here ;)
___
*[LibOS/shim/src/fs/shim_namei.c, line 670 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc6cpM736GJ2NYWhQSQ:-Mc6cpM736GJ2NYWhQSR:byn8sge) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/src/fs/shim_namei.c#L670)):*
> ```C
>             if (ret != -EACCES) {
>                 /* Fail on underlying lookup errors, except -EACCES (for which we will just ignore the
>                  * file). The lookup might fail with -EACCES for host symlinks pointing to inaccessible
> ```

please rewrap


<!-- Sent from Reviewable.io -->

2021-06-14 10:39 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: 8 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc1aqzJ0xJ3QoPzyaez:-Mc8oX-J8FhiYEbcX-Le:ban28gt) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not sure if this is a known issue, but I l played a bit with a shell in busybox on this PR and one FS still seems to be broken:
```
/ # ls /sys
ls: sys/devices: Permission denied
```
</blockquote></details>

Seems broken on master as well. It looks like the regression tests checks only specific paths (such as `/sys/devices/system/cpu`), and the intermediate ones do not work :(

I'm working on a pseudo-FS rewrite now. I'll make sure the tests are stronger.

---
___
*[LibOS/shim/include/shim_fs.h, line 293 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0P-yP3AetZx7AaE6m:-Mc8pfHx3CT2Hg-LeW8d:b-4b3l0c) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> converts the dentry pointed to by `mount_path` to a mountpoint
> ```

So, this means that the mounts are not stackable, like in Linux?
</blockquote></details>

They are. You can mount several filesystems under the same path:

```
mount_fs("chroot" , "file:.");                   // mount1 
mount_fs("chroot" , "file:/foo", "/mnt/x");      // mount2
mount_fs("chroot" , "file:/bar", "/mnt/x");      // mount3
```

This will attach...
* `mount1` at `g_dentry_root`,
* `mount2` at the `mount1` dentry for `mnt/x`,
* `mount3` at the root dentry of `mount2`.

This is not how Linux implements it (AFAICT Linux stores mount information separately, and looks it up in a hash table), but the BSD family does more or less that (a vnode has a "mounted here" pointer to a mount).
___
*[LibOS/shim/include/shim_fs.h, line 306 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0O-Na5e9xEBmeSptk:-Mc8ws-5AO28oUCnmuR5:b-snzoln) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L306)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How hard is it to fix this? It's just a leftover you forgot to fix before submitting the PR, or something which needs more changes than just a few deallocations?
</blockquote></details>

The problem I see is we don't track which synthetic nodes were created by us, and which were created before.

I thought about recursively removing all synthetic nodes that seem unused (i.e. are empty directories), but decided against doing it now, mostly because it's not very useful: right now we mount only on Graphene startup (so errors will be fatal), and if we implement Unix `mount()`, it will not create synthetic nodes anyway.
___
*[LibOS/shim/src/fs/shim_fs.c, line 408 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc1dNk_6hwGzkN7moPA:-Mc8yc7Q62xoxeVytevO:bptrrhg) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/src/fs/shim_fs.c#L408)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How do you actually free this circular reference? (`mount` <-> `mount_point`) Which of these pointers is non-owning/weak-ref?
</blockquote></details>

If we wanted to have some sort of cleanup, then it would probably treat the mount as a child of mountpoint (i.e. dentries and mounts form a tree). So `mount.mount_point` would be the weak reference.
___
*[LibOS/shim/src/fs/shim_namei.c, line 261 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc6YlCS7w5CMxabC7lK:-Mc93Y1U05GM1_lDYNGJ:b-gm1bvw) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/src/fs/shim_namei.c#L261)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if we don't get caught in any of the if-else branches? It has to be negative, without `LOOKUP_MAKE_SYNTHETIC`, with `is_final` and with `LOOKUP_CREATE`. So, shouldn't we create it?

// This question may not make any sense, I admit I got lost in all the logic and IFs here ;)
</blockquote></details>

`LOOKUP_CREATE` actually means "I want to create a file", so we proceed with a negative dentry.

I rewrote this condition slightly, I think it's much easier to read when flipped. And I added some explanations to these checks.
___
*[LibOS/shim/src/fs/shim_namei.c, line 670 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc6cpM736GJ2NYWhQSQ:-Mc95_c2BV9FigIBxlSl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/src/fs/shim_namei.c#L670)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please rewrap
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-14 11:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-06-14 12:37 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc1aqzJ0xJ3QoPzyaez:-Mc9VMi02ddqhtHq9EBX:bkqjmh0) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Seems broken on master as well. It looks like the regression tests checks only specific paths (such as `/sys/devices/system/cpu`), and the intermediate ones do not work :(

I'm working on a pseudo-FS rewrite now. I'll make sure the tests are stronger.
</blockquote></details>

Ok, resolving for now then.

---
___
*[LibOS/shim/include/shim_fs.h, line 293 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0P-yP3AetZx7AaE6m:-Mc9VcbA1iovvMQboUsL:b-ykkj70) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L293)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

They are. You can mount several filesystems under the same path:

```
mount_fs("chroot" , "file:.");                   // mount1 
mount_fs("chroot" , "file:/foo", "/mnt/x");      // mount2
mount_fs("chroot" , "file:/bar", "/mnt/x");      // mount3
```

This will attach...
* `mount1` at `g_dentry_root`,
* `mount2` at the `mount1` dentry for `mnt/x`,
* `mount3` at the root dentry of `mount2`.

This is not how Linux implements it (AFAICT Linux stores mount information separately, and looks it up in a hash table), but the BSD family does more or less that (a vnode has a "mounted here" pointer to a mount).
</blockquote></details>

Hmm, but the comment says that "this function converts the dentry pointed to by `mount_path`", how does this work when there's already a mountpoint there? I think I'm just confused by this comment, it reads like the directory was just overridden by the mounpoint :)
___
*[LibOS/shim/include/shim_fs.h, line 306 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0O-Na5e9xEBmeSptk:-Mc9W-XM8NQVV_FdZsCH:b5w0bmo) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L306)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The problem I see is we don't track which synthetic nodes were created by us, and which were created before.

I thought about recursively removing all synthetic nodes that seem unused (i.e. are empty directories), but decided against doing it now, mostly because it's not very useful: right now we mount only on Graphene startup (so errors will be fatal), and if we implement Unix `mount()`, it will not create synthetic nodes anyway.
</blockquote></details>

Ah, right, then it's not a big deal.
___
*[LibOS/shim/src/fs/shim_namei.c, line 261 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc6YlCS7w5CMxabC7lK:-Mc9WJBJB4gltE9ljBuT:be33irv) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/src/fs/shim_namei.c#L261)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`LOOKUP_CREATE` actually means "I want to create a file", so we proceed with a negative dentry.

I rewrote this condition slightly, I think it's much easier to read when flipped. And I added some explanations to these checks.
</blockquote></details>

Ah, I see. It's much more readable now, thanks!


<!-- Sent from Reviewable.io -->

2021-06-14 14:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 293 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0P-yP3AetZx7AaE6m:-Mc9p_yc3c0IpmG2q32_:b-rfy9fz) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L293)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but the comment says that "this function converts the dentry pointed to by `mount_path`", how does this work when there's already a mountpoint there? I think I'm just confused by this comment, it reads like the directory was just overridden by the mounpoint :)
</blockquote></details>

Right, it's better to talk about attaching, not converting. I reworded the comment, and explained stacked mounts - if you have a better idea how to make it more clear, please suggest wording.


<!-- Sent from Reviewable.io -->

2021-06-14 14:16 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs.h, line 293 at r4](https://reviewable.io/reviews/oscarlab/graphene/2403#-Mc0P-yP3AetZx7AaE6m:-Mc9sEx636yD_Ju-kQhm:b-90rp) ([raw file](https://github.com/oscarlab/graphene/blob/98aa1255146c0d6d74da03d94a5fcc92c4fd2c52/LibOS/shim/include/shim_fs.h#L293)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Right, it's better to talk about attaching, not converting. I reworded the comment, and explained stacked mounts - if you have a better idea how to make it more clear, please suggest wording.
</blockquote></details>

Yeah, much better now! :)


<!-- Sent from Reviewable.io -->

2021-06-14 16:46 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-06-14 18:03 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2403)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-14 18:04 UTC, merged