[LibOS] Support `lseek` for directories
oscarlab/graphene pull request #2406
Opened 2021-05-28 14:57 UTC by pwmarcz

## Description of the changes 

Follow up for #2383 (simplifying getdents).

## How to test this PR? 

There is a new regression test, `getdents_lseek`.

2021-05-31 08:38 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/sys/shim_open.c, line 158 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0ZldF4bRjmckotO86:-Mb0ZldF4bRjmckotO87:b-yau9da) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/src/sys/shim_open.c#L158)):*
> ```C
> }
> 
> /* See also `do_getdents` in `shim_open.c`. */
> ```

It's in the same file, so I would remove this last part of the comment
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0YIJ-2uv8p6wCIYap:-Mb0YIJ0ERLlS5uZIPjo:b-fz33ht) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L21)):*
> ```C
> #define BUF_SIZE 32
> 
> static int list_dir(const char* name, int fd, size_t buf_size) {
> ```

Could we rename `name` -> `test_name`?
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0YRxEDFmFiHzrdWrC:-Mb0YRxEDFmFiHzrdWrD:bqx4oc7) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L21)):*
> ```C
> #define BUF_SIZE 32
> 
> static int list_dir(const char* name, int fd, size_t buf_size) {
> ```

Can we just use `BUF_SIZE` macro and remove `buf_size` argument?
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0XbxUASx5y6vWYhlF:-Mb0XbxUASx5y6vWYhlG:b-3drbe3) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L38)):*
> ```C
>         }
>     } while (count > 0);
>     return count;
> ```

Why not just return `0`?
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 100 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0YzfdAHTryByiHHT3:-Mb0YzfdAHTryByiHHT4:bk4ru8p) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L100)):*
> ```C
>     printf("getdents_lseek: removing file0 and creating file%d\n", N);
> 
>     ret = unlink("root/file0");
> ```

For uniformity, it would be better to use `remove_file("root", 0)`
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0Yk3z1_EM_rd0HKO3:-Mb0Yk3z1_EM_rd0HKO4:b5w0muv) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L113)):*
> ```C
>     ret = lseek(fd, 0, SEEK_SET);
>     if (ret < 0) {
>         perror("llseek 1");
> ```

`lseek`


<!-- Sent from Reviewable.io -->

2021-05-31 11:00 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: 3 of 5 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_open.c, line 158 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0ZldF4bRjmckotO86:-Mb133M1ADqg8kAGQbiz:b-jwpwza) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/src/sys/shim_open.c#L158)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's in the same file, so I would remove this last part of the comment
</blockquote></details>

Oh, right. Removed.
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0YIJ-2uv8p6wCIYap:-Mb13FoA0lcLhLZgFlx7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could we rename `name` -> `test_name`?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0YRxEDFmFiHzrdWrC:-Mb13RIK8f59HOdwSpQN:bm3yqt3) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we just use `BUF_SIZE` macro and remove `buf_size` argument?
</blockquote></details>

OK, done.
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0XbxUASx5y6vWYhlF:-Mb13XLYCsyR47rROWhN:bctpdcc) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just return `0`?
</blockquote></details>

Makes sense. Done.
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 100 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0YzfdAHTryByiHHT3:-Mb13u6QEmcMp18E7CeQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L100)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For uniformity, it would be better to use `remove_file("root", 0)`
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/getdents_lseek.c, line 113 at r1](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb0Yk3z1_EM_rd0HKO3:-Mb13x-D2XGhHFBzI55T:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/2c67689178ac7afb43dbd153cc06628e971ce0ce/LibOS/shim/test/regression/getdents_lseek.c#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`lseek`
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-05-31 11:15 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/test/regression/getdents_lseek.c, line 102 at r2](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb17afoBo33TiIFOyse:-Mb17afp71bRi_9KQVCj:b4ea7o3) ([raw file](https://github.com/oscarlab/graphene/blob/fea2200254448deccb46bc94752815430d1e8ca3/LibOS/shim/test/regression/getdents_lseek.c#L102)):*
> ```C
>     ret = remove_file("root", 0);
>     if (ret < 0) {
>         perror("unlink");
> ```

This error message is now redundant.


<!-- Sent from Reviewable.io -->

2021-05-31 11:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/getdents_lseek.c, line 102 at r2](https://reviewable.io/reviews/oscarlab/graphene/2406#-Mb17afoBo33TiIFOyse:-Mb1FVty8KSFZjtgq1uu:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/fea2200254448deccb46bc94752815430d1e8ca3/LibOS/shim/test/regression/getdents_lseek.c#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This error message is now redundant.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-05-31 12:17 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-01 15:18 UTC, mkow approved these changes
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-01 15:46 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-01 15:56 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2406)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-01 16:39 UTC, merged