[Pal/Linux-SGX] Force CPUID values of unused XSAVE features to zero
oscarlab/graphene pull request #2409
Opened 2021-05-31 10:47 UTC by dimakuv

## Description of the changes 

Previously, if the SGX enclave didn't use an XSAVE feature (by unsetting the bit in the SECS.ATTRIBUTES.XFRM mask), the sanity check failed if the XSAVE feature was available on the CPU. This check doesn't make sense: the SGX enclave may want to "hide" some CPU features, but this doesn't mean the enclave execution must be stopped.

This PR removes this incorrect check and instead forces the corresponding CPUID return values to zero.

For more information, please consult the Intel SDM. In particular, the `CPUID` instruction description (leaf `Processor Extended State Enumeration Sub-leaves (EAX = 0DH, ECX = n, n > 1)`), and SGX sections 37.7.1 and 41.7.

Fixes #2408.

## How to test this PR? 

All tests must pass.

2021-05-31 11:13 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-18.04 please (`test-direct / apps.LTP.pipe04` timed out, not relevant to this PR since it's not an SGX pipeline)

2021-06-01 02:55 UTC, sammyne commented
When will this be merged?

2021-06-01 05:53 UTC, dimakuv commented
> When will this be merged?

@sammyne This will go through a couple reviews, and then will be merged (if everything looks fine to reviewers). I expect in a week or two.

2021-06-01 16:32 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2409)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 273 at r1](https://reviewable.io/reviews/oscarlab/graphene/2409#-Mb7C6EJ2dVkZ9i6FvRF:-Mb7C6EJ2dVkZ9i6FvRG:b-fgdwlq) ([raw file](https://github.com/oscarlab/graphene/blob/15005d87b7a3916a632c725e6fb581f209b758a9/Pal/src/host/Linux-SGX/db_misc.c#L273)):*
> ```C
>             case PKRU:
>                 if (extension_enabled(xfrm, subleaf)) {
>                     if (values[EAX] != extension_sizes_bytes[subleaf]) {
> ```

Unrelated, but shouldn't we also shield EBX here?
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2409#-Mb7PjkPAcKNHgvo3bad:-Mb7PjkQCa0XiWIhzmPb:blh148r) ([raw file](https://github.com/oscarlab/graphene/blob/15005d87b7a3916a632c725e6fb581f209b758a9/Pal/src/host/Linux-SGX/db_misc.c#L283)):*
> ```C
>                      * the beginning of the XSAVE/XRSTOR area") to zero */
>                     values[EAX] = 0;
>                     values[EBX] = 0;
> ```

@boryspoplawski Please take a look at this change, you touched this recently.


<!-- Sent from Reviewable.io -->

2021-06-01 17:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2409)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 273 at r1](https://reviewable.io/reviews/oscarlab/graphene/2409#-Mb7C6EJ2dVkZ9i6FvRF:-Mb7SQd-BHfId3O1E6p2:b5e0ez2) ([raw file](https://github.com/oscarlab/graphene/blob/15005d87b7a3916a632c725e6fb581f209b758a9/Pal/src/host/Linux-SGX/db_misc.c#L273)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Unrelated, but shouldn't we also shield EBX here?
</blockquote></details>

Yeah, I was thinking the same. Sounds like we should check EBX as well against the predefined `extension_offset_bytes`. Let me try... UPDATE: Ok, works.


<!-- Sent from Reviewable.io -->

2021-06-01 18:50 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2409)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2409#-Mb7PjkPAcKNHgvo3bad:-Mb7tF6c-E7MxMmEH9PS:b-7okzl4) ([raw file](https://github.com/oscarlab/graphene/blob/15005d87b7a3916a632c725e6fb581f209b758a9/Pal/src/host/Linux-SGX/db_misc.c#L283)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@boryspoplawski Please take a look at this change, you touched this recently.
</blockquote></details>

I did not, I only worked with asm using `xsave`.
Anyway, @dimakuv why do we need to clear that? Why cannot we leave it as it is? Shouldn't Graphene only use features enabled in xfrm (which would mean it wont care about it being set or not in cpuid leaf)?


<!-- Sent from Reviewable.io -->

2021-06-01 19:03 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2409)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 283 at r1](https://reviewable.io/reviews/oscarlab/graphene/2409#-Mb7PjkPAcKNHgvo3bad:-Mb7wkxJ3LVIG2Ir_lKD:bz0bawj) ([raw file](https://github.com/oscarlab/graphene/blob/15005d87b7a3916a632c725e6fb581f209b758a9/Pal/src/host/Linux-SGX/db_misc.c#L283)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I did not, I only worked with asm using `xsave`.
Anyway, @dimakuv why do we need to clear that? Why cannot we leave it as it is? Shouldn't Graphene only use features enabled in xfrm (which would mean it wont care about it being set or not in cpuid leaf)?
</blockquote></details>

Well, the whole idea of this function `sanity_check_cpuid()` is to forcefully overwrite the CPUID values. It's like VM virtualization: Graphene hides some CPU features that are not marked in XFRM (the enclave must never use features not listed in the SECS.ATTRIBUTES.XFRM).

So this is what we do here: we overwrite EAX/EBX of the "not marked" CPU features so that the enclave code knows: Ok, I shouldn't even try to use this. This is in line with the rest of this function (notice how this function overwrites other CPUID leaves).


<!-- Sent from Reviewable.io -->

2021-06-01 19:09 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2409)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-06-01 20:54 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2409)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-01 21:01 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2409)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-01 22:52 UTC, merged