[PAL]: Fix sysfs numa sanitization when SNC is enabled
oscarlab/graphene pull request #2412
Opened 2021-06-01 02:22 UTC by vijaydhanraj

## Description of the changes 
When sanitizing `/sys/devices/system/node/node0/distance` path in graphene we compare the count of distances with number
of nodes present. But when SNC mode is enabled, we run out of the buffer to store the distances which results in incorrect distance count and the comparison fails. This PR increases the buffer size to hold all numa distances even for special cases like SNC.

Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>

## How to test this PR? 
All tests should pass.

2021-06-01 06:15 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb5BfZ73aD7vVh1tEUi:-Mb5BfZ73aD7vVh1tEUj:b-yi9jsu) (no related file):*
Comments about the commit message:

> [PAL]

We use small letters, so it should be `[Pal]`.

> in graphene

Just remove this, it is obvious that this commit pertains to Graphene :)

> when SNC mode

Please explain what it is: `when Sub-Numa Cluster (SNC) mode`

> This PR 

This is not a PR, this is a commit. Please replace with `This commit`.

> all numa distances

`all NUMA distances`
> 

---
___
*[Pal/include/arch/x86_64/pal-arch.h, line 325 at r1](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb5CHy52Uw3Sdpju-02:-Mb5CHy63lVBsuSVTDv_:b-bgr1nn) ([raw file](https://github.com/oscarlab/graphene/blob/2a57050ae1a9f6f3a6d6cd69e8162fa3ac54092b/Pal/include/arch/x86_64/pal-arch.h#L325)):*
> ```objc
> typedef struct PAL_NUMA_TOPO_INFO_ {
>     char cpumap[PAL_SYSFS_MAP_FILESZ];
>     char distance[PAL_SYSFS_BUF_FILESZ];
> ```

Is 64 bytes definitely enough, even for future systems with more sub-NUMA domains? In other words, in the machine that you used, what was the size of this buffer? If it is e.g. 32 bytes, then 64 bytes limit sounds like enough. If it is more, I would be happier with `PAL_SYSFS_MAP_FILESZ`.


<!-- Sent from Reviewable.io -->

2021-06-01 10:52 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb6B82XD3p5v-58uadS:-Mb6B82XD3p5v-58uadT:b-7gwvzo) (no related file):*
> [PAL]:

No colon here

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb6B9Pa4levLJSXGveL:-Mb6B9Pa4levLJSXGveM:bo1255o) (no related file):*
What's SNC? Please expand this abbreviation in the commit message (I see that Dmitrii also asked about this, but I just want to be sure that you expand it in the commit message, not just here in review).

---


<!-- Sent from Reviewable.io -->

2021-06-01 17:26 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb5BfZ73aD7vVh1tEUi:-Mb7_wcfBDRkpYY-zKhX:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Comments about the commit message:

> [PAL]

We use small letters, so it should be `[Pal]`.

> in graphene

Just remove this, it is obvious that this commit pertains to Graphene :)

> when SNC mode

Please explain what it is: `when Sub-Numa Cluster (SNC) mode`

> This PR 

This is not a PR, this is a commit. Please replace with `This commit`.

> all numa distances

`all NUMA distances`
> 
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb6B82XD3p5v-58uadS:-Mb7Xs_v4e6mkL43vfY5:bb6un1j) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> [PAL]:

No colon here
</blockquote></details>

Done

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb6B9Pa4levLJSXGveL:-Mb7Xtdc35VvZ9z96lU3:b-a7m82u) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's SNC? Please expand this abbreviation in the commit message (I see that Dmitrii also asked about this, but I just want to be sure that you expand it in the commit message, not just here in review).
</blockquote></details>

Yes, I have expanded SNC in the commit message.

---
___
*[Pal/include/arch/x86_64/pal-arch.h, line 325 at r1](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb5CHy52Uw3Sdpju-02:-Mb7YAdqDvlRudwC6FVO:buqkq00) ([raw file](https://github.com/oscarlab/graphene/blob/2a57050ae1a9f6f3a6d6cd69e8162fa3ac54092b/Pal/include/arch/x86_64/pal-arch.h#L325)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is 64 bytes definitely enough, even for future systems with more sub-NUMA domains? In other words, in the machine that you used, what was the size of this buffer? If it is e.g. 32 bytes, then 64 bytes limit sounds like enough. If it is more, I would be happier with `PAL_SYSFS_MAP_FILESZ`.
</blockquote></details>

The test platform where the issue was reported has two sockets and SNC-4 clustering mode enabled. This results in `8` nodes. The NUMA distances results in something like `10 12 12 12 21 21 21 21` taking `24` bytes. I think SNC-4 is the max supported on intel platforms so unless we have a monstrous system `64` bytes should be good enough. But I am open to increasing the buffer size to `256` bytes as well.


<!-- Sent from Reviewable.io -->

2021-06-01 18:16 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Pal/include/arch/x86_64/pal-arch.h, line 325 at r1](https://reviewable.io/reviews/oscarlab/graphene/2412#-Mb5CHy52Uw3Sdpju-02:-Mb7matX-3kHNeQN35rR:b-ukk4a0) ([raw file](https://github.com/oscarlab/graphene/blob/e540fa36ed28ae7295cf067f968cc40e0e17caa4/Pal/include/arch/x86_64/pal-arch.h#L325)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

The test platform where the issue was reported has two sockets and SNC-4 clustering mode enabled. This results in `8` nodes. The NUMA distances results in something like `10 12 12 12 21 21 21 21` taking `24` bytes. I think SNC-4 is the max supported on intel platforms so unless we have a monstrous system `64` bytes should be good enough. But I am open to increasing the buffer size to `256` bytes as well.
</blockquote></details>

OK, the current limit looks good to me.


<!-- Sent from Reviewable.io -->

2021-06-01 18:16 UTC, dimakuv commented
Jenkins, test this please

2021-06-02 11:42 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-02 14:31 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-02 14:35 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-06-02 14:35 UTC, dimakuv commented
Jenkins, test this please

2021-06-02 14:36 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-02 14:37 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2412)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-02 16:33 UTC, merged