WIP: Remove `libos.entrypoint` from PAL
oscarlab/graphene pull request #2416
Opened 2021-06-01 15:16 UTC by pwmarcz

## Description of the changes 

## How to test this PR?

2021-06-02 11:42 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 0 of 38 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 96 at r2](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBWbj54A9e-shL2Jmo:-MbBWbj54A9e-shL2Jmp:brfaolx) ([raw file](https://github.com/oscarlab/graphene/blob/09ce362d595f3a129156c12beb39c83244adec97/LibOS/shim/src/bookkeep/shim_handle.c#L96)):*
> ```C
>     exec->acc_mode = MAY_READ;
> 
>     /*
> ```

FYI: this will conflict with #2402 (split `shim_mount` and `shim_fs`), once we merge either of these PRs, I'll update the other one.


<!-- Sent from Reviewable.io -->

2021-06-02 12:18 UTC, dimakuv requested changes
> Reviewed 1 of 35 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 2 of 38 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBctxfDKTG4-35JrkQ:-MbBctxfDKTG4-35JrkR:b-7awf56) (no related file):*
> Unfortunately I had to remove the executable name from log prefix (log_setprefix), because the initialization happens too early to even parse it from manifest. I could restore it by initializing twice, or passing it from PAL, but unless you consider it important, I'd rather keep it that way - I don't see a non-hacky solution.

I consider it important. I don't see a problem with calling `log_setprefix()` again after all `init_*()` functions are done. Why would that be hacky?

---


<!-- Sent from Reviewable.io -->

2021-06-02 12:30 UTC, dimakuv requested changes
> Reviewed 26 of 35 files at r1, 9 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 37 of 38 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/utils/log.c, line 33 at r3](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBeZ9vEb5jN5rsmCjC:-MbBeZ9vEb5jN5rsmCjD:b-u3ul0p) ([raw file](https://github.com/oscarlab/graphene/blob/0b814ebe4e93844f5e929271215f983ca7f229f5/LibOS/shim/src/utils/log.c#L33)):*
> ```C
>         return;
> 
>     const char* exec = g_pal_control->executable;
> ```

We could simply use `g_process.exec` name here. If there is no `g_process.exec` or its name, then we skip it in the log prefix.
___
*[Pal/include/pal/pal.h, line 240 at r3](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBg7NY2ncWqb79oE7L:-MbBg7NY2ncWqb79oE7M:bw0j3xc) ([raw file](https://github.com/oscarlab/graphene/blob/418668860229f8b0c8dc9e756c8af19ea2a26a8f/Pal/include/pal/pal.h#L240)):*
> ```objc
> 
> /*!
>  * \brief Create a new process.
> ```

The semantics of this PAL function are weird now. Could you add some more details: that it loads the same binary (LibOS library or PAL executable) and passes to it the new arguments?

Also, could you add a TODO/FIXME/NOTE that `args` is *not* used by the LibOS but only by PAL regression tests, and this should be actually removed at some point?
___
*[Pal/regression/..Bootstrap.c, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBf7b5BJFVATtsp8Te:-MbBf7b6-Ikf1waOJGOL:b-odphlg) ([raw file](https://github.com/oscarlab/graphene/blob/0b814ebe4e93844f5e929271215f983ca7f229f5/Pal/regression/..Bootstrap.c#L10)):*
> ```C
>     /* check control block */
>     /* check executable name */
>     pal_printf("Loaded Executable: %s\n", pal_control.executable);
> ```

So now PAL regression tests (and generally any Graphene version that doesn't use LibOS) do not have a "program name", right? Like, there is no way to know from a PAL regression test code what actually executes?


<!-- Sent from Reviewable.io -->

2021-06-02 13:08 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 37 of 38 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBctxfDKTG4-35JrkQ:-MbBpWD07MwUDec_G-jT:bxvxdb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Unfortunately I had to remove the executable name from log prefix (log_setprefix), because the initialization happens too early to even parse it from manifest. I could restore it by initializing twice, or passing it from PAL, but unless you consider it important, I'd rather keep it that way - I don't see a non-hacky solution.

I consider it important. I don't see a problem with calling `log_setprefix()` again after all `init_*()` functions are done. Why would that be hacky?
</blockquote></details>

+1 for doing this after we get this name set, sounds like this shouldn't be hacky?

---


<!-- Sent from Reviewable.io -->

2021-06-02 13:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 34 of 39 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBctxfDKTG4-35JrkQ:-MbBigq30rYwDDy0oMbH:b-9omny2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1 for doing this after we get this name set, sounds like this shouldn't be hacky?
</blockquote></details>

Basically adding a new dependency on the `g_process.exec` handle. But I see we already change the prefix after initializing threads, so this is not a big change.

However: we should update this after `execve()`. This is easy for the application thread, but the IPC threads continue normally after `execve()` and keep the old name. I can override the name to something like `shim`, which is a workaround, but also kind of accurate since these thread are not running application code.

Take a look at the updated code, what do you think? Here is an execution log at "debug" level for `graphene-direct fork_and_exec`:

```
warning: Manifest contains a deprecated syntax for 'loader.insecure__use_cmdline_argv' key. Please use true/false instead of 1/0
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
[P60877::] debug: Host: Linux
[P60877::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[P60877::] debug: Initial VMA region 0x78e2e981d000-0x78e2e98c8000 (LibOS) bookkeeped
[P60877::] debug: Initial VMA region 0x7ffcd27b9000-0x7ffcd27ba000 (vdso) bookkeeped
[P60877::] debug: Initial VMA region 0x7ffcd27b5000-0x7ffcd27b9000 (vvar) bookkeeped
[P60877::] debug: ASLR top address adjusted to 0x67a65201a000
[P60877::] debug: Shim loaded at 0x78e2e981d000, ready to initialize
[P60877::] debug: Mounting root as chroot filesystem: from file:. to /
[P60877::] debug: Mounting special proc filesystem: /proc
[P60877::] debug: Mounting special dev filesystem: /dev
[P60877::] debug: Mounting terminal device /dev/tty under /dev
[P60877::] debug: Mounting special sys filesystem: /sys
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc to /lib
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/bin to /bin
[P60877:T1:] debug: Mounting as chroot filesystem: from dev:/dev/kmsg to /dev/kmsg
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/usr//lib/x86_64-linux-gnu to /usr//lib/x86_64-linux-gnu
[P60877:T1:fork_and_exec] debug: Allocating stack at 0x0 (size = 262144)
[P60877:T1:fork_and_exec] debug: loading "file:fork_and_exec"
[P60877:T1:fork_and_exec] debug: adding a library for gdb: file:fork_and_exec
[P60877:T1:fork_and_exec] debug: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P60877:T1:fork_and_exec] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/ld-linux-x86-64.so.2
[P60877:T1:fork_and_exec] debug: Creating pipe: pipe.srv:60877
[P60877:T1:fork_and_exec] debug: Shim process initialized
[P60877:T1:fork_and_exec] warning: Not supported flag (0x3001) passed to arch_prctl
[P60877:i1:shim] debug: IPC worker started
[P60877:T1:fork_and_exec] debug: glibc register library /lib/libc.so.6 loaded at 0x67a651dde000
[P60877:T1:fork_and_exec] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/libc.so.6
[P60877:T1:fork_and_exec] debug: allocating checkpoint store (size = 67108864, reserve = 33554432)
[P60877:T1:fork_and_exec] debug: complete checkpointing data
[P60877:T1:fork_and_exec] debug: checkpoint of 32272 bytes created
warning: Manifest contains a deprecated syntax for 'loader.insecure__use_cmdline_argv' key. Please use true/false instead of 1/0
[P60879::] debug: Host: Linux
[P60879::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[P60879::] debug: Initial VMA region 0x715f6f5fd000-0x715f6f6a8000 (LibOS) bookkeeped
[P60879::] debug: Initial VMA region 0x7ffe287d1000-0x7ffe287d2000 (vdso) bookkeeped
[P60879::] debug: Initial VMA region 0x7ffe287cd000-0x7ffe287d1000 (vvar) bookkeeped
[P60879::] debug: ASLR top address adjusted to 0x70e55d99b000
[P60879::] debug: Shim loaded at 0x715f6f5fd000, ready to initialize
[P60879::] debug: checkpoint mapped at 0x715f6f5b7000-0x715f6f5bee10
[P60879::] debug: read checkpoint of 32272 bytes from parent
[P60879::] debug: memory entry [0x715f6f5b96c8]: 0x67a651ddc000-0x67a651dde000
[P60879::] debug: memory entry [0x715f6f5b9490]: 0x67a651f94000-0x67a651f97000
[P60879::] debug: memory entry [0x715f6f5b93f8]: 0x67a651f97000-0x67a651f9a000
[P60879::] debug: memory entry [0x715f6f5b90f0]: 0x67a651f9a000-0x67a651f9e000
[P60879::] debug: memory entry [0x715f6f5b9058]: 0x67a651f9e000-0x67a651fa0000
[P60879::] debug: memory entry [0x715f6f5b8fc0]: 0x67a651fa0000-0x67a651fa1000
[P60879::] debug: memory entry [0x715f6f5b8d88]: 0x67a651fd0000-0x67a651fd2000
[P60879::] debug: memory entry [0x715f6f5b8cf0]: 0x67a651fd2000-0x67a651fd4000
[P60879::] debug: memory entry [0x715f6f5b8958]: 0x67a651fd7000-0x67a651fd8000
[P60879::] debug: memory entry [0x715f6f5b88c0]: 0x67a651fd8000-0x67a651fd9000
[P60879::] debug: memory entry [0x715f6f5b8620]: 0x67a651fd9000-0x67a651fda000
[P60879::] debug: memory entry [0x715f6f5b8588]: 0x67a651fda000-0x67a65201a000
[P60879::] debug: memory entry [0x715f6f5b84f0]: 0x67a652a09000-0x67a652a2a000
[P60879::] debug: restored memory from checkpoint
[P60879::] debug: restoring checkpoint at 0x715f6f5b7000 rebased from 0x78e2e37ca000
[P60879:T2:fork_and_exec] debug: successfully restored checkpoint at 0x715f6f5b7000 - 0x715f6f5bee10
[P60879:T2:fork_and_exec] debug: Creating pipe: pipe.srv:60879
[P60879:T2:fork_and_exec] debug: sending IPC_MSG_CONNBACK message to 60877
[P60879:T2:fork_and_exec] debug: Sending ipc message to 60877
[P60879:T2:fork_and_exec] debug: Waiting for response (seq = 1)
[P60879:i1:shim] debug: IPC worker started
[P60877:i1:shim] debug: IPC worker: received IPC message from 60879: code=1 size=128 src=60879 dst=60877 seq=1
[P60877:i1:shim] debug: Sending ipc message to 60879
[P60879:i1:shim] debug: IPC worker: received IPC message from 60877: code=2 size=80 src=60877 dst=60879 seq=1
[P60879:T2:fork_and_exec] debug: Finished waiting for response (seq = 1, ret = 0)
[P60879:T2:fork_and_exec] debug: Shim process initialized
[P60879:T2:exec_victim] debug: Allocating stack at 0x0 (size = 262144)
[P60879:T2:exec_victim] debug: removing a library for gdb: file:fork_and_exec
[P60879:T2:exec_victim] debug: removing a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/ld-linux-x86-64.so.2
[P60879:T2:exec_victim] debug: loading "file:./exec_victim"
[P60879:T2:exec_victim] debug: adding a library for gdb: file:./exec_victim
[P60879:T2:exec_victim] debug: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P60879:T2:exec_victim] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/ld-linux-x86-64.so.2
[P60879:T2:exec_victim] debug: execve: start execution
[P60879:T2:exec_victim] warning: Not supported flag (0x3001) passed to arch_prctl
[P60879:T2:exec_victim] debug: glibc register library /lib/libc.so.6 loaded at 0x70e55d75f000
[P60879:T2:exec_victim] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/libc.so.6
Hello World (./exec_victim)!
envp['IN_EXECVE'] = 1
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 00 [...]

2021-06-02 14:47 UTC, dimakuv requested changes
> Reviewed 1 of 11 files at r2, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBctxfDKTG4-35JrkQ:-MbC9BvmA92QZb1yo8lL:bg30m4m) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Basically adding a new dependency on the `g_process.exec` handle. But I see we already change the prefix after initializing threads, so this is not a big change.

However: we should update this after `execve()`. This is easy for the application thread, but the IPC threads continue normally after `execve()` and keep the old name. I can override the name to something like `shim`, which is a workaround, but also kind of accurate since these thread are not running application code.

Take a look at the updated code, what do you think? Here is an execution log at "debug" level for `graphene-direct fork_and_exec`:

```
warning: Manifest contains a deprecated syntax for 'loader.insecure__use_cmdline_argv' key. Please use true/false instead of 1/0
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
[P60877::] debug: Host: Linux
[P60877::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[P60877::] debug: Initial VMA region 0x78e2e981d000-0x78e2e98c8000 (LibOS) bookkeeped
[P60877::] debug: Initial VMA region 0x7ffcd27b9000-0x7ffcd27ba000 (vdso) bookkeeped
[P60877::] debug: Initial VMA region 0x7ffcd27b5000-0x7ffcd27b9000 (vvar) bookkeeped
[P60877::] debug: ASLR top address adjusted to 0x67a65201a000
[P60877::] debug: Shim loaded at 0x78e2e981d000, ready to initialize
[P60877::] debug: Mounting root as chroot filesystem: from file:. to /
[P60877::] debug: Mounting special proc filesystem: /proc
[P60877::] debug: Mounting special dev filesystem: /dev
[P60877::] debug: Mounting terminal device /dev/tty under /dev
[P60877::] debug: Mounting special sys filesystem: /sys
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc to /lib
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/bin to /bin
[P60877:T1:] debug: Mounting as chroot filesystem: from dev:/dev/kmsg to /dev/kmsg
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
[P60877:T1:] debug: Mounting as chroot filesystem: from file:/usr//lib/x86_64-linux-gnu to /usr//lib/x86_64-linux-gnu
[P60877:T1:fork_and_exec] debug: Allocating stack at 0x0 (size = 262144)
[P60877:T1:fork_and_exec] debug: loading "file:fork_and_exec"
[P60877:T1:fork_and_exec] debug: adding a library for gdb: file:fork_and_exec
[P60877:T1:fork_and_exec] debug: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P60877:T1:fork_and_exec] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/ld-linux-x86-64.so.2
[P60877:T1:fork_and_exec] debug: Creating pipe: pipe.srv:60877
[P60877:T1:fork_and_exec] debug: Shim process initialized
[P60877:T1:fork_and_exec] warning: Not supported flag (0x3001) passed to arch_prctl
[P60877:i1:shim] debug: IPC worker started
[P60877:T1:fork_and_exec] debug: glibc register library /lib/libc.so.6 loaded at 0x67a651dde000
[P60877:T1:fork_and_exec] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/libc.so.6
[P60877:T1:fork_and_exec] debug: allocating checkpoint store (size = 67108864, reserve = 33554432)
[P60877:T1:fork_and_exec] debug: complete checkpointing data
[P60877:T1:fork_and_exec] debug: checkpoint of 32272 bytes created
warning: Manifest contains a deprecated syntax for 'loader.insecure__use_cmdline_argv' key. Please use true/false instead of 1/0
[P60879::] debug: Host: Linux
[P60879::] debug: LibOS xsave_enabled 1, xsave_size 0x340(832), xsave_features 0x7
[P60879::] debug: Initial VMA region 0x715f6f5fd000-0x715f6f6a8000 (LibOS) bookkeeped
[P60879::] debug: Initial VMA region 0x7ffe287d1000-0x7ffe287d2000 (vdso) bookkeeped
[P60879::] debug: Initial VMA region 0x7ffe287cd000-0x7ffe287d1000 (vvar) bookkeeped
[P60879::] debug: ASLR top address adjusted to 0x70e55d99b000
[P60879::] debug: Shim loaded at 0x715f6f5fd000, ready to initialize
[P60879::] debug: checkpoint mapped at 0x715f6f5b7000-0x715f6f5bee10
[P60879::] debug: read checkpoint of 32272 bytes from parent
[P60879::] debug: memory entry [0x715f6f5b96c8]: 0x67a651ddc000-0x67a651dde000
[P60879::] debug: memory entry [0x715f6f5b9490]: 0x67a651f94000-0x67a651f97000
[P60879::] debug: memory entry [0x715f6f5b93f8]: 0x67a651f97000-0x67a651f9a000
[P60879::] debug: memory entry [0x715f6f5b90f0]: 0x67a651f9a000-0x67a651f9e000
[P60879::] debug: memory entry [0x715f6f5b9058]: 0x67a651f9e000-0x67a651fa0000
[P60879::] debug: memory entry [0x715f6f5b8fc0]: 0x67a651fa0000-0x67a651fa1000
[P60879::] debug: memory entry [0x715f6f5b8d88]: 0x67a651fd0000-0x67a651fd2000
[P60879::] debug: memory entry [0x715f6f5b8cf0]: 0x67a651fd2000-0x67a651fd4000
[P60879::] debug: memory entry [0x715f6f5b8958]: 0x67a651fd7000-0x67a651fd8000
[P60879::] debug: memory entry [0x715f6f5b88c0]: 0x67a651fd8000-0x67a651fd9000
[P60879::] debug: memory entry [0x715f6f5b8620]: 0x67a651fd9000-0x67a651fda000
[P60879::] debug: memory entry [0x715f6f5b8588]: 0x67a651fda000-0x67a65201a000
[P60879::] debug: memory entry [0x715f6f5b84f0]: 0x67a652a09000-0x67a652a2a000
[P60879::] debug: restored memory from checkpoint
[P60879::] debug: restoring checkpoint at 0x715f6f5b7000 rebased from 0x78e2e37ca000
[P60879:T2:fork_and_exec] debug: successfully restored checkpoint at 0x715f6f5b7000 - 0x715f6f5bee10
[P60879:T2:fork_and_exec] debug: Creating pipe: pipe.srv:60879
[P60879:T2:fork_and_exec] debug: sending IPC_MSG_CONNBACK message to 60877
[P60879:T2:fork_and_exec] debug: Sending ipc message to 60877
[P60879:T2:fork_and_exec] debug: Waiting for response (seq = 1)
[P60879:i1:shim] debug: IPC worker started
[P60877:i1:shim] debug: IPC worker: received IPC message from 60879: code=1 size=128 src=60879 dst=60877 seq=1
[P60877:i1:shim] debug: Sending ipc message to 60879
[P60879:i1:shim] debug: IPC worker: received IPC message from 60877: code=2 size=80 src=60877 dst=60879 seq=1
[P60879:T2:fork_and_exec] debug: Finished waiting for response (seq = 1, ret = 0)
[P60879:T2:fork_and_exec] debug: Shim process initialized
[P60879:T2:exec_victim] debug: Allocating stack at 0x0 (size = 262144)
[P60879:T2:exec_victim] debug: removing a library for gdb: file:fork_and_exec
[P60879:T2:exec_victim] debug: removing a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/ld-linux-x86-64.so.2
[P60879:T2:exec_victim] debug: loading "file:./exec_victim"
[P60879:T2:exec_victim] debug: adding a library for gdb: file:./exec_victim
[P60879:T2:exec_victim] debug: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P60879:T2:exec_victim] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/ld-linux-x86-64.so.2
[P60879:T2:exec_victim] debug: execve: start execution
[P60879:T2:exec_victim] warning: Not supported flag (0x3001) passed to arch_prctl
[P60879:T2:exec_victim] debug: glibc register library /lib/libc.so.6 loaded at 0x70e55d75f000
[P60879:T2:exec_victim] debug: adding a library for gdb: file:/usr/local/lib/x86_64-linux-gnu/graphene/runtime/glibc/libc.so.6
Hello World (./exec_victim)!
envp['IN_EXECVE'] = 1
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000 [...]

2021-06-04 08:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 38 of 39 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 71 at r4](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbCAZAbCPnCJM2hAonu:-MbL3GJH8QlXhbEKPTWU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/af795fd9221f7b02f93040a9384b43c1fe2f149c/LibOS/shim/src/bookkeep/shim_handle.c#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need smth like `ret = -EINVAL` because `toml_string_in()` simply returns `-1`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-04 14:45 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 36 of 40 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 96 at r2](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBWbj54A9e-shL2Jmo:-MbMTwhT2owkrZBeUL_j:b-bw8e14) ([raw file](https://github.com/oscarlab/graphene/blob/09ce362d595f3a129156c12beb39c83244adec97/LibOS/shim/src/bookkeep/shim_handle.c#L96)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

FYI: this will conflict with #2402 (split `shim_mount` and `shim_fs`), once we merge either of these PRs, I'll update the other one.
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2021-06-04 17:10 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 25 of 35 files at r1, 8 of 11 files at r2, 3 of 4 files at r4, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-06-04 22:20 UTC, mkow requested changes
Great to see those loader changes finally being finished, thanks!

> Reviewed 25 of 35 files at r1, 8 of 11 files at r2, 3 of 4 files at r4, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416#-:-MbO64YuAXHI8NErQkC1:bb052uv)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbBctxfDKTG4-35JrkQ:-MbLfKdG8kxcUDzGlfqJ:b-vs1prh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like it! Yes, `shim` for internal threads sounds good to me.
</blockquote></details>

Looks good!

---
___
*[LibOS/shim/src/shim_init.c, line 436 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbNHIvu8FzfPLGYi8Sk:-MbNHIvv4O9gKJz1lSAz:b5ww69y) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/shim_init.c#L436)):*
> ```C
> 
>     /* Update log prefix after we initialized `g_process.exec` */
>     log_setprefix(shim_get_tcb());
> ```

Can we do this right after that point? (I guess it's `init_process()`?) Would be good to have this info as soon as possible.
___
*[LibOS/shim/src/utils/log.c, line 39 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO2WTZ9xIJVx81e7h_:-MbO2WT_BuoMhpRavO7J:b2600kz) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L39)):*
> ```C
>     const char* exec_name;
>     if (tcb->tp && is_internal_tid(tcb->tp->tid)) {
>         /* This is an internal thread, use "shim" as executable name */
> ```

Hmm, why should a thread matter? We're printing the executable which the whole _process_ executes, this "shim" is not really informative - you already know which threads are internal from the thread id prefix ("i" for internal), so this only hides information from users.
___
*[LibOS/shim/src/utils/log.c, line 45 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO48tx9d4nj12gkAqy:-MbO48tx9d4nj12gkAqz:b-55hxeb) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L45)):*
> ```C
>             exec_name = qstrgetstr(&g_process.exec->dentry->name);
>         } else if (!qstrempty(&g_process.exec->uri)) {
>             exec_name = qstrgetstr(&g_process.exec->uri);
> ```

When it's possible to have this entry, but not the above? (`g_process.exec->dentry`)
___
*[LibOS/shim/src/utils/log.c, line 88 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO4WVQ6CikNm05ly3X:-MbO4WVQ6CikNm05ly3Y:bd4nhve) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L88)):*
> ```C
>     }
> 
>     unlock(&g_process.fs_lock);
> ```

Could we unlock it right after it's not needed? This is a global lock, so we should hold it as short as possible.


<!-- Sent from Reviewable.io -->

2021-06-04 22:27 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/shim_init.c, line 436 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbNHIvu8FzfPLGYi8Sk:-MbO6wwE3vh9L06ontYX:b-327ez6) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/shim_init.c#L436)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we do this right after that point? (I guess it's `init_process()`?) Would be good to have this info as soon as possible.
</blockquote></details>

This is right after. `init_important_handles` does that.
___
*[LibOS/shim/src/utils/log.c, line 88 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO4WVQ6CikNm05ly3X:-MbO7cJU90LtJAPokEZh:b-9ia20j) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L88)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we unlock it right after it's not needed? This is a global lock, so we should hold it as short as possible.
</blockquote></details>

Well, it could be moved just before that `snip` if above, tho that's not much...


<!-- Sent from Reviewable.io -->

2021-06-04 22:45 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/shim_init.c, line 436 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbNHIvu8FzfPLGYi8Sk:-MbOBbtCExV6GjJwAr3g:b5a8ssi) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/shim_init.c#L436)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is right after. `init_important_handles` does that.
</blockquote></details>

ACK, resolving then.
___
*[LibOS/shim/src/utils/log.c, line 88 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO4WVQ6CikNm05ly3X:-MbOBnpA8EIt0R1xdynX:bhsuv5a) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L88)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, it could be moved just before that `snip` if above, tho that's not much...
</blockquote></details>

Ah, right, using `exec_name` requires this lock.


<!-- Sent from Reviewable.io -->

2021-06-05 10:27 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: 38 of 40 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/utils/log.c, line 39 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO2WTZ9xIJVx81e7h_:-MbQeiCe93ZJB5Y-ymhT:b6ctsgn) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L39)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, why should a thread matter? We're printing the executable which the whole _process_ executes, this "shim" is not really informative - you already know which threads are internal from the thread id prefix ("i" for internal), so this only hides information from users.
</blockquote></details>

See the discussion at the top. Unfortunately we cannot easily show an executable name here, because it changes after `execve` (and the internal processes do not have an idea about that). I proposed to use `shim` instead and @dimakuv agreed.

I added a comment explaining that here.
___
*[LibOS/shim/src/utils/log.c, line 45 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO48tx9d4nj12gkAqy:-MbQf8dtExGijCAxUr7r:b-m6la1d) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

When it's possible to have this entry, but not the above? (`g_process.exec->dentry`)
</blockquote></details>

See `init_exec_handle` - there is a case where we cannot find an executable.

This will be fixed in next PR (WIP in #2421), so I added a TODO to remove this branch.


<!-- Sent from Reviewable.io -->

2021-06-05 15:21 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/utils/log.c, line 39 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO2WTZ9xIJVx81e7h_:-MbRkd262kKwaZy1EKxF:b-uvcz4l) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L39)):*
> Looks good!

@mkow agreed there as well ;)


<!-- Sent from Reviewable.io -->

2021-06-05 20:55 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/utils/log.c, line 39 at r6](https://reviewable.io/reviews/oscarlab/graphene/2416#-MbO2WTZ9xIJVx81e7h_:-MbSuTm4670Q6gP3m7cI:b-1jp2v9) ([raw file](https://github.com/oscarlab/graphene/blob/ea0b4e721de6c2df19becdd69a0556197c963dad/LibOS/shim/src/utils/log.c#L39)):*
Ok, I get the problem now. I guess we should just have a global prefix buffer and update it atomically / with an R/W lock, this design with thread-local buffers for something which is conceptually global is weird. But we can fix it later.

> @mkow agreed there as well ;)

I didn't notice that this "shim" is for internal threads, thought that it's just used before we set the exec name.


<!-- Sent from Reviewable.io -->

2021-06-07 06:36 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, 2 of 4 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-07 07:38 UTC, dimakuv approved these changes
> Reviewed 1 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2416)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-07 08:05 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (`test_libos.TC_50_GDB.test_000_gdb_backtrace` timed out; the timeout is 10 seconds, maybe it's too small for really slow Jenkins nodes?)

2021-06-07 08:26 UTC, merged