[LibOS] Convert `libos.entrypoint` to a Graphene path
oscarlab/graphene pull request #2421
Opened 2021-06-04 09:53 UTC by pwmarcz

Follow up to #2416.

## Description of the changes 

## How to test this PR? 

The existing Jenkins builds should be enough.

2021-06-07 13:19 UTC, mkow requested changes
> Reviewed 49 of 49 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_LTD9--ma0iLJ2Th:-Mba_LTEAbnuYA2mNqGR:bayimv) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L81)):*
> ```reStructuredText
> ``/``.
> 
> Because Graphene by default mounts the current host directory at ``/``, the
> ```

I'm not sure we want to keep this behavior in the future and if we should support and recommend it. These default cwd-to-root mounts are weird and look like a footgun.
___
*[Documentation/manifest-syntax.rst, line 86 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_jQ4CwsNWPRqQjke:-Mba_jQ4CwsNWPRqQjkf:bpneqy5) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L86)):*
> ```reStructuredText
> current host directory.
> 
> *NOTE:* Earlier, ``libos.entrypoint`` was a PAL URI. If you used it with a
> ```

I think `.. note::` would look nicer, but I'm not blocking.


<!-- Sent from Reviewable.io -->

2021-06-07 13:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: 48 of 49 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_LTD9--ma0iLJ2Th:-MbackJ25KUIokelbr7B:b61j20h) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm not sure we want to keep this behavior in the future and if we should support and recommend it. These default cwd-to-root mounts are weird and look like a footgun.
</blockquote></details>

I agree. I think that in the future Graphene applications should run from a different directory (such as `/home/user` or even `/root`). This could be an implicit default, or an explicit convention that we encourage in example manifests.

That's actually why I encourage using relative paths here: if, in the future, Graphene mounts `.` at `/home/user`, and the starting PWD is also `/home/user`, then `libos.entrypoint = "busybox"` would still work (and the absolute path would break).
___
*[Documentation/manifest-syntax.rst, line 86 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_jQ4CwsNWPRqQjke:-MbafYFoCrRJ_PrlHMsu:bngkr0l) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think `.. note::` would look nicer, but I'm not blocking.
</blockquote></details>

Done, and I changed the other two `NOTE:`s to use it also.


<!-- Sent from Reviewable.io -->

2021-06-07 14:17 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[Documentation/manifest-syntax.rst, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_LTD9--ma0iLJ2Th:-Mbap7YN0MwbAW6PzRvc:b-7nzq23) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L81)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I agree. I think that in the future Graphene applications should run from a different directory (such as `/home/user` or even `/root`). This could be an implicit default, or an explicit convention that we encourage in example manifests.

That's actually why I encourage using relative paths here: if, in the future, Graphene mounts `.` at `/home/user`, and the starting PWD is also `/home/user`, then `libos.entrypoint = "busybox"` would still work (and the absolute path would break).
</blockquote></details>

Ah, I see your plan now. Makes sense.


<!-- Sent from Reviewable.io -->

2021-06-07 16:01 UTC, boryspoplawski requested changes
> Reviewed 5 of 49 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_LTD9--ma0iLJ2Th:-Mbb7SEO3CxIaYZRB7Jz:bmhgcyc) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ah, I see your plan now. Makes sense.
</blockquote></details>

IMO it should not be recommended, I would say recommended way is to mount the binary explicitly (or any of it's parent directories, of course) and not rely on this explicit `.` mount.
I dislike the idea of implicit starting CWD other than `/` (but there should be or even is atm an option to specify that in manifest).
Why can't we interpret relative paths as starting from CWD instead of "Relative paths will be interpreted as starting from `/`"?
___
*[LibOS/shim/src/sys/shim_exec.c, line 187 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-MbbBTX788FfoZyvVO1A:-MbbBTX788FfoZyvVO1B:b9050us) ([raw file](https://github.com/oscarlab/graphene/blob/293ed2032e709807bfc238728e6f55aa6c7d5d61/LibOS/shim/src/sys/shim_exec.c#L187)):*
> ```C
> reopen:
> 
>     /* XXX: Not sure what to do here yet */
> ```

A little step closer to sanity :)


<!-- Sent from Reviewable.io -->

2021-06-07 18:10 UTC, dimakuv requested changes
> Reviewed 48 of 49 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/sys/shim_exec.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mbbd_iO6UH2WbFD_l9A:-Mbbd_iP4SVo5lf6JBw4:b-gr9jee) ([raw file](https://github.com/oscarlab/graphene/blob/081ef5c983fb2545ae88b81a06d051d14a98daf5/LibOS/shim/src/sys/shim_exec.c#L200)):*
> ```C
>     }
> 
>     if (ret == -EINVAL) { /* it's a shebang */
> ```

Maybe it's time to remove this "shebang" fallback? This is probably wrong anyway and was never used/tested in Graphene. I would just purge this.

Then we'll be also able to remove the `reopen` label.
___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-MbbeXTQ0gJ_itGrwD4b:-MbbeXTQ0gJ_itGrwD4c:b-jez8iy) ([raw file](https://github.com/oscarlab/graphene/blob/081ef5c983fb2545ae88b81a06d051d14a98daf5/LibOS/shim/test/regression/host_root_fs.manifest.template#L2)):*
> ```
> loader.preload = "file:{{ graphene.libos }}"
> libos.entrypoint = "{{ env.PWD }}/host_root_fs"
> ```

How does this work? We don't propagate environment variables from the host, so who sets up the PWD variable? Glibc? Based on what?


<!-- Sent from Reviewable.io -->

2021-06-08 13:04 UTC, boryspoplawski reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-06-08 13:29 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/host_root_fs.manifest.template, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-MbbeXTQ0gJ_itGrwD4b:-Mbfo7y05_j7gj7LV3ac:bmctigb) ([raw file](https://github.com/oscarlab/graphene/blob/081ef5c983fb2545ae88b81a06d051d14a98daf5/LibOS/shim/test/regression/host_root_fs.manifest.template#L2)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is `host_root_fs.manifest.template`, and it's compiled using Jinja to `host_root_fs.manifest`. Jinja expands `env.PWD` (interpreting it as `os.environ['PWD']`) to the right path. Unfortunately the resulting manifest file is "non-relocatable", but I think the harm is relatively minor since it's only a test.
</blockquote></details>

OK, true.


<!-- Sent from Reviewable.io -->

2021-06-08 13:31 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_exec.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mbbd_iO6UH2WbFD_l9A:-MbfjqN_AFAKzkgd9glV:buqw86z) ([raw file](https://github.com/oscarlab/graphene/blob/081ef5c983fb2545ae88b81a06d051d14a98daf5/LibOS/shim/src/sys/shim_exec.c#L200)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sure, I didn't know it's unused. Happy to remove.
</blockquote></details>

Done.

I checked (using Python and `os.execve()`) and it doesn't work: the `do_handle_read` here does not start at offset 0. I think I was the one to break it, a few months ago: the ELF parsing code was rewinding the handle before.

I could try and fix it, but seeing how it's ugly, untested and most likely unused (nobody is complaining), removing seems to be the best option.


<!-- Sent from Reviewable.io -->

2021-06-08 13:36 UTC, mkow reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_LTD9--ma0iLJ2Th:-MbfpNUF90unpmPdsJqH:bumc8lt) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L81)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>I dislike the idea of implicit starting CWD other than `/` (but there should be or even is atm an option to specify that in manifest).

I did not know there is an option! I found it: `fs.start_dir`. It even seems to work.

>Why can't we interpret relative paths as starting from CWD instead of "Relative paths will be interpreted as starting from `/`"?

It's actually the CWD, I just thought it's hardcoded to `/` :) I reworded that bit.

>IMO it should not be recommended, I would say recommended way is to mount the binary explicitly (or any of it's parent directories, of course) and not rely on this explicit . mount.

I don't want to rewrite *all* the manifests now, but maybe I could rewrite an example or two, and add a recommedation here.

How about:

```toml
# The recommended usage is to provide an absolute path, and
# mount the executable at that path. For example:

    libos.entrypoint = "/bin/busybox"

    [fs.mount.busybox]
    type = "chroot"
    path = "/bin/busybox"
    # Or "file:/usr/sbin/busybox" if Busybox is installed system-wide on host
    uri = "file:busybox"
```
</blockquote></details>

The snippet looks good to me.


<!-- Sent from Reviewable.io -->

2021-06-08 13:43 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: 47 of 49 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Documentation/manifest-syntax.rst, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mba_LTD9--ma0iLJ2Th:-MbfoyaTAKyecdn7TN7E:b-5ctwpk) ([raw file](https://github.com/oscarlab/graphene/blob/e239ed77fa1bbf34cdbbe5577494d384979c5275/Documentation/manifest-syntax.rst#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The snippet looks good to me.
</blockquote></details>

Done, with some modifications: I used Python as an example (with the same syntax as in our `python.manifest`), and assumed that the default is to use system-wide binary from host.


<!-- Sent from Reviewable.io -->

2021-06-08 13:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: 47 of 49 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_exec.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mbbd_iO6UH2WbFD_l9A:-Mbfss-u8KIzk9aLFC6L:b-by3jck) ([raw file](https://github.com/oscarlab/graphene/blob/081ef5c983fb2545ae88b81a06d051d14a98daf5/LibOS/shim/src/sys/shim_exec.c#L200)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.

I checked (using Python and `os.execve()`) and it doesn't work: the `do_handle_read` here does not start at offset 0. I think I was the one to break it, a few months ago: the ELF parsing code was rewinding the handle before.

I could try and fix it, but seeing how it's ugly, untested and most likely unused (nobody is complaining), removing seems to be the best option.
</blockquote></details>

Not pushed to github?


<!-- Sent from Reviewable.io -->

2021-06-08 13:54 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 90 at r4](https://reviewable.io/reviews/oscarlab/graphene/2421#-MbftmJI-2sUcln99vnk:-MbftmJJ0WIK8HLjWrDS:bnw4gxu) ([raw file](https://github.com/oscarlab/graphene/blob/285536ea03299dbe0aed6b6d384b7841ed341916/Documentation/manifest-syntax.rst#L90)):*
> ```reStructuredText
>    fs.mount.python.type = "chroot"
>    fs.mount.path = "/usr/bin/python3.8"
>    # Or "file:python3.8" if using a binary from your local directory
> ```

Maybe move this line after `fs.mount.uri`? Looks weird now.
___
*[LibOS/shim/src/sys/shim_exec.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mbbd_iO6UH2WbFD_l9A:-Mbft2S99UzxtRqoK1TR:b9dfe08) ([raw file](https://github.com/oscarlab/graphene/blob/081ef5c983fb2545ae88b81a06d051d14a98daf5/LibOS/shim/src/sys/shim_exec.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not pushed to github?
</blockquote></details>

Done. Reviewable didn't update previously, now I see the changes.
___
*[LibOS/shim/src/sys/shim_exec.c, line 186 at r4](https://reviewable.io/reviews/oscarlab/graphene/2421#-MbftBCmDAs97XR2XHLR:-MbftBCmDAs97XR2XHLS:b-z6sry6) ([raw file](https://github.com/oscarlab/graphene/blob/285536ea03299dbe0aed6b6d384b7841ed341916/LibOS/shim/src/sys/shim_exec.c#L186)):*
> ```C
>     /* TODO: consider handling shebangs, if necessary */
>     if ((ret = check_elf_object(exec)) < 0) {
>         log_warning("file not recognized as ELF\n");
> ```

Should be `log_error()`?


<!-- Sent from Reviewable.io -->

2021-06-08 14:04 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: 48 of 49 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 90 at r4](https://reviewable.io/reviews/oscarlab/graphene/2421#-MbftmJI-2sUcln99vnk:-MbfuXL81eN8msEKHjfc:ba7zx9g) ([raw file](https://github.com/oscarlab/graphene/blob/285536ea03299dbe0aed6b6d384b7841ed341916/Documentation/manifest-syntax.rst#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe move this line after `fs.mount.uri`? Looks weird now.
</blockquote></details>

Changed to a full commented-out line, should read better now.
___
*[LibOS/shim/src/sys/shim_exec.c, line 200 at r2](https://reviewable.io/reviews/oscarlab/graphene/2421#-Mbbd_iO6UH2WbFD_l9A:-MbfuGpF7vO6mZNaftaA:b-k6i3yj) ([raw file](https://github.com/oscarlab/graphene/blob/081ef5c983fb2545ae88b81a06d051d14a98daf5/LibOS/shim/src/sys/shim_exec.c#L200)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Reviewable didn't update previously, now I see the changes.
</blockquote></details>

Yeah, I posted too quickly, sorry.
___
*[LibOS/shim/src/sys/shim_exec.c, line 186 at r4](https://reviewable.io/reviews/oscarlab/graphene/2421#-MbftBCmDAs97XR2XHLR:-MbftwIh9OePr8poLqLV:bhht7fk) ([raw file](https://github.com/oscarlab/graphene/blob/285536ea03299dbe0aed6b6d384b7841ed341916/LibOS/shim/src/sys/shim_exec.c#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should be `log_error()`?
</blockquote></details>

I think warning is better. It's not fatal for the whole application, just a failed syscall.


<!-- Sent from Reviewable.io -->

2021-06-08 14:30 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-06-08 15:06 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-08 17:46 UTC, boryspoplawski reviewed
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-08 17:50 UTC, boryspoplawski reviewed
test

2021-06-08 17:50 UTC, boryspoplawski approved these changes
Didn't review, but GH is stupid and doesn't let me unblock.

2021-06-08 17:54 UTC, dimakuv approved these changes
Reviewable thinks that everything is fine. Probably after rebase, the "blocking" disposition on GitHub will disappear.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421#-:-Mbgk_ZmD4hD8Hy95xLh:b8u41an)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-08 18:07 UTC, mkow approved these changes
Borys meant that he didn't review this PR, so we shuoldn't count his approval ;) (but he has no other way to unblock from his side than pushing an "approve")

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421#-:-MbgnX_H0Qw9sgdWBWC7:b-5ex52x)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-09 05:37 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-09 10:14 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2421)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-09 10:32 UTC, merged