Corrected check for in-kernel driver.
oscarlab/graphene pull request #2427
Opened 2021-06-07 14:46 UTC by ScottR-Intel

## Description of the changes

The in-kernel driver by itself doesn't create the /dev/sgx folder any longer.  This is done by the PSW installers now.  So, if the PSW isn't yet installed when running the tool, it will fail the in-kernel driver check.  Modifying the tool to check for /dev/sgx_provision /dev/sgx_enclave which is what the in-kernel driver creates.

2021-06-07 16:03 UTC, woju requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ScottR-Intel)

___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/2427#-MbbBs6fDQGrEH9f-BfQ:-MbbBs6fDQGrEH9f-BfR:b-9tgvpq) ([raw file](https://github.com/oscarlab/graphene/blob/8e6416b9ee45f378456c9ffe6b8a808dafa0664a/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L169)):*
> ```cpp
> bool sgx_driver_loaded() {
>     // /dev/isgx is for LKM version, /dev/sgx_enclave and /dev/sgx_provision are for in-kernel support.
>     return file_exists("/dev/isgx") || (file_exists("/dev/sgx_enclave") && file_exists("/dev/sgx_provision"));
> ```

This will return false on DCAP < 1.10. Do we care about that?
___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/2427#-MbbCjLq3e5fHg4VI39V:-MbbCjLs3sq_8os_he_W:b-cxgw41) ([raw file](https://github.com/oscarlab/graphene/blob/8e6416b9ee45f378456c9ffe6b8a808dafa0664a/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L169)):*
> ```cpp
> bool sgx_driver_loaded() {
>     // /dev/isgx is for LKM version, /dev/sgx_enclave and /dev/sgx_provision are for in-kernel support.
>     return file_exists("/dev/isgx") || (file_exists("/dev/sgx_enclave") && file_exists("/dev/sgx_provision"));
> ```

We don't need to check for `sgx_provision`.


<!-- Sent from Reviewable.io -->

2021-06-07 16:42 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @woju)

___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/2427#-MbbBs6fDQGrEH9f-BfQ:-MbbLKiA8N4QKul7slUZ:b-reva68) ([raw file](https://github.com/oscarlab/graphene/blob/8e6416b9ee45f378456c9ffe6b8a808dafa0664a/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L169)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This will return false on DCAP < 1.10. Do we care about that?
</blockquote></details>

+1 to woju's request. Why not keep the older `/dev/sgx` as a third option here?
___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/2427#-MbbCjLq3e5fHg4VI39V:-MbbLR75DdoJqkiLmLGx:b-8xe41d) ([raw file](https://github.com/oscarlab/graphene/blob/8e6416b9ee45f378456c9ffe6b8a808dafa0664a/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L169)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

We don't need to check for `sgx_provision`.
</blockquote></details>

It doesn't hurt to check for it, it's a part of the SGX driver installation. I would keep it.


<!-- Sent from Reviewable.io -->

2021-06-07 21:59 UTC, mkow reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2021-06-08 12:15 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/2427#-MbbCjLq3e5fHg4VI39V:-MbfXiN9Dv5E2bqfqeyT:b-x8f5e3) ([raw file](https://github.com/oscarlab/graphene/blob/8e6416b9ee45f378456c9ffe6b8a808dafa0664a/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It doesn't hurt to check for it, it's a part of the SGX driver installation. I would keep it.
</blockquote></details>

IDK, we don't use it, right? But no strong opinion, unblocking.


<!-- Sent from Reviewable.io -->

2021-06-08 12:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2427)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @woju)

___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 169 at r1](https://reviewable.io/reviews/oscarlab/graphene/2427#-MbbCjLq3e5fHg4VI39V:-MbfcqnH-8bPYVa9yYoS:bk80aml) ([raw file](https://github.com/oscarlab/graphene/blob/8e6416b9ee45f378456c9ffe6b8a808dafa0664a/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L169)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IDK, we don't use it, right? But no strong opinion, unblocking.
</blockquote></details>

Graphene doesn't use it. But the tool in question (`is_sgx_available`) is unrelated to Graphene -- it just so happened that it is built and shipped with Graphene (because one of the ITL people wrote this handy tool, and we just have it now).


<!-- Sent from Reviewable.io -->

2021-06-13 23:22 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2427)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ScottR-Intel and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2427#-Mc6e_3vA0vyojyFW1-h:-Mc6e_3vA0vyojyFW1-i:b-greqz3) (no related file):*
Whoops, I forgot about this PR and made my own fix for this issue (#2438). Sorry @scottr-intel, I didn't intend to take over this PR :)
Anyways, I prefer my version, because it doesn't remove the checks for `/dev/sgx`, which AFAIK still has users. But if you want to introduce a similar change here, then we can keep your PR and I'll close mine. If you want to do so, please also reformat the comment like I did in #2438.

---


<!-- Sent from Reviewable.io -->

2021-06-14 10:57 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2427)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @ScottR-Intel and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2427#-Mc6e_3vA0vyojyFW1-h:-Mc99pxV658Ve_Rhn4Bl:b-xa4y1v) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Whoops, I forgot about this PR and made my own fix for this issue (#2438). Sorry @scottr-intel, I didn't intend to take over this PR :)
Anyways, I prefer my version, because it doesn't remove the checks for `/dev/sgx`, which AFAIK still has users. But if you want to introduce a similar change here, then we can keep your PR and I'll close mine. If you want to do so, please also reformat the comment like I did in #2438.
</blockquote></details>

I suggest to go with Michal's #2438.

---


<!-- Sent from Reviewable.io -->

2021-06-18 09:55 UTC, closed without merging