[LibOS] Remove IPC msg_with_ack and introduce message responses
oscarlab/graphene pull request #2433
Opened 2021-06-09 15:16 UTC by boryspoplawski

## Description of the changes 
Function `ipc_send_msg_and_get_response` is introduced, which sends the probided IPC message and waits for a response to it. The response could be anything and is returned by this function - it is the caller responsibility to interpret it.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene/2433)

2021-06-09 15:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: 0 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2433#-MblLPv4-uuK2wxLMMzm:-MblLPv4-uuK2wxLMMzn:b12dbiy) (no related file):*
TODO: add some debug logging in appropriate places.

---


<!-- Sent from Reviewable.io -->

2021-06-09 16:07 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-06-09 16:54 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-06-09 17:32 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbloPd_1pk2tBdfzx9Y:-MbloPd_1pk2tBdfzx9Z:bxi5yfe) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc_worker.c#L190)):*
> ```C
>         }
> 
>         /* TODO: fix this interface - ownership passing. */
> ```

Currently `msg_data` is passed to the callbacks, but only `IPS_MSG_RESP` takes the ownership, which is a bit ugly to deal with.
I see 3 options:
1) Leave it as it is (and have this if here).
2) Always pass ownership to callbacks - we would need to free it on all return paths in all callbacks - I very much dislike this approach.
3) Pass ownership only if the callback was successful i.e. returned `0`. We would still need to free `msg_data` in callbacks, but only on success paths - still cumbersome.


<!-- Sent from Reviewable.io -->

2021-06-09 23:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: 0 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbn2P1794wpcnX48MDZ:-Mbn2P184NTvoEu3aoq4:b-yh8j21) (no related file):*
@pwmarcz you might want to take a look at these changes, since you're probably going to use them soon ;)

---


<!-- Sent from Reviewable.io -->

2021-06-09 23:18 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

___
*[LibOS/shim/include/shim_ipc.h, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbmnW8L0gG9f7f3NwUX:-MbmnW8M0l_XUbuN0c_M:bu56mrg) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/include/shim_ipc.h#L81)):*
> ```objc
> int request_leader_connect_back(void);
> /*!
>  * \brief Callback for a IPC connection request
> ```

`a` -> `an`
___
*[LibOS/shim/include/shim_ipc.h, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbmoytC0jughDvTsr6I:-MbmoytC0jughDvTsr6J:b-tjmqt6) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/include/shim_ipc.h#L92)):*
> ```objc
>     unsigned long seq;
>     unsigned char code;
> } __attribute__((packed));
> ```

I'd add a comment that this is legal only assuming that the fields are sorted by decreasing alignment.
___
*[LibOS/shim/include/shim_ipc.h, line 250 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbmtboECDruLf1PGE7G:-MbmtboECDruLf1PGE7H:b-f7lo4y) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/include/shim_ipc.h#L250)):*
> ```
> int npids
> ```

Should be `size_t`.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 279 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbmx1kL8oaMPwgFurWK:-Mbmx1kL8oaMPwgFurWL:behf40d) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc.c#L279)):*
> ```
> unsigned long seq
> ```

I'm looking at this each time I see an IPC-related PR and I'm wondering whether this is a good type. Shouldn't we use `uint64_t` for it? On 32-bit it may potentially be overflowable under weird circumstances...
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbloPd_1pk2tBdfzx9Y:-Mbn2vWc9z39jf5Oc_qP:bg7xz2w) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc_worker.c#L190)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Currently `msg_data` is passed to the callbacks, but only `IPS_MSG_RESP` takes the ownership, which is a bit ugly to deal with.
I see 3 options:
1) Leave it as it is (and have this if here).
2) Always pass ownership to callbacks - we would need to free it on all return paths in all callbacks - I very much dislike this approach.
3) Pass ownership only if the callback was successful i.e. returned `0`. We would still need to free `msg_data` in callbacks, but only on success paths - still cumbersome.
</blockquote></details>

3. seems to be the least evil to me.


<!-- Sent from Reviewable.io -->

2021-06-10 00:04 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: 4 of 8 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbmnW8L0gG9f7f3NwUX:-Mbn5HmS4r9HOJatn6nG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/include/shim_ipc.h#L81)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`a` -> `an`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbmoytC0jughDvTsr6I:-Mbn5ObA9l2TwgAMF_bP:b3u9ecy) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/include/shim_ipc.h#L92)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add a comment that this is legal only assuming that the fields are sorted by decreasing alignment.
</blockquote></details>

Even then it's not legal. I have a TODO to change usages of this fields into memcpy, but seems I didn't add it to the code/reviewable.

Update: after recent changes this was trivial to fix, so stashed changes into this PR.
___
*[LibOS/shim/include/shim_ipc.h, line 250 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbmtboECDruLf1PGE7G:-Mbn5aKC-9qCcfsDxGYN:b-vrz457) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/include/shim_ipc.h#L250)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> int npids
> ```

Should be `size_t`.
</blockquote></details>

Yes it should. But it's an old interface, I didn't change it in this PR. It's waiting for its turn :)
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 279 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbmx1kL8oaMPwgFurWK:-Mbn5xSA1m_VvXzg9WTp:b-9zu9s2) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc.c#L279)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> unsigned long seq
> ```

I'm looking at this each time I see an IPC-related PR and I'm wondering whether this is a good type. Shouldn't we use `uint64_t` for it? On 32-bit it may potentially be overflowable under weird circumstances...
</blockquote></details>

Actually after this PR the overflow should not matter, as long as there are no 2 messages with the same `seq` at the same time, but that would mean 2**32 concurrent messages going out of 1 thread, which seems unlikely.
Changed it to start from `0` and removed the check below.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbloPd_1pk2tBdfzx9Y:-Mbn9ALOE12LnvDaZ5EQ:b-2rwu0b) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc_worker.c#L190)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

3. seems to be the least evil to me.
</blockquote></details>

TBH: I'm leaning towards 1, beacuase `IPC_MSG_RESP` is pretty special. Any new callback that is created should not be interested in keeping this `msg_data` for itself (i.e. requiring ownership passing). So it's not like the list will grow and we would need to add more ifs here. Also such new callback wouldn't need to worry about whether and when to free `msg_data`.

My original impression was that the current version is super ugly and needs to be somehow fixed, but after thinking a bit about it, I don't se a better way (i.e. I think all other proposed, including 3, are even worse).


<!-- Sent from Reviewable.io -->

2021-06-10 01:04 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[common/include/api.h, line 110 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbnOTH25M-8BPQjTrC6:-MbnOTH25M-8BPQjTrC7:b-r1xmmm) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/common/include/api.h#L110)):*
> ```objc
> 
> #define SET_UNALIGNED(a, b) ({                  \
>     __typeof__(b) _b = (b);                     \
> ```

Why having anti-double-eval on `b`, but not on `a`? Both occur more than once in this macro.
___
*[LibOS/shim/include/shim_ipc.h, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbmoytC0jughDvTsr6I:-MbnOgO5-XxE7TA7yhsr:b-wdj8zi) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/include/shim_ipc.h#L92)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Even then it's not legal. I have a TODO to change usages of this fields into memcpy, but seems I didn't add it to the code/reviewable.

Update: after recent changes this was trivial to fix, so stashed changes into this PR.
</blockquote></details>

Nice, thanks!
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 279 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbmx1kL8oaMPwgFurWK:-MbnP7a1DtUH6LZdrhz9:b16w16) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc.c#L279)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Actually after this PR the overflow should not matter, as long as there are no 2 messages with the same `seq` at the same time, but that would mean 2**32 concurrent messages going out of 1 thread, which seems unlikely.
Changed it to start from `0` and removed the check below.
</blockquote></details>

Yeah, I was thinking the same previously, but can't there be a case where you stall the first message somehow (e.g. by freezing its recipient process) and then if the rest 2**32-1 would be addressed to other processes they would then get answered quickly? This way the messages wouldn't need to be concurrent.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbloPd_1pk2tBdfzx9Y:-MbnQLL34FBXPSPFF3RQ:b-rqqs1y) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc_worker.c#L190)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TBH: I'm leaning towards 1, beacuase `IPC_MSG_RESP` is pretty special. Any new callback that is created should not be interested in keeping this `msg_data` for itself (i.e. requiring ownership passing). So it's not like the list will grow and we would need to add more ifs here. Also such new callback wouldn't need to worry about whether and when to free `msg_data`.

My original impression was that the current version is super ugly and needs to be somehow fixed, but after thinking a bit about it, I don't se a better way (i.e. I think all other proposed, including 3, are even worse).
</blockquote></details>

I'm fine with this, I'm relying on you in this area of Graphene code :)

Also, I thought a bit about alternative solutions, maybe something around returning by arguments could make this ownership passing more explicit? E.g. something like: you get this data buffer through `type**` arg, and if you want to take ownership then you NULL-ify it. But I'm not sure if it's better, sounds like a pretty uncommon convention (but proper ownership control in most C codebases is also an uncommon thing :) ).


<!-- Sent from Reviewable.io -->

2021-06-10 01:39 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/include/api.h, line 110 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbnOTH25M-8BPQjTrC6:-MbnUW1lD7BCIdlyGoFv:bbm93uj) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/common/include/api.h#L110)):*
This has nothing to do with double-eval, it's to support rvalues in `b` (e.g. immediates or function call results).
Note we take an address of `_b`.

> Both occur more than once in this macro.

But other usage places do not evaluate them, there is only one evaluation for each (unless they are VLAs, but then static_assert should fail).
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 279 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbmx1kL8oaMPwgFurWK:-MbnXEcOCo19U00M-ckM:b-qvuy6) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc.c#L279)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I was thinking the same previously, but can't there be a case where you stall the first message somehow (e.g. by freezing its recipient process) and then if the rest 2**32-1 would be addressed to other processes they would then get answered quickly? This way the messages wouldn't need to be concurrent.
</blockquote></details>

That's true, and with careful ordering of the overlap and wakeup we could get a type confusion (on response data).
I'll restore the previous version (with 0 acting as a invalid value) and change it to 64bits.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbloPd_1pk2tBdfzx9Y:-MbnW-hV2CJe5E802vs-:b-90fpya) ([raw file](https://github.com/oscarlab/graphene/blob/93bf7fb6ad920cbe2398e10e5ff8b5a162c4865a/LibOS/shim/src/ipc/shim_ipc_worker.c#L190)):*
Ah, yes, that was the original idea (to have `void**` and NULL-ify it if we took the ownership of the pointer), the problem is that the interface would change (not a problem per se) an just as with 3 - we really only want to do that in response handling (`IPC_MSG_RESP`), which means other places would have to use `*data`. Maybe this is better than special casing like now?

> sounds like a pretty uncommon convention

Not sure if it's or it's not, but I've definitely used it in Graphene before :)

Let me try that tomorrow, I'll see if it looks better.


<!-- Sent from Reviewable.io -->

2021-06-10 08:49 UTC, dimakuv requested changes
> Reviewed 4 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mboqkv8E71L04snGHbt:-Mboqkv8E71L04snGHbu:b-z6yyiq) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/include/shim_ipc.h#L118)):*
> ```objc
>  * \param dest vmid of the destination process
>  * \param msg message to send
>  * \param[out] resp upon successful return contains poitner to the response
> ```

`pointer`
___
*[LibOS/shim/include/shim_ipc.h, line 126 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mboqtsy4cqwPLnoFm8d:-Mboqtsy4cqwPLnoFm8e:brmk5h7) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/include/shim_ipc.h#L126)):*
> ```objc
>  * discarded, but still awaited for.
>  */
> int ipc_send_msg_and_get_response(IDTYPE dst, struct shim_ipc_msg* msg, void** resp);
> ```

`dst` -- typo? You have `dest` in all other places (including comments for this func).
___
*[LibOS/shim/include/shim_ipc.h, line 135 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MboqYfZ-knUXUgL1UJx:-MboqYfZ-knUXUgL1UJy:bh4br3j) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/include/shim_ipc.h#L135)):*
> ```objc
>  * Send an IPC message \p msg to all known (connected) processes except for \p exclude_vmid.
>  */
> int broadcast_ipc(struct shim_ipc_msg* msg, IDTYPE exclude_vmid);
> ```

Since we're changing all function names to have a prefix `ipc_`, maybe also change this to `ipc_broadcast`?
___
*[LibOS/shim/include/shim_ipc.h, line 145 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MborsaJ17pW8wjSv5_6:-MborsaJ17pW8wjSv5_7:b6eyjzf) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/include/shim_ipc.h#L145)):*
> ```objc
>  *
>  * Searches for a thread waiting for a response to a message previously sent to \p src with
>  * the sequence number \p seq. If such thread is found, it is woken up and \p data is passed to it.
> ```

What does it mean `data is passed to it`? Previously you called a callback, with data as one argument. Could you make it clearer in this comment, how does the woken thread "detects" this data?

I haven't seen to implementation, but I'm assuming that the thread-to-awake must sleep in the `ipc_send_msg_and_get_response()` function, and the `data` is found in the `resp` object there.
___
*[LibOS/shim/include/shim_ipc.h, line 189 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbotJw-CDJ3_Fz_yfV6:-MbotJw-CDJ3_Fz_yfV7:b8fo8vx) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/include/shim_ipc.h#L189)):*
> ```objc
>     IDTYPE base;
>     IDTYPE size;
> } __attribute__((packed));
> ```

Where does this OFFER message belong to? Is it for `ipc_lease_send`? Could you move it above that function then? (And also add a quick comment.)
___
*[LibOS/shim/include/shim_ipc.h, line 250 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbou3ab-ylaRwnSPSyl:-Mbou3ab-ylaRwnSPSym:brb1xj9) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/include/shim_ipc.h#L250)):*
> ```objc
> } __attribute__((packed));
> 
> int ipc_pid_getstatus(IDTYPE dest, int npids, IDTYPE* pids, struct shim_ipc_pid_retstatus** status);
> ```

Please change to `size_t npids` since you've done it above.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MboupVp-HTDHQDORJ9b:-MboupVq7b-rGYLWwcUj:b-60gj3c) ([raw file](https://github.com/oscarlab/graphene/blob/f0604438cda00379b3ea4c67a1a1c2a55a6f0416/LibOS/shim/src/ipc/shim_ipc.c#L2)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2014 Stony Brook University
> ```

Is this correct from a legal perspective?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 190 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbovPtbBCbFn9dQrGAy:-MbovPtbBCbFn9dQrGAz:b-4u5wdk) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/src/ipc/shim_ipc.c#L190)):*
> ```C
>     SET_UNALIGNED(msg->header.size, get_ipc_msg_size(size));
>     SET_UNALIGNED(msg->header.seq, 0ul);
>     SET_UNALIGNED(msg->header.code, code);
> ```

What is the point of `SET_UNALIGNED`?
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 232 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbow9VC9mTO8GJlH7i-:-Mbow9VC9mTO8GJlH7i0:b6dz94k) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/src/ipc/shim_ipc.c#L232)):*
> ```C
>     int ret = 0;
>     do {
>         ret = pal_to_unix_errno(DkEventWait(waiter->event, NULL));
> ```

Please add `/*timeout=*/`
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 248 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbowirSCAAecFnn92iI:-MbowirSCAAecFnn92iJ:bsa1p3f) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/src/ipc/shim_ipc.c#L248)):*
> ```C
>         .response_data = NULL,
>     };
>     int ret = DkEventCreate(&waiter.event, /*init_signaled=*/false, /*auto_clear=*/false);
> ```

What was wrong with using `thread_wait()`? Is it to support "send ipc message during sighandler" cases (where the normal-execution flow was probably already thread-waiting)?

Using a dedicated event is of course better, but won't it introduce performance overheads? For each message send, we now need to create an event, which is not fast at all in SGX case: https://github.com/oscarlab/graphene/blob/c781b2ab9081bc5725270a0344206aca28fbdc3e/Pal/src/host/Linux-SGX/db_events.c#L26
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 268 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mboxov92m_NRsyww8Dn:-MboxovA23YGkWOfs6Yk:b54dsvn) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/src/ipc/shim_ipc.c#L268)):*
> ```C
> 
>     if (resp) {
>         *resp = waiter.response_data;
> ```

Maybe add an assert that `response_data` contains something? I would also add a comment about the passing of ownership here.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbozVb1BV7NDoG0eo2k:-MbozVb28EqD4Udepaf7:b-vverrb) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/src/ipc/shim_ipc_pid.c#L152)):*
> ```C
> }
> 
> int ipc_pid_getstatus(IDTYPE dest, int npids, IDTYPE* pids,
> ```

`size_t npids`
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 237 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbozxG83l5zBySxBTjz:-MbozxG83l5zBySxBTk-:b-mwpcc) ([raw file](https://github.com/oscarlab/graphene/blob/f0604438cda00379b3ea4c67a1a1c2a55a6f0416/LibOS/shim/src/ipc/shim_ipc_pid.c#L237)):*
> ```C
>                   status[0].pid);
>     else
>         log_debug("ipc send to %u: IPC_MSG_PID_RETSTATUS(0, [])\n", dest);
> ```

Don't you want to keep this log message? Looks useful to know that the response was sent.
___
*[LibOS/shim/src/ipc/shim_ipc_pid.c, line 415 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbp-3SDEZpxjX8lj8fu:-Mbp-3SDEZpxjX8lj8fv:b-mwpcc) ([raw file](https://github.com/oscarlab/graphene/blob/f0604438cda00379b3ea4c67a1a1c2a55a6f0416/LibOS/shim/src/ipc/shim_ipc_pid.c#L415)):*
> ```C
> 
>     log_debug("ipc send to %u: IPC_MSG_PID_RETMETA(%d, %s, %d)\n", dest, p [...]

2021-06-10 09:47 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[common/include/api.h, line 110 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbnOTH25M-8BPQjTrC6:-MbpI9vNCziAkSfDbR9e:b-7vo826) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/common/include/api.h#L110)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This has nothing to do with double-eval, it's to support rvalues in `b` (e.g. immediates or function call results).
Note we take an address of `_b`.

> Both occur more than once in this macro.

But other usage places do not evaluate them, there is only one evaluation for each (unless they are VLAs, but then static_assert should fail).
</blockquote></details>

Ah, I see.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 2 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MboupVp-HTDHQDORJ9b:-MbpIa3E7UQSVjv-r1rq:bdcm9qt) ([raw file](https://github.com/oscarlab/graphene/blob/f0604438cda00379b3ea4c67a1a1c2a55a6f0416/LibOS/shim/src/ipc/shim_ipc.c#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this correct from a legal perspective?
</blockquote></details>

AFAIK at this point Borys have rewritten all the lines in this file.
___
*[LibOS/shim/src/ipc/shim_ipc.c, line 190 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbovPtbBCbFn9dQrGAy:-MbpIoGqBuEGsG_luo2A:b-rciir1) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/src/ipc/shim_ipc.c#L190)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the point of `SET_UNALIGNED`?
</blockquote></details>

`msg->header` is packed, so accessing its fields other than by using `memcpy()` is illegal.


<!-- Sent from Reviewable.io -->

2021-06-10 23:50 UTC, mkow requested changes
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 290 at r3](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbsIO3RDdI7pjUpPrHh:-MbsIO3RDdI7pjUpPrHi:bbz2ye2) ([raw file](https://github.com/oscarlab/graphene/blob/80973a0169658d6cb2be3120c7e36fcc625d2606/LibOS/shim/src/ipc/shim_ipc.c#L290)):*
> ```C
>     if (!seq) {
>         log_error("Got an IPC response without a sequence number\n");
>         return -EINVAL;
> ```

I think `data` leaks here? Not sure if this error is fatal though, if it is then it may not be a problem.


<!-- Sent from Reviewable.io -->

2021-06-11 01:43 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: 7 of 8 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 290 at r3](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbsIO3RDdI7pjUpPrHh:-MbsanRcE6Z_B_O_3AkK:b-h5d02v) ([raw file](https://github.com/oscarlab/graphene/blob/80973a0169658d6cb2be3120c7e36fcc625d2606/LibOS/shim/src/ipc/shim_ipc.c#L290)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think `data` leaks here? Not sure if this error is fatal though, if it is then it may not be a problem.
</blockquote></details>

Oops, right, stashed too many unrelated changes in one fixup and missed this.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 186 at r3](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbscrkED6IckKh64HNB:-MbscrkFAWR337RDFeYw:blrzfnm) ([raw file](https://github.com/oscarlab/graphene/blob/80973a0169658d6cb2be3120c7e36fcc625d2606/LibOS/shim/src/ipc/shim_ipc_worker.c#L186)):*
> ```C
>         if (msg_code < ARRAY_SIZE(ipc_callbacks) && ipc_callbacks[msg_code]) {
>             ret = ipc_callbacks[msg_code](conn->vmid, msg_data, msg_seq);
>             if (ret < 0) {
> ```

TBH I have no idea what to do here...
Should this be a fatal error?


<!-- Sent from Reviewable.io -->

2021-06-11 09:56 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 186 at r3](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbscrkED6IckKh64HNB:-MbuUsfF1hNoLuSpt_1F:b-7sju7h) ([raw file](https://github.com/oscarlab/graphene/blob/80973a0169658d6cb2be3120c7e36fcc625d2606/LibOS/shim/src/ipc/shim_ipc_worker.c#L186)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TBH I have no idea what to do here...
Should this be a fatal error?
</blockquote></details>

I'd say so, but maybe I'm missing a case where it can legitimately fail.


<!-- Sent from Reviewable.io -->

2021-06-14 09:35 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 186 at r3](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbscrkED6IckKh64HNB:-Mc8rme078fiRMyONol1:btmddzw) ([raw file](https://github.com/oscarlab/graphene/blob/80973a0169658d6cb2be3120c7e36fcc625d2606/LibOS/shim/src/ipc/shim_ipc_worker.c#L186)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd say so, but maybe I'm missing a case where it can legitimately fail.
</blockquote></details>

Turns out it can, but I think it should not be the case, I'll move some thing around and make this fatal.


<!-- Sent from Reviewable.io -->

2021-06-14 10:37 UTC, dimakuv approved these changes
> Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 250 at r2](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mbou3ab-ylaRwnSPSyl:-Mc93ZTJ6H4Jz5HZRZRw:b32w0x) ([raw file](https://github.com/oscarlab/graphene/blob/1286e0415eb1f06e0854011826f296ef75910c87/LibOS/shim/include/shim_ipc.h#L250)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (in this PR I've only changes what was necessary)
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-06-14 12:47 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: 3 of 10 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 186 at r3](https://reviewable.io/reviews/oscarlab/graphene/2433#-MbscrkED6IckKh64HNB:-Mc9Yg4w1sbutANnSzo1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/80973a0169658d6cb2be3120c7e36fcc625d2606/LibOS/shim/src/ipc/shim_ipc_worker.c#L186)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Turns out it can, but I think it should not be the case, I'll move some thing around and make this fatal.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/sighandler_reset.c, line 42 at r5](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mc9Yklc5NYa3xNB6jL7:-Mc9Yklc5NYa3xNB6jL8:b-udvjhp) ([raw file](https://github.com/oscarlab/graphene/blob/f0604438cda00379b3ea4c67a1a1c2a55a6f0416/LibOS/shim/test/regression/sighandler_reset.c#L42)):*
> ```C
>     }
> 
>     wait(NULL);
> ```

FYI: this returned `-EINTR`, so I fixed everything.


<!-- Sent from Reviewable.io -->

2021-06-14 13:09 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-14 13:14 UTC, mkow requested changes
> Reviewed 7 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 187 at r5](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mc9_ONoDOKpZNzOQACF:-Mc9_ONoDOKpZNzOQACG:bdqy03k) ([raw file](https://github.com/oscarlab/graphene/blob/f68853da4c9aec4b2f857603ef5e4565032865a4/LibOS/shim/src/ipc/shim_ipc.c#L187)):*
> ```C
>     }
>     unlock(&g_ipc_connections_lock);
> ```

What if a new connection to `dest` gets created here? Is this possible? If not, please add a comment explaining why.


<!-- Sent from Reviewable.io -->

2021-06-14 13:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 187 at r5](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mc9_ONoDOKpZNzOQACF:-Mc9fXuF45RUZ5mvgObm:b-yskwcr) ([raw file](https://github.com/oscarlab/graphene/blob/f68853da4c9aec4b2f857603ef5e4565032865a4/LibOS/shim/src/ipc/shim_ipc.c#L187)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What if a new connection to `dest` gets created here? Is this possible? If not, please add a comment explaining why.
</blockquote></details>

Well, nothing? It is possible.


<!-- Sent from Reviewable.io -->

2021-06-14 13:27 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 187 at r5](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mc9_ONoDOKpZNzOQACF:-Mc9gmtt2T53deIgtyuo:bem48n1) ([raw file](https://github.com/oscarlab/graphene/blob/f68853da4c9aec4b2f857603ef5e4565032865a4/LibOS/shim/src/ipc/shim_ipc.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Well, nothing? It is possible.
</blockquote></details>

And the code below will delete the response from it, sounds wrong?


<!-- Sent from Reviewable.io -->

2021-06-14 13:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 187 at r5](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mc9_ONoDOKpZNzOQACF:-Mc9hR6T80TLF06dNXXt:b-4eyti5) ([raw file](https://github.com/oscarlab/graphene/blob/f68853da4c9aec4b2f857603ef5e4565032865a4/LibOS/shim/src/ipc/shim_ipc.c#L187)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

And the code below will delete the response from it, sounds wrong?
</blockquote></details>

If there is a response waiter, that means we had a connection that was removed above - in such case there was an error, so removing it is fine.


<!-- Sent from Reviewable.io -->

2021-06-14 14:00 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/ipc/shim_ipc.c, line 187 at r5](https://reviewable.io/reviews/oscarlab/graphene/2433#-Mc9_ONoDOKpZNzOQACF:-Mc9mYLL2QLGREgmS1ww:bz29wzx) ([raw file](https://github.com/oscarlab/graphene/blob/f68853da4c9aec4b2f857603ef5e4565032865a4/LibOS/shim/src/ipc/shim_ipc.c#L187)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If there is a response waiter, that means we had a connection that was removed above - in such case there was an error, so removing it is fine.
</blockquote></details>

Discussed on priv, seems legit, resolving.


<!-- Sent from Reviewable.io -->

2021-06-14 14:39 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-06-14 14:41 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2433)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-14 14:57 UTC, merged