[Pal/Linux-SGX] tools: Support upstreamed driver in is_sgx_available
oscarlab/graphene pull request #2438
Opened 2021-06-12 17:47 UTC by mkow

## Description of the changes 

Seems we forgot to update this tool after SGX got into the kernel. Kudos to @vans163 for noticing this!

## How to test this PR? 

Run `is_sgx_available` on a system which uses the upstreamed SGX driver and check if "SGX driver loaded" says "true".

2021-06-14 10:57 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2438)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-14 11:01 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2438)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2438#-Mc9Adwh-71Yj2TViF_Y:-Mc9Adwi9U20aJStJ00E:btf6hti) (no related file):*
Please add that this PR closes #2427 

---


<!-- Sent from Reviewable.io -->

2021-06-14 12:30 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2438)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2438#-Mc9Adwh-71Yj2TViF_Y:-Mc9V2AgEcpzIHtRoLsQ:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add that this PR closes #2427 
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-06-14 12:38 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2438)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-18 09:53 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2438)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-18 09:55 UTC, merged