[Pal/Linux-SGX] Add handling for all reserved and unrecognized CPUID leaves
oscarlab/graphene pull request #2440
Opened 2021-06-14 12:15 UTC by dimakuv

## Description of the changes 

Previously, Linux-SGX PAL failed on all CPUID leaves not mentioned in our internal CPUID table. This is not how the actual Intel CPUID instruction behaves: some CPUID leaves are explicitly reserved and always return zeros, and the rest CPUID leaves return the info as if they are the "highest basic information leaf".

This PR adds such handling to make our CPUID logic exactly the same as in the latest Intel SDM documentation.

## How to test this PR? 

Added more testing to the `cpuid` LibOS regression test.

2021-06-15 18:24 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/test/regression/cpuid.c, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFWLGP0g1ryUmh5uJP:-McFWLGP0g1ryUmh5uJQ:b-cqjzay) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L75)):*
> ```
> 0x00
> ```

I'd either write `0` or `0x0`, the current version looks like it's suggesting that this is a one-byte argument.
___
*[LibOS/shim/test/regression/cpuid.c, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McEhUX85tqzranThwjL:-McEhUX85tqzranThwjM:b-2xiyp0) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L78)):*
> ```C
>     if (r.eax || r.ebx || r.ecx || r.edx)
>         abort();
>     memset(&r, 0, sizeof(r));
> ```

Could you set this to something non-zero, so we could detect a bug if some of the registers are not cleared by Graphene? Same in other similar places in this file.
___
*[LibOS/shim/test/regression/cpuid.c, line 86 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFt7uH0ZgwWYP_7MCO:-McFt7uI5Gez6jSiGo9N:b-klzgkf) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L86)):*
> ```C
> 
> static void test_cpuid_leaf_not_recognized(void) {
>     /* in case of unrecognized leaves, Graphene returns info for highest basic information leaf */
> ```

Uhm, really? Is this what x86 does?
___
*[LibOS/shim/test/regression/cpuid.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtagcCGrkt_6YSsSW:-McFtagcCGrkt_6YSsSX:b-qqgtes) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L92)):*
> ```C
>     /* we don't care about return values, just check that they are not all-zeros */
>     if (!r.eax && !r.ebx && !r.ecx && !r.edx)
>         abort();
> ```

My Intel CPU says: "Program received signal SIGABRT, Aborted." :)
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 323 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtrBl4WL55HpiZmrY:-McFtrBl4WL55HpiZmrZ:bv6ab6z) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L323)):*
> ```C
>     {.leaf = 0x0F, .zero_subleaf = false, .cache = true},  /* Intel RDT Monitoring */
>     {.leaf = 0x10, .zero_subleaf = false, .cache = true},  /* RDT/L2/L3 Cache Allocation Tech */
>     /* NOTE: 0x11 leaf is not recognized, see code below */
> ```

What's the difference between unrecognized and reserved? I can't find any info about these leaves in SDM, but maybe I'm looking at a wrong place.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 369 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFWoY5-3dTgAX02aKc:-McFWoY65kypjvasG--F:b-8b8jqz) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L369)):*
> ```C
>     }
> 
>     /* a few basic leaves are considered reserved and always return zeros */
> ```

[citation needed]
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 388 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFuYeD2Y-CZDU7eZ5C:-McFuYeD2Y-CZDU7eZ5D:b-8b8jqz) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L388)):*
> ```C
>     if (!known_leaf) {
>         /* leaf is not recognized (EAX value is outside of recongized range for CPUID), return info
>          * for highest basic information leaf (see cpuid_known_leaves table; currently 0x1F) */
> ```

[citation needed]
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 390 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFu_kVEyTZPQPn-hvX:-McFu_kVEyTZPQPn-hvY:b-kfafa9) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L390)):*
> ```C
>          * for highest basic information leaf (see cpuid_known_leaves table; currently 0x1F) */
>         leaf = 0x1F;
>         for (unsigned int i = 0; i < ARRAY_SIZE(cpuid_known_leaves); i++) {
> ```

should be `size_t`


<!-- Sent from Reviewable.io -->

2021-06-16 11:43 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: 0 of 2 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[LibOS/shim/test/regression/cpuid.c, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFWLGP0g1ryUmh5uJP:-McJXwq93H8joP2L1um2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L75)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> 0x00
> ```

I'd either write `0` or `0x0`, the current version looks like it's suggesting that this is a one-byte argument.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/cpuid.c, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McEhUX85tqzranThwjL:-McJZh9T6uCW4xu6zcMM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you set this to something non-zero, so we could detect a bug if some of the registers are not cleared by Graphene? Same in other similar places in this file.
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/cpuid.c, line 86 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFt7uH0ZgwWYP_7MCO:-McJb7tEA2osL5oQLLPk:b-b7zm58) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Uhm, really? Is this what x86 does?
</blockquote></details>

Yes. See Intel SDM or here: https://www.felixcloutier.com/x86/cpuid (the very end of the pseudo-code, the `DEFAULT` case).
___
*[LibOS/shim/test/regression/cpuid.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtagcCGrkt_6YSsSW:-McJbHE-Bj4GQ1tlyOZE:b-ulcao0) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L92)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

My Intel CPU says: "Program received signal SIGABRT, Aborted." :)
</blockquote></details>

Done. I changed this check, but I'm actually curious what "highest basic" CPUID leaf returns all-zeros. Well, I guess this is possible, e.g. some kind of `keylocker` CPUID leaf is the last one on your CPU and it is set to all zeros.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 323 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtrBl4WL55HpiZmrY:-McJaf7K8R2tG8RD1-zB:bj769jg) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L323)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the difference between unrecognized and reserved? I can't find any info about these leaves in SDM, but maybe I'm looking at a wrong place.
</blockquote></details>

You should be looking at the "Operation" section (pseudo-code) of the CPUID instruction. In my Intel SDM, this is Vol. 2A, Chapter 3.2, pages 3-234. Or check pseudo-code here: https://www.felixcloutier.com/x86/cpuid (e.g., search for `EAX = 8H:`).

`Reserved` always return all-zeros. `Unrecognized` return the same as the "highest basic supported CPUID leaf".
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 369 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFWoY5-3dTgAX02aKc:-McJb5So5XBpYuyR-uFd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L369)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

[citation needed]
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 388 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFuYeD2Y-CZDU7eZ5C:-McJb625EdiEafWYl5cs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L388)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

[citation needed]
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 390 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFu_kVEyTZPQPn-hvX:-McJ_Ag20xa48tfBIMNf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L390)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be `size_t`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-01 15:33 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/cpuid.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtagcCGrkt_6YSsSW:-MdXZC1S0_HYhSKIEo95:b-l3bhbh) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L92)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I changed this check, but I'm actually curious what "highest basic" CPUID leaf returns all-zeros. Well, I guess this is possible, e.g. some kind of `keylocker` CPUID leaf is the last one on your CPU and it is set to all zeros.
</blockquote></details>

On my CPU `0x13` returns all-zeros but `0x1b` returns highest supported info.
___
*[LibOS/shim/test/regression/cpuid.c, line 116 at r2](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdX_Y-69e1HfQ14XALh:-MdX_Y-7441zQQv3UFO3:b-quhvrl) ([raw file](https://github.com/oscarlab/graphene/blob/a5d801895ad44b119ecafd3b7219d2da2d402265/LibOS/shim/test/regression/cpuid.c#L116)):*
> ```C
> 
> static void test_cpuid_leaf_invalid(void) {
>     /* Graphene returns all zeros for CPUID leaves 0x40000000 - 0x4FFFFFFF ("no virtualization") */
> ```

We should return highest supported leaf info here - technically that could be all zeroes, but most likely it's not. It's also most likely not important, so not blocking.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 323 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtrBl4WL55HpiZmrY:-MdXewra1Uc4lKQzCM-4:b-wzju0w) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L323)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should be looking at the "Operation" section (pseudo-code) of the CPUID instruction. In my Intel SDM, this is Vol. 2A, Chapter 3.2, pages 3-234. Or check pseudo-code here: https://www.felixcloutier.com/x86/cpuid (e.g., search for `EAX = 8H:`).

`Reserved` always return all-zeros. `Unrecognized` return the same as the "highest basic supported CPUID leaf".
</blockquote></details>

On my CPU this leaf is reserved.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 390 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFu_kVEyTZPQPn-hvX:-MdXgecD4pz17c27FSuC:bfhqml6) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L390)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 325 at r2](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdXfl8B30ZKWKRyv5Vy:-MdXfl8B30ZKWKRyv5Vz:b-wzju0w) ([raw file](https://github.com/oscarlab/graphene/blob/a5d801895ad44b119ecafd3b7219d2da2d402265/Pal/src/host/Linux-SGX/db_misc.c#L325)):*
> ```C
>     /* NOTE: 0x11 leaf is not recognized, see code below */
>     {.leaf = 0x12, .zero_subleaf = false, .cache = true},  /* Intel SGX Capability */
>     /* NOTE: 0x13 leaf is not recognized, see code below */
> ```

On my CPU this leaf is reserved.


<!-- Sent from Reviewable.io -->

2021-07-02 07:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: 0 of 2 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2440#-Mda926r7OMPe1YfS9Aj:-Mda926r7OMPe1YfS9Ak:b-kxr13l) (no related file):*
> make our CPUID logic exactly the same as in the latest Intel SDM documentation

This sentence in my commit message is now not entirely correct. I will replace it with something like `make our CPUID logic conform to the actual CPU behavior and to the latest Intel SDM documentation`.

---
___
*[LibOS/shim/test/regression/cpuid.c, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtagcCGrkt_6YSsSW:-Mda7AfK7dMUzQKEZeK_:b-nb9eze) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/LibOS/shim/test/regression/cpuid.c#L92)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On my CPU `0x13` returns all-zeros but `0x1b` returns highest supported info.
</blockquote></details>

Done. Changed to `0x1b` here. See also my comments below.
___
*[LibOS/shim/test/regression/cpuid.c, line 116 at r2](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdX_Y-69e1HfQ14XALh:-Mda5cqKAtmBMSa5vaLx:b-38qgtq) ([raw file](https://github.com/oscarlab/graphene/blob/a5d801895ad44b119ecafd3b7219d2da2d402265/LibOS/shim/test/regression/cpuid.c#L116)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We should return highest supported leaf info here - technically that could be all zeroes, but most likely it's not. It's also most likely not important, so not blocking.
</blockquote></details>

I also checked that on my local machine, these leafs return the highest supported leaf info. However, this looks to directly contradict to what the Intel SDM says: `No existing or future CPU will return processor identification or feature information` (clearly by returning the highest supported leaf info, we do `return feature information`). So what the hack is happening here, I don't understand. I'll keep our Graphene logic as-is for now, but adding a comment.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 323 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtrBl4WL55HpiZmrY:-Mda7Hxn9V-500yNnrjM:bqoq0p3) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L323)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On my CPU this leaf is reserved.
</blockquote></details>

Done. On my CPU as well. So it looks like `0x11` and `0x13` are reserved after all. So I'm adding them as such and adding a comment (because the Intel SDM says otherwise...).
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 390 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFu_kVEyTZPQPn-hvX:-Mda25mi44GZHNRAZuMm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L390)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 325 at r2](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdXfl8B30ZKWKRyv5Vy:-Mda8BUFDbrrpWWe4Tvd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a5d801895ad44b119ecafd3b7219d2da2d402265/Pal/src/host/Linux-SGX/db_misc.c#L325)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On my CPU this leaf is reserved.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-02 14:11 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/regression/cpuid.c, line 116 at r2](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdX_Y-69e1HfQ14XALh:-MdbXkJ81y01uO9UXtOY:b-ofellu) ([raw file](https://github.com/oscarlab/graphene/blob/a5d801895ad44b119ecafd3b7219d2da2d402265/LibOS/shim/test/regression/cpuid.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also checked that on my local machine, these leafs return the highest supported leaf info. However, this looks to directly contradict to what the Intel SDM says: `No existing or future CPU will return processor identification or feature information` (clearly by returning the highest supported leaf info, we do `return feature information`). So what the hack is happening here, I don't understand. I'll keep our Graphene logic as-is for now, but adding a comment.
</blockquote></details>

On the other hand it states that these leafs are invalid and it also states that for invalid leafs it returns highest basic info...
I guess it's just a messy documentation :)
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 360 at r3](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdbYduH21YdTHD8DSMs:-MdbYduI-RARw3C9ENVr:b-oqlh3f) ([raw file](https://github.com/oscarlab/graphene/blob/e35825059b3fb54259775aab6ceac0a6a591c833/Pal/src/host/Linux-SGX/db_misc.c#L360)):*
> ```C
>      * they return all zeros on bare metal; runtimes like JVM query these leaves to learn about
>      * the underlying virtualization software */
>     if (leaf >= 0x40000000 && leaf <= 0x4FFFFFFF) {
> ```

Why don't we remove this special case? It would be consistent with SDM and actual CPUs then...


<!-- Sent from Reviewable.io -->

2021-07-02 18:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: 0 of 2 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/test/regression/cpuid.c, line 116 at r2](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdX_Y-69e1HfQ14XALh:-MdcYjac6Uv2lqgJKQe-:b22hrsf) ([raw file](https://github.com/oscarlab/graphene/blob/a5d801895ad44b119ecafd3b7219d2da2d402265/LibOS/shim/test/regression/cpuid.c#L116)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On the other hand it states that these leafs are invalid and it also states that for invalid leafs it returns highest basic info...
I guess it's just a messy documentation :)
</blockquote></details>

Done. You're right, it's probably just messy documentation.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 360 at r3](https://reviewable.io/reviews/oscarlab/graphene/2440#-MdbYduH21YdTHD8DSMs:-MdcZIdh2RK8tZYfkIFY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e35825059b3fb54259775aab6ceac0a6a591c833/Pal/src/host/Linux-SGX/db_misc.c#L360)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why don't we remove this special case? It would be consistent with SDM and actual CPUs then...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-02 20:10 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: all files reviewed, 9 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-07-02 21:46 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2440#-Mda926r7OMPe1YfS9Aj:-MdcxCvZ92LnBgw3iNq0:b-azows4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> make our CPUID logic exactly the same as in the latest Intel SDM documentation

This sentence in my commit message is now not entirely correct. I will replace it with something like `make our CPUID logic conform to the actual CPU behavior and to the latest Intel SDM documentation`.
</blockquote></details>

heh, typical x86

---
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 323 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtrBl4WL55HpiZmrY:-Mdd74m2CtGkHZlGbfVu:behmdwu) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L323)):*
> e.g., search for `EAX = 8H:`

What I meant is that there's completely zero information about 0x11 and 0x13 leaves (under which I posted my original comment), so how do we know they are "reserved" and not "unrecognized"? From manual testing on a random x86 CPU I guess?

Update: I see from the comment below that I guessed correctly :)


<!-- Sent from Reviewable.io -->

2021-07-02 21:53 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-07-02 21:56 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-07-02 21:56 UTC, dimakuv reviewed
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2440)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 323 at r1](https://reviewable.io/reviews/oscarlab/graphene/2440#-McFtrBl4WL55HpiZmrY:-MddD1dFEkKOsl9AYGd0:b-n6rkk8) ([raw file](https://github.com/oscarlab/graphene/blob/8b568a295a2f3ca7ddd4d8e8d5effe8868f6015c/Pal/src/host/Linux-SGX/db_misc.c#L323)):*
> there's completely zero information about 0x11 and 0x13 leaves (under which I posted my original comment), so how do we know they are "reserved" and not "unrecognized"? 

I assumed that "zero information" in the Intel SDM means that these leaves are "unrecognized". But I was wrong.


<!-- Sent from Reviewable.io -->

2021-07-02 22:21 UTC, merged