[Pal/Linux] Honor `loader.pal_internal_mem_size` limit
oscarlab/graphene pull request #2444
Opened 2021-06-15 10:09 UTC by dimakuv

## Description of the changes 

Previously, only the Linux-SGX PAL honored the manifest option `loader.pal_internal_mem_size`. The Linux PAL simply performed
`mmap(/*addr=*/NULL, ..)` when 64MB of the pre-allocated memory pool depleted, which led to memory corruptions (since LibOS was unaware of this PAL-internal mmap and could overwrite it, and vice versa).

This commit fixes Linux PAL's allocator to honor this limit. The whole virtual space of the process is split into two parts: the lower part is for LibOS consumption, the upper part is for internal PAL consumption, so there is no possibility for memory corruptions any more.

As part of this fix, PAL memory allocation routines have stricter checks on allocation arguments. As a side effect, PAL regression tests are modified to always use fixed memory addresses.

## How to test this PR? 

This was found on a huge Java workload (which allocated more than 1000 threads in parallel!). One can manually test with smth like this:
```
diff --git a/LibOS/shim/test/regression/multi_pthread.c b/LibOS/shim/test/regression/multi_pthread.c
-#define CONC_THREAD_NUM 4
+#define CONC_THREAD_NUM 1024

 static void* inc(void* arg) {
+        sleep(1);
     counter++;
     return NULL;
 }

diff --git a/LibOS/shim/test/regression/multi_pthread.manifest.template b/LibOS/shim/test/regression/multi_pthread.manifest.te
mplate
@@ -7,6 +7,8 @@ fs.mount.lib.type = "chroot"

+loader.pal_internal_mem_size = "256M"
+
```

2021-06-15 11:41 UTC, mkow requested changes
> This was found on a huge Java workload (which allocated more than 1000 threads in parallel!).

:O

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444#-:-McEPHI-CX9AtUDIHNpC:b-sg23yv)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2444#-McERbgj8F96subSWj5D:-McERbgj8F96subSWj5E:b-cun8ac) (no related file):*
/summon @boryspoplawski

---
___
*[Pal/regression/Memory.c, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McEPWu91oENapfnW7dK:-McEPWuABkjTAvcXPEMT:b-86oyir) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/regression/Memory.c#L2)):*
> ```C
> /* XXX: What on earth is this supposed to be, an attempt to fit most UBs in one file?
>  * XXX: +1, please someone rm rf this file. */
> ```

+1
Or maybe the whole PAL regression directory while we're here :)
___
*[Pal/src/host/Linux/db_memory.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McER-P0BqCluVA0lb-4:-McER-P1CljKRXleCyqh:be554p2) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/host/Linux/db_memory.c#L25)):*
> ```C
>  * address space in two parts:
>  *   - the lower part (before TEXT_START) is for LibOS consumption,
>  *   - the upper part (after DATA_END) is for internal PAL consumption.
> ```

Won't this break non-PIE binaries on high addresses?
___
*[Pal/src/host/Linux/db_memory.c, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McESfBZ1Y27Rrgv67S6:-McESfBZ1Y27Rrgv67S7:bglu4x) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/host/Linux/db_memory.c#L62)):*
> ```C
>         }
>         addr = ALIGN_UP_PTR((char*)DATA_END + g_pal_internal_mem_used, g_page_size);
>         g_pal_internal_mem_used += size;
> ```

This can diverge after a few unaligned allocations. You need to set it to `addr - (char*)DATA_END`.
___
*[Pal/src/host/Linux-SGX/db_memory.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McETQP_6UmO0l53wMLx:-McETQP_6UmO0l53wMLy:b-nmpq4i) ([raw file](https://github.com/oscarlab/graphene/blob/69e5edafa58e3e98ce88991956fe8c8404f0e7f4/Pal/src/host/Linux-SGX/db_memory.c#L46)):*
> ```C
> 
>     if ((alloc_type & PAL_ALLOC_INTERNAL) && addr) {
>         /* internal-PAL memory allocation never uses fixed addresses */
> ```

Why is this different between SGX and non-SGX PALs?


<!-- Sent from Reviewable.io -->

2021-06-15 13:14 UTC, boryspoplawski requested changes
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: 7 of 10 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2444#-McEnkp0ElfU9gPH1eVq:-McEnkp12zwV1IH_ar5A:b-xot500) (no related file):*
As discussed internally, I've pushed a PoC with alternative approach.

---
___
*[Pal/src/db_streams.c, line 426 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McEYTtu2V3KP5Sl8Qis:-McEYTtv1MeW_WBUZrEI:b-dgyq6p) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/db_streams.c#L426)):*
> ```C
>     void* map_addr = *addr;
> 
>     /* TODO: we must not allow NULL addresses here, but sendfile() in LibOS does it -- it must be
> ```

Please also add a note near `sendfile` so we don't forget.
___
*[Pal/src/host/Linux/db_main.c, line 303 at r2](https://reviewable.io/reviews/oscarlab/graphene/2444#-McEnbrz9h_kNEXqrFu7:-McEnbrz9h_kNEXqrFu8:b-jnp61j) ([raw file](https://github.com/oscarlab/graphene/blob/89268270348d482a67dfd3421dbf273d146d889f/Pal/src/host/Linux/db_main.c#L303)):*
> ```C
> 
>     ret = toml_sizestring_in(g_pal_state.manifest_root, "loader.pal_internal_mem_size",
>                              /*defaultval=*/g_page_size, &g_pal_internal_mem_size);
> ```

It's easier to always allocate 1 single page than to deal with special cases later on.
___
*[Pal/src/host/Linux/db_memory.c, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McESfBZ1Y27Rrgv67S6:-McEagb-DdrJWjYO126p:bo6z5pm) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/host/Linux/db_memory.c#L62)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This can diverge after a few unaligned allocations. You need to set it to `addr - (char*)DATA_END`.
</blockquote></details>

`addr - DATA_END + size` actually.


<!-- Sent from Reviewable.io -->

2021-06-15 14:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: 7 of 12 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2444#-McEnkp0ElfU9gPH1eVq:-McExuba-JM2SLHRukqZ:bvohpqm) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

As discussed internally, I've pushed a PoC with alternative approach.
</blockquote></details>

Incorporated and rebased.

---
___
*[Pal/src/db_streams.c, line 426 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McEYTtu2V3KP5Sl8Qis:-McEvz6M-Qzlk_pZEDjd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/db_streams.c#L426)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please also add a note near `sendfile` so we don't forget.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_memory.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McER-P0BqCluVA0lb-4:-McExoga6yl6dAYP25QS:bld74jo) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/host/Linux/db_memory.c#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Won't this break non-PIE binaries on high addresses?
</blockquote></details>

Done. Borys fixed this part, so I rewrote the comment.
___
*[Pal/src/host/Linux/db_memory.c, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McESfBZ1Y27Rrgv67S6:-McEwuAr0HTXgGzn3GBw:b-ecv3au) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/host/Linux/db_memory.c#L62)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`addr - DATA_END + size` actually.
</blockquote></details>

Done. Borys fixed this.
___
*[Pal/src/host/Linux/pal_linux.h, line 144 at r3](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF-G4q2nB-iKfUdR7_:-McF-G4r3Ep3WDHg-QMd:b4hah3f) ([raw file](https://github.com/oscarlab/graphene/blob/1db57a7e3284064ebd92c4f5e12512831209fc9f/Pal/src/host/Linux/pal_linux.h#L144)):*
> ```objc
> #define TEXT_END   ((void*)(&__text_end))
> #define DATA_START ((void*)(&__data_start))
> #define DATA_END   ((void*)(&__data_end))
> ```

FYI: Not related anymore, but since I found it, I fixed it.
___
*[Pal/src/host/Linux-SGX/db_memory.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McETQP_6UmO0l53wMLx:-McEwV0ZDSHRmLeTMngL:b-dvhi6) ([raw file](https://github.com/oscarlab/graphene/blob/69e5edafa58e3e98ce88991956fe8c8404f0e7f4/Pal/src/host/Linux-SGX/db_memory.c#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this different between SGX and non-SGX PALs?
</blockquote></details>

It is not. I moved this check from Linux-SGX specific code to generic PAL code (`Pal/src/db_memory.c`). So now this check (and one more new one) is shared between both SGX and non-SGX PALs.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 76 at r3](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF-BPGEg0VXAnBK555:-McF-BPGEg0VXAnBK556:b-cz6g50) ([raw file](https://github.com/oscarlab/graphene/blob/1db57a7e3284064ebd92c4f5e12512831209fc9f/Pal/src/host/Linux-SGX/pal_linux.h#L76)):*
> ```objc
> #define TEXT_END   ((void*)(&__text_end))
> #define DATA_START ((void*)(&__data_start))
> #define DATA_END   ((void*)(&__data_end))
> ```

FYI: Not related, but since I found it, I fixed it.


<!-- Sent from Reviewable.io -->

2021-06-15 14:16 UTC, boryspoplawski requested changes
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 308 at r3](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF0C-21FYzfShw02nZ:-McF0C-32y_kK-jB3jk_:b-1lgown) ([raw file](https://github.com/oscarlab/graphene/blob/1db57a7e3284064ebd92c4f5e12512831209fc9f/Pal/src/host/Linux/db_main.c#L308)):*
> ```C
>     }
> 
>     void* internal_mem_addr = (void*)INLINE_SYSCALL(mmap, 6, NULL, g_pal_internal_mem_size,
> ```

Hmm, we have `ARCH_MMAP`, which probably should be used instead (mmap could have different signatures on different archs). Sorry, realized just now.


<!-- Sent from Reviewable.io -->

2021-06-15 14:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: 11 of 12 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 308 at r3](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF0C-21FYzfShw02nZ:-McF29AlCqvjcF4gMsP-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1db57a7e3284064ebd92c4f5e12512831209fc9f/Pal/src/host/Linux/db_main.c#L308)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hmm, we have `ARCH_MMAP`, which probably should be used instead (mmap could have different signatures on different archs). Sorry, realized just now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-15 14:29 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-06-15 14:50 UTC, dimakuv commented
Jenkins, retest this please (just making sure)

2021-06-15 15:01 UTC, mkow requested changes
> Reviewed 1 of 3 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_main.c, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF9Vej0KDO2HVIU32_:-McF9Vej0KDO2HVIU32a:bksw799) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_main.c#L44)):*
> ```C
> char* g_pal_internal_mem_addr = NULL;
> 
> size_t g_page_size = PRESET_PAGESIZE;
> ```

I'd feel safer if this was `const`.
___
*[Pal/src/host/Linux/db_memory.c, line 62 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McESfBZ1Y27Rrgv67S6:-McF9J3g14klgN-5QHa0:b-ki2pkp) ([raw file](https://github.com/oscarlab/graphene/blob/13594009aa3e9c627bc3d0025a0a64c71d1468ac/Pal/src/host/Linux/db_memory.c#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Borys fixed this.
</blockquote></details>

Right. Looks good now :)
___
*[Pal/src/host/Linux/db_memory.c, line 30 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF8nqw2QSumFhCulqd:-McF8nqw2QSumFhCulqe:b-y2cg97) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_memory.c#L30)):*
> ```
> overwrite
> ```

You mean "rewrite"?
___
*[Pal/src/host/Linux/pal_linux.h, line 144 at r3](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF-G4q2nB-iKfUdR7_:-McF9o17-dOn_-UOMz2m:bz1dhva) ([raw file](https://github.com/oscarlab/graphene/blob/1db57a7e3284064ebd92c4f5e12512831209fc9f/Pal/src/host/Linux/pal_linux.h#L144)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Not related anymore, but since I found it, I fixed it.
</blockquote></details>

:scream:
___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McFA75wDwV5rRdkx12s:b11yw0e) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
> ```objc
> extern size_t g_page_size;
> extern char* g_pal_internal_mem_addr;
> extern size_t g_pal_internal_mem_size;
> ```

I'd const all of them in the header and only allow editing (or rather initialization) from db_main.c.
___
*[Pal/src/host/Linux-SGX/db_memory.c, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene/2444#-McETQP_6UmO0l53wMLx:-McFAR058czEoIOjw5-6:bcslg4n) ([raw file](https://github.com/oscarlab/graphene/blob/69e5edafa58e3e98ce88991956fe8c8404f0e7f4/Pal/src/host/Linux-SGX/db_memory.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It is not. I moved this check from Linux-SGX specific code to generic PAL code (`Pal/src/db_memory.c`). So now this check (and one more new one) is shared between both SGX and non-SGX PALs.
</blockquote></details>

Ahh, I missed that it's not in the shared part. Thanks for clarification.


<!-- Sent from Reviewable.io -->

2021-06-15 15:19 UTC, boryspoplawski submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF9Vej0KDO2HVIU32_:-McFFDBKDw-sId4sxDRv:b-on5b05) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_main.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd feel safer if this was `const`.
</blockquote></details>

But it's not constant (it's set in runtime).
___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McFFMl79BxB-qZOJJ_5:btqx1s5) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd const all of them in the header and only allow editing (or rather initialization) from db_main.c.
</blockquote></details>

But they are initialized in runtime.


<!-- Sent from Reviewable.io -->

2021-06-15 15:24 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: 11 of 12 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF9Vej0KDO2HVIU32_:-McFDQSF5P2oiVIGRbvE:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_main.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd feel safer if this was `const`.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_memory.c, line 30 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF8nqw2QSumFhCulqd:-McFDVp88bPHwWNIy5qM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_memory.c#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> overwrite
> ```

You mean "rewrite"?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McFGM0RAbQvk5cXg8kI:b-7m02o2) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But they are initialized in runtime.
</blockquote></details>

I didn't do anything about this comment, looks like Michal misunderstood something.


<!-- Sent from Reviewable.io -->

2021-06-15 15:28 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-06-15 18:11 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_main.c, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF9Vej0KDO2HVIU32_:-McFnXeN0kFsEUGnEeqi:b-xde6a3) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_main.c#L44)):*
> it's set in runtime

where?
___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McFqT2Y-kseJMD6tQVP:buhov37) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I didn't do anything about this comment, looks like Michal misunderstood something.
</blockquote></details>

Nah, I understand everything ;)
`const` in C doesn't mean that it doesn't change, but that you can't change the value through this declaration. So, this would forbid changing it from the outside. Unfortunately though, it seems that db_main.c includes this header, which causes a conflict there.


<!-- Sent from Reviewable.io -->

2021-06-15 18:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF9Vej0KDO2HVIU32_:-McFzr5p2QLuMbgACk1a:b6p0c28) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_main.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> it's set in runtime

where?
</blockquote></details>

See below comment.
___
*[Pal/src/host/Linux/db_main.c, line 82 at r5](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFzl3I08Q33-gtCaTd:-McFzl3JBP8wm1FJ3Gjo:b73pfwu) ([raw file](https://github.com/oscarlab/graphene/blob/093b401472eae8591eea86f5861f941372283f8d/Pal/src/host/Linux/db_main.c#L82)):*
> ```C
>         switch (av->a_type) {
>             case AT_PAGESZ:
>                 g_page_size = av->a_un.a_val;
> ```

@mkow Here `g_page_size` may be overwritten at runtime.
___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McFDd6z1F0uWvKdUolH:b-d78sm6) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nah, I understand everything ;)
`const` in C doesn't mean that it doesn't change, but that you can't change the value through this declaration. So, this would forbid changing it from the outside. Unfortunately though, it seems that db_main.c includes this header, which causes a conflict there.
</blockquote></details>

Yes. I understand your point now, it would be smart to hide their initialization. But yeah, needs untangling of header files. Not for this PR, but will keep in mind, we have a bunch of such "almost-constants".


<!-- Sent from Reviewable.io -->

2021-06-15 19:06 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 82 at r5](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFzl3I08Q33-gtCaTd:-McG2rsYDYSw91UGqCUv:b-n7yj88) ([raw file](https://github.com/oscarlab/graphene/blob/093b401472eae8591eea86f5861f941372283f8d/Pal/src/host/Linux/db_main.c#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@mkow Here `g_page_size` may be overwritten at runtime.
</blockquote></details>

Ouch, that's quite bad. We start with one page size and then in runtime it can suddenly change? We should just check here whether the sizes match, and if not then just abort with an error.


<!-- Sent from Reviewable.io -->

2021-06-15 19:47 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 82 at r5](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFzl3I08Q33-gtCaTd:-McGBcw-A1u1FtzSWIi4:b-cpsc1o) ([raw file](https://github.com/oscarlab/graphene/blob/093b401472eae8591eea86f5861f941372283f8d/Pal/src/host/Linux/db_main.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ouch, that's quite bad. We start with one page size and then in runtime it can suddenly change? We should just check here whether the sizes match, and if not then just abort with an error.
</blockquote></details>

It's not really like that, it's supposed to be inside a very early init routine. But as always, some things are messed here. I would rather not stash such change into this PR tho.
___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McGC3ZH1IQVI3kqAvL0:b-abput1) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes. I understand your point now, it would be smart to hide their initialization. But yeah, needs untangling of header files. Not for this PR, but will keep in mind, we have a bunch of such "almost-constants".
</blockquote></details>

No no no, you cannot do this, that's UB (having an `extern const type X` in here and `type X` in `db_main.c`).


<!-- Sent from Reviewable.io -->

2021-06-15 19:53 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McGE-EsCOFY7Q1m0b7H:bkys1dz) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No no no, you cannot do this, that's UB (having an `extern const type X` in here and `type X` in `db_main.c`).
</blockquote></details>

Huh, really? Are you sure?


<!-- Sent from Reviewable.io -->

2021-06-15 20:22 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McGKReZBeVbssqq28xp:br6wxpr) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Huh, really? Are you sure?
</blockquote></details>

Quoting standard (c11): `All declarations  that  refer  to  the  same  object  or  function  shall  have  compatible  type; otherwise, the behavior is undefined.`
`const size_t` and `size_t` are **not** compatible.


<!-- Sent from Reviewable.io -->

2021-06-15 21:18 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 82 at r5](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFzl3I08Q33-gtCaTd:-McGXDlIDwk6tBTobHEP:bk2out9) ([raw file](https://github.com/oscarlab/graphene/blob/093b401472eae8591eea86f5861f941372283f8d/Pal/src/host/Linux/db_main.c#L82)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not really like that, it's supposed to be inside a very early init routine. But as always, some things are messed here. I would rather not stash such change into this PR tho.
</blockquote></details>

I'd prefer to fix this while we're here, it seems trivial (but in a separate commit).
___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McGX0SLCIBioJsJVjep:b-9o8yo8) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Quoting standard (c11): `All declarations  that  refer  to  the  same  object  or  function  shall  have  compatible  type; otherwise, the behavior is undefined.`
`const size_t` and `size_t` are **not** compatible.
</blockquote></details>

I thought that `const X` is compatible with `X`, but reading the standard closely it seems that they aren't. TIL.


<!-- Sent from Reviewable.io -->

2021-06-15 23:19 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McGxnJLEwbFB__2q4vu:bp8iuub) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I thought that `const X` is compatible with `X`, but reading the standard closely it seems that they aren't. TIL.
</blockquote></details>

If it was, then e.g. you could write `int* ptr = (const int*)NULL;`


<!-- Sent from Reviewable.io -->

2021-06-15 23:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McGz6FI9Y7hOZOkl1OH:b-gs8dnt) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If it was, then e.g. you could write `int* ptr = (const int*)NULL;`
</blockquote></details>

But for this you need to know how such deref are defined, i.e. whether the types need to be "compatible" or some other wording is used in the standard ;) (e.g. "compatible + same qualifiers")


<!-- Sent from Reviewable.io -->

2021-06-16 00:03 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux/pal_linux.h, line 108 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFA75wDwV5rRdkx12r:-McH4y9C2okzWbJ7YPJm:bark95q) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/pal_linux.h#L108)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But for this you need to know how such deref are defined, i.e. whether the types need to be "compatible" or some other wording is used in the standard ;) (e.g. "compatible + same qualifiers")
</blockquote></details>

deref? This is simple assignment. Less concise example:
```c
const int x = 1;
const int* a = &x;
int* b = a;
```
Generally, I think you can use compatible types interchangeably in most (all?) cases.


<!-- Sent from Reviewable.io -->

2021-06-16 06:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: 8 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 44 at r4](https://reviewable.io/reviews/oscarlab/graphene/2444#-McF9Vej0KDO2HVIU32_:-McI_RLy80iFjGhKn9_a:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/60b41689bb4505080436646d12e48f828b33f725/Pal/src/host/Linux/db_main.c#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See below comment.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux/db_main.c, line 82 at r5](https://reviewable.io/reviews/oscarlab/graphene/2444#-McFzl3I08Q33-gtCaTd:-McI_U4P6BxRwEy8Ubv9:bnw788e) ([raw file](https://github.com/oscarlab/graphene/blob/093b401472eae8591eea86f5861f941372283f8d/Pal/src/host/Linux/db_main.c#L82)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to fix this while we're here, it seems trivial (but in a separate commit).
</blockquote></details>

Done. `g_page_size` was a mess in all PALs. I fixed it all (hopefully), now it's a constant and just verified at runtime.


<!-- Sent from Reviewable.io -->

2021-06-16 10:31 UTC, boryspoplawski approved these changes
> Reviewed 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-06-16 11:02 UTC, mkow approved these changes
> Reviewed 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2444)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-16 11:12 UTC, merged