[Pal/Linux-SGX] Disallow creating unknown files
oscarlab/graphene pull request #2446
Opened 2021-06-15 18:45 UTC by dimakuv

## Description of the changes 

Previously, Linux-SGX PAL had a bug of creating any files from within the enclave, even though such files were not listed as allowed or trusted files/paths. This commit fixes this bug, and also disallows opening a trusted file for write/append (because this doesn't make sense and write operations are already disallowed for trusted files).

## How to test this PR? 

The `file_check_policy` LibOS regression test is augmented to test this bug fix.

2021-06-15 19:17 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2446#-McG5SnX9LhVj4r8ql8c:-McG5SnX9LhVj4r8ql8d:byts3il) (no related file):*
I tested this PR and something weird happens, the unknown file I tried to create is still created on the host, but it's empty. And then the Graphene error appears. I guess you just error out too late?

---


<!-- Sent from Reviewable.io -->

2021-06-16 09:55 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2446#-McG5SnX9LhVj4r8ql8c:-McJE_-N1_237AV1Pane:b-3i29om) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I tested this PR and something weird happens, the unknown file I tried to create is still created on the host, but it's empty. And then the Graphene error appears. I guess you just error out too late?
</blockquote></details>

Turns out it was like this the whole time, unrelated to this PR. Graphene did `ocall_open()` in the very beginning of `file_open()` and only then performed checks.

I submitted a follow-up PR #2450. I would prefer to leave this PR as is and continue with your found bug in that new PR.

---


<!-- Sent from Reviewable.io -->

2021-06-16 15:56 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2446#-McG5SnX9LhVj4r8ql8c:-McJTDOPA1mVK01HJSnU:b-ff2g7e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Turns out it was like this the whole time, unrelated to this PR. Graphene did `ocall_open()` in the very beginning of `file_open()` and only then performed checks.

I submitted a follow-up PR #2450. I would prefer to leave this PR as is and continue with your found bug in that new PR.
</blockquote></details>

Huh. Thanks for fixing this!

---
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 324 at r1](https://reviewable.io/reviews/oscarlab/graphene/2446#-McKWyJy-m7umBozYGsO:-McKWyJz71JeXWttK9YZ:b-ho1a7m) ([raw file](https://github.com/oscarlab/graphene/blob/a3308886b644b8737cd578a5cc59b5bd2d15b2eb/Pal/src/host/Linux-SGX/enclave_framework.c#L324)):*
> ```C
> 
>     if (create && !tf->allowed) {
>         log_error("Trying to create/write/append an already-created trusted '%s'\n", uri);
> ```

`trusted` -> `trusted file`


<!-- Sent from Reviewable.io -->

2021-06-17 07:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 324 at r1](https://reviewable.io/reviews/oscarlab/graphene/2446#-McKWyJy-m7umBozYGsO:-McNvYkq6vrHQPuSmOYM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a3308886b644b8737cd578a5cc59b5bd2d15b2eb/Pal/src/host/Linux-SGX/enclave_framework.c#L324)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`trusted` -> `trusted file`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-17 08:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 324 at r1](https://reviewable.io/reviews/oscarlab/graphene/2446#-McKWyJy-m7umBozYGsO:-McO26LB55XrU_bOxgQl:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a3308886b644b8737cd578a5cc59b5bd2d15b2eb/Pal/src/host/Linux-SGX/enclave_framework.c#L324)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-17 13:08 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-18 10:23 UTC, pwmarcz requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2446#-McTbTQZCk1N5V_WAhT4:-McTbTQ_BOpkvsp9zggA:b-uu1ibg) (no related file):*
So, if I understand correctly:

- *allowed* files can be opened for writing, and created if they do not exist already,
- *trusted* files can be only opened for reading, and new ones cannot be created.
- `sgx.file_check_policy` effectively makes all unknown files allowed, but still does not allow writing/creating files specified as trusted.

Can you describe this behavior in `manifest-syntax.rst`? I think it's worth spelling out.

---


<!-- Sent from Reviewable.io -->

2021-06-18 12:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: 3 of 4 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2446#-McTbTQZCk1N5V_WAhT4:-McTyUtf6W6gDMQTnrNn:bqagmuo) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

So, if I understand correctly:

- *allowed* files can be opened for writing, and created if they do not exist already,
- *trusted* files can be only opened for reading, and new ones cannot be created.
- `sgx.file_check_policy` effectively makes all unknown files allowed, but still does not allow writing/creating files specified as trusted.

Can you describe this behavior in `manifest-syntax.rst`? I think it's worth spelling out.
</blockquote></details>

Done. Very good point.

---


<!-- Sent from Reviewable.io -->

2021-06-18 12:14 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-18 12:48 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-18 14:44 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-19 03:04 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-21 10:26 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 521 at r5](https://reviewable.io/reviews/oscarlab/graphene/2446#-Mci5kaa8gSzjdh84bbl:-Mci5kaa8gSzjdh84bbm:b-5olh4r) ([raw file](https://github.com/oscarlab/graphene/blob/3bf764ae58844c7ea9b2f25e8c2a8edf9bc94679/Documentation/manifest-syntax.rst#L521)):*
> ```reStructuredText
> trusted and allowed are allowed for access, and Graphene-SGX emits a warning
> message for every such file. Effectively, this policy operates on all unknown
> files as if they were listed as _allowed_files_. (However, this policy still
> ```

Now it doesn't render correctly. See #2454 for a working solution :)


<!-- Sent from Reviewable.io -->

2021-06-21 11:23 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2446)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-21 13:41 UTC, merged