[LibOS] Refactor pseudo filesystems
oscarlab/graphene pull request #2453
Opened 2021-06-16 15:17 UTC by pwmarcz

## Description of the changes 

See commit message for details.

I need this rewrite now, because it's really hard to change anything FS-related while tripping over all this boilerplate code in `/proc`, `/dev` and `/sys`. Now, `shim_fs_pseudo.c` provides an extra abstraction layer: when I'm refactoring, hopefully I won't need to touch these individual filesystems again, just `shim_fs_pseudo`.

Also, hopefully code for individual filesystems is much nicer now. 

I realize it's a huge change. The problem is that it's hard to split: I could submit a change that rewrites just, say, `/dev`, but then there would be two `shim_fs_pseudo` implementations: old one, and new one; and some names might collide (when I was working on it, I did exactly that, and had to change some function names to `pseudo2_*`).

Fixes issues with `/proc` (#2385, #948).

## How to test this PR? 

* The tests for `proc` and `sys` are stronger: they literally look at every file and directory (then Python assertions check the result). You can examine what they do by running them (`graphene-direct proc_common`, `graphene_direct sysfs_common`).

* If you want to examine the filesystems, I recommend the `busybox` example (e.g. `graphene-direct busybox ls -la /proc`).

2021-06-16 15:25 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: 0 of 34 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene/2453#-McKPpFO7e6JEBgXRx2p:-McKPpFO7e6JEBgXRx2q:blq5wo7) ([raw file](https://github.com/oscarlab/graphene/blob/517ccc59f891f8d0ff3fa865813d50e3416a5746/LibOS/shim/include/shim_fs_pseudo.h#L136)):*
> ```objc
> };
> 
> struct pseudo_node* pseudo_add_root_dir(const char* name);
> ```

FYI: these functions allocate memory, and abort on failure. I'm not sure about this, but it makes the setup code much easier to read (otherwise every single invocation in `init_procfs()` etc. needs to be guarded).
___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 851 at r2](https://reviewable.io/reviews/oscarlab/graphene/2453#-McKPKZE4kWF-d_23nGN:-McKPKZE4kWF-d_23nGO:b-sjg072) ([raw file](https://github.com/oscarlab/graphene/blob/074091da29e95df47fb3261f7dac525f9b346506/LibOS/shim/src/ipc/shim_ipc_ranges.c#L851)):*
> ```C
>         ret = ipc_pid_getstatus(owner, idx == UNDEF_IDX ? RANGE_SIZE : 1, pids, &retstatus);
> 
>         if (ret >= 0 && retstatus->count > 0) {
> ```

FYI, this function broke after 26e3155c3483f3ae95e0b7b71cb3f7be69d6796f (my code using it was working until I rebased on top of it). It looks super ugly and I don't want to go too deep fixing it now...


<!-- Sent from Reviewable.io -->

2021-06-17 12:38 UTC, dimakuv requested changes
> Reviewed 28 of 34 files at r1, 1 of 1 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 42 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[common/include/api.h, line 173 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO79Wy45gMn6chK-tU:-McO79WzBi6-iEh60r3f:b-w5f08d) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/common/include/api.h#L173)):*
> ```objc
> /* Converts a string to unsigned int. Requires the string to be non-empty, consist only of decimal
>  * digits, and not overflow. Returns 0 on success, -1 on failure. */
> int parse_uint(const char* str, unsigned int* value);
> ```

You introduced this function because `str_to_ulong()` works on longs, and you needed ints?

Why not introduce `str_to_uint(const char* str, int base, unsigned long* out_value, char** out_endptr)` for uniformity?
___
*[LibOS/shim/include/shim_fs.h, line 676 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOFEze9iX_ENKQaXAt:-McOFEze9iX_ENKQaXAu:b9s71ja) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/include/shim_fs.h#L676)):*
> ```objc
> 
> extern struct shim_fs chroot_builtin_fs;
> extern struct shim_fs dev_builtin_fs;
> ```

Why do you still need this here?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene/2453#-McKPpFO7e6JEBgXRx2p:-McOBTtN3qa9SDKkvI2o:bl3egys) ([raw file](https://github.com/oscarlab/graphene/blob/517ccc59f891f8d0ff3fa865813d50e3416a5746/LibOS/shim/include/shim_fs_pseudo.h#L136)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

FYI: these functions allocate memory, and abort on failure. I'm not sure about this, but it makes the setup code much easier to read (otherwise every single invocation in `init_procfs()` etc. needs to be guarded).
</blockquote></details>

These functions are called only during LibOS initialization, right? In this case, I'm fine with just `abort()` on OOM.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 8 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9TkEELv0h2dXLhIz:-McO9TkEELv0h2dXLhJ-:b-5ql7f) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L8)):*
> ```objc
> /*
>  * This file defines the "pseudo" filesystem: a building block for implementing pseudo-FS's such as
>  * `/proc` or `/sys`.
> ```

What about `/dev`? I see that you have `PSEUDO_DEV`, so couldn't your new machinery also replace `dev_builtin_fs`?

UPDATE: Actually, seems like you already do this...
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 16 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9F6xBD2B1jVb9kJo:-McO9F6xBD2B1jVb9kJp:b-thalo8) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L16)):*
> ```objc
>  *     pseudo_add_str(root, "cpuinfo", &proc_cpuinfo_load);
>  *
>  * It can the be mounted by providing the root name ("proc" in the example):
> ```

`then`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 28 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9NAsBxGlfrwbtLuZ:-McO9NAsBxGlfrwbtLu_:bciv0p3) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L28)):*
> ```objc
> #include "perm.h"
> #include "list.h"
> #include "shim_fs.h"
> ```

Please sort this include list
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 53 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9tXuDKNiM9frVSy8:-McO9tXuDKNiM9frVSy9:b-xo0caj) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L53)):*
> ```objc
>     int (*flush)(struct shim_handle* hdl);
>     off_t (*seek)(struct shim_handle* hdl, off_t offset, int whence);
>     int (*truncate)(struct shim_handle* hdl, uint64_t len);
> ```

Shouldn't it be `size_t len`?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 148 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOBu0-4kkF8-H6M6Hv:-McOBu0-4kkF8-H6M6Hw:b-f40t1) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L148)):*
> ```objc
> struct pseudo_node* pseudo_add_dev(struct pseudo_node* parent_ent, const char* name);
> 
> extern struct shim_fs pseudo_builtin_fs;
> ```

You declare it twice, here and in `shim_fs.h`. Can you remove one of these copies?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 179 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOoGcu0qnx47qtywGk:-McOoGcu0qnx47qtywGl:b8qq2r6) ([raw file](https://github.com/oscarlab/graphene/blob/351abb3ba5d9e082a72f989d3aa72062790faec1/LibOS/shim/include/shim_fs_pseudo.h#L179)):*
> ```objc
> int dev_null_truncate(struct shim_handle* hdl, uint64_t size);
> ssize_t dev_zero_read(struct shim_handle* hdl, void* buf, size_t count);
> ssize_t dev_random_read(struct shim_handle* hdl, void* buf, size_t count);
> ```

Why not move all these into `dev/fs.c` and make them static and remove from here?
___
*[LibOS/shim/src/fs/shim_fs.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOFRCF0Rj2LPOO0tmD:-McOFRCF0Rj2LPOO0tmE:be9ynik) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs.c#L63)):*
> ```C
>     int ret;
>     if ((ret = init_procfs()) < 0)
>         return ret;
> ```

What about `destroy_mem_mgr()` in all these error paths?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 13 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOFcRZCsJMlJwB6ElL:-McOFcRZCsJMlJwB6ElM:b-rlcsvl) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L13)):*
> ```C
> #include "perm.h"
> #include "shim_fs_pseudo.h"
> #include "shim_internal.h"
> ```

Please sort
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 51 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOGx3W4NNkVKe7vY2_:-McOGx3W4NNkVKe7vY2a:b7w6vsh) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L51)):*
> ```C
>     const char* name = qstrgetstr(&dent->name);
> 
>     /* Recursive call: find the node for parent */
> ```

This recursion also inits `dent->data` for all parent nodes on the path. Maybe add this remark to the top-level comment for this function?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 56 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOGtbg7-I3NBOSjYqy:-McOGtbhAjBho5gkDY2Z:b6n861g) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L56)):*
> ```C
>         return NULL;
> 
>     /* Look for a find child node with matching name */
> ```

Broken English. Just remove `find`?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 64 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOGna2CaksuXAB09NH:-McOGna2CaksuXAB09NI:b-ttxb4) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L64)):*
> ```C
>             return node;
>         }
>         if (node->match_name && node->match_name(dent->parent, name) >= 0) {
> ```

Why `>= 0`? Looks like should be `== 0`.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 85 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOHGqCESDZkJF7sWo0:-McOHGqCESDZkJF7sWo1:b-gnv3cm) ([raw file](https://github.com/oscarlab/graphe [...]

2021-06-17 17:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: 14 of 36 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[common/include/api.h, line 173 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO79Wy45gMn6chK-tU:-McPJAT74Rei2qa-kHum:b-23ayxj) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/common/include/api.h#L173)):*
>You introduced this function because `str_to_ulong()` works on longs, and you needed ints?

No, it's mostly for convenience: `str_to_ulong` has a weird convention of returning `bool`, allows characters after the number, allows empty numbers, removes whitespace at the beginning, etc.

But okay, I can make the situation better. I changed `str_to_ulong` to be more workable and rewrote the call-sites (it's only used in one file: SGX `db_main.c`).
___
*[LibOS/shim/include/shim_fs.h, line 676 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOFEze9iX_ENKQaXAt:-McPZ-TPE0j3LV8r_u4S:b-wo9224) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/include/shim_fs.h#L676)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you still need this here?
</blockquote></details>

I forgot to remove. Fixed.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 8 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9TkEELv0h2dXLhIz:-McPZ9On5tXC4nx6956m:b8e1iot) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about `/dev`? I see that you have `PSEUDO_DEV`, so couldn't your new machinery also replace `dev_builtin_fs`?

UPDATE: Actually, seems like you already do this...
</blockquote></details>

Added `/dev` here.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 16 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9F6xBD2B1jVb9kJo:-McPZCep6-UkqqeIxyXw:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`then`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 28 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9NAsBxGlfrwbtLuZ:-McPZEWo2BuJsRg8xukB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort this include list
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 53 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9tXuDKNiM9frVSy8:-McPZEy_7C35Cr1T6Jb_:b-uvtrgu) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't it be `size_t len`?
</blockquote></details>

No, this is file size, not memory size, and `size_t` would cause problems on 32-bit. We talked about it on Slack recently, and decided to use `int64_t` / `uint64_t` to be unambiguous.

(The main filesystem interface still uses `off_t`, but I don't want to add more places that use it - now that I noticed it, I also changed `seek` to use `int64_t`).
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 148 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOBu0-4kkF8-H6M6Hv:-McP_XBa04MzFd1HMzfN:b-9z0jof) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L148)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You declare it twice, here and in `shim_fs.h`. Can you remove one of these copies?
</blockquote></details>

OK, I removed the one in `shim_fs.h`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 179 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOoGcu0qnx47qtywGk:-McP_grQB61lKzt5CULN:bb1l6gh) ([raw file](https://github.com/oscarlab/graphene/blob/351abb3ba5d9e082a72f989d3aa72062790faec1/LibOS/shim/include/shim_fs_pseudo.h#L179)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not move all these into `dev/fs.c` and make them static and remove from here?
</blockquote></details>

Makes sense, these are all pretty trivial. Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 63 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOFRCF0Rj2LPOO0tmD:-McPb4s-CTG7bh_uQWdT:b-k784c6) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs.c#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about `destroy_mem_mgr()` in all these error paths?
</blockquote></details>

Done, I fixed error handling in this function.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 426 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOinXl-UMzmnunjWIp:-McPj6nD1c6H6h6zfsM3:b-ly2o6e) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L426)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, this `FS_POLL_SZ` sounds like a dirty hack from old times.
</blockquote></details>

Looks like it :) But now we have a good starting point to removing it.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 245 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOljkXBZ3CVR2uwad7:-McPmg6rDpopkFRT3SrP:bg0d161) ([raw file](https://github.com/oscarlab/graphene/blob/351abb3ba5d9e082a72f989d3aa72062790faec1/LibOS/shim/src/fs/dev/attestation.c#L245)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not `sizeof(g_pf_key_hex)`? Or if you want to use `strlen()`, why not `+1`?
</blockquote></details>

Because we store the key null-terminated.

Okay, I think this will be way less confusing if we treat the key as constant-size array, and convert it to a null-terminated string only when needed (i.e. when we call `DkSetProtectedFilesKey`).
___
*[LibOS/shim/src/fs/dev/attestation.c, line 284 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOmH9G2TEH6yyZgLL-:-McPqhrP9711BQ3iptMs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/351abb3ba5d9e082a72f989d3aa72062790faec1/LibOS/shim/src/fs/dev/attestation.c#L284)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`\n` at the end
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 290 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOmaUl7wKYC-hgWtds:-McPrGlA5Rl-OGGwa_3C:bka9zrm) ([raw file](https://github.com/oscarlab/graphene/blob/351abb3ba5d9e082a72f989d3aa72062790faec1/LibOS/shim/src/fs/dev/attestation.c#L290)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you set the sizes here? We have a special `init_struct_sizes()` function here to init these variables to correct sizes. With your hard-coding, the function `init_struct_sizes()` becomes redundant.
</blockquote></details>

Looks like I added it early for debugging and forgot about it. Fixed.
___
*[LibOS/shim/src/fs/dev/null.c, line 1 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453 [...]

2021-06-18 08:49 UTC, dimakuv requested changes
> Reviewed 23 of 23 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/api.h, line 173 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO79Wy45gMn6chK-tU:-McTDqUZBDn_PSV5omq-:b-wxpo3v) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/common/include/api.h#L173)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>You introduced this function because `str_to_ulong()` works on longs, and you needed ints?

No, it's mostly for convenience: `str_to_ulong` has a weird convention of returning `bool`, allows characters after the number, allows empty numbers, removes whitespace at the beginning, etc.

But okay, I can make the situation better. I changed `str_to_ulong` to be more workable and rewrote the call-sites (it's only used in one file: SGX `db_main.c`).
</blockquote></details>

Thanks, the new version looks great. The old code was adapted from Glibc (I believe), so no wonder it looked so bad :)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 53 at r3](https://reviewable.io/reviews/oscarlab/graphene/2453#-McO9tXuDKNiM9frVSy8:-McTEdr5Da7s3JQdkJd-:b-y3cmxm) ([raw file](https://github.com/oscarlab/graphene/blob/7ad4aba3cb1076a0af76f4649cac0429949f9d52/LibOS/shim/include/shim_fs_pseudo.h#L53)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

No, this is file size, not memory size, and `size_t` would cause problems on 32-bit. We talked about it on Slack recently, and decided to use `int64_t` / `uint64_t` to be unambiguous.

(The main filesystem interface still uses `off_t`, but I don't want to add more places that use it - now that I noticed it, I also changed `seek` to use `int64_t`).
</blockquote></details>

OK, right, now I remembered.
___
*[LibOS/shim/src/fs/sys/fs.c, line 76 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOu8fTBSHIGiaSuf6S:-McTHBIRAUghs6vpyTgL:bc6zzl1) ([raw file](https://github.com/oscarlab/graphene/blob/351abb3ba5d9e082a72f989d3aa72062790faec1/LibOS/shim/src/fs/sys/fs.c#L76)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`sys_resource` actually returns the parsed number... but I regret my choice. Fixed, the parsed number is now passed via out-parameter.
</blockquote></details>

OK, got it. Yes, it was confusing.
___
*[LibOS/shim/src/fs/sys/fs.c, line 102 at r5](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOud309FnLV5MttDzG:-McTHjl964ivVS_K4Fx-:brmxuud) ([raw file](https://github.com/oscarlab/graphene/blob/351abb3ba5d9e082a72f989d3aa72062790faec1/LibOS/shim/src/fs/sys/fs.c#L102)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's related, but somewhat cryptic. I rewrote it.
</blockquote></details>

OK, now I understand. We can't just do `pseudo_add_str(cpuX, "online", &sys_cpu_load)` because of this special case.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 155 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIb446IVfIzBNTkos:-McTIb446IVfIzBNTkot:bxek1ig) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/db_main.c#L155)):*
> ```C
>         return -EINVAL;
>     if (intval > LONG_MAX)
>         return -EINVAL;
> ```

We could collapse these two IFs into one
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIgEd0Q3l197tepUV:-McTIgEd0Q3l197tepUW:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/db_main.c#L224)):*
> ```C
>             return -EINVAL;
>         if (firstint > LONG_MAX)
>             return -EINVAL;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/db_main.c, line 244 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIhJK04i8MtHEDSc0:-McTIhJK04i8MtHEDSc1:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/db_main.c#L244)):*
> ```C
>                 return -EINVAL;
>             if (secondint > LONG_MAX)
>                 return -EINVAL;
> ```

ditto
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c, line 323 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIpXXA4ffhkcfkywC:-McTIpXXA4ffhkcfkywD:bydag4l) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L323)):*
> ```C
>         }
> 
>         size_t secret_len = secret_size - 1; /* length without null terminator */
> ```

How is this related to your changes? Or how did you detect this error?


<!-- Sent from Reviewable.io -->

2021-06-18 09:58 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: 35 of 37 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 85 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOHGqCESDZkJF7sWo0:-McTTcdT5w92rcODwnbi:b-7g5s1b) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L85)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this `!node` even possible? Shouldn't it be an assert?
</blockquote></details>

(Weird, I thought I replied to this, but I don't see my message in Reviewable. I also don't see my replies for several other discussions, which I see you resolved anyway after my changes - thanks!)

It's possible if this is a checkpointed dentry, we're in the new process, and the file turns out not to exist anymore.

More generally, unfortunately this pseudo-fs does not have great cache invalidation: `/proc/<pid>` directories do not disappear when a process exits, etc. This is nothing new, and I don't want to try fixing it now, but I added a comment about it to the top of `shim_fs_pseudo.h`.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 163 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOOqO35xQrWLh8fSoN:-McTUboA7qFNgEH1YEXu:b-86rbu1) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L163)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you remind the logic, why do we update the dentry state/type in `lookup()` here but e.g. don't update/check them on `open()` above?
</blockquote></details>

Opening a directory is mostly handled in `dentry_open`. I added an explanation to `pseudo_open()` about what happens here.

I'm starting to get convinced that this is a bad design, and the `open()` call should not reach the underlying filesystem at all - directory handles should be managed by the outer layer only. I'll try to fix it sometime after this PR.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 217 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOPdg88J96ZEPOt-By:-McTVSUv8wf8_mmkOMSt:blrnz0p) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you return success here?
</blockquote></details>

Looks like a typo, fixed.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 384 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOQs612ZWTJsFls-_W:-McTVa4yEEqK6MEJcgYa:bnf4edp) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L384)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not `-ENOSYS?`
</blockquote></details>

Done. AFAICT this call does not reach us in case of the other handles (dir/link).

I also added `-EINVAL` in case a device does not support flush, this is what Linux seems to do (e.g. `fsync()` on `/dev/null` fd).
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 397 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOiXO-7eG8rpDtKalR:-McTVr9UB36n7S58B3cO:b1bkc5z) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L397)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So it looks like instead of `str_close`, you just free the data manually? I.e., there is no leak, just duplicate functionality.
</blockquote></details>

Yes, this is not a leak, just duplication because the `str_*` API is not exactly what we want. I reworded the comment, hopefully it doesn't imply there is a leak anymore.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 439 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOj4G71w62I9q8KUPV:-McTWaFwD1mMX_i3UvAo:b-jx9e93) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L439)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we add a TODO here that this poll-on-devices just always returns "R/W event ready", and ideally we should use `DkStreamWaitObjects()` (or whatever its name).
</blockquote></details>

`DkStreamWaitObjects` on what? These are pseudo-devices like `/dev/null` or `/dev/zero`, so they should be always ready.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 461 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOj_sqE1TqUgN97y5o:-McTWopm0xz3Ro0wU_C1:b-fkixsl) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L461)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How does all this work under multi-threading? Why don't we grab any locks anywhere?
</blockquote></details>

The setup is performed on process startup. As for `pseudo_find`, you're right, we access `dent->data` in various places and I'm pretty sure they don't all use the same lock. 

So now I take `dent->lock`, that what we seem to do when accessing the dentry `data` field in other filesystems.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 501 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOk-7K---k8nERf1jV:-McTXLs619D8K8JK5hWN:b-xp6czl) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L501)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this even needed? What if you just leave this field NULL and remove `pseudo_mount`?
</blockquote></details>

Without `mount`, we assume the filesystem is unmountable (e.g. `pipe` or `socket`).
___
*[Pal/src/host/Linux-SGX/db_main.c, line 155 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIb446IVfIzBNTkos:-McTSxLLCADpUNPrfyLd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/db_main.c#L155)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We could collapse these two IFs into one
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 224 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIgEd0Q3l197tepUV:-McTT4hX4gKXR3eXtO4y:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/db_main.c#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 244 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIhJK04i8MtHEDSc0:-McTT73I2JF-xiESjJx2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/db_main.c#L244)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c, line 323 at r6](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTIpXXA4ffhkcfkywC:-McTT8Wk68mk1qLArvSg:bghqicb) ([raw file](https://github.com/oscarlab/graphene/blob/7f3ae3d51a86b837142fbedf52e3852179b74ff4/Pal/src/host/Linux-SGX/tools/ra-tls/secret_prov_attest.c#L323)):*
<details><summary><i>Previously, dimakuv (Dmitr [...]

2021-06-18 14:50 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 439 at r4](https://reviewable.io/reviews/oscarlab/graphene/2453#-McOj4G71w62I9q8KUPV:-McU_Gpm1vRm_5Fme6c_:bs5mnuy) ([raw file](https://github.com/oscarlab/graphene/blob/45f736332fb8c3b4ec3bde241498cbebe148ccf7/LibOS/shim/src/fs/shim_fs_pseudo.c#L439)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`DkStreamWaitObjects` on what? These are pseudo-devices like `/dev/null` or `/dev/zero`, so they should be always ready.
</blockquote></details>

Oops, me being stupid.


<!-- Sent from Reviewable.io -->

2021-06-20 12:31 UTC, mkow requested changes
> Reviewed 12 of 34 files at r1, 1 of 1 files at r2, 1 of 3 files at r3, 21 of 23 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 46 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTv6nt-y_UhpAXUOp4:-McTv6nt-y_UhpAXUOp5:b-pn8wlu) (no related file):*
> Fixes issues with /proc (#2385, #948).

Please change this to the GitHub auto-close syntax (in the PR description).

---
___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-McTwDsS1wyRAE9jWooG:bwvhsph) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
> ```objc
>  * after the number.
>  */
> int str_to_ulong(const char* str, unsigned int base, unsigned long* value, const char** end);
> ```

Why dropping `out_` prefixes? I think they are nice for readability to clearly see which args are actually retvals.
___
*[common/src/string/atoi.c, line 78 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McU-3aFCn-ghkF3wqYr:-McU-3aFCn-ghkF3wqYs:b-6xezra) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/src/string/atoi.c#L78)):*
> ```C
>         str += 2;
> 
>     unsigned long _value = 0;
> ```

You wouldn't need the underscore if the out arg was named `out_value` :)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUFIHx5djUlYNzOdvg:-McUFIHyC8mDmLFWpxJl:b-2vca30) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L7)):*
> ```
> pseudo-FS's
> ```

I think this should be "pseudo-FSes" or "pseudo-FS-es"
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 56 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUchQt2j1CMqO35PV9:-McUchQt2j1CMqO35PVA:b6wmxro) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L56)):*
> ```
> int whence
> ```

Could we use `enum` for this? It's our own code, so we don't need to comply with the ugly POSIX conventions :)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 86 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUeXai3rYrhF-eCSFu:-McUeXai3rYrhF-eCSFv:b-98kusp) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L86)):*
> ```objc
>     /* Verify if a file with a given name exists. Should return 0 if file exists, negative value if
>      * not. */
>     int (*match_name)(struct shim_dentry* parent, const char* name);
> ```

I think `bool` retval + name change to something like `name_matches` would be more intuitive/readable. But let's maybe also ask @dimakuv/other reviewers for their prefs, I'm not blocking on this.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 104 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUhPHdC9p3LZePkD-Z:-McUhPHdC9p3LZePkD-_:b-k4hc31) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L104)):*
> ```objc
>         struct {
>             /*
>              * Read link target. Should allocate a new (null-terminated) string: it will be freed
> ```

Read -> Reads
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 117 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUhR3PDFu-tBA-VZCm:-McUhR3PDFu-tBA-VZCn:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L117)):*
> ```objc
>         struct {
>             /*
>              * Provide data for newly-opened file. Should allocate a new buffer: on file close, the
> ```

ditto
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 19 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McWkOd54WgBfm4uG5Qq:-McWkOd54WgBfm4uG5Qr:bh0awlt) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L19)):*
> ```C
> 
> /* Find a root node with given name. */
> static struct pseudo_node* pseudo_find_root(const char* name) {
> ```

Hmm, is it possible to mount pseudo FSes under a different directory than `/`? I'm asking mostly in the context of allowing mount syscall in the future for apps.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 33 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_nQWKCjuis9haFS57:-Mc_nQWKCjuis9haFS58:b-orlare) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L33)):*
> ```
>  in the `data` field.
> ```

Of `dent`? I see that this is explained below, but was a bit confusing at first to me.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 54 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_oCtLBiKkG_cEVTU-:-Mc_oCtLBiKkG_cEVTU0:bjj7mrt) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L54)):*
> ```C
>         return node;
> 
>     if (!dent->parent) {
> ```

Can we use this field without the lock? Ditto for all others below.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 72 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_oZzI6IKuvJHmldvC:-Mc_oZzI6IKuvJHmldvD:budmwdg) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L72)):*
> ```C
>     assert(parent_node->type == PSEUDO_DIR);
>     LISTP_FOR_EACH_ENTRY(node, &parent_node->dir.children, siblings) {
>         if (node->name && (strcmp(name, node->name) == 0)) {
> ```

Please remove the superfluous parens.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 96 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mca3cGk3lsjMQA8qDBC:-Mca3cGl1CIVGj8IxrO9:bbs5jil) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L96)):*
> ```C
> 
> /* The `modify` callback for string handle. Invokes `save` from user. */
> static int pseudo_modify(struct shim_handle* hdl) {
> ```

Seems to be a bit weird interface, its user is supposed to first set `hdl->info.str.data->str` manually and then call this function? Why isn't this function doing that?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 193 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mca55By-YN7S-dwU83d:-Mca55By-YN7S-dwU83e:b-7c8af0) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L193)):*
> ```C
>     dent->perm = node->perm;
>     return 0;
> };
> ```

Accidental semicolon? Ditto below.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 305 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mca8nhu-QXnSZngQEO5:-Mca8nhu-QXnSZngQEO6:bb8hz4s) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L305)):*
> ```
> void* buf, size_t count
> ```

I'd prefer to name this "size". "count" is used for array elements count, which doesn't make sense here (the pointer is `void`).
Same for other similar places.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 309 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mca8A84-7mvPcvUl2sH:-Mca8A84-7mvPcvUl2sI:b4w50wa) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L309)):*
> ```C
>     struct pseudo_node* node = pseudo_find(hdl->dentry);
>     if (!node)
>         return -ENOENT;
> ```

Is this possible without bugs in Graphene? [...]

2021-06-20 22:58 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 46 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/ipc/shim_ipc_ranges.c, line 851 at r2](https://reviewable.io/reviews/oscarlab/graphene/2453#-McKPKZE4kWF-d_23nGN:-Mcfcti6CccHIEzNRz0G:b-tt6slf) ([raw file](https://github.com/oscarlab/graphene/blob/074091da29e95df47fb3261f7dac525f9b346506/LibOS/shim/src/ipc/shim_ipc_ranges.c#L851)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

CC: @boryspoplawski
</blockquote></details>

I'm currently working on a PR which removes this file completely.
But you are right, that commit broke this function (I didn't want to put much attention to it, since I knew we will remove it soon).


<!-- Sent from Reviewable.io -->

2021-06-21 07:27 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 46 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 86 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUeXai3rYrhF-eCSFu:-MchNjq88dBtyOlzzkUW:bxxoyof) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think `bool` retval + name change to something like `name_matches` would be more intuitive/readable. But let's maybe also ask @dimakuv/other reviewers for their prefs, I'm not blocking on this.
</blockquote></details>

I'm also not blocking on this. Michal's suggested `name_matches` is good; I also like `verify_name_exists`. But this is a legacy name, and changing it would lead to changing all call-sites, so maybe it is for a follow-up PR.
___
*[LibOS/shim/src/fs/dev/attestation.c, line 41 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McaCq9u9qUIeUDQ_6Di:-MchOFAS-dsqgWN9f8eR:bipiu8y) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/dev/attestation.c#L41)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I missed this previously when merging the attestation PR, but what if multiple threads open the attestation device at the same time? Won't they race here?
</blockquote></details>

I implemented this. Please see the top-level comment in this file. TLDR: the app is responsible for locking.
___
*[LibOS/shim/test/regression/test_libos.py, line 678 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McdMBcSE28fAceXWyaA:-MchSaD5Ae0M97dFfYqa:b-ep04gq) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/test/regression/test_libos.py#L678)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv: Just to be sure, could you test this on an Icelake Xeon? (i.e. something with 2 sockets)
We have some problems with ours and can't do the tests at the moment.
</blockquote></details>

Done. Tested on Icelake with 2 sockets. It works.


<!-- Sent from Reviewable.io -->

2021-06-21 10:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 45 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/fs/dev/attestation.c, line 41 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McaCq9u9qUIeUDQ_6Di:-Mci9eKN27fJme7TOwKR:b-2vdli8) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/dev/attestation.c#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I implemented this. Please see the top-level comment in this file. TLDR: the app is responsible for locking.
</blockquote></details>

Oh, right, I forgot about this weird requirement :) Resolving then.


<!-- Sent from Reviewable.io -->

2021-06-21 12:07 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 45 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTv6nt-y_UhpAXUOp4:-MciBr_L8t6cdR7coEv-:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Fixes issues with /proc (#2385, #948).

Please change this to the GitHub auto-close syntax (in the PR description).
</blockquote></details>

Done.

---
___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-MciBsTg48_KIW6NshOL:b5s9k3v) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
I understood that this is not an established convention for out-parameters in our code. See an [earlier discussion](https://github.com/oscarlab/graphene/pull/2342#pullrequestreview-657539106):

>@mkow: Here you use pathp and sizep, but in dentry_abs_path you use path and size. Please unify.
>@dimakuv: +1. I prefer without these p suffixes.
>@pwmarcz: I did it this way because this function already uses path as size for actual values. I renamed them to _path and _size - if we already have a convention for such cases, I can change.

I have used that convention in all my code for some time now: normal names like `size` for out-parameters, underscored local variables (`_size`) in case of name collision.

I do not particularly like that and I would be fine with adopting `out_*` as a convention, but let's be clear that this is something we want _everywhere_ in Graphene?
___
*[common/src/string/atoi.c, line 78 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McU-3aFCn-ghkF3wqYr:-MciDf4L1aQRY071Aj2j:b-q64pkt) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/src/string/atoi.c#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You wouldn't need the underscore if the out arg was named `out_value` :)
</blockquote></details>

See above.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 7 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUFIHx5djUlYNzOdvg:-MciDqyyC6NthJmntgN6:bi5ypcf) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> pseudo-FS's
> ```

I think this should be "pseudo-FSes" or "pseudo-FS-es"
</blockquote></details>

OK, changed.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 56 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUchQt2j1CMqO35PV9:-MciDy5x1wHUS8LP60d-:b-p7qilk) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L56)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> int whence
> ```

Could we use `enum` for this? It's our own code, so we don't need to comply with the ugly POSIX conventions :)
</blockquote></details>

This is just a pass-through to the main definition in `shim_fs_ops`, so I'd rather not define a local enum just for `shim_fs_pseudo.h`.

Longer term, I'm not convinced `seek` for individual filesystems will stay at all. I think we might have a `pread` callback, and `seek` implemented in the main filesystem.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 86 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUeXai3rYrhF-eCSFu:-MciEzDnE4x0uTMO-Z5v:b-4rg8om) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm also not blocking on this. Michal's suggested `name_matches` is good; I also like `verify_name_exists`. But this is a legacy name, and changing it would lead to changing all call-sites, so maybe it is for a follow-up PR.
</blockquote></details>

If you prefer a bool, how about just `name_exists()`? So that it looks more like a predicate, not action.

We are changing all call-sites in this PR anyway so I can do it now.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 104 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUhPHdC9p3LZePkD-Z:-MciFUil6lDRzJMnnIXR:bm3yqt3) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Read -> Reads
</blockquote></details>

OK, done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 117 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUhR3PDFu-tBA-VZCm:-MciFXNNCnmuoEtHf1Rj:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 19 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McWkOd54WgBfm4uG5Qq:-MciB31YE-FzkkWTEz85:bt9c5gj) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, is it possible to mount pseudo FSes under a different directory than `/`? I'm asking mostly in the context of allowing mount syscall in the future for apps.
</blockquote></details>

Sure! You can mount a pseudo-filesystem `foo` under `/bar/baz`. The root name (`foo` here) is just a token for distinguishing pseudo-FSes.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 33 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_nQWKCjuis9haFS57:-MciFZxL6kfCIWQyeZmc:bqmjwcz) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  in the `data` field.
> ```

Of `dent`? I see that this is explained below, but was a bit confusing at first to me.
</blockquote></details>

Added.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 54 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_oCtLBiKkG_cEVTU-:-MciF_un2j_M7AMkIo_I:b49emvr) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can we use this field without the lock? Ditto for all others below.
</blockquote></details>

Yes. Parent, name and mount never change.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 72 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_oZzI6IKuvJHmldvC:-MciFrLuE4GlSFsyNlUD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L72)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please remove the superfluous parens.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 96 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mca3cGk3lsjMQA8qDBC:-MciFuKhBztrrHzEWTXG:b9dvu1f) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L96)):*
<details> [...]

2021-06-21 13:52 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: 25 of 37 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-McipjO80ZsuRr_vVRGN:bt618bd) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I understood that this is not an established convention for out-parameters in our code. See an [earlier discussion](https://github.com/oscarlab/graphene/pull/2342#pullrequestreview-657539106):

>@mkow: Here you use pathp and sizep, but in dentry_abs_path you use path and size. Please unify.
>@dimakuv: +1. I prefer without these p suffixes.
>@pwmarcz: I did it this way because this function already uses path as size for actual values. I renamed them to _path and _size - if we already have a convention for such cases, I can change.

I have used that convention in all my code for some time now: normal names like `size` for out-parameters, underscored local variables (`_size`) in case of name collision.

I do not particularly like that and I would be fine with adopting `out_*` as a convention, but let's be clear that this is something we want _everywhere_ in Graphene?
</blockquote></details>

Good point, we've never actually decided which way to go officially. I vote for using `out_` prefixes everywhere.
@dimakuv, @boryspoplawski: What's your opinion?


<!-- Sent from Reviewable.io -->

2021-06-21 14:07 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: 25 of 37 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-Mcit7CH5UXWe7DMEAlY:b-2m4ieg) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Good point, we've never actually decided which way to go officially. I vote for using `out_` prefixes everywhere.
@dimakuv, @boryspoplawski: What's your opinion?
</blockquote></details>

I would prefer suffixes (I've usually used `_ptr`, but `_out` seems ok too).


<!-- Sent from Reviewable.io -->

2021-06-21 14:29 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: 25 of 37 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-McixPjc4uzmv8c0j4rc:b-kg9xzv) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would prefer suffixes (I've usually used `_ptr`, but `_out` seems ok too).
</blockquote></details>

I don't care about it much (almost always you have to check the comments/implementation anyway). But if we definitely want this, then I prefer the `out_` prefix. The suffix is a bit annoying (e.g., examples like `stdout_out` and `i_want_out` are harder to parse than `out_stdout`/`out_i_want`).
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 86 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUeXai3rYrhF-eCSFu:-Mciy4MPDpU3AzaoF9Wv:b-i0lrx8) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L86)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If you prefer a bool, how about just `name_exists()`? So that it looks more like a predicate, not action.

We are changing all call-sites in this PR anyway so I can do it now.
</blockquote></details>

+1 for `name_exists`


<!-- Sent from Reviewable.io -->

2021-06-21 14:34 UTC, mkow requested changes
> Reviewed 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs_pseudo.h, line 56 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUchQt2j1CMqO35PV9:-MciqIxO-XJLn2QdEYTY:b7pn4kv) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L56)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is just a pass-through to the main definition in `shim_fs_ops`, so I'd rather not define a local enum just for `shim_fs_pseudo.h`.

Longer term, I'm not convinced `seek` for individual filesystems will stay at all. I think we might have a `pread` callback, and `seek` implemented in the main filesystem.
</blockquote></details>

Sounds good, although it may be tricky with more magic FSes like devfs.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 86 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUeXai3rYrhF-eCSFu:-Mciqwx7CByG5wX2iGoj:b-o7smvt) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L86)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If you prefer a bool, how about just `name_exists()`? So that it looks more like a predicate, not action.

We are changing all call-sites in this PR anyway so I can do it now.
</blockquote></details>

Sounds even better than my proposal :)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 152 at r8](https://reviewable.io/reviews/oscarlab/graphene/2453#-McisATp5M3Twibs6fJp:-McisATq0Wf-Vvh7DRNW:b-tzye2s) ([raw file](https://github.com/oscarlab/graphene/blob/d8f503145a35d1cdcf749811057ad4320baaf317/LibOS/shim/include/shim_fs_pseudo.h#L152)):*
> ```
> match_name
> ```

Please remember to update this place when renaming that function.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 19 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McWkOd54WgBfm4uG5Qq:-McisHp873eKk_I8E3Ox:b9cdcq9) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L19)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Sure! You can mount a pseudo-filesystem `foo` under `/bar/baz`. The root name (`foo` here) is just a token for distinguishing pseudo-FSes.
</blockquote></details>

Ah, now I understand how it works :)
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 54 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_oCtLBiKkG_cEVTU-:-McisS_CD0eoedEvQ1Da:bawwmfy) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L54)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes. Parent, name and mount never change.
</blockquote></details>

Could we document this somewhere? (in the `struct shim_dentry` definition I guess?) It's definitely not obvious to me, assuming I didn't miss any docs on this.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 96 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mca3cGk3lsjMQA8qDBC:-Mcisp1gBWMc2m8RI5zx:b2nhysk) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L96)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is a "modify" callback that the "string filesystem" invokes on saving a file. Nobody modifies `hdl->info.str.data->str`, it happens when the application writes to a file.

I agree that the "string filesystem" is somewhat poorly designed, but I'm not modifying it here, just providing a bit of glue so that the pseudofs can expose a nice `save()` interface.
</blockquote></details>

ack
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 477 at r8](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mciu7b69e_y4h9Z3Bxp:-Mciu7b7-hfz5LLbBcV9:b-sf9zc5) ([raw file](https://github.com/oscarlab/graphene/blob/d8f503145a35d1cdcf749811057ad4320baaf317/LibOS/shim/src/fs/shim_fs_pseudo.c#L477)):*
> ```C
> 
>     /* no leading zeroes */
>     if (_value > 0 && str[0] == '0')
> ```

Try again! :)

```
/ # ls -la /proc/self/fd/00000
lrwxrwxrwx    1 root     root             0 Jan  1  1970 /proc/self/fd/00000 -> /dev/tty
```
___
*[LibOS/shim/src/fs/dev/fs.c, line 38 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McaVoUE4Kth9w9l4dek:-MciukpmCzJuYLtAKR0Z:b-t5p25v) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/dev/fs.c#L38)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Unfortunately that breaks `open()` with `O_TRUNC`, which should succeed :( Looks like we don't allow distinguishing between these two cases. I added a TODO for now.
</blockquote></details>

Oops :/
___
*[LibOS/shim/src/fs/proc/fs.c, line 38 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McabwpXAwZmVZj07BF4:-Mciurab23D0vp5xDHC4:b-jj57ll) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/proc/fs.c#L38)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is some (very basic) support for information about other processes, acquired throught IPC. I added a comment here.
</blockquote></details>

Aah. Much better with the comment :)
___
*[LibOS/shim/src/fs/proc/thread.c, line 298 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McatEeR0Ahik9rRAi8L:-Mcivn032aLHPC4CKy-Y:b-ndd6tx) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/proc/thread.c#L298)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Right. Changed to `-ENOENT`.
</blockquote></details>

What about other places? E.g. line 236. Please grep the whole PR for this.


<!-- Sent from Reviewable.io -->

2021-06-21 14:41 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-Mcj-jvP1qxSQDHCwntk:b-jswez6) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
I agree that this is implementation specific anyway, so there is not much readability gain, outside of review of the new code.

> The suffix is a bit annoying (e.g., examples like stdout_out and i_want_out are harder to parse than out_stdout/out_i_want).

For me it's exactly the opposite :)


<!-- Sent from Reviewable.io -->

2021-06-21 16:12 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: 23 of 37 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-McjGJZc0iW7Lm9VQiYl:b-zp9mu) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I agree that this is implementation specific anyway, so there is not much readability gain, outside of review of the new code.

> The suffix is a bit annoying (e.g., examples like stdout_out and i_want_out are harder to parse than out_stdout/out_i_want).

For me it's exactly the opposite :)
</blockquote></details>

I prefer `out_` prefix as well, and there is some precedent for it in Graphene. (Unfortunately I couldn't find any style guide that recommends such a convention...)

I changed this PR to use `out_*`. It's good to get rid of hacky declarations like `size_t _size`, it makes the functions more readable.
___
*[common/src/string/atoi.c, line 78 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McU-3aFCn-ghkF3wqYr:-McjGqWf21sTRdIQJhom:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/src/string/atoi.c#L78)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 86 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McUeXai3rYrhF-eCSFu:-McjCLzg1qbDoMoW9RkH:bol9u7f) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/include/shim_fs_pseudo.h#L86)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Sounds even better than my proposal :)
</blockquote></details>

Done, changed to `bool name_exists()`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 152 at r8](https://reviewable.io/reviews/oscarlab/graphene/2453#-McisATp5M3Twibs6fJp:-McjCL9h2TbugjG3uAQd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d8f503145a35d1cdcf749811057ad4320baaf317/LibOS/shim/include/shim_fs_pseudo.h#L152)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> match_name
> ```

Please remember to update this place when renaming that function.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 54 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mc_oCtLBiKkG_cEVTU-:-Mcj8-Yk2dP_Ox_V-BKT:b-qq1efn) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/shim_fs_pseudo.c#L54)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we document this somewhere? (in the `struct shim_dentry` definition I guess?) It's definitely not obvious to me, assuming I didn't miss any docs on this.
</blockquote></details>

I documented which fields do not change, and that the `data` field is protected by `lock`.

I would like to document more (how are all the fields accessed, the dentry lifecycle) but I think LibOS does not follow any sane rules yet, so I'll wait with such comments until they're more truthful :)
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 477 at r8](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mciu7b69e_y4h9Z3Bxp:-Mcj8oOxER5rRayNf0AE:bouwa75) ([raw file](https://github.com/oscarlab/graphene/blob/d8f503145a35d1cdcf749811057ad4320baaf317/LibOS/shim/src/fs/shim_fs_pseudo.c#L477)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Try again! :)

```
/ # ls -la /proc/self/fd/00000
lrwxrwxrwx    1 root     root             0 Jan  1  1970 /proc/self/fd/00000 -> /dev/tty
```
</blockquote></details>

Oh well. How about now? :)
___
*[LibOS/shim/src/fs/proc/thread.c, line 298 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McatEeR0Ahik9rRAi8L:-McjA4P02w6XCUWuCbD1:b-n08r7d) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/LibOS/shim/src/fs/proc/thread.c#L298)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about other places? E.g. line 236. Please grep the whole PR for this.
</blockquote></details>

Fixed line 236, and on a closer look I also changed the size check in `pfkey_save` to return `-EACCES`, same as we do for errors from `DkSetProtectedFilesKey()` (which presumably also include wrong key format).

I see no other suspicious `-EINVAL`s in the diff (and `git grep -A1 pseudo_parse` confirms the cases with parsing pseudo-fs names).


<!-- Sent from Reviewable.io -->

2021-06-21 16:21 UTC, mkow approved these changes
> Reviewed 14 of 14 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 477 at r8](https://reviewable.io/reviews/oscarlab/graphene/2453#-Mciu7b69e_y4h9Z3Bxp:-McjM1KB930-0tzkQPR0:bijjgan) ([raw file](https://github.com/oscarlab/graphene/blob/d8f503145a35d1cdcf749811057ad4320baaf317/LibOS/shim/src/fs/shim_fs_pseudo.c#L477)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Oh well. How about now? :)
</blockquote></details>

Now it's correct :)


<!-- Sent from Reviewable.io -->

2021-06-21 16:42 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-McjRQnH3Fk0wmkNglTv:b-jlccei) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
> and there is some precedent for it in Graphene.

Quick grep shows `_ptr` is more common in Graphene function params :)

@mkow what's your stand on prefix vs suffix? For now it seems it's 2:1 for prefix.


<!-- Sent from Reviewable.io -->

2021-06-21 17:02 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-McjW8r-2OF_8qw73BC0:b-vr4sso) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
> Quick grep shows `_ptr` is more common in Graphene function params :)

But being a pointer doesn't imply being a return value, it might have been just a struct which is too big to pass by copy.

> @mkow what's your stand on prefix vs suffix? For now it seems it's 2:1 for prefix.

I slightly prefer prefix, but hard to explain why, just reads more naturally and less-confusing for me.


<!-- Sent from Reviewable.io -->

2021-06-21 17:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[common/include/api.h, line 181 at r7](https://reviewable.io/reviews/oscarlab/graphene/2453#-McTwDsS1wyRAE9jWooF:-Mcjb0GS5tFmLkNZehXM:b-mki5n4) ([raw file](https://github.com/oscarlab/graphene/blob/776fef1112296493b31bcd7c3657af1e4429d099/common/include/api.h#L181)):*
> But being a pointer doesn't imply being a return value, it might have been just a struct which is too big to pass by copy.

1) `_ptr` was just an example (I'm not saying it's the best sufix we can come up with)
2) it's not like we add `_ptr` because the type of that variable has `*`. It just used in case of conflicts with a local variable and then such out parameter usually is a double pointer (`**`).

> I slightly prefer prefix, but hard to explain why, just reads more naturally and less-confusing for me.

Which makes it 3:1 so case closed, I guess.


<!-- Sent from Reviewable.io -->

2021-06-22 14:25 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-06-28 06:18 UTC, dimakuv approved these changes
> Reviewed 4 of 12 files at r8, 13 of 14 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2453)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-28 06:20 UTC, merged