[Docs] Ensure that insecure options are clearly marked as such
oscarlab/graphene pull request #2454
Opened 2021-06-16 23:32 UTC by mkow

## Description of the changes

I'm still not sure about one option: `sgx.debug`. Is it actually possible to set it to `true` and accidentally ship such an enclave? This will be visible in the attestation, but maybe that's not enough?

In the future it would be good to have some kind of warning banner at the start of Graphene if it's insecure, which would be enabled in all debug builds, when using insecure/non-prod manifest settings, etc.

ps. I squashed in a few formatting fixes, reST was broken in a few places.

2021-06-17 00:26 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2454)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2454#-McMLIz715L71qlAO9eY:-McMLIz715L71qlAO9eZ:baa3yv4) (no related file):*
> I'm still not sure about one option: sgx.debug. Is it actually possible to set it to true and accidentally ship such an enclave? This will be visible in the attestation, but maybe that's not enough?

It is possible. But I don't see a problem -- it is reflected during remote attestation, and a good verification library will throw some huge warning or something like this.

---
___
*[Documentation/manifest-syntax.rst, line 477 at r1](https://reviewable.io/reviews/oscarlab/graphene/2454#-McMKwl87p1Q_TT-x-3y:-McMKwl96oCzHu8VrO-k:b2c5zgw) ([raw file](https://github.com/oscarlab/graphene/blob/7e2b9e1bd7da95b21fca2ef709581fed0545a4b9/Documentation/manifest-syntax.rst#L477)):*
> ```reStructuredText
>     sgx.trusted_files.[identifier] = "[URI]"
> 
> This syntax specifies the files to be cryptographically hashed build-time, and
> ```

`at build time`?


<!-- Sent from Reviewable.io -->

2021-06-17 00:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2454)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Documentation/manifest-syntax.rst, line 477 at r1](https://reviewable.io/reviews/oscarlab/graphene/2454#-McMKwl87p1Q_TT-x-3y:-McMPuJw8fejxZuQi6iU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/7e2b9e1bd7da95b21fca2ef709581fed0545a4b9/Documentation/manifest-syntax.rst#L477)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`at build time`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-23 17:00 UTC, boryspoplawski approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2454)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-06-28 06:28 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2454)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-28 07:17 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2454)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-28 07:44 UTC, merged