Add java sample to graphene examples
oscarlab/graphene pull request #2465
Opened 2021-06-21 09:06 UTC by jkr0103

Signed-off-by: jkr0103 <jitender.kumar@intel.com>

## Description of the changes 

This PR adds java sample to graphene Examples.

## How to test this PR? 
Successful execution of java sample is sufficient to test the PR. Follow instructions in README.txt for execution steps of java sample.

2021-06-21 11:34 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 0 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciK6RBBHNBuGXo6ZSY:-MciK6RBBHNBuGXo6ZSZ:b6jmxtx) (no related file):*
Please read https://graphene.readthedocs.io/en/latest/devel/contributing.html and clean up the whole PR. Sorry for not being nice, but this whole PR is a mess :/

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKeAI6Ttxnbs_rEBG:-MciKeAJB6jmJHHoe5Oq:b-mrq5j1) (no related file):*
Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can push-force if you choose the former.

---
___
*[Examples/java_sample/hello.jar, line 0 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKucB84BWgzgxuLzU:-MciKucB84BWgzgxuLzV:b92cx6c) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.jar#L0)):*
What's the point in committing both sources and binaries to the repo?
___
*[Examples/java_sample/hello.java, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKt_oEUosSKBGp9vX:-MciKt_p4tQOKl2YNp1q:b3kre) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.java#L1)):*
> ```Java
> // Your First Program
> ```

?
___
*[Examples/java_sample/hello.mf, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciLDE165e0dPVxTN_e:-MciLDE165e0dPVxTN_f:bj401e4) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.mf#L1)):*
> ```
> Main-Class: hello
> ```

what's this file?
___
*[Examples/java_sample/java.manifest.template, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciLAa-68k5_aTYOdfO:-MciLAa-68k5_aTYOdfP:b3kre) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/java.manifest.template#L69)):*
> ```
> # thread for asynchronous events. Therefore, the actual number of threads that
> # the application can create is (sgx.thread_num - 2).
> sgx.thread_num = 1024
> ```

?


<!-- Sent from Reviewable.io -->

2021-06-22 03:54 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 0 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciK6RBBHNBuGXo6ZSY:-MclqDWsDkRWitn1mKf7:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please read https://graphene.readthedocs.io/en/latest/devel/contributing.html and clean up the whole PR. Sorry for not being nice, but this whole PR is a mess :/
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKeAI6Ttxnbs_rEBG:-MclqHZfEIHfkL95UL0R:bgx1ebv) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can push-force if you choose the former.
</blockquote></details>

I have added jitender.kumar@intel.com email address to GitHub account.

---
___
*[Examples/java_sample/hello.java, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKt_oEUosSKBGp9vX:-MclpewiEWjy_hALpMrU:ba5xqcm) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.java#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

updated the comment
___
*[Examples/java_sample/hello.mf, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciLDE165e0dPVxTN_e:-McliNIxCWQ6Y_reJOpZ:bu6hjec) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.mf#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

what's this file?
</blockquote></details>

This file is required to build the binary hello.jar
___
*[Examples/java_sample/java.manifest.template, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciLAa-68k5_aTYOdfO:-McliSk4EBPpTuNknSyg:bj6zezc) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/java.manifest.template#L69)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

1024 thread numbers was the minimum requirement for specjbb but as we are not adding specjbb now, I checked this example with lesser thread sizes that works even with 32 thread, hence updated the same in manifest file.
___
*[Examples/java_sample/hello.jar, line  at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKucB84BWgzgxuLzU:-MclhfdpEhHC51R0LwZB:b-p1vjvk) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.jar#L)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point in committing both sources and binaries to the repo?
</blockquote></details>

agree, will remove binary file hello.jar and add instructions in README.txt to build the binary.


<!-- Sent from Reviewable.io -->

2021-06-28 06:58 UTC, dimakuv requested changes
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKeAI6Ttxnbs_rEBG:-MdGLTVVBBpCSFNHzt8U:b-ihagz3) (no related file):*
> Signed-off-by: jkr0103 <jitender.kumar@intel.com>

Could you also change the name from `jkr0103` to your full name?

> Signed-off-by: jkr0103 <jkr0103@gmail.com>

Some of your commits still have `gmail.com` email address.

---
___
*[Examples/java_sample/java.manifest.template, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciLAa-68k5_aTYOdfO:-MdGMPwV4VGy8Jp3n1rt:bvogqcr) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/java.manifest.template#L69)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

1024 thread numbers was the minimum requirement for specjbb but as we are not adding specjbb now, I checked this example with lesser thread sizes that works even with 32 thread, hence updated the same in manifest file.
</blockquote></details>

But why not e.g. 4 threads? You only run a HelloWorld kind of application.
___
*[Examples/java_sample/java.manifest.template, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLgQu8gpu4-ulB2pg:-MdGLgQu8gpu4-ulB2ph:bgumg22) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L17)):*
> ```
> 
> # Environment variables for java
> loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/lib:/usr/{{ arch_libdir }}:/usr/lib/jvm/java-11-openjdk-amd64/lib/jli:/usr/lib/jvm/java-11-openjdk-amd64/lib:/usr/lib/jvm/java-11-openjdk-amd64/lib/server:/usr/lib/jvm/java-11-openjdk-amd64/conf"
> ```

Do we really need all these paths in `LD_LIBRARY_PATH`? For example, the last path (`conf`) definitely doesn't look like it contains shared libraries.
___
*[Examples/java_sample/java.manifest.template, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLpYVEORGWncAM3_p:-MdGLpYW5CQDz1Bqjfu3:b-4174j7) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L20)):*
> ```
> 
> # Allow for injecting SIGTERM signal from the host.
> sys.enable_sigterm_injection = true
> ```

This option looks not needed. Please remove and test that your Java example still works. 
___
*[Examples/java_sample/java.manifest.template, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLxzo7av0WhYtU-Sl:-MdGLxzo7av0WhYtU-Sm:b-9osqn6) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L39)):*
> ```
> fs.mount.lib3.uri = "file:/usr/{{ arch_libdir }}"
> 
> # Host-level directory (/usr) required by the Python executable
> ```

Python?
___
*[Examples/java_sample/java.manifest.template, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLzWm9wm3KHcLg8tt:-MdGLzWm9wm3KHcLg8tu:b-s4w6wt) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L47)):*
> ```
> fs.mount.tmp.type = "chroot"
> fs.mount.tmp.path = "/tmp"
> fs.mount.tmp.uri = "file:/tmp"
> ```

Do you really need `/tmp` directory? Why?
___
*[Examples/java_sample/java.manifest.template, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGM1im1-CnIiQ1G_F7:-MdGM1im1-CnIiQ1G_F8:b-n7ew9m) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L52)):*
> ```
> fs.mount.etc.type = "chroot"
> fs.mount.etc.path = "/etc"
> fs.mount.etc.uri = "file:/etc"
> ```

Do you really need `/etc` directory? Why?
___
*[Examples/java_sample/java.manifest.template, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGM4II0PnKYf9jd2wg:-MdGM4II0PnKYf9jd2wh:b-9osqn6) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L57)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave
> # size must be specified during signing. If Python needs more virtual memory
> ```

Python?
___
*[Examples/java_sample/java.manifest.template, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGPAzgEfoN4imAx1S-:-MdGPAzgEfoN4imAx1S0:bqgta28) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L59)):*
> ```
> # size must be specified during signing. If Python needs more virtual memory
> # than the enclave size, Graphene will not be able to allocate it.
> sgx.enclave_size = "64G"
> ```

Instead of the generic comment `Set the virtual ...`, please add the comment that you have in the README file.
___
*[Examples/java_sample/java.manifest.template, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGM5rO2xbDzNa-v6er:-MdGM5rO2xbDzNa-v6es:bhscx7h) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L60)):*
> ```
> # than the enclave size, Graphene will not be able to allocate it.
> sgx.enclave_size = "64G"
> sgx.static_address = 1
> ```

This option doesn't exist in Graphene anymore, please remove.
___
*[Examples/java_sample/java.manifest.template, line 61 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGMBV0EqWGtc78_WL2:-MdGMBV0EqWGtc78_WL3:bv8jvor) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L61)):*
> ```
> sgx.enclave_size = "64G"
> sgx.static_address = 1
> libos.check_invalid_pointers = false
> ```

Why do you have this option? For performance? What happens if we remove this option?
___
*[Examples/java_sample/java.manifest.template, line 72 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGMY2801R3Vv7JxRfH:-MdGMY2801R3Vv7JxRfI:b-b29ivd) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L72)):*
> ```
> 
> sgx.nonpie_binary = true
> sgx.allow_file_creation=true
> ```

This option doesn't exist anymore, please delete this line
___
*[Examples/java_sample/java.manifest.template, line 81 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGMfDI9qim508NHl7N:-MdGMfDI9qim508NHl7O:bhke665) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L81)):*
> ```
> sgx.trusted_files.libtcmalloc = "file:/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4"
> sgx.trusted_files.libunwind = "file:/usr/lib/x86_64-linux-gnu/libunwind.so.8"
> sgx.trusted_files.liblzma = "file:/lib/x86_64-linux-gnu/liblzma.so.5"
> ```

What are these three libraries? Aren't they already "subsumed" by the above line `sgx.trusted_files.usr_arch_libdir = "file:/usr/{{ arch_libdir }}/"`?
___
*[Examples/java_sample/java.manifest.template, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGN7Yk86FyycX_0ILS:-MdGN7Yk86FyycX_0ILT:briff8r) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L85)):*
> ```
> # Other libraries
> sgx.trusted_files.libjli = "file:/usr/lib/jvm/java-11-openjdk-amd64/lib/jli/libjli.so"
> sgx.trusted_files.libz = "file:/lib/x86_64-linux-gnu/libz.so.1"
> ```

 Isn't this one alre [...]

2021-06-29 06:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 1 of 7 files reviewed, 43 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @jkr0103, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLT1_yAP1RD4Mz_ZIl:-MdLT1_zE0DFX460lvo7:b-61us3p) (no related file):*
When I build this example, git detects the generated files and wants to add them to Graphene codebase:
```
~/more-graphene/Examples/java_sample$ git status
On branch java_example
Your branch is up to date with 'jkr0103/java_example'.

Untracked files:
        hello.class
        hello.jar
```

Please add a `.gitignore` file here with the following contents:
```
 /hello.class
 /hello.jar
```

This will force git to ignore the auto-generated files in this example.

For an example, see https://github.com/oscarlab/graphene/blob/master/Examples/bash/.gitignore

---
___
*[Examples/java_sample/java.manifest.template, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLU_Th4bJJZAYUoh06:-MdLU_Ti3PUrfF-PhF7v:bktmijl) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L59)):*
> ```
> # size must be specified during signing. If Python needs more virtual memory
> # than the enclave size, Graphene will not be able to allocate it.
> sgx.enclave_size = "64G"
> ```

I tried this default version with 64GB of enclave size, and it took ages on my 128MB machine.
___
*[Examples/java_sample/Makefile, line 48 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLTdJc4fns719DMlsB:-MdLTdJc4fns719DMlsC:bbuz702) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/Makefile#L48)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) *.token *.sig *.manifest.sgx *.manifest *.rdb
> ```

Please add here `*.class *.jar` to delete the auto-generated files
___
*[Examples/java_sample/README.txt, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLRocf9sgFBT7c-yME:-MdLRocf9sgFBT7c-yMF:b-nenefp) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/README.txt#L15)):*
> ```help
> following command to install the required packages (Ubuntu-specific):
> 
>     `sudo apt-get install openjdk-11-jdk`
> ```

I also needed to install `tcmalloc` (part of Google's perftools) on my system:
```
sudo apt-get install google-perftools
```


<!-- Sent from Reviewable.io -->

2021-06-29 06:49 UTC, dimakuv requested changes
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 2 of 7 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @jkr0103, and @mkow)

___
*[Examples/java/java.manifest.template, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLWQC9652pNlYUYNyJ:-MdLWQCBCgxLTyx_0SOW:bbuo6cp) ([raw file](https://github.com/oscarlab/graphene/blob/03ba7c8cdbc7531870f019c0f82224862fe6bed2/Examples/java/java.manifest.template#L41)):*
> ```
> # By default this example uses 64G enclave size. This example also works with 8G enclave
> # size also but in that case Max Heap size should be restricted to 4G using jvm flag -Xmx4G.
> sgx.enclave_size = "64G"
> ```

Actually can we revert it? I tried this example with the default 64GB on my small SGX machine, and it took ages.

Changing to `8G` here and running with `graphene-sgx java -Xmx4G -jar hello.jar` was much faster.

Let's change to this default (8GB and `-Xmx4G` in the README). And note that one can set 64GB enclave size and one can then remove `-Xmx` option.


<!-- Sent from Reviewable.io -->

2021-06-29 08:04 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 1 of 8 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKeAI6Ttxnbs_rEBG:-MdLkByf2Pm4bMDN9X7O:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Signed-off-by: jkr0103 <jitender.kumar@intel.com>

Could you also change the name from `jkr0103` to your full name?

> Signed-off-by: jkr0103 <jkr0103@gmail.com>

Some of your commits still have `gmail.com` email address.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLT1_yAP1RD4Mz_ZIl:-MdLkDWS4wULQJbMkUrx:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When I build this example, git detects the generated files and wants to add them to Graphene codebase:
```
~/more-graphene/Examples/java_sample$ git status
On branch java_example
Your branch is up to date with 'jkr0103/java_example'.

Untracked files:
        hello.class
        hello.jar
```

Please add a `.gitignore` file here with the following contents:
```
 /hello.class
 /hello.jar
```

This will force git to ignore the auto-generated files in this example.

For an example, see https://github.com/oscarlab/graphene/blob/master/Examples/bash/.gitignore
</blockquote></details>

Done.

---
___
*[Examples/java/java.manifest.template, line 41 at r3](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLWQC9652pNlYUYNyJ:-MdLkJby88nnQO53Mc3H:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/03ba7c8cdbc7531870f019c0f82224862fe6bed2/Examples/java/java.manifest.template#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually can we revert it? I tried this example with the default 64GB on my small SGX machine, and it took ages.

Changing to `8G` here and running with `graphene-sgx java -Xmx4G -jar hello.jar` was much faster.

Let's change to this default (8GB and `-Xmx4G` in the README). And note that one can set 64GB enclave size and one can then remove `-Xmx` option.
</blockquote></details>

Done.
___
*[Examples/java_sample/hello.jar, line  at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKucB84BWgzgxuLzU:-MdLmYUw6DXNcjyJwLpX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.jar#L)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

agree, will remove binary file hello.jar and add instructions in README.txt to build the binary.
</blockquote></details>

Done.
___
*[Examples/java_sample/java.manifest.template, line 69 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciLAa-68k5_aTYOdfO:-MclqsdsAlOOtT7LD0lA:bn975tz) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/java.manifest.template#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why not e.g. 4 threads? You only run a HelloWorld kind of application.
</blockquote></details>

As discussed graphene-sgx complains with error `error: There are no available TCS pages left for a new thread!` for threads lesser than 32.
___
*[Examples/java_sample/java.manifest.template, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLgQu8gpu4-ulB2pg:-MdLl2SM76JCmKUE9uU8:b7x7nkf) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do we really need all these paths in `LD_LIBRARY_PATH`? For example, the last path (`conf`) definitely doesn't look like it contains shared libraries.
</blockquote></details>

removed unnecessary paths.
___
*[Examples/java_sample/java.manifest.template, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLpYVEORGWncAM3_p:-MdLl8Ot-qh5STq60BHC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This option looks not needed. Please remove and test that your Java example still works. 
</blockquote></details>

Done.
___
*[Examples/java_sample/java.manifest.template, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLxzo7av0WhYtU-Sl:-MdLl95ADuKTOpR8kl3f:b-7ql1td) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Python?
</blockquote></details>

fixed
___
*[Examples/java_sample/java.manifest.template, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGLzWm9wm3KHcLg8tt:-MdLlAFg4cNC-zDtHZAJ:brpmqc3) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you really need `/tmp` directory? Why?
</blockquote></details>

removed.
___
*[Examples/java_sample/java.manifest.template, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGM1im1-CnIiQ1G_F7:-MdLlBYR3jUiWpQYQRip:brpmqc3) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you really need `/etc` directory? Why?
</blockquote></details>

removed.
___
*[Examples/java_sample/java.manifest.template, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGM4II0PnKYf9jd2wg:-MdLlCqvDwQ5mNfgcd4T:boac9bm) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Python?
</blockquote></details>

updated.
___
*[Examples/java_sample/java.manifest.template, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGPAzgEfoN4imAx1S-:-MdLlYDi9D73DxDA-fVL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of the generic comment `Set the virtual ...`, please add the comment that you have in the README file.
</blockquote></details>

Done.
___
*[Examples/java_sample/java.manifest.template, line 59 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLU_Th4bJJZAYUoh06:-MdLldAX1ANbJzVYz8x2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f5b84b9b0082b55/Examples/java_sample/java.manifest.template#L59)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tried this default version with 64GB of enclave size, and it took ages on my 128MB machine.
</blockquote></details>

Done.
___
*[Examples/java_sample/java.manifest.template, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdGM5rO2xbDzNa-v6er:-MdLlGXA83xVTpdhcQgM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5729a9f9a8f3d4e7033fbab86f [...]

2021-06-29 09:45 UTC, dimakuv requested changes
> Reviewed 3 of 6 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[Examples/java/java.manifest.template, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdM8uOAD4tdAsfF16bP:-MdM8uOAD4tdAsfF16bQ:b6cbss0) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/java.manifest.template#L17)):*
> ```
> 
> # Environment variables for Java
> loader.env.LD_LIBRARY_PATH = "{{ arch_libdir }}"
> ```

This wasn't enough for me. I ended up adding this:
```
loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/lib:/usr/{{ arch_libdir }}"
```

Please update.
___
*[Examples/java/README.md, line 16 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoCjE9iXK1mzi0AFP:-MdLoCjE9iXK1mzi0AFQ:bp0v3jv) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L16)):*
> ```Markdown
> 
>     `sudo apt-get install openjdk-11-jdk`
>     `sudo apt-get install google-perftools`
> ```

This doesn't render well: https://github.com/jkr0103/graphene/tree/java_example/Examples/java

This is because you're using both indentations and backticks. Please remove backticks in this case.
___
*[Examples/java/README.md, line 20 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoXRm-8jcn3f-vUiE:-MdLoXRm-8jcn3f-vUiF:b-z4ox0m) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L20)):*
> ```Markdown
> ## Building for Linux
> 
>     Run `make` (non-debug) or `make DEBUG=1` (debug) in the directory.
> ```

This doesn't render well. Please remove indentation.
___
*[Examples/java/README.md, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLo_3K6_iRhBIiTeYd:-MdLo_3K6_iRhBIiTeYe:b-z4ox0m) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L24)):*
> ```Markdown
> ## Building for SGX
> 
>     Run `make SGX=1` (non-debug) or `make SGX=1 DEBUG=1` (debug) in the directory.
> ```

This doesn't render well. Please remove indentation.
___
*[Examples/java/README.md, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdM6rk41aVkUgdxAPS3:-MdM6rk5843ZZb6gZKPh:bdq7gs0) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L26)):*
> ```Markdown
>     Run `make SGX=1` (non-debug) or `make SGX=1 DEBUG=1` (debug) in the directory.
> 
> ## Building hello.jar
> ```

Please move this section before `Building for Linux`. This is because when I tried to do the steps as in this README, `Building for SGX` failed with not-found `hello.jar` file. So we should reorder the steps here to first build `hello.jar`.
___
*[Examples/java/README.md, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoaRi1YPK2CgDjU9t:-MdLoaRi1YPK2CgDjU9u:b-8kjtyq) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L29)):*
> ```Markdown
> 
>     Run `javac hello.java`
>     Run `jar cvfm hello.jar hello.mf hello.class`
> ```

These two lines don't render well. Please remove indentation.
___
*[Examples/java/README.md, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoeny2vyiRh-KbkpB:-MdLoeny2vyiRh-KbkpC:b778t6c) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L35)):*
> ```Markdown
> Without SGX:
> 
>     `graphene-direct java -jar hello.jar`
> ```

This doesn't render well. Please remove backticks.
___
*[Examples/java/README.md, line 39 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLofvE12ZsFx26FLlz:-MdLofvE12ZsFx26FLm-:b778t6c) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L39)):*
> ```Markdown
> With SGX:
> 
>     `graphene-sgx java -Xmx4G -jar hello.jar`
> ```

This doesn't render well. Please remove backticks.


<!-- Sent from Reviewable.io -->

2021-06-29 10:59 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 6 of 8 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Examples/java/java.manifest.template, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdM8uOAD4tdAsfF16bP:-MdMPycXALc76cF0uOed:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/java.manifest.template#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This wasn't enough for me. I ended up adding this:
```
loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/lib:/usr/{{ arch_libdir }}"
```

Please update.
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 16 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoCjE9iXK1mzi0AFP:-MdMPiDp2N-mcoSEYqJC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't render well: https://github.com/jkr0103/graphene/tree/java_example/Examples/java

This is because you're using both indentations and backticks. Please remove backticks in this case.
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 20 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoXRm-8jcn3f-vUiE:-MdMPj5y8FsD0943TW4l:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't render well. Please remove indentation.
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 24 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLo_3K6_iRhBIiTeYd:-MdMPjkMDETK0mjNN1cW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't render well. Please remove indentation.
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdM6rk41aVkUgdxAPS3:-MdMPkNA5HDnIx0-aJua:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this section before `Building for Linux`. This is because when I tried to do the steps as in this README, `Building for SGX` failed with not-found `hello.jar` file. So we should reorder the steps here to first build `hello.jar`.
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 29 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoaRi1YPK2CgDjU9t:-MdMPkxw8a6E0TsvOlq-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

These two lines don't render well. Please remove indentation.
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 35 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoeny2vyiRh-KbkpB:-MdMPleX2AfOtP9UfPfk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't render well. Please remove backticks.
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 39 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLofvE12ZsFx26FLlz:-MdMPmCh4Ntl7niRkFt8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't render well. Please remove backticks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-29 11:08 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[Examples/java/README.md, line 20 at r4](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdLoXRm-8jcn3f-vUiE:-MdMRxyH5WZudA59H9dQ:b-h115hx) ([raw file](https://github.com/oscarlab/graphene/blob/f90dbbc4c179cbe2ea4c3f24fc8412b90b44a4e2/Examples/java/README.md#L20)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This still doesn't render well: https://github.com/jkr0103/graphene/tree/java_example/Examples/java.

I suggest to change like this:
```
Run the following commands:
    javac hello.java
    jar cvfm hello.jar hello.mf hello.class
```


<!-- Sent from Reviewable.io -->

2021-06-29 11:16 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-06-29 12:25 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MdMirez15gw6qh65975:-MdMirf-EYdbkAXF4vgZ:bje35gh) (no related file):*
FYI: I tested the latest version of this PR, it works.

---


<!-- Sent from Reviewable.io -->

2021-06-29 12:26 UTC, dimakuv commented
Jenkins, test this please

2021-08-10 03:50 UTC, aneessahib commented
Any more changes needed here?

2021-08-10 06:35 UTC, jkr0103 commented
> Any more changes needed here?

no

2021-08-10 06:43 UTC, dimakuv requested changes
Actually, changes are needed again. We cleaned up all Examples recently, so this one needs to be updated as well.

And yeah, we need to wait for Michal to find time to review this one again...

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465#-:-MgilOpiDQsrF5HmkQIp:bkd8nly)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[Examples/java/java.manifest.template, line 3 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgilbBH0fsvjLchBLJX:-MgilbBH0fsvjLchBLJY:bs4vjlh) ([raw file](https://github.com/oscarlab/graphene/blob/05f5699b1c921719833af998f127eb1b079c585b/Examples/java/java.manifest.template#L3)):*
> ```
> # Java manifest example
> #
> # This manifest was prepared and tested on Ubuntu 18.04 and tested with openjdk11
> ```

Recently, we decided to remove all irrelevant comments in manifest files (see any example in our Examples/, except Redis). Please remove all comments here, except the ones which directly affect/explain the Java workload. (From what I see, only `sgx.enclave_size` and `sgx.thread_num` can keep their comments.)
___
*[Examples/java/Makefile, line 8 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgim-3y3z8zmEfne4Yf:-Mgim-3y3z8zmEfne4Yg:b-iu8epj) ([raw file](https://github.com/oscarlab/graphene/blob/05f5699b1c921719833af998f127eb1b079c585b/Examples/java/Makefile#L8)):*
> ```Makefile
> # - make SGX=1 DEBUG=1  Building for SGX (with Graphene debug output)
> #
> # Use `make clean` to remove Graphene-generated files.
> ```

Recently, we decided to remove all irrelevant comments in Makefiles (see any example in our Examples/, except Redis). Please remove all comments here.
___
*[Examples/java/Makefile, line 10 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgim3ZCBrYjAs5okg-y:-Mgim3ZCBrYjAs5okg-z:bnycafp) ([raw file](https://github.com/oscarlab/graphene/blob/05f5699b1c921719833af998f127eb1b079c585b/Examples/java/Makefile#L10)):*
> ```Makefile
> # Use `make clean` to remove Graphene-generated files.
> 
> include ../../Scripts/Makefile.configs
> ```

Recently, we got rid of this include. Please remove. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
___
*[Examples/java/Makefile, line 13 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgimTQA27IULW05ccHF:-MgimTQA27IULW05ccHG:b5lp1ef) ([raw file](https://github.com/oscarlab/graphene/blob/05f5699b1c921719833af998f127eb1b079c585b/Examples/java/Makefile#L13)):*
> ```Makefile
> 
> # Relative path to Graphene root
> GRAPHENEDIR ?= ../..
> ```

We got rid of this, please remove. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
___
*[Examples/java/Makefile, line 31 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgimgTXCHe5OyNqbnlA:-MgimgTXCHe5OyNqbnlB:b-clwfg1) ([raw file](https://github.com/oscarlab/graphene/blob/05f5699b1c921719833af998f127eb1b079c585b/Examples/java/Makefile#L31)):*
> ```Makefile
> 	graphene-manifest \
> 		-Dlog_level=$(GRAPHENE_LOG_LEVEL) \
> 		-Darch_libdir=$(ARCH_LIBDIR) \
> ```

Please define `ARCH_LIBDIR` explicitly in this Makefile. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
___
*[Examples/java/Makefile, line 36 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgimbqu5EI1u-XhdWWg:-Mgimbqu5EI1u-XhdWWh:bhoinc7) ([raw file](https://github.com/oscarlab/graphene/blob/05f5699b1c921719833af998f127eb1b079c585b/Examples/java/Makefile#L36)):*
> ```Makefile
> 
> java.manifest.sgx: java.manifest
> 	graphene-sgx-sign \
> ```

Before this line, please add a check on existence of `SGX_SIGNER_KEY`. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
___
*[Examples/java/README.md, line 5 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgin4ci6q3S13IKUsph:-Mgin4cj8wqdiZtaj7ll:b-bpvpfs) ([raw file](https://github.com/oscarlab/graphene/blob/05f5699b1c921719833af998f127eb1b079c585b/Examples/java/README.md#L5)):*
> ```Markdown
> This directory contains an example for running a HelloWorld Java example in Graphene,
> including the Makefile and a template for generating the manifest.
> The application is tested on Ubuntu 18.04 with both normal Linux and SGX platforms.
> ```

Please remove this sentence about Ubuntu 18.04 and Linux/SGX platforms. Recently we removed all such generic statements and put them in a top-level README. See https://github.com/oscarlab/graphene/commit/b2a8eeecb5e109c81badac17ee9b59fa99b31c8e.


<!-- Sent from Reviewable.io -->

2021-08-11 08:50 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 5 of 8 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Examples/java/java.manifest.template, line 3 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgilbBH0fsvjLchBLJX:-MgoObtGESxjtfqCmIE0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61beefc6be3c67e4b1dfe448828744fce9f3ab4f/Examples/java/java.manifest.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Recently, we decided to remove all irrelevant comments in manifest files (see any example in our Examples/, except Redis). Please remove all comments here, except the ones which directly affect/explain the Java workload. (From what I see, only `sgx.enclave_size` and `sgx.thread_num` can keep their comments.)
</blockquote></details>

Done.
___
*[Examples/java/Makefile, line 8 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgim-3y3z8zmEfne4Yf:-MgoOkFm9DT2jIL8pU9-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61beefc6be3c67e4b1dfe448828744fce9f3ab4f/Examples/java/Makefile#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Recently, we decided to remove all irrelevant comments in Makefiles (see any example in our Examples/, except Redis). Please remove all comments here.
</blockquote></details>

Done.
___
*[Examples/java/Makefile, line 10 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgim3ZCBrYjAs5okg-y:-MgoOmSKCbQF9YWe4qbC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61beefc6be3c67e4b1dfe448828744fce9f3ab4f/Examples/java/Makefile#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Recently, we got rid of this include. Please remove. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
</blockquote></details>

Done.
___
*[Examples/java/Makefile, line 13 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgimTQA27IULW05ccHF:-MgoOnED37QluZ7GHspU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61beefc6be3c67e4b1dfe448828744fce9f3ab4f/Examples/java/Makefile#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We got rid of this, please remove. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
</blockquote></details>

Done.
___
*[Examples/java/Makefile, line 31 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgimgTXCHe5OyNqbnlA:-MgoOoeD9oFlntkBMTU8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61beefc6be3c67e4b1dfe448828744fce9f3ab4f/Examples/java/Makefile#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please define `ARCH_LIBDIR` explicitly in this Makefile. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
</blockquote></details>

Done.
___
*[Examples/java/Makefile, line 36 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgimbqu5EI1u-XhdWWg:-MgoOpvL-zFYl03vugak:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61beefc6be3c67e4b1dfe448828744fce9f3ab4f/Examples/java/Makefile#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Before this line, please add a check on existence of `SGX_SIGNER_KEY`. See https://github.com/oscarlab/graphene/commit/f9bd16d9209a8b05da7eedb06a50a45bed2c5f03
</blockquote></details>

Done.
___
*[Examples/java/README.md, line 5 at r6](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mgin4ci6q3S13IKUsph:-MgoOssL89dLw6avzjGA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/61beefc6be3c67e4b1dfe448828744fce9f3ab4f/Examples/java/README.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this sentence about Ubuntu 18.04 and Linux/SGX platforms. Recently we removed all such generic statements and put them in a top-level README. See https://github.com/oscarlab/graphene/commit/b2a8eeecb5e109c81badac17ee9b59fa99b31c8e.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-11 08:51 UTC, jkr0103 reviewed
> Reviewed 1 of 5 files at r2, 3 of 6 files at r3, 1 of 4 files at r4, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-08-11 12:37 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[Examples/java/README.md, line 6 at r7](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgpCeSj14stfeEo8Dys:-MgpCeSj14stfeEo8Dyt:b-2qaszn) ([raw file](https://github.com/oscarlab/graphene/blob/3d749bd1bc29c0844fb6e2c7a147b200eea3dd31/Examples/java/README.md#L6)):*
> ```Markdown
> including the Makefile and a template for generating the manifest.
> 
> # Generating the manifest
> ```

Just noticed this weird empty section. Please simply remove it.


<!-- Sent from Reviewable.io -->

2021-08-12 00:23 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: 7 of 8 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @mkow)

___
*[Examples/java/README.md, line 6 at r7](https://reviewable.io/reviews/oscarlab/graphene/2465#-MgpCeSj14stfeEo8Dys:-MgrjUPC3xs_oHKIYJ_8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/3d749bd1bc29c0844fb6e2c7a147b200eea3dd31/Examples/java/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed this weird empty section. Please simply remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-24 14:12 UTC, mkow requested changes
> Reviewed 1 of 5 files at r2, 3 of 6 files at r3, 1 of 4 files at r4, 2 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsPJ6o78ucpayP8W0J:-MhsPJ6o78ucpayP8W0K:b-nbg6jl) (no related file):*
> added java sample to graphene examples

Commit message one-liner should be something like: [Examples] Add Java

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsQWHL2_lObHKuzdQp:-MhsQWHL2_lObHKuzdQq:bimekrl) (no related file):*
> Examples/java

It's actually an OpenJDK example, not just "Java". Java has a bunch of different runtimes which can differ a lot (e.g. one may work under Graphene and another not).

---
___
*[Examples/java/java.manifest.template, line 1 at r8](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsQ6Po18ssywVmiLYq:-MhsQ6Po18ssywVmiLYr:biuehmr) ([raw file](https://github.com/oscarlab/graphene/blob/1a91fb141287589f73f3d038ea3002850155ded1/Examples/java/java.manifest.template#L1)):*
> ```
> # Java manifest example
> ```

The reader already knows this, the file is in "Examples/java/java.manifest.template" ;)
___
*[Examples/java/java.manifest.template, line 26 at r8](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsU2oB0tpz_XjB3-Uf:-MhsU2oB0tpz_XjB3-Ug:b-harjrb) ([raw file](https://github.com/oscarlab/graphene/blob/1a91fb141287589f73f3d038ea3002850155ded1/Examples/java/java.manifest.template#L26)):*
> ```
> sgx.enclave_size = "8G"
> 
> # SGX needs minimum 32 threads for loading a JVM.
> ```

`a JVM` -> `OpenJDK runtime`
___
*[Examples/java/hello.java, line 2 at r8](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsPp8IBZkz0MVN6GeX:-MhsPp8IBZkz0MVN6GeY:b-f1l8rr) ([raw file](https://github.com/oscarlab/graphene/blob/1a91fb141287589f73f3d038ea3002850155ded1/Examples/java/hello.java#L2)):*
> ```Java
> //java sample program
> class hello {
> ```

In Java's naming convention class names should be capitalized.
___
*[Examples/java/hello.java, line 4 at r8](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsS1U_-FfL7o8J-KYX:-MhsS1U_-FfL7o8J-KYY:b-1ac5za) ([raw file](https://github.com/oscarlab/graphene/blob/1a91fb141287589f73f3d038ea3002850155ded1/Examples/java/hello.java#L4)):*
> ```Java
> class hello {
>     public static void main(String[] args) {
>         System.out.println("Hello, World!");
> ```

Could you add something a bit less trivial? So that we actually test something with it :)

Maybe something like incrementing a variable from a few threads? It should be just ~20 more lines and we'd test OpenJDK locks and threading with this.
___
*[Examples/java/README.md, line 17 at r8](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsSh6i7O180O-TjUVc:-MhsSh6i7O180O-TjUVd:brcxz0s) ([raw file](https://github.com/oscarlab/graphene/blob/1a91fb141287589f73f3d038ea3002850155ded1/Examples/java/README.md#L17)):*
> ```Markdown
> 
>     javac hello.java
>     jar cvfm hello.jar hello.mf hello.class
> ```

This should be part of Makefile, not README.
___
*[Examples/java/README.md, line 17 at r8](https://reviewable.io/reviews/oscarlab/graphene/2465#-MhsTSkl-eI_nfdccYCM:-MhsTSkl-eI_nfdccYCN:b6lez7h) ([raw file](https://github.com/oscarlab/graphene/blob/1a91fb141287589f73f3d038ea3002850155ded1/Examples/java/README.md#L17)):*
> ```
> jar cvfm hello.jar hello.mf hello.class
> ```

Why not just run the .class file directly? It would be simpler this way and you also wouldn't need the .mf file.
___
*[Examples/java_sample/hello.java, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2465#-MciKt_oEUosSKBGp9vX:-MhsPY1_419M3r6lZ53E:b66w6df) ([raw file](https://github.com/oscarlab/graphene/blob/b25da42bf1c9421684c9742011a665da5c12fbeb/Examples/java_sample/hello.java#L1)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

updated the comment
</blockquote></details>

What's the point of this comment?


<!-- Sent from Reviewable.io -->

2021-08-27 08:55 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Examples/openjdk/README.md, line 12 at r13](https://reviewable.io/reviews/oscarlab/graphene/2465#-Mi297X1EdogulH1jLvv:-Mi5jMfd00s7KJf0kYih:bxtjs99) ([raw file](https://github.com/oscarlab/graphene/blob/8cdd98eeb6df852ba82dde3f9435d8825146d5fb/Examples/openjdk/README.md#L12)):*
You did, if you change diff ranges in Reviewable to base vs r2 then you'll see

> ```
> sgx.trusted_files.libtcmalloc = "file:/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4"
> ```

in your manifest ;)


<!-- Sent from Reviewable.io -->

2021-08-30 06:36 UTC, dimakuv approved these changes
> Reviewed 2 of 8 files at r10, 1 of 3 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-08-30 21:17 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-30 21:21 UTC, mkow approved these changes
> Reviewed 1 of 8 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-30 21:21 UTC, mkow commented
Jenkins, retest this please

2021-08-30 21:39 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2465)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-30 21:51 UTC, merged