Strip confidential information from logs on "error" level
oscarlab/graphene pull request #2468
Opened 2021-06-21 23:08 UTC by mkow

## Description of the changes 

As officially added to the docs in #2454, running with `log_level = "error"` should be secure in production. This PR fixes the places where `log_error()` calls leaked potentially sensitive information.

Things I skipped from censoring:
- error codes: I assume they are not confidential, especially in log_error paths,
- non-SGX Linux PAL altogether,
- paths: they are not encrypted and visible from the host anyways,
- memory page addresses: same as with paths.

2021-06-23 17:13 UTC, boryspoplawski requested changes
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2468)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2468#-MctofQfBGUqyOIBk0Nv:-MctofQgBMi9CMdvmI9f:b-n3jl7s) (no related file):*
Two substantial notes:
- imo both addresses and error codes should be stripped. E.g. addresses are way more sensitive information than, let's say, `vmid` (which you did strip). As far as general memory layout (basically range of available addresses) is known by malicious host, each object addresses are not (we do have some form of ASLR).
- I very much dislike the current version of splitting 1 message into 2 parts. In debug mode they will be printed in separate lines and mixed between different threads/processes. Note that currently we don't have any way not to flush after each `log_*`.

---
___
*[common/include/spinlock.h, line 187 at r1](https://reviewable.io/reviews/oscarlab/graphene/2468#-Mctp15n83woAuzR8g9E:-Mctp15oCZzWrubB4SLH:bftxjj0) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/common/include/spinlock.h#L187)):*
> ```objc
>     unsigned int owner = __atomic_load_n(&lock->owner, __ATOMIC_RELAXED);
>     if (owner != get_cur_tid()) {
>         log_error("Unexpected lock ownership: owned by: %d, checked in: %d", owner, get_cur_tid());
> ```

FYI: this is only run in `DEBUG` mode, but let's keep it for uniformity. 


<!-- Sent from Reviewable.io -->

2021-06-24 12:14 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2468)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2468#-MctofQfBGUqyOIBk0Nv:-Mcxpsh16krr4RgDbyPy:b-liq8ej) (no related file):*
> imo both addresses and error codes should be stripped. E.g. addresses are way more sensitive information than, let's say, vmid (which you did strip). As far as general memory layout (basically range of available addresses) is known by malicious host, each object addresses are not (we do have some form of ASLR).

Any idea how to strip them in practice? Having two prints at literally every error in our codebase sounds like an overkill.

> I very much dislike the current version of splitting 1 message into 2 parts. In debug mode they will be printed in separate lines and mixed between different threads/processes. Note that currently we don't have any way not to flush after each log_*.

Yeah, I know and also dislike it, but I don't have any better ideas how to implement this.

---


<!-- Sent from Reviewable.io -->

2021-06-24 12:55 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2468)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2468#-MctofQfBGUqyOIBk0Nv:-Mcy4WPh7lbO46RqE74h:bosiqhf) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> imo both addresses and error codes should be stripped. E.g. addresses are way more sensitive information than, let's say, vmid (which you did strip). As far as general memory layout (basically range of available addresses) is known by malicious host, each object addresses are not (we do have some form of ASLR).

Any idea how to strip them in practice? Having two prints at literally every error in our codebase sounds like an overkill.

> I very much dislike the current version of splitting 1 message into 2 parts. In debug mode they will be printed in separate lines and mixed between different threads/processes. Note that currently we don't have any way not to flush after each log_*.

Yeah, I know and also dislike it, but I don't have any better ideas how to implement this.
</blockquote></details>

Maybe just turn all messages into debug/warning? Error log would be used just for fatal messages (just before dying) which would only point to a place in the code without printing any dynamic info.

---


<!-- Sent from Reviewable.io -->

2021-06-28 07:28 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2468)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2468#-MctofQfBGUqyOIBk0Nv:-MdGUlQ6DcxWj5LlCcEc:bnpsfsq) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe just turn all messages into debug/warning? Error log would be used just for fatal messages (just before dying) which would only point to a place in the code without printing any dynamic info.
</blockquote></details>

Maybe we should change `log_error()` signature? E.g. `log_error(msg, debug_details, msg_suffix, ...)`, and use it like this:
```
log_error("Unexpected lock ownership", "(owned by: %d, checked in: %d)", "\n", owner, get_cur_tid());
```

This format can support all our current error messages, doesn't split messages into two, and has a benefit of making `log_error` usage really special (making it hard for new developers to inadvertently leak secret data while adding logs).

---


<!-- Sent from Reviewable.io -->

2021-06-28 11:54 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2468)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2468#-MctofQfBGUqyOIBk0Nv:-MdHT-485L7qNx_fLSYg:b-7hqarp) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe we should change `log_error()` signature? E.g. `log_error(msg, debug_details, msg_suffix, ...)`, and use it like this:
```
log_error("Unexpected lock ownership", "(owned by: %d, checked in: %d)", "\n", owner, get_cur_tid());
```

This format can support all our current error messages, doesn't split messages into two, and has a benefit of making `log_error` usage really special (making it hard for new developers to inadvertently leak secret data while adding logs).
</blockquote></details>

On one hand I like the idea, sounds neat and would solve the problem, but on the other logging is supposed to be dead simple...

---


<!-- Sent from Reviewable.io -->

2021-06-28 16:20 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2468)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2468#-MctofQfBGUqyOIBk0Nv:-MdIPZl-EnYhWiaLoYpz:b-anpn5o) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

On one hand I like the idea, sounds neat and would solve the problem, but on the other logging is supposed to be dead simple...
</blockquote></details>

I like @dimakuv's idea and also talked with @pwmarcz, he also likes it (modulo some printing format details, but this we can review after it's implemented).

---


<!-- Sent from Reviewable.io -->

2021-06-28 19:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2468)* status: 1 of 12 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2468#-MctofQfBGUqyOIBk0Nv:-MdIzLX_2uXJmuelDgVC:bjzgw2t) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I like @dimakuv's idea and also talked with @pwmarcz, he also likes it (modulo some printing format details, but this we can review after it's implemented).
</blockquote></details>

Ok, I'll will implement it in a separate PR, but let's start with dropping these explicit newlines from the messages finally and make them implicit.

---


<!-- Sent from Reviewable.io -->

2021-06-28 19:01 UTC, closed without merging