Erase memory on `free()` in debug builds
oscarlab/graphene pull request #2470
Opened 2021-06-22 12:16 UTC by mkow

## Description of the changes 

Seems we finally can do this, some time ago everything exploded after doing so :) Now it found only one use-after-free bug, which is also fixed in this PR.

## How to test this PR? 

CI in debug mode.

2021-06-22 14:48 UTC, pwmarcz requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[common/include/list.h, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/2470#-McoAkEa-Uv73KSLa6Rz:-McoAkEa-Uv73KSLa6S-:b-n6ck1p) ([raw file](https://github.com/oscarlab/graphene/blob/204717f9b49c4180b01fd038c23ca386414cb2f7/common/include/list.h#L112)):*
> ```objc
> #endif
> 
> #define INVALID_PTR_CANARY ((void*)0xCCCCCCCC)
> ```

Unlike the memory after `memset(0xCC)`, this is a canonical address - maybe add a comment why?


<!-- Sent from Reviewable.io -->

2021-06-22 17:38 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/include/list.h, line 112 at r1](https://reviewable.io/reviews/oscarlab/graphene/2470#-McoAkEa-Uv73KSLa6Rz:-MconAhsEF1mclqyFXRn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/204717f9b49c4180b01fd038c23ca386414cb2f7/common/include/list.h#L112)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Unlike the memory after `memset(0xCC)`, this is a canonical address - maybe add a comment why?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-23 10:50 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-23 16:51 UTC, boryspoplawski requested changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/include/list.h, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctgw-ZC__goinzCZKX:-Mctgw-ZC__goinzCZKY:b-lr3zep) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/list.h#L115)):*
> ```objc
>  * from siginfo_t::si_addr. Downside of this is that there's a chance of it being a valid address,
>  * but it should be quite unlikely on x64. */
> #define INVALID_PTR_CANARY ((void*)0xCCCCCCCC)
> ```

Maybe `(void*)0xffffffffccccccccUL`? It's canonical, on x64 Linux it's invalid and on 32-bit it will get truncated to the same value as now.
___
*[common/include/list.h, line 207 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctfh2P3fcjpXrvJHdn:-Mctfh2P3fcjpXrvJHdo:bkukwh5) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/list.h#L207)):*
> ```objc
> 
> #ifdef DEBUG
> #define DEBUG_ERASE_NODE(NODE, FIELD)            \
> ```

Maybe add a `LIST_` prefix to be consistent with other macros? It's only used in this file, so not blocking.
___
*[common/include/slabmgr.h, line 382 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctj-WiCrRCcnUUBwpt:-Mctj-WiCrRCcnUUBwpu:b-qnp9jd) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/slabmgr.h#L382)):*
> ```objc
>         LARGE_MEM_OBJ mem = RAW_TO_OBJ(obj, LARGE_MEM_OBJ_TYPE);
> #ifdef DEBUG
>         memset(OBJ_RAW(mem), 0xCC, mem->size);
> ```

Why not `memset(obj, ...` ?
___
*[common/include/slabmgr.h, line 408 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlBTQ3EwetR9MqWor:-MctlBTR9whjDWmNGas1:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/slabmgr.h#L408)):*
> ```objc
>     SLAB_OBJ mobj = RAW_TO_OBJ(obj, SLAB_OBJ_TYPE);
> #ifdef DEBUG
>     memset(OBJ_RAW(mobj), 0xCC, slab_levels[mobj->level]);
> ```

ditto
___
*[common/include/slabmgr.h, line 408 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlOhY5jwrpyYvRtvb:-MctlOhZ2-iAQEIpSwum:b-ygcfh7) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/slabmgr.h#L408)):*
> ```objc
>     SLAB_OBJ mobj = RAW_TO_OBJ(obj, SLAB_OBJ_TYPE);
> #ifdef DEBUG
>     memset(OBJ_RAW(mobj), 0xCC, slab_levels[mobj->level]);
> ```

`slab_levels[level]`
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 138 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctlg_T8egaYNDiDaqw:-Mctlg_T8egaYNDiDaqx:b-zi0skx) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/bookkeep/shim_process.c#L138)):*
> ```C
>             child->uid = child_uid;
> 
>             LISTP_DEL_INIT(child, &g_process.children, list);
> ```

FYI: we add it to another list just below, so it does not really matter...
___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-MctlysK2CyZ9_btRD5_:b-nvkxg4) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
> ```C
>     assert(dent->nchildren == 0);
>     assert(LISTP_EMPTY(&dent->children));
>     assert(LIST_EMPTY(dent, siblings));
> ```

This seems like an useful assert.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 140 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctm0rG9LD2ZfMME53L:-Mctm0rG9LD2ZfMME53M:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L140)):*
> ```C
> 
>     if (count == 0) {
>         assert(LIST_EMPTY(dent, siblings));
> ```

ditto


<!-- Sent from Reviewable.io -->

2021-06-24 00:05 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: 4 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[common/include/list.h, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctgw-ZC__goinzCZKX:-McvE8nWCISfT-2hZth4:b-ygryhi) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/list.h#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `(void*)0xffffffffccccccccUL`? It's canonical, on x64 Linux it's invalid and on 32-bit it will get truncated to the same value as now.
</blockquote></details>

Huh, I was sure this would throw a warning on 32-bit with `-Wall` (because of stripping bits on the cast), but it seems that's not the case. Done.
btw. I ff-ed only the msb-extension bits, not the 32 highest ones.
___
*[common/include/list.h, line 207 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctfh2P3fcjpXrvJHdn:-McvI7Gy9tlxNbed4uAr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/list.h#L207)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe add a `LIST_` prefix to be consistent with other macros? It's only used in this file, so not blocking.
</blockquote></details>

Done.
___
*[common/include/slabmgr.h, line 382 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctj-WiCrRCcnUUBwpt:-McvIjlc-8rFgSrOrR1Z:bf4sqfr) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/slabmgr.h#L382)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `memset(obj, ...` ?
</blockquote></details>

Done. I got lost in this mess :(
___
*[common/include/slabmgr.h, line 408 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlBTQ3EwetR9MqWor:-McvItgF0focMuCYycx_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/slabmgr.h#L408)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[common/include/slabmgr.h, line 408 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlOhY5jwrpyYvRtvb:-McvItvqBUsNW722kU2-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/slabmgr.h#L408)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`slab_levels[level]`
</blockquote></details>

Done.
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 138 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctlg_T8egaYNDiDaqw:-McvIyzt-ATKRlcpkAOG:bk3v1jk) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/bookkeep/shim_process.c#L138)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

FYI: we add it to another list just below, so it does not really matter...
</blockquote></details>

Then why init it? The point of this change is to not do this in release builds.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-McvJ4f5DWq5EPHL6QsT:b-jlisic) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This seems like an useful assert.
</blockquote></details>

But it doesn't work, it assumes that the deleted list entry has zeros inside. Now it has the canary pointers in debug builds, so I don't think such an assert is useful.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 140 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctm0rG9LD2ZfMME53L:-McvJIUj46f8YVF6k-HS:bnj7hl0) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L140)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

same as above


<!-- Sent from Reviewable.io -->

2021-06-24 09:42 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[common/include/list.h, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctgw-ZC__goinzCZKX:-McxLrUd6vZS9WHl3aJE:b3nqh6) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/list.h#L115)):*
I've checked that before writing it here :)

> because of stripping bits on the cast

It's not the cast that strips bits - `unsigned long` is 32bits on gcc with -m32 so the warning would be about immediate value being too big for the type.
___
*[common/include/list.h, line 113 at r3](https://reviewable.io/reviews/oscarlab/graphene/2470#-McxMlKVDhdY2WPMpGfU:-McxMlKW5SOh1QW36zpM:bqbh2qm) ([raw file](https://github.com/oscarlab/graphene/blob/0d1f2d7fed0b31562e4596ced7337eec61a759b3/common/include/list.h#L113)):*
> ```objc
> 
> /* This is intentionally crafted to be in a canonical form on x64, so that it's not stripped from
>  * siginfo_t::si_addr. It's also never accessible from usermode, so it will always raise an
> ```

I would add that the last sentence is about x86/x64 Linux. Who knows were Graphene will be ported to...
___
*[LibOS/shim/src/bookkeep/shim_process.c, line 138 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctlg_T8egaYNDiDaqw:-McxNFh4EpB6ABaHqIk3:b309fdd) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/bookkeep/shim_process.c#L138)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Then why init it? The point of this change is to not do this in release builds.
</blockquote></details>

Idk, maybe `LISTP_ADD` had an assert on `LISTP_EMPTY` someday?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-McxNZZk38o6mc7BA0Sc:b-wzzdil) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But it doesn't work, it assumes that the deleted list entry has zeros inside. Now it has the canary pointers in debug builds, so I don't think such an assert is useful.
</blockquote></details>

It's not true, it still has zeroes because `_INIT` versions are used.


<!-- Sent from Reviewable.io -->

2021-06-24 11:42 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[common/include/list.h, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctgw-ZC__goinzCZKX:-Mcxo00d5soSqreX4v9L:b-1ujfa8) ([raw file](https://github.com/oscarlab/graphene/blob/14613d429fa5d51f053f7c693b1cd7017bed5595/common/include/list.h#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I've checked that before writing it here :)

> because of stripping bits on the cast

It's not the cast that strips bits - `unsigned long` is 32bits on gcc with -m32 so the warning would be about immediate value being too big for the type.
</blockquote></details>

Ah, true.
___
*[common/include/list.h, line 113 at r3](https://reviewable.io/reviews/oscarlab/graphene/2470#-McxMlKVDhdY2WPMpGfU:-McxnzqM5F13kcg8o8X6:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/0d1f2d7fed0b31562e4596ced7337eec61a759b3/common/include/list.h#L113)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would add that the last sentence is about x86/x64 Linux. Who knows were Graphene will be ported to...
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-Mcxo9YW3jJ5zIOiK7Gm:br6mofk) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's not true, it still has zeroes because `_INIT` versions are used.
</blockquote></details>

Maybe not everywhere. I stripped these asserts exactly because they were failing, so somehow it's possible to get a canaried node here.


<!-- Sent from Reviewable.io -->

2021-06-24 12:52 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-Mcy3VyI8wJNTRJ1PFzP:b-dougmd) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Maybe not everywhere. I stripped these asserts exactly because they were failing, so somehow it's possible to get a canaried node here.
</blockquote></details>

I've checked they are all `_INIT` also there is exactly one `DEL` using this field and it's `_INIT`, so it should never use canaries.


<!-- Sent from Reviewable.io -->

2021-06-24 13:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-Mcy7tGa0GaPganDM4Q9:bb4dnw5) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
```
> graphene-direct ./helloworld
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
[P3737635:T1:helloworld] assert failed ../LibOS/shim/src/fs/shim_dcache.c:115 LIST_EMPTY(dent, siblings)
```

Seems it's not ¯\\_(ツ)_/¯ Overall, I don't like the idea of asserting any properties on an object which was already released. What we should do is put some canaries in debug builds there to ensure crashes in case anyone tries to use them.


<!-- Sent from Reviewable.io -->

2021-06-24 15:00 UTC, boryspoplawski requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-McyV5MRB5TEkWGOPeG2:ba7to78) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
Ah, you removed the `_INIT` in this PR, which I already forgot about. That's why they are failing.

> Overall, I don't like the idea of asserting any properties on an object which was already released.

But this object is not release yet, it will be only after this function.

> What we should do is put some canaries in debug builds there to ensure crashes in case anyone tries to use them.

For general usage of the object you overwrite it after free, which is unrelated to this case.
This check is for objects that are still on some list but being freed now and is a bit stronger than just usage crashes - if a object is never used this will catch it too.

Generally I don't see a reason not to keep them - they can usefully catch some errors other checks do not. And we have the UAF checks (after free overwrite) anyway.


<!-- Sent from Reviewable.io -->

2021-06-28 07:34 UTC, dimakuv approved these changes
> Reviewed 2 of 6 files at r1, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)



<!-- Sent from Reviewable.io -->

2021-06-28 15:48 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: 5 of 6 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_dcache.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-MctlysJ9GDTtygbm-kR:-MdII4tyBk2EwjOTOXmi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L115)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ah, you removed the `_INIT` in this PR, which I already forgot about. That's why they are failing.

> Overall, I don't like the idea of asserting any properties on an object which was already released.

But this object is not release yet, it will be only after this function.

> What we should do is put some canaries in debug builds there to ensure crashes in case anyone tries to use them.

For general usage of the object you overwrite it after free, which is unrelated to this case.
This check is for objects that are still on some list but being freed now and is a bit stronger than just usage crashes - if a object is never used this will catch it too.

Generally I don't see a reason not to keep them - they can usefully catch some errors other checks do not. And we have the UAF checks (after free overwrite) anyway.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 140 at r2](https://reviewable.io/reviews/oscarlab/graphene/2470#-Mctm0rG9LD2ZfMME53L:-MdII6162MRARgaz4_4n:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6ba10c60b94a066d516bb9121c31280c0ba69468/LibOS/shim/src/fs/shim_dcache.c#L140)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-28 15:55 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-06-28 17:10 UTC, dimakuv approved these changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2470)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-28 17:11 UTC, merged