[LibOS] Rework IDs management
oscarlab/graphene pull request #2472
Opened 2021-06-22 20:22 UTC by boryspoplawski

## Description of the changes 
More description in commit message and comments.

Only caveat is that listing `/proc` does not show remote processes (but they are still accessible via `/proc/[pid]/*`, you just need to know the pid).

2021-06-22 20:30 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 0 of 24 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-McpOunwDc-QchDqK_F3:-McpOunwDc-QchDqK_F4:bjfplrz) (no related file):*
@pwmarcz please take a look (at least) at fs related changes

---
___
*[common/include/api.h, line 109 at r1](https://reviewable.io/reviews/oscarlab/graphene/2472#-McpOAxs8ofLdUTGyhPG:-McpOAxt5ZuPB-A8xDPa:bj83guk) ([raw file](https://github.com/oscarlab/graphene/blob/e3dc9569ca755833fb0f47b506f1d37f087a211f/common/include/api.h#L109)):*
> ```objc
> #endif
> 
> #define IS_SIGNED(T) ((T)-1 < (T)1)
> ```

kudos to @mkow for coming up with this :)
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 211 at r1](https://reviewable.io/reviews/oscarlab/graphene/2472#-McpPFdx4QRP1Ioe95fb:-McpPFdx4QRP1Ioe95fc:bdtyhxv) ([raw file](https://github.com/oscarlab/graphene/blob/e3dc9569ca755833fb0f47b506f1d37f087a211f/LibOS/shim/src/ipc/shim_ipc_id.c#L211)):*
> ```C
> }
> 
> static void release_id_range(IDTYPE start, IDTYPE end) {
> ```

`start` and `end` must denote an existing range, which means that if you change ownership of an ID, you need to release all parts separately (in case the range was split in multiple parts). This comes naturally with the current code.
If somebody has something against it, now is the time.
Maybe this requires more comments?
___
*[LibOS/shim/src/sys/shim_exit.c, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2472#-McpP5KX2_ltGlo-Bh0I:-McpP5KX2_ltGlo-Bh0J:b-xmhw2g) ([raw file](https://github.com/oscarlab/graphene/blob/e3dc9569ca755833fb0f47b506f1d37f087a211f/LibOS/shim/src/sys/shim_exit.c#L44)):*
> ```C
>      * lying around, so nothing bad should happen™. Hopefully...
>      */
>     release_id(get_cur_thread()->tid);
> ```

I don't know how to handle this better.


<!-- Sent from Reviewable.io -->

2021-06-23 11:07 UTC, pwmarcz reviewed
> Reviewed 5 of 24 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 6 of 24 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-McpOunwDc-QchDqK_F3:-McsWnNh7Hmjb7tpmWuU:boyqoyr) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@pwmarcz please take a look (at least) at fs related changes
</blockquote></details>

Filesystem changes look good. The rest looks too scary for me to reliably review :)

---
___
*[LibOS/shim/src/fs/proc/fs.c, line 67 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McsVZNOBFIMgK3sUna1:-McsVZNOBFIMgK3sUna2:b-n8hvxi) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/fs/proc/fs.c#L67)):*
> ```C
>     struct pseudo_node* ipc_thread_pid = pseudo_add_dir(root, /*name=*/NULL);
>     ipc_thread_pid->name_exists = &proc_ipc_thread_pid_name_exists;
>     /* Listing remote processes is not currently supported. */
> ```

Thanks for the comment!
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McsX7AC8MviJBAtriIF:-McsX7AD2ejKLFkJLRtp:bh5mres) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/fs/proc/ipc-thread.c#L24)):*
> ```C
>         return false;
> 
>     if (pid == g_process.pid) {
> ```

I wonder if `get_all_pid_status()` returned the local PID as well... I haven't checked when I wrote that.


<!-- Sent from Reviewable.io -->

2021-06-23 12:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 6 of 24 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-McpOunwDc-QchDqK_F3:-McskNQd1rudmhvlu18i:b-ucfknh) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Filesystem changes look good. The rest looks too scary for me to reliably review :)
</blockquote></details>

Thanks!

---
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McsX7AC8MviJBAtriIF:-McskajF8UMyi1qe6RQE:b-csw6ae) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/fs/proc/ipc-thread.c#L24)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I wonder if `get_all_pid_status()` returned the local PID as well... I haven't checked when I wrote that.
</blockquote></details>

I think it did not and hat's how I discovered it - I was failing to access `/proc/[pid]/maps` of local process, because ipc routines took precedence of local routines (afaik they are just checked iteratively).


<!-- Sent from Reviewable.io -->

2021-06-24 09:42 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure).

2021-06-24 09:45 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 6 of 24 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 56 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McxOp7L1Wtthzel67tx:-McxOp7M2FBOqRIF65BZ:bjsnc06) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L56)):*
> ```C
>         return -ENOMEM;
>     }
> #ifdef DO_TESTS
> ```

This is intended be removed before merging. It allows for some testing of the implementation: just add a couple of ranges with owner `0` (invalid) and change `g_last_id`.


<!-- Sent from Reviewable.io -->

2021-06-28 01:34 UTC, mkow requested changes
> Reviewed 14 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 16 of 24 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcsp15D0yJJ1iB7Bv2h:-Mcsp15D0yJJ1iB7Bv2i:b-41fglp) (no related file):*
Typo in the commit message: "proces"

---
___
*[common/include/api.h, line 109 at r1](https://reviewable.io/reviews/oscarlab/graphene/2472#-McpOAxs8ofLdUTGyhPG:-McspJpK0VxQLKv0Mpna:bjt9gjc) ([raw file](https://github.com/oscarlab/graphene/blob/e3dc9569ca755833fb0f47b506f1d37f087a211f/common/include/api.h#L109)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

kudos to @mkow for coming up with this :)
</blockquote></details>

I'm always happy to provide more hacks like this :)
___
*[LibOS/shim/include/shim_ipc.h, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mct6bXd6Y86hgd8AoY8:-Mct6bXeA53Zhheewiqw:b-widbty) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L23)):*
> ```objc
>     IPC_MSG_RESP = 0,
>     IPC_MSG_CHILDEXIT,          /*!< Child exit/death information. */
>     IPC_MSG_NEW_ID_RANGE,       /*!< Request new IDs range. */
> ```

I'd add "GET" to this one to make it less confusing
___
*[LibOS/shim/include/shim_ipc.h, line 159 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy-R9r1hMlgIjhR99b:-Mcy-R9r1hMlgIjhR99c:b-doe9kx) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L159)):*
> ```objc
>  *
>  * \param start[out] start of the new ID range
>  * \param end[out] end of the new ID range
> ```

I'd start using the `out_` prefix convention. Ditto for the whole PR.
___
*[LibOS/shim/include/shim_ipc.h, line 159 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy-U7L5haF9bqQvkRB:-Mcy-U7L5haF9bqQvkRC:b-y1q9so) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L159)):*
> ```objc
>  *
>  * \param start[out] start of the new ID range
>  * \param end[out] end of the new ID range
> ```

I think `[out]` should be after `\param`?
___
*[LibOS/shim/include/shim_ipc.h, line 193 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy0lQy98242h9-cegI:-Mcy0lQy98242h9-cegJ:b-19ji6g) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L193)):*
> ```
> parami
> ```

typo?
___
*[LibOS/shim/include/shim_thread.h, line 137 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy26nF0HOXQq9U6huc:-Mcy26nF0HOXQq9U6hud:b-466amp) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_thread.h#L137)):*
> ```
> preaload
> ```

typo
___
*[LibOS/shim/include/shim_thread.h, line 146 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy2QRk7oYpU0tU-zqY:-Mcy2QRk7oYpU0tU-zqZ:b-2a3ynl) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_thread.h#L146)):*
> ```
>  * \param remove_from_owned if true, ID is removed from owned and locally tracked IDs
> ```

Hmm, I don't understand this semantic. Could you explain? If `remove_from_owned` is true, then this ID will be used somehow in a different process?
___
*[LibOS/shim/include/shim_thread.h, line 152 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy34HW96SpHu-oEagf:-Mcy34HW96SpHu-oEagg:bt1xjjq) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_thread.h#L152)):*
> ```objc
> IDTYPE get_new_id(bool remove_from_owned);
> /*!
>  * \brief Releases (frees) previously allocated ID
> ```

Does this release the ID to the leader, or only mark it as non-owned in current process?
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McyHFdG-zvppLXNkUk1:-McyHFdG-zvppLXNkUk2:b-ya0kb) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L22)):*
> ```C
>     IDTYPE start;
>     IDTYPE end;
>     unsigned int taken_count;
> ```

Shouldn't this also be `IDTYPE`? OTOH, I see that this is capped by `MAX_RANGE_SIZE` which is small, but I don't like such a convoluted assumption.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 43 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McyPBrq036r9IfUQGkC:-McyPBrr6A5xvMnw2ZMH:bllnae0) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L43)):*
> ```C
> static struct shim_lock g_ranges_lock;
> 
> int init_id_ranges(IDTYPE preaload_tid) {
> ```

ditto (typo)
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 70 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McyQ6e_16lQY9esFMBc:-McyQ6e_16lQY9esFMBd:b-3tpezi) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L70)):*
> ```C
>     lock(&g_ranges_lock);
>     if (!g_last_range) {
>         g_last_range = malloc(sizeof(*g_last_range));
> ```

I'd feel better if allocations were outside the locked region if this won't make this function too complex.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 86 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McyRg_TD_ILwVqx6iar:-McyRg_TD_ILwVqx6ias:b91bo2q) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L86)):*
> ```C
>         assert(start <= end);
>         assert(end - start + 1 <= MAX_RANGE_SIZE);
>         assert(start > 0);
> ```

So, ID == 0 is somehow a reserved/magic one? Or it's banned only to simplify the calculations below and allow them to safely use `- 1` on it? (and to not have to return the ID using an out arg from here?)
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 94 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McyTxGu-_tomNMeTlUg:-McyTxGu-_tomNMeTlUh:b-1wo17b) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L94)):*
> ```C
>     }
>     assert(g_last_used_id < g_last_range->end);
>     assert(g_last_range->end - g_last_range->start + 1 > g_last_range->taken_count);
> ```

Would be more natural to read if you flipped the sides (it's `taken_count` which we assert that is still below the expected limit).
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Md9kwM_CApISZMvZ2zY:-Md9kwMa7EZxPBPEPgpd:b-8nff9n) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/fs/proc/ipc-thread.c#L8)):*
> ```C
> /*
>  * Implementation of `/proc/<remote-pid>`. Currently supports only `root`, `cwd` and `exe` symlinks,
>  * does not support process listsing (you need to know the pid in advance) and does not do any
> ```

`listsing` -> `listing`
___
*[LibOS/shim/src/fs/proc/ipc-thread.c, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdEszte9tcCSglACslx:-MdEstYvBwWx6jSnoP_4:b-bpav0q) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/fs/proc/ipc-thread.c#L32)):*
> ```C
>     struct shim_ipc_pid_retmeta* retmeta = NULL;
>     int ret = ipc_pid_getmeta(pid, PID_META_CRED, &retmeta);
>     if (ret < 0) {
> ```

One problem with this is that we silence potential errors (i.e. different than ENOENT), but to fix this we'd need to change the interface and add mo [...]

2021-06-28 11:22 UTC, dimakuv requested changes
> Reviewed 23 of 24 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGdpNh3csZt5qxO7UP:-MdGdpNi7YEFkc8UWpkj:b-429jc2) (no related file):*
What will be the plan to add Sys-V semaphores and other shared resources back to Graphene? Previously they were also considered as IDs (and re-used the same code), but now your implementation looks very PID/TID centric.

UPDATE: After reading the implementation, it doesn't look PID/TID centric. So this could be re-used for Sys-V stuff (if we decide to do this).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHLMPCEahBVpMYsiUm:-MdHLMPCEahBVpMYsiUn:b409f13) (no related file):*
We finally deleted `shim_ipc_ranges.c`. Graphene feels different now.

---
___
*[LibOS/shim/include/shim_ipc.h, line 172 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm5qc-mOK1C8-gtKC:-MdGm5qc-mOK1C8-gtKD:bmrpylr) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L172)):*
> ```objc
>  * \param end end of the ID range
>  *
>  * \p start and \p end must denote a full range.
> ```

What do you mean by this `full range`? Do you mean "inclusive"? In that case, please append `(inclusive)`.
___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdGm_M70sm1eun4XlXM:b-f51ugd) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
> ```objc
>  *
>  * This operation effectively splits an existing ID range. Each (if any) of the range parts must be
>  * later on freed separately.
> ```

This is vague. What exactly happens if we have this:
- existing ID range is `1..10`, belongs to ID `pid1`
- we call this function with `id=5`, `new_owner=pid2`

Do we have three ranges then? `1..4` -> `pid1`, `5` -> `pid2`, `6..10` -> `pid1`? And do we need to free each of these three ranges?

UPDATE: The answer is in `change_id_owner()`. My example is correct, we create three ranges if the ID is somewhere in the middle of an existing range. I suggest to add some comment or maybe just this example.
___
*[LibOS/shim/include/shim_ipc.h, line 193 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGnCEB7qV3iwD2a_3r:-MdGnCEB7qV3iwD2a_3s:b-isuk6p) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L193)):*
> ```objc
>  *
>  * \param id id to find the owner of
>  * \parami[out] owner contains vmid of the process owning \p id
> ```

What happens if there is no owner? Do we return some error code?
___
*[LibOS/shim/include/shim_ipc.h, line 254 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGnM1j4Y0GKJLvwhrC:-MdGnM1j4Y0GKJLvwhrD:b-ba5l42) ([raw file](https://github.com/oscarlab/graphene/blob/995dac4b1188daff9a253374782b55e4b6cdbfd5/LibOS/shim/include/shim_ipc.h#L254)):*
> ```objc
> } __attribute__((packed));
> 
> /* PID_RETSTATUS: return status of pid(s) */
> ```

What was this one used for? And why is it removed now?
___
*[LibOS/shim/include/shim_thread.h, line 144 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGngwE1lXYFed9-tkJ:-MdGngwE1lXYFed9-tkK:b1yber3) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_thread.h#L144)):*
> ```objc
> 
> /*!
>  * \brief Allocates new ID
> ```

Do these new functions really belong to `shim_thread.h`? They are more than just for TID management; at some point they will also be used for other shared resources (I guess?). Maybe create a new header file for them or at least move them to `shim_internal.h`?
___
*[LibOS/shim/include/shim_thread.h, line 146 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy2QRk7oYpU0tU-zqY:-MdGn_hhASC6A58qGL_H:b-migktx) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_thread.h#L146)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
>  * \param remove_from_owned if true, ID is removed from owned and locally tracked IDs
> ```

Hmm, I don't understand this semantic. Could you explain? If `remove_from_owned` is true, then this ID will be used somehow in a different process?
</blockquote></details>

I also don't understand the semantics.

UPDATE: Ok, `remove_from_owned == true` for the case of spawning a new child process. In this case, the new ID is owned by the child process, not by this parent process. So the ID must be "hidden" from this process (= not in `g_used_ranges_tree` and not in `g_last_range`). Please add some comment like this.
___
*[LibOS/shim/src/shim_init.c, line 460 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGoJX88dCa3RSHkftU:-MdGoJX88dCa3RSHkftV:bu2oopa) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/shim_init.c#L460)):*
> ```C
>         ret = ipc_change_id_owner(g_process.pid, g_self_vmid);
>         if (ret < 0) {
>             log_debug("shim_init: failed to change child process PID ownership: %d\n", ret);
> ```

Why debug, not error?
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdH-p8N9-QcE2lKafXd:-MdH-p8N9-QcE2lKafXe:b-c3ftt9) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L1)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

The name `shim_pid.c` is inconsistent with other names. Please change to `shim_id.c`.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGpsiWD0yA4ebsbPUj:-MdGpsiWD0yA4ebsbPUk:b-u6czms) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L32)):*
> ```C
>      * ```return a->start <= b->start;```
>      * because overlapping ranges in one tree are disallowed, but it also enables easy lookups of
>      * ranges overlapping any given point.
> ```

This is confusing. Why not just use `a->start <= b->start` and make sure that "any given point" always has `b->start == b->end`?
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGqRZ85AcfKlSUQRuM:-MdGqRZ85AcfKlSUQRuN:bypzfqb) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L49)):*
> ```C
> 
>     if (!preaload_tid) {
>         return 0;
> ```

Shouldn't you destroy the lock as part of cleanup?
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 54 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGqVRT2KGrvfDJXB8u:-MdGqVRT2KGrvfDJXB8v:bypzfqb) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L54)):*
> ```C
>     struct id_range* range = malloc(sizeof(*range));
>     if (!range) {
>         return -ENOMEM;
> ```

Shouldn't you destroy the lock as part of cleanup?
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 77 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGw4G6EuKh7beTuZOU:-MdGw4G6EuKh7beTuZOV:b-ut3n8i) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L77)):*
> ```C
>         IDTYPE start;
>         IDTYPE end;
>         int ret = ipc_alloc_id_range(&start, &end);
> ```

This should also be moved  [...]

2021-06-28 12:30 UTC, mkow requested changes
> Reviewed 9 of 24 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 45 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHLMPCEahBVpMYsiUm:-MdH_plP48yDPlWxYWQH:bkhp78f) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We finally deleted `shim_ipc_ranges.c`. Graphene feels different now.
</blockquote></details>

I agree :)

---
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 300 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHV4pR-ermCb8RS-tI:-MdHV4pR-ermCb8RS-tJ:b-afnzev) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L300)):*
> ```C
>     };
>     size_t msg_size = get_ipc_msg_size(sizeof(range));
>     struct shim_ipc_msg* msg = __alloca(msg_size);
> ```

Sometimes you use `alloca` and sometimes `malloc` (e.g. in line 258 in this very file). Any rule behind this?
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 322 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHWFO-B3CHMbz8qrza:-MdHWFO-B3CHMbz8qrzb:b9rfetd) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L322)):*
> ```C
>         return -ENOMEM;
>     }
>     init_ipc_msg(msg, IPC_MSG_FREE_ID_RANGE, msg_size);
> ```

Would be good if the function name matched the message name more closely ("free" vs "release").
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 330 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHWodUA2tkmwzvOmm-:-MdHWodUA2tkmwzvOmm0:bim8lam) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L330)):*
> ```C
> }
> 
> int ipc_release_id_range_callback(IDTYPE src, void* data, uint64_t seq) {
> ```

All these callbacks are used only in the IPC leader, right? Maybe it would be a good idea to rename them to something like "ipc_<op_name>_leader_callback"?
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 377 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHTCEl6AReXVoafJRR:-MdHTCEl6AReXVoafJRS:bn57t2l) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L377)):*
> ```C
>     if (!g_process_ipc_ids.leader_vmid) {
>         *owner = find_id_owner(id);
>         return 0;
> ```

Shouldn't we return failure if `owner == 0`? The callsites seem to not check for this value.
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 405 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHSwpxDJjHEUfk_4e8:-MdHSwpxDJjHEUfk_4e9:bz5rzgz) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L405)):*
> ```C
> int ipc_get_id_owner_callback(IDTYPE src, void* data, uint64_t seq) {
>     IDTYPE* id = data;
>     IDTYPE owner = find_id_owner(*id);
> ```

Who's checking for failure? (i.e. `owner == 0`)
___
*[LibOS/shim/test/regression/multi_pthread.c, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdH_9PI5NS5vw3gnWUM:-MdH_9PI5NS5vw3gnWUN:b-ip46jp) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/test/regression/multi_pthread.c#L30)):*
> ```C
>             if (x != 0) {
>                 printf("pthread_create: %d\n", x);
>                 ret = 1;
> ```

Shouldn't you break from the loops here? Otherwise we'll try to join this uninitialized thread structure.


<!-- Sent from Reviewable.io -->

2021-06-28 15:41 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 15 of 24 files reviewed, 44 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcsp15D0yJJ1iB7Bv2h:-MdHWr-16BQdlv8b-5LR:baw2tp5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Typo in the commit message: "proces"
</blockquote></details>

TODO at next rebase

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGdpNh3csZt5qxO7UP:-MdHX3ivE-oC0HOcXL_8:b-j8e24z) (no related file):*
> What will be the plan to add Sys-V semaphores and other shared resources back to Graphene?

I had no such plan unless users requested it.
But I also thought a bit about it :) More details below.

> After reading the implementation, it doesn't look PID/TID centric. So this could be re-used for Sys-V stuff (if we decide to do this).

I would rather not go this way, it's designed to handle PID ranges, not SYSV-IPC IDs. There's a change we would be able to use the sync engine merged recently.
The problems with using these ID ranges for SYSV-IPC:
- we would mix PIDs with IPC IDs; not a real problem, but sounds weird,
- there ranges are given in batches, to decrease amount of IPC messages on thread creation; there is no such need for SYSV stuff,
- I do not think that IPC IDs needs to be sequential, but here PIDs are and it adds a some otherwise unnecessary complexity to the implementation.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHLMPCEahBVpMYsiUm:-MdHWynlAQKoEWxcUDl1:b-ffl5s0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We finally deleted `shim_ipc_ranges.c`. Graphene feels different now.
</blockquote></details>

Hopefully in a good way :)

---
___
*[LibOS/shim/include/shim_ipc.h, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mct6bXd6Y86hgd8AoY8:-MdHZaWf3rZWvFrpE9Oe:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add "GET" to this one to make it less confusing
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 159 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy-R9r1hMlgIjhR99b:-MdH_pqa2tLYt3plub2G:b6eoiuj) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L159)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd start using the `out_` prefix convention. Ditto for the whole PR.
</blockquote></details>

Done, if I did not miss something.
___
*[LibOS/shim/include/shim_ipc.h, line 159 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy-U7L5haF9bqQvkRB:-MdHZcDgByvGLUg6gvPU:b-834n6i) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L159)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think `[out]` should be after `\param`?
</blockquote></details>

Oops.
___
*[LibOS/shim/include/shim_ipc.h, line 172 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm5qc-mOK1C8-gtKC:-MdHaFqJ1LuJx62vxvhK:b7r8ymf) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by this `full range`? Do you mean "inclusive"? In that case, please append `(inclusive)`.
</blockquote></details>

I meant it must be a range that was previously allocated as a whole, not part of it.
Example: `/*snip*/`
Update: this exactly the case you described in the comment below.
___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdHeGNt6oFvA_TZddyn:b-lnnkym) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is vague. What exactly happens if we have this:
- existing ID range is `1..10`, belongs to ID `pid1`
- we call this function with `id=5`, `new_owner=pid2`

Do we have three ranges then? `1..4` -> `pid1`, `5` -> `pid2`, `6..10` -> `pid1`? And do we need to free each of these three ranges?

UPDATE: The answer is in `change_id_owner()`. My example is correct, we create three ranges if the ID is somewhere in the middle of an existing range. I suggest to add some comment or maybe just this example.
</blockquote></details>

Added some comments, please let me know how to describe it better.
___
*[LibOS/shim/include/shim_ipc.h, line 193 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy0lQy98242h9-cegI:-MdHZxO73B_JfktmYyZD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L193)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> parami
> ```

typo?
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 193 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGnCEB7qV3iwD2a_3r:-MdHh5K26JEPdmJadfOZ:b-57owxc) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L193)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What happens if there is no owner? Do we return some error code?
</blockquote></details>

Added a comment.
Generally `0` is considered an invalid ID in all of this code. Maybe that deserves a comment somewhere, but I do not really know where, since all of the code assumes that.
Also, `ipc_*` functions return errors only on real errors (like OOM or sending failure). It's responsibility of the caller to handle logical errors (like missing IDs - this function returns `0`, in others it would be a implementation bug).
___
*[LibOS/shim/include/shim_ipc.h, line 254 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGnM1j4Y0GKJLvwhrC:-MdHhyUq10OqFuATatah:bhxc0a2) ([raw file](https://github.com/oscarlab/graphene/blob/995dac4b1188daff9a253374782b55e4b6cdbfd5/LibOS/shim/include/shim_ipc.h#L254)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What was this one used for? And why is it removed now?
</blockquote></details>

It was used by `get_all_pid_status` to get list of all pids (other fields were not used). Only usage of `get_all_pid_status` was to list `/proc` entries, which is currently disabled (we can add it later on if needed, but I doubt there will be any real usage except testing).
___
*[LibOS/shim/include/shim_thread.h, line 137 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcy26nF0HOXQq9U6huc:-MdHicQk2xZxtA2KkS_s:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_thread.h#L137)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> preaload
> ```

typo
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_thread.h, line 144 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGngwE1lXYFed9-tkJ:-MdHihmo1ue7l7MWLzbD:bjzqe24) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f [...]

2021-06-28 16:13 UTC, mkow requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdIJasdE3Z55jnBrhCP:b-l477tn) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Added some comments, please let me know how to describe it better.
</blockquote></details>

Much better now, thanks! One question thought, to the last point in the example: who's supposed to call which release func? I.e. which of these two processes? Both all of them? Or 1, 2, 1?
___
*[LibOS/shim/src/shim_init.c, line 460 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGoJX88dCa3RSHkftU:-MdIKZZf9Dk-38AF375k:b-y41m70) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/shim_init.c#L460)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Because I thought the not-leaking-things-on-log_error PR will be merged before this, but seems it's not so obvious.
As a rule of thumb I assumed all dynamically build error messages leak stuff (even it these are seemingly unimportant things like error codes).
</blockquote></details>

I think this one will be ready first. I can update this place afterwards.
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 330 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHWodUA2tkmwzvOmm-:-MdIN8xE5vMdngVVReZl:bkbfbyl) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L330)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> All these callbacks are used only in the IPC leader, right?

Yes, they are only used in IPC leader.
> Maybe it would be a good idea to rename them to something like "ipc_<op_name>_leader_callback"?

Maybe, maybe not, I have no preference. Which one would you prefer? cc @dimakuv 
</blockquote></details>

I'd prefer to rename them, would be less confusing IMO. But let's wait for @dimakuv's opinion.
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 348 at r3](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdINQ9h9Qsu_-6rfDGO:-MdINQ9h9Qsu_-6rfDGP:bxnnlts) ([raw file](https://github.com/oscarlab/graphene/blob/ce3022dbe4000872210dba5eabf9eb78bc5bbf20/LibOS/shim/src/ipc/shim_ipc_id.c#L348)):*
> ```
> %u, %u
> ```

I think `%u..%u` would look nicer in the logs, where you don't have names of these arguments and may not remember what they mean exactly (e.g. maybe it's start + size?)


<!-- Sent from Reviewable.io -->

2021-06-28 17:54 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGdpNh3csZt5qxO7UP:-MdIb0b72EnxUeJd-idw:bghi3o6) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> What will be the plan to add Sys-V semaphores and other shared resources back to Graphene?

I had no such plan unless users requested it.
But I also thought a bit about it :) More details below.

> After reading the implementation, it doesn't look PID/TID centric. So this could be re-used for Sys-V stuff (if we decide to do this).

I would rather not go this way, it's designed to handle PID ranges, not SYSV-IPC IDs. There's a change we would be able to use the sync engine merged recently.
The problems with using these ID ranges for SYSV-IPC:
- we would mix PIDs with IPC IDs; not a real problem, but sounds weird,
- there ranges are given in batches, to decrease amount of IPC messages on thread creation; there is no such need for SYSV stuff,
- I do not think that IPC IDs needs to be sequential, but here PIDs are and it adds a some otherwise unnecessary complexity to the implementation.
</blockquote></details>

OK, I agree on all points. I was also thinking of using the sync engine from Pawel to implement SYS-V stuff (if at all).

---
___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdIc5s09eyZAamPip78:b-wudtb3) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Much better now, thanks! One question thought, to the last point in the example: who's supposed to call which release func? I.e. which of these two processes? Both all of them? Or 1, 2, 1?
</blockquote></details>

LGTM. As for Michal's question, each process must send a release-range message with its owned range (so 1,2,1) and the actual remove-from-tree/free happens in the leader process.
___
*[LibOS/shim/include/shim_thread.h, line 144 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGngwE1lXYFed9-tkJ:-MdId0wc87t41-FgGAQp:bv56fo0) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_thread.h#L144)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> Do these new functions really belong to shim_thread.h?

Yes, currently they allocate PID/TID explicitly.

> t some point they will also be used for other shared resources (I guess?).

Probably not.

> Maybe create a new header file for them or at least move them to shim_internal.h?

I didn't want to create another header for just 2 functions, since they are tightly couple with pid/tid atm.
</blockquote></details>

OK, makes sense.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdH-p8N9-QcE2lKafXd:-MdIdXy-4m1N3fspclXK:b-2tyf4t) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

The idea was that this file deals with PIDs (/TIDs) and `shim_ipc_id.c` can handle arbitrary IDs (e.g. also SYSV IPC stuff). In the meantime I came to the conclusion that handling them together is not a good idea.
If you want to rename it anyway, let's do that on the final rebase.
</blockquote></details>

Yeah, then I would prefer `shim_ipc_pid.c` name.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGpsiWD0yA4ebsbPUj:-MdIe-G9CuAIjcQMDtY1:bosyhi) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L32)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is a copy paste from `ipc/shim_ipc_id.c` and probably does not matter in this file.
Once these two file were merged together but it turned out the only similarity is this tree, so I've split them and just copy pasted the comparison function.
I see 3 options:
1) Change to `a->start <= b->start`
2) Remove the comment
3) Leave it as it is
4) Change the comment
I don't like 1) because what we have currently just basically checks whether `a` and `b` overlap and I don't like 2) because a binary tree cannot hold arbitrarily overlapping ranges. Probably 4) would be the best.
</blockquote></details>

I got confused by your options, but yes, please do option 4 then.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 49 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGqRZ85AcfKlSUQRuM:-MdIe8qP6TP6xi0Ynt5N:bflkhuh) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L49)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wait what? Why? This is `return 0;` it means the call was successful.
</blockquote></details>

Yep, copy-paste error :)
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 54 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGqVRT2KGrvfDJXB8u:-MdIeE4C-2o9_VNVXvyM:b2nhktp) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I thought we have a convention not to bother with cleanup in shim init functions.
</blockquote></details>

OK.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 77 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGw4G6EuKh7beTuZOU:-MdIeMlf25K9bcDMlcL0:bnmtp0r) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L77)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It cannot be moved out of the lock because it prevents multiple threads from allocating a new range in parallel. Handing such cases would be a mess.
</blockquote></details>

OK. Doesn't look like a perf problem anyway.
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 41 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHCvwVCVgCSyT4k8ed:-MdIf26j3omWmbhtesck:behlqgv) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

To be fair I got lost in all of this and have no idea what was the original reasoning. Maybe some intermediate version needed it...
Anyway, see the other comment with description of the current state and next steps.
</blockquote></details>

OK, resolving this since it's not a big issue for me.
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 330 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHWodUA2tkmwzvOmm-:-MdIjxAi28e334dyQU7Z:bafjaeg) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L330)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to rename them, would be less confusing IMO. But let's wait for @dimakuv's opinion.
</blockquote></details>

I didn't have any issue with these names. So if yo [...]

2021-06-28 21:16 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 22 of 24 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdIlEfj3WsBQXVz9sDT:bopczho) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

LGTM. As for Michal's question, each process must send a release-range message with its owned range (so 1,2,1) and the actual remove-from-tree/free happens in the leader process.
</blockquote></details>

It does not matter which process does it, but:
1) a single range must be freed by only one process (otherwise it would be a double free!, well, it wold be caught and IPC leader would die loudly)
2) it really does not make any sense to do it from a process other than the current owner of the range.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdH-p8N9-QcE2lKafXd:-MdInPCf6S6XHSKNMBTj:b6ixj0k) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, then I would prefer `shim_ipc_pid.c` name.
</blockquote></details>

TODO: at final rebase.
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGpsiWD0yA4ebsbPUj:-MdJJqTP2gBzrp5txO3k:bwgt2pi) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I got confused by your options, but yes, please do option 4 then.
</blockquote></details>

After thinking about this a bit: the current comment is correct and `a->start <= b->start` does not allow for overlapping range queries, even if one of them is a point.
Example:
Range `R = [1..10]`
Point `p = [5..5]`
`R <= p` is true (because `1 <= 5`), but `p <= R` is false (because `5 <= 1` is false). If we did a `lower_bound` on a tree containing only `R` with `p` as argument, it would return nothing, where as in the current (correct) version, it will return R.
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 330 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdHWodUA2tkmwzvOmm-:-MdImxcs0g_8oinszsy0:b3e3o19) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L330)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I didn't have any issue with these names. So if you want a majority vote, then it's 2:1 for keeping as-is.
</blockquote></details>

Strictly speaking it's 1:1 as I do not prefer any of these options :)
But keeping the current version is easier, so...
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 348 at r3](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdINQ9h9Qsu_-6rfDGO:-MdJFT5I8ivz5Hr7k8bQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/ce3022dbe4000872210dba5eabf9eb78bc5bbf20/LibOS/shim/src/ipc/shim_ipc_id.c#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to Michal's suggestion. Same in all other places where you print a range.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-28 21:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 22 of 24 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc_signal.c, line 33 at r4](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdJUB808Gu48zFZHFXR:-MdJUB808Gu48zFZHFXS:b-j2m3j6) ([raw file](https://github.com/oscarlab/graphene/blob/787c15cc6e0e9d430cea3582647cae500f61aee3/LibOS/shim/src/ipc/shim_ipc_signal.c#L33)):*
> ```C
>             /* No process owns `dest_pid`... */
>             if (is_zombie_process(dest_pid)) {
>                 /* ... but it's a zombie! */
> ```

This made me realize that the current semantics are a bit off: a child releases it's pid on exit, yet it might still be a zombie in the parent. In a unlikely case that the parents does not wait for the child for a long time and pids overlap we could have a nasty conflict.
The problem is that solving this is hard: we would need to make the parent own the pid of the child, but that would require "reparenting" in case the parent dies but the child is still alive. Such solution would also have some nasty consequences: Graphene pid 1 (which I guess would become the new parent) might not be expecting to have more children than it spawned (normal apps do not expect that, as init process is pretty special).
Generally speaking: there is a problem and there is no good solution to it.


<!-- Sent from Reviewable.io -->

2021-06-28 21:26 UTC, mkow requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdJV3ud-lk2o1fAR9IB:bthmgz) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It does not matter which process does it, but:
1) a single range must be freed by only one process (otherwise it would be a double free!, well, it wold be caught and IPC leader would die loudly)
2) it really does not make any sense to do it from a process other than the current owner of the range.
</blockquote></details>

Could you explain this in the comment? It's really not obvious to me which options are valid and which are currently used / make sense to be used.
___
*[LibOS/shim/src/ipc/shim_ipc_signal.c, line 33 at r4](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdJUB808Gu48zFZHFXR:-MdJVssr1D-myvB5QM94:b-b3m6v2) ([raw file](https://github.com/oscarlab/graphene/blob/787c15cc6e0e9d430cea3582647cae500f61aee3/LibOS/shim/src/ipc/shim_ipc_signal.c#L33)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This made me realize that the current semantics are a bit off: a child releases it's pid on exit, yet it might still be a zombie in the parent. In a unlikely case that the parents does not wait for the child for a long time and pids overlap we could have a nasty conflict.
The problem is that solving this is hard: we would need to make the parent own the pid of the child, but that would require "reparenting" in case the parent dies but the child is still alive. Such solution would also have some nasty consequences: Graphene pid 1 (which I guess would become the new parent) might not be expecting to have more children than it spawned (normal apps do not expect that, as init process is pretty special).
Generally speaking: there is a problem and there is no good solution to it.
</blockquote></details>

I think this comment deserves landing in the code ;)


<!-- Sent from Reviewable.io -->

2021-06-28 22:14 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 22 of 24 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdJaZTB-lUHXO08F_Ix:b-r83khn) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you explain this in the comment? It's really not obvious to me which options are valid and which are currently used / make sense to be used.
</blockquote></details>

Sure I could, but I'm not sure what to put where. Could you specify what comment you would like to have and where?
To me it's quite obvious that releasing/freeing the same range from 2 processes is wrong and other than that there are no real requirements. We do it in a certain way atm (owner releases it's own ranges), but it's not a requirement (parent or IPC leader could release them as well). As long as everything is released once and only once, it's all good.
But I'm the author of this code - I have a biased opinion - so it would be better if you described what requires a comment and where.
___
*[LibOS/shim/src/ipc/shim_ipc_signal.c, line 33 at r4](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdJUB808Gu48zFZHFXR:-MdJg5Y3EHXbpEr7UHa2:b-l502u3) ([raw file](https://github.com/oscarlab/graphene/blob/787c15cc6e0e9d430cea3582647cae500f61aee3/LibOS/shim/src/ipc/shim_ipc_signal.c#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this comment deserves landing in the code ;)
</blockquote></details>

Done in `shim_exit.c`


<!-- Sent from Reviewable.io -->

2021-06-28 22:51 UTC, mkow reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdJo0th9glKn8UM5VTP:ba9qpt9) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Sure I could, but I'm not sure what to put where. Could you specify what comment you would like to have and where?
To me it's quite obvious that releasing/freeing the same range from 2 processes is wrong and other than that there are no real requirements. We do it in a certain way atm (owner releases it's own ranges), but it's not a requirement (parent or IPC leader could release them as well). As long as everything is released once and only once, it's all good.
But I'm the author of this code - I have a biased opinion - so it would be better if you described what requires a comment and where.
</blockquote></details>

So, for me this wasn't clear if there's any requirement about such things or not. So, I'd just say here that technically any process is allowed to free any range, but in current implementation processes always free only the ranges they own. Ad where: just right below this example maybe?


<!-- Sent from Reviewable.io -->

2021-06-28 23:00 UTC, boryspoplawski commented
Jenkins, retest Jenkins-Debug-20.04 please (`fsync02` from LTP timedout, known issue)

2021-06-28 23:25 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 23 of 24 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdJwC3N3Scgu1GLNnkv:b92uiml) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, for me this wasn't clear if there's any requirement about such things or not. So, I'd just say here that technically any process is allowed to free any range, but in current implementation processes always free only the ranges they own. Ad where: just right below this example maybe?
</blockquote></details>

Added, please check.


<!-- Sent from Reviewable.io -->

2021-06-28 23:27 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 184 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdGm_M70sm1eun4XlXL:-MdJwmbj5n3XYoebLFA4:br06oxi) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/include/shim_ipc.h#L184)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Added, please check.
</blockquote></details>

Looks good, thanks!


<!-- Sent from Reviewable.io -->

2021-06-29 06:17 UTC, dimakuv approved these changes, later dismissed
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)



<!-- Sent from Reviewable.io -->

2021-06-29 11:09 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: 21 of 24 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2472#-Mcsp15D0yJJ1iB7Bv2h:-MdMQOPxBe5zCfmk3TjT:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO at next rebase
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/bookkeep/shim_pid.c, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-MdH-p8N9-QcE2lKafXd:-MdMR5qkDpmHJ-O17kWU:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/bookkeep/shim_pid.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

TODO: at final rebase.
</blockquote></details>

Done.
___
*[LibOS/shim/src/ipc/shim_ipc_id.c, line 56 at r2](https://reviewable.io/reviews/oscarlab/graphene/2472#-McxOp7L1Wtthzel67tx:-MdMRLhaCK4W3FKjkNW0:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/fe32da41a45607a95baa89f374901c505a3715f9/LibOS/shim/src/ipc/shim_ipc_id.c#L56)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

This is intended be removed before merging. It allows for some testing of the implementation: just add a couple of ranges with owner `0` (invalid) and change `g_last_id`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-29 11:27 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-06-29 12:25 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2472)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-06-29 12:27 UTC, merged