[LibOS] Implement POSIX locks
oscarlab/graphene pull request #2481
Opened 2021-06-28 18:16 UTC by pwmarcz

## Description of the changes 

## How to test this PR?

2021-06-30 13:20 UTC, dimakuv requested changes
> Reviewed 16 of 17 files at r1, 6 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdR60he1WtrGSwCeaYB:-MdR60he1WtrGSwCeaYC:b-213cxv) (no related file):*
> I initially added an example for SQLite, but together with @mkow we decided it's probably not worth keeping. Too much maintenance burden, and there are other tests anyway. So I removed it from this PR.

Could you submit it as a separate PR, so that we don't lose this work?

Generally, I believe that SQLite is a very good candidate to be included in our Examples and CI. It at least shows that SQL database engines can work on Graphene (currently we only have noSQL Redis in cache-only mode).

---
___
*[LibOS/shim/include/shim_fs_lock.h, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRED160L8yrdJNaVGX:-MdRED160L8yrdJNaVGY:b-pgugsb) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs_lock.h#L70)):*
> ```objc
>  *
>  * If `pl->type` is `F_UNLCK`, the function will remove any locks held by the given PID for the
>  * given range. Removing a locks never waits.
> ```

Typo: `a lock`
___
*[LibOS/shim/include/shim_fs_lock.h, line 97 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRF5uoDTzUOX4lzMw7:-MdRF5uoDTzUOX4lzMw8:b-p96qg) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs_lock.h#L97)):*
> ```objc
> int posix_lock_clear_pid(IDTYPE pid);
> 
> /* Version of `posix_lock_set` called from IPC callback. */
> ```

Could you add comments on params? For example, `path` must be an absolute path or can be relative? Must it be normalized? And what does `postponed` mean?

UPDATES:
- `path` is indeed an absolute path
- I don't like `postponed` and proposed to remove it in other comments
___
*[LibOS/shim/include/shim_fs_lock.h, line 101 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRF8_YAka6XcU_WHiA:-MdRF8_YAka6XcU_WHiB:bw7bail) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs_lock.h#L101)):*
> ```objc
>                             unsigned long seq, bool* postponed);
> 
> /* Version of `posix_lock_get` called from IPC callback. */
> ```

Could you add comments on params? This function is kinda obvious, so feel free to ignore.
___
*[LibOS/shim/include/shim_ipc.h, line 287 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRGkD730Polq0dsGom:-MdRGkD730Polq0dsGon:b-x7g0d0) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_ipc.h#L287)):*
> ```objc
> 
> int ipc_posix_lock_set(const char* path, struct posix_lock* pl, bool wait);
> int ipc_posix_lock_set_send_response(IDTYPE vmid, unsigned long seq, int result);
> ```

I am confused by this function. Why don't we have a similar one `ipc_posix_lock_get_send_response`?

UPDATE: I proposed to remove it (make it static) in other comments
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 320 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRHD1F9oDkp6DfxC5Z:-MdRHD1GApCgFeanIZXZ:b-glxmjs) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/src/bookkeep/shim_handle.c#L320)):*
> ```C
>     if (handle && handle->dentry) {
>         /* Clear POSIX locks for a file. We are required to do that every time a FD is closed
>          * closed, even if the process holds other handles for that file, or duplicated FDs for the
> ```

Typo: you have `closed closed`
___
*[LibOS/shim/src/fs/shim_dcache.c, line 456 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRI7y75mWnaEjGc5U_:-MdRI7y75mWnaEjGc5Ua:bnn7rbl) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/src/fs/shim_dcache.c#L456)):*
> ```C
>         }
> 
>         new_dent->fs_lock = NULL;
> ```

Could you add a comment that POSIX locks are not inherited over forks?
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRa42n5L6BapgjPK1e:-MdRa42n5L6BapgjPK1f:b8q3u9e) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L13)):*
> ```C
> #include "shim_lock.h"
> 
> /* Describes a pending request for a POSIX lock, either local on remote. After processing the request,
> ```

`on` -> `or`
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 28 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRaKjt7wKmnOcBUleg:-MdRaKjt7wKmnOcBUleh:b-pccw8q) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L28)):*
> ```C
>      * processing the request, IPC response will be sent. */
>     IDTYPE vmid;
>     unsigned int seq;
> ```

How do you distinguish between a local and a remote request? Could you add a comment on this?

UPDATE: Theoretically it can be both. But in reality, `event!=NULL` and `vmid!=0` denote that local/remote event should be fired.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 46 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRb-f61dfzPPkpZaGe:-MdRb-f61dfzPPkpZaGf:bkhaok5) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L46)):*
> ```C
>     LISTP_TYPE(posix_lock_request) posix_lock_requests;
> 
>     LIST_TYPE(fs_lock) list;
> ```

This field is for traversing `g_fs_lock_list`, right? Could you add a comment about this?
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 123 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRrrNC9MdDHIdzQilV:-MdRrrNC9MdDHIdzQilW:b-6ohi48) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L123)):*
> ```C
> static void fs_lock_gc(struct fs_lock* fs_lock) {
>     assert(locked(&g_fs_lock_lock));
>     if (g_log_level >= LOG_LEVEL_DEBUG)
> ```

Isn't it too much info? I would prefer `trace` level.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 139 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRvfFV8ztWcyV4c9OS:-MdRvfFV8ztWcyV4c9OT:b-5aawdy) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L139)):*
> ```C
>  * ranges overlap, and at least one of them is a write lock.
>  */
> static struct posix_lock* posix_lock_find(struct fs_lock *fs_lock, struct posix_lock* pl) {
> ```

Wrong asterisk alignment in the first argument (also in a couple other functions in this file, please fix all)
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 139 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRvwvx44YMHWYJbrzh:-MdRvwvx44YMHWYJbrzi:beofj21) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L139)):*
> ```C
>  * ranges overlap, and at least one of them is a write lock.
>  */
> static struct posix_lock* posix_lock_find(struct fs_lock *fs_lock, struct posix_lock* pl) {
> ```

Can we rename this func to `posix_lock_find_conflict`?
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 338 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRy0mDBSyllcwJm2Od:-MdRy0mDBSyllcwJm2Oe:bg2zpp2) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L338)):*
> ```C
> 
> /*
>  * Process pending requests after modifying the list of locks.
 [...]

2021-06-30 16:16 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: 8 of 17 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdR60he1WtrGSwCeaYB:-MdSAYuNBn-ihdTvwX8d:b-sz2evf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> I initially added an example for SQLite, but together with @mkow we decided it's probably not worth keeping. Too much maintenance burden, and there are other tests anyway. So I removed it from this PR.

Could you submit it as a separate PR, so that we don't lose this work?

Generally, I believe that SQLite is a very good candidate to be included in our Examples and CI. It at least shows that SQL database engines can work on Graphene (currently we only have noSQL Redis in cache-only mode).
</blockquote></details>

OK, I'll create a PR with this branch as target (since it doesn't work on master yet).

---
___
*[LibOS/shim/include/shim_fs_lock.h, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRED160L8yrdJNaVGX:-MdSArv22EmXWqohtThK:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs_lock.h#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `a lock`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs_lock.h, line 97 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRF5uoDTzUOX4lzMw7:-MdSdFcr2zwEL4yuwg43:bgn0dgu) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs_lock.h#L97)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add comments on params? For example, `path` must be an absolute path or can be relative? Must it be normalized? And what does `postponed` mean?

UPDATES:
- `path` is indeed an absolute path
- I don't like `postponed` and proposed to remove it in other comments
</blockquote></details>

I agree, these deserve more explanation, especially the part about a response. I added a full doc comment.

(I thought about using the `abs_path` name throughout the code, but it adds too much noise. But the comment now mentions it's supposed to be absolute).
___
*[LibOS/shim/include/shim_fs_lock.h, line 101 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRF8_YAka6XcU_WHiA:-MdSdcn25Jv4pws0aqXF:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs_lock.h#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add comments on params? This function is kinda obvious, so feel free to ignore.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_ipc.h, line 287 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRGkD730Polq0dsGom:-MdSdgebAHIU2A4eqcT9:b-omcahy) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_ipc.h#L287)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I am confused by this function. Why don't we have a similar one `ipc_posix_lock_get_send_response`?

UPDATE: I proposed to remove it (make it static) in other comments
</blockquote></details>

Because the response for `posix_lock_get` is sent immediately, and the one for `posix_lock_set` has to sometimes be sent later. I replied in detail in the other comment.
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 320 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRHD1F9oDkp6DfxC5Z:-MdSBbNvBH6BZBXHnp4l:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/src/bookkeep/shim_handle.c#L320)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: you have `closed closed`
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 456 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRI7y75mWnaEjGc5U_:-MdSBnagCitKRip2aPRU:b-7y1rcd) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/src/fs/shim_dcache.c#L456)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a comment that POSIX locks are not inherited over forks?
</blockquote></details>

It's not even about POSIX locks: currently `fs_lock` is used only by process leader. I added a comment.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRa42n5L6BapgjPK1e:-MdSC6FX26siyOxOMVqL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`on` -> `or`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 28 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRaKjt7wKmnOcBUleg:-MdSD9Ks57TZDfRE9TXm:b-8tgnbw) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How do you distinguish between a local and a remote request? Could you add a comment on this?

UPDATE: Theoretically it can be both. But in reality, `event!=NULL` and `vmid!=0` denote that local/remote event should be fired.
</blockquote></details>

I reworded this comment, and made the code a bit clearer: we always set all the fields, and check that exactly one of the cases is true.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 46 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRb-f61dfzPPkpZaGe:-MdSFC5M6RaxYhMY69-T:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This field is for traversing `g_fs_lock_list`, right? Could you add a comment about this?
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 123 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRrrNC9MdDHIdzQilV:-MdSFPx82UYjw_04D8JS:bc91zj1) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L123)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Isn't it too much info? I would prefer `trace` level.
</blockquote></details>

Makes sense, I imagine a program making heavy use of locks will output a lot of these (and we can always grep for them). Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 139 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRvfFV8ztWcyV4c9OS:-MdSFm9HEtuyx_sGd5nw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L139)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wrong asterisk alignment in the first argument (also in a couple other functions in this file, please fix all)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 139 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRvwvx44YMHWYJbrzh:-MdSFtSJ14lxp1pOj_rh:b6yw7bn) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04 [...]

2021-06-30 16:21 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: 8 of 17 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdR60he1WtrGSwCeaYB:-MdSiFScDbj6OgR53WC9:b-rqr43y) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK, I'll create a PR with this branch as target (since it doesn't work on master yet).
</blockquote></details>

PR: #2493

---


<!-- Sent from Reviewable.io -->

2021-06-30 17:06 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs_lock.h, line 120 at r4](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdSsVtz1z3h0mkRY-qc:-MdSsVtz1z3h0mkRY-qd:bgia2xh) ([raw file](https://github.com/oscarlab/graphene/blob/e0d9a2fcfa58b09c50e848fedb00119328c23968/LibOS/shim/include/shim_fs_lock.h#L120)):*
> ```objc
>  *
>  * \param path absolute path for a file
>  * \param pl parameters of new lock (type cannot be `F_UNLCK`
> ```

You forgot closing `)`
___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 117 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdS2agw1opFu_yzznxc:-MdSrj2MBpdZO5Jzxigj:b-z1oiny) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L117)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Are you proposing to *always* add a request and then invoke `posix_lock_process_requests()`? I don't want to do that: I think it would obscure the fact that the `wait == false` case is guaranteed to return immediately (even if technically that can be guaranteed). I'm sure the current version can be improved, but I like that it clearly distunguishes the "wait" and "return immediately" cases.

I agree with moving the invocation of `ipc_posix_lock_send_response()` to the main module, so that both these are handled in that file. That indeed removes the need for `postponed`. Done.

However, I disagree with making `ipc_posix_lock_set_send_response()` static. I think it belongs in this file - I want to keep actual logic and IPC glue code separate.
</blockquote></details>

OK, I like the new version.
___
*[LibOS/shim/src/sys/shim_exit.c, line 98 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRIymQ7UHiSQt8x890:-MdSrtBND-5M0jlz6u9x:byazc3l) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/src/sys/shim_exit.c#L98)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Reworded to say: "after a successful `wait()` by parent, our locks should already be gone". This is one of the issues found by LTP: the parent process got notified about a child process exit, but there was a short window before the locks of that process were removed (so `F_SETLK` sometimes failed for parent).
</blockquote></details>

OK, got it. Pretty cool.
___
*[LibOS/shim/src/sys/shim_fcntl.c, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRLp17Bb-fm1xn1pgP:-MdSs1-V0miNW32c0ix3:b-1drpga) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/src/sys/shim_fcntl.c#L134)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

They seem to be copied more or less verbatim from `man fcntl`, but the description in man page usually has some more paragraphs of context. They also seem to be outdated: for example, the versions of Linux man pages that I can find already correct some `long` argument types to `int`.

So, I'd rather not maintain these descriptions independently here. For any kind of serious review or modification I'd expect the developer to look at the man page anyway. 

How about we just keep the argument types here, and whatever Graphene does differently?

```c
/* See `man fcntl` for the expected semantics of these calls. */

/* F_DUPFD (int) */
case F_DUPFD: ...

/* F_SETLK, F_SETLKW (struct flock*): see `shim_fs_lock.h` for caveats */
case F_SETLK:
case F_SETLKW: ...

/* F_SETOWN (int): a dummy implementation for now */
case F_SETOWN:
    ret = 0;
    break;
```
</blockquote></details>

Yeah, removing is also a good option (well, actually a better one :)). Please proceed with your proposed change.


<!-- Sent from Reviewable.io -->

2021-06-30 19:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: 14 of 17 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/include/shim_fs_lock.h, line 120 at r4](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdSsVtz1z3h0mkRY-qc:-MdTJJPvDj8KATswFdVX:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/e0d9a2fcfa58b09c50e848fedb00119328c23968/LibOS/shim/include/shim_fs_lock.h#L120)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You forgot closing `)`
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/sys/shim_fcntl.c, line 134 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRLp17Bb-fm1xn1pgP:-MdTKRry23_W1FVsiZii:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/src/sys/shim_fcntl.c#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, removing is also a good option (well, actually a better one :)). Please proceed with your proposed change.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_fcntl.c, line 253 at r5](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdTTYiIEDbaPyj9CJWB:-MdTTYiIEDbaPyj9CJWC:b-gehkau) ([raw file](https://github.com/oscarlab/graphene/blob/69c15414d45ba2a4986e90f258b2230dfb2fab55/LibOS/shim/src/sys/shim_fcntl.c#L253)):*
> ```C
>                 if (pl2.end == FS_LOCK_EOF) {
>                     /* range until EOF is encoded as len == 0 */
>                     fl->l_len = 0;
> ```

Apparently this was not checked by LTP. I added a test to `regression/fcntl_lock.c`.


<!-- Sent from Reviewable.io -->

2021-07-01 02:01 UTC, mkow requested changes
FYI: I'm submitting a partial review for now and will finish the rest tomorrow.

> Reviewed 8 of 17 files at r1, 1 of 6 files at r2, 1 of 1 files at r3, 5 of 9 files at r4, 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481#-:-MdUmR-x4GDvF7ZX-pi7:b-821jjn)* status: 16 of 17 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 157 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdUmJYs1qBnwbT8yeNt:-MdUmJYs1qBnwbT8yeNu:b9s9tpj) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs.h#L157)):*
> ```objc
>     void* data;
> 
>     /* File lock information, stored in the main process. See shim_fs_lock.c. */
> ```

`stored in the main process` -> `stored only in the main process` (added "only")
___
*[LibOS/shim/include/shim_fs.h, line 118 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRtnbWBMl5FYP3zeb_:-MdRtnbWBMl5FYP3zeba:b-nems9r) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs.h#L118)):*
> ```objc
> #define DENTRY_MAX_CHILDREN 1000000
> 
> struct fs_lock_info;
> ```

Shouldn't we include `shim_fs_lock.h` instead?
___
*[LibOS/shim/include/shim_fs.h, line 162 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdS2mOR7Ks6irha6QWJ:-MdS2mOR7Ks6irha6QWK:b-i5vdh1) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs.h#L162)):*
> ```objc
>     /* True if the file might have locks placed by current process. Used in processes other than
>      * main process, to prevent unnecessary IPC calls on handle close. See shim_fs_lock.c. */
>     bool maybe_has_locks;
> ```

`locks` -> `fs_locks` (this is confusing, because it may mean Graphene-level locks for concurrent access to this struct)
___
*[LibOS/shim/include/shim_fs_lock.h, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdS37dG4IJgtcKrJij9:-MdS37dG4IJgtcKrJijA:b-te34gk) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs_lock.h#L7)):*
> ```
> Currently POSIX locks are implemented.
> ```

I'd add "only", sounds a bit weird otherwise.
___
*[LibOS/shim/include/shim_fs_lock.h, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdS4-YuAdPoYa1kjA_Z:-MdS4-YuAdPoYa1kjA__:b7njocq) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs_lock.h#L104)):*
> ```objc
> int posix_lock_get_from_ipc(const char* path, struct posix_lock* pl, struct posix_lock* out_pl);
> 
> #endif /* SHIM_FS_LOCK_H */
> ```

This doesn't match
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRuERF5Rx7l4wJPKsG:-MdRuERF5Rx7l4wJPKsH:b-qs7z6) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L36)):*
> ```C
> DEFINE_LISTP(fs_lock);
> DEFINE_LIST(fs_lock);
> struct fs_lock {
> ```

Why isn't this in the header?
___
*[LibOS/shim/test/ltp/ltp.cfg, line 372 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdNYqhS0p0E9pbRMGgV:-MdNYqhTBC5u8s_f9KA-:b-8vxym8) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/ltp/ltp.cfg#L372)):*
> ```INI
> timeout = 60
> 
> # no deadlock detection
> ```

please add "in POSIX locks"
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdPG2-GEmhpUIFsHg_M:-MdPG2-GEmhpUIFsHg_N:bp8t42i) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/regression/fcntl_lock.c#L107)):*
> ```C
> }
> 
> static void lock_ok(int type, long int start, long int len) {
> ```

Why is this named `lock_ok` but the above one is just `unlock`?
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 132 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdPFmPgE8w-tIk_hxo4:-MdPFmPgE8w-tIk_hxo5:b2ndhfc) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/regression/fcntl_lock.c#L132)):*
> ```C
>  */
> static void test_ranges() {
>     printf("test ranges...\n");
> ```

`test` -> `testing` (ditto below)
or just reword it somehow to make more sense grammatically/in this context :)
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 349 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdUmwl-1krbkDbklKvA:-MdUmwl-1krbkDbklKvB:b-pgdq58) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/regression/fcntl_lock.c#L349)):*
> ```C
>     if (unlink(TEST_FILE) < 0)
>         err(1, "unlink");
> ```

I'd leave this to keep this test self-contained, the removal in Python should be just a fallback.
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 111 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdUkoU23uQKLRDYnttl:-MdUkoU3CL93pRDWoDkR:b30ume6) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/test/regression/fcntl_lock.c#L111)):*
> ```C
> 
>     if (cmd == F_GETLK) {
>         return fl.l_type == F_UNLCK;
> ```

No check for `ret` in this case?


<!-- Sent from Reviewable.io -->

2021-07-01 07:03 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/sys/shim_fcntl.c, line 253 at r5](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdTTYiIEDbaPyj9CJWB:-MdVqQu_16Eh1K3N6hAM:bfv3b4d) ([raw file](https://github.com/oscarlab/graphene/blob/69c15414d45ba2a4986e90f258b2230dfb2fab55/LibOS/shim/src/sys/shim_fcntl.c#L253)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Apparently this was not checked by LTP. I added a test to `regression/fcntl_lock.c`.
</blockquote></details>

Oops, good catch!


<!-- Sent from Reviewable.io -->

2021-07-01 12:39 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: 11 of 17 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_fs.h, line 157 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdUmJYs1qBnwbT8yeNt:-MdX-4dHC4qETC3_Wq7S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/include/shim_fs.h#L157)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`stored in the main process` -> `stored only in the main process` (added "only")
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs.h, line 118 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRtnbWBMl5FYP3zeb_:-MdWyyow9_qBopJE6hYk:b-pa4h88) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs.h#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't we include `shim_fs_lock.h` instead?
</blockquote></details>

This is a private structure of `shim_fs_lock.c` anyway, so `shim_fs_lock.h` does not declare it.

I could declare it in `shim_fs_lock.h`, and include that here. Do you think that's better? I didn't want that, because then nobody would be forced to include `shim_fs_lock.h` directly, which I think is good for clarity.
___
*[LibOS/shim/include/shim_fs.h, line 162 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdS2mOR7Ks6irha6QWJ:-MdX-I_296HheLjABXfM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs.h#L162)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`locks` -> `fs_locks` (this is confusing, because it may mean Graphene-level locks for concurrent access to this struct)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_lock.h, line 7 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdS37dG4IJgtcKrJij9:-MdX-P_c9uTyt38zYU_v:b-ho5wpv) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs_lock.h#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Currently POSIX locks are implemented.
> ```

I'd add "only", sounds a bit weird otherwise.
</blockquote></details>

Agreed. Done.
___
*[LibOS/shim/include/shim_fs_lock.h, line 104 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdS4-YuAdPoYa1kjA_Z:-MdX-SXh14abdyd5I80G:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs_lock.h#L104)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This doesn't match
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 36 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRuERF5Rx7l4wJPKsG:-MdX-Tq2ARgo2cTW1juQ:b-tcpqzf) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/src/fs/shim_fs_lock.c#L36)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why isn't this in the header?
</blockquote></details>

Because it's a private structure, and only this file needs to know the details. See also futex or vma subsystems.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 372 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdNYqhS0p0E9pbRMGgV:-MdX-o_DDDqSrERmZjb6:b1boqb) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/ltp/ltp.cfg#L372)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please add "in POSIX locks"
</blockquote></details>

Done ("for POSIX locks" sounded better for me).
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 107 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdPG2-GEmhpUIFsHg_M:-MdX20ng9wZEbDFavDgq:b-ydavi0) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/regression/fcntl_lock.c#L107)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this named `lock_ok` but the above one is just `unlock`?
</blockquote></details>

Yes, it makes sense to rename it just to `lock`. Done.
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 132 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdPFmPgE8w-tIk_hxo4:-MdX2CEsD_9asE0NNrUO:bcqiebz) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/regression/fcntl_lock.c#L132)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`test` -> `testing` (ditto below)
or just reword it somehow to make more sense grammatically/in this context :)
</blockquote></details>

Changed all to "testing".
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 349 at r1](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdUmwl-1krbkDbklKvA:-MdX2cO4COY5dRYsy8Kg:b-b6pcm7) ([raw file](https://github.com/oscarlab/graphene/blob/a568e5bc416b601b734e6c6815dce12b0901c0e5/LibOS/shim/test/regression/fcntl_lock.c#L349)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```C
>     if (unlink(TEST_FILE) < 0)
>         err(1, "unlink");
> ```

I'd leave this to keep this test self-contained, the removal in Python should be just a fallback.
</blockquote></details>

OK. I restored the unlink here, and changed the Python code to "remove if exists".
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 111 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdUkoU23uQKLRDYnttl:-MdX0_JV9RhOGIAmAgx5:boh44bv) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/test/regression/fcntl_lock.c#L111)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No check for `ret` in this case?
</blockquote></details>

I added a check above, we really permit `ret` other than 0 in one specific case.


<!-- Sent from Reviewable.io -->

2021-07-01 13:17 UTC, dimakuv submitted a review, later dismissed
> Reviewed 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-07-01 13:49 UTC, mkow requested changes
> Reviewed 1 of 6 files at r2, 3 of 9 files at r4, 1 of 3 files at r5, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 118 at r3](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdRtnbWBMl5FYP3zeb_:-MdXIKZE98oImY6M8hFl:b-ebul4h) ([raw file](https://github.com/oscarlab/graphene/blob/d5711f77275357e04563d5f800badf967ae4c22b/LibOS/shim/include/shim_fs.h#L118)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is a private structure of `shim_fs_lock.c` anyway, so `shim_fs_lock.h` does not declare it.

I could declare it in `shim_fs_lock.h`, and include that here. Do you think that's better? I didn't want that, because then nobody would be forced to include `shim_fs_lock.h` directly, which I think is good for clarity.
</blockquote></details>

My main concern was this was the reason to use a pointer instead of directly embedding `fs_lock_info` into the `dentry`, but seems that's not the case. Anyways, I think we should rethink our conventions w.r.t. headers and what goes where...
___
*[LibOS/shim/include/shim_ipc.h, line 268 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX7DvsE3e2ze6fbhN4:-MdX7DvsE3e2ze6fbhN5:bwj4hhi) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/include/shim_ipc.h#L268)):*
> ```objc
>     int type;
>     uint64_t start;
>     uint64_t end;
> ```

Please comment whether this is inclusive or exclusive
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 33 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWulGz1tlVFhPCV25s:-MdWulGz1tlVFhPCV25t:b-lwf7ph) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L33)):*
> ```C
> 
>     PAL_HANDLE event;
>     int* result;
> ```

What's the lifetime/ownership of this? Why is it a pointer in the first place? I didn't read the implementation yet, but looks really weird and unconventional, so I think it deserves a comment :)
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 44 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX-S4L-PKPUGRRY-Ut:-MdX-S4L-PKPUGRRY-Uu:b7ghl82) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L44)):*
> ```
> sorted by PID and then by start position
> ```

Am I right, that this sorting is actually only for pretty-printing purposes?

Update: this is also used to be able to merge locks, right? If so, could you comment about this here? Overall sorted lists are rarely useful (because they are O(n^2) anyways), so it's a bit puzzling when you read it.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 58 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWyxv35ZSzZEnHJKNh:-MdWyxv35ZSzZEnHJKNi:bm6m5qh) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L58)):*
> ```
> including access to dentry `fs_lock`
> ```

That sounds weird (using a global lock to lock fields in some structures?), doesn't dentry already have its own lock?
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 170 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX2mWTAVWqJk_FUERL:-MdX2mWTAVWqJk_FUERM:bgvflfc) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L170)):*
> ```C
>     if (!req)
>         return -ENOMEM;
>     req->pl = *pl;
> ```

What's the condition on whether other fields are in initialized state? It's quite implicit right now, it deserves a comment at the structure at least. The current comment sounds like some of the fields should be initialized depending on whether this request is an IPC one, but here you don't initialize anything except `.pl`.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 204 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX6PiXAPe5JgTqVGbP:-MdX6PiXAPe5JgTqVGbQ:b-nrycai) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L204)):*
> ```C
> 
>     /* Target range: we will be changing it when merging existing locks. */
>     uint64_t start = pl->start, end = pl->end;
> ```

I'd prefer to have this on separate lines with aligned `=`.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 217 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5nSI71rm_f-I4kEx:-MdX5nSJ-Sz5-K7HhCd1:bf2ws03) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L217)):*
> ```C
>             continue;
>         }
>         if (pl->pid < cur->pid) {
> ```

I think it would read easier if you swapped sides, so that it complements the condition above.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 221 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5uar13ka8YL2VNQc:-MdX5uas65wXVTMLuGWh:b-ighxqf) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L221)):*
> ```C
>         }
> 
>         if (pl->type == cur->type) {
> ```

ditto (this time because we're iterating with `cur`, so it seems more natural to have it on the left)
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 285 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX9nmV7OquyNIS0N-W:-MdX9nmV7OquyNIS0N-X:b5r1ig7) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L285)):*
> ```
> start <= cur->start
> ```

Could you swap sides? Would be easier to notice that this is complement to the conditions above.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 304 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXA5308hqh-YFcWo5C:-MdXA5308hqh-YFcWo5D:b-jz3cb2) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L304)):*
> ```C
>                  */
>                 assert(start <= cur->start && end < cur->end);
>                 assert (end < FS_LOCK_EOF);
> ```

no space after `assert`
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 309 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXAG0j9bscm9if1oa0:-MdXAG0j9bscm9if1oa1:b-utjw3x) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L309)):*
> ```C
>             }
>         }
>     }
> ```

wow, that loop was tough
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 386 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXBw8f6LK7StW9IOE6:-MdXBw8f6LK7StW9IOE7:b1avbzr) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L386)):*
> ```
> bool wait
> ```

This name seems a bit misleading, because this function is not actually waiting if it's true, it just inserts a wait request into a list and returns.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 462 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXDX7D0qJ7-jcZSh55:-MdXDX7D0qJ7-jcZSh56:bsqr4mw) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L462)):*
> ```C
>         goto out;
>     if (req) {
>         assert(wait);
> ```

Why this always has to be the case here?
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 510 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXDxIEEzpeREf5872R:-MdXDxIEEzpeREf5872S:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L510)):*
> ` [...]

2021-07-01 14:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: 16 of 17 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_ipc.h, line 268 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX7DvsE3e2ze6fbhN4:-MdXPRcD2evT6vSqI-a8:b-8c711y) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/include/shim_ipc.h#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please comment whether this is inclusive or exclusive
</blockquote></details>

If I describe `start` and `end`, then probably I should also describe `type`, but I'd rather not duplicate all the comments from `struct posix_lock`. How about I say "see `struct posix_lock` in `shim_fs_lock.h`" instead?

I could also embed `struct posix_lock` here... that's a bit ugly because it contains the list node, though.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 33 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWulGz1tlVFhPCV25s:-MdXPyuI9OyEngBi8jsn:b-f8sf1p) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the lifetime/ownership of this? Why is it a pointer in the first place? I didn't read the implementation yet, but looks really weird and unconventional, so I think it deserves a comment :)
</blockquote></details>

Added a comment.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 44 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX-S4L-PKPUGRRY-Ut:-MdXQUxC1kXcrG_Ns0W1:b-sbf2ja) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> sorted by PID and then by start position
> ```

Am I right, that this sorting is actually only for pretty-printing purposes?

Update: this is also used to be able to merge locks, right? If so, could you comment about this here? Overall sorted lists are rarely useful (because they are O(n^2) anyways), so it's a bit puzzling when you read it.
</blockquote></details>

I added a comment.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 58 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWyxv35ZSzZEnHJKNh:-MdXS4wo7OljNnlvw7AU:bdb8br0) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> including access to dentry `fs_lock`
> ```

That sounds weird (using a global lock to lock fields in some structures?), doesn't dentry already have its own lock?
</blockquote></details>

I could use `dent->lock`, but I need the global lock for the global list anyway, at least when adding/removing/traversing it.

And actually I can't think of a way to traverse the list and process all the locks in `posix_lock_clear_pid`, any ideas?
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 170 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX2mWTAVWqJk_FUERL:-MdXUG53CS6Fp5vEhPgD:b-crv55n) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L170)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the condition on whether other fields are in initialized state? It's quite implicit right now, it deserves a comment at the structure at least. The current comment sounds like some of the fields should be initialized depending on whether this request is an IPC one, but here you don't initialize anything except `.pl`.
</blockquote></details>

I thought it would be clearer if we require the user to initialize all the fields. I grouped them in a `struct { ... } notify` to make that obvious.

(I also considered using a generic `callback, arg` pair, but it introduced another layer of indirection and did not look good.)
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 204 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX6PiXAPe5JgTqVGbP:-MdXUWOm9RKJaaRrplWu:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L204)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to have this on separate lines with aligned `=`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 217 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5nSI71rm_f-I4kEx:-MdXU_E2DDL31MqyMyR4:buuvtzh) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L217)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it would read easier if you swapped sides, so that it complements the condition above.
</blockquote></details>

It was clearer for me to keep all comparisons "left to right", so that the variables read in the order they was encountered. I won't insist, but do you think I should drop that convention in this whole function, or in some of the checks only (and which ones)?
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 221 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5uar13ka8YL2VNQc:-MdXUZpl4JiqyCVyAkRu:bjxunyf) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L221)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (this time because we're iterating with `cur`, so it seems more natural to have it on the left)
</blockquote></details>

Yeah, here there's no reason to keep it the opposite way. Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 285 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX9nmV7OquyNIS0N-W:-MdXUdyXAJbd003ElcSO:bs9uqgg) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L285)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> start <= cur->start
> ```

Could you swap sides? Would be easier to notice that this is complement to the conditions above.
</blockquote></details>

See above discussion about "left to right".
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 304 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXA5308hqh-YFcWo5C:-MdXUk48-gwc1eCV0clE:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L304)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no space after `assert`
</blockquote></details>

Fixed.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 309 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXAG0j9bscm9if1oa0:-MdXUkj72_YdFLzx4YAK:bdv1i66) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L309)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wow, that loop was tough
</blockquote></details>

I hope the ASCII art helped!
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 386 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXBw8f6LK7StW9IOE6:-MdXUmi71eRKpFDiPlKQ:b2ahyyr) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim [...]

2021-07-01 15:24 UTC, mkow reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/include/shim_ipc.h, line 268 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX7DvsE3e2ze6fbhN4:-MdXcCPt1UAev5EftZse:b5nywp9) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/include/shim_ipc.h#L268)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If I describe `start` and `end`, then probably I should also describe `type`, but I'd rather not duplicate all the comments from `struct posix_lock`. How about I say "see `struct posix_lock` in `shim_fs_lock.h`" instead?

I could also embed `struct posix_lock` here... that's a bit ugly because it contains the list node, though.
</blockquote></details>

"see `struct posix_lock` in `shim_fs_lock.h`" sounds good
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 33 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWulGz1tlVFhPCV25s:-MdXcQ9DDzO6CJI_EEx2:b-dcbopc) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L33)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Added a comment.
</blockquote></details>

Much better now, thanks!
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 58 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWyxv35ZSzZEnHJKNh:-MdXckXBByiGkhmwI_O2:b-h0sz8g) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L58)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I could use `dent->lock`, but I need the global lock for the global list anyway, at least when adding/removing/traversing it.

And actually I can't think of a way to traverse the list and process all the locks in `posix_lock_clear_pid`, any ideas?
</blockquote></details>

Is there anything wrong with keeping this lock constrained only to the global list and dentry locks to their own fields? When traversing the global list you'd need to take the list lock and then try to lock all the entries when inspecting them.
Be careful about the lock hierarchy though (right now it's global lock -> dentry lock, right?).
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 217 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5nSI71rm_f-I4kEx:-MdXdfdA8sPAX0T4OMB1:b-1x7m5) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L217)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It was clearer for me to keep all comparisons "left to right", so that the variables read in the order they was encountered. I won't insist, but do you think I should drop that convention in this whole function, or in some of the checks only (and which ones)?
</blockquote></details>

For me in code like this I need to follow which cases are handled where, and this is much easier if I have `if (a < b)` and `if (a >= b)` instead of `if (b <= a)`.

Let's ask @dimakuv and @boryspoplawski for their preferences.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 309 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXAG0j9bscm9if1oa0:-MdXe6Ii4JCiVFRym67b:bcmdrzo) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L309)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I hope the ASCII art helped!
</blockquote></details>

Yup, without it I'd probably just block with "please explain what's happening here" :)
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 462 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXDX7D0qJ7-jcZSh55:-MdXea4d4FIF-HROf8jz:bq8czxz) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L462)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Because `posix_lock_add_request` is allowed to add a request only if `wait` is true.

I'm not sure how to make that clearer. One idea:

```c
if (wait) {
    ret = posix_lock_set_or_add_request(dent, pl, &req);
} else {
    ret = posix_lock_set_or_give_up(dent, pl);
}
```

But that introduces too much duplication (between those two functions) to be worth it, IMO.

Another one:
```c
ret = posix_lock_set_or_add_request(dent, pl, wait ? &req : NULL);
```

But I think that's abusing the `out_req` parameter.

So for now, I added a short comment to `posix_lock_set_or_add_request`.

</blockquote></details>

Ok, maybe then just add "`posix_lock_add_request` is allowed to add a request only if `wait` is true" as a comment?
___
*[LibOS/shim/src/sys/shim_fcntl.c, line 70 at r7](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXH1Mh4KJyP0VjnA4l:-MdXekfjEIOoFPodQTD2:b-ox4xvn) ([raw file](https://github.com/oscarlab/graphene/blob/cbb432c4c8c4ffab2e892c1bbc2d74755a8eb3bb/LibOS/shim/src/sys/shim_fcntl.c#L70)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I thought so too, but `seek()` will change the file position. So I'm only allowed to call it with `(0, SEEK_CUR)` to find the current position.
</blockquote></details>

Could you say this in a comment in the code? I guess we won't be the last wondering about this :)


<!-- Sent from Reviewable.io -->

2021-07-01 15:40 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 217 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5nSI71rm_f-I4kEx:-MdXhVDG8BeJ5THEsRxg:b-aj15u7) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L217)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For me in code like this I need to follow which cases are handled where, and this is much easier if I have `if (a < b)` and `if (a >= b)` instead of `if (b <= a)`.

Let's ask @dimakuv and @boryspoplawski for their preferences.
</blockquote></details>

I prefer the current version. The pids in this list form a monotonic sequence / range (I guess so at least, didn't read the code other than these 2 ifs) so for me it's more natural to always use `<`/`<=` as comparison.


<!-- Sent from Reviewable.io -->

2021-07-02 06:42 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 217 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5nSI71rm_f-I4kEx:-Md_vYM_37yP3CVGHXcY:b-4xt3al) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L217)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I prefer the current version. The pids in this list form a monotonic sequence / range (I guess so at least, didn't read the code other than these 2 ifs) so for me it's more natural to always use `<`/`<=` as comparison.
</blockquote></details>

Sounds like we're doing bike shedding here :) I have no global preference. In this particular case, there is no mental effort for me to see that "we are searching for lock with higher PID, at which point we exit the loop; we memorize the lock with lower PID; if the lock has the same PID, then we go into the split-merge lock ranges logic".

I mean, these are five lines of code close to each other and doing continue/break. If these IF clauses would expand to 50 LoC each, then I would prefer Michal's suggestion (clauses complement each other). But here it's too tiny to bother.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 309 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXAG0j9bscm9if1oa0:-Md_wzCG-_qQ45lTmbZj:b2e0bmp) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L309)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, without it I'd probably just block with "please explain what's happening here" :)
</blockquote></details>

This ASCII art really helped! I took a note of this way of representation, will use it also.
___
*[LibOS/shim/src/sys/shim_fcntl.c, line 70 at r7](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXH1Mh4KJyP0VjnA4l:-Md_wjtbDRCv1ooywsYk:b9uemj9) ([raw file](https://github.com/oscarlab/graphene/blob/cbb432c4c8c4ffab2e892c1bbc2d74755a8eb3bb/LibOS/shim/src/sys/shim_fcntl.c#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you say this in a comment in the code? I guess we won't be the last wondering about this :)
</blockquote></details>

+1 to add the comment about the usage of `seek(0, SEEK_CUR)` in this code.


<!-- Sent from Reviewable.io -->

2021-07-02 09:52 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 217 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX5nSI71rm_f-I4kEx:-MdabxAK0e8Ws56Fo7Nz:b-rbtf7k) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds like we're doing bike shedding here :) I have no global preference. In this particular case, there is no mental effort for me to see that "we are searching for lock with higher PID, at which point we exit the loop; we memorize the lock with lower PID; if the lock has the same PID, then we go into the split-merge lock ranges logic".

I mean, these are five lines of code close to each other and doing continue/break. If these IF clauses would expand to 50 LoC each, then I would prefer Michal's suggestion (clauses complement each other). But here it's too tiny to bother.
</blockquote></details>

Ok, unblocking then.

@dimakuv: The problem is that this is a part of a function which was really hard to check thoroughly for correctness, partially because of the amount of conditions (I had to check for all cases which could be missed in those IFs).


<!-- Sent from Reviewable.io -->

2021-07-02 12:08 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: 12 of 17 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/include/shim_ipc.h, line 268 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdX7DvsE3e2ze6fbhN4:-MdarbU12fG7c1sKwdkB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/include/shim_ipc.h#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

"see `struct posix_lock` in `shim_fs_lock.h`" sounds good
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 58 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWyxv35ZSzZEnHJKNh:-MdargZR1aCOsQQywQmq:bojpt5e) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Is there anything wrong with keeping this lock constrained only to the global list and dentry locks to their own fields? When traversing the global list you'd need to take the list lock and then try to lock all the entries when inspecting them.
Be careful about the lock hierarchy though (right now it's global lock -> dentry lock, right?).
</blockquote></details>

Unfortunately, it's the opposite. We first take `dent->lock`, and usually that's enough; but sometimes we need to take the global lock to add to the list.

See my current solution. If you are not impressed by my Three Star Programming, I'm open to suggestions :)
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 462 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXDX7D0qJ7-jcZSh55:-MdapzSkBELBEHV1X_7A:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L462)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, maybe then just add "`posix_lock_add_request` is allowed to add a request only if `wait` is true" as a comment?
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 510 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXDxIEEzpeREf5872R:-Mdaq-Xz6H7-Tz0uc0nV:b-t57iqj) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L510)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Added a comment here too.
___
*[LibOS/shim/src/sys/shim_fcntl.c, line 70 at r7](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdXH1Mh4KJyP0VjnA4l:-MdarEHc3IGQNoxkh5rD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/cbb432c4c8c4ffab2e892c1bbc2d74755a8eb3bb/LibOS/shim/src/sys/shim_fcntl.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to add the comment about the usage of `seek(0, SEEK_CUR)` in this code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-02 12:10 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: 12 of 17 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/test/ltp/ltp.cfg, line 372 at r9](https://reviewable.io/reviews/oscarlab/graphene/2481#-Mdb6z2l0fK5hFWEazUw:-Mdb6z2l0fK5hFWEazUx:bkebyef) ([raw file](https://github.com/oscarlab/graphene/blob/0ee10e246033b858fabbf017efacde8a03892b8f/LibOS/shim/test/ltp/ltp.cfg#L372)):*
> ```INI
> timeout = 60
> 
> # depends on POSIX locks returning EINTR after signal, which we don't support
> ```

Failed on Jenkins... by my reading of the code, the test actually depends on this EINTR even when it passes.


<!-- Sent from Reviewable.io -->

2021-07-02 12:48 UTC, dimakuv approved these changes
> Reviewed 4 of 5 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-07-02 15:17 UTC, mkow requested changes
> Reviewed 4 of 5 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 58 at r6](https://reviewable.io/reviews/oscarlab/graphene/2481#-MdWyxv35ZSzZEnHJKNh:-Mdb7YOQ8qpziTRPNW3L:b-17dezi) ([raw file](https://github.com/oscarlab/graphene/blob/42c6def55b14ff93c8fec4e5d44999f67474e1bb/LibOS/shim/src/fs/shim_fs_lock.c#L58)):*
> Three Star Programming

Elite!


<!-- Sent from Reviewable.io -->

2021-07-02 15:18 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-02 15:25 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-07-02 18:11 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2481)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-02 18:13 UTC, merged