Fixing pointer check issues flagged by klockwork
oscarlab/graphene pull request #2483
Opened 2021-06-29 08:39 UTC by aneessahib

This PR fixes the following issues flagged by Klockwork scan of graphene repo

 Pointer 'cipher_info' returned from call to function 'mbedtls_cipher_info_from_type' at line 254 may be NULL and will be dereferenced at line 257.
/home/intel/graphene_klockwork/graphene/common/src/crypto/adapters/mbedtls_adapter.c:257 | lib_AESCMACFinish()

Pointer 'cipher_info' returned from call to function 'mbedtls_cipher_info_from_type' at line 212 may be NULL and will be dereferenced at line 214.
/home/intel/graphene_klockwork/graphene/common/src/crypto/adapters/mbedtls_adapter.c:214 | lib_AESCMAC()

2021-06-29 10:08 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2483#-MdME1Yz9rqGxAvb11Fp:-MdME1Yz9rqGxAvb11Fq:bsxm6e4) (no related file):*
Please fix your commit message to comply with our conventions. Also, you have a typo in it: it's "Klocwork", without "k" + should be capitalized.

---


<!-- Sent from Reviewable.io -->

2021-06-29 10:35 UTC, aneessahib commented
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2483#-MdME1Yz9rqGxAvb11Fp:-MdME1Yz9rqGxAvb11Fq:bsxm6e4) (no related file):_
> Please fix your commit message to comply with our conventions. Also, you have a typo in it: it's "Klocwork", without "k" + should be capitalized.

Done - changed both commit message as well as the PR title

2021-06-29 10:36 UTC, aneessahib commented
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)
> 
> _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2483#-MdME1Yz9rqGxAvb11Fp:-MdME1Yz9rqGxAvb11Fq:bsxm6e4) (no related file):_
> Please fix your commit message to comply with our conventions. Also, you have a typo in it: it's "Klocwork", without "k" + should be capitalized.

2021-06-29 10:37 UTC, aneessahib commented
> > > Reviewed 1 of 1 files at r1.
> > > _[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)_ status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)
> > 
> > 
> > _[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2483#-MdME1Yz9rqGxAvb11Fp:-MdME1Yz9rqGxAvb11Fq:bsxm6e4) (no related file):_
> > Please fix your commit message to comply with our conventions. Also, you have a typo in it: it's "Klocwork", without "k" + should be capitalized.

Done - changed both commit as well as the PR title

2021-06-29 10:42 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2483#-MdME1Yz9rqGxAvb11Fp:-MdMMBZk1dVOZrhecBN1:b-ucfknh) (no related file):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done - changed both commit as well as the PR title
</blockquote></details>

Thanks!

---


<!-- Sent from Reviewable.io -->

2021-06-29 12:29 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-06-29 12:29 UTC, dimakuv commented
Jenkins, test this please

2021-07-02 22:27 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-05 09:10 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-07-05 09:10 UTC, dimakuv commented
Jenkins, test this please

2021-07-05 10:11 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2483)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-05 10:13 UTC, merged