[Pal/Linux-SGX] Add `sgx.protected_mr{enclave,signer}_files` manifest options
oscarlab/graphene pull request #2484
Opened 2021-06-29 11:11 UTC by dimakuv

## Description of the changes 

Previously, only `sgx.protected_files` were available in the manifest. This kind of protected files needs a provisioned master (wrap) key. But sometimes it is enough to seal files on the same platform for later usage by the same enclave or by enclaves of the same signer: this is the SGX sealing feature.

This PR adds two more options to support SGX sealing: `sgx.protected_mrenclave_files` and `sgx.protected_mrsigner_files`.
Similarly to `sgx.protected_files`, these new options specify lists of files that are encrypted by the SGX key generated via SGX instruction `EGETKEY(SEAL_KEY)`, bound to the MRENCLAVE/MRSIGNER enclave measurement (so that only instances of the same enclave/only enclaves with the same signer may decrypt protected files). 

This is a reincarnation of #2328 but with a different user interface (and more flexible -- now we have three keys at the same time). Closes #2328.

## How to test this PR? 

A corresponding LibOS test is added and documentation is updated.

2021-07-30 15:42 UTC, mkow requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2484)* status: 1 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[Documentation/manifest-syntax.rst, line 493 at r1](https://reviewable.io/reviews/oscarlab/graphene/2484#-Mfs27Xt0ssica8a-6dh:-Mfs27Xt0ssica8a-6di:b-731f4v) ([raw file](https://github.com/oscarlab/graphene/blob/c8e152d4648b9d65fb8bbb13b7d3ae605e0b4caa/Documentation/manifest-syntax.rst#L493)):*
> ```reStructuredText
>     sgx.protected_files.[identifier]           = "[URI]"
>     sgx.protected_mrenclave_files.[identifier] = "[URI]"
>     sgx.protected_mrsigner_files.[identifier]  = "[URI]"
> ```

Could we use the proper syntax for this? (i.e. TOML arrays, not dictionaries)
We'll be changing this for all other file types soon, so I don't like adding this it this way and then rewriting 3 weeks later :)
___
*[Documentation/manifest-syntax.rst, line 521 at r1](https://reviewable.io/reviews/oscarlab/graphene/2484#-Mfs3Qp5CXGe-DPezm3N:-Mfs3Qp5CXGe-DPezm3O:b-9r94eb) ([raw file](https://github.com/oscarlab/graphene/blob/c8e152d4648b9d65fb8bbb13b7d3ae605e0b4caa/Documentation/manifest-syntax.rst#L521)):*
> ```
> enclaves from the same signer
> ```

I'd say "enclaves signed with the same key", it's less convoluted (i.e. it's IMO not obvious what "signer" means precisely).
___
*[LibOS/shim/test/regression/test_libos.py, line 728 at r1](https://reviewable.io/reviews/oscarlab/graphene/2484#-Mfs4C653pcRQu7ksam7:-Mfs4C653pcRQu7ksam8:b-kb1yp3) ([raw file](https://github.com/oscarlab/graphene/blob/c8e152d4648b9d65fb8bbb13b7d3ae605e0b4caa/LibOS/shim/test/regression/test_libos.py#L728)):*
> ```Python
>             self.assertIn(f'{node}/hugepages/hugepages-1048576kB/nr_hugepages: file', lines)
> 
>     def test_060_protected_file(self):
> ```

shouldn't this be named "sealed_file"?


<!-- Sent from Reviewable.io -->

2021-08-02 07:53 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2484)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 493 at r1](https://reviewable.io/reviews/oscarlab/graphene/2484#-Mfs27Xt0ssica8a-6dh:-Mg4aDuQB-o6er2jh2ww:b-nvdztk) ([raw file](https://github.com/oscarlab/graphene/blob/c8e152d4648b9d65fb8bbb13b7d3ae605e0b4caa/Documentation/manifest-syntax.rst#L493)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we use the proper syntax for this? (i.e. TOML arrays, not dictionaries)
We'll be changing this for all other file types soon, so I don't like adding this it this way and then rewriting 3 weeks later :)
</blockquote></details>

The old `sgx.protected_files` and the new `sgx.protected_{mrenclave,mrsigner}_files` are both handled by the same (old) code. This old code uses TOML dictionaries. So it will not be straight-forward to use TOML dicts only for the new options.

Anyway, it looks like high time to change from TOML dicts -> TOML arrays in our SGX files. I will submit a separate PR on this... And then I guess we'll rebase this PR on top of that other one.
___
*[Documentation/manifest-syntax.rst, line 521 at r1](https://reviewable.io/reviews/oscarlab/graphene/2484#-Mfs3Qp5CXGe-DPezm3N:-Mg4ayLaDSN9K4Nf2_ng:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/c8e152d4648b9d65fb8bbb13b7d3ae605e0b4caa/Documentation/manifest-syntax.rst#L521)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> enclaves from the same signer
> ```

I'd say "enclaves signed with the same key", it's less convoluted (i.e. it's IMO not obvious what "signer" means precisely).
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 728 at r1](https://reviewable.io/reviews/oscarlab/graphene/2484#-Mfs4C653pcRQu7ksam7:-Mg4_Zxn7ub9OzoMSELc:b-1e9o93) ([raw file](https://github.com/oscarlab/graphene/blob/c8e152d4648b9d65fb8bbb13b7d3ae605e0b4caa/LibOS/shim/test/regression/test_libos.py#L728)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

shouldn't this be named "sealed_file"?
</blockquote></details>

Do you mean to rename just this test? Or do you want to rename `sgx.protected_mrenclave_files`/`sgx.protected_mrsigner_files`?

Aynway, I currently changed the name of this test and the name of the generated test file.


<!-- Sent from Reviewable.io -->

2021-09-02 13:23 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2484)* status: 0 of 11 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Documentation/manifest-syntax.rst, line 493 at r1](https://reviewable.io/reviews/oscarlab/graphene/2484#-Mfs27Xt0ssica8a-6dh:-MiafIN52aw0QsIG5GFb:bs0wc92) ([raw file](https://github.com/oscarlab/graphene/blob/c8e152d4648b9d65fb8bbb13b7d3ae605e0b4caa/Documentation/manifest-syntax.rst#L493)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The old `sgx.protected_files` and the new `sgx.protected_{mrenclave,mrsigner}_files` are both handled by the same (old) code. This old code uses TOML dictionaries. So it will not be straight-forward to use TOML dicts only for the new options.

Anyway, it looks like high time to change from TOML dicts -> TOML arrays in our SGX files. I will submit a separate PR on this... And then I guess we'll rebase this PR on top of that other one.
</blockquote></details>

Done. Rebased to the latest master. @mkow Please re-review.


<!-- Sent from Reviewable.io -->

2021-09-07 12:45 UTC, dimakuv reviewed
*removed comment*

2021-09-29 08:32 UTC, dimakuv commented
Recreated this PR in https://github.com/gramineproject/gramine/pull/101. Closing here.

2021-09-29 08:32 UTC, closed without merging