[LibOS] Fix poll() crashing on pseudo-files
oscarlab/graphene pull request #2498
Opened 2021-07-02 13:57 UTC by pwmarcz

Found when investigating `stress-ng` (#2419).

## Description of the changes 

The code assumed that all handles (other than TYPE_FILE and TYPE_DEV) had an associated PAL handle, which caused a crash when polling files from /proc. This change adds support for polling TYPE_STR, and also adds a check for PAL handle in all cases.

(I think poll deserves a bigger rewrite, this is just a quick fix).

## How to test this PR? 

* The procfs stress test (`stress-ng --procfs 8 --timeout 40s`) stopped crashing for me (see #2419).
* I rewrote `poll` regression test to be more thorough, it checks several types of files now.

2021-07-02 18:54 UTC, dimakuv reviewed
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2498)* status: 2 of 6 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-07-05 08:39 UTC, dimakuv requested changes
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2498)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 446 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-MdpeJw_9nrOPJDwCCxj:-MdpeJw_9nrOPJDwCCxk:bb93wac) ([raw file](https://github.com/oscarlab/graphene/blob/c25a0f4074254e4179895573f5f49a28871823c7/LibOS/shim/src/fs/shim_fs_pseudo.c#L446)):*
> ```C
> 
> /* TODO: add support for polling TYPE_STR handles; currently `shim_do_poll` doesn't call this for
>  * anything else than TYPE_STR and TYPE_DEV */
> ```

Btw, this comment was wrong? I see that `shim_do_poll()` calls `hdl->fs->fs_ops->poll()` on TYPE_FILE and TYPE_DEV. There was no mention of TYPE_STR. 
___
*[LibOS/shim/src/fs/str/fs.c, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-MdplGVo2mBDiKZISSgV:-MdplGVo2mBDiKZISSgW:bclqx8o) ([raw file](https://github.com/oscarlab/graphene/blob/13106ef9b9ab447338ca783e043cf4664040e65b/LibOS/shim/src/fs/str/fs.c#L280)):*
> ```C
>     }
>     if (poll_type & FS_POLL_WR)
>         ret |= FS_POLL_WR;
> ```

Can we really always write in a pseudo-str-file? Some files are read-only (e.g. `/dev/attestation/report`), don't we want to check whether the permissions allow writing?
___
*[LibOS/shim/src/sys/shim_poll.c, line 110 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-Mdplr_h2gfN07E7BkcG:-Mdplr_h2gfN07E7BkcH:b-synayz) ([raw file](https://github.com/oscarlab/graphene/blob/13106ef9b9ab447338ca783e043cf4664040e65b/LibOS/shim/src/sys/shim_poll.c#L110)):*
> ```C
>              * callback.
>              *
>              * TODO: we probably should use the poll() callback in all cases. */
> ```

What do you mean by this comment?


<!-- Sent from Reviewable.io -->

2021-07-05 10:16 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2498)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 446 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-MdpeJw_9nrOPJDwCCxj:-Mdq5KxC7Z4hmlEW-omC:b-bfitf1) ([raw file](https://github.com/oscarlab/graphene/blob/c25a0f4074254e4179895573f5f49a28871823c7/LibOS/shim/src/fs/shim_fs_pseudo.c#L446)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Btw, this comment was wrong? I see that `shim_do_poll()` calls `hdl->fs->fs_ops->poll()` on TYPE_FILE and TYPE_DEV. There was no mention of TYPE_STR. 
</blockquote></details>

Yes, that was supposed to be "anything else than `TYPE_FILE` and `TYPE_DEV`".
___
*[LibOS/shim/src/fs/str/fs.c, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-MdplGVo2mBDiKZISSgV:-Mdq5YDUDOB1sd-qcLdE:bosbg9u) ([raw file](https://github.com/oscarlab/graphene/blob/13106ef9b9ab447338ca783e043cf4664040e65b/LibOS/shim/src/fs/str/fs.c#L280)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we really always write in a pseudo-str-file? Some files are read-only (e.g. `/dev/attestation/report`), don't we want to check whether the permissions allow writing?
</blockquote></details>

We check file permissions when setting handle mode, and the caller of `poll` callback (such as `shim_do_poll`) checks the handle mode. I don't think the `poll` callback itself should do that - the check is the same regardless of handle.

(This does allow a loophole where a user `chmod`s the file and then writes to it. I just checked and Linux allows you to `chmod` a file like `/proc/meminfo` to be writable, and even open it, but fails with `EIO` on the actual `write` call... I don't want to bother with replicating that now, but I'm planning to rewrite the `str_*` filesystem so maybe that will be the time.)
___
*[LibOS/shim/src/sys/shim_poll.c, line 110 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-Mdplr_h2gfN07E7BkcG:-Mdq8JTBBXJL8uv91yYa:b-njehb1) ([raw file](https://github.com/oscarlab/graphene/blob/13106ef9b9ab447338ca783e043cf4664040e65b/LibOS/shim/src/sys/shim_poll.c#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What do you mean by this comment?
</blockquote></details>

This function collects PAL handles and uses `DkStreamsWaitEvents` on them, disregarding the fact that most of filesystems actually have a `poll` callback defined. It calls the `poll` callback only for some specific handle types. That seems weird to me: what are the other `poll` callbacks even for?

I don't want to touch that right now, though, it looks like bigger change and I would need to understand our implementation of poll/epoll/select better. Right now I want to fix this one thing with STR handles.


<!-- Sent from Reviewable.io -->

2021-07-05 10:35 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2498)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/fs/str/fs.c, line 280 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-MdplGVo2mBDiKZISSgV:-MdqB3EHD6iJFvJODWP2:bs4ixp3) ([raw file](https://github.com/oscarlab/graphene/blob/13106ef9b9ab447338ca783e043cf4664040e65b/LibOS/shim/src/fs/str/fs.c#L280)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We check file permissions when setting handle mode, and the caller of `poll` callback (such as `shim_do_poll`) checks the handle mode. I don't think the `poll` callback itself should do that - the check is the same regardless of handle.

(This does allow a loophole where a user `chmod`s the file and then writes to it. I just checked and Linux allows you to `chmod` a file like `/proc/meminfo` to be writable, and even open it, but fails with `EIO` on the actual `write` call... I don't want to bother with replicating that now, but I'm planning to rewrite the `str_*` filesystem so maybe that will be the time.)
</blockquote></details>

OK, fair enough.
___
*[LibOS/shim/src/sys/shim_poll.c, line 110 at r1](https://reviewable.io/reviews/oscarlab/graphene/2498#-Mdplr_h2gfN07E7BkcG:-MdqBAp0BUFBb8MfL_Rb:b-4qgiru) ([raw file](https://github.com/oscarlab/graphene/blob/13106ef9b9ab447338ca783e043cf4664040e65b/LibOS/shim/src/sys/shim_poll.c#L110)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This function collects PAL handles and uses `DkStreamsWaitEvents` on them, disregarding the fact that most of filesystems actually have a `poll` callback defined. It calls the `poll` callback only for some specific handle types. That seems weird to me: what are the other `poll` callbacks even for?

I don't want to touch that right now, though, it looks like bigger change and I would need to understand our implementation of poll/epoll/select better. Right now I want to fix this one thing with STR handles.
</blockquote></details>

OK. The idea of a `poll` callback was to have a fall-back for those handle types that do not have a corresonding PAL handle (= emulated completely inside LibOS, without the help of the host OS). But let's not touch this now.


<!-- Sent from Reviewable.io -->

2021-07-05 13:07 UTC, mkow submitted a review, later dismissed
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2498)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-05 13:15 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2498)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-05 13:39 UTC, merged