[LibOS] Rewrite `shim_do_sendfile()` to make it simple, correct and robust
oscarlab/graphene pull request #2500
Opened 2021-07-02 18:44 UTC by dimakuv

## Description of the changes 

Now sendfile emulation doesn't try to be fancy and use `mmap` but instead simply `read`s from input handle and `write`s into output handle. This is not performant but good enough for now.

## How to test this PR? 

Several LTP tests are enabled.

2021-07-02 18:47 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: 0 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdcXrJU1XeAyWFZ6Q56:-MdcXrJV6A2UccBcvMOA:b-1yohan) (no related file):*
We should test this PR several times on Jenkins.

---
___
*[LibOS/shim/src/sys/shim_file.c, line 407 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdcXUc6AUXLS71bVCNk:-MdcXUc73dTJMojE8yBd:bbh8ywb) ([raw file](https://github.com/oscarlab/graphene/blob/c25a0f4074254e4179895573f5f49a28871823c7/LibOS/shim/src/sys/shim_file.c#L407)):*
> ```C
>             copysize = count - bytes > bufsize ? bufsize : count - bytes;
>             memcpy(bufo + boffo, bufi + boffi, copysize);
>             /* XXX: ??? Where is vma bookkeeping? Hans, get ze flammenwerfer... */
> ```

@boryspoplawski As requested :)
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1972 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdcXcmn9TGeigFc-x7C:-MdcXcmn9TGeigFc-x7D:b8ao3h) ([raw file](https://github.com/oscarlab/graphene/blob/c25a0f4074254e4179895573f5f49a28871823c7/LibOS/shim/test/ltp/ltp.cfg#L1972)):*
> ```INI
> skip = yes
> 
> [sendfile09]
> ```

`sendfile09` and `sendfile09_64` are quite slow (they create and then delete huge files) even in native execution. This is still far less than our default 30s timeout, but I should kick our Jenkins several times to make sure that these two do not timeout sometimes.


<!-- Sent from Reviewable.io -->

2021-07-02 20:18 UTC, boryspoplawski commented
Jenkins, retest this please (just making sure)

2021-07-02 21:57 UTC, dimakuv commented
Jenkins, retest this please (just making sure)

2021-07-02 22:01 UTC, boryspoplawski requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[LibOS/shim/src/sys/shim_file.c, line 361 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd2H7u6R4WhggKLbEL:-Mdd2H7u6R4WhggKLbEM:b-ev94j1) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L361)):*
> ```C
> }
> 
> long shim_do_sendfile(int ofd, int ifd, off_t* offset, size_t count) {
> ```

While we are here, could you change these to some sane names? E.g. `out_fd` instead of `ofd`.
___
*[LibOS/shim/src/sys/shim_file.c, line 367 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd2QA-0Q_ZBUKKdSRJ:-Mdd2QA-0Q_ZBUKKdSRK:bwe7v32) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L367)):*
> ```C
>         return -EFAULT;
> 
>     struct shim_handle* hdli = get_fd_handle(ifd, NULL, NULL);
> ```

ditto (name), maybe `in_handle`?
___
*[LibOS/shim/src/sys/shim_file.c, line 392 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd32AQ2YmQXw58Kccc:-Mdd32AQ2YmQXw58Kccd:bkk0g4v) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L392)):*
> ```C
>      *        into output FD. Mmap-based emulation may be more efficient but adds complexity (not
>      *        all handle types provide mmap callback). */
>     char buf[BUF_SIZE];
> ```

Could you just malloc it? I don't like the idea of creating big buffers on stack...
___
*[LibOS/shim/src/sys/shim_file.c, line 401 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd4wKe7BI_ddaNomQE:-Mdd4wKe7BI_ddaNomQF:bb56gyt) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L401)):*
> ```C
> 
>     off_t old_offset = 0;
>     off_t tmp_offset = 0;
> ```

Please move it inside appropriate block.
___
*[LibOS/shim/src/sys/shim_file.c, line 407 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdcXUc6AUXLS71bVCNk:-Mdd0lxn9GInx53vkwSy:b-6v10rb) ([raw file](https://github.com/oscarlab/graphene/blob/c25a0f4074254e4179895573f5f49a28871823c7/LibOS/shim/src/sys/shim_file.c#L407)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@boryspoplawski As requested :)
</blockquote></details>

Danke :)
___
*[LibOS/shim/src/sys/shim_file.c, line 415 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd5G2RCJla52ZNZzoB:-Mdd5G2RCJla52ZNZzoC:bpnv10j) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L415)):*
> ```C
>         }
> 
>         tmp_offset = hdli->fs->fs_ops->seek(hdli, *offset, SEEK_SET);
> ```

Why not just use `ret`?
___
*[LibOS/shim/src/sys/shim_file.c, line 426 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd5Vdb5UozGsKkgGwS:-Mdd5Vdb5UozGsKkgGwT:b-j12fi0) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L426)):*
> ```C
> 
>         ssize_t x;
>         while (true) {
> ```

What's the point of this loop? You can simple continue on outer loop...
___
*[LibOS/shim/src/sys/shim_file.c, line 429 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd66VZBzutc6mJUL8T:-Mdd66VZBzutc6mJUL8U:bjtlvm) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L429)):*
> ```C
>             x = hdli->fs->fs_ops->read(hdli, buf, to_copy);
>             if (x < 0) {
>                 if (x == -EINTR) {
> ```

Why do you skip `EINTR`s? We should return from syscall... (with EINTR or amount of bytes already copied).
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MddB4TSCyibJy2eosLV:-MddB4TT1nNtuLrDVmjP:b-jssjf6) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L449)):*
> ```C
>             if (y < 0) {
>                 if (y == -EINTR) {
>                     continue;
> ```

We cannot just ignore `EINTR`s. Seems that you just break on smaller writes - the same should be done on `EINTR`s


<!-- Sent from Reviewable.io -->

2021-07-05 07:49 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: 2 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/sys/shim_file.c, line 361 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd2H7u6R4WhggKLbEL:-MdpV3Q0235Jsdyzd9ck:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L361)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

While we are here, could you change these to some sane names? E.g. `out_fd` instead of `ofd`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_file.c, line 367 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd2QA-0Q_ZBUKKdSRJ:-MdpV47919qGlU_mZA7t:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L367)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (name), maybe `in_handle`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_file.c, line 392 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd32AQ2YmQXw58Kccc:-MdpVbaH46wC7ULvPOTB:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L392)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you just malloc it? I don't like the idea of creating big buffers on stack...
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_file.c, line 401 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd4wKe7BI_ddaNomQE:-Mdp_KHr0ywSyevmJOiy:b-pufgw9) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L401)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move it inside appropriate block.
</blockquote></details>

Done. Removed it actually.
___
*[LibOS/shim/src/sys/shim_file.c, line 415 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd5G2RCJla52ZNZzoB:-MdpVx5wD-bELz_84m6c:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L415)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not just use `ret`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_file.c, line 426 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd5Vdb5UozGsKkgGwS:-MdpW82e5lb3YMIyfQVD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L426)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's the point of this loop? You can simple continue on outer loop...
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_file.c, line 429 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd66VZBzutc6mJUL8T:-MdpW8OW5--WN4sgioKs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L429)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why do you skip `EINTR`s? We should return from syscall... (with EINTR or amount of bytes already copied).
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MddB4TSCyibJy2eosLV:-MdpZuCC4GAA1YWBWrGA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L449)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We cannot just ignore `EINTR`s. Seems that you just break on smaller writes - the same should be done on `EINTR`s
</blockquote></details>

Done.
___
*[LibOS/shim/test/ltp/ltp.cfg, line 1972 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdcXcmn9TGeigFc-x7C:-Mdp_GfH3T7wROSJhTXS:b-r6frak) ([raw file](https://github.com/oscarlab/graphene/blob/c25a0f4074254e4179895573f5f49a28871823c7/LibOS/shim/test/ltp/ltp.cfg#L1972)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`sendfile09` and `sendfile09_64` are quite slow (they create and then delete huge files) even in native execution. This is still far less than our default 30s timeout, but I should kick our Jenkins several times to make sure that these two do not timeout sometimes.
</blockquote></details>

Looks fine so resolving.


<!-- Sent from Reviewable.io -->

2021-07-05 13:24 UTC, pwmarcz requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_file.c, line 418 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqjzTU-cXpiTZ8o5g7:-MdqjzTU-cXpiTZ8o5g8:b-h6hkj6) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L418)):*
> ```C
>         }
> 
>         ret = in_hdl->fs->fs_ops->seek(in_hdl, *offset, SEEK_SET);
> ```

What if we use `read` on the file at the same time, in a different thread? I understand that Linux `sendfile` will not interfere with the offset it this case. Can you add a comment? 

(It might not be easy to fix right now, but later I want to make the read/write callbacks to take explicit offsets, which would fix that, I guess.)
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqnZzB-EPqvMAj7m2a:-MdqnZzC-0-oXoIQvmTi:b-5xyzrp) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L449)):*
> ```C
> 
>         if (y < x) {
>             /* written less bytes to output fd than read from input fd -> out of sync now; don't try
> ```

Just to understand it better: is it possible for `sendfile` to read more bytes than it has written, and advance the input handle by more than the output ones? That wasn't explicit in the manpage, but seems to follow.
___
*[LibOS/shim/src/sys/shim_file.c, line 463 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqnUO428JIWMFN-nSr:-MdqnUO428JIWMFN-nSs:b-gls5ei) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L463)):*
> ```C
> 
>         /* "...and the file offset will be updated by the call" */
>         *offset = *offset + copied;
> ```

If I'm right about the previous comment, `*offset` should be advanced by number of bytes read, not written (although the user won't notice the difference).


<!-- Sent from Reviewable.io -->

2021-07-05 15:55 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_file.c, line 429 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd66VZBzutc6mJUL8T:-MdrMXTP1ifjbYbzNXEc:b-obnotw) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L429)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If `x == -EINTR` we probably need to check if `copied != 0` and return `copied` if that's the case.
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MddB4TSCyibJy2eosLV:-MdrMmTk1N_jaHdqQNiO:b-n9sfey) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L449)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (this case is more complicated), we cannot return `-EINTR` if we've already wrote something
___
*[LibOS/shim/src/sys/shim_file.c, line 418 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqjzTU-cXpiTZ8o5g7:-MdrLh835dNZDq8Pj_yH:by909y4) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L418)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What if we use `read` on the file at the same time, in a different thread? I understand that Linux `sendfile` will not interfere with the offset it this case. Can you add a comment? 

(It might not be easy to fix right now, but later I want to make the read/write callbacks to take explicit offsets, which would fix that, I guess.)
</blockquote></details>

@pwmarcz Actually shouldn't we have some per handle lock and disallow concurrent reads from the same handle?
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqnZzB-EPqvMAj7m2a:-MdrN-ZgACyL71eDGx1l:b-imc2pc) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L449)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Just to understand it better: is it possible for `sendfile` to read more bytes than it has written, and advance the input handle by more than the output ones? That wasn't explicit in the manpage, but seems to follow.
</blockquote></details>

I don't think that's the case on normal Linux, I would expect that written bytes == read bytes, since Linux can do the copying sort of atomically.


<!-- Sent from Reviewable.io -->

2021-07-05 16:38 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/sys/shim_file.c, line 418 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqjzTU-cXpiTZ8o5g7:-MdrQ-x08atuAuoi-Dlw:bb7o0cg) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L418)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@pwmarcz Actually shouldn't we have some per handle lock and disallow concurrent reads from the same handle?
</blockquote></details>

I think we should. Right now we take `hdl->lock` in some `read` / `write` callbacks (I know about chroot fs). That's not very helpful, because it means `shim_do_sendfile`, which calls these, cannot take the same lock.

But the lock probably should be taken outside, in `shim_do_read` / `shim_do_write`. I'm not sure how feasible it is right now, though.

(As a matter of principle we should probably allow concurrent `pread` / `pwrite` / operations that don't modify the file offset. I doesn't look like we're ready for that, though!)
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqnZzB-EPqvMAj7m2a:-MdrSTFCBiULk6uwciEt:b-95j2sh) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L449)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think that's the case on normal Linux, I would expect that written bytes == read bytes, since Linux can do the copying sort of atomically.
</blockquote></details>

In that case, shouldn't we also emulate this behavior? That would either pretending we read only `copied` bytes (and correcting the position if we're supposed to move the handle), or writing the remaining part.

Otherwise, an application depending on "written bytes == read bytes" might skip over parts of the input file.


<!-- Sent from Reviewable.io -->

2021-07-05 16:44 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: 2 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/sys/shim_file.c, line 429 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd66VZBzutc6mJUL8T:-MdrPkjS0y5mEhkzGNNq:b-xfxip2) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L429)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

If `x == -EINTR` we probably need to check if `copied != 0` and return `copied` if that's the case.
</blockquote></details>

But that's what we do, check the logic under the `out` label.

Full disclosure: the current logic hides all failures if `copied != 0`. I took a look at the Linux code, but unfortunately it uses splicing and several different paths, so I didn't look into all the cases. But from my brief examination, Linux also hides errors as long as `copied != 0` (i.e., at least one bytes was written).
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-MddB4TSCyibJy2eosLV:-MdrPsoG0EkxSxF1ekur:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L449)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto (this case is more complicated), we cannot return `-EINTR` if we've already wrote something
</blockquote></details>

ditto
___
*[LibOS/shim/src/sys/shim_file.c, line 418 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqjzTU-cXpiTZ8o5g7:-MdrWN5F62q_AZSWJh0a:b-x9gsm7) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L418)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

@pwmarcz Actually shouldn't we have some per handle lock and disallow concurrent reads from the same handle?
</blockquote></details>

@pwmarcz Added a comment on this. A read callback with explicit offset will help in this code.

@boryspoplawski But we do have it. It's just that `sendfile()` may issue two `read` callbacks, and then another thread's `read` will interject, and `sendfile()` will send a "disjoint" data to the out FD. (Note that we cannot simply take a lock on `in_hdl` here since this will lead to a deadlock.)
___
*[LibOS/shim/src/sys/shim_file.c, line 449 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqnZzB-EPqvMAj7m2a:-MdrQTKK1_thsvXJqFEu:btbtwdc) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L449)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't think that's the case on normal Linux, I would expect that written bytes == read bytes, since Linux can do the copying sort of atomically.
</blockquote></details>

Yes, exactly, `sendfile` could read more bytes than written. From what I understand, technically `in_fd` may not support the seek operation, and thus there is no way to "revert" the read. (On the other hand, `in_fd` must support the mmap operation, so doesn't it mean that the seek operation will also be supported? The manpage is vague in this regard.)

Added a TODO for now. I don't want to spend more time analysing the Linux kernel implementation, since we wanted to merge this PR sooner than later.
___
*[LibOS/shim/src/sys/shim_file.c, line 463 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqnUO428JIWMFN-nSr:-MdrUg6e-EuTEtvGPIv_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L463)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If I'm right about the previous comment, `*offset` should be advanced by number of bytes read, not written (although the user won't notice the difference).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-05 17:00 UTC, pwmarcz approved these changes
> Reviewed 1 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-07-05 17:04 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/sys/shim_file.c, line 429 at r1](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdd66VZBzutc6mJUL8T:-Mdr_8Y85QBS60fXrv_I:bhgseje) ([raw file](https://github.com/oscarlab/graphene/blob/18aef799db649d10e07f000ef6ff041ccd98e04d/LibOS/shim/src/sys/shim_file.c#L429)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But that's what we do, check the logic under the `out` label.

Full disclosure: the current logic hides all failures if `copied != 0`. I took a look at the Linux code, but unfortunately it uses splicing and several different paths, so I didn't look into all the cases. But from my brief examination, Linux also hides errors as long as `copied != 0` (i.e., at least one bytes was written).
</blockquote></details>

Oh, sorry, I've missed that `if` in the `return` statement.
___
*[LibOS/shim/src/sys/shim_file.c, line 418 at r2](https://reviewable.io/reviews/oscarlab/graphene/2500#-MdqjzTU-cXpiTZ8o5g7:-MdrZntz75Ycjz4IHMXM:b-qje6gn) ([raw file](https://github.com/oscarlab/graphene/blob/af5c0f074fc612b554fa3a2eb53d2ffa5e29e94f/LibOS/shim/src/sys/shim_file.c#L418)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@pwmarcz Added a comment on this. A read callback with explicit offset will help in this code.

@boryspoplawski But we do have it. It's just that `sendfile()` may issue two `read` callbacks, and then another thread's `read` will interject, and `sendfile()` will send a "disjoint" data to the out FD. (Note that we cannot simply take a lock on `in_hdl` here since this will lead to a deadlock.)
</blockquote></details>

I meant locks in LibOS syscall wrappers not inside specific fs callbacks or PALs.
___
*[LibOS/shim/src/sys/shim_file.c, line 459 at r3](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdrc8u0AEUhg0ByGyl6:-Mdrc8u0AEUhg0ByGyl7:b2scx55) ([raw file](https://github.com/oscarlab/graphene/blob/edf34cd86c76fdd59daefc064e6650f6dea99307/LibOS/shim/src/sys/shim_file.c#L459)):*
> ```C
>             /* written less bytes to output fd than read from input fd -> out of sync now; don't try
>              * to be smart and simply return however many bytes we copied_to_out up until now */
>             /* TODO: need to revert in_fd's file position to (read_from_in - x + y) from original
> ```

I don't like the current solution, but fixing this would be complicated.


<!-- Sent from Reviewable.io -->

2021-07-05 17:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdrd8Je-0EQRhBQ3_W1:-Mdrd8Je-0EQRhBQ3_W2:bhl5yze) (no related file):*
At rebase, I'll drop `correct and robust` from the commit message since the current version has too many TODOs. I'll replace with `simple and minimal`.

---
___
*[LibOS/shim/src/sys/shim_file.c, line 459 at r3](https://reviewable.io/reviews/oscarlab/graphene/2500#-Mdrc8u0AEUhg0ByGyl6:-MdrczOAEmql64DYoj1K:bbu8n6) ([raw file](https://github.com/oscarlab/graphene/blob/edf34cd86c76fdd59daefc064e6650f6dea99307/LibOS/shim/src/sys/shim_file.c#L459)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't like the current solution, but fixing this would be complicated.
</blockquote></details>

I actually dislike this myself now :) Well, let's start small and then remove all these limitations.


<!-- Sent from Reviewable.io -->

2021-07-06 09:02 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-07-06 15:31 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2500)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-06 18:37 UTC, merged