[Docs] Add note on adding `/usr/local/bin` to `PATH` envvar
oscarlab/graphene pull request #2509
Opened 2021-07-05 17:14 UTC by dimakuv

## Description of the changes 

When installed from sources, Graphene is put under `/usr/local/bin`. However, some Linux distros (notably CentOS) do not allow running apps from this directory, so users must manually add this directory to the `PATH` environment variable.

This PR adds a note on this in our documentation.

## How to test this PR? 

N/A.

2021-07-07 00:30 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2509)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyLOi3EG54YQfseq9o:-MdyLOi3EG54YQfseq9p:b-ubis2a) (no related file):*
> do not allow running apps from this directory

That's not true, they just don't put this into PATH by default. You can still run them using the full path.

The text you put in the docs is actually correct, so I guess it's just the commit message containing some older version of the text.

---
___
*[Documentation/building.rst, line 181 at r1](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyLu-0AZkM1sZkplf9:-MdyLu-0AZkM1sZkplfA:b6wforo) ([raw file](https://github.com/oscarlab/graphene/blob/96fb1dfb90acb30df8a14fd0e6424cfadb249a4a/Documentation/building.rst#L181)):*
> ```
> in the ``PATH``
> ```
I think it should be without "the"? (it's a proper name)
___
*[Documentation/quickstart.rst, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyMd0fEa5tK-iQeRP4:-MdyMd0fEa5tK-iQeRP5:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/96fb1dfb90acb30df8a14fd0e6424cfadb249a4a/Documentation/quickstart.rst#L12)):*
> ```reStructuredText
>    for executables under this path. If your system reports that Graphene
>    programs can not be found, you might need to edit your configuration files so
>    that ``/usr/local/bin`` is in your path (in the ``PATH`` environment
> ```

ditto
___
*[Documentation/quickstart.rst, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyMEYu517CyQA6B6Mz:-MdyMEYu517CyQA6B6N-:b-65x9vi) ([raw file](https://github.com/oscarlab/graphene/blob/96fb1dfb90acb30df8a14fd0e6424cfadb249a4a/Documentation/quickstart.rst#L13)):*
> ```reStructuredText
>    programs can not be found, you might need to edit your configuration files so
>    that ``/usr/local/bin`` is in your path (in the ``PATH`` environment
>    variable).
> ```

Now this whole page start with this CentOS-specific note. Could you move it down a bit to the first place where it's actually relevant? I think this would be after the first snippet mentioning `graphene-direct`?


<!-- Sent from Reviewable.io -->

2021-07-07 06:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2509)* status: 0 of 2 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyLOi3EG54YQfseq9o:-MdzjqLJDvZiiJj-0Ore:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> do not allow running apps from this directory

That's not true, they just don't put this into PATH by default. You can still run them using the full path.

The text you put in the docs is actually correct, so I guess it's just the commit message containing some older version of the text.
</blockquote></details>

Done.

---
___
*[Documentation/building.rst, line 181 at r1](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyLu-0AZkM1sZkplf9:-MdzispLCTjvTGTlbcAO:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96fb1dfb90acb30df8a14fd0e6424cfadb249a4a/Documentation/building.rst#L181)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> in the ``PATH``
> ```
I think it should be without "the"? (it's a proper name)
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyMd0fEa5tK-iQeRP4:-MdzixYc3d4j3fgqMu6h:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/96fb1dfb90acb30df8a14fd0e6424cfadb249a4a/Documentation/quickstart.rst#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Documentation/quickstart.rst, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyMEYu517CyQA6B6Mz:-MdzjNQv6fy7A4ryCtOC:b-1n593k) ([raw file](https://github.com/oscarlab/graphene/blob/96fb1dfb90acb30df8a14fd0e6424cfadb249a4a/Documentation/quickstart.rst#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now this whole page start with this CentOS-specific note. Could you move it down a bit to the first place where it's actually relevant? I think this would be after the first snippet mentioning `graphene-direct`?
</blockquote></details>

Done. I didn't want to add this note close to `graphene-direct` because we have two separate sections: one for non-SGX build and one for SGX build. People tend to read one of these sections, ignoring the other. So I should have added this note to both sections, but this sounds like an overkill.

So I added a new section `Troubleshooting` and put this note there.


<!-- Sent from Reviewable.io -->

2021-07-07 14:05 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2509)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[Documentation/quickstart.rst, line 13 at r1](https://reviewable.io/reviews/oscarlab/graphene/2509#-MdyMEYu517CyQA6B6Mz:-Me0Gu62Cw-H0ZO3OLNT:b-hfghm4) ([raw file](https://github.com/oscarlab/graphene/blob/96fb1dfb90acb30df8a14fd0e6424cfadb249a4a/Documentation/quickstart.rst#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. I didn't want to add this note close to `graphene-direct` because we have two separate sections: one for non-SGX build and one for SGX build. People tend to read one of these sections, ignoring the other. So I should have added this note to both sections, but this sounds like an overkill.

So I added a new section `Troubleshooting` and put this note there.
</blockquote></details>

Sounds good


<!-- Sent from Reviewable.io -->

2021-07-12 10:49 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2509)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-12 11:25 UTC, merged