[LibOS] Make POSIX locks interruptible
oscarlab/graphene pull request #2522
Opened 2021-07-08 11:00 UTC by pwmarcz

Draft because I want to check Jenkins first.

## Description of the changes 

This makes it possible for POSIX locks (`F_SETLKW`) to return `-EINTR` when interrupted, e.g. after receiving a signal from `alarm()`. See #2517 for design discussion. 

Fixes #2510.

## How to test this PR? 

* I added some test cases to `fcntl_lock`
* The `stress-ng` lockf test should no longer hang (see #2510)
* LTP `fcntl16` test is reenabled (the test depends on being able to interrupt a lock request, unfortunately it's racy and the interrupt is not always necessary)

2021-07-09 09:15 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2522)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9J9kmCnnSNtrOGWQ9:-Me9J9kn1Ly13Y1zAVqB:b-ofgp2l) (no related file):*
Can you amend your commit to have the text from the PR description? Sounds very helpful in understanding what this commit resolves.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9YAmI01dp0t5J1qxR:-Me9YAmI01dp0t5J1qxS:b90k7ok) (no related file):*
I found this change very readable. I definitely like this Option 4.

---
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 517 at r1](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9Ssf-9a0kfgdGUdoW:-Me9Ssf02H4iadT3nD9s:b-ebki6s) ([raw file](https://github.com/oscarlab/graphene/blob/f9d9631e174ab5bd10bf5d08e2e28832f71d6072/LibOS/shim/src/fs/shim_fs_lock.c#L517)):*
> ```C
>          * -EINTR. Either way, we delete the request.
>          */
>         ret = req->resolved ? req->result : -EINTR;
> ```

But `ret` could be something other than "interrupted" (if `DkEventWait` failed in a weird way). I would expect to return this error then, or have `die_or_inf_loop()` after the message "unexpected error from DkEventWait".
___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9X-VA1fvqsMkUsqXF:-Me9X-VA1fvqsMkUsqXG:b-6odcw8) ([raw file](https://github.com/oscarlab/graphene/blob/f9d9631e174ab5bd10bf5d08e2e28832f71d6072/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L54)):*
> ```C
>     void* data;
>     int ret = ipc_send_msg_and_get_response_with_cancel(
>         g_process_ipc_ids.leader_vmid, msg, &cancel_posix_lock, msg, &data);
> ```

I first wanted to suggest that only `F_SETLKW` uses this `with_cancel` version, but then I noticed that the man page allows `EINTR` even for `F_SETLK`/`F_GETLK`. So you are correct here.
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 458 at r1](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9Xraf8z0ecDXlghHH:-Me9Xrag54HINzZasRhM:b-gfkx6) ([raw file](https://github.com/oscarlab/graphene/blob/f9d9631e174ab5bd10bf5d08e2e28832f71d6072/LibOS/shim/test/regression/fcntl_lock.c#L458)):*
> ```C
> 
>     if (pid == 0) {
>         lock(F_RDLCK, 0, 100);
> ```

Why not `F_WRLCK`? Just to cover more cases?


<!-- Sent from Reviewable.io -->

2021-07-09 09:53 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2522)* status: 8 of 9 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9J9kmCnnSNtrOGWQ9:-Me9apx019wSvCj76RY_:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you amend your commit to have the text from the PR description? Sounds very helpful in understanding what this commit resolves.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 517 at r1](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9Ssf-9a0kfgdGUdoW:-Me9au9a6xCkC922FO88:blegylc) ([raw file](https://github.com/oscarlab/graphene/blob/f9d9631e174ab5bd10bf5d08e2e28832f71d6072/LibOS/shim/src/fs/shim_fs_lock.c#L517)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But `ret` could be something other than "interrupted" (if `DkEventWait` failed in a weird way). I would expect to return this error then, or have `die_or_inf_loop()` after the message "unexpected error from DkEventWait".
</blockquote></details>

This is a race: if `DkEventWait` failed in a weird way, the lock operation still might have finished with success, in which case returning something else than 0 would be very confusing for the user. That's why I didn't want to return the error from `DkEventWait`.

Do you think `die_or_inf_loop()` is a good solution here? I did not want to do that either, because a failed wait shouldn't have any impact on *correctness* of the lock operation, so I don't think it should be a fatal error.

Another solution would be to return the error from `DkEventWait`, but *only* if the operation has not finished yet (i.e. `ret = req->resolved ? req->result : ret_from_wait`). I'm not sure if that's useful, though.
___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 54 at r1](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9X-VA1fvqsMkUsqXF:-Me9df7B6zU2OJKe6b9g:blg7pbk) ([raw file](https://github.com/oscarlab/graphene/blob/f9d9631e174ab5bd10bf5d08e2e28832f71d6072/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I first wanted to suggest that only `F_SETLKW` uses this `with_cancel` version, but then I noticed that the man page allows `EINTR` even for `F_SETLK`/`F_GETLK`. So you are correct here.
</blockquote></details>

Graphene won't fail with `EINTR` on these, though. We will send the cancel request, but it will not find any pending operation, so the original requests will proceed. The same will happen for `F_SETLKW` for a lock that can be granted immediately.
___
*[LibOS/shim/test/regression/fcntl_lock.c, line 458 at r1](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9Xraf8z0ecDXlghHH:-Me9eacI1m213e_H9Anq:b82vqg) ([raw file](https://github.com/oscarlab/graphene/blob/f9d9631e174ab5bd10bf5d08e2e28832f71d6072/LibOS/shim/test/regression/fcntl_lock.c#L458)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not `F_WRLCK`? Just to cover more cases?
</blockquote></details>

Oh, I can do `F_WRLCK`, same as in the other "eitr" test. Changed.

I'm not very consistent with these, though; some other tests check `F_RDLCK` vs. `F_WRLCK`.


<!-- Sent from Reviewable.io -->

2021-07-09 14:53 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2522)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[LibOS/shim/src/fs/shim_fs_lock.c, line 517 at r1](https://reviewable.io/reviews/oscarlab/graphene/2522#-Me9Ssf-9a0kfgdGUdoW:-MeAkB9X-IA1qG7UGTb5:b-88dhlt) ([raw file](https://github.com/oscarlab/graphene/blob/f9d9631e174ab5bd10bf5d08e2e28832f71d6072/LibOS/shim/src/fs/shim_fs_lock.c#L517)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is a race: if `DkEventWait` failed in a weird way, the lock operation still might have finished with success, in which case returning something else than 0 would be very confusing for the user. That's why I didn't want to return the error from `DkEventWait`.

Do you think `die_or_inf_loop()` is a good solution here? I did not want to do that either, because a failed wait shouldn't have any impact on *correctness* of the lock operation, so I don't think it should be a fatal error.

Another solution would be to return the error from `DkEventWait`, but *only* if the operation has not finished yet (i.e. `ret = req->resolved ? req->result : ret_from_wait`). I'm not sure if that's useful, though.
</blockquote></details>

OK, understood your point. Given that it shouldn't happen in practice, and we have a log warning for this case, I'm resolving.


<!-- Sent from Reviewable.io -->

2021-07-19 11:26 UTC, pwmarcz commented
Closing as @boryspoplawski (https://github.com/oscarlab/graphene/issues/2517#issuecomment-877881232) wants not to use IPC responses for this. I'll be trying to rewrite this subsystem (and think how it ties with the sync engine).

2021-07-19 11:26 UTC, closed without merging