[LibOS] Make Graphene internal IDs managed by LibOS
oscarlab/graphene pull request #2526
Opened 2021-07-09 05:59 UTC by boryspoplawski

## Description of the changes 
Previously Graphene internal IDs were just equal to host PIDs, which was a security issue on SGX PAL.

2021-07-09 06:02 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: 0 of 25 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2526#-Me8qvyhE1chbkCOdiro:-Me8qvyhE1chbkCOdirp:b-72oie8) (no related file):*
Requires #2525 being merged before.

---


<!-- Sent from Reviewable.io -->

2021-07-12 16:25 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: 0 of 25 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2526#-Me8qvyhE1chbkCOdiro:-MeQXNpXAe_0rUedkrdC:byotcgg) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Requires #2525 being merged before.
</blockquote></details>

Ready.

---


<!-- Sent from Reviewable.io -->

2021-07-13 07:31 UTC, dimakuv requested changes
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlb-D1a6izvbTcAi6:-MeTlb-D1a6izvbTcAi7:b-vr8gww) (no related file):*
It's gonna be much harder to compare strace logs and Graphene debug logs with this change :)

---
___
*[LibOS/shim/src/shim_checkpoint.c, line 565 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeThdwOBgsEjtKOFy9O:-MeThdwOBgsEjtKOFy9P:b-nrn5ev) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/shim_checkpoint.c#L565)):*
> ```C
>     /* wait for final ack from child process (contains VMID of child) */
>     IDTYPE child_vmid = 0;
>     ret = read_exact(pal_process, &child_vmid, sizeof(child_vmid));
> ```

This read from the child is a bit useless now (only used for synchronization between parent and child; `child_vmid` is unused other than in the error message).

Since this synchronization is important to keep, maybe we should simply add a sanity check here? Like this:
```
if (child_vmid != child_process->vmid) {
    log_error("child process acked with an unexpected vmid, something went terribly wrong");
    ret = -...;
    goto out;
}
```
___
*[LibOS/shim/src/shim_init.c, line 467 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTiIodCAycqRiTs71x:-MeTiIodCAycqRiTs71y:bdecll1) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/shim_init.c#L467)):*
> ```C
>         }
> 
>         /* Notify the parent process */
> ```

Maybe append smth like `...; send back the same vmid as received from parent, for sanity checking`

Otherwise future readers may be confused, why we're sending a useless `child_vmid`.
___
*[LibOS/shim/src/ipc/shim_ipc_vmid.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlL1Y0uvDLzPK-3hq:-MeTlL1Y0uvDLzPK-3hr:b-m81lg2) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/ipc/shim_ipc_vmid.c#L25)):*
> ```C
> 
>     size_t msg_size = get_ipc_msg_size(0);
>     struct shim_ipc_msg* msg = malloc(msg_size);
> ```

Why do you sometimes use `__alloca` and sometimes `malloc`? Can you allocate on the stack here, that would be simpler?
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTipLu7CnPlFOisfH-:-MeTipLv-IzBTv5I-Rfj:b8sba0n) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/ipc/shim_ipc_worker.c#L49)):*
> ```C
> static ipc_callback ipc_callbacks[] = {
>     [IPC_MSG_RESP]              = ipc_response_callback,
>     [IPC_MSG_GET_VMID]          = ipc_get_new_vmid_callback,
> ```

Can we rename to more specific `IPC_MSG_GET_NEW_VMID`?


<!-- Sent from Reviewable.io -->

2021-07-13 21:11 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlb-D1a6izvbTcAi6:-MeWeC_dDEz67-vh1VeX:b-5t0ci6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's gonna be much harder to compare strace logs and Graphene debug logs with this change :)
</blockquote></details>

Which part makes it harder?

---
___
*[LibOS/shim/src/shim_checkpoint.c, line 565 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeThdwOBgsEjtKOFy9O:-MeWel_Z4ospAvPWLcUy:bleeyc6) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/shim_checkpoint.c#L565)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This read from the child is a bit useless now (only used for synchronization between parent and child; `child_vmid` is unused other than in the error message).

Since this synchronization is important to keep, maybe we should simply add a sanity check here? Like this:
```
if (child_vmid != child_process->vmid) {
    log_error("child process acked with an unexpected vmid, something went terribly wrong");
    ret = -...;
    goto out;
}
```
</blockquote></details>

I tried to get rid of this synchronization and do something simpler, but couldn't find a way, so I've left what we have now (even tho it seems unnecessarily complicated).
I've changed this to just a simple byte sending.
___
*[LibOS/shim/src/shim_init.c, line 467 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTiIodCAycqRiTs71x:-MeWgMNYEspYF6jWg21L:bss4a2b) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/shim_init.c#L467)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe append smth like `...; send back the same vmid as received from parent, for sanity checking`

Otherwise future readers may be confused, why we're sending a useless `child_vmid`.
</blockquote></details>

Removed.
___
*[LibOS/shim/src/ipc/shim_ipc_vmid.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlL1Y0uvDLzPK-3hq:-MeWgSYT4yF6TtunZcz4:b-ai3afx) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/ipc/shim_ipc_vmid.c#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you sometimes use `__alloca` and sometimes `malloc`? Can you allocate on the stack here, that would be simpler?
</blockquote></details>

I use `malloc` wherever I can and `__alloca` in IPC worker thread callbacks to have one less point of failure (OOM) as there should be enough stack for this simple message.
___
*[LibOS/shim/src/ipc/shim_ipc_worker.c, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTipLu7CnPlFOisfH-:-MeWhOm-0R3XjDH4SJRn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/ipc/shim_ipc_worker.c#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename to more specific `IPC_MSG_GET_NEW_VMID`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-14 05:31 UTC, dimakuv approved these changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlb-D1a6izvbTcAi6:-MeYU8EhBMAaM7B_chpF:bqwjzzq) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Which part makes it harder?
</blockquote></details>

I used to do `log_level = "all"` and `strace -ff graphene-direct myapp`. This gave me both Graphene logs and strace logs at the same time. Since both printed out the same PIDs, it was easy to collate the two.

Now it will be one more mental indirection: Graphene-log PIDs are different from strace ones.

That's not a problem, just a side note.

---
___
*[LibOS/shim/src/ipc/shim_ipc_vmid.c, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlL1Y0uvDLzPK-3hq:-MeYUoJN7vpRJwTGK4ra:b-y5o3si) ([raw file](https://github.com/oscarlab/graphene/blob/f79f7ed5b2538b55a814f01dbafe47b4ec673cea/LibOS/shim/src/ipc/shim_ipc_vmid.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I use `malloc` wherever I can and `__alloca` in IPC worker thread callbacks to have one less point of failure (OOM) as there should be enough stack for this simple message.
</blockquote></details>

OK, I see your logic now.


<!-- Sent from Reviewable.io -->

2021-07-14 09:08 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlb-D1a6izvbTcAi6:-MeZDmdd63AD7jHveH2u:bwvww9o) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I used to do `log_level = "all"` and `strace -ff graphene-direct myapp`. This gave me both Graphene logs and strace logs at the same time. Since both printed out the same PIDs, it was easy to collate the two.

Now it will be one more mental indirection: Graphene-log PIDs are different from strace ones.

That's not a problem, just a side note.
</blockquote></details>

I see.
Well, I've never done that myself, I guess it's a matter of ones approach to debugging Graphene ;)
If that was useful to you, maybe we can modify this PR to still save host-level pid in some PAL internal structure and add it to log printing (e.g. use prefix `[host_level_pid:VMID:app_pid:exec_name]`)

---


<!-- Sent from Reviewable.io -->

2021-07-14 09:17 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeTlb-D1a6izvbTcAi6:-MeZIQh-4xH3Y4h2UhI7:b-qvzadi) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I see.
Well, I've never done that myself, I guess it's a matter of ones approach to debugging Graphene ;)
If that was useful to you, maybe we can modify this PR to still save host-level pid in some PAL internal structure and add it to log printing (e.g. use prefix `[host_level_pid:VMID:app_pid:exec_name]`)
</blockquote></details>

No, I don't care. That was just a side note.

---


<!-- Sent from Reviewable.io -->

2021-07-14 09:17 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-07-14 12:42 UTC, mkow approved these changes
> Reviewed 20 of 25 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/ipc/shim_ipc_vmid.c, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeZzKS99ORlERPFSBEc:-MeZzKS99ORlERPFSBEd:bm3t2gp) ([raw file](https://github.com/oscarlab/graphene/blob/6d4a1fe2e9cd2f944eccc294f4d888a99b3a03b0/LibOS/shim/src/ipc/shim_ipc_vmid.c#L15)):*
> ```C
> 
> static IDTYPE get_next_vmid(void) {
>     return __atomic_add_fetch(&g_last_vmid, 1, __ATOMIC_ACQ_REL);
> ```

nitpick: I think we don't need any ordering here? We just pick a unique ID from this variable, but this is independent from all other stuff.


<!-- Sent from Reviewable.io -->

2021-07-14 13:45 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: 24 of 25 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/ipc/shim_ipc_vmid.c, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeZzKS99ORlERPFSBEc:-Me_Fn4J9sDfJyo4NjL1:b-o4d27i) ([raw file](https://github.com/oscarlab/graphene/blob/6d4a1fe2e9cd2f944eccc294f4d888a99b3a03b0/LibOS/shim/src/ipc/shim_ipc_vmid.c#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nitpick: I think we don't need any ordering here? We just pick a unique ID from this variable, but this is independent from all other stuff.
</blockquote></details>

We do not, I even had a TODO in my notes to fix thix, but too many things happening at once and forgot...


<!-- Sent from Reviewable.io -->

2021-07-14 13:50 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-14 14:07 UTC, merged

2021-07-14 14:13 UTC, mkow reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2526)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/ipc/shim_ipc_vmid.c, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2526#-MeZzKS99ORlERPFSBEc:-Me_MC9bCeKvQlYaFoxK:b32vhw) ([raw file](https://github.com/oscarlab/graphene/blob/6d4a1fe2e9cd2f944eccc294f4d888a99b3a03b0/LibOS/shim/src/ipc/shim_ipc_vmid.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We do not, I even had a TODO in my notes to fix thix, but too many things happening at once and forgot...
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->