[Examples] Adding TensorFlow examples - ResNet50 and BERT models
oscarlab/graphene pull request #2530
Opened 2021-07-12 11:20 UTC by Satya1493

Signed-off-by: Satya <satyanaraya.illa@intel.com>

## Description of the changes 
TensorFlow examples for ResNet50 and BERT models. The samples run inference using pre-trained models.

## How to test this PR? 
Please follow steps present at Examples/tensorflow/README.md

2021-07-13 07:50 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @Satya1493)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTmZkD9Ko5CCXW9ItU:-MeTmZkE3OzRO4lBICxX:b-278c01) (no related file):*
There are currently two commits. From what I understand, the second commit is supposed to be a fixup to the first commit. So during rebase, these two commits should be merged into one.

---
___
*[Examples/tensorflow/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTn-vF6OLZmMIc1yQW:-MeTn-vGDMAp61X33Lx1:bqzhynf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L1)):*
> ```Markdown
> ## Run inference on TensorFlow BERT and ResNet50 models
> ```

Could you re-wrap this file to 100 characters per line? Hard to read.
___
*[Examples/tensorflow/README.md, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTp05X52JrIPlxgLsp:-MeTp05X52JrIPlxgLsq:beo6hq7) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L2)):*
> ```Markdown
> ## Run inference on TensorFlow BERT and ResNet50 models
> This directory contains steps and artifacts to run inference with TensorFlow BERT and ResNet50 sample workloads on Graphene. Specifically, both these examples use pre-trained models to run inference. We tested this on Ubuntu 18.04 and uses the package version of Python 3.6.
> ```

`and uses the package version of Python 3.6` -> `with Python 3.6`
___
*[Examples/tensorflow/README.md, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTp76yA46vGk8Pbx99:-MeTp76yA46vGk8Pbx9A:b-nr3l9b) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L2)):*
> ```Markdown
> ## Run inference on TensorFlow BERT and ResNet50 models
> This directory contains steps and artifacts to run inference with TensorFlow BERT and ResNet50 sample workloads on Graphene. Specifically, both these examples use pre-trained models to run inference. We tested this on Ubuntu 18.04 and uses the package version of Python 3.6.
> ```

Could you give a sentence each about BERT and ResNet50?
___
*[Examples/tensorflow/README.md, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTnImh6JUfK_dP051l:-MeTnImh6JUfK_dP051m:b-jzmrg7) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L24)):*
> ```Markdown
> ## Run inference on BERT model
> - To run int8 inference on graphene-sgx(SGX version)<br>
> ``KMP_BLOCKTIME=1 KMP_SETTINGS=1 OMP_NUM_THREADS=36 KMP_AFFINITY=granularity=fine,verbose,compact,1,0 taskset -c 0-35 graphene-sgx ./python models/models/language_modeling/tensorflow/bert_large/inference/run_squad.py --init_checkpoint=data/bert_large_checkpoints/model.ckpt-3649 --vocab_file=data/wwm_uncased_L-24_H-1024_A-16/vocab.txt --bert_config_file=data/wwm_uncased_L-24_H-1024_A-16/bert_config.json --predict_file=data/wwm_uncased_L-24_H-1024_A-16/dev-v1.1.json --precision=int8 --output_dir=output/bert-squad-output --predict_batch_size=32 --experimental_gelu=True --optimized_softmax=True --input_graph=data/asymmetric_per_channel_bert_int8.pb --do_predict=True --mode=benchmark --inter_op_parallelism_threads=1 --intra_op_parallelism_threads=36``
> ```

Could you split this huge line into multiple lines? This is unreadable.

Like this:
```
KMP_BLOCKTIME=1 KMP_SETTINGS=1 KMP_AFFINITY=granularity=fine,verbose,compact,1,0 \
OMP_NUM_THREADS=36 taskset -c 0-35 \
graphene-sgx ./python \
... and so on ...
```

Same for everything here.
___
*[Examples/tensorflow/README.md, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeToHjDDUEeroSMqyTK:-MeToHjDDUEeroSMqyTL:bb919je) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L24)):*
> ```Markdown
> ## Run inference on BERT model
> - To run int8 inference on graphene-sgx(SGX version)<br>
> ``KMP_BLOCKTIME=1 KMP_SETTINGS=1 OMP_NUM_THREADS=36 KMP_AFFINITY=granularity=fine,verbose,compact,1,0 taskset -c 0-35 graphene-sgx ./python models/models/language_modeling/tensorflow/bert_large/inference/run_squad.py --init_checkpoint=data/bert_large_checkpoints/model.ckpt-3649 --vocab_file=data/wwm_uncased_L-24_H-1024_A-16/vocab.txt --bert_config_file=data/wwm_uncased_L-24_H-1024_A-16/bert_config.json --predict_file=data/wwm_uncased_L-24_H-1024_A-16/dev-v1.1.json --precision=int8 --output_dir=output/bert-squad-output --predict_batch_size=32 --experimental_gelu=True --optimized_softmax=True --input_graph=data/asymmetric_per_channel_bert_int8.pb --do_predict=True --mode=benchmark --inter_op_parallelism_threads=1 --intra_op_parallelism_threads=36``
> ```

What are all these magic options? Please describe them. Do we really need to specify them all?
___
*[Examples/tensorflow/README.md, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeToE3C0ZryAvXsgCQT:-MeToE3C0ZryAvXsgCQU:b-milz0z) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L30)):*
> ```Markdown
> ``KMP_BLOCKTIME=1 KMP_SETTINGS=1 OMP_NUM_THREADS=36 KMP_AFFINITY=granularity=fine,verbose,compact,1,0 taskset -c 0-35 python3.6 models/models/language_modeling/tensorflow/bert_large/inference/run_squad.py --init_checkpoint=data/bert_large_checkpoints/model.ckpt-3649 --vocab_file=data/wwm_uncased_L-24_H-1024_A-16/vocab.txt --bert_config_file=data/wwm_uncased_L-24_H-1024_A-16/bert_config.json --predict_file=data/wwm_uncased_L-24_H-1024_A-16/dev-v1.1.json --precision=int8 --output_dir=output/bert-squad-output --predict_batch_size=32 --experimental_gelu=True --optimized_softmax=True --input_graph=data/asymmetric_per_channel_bert_int8.pb --do_predict=True  --mode=benchmark --inter_op_parallelism_threads=1 --intra_op_parallelism_threads=36``
> - Above commands are for a 36 core system. Please set the following options accordingly for optimal performance.
> 	- OMP_NUM_THREADS='Core(s) per socket'
> ```

Please replace all tabs with spaces.
___
*[Examples/tensorflow/README.md, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTo6dG6HDzTkBBXLWs:-MeTo6dG6HDzTkBBXLWt:bhylhp7) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L36)):*
> ```Markdown
> 
> ## Run inference on ResNet50 model
> - To run inference on graphene-sgx(SGX version)<br>
> ```

What are these `<br>` HTML tags? They are not needed in Markdown.
___
*[Examples/tensorflow/README.md, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTns4n5bBmnyehAHRU:-MeTns4n5bBmnyehAHRV:bc1cw1s) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L48)):*
> ```Markdown
> >**NOTE** To get 'Core(s) per socket', do ``lscpu | grep 'Core(s) per socket'``
> 
> # GSC :
> ```

I don't think we should have this in our `Examples/` directory. This should belong to GSC examples/tests. I would suggest to remove this GSC part completely from this PR, and then later submit a separate PR on this.
___
*[Examples/tensorflow/README.md, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTnoO13OP92eUE8b9u:-MeTnoO13OP92eUE8b9v:b-8parg8) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L60)):*
> ```Markdown
> 4. Build docker image :
>     - ``cd test``
>     - ``docker build --rm -t ubuntu18.04-tensorflow-bert -f ubuntu18.04-tensorflow-bert.dockerfile ../../../Exa [...]

2021-07-15 08:04 UTC, Satya1493 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 3 of 7 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTn-vF6OLZmMIc1yQW:-Med5rnHAJ94dGt5xivB:bb6un1j) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you re-wrap this file to 100 characters per line? Hard to read.
</blockquote></details>

Done
___
*[Examples/tensorflow/README.md, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTp05X52JrIPlxgLsp:-Med62LTCFEsLpk02Xpr:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`and uses the package version of Python 3.6` -> `with Python 3.6`
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTp76yA46vGk8Pbx99:-Med63j5D1mrDHEQgMwp:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you give a sentence each about BERT and ResNet50?
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTnImh6JUfK_dP051l:-Med67wu7C6Wp7u8fblB:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you split this huge line into multiple lines? This is unreadable.

Like this:
```
KMP_BLOCKTIME=1 KMP_SETTINGS=1 KMP_AFFINITY=granularity=fine,verbose,compact,1,0 \
OMP_NUM_THREADS=36 taskset -c 0-35 \
graphene-sgx ./python \
... and so on ...
```

Same for everything here.
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeToHjDDUEeroSMqyTK:-Med69Rx3Cd0OgFL60G-:b5qp714) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What are all these magic options? Please describe them. Do we really need to specify them all?
</blockquote></details>

Removed KMP_BLOCKTIME and KMP_SETTINGS now as they are default values anyway. Added a one line description about OMP_NUM_THREADS and KMP_AFFINITY.
___
*[Examples/tensorflow/README.md, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeToE3C0ZryAvXsgCQT:-Med763p0aS8Fb0uJl9s:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace all tabs with spaces.
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTo6dG6HDzTkBBXLWs:-Med78VgCKmH8D0OnAv-:b-n48fm3) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What are these `<br>` HTML tags? They are not needed in Markdown.
</blockquote></details>

<br> also does line breaks. But yeah, its ugly while reading. Removed them now.
___
*[Examples/tensorflow/README.md, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTns4n5bBmnyehAHRU:-Med7T4D-iDMCFESGYqk:b-ert2jv) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think we should have this in our `Examples/` directory. This should belong to GSC examples/tests. I would suggest to remove this GSC part completely from this PR, and then later submit a separate PR on this.
</blockquote></details>

Yeah, removed GSC section. Will push another PR for GSC.
___
*[Examples/tensorflow/README.md, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTnoO13OP92eUE8b9u:-Med7WJJDVD5pMzW7irI:b-gkuk6o) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `ubuntu18.04-tensorflow-bert.dockerfile`?
</blockquote></details>

This is GSC related file, will push another PR for GSC.
___
*[Examples/tensorflow/BERT/python.manifest.template, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTpDgL49M1yV8Injvq:-Med8C4d-70ieZYflPfo:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/BERT/python.manifest.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`layout`
</blockquote></details>

done
___
*[Examples/tensorflow/BERT/python.manifest.template, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTpQec1VxMK1ui7mhy:-Med8EOn89nktN9V2mU1:bz0un9z) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/BERT/python.manifest.template#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are these two last files needed? I think they are already "covered" by `arch_libdir` and `usr_arch_libdir`
</blockquote></details>

Removed them now.
___
*[Examples/tensorflow/BERT/python.manifest.template, line 70 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTpXjd3jwbjJSwSe8_:-Med8JHvEIqZ0lXKEu7P:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/BERT/python.manifest.template#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This manifest option is not present in Graphene anymore. Please just remove it.
</blockquote></details>

done
___
*[Examples/tensorflow/BERT/python.manifest.template, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTpdag7ttIxBJE9fTl:-Med8K7C4Y0lrvd057KU:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/BERT/python.manifest.template#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just have `sgx.allowed_files.models = "file:models/` ?
</blockquote></details>

done
___
*[Examples/tensorflow/BERT/python.manifest.template, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTpvtb2znbstRoLU1L:-Med8N4TEW5_V1B6cbk6:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/BERT/python.manifest.template#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not have these four as `sgx.trusted_files`? This is what we do in our Python example: https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952 [...]

2021-07-19 14:51 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 3 of 7 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTn-vF6OLZmMIc1yQW:-MezEatB0aSHY7wf78MD:bwonxs9) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L1)):*
<details><summary><i>Previously, Satya1493 wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry, that's not what I meant. You don't need to add `\` at the end of the line, otherwise your whole file (when rendered) is wrapped in 100 characters: https://github.com/Satya1493/graphene/tree/tensorflow/Examples/tensorflow.

So by simply removing all these `\` characters, you'll get what we want:
- Render in GitHub correctly,
- but be readable when opened in e.g. Vim (without line wraps, as is typically used by developers)


<!-- Sent from Reviewable.io -->

2021-07-23 06:10 UTC, Satya1493 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 3 of 7 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTn-vF6OLZmMIc1yQW:-MfGyyJR7LawrzttegZ4:b-lxvmy8) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, that's not what I meant. You don't need to add `\` at the end of the line, otherwise your whole file (when rendered) is wrapped in 100 characters: https://github.com/Satya1493/graphene/tree/tensorflow/Examples/tensorflow.

So by simply removing all these `\` characters, you'll get what we want:
- Render in GitHub correctly,
- but be readable when opened in e.g. Vim (without line wraps, as is typically used by developers)
</blockquote></details>

Got it.. Done.


<!-- Sent from Reviewable.io -->

2021-07-23 07:01 UTC, dimakuv requested changes
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTnImh6JUfK_dP051l:-MfH7Ou4Cg4TJW9yD5_Y:b-ky51oq) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L24)):*
<details><summary><i>Previously, Satya1493 wrote…</i></summary><blockquote>

done
</blockquote></details>

Thanks, looks much better now!
___
*[Examples/tensorflow/README.md, line 48 at r1](https://reviewable.io/reviews/oscarlab/graphene/2530#-MeTns4n5bBmnyehAHRU:-MfH8jIR-WY0B5tzNqT4:b-c7moba) ([raw file](https://github.com/oscarlab/graphene/blob/13a09c247ea0a7d11b0d69c479c0d5c7655912a3/Examples/tensorflow/README.md#L48)):*
<details><summary><i>Previously, Satya1493 wrote…</i></summary><blockquote>

Yeah, removed GSC section. Will push another PR for GSC.
</blockquote></details>

Thanks! This is much easier to review now.
___
*[Examples/tensorflow/README.md, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH6A6J90Cp50IqhH-5:-MfH6A6J90Cp50IqhH-6:b277oh) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L4)):*
> ```Markdown
> This directory contains steps and artifacts to run inference with TensorFlow BERT and ResNet50
> sample workloads on Graphene. Specifically, both these examples use pre-trained models to run
> inference. We tested this on Ubuntu 18.04 and uses the package version with Python 3.6.
> ```

Actually, could you remove this whole sentence `We tested this ...` because we agreed to remove it from all our examples (see https://github.com/oscarlab/graphene/pull/2566).
___
*[Examples/tensorflow/README.md, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH6JRtDbX2YB3jfJFy:-MfH6JRtDbX2YB3jfJFz:bisa81u) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L26)):*
> ```Markdown
> 
> ## Pre-requisites
> - Install python3.6.
> ```

Python is pre-installed on all known Linux distros, so just remove this line.
___
*[Examples/tensorflow/README.md, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH6y6M3KS8tpCRjI4o:-MfH6y6M3KS8tpCRjI4p:b-k4w07i) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L35)):*
> ```Markdown
> - To clean the sample, do ``make clean``
> - To clean and remove downloaded models and datasets, do ``make distclean``
> - To build the non-SGX version, do ``make PYTHONDISTPATH=path_to_python_dist_packages/``
> ```

Why do you need `PYTHONDISTPATH`? `graphene-manifest` utility (the one that generates the manifest) already provides the convinience macro `{{ python.distlib }}`, so you don't need an additional `PYTHONDISTPATH`. Please remove it from everywhere.
___
*[Examples/tensorflow/README.md, line 39 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7B9Z1aVjWjg5Flen:-MfH7B9Z1aVjWjg5Fleo:b-r02tpr) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L39)):*
> ```Markdown
> - Typically, path_to_python_dist_packages is '/usr/local/lib/python3.6/dist-packages', but can
> change based on python's installation directory.
> >**WARNING:** Building BERT sample downloads about 5GB of data.
> ```

Please don't use `>` to mark warnings/notes. See also discussions in https://github.com/oscarlab/graphene/pull/2535
___
*[Examples/tensorflow/README.md, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7S-Z-XyvSajrzRpR:-MfH7S-Z-XyvSajrzRpS:b2sfjcn) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L42)):*
> ```Markdown
> 
> ## Run inference on BERT model
> - To run int8 inference on graphene-sgx(SGX version)
> ```

Please add a whitespace between `graphene-sgx` and `(SGX version)`. Same for everywhere else.
___
*[Examples/tensorflow/README.md, line 98 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7a87ALyq4essIwfm:-MfH7a87ALyq4essIwfn:baw5n80) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L98)):*
> ```Markdown
> ```
> - Above commands are for a 36 core system. Please set the following options accordingly for optimal
>   performance.
> ```

Instead of a dot, please use `:` at the end
___
*[Examples/tensorflow/README.md, line 99 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7myX3NLznlYovGMj:-MfH7myX3NLznlYovGMk:b-bfdpbb) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L99)):*
> ```Markdown
> - Above commands are for a 36 core system. Please set the following options accordingly for optimal
>   performance.
>     - OMP_NUM_THREADS='Core(s) per socket', OMP_NUM_THREADS sets the maximum number of threads to
> ```

Please put `OMP_NUM_THREADS` in backticks
___
*[Examples/tensorflow/README.md, line 102 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7sQu-dMyNYMp3x7d:-MfH7sQu-dMyNYMp3x7e:b-c94oq2) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L102)):*
> ```Markdown
>       use for OpenMP parallel regions.
>     - taskset to 'Core(s) per socket'
>     - intra_op_parallelism_threads='Core(s) per socket'
> ```

Instead of using `'Core(s) per socket'` in three sentences here, maybe something like this?
```
    - Assuming that X is the number of cores per socket, set `OMP_NUM_THREADS=X`
      and `intra_op_parallelism_threads=X`.
    - Specify the whole range of cores available on one of the sockets in `taskset`.
    - ... hyperthreading stuff ...
    - Note that `OMP_NUM_THREADS` sets the maximum number of threads to
      use for OpenMP parallel regions, and `KVM_AFFINITY` binds OpenMP threads
      to physical processing units.
```
___
*[Examples/tensorflow/README.md, line 103 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH8ndG6PJsTMPeWQjj:-MfH8ndG6PJsTMPeWQjk:bbvpp2c) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L103)):*
> ```Markdown
>     - taskset to 'Core(s) per socket'
>     - intra_op_parallelism_threads='Core(s) per socket'
>     - If hyperthreading is enabled : use ``KMP_AFFINITY=granularity=fine,verbose,compact,1,0``
> ```

Please remove a redundant whitespace in between `enabled` and `:`. Apply everywhere in this PR.
___
*[Examples/tensorflow/README.md, line 105 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7qh98bYxEgx7JJEA:-MfH7qh98bYxEgx7JJEB:binbnpn) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L105)):*
> ```Markdown
>     - If hyperthreading is enabled : use ``KMP_AFFINITY=granularity=fine,verbose,compact,1,0``
>     - If hyperthreading is disabled : use ``KMP_AFFINITY=granularity=fine,verbose,compact``
>     - KMP_AFFINITY binds OpenMP threads to physical processing units.
> ```

Please put `KMP_AFFINITY` in backticks
___
*[Examples/tensorflow/README.md, line 106 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH8f7i4zvuxn9B96Cm:-MfH8f7i4zvuxn9B96Cn:brk8yob) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L106)):*
> ```Markdown
>     - If hyperthr [...]

2021-07-26 09:06 UTC, Satya1493 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 4 of 7 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH6A6J90Cp50IqhH-5:-MfWrDjy4BnoGoYILiHd:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, could you remove this whole sentence `We tested this ...` because we agreed to remove it from all our examples (see https://github.com/oscarlab/graphene/pull/2566).
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 26 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH6JRtDbX2YB3jfJFy:-MfWrFtp0Q945shXpanO:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Python is pre-installed on all known Linux distros, so just remove this line.
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH6y6M3KS8tpCRjI4o:-MfX2CcNEl2y6fC25QMR:bk986s0) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need `PYTHONDISTPATH`? `graphene-manifest` utility (the one that generates the manifest) already provides the convinience macro `{{ python.distlib }}`, so you don't need an additional `PYTHONDISTPATH`. Please remove it from everywhere.
</blockquote></details>

The pip version that comes with the distro is pip 9.0.1.
TensorFlow 2.4 version can only be installed with latest pip version 21.2.1.
Once pip is upgraded, it installs all packages into /usr/local/lib/python3.6/dist-packages.
{{ python.distlib }} gives /usr/lib/python3/dist-packages.
In addition to this path, TensorFlow samples also need /usr/local/lib/python3.6/dist-packages 
or any custom path that tensorflow is installed into.
Hence, I've added this as a configuration option during build.
___
*[Examples/tensorflow/README.md, line 39 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7B9Z1aVjWjg5Flen:-MfX2RnMC74RQpxoCWuO:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't use `>` to mark warnings/notes. See also discussions in https://github.com/oscarlab/graphene/pull/2535
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 42 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7S-Z-XyvSajrzRpR:-MfX2SnK0Gj8bvUO6PGa:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a whitespace between `graphene-sgx` and `(SGX version)`. Same for everywhere else.
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 98 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7a87ALyq4essIwfm:-MfX2WzK50wB-cXx8sVn:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L98)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of a dot, please use `:` at the end
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 99 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7myX3NLznlYovGMj:-MfX2XbYBmLeneowUb5j:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L99)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put `OMP_NUM_THREADS` in backticks
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 102 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7sQu-dMyNYMp3x7d:-MfX2ZA03nx8BQBjYpld:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L102)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Instead of using `'Core(s) per socket'` in three sentences here, maybe something like this?
```
    - Assuming that X is the number of cores per socket, set `OMP_NUM_THREADS=X`
      and `intra_op_parallelism_threads=X`.
    - Specify the whole range of cores available on one of the sockets in `taskset`.
    - ... hyperthreading stuff ...
    - Note that `OMP_NUM_THREADS` sets the maximum number of threads to
      use for OpenMP parallel regions, and `KVM_AFFINITY` binds OpenMP threads
      to physical processing units.
```
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 103 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH8ndG6PJsTMPeWQjj:-MfX2aGE0pVVctklgXvf:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove a redundant whitespace in between `enabled` and `:`. Apply everywhere in this PR.
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 105 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH7qh98bYxEgx7JJEA:-MfX2bMfDJse4iDhiyKx:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put `KMP_AFFINITY` in backticks
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 106 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH8f7i4zvuxn9B96Cm:-MfX2cKBAq-xBahVdNBD:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `>`
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 151 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH8x1p1OF_B4CVgriC:-MfX2fB97hdELd4jkNiY:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L151)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add backticks around option names.
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 152 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH8zQL3lGyMj1bptPM:-MfX2kakEEEJnQogvFns:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L152)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `>`
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 175 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH9-pv5oTq3C6593b6:-MfX2lfq3XzuXCaijja_:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8 [...]

2021-07-28 15:02 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 4 of 7 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2530#-Mfhc_CL2BiZWm2_OjTy:-Mfhc_CL2BiZWm2_OjTz:b-4dsoud) (no related file):*
Quick note (I will do the proper review tomorrow): could you please add `.gitignore` file to your example? This file informs git to "not track" (ignore) files that were downloaded or auto-generated. Basically, all files created during builds and runs (other than your manifest.template and Makefile files) should be git-ignored.

---


<!-- Sent from Reviewable.io -->

2021-07-28 15:05 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 4 of 7 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2530#-Mfhd0RhCQxedDpaqpLj:-Mfhd0RhCQxedDpaqpLk:b40kls) ([raw file](https://github.com/oscarlab/graphene/blob/b891ded309b7ef09ccf5e329b99d708b65542c4e/Examples/tensorflow/README.md#L37)):*
> ```Markdown
> 
> ## Run inference on BERT model
> - To run int8 inference on graphene-sgx (SGX version)
> ```

Another quick note: this README is quite hard to read because the command is duplicated three times. Could we replace this copy-paste with another structure? Like you give a command first, and then you describe that to run in non-SGX mode, replace `graphene-sgx` with `graphene`, and to run natively, replace `graphene-sgx ./python` with `python3`.
___
*[Examples/tensorflow/README.md, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfhdKteBapDXQYO5alO:-MfhdKteBapDXQYO5alP:blt9u4z) ([raw file](https://github.com/oscarlab/graphene/blob/b891ded309b7ef09ccf5e329b99d708b65542c4e/Examples/tensorflow/README.md#L76)):*
> ```Markdown
> - To run int8 inference on native baremetal (outside Graphene)
> ```
> OMP_NUM_THREADS=36 KMP_AFFINITY=granularity=fine,verbose,compact,1,0 taskset -c 0-35 python3.6 \
> ```

No need to hard-code the version of Python. So replace `python3.6` with simply `python3`. Here and everywhere else in this README.


<!-- Sent from Reviewable.io -->

2021-07-29 10:36 UTC, Satya1493 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 4 of 9 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2530#-Mfhc_CL2BiZWm2_OjTy:-MflowsqAWD0-2vWOSnQ:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Quick note (I will do the proper review tomorrow): could you please add `.gitignore` file to your example? This file informs git to "not track" (ignore) files that were downloaded or auto-generated. Basically, all files created during builds and runs (other than your manifest.template and Makefile files) should be git-ignored.
</blockquote></details>

Done

---
___
*[Examples/tensorflow/README.md, line 37 at r4](https://reviewable.io/reviews/oscarlab/graphene/2530#-Mfhd0RhCQxedDpaqpLj:-Mflp2nHDrdqx2IkzM2n:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b891ded309b7ef09ccf5e329b99d708b65542c4e/Examples/tensorflow/README.md#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Another quick note: this README is quite hard to read because the command is duplicated three times. Could we replace this copy-paste with another structure? Like you give a command first, and then you describe that to run in non-SGX mode, replace `graphene-sgx` with `graphene`, and to run natively, replace `graphene-sgx ./python` with `python3`.
</blockquote></details>

done
___
*[Examples/tensorflow/README.md, line 76 at r4](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfhdKteBapDXQYO5alO:-Mflp63w7lxj0fgciUW-:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene/blob/b891ded309b7ef09ccf5e329b99d708b65542c4e/Examples/tensorflow/README.md#L76)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need to hard-code the version of Python. So replace `python3.6` with simply `python3`. Here and everywhere else in this README.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-08-03 08:50 UTC, dimakuv requested changes
> Reviewed 2 of 3 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

___
*[Examples/tensorflow/README.md, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene/2530#-MfH6y6M3KS8tpCRjI4o:-MgAAzZbAUDLz2E_tJwk:bkq973u) ([raw file](https://github.com/oscarlab/graphene/blob/b8c1bb8bc267b8318d71faacae8e09bbdbacd82a/Examples/tensorflow/README.md#L35)):*
<details><summary><i>Previously, Satya1493 wrote…</i></summary><blockquote>

The pip version that comes with the distro is pip 9.0.1.
TensorFlow 2.4 version can only be installed with latest pip version 21.2.1.
Once pip is upgraded, it installs all packages into /usr/local/lib/python3.6/dist-packages.
{{ python.distlib }} gives /usr/lib/python3/dist-packages.
In addition to this path, TensorFlow samples also need /usr/local/lib/python3.6/dist-packages 
or any custom path that tensorflow is installed into.
Hence, I've added this as a configuration option during build.
</blockquote></details>

Ok, got it.
___
*[Examples/tensorflow/README.md, line 8 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA6uQs7nU6REAgCrfE:-MgA6uQs7nU6REAgCrfF:b-yd9awt) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L8)):*
> ```Markdown
> ### Bidirectional Encoder Representations from Transformers (BERT):
> BERT is a method of pre-training language representations and then use that trained model for
> downstream NLP tasks like 'question answering'. BERT is an unsupervised, deeply birectional system
> ```

What is `birectional`? I guess `bidirectional`
___
*[Examples/tensorflow/README.md, line 10 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7MoC5bAZYRTB20-Q:-MgA7MoC5bAZYRTB20-R:b-fons5u) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L10)):*
> ```Markdown
> downstream NLP tasks like 'question answering'. BERT is an unsupervised, deeply birectional system
> for pre-training NLP.
> In this BERT sample, we use 'BERT-Large, Uncased (Whole Word Masking)' model and perform int8
> ```

I would prefer to bold this `'BERT-Large, Uncased (Whole Word Masking)'` instead of putting into quotes. So it will be: `**BERT-Large, Uncased (Whole Word Masking)**`
___
*[Examples/tensorflow/README.md, line 15 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7BPZ-PZqvXS_eXE_:-MgA7BPZ-PZqvXS_eXEa:byn0dds) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L15)):*
> ```Markdown
> ### Residual Network (ResNet):
> ResNet50 is a convolutional neural network that is 50 layers deep.
> In this ResNet50(v1.5) sample, we use a pre-trained model and perform int8 inference.
> ```

Can you add a space: `ResNet50(v1.5)` -> `ResNet50 (v1.5)` (unless this is how it is supposed to be written, then don't change)
___
*[Examples/tensorflow/README.md, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7ZtI4G139AtNHJ_g:-MgA7ZtI4G139AtNHJ_h:b-lfakgq) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L20)):*
> ```Markdown
> ## Pre-requisites
> - Upgrade pip/pip3.
> - Install tensorflow using ``pip install intel-tensorflow-avx512==2.4.0`` or by downloading whl
> ```

`tensorflow` -> `TensorFlow`
___
*[Examples/tensorflow/README.md, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7gA20M-VKGfr4MRD:-MgA7gA20M-VKGfr4MRE:bszdtff) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L20)):*
> ```Markdown
> ## Pre-requisites
> - Upgrade pip/pip3.
> - Install tensorflow using ``pip install intel-tensorflow-avx512==2.4.0`` or by downloading whl
> ```

`whl package` -> `the Wheel (.whl) package`
___
*[Examples/tensorflow/README.md, line 21 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7siTD4KPfV6430Le:-MgA7siTD4KPfV6430Lf:b-n9agkp) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L21)):*
> ```Markdown
> - Upgrade pip/pip3.
> - Install tensorflow using ``pip install intel-tensorflow-avx512==2.4.0`` or by downloading whl
> package from https://pypi.org/project/intel-tensorflow-avx512/2.4.0/#files.
> ```

Actually, why do you specify two different ways of installing TensorFlow? Why would a user choose one over the other? Could we just specify one way (I would go with `pip` installation then)?
___
*[Examples/tensorflow/README.md, line 24 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA88CU34axmquQpRrw:-MgA88CVDgmMag07QT_H:b-wx5azi) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L24)):*
> ```Markdown
> 
> ## Build BERT or ResNet50 samples
> - To build BERT sample, do ``cd BERT`` or to build ResNet50 sample, do ``cd ResNet50``.
> ```

Can you separate into two sentences? Hard to read this. Like this:
```
- To build BERT sample, do ``cd BERT``. To build ResNet50 sample, do ``cd ResNet50``.
```
___
*[Examples/tensorflow/README.md, line 29 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8MGA9FlXQRPedDfP:-MgA8MGA9FlXQRPedDfQ:b-x1rfsz) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L29)):*
> ```Markdown
> - To build the non-SGX version, do ``make PYTHONDISTPATH=path_to_python_dist_packages/``
> - To build the SGX version, do ``make PYTHONDISTPATH=path_to_python_dist_packages/ SGX=1``
> - Typically, path_to_python_dist_packages is '/usr/local/lib/python3.6/dist-packages', but can
> ```

Please place `path_to_python_dist_packages` in backticks. Also put `/usr/local/...` in backticks (instead of current single quotes).
___
*[Examples/tensorflow/README.md, line 31 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8SpVBL8CHKUQbUKk:-MgA8SpVBL8CHKUQbUKl:b-10d3a0) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L31)):*
> ```Markdown
> - Typically, path_to_python_dist_packages is '/usr/local/lib/python3.6/dist-packages', but can
> change based on python's installation directory.
> - Keras settings are configured in the file root/.keras/keras.json. It is configured to use
> ```

Please place `root/.keras/...` in backticks.
___
*[Examples/tensorflow/README.md, line 32 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8XK4CPq8oRsS0JUz:-MgA8XK4CPq8oRsS0JV-:b-lfakgq) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L32)):*
> ```Markdown
> change based on python's installation directory.
> - Keras settings are configured in the file root/.keras/keras.json. It is configured to use
> tensorflow as backend.
> ```

`tensorflow` -> `TensorFlow`
___
*[Examples/tensorflow/README.md, line 37 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8dxi6mTcWkZGsJW7:-MgA8dxi6mTcWkZGsJW8:b39449w) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L37)):*
> ```Markdown
> 
> ## Run inference on BERT model
> - To run int8 inference on graphene-sgx (SGX version)
> ```

Please place `graphene-sgx` into backticks.
___
*[Examples/tensorflow/README.md, line 37 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA9KEW30_BJQ819Kcn:-MgA9KEW30_BJQ819Kco:bxeq3hl) ([raw file](https://github.com/oscarlab/graphene/blob/ [...]

2021-08-04 08:40 UTC, Satya1493 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 4 of 9 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 8 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA6uQs7nU6REAgCrfE:-MgFIS7w8wfttlXeaVt8:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `birectional`? I guess `bidirectional`
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 10 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7MoC5bAZYRTB20-Q:-MgFITch2CsiL2fD_Clk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to bold this `'BERT-Large, Uncased (Whole Word Masking)'` instead of putting into quotes. So it will be: `**BERT-Large, Uncased (Whole Word Masking)**`
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 15 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7BPZ-PZqvXS_eXE_:-MgFIUX95sSX6FKqYMs_:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a space: `ResNet50(v1.5)` -> `ResNet50 (v1.5)` (unless this is how it is supposed to be written, then don't change)
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7ZtI4G139AtNHJ_g:-MgFIVmh1JRBAAaDjGwt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`tensorflow` -> `TensorFlow`
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 20 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7gA20M-VKGfr4MRD:-MgFIX7EElah4XivM99t:b16jpro) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`whl package` -> `the Wheel (.whl) package`
</blockquote></details>

Removed installation step from .whl package as per the below comment.
___
*[Examples/tensorflow/README.md, line 21 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA7siTD4KPfV6430Le:-MgFIffTAP7OMZmv64BZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do you specify two different ways of installing TensorFlow? Why would a user choose one over the other? Could we just specify one way (I would go with `pip` installation then)?
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 24 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA88CU34axmquQpRrw:-MgFIiabBySS4GMlIF_2:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you separate into two sentences? Hard to read this. Like this:
```
- To build BERT sample, do ``cd BERT``. To build ResNet50 sample, do ``cd ResNet50``.
```
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 29 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8MGA9FlXQRPedDfP:-MgFIlq7D7cmrX-KA7WG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please place `path_to_python_dist_packages` in backticks. Also put `/usr/local/...` in backticks (instead of current single quotes).
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 31 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8SpVBL8CHKUQbUKk:-MgFItD80thPeL-hUE1H:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please place `root/.keras/...` in backticks.
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 32 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8XK4CPq8oRsS0JUz:-MgFItoI7dgEMwTLyP9V:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`tensorflow` -> `TensorFlow`
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 37 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8dxi6mTcWkZGsJW7:-MgFIysY60rrXpIpq-SK:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please place `graphene-sgx` into backticks.
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 37 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA9KEW30_BJQ819Kcn:-MgFIzz_0f2SoiF6C71a:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `:` at the end
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 55 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA8nwuCWCwyZQkkRjD:-MgFJ03k8muYN_k5C9ua:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L55)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please place `graphene-direct` into backticks.
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 60 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgAABDO4pPOd7CvGTiu:-MgFJ6Jc9U0ttYhRuTvP:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L60)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This whole part is almost identical for both BERT and ResNet. Could you extract this part into a separate section (e.g., `## Notes on optimal performance`)? Then you won't have this replication of the same text.

The only difference I see is `intra_op_parallelism_threads=X` vs `num_intra_threads=X`. Just add a text that the first one is for BERT and the second one is for ResNet.
</blockquote></details>

Done.
___
*[Examples/tensorflow/README.md, line 71 at r5](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgA92wHCUxjUZVGYgQc:-MgFJ9cbAFkONF2BajLa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/e4488412e107e0db6c8472cc6a464ef30884d8e2/Examples/tensorflow/README.md#L71)):*
< [...]

2021-08-06 09:26 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

___
*[Examples/tensorflow/README.md, line 77 at r6](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgPlhzX-M7kd2M9OiIz:-MgPlhzX-M7kd2M9OiJ-:b-s0erzm) ([raw file](https://github.com/oscarlab/graphene/blob/a4ea7d9851ace8bc280f1e4cd45a4af38e36dc49/Examples/tensorflow/README.md#L77)):*
> ```Markdown
> 
> ## Notes on optimal performance
> - Above commands are for a 36 core system. Please set the following options accordingly for optimal
> ```

There is no need to make these two sentences a list. Please remove `-` here.


<!-- Sent from Reviewable.io -->

2021-08-06 09:44 UTC, Satya1493 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: 8 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @Satya1493)

___
*[Examples/tensorflow/README.md, line 77 at r6](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgPlhzX-M7kd2M9OiIz:-MgPqK8V44wy-Hp8SbaD:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a4ea7d9851ace8bc280f1e4cd45a4af38e36dc49/Examples/tensorflow/README.md#L77)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need to make these two sentences a list. Please remove `-` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 12:34 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2530)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @Satya1493)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2530#-MgQSEKIA_A-jJFQAd3v:-MgQSEKJBbPXeP_vDEDF:b-6t3q97) (no related file):*
Thanks for the PR! Good from my side (but still blocking on the "merge two commits into one during final rebase").

---


<!-- Sent from Reviewable.io -->

2021-10-29 11:59 UTC, Satya1493 commented
Moved to new gramine 'examples' repository at [pr #7](https://github.com/gramineproject/examples/pull/7)

2021-10-29 11:59 UTC, closed without merging