[Pal/Linux-SGX]Fix pointer check issues
oscarlab/graphene pull request #2559
Opened 2021-07-15 15:39 UTC by aneessahib

These issues were flagged by Klocwork

Pointer 'known_leaf' checked for NULL at line 380 may be dereferenced at line 402.
/graphene/Pal/src/host/Linux-SGX/db_misc.c:402 | _DkCpuIdRetrieve()

Null pointer 'known_leaf' that comes from line 372 may be dereferenced at line 402.
/graphene/Pal/src/host/Linux-SGX/db_misc.c:402 | _DkCpuIdRetrieve()

Pointer 'orig_env_key_end' returned from call to function 'strchr' at line 113 may be NULL and will be dereferenced at line 115.
/Pal/src/db_main.c:115 | insert_envs_from_manifest()

Pointer 'toml_env_key' returned from call to function 'toml_key_in' at line 132 may be NULL and may be dereferenced at line 144.
Pal/src/db_main.c:144 | insert_envs_from_manifest()

2021-07-16 08:26 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2559)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[Pal/src/host/Linux-SGX/db_misc.c, line 395 at r1](https://reviewable.io/reviews/oscarlab/graphene/2559#-MeiPklK88wDdy-nCWes:-MeiPklK88wDdy-nCWet:b-70rm18) ([raw file](https://github.com/oscarlab/graphene/blob/dd53b7ebcb6dd25d2fb617a214a1f0c252b3270c/Pal/src/host/Linux-SGX/db_misc.c#L395)):*
> ```C
> 
>     if (!known_leaf)
>        goto fail;
> ```

Actually, instead of this IF check, I would put an assert here: `assert(known_leaf)`. The code above must find the corresponding `known_leaf` always. If it's not the case (currently it is the case, but in the future someone could break this), then our code is broken. So assert is better than just performing a check.


<!-- Sent from Reviewable.io -->

2021-07-16 14:36 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2559)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2559#-Meji0sJ5iYF6KI9U8KQ:-Meji0sJ5iYF6KI9U8KR:b-nyu3nj) (no related file):*
> [Pal/Linux-SGX]Fix pointer check issues

You're missing a space after `]`

---
___
*[Pal/src/db_main.c, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2559#-Meji6kU2yHzbfKKwtc4:-Meji6kU2yHzbfKKwtc5:b-r6gjr5) ([raw file](https://github.com/oscarlab/graphene/blob/dd53b7ebcb6dd25d2fb617a214a1f0c252b3270c/Pal/src/db_main.c#L114)):*
> ```C
>     for (const char** orig_env = *envpp; *orig_env; orig_env++) {
>         char* orig_env_key_end = strchr(*orig_env, '=');
>         if (!orig_env_key_end)
> ```

This case is not possible, this very condition is already verified in the loop above.
___
*[Pal/src/db_main.c, line 135 at r1](https://reviewable.io/reviews/oscarlab/graphene/2559#-MejicOl8Dl3HehUuedR:-MejicOl8Dl3HehUuedS:b-t1ep6y) ([raw file](https://github.com/oscarlab/graphene/blob/dd53b7ebcb6dd25d2fb617a214a1f0c252b3270c/Pal/src/db_main.c#L135)):*
> ```C
>     for (ssize_t i = 0; i < toml_envs_cnt; i++) {
>         const char* toml_env_key = toml_key_in(toml_envs, i);
>         if (!toml_env_key)
> ```

Also impossible, tomlc99 interface guarantees this.
___
*[Pal/src/host/Linux-SGX/db_misc.c, line 395 at r1](https://reviewable.io/reviews/oscarlab/graphene/2559#-MeiPklK88wDdy-nCWes:-MejjaRN0_c9mgEAJaLR:b32v57) ([raw file](https://github.com/oscarlab/graphene/blob/dd53b7ebcb6dd25d2fb617a214a1f0c252b3270c/Pal/src/host/Linux-SGX/db_misc.c#L395)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, instead of this IF check, I would put an assert here: `assert(known_leaf)`. The code above must find the corresponding `known_leaf` always. If it's not the case (currently it is the case, but in the future someone could break this), then our code is broken. So assert is better than just performing a check.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-07-16 17:34 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2559)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @mkow)

___
*[Pal/src/db_main.c, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2559#-Meji6kU2yHzbfKKwtc4:-MekLzvC5CGLNTBlFQbQ:b3y3c3e) ([raw file](https://github.com/oscarlab/graphene/blob/dd53b7ebcb6dd25d2fb617a214a1f0c252b3270c/Pal/src/db_main.c#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This case is not possible, this very condition is already verified in the loop above.
</blockquote></details>

this may not happen in a normal case.  But strchr can return NULL if  "=" is not found in *orig_env. How is the above loop ensuring this doesnt  happen?  


<!-- Sent from Reviewable.io -->

2021-07-18 19:34 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2559)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)

___
*[Pal/src/db_main.c, line 114 at r1](https://reviewable.io/reviews/oscarlab/graphene/2559#-Meji6kU2yHzbfKKwtc4:-Mev5t721f3gCIN_FTyX:b-o7t00r) ([raw file](https://github.com/oscarlab/graphene/blob/dd53b7ebcb6dd25d2fb617a214a1f0c252b3270c/Pal/src/db_main.c#L114)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

this may not happen in a normal case.  But strchr can return NULL if  "=" is not found in *orig_env. How is the above loop ensuring this doesnt  happen?  
</blockquote></details>

The loop above is iterating over the very same array and has:
```C
char* orig_env_key_end = strchr(*orig_env, '=');
if (!orig_env_key_end)
    return -PAL_ERROR_INVAL;
```


<!-- Sent from Reviewable.io -->

2021-08-16 11:22 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2559)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2559#-MhDgXMMCNj-7jWks9x_:-MhDgXMN4w3i7kLtldrh:b-qj23dv) (no related file):*
@aneessahib: Are you planning to continue working on this, or should we close this PR?

---


<!-- Sent from Reviewable.io -->

2021-08-17 04:02 UTC, aneessahib commented
will close this. there are cpl of other valid issues for which i will raise a separate PR.

2021-08-17 04:02 UTC, closed without merging