[LibOS] Warn on mounting host dirs/files shadowing sensitive directories
oscarlab/graphene pull request #2567
Opened 2021-07-21 12:29 UTC by dimakuv

## Description of the changes 

Graphene automatically mounts and populates `/proc`, `/sys` and `/dev`. The user may mount these directories (or files under these directories) from the host but Graphene will now loudly warn about this. Also, Graphene warns about mounting `/etc` because it contains sensitive and (typically) non-sanitized files.

## How to test this PR? 

Manually add these mounts to the manifest and see how Graphene complains.

2021-07-21 13:15 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf87uw66g5u_JU-lKkR:-Mf87uw70pB3L67IN3pi:b-qzft4v) (no related file):*
Our own examples mount files from `/etc` quite often; and according to @mkow this is not that easy to get rid of. Maybe we shouldn't complain about `/etc`?

---
___
*[LibOS/shim/src/fs/shim_fs.c, line 228 at r1](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf8Bw3g-gLXC-hWdFcq:-Mf8Bw3g-gLXC-hWdFcr:b4vi2xu) ([raw file](https://github.com/oscarlab/graphene/blob/1b52bc45c18142f553235bde748be9d36b26bba5/LibOS/shim/src/fs/shim_fs.c#L228)):*
> ```C
>     }
> 
>     if (!g_pal_control->parent_process) {
> ```

AFAICT, only the first process executes this - the others migrate the mounts.
___
*[LibOS/shim/src/fs/shim_fs.c, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf88OyMD53_syiS6UgE:-Mf88OyMD53_syiS6UgF:b-o6k0ez) ([raw file](https://github.com/oscarlab/graphene/blob/1b52bc45c18142f553235bde748be9d36b26bba5/LibOS/shim/src/fs/shim_fs.c#L230)):*
> ```C
>     if (!g_pal_control->parent_process) {
>         /* print warnings on suspicious mounts but don't exit; only in first process */
>        if (!strncmp(mount_uri, "file:/proc", strlen("file:/proc")) ||
> ```

Bad indentation. And we usually over-indent the continuation lines by 4 spaces, so that the condition is visually separate from `if` body:

```c
if (foo ||
        bar ||
        baz) {
    quux();
}
```
___
*[LibOS/shim/src/fs/shim_fs.c, line 233 at r1](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf88K4l4tQuYI__AvZU:-Mf88K4l4tQuYI__AvZV:b-qwbj4e) ([raw file](https://github.com/oscarlab/graphene/blob/1b52bc45c18142f553235bde748be9d36b26bba5/LibOS/shim/src/fs/shim_fs.c#L233)):*
> ```C
>             !strncmp(mount_uri, "file:/sys", strlen("file:/sys")) ||
>             !strncmp(mount_uri, "file:/dev", strlen("file:/dev"))) {
>            log_error("Mounting %s overlaps with Graphene internal mounts (/proc, /sys, /dev). "
> ```

It's not the overlap that is the problem, it's that these are files from host system and not emulated ones. I'd rather say that this is unsanitized, unsafe, and possibly incorrect (e.g. the information refers to host system, not LibOS). I can't think of good concise wording for that, though...


<!-- Sent from Reviewable.io -->

2021-07-21 13:58 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: 0 of 1 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf87uw66g5u_JU-lKkR:-Mf8M2pVCBPEjNoBphdo:blmmcnx) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Our own examples mount files from `/etc` quite often; and according to @mkow this is not that easy to get rid of. Maybe we shouldn't complain about `/etc`?
</blockquote></details>

Yeah, `/etc` was pointed out to us as a "dangereous" path. @mkow What would you say about this? Do we want to have some warning on `/etc`?

---
___
*[LibOS/shim/src/fs/shim_fs.c, line 228 at r1](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf8Bw3g-gLXC-hWdFcq:-Mf8K4syBFGfu4E-A6VR:bmgb74e) ([raw file](https://github.com/oscarlab/graphene/blob/1b52bc45c18142f553235bde748be9d36b26bba5/LibOS/shim/src/fs/shim_fs.c#L228)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

AFAICT, only the first process executes this - the others migrate the mounts.
</blockquote></details>

Done. You're right, we have this check in `init_mount()`.
___
*[LibOS/shim/src/fs/shim_fs.c, line 230 at r1](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf88OyMD53_syiS6UgE:-Mf8K7pKBE8NEsXvhlLM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1b52bc45c18142f553235bde748be9d36b26bba5/LibOS/shim/src/fs/shim_fs.c#L230)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Bad indentation. And we usually over-indent the continuation lines by 4 spaces, so that the condition is visually separate from `if` body:

```c
if (foo ||
        bar ||
        baz) {
    quux();
}
```
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_fs.c, line 233 at r1](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf88K4l4tQuYI__AvZU:-Mf8LzB0-GoWIYUKCVKy:b-g5l2l7) ([raw file](https://github.com/oscarlab/graphene/blob/1b52bc45c18142f553235bde748be9d36b26bba5/LibOS/shim/src/fs/shim_fs.c#L233)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It's not the overlap that is the problem, it's that these are files from host system and not emulated ones. I'd rather say that this is unsanitized, unsafe, and possibly incorrect (e.g. the information refers to host system, not LibOS). I can't think of good concise wording for that, though...
</blockquote></details>

Done. Agreed, this was bad wording.


<!-- Sent from Reviewable.io -->

2021-07-21 15:13 UTC, pwmarcz reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-07-22 11:25 UTC, mkow requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf87uw66g5u_JU-lKkR:-MfCwjNm8W3C6_yfkU-I:blkux8t) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, `/etc` was pointed out to us as a "dangereous" path. @mkow What would you say about this? Do we want to have some warning on `/etc`?
</blockquote></details>

Hmm, I wouldn't warn at least until we manage to get rid of it from our examples. Because right now you often have to mount fake `/etc` to emulate some configs (and this can be fine if you don't mount it from the host `/etc`, but from a specially crafted one).
Btw. Could you also update the PR description? It still mentions `/etc/`.

---
___
*[LibOS/shim/src/fs/shim_fs.c, line 230 at r2](https://reviewable.io/reviews/oscarlab/graphene/2567#-MfCxMLV5THdLeYCnjEs:-MfCxMLW8O11RAmaHWFZ:b28gcqm) ([raw file](https://github.com/oscarlab/graphene/blob/a55a5f3157bd0da91b9e0c9ae581204ef863a1a3/LibOS/shim/src/fs/shim_fs.c#L230)):*
> ```C
>     if (!strncmp(mount_uri, "file:/proc", strlen("file:/proc")) ||
>             !strncmp(mount_uri, "file:/sys", strlen("file:/sys")) ||
>             !strncmp(mount_uri, "file:/dev", strlen("file:/dev"))) {
> ```

Hmm, this matches too much. E.g. `/system` :)
It should match both `/proc\0` and `/proc/[...]` (and analogously with others), but nothing more.


<!-- Sent from Reviewable.io -->

2021-07-22 12:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2567#-Mf87uw66g5u_JU-lKkR:-MfDDdCMEwWXvnLs7BWs:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, I wouldn't warn at least until we manage to get rid of it from our examples. Because right now you often have to mount fake `/etc` to emulate some configs (and this can be fine if you don't mount it from the host `/etc`, but from a specially crafted one).
Btw. Could you also update the PR description? It still mentions `/etc/`.
</blockquote></details>

Done.

---
___
*[LibOS/shim/src/fs/shim_fs.c, line 230 at r2](https://reviewable.io/reviews/oscarlab/graphene/2567#-MfCxMLV5THdLeYCnjEs:-MfDDRoHCINrzMmSTmSf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/a55a5f3157bd0da91b9e0c9ae581204ef863a1a3/LibOS/shim/src/fs/shim_fs.c#L230)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, this matches too much. E.g. `/system` :)
It should match both `/proc\0` and `/proc/[...]` (and analogously with others), but nothing more.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-22 13:07 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2021-07-22 23:27 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_fs.c, line 230 at r2](https://reviewable.io/reviews/oscarlab/graphene/2567#-MfCxMLV5THdLeYCnjEs:-MfFXfXd7MG8okGso0CR:b-gtb5d7) ([raw file](https://github.com/oscarlab/graphene/blob/a55a5f3157bd0da91b9e0c9ae581204ef863a1a3/LibOS/shim/src/fs/shim_fs.c#L230)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can use `strcmp(mount_uri, X)` instead of `strncmp(mount_uri, X, strlen(X) + 1)`.


<!-- Sent from Reviewable.io -->

2021-07-23 07:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_fs.c, line 230 at r2](https://reviewable.io/reviews/oscarlab/graphene/2567#-MfCxMLV5THdLeYCnjEs:-MfHAIag9wb8QeiuPfy4:b-vgo3nx) ([raw file](https://github.com/oscarlab/graphene/blob/a55a5f3157bd0da91b9e0c9ae581204ef863a1a3/LibOS/shim/src/fs/shim_fs.c#L230)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You can use `strcmp(mount_uri, X)` instead of `strncmp(mount_uri, X, strlen(X) + 1)`.
</blockquote></details>

Done. I wanted to make it explicit, but you're right, looked like high-school C programming.


<!-- Sent from Reviewable.io -->

2021-07-23 12:04 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-23 12:58 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-23 13:08 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-07-23 13:23 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2567)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-23 13:53 UTC, merged