[SGX Tools] `is_sgx_available` reports whether AESMD is installed
oscarlab/graphene pull request #2573
Opened 2021-07-22 10:02 UTC by dimakuv

## Description of the changes 

Previously, `is_sgx_available` reported whether AESMD is *running* based on existence of the socket `/var/run/aesmd/aesm.socket`. In reality, the existence of this socket doesn't mean that AESMD is actually running but that it is only installed on the machine.

See https://github.com/oscarlab/graphene/issues/1998 for context. I went with the approach number 3 in here: https://github.com/oscarlab/graphene/issues/1998#issuecomment-736333951.

## How to test this PR? 

Run `is_sgx_available` on any machine, including CentOS.

2021-07-22 12:24 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2573)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2573#-MfD9BMb-8XM2bKLUVjv:-MfD9BMc8uHGQarJxNOf:bdw0wyj) (no related file):*
> [SGX Tools] `is_sgx_available` reports whether AESMD is installed

Is this a problem with the current version or the thing you implemented in this commit?

---
___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2573#-MfD9aRl1mlcrjAEGXp8:-MfD9aRl1mlcrjAEGXp9:b-6f9g5d) ([raw file](https://github.com/oscarlab/graphene/blob/eab022b6c812c27d566f39e4a42f6b6cf31b8d4d/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L19)):*
> ```cpp
>     PSW_NOT_INSTALLED = 3,
>     AESMD_NOT_INSTALLED = 4 // This is a separate exit code, because AESMD tends
>                             // to die spontaneously.
> ```

I guess this comment isn't relevant anymore? It turned out to actually not detect this case, so @woju had to implement something which communicates with aesmd on Jenkins to actually check whether it's running correctly.


<!-- Sent from Reviewable.io -->

2021-07-22 12:51 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2573)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2573#-MfD9BMb-8XM2bKLUVjv:-MfDGImN12WsIR2zM74E:b4ewy0n) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> [SGX Tools] `is_sgx_available` reports whether AESMD is installed

Is this a problem with the current version or the thing you implemented in this commit?
</blockquote></details>

Done. Force-pushed with the new commit name.

---
___
*[Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene/2573#-MfD9aRl1mlcrjAEGXp8:-MfDFp4QBfeEJtAqbrrW:b-5r0bjh) ([raw file](https://github.com/oscarlab/graphene/blob/eab022b6c812c27d566f39e4a42f6b6cf31b8d4d/Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available.cpp#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I guess this comment isn't relevant anymore? It turned out to actually not detect this case, so @woju had to implement something which communicates with aesmd on Jenkins to actually check whether it's running correctly.
</blockquote></details>

OK, removed the comment.


<!-- Sent from Reviewable.io -->

2021-07-22 23:23 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2573)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-07-27 16:31 UTC, mkow approved these changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2573)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-27 16:49 UTC, merged