[LTP] fix pread fails when file descriptor refers to a directory
oscarlab/graphene pull request #2577
Opened 2021-07-23 08:59 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
fix pread fails when file descriptor refers to a directory.
Fixes #2539 

## How to test this PR? 
Run LTP Test pread03

2021-07-23 10:20 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2577)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-07-23 10:22 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2577)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2577#-MfHsQ-m3sQwKsuFMC6G:-MfHsQ-m3sQwKsuFMC6H:be9ma) (no related file):*
> `[LTP] fix pread fails when file descriptor refers to a directory`

This commit message should be changed to smth like:
```
[LibOS] return EISDIR in pread64() if fd refers to a directory
```

We can do it during the final rebase, so nothing for you to fix, @sahason. We'll do it ourselves. Thanks for the fix!

---


<!-- Sent from Reviewable.io -->

2021-07-23 12:13 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2577)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2577#-MfHsQ-m3sQwKsuFMC6G:-MfIGtsG-B-UFQK9Uyvo:b-rdvtk3) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> `[LTP] fix pread fails when file descriptor refers to a directory`

This commit message should be changed to smth like:
```
[LibOS] return EISDIR in pread64() if fd refers to a directory
```

We can do it during the final rebase, so nothing for you to fix, @sahason. We'll do it ourselves. Thanks for the fix!
</blockquote></details>

and `return` -> `Return`

---


<!-- Sent from Reviewable.io -->

2021-07-23 13:07 UTC, dimakuv commented
Jenkins, test this please

2021-08-06 07:41 UTC, dimakuv commented
This PR was superseded by #2626. Sorry. For rationale, see https://github.com/oscarlab/graphene/issues/2539#issuecomment-894069814.

2021-08-06 07:41 UTC, closed without merging