[Examples] Decouple all examples from the core Graphene repo
oscarlab/graphene pull request #2582
Opened 2021-07-26 13:55 UTC by dimakuv

## Description of the changes 

Examples are supposed to be stand-alone and work with packaged Graphene. To this end, this commit removes the `GRAPHENEDIR` envvar and the associated includes of Graphene-internal Makefiles. This commit also copies the `download` bash script under `Examples/` so that it is closer to the actual examples (this will be handy when moving examples out of this core repository).

Ideally, `SGX_SIGNER_KEY` should be explicitly asked from the user, but for now we default to Graphene-internal `Pal/src/host/Linux-SGX/signer` for simplicity.

Also, `ra-tls-mbedtls` and `ra-tls-secret-prov` are still tightly coupled to Graphene-internal paths. This will be fixed when Linux-SGX PAL build is finally moved to Meson.

## How to test this PR? 

All CI tests must pass. I also manually tested almost all examples.

2021-07-26 14:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: 0 of 21 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[Examples/apache/Makefile, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5xdv62vdqus_5nqi:-MfY5xdv62vdqus_5nqj:bx4qbk0) ([raw file](https://github.com/oscarlab/graphene/blob/0f286951f01c0768224837af683e7ed513aa33e3/Examples/apache/Makefile#L33)):*
> ```Makefile
> endif
> 
> include ../../Scripts/Makefile.configs
> ```

FYI: The sole reason to include this Makefile.configs file was because we wanted `ARCH_LIBDIR`. I moved the definition of `ARCH_LIBDIR` in the Examples' Makefiles now, so it is explicit.
___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfY5iCF6SZwldbHCOdG:b-4qz678) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
> ```
> #!/usr/bin/env bash
> ```

FYI: Having two copies of this file is not amazing (the original is under `graphene/Scripts/download`). But we'll soon have a separate repository with Examples, so that's why this duplication.
___
*[Examples/ra-tls-mbedtls/Makefile, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY6Gl9C4FPVLNJwnOG:-MfY6Gl9C4FPVLNJwnOH:b-ahemu4) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/ra-tls-mbedtls/Makefile#L2)):*
> ```Makefile
> GRAPHENEDIR ?= ../..
> GRAPHENEKEY ?= $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem
> ```

I kept `GRAPHENEDIR` here because these examples are currently very much tied to the core Graphene repo. I'll create separate PRs to fix this, after we have proper packaging of Linux-SGX tools (including RA-TLS) via Meson.
___
*[Examples/ra-tls-secret-prov/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY6StaA4s_GuBRvB7r:-MfY6StaA4s_GuBRvB7s:b-ahemu4) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/ra-tls-secret-prov/Makefile#L1)):*
> ```Makefile
> GRAPHENEDIR ?= ../..
> ```

I kept `GRAPHENEDIR` here because these examples are currently very much tied to the core Graphene repo. I'll create separate PRs to fix this, after we have proper packaging of Linux-SGX tools (including RA-TLS) via Meson.
___
*[Examples/tensorflow-lite/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY6Y8aArXfFchaZKHm:-MfY6Y8aArXfFchaZKHn:b-9rkxl1) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/tensorflow-lite/Makefile#L1)):*
> ```Makefile
> manifests = $(addsuffix .manifest,label_image)
> ```

Someone please update this TensorFlow-Lite example, it's old as the world.


<!-- Sent from Reviewable.io -->

2021-07-27 09:48 UTC, pwmarcz requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfbKyx50oXyptC6Q82A:-MfbKyx50oXyptC6Q82B:bhvkozf) (no related file):*
I see `ARCH_LIBDIR` has also been customized for Fedora (f7f89c2ed2); apparently it uses just `/lib64` instead of an architecture-specific directory. How about using `?=` so that it can be overriden?

---


<!-- Sent from Reviewable.io -->

2021-07-27 09:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfbKyx50oXyptC6Q82A:-MfbOG7RCNxsXmgrLUhY:b-v5ph4z) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I see `ARCH_LIBDIR` has also been customized for Fedora (f7f89c2ed2); apparently it uses just `/lib64` instead of an architecture-specific directory. How about using `?=` so that it can be overriden?
</blockquote></details>

Oops, that was actually what I was targeting for. And forgot to replace with `?=`... Will do now.

---


<!-- Sent from Reviewable.io -->

2021-07-27 12:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: 2 of 21 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfbKyx50oXyptC6Q82A:-Mfbv_yoAhkb1DuEfTkK:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, that was actually what I was targeting for. And forgot to replace with `?=`... Will do now.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-07-27 12:52 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-27 13:37 UTC, mkow requested changes
> Reviewed 2 of 21 files at r1, 19 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[Examples/apache/Makefile, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc7buu8A8PXX-Wczm8:-Mfc7buu8A8PXX-Wczm9:b-18l4ia) ([raw file](https://github.com/oscarlab/graphene/blob/0f286951f01c0768224837af683e7ed513aa33e3/Examples/apache/Makefile#L19)):*
> ```Makefile
> 
> GRAPHENEDIR ?= $(THIS_DIR)../..
> SGX_SIGNER_KEY ?= $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem
> ```

Could we fail with a nice error message if `SGX_SIGNER_KEY` file doesn't exist after this assignment?
___
*[Examples/bash/Makefile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc8IgfDrs1BdrXaioT:-Mfc8IgfDrs1BdrXaioU:buiz5xd) ([raw file](https://github.com/oscarlab/graphene/blob/fa9fd13ec735717d930744160eb09a682f450964/Examples/bash/Makefile#L3)):*
> ```Makefile
> SGX_SIGNER_KEY ?= ../../Pal/src/host/Linux-SGX/signer/enclave-key.pem
> 
> ARCH_LIBDIR ?= /lib/$(shell $(CC) -dumpmachine)
> ```

@stefanberger: Could you check if this works for you?
___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-Mfc9Baj4gMnyal4N8Q5:b-pfxrpb) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: Having two copies of this file is not amazing (the original is under `graphene/Scripts/download`). But we'll soon have a separate repository with Examples, so that's why this duplication.
</blockquote></details>

I really don't like this duplication, but also don't have better ideas for now. But maybe @boryspoplawski or @pwmarcz have?


<!-- Sent from Reviewable.io -->

2021-07-27 13:48 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

___
*[Examples/bash/Makefile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc8IgfDrs1BdrXaioT:-MfcCgts7yZsdVj5ENxY:bjbqggh) ([raw file](https://github.com/oscarlab/graphene/blob/fa9fd13ec735717d930744160eb09a682f450964/Examples/bash/Makefile#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@stefanberger: Could you check if this works for you?
</blockquote></details>

Yes, this should work on Debina and Ubuntu. 
Scripts/Makefile.configs has:
```
SYS ?= $(shell $(CC) -dumpmachine)
ARCH_LIBDIR := /lib/$(SYS)
```
but then for RHEL and the like it tests the dir and ends up setting it to /lib64
```
ifeq ($(wildcard $(ARCH_LIBDIR)/*),)
    ARCH_LIBDIR := /lib64
endif

```


<!-- Sent from Reviewable.io -->

2021-07-27 14:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @mkow, and @pwmarcz)

___
*[Examples/apache/Makefile, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc7buu8A8PXX-Wczm8:-MfcIlAa1WFJVIgh5Fs7:bgxv24c) ([raw file](https://github.com/oscarlab/graphene/blob/0f286951f01c0768224837af683e7ed513aa33e3/Examples/apache/Makefile#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we fail with a nice error message if `SGX_SIGNER_KEY` file doesn't exist after this assignment?
</blockquote></details>

I initially was hoping that `graphene-sgx-sign` failing with "Cannot find file ..." will be enough, but this is not a nice error for our users. So I guess you're right, I'll add a check on existence of this file in every Makefile. What would be a nice error message in your opinion?
___
*[Examples/bash/Makefile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc8IgfDrs1BdrXaioT:-MfcIO2EAP_eYd8e33qI:b-om93lh) ([raw file](https://github.com/oscarlab/graphene/blob/fa9fd13ec735717d930744160eb09a682f450964/Examples/bash/Makefile#L3)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

Yes, this should work on Debina and Ubuntu. 
Scripts/Makefile.configs has:
```
SYS ?= $(shell $(CC) -dumpmachine)
ARCH_LIBDIR := /lib/$(SYS)
```
but then for RHEL and the like it tests the dir and ends up setting it to /lib64
```
ifeq ($(wildcard $(ARCH_LIBDIR)/*),)
    ARCH_LIBDIR := /lib64
endif

```
</blockquote></details>

@stefanberger With this PR, we remove the dependency on `Makefile.configs` from all examples (to make them self-contained). So the idea is that they work out-of-the-box on Debian/Ubuntu, but for RHEL/Fedora/CentOS the fix is like this: `ARCH_LIBDIR="/lib64" make`.

Is this fine for you? Basically, you need to `export ARCH_LIBDIR` in your CI before you run your tests.


<!-- Sent from Reviewable.io -->

2021-07-27 14:17 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfcJcKP12_AADDod1kD:b-th7vfd) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I really don't like this duplication, but also don't have better ideas for now. But maybe @boryspoplawski or @pwmarcz have?
</blockquote></details>

What's wrong with it? Since this will be moved to a separate repo, then we have no other option (as creating another repo for such tools would be a overkill).


<!-- Sent from Reviewable.io -->

2021-07-27 14:24 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @pwmarcz, and @stefanberger)

___
*[Examples/apache/Makefile, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc7buu8A8PXX-Wczm8:-MfcL0iBCSHF-A8UoFxO:b1q6nms) ([raw file](https://github.com/oscarlab/graphene/blob/0f286951f01c0768224837af683e7ed513aa33e3/Examples/apache/Makefile#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I initially was hoping that `graphene-sgx-sign` failing with "Cannot find file ..." will be enough, but this is not a nice error for our users. So I guess you're right, I'll add a check on existence of this file in every Makefile. What would be a nice error message in your opinion?
</blockquote></details>

Hmm, something like "\`SGX_SIGNER_KEY\` env is missing or the file doesn't exist" should be enough IMO.
___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfcKuV7CfE1apCWlc1C:bvkqrll) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What's wrong with it? Since this will be moved to a separate repo, then we have no other option (as creating another repo for such tools would be a overkill).
</blockquote></details>

Dunno, maybe we could package it in graphene-dev or something similar?


<!-- Sent from Reviewable.io -->

2021-07-27 14:51 UTC, stefanberger reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Examples/bash/Makefile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc8IgfDrs1BdrXaioT:-MfcRd_H4gt7PvRiDIvJ:b-gbhpxg) ([raw file](https://github.com/oscarlab/graphene/blob/fa9fd13ec735717d930744160eb09a682f450964/Examples/bash/Makefile#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@stefanberger With this PR, we remove the dependency on `Makefile.configs` from all examples (to make them self-contained). So the idea is that they work out-of-the-box on Debian/Ubuntu, but for RHEL/Fedora/CentOS the fix is like this: `ARCH_LIBDIR="/lib64" make`.

Is this fine for you? Basically, you need to `export ARCH_LIBDIR` in your CI before you run your tests.
</blockquote></details>

It's fine for me but the CentOS users may not know about it....


<!-- Sent from Reviewable.io -->

2021-07-27 15:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Examples/bash/Makefile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc8IgfDrs1BdrXaioT:-Mfcf9b40de9XoZAEgkq:bubu7wt) ([raw file](https://github.com/oscarlab/graphene/blob/fa9fd13ec735717d930744160eb09a682f450964/Examples/bash/Makefile#L3)):*
<details><summary><i>Previously, stefanberger (Stefan Berger) wrote…</i></summary><blockquote>

It's fine for me but the CentOS users may not know about it....
</blockquote></details>

Should I add like this in every example Makefile:
```
ARCH_LIBDIR ?= /lib/$(shell $(CC) -dumpmachine)
ifeq ($(wildcard $(ARCH_LIBDIR)/*),)
    ARCH_LIBDIR := /lib64  # RHEL/Fedora/CentOS distros use this path for arch-specific libraries
endif
```

I can add it but looks a bit... ugly. @mkow @pwmarcz ?
___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfcZrhLAcPpsOe7OgnW:b-oppjy7) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Dunno, maybe we could package it in graphene-dev or something similar?
</blockquote></details>

Why graphene-dev? Anyway, this sounds complicated. Maybe let's stick with this `download` script here and we'll think about this later? (We have a similar issue with https://github.com/oscarlab/graphene/blob/master/Examples/common_tools/benchmark-http.sh, we may want to solve the issue for both then.)


<!-- Sent from Reviewable.io -->

2021-07-27 16:43 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Examples/bash/Makefile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc8IgfDrs1BdrXaioT:-MfcprtJDUX1uiBuEhGU:bd5w5pw) ([raw file](https://github.com/oscarlab/graphene/blob/fa9fd13ec735717d930744160eb09a682f450964/Examples/bash/Makefile#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Should I add like this in every example Makefile:
```
ARCH_LIBDIR ?= /lib/$(shell $(CC) -dumpmachine)
ifeq ($(wildcard $(ARCH_LIBDIR)/*),)
    ARCH_LIBDIR := /lib64  # RHEL/Fedora/CentOS distros use this path for arch-specific libraries
endif
```

I can add it but looks a bit... ugly. @mkow @pwmarcz ?
</blockquote></details>

I'd skip this, we say in the readme that the examples are for Ubuntu, it's expected that you may need more/different configuration for other distros.
___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfcqDBO1RlXUHWAhd1h:b-wv6y5b) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
> Why graphene-dev?

Same as with other packages, they often have a `-dev` version with some tooling for development (e.g. headers).


<!-- Sent from Reviewable.io -->

2021-07-27 16:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Examples/bash/Makefile, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc8IgfDrs1BdrXaioT:-Mfcsm_y2N0eHU4YSyX-:b-c1yiev) ([raw file](https://github.com/oscarlab/graphene/blob/fa9fd13ec735717d930744160eb09a682f450964/Examples/bash/Makefile#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd skip this, we say in the readme that the examples are for Ubuntu, it's expected that you may need more/different configuration for other distros.
</blockquote></details>

OK, I am skipping this.
___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfctkgaAu3sBrIhn_FN:b-ftjxcj) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Why graphene-dev?

Same as with other packages, they often have a `-dev` version with some tooling for development (e.g. headers).
</blockquote></details>

My point was that users won't want to install the `graphene-dev` package just to build their examples. Wouldn't we want users to run these Makefiles with just the `graphene` package?


<!-- Sent from Reviewable.io -->

2021-07-27 17:11 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-Mfcw9e844U7XeeO-pqK:b-bv4mvf) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

My point was that users won't want to install the `graphene-dev` package just to build their examples. Wouldn't we want users to run these Makefiles with just the `graphene` package?
</blockquote></details>

I'd say "yes", they need `graphene-dev` to develop enclaves with Graphene and vanilla `graphene` to run enclaves already prepared with Graphene. But maybe I'm getting this wrong?
CC: @woju


<!-- Sent from Reviewable.io -->

2021-07-28 07:08 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: 2 of 21 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Examples/apache/Makefile, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc7buu8A8PXX-Wczm8:-MffvsVH5NqXfLbltqLe:b-z9e2bh) ([raw file](https://github.com/oscarlab/graphene/blob/0f286951f01c0768224837af683e7ed513aa33e3/Examples/apache/Makefile#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, something like "\`SGX_SIGNER_KEY\` env is missing or the file doesn't exist" should be enough IMO.
</blockquote></details>

Done. Please note that I brought the check under the "graphene-sgx-sign" target (because we don't want to scare the user who just wants to build the non-SGX version). This is true for all examples except `ra-tls-mbedtls` and `ra-tls-secret-prov` -- these examples are SGX-only anyway.
___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MffvuuA4EaLjzx8cosO:b-m6qobt) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd say "yes", they need `graphene-dev` to develop enclaves with Graphene and vanilla `graphene` to run enclaves already prepared with Graphene. But maybe I'm getting this wrong?
CC: @woju
</blockquote></details>

I see your point. Anyway, this is not for this PR.


<!-- Sent from Reviewable.io -->

2021-07-28 09:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: 2 of 21 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Examples/apache/Makefile, line 19 at r2](https://reviewable.io/reviews/oscarlab/graphene/2582#-Mfc7buu8A8PXX-Wczm8:-MfgO20l2N5S60m0FOkL:bjc2rb7) ([raw file](https://github.com/oscarlab/graphene/blob/0f286951f01c0768224837af683e7ed513aa33e3/Examples/apache/Makefile#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Please note that I brought the check under the "graphene-sgx-sign" target (because we don't want to scare the user who just wants to build the non-SGX version). This is true for all examples except `ra-tls-mbedtls` and `ra-tls-secret-prov` -- these examples are SGX-only anyway.
</blockquote></details>

UPDATE: It was a bad idea to "exempt" `ra-tls-mbedtls` and `ra-tls-secret-prov` because our CI scripts do things like `make distclean` *after* the SGX signing key is removed. Anyway, changed these two examples to be the same as the rest.


<!-- Sent from Reviewable.io -->

2021-07-28 09:27 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfgPqsQ0yKDvDvN-kHw:b-xbgcxi) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see your point. Anyway, this is not for this PR.
</blockquote></details>

We could also treat this tool similar to `graphene-manifest` and `graphene-sgx-sign`, and keep it as part the `graphene` package (put it in bin directory as `graphene-download`?)


<!-- Sent from Reviewable.io -->

2021-07-29 01:25 UTC, mkow approved these changes
> Reviewed 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-Mfjofnf6wggDhqJ8oua:biy0zrt) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

We could also treat this tool similar to `graphene-manifest` and `graphene-sgx-sign`, and keep it as part the `graphene` package (put it in bin directory as `graphene-download`?)
</blockquote></details>

Yup, that's what I thought of, but it probably shouldn't go to the main package. But hard to say...


<!-- Sent from Reviewable.io -->

2021-07-29 12:58 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-07-29 13:09 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2582)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Examples/common_tools/download, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene/2582#-MfY5iCF6SZwldbHCOdF:-MfmMvppEe0cWhAyXpCb:bv1di6c) ([raw file](https://github.com/oscarlab/graphene/blob/bb146ac3ef73ef0ca839572ea26a2128c7f9ac5b/Examples/common_tools/download#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, that's what I thought of, but it probably shouldn't go to the main package. But hard to say...
</blockquote></details>

I agree it's a bit weird to have a tool that's for downloading files and checking hashes. But if there are no other tools that we would put in `graphene-dev`, then I wouldn't worry about putting it in a main package.

By the way, someday we might want to have some higher-level tool (a "build system"?) that could help remove more boilerplate from these Makefiles. I think of these three (-manifest, -sgx-sign, -downloads) as parts of that tool...


<!-- Sent from Reviewable.io -->

2021-07-29 13:25 UTC, merged