[LibOS] Convert some `shim_qstr` instances to C strings
oscarlab/graphene pull request #2585
Opened 2021-07-27 11:46 UTC by pwmarcz

## Description of the changes 

This change gets rid of the following `shim_qstr` instances:

- `shim_dentry.name`
- `shim_mount.path`, `shim_dentry.uri`
- parameter to `follow_link` callback

The remaining ones are mostly `shim_handle.uri` and URIs used by pipe filesystem, but it's somewhat harder to change them, so I wanted to push this first.

## How to test this PR? 

This should be well-covered by existing tests.

2021-07-27 13:22 UTC, dimakuv requested changes
> Reviewed 19 of 19 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/shim_checkpoint.c, line 227 at r1](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfc4tyT8-1EiTwjHjbK:-Mfc4tyU-kbewqBqph1H:b-iaslw9) ([raw file](https://github.com/oscarlab/graphene/blob/d71044fb554a1f26e9ee03e382ba75c42f79491d/LibOS/shim/src/shim_checkpoint.c#L227)):*
> ```C
>     char* new_str = (char*)base + ADD_CP_OFFSET(len + 1);
>     memcpy(new_str, str, len + 1);
>     *str_ptr = new_str;
> ```

This feels wrong. Here you're rewiring the parent's pointer to the newly created string somewhere in the checkpoint blob. You seem to be doing this to simplify your life: you don't need the restore function (`BEGIN_RS_FUNC`) anymore. But I'm pretty sure this leads to nasty side effects: you may have other pointers that point somewhere inside the original string, and now you have a discrepancy (because you have two objects). Also, I think the checkpoint blob is immediately removed after being sent to the child, so you have a dangling pointer. Also, I think this leaves you with a memory leak of the old string.

Hm... Or did I forget how this checkpointing magic works?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 451 at r1](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfc5fq9Bqs-0bEh4TGf:-Mfc5fq9Bqs-0bEh4TGg:b-32mkyv) ([raw file](https://github.com/oscarlab/graphene/blob/d71044fb554a1f26e9ee03e382ba75c42f79491d/LibOS/shim/src/bookkeep/shim_handle.c#L451)):*
> ```C
>     if (!qstrempty(&hdl->uri))
>         return qstrgetstr(&hdl->uri);
>     if (hdl->dentry && hdl->dentry->name[0] != '\0')
> ```

Is this guaranteed that a dentry always has a non-NULL name? Otherwise you have a segfault here.


<!-- Sent from Reviewable.io -->

2021-07-27 14:43 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: 16 of 19 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_checkpoint.c, line 227 at r1](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfc4tyT8-1EiTwjHjbK:-MfcEC4OEZyycJBtwxBO:baqw4nj) ([raw file](https://github.com/oscarlab/graphene/blob/d71044fb554a1f26e9ee03e382ba75c42f79491d/LibOS/shim/src/shim_checkpoint.c#L227)):*
Yeah, I think that's not how it should be (although that's hard to tell because the checkpoint system is super confusing and not documented at all...)

I tried to write a new version, please take a look. Here are my responses:

>Here you're rewiring the parent's pointer to the newly created string somewhere in the checkpoint blob. You seem to be doing this to simplify your life: you don't need the restore function (BEGIN_RS_FUNC) anymore.

Right. I think that instead of modifying `*obj` (which is the "source", in an old object) I should take it, save the content, and modify `*objp` which is the ("destination", for an already-copied object). Fixed.

However, I still maintain I don't need the restore function. The restore function seems to be for "inflating" the new object, e.g. adjusting its members. In our case, the new object is the string, and its content does not need any adjusting.

>But I'm pretty sure this leads to nasty side effects: you may have other pointers that point somewhere inside the original string, and now you have a discrepancy (because you have two objects).

Yes, that's what this `GET_FROM_CP_MAP` etc. seems to do: if there are multiple pointers to the same object, the object should get checkpointed only once. 

Fixed. However, I'm afraid I cannot do anything about pointers that point _somewhere inside_ the original string, just to the beginning of it. (We don't seem to have any such pointers, though).

>Also, I think the checkpoint blob is immediately removed after being sent to the child, so you have a dangling pointer. Also, I think this leaves you with a memory leak of the old string.

I think you assume that I modify the old object. I made sure to modify only the new object (this function is invoked by `DO_CP_IN_MEMBER`), becase that's what the code for `qstr` did. But, as mentioned above, the right way seems to be to modify only the "destination" pointer, so that should be fixed now.

---

By the way, for when we get to changing the checkpoint system: I think that this paradigm of "copy this data and adjust some pointers -> directly use the copied data" is misguided. It would be better to have explicit serialization/deserialization steps where you have to write (and then read) all the fields. The "checkpoint blob" would be something that you receive, deserialize, and then remove from memory. Do you see it that way?
___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 451 at r1](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfc5fq9Bqs-0bEh4TGf:-MfcNSGF7kx2fSwOMjmi:bhc0u24) ([raw file](https://github.com/oscarlab/graphene/blob/d71044fb554a1f26e9ee03e382ba75c42f79491d/LibOS/shim/src/bookkeep/shim_handle.c#L451)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this guaranteed that a dentry always has a non-NULL name? Otherwise you have a segfault here.
</blockquote></details>

Yes, `shim_dentry.name` is never null.


<!-- Sent from Reviewable.io -->

2021-07-27 17:47 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/shim_checkpoint.c, line 227 at r1](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfc4tyT8-1EiTwjHjbK:-Mfd0kkWAWypEr8xZLca:b-ssd4nr) ([raw file](https://github.com/oscarlab/graphene/blob/d71044fb554a1f26e9ee03e382ba75c42f79491d/LibOS/shim/src/shim_checkpoint.c#L227)):*
Yes, the new version looks correct.

> However, I still maintain I don't need the restore function. The restore function seems to be for "inflating" the new object, e.g. adjusting its members. In our case, the new object is the string, and its content does not need any adjusting.

You are right, I didn't think that through. You already have the `CP_REBASE(dent->name)` statement to fix the pointer to the string in the child process, so nothing else to be done.

> Yes, that's what this GET_FROM_CP_MAP etc. seems to do: if there are multiple pointers to the same object, the object should get checkpointed only once.

You are right again. I actually don't know if different dentries can point to the same underlying name string (i.e., `dent1->name == dent2->name`. From what I remember, this is not possible in the code -- in this case you *could* get rid of this `if (!off) {`. But keeping it doesn't harm anyway. UPDATE: Well, you also use this code for `mount.path` and `mount.uri`, and probably will use it in other places, so keeping this safety check is good.

> However, I'm afraid I cannot do anything about pointers that point somewhere inside the original string, just to the beginning of it. (We don't seem to have any such pointers, though).

We seem to be thinking about different scenarios. I meant that in your original code, you modified the old object, and that would lead to discrepancies *in the parent*. But your comment seems to imply that you're worried about the "restore checkpoint" logic *in the child*. But you're right, we don't have such pointers during checkpointing.

> I think you assume that I modify the old object. I made sure to modify only the new object (this function is invoked by DO_CP_IN_MEMBER), becase that's what the code for qstr did. 

Yeah, I got confused by our beautiful checkpointing macros `DO_CP_MEMBER` vs `DO_CP_IN_MEMBER`.

---

>  The "checkpoint blob" would be something that you receive, deserialize, and then remove from memory.

Yes, this is the sane way of doing checkpointing. Whatever we have now is legacy (from ~2014), and I periodically marvel at its implementation. It's kinda beautiful in its own way. But I (and everyone who touched checkpointing code, just ask Borys) want this code rewritten asap.

Btw, the sane checkpointing implementation via proper serialization/deserialization will open the way for SCM_RIGHTS send syscall (to send FDs from parent enclave to child enclave -- Graphene currently can't support it).
___
*[LibOS/shim/src/shim_checkpoint.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfd0M53EkaVcXgfMMnu:-Mfd0M53EkaVcXgfMMnv:b-6035rr) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/shim_checkpoint.c#L223)):*
> ```C
>     assert(size == sizeof(char));
> 
>     char* str = obj;
> ```

You seem to not really use `str` below other than one place. Please either remove this `str` or use it instead of `obj`.


<!-- Sent from Reviewable.io -->

2021-07-28 13:15 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: 18 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/shim_checkpoint.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfd0M53EkaVcXgfMMnu:-MfhEUir1vX9LrZUgbVF:b-l6xzsb) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/shim_checkpoint.c#L223)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You seem to not really use `str` below other than one place. Please either remove this `str` or use it instead of `obj`.
</blockquote></details>

Done. I changed the code below to use `str`, I think that's the better choice becuase `strlen(obj)` looks too ugly.


<!-- Sent from Reviewable.io -->

2021-07-28 13:22 UTC, boryspoplawski requested changes
> Reviewed 16 of 19 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: 18 of 19 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 127 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh8u-NCRXYeIuHJEkC:-Mfh8u-ODJjqZ1suFviY:b-glqyai) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/include/shim_fs.h#L127)):*
> ```objc
>     /* File name, maximum of NAME_MAX characters. By convention, the root has an empty name. Does
>      * not change. */
>     char* name;
> ```

Length of this name seems to be used in some places, isn't it worth to stash it together with the pointer (maybe we use it just in couple of places and it's not worth)?
___
*[LibOS/shim/include/shim_fs.h, line 256 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh9A-V2wrNpn-3_DKc:-Mfh9A-WD_Dyi8MI8HaL:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/include/shim_fs.h#L256)):*
> ```objc
> 
>     char* path;
>     char* uri;
> ```

ditto
___
*[LibOS/shim/src/shim_checkpoint.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfd0M53EkaVcXgfMMnu:-Mfh5Lb294stSS32abpS:b-5yp84s) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/shim_checkpoint.c#L223)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You seem to not really use `str` below other than one place. Please either remove this `str` or use it instead of `obj`.
</blockquote></details>

+1 to removing it.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 92 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh743P8Jah_bLIVz9_:-Mfh743Q6PNCqfLtdMkw:b-7evh2d) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/fs/shim_dcache.c#L92)):*
> ```C
>     char* name = strdup("");
>     if (!name) {
>         free_dentry(g_dentry_root);
> ```

Shouldn't we also clear `g_dentry_root = NULL`?
Oh, this is init code, so it does not matter probably, but please do for sanity.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 231 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh7iedDvKIpfuf2fJC:-Mfh7iee-orF6R14V03k:b-ycjk25) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/fs/shim_dcache.c#L231)):*
> ```C
>     LISTP_FOR_EACH_ENTRY_SAFE(dent, tmp, &parent->children, siblings) {
>         size_t dent_name_len = strlen(dent->name);
>         if (dent_name_len == name_len && memcmp(dent->name, name, name_len) == 0) {
> ```

Why not `!strcmp(a, b)`?
___
*[LibOS/shim/src/fs/shim_namei.c, line 138 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-MfhFrMj8CI09gUmdk9M:-MfhFrMk4q-CqvmyoyNp:b-cnfn4j) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/fs/shim_namei.c#L138)):*
> ```C
>                                 unsigned int link_depth) {
>     int ret;
>     char* target;
> ```

Please initialized this to `NULL`. You free it unconditionally (maybe `follow_link` initializes this in case of failures, I don't know, but explicitly setting is better at least for readability)


<!-- Sent from Reviewable.io -->

2021-07-28 13:22 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-07-29 13:05 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: 13 of 19 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/shim_fs.h, line 127 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh8u-NCRXYeIuHJEkC:-MfmGq2lBwfPlfs7wOOh:b7hihr9) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/include/shim_fs.h#L127)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Length of this name seems to be used in some places, isn't it worth to stash it together with the pointer (maybe we use it just in couple of places and it's not worth)?
</blockquote></details>

I think it's worth it, because file lookup right now traverses the whole directory. It needs to be fixed someday, but in the meantime, I don't want to make it even worse (especially since #2593 suggest this would be a problem for files in `/lib` and such)

I added `name_len` and converted the code to use it.
___
*[LibOS/shim/include/shim_fs.h, line 256 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh9A-V2wrNpn-3_DKc:-MfmHIkiD2DJTN35PErQ:bj657gm) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/include/shim_fs.h#L256)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Here, I don't believe it would do much: we use this to construct file URIs, so we need to traverse the whole URI anyway.
___
*[LibOS/shim/src/shim_checkpoint.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfd0M53EkaVcXgfMMnu:-MfmHr8FBkNtTXAgVO8I:b-93xexv) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/shim_checkpoint.c#L223)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

+1 to removing it.
</blockquote></details>

`strlen(obj)` on a `void*` pointer looks weird to me, but I don't care that much. Changed.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 92 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh743P8Jah_bLIVz9_:-MfmIYdKDtibXbpeXAsc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/fs/shim_dcache.c#L92)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Shouldn't we also clear `g_dentry_root = NULL`?
Oh, this is init code, so it does not matter probably, but please do for sanity.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 231 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-Mfh7iedDvKIpfuf2fJC:-MfmIoKU3qP9Zo_PuX6l:bwwz2rw) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/fs/shim_dcache.c#L231)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `!strcmp(a, b)`?
</blockquote></details>

Because `name` is not null-terminated (it's a string fragment from larger path).
___
*[LibOS/shim/src/fs/shim_namei.c, line 138 at r3](https://reviewable.io/reviews/oscarlab/graphene/2585#-MfhFrMj8CI09gUmdk9M:-MfmJ4YR2q3XUJ-9sRGj:bdf3nae) ([raw file](https://github.com/oscarlab/graphene/blob/21b5d53afe11d5d174eb042b406962e9ba180ae9/LibOS/shim/src/fs/shim_namei.c#L138)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please initialized this to `NULL`. You free it unconditionally (maybe `follow_link` initializes this in case of failures, I don't know, but explicitly setting is better at least for readability)
</blockquote></details>

Right, it should be initialized. Fixed.


<!-- Sent from Reviewable.io -->

2021-07-29 13:26 UTC, mkow approved these changes
> Reviewed 13 of 19 files at r1, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-07-29 14:03 UTC, boryspoplawski approved these changes
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-29 15:03 UTC, dimakuv approved these changes
> Reviewed 5 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-29 15:09 UTC, dimakuv approved these changes
> Reviewed 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-07-29 15:11 UTC, boryspoplawski approved these changes
> Reviewed 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-29 15:30 UTC, mkow approved these changes
> Reviewed 9 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2585)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-30 06:25 UTC, dimakuv commented
Jenkins, retest Jenkins-20.04 please (`sendfile09` LTP test timed out, I need to debug it)

2021-07-30 06:52 UTC, merged