[LibOS] Fix mismatching data type in do_handle_read and do_handle_write causing overflow
oscarlab/graphene pull request #2590
Opened 2021-07-28 10:50 UTC by svenkata9

Signed-off-by: Sankaranarayanan Venkatasubramanian <sankaranarayanan.venkatasubramanian@intel.com>

## Description of the changes 
I encountered an issue while executing a workload where the `read` call was returning error causing the `fread` operation in the application to fail. This is rootcaused to mismatching data types between `shim_do_read` (and `shim_do_write`) and `do_handle_read` (and `do_handle_write`) calls. The incoming argument `count ` in `read` and `write` calls is of data type `size_t` whereas `do_handle_read` and `do_handle_write` takes this `count` as `int` causing an overflow and resulting in error.

This PR is to fix this issue by changing the data type of the argument `count`  in `do_handle_read` and `do_handle_write` to `size_t`.

## How to test this PR?

2021-07-28 11:18 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

___
*[LibOS/shim/include/shim_handle.h, line 334 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpFdP5bVtJUrXhpRw:-MfgpFdP5bVtJUrXhpRx:b-xbl8jy) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/include/shim_handle.h#L334)):*
> ```objc
> int get_file_size(struct shim_handle* file, uint64_t* size);
> 
> int do_handle_read(struct shim_handle* hdl, void* buf, size_t count);
> ```

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
___
*[LibOS/shim/include/shim_handle.h, line 335 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpKHi8yOcnHsF5yxN:-MfgpKHi8yOcnHsF5yxO:b-xbl8jy) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/include/shim_handle.h#L335)):*
> ```objc
> 
> int do_handle_read(struct shim_handle* hdl, void* buf, size_t count);
> int do_handle_write(struct shim_handle* hdl, const void* buf, size_t count);
> ```

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
___
*[LibOS/shim/src/sys/shim_open.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpKvo4F2DVwNcHwP9:-MfgpKvo4F2DVwNcHwPA:b-xbl8jy) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L28)):*
> ```C
> #include "stat.h"
> 
> int do_handle_read(struct shim_handle* hdl, void* buf, size_t count) {
> ```

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
___
*[LibOS/shim/src/sys/shim_open.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpVzk-73lJd-uKxS1:-MfgpVzk-73lJd-uKxS2:b-xbl8jy) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L58)):*
> ```C
>     }
> 
>     int ret = do_handle_read(hdl, buf, count);
> ```

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
___
*[LibOS/shim/src/sys/shim_open.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpNQo-3oRM-WluSNp:-MfgpNQo-3oRM-WluSNq:b-xbl8jy) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L66)):*
> ```C
> }
> 
> int do_handle_write(struct shim_handle* hdl, const void* buf, size_t count) {
> ```

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
___
*[LibOS/shim/src/sys/shim_open.c, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-Mfgp_oREG_EEwXF_pCs:-Mfgp_oREG_EEwXF_pCt:b-xbl8jy) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L90)):*
> ```C
>         return -EBADF;
> 
>     int ret = do_handle_write(hdl, buf, count);
> ```

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.


<!-- Sent from Reviewable.io -->

2021-07-28 11:18 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @svenkata9)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpdHM4rZkZqsgoh-3:-MfgpdHM4rZkZqsgoh-4:b4c8fec) (no related file):*
@pwmarcz Could you also take a look?

---


<!-- Sent from Reviewable.io -->

2021-07-28 11:52 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pwmarcz and @svenkata9)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpdHM4rZkZqsgoh-3:-Mfgx64g3FHW8-ZGb5C0:b-tyzf3s) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@pwmarcz Could you also take a look?
</blockquote></details>

Looks good, except for the `ssize_t` return type. Thanks @svenkata9!

---


<!-- Sent from Reviewable.io -->

2021-07-28 14:42 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: 0 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @pwmarcz, and @svenkata9)

___
*[LibOS/shim/include/shim_handle.h, line 334 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpFdP5bVtJUrXhpRw:-MfhYg2l8V2vsC1UhXvY:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/include/shim_handle.h#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_handle.h, line 335 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpKHi8yOcnHsF5yxN:-MfhZAlP2Xft5PDCUpis:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/include/shim_handle.h#L335)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpKvo4F2DVwNcHwP9:-MfhZBshAAVe8QoDBulC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpVzk-73lJd-uKxS1:-MfhZCmeAl-n2NLAuXqZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpNQo-3oRM-WluSNp:-MfhZDWn3FPZH65QKuUc:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
</blockquote></details>

Done.
___
*[LibOS/shim/src/sys/shim_open.c, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2590#-Mfgp_oREG_EEwXF_pCs:-MfhZEAt8PsahjuksArR:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/acd923921d2d81494b49d7313f748da27a794149/LibOS/shim/src/sys/shim_open.c#L90)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One more issue here: return type is also wrong. Please replace `int` -> `ssize_t`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 14:42 UTC, svenkata9 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: 0 of 2 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2590#-MfgpdHM4rZkZqsgoh-3:-MfhZM1e0KAd-3yrxrDD:b-896fix) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Looks good, except for the `ssize_t` return type. Thanks @svenkata9!
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-07-28 14:55 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-07-28 14:55 UTC, dimakuv commented
Jenkins, test this please

2021-07-28 19:03 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-29 00:32 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-29 00:33 UTC, mkow reviewed
Seems this survived my grepping when I was fixing #152 :)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590#-:-MfjfXHPDwR_abe_ec0_:bb2xucp)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-07-29 00:47 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-07-29 00:48 UTC, mkow commented
Jenkins, retest this please

2021-07-29 06:23 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (`sendfile09` LTP test timed out, have we seen this before?)

2021-07-29 06:54 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-07-29 07:01 UTC, svenkata9 commented
> Jenkins, retest Jenkins-Debug-20.04 please (`sendfile09` LTP test timed out, have we seen this before?)

Seeing this here as well: https://github.com/oscarlab/graphene/pull/2555

2021-07-29 10:29 UTC, pwmarcz approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2590)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-07-29 10:42 UTC, merged