[GSC] Update GSC for latest master build changes
oscarlab/graphene pull request #2594
Opened 2021-07-29 13:35 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 

This PR allows GSC to work successfully with latest master. Meson build steps are included in gsc/templates/Dockerfile.ubuntu18.04.compile.template file. The output of meson build is stored inside */graphene/meson_build_output* directory and path to this output directory is included in $PATH and $PYTHONPATH environment variables. 

Few more changes:
(i) loader.preload variable in entrypoint.manifest.template points to meson build output sub-directory, i.e., */graphene/meson_build_output*/lib/x86_64-linux-gnu/graphene/.
(ii) graphene-sgx-sign and graphene-sgx-get-token binaries are included from meson build output sub-directory, i.e. ,
*/graphene/meson_build_output*/bin. 

## How to test this PR? 
GSC build and sign steps should pass, and resultant gsc image should successfully run. 
Jenkins must pass.

2021-07-30 07:14 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqBoW-8hd619O54-V_:-MfqBoW-8hd619O54-Va:b-162yu2) (no related file):*
Please also change `graphene/master/Documentation/manpages/gsc.rst` -- remove the warning about the "last working commit" from there.

Could you also check that this GSC documentation is generally correct? I think so, but just in case we should verify that it's up-to-date. (The link to our readthedocs page: https://graphene.readthedocs.io/en/latest/manpages/gsc.html)

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqFIsnCMOH-5SkdU9B:-MfqFIsnCMOH-5SkdU9C:b-m0k3b) (no related file):*
There is one recurrent issue in this PR: you mix the new-way `/graphene/meson_build_output` path with the old-way paths.

In our new Meson way, all Graphene-related binaries, libraries, config files, GDB-integration files are all located under `/graphene/meson_build_output`, so there is **nothing** that should be COPYed from other directories.

So please remove all occurences of the old way, and replace with the new-way paths. I tried to mark all such places in your PR, but I could have missed some.

---
___
*[Tools/gsc/templates/apploader.template, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqCafNExxJm48nQ7rd:-MfqCafO3Y8mLP1-fKfF:bdo23cp) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/apploader.template#L8)):*
> ```
> if [ -z "$GSC_PAL" ] || [ "$GSC_PAL" == "Linux-SGX" ]
> then
>     GSC_PAL=Linux-SGX
> ```

This variable won't be needed if you replace the below with `graphene-sgx`
___
*[Tools/gsc/templates/apploader.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqCNcL-JjG0PRWm_Mv:-MfqCNcL-JjG0PRWm_Mw:b9dzelo) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/apploader.template#L10)):*
> ```
>     GSC_PAL=Linux-SGX
>     graphene-sgx-get-token -output /entrypoint.token -sig /entrypoint.sig
>     /graphene/Runtime/pal-$GSC_PAL /graphene/Runtime/libpal-$GSC_PAL.so init /entrypoint {% if insecure_args %}{{binary_arguments}} "${@}"{% endif %}
> ```

This can be replaced by simply `graphene-sgx`. So it will look like this:
```
graphene-sgx /entrypoint {% if insecure_args %}{{binary_arguments}} "${@}"{% endif %}
```
___
*[Tools/gsc/templates/apploader.template, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqCVX41oHM_zeMuBW6:-MfqCVX41oHM_zeMuBW7:bnmaovx) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/apploader.template#L12)):*
> ```
>     /graphene/Runtime/pal-$GSC_PAL /graphene/Runtime/libpal-$GSC_PAL.so init /entrypoint {% if insecure_args %}{{binary_arguments}} "${@}"{% endif %}
> else
>     /graphene/Runtime/pal-$GSC_PAL /graphene/Runtime/libpal-$GSC_PAL.so init /entrypoint {{binary_arguments}} "${@}"
> ```

This can be replaced by simply `graphene-direct`. So it will look like this:
```
graphene-direct /entrypoint {{binary_arguments}}
```
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqEe9u2QE86LrPJ1zO:-MfqEe9u2QE86LrPJ1zP:b7kniv) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L38)):*
> ```
>     && mkdir -p /graphene/Scripts \
>     && mkdir -p /graphene/Tools \
>     && mkdir -p /graphene/python \
> ```

You're not supposed to have any other directories other than `/graphene/meson_build_output`. Please remove all these `mkdir` commands.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqElrm73voP1-3Vhgj:-MfqElrm73voP1-3Vhgk:bfop3m9) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L45)):*
> ```
> COPY --from=graphene /graphene/Scripts/Makefile.Host /graphene/Scripts
> COPY --from=graphene /graphene/Tools/argv_serializer /graphene/Tools
> COPY --from=graphene /graphene/python /graphene/python
> ```

You're not supposed to have any other directories other than `/graphene/meson_build_output`. Please remove all these `COPY` commands.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqEodx3IANkYqrDzjb:-MfqEodx3IANkYqrDzjc:by1eojf) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L66)):*
> ```
> COPY --from=graphene /graphene/Pal/src/host/Linux-SGX/gdb_integration/graphene_sgx.gdb \
>                      /graphene/Pal/src/host/Linux-SGX/gdb_integration/
> RUN ln -sf /graphene/Pal/gdb_integration /graphene/Pal/src/host/Linux-SGX/gdb_integration/common
> ```

You're not supposed to have any other directories other than `/graphene/meson_build_output`. Please remove all these `COPY/RUN` commands. All these GDB integration files should be found somewhere under `/graphene/meson_build_output`, and you don't need to copy anything.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqF1LpDRoFnR0jVKhb:-MfqF1LpDRoFnR0jVKhc:bg8bytu) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L75)):*
> ```
> 
> # For convenience (e.g. for debugging), create a link to pal_loader in the root dir
> RUN ln -sf /graphene/Runtime/pal_loader
> ```

Please remove this. `pal_loader` is not used by Graphene anymore.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqF4RW1t3UtJwYfji4:-MfqF4RW1t3UtJwYfji5:bd31ro3) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L79)):*
> ```
> # Generate trusted arguments if required
> {% if not insecure_args %}
> RUN /graphene/Tools/argv_serializer {{binary}} {{binary_arguments}} "{{"\" \"".join(cmd)}}" > /trusted_argv
> ```

Please change this path to wherever `argv_serializer` is located under `/graphene/meson_build_output`.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqD2afDC1TbbJnZFCH:-MfqD2afDC1TbbJnZFCI:b-lp12km) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template#L18)):*
> ```
>         python3-protobuf \
>         wget \
>         meson \
> ```

Please sort this list so that `meson` is between `l` and `p` letters
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqDcT_AZSabkw8wdU-:-MfqDcT_AZSabkw8wdU0:b1qy6yy) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template#L49)):*
> ```
>     && ninja -C build \
>     && ninja -C build install
> {% endif %}
> ```

Actually, I see no reason to *not* build `graphene-direct` by default. So I suggest to combine these two cases into one and simply do:
```
RUN cd /graphene \
    && make -s -j WERROR=1 SGX=1 {% if debug %} DEBUG=1 {% endif %} \
    && meson build - [...]

2021-07-30 08:13 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqBoW-8hd619O54-V_:-MfqNKhmB0Xnpp4hjasi:bd25nlw) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also change `graphene/master/Documentation/manpages/gsc.rst` -- remove the warning about the "last working commit" from there.

Could you also check that this GSC documentation is generally correct? I think so, but just in case we should verify that it's up-to-date. (The link to our readthedocs page: https://graphene.readthedocs.io/en/latest/manpages/gsc.html)
</blockquote></details>

Sure, will do , thanks. 

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqFIsnCMOH-5SkdU9B:-MfqNOoV-bzzOISUdmiy:bb1rxgy) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is one recurrent issue in this PR: you mix the new-way `/graphene/meson_build_output` path with the old-way paths.

In our new Meson way, all Graphene-related binaries, libraries, config files, GDB-integration files are all located under `/graphene/meson_build_output`, so there is **nothing** that should be COPYed from other directories.

So please remove all occurences of the old way, and replace with the new-way paths. I tried to mark all such places in your PR, but I could have missed some.
</blockquote></details>

I agree, I just wrote a working solution with minimum changes that will prevent GSC to break with new master build. I will do all the necessary changes to make GSC up to date with the new-way.  Thanks.

---
___
*[Tools/gsc/templates/apploader.template, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqCafNExxJm48nQ7rd:-MfqNyzm3NnT4fDg4XST:b-ghgth2) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/apploader.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This variable won't be needed if you replace the below with `graphene-sgx`
</blockquote></details>

Agree, thanks.
___
*[Tools/gsc/templates/apploader.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqCNcL-JjG0PRWm_Mv:-MfqNvh0A1Af8KY-Op7G:bkf6n13) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/apploader.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can be replaced by simply `graphene-sgx`. So it will look like this:
```
graphene-sgx /entrypoint {% if insecure_args %}{{binary_arguments}} "${@}"{% endif %}
```
</blockquote></details>

Sure, thanks.
___
*[Tools/gsc/templates/apploader.template, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqCVX41oHM_zeMuBW6:-MfqNxVo2sukJDR_pO0B:b-67antj) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/apploader.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can be replaced by simply `graphene-direct`. So it will look like this:
```
graphene-direct /entrypoint {{binary_arguments}}
```
</blockquote></details>

Sure, thanks. 
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqEe9u2QE86LrPJ1zO:-MfqO2iyAb4YjjvBsOAj:bkf6n13) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're not supposed to have any other directories other than `/graphene/meson_build_output`. Please remove all these `mkdir` commands.
</blockquote></details>

Sure, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqElrm73voP1-3Vhgj:-MfqO4Rc580g5hPZEDuP:b-t5ohw5) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're not supposed to have any other directories other than `/graphene/meson_build_output`. Please remove all these `COPY` commands.
</blockquote></details>

Sure, thanks, will do that. 
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqEodx3IANkYqrDzjb:-MfqO7ns-1YDe9qq1Bkx:b-67antj) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're not supposed to have any other directories other than `/graphene/meson_build_output`. Please remove all these `COPY/RUN` commands. All these GDB integration files should be found somewhere under `/graphene/meson_build_output`, and you don't need to copy anything.
</blockquote></details>

Sure, thanks. 
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqF1LpDRoFnR0jVKhb:-MfqO9Kd-oXsD4VfdVwo:bkf6n13) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this. `pal_loader` is not used by Graphene anymore.
</blockquote></details>

Sure, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqF4RW1t3UtJwYfji4:-MfqOD2I2ktbybbt-R0C:bkf6n13) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change this path to wherever `argv_serializer` is located under `/graphene/meson_build_output`.
</blockquote></details>

Sure, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqD2afDC1TbbJnZFCH:-MfqOEm18QzFIdX02lFA:b-67antj) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort this list so that `meson` is between `l` and `p` letters
</blockquote></details>

Sure, thanks. 
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqDcT_AZSabkw8wdU-:-MfqOHwJEvUgtyL_zcI5:bgsy82v) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template#L49)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I see no reason to *not* build `graphene-direct` by default. So I suggest to combine these two cases into one and simply do:
```
RUN cd /graphene \
    && make -s -j WERROR=1 SGX=1 {% if debug %} DEBUG=1 {% endif %} \
    && meson build --prefix="/gra [...]

2021-07-30 09:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqEGFWEG_e-ilmdFSU:-Mfqejn2COIvNNtKPLDG:b5pge8j) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template#L24)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Sure, will do that. Should I remove the graphene-sgx-sign and sgx_sign.py from new path as well, if currently we are removing these files for some security reason ?
</blockquote></details>

No, I don't see any reason for removing these files. They don't have anything security-related. Also, I don't see anything meaningful in the git log to explain why this deletion was needed (this is where my search led me to: https://github.com/oscarlab/graphene/blame/94c2d8c24e997ab0d990e984b0c52a7a2a818aa8/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template). As you can see, the deletion of these files was introduced my the very first GSC commit.

Anyway, I think these files are irrelevant. There is no need to remove them.
___
*[Tools/gsc/templates/entrypoint.manifest.template, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqENtN6UwWrpiixfNJ:-Mfqf3n9Dh0TvZsT5Ura:b-1vijnd) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Sure, I will point it to /graphene/meson_build_output/lib/x86_64-linux-gnu/graphene/runtime/glibc directory.  Thanks.
</blockquote></details>

Exactly.


<!-- Sent from Reviewable.io -->

2021-07-30 11:54 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqEGFWEG_e-ilmdFSU:-MfrFv6RB0VEk3dpuaik:b-jcyzg0) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, I don't see any reason for removing these files. They don't have anything security-related. Also, I don't see anything meaningful in the git log to explain why this deletion was needed (this is where my search led me to: https://github.com/oscarlab/graphene/blame/94c2d8c24e997ab0d990e984b0c52a7a2a818aa8/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign_manifests.template). As you can see, the deletion of these files was introduced my the very first GSC commit.

Anyway, I think these files are irrelevant. There is no need to remove them.
</blockquote></details>

ok, thanks. 
___
*[Tools/gsc/templates/entrypoint.manifest.template, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-MfqENtN6UwWrpiixfNJ:-MfrFypg1a76iamvO3-i:b-jcyzg0) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Exactly.
</blockquote></details>

ok, thanks. 


<!-- Sent from Reviewable.io -->

2021-08-02 10:37 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 1 of 7 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 264 at r2](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5QY2GB5LI0M6W9mLY:-Mg5QY2GB5LI0M6W9mLZ:b3siebk) ([raw file](https://github.com/oscarlab/graphene/blob/af411f0a471d0b62ad054bbcbb3d4a4e5ed8fbf2/Documentation/manpages/gsc.rst#L264)):*
> ```reStructuredText
>    generate a list of trusted files.  GSC excludes files and paths starting with
>    :file:`/boot`, :file:`/dev`, :file:`/proc`, :file:`/var`, :file:`/sys`,
>    :file:`/etc/mtab`, and :file:`/etc/rc`, since checksums are required which
> ```

We have two more files (not directories) excluded. These are .dockerenv and .dockerinit. Should we specify these two as well in the document?
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5OiHoDuPoguuyRtyl:-Mg5OiHoDuPoguuyRtym:bp49hlc) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L44)):*
> ```
> COPY --from=graphene /graphene/Scripts/Makefile.configs /graphene/Scripts
> COPY --from=graphene /graphene/Scripts/Makefile.Host /graphene/Scripts
> COPY --from=graphene /graphene/Tools/argv_serializer /graphene/Tools
> ```

I could not find argv_serializer under meson_build_output directory.  Also, we don't have any meson.build file for graphene/Tools directory.  Hence, keeping the old format.


<!-- Sent from Reviewable.io -->

2021-08-02 10:43 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 1 of 7 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 321 at r2](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5S5iG2sHtkUaDZVLN:-Mg5S5iG2sHtkUaDZVLO:b-9r1y1p) ([raw file](https://github.com/oscarlab/graphene/blob/af411f0a471d0b62ad054bbcbb3d4a4e5ed8fbf2/Documentation/manpages/gsc.rst#L321)):*
> ```reStructuredText
>    `Graphene.Branch` are ignored in case `Graphene.Image` is specified.
> 
> .. describe:: SGXDriver.Repository
> ```

Currently we have default values as 

SGXDriver:
    Repository: ""
    Branch:     ""

Assuming intel-next kernel on the target system. Do I need to update the manpage as well?


<!-- Sent from Reviewable.io -->

2021-08-02 10:48 UTC, dimakuv requested changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 2 of 7 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Documentation/manpages/gsc.rst, line 264 at r2](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5QY2GB5LI0M6W9mLY:-Mg5T59X9C7LaxRe86H3:b-i8i9kj) ([raw file](https://github.com/oscarlab/graphene/blob/af411f0a471d0b62ad054bbcbb3d4a4e5ed8fbf2/Documentation/manpages/gsc.rst#L264)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

We have two more files (not directories) excluded. These are .dockerenv and .dockerinit. Should we specify these two as well in the document?
</blockquote></details>

Yes, please specify.
___
*[Documentation/manpages/gsc.rst, line 321 at r2](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5S5iG2sHtkUaDZVLN:-Mg5TC-hCu0QP9RT5MNI:b-5e53qa) ([raw file](https://github.com/oscarlab/graphene/blob/af411f0a471d0b62ad054bbcbb3d4a4e5ed8fbf2/Documentation/manpages/gsc.rst#L321)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Currently we have default values as 

SGXDriver:
    Repository: ""
    Branch:     ""

Assuming intel-next kernel on the target system. Do I need to update the manpage as well?
</blockquote></details>

Yes, please update this manpage. Sorry, this was my blooper: I forgot to update it when I changed the defaults.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5OiHoDuPoguuyRtyl:-Mg5TSbi8vAIijqTnU6t:bw0v4gk) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L44)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

I could not find argv_serializer under meson_build_output directory.  Also, we don't have any meson.build file for graphene/Tools directory.  Hence, keeping the old format.
</blockquote></details>

Yes, you are right, we still didn't "Mesonify" the Tools directory (which currently contains only this one utility `argv_serializer`). Keeping the old format for this special case is fine.


<!-- Sent from Reviewable.io -->

2021-08-02 11:17 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 1 of 7 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 264 at r2](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5QY2GB5LI0M6W9mLY:-Mg5_DG-CxkzAw6d_3MH:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/af411f0a471d0b62ad054bbcbb3d4a4e5ed8fbf2/Documentation/manpages/gsc.rst#L264)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please specify.
</blockquote></details>

done, thanks.
___
*[Documentation/manpages/gsc.rst, line 321 at r2](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5S5iG2sHtkUaDZVLN:-Mg5_FLd3WJamdXd8DU2:b-dtkdrq) ([raw file](https://github.com/oscarlab/graphene/blob/af411f0a471d0b62ad054bbcbb3d4a4e5ed8fbf2/Documentation/manpages/gsc.rst#L321)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, please update this manpage. Sorry, this was my blooper: I forgot to update it when I changed the defaults.
</blockquote></details>

Done, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5OiHoDuPoguuyRtyl:-Mg5_H4oERlGNos7rMf4:b-54avio) ([raw file](https://github.com/oscarlab/graphene/blob/3dffb83b0cc981319ef9d8f3d1e8868950ecb8aa/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L44)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, you are right, we still didn't "Mesonify" the Tools directory (which currently contains only this one utility `argv_serializer`). Keeping the old format for this special case is fine.
</blockquote></details>

Ok, thanks.


<!-- Sent from Reviewable.io -->

2021-08-02 12:26 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

___
*[Documentation/manpages/gsc.rst, line 325 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5o-QnBJ3OGJXj7rzr:-Mg5o-QnBJ3OGJXj7rzs:b-hqd8k) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Documentation/manpages/gsc.rst#L325)):*
> ```reStructuredText
> 
>    Source repository of the Intel SGX driver. Default value: ""
>    (Considering DCAP in-kernel driver)
> ```

I don't like this `Considering`. Please just remove this word.
___
*[Documentation/manpages/gsc.rst, line 330 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5o2GJDYE28P0dsdAE:-Mg5o2GJDYE28P0dsdAF:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Documentation/manpages/gsc.rst#L330)):*
> ```reStructuredText
> 
>    Use this branch of the repository. Default value: ""
>    (Considering DCAP in-kernel driver)
> ```

ditto
___
*[Documentation/manpages/gsc.rst, line 389 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5mP9p9WmiyGveR-w5:-Mg5mP9p9WmiyGveR-w6:b-uc3jc1) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Documentation/manpages/gsc.rst#L389)):*
> ```reStructuredText
> The :file:`test` folder in :file:`Tools/gsc` describes how to graphenize Docker
> images and test them with sample inputs. The samples include Ubuntu-based Docker
> images of Bash, Python, Node.js, Numpy, Pytorch, and few more.
> ```

`and a few more` (forgot `a`)
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5mvpSDmMQkojPJhjr:-Mg5mvpSDmMQkojPJhjs:bq1os8j) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L35)):*
> ```
> RUN mkdir -p /graphene/Tools \
>     && mkdir -p /graphene/meson_build_output
> COPY --from=graphene /graphene/Tools/argv_serializer /graphene/Tools
> ```

Can you add a TODO comment here: `# TODO: remove this copy after argv_serializer becomes a part of Meson build`
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5ohnr4F5dORDv0MXK:-Mg5ohnr4F5dORDv0MXL:b-3lpsvk) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L54)):*
> ```
> # Include meson build output directory in $PATH and $PYTHONPATH
> ENV PATH = "${PATH}:/graphene/meson_build_output/bin"
> ENV PYTHONPATH = "${PYTHONPATH}:/graphene/meson_build_output/lib/python3.6/site-packages/"
> ```

I don't like hard-coding `python3.6` (the exact version) here... Is there anything we could do? Does Docker support something like "fetch Python version in a variable and use this variable here"?
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5nMIr7JGybVT8IqMT:-Mg5nMIr7JGybVT8IqMU:bc2wyck) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template#L40)):*
> ```
>     && make -s -j WERROR=1 SGX=1 {% if debug %} DEBUG=1 {% endif %} \
>     && make -s -j WERROR=1 {% if debug %} DEBUG=1 {% endif %} \
>     && meson build --prefix="/graphene/meson_build_output" --buildtype=release -Ddirect=enabled -Dsgx=enabled \
> ```

Here you always build in `release` buildtype. But you should actually choose between `debug` and `release` based on `if debug`. So you need something like this:
```
&& meson build --prefix="/graphene/meson_build_output"  -Ddirect=enabled -Dsgx=enabled \
    --buildtype={% if debug %}debug{% else %}release{% endif %} \
```


<!-- Sent from Reviewable.io -->

2021-08-05 06:00 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5ohnr4F5dORDv0MXK:-MgJs_zC7li0h2hsFRK8:b-ovgggy) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L54)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like hard-coding `python3.6` (the exact version) here... Is there anything we could do? Does Docker support something like "fetch Python version in a variable and use this variable here"?
</blockquote></details>

Correct. Looks like its complicated to have docker do this. Worst case, we should be able to do it as part of one of the scripts (perhaps finalize manifest).


<!-- Sent from Reviewable.io -->

2021-08-05 10:46 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 54 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5ohnr4F5dORDv0MXK:-MgKngQ3B2SJ6kzC7kSd:bsx71q1) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L54)):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Correct. Looks like its complicated to have docker do this. Worst case, we should be able to do it as part of one of the scripts (perhaps finalize manifest).
</blockquote></details>

Currently docker has this limitation that "we cannot get python version info as part of RUN command, store it in a variable and later assign it to ENV instruction (source:  https://forums.docker.com/t/how-do-i-send-runs-output-to-env-in-dockerfile/16106/3)". 

Also, using inline shell script too not supported for ENV (as shown below) 
 ENV PYTHONPATH = ${PYTHONPATH}:{$(echo python --version)}    //dummy data

In addition to these, if we set the PYTHONPATH environment variable as part of finalize_manifest.py, we can't see PYTHONPATH value set for the unsigned image (post line https://github.com/oscarlab/graphene/blob/master/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L88). Because whatever is executed as part of RUN, will not be visible after RUN command. 

These are the current limitations , we are trying other options too. Thanks.


<!-- Sent from Reviewable.io -->

2021-08-05 11:29 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 4 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Documentation/manpages/gsc.rst, line 325 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5o-QnBJ3OGJXj7rzr:-MgL3gyL5uRUUEIfhJ-X:b-lhs69o) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Documentation/manpages/gsc.rst#L325)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this `Considering`. Please just remove this word.
</blockquote></details>

done, thanks
___
*[Documentation/manpages/gsc.rst, line 330 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5o2GJDYE28P0dsdAE:-MgL3fZF7mFSqVT0y55c:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Documentation/manpages/gsc.rst#L330)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done, thanks.
___
*[Documentation/manpages/gsc.rst, line 389 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5mP9p9WmiyGveR-w5:-MgL3eKwD6J3YfKH4axm:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Documentation/manpages/gsc.rst#L389)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`and a few more` (forgot `a`)
</blockquote></details>

done, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5mvpSDmMQkojPJhjr:-MgL3bkUDcIAqh_CUFYL:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a TODO comment here: `# TODO: remove this copy after argv_serializer becomes a part of Meson build`
</blockquote></details>

done, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, line 40 at r3](https://reviewable.io/reviews/oscarlab/graphene/2594#-Mg5nMIr7JGybVT8IqMT:-MgL3Yx6DogU2i3KZqid:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/0886e26b9a7f59c33d63bb5429d8179f7cbb794b/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here you always build in `release` buildtype. But you should actually choose between `debug` and `release` based on `if debug`. So you need something like this:
```
&& meson build --prefix="/graphene/meson_build_output"  -Ddirect=enabled -Dsgx=enabled \
    --buildtype={% if debug %}debug{% else %}release{% endif %} \
```
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-08-06 08:01 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

___
*[Tools/gsc/templates/apploader.template, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgPTJfL8nN8S7_u4RBV:-MgPTJfL8nN8S7_u4RBW:br4o7qk) ([raw file](https://github.com/oscarlab/graphene/blob/3b56611f4abfc442c50549fb20fad3df33833a41/Tools/gsc/templates/apploader.template#L3)):*
> ```
> #!/usr/bin/env bash
> 
> set -ex
> ```

Please add an empty line after this (for readability)
___
*[Tools/gsc/templates/apploader.template, line 4 at r4](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgPTMPT2SCfK5AmSt0_:-MgPTMPT2SCfK5AmSt0a:bipofcs) ([raw file](https://github.com/oscarlab/graphene/blob/3b56611f4abfc442c50549fb20fad3df33833a41/Tools/gsc/templates/apploader.template#L4)):*
> ```
> 
> set -ex
> # Include meson build output directory in $PYTHONPATH
> ```

PYTHONPATH is needed for `graphene-sgx-get-token`, right? Could you append it to your comment? Like this:
```
# Include meson build output directory in $PYTHONPATH, needed by graphene-sgx-get-token
```


<!-- Sent from Reviewable.io -->

2021-08-06 08:13 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 6 of 7 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[Tools/gsc/templates/apploader.template, line 3 at r4](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgPTJfL8nN8S7_u4RBV:-MgPWXIyEXV-v7Nhis0s:b-dtkdrq) ([raw file](https://github.com/oscarlab/graphene/blob/3b56611f4abfc442c50549fb20fad3df33833a41/Tools/gsc/templates/apploader.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this (for readability)
</blockquote></details>

Done, thanks.
___
*[Tools/gsc/templates/apploader.template, line 4 at r4](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgPTMPT2SCfK5AmSt0_:-MgPWHSuAVCiVu5zgcMF:b-z749ih) ([raw file](https://github.com/oscarlab/graphene/blob/3b56611f4abfc442c50549fb20fad3df33833a41/Tools/gsc/templates/apploader.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

PYTHONPATH is needed for `graphene-sgx-get-token`, right? Could you append it to your comment? Like this:
```
# Include meson build output directory in $PYTHONPATH, needed by graphene-sgx-get-token
```
</blockquote></details>

Yes, PYTHONPATH is needed for graphene-sgx-get-token. Modified the comment, thanks.


<!-- Sent from Reviewable.io -->

2021-08-06 08:43 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-08-07 21:59 UTC, mkow requested changes
> Reviewed 1 of 6 files at r1, 1 of 6 files at r2, 4 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

___
*[Documentation/manpages/gsc.rst, line 325 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXZTPY86mNl-oWw2rf:-MgXZTPY86mNl-oWw2rg:bukyc3b) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L325)):*
> ```reStructuredText
> 
>    Source repository of the Intel SGX driver. Default value: ""
>    (DCAP in-kernel driver)
> ```

DCAP _or_ in-kernel? These are two different drivers.
___
*[Documentation/manpages/gsc.rst, line 330 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgX_dZm9d6ApYN2kYUJ:-MgX_dZm9d6ApYN2kYUK:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L330)):*
> ```reStructuredText
> 
>    Use this branch of the repository. Default value: ""
>    (DCAP in-kernel driver)
> ```

ditto
___
*[Tools/gsc/templates/apploader.template, line 5 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXa3hxEl3Fq8uc3YNQ:-MgXa3hxEl3Fq8uc3YNR:b-wxp356) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/apploader.template#L5)):*
> ```
> set -ex
> 
> # Include meson build output directory in $PYTHONPATH, needed by graphene-sgx-get-token
> ```

`meson` -> `Meson`
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 55 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbDWTAxVYc87tOwDJ:-MgXbDWTAxVYc87tOwDK:b-2cpbjy) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L55)):*
> ```
> 
> # Include meson build output directory in $PATH
> ENV PATH = "${PATH}:/graphene/meson_build_output/bin"
> ```

Umm, isn't this setting `PATH` to `= "${PATH}:/graphene/meson_build_output/bin"`? Please use the officially recommended syntax for `ENV` (see https://docs.docker.com/engine/reference/builder/#env).
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template, line 12 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbhkeCuoY793cZ-lZ:-MgXbhkeCuoY793cZ-l_:bm0wn7g) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template#L12)):*
> ```
> COPY gsc-signer-key.pem /gsc-signer-key.pem
> 
> RUN export PYTHONPATH="${PYTHONPATH}:$(find /graphene/meson_build_output/lib -type d  -path '*/site-packages')" \
> ```

double space
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template, line 23 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbc2e69fbgM6fkCE6:-MgXbc2e69fbgM6fkCE7:b-ositwi) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template#L23)):*
> ```
> COPY --from=unsigned_image /*.sig /
> COPY --from=unsigned_image /*.sgx /
> ```

please remove this empty line


<!-- Sent from Reviewable.io -->

2021-08-09 05:28 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 3 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Documentation/manpages/gsc.rst, line 325 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXZTPY86mNl-oWw2rf:-MgdMZuA-wOHcELud3Su:b-jy17fi) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L325)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

DCAP _or_ in-kernel? These are two different drivers.
</blockquote></details>

Based on my understannding , In -kernel driver internally uses DCAP only. We have the same naming convention in config.yaml.template as well.  Please suggest if I have to make the change at config.yaml.template as well ? Thanks.
___
*[Documentation/manpages/gsc.rst, line 330 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgX_dZm9d6ApYN2kYUJ:-MgdNBKL3lEXyRAFXmKM:b-dtkdrq) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L330)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done, thanks.
___
*[Tools/gsc/templates/apploader.template, line 5 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXa3hxEl3Fq8uc3YNQ:-MgdNNRQ378BSUPMbR-E:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/apploader.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`meson` -> `Meson`
</blockquote></details>

done, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 55 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbDWTAxVYc87tOwDJ:-MgdNP991iH-_lsIdcAp:b-29vizu) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Umm, isn't this setting `PATH` to `= "${PATH}:/graphene/meson_build_output/bin"`? Please use the officially recommended syntax for `ENV` (see https://docs.docker.com/engine/reference/builder/#env).
</blockquote></details>

Done, thanks. 
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template, line 12 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbhkeCuoY793cZ-lZ:-MgdNR4v52TjyyV6SMDB:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space
</blockquote></details>

done, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template, line 23 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbc2e69fbgM6fkCE6:-MgdNSDZ9jozScDZGS2b:b-lhs69o) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.sign.template#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please remove this empty line
</blockquote></details>

done, thanks


<!-- Sent from Reviewable.io -->

2021-08-09 07:28 UTC, dimakuv approved these changes
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Documentation/manpages/gsc.rst, line 325 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXZTPY86mNl-oWw2rf:-MgdnAw86j3U21EGYmZq:bs2kkkf) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L325)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Based on my understannding , In -kernel driver internally uses DCAP only. We have the same naming convention in config.yaml.template as well.  Please suggest if I have to make the change at config.yaml.template as well ? Thanks.
</blockquote></details>

LGTM. You are both right, but Michal is correct: we (and many other people) tend to call the three different drivers as: "legacy" (aka "non-DCAP"), "DCAP" (aka "modern out-of-linux-tree"), "in-kernel" (aka "in-linux-tree").

So to avoid confusion, I like the current `In-kernel driver` text.


<!-- Sent from Reviewable.io -->

2021-08-09 07:39 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[Documentation/manpages/gsc.rst, line 325 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXZTPY86mNl-oWw2rf:-MgdqWwEEx4CgcoArXM1:b-567si8) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L325)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

LGTM. You are both right, but Michal is correct: we (and many other people) tend to call the three different drivers as: "legacy" (aka "non-DCAP"), "DCAP" (aka "modern out-of-linux-tree"), "in-kernel" (aka "in-linux-tree").

So to avoid confusion, I like the current `In-kernel driver` text.
</blockquote></details>

ok, Thanks.


<!-- Sent from Reviewable.io -->

2021-08-09 17:47 UTC, mkow requested changes
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

___
*[Documentation/manpages/gsc.rst, line 325 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXZTPY86mNl-oWw2rf:-MgfzoyW7aCmZDBiBxf-:bad75k3) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L325)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

ok, Thanks.
</blockquote></details>

should be rather "in-kernel" (lowercase, as this isn't a new sentence).
___
*[Documentation/manpages/gsc.rst, line 330 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgX_dZm9d6ApYN2kYUJ:-Mgfzx4p5ZIPXQfwLsEq:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L330)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Done, thanks.
</blockquote></details>

ditto
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 55 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbDWTAxVYc87tOwDJ:-Mgg-83i9OBcJHRXWe-b:b-frrg7t) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L55)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Done, thanks. 
</blockquote></details>

But why have you removed doublequotes? What if `$PATH` contains spaces?


<!-- Sent from Reviewable.io -->

2021-08-10 03:31 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @veenasai2)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 55 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbDWTAxVYc87tOwDJ:-Mgi5nZk0ArT5Kb5-A2r:b-aks2je) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But why have you removed doublequotes? What if `$PATH` contains spaces?
</blockquote></details>

I was following the syntax provided at official docker site (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#env).  Here, I found       ENV PATH=/usr/local/nginx/bin:$PATH     . 


<!-- Sent from Reviewable.io -->

2021-08-10 11:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 55 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbDWTAxVYc87tOwDJ:-MgjlYYIAA84PSWI5Yak:btbunpv) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L55)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

I was following the syntax provided at official docker site (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#env).  Here, I found       ENV PATH=/usr/local/nginx/bin:$PATH     . 
</blockquote></details>

Looks like a bug in theirs docs, in other places they use doublequotes (see e.g. https://docs.docker.com/engine/reference/builder/#env).


<!-- Sent from Reviewable.io -->

2021-08-10 16:53 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: 5 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[Documentation/manpages/gsc.rst, line 325 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXZTPY86mNl-oWw2rf:-Mgkhinu604D9J9LP8d9:b-dtkdrq) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L325)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be rather "in-kernel" (lowercase, as this isn't a new sentence).
</blockquote></details>

Done, thanks.
___
*[Documentation/manpages/gsc.rst, line 330 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgX_dZm9d6ApYN2kYUJ:-Mgkhkxx8DzUTyakc5gQ:b-r18wie) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Documentation/manpages/gsc.rst#L330)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done, thanks.
___
*[Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template, line 55 at r5](https://reviewable.io/reviews/oscarlab/graphene/2594#-MgXbDWTAxVYc87tOwDJ:-MgkhnacBz9T29eVxa3S:b-id1ttn) ([raw file](https://github.com/oscarlab/graphene/blob/8049f25ff4fce0f97787506c4e13b451c38f5d13/Tools/gsc/templates/Dockerfile.ubuntu18.04.build.template#L55)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Looks like a bug in theirs docs, in other places they use doublequotes (see e.g. https://docs.docker.com/engine/reference/builder/#env).
</blockquote></details>

ok, I put the double quotes. Thanks for the clarification. 


<!-- Sent from Reviewable.io -->

2021-08-10 19:59 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-11 07:15 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-11 08:33 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-08-11 09:48 UTC, dimakuv commented
Jenkins, test this please

2021-08-11 12:13 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2594)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-11 12:15 UTC, merged