[SGX/SIGN] Refactor the sgx_sign script
oscarlab/graphene pull request #2596
Opened 2021-07-29 17:19 UTC by bigdata-memory

## Description of the changes 
As @dimakuv  suggested, the sign script needs to get refactored.

This patch abstracts several conceptual entities from original scripts.
Those entities have been organized into the following scripts as internal modules.
The sgx_sign script becomes a wrapper to control the main workflow.
_sgx_depend.py
_sgx_manifest.py
_sgx_measure.py
_sgx_memory.py
_sgx_sign.py
_sgx_utility.py

## How to test this PR? 
Use `graphene-sgx-sign` to test w/ and w/o `--depend` option.

2021-07-30 08:51 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: all files reviewed, 53 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bigdata-memory)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_e82Ccxz0xJpuKHd:-Mfq_e82Ccxz0xJpuKHe:b-p915wd) (no related file):*
This looks great! The first step to refactor our SGX-signing messy code. Thanks for this.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_mK1DfvMaiilYpuz:-Mfq_mK1DfvMaiilYpv-:b71cwk2) (no related file):*
I don't like the naming convention you chose (`_` prefix). I suggest to definitely remove the prefix and instead use the names like this:
```
_sgx_depend.py     -> sgx_gen_make_deps.py
_sgx_manifest.py   -> sgx_finalize_manifest.py
_sgx_measure.py    -> sgx_measure_enclave.py
_sgx_memory.py     -> sgx_get_enclave_mem_areas.py
_sgx_sign.py       -> sgx_gen_sigstruct.py
_sgx_utility.py    -> sgx_utils.py
```

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfqay38BcXH8QG01wHs:-Mfqay38BcXH8QG01wHt:bfvbnik) (no related file):*
> [SGX/SIGN] Refactor the sgx_sign script

I propose to change to `[Python] Refactor sgx_sign.py script`

---
___
*[python/graphenelibos/_sgx_depend.py, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqJe3Y6FwtALk0kT20:-MfqJe3Z20646VDnSlCm:b-de8gyl) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_depend.py#L8)):*
> ```Python
> 
> from pathlib import Path
> from . import _sgx_utility
> ```

Looks like both these `from ...` lines are not needed, please remove
___
*[python/graphenelibos/_sgx_depend.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqJlO_C1OUzWomYybZ:-MfqJlO_C1OUzWomYyb_:b-w1anm9) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_depend.py#L9)):*
> ```Python
> from pathlib import Path
> from . import _sgx_utility
> ```

Could you add a top-level comment here like this:
```
'''
Generator of Makefile dependency files (`.d`): the final Graphene manifest.sgx file depends on
all trusted-files listed in the manifest, the libpal.so library, and the signer key.

This is Makefile-specific and will be removed after the complete transition to Meson.
'''
```

(Please also rewrap the above text to 100 chars)
___
*[python/graphenelibos/_sgx_manifest.py, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqPqpqEpnkcOpv9hf_:-MfqPqpqEpnkcOpv9hfa:b-clp23l) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L14)):*
> ```Python
> from . import _offsets as offs # pylint: disable=import-error,no-name-in-module
> from . import _sgx_utility as util
> ```

Could you add a top-level comment here like this:
```
'''
Loading the manifest file, modifying it, and extracting options from it.
'''
```
___
*[python/graphenelibos/_sgx_manifest.py, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqPcdu7pSf2BcYmd32:-MfqPcdu7pSf2BcYmd33:b-cumm98) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L15)):*
> ```Python
> from . import _sgx_utility as util
> 
> # Default / Architectural Options
> ```

Can you remove this comment? The lines below are self-describing.
___
*[python/graphenelibos/_sgx_manifest.py, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqXkfMEt71xdobUDBf:-MfqXkfMEt71xdobUDBg:b4voo87) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L34)):*
> ```Python
>             self.manifest = toml.load(self.manifest_file)
>         except toml.TomlDecodeError as exc:
>             raise ManifestError(f'Parsing {self.manifest_file} as TOML file failed: {exc}')
> ```

Shouldn't it be `util.ManifestError`?
___
*[python/graphenelibos/_sgx_manifest.py, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqLtoA6ZwX3oPsMZog:-MfqLtoA6ZwX3oPsMZoh:b-kz80re) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L59)):*
> ```Python
>         loader.setdefault('preload', '')
> ```

You have two empty lines. Please remove one.
___
*[python/graphenelibos/_sgx_manifest.py, line 86 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqMvjA4nOJBW9ah-q8:-MfqMvjA4nOJBW9ah-q9:bo4m1hq) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L86)):*
> ```Python
>         return targets
> 
>     def get_manifest(self):
> ```

This function is not used anywhere, please remove.
___
*[python/graphenelibos/_sgx_manifest.py, line 90 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqMpUd1tgb8emJuwfy:-MfqMpUd1tgb8emJuwfz:b7r8wbp) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L90)):*
> ```Python
> 
>     def get_trusted_fileset(self):
>         return self.trusted_fileset
> ```

This function (and this corresponding `self.trusted_fileset`) are not used anywhere, please remove
___
*[python/graphenelibos/_sgx_manifest.py, line 148 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqNOgL0MP5s7ewLnJR:-MfqNOgMBiK0gNzh4BTz:b-yfraug) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L148)):*
> ```Python
>     def get_sgx_attr(self):
>         if self.attr is not None:
>             return self.attr
> ```

Please add an empty line after this
___
*[python/graphenelibos/_sgx_manifest.py, line 177 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqOLAA0auDKk55i5IX:-MfqOLAA0auDKk55i5IY:b-dngqp6) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L177)):*
> ```Python
>         return self.attr
> 
>     def get_client_spid(self):
> ```

Can we rename to `get_sgx_ra_attr`? This will be more readable ("Get SGX Remote Attestation attributes")
___
*[python/graphenelibos/_sgx_manifest.py, line 190 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqOc8n-B9x7qxjflH1:-MfqOc8n-B9x7qxjflH2:bwcre23) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L190)):*
> ```Python
>         return spid, linkable
> 
>     def get_enclave_info(self, attr):
> ```

Could we rename to more specific `get_enclave_addresses`?
___
*[python/graphenelibos/_sgx_manifest.py, line 200 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqP4Pt8Xn0Sp4kDqtw:-MfqP4Pt8Xn0Sp4kDqtx:bpwxvt) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L200)):*
> ```Python
>         return enclave_base, enclave_heap_min
> 
>     def attach_trusted_file_hashs(self):
> ```

Could we rename to `append_trusted_files_and_hashes`?
___
*[python/graphenelibos/_sgx_manifest.py, line 202 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqPAQ99M6G0CMKFVNg:-MfqPAQ99M6G0CMKFVNh:b1yiggf) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L202)):*
> ```Python
>     def attach_trusted_file_hashs(self):
>         manifest_sgx = self.manifest['sgx']
>         # Get trusted hashes and measurements
> ```

Please remove this comment. The code (and the function name) are self-sufficient.
___
*[python/graphenelibos/_sgx_measure. [...]

2021-07-30 13:26 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: all files reviewed, 54 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bigdata-memory)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfr_tb52iMBKKdHEuVl:-Mfr_tb52iMBKKdHEuVm:b-ovg80u) (no related file):*
This is something @woju should review, blocking until he does.

---


<!-- Sent from Reviewable.io -->

2021-07-30 14:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: all files reviewed, 54 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @bigdata-memory and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfr_tb52iMBKKdHEuVl:-MfribAj6uCp9XJLRFWI:b-9xcgsv) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This is something @woju should review, blocking until he does.
</blockquote></details>

Indeed. By the way, note that I compared the code in this PR with the old (current) code manually. There are no changes other than the required ones for splitting into separate files. I would prefer to not stash new changes in this PR (like, the code for measuring the enclave is terrible, and this PR doesn't change that fact). But this is a good first step to later apply specific refactorings on different parts of the code.

---


<!-- Sent from Reviewable.io -->

2021-07-30 22:16 UTC, bigdata-memory commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_e82Ccxz0xJpuKHd:-MftTwmJ-Uh6qJsyNa9a:bnfzi1u) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks great! The first step to refactor our SGX-signing messy code. Thanks for this.
</blockquote></details>

Thank you for the review, I will follow up to get it fixed, thanks.

---


<!-- Sent from Reviewable.io -->

2021-08-02 18:02 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: 0 of 8 files reviewed, 54 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_mK1DfvMaiilYpuz:-Mg6rImlDJgF0nf1yzs1:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like the naming convention you chose (`_` prefix). I suggest to definitely remove the prefix and instead use the names like this:
```
_sgx_depend.py     -> sgx_gen_make_deps.py
_sgx_manifest.py   -> sgx_finalize_manifest.py
_sgx_measure.py    -> sgx_measure_enclave.py
_sgx_memory.py     -> sgx_get_enclave_mem_areas.py
_sgx_sign.py       -> sgx_gen_sigstruct.py
_sgx_utility.py    -> sgx_utils.py
```
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfqay38BcXH8QG01wHs:-Mg70v248w7nDBtEsE5A:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> [SGX/SIGN] Refactor the sgx_sign script

I propose to change to `[Python] Refactor sgx_sign.py script`
</blockquote></details>

Done.

---
___
*[python/graphenelibos/meson.build, line 36 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqYvQf4VOmt8NsCsuJ:-Mg6x5P17FKcbLO8_pYn:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/meson.build#L36)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqZ1Cc00FDzDkM537s:-Mg6ueMgD7k_LiJKKp_u:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/sgx_sign.py#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you can simplify:
```
from . import (
    _CONFIG_PKGLIBDIR,
    _sgx_manifest as manifest,
    _sgx_depend as depend,
    ...
)
```
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqZiWf6Mb6skOg5mZ9:-Mg6lJCFD3mjOEvbrllm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/sgx_sign.py#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you replace it with better names:
```
input_manifest = manifest.Manifest(args['manifest'])
output_manifest = args['output']
```

And then use `output_manifest` everywhere below instead of `args['output']`
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 72 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqZx_j7TW7-genqMim:-Mg6m8SyEz_ocE9KB2SM:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/sgx_sign.py#L72)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indentation is weird. I would recommend to just put everything in one line:
```
        dg = depend.DependGenerator(manifest_, args['libpal'], args['key'], sigfile)
        dg.generate()
        ...
```
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 74 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_Obc9fbaHAs-3n_7:-Mg6mKMjDfg5xwDsPi-S:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/sgx_sign.py#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks weird. I recommend to split into two lines:
```
depend_generator.write(args['output'])
return 0
```
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_8Qv3wXoba8obZuu:-Mg6mTNXCUKPIDxlZURX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/sgx_sign.py#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indentation is weird. Just put everything in one line (we have the limit of 100 chars, so should be enough).
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 86 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_U7O6dAnZ434SVR-:-Mg6mYxaCRdGG6M3ocqa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/sgx_sign.py#L86)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks weird. I recommend to split into two lines:
```
sgx_sign.write(sigfile)
return 0
```
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_depend.py, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqJe3Y6FwtALk0kT20:-Mg6nBcXBInuy7YlE7Ye:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_depend.py#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like both these `from ...` lines are not needed, please remove
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_depend.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqJlO_C1OUzWomYybZ:-Mg6n2nC0PXZnZUf_xen:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_depend.py#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a top-level comment here like this:
```
'''
Generator of Makefile dependency files (`.d`): the final Graphene manifest.sgx file depends on
all trusted-files listed in the manifest, the libpal.so library, and the signer key.

This is Makefile-specific and will be removed after the complete transition to Meson.
'''
```

(Please also rewrap the above text to 100 chars)
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_manifest.py, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqPqpqEpnkcOpv9hf_:-Mg6RWRZBKVJJyJjAjMC:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add a top-level comment here like this:
```
'''
Loading the manifest file, modifying it, and extracting options from it.
'''
```
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_manifest.py, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqPcdu7pSf2BcYmd32:-Mg6O58cBXzc6LWJ59wW:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you remove this comment? The lines below are self-describing.
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_manifest.py, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-MfqXkfMEt71xdobUDBf:-Mg6Nx6nBtmgOLmSZWWw:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summar [...]

2021-08-03 07:59 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory and @woju)

___
*[python/graphenelibos/meson.build, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9ugEVBTrhm1geIaQ6:-Mg9ugEVBTrhm1geIaQ7:b-g0cont) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/meson.build#L38)):*
> ```Meson
>         'sgx_measure_enclave.py',
>         'sgx_sign.py',
>         'sgx_utils.py',       
> ```

Please remove the trailing whitespace
___
*[python/graphenelibos/sgx_sign.py, line 74 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9yKJh8GWwcdfl5lsX:-Mg9yKJh8GWwcdfl5lsY:bm54p5t) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L74)):*
> ```Python
>         dg = depend.DependGenerator(input_manifest, args['libpal'], args['key'], sigfile)
>         dg.generate()
>         dg.write(output_manifest)
> ```

BTW, this looks a bit weird. We don't really write to a final output manifest, we write to a `.d` file -- but because we re-use the same `args['output']`, it looks weird.

But this `depend` logic will go away soon, when we completely migrate to Meson. So I wouldn't bother with making it nicer.
___
*[python/graphenelibos/sgx_sign.py, line 78 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA0Bs92oiWSiwa7XXp:-MgA0BsA8l-B1UMBjEC7:b5dgosi) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L78)):*
> ```Python
> 
>     sgx_measurement = measure.EnclaveMeasurement(input_manifest, args['libpal'])
>     input_manifest.get_sgx_ra_attr()
> ```

Can you add a comment here that this is currently only to print information (it doesn't really "do" anything):
```
input_manifest.get_sgx_ra_attr()   # currently only to print info on SGX Remote Attestation
```
___
*[python/graphenelibos/sgx_sign.py, line 79 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA-8tc76vnCQlXhP-h:-MgA-8td68VqahUWUtqk:b-lm8twx) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L79)):*
> ```Python
>     sgx_measurement = measure.EnclaveMeasurement(input_manifest, args['libpal'])
>     input_manifest.get_sgx_ra_attr()
>     input_manifest.gen_manifest_sgx_file()
> ```

See my other comment (to rename this function to `write` for uniformity). Then this line will become:
```
input_manifest.write(output_manifest)
```

This will make this code clearer: it will be obvious for the reader that we create both an output manifest file (`.manifest.sgx`) and the sigstruct file (`.sig`).
___
*[python/graphenelibos/sgx_sign.py, line 82 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA0NC1D5lmv9oDV_1h:-MgA0NC1D5lmv9oDV_1i:b-c48pdt) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L82)):*
> ```Python
>     sgx_measurement.measure_enclave()
> 
>     sgx_sign = sign.EnclaveSign(input_manifest.get_sgx_attr(),
> ```

See my other comment. I suggest to rename `EnclaveSign` to `EnclaveSigstruct`. Therefore, please rename also the variable: `sgx_sign` -> `sgx_sigstruct`.
___
*[python/graphenelibos/_sgx_manifest.py, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9uqjR2QVPucrIXYhG:-Mg9uqjR2QVPucrIXYhH:b-q1hpzh) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L12)):*
> ```Python
> from pathlib import Path
> from . import _CONFIG_PKGLIBDIR
> from . import _offsets as offs # pylint: disable=import-error,no-name-in-module
> ```

You should keep this pylint comment, otherwise our Jenkins CI will complain and fail
___
*[python/graphenelibos/_sgx_measure.py, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9wGQi2sQbz-MlAjjt:-Mg9wGQi2sQbz-MlAjju:b-46dm34) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_measure.py#L10)):*
> ```Python
> import hashlib
> from pathlib import Path
> from . import _offsets as offs # pylint: disable=import-error,no-name-in-module
> ```

ditto (you need this comment)
___
*[python/graphenelibos/_sgx_memory.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9vkBmDCiwWuMHblMb:-Mg9vkBmDCiwWuMHblMc:brs5h3x) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_memory.py#L9)):*
> ```Python
> import struct
> from pathlib import Path
> from . import _offsets as offs # pylint: disable=import-error,no-name-in-module
> ```

Ditto, you need this pylint comment
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9zicYBVhbBic_7DJ_:-Mg9zicYBVhbBic_7DJa:bnw44n) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_finalize_manifest.py#L204)):*
> ```Python
>             manifest_sgx['trusted_checksum'][key] = hash_
> 
>     def gen_manifest_sgx_file(self):
> ```

I understand why you chose to implement this function like this. But for uniformity with other scripts, can we can this function `write` and add an explicit `output_manifest` argument to it? Like this:
```
    def write(self, output_manifest):
        self.append_trusted_files_and_hashes()
        with open(output_manifest, 'w', encoding='UTF-8') as file:
            ...
```
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA-vsi3kkGif8Mg9Tw:-MgA-vsjDZ6rITfdk9o2:b-l8wmd2) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_gen_sigstruct.py#L15)):*
> ```Python
> #       generated). Need to update to the two-step signing process.
> 
> class EnclaveSign:
> ```

Just noticed that this name is now misleading (because the file is named differently now, and because we actually work on SIGSTRUCT here). I suggest to rename to `EnclaveSigstruct`.
___
*[python/graphenelibos/sgx_get_enclave_mem_areas.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9vtyJB1xSlAMNKOT2:-Mg9vtyJB1xSlAMNKOT3:b-norgh4) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_get_enclave_mem_areas.py#L15)):*
> ```Python
> 
> # Collect memory areas that constitute the enclave. Used to generate the final SGX measurement
> # MRENCLAVE) in `sgx_get_enclave_mem_areas.py`.
> ```

`MRENCLAVE)` -> `(MRENCLAVE)` (you forgot the opening `(`)
___
*[python/graphenelibos/sgx_measure_enclave.py, line 156 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9x2pk-S30HamUW2pT:-Mg9x2pk-S30HamUW2pU:b95qgd0) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_measure_enclave.py#L156)):*
> ```Python
> 
>         mrenclave_digest = self.mrenclave.digest()
>         print('Memory:')
> ```

This print should be in the very beginning of this function


<!-- Sent from Reviewable.io -->

2021-08-10 04:37 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: 2 of 8 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[python/graphenelibos/meson.build, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9ugEVBTrhm1geIaQ6:-MgiANQ3CrhuVpUTykPG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/meson.build#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the trailing whitespace
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 74 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9yKJh8GWwcdfl5lsX:-MgiIoko0nx6dHRqZ5iZ:b-ghgth2) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L74)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

BTW, this looks a bit weird. We don't really write to a final output manifest, we write to a `.d` file -- but because we re-use the same `args['output']`, it looks weird.

But this `depend` logic will go away soon, when we completely migrate to Meson. So I wouldn't bother with making it nicer.
</blockquote></details>

Agree, thanks.
___
*[python/graphenelibos/sgx_sign.py, line 78 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA0Bs92oiWSiwa7XXp:-MgiJE5AAD9Pb6TTTXMi:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment here that this is currently only to print information (it doesn't really "do" anything):
```
input_manifest.get_sgx_ra_attr()   # currently only to print info on SGX Remote Attestation
```
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 79 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA-8tc76vnCQlXhP-h:-MgiJJeC1qMRZsRulTFM:bw6ngio) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my other comment (to rename this function to `write` for uniformity). Then this line will become:
```
input_manifest.write(output_manifest)
```

This will make this code clearer: it will be obvious for the reader that we create both an output manifest file (`.manifest.sgx`) and the sigstruct file (`.sig`).
</blockquote></details>

Please see my related comment above, thanks.
___
*[python/graphenelibos/sgx_sign.py, line 82 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA0NC1D5lmv9oDV_1h:-MgiJRpwAnGsgF0772n7:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

See my other comment. I suggest to rename `EnclaveSign` to `EnclaveSigstruct`. Therefore, please rename also the variable: `sgx_sign` -> `sgx_sigstruct`.
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_manifest.py, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9uqjR2QVPucrIXYhG:-MgiC2vw5H-6KNKtXOSk:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should keep this pylint comment, otherwise our Jenkins CI will complain and fail
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_measure.py, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9wGQi2sQbz-MlAjjt:-MgiK4Xc1124fYrRL6Qb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_measure.py#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (you need this comment)
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_memory.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9vkBmDCiwWuMHblMb:-MgiK3_89bxcf6ocoY-h:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_memory.py#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ditto, you need this pylint comment
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9zicYBVhbBic_7DJ_:-MgiE-Jt8TXgSs_PZUMe:b-3yt5j3) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_finalize_manifest.py#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I understand why you chose to implement this function like this. But for uniformity with other scripts, can we can this function `write` and add an explicit `output_manifest` argument to it? Like this:
```
    def write(self, output_manifest):
        self.append_trusted_files_and_hashes()
        with open(output_manifest, 'w', encoding='UTF-8') as file:
            ...
```
</blockquote></details>

if we don't keep the info of output_manifest in this object in question, we have to provision it again in the following call site
`sgx_get_enclave_mem_areas.py:182:        manifest_data = self.manifest.get_manifest_sgx()`
that object supposes having no knowledge about it.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA-vsi3kkGif8Mg9Tw:-MgiHq9L2H5Yo3fB6fNa:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_gen_sigstruct.py#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed that this name is now misleading (because the file is named differently now, and because we actually work on SIGSTRUCT here). I suggest to rename to `EnclaveSigstruct`.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_get_enclave_mem_areas.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9vtyJB1xSlAMNKOT2:-MgiI6uG2_KaY-HljUBX:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_get_enclave_mem_areas.py#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`MRENCLAVE)` -> `(MRENCLAVE)` (you forgot the opening `(`)
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_measure_enclave.py, line 156 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9x2pk-S30HamUW2pT:-MgiIXga-85Rbkmvg6uT:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_measure_enclave.py#L156)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This print should be in the very beginning of this function
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-13 16:39 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: 2 of 8 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[python/graphenelibos/meson.build, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9ugEVBTrhm1geIaQ6:-Mh-N6OlAz3Q1Z04M-Y5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/meson.build#L38)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 78 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA0Bs92oiWSiwa7XXp:-Mh-NLUC9ht_xJQxZvDN:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L78)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 82 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA0NC1D5lmv9oDV_1h:-Mh-NOm54I8oEdR7HA5d:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_sign.py#L82)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_manifest.py, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9uqjR2QVPucrIXYhG:-Mh-N8_731Z72bcizdyb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_manifest.py#L12)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_measure.py, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9wGQi2sQbz-MlAjjt:-Mh-NGLL7qURPNln7Zqb:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_measure.py#L10)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/_sgx_memory.py, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9vkBmDCiwWuMHblMb:-Mh-NDtg6YYkJC8GGHKz:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/506d5b2580fcc79045b91a76de4085b57b536019/python/graphenelibos/_sgx_memory.py#L9)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgA-vsi3kkGif8Mg9Tw:-Mh-NCL32K6s_5tDauh1:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_gen_sigstruct.py#L15)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_get_enclave_mem_areas.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9vtyJB1xSlAMNKOT2:-Mh-NEyyD3pO4hKq6Q2o:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_get_enclave_mem_areas.py#L15)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_measure_enclave.py, line 156 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9x2pk-S30HamUW2pT:-Mh-NIsu7qInoxwDBkuf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_measure_enclave.py#L156)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-14 09:22 UTC, woju requested changes
> Reviewed 1 of 8 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: all files reviewed, 29 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_mK1DfvMaiilYpuz:-MgzTyTk2WFZvQX9V2UF:b11kze1) (no related file):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would prefer if those weren't split between different files, ~1000loc Python files are perfectly manageable. The comments written at the top of the files might be docstrings in respective classes, where appropriate.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfr_tb52iMBKKdHEuVl:-MgAwgjG780EK_OldBxE:b27cqe9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Indeed. By the way, note that I compared the code in this PR with the old (current) code manually. There are no changes other than the required ones for splitting into separate files. I would prefer to not stash new changes in this PR (like, the code for measuring the enclave is terrible, and this PR doesn't change that fact). But this is a good first step to later apply specific refactorings on different parts of the code.
</blockquote></details>

If this PR does nothing but moves functions/classes between files, then I think this PR does not help. We should first rewrite the actual code and then splitting it between files should be obivious. (If at all necessary -- the file is currently at ~800 lines, so totally manageable, even if it stands out from other python scripts).

---
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9zicYBVhbBic_7DJ_:-Mh2Xy7n5ewaJhWsgbAn:b6pooqh) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_finalize_manifest.py#L204)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

if we don't keep the info of output_manifest in this object in question, we have to provision it again in the following call site
`sgx_get_enclave_mem_areas.py:182:        manifest_data = self.manifest.get_manifest_sgx()`
that object supposes having no knowledge about it.
</blockquote></details>

No, this is wrong. You should pass manifest's path into `EnclaveMemory` just as you pass libpal.
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 33 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh1tlXt7U-gAH998YPM:-Mh1tlXyElQLBCGzteb-:b-vd6072) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L33)):*
> ```Python
>         self.attr = None
> 
>     def load(self):
> ```

This function should be part of `__init__`, there's no need to separate this.
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 39 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh1wwS-2R88o-vaPNeK:-Mh1tsTC6_04UECX-0vv:bxpucyr) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L39)):*
> ```Python
>             raise util.ManifestError(f'Parsing {self.manifest_file} as TOML file failed: {exc}')
> 
>     def set_defaults(self):
> ```

This function should be private (`def _set_defaults(self):`).
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 156 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh1xFLU7UKLSJehJXqZ:-Mh1xFLU7UKLSJehJXq_:bmjl3ca) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L156)):*
> ```Python
>         attr['day'] = today.day
> 
>         print('Attributes:')
> ```

A function called `get`-something should never print anything. Please move this `print()` block elsewhere.
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 175 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2VnHKCney-7Sv_37u:-Mh2VnHL7SHAL63r0M4i:bl8qtvc) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L175)):*
> ```Python
>             spid = manifest_sgx.get('ra_client_spid', '')
>             linkable = manifest_sgx.get('ra_client_linkable', False)
>             print('SGX remote attestation:')
> ```

Same as above: don't `print()` from a function called `get_*()`.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 8 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzTR6S2rx1i9hCxRwI:-MgzTR6T39e1h2UwrZp-:b-jkbgtr) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L8)):*
> ```Python
> 
> # Generator of Makefile dependency files (`.d`): the final Graphene manifest.sgx file depends on
> # all trusted-files listed in the manifest, the libpal.so library, and the signer key.
> ```

This should be a docstring, probably in the class itself.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 10 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzNcy0Dh68194cIjRW:-MgzNcy21JbZg97zXa7y:b4i4wxa) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L10)):*
> ```Python
> # all trusted-files listed in the manifest, the libpal.so library, and the signer key.
> 
> # This is Makefile-specific and will be removed after the complete transition to Meson.
> ```

This is incorrect, while the format is in Make syntax, ninja supports those file and meson can configure ninja use those files to infer if the target should be rebuilt when some dependency changes. What will change is, depend files will be generated alongside the targets, not as alternative invocation. Please see https://mesonbuild.com/Reference-manual.html#custom_target, `depfile` argument.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzO1ERBvR8WC0PlXIE:-MgzO1ERBvR8WC0PlXIF:b-vbvgy9) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L14)):*
> ```Python
> class DependGenerator:
> 
>     def __init__(self, manifest, libpal_file, key, sigfile_name):
> ```

libpal_file and key, while special, could be just added to the accumulator and not stored as attributes. Also, `.dependencies` attribute should be initialised in `__init__`.

So this should look something like this:

```python
def __init__(self, manifest, sigfile_name, *args):
    self.dependencies = {*args}
```

And the sigfile_name should be reordered in invocation.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 21 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzNkKH65Gu_zP07U4p:-MgzNkKI2fC-1thUutvh:blh30el) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L21)):*
> ```Python
> 
>     def generate(self):
>         self.dependencies = set()
> ```

This is attribute creation outside `__init__`, plz move this to `__init__` and ideally this should be initialised as `self.dependencies = {*initial}
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzO8_g6xqvqOLU0Oj3:-MgzO8_g6xqvqOLU0Oj4:btid14q) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L29)):*
> ` [...]

2021-08-17 01:06 UTC, bigdata-memory reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: all files reviewed, 29 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfq_mK1DfvMaiilYpuz:-MhGcAea-QXOSNeObAX7:b-v5vzlc) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I would prefer if those weren't split between different files, ~1000loc Python files are perfectly manageable. The comments written at the top of the files might be docstrings in respective classes, where appropriate.
</blockquote></details>

agree on the docstrings, thanks.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfr_tb52iMBKKdHEuVl:-MhGcqBsAUrn380PEtwO:b-97c7k3) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If this PR does nothing but moves functions/classes between files, then I think this PR does not help. We should first rewrite the actual code and then splitting it between files should be obivious. (If at all necessary -- the file is currently at ~800 lines, so totally manageable, even if it stands out from other python scripts).
</blockquote></details>

I don't understand why refactored code is not helpful for further code rewrite.

---
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9zicYBVhbBic_7DJ_:-MhGXO8y60vLabZso_NE:b-5xvr1v) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_finalize_manifest.py#L204)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this is wrong. You should pass manifest's path into `EnclaveMemory` just as you pass libpal.
</blockquote></details>

why it is wrong ? please be more specific, thanks.
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 33 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh1tlXt7U-gAH998YPM:-MhGYgLOEwhk3T3Hg1e3:brg2y9g) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L33)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This function should be part of `__init__`, there's no need to separate this.
</blockquote></details>

why cannot separate it ? please be more specific, thanks.
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 39 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh1wwS-2R88o-vaPNeK:-MhGYGz_6hVCJNTIk8-q:b-4jbvvd) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L39)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This function should be private (`def _set_defaults(self):`).
</blockquote></details>

this function could be a used externally, why we need to limit it ?
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 175 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2VnHKCney-7Sv_37u:-MhGYoNXDdCA0eBOacV_:by40t57) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L175)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Same as above: don't `print()` from a function called `get_*()`.
</blockquote></details>

Agree on this, thanks.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzO1ERBvR8WC0PlXIE:-MhG_NQtE389LMiQekdB:bo1tdsb) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

libpal_file and key, while special, could be just added to the accumulator and not stored as attributes. Also, `.dependencies` attribute should be initialised in `__init__`.

So this should look something like this:

```python
def __init__(self, manifest, sigfile_name, *args):
    self.dependencies = {*args}
```

And the sigfile_name should be reordered in invocation.
</blockquote></details>

do we allow to add any `args` through this way ? it looks unchecked and unsafe way to add dependencies.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 21 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzNkKH65Gu_zP07U4p:-MhGa9ru8uKFr5w4QI_t:b-lbd6g8) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is attribute creation outside `__init__`, plz move this to `__init__` and ideally this should be initialised as `self.dependencies = {*initial}
</blockquote></details>

why we cannot call it explicitly ? usually, the `init` code should be minimized. 
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzO8_g6xqvqOLU0Oj3:-MhGanqj-AFKZkfVFrFr:b-22b4tr) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L29)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`open()`ing should be left for the caller of this function, to be used as:

```python
with open('filename', 'w') as file:
    dg.write(file)
```
</blockquote></details>

Don't understand this, please clarify it, thanks.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 21 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2mWKCCqgZsQKD3G6u:-MhGatex7xXfABxF__46:b-rqxvo7) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_sigstruct.py#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Everything in this function should be just in `__init__`.
</blockquote></details>

ditto.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 55 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2mGUNBhJdCf5MstrT:-MhGb2FvBMafRRsoVLwy:b-an7o7b) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_sigstruct.py#L55)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please rename to `def sign(self, keyfile):`
</blockquote></details>

the simple function name sign(...) may cause confusion due to there are many places contains the word `sign`, the more specific the better.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 94 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2miJH5x9Rc4YHHpBM:-MhGbfYm2jTNxU31RlEv:b-dc7z7t) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_sigstruct.py#L94)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The file should be opened externally to this function.
</blockquote></details>

why ? please be more specific ?
___
*[python/graphenelibos/sgx_get_enclave_mem_areas.py, line 181 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2qk6C3Fuf41BHycGw:-MhGblkQ1GkvNk-Gcdj1:b-rqxvo7) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_get_enclave_mem_areas.py#L181)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i [...]

2021-08-18 12:16 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2596)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @bigdata-memory, @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mfr_tb52iMBKKdHEuVl:-MhO8URH3LFGRd6CBeCs:b-2pn6bk) (no related file):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

I don't understand why refactored code is not helpful for further code rewrite.
</blockquote></details>

Refactored doesn't mean it should be put in different files. For now it's enough to cut it into classes and still keep in a single file.

---
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mg9zicYBVhbBic_7DJ_:-MhO95zVEVHe4syA0gLQ:ba117ax) ([raw file](https://github.com/oscarlab/graphene/blob/5a2e0738f34072ec978043a508495a43e562ab9c/python/graphenelibos/sgx_finalize_manifest.py#L204)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

why it is wrong ? please be more specific, thanks.
</blockquote></details>

Because data flow is contrived. Why it's needed to handle manifest and libpal differently?
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 33 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh1tlXt7U-gAH998YPM:-MhO8kbqDHOIOjBiroKx:b-oc8eiy) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L33)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

why cannot separate it ? please be more specific, thanks.
</blockquote></details>

Why would you? You don't need to reload the manifest, so this function as a separate entity is unnecessary.
___
*[python/graphenelibos/sgx_finalize_manifest.py, line 39 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh1wwS-2R88o-vaPNeK:-MhO9-GU3E5x8SCV34og:b-85u9pq) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_finalize_manifest.py#L39)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

this function could be a used externally, why we need to limit it ?
</blockquote></details>

In what scenario this function could be used externally?
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzO1ERBvR8WC0PlXIE:-MhO9P4f7FTOsh7ehRRp:b-vc3zc) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L14)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

do we allow to add any `args` through this way ? it looks unchecked and unsafe way to add dependencies.
</blockquote></details>

You may need some other files which weren't added by trusted_files expansion, for example from manifest renderer, which can substitute anything really, so maybe even content derived from a file.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 21 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzNkKH65Gu_zP07U4p:-MhO9icT1aPiI4fggNOe:b-1mvn85) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L21)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

why we cannot call it explicitly ? usually, the `init` code should be minimized. 
</blockquote></details>

Nope, there's no need to (within reason). Adding another function call is adding another way to use this class wrong.
___
*[python/graphenelibos/sgx_gen_make_deps.py, line 29 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-MgzO8_g6xqvqOLU0Oj3:-MhO9wFy-dTN6CvOChzK:b-ilbf9g) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_make_deps.py#L29)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

Don't understand this, please clarify it, thanks.
</blockquote></details>

Remove `with open(depfile, ...)` from this function and move it to caller.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 21 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2mWKCCqgZsQKD3G6u:-MhOA9R-5XJP5qLgPfHb:b5lmad0) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_sigstruct.py#L21)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

No, here this should be more than anything else. Optimally there should be two different classes, one for TBSSIGSTRUCT (unsigned SIGSTRUCT) and another for signed SIGSTRUCT, both immutable. Mutability of this class is just asking for misuse.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 55 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2mGUNBhJdCf5MstrT:-MhOAVAA60oLqa6Pcn4T:b-fk0s4r) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_sigstruct.py#L55)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

the simple function name sign(...) may cause confusion due to there are many places contains the word `sign`, the more specific the better.
</blockquote></details>

Yes, esp. if we might want different signing mechanisms (submission signatures and/or smartcards). Please leave for now, we'll revisit this in the future.
___
*[python/graphenelibos/sgx_gen_sigstruct.py, line 94 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2miJH5x9Rc4YHHpBM:-MhOAnDO7IdFlzk_fCSC:b-j4nkfd) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_gen_sigstruct.py#L94)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

why ? please be more specific ?
</blockquote></details>

Remove `with open()` from this function and add to the caller.
___
*[python/graphenelibos/sgx_get_enclave_mem_areas.py, line 181 at r3](https://reviewable.io/reviews/oscarlab/graphene/2596#-Mh2qk6C3Fuf41BHycGw:-MhOAuGT7AicMs6DTICj:b-xjpv9x) ([raw file](https://github.com/oscarlab/graphene/blob/49bbac15ae40be366496e4e181a3eeb042a1de26/python/graphenelibos/sgx_get_enclave_mem_areas.py#L181)):*
<details><summary><i>Previously, bigdata-memory (Gordon King) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

NAK. Please do as instructed.


<!-- Sent from Reviewable.io -->

2021-10-03 02:17 UTC, mkow commented
This was superseded by https://github.com/gramineproject/gramine/pull/72, closing.

2021-10-03 02:17 UTC, closed without merging