[Documentation] conf.py: Check the version of sphinx at the beginning of setup() to avoid invoking deprecated method
oscarlab/graphene pull request #2601
Opened 2021-07-31 16:33 UTC by xymeng16

This PR is related to building the documentation. 

In the setup() function of conf.py, app.add_stylesheet() is used to add a CSS file. But this only works for Sphinx under version 1.8 as Sphinx has renamed app.add_stylesheet() into app.add_css_file() since version 1.8. Hence I added a version check before invoking that to avoid that such an error happens.

## How to test?
Change the directory into Documentation/, and use `make html`.

2021-07-31 22:52 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2601)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @xymeng16)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2601#-Mfyl-Zd26qEhJRYEjLE:-Mfyl-Zd26qEhJRYEjLF:b57i9tw) (no related file):*
Hmm, but we have `sphinx==1.8.0` in our `requirements.txt`? So, I'm not sure if we should add IFs for other versions, I don't think we support them.
CC: @woju

---


<!-- Sent from Reviewable.io -->

2021-08-01 11:45 UTC, xymeng16 commented
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2601#-Mfyl-Zd26qEhJRYEjLE:-Mg0W3iy9FSYv-57aIlJ:b-ki9jh2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, but we have `sphinx==1.8.0` in our `requirements.txt`? So, I'm not sure if we should add IFs for other versions, I don't think we support them.
CC: @woju
</blockquote></details>

Oh, thanks for your reply. I have the sphinx installed in my environment so I ignored the `requirements.txt`. So if applicable, please ignore and close this PR. 

(FYI, at least sphinx 4.1.2 and 4.0.0.b2 works based on my tests.)

---


<!-- Sent from Reviewable.io -->

2021-08-01 22:33 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2601)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2601#-Mfyl-Zd26qEhJRYEjLE:-Mg2qImQ0nlXb8qmFDtw:b-ozxsxm) (no related file):*
<details><summary><i>Previously, xymeng16 (Xiangyi Meng) wrote…</i></summary><blockquote>

Oh, thanks for your reply. I have the sphinx installed in my environment so I ignored the `requirements.txt`. So if applicable, please ignore and close this PR. 

(FYI, at least sphinx 4.1.2 and 4.0.0.b2 works based on my tests.)
</blockquote></details>

No worries :)
Let's wait for @woju to comment on this, he's maintaining this part.

---


<!-- Sent from Reviewable.io -->

2021-08-02 22:37 UTC, woju commented
I'm unconvinced. We can't update sphinx at least until 22.04, because 20.04 still has sphinx 1.8 and we will need deb-packaged sphinx to build manpages in our debs (its not only for rtfd.io, where we could have greater latitude). When we'll be eventually upgrading, we'll just rename the function, without this conditional. So unless I miss something, this brings nothing but maintenance. If anything, I would prefer a comment `# after sphinx $VERSION, rename this to .add_css()`.

2021-08-03 08:01 UTC, dimakuv commented
Thanks for the PR, @xymeng16, but based on input from @mkow and @woju looks like we should close it.

2021-08-03 08:01 UTC, closed without merging