[Pal] Make "syscall" instruction appear only once in PAL binary
oscarlab/graphene pull request #2602
Opened 2021-08-02 01:50 UTC by boryspoplawski

## Description of the changes 
This is needed to properly handle signals interrupting ocalls on SGX PAL. It will probably also be useful in fixing the issue of signals appearing while in LibOS, but before issuing a host level syscall instruction (in which case the signal is blocked until the syscall returns or another signal appears).

Fixes #2532

## How to test this PR? 
Check #2532 for example code failing on current master.

2021-08-02 02:13 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: 0 of 51 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg3Zm4OAM5mTaxhTxh5:-Mg3Zm4P2r7Xw0NTfrkx:b-8b0004) (no related file):*
Unfortunately I'm afraid that the current version of `do_syscall(long, ...)` is an UB: on each callsite arguments are not extended to the full register size. E.g. that could fail: `DO_SYSCALL(kill, -1, SIGTERM)` - `-1` is an `int` and will be passed via 32bit register (here `esi`), so the generated code will most likely be `mov esi, 0xffffffff`. If the kernel expects an `int` argument this might work, but if it expects `long` (64bit in this case), then this will fail as upper half of `rsi` contains zeros.
This can also be problematic on architectures that pass arguments in different places depending of the type of previous arguments (e.g. `f(u32 a0, u32 a1, u64 a2)` and args passed on stack: `a0` at offset `0`, `a1` at offset `4`(`sizeof(u32)`) and `a2` at offset `8` - now change all args to `u64`...).

I do not see any other solution that reintroducing an additional argument to `DO_SYSCALL` indicating the number of arguments and casting all necessary args to `long`, `uint64_t` or whatever (this code will be arch specific anyway).
Ideas?

---


<!-- Sent from Reviewable.io -->

2021-08-02 10:34 UTC, dimakuv requested changes
> Reviewed 51 of 51 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg3Zm4OAM5mTaxhTxh5:-Mg5B0so2BOwKzH88taM:b-6vdw9f) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Unfortunately I'm afraid that the current version of `do_syscall(long, ...)` is an UB: on each callsite arguments are not extended to the full register size. E.g. that could fail: `DO_SYSCALL(kill, -1, SIGTERM)` - `-1` is an `int` and will be passed via 32bit register (here `esi`), so the generated code will most likely be `mov esi, 0xffffffff`. If the kernel expects an `int` argument this might work, but if it expects `long` (64bit in this case), then this will fail as upper half of `rsi` contains zeros.
This can also be problematic on architectures that pass arguments in different places depending of the type of previous arguments (e.g. `f(u32 a0, u32 a1, u64 a2)` and args passed on stack: `a0` at offset `0`, `a1` at offset `4`(`sizeof(u32)`) and `a2` at offset `8` - now change all args to `u64`...).

I do not see any other solution that reintroducing an additional argument to `DO_SYSCALL` indicating the number of arguments and casting all necessary args to `long`, `uint64_t` or whatever (this code will be arch specific anyway).
Ideas?
</blockquote></details>

What about this variadic-macro trick: https://stackoverflow.com/a/11763277/6325371? It basically overloads `DO_SYSCALL` macro with `DO_SYSCALL0`, `DO_SYSCALL1`, .. `DO_SYSCALL6` depending on the number of arguments provided. Looks very neat. Our use case also has the benefit of having only 0 to 6 arguments always, so this simplifies things.

And in each of these `DO_SYSCALL0`, `DO_SYSCALL1`, .. `DO_SYSCALL6` we cast the args before we call `do_syscall`.

---
___
*[Pal/src/host/Linux/db_files.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5D-Ow9X4tMz62DiDn:-Mg5D-Ow9X4tMz62DiDo:brd9qne) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux/db_files.c#L161)):*
> ```C
> 
>     if (IS_PTR_ERR(mem))
>         return PTR_TO_ERR(mem);
> ```

We also need to change from UNIX to PAL error code.
___
*[Pal/src/host/Linux/db_process.c, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5D_KmDkqz89g0QBOW:-Mg5D_KmDkqz89g0QBOX:bd6zi2o) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux/db_process.c#L116)):*
> ```C
>  * NOTE: more tricks may be needed to prevent unexpected optimization for
>  * future compiler.
>  */
> ```

Why is this comment not relevant anymore? Is it because we call `do_syscall()` asm function immediately after vfork, and there is no "room" for compiler to rearrange something on stack before this call?
___
*[Pal/src/host/Linux/pal_linux.h, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5FkSaCwPFpo5ZKZG-:-Mg5FkSaCwPFpo5ZKZG0:b-hddku8) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux/pal_linux.h#L71)):*
> ```objc
>     })
> #else
> #define ARCH_MMAP(addr, len, prot, flags, fd, offset) \
> ```

Wouldn't it make more sense to move `ARCH_MMAP` to the arch-specific header? And since we don't have currently (and most probably never) the "old-style" x86 mmap, we just remove the `ifdef __i386__` version of mmap.

Also, renaming to smth like `DO_SYSCALL_MMAP` sounds better.
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5GtIh5pZdv-uiowUl:-Mg5GtIh5pZdv-uiowUm:biygif1) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L6)):*
> ```
>  */
> 
> /* Oh boy. */
> ```

Why oh boy?
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5H4x01zOjerrudTpc:-Mg5H4x01zOjerrudTpd:b4evaa2) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L9)):*
> ```
> #define __ASSEMBLY__
> #include <asm/unistd.h>
> #include <linux/sched.h>
> ```

Why do you need this one?
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5IZdI8yX6g-dU6hKY:-Mg5IZdI8yX6g-dU6hKZ:bolkdlr) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L23)):*
> ```
>     mov %r9, %r8
>     mov 8(%rsp), %r9
>     syscall
> ```

r11 is not used by Linux syscalls? It is supposed to store `saved rflags`, but you don't shash rflags into r11 here, so r11 can be random.
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5KYtP4SB7j6k9Y_Ex:-Mg5KYtQ5GOOJkrNTGP6:b227gsp) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L81)):*
> ```
> vfork:
>     .cfi_startproc
>     pop %rdx
> ```

What is this pop/push of rdx? I see that it is done also in Musl, Glibc... What is this for?
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 303 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5KqVN9jbWJHJkJ5R_:-Mg5KqVN9jbWJHJkJ5Ra:bfsrm35) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux-SGX/pal_linux.h#L303)):*
> ```objc
> #define ARCH_VFORK()                                                                 \
>     (g_pal_enclave.pal_sec.in_gdb                                                    \
>          ? INLINE_SYSCALL(clone, 4, CLONE_VM | CLONE_VFORK | SIGCHLD, 0, NULL, NULL) \
> ```

I hope our GDB integration still works? I guess we have no idea why `SIGCHLD` was used for DEBUG?
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 208 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5LDCQ4PZCF7f78iPL:-Mg5LDCQ4PZCF7f78iPM:b-7ived9) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-SGX/sgx_enclave.c#L208)):*
> ```C
>     ms_ocall_fsync_t* ms = (ms_ocall_fsync_t*)pms;
>     ODEBUG(OCALL_FSYNC, ms);
>     return DO_SYSCALL_INTERRUPTIBLE(fsync, ms->ms_fd);
> ```

We could simplify like this almost all functions here (combine `return` with `DO_SYSCALL`).
___
*[Pal/src/host/Linux-SGX/sgx_entry.S, line 175 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5Ppjm48UqbxubxjyS:-Mg5PpjnAOVCXVLQ1xdH:bd6py0k) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-SGX/sgx_entry.S#L175)):*
> ```
> 	movq %rax, %rdi
> 	xor %esi, %esi
> 	lock xchgl %esi, %gs:PAL_TCB_URTS_LAST_ASYNC_EVENT
> ```

From what I understand, we can return both the "host-level syscall return value" (which may be a success) and the "last seen async event". So it is possible that both things happened: the syscall was finished, and there was an async event.

This is cool, but does our trusted-PAL code supports this already?
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 189 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5OYnD65qeqiapUX86:-Mg5OYnE3TMvopy7iVvx:b-x8kcr7) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-SGX/sgx_exception.c#L189)):*
> ```C
>             || rip == (uint64_t)&do_syscall_intr_after_check2) {
>         ucontext_set_ip(uc, (uint64 [...]

2021-08-02 16:31 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: 44 of 51 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg3Zm4OAM5mTaxhTxh5:-Mg5trZECnIMx1K3ovpc:b-km5xk) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this variadic-macro trick: https://stackoverflow.com/a/11763277/6325371? It basically overloads `DO_SYSCALL` macro with `DO_SYSCALL0`, `DO_SYSCALL1`, .. `DO_SYSCALL6` depending on the number of arguments provided. Looks very neat. Our use case also has the benefit of having only 0 to 6 arguments always, so this simplifies things.

And in each of these `DO_SYSCALL0`, `DO_SYSCALL1`, .. `DO_SYSCALL6` we cast the args before we call `do_syscall`.
</blockquote></details>

Damn, that's evil. But it would work.

---
___
*[Pal/src/host/Linux/db_files.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5D-Ow9X4tMz62DiDn:-Mg5u3Zf8G7J5RzCd7R5:b7f4sft) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux/db_files.c#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We also need to change from UNIX to PAL error code.
</blockquote></details>

Opps, good catch.
___
*[Pal/src/host/Linux/db_process.c, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5D_KmDkqz89g0QBOW:-Mg5ujKnE_Vo3obfHeSA:bj4t473) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux/db_process.c#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this comment not relevant anymore? Is it because we call `do_syscall()` asm function immediately after vfork, and there is no "room" for compiler to rearrange something on stack before this call?
</blockquote></details>

This comment was partially wrong and relied on specific compiler behavior. Now `vfork` is marked as `returns_twice`, which should give the compiler enough information. Note that the child process also ran a function `handle_set_cloexec` which was one big UB.
___
*[Pal/src/host/Linux/pal_linux.h, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5FkSaCwPFpo5ZKZG-:-Mg6ETJzAtsQms8d_vP4:b-mij2ty) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux/pal_linux.h#L71)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wouldn't it make more sense to move `ARCH_MMAP` to the arch-specific header? And since we don't have currently (and most probably never) the "old-style" x86 mmap, we just remove the `ifdef __i386__` version of mmap.

Also, renaming to smth like `DO_SYSCALL_MMAP` sounds better.
</blockquote></details>

I just didn't want to stash even more changes to this PR, but you might be right that it's related and this PR is probably a good place to fix it.
Done. Since couple of popular archs (checked x86, arm and ppc) support a syscall with the same name (`mmap`) and same args, I just simply removed it.
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5GtIh5pZdv-uiowUl:-Mg6_YeL1l3hWBbVZDy-:brsjxls) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why oh boy?
</blockquote></details>

Need to manually define `__ASSEMBLY__` because these headers do not use a more standard `__ASSEMBLER__` (due to historical reasons).
Removed that comment.
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5H4x01zOjerrudTpc:-Mg6a3DFC-cUpaSUbI5k:bdi5189) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this one?
</blockquote></details>

Artifact from intermediate version which had clone flags hardcoded (until I realized we use clone in multiple places).
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5IZdI8yX6g-dU6hKY:-Mg6aF1Z6yycoz0O4URa:ble07mz) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

r11 is not used by Linux syscalls? It is supposed to store `saved rflags`, but you don't shash rflags into r11 here, so r11 can be random.
</blockquote></details>

I do not understand your comment. `r11` does not need to be preserved in function calls and it's not an argument to syscall, why would we want to do anything? The CPU stores flags in `r11`, but that's not important.
___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5KYtP4SB7j6k9Y_Ex:-Mg6an1h7i2iu1wnuiLH:b-u92vlr) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this pop/push of rdx? I see that it is done also in Musl, Glibc... What is this for?
</blockquote></details>

Because the child process will return here and most likely clobber the stack, including the return address from `vfork`, as it's going to call `execve` or `exit`. We stash the return address inside register because the child process wont affect those.
Picked `rdx` as `rax` is used by syscall, `rbx` needs to be preserved across function calls, `rcx` is used by syscall, and next is `rdx` :)
Updated the code a bit (jmp instead of push+ret).
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 303 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5KqVN9jbWJHJkJ5R_:-Mg6cMRjAONEY_Ta6XBb:bjzqg0w) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux-SGX/pal_linux.h#L303)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I hope our GDB integration still works? I guess we have no idea why `SIGCHLD` was used for DEBUG?
</blockquote></details>

What do you mean? We use vfork syscall now (at least on x64) which is equivalent to `clone` with `SIGCHLD` (and some other flags). The question is why `SIGCHLD` was not set in non debug builds and I guess it was an optimization: back in the day we did not ignore `SIGCHILD` as we now do.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 208 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5LDCQ4PZCF7f78iPL:-Mg6cyaY88V2e6dGaNdS:b-ft5bo1) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-SGX/sgx_enclave.c#L208)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We could simplify like this almost all functions here (combine `return` with `DO_SYSCALL`).
</blockquote></details>

We could do a lot of things with this file :) You want me to add them here? I could, no problem from my side.
___
*[Pal/src/host/Linux-SGX/sgx_entry.S, line 175 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5Ppjm48UqbxubxjyS:-Mg6dAH [...]

2021-08-02 17:45 UTC, aneessahib commented
>>Async signal happened during or right-before host-level syscall: in this case we emulate -EINTR on this syscall, without executing it.

in case of futex waits- the application expects the remainder  of the time (total - interrupted time) to be sent back to the application. we have this logic after the host has returned from syscall, but it wont run If we EINTR without executing it. Which is probably why this fix is not working for #2260

2021-08-02 18:04 UTC, boryspoplawski reviewed
What? We do execute it regardless of EINTRs. Besides this PR  did fix #2260 for me.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602#-:-Mg70SGC4c8L3VQvZVGh:b-7cukvm)* status: 44 of 51 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-08-02 18:57 UTC, dimakuv submitted a review, later dismissed
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-common/arch/x86_64/syscall.S, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5IZdI8yX6g-dU6hKY:-Mg76bCe7pAuLsd3rRvV:biorfrw) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-common/arch/x86_64/syscall.S#L23)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I do not understand your comment. `r11` does not need to be preserved in function calls and it's not an argument to syscall, why would we want to do anything? The CPU stores flags in `r11`, but that's not important.
</blockquote></details>

Ok, my bad, I forgot that it is the `syscall` instruction itself who puts rflags into r11.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 303 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5KqVN9jbWJHJkJ5R_:-Mg782SP9zXl8T0RbSL6:bomsr9q) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux-SGX/pal_linux.h#L303)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

What do you mean? We use vfork syscall now (at least on x64) which is equivalent to `clone` with `SIGCHLD` (and some other flags). The question is why `SIGCHLD` was not set in non debug builds and I guess it was an optimization: back in the day we did not ignore `SIGCHILD` as we now do.
</blockquote></details>

True, I just realized that previously vfork was done via `clone()` and now you switched to the actual `vfork()`.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 208 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5LDCQ4PZCF7f78iPL:-Mg78MCT0S5coyz-8TIG:b96lpa8) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-SGX/sgx_enclave.c#L208)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

We could do a lot of things with this file :) You want me to add them here? I could, no problem from my side.
</blockquote></details>

No, let's not bother.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 189 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5OYnD65qeqiapUX86:-Mg7AKL0065j9NaxQeEC:b-1f1f2s) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-SGX/sgx_exception.c#L189)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No. There are 3 cases:
1. Async signal happened while in enclave - nothing changes here, we just enter the enclave and let that code handle the event.
2a. Async signal happened outside of the enclave (in general) - we just memorize the event and report it when returning back from ocall. Old code did the same, but it also forcibly moved rip to ocall return code and injected `-EINTR`. Now we just save it and syscall executing functions checks that value and reports `-EINTR` instead of actually issuing the syscall (but only the `DO_SYSCALL_INTERRUPTIBLE` macro, in some places we want to issue the syscall unconditionally, which we can do with `DO_SYSCALL`).
2b. Special case of above: if the signal happened while checking whether the last_event is set (checking happens inside the `do_syscall_intr` function, just before `syscall` instruction), we forward `rip` behind that check and `syscall` instruction, where `-EINTR` is set. There are only two problematic instruction, both checked here.

This code should work in all cases, i.e. there are no lost signals and they always preempt blocking syscalls, even if such signals arrives before the actual syscall!
</blockquote></details>

OK, you are right. I missed to combine the pieces in your PR. I was mainly interested in case 2a. But now I see that:
- An async signal happens, it lands in this exception handler which sets `last_async_event`
- Then the exception handler is done, Linux moves the thread to the normal execution context, which continues whenever it was interrupted
- If we were in the `do_syscall_intr()` prologue code (or somewhere before it), we'll notice `last_async_event` was set and skip the syscall
- If we were somewhere else (after `do_syscall_intr()`), we'll notice `last_async_event` in `sgx_entry.S` and set `rsi`


<!-- Sent from Reviewable.io -->

2021-08-02 19:38 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: 50 of 51 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg3Zm4OAM5mTaxhTxh5:-Mg7G9FZ0pbXg1jsyzkT:b-896fix) (no related file):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Damn, that's evil. But it would work.
</blockquote></details>

Done.

---
___
*[Pal/src/host/Linux-SGX/sgx_entry.S, line 175 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg7MrvB8YEuAuYo6cyF:-Mg7MrvB8YEuAuYo6cyG:b-1r3uxy) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_entry.S#L175)):*
> ```
> 	movq %rax, %rdi
> 	xor %esi, %esi
> 	lock xchgl %esi, %gs:PAL_TCB_URTS_LAST_ASYNC_EVENT
> ```

Note that a `lock` is implicit in `xchg` with one memory operand, but I just wanted to make this explicit.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 189 at r1](https://reviewable.io/reviews/oscarlab/graphene/2602#-Mg5OYnD65qeqiapUX86:-Mg7HkgR8_NUp3IM7O8P:bd5pos8) ([raw file](https://github.com/oscarlab/graphene/blob/d245dff63aac750bff5eae6a188329d6a90c4ebe/Pal/src/host/Linux-SGX/sgx_exception.c#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, you are right. I missed to combine the pieces in your PR. I was mainly interested in case 2a. But now I see that:
- An async signal happens, it lands in this exception handler which sets `last_async_event`
- Then the exception handler is done, Linux moves the thread to the normal execution context, which continues whenever it was interrupted
- If we were in the `do_syscall_intr()` prologue code (or somewhere before it), we'll notice `last_async_event` was set and skip the syscall
- If we were somewhere else (after `do_syscall_intr()`), we'll notice `last_async_event` in `sgx_entry.S` and set `rsi`
</blockquote></details>

Note that `last_async_event` will be returned regardless when the exception happens (even before the syscall).
This actually reminded me that there still is a small window when the even will be missed (well, actually reported on the next ocall): if it happens after `xchg %rsi, ...` instruction and before EENTER in `sgx_entry.S`. I don't think we should bother fixing that tho: only possible events are `PAL_INTERRUPTED` and `PAL_QUIT`. The former is merely an interrupt to make Graphene notice some state changes (so missing it is irrelevant when we return from ocall) and the latter rarely used.


<!-- Sent from Reviewable.io -->

2021-08-03 06:15 UTC, dimakuv approved these changes, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-08-03 16:47 UTC, mkow requested changes
> Reviewed 9 of 51 files at r1, 2 of 7 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/include/host/Linux-common/syscall.h, line 27 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgBjfZ65ssf9-LSC4W_:-MgBjfZ65ssf9-LSC4Wa:b15e1k) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/include/host/Linux-common/syscall.h#L27)):*
> ```objc
> 
> #define DO_SYSCALL(name, args...) \
>     PICK_SYSCALL_MACRO(name, ##args, 6, 5, 4, 3, 2, 1, 0)(__NR_##name, ##args)
> ```

wow, that's a clever trick
___
*[Pal/include/host/Linux-common/syscall.h, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgBrH731z1b8UwD90kn:-MgBrH7448zgu6sOObyS:b94h6w6) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/include/host/Linux-common/syscall.h#L30)):*
> ```objc
> 
> #define IS_PTR_ERR(val) ((unsigned long)(val) >= -4095UL)
> #define PTR_TO_ERR(val) ((long)val)
> ```

`val` should be parenthesized


<!-- Sent from Reviewable.io -->

2021-08-04 20:28 UTC, mkow requested changes
> Reviewed 34 of 51 files at r1, 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 122 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHjf5f38r9IaKlRKkm:-MgHjf5f38r9IaKlRKkn:b-yiz8ny) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_enclave.c#L122)):*
> ```C
>     ms_ocall_close_t* ms = (ms_ocall_close_t*)pms;
>     ODEBUG(OCALL_CLOSE, ms);
>     DO_SYSCALL(close, ms->ms_fd);
> ```

isn't `close()` also interruptible in some exotic cases?
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 188 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHk7Xo5BQOtyX_hYW2:-MgHk7Xp0zYkM0XAw51M:b82jpkd) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_enclave.c#L188)):*
> ```
> O_NONBLOCK
> ```
this one is with `O_NONBLOCK`, so I guess it shouldn't be interruptible?
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHmJkG0xpp78ptg6NU:-MgHmJkG0xpp78ptg6NV:b-w3gnkg) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux-SGX/sgx_exception.c#L223)):*
> ```C
>         goto err;
> 
>     ret = set_signal_handler(SIGSYS, handle_sync_signal);
> ```

why it was here originally, and why can we remove it now?


<!-- Sent from Reviewable.io -->

2021-08-05 18:21 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/include/host/Linux-common/syscall.h, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgBrH731z1b8UwD90kn:-MgMWiyfCHf-wxLNC3wx:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/include/host/Linux-common/syscall.h#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`val` should be parenthesized
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 122 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHjf5f38r9IaKlRKkm:-MgMWjxLCrSZL9lm_aTS:baspkf5) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_enclave.c#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

isn't `close()` also interruptible in some exotic cases?
</blockquote></details>

No. I mean it is, but Linux closes the fd anyway and only then returns `-EINTR`, but since you cannot repeat close on errors, I've decided to make it ignore signals.
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 188 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHk7Xo5BQOtyX_hYW2:-MgMX6QJ3vGkfwiKNxS8:b-2p1no4) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_enclave.c#L188)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> O_NONBLOCK
> ```
this one is with `O_NONBLOCK`, so I guess it shouldn't be interruptible?
</blockquote></details>

It's rather about `F_SETFL`, but yes.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHmJkG0xpp78ptg6NU:-MgMXnfK5ASCo_2IUIod:b-tdttfx) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux-SGX/sgx_exception.c#L223)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why it was here originally, and why can we remove it now?
</blockquote></details>

No idea why it was here. Why wouldn't we remove it, if it's useless? 


<!-- Sent from Reviewable.io -->

2021-08-05 18:22 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: 49 of 51 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHmJkG0xpp78ptg6NU:-MgMY5bT05cFCAQkCU7d:b-tysqet) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux-SGX/sgx_exception.c#L223)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No idea why it was here. Why wouldn't we remove it, if it's useless? 
</blockquote></details>

Wasn't there some kind of sandbox feature implemented a long time ago? Maybe it used seccomp...


<!-- Sent from Reviewable.io -->

2021-08-05 18:23 UTC, mkow requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 122 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHjf5f38r9IaKlRKkm:-MgMYQEuCUjF6IbxupPZ:b4il27w) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_enclave.c#L122)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

No. I mean it is, but Linux closes the fd anyway and only then returns `-EINTR`, but since you cannot repeat close on errors, I've decided to make it ignore signals.
</blockquote></details>

Could you say this in a comment here?
___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 188 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHk7Xo5BQOtyX_hYW2:-MgMYXSMBBm9Ct4u2jak:b-1ujfa8) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_enclave.c#L188)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It's rather about `F_SETFL`, but yes.
</blockquote></details>

Ah, true.
___
*[Pal/src/host/Linux-SGX/sgx_exception.c, line 223 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHmJkG0xpp78ptg6NU:-MgMYZv_A6w-QFGm0ydr:b-1d5ldv) ([raw file](https://github.com/oscarlab/graphene/blob/3182ca948c6712631a3ac9bf8983b8103351c9a9/Pal/src/host/Linux-SGX/sgx_exception.c#L223)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Wasn't there some kind of sandbox feature implemented a long time ago? Maybe it used seccomp...
</blockquote></details>

Hmm, maybe...


<!-- Sent from Reviewable.io -->

2021-08-05 20:12 UTC, boryspoplawski reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[Pal/src/host/Linux-SGX/sgx_enclave.c, line 122 at r3](https://reviewable.io/reviews/oscarlab/graphene/2602#-MgHjf5f38r9IaKlRKkm:-MgMwZJyBnUkoLd4GfpH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/41fbbdd5297055233fcd10544cac16587c9aa8cf/Pal/src/host/Linux-SGX/sgx_enclave.c#L122)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you say this in a comment here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-05 22:05 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-08-05 23:58 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-06 07:32 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2602)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-06 07:33 UTC, merged