[Pal/{Linux,Linux-SGX}] Fix early log messages crashing PAL
oscarlab/graphene pull request #2618
Opened 2021-08-04 16:34 UTC by pwmarcz

## Description of the changes 

The logging subsystem (`log_error`) requires relocations to be applied before use, due to use of `log_level_to_prefix` array. This caused early calls to `log_error()` to crash.

To fix that, we apply relocations earlier in the startup process.

## Alternatives

- **Compile PAL so that no relocations are necessary** - I'm not sure if that's possible if PAL is position-independent? Apparently GCC has [-static-pie](https://stackoverflow.com/questions/62586808/how-are-relocations-supposed-to-work-in-static-pie-binaries), but it just shifts the work of applying these relocations to runtime (by calling a glibc function)...
- **Compile PAL so that it's at a static position** - probably it's not worth it just for that?
- **Make `log_*` code position-independent**. Maybe that's worth doing regardless of this fix, just in case? So that e.g. we can use log messages in relocation code.

   The problem is that the array (`static const char* log_level_to_prefix[]`) contains the right pointers only after applying relocations. The simplest fix would be to use a `switch` instead of a global array. Experimentally, this does produce position-independent code (although with `-O3` it still produces a sequence of conditions, not a lookup table).

  Alternatively, changing it to `const char log_level_to_prefix[][16]` produces a flat array.
- **Install stack canary **after** relocations** - under Linux host, we start by setting up the stack canary; this can be moved further down if the relocation code itself is marked as `__attribute_no_stack_protector`, but I'm not sure if that's a good idea

## How to test this PR? 

`log_error` calls just after `ELF_DYNAMIC_RELOCATE()` should work correctly, and there should be no calls _before_ it.

On master, calls to `log_error` before `ELF_DYNAMIC_RELOCATE()` produce a segfault under Linux, and print a message with no prefix under Linux-SGX (as the non-relocated pointers end up pointing to null bytes by accident).

2021-08-04 17:11 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-05 06:34 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJzBA6AfOg55DBK8t9:-MgJzBA6AfOg55DBK8tA:bnp5kk9) (no related file):*
I like this PR as-is. But just comments on alternatives:

> Compile PAL so that no relocations are necessary

This looks impossible to do. Some kind of runtime relocation routine is still needed, so no difference to what we do right now.

> Compile PAL so that it's at a static position

I don't like this one for several reasons. First, on Linux PAL, we may get into the problem with tools like Valgrind (IIRC, Valgrind wants to put the executable at a specific location? something like this). Second, on Linux-SGX PAL, we definitely want the trusted-PAL binary to be placed in different parts of the enclave memory (right now we place it at the top of enclave address space, and since enclave sizes vary, this near-the-top address also varies).

> Make log_* code position-independent.

This can bo done, but this only solves one particular problem (with log functions). The same issue can happen with some other functionality that we want to add later...

> Install stack canary after relocations

This is tricky. I am pretty sure we want to install the stack canary as the very first thing in the Linux PAL (in Linux-SGX PAL, we don't need to worry because the untrusted runtime already set up a dummy stack canary for us, so at least all function calls work, and installing the real stack canary can be pushed to the very end). Marking all functions before installing the stack canary as "no-stack-protector" is tedious, error-prone, and just not right.

---
___
*[Pal/src/host/Linux/db_main.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJyKSJCxC_bcU8FOBe:-MgJyKSJCxC_bcU8FOBf:b-1jq7bc) ([raw file](https://github.com/oscarlab/graphene/blob/f1ad322b8d7e2418d1b1ed1bdd6a5c2467e8fefd/Pal/src/host/Linux/db_main.c#L161)):*
> ```C
>         /* We failed to install a TCB (and haven't applied relocations yet), so no other code will
>          * work anyway */
>         int exitcode = unix_to_pal_error(-ret);
> ```

You don't need `unix_to_pal_error()`. We want to return the UNIX error code in the `exit_group` syscall. (Previously we had the convertion to the PAL error code because `INIT_FAIL()` assumes a PAL error code.)


<!-- Sent from Reviewable.io -->

2021-08-05 16:56 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: 1 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJzBA6AfOg55DBK8t9:-MgMCUuHAq3ZClK8AKuj:bgwyrll) (no related file):*
>IIRC, Valgrind wants to put the executable at a specific location? something like this

It's the opposite: if your code is position-independent, Valgrind will put it at an inconvenient location; you can make it static so that Valgrind will not mess with the position. But this is a bug in Valgrind, and definitely not a good justification for doing it on production.

>>Make `log_*` code position-independent.

>This can bo done, but this only solves one particular problem (with log functions). The same issue can happen with some other functionality that we want to add later...

Okay, I don't want to do this convertion without a good reason, but I'm adding a comment so that it's less confusing for the next person encountering this problem.

>Marking all functions before installing the stack canary as "no-stack-protector" is tedious, error-prone, and just not right.

Yeah, I had to annotate some random inline functions in `dynamic_link.h`, it felt very brittle.

---
___
*[Pal/src/host/Linux/db_main.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJyKSJCxC_bcU8FOBe:-MgMDncB5tVsGdBQ4pdQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f1ad322b8d7e2418d1b1ed1bdd6a5c2467e8fefd/Pal/src/host/Linux/db_main.c#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need `unix_to_pal_error()`. We want to return the UNIX error code in the `exit_group` syscall. (Previously we had the convertion to the PAL error code because `INIT_FAIL()` assumes a PAL error code.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-05 18:09 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: 2 of 3 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_main.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJyKSJCxC_bcU8FOBe:-MgMV0kF9eyNEnmDwqaO:b-pfcs9j) ([raw file](https://github.com/oscarlab/graphene/blob/f1ad322b8d7e2418d1b1ed1bdd6a5c2467e8fefd/Pal/src/host/Linux/db_main.c#L161)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought we had a convention of returning PAL error codes. This version is not ok, since it returns different codes in different places (PAL vs UNIX).


<!-- Sent from Reviewable.io -->

2021-08-05 18:17 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-08-05 18:32 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[Pal/src/host/Linux/db_main.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJyKSJCxC_bcU8FOBe:-MgM_518C3orTvIZ0asQ:b-29kcpo) ([raw file](https://github.com/oscarlab/graphene/blob/f1ad322b8d7e2418d1b1ed1bdd6a5c2467e8fefd/Pal/src/host/Linux/db_main.c#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I thought we had a convention of returning PAL error codes. This version is not ok, since it returns different codes in different places (PAL vs UNIX).
</blockquote></details>

It does look like it. On the other hand, it means also annotating `unix_to_pal_error` (as well as `unix_to_pal_error_positive`) with `__attribute_no_stack_protector`... Should I?


<!-- Sent from Reviewable.io -->

2021-08-05 19:38 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[Pal/src/host/Linux/db_main.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJyKSJCxC_bcU8FOBe:-MgMm3v-8_OnYQsH3H1x:b-4xdg8d) ([raw file](https://github.com/oscarlab/graphene/blob/f1ad322b8d7e2418d1b1ed1bdd6a5c2467e8fefd/Pal/src/host/Linux/db_main.c#L161)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It does look like it. On the other hand, it means also annotating `unix_to_pal_error` (as well as `unix_to_pal_error_positive`) with `__attribute_no_stack_protector`... Should I?
</blockquote></details>

You know what? Just return `1` here, who cares.


<!-- Sent from Reviewable.io -->

2021-08-06 07:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[Pal/src/host/Linux/db_main.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJyKSJCxC_bcU8FOBe:-MgPL2yi3qX02U-NyuUQ:bc14mhb) ([raw file](https://github.com/oscarlab/graphene/blob/f1ad322b8d7e2418d1b1ed1bdd6a5c2467e8fefd/Pal/src/host/Linux/db_main.c#L161)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

You know what? Just return `1` here, who cares.
</blockquote></details>

Oops, true. Well, let's not hard-code `1` as Borys suggests, but at least an actual PAL error. Just do `INLINE_SYSCALL(exit_group, 1, PAL_ERROR_DENIED)`.


<!-- Sent from Reviewable.io -->

2021-08-06 08:11 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[Pal/src/host/Linux/db_main.c, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene/2618#-MgJyKSJCxC_bcU8FOBe:-MgPW7KZ7CemyG3xkzEm:bbr3dvq) ([raw file](https://github.com/oscarlab/graphene/blob/f1ad322b8d7e2418d1b1ed1bdd6a5c2467e8fefd/Pal/src/host/Linux/db_main.c#L161)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops, true. Well, let's not hard-code `1` as Borys suggests, but at least an actual PAL error. Just do `INLINE_SYSCALL(exit_group, 1, PAL_ERROR_DENIED)`.
</blockquote></details>

Sounds good. Done.


<!-- Sent from Reviewable.io -->

2021-08-06 08:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-08-06 09:39 UTC, pwmarcz reviewed
Rebased after f3e34953a4e9ea514f4f54e8f6139b2e0d17c860 changed `INLINE_SYSCALL` to `DO_SYSCALL`.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618#-:-MgPpCas1LJZYkkhDCPP:b-fq6jbo)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)



<!-- Sent from Reviewable.io -->

2021-08-06 12:28 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-08-06 15:07 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, 1 unresolved discussion (waiting on @boryspoplawski)



<!-- Sent from Reviewable.io -->

2021-08-06 15:09 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-06 18:16 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-07 15:59 UTC, boryspoplawski approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-09 06:08 UTC, dimakuv approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2618)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-09 06:09 UTC, merged