[LibOS] Simplify RTLD code
oscarlab/graphene pull request #2625
Opened 2021-08-05 16:10 UTC by pwmarcz

## Description of the changes 

* Remove searchable ELF map list (we only need to access two maps: executable and interpreter)
* Refactor interpreter loading code
* Convert some globals to `g_*` naming scheme

This is a byproduct of upcoming FS refactoring.

## How to test this PR? 

Existing tests should be enough.

2021-08-05 19:33 UTC, mkow submitted a review, later dismissed
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2625)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-06 07:19 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2625)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[LibOS/shim/include/shim_utils.h, line 149 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPIIwa2KBfTKCh52UB:-MgPIIwa2KBfTKCh52UC:bc70vcd) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/include/shim_utils.h#L149)):*
> ```objc
> int load_elf_interp(struct link_map* exec_map);
> noreturn void execute_elf_object(struct link_map* exec_map, void* argp, elf_auxv_t* auxp);
> void remove_loaded_libraries(void);
> ```

I very much dislike the old naming. Shouldn't this be `remove_loaded_elf_objects`? (See my other comments on `libraries` in the names.)
___
*[LibOS/shim/src/shim_init.c, line 448 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPIfN-9NB6j1TpX1ee:-MgPIfN-9NB6j1TpX1ef:b-94nl2e) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_init.c#L448)):*
> ```C
>     RUN_INIT(init_stack, argv, envp, &new_argp, &new_auxv);
> 
>     RUN_INIT(init_loader);
> ```

I would prefer to rename it to something more meaningful now. `init_exec_and_its_interp`?
___
*[LibOS/shim/src/shim_init.c, line 502 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPBAd40NaTCHpk2sj-:-MgPBAd56CoVroKm-cFU:bwi5n2v) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_init.c#L502)):*
> ```C
>     /* At this point, the exec map has been either copied from checkpoint, or initialized in
>      * `init_loader`. */
>     execute_elf_object(/*exec_map=*/NULL, new_argp, new_auxv);
> ```

Can you add a new line with `/* UNREACHABLE */`?
___
*[LibOS/shim/src/shim_rtld.c, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPC7gbEdaEBY7h3QXR:-MgPC7gbEdaEBY7h3QXS:b-x2bwsd) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L42)):*
> ```C
> /*
>  * Structure describing a loaded shared object. The `l_next' and `l_prev' members form a chain of
>  * all the shared objects loaded at startup.
> ```

Please remove the comment about `l_next/l_prev`
___
*[LibOS/shim/src/shim_rtld.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPHXv482vJTvpIWCoF:-MgPHXv482vJTvpIWCoG:b-tj461) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L106)):*
> ```C
> };
> 
> struct link_map* g_exec_map = NULL;
> ```

Why not static?
___
*[LibOS/shim/src/shim_rtld.c, line 636 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPDGExCqFY3eHu2UDG:-MgPDGExCqFY3eHu2UDH:b4y6ktd) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L636)):*
> ```C
>             filename_len = interp_name_len - i - 1;
>         }
>     }
> ```

Actually, why do we extract the filename from the full interpreter path? This is non-standard behavior, right? Is this purely a Graphene feature (to always use our `/lib/ld-linux-x86-64.so.2`)?
___
*[LibOS/shim/src/shim_rtld.c, line 661 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJ-4V2wzxrhR6Ec6c:-MgPJ-4V2wzxrhR6Ec6d:bewo70m) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L661)):*
> ```C
> }
> 
> static int __load_interp_object(struct link_map* exec_map) {
> ```

Any reason to keep `__`?
___
*[LibOS/shim/src/shim_rtld.c, line 697 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJ2LM1yWjwAIMEBQe:-MgPJ2LM1yWjwAIMEBQf:bc70vcd) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L697)):*
> ```C
> }
> 
> void remove_loaded_libraries(void) {
> ```

I very much dislike the old naming. Shouldn't this be `remove_loaded_elf_objects`? (See my other comments on `libraries` in the names.)
___
*[LibOS/shim/src/shim_rtld.c, line 768 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPFVCL1qzLFr06gqNS:-MgPFVCM6CXBbw5nENPS:b-r50snp) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L768)):*
> ```C
>         ret = load_elf_object(exec, &g_exec_map);
>         if (ret < 0) {
>             // TODO: Actually verify that the non-PIE-ness was the real cause of loading failure.
> ```

This would be cool to finally implement (as a separate PR). In general, we give the below confusing message even when the executable file doesn't exist or is a Bash/Perl script. This mightily confuses end users, who try `sgx.nonpie_binary` and still fail.

It would be better to assign proper return error codes inside `load_elf_object()` and print different messages based on these returned error codes. Not blocking, just something I remembered.
___
*[LibOS/shim/src/shim_rtld.c, line 799 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJPQE6VRZwDdfWwI7:-MgPJPQE6VRZwDdfWwI8:bo2he0o) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L799)):*
> ```C
> }
> 
> int register_library(const char* name, unsigned long load_address) {
> ```

Why don't we have a counterpart function to this one? To stop tracking loaded libraries for debugging? Is it because they are removed during checkpoint-and-restore? Or this is simply not needed during a debug session? 
___
*[LibOS/shim/src/shim_rtld.c, line 821 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPHbWv2OIyHztu6bnd:-MgPHbWv2OIyHztu6bne:b-svsnhr) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L821)):*
> ```C
>     if (exec_map) {
>         /* If a new map is provided, it means we have cleared the existing one by calling
>          * `remove_loaded_libraries`. */
> ```

Maybe add a comment that this can happen on `execve` emulation?
___
*[LibOS/shim/src/shim_rtld.c, line 895 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJjJa3TVEW_uDCFwL:-MgPJjJa3TVEW_uDCFwM:bu6weaq) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L895)):*
> ```C
> }
> 
> BEGIN_CP_FUNC(library) {
> ```

I dislike this `library` name, let's rename to `elf_object`. Or at least `link_map`. We never deal with libraries here, right? It is only ever the executable and its interpreter (if applicable).
___
*[LibOS/shim/src/shim_rtld.c, line 941 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJu_vCp9MKPw0wzzr:-MgPJu_vCp9MKPw0wzzs:babddsf) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L941)):*
> ```C
> END_RS_FUNC(library)
> 
> BEGIN_CP_FUNC(loaded_libraries) {
> ```

I dislike this `loaded_libraries` name, let's rename to `exec_and_its_interp`?


<!-- Sent from Reviewable.io -->

2021-08-06 09:28 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2625)* status: 1 of 7 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[LibOS/shim/include/shim_utils.h, line 149 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPIIwa2KBfTKCh52UB:-MgPiCcvC7afHfEi09m9:bskk5e3) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/include/shim_utils.h#L149)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I very much dislike the old naming. Shouldn't this be `remove_loaded_elf_objects`? (See my other comments on `libraries` in the names.)
</blockquote></details>

Renamed the way you suggested.
___
*[LibOS/shim/src/shim_init.c, line 448 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPIfN-9NB6j1TpX1ee:-MgPjDYJ1XwTNNp31_Aw:b-c14hfc) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_init.c#L448)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would prefer to rename it to something more meaningful now. `init_exec_and_its_interp`?
</blockquote></details>

Changed to `init_elf_objects`, to match `loaded_elf_objects` etc.

(It's true that, by design, we track only the executable and interpreter ELFs, but I think there's no reason to expose that outside of the module).
___
*[LibOS/shim/src/shim_init.c, line 502 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPBAd40NaTCHpk2sj-:-MgPWgQn-zyfA3fz_opg:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_init.c#L502)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a new line with `/* UNREACHABLE */`?
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPC7gbEdaEBY7h3QXR:-MgPWmWvEW2Fvwc40iZZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the comment about `l_next/l_prev`
</blockquote></details>

Done.
___
*[LibOS/shim/src/shim_rtld.c, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPHXv482vJTvpIWCoF:-MgPWofzAdIQRZwNtuuH:b96nlkc) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L106)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not static?
</blockquote></details>

Right, it should be.

(Initially I kept it exposed so that you can run `execute_elf_object(g_exec_map)`, but I decided `execute_elf_object(NULL)` is slightly less ugly).
___
*[LibOS/shim/src/shim_rtld.c, line 636 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPDGExCqFY3eHu2UDG:-MgPXVrzD4dQzQUOu5Hb:bcyob3u) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L636)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do we extract the filename from the full interpreter path? This is non-standard behavior, right? Is this purely a Graphene feature (to always use our `/lib/ld-linux-x86-64.so.2`)?
</blockquote></details>

Yeah... I think 64-bit executables compiled with glibc always use `/lib64/ld-linux-x86-64.so.2` (the same path with `lib64`). We seem to also support `LD_LIBRARY_PATH` as override, which is again non-standard (it shouldn't change the interpreter).

I'm tempted to just change this code to use the interpreter path directly (and remove `LD_LIBRARY_PATH` parsing). @boryspoplawski @mkow any objections?

(I don't want to do it in this PR, though: because we currently mount Graphene libs under `/lib`, this is a breaking change, requires changing all manifests, etc. I can ticket it.)
___
*[LibOS/shim/src/shim_rtld.c, line 661 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJ-4V2wzxrhR6Ec6c:-MgPad4q14AZ8bj3iQmL:bku8q6h) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L661)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Any reason to keep `__`?
</blockquote></details>

Actually I see we just rid of all `func / __func` pairs, so there is no reason to keep this naming scheme (looks like originally it was also used for static functions but I'm pretty sure we don't want that).

I removed `__` from remaining names in this file.
___
*[LibOS/shim/src/shim_rtld.c, line 697 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJ2LM1yWjwAIMEBQe:-MgPj9vTAANojSERAMDP:bskk5e3) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L697)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I very much dislike the old naming. Shouldn't this be `remove_loaded_elf_objects`? (See my other comments on `libraries` in the names.)
</blockquote></details>

Renamed the way you suggested.
___
*[LibOS/shim/src/shim_rtld.c, line 768 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPFVCL1qzLFr06gqNS:-MgPbBg7A3DyGDM6aRuK:bqyqmn4) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L768)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This would be cool to finally implement (as a separate PR). In general, we give the below confusing message even when the executable file doesn't exist or is a Bash/Perl script. This mightily confuses end users, who try `sgx.nonpie_binary` and still fail.

It would be better to assign proper return error codes inside `load_elf_object()` and print different messages based on these returned error codes. Not blocking, just something I remembered.
</blockquote></details>

Acknowledged, although I don't want to go deeper right now.
___
*[LibOS/shim/src/shim_rtld.c, line 799 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPJPQE6VRZwDdfWwI7:-MgPcTDr65SEuRLcTIC5:bdk1hua) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L799)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why don't we have a counterpart function to this one? To stop tracking loaded libraries for debugging? Is it because they are removed during checkpoint-and-restore? Or this is simply not needed during a debug session? 
</blockquote></details>

During `execve`, we unregister all libraries. But also we try to unregister a library during munmap, probably to cover the case of loading and unloading a library with `dlopen`.

(And I just realized it's probably not 100% correct because we look at `l_addr`... I added a TODO).

By the way, I know that `perf` tracks loaded libraries by tracking `mmap` and `munmap` operations (if a region is backed by a file, and is executable). Maybe we could do the same, and we wouldn't need `register_library` at all.
___
*[LibOS/shim/src/shim_rtld.c, line 821 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPHbWv2OIyHztu6bnd:-MgPhRqr3Vwgs441wK5i:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L821)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvais [...]

2021-08-06 12:26 UTC, dimakuv approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2625)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/shim_rtld.c, line 636 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPDGExCqFY3eHu2UDG:-MgQPsyx0zaxRjDIBPGL:b-tqaq6j) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L636)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah... I think 64-bit executables compiled with glibc always use `/lib64/ld-linux-x86-64.so.2` (the same path with `lib64`). We seem to also support `LD_LIBRARY_PATH` as override, which is again non-standard (it shouldn't change the interpreter).

I'm tempted to just change this code to use the interpreter path directly (and remove `LD_LIBRARY_PATH` parsing). @boryspoplawski @mkow any objections?

(I don't want to do it in this PR, though: because we currently mount Graphene libs under `/lib`, this is a breaking change, requires changing all manifests, etc. I can ticket it.)
</blockquote></details>

OK, thanks for explanations. This is also my understanding that it's just some Graphene hack (probably to stash all dependent binaries under `<graphene>/Runtime/ -> /lib/`). Definitely for another PR.


<!-- Sent from Reviewable.io -->

2021-08-06 12:30 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2625)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2021-08-06 13:26 UTC, mkow approved these changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2625)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[LibOS/shim/src/shim_rtld.c, line 636 at r1](https://reviewable.io/reviews/oscarlab/graphene/2625#-MgPDGExCqFY3eHu2UDG:-MgQcZkvAv2qp8REs4IE:bwaix3b) ([raw file](https://github.com/oscarlab/graphene/blob/f197bb2140c44a1a55b09c967ccc34a446618b16/LibOS/shim/src/shim_rtld.c#L636)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

OK, thanks for explanations. This is also my understanding that it's just some Graphene hack (probably to stash all dependent binaries under `<graphene>/Runtime/ -> /lib/`). Definitely for another PR.
</blockquote></details>

+1 to using the interp path directly. But can be done in a separate PR.


<!-- Sent from Reviewable.io -->

2021-08-06 13:27 UTC, merged