[Pal/Linux-SGX] Fix random header problems
oscarlab/graphene pull request #2631
Opened 2021-08-07 11:38 UTC by woju

## Description of the changes 

The main thing I wanted to fix is a horrible `#undef __USE_POSIX199309` hidden somewhere in headers. Then the delicate header structure collapsed. This resulted in random header adjustments all over the place.

This was split from #2466 to merge earlier.

## How to test this PR? 

Jenkins

2021-08-07 16:32 UTC, mkow requested changes
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @woju)

___
*[-- commits, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWS8m8EbLB8XJMzlyB:-MgWS8m8EbLB8XJMzlyC:b8amo5a) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/-- commits#L30)):*
Why WIP?
___
*[common/src/string/ctype.c, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWQHm_3a_zeA-WLMk3:-MgWQHmaBdtkxq-dtWLs:b-ookv9b) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/common/src/string/ctype.c#L16)):*
> ```C
> 
> int tolower(int c)
> {
> ```

please reformat both functions
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWQzbX9tyZRxv13XSp:-MgWQzbX9tyZRxv13XSq:blnyvdn) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/pal_linux.h#L14)):*
> in loader

you mean in urts?
___
*[Pal/src/host/Linux-SGX/sgx_process.h, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWRW2sCQxayRahZY4O:-MgWRW2sCQxayRahZY4P:b-k85u7) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/sgx_process.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> /* Copyright (C) 2020 Intel Corporation
> ```

we have 2021 now :)


<!-- Sent from Reviewable.io -->

2021-08-09 08:17 UTC, dimakuv requested changes
> Reviewed 13 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "WIP" found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWQzbX9tyZRxv13XSp:-Mgdz8986DXxcgrTX7DE:b-afv8o0) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/pal_linux.h#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> in loader

you mean in urts?
</blockquote></details>

+1, `linker` -> `untrusted PAL`
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgdyKaR8IVaZO22Etz2:-MgdyKaS1zAiY3xhb2tU:b-g9xzua) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/sgx_perf_data.c#L34)):*
> ```C
> #include <assert.h>
> #include <linux/perf_event.h>
> #include <stdio.h>
> ```

Why is this needed? All operations on the profiling file are done using raw syscalls and memcpy, so why this include?

I would prefer to include this header (it is almost always a source of conflicts).


<!-- Sent from Reviewable.io -->

2021-08-11 23:58 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: 8 of 15 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[-- commits, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWS8m8EbLB8XJMzlyB:-Mgrbaxi6dXtf8Nkh8O3:b7e94k0) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/-- commits#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why WIP?
</blockquote></details>

Oversight. Fixed.
___
*[common/src/string/ctype.c, line 16 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWQHm_3a_zeA-WLMk3:-Mgrbe9q8MPkQnpSmsZG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/common/src/string/ctype.c#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please reformat both functions
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/pal_linux.h, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWQzbX9tyZRxv13XSp:-MgrcGH4CRaI4TEkVpzH:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/pal_linux.h#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, `linker` -> `untrusted PAL`
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgdyKaR8IVaZO22Etz2:-MgrcJLH9ZdVX0G-xV_T:bcocegw) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/sgx_perf_data.c#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this needed? All operations on the profiling file are done using raw syscalls and memcpy, so why this include?

I would prefer to include this header (it is almost always a source of conflicts).
</blockquote></details>

This was misguided. I needed flags for `open()`. @boryspoplawski said it's better to use `<linux/*>` headers.
___
*[Pal/src/host/Linux-SGX/sgx_process.h, line 2 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgWRW2sCQxayRahZY4O:-MgrcgYI1UCaQN6c9f6B:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/sgx_process.h#L2)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

we have 2021 now :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-12 00:36 UTC, boryspoplawski requested changes
> Reviewed 8 of 15 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-Mgrj9Hz6G7UeYJ6u5q_:b4laydx) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
Please do not paste such error logs in commit messages, they are useless (we've already discussed this before).
___
*[-- commits, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrjq912LqSVHc29Smm:-Mgrjq912LqSVHc29Smn:b-sujmgd) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L30)):*
Why the 1st and 3rd commit are split? The 3rd just does random changes, may as well contain the first.
___
*[common/src/string/ctype.c, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgrkS4vDeSPAbaCpNnP:-MgrkS4vDeSPAbaCpNnQ:bf78e2w) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/common/src/string/ctype.c#L15)):*
> ```C
> 
> int tolower(int c) {
>     if (isupper(c)) return c | 32;
> ```

Please move `return` to a new line.
___
*[Pal/src/host/Linux-SGX/linux_types.h, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgrmHKV7LE7fwnXeT15:-MgrmHKV7LE7fwnXeT16:b1uddk6) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/Pal/src/host/Linux-SGX/linux_types.h#L17)):*
> ```objc
> #include "sigset.h"
> 
> typedef __kernel_off_t off_t;
> ```

Just use `typedef int64_t off_t;` and remove the include.
___
*[Pal/src/host/Linux-SGX/sgx_perf_data.c, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgdyKaR8IVaZO22Etz2:-MgrlFAp9joy0LMvGmMM:b-oob4r4) ([raw file](https://github.com/oscarlab/graphene/blob/57292ead482275d980e01a2fc29ee74a98d9e1bd/Pal/src/host/Linux-SGX/sgx_perf_data.c#L34)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This was misguided. I needed flags for `open()`. @boryspoplawski said it's better to use `<linux/*>` headers.
</blockquote></details>

It's not "better", it's the only way.


<!-- Sent from Reviewable.io -->

2021-08-12 14:09 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: 13 of 15 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-Mguarae2GoYidigw10z:barheb6) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please do not paste such error logs in commit messages, they are useless (we've already discussed this before).
</blockquote></details>

Yes, and I still don't understand why that's wrong.
___
*[-- commits, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrjq912LqSVHc29Smm:-MguaxYG2pzVcsMCnsZ6:br0bgnb) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why the 1st and 3rd commit are split? The 3rd just does random changes, may as well contain the first.
</blockquote></details>

For historical reasons, and they're orthogonal, so there's no need to actually merge them. It's good to have smaller commits, when possible for blame or bisect.
___
*[common/src/string/ctype.c, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgrkS4vDeSPAbaCpNnP:-MgubFQLEborPRo2wBDd:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/common/src/string/ctype.c#L15)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please move `return` to a new line.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/linux_types.h, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgrmHKV7LE7fwnXeT15:-Mgubu4Z65hXE13TpSFe:b-epmd6g) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/Pal/src/host/Linux-SGX/linux_types.h#L17)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Just use `typedef int64_t off_t;` and remove the include.
</blockquote></details>

Eh, this also comes from `asm/posix_types.h`, so removed header and left `__kernel_off_t` in place. Also, there's `__kernel_size_t` below. Would you like `#ifndef` around this for consistency?

The order was funny (first some `<linux/*>`, then `<asm/*>`, then the rest of `<linux/*>`, because of that funny `#undef`.


<!-- Sent from Reviewable.io -->

2021-08-12 14:38 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @mkow, and @woju)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-MgulBtOBtR57dGSTbwV:bsbeij1) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, and I still don't understand why that's wrong.
</blockquote></details>

Unnecessary bloat that's useless, especially the paths from your host.
___
*[-- commits, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrjq912LqSVHc29Smm:-MguloUU3A_CSFLyzJ0Z:b-6xcnwr) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L30)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For historical reasons, and they're orthogonal, so there's no need to actually merge them. It's good to have smaller commits, when possible for blame or bisect.
</blockquote></details>

Following this line of thought you should split the 3rd commit so that each commit fixes one issue instead of one fixing "assorted" problems.
___
*[Pal/src/host/Linux-SGX/linux_types.h, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-MgrmHKV7LE7fwnXeT15:-MgumSw10oF9xXB9qBYK:b8dgvkm) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/Pal/src/host/Linux-SGX/linux_types.h#L17)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Eh, this also comes from `asm/posix_types.h`, so removed header and left `__kernel_off_t` in place. Also, there's `__kernel_size_t` below. Would you like `#ifndef` around this for consistency?

The order was funny (first some `<linux/*>`, then `<asm/*>`, then the rest of `<linux/*>`, because of that funny `#undef`.
</blockquote></details>

I'm pretending I didn't see that `ifdef` below.


<!-- Sent from Reviewable.io -->

2021-08-20 09:36 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @woju)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-MhXr8OW-rQL05HIlJ6O:bnx6uue) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Unnecessary bloat that's useless, especially the paths from your host.
</blockquote></details>

I'd say it's not notable enough. It's a pretty common occurence in Graphene: this happens with a *lot* of different header files and definitions. And the paths are specific to this one occurence.

If you want to keep a searchable part of the message, I'd say, `redefinition or 'struct timeval'` is plenty enough. Instead of all the paths, you can explain the problem: "this is a conflict between `<sys/types.h>` and `<linux/time.h>`, we use the latter".

If you want to leave more information for the next person, then I suggest adding a section to `coding-style.rst` with some general advice about the header situation, e.g. headers that we avoid and what we do instead. Stuff like "generally, don't include `<sys/*>` headers because they conflict with `<linux/*>` headers", or "don't include `<string.h>`, our string functions are defined in `"api.h"`", or "we have our own `"stat.h"` and `"assert.h"`, use these".


<!-- Sent from Reviewable.io -->

2021-08-20 10:55 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @mkow)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-MguwsBl1rWgvqJoARDX:bsfq88w) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
Thanks for the idea. I've shortened the commit msg.

> generally, don't include <sys/*> headers because they conflict with <linux/*> headers

I don't think I'm knowledgeable enough to suggest a language for this change. And I know enough to be sure there will be some quantifier, because that doesn't hold in `Linux-SGX/tools`. And this possibly belongs to some general intro guide, `HACKING`-like, which we don't have. Not `coding-style.rst`.

> especially the paths from your host.

It's one of the benefits of meson, paths are either standard or relative, so everyone gets same paths.
___
*[-- commits, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrjq912LqSVHc29Smm:-MhYBjUk3IGekqRVbc23:bftq442) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L30)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Following this line of thought you should split the 3rd commit so that each commit fixes one issue instead of one fixing "assorted" problems.
</blockquote></details>

Be my guest.


<!-- Sent from Reviewable.io -->

2021-08-20 11:10 UTC, mkow approved these changes
> Reviewed 5 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @dimakuv)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-MhYE1n16HP134mHps3Z:b-x1mkc5) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Thanks for the idea. I've shortened the commit msg.

> generally, don't include <sys/*> headers because they conflict with <linux/*> headers

I don't think I'm knowledgeable enough to suggest a language for this change. And I know enough to be sure there will be some quantifier, because that doesn't hold in `Linux-SGX/tools`. And this possibly belongs to some general intro guide, `HACKING`-like, which we don't have. Not `coding-style.rst`.

> especially the paths from your host.

It's one of the benefits of meson, paths are either standard or relative, so everyone gets same paths.
</blockquote></details>

+1 to Borys and Paweł, commit messages should be concise and also such logs are not really helpful. The new version looks better, although I'd still trim it to just `manifested in "redefinition of ‘struct timeval’" error` or something similar.
___
*[-- commits, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrjq912LqSVHc29Smm:-MhYA8e5DtO71rWAg2Au:b5tsc28) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L30)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Be my guest.
</blockquote></details>

+1, this split doesn't really help IMO, but I'm not blocking here


<!-- Sent from Reviewable.io -->

2021-08-20 12:11 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2631#-MhYS0R68oksCNSnlpda:-MhYS0R68oksCNSnlpdb:b2g3gat) (no related file):*
`SGX=1 DEBUG=1 make` fails for me due to lack of definition of `pid_t` and `SEEK_END`. This is the configuration that we don't have on Jenkins, btw :)

I think this is what we need:

```diff
diff --git a/Pal/src/host/Linux-SGX/linux_types.h b/Pal/src/host/Linux-SGX/linux_types.h
index 45766706..9935efed 100644
--- a/Pal/src/host/Linux-SGX/linux_types.h
+++ b/Pal/src/host/Linux-SGX/linux_types.h
@@ -4,6 +4,7 @@
 #include <asm/fcntl.h>
 #include <asm/posix_types.h>
 #include <asm/stat.h>
+#include <linux/fs.h>
 #include <linux/poll.h>
 #include <linux/sched.h>
 #include <linux/socket.h>
@@ -14,6 +15,7 @@
 #include "sigset.h"
 
 typedef __kernel_off_t off_t;
+typedef __kernel_pid_t pid_t;
 
 #ifndef size_t
 typedef __kernel_size_t size_t;
```

---


<!-- Sent from Reviewable.io -->

2021-08-20 14:00 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv, @pwmarcz, and @woju)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-MhYfDOh9EvM8XuM8biq:b-db7dbe) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*

> It's one of the benefits of meson, paths are either standard or relative, so everyone gets same paths.

I have bad news for you:
```
$ file /usr/include/x86_64-linux-gnu/sys/types.h
/usr/include/x86_64-linux-gnu/sys/types.h: cannot open `/usr/include/x86_64-linux-gnu/sys/types.h' (No such file or directory)
```
(on my local system, Linux + GNU/glibc).

Why cannot you just remove the copy pasted errors as whole? You already state that
> (...) because struct timeval is defined twice

so there is no point in repeating this with:
> This problem manifested in: (...) redefinition of ‘struct timeval’
___
*[-- commits, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene/2631#-MhYjwVmCcsGrWtTGsvZ:-MhYjwVnAl6tk40M441P:b-uacujq) ([raw file](https://github.com/oscarlab/graphene/blob/2e80b2aa37965545bdff4e589c681c28d9464e92/-- commits#L26)):*
Best commit one liner. After reading it I have no idea what this will do. Why not simply use the statement you have later `Remove egregious "#undef __USE_POSIX199309" from linux_types.h`?


<!-- Sent from Reviewable.io -->

2021-08-20 18:08 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2631#-MhYS0R68oksCNSnlpda:-MhZijUg5qKTRsABE9V6:b-4opnay) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

`SGX=1 DEBUG=1 make` fails for me due to lack of definition of `pid_t` and `SEEK_END`. This is the configuration that we don't have on Jenkins, btw :)

I think this is what we need:

```diff
diff --git a/Pal/src/host/Linux-SGX/linux_types.h b/Pal/src/host/Linux-SGX/linux_types.h
index 45766706..9935efed 100644
--- a/Pal/src/host/Linux-SGX/linux_types.h
+++ b/Pal/src/host/Linux-SGX/linux_types.h
@@ -4,6 +4,7 @@
 #include <asm/fcntl.h>
 #include <asm/posix_types.h>
 #include <asm/stat.h>
+#include <linux/fs.h>
 #include <linux/poll.h>
 #include <linux/sched.h>
 #include <linux/socket.h>
@@ -14,6 +15,7 @@
 #include "sigset.h"
 
 typedef __kernel_off_t off_t;
+typedef __kernel_pid_t pid_t;
 
 #ifndef size_t
 typedef __kernel_size_t size_t;
```
</blockquote></details>

Where is that missing `SEEK_END`? Shouldn't this `#include <linux/fs.h>` be in the file that actually uses it?

---
___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-MhZhJmx5poS8RbO5yvQ:bc4adu5) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
> I have bad news for you:

BTW I use Arch. Or NixOS.
___
*[-- commits, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene/2631#-MhYjwVmCcsGrWtTGsvZ:-MhZfVGT6-OZ6063AiCQ:bj7ykvk) ([raw file](https://github.com/oscarlab/graphene/blob/2e80b2aa37965545bdff4e589c681c28d9464e92/-- commits#L26)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Best commit one liner. After reading it I have no idea what this will do. Why not simply use the statement you have later `Remove egregious "#undef __USE_POSIX199309" from linux_types.h`?
</blockquote></details>

Can't we please stop bikeshedding the commit messages and start hacking? I know it's Friday evening but for God's sake.


<!-- Sent from Reviewable.io -->

2021-08-20 19:02 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2631#-MhYS0R68oksCNSnlpda:-MhZvfLs6GZwNr-uq0qu:be7jxto) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Where is that missing `SEEK_END`? Shouldn't this `#include <linux/fs.h>` be in the file that actually uses it?
</blockquote></details>

In `sgx_profile.c`. I agree, it's better to include it in that file.

I'd say `pid_t` still belongs in `linux_types.h`, since other types are there.

---


<!-- Sent from Reviewable.io -->

2021-08-20 20:29 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: 14 of 16 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, @mkow, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2631#-MhYS0R68oksCNSnlpda:-Mh_F89l5wxcnxpOyC4D:b-2zgx8p) (no related file):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

In `sgx_profile.c`. I agree, it's better to include it in that file.

I'd say `pid_t` still belongs in `linux_types.h`, since other types are there.
</blockquote></details>

Done. Yes, that sounds right.

---


<!-- Sent from Reviewable.io -->

2021-08-20 22:04 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[-- commits, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2631#-Mgrj9Hy6Gbh643x7cyJ:-Mh__TUT0ru9IBMxP3Cn:brdo0wc) ([raw file](https://github.com/oscarlab/graphene/blob/bbfd0c55f6746c6c04ea2bb338731e1707c3313f/-- commits#L8)):*
> so everyone gets same paths.

Contradiction.
___
*[-- commits, line 26 at r4](https://reviewable.io/reviews/oscarlab/graphene/2631#-MhYjwVmCcsGrWtTGsvZ:-Mh__nVz7EgAJ1rZc6-C:blhogwx) ([raw file](https://github.com/oscarlab/graphene/blob/2e80b2aa37965545bdff4e589c681c28d9464e92/-- commits#L26)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can't we please stop bikeshedding the commit messages and start hacking? I know it's Friday evening but for God's sake.
</blockquote></details>

You wanted the split for multiple commits, so at least make the commit messages meaningful. I wanted to join them in the first place.


<!-- Sent from Reviewable.io -->

2021-08-23 22:38 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-08-24 07:15 UTC, pwmarcz approved these changes
> Reviewed 7 of 15 files at r1, 3 of 7 files at r2, 1 of 2 files at r3, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)



<!-- Sent from Reviewable.io -->

2021-08-30 06:28 UTC, dimakuv approved these changes
> Reviewed 3 of 7 files at r2, 1 of 2 files at r3, 2 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2631)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-30 06:30 UTC, merged