[Pal/Linux-SGX] Define SGX allowed/trusted/protected files as TOML arrays
oscarlab/graphene pull request #2644
Opened 2021-08-11 12:41 UTC by dimakuv

## Description of the changes 

This PR adds a new manifest syntax to define lists of SGX allowed, trusted, protected files. The previous syntax used TOML tables:

      sgx.trusted_files.file1 = "file:foo"
      sgx.trusted_files.file2 = "file:bar"

The new syntax uses TOML arrays:

      sgx.trusted_files = [ "file:foo", "file:bar" ]

The new syntax also allows to specify SHA256 hashes for a subset of trusted files (to skip hash generation during `graphene-sgx-sign`):

      [[sgx.trusted_files]]
      uri  = "file:trusted_testfile"
      hash = "c49a0aae384a14c8320f015ed5958d4402ba0726a31c4230cf772f76ff8aca2e"

The previous TOML-table syntax is still supported but deprecated. Graphene utility `graphene-sgx-sign` generates final SGX manifests using the new syntax, but `graphene-sgx` can still run old-syntax manifests.

All Graphene regression tests are updated to use the new syntax. **But all examples still use the old syntax** (to be fixed in next commits).

As a side effect, the TOML C library (`tomlc99`) is updated to the latest version -- it supports mixed TOML arrays.

## How to test this PR? 

All tests should pass. Since I updated Graphene tests to the new syntax, and left the examples with the old syntax, both syntaxes will be tested in CI and both must succeed.

2021-08-11 14:52 UTC, woju requested changes
> Reviewed 22 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 21 of 29 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 792 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpWsvp55mj7OPFyTvl:-MgpWsvtADLEcsBpLuin:bgm8m3u) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/Pal/src/host/Linux-SGX/enclave_framework.c#L792)):*
> ```C
>         }
> 
>         toml_raw_t toml_trusted_hash_raw = toml_raw_in(toml_trusted_file, "hash");
> ```

Could we name this `"sha256"` instead of "hash"? 1) Explicit is better than implicit, 2) we may want to change the algorithm in the future (cf. SHA1 in git).
___
*[python/graphenelibos/sgx_sign.py, line 206 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpY14p8uiK31XM1nBy:-MgpY14p8uiK31XM1nBz:b84s2tn) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/python/graphenelibos/sgx_sign.py#L206)):*
> ```Python
>             if hash_ is None:
>                 hash_ = get_hash(target).hex()
>             targets[idx] = uri, target, hash_
> ```

Are you sure this works? You're modifying the collection, over which you're iterating (via `enumerate(targets)` above), and while this sometimes works (eg. with lists), sometimes this breaks (notably hash-based structures, like dicts and sets). If you're not sure, I'd suggest to duplicate either collection (like `list(enumerate(...))`).


<!-- Sent from Reviewable.io -->

2021-08-11 18:42 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 21 of 29 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgqUhqr45sSByMcCB-8:-MgqUhr3ASSoH69zpYwr:b-cg3fxn) (no related file):*
Also, please fix documentation, at least `Documentation/manifest-syntax.rst` and `Pal/src/host/Linux-SGX/protected-files/README.rst`.

---


<!-- Sent from Reviewable.io -->

2021-08-12 17:52 UTC, pwmarcz requested changes
> Reviewed 27 of 29 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[-- commits, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvNnDS4VfVZwbNdVnz:-MgvNnDS4VfVZwbNdVo-:bwel4h5) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/-- commits#L28)):*
Can this be a separate commit, before the main one?
___
*[common/src/toml.patch, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvOPgi-kHc_tfR3LLp:-MgvOPgi-kHc_tfR3LLq:b-80o59p) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/common/src/toml.patch#L26)):*
> ```Diff
>  			if (!arr) return -1;
>  		}
> -		if (arr->kind != 't')
> ```

What's happening here? Does that mean tomlc99 doesn't support mixed arrays in some cases, and you're patching it by removing the "array mismatch" error?

(Probably worth explaining in the commit message at least).
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 781 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvR2Mw9eHKnfKl0_am:-MgvR2Mw9eHKnfKl0_an:bql2b7) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/Pal/src/host/Linux-SGX/enclave_framework.c#L781)):*
> ```C
>     for (ssize_t i = 0; i < toml_trusted_files_cnt; i++) {
>         /* read `sgx.trusted_file = {uri = "file:foo", hash = "deadbeef"}` entry from manifest */
>         toml_table_t* toml_trusted_file = toml_table_at(toml_trusted_files, i);
> ```

What happens if the entry is not a TOML table (e.g. `trusted_files = [ "foo", "bar" ]`), do we get a NULL here? Can you handle it?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 784 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvRNNLEMxZIjBG9BR_:-MgvRNNLEMxZIjBG9BRa:ba96pop) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/Pal/src/host/Linux-SGX/enclave_framework.c#L784)):*
> ```C
> 
>         toml_raw_t toml_trusted_uri_raw = toml_raw_in(toml_trusted_file, "uri");
>         assert(toml_trusted_uri_raw);
> ```

This can be null if there's no `uri` key, right? Is it a good idea to use asserts instead of checking the value and returning an error?

I assume you're doing this because the manifest has been produced and validated by our (Python?) tools. But if so, it would still be better to return an error instead of debug-mode `assert`...
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 518 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvSKVLAYCyCU0ft7f-:-MgvSKVLAYCyCU0ft7f0:b-lztvto) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/Pal/src/host/Linux-SGX/enclave_pf.c#L518)):*
> ```C
>         ret = register_protected_files_from_toml_array();
>         if (ret == -PAL_ERROR_NOTDEFINED) {
>             /* no allowed files were found, perfectly valid case */
> ```

Using an error code (`-PAL_ERROR_NOTDEFINED`) as a valid case looks a bit awkward. How about making these functions return the number of files parsed? Then you can call the other one if the number is 0.
___
*[python/graphenelibos/sgx_sign.py, line 167 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvSg402twWS5ImxvZT:-MgvSg402twWS5ImxvZU:bg4ue0o) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/python/graphenelibos/sgx_sign.py#L167)):*
> ```Python
> 
> def append_trusted_dir_or_file(targets, val, check_exist):
>     try:
> ```

This looks convoluted, the `except:` branch does no check that `val` is actually a string. I think it's much better to check the type directly:

```python
if isinstance(val, dict):
    uri = val['uri']
    hash = val['hash']
elif isinstance(val, str):
    uri = val
    hash = None
else:
    raise ValueError(f'unknown trusted file format: {val!r}')
```


<!-- Sent from Reviewable.io -->

2021-08-12 17:57 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv and @woju)

___
*[python/graphenelibos/sgx_sign.py, line 206 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpY14p8uiK31XM1nBy:-MgvUb9L9bnkEFFfnb8D:bxv6szq) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/python/graphenelibos/sgx_sign.py#L206)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Are you sure this works? You're modifying the collection, over which you're iterating (via `enumerate(targets)` above), and while this sometimes works (eg. with lists), sometimes this breaks (notably hash-based structures, like dicts and sets). If you're not sure, I'd suggest to duplicate either collection (like `list(enumerate(...))`).
</blockquote></details>

If you want to modify it in place, you can use the index (also, modify only if it needs changing):

```python
for i in range(len(targets)):
     uri, target, hash_ = targets[i]
    if hash_ is None:
        hash_ = get_hash(target).hex()
        targets[i] = uri, target, hash_
```

If you don't mind copying the array, this looks more straightforward:

```python
hashed_targets = []
for (uri, target, hash_) in targets:
    if hash_ is None:
        hash_ = get_hash(target).hex()
    hashed_targets.append((uri, target, hash_))
```


<!-- Sent from Reviewable.io -->

2021-08-30 14:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 23 of 31 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @pwmarcz and @woju)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgqUhqr45sSByMcCB-8:-MiMMRjd8EjjfDwqLniR:b-896fix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Also, please fix documentation, at least `Documentation/manifest-syntax.rst` and `Pal/src/host/Linux-SGX/protected-files/README.rst`.
</blockquote></details>

Done.

---
___
*[-- commits, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvNnDS4VfVZwbNdVnz):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Can this be a separate commit, before the main one?
</blockquote></details>

Done
___
*[common/src/toml.patch, line 26 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvOPgi-kHc_tfR3LLp:-MiLzZSS4__qTuo2qZ3o:b-kb5xtc) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/common/src/toml.patch#L26)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What's happening here? Does that mean tomlc99 doesn't support mixed arrays in some cases, and you're patching it by removing the "array mismatch" error?

(Probably worth explaining in the commit message at least).
</blockquote></details>

Done. I removed this hack. This was a leftover from my hacking, thanks for noticing.
___
*[common/src/toml.patch, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiMMcLA8RV1Wu5tSNPN:-MiMMcLA8RV1Wu5tSNPO:bk6byzk) ([raw file](https://github.com/oscarlab/graphene/blob/d4eb01e781a7bc078edb20d3d3df1f18836f0e20/common/src/toml.patch#L91)):*
> ```Diff
>  	*ret = strtoll(buf, &endp, base);
> -	return (errno || *endp) ? -1 : 0;
> +    return (*endp) ? -1 : 0;
> ```

Meh... Could we ignore this blooper? I don't want to recreate the patch file.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 792 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpWsvp55mj7OPFyTvl:-MiMASXKB_UkW1ND-NDm:b-dgxz11) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/Pal/src/host/Linux-SGX/enclave_framework.c#L792)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Could we name this `"sha256"` instead of "hash"? 1) Explicit is better than implicit, 2) we may want to change the algorithm in the future (cf. SHA1 in git).
</blockquote></details>

Done.

Note that I only changed it in this new TOML syntax and in this function: the old TOML syntax uses `sgx.trusted_checksum` (and is kept for legacy reasons) and the other C functions use `hash` words (because it is not important how we name it locally in our C code and because it would require a lot of unrelated changes).
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 781 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvR2Mw9eHKnfKl0_am:-MiM1H1P9tcC9KtC_XEy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/Pal/src/host/Linux-SGX/enclave_framework.c#L781)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

What happens if the entry is not a TOML table (e.g. `trusted_files = [ "foo", "bar" ]`), do we get a NULL here? Can you handle it?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 784 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvRNNLEMxZIjBG9BR_:-MiM1IBM7oNi-2YXtyrJ:bk36ero) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/Pal/src/host/Linux-SGX/enclave_framework.c#L784)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This can be null if there's no `uri` key, right? Is it a good idea to use asserts instead of checking the value and returning an error?

I assume you're doing this because the manifest has been produced and validated by our (Python?) tools. But if so, it would still be better to return an error instead of debug-mode `assert`...
</blockquote></details>

Done.

No, I did this because I was in vacation mode already that day...
___
*[Pal/src/host/Linux-SGX/enclave_pf.c, line 518 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvSKVLAYCyCU0ft7f-:-MiM8xE89nLpJccHLMU0:b6vtfne) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/Pal/src/host/Linux-SGX/enclave_pf.c#L518)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Using an error code (`-PAL_ERROR_NOTDEFINED`) as a valid case looks a bit awkward. How about making these functions return the number of files parsed? Then you can call the other one if the number is 0.
</blockquote></details>

Done.

Actually did some more refactoring to make allowed / trusted / protected files logic similar and added more error checking.
___
*[python/graphenelibos/sgx_sign.py, line 206 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpY14p8uiK31XM1nBy:-MiMCw-50lUu9ql6toF-:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/python/graphenelibos/sgx_sign.py#L206)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If you want to modify it in place, you can use the index (also, modify only if it needs changing):

```python
for i in range(len(targets)):
     uri, target, hash_ = targets[i]
    if hash_ is None:
        hash_ = get_hash(target).hex()
        targets[i] = uri, target, hash_
```

If you don't mind copying the array, this looks more straightforward:

```python
hashed_targets = []
for (uri, target, hash_) in targets:
    if hash_ is None:
        hash_ = get_hash(target).hex()
    hashed_targets.append((uri, target, hash_))
```
</blockquote></details>

Done.
___
*[python/graphenelibos/sgx_sign.py, line 167 at r2](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgvSg402twWS5ImxvZT:-MiMBDf33vfmlhnaGBAJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/12f7b3d5e8ee057c725b7c4e5df388ace2374c0d/python/graphenelibos/sgx_sign.py#L167)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This looks convoluted, the `except:` branch does no check that `val` is actually a string. I think it's much better to check the type directly:

```python
if isinstance(val, dict):
    uri = val['uri']
    hash = val['hash']
elif isinstance(val, str):
    uri = val
    hash = None
else:
    raise ValueError(f'unknown trusted file format: {val!r}')
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-30 14:17 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 23 of 31 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)

___
*[python/graphenelibos/sgx_sign.py, line 206 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpY14p8uiK31XM1nBy:-MiMPyDiDkQSWMao2g6d:b-yln9k0) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/python/graphenelibos/sgx_sign.py#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done. Used the approach with duplication (new collection). The first approach made Pylint unhappy:
```
C:204, 8: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
```


<!-- Sent from Reviewable.io -->

2021-08-30 15:27 UTC, woju reviewed
> Reviewed 4 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 28 of 31 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgqUhqr45sSByMcCB-8:-MiMehZ66JkLcE5Mo5Ko:b-ucfkn4) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks.

---
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 792 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpWsvp55mj7OPFyTvl:-MiMectQ49B7wG0vWi-p:b-eignk6) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/Pal/src/host/Linux-SGX/enclave_framework.c#L792)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.

Note that I only changed it in this new TOML syntax and in this function: the old TOML syntax uses `sgx.trusted_checksum` (and is kept for legacy reasons) and the other C functions use `hash` words (because it is not important how we name it locally in our C code and because it would require a lot of unrelated changes).
</blockquote></details>

Yes, certainly. Thanks.
___
*[python/graphenelibos/sgx_sign.py, line 206 at r1](https://reviewable.io/reviews/oscarlab/graphene/2644#-MgpY14p8uiK31XM1nBy:-MgvfYgtBMi24Xw1lxj7:bakbg9l) ([raw file](https://github.com/oscarlab/graphene/blob/00a2b6bb6c4c345fec591bab7d3ca9a403890366/python/graphenelibos/sgx_sign.py#L206)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Used the approach with duplication (new collection). The first approach made Pylint unhappy:
```
C:204, 8: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
```
</blockquote></details>

Seems bogus, if you'd like, add to ignored in `.pylintrc`. Resolving here.


<!-- Sent from Reviewable.io -->

2021-08-30 20:48 UTC, mkow requested changes
> Reviewed 21 of 29 files at r1, 2 of 2 files at r2, 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 30 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[common/src/toml.patch, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiMMcLA8RV1Wu5tSNPN:-MiNniy11bO3KPqQ6Po_:brf7jod) ([raw file](https://github.com/oscarlab/graphene/blob/d4eb01e781a7bc078edb20d3d3df1f18836f0e20/common/src/toml.patch#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Meh... Could we ignore this blooper? I don't want to recreate the patch file.
</blockquote></details>

Can't you edit this line manually in the .patch file? ;)
___
*[Documentation/manifest-syntax.rst, line 457 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVwRL-1lwRkASsbI_:-MiNVwRL-1lwRkASsbIa:b-gp46at) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L457)):*
> ```reStructuredText
> ::
> 
>     sgx.allowed_files = [ "[URI]", "[URI]" ]
> ```

I'd use a nicer formatting here, as people will most likely just copy paste it, plus they'll have many more files. E.g.:

```TOML
sgx.allowed_files = [
  "[URI]",
  "[URI]",
]
```
___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiNVfS_CAxsZR82sox2:b-db55d6) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
> ```reStructuredText
>     sgx.allowed_files = [ "[URI]", "[URI]" ]
>     # Or, deprecated TOML-table syntax:
>     # sgx.allowed_files.[identifier] = "[URI]"
> ```

I wouldn't list the old syntax at all and just purge it from any documentation + warn if used. And then stop supporting it at some point.
___
*[Documentation/manifest-syntax.rst, line 476 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWD7j69-BzTdRerx4:-MiNWD7j69-BzTdRerx5:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L476)):*
> ```reStructuredText
> ::
> 
>     sgx.trusted_files = [ "[URI]", "[URI]" ]  # entries can be strings
> ```

ditto
___
*[Documentation/manifest-syntax.rst, line 478 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWH-2BirBp1QQtXYW:-MiNWH-31IFLwFr2-WtO:b-12k6rl) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L478)):*
> ```reStructuredText
>     sgx.trusted_files = [ "[URI]", "[URI]" ]  # entries can be strings
> 
>     [[sgx.trusted_files]]                     # entries can be tables
> ```

`entries can be tables` -> `entries can also be tables`
___
*[Documentation/manifest-syntax.rst, line 491 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWPUTAcLbXB4htsQ0:-MiNWPUTAcLbXB4htsQ1:bas8cv4) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L491)):*
> ```reStructuredText
> automatically generate hashes of these files and add them to the SGX-specific
> manifest (``.manifest.sgx``). The manifest writer may also specify the hash for
> a file using the TOML-table syntax, in the field ``sha256``.
> ```

Please mention explicitly that hashing this file will be skipped by `graphene-sgx-sign` tool and this value will be used instead.
___
*[Documentation/manifest-syntax.rst, line 504 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWcbE2XMlssnppwJx:-MiNWcbE2XMlssnppwJy:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L504)):*
> ```reStructuredText
>     sgx.protected_files_key = "[16-byte hex value]"
> 
>     sgx.protected_files = [ "[URI]", "[URI]" ]
> ```

ditto
___
*[Documentation/manifest-syntax.rst, line 506 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWdBS4Bc7zkJg3Buu:-MiNWdBS4Bc7zkJg3Buv:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L506)):*
> ```reStructuredText
>     sgx.protected_files = [ "[URI]", "[URI]" ]
>     # Or, deprecated TOML-table syntax:
>     # sgx.protected_files.[identifier] = "[URI]"
> ```

ditto
___
*[LibOS/shim/test/fs/manifest.template, line 46 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNX1U3De1AhxCw7hkj:-MiNX1U3De1AhxCw7hkk:bdqsb27) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/LibOS/shim/test/fs/manifest.template#L46)):*
> ```
> sgx.protected_files = [
>   "file:tmp/pf_input",
>   "file:tmp/pf_output"
> ```

I prefer putting the comma after the last element if it's listed one-per-line. The diff is then nicer if you add/reshuffle the lines, and you can also move them easier when experimenting with code (no need to fix the missing comma).
ditto for all other places
___
*[LibOS/shim/test/regression/rename.manifest.template, line 22 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNZ_Gu3Oo0Q-a1ERT_:-MiNZ_Gu3Oo0Q-a1ERTa:b-i252fe) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/LibOS/shim/test/regression/rename.manifest.template#L22)):*
> ```
> ]
> 
> sgx.allowed_files = [ "file:tmp/" ]
> ```

In other manifests you listed allowed files first, could you do the same here?
___
*[Pal/regression/manifest.template, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNZg7X1bvzol--6kRe:-MiNZg7X1bvzol--6kRf:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/regression/manifest.template#L17)):*
> ```
> ]
> 
> sgx.allowed_files = [
> ```

ditto
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 560 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNa7Tf4jt6IcNgH33t:-MiNa7Tg3e77u17q30Na:b-hqzcs7) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L560)):*
> ```C
>     int ret;
> 
>     if (checksum_str && strlen(checksum_str) < sizeof(sgx_file_hash_t) * 2) {
> ```

not `!=`?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 752 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNfBD4A753rojUv9n5:-MiNfBD4A753rojUv9n6:b-doo955) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L752)):*
> ```C
>               "= [\"file1\", ..]'.");
> 
>     ret = (int)toml_trusted_files_cnt;
> ```

could we return this via argument? also, is it really used?
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 777 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNgpqJBaFGXl28EH-e:-MiNgpqJBaFGXl28EH-f:bm0wn7g) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L777)):*
> ```C
>         return 0;
> 
>     char* toml_trusted_uri_str  = NULL;
> ```

double space
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 824 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNiJHPDUkpcPn_Vbfc:-MiNiJHPDUkpcPn_Vbfd:bow0zw0) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L824)):*
> ```C
>         free(toml_trusted_uri_str);
>         free(toml_trusted_sha256_str);
>         toml_trusted_uri_str  = NULL;
> ```

doublespace
___
*[Pal/src/host/Linux-SGX/enc [...]

2021-08-31 08:13 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 3 of 35 files reviewed, 30 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow, @pwmarcz, and @woju)

___
*[common/src/toml.patch, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiMMcLA8RV1Wu5tSNPN:-MiPyGYt8ledq_TM0CUC:b-rcysse) ([raw file](https://github.com/oscarlab/graphene/blob/d4eb01e781a7bc078edb20d3d3df1f18836f0e20/common/src/toml.patch#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Can't you edit this line manually in the .patch file? ;)
</blockquote></details>

Done. Technically, the hash should have changed but who cares.
___
*[Documentation/manifest-syntax.rst, line 457 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVwRL-1lwRkASsbI_:-MiPydPiAv9O43n92Cyr:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L457)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd use a nicer formatting here, as people will most likely just copy paste it, plus they'll have many more files. E.g.:

```TOML
sgx.allowed_files = [
  "[URI]",
  "[URI]",
]
```
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiPydp18tKreAUqdTVs:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I wouldn't list the old syntax at all and just purge it from any documentation + warn if used. And then stop supporting it at some point.
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 476 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWD7j69-BzTdRerx4:-MiQ-E7kEEQxyl-F2gOG:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L476)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 478 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWH-2BirBp1QQtXYW:-MiQ-EXi6vi96IUN3g9G:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L478)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`entries can be tables` -> `entries can also be tables`
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 491 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWPUTAcLbXB4htsQ0:-MiQ-Uaw0eofs_RK38-O:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L491)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please mention explicitly that hashing this file will be skipped by `graphene-sgx-sign` tool and this value will be used instead.
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 504 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWcbE2XMlssnppwJx:-MiQ-a0x1QUkhP3K7Cut:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L504)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Documentation/manifest-syntax.rst, line 506 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNWdBS4Bc7zkJg3Buu:-MiQ-aKC5zDm-GrQrTO5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L506)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[LibOS/shim/test/fs/manifest.template, line 46 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNX1U3De1AhxCw7hkj:-MiQ-osy94VUHHVRmswy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/LibOS/shim/test/fs/manifest.template#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I prefer putting the comma after the last element if it's listed one-per-line. The diff is then nicer if you add/reshuffle the lines, and you can also move them easier when experimenting with code (no need to fix the missing comma).
ditto for all other places
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/rename.manifest.template, line 22 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNZ_Gu3Oo0Q-a1ERT_:-MiQ0dhVAeHklEfU30Ny:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/LibOS/shim/test/regression/rename.manifest.template#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

In other manifests you listed allowed files first, could you do the same here?
</blockquote></details>

Done.
___
*[Pal/regression/manifest.template, line 17 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNZg7X1bvzol--6kRe:-MiQ0ej54s_SNRsuWmQt:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/regression/manifest.template#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 560 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNa7Tf4jt6IcNgH33t:-MiQ1N8s6uKPYCJZKcdm:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L560)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not `!=`?
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 752 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNfBD4A753rojUv9n5:-MiQ2aA0444dCiF6W4N1:bvnddf6) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L752)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

could we return this via argument? also, is it really used?
</blockquote></details>

Done. Actually, there is no sense to use either TOML-table syntax or TOML-array syntax. I now use both, and thus the return value is irrelevant.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 777 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNgpqJBaFGXl28EH-e:-MiQ2pIY3E6bCWFulYtL:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L777)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/enclave_framework.c, line 824 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNiJHPDUkpcPn_Vbfc:-MiQ2wfwA3wKk0nOBZLA:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Pal/src/host/Linux-SGX/enclave_framework.c#L824)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

doublespace
</blockquote></details>

Done.
___
*[Pal/src/ho [...]

2021-08-31 09:33 UTC, mkow approved these changes
> Reviewed 32 of 32 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/src/toml.patch, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiMMcLA8RV1Wu5tSNPN:-MiQV9fk1BrVTPI-rLT-:b3o30rf) ([raw file](https://github.com/oscarlab/graphene/blob/d4eb01e781a7bc078edb20d3d3df1f18836f0e20/common/src/toml.patch#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Technically, the hash should have changed but who cares.
</blockquote></details>

Oh, true :) Whatever.


<!-- Sent from Reviewable.io -->

2021-08-31 11:22 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiQw0c_0BacOcv5yW_c:b-obrjwq) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I disagree, we shoudn't just remove the documentation of any supported schema. If you don't want it here, please add "Deprecated schema" (or sth like that) section somewhere near the end.


<!-- Sent from Reviewable.io -->

2021-08-31 11:31 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz and @woju)

___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiQyFZX9ay5yjMmKAjB:bybc33m) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I disagree, we shoudn't just remove the documentation of any supported schema. If you don't want it here, please add "Deprecated schema" (or sth like that) section somewhere near the end.
</blockquote></details>

What's the point of keeping it? It only makes the docs longer and I don't see any case where someone should actually read about it.
It will cease to be supported soon.


<!-- Sent from Reviewable.io -->

2021-08-31 12:17 UTC, pwmarcz approved these changes
> Reviewed 1 of 8 files at r3, 32 of 32 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[common/src/toml.patch, line 91 at r3](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiMMcLA8RV1Wu5tSNPN:-MiN91qO-CCWw4U0pHht:bcuikc0) ([raw file](https://github.com/oscarlab/graphene/blob/d4eb01e781a7bc078edb20d3d3df1f18836f0e20/common/src/toml.patch#L91)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Oh, true :) Whatever.
</blockquote></details>

+1 for not caring too much about the hashes, editing the patches manually is too convenient (Emacs even adjusts the line numbers and counts if necessary :) ).
___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiR52XS22vRNLNt6Brc:b-khwp1g) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of keeping it? It only makes the docs longer and I don't see any case where someone should actually read about it.
It will cease to be supported soon.
</blockquote></details>

Release notes?


<!-- Sent from Reviewable.io -->

2021-08-31 13:00 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiRHMuZ3wpLCM3jWJ45:balhmtn) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Release notes?
</blockquote></details>

@pwmarcz: You mean adding this only to release notes? This is something which will definitely go there, I think this part is out of question :) (we always have "breaking changes" section)


<!-- Sent from Reviewable.io -->

2021-08-31 13:56 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiRRS5I4-VOSgFFPXH5:b8v5dmq) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@pwmarcz: You mean adding this only to release notes? This is something which will definitely go there, I think this part is out of question :) (we always have "breaking changes" section)
</blockquote></details>

This is orthogonal. Yes, this obviously should be mentioned in release notes, but I think as long we support this, we should have this documented. We can remove this when we'll stop supporting it.


<!-- Sent from Reviewable.io -->

2021-08-31 13:58 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiRV3YTA2_LS1DKwq9U:b-qj7hdt) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is orthogonal. Yes, this obviously should be mentioned in release notes, but I think as long we support this, we should have this documented. We can remove this when we'll stop supporting it.
</blockquote></details>

IMO it's just taking space in the docs and no one should ever need to use it anymore. So, I vote for removing it.


<!-- Sent from Reviewable.io -->

2021-08-31 16:02 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 34 of 35 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @woju)

___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiRwYNj7EQ3oeyuL0-3:b-et8wlb) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

IMO it's just taking space in the docs and no one should ever need to use it anymore. So, I vote for removing it.
</blockquote></details>

Done. Added the `Deprecated syntax` section.


<!-- Sent from Reviewable.io -->

2021-08-31 16:09 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 34 of 35 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, @pwmarcz, and @woju)

___
*[Documentation/manifest-syntax.rst, line 459 at r4](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiNVfSZ7Ne0Gso6Cmf7:-MiRwxcGAYNAph712YWK:b-jy2fsg) ([raw file](https://github.com/oscarlab/graphene/blob/6dc8090271c920742c63494db3c5c5a80074c4fd/Documentation/manifest-syntax.rst#L459)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. Added the `Deprecated syntax` section.
</blockquote></details>

For the record: we did a small vote on this and an additional section won.
___
*[Documentation/manifest-syntax.rst, line 717 at r6](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiRy5cx6mAFypvgeJ-u:-MiRy5cx6mAFypvgeJ-v:bhvelh2) ([raw file](https://github.com/oscarlab/graphene/blob/f05ab35c1101477e1fe5512ae82291734df25e7e/Documentation/manifest-syntax.rst#L717)):*
> ```reStructuredText
> listed below, with short descriptions.
> 
> Executable (removed)
> ```

What's the point of including all of these? They don't work anymore and no one is using them.


<!-- Sent from Reviewable.io -->

2021-08-31 16:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 34 of 35 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @woju)

___
*[Documentation/manifest-syntax.rst, line 717 at r6](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiRy5cx6mAFypvgeJ-u:-MiS-amI8AIFtJgkBvMw:b4fahnn) ([raw file](https://github.com/oscarlab/graphene/blob/f05ab35c1101477e1fe5512ae82291734df25e7e/Documentation/manifest-syntax.rst#L717)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the point of including all of these? They don't work anymore and no one is using them.
</blockquote></details>

Before I fixup: do you want me to remove all the `(removed)` manifest options?

What about `Program Break Size (renamed)`? Remove or keep?


<!-- Sent from Reviewable.io -->

2021-08-31 16:26 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 34 of 35 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow, @pwmarcz, and @woju)

___
*[Documentation/manifest-syntax.rst, line 717 at r6](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiRy5cx6mAFypvgeJ-u:-MiS0uGq7pey8fc4u1XJ:b-df5ofp) ([raw file](https://github.com/oscarlab/graphene/blob/f05ab35c1101477e1fe5512ae82291734df25e7e/Documentation/manifest-syntax.rst#L717)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Before I fixup: do you want me to remove all the `(removed)` manifest options?

What about `Program Break Size (renamed)`? Remove or keep?
</blockquote></details>

I vote for removing everything which doesn't currently work (and I think that was @woju's original proposal, to document only things that still work).


<!-- Sent from Reviewable.io -->

2021-08-31 16:29 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 34 of 35 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 698 at r6](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiS1msk1PfOoWHae57T:-MiS1msl2REZFY1yif0y:b-938pd1) ([raw file](https://github.com/oscarlab/graphene/blob/f05ab35c1101477e1fe5512ae82291734df25e7e/Documentation/manifest-syntax.rst#L698)):*
> ```reStructuredText
> 
> 
> Deprecated syntax
> ```

This is "schema", not syntax. Syntax is TOML, we define schema inside.
___
*[Documentation/manifest-syntax.rst, line 717 at r6](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiRy5cx6mAFypvgeJ-u:-MiS1XTZ1fp84P_9dyvg:b-r4n7h8) ([raw file](https://github.com/oscarlab/graphene/blob/f05ab35c1101477e1fe5512ae82291734df25e7e/Documentation/manifest-syntax.rst#L717)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I vote for removing everything which doesn't currently work (and I think that was @woju's original proposal, to document only things that still work).
</blockquote></details>

Right, we shouldn't document things that don't actually work. That's really for release notes and git log only.


<!-- Sent from Reviewable.io -->

2021-08-31 16:45 UTC, mkow reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 34 of 35 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 702 at r7](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiS59FF6-VxsRKJQgx7:-MiS59FF6-VxsRKJQgx8:b-mcclgu) ([raw file](https://github.com/oscarlab/graphene/blob/ea71d4f4d168377c302b5f6eca91e5978cb5d5a6/Documentation/manifest-syntax.rst#L702)):*
> ```reStructuredText
> 
> Before October 2020, manifests were not written in the TOML syntax but instead
> in an ad-hoc INI file-like syntax. Some of the differences include:
> ```

What about this section? It also lists things which are long-gone, I see no point in documenting them.


<!-- Sent from Reviewable.io -->

2021-08-31 17:14 UTC, pwmarcz reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: 34 of 35 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @pwmarcz)

___
*[Documentation/manifest-syntax.rst, line 717 at r6](https://reviewable.io/reviews/oscarlab/graphene/2644#-MiRy5cx6mAFypvgeJ-u:-MiSArLb3872HdFEdC_R:bm7ycao) ([raw file](https://github.com/oscarlab/graphene/blob/f05ab35c1101477e1fe5512ae82291734df25e7e/Documentation/manifest-syntax.rst#L717)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Right, we shouldn't document things that don't actually work. That's really for release notes and git log only.
</blockquote></details>

+1, let's just document what works (even if it's about to be removed soon).


<!-- Sent from Reviewable.io -->

2021-08-31 18:35 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-08-31 18:37 UTC, woju submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-08-31 20:52 UTC, mkow approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-01 09:59 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2644)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-01 10:57 UTC, dimakuv commented
Jenkins, retest Jenkins-Debug-20.04 please (`test_libos.TC_50_GDB.test_000_gdb_backtrace` failed with `AssertionError: timeout (10 s) expired`)

2021-09-01 11:16 UTC, merged