[LibOS] Introduce inodes, rewrite `chroot` filesystem
oscarlab/graphene pull request #2646
Opened 2021-08-12 15:12 UTC by pwmarcz

## Description of the changes 

This change begins the migration to inodes: file data will be kept in a separate structure (inode) instead of dentry. In this step, inodes are still optional, and only the `chroot` filesystem is rewritten to use them.

The main use case for inodes is proper handling of `rename` and `unlink` operations. The new `chroot` filesystem should do that much better than the old one. I also added a regression test (`rename_unlink`) with that checks various cases.

## Why?

I finally decided to do that because it turns out the `chroot` filesystem *does* contain partial support for unlinking open files (you can open a file, then `unlink` it, and it will still work). It was based on a pretty bad hack (a handle contains a copy of file metadata, along with "version" attribute), and I'm not sure if it could even handle all corner cases.

I did not want to lose that partial support, and I did not want the rewritten version to include any such hacks (I would have to also replace it in `tmpfs`, and so on). Also, since a pure "dentry-based" architecture starts to really show its limitations, I don't want to base more changes on it.

I removed the experimental file position sync; I want to finish this refactoring before returning to work on sync engine.

Note that this also removes some uses of legacy structures (`atomic_int`, `shim_qstr`), though not all of them.

## Next steps

First, I plan to gradually rewrite other filesystems (starting with `tmpfs`) to use inodes. Then, I can remove the redundant fields from dentry, switching to inode completely.

I expect that the end result will make both objects (dentry and inode) much simpler than the existing dentry. The dentry will not contain any "custom" data (and probably can have much simpler locking rules), while the inode will not contain any links to children and parents.

## How to test this PR? 

This is about the `chroot` filesystem, so I expect it to be reasonably covered by existing tests (regression and LTP). I also added the `rename_unlink` regression test.

2021-09-03 11:24 UTC, dimakuv requested changes
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifOoJF26NnpNHHMzfe:-MifOoJF26NnpNHHMzff:b-3ou7kh) (no related file):*
Maybe any LTP tests (rename ones) can be enabled now?

---
___
*[-- commits, line 12 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MieqJ4U3AB21YwDVTSM):*
`with that checks various cases` -- broken English?
___
*[LibOS/shim/include/shim_fs.h, line 699 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MierQj406fFZL6ermNt:-MierQj406fFZL6ermNu:b-icmtny) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L699)):*
> ```objc
> 
> /*!
>  * \brief Allocaate and initialize a new inode
> ```

Typo: `Allocate`
___
*[LibOS/shim/include/shim_handle.h, line 205 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Miet6VO1LuO2T7Urtkq:-Miet6VO1LuO2T7Urtkr:b-ckhxbv) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_handle.h#L205)):*
> ```objc
>     /* Inode associated with this handle. Currently optional, and only for the use of underlying
>      * filesystem (see `shim_inode` in `shim_fs.h`). Eventually, should replace `dentry` fields. */
>     struct shim_inode* inode;
> ```

It cannot change during the lifetime of the `shim_handle` object, right? In other words, we don't need to protect it with the `lock`? Can you add this comment then?
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 142 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiewB7JAtQQ9cq7uWIx:-MiewB7JAtQQ9cq7uWIy:b-isvyx6) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/shim_fs_pseudo.c#L142)):*
> ```C
>         }
>     }
>     hdl->flags = flags & ~O_ACCMODE;
> ```

Why was it needed before?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 31 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif3EC4CZ920KdmSgqA:-Mif3EC4CZ920KdmSgqB:b6z48pv) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L31)):*
> ```C
> #include "stat.h"
> 
> struct chroot_mount_data {
> ```

Why is it so complicated? Why do we have `void* shim_mount::data`, and then for different FS types we have different mount-data types? Isn't `chroot_mount_data::root` field generic for all mounts? Same for `chroot_mount_data::default_type`... Couldn't we just move these fields into `shim_mount` struct?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif0ZT8DF8wEVhiHCSg:-Mif0ZT8DF8wEVhiHCSh:bsi5ay0) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L38)):*
> ```C
>     mode_t default_type;
> 
>     /* Root of the filesystem on host (URI without the scheme) */
> ```

I don't get this comment. What does `URI without the scheme` mean? If for example the file is under `/home/dimakuv/foo.c`, and the FS is mounted with `fs.mount.bla.uri = "file:/home/"`, then `root = "/home"`?

Why is this needed? UPDATE: Ok, it is needed to generate the absolute host URI for a dentry (hmm, not really absolute URI?).
___
*[LibOS/shim/src/fs/chroot/fs.c, line 112 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif2FI04SUJLFbR51Ae:-Mif2FI1-Y2Ztj50qsFV:b-jkocz4) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L112)):*
> ```C
>         return ret;
> 
>     struct chroot_mount_data* mdata = dent->mount->data;
> ```

How do we know that at this point, dentry has `mount->data`? You mention that this function can be called on a newly-created dentry, so some fields may not be yet initialized. At least put an assert here.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 173 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif4cq31zHxc5s9G65X:-Mif4cq31zHxc5s9G65Y:b-od6ll2) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L173)):*
> ```C
>      * is a directory or a device, `DkStreamAttributesQuery` will still recognize it. However, PAL
>      * also recognizes a special "dev:tty" device, which doesn't work that way (i.e. "file:tty" will
>      * not open it).
> ```

This sounds like a bug/quirk of the PAL implementation. Maybe add a FIXME? Or does this behavior sound legit to you?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 176 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif5_9_-rZMQBJDM61v:-Mif5_9_-rZMQBJDM61w:b-x8javb) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L176)):*
> ```C
>      */
>     char* uri = NULL;
>     ret = chroot_dentry_uri(dent, mdata->default_type, &uri);
> ```

Aren't you supposed to free `uri` in the benign/error paths below?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 222 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif6N2d3vIMgxIGtzYU:-Mif6N2d3vIMgxIGtzYV:b-vrumqv) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L222)):*
> ```C
> 
> /* Open a temporary read-only PAL handle for a file (used by `unlink` etc.) */
> static int chroot_temp_open(struct shim_dentry* dent, mode_t type, PAL_HANDLE* palhdl) {
> ```

`palhdl` -> `out_palhdl`
___
*[LibOS/shim/src/fs/chroot/fs.c, line 224 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif5dtS8TmhnzJ8ThIO:-Mif5dtS8TmhnzJ8ThIP:b-x8javb) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L224)):*
> ```C
> static int chroot_temp_open(struct shim_dentry* dent, mode_t type, PAL_HANDLE* palhdl) {
>     char* uri;
>     int ret = chroot_dentry_uri(dent, type, &uri);
> ```

Aren't you supposed to free `uri` in the benign/error paths below?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 238 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif6PoDCtW9zeAeBfB8:-Mif6PoDCtW9zeAeBfB9:bcv7dvk) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L238)):*
> ```C
> /* Open a PAL handle, and associate it with a LibOS handle (if provided). */
> static int chroot_do_open(struct shim_handle* hdl, struct shim_dentry* dent, mode_t type,
>                           int flags, mode_t mode) {
> ```

`hdl` -> `out_hdl` and move to be the last arg
___
*[LibOS/shim/src/fs/chroot/fs.c, line 472 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifKmVc-zGFr-Flvfv7:-MifKmVc-zGFr-Flvfv8:b-dez3vt) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L472)):*
> ```C
>     }
>     if (actual_count > count)
>         BUG();
> ```

Why not assert as you did in the `chroot_read` case?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 533 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifLUVe3Vbim-1vpheI:-MifLUVfALZORslruk7d:b-10zq1n) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L533)):*
> ```C
>     int ret;
> 
>     lock(&hdl->lock);
> ```

There seems to be no reason to lock the handle. Both `inode` and `pal_handle` are immutable, IIUC.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 612 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifM3lTEUXebm72wdN6:-MifM3lU7eMI-Q [...]

2021-09-03 15:41 UTC, boryspoplawski requested changes
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646)* status: all files reviewed, 63 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 186 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiblloA9TCCdcrdb7Bo:-MiblloA9TCCdcrdb7Bp:b-pi5exb) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L186)):*
> ```objc
> 
>     /* File size */
>     file_off_t size;
> ```

Why `file_off_t` for sizes? Just not to introduce another type? I guess it's ok, just a bit weird to have signed size.
___
*[LibOS/shim/include/shim_fs.h, line 268 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiS1kTn83gNEQhPfFUL:-MiS1kTn83gNEQhPfFUM:bjqhyhe) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L268)):*
> ```objc
> 
>     /* Deallocate internal data from an inode */
>     int (*iput)(struct shim_inode* inode);
> ```

Why this is part of dentry ops?
___
*[LibOS/shim/include/shim_fs.h, line 699 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiSXl1e2PI_3EbTrpNo:-MiSXl1f7Vibz4V6xoAr:bb7c7z9) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L699)):*
> ```objc
> 
> /*!
>  * \brief Allocaate and initialize a new inode
> ```

`aa`
___
*[LibOS/shim/include/shim_fs.h, line 705 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiSXvSO7euWeik9Oi1c:-MiSXvSO7euWeik9Oi1d:bo96vbz) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L705)):*
> ```objc
>  * \param perm inode permissions (PERM_rwxrwxrwx, etc.)
>  *
>  * This function will initialize the following fields: `mount`, `fs` (to `mount->fs`), `type`, and
> ```

It should initialize all fields (at least to 0, NULL etc) and then this comment will be pointless.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 379 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicLmxM6Jxdv3eqPCo3:-MicLmxM6Jxdv3eqPCo4:b-wc5ge1) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L379)):*
> ```C
> }
> 
> struct shim_inode* get_new_inode(struct shim_mount* mount, mode_t type, mode_t perm) {
> ```

Please add `assert(mount);`
___
*[LibOS/shim/src/fs/shim_dcache.c, line 380 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicKoif1ViH82GO3KHZ:-MicKoif1ViH82GO3KH_:bw3b2t2) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L380)):*
> ```C
> 
> struct shim_inode* get_new_inode(struct shim_mount* mount, mode_t type, mode_t perm) {
>     struct shim_inode* inode = malloc(sizeof(*inode));
> ```

Hm, maybe use `calloc` to zero everything?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 411 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicLKDw8Gs3goH9pha3:-MicLKDw8Gs3goH9pha4:b-v3wujy) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L411)):*
> ```C
>     if (REF_DEC(inode->ref_count) == 0) {
>         if (inode->fs->d_ops->iput) {
>             int ret = inode->fs->d_ops->iput(inode);
> ```

Can `iput` actually fail? Can we ignore the failure?
Maybe `iput` should return void and never fail? Currently there are no implementations of it, why did you introduce it then?
___
*[LibOS/shim/src/fs/shim_dcache.c, line 654 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicMmpN6ZollxgCVqeh:-MicMmpN6ZollxgCVqei:b-l4tfmb) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L654)):*
> ```C
> 
>         lock(&inode->lock);
>         memcpy(new_inode, inode, sizeof(*inode));
> ```

Could we copy all fields manually? This will copy everything, including nested structs, like `lock`, which might or might not be harmless (note that you don't clear `lock` struct anywhere). It might get worse when we expand `inode` with more fields later on.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 142 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicNcXJ3YcU2iSTG3rf:-MicNcXK-1SlI_hlB_5F:b-2iyhef) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/shim_fs_pseudo.c#L142)):*
> ```C
>         }
>     }
>     hdl->flags = flags & ~O_ACCMODE;
> ```

Why this change? Looks pretty random and unrelated. Why do we need it? If we keep everything in `flags` then what's the point of `acc_mode`?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 40 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicZFkZ3lL26w0i3vgj:-MicZFkZ3lL26w0i3vgk:byjx26e) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L40)):*
> ```C
>     /* Root of the filesystem on host (URI without the scheme) */
>     size_t root_len;
>     char root[];
> ```

Why have you opted to keep this inline (instead of external pointer)?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 115 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Micadoz8Bc04JH2X31v:-Micadoz8Bc04JH2X31w:b-cnq46l) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L115)):*
> ```C
> 
>     char* uri;
>     if (rel_path_size == 1) {
> ```

I do not understand this check. Isn't it true if we have a file `a` inside `/mounted_path`?
Update: ok, this is size not length. Why does `dentry_rel_path` returns size, not length? I would expect to have a length for a path (which is a C string, I suppose), this seems weird and non-natural to me...
___
*[LibOS/shim/src/fs/chroot/fs.c, line 116 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiccjgPBJZCzNYe9Fm8:-MiccjgPBJZCzNYe9Fm9:b-sdus9v) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L116)):*
> ```C
>     char* uri;
>     if (rel_path_size == 1) {
>         /* this is the mount root, the URI is "<prefix:><root>" */
> ```

Cannot we use `<prefix:><root>/` in this case? We could then remove this if completely and use the part from else clause unconditionally.
Or could this be a normal file (not directory) too, e.g. if we mount a single file? Then we could overwrite the trailing `/` with null byte, but it would overallocate the buffer by 1 byte. Would it be a problem? `uri` seems to be short-lived.... Generally my point is we could move `malloc`, prefix copying and root path copying out of this `if`.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 144 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Micf5768itlB8Hfbm69:-Micf5768itlB8Hfbm6A:b-y7ssex) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L144)):*
> ```C
> }
> 
> static int chroot_init_dentry(struct shim_dentry* dent, mode_t type, mode_t perm, file_off_t size) {
> ```

This function does not really initialize `dent`, merely a couple (out of many) of its fields. We need a better name.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 155 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mifdttz4aoaGRc6CNlM:-Mifdttz4aoaGRc6CNlN:bz3do3w) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L155)):*
> ```C
>         return -ENOMEM;
>     inode->size = size;
>     dent->inode = inode;
> ```

Shouldn't we inc refcount?
_ [...]

2021-09-06 15:01 UTC, pwmarcz reviewed
Rebased (we updated glibc so it's annoying to recompile the old one; and also introduced a conflicting change with `PAL_TYPE_*` today).

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646#-:-MiuYAnj4iQSWHFC0hCr:bhtwk7o)* status: 5 of 17 files reviewed, 63 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifOoJF26NnpNHHMzfe:-Miu_S5d9lk5bgN4ZSzi:bxkmojj) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Maybe any LTP tests (rename ones) can be enabled now?
</blockquote></details>

Unfortunately they depend on `utimensat` syscall to change modification times, so not yet.

(I'm planning to implement it, and this refactoring will help. It's used by many LTP test cases, and even by the `touch` command.)

---
___
*[-- commits, line 12 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MieqJ4U3AB21YwDVTSM):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`with that checks various cases` -- broken English?
</blockquote></details>

Removed `with`, thanks.
___
*[LibOS/shim/include/shim_fs.h, line 186 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiblloA9TCCdcrdb7Bo:-MiuaH731yDUnyFLc2is:bj4ah17) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L186)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `file_off_t` for sizes? Just not to introduce another type? I guess it's ok, just a bit weird to have signed size.
</blockquote></details>

This is what Linux and POSIX do (`loff_t i_size` in Linux inode, `off_t st_size` in stat). I think it's because it's good to have the same type for offset and size. And the offset type is signed because of how `seek` works.

(And after working a while with the filesystem code, I think I understand why signed type is better here: it's much easier to guard against size < 0 (and easier to notice bugs) than handle overflow.)
___
*[LibOS/shim/include/shim_fs.h, line 268 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiS1kTn83gNEQhPfFUL:-Miue-0u0s4oFFgJe3l_:bz19io7) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L268)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this is part of dentry ops?
</blockquote></details>

Because they're going to become "inode ops" later; most of them should take an inode and not touch dentries.

(But I don't need it right now, I'll add it back when I need the `data` field for inode).
___
*[LibOS/shim/include/shim_fs.h, line 699 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MierQj406fFZL6ermNt:-MiuebOdBDBL9v002yMx:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L699)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Typo: `Allocate`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 699 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiSXl1e2PI_3EbTrpNo:-MiuecG67jiuwaKJi2eC:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L699)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`aa`
</blockquote></details>

Fixed.
___
*[LibOS/shim/include/shim_fs.h, line 705 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiSXvSO7euWeik9Oi1c:-Miuf55fDlwa1EF6oFKU:b4oo9zm) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L705)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

It should initialize all fields (at least to 0, NULL etc) and then this comment will be pointless.
</blockquote></details>

The wording is unfortunate, we do initialize all fields. I removed this comment.
___
*[LibOS/shim/include/shim_handle.h, line 205 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Miet6VO1LuO2T7Urtkq:-MiugBFfBYG-tSnlVjXf:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_handle.h#L205)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It cannot change during the lifetime of the `shim_handle` object, right? In other words, we don't need to protect it with the `lock`? Can you add this comment then?
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 379 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicLmxM6Jxdv3eqPCo3:-MiugLvv4xAs78qL7eVy:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L379)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please add `assert(mount);`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 380 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicKoif1ViH82GO3KHZ:-MiugMHa-fiFFjVMBpil:b-6urzkx) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L380)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Hm, maybe use `calloc` to zero everything?
</blockquote></details>

OK. But I think we should still initialize every field.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 411 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicLKDw8Gs3goH9pha3:-Miuhfj01sypt1Qd_bxe:bb77sgx) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L411)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Can `iput` actually fail? Can we ignore the failure?
Maybe `iput` should return void and never fail? Currently there are no implementations of it, why did you introduce it then?
</blockquote></details>

I copied the existing design (dput etc.) but I agree, it should be void, like `free`.

Actually this is for the `data` field which we don't use yet. I'll remove it from this PR, and introduce in when it's needed.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 654 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicMmpN6ZollxgCVqeh:-MiuiezJ5pcZQyiilAq6:bjbg5vo) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L654)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we copy all fields manually? This will copy everything, including nested structs, like `lock`, which might or might not be harmless (note that you don't clear `lock` struct anywhere). It might get worse when we expand `inode` with more fields later on.
</blockquote></details>

I think this is what we should do everywhere once we rewrite checkpoint system (maybe when we rewrite it?)

I changed the memcpy to memset-zero (so that it works same as `calloc` above), and manually copy all the fields. It's different than all the other checkpoint/restore procedures, I guess we can treat it as an experiment...
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 142 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicNcXJ3YcU2iSTG3rf:-Miul31MAGaOWZgX5z_0:b-ul5o1e) ([raw file](https://github.com/oscarlab/graphene/blob/1a2 [...]

2021-09-06 19:33 UTC, boryspoplawski requested changes
> Reviewed 11 of 12 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646)* status: all files reviewed, 29 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv and @pwmarcz)

___
*[LibOS/shim/include/shim_fs.h, line 186 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiblloA9TCCdcrdb7Bo:-Mivh7vU-EQXpssv8drl:b-n0v02v) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L186)):*
>  I think it's because it's good to have the same type for offset and size. And the offset type is signed because of how seek works.

Yeah, that's what I was thinking too.

> (And after working a while with the filesystem code, I think I understand why signed type is better here: it's much easier to guard against size < 0 (and easier to notice bugs) than handle overflow.)

I don't see how signed type solves overflows...
___
*[LibOS/shim/src/fs/shim_dcache.c, line 380 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicKoif1ViH82GO3KHZ:-MivhrwW-WjOaL4lOWfp:bhkfecb) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L380)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

OK. But I think we should still initialize every field.
</blockquote></details>

Don't see a reason (since they are all `0` anyway), but I don't mind either.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 654 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicMmpN6ZollxgCVqeh:-MivipqG07-WVX9HryIA:b-5njlmi) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L654)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think this is what we should do everywhere once we rewrite checkpoint system (maybe when we rewrite it?)

I changed the memcpy to memset-zero (so that it works same as `calloc` above), and manually copy all the fields. It's different than all the other checkpoint/restore procedures, I guess we can treat it as an experiment...
</blockquote></details>

Is it really different? I've seen memset + manual copy in checkpointing, I think and there are definitely places where we just copy everything manually.
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 142 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicNcXJ3YcU2iSTG3rf:-MivjyVQAFF9KqyuwCqy:b6qwz7k) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/shim_fs_pseudo.c#L142)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I agree, this fix is unrelated. I moved it to a separate commit on this branch.

>Why this change? Looks pretty random and unrelated. Why do we need it?

I noticed this is the only place where we mask out `O_ACCMODE`. It's also wrong, there is at least one check that assumes the mode is there (`shim_vma.c` checks `file_hdl->flags & O_RDWR`; though most of the other checks use `acc_mode`).

>If we keep everything in flags then what's the point of `acc_mode`?

Probably because it's easier to use?

I think it would be good to change it this way (keep access mode out of flags), but then they should be called something else (like "options"). I did a similar thing with file mode (split it into "type" and "perm").
</blockquote></details>

All right.
Are you planning to unify this behavior (e.g. do the split)?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 406 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifxhRbCL0gmAWqXD52:-MiwWGPG0l4cm-WTHtfO:b-w44fjm) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L406)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It worked like this before, and I think it's a good optimization: we can skip taking locks, syscalls, etc.
</blockquote></details>

But there is no point, if app does `read(x, y, 0)` then it clearly doesn't care that much about performance. Besides it's rather rare, no need to optimize it.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifOQIT2KkraIT0XL0e:-MiwYIoQ2T5dbMaCPOpb:b-94if47) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I see. Is this complexity justified, though? What happens if we always send PAL handles?
</blockquote></details>

I don't know to be honest. Do protected files work correctly?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 294 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mivr4sJ3cRA8Vwvdqgz:-Mivr4sJ3cRA8Vwvdqh-:b5geae5) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L294)):*
> ```C
>         goto out;
> 
>     ret = chroot_setup_dentry(dent, type, perm, /*size=*/0);
> ```

Isn't it possible for `dent` to already have `inode`? E.g. if we create this file, delete and create again, or do we always delete dentry?


<!-- Sent from Reviewable.io -->

2021-09-07 07:34 UTC, dimakuv requested changes
> Reviewed 11 of 12 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 173 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mif4cq31zHxc5s9G65X:-Miz5NkN5DESE6meFYwr:b-bqwgwo) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L173)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

It sounds pretty bad to me, but I think it's a deeper design flaw in PAL, not a single thing you can correct. At least I don't have a clear idea how a fix should look like.
</blockquote></details>

OK, postponing
___
*[LibOS/shim/src/fs/chroot/fs.c, line 615 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifMJlO1N8YYIAQXpqp:-Miz8-rp8tWcNgvZ46K1:b2t65dt) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L615)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes, it's called in the receiving process.

I'm actually going to implement the same mechanism for inodes, once they hold custom data, but I probably should rename the `migrate` callback to `restore`.
</blockquote></details>

Yes, the name is very misleading. Please rename at some point to `restore`.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifOQIT2KkraIT0XL0e:-Miz87j_-AaiU654lnUB:bb1xpp7) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I don't know to be honest. Do protected files work correctly?
</blockquote></details>

I also don't know why this complexity. But it looks like everything works :) So I'm resolving.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-MizADyZ0rINMUC1Uw0a:-MizADyZ0rINMUC1Uw0b:bhn1gn4) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L11)):*
> ```C
>  *
>  * TODO: reintroduce the file position sync (using shim_fs_sync.h) after the migration to inodes is
>  * finished.
> ```

I thought that you added a LibOS regression test for this file position sync in one of your previous PRs? If yes, then how can Jenkins still pass?


<!-- Sent from Reviewable.io -->

2021-09-07 12:26 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646)* status: 15 of 17 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/include/shim_fs.h, line 186 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MiblloA9TCCdcrdb7Bo:-Mizi_dgAVIRrijaB1xY:b-ubhtfe) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/include/shim_fs.h#L186)):*
>I don't see how signed type solves overflows...

In some places you need to use a signed type anyway (e.g. seeking), and if your internal file size/offset is unsigned, you need to do a conversion which may overflow. This is inconvenient to handle, and makes the upper range of the unsigned type pretty much unusable anyway (you would have file size/offset so big you cannot report it to the user). With signed types, fewer conversions are necessary.
___
*[LibOS/shim/src/fs/shim_dcache.c, line 654 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicMmpN6ZollxgCVqeh:-Mizk5tP8UgC6TzxO0Zz:b8uaaet) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/shim_dcache.c#L654)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Is it really different? I've seen memset + manual copy in checkpointing, I think and there are definitely places where we just copy everything manually.
</blockquote></details>

I haven't seen such places, but I approve :)
___
*[LibOS/shim/src/fs/shim_fs_pseudo.c, line 142 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MicNcXJ3YcU2iSTG3rf:-Mizko9D333l4PGxqmxp:b-2ru72b) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/shim_fs_pseudo.c#L142)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

All right.
Are you planning to unify this behavior (e.g. do the split)?
</blockquote></details>

Not in the near future, so far it hasn't been annoying enough. But I guess after this discussion it at least deserves a TODO. I added one to `shim_handle`.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 406 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifxhRbCL0gmAWqXD52:-MizoPp09YHFmEazINPq:bm8qiro) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L406)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

But there is no point, if app does `read(x, y, 0)` then it clearly doesn't care that much about performance. Besides it's rather rare, no need to optimize it.
</blockquote></details>

OK. I'm happy to simplify.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 447 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifyBEGC8pcgwTclhxW:-MizoTT4-IULNXpmRhJr:bt9unbr) ([raw file](https://github.com/oscarlab/graphene/blob/5bd13eb472dc27da8356c559c93bef951ce2bfe3/LibOS/shim/src/fs/chroot/fs.c#L447)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Removed as well.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifOQIT2KkraIT0XL0e:-Mj-CQ3FDS-UkaJ5Ag7Z:b-m3ve40) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also don't know why this complexity. But it looks like everything works :) So I'm resolving.
</blockquote></details>

Ouch, you're right: inheriting a protected file handle doesn't work; it wasn't failing so badly before because we always reopened the file, and fails pretty badly right now.

I'll see if I can fix that, and restore the previous behavior if I can't.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-MizADyZ0rINMUC1Uw0a:-MizlG9HEEQc2zvgi0Ly:b-v4eohg) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I thought that you added a LibOS regression test for this file position sync in one of your previous PRs? If yes, then how can Jenkins still pass?
</blockquote></details>

I never got to enabling it on Jenkins (it works there only _without_ the sync engine, with a single process and multiple threads); that's because IPC was pretty unstable at that time and I didn't believe it would be reliable.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 294 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mivr4sJ3cRA8Vwvdqgz:-Mizn7mi8j8sfZ42PKQt:b-yt6ot0) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L294)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Isn't it possible for `dent` to already have `inode`? E.g. if we create this file, delete and create again, or do we always delete dentry?
</blockquote></details>

We don't delete the dentry, but we detach the inode when deleting. And creating a new inode (lookup/creat/mkdir) always happens with the global lock held. I added asserts to make that clear.

(The lock situation is... _bad_ currently. Many filesystem operations (syscall handlers) are pretty racy. The plan is to have only `g_dcache_lock` for dentries (no `shim_dentry.lock`), and locks for inodes.)


<!-- Sent from Reviewable.io -->

2021-09-07 13:26 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-MizADyZ0rINMUC1Uw0a:-Mj-PUGqDBq3n1OBNgUI:byr4ozj) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L11)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I never got to enabling it on Jenkins (it works there only _without_ the sync engine, with a single process and multiple threads); that's because IPC was pretty unstable at that time and I didn't believe it would be reliable.
</blockquote></details>

Does it work now (without this PR)? IPC should be stable.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 294 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mivr4sJ3cRA8Vwvdqgz:-Mj-QSq07vHaUoyY5Lv6:b-d0wflq) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L294)):*
> We don't delete the dentry, 

Wait, we do delete dentries... (`dentry_gc`)


<!-- Sent from Reviewable.io -->

2021-09-07 14:55 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2646)* status: 13 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/oscarlab/graphene/2646#-MifOQIT2KkraIT0XL0e:-Mj-fJfF5Prg0I3YuEjK:b-3ats2d) ([raw file](https://github.com/oscarlab/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Ouch, you're right: inheriting a protected file handle doesn't work; it wasn't failing so badly before because we always reopened the file, and fails pretty badly right now.

I'll see if I can fix that, and restore the previous behavior if I can't.
</blockquote></details>

Okay, this part of PAL looks pretty hostile to fixing: there is `DkSendHandle` which looks like _another_ "serialization" system (not a very smart one), and protected files do not take it into account at all.

I restored the previous behavior (only send PAL handles for files that don't exist anymore, reopen lazily), and added a test for sending handles.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 11 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-MizADyZ0rINMUC1Uw0a:-Mj-e5uZ5vuT3EOmUGnW:bqoaeg8) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L11)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Does it work now (without this PR)? IPC should be stable.
</blockquote></details>

I just checked and it works now, on master. But I'm about to disable this feature here.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 294 at r4](https://reviewable.io/reviews/oscarlab/graphene/2646#-Mivr4sJ3cRA8Vwvdqgz:-Mj-eBj_5IMtkZ1MZKOv:b-4qgpqr) ([raw file](https://github.com/oscarlab/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L294)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

> We don't delete the dentry, 

Wait, we do delete dentries... (`dentry_gc`)
</blockquote></details>

Yes, but we don't delete the dentry on unlink. We do that sometime later, when this directory is ever again, to prevent stale negative dentries from accumulating. If we `unlink` a file and then immediately `creat` it, the existing dentry will be reused.

(This is pretty bad design right now, because dentry contains so much data. If it's just a path-to-inode association, then it wouldn't matter).


<!-- Sent from Reviewable.io -->

2021-09-07 16:22 UTC, boryspoplawski requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: 13 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/gramineproject/graphene/2646#-MifOQIT2KkraIT0XL0e:-Mj02PH_9w0DJVLFPR8v:bx83o9w) ([raw file](https://github.com/gramineproject/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Okay, this part of PAL looks pretty hostile to fixing: there is `DkSendHandle` which looks like _another_ "serialization" system (not a very smart one), and protected files do not take it into account at all.

I restored the previous behavior (only send PAL handles for files that don't exist anymore, reopen lazily), and added a test for sending handles.
</blockquote></details>

Why is reopen lazy? Did it work like that before?
Update: Ok, I see the comment below, but I disagree. If something changes host permissions while Graphene is running, we are more than OK to exit with an error, actually, it's what I would expect to happen.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 11 at r4](https://reviewable.io/reviews/gramineproject/graphene/2646#-MizADyZ0rINMUC1Uw0a:-Mj-p33d355u1P9atovT:b4bmlf2) ([raw file](https://github.com/gramineproject/graphene/blob/7f851b95803b12a1884becf83ee04899802702c7/LibOS/shim/src/fs/chroot/fs.c#L11)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I just checked and it works now, on master. But I'm about to disable this feature here.
</blockquote></details>

Sure, was just asking out of curiosity and for the future.
___
*[LibOS/shim/test/regression/send_handle.c, line 1 at r6](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj-nFyt9FrhvpK6KRWL:-Mj-nFyu9a8qdG6RRW2L:b-jsvmqv) ([raw file](https://github.com/gramineproject/graphene/blob/b2996629a75fdf484ead0462e04a7d022d8786c8/LibOS/shim/test/regression/send_handle.c#L1)):*
> ```C
> /* SPDX-License-Identifier: LGPL-3.0-or-later */
> ```

Could we add this test functionality to some existing one? We do have a lot of fs tests already. The main reason is CI run time - enclave creation takes the most of it.


<!-- Sent from Reviewable.io -->

2021-09-07 17:19 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: 13 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/gramineproject/graphene/2646#-MifOQIT2KkraIT0XL0e:-Mj0B58b-okwUdksWzkX:b-nvr7f3) ([raw file](https://github.com/gramineproject/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
> Why is reopen lazy? Did it work like that before?

Yes, it did work like this before.

>Update: Ok, I see the comment below, but I disagree. If something changes host permissions while Graphene is running, we are more than OK to exit with an error, actually, it's what I would expect to happen.

The application can also change the permissions by itself (`fchmod`) or even `creat` a file with 000 permissions, I'm not sure how common that is but it's a well-documented case.

I changed the code so that it tries to open the file with the same parameters, I think that should be resistant enough to an application shooting itself in the foot.
___
*[LibOS/shim/test/regression/send_handle.c, line 1 at r6](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj-nFyt9FrhvpK6KRWL:-Mj05cuGAEfpy4PkpKOY:bei4ch2) ([raw file](https://github.com/gramineproject/graphene/blob/b2996629a75fdf484ead0462e04a7d022d8786c8/LibOS/shim/test/regression/send_handle.c#L1)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could we add this test functionality to some existing one? We do have a lot of fs tests already. The main reason is CI run time - enclave creation takes the most of it.
</blockquote></details>

If you mean the tests in `fs`, these are pretty useless, and last time [I've been asked not to add more](https://github.com/gramineproject/graphene/pull/2584#pullrequestreview-716989621) because they're "mainly to check copying of a bunch of files".

Here in `regression`, we have a few tests that do a fork, but none seem to fit thematically. I think it's a good idea to combine some tests (for example, we have 4 different programs for futex operations), but I'm not sure if this one can be added anywhere without it looking weird.

(By the way, it's hard to make a smaller enclave because PAL has 64 megabytes worth of `g_mem_pool`, maybe if we fix allocation in PAL, it would allow the tests to run in smaller enclave and be faster?)


<!-- Sent from Reviewable.io -->

2021-09-07 22:12 UTC, boryspoplawski requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: 14 of 19 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski, @dimakuv, and @pwmarcz)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 811 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj1HFjdDpZ_XQ797FCG:-Mj1HFjdDpZ_XQ797FCH:b-zedqsd) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/bookkeep/shim_handle.c#L811)):*
> ```C
> 
>     if (hdl->fs && hdl->fs->fs_ops && hdl->fs->fs_ops->checkin)
>         hdl->fs->fs_ops->checkin(hdl);
> ```

Could you add error checking here? We depend on in in chroot.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/gramineproject/graphene/2646#-MifOQIT2KkraIT0XL0e:-Mj0Ucdb8Uz3qqOULoat:biftu2q) ([raw file](https://github.com/gramineproject/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

> Why is reopen lazy? Did it work like that before?

Yes, it did work like this before.

>Update: Ok, I see the comment below, but I disagree. If something changes host permissions while Graphene is running, we are more than OK to exit with an error, actually, it's what I would expect to happen.

The application can also change the permissions by itself (`fchmod`) or even `creat` a file with 000 permissions, I'm not sure how common that is but it's a well-documented case.

I changed the code so that it tries to open the file with the same parameters, I think that should be resistant enough to an application shooting itself in the foot.
</blockquote></details>

Didn't we have a code that added `S_IRUSR` at some layer? (Can't find it now.)
___
*[LibOS/shim/src/fs/chroot/fs.c, line 734 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj1CKw6D6KrM5nXWOlo:-Mj1CKw6D6KrM5nXWOlp:b-k9ejqa) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L734)):*
> ```C
>      * inode). */
>     lock(&hdl->dentry->lock);
>     bool still_exists = (hdl->dentry->inode == hdl->inode);
> ```

How can this be false? Only if `hdl->dentry->inode == NULL`?
___
*[LibOS/shim/test/regression/send_handle.c, line 1 at r6](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj-nFyt9FrhvpK6KRWL:-Mj1HhO_8ee2F51s3Bee:bjkso76) ([raw file](https://github.com/gramineproject/graphene/blob/b2996629a75fdf484ead0462e04a7d022d8786c8/LibOS/shim/test/regression/send_handle.c#L1)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

If you mean the tests in `fs`, these are pretty useless, and last time [I've been asked not to add more](https://github.com/gramineproject/graphene/pull/2584#pullrequestreview-716989621) because they're "mainly to check copying of a bunch of files".

Here in `regression`, we have a few tests that do a fork, but none seem to fit thematically. I think it's a good idea to combine some tests (for example, we have 4 different programs for futex operations), but I'm not sure if this one can be added anywhere without it looking weird.

(By the way, it's hard to make a smaller enclave because PAL has 64 megabytes worth of `g_mem_pool`, maybe if we fix allocation in PAL, it would allow the tests to run in smaller enclave and be faster?)
</blockquote></details>

I meant LibOS regression.
There is nothing stopping you from adding this to a test that does not fork currently. It should be a separate function doing this test (open + fork + read/write + wait).
Is there no file that this could be added to?


<!-- Sent from Reviewable.io -->

2021-09-08 09:50 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r5, 5 of 6 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 725 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3mkFW3V0uJ3W0d7qo:-Mj3mkFW3V0uJ3W0d7qp:b-b5poxk) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L725)):*
> ```C
>  * process (`DkSendHandle`). This workaround limits the damage: inheriting a handle by child process
>  * will now fail to work only if it's a handle for a protected file *and* the file has been deleted
>  * from host.
> ```

We need someone to re-work the Protected Files implementation in PAL properly. It's missing too many important features: proper checkpoint/restore support, proper refcounting, etc. We papered over the cracks for too long, and now it's showing...
___
*[LibOS/shim/src/fs/chroot/fs.c, line 744 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3nmD37JS3WoOO5wsB:-Mj3nmD37JS3WoOO5wsC:b-gpby37) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L744)):*
> ```C
>         if (chroot_reopen(hdl, &palhdl) == 0) {
>             DkObjectClose(palhdl);
>             hdl->pal_handle = NULL;
> ```

Don't we need to `lock(hdl)`?
___
*[LibOS/shim/src/fs/chroot/fs.c, line 761 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3o1Bq8X7UO894j4E_:-Mj3o1Bq8X7UO894j4Ea:bnqppaj) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L761)):*
> ```C
>             return ret;
>         }
>         hdl->pal_handle = palhdl;
> ```

Don't we need to `lock(hdl)`? Well, maybe not here because it happens only during Graphene init.
___
*[LibOS/shim/test/regression/Makefile, line 112 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3l_3H5k0UZ_V2iC4v:-Mj3l_3H5k0UZ_V2iC4w:bh4j3c3) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/test/regression/Makefile#L112)):*
> ```Makefile
> 	file_check_policy_allow_all_but_log.manifest \
> 	file_check_policy_strict.manifest \
> 	multi_pthread_exitless.manifest
> ```

Are you sure your `send_handle.manifest.sgx` file is derived from `send_handle.manifest.template` and not from the generic `manifest.template`? Because you didn't add your template in this list.
___
*[LibOS/shim/test/regression/send_handle.c, line 1 at r6](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj-nFyt9FrhvpK6KRWL:-Mj3hcZV9_Dp5SlQd2Rq:b-xwbm24) ([raw file](https://github.com/gramineproject/graphene/blob/b2996629a75fdf484ead0462e04a7d022d8786c8/LibOS/shim/test/regression/send_handle.c#L1)):*
> Could we add this test functionality to some existing one?

I am against it. This test is way too long to add it to an existing one. To me, the main quality of a LibOS regression test is to debug it easily. Adding unrelated tests in one file makes debugging much more cumbersome.

> The main reason is CI run time - enclave creation takes the most of it.

We have many old, like *really old* regression tests that test almost nothing and occupy CI time. If we care about CI time, I would start by deleting, modifying and merging together these old tests. Not artifically lumping together new tests.

> (By the way, it's hard to make a smaller enclave because PAL has 64 megabytes worth of g_mem_pool, maybe if we fix allocation in PAL, it would allow the tests to run in smaller enclave and be faster?)

One day, one day... But for now it's impractical to decrease the 64mb size of the initial PAL memory pool. In particular, we need some pre-allocated memory before we get to `loader.pal_internal_mem_size` manifest option. And given that some manifests seen in the wild may have ~20MB of text, and the manifest needs to be parsed into enclave memory by the TOML library *before* we are able to look at  `loader.pal_internal_mem_size`, we are stuck with 64MB of initial memory.
___
*[LibOS/shim/test/regression/send_handle.manifest.template, line 25 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3lnYW2DW3DlW6Jhs3:-Mj3lnYW2DW3DlW6Jhs4:b-4pw4wy) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/test/regression/send_handle.manifest.template#L25)):*
> ```
> sgx.protected_files = [
>   "file:tmp/pf/",
> ]
> ```

Why do you even need this new file? You can just add the missing manifest options to the generic `manifest.template` file and add a comment that these manifest options are for the specific `send_handle` test.
___
*[LibOS/shim/test/regression/test_libos.py, line 204 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3mDbL2zdQEQQUhYu5:-Mj3mDbL2zdQEQQUhYu6:b-puf39i) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/test/regression/test_libos.py#L204)):*
> ```Python
>             if os.path.exists(path):
>                 os.unlink(path)
>         self.assertIn('TEST OK', stdout, 'test failed: {}'.format(cmd))
> ```

This `test failed` part is something new. Why do you need this?


<!-- Sent from Reviewable.io -->

2021-09-08 10:35 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/bookkeep/shim_handle.c, line 811 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj1HFjdDpZ_XQ797FCG:-Mj3ogQgEl1oM6NP5-Ym:b-t4f506) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/bookkeep/shim_handle.c#L811)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Could you add error checking here? We depend on in in chroot.
</blockquote></details>

Ouch. Done.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/gramineproject/graphene/2646#-MifOQIT2KkraIT0XL0e:-Mj3oipE0ArEXleNS1bf:b2tt7xt) ([raw file](https://github.com/gramineproject/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Didn't we have a code that added `S_IRUSR` at some layer? (Can't find it now.)
</blockquote></details>

I don't know, but we can also create a read-only file for writing, etc. AFAICT, The PAL code doesn't seem super aware of file modes, it just passes them to Linux without looking...

... But it turns out my solution does not work (and I didn't know about that because Jenkins broke). That's because you can't have two writable handles to a protected file? (Which in itself seems to be a design flaw, because we actually store a single data structure per file).

Anyway, okay, let's do `DkStreamAttributesQuery` _and_ fail early if something goes wrong, as you suggested.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 725 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3mkFW3V0uJ3W0d7qo:-Mj3p36qBa44PgLqEMlt:b-81y9xq) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L725)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We need someone to re-work the Protected Files implementation in PAL properly. It's missing too many important features: proper checkpoint/restore support, proper refcounting, etc. We papered over the cracks for too long, and now it's showing...
</blockquote></details>

Yeah, I'm starting to get annoyed at this too.

By the way, what do you think about moving protected-files feature out of SGX somehow? While this doesn't give any additional security for graphene-direct, it would help with development and testing.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 734 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj1CKw6D6KrM5nXWOlo:-Mj3pDQ-5YLN9eefNc2d:b-o8nwcv) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L734)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

How can this be false? Only if `hdl->dentry->inode == NULL`?
</blockquote></details>

The file might be deleted and another file might be created in its place: `hdl->dentry->inode` would then point to this new file, and we still care about the _old_ one, accessible through our handle.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 744 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3nmD37JS3WoOO5wsB:-Mj3pqt22PUBgLhdQO-t:bzbsq0k) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L744)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we need to `lock(hdl)`?
</blockquote></details>

This is called on a new, copied handle (`new_hdl` in the checkpoint code), AFAICT it doesn't even have a real lock.

Added a comment.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 761 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3o1Bq8X7UO894j4E_:-Mj3qXCCE4LbOKkzeUbB:bundyg2) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L761)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Don't we need to `lock(hdl)`? Well, maybe not here because it happens only during Graphene init.
</blockquote></details>

Yes. Added a comment.
___
*[LibOS/shim/test/regression/Makefile, line 112 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3l_3H5k0UZ_V2iC4v:-Mj3rt4q4xk-5wUaRoH6:bx1kx5p) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/test/regression/Makefile#L112)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Are you sure your `send_handle.manifest.sgx` file is derived from `send_handle.manifest.template` and not from the generic `manifest.template`? Because you didn't add your template in this list.
</blockquote></details>

I think it still worked for me... But anyway, I removed this extra template.
___
*[LibOS/shim/test/regression/send_handle.c, line 1 at r6](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj-nFyt9FrhvpK6KRWL:-Mj3r6PzEtYjYBZ2L3vm:bbqp8p8) ([raw file](https://github.com/gramineproject/graphene/blob/b2996629a75fdf484ead0462e04a7d022d8786c8/LibOS/shim/test/regression/send_handle.c#L1)):*
>Is there no file that this could be added to?

We don't have that many filesystem tests. I'm open to suggestions, but I agree with @dimakuv it's not worth it to artificially lump together tests that are only barely related.
___
*[LibOS/shim/test/regression/send_handle.manifest.template, line 25 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3lnYW2DW3DlW6Jhs3:-Mj3rlhV066h5SMN_3OQ:b-aa14oj) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/test/regression/send_handle.manifest.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you even need this new file? You can just add the missing manifest options to the generic `manifest.template` file and add a comment that these manifest options are for the specific `send_handle` test.
</blockquote></details>

Okay, I see we already do that for other tests. Done.
___
*[LibOS/shim/test/regression/test_libos.py, line 204 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3mDbL2zdQEQQUhYu5:-Mj3sZvz0ALVxTSPzHlN:b56p7dg) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/test/regression/test_libos.py#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `test failed` part is something new. Why do you need this?
</blockquote></details>

This is an extra message to provide context for the user. I added it because this is not a single test, but a method that is sometimes being called multiple times from a single test. (The user might still look through the traceback, but this is friendlier).


<!-- Sent from Reviewable.io -->

2021-09-08 11:18 UTC, dimakuv approved these changes, later dismissed
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 875 at r2](https://reviewable.io/reviews/gramineproject/graphene/2646#-MifOQIT2KkraIT0XL0e:-Mj46-eM86veFYp7Vv8l:bojl7oj) ([raw file](https://github.com/gramineproject/graphene/blob/1a2275e00d00a29de12e2d7de840141ce264b2cb/LibOS/shim/src/fs/chroot/fs.c#L875)):*
> That's because you can't have two writable handles to a protected file? (Which in itself seems to be a design flaw, because we actually store a single data structure per file).

Yes, this is correct. I tried to fix it in my postponed PR: https://github.com/gramineproject/graphene/pull/2372. The consensus though was that PFs are very much broken, and we should postpone the PR and just fix PFs properly in the future.
___
*[LibOS/shim/src/fs/chroot/fs.c, line 725 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3mkFW3V0uJ3W0d7qo:-Mj46IWB0ULefH9pC2Qw:b87g7h) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L725)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yeah, I'm starting to get annoyed at this too.

By the way, what do you think about moving protected-files feature out of SGX somehow? While this doesn't give any additional security for graphene-direct, it would help with development and testing.
</blockquote></details>

Help with development and testing? How?

Generally sure, we can move them out. I just don't see how exactly it helps (easier to debug `graphene-direct` than `graphene-sgx`?).

Also, this would force us to also move out `trusted_files` feature out of SGX. Otherwise we'll have strange discrepancy.

Anyway, moving PFs out of SGX sounds like way too much effort (including side efforts).
___
*[LibOS/shim/src/fs/chroot/fs.c, line 744 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3nmD37JS3WoOO5wsB:-Mj46lsp3-SLRf_EQiUZ:bl3ckni) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L744)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is called on a new, copied handle (`new_hdl` in the checkpoint code), AFAICT it doesn't even have a real lock.

Added a comment.
</blockquote></details>

OK. Our checkpointing subsystem and its naming is amazing.


<!-- Sent from Reviewable.io -->

2021-09-08 11:38 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 725 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3mkFW3V0uJ3W0d7qo:-Mj49EoP1g2yLTepYr7r:b33pgle) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L725)):*
> Help with development and testing? How?

>Generally sure, we can move them out. I just don't see how exactly it helps (easier to debug graphene-direct than graphene-sgx?).

As a developer, I can set up `graphene-direct` locally and work on it quickly.

I don't have a local setup for SGX, so I need to rely on Jenkins or external server, which means having to commit first or editing code remotely.

I need to re-sign manifests every time I rebuild Graphene or the application, which takes time. And our Makefiles are pretty brittle do not track all dependencies correctly, so sometimes that requires manually deleting files or even running the same `make` command twice.

And SGX startup is much slower, there's a few seconds of overhead for every program run, so it's impractical to e.g. run the whole `make regression` often.

I'm sure some of these problems can be fixed, but for now `graphene-direct` remains a much more attractive option for development.

>Anyway, moving PFs out of SGX sounds like way too much effort (including side efforts).

OK. I guess that's something we'll do when we have another "real" target...


<!-- Sent from Reviewable.io -->

2021-09-08 12:04 UTC, boryspoplawski requested changes
> Reviewed 4 of 6 files at r6, 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 734 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj1CKw6D6KrM5nXWOlo:-Mj4EzW5ApV0WKDbBwEx:b-81dsqw) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L734)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

The file might be deleted and another file might be created in its place: `hdl->dentry->inode` would then point to this new file, and we still care about the _old_ one, accessible through our handle.
</blockquote></details>

Ok that makes sense.
What happens in such case if the file is PF? Does it work, error out with a message or just blows up?
___
*[LibOS/shim/test/regression/send_handle.c, line 25 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4FeNB7mRkUi3A2M81:-Mj4FeNB7mRkUi3A2M82:b64fzak) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/send_handle.c#L25)):*
> ```C
> 
> #define MESSAGE "hello world"
> #define MESSAGE_LEN 11
> ```

Maybe `sizeof(MESSAGE) - 1`?
___
*[LibOS/shim/test/regression/send_handle.c, line 41 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4GTpW6uU3rSzvDaw5:-Mj4GTpW6uU3rSzvDaw6:bciy45e) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/send_handle.c#L41)):*
> ```C
>     const char* path = argv[i];
> 
>     int fd = open(path, O_RDWR | O_CREAT | O_EXCL, 0666);
> ```

Why `O_EXCL`? If something breaks or I stop the test in the middle, it won't run again.
___
*[LibOS/shim/test/regression/send_handle.c, line 54 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4GiqF-m1bCNC1ax7S:-Mj4GiqF-m1bCNC1ax7T:b8qizhl) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/send_handle.c#L54)):*
> ```C
>     do {
>         ssize_t ret = write(fd, &message[pos], MESSAGE_LEN - pos);
>         if (ret < 0)
> ```

`ret == 0` not handled.
___
*[LibOS/shim/test/regression/test_libos.py, line 198 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4HZzg423IPZecRENz:-Mj4HZzh1_d-83GZB66M:b-3xzvhw) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/test_libos.py#L198)):*
> ```Python
> 
>         if os.path.exists(path):
>             os.unlink(path)
> ```

I would move this to the test so it can be run standalone.


<!-- Sent from Reviewable.io -->

2021-09-08 13:09 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: 18 of 20 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @dimakuv)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 734 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj1CKw6D6KrM5nXWOlo:-Mj4NW6R0_Ak6PPltMnQ:b-vv8d2k) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L734)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Ok that makes sense.
What happens in such case if the file is PF? Does it work, error out with a message or just blows up?
</blockquote></details>

LibOS will see that the file does not exist on host, and transfer the PAL handle to the child process. However, this doesn't send any information about protected files.

On next `read()` in the child process, PAL will call `find_protected_file` for the handle. Then:

* if the file has been mentioned by name in the manifest, PAL will find a not-loaded protected file object, and return `PAL_ERROR_BAD_HANDLE`, which LibOS translates to `EFAULT` and returns that from `read()`,
* if the file has not been mentioned by name in the manifest (for example, because we only included the parent directory in protected files), `read` will proceed as if this was a normal file, but will read encrypted data.

AFAIK this is how it works on master right now :(

The problem is that protected files are supposed to work "transparently", so they're indistinguishable from other handles from outside, but they break horribly in many cases. Also, the PAL handle is not linked to `struct protected_file` in any way, but we rely on a hash lookup.
___
*[LibOS/shim/test/regression/send_handle.c, line 25 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4FeNB7mRkUi3A2M81:-Mj4R6rl7WYP3ue0XD8n:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/send_handle.c#L25)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Maybe `sizeof(MESSAGE) - 1`?
</blockquote></details>

Done.
___
*[LibOS/shim/test/regression/send_handle.c, line 41 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4GTpW6uU3rSzvDaw5:-Mj4RFOs3v1mzRWtaoio:b-nr2swc) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/send_handle.c#L41)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why `O_EXCL`? If something breaks or I stop the test in the middle, it won't run again.
</blockquote></details>

This will error out trying to open a malformed protected file, even with `O_TRUNC`. In fact, I cannot even `unlink` such file from inside Graphene, because any operation on it will fail. Another quirk of protected files :)

But it might be more friendly if I do `O_CREAT | O_TRUNC` here, and ensure the Python harness deletes the protected file first.
___
*[LibOS/shim/test/regression/send_handle.c, line 54 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4GiqF-m1bCNC1ax7S:-Mj4Td2NCnkdVHBdcqj4:b-14x8po) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/send_handle.c#L54)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`ret == 0` not handled.
</blockquote></details>

I think `write` is not allowed to return 0 here (at least [according to some people who read the POSIX spec](https://stackoverflow.com/a/41970485)). But since this is Graphene, I'll add a check.
___
*[LibOS/shim/test/regression/test_libos.py, line 198 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4HZzg423IPZecRENz:-Mj4UIoD3vgQfrzTiJNZ:b-9yv7zb) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/test_libos.py#L198)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

I would move this to the test so it can be run standalone.
</blockquote></details>

See the other discussion: the case this is supposed to guard against (trying to access a protected file that has garbage data) doesn't actually allow you to unlink the file from inside the test.

I changed the test so that it accepts an existing file, and added an explanation here for why we do the unlink.


<!-- Sent from Reviewable.io -->

2021-09-08 13:48 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: all files reviewed, 5 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[LibOS/shim/src/fs/chroot/fs.c, line 725 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj3mkFW3V0uJ3W0d7qo:-Mj4dsAnAPV85ZqSMX7g:b-j25zd4) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L725)):*
> I don't have a local setup for SGX, so I need to rely on Jenkins or external server, which means having to commit first or editing code remotely.

😲


<!-- Sent from Reviewable.io -->

2021-09-08 14:04 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[LibOS/shim/src/fs/chroot/fs.c, line 734 at r7](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj1CKw6D6KrM5nXWOlo:-Mj4gFGk6gLzBQ8jbsy0:b-1o2lzg) ([raw file](https://github.com/gramineproject/graphene/blob/a280a73dd2a967e414f99677a5bac557ae6aca92/LibOS/shim/src/fs/chroot/fs.c#L734)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

LibOS will see that the file does not exist on host, and transfer the PAL handle to the child process. However, this doesn't send any information about protected files.

On next `read()` in the child process, PAL will call `find_protected_file` for the handle. Then:

* if the file has been mentioned by name in the manifest, PAL will find a not-loaded protected file object, and return `PAL_ERROR_BAD_HANDLE`, which LibOS translates to `EFAULT` and returns that from `read()`,
* if the file has not been mentioned by name in the manifest (for example, because we only included the parent directory in protected files), `read` will proceed as if this was a normal file, but will read encrypted data.

AFAIK this is how it works on master right now :(

The problem is that protected files are supposed to work "transparently", so they're indistinguishable from other handles from outside, but they break horribly in many cases. Also, the PAL handle is not linked to `struct protected_file` in any way, but we rely on a hash lookup.
</blockquote></details>

Ok, if the current version is not worse than the master, then let's leave it, but oh boy, this looks bad.
___
*[LibOS/shim/test/regression/send_handle.c, line 54 at r8](https://reviewable.io/reviews/gramineproject/graphene/2646#-Mj4GiqF-m1bCNC1ax7S:-Mj4hQ-U1FctbF0naYjS:bgatctg) ([raw file](https://github.com/gramineproject/graphene/blob/68a815de1ebd8874f9c03629ff90f7e49953695a/LibOS/shim/test/regression/send_handle.c#L54)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I think `write` is not allowed to return 0 here (at least [according to some people who read the POSIX spec](https://stackoverflow.com/a/41970485)). But since this is Graphene, I'll add a check.
</blockquote></details>

1. We emulate Linux not POSIX. (from manpage: "Note that not all filesystems are POSIX conforming")
2. As you noted, this is Graphene ;)


<!-- Sent from Reviewable.io -->

2021-09-09 09:59 UTC, pwmarcz reviewed
All discussions resolved, so I'm resubmitting the PR to Gramine: https://github.com/gramineproject/gramine/pull/5

> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2646#-:-Mj4quWn0LMlscXKumeg:b-7v4naw)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-10-03 02:16 UTC, mkow commented
This was already merged in the new repo, so I'm closing it.

2021-10-03 02:16 UTC, closed without merging