Fix GDB integration with non-C apps
oscarlab/graphene pull request #2652
Opened 2021-08-17 11:15 UTC by mkow

## Description of the changes 

I truly hate GDB :) It turns out that the scripts are interpreted with syntax which depends on the current *app* language. So, e.g. expressions in our signal handler in GDB script are parsed using C syntax if the signal happened when executing C code, but if the signal arrived in Rust code, then the expressions in same script code will be parsed as Rust...

## How to test this PR? 

Try to debug a Rust application in Graphene.

2021-08-17 11:44 UTC, pwmarcz requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2652)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

___
*[Pal/gdb_integration/language_gdb.py, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2652#-MhIumvz1yU4tLynFCST:-MhIumw-664tlzZLHpZZ:b-jueolm) ([raw file](https://github.com/oscarlab/graphene/blob/8418585a899cf499a6395165cf2e376604873e09/Pal/gdb_integration/language_gdb.py#L33)):*
> ```Python
> 
>         lang_str = gdb.execute('show language', to_string=True).strip()
>         lang_str = cut_between(lang_str, 'The current source language is "', '"')
> ```

How about:

```python
m = re.match(r'The current language is "(.*?)"', lang_str)
assert m, "unexpected output from 'show language': " + lang_str
lang = m.group(1)
```

If GDB changes its output, this would fail with a clearer message.


<!-- Sent from Reviewable.io -->

2021-08-17 12:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2652)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/gdb_integration/language_gdb.py, line 33 at r1](https://reviewable.io/reviews/oscarlab/graphene/2652#-MhIumvz1yU4tLynFCST:-MhJ0glh8RIb4V98BAWR:b-fznogt) ([raw file](https://github.com/oscarlab/graphene/blob/8418585a899cf499a6395165cf2e376604873e09/Pal/gdb_integration/language_gdb.py#L33)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

How about:

```python
m = re.match(r'The current language is "(.*?)"', lang_str)
assert m, "unexpected output from 'show language': " + lang_str
lang = m.group(1)
```

If GDB changes its output, this would fail with a clearer message.
</blockquote></details>

Good idea, done.


<!-- Sent from Reviewable.io -->

2021-08-17 13:18 UTC, pwmarcz requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2652)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[Pal/gdb_integration/language_gdb.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2652#-MhJFaLZ7wRTSnW7peOO:-MhJFaL_AieSnkLg1-lS:b2fcop3) ([raw file](https://github.com/oscarlab/graphene/blob/f5a3c330aef00436dcee6f8b512f7524ea9672b9/Pal/gdb_integration/language_gdb.py#L15)):*
>C: 15, 0: standard import "import re" should be placed before "import gdb" (wrong-import-order)```

```python
import re

import gdb
```


<!-- Sent from Reviewable.io -->

2021-08-17 13:28 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2652)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[Pal/gdb_integration/language_gdb.py, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene/2652#-MhJFaLZ7wRTSnW7peOO:-MhJH6uv5JT_0i36RId5:bev6w9v) ([raw file](https://github.com/oscarlab/graphene/blob/f5a3c330aef00436dcee6f8b512f7524ea9672b9/Pal/gdb_integration/language_gdb.py#L15)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

>C: 15, 0: standard import "import re" should be placed before "import gdb" (wrong-import-order)```

```python
import re

import gdb
```
</blockquote></details>

Uh, pylint is really annoying. I ran it locally and it passed, seems all versions emit completely different sets of warnings... (as you can see on Jenkins, it failed only on 18.04...)


<!-- Sent from Reviewable.io -->

2021-08-17 14:14 UTC, pwmarcz approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2652)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-08-23 08:05 UTC, dimakuv approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2652)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-23 08:07 UTC, pwmarcz approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2652)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-23 08:27 UTC, merged