[Examples] pytorch: Fix permission denied error for python local libs…
oscarlab/graphene pull request #2655
Opened 2021-08-18 13:48 UTC by sahason

… and result.txt in Graphene-SGX

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Fix permission denied error for python local libs. In manifest file python local libs paths are not populated correctly, used `installed_base` instead of `prefix` for `vars` parameter while getting the path using `sysconfig.getpath()`.
Please check https://github.com/python/cpython/blob/ebe7e6d86cf8f54d449d49866698d7f4c700cc7c/Lib/sysconfig.py#L28

Fix accessing `result.txt` is denied as the file is not trusted/allowed. Increased thread numbers and enclave size to run the application successfully.

Fixes #2643

## How to test this PR? 

Build and run pytorch example according to the instructions
in https://github.com/oscarlab/graphene/blob/master/Examples/pytorch/README.md
Example application should run without error.

2021-08-18 13:57 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2655)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-19 00:25 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2655)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2655#-MhQmYzhBkNjQ4c7gX1Q:-MhQmYzhBkNjQ4c7gX1R:byv1j7k) (no related file):*
> Fixes #2643 #2630 

This won't work as expected - you need to write "fixes" keyword twice, right now only the first issue will get auto-closed. Otherwise this PR looks good :)

---


<!-- Sent from Reviewable.io -->

2021-08-19 04:52 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2655)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2655#-MhQmYzhBkNjQ4c7gX1Q:-MhRk4BL7JekkgjWAOYC:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Fixes #2643 #2630 

This won't work as expected - you need to write "fixes" keyword twice, right now only the first issue will get auto-closed. Otherwise this PR looks good :)
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-08-19 11:18 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2655)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-19 15:55 UTC, mkow commented
Jenkins, test this please

2021-08-19 16:11 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2655)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-19 16:15 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2655)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-23 04:34 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2655)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-23 07:54 UTC, merged