Prepare for UBSan and Clang
oscarlab/graphene pull request #2657
Opened 2021-08-19 14:48 UTC by pwmarcz

This is in preparation to enable UBSan (and Clang at the same time, because Clang's checks are much stronger).

## Description of the changes 

See commit messages.

Note that these are just bugfixes in existing code. I will submit UBSan integration (and Jenkins configuration) in next PR.

## How to test this PR? 

The current tests should ensure there are no regressions. I also ran this code on a [draft branch](https://github.com/oscarlab/graphene/pull/2653) and it passes UBSan.

2021-08-23 08:09 UTC, pwmarcz commented
Jenkins, retest Jenkins-20.04, please (timeout in LTP, seems unrelated)

2021-08-23 16:56 UTC, pwmarcz reviewed
>Jenkins, retest Jenkins-20.04, please (timeout in LTP, seems unrelated)

Weird, looks like that didn't trigger anything...

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657#-:-Mhnvm-24egzCOv_e6Ax:brxo5uu)* status: 0 of 9 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[common/src/string/strlen.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhTsnc97DFIjpmDg9T-:-MhTsnc97DFIjpmDg9T0:b-ea59dx) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/strlen.c#L10)):*
> ```C
> /* Find the length of S, but scan at most MAXLEN characters.  If no
>    '\0' terminator is found in that many characters, return MAXLEN.  */
> size_t strnlen(const char* str, size_t maxlen) {
> ```

This is going to be slower 


<!-- Sent from Reviewable.io -->

2021-08-23 22:41 UTC, mkow requested changes
> Weird, looks like that didn't trigger anything...

Heh, you put a comma before "please" which our primitive regexes didn't foresee :)

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657#-:-MhpA-U4DD0g6qA23iIN:beq1ij7)* status: 0 of 9 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[common/src/string/strlen.c, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhTthQI9RrwK1Lu9yB8:-MhTthQI9RrwK1Lu9yB9:b23jk3r) ([raw file](https://github.com/oscarlab/graphene/blob/398727edcee3f8e29c050d2cfdcc7a79d7387e5d/common/src/string/strlen.c#L3)):*
> ```C
> /* Find the length of STRING, but scan at most MAXLEN characters.
>    Copyright (C) 1991,1993,1997,2000,2001,2005 Free Software Foundation, Inc.
>    Contributed by Jakub Jelinek <jakub@redhat.com>.
> ```

Please update LICENSE.addendum.txt
___
*[LibOS/shim/src/fs/shim_fs_mem.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhTtUThBBAAxWGU7L03:-MhTtUThBBAAxWGU7L04:b-kpnmmf) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/LibOS/shim/src/fs/shim_fs_mem.c#L12)):*
> ```C
> #define OVERFLOWS(type, val)                        \
>     ({                                              \
>         file_off_t __dummy;                         \
> ```

`file_off_t` -> `type`


<!-- Sent from Reviewable.io -->

2021-08-23 22:42 UTC, mkow commented
Jenkins, retest Jenkins-20.04 please (this version of the trigger should work :) )

2021-08-23 23:41 UTC, mkow requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @pwmarcz)

___
*[common/src/string/atoi.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpMp06B4iLVLqoXuCI:-MhpMp06B4iLVLqoXuCJ:beiytxt) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L128)):*
> ```C
>     }
> 
>     if (s == str)
> ```

unrelated, but why is this check here, but not in `strtol()`?
___
*[common/src/string/atoi.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpNdafEkIBqgyCk6uV:-MhpNdafEkIBqgyCk6uW:b-e3zr7q) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L165)):*
> ```C
> 
>         __builtin_mul_overflow(value, 10, &value);
>         __builtin_add_overflow(value, digit * sign, &value);
> ```

Why not just do the arithmetic normally? These functions are assuming the input is correct.

Also, I'm not sure how the out value is defined on overflow in these macros? The documentation doesn't specify this :/
___
*[common/src/string/strlen.c, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhTsnc97DFIjpmDg9T-:-MhpF1sWAmX9T-ZUXBYm:b6giatn) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/strlen.c#L10)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

This is going to be slower 
</blockquote></details>

This is used only internally and usually for short strings, so it shouldn't really matter IMO.
___
*[Pal/include/do-rel.h, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpIhsDEAjIQhfp2JWX:-MhpIhsEAPEmtx6cYtWm:bvlduo2) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/Pal/include/do-rel.h#L28)):*
> ```objc
>         return;
> 
>     if (!reladdr)
> ```

Actually, can't we have a valid relocation at zero?
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1016 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpKh3n7KNjgC2hpqMP:-MhpKh3o507jw7s1H7WD:b-64zirp) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1016)):*
> ```C
>     new_file_data_node->parent = file_mht_node;
>     new_file_data_node->node_number = node_number;
>     new_file_data_node->physical_node_number = physical_node_number;
> ```

I don't understand this change. If the old code had an unaligned access, then the new one also has it? I.e. if `&new_file_data_node->node_number` is unaligned, then you can't assign to it (or do anything else with it).


<!-- Sent from Reviewable.io -->

2021-08-24 08:32 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: 6 of 10 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[common/src/string/atoi.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpMp06B4iLVLqoXuCI:-Mhr1mtNE34rAF7ESf_U:b-fsn638) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L128)):*
Because `strtol` emulates the standard behavior, which is:

>If  there  were  no digits at all, strtol() stores the original value of nptr in *endptr (and returns 0).

And `str_to_ulong` is our slightly nicer version that doesn't accept "empty" numbers.
___
*[common/src/string/atoi.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpNdafEkIBqgyCk6uV:-Mhr2YzLEbbOm3uwyjrD:bjupx8h) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L165)):*
> Why not just do the arithmetic normally? These functions are assuming the input is correct.

Good point. And if the input is not correct, it's better to trigger UBSan here. Changed to normal arithmetic.

>Also, I'm not sure how the out value is defined on overflow in these macros? The documentation doesn't specify this :/

It's defined as performing the operation at infinite precision and then downcasting. I'm guessing for normal 2s complement arithmetic it should be equivalent to 2s complement signed overflow.
___
*[common/src/string/strlen.c, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhTthQI9RrwK1Lu9yB8:-Mhr4GWx3WF35Ks2CFfJ:bpby6tf) ([raw file](https://github.com/oscarlab/graphene/blob/398727edcee3f8e29c050d2cfdcc7a79d7387e5d/common/src/string/strlen.c#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please update LICENSE.addendum.txt
</blockquote></details>

`atoi.c` also looks like it has no glibc code anymore. I removed both from `LICENSE.addendum.txt` and removed the license header from `atoi.c`.
___
*[LibOS/shim/src/fs/shim_fs_mem.c, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhTtUThBBAAxWGU7L03:-Mhr4nHP0xu9aAoq60Jj:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/LibOS/shim/src/fs/shim_fs_mem.c#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`file_off_t` -> `type`
</blockquote></details>

Fixed.
___
*[Pal/include/do-rel.h, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpIhsDEAjIQhfp2JWX:-Mhr4ybZEel4sF0vcKrF:b-klqqb) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/Pal/include/do-rel.h#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, can't we have a valid relocation at zero?
</blockquote></details>

I don't think it can (this is an array of relocation records, not relocation targets), but I don't know enough to rule it out.

I changed the condition to `relsize == 0`, that case should be a no-op anyway (because `r == relative == end`, so the loops do nothing).
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1016 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpKh3n7KNjgC2hpqMP:-MhrAF6d4DAvDwd8JfSL:b-7jpkfr) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1016)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't understand this change. If the old code had an unaligned access, then the new one also has it? I.e. if `&new_file_data_node->node_number` is unaligned, then you can't assign to it (or do anything else with it).
</blockquote></details>

I believe unaligned access to packed struct members (not taking a pointer) is safe. Unfortunately I can't find any guarantees in the documentation, but here's what I found:

* Packed structures are not part of the standard, so the behavior is compiler-specific anyway.
* GCC and Clang's warnings (`-Waddress-for-packed-member`) complain about taking a pointer, but there's no warning about direct access.
  * See also [the discussion about adding this warning](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51628), where it seems to be accepted that:
    >When a program accesses a misaligned member of a packed struct, the compiler generates whatever code is necessary to read or write the correct value.
* UBSan also complains about unaligned pointers, but not unaligned member access.
* GCC and Clang are aware the access is unaligned in such cases, and generate the right code on platforms where it's needed (I checked ARM and RISC-V on Godbolt)
  * It looks like *specifically for ARM on GCC>=9.3* the compiler generates unaligned access (and you can override that with `-mno-unaligned-access`).That's because apparently [unaligned access on ARM is permitted, used to be slower, but isn't slower anymore](https://patchwork.ozlabs.org/project/uboot/patch/4FF16CF2.9090808@kmckk.co.jp/).

Tell me if you have any evidence to the contrary.

But anyway, the alternative is to rewrite the whole protected-files subsystem, isn't it?


<!-- Sent from Reviewable.io -->

2021-08-24 09:35 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[common/src/string/atoi.c, line 128 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpMp06B4iLVLqoXuCI:-MhrP1Dm5Gt5gUDadWUQ:b8339qs) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L128)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Because `strtol` emulates the standard behavior, which is:

>If  there  were  no digits at all, strtol() stores the original value of nptr in *endptr (and returns 0).

And `str_to_ulong` is our slightly nicer version that doesn't accept "empty" numbers.
</blockquote></details>

Ah, right, I missed that this one is our custom ;)
___
*[common/src/string/atoi.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpNdafEkIBqgyCk6uV:-MhrPBj_6ltEDyWELhoh:b-gv9cel) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L165)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

> Why not just do the arithmetic normally? These functions are assuming the input is correct.

Good point. And if the input is not correct, it's better to trigger UBSan here. Changed to normal arithmetic.

>Also, I'm not sure how the out value is defined on overflow in these macros? The documentation doesn't specify this :/

It's defined as performing the operation at infinite precision and then downcasting. I'm guessing for normal 2s complement arithmetic it should be equivalent to 2s complement signed overflow.
</blockquote></details>

Yeah, but downcasting is not defined for signed overflow case and 2s complement is not guaranteed?
___
*[Pal/include/do-rel.h, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpIhsDEAjIQhfp2JWX:-MhrPafV4bKMrFGRT-d5:b-ezjh3d) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/Pal/include/do-rel.h#L28)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I don't think it can (this is an array of relocation records, not relocation targets), but I don't know enough to rule it out.

I changed the condition to `relsize == 0`, that case should be a no-op anyway (because `r == relative == end`, so the loops do nothing).
</blockquote></details>

That's better :)
___
*[Pal/src/host/Linux-SGX/protected-files/protected_files.c, line 1016 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpKh3n7KNjgC2hpqMP:-MhrTEn5EFUSYGJt2Z7v:b-lwhpfm) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1016)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

I believe unaligned access to packed struct members (not taking a pointer) is safe. Unfortunately I can't find any guarantees in the documentation, but here's what I found:

* Packed structures are not part of the standard, so the behavior is compiler-specific anyway.
* GCC and Clang's warnings (`-Waddress-for-packed-member`) complain about taking a pointer, but there's no warning about direct access.
  * See also [the discussion about adding this warning](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51628), where it seems to be accepted that:
    >When a program accesses a misaligned member of a packed struct, the compiler generates whatever code is necessary to read or write the correct value.
* UBSan also complains about unaligned pointers, but not unaligned member access.
* GCC and Clang are aware the access is unaligned in such cases, and generate the right code on platforms where it's needed (I checked ARM and RISC-V on Godbolt)
  * It looks like *specifically for ARM on GCC>=9.3* the compiler generates unaligned access (and you can override that with `-mno-unaligned-access`).That's because apparently [unaligned access on ARM is permitted, used to be slower, but isn't slower anymore](https://patchwork.ozlabs.org/project/uboot/patch/4FF16CF2.9090808@kmckk.co.jp/).

Tell me if you have any evidence to the contrary.

But anyway, the alternative is to rewrite the whole protected-files subsystem, isn't it?
</blockquote></details>

That's quite an interesting problem, I didn't consider that this may be somehow specified for non-pointer accesses, but you may be right, as the compiler knows in all such cases that the access is unaligned and it can emit proper instructions for it. The unsolvable case is only with pointers, which can be passed to functions which are allowed to assume that they are aligned.

I also checked some more RISCy archs and GCC splits the writes/reads into single-byte accesses there, so it seems to be aware of this problem and handles it properly.

So, it seems to be legal, although not explicitly allowed in the documentation.


<!-- Sent from Reviewable.io -->

2021-08-24 10:14 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[common/src/string/atoi.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpNdafEkIBqgyCk6uV:-Mhrd4jXCOQksBND95q9:b-kwb80b) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L165)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, but downcasting is not defined for signed overflow case and 2s complement is not guaranteed?
</blockquote></details>

Oh. So probably there's no guarantees about the result, but at least the compiler doesn't treat it as UB.


<!-- Sent from Reviewable.io -->

2021-08-24 13:54 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[common/src/string/atoi.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpNdafEkIBqgyCk6uV:-MhsQxwM4XTgFB78ur88:b-4sjsxw) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L165)):*
Which contradicts their own statement, hehe :)

> these built-in functions have fully defined behavior for all argument values.


<!-- Sent from Reviewable.io -->

2021-08-28 18:58 UTC, boryspoplawski requested changes
> Reviewed 6 of 9 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[common/src/string/strlen.c, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCEW356gsWkMFFBSRe:-MiCEW361_C4Y-Bzc8vZ:bfwmgot) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/common/src/string/strlen.c#L8)):*
> ```C
> #include "api.h"
> 
> /* Find the length of S, but scan at most MAXLEN characters.  If no
> ```

Please change to our code guidelines and use actual arg names (`str`, `maxlen`).
___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCtlBf5-gXNwAYQRRU:-MiCtlBgAssw9uPt7sJo:brj9n12) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L27)):*
> ```C
>     size_t path_len = strlen(path);
>     size_t total_msg_size = get_ipc_msg_size(sizeof(msgin) + path_len + 1);
>     struct shim_ipc_msg* msg = __alloca(total_msg_size);
> ```

Not blocking cause it's unrelated, but we should use `malloc` here.
___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 67 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCtqK44up-ssQ2itKs:-MiCtqK44up-ssQ2itKt:b-7ropln) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L67)):*
> ```C
>     size_t path_len = strlen(path);
>     size_t total_msg_size = get_ipc_msg_size(sizeof(msgin) + path_len + 1);
>     struct shim_ipc_msg* msg = __alloca(total_msg_size);
> ```

ditto
___
*[Pal/src/host/Linux/db_memory.c, line 222 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCwDcl8d_xLSHuHdxt:-MiCwDcl8d_xLSHuHdxu:b-ypft4m) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/Pal/src/host/Linux/db_memory.c#L222)):*
> ```C
>             ret = parse_line(buf, vdso_start, vdso_end);
>             if (ret < 0)
>                 goto out;
> ```

`unix_to_pal_error` missing


<!-- Sent from Reviewable.io -->

2021-08-30 08:56 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski)

___
*[common/src/string/atoi.c, line 165 at r1](https://reviewable.io/reviews/oscarlab/graphene/2657#-MhpNdafEkIBqgyCk6uV:-MiLCNPw7DcbOtFgsRBg:b-2mvtln) ([raw file](https://github.com/oscarlab/graphene/blob/d5b585794ea7b351254d90d7436d7bbd91ba0587/common/src/string/atoi.c#L165)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Which contradicts their own statement, hehe :)

> these built-in functions have fully defined behavior for all argument values.
</blockquote></details>

I read "fully defined behavior" as something like "we won't tell you what it is, but we won't assume it never happens and optimize something out". And it's *probably* deterministic...
___
*[common/src/string/strlen.c, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCEW356gsWkMFFBSRe:-MiLDBpPE89mn5-vTgbx:b-uj6w85) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/common/src/string/strlen.c#L8)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Please change to our code guidelines and use actual arg names (`str`, `maxlen`).
</blockquote></details>

Actually I'd rather just remove this comment. This is just standard behavior, and we don't include documentation other standard functions (`strlen`, `strcmp` etc.)
___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCtlBf5-gXNwAYQRRU:-MiLDvf154JI4c64fVLg:b-aq3v0j) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Not blocking cause it's unrelated, but we should use `malloc` here.
</blockquote></details>

Acknowledged, but I don't want to fix it now, especially since all of the IPC code uses alloca for the messages.
___
*[Pal/src/host/Linux/db_memory.c, line 222 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCwDcl8d_xLSHuHdxt:-MiLFavRBBdjVnfTBVpD:b-b41tke) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/Pal/src/host/Linux/db_memory.c#L222)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

`unix_to_pal_error` missing
</blockquote></details>

Oh, I see we use PAL errors in this code, including helper functions (`read_proc_meminfo`). I changed `parse_line` to also return PAL errors.


<!-- Sent from Reviewable.io -->

2021-08-30 11:16 UTC, dimakuv requested changes
> Reviewed 4 of 9 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @boryspoplawski and @pwmarcz)

___
*[LibOS/shim/test/regression/Makefile, line 160 at r3](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiLkXUCAGmKzNJqQXwP:-MiLkXUCAGmKzNJqQXwQ:bilyyv0) ([raw file](https://github.com/oscarlab/graphene/blob/5f2e82df75fab557614370271c6ab931618e82f5/LibOS/shim/test/regression/Makefile#L160)):*
> ```Makefile
> 
> ifeq ($(findstring clang,$(CC)),clang)
> CFLAGS-openmp = -fopenmp=libgomp
> ```

In the commit message you write: `Make sure we still use our patched libgomp.` What does it mean? What does Clang try to use by default?


<!-- Sent from Reviewable.io -->

2021-08-30 11:18 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @pwmarcz)

___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCtlBf5-gXNwAYQRRU:-MiLlTvY7w4z8jUM7F7z:b-u278kk) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L27)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Acknowledged, but I don't want to fix it now, especially since all of the IPC code uses alloca for the messages.
</blockquote></details>

That's not true, most of the IPC code uses `malloc` when sending, only IPC worker thread callbacks use `alloca`.


<!-- Sent from Reviewable.io -->

2021-08-30 11:37 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/ipc/shim_ipc_fs_lock.c, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiCtlBf5-gXNwAYQRRU:-MiLovxi3cJgxjqJ_Us3:b-3mg8g0) ([raw file](https://github.com/oscarlab/graphene/blob/e012c1184127d9b025bf634cc8b4bde85c63cec8/LibOS/shim/src/ipc/shim_ipc_fs_lock.c#L27)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

That's not true, most of the IPC code uses `malloc` when sending, only IPC worker thread callbacks use `alloca`.
</blockquote></details>

Oh, I see. I grepped for `total_msg_size` but there's also code that uses `msg_size`.
___
*[LibOS/shim/test/regression/Makefile, line 160 at r3](https://reviewable.io/reviews/oscarlab/graphene/2657#-MiLkXUCAGmKzNJqQXwP:-MiLp96L3x4kLtj8D1MJ:b991wvq) ([raw file](https://github.com/oscarlab/graphene/blob/5f2e82df75fab557614370271c6ab931618e82f5/LibOS/shim/test/regression/Makefile#L160)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In the commit message you write: `Make sure we still use our patched libgomp.` What does it mean? What does Clang try to use by default?
</blockquote></details>

It uses `libomp.so` which comes from LLVM.


<!-- Sent from Reviewable.io -->

2021-08-30 13:32 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-08-30 13:56 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-30 13:59 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-30 14:08 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2657)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-30 14:10 UTC, merged