[Pal/Linux-SGX] Fix memory leak issues flagged by Klocwork
oscarlab/graphene pull request #2658
Opened 2021-08-21 05:47 UTC by aneessahib

Following issues are addressed 

Possible memory leak. Dynamic memory stored in 'application_path' allocated through function 'malloc' at line 161 can be lost at line 199
graphene/Pal/src/host/Linux-SGX/sgx_process.c:199 | sgx_init_child_process()

Possible memory leak. Dynamic memory stored in 'd1' allocated through function '_DkStreamSecureSave' at line 139 can be lost at line 153. 
graphene/Pal/src/host/Linux-SGX/db_streams.c:153 | handle_serialize()

2021-08-21 22:08 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhekFLGAVDB9s9HPVMl:-MhekFLGAVDB9s9HPVMm:b-xny329) ([raw file](https://github.com/oscarlab/graphene/blob/c9a75c0a650848945dc5811614ec4bef558601fa/-- commits#L5)):*
Could you merge this into one commit? You even already use plural form here ;)
You can force push when doing so (this change is simple, so it shouldn't annoy other reviewers).


<!-- Sent from Reviewable.io -->

2021-08-23 06:30 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhekFLGAVDB9s9HPVMl:-Mhlgu579N8II6amg-Hj:bub7obu) ([raw file](https://github.com/oscarlab/graphene/blob/c9a75c0a650848945dc5811614ec4bef558601fa/-- commits#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you merge this into one commit? You even already use plural form here ;)
You can force push when doing so (this change is simple, so it shouldn't annoy other reviewers).
</blockquote></details>

Done, that should be it then ;)


<!-- Sent from Reviewable.io -->

2021-08-24 09:41 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhrX5WXA0Sg7CSqERKt:-MhrX5WY89abnTfQYYxH:b4nnv0) (no related file):*
Could you reformat the PR description? Hard to read without Markdown.

---
___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhekFLGAVDB9s9HPVMl):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Done, that should be it then ;)
</blockquote></details>

What happened to the commit message here? ;)


<!-- Sent from Reviewable.io -->

2021-08-24 10:44 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhrX5WXA0Sg7CSqERKt:-MhrkCp-EilcN2FxCp39:b-ko7v0) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you reformat the PR description? Hard to read without Markdown.
</blockquote></details>

better now?

---
___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhekFLGAVDB9s9HPVMl):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What happened to the commit message here? ;)
</blockquote></details>

Yikes ! missed to check. Hopefully fine now.


<!-- Sent from Reviewable.io -->

2021-08-24 13:36 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhrX5WXA0Sg7CSqERKt:-MhsMyBzBIIqJWJqN8xg:b-o4difk) (no related file):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

better now?
</blockquote></details>

Yep :) You could also use single/triple backticks in some places, but it's good enough now.

---
___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene/2658#-MhekFLGAVDB9s9HPVMl):*
<details><summary><i>Previously, aneessahib wrote…</i></summary><blockquote>

Yikes ! missed to check. Hopefully fine now.
</blockquote></details>

Yep, looks good now :)


<!-- Sent from Reviewable.io -->

2021-08-24 14:15 UTC, pwmarcz approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-28 13:17 UTC, boryspoplawski submitted a review, later dismissed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-28 13:17 UTC, boryspoplawski commented
Jenkins, test this please

2021-08-30 14:14 UTC, mkow commented
Jenkins, retest this please

2021-08-30 14:14 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-08-30 14:19 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-30 14:34 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2658)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-08-30 15:33 UTC, merged