Refactor sysfs to improve sanitization
oscarlab/graphene pull request #2661
Opened 2021-08-24 04:20 UTC by vijaydhanraj

## Description of the changes 
This PR refactors sysfs to improve sanitization. It fixes issues 1, 2 listed as part of https://github.com/oscarlab/graphene/issues/2105.

## How to test this PR? 
Please run `sysfs_common` and `proc_common` regression tests.

2021-09-06 16:31 UTC, vijaydhanraj commented
Rebased to latest master with few updates.

2021-09-07 09:38 UTC, dimakuv requested changes
> Reviewed 10 of 19 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2661)* status: all files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizM-Tw1pdVcvyaWnAA):*
We don't use `Pal-SGX` but instead `Pal/Linux-SGX`. This will make sense once we have e.g. `Pal/Windows-SGX` (I know, I know, never gonna happen :)).

Please fix here and in all other commit messages (you can rebase).
___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizMFPR0Becw4ZiReWO):*
`[Pal, LibOS]`
___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizMlpO9m-ulhlwcNW9):*
Just remove this sentence. By the way, we never say "patch", typically we say "commit" or "change".
___
*[-- commits, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizMO42EmmJXhd0aClb):*
`...on untrusted integers` (If I understood correctly)
___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizMUxB2Dric0DGSI1s):*
Sounds weird. I suggest `3. Convert the integers to Linux-formatted strings.` No need to say "before the app actually starts", it is obvious.
___
*[-- commits, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizMsMs7WND1eKbEn6-):*
Sometimes you have `s` on the end of verbs, sometimes without it (e.g., `refactors` vs `reconvert`). Please make uniform.
___
*[-- commits, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizN0AIEO3k_RQdxAV4):*
`to` -> `into`
___
*[-- commits, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizN4BDAd2IFZTezVBE):*
How can this be a separate commit? Doesn't it mean that the previous commit is unusable by itself? (If you `git checkout` that commit, Graphene won't even compile, right?)
___
*[-- commits, line 28 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizNE7x2EzTiE_tlhzC):*
ditto, how can this be a separate commit?
___
*[-- commits, line 36 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizNN7Y9TyoQnhHG7CX):*
Simply `[LibOS] Add...`
___
*[-- commits, line 39 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizNSuC22YjLUIsjfu6):*
Please remove `#2453` (we never put PR numbers, especially given that we're moving to a new org). Also remove `Just adding it back` -- it is obvious.
___
*[common/include/api.h, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizNkE48fI57M-RdqyX:-MizNkE48fI57M-RdqyY:bxyvgi4) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/common/include/api.h#L84)):*
> ```objc
> #define BITS_IN_BYTE                    8
> #define BITS_IN_TYPE(type)              (sizeof(type) * BITS_IN_BYTE)
> #define BITS_TO_INT(nr)                 DIV_ROUND_UP(nr, BITS_IN_TYPE(int))
> ```

For uniformity, it should be `BITS_TO_INTS`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizOSQw5fR5-KBJWX2I:-MizOSQw5fR5-KBJWX2J:b-ll4a83) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
> ```objc
> bool sys_cpu_online_name_exists(struct shim_dentry* parent, const char* name);
> int sys_cpu_online_list_names(struct shim_dentry* parent, readdir_callback_t callback, void* arg);
> int sys_convert_int_to_str(PAL_NUM val, SIZE_QUALIFIER_T size_qual, char* str, int max_len);
> ```

We don't use types for enums. We simply use `int`. So `SIZE_QUALIFIER_T size_qual` -> `int size_qual`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizP4ym7Vhsow1pS861:-MizP4ym7Vhsow1pS862:b5we4mb) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
> ```objc
> bool sys_cpu_online_name_exists(struct shim_dentry* parent, const char* name);
> int sys_cpu_online_list_names(struct shim_dentry* parent, readdir_callback_t callback, void* arg);
> int sys_convert_int_to_str(PAL_NUM val, SIZE_QUALIFIER_T size_qual, char* str, int max_len);
> ```

I dislike `PAL_NUM` type. Let's just replace with `uint64_t`.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizPUTsCvQCwcQqYnPG:-MizPUTsCvQCwcQqYnPH:b-ufqe64) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
> ```objc
> bool sys_cpu_online_name_exists(struct shim_dentry* parent, const char* name);
> int sys_cpu_online_list_names(struct shim_dentry* parent, readdir_callback_t callback, void* arg);
> int sys_convert_int_to_str(PAL_NUM val, SIZE_QUALIFIER_T size_qual, char* str, int max_len);
> ```

Please replace `int max_len` with `size_t size`. This is more common in the C world (see e.g. `man snprintf`)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 212 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizOtUN0MW9WWxpmGkA:-MizOtUN0MW9WWxpmGkB:bp0x0hr) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L212)):*
> ```objc
> int sys_cpu_online_list_names(struct shim_dentry* parent, readdir_callback_t callback, void* arg);
> int sys_convert_int_to_str(PAL_NUM val, SIZE_QUALIFIER_T size_qual, char* str, int max_len);
> int sys_convert_range_info_str(PAL_RES_RANGE_INFO res_range_info, char* str, int max_len,
> ```

`PAL_RES_RANGE_INFO` is a struct. We never pass structs by value, only by reference. So:
`PAL_RES_RANGE_INFO res_range_info` -> `const PAL_RES_RANGE_INFO* res_range_info`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 212 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizPehtDlAGQKz4ncCn:-MizPehtDlAGQKz4ncCo:b-7w0g1g) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L212)):*
> ```objc
> int sys_cpu_online_list_names(struct shim_dentry* parent, readdir_callback_t callback, void* arg);
> int sys_convert_int_to_str(PAL_NUM val, SIZE_QUALIFIER_T size_qual, char* str, int max_len);
> int sys_convert_range_info_str(PAL_RES_RANGE_INFO res_range_info, char* str, int max_len,
> ```

`..._str` -> `..._to_str`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizP2Hi0yGpC0_5TEDU:-MizP2Hi0yGpC0_5TEDV:bp9qp51) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
> ```objc
> int sys_convert_range_info_str(PAL_RES_RANGE_INFO res_range_info, char* str, int max_len,
>                                const char* sep);
> int sys_convert_range_info_bitmap_str(PAL_RES_RANGE_INFO res_range_info, char* str, int max_len);
> ```

ditto (pass by reference)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizPjPg9LQvRlCJqNH8:-MizPjPg9LQvRlCJqNH9:b-7w0g1g) ([raw file](https://github.com/oscarlab/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
> ```objc
> int sys_convert_range_info_str(PAL_RES_RANGE_INFO res_range_info, char* str, int max_len,
>                                const char* sep);
> int sys_convert_range_info_bitmap_str(PAL_RES_RANGE_INFO res_range_info, char* str, int max_len);
> ```

`..._str` -> `..._to_str`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/oscarlab/graphene/2661#-MizPmmM7qtrUH8wRvCu:-MizPmmM7qtrUH8wRvCv:b-hg0xsa) ([raw file](https:/ [...]

2021-09-10 18:15 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: 9 of 20 files reviewed, 38 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizM-Tw1pdVcvyaWnAA):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't use `Pal-SGX` but instead `Pal/Linux-SGX`. This will make sense once we have e.g. `Pal/Windows-SGX` (I know, I know, never gonna happen :)).

Please fix here and in all other commit messages (you can rebase).
</blockquote></details>

:) yes done.
___
*[-- commits, line 11 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMFPR0Becw4ZiReWO):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`[Pal, LibOS]`
</blockquote></details>

Done.
___
*[-- commits, line 13 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMlpO9m-ulhlwcNW9):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just remove this sentence. By the way, we never say "patch", typically we say "commit" or "change".
</blockquote></details>

Done.
___
*[-- commits, line 16 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMO42EmmJXhd0aClb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...on untrusted integers` (If I understood correctly)
</blockquote></details>

yes, done.
___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMUxB2Dric0DGSI1s):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds weird. I suggest `3. Convert the integers to Linux-formatted strings.` No need to say "before the app actually starts", it is obvious.
</blockquote></details>

how about `Convert integers back to Linux-formatted strings in LibOS.`
___
*[-- commits, line 20 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMsMs7WND1eKbEn6-):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sometimes you have `s` on the end of verbs, sometimes without it (e.g., `refactors` vs `reconvert`). Please make uniform.
</blockquote></details>

Done.
___
*[-- commits, line 20 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizN0AIEO3k_RQdxAV4):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`to` -> `into`
</blockquote></details>

Done.
___
*[-- commits, line 24 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizN4BDAd2IFZTezVBE):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How can this be a separate commit? Doesn't it mean that the previous commit is unusable by itself? (If you `git checkout` that commit, Graphene won't even compile, right?)
</blockquote></details>

yes, you are right. I have merged `/proc/cpuinfo to use topo info from PAL_TOPO_INFO` commit and `Update set/get affinity syscall` commit into `Refactor sysfs to improve sanitization`.

I think I can pull out 4th item (`consolidate all topology related ...`) of `Refactor sysfs to improve sanitization` into a separate commit if that helps.
___
*[-- commits, line 28 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizNE7x2EzTiE_tlhzC):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, how can this be a separate commit?
</blockquote></details>

Done.
___
*[-- commits, line 36 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizNN7Y9TyoQnhHG7CX):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Simply `[LibOS] Add...`
</blockquote></details>

Done.
___
*[-- commits, line 39 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizNSuC22YjLUIsjfu6):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `#2453` (we never put PR numbers, especially given that we're moving to a new org). Also remove `Just adding it back` -- it is obvious.
</blockquote></details>

Done.
___
*[common/include/api.h, line 84 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizNkE48fI57M-RdqyX:-MjB-OYz1Ej3jprdccy7:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/common/include/api.h#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For uniformity, it should be `BITS_TO_INTS`
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizOSQw5fR5-KBJWX2I:-MjB1QBo1c8W9PrTeiG8:ba627s7) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't use types for enums. We simply use `int`. So `SIZE_QUALIFIER_T size_qual` -> `int size_qual`.
</blockquote></details>

Done, instead of int I changed it to `uint64_t`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizP4ym7Vhsow1pS861:-MjB1RFy3Zl8YXr2OboK:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I dislike `PAL_NUM` type. Let's just replace with `uint64_t`.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizPUTsCvQCwcQqYnPG:-MjB5_r47FO5t0fKJAsA:b-vej2hw) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `int max_len` with `size_t size`. This is more common in the C world (see e.g. `man snprintf`)
</blockquote></details>

yes, you are right but I put this for uniformity. We have 3 string manipulation functions, `1) sys_convert_int_to_str`,                                            `2) sys_convert_range_info_str` and `3) sys_convert_range_info_bitmap_str`. All these functions use snprintf but for functions 2 and 3 check for negative offsets. Please see  https://github.com/gramineproject/graphene/pull/2661/files#diff-9e25c4e2e0ea819880c207dd80fa7acbeec1f5d1d822502427abd1c2b70a71e4R43 and https://github.com/gramineproject/graphene/pull/2661/files#diff-9e25c4e2e0ea819880c207dd80fa7acbeec1f5d1d822502427abd1c2b70a71e4R111. Having `size_t` type might cause the compiler to convert even `offset` to `unsigned int` and this check will never be less than 0. Given this, I kept as `int max_len` even for  `sys_convert_int_to_str` function.

How about adding an `assert` or condition to check that `max_len` is not negative here? Please note this is an internal LibOS function and we always pass a `#define` positive value here. 
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 212 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizOtUN0MW9WWxpmGkA:-MjB8xrk9UH2ZVxuByXK:b-tyf5hk) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L212)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`PAL_RES_RANGE_INFO` is a struct. We never pass structs by value, o [...]

2021-09-16 13:21 UTC, dimakuv requested changes
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 72 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mjhyg24Bfj1xojCoOr9:-Mjhyg24Bfj1xojCoOrA:bl8x09t) (no related file):*
Given your other PR on `getcpu()` support, what should be the order of merging this PRs?

---
___
*[-- commits, line 16 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMO42EmmJXhd0aClb):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, done.
</blockquote></details>

Actually, I still don't understand step 2. Aren't you supposed to `2. Sanitize CPU/NUMA information based on untrusted integers`? I mean, it's not about `sysfs paths` because at this point you don't have any paths -- you just have an internal representation of the CPU/NUMA topology which is represented as a bunch of integers.

Please reword.
___
*[-- commits, line 18 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMUxB2Dric0DGSI1s):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

how about `Convert integers back to Linux-formatted strings in LibOS.`
</blockquote></details>

Sounds good.
___
*[-- commits, line 24 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizN4BDAd2IFZTezVBE):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, you are right. I have merged `/proc/cpuinfo to use topo info from PAL_TOPO_INFO` commit and `Update set/get affinity syscall` commit into `Refactor sysfs to improve sanitization`.

I think I can pull out 4th item (`consolidate all topology related ...`) of `Refactor sysfs to improve sanitization` into a separate commit if that helps.
</blockquote></details>

No, no need to create a separate commit. This looks good.
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-MjhzAp73vWQMb0mxQHP):*
This is a strange message. What you do here is add a new `realloc_size()` function. I don't see how adding something new is "exposing internal implementation". Am I missing something? Do you have two `realloc_size()` functions now? If yes, then why?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizPUTsCvQCwcQqYnPG:-Mji-qXADcCtwb51geuh:b-kfkrzt) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, you are right but I put this for uniformity. We have 3 string manipulation functions, `1) sys_convert_int_to_str`,                                            `2) sys_convert_range_info_str` and `3) sys_convert_range_info_bitmap_str`. All these functions use snprintf but for functions 2 and 3 check for negative offsets. Please see  https://github.com/gramineproject/graphene/pull/2661/files#diff-9e25c4e2e0ea819880c207dd80fa7acbeec1f5d1d822502427abd1c2b70a71e4R43 and https://github.com/gramineproject/graphene/pull/2661/files#diff-9e25c4e2e0ea819880c207dd80fa7acbeec1f5d1d822502427abd1c2b70a71e4R111. Having `size_t` type might cause the compiler to convert even `offset` to `unsigned int` and this check will never be less than 0. Given this, I kept as `int max_len` even for  `sys_convert_int_to_str` function.

How about adding an `assert` or condition to check that `max_len` is not negative here? Please note this is an internal LibOS function and we always pass a `#define` positive value here. 
</blockquote></details>

I see. Yes, please add an assert then.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 212 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizOtUN0MW9WWxpmGkA:-Mji-vKP8hEHRkzEMjq7:b-8sup06) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L212)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Done. Curious, are you suggesting passing by reference to save stack space? 
</blockquote></details>

Thanks. No, it's not about saving stack space (which of course is also true, but not the main point). We do this because that's the norm in C world, so the C developer who will read `PAL_RES_RANGE_INFO res_range_info` in 5 years from now will immediatelly assume that the type `PAL_RES_RANGE_INFO` is a typedef for some "pointer to some struct", and that `res_range_info` was passed by reference. Of course, quite quickly the developer will figure out this is not the case and will write us some hate mails :)

Basically, this change is to stick to the principle of least surprise. 99.9% of the C code is written this way, and there is no reason in this case to be in that 0.01%.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizPmmM7qtrUH8wRvCu:-Mji1dMk0ZD_K7E5lyPC:b-khvmo) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

There are two types of ranges we encounter, 1) `0-63` to represent a numerical range like the number of cpus online 2) `00000000, ffffffff` to represent bitmap like core_siblings. To convert ranges of 1st type, I have `sys_convert_range_info_to_str` and to convert ranges of 2nd type I have `sys_convert_range_to_cpu_bitmap_str`. 

I have added the below comments to the function declaration as well.

```
/* Converts integers to string. If size qualifier like 'K', 'M' or 'G' is passed, it is appended
 * to the string. */
int sys_convert_int_to_str(uint64_t val, int size_qual, char* str, int max_len);

/* Converts integer ranges to string. For example if ranges.start and ranges.end were 0 and 63
 * respectively, then `0-63` string is generated. */
int sys_convert_range_to_str(const PAL_RES_RANGE_INFO* res_range_info, char* str, int max_len,
                             const char* sep);

/* Converts integer ranges to cpu bitmap strings. For example, if ranges.start and ranges.end were
 * 32 and 63, then `ffffffff,00000000` string is generated */
int sys_convert_range_to_cpu_bitmap_str(const PAL_RES_RANGE_INFO* res_range_info, char* str,
                                        int max_len);
```
</blockquote></details>

OK. Thanks, the comments help.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 216 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji12EYDeb4Sy03kmfw:-Mji12EYDeb4Sy03kmfx:b7dfw6s) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/include/shim_fs_pseudo.h#L216)):*
> ```objc
> int sys_convert_int_to_str(uint64_t val, uint64_t size_mult, char* str, int max_len);
> 
> /* Converts integer ranges to a string. For example if ranges.start and ranges.end were 0 and 63
> ```

Why do you say `ranges`? Isn't it just one range that you convert? If it's just one range, why do you say `ranges.start`/`ranges.end` (and not e.g. `range.start`)?

If it is not one range but an array of ranges, please specify it in the comment (and also give a better example, like `0-63,64-127` string is generated).

UPDATE: I looked at the code. So this is an array of ranges. Please update your comment to make it more explicit that this is an array, e.g., describe an example with two ranges. Also, the function name is misleading, right? It should be `sys_convert_ranges_to_str` (notice the plural).
___
*[LibOS/ [...]

2021-09-20 18:28 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 71 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mjhyg24Bfj1xojCoOr9:-Mjk_7pw9TZZxM-dO5YH:befv39g) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Given your other PR on `getcpu()` support, what should be the order of merging this PRs?
</blockquote></details>

I prefer to merge in the following order,
1. Refactor sysfs to improve sanitization (as we do have some TODOs in `getcpu()` PR with respect to sanitization which this one will address)
2. Add checkpoint-and-restore support for sysfs
3. Finally, `getcpu()` PR.

---
___
*[-- commits, line 16 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizMO42EmmJXhd0aClb):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, I still don't understand step 2. Aren't you supposed to `2. Sanitize CPU/NUMA information based on untrusted integers`? I mean, it's not about `sysfs paths` because at this point you don't have any paths -- you just have an internal representation of the CPU/NUMA topology which is represented as a bunch of integers.

Please reword.
</blockquote></details>

I meant sanitization of untrusted integers read from sysfs paths, but I see that it isn't clear. Will make it more explicit as you have suggested.
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-MjhzAp73vWQMb0mxQHP):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is a strange message. What you do here is add a new `realloc_size()` function. I don't see how adding something new is "exposing internal implementation". Am I missing something? Do you have two `realloc_size()` functions now? If yes, then why?
</blockquote></details>

Yes, we do. One is defined statically here, https://github.com/gramineproject/graphene/blob/master/LibOS/shim/src/fs/proc/info.c#L57. I tried to expose this internal function to `Linux-SGX pal` as well. How about we change to ` Add realloc API support to Linux-SGX pal`?
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 211 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizPUTsCvQCwcQqYnPG:-MjyWtXF8L4aO2z_UQQY:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L211)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I see. Yes, please add an assert then.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 212 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizOtUN0MW9WWxpmGkA:-MjyXl492zPKOM-lqZ31:bzh1u98) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L212)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks. No, it's not about saving stack space (which of course is also true, but not the main point). We do this because that's the norm in C world, so the C developer who will read `PAL_RES_RANGE_INFO res_range_info` in 5 years from now will immediatelly assume that the type `PAL_RES_RANGE_INFO` is a typedef for some "pointer to some struct", and that `res_range_info` was passed by reference. Of course, quite quickly the developer will figure out this is not the case and will write us some hate mails :)

Basically, this change is to stick to the principle of least surprise. 99.9% of the C code is written this way, and there is no reason in this case to be in that 0.01%.
</blockquote></details>

I see, so the assumption is that if it is a `typedef` struct then it is generally a "pointer to some struct".
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 216 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji12EYDeb4Sy03kmfw:-MjyZK1vCjAWmXFLt_rA:b-6dqfkv) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/include/shim_fs_pseudo.h#L216)):*
>It should be sys_convert_ranges_to_str (notice the plural).

It is not necessary that we always will have multiple ranges. For example, `possible_online_cores` will just have a single range. Another example is numa `online`. But have reworded the comment and changed `range`->`ranges`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 218 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji58A_--KTWf9ypNT7:-Mjyj97I6_cb-PGsTjqX:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/include/shim_fs_pseudo.h#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Use the plural in function name (`ranges`)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 219 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji3npO4ps_K2Bo624G:-MjyiA0E5aSo1uedG9GK:bkldqp) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/include/shim_fs_pseudo.h#L219)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

By the way, what is the need for `sep`? Isn't it always `,` (comma)?
</blockquote></details>

yes, almost everywhere except when representing NUMA distance which is of form `10 20` where we have a space separator.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 221 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji1EEc1UNW1QrQ5WRa:-Mjyhs404rnme2QCG6sp:b3z37ir) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/include/shim_fs_pseudo.h#L221)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you say `ranges`? Isn't it just one range that you convert? If it's just one range, why do you say `ranges.start`/`ranges.end`?
</blockquote></details>

please refer to the earlier comment on this.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 57 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji3Zmj7LZEnf_aPNaL:-MjyjBtA9uWcVhlFP6De:b-1bjpmn) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/src/fs/sys/cache_info.c#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I quite like this new code! Very readable.
</blockquote></details>

thanks :)
___
*[LibOS/shim/src/fs/sys/cpu_info.c, line 16 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji44B-B8Gal8LFfHS-:-MjzVLNI-TH7utQHLjAt:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/src/fs/sys/cpu_info.c#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No reason to `= 0`. But not blocking.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 47 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizTOd_8L023-oInnH1:-Mk2BC9yB8b1YiRAxnHl:b5r6qfw) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/src/fs/sys/fs.c#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, two things.

1. Why magic value of `UINT64_MAX`? If you have a range consisting of only one value, then you can always specify `ranges[0].start = ranges[0].end = 20`, which gives you the single value `20`.  [...]

2021-09-21 16:25 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 72 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8AK_W0y2DlOYRXyJF:-Mk8AK_W0y2DlOYRXyJG:b-ht2dhp) (no related file):*
@vijaydhanraj Did you forget to push the new changes?

---


<!-- Sent from Reviewable.io -->

2021-09-21 16:43 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: 11 of 20 files reviewed, 72 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8AK_W0y2DlOYRXyJF:-Mk8EL2F0HCZ2sbHHeU1:b-woxs5l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj Did you forget to push the new changes?
</blockquote></details>

oh, I am sorry, just forced pushed the changes since we changed commit messages.

---


<!-- Sent from Reviewable.io -->

2021-09-21 18:17 UTC, dimakuv requested changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 31 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mjhyg24Bfj1xojCoOr9:-Mk8Zw8m3JLDdwukE_27:b-9rpwze) (no related file):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I prefer to merge in the following order,
1. Refactor sysfs to improve sanitization (as we do have some TODOs in `getcpu()` PR with respect to sanitization which this one will address)
2. Add checkpoint-and-restore support for sysfs
3. Finally, `getcpu()` PR.

</blockquote></details>

Got it. Let me block `getcpu` PR then on this.

---
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-MjhzAp73vWQMb0mxQHP):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Yes, we do. One is defined statically here, https://github.com/gramineproject/graphene/blob/master/LibOS/shim/src/fs/proc/info.c#L57. I tried to expose this internal function to `Linux-SGX pal` as well. How about we change to ` Add realloc API support to Linux-SGX pal`?
</blockquote></details>

Ah, I see. Just call this commit
```
[Pal] Add `realloc_size()` in PAL slab manager
```
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 212 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizOtUN0MW9WWxpmGkA:-Mk8DT0o0BXz3uucsgIq:bc6wipe) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L212)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I see, so the assumption is that if it is a `typedef` struct then it is generally a "pointer to some struct".
</blockquote></details>

Yes. The emphasis is though on the word `struct` not on the word `typedef`.

E.g., `typedef uint8_t char` is perfectly fine. But `typedef struct { ... }` -- here devs expect that this is passed as a pointer to functions.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 219 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji3npO4ps_K2Bo624G:-Mk8DldgCzpC85ParfQ3:b-hbzzja) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/include/shim_fs_pseudo.h#L219)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

yes, almost everywhere except when representing NUMA distance which is of form `10 20` where we have a space separator.
</blockquote></details>

OK, got it.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8GLh77XlmGDX7TZAC:-Mk8GLh8BNmFHCfaWVCP:b-6yn6mo) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
> ```objc
> /* Converts integer to a string. If size multiplier like 'K', 'M' or 'G' is passed, it is appended
>  * to the string. */
> int sys_convert_int_to_str(uint64_t val, uint64_t size_mult, char* str, size_t max_len);
> ```

Please replace `max_len` with `size` (or `max_size`).

You're passing not string lengths but string sizes in all call sites (e.g., you pass `sizeof(str)`). The name `len` confused me.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 218 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8GXhGAL4GE1XJ9_8Z:-Mk8GXhGAL4GE1XJ9_8_:b-6yn6mo) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/include/shim_fs_pseudo.h#L218)):*
> ```objc
> /* Converts array of integer range(s) to a string. For example if ranges[0].start and ranges[0].end
>  * were 0 and 63 respectively, then `0-63` string is generated. */
> int sys_convert_ranges_to_str(const PAL_RES_RANGE_INFO* res_range_info, char* str, size_t max_len,
> ```

Please replace `max_len` with `size` (or `max_size`).

You're passing not string lengths but string sizes in all call sites (e.g., you pass `sizeof(str)`). The name `len` confused me.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 224 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8G_PsEfXe40ZVOCLp:-Mk8G_PsEfXe40ZVOCLq:b-6yn6mo) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/include/shim_fs_pseudo.h#L224)):*
> ```objc
>  * ranges[0].end were 0 and 31 respectively, then `00000000,ffffffff` string is generated. */
> int sys_convert_ranges_to_cpu_bitmap_str(const PAL_RES_RANGE_INFO* res_range_info, char* str,
>                                          size_t max_len);
> ```

Please replace `max_len` with `size` (or `max_size`).

You're passing not string lengths but string sizes in all call sites (e.g., you pass `sizeof(str)`). The name `len` confused me.
___
*[LibOS/shim/src/fs/sys/fs.c, line 91 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji7hjI2RfyNik42wsj:-Mk8EuL16WlzxPXv2CyD:b-e83aeb) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/src/fs/sys/fs.c#L91)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

no, I have `BITS_TO_INTS` macro which is used to calculate the number of integers required to represent a given value which is different than this case.
</blockquote></details>

Well, true. But you have `BITS_IN_TYPE`, you can use it here.
___
*[LibOS/shim/src/fs/sys/fs.c, line 96 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji7lyYE00soFr7Dq2R:-Mk8Eyve5FbxZ8EuCKD7:bx44lsu) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/src/fs/sys/fs.c#L96)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

please see earlier comment.
</blockquote></details>

ditto (use `BITS_IN_TYPE`)
___
*[LibOS/shim/src/fs/sys/fs.c, line 19 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8FYyOEdVmQpyQ7FnV:-Mk8FYyOEdVmQpyQ7FnW:b-8aqlwt) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L19)):*
> ```C
> int sys_convert_int_to_str(uint64_t val, uint64_t size_mult, char* str, size_t max_len) {
>     int ret = 0;
>     assert(max_len > 0);
> ```

This is useless now, because `max_len` is of unsigned type. Please remove.
___
*[LibOS/shim/src/fs/sys/fs.c, line 46 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8Gdbo8g_Gfxf-Ot47:-Mk8Gdbo8g_Gfxf-Ot48:b-9g7u0o) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L46)):*
> ```C
>     size_t offset = 0;
>     for (int64_t i = 0; i < range_cnt; i++) {
>         if (offset > max_len)
> ```

It should be `offset >= max_len`. Otherwise your loop will become infinite.
___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8HSBU-48aK7b8SKcR:-Mk8HSBU-48aK7b8SKcS:btp45av) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L70)):*
> ```C
>                                          size_t max_len) {
>     if (g_pal_control->topo_info.possible_logical_cores.resource_count > INT64_MAX)
>         return -1;
> ```

`-EINVAL`
___
*[LibOS/shim/src/fs/sys/fs.c, line 81 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8HwmU4Mhe8aCUNrZq:-Mk8HwmU4Mhe8aCUNrZr:bm34zws) ([raw file](https://github.com/graminep [...]

2021-09-22 03:02 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 31 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-MjhzAp73vWQMb0mxQHP):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I see. Just call this commit
```
[Pal] Add `realloc_size()` in PAL slab manager
```
</blockquote></details>

OK, done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 212 at r2](https://reviewable.io/reviews/gramineproject/graphene/2661#-MizOtUN0MW9WWxpmGkA:-Mk9Chqr0OvzxCrBJskY:bx40ouy) ([raw file](https://github.com/gramineproject/graphene/blob/8a8758517f3c179203f629d705c024a8380cbede/LibOS/shim/include/shim_fs_pseudo.h#L212)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes. The emphasis is though on the word `struct` not on the word `typedef`.

E.g., `typedef uint8_t char` is perfectly fine. But `typedef struct { ... }` -- here devs expect that this is passed as a pointer to functions.
</blockquote></details>

Got it, thanks for the explanation.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8GLh77XlmGDX7TZAC:-Mk9E1CvEDswEv98vRhL:bq1sf6w) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `max_len` with `size` (or `max_size`).

You're passing not string lengths but string sizes in all call sites (e.g., you pass `sizeof(str)`). The name `len` confused me.
</blockquote></details>

changed `max_len` -> `max_size`
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 218 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8GXhGAL4GE1XJ9_8Z:-Mk9E3MNB6CqkYkbwOBv:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/include/shim_fs_pseudo.h#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `max_len` with `size` (or `max_size`).

You're passing not string lengths but string sizes in all call sites (e.g., you pass `sizeof(str)`). The name `len` confused me.
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 224 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8G_PsEfXe40ZVOCLp:-Mk9EBIZ1A7V06-yqXkW:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/include/shim_fs_pseudo.h#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `max_len` with `size` (or `max_size`).

You're passing not string lengths but string sizes in all call sites (e.g., you pass `sizeof(str)`). The name `len` confused me.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 91 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji7hjI2RfyNik42wsj:-Mk9Eloh3wJHwZc1CpE7:b-nqm8d7) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/src/fs/sys/fs.c#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, true. But you have `BITS_IN_TYPE`, you can use it here.
</blockquote></details>

oh right, yes done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 96 at r3](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mji7lyYE00soFr7Dq2R:-Mk9Eo_96OdBklkG-PYE:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/0dc6f10ed0e5c6ab286f13d0028d7b9fd6a9d144/LibOS/shim/src/fs/sys/fs.c#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (use `BITS_IN_TYPE`)
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 19 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8FYyOEdVmQpyQ7FnV:-Mk9EpdID3T89auJU_sw:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is useless now, because `max_len` is of unsigned type. Please remove.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 46 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8Gdbo8g_Gfxf-Ot47:-Mk9Fw8b7_l82a0nMy85:beczhlk) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It should be `offset >= max_len`. Otherwise your loop will become infinite.
</blockquote></details>

Sorry, how do we run into an infinite loop? The loop only runs `range_cnt` times which is unmodified.

Also, what is the use of `offset == max_len` condition? It is going to be a no-op right?
___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8HSBU-48aK7b8SKcR:-Mk9IvLOAGmZ50iMBkLz:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`-EINVAL`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 81 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8HwmU4Mhe8aCUNrZq:-Mk9WQVP6APzw-oRmV8y:brdgoy4) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You leak `bitmap` here. Simply move this check above the `calloc` code.
</blockquote></details>

yes true, done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 87 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8I2Sc4fCCbC5zwTow:-Mk9Wh6B5KoNNPq_ibLO:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You leak `bitmap` here
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 101 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8GpgJ3XAVTovoizpK:-Mk9GamA-ggB9z0vFbhr:bxkoht6) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It should be `offset >= max_len`. Otherwise your loop will become infinite.
</blockquote></details>

Here the loop only runs until `0`- `num_cpumask-1`. Please clarify.
___
*[LibOS/shim/src/fs/sys/fs.c, line 105 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8HbVw9zA8EMPIO5E9:-Mk9WPXp6aFwwtTfVfPb:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You re-define `ret` here. This will lead to undefined behavior because the outer-scope `ret` (which is returned in the `out` label) will not be initialized...

Please remove the `int` word basically.
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs [...]

2021-09-22 14:02 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 46 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8Gdbo8g_Gfxf-Ot47:-MkCgXWE2oyr0ofFCtEF:b-yuonhn) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L46)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Sorry, how do we run into an infinite loop? The loop only runs `range_cnt` times which is unmodified.

Also, what is the use of `offset == max_len` condition? It is going to be a no-op right?
</blockquote></details>

Oops, my bad, I misread the loop condition.
___
*[LibOS/shim/src/fs/sys/fs.c, line 101 at r4](https://reviewable.io/reviews/gramineproject/graphene/2661#-Mk8GpgJ3XAVTovoizpK:-MkChF_q0mztELNvgYQK:bnygw8d) ([raw file](https://github.com/gramineproject/graphene/blob/8f7fa8fd0b0af9b963cc05a13ebe1dd913f966f4/LibOS/shim/src/fs/sys/fs.c#L101)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

Here the loop only runs until `0`- `num_cpumask-1`. Please clarify.
</blockquote></details>

Ignore me.
___
*[LibOS/shim/src/fs/sys/fs.c, line 101 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCliwR4Kv5iFLe9wIb:-MkCliwR4Kv5iFLe9wIc:b-9glxm0) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/LibOS/shim/src/fs/sys/fs.c#L101)):*
> ```C
>     /* Convert cpumask to strings */
>     size_t offset = 0;
>     for (int64_t j = num_cpumask - 1; j >= 0; j-- ) {
> ```

`j-- )` -> `j--)`
___
*[LibOS/shim/src/fs/sys/fs.c, line 110 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCiW9w0UCj1vo2UjGN:-MkCiW9w0UCj1vo2UjGO:b-ash67b) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/LibOS/shim/src/fs/sys/fs.c#L110)):*
> ```C
>                        (bitmap[j] & 0xf00000) >> 20, (bitmap[j] & 0xf0000) >> 16,
>                        (bitmap[j] & 0xf000) >> 12, (bitmap[j] & 0xf00) >> 8,
>                        (bitmap[j] & 0xf0) >> 4, (bitmap[j] & 0xf), (j == 0) ? "\0" : ",");
> ```

Actually, why so weird? Why do you need to print hex-digit by hex-digit?

`%x` qualifier takes `unsigned int` which is exactly the type of your `bitmap[j]` (32 bits). So you could simply do:
```
snprintf(str + offset, max_size - offset, "%08x%s", bitmap[j], (j == 0) ? "\0" : ",");
```

Or did I miss something? My version seems correct.
___
*[Pal/src/host/Linux-common/topo_info.c, line 109 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCmVVI26W_Hq2pIlwp:-MkCmVVJCBKB5iJ4bSoZ:b-k6sx88) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-common/topo_info.c#L109)):*
> ```C
>             res_info->range_count++;
> 
>             /* Realloc as we identify new range when parsing */
> ```

I'm confused again. Why can't you use `realloc_size()` here?

Are we running in circles? I remember asking you to remove `realloc_size()` and just replace it with this explicit logic everywhere instead. But then I guess you found other places where you wanted to use `realloc_size()` so you re-introduced it again in those places. But you didn't re-introduce `realloc_size()` here?

I mean, if we're using `realloc_size()`, let's use it everywhere we can. If we don't use `realloc_size()`, then we should remove it from everywhere.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 192 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCjvQt59xbf4KgXv3_:-MkCjvQt59xbf4KgXv3a:bwp9yhg) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L192)):*
> ```C
>             return -1;
> 
>         int64_t start = (int64_t)res_info.ranges[i].start;
> ```

I think I already asked but... what's the deal with `int64_t` vs `uint64_t`? Why can't all variables be of type `uint64_t`? Then you won't have these ugly explicit casts and you won't need to do all these checks `blabla > INT64_MAX`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 229 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCnP2IEZ3EFePs9nTR:-MkCnP2IEZ3EFePs9nTS:b-r85trd) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L229)):*
> ```C
>             max_limit = 2; /* Taking HT into account */
>         } else {
>             /* if unified cache then it can range upto total number of cores. */
> ```

`upto` -> `up to`

Or is it correct English? Dictionary tells me `upto` is not a word.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 332 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCng9eEDqVQqgK6WOB:-MkCng9f7Rr7g-r4Y9BI:bf5kock) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L332)):*
> ```C
> }
> 
> static int sanitize_socket_info(PAL_TOPO_INFO topo_info) {
> ```

Just noticed. Why is `topo_info` passed by value? Or am I missing something?
___
*[Pal/src/host/Linux-SGX/db_main.c, line 439 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCkY1oDzQuidCt1wTd:-MkCkY1oDzQuidCt1wTe:bm21kkq) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L439)):*
> ```C
>                     goto out_numa;
>                 }
>                 if (bitmap[index] >> (j % BITS_IN_TYPE(int)) == 1) {
> ```

Wait, is this check correct? You just want to check if bit `j % BITS_IN_TYPE(int)` is set in `bitmap[index]`. But your code checks something else: whether from the upper bits only bit `j % BITS_IN_TYPE(int)` is set. So your check is wrong.

Anyway, the classic way to check if the bit is set: `bitmap[index] & 1U << (j % BITS_IN_TYPE(int))`


<!-- Sent from Reviewable.io -->

2021-09-22 18:13 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: 18 of 20 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/sys/fs.c, line 101 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCliwR4Kv5iFLe9wIb:-MkDOUbtDVB0kL5KM_r0:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/LibOS/shim/src/fs/sys/fs.c#L101)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`j-- )` -> `j--)`
</blockquote></details>

Done.
___
*[LibOS/shim/src/fs/sys/fs.c, line 110 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCiW9w0UCj1vo2UjGN:-MkDOXLs4_sK_CanWxNL:btoqxos) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/LibOS/shim/src/fs/sys/fs.c#L110)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why so weird? Why do you need to print hex-digit by hex-digit?

`%x` qualifier takes `unsigned int` which is exactly the type of your `bitmap[j]` (32 bits). So you could simply do:
```
snprintf(str + offset, max_size - offset, "%08x%s", bitmap[j], (j == 0) ? "\0" : ",");
```

Or did I miss something? My version seems correct.
</blockquote></details>

I am not able to think why I had this logic. So, let us use your suggested approach.
___
*[Pal/src/host/Linux-common/topo_info.c, line 109 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCmVVI26W_Hq2pIlwp:-MkDSGHp4gHdVR3EnZpu:b-tdvu8g) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-common/topo_info.c#L109)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm confused again. Why can't you use `realloc_size()` here?

Are we running in circles? I remember asking you to remove `realloc_size()` and just replace it with this explicit logic everywhere instead. But then I guess you found other places where you wanted to use `realloc_size()` so you re-introduced it again in those places. But you didn't re-introduce `realloc_size()` here?

I mean, if we're using `realloc_size()`, let's use it everywhere we can. If we don't use `realloc_size()`, then we should remove it from everywhere.
</blockquote></details>

I did try this, and it was giving me a linker error. Based on our offline chat it seemed like we needed to modify sources and makefile which was not desired. So ended up using explicit logic instead of `realloc_size()`. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 192 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCjvQt59xbf4KgXv3_:-MkDV6Or4qOswV8TlQ0K:b52wqn4) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think I already asked but... what's the deal with `int64_t` vs `uint64_t`? Why can't all variables be of type `uint64_t`? Then you won't have these ugly explicit casts and you won't need to do all these checks `blabla > INT64_MAX`.
</blockquote></details>

If you see here, https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R207 we compare with `end` with `previous_end` which is initialized to `-1`. 

Again, in couple of places we check against `< 0` like here, https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R234

So in order to maintain consistency, I used `int64_t` everywhere. I think we had a similar situation last time when merging sysfs changes and the consensus was to keep things uniform. 
___
*[Pal/src/host/Linux-SGX/db_main.c, line 229 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCnP2IEZ3EFePs9nTR:-MkDWUFfDOB69PNC-M69:b-896fix) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L229)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`upto` -> `up to`

Or is it correct English? Dictionary tells me `upto` is not a word.
</blockquote></details>

Done.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 332 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCng9eEDqVQqgK6WOB:-MkDeadD4EBXeLbfx-Xl:b-a54za6) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L332)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just noticed. Why is `topo_info` passed by value? Or am I missing something?
</blockquote></details>

Changed this and few other functions as well to pass by reference where `typedef struct` was used.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 439 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCkY1oDzQuidCt1wTd:-MkDbDBdBSwXGoCvfDda:bwe4k0r) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L439)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, is this check correct? You just want to check if bit `j % BITS_IN_TYPE(int)` is set in `bitmap[index]`. But your code checks something else: whether from the upper bits only bit `j % BITS_IN_TYPE(int)` is set. So your check is wrong.

Anyway, the classic way to check if the bit is set: `bitmap[index] & 1U << (j % BITS_IN_TYPE(int))`
</blockquote></details>

Good catch.  Done.


<!-- Sent from Reviewable.io -->

2021-09-23 01:10 UTC, mkow requested changes
> Reviewed 1 of 11 files at r3, 1 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: 18 of 20 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[-- commits, line 3 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF1Gpq5_-FQgIjTvyU):*
missing verb
___
*[-- commits, line 14 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF30mU7cjcs7S0PfYk):*
Please align this to the "R" above (ditto below)
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF4qkODd-mc3sSUXjo:-MkF4qkPBFLnI-j_NTWN:bdajzo3) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
This isn't just a traditional "int to string" as the name suggests. Should be named e.g. like this: `sys_convert_int_to_sizestr`.

> If size multiplier like 'K', 'M' or 'G' is passed

How can a character be passed in `uint64_t` argument? If you want to pass a character then it should be `char`.

> If size multiplier [...] is passed

How can it _not_ be passed? C doesn't have optional arguments...

This whole signature and explanation is very confusing to me (at this point I haven't read the implementation yet, but the header should suffice for the function users).
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 216 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF5vUS03qQHeTBm-UD:-MkF5vUS03qQHeTBm-UE:b-xwgvr0) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L216)):*
> ```
> ranges[0].start and ranges[0].end
> ```

This is pseudocode, right? There's no `ranges` parameter in this function.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 217 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF67bf-ExbVIWPYCmu:-MkF67bf-ExbVIWPYCmv:b8ilgw2) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L217)):*
> ```
> then `0-63` string is generated
> ```

umm, but it's `res_range_info` which has "res" in its name, I'd assume that this is the returned result of the function and the string is its input? But the function name and the comment say otherwise.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF6WU92bNQhBnJ5FHk:-MkF6WU92bNQhBnJ5FHl:b-7ropln) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
> ```objc
> 
> /* Converts array of integer range(s) to a cpu bitmap string. For example, if ranges[0].start and
>  * ranges[0].end were 0 and 31 respectively, then `00000000,ffffffff` string is generated. */
> ```

ditto
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF6YNI2PZSVHBpJ9JQ:-MkF6YNI2PZSVHBpJ9JR:bob2lye) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
> ```objc
> int sys_convert_ranges_to_cpu_bitmap_str(const PAL_RES_RANGE_INFO* res_range_info, char* str,
>                                          size_t max_size);
> ```

Overall: these declarations are super confusing, I just read them and have no idea what would actually happen if I called these functions in my code.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 34 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF7CoF1N8pnfDqOoYT:-MkF7CoF1N8pnfDqOoYU:b-w2gaqk) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/cache_info.c#L34)):*
> ```
> MULTIPLIER_NONE
> ```

Ugh, where did you get that constant from? The header for this function doesn't mention it at all, the type of this argument is `uint64_t` (indicating that maybe I should pass `1`/`1000`/`1000000`?), the description says that I should pass `'K'`/`'M'`/`'G'` or not pass it at all (?), and here you're passing some enum?
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 34 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF8orW2gfYJjR_zh30:-MkF8or_26kCjjS5Gp6f:bt7sb2c) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/cache_info.c#L34)):*
> ```C
>         ret = sys_convert_ranges_to_cpu_bitmap_str(&cache->shared_cpu_map, str, sizeof(str));
>     } else if (strcmp(name, "level") == 0) {
>         ret = sys_convert_int_to_str(cache->level, MULTIPLIER_NONE, str, sizeof(str));
> ```

Why does this multiplier even exists? Wasn't the idea that what host passes should be as simple and normalized as possible? Why not just pass the number of bytes everywhere and just in that int->str function shorten it if it's divisible by some size unit? (for specific rounding rules please check the kernel source)

With current version you have a problem that you may pass to the app things which normal kernel would never pass - e.g. "1024K" instead of "1M", or even things like "1000000000K".

And another problem: what if the untrusted host gives you `LONG_MAX` gigabytes? I think in some places you'll just pass it to the app without erroring out, because you never needed to multiply it, so there was no chance for overflow detection (which will certainly happen in the user app then).
___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkFAubYDl-iP4Rr1Erh:-MkFAubYDl-iP4Rr1Eri:b-jdjup5) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/fs.c#L70)):*
> ```C
>     if (g_pal_control->topo_info.possible_logical_cores.resource_count > INT64_MAX)
>         return -EINVAL;
>     int ret;
> ```

this is declared in a completely random place


<!-- Sent from Reviewable.io -->

2021-09-23 09:48 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkFAubYDl-iP4Rr1Erh:-MkH-jP7-tb9oQeVV98I:bxyy36o) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/fs.c#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this is declared in a completely random place
</blockquote></details>

To expand on @mkow's comment: we (almost always) put `int ret;` as the very first statement of the function.
___
*[Pal/src/host/Linux-common/topo_info.c, line 109 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCmVVI26W_Hq2pIlwp:-MkH07biCsBUSTMDCSuV:b-e5fq72) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-common/topo_info.c#L109)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

I did try this, and it was giving me a linker error. Based on our offline chat it seemed like we needed to modify sources and makefile which was not desired. So ended up using explicit logic instead of `realloc_size()`. 
</blockquote></details>

But in the other place you use `realloc_size()`. Now we have a strange state that some PAL sources use `realloc_size` and some sources don't use it (and instead do the `malloc-memcpy-free` pattern explicitly).

Sorry to go back and forth, but let's remove your newly-introduced `realloc_size` function and replace the only caller of `realloc_size` with the explicit `malloc-memcpy-free` pattern. It doesn't make sense to introduce a function for only one place in the code and (for some obscure reason) to not use this function in other places.

This means that you should drop the commit `[Pal] Add `realloc_size()` in PAL slab manager`.
___
*[Pal/src/host/Linux-SGX/db_main.c, line 192 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCjvQt59xbf4KgXv3_:-MkH1_-RAvYIoKR9GhlC:b-vd0x27) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-SGX/db_main.c#L192)):*
<details><summary><i>Previously, vijaydhanraj (Vijay Dhanraj) wrote…</i></summary><blockquote>

If you see here, https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R207 we compare with `end` with `previous_end` which is initialized to `-1`. 

Again, in couple of places we check against `< 0` like here, https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R234

So in order to maintain consistency, I used `int64_t` everywhere. I think we had a similar situation last time when merging sysfs changes and the consensus was to keep things uniform. 
</blockquote></details>

Well, `previous_end` could be initialized to `0`, and everything would still work.

I still don't get why we have `int64_t`. There must have been a better/more sophisticated reason why we introduced these `int64_t` types in the first place. Or maybe there is no reason at all? Then we should just go back to `uint64_t`, the code will become much simpler.

We already store all CPU/NUMA data as `PAL_NUM` which is `uint64_t`. There seems to be no reason to use `int64_t` and do all these checks like `res_info->range_count > INT64_MAX`...
___
*[Pal/src/host/Linux-SGX/db_main.c, line 360 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkH1QgPDj-3uB_ozToi:-MkH1QgPDj-3uB_ozToj:b-e6bcwb) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/Pal/src/host/Linux-SGX/db_main.c#L360)):*
> ```C
>             size_t new_sz = sizeof(PAL_RANGE_INFO) * socket_info[socket].range_count;
>             size_t old_sz = new_sz - sizeof(PAL_RANGE_INFO);
>             socket_info[socket].ranges = realloc_size(socket_info[socket].ranges, old_sz, new_sz);
> ```

Please replace this call with an explicit `malloc-memcpy-free`.


<!-- Sent from Reviewable.io -->

2021-09-23 11:01 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @vijaydhanraj)

___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkFAubYDl-iP4Rr1Erh:-MkHIo-cEAm5ypBIFiFx:b-vrw50p) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/fs.c#L70)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

To expand on @mkow's comment: we (almost always) put `int ret;` as the very first statement of the function.
</blockquote></details>

Not even this, I would be also fine if it was declared right before the first usage. But here it's declared in a middle of unrelated code...


<!-- Sent from Reviewable.io -->

2021-09-30 13:12 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661)* status: 12 of 20 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[-- commits, line 3 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF1Gpq5_-FQgIjTvyU):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing verb
</blockquote></details>

Rephrased as `Add helper macro to convert bits to integer size`
___
*[-- commits, line 14 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF30mU7cjcs7S0PfYk):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please align this to the "R" above (ditto below)
</blockquote></details>

Done.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 214 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF4qkODd-mc3sSUXjo:-Mkn9zkb8NUAMXBZJ7ii:b-o4fcgu) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L214)):*
Renamed from `sys_convert_int_to_str` to `sys_convert_int_to_sizestr`

>How can a character be passed in uint64_t argument?

I am not passing a character but an `enum` value here.

>How can it not be passed?

My wording might be misleading. What I meant here by "not passing" is that we simply pass a default multiplier like `MULTIPLIER_NONE` instead of the actual `size qualifier`

I have reworded the text as below. Let me know if this makes it clearer.
```
/* Converts integer to a string. When integer representation (enum value) of size multiplier like
 *'K', 'M' or 'G' is passed, it is converted back to string and appended. When the size multiplier 
 * is `MULTIPLIER_NONE`, nothing is appended, and the integer is simply converted to a string. */
```
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 216 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF5vUS03qQHeTBm-UD:-MkoDiTs9GE8tHVsbb-N:b-obsh6x) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L216)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> ranges[0].start and ranges[0].end
> ```

This is pseudocode, right? There's no `ranges` parameter in this function.
</blockquote></details>

I have added the parameter that has `ranges` in the comment to make it clear.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 217 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF67bf-ExbVIWPYCmu:-MkoEdgV7yb4HBGDeSAh:bjhl2e1) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L217)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> then `0-63` string is generated
> ```

umm, but it's `res_range_info` which has "res" in its name, I'd assume that this is the returned result of the function and the string is its input? But the function name and the comment say otherwise.
</blockquote></details>

As the function name indicates we want to convert the integer input (in this case range info) that is part of `res_range_info` to an output string that is stored in `str`.

`res` in this context is for `resource` and not `result` 
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 222 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF6WU92bNQhBnJ5FHk:-MkoFsN5Cjb94LG4m9M5:b-z7sg5q) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L222)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Please refer to the earlier comment.
___
*[LibOS/shim/include/shim_fs_pseudo.h, line 225 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF6YNI2PZSVHBpJ9JQ:-MkoG-mo-6ysAwTMqiCv:bacqc0m) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/include/shim_fs_pseudo.h#L225)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Overall: these declarations are super confusing, I just read them and have no idea what would actually happen if I called these functions in my code.
</blockquote></details>

I have reworded the comments a bit to clarify. Please see it helps. Suggestions are definitely welcome.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 34 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF7CoF1N8pnfDqOoYT:-MkoGwz202EgDBr0D-Zs:bfpj6xc) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/cache_info.c#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> MULTIPLIER_NONE
> ```

Ugh, where did you get that constant from? The header for this function doesn't mention it at all, the type of this argument is `uint64_t` (indicating that maybe I should pass `1`/`1000`/`1000000`?), the description says that I should pass `'K'`/`'M'`/`'G'` or not pass it at all (?), and here you're passing some enum?
</blockquote></details>

I have this `enum` defined in `pal-arch.h`. `pal.h` includes this and it is in turn included in `shim_fs.h`

I have reworded the comments on this function, please take a look and let me know.
___
*[LibOS/shim/src/fs/sys/cache_info.c, line 34 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkF8orW2gfYJjR_zh30:-MkoJKwjEow5cYgXZgS-:bcx9pw1) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/cache_info.c#L34)):*

>Why does this multiplier even exists? 

We have a multiplier because we exactly need to know how the normal kernel is representing the strings. For example, on reading`/sys/devices/system/cpu/cpu2/cache/index3/size we get `49152K`. Now this can be represented as `48M` or `49152K` and in this case, kernel chose the latter representation, and we need to give the same to the end-user.

>With current version you have a problem that you may pass to the app things which normal kernel would never pass - e.g. "1024K" instead of "1M", or even things like "1000000000K".

Please see the earlier comment.

>And another problem: what if the untrusted host gives you LONG_MAX gigabytes?

Please see here (lines `263-267`) https://github.com/gramineproject/graphene/pull/2661/files#diff-cc6f581d340e5e5a512e7693bb560ee623a287dab6d3d24c47410912a2ddd305R263, I do multiply the size qualifier and check the limits when sanitizing so we shouldn't be running into overflow issues in this case. If you see the issue somewhere, please point me to it.
___
*[LibOS/shim/src/fs/sys/fs.c, line 70 at r6](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkFAubYDl-iP4Rr1Erh:-MkoN4FoBxfGvZH5K5Sw:br6q5v0) ([raw file](https://github.com/gramineproject/graphene/blob/48aa4d72df1a368eae26849403801fae11ca7b05/LibOS/shim/src/fs/sys/fs.c#L70)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not even this, I would be also fine if it was declared right before the first usage. But here it's declared in a middle of unrelated code...
</blockquote></details>

I might have removed some code and missed removing/re-arranging the `ret` variable. But fixed this now.
___
*[Pal/src/host/Linux-common/topo_info.c, line 109 at r5](https://reviewable.io/reviews/gramineproject/graphene/2661#-MkCmVVI26W_Hq2pIlwp:-MkoNUT58N7xgKdOKtMM:bntpcvk) ([raw file](https://github.com/gramineproject/graphene/blob/15962c0aa977608a7c3abea5563b856252fbf338/Pal/src/host/Linux-common/topo_info.c#L109)):*
<details><summary><i>Pre [...]

2021-09-30 13:53 UTC, vijaydhanraj reviewed
Addressed the review comments and pushed the changes. Also, as discussed ported this to gramine repository, https://github.com/gramineproject/gramine/pull/106. Please let me know if I should close this one.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/graphene/2661#-:-MkqyWvdCez0pYrUk8mJ:bd26tv6)* status: 12 of 20 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-10-03 02:08 UTC, closed without merging