[LibOS] Return -EISDIR on opening a directory with O_CREAT flag
oscarlab/graphene pull request #2671
Opened 2021-09-01 06:02 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Opening a directory with O_CREAT should fail with -EISDIR instead of success.
Fixes #2550 

## How to test this PR? 
Follow the steps to reproduce mentioned in issue #2550.

2021-09-01 06:16 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2021-09-01 06:17 UTC, mkow commented
Jenkins, test this please

2021-09-01 11:50 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @sahason)

___
*[LibOS/shim/src/fs/shim_namei.c, line 525 at r1](https://reviewable.io/reviews/oscarlab/graphene/2671#-MiWAWWM8bCeA3sU1Uwt:-MiWAWWM8bCeA3sU1Uwu:bn0d1h6) ([raw file](https://github.com/oscarlab/graphene/blob/1ee9f081ecf882833c0e9eb4dd8cdaf9322969ef/LibOS/shim/src/fs/shim_namei.c#L525)):*
> ```C
> 
>     if (dent->type == S_IFDIR) {
>         if (flags & O_WRONLY || flags & O_RDWR || flags & O_CREAT) {
> ```

This is not enough because `open_namei()` is also called by `shim_do_mkdirat()`, see: https://github.com/oscarlab/graphene/blob/6ee2c0b15b4f507c15d15cac733c091080246b04/LibOS/shim/src/sys/shim_file.c#L98

This is way our Jenkins CI failed. Here is what Jenkins complains about:
```
Failed: test_libos.TC_30_Syscall.test_023_readdir
mkdir failed: Is a directory
```

I suggest to distinguish between `man 2 open` and `man 2 mkdir` in here as follows:
```
    if (dent->type == S_IFDIR) {
        if (flags & O_WRONLY || flags & O_RDWR || ((flags & O_CREAT) && !(flags & O_DIRECTORY)) {
            ... same ...
```

In other words, we will return `-EISDIR` if the user syscall requested creation (`O_CREAT`) on a regular file (`!O_DIRECTORY`) but the found path is actually a directory.

@pwmarcz Does this sound reasonable to you?


<!-- Sent from Reviewable.io -->

2021-09-01 13:22 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

___
*[LibOS/shim/src/fs/shim_namei.c, line 525 at r1](https://reviewable.io/reviews/oscarlab/graphene/2671#-MiWAWWM8bCeA3sU1Uwt:-MiWUQceEHhT9Hj3MuqE:blkbsdc) ([raw file](https://github.com/oscarlab/graphene/blob/1ee9f081ecf882833c0e9eb4dd8cdaf9322969ef/LibOS/shim/src/fs/shim_namei.c#L525)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is not enough because `open_namei()` is also called by `shim_do_mkdirat()`, see: https://github.com/oscarlab/graphene/blob/6ee2c0b15b4f507c15d15cac733c091080246b04/LibOS/shim/src/sys/shim_file.c#L98

This is way our Jenkins CI failed. Here is what Jenkins complains about:
```
Failed: test_libos.TC_30_Syscall.test_023_readdir
mkdir failed: Is a directory
```

I suggest to distinguish between `man 2 open` and `man 2 mkdir` in here as follows:
```
    if (dent->type == S_IFDIR) {
        if (flags & O_WRONLY || flags & O_RDWR || ((flags & O_CREAT) && !(flags & O_DIRECTORY)) {
            ... same ...
```

In other words, we will return `-EISDIR` if the user syscall requested creation (`O_CREAT`) on a regular file (`!O_DIRECTORY`) but the found path is actually a directory.

@pwmarcz Does this sound reasonable to you?
</blockquote></details>

Almost. Your condition will also be triggered on `open(O_CREAT | O_EXCL)`, and in that case we want to return `-EEXIST`, not `-EISDIR`. So you need to check for `!(flags & O_EXCL)` as well.


<!-- Sent from Reviewable.io -->

2021-09-02 14:39 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/shim_namei.c, line 525 at r1](https://reviewable.io/reviews/oscarlab/graphene/2671#-MiWAWWM8bCeA3sU1Uwt:-Miai1gJA_MVY3bKVQ16:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1ee9f081ecf882833c0e9eb4dd8cdaf9322969ef/LibOS/shim/src/fs/shim_namei.c#L525)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Almost. Your condition will also be triggered on `open(O_CREAT | O_EXCL)`, and in that case we want to return `-EEXIST`, not `-EISDIR`. So you need to check for `!(flags & O_EXCL)` as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-02 14:46 UTC, mkow commented
Jenkins, retest this please

2021-09-03 07:34 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pwmarcz)

___
*[LibOS/shim/src/fs/shim_namei.c, line 525 at r1](https://reviewable.io/reviews/oscarlab/graphene/2671#-MiWAWWM8bCeA3sU1Uwt:-MieZtx_BY49kGcrfTNd:b-pnv64e) ([raw file](https://github.com/oscarlab/graphene/blob/1ee9f081ecf882833c0e9eb4dd8cdaf9322969ef/LibOS/shim/src/fs/shim_namei.c#L525)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think Pawel meant this:
```
    if (dent->type == S_IFDIR) {
        if (flags & O_WRONLY || flags & O_RDWR ||
                ((flags & O_CREAT) && !(flags & O_DIRECTORY) && !(flags & O_EXCL)) {
            ... same ...
```

@pwmarcz Is that what you wanted?


<!-- Sent from Reviewable.io -->

2021-09-03 12:49 UTC, pwmarcz reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/shim_namei.c, line 525 at r1](https://reviewable.io/reviews/oscarlab/graphene/2671#-MiWAWWM8bCeA3sU1Uwt:-MifgIkC4kk_QghSujuh:b-z8piuj) ([raw file](https://github.com/oscarlab/graphene/blob/1ee9f081ecf882833c0e9eb4dd8cdaf9322969ef/LibOS/shim/src/fs/shim_namei.c#L525)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think Pawel meant this:
```
    if (dent->type == S_IFDIR) {
        if (flags & O_WRONLY || flags & O_RDWR ||
                ((flags & O_CREAT) && !(flags & O_DIRECTORY) && !(flags & O_EXCL)) {
            ... same ...
```

@pwmarcz Is that what you wanted?
</blockquote></details>

Yes. The current condition will still be true for `O_CREAT | O_EXCL` flags, so it's wrong. @dimakuv's proposed fix looks right.


<!-- Sent from Reviewable.io -->

2021-09-06 04:27 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[LibOS/shim/src/fs/shim_namei.c, line 525 at r1](https://reviewable.io/reviews/oscarlab/graphene/2671#-MiWAWWM8bCeA3sU1Uwt:-MitLzxt3T5LhnhfhWY5:b-896fix) ([raw file](https://github.com/oscarlab/graphene/blob/1ee9f081ecf882833c0e9eb4dd8cdaf9322969ef/LibOS/shim/src/fs/shim_namei.c#L525)):*
<details><summary><i>Previously, pwmarcz (Paweł Marczewski) wrote…</i></summary><blockquote>

Yes. The current condition will still be true for `O_CREAT | O_EXCL` flags, so it's wrong. @dimakuv's proposed fix looks right.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-06 08:14 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-06 08:15 UTC, dimakuv commented
Jenkins, test this please

2021-09-06 09:39 UTC, pwmarcz submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2021-09-06 11:33 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-09-06 11:33 UTC, dimakuv commented
Jenkins, test this please

2021-09-06 11:36 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-06 12:06 UTC, pwmarcz approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene/2671)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-06 12:39 UTC, merged